### ISSUE TITLE
yolo export tensorrt, pt to engine

### ISSUE THREAD

**Issue by georgelele1** [ultralytics/ultralytics#10003]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

  File "E:\Yolov8\ultralytics\engine\exporter.py", line 363, in export_onnx
    __version__ = onnx.version.version
AttributeError: module 'torch.onnx' has no attribute 'version'
PyTorch: starting from 'E:\Yolov8\runs\detect\caridentifyyolov8n\caryolov8n\weights\best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 19, 8400) (6.0 MB)
ONNX: export failure ❌ 0.0s: module 'torch.onnx' has no attribute 'version'
TensorRT: export failure ❌ 0.0s: module 'torch.onnx' has no attribute 'version'
ONNX: export failure ❌ 0.2s: module 'torch.onnx' has no attribute 'version'
TensorRT: export failure ❌ 0.2s: module 'torch.onnx' has no attribute 'version'

### Additional

i have tried to reinstall the onnx, reinstall the torchvision but none of that work, i also tried to excute the program with python and CLI both not working mac is working fine with onnx but windows is not functional correctly i want to export to tensorrt format which requried a cuda that my mac does not have so i have to move to windows anyone can helpe resolve the problem
?

**Comment by glenn-jocher** [comment]
Hello! It seems like you're encountering an issue with exporting your model to ONNX and subsequently to TensorRT format on a Windows machine. The specific error mentioning `module 'torch.onnx' has no attribute 'version'` suggests there might be an issue with your PyTorch or ONNX installation that is not directly related to Ultralytics YOLOv8. 

Here's a quick way to address this issue:

1. **Double-check your PyTorch version.** Ensure it's compatible with the ONNX you're trying to use. You can find compatibility information on the [PyTorch official website](https://pytorch.org/).

2. **Reinstall PyTorch and ONNX** using the commands below, making sure they are compatible with each other as well as with your CUDA version for TensorRT export:

    ```bash
    pip install --upgrade torch torchvision
    pip install --upgrade onnx
    ```

3. **Test ONNX separately** to ensure that the issue is not within the ONNX installation:

    ```python
    import onnx
    print(onnx.__version__)
    ```

If the error persists even after ensuring compatibility and successful imports of PyTorch and ONNX, it might be helpful to isolate the problem by attempting a simple model export to ONNX format using base PyTorch functionality, without involving Ultralytics YOLO code. This can help determine whether the issue lies with the setup or the specific export process:

```python
import torch
model = torch.load('path_to_your_model/model.pt')
dummy_input = torch.randn(1, 3, 640, 640)
torch.onnx.export(model, dummy_input, "model.onnx")
```

If the simple PyTorch export works, but YOLOv8's export doesn't, it might be a specific compatibility issue with the Ultralytics export script. In such a case, ensuring that all library versions (PyTorch, ONNX, torchvision) are up to date, and reviewing any recent Ultralytics YOLOv8 updates for compatibility notes would be the next steps.

Feel free to follow up if the issue persists after trying these steps! 🚀

**Comment by georgelele1** [comment]
Forcing --batch-size 1 square inference (1,3,640,640) for non-PyTorch models
val: Scanning E:\Datasets\cardatasets\cardataset\labels\val... 9477 images, 23 backgrounds, 0 corrupt: 100%|██████████| 9477/9477 [00:04<00:00, 2012.63it/s]
val: WARNING  Cache directory E:\Datasets\cardatasets\cardataset\labels is not writeable: [WinError 183] : 'E:\\Datasets\\cardatasets\\cardataset\\labels\\val.cache.npy' -> 'E:\\Datasets\\cardatasets\\cardataset\\labels\\val.cache'
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|          | 0/9477 [00:00<?, ?it/s]Error executing job with overrides: ['task=detect', 'mode=val', 'model=E:\\Yolov8\\runs\\detect\\caridentify\\caryolov8n\\weights\\best.onnx', 'data=E:\\Yolov8\\ultralytics\\cfg\\datasets\\vichel.yaml', 'batch=80']
Traceback (most recent call last):

<img width="1412" alt="image" src="https://github.com/ultralytics/ultralytics/assets/43303561/91606cae-b346-4734-9289-131afd26fd3d">

This is still not working my torch vision is 2.2.2+cu121 and onnx version is 1.16.0 i have really struglling with the issue and there is no guideline!

**Comment by glenn-jocher** [comment]
Hey there! 🌟 It looks like you're encountering a cache writeability issue alongside an error while executing a validation job. The cache warning suggests that the directory specified for caching is not writable, which can happen if you don't have the necessary permissions or if there's an existing file that cannot be overwritten due to system permissions.

For the cache issue, please ensure that your user has write permissions to the `E:\Datasets\cardatasets\cardataset\labels\` directory. You might need to manually check the folder properties or run your script/command prompt as an administrator.

Regarding the error executing the job with overrides, since you're using a non-PyTorch model (ONNX) for evaluation, ensure that the conversion was successful and that the model file isn't corrupted. Given the versions of torchvision (`2.2.2+cu121`) and ONNX (`1.16.0`) you're using, they seem up to date. However, double-check if these versions are compatible with your PyTorch version as well.

If you've verified permissions and compatibility and the issue persists, a simple workaround for debugging could involve using a simpler command without caching or trying with a smaller subset of your dataset to pinpoint the problem.

If you're still stuck, could you provide a bit more detail about the command you're running that leads to this error? It might provide more context for troubleshooting. Also, ensure there's enough disk space and no file lock issues, which can sometimes cause such errors.

Keep us posted, and we're here to help you sail through! 🚀

**Comment by georgelele1** [comment]
i have got some progress and it i have a more detailed info about the issue i have faced it seems that i have the tensorrt with the anaconda envs and everthing set up but i am facing some of the issue related to the nvidia- tensorrt i tried the export function with yolov5 and 8 it have different error for v8 it looks like this :
<img width="1406" alt="image" src="https://github.com/ultralytics/ultralytics/assets/43303561/ef276f0f-65b1-4a41-997b-d9a7b0bb076a">
And for v5 :
<img width="1413" alt="image" src="https://github.com/ultralytics/ultralytics/assets/43303561/9bf3462d-3cca-4955-9dcc-c9a99066a77e">
it looks like this and for clearfiy i also i have checked my envs see if it is compatable following is the envs info about tensorrt and torch, my Cuda is 12.4:
<img width="1413" alt="image" src="https://github.com/ultralytics/ultralytics/assets/43303561/1a5ef783-88fc-40f8-b6d8-c529eb95666f">
GOOD news is i can run onnx and val the onnx model not but tensorrt is still not working correctly! Looking forward to your help and thanks for all the support!

**Comment by georgelele1** [comment]
also when i tried to install the nvidia-tensorrt it gives me the following error:
<img width="1414" alt="image" src="https://github.com/ultralytics/ultralytics/assets/43303561/acc0750f-0bf7-446a-8b5c-b821a27456ac">
cant find solution to that via google

**Comment by glenn-jocher** [comment]
@georgelele1 hi there! 🙌 It looks like you're encountering an installation issue with NVIDIA TensorRT. This might be related to compatibility with your current CUDA version or specific package availability for your system.

One common step that often helps is making sure that your `pip` is up-to-date. This ensures that the latest package indexes are used when attempting to install packages:

```bash
pip install --upgrade pip
```

After updating `pip`, you can try installing the NVIDIA TensorRT package again. Additionally, consider checking the [NVIDIA official documentation](https://developer.nvidia.com/tensorrt) or [TensorRT PyPI page](https://pypi.org/project/nvidia-tensorrt/) for any version-specific installation instructions that might be relevant to your setup.

If the direct installation continues to fail, it may help to download the specific TensorRT package compatible with your CUDA version from the [NVIDIA Developer site](https://developer.nvidia.com/nvidia-tensorrt-download) and follow the installation instructions provided there.

Keep us posted on your progress! If you encounter any more hurdles, we're here to assist. Happy coding! 😊
