### ISSUE TITLE
How to load the model optimizer object 

### ISSUE THREAD

**Issue by nahidalam** [ultralytics/ultralytics#10021]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to train with a new optimizer for which I basically need to do this
```
mode.train()
optimizer.train()
...
model.eval()
optimizer.eval()
```

How do I load this optimizer object in the context of yolov8?
I tried this
```
from ultralytics import YOLO
model = YOLO("yolov8n-seg.pt")  
training_results = model.train(...)
optimizer = model.trainer.optimizer
optimizer.train()
```
This gives me error `AttributeError: 'SegmentationTrainer' object has no attribute 'optimizer'`

I also tried `optimizer = model["optimizer"]` but get error `TypeError: 'YOLO' object is not subscriptable`

Please suggest

**Comment by glenn-jocher** [comment]
Hello! 👋 It looks like you're trying to customize the optimizer behavior during your model's training with YOLOv8. Providing direct external access to the optimizer object isn't straightforward because Ultralytics YOLO implementation abstracts the training loop, including the optimizer's state transitions between train and eval modes, for ease of use and to minimize the setup for training.

However, you can customize the optimizer by defining it in your custom training script or the dataset configuration YAML file. For significant modifications or to explicitly set the optimizer mode (`.train()`, `.eval()`), you might need to adapt the training loop, which would involve more in-depth customization of the library's source code.

If the aim is to modify optimizer parameters or use a completely different optimizer, you could potentially achieve this by overriding the default settings in the YAML configuration file or by modifying the source code where the optimizer is initialized in the training process. Unfortunately, direct manipulation of the optimizer's train/evaluation mode outside the provided training process is not supported in the high-level API.

For more controlled training procedures and to include specific optimizer behaviors, consider integrating YOLOv8's model within a custom PyTorch training loop, where you have full control over the model and optimizer states.

If you still need to adjust the optimizer or its state, looking into the `train.py` script (or the relevant training script for the model you're working with) in the Ultralytics GitHub repo could offer more insights on how the training loop is structured and how best to implement your specific requirements.

Here's an example snippet for a more customized training loop, where you have control over the optimizer:
```python
import torch
from ultralytics import YOLO, load_dataset

# Load model and dataset
model = YOLO('yolov8n.pt')
dataset = load_dataset("path/to/your/dataset.yaml")

# Define a custom optimizer
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

for epoch in range(num_epochs):
    model.train()
    optimizer.zero_grad()
    # Your training loop here
    loss.backward()
    optimizer.step()

    # When evaluating
    model.eval()
    # Evaluation loop here
```
Keep in mind, the example above is quite simplified and intended to illustrate integrating the YOLO model into a PyTorch training loop where you exercise full control.

For more detailed implementation and possibly integrating YOLOv8's advanced features, diving into the source might be required. Don't hesitate to share your progress or further questions in the discussions! Good luck with your project! 🚀
