### ISSUE TITLE
modify standard yolov8 learning rate

### ISSUE THREAD

**Issue by ahmedfarouk99** [ultralytics/ultralytics#10052]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

here is my steps in order:
1- i created venv in my local pc "py -3.9 -m venv yolo_customconfig"
2- i activated the venv "yolo_custom/Scripts/activate"
3- git clone https://github.com/ultralytics/ultralytics.git
4- cd ultralytics
5- pip install -e.
6- i installed torch to enable GPU
7- i modified "F:\yolov8_customconfig\ultralytics\ultralytics\engine\trainer.py" file to add cyclic LR 
8- i modified "F:\yolov8_customconfig\ultralytics\ultralytics\cfg\default.yaml" file to add cyclic_lr=True and other hyperparameters
9- i run the code to train my custom dataset in CLI but i got error "ImportError: cannot import name '__version__' from 'ultralytics' (unknown location)" as shown below:
![1](https://github.com/ultralytics/ultralytics/assets/52285797/b5ae73fe-6eef-4962-81a9-f74df209b3c1)

**Comment by ahmedfarouk99** [comment]
@glenn-jocher @Alarmod @WangQvQ

**Comment by glenn-jocher** [comment]
Hi there! It looks like you've encountered an import error during your customization process. This issue might be related to the way the package is installed or the modifications made. Could you please try reinstalling the `ultralytics` package directly inside your activated virtual environment without using `-e` flag, like so:

```bash
pip install .
```

from the `ultralytics` directory? This will ensure the package and its dependencies are correctly installed.

For the cyclic learning rate implementation, ensure that the modifications in `trainer.py` and `default.yaml` are accurately aligned with the existing codebase structure and syntax. If the issue persists, consider sharing the specific changes you've made, which could help in diagnosing the problem more accurately.

Hope this helps! Let us know how it goes. 🚀

**Comment by ahmedfarouk99** [comment]
@glenn-jocher i used " pip install . " but it give me a new command line without starting training as shown below
![1](https://github.com/ultralytics/ultralytics/assets/52285797/26f9a68a-99b7-435a-bb12-341efaeb62ae)

**Comment by glenn-jocher** [comment]
Hi there! It looks like the `pip install .` command installed the package successfully, which is great. 🎉 If the training didn't start right after, it might be because you haven't yet run the specific command to start training. For a YOLOv8 model, you can start training using a command similar to the following (adjust paths and settings as needed for your setup):

```bash
yolo train --data your_dataset.yaml --cfg yolov8.yaml --weights yolov8.weights
```

Make sure you're in the correct directory or specify the full path to the `yolo` command if needed. If you have any specific error messages when you try to start the training, feel free to share them for more precise help!

**Comment by ahmedfarouk99** [comment]
@glenn-jocher i still facing an error and i got confused .....
1- when i wrote that command in CLI [ yolo train --data F:\yolov8custom\ultralytics\data.yaml --cfg F:\yolov8custom\ultralytics\ultralytics\cfg\default.yaml --weights yolov8s.pt  epochs=100 imgsz=640 cyclic_lr=True] , i got that error 
![2](https://github.com/ultralytics/ultralytics/assets/52285797/c37f62c7-8c3c-4498-9f90-8bac1f77ca95)

2-when i modified the command in CLI [ yolo train data='F:\yolov8custom\ultralytics\data.yaml' cfg='F:\yolov8custom\ultralytics\ultralytics\cfg\default.yaml' weights=yolov8s.pt  epochs=100 imgsz=640 cyclic_lr=True], i got that error
![1](https://github.com/ultralytics/ultralytics/assets/52285797/63cf56c7-3817-4de5-bf20-31fe784c9b2e)
however i defined the cyclic_lr in my trainer.py

**Comment by ahmedfarouk99** [comment]
@glenn-jocher thanks for your care an understanding....
1- i checked that each argument is separated by spaces and doesn't use square brackets [].
2- what is meant by " Also, for setting boolean flags like cyclic_lr, you might need to ensure that the code modifications correctly interpret this argument. " ?
3- this is the default section for schedule learning rate in trainer.py
![1](https://github.com/ultralytics/ultralytics/assets/52285797/6b43eeba-e1aa-4865-acde-99fb05899a58)
4- this is the modified schedule learning rate section in trainer.py after defining cyclic_lr
![2](https://github.com/ultralytics/ultralytics/assets/52285797/8f40dccb-44d6-458f-9db6-eda6ab95c975)
5- this is the modified part in default.yaml
![3](https://github.com/ultralytics/ultralytics/assets/52285797/e227e922-c9fd-48ef-aca9-694f44946847)
![4](https://github.com/ultralytics/ultralytics/assets/52285797/68a300dd-88c5-4c13-8bdc-9cae23225ed2)

**Comment by glenn-jocher** [comment]
Hi @ahmedfarouk99! 🌟 It looks like you're on the right track with your setup and modifications.

- Regarding boolean flags like `cyclic_lr`, it means ensuring that your script correctly handles these flags as `True` or `False` based on your command inputs. If `cyclic_lr=True` is set in your command, your script should recognize this and alter the learning rate schedule accordingly.

- From your screenshots, it looks like your modifications are well done! Just ensure that when you reference `cyclic_lr` or any new parameters in your YAML file, the Python script needs to read and apply these settings correctly. 

For example, to apply `cyclic_lr`, you could have something like this in `trainer.py`:

```python
if self.hyp['cyclic_lr']:
    scheduler = torch.optim.lr_scheduler.CyclicLR(optimizer, base_lr=0.001, max_lr=0.006)
else:
    # your default scheduler
```

Make sure your `default.yaml` correctly formats the new parameters, and they're being read appropriately by your Python script. 

Keep exploring and tweaking; it looks like you're very close to making it work perfectly! Let me know if there's anything else I can help with.🚀

**Comment by ahmedfarouk99** [comment]
@glenn-jocher when i modified my "trainer.py" as you mentioned before like this : 
![1](https://github.com/ultralytics/ultralytics/assets/52285797/76934e0b-4178-492b-99aa-b9071820ea01)
i got the same error:
![2](https://github.com/ultralytics/ultralytics/assets/52285797/59f787b7-ec7d-4268-b327-ed155e7db6e9)

**Comment by glenn-jocher** [comment]
Hey @ahmedfarouk99! It looks like we're making good progress. 😊 If you're still encountering the same error after modifying `trainer.py`, it might be that the `cyclic_lr` parameter isn't being properly parsed or utilized within the file. 

Be sure that `self.hyp['cyclic_lr']` correctly fetches the value from your `default.yaml`. If `cyclic_lr` has been properly defined in your YAML file and is still not being recognized, double-check the path and ensure that your training script loads the updated YAML configuration. 

Here's a quick snippet to ensure `cyclic_lr` is being read correctly:

```python
# Load hyperparameters from YAML
with open('path/to/your/default.yaml') as f:
    hyp = yaml.load(f, Loader=yaml.FullLoader)

# Check if 'cyclic_lr' is recognized
print(hyp.get('cyclic_lr'))  # Should print True/False based on your YAML
```

If this prints the expected value, ensure that the scheduler setup in your `trainer.py` is executed conditionally based on this flag. Otherwise, double-check the YAML file path and its contents. 📘

Let's keep the optimism up; you're on the brink of solving it! Let me know how it goes.

**Comment by ahmedfarouk99** [comment]
@glenn-jocher when i initiated a new python file to  ensure cyclic_lr is being read correctly like this:
![1](https://github.com/ultralytics/ultralytics/assets/52285797/6103a201-5c6b-4d24-884d-0386c3d3b683)
i got the expected value "True"
so what is the next step because i still encountering the same error as mentioned before.
sorry for bothering again and again

**Comment by glenn-jocher** [comment]
Hey there! No worries about reaching out; we're here to help! 🌟 If `cyclic_lr` is correctly printing as `True`, that's great progress! Since you're still facing the same error, it seems like the issue might lie in how the scheduler is set up in `trainer.py` or how it's integrated with the training loop.

A quick suggestion: double-check the integration of the `CyclicLR` scheduler with your optimizer and training loop in `trainer.py`. It should be something akin to this:

```python
# Example assuming `optimizer` is already defined
if hyp.get('cyclic_lr', False):  # Default to False if not specified
    scheduler = torch.optim.lr_scheduler.CyclicLR(optimizer, base_lr=0.001, max_lr=0.006)
```

And ensure you correctly step the scheduler at each iteration:

```python
for epoch in range(epochs):
    for batch_idx, data in enumerate(dataloader):
        # Your training step here

        # Step the scheduler if cyclic_lr is enabled
        if hyp.get('cyclic_lr', False):
            scheduler.step()
```

If everything looks correct and you still encounter issues, the problematic part might be elsewhere. In that case, sharing more about the error or the surrounding code block may help unravel the mystery further.

Keep pushing, and don't hesitate to ask more questions! 🚀

**Comment by ahmedfarouk99** [comment]
@glenn-jocher sorry but i do not understand.....
1-in order to add cyclic_lr to our code i only modified to files ( trainer.py & default.yaml) as i showed above
2- should i modify any other files? because i searched every python file in ultralytics repository and i found that the only files that contain section for learning rate are ( trainer.py & default.yaml)

**Comment by glenn-jocher** [comment]
@ahmedfarouk99 hi there! 😊 It sounds like you've done a fantastic job diving into the modifications for `cyclic_lr`. Modifying `trainer.py` and `default.yaml` is indeed the correct approach to integrating new hyperparameters like `cyclic_lr`.

You're on the right track! No additional files should need modifications for this feature unless you're considering advanced changes impacting the broader training loop or data handling mechanisms which doesn't seem to be the case here.

Regarding where to add or check the integration, make sure your scheduler update logic (`scheduler.step()`) is placed inside your training loop, directly after the `optimizer.step()` call for updating model weights. Here's a little snippet for clarity:

```python
if hyp.get('cyclic_lr', False):
    scheduler = torch.optim.lr_scheduler.CyclicLR(optimizer, ...)
else:
    scheduler = SomeOtherScheduler(optimizer, ...)

for epoch in range(epochs):
    for batch_idx, (inputs, targets) in enumerate(dataloader):
        ...
        optimizer.step()
        scheduler.step()
```

You've done great so far! Double-check these integration points, and you should be all set. Keep up the fantastic work, and feel free to reach out if you have more questions or need further assistance! 🚀

**Comment by ahmedfarouk99** [comment]
@glenn-jocher sorry for keep bothering you but i really interested on developing yolo...
i still got confused and do not find where the training loop in trainer.py in order to ensure that (schedular.step() ) is placed directly after ( optimizer.step() ) ....

**Comment by glenn-jocher** [comment]
@ahmedfarouk99 hey there! 🌞 No bother at all; I'm here to help!

1. The training loop in `trainer.py` typically looks like this:
```python
for epoch in range(epochs):
    model.train()
    for i, (imgs, targets) in enumerate(dataloader):
        optimizer.zero_grad()
        loss, outputs = model(imgs, targets)
        loss.backward()
        optimizer.step()

        if scheduler and cyclic_lr:  # If using cyclic_lr, step the scheduler here
            scheduler.step()
```
Just ensure `scheduler.step()` follows `optimizer.step()` as shown.

2. For the error regarding `cyclic_lr`, `base_lr`, `max_lr` not defined, make sure you've properly integrated these arguments in both `trainer.py` and `default.yaml`. In `trainer.py`, verify you're referencing these hyperparameters correctly from the `hyp` dictionary, like so:
```python
if hyp.get('cyclic_lr', False):
    scheduler = torch.optim.lr_scheduler.CyclicLR(optimizer, base_lr=hyp['base_lr'], max_lr=hyp['max_lr'])
```
And in `default.yaml`, ensure you've correctly added these parameters:
```yaml
cyclic_lr: True
base_lr: 0.001
max_lr: 0.01
```

This should link everything together nicely. Keep up the great work; exploring and developing on YOLO is always exciting! 🚀

**Comment by ahmedfarouk99** [comment]
@glenn-jocher 
1- i ensured that i'm referencing these hyperparameters correctly from the hyp dictionary, like so:
<img width="612" alt="1" src="https://github.com/ultralytics/ultralytics/assets/52285797/f20584be-d597-437f-9960-4605c91ea326">
2- i think you mean the training loop in trainer.py is the shadowed area as in the below screenshot
<img width="475" alt="2" src="https://github.com/ultralytics/ultralytics/assets/52285797/7fe95042-88d1-43d5-afc8-c46eba13c689">
i do not know where to add scheduler.step() after optimizer.step() in the trainer.py 
and i still counter the same error as above

**Comment by glenn-jocher** [comment]
Hey there! 😊 It looks like you've made great progress configuring the hyperparameters in your `hyp` dictionary and identifying the training loop section in `trainer.py`. 

For integrating the scheduler, right after your `optimizer.step()` call within the loop where you're backpropagating the loss, you can add the `scheduler.step()`. Here's a quick snippet to illustrate:

```python
...
optimizer.step()  # Update model weights

# Step the scheduler here if using cyclic_lr
if hyp.get('cyclic_lr', False):
    scheduler.step()
...
```

Make sure your `scheduler` is initialized based on the `cyclic_lr` flag before entering the training loop, as seen in previous examples. 

If you're still encountering an error, it might be helpful to double-check the hyperparameters (`cyclic_lr`, `base_lr`, `max_lr`) definitions in `default.yaml` and their usage in `trainer.py`.

Keep up the curiosity and exploration spirit in developing YOLO. You're doing fantastic! 🌟

**Comment by ahmedfarouk99** [comment]
@glenn-jocher sorry for bothering you but i still facing the same error without any progress 😞 here are my steps:
1- i cloned the repo in edit mode
2- i modified "trainer.py" according to your advice to add the "cyclic_lr" in schedule section as shown below 
<img width="603" alt="1" src="https://github.com/ultralytics/ultralytics/assets/52285797/d8622ad6-6356-40e6-97c2-74f205ded051">
3-  i modified "trainer.py" according to your advice For integrating the scheduler, right after your optimizer.step() call within the loop where you're backpropagating the loss, you can add the scheduler.step() as shown below
<img width="430" alt="2" src="https://github.com/ultralytics/ultralytics/assets/52285797/b1203ccb-edf9-4cb6-a361-2e82acc4203f">
4- i modified "default.yaml" to add "cyclic_lr" parameter as shown below
<img width="437" alt="3" src="https://github.com/ultralytics/ultralytics/assets/52285797/9cb91b79-b708-4c8b-bf69-b408b8daf766">
5-  i modified "default.yaml" to add "base_lr, max_lr, gamma, step_size, and mode " hyperparameters as shown below
<img width="302" alt="4" src="https://github.com/ultralytics/ultralytics/assets/52285797/c5632425-3831-4db2-8e55-043bcc6c1906">

and i still face the same error which i think it's related to defination
<img width="1220" alt="5" src="https://github.com/ultralytics/ultralytics/assets/52285797/60f17825-ee5e-4761-a4e9-1add254eda71">

 and i gave up and do not know how to solve it 😞

**Comment by glenn-jocher** [comment]
Hey @ahmedfarouk99! 👋 Sorry to hear you're still running into issues. From what you've described, it looks like you're really close to getting everything set up correctly! Let's tackle this step by step:

The error might be caused by how the hyperparameters are being accessed in `trainer.py`. If you've followed all the steps correctly for updating both `trainer.py` and `default.yaml`, just double-check that:

1. Every parameter (`cyclic_lr`, `base_lr`, `max_lr`, `gamma`, `step_size`, `mode`) is properly spelled and formatted in your `default.yaml`.
2. When you're accessing these parameters in `trainer.py`, you're using `hyp['parameter_name']` without typos. For instance, accessing `base_lr` should be done with `hyp['base_lr']`.

A common mistake is a typo or incorrect nesting in `default.yaml`, which may lead to parameters not being recognized. 

Also, make sure you're calling `scheduler.step()` outside any condition that might prevent it from executing every training iteration. It should look something like this:

```python
...
optimizer.step()  # Update weights
if hyp.get('cyclic_lr', False):  # Check if cyclic_lr is enabled
    scheduler.step()  # Update learning rate
...
```

If the issue persists, consider sharing the exact error message you're getting. Sometimes, a fresh pair of eyes can spot something you might have overlooked! Don't give up; you're on the brink of solving this! 🌟

**Comment by ahmedfarouk99** [comment]
@glenn-jocher i checked everthing thing as you asked and as i mentioned before but i still have the problem as shown below:
<img width="1046" alt="2" src="https://github.com/ultralytics/ultralytics/assets/52285797/3dcc2982-7612-4b66-8e5e-d9f3e92425e6">

**Comment by ahmedfarouk99** [comment]
@glenn-jocher can you answer me?

**Comment by glenn-jocher** [comment]
Hi there! 👋 Sure, I'm here to help. Could you please provide more details about your question or the issue you're facing? This way, I can offer you the most accurate advice or solution. Looking forward to hearing from you!

**Comment by ahmedfarouk99** [comment]
@glenn-jocher i succeeded to solve the previous error but i got another error
1- this is my modified schedule_lr function in trainer.py file
<img width="490" alt="1" src="https://github.com/ultralytics/ultralytics/assets/52285797/d0a97e7d-ebe6-4164-88d0-54bbc5792700">
2- this is the error i got 
<img width="1039" alt="2" src="https://github.com/ultralytics/ultralytics/assets/52285797/5a9d3bcd-f2e6-489b-88d5-6ded9a6e6a7a">

**Comment by glenn-jocher** [comment]
Hey there! 🌟 Great to hear you resolved the previous issue! For the new error you're encountering, it appears there might be a problem with how the scheduler is being referenced or parameters are fed into it.

Could you double-check that the scheduler setup in your `train.py` matches the expected arguments and configurations specified in `scheduler.py`? Occasionally, discrepancies in parameter names or types can lead to such errors.

If you could share a snippet of the code around where the error occurs (not just the error itself), I could give you more targeted advice! Keep up the good work, you're nearly there! 🚀

**Comment by ahmedfarouk99** [comment]
@glenn-jocher this is the default "schedule_lr" function in trainer.py 
<img width="652" alt="1" src="https://github.com/ultralytics/ultralytics/assets/52285797/cd391e5a-8bff-4f70-bf50-981f1f8a8ce8">
my question is how both cos_lr and linear LR has the same output or argument since they are both have the same code line 
''' self.scheduler = optim.lr_scheduler.LambdaLR(self.optimizer, lr_lambda=self.lf) " after IF condition.
but when i modified the function to add "cyclic_lr" as follows 
<img width="494" alt="2" src="https://github.com/ultralytics/ultralytics/assets/52285797/de8c7696-ffc1-433a-b6df-a11705f5932f">
it gives me the previous error

**Comment by glenn-jocher** [comment]
Hello! 😊 It seems like you are asking about how the same line of code in the `schedule_lr` function (`self.scheduler = optim.lr_scheduler.LambdaLR(self.optimizer, lr_lambda=self.lf)`) is used for both cos_lr and linear_lr setups, yet you face issues when modifying it for cyclic_lr.

The LambdaLR scheduler in PyTorch allows for creating custom learning rate schedules by providing a function (`lr_lambda`) that modifies the learning rate based on the current epoch or other criteria. Both the cos_lr and linear_lr configurations use different lambda functions (`self.lf` in this context) to define their own unique learning rate calculations. 

When you add cyclic_lr, make sure your implementation aligns with the specific requirements of a cyclic learning rate, which typically includes parameters for the base and max learning rates, and step size up/down. PyTorch also provides `CyclicLR` scheduler, which could handle these specifics internally and might simplify your implementation:

```python
from torch.optim.lr_scheduler import CyclicLR

self.scheduler = CyclicLR(self.optimizer, base_lr=0.001, max_lr=0.01, 
                          step_size_up=5, step_size_down=20)
```

Regarding the error you're seeing, it might be due to incorrect setup or parameters mismatch. Make sure the configuration passed to your custom or modified scheduler aligns with its expected input. Check the full traceback to pinpoint where exactly the error occurs which might give more insight into what parameter or setup might be incorrect.

Keep up the great work refining your training setup! 🚀

**Comment by ahmedfarouk99** [comment]
@glenn-jocher sorry for keeping bother you but i think i'm very close to the solution
1- this is the default "scheduler_lr " function where both linear and cos_lr used "LambdaLR" torch function as follows:
<img width="653" alt="1" src="https://github.com/ultralytics/ultralytics/assets/52285797/6fcf6e08-bb9d-4e5b-9c70-06ff8745bf1f">
we also see that cos_lr used "one_cycle" function as follows:
<img width="659" alt="4" src="https://github.com/ultralytics/ultralytics/assets/52285797/61e77b71-cc5b-4d1c-9ef1-8bf9ebb4dbcf">
2- here is my modified "scheduler_lr" function:
<img width="804" alt="2" src="https://github.com/ultralytics/ultralytics/assets/52285797/a3379b55-c12c-4e2b-bc21-22f33ade0258">
3- here is my error in line 366 because in my modified "scheduler_lr" where i added  "cyclic_lr" i only added one line as i showed above and not added any line related to "self.lf" parameter as used in default linear and cos_lr
<img width="770" alt="3" src="https://github.com/ultralytics/ultralytics/assets/52285797/8899b823-c776-427c-94d1-9c8bd215ec3c">
my question is how to use "one_cycle" function to be synched with "cyclic_lr" as to be able to use "self.lf" in order to avoid line 366 error in "trainer.py"

**Comment by glenn-jocher** [comment]
Hey @ahmedfarouk99! 🌟 You're indeed very close to cracking this! When applying a `cyclic_lr` with the `one_cycle` policy, it's crucial to set up `self.lf` properly since `LambdaLR` relies on this lambda function to calculate the learning rate dynamically.

For `one_cycle` with `cyclic_lr`, you typically define `self.lf` to control the learning rate adjustment over epochs. Here's a basic setup of what it might look like:

```python
def one_cycle(y1=0.0, y2=1.0, steps=100):
    # Lambda function to interpolate between y1 and y2 over `steps`
    return lambda x: ((1 - x/steps) * y1 + (x/steps) * y2)

steps = len(dataloader) * epochs  # total number of steps for the scheduler
self.lf = one_cycle(y1=0.1, y2=1.0, steps=steps)
self.scheduler = optim.lr_scheduler.LambdaLR(self.optimizer, lr_lambda=self.lf)
```

This setup interpolates the learning rate between `y1` and `y2` over the total `steps`. Adjust `y1`, `y2`, and `steps` as per your cyclic learning rate requirements. Make sure that the `steps` line computes the actual training steps in accordance with your epochs and dataloader.

Let me know if this helps clear the confusion, or if you need further tweaks! 😊

**Comment by ahmedfarouk99** [comment]
@glenn-jocher thanks for your respond but i have one more question:
1-as you mentioned above i will define "one_cycle" function as default one in "torch_utils" python file
2- also i'll add this 2 line in "trainer.py" :
self.lf = one_cycle(y1=0.1, y2=1.0, steps=steps)
self.scheduler = optim.lr_scheduler.LambdaLR(self.optimizer, lr_lambda=self.lf)
3- my question is where to add this line?
steps = len(dataloader) * epochs  # total number of steps for the scheduler

**Comment by ahmedfarouk99** [comment]
@glenn-jocher can you answer me please

**Comment by glenn-jocher** [comment]
Hi there! 👋 I'm here to help. Could you please provide more details about your question or the issue you're facing? This way, I can offer you the most accurate advice or solution. Looking forward to hearing from you!
