### ISSUE TITLE
How to solve the angular ambiguity issue for roughly square objects that exists in YOLOv8 Obb?

### ISSUE THREAD

**Issue by xuewengeophysics** [ultralytics/ultralytics#10093]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi everyone.

Using YOLOv8 Obb to detect square objects, I face the angular ambiguity issue.

According to the reference "Gaussian Bounding Boxes and Probabilistic Intersection-over-Union for Object Detection" and "Probabilistic Intersection-Over-Union for Training and Evaluation of Oriented Object Detectors", it is impossible to recover the angular information for square OBB annotations, because the GBBs associated with the two OBBs are exactly the same.

![image](https://github.com/ultralytics/ultralytics/assets/8676098/7a8b91dc-046a-441b-8b4b-e61ee45f8bcf)

![image](https://github.com/ultralytics/ultralytics/assets/8676098/73f1191d-bbc9-499a-8c00-e136f63146b1)

**Comment by glenn-jocher** [comment]
Hi there, 👋

Thanks for reaching out with your question on angular ambiguity for roughly square objects in YOLOv8 Obb.

You're correct in noting the challenge presented by square objects when it comes to recovering angular information. One potential approach to mitigate this issue is to incorporate additional context or features that may help distinguish the orientation. For detection tasks focused particularly on square or nearly square objects where angular information is crucial, exploring complementary techniques or custom enhancements (such as integrating specific orientation classifiers or utilizing additional labeling information) could potentially offset this limitation.

However, this is indeed an inherent complexity within oriented bounding box (OBB) detection for square objects, and further research or tailored solutions might be required to fully address this challenge.

Keep the exploration going, and feel free to discuss any further findings or innovative solutions you come across! 🚀

**Comment by Leo5050xvjf** [comment]
@xuewengeophysics
Hi, 
I've also encountered the same issue. Have you found a solution yet?
thx

**Comment by AlvinZheng** [comment]
i met the same problem.
my solution temporary：
just avoid to train the square object.
padding the OBB width or height before training
<img width="457" alt="Image" src="https://github.com/user-attachments/assets/32d89723-52e8-4e42-9fb2-7428a134c31c" />
when inference, minus the padded width or height, you got the square result.
This just worked for me!

**Comment by AlvinZheng** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.
> 
> ### Question
> Hi everyone.
> 
> Using YOLOv8 Obb to detect square objects, I face the angular ambiguity issue.
> 
> According to the reference "Gaussian Bounding Boxes and Probabilistic Intersection-over-Union for Object Detection" and "Probabilistic Intersection-Over-Union for Training and Evaluation of Oriented Object Detectors", it is impossible to recover the angular information for square OBB annotations, because the GBBs associated with the two OBBs are exactly the same.
> 
> ![image](https://github.com/ultralytics/ultralytics/assets/8676098/7a8b91dc-046a-441b-8b4b-e61ee45f8bcf)
> 
> ![image](https://github.com/ultralytics/ultralytics/assets/8676098/73f1191d-bbc9-499a-8c00-e136f63146b1)
> 
> ### Additional
> _No response_
i met the same problem.
my solution temporary：
just avoid to train the square object.
padding the OBB width or height before training
Image
when inference, minus the padded width or height, you got the square result.
This just worked for me!

**Comment by glenn-jocher** [comment]
Thank you for sharing your practical workaround! This angular ambiguity for square objects in OBB detection is indeed a known geometric limitation, as highlighted in the research papers you referenced. Your solution of padding dimensions during training and adjusting post-inference is a clever approach to circumvent the symmetry issue. While this remains an inherent challenge in oriented detection of square objects, your method provides a useful temporary mitigation strategy for the community.
