### ISSUE TITLE
keypoint coordinates for each point 

### ISSUE THREAD

**Issue by benicio22** [ultralytics/ultralytics#10122]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

User
Hello, I want to take the coordinates of each keypoint and classify them with numbers. For example, keypoint 1 has coordinates x,y; keypoint 2 has coordinates x1,y2 and so on, I want to do this for my entire dataset. However, I'm getting errors. 
This is my code.  from ultralytics import YOLO
import cv2
from ultralytics.utils.plotting import Annotator

model_path = 'C:/Users/idigi/Box/UIUC_ACADEMIC/PHD_THESIS/PROJECTS/GAIT_CATTLE/RESULTS/POSE_MODEL/POSE_TRAIN_MODEL/RESULTS_V1_20EPOCHS_500IMAGES/weights/best.pt'

image_path = 'C:/Users/idigi/Box/UIUC_ACADEMIC/PHD_THESIS/PROJECTS/GAIT_CATTLE/ANGLE_DATASET/DAY/06_13_19/6.13.19-124F/6.13.19-124F_Color_1560438142923.505_198.jpg'
img = cv2.imread(image_path)

model = YOLO(model_path)

results = model(image_path)[0]

for result in results:
    for keypoint_indx, keypoint in enumerate(result.keypoints[0]):
        #print(result.keypoints)
        # Assuming keypoint is a different data structure, adjust accordingly
        # For example, if keypoint is a list or tuple containing the coordinates:
        x, y = keypoint[0], keypoint[1]  # Assuming keypoint is a list or tuple
        cv2.putText(img, str(keypoint_indx), (int(x), int(y)),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

cv2.imshow('img', img)
cv2.waitKey(0)

and This is the error:
C:\Users\idigi\Documents\EMBRAPA_PROJECT_2023\venv\Scripts\python.exe C:\Users\idigi\Documents\EMBRAPA_PROJECT_2023\GAIT_CATTLE_2024\EXTRACT_ANGLES_GAIT.py 

image 1/1 C:\Users\idigi\Box\UIUC_ACADEMIC\PHD_THESIS\PROJECTS\GAIT_CATTLE\ANGLE_DATASET\DAY\06_13_19\6.13.19-124F\6.13.19-124F_Color_1560438142923.505_198.jpg: 384x640 1 cattle_keypoint, 110.1ms
Speed: 1.0ms preprocess, 110.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
Traceback (most recent call last):
  File "C:\Users\idigi\Documents\EMBRAPA_PROJECT_2023\GAIT_CATTLE_2024\EXTRACT_ANGLES_GAIT.py", line 20, in <module>
    x, y = keypoint[0], keypoint[1]  # Assuming keypoint is a list or tuple
                        ~~~~~~~~^^^
  File "C:\Users\idigi\Documents\EMBRAPA_PROJECT_2023\venv\Lib\site-packages\ultralytics\engine\results.py", line 63, in __getitem__
    return self.__class__(self.data[idx], self.orig_shape)
                          ~~~~~~~~~^^^^^
IndexError: index 1 is out of bounds for dimension 0 with size 1

Process finished with exit code 1

### Additional

_No response_

**Comment by glenn-jocher** [comment]
Hello! It looks like you're on the right track with your code, but let's address the error you encountered. The error message suggests that there's an issue accessing your keypoints' coordinates due to a potential misunderstanding of the keypoints data structure returned by the model. 🤔

Your keypoints enumeration suggests you're expecting a list of keypoints directly within the `result.keypoints` for each detection. However, the error indicates an indexing issue, likely because the keypoints data structure doesn't match your expectations.

Here’s a revised snippet of your loop for iterating over detected keypoints. This assumes that your model's `results.keypoints` returns a list of keypoints for each detected object:

```python
for idx, detection in enumerate(results.keypoints):
    keypoints = detection['keypoints']
    for keypoint_index, (x, y, conf) in enumerate(keypoints):
        # Now, x and y are the coordinates, and conf is the confidence of detection for each keypoint.
        # You might want to check if conf is above a certain threshold before plotting.
        cv2.putText(img, f'{keypoint_index}: ({int(x)}, {int(y)})', (int(x), int(y)),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)
```

This code assumes each `keypoint` contains the coordinates `(x, y)` and a confidence value `conf`. Please adjust the `keypoints = detection['keypoints']` line according to how the keypoints are structured in your results. If the structure is different, you may need to adapt the loop accordingly.

Don't forget to check if keypoints are returned as expected by printing them out or debugging. This snippet also includes a placeholder for handling confidence, in case you want to use it to filter keypoints. 

Hope this helps! Let me know if there's anything else you need. 🚀

**Comment by benicio22** [comment]
HI, I tried to do the way that you said. But I am having this error here: Traceback (most recent call last):
  File "C:\Users\idigi\Documents\EMBRAPA_PROJECT_2023\GAIT_CATTLE_2024\EXTRACT_ANGLES_GAIT.py", line 18, in <module>
    for keypoint_index, (x, y, conf) in enumerate(keypoints):
                        ^^^^^^^^^^^^
ValueError: too many values to unpack (expected 3)


This is my code: from ultralytics import YOLO
import cv2


model_path = 'C:/Users/idigi/Box/UIUC_ACADEMIC/PHD_THESIS/PROJECTS/GAIT_CATTLE/RESULTS/POSE_MODEL/POSE_TRAIN_MODEL/RESULTS_V1_20EPOCHS_500IMAGES/weights/best.pt'

image_path = 'C:/Users/idigi/Box/UIUC_ACADEMIC/PHD_THESIS/PROJECTS/GAIT_CATTLE/ANGLE_DATASET/DAY/06_13_19/6.13.19-124F/6.13.19-124F_Color_1560438142923.505_198.jpg'


model = YOLO(model_path)

results = model.predict(image_path)

img=cv2.imread(image_path)
for res in results:
    keypoints=res.keypoints.xy
    print(keypoints)
    for keypoint_index, (x, y, conf) in enumerate(keypoints):
        # Now, x and y are the coordinates, and conf is the confidence of detection for each keypoint.
        # You might want to check if conf is above a certain threshold before plotting.
        cv2.putText(img, f'{keypoint_index}: ({int(x)}, {int(y)})', (int(x), int(y)),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

And I printed the keypoint structure:
tensor([[[ 979.6750,  357.6494],
         [1039.8950,  302.0255],
         [1145.4583,  288.6907],
         [1245.9303,  286.9016],
         [1232.6051,  381.2330],
         [1233.4971,  407.7163],
         [1207.6041,  459.5955],
         [1236.7977,  377.1603],
         [1261.2654,  398.0333],
         [1222.8828,  474.4590],
         [1077.8118,  400.9701],
         [1077.3250,  435.8143],
         [1080.9961,  456.6836],
         [1094.6233,  395.8533],
         [1093.1389,  433.5782],
         [1102.5928,  469.3304]]])

**Comment by glenn-jocher** [comment]
Hey there! 🌟 It looks like the KeyError is because the keypoints tensor does not include confidence values directly in its structure, hence the mismatch during unpacking. Your keypoints tensor is structured with just `(x, y)` coordinates for each point, without a separate `conf` value per keypoint.

To iterate over each keypoint correctly, you might want to adjust your loop to exclude the expectation of a `conf` value directly. Here's a quick fix:

```python
for res in results:
    keypoints = res.keypoints.xy  # Assuming .xy gives the desired tensor based on your print output
    for keypoint_index, (x, y) in enumerate(keypoints[0]):  # No conf value expected here
        cv2.putText(img, f'{keypoint_index}: ({int(x)}, {int(y)})', (int(x), int(y)),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)
```

Since it seems there is no direct `conf` value associated within each keypoint tensor, adjusting your code like above should resolve the error. 

Keep rocking those keypoints, and let me know if there's more I can help with! 🚀
