### ISSUE TITLE
RTSP source is freezing when using YoloV8

### ISSUE THREAD

**Issue by Kayo-programs** [ultralytics/ultralytics#10127]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

The code below has the function of taking 3 photos of the environment with a time interval of 3 seconds between each photo. If a person is detected in at least one of these photos, it informs that there are people in the location, if not, it informs that the location is empty. After that, it waits 10 seconds to repeat the process (cycle). The problem is that when the program tries to get the most recent frame from the video source (an EZVIZ C3N, H.264/265, FFMPEG FULL HD camera communicating via the RTSP protocol), it is as if the frames from the camera stream are stuck and Yolov8 makes inferences normally on those frozen frames. Initially I thought that the stream's frames were completely stuck but they go at a very low FPS. When the program reaches the sixth cycle, it freezes on the second photo saying "source is empty", but the camera remains functional. The closest issue I found here was the following issue: https://github.com/ultralytics/ultralytics/issues/3559. But unfortunately I don't understand how it was resolved. Nothing so far has resolved the problem

My specs:
- Windows 10
- VS Code; 
- YOLOv8 8.1.29
- Open VC 4.9.0.80
- Python 3.11.7

```import cv2,time
from ultralytics import YOLO
from datetime import datetime
import os

model = YOLO("yolov8x.pt")
url = "rtsp://admin:pass@ipadress:554/H.265/Streaming/Channels/101"
cam1 = cv2.VideoCapture(url)
cicle_counter=1 
system_status = True 
today = datetime.now() 
moment_exec= today.strftime('%d-%m-%Y_%H-%M-%S') 
quant_analise_global = 3 
lot = "Empty Place"


def image_processing(img,cam):
    cls = []
    print("capturando foto...")
    photo_status, img = cam.read() 
    print("foto capturada!Processando...")

    if cam == cam1:
        Ciclo = f"Results\{moment_exec}\Cicle{cicle_counter}\Camera1"
        name_predict = f"Photo{quant_analise}"
    
    dir = f".\{Ciclo}\{name_predict}\image0.jpg"
    print (dir)
    os.makedirs(os.path.dirname(dir))
    cv2.imwrite(dir, img)
    results = model(dir, save = True,conf = 0.3, max_det=40,project = Ciclo, name = name_predict)
    
    time.sleep(3)

    for result in results:
        boxes = result.boxes
        for box in boxes: 
            cls.append(int(box.cls)) 
    return cls 

while system_status:
    print(f"Cicle {cicle_counter}") 
    sucess1, img1 = cam1.read() 

    interval = 10
    results = [] 
    classes = []
    classes_concat = [] 

    if sucess1: 
        print("Status Camera 1: OK")
        quant_analise = quant_analise_global 
        while quant_analise>0:
            classes.append(image_processing(img1, cam1))
            quant_analise-=1
    else: 
        print("Cam 1 Fail, turning Off Systems!")
        system_status = False
   

    for line in classes:
        for i in line:
            classes_concat.append(i)
    
    print (classes_concat)

    count_people = classes_concat.count(0)
    if count_people>0:
        print("People Detected in the place!")
    else: 
        print("Place is empty!")


    while interval > 0: 
        print(f"time for next verification:{interval} seconds","\33[k",end='\r')
        time.sleep(1)
        interval -= 1

    print ('-'*70)
    cicle_counter+=1
cam1.release() 
cv2.destroyAllWindows()  
print("System Off!") 
```

### Additional

This same program works perfectly with a webcam and video capture from this camera works normally using VLC or Open CV.```

**Comment by glenn-jocher** [comment]
It sounds like you're encountering an issue with frame buffering from the RTSP stream, which is a common problem when dealing with live video feeds. Here are a couple of suggestions that might help resolve the freezing issue:

1. **Force a Frame Flush**: Modify your loop to explicitly grab and decode frames continuously within your cycle to ensure you're always processing the latest frame. This can be done by adding a small loop to read several frames in quick succession before processing one, effectively clearing out any buffer.

2. **Adjust RTSP Transport Protocol**: Sometimes specifying the transport protocol in your RTSP URL can help. You can try adding `?transport=tcp` at the end of your RTSP URL to force the use of TCP instead of UDP, which might provide a more stable connection.

Here's a modified snippet of your code to include these suggestions:

```python
url = "rtsp://admin:pass @Kayo-programs:554/H.265/Streaming/Channels/101?transport=tcp"
cam1 = cv2.VideoCapture(url)
...
while system_status:
    print(f"Cicle {cicle_counter}") 
    for _ in range(5):  # Flush the buffer by reading some frames
        cam1.grab()
    sucess1, img1 = cam1.retrieve()  # Retrieve the latest frame

    if sucess1: 
        ...
```

Try these modifications and see if they help with the freezing issue. If the problem persists, it might be worth checking network conditions or camera settings related to stream encoding and transmission.
