### ISSUE TITLE
Test yolov8 model online

### ISSUE THREAD

**Issue by san-kou7** [ultralytics/ultralytics#10141]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I would like to ask: I have successfully trained a target detection model and achieved good results on the test set. However, since the number of my test sets is small, I hope to be able to implement online testing.

I plan to write a simple demo and use the camera of my laptop or the camera connected to the computer host to conduct an online test with the trained target detection model. Does the ultralytics framework support this operation or even have a corresponding interface?

If you can please give me some designation for my demo idea, I will be grateful！

**Comment by ambitious-octopus** [comment]
Hey @san-kou7 :small_airplane: ,
Assuming you already have a trained model. You can test your model locally using the webcam with the command-line interface:
```
yolo predict model=yolov8n-seg.pt source="0" show=True
```
In order to use your trained model you obviously need to replace `yolov8n-seg.pt` with the path to your trained model. Also you may need to change `source="0"`, try `"1"` or `"2",` it depends on how many camera devices you have connected to your computer. 

If you need more information take a look at the [documentation](https://docs.ultralytics.com/modes/predict/#inference-sources)!

**Comment by san-kou7** [comment]
Thanks for your answer, it helps me a lot

**Comment by glenn-jocher** [comment]
@san-kou7 you're welcome! I'm glad to hear that it was helpful. If you have any more questions or need further assistance, feel free to ask. Happy coding! 🚀
