### ISSUE TITLE
Use the track method in TensoRT

### ISSUE THREAD

**Issue by JustChenk** [ultralytics/ultralytics#10147]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

How to directly call the MOT algorithm through the TensoRT format model and output the analysis results, as in the pytorch model eg:model.track(image).

I don't know if  ultralytics  supports this feature.

![image](https://github.com/ultralytics/ultralytics/assets/136715410/b6f5be92-0def-49e1-9623-9585d8fd192b)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello! Thanks for reaching out with your question about using the `track` method with a TensorRT model in YOLOv8. 🚀

Currently, direct support for multi-object tracking (MOT) with TensorRT models using the `track` method, similar to the ease of PyTorch (`model.track(image)`), is not inherently available within Ultralytics YOLOv8. While the tracking functionality is available for PyTorch models, additional steps are typically required for TensorRT due to the need for post-processing the output tensors specifically for tracking purposes.

To incorporate MOT with TensorRT, you would generally need to process the output of the TensorRT model separately to apply tracking. This involves:
1. Running inference with the TensorRT model.
2. Extracting detected objects' bounding boxes, classes, and scores from the output tensors.
3. Feeding these detections to a tracking algorithm (e.g., sort, deep SORT, etc.) implemented in Python or another language compatible with your application.

While direct feature support for this workflow within Ultralytics YOLOv8 might not be available, your interest and willingness to contribute via a PR is greatly appreciated! This could be a valuable addition to the project. 

For specific implementation or starting points, I'd recommend exploring external MOT implementations that can process detections and adapt them to work with TensorRT outputs. If you develop a solution and would like to contribute, please feel free to open a PR or share your approach in the issues section for further discussion.

Thanks for contributing to the YOLOv8 community, and please don't hesitate to share your progress or ask for assistance as you work on integrating this feature! 🌟
