### ISSUE TITLE
how to  cancel the LetterBox?

### ISSUE THREAD

**Issue by wataincdx** [ultralytics/ultralytics#10187]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

how to  cancel the LetterBox?

### Additional

how to  cancel the LetterBox?

**Comment by glenn-jocher** [comment]
Hi there 👋! To remove the letterbox padding during inference in YOLOv8, you can use the `--rect` flag or set `rect=True` if you're executing YOLOv8 through Python. This will adjust the network's inference to use rectangular inference instead of the default square size, thus removing the letterbox effect that adds padding to maintain aspect ratio.

For instance, in CLI:
```bash
yolo detect predict --rect ...
```

In Python:
```python
from ultralytics import YOLO
model = YOLO('yolov8n.pt')
results = model.predict('path/to/image', rect=True)
```

Hope this helps! Let us know if you have any more questions.
