### ISSUE TITLE
Where can I check the benchmark score of yolov8x6.pt?

### ISSUE THREAD

**Issue by blackCmd** [ultralytics/ultralytics#10265]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Where can I check the benchmark score of `yolov8x6` and `yolov8-obb` etc..?
I used to see it before, but now I can't find it anywhere.

**Comment by glenn-jocher** [comment]
@blackCmd hello! 🌞 To check the benchmark scores of models like `yolov8x6` and `yolov8-obb`, I recommend visiting the [Ultralytics YOLOv8 documentation](https://docs.ultralytics.com/). Specifically, you'll want to explore the **Benchmark** section, which provides insight into performance, speed, and accuracy across various YOLOv8 models. While direct links to benchmarks might not always be highlighted, the documentation is continuously updated with the latest metrics and results.

If the benchmarks for these specific models aren't immediately visible, it could be due to recent updates or ongoing performance evaluations. In such cases, the [GitHub Discussions](https://github.com/ultralytics/ultralytics/discussions) can be a great place to ask for the latest benchmarks or share insights with the community. The Ultralytics team and community members often share results, tips, and updates there. Happy exploring! 🚀

**Comment by blackCmd** [comment]
@glenn-jocher 
There is no information about yolov8x6.pt in the documentation..
Where can I find it?

![image](https://github.com/ultralytics/ultralytics/assets/13531174/ddee4dcc-7a33-4c89-b5ba-5a5ca648db11)

**Comment by glenn-jocher** [comment]
Hi @blackCmd! 👋 It seems like the information for `yolov8x6.pt` might not be directly listed in the current documentation. I recommend checking the [Ultralytics YOLOv8 documentation](https://docs.ultralytics.com/) for any updates or related models. If it's still missing, the best course of action would be to raise this in the [GitHub Discussions](https://github.com/ultralytics/ultralytics/discussions) for a more specific update or guidance from the Ultralytics team. Thanks for reaching out!
