### ISSUE TITLE
How do i store unique track ids everytime my video restarts?

### ISSUE THREAD

**Issue by anishka07** [ultralytics/ultralytics#10302]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

So i want to give unique track ids to the tracked objects. I already did the part where track ids are given. I did that by taking the approach of checking the database and if the database is empty, then i use the normal track id of the yolo model. and the first part is working fine. But when i restart the video, the tracker doesnot work as i want it to. For example, for the first time running of the video, if the track id stopped at 156, when i start the video for the second time, the track id ends up being 2500+ which is absurd. How do i fix this, also how can i visualize this and store it in the database at the same time?

This is the code:

` def get_max_track_id(self):
        self.cursor.execute(f"SELECT max(track_id) FROM {self.table_name}")
        result = self.cursor.fetchone()
        return result[0] if result[0] is not None else 0

    def video_read(self):
        while self.cap.isOpened():
            ret, frame = self.cap.read()
            if ret is None:
                break
            yield frame

    def insert_db(self, classes: List[int], conf: float):
        for tracked_obj in self.detection(classes=classes, conf=conf):
            self.cursor.execute(f"INSERT INTO {self.table_name} VALUES (?, ?, ?, ?)", (
                tracked_obj.track_id,
                tracked_obj.class_name.encode('utf-8'),
                tracked_obj.bbox,
                tracked_obj.score
            ))
            self.connection.commit()

    def detection(self, classes: List[int], conf: float = .5):
        self.cursor.execute(f"SELECT COUNT(*) FROM {self.table_name}")
        table_is_empty = self.cursor.fetchone()[0] == 0
        if table_is_empty:
            for frame in self.video_read():
                results = self.model.track(frame, persist=True, classes=classes, conf=conf)
                for result in results:
                    boxes = result.boxes.cpu().numpy()
                    detections = zip(boxes.xyxy, result.boxes.id.int().cpu(), boxes.cls, result.boxes.conf)
                    for box, track_id, class_id, conf_val in detections:
                        confidence = round(float(conf_val.item()), 2)
                        if confidence >= conf:
                            class_id = int(class_id.item())
                            track_id = int(track_id.item())
                            bbox = ','.join(map(str, [int(x) for x in box.tolist()]))
                            class_name = str(self.model.names[class_id])
                            tracked_obj = VideoReaderResults(
                                track_id=track_id,
                                class_name=class_name,
                                bbox=bbox,
                                score=confidence
                            )
                            yield tracked_obj
        else:
            max_track_id = self.get_max_track_id()
            for frame in self.video_read():
                results = self.model.track(frame, persist=True, classes=classes, conf=conf)
                for result in results:
                    boxes = result.boxes.cpu().numpy()
                    detections = zip(boxes.xyxy, result.boxes.id.int().cpu(), boxes.cls, result.boxes.conf)
                    for box, track_id, class_id, conf_val in detections:
                        confidence = round(float(conf_val.item()), 2)
                        if confidence >= conf:
                            class_id = int(class_id.item())
                            track_id = int(max_track_id) + 1
                            max_track_id = track_id
                            bbox = ','.join(map(str, [int(x) for x in box.tolist()]))
                            class_name = str(self.model.names[class_id])
                            tracked_obj = VideoReaderResults(
                                track_id=track_id,
                                class_name=class_name,
                                bbox=bbox,
                                score=confidence
                            )
                            yield tracked_obj`

I have added the screenshots as well:

<img width="825" alt="Screenshot 2024-04-24 at 10 33 21 PM" src="https://github.com/ultralytics/ultralytics/assets/109445504/7f7f90e3-cf1f-42d9-936a-1d687e5b0aa2">
<img width="910" alt="Screenshot 2024-04-24 at 10 33 56 PM" src="https://github.com/ultralytics/ultralytics/assets/109445504/c831670f-73d2-49ac-8069-6e9c54d0e0d6">

please help me

**Comment by glenn-jocher** [comment]
@anishka07 hey! It seems like you're on the right track with handling unique track IDs and storing them in a database. 😊 For the issue with IDs jumping to 2500+ upon restarting the video, it might be because the `max_track_id` is not being updated correctly in subsequent video runs. 

One approach to ensure the `max_track_id` is consistent across video re-runs is to initialize `max_track_id` outside your loop and increment it inside the detection loop only when a new track is detected. This way, `max_track_id` will continue from where it left off when you restart the video.

Also, make sure to retrieve and update `max_track_id` appropriately at the beginning of each video processing to avoid large, unexpected jumps in ID numbers.

For visualization and database storage simultaneously, you're already inserting tracked objects into the database within `insert_db`. For visualization, you could draw the bounding boxes and IDs on the frames before or after this step, using OpenCV functions like `cv2.rectangle()` and `cv2.putText()` and then display them using `cv2.imshow()`.

Here's a quick modification to include a visual update:

```python
def visualize_and_insert(self, frame, tracked_obj):
    x1, y1, x2, y2 = map(int, tracked_obj.bbox.split(','))
    cv2.rectangle(frame, (x1, y1), (x2, y2), (255, 0, 0), 2)
    cv2.putText(frame, f"ID {tracked_obj.track_id}", (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (36,255,12), 2)
    self.insert_db(tracked_obj)  # Assuming this function is adapted to accept a single tracked_obj
    return frame
```

Remember to call this `visualize_and_insert` method inside your detection loop. This should help with both visualizing the tracks and storing them in the database simultaneously.

If restarting the video means starting a new instance/session of your application, ensure to fetch the last `max_track_id` from your database upon initialization and proceed from there.

Hope this helps! Let us know if you encounter any more issues.
