### ISSUE TITLE
enabling multiscal causes type error on random

### ISSUE THREAD

**Issue by uwer** [ultralytics/ultralytics#10331]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

lib/python3.12/site-packages/ultralytics/models/yolo/detect/train.py", line 63, in preprocess_batch
    random.randrange(self.args.imgsz * 0.5, self.args.imgsz * 1.5 + self.stride)
 lib/python3.12/random.py", line 301, in randrange
    istart = _index(start)
TypeError: 'float' object cannot be interpreted as an integer

### Environment

Ultralytics YOLOv8.2.2 🚀 Python-3.12.0 torch-2.1.1 CUDA:0 (NVIDIA H100, 95465MiB)
Setup complete ✅ (72 CPUs, 502.9 GB RAM, 12.1/24.0 GB disk)
OS                  Linux-5.14.21-150400.24.28-default-x86_64-with-glibc2.31
Environment         Linux
Python              3.12.0
Install             pip
RAM                 502.92 GB
CPU                 Intel Xeon Platinum 8452Y
CUDA                12.2
matplotlib          ✅ 3.8.0>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.0.1>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.4>=1.4.1
torch               ✅ 2.1.1>=1.8.0
torchvision         ✅ 0.16.0>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.1.1>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0

### Minimal Reproducible Example

enable 
multi-scale=True

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hi there! 👋 It seems like the issue you've encountered might be related to the multi-scale training aspect expecting integer values for image sizes, but receiving floating-point numbers instead. This type error can happen due to the multiplication with `self.stride`, which might not result in an integer as required by `random.randrange`.

As a quick solution, you could try rounding the result to the nearest integer using the `round()` function. Here's a modified line that might resolve the issue:

```python
random.randrange(round(self.args.imgsz * 0.5), round(self.args.imgsz * 1.5) + self.stride)
```

This ensures that the arguments passed to `random.randrange` are integers, thereby preventing the `TypeError`. 

Of course, this is just a quick fix. Further investigation into ensuring multi-scale handling correctly interprets the intended image sizes as integers throughout the code might be necessary. 🕵️‍♂️

If you're comfortable modifying the source code, this could be a good place to start. If you need further assistance or would like to discuss this issue in more depth, don't hesitate to let us know! 😊

**Comment by uwer** [comment]
Hi Glenn,

I am acutely aware on how to fix it, actually I thought this should not
happen in the first place as the hardcoded multipliers are floats in the
first place, so the result will always be a float - if the receiving
function random doesn't accept floats a simple cast to int should do it ...
unless of course the original author was concerned about the fractions -
than the target function is wrong.

Cheers
Uwe

**Comment by glenn-jocher** [comment]
@uwer hey Uwe,

Thanks for the feedback! 😊 You're absolutely right—the issue stems from those multipliers being floats, leading to a float result which `random.randrange` can't handle directly. A straightforward cast to int, as you mentioned, would indeed resolve this, ensuring that the inputs to `random.randrange` remain integers and avoiding any concerns about fractions.

Here's how that simple cast to int could look:

```python
random.randrange(int(self.args.imgsz * 0.5), int(self.args.imgsz * 1.5) + self.stride)
```

This should keep things running smoothly without affecting the intended functionality of the multi-scale training. Thanks for pointing out this cleaner approach! 👍
