### ISSUE TITLE
Very Slow Scanning time on google colab for training on kitti dataset using yolov8

### ISSUE THREAD

**Issue by SalmaHishamm** [ultralytics/ultralytics#10340]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am using google colab to train my  model on a dataset (7480 IMAGES) uploaded on google drive and the scanning time is taking a lot (1 hr 45 mins so far ) for 6000 images vs. on my local machine the scanning took 1 min (however the training itself was slow so I switched to google colab) so how to fasten this ? I have seen the solution to train on local data but I don't understand how to do this on google colab ?

**Comment by glenn-jocher** [comment]
@SalmaHishamm hi there! It seems like the issue you're encountering with scanning times on Google Colab is due to the I/O bottleneck when accessing data from Google Drive. Reading large datasets directly from Google Drive can be significantly slower compared to local storage. 🐢

To speed up the process, you can try copying your dataset from Google Drive to the Colab instance's local storage before starting the training. Here's a snippet that might help:

```python
from google.colab import drive
drive.mount('/content/drive')

!cp -r "/content/drive/My Drive/path_to_your_dataset" "/content/local_dataset"
```

After copying, make sure to point your dataset path to `"/content/local_dataset"` in your training script. This way, you're leveraging the faster local storage of the Colab instance.

Hope this helps! If the issue persists or if there's anything else, feel free to ask. Happy training with YOLOv8! 🚀
