### ISSUE TITLE
Do we need augmentation when using YOLOv8 as our benchmark?

### ISSUE THREAD

**Issue by yaoshanliang** [ultralytics/ultralytics#1035]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a question that when using YOLOv8 as the benchmark, do we use default hyperparameters or close all augmentations, like hsv, translate, mosaic?

**Comment by glenn-jocher** [comment]
It depends on what you want to achieve with your benchmarking. If you want to compare the performance of YOLOv8 with other object detection models, it's best to use the default hyperparameters and augmentations, as this is what the model was designed and optimized for. However, if you want to compare the effect of different augmentations on the model's performance, you can try disabling certain augmentations and measuring the impact on accuracy and other metrics. Keep in mind that removing or modifying augmentations may affect the model's generalization ability and may not reflect its true performance in real-world scenarios.

**Comment by mabubakarsaleem** [comment]
So,how can we select that which result is best by evaluating accuracies from "split=val" command , because whenever i run this command  
"yolo detect val model=path/best.pt  data=path/data.yaml split=val" , i found different results of accuracy because of augmentation.

**Comment by glenn-jocher** [comment]
@mabubakarsaleem evaluating accuracy is a crucial step in benchmarking your model's performance. When running the `yolo detect val` command, you may get different results of accuracy due to the use of different augmentations. One way to handle this is to keep a record of the hyperparameters and augmentations used for your experiments, and report the best result obtained with those parameters. This allows for fair comparisons with other models and methods that use the same set of hyperparameters and augmentations. Additionally, it's important to keep in mind that accuracy is just one measure of performance, and that other metrics such as precision, recall, and F1 score may also be informative depending on the task and application.
