### ISSUE TITLE
Not getting any results.csv file saved in the val folder after validating a dataset on a trained mode

### ISSUE THREAD

**Issue by Zidny000** [ultralytics/ultralytics#10359]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have cloned the ultralytics repo and trained the mode on my custom dataset.

Here is the command for training 
!yolo task=segment mode=train model=yolov8x-seg.pt data={dataset}/data.yaml epochs=100 imgsz=640

After this I get a results.csv inside train folder. But when I use the below command for validation on a new datase
!yolo task=segment mode=val model=F:/Zidny/YOLO/ultralytics/runs/segment/train/weights/best.pt data={dataset}/data.yaml iou=0.5 imgsz=640 
[Changed the location in data.yaml for the new dataset]

I don't see any results.csv file in the val folder

**Comment by glenn-jocher** [comment]
Hey there! 😊 It looks like you're experiencing some issues with getting a `results.csv` file after model validation. Usually, Ultralytics YOLO implementation indeed saves a `results.csv` after each training session within the training folder, which logs metrics across epochs. For validation, metrics are directly printed to the console rather than saved to a `results.csv` file by default.

However, if you'd like to save the validation metrics, a quick workaround is to redirect the console output to a file manually. Here's how you can modify your validation command:

```bash
!yolo task=segment mode=val model=F:/Zidny/YOLO/ultralytics/runs/segment/train/weights/best.pt data={dataset}/data.yaml iou=0.5 imgsz=640 > validation_results.csv
```

This command will save the console output (which includes your validation metrics) to `validation_results.csv`. You can adjust the file name as per your preference. Just remember, this file will be saved in the directory from where you run the command, so you might want to specify a full path if you have a specific folder in mind. 

Hope this helps! Let us know if there's anything else we can do for you. 🚀
