### ISSUE TITLE
subprocess-exited-with-error while doing 'pip install deepsparse'

### ISSUE THREAD

**Issue by dhrhkddns** [ultralytics/ultralytics#10384]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Downloading deepsparse-1.7.1.tar.gz (46.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.6/46.6 MB 6.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Loaded version 1.7.1 from C:\Users\ION\AppData\Local\Temp\pip-install-kyofho_m\deepsparse_88e2857e65a543459f6c70f0bc12ff2f\src\deepsparse\version.py
      Traceback (most recent call last):
        File "C:\Users\ION\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\ION\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\ION\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\ION\AppData\Local\Temp\pip-build-env-t0ziloty\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\ION\AppData\Local\Temp\pip-build-env-t0ziloty\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\ION\AppData\Local\Temp\pip-build-env-t0ziloty\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\ION\AppData\Local\Temp\pip-build-env-t0ziloty\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 220, in <module>
        File "<string>", line 181, in _check_supported_system
      OSError: Native Windows is currently unsupported for DeepSparse. Please run on a Linux system or within a Linux container on Windows. More info can be found in our docs here: https://docs.neuralmagic.com/deepsparse/source/hardware.html
      [end of output]

error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### Environment

Ultralytics YOLOv8.2.4 🚀 Python-3.10.11 torch-2.3.0+cpu CPU (Intel Core(TM) i5-8500 3.00GHz)
Setup complete ✅ (6 CPUs, 15.9 GB RAM, 40.7/80.0 GB disk)

OS                  Windows-10-10.0.19044-SP0     
Environment         Windows
Python              3.10.11
Install             pip
RAM                 15.95 GB
CPU                 Intel Core(TM) i5-8500 3.00GHz
CUDA                None

matplotlib          ✅ 3.8.4>=3.3.0   
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.3.0>=7.1.2  
pyyaml              ✅ 6.0.1>=5.3.1   
requests            ✅ 2.31.0>=2.23.0 
scipy               ✅ 1.13.0>=1.4.1  
torch               ✅ 2.3.0>=1.8.0   
torchvision         ✅ 0.18.0>=0.9.0  
tqdm                ✅ 4.66.2>=4.64.0 
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by dhrhkddns** [comment]
![subprocess-exited-with-error-deepsparse-install](https://github.com/ultralytics/ultralytics/assets/59607551/d6dcc2ef-d6b8-45ef-906c-7ecfba8eb0ca)

**Comment by glenn-jocher** [comment]
@dhrhkddns hello and thank you for reaching out with your issue! 🙌

From the error message you've shared, it appears that `deepsparse` installation has failed because the library currently does not support native Windows environments directly. The message specifically mentions: 

```
OSError: Native Windows is currently unsupported for DeepSparse. Please run on a Linux system or within a Linux container on Windows.
```

A workaround for this is to use WSL (Windows Subsystem for Linux) on your Windows machine. WSL allows you to run a Linux environment directly on Windows, sans the overhead of a traditional virtual machine or dualboot setup.

Here's how you can get started with WSL and then attempt installing `deepsparse` again:
1. Install WSL following the [official guide](https://docs.microsoft.com/en-us/windows/wsl/install).
2. Once WSL is setup and you have your Linux distribution of choice installed, you can open a WSL terminal.
3. In the WSL terminal, try installing `deepsparse` again using pip.

If running on Linux isn't a possibility for your current setup, we'd recommend keeping an eye on the `deepsparse` [GitHub repo](https://github.com/neuralmagic/deepsparse) or their [documentation](https://docs.neuralmagic.com/deepsparse/source/hardware.html) for future updates regarding Windows support.

If you encounter any further issues or have more questions, feel free to reach out. Happy coding!
