### ISSUE TITLE
Wrong exported ouptut size for OBB task should be (1, 7, 8400) instead of (1, 6, 8400)

### ISSUE THREAD

**Issue by wojciechpolchlopek** [ultralytics/ultralytics#10410]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

PyTorch: starting from 'best-obb.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 6, 8400) (50.8 MB)

TorchScript: starting export with torch 2.3.0+cu121...
TorchScript: export success ✅ 2.2s, saved as 'best-obb.torchscript' (101.2 MB)

Export complete (4.2s)
Results saved to /home/wojpol/Desktop/repo_gitlab/triton-client
Predict:         yolo predict task=obb model=best-obb.torchscript imgsz=640  
Validate:        yolo val task=obb model=best-obb.torchscript imgsz=640 data=config.yaml  
Visualize:       https://netron.app
💡 Learn more at https://docs.ultralytics.com/modes/export

### Environment

Ultralytics YOLOv8.2.2 🚀 Python-3.9.19 torch-2.3.0+cu121 CPU (Intel Core(TM) i7-10870H 2.20GHz)
YOLOv8m-obb summary (fused): 237 layers, 26400646 parameters, 0 gradients, 80.8 GFLOPs

### Minimal Reproducible Example

``` yolo export model=best-obb.pt format='torchscript' ```

### Additional

I cannot evaluate exported model on triton-server due to truncated output dimension to 6 (local evaluation before export is fine)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello! Thanks for bringing this to our attention. 🛠

It looks like the output dimension discrepancy you're experiencing during the export of an OBB task model may be due to how the export process is handling the specific requirements for the oriented bounding box (OBB) output format.

For OBB, the expected output format should indeed include 7 values per detection (x_center, y_center, width, height, angle, confidence, class) instead of the 6 as you observed. This mismatch could potentially affect the evaluation of your model on platforms like Triton.

If you haven't already, I recommend checking the export configuration to ensure it's tailored for OBB tasks. It's possible that additional handling might be required to properly configure the model export to include the angle dimension in the output.

While an immediate code sample to fix this right out of the bat isn't available, diving into the export settings or potentially adjusting the output layer's specifications in your model definition might be necessary steps.

For now, please keep an eye on updates related to this issue, as it might require a more in-depth look to resolve. Contributions towards a fix are welcome if you have insights into adjusting the export process to accommodate OBB specific needs.

Thanks for your patience and for contributing to the YOLOv8 community! If any more details emerge on your end, feel free to share. 🌟

**Comment by wojciechpolchlopek** [comment]
Seems to be output problem for task='obb' - localy is ok
``` model = YOLO(f'best.torchscript', task='obb')
results = model('tests/assets/yolo_obb/1.jpg')
Loading best.torchscript for TorchScript inference...
image 1/1 /home/wojpol/Desktop/repo_gitlab/triton-client/tests/assets/yolo_obb/1.jpg: 640x640 319.8ms
Speed: 1.8ms preprocess, 319.8ms inference, 1.6ms postprocess per image at shape (1, 3, 640, 640)```
Exported model on triton server causes problem w NMS:
``` model = YOLO(f'http://localhost:8000/yolo_obb_2', task='obb')
results = model('tests/assets/yolo_obb/1.jpg')
Traceback (most recent call last):
  File "/snap/pycharm-community/378/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/home/wojpol/Desktop/repo_gitlab/triton-client/venv/lib/python3.9/site-packages/ultralytics/engine/model.py", line 101, in __call__
    return self.predict(source, stream, **kwargs)
  File "/home/wojpol/Desktop/repo_gitlab/triton-client/venv/lib/python3.9/site-packages/ultralytics/engine/model.py", line 274, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/wojpol/Desktop/repo_gitlab/triton-client/venv/lib/python3.9/site-packages/ultralytics/engine/predictor.py", line 204, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/home/wojpol/Desktop/repo_gitlab/triton-client/venv/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/wojpol/Desktop/repo_gitlab/triton-client/venv/lib/python3.9/site-packages/ultralytics/engine/predictor.py", line 290, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "/home/wojpol/Desktop/repo_gitlab/triton-client/venv/lib/python3.9/site-packages/ultralytics/models/yolo/obb/predict.py", line 32, in postprocess
    preds = ops.non_max_suppression(
  File "/home/wojpol/Desktop/repo_gitlab/triton-client/venv/lib/python3.9/site-packages/ultralytics/utils/ops.py", line 231, in non_max_suppression
    output = [torch.zeros((0, 6 + nm), device=prediction.device)] * bs
RuntimeError: Trying to create tensor with negative dimension -990: [0, -990]
```
I coud run with task='detect' but output is invalid (scores > 1)
```model = YOLO(f'http://localhost:8000/yolo_obb_2', task='detect')
results = model('tests/assets/yolo_obb/1.jpg')
image 1/1 /home/wojpol/Desktop/repo_gitlab/triton-client/tests/assets/yolo_obb/1.jpg: 640x640 300 class2s, 237.3ms
Speed: 2.0ms preprocess, 237.3ms inference, 54.2ms postprocess per image at shape (1, 3, 640, 640) ```
**Seems that model is run by default on 'detect' task - can I configure the task in config.pbtxt?**

**Comment by glenn-jocher** [comment]
Hey there! 👋 It looks like you're experiencing a couple of issues with your OBB model, particularly around the non-max suppression (NMS) process and task configuration, especially when deploying on Triton.

For the NMS issue, it seems like the model output might not be matching the expected format, especially if the number of outputs or the class scores are causing exceptions. As you observed, exporting the model with `task='obb'` should indeed adjust the output format accordingly.

Regarding your question on setting the task in `config.pbtxt` for Triton, unfortunately, Triton's configuration files do not directly support this kind of high-level model configuration as you would usually define in Ultralytics YOLO settings. Instead, you might consider wrapping the model inference within a custom model class or script where you explicitly set the task type before loading and running inference with the model. This can be done in your Python script that interacts with the Triton server rather than attempting to configure it through Triton's `config.pbtxt`.

Here's a quick example of how you might wrap your model inference to ensure the `task='obb'` is used:

```python
# Custom wrapper for OBB task before sending to Triton for inference
class CustomYOLOOBB:
    def __init__(self, model_path, task='obb'):
        self.model = YOLO(model_path, task=task)
    
    def predict(self, image_path):
        results = self.model(image_path)
        return results

# Use the custom class with your model URL and task
model_wrapper = CustomYOLOOBB(f'http://localhost:8000/yolo_obb_2', task='obb')
results = model_wrapper.predict('tests/assets/yolo_obb/1.jpg')
```

This way, you ensure that your model is always loaded with the correct task type before running inference. Feel free to adjust the snippet to fit your deployment setup!

If you're still encountering issues, revisiting the export process and ensuring the model is exported correctly for the OBB task might also be beneficial. Sometimes, re-exporting with explicit arguments can help iron out these discrepancies.

Let us know how it goes, or if you have any more questions! 🌟

**Comment by wojciechpolchlopek** [comment]
Hi, Is there a way running raw yolov8 OBB model on triton with correct task ('obb') for the moment? When we can expect this issue fixed? Model wrapper could be a solution but it seems as a workaround of the issue.

**Comment by glenn-jocher** [comment]
Hello! 😊 Great question! As of now, setting the `task` explicitly for a YOLOv8 OBB model on Triton Inference Server isn't directly supported through `config.pbtxt`. However, we're aware of how beneficial this feature would be and are looking into more integrated solutions.

For the moment, the model wrapper technique is indeed a workaround, but it allows for flexibility in managing tasks until we have a more streamlined approach. Here's a minimal example on how to use the wrapper:

```python
class YOLOOBBWrapper:
    def __init__(self, model_url):
        self.model = YOLO(model_url, task='obb')
    
    def predict(self, image_path):
        return self.model(image_path)

model = YOLOOBBWrapper('model_url_here')
results = model.predict('path/to/image.jpg')
```

We're working on enhancing the experience and hope to have updates soon. Stay tuned to our GitHub repo for the latest! 🚀

**Comment by wojciechpolchlopek** [comment]
> Hello! 😊 Great question! As of now, setting the `task` explicitly for a YOLOv8 OBB model on Triton Inference Server isn't directly supported through `config.pbtxt`. However, we're aware of how beneficial this feature would be and are looking into more integrated solutions.
> 
> For the moment, the model wrapper technique is indeed a workaround, but it allows for flexibility in managing tasks until we have a more streamlined approach. Here's a minimal example on how to use the wrapper:
> 
> ```python
> class YOLOOBBWrapper:
>     def __init__(self, model_url):
>         self.model = YOLO(model_url, task='obb')
>     
>     def predict(self, image_path):
>         return self.model(image_path)
> 
> model = YOLOOBBWrapper('model_url_here')
> results = model.predict('path/to/image.jpg')
> ```
> 
> We're working on enhancing the experience and hope to have updates soon. Stay tuned to our GitHub repo for the latest! 🚀

Unfortunately I got same error...
```
ultralytics/utils/ops.py", line 231, in non_max_suppression
    output = [torch.zeros((0, 6 + nm), device=prediction.device)] * bs
RuntimeError: Trying to create tensor with negative dimension -991: [0, -991]
```

**Comment by glenn-jocher** [comment]
Hey there! Thanks for trying out the suggested workaround and reporting back. It appears the issue persists because the NMS operation is expecting a different dimension due to how the model was exported and now executed.

The problem seems more related to how the model predicts output dimensions rather than how it's wrapped. The wrapper influences the model loading and inference but not the intrinsic architecture or export mechanics.

Could you try explicitly defining the number of classes (`nc`) during model export? Sometimes, ensuring that the export settings fully line up with how the model was trained can resolve such issues. Here’s a quick modification you can apply to your export settings, specifying the number of classes explicitly, assuming your dataset has only one class:

```python
model = YOLO('path/to/model.pt', task='obb')
model.export('path/to/exported/model', format='torchscript', imgsz=640, nc=1)
```

Could you give this a try and see if it amends the issue? If not, I recommend revisiting the training or re-exporting process, ensuring all configurations align correctly.

Apologies for the inconvenience! We're here to help, so let us know how it goes!

**Comment by wojciechpolchlopek** [comment]
> ```python
> model.export('path/to/exported/model', format='torchscript', imgsz=640, nc=1)
> ```

SyntaxError: 'nc' is not a valid YOLO argument. :(

**Comment by glenn-jocher** [comment]
@wojciechpolchlopek hello! 😊 My apologies for the confusion. It looks like my previous code snippet included an incorrect parameter `nc` which isn't a valid argument during the export process for YOLO models. 

For addressing issues related to class numbers during export, it's key to ensure that your model was initially trained with the correct dataset configuration. Please verify that the dataset configurations used in training reflect the accurate number of classes.

If the problem persists, consider revisiting your training setup to confirm that all parameters align well with your model's intended deployment environment.

Here’s how you might re-export a TorchScript model assuming other settings are aligned correctly:

```python
model = YOLO('path/to/model.pt', task='obb')
model.export('path/to/exported/model', format='torchscript', imgsz=640)
```

Thanks for your patience and let us know if there's anything else we can help with! 🚀

**Comment by wojciechpolchlopek** [comment]
To clarify problem seems the local evaluation is correct on torchscript model but on triton seems to evaluate on task 'detect' instead of OBB 
I trained two models:
- nc = 1 -> exported size (1, 6, 8400)
- nc =2  -> exported size (1, 7, 8400)
--local evaluation on exported torchscript model is correct -> correctly detected two rotated frames (with high score) using
model = YOLO(f'best.torchscript', task='obb')
--evaluaion on triton caused RuntimeError: Trying to create tensor with negative dimension -991: [0, -991] - for model = YOLOOBBWrapper(f'http://localhost:8000/yolo_obb_1', task='obb')
--raw evaluation with triton_client.async_infer and ultralytics.utils.ops.non_max_suppression(
            data,
            conf_thres=0.5,
            iou_thres=0.4,
            nc=2,
            rotated=True,
            agnostic=True
        ) -> I got only one rotated frame with low score

**Comment by glenn-jocher** [comment]
Hello @wojciechpolchlopek! Thanks for the detailed clarification. It does indeed seem like the issue arises specifically during the evaluation on Triton, given that your local evaluations are correct. This might point towards a discrepancy in how Triton handles the exported model, particularly with respect to the task settings.

Before you report it as a separate issue, could you reconfirm the configurations and settings in your Triton deployment environment? Ensure that there isn't any residual configuration from previous deployments that might be interfering.

If after checking and confirming these settings the issue persists, then yes, it would be helpful to open a separate GitHub issue focusing on the Triton server evaluation discrepancies. This way, our team can focus directly on that aspect and assist you more efficiently.

Thanks for doing such thorough testing, and for your contributions to improving the model's robustness! 🚀

**Comment by wojciechpolchlopek** [comment]
I have checked once again all the configurations and have obtained same results - the new Issue is reported in https://github.com/ultralytics/ultralytics/issues/11757

**Comment by koikuchi1** [comment]
Additional Info:
I found same issue.
I use "Ultralytics 8.3.138 🚀 Python-3.10.12 torch-2.7.0+cu128 CPU"

I have trained a PyTorch model to classify 41 types of Mahjong tiles (3 colors × 9 numbers, 4 wind tiles, 3 dragon tiles including red dora, and 4 flower tiles: Spring, Summer, Autumn, Winter). I attempted to convert this model to TorchScript for deployment on a smartphone, but I noticed that the output tensor has only 46 elements, even though 47 are required when including all necessary elements.

I also tested exporting the OBB model using yolo export model=best.pt format=torchscript task=obb, but the output shape is still (1, 46, 8400) even though model.nc = 41.
I guess data format "center-x, center-y, width, height, class0~40"??

WHERE IS "confidence" ?
But, The last class (ID 40) appears to have incorrect scores, , and only 40 class scores are actually present in the output tensor. "THIS IS confidence !"

This suggests that the exporter is missing one class during export for OBB models, which leads to corrupted inference results.

Dear Ultralytics development team, please address this issue as soon as possible.

In Japanese
追加情報：
同じ問題を確認しました。
私は「Ultralytics 8.3.138 🚀 Python-3.10.12 torch-2.7.0+cu128 CPU」を使用しています。

私は麻雀牌を分類するPyTorchモデルを作成しました（3種の数牌×9種、風牌4種、ドラ牌3種（赤ドラ含む）、花牌4種：春・夏・秋・冬の合計41クラス）。
このモデルをスマートフォンに移植するためにTorchScript形式に変換しようとしましたが、必要な全要素を含めると47要素になるはずの出力テンソルが、46要素しか出力していないことに気づきました。

また、yolo export model=best.pt format=torchscript task=obb を使ってOBBモデルをエクスポートしても、出力の形状は model.nc = 41 にもかかわらず (1, 46, 8400) のままでした。
おそらく、データのフォーマットは "center-x, center-y, width, height, class0～class40" だと思われます。

では "confidence" はどこにあるのでしょうか？
最後のクラス（ID 40）のスコアが明らかにおかしく、出力テンソルには実際には40個のクラススコアしか存在していないようです。「この最後の値が confidence なのでは？」

これは、OBBモデルのエクスポート時にクラスが1つ欠落していることを示しており、結果として推論結果が破損してしまいます。

Ultralytics 開発チームの皆さん、早急な改善をお願いします。

**Comment by glenn-jocher** [comment]
Hello @koikuchi1! Thanks for the detailed report and the additional information. The output is correct. There's no separate confidence/objectness score. Just class scores. So for 41 classes, the expected shape is `(1, 46, 8400)`.
