### ISSUE TITLE
Yolo v8 track gets slower and slower over time

### ISSUE THREAD

**Issue by a-shumanski** [ultralytics/ultralytics#10420]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Hello,
I run YOLO8 track using live stream(RTSP) with 16FPS and resolution 640x480 and initially everything works as expected regarding the speed:

```640x480 (no detections), 5.1ms
Speed: 2.9ms preprocess, 4.6ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 640)
```
<img width="1059" alt="Screenshot 2024-04-29 at 18 37 08" src="https://github.com/ultralytics/ultralytics/assets/58070595/76e98bd9-e349-4f29-a5f3-ac7f4461a2e8">

but after around a 10min the speed significant decrease:

```640x480 (no detections), 5.1ms
Speed: 6.2ms preprocess, 5.1ms inference, 29.5ms postprocess per image at shape (1, 3, 640, 480)
```

The code looks like that:

```
camera1_lp_detector = YOLO('./models/license_plate_detector.engine', task='detect')

//...here I read the frames using python and pass them to queue and in the queue thread I do a track...

camera1_lp_detector.track(
            source=frame,
            persist=True,
            tracker="./tracker.yaml",
            conf=0.6,
            imgsz=[640, 480],
            max_det=1,
            verbose=True,
            device="0",
            stream=True,
        )
```
and tracker.yaml looks like that:
```tracker_type: bytetrack  # tracker type, ['botsort', 'bytetrack']
track_high_thresh: 0.5  # threshold for the first association
track_low_thresh: 0.1  # threshold for the second association
new_track_thresh: 0.6  # threshold for init new track if the detection does not match any tracks
track_buffer: 10  # buffer to calculate the time when to remove tracks
match_thresh: 0.8  # threshold for matching tracks
```

Have in your mind that the camera point to my wall so it detects and tracks nothing.

What can be the reason of getting slower over a time?

### Environment

ltralytics YOLOv8.2.2 🚀 Python-3.8.10 torch-2.0.0+nv23.05 CUDA:0 (Orin, 15388MiB)
Setup complete ✅ (8 CPUs, 15.0 GB RAM, 52.7/78.2 GB disk)

OS                  Linux-5.10.104-tegra-aarch64-with-glibc2.29
Environment         Linux
Python              3.8.10
Install             pip
RAM                 15.03 GB
CPU                 ARMv8 Processor rev 1 (v8l)
CUDA                11.4

matplotlib          ✅ 3.7.4>=3.3.0
opencv-python       ✅ 4.6.0.66>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 5.3.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.0.0+nv23.5>=1.8.0
torchvision         ✅ 0.15.2a0+fa99a53>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.7
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.0.2>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hey there! 👋 It seems like you're encountering an issue where tracking slows down over time. This gradual decrease in speed, especially noted in the post-processing duration, might be related to memory leaks or accumulating overhead due to the constant feed and processing in a live stream scenario.

Here are a couple of suggestions to look into:
- **Memory Management:** Check if there's any increase in memory usage over time. If so, it could indicate a memory leak which needs to be addressed.
- **Queue Management:** Since you're using a queue mechanism for frames, ensure it's optimally managed to prevent backlog or memory overflow.
- **Profile Your Code:** Try using Python profiling tools to identify any bottlenecks that occur over time.
- **Tracker Config Adjustments:** Temporarily adjust or simplify `tracker.yaml` settings to gauge performance impact.
- **Resource Monitoring:** Monitor CPU and GPU usage to see if there's an increased load affecting performance.

```python
# Example pseudocode for monitoring queue size
if frame_queue.qsize() > MAX_QUEUE_SIZE:
    logging.warning(f"Queue size is large ({frame_queue.qsize()}), consider adjusting flow or processing speed.")

# Also, consider clearing any non-essential data structures periodically if applicable.
```

It might also help to restart the tracker after a certain period or number of frames as a temporary workaround.

If the issue persists, feel free to share more details or any observations you make with the mentioned suggestions. The community and the Ultralytics team are here to help! 🚀
