### ISSUE TITLE
Validation of model converted.pt

### ISSUE THREAD

**Issue by avenger123456** [ultralytics/ultralytics#10427]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Val

### Bug

I trained a detection model and got a best.pt, When I use the data.yaml of my own. The result is fine. 
However, when I use some of the parameters of the best.pt to get a converted.pt just like gelan-c and yolov9-c. 
Then I use the same val command: yolo detect val data=my_own.yaml model='converted.pt' imgsz=640. to see the metrics . The bug occurs. It calls engine/trainer and use data=coco8.yaml which is not what I want.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@avenger123456 hello! 👋

Thank you for bringing this to our attention. It seems like there might be a misconfiguration issue causing the validation process to default to `coco128.yaml` instead of using your custom `data.yaml`. To ensure the correct dataset configuration file is being used during validation with your `converted.pt` model, please make sure that the `data` argument is correctly specified and points to your custom `my_own.yaml`. The command should look like this:

```bash
yolo detect val data=my_own.yaml model=converted.pt imgsz=640
```

If the issue persists, please check if `my_own.yaml` is correctly formatted and located in the expected directory. If everything seems correct yet the issue remains unsolved, there might be a need to delve deeper into the specifics of how `converted.pt` was generated and if any modifications might have affected its ability to correctly reference the specified dataset.

Feel free to share more details or ask further questions if needed. We're here to help!
