### ISSUE TITLE
TypeErrorTypeError: meshgrid() got an unexpected keyword argument 'indexing'

### ISSUE THREAD

**Issue by hbl843449791** [ultralytics/ultralytics#10431]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

File "/mnt/data/anaconda/envs/yolov8/lib/python3.8/site-packages/ultralytics/nn/modules/transformer.py", line 107, in build_2d_sincos_position_embedding
grid_w, grid_h = torch.meshgrid(grid_w, grid_h, indexing="ij")
    grid_w, grid_h = torch.meshgrid(grid_w, grid_h, indexing="ij")
TypeErrorTypeError: meshgrid() got an unexpected keyword argument 'indexing'

**Comment by hbl843449791** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/42711853/56a8c915-390d-456a-8a05-b242fba79474)

**Comment by hbl843449791** [comment]
The image shows the versions of each component: ultralytics==8.2.5  torch==2.0.0  torchvision==0.18.0,it seems like torch.meshgrid has the keyword argument 'indexing',why it say unexpected?

**Comment by glenn-jocher** [comment]
Hi @hbl843449791, thank you for the details! 🌟

The issue you're encountering with `torch.meshgrid()` and the `indexing` argument might be due to changes in the PyTorch API in version 2.0.0. It's possible that this version introduced or altered the behavior of the `indexing` keyword.

As a quick solution, you can modify the code to omit the `indexing` argument as follows:
```python
grid_w, grid_h = torch.meshgrid(grid_w, grid_h)
```
This uses the default indexing mode, which should suffice in most cases unless specific ordering is needed for your application.

Please try this modification, and let us know if it resolves your issue. If more adjustments are needed, I'm here to help!
