### ISSUE TITLE
`ultralytics.engine.results.BaseTensor.cpu()` does not return a tensor, `.numpy()` does not return an array.

### ISSUE THREAD

**Issue by TSoli** [ultralytics/ultralytics#10647]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

The `ultralytics.engine.results.BaseTensor.cpu()` does not return a tensor as described. The bug is similar for the `numpy()` method. See the implementations [here](https://github.com/ultralytics/ultralytics/blob/bc9fd45cdf10ebe8009037aaf8def2353761c9ed/ultralytics/engine/results.py#L41) . When `self.data` is a `torch.Tensor` (which I believe is most of the time) `cpu()` would not return the data as a tensor but rather just move the tensor to the CPU on a new instance of the object. If you call it again the data will still be a `torch.Tensor` and therefore it will just keep returning new instances of the object rather than the underlying data. Similarly, using `.numpy()` returns an instance of the object instead of the underlying data as suggested.

In most people probably use the other methods in the subclasses such as `Boxes.xy`. However, if you would like the segmentation masks from the segmentation model, the fact that these methods are broken means you would need to access `Masks.data` directly or use the `xy()` method and convert from segments back to the masks.

### Minimal Reproducible Example

```python3
from ultralytics import YOLO

model = YOLO("yolov8n-seg.pt")
results = model.predict("https://ultralytics.com/images/bus.jpg")
print(type(results[0].masks))
print(type(results[0].masks.cpu()))
print(type(results[0].masks.cpu().numpy()))
print(type(results[0].masks.data))
```

Outputs:
```
<class 'ultralytics.engine.results.Masks'>
<class 'ultralytics.engine.results.Masks'>
<class 'ultralytics.engine.results.Masks'>
<class 'torch.Tensor'>
```

Or for bboxes
```python3
from ultralytics import YOLO

model = YOLO("yolov8n.pt")
results = model.predict("https://ultralytics.com/images/bus.jpg")
print(type(results[0].boxes))
print(type(results[0].boxes.cpu()))
print(type(results[0].boxes.cpu().numpy()))
print(type(results[0].boxes.data))
```

Outputs:
```
<class 'ultralytics.engine.results.Boxes'>
<class 'ultralytics.engine.results.Boxes'>
<class 'ultralytics.engine.results.Boxes'>
<class 'torch.Tensor'>
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
👋 Hi there! Thanks for bringing this to our attention. It looks like there's a misunderstanding in how the `.cpu()` and `.numpy()` methods are intended to work with `BaseTensor` and its subclasses (`Boxes`, `Masks`, etc.).

These methods (`cpu()`, `numpy()`) are designed to be chainable and thus return the same object type (e.g., `Boxes`, `Masks`) for further processing, rather than directly returning the underlying data as a `torch.Tensor` or a numpy array. That's why you see the object type remains the same after calling `.cpu()` or `.numpy()`.

To access the underlying `torch.Tensor` directly, you can use the `.data` attribute as you've discovered. If you need a numpy array representation, do so from the `.data` attribute:

```python3
import numpy as np

# For masks
mask_tensor = results[0].masks.data  # This will be a torch.Tensor
mask_array = mask_tensor.numpy()  # Convert to numpy array if it's already on CPU

# For boxes
boxes_tensor = results[0].boxes.data
boxes_array = boxes_tensor.numpy()  # Convert to numpy array if it's already on CPU
```

Remember, to use `.numpy()` on a `torch.Tensor`, it needs to be on CPU memory, which `.cpu()` explicitly ensures.

We appreciate your interest in helping with a PR! A potential improvement could be to clarify this behavior in the documentation to prevent confusion. Contributions to the docs would be wonderful! Let us know if you need any further information or guidance. 😊

**Comment by TSoli** [comment]
Thank you for the info. I would be happy to help with documenting this behaviour a bit more clearly soon when I have the time to read about how to contribute. If I have any problems understanding that I will let you know.

**Comment by glenn-jocher** [comment]
That sounds fantastic! We'd greatly appreciate your contributions to the documentation. 📚 If you encounter any obstacles or have questions about the contribution process, feel free to reach out. Happy coding!
