### ISSUE TITLE
Why yolov5m6 != yolov5m6 --imgsz 1280

### ISSUE THREAD

**Issue by maximereder** [ultralytics/ultralytics#1066]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

I'm training model to detect smalls persons in images. I choose a yolov5m6 weight because it is said that it can infer much larger image in architecture (1280). 
However, I keep --imgsz 1280 in my command line (that was a mistake). 
I launched the training with --imgsz 1280  and without --imgsz 1280 and I note that training with --imgsz 1280 need more memory.

I don't understand why there is a difference in memory consumption when the documentation states that yolov5m6 has an input image of 1280? 

Isn't yolov5m6 equal to yolov5 --imgsz 1280?

Thanks

**Comment by glenn-jocher** [comment]
Larger images require more memory.

**Comment by maximereder** [comment]
All rights, so what is the difference between yolov5m6 and yolov5 --imgsz 1280 ?

**Comment by JustasBart** [comment]
@maximereder I believe that yolov5/yolov8 will always use 640x640 by default no matter what. Can you please confirm that if you run either configuration the output log will contain the **imgsz** parameter value just before it starts crunching **Epochs**.

Can you please look this up and confirm that it's 1280 and 1280 opposed to 640 and 1280?

Thanks and good luck! :rocket:

**Comment by maximereder** [comment]
@JustasBart I look up and I confirm 
yolov5m6 => Image sizes 640 train, 640 val
yolov5m --imgsz 1280 => Image sizes 1280 train, 1280 val

I don't understand the influence of --imgsz if model always resize to 640 ? (or 1280 if yolov5m6) ?

**Comment by JustasBart** [comment]
@maximereder Okay well there's the problem then and also I understand your confusion, but I'm not sure if you're aware that the difference between the p5 models and p6 models (the 640x640 and 1280x1280) is basically just the stride size. Meaning that the p5 (640x640) models (Or the regular models) use a 32x32 kernel to run inference and hence they are by default trained as 640x640 models, however, you can still take a p5 model and train it as 1280x1280 or as anything else that you'd like...

See the confusion is that the p6 models (1280x1280) have a stride of 64 meaning 64x64 kernels and thus by default they were trained as 1280x1280, but you can still train a p6 model as 640x640 and or as a 2560x2560 or as anything else that you'd like...

Therefore if you pass in a p6 model and don't specify **imgsz** being 1280x1280 it'll still default to 640x640 and that will still work just fine as the pre-trained model sizes are not fixed in any way and are simply there for your convenience.

What do I mean by convenience? I mean if you want your final network to be say 1280x768 it would make more sense for you to start off with a p6 model (stride 64) that was already trained on 1280x1280 opposed to starting with a p5 model that was trained on 640x640, however, be fully aware that this is not always the case either as sometimes you would still want a p5 model trained as 1280x768 simply because you might need the stride to be smaller in order to detect smaller objects!

There's always a trade-off between these things in the end but anyway I digress in that to answer your question none of the models are of fixed size and you can train it as whatever you'd like hence why this is happening.

All the best to you and good luck using Ultralytics YOLO models! :rocket:

**Comment by maximereder** [comment]
Ok thanks for your explanation!

**Comment by pderrenger** [comment]
@maximereder you're welcome! If you have any more questions or need further clarification, feel free to ask. Good luck with your YOLO models and happy coding! :rocket:
