### ISSUE TITLE
The colors for the evaluation curves get repeated with more than 10 classes

### ISSUE THREAD

**Issue by Legor** [ultralytics/ultralytics#1079]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

When running the validation on a dataset with more than 10 classes, the colors for the plotted lines, e.g. in F1_curve, get repeated.
This makes single lines with the same color indistinguishable from each other.

This is a known limitation of matplotlib plots, however can be avoided when the used colormap is configured explicitly, e.g.

 ```python
N_classes = 20
# choose colormap
cm = plt.get_cmap('gist_rainbow')
fig = plt.figure()
ax = fig.add_subplot(111)
ax.set_prop_cycle('color', [cm(1.*i/N_classes ) for i in range(N_classes)])
```

### Use case

Improve the interpretability of evaluation plots for more than 10 classes.

### Additional

Code example based on stackoverflow question:
https://stackoverflow.com/questions/53199728/how-can-i-stop-matplotlib-from-repeating-colors

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Legor hi buddy. Yes that's correct. Most colormaps are limited to i.e. 10 or 20 colors to ensure sufficient difference to the human eye, so this is not really a bug but intentional. In any case you can modify the default Ultralytics colormap here and add/remove colors as you see fit:
https://github.com/ultralytics/ultralytics/blob/f2a7a29e531ad029255c8ec180ff65de24f42e8d/ultralytics/yolo/utils/plotting.py#L22-L39
