### ISSUE TITLE
Problem with imgsz and rect=True

### ISSUE THREAD

**Issue by bzisl** [ultralytics/ultralytics#1103]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

When used rect=True and imagsz=[x,y], an error appears:

Original Traceback (most recent call last):
  File "/home/paco/AI/aistage4/yolov8_venv/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "yolov8_venv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "yolov8_venv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "yolov8/ultralytics/yolo/data/base.py", line 179, in __getitem__
    return self.transforms(self.get_label_info(index))
  File "yolov8/ultralytics/yolo/data/base.py", line 183, in get_label_info
    label["img"], label["ori_shape"], label["resized_shape"] = self.load_image(index)
  File "yolov8/ultralytics/yolo/data/base.py", line 125, in load_image
    r = self.imgsz / max(h0, w0)  # ratio
TypeError: unsupported operand type(s) for /: 'ListConfig' and 'int'

A posible solution is to change line 125 of base.py:
`            r = max(self.imgsz) / max(h0, w0)  # ratio`

### Environment

Ultralytics YOLOv8.0.9 🚀 Python-3.8.10 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090, 24268MiB)
Setup complete ✅ (32 CPUs, 125.7 GB RAM, 702.1/1758.9 GB disk)
Ubuntu 22.04

### Minimal Reproducible Example

`model.train(data='', imgsz=[512,384], rect=True)`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by JustasBart** [comment]
Hi @bzisl many are confused by this initially but the answer and the solution is quite simple really!

To train call:

`model.train(data='', imgsz=512, rect=True)`

And to export call:
```
yolo export \
model=yolov8m.pt \
imgsz=[384,512] \
opset=12 \
format=onnx
```
(Sorry I only have this example based on CLI)

The idea is that the training will look at your highest dimensions (Which I assume you have it as width=512 and height=384) and it'll work out the other dimension such so that you can actually still export it as a different dimensions say 416 or 352 etc... (Stride 32) meaning you don't have to give it the specific size when Training and inf fact it won't even like that as you've just found out :smile: 

Good luck! :rocket:

**Comment by bzisl** [comment]
Thanks for your reply!
One question were I always confused. To export:
`yolov8.export(format='onnx', imgsz=[512,384]) `
Is the order of imgsz right (imgsz=[x,y]) or is it in reverse order?

**Comment by JustasBart** [comment]
To export it's [Height, Width] or in your example it would be [y, x] it's a bit of a gotcha!

Good luck! :rocket:

**Comment by bzisl** [comment]
Thanks a lot!

**Comment by Laughing-q** [comment]
@JustasBart @bzisl closing the issue as it seems to be solved! feel free to reopen it if you still have related issues. :)
