### ISSUE TITLE
Segmentation of object with holes

### ISSUE THREAD

**Issue by alexcbb** [ultralytics/ultralytics#1106]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, it's been a while that I search a way to train YOLO to segment objects that could contain holes, for example a cup as you can see here got an handle and the segmentation contains a hole :
![0000-000666-color](https://user-images.githubusercontent.com/16562497/220672012-676ab574-2b58-4d69-8f55-c3018c5422ee.png)
![000666-label](https://user-images.githubusercontent.com/16562497/220672643-16738d35-1240-4464-8621-81a4cd325465.png)

I've searched a way to get the polygon around the object by taking account the hole but didn't found any solution. My segmentation masks are .png that contains the objects id's  at each pixel. Isn't it a way to convert those files to masks adapted to YOLO ?

Thank you !

**Comment by JustasBart** [comment]
I would really like to find out more about this as well!
@alexcbb As far as I know it's not currently possible, but I would love to know if anyone has any input on this!

**Comment by Laughing-q** [comment]
@alexcbb @JustasBart For now I can only  think of the following solution to solve this:
- find the segment coordinates of both the cup and the hole, which `cv2.findContours` can do it.
- mark these holes as a specific class, probably class_id: `-1`
- find these segment coordinates marked `-1` and make these areas 0 pixel when generating masks from segment coordinates.

But this needs to modify the code a lot and the whole workflow looks complicated.
Probably we should also support accepting mask images as labels as well which the workflow is simpler and easier for this situation.🤔 @glenn-jocher @AyushExel

**Comment by JustasBart** [comment]
@Laughing-q Yeah, I think that naturally having the ability to present images and masks to get a new mask out would be rather powerful and would in a sense be the next step for Segmentation! Not sure how difficult of a task this is though...

Would love to see it but let's see :rocket:

**Comment by alexcbb** [comment]
Thank you for your responses and yes my pipeline was already using opencv to do it with findcontours (and it's not always accurate, so a bit bothering)

**Comment by PallottaEnrico** [comment]
Any updates? Directly using masks instead of polygons as labels would be great.

**Comment by pderrenger** [comment]
@PallottaEnrico i understand the inconvenience of relying on `cv2.findContours` for accurate segment extraction. While direct utilization of masks as labels would indeed streamline the process, this feature isn't currently available in YOLOv8. The workflow you suggested could potentially address this hurdle, although it may require extensive code modifications.

Your feedback is valuable, and I'll ensure it reaches the development team for consideration. Thanks for your input!

**Comment by ryouchinsa** [comment]
Using the script [general_json2yolo.py](https://github.com/ryouchinsa/Rectlabel-support/blob/master/general_json2yolo.py), you can convert the RLE mask with holes to the YOLO segmentation format.

The RLE mask is converted to a parent polygon and a child polygon using `cv2.findContours()`.
The parent polygon points are sorted in clockwise order. 
The child polygon points are sorted in counterclockwise order.
Detect the nearest point in the parent polygon and in the child polygon.
Connect those 2 points with narrow 2 lines.
So that the polygon with a hole is saved in the YOLO segmentation format.

```
def is_clockwise(contour):
    value = 0
    num = len(contour)
    for i, point in enumerate(contour):
        p1 = contour[i]
        if i < num - 1:
            p2 = contour[i + 1]
        else:
            p2 = contour[0]
        value += (p2[0][0] - p1[0][0]) * (p2[0][1] + p1[0][1]);
    return value < 0

def get_merge_point_idx(contour1, contour2):
    idx1 = 0
    idx2 = 0
    distance_min = -1
    for i, p1 in enumerate(contour1):
        for j, p2 in enumerate(contour2):
            distance = pow(p2[0][0] - p1[0][0], 2) + pow(p2[0][1] - p1[0][1], 2);
            if distance_min < 0:
                distance_min = distance
                idx1 = i
                idx2 = j
            elif distance < distance_min:
                distance_min = distance
                idx1 = i
                idx2 = j
    return idx1, idx2

def merge_contours(contour1, contour2, idx1, idx2):
    contour = []
    for i in list(range(0, idx1 + 1)):
        contour.append(contour1[i])
    for i in list(range(idx2, len(contour2))):
        contour.append(contour2[i])
    for i in list(range(0, idx2 + 1)):
        contour.append(contour2[i])
    for i in list(range(idx1, len(contour1))):
        contour.append(contour1[i])
    contour = np.array(contour)
    return contour

def merge_with_parent(contour_parent, contour):
    if not is_clockwise(contour_parent):
        contour_parent = contour_parent[::-1]
    if is_clockwise(contour):
        contour = contour[::-1]
    idx1, idx2 = get_merge_point_idx(contour_parent, contour)
    return merge_contours(contour_parent, contour, idx1, idx2)

def mask2polygon(image):
    contours, hierarchies = cv2.findContours(image, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_TC89_KCOS)
    contours_approx = []
    polygons = []
    for contour in contours:
        epsilon = 0.001 * cv2.arcLength(contour, True)
        contour_approx = cv2.approxPolyDP(contour, epsilon, True)
        contours_approx.append(contour_approx)

    contours_parent = []
    for i, contour in enumerate(contours_approx):
        parent_idx = hierarchies[0][i][3]
        if parent_idx < 0 and len(contour) >= 3:
            contours_parent.append(contour)
        else:
            contours_parent.append([])

    for i, contour in enumerate(contours_approx):
        parent_idx = hierarchies[0][i][3]
        if parent_idx >= 0 and len(contour) >= 3:
            contour_parent = contours_parent[parent_idx]
            if len(contour_parent) == 0:
                continue
            contours_parent[parent_idx] = merge_with_parent(contour_parent, contour)

    contours_parent_tmp = []
    for contour in contours_parent:
        if len(contour) == 0:
            continue
        contours_parent_tmp.append(contour)

    polygons = []
    for contour in contours_parent_tmp:
        polygon = contour.flatten().tolist()
        polygons.append(polygon)
    return polygons 

def rle2polygon(segmentation):
    if isinstance(segmentation["counts"], list):
        segmentation = mask.frPyObjects(segmentation, *segmentation["size"])
    m = mask.decode(segmentation) 
    m[m > 0] = 255
    polygons = mask2polygon(m)
    return polygons
```

The RLE mask.

![スクリーンショット 2023-11-22 1 57 52](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/df2dfad5-a13f-49c6-818a-8aba1d3ce83c)

The converted YOLO segmentation format.

![スクリーンショット 2023-11-22 2 11 14](https://github.com/ryouchinsa/Rectlabel-support/assets/1954306/cc34027a-075f-4b67-8de7-bd2dddddac59)

To run the script, put the COCO JSON file coco_train.json into `datasets/coco/annotations`.
Run the script. `python general_json2yolo.py  `
The converted YOLO txt files are saved in `new_dir/labels/coco_train`.

![スクリーンショット 2023-11-23 16 39 21](https://github.com/ultralytics/JSON2YOLO/assets/1954306/c3d98120-66f5-4cb8-b74d-a500f0bd811d)

Edit use_segments and use_keypoints in the script.

```
if __name__ == '__main__':
    source = 'COCO'

    if source == 'COCO':
        convert_coco_json('../datasets/coco/annotations',  # directory with *.json
                          use_segments=True,
                          use_keypoints=False,
                          cls91to80=False)
```

To convert the COCO bbox format to YOLO bbox format.
```
use_segments=False,
use_keypoints=False,
```

To convert the COCO segmentation format to YOLO segmentation format.
```
use_segments=True,
use_keypoints=False,
```

To convert the COCO keypoints format to YOLO keypoints format.
```
use_segments=False,
use_keypoints=True,
```

This script originates from Ultralytics [JSON2YOLO](https://github.com/ultralytics/JSON2YOLO) repository.
We hope this script would help your business.

**Comment by glenn-jocher** [comment]
@ryouchinsa hello everyone, and thank you for the ongoing discussion about utilizing segmentation masks with YOLOv8. The workflow you described, involving mask conversion and direct usage, is indeed a sought-after feature. Currently, YOLOv8 does not natively support the direct use of segmentation masks as labels.

While the script that has been shared seems interesting and could be valuable for converting RLE masks to a YOLO-compatible format, users must adapt and integrate such procedures into their own processing pipelines as needed. In YOLOv8, the process for handling segmentation remains consistent with the definitions provided in our documentation.

I can see that the ability to use segmentation masks directly is a popular request; your interest and input helps us prioritize new features for future updates. Keep an eye on our repository for any official updates or announcements regarding new capabilities.

For further inquiries, please refer to our documentation, and thank you for being part of the community that helps improve YOLOv8. Your feedback is essential as we strive to enhance the model and its ecosystem.

**Comment by ryouchinsa** [comment]
Thanks for reviewing our script.
We checked whether YOLO can train polygon masks with holes with a small dataset.

[Donut images and YOLO segmentation text files](https://github.com/ryouchinsa/donut) to confirm that YOLO can train polygon masks with holes.

![mak-E-6fFmT1kAw-unsplash](https://github.com/ultralytics/JSON2YOLO/assets/1954306/aeba1a78-f51b-46fd-8939-878aae541bb9)

![aldrin-rachman-pradana-Ilt3lUJP-EA-unsplash](https://github.com/ultralytics/JSON2YOLO/assets/1954306/f3d23fc9-c34e-4fe1-a3eb-7b528dfdacd8)

![brooke-lark-5BbB3WPi128-unsplash](https://github.com/ultralytics/JSON2YOLO/assets/1954306/d1ff30ee-d87d-4ab3-833d-34bcddef00cc)

![xandreasw-NH2S3zVPMaE-unsplash](https://github.com/ultralytics/JSON2YOLO/assets/1954306/d850947f-66f1-434f-8edf-9aa86c6eced6)

**Comment by glenn-jocher** [comment]
@ryouchinsa it's great to see community members actively participating and creating resources that can potentially extend the capabilities of YOLOv8. Your initiative in testing polygon masks with holes and providing a dataset for others to verify this functionality is highly appreciated. While direct support for such features is not officially integrated into YOLOv8 as of now, contributions like yours demonstrate the adaptability and innovative spirit of the YOLO community.

For users interested in exploring polygon masks with holes, resources like the one shared can be a good starting point. However, please be mindful that any methods or scripts from external sources should be thoroughly tested and verified before integrating them into your main workflows.

The Ultralytics team is always working on improving the YOLO models, and community feedback plays a pivotal role in guiding these enhancements. We encourage continued sharing of ideas and tools, as this collaborative effort leads to a stronger and more versatile YOLO ecosystem.

Thank you once again for your contribution and for supporting the YOLOv8 project. Your insights and hands-on experiments help push the boundaries of what's possible with our models.

**Comment by lukas-buergi** [comment]
Hi.
I'm using YOLO because it saves me development effort. This issue almost made me switch to torchvision / Mask R-CNN and I'm still not quite done.

I wasn't going to use the rather long and complicated code by @ryouchinsa because I didn't want to check it. But it turns out this works too:

```
contours, _ = cv2.findContours(
                image, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE
            )
contours = [[p.flatten().tolist() for p in c] for c in contours]
contour_merged = contours.pop()
for contour in contours:
  contour_merged += contour + [contour_merged[-1]]

```
According to @TheOfficialOzone in https://github.com/ultralytics/ultralytics/issues/18131 YOLO uses cv2.fillPoly() to draw masks from the contours, and in my tests this function consistently drew correct masks from contours generated as above. In my case I know I only have one object in the frame, if you had multiple you would need to work with the hierarchy a bit which opencv can generate for you.

I'm not sure if this works because the contours are correct (I don't think so, they are degenerate in my opinion) or rather because of undocumented behavior of cv2.fillPoly(), but as long as it works I'm happy with it, for now.
