### ISSUE TITLE
Why can't I train and inference my model on my original image size?

### ISSUE THREAD

**Issue by brr53** [ultralytics/ultralytics#1113]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

All images in my training dataset are 300x300 pixels and all images I will be inferencing on are also 300x300 pixels.

Resizing images wastes hardware and time unnecessarily. I do not want to do imgsz (640, 640) resize on every inference. I don't feel that I need to resize at all.

Yolo does not allow me to train a model that allows for input of 300x300 image directly because it is not a multiple of 32. Why is this and how can I allow it to do so?

**Comment by Laughing-q** [comment]
@brr53 The `multiple of 32` is about the design of model architecture. The model has several downsample operations which eventually downsample the original image to its 1/32 size, so that's why we need a multiple of 32 as the size of input image. 

Regarding to the 640x640, actually you don't have to set 640 and you can set a number close to 300 in your case as long as it is a multiple of 32. i.e 288 or 320.

**Comment by glenn-jocher** [comment]
@brr53 just pass `--imgsz 300` during training and prediction and YOLO will scale automatically to the nearest valid imgsz, i.e. 288 or 320.

**Comment by valentin-fngr** [comment]
> @brr53 just pass `--imgsz 300` during training and prediction and YOLO will scale automatically to the nearest valid imgsz, i.e. 288 or 320.

Is it what you mean ? 

`yolo(torch.rand(1, 3, 360, 360), imgsz=192)`

Because this is not working for me
