### ISSUE TITLE
Export tensorrt to infer an error when specifying the image size

### ISSUE THREAD

**Issue by ohj666** [ultralytics/ultralytics#11179]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

```python
model = YOLO(r'./best.pt')
model.export(format='engine', imgsz=2048)
```
AssertionError: input size torch.Size([1, 3, 640, 640]) not equal to max model size (1, 3, 2048, 2048)

I executed this command to export the yolov8 model, but the exported tensorrt model reported an incorrect size error during inference. But the imgsz printed out during conversion is the 2048 I entered.

**Comment by glenn-jocher** [comment]
Hello! 😊 It looks like you're encountering an issue where the input size during the export doesn't match the model's maximum input size specified during the conversion process.

When exporting your model to TensorRT using a custom `imgsz` (image size), ensure that the exported model's inference input size matches the specified `imgsz`. The error you're encountering typically happens when there's a mismatch in the sizes expected by the model.

You can try specifying the `imgsz` during inference to match the size used during the export. Here's a snippet that might help:

```python
# Assuming you've already exported your model as shown in your question...

# Load your TensorRT model
model_trt = YOLO('path_to_exported_engine_file.engine')

# Specify the same imgsz for inference
results = model_trt.predict('path_to_your_image_or_video', imgsz=2048)
```

This makes sure that both during export and inference, the model works with the same image dimensions, thus avoiding any size mismatch issues.

If you continue experiencing issues or have more questions, feel free to ask. Good luck! 🚀

**Comment by ohj666** [comment]
> Hello! 😊 It looks like you're encountering an issue where the input size during the export doesn't match the model's maximum input size specified during the conversion process.
> 
> When exporting your model to TensorRT using a custom `imgsz` (image size), ensure that the exported model's inference input size matches the specified `imgsz`. The error you're encountering typically happens when there's a mismatch in the sizes expected by the model.
> 
> You can try specifying the `imgsz` during inference to match the size used during the export. Here's a snippet that might help:
> 
> ```python
> # Assuming you've already exported your model as shown in your question...
> 
> # Load your TensorRT model
> model_trt = YOLO('path_to_exported_engine_file.engine')
> 
> # Specify the same imgsz for inference
> results = model_trt.predict('path_to_your_image_or_video', imgsz=2048)
> ```
> 
> This makes sure that both during export and inference, the model works with the same image dimensions, thus avoiding any size mismatch issues.
> 
> If you continue experiencing issues or have more questions, feel free to ask. Good luck! 🚀

I appreciate your help so much that I forgot to give you feedback here to successfully solve the problem.

**Comment by glenn-jocher** [comment]
We're glad to hear that your issue was resolved successfully! If you have any more questions in the future or need further assistance, don't hesitate to reach out. Happy coding! 🌟
