### ISSUE TITLE
KeyError: 'step' when resume training from previous checkpoint

### ISSUE THREAD

**Issue by hdkhang6803** [ultralytics/ultralytics#11188]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hi, I have the same issue when resume training from the last checkpoint.

I am using Kaggle with GPU T4x2. I have trained the YOLOv9 and YOLOv8 on my custom dataset and retrieved best.pt and last.pt for each model. I want to resume training with more epoch on the next run but it throws the error:
---------------------------------------------------------------------------------------------------------------------------------------
File /opt/conda/lib/python3.10/site-packages/torch/optim/adamw.py:84, in AdamW.setstate(self, state)
81 group.setdefault("fused", None)
82 state_values = list(self.state.values())
83 step_is_tensor = (len(state_values) != 0) and torch.is_tensor(
---> 84 state_values[0]["step"]
85 )
86 if not step_is_tensor:
87 for s in state_values:

KeyError: 'step'
---------------------------------------------------------------------------------------------------------------------------------------
The configs for the model are:

from ultralytics import YOLO
model_path = '/kaggle/input/yolov9-train-epoch5/last_checkpoint/yolov9_last_epoch5_autobatch_time12.pt'
model = YOLO(model_path)

EPOCHS = 60
BATCH_SIZE = -1
OPTIMIZER = "auto"
SEED = 42
NAME = f"Yolov9_{EPOCHS}_freeze9"
DEVICE = [0]
VERBOSE = False
RESUME = False
PATIENCE = 20

model.train(
    data = "/kaggle/working/data.yaml",
    task = 'detect',
    imgsz = 1000,
    epochs = EPOCHS,
    batch = BATCH_SIZE,
    optimizer = OPTIMIZER,
    patience = PATIENCE,
    name = NAME,
    seed = SEED,
    val = True,
    resume = True,
    device = DEVICE,
    verbose = VERBOSE,
    save = True,
    save_period = 3,
    time=11, #kaggle limits
    freeze = 9
)

I have searched the Issues and found a similar bug where the other person fixed it by trying restarting docker but it does not work on kaggle.
# My question is that to resume training, I only need to set the resume flag to True and paste the path to the last.pt to my model as above right? And how can I solve the KeyError problem?

Thank you in advance.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello 👋,

Thanks for sharing the details about the issue you're encountering while trying to resume your training. It's great to see that you've done some digging into past issues and tried solutions like restarting the docker, although in this case, it didn't work as expected.

You're correct; to resume training, setting the `resume` flag to `True` should typically suffice, provided that you're pointing to the correct `.pt` file. However, the `KeyError: 'step'` error suggests there might be a mismatch or an issue with the state dictionary of the optimizer in the checkpoint file you're trying to resume from.

A common cause for this error is when the training gets interrupted in a very initial stage, and the checkpoint file may not have all the expected entries saved correctly.

Here's what you can try to potentially resolve this issue:
- Ensure that the `.pt` file you're trying to resume from (in this case `yolov9_last_epoch5_autobatch_time12.pt`) was saved properly and isn't corrupted.
- Since you're working in a Kaggle environment and mentioned a `docker` solution didn't apply, you might want to ensure that the environment does not have version conflicts or explore whether reinitializing your Kaggle kernel could help.
- Also, double-check the path to the `.pt` file to make sure it is correct and accessible from your current working environment.

If the problem persists, explicitly loading the `.pt` file before resuming might be another approach to consider, although based on your code, it looks like you're already doing this correctly.

Since this issue can sometimes be tricky to debug without more specific information about the environment and exact circumstances leading to the error, don't hesitate to provide any additional details if you continue facing this issue.

Hope this helps, and fingers crossed 🤞 you'll be able to resume your training smoothly.
