### ISSUE TITLE
What is the maximum number of classes yolov8 can learn?

### ISSUE THREAD

**Issue by Muffinnnnb** [ultralytics/ultralytics#1130]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to train a dataset with 260 classes.
Is learning possible in YOLOv8?
And what is the maximum number of classes that can be learned in YOLOv8?

**Comment by glenn-jocher** [comment]
@Muffinnnnb there is no maximum number of classes, though naturally as you add more classes the performance on each class will decrease slightly. 

Objects365.yaml has 365 classes for example and trains well.

**Comment by Krilaria** [comment]
I have dataset with 4600 classes and it seems that I near the limit of YOLO.

**Comment by glenn-jocher** [comment]
@Krilaria hi there! While YOLOv8 doesn't have a hard-set limit on the number of classes, training with a very high number of classes like 4600 can be challenging in terms of model performance and required computational resources. If you're experiencing issues, you might consider strategies such as simplifying the class structure if possible, or focusing on subsets of classes. Happy training! 😊

**Comment by zamanzamzz** [comment]
> I have dataset with 4600 classes and it seems that I near the limit of YOLO.

@Krilaria Can you elaborate a bit on how the 4600 class dataset nears the limit of YOLO?

Is it the amount if time it takes to perform an inference on single frame, or is it the accuracy?

**Comment by simonmoya** [comment]
I have 1200 categories to train in a YoLo detection algoritm, the new version 12 can support easily?

**Comment by glenn-jocher** [comment]
@simonmoya yOLO12 is not recommended for any use case due to training instability and high resource demands. For 1200 classes, we recommend **YOLO11**, which handles large class counts effectively when properly trained on a high-quality dataset. The number of classes doesn't inherently "max out" YOLO models, but performance depends on your dataset quality, resolution, and computational resources. For implementation details, see the YOLO11 documentation.
