### ISSUE TITLE
adreno GPU

### ISSUE THREAD

**Issue by wofvh** [ultralytics/ultralytics#1132]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

im using qualcomm adreno GPU but is it possible to run yolov8 with qualcomm adreno GPU ? 

### Use case

qualcomm RB5 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@wofvh we've made optimizations in YOLOv8 after learning that YOLOv5 was difficult to run on Qualcomm snapdragon devices due to 5th dimension ops. YOLOv8 inference never exceeds 4 dimensions, so it should be more compatible with Qualcomm devices in general, but we don't have experience implementing it ourselves on this hardware backend.
