### ISSUE TITLE
Is it possible for yolo to use Sharedmemory?

### ISSUE THREAD

**Issue by 00ffcc** [ultralytics/ultralytics#1140]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm running yolov8 on my 4050 laptop and its display memory is quite poor(6GB), which leads to low efficiency of GPU. So is it possilbe to use shared display memory?
<img width="484" alt="image" src="https://user-images.githubusercontent.com/52339737/221220716-8c6c1fb6-fbd5-4d58-94d3-1ef261de8fed.png">
<img width="765" alt="image" src="https://user-images.githubusercontent.com/52339737/221221145-971e7365-dce1-42ce-94fc-44af86c711e4.png">

**Comment by glenn-jocher** [comment]
@00ffcc I don't believe so

**Comment by glenn-jocher** [comment]
@00ffcc Hi! In general, using shared display memory is not recommended for deep learning tasks as it can result in lower performance due to the shared memory being used by the display system and other applications running on the computer. However, there are some techniques you can try to reduce the memory footprint of your YOLOv8 model such as reducing the batch size or using lower-resolution images for training and inference. Another option would be to train and run the model on a cloud-based GPU instance with more memory. I hope this helps!

**Comment by Ank221199** [comment]
@00ffcc what is the laptop model, it has 2 gpus ... interesting
