### ISSUE TITLE
YOLOV8 GPU train all loss is NAN  and P/R/map is 0

### ISSUE THREAD

**Issue by GUDENGYIN** [ultralytics/ultralytics#1148]
### Search before asking

- [ ] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

all loss is NAN and P/R/map is 0 when the user-defined data set GPU is trained! CUDA Change from 11.7 to 11.6 still can't train properly.Using the CPU works fine, but is often too long。Is there any solution？

1. **Environment**

- yolov8 install：
> pip install ultralytics
> pip install onnx
> pip install onnxruntime-gpu
>conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia

- Ultralytics YOLOv8.0.45   Python-3.9.16  torch-1.13.1+cu116 CUDA:0 (NVIDIA GeForce GTX 1660Ti, 6144MiB)
- Windows10 CPU:i7-10750H, 32 GB RAM
- command:yolo task=detect mode=train model=./datasets/yolov8s.yaml data=./datasets/dataset.yaml epochs=100  batch=10 imgsz=640 resume=True workers=4

2. **Datasets**
- Data sources: Open Images V6
- Dataset structure：
![dataset_struck](https://user-images.githubusercontent.com/48325199/221359270-79cadc21-bcc7-4591-ac42-3d1e7e02d55f.png)
![image](https://user-images.githubusercontent.com/48325199/221359265-e3cf0644-37e6-4d33-a5d0-3b5a420b08bc.png)
![image](https://user-images.githubusercontent.com/48325199/221359354-78995828-ffa7-4ae7-80a5-a4eaa04e9d25.png)
![image](https://user-images.githubusercontent.com/48325199/221359609-e87e7479-95b2-4194-b407-6d8b4f611685.png)
![image](https://user-images.githubusercontent.com/48325199/221359637-c3f18c5e-0198-435e-9fcd-c96ab2c46c2f.png)

3. **Result**

![result](https://user-images.githubusercontent.com/48325199/221358735-885481cb-6889-460f-aa43-85ecaedcc261.png)
![result2](https://user-images.githubusercontent.com/48325199/221358939-78983b1a-716d-401a-8b75-8180fbb8016c.png)

**Comment by glenn-jocher** [comment]
@GUDENGYIN if default datasets, i.e. coco128.yaml train correctly then it's likely your dataset has issues you may need to resolve, i.e. check your labels and adjust warmup and hyps as required for your custom dataset.

**Comment by GUDENGYIN** [comment]
Thank you very much for your guidance,But the same is true when I use the default COCO training set!Since I used yolov5 to v8, it seems that GTX16 series graphics card support is not friendly! Compatibility is always a problem.Yolov7 did not find this to be the case!

**Comment by MathewsJosh** [comment]
I am in the same situation, I have a GTX1650 and a 1660Ti and the "nan" problem only goes away from both of them when I set "device=cpu".

**Comment by jagprieto** [comment]
I have the same problem with a GEForge GTX 1080. The problem dissapears if the batch size is set to 2.

**Comment by 634739726** [comment]
> I am in the same situation, I have a GTX1650 and a 1660Ti and the "nan" problem only goes away from both of them when I set "device=cpu".

yes, I'm in the same situation as you

**Comment by MathewsJosh** [comment]
@glenn-jocher  Any news on this compatibility bug with GTX 16 series? Can we do anything to help you detect it?

**Comment by zhu000** [comment]
I have the same problem with the GTX1660Ti when I use coco128 dataset

**Comment by zhu000** [comment]
> > I am in the same situation, I have a GTX1650 and a 1660Ti and the "nan" problem only goes away from both of them when I set "device=cpu".
> 
> yes, I'm in the same situation as you

Maybe you can try this: https://zhuanlan.zhihu.com/p/165152789

**Comment by JianDan0212** [comment]
> > > I am in the same situation, I have a GTX1650 and a 1660Ti and the "nan" problem only goes away from both of them when I set "device=cpu".
> > 
> > 
> > yes, I'm in the same situation as you
> 
> Maybe you can try this: https://zhuanlan.zhihu.com/p/165152789

请问您解决上述问题了嘛

**Comment by zhu000** [comment]
好像是英伟达软件和16系显卡的问题，我降到pytorch 1.10.0 + cuda10.2后就没问题了

---Original---
From: ***@***.***&gt;
Date: Thu, Mar 16, 2023 18:10 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ultralytics/ultralytics] YOLOV8 GPU train all loss is NAN  andP/R/map is 0 (Issue #1148)




    
I am in the same situation, I have a GTX1650 and a 1660Ti and the "nan" problem only goes away from both of them when I set "device=cpu".
  
yes, I'm in the same situation as you
  
Maybe you can try this: https://zhuanlan.zhihu.com/p/165152789
  
请问您解决上述问题了嘛

**Comment by asanaa8** [comment]
Same problem with Nvidia Quadro T2000 with max Q design

**Comment by glenn-jocher** [comment]
#1601 may help here by allowing easy AMP disabling, i.e. yolo train amp=False

**Comment by YIN319** [comment]
> #1601 可能通过允许轻松禁用 AMP 来提供帮助，即 yolo 火车 amp=False
Thanks for your helpful reply

**Comment by glenn-jocher** [comment]
@YIN319 you're welcome! I hope that disabling Automatic Mixed Precision in the training process using the amp=False command will help resolve the issue you're encountering. Let us know if you have any further questions.

**Comment by Not-A-Psychic** [comment]
I am still getting:
      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/10      5.08G          1      2.393      1.489          5        640: 100%|██████████| 325/3
       
Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████
  all       1276       1508                   0          0          0          0

**Comment by glenn-jocher** [comment]
@Not-A-Psychic hi there, it looks like you may have encountered an issue where the loss values are not improving and the P/R/map scores are 0. This could be due to several factors, including improper dataset labeling, incorrect model configurations, or suboptimal training parameters. Here are a few suggestions to troubleshoot:

1. Check your dataset labels to ensure they are accurate and match the training set.
2. Double-check your model configurations, including the layer settings and input/output dimensions.
3. Make sure your training parameters, such as learning rate and batch size, are set appropriately for your data and model.
4. Try adjusting different training parameters one at a time to isolate the issue.
5. Check that your training dataset has enough diversity of classes and examples to train the YOLOv8 model effectively.

I hope some of these suggestions help you diagnose and resolve the issue you are experiencing. Let us know if you have any further questions or concerns.

**Comment by AhmetEkiz** [comment]
> #1601 may help here by allowing easy AMP disabling, i.e. yolo train amp=False

I have GTX 1650, and the same problem for the instance segmentation task. `amp=False` and batch=2 either didn't work.
Additionally, in Colab everything works fine for all cases, such as adding the `amp=False' flag.

**Comment by glenn-jocher** [comment]
@AhmetEkiz hi there,

Thank you for reaching out and sharing your experience. I understand that you are encountering issues with the instance segmentation task on a GTX 1650, even after attempting to disable Automatic Mixed Precision (AMP) using the `amp=False` flag and adjusting the batch size. 

It's great to hear that you have also tried running the code in Colab and it's working fine there. In such cases, it could be helpful to compare the software versions, configurations, and dependencies between your local environment and Colab to identify any potential differences that might be causing the issue.

If you have already double-checked the dataset labels, model configurations, and training parameters, and still haven't found a solution, I would recommend opening a new GitHub issue with details about your specific setup, including the versions of software, libraries, and dependencies you are using.

The YOLOv8 community and the Ultralytics team will be able to assist you further with troubleshooting the issue and finding a resolution.

Please let me know if you have any more questions or if there's anything else I can help you with.

**Comment by aabb1133** [comment]
ultralytics/yolo/cfg/default.yaml   modify the code on line 49:    `half: False`  
ultralytics/yolo/v8/detect/val.py    Comment out the 102nd line of code(  `self.args.half = self.device.type != 'cpu' `  ):`# self.args.half = self.device.type != 'cpu'  # force FP16 val during training` 
Ensure that the   `self.args.half`   value is False.

**Comment by glenn-jocher** [comment]
@aabb1133 hello,

Thank you for reaching out with your issue. I see that you are experiencing an error related to CUDA kernel accesses when running YOLOv8 on your RTX 3060 GPU.

To resolve this issue, you may need to update your CUDA version to a compatible version. I recommend using CUDA 11.1 or higher, as it has been tested and confirmed to work well with YOLOv8.

Additionally, please make sure that you have the correct versions of the required dependencies, such as PyTorch and torchvision, installed. You can refer to the Ultralytics YOLOv8 repository's `requirements.txt` file for the recommended versions.

If updating your CUDA version and dependencies does not resolve the issue, please consider opening a new GitHub issue with more specific details about your setup, including the versions of software and libraries you are using. This will allow the YOLOv8 community and the Ultralytics team to assist you further in finding a solution.

I hope this information helps! Let me know if you have any further questions or if there's anything else I can do to assist you.


Best regards,
Glenn Jocher

**Comment by aabb1133** [comment]
> 我的GPU：RTX 3060，我的问题：![图像](https://user-images.githubusercontent.com/48760748/250630471-4ec40426-7eb2-42ac-a650-b57b92af61ac.png)如何解决？

If there is a similar reason, you can try [this：](https://blog.csdn.net/2301_78783836/article/details/131526129)

**Comment by glenn-jocher** [comment]
@codewithleo1103 hello,

Thank you for reaching out with your GPU and issue. I understand that you are experiencing a problem with YOLOv8 on your RTX 3060 GPU. To address this issue, you can try the following steps:

1. Firstly, please make sure that you have the correct version of CUDA installed. You may need to update your CUDA version to a compatible version such as CUDA 11.1 or higher.
2. Ensure that you have the appropriate versions of the required dependencies, such as PyTorch and torchvision, installed. It is recommended to refer to the Ultralytics YOLOv8 repository's `requirements.txt` file for the recommended versions.
3. If updating CUDA and dependencies does not resolve the issue, you can also try referring to the link provided in the GitHub issue (https://blog.csdn.net/2301_78783836/article/details/131526129) for possible solutions.

Please note that the provided link is in Chinese and may have helpful information specific to your issue. However, it's important to exercise caution and verify the information before making any changes to your system.

If these steps do not resolve the issue, I recommend opening a new GitHub issue with more specific details about your setup so that the YOLOv8 community and the Ultralytics team can provide further assistance.

I hope this guidance helps! Let me know if you have any further questions or if there's anything else I can assist you with.

Best regards,
Glenn Jocher

**Comment by AkshajGupta** [comment]
Is there a translated version of https://blog.csdn.net/2301_78783836/article/details/131526129 in English?

**Comment by andresinsitu** [comment]
Im getting the same error, it is weird. I can train yolov8s on batch=16 no problem, also yolov8s on batch=8, but if change to batch=4 it gives the 0 P R map bug. Also with models yolov8m and yolov8l on batch=2 gives the bug.

**Comment by glenn-jocher** [comment]
@andresinsitu hi there,

This is indeed a perplexing issue. Notably, training problems in neural networks can often arise due to various reasons. One probable explanation could be that the batch normalization layers behave differently depending upon the size of the batch, and might be leading to unstable training or other unexpected behavior when the batch size is reduced.

Experimenting with different hyperparameters, especially learning rate, might be worth trying as smaller batch sizes can sometimes require a smaller learning rate.

Also, it would be helpful to observe if there's any irregularity in the loss trends, since the metrics rely on the confidence scores which can be unstable if the loss goes to infinity or NAN. 

Remember, debugging machine learning problems can sometimes involve a bit of trial and error. Therefore, it's typically a good idea to experiment with different settings and analyze the outputs closely. 

I hope this helps! Don't hesitate to share any updates or additional details as they might be useful in resolving your issue.

**Comment by andresinsitu** [comment]
@glenn-jocher Thanks for your answer, how can I modify the hyperparameters?

**Comment by glenn-jocher** [comment]
@andresinsitu hello,

Modifying the hyperparameters in YOLOv8 can be done in the YAML configuration file corresponding to the model. Inside this YAML file, you will find a section where the hyperparameters like learning rate, momentum, weight decay, etc. are defined.

To modify them, simply change the values corresponding to the hyperparameters you are interested in. For instance, if you want to change the learning rate, find the line that begins with `lr:` and update the value.

Please remember to save the changes to the YAML file before you run your training command again. The new training run will then use these updated hyperparameters.

I hope that helps! Let me know if you have other questions.

**Comment by andresinsitu** [comment]
@glenn-jocher thanks for the answer glenn, I dont have any yaml model configuration, only the yaml that hast the dataset paths and classes. In order to modify the yaml do i have to fork the repo and make my "own" package or can you pass a configuration yaml to the train function without the need of modifying the package?

**Comment by glenn-jocher** [comment]
@andresinsitu hello,

The YAML file for your model's configuration is not typically meant to be modified for hyperparameters. Instead, you should change the hyperparameters in your training script where you call the train function.

To adjust the hyperparameters, you don't necessarily need to fork the repo or create your own package. You can modify these settings directly in your training command or script.

Look for the part of your script where the training function is called, you should see various hyperparameters being set there such as learning rate, batch size, momentum, etc. These values can be modified directly in your script.

Please remember to save any changes before re-running your training script. These adjustments should then be applied in your subsequent training runs.

I hope that helps! Let me know if you have other questions.

**Comment by karimkohel** [comment]
@jagprieto Your solution works for me so I'll share my case so maybe it can help.

on a Windows 10 Machine:
GTX 1660 super 6GB
NVIDIA-SMI: 537.13
CUDA version: 12.2
torch: 2.0.1+cu117
ultralytics: 8.0.171

it works with Automatic Mixed Precision disabled and a batch size of 2, didn't test further because I was content with the outcome.

**Comment by glenn-jocher** [comment]
@karimkohel Hi there, thank you for sharing your solution! 

It's great to hear that disabling Automatic Mixed Precision (AMP) and adjusting the batch size to 2 helped resolve your issue on your Windows 10 machine with a GTX 1660 Super GPU. 

It is always helpful to understand the hardware and software setup that works. This can serve as a reference for others in the community facing similar issues. 

Feel free to reach out if you encounter any other issues or have any further insights to share with the community. We appreciate your input!

Best,
Glenn Jocher

**Comment by enricob95** [comment]
Hi there, I went through the whole comment section but still haven't found a solution that works for me.

This is the hardware I am currently using: (NVIDIA GeForce GTX 1650 Ti, 4096MiB), and when training YOLOv8.0.173 model for image detection the mAP is always = 0.

According to what previously reported by @karimkohel I tried to:
-change the batch size = 2 
-turn the amp = False

Box_loss and other metrics are not zero, but mAP = 0 even after many epochs. Everything works fine when using the CPU instead.

Thanks

**Comment by glenn-jocher** [comment]
@enricob95 hello, 

Thank you for reaching out and sharing the details of the problem you're encountering. 

In your case, getting mAP=0 even when other metrics like box_loss are not zero does seem peculiar, especially considering that you achieve proper results while using CPU.

A couple of things you might want to look into: 

First, ensure that your GPU drivers and CUDA version are up to date. Differences in versions can sometimes cause conflicts leading to unexpected behaviour.

Next, you may want to verify your label data. Ensure all your bounding boxes have correct labels and coordinates. Remember, the mAP metric is strongly influenced by the quality of your annotations. 

Finally, try varying the learning rate. When transitioning from CPU to GPU, sometimes tweaking the learning rate can make a big difference because of the interplay between batch size and learning rate.

Please try these suggestions and let us know how it goes. Good luck with your training!

**Comment by enricob95** [comment]
Thank for your quick reply @glenn-jocher 

I would exclude the first two options as I have just updated the CUDA toolkit... Also I double checked the labels and they are ok, and predictions are discrete by training with the cpu even with 50 epochs... 
I will try to change the lr, thanks

**Comment by glenn-jocher** [comment]
@enricob95 Hi, thank you for getting back to us and confirming the steps you have already taken. 

With your CUDA toolkit updated and your labels verified, you've taken essential steps in troubleshooting this issue. 

Regarding the learning rate, it plays a critical role in model training. Therefore, adjusting it might help in dealing with the mAP being 0 when using GPU. 

Slight variations in learning rates can impact network stability. Very large learning rates may cause the model to converge too quickly or not at all, while very small learning rates may cause the model to converge too slowly or get stuck at high loss values. 

Choosing a proper learning rate may involve a bit of experimentation. Therefore, you might want to try different values and see how it affects the mAP.

Thank you for your patience and perseverance in resolving this issue!

**Comment by mohamedaliELfeky** [comment]
I encountered a similar error and resolved it by modifying the 'imgsz' parameter from 1280 to 640. The adjustment successfully addressed the issue. If anyone else faces a similar challenge, consider trying this solution.

**Comment by glenn-jocher** [comment]
@mohamedaliELfeky thank you for sharing your experience. Adjusting the 'imgsz' parameter can indeed influence GPU memory usage and potentially resolve training issues related to resource constraints. It's good to know this solution worked for you and might benefit others facing similar challenges. 👍

**Comment by mpj1234** [comment]
My equipment is also 1650, so I can train after I turn off amp.

**Comment by wenhongwu** [comment]
GTX1660TI
Modify line 115 in validator from self.args.half = self.device.type != 'cpu' to self.args.half=False.
Modify line in yolo/detect/val.py from batch['img'] = (batch['img'].half() if self.args.half else batch['img'].float()) / 255 to batch["img"] = (batch["img"].float()) / 255.

**Comment by glenn-jocher** [comment]
@wenhongwu thank you for sharing your solution! It looks like you've pinpointed a workaround for issues related to training on a GTX 1660 Ti by explicitly disabling AMP (Automatic Mixed Precision) in the code. ☺️

For those encountering similar issues, here's a concise version based on the suggestions:

```python
# Disable AMP
self.args.half = False

# Ensure images are processed as float32
batch["img"] = batch["img"].float() / 255
```

Remember, changes to the source can affect future updates, so keep track of any modifications you make. Hopefully, this helps anyone facing similar GPU issues! 🚀

**Comment by ankbhatia19** [comment]
> Hi there, I went through the whole comment section but still haven't found a solution that works for me.
> 
> This is the hardware I am currently using: (NVIDIA GeForce GTX 1650 Ti, 4096MiB), and when training YOLOv8.0.173 model for image detection the mAP is always = 0.
> 
> According to what previously reported by @karimkohel I tried to: -change the batch size = 2 -turn the amp = False
> 
> Box_loss and other metrics are not zero, but mAP = 0 even after many epochs. Everything works fine when using the CPU instead.
> 
> Thanks

I also have been running into the same problem. Although setting `amp=False` started showing loss data, all other metrics (R,  etc.) are zero. Tried using an `imgsz=640` as mentioned as well. Like others mentioned, works fine on CPU. Bit of an odd one isn't it?

![results](https://github.com/ultralytics/ultralytics/assets/25870725/4cff2b14-23fc-4118-87e1-0ef1aeb0dfb1)

__Nvidia Info__
- GTX 1660ti
- Driver Version: 550.78 (most recent as of time of post)
- CUDA: 12.4

__Host Info__
- OS: Arch
- Kernel: 6.8.7

**Comment by Cat2eacher** [comment]
Hello, I had the same problem, 
I use default config, But all loss is nan， and all metrics(P,R,map) is 0.
I change amp=False, batch=2, but it didn't work.
你好，我有同样的问题，
我使用默认配置，但所有的损失是 nan，
和所有的指标(P，R，map)是0。
我改变了 amp = False，批量 = 2，但也没用。

**Comment by pderrenger** [comment]
Hello, it seems like you're encountering persistent issues with NaN losses and zero metrics despite trying the suggested changes. Please ensure you're using the latest version of the Ultralytics package, as updates often include important bug fixes. If the problem persists, consider checking your dataset for any anomalies or inconsistencies that might be causing these issues. Additionally, you might want to experiment with different learning rates or other hyperparameters. If you continue to face difficulties, please provide more details about your setup and configuration.

**Comment by glenn-jocher** [comment]
Please ensure your CUDA and PyTorch versions are compatible with your GPU. Updating your drivers and checking your dataset for any issues might also help. If the problem persists, consider opening a new issue with detailed logs and environment information.

**Comment by glenn-jocher** [comment]
Please ensure your CUDA and PyTorch versions are compatible with your RTX 3060. Updating your GPU drivers might also help. If the issue persists, check the Ultralytics documentation for further guidance.
