### ISSUE TITLE
Which model would have the best precision yolov8x or yolov8x6 considering that I'm limited to an image size of 928?

### ISSUE THREAD

**Issue by hjk789** [ultralytics/ultralytics#1155]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Reading the docs, I saw that the yolov8x model is trained at an image size of 640, while the yolov8x6 is trained at 1280. 

I'm currently using yolov8x with an image size of 928, because 640 is too small for my use case, but I think that's affecting the precision. 

I thought of using the yolov8x6 model as it's trained at bigger images, but my system can't handle images at 1280 size and I'm limited to 928. 

What I ask is: will using the yolov8x6 model at 928 have a higher precision than yolov8x at 928?

**Comment by glenn-jocher** [comment]
@hjk789 It's hard to say definitively without trying it out, but in general, a model trained on larger images may have better performance on larger test images. However, this may not necessarily translate to better performance on smaller images.

In your case, if your system can't handle images at 1280 size and you are limited to 928, then using the yolov8x6 model at 928 may be the best option. Note that P6 models like YOLOv8x6 are best for detecting large objects. The additional P6 output is stride 64, vs stride 32 for P5 models like YOLOv8x. 

In this case, you can try experimenting with different image sizes for the yolov8x model and see if you can find an optimal image size that balances performance and resource constraints.

**Comment by nikky4D** [comment]
@glenn-jocher  is there a reference for which segmentation or detection models are best for small/large objects?

**Comment by arunsahu159** [comment]
Why do YOLOv8's different variants perform differently on the same dataset? Basically, why does the model's performance increase as the size of the model increases from nano(n) to extralarge (X)?

**Comment by glenn-jocher** [comment]
@arunsahu159 thanks for reaching out!

It is indeed intriguing how your observation contrasts with the common belief that larger models yield better performance. This is typically true due to their higher capacity to learn more complex features.

However, the performance of a model also heavily depends on the specifics of the dataset, like the nature of the images, the variety and scale of objects to be detected, among other factors. It's possible that for your particular Pictor v3 construction dataset, the smaller models are sufficient and more effective.

Smaller models being more efficient could boil down to a few reasons:

1. Characteristic of Dataset: The key features of your classes could be well captured by smaller models indicating a lower complexity of features.

2. Overfitting: Larger models sometimes tend to overfit on smaller datasets due to their large capacity.

3. Noise Sensitivity: Smaller models are sometimes less sensitive to noise and can build a more robust understanding of the real defining features of the classes.

4. Size of Objects: Smaller models could perform better on smaller objects as they maintain more detail from the input image.

Therefore, while larger models have more potential and usually do better in 'in-the-wild' scenarios and across various datasets, it isn't uncommon for smaller models to outperform on specific datasets.

Remember, model selection is situational and oftentimes requires testing different sizes and architectures to see which performs best given your unique circumstances.

I hope this helps clarify it! Do let me know if you have any more questions.

**Comment by arunsahu159** [comment]
@glenn-jocher Thank you so much for the valuable insight.

**Comment by glenn-jocher** [comment]
@arunsahu159, you're most welcome! I'm very glad that you found the information useful. Remember, the beauty of these models lies in their adaptability, so continue experimenting as you refine your models for your specific needs. Don't hesitate to reach out if you have other questions or interesting observations as you further your work with YOLOv8. Happy coding!

**Comment by christospelekis** [comment]
> @arunsahu159 yes, we have some guidelines about what types of models tend to work best with different object sizes:
> 
> * For small objects, lower-stride models typically fare better. That's because these models generally maintain more detail from the input image, which can be essential for detecting and correctly classifying small objects. Our YOLOv8s, YOLOv8m, or YOLOv8l models would be great for small objects detection.
> * For large objects, higher-stride models often work well. These models effectively sum up larger areas of the image, which can help them detect and classify large objects. In this case, the YOLOv8x and YOLOv8x6 models could be a better option.
> * For a mixed-size object detection or segmentation, a model with a mix of strides can often hit the sweet spot. This includes models like YOLOv8l6 or YOLOv8x6, which have additional P6 output with stride 64.
> 
> Please note that these are just general guidelines, and the exact performance can vary greatly depending on your specific dataset and task. I would highly recommend you try out a few different models with your own data to see which one provides the best results.
> 
> Let me know if you have any other questions!

Hello,

I am working with images of resolution 3840x2160, where the objects intended for detection are quite small, approximately 15-50 pixels in size. I have compiled a robust dataset and am planning to initiate new training at either 1280x720 or 1920x1080 resolution.

I would like some advice on which base model would be most effective for training in this scenario. Considering the small size of the objects, should I opt for YOLOv8s, YOLOv8m, or YOLOv8l, which are known for better detection of small objects? Or, given the very high resolution of the images, would YOLOv8x6 be a more suitable choice?

Additionally, I am seeking guidance on the optimal ratio of camera resolution to image size for experiments involving small objects like those described above.

Thank you for your insights.
