### ISSUE TITLE
cant get bounding box cords while using sahi only without

### ISSUE THREAD

**Issue by mohammdkaraca** [ultralytics/ultralytics#11649]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hi, im really new to this so im sorry if this is a dumb question. I am trying to print the cords of the bounding boxes of each object detected but it wont work with sahi im getting this eror"'PredictionResult' object is not subscriptable" I can print out the cords fine without it but it wont work while using it again im sorry if its a dumb question thanks in advanced.(I added the code in a txt file)
[github_question.txt](https://github.com/ultralytics/ultralytics/files/15212965/github_question.txt)

**Comment by glenn-jocher** [comment]
Hello! No question is a dumb question here, we're all learning! 😊 The error you're seeing, "'PredictionResult' object is not subscriptable," usually means that you are trying to access the results in a way that the object type does not support.

When using YOLOv8 with SAHI, make sure you are accessing the properties of the `PredictionResult` correctly. For instance, if you are trying to access the bounding box coordinates, you should utilize the methods provided by the `PredictionResult` object to pull these details, rather than directly indexing the object like a list or dictionary.

Here's a generic example of how you might retrieve bbox coordinates from a YOLOv8 prediction result:

```python
# Assuming 'results' is your PredictionResult object
for detection in results.detections:
    print("Bounding Box:", detection.bbox)
    print("Confidence:", detection.confidence)
    print("Class ID:", detection.class_id)
```

Make sure to replace `results.detections` with the actual attribute or method your 'results' object provides for accessing detections. Each detection typically has attributes like `bbox`, `confidence`, and `class_id`.

If you need more specific help, please provide the snippet of your code where you handle the result processing, and we can give more targeted advice!
