### ISSUE TITLE
webcam window is not opening

### ISSUE THREAD

**Issue by nitish9413** [ultralytics/ultralytics#1165]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

when running CLI detection webcam pop-up is not opening but it is accessing the camera and terminal showing detected objects
I tried uninstalling and reinstalling the package but the issue was not resolved

### Environment

- OS - windows 11
- Python - 3.9.12

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Have you passed `show=True`?

**Comment by glenn-jocher** [comment]
@AyushExel do you think we should treat webcam 0 source as special and automatically set show=True if it's not in overrides?

**Comment by AyushExel** [comment]
@glenn-jocher Yeah I guess at makes sense to use different defaults for CLI and python. CLI mode already uses stream mode by default as users can't access results and it'll never run out of memory on video inference. We can follow the same approach for show=True

**Comment by glenn-jocher** [comment]
@AyushExel yeah that's true. CLI is most useful for quickstart/experimenting and starting trainings. Users probably expect show=True by default here. Should we default show=True for streaming sources or for all sources?

**Comment by glenn-jocher** [comment]
@AyushExel I updated show wait times by the way, so now the images linger for a bit. Maybe we could extend show to accept a time in seconds to show for, i.e. show=1.0, since we've already seen users complain that the show times are too short.

**Comment by nitish9413** [comment]
working now,
earlier it was working without passing show=True

**Comment by nitish9413** [comment]
> I have been trying it as well but does not seem to be working for me. I am passing results = model(source= "0", show=True) but the webcam window does not seem to be popping up.
> 
> > working now, earlier it was working without passing show=True

try source=0

**Comment by abhisheksharmads** [comment]
> > I have been trying it as well but does not seem to be working for me. I am passing results = model(source= "0", show=True) but the webcam window does not seem to be popping up.
> > > working now, earlier it was working without passing show=True
> 
> try source=0 not "0"

I tried that as well.  Does not seem to be resolving the issue. Could be the python version? I tried on 3.9.7 and 3.10.

**Comment by komiam** [comment]
Same issue for me when I try to run it inside the docker container. The terminal shows the detected objects but I have no window. 
If I run it outside the container (on ubuntu), everything is good.
Any idea?

**Comment by pderrenger** [comment]
@komiam it seems like there might be an issue related to running the webcam inside a docker container. This could be due to the way Docker handles graphical interfaces. You may need to ensure that your docker container has access to the host machine's display and that the necessary drivers are installed.

You could try running the docker container with the `--device` flag to give the container direct access to the host machine's devices. Additionally, make sure that you have the appropriate dependencies installed within the container to support the display, such as X11 or Wayland.

Please ensure that your Docker image includes the necessary dependencies and configurations to support the display and graphical interfaces.

Let me know if this helps or if you have further questions!
