### ISSUE TITLE
unable to convert yolov8n.pt into tflite int8 format

### ISSUE THREAD

**Issue by manishp54** [ultralytics/ultralytics#11722]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i am  converting YOLOv8n.pt model into tflite int8 format and it showing following error:
`RuntimeError: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 4 is not equal to len(dims) = 3`

here I am giving imgsz as same as in .pt model but still facing the issue

**Comment by glenn-jocher** [comment]
Hello! It looks like you're encountering a dimension mismatch issue during the conversion process to TensorFlow Lite (TFLite) INT8 format. This can sometimes occur due to the specific handling of tensors during conversion.

To resolve this, you might need to adjust the sequence in which dimensions are permuted or handled during the conversion process. Here's a general example of how you might adjust the conversion code, ensuring dimensions align correctly:

```python
import torch
from ultralytics import YOLO

# Load the PyTorch model
model = YOLO('yolov8n.pt')

# Export to ONNX first as an intermediate step
model.export('onnx', imgsz=640)

# Convert ONNX to TensorFlow Lite as needed here (this part may require additional tools like onnx-tf or onnx2keras)
```

Make sure that the image size (`imgsz`) and other parameters are consistent throughout the conversion steps. If the issue persists, re-checking the conversion pipeline step by step to match the tensor dimensions might help. If you need more specific guidance, feel free to share the portion of your conversion script where you prepare the model inputs or handle the tensors.

**Comment by glenn-jocher** [comment]
Hello! It looks like you're encountering a dimension issue during your conversion to TensorFlow Lite INT8 format. This could be due to how dimensions are handled or permuted within your conversion process.

A helpful step might be to ensure that your dimension transformations align properly as you move from PyTorch to the TFLite model. Sometimes, converting to ONNX as an intermediate format can streamline the process, ensuring better compatibility when shifting to TFLite.

Here’s a quick example of how you might start this with an export to ONNX:
```python
from ultralytics import YOLO

# Load the model
model = YOLO('yolov8n.pt')

# Export to ONNX
model.export('onnx', imgsz=640)
```
Continue the conversion from ONNX to TFLite, ensuring that dimension handling is correct at each step. If you have more specific code snippets or errors during this process, feel free to share! 😊

**Comment by x2031** [comment]
> > ### 询问后搜索
> > 
> > * [x] 我搜索了 YOLOv8 [问题](https://github.com/ultralytics/ultralytics/issues)和[讨论](https://github.com/ultralytics/ultralytics/discussions)，没有发现类似的问题。
> > 
> > ### 问题
> > 我正在将 YOLOv8n.pt 模型转换为 Tflite int8 格式，它显示以下错误：`RuntimeError: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 4 is not equal to len(dims) = 3`
> > 在这里，我给出的imgsz与.pt模型相同，但仍然面临问题
> > ### 附加
> > _没有回应_
> 
> 你设法解决了吗？如果是这样，你能分享你的解决方案吗？我也在尝试量化模型

I'm getting the same error.

**Comment by glenn-jocher** [comment]
@x2031 hello! It seems like you're encountering a dimension mismatch during the conversion process. This error typically occurs when the tensor operations in the model are not compatible with the expected input/output format for TFLite.

A potential solution is to ensure that all tensor transformations, especially `permute` operations, are correctly aligned with TFLite's requirements. Here's a quick snippet on how you might adjust the tensor dimensions before exporting:

```python
# Assuming 'model' is your loaded YOLOv8 model
x = torch.randn(1, 3, 640, 640)  # Example input tensor
x = x.permute(0, 2, 3, 1)  # Adjust dimensions to match TFLite's expected input [batch, height, width, channels]
```

Make sure to adjust the dimensions as needed based on your specific model architecture. If you find a solution that works, sharing it would be greatly appreciated! 😊

**Comment by petewarden** [comment]
I'm hitting this too, and here's a minimal reproducible example of the code that triggers it in my case:

```python
from ultralytics import YOLO

model = YOLO("yolov8n-cls.pt")
model.export(format='tflite', int8=True)
```

This gives the following error message in the logs:

```python
[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py](https://localhost:8080/#) in export_saved_model(self, prefix)
    864                     if i >= 100:  # maximum number of calibration images
    865                         break
--> 866                     im = batch["img"].permute(1, 2, 0)[None]  # list to nparray, CHW to BHWC
    867                     images.append(im)
    868                 f.mkdir()

RuntimeError: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 4 is not equal to len(dims) = 3
```

This is running in Google's Colab notebook environment, and you can access the full script at [https://colab.research.google.com/gist/petewarden/17ca08f293b5b450ae21a1e05d41beed/ultralytics-tfl-export-bug.ipynb]( https://colab.research.google.com/gist/petewarden/17ca08f293b5b450ae21a1e05d41beed/ultralytics-tfl-export-bug.ipynb).

Any help much appreciated! This only started happening in the last three weeks or so.

**Comment by x2031** [comment]
> 我也遇到了这个问题，这是我的情况下触发它的代码的最小可重现示例：
> 
> ```python
> from ultralytics import YOLO
> 
> model = YOLO("yolov8n-cls.pt")
> model.export(format='tflite', int8=True)
> ```
> 
> 这会在日志中显示以下错误消息：
> 
> ```python
> [/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py](https://localhost:8080/#) in export_saved_model(self, prefix)
>     864                     if i >= 100:  # maximum number of calibration images
>     865                         break
> --> 866                     im = batch["img"].permute(1, 2, 0)[None]  # list to nparray, CHW to BHWC
>     867                     images.append(im)
>     868                 f.mkdir()
> 
> RuntimeError: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 4 is not equal to len(dims) = 3
> ```
> 
> 这是在 Google 的 Colab 笔记本环境中运行的，您可以在 https://colab.research.google.com/gist/petewarden/17ca08f293b5b450ae21a1e05d41beed/ultralytics-tfl-export-bug.ipynb 访问完整的脚本。
> 
> 任何帮助非常感谢！这是在过去三周左右才开始发生的。

Yes I rolled back to 8.1.47 and no longer get the error

**Comment by glenn-jocher** [comment]
Hello! Thanks for sharing your experience and the workaround by rolling back to version 8.1.47. It's great to hear that this resolved the error for you! 🎉

For anyone else encountering this issue, you might consider using the same version as a temporary solution. Meanwhile, we'll look into this issue to ensure better compatibility in future releases. Thanks again for your input!

**Comment by petewarden** [comment]
Thanks! I can confirm that the suggested `%pip install ultralytics==8.1.47` workaround does solve the issue for me.

**Comment by glenn-jocher** [comment]
@petewarden great to hear that the workaround resolved the issue for you! 🎉 We appreciate your confirmation. If any other questions or issues arise, feel free to reach out. Happy coding!
