### ISSUE TITLE
I'm using YOLOV8 to detect a character by training custom model. The detected item is not able to retrieve its class name, a box appears instead. How do I make fix?

### ISSUE THREAD

**Issue by yaredoguta** [ultralytics/ultralytics#11751]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train, Val

### Bug

![8d35023a-7fb8-4d9c-a9ab-8812677343a6](https://github.com/ultralytics/ultralytics/assets/38752701/5e5bbd25-630c-44ff-bfd1-03a78ca40e8b)
![val_batch1_labels](https://github.com/ultralytics/ultralytics/assets/38752701/72078d41-5efd-4a33-8c43-5942b53bc6f3)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello!

It looks like there might be an issue with how the class labels are being handled during training or validation. To fix the issue where the class name does not appear correctly on detection and only a box is shown, please ensure the following points:

1. **Check the Labels:** The class labels in your dataset's YAML file should be correctly specified and match the labels provided during training.
2. **Validate the Path:** Make sure the path for the labels in your dataset YAML is correct and accessible during the training and validation processes.

Here's a quick snippet to check if the labels are loading correctly in Python (assuming you are using Python for viewing or post-processing):

```python
import yaml

# Load your dataset YAML
with open('path/to/your/dataset.yaml', 'r') as file:
    data_yaml = yaml.safe_load(file)

# Check the content
print(data_yaml['names'])  # This should print the list of your class names
```

Ensure that this list matches with the expected class names and is in the correct order as your dataset annotations.

If everything with the dataset and labels seems correct, please make sure that the latest version of Ultralytics YOLOv8 is used, as there might be updates or bug fixes that could resolve your issue.

Let me know if this helps or if you need more detailed guidance! 😊

**Comment by yaredoguta** [comment]
Thank you for your assistance Sir, the code you suggest displays the expected class, let me check the second suggestions 
 
![image](https://github.com/ultralytics/ultralytics/assets/38752701/e8b1da2a-b484-4d3b-8581-8c127a982c7d)

**Comment by glenn-jocher** [comment]
Great to hear the first part worked out for you! 👍 Please take your time to check the second suggestion and see if it resolves the issue completely. If you encounter any more bumps along the way or have further questions, feel free to reach out. Happy to help! 😊

**Comment by yaredoguta** [comment]
> Great to hear the first part worked out for you! 👍 Please take your time to check the second suggestion and see if it resolves the issue completely. If you encounter any more bumps along the way or have further questions, feel free to reach out. Happy to help! 😊
@glenn-jocher 

I examined the second proposal. The latest, or Ultralytics 8.2.11, is the Ultralytics YOLOv8 that is being used. I was unable to determine the cause of the problem.

**Comment by glenn-jocher** [comment]
Thanks for the update! Since you're using the latest version and the problem persists, it might be helpful to double-check the annotation format in your dataset and ensure it matches the expected input format for YOLOv8. Sometimes, even minor discrepancies in annotation coordinates or formats can cause such issues.

Additionally, if you could share a snippet of your configuration file or a few example annotations, I might be able to offer more specific advice. Also, considering running a diagnostic on a small subset of your data might pinpoint the issue more clearly. 🧐

Looking forward to helping you resolve this!

**Comment by yaredoguta** [comment]
Thank you! @glenn-jocher 

This is an example of input and output with a confusion matrix where the class label is hidden. 

[SampleDataAndAnotation.zip](https://github.com/ultralytics/ultralytics/files/15260445/SampleDataAndAnotation.zip)

Class
names: {0: 'ሀ', 1: 'ሁ', 2: 'ሂ', 3: 'ሃ', 4: 'ሄ', 5: 'ህ', 6: 'ሆ'}

![confusion_matrix_normalized](https://github.com/ultralytics/ultralytics/assets/38752701/319d83fa-4e83-4209-ad24-30c407ce39d1)
![F1_curve](https://github.com/ultralytics/ultralytics/assets/38752701/770b302f-9fdb-4054-a199-cab7eb939aed)
![confusion_matrix](https://github.com/ultralytics/ultralytics/assets/38752701/0dd26e33-08c8-438d-869e-2a0fc160532d)
![P_curve](https://github.com/ultralytics/ultralytics/assets/38752701/6eae0530-677a-4f70-9cab-06532d505d29)
![PR_curve](https://github.com/ultralytics/ultralytics/assets/38752701/d7c8a400-7bfe-4566-a8c4-a8eaf41de899)
![val_batch2_labels](https://github.com/ultralytics/ultralytics/assets/38752701/993c7703-4261-4ab8-aedc-8e92dcdcf5ad)

I saw the same difficulties as were noted in your earlier reply URL below. Could it be that the label name I supplied during annotation is not supported, causing the class label to be represented by a rectangle symbol? 

https://github.com/ultralytics/yolov5/issues/6851

**Comment by glenn-jocher** [comment]
Hey! Thanks for sharing the detailed information and visuals. 🌟

From your description and the linked issue, it seems like there might be a problem with rendering the class labels, possibly due to font support for the characters you're using. YOLO typically relies on common system fonts to display text, which might not include glyphs for all character sets.

A practical step would be to customize the font used in your visual output to one that supports your specific characters. Here’s a quick example of how you can specify a font in Python using PIL (Pillow), assuming you’re post-processing your visual outputs this way:

```python
from PIL import ImageFont, ImageDraw, Image

image = Image.open('path_to_image.jpg')
draw = ImageDraw.Draw(image)
font = ImageFont.truetype('path_to_custom_font.ttf', size=15)  # Ensure the font supports your characters

# Suppose this is where you want to draw text
text_position = (100, 50)
draw.text(text_position, 'Hello World', font=font, fill=(255,255,255))

image.show()
```

Make sure to replace `'path_to_custom_font.ttf'` with the path to a font file that supports your characters. This should help display the labels correctly. 👍

If issues persist, do let us know!

**Comment by natime1231** [comment]
Thank you, @glenn-jocher for the helpful reply. It works for displaying visuals for post-processing tasks. However, in the documentation, it mentions the YOLO Performance Metrics file saved in the directory **runs/detect/val**. 

Thus, how do I add a font like the above example so that the automatically saved performance metrics file will display the characters?

**Comment by glenn-jocher** [comment]
@natime1231 hi there! I'm glad to hear that the solution worked for your post-processing tasks! 😊 For embedding the font directly into the automatically saved performance metrics files, you'll need to modify the source code where the images are saved during detection or validation.

Here's a simple way to do it using Python. You'll have to locate the section in the YOLOv8 source code where images are annotated and saved. It likely involves drawing text on images using `PIL` or `cv2`. Here’s a snippet of how you might adjust it:

```python
from PIL import ImageFont, ImageDraw, Image

# Load your custom font
font = ImageFont.truetype('path_to_custom_font.ttf', size=15)

# When drawing text:
draw.text((x, y), 'Label Text', font=font, fill='white')
```

Just ensure you add this snippet wherever text is drawn on your performance metric outputs. If you're not comfortable adjusting the source, I suggest reaching out through a GitHub issue for further guidance or possibly a feature request!

Let me know if there's anything else you'd like to explore! 🌟
