### ISSUE TITLE
Why are width and height values in inferencing output switched?

### ISSUE THREAD

**Issue by haimat** [ultralytics/ultralytics#11778]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have trained my YOLOv8 model with the `imgsz` parameter set to `1920`.
All my images have a dimension of width=1920 x height=1200.

Now my inferencing output looks like this:

```
Ultralytics YOLOv8.2.11 🚀 Python-3.10.12 torch-2.1.1+cu121 CUDA:0 (NVIDIA GeForce RTX 2070 with Max-Q Design, 7974MiB)
Model summary (fused): 168 layers, 3006233 parameters, 0 gradients, 8.1 GFLOPs

image 1/15 /data/clients/test/images/muffen/tmp/20240506_132019_NotGood.jpg: 1216x1920 1 Fehler, 43.6ms
...
image 15/15 /data/clients/test/images/muffen/tmp/20240506_133350_NotGood.jpg: 1216x1920 1 Fehler, 19.9ms
Speed: 7.9ms preprocess, 21.6ms inference, 49.1ms postprocess per image at shape (1, 3, 1216, 1920)
```

For me that looks like width and height has been switched for inferencing - or is this just the output, which lists height before width? If so, why is that?

Additionally, would it make sense to use the `rect` training paramenter? What difference does it make exactly?

**Comment by glenn-jocher** [comment]
@haimat hello! The output you're seeing, where it appears that height and width are switched (listed as 1216x1920 instead of 1920x1216), is due to the format typically used in deep learning where dimensions are often described as height x width rather than the conventional width x height. This format is standard in many frameworks and tools that deal with image processing including PyTorch and Ultralytics YOLO.

Regarding your question about using the `rect` training parameter: using `rect` can be beneficial as it trains the model using rectangular images rather than square. This can lead to better memory utilization and potentially faster training times, especially if your input images are naturally rectangular (like yours). It adjusts the network to more effectively handle the aspect ratios of your input images during training, which can improve detection accuracy on similarly shaped test images.

Hope this clarifies your concerns! 😊

**Comment by haimat** [comment]
@glenn-jocher Thanks your response.

So in my case, if I would use the `rect` parameter, would that also mean
I should provide both width and height for the `imgsz` parameter?

**Comment by glenn-jocher** [comment]
Hello @haimat! Yes, using the `rect` parameter allows the model to train on non-square images, which can be beneficial for handling different aspect ratios more effectively. When using `rect`, it's a good idea to specify both width and height in the `imgsz` parameter to match your typical image dimensions, like so: `imgsz=1920,1200`. This setup helps the model to better adapt to the dimensions of your input images during training. 😊
