### ISSUE TITLE
Conversion from torch model to Onnx model causing variations in inferencing input parameters

### ISSUE THREAD

**Issue by liuy129** [ultralytics/ultralytics#11783]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

converted the torch model in .pt to .onnx file type, and it resulted into the following two issues:

1). additional input parameters are required to be specified in order to run predict (e.g. 'task' and 'imgsz').
2). the prediction mask returned using .onnx model file are resized and zero-padded to the dimension of 'imgsz'; however, this is not the case working with .pt model file. The prediction mask returned using .pt are resized only.

### Environment

Ultralytics YOLOv8.2.10 🚀 Python-3.8.8rc1 torch-1.13.1+cpu CPU (AMD EPYC 7F52 16-Core Processor)
Setup complete ✅ (2 CPUs, 64.0 GB RAM, 151.1/195.3 GB disk)

### Minimal Reproducible Example

from ultralytics import YOLO

# codes to run inference with .pth model file
model = YOLO(model_path)
results = model.predict(source=cropped_image)

# codes to run inference with .onnx file
model = YOLO(model_path, task = "segment")
results = model.predict(source=cropped_image, imgsz = 1024) # default 'imgsz' is 640 so have to updated to 1024 because my model expected a tensor shape of (1, 3, 1024, 1024)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello! It looks like you've encountered issues regarding input parameters and output resizing when converting from a PyTorch `.pt` model to an `.onnx` format. Here are some insights to help address these:

1. **Input Parameters (task and imgsz)**: When exporting to ONNX and using it, you might need to explicitly specify these parameters that are automatically handled in the PyTorch version. This difference often comes due to the static nature of ONNX which needs definite input sizes and tasks specified.

2. **Output Resizing and Padding**: ONNX models sometimes behave differently due to the static graph constraints. ONNX requires fixed dimensions (`imgsz`) for all operations within the model, which might lead to additional resizing and zero-padding not present in the dynamical PyTorch version.

To remedy resizing and padding issues, you can adjust the post-processing of the output in your application to align with how the `.pt` model handles these aspects. Here is sample code to adjust the output:

```python
# Assuming `results` is the output of the ONNX model
import numpy as np

def resize_masks(masks, original_shape):
    out = [cv2.resize(mask, (original_shape[1], original_shape[0]), interpolation=cv2.INTER_LINEAR) for mask in masks]
    return np.array(out)

original_shape = cropped_image.shape[:2]  # Assuming cropped_image shape is HxWxC
resized_masks = resize_masks(results.masks, original_shape)
```

Please refer to the Ultralytics documentation on [model export](https://docs.ultralytics.com/modes/export) for details on how configurations may affect ONNX outputs compared to PyTorch. If the issue persists, consider using our support channels where we can examine your case more closely. Let us know if this was helpful! 🚀
