### ISSUE TITLE
Get params and GFLOPs values on exported models (ONNX)

### ISSUE THREAD

**Issue by Sidla** [ultralytics/ultralytics#11841]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, my question is how can I get to know the parameters and GLOPs values from exported models ?

For example when I have basic model: 

```
import torch
from ultralytics import YOLO
model = YOLO('yolov8n.pt')
model.info()
```

I can get the metrics from _info()_ method: _**YOLOv8n summary: 225 layers, 3157200 parameters, 0 gradients, 8.9 GFLOPs**_

The thing is, I wanted to export model and set exporting parameter to "**_imgsz=320_**" thinking
it would speed up the model. So I did command `model.export(format='onnx', imgsz=320)` which exported model to onnx. 
This model is faster on validation for the same dataset as the original model, but with worse precision, the very thing I expected.

But then I wanted to get info from the model to see how hopefully the GFLOPs and parameters values changed to the way down. However I can't use method _info()_ on exported models, as I get error that its only possible on _.pt_ models. 

So then I tried scrolling through this wonderful forum and found I could save the _320x320 onnx model_ back to the _.pt_ format and then try the _info()_ method like this: 
```
model = YOLO('yolov8n.onnx')
torch.save(model, 'ONNX320model.pt')

model = YOLO('ONNX320model.pt')
model.info()
```

However, this doesn't work as I get this error: 
File "C:\Users\PC\anaconda3\envs\bc\lib\site-packages\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "C:\Users\PC\anaconda3\envs\bc\lib\site-packages\ultralytics\engine\model.py", line 151, in __init__
    self._load(model, task=task)
  File "C:\Users\PC\anaconda3\envs\bc\lib\site-packages\ultralytics\engine\model.py", line 240, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "C:\Users\PC\anaconda3\envs\bc\lib\site-packages\ultralytics\nn\tasks.py", line 808, in attempt_load_one_weight
    model = (ckpt.get("ema") or ckpt["model"]).to(device).float()  # FP32 model
AttributeError: 'str' object has no attribute 'to'

**So what is the correct way to get parameters and GFLOPs metric from model with imgsz=320? Hopefully they (should?) would be lower, than with the original model which uses 640x640?**

**Comment by glenn-jocher** [comment]
@Sidla hello! Great question about assessing the parameters and GFLOPs of exported ONNX models. 🚀

The error you encountered is because direct conversion from ONNX back to PyTorch format isn’t straightforward and usually can’t retain the metadata required for the `info()` method in YOLO models. For exported models, especially when you change dimensions like imgsz for optimization purposes, the process does not directly translate into observable metadata in the same way `.pt` models do within our PyTorch framework.

For analyzing ONNX models, you normally need to utilize ONNX-specific tools. You can use `onnxruntime` to execute the model and a library like `onnx` itself to manually calculate GFLOPs and parameters. Here’s a basic example of how you can load and inspect an ONNX model:

```python
import onnx
from onnx import checker, helper

# Load the ONNX model
model = onnx.load("yolov8n.onnx")

# Check the model’s validity
checker.check_model(model)

# Print details for inspection
print(onnx.helper.printable_graph(model.graph))
```

This script loads the ONNX model and outputs its computation graph. However, calculating GFLOPs and exact parameters directly from this representation might require more specific calculations, as ONNX does not have inherent support for these metrics like PyTorch.

For detailed analysis, specialized tools or custom scripts are typically needed. Calculating GFLOPs manually involves summing up operations in each layer, which can be extracted from the model graph, though this is often non-trivial without deep familiarity with model structures and operations.

Keep exploring, and if you need further help with specific calculations or tools, feel free to ask!

**Comment by Sidla** [comment]
Thank you for your fast reply @glenn-jocher.  

So my follow up question is, what is the easiest way to get the GFLOPs metric from model which is running/exported on imgsz 320x320?

So I could compare it with the default model which is on 640x640 and hopefully see the drop of GFLOPs?

**Comment by glenn-jocher** [comment]
Hello @Sidla!

To get the GFLOPs for a model exported at a specific image size (like 320x320), you'd typically use a tool or script that evaluates the model's computational complexity based on its ONNX or other exported formats.

Here's a basic strategy using Python and ONNX:

1. Export your model to the ONNX format with `imgsz=320`.
2. Load the ONNX model.
3. Use a tool or write a script to calculate GFLOPs. While ONNX doesn't support GFLOP calculation natively, you can use other tools like [Netron](https://netron.app/) to visually inspect the model, or extend a Python script to parse the ONNX graph to compute GFLOPs based on the operations defined.

For a Python script that calculates the operations manually, you would traverse the computation graph and tally the operations based on the type and dimensions of each node. This might get a bit technical and needs a deeper dive into model structures.

Hope this points you in the right direction! If you need more detailed code snippets or further help, just let me know! 🚀

**Comment by glenn-jocher** [comment]
@Sidla hi there!

Thanks for reaching out with your findings! When you export YOLOv8 models with a smaller `imgsz` (like 320x320), it indeed adjusts the input tensor size, which can affect the inference speed and possibly the GFLOPs due to fewer computations needed per forward pass 🚀. However, the total number of parameters in the model typically remains unchanged because these are set during the model architecture design – the model's depth, number of layers, and connections stay consistent regardless of the input size.

Changing `imgsz` primarily impacts how the model handles input and affects operational dynamics (like speed and computational load during inference) rather than altering the model's structural parameters. If you aim specifically to reduce GFLOPs significantly, model pruning or architecture adjustments might be necessary approaches.

Hope this clears things up! If you have any more questions, feel free to ask. Happy modeling!
