### ISSUE TITLE
Training cli - Missing confusion matrix image and validation images

### ISSUE THREAD

**Issue by ahazat** [ultralytics/ultralytics#1184]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Hello, 

Since **Ultralytics v8.0.42** when i trained the a custom model, by specifiying my own data dataset as `data.yaml`: 
```yml
train: v3/train
val: v3/val
nc: 2
names: ['door', 'window']
```

And my own configuration as `model.yaml`
```yml
nms: true
iou: 0.3
project: object_detection
epochs: 1000
patience: 50
```

And i trained the model using : 

```bash
yolo cfg=train/model.yaml task=detect mode=train model=yolov8n.pt data=train/data.yaml device=0
```

The training is finished correctly but i no more see the images related to confusion_matrix and validation batchs ? 

With epochs = 100

![image](https://user-images.githubusercontent.com/15121100/221548800-be9d1a47-f50d-486b-8ff3-31cfb5b2c772.png)
 
With epochs = 1000

![image](https://user-images.githubusercontent.com/15121100/221549280-0ca53525-acb0-4e44-8319-b5729b5f0b9a.png)

I think that when the training is stopped early with more epochs no performance images are generated but when with small epochs i had the performance image !

There is a bug some where ? 

Thank you for your help,

Best Regards,

### Environment

- Ultralytics YOLOv8.0.42 🚀 Python-3.10.6 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce GTX 1070, 8114MiB)
- Python: 3.10.6
- OS: Ubuntu 22.04.2 LTS

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ahazat looks nearly identical to me. Any differences may be simply due to different batch sizes. I'm going to attach a non-reproducible tag here since I'm not able to reproduce any significant differences. If you can provide a minimum reproducible example in a common environment with a common dataset, let us know, thanks!

<img width="1213" alt="Screenshot 2023-03-04 at 12 51 40" src="https://user-images.githubusercontent.com/26833433/222928251-36c9a351-1123-496a-8afb-9a697bb52039.png">
