### ISSUE TITLE
How to use track mode separately

### ISSUE THREAD

**Issue by Li-shuangyi** [ultralytics/ultralytics#11867]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, thank you for your excellent work! Recently I was working on a project to apply model.track in a video. In order to improve the speed of operation, I extracted video frames and tracked them in multiple processes. Obviously, a mistake here is that when I track the video across multiple processes, the continuity between frames is broken.For a single target, the ID is not unique.

![pic1](https://github.com/ultralytics/ultralytics/assets/138353208/43b83e51-66db-4704-a59d-0f372588693e)
![pic2](https://github.com/ultralytics/ultralytics/assets/138353208/08424009-06a2-47ef-bf0a-72874868f35b)
![pic3](https://github.com/ultralytics/ultralytics/assets/138353208/405841e6-bac2-471e-918c-2b9892b8c4fc)

In my opinion,Yolov8's detect mode can be used in multiple processes to process a continuous video, cause it only needs to detect each frame of the image and return the result.And for a video, the sequence between frames is clearly known.

Is it possible to use Yolov8's detect and track separately in some way so that I can handle image detection in multiple processes and track different images by frame time in one process? If I need to change the code to implement it, what parts of the code should I focus on?

**Comment by glenn-jocher** [comment]
Hi there! Thank you for reaching out and detailing the challenges you're facing.

To handle your requirement, you can indeed separate the detection and tracking processes. Here's a simple strategy:

1. **Multi-Process Detection**: Use multiple processes to detect objects in each frame (similar to what you're currently doing). Save these detection results, including bounding boxes and class IDs, to a shared storage that maintains the order of frames.

2. **Single-Process Tracking**: After detection, use a single process to read the stored detection results in sequence and apply tracking. This way, you maintain the continuity and uniqueness of object IDs across the frames.

For implementing this, focus on:

- **Data Storage**: Ensure detection results are stored with frame identifiers to maintain sequence.
- **Tracking Logic**: Modify the tracking logic to read from the stored results rather than performing detection on the fly.

This approach keeps detection and tracking decoupled but synchronized through stored results.

Here’s a brief pseudo-code to outline how you might structure this:

```python
# Multi-process detection
def detect(frame):
    # perform detection
    results = model.detect(frame)
    save_to_shared_storage(frame_id, results)

# Single-process tracking
def track():
    for frame_id in sorted(get_frame_ids()):
        detections = read_from_shared_storage(frame_id)
        track_results = update_tracker(detections)
        display_track_results(track_results)
```

I hope this helps! Keep us posted on your progress or if you encounter any issues.
