### ISSUE TITLE
Custom validation output issues

### ISSUE THREAD

**Issue by zyy-xy** [ultralytics/ultralytics#12148]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Excuse me! I encountered two issues while conducting data validation：

1. I validated using the official YOLOv8 model on a big dataset. According to the project requirements, I only need to identify two types of objects (such as 0-person and 59-bed). In order to improve efficiency, I want the network to only output the prediction results of these two categories (note that it is not simply blocking the prediction results of other categories, but rather directly not calculating other categories during the final operation, thereby reducing the computational complexity of the model). One attempt I made was to modify the yaml file to the following content, but this did not work. Is there any effective method?
    ```yaml
    names:
        0: person
        59: bed            # `59: bed` would result in code errors and `1: bed` did not work as well.
    ```
2. I want to visualize the predicted results of each image and save them, that is, draw the real and predicted boxes or masks on each image simultaneously as image files. How could I do it?

I would greatly appreciate it if you could reply to me and help me.

**Comment by glenn-jocher** [comment]
Hi there! Thanks for reaching out. Let's tackle your questions one by one:

1. **Filtering Object Categories for Efficiency**: To have the model only calculate the categories you're interested in, the model itself would need to be retrained with only the categories of interest (person, bed) in your dataset. This is because the current model architecture includes all trained categories by default. After retraining, it will naturally compute only for those categories.

2. **Visualizing and Saving Predictions**:
   For visualizing and saving the predicted results on images, you can utilize the `show()` and `save()` methods after running predictions:

   ```python
   from ultralytics import YOLO
   model = YOLO('yolov8n.pt')  # or your custom model path

   # Run prediction
   results = model.predict('path/to/your/image.jpg')

   # Visualize and save results
   results.show()
   results.save('path/where/to/save.jpg')
   ```

I hope this clarifies your queries! Let me know if there's anything else you need help with. 😊

**Comment by Petros626** [comment]
@zyy-xy never finished?
