### ISSUE TITLE
A generalized YOLOv8 model with DET, OBB, SEG and POSE tasks.

### ISSUE THREAD

**Issue by zhouzq-thu** [ultralytics/ultralytics#12174]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Currently, we can only use the YOLOv8 model to handle one of obb, seg and pose tasks.

#### Idea

Since one of the output layers of the YOLOv8 model has the output with shape as follows:
- det: `[bs, num_classes + 4 * reg_max, lw, lh]`
- obb: `[bs, num_classes + 4 * reg_max + 1, lw, lh]`
- seg: `[bs, num_classes + 4 * reg_max + num_masks, lw, lh]`
- pose: `[bs, num_classes + 4 * reg_max + 3 * num_kpts, lw, lh]`

We can define a generalized YOLOv8 model with output as follows:
- gen: `[bs, num_classes + 4 * reg_max + is_obb + num_masks + 3 * num_kpts, lw, lh]`

### Use case

```python
class GeneralizedHead(nn.Module):
    """YOLOv8 Generalized head."""
    def __init__(self, nc=80, is_obb=False, nm=0, npr=256, kpt_shape=None, ch=()):
        ...
```

With the generalized YOLOv8 model:
- If we want the obb+seg model, then set `is_obb = True, nm = 32`. (#7918)
- If we want the seg+pose model, then set `nm = 32, kpt_shape = (17, 3)`. (#2405)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@zhouzq-thu hello there! Thank you for your detailed suggestion regarding a generalized YOLOv8 model that can handle multiple tasks (DET, OBB, SEG, and POSE) in one framework. This is indeed a very interesting idea and could significantly enhance YOLOv8's versatility.

Your proposed approach to integrating a generalized head that can dynamically configure to handle combinations of different tasks is compelling. It would allow the user customization based on specific requirements, and using flags like `is_obb`, `nm`, and `kpt_shape` as parameters offers a straightforward method to toggle functionalities.

I encourage you to proceed with submitting a PR since you are already considering it. The community, including the development team, would greatly benefit from this capability and can provide feedback directly on your implementation. Looking forward to seeing your contribution! 😊🚀

Best of luck!
