### ISSUE TITLE
Issue with deploying YOLOv8 object detection model on mobile using TFLite

### ISSUE THREAD

**Issue by kostum123** [ultralytics/ultralytics#1221]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I am facing an issue while attempting to deploy my YOLOv8-based object detection model for mobile devices. This model was developed as part of my university project, which requires me to present it for use on mobile platforms. During my research, I selected YOLOv8 due to its TFLite output support and user-friendly nature. After successfully training the model, I discovered that the TFLite version of my model is not functional in the TensorFlow Lite object detection example application. I would appreciate any guidance or suggestions on how to integrate the YOLOv8-generated model with the mobile application. StartGraph failed: $Expected a model with 4 output tensors, found 1.; Initialize was not ok.

**Comment by glenn-jocher** [comment]
@kostum123 you can train and deploy to the Ultralytics App using TFLite now at https://hub.ultralytics.com/, and we are working on adding a framework for general Android deployments in the future.

@sergiossm

**Comment by noorraghib12** [comment]
Hi, I'm still looking for an android sdk example usecase for yolov8 model deployment! Any help would be much appreciated!

**Comment by sergiossm** [comment]
Hey @noorraghib12 we're now offering a license solution for our mobile SDK 🚀. If you're interested, please fill in this form and we'll get to you shortly https://ultralytics.com/license

**Comment by noorraghib12** [comment]
could you explain further on the licensing solution ? Due to not being knowledgeable enough, I dont quite understand how the license works. I could deploy my own version to the sdk if I could just get a usecase on how to deploy it to the android.

**Comment by glenn-jocher** [comment]
Hello @noorraghib12, thank you for your interest in our mobile SDK licensing solution. To put it simply, our licensing solution provides you with access to a mobile SDK built specifically for deploying YOLOv8 object detection models onto Android devices. This SDK package includes a pre-trained YOLOv8 model, libraries and plugins necessary for deployment, and a streamlined deployment process to integrate your own custom models.

In order to deploy your own custom YOLOv8 models onto the SDK, you can go through the following steps:

1. Train your YOLOv8 model on your desired dataset
2. Convert the model into a TensorFlow Lite format (.tflite)
3. Package the .tflite file and include it in the SDK package
4. Use the SDK APIs to invoke the detection functions to run your custom YOLOv8 model on device

We hope this helps answer your question! If you have any further concerns or questions, please do not hesitate to ask.

**Comment by noorraghib12** [comment]
@glenn-jocher is the SDK licensing solution open source ? Or do I need to pay for it ? In the case I do, how much would a one time payment cost ?

**Comment by glenn-jocher** [comment]
Hi @noorraghib12, thank you for your question! The Ultralytics mobile SDK is not open source and does require licensing. The licensing fees for the mobile SDK depend on a few factors such as the intended use case, the number of devices the SDK will be deployed on, and the required level of support. Our team will work with you to determine the most appropriate licensing fee for your specific needs. If you're interested, you can fill out the form on our website and one of our team members will be in touch with you to discuss licensing options in more detail.

**Comment by connli** [comment]
> @kostum123 you can train and deploy to the Ultralytics App using TFLite now at https://hub.ultralytics.com/, and we are working on adding a framework for general Android deployments in the future.
> 
> @sergiossm

when ……^_^
