### ISSUE TITLE
Export to ONNX with NMS?

### ISSUE THREAD

**Issue by guillermovc** [ultralytics/ultralytics#1230]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, i would like to know if there is any chance to export my motel to onnx, adding NMS to the model itself, so i wont need to install torch, which is of my interest since im using a light Docker image for inference.

I've tried to export my model with nms=True parameter, but when i do inference the output shape is (1,84,8400)

**Comment by AyushExel** [comment]
See this ONNX opencv example that uses ONNX model without torch NMS https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-OpenCV-ONNX-Python
I think this will satisfy your use case

**Comment by UltralyticsAssistant** [comment]
The associated pull request [#18484](https://github.com/ultralytics/ultralytics/pull/18484) has been merged, and it includes a potential fix that may resolve this issue! 🎉  

### Relevant Key Changes from the PR:
This update introduces extended export functionalities and post-processing improvements for object detection models, addressing several limitations in the workflow. Notable changes include:
- **Non-Maximum Suppression (NMS) Integration**: Exported models (TorchScript, ONNX, OpenVINO, TensorRT, TensorFlow) now include embedded NMS, providing seamless post-processing capabilities.
- **Enhanced Post-Processing Logic**: Predictions for various tasks (detection, segmentation, pose, and OBB) have been refined, including additional attribute support, like `keypoints`, for improved handling of prediction results.
- **Flexibility in Export Configurations**: Users can now toggle NMS during the export process, enabling easier deployment customization.
- **Better Metadata Handling**: Updates for improved export compatibility across formats.
- 🆙 Version upgraded to `8.3.67` for tracking this new functionality.

These changes aim to streamline the export process while improving runtime efficiency and usability for deployment scenarios.  

### Contributors ❤️
This valuable update was made possible due to contributions from [Y-T-G](https://github.com/Y-T-G), [lifafang](https://github.com/lifafang), [boorad](https://github.com/boorad), [glenn-jocher](https://github.com/glenn-jocher), [Laughing-q](https://github.com/Laughing-q), and [inisis](https://github.com/inisis). A big thank you to everyone involved! 🙌  

### How to Test the Changes:
To verify if this resolves your issue:
- Install the latest changes directly from the `main` branch:
  ```bash
  pip install git+https://github.com/ultralytics/ultralytics.git@main
  ```
- Or you can wait for the next official release on PyPI if preferred.

Let us know if this resolves the issue or if you encounter any remaining problems. Your feedback is invaluable in ensuring the robustness of these updates.  

Thanks again for bringing up this issue! 🙏 If anything persists or additional adjustments are needed, feel free to share more details.
