### ISSUE TITLE
Implementing a simple ReID process

### ISSUE THREAD

**Issue by yusufkoca0** [ultralytics/ultralytics#12626]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, for my current project I am trying to make a drone track the objects in its view and follow a specified object physically. To accomplish this I am using the id of the tracked object and it works wonders in most cases. I am currently stuck on a problem where if an occlusion happens for 5-10s or occlusion happens on a curved road and car changes position the tracked id changes. I know yolov8 does not have a built in re-id process yet. So I want to implement a simple re-id myself.

One of the possible solutions I came up with was storing the object and fixing it when its id changes. But I face a huge issue that when its id changes the after correction model still gives the unmodified id. For example I follow id = 1 and id becomes id = 2, I correct this back to id = 1 but I assume since I am not able to feed this correction to the system it gives id = 2 again and I try to correct it again. This process being done in a few frame does not cause an issue but I am trying to work it in real time and this additional time complexity puts me behind.

So my main question is how can I implement this reid process so that it makes the correction in the model so when it is corrected it gives the correct output? Can I accomplish this without going into the source code? 

Thanks in advance.

**Comment by glenn-jocher** [comment]
Hi there,

It sounds like a challenging but interesting problem! Implementing re-identification (ReID) can indeed help maintain object tracking continuity even through occlusions or other visual interruptions.

For a simple ReID system without modifying the YOLOv8 source code, consider maintaining a history of object features (like bounding boxes, appearance features extracted from the detection region, etc.). Here’s a brief idea:

1. **Extract Features**: Every time an object is detected, extract features that could be used to re-identify it later. This could be simple bounding box coordinates and size, or more complex appearance features using a separate feature extraction model.

2. **Comparison Function**: Implement a function to compare the feature vector of a newly detected object with those of previously tracked objects. The function could be based on simple Euclidean distance for numerical features, or more complex similarity measures for comprehensive feature vectors.

3. **Update Logic**: When an object is occluded and reappears, use this function to find the most similar previously tracked object and assign its ID to the new detection.

Here's a rough code example to illustrate the concept:

```python
def extract_features(detection):
    # Placeholder for feature extraction logic
    return detection['bbox'], detection['appearance']

def match_object(new_detection, tracked_objects):
    new_features = extract_features(new_detection)
    best_match = None
    min_distance = float('inf')
    for obj in tracked_objects:
        dist = np.linalg.norm(new_features - tracked_objects[obj]['features'])
        if dist < min_distance:
            min_distance = dist
            best_match = obj
    return best_match

# Usage in tracking loop
new_detection = detect_objects(frame)
object_id = match_object(new_detection, tracked_objects)
if object_id:
    update_tracker(object_id, new_detection)
else:
    add_new_object(new_detection)
```

This approach manages IDs at the application level and doesn't require altering the underlying model or its training procedure. However, integrating more advanced machine learning models for feature comparison could offer better results but might involve more complexity and computational overhead.

Hope this helps get you started on your ReID system, and I'm eager to see how your project turns out!

**Comment by yusufkoca0** [comment]
Hi Glenn,

Sorry about the late response. I've been busy with other projects and school mostly. Thank you for the quick response. I am still confused about how I can update the tracker. I am using this to obtain results from the model:

```
result = model.track(frame, persist=True, tracker="custom.yaml")[0]
detections = sv.Detections.from_ultralytics(result)
detections.tracker_id = result.boxes.id.cpu().numpy().astype(int)
```

This gives me tracker ids as an output. Is there any way to access and update yolov8 tracker? I am confused about "update_tracker" function you mentioned. Was it just some sort of pseudocode or was it me not being able to find it inside in YOLO. Big thanks.

**Comment by glenn-jocher** [comment]
@yusufkoca0 hi there,

No worries about the delay; I completely understand how busy things can get with school and other projects. 😊

Regarding your question, the `update_tracker` function I mentioned was indeed pseudocode to illustrate the concept. YOLOv8's built-in tracking functionality doesn't directly support modifying tracker IDs post-detection.

However, you can implement a custom logic to handle re-identification by maintaining a mapping of tracker IDs and updating them as needed. Here's a more concrete example to help you get started:

```python
# Initialize a dictionary to store the mapping of old IDs to new IDs
id_mapping = {}

# Function to update tracker IDs
def update_tracker_ids(result, id_mapping):
    for i, old_id in enumerate(result.boxes.id.cpu().numpy().astype(int)):
        if old_id in id_mapping:
            result.boxes.id[i] = id_mapping[old_id]
        else:
            # If the ID is new, add it to the mapping
            new_id = max(id_mapping.values(), default=0) + 1
            id_mapping[old_id] = new_id
            result.boxes.id[i] = new_id

# Example usage in your tracking loop
result = model.track(frame, persist=True, tracker="custom.yaml")[0]
update_tracker_ids(result, id_mapping)
detections = sv.Detections.from_ultralytics(result)
detections.tracker_id = result.boxes.id.cpu().numpy().astype(int)
```

This way, you can maintain consistency in tracker IDs even when objects are re-identified after occlusions.

I hope this clarifies things! If you have any more questions or need further assistance, feel free to ask. Good luck with your project! 🚀

**Comment by yusufkoca0** [comment]
Hi Glenn, sometimes the most obvious answers can be hard to imagine because we're so focused on the hard task. Thanks for the tip, since I was so determined on trying to update the tracker I didn't think about a simple dictionary lol. I didn't exactly use your implementation but it was helpful! Thanks for the help.

**Comment by glenn-jocher** [comment]
Hi @yusufkoca0,

I'm glad to hear that the suggestion helped spark a solution for you! It's often those simpler approaches that slip our minds when we're deep into complex problems. If you have any more questions or need further assistance as you refine your implementation, feel free to reach out. Happy coding and best of luck with your project!

**Comment by nadinator** [comment]
> Hi Glenn, sometimes the most obvious answers can be hard to imagine because we're so focused on the hard task. Thanks for the tip, since I was so determined on trying to update the tracker I didn't think about a simple dictionary lol. I didn't exactly use your implementation but it was helpful! Thanks for the help.

Were you able to solve your problem? I'm in the middle of something similar.

**Comment by glenn-jocher** [comment]
@nadinator i'm glad the information was helpful! If you have specific questions about your implementation, feel free to ask here, and I'll be happy to assist.

**Comment by samrere** [comment]
> [@nadinator](https://github.com/nadinator) i'm glad the information was helpful! If you have specific questions about your implementation, feel free to ask here, and I'll be happy to assist.

Hi @glenn-jocher,
I'm working on a project that involves tracking and re-identifying pigs. Based on the [documentation](https://docs.ultralytics.com/modes/track/#available-trackers), I see that the default tracker is BoT-SORT, but according to its [YAML file](https://github.com/ultralytics/ultralytics/blob/a1a0143342729737cac299f238c0902cc66af477/ultralytics/cfg/trackers/botsort.yaml#L18), Re-ID is currently not supported.

I'm considering fine-tuning OSNet to extract appearance features specific to pigs and then integrating it with BoT-SORT for tracking and Re-ID. This would involve using model(frame) for detections and passing the results to a custom BoT-SORT + OSNet pipeline, instead of relying on model.track(frame). Does this approach make sense, or is there a better way to achieve this within the current Ultralytics framework?

Also, are there any plans to support Re-ID in the default BoT-SORT tracker anytime soon? Thanks for your help!

**Comment by glenn-jocher** [comment]
Hi @samrere,  

Your approach to integrate a fine-tuned OSNet with BoT-SORT for pig Re-ID is valid and aligns with advanced tracking workflows. While Ultralytics YOLO currently does not natively support Re-ID in BoT-SORT ([trackers documentation](https://docs.ultralytics.com/modes/track/#available-trackers)), your proposed method of using YOLO11 for detection and passing results to a custom BoT-SORT + OSNet pipeline is a practical solution. This allows full control over appearance feature extraction while leveraging YOLO's detection capabilities.  

There are no immediate plans to add Re-ID support to the default trackers, but community contributions are welcome via [Ultralytics contributing guidelines](https://docs.ultralytics.com/help/contributing).  

For licensing: Ensure your implementation complies with AGPL-3.0 or obtain an [Ultralytics Enterprise License](https://ultralytics.com/license) for commercial/internal use.

**Comment by dkarvan8** [comment]
> > [@nadinator](https://github.com/nadinator) i'm glad the information was helpful! If you have specific questions about your implementation, feel free to ask here, and I'll be happy to assist.
> 
> Hi [@glenn-jocher](https://github.com/glenn-jocher), I'm working on a project that involves tracking and re-identifying pigs. Based on the [documentation](https://docs.ultralytics.com/modes/track/#available-trackers), I see that the default tracker is BoT-SORT, but according to its [YAML file](https://github.com/ultralytics/ultralytics/blob/a1a0143342729737cac299f238c0902cc66af477/ultralytics/cfg/trackers/botsort.yaml#L18), Re-ID is currently not supported.
> 
> I'm considering fine-tuning OSNet to extract appearance features specific to pigs and then integrating it with BoT-SORT for tracking and Re-ID. This would involve using model(frame) for detections and passing the results to a custom BoT-SORT + OSNet pipeline, instead of relying on model.track(frame). Does this approach make sense, or is there a better way to achieve this within the current Ultralytics framework?
> 
> Also, are there any plans to support Re-ID in the default BoT-SORT tracker anytime soon? Thanks for your help!



> > [@nadinator](https://github.com/nadinator) i'm glad the information was helpful! If you have specific questions about your implementation, feel free to ask here, and I'll be happy to assist.
> 
> Hi [@glenn-jocher](https://github.com/glenn-jocher), I'm working on a project that involves tracking and re-identifying pigs. Based on the [documentation](https://docs.ultralytics.com/modes/track/#available-trackers), I see that the default tracker is BoT-SORT, but according to its [YAML file](https://github.com/ultralytics/ultralytics/blob/a1a0143342729737cac299f238c0902cc66af477/ultralytics/cfg/trackers/botsort.yaml#L18), Re-ID is currently not supported.
> 
> I'm considering fine-tuning OSNet to extract appearance features specific to pigs and then integrating it with BoT-SORT for tracking and Re-ID. This would involve using model(frame) for detections and passing the results to a custom BoT-SORT + OSNet pipeline, instead of relying on model.track(frame). Does this approach make sense, or is there a better way to achieve this within the current Ultralytics framework?
> 
> Also, are there any plans to support Re-ID in the default BoT-SORT tracker anytime soon? Thanks for your help!

hey. I'm working on a similar project(reidentiifcation of humans)..I did integrate osnet in botsort but there's latency issue and the accuracy is bad. I would like to know if you successfully finished your project.

**Comment by glenn-jocher** [comment]
@dkarvan8 actually, there's been an update since the earlier discussion - Ultralytics YOLO now supports built-in ReID functionality! You can enable it by setting `with_reid: True` in your [tracker configuration](https://docs.ultralytics.com/modes/track/#enabling-re-identification-reid). This should address the latency and accuracy issues you encountered with custom OSNet integration.

The built-in ReID offers two options: native features from the YOLO detector (minimal overhead) or dedicated classification models like `yolo11n-cls.pt` for better embeddings. You might find this more efficient than a custom OSNet pipeline.

**Comment by dkarvan8** [comment]
> [@dkarvan8](https://github.com/dkarvan8) actually, there's been an update since the earlier discussion - Ultralytics YOLO now supports built-in ReID functionality! You can enable it by setting `with_reid: True` in your [tracker configuration](https://docs.ultralytics.com/modes/track/#enabling-re-identification-reid). This should address the latency and accuracy issues you encountered with custom OSNet integration.
> 
> The built-in ReID offers two options: native features from the YOLO detector (minimal overhead) or dedicated classification models like `yolo11n-cls.pt` for better embeddings. You might find this more efficient than a custom OSNet pipeline.

quick question how will classification model help because it doesn't generate any embeddings right..it just converts the original image into numpy array right

**Comment by glenn-jocher** [comment]
@dkarvan8 actually, classification models do generate embeddings! When used for ReID, the classification model extracts feature representations from the detection regions rather than just performing classification. These embeddings capture appearance characteristics that can be compared across frames to determine object similarity.

The process works by using the intermediate layers of the classification model (before the final prediction layer) to extract discriminative features from each detected object. These feature vectors are then used to match objects across frames, even after occlusions or ID switches.

This is more sophisticated than simple numpy array conversion - it's leveraging the learned representations from the classification model's backbone to create meaningful embeddings for appearance-based matching.
