### ISSUE TITLE
Why i can't use ultralytics.yolo

### ISSUE THREAD

**Issue by cbt12123** [ultralytics/ultralytics#12675]
### Search before asking

- [ ] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to use torch-prune after training my model by yolov8,but i found i can't import ultralytics.yolo like this:`from ultralytics.yolo.engine.model import TASK_MAP`
![1715658738703](https://github.com/ultralytics/ultralytics/assets/58580008/729597b7-5806-430d-af0c-c6e2a89d6e1f)

**Comment by glenn-jocher** [comment]
@cbt12123 hello! It looks like you're trying to import a module in a way that isn't supported by the current structure of the Ultralytics YOLO repository. Instead of using `from ultralytics.yolo.engine.model import TASK_MAP`, you should use the following import statement:

```python
from ultralytics import YOLO
```

After importing the YOLO class, you can load your model and access various functionalities provided by the YOLOv8 API. If you need to perform operations like pruning, you might need to work directly with the underlying PyTorch model, which can be accessed via:

```python
model = YOLO('path/to/your/model.pt')
torch_model = model.model  # This is the PyTorch model
```

From there, you can apply torch-prune or other PyTorch-based operations. If you have further questions or run into issues, feel free to ask! 🚀
