### ISSUE TITLE
where is the paper of YOLO v5?

### ISSUE THREAD

**Issue by ma3252788** [ultralytics/ultralytics#1268]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

V8 has been released, but I still can't find the v5 paper.

**Comment by pderrenger** [comment]
@ma3252788 hey there!

The YOLOv8 project focuses on the YOLOv8 model rather than YOLOv5. YOLOv5 was developed by a separate team, and its paper and documentation can be found on the YOLOv5 repository.

If you have any questions or need assistance regarding YOLOv8, feel free to ask, and I'll be happy to help!

Cheers!
