### ISSUE TITLE
Discrepancy between val params (conf, iou) and corresponding values in results.json(confidence_threshold, iou_threshold)

### ISSUE THREAD

**Issue by irconde** [ultralytics/ultralytics#12691]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm trying to replicate the results provided by Ultralytics when validating a detection model, which are saved by Ultralytics in results.json.

I created a Python script and used the following params for the val method:
return model.val(
        conf=0.001,
        iou=0.6,
    )
The values I see in results.json for those two params are:
...
    "general_metrics": {
        "confidence_threshold": 0.25,
        "iou_threshold": 0.45,
...

I would appreciate it if you could help me with this. Thanks!

**Comment by glenn-jocher** [comment]
Hello! It looks like there might be a misunderstanding regarding the parameters used during validation and their representation in the `results.json` file. The values you set in the `model.val()` method (`conf=0.001` and `iou=0.6`) are indeed used during the validation process. However, the values recorded in `results.json` under `confidence_threshold` and `iou_threshold` might reflect default or overridden settings used specifically for certain metrics calculations or post-processing steps.

To ensure consistency, you can explicitly specify these thresholds when calling the `val()` method and check if they match the output in `results.json`. Here's a quick example:

```python
results = model.val(conf=0.25, iou=0.45)
```

This should align the `results.json` output with the parameters you've set. If the discrepancy persists, it might be worth checking if any default settings or post-processing steps in the validation pipeline are affecting these values. Let me know if this helps or if you need further assistance! 😊

**Comment by irconde** [comment]
Will do @glenn-jocher. Thanks for the valuable feedback

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions or need further assistance, feel free to reach out. Happy coding! 😊

**Comment by irconde** [comment]
@glenn-jocher , I do have another question along similar lines. The predictions.json file generated by val has, let's say... , a list with 20,680 objects. However, as far as I understand, the figures provided by val for TP and FP do not match that number: 
TP: 18,513
FP: 1,422
FN: 2,051

I'd appreciate it if you could shed some light on this. Thanks again for the support

**Comment by glenn-jocher** [comment]
@irconde hello!

The numbers you're seeing in the `predictions.json` file and the TP, FP, FN counts can indeed differ due to several factors. The `predictions.json` file lists all detections made by the model, which includes every object the model has identified across all validation images, regardless of confidence score.

On the other hand, the TP (True Positive), FP (False Positive), and FN (False Negative) counts are derived from applying specific thresholds (confidence and IoU) to determine the accuracy of these detections against the ground truth labels:

- **True Positives (TP)**: Detections that match a ground truth label within the IoU threshold.
- **False Positives (FP)**: Detections that do not match any ground truth label or exceed the IoU threshold.
- **False Negatives (FN)**: Ground truth labels that were not detected by the model above the confidence threshold.

The sum of TP and FP will not necessarily match the total number of objects listed in `predictions.json` because some detected objects might be discarded based on the confidence threshold or IoU criteria used for calculating these metrics.

I hope this clarifies your query! Let me know if there's anything else you'd like to discuss. 😊

**Comment by irconde** [comment]
Thanks @glenn-jocher. I expected something like that, but I just wanted confirmation. 

Now, does that mean that nms is also used in a postprocessing step to discard detections based on the confidence threshold and IoU criteria before calculating TP, FN and FP? Or is iOU just used in a more straightforward way as a threshold to discard detections as well?

**Comment by glenn-jocher** [comment]
Hello @irconde,

Yes, you're on the right track! Non-Maximum Suppression (NMS) is indeed used as a post-processing step during the validation process. NMS helps in discarding overlapping detections based on the confidence scores and the IoU threshold. This ensures that only the most probable detections are considered, which effectively reduces the number of False Positives (FP).

The IoU threshold is then used to determine whether the remaining detections after NMS match the ground truth labels (to count as True Positives) or if they are mismatches/false alarms (counted as False Positives). False Negatives are simply the ground truths that weren't detected above the confidence threshold.

I hope this clears up how these metrics are calculated! If you have more questions, feel free to ask. 😊
