### ISSUE TITLE
Opencv C++ inference yolov8

### ISSUE THREAD

**Issue by FeiSong123** [ultralytics/ultralytics#1276]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

GPU:  RTX 3070 8GB

Hello everyone. Recently, I want to use OpenCV C++to infer yolov8 and yolov5. I found that if I want to infer yolov8, the OpenCV version must be above 4.7. So after I updated OpenCV to 4.7, it took 13 ms to infer yolov8m. onnx and 12 ms to infer yolov5m. onnx, but OpenCV4.5.4 cannot infer yolov8, and only 5 ms to infer yolov5. Have you ever encountered this problem and how to solve it.

**Comment by JustasBart** [comment]
Hi @FeiSong123 I haven't tried what you're describing but if it's more speed that you are looking for I don't think that OpenCV is specifically your best bet anyway. I know for me it's just the most convenient way of running Inference, but I think that even [ONNX Runtime](https://onnxruntime.ai/) should be faster. [OpenVino](https://docs.openvino.ai/latest/home.html) also offers all sorts of optimisations that I'm sure would enable you for a faster inference as well...

The only thing is that I'm sure you'll find that using either OpenVino or ONNX Runtime will require you to build all those additional dependencies and link them to your project and all the rest hence why I've stuck with OpenCV myself as I use it for most of what I do anyway so it's just super convenient and minimalist - but you're right it's not the most efficient.

Anyway good luck in your future endeavours of using yolov8 :rocket:

**Comment by FeiSong123** [comment]
@JustasBart Hello, thank you for your help. For me, using OpenCV is also because of its convenience. At present, the current inferenerce speed of OpenCV is enough for my use, but I just wonder why the inferenerce speed of OpenCV4.7.0 is slower than that of OpenCV4.5.4. As for onnx Runtime, I have never heard of it before. If I need faster reasoning speed in the future, I will try it. Thank you for your proposal!

**Comment by glenn-jocher** [comment]
@FeiSong123 I'd ask your question on the OpenCV repository as we aren't in control of their code so we don't know the cause of different performance with different versions.

ONNX runtime is the fastest way to run ONNX models. We use this automatically when pass an ONNX model, ie:

yolo predict yolov8n.onnx

**Comment by JustasBart** [comment]
@FeiSong123 Yeah, something like that can be a little bit tricky to track down as both the **OpenCV** team are constantly making changes/improvements but also the **Ultralytics** and the **ONNX** teams are making their own changes and optimisations as well, for instance in the past setting the **opset=12** wasn't a thing at all, but now with the latest **ONNX Exporter** it doesn't work with the newer opset version (17 I believe) etc... So you know there's just a lot of moving parts in that regard and so ultimately if it's ever not fast enough in my opinion you would really just have to look into one of the other (More optimised) options, but again having the convenience is also a one powerful thing to have...

I see what you mean though why would it get slower rather than either faster or the same, but I think that you know it could just be extra checks and whatnot from people finding bugs and all that so yeah what @glenn-jocher said you'd have to ask the **OpenCV** team first and see if that might lead you somewhere...

**Comment by FeiSong123** [comment]
@glenn-jocher @JustasBart Hello, I would like to follow the question you asked on OpenCV. Could you share a link.
Also, I recently wanted to try using onnx to use C++inference for Yolov5 on Ubuntu 20.04. However, as I am completely new in this field, can you provide me with some information on this aspect, please?

**Comment by JustasBart** [comment]
@FeiSong123 There exists an official yolov8 C++ example that can run both yolov8 and yolov5 models [here](https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-CPP-Inference) and if instead of exporting your own models you would like to instead try a sample model you can find a yolov8 / yolov5 model under the original repository [here](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX/tree/minimalistic/source/models). If you're having issues building your OpenCV you can refer to this guide:

![OpenCV build](https://user-images.githubusercontent.com/40023722/226941282-40b887eb-e338-4bdb-a9d5-f25dbf279c15.png)

Give it a go and see how you get on, good luck! :rocket:
