### ISSUE TITLE
I'm also having the same problem, I use botsort to track the target to detect the target but can't, the confidence level is also very high, the threshold setting should be fine. How to solve it, I thought it was a confidence threshold, but I can't debug it

### ISSUE THREAD

**Issue by Mster4** [ultralytics/ultralytics#12766]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

0: 384x640 1 car, 11.0ms
Speed: 2.0ms preprocess, 11.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
ultralytics.engine.results.Boxes object with attributes:

cls: tensor([0.], device='cuda:0')
conf: tensor([0.8089], device='cuda:0')
data: tensor([[1.6448e+03, 6.0801e+02, 1.7134e+03, 6.3788e+02, 8.0887e-01, 0.0000e+00]], device='cuda:0')
id: None
is_track: False
orig_shape: (1080, 1920)
shape: torch.Size([1, 6])
xywh: tensor([[1679.0945,  622.9431,   68.5400,   29.8672]], device='cuda:0')
xywhn: tensor([[0.8745, 0.5768, 0.0357, 0.0277]], device='cuda:0')
xyxy: tensor([[1644.8245,  608.0095, 1713.3645,  637.8767]], device='cuda:0')
xyxyn: tensor([[0.8567, 0.5630, 0.8924, 0.5906]], device='cuda:0')

id：None
tensor([[1644.8245,  608.0095, 1713.3645,  637.8767]])
None

the id: None
is_track: False

### Environment

Ultralytics YOLOv8.0.230 🚀 Python-3.10.0 torch-2.3.0+cu121 CUDA:0 (NVIDIA GeForce RTX 4080 Laptop GPU, 12282MiB)

### Minimal Reproducible Example

model = YOLO(self.model_filename)
tracks = model.track(im0, conf=0.3,persist=True, show=False, tracker='mybotsort.yaml')
                    print(tracks[0].boxes)
                    print(tracks[0].boxes.id)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
It seems like the tracking isn't being activated in your case, as indicated by `is_track: False` and `id: None`. This could be due to the tracker configuration not being properly loaded or recognized. Here are a couple of things you might want to check:

1. **Tracker Configuration**: Ensure that the `mybotsort.yaml` file is correctly set up and located in the right directory. The tracker configuration file should be accessible by the model at runtime.

2. **Tracker Initialization**: Make sure that the tracker is being initialized correctly in your code. Here's a small snippet to help you verify:

   ```python
   model = YOLO(self.model_filename)
   tracks = model.track(im0, conf=0.3, persist=True, show=False, tracker='mybotsort.yaml')
   if tracks[0].boxes.is_track:
       print("Tracking is active.")
   else:
       print("Tracking is not active.")
   ```

If these steps don't resolve the issue, it might be helpful to double-check the contents of your `mybotsort.yaml` to ensure all necessary parameters are correctly specified. If the problem persists, feel free to open an issue with the details, and we can look into it further! 🚀
