### ISSUE TITLE
The YOLOv8 segmentation model with batching option doesn't run on the GPU ?

### ISSUE THREAD

**Issue by shimaamorsy** [ultralytics/ultralytics#12776]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I tried to run yolov8-seg.onnx with the batching option activated, this error appeared ..

`ort-wasm-simd.jsep.js:54 2024-05-17 15:23:15.490199 [W:onnxruntime:, session_state.cc:1162 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf`

`ort-wasm-simd.jsep.js:54 2024-05-17 15:23:15.492300 [W:onnxruntime:, session_state.cc:1164 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.`

`ERROR_MESSAGE: Non-zero status code returned while running Softmax node. Name:'/model.22/dfl/Softmax' Status Message: Failed to run JSEP kernel`

**_To Produce_**
```
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.pt')  # load an official model
model = YOLO('path/to/best.pt')  # load a custom trained model

# Export the model
model.export(format='onnx' ,dynmic=True)
```
[_Here'is the mdel_](https://drive.google.com/file/d/1kHGS0nH8FHQTW_lgPMKCqL55WSoBHvLJ/view?usp=sharing)

**Script**
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"/>
    <title>Yolov8 test</title>

    <!-- ONNX RUNTIME -->
    <script src="https://cdn.jsdelivr.net/npm/onnxruntime-web/dist/ort.webgpu.min.js"></script>
  </head>
  <body>
   <script>
    const modelName = "yolov8n-seg-batching.onnx";
    const modelInputShape = [1, 3, 640, 640];
    async function testModel() {
    
        let model =  await ort.InferenceSession.create(modelName,{ executionProviders: ["webgpu","cpu"] });
        const tensor = new ort.Tensor("float32",new Float32Array(modelInputShape.reduce((a, b) => a * b)),modelInputShape);
        await model.run({ images: tensor });
        console.log(model);
    }
    testModel();
    </script>
  </body>
</html>
```

**Comment by glenn-jocher** [comment]
Hello! It looks like you're encountering an issue with running the YOLOv8 segmentation model with batching on a GPU using ONNX Runtime. The error message suggests that some operations are being assigned to the CPU instead of the GPU, which might be affecting performance.

Here are a couple of suggestions to potentially resolve this issue:

1. **Ensure GPU Support**: Make sure that your ONNX Runtime installation supports GPU execution. You might need to install the GPU-specific package for ONNX Runtime if not already done.

2. **Execution Providers**: In your script, you're specifying `"webgpu"` and `"cpu"` as execution providers. If you're aiming to run the model on an NVIDIA GPU, you should use `"cuda"` instead of `"webgpu"`. Modify your script as follows:

   ```javascript
   let model = await ort.InferenceSession.create(modelName, { executionProviders: ["cuda","cpu"] });
   ```

3. **Verbose Logging**: As the warning suggests, enabling verbose logging might provide more insights into why certain nodes are not being assigned to the GPU. This can help in diagnosing the issue further.

4. **Dynamic Batching**: You've mentioned using `dynamic=True` during export, which is great for flexibility in input sizes but can sometimes complicate execution provider optimizations. Ensure that your model and the ONNX Runtime version are compatible with dynamic batching.

If these steps don't resolve the issue, consider providing more details or the verbose logs as suggested by the error message. This could help in pinpointing the exact problem. Hope this helps! 😊

**Comment by chopin1998** [comment]
webgpu to cuda ?? 

no it under web env. 

i met same problem, yolo v8-pose pt model to onnx cannot running under onnx/webgpu

**Comment by pderrenger** [comment]
@chopin1998 thank you for the clarification. If you're running the model in a web environment using WebGPU, the issue might be related to the compatibility of certain ONNX operations with WebGPU. Unfortunately, not all ONNX operations are fully supported in WebGPU yet. You might want to check if the latest versions of ONNX Runtime and the model export tools address this issue. Additionally, consider running the model with verbose logging enabled to get more detailed information on the operations causing the problem. If the issue persists, it may be necessary to wait for further updates to ONNX Runtime's WebGPU support.
