### ISSUE TITLE
Ultralytics not working on Jetpack 6.0?

### ISSUE THREAD

**Issue by MOXHAN** [ultralytics/ultralytics#12772]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I recently updated our Jetson AGX Orin DevKit to the newest Jetpack Version 6.0 (nv_tegra release is 36.3.0) and now I am unable to install the Ultralytics package. When trying to install it using pip, it starts to search through all available versions of the package, eventually either fails and gives me the error that no matching distribution for the dependency opencv-python>4.6.0 was found or it succeeds, but installs Ultralytics version 0.0.44, which obviously is very outdated. Im trying to install the package inside a Docker Image, which is based on the nvidia jetson-inference image. I guess this is where the problem lies, however this has been working the exact same way before on Jetpack 5, so I was wondering if theres a fix for this?

**Comment by glenn-jocher** [comment]
Hi there! It seems like you're encountering compatibility issues with the latest Jetpack 6.0 update. Here are a couple of suggestions that might help:

1. **Check for Compatibility Updates**: Ensure that all dependencies, especially `opencv-python`, are compatible with Jetpack 6.0. Sometimes, newer OS versions require specific versions of packages.

2. **Manual Dependency Management**: Try manually installing a compatible version of `opencv-python` before installing Ultralytics. You can do this using:
   ```bash
   pip install opencv-python==4.5.5.64
   ```
   Then proceed with the Ultralytics installation.

3. **Use Virtual Environments**: If not already, using a Python virtual environment might help manage dependencies better without conflicting with the system packages.

4. **Consult NVIDIA's Documentation**: Since this issue arose after updating to Jetpack 6.0, NVIDIA's release notes or forums might have specific guidance or mention similar issues.

If these steps don't resolve the issue, it might be helpful to raise this with the NVIDIA support forums to check for any known issues with Jetpack 6.0 and Docker compatibility. 🚀

**Comment by MOXHAN** [comment]
Hi @glenn-jocher,

I was able to fix this by going back one version of the nvidia jetson-inference docker image. While I cant say what exactly was the problem, it does work now and ultralytics does install normally. Thanks! :)

Conclusion: nvidia/jetson-inference:r36.3.0 has some incompatibility with ultralytics package, use r36.2.0 instead when on Jetpack 6 for quick fix

**Comment by glenn-jocher** [comment]
Hi there! Great to hear you found a workaround by using the previous version of the NVIDIA Jetson-inference Docker image. 🎉 It's helpful to know about the compatibility issue with `nvidia/jetson-inference:r36.3.0`. Your feedback is invaluable and will surely assist others facing similar issues. Thanks for sharing your solution! 🚀
