### ISSUE TITLE
YOLOv8 Training Your Own Dataset

### ISSUE THREAD

**Issue by smallMantou** [ultralytics/ultralytics#12788]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I created a datasets folder to place my own images while training my dataset
<img width="178" alt="1" src="https://github.com/ultralytics/ultralytics/assets/156918297/5635c42e-571c-4735-84bd-fc53134a6550">
And write the model parameters in ultralytics 8.2.0/ultralytcs/cfg/models/v8/grayscale_yolov8s.yaml
<img width="674" alt="2" src="https://github.com/ultralytics/ultralytics/assets/156918297/f27bebb1-02cd-41c5-a776-f1d8c3e3f0d4">
Write dataset parameters in ultralys-8.2.0/ultralys/cfg/dataset/grayscale_data.yaml.
<img width="410" alt="3" src="https://github.com/ultralytics/ultralytics/assets/156918297/3ccded8b-02bb-4b6a-b175-5dc794499729">
Finally, train it
<img width="1077" alt="4" src="https://github.com/ultralytics/ultralytics/assets/156918297/84e03e2f-12d3-41c7-be65-6d7d4f0bd9f0">
He will prompt the following errors
OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "D:\A\A1\envs\YOLOv8\lib\site-packages\torch\lib\cublas64_11.dll" or one of its dependencies.

**Comment by smallMantou** [comment]
ImportError: DLL load failed while importing cv2: 页面文件太小，无法完成操作。

**Comment by glenn-jocher** [comment]
Hello,

This error typically occurs due to insufficient system memory or page file size, especially when loading large libraries like OpenCV in constrained environments.

You can try increasing the size of your system's page file:
1. Go to **Control Panel > System and Security > System > Advanced system settings**.
2. Under the **Advanced** tab, click on **Settings** in the Performance section.
3. Go to the **Advanced** tab in the Performance Options window, click on **Change** under Virtual memory.
4. Uncheck **Automatically manage paging file size for all drives**.
5. Select **Custom size** and enter a larger initial and maximum size for your page file.
6. Click **Set**, then **OK** and restart your computer.

Make sure your Python environment has enough memory allocated, and consider closing other memory-intensive applications while running your code.

If the problem persists even after increasing the page file size, please ensure that you have all the necessary system requirements and dependencies installed for OpenCV and PyTorch.

Hope this helps! Let us know how it goes.
