### ISSUE TITLE
The parameters printed through model.info are different from those printed through the val command

### ISSUE THREAD

**Issue by lishihong-1** [ultralytics/ultralytics#12786]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Why is the number of layers printed using model.info is different from the summary layers? Why does a yaml file show only twenty layers when there are actually two hundred layers? How should I print the parameters of my own model like a yaml file?
use model.info:
<img width="762" alt="5b0ba27e8dc789bee36b5d31b82e52fa" src="https://github.com/ultralytics/ultralytics/assets/73936514/eb292e26-37a9-408f-b902-e7f514fd5765">
use val command
<img width="675" alt="9e99649c8dfb84b1944f33305452707f" src="https://github.com/ultralytics/ultralytics/assets/73936514/3708c587-b5ea-4d6d-9683-60d8c5dd463b">
I hope to print parameters like this even though I have finished training, what should I do?
<img width="515" alt="cc769739cb96d313017854b7c48947eb" src="https://github.com/ultralytics/ultralytics/assets/73936514/e32b76bf-453f-420c-9af9-d594ebce46e7">

**Comment by glenn-jocher** [comment]
Hello! The discrepancy you're seeing between the outputs of `model.info` and the `val` command is likely due to different levels of detail each function is designed to provide. The `model.info` generally provides a detailed summary including all layers and parameters explicitly defined in your model. On the other hand, the `val` command focuses more on performance metrics and may summarize the model architecture more broadly.

To get a detailed parameter printout similar to what you see in a `.yaml` file post-training, you can use the `model.yaml()` method to print or even save your model definition:

```python
print(model.yaml())  # to display on screen
model.yaml(save_path='model_details.yaml')  # to save to a file
```

This will generate output similar to the initial YAML configuration, reflecting the full list of layers and parameters used in your model. If you’re specifically looking to match the visualization format in the last image, consider custom scripts or tools that format layer and parameter data accordingly. Happy modeling! 🚀
