### ISSUE TITLE
Can the yolov8 support to train the non-square (the default input size is w == h) image? 

### ISSUE THREAD

**Issue by xiaolinyezi** [ultralytics/ultralytics#1284]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

For example, the input train image with size 1920(w)*1080(h)? the ingsz=640 can be set to imgsz=1920,1080? Thank a lot.

**Comment by glenn-jocher** [comment]
@xiaolinyezi inference modes (predict, val), automatically run rectangular inference. Training is done on square mosaics.

You can set rectangular training with `yolo train rect` (not recommended).

**Comment by dceluis** [comment]
@glenn-jocher could you please expand on why is it not recommended to run yolo train with rect=True? I dont see this referenced anywhere else. Thanks

**Comment by glenn-jocher** [comment]
@dceluis rectangular training is technically supported, but it's generally not recommended because it can introduce additional complexity and potential issues in the training process.

Specifically, during training, YOLOv8 typically uses square image sizes because they allow for streamlined and stable batching and processing of images. This is important for maintaining a consistent aspect ratio and avoiding distortions during data augmentation and processing.

With rectangular training (i.e., when rect=True), input images of varying aspect ratios can potentially introduce inconsistencies. Different image sizes could lead to varying sizes of feature maps, which may not be handled appropriately by all parts of the model or may lead to increases in computational requirements and memory usage.

That said, it could be useful in certain cases where you're dealing with images of a specific and consistent non-square size, but in general, it can add complexity and potential instability in the training process. So, our default recommendation is to train on square images for the best and most consistent performance.
