### ISSUE TITLE
Not all dynamic dimensions are correctly set during model expert

### ISSUE THREAD

**Issue by zvant** [ultralytics/ultralytics#12902]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have trained a custom YOLOv8 model. It does pose estimation and face detection at the same time. And its `forward` function returns a set of tensors. The function looks like this:
```
class PoseFaceModel(PoseModel):
    ......
    def forward(self, x, *args, **kwargs):
        ......
        return face_boxes, face_confs, pose_kpts, pose_confs, face_crops, y_pose, y_face
```
I also do the NMS and some face-pose matching in the `forward` function. All the output tensors have the batch size as their first dimension.

Now I want to export this model to TensorRT. So I set the output format in the exporter as something like this:
```
        if isinstance(self.model, PoseFaceModel):
            output_names = ["face_boxes", "face_confs", "pose_kpts", "pose_confs", "face_crops", "y_pose", "y_face"]
        dynamic = self.args.dynamic
        if dynamic:
            dynamic = {"images": {0: "batch", 2: "height", 3: "width"}}  # shape(1,3,640,640)
            if isinstance(self.model, PoseFaceModelInferenceExport):
                dynamic["face_boxes"] = {0: "batch"}
                dynamic["face_confs"] = {0: "batch"}
                dynamic["pose_kpts"] = {0: "batch"}
                dynamic["pose_confs"] = {0: "batch"}
                dynamic["face_crops"] = {0: "batch"}
                dynamic["y_pose"] = {0: "batch", 2: "anchors"}
                dynamic["y_face"] = {0: "batch", 2: "anchors"}
```
And I call the exporter by:
```
model.export(format='engine', imgsz=1920, batch=1, half=True, dynamic=True, simplify=False, int8=False)
```

Wiredly, from the export log, I see only the input tensor and the last 2 output tensors are set correctly:
```
TensorRT: input "images" with shape(-1, 3, -1, -1) DataType.FLOAT
TensorRT: output "face_boxes" with shape(1, 32, 4) DataType.FLOAT
TensorRT: output "face_confs" with shape(1, 32) DataType.FLOAT
TensorRT: output "pose_kpts" with shape(1, 32, 11, 3) DataType.FLOAT
TensorRT: output "pose_confs" with shape(1, 32) DataType.FLOAT
TensorRT: output "face_crops" with shape(1, 32, 3, 160, 160) DataType.FLOAT
TensorRT: output "y_pose" with shape(-1, 56, -1) DataType.FLOAT
TensorRT: output "y_face" with shape(-1, 5, -1) DataType.FLOAT
TensorRT: WARNING ⚠️ 'dynamic=True' model requires max batch size, i.e. 'batch=16'
TensorRT: building FP16 engine as yolov8m-poseface.engine
```
For the other tensors, the first dimension is still `1` instead of `-1`. Is this normal? Or I have done something wrong? Any advice would be appreciate!

**Comment by glenn-jocher** [comment]
Hello! It looks like you're on the right track with setting up dynamic dimensions for your custom YOLOv8 model export to TensorRT. However, the issue you're encountering with the first dimension not being set to `-1` for certain tensors is likely due to how TensorRT handles dynamic shapes during the export process.

For TensorRT, when you specify dynamic axes, you need to ensure that the model's architecture and the export settings are correctly aligned to handle these dynamic dimensions. From your description, it seems that only the last two output tensors are correctly recognizing the dynamic batch size.

Here's a couple of things you might want to check or adjust:
1. **Ensure Consistency in Model Definition**: Double-check your model's forward function and make sure that all tensors that should have dynamic dimensions are correctly defined to handle varying batch sizes.
2. **Adjust Export Settings**: Sometimes, explicitly setting the dynamic axes for all outputs as you've done might not be recognized due to internal handling by the export function. You might need to adjust or simplify how you define these settings.

If these steps don't resolve the issue, consider providing a minimal reproducible example when you seek further help. This way, the community or the support team can replicate the issue exactly and provide more targeted assistance.

Here's a simplified dynamic setting you might try adjusting to:
```python
dynamic_axes = {'input': {0: 'batch'}, 'output': {0: 'batch'}}
model.export(format='engine', imgsz=1920, batch=1, half=True, dynamic_axes=dynamic_axes, simplify=False, int8=False)
```

Hope this helps! Let us know how it goes. 🚀

**Comment by zvant** [comment]
@glenn-jocher 
My forward function is quite complicated, involving multiple stages of scaling, NMS, sorting, indexing, matching, etc. It uses a for loop to iterate the samples in each batch. If TensorRT requires the dynamic dimension to be aligned through all these steps, it is not surprising it cannot work.

And yes, a simpler example does work with dynamic batch size.

My application does not really require dynamic batch size, so I might just set it to 1 for now. Thanks for the advice!

**Comment by glenn-jocher** [comment]
Hi there! 👋

It sounds like you've got a complex forward function with multiple operations that might indeed complicate the handling of dynamic dimensions in TensorRT. Sticking to a fixed batch size, especially if dynamic batching isn't a requirement for your application, is a practical approach. Setting the batch size to 1, as you mentioned, should help maintain consistency and stability in your model's performance.

If you ever need to revisit dynamic batching or encounter any other issues, feel free to reach out. Happy coding! 😊

**Comment by Petros626** [comment]
But why a `batch_size` of 16 can't be handled from FP32 best.pt to best.engine?

**Comment by glenn-jocher** [comment]
Handling larger batch sizes in TensorRT exports depends on available GPU memory and proper dynamic axis configuration. For FP32 models, memory requirements scale linearly with batch size - batch=16 needs 16x more memory than batch=1. The solution is to:

1. Set `dynamic=True` and specify max batch size via `batch=16`
2. Allocate sufficient workspace memory with `workspace=8` (8GB+ recommended)
3. Ensure your GPU has enough VRAM for both conversion and inference

For detailed TensorRT export configuration, see the TensorRT Export documentation.

**Comment by Petros626** [comment]
Approved

**Comment by glenn-jocher** [comment]
This error typically occurs when TensorRT encounters shape inconsistencies or insufficient GPU memory during INT8 calibration. For FP32 exports with larger batch sizes:

1. **Memory Allocation**: Use `workspace=None` to allow TensorRT auto-allocation as manual settings can cause overflow
2. **Batch Handling**: Ensure `dynamic=True` with explicit `batch=16` parameter
3. **Hardware Check**: Verify sufficient GPU memory exists for both conversion and inference (16GB+ recommended for batch=16)

For detailed configuration guidance, see the [TensorRT Export documentation](https://docs.ultralytics.com/integrations/tensorrt/#configuring-int8-export). Let us know if these adjustments resolve the issue.
