### ISSUE TITLE
AttributeError: module 'ultralytics.solutions' has no attribute 'SpeedEstimator'

### ISSUE THREAD

**Issue by gouni3790** [ultralytics/ultralytics#12903]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I used this code below.

import cv2
from ultralytics import YOLO, solutions

model = YOLO("yolov8n.pt")
names = model.model.names

cap = cv2.VideoCapture("path/to/video/file.mp4")
assert cap.isOpened(), "Error reading video file"
w, h, fps = (int(cap.get(x)) for x in (cv2.CAP_PROP_FRAME_WIDTH, cv2.CAP_PROP_FRAME_HEIGHT, cv2.CAP_PROP_FPS))

# Video writer
video_writer = cv2.VideoWriter("speed_estimation.avi", cv2.VideoWriter_fourcc(*"mp4v"), fps, (w, h))

line_pts = [(0, 360), (1280, 360)]

# Init speed-estimation obj
speed_obj = solutions.SpeedEstimator(
    reg_pts=line_pts,
    names=names,
    view_img=True,
)

while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        print("Video frame is empty or video processing has been successfully completed.")
        break

    tracks = model.track(im0, persist=True, show=False)

    im0 = speed_obj.estimate_speed(im0, tracks)
    video_writer.write(im0)

cap.release()
video_writer.release()
cv2.destroyAllWindows()

but, I have problem. 😂
"AttributeError: module 'ultralytics.solutions' has no attribute 'SpeedEstimator'"
why this error occur?

**Comment by gouni3790** [comment]
I already did this

**Comment by glenn-jocher** [comment]
Hi there! It looks like you've encountered an issue with the `SpeedEstimator` not being recognized. This could be due to a few reasons, such as the module not being updated or the feature not being available in your current version of the Ultralytics YOLO package.

Could you please ensure that you have the latest version of the Ultralytics YOLO installed? You can update it using pip:

```bash
pip install --upgrade ultralytics
```

If the problem persists, it might be helpful to check the official documentation or the latest release notes to see if `SpeedEstimator` is included or if there are any changes to how it should be implemented.

Let me know how it goes! 😊

**Comment by musharrafhamraz** [comment]
Upgrading ultralytics to latest version works. because the speed estimation is added recently.

**Comment by glenn-jocher** [comment]
Great to hear that upgrading to the latest version resolved the issue! The Speed Estimator feature is indeed a recent addition. If you have any more questions or need further assistance as you work with it, feel free to reach out. Happy coding! 😊
