### ISSUE TITLE
Exported TensorRT structure documentation? Fields are different

### ISSUE THREAD

**Issue by alsozatch** [ultralytics/ultralytics#12963]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When you load a YOLO model, e.g. `model = YOLO("yolov8n.pt")` it has fields such as `model.names`.
However, when you load a YOLO model exported to a TensorRT engine, e.g. `model = YOLO("yolov8n.engine")` it does not have the same fields. I need to link up a loaded engine in the same way as a normal model but I'm not finding documentation on how the fields are provided in the YOLO-loaded engines. Can you point me in the right direction? Thanks.

**Comment by glenn-jocher** [comment]
@alsozatch hello! When you export a YOLOv8 model to TensorRT format using `model.export(format='engine')`, the resulting `.engine` file does not inherently include all the Python attributes like `model.names` that are available in the PyTorch model. This is due to the nature of the TensorRT engine focusing primarily on optimized inference.

To access similar attributes when using the TensorRT engine, you'll need to manually handle these properties. For example, you can save the `model.names` to a file when exporting and load them separately when performing inference with the TensorRT engine.

Here's a quick example of how you might handle this:

```python
# When exporting the model
model = YOLO("yolov8n.pt")
model.export(format="engine")
with open("names.txt", "w") as f:
    f.write("\n".join(model.names))

# When loading the TensorRT engine
model = YOLO("yolov8n.engine")
with open("names.txt", "r") as f:
    names = f.read().splitlines()
```

This way, you can maintain access to necessary metadata like class names. For more details on handling specific fields or further customization, please refer to the [TensorRT documentation](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html) or the specific sections in the Ultralytics documentation related to TensorRT integration.

**Comment by alsozatch** [comment]
Usually GPT responses are misleading, but above seems mostly correct. I don't know about straight up reading/writing, but saving into a json and loading manually seems to be the best solution. The engine files just do not contain metadata that the pytorch models contain.

**Comment by glenn-jocher** [comment]
@alsozatch, you're right on point! 🎯 The TensorRT `.engine` files focus on optimized inference and don't include metadata like the PyTorch models do. Using JSON or a similar method to handle metadata separately, as you mentioned, is indeed a practical approach. If you have any more questions or need further assistance, feel free to ask. Happy coding!
