### ISSUE TITLE
get_latesr_run() when resume

### ISSUE THREAD

**Issue by jurijsnazarovsambientai** [ultralytics/ultralytics#12965]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

resume can be path to file or boolean (true/false). In case we provide boolean the `get_latest_run` in [`trainer.py` ](https://github.com/ultralytics/ultralytics/blob/c8b6a8bc37ce196a6b7e0c153539402db4383c16/ultralytics/engine/trainer.py#L647) returns some random `latest.pt` it found. I think it would be better to do `get_latest_run(os.path.join(self.args.project, self.args.name))` In that case we do not need to provide specific path to resume and code will find the latest model in a right path. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@jurijsnazarovsambientai hello! Thank you for bringing this to our attention. Your suggestion to modify the `get_latest_run()` function to search within a specific project and name directory makes sense for better targeting the latest model file. This would indeed streamline the resuming process by automatically finding the most recent model in the correct path.

Here's a quick example of how you could adjust the function call:

```python
get_latest_run(os.path.join(self.args.project, self.args.name))
```

This change would ensure that `get_latest_run()` fetches the latest model from the specified project and name directory, rather than from a broader scope.

If you're open to contributing, a pull request with this modification would be greatly appreciated! Let us know if you need any guidance on making this change. Thanks again for your input! 🚀
