### ISSUE TITLE
CLI question

### ISSUE THREAD

**Issue by georgelele1** [ultralytics/ultralytics#12974]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have added some code into the val.py under the yolo detect folder and when i run the validation via py file it can activiated my code correctly however when i try to run the validation by CLI the code i added seems skipped and not activated 
Here is the picture of the code i have added in the val.py print.results() function:
<img width="966" alt="image" src="https://github.com/ultralytics/ultralytics/assets/43303561/b17554ac-cfd2-4c3f-a332-57885b4bef8a">
the code was simply create a txt file and store the final log into it for later usage ! can anyone explain why it does not work and what should i do to make it work?
Thanks for your help

**Comment by glenn-jocher** [comment]
Hello! It sounds like the modifications you made to the `val.py` are not being recognized when running validations through the CLI. This could be due to the CLI using a different execution path or environment that doesn't pick up your local changes directly.

To ensure your changes are executed via the CLI, you might need to explicitly specify the path to your modified `val.py` or ensure that your environment is set up to use the modified version of the script. Here's a quick check you can do:

1. Make sure the CLI is pointing to the correct Python environment where your modified `val.py` is located.
2. You could also try invoking the CLI command from the same directory where your modified `val.py` resides to see if it picks up the changes.

If these suggestions don't resolve the issue, it might be helpful to look into how the CLI is configured to load the modules and see if there's a configuration that explicitly sets the script paths.

Hope this helps! Let me know if you have any more questions. 😊

**Comment by georgelele1** [comment]
the CLI i used is same as the normal yolo detect val model= data= batch= , i have looked over the validator.py under the engine folder which discribe how does the cli run i saw that inisde the validator it pass and import the print_result from the val.py which should be make no difference while i am running the cli instead of the python file ! it is very cofusing can you please help me with it for more detailed information ! Thanks

**Comment by glenn-jocher** [comment]
Hello! It sounds like you're encountering an issue where your modifications in `val.py` are not being executed when using the CLI, despite the `validator.py` importing `print_result` from `val.py`. This could potentially be due to the environment or the way the CLI is set up to execute the scripts.

To troubleshoot, please ensure that the CLI is indeed using the modified `val.py`. You might want to add a simple print statement at the start of `val.py` to confirm it's being executed when you run the CLI command. For example:

```python
print("Using modified val.py")
```

If you don't see this message when running the CLI, it indicates the CLI might be using a different copy or version of `val.py`. Double-check your environment and paths to ensure the correct files are being used.

If you continue to experience issues, providing the exact CLI command you're using could help further diagnose the problem. Thanks for reaching out, and I hope this helps! 😊

**Comment by georgelele1** [comment]
thanks i have add the print steatment into the val.py which prove that CLI did not go throw the modified python file and i am wonder which path and python filed did it used to do the validation?
Here is the CLI i used in the terminal:
<img width="1383" alt="image" src="https://github.com/ultralytics/ultralytics/assets/43303561/8063b64e-4aa4-4219-af7e-7a46d274bc18">
this is the one i use python file to execute:
<img width="1418" alt="image" src="https://github.com/ultralytics/ultralytics/assets/43303561/ef7d7a2e-566f-43e5-bdc6-d4fd0226ec91">
Which is easy to tell the difference because i have modifyied the log letter! so can you please tell me where can i find the path file for cli? also i have the enviroment just like the guide "pip install -r requirments" the application i used is anaconda!
Looking forward to your reply and thanks for all your help, i am appreciate it!

**Comment by glenn-jocher** [comment]
Hello! It looks like the CLI might be using a different installation of the Ultralytics package, possibly from a different Python environment. To check which file the CLI is using, you can run the following command in your terminal:

```bash
which yolo
```

This command will show you the path to the executable that is being called by the `yolo` command. If this path doesn't point to your expected environment (where you made changes), you might need to adjust your PATH or activate the correct Python environment.

Also, ensure that your Anaconda environment is activated when you run the CLI command. You can activate your environment using:

```bash
conda activate your_environment_name
```

Replace `your_environment_name` with the name of your environment. After activation, try running the `which yolo` command again to confirm that it points to the correct executable within your Anaconda environment.

Hope this helps! Let me know if there's anything else you need. 😊

**Comment by georgelele1** [comment]
it seems that there is a little misunderstanding, i have made some changes in the val.py file and the modification can be reflact in the python script based on the code in the guide as the image below:
<img width="1061" alt="image" src="https://github.com/ultralytics/ultralytics/assets/43303561/7893b17f-8a65-428a-b1f7-a9d19bf3e781">
however the modification does no appear in the CLI command code if i excute the val function via terminal below is the command:
<img width="1393" alt="image" src="https://github.com/ultralytics/ultralytics/assets/43303561/cc7f862a-3969-4cca-8c6d-12a93963d60b">
now i want to make the modification appear on the command execution as well as the py script what should i do. Thanks for your help and reply!

**Comment by glenn-jocher** [comment]
Hello! It seems like there might be a discrepancy between the Python environment used by your script and the one used by the CLI. Here are a few steps to ensure your modifications in `val.py` are recognized by the CLI:

1. **Check the Path**: Ensure the CLI is using the correct Python environment. You can verify this by running `which yolo` in your terminal to see the path of the executable being used.

2. **Activate the Environment**: Make sure your Anaconda environment is activated before running the CLI command. You can do this with:
   ```bash
   conda activate your_environment_name
   ```

3. **Reinstall the Package**: If the CLI is still not recognizing your changes, try reinstalling the Ultralytics package in your active environment:
   ```bash
   pip install -e .
   ```

These steps should help ensure that your modifications in `val.py` are reflected when using the CLI. Let us know if you need any further assistance! 😊
