### ISSUE TITLE
Yolov8 performance on Raspberry Pi 4B (8Gb)

### ISSUE THREAD

**Issue by montardon** [ultralytics/ultralytics#12996]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I ran a Yolov8 model (yolov8n) on my Raspberry Pi 4B.

I previously exported it to ncnn format to get the best performance on this platform.

When running with X server, I got an average 600ms inference time per image, on 230 images.
When running on CLI only, I got 500ms/im average on the same images.

It looks like the documentation show a 400ms/im performance on the benchmark graph for Raspberry Pi 4B.

Am I missing some optimization ?

I'm using latest image of raspios 64bit (Release date: March 15th 2024) with lastest version of Yolov8 (as of today).

**Comment by glenn-jocher** [comment]
Hello! 👋

It looks like you're already doing great by using the ncnn format for optimal performance on your Raspberry Pi 4B. The difference in inference times between X server and CLI-only environments is expected due to the additional overhead from the graphical interface.

To further optimize and potentially match the 400ms/im benchmark, consider the following:
- Ensure that no other processes are consuming significant CPU resources during inference.
- Try overclocking the Raspberry Pi CPU and GPU, if you haven't already, to squeeze out more performance.
- Verify that you're using the most efficient build of ncnn and that it's properly utilizing all available cores.

If you continue to see discrepancies, it might be worth revisiting the ncnn model conversion and optimization steps to ensure everything is configured optimally.

Keep up the great work! 🚀

**Comment by montardon** [comment]
Thank you for your quick answer.

I tried overclocking (with some freezes) and I achieved 470ms/im which is better and closer to your figures.

I also tried Yolov8n on an "old" Jetson Xavier NX and got 50ms/im which better, but less than with recent version.

**Comment by glenn-jocher** [comment]
@montardon hello!

Great to hear that overclocking improved your performance on the Raspberry Pi 4B! 🚀

Regarding the Jetson Xavier NX, the difference in performance could be due to various factors such as software versions or model optimizations specific to newer hardware. Ensuring that you're using the latest drivers and libraries optimized for the Xavier NX might help close the gap.

Keep experimenting, and feel free to reach out if you have more questions!
