### ISSUE TITLE
Attempt to Replicate Validation Produces Worse Results

### ISSUE THREAD

**Issue by keenanbuckley** [ultralytics/ultralytics#12994]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I've been trying to write a python script to load a YoloV8 model generated with Ultralytics CLI, and run it on the COCO dataset to replicate the expected results. This is so I can be sure that I am using the model correctly as I begin trying to use it in a C++ application I plan to work on. I haven't been getting the results I'm expecting, so how can I modify my script to better replicate the predictions Ultralytics CLI produces?

### Additional

When I use the CLI command `yolo val model=models/yolo/yolov8n.engine data=coco.yaml imgsz=640,640`, I get the expected results:
![image](https://github.com/ultralytics/ultralytics/assets/31972815/ff8484ec-1e28-4e52-a060-f0eac5abdebb)

However when I try using my script to generate similar results, they turn out much worse:
![image](https://github.com/ultralytics/ultralytics/assets/31972815/9fa52fbf-f1e2-41d7-b366-b115dd4ed7fd)

Here's the aforementioned script:

```
import cv2
from ultralytics import YOLO
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval
import json

dataDir = 'data'
dataType = 'val2017'
annFile='{}/annotations/instances_{}.json'.format(dataDir,dataType)

# initialize COCO api for instance annotations
coco=COCO(annFile)

# get all image ids
imgIds = coco.getImgIds()

# load TensorRT Engine
model = YOLO("models/yolo/yolov8n.engine")

# set batch size (must be a factor of 5000 to capture entire dataset)
batch_size = 1

coco_results = []
for num_processed in range(batch_size, len(imgIds)+1, batch_size):
    # make prediction
    batchIds = imgIds[num_processed-batch_size:num_processed]
    imgs = coco.loadImgs(batchIds)
    print(f'loading {len(imgs)} images...')
    batch = [cv2.imread(f'{dataDir}/images/{dataType}/{img["file_name"]}') for img in imgs]
    print(f'making {len(batch)} predictions...')
    results = model.predict(batch, verbose=False)
    
    # store results
    for imgIdx in range(len(results)):
        boxes = results[imgIdx].boxes
        for idx in range(len(boxes.cls)):
            # create dict for results
            r = dict()
            r["image_id"] = batchIds[imgIdx]
            r["category_id"] = int(boxes.cls[idx])+1
            r["bbox"] = [round(float(item),3) for item in boxes.xywh[idx]]
            r["bbox"][0] -= r["bbox"][2]/2  # x1 = cx - w/2
            r["bbox"][1] -= r["bbox"][3]/2  # y1 = cy - h/2
            r["score"] = round(float(boxes.conf[idx]), 5)
            coco_results.append(r)
    print(f'{num_processed} images processed.')

# save results to json file
with open(f'{dataDir}/results/{dataType}/results.json', 'w') as f:
    json.dump(coco_results, f)

# run evaluation
print(f'Running evaluation...')
cocoRes = coco.loadRes(f'{dataDir}/results/{dataType}/results.json')
cocoEval = COCOeval(coco,cocoRes,'bbox')
cocoEval.params.imgIds  = imgIds
cocoEval.evaluate()
cocoEval.accumulate()
cocoEval.summarize()
```

**Comment by glenn-jocher** [comment]
Hello! It looks like you've done a thorough job setting up your script for evaluation. However, if the results are not matching up with those from the CLI, here are a couple of things you might want to check:

1. **Preprocessing**: Ensure that your images are preprocessed in the same way as the CLI does. This includes resizing, normalization, and possibly color adjustments. The CLI might handle these implicitly.

2. **Batch Size**: You mentioned setting the batch size to 1. Sometimes, changing the batch size can affect the results due to differences in how batch normalization is handled. Try matching the batch size used in the CLI if it's different.

3. **Model Loading**: Double-check that the model loaded in your script is indeed the same and is being loaded correctly without any modifications or corruptions.

4. **Evaluation Metrics**: Ensure that the evaluation metrics and the way bounding boxes are handled (like conversion from center coordinates to corner coordinates) are consistent with those expected by the COCO API.

Here's a small tweak in your script to ensure the bounding box coordinates are correctly formatted before evaluation:

```python
# Adjust bbox coordinates from center to top-left corner
r["bbox"][0] = round(float(boxes.xywh[idx][0] - boxes.xywh[idx][2] / 2), 3)  # x1 = cx - w/2
r["bbox"][1] = round(float(boxes.xywh[idx][1] - boxes.xywh[idx][3] / 2), 3)  # y1 = cy - h/2
```

Try these adjustments, and let's see if it brings your script's output closer to the CLI results! 🚀
