### ISSUE TITLE
Model quantization with ONNX fails

### ISSUE THREAD

**Issue by Jamil** [ultralytics/ultralytics#13000]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

I exported a full-precision pretrained yolov8x model to ONNX using `yolo export`, and then tried to quantize with `onnxruntime`'s `quantize_static`. I get this output:

```
2024-05-21 13:34:36.438731609 [W:onnxruntime:, graph.cc:108 MergeShapeInfo] Error merging shape info for output. '/model.22/Split_output_0' source:{1,64,8400} target:{1,72,8400}. Falling back to lenient merge.
2024-05-21 13:34:36.438755354 [W:onnxruntime:, graph.cc:108 MergeShapeInfo] Error merging shape info for output. '/model.22/Split_output_1' source:{1,80,8400} target:{1,72,8400}. Falling back to lenient merge.
2024-05-21 13:34:36.440674476 [W:onnxruntime:, graph.cc:108 MergeShapeInfo] Error merging shape info for output. '/model.22/Sigmoid_output_0' source:{1,80,8400} target:{1,72,8400}. Falling back to lenient merge.
2024-05-21 13:34:36.442220273 [W:onnxruntime:, graph.cc:108 MergeShapeInfo] Error merging shape info for output. 'output0' source:{1,84,8400} target:{1,76,8400}. Falling back to lenient merge.
```

and, later, 
```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running QLinearConv node. Name:'QLinearConv_token_5159' Status Message: Input channels C is not equal to kernel channels * group. C: 1277 kernel channels: 1280 group: 1
```

It seems to work on fine-tuned models, but not the raw pretrained ones.

### Environment

```
OS                  Linux-6.5.0-35-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             pip
RAM                 251.52 GB
CPU                 AMD Ryzen Threadripper PRO 5955WX 16-Cores
CUDA                12.1

matplotlib          ✅ 3.5.1>=3.3.0
numpy               ✅ 1.26.2>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.1.0>=7.1.2
pyyaml              ✅ 5.4.1>=5.3.1
requests            ✅ 2.25.1>=2.23.0
scipy               ✅ 1.8.0>=1.4.1
torch               ✅ 2.1.2>=1.8.0
torchvision         ✅ 0.16.2>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
```

### Minimal Reproducible Example

```
    preproc_model_path = os.path.join(models_directory, 'model.preproc.onnx')
    quant_pre_process(input_model_path, preproc_model_path, skip_optimization=False)
    model_changed = qnn_preprocess_model(preproc_model_path, preproc_model_path)
    model_to_quantize = preproc_model_path if model_changed else input_model_path

    qnn_config = get_qnn_qdq_config(model_to_quantize,
                                    data_reader,
                                    activation_type=QuantType.QUInt8,
                                    weight_type=QuantType.QUInt8)

    model = onnx.load(model_to_quantize)
    output_model_path = os.path.join(models_directory, 'model.qdq.onnx')
    quantize(model_to_quantize, output_model_path, qnn_config)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hi there! It looks like you're encountering shape mismatch issues during the quantization process with ONNX Runtime. This is a common issue when the model's architecture has layers that dynamically adjust based on the input size or the model's internal configurations.

For pretrained models, especially those not fine-tuned, discrepancies in expected input and output dimensions can occur due to fixed parameters set during training. Here are a couple of suggestions:

1. **Ensure Consistent Input Dimensions:** Verify that the input dimensions during quantization match those used during the model's initial training. Any discrepancy can lead to the errors you're seeing.

2. **Model Simplification:** Before quantization, consider simplifying the model using ONNX's built-in tools. This can sometimes resolve issues related to unsupported operations or mismatches in layer configurations:
   ```python
   import onnx
   from onnx import optimizer

   # Load your model
   original_model = onnx.load('model.onnx')
   # Apply model simplification
   passes = ["extract_constant_to_initializer", "eliminate_unused_initializer"]
   simplified_model = optimizer.optimize(original_model, passes)
   onnx.save(simplified_model, 'simplified_model.onnx')
   ```

3. **Check Layer Configurations:** Ensure that all layers, especially those involving convolutions or transformations, are correctly configured to handle the dimensions they receive. This might require adjusting the model architecture slightly for compatibility with quantization.

If these steps don't resolve the issue, it might be helpful to look into the specific layers mentioned in the error logs and adjust their configurations accordingly. If you continue to experience difficulties, consider reaching out on the ONNX community forums or GitHub for more targeted advice.
