### ISSUE TITLE
Object undetectable after a while

### ISSUE THREAD

**Issue by PikachuRX78** [ultralytics/ultralytics#13025]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

After a period of time, the object can no longer be detected.
Initially detectable, but after a while, the object is no longer detected.
Even when the object appears on the screen, it shows "no detections".
Before:
![image](https://github.com/ultralytics/ultralytics/assets/32907497/c0336ab7-25d1-4bc7-bf41-4d22931ac272)
After:
![image](https://github.com/ultralytics/ultralytics/assets/32907497/0db3e93e-beec-4a7b-b666-ecdc366c0125)

0: 608x736 3 buss, 8.8ms
WARNING ⚠️ Waiting for stream 0
0: 608x736 2 buss, 7.8ms
0: 608x736 2 buss, 7.8ms
0: 608x736 2 buss, 6.8ms
0: 608x736 1 car, 7.8ms
0: 608x736 1 car, 7.8ms
0: 608x736 1 car, 8.8ms
0: 608x736 1 car, 8.8ms
0: 608x736 1 car, 7.8ms
0: 608x736 1 car, 8.8ms
0: 608x736 1 bus, 8.8ms
0: 608x736 1 bus, 8.8ms
0: 608x736 1 bus, 6.8ms
0: 608x736 1 bus, 6.8ms
0: 608x736 1 bus, 7.8ms
0: 608x736 1 bus, 7.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 8.8ms
0: 608x736 (no detections), 6.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 1 bus, 6.8ms
0: 608x736 (no detections), 6.8ms
0: 608x736 1 motorbike, 6.8ms
0: 608x736 (no detections), 6.8ms
0: 608x736 (no detections), 8.8ms
WARNING ⚠️ Waiting for stream 0
0: 608x736 (no detections), 6.8ms
0: 608x736 (no detections), 6.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 6.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 5.9ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 12.7ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 6.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 6.8ms
0: 608x736 (no detections), 8.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 6.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 8.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 6.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 6.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 6.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 6.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 7.8ms
0: 608x736 (no detections), 7.8ms

### Environment

Ultralytics YOLOv8.2.18 🚀 Python-3.11.7 torch-2.1.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3080 Ti, 12288MiB)
Setup complete ✅ (24 CPUs, 31.9 GB RAM, 198.2/476.9 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.11.7
Install             pip
RAM                 31.91 GB
CPU                 AMD Ryzen 9 5900X 12-Core Processor
CUDA                12.1

matplotlib          ✅ 3.8.2>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 9.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.28.1>=2.23.0
scipy               ✅ 1.11.4>=1.4.1
torch               ✅ 2.1.1+cu121>=1.8.0
torchvision         ✅ 0.16.1+cu121>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.7
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.1.4>=1.1.4
seaborn             ✅ 0.13.1>=0.11.0

### Minimal Reproducible Example

```
from ultralytics import YOLO
from ultralytics.solutions import speed_estimation


def camera_task(rtsp_link, rgb_to_radar_queue, cam_frame_queue):
    model = YOLO("model/best.pt")
    while True:
        results = model.track(source=rtsp_link,show_conf=False,conf=0.3,verbose=True,stream=True,show=True)
        for res in results:
            if res.boxes.id != None:
                track_ids = res.boxes.id.int().cpu().tolist()
            else:
                track_ids = int(-1)
            boxes = res.boxes.xywh.cpu()
            annotated_frame = res.plot(conf=False)

            cam_frame_queue.put([boxes,track_ids,annotated_frame])

            obj_boxes = res.boxes.xyxy
            obj_cls = res.boxes.cls

            rgb_to_radar_queue.put([annotated_frame, obj_boxes, obj_cls])

```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@PikachuRX78 it looks like your model might be experiencing issues with detecting objects consistently over time. Here are a couple of things you could check and try:

1. **Model Overheating**: If the detection performance degrades over time, it might be due to the hardware, especially the GPU, overheating. Ensure your cooling systems are working correctly.

2. **Memory Leak**: There could be a memory leak in your application that affects performance as it runs longer. Monitor your system's memory usage over time to check for any unusual increases.

3. **Dynamic Changes in the Scene**: If the environmental conditions (like lighting, angle, or background) in the video stream change significantly, the model might struggle to detect objects. Try to ensure consistent conditions, or consider retraining your model with more varied data.

4. **Threshold Adjustments**: Sometimes, adjusting the confidence threshold (`conf`) might help in maintaining detection consistency. Experiment with different values to find a balance between detection accuracy and reliability.

5. **Update Model**: Ensure you are using the latest version of the YOLOv8 model and Ultralytics library, as updates often include performance improvements and bug fixes.

If these suggestions don't resolve the issue, please provide more details about the conditions under which the object becomes undetectable, and we can explore further solutions! 🚀
