### ISSUE TITLE
Instance segmentation custom model training

### ISSUE THREAD

**Issue by Anchal123Kumar** [ultralytics/ultralytics#13046]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

from ultralytics import YOLO

def main():
    model = YOLO("D:\\AI\\Mars\\interface scrub\\yolov8n-seg.pt")
    results = model.train(
        data="D:\\AI\\Mars\\interface scrub\\Data\\data.yaml",
        imgsz=640,
        epochs=130,
        batch=30,
        name="Office_Senitize15",
        task="segment"
        
    )
   

if __name__ == '__main__':
    main()
    
    
    Downloading https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8n.pt to 'yolov8n.pt'... 

I am training my custom dataset for instance segmentation on vs code and above is the code I am using to train but it starts to download yolov8n.pt and I suspect it is not training the segmentation model. So Please anyone verify that the code I am using is correct or not, if not, then help me with it. Also added the screenshot of the training terminal for the reference.
![Screenshot (2)](https://github.com/ultralytics/ultralytics/assets/94280751/c1dbf9db-ed35-4da3-a198-bc81e9faa7a4)

**Comment by glenn-jocher** [comment]
Hello! It looks like you're trying to train an instance segmentation model but the code is loading a detection model instead. To train a segmentation model, you should use a segmentation model file, like `yolov8n-seg.pt`, instead of `yolov8n.pt`.

Here's a corrected version of your code:

```python
from ultralytics import YOLO

def main():
    # Ensure you're using a segmentation model
    model = YOLO("D:\\AI\\Mars\\interface scrub\\yolov8n-seg.pt")
    results = model.train(
        data="D:\\AI\\Mars\\interface scrub\\Data\\data.yaml",
        imgsz=640,
        epochs=130,
        batch=30,
        name="Office_Senitize15",
        task="segment"
    )

if __name__ == '__main__':
    main()
```

Make sure that `yolov8n-seg.pt` is correctly placed in your specified directory or adjust the path accordingly. This should resolve the issue of downloading the wrong model and ensure you're training with the correct segmentation model. Happy training! 🚀
