### ISSUE TITLE
argument save_dir doesn't work

### ISSUE THREAD

**Issue by AN-ZE** [ultralytics/ultralytics#13041]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

use python  environment  train and predict.
results = model.train(data='ultralytics/cfg/datasets/VOC.yaml', 
                      save_dir='/home/lutos/anze/ultralytics/yolov8n')
 results = model(img_path,
                    save_dir='/home/lutos/anze/ultralytics/yolov8n_qrcode')

The save_dir argument doesn't work,
 My thoughts https://github.com/ultralytics/ultralytics/issues/8912
adding this argument to the file(ultralytics/cfg/default.yaml) can fix this problem.

### Environment

ubuntu20.04
git clone new master.

### Minimal Reproducible Example

No response

### Additional

No response

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@AN-ZE there is no `save_dir` argument. For Predict mode arguments see https://docs.ultralytics.com/modes/predict/#inference-arguments

**Comment by AlexandreOuellet** [comment]
Sorry to comment on an old PR, but I have an issue that is related to this PR.
Here's what I'm trying to do :

1. Load a model
2. do a prediction with visualize=True
3. save that prediction and visualization in a folder

The issue that I encounter is saving the visualization.  It appears that I can send overrides to predict() to use with the predictor, but save_dir was specifically removed from overrides in this PR specifically.  How do I specify save_dir now?  Using Result class is not good enough as I want to save the visualization created with predict(img, visualize=True) somewhere I know.  Since the predictor is essentially "lazy loaded", and since it removes the save_dir as a feature, I can't really rely on doing predict(img, visualized=True, save_dir="/tmp/somedir").  Do I now need to do an empty predict, then pass in an override?

I expected to be able to do something like this : 
```python
temp_dir = tempfile.mkdtemp()
model.predict(image, visualize=True, save_dir=temp_dir)
```

Instead, I seem to be forced to actually move the files after the fact, like this : 
```python
model.predict(image, visualize=True)
#move everything into the tmp folder
shutil.move(model.predictor.save_dir, tempfile.mkdtemp())
```

Why was save_dir removed in #4480?

**Comment by glenn-jocher** [comment]
@AlexandreOuellet hello! Thanks for reaching out with your query. I understand the confusion regarding the `save_dir` parameter.

In the current implementation of the YOLOv8 `predict()` method, the `save_dir` parameter isn't directly modifiable as an argument. Instead, the results and visualizations are automatically saved in the `runs/predict` directory under the project directory.

To save the visualizations to a specific directory, you can indeed move the files after prediction as you've described. Here's a streamlined approach:

```python
import shutil
import tempfile
from ultralytics import YOLO

# Load your model
model = YOLO('path/to/model.pt')

# Run prediction
results = model.predict('path/to/image.jpg', visualize=True)

# Create temporary directory and move files
temp_dir = tempfile.mkdtemp()
for path in results.files:
    shutil.move(path, temp_dir)
```

This method ensures that all generated files from the prediction are moved to your desired temporary directory.

We appreciate your feedback on this, and I'll relay it to our development team to consider reintroducing or modifying the `save_dir` functionality in future updates. If you have any more questions or need further assistance, feel free to ask. Happy coding! 🚀

**Comment by AN-ZE** [comment]
@AlexandreOuellet 
Hi, your problem is actually the same as mine.
