### ISSUE TITLE
Model exported to CoreML showing 1.0 confidence values for all detections

### ISSUE THREAD

**Issue by 117nyx** [ultralytics/ultralytics#13079]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am working on a project that uses a YOLO model in IOS, but am running into issues with false positives once I export to CoreML. When making predictions using the CoreML model, all of the bounding boxes predicted have a confidence value of 1.0, whereas running the same images through the model in python I see confidence values that are (0,1]. What am I tripping up on? Below is a snippet from my training and translation script.

`from ultralytics import YOLO`
`model = YOLO("yolov8m.pt")`
`included_class = [0,1]`
`model.train(data="YOLODataset/dataset.yaml",epochs=100,imgsz=480)`
`model.export(format="coreml",imgsz=[480,384],nms=True)`

**Comment by glenn-jocher** [comment]
Hello! It looks like the issue with confidence values being 1.0 in your CoreML model might be related to the post-processing steps, specifically the Non-Maximum Suppression (NMS) that's integrated during the export. When exporting to CoreML with `nms=True`, the model should handle overlapping detections and confidence scores correctly.

Here are a couple of things you might want to check or try:

1. Ensure that the latest version of `ultralytics` is installed, as updates often fix such issues.
2. Try exporting the model without setting `nms=True` to see if the confidence scores vary as expected. This can help isolate if the issue is related to the NMS configuration in CoreML.

If the problem persists, consider providing more details or the output logs which might give more insight into what's happening during the export process. This will help in diagnosing the issue more effectively.

**Comment by glenn-jocher** [comment]
Hello! It seems like you're encountering a known issue with the CoreML export, particularly with the confidence scores and model recognition in newer versions of coremltools. A potential workaround, until a fix is implemented, is to continue using the combination of Ultralytics==8.0.75 and CoreMLTools==6.2, which you mentioned works for producing sensible results.

For the issue with `nms=False` leading to CoreML not recognizing the model as a vision model, this might be related to how the metadata is handled during the export. You could try manually setting the model type in your CoreML model's metadata after export, or explore using a different version of coremltools that might handle this more gracefully.

If these suggestions don't resolve your issue, please provide more details or error logs, and we can look further into this! 🚀

**Comment by finleyqqq** [comment]
> 1. When I export using the latest version of Ultralytics and coremltools>=7.0 I am running into issues that others have had as shown here: [Issue with exported coreml model on ios17 and Sonoma #5165](https://github.com/ultralytics/ultralytics/issues/5165).
> 
> I am able to produce a model that has sensible results when I use Ultralytics==8.0.75 and CoreMLTools==6.2, however all of the predictions from the coreml model have 1.0 confidence.
> 
> When I export the model with nms=False, CoreML doesn't seem to recognize the model as a vision model, and predictions are nil when I try to predict using the coreml model that I exported.

Hi, I met the same problem. I would like to ask if you solved this problem. Looking forward to hearing from you.

**Comment by barbaramartina** [comment]
Hello, I am dealing with a similar issue. I exported Yolo26-class... and CoreML (without nms) is not mapping any variable called "confidence" to the output... I only have an array, with the name of the classes in a variable called var_564 ... With values from 0... to 1.0 ... can I derive "confidence" from the float assigned to the class in that array?

**Comment by glenn-jocher** [comment]
If you exported a **classification** checkpoint (`model.task == "classify"`), then it’s expected you only see a single output array of per-class probabilities (your `var_564`), and you can treat the max class probability as the “confidence”; if you’re expecting **bounding boxes**, you need a **detect** model and should export with `nms=True` so the CoreML pipeline exposes the `confidence` and `coordinates` outputs (see how we build the CoreML NMS pipeline in the [exporter CoreML pipeline reference](https://docs.ultralytics.com/reference/engine/exporter/)); since this issue is closed/stale, if you’re still blocked please open a new issue with your `yolo checks` output and the full export log.
