### ISSUE TITLE
New network structure with old weights

### ISSUE THREAD

**Issue by TonightGo** [ultralytics/ultralytics#13086]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to trian a new network structure, load old weights: 
![image](https://github.com/ultralytics/ultralytics/assets/20351057/88d7bb1a-c710-40ba-9067-5fc533c54f2f)
![image](https://github.com/ultralytics/ultralytics/assets/20351057/29d0a763-de24-4d94-8f80-c2f247e96688)
![image](https://github.com/ultralytics/ultralytics/assets/20351057/acc5f23f-72d7-49c2-be62-cf61ce0ba07e)
The model is modified ok. But why the model change back while train.
![image](https://github.com/ultralytics/ultralytics/assets/20351057/bed9586f-4d4c-4dc9-8a5a-723b25185ea5)

**Comment by glenn-jocher** [comment]
Hello! It looks like you're trying to train a new network structure using pre-existing weights. If your model reverts to the original structure during training, it might be due to the way the weights are being loaded. Ensure that the weights are compatible with the new model structure, and check if the model definition in your training script correctly reflects the new architecture.

Here's a quick example of how you can load the weights:

```python
from ultralytics import YOLO

# Load your custom model architecture
model = YOLO('path/to/new_model.yaml')

# Load weights from the old model
model.load('path/to/old_weights.pt', strict=False)  # Use strict=False to allow mismatch

# Now you can proceed with training
model.train('data.yaml', epochs=100)
```

Make sure that the `strict=False` parameter is used to allow for the size mismatches between the new model and the old weights. This should help in adapting the old weights to your new structure without forcing the architecture to revert. If you continue to experience issues, double-check the architecture changes and ensure they are saved correctly.

**Comment by TonightGo** [comment]
load() got an unexpected keyword argument 'strict'，but in the function, it set strict=False default when call torch.load.
I use model.load('path/to/old_weights.pt'), it works.
Thank you for your help. ~~

**Comment by glenn-jocher** [comment]
@TonightGo hello! I'm glad to hear that using `model.load('path/to/old_weights.pt')` worked out for you. It seems there was a misunderstanding regarding the `strict` parameter; it's not directly used in the `model.load()` method for YOLOv8. The method handles the loading process internally, including any necessary adjustments for weight compatibility. If you have any more questions or need further assistance, feel free to ask. Happy coding! 😊
