### ISSUE TITLE
Can YOLOv8 Simultaneously Support Rotated Object Detection (OBB) and Keypoint Detection?

### ISSUE THREAD

**Issue by 666echo** [ultralytics/ultralytics#13090]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Description:
I am currently working on a project where I need to detect objects along with their keypoints. However, instead of using standard rectangular bounding boxes, I require the detection to be based on rotated bounding boxes (OBB). This is essential for my application as I need to compute the keypoints within the object and correct the object's orientation to a standard angle.

As far as I know, YOLOv8 supports rectangular bounding boxes and keypoint detection separately. I am unsure how to integrate both rotated bounding boxes and keypoint detection into a single model.

Questions:
Is it feasible to train a single YOLOv8 model that can handle both OBB and keypoint detection simultaneously?
What modifications would be necessary to the model architecture and the training pipeline to achieve this?
Are there any existing implementations, workarounds, or extensions that can help in achieving this functionality?

Any guidance, references to similar implementations, or suggestions on how to modify the YOLOv8 codebase would be highly appreciated. I am looking forward to any advice or ideas that can help me with this requirement. Thank you in advance for your support and assistance!

**Comment by glenn-jocher** [comment]
Hello! Great to see your interest in extending YOLOv8 capabilities for your project. Currently, YOLOv8 does not natively support a single model that handles both Oriented Bounding Boxes (OBB) and keypoint detection simultaneously. Each task is typically handled by distinct model architectures due to their different output requirements.

However, you can approach this challenge by:
1. **Sequential Processing**: First use an OBB model to detect objects and then run a keypoint detection model on the regions defined by the OBBs.
2. **Custom Model Development**: Modify the YOLOv8 architecture to output both keypoints and OBBs. This would involve significant changes to the model's head to predict additional keypoints along with the angle for rotation.

For the second approach, you might need to dive deep into the model's architecture and training pipeline, adjusting the loss functions to handle both tasks effectively.

No existing implementations directly combine these two in YOLOv8, but exploring related research papers or similar tasks might give you some insights on integration.

If you decide to modify the YOLOv8 codebase, consider the impact on training complexity and inference performance. Good luck with your project, and feel free to reach out if you have more questions! 🚀

**Comment by 666echo** [comment]
Thank you for your helpful advice. I’m now following your suggestion to use OBB detection followed by keypoint detection. However, I still have a query I hope you can clarify for me. For identifying a simple triangle, should I label the three keypoints with the same tag, or should each keypoint have a unique label? I don't have any sequence or position constraints; I just need the keypoints that form the triangle. The order does not matter to me, as long as the model can predict these three points. Once again, thank you for your assistance.

**Comment by glenn-jocher** [comment]
You're welcome! For your triangle keypoints, you can label all three keypoints with the same tag since the order doesn't matter to you. This way, the model will learn to detect the three points that form the triangle without worrying about their sequence. Happy coding! 😊
