### ISSUE TITLE
edgetpu.ftlite is numpy.int8 but Coral only support uint8 input type

### ISSUE THREAD

**Issue by oscarhuang1117** [ultralytics/ultralytics#13108]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have used this code ( **!yolo export model=/content/drive/MyDrive/yolov8/best.pt format=edgetpu** ) in Colab, and successfully obtained **\best_saved_model\yolov8s-pose_full_integer_quant_edgetpu.tflite**.
But when I use yolov8s-pose_full_integer_quant_edgetpu.tflite on my Coral, it tells me **ValueError: Only support uint8 input type**, then I check my edgetpu.tflite's type, which is numpy.int8.
Please tell me how to solve this problem, thanks!

**Comment by glenn-jocher** [comment]
@oscarhuang1117 hello! It looks like there's a mismatch between the data types expected by the Coral Edge TPU and the ones produced by the export process. To resolve this, you can modify the export process to ensure the model uses `uint8` quantization instead of `int8`. Unfortunately, direct control over this isn't available through the YOLO CLI or API directly.

However, you can manually adjust the quantization parameters in the TensorFlow code before exporting if you have access to the TensorFlow model conversion scripts. If you're using the Ultralytics export functionality, ensure you're using the latest version as updates and fixes are continuously made.

If the issue persists, consider opening an issue on the Ultralytics GitHub page to get specific help or updates on this matter.
