### ISSUE TITLE
Deepsparse provides empty results with custom yolov8 model

### ISSUE THREAD

**Issue by nithrous** [ultralytics/ultralytics#13112]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Environment: python:3.8.10 docker container inside windows 11

I get empty result from deepsparse on my custom model with another classes based on `yolov8n`, but get normal results on original `yolo8n`. Default yolo predict works great for my custom model

Inference code:
```
model_path = "mymodel.onnx"
image = "myimg.jpg"

from deepsparse import Pipeline
yolo_pipeline = Pipeline.create(task="yolov8", model_path=model_path)
images = [image]
pipeline_outputs = yolo_pipeline(images=images)

print(pipeline_outputs)
```

My model output on my image:
```
boxes=[[]] scores=[[]] labels=[[]] intermediate_outputs=None
```

Original model output on the "bus.jpg" image:
```
boxes=[[[51.587910890579224, 397.2844820022583, 241.35066676139832, 905.3627014160156], [224.02489471435547, 406.10554218292236, 345.86957359313965, 857.8140106201172], [670.8741788864136, 389.5267095565796, 809.8364667892456, 875.7920036315918], [5.2853593826293945, 226.4121551513672, 803.8898677825928, 744.6077270507812], [-0.05325740575790405, 548.21337890625, 71.32903254032135, 873.0747413635254]]] scores=[[0.8920409083366394, 0.8821775913238525, 0.8800204992294312, 0.8768078088760376, 0.5801830291748047]] labels=[['0.0', '0.0', '0.0', '5.0', '0.0']] intermediate_outputs=None
```

Both models were downloaded from ultralytics hub and converted to onnx format using:
```
yolo task=detect mode=export model=[model_name].pt format=onnx opset=13
```

Does anybody know the reason or some ideas how to debug it?

**Comment by nithrous** [comment]
Here is the target image:
![image](https://github.com/ultralytics/ultralytics/assets/10476019/5d138111-b790-4dc0-bfba-a51c131f3c44)

So i'm detecting small items. Tried another one, had some results, but precision is few times lower.
Also tried to use yolov8m instead yolov8n. Have some progress, but it cannot detect all objects, the precision is 40 percent vs 90 using regular yolo

Also noticed this output line:
deepsparse.pipeline WARNING  Could not create v2 'yolov8' pipeline, trying legacy

**Comment by glenn-jocher** [comment]
@nithrous it looks like you're dealing with a few issues related to model performance and pipeline creation warnings when using DeepSparse with your YOLOv8 models.

1. **Model Precision**: The drop in precision when switching from YOLOv8n to YOLOv8m and using DeepSparse might be due to the differences in model architecture and how well each model handles the sparsity. YOLOv8m is generally more complex than YOLOv8n, which could affect its performance under sparsity.

2. **Detection of Small Objects**: If your target objects are small, you might need to adjust the model's anchor sizes or the input resolution to better capture the details of smaller objects. Increasing the input resolution can help the model detect smaller objects more accurately.

3. **Pipeline Warning**: The warning about the pipeline could indicate an issue with the compatibility of the model or the specific configuration of DeepSparse. Ensure that your ONNX model is exported correctly with the appropriate `opset` version and that it's compatible with the DeepSparse version you're using.

Here's a quick check you can do to ensure your ONNX model is set up correctly for DeepSparse:
```python
from deepsparse import compile_model
model = compile_model(model_path="path_to_your_model.onnx", batch_size=1)
print(model)
```
This will give you an idea if the model is loaded correctly without initiating the full pipeline.

For improving detection on small objects, consider experimenting with different image sizes during the export:
```bash
yolo export model=yolov8n.pt format=onnx imgsz=832,832 opset=13
```
Using a larger `imgsz` might help improve the detection of smaller objects.

If these adjustments don't help, I recommend revisiting the training phase to ensure your model is well-tuned for the specifics of your dataset, especially regarding small object detection.

**Comment by nithrous** [comment]
> @nithrous it looks like you're dealing with a few issues related to model performance and pipeline creation warnings when using DeepSparse with your YOLOv8 models.
> 
> 1. **Model Precision**: The drop in precision when switching from YOLOv8n to YOLOv8m and using DeepSparse might be due to the differences in model architecture and how well each model handles the sparsity. YOLOv8m is generally more complex than YOLOv8n, which could affect its performance under sparsity.
> 2. **Detection of Small Objects**: If your target objects are small, you might need to adjust the model's anchor sizes or the input resolution to better capture the details of smaller objects. Increasing the input resolution can help the model detect smaller objects more accurately.
> 3. **Pipeline Warning**: The warning about the pipeline could indicate an issue with the compatibility of the model or the specific configuration of DeepSparse. Ensure that your ONNX model is exported correctly with the appropriate `opset` version and that it's compatible with the DeepSparse version you're using.
> 
> Here's a quick check you can do to ensure your ONNX model is set up correctly for DeepSparse:
> 
> ```python
> from deepsparse import compile_model
> model = compile_model(model_path="path_to_your_model.onnx", batch_size=1)
> print(model)
> ```
> 
> This will give you an idea if the model is loaded correctly without initiating the full pipeline.
> 
> For improving detection on small objects, consider experimenting with different image sizes during the export:
> 
> ```shell
> yolo export model=yolov8n.pt format=onnx imgsz=832,832 opset=13
> ```
> 
> Using a larger `imgsz` might help improve the detection of smaller objects.
> 
> If these adjustments don't help, I recommend revisiting the training phase to ensure your model is well-tuned for the specifics of your dataset, especially regarding small object detection.

Your advice to increase imgsz helped, accuracy increased dramatically, without significant performance loss
`compile_model` from deepsparse loaded the model successfully, will ask about "legacy warning" deepsparse guys
Thanks a lot!

Why did you adviced to try 832 img size? Is there some magic number set?

**Comment by glenn-jocher** [comment]
Great to hear that increasing `imgsz` improved accuracy! 🎉

The choice of 832 isn't magic but rather a balance between resolution and performance. Larger sizes help detect smaller objects better. Feel free to experiment with different sizes to find the optimal one for your use case.

Good luck, and happy detecting! 🚀
