### ISSUE TITLE
Problem exporting yolov8n segmentation model to edgetpu

### ISSUE THREAD

**Issue by MukilSundaravadivel** [ultralytics/ultralytics#1313]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

After successfully training the base model yolov8n-seg.pt, I tried exporting best.pt to edgetpu format but encountered these errors: 

(Colab)

![image](https://user-images.githubusercontent.com/67285595/223586121-dcb5e197-641b-4454-b16e-67532072f625.png)

Here are the commands I used: 

!yolo train model=yolov8n-seg.pt data=/content/data.yaml epochs=3 imgsz=640

!yolo export model="/content/runs/segment/train/weights/best.pt" format="edgetpu" task=segment

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MukilSundaravadivel YOLOv8 Segmentation export to EdgeTPU is working correctly as you can see from the Green CI badge above. If your environment is causing issues feel free to run Edge TPU export in of of our verified environments above.

<img width="1028" alt="Screenshot 2023-03-08 at 01 28 13" src="https://user-images.githubusercontent.com/26833433/223587541-ca3351c2-3777-4af1-8cde-008371c83139.png">

**Comment by MukilSundaravadivel** [comment]
> @MukilSundaravadivel YOLOv8 Segmentation export to EdgeTPU is working correctly as you can see from the Green CI badge above. If your environment is causing issues feel free to run Edge TPU export in of of our verified environments above.
> 
> <img alt="Screenshot 2023-03-08 at 01 28 13" width="1028" src="https://user-images.githubusercontent.com/26833433/223587541-ca3351c2-3777-4af1-8cde-008371c83139.png">

Thank you for responding. So for some clarification, what might be causing the compilation failure shown in the image? I can show more of the error if you would like me to, unless this is normal.

**Comment by rolouis** [comment]
@MukilSundaravadivel did you manage to export and run the model?

**Comment by glenn-jocher** [comment]
@rolouis Unfortunately, we did not receive any response from you. If you are still experiencing issues, please provide more information, including the specific steps to reproduce the problem, and error message output. If your problem is specific to your environment or setup, you could use one of our verified environments mentioned above to run exported EdgeTPU models.

**Comment by philippedegeer** [comment]
Hello.
I am trying to compile a yolov8s (or n) for an edgetpu equipped system using this :

!pip install ultralytics
from ultralytics import YOLO
model_name = 'yolov8s'
input_width = 416 
input_height = 416 
model = YOLO(f"{model_name}.pt")
model.export(format="edgetpu", imgsz=[input_height,input_width], int8=True)

The process runs fine, with the right file generated at the end by the edgetpu compiler :

Edge TPU: starting export with Edge TPU compiler 16.0.384591198...
Edge TPU: running 'edgetpu_compiler -s -d -k 10 --out_dir yolov8s_saved_model yolov8s_saved_model/yolov8s_full_integer_quant.tflite'
Edge TPU: export success ✅ 14.4s, saved as yolov8s_saved_model/yolov8s_full_integer_quant_edgetpu.tflite (11.3 MB)
Export complete (280.0s)

However when I load the file in frigate I get the following error : 

2023-06-17 09:41:38.836806216  [2023-06-17 09:41:38] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-06-17 09:41:42.414189579  Process detector:coral:
2023-06-17 09:41:42.417775259  Traceback (most recent call last):
2023-06-17 09:41:42.417857129    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-06-17 09:41:42.417861240      self.run()
2023-06-17 09:41:42.417932666    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-06-17 09:41:42.417940517      self._target(*self._args, **self._kwargs)
2023-06-17 09:41:42.418162294    File "/opt/frigate/frigate/object_detection.py", line 121, in run_detector
2023-06-17 09:41:42.418169053      detections = object_detector.detect_raw(input_frame)
2023-06-17 09:41:42.418172942    File "/opt/frigate/frigate/object_detection.py", line 71, in detect_raw
2023-06-17 09:41:42.418176460      return self.detect_api.detect_raw(tensor_input=tensor_input)
2023-06-17 09:41:42.418181349    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 55, in detect_raw
2023-06-17 09:41:42.418299811      self.interpreter.set_tensor(self.tensor_input_details[0]["index"], tensor_input)
2023-06-17 09:41:42.418307422    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 572, in set_tensor
2023-06-17 09:41:42.418310885      self._interpreter.SetTensor(tensor_index, value)
2023-06-17 09:41:42.418778993  ValueError: Cannot set tensor: Got value of type UINT8 but expected type INT8 for input 0, name: serving_default_images:0 

I get the same behavior on two different systems (one pI4 and one NUC), both equipped with an edgetpu.

Any idea of what I am doing wrong ?

Many thanks - Philippe

**Comment by pderrenger** [comment]
@philippedegeer hi Philippe,

The error message indicates a type mismatch between the expected tensor type (INT8) and the provided value type (UINT8). This inconsistency likely results from the inference graph generated during the Edge TPU compilation process.

To address this issue, I recommend revisiting the model export process and verifying that the input tensor data type is appropriately set to INT8 during the conversion to Edge TPU-compatible format. This may involve reviewing the specific conversion options available through the Edge TPU compiler to ensure the correct data type is specified.

If you have any further questions or encounter any difficulties during this process, please feel free to reach out for additional assistance.

**Comment by philippedegeer** [comment]
Thanks you Paula for your reply.
I had originally done the export via the Ultralytics Hub, without much view on the arguments passed during the export process.
I have then used the yolo command

**Comment by philippedegeer** [comment]
Thanks for you reply Paula.
I had originally used the Ultralytics Hub to perform the export, without much visibility on the arguments passed during the process.
I then used the command: yolo export model=yolov8s_srt_100eV2.pt format=edgetpu imgsz=320 int8=True 
but the command did abort with the message:
TypeError: Descriptors cannot not be created directly
I am not a developper and understanding these messages is beyond my capability.
I would be glad if you could provide some guidance on how to proceed.
Thanks - Philippe Degeer

**Comment by glenn-jocher** [comment]
Hi Philippe ( @philippedegeer),

It seems you're facing a type compatibility issue and perhaps a problem with invoking the export command correctly. The type mismatch error suggests there may have been a misconfiguration during the quantization or the export process.

For the `TypeError: Descriptors cannot be created directly`, this error is less common and could be related to multiple issues, possibly an internal bug or even an incompatible library version in your environment.

Without diving into the actual code or providing direct code instructions as per the guidelines, here's a high-level approach you can take:

1. Verify your environment: Make sure your software environment is up-to-date and compatible with the EdgeTPU export process. This includes having the correct versions of all necessary libraries and dependencies.

2. Revisit the export process: Go through the export process to the EdgeTPU format and ensure that the quantization settings (int8 quantization) are correctly applied.

If you’re not a developer, the above steps might be challenging. I would recommend reaching out to the community or a developer who can help you debug this further. The export functionality for EdgeTPU should handle the quantization, so these errors may be indicative of a deeper issue that requires someone with a development background to investigate.

Remember that the YOLO export function is designed to handle these processes, but it still requires a correctly set up environment, and sometimes things can go wrong that are environment-specific or related to edge cases that haven't been thoroughly explored yet.

If these steps don't help in resolving the issue, I’d suggest opening an issue on the YOLOv8 GitHub issues page, providing all the detailed information, and possibly the maintainers or other community members will be able to guide you more specifically. Make sure to explain your process as well as the environment where you're running the commands.

**Comment by glenn-jocher** [comment]
Hello Philippe ( @philippedegeer ),

I'm sorry to hear you're encountering issues with the export process in the Colab environment. The screenshot you referenced is not visible here, but I can provide some general pointers that might help you troubleshoot the problem.

Here are a few things you might want to check:

1. **Ensure Compatibility**: Verify that the YOLOv8 model you're using is compatible with Edge TPU export. There might be specific requirements or constraints for models that can be compiled for the Edge TPU.

2. **Check Colab Environment**: Ensure that the Colab runtime you're using has all the necessary packages and dependencies installed and properly configured for exporting the model.

3. **Examine Error Messages**: Review the output logs for any error messages. These messages can provide insight into what might be going wrong during the export process.

4. **Resource Constraints**: Colab provides limited resources, and sometimes, processes may fail if these resources are exhausted. Verify that you haven't run out of memory or disk space.

5. **Version Conflicts**: There could be version conflicts with the libraries and tools being used. Ensure that you're using the recommended versions of TensorFlow, the Edge TPU compiler, and other related tools.

6. **Edge TPU Compiler Options**: If you're using the command line to call the Edge TPU compiler directly, make sure the arguments passed to it correspond to the expected inputs and settings for your YOLOv8 model.

If the process still fails, I would suggest sharing a copy of the actual error messages you receive during the export. This way, the Ultralytics community or someone from their support team can provide more targeted assistance. 

If the problem persists, consider opening an issue on the YOLOv8 GitHub repository with detailed information about the steps you've taken, the commands used, and the error messages received. This will help the maintainers reproduce and troubleshoot your issue.

**Comment by philippedegeer** [comment]
Hello Glenn,
Thanks for your extensive responses. I have done, with my limited capabilities, the checks you suggest and keep receiving from the Colab Notebook the same error at the export stage of the process. 

The only thing I have changed in your Notebook is the export line, into:
!yolo export model=yolov8n.pt format=edgetpu imgsz=320 (with or without INT8=True at the end)

... and the error message reads:
TensorFlow SavedModel: export failure
98.3s: generic_type: cannot initialize type
"StatusCode": an object with that name is already defined

I originally wanted to get more speed for my project by leveraging unused hardware (2 Coral USB EdgeTPUs). Based on your comments, and the capabilities required to make it work,  I will go back to my proven setup (yolov8+Openvino+iGPU) and continue focusing on model improvement instead.

Thanks again for your valuable comments - Philippe

**Comment by glenn-jocher** [comment]
Hi Philippe ( @philippedegeer ),

Firstly, I appreciate your efforts and understand the complexities involved in navigating these technical processes. It's great to hear about your project and your intention to utilize Edge TPUs for improved speed.

The error message you're receiving indicates there might be an issue with the TensorFlow SavedModel conversion, which is a step before the Edge TPU compilation. The `generic_type: cannot initialize type "StatusCode"` suggests there could be an issue within the TensorFlow framework or a conflict with pre-existing definitions in the environment.

Since the Colab environment is managed and should typically work for standard operations like the one you're attempting, the error might also indicate a bug that the Ultralytics team needs to address.

I understand that you're considering focusing on your existing setup, which is entirely reasonable. However, should you or someone else with the necessary technical expertise wish to pursue the Edge TPU export further in the future, I'd recommend the following steps:

1. **Detailed Issue Report**: Create a detailed issue report on the [YOLOv8 GitHub issues](https://github.com/ultralytics/ultralytics/issues) page. Be sure to include the full error message, the steps you've taken, and any other relevant information. The development team or community may be able to offer more specific guidance.

2. **Ask for Community Support**: Engage with the Ultralytics community directly through discussion forums or GitHub Discussions. There might be community members who have encountered and overcome similar issues.

3. **Consider Ultralytics Support**: If your project is reaching a commercial scale, Ultralytics offers professional support options that may be worth exploring. They could provide more direct assistance with your export and deployment challenges.

It's commendable that you've pushed your project this far, and returning to a stable setup is essential for keeping progress moving forward. I do hope that sooner rather than later, a straightforward solution will emerge to enable the use of YOLOv8 models with Edge TPUs, granting you the speed boost you're aiming for.

I wish you the best with your project, and if you ever circle back to trying the Edge TPU export again, please know that the community is here to support you.

Thanks and

**Comment by Shu2023a** [comment]
Hello,

In my case, EdgeTPU is one environment.

#If I downgrade the TensorFlow version to 2.13.0, I can export in my environment.
In the notebook settings, I selected CPU.

import tensorflow as tf
print(tf.__version__)

-> 2.15.0

!pip uninstall tensorflow
!pip install tensorflow==2.13.0

Push RESTART SESSION

import tensorflow as tf
print(tf.__version__)

-> 2.13.0

!yolo export model=yolov8n.pt format=edgetpu imgsz=320
will end normally.

**Comment by glenn-jocher** [comment]
@Shu2023a hello,

It's great to hear you were able to successfully export the YOLOv8 model to the EdgeTPU format after downgrading TensorFlow to version 2.13.0 and conducting the process on a CPU environment. Sometimes, specific versions of TensorFlow are more compatible with certain operations or tools due to changes in the API or other underlying mechanisms between versions.

Thank you for sharing your solution with the community. This could be very helpful for others facing similar export challenges. If you encounter any further issues or have additional insights to share, please feel free to contribute. Your experiences enrich the collective knowledge and benefit all users working with YOLOv8 and EdgeTPUs.
