### ISSUE TITLE
Corrupt JPEG data: 1199 extraneous bytes before marker 0xd4

### ISSUE THREAD

**Issue by YEONCHEOL-HA** [ultralytics/ultralytics#13142]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

when i employ to train YOLOv8 classfication, i got follosing error message. 

"Corrupt JPEG data: 1199 extraneous bytes before marker 0xd4"
![image](https://github.com/ultralytics/ultralytics/assets/63231666/d6976f0e-4a26-498e-877d-7223f4b43116)

however, this dataset already fixed with following code. 

`def process_images_in_folder(folder_path):
    for img_name in os.listdir(folder_path):
        if img_name.lower().endswith(('.jpg', '.jpeg')):
            img_path = os.path.join(folder_path, img_name)
            if os.path.isfile(img_path):
                try:
                    with open(img_path, 'rb') as im:
                        im.seek(-2, 2)
                        if im.read() == b'\xff\xd9':
                            print('Image OK :', img_name)
                        else:
                            # fix image
                            img = cv2.imread(img_path)
                            if img is not None:
                                cv2.imwrite(img_path, img)
                                print('FIXED corrupted image :', img_name)
                            else:
                                print('Failed to read image :', img_name)
                except Exception as e:
                    print(f'Error processing image {img_name}: {e}')`
What causes these errors?

Do these errors affect your training?

**Comment by glenn-jocher** [comment]
Hi there,

The error message "Corrupt JPEG data: 1199 extraneous bytes before marker 0xd4" indicates that some of your JPEG files contain extraneous data before the JPEG marker. This can happen even if the images appear to be fixed or readable by some tools.

To address this, you might want to ensure that all images are properly processed and saved. Your current script is a good start, but you might want to add a step to re-encode the images to ensure they are fully compliant with the JPEG standard.

Here's an enhanced version of your script:

```python
import os
import cv2

def process_images_in_folder(folder_path):
    for img_name in os.listdir(folder_path):
        if img_name.lower().endswith(('.jpg', '.jpeg')):
            img_path = os.path.join(folder_path, img_name)
            if os.path.isfile(img_path):
                try:
                    with open(img_path, 'rb') as im:
                        im.seek(-2, 2)
                        if im.read() == b'\xff\xd9':
                            print('Image OK :', img_name)
                        else:
                            # fix image
                            img = cv2.imread(img_path)
                            if img is not None:
                                cv2.imwrite(img_path, img, [int(cv2.IMWRITE_JPEG_QUALITY), 100])
                                print('FIXED corrupted image :', img_name)
                            else:
                                print('Failed to read image :', img_name)
                except Exception as e:
                    print(f'Error processing image {img_name}: {e}')

# Example usage
process_images_in_folder('path/to/your/folder')
```

This script re-encodes the images with a high JPEG quality setting, which should help eliminate any extraneous data.

Regarding your questions:
1. **What causes these errors?**
   - These errors are caused by extraneous data in the JPEG files, which can occur due to improper saving or editing of the images.

2. **Do these errors affect your training?**
   - Yes, these errors can affect your training as they may prevent the images from being correctly read and processed by the training pipeline.

Feel free to try the updated script and let us know if the issue persists. Happy training! 🚀

**Comment by YEONCHEOL-HA** [comment]
Q1. Why does training proceed even though an error message is displayed?

Q2. Aren't files with that error excluded from learning?

**Comment by glenn-jocher** [comment]
@YEONCHEOL-HA hi there,

Great questions! Let's address them one by one:

1. **Why does training proceed even though an error message is displayed?**
   - Training can continue because the error message indicates a warning about corrupted JPEG data, but the image might still be partially readable. YOLOv8 tries to process as much data as possible, even if some images have minor issues.

2. **Aren't files with that error excluded from learning?**
   - Typically, files with minor corruption are not excluded unless they are completely unreadable. YOLOv8 attempts to use all available data to maximize training efficiency.

3. **What is the pg in YOLOv8?**
   - "pg" stands for "Programmable Gradient," a feature in YOLOv8 that allows for more flexible and efficient gradient computation during training.

If you have any more questions or need further assistance, feel free to ask! 😊
