### ISSUE TITLE
Illegal instruction: 4  with yolov8 pose task testing

### ISSUE THREAD

**Issue by yangboz** [ultralytics/ultralytics#13152]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Ultralytics YOLOv8.1.34 🚀 Python-3.10.13 torch-2.1.0 CPU (Apple M1 Pro)
engine/trainer: task=detect, mode=train, model=yolov10n.pt, data=coco8.yaml, epochs=100, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, val_period=1, cache=False, device=None, workers=8, project=None, name=train4, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=4poseDetect.jpg, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train4
Illegal instruction: 4
(py310) bogon:YOLOv10 yangboz$ yolo pose  model=yolov8n.pt source='4poseDetect.jpg'

### Environment

Ultralytics YOLOv8.1.34 🚀 Python-3.10.13 torch-2.1.0 CPU (Apple M1 Pro)
Setup complete ✅ (8 CPUs, 16.0 GB RAM, 786.8/1858.2 GB disk)

OS                  macOS-10.16-x86_64-i386-64bit
Environment         Darwin
Python              3.10.13
Install             git
RAM                 16.00 GB
CPU                 Apple M1 Pro
CUDA                None

matplotlib          ✅ 3.7.3>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.3>=1.4.1
torch               ✅ 2.1.0>=1.8.0
torchvision         ✅ 0.16.0>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 5.9.6
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0

### Minimal Reproducible Example

```
yolo pose  model=yolov10n.pt source='4poseDetect.jpg' 
```

### Additional

maybe only MacosxM1 related? thanks

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hi @yangboz,

Thank you for reaching out and providing detailed information about the issue. The "Illegal instruction: 4" error on macOS with M1 chips can sometimes be related to compatibility issues with certain libraries or hardware instructions.

Here are a few steps you can try to resolve this:

1. **Update Dependencies**: Ensure all your dependencies are up-to-date. You can do this by running:
   ```bash
   pip install --upgrade torch torchvision opencv-python
   ```

2. **Use MPS Device**: Since you're on an Apple M1 chip, you might want to try using the Metal Performance Shaders (MPS) backend for PyTorch. You can specify the device as 'mps' in your command:
   ```bash
   yolo pose model=yolov8n.pt source='4poseDetect.jpg' device=mps
   ```

3. **Check for Known Issues**: Sometimes, specific versions of libraries might have known issues. Checking the [PyTorch GitHub issues](https://github.com/pytorch/pytorch/issues) or the [Ultralytics YOLO issues](https://github.com/ultralytics/ultralytics/issues) might provide some insights.

If the issue persists, please let us know, and we can further investigate. Your willingness to submit a PR is greatly appreciated! 🙌

**Comment by yangboz** [comment]
> Hi @yangboz,
> 
> Thank you for reaching out and providing detailed information about the issue. The "Illegal instruction: 4" error on macOS with M1 chips can sometimes be related to compatibility issues with certain libraries or hardware instructions.
> 
> Here are a few steps you can try to resolve this:
> 
> 1. **Update Dependencies**: Ensure all your dependencies are up-to-date. You can do this by running:
>    ```shell
>    pip install --upgrade torch torchvision opencv-python
>    ```
> 2. **Use MPS Device**: Since you're on an Apple M1 chip, you might want to try using the Metal Performance Shaders (MPS) backend for PyTorch. You can specify the device as 'mps' in your command:
>    ```shell
>    yolo pose predict model=yolov8n.pt source='4poseDetect.jpg' device=mps
>    ```
> 3. **Check for Known Issues**: Sometimes, specific versions of libraries might have known issues. Checking the [PyTorch GitHub issues](https://github.com/pytorch/pytorch/issues) or the [Ultralytics YOLO issues](https://github.com/ultralytics/ultralytics/issues) might provide some insights.
> 
> If the issue persists, please let us know, and we can further investigate. Your willingness to submit a PR is greatly appreciated! 🙌

and  tried again, it throws as following :

```
NotImplementedError: The operator 'torchvision::nms' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.
```

**Comment by glenn-jocher** [comment]
Hi @yangboz,

Thank you for the update. It looks like the `torchvision::nms` operator is not yet supported on the MPS device. As suggested in the error message, you can set the environment variable to enable CPU fallback for this operation:

```shell
export PYTORCH_ENABLE_MPS_FALLBACK=1
yolo pose predict model=yolov8n.pt source='4poseDetect.jpg' device=mps
```

This will allow the operation to run on the CPU when it's not supported on MPS, albeit with a potential performance hit.

If you continue to experience issues, please let us know, and we can explore further solutions. Your proactive approach and willingness to contribute are much appreciated! 😊

**Comment by Burhan-Q** [comment]
Note Ultralytics v8.1.34 doesn't include YOLOv10 and our integration with the YOLOv10 model that was published is not yet released. The [docs page on the YOLOv10 model](https://docs.ultralytics.com/models/yolov10/#usage-examples) states this as well and you will need to update your install of `ultralytics` once the model is integrated.

**Comment by glenn-jocher** [comment]
Hi @yangboz,

Thank you for the clarification! It seems there was a misunderstanding regarding the model version. Since you are using `yolov8n.pt`, the suggestions provided earlier should be applicable. If you encounter any further issues or have additional questions, please feel free to reach out. We're here to help! 😊

**Comment by Burhan-Q** [comment]
@yangboz I was looking at your minimal reproducible example ![Screenshot_20240529-062414.png](https://github.com/ultralytics/ultralytics/assets/62214284/c312667e-20fd-4f0c-972f-a133f16d769e)

**Comment by Burhan-Q** [comment]
@yangboz I was looking at your minimal reproducible example ![Screenshot_20240529-062414.png](https://github.com/ultralytics/ultralytics/assets/62214284/c312667e-20fd-4f0c-972f-a133f16d769e)

**Comment by Burhan-Q** [comment]
Additionally, for the `pose` task, you will need to use the `pose` weights, `yolov8n-pose.pt` as otherwise you will have an object detection model when using `yolov8n.pt` weights.

**Comment by glenn-jocher** [comment]
Hi @yangboz,

Thanks for the update! Yes, using the correct model file `yolov8n-pose.pt` for pose estimation tasks is crucial. Regarding the MPS issue, setting `PYTORCH_ENABLE_MPS_FALLBACK=1` as you've done is a good temporary solution until the necessary operations are supported natively on MPS. This will ensure your tasks continue to run, albeit with a potential decrease in performance due to the fallback to CPU.

If you have any more questions or need further assistance, feel free to ask. Happy coding! 😊
