### ISSUE TITLE
values of Results disapears when move to cpu

### ISSUE THREAD

**Issue by ZeroAct** [ultralytics/ultralytics#1318]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

When I move the Results object to the CPU, numpy, or cuda, the values disappear. 
I have noticed that the _keys attribute, which is of generator type, becomes empty when these moving functions are called. 
It seems that the generator may have reached its end at some point.

I made some changes and I'd like to make a Pull Request of this issue.

Thank you.

### Environment

- YOLO: Ultralytics 8.0.50

### Minimal Reproducible Example

``` python
from ultralytics import YOLO

model = YOLO("yolov8n-cls.pt")
result = model.predict()[0]

print(result.probs)
# tensor(...)

print(result.cpu().probs)
# None

print(result.cpu().numpy().probs)
# None

print(result.cuda().probs)
# None

print(result.to("cpu").probs)
# None
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@ZeroAct hi there! It's great to see your interest in addressing this issue. When moving the Results object to the CPU, numpy, or CUDA, the values disappearing might be due to the attributes getting reset or the generator reaching its end, as you've noticed.

However, please note that the `result.probs` attribute should certainly yield tensor values, so the observed behavior seems unexpected. 🤔

As for your proposed Pull Request, we truly appreciate your willingness to contribute! Your insights would certainly be valuable in resolving this issue. Please feel free to proceed with your proposed changes. If you encounter any roadblocks or need further guidance during the process, don't hesitate to reach out for assistance.

Looking forward to your contribution!
