### ISSUE TITLE
yolov10 pytorch to OpenVINO Model Conversion Fails Due to Unsupported Operations and Inconsistent Argument Types

### ISSUE THREAD

**Issue by dsnsabari** [ultralytics/ultralytics#13185]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

Argument element types are inconsistent.

-- No conversion rule found for operations: aten::chunk, aten::split_with_sizes
-- Conversion is failed for: aten::cat, prim::ListConstruct, prim::ListUnpack

Traceback (most recent call last):
  File "/home/ubuntu/sabari/Yolo/yolo_model_conversion.py", line 14, in <module>
    model.export(format="openvino")
  File "/home/ubuntu/miniconda3/envs/new_pytorch/lib/python3.9/site-packages/ultralytics/engine/model.py", line 602, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/home/ubuntu/miniconda3/envs/new_pytorch/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/new_pytorch/lib/python3.9/site-packages/ultralytics/engine/exporter.py", line 305, in __call__
    f[3], _ = self.export_openvino()
  File "/home/ubuntu/miniconda3/envs/new_pytorch/lib/python3.9/site-packages/ultralytics/engine/exporter.py", line 143, in outer_func
    raise e
  File "/home/ubuntu/miniconda3/envs/new_pytorch/lib/python3.9/site-packages/ultralytics/engine/exporter.py", line 138, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/new_pytorch/lib/python3.9/site-packages/ultralytics/engine/exporter.py", line 452, in export_openvino
    ov_model = ov.convert_model(
  File "/home/ubuntu/miniconda3/envs/new_pytorch/lib/python3.9/site-packages/openvino/tools/ovc/convert.py", line 100, in convert_model
    ov_model, _ = _convert(cli_parser, params, True)
  File "/home/ubuntu/miniconda3/envs/new_pytorch/lib/python3.9/site-packages/openvino/tools/ovc/convert_impl.py", line 547, in _convert
    raise e
  File "/home/ubuntu/miniconda3/envs/new_pytorch/lib/python3.9/site-packages/openvino/tools/ovc/convert_impl.py", line 489, in _convert
    ov_model = driver(argv, {"conversion_parameters": non_default_params})
  File "/home/ubuntu/miniconda3/envs/new_pytorch/lib/python3.9/site-packages/openvino/tools/ovc/convert_impl.py", line 240, in driver
    ov_model = moc_emit_ir(prepare_ir(argv), argv)
  File "/home/ubuntu/miniconda3/envs/new_pytorch/lib/python3.9/site-packages/openvino/tools/ovc/convert_impl.py", line 189, in prepare_ir
    ov_model = moc_pipeline(argv, moc_front_end)
  File "/home/ubuntu/miniconda3/envs/new_pytorch/lib/python3.9/site-packages/openvino/tools/ovc/moc_frontend/pipeline.py", line 244, in moc_pipeline
    ov_model = moc_front_end.convert(input_model)
  File "/home/ubuntu/miniconda3/envs/new_pytorch/lib/python3.9/site-packages/openvino/frontend/frontend.py", line 18, in convert
    converted_model = super().convert(model)
openvino._pyopenvino.OpConversionFailure: Check 'is_conversion_successful' failed at src/frontends/pytorch/src/frontend.cpp:143:
FrontEnd API failed with OpConversionFailure:
Model wasn't fully converted. Failed operations detailed log:
-- aten::cat with a message:
Exception happened during conversion of operation __module.model.23/aten::cat with schema aten::cat(Tensor[] tensors, int dim=0) -> Tensor
Check 'element::Type::merge(inputs_et, inputs_et, get_input_element_type(i))' failed at src/core/src/op/concat.cpp:36:
While validating node 'opset1::Concat Concat_6575 (opset6::GatherElements __module.model.23/aten::gather/GatherElements[0]:f32[?,?,?], opset1::Unsqueeze __module.model.23/aten::unsqueeze/Unsqueeze[0]:f32[?,300,1], opset1::Unsqueeze __module.model.23/aten::unsqueeze/Unsqueeze[0]:i64[?,300,1]) -> (dynamic[...])' with friendly_name 'Concat_6575':
Argument element types are inconsistent.

-- prim::ListConstruct with a message:
Exception happened during conversion of operation __module.model.10.attn/prim::ListConstruct with schema (no schema)
Check '(c_node)' failed at src/frontends/pytorch/src/op/list_construct.cpp:25:
FrontEnd API failed with OpConversionFailure:
[PyTorch Frontend] Translation for prim::ListConstruct support only constant inputs

-- prim::ListUnpack with a message:
Exception happened during conversion of operation __module.model.2/prim::ListUnpack with schema (no schema)
Lists are not supported yet and can be resolved only in specific cases.
Summary:
-- normalize step failed with: Check 'element::Type::merge(inputs_et, inputs_et, get_input_element_type(i))' failed at src/core/src/op/concat.cpp:36:
While validating node 'opset1::Concat Concat_8483 (opset6::GatherElements __module.model.23/aten::gather/GatherElements[0]:f32[?,?,?], opset1::Unsqueeze __module.model.23/aten::unsqueeze/Unsqueeze[0]:f32[?,300,1], opset1::Unsqueeze __module.model.23/aten::unsqueeze/Unsqueeze[0]:i64[?,300,1]) -> (dynamic[...])' with friendly_name 'Concat_8483':
Argument element types are inconsistent.

-- No conversion rule found for operations: aten::chunk, aten::split_with_sizes
-- Conversion is failed for: aten::cat, prim::ListConstruct, prim::ListUnpack

### Environment

Ultralytics YOLOv8.2.22 🚀 Python-3.9.12 torch-2.0.1 CUDA:0 (Tesla V100-SXM2-16GB, 16161MiB)
Setup complete ✅ (8 CPUs, 59.9 GB RAM, 106.7/121.1 GB disk)

### Minimal Reproducible Example

from ultralytics import YOLOv10

# Load a model
model = YOLOv10("yolov10n.pt")  # load an official model
# Export the model
model.export(format="openvino")

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello,

Thank you for providing detailed information about the issue you're encountering during the OpenVINO export process. It seems that the conversion failures are due to certain PyTorch operations (`aten::chunk`, `aten::split_with_sizes`, `aten::cat`, `prim::ListConstruct`, and `prim::ListUnpack`) that are not directly supported by OpenVINO's model optimizer.

Here are a few suggestions that might help resolve the issue:

1. **Model Simplification**: Before exporting, simplify the model to remove or replace unsupported operations. This might involve modifying the model architecture slightly to ensure compatibility with OpenVINO.

2. **Custom Layers**: For operations that OpenVINO does not natively support, consider implementing custom layers in OpenVINO. This requires writing the corresponding C++ code and integrating it with the OpenVINO toolkit.

3. **Intermediate Conversion**: Sometimes, converting to an intermediate format like ONNX before going to OpenVINO can help, as ONNX might offer broader operation support or different handling that aligns better with OpenVINO's capabilities.

4. **Update Libraries**: Ensure that both PyTorch and OpenVINO are updated to their latest versions, as compatibility improvements are continuously being made.

5. **Consult OpenVINO Documentation**: Review the latest [OpenVINO documentation](https://docs.ultralytics.com/integrations/openvino/) for any updates or additional tips on handling specific PyTorch operations during conversion.

If these steps do not resolve the issue, please consider opening an issue on the OpenVINO GitHub repository with the details of the unsupported operations. The OpenVINO community might offer patches or workarounds.

Let us know how it goes, or if there's anything else we can assist you with!
