### ISSUE TITLE
NotImplementedError：警告⚠️“YOLO”模型还不支持“None”任务的“_new”模式。

### ISSUE THREAD

**Issue by zengqing1218** [ultralytics/ultralytics#13191]
### Discussed in https://github.com/orgs/ultralytics/discussions/13190

<div type='discussions-op-text'>

<sup>Originally posted by **zengqing1218** May 29, 2024</sup>
I tried to add a new module in "ultralytics" to improve "yolov8 world", but the above error occurred. How can I solve it</div>

**Comment by glenn-jocher** [comment]
@zengqing1218 hello **zengqing1218**,

It looks like you're encountering a `NotImplementedError` because the task or mode you're trying to use isn't currently supported in our YOLO implementation. To resolve this, please ensure that you specify a valid task and mode that are compatible with the YOLO model. You can refer to our documentation for a list of supported tasks and modes.

If you're adding a new module or feature, you might need to integrate it properly with the existing task and mode handlers. If you need further assistance, could you please provide more details about the module you're trying to add or the specific functionality you're working on? This will help us give you more targeted advice.

Thank you for contributing to the Ultralytics community! 🚀
