### ISSUE TITLE
How not to display output image ?

### ISSUE THREAD

**Issue by Ssangam1999** [ultralytics/ultralytics#13204]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I tried not to display output to screen. Only display top 3 images with confidence but neither show= False works nor visualize  = False works. 

import os
import cv2
import shutil
from ultralytics import YOLO
from ultralytics.utils.plotting import Annotator, colors

# Load the YOLO model
model = YOLO("/bes.pt")
names = model.names

# Read the image
im0 = cv2.imread('/Blight02.jpg')

# Create a directory for cropped images if it doesn't exist
crop_dir_name = "img_crop"
if not os.path.exists(crop_dir_name):
    os.mkdir(crop_dir_name)

# Perform prediction
results = model.predict(im0,save=False)
boxes = results[0].boxes.xyxy.cpu().tolist()
clss = results[0].boxes.cls.cpu().tolist()
confidences = results[0].boxes.conf.cpu().tolist()

# Combine boxes, classes, and confidences into a single list of tuples
combined = list(zip(boxes, confidences))

# Sort the combined list by confidence scores in descending order
combined.sort(key=lambda x: x[1], reverse=True)

# Select the top 3 entries with the highest confidence scores
top_3 = combined[:3]
print(top_3)

#This displays image as well. I dont want that

**Comment by glenn-jocher** [comment]
Hello,

To prevent displaying the output image when using the `predict()` method, you can modify the `show()` method call that is likely being triggered automatically. In the current setup of the Ultralytics YOLO library, the `show()` method is used to display images, and it's usually called after plotting the results.

Since you're already using the `save=False` parameter which should prevent saving the output, make sure that no `show()` or `plot()` method is called implicitly in your script after the prediction. If you're using a custom function or a loop that might be invoking `show()`, you'll need to remove or comment out these calls.

If the issue persists, please ensure that your library version is up-to-date as older versions might behave differently. If you're still facing issues, providing the exact version of the library you're using could help in diagnosing the problem more effectively.

**Comment by Ssangam1999** [comment]
I am using ultralytics==8.2.26
Even though I aint calling show. The output is still displayed
from ultralytics import YOLO

# Load a model
model = YOLO("/home/vertex/Documents/vertex_projects/ultralytics/ultralytics/models/yolo/detect/yolov8n.pt")  # pretrained YOLOv8n model

# Run batched inference on a list of images
results = model(['/home/vertex/Documents/vertex_projects/ultralytics/examples/temp/Screenshot from 2023-12-21 16-09-08.png'])  # return a list of Results objects

# Process results list
for result in results:
    boxes = result.boxes  # Boxes object for bounding box outputs
    masks = result.masks  # Masks object for segmentation masks outputs
    keypoints = result.keypoints  # Keypoints object for pose outputs
    probs = result.probs  # Probs object for classification outputs
    obb = result.obb  # Oriented boxes object for OBB outputs

**Comment by glenn-jocher** [comment]
Hello,

Thank you for sharing the details of your implementation. It seems unusual for the output to be displayed if you're not explicitly calling the `show()` method. One possibility could be that there's an internal call or a default setting in the version of the library you are using that automatically displays the image.

As a workaround, you can explicitly set `show=False` in any method that might be displaying the image. If this option is not available or does not resolve the issue, I recommend checking the documentation for any default behaviors or updates in the newer versions that might have introduced this change.

If the problem persists, it might be helpful to raise an issue on the GitHub repository to see if the developers or other users have encountered and resolved a similar issue.

**Comment by Ssangam1999** [comment]
Thank you so much . Issue is solved by now. The reason why output was showing even though show function wasn't called  because the code was inside the main yolov8 directory(that I cloned from ultralytics github). When I created another directory in separate folder outside main yolov8 directory . It worked .

**Comment by glenn-jocher** [comment]
@Ssangam1999 hello,

Great to hear that the issue is resolved, and thank you for sharing the solution! It's interesting to note how the project's directory structure influenced the behavior. Your experience might help others facing similar issues. If you have any more questions or run into further issues, feel free to reach out. Happy coding! 🚀
