### ISSUE TITLE
FastSAMPrompt.text_prompt produces exception with PIL.Image

### ISSUE THREAD

**Issue by abrichr** [ultralytics/ultralytics#13218]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

```
def fetch_segmented_image(
    image: Image,
    model_name: str = MODEL_NAME,
    # TODO: inject from config
    device: str = "cpu",
    retina_masks: bool = True,
    imgsz: int = 1024,
    conf: float = 0.5,
    iou: float = 0.5,
) -> Image:
    """Segment a PIL.Image using ultralytics Fast Segment Anything.

    Args:
        image: The input image to be segmented.
        model_name: The name of the model to use. Must be FastSAM-s.pt or FastSAM-x.pt.
        TODO: document remaining params

    Returns:
        The segmented image as a PIL Image.
    """
    model = FastSAM(model_name)

    # Run inference on image
    everything_results = model(
        image,
        device=device,
        retina_masks=retina_masks,
        imgsz=imgsz,
        conf=conf,
        iou=iou,
    )

    # Prepare a Prompt Process object
    prompt_process = FastSAMPrompt(image, everything_results, device="cpu")

    # Text prompt
    annotations = prompt_process.text_prompt(
        text='clickable graphical user interface elements'
    )
```
Produces:
```
  File "/Users/abrichr/oa/OpenAdapt/openadapt/adapters/ultralytics.py", line 87, in fetch_segmented_image
    annotations = prompt_process.text_prompt(
  File "/Users/abrichr/Library/Caches/pypoetry/virtualenvs/openadapt-VBXg4jpm-py3.10/lib/python3.10/site-packages/ultralytics/models/fastsam/prompt.py", line 348, in text_prompt
    cropped_boxes, cropped_images, not_crop, filter_id, annotations = self._crop_image(format_results)
  File "/Users/abrichr/Library/Caches/pypoetry/virtualenvs/openadapt-VBXg4jpm-py3.10/lib/python3.10/site-packages/ultralytics/models/fastsam/prompt.py", line 264, in _crop_image
    if os.path.isdir(self.source):
  File "/usr/local/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not Image
```

### Environment

```
Ultralytics YOLOv8.1.47 🚀 Python-3.10.14 torch-2.0.1 CPU (Apple M2 Max)
Setup complete ✅ (12 CPUs, 96.0 GB RAM, 1844.6/1858.2 GB disk)
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@abrichr hello! Thank you for the detailed report and your willingness to contribute a PR. It seems the issue arises because `self.source` is expected to be a path, but a PIL Image object is being passed instead. As a quick fix, you might consider modifying the `_crop_image` method to handle cases where `self.source` is an image object directly, or adjust the input to ensure a file path is passed.

If you're planning to submit a PR, it would be great to include a check within `_crop_image` to determine the type of `self.source` and handle it accordingly. This could prevent similar issues in the future and make the function more robust.

Looking forward to your contribution! If you need further assistance or have more questions, feel free to ask. 🚀

**Comment by abrichr** [comment]
This bug appears to exist in `fastsam/prompt.py::point_prompt` as well:

```
  File "/Users/abrichr/oa/OpenAdapt/openadapt/adapters/ultralytics.py", line 242, in do_fastsam
    annotations = prompt_process.point_prompt(points=[[200, 200]], pointlabel=[1])
  File "/Users/abrichr/Library/Caches/pypoetry/virtualenvs/openadapt-VBXg4jpm-py3.10/lib/python3.10/site-packages/ultralytics/models/fastsam/prompt.py", line 324, in point_prompt
    if os.path.isdir(self.source):
  File "/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not Image
```

**Comment by glenn-jocher** [comment]
Hello @abrichr,

Thank you for pointing out this additional occurrence in `point_prompt`. It seems the issue is consistent with the handling of `self.source` across different methods. We appreciate your diligence in identifying these bugs.

We'll address this in the upcoming patch to ensure `self.source` is managed correctly across all relevant methods. If you have any further insights or suggestions, please feel free to share them. Your contributions are invaluable to improving the robustness of our library! 🛠️

**Comment by abrichr** [comment]
@glenn-jocher can you please comment on the status of the fix?

**Comment by glenn-jocher** [comment]
Thank you for your patience. The team is actively working on addressing the issue. In the meantime, please ensure you are using the latest version of the package, as updates may contain relevant fixes. If the problem persists, feel free to provide any additional details that might help us expedite the resolution.
