### ISSUE TITLE
evaluation VS benchmark

### ISSUE THREAD

**Issue by mmr689** [ultralytics/ultralytics#13244]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have trained a v8 model and now I want to validate it. If I'm not mistaken, you have two modes for doing this.

The obvious one, is `val` and the other is `benchmark` (this is very interesting because I need to run the model in different formats like TFLite or EdgeTPU).

My question is, I have validated my own model with `.val()` and the metrics are:

```
Ultralytics YOLOv8.1.47 🚀 Python-3.8.10 torch-2.3.0+cu121 CUDA:0 (NVIDIA RTX A6000, 48677MiB)
YOLOv8n summary (fused): 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs
val: Scanning /home/qcienmed/mmr689/yolo-consumptions/datasets/bioview-lizards_TRAIN/dataset/validation/labels.cache... 145 images, 0 backgrounds, 0 corrupt: 100%|██████████| 145/145 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 10/10 [00:05<00:00,  1.68it/s]
                   all        145        146          1          1      0.995      0.995
Speed: 1.5ms preprocess, 3.1ms inference, 0.0ms loss, 9.3ms postprocess per image
Saving datasets/bioview-lizards_TRAIN/run/validation4/predictions.json...
Results saved to datasets/bioview-lizards_TRAIN/run/validation4
```

But when I `benchmark` the same model, with the same validation data, the  mAP is very different.

```
Setup complete ✅ (48 CPUs, 251.4 GB RAM, 1601.6/1758.3 GB disk)

Benchmarks complete for best.pt on datasets/bioview-lizards_TRAIN/config.yaml at imgsz=160 (351.75s)
                   Format Status❔  Size (MB)  metrics/mAP50-95(B)  Inference time (ms/im)
0                 PyTorch       ✅        6.1               0.0364                    6.10
1             TorchScript       ✅       11.8               0.0379                    3.59
2                    ONNX       ✅       11.5               0.0379                    6.70
3                OpenVINO       ❌        0.0                  NaN                     NaN
4                TensorRT       ❎       12.9                  NaN                     NaN
5                  CoreML       ❌        0.0                  NaN                     NaN
6   TensorFlow SavedModel       ✅       38.2               0.0379                   44.41
7     TensorFlow GraphDef       ❌        0.0                  NaN                     NaN
8         TensorFlow Lite       ❌        0.0                  NaN                     NaN
9     TensorFlow Edge TPU       ❌        0.0                  NaN                     NaN
10          TensorFlow.js       ❌        0.0                  NaN                     NaN
11           PaddlePaddle       ✅       23.2               0.0379                   24.31
12                   NCNN       ✅       11.5               0.0379                    7.16
```

Why is this happening? What is the `(B)` in the `mAP50-95` metric? Bytes? Shouldn't it be a percentage?

Extra: Can I define which formats I need to benchmark? Or is it mandatory to benchmark them all?

**Comment by glenn-jocher** [comment]
Hello! Great questions, and I'm glad to see you're diving deep into the capabilities of YOLOv8.

The difference in mAP between `.val()` and `.benchmark()` can occur due to several reasons. Primarily, the `.benchmark()` mode not only validates the model but also converts it into various formats (like ONNX, TensorRT, etc.), which might introduce slight variations in precision or computational differences, especially if quantization or other optimizations are applied.

The `(B)` in the `mAP50-95(B)` metric stands for "Benchmark" and not bytes. It indicates that this mAP value is derived from the benchmarking process, which, as mentioned, can differ from the standard validation due to the transformations and optimizations applied to the model.

Regarding your question about defining specific formats for benchmarking: yes, you can specify which formats to benchmark. You don't have to run them all. You can control this by adjusting the `format` argument in the benchmark function or CLI command to include only the formats you're interested in.

If you need further clarification or have more questions, feel free to ask. Happy benchmarking! 🚀

**Comment by mmr689** [comment]
Mmm, but the Pytorch row would have the same value as the validation, wouldn't it? I mean, there is no conversion, so it is just a validation.

---

> Regarding your question about defining specific formats for benchmarking: yes, you can specify which formats to benchmark. You don't have to run them all. You can control this by adjusting the format argument in the benchmark function or CLI command to include only the formats you're interested in.

If I,

```
benchmark_df = benchmark(model="run/train/weights/best.pt",
          data="config.yaml",
          format='edgetpu',
          half=False,
          int8=True,
          device=device)
```

the error is `TypeError: benchmark() got an unexpected keyword argument 'format'`. This error is consistent with your [documentation](https://docs.ultralytics.com/modes/benchmark/#arguments), as this parameter doesn't appear in the arguments table. So how can I define it?

Thanks for all!!!

**Comment by glenn-jocher** [comment]
Hello! Thanks for your insightful observations.

Regarding the PyTorch row in the benchmark results, you're correct that it should ideally match the validation results since there's no conversion involved. However, the benchmarking process might still involve slight variations due to the specific setup or additional overhead from the benchmarking code itself.

As for specifying formats in the `benchmark()` function, it appears there was a misunderstanding in my previous message. Currently, the benchmarking function does not support the `format` argument directly. My apologies for the confusion. To benchmark specific formats, you would typically need to export the model to each format first and then run the benchmark separately on each exported model. This process is more manual but allows for specific control over which formats are tested.

Thank you for pointing out these discrepancies, and I appreciate your patience as we strive to provide accurate information. If you have any more questions or need further assistance, feel free to ask!
