### ISSUE TITLE
About TensorRT speed test

### ISSUE THREAD

**Issue by BarryGUN** [ultralytics/ultralytics#13299]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have some question about your inference latency with TensorRT accelerate. Did you export your model to engine and test on c++ code? The latency including nms or not ?

**Comment by glenn-jocher** [comment]
@BarryGUN hello!

Thank you for reaching out with your questions about TensorRT acceleration with YOLOv8.

Yes, we export the model to the TensorRT `.engine` format for testing. These tests are typically conducted using Python, but the results should be comparable when using C++ as both utilize the TensorRT runtime.

Regarding latency, the reported inference times include all processing steps, including Non-Maximum Suppression (NMS), unless explicitly stated otherwise. This ensures that the latency figures we provide reflect the total time required to process input and produce final detections.

If you have any more specific scenarios or configurations in mind, feel free to share, and I'll be happy to provide more detailed insights!

**Comment by BarryGUN** [comment]
Thank you for answer my question, i got it.

**Comment by glenn-jocher** [comment]
@BarryGUN You're welcome! If you have any more questions or need further assistance in the future, feel free to reach out. Happy coding! 😊

**Comment by BarryGUN** [comment]
I also want to know that in speed test, whether batch-size=32 depends on the image count of the coco2017 test datasets because 32 is divisible by 20288.

**Comment by BarryGUN** [comment]
I got it ，thank you！

**Comment by glenn-jocher** [comment]
@BarryGUN You're welcome! If you have any more questions in the future, don't hesitate to ask. Happy coding! 😊
