### ISSUE TITLE
Output shape of [1,5,2100]

### ISSUE THREAD

**Issue by Bello-dev** [ultralytics/ultralytics#13300]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i have this output when exporting my model to onnx
PyTorch: starting from 'best.pt' with input shape (1, 3, 320, 320) BCHW and output shape(s) (1, 5, 2100)
but its not like the standard of 8400 of yolov8 is this something i made wrong cus before i used to train models with only one class and get the [1,5,8400]

**Comment by glenn-jocher** [comment]
Hello,

The output shape `[1, 5, 2100]` you're observing after exporting your model to ONNX seems to be related to the number of anchors and the grid size used during the training of your model. The standard output shape `[1, 5, 8400]` typically corresponds to a different configuration, possibly with more or larger grid sizes.

If you've previously trained models with only one class and are now working with a different setup or a different number of classes, this might affect the output shape due to changes in the configuration settings such as anchor boxes, grid sizes, or the number of classes.

Please ensure that your model configuration during training matches your expectations and intended use case. You might want to review the configuration file used for training (`*.yaml`) to verify that all parameters are set correctly according to your current needs.

If everything seems correct and you're still facing issues, please provide more details about your training configuration and we can look deeper into it.

**Comment by Bello-dev** [comment]
i didn't change any config i just run the command as always 
`yolo detect train data=data.yaml model=yolov8n.pt epochs=100 imgsz=320 device=0 batch=64`

using the data.yaml
```
train: ../train/images
val: ../valid/images
test: ../test/images

nc: 1
names: ['boat']
```

**Comment by glenn-jocher** [comment]
@Bello-dev hello,

Thank you for providing the details of your training command and configuration. From what you've shared, it seems like your setup is consistent with training a model for a single class ('boat').

The output shape `[1, 5, 2100]` you're seeing is likely due to the specific grid sizes and anchor configurations used by the YOLOv8n model for the image size of 320x320. This configuration can result in different numbers of output predictions, which seems to be the case here.

If you haven't modified any other settings like the anchor boxes or the model architecture itself, the output shape you're observing is expected based on the internal calculations of the model for the given input size and the number of classes.

If you have further questions or need more assistance, feel free to ask. Happy to help! 😊
