### ISSUE TITLE
Auto annotation for specific labels

### ISSUE THREAD

**Issue by toni-santos** [ultralytics/ultralytics#13308]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hey there, I'm working with a single class dataset that only has bounding box annotations, which I've used up to this point to run object detection using YOLOv8, with great results! However I'd like to generate some segmentation annotations for it, for that effect I'm using [`auto_annotate`](https://docs.ultralytics.com/reference/data/annotator/#ultralytics.data.annotator.auto_annotate), but when running it I'm getting annotations for classes that are not present in my dataset, such as "car" or "table". Am I getting the wrong impression of how `auto_annotate` is supposed to work or is there any way to make it so that I only get detections/segmentations for my specific class?

**Comment by glenn-jocher** [comment]
Hello!

Thanks for reaching out with your question. The `auto_annotate` function indeed utilizes pre-trained models which are capable of detecting and segmenting multiple classes. If you're seeing unwanted classes like "car" or "table," it's because the pre-trained model includes these classes by default.

To generate segmentations only for your specific class, you would need to modify the detection model to detect only your class of interest before running `auto_annotate`. This involves re-training the detection model on your dataset with only the relevant class. Once you have a model trained specifically for your class, you can then use `auto_annotate` with this model to generate the desired segmentation annotations.

If you need further guidance on re-training your model or any other questions, feel free to ask. Happy to help!

**Comment by toni-santos** [comment]
That's it! :) Thank you very much!

**Comment by glenn-jocher** [comment]
You're welcome! 😊 If you have any more questions in the future, feel free to reach out. Happy coding!
