### ISSUE TITLE
How to Convert YOLOv10 Model to TFLite with INT8 Quantization?

### ISSUE THREAD

**Issue by AhmedFkih** [ultralytics/ultralytics#13314]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi everyone,

I’m working on a project that involves deploying a YOLOv10 model on a mobile/edge device. To improve inference speed and reduce the model size, I want to convert my YOLOv10 model to TensorFlow Lite (TFLite) with INT8 quantization.

-What is the best approach to convert the YOLOv10 model to TFLite with INT8 quantization?
-Are there any specific calibration techniques required for YOLOv10 during quantization?
-Can someone provide a code example or point me to resources for performing INT8 quantization on YOLOv10?

**Comment by glenn-jocher** [comment]
@AhmedFkih hello,

To convert a YOLOv10 model to TensorFlow Lite (TFLite) with INT8 quantization, you'll generally follow these steps:

1. **Export YOLOv10 to ONNX or SavedModel**: First, export your model to a compatible format like ONNX or TensorFlow's SavedModel.

2. **Convert to TensorFlow Lite**: Use TensorFlow's TFLite Converter to convert the model from ONNX/SavedModel to TFLite. During this step, you can specify the INT8 quantization.

3. **Calibration**: For INT8 quantization, you'll need to perform calibration using a representative dataset. This helps in accurately mapping the floating-point values to INT8.

Here’s a basic example using TensorFlow's TFLite Converter:

```python
import tensorflow as tf

# Load the SavedModel
model = tf.saved_model.load('path_to_saved_model')

# Set up the converter with INT8 quantization
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8  # or tf.uint8
converter.inference_output_type = tf.int8  # or tf.uint8

# Convert the model
tflite_model = converter.convert()

# Save the TFLite model
with open('model.tflite', 'wb') as f:
    f.write(tflite_model)
```

For the `representative_data_gen`, you need to provide a function that yields batches of input data from your dataset. This data is used to calibrate the quantization parameters.

For more detailed guidance and advanced configurations, please refer to the TensorFlow Lite documentation on model optimization and quantization.

Best of luck with your deployment!

— The Ultralytics Team

**Comment by rjacaac** [comment]
I'm encountering an issue while trying to convert the YOLOv10n model to TensorFlow Lite with INT8 quantization. Below is the code I used:

model = YOLO('yolov10n.pt')
model.export(format="tflite", int8=True)

However, the conversion fails, and I receive the following errors [snippets]:
RuntimeError: Quantized dimension for tensor property and quantization parameters do not match. Got 3 and 0 respectively.
...
WARNING: INT8 Quantization with int16 activations tflite output failed.
...
RuntimeError: Quantized dimension for tensor property and quantization parameters do not match. Got 3 and 0 respectively.
...
WARNING: Full INT8 Quantization with int16 activations tflite output failed.


It seems that the issue is related to a mismatch in the quantized dimensions. Has anyone else experienced this, or does anyone have suggestions on how to fix it?

Thanks in advance for any assistance!

**Comment by glenn-jocher** [comment]
@rjacaac thank you for reporting this issue. Please ensure you are using the latest version of the Ultralytics package. If the problem persists, consider using a representative dataset for calibration during the INT8 quantization process. For further details, refer to the TensorFlow Lite documentation on model optimization and quantization.
