### ISSUE TITLE
zh

### ISSUE THREAD

**Issue by wanghongfei833** [ultralytics/ultralytics#13343]
### Discussed in https://github.com/orgs/ultralytics/discussions/8026

<div type='discussions-op-text'>

<sup>Originally posted by **giscus[bot]** February  5, 2024</sup>
# zh

我使用
yolo export model=runs/detect/train/weights/best.pt  format=onnx device=0 half=True opset=12
导出onnx后，在c++利用OPENCV进行推理时 ，CPU可以正常预测出 cx cy w h conf 信息，但是在GPU推理时，cx cy w h 都是0，conf 的值时正常的，是什么原因呢，显卡为RTX3070

https://docs.ultralytics.com/zh

</div>

**Comment by glenn-jocher** [comment]
@wanghongfei833 hello! It seems like you're encountering an issue where bounding box coordinates (cx, cy, w, h) are not being correctly predicted when using GPU inference with an ONNX model exported from YOLOv8, while confidence scores remain normal.

This issue might be related to how the ONNX model handles computations on the GPU. Here are a few things you could check:

1. **ONNX Version Compatibility:** Ensure that the ONNX runtime and the version used for exporting the model are compatible with your GPU.
2. **Model Conversion:** Verify that during the conversion to ONNX with `half=True`, all layers and operations are correctly translated and supported on the GPU. Sometimes, reduced precision can lead to unexpected behaviors in certain operations.
3. **GPU Drivers and CUDA Version:** Make sure that your GPU drivers and CUDA toolkit are up to date and compatible with the ONNX runtime you are using.

If the issue persists, consider re-exporting the model with different settings or testing with `half=False` to see if the issue is related to the use of FP16 precision.

Feel free to share more details or error logs if the problem continues, and we can look deeper into it.

**Comment by wanghongfei833** [comment]
您好 我看了一下yolov5的export，其中186行出现了这样一个注释：# WARNING: DNN inference with torch>=1.12 may require do_constant_folding=False，我无法推理的原因是否是这个呢

以下是源码：
torch.onnx.export(
        model.cpu() if dynamic else model,  # --dynamic only compatible with cpu
        im.cpu() if dynamic else im,
        f,
        verbose=False,
        opset_version=opset,
        do_constant_folding=True,  # WARNING: DNN inference with torch>=1.12 may require do_constant_folding=False
        input_names=["images"],
        output_names=output_names,
        dynamic_axes=dynamic or None,
    )

**Comment by glenn-jocher** [comment]
@wanghongfei833 您好！👋 是的，您提到的这个警告可能是导致推理问题的原因之一。在 PyTorch 1.12 及以上版本中，使用 ONNX 导出时设置 `do_constant_folding=False` 可能会解决一些与 DNN 推理相关的问题。您可以尝试修改这个参数看看是否能解决您的问题。如果问题仍然存在，请随时回复，我们会进一步帮助您解决。谢谢！
