### ISSUE TITLE
Wandb gives wrong label for x-axis

### ISSUE THREAD

**Issue by ZeeRizvee** [ultralytics/ultralytics#13397]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

This is probably a bug. In the wandb plots, I noticed the graphs mention 'Steps' on the x-axis, when it should actually be 'Epochs'. The drop down menu for x-axis also does not give an option to change to 'Epochs'. There is a workaround though. The axis can be manually changed by going to 'Charts' and then manually writing 'Epochs' for the x-axis. But it is strange that this is not the default behaviour during graph plotting.

### Environment

Ultralytics YOLOv8.2.28 🚀 Python-3.8.19 torch-2.3.0+cu121 CUDA:0 (NVIDIA RTX 2000 Ada Generation Laptop GPU, 7940MiB)
Setup complete ✅ (28 CPUs, 31.0 GB RAM, 411.5/930.1 GB disk)

OS                  Linux-6.5.0-1023-oem-x86_64-with-glibc2.17
Environment         Linux
Python              3.8.19
Install             pip
RAM                 31.02 GB
CPU                 13th Gen Intel Core(TM) i7-13850HX
CUDA                12.1

matplotlib          ✅ 3.7.5>=3.3.0
opencv-python       ✅ 4.10.0.82>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.3.0>=1.8.0
torchvision         ✅ 0.18.0>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 0.2.7>=0.2.5

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Thank you for reporting this issue with the wandb plots in YOLOv8. It seems like the default setting for the x-axis label should indeed be 'Epochs' rather than 'Steps'. Your workaround is a good temporary solution, and we appreciate you sharing it.

We'll look into why 'Epochs' is not set as the default and aim to address this in an upcoming release. If you have any more insights or further details that could help us pinpoint the issue faster, please feel free to share. Your contributions to improving YOLOv8 are greatly valued! 🌟
