### ISSUE TITLE
How to get image_buffer inference name of result

### ISSUE THREAD

**Issue by yangtao-git** [ultralytics/ultralytics#13400]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

import os
import cv2
import base64

# Load a model
model = YOLO("/yangtao/programs/ultralytics-main/ultralytics-main/runs/detect/mg_yolov8m_116/weights/best.pt")  # pretrained YOLOv8n model
root_dir = '/yangtao/programs/ultralytics-main/ultralytics-main/test_files/images/'
save_folder = '/yangtao/programs/ultralytics-main/ultralytics-main/test_files/results/'
files = os.listdir(root_dir)
for file in files:
    # Run batched inference on a list of images
    file_path = root_dir + file
    image = cv2.imread(file_path)
    save_path = save_folder + file
    img_buffer = cv2.imencode(".jpg", image)[1]
    img_buffer = base64.b64encode(img_buffer)
    results = model(img_buffer)
    print('resluts ',results)
    print("//////////////////////////////////////////////////////////////////////////")
    # Process results list
    for result in results:
        print('reslut ',result)
        result.save(filename=save_path)  # save to disk

Multi-target detection task, I want to get the box and name of the model inference result by inputting the image buffer, how to modify the code, input is file -- path can get the name, but change to bufer can not get the name

**Comment by glenn-jocher** [comment]
Hello,

To handle image buffers directly with the YOLO model and retrieve the detection boxes and names, you can modify your approach slightly. Instead of encoding the image to a base64 string, you should pass the numpy array directly to the model after decoding it from the buffer. Here's how you can adjust your code:

```python
import os
import cv2
import numpy as np

# Load a model
model = YOLO("/path/to/your/model.pt")  # Adjust the path to your model

root_dir = '/path/to/images/'
save_folder = '/path/to/results/'
files = os.listdir(root_dir)

for file in files:
    file_path = os.path.join(root_dir, file)
    image = cv2.imread(file_path)
    _, img_buffer = cv2.imencode(".jpg", image)
    img_array = cv2.imdecode(img_buffer, cv2.IMREAD_COLOR)  # Decode buffer to array

    results = model(img_array)  # Pass numpy array directly
    print('Results:', results)

    # Process results list
    for result in results:
        print('Result:', result)
        save_path = os.path.join(save_folder, file)
        result.save(filename=save_path)  # Save to disk
```

This modification ensures that the image buffer is correctly converted back to a numpy array, which can then be processed by the YOLO model. The `results` object will contain all the detection details, including the bounding boxes and class names.

If you have further questions or need more assistance, feel free to ask!
