### ISSUE TITLE
quadrilateral(polygon/convex) object detection

### ISSUE THREAD

**Issue by yellowjs0304** [ultralytics/ultralytics#1342]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is there any way to get Polygon shape (instead of rect form) in Yolov8? 
Before: (x1, y1, x3, y3) / Wanted : (x1, y1, x2, y2, x3, y3, x4, y4)
I wanted to detect a quadrilateral bboxes or something convex items. 
I already know the Obb task related with YOLOv5 but, a few cases in my dataset is not only rotated but also, distorted.

i already tried segmentation task in YOLOv8, but segmentation accuracy is really low. So I can't get the contour of that segmentation mask.

Also, found related another [repo](https://github.com/XinzeLee/PolygonObjectDetection/) related with YOLOv5, but it looks like code from a very old version of Yolov5.

Which Part should i modify for the polygon shape in YOLOv8?
If you have any ideas, please help.. :)

**Comment by glenn-jocher** [comment]
@yellowjs0304 Modifying YOLOv8 to output polygon shapes instead of rectangular bounding boxes is possible, but it would require significant modifications to the codebase. You would need to modify the loss function, the network architecture, and the post-processing code to handle polygons instead of rectangles.

One potential approach would be to use a variant of the YOLOv8 architecture that outputs corner points instead of rectangles. This could be done by adding additional output channels to the final convolutional layer, with each channel corresponding to a different corner point. You would also need to modify the post-processing code to assemble the corner points into a polygon shape.

Another approach would be to use a separate algorithm to convert the rectangular bounding boxes output by YOLOv8 into polygon shapes. One popular algorithm for this is the Minimum Weighted Polygon algorithm, which constructs the minimum polygon that encloses the points in the bounding box.

However, it's worth noting that detecting polygon shapes can be a challenging task, especially when dealing with distorted or rotated objects. You may need to use additional techniques such as data augmentation or specialized loss functions to improve the accuracy of the model.

Overall, modifying YOLOv8 to output polygon shapes would require significant modifications to the codebase, and it may be worth considering alternative approaches such as using a separate algorithm to convert rectangular bounding boxes into polygons.

**Comment by yellowjs0304** [comment]
Thank you for your advice. :)

**Comment by glenn-jocher** [comment]
@yellowjs0304 also see OBB PR #1958
