### ISSUE TITLE
show_labels=False, show_conf=False parameters won't work (ultralytics==8.2.25)

### ISSUE THREAD

**Issue by paulohss** [ultralytics/ultralytics#13422]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

Hello!

Im using YOLO (v8.2.25) and when I run the code below it won't work:

```
model = YOLO(model_path)
results = model.predict(self.image_path, show_labels=False, show_conf=False)
result[0].save(filename=path_jpg_image)
```
The predictions are working OK, however even though I've set show_labels and show_conf are set to FALSE, the resulting image has the labels and confidence level.

Any suggestion to fix this?

Thanks

### Environment

Ultralytics YOLOv8.2.25 🚀 Python-3.11.9 torch-2.3.0+cpu CPU (11th Gen Intel Core(TM) i5-1135G7 2.40GHz)
Setup complete ✅ (8 CPUs, 15.7 GB RAM, 220.0/237.8 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.11.9
Install             pip
RAM                 15.73 GB
CPU                 11th Gen Intel Core(TM) i5-1135G7 2.40GHz
CUDA                None

matplotlib          ✅ 3.9.0>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.3.0>=1.8.0
torchvision         ✅ 0.18.0>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0

### Minimal Reproducible Example

model = YOLO(model_path)
results = model.predict(self.image_path, show_labels=False, show_conf=False)
result[0].save(filename=path_jpg_image)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello!

Thank you for reporting this issue with the `show_labels` and `show_conf` parameters not functioning as expected in YOLOv8.2.25. It seems like there might be a bug affecting these settings.

As a temporary workaround, you can manually edit the image output in your script after predictions are made but before saving the image. Here's a quick example of how you might adjust the visualization manually:

```python
model = YOLO(model_path)
results = model.predict(self.image_path)
for result in results:
    result.show_labels = False
    result.show_conf = False
result[0].save(filename=path_jpg_image)
```

This should help prevent labels and confidence scores from appearing in your saved images. Meanwhile, we'll look into this issue and aim for a fix in an upcoming release.

Thank you for your patience and for using Ultralytics YOLO!

**Comment by paulohss** [comment]
Thanks for the response @glenn-jocher !
Unfortunately, that won't work either, just tried it =/

**Comment by glenn-jocher** [comment]
Hello!

Thank you for trying out the suggested workaround and for your feedback. It seems we need to investigate this issue further. We appreciate your patience while we work on a resolution. Please stay tuned for updates on this matter.

**Comment by Burhan-Q** [comment]
@paulohss try using `result[0].save(filename=path_jpg_image, labels=False, conf=False)` when you pass the `show_labels` or `show_conf` arguments during prediction, these are for use _specifically_ with the `show` and `save` inference arguments. This is because the arguments passed to the `save()` method are forwarded to the `plot()` method. https://github.com/ultralytics/ultralytics/blob/fd854a7c6805ebd5c6e25917200ce5dbf1ac9a6e/ultralytics/engine/results.py#L310-L315

If you're only looking to save the annotated images from prediction, you can skip a step and add `save=True` to the `predict()` method. This however will be output to the default `runs/` directory, so if you want explicit control on where the output image is saved, use the `save()` method and include your plot arguments there.

I highly recommend checking out our [Docs page on predict mode](https://docs.ultralytics.com/modes/predict/). There's a lot of great information there, specifically the [Inference Arguments](https://docs.ultralytics.com/modes/predict/#inference-arguments) and [Plotting Results](https://docs.ultralytics.com/modes/predict/#plotting-results) sections.

**Comment by kira-pareser** [comment]
> @paulohss try using `result[0].save(filename=path_jpg_image, labels=False, conf=False)` when you pass the `show_labels` or `show_conf` arguments during prediction, these are for use _specifically_ with the `show` and `save` inference arguments. This is because the arguments passed to the `save()` method are forwarded to the `plot()` method.
> 
> https://github.com/ultralytics/ultralytics/blob/fd854a7c6805ebd5c6e25917200ce5dbf1ac9a6e/ultralytics/engine/results.py#L310-L315
> 
> If you're only looking to save the annotated images from prediction, you can skip a step and add `save=True` to the `predict()` method. This however will be output to the default `runs/` directory, so if you want explicit control on where the output image is saved, use the `save()` method and include your plot arguments there.
> 
> I highly recommend checking out our [Docs page on predict mode](https://docs.ultralytics.com/modes/predict/). There's a lot of great information there, specifically the [Inference Arguments](https://docs.ultralytics.com/modes/predict/#inference-arguments) and [Plotting Results](https://docs.ultralytics.com/modes/predict/#plotting-results) sections.

Hi, ```Ultralytics 8.3.51``` still not solved this issue yet right?

and the other issue that when i put ```results[0].save(filename = "EX02KZGDL6Z.jpg", labels = False, conf = True)``` it will remove either label and conf instead of keep the conf

This is same with when i use ```results[0].plot(labels = False, conf = True)```

I can't figure out why the labels keep both class and conf in it but the conf might be keep nothing in it

can you fix this please?


![image](https://github.com/user-attachments/assets/8895acfe-168b-4602-9a5a-2ab90e9132c4)
![image](https://github.com/user-attachments/assets/343f85f8-a343-4297-8b8c-315494f8b6be)
