### ISSUE TITLE
Change evaluation period

### ISSUE THREAD

**Issue by june94** [ultralytics/ultralytics#13439]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Thank you for your work! Could you please clarify how to change eval period in training process? For example, I want to run eval every 10 epochs, now (by default) evaluation runs after each epoch.

**Comment by glenn-jocher** [comment]
Hello!

Thank you for your kind words and for using YOLOv8! 😊

To change the evaluation period during the training process, you can use the `val_period` argument. This argument allows you to specify how often (in terms of epochs) you want the validation to run. By default, validation runs after each epoch, but you can adjust this to fit your needs.

Here's how you can set the evaluation to run every 10 epochs:

### Using Python
```python
from ultralytics import YOLO

# Load your model
model = YOLO('yolov8n.pt')  # or your custom model

# Train the model with validation every 10 epochs
results = model.train(data='coco128.yaml', epochs=100, imgsz=640, val_period=10)
```

### Using CLI
```bash
yolo detect train data=coco128.yaml model=yolov8n.pt epochs=100 imgsz=640 val_period=10
```

This will ensure that the validation step is performed every 10 epochs instead of after every epoch.

Feel free to reach out if you have any more questions or need further assistance. Happy training! 🚀

**Comment by june94** [comment]
Thank you!

**Comment by glenn-jocher** [comment]
@june94 you're welcome! 😊

If you have any more questions or need further assistance, feel free to ask. We're here to help! Happy training and best of luck with your projects! 🚀

If you encounter any issues or bugs, please make sure to provide a minimum reproducible code example. This will help us investigate and resolve the issue more efficiently. You can find more information on how to create one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, ensure that you are using the most recent versions of `torch` and `ultralytics`. If you haven't updated recently, please upgrade your packages and try again.

Thank you for being a part of the YOLO community!
