### ISSUE TITLE
Issue with Continued Training in YOLOv8 Classification

### ISSUE THREAD

**Issue by snehitvaddi** [ultralytics/ultralytics#13468]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Why does the training seem to restart from the beginning when resuming from saved weights, instead of continuing from where it left off?

### Additional

I’m encountering an issue with continued training using the YOLOv8 model. I have an image dataset and I’m trying to resume training from leftover epochs using the saved best model. I’ve set `model.resume = True` to continue the training. Here’s the code snippet I used:

```
model = YOLO(f'{HOME}/runs/classify/train2/weights/best.pt')
model.resume = True 

# train the model
results = model.train(
    epochs=300, 
    imgsz=640    
)
```

However, after resuming the training, the performance plot shows an unexpected behavior. Instead of continuing from where it left off, the training seems to be starting from the beginning. The attached graph illustrates this issue. It combines the results from both the initial and resumed training over several hundred epochs. Despite setting up for resumption, there’s a clear discontinuity in performance around epoch 200 where it appears as if the training has started over rather than continuing smoothly.

![image](https://github.com/ultralytics/ultralytics/assets/35267863/73022012-a78a-489c-a14d-f005735618ec)

**Comment by glenn-jocher** [comment]
Hello @snehitvaddi,

Thank you for reaching out and providing a detailed description of the issue you're encountering with continued training in YOLOv8. Let's work through this together to find a solution.

### Steps to Verify and Troubleshoot

1. **Minimum Reproducible Example**:
   To better understand and reproduce the issue, could you please provide a minimum reproducible code example? This will help us investigate the problem more effectively. You can refer to our [Minimum Reproducible Example Guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details on how to structure this.

2. **Ensure Latest Versions**:
   Please make sure you are using the latest versions of `torch` and `ultralytics`. You can upgrade your packages using the following commands:
   ```bash
   pip install --upgrade torch ultralytics
   ```

3. **Correct Resumption Method**:
   The `resume` argument should be passed directly to the `train` method rather than setting it as an attribute on the model. Here’s an updated version of your code snippet:
   ```python
   from ultralytics import YOLO

   # Load the model
   model = YOLO(f'{HOME}/runs/classify/train2/weights/best.pt')

   # Resume training
   results = model.train(
       epochs=300,
       imgsz=640,
       resume=True  # Pass resume as an argument here
   )
   ```

4. **Checkpoint Verification**:
   Ensure that the checkpoint file (`best.pt`) includes the optimizer state and other training parameters. This is crucial for resuming training correctly. If the checkpoint does not contain this information, the training will start from scratch.

5. **Monitoring Training Logs**:
   Keep an eye on the training logs to verify that the model is indeed resuming from the correct epoch. The logs should indicate the starting epoch when resuming training.

### Additional Resources

For further insights and troubleshooting tips, you can visit our [Common Issues Guide](https://docs.ultralytics.com/guides/yolo-common-issues/). This guide covers a range of topics that might help resolve your issue.

If you continue to experience problems, please share the additional details and logs here, and we'll be happy to assist you further.
