### ISSUE TITLE
Passing the parameters to new class 

### ISSUE THREAD

**Issue by MuhabHariri** [ultralytics/ultralytics#13461]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi

In the YAML file, there are parameters that determine the version of YOLO used during training by specifying the number of filters in the output of each block. These parameters include depth_multiple, width_multiple, and max_channels. 

Suppose I want to replace the C2F class with a different class, such as ConvMobileNetV2:

```
class ConvMobileNetV2(nn.Module):
    def __init__(self, in_channels, num_filters, kernel_size, stride):
        super(ConvMobileNetV2, self).__init__()
        self.num_filters = num_filters
        self.kernel_size = kernel_size
        self.stride = stride
        self.in_channels = in_channels
 
        self.conv = nn.Conv2d(in_channels, num_filters, kernel_size, stride=self.stride, padding=kernel_size // 2, bias=False)
        self.bn = nn.BatchNorm2d(num_filters)
        self.act = nn.ReLU6(inplace=True)
 
    def forward(self, x):
        x = self.act(self.bn(self.conv(x)))
        return x
```
How can I ensure these parameters are passed to the new class so that its output matches the original version of YOLOv8 (n, m, s, l, x)? Should I add something to the new class, or will these parameters be automatically passed to the output of the new class without needing to explicitly define them inside the new class?

Thanks for your help :)

**Comment by glenn-jocher** [comment]
@MuhabHariri hi there,

Thank you for your question and for providing a clear example of your custom class `ConvMobileNetV2`. It's great to see your interest in customizing the YOLOv8 architecture!

To ensure that your new class `ConvMobileNetV2` integrates seamlessly with the YOLOv8 architecture and that parameters like `depth_multiple`, `width_multiple`, and `max_channels` are correctly applied, you'll need to make a few adjustments. Here’s a step-by-step guide to help you achieve this:

1. **Modify the YAML Configuration:**
   Update your model's YAML file to replace the `C2F` class with your new `ConvMobileNetV2` class. Ensure that the parameters are correctly defined in the YAML file.

   ```yaml
   backbone:
     - [from, number, module, args]
     - [-1, 1, ConvMobileNetV2, [in_channels, num_filters, kernel_size, stride]]
   ```

2. **Update the `parse_model` Function:**
   The `parse_model` function in `ultralytics/nn/tasks.py` is responsible for parsing the YAML file and creating the model layers. You need to ensure that your new class is recognized and instantiated correctly.

   ```python
   def parse_model(d, ch, verbose=True):
       # ... existing code ...
       for i, (f, n, m, args) in enumerate(d["backbone"] + d["head"]):
           m = globals()[m] if m in globals() else getattr(torch.nn, m[3:]) if "nn." in m else None
           if m is None:
               raise ValueError(f"Module {m} not found in globals or torch.nn")
           # ... existing code ...
   ```

3. **Ensure Parameter Passing:**
   Your `ConvMobileNetV2` class should be designed to accept the parameters from the YAML file. Since you've already defined the `__init__` method to accept `in_channels`, `num_filters`, `kernel_size`, and `stride`, the parameters from the YAML file will be passed automatically when the model is instantiated.

4. **Example Integration:**
   Here’s an example of how you might define your custom class and ensure it integrates with the YOLOv8 architecture:

   ```python
   class ConvMobileNetV2(nn.Module):
       def __init__(self, in_channels, num_filters, kernel_size, stride):
           super(ConvMobileNetV2, self).__init__()
           self.conv = nn.Conv2d(in_channels, num_filters, kernel_size, stride=stride, padding=kernel_size // 2, bias=False)
           self.bn = nn.BatchNorm2d(num_filters)
           self.act = nn.ReLU6(inplace=True)

       def forward(self, x):
           return self.act(self.bn(self.conv(x)))
   ```

5. **Testing and Validation:**
   After making these changes, test your model to ensure that it works as expected. You can do this by running a training script and verifying that the model architecture is correctly built and that training proceeds without errors.

If you encounter any issues or need further assistance, please provide a minimum reproducible example so we can better understand the context and help you troubleshoot. You can find more details on creating a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Lastly, ensure you are using the latest versions of `torch` and `ultralytics` to avoid any compatibility issues. You can update your packages using:

```bash
pip install --upgrade torch ultralytics
```

I hope this helps! If you have any more questions or need further clarification, feel free to ask. Happy coding! 😊

**Comment by MuhabHariri** [comment]
Dear @glenn-jocher 
Thank you for your answer; it was very beneficial. However, could you tell me if depth_multiple, width_multiple, and max_channels should be passed to the new class ConvMobileNetV2 so that the new class output matches the original versions of YOLOv8 (n, m, s, l, x)? Should I add something to the new class, or will these parameters (depth_multiple, width_multiple, and max_channels) be automatically passed to the output of the new class (ConvMobileNetV2) without needing to explicitly define them inside the new class?

**Comment by glenn-jocher** [comment]
Dear @MuhabHariri,

Thank you for your follow-up question! I'm glad to hear that the previous response was helpful. 😊

To address your query about `depth_multiple`, `width_multiple`, and `max_channels`, these parameters are crucial for ensuring that the architecture of your custom class `ConvMobileNetV2` aligns with the original YOLOv8 versions (n, m, s, l, x). Here’s a detailed explanation:

### Understanding the Parameters

1. **`depth_multiple`**: This parameter scales the depth of the network, i.e., the number of layers.
2. **`width_multiple`**: This parameter scales the width of the network, i.e., the number of channels.
3. **`max_channels`**: This parameter limits the maximum number of channels in any layer.

### Integrating Parameters into `ConvMobileNetV2`

To ensure that these parameters are correctly applied to your custom class, you need to incorporate them into the initialization of your class. Here’s how you can do it:

1. **Modify the YAML Configuration**: Ensure that the parameters are correctly defined in the YAML file and passed to your custom class.

   ```yaml
   backbone:
     - [from, number, module, args]
     - [-1, 1, ConvMobileNetV2, [in_channels, num_filters, kernel_size, stride, depth_multiple, width_multiple, max_channels]]
   ```

2. **Update the Custom Class**: Modify the `ConvMobileNetV2` class to accept these parameters and use them to adjust the number of filters and layers.

   ```python
   class ConvMobileNetV2(nn.Module):
       def __init__(self, in_channels, num_filters, kernel_size, stride, depth_multiple, width_multiple, max_channels):
           super(ConvMobileNetV2, self).__init__()
           self.num_filters = min(int(num_filters * width_multiple), max_channels)
           self.kernel_size = kernel_size
           self.stride = stride
           self.in_channels = in_channels

           self.conv = nn.Conv2d(in_channels, self.num_filters, kernel_size, stride=self.stride, padding=kernel_size // 2, bias=False)
           self.bn = nn.BatchNorm2d(self.num_filters)
           self.act = nn.ReLU6(inplace=True)

       def forward(self, x):
           x = self.act(self.bn(self.conv(x)))
           return x
   ```

### Ensuring Compatibility

By incorporating `depth_multiple`, `width_multiple`, and `max_channels` into your class, you ensure that the output dimensions match the original YOLOv8 versions. This approach allows the model to dynamically adjust its architecture based on the specified parameters.

### Testing and Validation

After making these changes, I recommend testing your model to ensure that it works as expected. You can do this by running a training script and verifying that the model architecture is correctly built and that training proceeds without errors.

If you encounter any issues or need further assistance, please provide a minimum reproducible example so we can better understand the context and help you troubleshoot. You can find more details on creating a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Lastly, ensure you are using the latest versions of `torch` and `ultralytics` to avoid any compatibility issues. You can update your packages using:

```bash
pip install --upgrade torch ultralytics
```

I hope this helps! If you have any more questions or need further clarification, feel free to ask. Happy coding! 😊
