### ISSUE TITLE
Predict killed 

### ISSUE THREAD

**Issue by Keyird** [ultralytics/ultralytics#1346]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Thank you for you great work! When I test a large number of images，I found the program process would be killed ! So how to solve this problem?
![image](https://user-images.githubusercontent.com/46480540/223995950-f1a14ba0-00e0-4d14-ac0b-ec48f53efa68.png)
![image](https://user-images.githubusercontent.com/46480540/223996396-573d8494-a1d3-4e2f-b6b3-84f9c34b0ab2.png)

**Comment by Laughing-q** [comment]
@Keyird probably it's because of `out of memory`, python interface is keeping the predicted results which could happen `out of memory` if there are many images. Could you try again with command line?
```bash
yolo detect predict model=best.pt source=... save save_txt save_conf
```

**Comment by velastin** [comment]
Hello. I have the same issue with the command line. I had to split the directory with images. Tedious!
What is the "save" parameter in the command line?

**Comment by glenn-jocher** [comment]
Hello @velastin, thank you for your question. The `save` parameter in the command line is an optional argument that you can use to save the predicted output detections to an image or video file. This can be done by including the `save` argument followed by the path and file name of the output file. For example, you can use `--save path/output.jpg` to save the detections to a JPEG image file, or `--save path/output.mp4` to save the detections to an MP4 video file. 

However, since `save` creates and saves an output file on disk, this parameter may not necessarily solve your original issue. You may try other possible solutions such as downsample the inputs, reduce the batch size or other techniques to decrease memory requirement, or consider using a machine with larger memory if feasible. If you have any further questions, please do not hesitate to ask.
