### ISSUE TITLE
GPU_mem = 0 Using Apple M2 Chip

### ISSUE THREAD

**Issue by kowyo** [ultralytics/ultralytics#13488]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

Does `GPU_mem = 0` mean training is not using Apple Silicon GPU?

![image](https://github.com/ultralytics/ultralytics/assets/110339237/41c52c90-7b43-46fe-9ccb-05e411297bc1)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello!

Thank you for reaching out and for providing the details of your issue. It looks like you're encountering a problem where `GPU_mem = 0` during training on an Apple M2 chip.

To assist you better, could you please provide a minimal reproducible code example? This will help us understand the context and reproduce the issue on our end. You can find guidelines on how to create a minimal reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example). This step is crucial for us to investigate and resolve the bug effectively.

Additionally, please ensure that you are using the latest versions of `torch` and `ultralytics`. You can update your packages using the following commands:

```bash
pip install --upgrade torch ultralytics
```

Once you've updated, please try running your training script again and let us know if the issue persists.

For training on Apple Silicon (M1/M2), make sure you specify the device as 'mps' to utilize the Metal Performance Shaders (MPS) framework:

```python
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.pt')  # load a pretrained model

# Train the model with MPS
results = model.train(data='coco128.yaml', epochs=100, imgsz=640, device='mps')
```

If you continue to experience issues, please share the specific code snippet you are using along with any error messages or logs. This will help us diagnose the problem more accurately.

Looking forward to your response!

**Comment by kowyo** [comment]
Thank you for your reply! I have installed the latest torch and ultralytics and made sure that mps is available in my Mac. My code is just the same as mentioned above:

```
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.pt')  # load a pretrained model

# Train the model with MPS
results = model.train(data='coco128.yaml', epochs=100, imgsz=640, device='mps')
```

Let me know if it could be the MRE you want. I have also checked some issues with Mac user, though no one mentioned this issue before, but I could see from their screenshot that there `GPU_mem` is also 0.

But later before, I used Mac's GPU history and found that GPU usage is actually high, where I believed my GPU was engaged in the training task.

Thank you for any possible given advice!

**Comment by glenn-jocher** [comment]
@kowyo hello!

Thank you for providing the additional details and the code snippet. It's great to hear that you've ensured `torch` and `ultralytics` are up-to-date and that MPS is available on your Mac.

From your description, it seems like the GPU is indeed being utilized during training, even though `GPU_mem = 0` is displayed. This might be a display issue rather than an actual problem with GPU utilization.

To further investigate, you can try the following steps:

1. **Verify MPS Device Usage**:
   Ensure that the MPS device is being correctly utilized by printing the device information:

   ```python
   import torch
   print(torch.backends.mps.is_available())  # Should return True
   print(torch.backends.mps.is_built())      # Should return True
   ```

2. **Monitor GPU Usage**:
   Since you mentioned that the GPU usage is high according to the Mac's GPU history, it indicates that the GPU is engaged. You can also use the `Activity Monitor` to observe the GPU usage in real-time.

3. **Check Training Logs**:
   Sometimes, the training logs might provide more insights. Ensure that the logs indicate the use of the MPS device:

   ```python
   from ultralytics import YOLO

   # Load a model
   model = YOLO('yolov8n.pt')  # load a pretrained model

   # Train the model with MPS
   results = model.train(data='coco128.yaml', epochs=100, imgsz=640, device='mps', verbose=True)
   ```

4. **Update PyTorch and Ultralytics**:
   Although you've mentioned that you have the latest versions, it's always good to double-check. You can update using:

   ```bash
   pip install --upgrade torch ultralytics
   ```

5. **Check for Known Issues**:
   Sometimes, specific issues might be known and documented. You can check the [PyTorch MPS documentation](https://pytorch.org/docs/stable/notes/mps.html) for any known issues or updates related to MPS.

If the issue persists and `GPU_mem = 0` continues to be displayed while the GPU is being utilized, it might be a minor display bug. However, if the training performance is as expected and the GPU usage is high, you can be assured that the MPS device is being used effectively.

Feel free to reach out if you have any more questions or need further assistance. We're here to help! 😊

**Comment by kowyo** [comment]
I ran the code

```python
import torch
print(torch.backends.mps.is_available())  # Should return True
print(torch.backends.mps.is_built())      # Should return True
```

and both returned true.

I also find it a common confusion for Apple Silicon users in [stackflow](https://stackoverflow.com/questions/77478104/yolo-v8-training-couldnt-use-apple-m1-pro-chip).

Therefore I believed it's a displayed issue and need to be fixed.

**Comment by glenn-jocher** [comment]
Hello @kowyo,

Thank you for the detailed follow-up and for running the verification code. It's great to hear that both `torch.backends.mps.is_available()` and `torch.backends.mps.is_built()` returned `True`, confirming that the MPS device is available and built correctly on your Apple Silicon.

Given that the GPU usage is high according to your Mac's GPU history, it does indeed seem like the GPU is being utilized effectively during training. The `GPU_mem = 0` display issue might be a minor bug in how the memory usage is reported.

We appreciate your patience and understanding. To ensure that this is addressed, we'll look into this display issue further. In the meantime, you can continue to monitor the actual GPU usage through the Mac's Activity Monitor or other system tools.

If you encounter any other issues or have further questions, please don't hesitate to reach out. Your feedback is invaluable in helping us improve the experience for all users. 😊

Thank you for your support and for being an active member of the YOLO community!
