### ISSUE TITLE
problem with AMP

### ISSUE THREAD

**Issue by sandelush** [ultralytics/ultralytics#1348]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Transferred 319/355 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks failed . Anomalies were detected with AMP on your system that may lead to NaN losses or zero-mAP results, so AMP will be disabled during training.
optimizer: SGD(lr=0.01) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias
train: Scanning C:\Users\devel\Desktop\dataset\train\labels... 20912 images, 7 backgrounds, 0 corrupt: 100%|██████████|
train: New cache created: C:\Users\devel\Desktop\dataset\train\labels.cache
val: Scanning C:\Users\devel\Desktop\dataset\valid\labels... 6051 images, 1 backgrounds, 0 corrupt: 100%|██████████| 6051/6051 [00:40<00:00, 150.81it/s]
val: New cache created: C:\Users\devel\Desktop\dataset\valid\labels.cache
Plotting labels to runs\detect\train\labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to runs\detect\train
Starting training for 500 epochs...

### Environment

Ultralytics YOLOv8.0.51  Python-3.9.12 torch-2.0.0.dev20230301+cu118 CUDA:0 (NVIDIA GeForce RTX 2060 SUPER, 8192MiB)
Windows 10 PRO x64

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by wvalcke** [comment]
I just saw the same, also used yolov8n, (under Linux)

**Comment by glenn-jocher** [comment]
@sandelush @wvalcke everything is working correctly here. AMP checks are intended to verify correct operation of AMP before using it for training, and it appears using AMP on your system may lead to NaN training, so it has been disabled. 

You can manually set it in trainer.py to True or False, but the primary intention here to disable on different AMP results appears to be working correctly and protecting you from NaN training results.

**Comment by glenn-jocher** [comment]
@sandelush @wvalcke I've got new information! 8.0.51 did indeed have an AMP bug. This should be fixed in 8.0.52. Please update with `pip install -U ultralytics` and try again.

**Comment by wvalcke** [comment]
@glenn-jocher 
Indeed, problem is fixed, thanks for the update!

**Comment by glenn-jocher** [comment]
Great, thanks for letting us know!

**Comment by saikrishna0203** [comment]
Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8s.pt to 'yolov8s.pt'...
100% 21.5M/21.5M [00:00<00:00, 138MB/s]
Ultralytics YOLOv8.0.210 🚀 Python-3.10.12 torch-2.1.0+cu118 CUDA:0 (Tesla T4, 15102MiB)
engine/trainer: task=detect, mode=train, model=yolov8s.pt, data=data.yaml, epochs=500, patience=50, batch=4, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train7, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, stream_buffer=False, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train7
2023-11-16 07:56:15.388972: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-16 07:56:15.389027: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-16 07:56:15.389066: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
Overriding model.yaml nc=80 with nc=5

                   from  n    params  module                                       arguments                     
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]                 
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]             
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]           
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]              
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]           
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]                 
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]                 
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]                 
 22        [15, 18, 21]  1   2117983  ultralytics.nn.modules.head.Detect           [5, [128, 256, 512]]          
Model summary: 225 layers, 11137535 parameters, 11137519 gradients, 28.7 GFLOPs

Transferred 349/355 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir runs/detect/train7', view at http://localhost:6006/
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt to 'yolov8n.pt'...
100% 6.23M/6.23M [00:00<00:00, 96.0MB/s]
AMP: checks passed ✅     i am getting like this ,please clarify i have used model=yolov8s model but here it downloaded both v8s and v8n and started training ,is it wrong or correct?is the model is v8s or v8n please help

**Comment by glenn-jocher** [comment]
@saikrishna0203 hello! What you're experiencing seems to be a minor confusion within the process.

When you specify `model=yolov8s.pt`, the system should only download the YOLOv8's weights. However, the message you received about downloading YOLOv8n weights as well might be a part of the AMP (Automatic Mixed Precision) checks. AMP might be downloading YOLOv8n to use as a baseline for its checks.

The training should still be using YOLOv8s, as that is the model you've specified. To be completely sure, you can check the model summary output in your logs; it will specify the architecture and parameters of the model which is actually being used for training. The line `Transferred 349/355 items from pretrained weights` indicates that the weights have been transferred over to your specified model architecture – in this case, the YOLOv8s.

If there's no additional download outside of the AMP check, and the training proceeds with the stated model architecture, your process is correct and you're training with YOLOv8s. If there's any unintended behavior outside of this explanation, or if this significantly interferes with your workflow, you might want to look into the code responsible for the AMP checks or even flag it as an issue on the repository.

Remember, the model summary is key to understanding which model is in use, as it details the structure and parameters directly utilized in training.

**Comment by iadr** [comment]
Hello!
related to AMP and to this comment: https://github.com/ultralytics/ultralytics/issues/4107#issuecomment-1685938768.
Is it possible to set the path for the YOLOv8n file for AMP?

**Comment by glenn-jocher** [comment]
@iadr hello!

The AMP (Automatic Mixed Precision) check uses a YOLOv8 network by default for certain internal operations, which is why you've observed a YOLOv8n download even if you're training with a different model.

Currently, customizing the path or the specific model file used for AMP checks isn't a configurable feature out-of-the-box. The check is designed to ensure that AMP is compatible with your system and won't cause NaN losses or other training issues.

However, you have the option to manually change the source code if needed. You might modify the AMP check implementation within `trainer.py` or relevant source files to point to a specific model path. Keep in mind that this would require a good understanding of the codebase and careful adjustments to avoid introducing bugs.

Before you attempt any modifications, you should verify whether such changes are in alignment with the intended operation of the training script and ensure you are compliant with the licensing terms.

The Ultralytics team continuously works on improvements, and if this feature receives enough interest or is critical for use cases, it may be considered for future releases. You may also suggest this as a feature request on the repository's issue tracker for the team to review.

If changing the code isn't within your scope, using the software as provided ensures a smoother and more reliable experience, letting the AMP checks run as designed by the developers.

**Comment by emcrobert** [comment]
I'm also getting the amp check failure (version 8.0.222). 

It seems using YOLO Nano with full precision on the bus image detects 4 people, the bus and the sign. Whilst for mixed precision it only detects 3 of the people (doesn't detect the person whose arm you can see on the left hand side who is predicted with 0.25 probability when using full precision).

If I use YOLO large (which is the model I actually want to use) it returns 4 people whether I use mixed precision or full precision. Trying to get my head around this. Should I care that there is an issue with nano if that's not the model I intend to use or is it indicative that the larger model will also be less accurate in some cases? Why does this check produce different results for different people (is it hardware related or to do with the version of Cuda installed?)

I know you said to another person that if they want they can override trainer.py not to do the check or change checks.py to use the correct model, but I'm not really keen to make those changes without understanding the logic for the way it currently works. Also if I overwrite those files my changes will be lost whenever I update YOLO, or is there a way to make a patch so that doesn't happen?

**Comment by glenn-jocher** [comment]
@emcrobert the AMP check failure in version 8.0.222 is not unusual; it's a precautionary step to ensure AMP compatibility with different systems. Some variation in detection results between full precision and mixed precision (AMP) is common due to the inherent differences in precision handling.

Regarding the discrepancy in detections between YOLO Nano and YOLO Large: the model size and architecture can influence how robust it is to the changes AMP introduces. Larger models often have more capacity to maintain accuracy under reduced precision conditions. It is not necessarily indicative that larger models will be less accurate; they may be more resilient.

The differences in AMP check results can indeed be hardware-related or due to different CUDA versions—each system's unique configuration can affect the outcome.

While you could modify `trainer.py` or `checks.py`, these changes would be overwritten with updates. As for maintaining custom changes, you could fork the Ultralytics YOLOv8 repo, apply your changes to the fork, and update manually as needed. This way, you preserve your modifications while still being able to pull in upstream changes from the original repository.

**Comment by ztxdcyy** [comment]
AMP: checks failed ❌. Anomalies were detected with AMP on your system that may lead to NaN losses or zero-mAP results, so AMP will be disabled during training.

Maybe you can change the code in here:`ultralytics/utils/checks.py` line 470.
Change `assert amp_allclose(YOLO('yolov8n.pt'), im)` to `assert amp_allclose(YOLO('your-custom-weight.pt'), im)

**Comment by glenn-jocher** [comment]
@ztxdcyy hey there! 👋

Thanks for reaching out. The AMP check is designed to ensure stable training, and it's good to see you're keeping an eye on it. If you're consistently seeing this message and you're certain that your custom model is stable with AMP, you can indeed modify the check as you suggested. Just replace `'yolov8n.pt'` with the path to your custom weights in `checks.py`:

```python
assert amp_allclose(YOLO('path/to/your-custom-weight.pt'), im)
```

Remember to keep a backup of the original `checks.py` in case you need to revert your changes. Happy training! 🚀

**Comment by glenn-jocher** [comment]
Hey there! 😊

Thanks for reaching out with your inquiry about the AMP checks during training with YOLOv9c. To clarify:

1. **Why YOLOv8n.pt is downloaded:** The AMP (Automatic Mixed Precision) checks in our training script currently use a fixed model (YOLOv8n) to perform stability and compatibility tests with AMP on your specific system setup. This ensures that AMP can be safely used without leading to potential issues like NaN losses or zero mAP results.

2. **Why AMP checks are done with YOLOv8n instead of YOLOv9c:** The model used for AMP checks is standardized (YOLOv8n) across all training sessions regardless of the actual model being trained (e.g., YOLOv9c). This is to maintain consistency in testing AMP's compatibility across different systems and configurations.

This approach helps ensure that if AMP is compatible with the test model (YOLOv8n), it would likely be compatible with others, including the newer YOLOv9c, making these checks a sort of "baseline" assessment.

Your setup and usage look correct! 👍 The AMP check using YOLOv8n doesn't impact your training with YOLOv9c; it's just a preliminary compatibility test.

Hope this clears things up. Happy training with YOLOv9c! 🚀

**Comment by Ezreal0211** [comment]
Version: 8.0.200
D:\kaggle dataset\coco2017\ultralytics-main>yolo pose train data=coco8-pose.yaml model=yolov8n-pose.yaml epochs=100 imgsz=640

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1   1035934  ultralytics.nn.modules.head.Pose             [1, [17, 3], [64, 128, 256]]
YOLOv8n-pose summary: 250 layers, 3295470 parameters, 3295454 gradients, 9.3 GFLOPs

D:\anaconda\envs\yolov8pose\lib\site-packages\torch\cuda\__init__.py:104: UserWarning: 
NVIDIA GeForce RTX 3050 Laptop GPU with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA GeForce RTX 3050 Laptop GPU GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Ultralytics YOLOv8.0.200  Python-3.8.18 torch-1.8.0 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
WARNING  Upgrade to torch>=2.0.0 for deterministic training.
engine\trainer: task=pose, mode=train, model=yolov8n-pose.yaml, data=coco8-pose.yaml, epochs=100, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=trai
n4, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=Non
e, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save
_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, stream_buffer=False, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, forma
t=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8,
 warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=runs\pose\train
`Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
     59/100      1.12G      3.141       9.63     0.6979      3.519      4.154         15        640: 100%|██████████| 1/1 [00:00<00:00,  8.61it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 13.99it/s]
                   all          4         14    0.00417      0.357    0.00288    0.00153          0          0          0          0

      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
     60/100      1.12G      3.653      10.31     0.6937      3.705      4.153         20        640: 100%|██████████| 1/1 [00:00<00:00,  5.32it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 26.93it/s]
                   all          4         14    0.00417      0.357    0.00288    0.00153          0          0          0          0
`
When I tried to use my laptop (3050 graphics card) YOLOv8 for posture estimation tasks, the amp check failed, and the training results showed that the indicators related to posture (p r map map50-95) were all 0. Why is this?

**Comment by glenn-jocher** [comment]
Hello @Ezreal0211,

Thank you for providing detailed information about your setup and the issue you're encountering. Let's address your concerns step-by-step.

### AMP Check Failure

The AMP (Automatic Mixed Precision) check failure indicates that your system might have compatibility issues with AMP, which can lead to NaN losses or zero-mAP results. This is why AMP is being disabled during training. The AMP check uses a standard model (YOLOv8n) to ensure consistency across different systems.

### CUDA Compatibility Warning

The warning message indicates that your NVIDIA GeForce RTX 3050 Laptop GPU is not fully compatible with the current PyTorch installation. Specifically, your PyTorch installation supports CUDA capabilities up to sm_75, while your GPU requires sm_86. This mismatch can lead to suboptimal performance or even failures during training.

### Zero mAP Results

The zero mAP results for pose estimation metrics (P, R, mAP50, mAP50-95) suggest that the model is not learning effectively. This could be due to several factors:

1. **CUDA Compatibility:** The warning about CUDA compatibility might be affecting the training process. Ensure you have the correct version of PyTorch installed that supports your GPU. You can follow the instructions at [PyTorch Get Started](https://pytorch.org/get-started/locally/) to install the appropriate version.

2. **AMP Issues:** Since AMP checks failed, it's good that AMP is disabled. However, you might want to ensure that your training runs smoothly without AMP. You can explicitly disable AMP in your training command to avoid any potential issues:
    ```python
    result = model.train(data='data.yaml', epochs=1, imgsz=640, amp=False)
    ```

3. **Dataset and Labels:** Ensure that your dataset and labels are correctly formatted and of high quality. Incorrect annotations can lead to poor training performance.

### Next Steps

1. **Verify CUDA and PyTorch Installation:**
    - Ensure you have the correct version of PyTorch installed that supports your GPU. Follow the [PyTorch installation guide](https://pytorch.org/get-started/locally/) and select the appropriate CUDA version for your system.

2. **Disable AMP Explicitly:**
    - If you haven't already, try disabling AMP explicitly in your training command to see if it resolves the issue:
    ```python
    result = model.train(data='data.yaml', epochs=1, imgsz=640, amp=False)
    ```

3. **Check Dataset Quality:**
    - Verify that your dataset and annotations are correctly formatted and of high quality. Poor quality data can lead to poor training performance.

4. **Reproducible Example:**
    - If the issue persists, please provide a minimal reproducible example to help us diagnose the problem more effectively. You can follow the guidelines here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

By following these steps, you should be able to address the issues you're encountering. If you continue to face problems, feel free to provide additional details, and we'll be happy to assist further.

Best regards and happy training! 🚀

**Comment by beizhengren** [comment]
Hi @glenn-jocher ,  In case of downloading everytime during training, where can I put yolov8n.pt?

**Comment by glenn-jocher** [comment]
You can place `yolov8n.pt` in the same directory where you're running your script to avoid downloading it each time. Ensure your code references the correct path to this file.

**Comment by glenn-jocher** [comment]
You can place `yolov8n.pt` in the same directory where you run your training script, or specify its path directly in your training command to avoid redownloading.

**Comment by glenn-jocher** [comment]
You can place `yolov8n.pt` in the same directory where you're running your training script to avoid downloading it each time.

**Comment by glenn-jocher** [comment]
You can place `yolov8n.pt` in the same directory where you run your training script to avoid downloading it each time.

**Comment by glenn-jocher** [comment]
@beizhengren you can place `yolov8n.pt` in the same directory where you run your training script, or specify the path directly in your training command to avoid re-downloading.

**Comment by glenn-jocher** [comment]
You can place the `yolov8n.pt` file in the same directory where you're running your training script to avoid downloading it each time.
