### ISSUE TITLE
YOLO reduce original video's number of frame when inferring

### ISSUE THREAD

**Issue by KieuSonTung** [ultralytics/ultralytics#13507]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi everyone! I hope that someone can help me fix this. 

I'm using DetectionPredictor from `ultralytics.models.yolo.detect` with my pre-trained model to infer a video. I used this line of code

```python
model = DetectionPredictor(cfg=args)
results = model(source=video_path, stream=True)
```

which `args` is a dictionary of custom parameters (device, project, name, batch).

In the original video, there are 48000 frames. However, when I loop the `results` and count, there are only 24000 frames. How does this happen? And also, does YOLO support reducing video's FPS while inferring or training?

Thank you so much!

**Comment by glenn-jocher** [comment]
Hello!

Thank you for reaching out and providing details about your issue. Let's address your concerns step-by-step.

### Frame Reduction Issue
The reduction in the number of frames from 48,000 to 24,000 suggests that the inference process might be skipping frames. This can happen due to the `vid_stride` parameter, which controls the frame stride for video inputs. By default, `vid_stride` is set to 1, meaning every frame is processed. If this parameter is set to a higher value, it will skip frames accordingly.

Could you please check if `vid_stride` is set in your `args` dictionary? If not, you can explicitly set it to 1 to ensure every frame is processed:

```python
args['vid_stride'] = 1
model = DetectionPredictor(cfg=args)
results = model(source=video_path, stream=True)
```

### Reducing Video FPS
Yes, YOLO does support reducing the video's FPS during inference or training. You can achieve this by adjusting the `vid_stride` parameter. For example, setting `vid_stride` to 2 will process every second frame, effectively halving the FPS:

```python
args['vid_stride'] = 2  # Process every second frame
model = DetectionPredictor(cfg=args)
results = model(source=video_path, stream=True)
```

### Next Steps
1. **Check `vid_stride`**: Ensure `vid_stride` is set to 1 if you want to process every frame.
2. **Update Packages**: Make sure you are using the latest versions of `torch` and `ultralytics`. You can update them using:
    ```bash
    pip install --upgrade torch ultralytics
    ```

If the issue persists after these steps, please provide a minimum reproducible example of your code. This will help us investigate further. You can refer to our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.

Feel free to reach out if you have any more questions or need further assistance. We're here to help! 😊

**Comment by KieuSonTung** [comment]
Hi @glenn-jocher . Thank you so much for replying.

I tried to adjust `vid_stride` parameter but it didn't work.

I used this code to print out the number of frames and fps
```python
video_path = '/data/test_video/T160-1_video.mp4'

cap = cv2.VideoCapture(video_path)
frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
fps = cap.get(cv2.CAP_PROP_FPS)

print('FRAME_COUNT', frame_count)
```
and it returns **22833** frames

And i ran this code to count the number of frames in the result output:
```python
args['vid_stride'] = 1
    
model = DetectionPredictor(cfg=args)
results = model(source=video_path, stream=True)

cnt = 0

for r in results:
    cnt += 1

print(cnt)
```
and it returns **11411** frames.

What should I do next? Thank you so much.

**Comment by glenn-jocher** [comment]
Hi @KieuSonTung,

Thank you for providing additional details and the code snippets. Let's work together to resolve this issue.

### Steps to Investigate Further

1. **Verify Package Versions**:
   Ensure you are using the latest versions of `torch` and `ultralytics`. You can update them using:
   ```bash
   pip install --upgrade torch ultralytics
   ```

2. **Check Video Properties**:
   Let's verify the video properties directly using OpenCV to ensure there are no discrepancies:
   ```python
   import cv2

   video_path = '/data/test_video/T160-1_video.mp4'
   cap = cv2.VideoCapture(video_path)
   frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
   fps = cap.get(cv2.CAP_PROP_FPS)

   print('FRAME_COUNT:', frame_count)
   print('FPS:', fps)
   ```

3. **Minimum Reproducible Example**:
   If the issue persists, please provide a minimum reproducible example. This will help us investigate the problem more effectively. You can refer to our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.

4. **Debugging the Frame Count**:
   Let's add some debug prints to understand where the frames might be getting skipped:
   ```python
   from ultralytics.models.yolo.detect import DetectionPredictor

   args = {
       'vid_stride': 1,
       'device': '0',  # Example device, adjust as needed
       'project': 'runs/detect',
       'name': 'exp'
   }

   model = DetectionPredictor(cfg=args)
   results = model(source=video_path, stream=True)

   cnt = 0

   for r in results:
       cnt += 1
       print(f"Processing frame {cnt}")

   print(f"Total frames processed: {cnt}")
   ```

### Next Steps
1. **Update Packages**: Ensure you are using the latest versions of `torch` and `ultralytics`.
2. **Verify Video Properties**: Run the provided code to check the frame count and FPS.
3. **Provide a Minimum Reproducible Example**: If the issue persists, share a minimal code example that reproduces the problem.

By following these steps, we can better understand the issue and work towards a solution. Feel free to reach out if you have any more questions or need further assistance. We're here to help! 😊
