### ISSUE TITLE
Issue on fine-tuning yolov10 on custom dataset

### ISSUE THREAD

**Issue by vhuard** [ultralytics/ultralytics#13508]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

the training session bugged at launch on Yolov10n while working perfectly on Yolov8n.
i got the following message
Traceback (most recent call last):
  File "/scorpion/home/vhu/.conda/envs/ultralytics/bin/yolo", line 5, in <module>
    from ultralytics.cfg import entrypoint
  File "/scorpion/home/vhu/.conda/envs/ultralytics/lib/python3.11/site-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.data.explorer.explorer import Explorer
  File "/scorpion/home/vhu/.conda/envs/ultralytics/lib/python3.11/site-packages/ultralytics/data/explorer/explorer.py", line 18, in <module>
    from ultralytics.models.yolo.model import YOLO
  File "/scorpion/home/vhu/.conda/envs/ultralytics/lib/python3.11/site-packages/ultralytics/models/__init__.py", line 6, in <module>
    from .yolov10 import YOLOv10
  File "/scorpion/home/vhu/.conda/envs/ultralytics/lib/python3.11/site-packages/ultralytics/models/yolov10/__init__.py", line 1, in <module>
    from .model import YOLOv10
  File "/scorpion/home/vhu/.conda/envs/ultralytics/lib/python3.11/site-packages/ultralytics/models/yolov10/model.py", line 7, in <module>
    from huggingface_hub import PyTorchModelHubMixin
ModuleNotFoundError: No module named 'huggingface_hub'
yolo checks

### Environment

Yolo8.2.31

### Minimal Reproducible Example

yolo task=detect mode=train model=/net/eagle/volume1/homes/vhu/IRT/yolov10n.pt data=/net/eagle/volume1/homes/vhu/IRT/data.yaml epochs=2000 imgsz=640

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hi @vhuard,

Thank you for bringing this issue to our attention! Let's work together to resolve it.

Firstly, it appears that the error is due to a missing dependency, specifically the `huggingface_hub` module. To resolve this, please install the missing module using the following command:

```bash
pip install huggingface_hub
```

Additionally, to ensure we can effectively investigate and address the issue, please verify the following:

1. **Reproducible Code Example**: Ensure that the provided code snippet is a minimal reproducible example. This helps us replicate the issue on our end. If you haven't already, please refer to our [guide on creating a minimal reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example).

2. **Package Versions**: Confirm that you are using the latest versions of `torch` and `ultralytics`. You can update your packages with the following commands:
    ```bash
    pip install --upgrade torch ultralytics
    ```

Once you've installed the missing module and ensured that your packages are up-to-date, please try running your training session again. If the issue persists, kindly provide any additional details or error messages you encounter.

Thank you for your cooperation, and we look forward to your response! 😊
