### ISSUE TITLE
non_max_suppression slow

### ISSUE THREAD

**Issue by HonestyBrave** [ultralytics/ultralytics#13521]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hi, i find a strange situation, 
i run a list of picture(about 3000 picture), each one picture i will cut more 100 small picture(640*640), then i batch(100) to predict, when first time the predict speed is quickly, about 1.2 second, but when do about 20 picture, the predict speed is slow(about 2.5 ~ 3.1 second), i find is the "**non_max_suppression**"  use much time, but why first time not use much time, why it will only increase after running for a while?

my code snippet is:
**model = attempt_load_weights(weight_path).to('cuda:0')
outputs = model(batch_picture)
nms_s = time.time()
outputs = outputs[0].cpu()
preds = ops.non_max_suppression(outputs, conf_thres=0.2, iou_thres=0.45, agnostic=False, max_det=168)
print(f'nms_s: {time.time() - nms_s}')**

Line 13: nms_s: 0.018895626068115234
Line 18:  nms_s: 0.02105712890625
Line 32: nms_s: 1.2599573135375977
Line 37:  nms_s: 1.6235673427581787
Line 51: nms_s: 0.7149143218994141
Line 56:  nms_s: 1.315716028213501
Line 70: nms_s: 1.0886635780334473
Line 75:  nms_s: 1.231294870376587
Line 102: nms_s: 1.392979383468628
Line 107:  nms_s: 1.3906316757202148
Line 121: nms_s: 1.4222452640533447
Line 126:  nms_s: 1.4749529361724854
Line 140: nms_s: 1.2883412837982178
Line 145:  nms_s: 1.3660409450531006
Line 159: nms_s: 1.0422418117523193
Line 164:  nms_s: 1.4288499355316162
Line 178: nms_s: 1.3430383205413818
Line 183:  nms_s: 1.5197572708129883
Line 197: nms_s: 0.8600707054138184
Line 202:  nms_s: 1.5291690826416016
Line 216: nms_s: 1.0888807773590088
Line 221:  nms_s: 1.35687255859375

**Comment by glenn-jocher** [comment]
@HonestyBrave hi there! 👋

Thank you for reaching out and providing a detailed description of the issue you're encountering with `non_max_suppression` (NMS) slowing down over time. Let's work through this together.

### Initial Checks

1. **Reproducible Example**: To better assist you, could you please provide a minimum reproducible code example? This will help us replicate the issue on our end and investigate further. You can refer to our guide on creating a minimum reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

2. **Library Versions**: Ensure that you are using the latest versions of `torch` and `ultralytics`. You can upgrade your packages using the following commands:
   ```bash
   pip install --upgrade torch ultralytics
   ```

### Potential Causes and Solutions

The slowdown you're experiencing could be due to several factors, including memory leaks or GPU memory fragmentation. Here are a few steps you can take to diagnose and potentially resolve the issue:

1. **Memory Management**: Ensure that you are properly managing GPU memory. You can try clearing the cache periodically using:
   ```python
   import torch
   torch.cuda.empty_cache()
   ```

2. **Batch Processing**: If you're processing a large number of images in batches, ensure that each batch is handled independently to avoid memory buildup. For example:
   ```python
   for batch in batches:
       outputs = model(batch)
       outputs = outputs[0].cpu()
       preds = ops.non_max_suppression(outputs, conf_thres=0.2, iou_thres=0.45, agnostic=False, max_det=168)
       torch.cuda.empty_cache()
   ```

3. **Profiling**: Use profiling tools to identify bottlenecks in your code. You can use `torch.profiler` to get detailed insights into where the time is being spent.

### Example Code

Here's a modified version of your code snippet with some of the suggestions applied:
```python
import torch
from ultralytics import YOLO
import time

# Load model
model = YOLO('path/to/weights.pt').to('cuda:0')

# Process batches
for batch in batches:
    start_time = time.time()
    outputs = model(batch)
    outputs = outputs[0].cpu()
    preds = ops.non_max_suppression(outputs, conf_thres=0.2, iou_thres=0.45, agnostic=False, max_det=168)
    print(f'NMS time: {time.time() - start_time}')
    torch.cuda.empty_cache()
```

### Next Steps

Please try the above suggestions and let us know if the issue persists. If it does, providing the minimum reproducible example will be crucial for us to dive deeper into the problem.

Thank you for your patience and cooperation. We're here to help! 😊

**Comment by HonestyBrave** [comment]
thank you for you reply in time, much pleasure.

i find is my server problem, i run the same code in other server, it not have the problem, but add "**torch.cuda.empty_cache()**" will add about 200ms in 2080Ti server. thank you again for you reply!

**Comment by glenn-jocher** [comment]
Hi @HonestyBrave,

Thank you for the update! 😊 I'm glad to hear that running the code on a different server resolved the issue. It sounds like the initial server might have had some underlying hardware or configuration problems affecting performance.

Regarding the `torch.cuda.empty_cache()` function, it's true that while it helps manage GPU memory, it can introduce a slight overhead. If you find that it adds significant delay, you might want to use it more sparingly or explore other memory management strategies.

If you have any more questions or run into other issues, feel free to reach out. We're here to help! 🚀
