### ISSUE TITLE
Postprocess Yolov8-segmentation raw prediction

### ISSUE THREAD

**Issue by dhouib-akram** [ultralytics/ultralytics#13523]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm trying to host my yolov8-segmentation model in a triton server, I have added nms layers when exporting the yolov8 model to .onnx format 
After exporting to .engine format and hosting the model to triton server I get the prediction output which is something like this :
```
output = results.as_numpy("output0") #ouput0 shape:  (1, 49, 8400)
# i have 13 classes so 49 = 4+13+32
output1 = results.as_numpy("output1")[0,:,:,:] #output1.shape:  (32, 160, 160)

selected_boxes = results.as_numpy("num_selected_indices") #selected_boxes.shape (n,3)
```

  
Postprocess the output and get get a masks array

```
output_boxes = output[0, :17, :] 
masks = output[0, 17:, :]

batch_size_id,labels,boxes_indexes=selected_boxes[:,0],selected_boxes[:,1],selected_boxes[:,2]
masks=masks[:,boxes_indexes]
masks=masks.T  #(n, 32) 

output1 = output1.reshape(32,160*160)

masks = masks @ output1 #(n, 32) (32, 25600)
```

To postprocess the masks, I used these functions
```
def sigmoid(z):
    return 1 / (1 + np.exp(-z))
def get_mask(row,box,img_w, img_h):    
    mask = row.reshape(160,160)
    mask = sigmoid(mask)
    #i
    mask = (mask > 0.5).astype('uint8')*255
    mask_x1 = round(box.x1/img_w*160)
    mask_y1 = round(box.y1/img_h*160)
    mask_x2 = round(box.x2/img_w*160)
    mask_y2 = round(box.y2/img_h*160)
    mask = mask[mask_y1:mask_y2,mask_x1:mask_x2]
    
    desired_width = round(box.x2 - box.x1)
    desired_height = round(box.y2 - box.y1)

# Resize mask directly to the bounding box size
    mask_resized = cv2.resize(mask, (desired_width, desired_height), interpolation=cv2.INTER_LINEAR)

    return mask_resized 
def get_polygon(mask):
    # Find contours
    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    
    # List to hold all polygons
    polygons = []
    for contour in contours:
        # Extract polygon points
        if len(contour) > 0:
            # Assume contour is an array of points and convert to a list of tuples
            polygon = [(int(point[0][0]), int(point[0][1])) for point in contour]
            polygons.append(polygon)
    
    return polygons
def postprocess(det_boxes, det_scores, det_classes, img_w, img_h, input_shape, masks):
    detected_objects = []
    polygons = []
    
    # Extracting box coordinates and converting to (x1, y1, x2, y2) format
    x, y, w, h = det_boxes[:, 0], det_boxes[:, 1], det_boxes[:, 2], det_boxes[:, 3]
    x1, y1, x2, y2 = (x - 0.5 * w), (y - 0.5 * h), (x + 0.5 * w), (y + 0.5 * h)
    boxes = np.stack([x1, y1, x2, y2], axis=-1)


    # Calculate the scale factors for width and height
    width_scale = img_w / input_shape[0]
    height_scale = img_h / input_shape[1]

    # Apply scale factors to adjust the bounding box coordinates
    boxes = boxes * np.array([width_scale, height_scale, width_scale, height_scale], dtype=np.float32)

    # Extract scores and classes
    scores = det_scores
    classes = det_classes


    for box, score, label,mask in zip(boxes, scores, classes,masks):
        # Ensure that box coordinates are within the image boundaries
        box = np.clip(box, 0, [img_w, img_h, img_w, img_h])
        box=BoundingBox(label, score, box[0], box[2], box[1], box[3], img_w, img_h)
        detected_objects.append(box)

            
        mask=get_mask(mask,box,img_w,img_h)
        
        polygons.append(get_polygon(mask))
       
    return detected_objects,polygons
```

The problem is when i draw those masks on the image i get a low resolution masks like in the first image

![image](https://github.com/ultralytics/ultralytics/assets/93084779/6469ca41-fb70-4fcd-ac23-03e1dff4061d)

If i use the ultralytics predifined predict function i get a high resolution prediction like in this image, although i am using the same model

![image](https://github.com/ultralytics/ultralytics/assets/93084779/969006d7-b4d6-4e3f-af21-cafa3604e3bc)

My question is what should  I do to have a high resolution inference and transform raw model prediction to high quality masks

**Comment by glenn-jocher** [comment]
Hi @dhouib-akram,

Thank you for reaching out and providing a detailed description of your issue along with the code snippets. It's great to see your effort in hosting the YOLOv8-segmentation model on a Triton server and working through the post-processing steps.

To address your concern about the low-resolution masks, there are a few key points and suggestions to consider:

1. **Ensure Latest Versions**: First, please make sure you are using the latest versions of `torch` and `ultralytics`. You can update them using:
    ```bash
    pip install --upgrade torch ultralytics
    ```

2. **Model Export and NMS**: When exporting the model to ONNX and subsequently to TensorRT, ensure that the Non-Maximum Suppression (NMS) layer is correctly integrated. If the NMS is not properly handled, it might affect the quality of the masks.

3. **Resolution Handling**: The low-resolution issue might be due to the resizing and reshaping operations. Ensure that the mask resolution is consistent throughout the process. Here’s a refined approach to handle the mask resolution:

    ```python
    def get_mask(row, box, img_w, img_h):
        mask = row.reshape(160, 160)
        mask = sigmoid(mask)
        mask = (mask > 0.5).astype('uint8') * 255

        # Calculate the bounding box coordinates in the mask's scale
        mask_x1 = round(box.x1 / img_w * 160)
        mask_y1 = round(box.y1 / img_h * 160)
        mask_x2 = round(box.x2 / img_w * 160)
        mask_y2 = round(box.y2 / img_h * 160)

        # Crop the mask to the bounding box
        mask = mask[mask_y1:mask_y2, mask_x1:mask_x2]

        # Resize mask directly to the bounding box size
        desired_width = round(box.x2 - box.x1)
        desired_height = round(box.y2 - box.y1)
        mask_resized = cv2.resize(mask, (desired_width, desired_height), interpolation=cv2.INTER_LINEAR)

        return mask_resized
    ```

4. **Post-Processing Pipeline**: Ensure that the post-processing pipeline maintains the resolution integrity. Here’s a refined version of your `postprocess` function:

    ```python
    def postprocess(det_boxes, det_scores, det_classes, img_w, img_h, input_shape, masks):
        detected_objects = []
        polygons = []

        # Extracting box coordinates and converting to (x1, y1, x2, y2) format
        x, y, w, h = det_boxes[:, 0], det_boxes[:, 1], det_boxes[:, 2], det_boxes[:, 3]
        x1, y1, x2, y2 = (x - 0.5 * w), (y - 0.5 * h), (x + 0.5 * w), (y + 0.5 * h)
        boxes = np.stack([x1, y1, x2, y2], axis=-1)

        # Calculate the scale factors for width and height
        width_scale = img_w / input_shape[0]
        height_scale = img_h / input_shape[1]

        # Apply scale factors to adjust the bounding box coordinates
        boxes = boxes * np.array([width_scale, height_scale, width_scale, height_scale], dtype=np.float32)

        # Extract scores and classes
        scores = det_scores
        classes = det_classes

        for box, score, label, mask in zip(boxes, scores, classes, masks):
            # Ensure that box coordinates are within the image boundaries
            box = np.clip(box, 0, [img_w, img_h, img_w, img_h])
            box = BoundingBox(label, score, box[0], box[2], box[1], box[3], img_w, img_h)
            detected_objects.append(box)

            mask = get_mask(mask, box, img_w, img_h)
            polygons.append(get_polygon(mask))

        return detected_objects, polygons
    ```

5. **Comparison with Ultralytics Predict**: If the predefined `predict` function from Ultralytics provides high-resolution masks, it might be beneficial to compare the internal steps of the `predict` function with your custom implementation. Ensure that the preprocessing and postprocessing steps align closely.

For further details on the `AutoBackend` class and dynamic backend selection, you can refer to the [Ultralytics documentation](https://docs.ultralytics.com/reference/nn/autobackend/).

If the issue persists, please provide a minimum reproducible example so we can investigate further. You can follow the guidelines here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions or need further assistance! 😊

**Comment by dhouib-akram** [comment]
Hello @glenn-jocher,

Thank you so much for your reply.

I haven't noticed any changes in the refined functions you provided. Could you please explain what modifications were made? 
I began my pipeline by building the Ultralytics Docker image, then trained the YOLOv8-segment model, and exported it to ONNX. Even without exporting to TensorRT or deploying to an inference server, I still encounter poor prediction results when using my code to postprocess the model predictions.

Here is a code snippet of how I attempted to infer the .onnx model:
```
import cv2
import numpy as np
import onnxruntime as ort
from processing import postprocess,preprocess
from render import render_box, render_filled_box, get_text_size, render_text, RAND_COLORS

classes=["L_back_door", "L_back_window", "L_front_door", "L_front_window", "R_back_door", "R_back_window", "R_front_door", "R_front_window", "back_window", "fg", "front_window", "plate", "wheel"]
labels = {idx: val for idx, val in enumerate(classes)}



# Load ONNX model using ONNX Runtime
session = ort.InferenceSession("path/to/best.onnx")
input_name = session.get_inputs()[0].name

# Path to your test image
image_path = "path/to/image.jpg"
input_shape = (640, 640)  #  input shape
img = cv2.imread(image_path)
# Load and preprocess the image
img = preprocess(img, input_shape)
# Perform inference
outputs = session.run(None, {input_name: img[np.newaxis, :, :, :]})
output = outputs[0]
output1 = outputs[1]

output_boxes = output[0, :17, :]
masks = output[0, 17:, :]
selected_boxes = outputs[2]

batch_size_id,labels,boxes_indexes=selected_boxes[:,0],selected_boxes[:,1],selected_boxes[:,2]
selected_boxes,det_scores = output_boxes[:4,boxes_indexes],output_boxes[ 4:, boxes_indexes]
#transpose selected boxes from 4,len boxes_indexes to boxes_indexes,4
selected_boxes = selected_boxes.T

max_class_probability = np.max(det_scores, axis=0)

masks=masks[:,boxes_indexes]

masks=masks.T


output1 = output1.reshape(32,160*160)
 #(8400, 32) (32, 25600)
masks = masks @ output1

print((input_shape[0], input_shape[1]))
print(img.shape)
detected_objects,polygons = postprocess(selected_boxes, max_class_probability, labels, img.shape[1], img.shape[2], (input_shape[0], input_shape[1]),masks)
# Initialize an overlay that will be used to accumulate all drawings
img=img.transpose((1, 2, 0))*255.0
img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)

final_overlay = np.zeros_like(img)
output_image_path="/path/to/output.jpg"
# Draw the bounding boxes and masks
for i, box in enumerate(detected_objects):
    name = labels[box.classID]
    
    
    color=tuple(RAND_COLORS[box.classID % 64].tolist())

    frame = render_box(img, (box.x1, box.y1, box.x2, box.y2), color=tuple(RAND_COLORS[box.classID % 64].tolist()))
    size = get_text_size(frame, f"{name}: {box.confidence:.2f}", normalised_scaling=0.6)
    frame = render_filled_box(frame, (box.x1 - 3, box.y1 - 3, box.x1 + size[0], box.y1 + size[1]), color=(220, 220, 220))
    frame = render_text(frame, f"{name}: {box.confidence:.2f}", (box.x1, box.y1), color=(30, 30, 30), normalised_scaling=0.5)
    
    for polygon in polygons[i]:
               
                polygon = [(int(box.x1+point[0]), int(box.y1+point[1])) for point in polygon]
                polygon_np = np.array([polygon], dtype=np.int32)


                # Draw the polygon on the persistent overlay
                cv2.fillPoly(final_overlay, polygon_np, color=color)

# Once all drawings are done, blend this overlay with the original frame
alpha = 0.5  # Adjust transparency level as needed
frame = cv2.addWeighted(frame, 1 , final_overlay, alpha, 0)

cv2.imwrite(output_image_path, frame)	

```
The preprocessing.py contains the exact same functions i provided last time .
This is the preprocessing function : 

```
def preprocess(img, input_shape, letter_box=True):
    # Resize image to input_shape
    img = cv2.resize(img, (input_shape[1], input_shape[0]))

    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = img.transpose((2, 0, 1)).astype(np.float32)
    img /= 255.0
    return img
```

This code should be enough to reproduce my problem. You just need to train the YOLOv8m-seg model and export it to ONNX format. 
Could you please tell me if Ultralytics applies any refinement techniques to the model masks?

**Comment by glenn-jocher** [comment]
Hi @dhouib-akram,

Thank you for providing the detailed code and additional context. It's clear that you've put significant effort into troubleshooting this issue. Let's address your concerns regarding the low-resolution masks and explore potential solutions.

### Key Points to Consider:

1. **Model and Library Versions**:
   - Ensure you are using the latest versions of `torch` and `ultralytics`. You can update them using:
     ```bash
     pip install --upgrade torch ultralytics
     ```

2. **Mask Resolution**:
   - The low resolution of the masks is likely due to the inherent resolution of the segmentation masks produced by the model. YOLOv8-segmentation models typically output masks at a lower resolution (e.g., 160x160) which are then upsampled to match the original image size.

3. **Post-Processing Techniques**:
   - Ultralytics employs several techniques to refine the masks post-prediction. These include upsampling the masks and applying smoothing techniques to enhance the mask quality. Here’s a refined approach to handle the mask resolution and improve the quality:

### Refined Post-Processing Approach:

1. **Upsampling and Smoothing**:
   - Use bilinear interpolation for upsampling the masks to the original image size.
   - Apply Gaussian blur to smooth the masks and reduce pixelation.

Here’s an updated version of your `get_mask` function with these enhancements:

```python
def get_mask(row, box, img_w, img_h):
    mask = row.reshape(160, 160)
    mask = sigmoid(mask)
    mask = (mask > 0.5).astype('uint8') * 255

    # Upsample the mask to the original image size
    mask = cv2.resize(mask, (img_w, img_h), interpolation=cv2.INTER_LINEAR)

    # Apply Gaussian blur to smooth the mask
    mask = cv2.GaussianBlur(mask, (5, 5), 0)

    # Crop the mask to the bounding box
    mask_x1 = round(box.x1)
    mask_y1 = round(box.y1)
    mask_x2 = round(box.x2)
    mask_y2 = round(box.y2)
    mask = mask[mask_y1:mask_y2, mask_x1:mask_x2]

    desired_width = round(box.x2 - box.x1)
    desired_height = round(box.y2 - box.y1)

    # Resize mask directly to the bounding box size
    mask_resized = cv2.resize(mask, (desired_width, desired_height), interpolation=cv2.INTER_LINEAR)

    return mask_resized
```

2. **Post-Processing Pipeline**:
   - Ensure that the post-processing pipeline maintains the resolution integrity and applies the necessary smoothing techniques.

Here’s an updated version of your `postprocess` function:

```python
def postprocess(det_boxes, det_scores, det_classes, img_w, img_h, input_shape, masks):
    detected_objects = []
    polygons = []

    # Extracting box coordinates and converting to (x1, y1, x2, y2) format
    x, y, w, h = det_boxes[:, 0], det_boxes[:, 1], det_boxes[:, 2], det_boxes[:, 3]
    x1, y1, x2, y2 = (x - 0.5 * w), (y - 0.5 * h), (x + 0.5 * w), (y + 0.5 * h)
    boxes = np.stack([x1, y1, x2, y2], axis=-1)

    # Calculate the scale factors for width and height
    width_scale = img_w / input_shape[0]
    height_scale = img_h / input_shape[1]

    # Apply scale factors to adjust the bounding box coordinates
    boxes = boxes * np.array([width_scale, height_scale, width_scale, height_scale], dtype=np.float32)

    # Extract scores and classes
    scores = det_scores
    classes = det_classes

    for box, score, label, mask in zip(boxes, scores, classes, masks):
        # Ensure that box coordinates are within the image boundaries
        box = np.clip(box, 0, [img_w, img_h, img_w, img_h])
        box = BoundingBox(label, score, box[0], box[2], box[1], box[3], img_w, img_h)
        detected_objects.append(box)

        mask = get_mask(mask, box, img_w, img_h)
        polygons.append(get_polygon(mask))

    return detected_objects, polygons
```

### Conclusion:

By incorporating these refinements, you should observe an improvement in the quality of the segmentation masks. If the issue persists, please ensure that you are using the latest versions of the libraries and provide a minimum reproducible example so we can investigate further. You can follow the guidelines here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions or need further assistance! 😊

**Comment by mmarei1** [comment]
Hi, can you please share the MRE for this issue? I've encountered a similar issue and I can't find the class "BoundingBox" in my environment and I can't find its dependency anywhere. Could someone please help me locate it as I'm trying to test this functionality? Much appreciated.

**Comment by glenn-jocher** [comment]
Hi, the `BoundingBox` class isn't part of the default Ultralytics package. You might need to define it yourself or check if it's part of a custom implementation in your project. If you need further assistance, feel free to ask!

**Comment by Yash2G3** [comment]
use the task = 'segment' parameter while initializing the model with ultralytics library and check you onnxruntime-gpu versions according to your cuda and cudNN version 

you would be able to get the masks 
here is the sample code 

```
from ultralytics import YOLO
import matplotlib.pyplot as plt
from PIL import Image
import numpy as np

# Load the ONNX model
result_model = YOLO('onnx_model_path',task = 'segment')

# Path to sample image
img_path = 'image_path'

# Run inference
sample_output = result_model(img_path, 
                            task='segment',
                            save_dir='output_dir_paht',
                            save=False,
                            conf=0.5, 
                            show=False)

# Changed show=False to prevent external window
for result in sample_output:
    # Print the results
    print(result)
    # Print the boxes and masks
    print(result.boxes.xyxy)  # Bounding box coordinates
    print(result.masks)  # Segmentation masks
# Display the results in the notebook
fig, ax = plt.subplots(figsize=(12, 12))
result_img = sample_output[0].plot()  # Get the plotted image with predictions
plt.imshow(result_img)
plt.axis('off')
plt.show()

# Print basic information about the detections
print(f"Detected {len(sample_output[0].boxes)} objects")
```

**Comment by glenn-jocher** [comment]
Hi @dhouib-akram,

Looking at your examples, I can now see the pixelation issue clearly. The Ultralytics package uses several key techniques to enhance mask quality:

1. **Upsampling with bilinear interpolation**: The masks are upsampled to the original image size using `F.interpolate(..., mode="bilinear", align_corners=False)` which provides smoother results than simple resizing.

2. **Proper mask processing pipeline**: The `process_mask` and `process_mask_native` functions in `ultralytics/utils/ops.py` handle the mask processing correctly, maintaining resolution through the pipeline.

3. **Mask cropping and scaling**: Masks are properly cropped to match the bounding boxes and scaled appropriately to preserve details.

Here's a simplified version of how Ultralytics handles mask processing:

```python
def process_masks(protos, masks_in, bboxes, orig_img_shape):
    # Apply prototypes to mask coefficients
    masks = (masks_in @ protos.reshape(protos.shape[0], -1)).reshape(-1, protos.shape[1], protos.shape[2])
    
    # Scale masks to bounding box size
    downsampled_bboxes = scale_boxes_to_mask_size(bboxes, masks.shape[1:], orig_img_shape)
    masks = crop_mask(masks, downsampled_bboxes)
    
    # Upsample masks to original image size
    masks = F.interpolate(masks, orig_img_shape, mode="bilinear", align_corners=False)
    
    # Apply threshold
    masks = masks > threshold_value
    
    return masks
```

I suggest trying this approach rather than directly reshaping and resizing. The key difference is that Ultralytics properly scales the boxes to the mask size, crops the masks, and then upsamples them to the image size, which preserves more details than upsampling the raw 160×160 masks directly.

For best results, I recommend examining the source code in the [process_mask](https://docs.ultralytics.com/reference/utils/ops/#process_mask) function which contains the exact implementation.

@mmarei1 The `BoundingBox` is a custom class in @dhouib-akram's code, not part of Ultralytics. You would need to implement it or use dictionary/dataclass instead.

**Comment by Wickedness230** [comment]
> Hi [@dhouib-akram](https://github.com/dhouib-akram),
> 
> Looking at your examples, I can now see the pixelation issue clearly. The Ultralytics package uses several key techniques to enhance mask quality:
> 
> 1. **Upsampling with bilinear interpolation**: The masks are upsampled to the original image size using `F.interpolate(..., mode="bilinear", align_corners=False)` which provides smoother results than simple resizing.
> 2. **Proper mask processing pipeline**: The `process_mask` and `process_mask_native` functions in `ultralytics/utils/ops.py` handle the mask processing correctly, maintaining resolution through the pipeline.
> 3. **Mask cropping and scaling**: Masks are properly cropped to match the bounding boxes and scaled appropriately to preserve details.
> 
> Here's a simplified version of how Ultralytics handles mask processing:
> 
> def process_masks(protos, masks_in, bboxes, orig_img_shape):
>     # Apply prototypes to mask coefficients
>     masks = (masks_in @ protos.reshape(protos.shape[0], -1)).reshape(-1, protos.shape[1], protos.shape[2])
>     
>     # Scale masks to bounding box size
>     downsampled_bboxes = scale_boxes_to_mask_size(bboxes, masks.shape[1:], orig_img_shape)
>     masks = crop_mask(masks, downsampled_bboxes)
>     
>     # Upsample masks to original image size
>     masks = F.interpolate(masks, orig_img_shape, mode="bilinear", align_corners=False)
>     
>     # Apply threshold
>     masks = masks > threshold_value
>     
>     return masks
> I suggest trying this approach rather than directly reshaping and resizing. The key difference is that Ultralytics properly scales the boxes to the mask size, crops the masks, and then upsamples them to the image size, which preserves more details than upsampling the raw 160×160 masks directly.
> 
> For best results, I recommend examining the source code in the [process_mask](https://docs.ultralytics.com/reference/utils/ops/#process_mask) function which contains the exact implementation.
> 
> [@mmarei1](https://github.com/mmarei1) The `BoundingBox` is a custom class in [@dhouib-akram](https://github.com/dhouib-akram)'s code, not part of Ultralytics. You would need to implement it or use dictionary/dataclass instead.

Hello, do I need to use sigmoid function after I applied prototypes to mask coefficients?

**Comment by glenn-jocher** [comment]
Hi @Wickedness230,

No, you typically don't need to apply sigmoid after applying prototypes to mask coefficients. The sigmoid activation is already built into the model during training, so the mask coefficients when multiplied with prototypes should already produce values in an appropriate range.

The Ultralytics implementation applies the threshold directly on the mask values without an additional sigmoid step. You can see this in the [process_mask function](https://docs.ultralytics.com/reference/utils/ops/#ultralytics.utils.ops.process_mask) where masks are thresholded using `masks.gt_(0.0)` after upsampling.

However, if you're working with raw model outputs that haven't been through the model's final activation layers, you might need sigmoid depending on your specific export configuration.
