### ISSUE TITLE
Image URLs without file extension lead to 500 error & server crash

### ISSUE THREAD

**Issue by emilio-balda** [ultralytics/ultralytics#13520]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

I sent a CURL request to the inference server with the following image URL "https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/be2cf638-7d2b-46f6-ab89-05be842adf78"

- The response was a 502 Server error
- After that, any request to inference server (with same model ID) would get timeout

The issue comes from this line https://github.com/ultralytics/ultralytics/blob/fe68cd8bd1f3edddd0afaf3d389a46fdff9e900d/ultralytics/data/build.py#L153 
The ultralytics library thinks the url does not correspond to a file because it doesn't have a file extension. It treats the url as a webcam stream and gets stuck into an infinite loop.

You can reproduce this error locally. See script below.

### Minimal Reproducible Example

```python
from ultralytics import YOLO

# Load a pretrained YOLOv8n model
model = YOLO("yolov8n.pt")

# Define remote image or video URL
source = "https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/be2cf638-7d2b-46f6-ab89-05be842adf78"

# Run inference on the source
results = model(source)  # list of Results objects
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hi there,

Thank you for bringing this to our attention and for providing a detailed report along with a reproducible example! This is very helpful. 😊

It appears that the issue stems from the URL lacking a file extension, which causes the library to misinterpret it as a webcam stream. This is indeed a bug that we need to address.

Before we proceed, could you please confirm that you are using the latest versions of both `torch` and `ultralytics`? You can update your packages using the following commands:

```bash
pip install --upgrade torch ultralytics
```

Once updated, please try running your script again to see if the issue persists. If it does, we will investigate further.

In the meantime, as a workaround, you might consider downloading the image locally and then running the inference on the local file. Here’s a quick example of how you could do this:

```python
import requests
from ultralytics import YOLO

# Load a pretrained YOLOv8n model
model = YOLO("yolov8n.pt")

# Download the image
url = "https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/be2cf638-7d2b-46f6-ab89-05be842adf78"
response = requests.get(url)
with open("temp_image.jpg", "wb") as file:
    file.write(response.content)

# Run inference on the downloaded image
results = model("temp_image.jpg")  # list of Results objects

# Display results
results[0].show()
```

This should help you continue your work while we look into a more permanent fix for the URL handling issue.

Thank you for your patience and for contributing to the improvement of our library. If you have any further questions or updates, please feel free to share them here.

**Comment by emilio-balda** [comment]
Hi,

The issue happened on the sever side when using Ultralytics HUB. So the Ultralytics & Torch versions are the ones in Ultralytics' infraestructure.

You can replicate the error like this
```
curl -X POST "https://api.ultralytics.com/v1/predict/<your-model-id>" \
     -H "Content-Type: multipart/form-data" \
     -H "x-api-key: <your-api-key>" \
     -F "size=640" \
     -F "confidence=0.25" \
     -F "iou=0.45" \
     -F "url=https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/be2cf638-7d2b-46f6-ab89-05be842adf78)"
```

The code snippet I provided is a way to replicate the issue locally. I originally ran it with these versions:
```
ultralytics               8.2.28
torch                     2.3.0
```

I just upgraded those libraries to their latest versions and I can confirm that the issue persists.

I can see where the issue is coming from, on the `main` branch of Ultralytics' GitHub repository. It is here https://github.com/ultralytics/ultralytics/blob/f92bd9dea119715ced09d0b6ca6241cdadb8397b/ultralytics/data/build.py#L153

**Comment by glenn-jocher** [comment]
@emilio-balda hi there,

Thank you for the detailed follow-up and for providing the cURL command to replicate the issue on the Ultralytics HUB. This is very helpful! 😊

I understand that the issue occurs on the server side when using the Ultralytics HUB Inference API. Given that you've already confirmed the bug persists with the latest versions of `ultralytics` and `torch`, we'll need to investigate further.

The problem seems to be related to how URLs without file extensions are handled, causing the library to misinterpret them as webcam streams. This indeed appears to be a bug in the URL handling logic.

To help us address this issue more effectively, I've noted the specific line in the codebase that you mentioned:
https://github.com/ultralytics/ultralytics/blob/f92bd9dea119715ced09d0b6ca6241cdadb8397b/ultralytics/data/build.py#L153

We will look into this and work on a fix. In the meantime, as a temporary workaround, you might consider downloading the image locally and running the inference on the local file, as shown in the earlier example.

Thank you for your patience and for bringing this to our attention. If you have any further questions or updates, please feel free to share them here. We appreciate your support in improving our library!
