### ISSUE TITLE
The ray tune result is incomplete

### ISSUE THREAD

**Issue by Eastar-star** [ultralytics/ultralytics#13538]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

（1）#YOLOv8 ray tune should generate all the files below.
runs/
└── detect/
    ├── train1/
    ├── train2/
    ├── ...
    └── tune/
        ├── best_hyperparameters.yaml
        ├── best_fitness.png
        ├── tune_results.csv
        ├── tune_scatter_plots.png
        └── weights/
            ├── last.pt
            └── best.pt
（2）#Run the following code
But after running the following code.
from ray import tune 
from ultralytics import YOLO
model = YOLO("yolov8n.pt")
result_grid = model.tune(data="coco128.yaml",
                         space={"lr0": tune.uniform(1e-5, 1e-1)},
                         epochs=5,
                         use_ray=True)
（3）#Generate results that do not match the official website
The following results were obtained.
runs/
└── detect/
    ├── train1/
    ├── train2/
    ├── ...
    └── tune/
However, the expected best_hyperparameters.yaml, best_fitness.png, tune_results.csv, tune_scatter_plots.png, as well as the weights/last. pt and weights/best. pt files were not generated in the tune directory

**Comment by glenn-jocher** [comment]
@Eastar-star hi there,

Thank you for reaching out and providing detailed information about the issue you're encountering with Ray Tune and YOLOv8. Let's work through this together to identify the root cause and find a solution.

Firstly, could you please confirm that you are using the latest versions of both `torch` and `ultralytics`? Ensuring that you have the most recent versions can often resolve unexpected issues. You can update your packages using the following commands:

```bash
pip install --upgrade torch ultralytics
```

Next, it's crucial to have a minimum reproducible example to help us diagnose the problem effectively. If you haven't already, please provide a snippet of your code that reproduces the issue. This will enable us to investigate further. You can find more information on creating a minimum reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Regarding the missing files in the `tune` directory, it seems like the expected outputs (`best_hyperparameters.yaml`, `best_fitness.png`, `tune_results.csv`, `tune_scatter_plots.png`, and the weights) are not being generated. This could be due to several reasons, such as the configuration of the tuning process or the specific settings used.

Here are a few steps you can take to troubleshoot and potentially resolve the issue:

1. **Check the Ray Tune Logs**: Ensure that there are no errors or warnings in the Ray Tune logs that might indicate why these files are not being generated.

2. **Verify the Configuration**: Ensure that your `tune()` method is correctly configured. For example, make sure that the `epochs` parameter is set appropriately and that the `space` dictionary is correctly defined.

3. **Inspect the Results**: After running the tuning process, you can inspect the results programmatically to ensure that the tuning process completed successfully. Here’s an example of how you can do this:

    ```python
    from ultralytics import YOLO

    # Load a YOLOv8n model
    model = YOLO("yolov8n.pt")

    # Start tuning hyperparameters for YOLOv8n training on the COCO8 dataset
    result_grid = model.tune(data="coco128.yaml", use_ray=True)

    # Check the results
    if result_grid.errors:
        print("One or more trials failed!")
    else:
        print("No errors!")
    
    for i, result in enumerate(result_grid):
        print(f"Trial #{i}: Configuration: {result.config}, Last Reported Metrics: {result.metrics}")
    ```

4. **Manual Inspection**: Manually inspect the `runs/detect/tune` directory to see if any files are being generated and if they contain the expected data.

If the issue persists after these steps, please provide the additional details requested, and we will continue to assist you in resolving this matter.

Thank you for your patience and cooperation. We look forward to helping you get this resolved! 😊
