### ISSUE TITLE
Difference between hub and local performance

### ISSUE THREAD

**Issue by cmilanes93** [ultralytics/ultralytics#13563]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Hello, recently I trained a model using the Ultralytics hub, and everything went well. I used the preview option to examine the performance on an image X, and it was excellent.

The problem arises when I download the model and use it locally on the same image X; the results are not as good, meaning there are some labels it fails to predict.

Any idea what could be the issue? Thanks in advance.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Burhan-Q** [comment]
@cmilanes93 I ran a quick test with Ultralytics HUB with the car parts segmentation dataset, and trained a model with the default settings which can be viewed on [HUB](https://hub.ultralytics.com/models/IQaCWW15uX0ftNPsXj0i). I downloaded the model and ran it locally using [this image](https://s3.amazonaws.com/3ge.shared.assets/things-to-know/toyota/v1/ttk-image-body_structure_02_04-1.png).

The results between the HUB preview and running locally _are_ different, but not in a drastic way. In fact, the model that runs locally seems to do slightly better, as it included one additional detection (but that could be a limitation of how many detections are show in the UI). 

## HUB results

![image](https://github.com/ultralytics/ultralytics/assets/62214284/7ced438c-111c-439a-aba3-2e24a07eb12e)

```
[
       [0.883, wheel], 
       [0.81, back_left_light],
       [0.778, wheel],
       [0.719, front_left_door],
       [0.601, back_left_door],
       [0.589, back_left_door],
       [0.427, back_right_light],
       [0.372, left_mirror],
]
```

## Local results

```
array([
       [0.886, wheel],
       [0.820, back_left_light],
       [0.726, front_left_door],
       [0.632, wheel],
       [0.594, back_left_door],
       [0.579, back_left_door],
       [0.408, back_right_light],
       [0.389, left_mirror],
       [0.279, wheel]  # <-- not included with HUB preview
], dtype='<U32')
```

![image](https://github.com/ultralytics/ultralytics/assets/62214284/c0c1e427-f2eb-4657-8494-8ffb5a560104)

<details><summary>Code</summary>
<p>

```py
import numpy as np

from ultralytics import YOLO

model = YOLO(rf"weights/2024-06-13_car_parts-seg.pt", task="segment")

# HUB model :: https://hub.ultralytics.com/models/IQaCWW15uX0ftNPsXj0i

img = "https://s3.amazonaws.com/3ge.shared.assets/things-to-know/toyota/v1/ttk-image-body_structure_02_04-1.png"

results = model.predict(img, conf=0.25, iou=0.45, imgsz=640)  # ensure same settings as HUB inference
names = model.names.copy()

np.stack(  # used to display names/confidence values
    zip(
        [round(p, 3) for p in results[0].boxes.data[..., -2].tolist()],
        [names[int(c)] for c in results[0].boxes.data[..., -1].tolist()], 
    )
)
```

</p>
</details> 

I think should be _some_ expectation that the results are going to be different as the hardware that the inference is run on for HUB versus locally are different. Additionally it's important to remember that you'll need to make sure that the settings run locally match those for HUB. There _could be_ (I'm not certain) more or different pre-processing steps done on HUB that would not run locally on your machine, so this too might account for variations in results (positively or negatively). As for instance if I save a copy of the image locally in JPEG format and include 60% compression (which would be a reasonable step for a web interface to help with speed/responsiveness), the results change to:

```
array([
       [0.878, wheel],
       [0.790, wheel],
       [0.729, back_left_light],
       [0.702, front_left_door],
       [0.615, back_left_door],
       [0.604, back_left_door],
       [0.401, back_right_light],
       [0.329, left_mirror],
       [0.326, back_glass]
], dtype='<U32')
```

Perhaps @sergiuwaxmann could help provide some insight as well from a HUB perspective. I will say that as far as I'm aware, the HUB preview function should be considered a demonstration and not an indicator of model performance. It's more of a sanity check and quick demo feature, than something to be relied on to indicate how well a model will or will not perform.

**Comment by cmilanes93** [comment]
@Burhan-Q  Thank you very much, you have been very collaborative, and your insights are truly excellent.

Is there any way to know for sure if there is any specific preprocessing in the HUB?

I asked this question once before, and someone, I don’t remember who, told me that there wasn’t, so it would be good to clarify. Thank you very much.

P.S. In my case, the predictions from the HUB are much better, haha.

**Comment by Burhan-Q** [comment]
@cmilanes93 happy I can help! Sergiu is offline for the day, but he would probably be able to answer more definitively about any image preprocessing that might happen. I took a look at what I _think_ could be the code for the preview, and if my guess was correct, then there are no preprocessing steps I could see beyond what a normal YOLO model would perform.

If I'm correct, then it's likely going to be mostly a difference in hardware. I suspect that the HUB inference runs on CPU and not GPU, since CPUs are much more available. That at differences in python versions or package libraries could play a factor as well (I'm not certain as I have not tested). Additionally rounding errors across different OSes can add up quite a lot, and I recall an issue being opened where there were significant differences due to using annotations with more than 6 significant digits on Linux versus Windows. 

This is pure speculation from here forward, so if it doesn't apply to you it's just for anyone else reading. I would guess that if the model was trained on a large dataset with excellent annotations, the minor differences in rounding errors between hardware or software package versions, would make little difference in performance. A model trained on a smaller dataset, even with great annotations, might perform differently in different environments based on the fact that the model wasn't able to update its parameters significantly. A way to think about this is that it could mean the model weights may retain a lot of randomness or noise, and when used under different conditions, the output might be slightly different.

**Comment by cmilanes93** [comment]
@Burhan-Q thanks again for all the info

**Comment by sergiuwaxmann** [comment]
@cmilanes93 @Burhan-Q As you suspected, we are not doing any preprocessing in HUB.

We are running HUB inference on CPU, and the difference may be due to the hardware (as Burhan mentioned).

This code snippet reproduces the HUB inference results exactly (for me):
```python
from ultralytics import YOLO

model = YOLO("best.pt")
results = model.predict("predict.jpg")

response = []
for box in results[0].boxes:
    r = {
        "class": int(box.cls),
        "name": model.names[int(box.cls)],
        "confidence": float(box.conf[0]),
        "xcenter": float(box.xywhn[0][0]),
        "ycenter": float(box.xywhn[0][1]),
        "width": float(box.xywhn[0][2]),
        "height": float(box.xywhn[0][3]),
    }
    response.append(r)
```
Hope it helps!
