### ISSUE TITLE
scipy or lap.lapjv?

### ISSUE THREAD

**Issue by flinzhao** [ultralytics/ultralytics#13583]
### Search before asking

- [ ] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In the `linear_assignment` function of `ultralytics/trackers/utils/matching.py`, which is faster, **scipy** or **lap.lapjv**? I had ChatGPT write a script to test the speed, and I found that scipy is faster. Does this mean it is more appropriate to set the use_lap parameter to False in `linear_assignment`?
This is the test script：
```python
import numpy as np
import scipy.optimize
import lap
import time

def linear_assignment_scipy(cost_matrix: np.ndarray, thresh: float) -> tuple:
    x, y = scipy.optimize.linear_sum_assignment(cost_matrix)  # row x, col y
    matches = np.asarray([[x[i], y[i]] for i in range(len(x)) if cost_matrix[x[i], y[i]] <= thresh])
    if len(matches) == 0:
        unmatched_a = list(np.arange(cost_matrix.shape[0]))
        unmatched_b = list(np.arange(cost_matrix.shape[1]))
    else:
        unmatched_a = list(set(np.arange(cost_matrix.shape[0])) - set(matches[:, 0]))
        unmatched_b = list(set(np.arange(cost_matrix.shape[1])) - set(matches[:, 1]))
    return matches, unmatched_a, unmatched_b

def linear_assignment_lap(cost_matrix: np.ndarray, thresh: float) -> tuple:
    _, x, y = lap.lapjv(cost_matrix, extend_cost=True, cost_limit=thresh)
    matches = [[ix, mx] for ix, mx in enumerate(x) if mx >= 0]
    unmatched_a = np.where(x < 0)[0]
    unmatched_b = np.where(y < 0)[0]
    return matches, unmatched_a, unmatched_b

def main():
    # Generate random cost matrices of different sizes
    sizes = [10, 50, 100, 200, 500]
    thresh = 100  # example threshold
    
    for size in sizes:
        cost_matrix = np.random.rand(size, size) * 100

        # Test scipy.optimize.linear_sum_assignment
        start_time = time.time()
        matches_scipy, unmatched_a_scipy, unmatched_b_scipy = linear_assignment_scipy(cost_matrix, thresh)
        end_time = time.time()
        time_scipy = end_time - start_time
        print(f"Scipy (size {size}): {time_scipy:.6f} seconds")

        # Test lap.lapjv
        start_time = time.time()
        matches_lap, unmatched_a_lap, unmatched_b_lap = linear_assignment_lap(cost_matrix, thresh)
        end_time = time.time()
        time_lap = end_time - start_time
        print(f"LAP (size {size}): {time_lap:.6f} seconds")

if __name__ == "__main__":
    main()
```
This is the output:
```
Scipy (size 10): 0.000059 seconds
LAP (size 10): 0.000147 seconds
Scipy (size 50): 0.000103 seconds
LAP (size 50): 0.000213 seconds
Scipy (size 100): 0.000424 seconds
LAP (size 100): 0.000955 seconds
Scipy (size 200): 0.001190 seconds
LAP (size 200): 0.004794 seconds
Scipy (size 500): 0.006916 seconds
LAP (size 500): 0.028149 seconds
```

### Additional

I am using `scipy` version 1.9.3, `lap` version 0.4.0, the system is CentOS 7.9, and the Python version is 3.10.14.

**Comment by glenn-jocher** [comment]
Hello @flinzhao,

Thank you for your detailed question and for providing a comprehensive test script! It's great to see such thorough investigation.

From your results, it appears that `scipy.optimize.linear_sum_assignment` is indeed faster than `lap.lapjv` for the cost matrices you tested. This aligns with some observations in the community, although the performance can vary depending on the specific use case and the size of the cost matrices.

The `linear_assignment` function in `ultralytics/trackers/utils/matching.py` defaults to using `lap.lapjv` because it can sometimes offer better performance on larger and more complex matrices, and it has been a reliable choice in various tracking scenarios. However, your findings suggest that for smaller matrices, `scipy` might be more efficient.

Here's a summary of your test results for quick reference:
```
Scipy (size 10): 0.000059 seconds
LAP (size 10): 0.000147 seconds
Scipy (size 50): 0.000103 seconds
LAP (size 50): 0.000213 seconds
Scipy (size 100): 0.000424 seconds
LAP (size 100): 0.000955 seconds
Scipy (size 200): 0.001190 seconds
LAP (size 200): 0.004794 seconds
Scipy (size 500): 0.006916 seconds
LAP (size 500): 0.028149 seconds
```

Given these results, you might consider setting `use_lap=False` in your specific application if you consistently observe better performance with `scipy`. However, it's important to test this in the context of your full application to ensure that the change does not negatively impact other aspects of performance or accuracy.

If you decide to make this change, you can adjust the `linear_assignment` function call in your code as follows:
```python
matches, unmatched_a, unmatched_b = linear_assignment(cost_matrix, thresh, use_lap=False)
```

For further details on the `linear_assignment` function and other utilities, you can refer to the [Ultralytics documentation on matching utilities](https://docs.ultralytics.com/reference/trackers/utils/matching/).

If you encounter any issues or have further questions, feel free to reach out. We're here to help!
