### ISSUE TITLE
RuntimeError: scatter(): Expected dtype int64 for index

### ISSUE THREAD

**Issue by 3232731490** [ultralytics/ultralytics#13590]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://github.com/ultralytics/ultralytics/assets/75670203/824bf2e8-9455-4ddf-abbd-8a37fa283730)
How did this error occur? Why did this bug appear after training for 75 epochs, while the first 74 epochs trained normally?

### Additional

When training on other datasets, everything runs normally without this bug. However, after adding some additional datasets, this error occurs, and it doesn't happen right away but rather after 75 epochs of training. How can I fix it?

**Comment by glenn-jocher** [comment]
@3232731490 hi there,

Thank you for reaching out and providing details about the issue you're encountering. The error message `RuntimeError: scatter(): Expected dtype int64 for index` typically indicates a problem with the data type of indices used in a scatter operation, which should be of type `int64`.

To help us investigate this further, could you please provide a minimum reproducible code example? This will allow us to reproduce the bug on our end and identify the root cause. You can refer to our guide on creating a minimum reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the most recent versions of `torch` and `ultralytics`. You can upgrade your packages using the following commands:

```bash
pip install --upgrade torch
pip install --upgrade ultralytics
```

Once you've updated the packages, try running your training again to see if the issue persists.

Given that the error occurs after adding additional datasets and only after 75 epochs, it might be related to specific data samples or the way the data is being processed. If possible, please share details about the datasets you added and any preprocessing steps you are performing.

Looking forward to your response so we can assist you further!

**Comment by 3232731490** [comment]
# Bug description:
When I train the model on certain specific datasets, a type mismatch error occurs at a certain epoch. The datasets where this error occurs are the VEDAI dataset and the FLIR dataset. Both datasets are multispectral image datasets. However, I have tried training using only infrared data as well as training with both modalities simultaneously, and the error still occurs.Additionally, I can train normally on some datasets, such as LLVIP and KAIST.

VEDAI dataset link: https://downloads.greyc.fr/vedai/
FLIR dataset link: https://pan.baidu.com/s/1z2GHVD3WVlGsVzBR1ajSrQ?pwd=qwer

Additionally, this error seems to occur only with certain batch sizes. When training on the VEDAI dataset with batch_size=4, the error appears at the 6th epoch, but with batch_size=16, the error does not occur. When training on the FLIR dataset with batch_size=16, the error appears at the 75th epoch.

# MRE
```python
from ultralytics import YOLO

if __name__ == '__main__':
    model = YOLO(r"ultralytics/cfg/models/v8/yolov8.yaml")
    model.train(data=r"ultralytics/cfg/datasets/VEDAI.yaml", epochs=200, batch = 4,cls_loss = None,imgsz = 1024,mosaic = 1.)  # 训练
```

# Error message
RuntimeError: scatter(): Expected dtype int64 for index 

# Dependencies
- ultralytics=8.0.238
- torch=2.2.2

**Comment by glenn-jocher** [comment]
Hi @3232731490,

Thank you for providing detailed information about the issue you're encountering. It seems like the type mismatch error is related to specific datasets and batch sizes, which can be tricky to diagnose without a closer look.

### Steps to Resolve

1. **Minimum Reproducible Example (MRE):**
   The code snippet you provided is helpful, but to further investigate, we need a complete minimum reproducible example. This includes the dataset configuration files (`VEDAI.yaml` and `FLIR.yaml`) and any custom preprocessing steps you might be using. Please refer to our guide on creating a minimum reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

2. **Package Versions:**
   Ensure you are using the latest versions of `torch` and `ultralytics`. You can upgrade your packages using the following commands:
   ```bash
   pip install --upgrade torch
   pip install --upgrade ultralytics
   ```
   After upgrading, try running your training again to see if the issue persists.

3. **Dataset Specifics:**
   Since the error occurs with specific datasets (VEDAI and FLIR), it might be related to the data format or preprocessing steps. Ensure that all indices used in scatter operations are of type `int64`. You can check and convert the data types if necessary.

### Example Code to Check Data Types
Here's an example of how you can ensure that your indices are of type `int64`:
```python
import torch

# Example tensor
indices = torch.tensor([1, 2, 3], dtype=torch.int32)

# Convert to int64
indices = indices.to(torch.int64)
```

### Further Assistance
If the issue persists after following the above steps, please share more details about the dataset configurations and any custom preprocessing steps. This will help us reproduce the issue on our end and provide a more accurate solution.

Thank you for your cooperation, and we look forward to resolving this issue together! 😊
