### ISSUE TITLE
Add DirectML support with new release of torch-directml

### ISSUE THREAD

**Issue by RobbStarkAustria** [ultralytics/ultralytics#13620]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Yesterday the new version of torch-directml is released. [torch-directml-0.2.2.dev240614](https://github.com/microsoft/DirectML/releases/tag/torch-directml-0.2.2.dev240614) enables torch to run any capable DirectX12 compatible hardware. In my opinion, it should be possible to use pytorch on a number of other GPUs, especially AMD accelerators. I would therefore like to ask the team to include pytorch-dml in the YoloV8 framework.

Thank you in advance as user of both a NIVIDU-GPU on desktop and an AMD-GPU in laptop.

Olaf

### Use case

Extension of the 'device' parameter by the option 'dml' to force the use of a DirectX12 accelerator.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@RobbStarkAustria hi Olaf,

Thank you for your suggestion and for providing the link to the new release of `torch-directml`. The idea of extending YOLOv8 to support DirectML is indeed intriguing and could potentially benefit users with a wider range of GPU hardware, including AMD accelerators.

To proceed, we need to ensure that the integration is seamless and does not introduce any unexpected issues. If you have any initial code or examples demonstrating how `torch-directml` can be integrated with YOLOv8, it would be greatly appreciated. This will help us better understand the implementation and testing requirements.

In the meantime, we encourage you to experiment with `torch-directml` on your setup and share any findings or issues you encounter. This collaborative effort will be invaluable in assessing the feasibility and performance of DirectML support in YOLOv8.

Thank you for your continued support and contributions to the YOLO community!

**Comment by Gurneet1928** [comment]
> @RobbStarkAustria hi Olaf,
> 
> Thank you for your suggestion and for providing the link to the new release of `torch-directml`. The idea of extending YOLOv8 to support DirectML is indeed intriguing and could potentially benefit users with a wider range of GPU hardware, including AMD accelerators.
> 
> To proceed, we need to ensure that the integration is seamless and does not introduce any unexpected issues. If you have any initial code or examples demonstrating how `torch-directml` can be integrated with YOLOv8, it would be greatly appreciated. This will help us better understand the implementation and testing requirements.
> 
> In the meantime, we encourage you to experiment with `torch-directml` on your setup and share any findings or issues you encounter. This collaborative effort will be invaluable in assessing the feasibility and performance of DirectML support in YOLOv8.
> 
> Thank you for your continued support and contributions to the YOLO community!


Hey @glenn-jocher , I have been following directml from past few months and I think I can implement it in yolov8 model. Let me see what I can do about it. Will it be beneficial to use directml with Yolo especially for AMD GPUs ?

**Comment by glenn-jocher** [comment]
Hi @Gurneet1928,

That's fantastic to hear that you're interested in implementing DirectML with YOLOv8! Leveraging DirectML can indeed be beneficial, especially for users with AMD GPUs or other DirectX12 compatible hardware. It can potentially broaden the accessibility and performance of YOLOv8 across a wider range of devices.

To ensure a smooth integration, here are a few steps you might consider:

1. **Experimentation**: Start by experimenting with `torch-directml` on your local setup. This will help you understand any potential challenges or limitations.
2. **Integration**: Implement DirectML support in YOLOv8 by extending the `device` parameter to include 'dml'. This will allow users to specify DirectML as their preferred backend.
3. **Testing**: Thoroughly test the integration to ensure it works seamlessly with existing functionalities and does not introduce any regressions.
4. **Documentation**: Update the documentation to guide users on how to enable and use DirectML with YOLOv8.

If you encounter any issues or have specific questions during the implementation, feel free to share them here. The community and the Ultralytics team are always here to help!

Looking forward to your contributions and findings. Your efforts will undoubtedly enhance the versatility and performance of YOLOv8 for many users. 🚀

**Comment by Gurneet1928** [comment]
@glenn-jocher 
Sure, already on it actually.

1. For the experimentation part, already using the DirectML on my local setup, so no issues with that. Infact, the microsoft shared YOLOv3 + DirectML sample works charm.
2. Trying to extend the device parameters in torch_utils.py file, stuck here actually because it isn't responding to the changes made to the file.
3. Testing to be done
4. Documentation to be done. 

Let me know if you can help in 2nd step. 
Thank you

**Comment by glenn-jocher** [comment]
Hi @Gurneet1928,

It's great to hear about your progress with integrating DirectML into YOLOv8! Your steps so far sound promising. Here are a few suggestions to help you with the second step and address the runtime errors you're encountering:

1. **Extending Device Parameters**: In `torch_utils.py`, ensure that the device selection logic correctly identifies and initializes the DirectML device. You might want to add a specific check for 'dml' and handle it accordingly. Here's a small snippet to guide you:

    ```python
    import torch_directml

    def select_device(device=''):
        if device == 'dml':
            return torch_directml.device()
        else:
            return torch.device(device)
    ```

2. **Runtime Errors**: The runtime errors within the PyTorch neural network layers could be due to compatibility issues or unsupported operations in DirectML. To debug this:
    - Ensure you are using the latest versions of `torch` and `torch-directml`.
    - Check the specific layers or operations causing the errors and see if there are any known issues or workarounds in the [torch-directml documentation](https://github.com/microsoft/DirectML).
    - Simplify the model to isolate the problematic layers and test them individually.

3. **Documentation**: Once you have a stable implementation, updating the documentation will be crucial. Include instructions on how to enable DirectML, any known limitations, and troubleshooting tips.

Feel free to share specific error messages or code snippets if you need more targeted assistance. Your efforts are greatly appreciated, and I'm sure the community will benefit from this enhancement. Keep up the great work! 🚀

**Comment by Gurneet1928** [comment]
@glenn-jocher  Thanks for the suggestion.

So, now I tried to run the inferences not from CLI but from python notebook using the clone repo (not the pip installed ultralytics). I individually imported predict.py file. This seems to be working and accepting the DirectML. Tried to inference on a 30sec video, the DirectML uses 22.9s whereas CPU takes 26.5s to inference the whole 750 frames. Added the screenshot as well. 

## CPU Output
![cpu](https://github.com/ultralytics/ultralytics/assets/68916061/9945726f-83bc-4c62-8cd7-384de2bb9615)

## Using DirectML
![dml_output](https://github.com/ultralytics/ultralytics/assets/68916061/068b6959-814b-42d6-950a-65406e4d3f31)


Another thing I noted is that, sometimes results are inconsistent between CPU and DML. Not sure why though, but I have a theory actually. DML shows two device_counts. These can be (CPU,GPU) pair or a (GPU,GPU) [dedicated,integrated] pair. In any case, the dedicated GPU and CPU are considerably slower than integrated GPU, so the results should be better in the latter.

**Comment by glenn-jocher** [comment]
Hi @Gurneet1928,

Thank you for sharing your detailed observations and results! It's great to see that you've made significant progress with DirectML integration and have provided comparative performance metrics. 🎉

To address the inconsistencies between CPU and DirectML results, here are a few suggestions:

1. **Device Selection**: Ensure that the correct device is being selected for DirectML. You can explicitly specify the device to avoid any ambiguity. For example:
    ```python
    import torch_directml

    device = torch_directml.device()
    model.to(device)
    ```

2. **Reproducibility**: If possible, please provide a minimum reproducible code example that demonstrates the inconsistencies. This will help us investigate the issue more effectively. You can refer to our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.

3. **Version Check**: Verify that you are using the latest versions of `torch`, `torch-directml`, and `ultralytics`. If not, please upgrade and try again:
    ```bash
    pip install --upgrade torch ultralytics
    ```

4. **Debugging**: To further debug the inconsistencies, you might want to log the device properties and ensure that the same device is being used consistently across different runs.

If you continue to experience issues, please share the specific code snippets and any error messages you encounter. This will help us provide more targeted assistance.

Thank you for your contributions and for helping to enhance YOLOv8's compatibility with a broader range of hardware. Your efforts are greatly appreciated by the community! 🚀

**Comment by Gurneet1928** [comment]
Hey @glenn-jocher .

One more promising update from my side. 
A problem popped while using the "train.py" file, but seems to be resolved now, since the file was only accepting **["cpu","cuda","mps"]** to its device list. Added **"dml"** into the list and now it works. The training now utilizes the GPU properly (visible from task manager). 

Regarding the **DML device count issue**, it’s interesting to note that DML prioritizes the dedicated GPU over the integrated GPU, resulting in a **[GPU,GPU] pair (Dedicated,Integrated).**

## Training Results on "yolov8n-cls" Model with "mnist" Data for 1 Epoch

### Devices used: 

1. **CPU - Ryzen 5 6500H**
   - Performance: ~1.3-1.5it/s
   - Utilizes default arguments.

![5600h_local](https://github.com/ultralytics/ultralytics/assets/68916061/ccc883da-e803-4ec6-8901-2161a83f15a1)

2. **CPU - Intel Xeon 2.2GHz (Colab)**
   - Performance: ~1-1.2it/s
   - Comparable to Ryzen 5.

![xeon_colab](https://github.com/ultralytics/ultralytics/assets/68916061/fc66b76d-0bde-4e83-9fc3-58e94a217b3b)

3. **GPU (DirectML) - Radeon RX 6500M**
   - Dedicated Memory: 4GB
   - Performance: ~3-6it/s
   - Notable performance for a mobile GPU.

![6500m_local](https://github.com/ultralytics/ultralytics/assets/68916061/74754a88-ff18-4f9d-89dc-ddb56ce88add)

4. **GPU (Cuda) - Nvidia T4 (Colab)**
   - Performance: ~10-12it/s
   - Workstation GPU optimized for AI/ML tasks.

![t4_colab](https://github.com/ultralytics/ultralytics/assets/68916061/d57421c2-af60-40f3-baaf-fbdec6f138ec)

### Results Summary:

- The CPUs (Ryzen 5 and Intel Xeon) show expected performance levels.
- The Radeon 6500M demonstrates a significant performance gap compared to CPUs, which is impressive for a mobile GPU.
- Higher-end AMD GPUs are expected to deliver even better performance.
- The Nvidia T4's performance aligns with expectations for a workstation GPU.

I would be happy to provide any additional metrics you need for comparison.

#### Training Code:
`python
from ultralytics.models.yolo.classify import train
from ultralytics.models.yolo.classify import ClassificationTrainer

args = dict(model='yolov8n-cls.pt', data='mnist', epochs=1, device="dml")
trainer = ClassificationTrainer(overrides=args)
trainer.train()
`

#### Prediction Code:
`python
from ultralytics.utils import ASSETS
from ultralytics.models.yolo.classify import ClassificationPredictor

args = dict(model='yolov8m-cls.pt', source=0, device="cpu",)
predictor = ClassificationPredictor(overrides=args)
predictor.predict_cli()
`

(Note: Ensure you run the above codes after cloning the repo and executing the python codes from within the cloned repository.)


## IMP: Can you provide me a list of tests or files that I must check and conduct reviews to finalize the working of DirectML. Currently, I have tested the **predict.py** and **train.py** files in **ultralytics>models>yolo>classify folder**. 
## A simplified list will surely help in efficient testing of DirectML and will resolve errors before finalizing the repository.

**Comment by glenn-jocher** [comment]
Hi @Gurneet1928,

Thank you for the detailed update and for sharing your findings! It's fantastic to see the progress you've made with integrating DirectML into YOLOv8. Your performance comparisons across different devices are particularly insightful.

Regarding your request for a list of tests or files to check for finalizing the DirectML integration, here are some key areas to focus on:

1. **Core Functionality**:
   - **train.py**: Ensure training works seamlessly across different datasets and configurations.
   - **predict.py**: Verify that predictions are accurate and consistent across various input sources (images, videos, webcam).

2. **Model Types**:
   - **Detection**: Test with YOLOv8 detection models.
   - **Segmentation**: Ensure segmentation models work correctly.
   - **Classification**: As you've already done, test classification models.

3. **Device Compatibility**:
   - Test across different hardware setups to ensure compatibility and performance consistency.
   - Validate that the device selection logic correctly prioritizes and utilizes the appropriate GPU.

4. **Edge Cases**:
   - Handle scenarios where DirectML might not be available or compatible.
   - Ensure fallback mechanisms to CPU or other supported devices are robust.

5. **Documentation**:
   - Update the documentation to include instructions for enabling and using DirectML.
   - Highlight any known limitations or special considerations.

Here's a simplified checklist to guide your testing:

### Checklist for DirectML Integration

1. **Training**:
   - [ ] Train detection models (`yolov8n.pt`) on a sample dataset.
   - [ ] Train segmentation models (`yolov8n-seg.pt`) on a sample dataset.
   - [ ] Train classification models (`yolov8n-cls.pt`) on a sample dataset.

2. **Prediction**:
   - [ ] Run predictions on images using detection models.
   - [ ] Run predictions on videos using detection models.
   - [ ] Run predictions on webcam feed using detection models.
   - [ ] Run predictions using segmentation models.
   - [ ] Run predictions using classification models.

3. **Device Handling**:
   - [ ] Verify device selection logic for DirectML.
   - [ ] Test fallback to CPU when DirectML is not available.
   - [ ] Ensure compatibility with different GPU setups (integrated vs. dedicated).

4. **Edge Cases**:
   - [ ] Handle low-memory scenarios gracefully.
   - [ ] Ensure consistent performance across different hardware.

5. **Documentation**:
   - [ ] Update usage instructions for DirectML.
   - [ ] Document any known issues or limitations.

By following this checklist, you can ensure a comprehensive and robust integration of DirectML into YOLOv8. If you encounter any specific issues or need further assistance, feel free to share the details here.

Thank you for your contributions and dedication to enhancing YOLOv8. Your efforts are greatly appreciated by the community! 🚀

**Comment by RobbStarkAustria** [comment]
Hi @Gurneet1928,

Thank you for looking into DirectML!

I have done also some tests with DirectML, but I started with object-detection not classification. I run also in this error and try to solve this by converting to numpy and use the return counts-operator of numpy in loss.py:

```
if targets.device.type == "privateuseone":
    i = i.cpu().numpy()
    _, counts = np.unique(i, return_counts=True)
    counts = torch.as_tensor(counts, dtype=torch.int)
else:
   _, counts = i.unique(return_counts=True)
```

I have some other incompatibilities to solve. A train run ends without a code error, but the loss will always 0.

Maybe my way could help you.

Regards

Olaf

**Comment by Gurneet1928** [comment]
> Hi @Gurneet1928,
> 
> Thank you for looking into DirectML!
> 
> I have done also some tests with DirectML, but I started with object-detection not classification. I run also in this error and try to solve this by converting to numpy and use the return counts-operator of numpy in loss.py:
> 
> ```
> if targets.device.type == "privateuseone":
>     i = i.cpu().numpy()
>     _, counts = np.unique(i, return_counts=True)
>     counts = torch.as_tensor(counts, dtype=torch.int)
> else:
>    _, counts = i.unique(return_counts=True)
> ```
> 
> I have some other incompatibilities to solve. A train run ends without a code error, but the loss will always 0.
> 
> Maybe my way could help you.
> 
> Regards
> 
> Olaf

Hey, thanks for the suggestion. This seems to be working, but throws up another error 
![image](https://github.com/ultralytics/ultralytics/assets/68916061/2af0432b-084b-4af1-954e-c968e514b9a4)

I am using the code u shared in loss.py as follows, in the object-detection preprocess function:
![image](https://github.com/ultralytics/ultralytics/assets/68916061/d849639d-cd70-4bad-9ecf-46f4ce19a10a)

**Comment by glenn-jocher** [comment]
Hi Olaf,

Thank you for sharing your insights and the workaround using numpy for the DirectML incompatibility in `loss.py`. It's great to see the community collaborating to tackle these challenges!

Gurneet, it looks like you're on the right track by incorporating Olaf's suggestion. However, the new error indicates there might be additional layers or operations that are not yet supported by DirectML.

Here are a few steps to help debug and potentially resolve this issue:

1. **Check for Other Incompatibilities**: Review the entire training loop and identify any other operations that might not be supported by DirectML. You might need to apply similar workarounds as Olaf's for those operations.

2. **Incremental Testing**: Simplify your model and training loop to the most basic form and gradually add complexity. This can help isolate the specific operations causing issues.

3. **Logging and Debugging**: Add detailed logging to track the flow of data and identify where the process breaks. This can provide more context for the errors you're encountering.

4. **Community and Documentation**: Keep an eye on updates from the DirectML and PyTorch communities. New releases might address some of these incompatibilities.

If you can provide a minimum reproducible example that demonstrates the issue, it would be immensely helpful for further investigation. You can refer to our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.

Thank you both for your contributions and efforts in enhancing YOLOv8's compatibility with DirectML. Your collaboration is invaluable to the community!

**Comment by Gurneet1928** [comment]
> Hi Olaf,
> 
> Thank you for sharing your insights and the workaround using numpy for the DirectML incompatibility in `loss.py`. It's great to see the community collaborating to tackle these challenges!
> 
> Gurneet, it looks like you're on the right track by incorporating Olaf's suggestion. However, the new error indicates there might be additional layers or operations that are not yet supported by DirectML.
> 
> Here are a few steps to help debug and potentially resolve this issue:
> 
> 1. **Check for Other Incompatibilities**: Review the entire training loop and identify any other operations that might not be supported by DirectML. You might need to apply similar workarounds as Olaf's for those operations.
> 2. **Incremental Testing**: Simplify your model and training loop to the most basic form and gradually add complexity. This can help isolate the specific operations causing issues.
> 3. **Logging and Debugging**: Add detailed logging to track the flow of data and identify where the process breaks. This can provide more context for the errors you're encountering.
> 4. **Community and Documentation**: Keep an eye on updates from the DirectML and PyTorch communities. New releases might address some of these incompatibilities.
> 
> If you can provide a minimum reproducible example that demonstrates the issue, it would be immensely helpful for further investigation. You can refer to our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.
> 
> Thank you both for your contributions and efforts in enhancing YOLOv8's compatibility with DirectML. Your collaboration is invaluable to the community!

Thanks for the suggestion @glenn-jocher . I am still trying to fix the errors through torch_directml documentations. 

As far as Minimum Reproducible Example is considered, it would be difficult to replicate the same in "minimized" manner, since the every file is dependent on each other. 

However, I have uploaded all the changed YoloV8 files alongside a trial.ipynb notebook on Github Repository (Link: https://github.com/Gurneet1928/yolov8_directml)

To run the codes, clone the repo using:
`
git clone https://github.com/Gurneet1928/yolov8_directml.git
`

And in the **"trials.ipynb"** file, there should be a section **Training Different Models on DML [ Detection, Segmentation, Classification]**

Try to execute the codes from the repo itself. 

Thank you

**Comment by RobbStarkAustria** [comment]
Hi Gurneet(@Gurneet1928), 
> Hey, thanks for the suggestion. This seems to be working, but throws up another error ![image](https://private-user-images.githubusercontent.com/68916061/340761200-2af0432b-084b-4af1-954e-c968e514b9a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MzM5NDQsIm5iZiI6MTcxODczMzY0NCwicGF0aCI6Ii82ODkxNjA2MS8zNDA3NjEyMDAtMmFmMDQzMmItMDg0Yi00YWYxLTk1NGUtYzk2OGU1MTRiOWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDE4MDA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMTBhMDQ2ZTliNzNhM2ZkMjZmOGEzODNjNmM0Y2ZmZTRjYzBmY2FlZjQ4ZmJhMzkyMTkzY2JhZjc3ZjJmOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TgSoX1kfVmqi9VlW1HTeudyKX0rXY0VlUFc2B2E3Xdg)
> 

Yes, I also run in this error in tal.py. I tried to use the same 'trick' as before by copying the data to cpu-device. I use the following code. It throws no error, but I had no time to validate if the result is the same compared to the original code:

```
if topk_idxs.device.type == "privateuseone":
    count_tensor = count_tensor.cpu()
    count_tensor.scatter_add_(-1, topk_idxs[:, :, k : k + 1].cpu(), ones.cpu())
    count_tensor = count_tensor.to(topk_idxs.device)
else:
    count_tensor.scatter_add_(-1, topk_idxs[:, :, k : k + 1], ones)
```

Maybe you have the chance to compare the value of _counter_tensor_.

And the question is whether the performance doesn't suffer too much from the constant copying back and forth.

Regards

**Comment by glenn-jocher** [comment]
@RobbStarkAustria hi Olaf,

Thank you for sharing your workaround for the issue in `tal.py`. It's great to see the community collaborating to address these challenges! 😊

Gurneet, it looks like Olaf's approach might help you move forward. Here’s the modified code snippet for `tal.py` that you can try:

```python
if topk_idxs.device.type == "privateuseone":
    count_tensor = count_tensor.cpu()
    count_tensor.scatter_add_(-1, topk_idxs[:, :, k : k + 1].cpu(), ones.cpu())
    count_tensor = count_tensor.to(topk_idxs.device)
else:
    count_tensor.scatter_add_(-1, topk_idxs[:, :, k : k + 1], ones)
```

This should help bypass the DirectML incompatibility by temporarily moving the tensors to the CPU for the `scatter_add_` operation. However, as Olaf mentioned, it's important to validate whether this workaround maintains the same results as the original code and to assess any potential performance impact due to the constant copying between devices.

### Next Steps:
1. **Validation**: Compare the results of the modified code with the original implementation to ensure consistency.
2. **Performance Testing**: Measure the performance to determine if the additional CPU-GPU transfers significantly affect the training speed.

If you encounter further issues or need additional assistance, please provide more details or share a minimum reproducible example. This will help us better understand the problem and provide more targeted support.

Thank you both for your contributions and efforts in enhancing YOLOv8's compatibility with DirectML. Your collaboration is invaluable to the community! 🚀

**Comment by Gurneet1928** [comment]
Thanks for you suggestions @RobbStarkAustria @glenn-jocher ,

After using the shared code snippet, I seem to run into another issue this time. Would be great if someone can help me on this:

``````

**Comment by RobbStarkAustria** [comment]
Hi Gurneet, @Gurneet1928 

for this error you can do this:
```
if prediction.device.type == "privateuseone":
    x = torch.cat((box[i].cpu(), x[i, 4 + j, None].cpu(), j[:, None].cpu().float(), mask[i].cpu()), 1)
    x = x.to(prediction.device)
else:
    x = torch.cat((box[i], x[i, 4 + j, None], j[:, None].float(), mask[i]), 1)
```

Then the code runs without error, but the metrics are always '0'. So we have to dive deeper in the code to find out the reason for this behaviour.

Regards

Olaf

**Comment by nietdoen** [comment]
Hello guys i wanted to ask if anyone manage to make it work?

because i always getting this error

RuntimeError: DirectML scatter doesn't allow partially modified dimensions. Please update the dimension so that the indices and input only differ in the provided dimension.

this is how my tal.py looks like 

`     def select_topk_candidates(self, metrics, largest=True, topk_mask=None):
 
    # Move to CPU for processing
        metrics_cpu = metrics.cpu()
    
    # (b, max_num_obj, topk)
        topk_metrics, topk_idxs = torch.topk(metrics_cpu, self.topk, dim=-1, largest=largest)
    
        if topk_mask is None:
            topk_mask = (topk_metrics.max(-1, keepdim=True)[0] > self.eps).expand_as(topk_idxs)
    
    # (b, max_num_obj, topk)
        topk_idxs.masked_fill_(~topk_mask, 0)

    # (b, max_num_obj, h*w)
        count_tensor = torch.zeros(metrics_cpu.shape, dtype=torch.int8)
    
    # Create a range tensor for batch and max_num_obj dimensions
        batch_size, max_num_obj = topk_idxs.shape[:2]
        batch_range = torch.arange(batch_size)[:, None, None]
        obj_range = torch.arange(max_num_obj)[None, :, None]
    
    # Use advanced indexing instead of scatter_add_
        for k in range(self.topk):
            valid_mask = topk_mask[:, :, k]
            valid_idxs = topk_idxs[:, :, k][valid_mask]
            count_tensor[batch_range[valid_mask], obj_range[valid_mask], valid_idxs] += 1

    # Filter invalid bboxes
        count_tensor.masked_fill_(count_tensor > 1, 0)

    # Move back to the original device (DML if it was DML)
        count_tensor = count_tensor.to(device=metrics.device, dtype=metrics.dtype)

        return count_tensor  `

**Comment by pderrenger** [comment]
@nietdoen hi,

Thank you for sharing your experience. The error you're encountering with DirectML scatter operations is known and has been discussed in previous comments. It appears to be related to DirectML's limitations with certain tensor operations.

To address this, you can try moving the tensors to the CPU for the specific operations that are causing issues and then move them back to the original device. This workaround has been suggested and implemented by other users facing similar issues.

If you continue to experience problems, please ensure you are using the latest versions of the Ultralytics and torch-directml packages, as updates may include fixes or improvements.

Feel free to share any further details or questions you have. Your contributions help improve the compatibility and performance of YOLOv8 with DirectML.
