### ISSUE TITLE
check_amp tries to download new weights

### ISSUE THREAD

**Issue by GuillaumeBruand** [ultralytics/ultralytics#1375]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

In trainer.py, l.624

`assert amp_allclose(YOLO('yolov8n.pt'), im)`

tries to download new weights, which is both inefficient and does not work in an offline setup (my case).

Solutions proposed:

1. Replace line 627 by `except (AssertionError, ConnectionError):`
2. Use input model weight path
3. Provide way to deactivate AMP check (right now check_amp is not even overload-able)

### Environment

- Ultralytics YOLOv8.0.52

### Minimal Reproducible Example

# Disable external web access
model = YOLO("insert_internal_path_for_weights_here")
results = model.train()  

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@GuillaumeBruand thanks for the feedback! We use an official pretrained model since we know it's expected output on the example images in ultralytics/assets. 

We can't use the user-supplied model for AMP checks since it may not produce detections on asset images because it may be trained on another dataset/domain, or it may not even be a pretrained model, it may just be a newly untrained model constructed from a YAML.

In offline environments it's likely not possible to conduct AMP checks then. We can add a special bypass that presents a warning and attempts AMP training in this case.

**Comment by glenn-jocher** [comment]
@GuillaumeBruand implemented a fix in https://github.com/ultralytics/ultralytics/pull/1368/commits/b8ad726a7a59707cd9c74c3644ba172548779ea2

Checks will be skipped when offline and unable to download official model, amp=True will be set automatically with a warning shown to user.

**Comment by GuillaumeBruand** [comment]
@glenn-jocher Thanks for the quick fix !

**Comment by glenn-jocher** [comment]
@AyushExel @Laughing-q should we add an `amp=True` argument to default.yaml to allow users to force-disable? Right now we have an AMP check in place that should resolve 90% of the problems, but it's not easy for users to manually disable. The behavior would be:

```python
amp=True  # amp = amp & amp_checks(), still run checks
amp=False  # amp=False, skip checks
```

**Comment by Laughing-q** [comment]
@glenn-jocher yeah I think that's a good idea!
