### ISSUE TITLE
AttributeError: 'Profile' object has no attribute 'dt'

### ISSUE THREAD

**Issue by Dukisef012** [ultralytics/ultralytics#1382]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I'm getting this error from time to time when using the model to get detection result

bigger traceback:
`  File "restapi.py", line 29, in predict
    results = model_1(im)
  File "/root/detection_server/.venv/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 71, in __call__
    return self.predict(source, stream, **kwargs)
  File "/root/detection_server/.venv/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 169, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/root/detection_server/.venv/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/detection_server/.venv/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 113, in __call__
    return list(self.stream_inference(source, model))  # merge list of Result into one
  File "/root/detection_server/.venv/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 194, in stream_inference
    LOGGER.info(f"{s}{'' if len(preds) else '(no detections), '}{self.dt[1].dt * 1E3:.1f}ms")
AttributeError: 'Profile' object has no attribute 'dt'`

### Minimal Reproducible Example

`model_1 = YOLO("models/normal/best.pt")  # load a custom model
@app.route(DETECTION_URL, methods=["POST"])
def predict():
    if not request.method == "POST":
        return

    if request.files.get("image"):
        im_file = request.files["image"]
        im_bytes = im_file.read()
        im = Image.open(io.BytesIO(im_bytes))
        results = model_1(im, size=1080)
        return results`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Dukisef012 please provide a minimal reproducible example of the bug you are seeing. See https://stackoverflow.com/help/minimal-reproducible-example for guidance.

**Comment by Dukisef012** [comment]
@glenn-jocher Sure, here it is

`model_1 = YOLO("models/normal/best.pt")  # load a custom model
@app.route(DETECTION_URL, methods=["POST"])
def predict():
    if request.files.get("image"):
        im_file = request.files["image"]
        im_bytes = im_file.read()
        im = Image.open(io.BytesIO(im_bytes))
        results = model_1(im, size=1080)
        return results`

**Comment by glenn-jocher** [comment]
@Dukisef012 I'm not able to reproduce your original issue as your code is not complete:

<img width="689" alt="Screenshot 2023-03-14 at 02 46 08" src="https://user-images.githubusercontent.com/26833433/224870968-cc4b3455-f15c-471d-bc7b-d421a075417a.png">


We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub, and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved.
- ✅ **Unmodified** – Your problem must be reproducible using official YOLO code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by dmccorm2** [comment]
I'm seeing this issue as well - however, it's in the context of a gstreamer pipeline, vs. this API example it would seem. I'll try and recreate with a minimal sample, but something to keep an eye on perhaps

**Comment by hhyilmaz** [comment]
if you add code below it fixes the problem. it relates to multithread calling predict function 
    
    self.dt = 0

in ops.py  

```
class Profile(contextlib.ContextDecorator):
    """
    YOLOv8 Profile class.
    Usage: as a decorator with @Profile() or as a context manager with 'with Profile():'
    """
    def __init__(self, t=0.0):
        """
        Initialize the Profile class.

        Args:
            t (float): Initial time. Defaults to 0.0.
        """
        self.t = t
        self.dt = 0

```

**Comment by hhyilmaz** [comment]
multithreading on predict function is broken it produces other errors.

**Comment by glenn-jocher** [comment]
@hhyilmaz sure! Based on the provided suggestion, I understand that there may be an issue when running the `predict()` function concurrently in multiple threads. To fix the problem, a solution has been suggested involving changes to the `Profile` class constructor within the `ops.py` file. 

However, it's difficult to provide more details without a complete example or additional context. If the issue persists, please provide more information, such as a use case scenario, what you are trying to achieve and what specific errors you are encountering. This would greatly help in understanding the issue and providing a more precise solution.

**Comment by EmersonDove** [comment]
Hey @glenn-jocher, also seeing this error:

```
    'inference': self.dt[1].dt * 1E3 / n,
AttributeError: 'Profile' object has no attribute 'dt'
```

as well as

```
    super().__delattr__(name)
AttributeError: bn
```

Looks like its occurring only if I run 2 or more concurrent calls to `yolo()`.

Here is complete example (you might have to change `image_path` and `ai_path`) which is creating 3 workers:

```python
from ultralytics import YOLO
from concurrent.futures import ThreadPoolExecutor

ai_path = "./models/yolov8s.pt"
image_path = './uploads/2e752fc9-5b84-42d7-bd7a-78ba56f64327-image.jpg'

yolo = YOLO(ai_path)

# Create a threadpool to run the model. Run two image calls at the same time

with ThreadPoolExecutor(max_workers=3) as executor:
    # Run the model on two images at the same time
    results = executor.map(yolo, [image_path, image_path, image_path])

    # Print the results
    for result in results:
        print(result)

``` 

Thanks!

**Comment by glenn-jocher** [comment]
@EmersonDove based on the provided error messages, it seems that there might be issues running multiple concurrent calls to the `YOLO()` function. The first error message suggests that there might be an issue with the `Profile` object, which could be related to multithreading. The second error message suggests an issue with a `batchnorm` attribute, though it is unclear how this relates to the multithreading issue.

To further understand the problem, additional context such as your use case, the environment you are running the code in, and the versions of relevant software and hardware being used might be helpful. Once the issue is better understood, potential solutions could involve modifying the YOLO code to handle multithreading. Alternatively, a workaround could involve limiting the number of requests in parallel to avoid the issue.

**Comment by EmersonDove** [comment]
Hey @glenn-jocher, we're using this on python 3.9 in a server context so concurrency is critical.

### Workaround
I managed to work around the issue by creating a new instance of `YOLO()` on each call and then placing that instance on each new thread, instead of trying to share one instance between threads. This is slightly suboptimal because the initialization takes a bit of time but it does become thread-"safer" at least.

Basically this:

```python
def calculate_image(image_path):
    # Create the model
    yolo = YOLO(ai_path)

    # Run the model on the image
    return yolo(image_path)


# Create a threadpool to run the model. Run two image calls at the same time
with ThreadPoolExecutor(max_workers=2) as executor:
    # Run the model on two images at the same time
    results = executor.map(calculate_image, [image_path, image_path])

    # Print the results
    for result in results:
        print(result)
```
Based on this solution, it seems like a simple case of attributes being modified through the lifecycle of the call which could be on the torch level.

**Comment by glenn-jocher** [comment]
@EmersonDove it appears that there is an issue with sharing one instance of the `YOLO()` object between multiple threads in a concurrent program, which is causing errors related to the `Profile` object and the `bn` attribute. One workaround that has been found is creating a new instance of `YOLO()` for each call to `calculate_image()` and running each instance on a separate thread, instead of trying to share one instance between threads.

This solution is suboptimal because initialization of `YOLO()` takes some time, but it appears to be a safer approach in a concurrent setting. It's possible that the issue is related to attributes being modified through the lifecycle of the call, potentially at the torch level.

**Comment by sicklife** [comment]
I meet with this issue when I try to run yolo prediction in a fastapi server. The error come up when the request frequency is high. But as far as I know, fastapi use single thread for every worker. So I'm curious about which really cause the problem~

**Comment by glenn-jocher** [comment]
@sicklife thank you for raising this issue with YOLOv8! Based on the error message you encountered, it appears that there might be an issue with sharing a single instance of the `YOLO()` object between multiple threads in a concurrent program. It's possible that the problem is related to modifying attributes through the lifecycle of the call, potentially at the torch level.

One solution you could try is creating a new instance of `YOLO()` for each call to `calculate_image()` and running each instance on a separate thread, rather than trying to share one instance between threads. This approach should be safer in a concurrent setting, though it may have a slightly longer initialization time per request.

Without more information about your implementation or environment, it's difficult to pinpoint the exact cause of the issue. However, I hope this explanation and potential solution help to resolve the problem!

**Comment by sicklife** [comment]
> 

 I think the problem is that the original code create a `self.dt` attribute in line 214. ultralytics/yolo/engine/predictor.py

When the this code is re-entered by  coroutine （not another thread）the `self.dt` attribute will be rewrite. So the solution could be simple, just use a local variable instead of a class attribute. 

I have create a PR for this issue. Hope can be helpful~

**Comment by glenn-jocher** [comment]
@sicklife thank you for pointing out the issue with the `self.dt` attribute in line 214 of the `ultralytics/yolo/engine/predictor.py` file. It seems that when the code is re-entered by a coroutine, the `self.dt` attribute is rewritten, causing issues.

Your solution of using a local variable instead of a class attribute seems reasonable, and we appreciate the effort you put into creating a pull request to address the issue. We will review the PR and integrate it if it is deemed appropriate.

Thanks again for your contribution and for helping to make YOLOv8 a better tool!

**Comment by glenn-jocher** [comment]
@sicklife PR merged!
