### ISSUE TITLE
Issues with using dataset which is not is square dimensions.

### ISSUE THREAD

**Issue by agNihit928** [ultralytics/ultralytics#13857]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

So, I trying to use a custom dataset to train yolov8m at an image size of 1280x640. When running the training, I saw some warnings that changing the size to 1280 and so.
```
WARNING ⚠️ updating to 'imgsz=1280'. 'train' and 'val' imgsz must be an integer, while 'predict' and 'export' imgsz may be a [h, w] list or an integer, i.e. 'yolo export imgsz=640,480' or 'yolo export imgsz=640'
```
So I checked other open issues regarding this and everywhere it said that we can avoid that warning. Later I tried to train 640x1280 image size and surprisingly, all the evaluation metrics from image size 1280x640 matched the evaluation metrics from 640x1280. So I started to explore the complete repo and found out that there is no provision for training rectangular images as somewhere down the line it updates the tuple size to integer. because most of the functions starts to throw error if the imgsz turns out to be a list at some point(I tried explicitly setting the image size in the codebase).
For example in the `augment.py` file in data folder:
```
class Mosaic(BaseMixTransform):
    """
    Mosaic augmentation.

    This class performs mosaic augmentation by combining multiple (4 or 9) images into a single mosaic image.
    The augmentation is applied to a dataset with a given probability.

    Attributes:
        dataset: The dataset on which the mosaic augmentation is applied.
        imgsz (int, optional): Image size (height and width) after mosaic pipeline of a single image. Default to 640.
        p (float, optional): Probability of applying the mosaic augmentation. Must be in the range 0-1. Default to 1.0.
        n (int, optional): The grid size, either 4 (for 2x2) or 9 (for 3x3).
    """

    def __init__(self, dataset, imgsz=640, p=1.0, n=4):
        """Initializes the object with a dataset, image size, probability, and border."""
        assert 0 <= p <= 1.0, f"The probability should be in range [0, 1], but got {p}."
        assert n in {4, 9}, "grid must be equal to 4 or 9."
        super().__init__(dataset=dataset, p=p)
        self.dataset = dataset
        self.imgsz = imgsz
        self.border = (-imgsz // 2, -imgsz // 2)  # width, height
        self.n = n
```

here it directly assumes imgsz as integer.
And this just an example, there are a lot more instances of this. So why is the documentation misguiding the users?

### Additional

Would be grateful if you could point out any error in my approach or guide me how I do a rectangular training.

**Comment by glenn-jocher** [comment]
@agNihit928 hi there,

Thank you for your detailed report and for checking existing issues before posting. It’s great to see your thorough investigation into the matter. 

The warning you encountered is indeed expected behavior. Currently, YOLOv8's training process assumes square dimensions for images (`imgsz` as an integer) due to the way various augmentations and transformations are implemented. This is why you see the warning and why the evaluation metrics remain consistent regardless of the rectangular dimensions you attempted to set.

To address your specific points:

1. **Training with Rectangular Images**: As you correctly identified, the current implementation does not support non-square dimensions directly in the training pipeline. The `imgsz` parameter is expected to be an integer, representing square dimensions. This is a design choice to ensure compatibility and stability across various augmentation and preprocessing steps.

2. **Documentation Clarification**: The documentation might indeed seem misleading regarding the flexibility of `imgsz`. While `predict` and `export` modes support rectangular dimensions, `train` and `val` modes do not. We appreciate your feedback and will work on clarifying this in our documentation to prevent future confusion.

3. **Possible Workaround**: If you need to work with rectangular images, you might consider resizing your images to the nearest square dimension (e.g., padding or cropping) before feeding them into the training pipeline. This ensures compatibility with the current implementation while allowing you to work with your desired aspect ratio.

Here’s a small snippet to help you resize your images to square dimensions using padding:

```python
import cv2
import numpy as np

def resize_to_square(image, size=640):
    h, w = image.shape[:2]
    scale = size / max(h, w)
    new_h, new_w = int(h * scale), int(w * scale)
    resized_image = cv2.resize(image, (new_w, new_h))

    delta_w = size - new_w
    delta_h = size - new_h
    top, bottom = delta_h // 2, delta_h - (delta_h // 2)
    left, right = delta_w // 2, delta_w - (delta_w // 2)

    color = [0, 0, 0]
    new_image = cv2.copyMakeBorder(resized_image, top, bottom, left, right, cv2.BORDER_CONSTANT, value=color)
    return new_image

# Example usage
image = cv2.imread('path/to/your/image.jpg')
square_image = resize_to_square(image, size=640)
cv2.imwrite('path/to/save/square_image.jpg', square_image)
```

This approach ensures that your images maintain their aspect ratio while fitting into the required square dimensions.

If you have any further questions or need additional assistance, feel free to ask. We’re here to help!

**Comment by agNihit928** [comment]
Thanks a lot for the confirmation @glenn-jocher .
Also, thank you the reference code, this is gonna make my work easier in the preprocessing step.

**Comment by glenn-jocher** [comment]
@agNihit928 you're welcome! 😊 I'm glad the reference code will help streamline your preprocessing step.

If you encounter any further issues or have additional questions, feel free to reach out. We're here to assist!

Happy coding! 🚀
