### ISSUE TITLE
How to Shut Down Wandb

### ISSUE THREAD

**Issue by ZYJIQVV** [ultralytics/ultralytics#13856]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Dear developer!
When I use YOLOv8 model, there is always a wandb prompt, which costs me a lot of energy and time to deal with.
Could you please teach me how to shut it down?
![image](https://github.com/ultralytics/ultralytics/assets/111969464/9b8956ce-6c60-4c20-8a03-ac1c4334d113)

**Comment by glenn-jocher** [comment]
@ZYJIQVV hello!

Thank you for reaching out. To disable the Weights & Biases (wandb) integration in YOLOv8, you can set the `--logger` argument to `None` when running your training or other tasks. This will prevent wandb from initializing and eliminate the prompts you're encountering.

Here's an example of how to do this:

```bash
yolo train data=coco128.yaml model=yolov8n.pt epochs=100 imgsz=640 logger=None
```

Or, if you're using the Python API:

```python
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.pt')

# Train the model with wandb disabled
results = model.train(data='coco128.yaml', epochs=100, imgsz=640, logger=None)
```

This should help you avoid the wandb prompts and save you some time and energy. If you have any other questions or run into further issues, feel free to ask!

**Comment by lamachlab** [comment]
Hi! I am having a similar problem, but when I try to use the logger solution, I get SyntaxError: 'logger' is not a valid YOLO argument.

my code looks like this 
`from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n-pose.pt") 

# Train the model
results = model.train(data="spine.yaml", epochs=100, imgsz=1024, logger=None)`

is there another way to disable wandb? why is logger not a valid YOLO argument for me?

**Comment by glenn-jocher** [comment]
Hello @lamachlab,

Thank you for reaching out and providing your code snippet. It looks like you're encountering a `SyntaxError` because the `logger` argument might not be recognized in your current setup.

To disable Weights & Biases (wandb) logging, you can set the `WANDB_DISABLED` environment variable to `true` before running your script. This approach ensures that wandb is completely disabled.

Here's how you can do it:

### Option 1: Setting Environment Variable in Python
You can set the environment variable directly in your Python script:

```python
import os
os.environ['WANDB_DISABLED'] = 'true'

from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n-pose.pt")

# Train the model
results = model.train(data="spine.yaml", epochs=100, imgsz=1024)
```

### Option 2: Setting Environment Variable in Command Line
Alternatively, you can set the environment variable in your command line before running your script:

```bash
export WANDB_DISABLED=true
python your_script.py
```

### Option 3: Using the CLI
If you prefer using the command line interface (CLI), you can disable wandb by setting the `logger` argument to `None`:

```bash
yolo train data=spine.yaml model=yolov8n-pose.pt epochs=100 imgsz=1024 logger=None
```

Please ensure you are using the latest version of the Ultralytics package to avoid any compatibility issues. You can update it using:

```bash
pip install --upgrade ultralytics
```

If the issue persists, please provide more details or a minimum reproducible example so we can assist you further. You can find more information on creating a reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

I hope this helps! If you have any more questions, feel free to ask. 😊

**Comment by lamachlab** [comment]
This worked! thank you for your help!

**Comment by glenn-jocher** [comment]
Hello @lamachlab,

You're very welcome! I'm glad to hear that the solution worked for you. 🎉

If you have any more questions or run into any other issues, feel free to reach out. We're here to help! Also, if you encounter any bugs or have suggestions for improvements, please don't hesitate to share them with us. Your feedback is invaluable to the YOLO community and the Ultralytics team.

Happy coding and best of luck with your project! 😊

**Comment by tjasmin111** [comment]
I tried doing `export WANDB_DISABLED=true` and then `yolo detect train ... logger=None` but it still complains `logger doesn't exist.

How to address this? I am using the latest Ultralytics.

**Comment by glenn-jocher** [comment]
@tjasmin111 thank you for your message. To disable wandb, please set the environment variable `WANDB_DISABLED=true` and remove the `logger=None` argument from your command. This should resolve the issue. If the problem persists, please ensure you are using the latest version of Ultralytics.
