### ISSUE TITLE
unexpected freezed layer

### ISSUE THREAD

**Issue by MuhabHariri** [ultralytics/ultralytics#13865]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hi

I am trying to freeze the first custom block using **freeze=1**, but I get these results:

![2024-06-21_19-18-13](https://github.com/ultralytics/ultralytics/assets/69437726/4fe80cba-ba9b-4b92-ba44-476491c33464)

All the frozen layers are related to the aforementioned custom block, except for the last layer **"Freezing layer 'model.19.dfl.conv.weight'**. Do you have any idea what this frozen layer is and why it was frozen? If we consider that model.0 refers to the first layer (since the index starts from 0), then model.19 is the Detect layer according to my YAML file. Is this interpretation logical? If yes, why is there a frozen layer in the Detect class?

Thanks

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MuhabHariri hi there,

Thank you for reaching out and providing details about the issue you're encountering with freezing layers in your custom YOLOv8 model. To assist you better, could you please provide a minimal reproducible code example? This will help us understand the context and reproduce the issue on our end. You can refer to our guide on creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details.

Additionally, please ensure that you are using the latest versions of `torch` and `ultralytics`. You can upgrade your packages using the following commands:
```bash
pip install --upgrade torch ultralytics
```

Regarding your question, your interpretation is correct. In the YOLOv8 model, `model.0` refers to the first layer, and `model.19` would indeed correspond to the Detect layer if your YAML file is structured that way. The unexpected freezing of the `model.19.dfl.conv.weight` layer could be due to a misconfiguration or an unintended side effect in the model's layer freezing logic.

Once you provide the reproducible example and confirm the versions, we can dive deeper into the issue and identify why the Detect layer's weight is being frozen.

Looking forward to your response!

**Comment by glenn-jocher** [comment]
@MuhabHariri DFL layers should always be frozen, this is all good.

**Comment by MuhabHariri** [comment]
@glenn-jocher Thank you for your response. Could you clarify further why DFL layers should always be frozen?

**Comment by glenn-jocher** [comment]
Hi @MuhabHariri,

Thank you for your follow-up question!

The DFL (Distribution Focal Loss) layers are designed to be frozen because they are part of the final detection head, which is responsible for refining the bounding box predictions. Freezing these layers helps maintain the stability of the model's output during training, ensuring that the learned distribution of bounding box coordinates remains consistent. This is particularly important for maintaining the accuracy and reliability of the model's predictions.

If you have any more questions or need further clarification, feel free to ask! 😊
