### ISSUE TITLE
How to access the Batch Normalization of Yolov8?

### ISSUE THREAD

**Issue by ishparsh** [ultralytics/ultralytics#13916]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

```
def collect_conv_layers(module, conv_layers, bns):
    for child_name, child in module.named_children():
        if isinstance(child, Conv):
            print(f'{child_name} : {child} (Conv layer)')
            conv_layers.append(child)

             bns.append(child.bn)
        elif isinstance(child, Bottleneck):
            print(f'{child_name} : {child} (Bottleneck layer)')
            conv_layers.append(child.cv1)
            bns.append(child.cv1.bn)
            conv_layers.append(child.cv2)
            bns.append(child.cv2.bn)
        else:
            collect_conv_layers(child, conv_layers, bns)
```

**This is my code to access the Batch normalization. But I am getting error**

`AttributeError: 'Conv' object has no attribute 'bn'

**Meanwhile this is your convolution layer.**

```
`class Conv(nn.Module):
    """Standard convolution with args(ch_in, ch_out, kernel, stride, padding, groups, dilation, activation)."""

    default_act = nn.SiLU()  # default activation

    def __init__(self, c1, c2, k=1, s=1, p=None, g=1, d=1, act=True):
        """Initialize Conv layer with given arguments including activation."""
        super().__init__()
        self.conv = nn.Conv2d(c1, c2, k, s, autopad(k, p, d), groups=g, dilation=d, bias=False)
        self.bn = nn.BatchNorm2d(c2)
        self.act = self.default_act if act is True else act if isinstance(act, nn.Module) else nn.Identity()

    def forward(self, x):
        """Apply convolution, batch normalization and activation to input tensor."""
        return self.act(self.bn(self.conv(x)))

    def forward_fuse(self, x):
        """Perform transposed convolution of 2D data."""
        return self.act(self.conv(x))`

```

**Comment by glenn-jocher** [comment]
@ishparsh hi there! 👋

Thank you for reaching out with your question. It looks like you're trying to access the Batch Normalization layers within the YOLOv8 model. Your approach is almost correct, but it seems like there might be a slight issue with how you're accessing the attributes.

Given the `Conv` class definition you provided, the `bn` attribute should indeed be present. However, let's ensure that your code correctly navigates through the model's layers. Here's a refined version of your function:

```python
def collect_conv_layers(module, conv_layers, bns):
    for child_name, child in module.named_children():
        if isinstance(child, Conv):
            print(f'{child_name} : {child} (Conv layer)')
            conv_layers.append(child)
            bns.append(child.bn)
        elif isinstance(child, Bottleneck):
            print(f'{child_name} : {child} (Bottleneck layer)')
            conv_layers.append(child.cv1)
            bns.append(child.cv1.bn)
            conv_layers.append(child.cv2)
            bns.append(child.cv2.bn)
        else:
            collect_conv_layers(child, conv_layers, bns)

# Example usage:
conv_layers = []
bns = []
model = YOLO('yolov8n.pt')  # Load your YOLOv8 model
collect_conv_layers(model.model, conv_layers, bns)  # Assuming 'model' is the attribute holding the layers
```

Make sure that the model you are passing to `collect_conv_layers` is correctly instantiated and that the layers are accessible. If you encounter any further issues, please provide a minimal reproducible example so we can better assist you. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, ensure you are using the latest version of the Ultralytics package to avoid any potential bugs that might have been fixed in newer releases.

Feel free to reach out if you have any more questions. Happy coding! 😊

**Comment by ishparsh** [comment]
I was using coco8 Yolo model, where I was not getting bn. However, when I used predefined 'yolov8n.pt', it had the batch normalization. I guess when the model is trained on coco8 it does not have bn. I think its because the dataset is already less and it won't be worth to do batch normalization. If I am wrong please correct me.

And thanks for replying really quick.

**Comment by ishparsh** [comment]
Last question, if I need to find the params and macs operation. How can I do that? If I use 'profile_macs', 
```
inputs = torch.randn(3, 480, 480).cuda()
macs =  profile_macs(model, inputs)
```

**Error**:

``TypeError: type Tensor doesn't define __round__ method
``

**Comment by glenn-jocher** [comment]
Hi @ishparsh,

Great question! To profile the parameters and MACs (Multiply-Accumulate Operations) of your YOLOv8 model, you can use the `torchprofile` library, which is specifically designed for this purpose. Here's how you can do it:

First, ensure you have the `torchprofile` library installed:
```bash
pip install torchprofile
```

Then, you can use the following code to profile your model:

```python
import torch
from torchprofile import profile_macs
from ultralytics import YOLO

# Load your YOLOv8 model
model = YOLO('yolov8n.pt').model

# Create a dummy input tensor with the appropriate shape
inputs = torch.randn(1, 3, 480, 480).cuda()  # Batch size of 1, 3 color channels, 480x480 image size

# Profile the MACs
macs = profile_macs(model, inputs)
print(f'MACs: {macs}')

# Profile the number of parameters
params = sum(p.numel() for p in model.parameters())
print(f'Parameters: {params}')
```

This should give you the MACs and the number of parameters for your model without any errors. If you encounter any issues, please ensure you are using the latest versions of the Ultralytics and `torchprofile` packages.

If you still face issues, providing a minimal reproducible example would be very helpful. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions. Happy coding! 😊

**Comment by ishparsh** [comment]
Hello again,
I am doing some fine grained pruning on YOLOv8. But when I try to save the model I am getting lots of issues.

``torch.save(model,'fine_grained.pt')``
Error:
``TypeError: cannot pickle 'torch._C.Generator' object
``

But if I have save the model 
`torch.save(model.model,'fine_grained.pt) `
It works but when I try to load the model
I get this error
`AttributeError: 'SiLU' object has no attribute 'accumulate_params'`

Now I tried using torchscript

```
model_scripted = torch.jit.script(model) # Export to TorchScript
model_scripted.save('model_scripted.pt') 
```

The error I get is 
```
UnsupportedNodeError: from ultralytics.nn.autobackend import check_class_names
        ~~~~ <--- HERE
    
        if hasattr(self.model, "names"):
```

Now you may say that why I didn't use state_dict to save the model, as I have done pruning operations so it doesn't follow predefined yolo architecture.

**Comment by glenn-jocher** [comment]
Hi @ishparsh,

Thank you for reaching out again and providing detailed information about the issues you're encountering with fine-grained pruning and saving your YOLOv8 model. Let's address each of your concerns:

### Saving the Model
When saving a pruned model, it's generally recommended to use the `state_dict` method to avoid issues with pickling and custom layers. However, since you've mentioned that the pruned model doesn't follow the predefined YOLO architecture, this might not be straightforward. 

### TorchScript Export
The error you're encountering with TorchScript (`UnsupportedNodeError`) suggests that certain parts of the model's code are not compatible with TorchScript. This is a known limitation when using dynamic or custom operations within the model.

### Export Function Accuracy Drop
The drop in accuracy when using the `model.export(format="torchscript")` function is concerning. This could be due to several reasons, including differences in how certain operations are handled in TorchScript versus PyTorch.

### Suggested Approach
1. **Saving and Loading the Model:**
   Given the issues with `torch.save`, you might want to try saving and loading the model using the `state_dict` method, even though it requires some adjustments:

   ```python
   # Save the state_dict
   torch.save(model.model.state_dict(), 'fine_grained_state_dict.pt')

   # Load the state_dict
   model = YOLO('yolov8n.yaml')  # Initialize a new model with the same architecture
   model.model.load_state_dict(torch.load('fine_grained_state_dict.pt'))
   ```

2. **TorchScript Compatibility:**
   To address the TorchScript compatibility issue, you might need to modify the model code to remove or replace unsupported operations. This can be complex, but it's often necessary for successful TorchScript conversion.

3. **Maintaining Accuracy:**
   Ensure that the model's weights and architecture are correctly preserved during the export process. You might need to fine-tune the exported model to regain the lost accuracy.

### Example Code for Fine-Grained Pruning and Saving
Here's a more detailed example of how you might approach fine-grained pruning and saving the model:

```python
import torch
from ultralytics import YOLO

# Load your YOLOv8 model
model = YOLO('yolov8n.pt')

# Perform fine-grained pruning (example)
# Note: This is a placeholder for your actual pruning code
for name, param in model.model.named_parameters():
    if 'weight' in name:
        param.data *= (torch.rand(param.data.size()) > 0.5).float()

# Save the pruned model's state_dict
torch.save(model.model.state_dict(), 'fine_grained_state_dict.pt')

# Load the pruned model
model = YOLO('yolov8n.yaml')  # Initialize a new model with the same architecture
model.model.load_state_dict(torch.load('fine_grained_state_dict.pt'))

# Verify the model's performance
# Note: You might need to fine-tune the model to regain accuracy
```

### Final Thoughts
If the issue persists, please ensure you're using the latest versions of the Ultralytics and PyTorch packages. If you can provide a minimal reproducible example, it would greatly help in diagnosing the problem further. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions or need further assistance. Happy coding! 😊

**Comment by ishparsh** [comment]
```
class FineGrainedPruner:
    def __init__(self, model, sparsity_dict):
        self.masks = FineGrainedPruner.prune(model, sparsity_dict)

    @torch.no_grad()
    def apply(self, model):
        for name, param in model.named_parameters():
            if name in self.masks:
                param *= self.masks[name]

    @staticmethod
    @torch.no_grad()
    def prune(model, sparsity_dict):
        masks = dict()
        for module_name, module in model.named_modules():
            if isinstance(module, C2f):
                for name, param in model.named_parameters():
                    if param.dim() > 1: # we only prune conv and fc weights
                        if isinstance(sparsity_dict, dict):
                            masks[name] = fine_grained_prune(param, sparsity_dict[name])
                        else:
                            assert(sparsity_dict < 1 and sparsity_dict >= 0) # prune every layer
                            if sparsity_dict > 0:
                                masks[name] = fine_grained_prune(param, sparsity_dict)
        return masks
```

This is how am I doing the fine grained pruning.
Now when I tried your approach to save the model now I am getting issue.

```
RuntimeError: Error(s) in loading state_dict for DetectionModel:
	size mismatch for model.22.cv3.0.0.conv.weight: copying a param with shape torch.Size([64, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([80, 64, 3, 3]).
	size mismatch for model.22.cv3.0.0.bn.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
	size mismatch for model.22.cv3.0.0.bn.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
	size mismatch for model.22.cv3.0.0.bn.running_mean: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
	size mismatch for model.22.cv3.0.0.bn.running_var: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
	size mismatch for model.22.cv3.0.1.conv.weight: copying a param with shape torch.Size([64, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([80, 80, 3, 3]).
	size mismatch for model.22.cv3.0.1.bn.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
	size mismatch for model.22.cv3.0.1.bn.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
	size mismatch for model.22.cv3.0.1.bn.running_mean: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([80]).
```

**Comment by ishparsh** [comment]
@glenn-jocher  I fixed the issue. I just had to change the yaml file where the number of class for my model is 43. 
Thank you so much for your help!!!!

**Comment by glenn-jocher** [comment]
Hi @ishparsh,

That's fantastic to hear! 🎉 I'm glad you were able to resolve the issue by updating the YAML file to reflect the correct number of classes for your model. 

If you have any more questions or run into any other issues, feel free to reach out. We're here to help! 😊

Happy coding and best of luck with your project!
