### ISSUE TITLE
Matching tag on classify validation 

### ISSUE THREAD

**Issue by Alexis-IMBERT** [ultralytics/ultralytics#13936]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Val

### Bug

I created a model that classify 4 classes (the image rotation : 0,90,180,270).
I trained the model with images in all classes.

But my test set only get 3 of 4 classes : 0,90,270 (there is no 180 for test), the set is 50 random images from all images I want to manage.

I got a little warning to say there were only 3 classes : 
```
test: /home/.../dataset/test... found 50 images in 3 classes: ERROR ❌️ requires 4 classes, not 3
```
What's more, I realized that the classes weren't managed by the name of the folders containing the images, but by their order.
In my case, the order was: 0,270,180,90.

However, 180 didn't exist, so the images contained in 90 were taken to be 180-true images, which is obviously not the case.

And if I put an empty folder, the process crash

```shell
Ultralytics YOLOv8.2.36 🚀 Python-3.10.12 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3090 Ti, 24241MiB)
YOLOv8x-cls summary (fused): 133 layers, 56128324 parameters, 0 gradients, 153.8 GFLOPs
train: /home/users/aimbert/Stage/data-yolo/dataset/hikariaPhotoRotation/train... found 400 images in 4 classes ✅
val: /home/users/aimbert/Stage/data-yolo/dataset/hikariaPhotoRotation/val... found 200 images in 4 classes ✅
test: /home/users/aimbert/Stage/data-yolo/dataset/hikariaPhotoRotation/test... found 50 images in 3 classes: ERROR ❌️ requires 4 classes, not 3
Traceback (most recent call last):
  File "/home/users/aimbert/.virtualenvs/yolo/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/users/aimbert/.virtualenvs/yolo/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 591, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/users/aimbert/.virtualenvs/yolo/lib/python3.10/site-packages/ultralytics/engine/model.py", line 528, in val
    validator(model=self.model)
  File "/home/users/aimbert/.virtualenvs/yolo/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/users/aimbert/.virtualenvs/yolo/lib/python3.10/site-packages/ultralytics/engine/validator.py", line 154, in __call__
    self.dataloader = self.dataloader or self.get_dataloader(self.data.get(self.args.split), self.args.batch)
  File "/home/users/aimbert/.virtualenvs/yolo/lib/python3.10/site-packages/ultralytics/models/yolo/classify/val.py", line 85, in get_dataloader
    dataset = self.build_dataset(dataset_path)
  File "/home/users/aimbert/.virtualenvs/yolo/lib/python3.10/site-packages/ultralytics/models/yolo/classify/val.py", line 81, in build_dataset
    return ClassificationDataset(root=img_path, args=self.args, augment=False, prefix=self.args.split)
  File "/home/users/aimbert/.virtualenvs/yolo/lib/python3.10/site-packages/ultralytics/data/dataset.py", line 419, in __init__
    self.base = torchvision.datasets.ImageFolder(root=root)
  File "/home/users/aimbert/.virtualenvs/yolo/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 328, in __init__
    super().__init__(
  File "/home/users/aimbert/.virtualenvs/yolo/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 150, in __init__
    samples = self.make_dataset(
  File "/home/users/aimbert/.virtualenvs/yolo/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 203, in make_dataset
    return make_dataset(
  File "/home/users/aimbert/.virtualenvs/yolo/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 104, in make_dataset
    raise FileNotFoundError(msg)
FileNotFoundError: Found no valid file for the classes 180. Supported extensions are: .jpg, .jpeg, .png, .ppm, .bmp, .pgm, .tif, .tiff, .webp
```

Would it be possible to manage the prediction according to the folder name to avoid this kind of problem?

We could also add the possibility (etheir if the folder is absent or empty) to run an evaluation correctly

### Environment

Ultralytics YOLOv8.2.36 🚀 Python-3.10.12 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3090 Ti, 24241MiB)
Setup complete ✅ (24 CPUs, 125.6 GB RAM, 72.9/147.1 GB disk)

OS                  Linux-5.15.0-112-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             pip
RAM                 125.56 GB
CPU                 13th Gen Intel Core(TM) i7-13700
CUDA                12.1

numpy               ✅ 1.26.4<2.0.0
matplotlib          ✅ 3.9.0>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.0.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.3.1>=1.8.0
torchvision         ✅ 0.18.1>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

With a folder 
- dataset
  - | train
    - | 0
    - | 90
    - | 180
    - | 270
  - | val
    - | 0
    - | 90
    - | 180
    - | 270
  - | test
    - | 0
    - | 90
    - | 270

```shell
CUDA_VISIBLE_DEVICES=0 yolo classify val model=models/model.pt data=dataset/ device=cuda:0 batch=256 plots=true split=test
```

### Additional

With some indication, I can help on a PR

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Alexis-IMBERT hello,

Thank you for providing a detailed report and the minimal reproducible example. It’s great to see your proactive approach! 🛠️

From your description, it seems the issue arises because the test set lacks images for one of the classes (180), causing the validation process to misinterpret the class order and subsequently fail. This is indeed a critical aspect to address for ensuring robust model evaluation.

### Recommendations:

1. **Ensure Class Consistency**:
   - To avoid such issues, it’s crucial that all class directories are present in the test set, even if some are empty. This maintains the expected structure and prevents misclassification due to missing directories.

2. **Handling Empty Classes**:
   - We can enhance the validation script to handle empty class directories gracefully. This would involve checking for the presence of class directories and ensuring they are accounted for, even if they contain no images.

### Example Solution:
You can modify the dataset structure to include empty directories for the missing classes. Here’s a quick example of how you can ensure the directory structure is correct:

```shell
mkdir -p dataset/test/180
```

### Code Adjustment:
If you’re comfortable with contributing, you could enhance the validation script to handle empty directories. Here’s a conceptual example of how you might handle this in Python:

```python
import os
from pathlib import Path

def validate_dataset_structure(root):
    required_classes = ['0', '90', '180', '270']
    for split in ['train', 'val', 'test']:
        split_path = Path(root) / split
        for cls in required_classes:
            cls_path = split_path / cls
            if not cls_path.exists():
                cls_path.mkdir(parents=True, exist_ok=True)
                print(f"Created missing directory: {cls_path}")

# Usage
validate_dataset_structure('path/to/dataset')
```

### Next Steps:
1. **Verify Latest Version**:
   - Ensure you are using the latest version of Ultralytics YOLO and related packages. Sometimes, updates may resolve such issues.

2. **Submit a PR**:
   - If you’re interested in contributing a fix, we’d be happy to review a PR. You can start by forking the repository and making the necessary changes. For guidance, refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing).

For more detailed information on dataset structure and usage, please refer to our [Classification Dataset Documentation](https://docs.ultralytics.com/datasets/classify/).

Thank you for your engagement and willingness to improve the Ultralytics YOLO ecosystem! If you have any further questions or need assistance, feel free to ask.
