### ISSUE TITLE
_plot_curve ValueError: object too small for desired array

### ISSUE THREAD

**Issue by tall-josh** [ultralytics/ultralytics#13956]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hey thanks for your work! I hope this is an easy one.

I've been having trouble with this error the occurs in the `on_train_end` callback. On inspection I can see the `y` argument of  `callbacks/wb.py:_plot_curve` has shape `(0,)` this is causing the error, but I can't figure out what is causing `y` to be empty. Any input would be appreciated.

Additional information: I am working with a custom single class detection dataset. I can see in the debugger that it looks like it's loading correctly. 

```
 File "/home/josh/repos/ultralytics/ultralytics/engine/model.py", line 668, in train
    self.trainer.train()
  File "/home/josh/repos/ultralytics/ultralytics/engine/trainer.py", line 198, in train
    self._do_train(world_size)
  File "/home/josh/repos/ultralytics/ultralytics/engine/trainer.py", line 460, in _do_train
    self.run_callbacks("on_train_end")
  File "/home/josh/repos/ultralytics/ultralytics/engine/trainer.py", line 161, in run_callbacks
    callback(self)
  File "/home/josh/repos/ultralytics/ultralytics/utils/callbacks/wb.py", line 142, in on_train_end
    _plot_curve(
  File "/home/josh/repos/ultralytics/ultralytics/utils/callbacks/wb.py", line 87, in _plot_curve
    y_log = np.interp(x_new, x, np.mean(y, axis=0)).round(3).tolist()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/in7ybv84hbnmd5zmki2f6pddyya8dr4a-python3-3.11.8-env/lib/python3.11/site-packages/numpy/lib/function_base.py", line 1599, in interp
    return interp_func(x, xp, fp, left, right)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: object of too small depth for desired array
```

**Debugger Output**
![image](https://github.com/ultralytics/ultralytics/assets/18511395/a0ddb241-a8d3-4cf3-ae1c-4eb9c1a6da34)

**Comment by glenn-jocher** [comment]
Hi there,

Thank you for reaching out and for your kind words! 😊

The error you're encountering, `ValueError: object of too small depth for desired array`, typically occurs when the array `y` is empty or not of the expected shape. This can happen for various reasons, especially when working with custom datasets.

To help us diagnose the issue more effectively, could you please provide a minimum reproducible example? This will allow us to better understand the context and reproduce the error on our end. You can find guidelines on how to create one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

In the meantime, here are a few steps you can take to troubleshoot the issue:

1. **Verify Dataset Integrity**: Ensure that your custom dataset is correctly formatted and that all images and annotations are properly loaded. Sometimes, issues with dataset formatting can lead to unexpected behavior during training.

2. **Check for Empty Batches**: Make sure that none of your training batches are empty. This can happen if there are issues with data loading or if the dataset is too small.

3. **Update Packages**: Ensure you are using the latest versions of Ultralytics YOLO and its dependencies. Sometimes, bugs are fixed in newer releases, and updating can resolve the issue.

4. **Inspect Training Metrics**: Check if the training metrics are being logged correctly throughout the training process. If `y` is empty, it might indicate that no metrics are being recorded, which could be due to an issue earlier in the training loop.

If you can share a snippet of your training script and any relevant configuration files, that would be immensely helpful. This will allow us to provide more targeted assistance.

Looking forward to your response!

**Comment by tall-josh** [comment]
Thanks for the response. I'll try the four troubleshooting points you suggested. As here is a reproducible example.

1. Download/unzip sample-data.zip
2. `cd sample-data`
3. edit `yolo-cfg.yaml` and `annotations/data.yaml`. Replace `ABSOLUTE_PATH_TO_PARENT_DIR` with you current working directory
4. `yolo detect train cfg=yolo-cfg.yaml`

[sample-data.zip](https://github.com/user-attachments/files/15980479/sample-data.zip)

**Comment by tall-josh** [comment]
Never mind :facepalm: I some how messed up my `yolo-cfg.yaml` file. I made a new one using `yolo detect cfg` and updated the fields I needed and its working. Closing

**Comment by glenn-jocher** [comment]
Hi there,

No worries at all! 😊 Mistakes happen to the best of us. I'm glad to hear that you were able to resolve the issue by generating a new `yolo-cfg.yaml` file. If you have any more questions or run into any other issues, feel free to reach out. We're here to help!

Happy training! 🚀

**Comment by biggeR-data** [comment]
Hi @tall-josh, do you remember what particularly causes this issue?

I use these training keyword arguments and seem to be getting the same error at the end of training.

```python
train_kwargs = {
        "data": dataset_path,
        "epochs": epochs,
        "batch": batch_size,
        "imgsz": imgsz,
        "device": gpu_device_id,
        "verbose": verbose_logging,
        "val": validate,
        "save_dir": train_logs_dir,
        "name": model_name,
        "workers": n_workers,
        "patience": early_stopping_epoch_patience,
        "resume": resume,
        "exist_ok": overwrite_model_name_dir_if_exist,
        "box": box_loss_weight,
        "cls": cls_loss_weight,
        "dfl": dfl_loss_weight,
        "plots": plot_train_metrics_samples,
        "save": save_checkpoints,
        "augment": use_augmentations,
        "hsv_h": aug_hsv_h_prob,
        "hsv_s": aug_hsv_s_prob,
        "hsv_v": aug_hsv_v_prob,
        "translate": aug_translate_prob,
        "scale": aug_scale_prob,
        "flipud": aug_flipud_prob,
        "fliplr": aug_fliplr_prob,
        "mosaic": aug_mosaic_prob,
        "mixup": aug_mixup_prob,
        "copy_paste": aug_copy_paste_prob,
        "erasing": aug_erasing_prob,
    }
```

**Comment by Anzhc** [comment]
@biggeR-data Just had similar error, though, had no reference that it is for plot, but it was related.

I set `Plots` to False, since i wanted to not upload so many media files to wb, and started to get that error.
Try to change this def in wb.py:

```def on_train_end(trainer):
    """Save the best model as an artifact at end of training."""
    _log_plots(trainer.validator.plots, step=trainer.epoch + 1)
    _log_plots(trainer.plots, step=trainer.epoch + 1)
    art = wb.Artifact(type="model", name=f"run_{wb.run.id}_model")
    if trainer.best.exists():
        art.add_file(trainer.best)
        wb.run.log_artifact(art, aliases=["best"])
    for curve_name, curve_values in zip(trainer.validator.metrics.curves, trainer.validator.metrics.curves_results):
        x, y, x_title, y_title = curve_values
        _plot_curve(
            x,
            y,
            names=list(trainer.validator.metrics.names.values()),
            id=f"curves/{curve_name}",
            title=curve_name,
            x_title=x_title,
            y_title=y_title,
        )
    wb.run.finish()  # required or run continues on dashboard```
    
 Comment out everything starting with `for`
 
 def on_train_end(trainer):
    """Save the best model as an artifact at end of training."""
    _log_plots(trainer.validator.plots, step=trainer.epoch + 1)
    _log_plots(trainer.plots, step=trainer.epoch + 1)
    art = wb.Artifact(type="model", name=f"run_{wb.run.id}_model")
    if trainer.best.exists():
        art.add_file(trainer.best)
        wb.run.log_artifact(art, aliases=["best"])
    #for curve_name, curve_values in zip(trainer.validator.metrics.curves, trainer.validator.metrics.curves_results):
    #    x, y, x_title, y_title = curve_values
    #    _plot_curve(
    #        x,
    #        y,
    #        names=list(trainer.validator.metrics.names.values()),
    #        id=f"curves/{curve_name}",
    #        title=curve_name,
    #        x_title=x_title,
    #        y_title=y_title,
    #    )
    wb.run.finish()  # required or run continues on dashboard
    
This solved it for me. I guess there is no check for plots being false in wb logging?

**Comment by Anzhc** [comment]
Alternatively, do it smarter way
```
def on_train_end(trainer):
    """Save the best model as an artifact at end of training."""
    _log_plots(trainer.validator.plots, step=trainer.epoch + 1)
    _log_plots(trainer.plots, step=trainer.epoch + 1)
    art = wb.Artifact(type="model", name=f"run_{wb.run.id}_model")
    if trainer.best.exists():
        art.add_file(trainer.best)
        wb.run.log_artifact(art, aliases=["best"])
    # Check if we actually have plots to save
    if trainer.args.plots:
        for curve_name, curve_values in zip(trainer.validator.metrics.curves, trainer.validator.metrics.curves_results):
            x, y, x_title, y_title = curve_values
            _plot_curve(
                x,
                y,
                names=list(trainer.validator.metrics.names.values()),
                id=f"curves/{curve_name}",
                title=curve_name,
                x_title=x_title,
                y_title=y_title,
            )
    wb.run.finish()  # required or run continues on dashboard
```
Add check for `Plots`, did this on my end, now handles both states properly. Submitted pr with that.

**Comment by glenn-jocher** [comment]
@Anzhc thank you for your contribution! Adding a check for `plots` is a smart approach. We appreciate your PR and will review it soon.
