### ISSUE TITLE
how to use two models at once

### ISSUE THREAD

**Issue by faizelkDatapost** [ultralytics/ultralytics#1396]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to use two models. First model detects people only and for each person's bounding box i want to parse to a new model to go look for a face. 
```
my main file looks like below and works:

//detecting people/person
from ultralytics import YOLO
model = YOLO("yolov8s.pt")
results = model.track(source="0", save=False, classes=[0], conf=0.5, show=True, imgsz=320,verbose=False,stream=True)
for result in results:
        result = result.numpy()
```

//what i tried, where and how
//on ultralytics/yolo/utils/plotting.py function def box_label
i am trying to detect a face from the person bounding box, I know i can just train one model to detect person and face but I tried a new instance of YOLO which would load the face model. I tried like below and I cannot get this to work.

```
face_model = YOLO("face_yolov8n.pt")
face_results= face_model(source=cropped_person, conf=0.2, verbose=False)
```

I keep getting this error 
"cannot import name 'YOLO' from partially initialized module 'ultralytics' (most likely due to a circular import)"

I tried extending / adding new class on  file ultralytics/yolo/engine/model.py and also  __init__.py

Can two models be used by any chance, specifically on plotting.py because this is where the actual boxes are found while on detection?

**Comment by glenn-jocher** [comment]
Yes, it is possible to use two models for your task. The error you are getting seems to be related to a circular import issue, which occurs when two modules import each other in a way that causes a loop. You can avoid this by importing the YOLO class directly from the model.py file, instead of from the __init__.py file.

Here's an example of how you can modify the plot_one_box function in ultralytics/yolo/utils/plotting.py to detect faces using another YOLO model:

```python
from ultralytics.yolo.engine.model import YOLO

def plot_one_box(x, img, color=None, label=None, line_thickness=None, face_model=None):
    # code to draw box and label

    # crop image to person bounding box
    cropped_person = img[y1:y2, x1:x2]

    # detect face using face model
    if face_model is not None:
        face_results = face_model(cropped_person, conf=0.2, verbose=False)
        # code to get face bounding box and draw box and label

    return img
```

In your main file, you can create an instance of the face model and pass it to the plot_one_box function like this:

```python
from ultralytics.yolo.utils.plotting import plot_one_box

face_model = YOLO("face_yolov8n.pt")
for result in results:
    result = result.numpy()
    img = plot_one_box(result, img, face_model=face_model)
```
This way, for each person bounding box detected by the first YOLO model, the face model will be used to detect faces within the bounding box, and the face boxes will be drawn on the image. Note that you will need to modify the plot_one_box function to extract the face bounding box from the face_results object returned by the face model.
