### ISSUE TITLE
YOLOV8 at 0.0 confidence?

### ISSUE THREAD

**Issue by Teymoor-Ali** [ultralytics/ultralytics#13984]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, i was wondering what is going on when i set the object detection confidence to 0.0?

(im working on detecting certain insects on a flytrap)

Usually im expecting to detect pretty much everything (i.e bounding boxes everwhere on every type of insect) but what im getting is minimal amount of detections and mostly on the insects i have trained it on?

Whats going on with the architecture that filters out most of these low confidence detections even when its set to 0?

I took a pre-trained model and trained it on a certain type of insect but those insects are very similar to others so im surprised why its not detecting them.

Thanks!

**Comment by glenn-jocher** [comment]
@Teymoor-Ali hi there,

Thank you for reaching out with your question! When you set the object detection confidence to 0.0, you might expect the model to detect everything indiscriminately. However, the architecture of YOLO models includes several internal mechanisms that influence the final detections, even when the confidence threshold is set to zero.

Here are a few key points to consider:

1. **Non-Maximum Suppression (NMS)**: YOLO models apply NMS to filter out overlapping bounding boxes. This process helps in retaining the most confident detections while suppressing others, which might explain why you're seeing fewer detections than expected.

2. **Model Training and Generalization**: Since you trained the model on a specific type of insect, it has learned to distinguish those insects from others. If the insects are very similar, the model might still be able to differentiate them based on subtle features it learned during training.

3. **Internal Confidence Filtering**: Even with a confidence threshold of 0.0, the model might internally filter out detections that it deems too uncertain. This is part of the model's design to ensure that only meaningful detections are considered.

To better understand and address your issue, could you provide a minimum reproducible example? This will help us diagnose the problem more effectively. You can find guidelines on how to create one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure you are using the latest version of the Ultralytics package, as updates often include important fixes and improvements.

If you have any further questions or need additional assistance, feel free to ask. We're here to help! 😊

**Comment by Teymoor-Ali** [comment]
Hi Glen,

Is it possible to turn them off without breaking everything ?
