### ISSUE TITLE
exe file for yolov8 using openvino goes on loop 

### ISSUE THREAD

**Issue by AnshulVijay** [ultralytics/ultralytics#14010]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Without using freeze_support it goes on loop, even incase of model export to openvino, this exe is facing same issue.
import multiprocessing
from ultralytics import YOLO

def main():
    print("conversion started")
    model = YOLO("C:/Users/user/Downloads/openvino_model/")
    results = model.predict("C:/Users/user/Downloads/IMG20220615131626.jpg")
    print(results)
    print("conversion completed")

if __name__ == "__main__":
    multiprocessing.freeze_support()
    main()

I saw a reported issue where using freeze_support issue is resolved, but it gives below error
![image](https://github.com/ultralytics/ultralytics/assets/28283505/59d742d3-8ed1-477f-bd7a-38391e699251)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@AnshulVijay hi there,

Thank you for bringing this issue to our attention. It seems like you're encountering a looping issue when running your YOLOv8 model with OpenVINO, and using `multiprocessing.freeze_support()` resolves the loop but introduces a new error.

To better assist you, could you please provide a minimal reproducible example of your code? This will help us diagnose the issue more effectively. You can find guidelines on creating a minimal reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

In the meantime, please ensure that you are using the latest versions of all relevant packages, including Ultralytics YOLO and OpenVINO. Sometimes, updating to the latest version can resolve unexpected issues.

Here's a quick example of how you might structure your code to avoid the loop issue:

```python
import multiprocessing
from ultralytics import YOLO

def main():
    print("Conversion started")
    model = YOLO("C:/Users/user/Downloads/openvino_model/")
    results = model.predict("C:/Users/user/Downloads/IMG20220615131626.jpg")
    print(results)
    print("Conversion completed")

if __name__ == "__main__":
    multiprocessing.freeze_support()
    main()
```

If you continue to face issues, please share the specific error message you are encountering when using `freeze_support()`. This will help us provide more targeted assistance.

Thank you for your cooperation, and we look forward to resolving this issue together! 😊

**Comment by glenn-jocher** [comment]
Hi @AnshulVijay,

Thank you for providing additional details and the command you're using to convert your Python script to an executable. It looks like you're encountering an issue with the executable file generated by PyInstaller.

To help us better understand and resolve the issue, could you please provide a minimal reproducible example of your code? This will allow us to diagnose the problem more effectively. You can find guidelines on creating a minimal reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

In the meantime, here are a few suggestions that might help resolve the issue:

1. **Ensure Latest Versions**: Make sure you are using the latest versions of Ultralytics YOLO and OpenVINO. Sometimes, updating to the latest version can resolve unexpected issues.

2. **PyInstaller Configuration**: When using PyInstaller, it's important to ensure that all dependencies are correctly included. You might need to adjust your PyInstaller command to explicitly include additional dependencies. For example:
    ```bash
    pyinstaller.exe --onefile -F --add-data "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics;ultralytics" --hidden-import="ultralytics" Yolov8_openvino_conversion.py
    ```

3. **Check for Missing Dependencies**: Sometimes, certain dependencies might not be included automatically. You can use the `--hidden-import` flag to include them manually.

4. **Debugging with PyInstaller**: You can use the `--debug` flag with PyInstaller to get more detailed output, which might help identify the root cause of the issue:
    ```bash
    pyinstaller.exe --onefile -F --debug all --add-data "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics;ultralytics" Yolov8_openvino_conversion.py
    ```

If the issue persists, please share the specific error message or any additional logs you receive. This will help us provide more targeted assistance.

Thank you for your cooperation, and we look forward to resolving this issue together! 😊

**Comment by zoldaten** [comment]
thanks for help i fixed the same issue with yolo train.
but in my case it all leads to hang on of train process (( :
![2024-08-28_15h07_17](https://github.com/user-attachments/assets/7e909f02-40ef-4874-b8fa-2850f4a74550)

the code example looks like:

```
from ultralytics import YOLO
import multiprocessing
os.environ['WANDB_DISABLED'] = 'true'

    model = YOLO('yolov8n.pt',verbose=True)
    model.train(data='data.yaml', epochs=5,device='cpu')

if __name__=="__main__":
    multiprocessing.freeze_support()
    main()
```

*exe made by `pyinstaller --onedir --collect-all ultralytics file.py`

**Comment by glenn-jocher** [comment]
@zoldaten thanks for the update. If the training process hangs, please ensure you're using the latest version of Ultralytics YOLO. If the issue persists, try running the script without PyInstaller to isolate the problem.

**Comment by zoldaten** [comment]
ok. fix it.
```
if __name__=="__main__":
    multiprocessing.freeze_support()
    child1 = Process(target=task1) #main code
    child1.start()    
    child1.join()
       
    child2 = Process(target=task2) # train of yolo
    child2.start()    
    child2.join()
```

exe starts working only in that way.

**Comment by zoldaten** [comment]
> @zoldaten thanks for the update. If the training process hangs, please ensure you're using the latest version of Ultralytics YOLO. If the issue persists, try running the script without PyInstaller to isolate the problem.

issue still presents (( script without Pyinstaller works well.

when i start **exe** i see 2 instances of my script appear:
![2024-08-29_12h44_33](https://github.com/user-attachments/assets/6bc48546-f7c4-47e9-a983-7835fd2aa918)

i tried to fix issue with wmi - https://github.com/ultralytics/ultralytics/issues/10115
but no success.

i also tried to change code :

```
from ultralytics import YOLO
import multiprocessing
os.environ['WANDB_DISABLED'] = 'true'

def task1():
    ...some other code...

def task2():
    model = YOLO('yolov8n.pt',verbose=True)
    model.train(data='data.yaml', epochs=5,device='cpu')



if __name__=="__main__":
    multiprocessing.freeze_support()
    child1 = Process(target=task1) #main code
    child1.start()    
    child1.join()
       
    child2 = Process(target=task2) # train of yolo
    child2.start()    
    child2.join()
```

**Comment by glenn-jocher** [comment]
Thank you for the detailed update. Since the script works without PyInstaller, the issue likely lies in how PyInstaller handles multiprocessing. Please ensure you're using the latest versions of all packages. If the problem persists, consider using an alternative packaging tool like `cx_Freeze` or `py2exe` to see if it resolves the issue.

**Comment by zoldaten** [comment]
fixed that. the problem was with torch==2.4.0 
i downgraded to 2.2.0 and everything starts working !

thanks for help.

**Comment by glenn-jocher** [comment]
Glad to hear you resolved the issue by downgrading PyTorch. If you encounter any further problems, feel free to reach out. Happy coding!

**Comment by zoldaten** [comment]
i also build file with Nuitka:
`nuitka --standalone project.py --module-parameter=torch-disable-jit=no`
but have to add by hands default.yaml to project (after compilation by nuitka):
```
project.dist\ultralytics\cfg\default.yaml
from
venv\ultralytics\cfg\default.yaml
```

**Comment by glenn-jocher** [comment]
Thank you for sharing your experience with Nuitka. It's good to know that adding `default.yaml` manually resolved the issue. If you encounter any further problems, please let us know.
