### ISSUE TITLE
When I was training the dataset, I enabled AMP. I downloaded yolov8n.pt into the ultralytics folder and the ultralytics/ultralytics folder. During the first few training sessions, I wasn't prompted to download yolov8n.pt, but after training a few times, I was prompted that AMP needs to download yolov8n.pt and it keeps waiting for the download. My server is extremely slow at downloading from GitHub, so I want to know where exactly I should place the .pt file so that it can be automatically detected during runtime?

### ISSUE THREAD

**Issue by HoungJee** [ultralytics/ultralytics#14012]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I was training the dataset, I enabled AMP. I downloaded yolov8n.pt into the ultralytics folder and the ultralytics/ultralytics folder. During the first few training sessions, I wasn't prompted to download yolov8n.pt, but after training a few times, I was prompted that AMP needs to download yolov8n.pt and it keeps waiting for the download. My server is extremely slow at downloading from GitHub, so I want to know where exactly I should place the .pt file so that it can be automatically detected during runtime?

**Comment by Y-T-G** [comment]
The folder where you are running the script from.

**Comment by glenn-jocher** [comment]
Hi there!

Thank you for your question. To ensure that the `yolov8n.pt` file is automatically detected during runtime, you should place it in the directory where you are running your training script. This is typically the current working directory from which you execute your Python script or command-line interface (CLI) commands.

Here’s a step-by-step guide to help you:

1. **Place the Model File**: Move or copy the `yolov8n.pt` file to the directory where your training script is located. This ensures that the script can easily find the model file without needing to download it again.

2. **Verify the Path**: When you specify the model in your training command, ensure that the path is correct. For example, if your script and model file are in the same directory, you can simply use:
    ```bash
    yolo train data=coco128.yaml model=yolov8n.pt epochs=100 imgsz=640
    ```

3. **Check Permissions**: Ensure that the file has the appropriate read permissions so that the script can access it without any issues.

If you continue to experience issues, please provide a minimum reproducible example of your script and training command. This will help us diagnose the problem more effectively. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, make sure you are using the latest version of the Ultralytics package to benefit from the latest fixes and improvements.

Feel free to reach out if you have any more questions or need further assistance. Happy training! 🚀

**Comment by Tpinion** [comment]
This situation seem to caused by a hard code at ultralytics/utils/checks.py:659
Can provide a interface to let me specify a exist model path?
![image](https://github.com/ultralytics/ultralytics/assets/27395365/023c82e7-7a68-4c63-9456-c3c97c7fb7d9)

**Comment by glenn-jocher** [comment]
Hi there!

Thank you for bringing this to our attention. It seems like you're encountering an issue with the hardcoded path in `ultralytics/utils/checks.py` that affects the detection of the `yolov8n.pt` model file.

To address this, you can specify the path to your existing model file directly in your training command or script. Here’s how you can do it:

### Using the Command Line Interface (CLI)
If you are using the CLI, you can specify the model path directly:
```bash
yolo train data=coco128.yaml model=path/to/your/yolov8n.pt epochs=100 imgsz=640
```

### Using Python Script
If you are using a Python script, you can load the model with the specified path:
```python
from ultralytics import YOLO

# Load the model from the specified path
model = YOLO('path/to/your/yolov8n.pt')

# Train the model
results = model.train(data='coco128.yaml', epochs=100, imgsz=640)
```

### Providing a Reproducible Example
If the issue persists, it would be very helpful if you could provide a minimum reproducible example. This will allow us to better understand the problem and provide a more accurate solution. You can find guidelines on creating a reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

### Updating to the Latest Version
Please ensure you are using the latest version of the Ultralytics package, as updates often include important bug fixes and improvements. You can update the package using:
```bash
pip install --upgrade ultralytics
```

We appreciate your patience and cooperation. If you have any further questions or need additional assistance, feel free to ask. 😊
