### ISSUE TITLE
During inference, conf too low produces nan in boxes

### ISSUE THREAD

**Issue by bw-pt** [ultralytics/ultralytics#14027]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I am running the latest ultralytics version 8.2.43.

When using YOLOv10x, and setting conf to 0.05 or lower, some of the boxes in the prediction results would contain coordinates of nan. 

`
from ultralytics import YOLO

model_detect= YOLO('yolov10x.pt')

r_detect = model_detect(img_tensors, conf=0.01)

r_detect[-1].boxes

Out[165]: 
ultralytics.engine.results.Boxes object with attributes:
cls: tensor([ 9., 14.,  9., 14.], device='cuda:0', dtype=torch.float16)
conf: tensor([0.1896, 0.0538, 0.0272, 0.0118], device='cuda:0', dtype=torch.float16)
data: tensor([[       nan,        nan,        nan,        nan, 1.8958e-01, 9.0000e+00],
        [       nan,        nan,        nan,        nan, 5.3802e-02, 1.4000e+01],
        [       nan,        nan,        nan,        nan, 2.7176e-02, 9.0000e+00],
        [       nan,        nan,        nan,        nan, 1.1826e-02, 1.4000e+01]], device='cuda:0', dtype=torch.float16)
id: None
is_track: False
orig_shape: (512, 512)
shape: torch.Size([4, 6])
xywh: tensor([[nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan]], device='cuda:0', dtype=torch.float16)
xywhn: tensor([[nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan]], device='cuda:0', dtype=torch.float16)
xyxy: tensor([[nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan]], device='cuda:0', dtype=torch.float16)
xyxyn: tensor([[nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan],
        [nan, nan, nan, nan]], device='cuda:0', dtype=torch.float16)

`

### Environment

Ultralytics YOLOv8.2.43 🚀 Python-3.11.9 torch-2.3.1+cu118 CUDA:0 (NVIDIA GeForce GTX 1660 SUPER, 6144MiB)
Setup complete ✅ (16 CPUs, 31.9 GB RAM, 239.0/430.6 GB disk)

OS                  Windows-10-10.0.22631-SP0
Environment         Windows
Python              3.11.9
Install             pip
RAM                 31.91 GB
CPU                 Intel Core(TM) i7-10700KF 3.80GHz
CUDA                11.8

numpy               ✅ 1.26.4<2.0.0,>=1.23.5
matplotlib          ✅ 3.8.4>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.28.2>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.3.1+cu118>=1.8.0
torchvision         ✅ 0.18.1+cu118>=0.9.0
tqdm                ✅ 4.65.2>=4.64.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 1.5.3>=1.1.4
seaborn             ✅ 0.12.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

from ultralytics import YOLO

model_detect= YOLO('yolov10x.pt')

r_detect = model_detect(img_tensors, conf=0.01)

r_detect[-1].boxes

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@bw-pt thank you for reporting this issue and providing a detailed description along with the code snippet. It’s very helpful! 😊

The occurrence of `nan` values in the bounding box coordinates when setting a low confidence threshold (`conf`) is indeed concerning. Here are a few steps to help diagnose and potentially resolve the issue:

1. **Reproducible Example**: While you've provided a good starting point, it would be beneficial to have a complete minimal reproducible example. This helps us replicate the issue on our end. Please refer to our guide on creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example).

2. **Latest Version**: Ensure that you are using the latest version of the Ultralytics package. Sometimes, issues are resolved in newer releases. You can update the package using:
   ```bash
   pip install -U ultralytics
   ```

3. **Validation**: Verify if the issue persists with different models or datasets. This can help determine if the problem is specific to the `YOLOv10x` model or a broader issue.

4. **Code Example**: Here’s a slightly modified version of your code to include a check for `nan` values and handle them gracefully:
   ```python
   from ultralytics import YOLO
   import torch

   # Load the model
   model_detect = YOLO('yolov10x.pt')

   # Perform inference with a low confidence threshold
   r_detect = model_detect(img_tensors, conf=0.01)

   # Check for nan values in the bounding boxes
   boxes = r_detect[-1].boxes
   if torch.isnan(boxes.data).any():
       print("Warning: Detected nan values in the bounding boxes.")
       # Handle nan values, for example, by filtering them out
       valid_boxes = boxes.data[~torch.isnan(boxes.data).any(dim=1)]
       print(valid_boxes)
   else:
       print(boxes)
   ```

5. **Further Investigation**: If the issue persists, please provide additional details such as the specific dataset and any preprocessing steps you are using. This will help us investigate further.

We appreciate your patience and cooperation in resolving this issue. If you have any more questions or need further assistance, feel free to ask. The YOLO community and the Ultralytics team are here to help! 🚀
