### ISSUE TITLE
Discrepency of mAP calculation between YOLOv8 and COCO API

### ISSUE THREAD

**Issue by ZYJIQVV** [ultralytics/ultralytics#14063]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I recently am using YOLOv8 detection model. I find that the mAP calculated by COCO API would be a litter lower than by YOLOv8.
After searching on the internet, I learnt some thought it is because the 2 differences that the results are different:

1. the interpolation functions are not the same. YOLOv8 uses np.interp while COCO uses np.searchsorted
YOLOv8:
![image](https://github.com/ultralytics/ultralytics/assets/111969464/945262d2-ad0c-4780-94be-2fae3c0ce1c2)
COCO:
![image](https://github.com/ultralytics/ultralytics/assets/111969464/fcbd4d6e-fba3-4b98-b1e0-d6db68c73076)

2. YOLOv8 uses integration to calculate mAP while COCO simply uses "mean" function
YOLOv8:
![image](https://github.com/ultralytics/ultralytics/assets/111969464/c836307c-45f8-479c-ae62-c4dd4a66f8ba)
COCO:
![image](https://github.com/ultralytics/ultralytics/assets/111969464/819a0f23-c0f2-4847-aca0-3dcf299d89ee)

So I tried to use the approaches in COCO to modify YOLOv8 but the two mAP result are still different.

So I'd like to ask if you could provide me more details of these 2 approaches and their true discrepencies and how to modify YOLOv8 so as to let it produce the same result as COCO API.

And one more question, when I set the max_det=300 in COCO, mAP50:95 sometimes is negative, which I can't understand. If you know the reason please tell me.

Thanks!

**Comment by glenn-jocher** [comment]
@ZYJIQVV hello,

Thank you for your detailed question and for providing the context regarding the discrepancy in mAP calculations between YOLOv8 and the COCO API. This is indeed an important topic for ensuring consistent evaluation metrics across different tools.

### Discrepancy in mAP Calculation

The differences you've highlighted between YOLOv8 and COCO API in terms of interpolation methods and integration approaches are correct. YOLOv8 uses `np.interp` for interpolation and integrates to calculate mAP, while COCO API uses `np.searchsorted` and a mean function. These differences can lead to slight variations in the mAP values.

To align YOLOv8's mAP calculation with the COCO API, you can modify the evaluation code in YOLOv8 to use the same methods as COCO. Here’s a brief outline of what you might need to do:

1. **Interpolation Method**: Replace `np.interp` with `np.searchsorted` in the mAP calculation.
2. **Integration Method**: Replace the integration approach with a simple mean function.

Here is a simplified example to illustrate how you might adjust the interpolation method:

```python
import numpy as np

# Example of using np.searchsorted instead of np.interp
def coco_interpolation(x, y, x_new):
    idx = np.searchsorted(x, x_new, side='left')
    y_new = y[idx - 1] + (y[idx] - y[idx - 1]) * (x_new - x[idx - 1]) / (x[idx] - x[idx - 1])
    return y_new

# Example data
x = np.array([0, 1, 2, 3])
y = np.array([0, 1, 4, 9])
x_new = np.array([0.5, 1.5, 2.5])

# Using the custom interpolation function
y_new = coco_interpolation(x, y, x_new)
print(y_new)
```

For the integration method, you can replace the integration logic with a mean calculation:

```python
# Example of using mean instead of integration
def coco_mean(y):
    return np.mean(y)

# Example data
y = np.array([0, 1, 4, 9])

# Using the mean function
mean_value = coco_mean(y)
print(mean_value)
```

### Negative mAP Values with max_det=300

Regarding the negative mAP values when setting `max_det=300`, this is unusual and typically indicates an issue with the evaluation setup or the data. Here are a few things to check:

1. **Data Integrity**: Ensure that the dataset annotations and predictions are correctly formatted and aligned.
2. **Evaluation Code**: Verify that the evaluation code correctly handles the `max_det` parameter and does not introduce any errors.
3. **Metric Calculation**: Double-check the logic for calculating mAP to ensure it handles edge cases appropriately.

If the issue persists, providing a minimum reproducible example would be very helpful for further investigation. You can find guidelines for creating one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

### Keeping Packages Updated

Lastly, please ensure you are using the latest versions of YOLOv8 and the COCO API, as updates often include bug fixes and improvements that might resolve these discrepancies.

I hope this helps! If you have any further questions or need additional assistance, feel free to ask. 😊

**Comment by ZYJIQVV** [comment]
@glenn-jocher 
Thanks for your detailed reply and solution! But there still exists one question. I have replaced the interpolation function and integration function with a mean function as follows:

But the result of YOLOv8 is still higher than that of COCO API. Am I writing a wrong code or is there any other problem I didn't notice. Do I need to modify more codes
```python
def compute_ap(recall, precision):
    """
    Compute the average precision (AP) given the recall and precision curves.

    Args:
        recall (list): The recall curve.
        precision (list): The precision curve.

    Returns:
        (float): Average precision.
        (np.ndarray): Precision envelope curve.
        (np.ndarray): Modified recall curve with sentinel values added at the beginning and end.
    """

    # Append sentinel values to beginning and end
    mrec = np.concatenate(([0.0], recall, [1.0]))
    mpre = np.concatenate(([1.0], precision, [0.0]))

    # Compute the precision envelope
    mpre = np.flip(np.maximum.accumulate(np.flip(mpre)))

    # Integrate area under curve
    method = "coco"  # methods: 'continuous', 'interp'
    if method == "interp":
        x = np.linspace(0, 1, 101)  # 101-point interp (COCO)
        ap = np.trapz(np.interp(x, mrec, mpre), x)  # integrate
    elif method == 'coco':
        q = np.zeros((101,))
        q = q.tolist()
        recThrs = np.linspace(0, 1, 101)  # 101-point interp (COCO)
        inds = np.searchsorted(mrec, recThrs, side='left')  # indices to sample
        try:
            for ri, pi in enumerate(inds):
                q[ri] = mpre[pi]
        except:
            pass
        ap = np.mean(np.array(q))  # area under the precision-recall curve
        
    else:  # 'continuous'
        i = np.where(mrec[1:] != mrec[:-1])[0]  # points where x-axis (recall) changes
        ap = np.sum((mrec[i + 1] - mrec[i]) * mpre[i + 1])  # area under curve

    return ap, mpre, mrec
```
Here is my modified code and the _method == 'coco'_ is my modification. In this elif branch, I use np.searchsorted as the interpolation function and at the end the ap is calculated using a mean function. This is the only modification.

Could you please check my code and tell my if I can make more modifications to align YOLOv8 mAP calculation with COCO API.

Thanks again!

**Comment by glenn-jocher** [comment]
Hello @ZYJIQVV,

Thank you for your follow-up and for sharing your modified code. It's great to see your proactive approach in aligning the mAP calculation with the COCO API. Let's take a closer look at your code and see if there are any additional modifications or considerations that might help.

### Code Review and Suggestions

Your approach to modifying the interpolation and integration functions seems correct. However, there are a few points to consider:

1. **Precision Envelope Calculation**: Ensure that the precision envelope calculation aligns with the COCO API. The COCO API uses a specific method to calculate the precision envelope, which might slightly differ from the `np.maximum.accumulate` approach.

2. **Recall Thresholds**: Verify that the recall thresholds (`recThrs`) are correctly defined and used. The COCO API uses specific recall thresholds, and any deviation might lead to differences in the mAP calculation.

3. **Edge Cases**: Ensure that edge cases, such as empty precision or recall arrays, are handled correctly. The COCO API might have specific handling for such cases.

Here's a refined version of your code with some additional comments and checks:

```python
def compute_ap(recall, precision):
    """
    Compute the average precision (AP) given the recall and precision curves.

    Args:
        recall (list): The recall curve.
        precision (list): The precision curve.

    Returns:
        (float): Average precision.
        (np.ndarray): Precision envelope curve.
        (np.ndarray): Modified recall curve with sentinel values added at the beginning and end.
    """

    # Append sentinel values to beginning and end
    mrec = np.concatenate(([0.0], recall, [1.0]))
    mpre = np.concatenate(([1.0], precision, [0.0]))

    # Compute the precision envelope
    mpre = np.flip(np.maximum.accumulate(np.flip(mpre)))

    # Integrate area under curve
    method = "coco"  # methods: 'continuous', 'interp', 'coco'
    if method == "interp":
        x = np.linspace(0, 1, 101)  # 101-point interp (COCO)
        ap = np.trapz(np.interp(x, mrec, mpre), x)  # integrate
    elif method == 'coco':
        recThrs = np.linspace(0, 1, 101)  # 101-point interp (COCO)
        q = np.zeros((101,))
        inds = np.searchsorted(mrec, recThrs, side='left')  # indices to sample
        for ri, pi in enumerate(inds):
            if pi < len(mpre):
                q[ri] = mpre[pi]
        ap = np.mean(q)  # area under the precision-recall curve
    else:  # 'continuous'
        i = np.where(mrec[1:] != mrec[:-1])[0]  # points where x-axis (recall) changes
        ap = np.sum((mrec[i + 1] - mrec[i]) * mpre[i + 1])  # area under curve

    return ap, mpre, mrec
```

### Additional Considerations

1. **Validation with COCO API**: To ensure that your modifications align with the COCO API, you might want to validate your results against the COCO API directly. This can help identify any subtle differences in the implementation.

2. **Version Consistency**: Ensure that you are using the latest versions of YOLOv8 and the COCO API. Sometimes, discrepancies arise due to version mismatches or updates in the libraries.

3. **Reproducible Example**: If the issue persists, providing a minimum reproducible example can be very helpful for further investigation. You can refer to the [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example) guide for more details.

I hope this helps! If you have any further questions or need additional assistance, feel free to ask. 😊

**Comment by nwoyecid** [comment]
Even with all these modifications, the two metrics returns different values on the same model output. What is the motivation for the choice of metrics design in YOLOv8?

**Comment by glenn-jocher** [comment]
The design of metrics in YOLOv8 aims to provide a balance between accuracy and computational efficiency, ensuring robust performance across diverse scenarios. If you need further details, please refer to the documentation for a deeper understanding.

**Comment by kkbjj** [comment]
Hi all, after reading the source code of both Ultralytics validator (_process_batch) and the COCO API (pycocotools), I noticed a possible reason for the difference in mAP results: Ultralytics seems to ensure one-to-one GT matching by keeping the detection with the highest IoU when multiple detections match the same GT. COCO API seems to ensure one-to-one GT matching by keeping the detection with the highest confidence score, since detections are sorted by score first and matched sequentially. This difference in matching priority (IoU-first vs. confidence-first) might explain some of the discrepancies between the two results, especially when multiple detections overlap the same GT but have different IoUs and scores. I’m not entirely sure if this is the only cause, but I thought it might be worth sharing. @glenn-jocher @nwoyecid

**Comment by glenn-jocher** [comment]
Good observation — Ultralytics’ matching is IoU-priority greedy, while COCO’s is score-priority greedy, which can yield small mAP deltas when multiple detections hit the same GT. You can see this in `match_predictions` where pairs are sorted by IoU before unique selection; see the function in the [Validator reference](https://docs.ultralytics.com/reference/engine/validator/). If you need COCO parity, adapt matching to iterate detections in confidence order and greedily assign the highest-IoU unmatched GT per IoU threshold, or evaluate with COCOeval on the exported results. Since this thread is closed/stale, please open a new issue or PR if you’d like to propose adding a score-first matching option.
