### ISSUE TITLE
In cfg.yaml,imgsz comment error

### ISSUE THREAD

**Issue by YingGit-Zhao** [ultralytics/ultralytics#14061]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

In cfg.yaml, the imgsz comment says: ’list[w,h] for predict and export modes', but it is actually read as list[h,w] in the code running.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by yang-fei** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.
> 
> ### YOLOv8 Component
> _No response_
> 
> ### Bug
> In cfg.yaml, the imgsz comment says: ’list[w,h] for predict and export modes', but it is actually read as list[h,w] in the code running.
> 
> ### Environment
> _No response_
> 
> ### Minimal Reproducible Example
> _No response_
> 
> ### Additional
> _No response_
> 
> ### Are you willing to submit a PR?
> * [ ]  Yes I'd like to help by submitting a PR!

yes, I also just found this comment error. I think they just made a mistake

**Comment by glenn-jocher** [comment]
@yang-fei thank you for bringing this to our attention! It appears there is indeed a discrepancy in the `cfg.yaml` comment regarding the `imgsz` parameter. The comment should accurately reflect the order in which the dimensions are read by the code.

To help us address this issue more effectively, could you please provide a minimal reproducible example? This will allow us to better understand the context and ensure that the fix is comprehensive. You can find guidelines on how to create a minimal reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please make sure you are using the latest version of the repository, as updates may have already addressed this issue.

We appreciate your willingness to contribute! If you would like to submit a PR to correct the comment, that would be fantastic. Your contributions help improve the project for everyone. 😊

Thank you for your support and collaboration!
