### ISSUE TITLE
file size same for yolov8-s model and yolov8-n model

### ISSUE THREAD

**Issue by balajib197** [ultralytics/ultralytics#1410]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I performed transfer learning for custom dataset for segmentation model using yolov8-s and yolov8-n the files size remains the same for both the training.
Actual file size for yolov8-n is 6.9 MB, but I get 26.6 MB
And for yolov8-s is 22.3 MB, I get the same.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@balajib197 hi, the model size could be larger while training because the pt file includes extra info like optimizer:
```python
        ckpt = {
            'epoch': self.epoch,
            'best_fitness': self.best_fitness,
            'model': deepcopy(de_parallel(self.model)).half(),
            'ema': deepcopy(self.ema.ema).half(),
            'updates': self.ema.updates,
            'optimizer': self.optimizer.state_dict(),
            'train_args': vars(self.args),  # save as dict
            'date': datetime.now().isoformat(),
            'version': __version__}
``` 
The official models has stripped these extra keys after the training is done, so the model size is smaller.
[https://github.com/ultralytics/ultralytics/blob/9e58c32c15835e54e57f7b8c925367a64cb94951/ultralytics/yolo/engine/trainer.py#L516](https://github.com/ultralytics/ultralytics/blob/9e58c32c15835e54e57f7b8c925367a64cb94951/ultralytics/yolo/engine/trainer.py#L516)
If you run `strip_optimizer` with your trained yolov8n model, the model size should be just 6.9M.
```python
from ultralytics.yolo.utils.torch_utils import strip_optimizer
strip_optimizer("model.pt")
```
