### ISSUE TITLE
cls_loss and dfl_loss suddenly spike in the last 10 epochs

### ISSUE THREAD

**Issue by tien0717** [ultralytics/ultralytics#14110]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![results](https://github.com/ultralytics/ultralytics/assets/138637601/689cffc0-007e-4e76-b35b-43d5247309b6)

When I finish training YOLOv8, the cls_loss and dfl_loss suddenly spike in the last 10 epochs. Could you please tell me where there might be an error in the code?

**Comment by Y-T-G** [comment]
Last 10 epochs run without mosaic augmentation. It's expected.

**Comment by glenn-jocher** [comment]
@Y-T-G hello,

Thank you for reaching out. The spike in `cls_loss` and `dfl_loss` during the last 10 epochs is likely due to the model transitioning from training with mosaic augmentation to training without it. This is a standard practice to stabilize the model's learning and improve its performance on more realistic, non-augmented data.

To provide a more accurate diagnosis, could you please share a minimum reproducible example of your training script? This will help us better understand the issue and offer more targeted advice. You can find guidelines for creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure you are using the latest version of the Ultralytics YOLO package, as updates often include important bug fixes and improvements.

Feel free to share any further details or questions you might have. We're here to help!
