### ISSUE TITLE
Please teach me how to resolve it

### ISSUE THREAD

**Issue by asd13723654042** [ultralytics/ultralytics#14146]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

When I try to add "CBAM" to model and try training has this problem, and I write something in task.py、conv.py、_init_.py and yolov8n.yaml. Please tell me how to resolve it

(yolo8) PS D:\Anaconda\envs\yolo8>  yolo detect train data=ultralytics-main/ultralytics/cfg/datasets/coco128.yaml model=ultralytics-main/ultralytics/cfg/models/v8/yolov8n.yaml  pre
trained=ultralytics/yolov8n.pt epochs=100 batch=4 lr0=0.01 resume=True
Traceback (most recent call last):
  File "D:\Anaconda\envs\yolo8\lib\runpy.py", line 196, in _run_module_as_main                                
    return _run_code(code, main_globals, None,                                                                
  File "D:\Anaconda\envs\yolo8\lib\runpy.py", line 86, in _run_code                                           
    exec(code, run_globals)                                                                                   
  File "D:\Anaconda\envs\yolo8\Scripts\yolo.exe\__main__.py", line 7, in <module>                             
  File "D:\Anaconda\envs\yolo8\lib\site-packages\ultralytics\cfg\__init__.py", line 564, in entrypoint        
    model = YOLO(model, task=task)                                                                            
  File "D:\Anaconda\envs\yolo8\lib\site-packages\ultralytics\models\yolo\model.py", line 23, in __init__      
    super().__init__(model=model, task=task, verbose=verbose)                                                 
  File "D:\Anaconda\envs\yolo8\lib\site-packages\ultralytics\engine\model.py", line 147, in __init__          
    self._new(model, task=task, verbose=verbose)                                                              
  File "D:\Anaconda\envs\yolo8\lib\site-packages\ultralytics\engine\model.py", line 208, in _new              
    self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "D:\Anaconda\envs\yolo8\lib\site-packages\ultralytics\nn\tasks.py", line 309, in __init__              
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=ch, verbose=verbose)  # model, savelist
  File "D:\Anaconda\envs\yolo8\lib\site-packages\ultralytics\nn\tasks.py", line 898, in parse_model    
    m = getattr(torch.nn, m[3:]) if "nn." in m else globals()[m]  # get module                         
KeyError: 'CBAM'    

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@asd13723654042 hello,

Thank you for reaching out and for your willingness to contribute! It looks like you're encountering a `KeyError` related to the 'CBAM' module when trying to modify the YOLOv8 model. To better assist you, could you please provide a minimal reproducible example of the code you're using? This will help us diagnose the issue more effectively. You can find guidance on creating a minimal reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

In the meantime, here are a few steps you can take to troubleshoot the issue:

1. **Verify Module Integration**: Ensure that the 'CBAM' module is correctly defined and imported in your `conv.py`, `task.py`, and `__init__.py` files. The error suggests that the module might not be recognized in the global scope.

2. **Check for Typographical Errors**: Double-check the spelling and case of 'CBAM' in your code. Python is case-sensitive, so 'CBAM' and 'cbam' would be treated as different identifiers.

3. **Update Packages**: Make sure you are using the latest versions of all relevant packages. Sometimes, issues arise due to version incompatibilities. You can update your packages using:
    ```bash
    pip install --upgrade ultralytics torch
    ```

4. **Model Configuration**: Ensure that your `yolov8n.yaml` file correctly references the 'CBAM' module. The configuration should align with the changes you've made in the model architecture.

Here is a small example of how you might integrate a custom module into the YOLOv8 architecture:

```python
# In your conv.py or a similar file
import torch.nn as nn

class CBAM(nn.Module):
    def __init__(self, in_channels):
        super(CBAM, self).__init__()
        # Define your CBAM layers here

    def forward(self, x):
        # Define the forward pass
        return x

# Ensure this module is imported in __init__.py
```

```yaml
# In your yolov8n.yaml
backbone:
  # Your existing backbone configuration
  - [CBAM, 64]  # Example of adding CBAM to the model
```

If the issue persists after these steps, please share the specific changes you've made to the code and configuration files. This will help us provide more targeted assistance.

For additional troubleshooting tips, you can also refer to our [YOLO Common Issues Guide](https://docs.ultralytics.com/guides/yolo-common-issues/).
