### ISSUE TITLE
cpu ram memory increase from one epoch to another 

### ISSUE THREAD

**Issue by PaulV74** [ultralytics/ultralytics#14150]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I encountered a memory leak issue while training a YOLOv8 model using the ultralytics library. The problem occurs after the 20th epoch, where CPU memory usage increases significantly from one epoch to the next. GPU memory remains stable. Here are the details:

from ultralytics import YOLO
import torch

model = YOLO('yolov8n.yaml').load('yolov8n.pt')
model.train(data='anonymous.yaml', cfg='default_anonymous.yaml')

batch: -1 # (int) number of images per batch (-1 for AutoBatch)
cache: False # (bool) True/ram, disk or False. Use cache for data loading
workers: 8 # (int) number of worker threads for data loading (per RANK if DDP)

Training Log:

I start the training using 60% of my CPU during the first epoch. Everything goes well until the 20th epoch, where the CPU memory usage increases significantly. The GPU memory usage remains stable throughout the training.

Software Versions:
    python3.10.9
    torchvision: 0.20.0.dev20240627+cu118
    torch: 2.5.0.dev20240627+cu118
    ultralytics: 8.2.48

Training Output:
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs/detect/train
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100      14.3G      1.529      3.605      2.154          8        640: 100%|██████████| 11613/11613 [1:08:24<00:00,  2.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 646/646 [02:49<00:00,  3.80it/s]
                   all     149645       9724      0.835      0.717      0.792      0.487

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/100      14.3G      1.631      1.688      2.421          4        640: 100%|██████████| 11613/11613 [1:08:10<00:00,  2.84it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 646/646 [02:45<00:00,  3.91it/s]
                   all     149645       9724      0.819      0.635      0.739      0.458

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/100      14.3G        1.7      1.786       2.59          9        640: 100%|██████████| 11613/11613 [1:08:13<00:00,  2.84it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 646/646 [02:40<00:00,  4.02it/s]
                   all     149645       9724      0.745     0.0379       0.39      0.239

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/100      15.6G      1.714      1.803      2.675          7        640: 100%|██████████| 11613/11613 [1:08:04<00:00,  2.84it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 646/646 [02:40<00:00,  4.02it/s]
                   all     149645       9724      0.593      0.185      0.388      0.224

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/100        15G      1.687      1.735      2.653          7        640: 100%|██████████| 11613/11613 [1:07:58<00:00,  2.85it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 646/646 [02:44<00:00,  3.94it/s]
                   all     149645       9724      0.752      0.435      0.579      0.331

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/100      14.9G       1.68      1.709      2.649          5        640: 100%|██████████| 11613/11613 [1:08:01<00:00,  2.84it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 646/646 [02:47<00:00,  3.87it/s]
                   all     149645       9724      0.798      0.624      0.718      0.424

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/100      14.3G      1.678      1.699      2.652          3        640: 100%|██████████| 11613/11613 [1:08:10<00:00,  2.84it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 646/646 [02:47<00:00,  3.85it/s]
                   all     149645       9724       0.81      0.664       0.75      0.449

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/100      14.3G      1.673      1.693      2.639          3        640: 100%|██████████| 11613/11613 [1:08:01<00:00,  2.85it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 646/646 [02:48<00:00,  3.84it/s]
                   all     149645       9724       0.81      0.684      0.765       0.46

Because it works from one epoch to another, it is not for me a batchsize issue.

### Environment

NVIDIA RTX A5000 
Docker ultralytics

### Additional

When the training leaks memory after N epochs, if I stop and resume the training using the --resume option, it continues from where the leak was it left off, it not come back to begin the leak from the beginning.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hi there,

Thank you for reporting this issue and providing detailed information about your setup and training process. It seems like you're encountering a memory leak during training, which can be quite frustrating. Let's work through this together to identify and resolve the problem.

### Steps to Troubleshoot:

1. **Reproducible Example**: To better understand and reproduce the issue, could you please provide a minimal reproducible example? This will help us diagnose the problem more effectively. You can refer to our guide on creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example).

2. **Latest Versions**: Ensure that you are using the latest versions of all relevant packages. Sometimes, issues are resolved in newer releases. You can update your packages using:
    ```bash
    pip install --upgrade ultralytics torch torchvision
    ```

3. **Memory Profiling**: To pinpoint where the memory leak might be occurring, you can use memory profiling tools like `memory_profiler` or `tracemalloc` in Python. These tools can help identify which part of the code is causing the memory increase.

4. **DataLoader Workers**: Sometimes, issues with memory can be related to the number of DataLoader workers. You might want to experiment with reducing the number of workers to see if it affects the memory usage:
    ```python
    model.train(data='anonymous.yaml', cfg='default_anonymous.yaml', workers=4)
    ```

5. **Caching**: Since you have caching disabled, this should not be the issue, but it's worth double-checking if enabling or disabling caching affects the memory usage:
    ```yaml
    cache: False  # Ensure this is set correctly in your config
    ```

6. **Monitoring Tools**: Utilize tools like `nvidia-smi` to monitor GPU memory usage and `htop` or `top` for CPU memory usage. This can provide real-time insights into how resources are being utilized during training.

### Example Code for Memory Profiling:
Here's a small snippet to get you started with memory profiling using `memory_profiler`:
```python
from memory_profiler import profile
 @PaulV74
def train_model():
    from ultralytics import YOLO
    model = YOLO('yolov8n.yaml').load('yolov8n.pt')
    model.train(data='anonymous.yaml', cfg='default_anonymous.yaml')

if __name__ == "__main__":
    train_model()
```
Run this script to see a detailed memory usage report.

### Next Steps:
- Please provide a minimal reproducible example if possible.
- Verify the issue persists with the latest versions of the packages.
- Experiment with the number of DataLoader workers and caching settings.
- Use memory profiling tools to identify the source of the leak.

Feel free to reach out if you have any further questions or need additional assistance. We're here to help! 😊

**Comment by PaulV74** [comment]
Hi,

I update everything with your last docker images. I investigate a little bit more, it seems that it is relative to the number of worker. The solutions seems to stop the training every 20 epoch (relative to your ram, number of worker and dataset size). If it continue to work with this kind of patch I will keep this solutions and closed the issue in one week.

Sorry for the disturb,

Best

**Comment by glenn-jocher** [comment]
@PaulV74 hi there,

Thank you for the update and for investigating further! It’s great to hear that you’ve identified a potential link between the memory issue and the number of workers. Your approach of stopping the training every 20 epochs to manage memory sounds like a practical interim solution.

To further assist you, here are a few additional suggestions:

1. **Worker Adjustment**: As you mentioned, adjusting the number of workers can have a significant impact. You might want to experiment with different values to find the optimal balance for your setup. For example:
    ```python
    model.train(data='anonymous.yaml', cfg='default_anonymous.yaml', workers=4)
    ```

2. **Memory Management**: If you continue to experience issues, consider using memory profiling tools to pinpoint the exact cause. Tools like `memory_profiler` or `tracemalloc` can be very helpful.

3. **Periodic Checkpoints**: Implementing periodic checkpoints can help you resume training seamlessly if you need to restart due to memory constraints. This can be done using the `save_period` argument:
    ```python
    model.train(data='anonymous.yaml', cfg='default_anonymous.yaml', save_period=20)
    ```

Please keep us posted on your findings. If the issue persists or if you discover any new insights, feel free to share them here. Your feedback is invaluable in helping us improve the library for everyone.

No disturbance at all—thank you for your diligence and for working with us to resolve this! 😊

**Comment by PaulV74** [comment]
if you want to investigate more from your point of view, I think (maybe) when I read you're code that it is relative to this :
https://github.com/pytorch/pytorch/issues/13246

**Comment by glenn-jocher** [comment]
Hi @PaulV74,

Thank you for your continued investigation and for sharing the PyTorch issue link. It’s insightful and could indeed be related to the memory behavior you're observing.

To further assist, here are a few additional steps you might consider:

1. **PyTorch DataLoader**: The issue you referenced suggests potential memory leaks with the DataLoader. You might want to try setting `persistent_workers=False` in your DataLoader configuration to see if it mitigates the issue:
    ```python
    model.train(data='anonymous.yaml', cfg='default_anonymous.yaml', workers=4, persistent_workers=False)
    ```

2. **Manual Garbage Collection**: Explicitly invoking garbage collection can sometimes help manage memory usage:
    ```python
    import gc
    gc.collect()
    ```

3. **Memory Profiling**: As mentioned earlier, using tools like `memory_profiler` or `tracemalloc` can provide deeper insights into where memory is being consumed.

4. **Community Insights**: Engaging with the PyTorch community on the issue you linked might also yield additional solutions or workarounds.

Please keep us updated on your progress. If these suggestions help resolve the issue or if you find any new insights, sharing them here would be greatly appreciated. Your contributions are invaluable to the community!

Best regards and happy training! 😊
