### ISSUE TITLE
Large Output Video Size with Yolov8 Predict Mode

### ISSUE THREAD

**Issue by nkinnaird** [ultralytics/ultralytics#14163]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a Yolov8 model that I'm predicting on a video using the CLI with a command like:

```
yolo task=detect mode=predict model=projects/DefaultTrainParams/FirstRuns_Small_bs64_ep100/weights/best.pt source=~/Software/DockerVolumeMount/mp4s/20231019-164703-593_2310191643_SK5SS6UL_S.mp4 imgsz=640 project=projects/DefaultTrainParams name=FirstRuns_Small_bs64_ep100 exist_ok=True
```

When I run this it outputs a `.avi` file which is much larger than the original `mp4` video, up from 152 MB to 1.2 GB. This is new behavior to me coming from Yolov5, where the output video was in `mp4` format and the size was more comparable to the input video (still larger).  My questions are:

1. Why is the video so much larger?
2. Is there a way using the CLI that I can return to an `mp4` output with a smaller size?

Thanks.

**Comment by glenn-jocher** [comment]
@nkinnaird hello,

Thank you for reaching out and for providing detailed information about your issue. I understand that the large output video size in `.avi` format is causing some concerns. Let me address your questions:

1. **Why is the video so much larger?**
   The `.avi` format generally results in larger file sizes compared to `.mp4` because `.avi` often uses less compression. This can lead to significantly larger files, especially when dealing with high-resolution videos.

2. **Is there a way using the CLI that I can return to an `mp4` output with a smaller size?**
   Yes, you can specify the output format to be `.mp4` to achieve a more compressed and smaller file size. Unfortunately, the current CLI does not directly support specifying the output format. However, you can convert the `.avi` file to `.mp4` using a tool like `ffmpeg` after the prediction. Here’s an example of how you can do this:

   ```bash
   ffmpeg -i input.avi -vcodec libx264 -crf 28 output.mp4
   ```

   This command will convert `input.avi` to `output.mp4` using the H.264 codec with a constant rate factor (CRF) of 28, which balances quality and file size. You can adjust the CRF value to control the output quality and size (lower values mean higher quality and larger file size).

Additionally, if you prefer to handle this within your Python script, you can use the following approach:

```python
import cv2
from ultralytics import YOLO

# Load the model
model = YOLO("path/to/your/model.pt")

# Run inference on the video
results = model.predict(source="path/to/your/video.mp4", save=True)

# Convert the output .avi to .mp4
input_path = "path/to/output.avi"
output_path = "path/to/output.mp4"
cap = cv2.VideoCapture(input_path)
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter(output_path, fourcc, cap.get(cv2.CAP_PROP_FPS), (int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)), int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))))

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    out.write(frame)

cap.release()
out.release()
```

This script will convert the `.avi` file generated by YOLOv8 to an `.mp4` file.

I hope this helps! If you continue to experience issues, please ensure you are using the latest version of the Ultralytics packages. For more detailed guidance, you can refer to our [documentation](https://docs.ultralytics.com/modes/predict/).
