### ISSUE TITLE
How to get an output as a timestamp?

### ISSUE THREAD

**Issue by BKHChathuranga** [ultralytics/ultralytics#14161]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have trained YOLOv8 model using a custom dataset. There are 5 classes to identify. My aim is to input a video and after identifying  objects, a list of identified objects and time duration of that objects appearance should be output. Is there a possibility to do that?

**Comment by glenn-jocher** [comment]
@BKHChathuranga hello,

Thank you for reaching out! Yes, it is indeed possible to achieve your goal of identifying objects in a video and outputting a list of identified objects along with their timestamps. You can leverage the YOLOv8 model's capabilities to process video frames and track objects over time.

Here's a concise example to get you started:

1. **Load the YOLOv8 model**:
   ```python
   from ultralytics import YOLO

   # Load your trained YOLOv8 model
   model = YOLO("path/to/your/custom_model.pt")
   ```

2. **Process the video and extract timestamps**:
   ```python
   import cv2

   # Open the video file
   video_path = "path/to/your/video.mp4"
   cap = cv2.VideoCapture(video_path)

   # Dictionary to store object appearances with timestamps
   object_timestamps = {}

   # Loop through the video frames
   while cap.isOpened():
       ret, frame = cap.read()
       if not ret:
           break

       # Get the current timestamp
       timestamp = cap.get(cv2.CAP_PROP_POS_MSEC) / 1000  # Convert milliseconds to seconds

       # Run inference on the frame
       results = model(frame)

       # Extract detected objects and their classes
       for result in results:
           for box in result.boxes:
               class_id = int(box.cls)
               class_name = model.names[class_id]
               if class_name not in object_timestamps:
                   object_timestamps[class_name] = []
               object_timestamps[class_name].append(timestamp)

   # Release the video capture object
   cap.release()

   # Print the object timestamps
   for obj, times in object_timestamps.items():
       print(f"Object: {obj}, Timestamps: {times}")
   ```

This script will process each frame of the video, run inference to detect objects, and store the timestamps of their appearances. You can further customize the script to suit your specific needs, such as filtering by confidence scores or handling overlapping detections.

If you encounter any issues or need further assistance, please ensure you are using the latest version of the Ultralytics YOLO package. Additionally, providing a minimum reproducible example can help us better understand and address any problems you might face. You can find more information on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions. Happy coding! 😊

**Comment by BKHChathuranga** [comment]
Thank you very much @glenn-jocher for your previous response. it was incredibly helpful. I have a few additional concerns that I hope you can assist me with:

I implemented the solution you suggested, but I noticed that processing a 4 minute video clip took more than 15 minutes. I watched some of the videos on the Ultralytics YouTube channel, specifically the episode titled "How to Extract the Outputs from Ultralytics YOLOv8 Model for Custom Projects," and in this guide, the processing seemed significantly faster.

- Could you please help me understand why my processing time is so much longer? Is it possible that processing frame by frame is causing this delay?

- Additionally, are there any other recommendations you could provide, aside from using a different YOLO model or parameter tuning, to help improve the processing speed?

Thank you again for your assistance.

**Comment by glenn-jocher** [comment]
Hello @BKHChathuranga,

Thank you for your kind words and for providing additional details about your issue. I'm glad to hear that the previous response was helpful. Let's address your concerns regarding the processing time of your video.

### Understanding the Processing Time

Processing time can be influenced by several factors, including:
1. **Hardware Specifications**: Ensure you are using a GPU for inference, as CPU processing can be significantly slower.
2. **Frame Rate and Resolution**: Higher frame rates and resolutions require more computational power.
3. **Model Complexity**: More complex models (e.g., YOLOv8x) will take longer to process each frame compared to smaller models (e.g., YOLOv8n).

### Recommendations to Improve Processing Speed

1. **Batch Processing**:
   Instead of processing each frame individually, you can process frames in batches. This can significantly reduce the overhead and improve processing speed.

   ```python
   import cv2
   from ultralytics import YOLO

   # Load your trained YOLOv8 model
   model = YOLO("path/to/your/custom_model.pt")

   # Open the video file
   video_path = "path/to/your/video.mp4"
   cap = cv2.VideoCapture(video_path)

   # List to store frames for batch processing
   frames = []
   batch_size = 16  # Adjust batch size based on your GPU memory

   while cap.isOpened():
       ret, frame = cap.read()
       if not ret:
           break

       frames.append(frame)
       if len(frames) == batch_size:
           results = model(frames)  # Process batch of frames
           frames = []  # Clear the list for the next batch

   # Process remaining frames
   if frames:
       results = model(frames)

   cap.release()
   ```

2. **Optimize Model**:
   Export your model to a more optimized format like TensorRT or ONNX. These formats can leverage hardware acceleration more effectively.

   ```python
   # Export to TensorRT
   model.export(format="engine")
   ```

3. **Reduce Image Size**:
   Reducing the input image size can also help speed up processing. Ensure that the reduced size still meets your accuracy requirements.

   ```python
   results = model(frame, imgsz=320)  # Example of reducing image size
   ```

4. **Use Mixed Precision**:
   If your hardware supports it, using mixed precision (FP16) can speed up inference.

   ```python
   results = model(frame, half=True)
   ```

### Additional Resources

For more detailed guidance, you can refer to the [Ultralytics documentation on model export](https://docs.ultralytics.com/modes/export) and [YOLOv8 optimization techniques](https://docs.ultralytics.com/help/FAQ/).

If the issue persists, please ensure you are using the latest version of the Ultralytics package. If you encounter any further issues, providing a minimum reproducible example can help us diagnose the problem more effectively. You can find more information on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions. Happy coding! 😊

**Comment by BKHChathuranga** [comment]
Hello @glenn-jocher,

Thank you so much for your assistance and guidance. I truly appreciate your help and will definitely try out the methods you have suggested.

**Comment by glenn-jocher** [comment]
Hello @BKHChathuranga,

You're very welcome! I'm glad to hear that you found the suggestions helpful. 😊

If you encounter any further issues or have additional questions as you implement the methods, please don't hesitate to share more details or provide a reproducible example. This will help us diagnose and address any problems more effectively. You can find guidance on creating a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure you are using the latest version of the Ultralytics package to benefit from the latest features and fixes.

Happy coding, and best of luck with your project! 🚀
