### ISSUE TITLE
yolov8 with multi cameras (using only CPU)

### ISSUE THREAD

**Issue by vtn98** [ultralytics/ultralytics#14175]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a device (8 core cpu). I want to process 4 cameras on this device using yolov8 in real-time. Is it possible?

**Comment by Y-T-G** [comment]
no

**Comment by glenn-jocher** [comment]
@Y-T-G hello,

Yes, it is possible to process multiple camera streams using YOLOv8 on a CPU, though achieving real-time performance will depend on several factors including the resolution of the video streams and the specific model variant you are using (e.g., YOLOv8n for smaller, faster models).

Here’s a basic approach to handle multiple camera streams using Python's threading to ensure each camera stream is processed concurrently:

```python
import threading
import cv2
from ultralytics import YOLO

def process_camera(camera_id, model):
    cap = cv2.VideoCapture(camera_id)
    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break
        results = model(frame)
        annotated_frame = results[0].plot()
        cv2.imshow(f'Camera {camera_id}', annotated_frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

# Load the YOLOv8 model
model = YOLO("yolov8n.pt")

# List of camera IDs
camera_ids = [0, 1, 2, 3]

# Create and start a thread for each camera
threads = []
for camera_id in camera_ids:
    thread = threading.Thread(target=process_camera, args=(camera_id, model))
    thread.start()
    threads.append(thread)

# Wait for all threads to finish
for thread in threads:
    thread.join()
```

This script initializes a separate thread for each camera, processes the video stream, and displays the annotated frames. Adjust the `camera_ids` list to match your specific camera setup.

Keep in mind that running multiple streams on a CPU might not achieve high frame rates. You can optimize performance by:
1. Using a smaller model variant (e.g., YOLOv8n).
2. Reducing the resolution of the input video streams.
3. Adjusting the inference settings, such as confidence thresholds.

If you encounter any issues or need further assistance, please provide a reproducible example and ensure you are using the latest version of the Ultralytics YOLO package. You can find more details on creating a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Best of luck with your project! 🚀

**Comment by vtn98** [comment]
I tried this approach, but it's not working. It takes around 200-300ms to process an image for each camera. Do you have other approaches?

**Comment by glenn-jocher** [comment]
Hi @vtn98-G,

Thank you for your feedback. Processing multiple camera streams on a CPU can indeed be challenging due to the computational load. Here are a few strategies to optimize performance:

1. **Model Optimization**:
   - **Use a Smaller Model**: Consider using a smaller model variant like YOLOv8n, which is designed for faster inference.
   - **Quantization**: Export the model to a more efficient format such as ONNX with FP16 or INT8 quantization. This can significantly reduce inference time. Example:
     ```python
     model.export(format='onnx', half=True)
     ```

2. **Frame Skipping**:
   - **Reduce Frame Rate**: Skip frames to reduce the processing load. For example, process every nth frame:
     ```python
     frame_count = 0
     while cap.isOpened():
         ret, frame = cap.read()
         if not ret:
             break
         if frame_count % 5 == 0:  # Process every 5th frame
             results = model(frame)
             annotated_frame = results[0].plot()
             cv2.imshow(f'Camera {camera_id}', annotated_frame)
         frame_count += 1
         if cv2.waitKey(1) & 0xFF == ord('q'):
             break
     ```

3. **Parallel Processing**:
   - **Multiprocessing**: Utilize Python’s multiprocessing module to run each camera stream in a separate process, which can better utilize multiple CPU cores.
     ```python
     import multiprocessing as mp

     def process_camera(camera_id, model_path):
         model = YOLO(model_path)
         cap = cv2.VideoCapture(camera_id)
         while cap.isOpened():
             ret, frame = cap.read()
             if not ret:
                 break
             results = model(frame)
             annotated_frame = results[0].plot()
             cv2.imshow(f'Camera {camera_id}', annotated_frame)
             if cv2.waitKey(1) & 0xFF == ord('q'):
                 break
         cap.release()
         cv2.destroyAllWindows()

     if __name__ == '__main__':
         model_path = "yolov8n.pt"
         camera_ids = [0, 1, 2, 3]
         processes = [mp.Process(target=process_camera, args=(camera_id, model_path)) for camera_id in camera_ids]
         for p in processes:
             p.start()
         for p in processes:
             p.join()
     ```

4. **Resolution Adjustment**:
   - **Lower Resolution**: Reduce the resolution of the input frames to decrease processing time.
     ```python
     ret, frame = cap.read()
     frame = cv2.resize(frame, (320, 240))  # Resize to 320x240
     ```

Please ensure you are using the latest version of the Ultralytics YOLO package to benefit from the latest optimizations and features. If the issue persists, providing a minimum reproducible example can help us diagnose the problem more effectively. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

I hope these suggestions help! If you have any further questions, feel free to ask. 😊
