### ISSUE TITLE
YOLOv8 export TensorRt INT8 format ‘dynamic axes will be enabled by default when exporting with int8=True even when not explicitly set’

### ISSUE THREAD

**Issue by Nash973** [ultralytics/ultralytics#14188]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I try to export Tensorrt INT8 quantized yolov8 model，I noticed that the output dimensions of the model are a little different.
For example, here is the output from my export of the INT8 quantization model：
TensorRT: input "images" with shape(-1, 3, -1, -1) DataType.FLOAT
TensorRT: output "output0" with shape(-1, 6, -1) DataType.FLOAT
Checking the **exporter.py** code, it looks like the INT8 quantization export is related to the dynamics of ONNX.

I also noted the description in the documentation.
![DOC](https://github.com/ultralytics/ultralytics/assets/71496247/af6f0458-0544-4000-83ee-a26b17284711)

So, my question is, is there any way to export the Tensorrt INT8 quantization model in such a way that this dynamic dimension can be turned off?
I would like to get a log like this：
TensorRT: input "images" with shape(-1, 3, 640, 640) DataType.FLOAT
TensorRT: output "output0" with shape(-1, 6, 8400) DataType.FLOAT

**Comment by glenn-jocher** [comment]
Hello @Nash973,

Thank you for reaching out and for providing detailed information about your issue. The dynamic axes are indeed enabled by default when exporting with `int8=True` to ensure flexibility in handling varying input sizes. This behavior is designed to optimize the model's performance across different scenarios.

If you would like to disable the dynamic dimensions and have fixed input and output shapes, you can modify the export parameters accordingly. Here is an example of how you can achieve this:

```python
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO("yolov8n.pt")

# Export the model to TensorRT INT8 format with fixed dimensions
model.export(
    format="engine",
    imgsz=(640, 640),  # Fixed image size
    batch=1,  # Fixed batch size
    int8=True,
    dynamic=False  # Disable dynamic axes
)
```

In the command line interface (CLI), you can use the following command:

```bash
yolo export model=yolov8n.pt format=engine imgsz=640,640 batch=1 int8=True dynamic=False
```

This should give you the desired fixed dimensions in the exported TensorRT model.

If you encounter any issues or if the problem persists, please ensure you are using the latest version of the Ultralytics package. You can update it using:

```bash
pip install --upgrade ultralytics
```

For further details on exporting models to TensorRT, you can refer to our [TensorRT Export Guide](https://docs.ultralytics.com/integrations/tensorrt/).

Feel free to reach out if you have any more questions or need further assistance. 😊

**Comment by Burhan-Q** [comment]
@Nash973 I opted to include dynamic axes for the TensorRT INT8 export as the default, because the interim ONNX export must be done with dynamic axes. The other reason is that for the calibration step, you _must_ specify a calibration profile, and instead of adding extra logic for this, it made more sense to export with dynamic axes as the "cost" is minimal to the performance and exported model size. Plus most users will likely want to have the flexibility to change their input image sizes as needed.

I believe for many users, defaulting to use dynamic axes is preferable, however if you'd like to export with static axes, you can make changes to the source to accomplish this. First you'd bypass this conditional (comment lines or delete)

https://github.com/ultralytics/ultralytics/blob/e285d3d1b285ba80fa77d2a55a8875d477c8a826/ultralytics/engine/exporter.py#L207-L208

Then you will have to define a `profile` to use for the `config.set_calibration_profile()` here

https://github.com/ultralytics/ultralytics/blob/e285d3d1b285ba80fa77d2a55a8875d477c8a826/ultralytics/engine/exporter.py#L739-L742

Feel free to test it out, but I think you'll find that there's negligible difference in the exported models.

**Comment by Nash973** [comment]
@Burhan-Q thanks a lot

**Comment by Egorundel** [comment]
@glenn-jocher @Burhan-Q 

Hello!

I have an ONNX model with dynamic batch_size and fixed dimensions (512, 512). My model also has an NMS module at the output. I want to create a calibration_data.cache file so that I can use it later with trtexec when I create TensorRT Engine. 

Can you tell me how to create calibration_data.cache? 

Your code seems to be able to do this, but I do not know if calibration_data.cache batch_size, dimensions and NMS module affect the creation? Or is it unrelated at all?

https://github.com/ultralytics/ultralytics/blob/2ebd01faa8a709a97e08e54a6b6c8ba31fece1d0/ultralytics/engine/exporter.py#L785-L792

I'm just new to this business, I'd appreciate your help.

**Comment by Burhan-Q** [comment]
@Egorundel I recommend you refer to the [NVIDIA TensorRT Python API](https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/index.html) and [Developer Documentation](https://docs.nvidia.com/deeplearning/tensorrt/).
