### ISSUE TITLE
Pytorch install in jetson tx2

### ISSUE THREAD

**Issue by Kwhi-zx** [ultralytics/ultralytics#14187]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I want to use yolov8 in jetson tx2;but the version of it is too old
jetpack version =4.6.1-b110 ;there is no suitable torch bag in the net; how could i fix it?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Kwhi-zx** [comment]
i have the same problem as https://github.com/ultralytics/ultralytics/issues/13537 ;but the link here is no more avaliable

**Comment by glenn-jocher** [comment]
@Kwhi-zx hello,

Thank you for reaching out and for providing the context regarding your issue with installing PyTorch on the Jetson TX2 with JetPack 4.6.1. I understand the challenge you're facing due to the older JetPack version.

To address this, you can manually install a compatible version of PyTorch and Torchvision for your Jetson TX2. Here’s a step-by-step guide to help you through the process:

1. **Uninstall Existing PyTorch and Torchvision:**
   First, ensure that any existing installations of PyTorch and Torchvision are removed:
   ```bash
   pip uninstall torch torchvision
   ```

2. **Install Dependencies:**
   Install the necessary dependencies:
   ```bash
   sudo apt-get update
   sudo apt-get install -y libopenblas-base libopenmpi-dev libjpeg-dev zlib1g-dev
   ```

3. **Download and Install PyTorch:**
   Download the appropriate PyTorch wheel for JetPack 4.6.1 and Python 3.6:
   ```bash
   wget https://developer.download.nvidia.com/compute/redist/jp/v461/pytorch/torch-1.10.0+nv21.11-cp36-cp36m-linux_aarch64.whl
   pip install torch-1.10.0+nv21.11-cp36-cp36m-linux_aarch64.whl
   ```

4. **Install Torchvision:**
   Clone the Torchvision repository and install it from source:
   ```bash
   git clone --branch v0.11.1 https://github.com/pytorch/vision torchvision
   cd torchvision
   python3 setup.py install --user
   ```

5. **Verify Installation:**
   Ensure that PyTorch and Torchvision are correctly installed:
   ```python
   python3 -c "import torch; print(torch.__version__)"
   python3 -c "import torchvision; print(torchvision.__version__)"
   ```

By following these steps, you should be able to install a compatible version of PyTorch and Torchvision on your Jetson TX2 running JetPack 4.6.1.

If you encounter any issues during the installation, please provide a minimal reproducible example of the problem you're facing. This will help us diagnose and address the issue more effectively. You can find more information on how to create a minimal reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, ensure that you are using the latest versions of the Ultralytics packages to avoid any compatibility issues.

Feel free to reach out if you have any further questions or run into any issues. We're here to help! 😊

**Comment by Kwhi-zx** [comment]
thank you for your help.I have installed torch and torchvision that fits the jetson ; but the ultralytics 8.0.208 seems too old ;
I get the new error  "AttributeError: Can't get attribute 'RepNCSPELAN4' on <module 'ultralytics.nn.modules.block' from '/root/.clearml/venvs-builds/3.10/lib/python3.10/site-packages/ultralytics/nn/modules/block.py'>" when I am exporting a yolov9c.pt; what can i do to fix it?

**Comment by Kwhi-zx** [comment]
thank you for your help.I build a environment with python3.6 and  have installed torch and torchvision that fits the jetson ;And I download a ultralytics8.0.208 that fit python3.6; but the ultralytics 8.0.208 seems too old ;
I get the new error "AttributeError: Can't get attribute 'RepNCSPELAN4' on <module 'ultralytics.nn.modules.block' from '/root/.clearml/venvs-builds/3.10/lib/python3.10/site-packages/ultralytics/nn/modules/block.py'>" when I am exporting a yolov9c.pt; what can i do to fix it?

**Comment by glenn-jocher** [comment]
Hello @Kwhi-zx,

Thank you for the update and for providing more details about your setup. It sounds like you've made significant progress in setting up your environment on the Jetson TX2. The error you're encountering, `AttributeError: Can't get attribute 'RepNCSPELAN4'`, suggests that there might be a compatibility issue with the version of Ultralytics YOLO you're using.

To address this, here are a few steps you can take:

1. **Verify Latest Version Compatibility:**
   Ensure you are using the latest compatible versions of the Ultralytics packages. While you mentioned using Ultralytics 8.0.208, it might be beneficial to try a more recent version if possible. You can check the latest releases and their compatibility with Python 3.6 on the [Ultralytics GitHub releases page](https://github.com/ultralytics/ultralytics/releases).

2. **Reproducible Example:**
   Providing a minimal reproducible example can help us diagnose the issue more effectively. This includes the specific code you are using to export the model and any relevant configurations. You can find more information on how to create a minimal reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

3. **Check Model Compatibility:**
   The error might be related to the specific model architecture (`RepNCSPELAN4`) used in YOLOv9c. Ensure that the model you are trying to export is compatible with the version of Ultralytics YOLO you have installed. If possible, try exporting a different model to see if the issue persists.

4. **Example Code:**
   Here is an example of how you might attempt to export a model using the latest compatible version of Ultralytics YOLO:
   ```python
   from ultralytics import YOLO

   # Load a YOLOv8n PyTorch model
   model = YOLO("yolov8n.pt")

   # Export the model to TensorRT format
   model.export(format="engine")  # creates 'yolov8n.engine'
   ```

5. **Update Dependencies:**
   Ensure all dependencies are up-to-date. Sometimes, issues arise from outdated dependencies that are not fully compatible with the latest features:
   ```bash
   pip install --upgrade ultralytics
   ```

By following these steps, you should be able to address the compatibility issue and successfully export your model. If the problem persists, please provide the minimal reproducible example, and we will be happy to assist you further.

Feel free to reach out if you have any more questions or need further assistance. We're here to help! 😊
