### ISSUE TITLE
Yolo-world training from scratch

### ISSUE THREAD

**Issue by Chi813** [ultralytics/ultralytics#14191]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I started training Yolo-world from scratch, my computer memory kept going down until forcing the training to quit. My computer memory is 30 G.

**Comment by Chi813** [comment]
I used the default training code from Docs.
![Screenshot from 2024-07-03 10-15-42](https://github.com/ultralytics/ultralytics/assets/129787227/e11cf6e0-97d1-4fcd-abaa-eea69c56cb47)

**Comment by Chi813** [comment]
The training has already started, but it couldn't finish the first epoch.

**Comment by glenn-jocher** [comment]
@Chi813 hi there,

Thank you for reaching out and providing details about your issue. It sounds like you're encountering a memory leak during the training process. Here are a few steps you can take to troubleshoot and potentially resolve this issue:

1. **Reproducible Example**: To better assist you, could you please provide a minimum reproducible example of your code? This will help us diagnose the issue more effectively. You can refer to our guide on creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example).

2. **Update Packages**: Ensure that you are using the latest versions of all relevant packages, including the Ultralytics YOLO repository. Sometimes, issues are resolved in newer releases.

3. **Memory Management**: Given that your system has 30 GB of memory, it should typically be sufficient. However, you can try the following to manage memory usage better:
   - **Reduce Batch Size**: Lowering the batch size can significantly reduce memory consumption.
     ```python
     results = model.train(data='coco128.yaml', epochs=100, imgsz=640, batch=8)
     ```
   - **Use Mixed Precision Training**: This can help reduce memory usage.
     ```python
     results = model.train(data='coco128.yaml', epochs=100, imgsz=640, amp=True)
     ```
   - **Cache Dataset**: Ensure that you are not caching the dataset in memory if it's too large.
     ```python
     results = model.train(data='coco128.yaml', epochs=100, imgsz=640, cache=False)
     ```

4. **Monitor System Resources**: Use system monitoring tools to observe memory usage during training. This can help identify if there are specific stages where memory usage spikes.

5. **Check for Data Issues**: Sometimes, issues with the dataset (e.g., very large images) can cause excessive memory usage. Ensure your dataset is properly formatted and optimized for training.

If the issue persists after trying these steps, please share the reproducible example and any additional logs or error messages you encounter. This will help us provide more targeted assistance.

**Comment by Chi813** [comment]
@glenn-jocher hello,

I have created a minimum reproducible example. The code is the same as the example in **Reproduce official results from scratch(Experimental)** from **YOLO-World (Real-Time Open-Vocabulary Object Detection)**. Please have a look.

### Bug description:
When training Yolo-world from scratch, I encounter a memory leak.

### MRE:
```
from ultralytics import YOLOWorld
from ultralytics.models.yolo.world.train_world import WorldTrainerFromScratch

data = dict(
    train=dict(
        yolo_data=["Objects365.yaml"],
        grounding_data=[
            dict(
                img_path="../datasets/flickr30k/images",
                json_file="../datasets/flickr30k/final_flickr_separateGT_train.json",
            ),
            dict(
                img_path="../datasets/GQA/images",
                json_file="../datasets/GQA/final_mixed_train_no_coco.json",
            ),
        ],
    ),
    val=dict(yolo_data=["lvis.yaml"]),
)
model = YOLOWorld("yolov8s-worldv2.yaml")
model.train(data=data, batch=128, epochs=100, trainer=WorldTrainerFromScratch)
```
I used the same datasets from the Docs, but dataset Objects365v1 needs to be downloaded manually; the code won't download it for you. Please see the dataset information on:
`https://docs.ultralytics.com/models/yolo-world/#benefits-of-saving-with-custom-vocabulary`

### Error message:
The training process was killed.

### Dependencies:
```
torch==2.3.1
ultralytics==8.2.48
```

### Addition:
I have reduced batches and workers but still encountered the same problem. Maybe there are some problems with grounding_data because if I train only Objects365, the problem won't occur.

**Comment by glenn-jocher** [comment]
Hi @Chi813,

Thank you for providing a detailed description and a minimum reproducible example. This is very helpful! 😊

Given your setup and the memory leak issue, here are a few suggestions to help troubleshoot and potentially resolve the problem:

1. **Update Packages**: Ensure you are using the latest versions of all relevant packages. Sometimes, issues are resolved in newer releases. You can update your packages using:
   ```bash
   pip install --upgrade ultralytics torch
   ```

2. **Reduce Batch Size**: Lowering the batch size can significantly reduce memory consumption. Since you mentioned reducing batches and workers, try setting the batch size even lower:
   ```python
   model.train(data=data, batch=16, epochs=100, trainer=WorldTrainerFromScratch)
   ```

3. **Use Mixed Precision Training**: This can help reduce memory usage:
   ```python
   model.train(data=data, batch=16, epochs=100, trainer=WorldTrainerFromScratch, amp=True)
   ```

4. **Monitor Memory Usage**: Use system monitoring tools to observe memory usage during training. This can help identify if there are specific stages where memory usage spikes.

5. **Check Data Loading**: Since the issue seems to be related to `grounding_data`, ensure that the data loading process is optimized. Large images or improperly formatted data can cause excessive memory usage. Verify that the images and annotations are correctly formatted and not excessively large.

6. **Debugging**: Add logging to monitor memory usage at different stages of the training process. This can help pinpoint where the memory leak occurs:
   ```python
   import tracemalloc
   tracemalloc.start()

   # Your training code here

   snapshot = tracemalloc.take_snapshot()
   top_stats = snapshot.statistics('lineno')

   print("[ Top 10 ]")
   for stat in top_stats[:10]:
       print(stat)
   ```

7. **Alternative Datasets**: If possible, try using a smaller subset of the `grounding_data` to see if the issue persists. This can help determine if the problem is related to the size or specific content of the dataset.

If the issue persists after trying these steps, please share any additional logs or error messages you encounter. This will help us provide more targeted assistance.

Thank you for your patience and cooperation. Let's work together to resolve this issue! 🚀
