### ISSUE TITLE
Multiple Streams Processing Lag for YOLOv8 Inference

### ISSUE THREAD

**Issue by raunak-shr** [ultralytics/ultralytics#14223]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to count the no. of vehicles in a RTSP stream for a whole day. But the problem that I am facing is that the number of streams that I am processing is in 50s or 100s. So the processing time bound on the GPU causes spillover of the data from 1 time bucket (15 mins) to another time bucket. Since the process of inferencing from the streams is infinite, no data is logged in the database. 

Assuming that I am using multithreading to handle each stream inference, how can I keep track of time at each stream level so that the data can be logged into the database at the correct time bucket in synchronization with the system/real-time?

If the same database (using MySQL) is accessed by multiple thread-streams, will it cause any race condition even though each stream has totally separate records in the same table?

**Comment by raunak-shr** [comment]
Thanks @glenn-jocher  i have implemented the same. the issue im facing right now is i want the vehicle count for each 15 munite bucket and the count should be correct for that bucket when im running 1 stream in that scenario my model is processing one frame in 10 ms but when im trying to run multiple streams the time is significantly growing in that scenario if with 1 stream it taking 250 ms to process 1 second in the other hand whn i have 50 streams its taking 3000 ms then in both cases i cant use time.now()

**Comment by glenn-jocher** [comment]
Hi @raunak-shr,

Thank you for the detailed explanation of your issue. It sounds like you're encountering performance bottlenecks when scaling up the number of streams, which is affecting your ability to accurately log vehicle counts in 15-minute intervals.

### Addressing Performance Bottlenecks

1. **Resource Allocation**: Ensure that your system's resources (CPU, GPU, memory) are being utilized efficiently. You might need to distribute the load across multiple GPUs if available, or consider using more powerful hardware.

2. **Batch Processing**: Instead of processing each frame individually, consider batching frames from each stream. This can significantly reduce the overhead and improve processing times.

3. **Asynchronous Processing**: Utilize asynchronous processing to handle multiple streams concurrently without blocking. Python's `asyncio` library can be helpful here.

### Example: Asynchronous Processing with Batching

Here's an example of how you might implement asynchronous processing with batching:

```python
import asyncio
from threading import Thread
from ultralytics import YOLO

async def process_stream(stream_url, db_connection):
    local_model = YOLO("yolov8n.pt")
    while True:
        frames = await capture_frames_from_stream(stream_url, batch_size=10)  # Capture frames in batches
        results = local_model.predict(frames)
        timestamp = get_current_timestamp()
        log_results_to_db(db_connection, results, timestamp)

async def main(stream_urls, db_connection):
    tasks = [process_stream(url, db_connection) for url in stream_urls]
    await asyncio.gather(*tasks)

# Start the event loop
stream_urls = ["rtsp://stream1", "rtsp://stream2", ...]  # List of stream URLs
db_connection = create_db_connection()
asyncio.run(main(stream_urls, db_connection))
```

### Accurate Time Logging

To ensure accurate logging, you can use the timestamp of when the frame was captured rather than the processing time. This way, even if there is a delay in processing, the data will be logged correctly:

```python
def log_results_to_db(db_connection, results, timestamp):
    connection = connection_pool.get_connection()
    cursor = connection.cursor()
    try:
        for result in results:
            cursor.execute("INSERT INTO your_table (timestamp, result) VALUES (%s, %s)", (timestamp, result))
        connection.commit()
    finally:
        cursor.close()
        connection.close()
```

### Further Optimization

1. **Profile Your Code**: Use profiling tools to identify bottlenecks in your code. This can help you understand where the delays are occurring and optimize accordingly.
2. **Optimize Model Inference**: Consider using optimized versions of your model, such as TensorRT, for faster inference times.

For more detailed guidance, you can refer to our [Thread-Safe Inference Guide](https://docs.ultralytics.com/guides/yolo-thread-safe-inference).

I hope this helps! If you have any further questions or need more assistance, feel free to ask. 😊

**Comment by raunak-shr** [comment]
There's a cv2 function `cap.get(cv2.CAP_PROP_POS_MSEC`) which gives the position of the frame in the stream. If I use this as a reference to log my results in the database, shall it work fine?

**Comment by glenn-jocher** [comment]
Hi @raunak-shr,

Using `cap.get(cv2.CAP_PROP_POS_MSEC)` to get the position of the frame in the stream is a great idea! This function returns the timestamp of the current frame in milliseconds, which can be very useful for logging results accurately.

Here's how you can integrate it into your logging process:

```python
import cv2
from ultralytics import YOLO

def process_stream(stream_url, db_connection):
    local_model = YOLO("yolov8n.pt")
    cap = cv2.VideoCapture(stream_url)
    
    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break
        
        # Get the timestamp of the current frame
        frame_time = cap.get(cv2.CAP_PROP_POS_MSEC)
        
        # Perform inference
        results = local_model.predict(frame)
        
        # Log results with the frame timestamp
        log_results_to_db(db_connection, results, frame_time)
    
    cap.release()

# Example usage
stream_url = "rtsp://your_stream_url"
db_connection = create_db_connection()
process_stream(stream_url, db_connection)
```

By using the frame timestamp provided by `cv2.CAP_PROP_POS_MSEC`, you can ensure that your results are logged with accurate timing, even when processing multiple streams concurrently.

If you encounter any issues or have further questions, please let us know. Also, make sure you're using the latest versions of the packages to benefit from the latest fixes and improvements.

Happy coding! 😊
