### ISSUE TITLE
How to hand bounding boxes with corners outside the image for oriented bounding box (OBB) task

### ISSUE THREAD

**Issue by CVHub520** [ultralytics/ultralytics#14228]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi Ultralytics Team,

I'm currently working on annotating training data for rotated object detection using your YOLO implementation. I've encountered a situation where some of the objects of interest have oriented bounding boxes (OBBs) that extend beyond the edges of the images.

![image](https://github.com/ultralytics/ultralytics/assets/72010077/fd9696dd-85c9-4e42-b45d-8301d898aad1)

As the example shown above, my question is, how should we handle these cases where the objects are clearly visible but their bounding boxes have corners that are not on the image? Should I:

1. Crop the bounding boxes to fit within the image boundaries?
2. Ignore these bounding boxes in the training process?
3. Or is there another recommended approach for dealing with such cases?

I'm looking for guidance on the best practices for annotating and handling these OBBs in order to ensure optimal performance of the trained model. Any advice or insights you could provide would be greatly appreciated.

Thank you for your time and assistance! 😄

**Comment by glenn-jocher** [comment]
@CVHub520 hi there,

Thank you for reaching out and for providing a clear description of your issue along with an example image. Handling oriented bounding boxes (OBBs) that extend beyond the image boundaries is a common challenge in object detection tasks, especially with aerial or satellite imagery.

Here are some recommended approaches to handle such cases:

1. **Crop the Bounding Boxes**: Adjust the bounding boxes so that they fit within the image boundaries. This involves clipping the coordinates of the bounding box corners to the edges of the image. This method ensures that all annotations are within the image, which can help maintain the integrity of the training data.

2. **Ignore These Bounding Boxes**: If the portion of the object outside the image is significant and the remaining visible part is not representative, you might consider ignoring these bounding boxes. However, this approach could lead to a loss of valuable training data if overused.

3. **Use Partial Annotations**: Annotate only the visible part of the object. This approach can be useful if the majority of the object is within the image and the visible part is sufficient for detection.

Here's a Python snippet to help you clip bounding box coordinates to the image boundaries:

```python
def clip_bbox_to_image(bbox, img_width, img_height):
    """
    Clips the bounding box coordinates to the image boundaries.
    
    Args:
        bbox (list): List of bounding box coordinates [x1, y1, x2, y2, x3, y3, x4, y4].
        img_width (int): Width of the image.
        img_height (int): Height of the image.
    
    Returns:
        list: Clipped bounding box coordinates.
    """
    clipped_bbox = []
    for i in range(0, len(bbox), 2):
        x = max(0, min(img_width, bbox[i]))
        y = max(0, min(img_height, bbox[i+1]))
        clipped_bbox.extend([x, y])
    return clipped_bbox

# Example usage
bbox = [0.78, 0.74, 0.82, 0.75, 0.77, 0.75, 0.76, 0.74]
img_width, img_height = 640, 480
clipped_bbox = clip_bbox_to_image(bbox, img_width, img_height)
print(clipped_bbox)
```

For more detailed guidance on handling OBB datasets and annotations, you can refer to our [Oriented Bounding Box (OBB) Datasets Overview](https://docs.ultralytics.com/datasets/obb/).

Additionally, ensure you are using the latest version of the Ultralytics YOLO package to benefit from the latest features and bug fixes. If the issue persists, providing a minimum reproducible example can help us diagnose and address the problem more effectively. You can find more information on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

I hope this helps! Feel free to reach out if you have any more questions. 😊

**Comment by CVHub520** [comment]
Thank you for your thoughtful response! I will definitely take that into consideration.

**Comment by glenn-jocher** [comment]
@CVHub520 you're welcome! 😊 I'm glad the information was helpful. If you decide to implement the clipping of bounding boxes to fit within the image boundaries, and you encounter any issues or have further questions, feel free to reach out.

Additionally, if you run into any specific problems or bugs, providing a minimum reproducible example can greatly assist us in diagnosing and addressing the issue more effectively. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Lastly, please ensure you are using the latest version of the Ultralytics YOLO package to benefit from the latest features and fixes. This can often resolve unexpected issues.

Happy coding, and best of luck with your project! 🚀
