### ISSUE TITLE
Clarafication of training Yolov8 about *yaml and *pt when using the CLI interface

### ISSUE THREAD

**Issue by Jacfger** [ultralytics/ultralytics#14292]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to train a new yolov8 model using my custom dataset, and I saw the documentations mentioned something like this.

```
# Build a new model from YAML and start training from scratch
yolo detect train data=coco8.yaml model=yolov8n.yaml epochs=100 imgsz=640

# Start training from a pretrained *.pt model
yolo detect train data=coco8.yaml model=yolov8n.pt epochs=100 imgsz=640

# Build a new model from YAML, transfer pretrained weights to it and start training
yolo detect train data=coco8.yaml model=yolov8n.yaml pretrained=yolov8n.pt epochs=100 imgsz=640
```

So from this page, it seemed that `model=*.yaml` would load the model but not the weight, whereas `model=*.pt` loads both the weights.

But when I tried it myself, I realize when I was loading yaml (by mistake, command as shown below), the trianing logs still prints `freezing layer ...`
![image](https://github.com/ultralytics/ultralytics/assets/43430515/b4a0c080-a44b-4426-abdb-449f36a076ef)
`CUDA_VISIBLE_DEVICES=5 yolo detect train data=data/metadata.yaml model=yolov8x.yaml epochs=150 imgsz=1280 close_mosaic=15 batch=8`

So what is happening here? Like,
1. Did it actually load anything? (in yaml case)
2. Is the freeze intended?
3. Is it just the logging is bugged?

**Comment by glenn-jocher** [comment]
@Jacfger hello,

Thank you for your detailed question and for providing the context of your issue. Let's clarify the behavior of the `model` argument in the CLI interface when using YAML and PT files.

### Understanding `model` Argument

1. **YAML File (`model=*.yaml`)**:
   - When you specify a YAML file, it defines the architecture of the model but does not include any pretrained weights. This is useful for training a model from scratch.
   - Example: `yolo detect train data=data/metadata.yaml model=yolov8x.yaml epochs=150 imgsz=1280`

2. **PT File (`model=*.pt`)**:
   - When you specify a PT file, it includes both the model architecture and the pretrained weights. This is useful for fine-tuning a pretrained model.
   - Example: `yolo detect train data=data/metadata.yaml model=yolov8x.pt epochs=150 imgsz=1280`

3. **Combining YAML and PT (`model=*.yaml pretrained=*.pt`)**:
   - This approach allows you to define the model architecture with a YAML file and initialize it with pretrained weights from a PT file.
   - Example: `yolo detect train data=data/metadata.yaml model=yolov8x.yaml pretrained=yolov8x.pt epochs=150 imgsz=1280`

### Addressing Your Questions

1. **Did it actually load anything? (in YAML case)**
   - Yes, it loaded the model architecture defined in the YAML file. However, since no weights are specified, it starts training from scratch.

2. **Is the freeze intended?**
   - The freezing of layers typically occurs when using pretrained weights to fine-tune specific layers while keeping others fixed. If you are seeing freezing messages when using a YAML file, it might be due to default settings or a bug. Ensure that no pretrained weights are being inadvertently loaded.

3. **Is it just the logging bugged?**
   - It's possible that the logging might be reflecting default behaviors or settings. To verify, you can explicitly set `freeze=0` in your command to ensure no layers are frozen:
     ```bash
     yolo detect train data=data/metadata.yaml model=yolov8x.yaml epochs=150 imgsz=1280 freeze=0
     ```

### Additional Steps

- **Reproducible Example**: If the issue persists, providing a minimum reproducible example can help diagnose the problem more effectively. You can refer to our guide on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).
- **Latest Versions**: Ensure you are using the latest versions of the Ultralytics packages to benefit from recent fixes and improvements.

Feel free to reach out if you have any more questions or need further assistance. Happy training! 🚀

**Comment by Y-T-G** [comment]
It will always freeze that layer

**Comment by Jacfger** [comment]
Thanks !

**Comment by glenn-jocher** [comment]
You're welcome! 😊

To address your concern about the layer always being frozen, this behavior typically occurs due to the default settings in the model configuration. Here are a few steps you can take to ensure that no layers are unintentionally frozen:

1. **Explicitly Set `freeze=0`**: When you train your model, you can explicitly set the `freeze` parameter to `0` to ensure that no layers are frozen:
   ```bash
   yolo detect train data=data/metadata.yaml model=yolov8x.yaml epochs=150 imgsz=1280 freeze=0
   ```

2. **Check Configuration**: Ensure that your YAML configuration file does not have any settings that might cause layers to be frozen. You can review the configuration file to verify this.

3. **Update to Latest Version**: Make sure you are using the latest version of the Ultralytics packages. Sometimes, issues like these are resolved in newer releases.

4. **Reproducible Example**: If the issue persists, providing a minimum reproducible example can help us diagnose the problem more effectively. You can refer to our guide on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

If you follow these steps and still encounter issues, please let us know. We're here to help! 🚀

Feel free to reach out with any more questions or details. Happy training!
