### ISSUE TITLE
Non crashing error while using model.tune()

### ISSUE THREAD

**Issue by AlainPilon** [ultralytics/ultralytics#14300]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Hyperparameter Tuning

### Bug

When performing

```
model = YOLO('yolov8m-cls.pt')
model.tune(data=data_path, device=0, epochs=10, iterations=4, plots=False, save=False, val=False)

```

I am getting this error at the end of about half the iterations:

```
...
Results saved to runs/classify/train
💡 Learn more at https://docs.ultralytics.com/modes/train
Exception in thread Thread-5 (_pin_memory_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop
    do_one_step()
  File "/usr/lib/python3/dist-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/usr/lib/python3/dist-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.10/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.10/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 508, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 752, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.25.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Saved runs/classify/tune/tune_scatter_plots.png
Saved runs/classify/tune/tune_fitness.png
....
```

The process keeps going on so I dont know if I am supposed to do anything to fix it or not. 

### Environment

Nvidia A100 on the lambdastack with only `pip install ultralytics`

### Minimal Reproducible Example

```
model = YOLO('yolov8m-cls.pt')
model.tune(data=data_path, device=0, epochs=10, iterations=4, plots=False, save=False, val=False)
```

I dont think it is data related as I have used the same dataset for training multiple times before.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AlainPilon** [comment]
1. Ultralytics was freshly installed so it shouldnt be an issue. I will check `torch` once my tune process is completed. 
2. I will investigate this also 
3. The default is 8, I will check with 2 but wouldnt it decrease dramatically the performance?
4. All good there, as we are using a fresh VM for each training
5. It may be difficult but if the issue persists, I will give it a shot. 

I will report back once my tuning is completed. In a few hours/days...

**Comment by glenn-jocher** [comment]
Hi @AlainPilon,

Thank you for your detailed response! It's great to hear that you're taking steps to investigate the issue further. Here are a few additional pointers:

1. **Updating Packages**: Ensuring that both Ultralytics and PyTorch are up-to-date is a good first step. This can often resolve unexpected issues.

2. **Pin Memory**: Disabling `pin_memory` or adjusting the number of worker threads can indeed impact performance, but it's a useful troubleshooting step to identify if the issue is related to data loading. You can start with a lower number of workers and gradually increase it to find a balance between stability and performance.

3. **Reproducible Example**: If the issue persists, providing a minimal reproducible example would be incredibly helpful. This allows us to replicate the problem on our end and provide a more targeted solution. You can find guidelines for creating one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to report back with your findings. We're here to help! 😊

Best of luck with your tuning process!
