### ISSUE TITLE
YOLOv8 segmentation predict deson't provide all polygons detected while result plot gives shows all polygons

### ISSUE THREAD

**Issue by jpointchoi** [ultralytics/ultralytics#14311]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

![yolov8_labels_txt_inference_result](https://github.com/ultralytics/ultralytics/assets/140245500/5add0a91-c899-4084-b58b-f22f8adb2ed8)
As shown in the figure, right plot(drawn with results[0].plot) shows 3 poygons with center big bounding box.
But model predict result lables.txt just porvide a semenation data for a center large bounding box. As shown in the left box(draw segementation label.txt with polygon)

Am I miss something here?

Thanks
J. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@jpointchoi hi J.,

Thank you for bringing this to our attention! It looks like you're encountering an issue where the segmentation predictions are not fully represented in the `labels.txt` file, even though the plot shows all detected polygons.

To help us diagnose the problem more effectively, could you please provide a minimal reproducible example? This will allow us to replicate the issue on our end and identify the root cause. You can find guidance on creating a minimal reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

In the meantime, please ensure that you are using the latest version of the Ultralytics YOLOv8 package, as updates often include important bug fixes and improvements. You can update your package using the following command:
```bash
pip install --upgrade ultralytics
```

Additionally, if you could share the specific code snippet you are using for prediction and any relevant configuration details, that would be very helpful.

Looking forward to your response!
