### ISSUE TITLE
Deformable convolutions

### ISSUE THREAD

**Issue by dariogonle** [ultralytics/ultralytics#14392]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have created a module with the library from `torchvision.ops import DeformConv2d`. 

```
class CustomModel(nn.Module):
    default_act = nn.SiLU()  # default activation
    def __init__(self, in_channels, out_channels, kernel_size=3, stride=1, padding=1, act=True):
        super().__init__()
        self.offset_conv = nn.Conv2d(in_channels, 2 * kernel_size * kernel_size, kernel_size=kernel_size, stride=stride, padding=padding)
        self.deform_conv = DeformConv2d(in_channels, out_channels, kernel_size=kernel_size, stride=stride, padding=padding)
        self.bn = nn.BatchNorm2d(out_channels)
        self.act = self.default_act if act is True else act if isinstance(act, nn.Module) else nn.Identity()

def forward(self, x):
        offset = self.offset_conv(x)
        out = self.deform_conv(x, offset)
        return self.act(self.bn(out))
```

However, when I create an architecture with this module,

```
backbone:
  # [from, repeats, module, args]
  - [-1, 1, CustomModel, [64, 3, 2]] # 0-P1/2

# YOLOv8.0n head
head:
  - [[-1], 1, Detect, [nc]] # Detect(P3, P4, P5)
```

 it seems that it is not possible to perform the training. The model loads correctly, but when training starts, a segmentation fault occurs. I have printed the type() of the tensor x used in BaseModel (tasks.py) just before checking if it is a dict (between lines 99 and 100)

https://github.com/ultralytics/ultralytics/blob/abd391b63338b79cebee808b6679498dcc94956f/ultralytics/nn/tasks.py#L87-L102

 If I use a normal convolution it is of type dict. If I use my module it is of type tensor. Does anyone know why this could be?

**Comment by glenn-jocher** [comment]
@dariogonle thank you for sharing your custom module and the detailed description of the issue you're encountering. It looks like you've done a great job integrating `DeformConv2d` into your model. The segmentation fault during training is concerning, and it seems related to the tensor type mismatch you've observed.

Here are a few steps to help diagnose and potentially resolve the issue:

1. **Reproducible Example**: Could you please provide a minimal reproducible example? This will help us better understand the context and reproduce the issue on our end. You can refer to our guide on creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example).

2. **Latest Versions**: Ensure you are using the latest versions of PyTorch, torchvision, and Ultralytics YOLO. Sometimes, issues like these are resolved in newer releases.

3. **Tensor Type Check**: The type mismatch between `dict` and `tensor` is unusual. Ensure that your custom module's output is consistent with what the rest of the YOLO architecture expects. You might want to check if the `DeformConv2d` layer or any subsequent operations are altering the tensor in unexpected ways.

4. **Debugging**: Add additional print statements or use a debugger to trace the tensor transformations step-by-step. This can help pinpoint where the type change occurs.

5. **Example Code**:
   ```python
   import torch
   import torch.nn as nn
   from torchvision.ops import DeformConv2d

   class CustomModel(nn.Module):
       default_act = nn.SiLU()  # default activation
       def __init__(self, in_channels, out_channels, kernel_size=3, stride=1, padding=1, act=True):
           super().__init__()
           self.offset_conv = nn.Conv2d(in_channels, 2 * kernel_size * kernel_size, kernel_size=kernel_size, stride=stride, padding=padding)
           self.deform_conv = DeformConv2d(in_channels, out_channels, kernel_size=kernel_size, stride=stride, padding=padding)
           self.bn = nn.BatchNorm2d(out_channels)
           self.act = self.default_act if act is True else act if isinstance(act, nn.Module) else nn.Identity()

       def forward(self, x):
           offset = self.offset_conv(x)
           out = self.deform_conv(x, offset)
           return self.act(self.bn(out))

   # Example usage
   model = CustomModel(3, 64)
   x = torch.randn(1, 3, 224, 224)
   output = model(x)
   print(output.shape)
   ```

By following these steps, we can better understand and address the issue. Please let us know if the problem persists after these checks. Your collaboration helps improve the robustness of our models and tools. Thank you! 😊

**Comment by yudis2** [comment]
hello @glenn-jocher i have problem "return F.conv2d( 550 input, weight, bias, self.stride, self.padding, self.dilation, self.groups 551 ) RuntimeError: Given groups=1, weight of size [32, 3, 1, 1], expected input[1, 128, 64, 64] to have 3 channels, but got 128 channels instead".

i have tried to implement the deformable module.
[-1, 1, DCN, [32, 64, 3, 1, 1]] 

can you help me to solve this problem.. thankyou

**Comment by glenn-jocher** [comment]
@yudis2 it seems that your `DCN` module is expecting an input with 3 channels but is instead receiving 128 channels. This mismatch likely stems from the `DCN` configuration you provided in the model architecture (`[-1, 1, DCN, [32, 64, 3, 1, 1]]`).

To resolve this, ensure that the input channels to your `DCN` align with the output channels from the preceding layer. You can achieve this by modifying the `DCN` module to accept 128 input channels instead of 3. For example, if `DCN` is a custom module, update its first argument to match the input channels (`128` in this case).

If you're still facing issues, please verify the configuration of the preceding layer in your model and adjust the channels accordingly. Let me know if you need further clarification or assistance.

**Comment by yudis2** [comment]
dear @glenn-jocher thank you for the response, but i have facing same problem with detail what i have done.

on ultralytics.nn.modules.conv.py i add the modules :
`class DCN(nn.Module):
    default_act = nn.SiLU()  # default activation
    def __init__(self, in_channels, out_channels, kernel_size=3, stride=1, padding=1, act=True):
        super().__init__()
        self.offset_conv = nn.Conv2d(in_channels, 2 * kernel_size * kernel_size, kernel_size=kernel_size, stride=stride, padding=padding)
        self.deform_conv = DeformConv2d(in_channels, out_channels, kernel_size=kernel_size, stride=stride, padding=padding)
        self.bn = nn.BatchNorm2d(out_channels)
        self.act = self.default_act if act is True else act if isinstance(act, nn.Module) else nn.Identity()

    def forward(self, x):
        offset = self.offset_conv(x)
        out = self.deform_conv(x, offset)
        return self.act(self.bn(out))`

on top of tasks.py i add this line : 
`from ultralytics.nn.modules.conv import DCN
globals()['DCN'] = DCN`

on yolov8n.yaml add : 
`# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, DCN, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]] # 9

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, C2f, [512]] # 12

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 3, C2f, [256]] # 15 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]] # cat head P4
  - [-1, 3, C2f, [512]] # 18 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]] # cat head P5
  - [-1, 3, C2f, [1024]] # 21 (P5/32-large)

  - [[15, 18, 21], 1, Detect, [nc]] # Detect(P3, P4, P5)`

and the finally i facing the error 
`[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py](https://localhost:8080/#) in _conv_forward(self, input, weight, bias)
    547                 self.groups,
    548             )
--> 549         return F.conv2d(
    550             input, weight, bias, self.stride, self.padding, self.dilation, self.groups
    551         )

RuntimeError: Given groups=1, weight of size [8, 64, 2, 2], expected input[1, 3, 256, 256] to have 64 channels, but got 3 channels instead`

**Comment by glenn-jocher** [comment]
Thank you for sharing the detailed steps you've taken to integrate Deformable Convolutions (DCN) into the YOLOv8n model. The error indicates a mismatch between the input channels and the expected input channels for the `DCN` layer. Here's how you can resolve this:

1. The format you are using in the YOLOv8 YAML file (`[-1, 1, DCN, [128, 3, 2]]`) corresponds to:
   - `128` → Output channels of the `DCN` layer.
   - `3` → Kernel size.
   - `2` → Stride.

2. The issue arises because the output channels from the preceding layer do not match the input channels expected by `DCN`. Specifically:
   - The layer before `DCN` produces `32` channels.
   - Your `DCN` expects `128` channels as input, causing the mismatch.

3. To fix this, you need to ensure the preceding layer outputs `128` channels. For example, modify the YAML configuration to adjust the channels before feeding into `DCN`:
   ```yaml
   backbone:
     - [-1, 1, Conv, [128, 3, 2]]  # Adjust the preceding layer to produce 128 channels
     - [-1, 1, DCN, [128, 3, 1]]  # DCN now receives 128 channels
   ```

4. Alternatively, if you want the preceding layer to produce fewer channels (e.g., 32), you need to update the `DCN` initialization (`in_channels`) in your `CustomModel` to match the preceding layer's output.

Let me know if you need further clarification or additional assistance!

**Comment by yudis2** [comment]
hello @glenn-jocher thank you so much to helping me, but i still have probelm, but i have done to analyze the output or input channel with default setting yolov8.pt
![image](https://github.com/user-attachments/assets/8faa9051-8f18-409e-a355-39dc9d2519c2)
based on image C2F should get 32 ​​channels and I replaced it with DCN of course with my update the DCN  initialization (in_channels) in my CustomModel to match the preceding layer's output based code on bellow :
`class DCN(nn.Module):
    default_act = nn.SiLU()  # default activation
    def __init__(self, in_channels=32, out_channels=32, kernel_size=3, stride=1, padding=1, act=True):
        super().__init__()
        self.offset_conv = nn.Conv2d(in_channels, 2 * kernel_size * kernel_size, kernel_size=kernel_size, stride=stride, padding=padding)
        self.deform_conv = DeformConv2d(in_channels, out_channels, kernel_size=kernel_size, stride=stride, padding=padding)
        self.bn = nn.BatchNorm2d(out_channels)
        self.act = self.default_act if act is True else act if isinstance(act, nn.Module) else nn.Identity()`
this is new yaml configuration : 
`backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [8, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 1, 1]] # 1-P2/4
  - [-1, 3, DCN, [128, 3, 2]]`
 am i still make mistakes on the configuration.. please mention on my detail. thank you so much..

**Comment by glenn-jocher** [comment]
Thank you for the update and for providing detailed observations. The issue you're encountering likely stems from mismatches in channel dimensions within your `head` configuration when integrating the `DCN` module. The `Detect` head module expects consistent channel outputs from the preceding layers, and any inconsistency can lead to such errors.

To ensure the `DCN` module works while keeping your `head` configuration intact:
1. Verify that the output channels of your `DCN` layer align with the input channels expected by subsequent layers in the `head`.
2. Adjust the `DCN` module's output dimensions or insert a `Conv` layer after the `DCN` to reshape its output to match the expected dimensions.
3. Debug by printing the tensor shapes at each stage to locate any mismatches in the pipeline.

If further assistance is needed, please share the exact channel dimensions at each stage for better guidance. Let me know how it goes!

**Comment by yudis2** [comment]
hello @glenn-jocher, i just observe the DCN how to work but i dont understand with in and output channel DCN working,
lets breakdown on my case : 
[-1, 1, Conv, [64, 3, 2]] -> the output yolov8n is 64/0.25 -> 16 output channel its mean 3, 16, 3, 2 for the output layer 1,
[-1, 1, DCN, [128, 3, 2]] -> the output result isnt 32 ? and the result is still same what i have write on yaml is 128, 3, 2. not receive output channel on layer 1 is 16.  what the result actually from DCN modul ? its same or not with conv layer (e.g 1[6, 32, 3, 2])?
[-1, 3, C2f, [128, True]] -> the output yolov8n is 128/0.25 -> 32 output channel its mean '16', 32, 1, True, for the output layer 3. the '16' make a layer is error because the result of DCN not receive on layer.

**Comment by glenn-jocher** [comment]
Hello @yudis2, thank you for your detailed question! The `DCN` module behavior differs slightly from standard convolution layers. 

The output channels of `DCN` are determined explicitly by the second parameter in the YAML configuration (e.g., `[128, 3, 2]`), regardless of the input channels. This means that the `DCN` layer does not automatically adapt its output channels to match the preceding layer but instead follows what is specified in the arguments.

For your case:
1. `[-1, 1, Conv, [64, 3, 2]]` produces 64 output channels.
2. `[-1, 1, DCN, [128, 3, 2]]` explicitly sets the output to 128 channels, independent of the input channels from the previous layer.
3. The subsequent `C2f` layer must match the expected input channels (`128` in this case) to avoid errors.

To resolve the mismatch, ensure the input channels to each layer match the output channels of the preceding layer. You can add intermediate `Conv` layers to adjust channel dimensions as needed. Let me know if you need further assistance!

**Comment by yudis2** [comment]
i have to add add extra conv layer but its still problem with dcn layer
![image](https://github.com/user-attachments/assets/2bc45894-cefb-44be-9a86-1fd0209e8d77)
can you give me details to solve my problem or i still not correct to write the dcn modul ? 
`class CustomModel(nn.Module):
    default_act = nn.SiLU()  # default activation
    def __init__(self, in_channels, out_channels, kernel_size=3, stride=1, padding=1, act=True):`

**Comment by glenn-jocher** [comment]
Hello @yudis2, the `DCN` module does receive input from the previous layer, but its output channels are explicitly set by the second argument in the YAML configuration (e.g., `128` in `[-1, 1, DCN, [128, 3, 2]]`). If the preceding layer doesn't match the expected input channels for `DCN`, you need to ensure they are aligned by modifying the preceding layer's output channels or adding a `Conv` layer to adjust them. Let me know if you need further clarification!

**Comment by glenn-jocher** [comment]
Thank you for the clarification. The DCN layer does process the input from the prior layer, but its output channels are explicitly defined in the `[128, 3, 2]` configuration, overriding the input-output channel relationship that standard convolution follows. To ensure consistency in your architecture, confirm that the preceding and succeeding layers are configured to match the expected input and output channels. If the issue persists, trace the tensor shapes at each stage to pinpoint mismatches. Let me know how it goes!

**Comment by yudis2** [comment]
hello @glenn-jocher the my dcn modul **hasn't already implement on parse model** is it because of that model cant match input-ouput channel. my **focus** is the **DCN not receive the output prior layer,** and the output of DCN isnt not receive on succeeding layer. i have trace the shape of tensor
layer 1. [-1, 1, Conv, [64, 3, 2]] -> the result 3, 16, 3, 2
layer 2. [-1, 1, DCN, [128, 3, 2]] -> the result is 128, 3, 2. **how it should be 16, 128, 3, 2**
the problem is the output from layer 1 receive in layer 3.
layer 3. [-1, 1, C2f, [128, True]] -> 16, 32, 1, True. **how it should be 32, 32, 1 True.**

i hope you understand what i mean. sorry for much ask to you thank you so much..

**Comment by glenn-jocher** [comment]
Thank you for the detailed explanation. It seems the issue lies in how the `DCN` module is implemented and parsed in the model. Specifically, the `DCN` is not properly receiving the output from the preceding layer, and its output is not correctly passed to the succeeding layer. This might be due to how the `DCN` is added to the `parse_model` logic in `tasks.py`.

To resolve this, ensure:
1. The `DCN` is properly registered in `parse_model` so it can correctly handle the input/output channels, similar to other modules like `Conv` or `C2f`.
2. Update the `args` in your `DCN` implementation to explicitly align input/output channels with prior and succeeding layers.
3. Trace tensor shapes step-by-step in both `parse_model` and during forward passes to verify channel consistency.

Let me know if further clarification is needed!

**Comment by yudis2** [comment]
thanks you so much @glenn-jocher its work my mistakes is not implement DCN input-ouput channel on DCN modul, but now i have problem. this error : RuntimeError: offset.shape[1] is not valid: got: 32 expected: 18.
with this detail DCN : 
`class DCN(nn.Module):
    default_act = nn.SiLU()  # default activation
    def __init__(self, c1, c2, k=3, s=1, p=1, d=1, act=True):
        super().__init__()
        self.offset_conv = nn.Conv2d(c1, c2, 2*k*k, s, autopad(k, p, d), dilation=d, bias=False)
        self.deform_conv = DeformConv2d(c1, c2, k, s, p)
        self.bn = nn.BatchNorm2d(c2)
        self.act = self.default_act if act is True else act if isinstance(act, nn.Module) else nn.Identity()

    def forward(self, x):
        offset = self.offset_conv(x)
        out = self.deform_conv(x, offset)
        return self.act(self.bn(out))`

**Comment by glenn-jocher** [comment]
You're welcome! The error `RuntimeError: offset.shape[1] is not valid: got: 32 expected: 18` occurs because the `offset_conv` layer is producing an incorrect number of channels for the offsets. For deformable convolutions, the `offset.shape[1]` should equal `2 * kernel_size * kernel_size`, which represents the offsets for each spatial position.

In your `DCN` implementation, you need to modify the `self.offset_conv` layer to produce the correct number of offset channels. Specifically, replace `c2` in the `self.offset_conv` definition with `2 * k * k` (since `k` is the kernel size). Here's the corrected code:

```python
class DCN(nn.Module):
    default_act = nn.SiLU()  # default activation
    def __init__(self, c1, c2, k=3, s=1, p=1, d=1, act=True):
        super().__init__()
        self.offset_conv = nn.Conv2d(c1, 2 * k * k, k, s, autopad(k, p, d), dilation=d, bias=False)
        self.deform_conv = DeformConv2d(c1, c2, k, s, p)
        self.bn = nn.BatchNorm2d(c2)
        self.act = self.default_act if act is True else act if isinstance(act, nn.Module) else nn.Identity()

    def forward(self, x):
        offset = self.offset_conv(x)
        out = self.deform_conv(x, offset)
        return self.act(self.bn(out))
```

This ensures that the `offset_conv` produces the correct number of channels for the deformable convolution's offsets. Let me know if you encounter any further issues!

**Comment by yudis2** [comment]
thanks @glenn-jocher glen the DCN now its works! but i have some problem when i run the model in google collabs with run type G4 or v28TPU it will crash as shown below
![fb7d1153-3ba4-4b16-9c36-5a83a0859bec](https://github.com/user-attachments/assets/a238e1c5-d143-4b01-8da7-d8c1aa33c5fc)

**Comment by glenn-jocher** [comment]
You're welcome! Crashes on specific hardware like G4 or v2-8TPU could relate to compatibility or resource limitations. Ensure you are using the latest versions of PyTorch, torchvision, and Ultralytics, and confirm that your DCN module and model configurations are optimized for the selected hardware. If the issue persists, please provide more details, such as the exact error message or logs, for further investigation.

**Comment by yudis2** [comment]
haloo @glenn-jocher ! im sorry taking a long to reply your response. im have search that problem and then i get a solution to downgrade the pytorch etc version, on this time my version is torch-2.3.0a0+gitd2f947. its running when not implemented DCN module. but when i installed `!pip install torch==1.11.0+cu102 torchvision==0.12.0+cu102 -f https://download.pytorch.org/whl/torch_stable.html` the CUda not available and the DCN can be run. can you help me. i use AMD Radeon RX 7900XT 20GB DDR6

**Comment by glenn-jocher** [comment]
@yudis2 thank you for your detailed explanation! Unfortunately, PyTorch does not support CUDA acceleration on AMD GPUs like the Radeon RX 7900XT, as CUDA is NVIDIA-specific. For AMD GPUs, you can use ROCm (Radeon Open Compute) instead. Ensure you install a ROCm-compatible version of PyTorch by following the official PyTorch ROCm installation guide: https://pytorch.org/get-started/locally/. Let me know if you encounter further issues!

**Comment by yudis2** [comment]
hello glen thank you for your help, i getting error again when i have been away for a long time to train this model, the output channel isnt not match

<img width="898" alt="Image" src="https://github.com/user-attachments/assets/002fef5a-47a6-4432-8bfa-84d9610abd4e" />

i was done with your recomen code but on this time i got the error again please help me @glenn-jocher
