### ISSUE TITLE
Adjust webcam resoltuion for prediction

### ISSUE THREAD

**Issue by Deep-Learner** [ultralytics/ultralytics#1446]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Is it possible to add an optional parameter (maybe called imgsz) for the predict task, which is used if the source is a number instead of a path, to adjust the webcam resolution?

### Use case

It seems that OpenCV uses a default resolution of 640 x 480, completely independent of the resolution of the webcam.

### Additional

Dear YOLOv8 Team,
thanks for your great work, I really enjoy YOLOv8!

I fine-tuned a YOLOv8 model on "large" images and would like to run my trained model with my laptop camera or webcam. It seems like OpenCV uses a standard resolution for webcams of 640 x 480, no matter which max. resolution our webcam supports. You can check if this is true for you as well with the following code:
```
import cv2

vidcap = cv2.VideoCapture(0)
suc, img = vidcap.read()
if suc:
    print("Webcam resolution:", img.shape)
else:
    print("You do not use a webcam.")

vidcap.release()
cv2.destroyAllWindows()
```
I suppose you are using OpenCV to get the webcam stream. So, I searched for a solution to this, and we could add two lines to our code above, to change the resolution. The new parameter `imgsz` could be None by default, and if it is a tuple like `imgsz=(1280, 1024)` we could do the following:
```
import cv2

imgsz = (1280, 1024)
vidcap = cv2.VideoCapture(0, cv2.CAP_DSHOW)

if type(imgsz) is tuple:
    vidcap.set(cv2.CAP_PROP_FRAME_WIDTH, imgsz[0])
    vidcap.set(cv2.CAP_PROP_FRAME_HEIGHT, imgsz[1])

suc, img = vidcap.read()
if suc:
    print("Webcam resolution:", img.shape)
else:
    print("You do not use a webcam.")

vidcap.release()
cv2.destroyAllWindows()
```
I am aware that I could do this in my Python script as well, reading the video stream itself and sending each video frame to the prediction method (instead of setting source=0 in the predict task), but I think your code is much faster than mine and adding this little feature would help more people(?)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi 👋🏻! I'm also curious if selecting stream resolution when using a webcam is possible.

**Comment by arturovv21** [comment]
I also need to change the camera resolution when doing webcam real-time tracking. How can it be done?

**Comment by arturovv21** [comment]
Also related, zone_annotator does not work properly while using the track mode. Index goes out of bounds when the object goes out of the image. But line_annotator works well. I think it is due to X and Y being interpolated out of the index while moving? I even see negative values in the xyxy detections.

**Comment by arturovv21** [comment]
Hello, I tried it that way for results=model.track() but it will not work. While the camera resolution does change, it keeps updating the tracker_id... So it only works for object detection and maybe prediction?

**Comment by glenn-jocher** [comment]
@Deep-Learner @arturovv21 webcam input is set by your streaming source command, inference resolution is already defined by imgsz, so i.e. our YouTube predict example streams at 1280 but runs inference at 320 with this command:

```python
yolo predict source=https://youtu.be/Zgi9g1ksQHc imgsz=320

WARNING ⚠️ 'model' is missing. Using default 'model=yolov8n.pt'.
Ultralytics YOLOv8.0.54 🚀 Python-3.10.6 torch-1.13.1 CPU
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

1/1: https://youtu.be/Zgi9g1ksQHc... Success ✅ (6557 frames of shape 1280x676 at 24.00 FPS)

0: 192x320 (no detections), 21.8ms
0: 192x320 (no detections), 16.6ms
0: 192x320 (no detections), 14.8ms
0: 192x320 (no detections), 13.4ms
0: 192x320 (no detections), 13.4ms
...
```

If you'd like to see changes to the stream loader please make any relevant updates in a PR where we can review. Thank you!

**Comment by SkalskiP** [comment]
@glenn-jocher webcam can stream at different resolutions. You are picking the default one. OpenCV is capable of changing default to other supported resolution.

**Comment by SkalskiP** [comment]
> Also related, zone_annotator does not work properly while using the track mode. Index goes out of bounds when the object goes out of the image. But line_annotator works well. I think it is due to X and Y being interpolated out of the index while moving? I even see negative values in the xyxy detections.

@arturovv21 that does not sound right. Could you create issue in supervision repo? I’ll take a look into that problem. I don’t want us to pollute YOLOv8 issues with our problems :)

**Comment by Deep-Learner** [comment]
@glenn-jocher thanks for you answer. Before I created this issue, I checked the predict parameters in the docu here:
https://docs.ultralytics.com/usage/cfg/#prediction
But I could not find the parameter imgsz for the predict task. I haven't checked the implementation of imgsz, but I checked the YOLOv8 code for the VideoCapture and could not find the two lines, I mentioned above
```
vidcap.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
vidcap.set(cv2.CAP_PROP_FRAME_HEIGHT, 1024)
``` 
So, I'm wondering if the implementation of imgsz (as you mentioned) is just a resize of the original source. Because, that's not what I'm looking for, I really want to use a better input resolution. OpenCV uses 640 x 480 by default, no matter even if our webcam supports HD or even 4K recordings.

**Comment by glenn-jocher** [comment]
@Deep-Learner cv2 is reading my webcam at 1920, so I think this is mainly between you and your streaming source rather than any cv2 limitation.

<img width="691" alt="Screenshot 2023-03-19 at 19 46 42" src="https://user-images.githubusercontent.com/26833433/226199904-fdbebd9b-2486-442f-9c6f-ae94683f823c.png">

**Comment by arturovv21** [comment]
Thanks for the responses. The "imgsz" seem to work for the inference. However, the camera resolution is still "default" which is usually lower than needed (in my case is 640 x 480) but it can do 1920 x 1080. I still have not found a way to included in the tracking algo. For detection only, I was using this code that worked (but it doesn't work for "model.tracking" since Tracker_IDs change in the loop every time the frame is read):

   cap = cv2.VideoCapture(0, cv2.CAP_DSHOW)
   print("Frame default resolution: (" + str(cap.get(cv2.CAP_PROP_FRAME_WIDTH)) + "; " + 
   str(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)) + ")")

   cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1920)
   cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 1080)

   r, frame = cap.read()

   print('Resolution: ' + str(frame.shape[0]) + ' x ' + str(frame.shape[1]))

This gives:
   Frame default resolution: (640.0; 480.0)
   Resolution: 1080 x 1920

**Comment by 1qh** [comment]
I'm humbly asking for help. If there's anyone who can shed some light on this issue or offer guidance, I would be deeply thankful.

**Comment by pderrenger** [comment]
@1qh I understand your concern and the importance of having control over the camera resolution for both inference and tracking. At the moment, the `imgsz` parameter in the predict task is designed to adjust the inference resolution, but it doesn't directly control the webcam resolution.

For tracking, the camera resolution is indeed controlled by OpenCV and is not currently configurable through YOLOv8 directly. It seems the issue lies in maintaining consistent tracking IDs when changing the camera resolution, which can be challenging due to the tracker's dependency on spatial and appearance information from the frames.

While we currently don't have a built-in solution for this specific use case, the Ultralytics team is always looking to improve the user experience based on community feedback. I'd recommend raising this as a feature request, providing clear use cases and examples, on the [Ultralytics GitHub Issues](https://github.com/ultralytics/ultralytics/issues) page, where it can be discussed and considered for future updates to YOLOv8.

Thank you for your understanding and for being part of the YOLOv8 community!

**Comment by glenn-jocher** [comment]
@pderrenger Your request for webcam resolution control is valid and I appreciate your patience. The `imgsz` parameter indeed adjusts the inference size, but not the webcam capture resolution. Currently, YOLOv8 does not offer a direct method to change the webcam resolution within the tracking or predict tasks.

The code snippet you've provided is a good approach for setting the webcam resolution using OpenCV, but integrating this functionality into the YOLOv8 tracking system would require additional development.

I encourage you to open a feature request issue on the [Ultralytics GitHub Issues](https://github.com/ultralytics/ultralytics/issues) page detailing your use case. This will allow the community to discuss and potentially contribute to a solution that integrates webcam resolution settings into YOLOv8's tracking capabilities.

Your contributions and feedback are invaluable to us, and we're committed to enhancing YOLOv8 with features that support our users' needs. Thank you for being an active member of our community!

**Comment by glenn-jocher** [comment]
@pderrenger I appreciate your patience and the detailed explanation of your issue. The `imgsz` parameter indeed adjusts the inference resolution, but it does not change the webcam's capture resolution, which is set by OpenCV defaults or manually using OpenCV properties as you've done in your script.

Currently, YOLOv8 does not offer a parameter to directly modify the webcam capture resolution within the tracking mode. This is a valid point for enhancement, and I encourage you to open a feature request on the [Ultralytics GitHub Issues](https://github.com/ultralytics/ultralytics/issues) page. Your input is valuable, and such contributions help us improve the functionality and flexibility of YOLOv8 for all users.

Thank you for your contribution to the YOLOv8 community, and we look forward to your feature request!
