### ISSUE TITLE
Failed to train on AMD GPU (RCOM enabled and validated)

### ISSUE THREAD

**Issue by JobberRT** [ultralytics/ultralytics#14503]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

Hi, Thanks for this amazing project. I found that I can use HuggingFace's lib and models to train Yolo but failed on this project. My GPU is AMD 7900XTX.

### Fail Behavior
The GPU usage is 100% but the train progress will never start. Title shown but there's no value(current batch index, train speed, gpu memory usage etc.)

### Training Code
```python
model = YOLO("yolov8m.pt")
model.train(
 # Some params here
 device="cuda"
)
```

### Additional Inforation
I can share the HuggingFace training code and Ultralytics training code, also a simple ROCM CUDA verify script.  But the code is long so to avoid messing up the whole page, I will only share the code if you want it

### Environment
Ubuntu 22.04 + AMD 7900XTX + ROCM 6.1

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@JobberRT hi there! Thanks for your kind words and for bringing this to our attention. It sounds like you're having trouble with training on an AMD GPU. While YOLOv8 primarily supports NVIDIA GPUs, you might want to ensure you're using the latest versions of PyTorch and ROCm. Sometimes, compatibility issues can arise with specific hardware setups. If the problem persists, please try running your code on the latest YOLOv8 release to see if the issue is resolved. If you continue to face difficulties, feel free to share any additional details or logs here.

**Comment by glenn-jocher** [comment]
To further clarify, Ultralytics does not currently support AMD GPU training, but @JobberRT if you are able to submit a PR with the changes required we'd be super happy to review!
