### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas._libs.interval'

### ISSUE THREAD

**Issue by cakwok** [ultralytics/ultralytics#1464]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

For some reasons i have changed python version at google colab.  since then i cannot run yolo8 again and i encounter this error - 

ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-11-00282710d424>](https://localhost:8080/#) in <module>
----> 1 from ultralytics import YOLO
      2 
      3 # Load a model
      4 model = YOLO("yolov8n.yaml")  # build a new model from scratch
      5 #model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)

11 frames
[/content/drive/MyDrive/Colab Notebooks/Bruce/Yolo8-lib/pandas/_libs/__init__.py](https://localhost:8080/#) in <module>
     11 
     12 
---> 13 from pandas._libs.interval import Interval
     14 from pandas._libs.tslibs import (
     15     NaT,

ModuleNotFoundError: No module named 'pandas._libs.interval'

Could you help to advise how shall I fix the issue?  Reinstallation is only the last resort since i have customed quite number of scripts.  The Python version is currently 3.9.16 fyi.

Thanks a lot.

**Comment by glenn-jocher** [comment]
@cakwok since your issue in not reproducible I would recommend you try an official environment below where everything will work correctly.

## Environments

YOLOv8 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/GCP-Quickstart)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/AWS-Quickstart)
- **Docker Image**. See [Docker Quickstart Guide](https://github.com/ultralytics/yolov5/wiki/Docker-Quickstart) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>
