### ISSUE TITLE
Which Annotation Tool for OBB?

### ISSUE THREAD

**Issue by dhunjoshi** [ultralytics/ultralytics#14680]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to know which annotation tool is suitable for oriented bounding box.

**Comment by Johan154** [comment]
You can also make annotations for an instance segmentation model. When you train an OBB model, the annotations are automatically converted to OBB annotations.

**Comment by Y-T-G** [comment]
https://github.com/CVHub520/X-AnyLabeling

**Comment by Petros626** [comment]
@dhunjoshi I can recommend you CVAT (https://www.cvat.ai/) for fast labeling.

**Comment by ryouchinsa** [comment]
[RectLabel](https://rectlabel.com/) added "rotated box" to the Create polygon using SAM.

<video src="https://github.com/user-attachments/assets/f5b2d9f6-dba6-4a56-acb6-8c71206a55a9" controls="controls" muted="muted" class="width-fit" style="max-height:640px; min-height: 200px"></video>

When principal component analysis does not recognize the correct orientation.

<video src="https://github.com/user-attachments/assets/ec7e3f6f-1da9-4ae2-8c9d-a52be252f5b6" controls="controls" muted="muted" class="width-fit" style="max-height:640px; min-height: 200px"></video>

**Comment by glenn-jocher** [comment]
Nice, thanks for sharing the RectLabel update. For anyone landing on this thread: YOLO OBB models only require labels in the YOLO OBB text format, so you can use any tool that supports polygons or rotated boxes and then convert/export to that format as outlined in the [OBB datasets overview](https://docs.ultralytics.com/datasets/obb/); since this issue is closed and marked stale, please open a new issue or discussion for any new OBB annotation questions so the team can see them.
