### ISSUE TITLE
How to stop ultralytics model. rain in Python code

### ISSUE THREAD

**Issue by zhang7249** [ultralytics/ultralytics#14747]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to turn off train in Python code, but I tried calling task.cancel() and returned true, but the process of model. train did not end. What should I do to close the model.train process. thank

```
@ai_train_router.get("/close_train_task")
def close_train_task():
    if len(job_task) == 0:
        logger.info("---------------->job_task 为空")
    for key, value in job_task.items():
        logger.info("---------------->key={}".format(key))
        try:
            task = value[0].current_task(value[1])
            if not task.done():
                result = task.cancel()
                logger.info("---------------->task.cancel()={}".format(result))
        except CancelledError as e:
            logger.info("[%s] cancelled success" % key)
```

```
import asyncio
import json
import os
import shutil
import subprocess
import sys
import time
import traceback
import torch
import uuid
from apscheduler.schedulers.background import BackgroundScheduler
from loguru import logger
from ultralytics import YOLO

from service.global_queue import queue, job_task
from utils.comm_util import read_ini

scheduler = BackgroundScheduler()


async def cron_job(_uuid):
     try:
        model.train(data=_data, model=_model, epochs=_epochs,
                    batch=_batch, imgsz=_img_sz, workers=16, device=read_ini("server", "train.device"), patience=50)
     except asyncio.CancelledError:
        logger.info("--------------------------> main(): cancel_me is cancelled now")




def long_running_task():
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    _uuid = str(uuid.uuid4())
    job_task[_uuid] = [asyncio, loop]
    loop.run_until_complete(cron_job(_uuid))
    loop.close()


scheduler.add_job(long_running_task, 'interval', seconds=10, max_instances=4)

if __name__ == '__main__':
    cron_job()
```

**Comment by pderrenger** [comment]
@zhang7249 to stop the `model.train` process in Python, you should ensure that the training loop is responsive to cancellation requests. The `asyncio.CancelledError` should be properly handled within the training loop. If the current implementation does not respond to `task.cancel()`, it might be due to the training loop not checking for cancellation requests frequently enough.

You can try updating to the latest version of the Ultralytics package to see if the issue persists. If the problem continues, consider adding periodic checks for cancellation within the training loop to ensure it can terminate gracefully when requested.

If you need further assistance, please provide more details about your setup or any specific errors you encounter.
