### ISSUE TITLE
Adding new YOLOv8 detection classes additionally and adding layers above with preserving all pretrained weights and detection head with 80 COCO classes.

### ISSUE THREAD

**Issue by ablyzniuk** [ultralytics/ultralytics#14974]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi there again!)
I'm currently struggling with adding some more new layers and adding more classes for the existing YOLOv8 topology and training those on a custom dataset. I also wish to preserve YOLOv8 pretrained COCO weights with its' head.
So:

1. I edited Ultralytics source files to create a new head alongside the old one and concatenate them. Ex: ConcatHead(oldHead, newHead) - Gives us a new head with 90 classes(80 COCO, 10 mine). The result was unsatisfying(precision and recall metrics were too low and false positives in outcomes). I experimented with unfreezing some layers before the detection head - the result was bad also. 
2.  Cleared and inspected my dataset again - I won just a few percent in metrics.
3.  My dataset has been increased by synthetic data - I assumed that I could mix my dataset with COCO and train with it. I increased the dataset to compete COCO classes to avoid degradation of network weights, - in other words made the data more balanced. After 40 and 100 epochs on pretrained yolov8n on a mix of COCO and custom datasets with 640x640 input image size result was also bad. (I think that I will try from the scratch zero network)
4. THE BEST results I gained from training pretrained network on my own data by an overwriting head by my classes as in the example:
`model = YOLO("yolov8n.pt")`
`torch.cuda.empty_cache()`
`model.train(data="custom_data.yaml", epochs=15, imgsz=640, batch=32, optimizer="Adam")`
`"best results"`
So, I assume, that adding few more layers before my custom head and concatenation custom head with COCO head with preserving the original weights will give me satisfying results in detection COCO classes and mine.

I want to ask for some shortcuts and examples of how can I add few more layers in general and easy ways or any advice on how to implement that correctly. Would you like please to give me advanced tips and easy tips? Do I need to edit yolov8.yaml, how should I do this, or I can implement it in the code, and how should I do that too? Or are my observations wrong and I should take a different path?

**Comment by pderrenger** [comment]
@ablyzniuk hi there,

It sounds like you're working on a complex task of extending YOLOv8's capabilities while preserving its pretrained weights. Here are a few suggestions that might help streamline your process:

1. **Custom Layers and Heads**: Adding new layers and heads can indeed be challenging. Instead of manually editing the source files, consider modifying the `yolov8.yaml` configuration file. This file allows you to define the model architecture, including adding new layers or heads. Ensure that the new layers are compatible with the existing architecture to avoid issues.

2. **Training Strategy**: When combining COCO and custom datasets, balancing the dataset is crucial. However, mixing datasets can sometimes lead to suboptimal results due to domain differences. You might want to try fine-tuning the model on your custom dataset after initially training on the combined dataset. This can help the model adapt better to your specific classes.

3. **Hyperparameters**: Experimenting with different hyperparameters such as learning rates, batch sizes, and optimizers can significantly impact performance. Since you mentioned using Adam, you might also want to try other optimizers like SGD with momentum to see if they yield better results.

4. **Evaluation Metrics**: Keep a close eye on evaluation metrics during training. Sometimes, overfitting can occur if the model is trained too long on a small dataset. Early stopping and model checkpoints can help mitigate this.

5. **Community Resources**: For advanced modifications, consider exploring community forums and discussions. Many users share their experiences and solutions, which can provide valuable insights and shortcuts.

If you continue to face issues, please ensure you're using the latest version of the Ultralytics package, as updates often include bug fixes and improvements.

Best of luck with your project! If you have further questions, feel free to ask.
