### ISSUE TITLE
How to get embeddings from model?

### ISSUE THREAD

**Issue by soltkreig** [ultralytics/ultralytics#1501]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi! I'm looking for answer how to get embeddings from detection object?

**Comment by glenn-jocher** [comment]
@soltkreig could you explain a little more the outputs you want? Do you mean you want the feature vector at each grid point?

**Comment by davidbernat** [comment]
@glenn-jocher @soltkreig To my surprise this seems to be the only ticket in this repository that discusses extracting embeddings at the image (or at the per-object level). There was tacit support previously during YOLOv5. Is this a feature you intend on offering in the near future or are you expecting a develop community to take over its development?

**Comment by glenn-jocher** [comment]
@davidbernat hello! Thanks for reaching out and expressing your interest in this feature.

While it's true that such a feature has interesting potential applications, we currently do not have explicit plans to offer embeddings extraction at the image or per-object level in the YOLOv8 roadmap. This might be subject to change in the future following the community's interests and needs.

However, due to the open-source nature of this project, developers and researchers are always encouraged to build upon this work to best suit their specific requirements. We're very open to contributions from the broader community and would welcome any plans or ideas to implement this feature. 

Please remember that any code changes or additions must be made in alignment with the AGPL-3.0 license and should be thoroughly tested before proposing changes or making a pull request. 

I hope this information was helpful! Let us know if you have further questions.

**Comment by rob-rapid-robotics** [comment]
@soltkreig Have you had any success or insights into how to make this happen?

**Comment by Stijnp** [comment]
Also interested in this ! Thinking this could be useful for monitoring for data drift

**Comment by pderrenger** [comment]
Extracting embeddings for monitoring data drift is indeed a valuable use case. While this feature isn't natively supported in YOLOv8, you can modify the model's forward method to access intermediate feature layers. This approach allows you to extract the necessary embeddings for your application. If you need further assistance, feel free to ask!

**Comment by pedromoraesh** [comment]
> Also interested in this ! Thinking this could be useful for monitoring for data drift

Did you see Yolov8 [predict](https://docs.ultralytics.com/modes/predict/#inference-arguments) docs? There is actually an embed argument where you specify which layer you want to extract the embedding vector, did you tried it?

**Comment by glenn-jocher** [comment]
@pedromoraesh you can extract embeddings using the `embed` argument in the YOLOv8 predict mode. Check the [predict documentation](https://docs.ultralytics.com/modes/predict/#inference-arguments) for more details.
