### ISSUE TITLE
Is There Any Plan for YOLOv11?

### ISSUE THREAD

**Issue by geoxpert0001** [ultralytics/ultralytics#15028]
I would like to ask the YOLOv8 team, YOLO has already reached the tenth generation, and I am wondering if your team has any plans to release the 11th generation. I hope the next generation can increase the imgsize to 1280 or even higher for the pre-trained weights. Currently, 640 is somewhat impractical. Although I know it is possible to adjust the detection imgsz size, I would like your team to fundamentally train a model that is truly designed for 1280 or even higher resolution for inference.

**Comment by Skillnoob** [comment]
1. Its not ultralytics's decision to make if yolov11 gets made, some researcher is probably already working on it
2. The models are with a imgsz of 640 because coco only has 640×480 images, a higher imgsz wouldn't gain you anything

**Comment by geoxpert0001** [comment]
> 1. Its not ultralytics's decision to make if yolov11 gets made, some researcher is probably already working on it
> 2. The models are with a imgsz of 640 because coco only has 640×480 images, a higher imgsz wouldn't gain you anything

1. What I meant was not v11, but rather whether there are plans for the next generation of YOLO.
2. I understand that COCO is only 640x480, but the demands of the real world far exceed this image size. Whether it's CCTV or mobile phones, image sizes are at least 1280 or above. I believe that if we truly want to advance object detection, we should start considering optimization for larger image sizes, as 640 is too low of a demand.

**Comment by pderrenger** [comment]
@geoxpert0001 thank you for your feedback. While we can't comment on specific plans for future YOLO versions, we appreciate your input on the need for higher resolution models. The current models are optimized for 640x480 due to the COCO dataset, but we understand the demand for larger image sizes in real-world applications. Your suggestion is valuable, and we will consider it for future developments. For now, you can adjust the detection image size in your configurations to better suit your needs.

**Comment by Skillnoob** [comment]
@geoxpert0001 
1. It is very likely that there are researchers working on a new generation of the YOLO models, but Ultralytics does not own YOLO so it has no control over that.
2. The problem is that with datasets that exceed a image size of 640x480, the storage space they require will increase dramatically. 4 times to be precise.

Also, not every "new" generation equals a direct improvement when you train it on your dataset. On some datasets v10 will perform really well, on some v8 outperforms by a lot.

**Comment by zshar7** [comment]
@geoxpert0001 YOLOv11 was presented on YOLO Vision today. Expect release soon I guess!
