### ISSUE TITLE
Unsmooth segmentation boundary

### ISSUE THREAD

**Issue by jiaqizhang123-stack** [ultralytics/ultralytics#1503]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, when I reduced the size of the image for testing, the segmentation boundary was not smooth. What was the main reason for this?
![image](https://user-images.githubusercontent.com/55009436/226283969-a4f18260-a39f-444e-9ea9-bb1b986e1cb7.png)

**Comment by JustasBart** [comment]
Hi @jiaqizhang123-stack I believe that this is just the result of optimization.
That is reducing the size of the images reduces the available resolution for the model and thus everything looks more block-y and therefore not smooth. There's always a trade off with AI (Otherwise if there wasn't then everything would be really low resolution, supper efficient and would work really good) but in reality there's always going to be a trade-off between speed and performance. In this case you should sacrifice some speed to gain the extra performance.

Hope this helps, good luck! :rocket:

**Comment by jiaqizhang123-stack** [comment]
Thank you very much, I also have a question. When the original size of the image is 2048, I use 1024 for training, but the size of 1024 will have a segmentation problem, and 2048 is fine. However, when the original size of the image is 1024, I use 1024 for training, but the size of 1024 will not have a segmentation problem, which is affected by the reduction factor of the label?

**Comment by jiaqizhang123-stack** [comment]
When testing images with the same resolution, but the training original image resolution is inconsistent, the image segmentation boundary smoothness is inconsistent. What is the main reason for this?

**Comment by JustasBart** [comment]
@jiaqizhang123-stack I believe you might be seeing the effects of this:
![image](https://user-images.githubusercontent.com/40023722/226309582-ea454d30-cd4d-40fd-8e69-4d92d2eea6de.png)
you should set the **mask_ratio=1** for your Segmentation training.

Also, if you're using the official predictor then consider setting this flag as well:
![image](https://user-images.githubusercontent.com/40023722/226310007-dc8163c5-71ad-4715-a77a-fa3038590f8d.png)

You can find these flags (And others) in the docs [here](https://docs.ultralytics.com/usage/cfg/).

Other than that it's just about the experimentation and/or perhaps there's something else that I'm not aware of.

But naturally the higher resolution you can go with in the first place and the closer to that resolution that you can stick when training/inferencing the better.

Good luck! :rocket:

**Comment by jiaqizhang123-stack** [comment]
But when I used the official model for testing, the input size was 320, and the recognized mask did not show jagged patterns. Thank you very much for your help！
![zidane](https://user-images.githubusercontent.com/55009436/232024553-ad989306-5513-453d-b723-581830f6da5f.jpg)

**Comment by glenn-jocher** [comment]
@huanhuan-xiao hello there! If you want to only draw the edge lines of the mask instead of displaying the entire mask area, you can try using the Canny edge detector algorithm, which finds and outlines the edges in an image. 

You can also use the OpenCV `findContours()` function, which retrieves the contours of the mask and then use the `drawContours()` function to draw the contour lines on the image. 

Both of these options can be useful for drawing only the edges of the mask, as opposed to displaying the whole mask area. Good luck with your project!
