### ISSUE TITLE
Unexpected change in detection probability as image is translated

### ISSUE THREAD

**Issue by trianta2** [ultralytics/ultralytics#15073]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm experimenting with the yolov8 obb model and found something unexpected. When an image is translated, the detection probability can change significantly.

I've used an image off the internet, shared below, and pre-trained `yolov8n-obb.pt` to demonstrate the issue.

As I translate the image horizontally, the detection probability changes, swinging between approximately 0.79 and 0.85 in this case. Why does this happen? How can the fluctuations be reduced? I have tried increasing the amount of image translation during training augmentation but without success.

# Confidence vs. shift:

![image](https://github.com/user-attachments/assets/f275a5dd-a4a3-4bac-867f-4f51382d4c4e)

# Input image:

![boat](https://github.com/user-attachments/assets/dd451246-c86c-4e2e-b714-870a161b5a3e)

# Shift animation:

https://github.com/user-attachments/assets/500b44a3-bb6b-492d-8675-4e342a30e2b1

# Code:

```python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import cv2

img = cv2.imread('boat.jpg')
model = YOLO('yolov8n-obb.pt')

shifts = np.linspace(280, 600, dtype=int)
imgs = [np.roll(img, shift, axis=1) for shift in shifts]
results = model.predict(imgs)
confs = [res.obb.conf.item() for res in results]

df = pd.DataFrame({'conf': confs, 'shift': shifts})
df.set_index('shift').plot(xlabel='Shift', ylabel='Confidence', title='yolov8n-obb.pt confidence vs. image shift')

```

**Comment by pderrenger** [comment]
@trianta2 thank you for bringing this to our attention. The fluctuation in detection probability with image translation can be attributed to the sensitivity of the model to spatial changes. This behavior is not uncommon in object detection models, especially when dealing with oriented bounding boxes (OBB).

To mitigate this, consider the following:
1. Ensure you are using the latest version of the Ultralytics YOLO package, as updates often include performance improvements and bug fixes.
2. Experiment with different augmentation techniques during training, such as random cropping, scaling, and rotation, to improve the model's robustness to spatial transformations.
3. Fine-tune the model on a dataset that includes a variety of translations and shifts to help it generalize better.

If the issue persists, please provide more details or share a minimal reproducible example so we can investigate further.

**Comment by trianta2** [comment]
@pderrenger I've considered your points and the issue persists. I believe I've already included a minimal reproducible example in my original post.

I've experimented with additional augmentations for robustness to spatial translations without success. I've also found that this issue occurs in your non-oriented bounding box detection models.

**Comment by Burhan-Q** [comment]
@trianta2 this is likely a part of the NMS process, where small changes in the image result in compounding differences in the candidate predictions that result in a different "final" prediction. Take the two examples below:

![image](https://github.com/user-attachments/assets/5836105f-d00b-40ae-8a13-75bce5c4d829)

![image](https://github.com/user-attachments/assets/68881f81-43c5-48c6-95b8-225113a63042)

In the first image, the bounding box extends far beyond the aft of the ship, but in the second the bounding box does not fully enclose the entire aft of the ship, but extends beyond on the port side slightly less than the first. One experiment you could try is to lower the `iou` threshold, which _might_ result a more "stable" prediction being used as the "final" prediction (not certainty). The variability in your results are $± 0.025$ which (from my experience) seems quite consistent, but you can always "tune" your inference arguments to better suit your needs. For example, try using `model.predict(imgs, iou=0.1, imgsz=960)` and see if this change results in a more "stable" predicted confidence.

Overall, it's unlikely that you'll see a consistent predicted confidence value for the same object. You can see this in videos showing inference on the same object moving (much like you've simulated here, but usually at a higher frame rate). This would be due to small changes in the image data and small floating point differences in the model weights "reacting" differently to the "new" input data.
