### ISSUE TITLE
inference fps fluctuate

### ISSUE THREAD

**Issue by shieman** [ultralytics/ultralytics#1517]
Hi

When i use yolov8 with pytorch, onnx or tensorrt model, fps inference fluctuate and monitoring of Gpu shows that it is under utilised.

If i lauch on other program in parralel ( here Touchdesigner) wich uses Gpu, the Gpu frequency goes high and yolov8 inference fps goes down and don't fluctuate.

Is there a way to solve it ?

Thanks

**Comment by AyushExel** [comment]
The GPU can be( mostly is) under-utilized during inference, both in terms of memory and power consumption because it's not as intensive a task as training is. The FPS fluctuations however are a different matter. 5-10% fluctuation is common, but if you're seeing a **massive**, **reproducible** fluctuation, it can be a bug. Although we haven't seen anything like that in our testing. 
So, please provide a way to reproduce it and we'll try to confirm if any problem exists.

**Comment by shieman** [comment]
Hi
I resolved the problem of low fps caused by an opencv waitkey.
But the Gpu frequency (Laptop Rtx 3060) continues fluctuating between 1,1Ghz and 1,7Ghz...
When i launch Touchdesigner in parralel, frequency stays constant at 2Ghz.

**Comment by pderrenger** [comment]
@shieman the GPU frequency fluctuations you're observing might be due to varying workloads on the GPU, which can affect its clock frequency. When launching Touchdesigner, it's possible that it enforces a constant workload on the GPU, thus stabilizing the clock frequency.
If the varying clock frequency is negatively impacting YOLOv8 inference FPS, you might consider looking into GPU settings or power management modes to maintain stable clock frequency during inference. Additionally, optimizing GPU usage or workload scheduling might help stabilize the clock frequency during YOLOv8 inference.

**Comment by johnnynunez** [comment]
> Hi I resolved the problem of low fps caused by an opencv waitkey. But the Gpu frequency (Laptop Rtx 3060) continues fluctuating between 1,1Ghz and 1,7Ghz... When i launch Touchdesigner in parralel, frequency stays constant at 2Ghz.

how?

**Comment by glenn-jocher** [comment]
@johnnynunez great to hear you solved the FPS issue! 🚀 The GPU frequency fluctuations during YOLOv8 inference without Touchdesigner might be due to the GPU's attempt at power saving when the workload isn't constant. Launching Touchdesigner likely increases GPU demand, stabilizing its frequency. To achieve stable frequency without additional workload, you could explore setting a higher performance mode in your GPU's control panel or using a tool like `nvidia-smi` for NVIDIA GPUs. 

For example, you can try setting the power mode to `Prefer Maximum Performance` in the NVIDIA Control Panel under `Manage 3D settings`. 

Just a side note, ensure this change aligns with your power and thermal preferences!
