### ISSUE TITLE
Callbacks on_fit_epoch_end in final_eval creates error

### ISSUE THREAD

**Issue by silvanro** [ultralytics/ultralytics#1534]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

3 epochs completed in 0.001 hours.
Optimizer stripped from runs\train\exp8\weights\last.pt, 18.5MB
Optimizer stripped from runs\train\exp8\weights\best.pt, 18.5MB

Validating runs\train\exp8\weights\best.pt...
Ultralytics YOLOv8.0.47  Python-3.9.16 torch-1.13.1+cpu CPU
YOLOv5s summary (fused): 193 layers, 9111923 parameters, 0 gradients, 23.8 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  9.89it/s]
                   all          1          1          0          0          0          0

-------------->
metrics: {'metrics/precision(B)': 0.0, 'metrics/recall(B)': 0.0, 'metrics/mAP50(B)': 0.0, 'metrics/mAP50-95(B)': 0.0}
loss:9.60869026184082
fitness: 0.0
best fitness: 0.0
trainer.validator.metrics: <ultralytics.yolo.utils.metrics.DetMetrics object at 0x000001F5558A3BE0>
trainer.validator.speed: {'preprocess': 2.0012855529785156, 'inference': 91.11285209655762, 'loss': 0.0, 'postprocess': 1.9991397857666016}
trainer.epoch: 2
trainer.tloss: tensor([3.64489, 4.94206, 1.02174])
trainer.lr {'lr/pg0': 0.098068, 'lr/pg1': 6.8e-05, 'lr/pg2': 6.8e-05}
trainer.csv: runs\train\exp8\results.csv
label_loss_items ['train/box_loss', 'train/cls_loss', 'train/dfl_loss']
Speed: 2.0ms preprocess, 91.1ms inference, 0.0ms loss, 2.0ms postprocess per image
Results saved to runs\train\exp8
Traceback (most recent call last):
  File "C:\Users\u230546\Desktop\yolov8\main.py", line 60, in <module>
    trainer.train(**config.app.model)
  File "C:\Users\u230546\Anaconda3\envs\YOLOv8\lib\site-packages\ultralytics\yolo\engine\model.py", line 317, in train
    self.trainer.train()
  File "C:\Users\u230546\Anaconda3\envs\YOLOv8\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 188, in train
    self._do_train(RANK, world_size)
  File "C:\Users\u230546\Anaconda3\envs\YOLOv8\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 376, in _do_train
    self.final_eval()
  File "C:\Users\u230546\Anaconda3\envs\YOLOv8\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 513, in final_eval
    self.run_callbacks('on_fit_epoch_end')
  File "C:\Users\u230546\Anaconda3\envs\YOLOv8\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 166, in run_callbacks
    callback(self)
  File "C:\Users\u230546\Desktop\yolov8\main.py", line 41, in on_fit_epoch_end
    "val/box_loss": trainer.metrics['val/box_loss'],
KeyError: 'val/box_loss'

Process finished with exit code 1

### Environment

-YOLO: Ultralytics 8.0.47
-OS: Win10

### Minimal Reproducible Example

```from ultralytics import YOLO

model = YOLO('yolov8n.pt')

def on_fit_epoch_end(trainer):
    print(f"val/box_loss: {trainer.metrics['val/box_loss']}")


model.add_callback("on_fit_epoch_end", on_fit_epoch_end)
model.train(data='coco128.yaml', epochs=3)
```

### Additional

Why is the callback on_fit_epoch_end two times in the training pipeline? The second time in final_eval are not the same metrics available.

Thanks for your help and your amazing work!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃
