### ISSUE TITLE
 How to   print(model.names) in img classification?

### ISSUE THREAD

**Issue by dmddmd** [ultralytics/ultralytics#1544]
In object detection with yolov8, model.names gives the class names of the pretrained model.

But when using the pretrained models for classification, model.names gives
  'n02108551', 'n02783161', 'n03127747', 'n04259630', 'n02837789', 'n04505470', 
instead of real label names

**Comment by Laughing-q** [comment]
@glenn-jocher @AyushExel I'm able to reproduce the issue.
```python
from ultralytics import YOLO

model = YOLO("yolov8n-cls.pt")
print(model.names)
```

**Comment by AyushExel** [comment]
@Laughing-q It looks like we're not using autobackend to load the models anymore in the python interface? Autobacked checks for class names and applies imagenet names but the torch_safe_load method doesnt

**Comment by Laughing-q** [comment]
@AyushExel @dmddmd tested with `model.predict` and it looks good. 
![20230322-161805](https://user-images.githubusercontent.com/61612323/226840851-11c2d148-a62c-4b55-903e-d21b7045e168.png)
@AyushExel the above code does not do anything but initializing model so it has not reached the `autobackend` part.

**Comment by glenn-jocher** [comment]
@dmddmd this is expected and correct, those are the actual imagenet classes. When running prediction we map these to their "pretty" names for plotting results to images and console. The function that we use for this for Imagenet is here:
https://github.com/ultralytics/ultralytics/blob/8c8c43922c8a01f70ef462a3213c270648275bb3/ultralytics/nn/autobackend.py#L23-L38

**Comment by glenn-jocher** [comment]
@VanNamMan your provided snippet seems correct in predicting the class of an image using a pretrained YOLOv8 model. The 'results' variable should contain an array of Prediction instances, each containing useful information about the prediction.

Iterating through 'results', for each 'result', you're obtaining the probabilities of the classes ('probs'), selecting the index of the class with the highest probability ('class_index'), and subsequently retrieving the name of the class ('class_name').

The 'score' variable represents the confidence score of the class, which is then converted to a numpy float for further usage. 

If you're encountering any difficulties or have further questions, please provide more specific details so that we can assist you better. Our priority is to ensure that you're able to use YOLOv8 to its fullest.
