### ISSUE TITLE
About result saving

### ISSUE THREAD

**Issue by YycYoung** [ultralytics/ultralytics#1545]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Why sometimes after training, the results are saved in the folder with only result.png, but no confusion matrix.png, F1-curve.png, P-curve.png, R-curve.png, PR-curve.png?

**Comment by VGONUL** [comment]
![image](https://user-images.githubusercontent.com/122591055/226648775-36914d08-8a93-44cd-a545-031b10d25898.png)
did you check here?

**Comment by Laughing-q** [comment]
@YycYoung these would be generated in the final evaluation of the training. Probably it's because your training was interrupted If you didn't get these.
I just finished a one epoch training with coco128.yaml and the folder looks correctly.
![image](https://user-images.githubusercontent.com/61612323/226815267-f0fbe7b0-7f85-4d1f-b16c-564affd5787e.png)
