### ISSUE TITLE
Running exe using Ultralytics YOLOv8 packaged with pyinstaller causing WMIC popup command prompts on Windows

### ISSUE THREAD

**Issue by mbrandon85** [ultralytics/ultralytics#15468]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

We have an application that uses YOLOv8 to detect people from a webcam source. We package this application into a single EXE using PyInstaller. We include the pt model and the coco.names files in the package. When we run this exe on Windows, it seems to very briefly create at least one command prompt which appears to be doing something with WMIC. The command prompt(s) stay open for less than a second each and then close. The application and model work as expected otherwise

If I remove the imports related to YOLO and package, we no longer see the command terminals popup when the application is run. Has anyone seen this? Are we not packaging something correctly?

### Environment

Ultralytics YOLOv8.1.46 🚀 Python-3.12.3 torch-2.2.2+cpu CPU (AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx)
Setup complete ✅ (4 CPUs, 13.9 GB RAM, 90.3/235.5 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.12.3
Install             git
RAM                 13.95 GB
CPU                 AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx
CUDA                None

matplotlib          ✅ 3.8.4>=3.3.0   
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1 
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.13.0>=1.4.1 
torch               ✅ 2.2.2>=1.8.0
torchvision         ✅ 0.17.2>=0.9.0 
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0

### Minimal Reproducible Example

Typical usage of yolo prediction in a python script, but packaged as an exe with pyinstaller

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
PyInstaller itself is a hacky workaround to packaging Python programs as `exe` when it's not intended to work like that. It shouldn't be surprising to see strange bugs like these.

If you want to create proper `exe`, you should consider using C++.

**Comment by mbrandon85** [comment]
Thanks for commenting @Y-T-G . I'm not sure I completely agree with your answer. PyInstaller has over 3 million downloads per month. A ton of people are using it to package up their python applications into executables. I don't think we can simply write it off as a hacky way to package a python application and therefore ignore any questions that involve it.

**Comment by Y-T-G** [comment]
There's a reason you can find dozens of strange and different issues when you search for "PyInstaller" issues in here.

What makes PyInstaller a hack is that it tries to do with Python what it's not supposed to do, with various hacks:
https://github.com/search?q=repo%3Apyinstaller%2Fpyinstaller%20hack&type=code

If `exe` weren't hacky, it would have been officially supported by Python. But Python is an interpreted language, not compiled language. It's not meant to be turned into `exe`.

Also it's not a genuine ultralytics issue since you're facing a bug trying to do something that's neither officially supported nor recommended. You should open an issue on the PyInstaller GitHub.

If you want self-contained inference examples that can be compiled to exe, you can check the examples section:
https://github.com/ultralytics/ultralytics/tree/main/examples

**Comment by Y-T-G** [comment]
There's a reason you can find dozens of strange and different issues when you search for "PyInstaller" issues in here.

What makes PyInstaller a hack is that it tries to do with Python what it's not supposed to do, with various hacks:
https://github.com/search?q=repo%3Apyinstaller%2Fpyinstaller%20hack&type=code

If `exe` weren't hacky, it would have been officially supported by Python. But Python is an interpreted language, not compiled language. It's not meant to be turned into `exe`.

Also it's not a genuine ultralytics issue since you're facing a bug trying to do something that's not officially supported. You should open an issue on the PyInstaller GitHub.

If you want self-contained inference examples that can be compiled to exe, you can check the examples section:
https://github.com/ultralytics/ultralytics/tree/main/examples

**Comment by hendralin** [comment]
same thing like this, wmic.exe window opened and then close, and my exe now have two instances, need to be end-task for working normaly
