### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by flytomato2020** [ultralytics/ultralytics#1557]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x0000021D74B69798>
Traceback (most recent call last):
  File "D:\Program\Anaconda3\envs\torch18\lib\site-packages\torch\utils\data\dataloader.py", line 1324, in __del__
  File "D:\Program\Anaconda3\envs\torch18\lib\site-packages\torch\utils\data\dataloader.py", line 1258, in _shutdown_workers
AttributeError: 'NoneType' object has no attribute 'python_exit_status'

### Environment

GTX 1660 Ti
windows 11
python 3.7.11
matplotlib==3.4.3
numpy==1.21.2
onnxruntime_gpu==1.10.0
opencv_python==3.4.4.19
pandas==1.3.4
psutil==5.9.0
requests==2.28.1
scipy==1.7.1
seaborn==0.11.2
setuptools==58.0.4
tensorflow==2.7.0
thop==0.1.1.post2207130030
torch==1.8.1+cu102
torchvision==0.9.1+cu102
tqdm==4.64.1
### Minimal Reproducible Example

from ultralytics import YOLO
import sys
if __name__ == '__main__':
    # Load a model
    model = YOLO('yolov8n.yaml').load('D:\Project\yolov8-main\yolov8n.pt')  # build from YAML and transfer weights
    # Train the model
    model.train(data='coco128.yaml', epochs=10, imgsz=640)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@flytomato2020 It would be very helpful if you could provide a **Minimal Reproducible Example** i.e the command you were using and the package version.

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃
