### ISSUE TITLE
Yolo model for edge devices

### ISSUE THREAD

**Issue by sajedulalamSajid** [ultralytics/ultralytics#15727]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm currently working on a project where I'll need to use edge devices to handle inference from a single camera. Specifically, I need the device to run two inferences simultaneously. The edge devices I'm planning to use are the Raspberry Pi 3B+ and Orange Pi Zero 2. To be more specific for 1 inference it will detect and recognize some object. And for the second inference it will make binary classification. 

Given the hardware limitations, can anyone recommend tiny YOLO models that are lightweight enough to run efficiently on these devices? I'd appreciate any suggestions or insights on models that have worked well for you in similar scenarios.

**Comment by glenn-jocher** [comment]
@sajedulalamSajid for edge devices like the Raspberry Pi 3B+ and Orange Pi Zero 2, I recommend using YOLOv8n (nano) models due to their lightweight nature and efficiency. These models are optimized for performance on resource-constrained hardware. Additionally, consider exporting the models to NCNN format for better inference performance on ARM architectures. For more details, please refer to our [Raspberry Pi guide](https://docs.ultralytics.com/guides/raspberry-pi/).

**Comment by sajedulalamSajid** [comment]
Thanks a lot for actively responding, it was helpful. ☺

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions or need further assistance, feel free to ask.
