### ISSUE TITLE
Why use official pre-training weights to reason cocoval map only 44.5 instead of 44.9.

### ISSUE THREAD

**Issue by tangruinenu** [ultralytics/ultralytics#1576]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Why use official pre-training weights to reason cocoval map only 44.5 instead of 44.9.

### Additional

<img width="1079" alt="截屏2023-03-23 下午12 42 50" src="https://user-images.githubusercontent.com/100890412/227105240-56abc2c4-039c-46bd-b796-bb6bdc590acc.png">

**Comment by tangruinenu** [comment]
> 

Thanks, so how do I validate using pycocotools in yolov8.

**Comment by tangruinenu** [comment]
> @tangruinenu official results are from pycocotools: https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb
> 
> <img alt="Screenshot 2023-03-23 at 13 11 15" width="1123" src="https://user-images.githubusercontent.com/26833433/227199989-4b275d99-884e-4505-a210-07daea0d492d.png">

pred_json = '/home/rui.tang/runs/detect/val/predictions.json'
anno_json = '/home/rui.tang/datasets/coco/annotations/instances_val2017.json'

cocoGt = COCO(anno_json)
cocoDt = cocoGt.loadRes(pred_json)
cocoEval = COCOeval(cocoGt, cocoDt, 'bbox')

cocoEval.evaluate()
cocoEval.accumulate()
cocoEval.summarize()

print(cocoEval.stats)

I seem to have found a way to evaluate it, but the output is wrong.

**Comment by glenn-jocher** [comment]
@tangruinenu evaluation will use pycocotools automatically if `data=coco.yaml`

**Comment by tangruinenu** [comment]
> @tangruinenu evaluation will use pycocotools automatically if `data=coco.yaml`

I validate with data==coco.yaml. YOLOv8 does not automatically call pycocotools for validation

**Comment by tangruinenu** [comment]
> @tangruinenu evaluation will use pycocotools automatically if `data=coco.yaml`
 yolo val detect data='ultralytics/datasets/coco.yaml' device=0 model=yolov8x.pt
Does yolov8 automatically use pycocotools? Why didn't I use PyCocoTools during validation
<img width="809" alt="截屏2023-03-24 下午6 07 34" src="https://user-images.githubusercontent.com/100890412/227492327-7124ad1f-93a5-430a-b2af-1b26eef293fa.png">

**Comment by glenn-jocher** [comment]
@tangruinenu this works correctly for me in Colab as in the example I showed you, so I'm unable to reproduce any problems running pycocotools automatically.

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃
