### ISSUE TITLE
CometML logger is using random experiment name

### ISSUE THREAD

**Issue by santapo** [ultralytics/ultralytics#1596]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Current CometML callback only uses `project` variable but not`name` to set a specific name for each experiment. This makes CometML assigning a random and meaningless experiment name

<img width="622" alt="image" src="https://user-images.githubusercontent.com/54897327/227471192-384931b2-303f-4f75-bec9-c514e4f0f4bd.png">

### Additional

Adding `experiment.set_name(name=trainer.args.name)` to `comet.py` can solve this issue!
![image](https://user-images.githubusercontent.com/54897327/227472386-71c989ce-2811-4f00-ad34-950793fa590f.png)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@santapo oh good solution! Can you submit a PR with this fix please? Thank you!

**Comment by glenn-jocher** [comment]
@santapo fixed in #1602 :)

**Comment by rfonod** [comment]
It seems that this issue is present again.

**Comment by glenn-jocher** [comment]
@rfonod hello! Thank you for bringing this to our attention. Could you please provide more information or context about the issue you are experiencing? What error messages or symptoms are you encountering? This will help us better understand the problem so we can work towards a solution. Thank you!

**Comment by rfonod** [comment]
@glenn-jocher, thank you for the reply. The context of the issue is exactly the same as described above by @santapo, i.e., CometML assigns a random name despite having the name of the experiment specified with the YOLO argument `name`.

It seems that the above-proposed fix to `ultralytics/yolo/utils/callbacks/comet.py` has been changed/lost.

**Comment by glenn-jocher** [comment]
@rfonod Thank you for letting us know about this issue. We apologize for the inconvenience you are experiencing and for any confusion caused by the missing fix. We will investigate this further and work on a solution to ensure that the experiment names specified with the YOLO argument `name` are correctly assigned to the CometML experiments. Once we have a fix, we will inform you and update the repo accordingly. Thank you for your patience and understanding.
