### ISSUE TITLE
Yolo Pose - Hardcoded human body keypoints

### ISSUE THREAD

**Issue by PallottaEnrico** [ultralytics/ultralytics#1598]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Validation, Detection

### Bug
@glenn-jocher 
I'm facing problems during the evaluation and inference steps.

First of all, in the case of inference the error is caused by the fact that in [autobackend](https://github.com/ultralytics/ultralytics/blob/pose/ultralytics/nn/autobackend.py) line 95 and 108 there's the kpt_shape hardcoded to (17,3), it should be instead read from the custom_data.yaml.

During evaluation instead it raises the following error:
![image](https://user-images.githubusercontent.com/57596722/227486056-1be7508e-63bc-49c6-9aaf-9a21d7df0bba.png)
I'm trying to detect objects with 4 keypoints, i've correctly followed the dataset format and set the yolo8-pose.yaml and custom_data.yaml accordingly (kpt_shape = [4,3] and nc=1).
Indeed, fixing the error described before, the inference works but the metric calculation during training still fails.
I managed to train my model only by disabling evaluation.

I think that this problem could be probably related to some other code that still doesn't generalize on object with an arbitrary number of keypoints.

### Environment

- Python 3.8.10
- Torch 1.13.1+cu117
- Ultralytics : latest commit on pose branch.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Laughing-q @AyushExel see above for hardcoded kpt_shape in AutoBackend. We also need a solution for exported format NMS with Pose which I need to work on.

**Comment by Laughing-q** [comment]
@glenn-jocher @PallottaEnrico 
[https://github.com/ultralytics/ultralytics/blob/5a365afb5c36dae4c49621e0ba23f3e0df0fe9f8/ultralytics/nn/autobackend.py#L108](https://github.com/ultralytics/ultralytics/blob/5a365afb5c36dae4c49621e0ba23f3e0df0fe9f8/ultralytics/nn/autobackend.py#L108)
this is for the backward compatibility for our old version pose model which do not include `kpt_shape`, but since now the models we trained have this attribute `kpt_shape`, probably we can just remove `(17, 3)`.

But logically this part should not affect anything since we assigned `kpt_shape` to `model` while launching training, so the code should not to the `(17, 3)`.
[https://github.com/ultralytics/ultralytics/blob/5a365afb5c36dae4c49621e0ba23f3e0df0fe9f8/ultralytics/yolo/v8/pose/train.py#L38](https://github.com/ultralytics/ultralytics/blob/5a365afb5c36dae4c49621e0ba23f3e0df0fe9f8/ultralytics/yolo/v8/pose/train.py#L38)

**Comment by Laughing-q** [comment]
@glenn-jocher @PallottaEnrico the evaluation issue fixed in [https://github.com/ultralytics/ultralytics/pull/1347/commits/a0b57c70c644163cd4de468c9e362d67143da36d](https://github.com/ultralytics/ultralytics/pull/1347/commits/a0b57c70c644163cd4de468c9e362d67143da36d)

**Comment by glenn-jocher** [comment]
> @glenn-jocher @PallottaEnrico the evaluation issue fixed in [a0b57c7](https://github.com/ultralytics/ultralytics/commit/a0b57c70c644163cd4de468c9e362d67143da36d)

Ohhhh, got it. Good work on the fix. I took a look at the autobackend code and just assumed that the models were missing the ktp_shape attribute.
