### ISSUE TITLE
CUDA tutorial

### ISSUE THREAD

**Issue by noooob-ody** [ultralytics/ultralytics#16119]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

i hope that the corresponding cuda version installtion can be added in README, this could be important for beginners. Also the issue that the project is too complex, its hard for beginners to find where the yolo model actually is 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Skillnoob** [comment]
The [quickstart guide](https://docs.ultralytics.com/quickstart/) already contains instructions on how to properly install the CUDA version of PyTorch.
I am unsure by what you mean with "where the yolo model actually is" because the models get automatically downloaded and are simply stored where you execute the script.
