### ISSUE TITLE
Set model parameters occurs no change

### ISSUE THREAD

**Issue by pedefe** [ultralytics/ultralytics#16307]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,
I call the tracking as following:
`results = _model.track(frame, persist=True, classes = [0,1,2,3,5,7], show_labels = False, show_conf = False, show_boxes = False)`
and this doesn't change result : not selected class is found (like 'train'), and unwanted information (label, boxes, confidence) is displayed.
Why ?
(I have done the same at init : 
```
_model = YOLO(modelName,task="detect",verbose=verbose)	
_model.classes = [0,1,2,3,5,7]
_model.show_labels = False
_model.show_conf = False
_model.show_boxes = False
```
and nothing changes.

best regards.

**Comment by UltralyticsAssistant** [comment]
👋 Hello @pedefe, thank you for your interest in Ultralytics 🚀!

We recommend checking out our [Docs](https://docs.ultralytics.com) for guidance on usage examples and solutions to common issues.

If this is a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us investigate the issue more effectively.

Since this involves custom tracking parameters, kindly ensure that your environment is set up as recommended. You can try upgrading to the latest `ultralytics` package in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/):

```bash
pip install -U ultralytics
```

Join our active community for more support. Engage in real-time conversations on [Discord](https://ultralytics.com/discord) 🎧, explore in-depth discussions on [Discourse](https://community.ultralytics.com), or check out our [Subreddit](https://reddit.com/r/ultralytics).

Stay tuned, as an Ultralytics engineer will assist you soon. 😊

## Environments

Consider running YOLOv8 in any of these supported environments:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud**: Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon**: Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**: See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing, verifying correct operation across platforms.

**Comment by Y-T-G** [comment]
Does it not change when you restart it? Or it doesn't change after you make the first inference and then try to change the arguments?

You can try running `model.predictor = None` before changing arguments after the first inference.

**Comment by pedefe** [comment]
My code is very simple : 
```
_model = YOLO('yolov8n.pt',task="detect",verbose=verbose)	
_model.classes = [0,1,2,3,5,7]
_model.show_labels = False
_model.show_conf = False
_model.show_boxes = False
...
success, frame = _cap.read()
results = _model.track(frame, persist=True)
```

Best regards

**Comment by Y-T-G** [comment]
Remove these:

```python
_model.classes = [0,1,2,3,5,7]
_model.show_labels = False
_model.show_conf = False
_model.show_boxes = False
```

You only pass them as arguments to prediction.

And how are you viewing the image? Because the arguments will affect the overlay of the image displayed when you use `show=True` or `save=True`.

If you're using `result.plot()` then you need to pass `labels=False, boxes=False, conf=False` to the `plot()` method.

Check the [arguments for plot](https://docs.ultralytics.com/modes/predict/#plot-method-parameters).

**Comment by pedefe** [comment]
Ok, thanks, it seems working for label, conf and boxes.
I am waiting for sub sample of classes...
Best regards.

**Comment by Y-T-G** [comment]
Selecting classes should work with the `classes` argument. Check whether you selected the correct classes.
