### ISSUE TITLE
[BUG] ultralytics[explorer] install fails on Python 3.12

### ISSUE THREAD

**Issue by BeanBagKing** [ultralytics/ultralytics#16331]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

During installation, requirements attempts to install duckdb <= 0.9.2
```
Collecting duckdb<=0.9.2 (from ultralytics[explorer])
  Downloading duckdb-0.9.2.tar.gz (10.7 MB)
```

Per https://github.com/duckdb/duckdb/issues/9301 - it looks like support for Python 3.12 wasn't added until sometime in 0.9.3. I see mentions of dev versions of 0.9.3 supporting it, but no 0.9.3 release. The next step up is 0.10.0.

In any case, the install fails during wheel build for duckdb. So I'm kind of assuming this is the issue, but it's beyond my skills and time to dive into.

```
Building wheels for collected packages: duckdb
  Building wheel for duckdb (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
```
[SNIP] pages of crash info
```
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for duckdb
  Running setup.py clean for duckdb
Failed to build duckdb
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (duckdb)
```

For anyone looking for a workaround, you can create a constraints.txt file and add the line `duckdb>=0.10.0` to it. Then attempt an install with `pip install -c .\constraints.txt ultralytics[explorer]`. Pip should find an old version without the duckdb requirement. You'll also have to manually run `pip install streamlit-select>=0.3` and `pip install fiftyone` for some of the features

### Environment

Ultralytics YOLOv8.1.12 🚀 Python-3.12.6 torch-2.4.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4090, 24563MiB)
Setup complete ✅ (16 CPUs, 63.9 GB RAM, 781.5/930.7 GB disk)

OS                  Windows-11-10.0.22631-SP0
Environment         Windows
Python              3.12.6
Install             pip
RAM                 63.91 GB
CPU                 Intel Core(TM) i9-9900K 3.60GHz
CUDA                12.1

matplotlib          ✅ 3.9.0>=3.3.0
numpy               ✅ 1.26.4>=1.22.2
opencv-python       ✅ 4.10.0.82>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.4.1+cu121>=1.8.0
torchvision         ✅ 0.19.1+cu121>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0

### Minimal Reproducible Example

An environment setup per the above should be enough to reproduce. I'm using a venv Python environment and PowerShell 7 as my shell, but I think the main thing that matters is Python 3.12.x, then try a `pip install ultralytics[explorer]`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @BeanBagKing, thank you for reporting this issue and for your interest in Ultralytics 🚀! 

We understand you're experiencing a problem with installing `ultralytics[explorer]` on Python 3.12 due to dependencies with `duckdb`. Your detailed report is greatly appreciated.

🔍 As this sounds like a 🐛 Bug Report, please ensure that you've included a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to assist us further in debugging.

Here's how you can update your setup to ensure you're using the latest compatible versions:
1. Upgrade the `ultralytics` package, which may resolve some compatibility issues:

```bash
pip install -U ultralytics
```

2. Consider your workaround with constraints for `duckdb`, and for any direct dependency issues, refer to our [CLI usage examples](https://docs.ultralytics.com/usage/cli/).

Join the Ultralytics community where it suits you best. For real-time chat, head to [Discord](https://ultralytics.com/discord) 🎧. Prefer in-depth discussions? Check out [Discourse](https://community.ultralytics.com). Or dive into threads on our [Subreddit](https://reddit.com/r/ultralytics) to share knowledge with the community.

## Environments

YOLOv8 is compatible with various environments which might provide a smoother setup experience:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a>, <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>, <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Our engineering team will look into this and assist you soon. Thank you for your patience and for helping us improve Ultralytics! 😊

**Comment by glenn-jocher** [comment]
@BeanBagKing thank you for reporting this issue. It seems the problem is related to the `duckdb` package's compatibility with Python 3.12. As a workaround, using a `constraints.txt` file to specify `duckdb>=0.10.0` is a good approach. We recommend following this method until an official fix is available. If you have further questions, feel free to ask in the GitHub Issues section.
