### ISSUE TITLE
Pose and rect training

### ISSUE THREAD

**Issue by enhany** [ultralytics/ultralytics#1637]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Looks like rect option doesn't work with pose training. Is it expected? Do you plan to create rect training for pose?

**Comment by glenn-jocher** [comment]
@enhany 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by enhany** [comment]
1. clone branch "pose" from yolov8 repository
2. create dataset with 384x320 resolution (all files the same resolution)
3. create and run file train.py
```
from ultralytics import YOLO

if __name__ == '__main__':
	model = YOLO("yolov8n-pose.yaml")
	model.train(data="auto.yaml", epochs=200, batch=32, imgsz=384, single_cls=True, rect=True)
```
4. check "train_batch0.jpg" in runs/pose/train folder

you can see: all pictures are 384*384 resolution
expected: pictures have to be 384*320 (like yolov8 detection with rect=True)
