### ISSUE TITLE
I want to get embeddings of each detected object

### ISSUE THREAD

**Issue by trongldwork** [ultralytics/ultralytics#16385]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a yolov8 model which use for detect one class, but i want to extract embedding of each object, I want if model detected 100 bbox, it will return 100 embedding, too. And after NMS, some bbox is removed, so i want to keep the embedding of the bbox what have kept by NMS. Can you help me pls

**Comment by UltralyticsAssistant** [comment]
👋 Hello @trongldwork! Thank you for reaching out and your interest in Ultralytics 🚀. 

For embedding extraction, we recommend checking the [Docs](https://docs.ultralytics.com) where you may find relevant insights and ensure you’re following best practices. 

Since this is a ❓ Question regarding custom processing, please provide more details about your specific implementation. Any extra context, such as code snippets or logs, can help us understand your use case better. 

If you're reporting a 🐛 Bug, please share a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us investigate the issue.

Feel free to join the Ultralytics community on [Discord](https://ultralytics.com/discord) 🎧 for real-time interactions, or check out [Discourse](https://community.ultralytics.com) for more detailed discussions.

To ensure you’re using the latest features and bug fixes, upgrade to the newest version of the `ultralytics` package:

```bash
pip install -U ultralytics
```

Rest assured, an Ultralytics engineer will assist you soon! 

Happy coding! 😊

**Comment by Y-T-G** [comment]
I have a [Colab notebook](https://colab.research.google.com/drive/1DrBqSBuwpRvauYaEvJ1_8PyR4lW5WJCF?usp=sharing) on this.
