### ISSUE TITLE
yolov8n-p2 is not as effective as yolov8n

### ISSUE THREAD

**Issue by HornGate** [ultralytics/ultralytics#1641]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have trained the **yolov8n** and **yolov8n-p2** on DOTA v1.0 with batchsize 6 on RTX 3070 GPU, and other training hyper-parameter is also same. There are many small targets in the DOTA v1.0 dataset, and it is reasonable to say that  yolov8n-p2 is better than yolov8n，but the mAP of  yolov8n-p2 is 2.5% lower than that of yolov8n. Why is this？

**Comment by glenn-jocher** [comment]
It is possible that the yolov8n model is better suited for the DOTA v1.0 dataset than the yolov8n-p2 model, despite the expectation that yolov8n-p2 would perform better on smaller targets due to its use of PANet. This could be due to various factors, such as the complexity of the dataset or the specifics of the training process.

It is also possible that there is an issue with the training process for the yolov8n-p2 model, such as suboptimal hyperparameters or an insufficient number of training epochs. It may be helpful to review the training logs and compare the training performance of the two models to identify any potential issues.

In any case, it would be helpful to provide more details about the training process and the specific metrics used to evaluate the models in order to better understand the issue and provide a more informed answer.

**Comment by HornGate** [comment]
> It is possible that the yolov8n model is better suited for the DOTA v1.0 dataset than the yolov8n-p2 model, despite the expectation that yolov8n-p2 would perform better on smaller targets due to its use of PANet. This could be due to various factors, such as the complexity of the dataset or the specifics of the training process.
> 
> It is also possible that there is an issue with the training process for the yolov8n-p2 model, such as suboptimal hyperparameters or an insufficient number of training epochs. It may be helpful to review the training logs and compare the training performance of the two models to identify any potential issues.
> 
> In any case, it would be helpful to provide more details about the training process and the specific metrics used to evaluate the models in order to better understand the issue and provide a more informed answer.

OK. Thank you for your answer.

**Comment by ExtReMLapin** [comment]
I currently don't have the required horsepower to train on p2 with a decent batchsize (> 1), i'll run some experimentation on yolov5 and compare them to the runs on yolov8 as soon as I can

**Comment by ExtReMLapin** [comment]
Sure the training is not finished but I can see something similar to YoloV5 here,
I'm using both `scale=0.95` and `RandomResizedCrop(2048,2048, scale=(0.16,1.0), ration(0.75,1.33333),p=0.5)` and `mixup=0.5`

Same dataset, same augmentations, 

# YoloV8

![image](https://user-images.githubusercontent.com/3909752/228188483-2c84f4df-328c-4e4b-9f62-eabfe1a1952a.png)


# YoloV5

![image](https://user-images.githubusercontent.com/3909752/228189375-c9598ff1-8306-4cc3-b9ee-a2161211fa02.png)



While it is surprising to get "worse" results with another layer that supports smaller features, I have to admit, I don't see anything much different from yolov5

Both yolov8 and v5 were on same size settings (medium).

While I'm clearly not an expert on the field, adding a P2 layer with those augmentations reduces `train/obj_loss` by a lot

**Comment by glenn-jocher** [comment]
We haven't trained YOLOv8 P2 models, so I'm not sure what an expected performance would be on a benchmark dataset, but in general they should improve small object mAP.
