### ISSUE TITLE
GPU Usage keeps fluctuating during inference

### ISSUE THREAD

**Issue by AbhishekHollaAB** [ultralytics/ultralytics#16497]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I had trained a YOLOv8 segmentaion model and had obtained the weight. Bow during inference on unseen dataset on a large number of images, the GPU memory usage keeps fluctuating. It ranges from around 1.5GB to around 12-13GB. Is there any reason as to why that is happening? It keeps varying image to image.

**Comment by UltralyticsAssistant** [comment]
👋 Hello @AbhishekHollaAB, thank you for reaching out to us about your GPU usage concerns during inference 🚀!

We suggest exploring our [Docs](https://docs.ultralytics.com) for potential insights. You might find our [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples particularly useful for understanding how to handle large dataset inferences efficiently.

Since this seems like a potential 🐛 Bug Report, could you please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better diagnose the issue?

While you await further assistance from an Ultralytics engineer, consider joining our vibrant community:
- For real-time discussions, hop onto our [Discord](https://ultralytics.com/discord) 🎧.
- Prefer detailed threads? Our [Discourse](https://community.ultralytics.com) platform could be right for you.
- Or engage with peers on our [Subreddit](https://reddit.com/r/ultralytics)!

## Upgrade

You might want to ensure you are using the latest version of `ultralytics`:

```bash
pip install -U ultralytics
```

This can fix known issues present in previous versions.

## Environments

We recommend testing your application in one of our verified environments to eliminate environment-specific issues:

- Notebooks with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

A green badge indicates all tests are passing, verifying that your issue might be environment-specific or setup-related. 

Rest assured, an Ultralytics engineer will follow up soon to assist further. 😊

**Comment by Y-T-G** [comment]
Provide the code you're using for inference.

**Comment by AbhishekHollaAB** [comment]
> Provide the code you're using for inference.

`results = model.predict(img, save=False, stream=True, conf=0.04, iou=0.1, verbose=False, max_det=10000)`

**Comment by Y-T-G** [comment]
You are running on a single image, there's no need for `stream=True`. The GPU usage shouldn't fluctuate a lot unless you're doing something in postprocessing where the `results` are used without moving it to CPU first.

**Comment by AbhishekHollaAB** [comment]
> You are running on a single image, there's no need for `stream=True`. The GPU usage shouldn't fluctuate a lot unless you're doing something in postprocessing where the `results` are used without moving it to CPU first.

I am actually looping through the images one by one from a folder. if i dont use `stream=True`, the GPU memory keeps on increasing until it runs out of memory.

**Comment by Y-T-G** [comment]
Then you're likely storing the results or doing something similar without moving it to the CPU.

You can run `result.cpu()` to move the result from the GPU memory to the system memory.

Also, ultralytics supports passing a folder path directly in `model.predict`. If you use that with `stream=True` and specify a `batch` size, it will perform inference in batches which will be faster.

https://docs.ultralytics.com/modes/predict/#inference-arguments

**Comment by AbhishekHollaAB** [comment]
Okay thanks. I'll look into it then. :)

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions, feel free to ask.
