### ISSUE TITLE
CoreML export failure: CoreML: export failure ❌ 12.0s: 1 names found for nc=8395

### ISSUE THREAD

**Issue by dhiman10** [ultralytics/ultralytics#1652]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Whenever I want to export Yolov8s best.pt file to the coreML format with nms=True, I am getting this error, How can I solve this, could anyone give me a solution? 
_**!yolo mode=export model=runs/detect/train/weights/best.pt format=coreml nms=True**_

PyTorch: starting from runs/detect/train/weights/best.pt with output shape (1, 5, 8400) (21.5 MB)
scikit-learn version 1.2.2 is not supported. Minimum required version: 0.17. Maximum required version: 1.1.2. Disabling scikit-learn conversion API.
XGBoost version 1.7.4 has not been tested with coremltools. You may run into unexpected errors. XGBoost 1.4.2 is the most recent version that has been tested.
2023-03-27 10:21:09.387840: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-27 10:21:10.553826: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.9/dist-packages/cv2/../../lib64:/usr/local/lib/python3.9/dist-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-03-27 10:21:10.553952: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.9/dist-packages/cv2/../../lib64:/usr/local/lib/python3.9/dist-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-03-27 10:21:10.553975: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
TensorFlow version 2.11.0 has not been tested with coremltools. You may run into unexpected errors. TensorFlow 2.10.0 is the most recent version that has been tested.

CoreML: starting export with coremltools 6.2...
Tuple detected at graph output. This will be flattened in the converted model.
Converting PyTorch Frontend ==> MIL Ops: 100% 524/526 [00:00<00:00, 2317.40 ops/s]
Running MIL Common passes: 100% 40/40 [00:00<00:00, 137.80 passes/s]
Running MIL Clean up passes: 100% 11/11 [00:00<00:00, 75.93 passes/s]
Translating MIL ==> NeuralNetwork Ops:  86% 552/639 [00:01<00:00, 353.96 ops/s]Const anchor_points was already added.
Translating MIL ==> NeuralNetwork Ops: 100% 639/639 [00:01<00:00, 434.87 ops/s]
CoreML Pipeline: starting pipeline with coremltools 6.2...

**### **CoreML: export failure ❌ 12.0s: 1 names found for nc=8395****

### Additional

I am using yolov8s.pt
!yolo task=detect mode=train model=yolov8s.pt data= data.yaml epochs=25 imgsz=640 plots=True

**Comment by glenn-jocher** [comment]
@dhiman10 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. I've trained a model and exported to CoreML with nms=True and everything works correctly. I am unable to reproduce any problems with this workflow.

<img width="1263" alt="Screenshot 2023-03-27 at 13 56 09" src="https://user-images.githubusercontent.com/26833433/227934799-98c7ee46-be1a-453b-980e-aa4d473eebd9.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by glenn-jocher** [comment]
@dhiman10 your model or your ultralytics package, or both are out of date. Update both and everything will work correctly.

**Comment by dhiman10** [comment]
Thanks, Now it's working.

**Comment by pderrenger** [comment]
@dhiman10 you're welcome! I'm glad to hear that it's working now. If you have any more questions or need further assistance, feel free to ask. Good luck with your project! 👍

**Comment by glenn-jocher** [comment]
@pderrenger Great to hear it's working! If you need help in the future, just reach out. Happy coding! 🚀
