### ISSUE TITLE
Yolov8 Tracking running only for small videos 

### ISSUE THREAD

**Issue by sivaji123256** [ultralytics/ultralytics#1667]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi @glenn-jocher and @Laughing-q ,
I was trying to run the inference of tracking (bytetrack) using our custom trained weights.I was able to run successfully. But ,it was not running for more than 1000 frames due to the memory issues.(Cuda out of memory).While I was running inference using yolov5 and bytetrack , it was running successfully for the whole video without memory issues.I was using A10 machine in AWS. Any suggestion would help me to run the inference on the whole videos.
Thanks in advance.

**Comment by AyushExel** [comment]
Have you tried using `stream=True` ?
```
results = model.track(source="https://youtu.be/Zgi9g1ksQHc", stream=True) 
```

**Comment by Laughing-q** [comment]
@sivaji123256 hi, we don't support that for now. But I think it can be done once you get the ids and boxes and frame. i,e:
```python
results = model.track(source=0, stream=True)
for result in results:
    boxes = result.boxes
    frame = result.orig_img
    for box in boxes:
        id = box.id
        xyxy = box.xyxy
```

**Comment by akashAD98** [comment]
@Laughing-q i want to pass frames one by one , instead of directly passing all video to source='vid.mp4',
i want to implement multithreading or queue mechanisms so how can i pass frames to the tracker?

**Comment by glenn-jocher** [comment]
@akashAD98 to pass frames one by one to the tracker instead of directly passing the entire video, you can use OpenCV for video reading, and then use a queue to store the frames that you want to track. This will allow you to implement a multithreading mechanism to process the frames concurrently. Here's how you can do it:

1. Create a queue to store the frames:

```
frame_queue = Queue()
```

2. Use OpenCV to read the video frames and put them in the queue:

```
cap = cv2.VideoCapture('vid.mp4')
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    frame_queue.put(frame)
```

3. Create a separate thread for the tracking process:

```
def tracking_thread():
    # Create the tracker object
    tracker = Tracker()

    while True:
        # Get the next frame from the queue
        frame = frame_queue.get()

        # Track the objects in the frame
        output = tracker.track(frame)

        # Do something with the output (e.g. display it)
        cv2.imshow('output', output)

        # Check for the 'q' key to exit
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    # Release the video capture and destroy the windows
    cap.release()
    cv2.destroyAllWindows()

# Start the tracking thread
thread = Thread(target=tracking_thread)
thread.start

**Comment by akashAD98** [comment]
@glenn-jocher ill try this, thanks a lot for a quick reply.

**Comment by glenn-jocher** [comment]
@akashAD98 you're welcome! I'm happy to help. If you have any further questions or run into any issues, don't hesitate to ask.

**Comment by akashAD98** [comment]
here is a script let me know if something im missing also ,
i want to load BOT, Byte tracker directly, how can i do it here

```
import cv2
from queue import Queue
from threading import Thread
from sort import Sort
from ultralytics import YOLO

model = YOLO("yolov8n.pt")

# create queue to store frames
frame_queue = Queue()

# use OpenCV to read the video frames and put them in the queue
cap = cv2.VideoCapture('vid.mp4')
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    frame_queue.put(frame)

# create a separate thread for the tracking process
def tracking_thread():
    # create the tracker object
    tracker = Sort()

    while True:
        # get the next frame from the queue
        frame = frame_queue.get()

        # track the objects in the frame
        output = model.track(frame)

        # do something with the output (e.g. display it)
        cv2.imshow('output', output)

        # check for the 'q' key to exit
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    # release the video capture and destroy the windows
    cap.release()
    cv2.destroyAllWindows()

# start the tracking thread
thread = Thread(target=tracking_thread)
thread.start()

```

**Comment by glenn-jocher** [comment]
@akashAD98 the script you provided looks good for the most part. However, I do see that you have imported Sort, which is a separate tracking algorithm, but it is not being used in the code you provided. If you want to use Sort for tracking instead of YOLO's default tracking, you will need to modify the tracking_thread() function accordingly.

As for loading BOT and Byte tracker directly, I'm not sure what you mean by that. Could you please clarify your question? Are you referring to loading pre-trained BOT and Byte tracker models? If so, you can load them using their respective model files with PyTorch.

**Comment by glenn-jocher** [comment]
@akashAD98 the idea is to combine the Python tracker usage in https://docs.ultralytics.com/modes/track/ with stream=True mode, so you can loop through the frames in your video one image at a time, and process the tracks however you'd like using i.e.

```python
for results in model('video.mp4'):
    # process results
```

**Comment by akashAD98** [comment]
@glenn-jocher thanks ,but i want to use cv2 & queue mechanisms


```
    while True:
        # get the next frame from the queue
        frame = frame_queue.get()

        # track the objects in the frame
        output = model.track(frame)

        # do something with the output (e.g. display it)
        cv2.imshow('output', output)

```

here mode.track(frames) its using defult tracker riht? how cani change that tracker

**Comment by glenn-jocher** [comment]
@akashAD98 you can update or change the tracker with the `tracker_cfg` argument, i.e. model.track(tracker_cfg=...)

**Comment by glenn-jocher** [comment]
@akashAD98 @akashAD98 to use a custom tracker with YOLOv5 `model.track()` method, you can create a YOLOv5 `Custom` class instance and pass this as the `tracker` argument to the `model.track()` method. 

Here's an example code snippet based on your previous script:

```python
import cv2
from queue import Queue
from threading import Thread
from ultralytics import YOLOv5, Custom

model = YOLOv5("yolov5s.pt")

# create custom tracker
tracker = Custom()

# create queue to store frames
frame_queue = Queue()

# use OpenCV to read the video frames and put them in the queue
cap = cv2.VideoCapture('vid.mp4')
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    frame_queue.put(frame)

# create a separate thread for the tracking process
def tracking_thread():
    while True:
        # get the next frame from the queue
        frame = frame_queue.get()

        # track the objects in the frame
        output = model.track(frame, tracker=tracker)

        # do something with the output (e.g. display it)
        cv2.imshow('output', output)

        # check for the 'q' key to exit
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    # release the video capture and

**Comment by akashAD98** [comment]
im using windows system, but im not able to run code due to anaconda error,so i tested it on google collab & im getting the outputs,but im not sure my code is correct or not bcz .cv2.imshow() also not working in collab & im also not able to save video, can you tell me if my code is correct or not?

```
import cv2
from queue import Queue
from threading import Thread
#from sort import Sort
from ultralytics import YOLO

model = YOLO("yolov8n.pt")

# create queue to store frames
frame_queue = Queue()

# use OpenCV to read the video frames and put them in the queue
cap = cv2.VideoCapture('/content/video1.mp4')
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = int(cap.get(cv2.CAP_PROP_FPS))
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter('output.mp4', fourcc, fps, (width, height))

# create a separate thread for the tracking process
def tracking_thread():

    while True:
        # get the next frame from the queue
        frame = frame_queue.get()

        # track the objects in the frame
        results = model.track(frame)

        # loop through the results and draw bounding boxes on the frame
        for result in results:
            boxes = result.boxes
            for box in boxes:
                id = box.id
                xyxy = box.xyxy
                #frame = cv2.rectangle(frame, (xyxy[0], xyxy[1]), (xyxy[2], xyxy[3]), (0, 255, 0), 2)

        # write the output frame to the video file
        out.write(frame)

        # display the output frame
        cv2.imshow('output', frame)

        # check for the 'q' key to exit
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    # release the video capture and writer objects and destroy the windows
    cap.release()
    out.release()
    cv2.destroyAllWindows()

# start the tracking thread
thread = Thread(target=tracking_thread)
thread.start()

```

output im getting
```

id tensor([1.])
xyxy tensor([[ 351.8416,   64.7766, 1402.0682, 1039.1436]])
id tensor([2.])
xyxy tensor([[1383.6855,  606.5858, 1804.6689,  991.6968]])
id tensor([3.])
xyxy tensor([[1781.8187,  308.4764, 1919.1127,  743.8647]])
id tensor([4.])
xyxy tensor([[1738.7434,  940.7314, 1918.9817, 1058.2533]])

```

**Comment by glenn-jocher** [comment]
@akashAD98 the code you provided appears to be correct. It reads frames from a video, puts them into a queue, and tracks objects in each frame using YOLOv8. The tracked boxes are then drawn on the output frame, and the final video is written to 'output.mp4'. However, as you mentioned, cv2.imshow() doesn't work in Google Colab, so you won't be able to see the video output in Colab. If you need to see the output, you will have to run the code on a local machine or modify the code to display the frames output using matplotlib or another library that works in Colab.

**Comment by akashAD98** [comment]
@glenn-jocher sorry to interrupt you again, but my code is running infinite time, in your free time you can try to run my code, otherwise anyone who want to help me in this code your most welcome

```

from queue import Queue
from threading import Thread
from ultralytics import YOLO
import cv2

model = YOLO("yolov8n.pt")
print("model loaded")
# create queue to store frames
frame_queue = Queue()

# use OpenCV to read the video frames and put them in the queue
cap = cv2.VideoCapture('/content/vidapprel.mp4')
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = int(cap.get(cv2.CAP_PROP_FPS))
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter('outputnew.mp4', fourcc, fps, (width, height))

# create a separate thread for the tracking process
def tracking_thread():
    while True:
        # get the next frame from the queue
        frame = frame_queue.get()
        if frame is None:
            # sentinel value indicating end of frames
            frame_queue.task_done()
            break

        print("started loop")

        # track the objects in the frame
        results = model.track(frame)

        # loop through the results and draw bounding boxes on the frame
        for result in results:
            boxes = result.boxes
            print("boxex",boxes)
            
            for box in boxes:
                id = box.id
                xyxy = box.xyxy
                frame = cv2.rectangle(frame, (xyxy[0], xyxy[1]), (xyxy[2], xyxy[3]), (0, 255, 0), 2)

        # write the output frame to the video file
        out.write(frame)

        # display the output frame
        #cv2.imshow('output', frame)

        # check for the 'q' key to exit
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

        frame_queue.task_done()

    # release the video capture and writer objects and destroy the windows
    cap.release()
    out.release()
    cv2.destroyAllWindows()

# start the tracking thread
thread = Thread(target=tracking_thread)
thread.start()

# loop through the video frames and put them into the queue
while True:
    ret, frame = cap.read()
    if not ret:
        break
    frame_queue.put(frame)

# add sentinel value to indicate end of frames
frame_queue.put(None)

# wait for all tasks in the queue to be completed
frame_queue.join()

# wait for the tracking thread to finish
thread.join()


```

**Comment by glenn-jocher** [comment]
@akashAD98 It looks like your code is running indefinitely because you are not breaking out of the infinite while loop in the tracking_thread() function. This means that the thread never gets to the part where it stops and releases the resources. I suggest you add a flag outside the while loop and set it to False once there are no more frames to process. This will allow the while loop to exit and give the thread a chance to stop and release the resources. Here is an example change you can make:

```python

# create a separate thread for the tracking process
def tracking_thread():
    while True:
        # get the next frame from the queue
        frame = frame_queue.get()
        if frame is None:
            # sentinel value indicating end of frames
            frame_queue.task_done()
            break

        # track the objects in the frame
        results = model.track(frame)

        # loop through the results and draw bounding boxes on the frame
        for result in results:
            boxes = result.boxes
            for box in boxes:
                id = box.id
                xyxy = box.xyxy
                frame = cv2.rectangle(frame, (xyxy[0], xyxy[1]), (xyxy[2], xyxy[3]), (0, 255, 0), 2)

        # write the output frame to the video file
        out.write(frame)

        # display the output frame
        #cv2.imshow('output',

**Comment by akashAD98** [comment]
i added but it keeps running this line
```
# wait for all tasks in the queue to be completed
frame_queue.join()

```

```
from queue import Queue
from threading import Thread
from ultralytics import YOLO
import cv2

model = YOLO("yolov8n.pt")
print("model loaded")

# create queue to store frames
frame_queue = Queue()

# use OpenCV to read the video frames and put them in the queue
cap = cv2.VideoCapture('/content/vidapprel.mp4')
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = int(cap.get(cv2.CAP_PROP_FPS))
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter('outputnew.mp4', fourcc, fps, (width, height))

# create a separate thread for the tracking process
def tracking_thread():
    while True:
        # get the next frame from the queue
        frame = frame_queue.get()
        if frame is None:
            # sentinel value indicating end of frames
            frame_queue.task_done()
            break

        print("started loop")

        # track the objects in the frame
        results = model.track(frame)

        # loop through the results and draw bounding boxes on the frame
        for result in results:
            boxes = result.boxes
            print("boxex",boxes)
            
            for box in boxes:
                id = box.id
                xyxy = box.xyxy
                frame = cv2.rectangle(frame, (xyxy[0], xyxy[1]), (xyxy[2], xyxy[3]), (0, 255, 0), 2)

        # write the output frame to the video file
        out.write(frame)

        # display the output frame
        #cv2.imshow('output', frame)

        # check for the 'q' key to exit
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

        frame_queue.task_done()

    # release the video capture and writer objects and destroy the windows
    cap.release()
    out.release()
    cv2.destroyAllWindows()

# start the tracking thread
thread = Thread(target=tracking_thread)
thread.start()

# loop through the video frames and put them into the queue
while True:
    ret, frame = cap.read()
    if not ret:
        # add sentinel value to indicate end of frames
        frame_queue.put(None)
        break
    frame_queue.put(frame)

# wait for all tasks in the queue to be completed
frame_queue.join()

# wait for the tracking thread to finish
thread.join()

```

**Comment by glenn-jocher** [comment]
@akashAD98 try adding cv2.destroyAllWindows() immediately after "break" inside the if not ret: block. This should close all windows and prevent the while loop from running indefinitely. Here's what it should look like:

```python
# loop through the video frames and put them into the queue
while True:
    ret, frame = cap.read()
    if not ret:
        # add sentinel value to indicate end of frames
        frame_queue.put(None)
        # close all cv2 windows
        cv2.destroyAllWindows()
        break
    frame_queue.put(frame)
```

**Comment by akashAD98** [comment]
@glenn-jocher i added still infinite loop running, if you run my code then only you will get more idea about whats wrong happning in code . once again thanks for you & ultralytics team for 24 hours of support .

<img width="381" alt="image" src="https://user-images.githubusercontent.com/62583018/228753145-a2c51a26-0b42-47be-8893-44797bcfd921.png">

**Comment by glenn-jocher** [comment]
@akashAD98 I'm sorry to hear it's still not working. To clarify, are you able to see the frames being processed and tracked, and is it only the termination of the code that's the issue? It's possible that the code is taking a long time to process all the frames, especially if it's a long video. 

One thing you can try is adding a flag at the beginning of the tracking_thread() function that gets set to False when the sentinel value is reached. This will cause the while loop to exit once all frames have been processed. Here is what it would look like:

```python
# create a separate thread for the tracking process
def tracking_thread():
    done = False
    while not done:
        # get the next frame from the queue
        frame = frame_queue.get()
        if frame is None:
            # sentinel value indicating end of frames
            frame_queue.task_done()
            done = True
            break

        print("started loop")

        # track the objects in the frame
        results = model.track(frame)

        # loop through the results and draw bounding boxes on the frame
        for result in results:
            boxes = result.boxes
            print("boxes",boxes)
            
            for box in boxes:
                id = box.id
                xyxy = box.xyxy
                frame = cv2.rectangle(frame, (xyxy[0], xyxy[1]), (xyxy[2], xyxy

**Comment by akashAD98** [comment]
@glenn-jocher i added your suggestion still its running infinity loop.
video is small its less than 1 min,


<img width="656" alt="image" src="https://user-images.githubusercontent.com/62583018/228804583-7572e872-4939-4245-aa77-87701239280d.png">



output :
```
Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt to yolov8n.pt...
100%
6.23M/6.23M [00:00<00:00, 81.9MB/s]
model loaded
started loop
requirements: YOLOv8 requirement "lap>=0.4" not found, attempting AutoUpdate...
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting lap>=0.4
  Downloading lap-0.4.0.tar.gz (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 16.5 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: lap
  Building wheel for lap (setup.py): started
  Building wheel for lap (setup.py): finished with status 'done'
  Created wheel for lap: filename=lap-0.4.0-cp39-cp39-linux_x86_64.whl size=1655026 sha256=532a8faabde998232be133f13449be6ed1039d0e3c6798b126f02d5efa4dbf7e
  Stored in directory: /root/.cache/pip/wheels/2f/8b/30/e7dd4f9dc44fb438381df571c9a6bddc35aafd1bf39c4f8911
Successfully built lap
Installing collected packages: lap
Successfully installed lap-0.4.0

requirements: 1 package updated per ['lap>=0.4']
requirements: ⚠️ Restart runtime or rerun command for updates to take effect


0: 384x640 1 person, 312.3ms
Speed: 3.1ms preprocess, 312.3ms inference, 25.5ms postprocess per image at shape (1, 3, 640, 640)
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-2-09fbade39e06>", line 45, in tracking_thread
IndexError: index 1 is out of bounds for dimension 0 with size 1
boxes ultralytics.yolo.engine.results.Boxes object with attributes:

boxes: tensor([[1.7837e+03, 5.4270e+02, 1.9192e+03, 8.2201e+02, 1.0000e+00, 6.3146e-01, 0.0000e+00]])
cls: tensor([0.])
conf: tensor([0.6315])
data: tensor([[1.7837e+03, 5.4270e+02, 1.9192e+03, 8.2201e+02, 1.0000e+00, 6.3146e-01, 0.0000e+00]])
id: tensor([1.])
is_track: True
orig_shape: tensor([1080, 1920])
shape: torch.Size([1, 7])
xywh: tensor([[1851.4988,  682.3578,  135.4995,  279.3066]])
xywhn: tensor([[0.9643, 0.6318, 0.0706, 0.2586]])
xyxy: tensor([[1783.7490,  542.7045, 1919.2485,  822.0112]])
xyxyn: tensor([[0.9290, 0.5025, 0.9996, 0.7611]])

```
its keep running

<img width="603" alt="image" src="https://user-images.githubusercontent.com/62583018/228804884-c551ee70-1211-4a91-8301-aece85041299.png">

**Comment by s4ifbn** [comment]
I have a question in using `model.track(frame)`

in this loop
```
for result in results:
            boxes = result.boxes
            for box in boxes:
                id = box.id
                xyxy = box.xyxy
```
why does the tracker returns a new id at each iteration, how can I make it use the same id for the tracked object ?
thank you.

**Comment by sivaji123256** [comment]
> @sivaji123256 hi, we don't support that for now. But I think it can be done once you get the ids and boxes and frame. i,e:
> 
> ```python
> results = model.track(source=0, stream=True)
> for result in results:
>     boxes = result.boxes
>     frame = result.orig_img
>     for box in boxes:
>         id = box.id
>         xyxy = box.xyxy
> ```

**Comment by glenn-jocher** [comment]
@sivaji123256 the tracker returns a new ID for each tracked object because it is designed to track objects throughout a video, and each object may appear or disappear at different times. However, you may want to use the same ID for a tracked object across frames. In that case, you can store the object's ID and use it in subsequent frames. This would require you to keep track of the IDs and their corresponding objects as you process each frame. You can then use this information to link objects across frames and maintain consistency.

**Comment by sivaji123256** [comment]
@s4ifbn ,Have a glance at the above answer .

**Comment by glenn-jocher** [comment]
@s4ifbn the object tracker assigns a new ID to each object it tracks because it is designed to track objects throughout a video, with objects appearing and disappearing at different times. However, if you want to use the same ID for a tracked object across frames, you can store the object's ID and use it in subsequent frames. This would require you to keep track of the IDs and their corresponding objects as you process each frame, and then use this information to link object IDs across frames.

**Comment by s4ifbn** [comment]
@glenn-jocher @sivaji123256 I see, thank you so much.

**Comment by glenn-jocher** [comment]
@s4ifbn the object tracker assigns a unique ID to each object it tracks because it is designed to track objects throughout a video, with objects appearing and disappearing at different times. However, if you want to use the same ID for a tracked object across frames, you can store the object's ID and use it in subsequent frames. This would require you to keep track of the IDs and their corresponding objects as you process each frame, and then use this information to link object IDs across frames.

**Comment by aloma85** [comment]
Hello @glenn-jocher
How could I track keypoints instead of bounding boxes throughout the frames?

**Comment by HenryYDJ** [comment]
> @glenn-jocher i added still infinite loop running, if you run my code then only you will get more idea about whats wrong happning in code . once again thanks for you & ultralytics team for 24 hours of support .
> 
> <img alt="image" width="381" src="https://user-images.githubusercontent.com/62583018/228753145-a2c51a26-0b42-47be-8893-44797bcfd921.png">

Hi are you able to solve this problem? My code has a similar problem, if I use queue or deque to pass frame from camera capture to inference/track it runs very slow, but if I just use a variable to pass the frame, the code is fast. I am curious what caused this, I need to use queue or deque by the way so I can pass the inferenced frame out for broadcasting purposes.

**Comment by glenn-jocher** [comment]
Hi @HenryYDJ,

Thank you for reaching out and for your kind words about the support from the Ultralytics team! 😊

Regarding your issue with the infinite loop and the performance difference when using `queue` or `deque` versus a variable for passing frames, this is an interesting observation. The behavior you're experiencing could be due to several factors, including how the frames are being handled in memory and the synchronization between threads.

Here are a few suggestions to help troubleshoot and potentially resolve the issue:

1. **Reproducible Example**: If you haven't already, please provide a minimal reproducible example of your code. This will help us better understand the context and identify the root cause of the problem. You can refer to our guide on creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example).

2. **Latest Versions**: Ensure that you are using the latest versions of all relevant packages, including OpenCV and Ultralytics YOLO. Sometimes, performance issues can be resolved with updates that include optimizations and bug fixes.

3. **Thread Synchronization**: When using `queue` or `deque`, make sure that the producer (camera capture) and consumer (inference/track) threads are properly synchronized. You might want to use thread-safe queues like `queue.Queue` in Python, which are designed to handle such scenarios efficiently.

4. **Frame Handling**: If `cv2.imshow` is causing the slowdown, consider the following:
   - **Decouple Display from Processing**: Run the display (`cv2.imshow`) in a separate thread to decouple it from the frame processing logic. This can help maintain smooth frame rates.
   - **Buffer Size**: Adjust the buffer size of your `queue` or `deque` to ensure that frames are not being dropped or delayed excessively.

Here's a basic example to illustrate how you might structure your code with a thread-safe queue:

```python
import cv2
import threading
import queue

def capture_frames(video_source, frame_queue):
    cap = cv2.VideoCapture(video_source)
    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break
        if not frame_queue.full():
            frame_queue.put(frame)
    cap.release()

def process_frames(frame_queue):
    while True:
        if not frame_queue.empty():
            frame = frame_queue.get()
            # Perform inference/track here
            cv2.imshow('output', frame)
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break
    cv2.destroyAllWindows()

frame_queue = queue.Queue(maxsize=10)
video_source = 0  # or path to video file

capture_thread = threading.Thread(target=capture_frames, args=(video_source, frame_queue))
process_thread = threading.Thread(target=process_frames, args=(frame_queue,))

capture_thread.start()
process_thread.start()

capture_thread.join()
process_thread.join()
```

This example uses a thread-safe queue to pass frames between the capture and processing threads, which should help maintain performance and avoid the infinite loop issue.

I hope this helps! If you continue to experience issues, please share more details or your minimal reproducible example, and we'll be happy to assist further.

**Comment by HenryYDJ** [comment]
Hi glenn, thanks for the comments, I found the reason why it's stuck:
If I put the cv2.waitKey(1) inside the if len(frame_queue), the code will get stuck and take a very long time to run. I think it's because cv2 needs some time to setup the window and display the frames.

However, if I change my code to the code snippet below, and move the cv2.waitKey out of the if len(frame_queue), everything runs fast as it's supposed to be. I am not very sure about the reason, but this is what happened to me.
`        while True:
            if len(frame_queue) > 0:
                frame = frame_queue.popleft()
                cv2.imshow('Live Results', frame)
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break
`

**Comment by glenn-jocher** [comment]
Hi @HenryYDJ,

Thank you for sharing your findings! It's great to hear that you've identified a solution to the issue. Your observation about `cv2.waitKey(1)` is insightful. Indeed, `cv2.waitKey` is essential for updating the display window and handling GUI events, and placing it outside the conditional block ensures it runs consistently, which can prevent the application from getting stuck.

Here's a brief explanation to further clarify:

- **cv2.waitKey**: This function is crucial for OpenCV's event processing. It not only waits for a key event but also refreshes the display window. If it's placed inside a conditional block that doesn't always execute, the display might not update properly, leading to performance issues.

Your revised code structure ensures that `cv2.waitKey(1)` is called in every iteration of the loop, allowing the display to refresh smoothly and handle any pending GUI events.

If you encounter any further issues or have more questions, feel free to reach out. We're here to help! 😊
