### ISSUE TITLE
could you provide you ultralytics' yolov8 train log file?

### ISSUE THREAD

**Issue by greasebig** [ultralytics/ultralytics#1671]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

could you provide you ultralytics' yolov8 train log file?

**Comment by AyushExel** [comment]
@glenn-jocher could we zip the training logs together with the release?

**Comment by glenn-jocher** [comment]
@AyushExel what we want to do is train directly with HUB and then link directly to HUB projects. The original local training logs are gone now as they were on Docker images that have since been deleted. 

But we're going to retrain all models again once we have the HUB integration up, and then everything should be public and shareable.
