### ISSUE TITLE
How can I implement the YOLOv9 TFLite model with an input shape of [1, 320, 576, 3] and output shape of [1, 19, 3780] in Python?

### ISSUE THREAD

**Issue by foskyblue** [ultralytics/ultralytics#16717]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm working on a Python project requiring object detection using the YOLOv9 model. I successfully converted the model to TFLite format, but I'm having difficulties handling the output shape. The model requires an input shape of [1, 320, 576, 3] and outputs a tensor with the shape [1, 19, 3780].

I would greatly appreciate any guidance on how to interpret and process this output shape. Specifically, I need assistance with understanding the structure of the output tensor and extracting the bounding box coordinates and class probabilities for each detected object.

Any code snippets, suggestions, or resources related to implementing YOLOv9 TFLite with this specific output shape in Python would be immensely helpful. Thank you in advance for your assistance!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @foskyblue, thank you for your interest in Ultralytics 🚀! An Ultralytics engineer will assist you soon.

In the meantime, we suggest you visit our [Docs](https://docs.ultralytics.com) for detailed guidance on using YOLO models. You might find our sections on [Python](https://docs.ultralytics.com/usage/python/) usage helpful.

If this is a 🐛 Bug Report, please ensure to provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to assist us in debugging the issue more effectively.

For questions on custom implementations like this, it's beneficial to share as much detail as possible about your setup, including code snippets, any error messages, and logs. 

Join the vibrant Ultralytics community for immediate support. You can jump into our [Discord](https://ultralytics.com/discord) 🎧 for live discussions, participate in focused topics on our [Discourse](https://community.ultralytics.com), or explore the dialogues on our [Subreddit](https://reddit.com/r/ultralytics).

## Upgrade

Ensure you're on the latest `ultralytics` package with all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/):

```bash
pip install -U ultralytics
```

## Environments

YOLO can be run in the following verified environments, complete with dependencies like [CUDA](https://developer.nvidia.com/cuda) and [CUDNN](https://developer.nvidia.com/cudnn):

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** VM: See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** AMI: See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**: See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

The green badge indicates all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are passing, ensuring functionality across different setups.

Thanks for your patience and for being a part of our community! If you have more information or findings, feel free to update your issue here.

**Comment by Y-T-G** [comment]
Did you use `ultralytics` to export it to TFLite?

**Comment by foskyblue** [comment]
Thanks for your response @Y-T-G . Yes, I used ultralytics to export it to TFLite.

**Comment by Y-T-G** [comment]
What was the export command?

**Comment by foskyblue** [comment]
"model.export(format="tflite", imgsz=train_image_size)"

**Comment by foskyblue** [comment]
where train_image_size = (320, 576) -> (height, width)

**Comment by Y-T-G** [comment]
The post-processing for YOLOv9 is same as YOLov8. You can follow the example.

https://github.com/ultralytics/ultralytics/blob/main/examples/YOLOv8-OpenCV-int8-tflite-Python/main.py

**Comment by foskyblue** [comment]
Hi @Y-T-G. I was able to successfully test my TFLite model with recommended code. However, I get a division by zero error on the line 259 of the main.py script: ``` img_data_int8 = (img_data / scale + zero_point).astype(np.int8)```

Maybe this is because my TFLite model is of type float32 and not int8. I updated the line 259 in main.py to ```img_data_int8 = img_data.astype(np.float32)``` but then I get detection boxes of all zeros.


The input and output details of my TFLite model can be seen below:

input_details: ```{'name': 'inputs_0', 'index': 0, 'shape': array([  1, 320, 576,   3], dtype=int32), 'shape_signature': array([  1, 320, 576,   3], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}```

output_details: ```{'name': 'Identity', 'index': 1073, 'shape': array([   1,   19, 3780], dtype=int32), 'shape_signature': array([   1,   19, 3780], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}```

Do you see anything else I can do to get this to work fine? Thanks

**Comment by foskyblue** [comment]
Gat it! That worked! But the confidence scores are very low. The max confidence score is less than 0.01. Are there any reasons for having these very low scores? Thanks for your patience on this

**Comment by Y-T-G** [comment]
Does it work correctly with `ultralytics` ?
