### ISSUE TITLE
Save only detected images

### ISSUE THREAD

**Issue by ArthurHakobyann** [ultralytics/ultralytics#1696]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to save the images only when something is detected on it. Is there a parameter for this or I need to check results ?

**Comment by ArthurHakobyann** [comment]
Who can help me

**Comment by glenn-jocher** [comment]
Hello @ArthurHakobyann, I'm happy to help you with any questions you have regarding YOLOv8. What do you need help with?

**Comment by ArthurHakobyann** [comment]
@glenn-jocher I want to save the images only when something is detected on it. Is there a parameter for this?

**Comment by glenn-jocher** [comment]
Hello @ArthurHakobyann, there is no built-in parameter in YOLOv8 to save only the images with detected objects. However, you can achieve this by modifying the YOLOv8 source code. Here is one way to do it:

1. In the `detect.py` file, modify the `detect()` function to return only the images with detected objects. You can do this by adding a condition to check if the `pred` tensor has detected objects before appending the image to the `img_list` list:

```
    for img in dataset:
        # Get detections
        pred = model(img)

        # Check if there are detections
        num_detections = pred[pred[:, :, 4] > conf_thres].shape[0]
        if num_detections > 0:
            # Store image
            img_list.append(img)
```

2. In the `utils/general.py` file, modify the `load_images()` function to return only the images that will be used for detection. You can do this by adding a parameter to the `load_images()` function to indicate whether to load all images or only the ones with detected objects:

```
def load_images(img_dir, img_size=640, detect_only=False):
    if not detect_only:
        # Load all images
        path = str(Path(img_dir)) + os.sep
        files = sorted(glob.glob(path + '*.*'))
        return [cv2.cvtColor

**Comment by Abshir4** [comment]
> Hello @ArthurHakobyann, there is no built-in parameter in YOLOv8 to save only the images with detected objects. However, you can achieve this by processing Results objects however you'd like, including plotting/saving an image when something is detected. See https://docs.ultralytics.com/modes/predict for details.

can u give a example maybe?

**Comment by glenn-jocher** [comment]
@Abshir4 yes your predictions are in your results object and will be saved with your annotated image.

**Comment by Abshir4** [comment]
> redictions are in your results object and will be save

    model = YOLO('yolov8x-seg.pt')
    results = model.predict(source="bilder", imgsz=3400, save=True, boxes=True, conf=0.55, classes=[0, 2, 3, 5, 7])

can u do a example with this code?

**Comment by ArthurHakobyann** [comment]
@glenn-jocher I have another question. Why is it not possible to choose batch size during inference?
When the model overflows, neither the memory is filled, nor the GPU works at 100%. Then why doesn't inference parallelize multiple images?

**Comment by ArthurHakobyann** [comment]
> @glenn-jocher I have another question. Why is it not possible to choose batch size during inference? When the model overflows, neither the memory is filled, nor the GPU works at 100%. Then why doesn't inference parallelize multiple images?

@glenn-jocher I am still waiting )

**Comment by glenn-jocher** [comment]
I'm sorry for the delayed response @ArthurHakobyann. During inference, the model makes predictions on new, unseen data, which means that it hasn't been trained on any of the new data before. The batch size during inference is often lower than the batch size during training because more memory is required to store the intermediate activations when computing gradients during backpropagation. In addition, parallelizing inference over multiple images is possible and often a good way to speed up the inference process. This typically requires specific hardware and software optimizations, such as using multiple GPUs, data parallelism, or model parallelism, which are not always feasible on every hardware setup.

**Comment by SuperMaximus1984** [comment]
@glenn-jocher 
Is it possible to save only detected objects ("person" in particular) if the source is MP4 (or RTSP) HTTP video stream?
Bumping my head against various codes, I could not succeed. 
This (below) does not save any JPGs. Please help to solve this.
```
from ultralytics import YOLO

model = YOLO('yolov8x.pt') 

results = model.track(source="http://192.168.0.207:8080/video", conf=0.65, show=True)

# Save image of person with unique ID in "/detect/person" folder - doesn't work :(
for i, result in enumerate(results.xyxy):
    if result[-1] == 0:
        img_name = "/detect/person/" + str(i) + ".jpg"
        result.save(img_name)
```

**Comment by glenn-jocher** [comment]
Hello @SuperMaximus1984! It is definitely possible to save only detected objects, in particular "person", from an MP4 or RTSP video stream using YOLOv8. Your code looks mostly good, but you'll need to make a couple of changes to get it working: 

1. Change `results.xyxy` to `results.pred`. `results.xyxy` is not an attribute in the Results object, you will want to use `results.pred` which returns a list of coordinates for the predicted boxes.
2. Use `result[5]` instead of `result[-1]` to access the class index because YOLOv8 returns five coordinates instead of four for every predicted bounding box.

Here is the corrected code:

```python
from ultralytics import YOLO

model = YOLO('yolov8x.pt') 

results = model.track(source="http://192.168.0.207:8080/video", conf=0.65, show=True)

# Save image of person with unique ID in "/detect/person" folder
for i, result in enumerate(results.pred):
    if result[5] == 0:  # "person" class has index of 0
        img_name = "/detect/person/" + str(i) + ".jpg"
        model.save_img(img_name, result)  # save the image using YOLO's built-in save_img() method
```

I hope this helps! Let me know if you have any further questions or if there's anything else I can assist you with.

**Comment by SuperMaximus1984** [comment]
@glenn-jocher 
Unfortunately, your proposed code does not save any .jpg once a person is detected.
The only way I managed to save JPG is using `cv2.imwrite`, but that's a different not ideal approach (code is below):
```
import cv2
from ultralytics import YOLO

model = YOLO("yolov8x.pt")
cap = cv2.VideoCapture('http://192.168.0.207:8080/video')
object = None

while True:
    ret, frame = cap.read()
    if not ret:
        break

    result = model(frame)
    result = result[0].boxes
    result = result.cpu().numpy()
    
    for box in result.xyxy.tolist():
        [x,y,w,h] = box
        x, y, w, h = int(x), int(y), int(w), int(h)
        if object is None or (w-x)*(h-y) > object.shape[0]*object.shape[1]:
            object = frame[y:h, x:w]
            cv2.imwrite('output.jpg', object)
```

cap.release()
Here I solve another task, - saving .jpg of the biggest object, which is necessary in my case but cannot filter detection of "person"-only class [0].

If you have any other suggestions, please help. 
Thanks!

**Comment by glenn-jocher** [comment]
@SuperMaximus1984 hello, 

I apologize for the inconvenience you experienced with the previously suggested code. You can still use YOLOv8 to save images when a person is detected. For example, assuming you have a Results object from a `predict()` method call, you can filter the object detections to just the "person" class using the `where` method of the `Results` object. For instance, `result.where('class',0)` will return the coordinates of all "person" detections in `result`. You can then extract each detected person and save the image using OpenCV's `imwrite()` function.

I hope this helps. Let us know if you need further assistance.

**Comment by MachoPanko** [comment]
@glenn-jocher Hi glenn, thanks for the help on so many articles, you mentioned a .where method of the results class and .pred method. i cant seem to find them in the documentation under results on the ultralytics website. Do you perhaps have a link?

**Comment by glenn-jocher** [comment]
@MachoPanko to save images only when a detection is made, you can check the results after running the prediction and save the images conditionally based on whether any detections were found. There isn't a direct parameter to do this automatically, but it's straightforward to implement in your code.

Here's an example of how you can do this in Python using the Ultralytics YOLOv8 API:

```python
from ultralytics import YOLO
import cv2

# Load your model
model = YOLO('yolov8n.pt')  # Replace with your model path if needed

# Define your source images or directory
source = 'path/to/your/images'  # Can be a directory, a single image, or a list of images

# Run prediction
results = model.predict(source)

# Iterate over results and save images with detections
for i, result in enumerate(results):
    # Check if any detections were made
    if len(result.boxes) > 0:
        # Detections were made, save the image
        # You can use result.plot() to draw the detections on the image
        annotated_image = result.plot()
        cv2.imwrite(f'detected_image_{i}.jpg', annotated_image)
```

In this script, `result.boxes` will contain the bounding boxes of the detections. If this list is not empty, it means that objects were detected in the image, and you can proceed to save the image with the drawn detections using `result.plot()`. The `cv2.imwrite()` function is then used to save the image to disk. Adjust the file path and naming (`detected_image_{i}.jpg`) as needed for your application.

**Comment by Syed05** [comment]
How to adjust confidence score in this script?

**Comment by glenn-jocher** [comment]
@Syed05 hello! You can adjust the confidence score by setting the `conf` parameter in the `predict()` method. Here’s how you can modify your script:

```python
results = model.predict(source, conf=0.5)  # Set confidence threshold to 0.5
```

Just replace `0.5` with your desired confidence threshold. This will filter out detections below this confidence level. Happy coding! 😊

**Comment by Quanzan04** [comment]
Hello, for now I have a code that read every file from a directory and I use my trained Yolov9 model to detect if there is something I want. But the problem I have right now is that it's too slow because for each image i need to reload the model. On the other hand i don't  want to put all my data at once because there are too many. Is there a way during the inference to save only labeled image ? Because what you show is to save after the inference only the image with label on it. I hope I was clear enough and thanks for the response.

**Comment by Quanzan04** [comment]
Can we do the same with YOLOv9 ? Because I tried and it gave me the error : "appears to be an Ultralytics YOLOv5 model originally trained with https://github.com/ultralytics/yolov5.
This model is NOT forwards compatible with YOLOv8 at https://github.com/ultralytics/ultralytics.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt'"
So how to do the same, and only save image with labeled with yolov9 ?

**Comment by glenn-jocher** [comment]
Hello @Quanzan04,

Thank you for reaching out! It looks like you're encountering an issue with using a YOLOv5 model in the YOLOv8 framework. Unfortunately, models trained with YOLOv5 are not forwards compatible with YOLOv8 due to significant architectural changes and improvements.

To achieve the same functionality with YOLOv9, you'll need to ensure you're using a YOLOv9 model trained with the latest Ultralytics package. Here's how you can proceed:

1. **Train a YOLOv9 Model**: If you haven't already, train a new YOLOv9 model using the latest Ultralytics package. You can find detailed instructions on training YOLOv9 models in the [YOLOv9 documentation](https://docs.ultralytics.com/models/yolov9/).

2. **Adjust Confidence Score and Save Detected Images**: Once you have a YOLOv9 model, you can use the following script to adjust the confidence score and save images only when detections are made:

```python
from ultralytics import YOLO
import cv2

# Load your YOLOv9 model
model = YOLO('yolov9c.pt')  # Replace with your YOLOv9 model path if needed

# Define your source images or directory
source = 'path/to/your/images'  # Can be a directory, a single image, or a list of images

# Run prediction with a confidence threshold
results = model.predict(source, conf=0.5)  # Set confidence threshold to 0.5

# Iterate over results and save images with detections
for i, result in enumerate(results):
    # Check if any detections were made
    if len(result.boxes) > 0:
        # Detections were made, save the image
        annotated_image = result.plot()
        cv2.imwrite(f'detected_image_{i}.jpg', annotated_image)
```

This script sets a confidence threshold and saves images only when detections are made. Adjust the `conf` parameter to your desired confidence level.

If you encounter any issues, please ensure you are using the latest versions of the Ultralytics packages. If the problem persists, providing a minimum reproducible example would be very helpful. You can find guidance on creating one [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions or need further assistance. Happy coding! 😊

**Comment by Quanzan04** [comment]
Thank you very much for your help. But the thing is I trained my model with YOLOv9 base (the gelan-c-seg) so I don't know why it's not working ? 
Is there a problem with this model ?

**Comment by glenn-jocher** [comment]
Hello @Quanzan04,

Thank you for your question! It sounds like you're encountering an issue with your YOLOv9 model. To help you effectively, could you please provide a minimum reproducible example of your code? This will allow us to better understand the problem and offer a more precise solution. You can find guidance on creating one [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

In the meantime, please ensure you are using the latest versions of the Ultralytics packages. Sometimes, updating to the latest version can resolve unexpected issues.

If you have already verified that the issue persists with the latest versions and provided a reproducible example, we can dive deeper into the specifics of your YOLOv9 model and its configuration.

Looking forward to your response! 😊
