### ISSUE TITLE
How can I specify the directory where I need the resulting predicted video and the labels saved?

### ISSUE THREAD

**Issue by camarcano** [ultralytics/ultralytics#1702]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can I specify the directory where I need the resulting predicted video and the labels saved?

**Comment by glenn-jocher** [comment]
@camarcano regarding your question on how to specify the directory for saving the predicted video and labels, in `detect.py` and `detect_external.py`, add the `--save-dir` argument followed by the root directory you'd like to save to, as shown in the command below:

```bash
python detect.py --weights runs/train/exp/weights/last.pt --img 640 --conf 0.25 --source data/images --names runs/train/exp/weights/labels.txt --save-txt --save-conf --save-dir /path/to/save
```

This will output the predictions along with the labels and confidence score in the specified root directory. 

Please note that `--save-txt` and `--save-conf` arguments are necessary in order to save the text files containing labels and confidence scores respectively. 

Let me know if that helps!

**Comment by camarcano** [comment]
Thanks a lot! I was wondering, how can I adapt to this instruction I'm using in Python:

model.predict(source="joined.mp4", cfg="custom.yaml", show=False, save_txt=True, save=True, conf=0.45)

Thanks in advance!

**Comment by camarcano** [comment]
> @camarcano you can use `project` and `name` together. Your results will be saved to PROJECT/NAME:
> 
> ```
> yolo detect project=abc name=def
> ```

This worked perfectly like this:

model.predict(source="joined.mp4", project="results", name="prediction", show=False, save_txt=True, save=True, conf=0.45)

 thanks!

**Comment by glenn-jocher** [comment]
You're welcome, @camarcano! Glad to hear it worked for you. Don't hesitate to ask if you have any more questions or concerns!
