### ISSUE TITLE
About segmentation results and classes

### ISSUE THREAD

**Issue by tg636100** [ultralytics/ultralytics#17104]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I searched the documentation and Ask AI before asking the question, but I apologize if a similar question has already been asked.

I am getting the segmentation mask with the following code:
```
results_0 = model(frame, device=device, imgsz=640, conf=0.5, classes=[0])
masks_0 = [result.masks.cpu() if result.masks is not None else None for result in results_0]
```
```
results_1 = model(frame, device=device, imgsz=640, conf=0.5, classes=[1])
masks_1 = [result.masks.cpu() if result.masks is not None else None for result in results_1]
```
However, this code performs inference twice, which is wasteful. I would like to obtain the segmentation result without specifying the class as shown below, and then obtain the segmentation information for class=0 and class=1 separately, but I could not find such a way.
After getting the segmentation, I'm using my own code to draw the masks in a frame, so I want to get the same results as if I specified classes=[1]. Is this possible?
```
results = model(frame, device=device, imgsz=640, conf=0.5)
masks_0 = ?
masks_1 = ?
# I want the mask results for class=0 and class=1 separately
```

**Comment by UltralyticsAssistant** [comment]
👋 Hello @tg636100, thank you for your interest in Ultralytics 🚀! It seems you're working on segmentation masks and looking for a more efficient way to obtain results for specific classes without performing inference multiple times.

If this is a 🐛 Bug Report, please provide a minimum reproducible example to help us debug it. 

If this is a custom training ❓ Question, please provide as much information as possible, including dataset image examples and training logs, and verify you are following our tips for best training results.

Join the Ultralytics community where it suits you best. For real-time chat, head to Discord 🎧. Prefer in-depth discussions? Check out Discourse. Or dive into threads on our Subreddit to share knowledge with the community.

## Upgrade

Upgrade to the latest `ultralytics` package including all requirements in a **Python>=3.8** environment with **PyTorch>=1.8** to verify your issue is not already resolved in the latest version:

```bash
pip install -U ultralytics
```

## Environments

YOLO may be run in any of the following up-to-date verified environments (with all dependencies including CUDA/CUDNN, Python and PyTorch preinstalled):

- Notebooks with free GPU
- Google Cloud Deep Learning VM
- Amazon Deep Learning AMI
- Docker Image

## Status

If the CI badge is green, all Ultralytics CI tests are currently passing. CI tests verify correct operation of all YOLO Modes and Tasks on macOS, Windows, and Ubuntu every 24 hours and on every commit.

This response is automated, but rest assured, an Ultralytics engineer will assist you soon. 😊

**Comment by Y-T-G** [comment]
You can use class information from `results.boxes`:

```python
results = model(ASSETS / "bus.jpg")[0]
for cls, mask in zip(results.boxes.cls, result.masks.xy):
    if cls == 0:
        mask_0 = mask
```

**Comment by tg636100** [comment]
Thank you for your reply! I solved it thanks to you.

**Comment by glenn-jocher** [comment]
You're welcome! I'm glad to hear you resolved the issue. If you have any more questions, feel free to ask.
