### ISSUE TITLE
stream＝True？

### ISSUE THREAD

**Issue by HornGate** [ultralytics/ultralytics#1713]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I use yolov8x.pt (for detect) to predict the number of images in the folder greater than 1000, it show me with warnings that I should make sure the stream=True, otherwise it would easily result in OOM. How should I set stream = True?

**Comment by Laughing-q** [comment]
@HornGate just pass `stream=True` and use a for loop to launch it.
```python
results = model(source=..., stream=True)  # generator of Results objects
for r in results:
    boxes = r.boxes  # Boxes object for bbox outputs
    masks = r.masks  # Masks object for segment masks outputs
    probs = r.probs  # Class probabilities for classification outputs
```

**Comment by dh031200** [comment]
You can use `stream=True` like this:
model = YOLO("yolov8n.pt")
```python
results = model.predict(source=src, verbose=False, stream=True)
for r in results:
    writer.write(r.plot())
```

**Comment by apiszcz** [comment]
Using the yolov8 CLI how does one enable stream=True?

**Comment by glenn-jocher** [comment]
@apiszcz stream=True is enabled by default for CLI inference, but if you have any doubt you can force it with `yolo predict stream=True`

**Comment by HornGate** [comment]
> `yolo predict stream=True`

But why we get this "**SyntaxError: 'stream' is not a valid YOLO argument.** "?

**Comment by glenn-jocher** [comment]
@HornGate i apologize for the confusion. The `stream` argument is actually not a CLI argument of YOLOv8. It's a parameter you pass to the `predict` method when using the YOLOv8 Python API. 

So to clarify, you don't need to enable `stream=True` when using `yolo predict` CLI command. The CLI command automatically enables `stream=True` mode to process videos or live streams in real-time.

I hope this clears up any confusion. Let me know if you have any other questions!

**Comment by apiszcz** [comment]
yolov8 started with CLI is producing this warning

```
WARNING  stream/video/webcam/dir predict source will accumulate results in RAM unless `stream=True` is passed,
    causing potential out-of-memory errors for large sources or long-running streams/videos.
```

**Comment by HornGate** [comment]
> yolov8 started with CLI is producing this warning
> 
> ```
> WARNING  stream/video/webcam/dir predict source will accumulate results in RAM unless `stream=True` is passed,
>     causing potential out-of-memory errors for large sources or long-running streams/videos.
> ```

You can run “**yolo predict cfg=./predict_cfg.yaml**”，and this CLI command automatically enables "**stream=True**" mode to process videos or live streams in real-time.

**Comment by apiszcz** [comment]
That is what I am doing, I am still getting the warning.

Tx

**Comment by glenn-jocher** [comment]
@HornGate The warning message is there to inform you of the potential issue of running out of memory. If your source files are not too large, or if you are processing them relatively quickly, you can ignore the message.

If you need to process larger files, or if your processing is particularly long-running, then you should pass the `stream=True` argument to the `yolo predict` command to avoid accumulating results in RAM. 

If you have already passed `stream=True` and are still getting the warning messages, you can safely ignore them as long as you are able to process your files without any issues or crashes. 

I hope this helps clarify your understanding. Let me know if you have any other questions!

**Comment by apiszcz** [comment]
stream=True throws an error stating it is invalid option on the command line or in a cfg file

yolo cfg=test.yml stream=True 

or

yolo cfg=test.yaml
where test.yaml has
stream: True

**Comment by glenn-jocher** [comment]
@HornGate I apologize for the confusion. The `stream` parameter is not a recognized parameter in the YOLOv8 configuration file or CLI command.

However, you can configure the streaming mode by setting the `source` parameter to a URL, camera index, or directory path to automatically turn on streaming mode. For example, `source: "rtsp://192.168.1.10:554/stream1"` to stream from a network camera, or `source: 0` to stream from the default local camera.

If you are processing files from a directory, make sure to include the directory path in the `source` parameter, such as `source: "/path/to/directory/"`.

I hope this helps. Let me know if you have any other questions.

**Comment by apiszcz** [comment]
I am. Processing is running fine, curious about the warning.

**Comment by glenn-jocher** [comment]
@HornGate You're welcome! I'm glad to hear that the processing is running fine.

Yes, the warning is mostly for streaming sources, but it's always a good idea to keep your system resources in mind when processing large amounts of data.

Regarding recursive folder search, it's a good suggestion, and I will pass it along to the development team for consideration. In the meantime, as a workaround, you can use the command-line tools provided by your operating system to create a list of files across multiple directories and pass that list to YOLOv8 using the `--source` option.

Let me know if you have any other questions or concerns.

**Comment by apiszcz** [comment]
thanks, was not aware of list input for source, i have a lot of files.

**Comment by glenn-jocher** [comment]
@HornGate You're welcome! Yes, the `--source` option in YOLOv8 allows you to input a list of files for processing, making it easy to process multiple files at once without the need to include individual file paths in the command. 

To use this option, simply create a text file listing the file paths (one file path per line), and pass the file path to that text file as the source. The `--source` option supports text files with the `.txt` extension.

I hope this helps simplify your data processing workflow. Let me know if you have any other questions or concerns.

**Comment by HornGate** [comment]
> stream=True throws an error stating it is invalid option on the command line or in a cfg file
> 
> yolo cfg=test.yml stream=True
> 
> or
> 
> yolo cfg=test.yaml where test.yaml has stream: True

You should run "yolo **predict** cfg=...."

**Comment by apiszcz** [comment]
Did i miss the the --source listofiles.txt in the documentation?

**Comment by apiszcz** [comment]
yolv8 running CLI on a lot of video files, memory use > 210GB? 
Seems like there is an issue.

**Comment by apiszcz** [comment]
Switching back to yolov5. Standing by for any tips on how to conserve memory.
yv5 stays under 23 GB per process.

**Comment by glenn-jocher** [comment]
@AyushExel seems like YOLOv8 RAM usage during video/dir CLI inference is much higher than YOLOv5 per @apiszcz above

**Comment by apiszcz** [comment]
After a few hours of operation yv8 exceeds 600GB of RAM and stalls the system. yv5 no issues, stays at 2.8GB through processing runs.  I have tried yv8 on a few different instances, ubuntu 20.04.

**Comment by AyushExel** [comment]
This points to memory leak. I'll try to reproduce tonight

**Comment by Laughing-q** [comment]
@apiszcz could you provide your command to reproduce?

**Comment by AyushExel** [comment]
@apiszcz cli mode already uses stream mode by default so you should not get that warning. We can try to debug it if you provide the reproducible command. Thanks!

**Comment by apiszcz** [comment]
yolo cfg=yolov8cfg.yml

**Comment by apiszcz** [comment]
rcvd an email stating this issue is closed?

**Comment by AyushExel** [comment]
@apiszcz I'm reopening this issue. I think we know why this is happening. Somehow when you pass `cfg=...` the stream mode is not being initialized. I'll investigate this after the current project. Please ping me if you don't hear from me in 2 days

**Comment by apiszcz** [comment]
I agree, which is the issue raised in the start of this issue. Thank you!
________________________________

**Comment by glenn-jocher** [comment]
Apologies for the confusion. Yes, it seems like this issue still remains unsolved. When passing `cfg=...` it appears that the stream mode is not being initialized which could be causing the issue. @apiszcz has provided a command earlier for reproducing the issue, and I will investigate this after finishing my current project. If you don't hear from me in 2 days or need further assistance, please don't hesitate to ping me again.

**Comment by Laughing-q** [comment]
@apiszcz @AyushExel @glenn-jocher well I'm able to reproduce the issue with `yolo cfg=test.yaml` which the `source` in this file is a video, but in fact the author @HornGate of this issue had commented the correct usage twice. [https://github.com/ultralytics/ultralytics/issues/1713#issuecomment-1492697658](https://github.com/ultralytics/ultralytics/issues/1713#issuecomment-1492697658) and [https://github.com/ultralytics/ultralytics/issues/1713#issuecomment-1492234809](https://github.com/ultralytics/ultralytics/issues/1713#issuecomment-1492234809)
you should use `yolo predict cfg=` instead of `yolo cfg=`.
This is because the updated logic here:
[https://github.com/ultralytics/ultralytics/blob/4198570a4ba98351107527142d85125eb8d0039f/ultralytics/yolo/engine/model.py#L223-L224](https://github.com/ultralytics/ultralytics/blob/4198570a4ba98351107527142d85125eb8d0039f/ultralytics/yolo/engine/model.py#L223-L224)

**Comment by apiszcz** [comment]
Thank you will test.

**Comment by glenn-jocher** [comment]
@apiszcz you're welcome! The solution to your problem might be as simple as using `yolo predict cfg=` instead of `yolo cfg=`. This is because the `yolo cfg=` command doesn't initialize the stream mode properly when the `cfg` file contains a video source, which could be causing the out-of-memory issue. The correct command `yolo predict cfg=` should initialize the stream mode properly and avoid the out-of-memory issue.

**Comment by apiszcz** [comment]
5.2gb vs 100GB+ per process.

**Comment by glenn-jocher** [comment]
@apiszcz i'm glad the solution worked for you! As for the REST API, it should be a great addition to Ultralytics YOLOv8. REST API is a way to provide an HTTP interface for other systems to interact with your application. It will allow you to serve your YOLOv8 model as an HTTP service in order to perform real-time object detection of live video streams, image files, and IP camera feeds. This can be useful for a number of applications, such as security cameras, traffic monitoring, and more.

**Comment by apiszcz** [comment]
Is the REST API ready? Tx

**Comment by glenn-jocher** [comment]
@apiszcz, as far as I know, the REST API is not yet available in Ultralytics YOLOv8. While it is a planned feature, at the moment there is no specific timeline for when it will be implemented. However, there are a number of resources available online that can help you build your own REST API to serve YOLOv8 model. One popular tool for building REST APIs is Flask, which can be used to create a web service that serves the YOLOv8 model.

**Comment by ElNoSabe322** [comment]
Hi,
So I have a small issue. I set the ```stream=True``` flag since I have a large video source but whenever I set this parameter as ```True```, I do not see any video output being saved. However, setting the parameter as ```False``` saves the output but leads to a full RAM. 

Here is the predict command used (in Google Colab): ``` model. Predict(source=VIDEO_SRC_PATH, stream=False, save=True, save_txt=False, device=0, conf=0.5, line_width=None, visualize=False, augment=True, agnostic_nms=True, project=PRED_VIDEO_DIR, name=f'Turtle_Video{VIDEO_CTR}')```

Thank you.

**Comment by apiszcz** [comment]
Are you setting this flag on the command line? 

yolo cfg=test.yml stream=True

**Comment by ElNoSabe322** [comment]
> Are you setting this flag on the command line?
> 
> yolo cfg=test.yml stream=True

No, I'm setting this flag on a Jupyter Notebook cell, i.e., a Python statement. I even ran this on a local Jupyter Lab server (and similar to Google Colab), I see no output and the video is not being saved as well.

**Comment by apiszcz** [comment]
That is most likely that is the issue, i was trying to set stream in the
configuration file and had the same issue. it needs to be set on the
command line

**Comment by glenn-jocher** [comment]
@ElNoSabe322 hi Dominic Alex Joseph,

Thank you for reaching out with your issue. From what you've mentioned, it seems like you're setting the `stream` flag in a Jupyter Notebook cell using a Python statement. However, in order to properly set the `stream` flag, it needs to be set on the command line, not in the configuration file or as a Python statement. 

When running the YOLOv8 command, you can set the `stream` flag to `True` in the command line by using the following format:

```bash
yolo cfg=test.yml stream=True
```

This will enable the streaming mode and should allow the video to be saved without consuming excessive RAM.

I hope this explanation helps. If you have any further questions or need additional assistance, please don't hesitate to ask.

Kind regards,
Glenn Jocher

**Comment by ElNoSabe322** [comment]
> That is most likely that is the issue, i was trying to set stream in the configuration file and had the same issue. it needs to be set on the command line
> […](#)
> 




> @ElNoSabe322 hi Dominic Alex Joseph,
> 
> Thank you for reaching out with your issue. From what you've mentioned, it seems like you're setting the `stream` flag in a Jupyter Notebook cell using a Python statement. However, in order to properly set the `stream` flag, it needs to be set on the command line, not in the configuration file or as a Python statement.
> 
> When running the YOLOv8 command, you can set the `stream` flag to `True` in the command line by using the following format:
> 
> ```shell
> yolo cfg=test.yml stream=True
> ```
> 
> This will enable the streaming mode and should allow the video to be saved without consuming excessive RAM.
> 
> I hope this explanation helps. If you have any further questions or need additional assistance, please don't hesitate to ask.
> 
> Kind regards, Glenn Jocher

@apiszcz and @glenn-jocher, Oh I see... I was not aware of that 😮. I thought both CLI commands and Python statement parameters could be used interchangeably, but I guess the ```stream``` parameter is an exception. 
Thank you all so much. I appreciate your valuable explanations. ♥

**Comment by ElNoSabe322** [comment]
@apiszcz and @glenn-jocher Sorry, but I now have another problem 😅. So, I took the suggestion provided and tried to run the ```stream=True``` parameter from the CLI but I now receive an error saying that ```'stream' is not a valid YOLO argument.```

Here's the code that I tried to run via Google Colab
```python
# Predicting on videos
PredTimeStart = time.time()
VIDEO_CTR = 1
PRED_VIDEO_DIR = f'{HOME}/runs/detect/Detect_TestVideo_Predict'
for VIDEO_NAME in VIDEO_FILE_LIST[0:1]:
    VIDEO_SRC_PATH = os.path.join(VIDEO_DIR, VIDEO_NAME)

    # Running video prediction on CLI since the ```stream = True``` parameter works only 
    # with a CLI command and not as a Python statement
    !yolo cfg='/content/drive/MyDrive/Colab Notebooks/Detect/detect_predict_config.yaml' stream=True
    # model.predict(source=VIDEO_SRC_PATH, stream=True, save=True, save_txt=False, device=0, 
    #               conf=0.5, line_width=None, visualize=False, augment=True, agnostic_nms=True, 
    #               project=PRED_VIDEO_DIR, name=f'Turtle_Video{VIDEO_CTR}')

    VIDEO_CTR += 1
    # display.clear_output()
PredTime_Elapsed_1 = time.time()-PredTimeStart
print(f"\nPrediction on {len(VIDEO_FILE_LIST[:4])} test videos completed in 
{PredTime_Elapsed_1/60:.0f} minutes and {PredTime_Elapsed_1%60:.0f} seconds.")
```
Here's the custom config file I made (yeah the extension should be .yaml)
[detect_predict_config.txt](https://github.com/ultralytics/ultralytics/files/11859299/detect_predict_config.txt)
<br>And here is a screenshot of the error I received from Google Colab.
<img width="730" alt="v8 stream error" src="https://github.com/ultralytics/ultralytics/assets/79654411/2e2a5c1b-e184-4a48-84a1-2352d1e21df9">

<br>Sorry but yeah, I need some additional assistance.

**Comment by Laughing-q** [comment]
@ElNoSabe322 please use the latest version of ultralytics package.

**Comment by ElNoSabe322** [comment]
> @ElNoSabe322 please use the latest version of ultralytics package.

@Laughing-q I am using the latest version of the Ultralytics package (8.0.122). 

Upon reading this whole thread once again, I realize that a solution was already provided which I did not check out. 
```yolo predict cfg=``` and not ```yolo cfg```.

**Update:** I tried ```!yolo predict cfg='/content/drive/MyDrive/Colab Notebooks/Detect/detect_predict_config.yaml' stream=True``` but I still get the same error from Google Colab.

**Comment by glenn-jocher** [comment]
@ElNoSabe322 I apologize for the confusion. It seems that the issue you are facing is not related to the `stream` parameter. In your updated code snippet, you are using `yolo predict` command instead of `yolo cfg` command, and have specified `mode: predict` in your custom configuration file. However, you are still encountering the same error.

To troubleshoot this issue, I would recommend checking the following:

1. Make sure that the custom configuration file `detect_predict_config.yaml` is correctly formatted and does not contain any syntax errors.

2. Verify that the file path for the configuration file is correct. Double-check if the file is located at the specified path `/content/drive/MyDrive/Colab Notebooks/Detect/detect_predict_config.yaml`.

3. Ensure that the Ultralytics package is installed correctly, and that you are using the latest version (`8.0.122`).

If the issue persists, I would recommend reaching out to the Ultralytics YOLOv8 repository for further assistance. They will be able to provide more specific guidance on how to resolve the error you are encountering.

I hope this helps. If you have any further questions, please let me know.

**Comment by Laughing-q** [comment]
@ElNoSabe322 ooh my bad, `stream` mode is only for python api, if you're using cli mode then you don't need to worry about `stream`, it is set to `True`  for cli mode.
BTW from your code, it seems you're calling command line inside python script, actually you don't have to do that, you can just use our friendly python api. :) something like this:
```python
# Predicting on videos
PredTimeStart = time.time()
VIDEO_CTR = 1
PRED_VIDEO_DIR = f'{HOME}/runs/detect/Detect_TestVideo_Predict'
for VIDEO_NAME in VIDEO_FILE_LIST[0:1]:
    VIDEO_SRC_PATH = os.path.join(VIDEO_DIR, VIDEO_NAME)

    # Running video prediction on CLI since the ```stream = True``` parameter works only 
    # with a CLI command and not as a Python statement
    model = YOLO("yolov8n.pt")
    model.predict(cfg=cfg, stream=True)
    # model.predict(source=VIDEO_SRC_PATH, stream=True, save=True, save_txt=False, device=0, 
    #               conf=0.5, line_width=None, visualize=False, augment=True, agnostic_nms=True, 
    #               project=PRED_VIDEO_DIR, name=f'Turtle_Video{VIDEO_CTR}')

    VIDEO_CTR += 1
    # display.clear_output()
PredTime_Elapsed_1 = time.time()-PredTimeStart
print(f"\nPrediction on {len(VIDEO_FILE_LIST)} test videos completed in 
{PredTime_Elapsed_1/60:.0f} minutes and {PredTime_Elapsed_1%60:.0f} seconds."
```

**Comment by ElNoSabe322** [comment]
> @ElNoSabe322 I apologize for the confusion. It seems that the issue you are facing is not related to the `stream` parameter. In your updated code snippet, you are using `yolo predict` command instead of `yolo cfg` command, and have specified `mode: predict` in your custom configuration file. However, you are still encountering the same error.
> 
> To troubleshoot this issue, I would recommend checking the following:
> 
> 1. Make sure that the custom configuration file `detect_predict_config.yaml` is correctly formatted and does not contain any syntax errors.
> 2. Verify that the file path for the configuration file is correct. Double-check if the file is located at the specified path `/content/drive/MyDrive/Colab Notebooks/Detect/detect_predict_config.yaml`.
> 3. Ensure that the Ultralytics package is installed correctly, and that you are using the latest version (`8.0.122`).
> 
> If the issue persists, I would recommend reaching out to the Ultralytics YOLOv8 repository for further assistance. They will be able to provide more specific guidance on how to resolve the error you are encountering.
> 
> I hope this helps. If you have any further questions, please let me know.

@glenn-jocher Thank you for your reply and there's no need to apologize 😄. As per your recommendations, I have checked the following:
1. I have not received any syntax errors and I have double-checked the custom configuration file.
2. Yes, the path to the configuration file is also correct. 
3. Yes, I can guarantee that the package is installed correctly and is also the latest version.

<br>These answers are further reinforced by the fact that when I remove the ```stream=True``` parameter, all the errors are removed and everything works as intended. 
```python
# CLI command without stream=True
!yolo predict cfg='/content/drive/MyDrive/Colab Notebooks/Detect/detect_predict_config.yaml'
```
And the corresponding output from Google Colab is:
<img width="662" alt="image" src="https://github.com/ultralytics/ultralytics/assets/79654411/9f21e265-419b-44b0-a084-3130a989de50">

<br>Everything seems to be working in Colab, without the ```stream=True``` parameter.<br> 

**SOLUTION**
Yeah, so building upon what everyone has discussed in this thread, yes in Google Colab, the addition of the ```stream=True``` parameter leads to an error. Therefore, in Google Colab, running the prediction statement as a CLI command implicitly enforces the ```stream=True``` by default and hence no _out of _memory__ issues are observed and everything now runs smoothly, all of a sudden (7 large videos and the RAM never broke a sweat 😂).<br><br>
To anyone who may potentially encounter this problem while predicting on Google Colab (or even Jupyter Lab or Jupyter Notebook), run the prediction command (especially for videos) as a CLI command and **not** as a Python statement in the corresponding cell. As described earlier, the ```stream=True``` warning disappears when executed from the CLI and there is no need to explicitly declare this parameter since (as again mentioned earlier in this thread, it is done so by default). An example of this command can be:
```python
!yolo predict cfg='/content/drive/MyDrive/Colab Notebooks/Detect/detect_predict_config.yaml' name='Turtle_Video'
```
where ```cfg``` refers to the custom prediction setting configuration file (an example of which can be found in the messages earlier) and the meanings behind each of the hyperparameters can be found here: [Inference Arguments](https://docs.ultralytics.com/modes/predict/#inference-sources).

Thank you so much @apiszcz, @glenn-jocher, and @Laughing-q for taking the time to go through my queries. 🥰

**Comment by glenn-jocher** [comment]
@apiszcz Great explanation and solution! Your response is clear, concise, and provides a step-by-step troubleshooting guide for the mentioned issue. The explanation on how to run the prediction command as a CLI command instead of a Python statement in Google Colab is particularly helpful. The additional example command and the reference link provide useful information for users to understand and apply your solution. The overall tone is friendly, professional, and appreciative. Well done!

**Comment by abbyad** [comment]
Similar to @epochDVKHN's [issue above](https://github.com/ultralytics/ultralytics/issues/1713#issuecomment-1605689756), I was doing a predict via python with `stream=True` and it yielded no output. The solution is somewhat hidden in the [earlier comments](https://github.com/ultralytics/ultralytics/issues/1713#issuecomment-1489838448), so I figure it would help to be more explicit about it in case it helps someone else: 
 ###  You **_must_ use the python generator** to run the predict

```python
results = model.predict(source=..., stream=True)
for r in results:
    # Do anything here. If you omit this, the predict doesn't run
```

_Thanks @Laughing-q for helping me resolve my issue with your [comments above](https://github.com/ultralytics/ultralytics/issues/1713#issuecomment-1489838448) and in [this other issue](https://github.com/ultralytics/ultralytics/issues/2930#issuecomment-1571262310). In case someone else runs into this situation, perhaps it's worth updating [the snippet](https://github.com/ultralytics/ultralytics/issues/1713#issuecomment-1606107757) as well?_

**Comment by CH-Echo** [comment]
@glenn-jocher Using the same stream, the time for inference and prediction has indeed been reduced. But why does the time increase when later values ​​are retrieved? As soon as I open the stream, the subsequent value extraction time increases. After closing the stream, the subsequent value extraction time is basically ignored.

**Comment by glenn-jocher** [comment]
It sounds like the increase in time might be due to buffering or processing delays as the stream progresses. You might want to check if the system resources are being efficiently managed or if there's a need to optimize the processing pipeline.
