### ISSUE TITLE
Not able to resume from last weight. using cli

### ISSUE THREAD

**Issue by akashAD98** [ultralytics/ultralytics#1722]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

```yolo detect train  model=yolov8s_mosicoff_degree20_office20/train/weights/last.pt data=data.yaml cfg=default.yaml resume=True```

my model trained for 100 epochs & stopped now i want to resume it ,how should i do it?

i used this command to train my  model
```
yolo detect train  model=yolov8s.pt data=data.yaml cfg=default.yaml
```

### Environment

ubuntu 20.04 ,latest ultralytics version

**Comment by akashAD98** [comment]
also, it's not taking my data.yaml file, its taking coco128.yaml files

**Comment by glenn-jocher** [comment]
@akashAD98 your use case is not resuming, it's just starting from pretrained weights. So run it without the resume argument.

**Comment by Arshadoid** [comment]
@glenn-jocher  Just to follow-up on this question. In my case if I want to start a training let's say for 300 epochs, and I want to make sure that I can continue if training stops ( because of allocated time-out etc.). What would be correct way of doing this?
Here is my python training code:
```
from ultralytics import YOLO
model=YOLO('yolov8x-seg.pt')
model.train(data='dataset_TTPLA.yaml', epochs=300, imgsz=1280, batch=8, save_period=5, cache=True, device=[0,1,2,3], workers=4, resume=True)
```
As @akashAD98 mentioned, with this code the model tries to load "coco128.yaml" file. 
 
But if I remove resume=True model can start the training. 
`model.train(data='dataset_TTPLA.yaml', epochs=300 imgsz=1280, batch=8, save_period=5, device=[0,1,2,3], workers=1)`

I'm assuming we need to use resume=True if have checkpoint saved, is this right? So let's say if I run the last model.train and it stops after 100 epochs, how can I continue it? Thanks.

**Comment by glenn-jocher** [comment]
@bytejunkie You are correct that setting `resume=True` is required to resume training from the last checkpoint if it stops, provided that the `save_period` parameter is set correctly to save the checkpoint at intervals. 

In your case, you can resume the training by using the `model.train()` method without any further changes, since you have already set `resume=True` in your initial training code. If training stops due to a timeout or other reason, simply run the same `model.train()` command again, and training will resume from the last checkpoint. 

You can also adjust other parameters like the number of epochs, and `save_period` as needed. Ensure that the `data` parameter is set to the correct `.yaml` file for your dataset. If you encounter any further issues, please do not hesitate to ask.

**Comment by Arshadoid** [comment]
@glenn-jocher Sorry, I didn't quite get it.

This is the code I run to start my training:  
```
from ultralytics import YOLO
model=YOLO('yolov8x-seg.pt')
model.train(data='dataset_TTPLA.yaml', epochs=300, imgsz=1280, batch=12, save_period=5, cache=True, device=[0,1,2,3], workers=4)
```
I **didn't** set`resume=True` there as if I do the model is looking for "coco128.yaml". Maybe it's a bug as mentioned earlier.

Currently the model run without `resume=True`  for 10 hours and stopped at epoch 225/300. Now, I want to continue from the last checkpoint(or last.py?)

Should I run it like this, according to [link to docs]?(https://github.com/ultralytics/ultralytics/blob/main/docs/usage/python.md#:~:text=%3D%3D%3D%20%22Resume%22%0A%20%20%20%20%60%60%60python%0A%20%20%20%20%23%20TODO%3A%20Resume%20feature%20is%20under%20development%20and%20should%20be%20released%20soon.%0A%20%20%20%20model%20%3D%20YOLO(%22last.pt%22)%0A%20%20%20%20model.train(resume%3DTrue))

```
model.YOLO('last.pt')
model.train(resume=True)
```
Also when pointing out to "last.pt" I assume we need to point to exact directory as it currently sits in  /runs/segment/train8.

I would appreciate if you could clarify the resume feature one more time (with given example maybe). Thanks!

**Comment by akashAD98** [comment]
@Arshadoid you can simply load your last.pt in YOLO('weight/last.pt) & start the trainig, it will automatically pick from last epoch
& also put resume=True. Ayour bove code is correct.
