### ISSUE TITLE
Predict using OpenCV - colour channels 

### ISSUE THREAD

**Issue by MiksVasiljevs** [ultralytics/ultralytics#1723]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When running prediction on an OpenCV, according to the docs, we should switch the colour channels from BGR to RGB, as referenced here:
https://github.com/ultralytics/ultralytics/blob/ccb64198351b1121478ab4280589741c7988003f/docs/modes/predict.md?plain=1#L47

However, when running a simple test with 4 different ways of providing image to the predictor, it seems that running prediction on an image directly read via OpenCV yields results that match running from a url, while using PIL or changing colour channels for an image read via OpenCV yield different outputs. 

Furthermore, although I have not tracked the full pipeline of inferencing, it appears that np images do get their colour channels adjusted within the dataloaders?
https://github.com/ultralytics/ultralytics/blob/ccb64198351b1121478ab4280589741c7988003f/ultralytics/yolo/data/dataloaders/stream_loaders.py#L312

Could you please advise on whether images loaded using OpenCV should be/are intended to be provided to the dector with BGR or RGB colours?
Additionally, the performance of a "large" model appears to be relatively poor on the sample image (seems to perform slightly worse compared to "n" model), is this also the expected performance of the model?

Below I am providing the 4 different versions of predicting, as well as the outputs as stored on disk.

```
#  yields output 1 (below)
model = YOLO('yolov8l.pt')
model.predict('https://ultralytics.com/images/bus.jpg', save=True)
```

``` 
#  yields output 2 (below)
model = YOLO('yolov8l.pt')
img = cv2.imread('bus.jpg')
model.predict(img, save=True)
```

```
#  yields output 3 (below)
model = YOLO('yolov8l.pt')
img = cv2.imread('bus.jpg')[:,:,::-1]  # HWC, BGR to RGB
model.predict(img, save=True)
```

```
#  yields output 4 (below)
model = YOLO('yolov8l.pt')
img = Image.open('bus.jpg')
model.predict(img, save=True)
```
output 1 (url/file path)
![bus](https://user-images.githubusercontent.com/51921908/228922863-8bbae19d-20f2-4cf1-a3a9-8d775b450d9e.jpg)

output 2 (cv2 without channel conversion)
![image0](https://user-images.githubusercontent.com/51921908/228924168-335e0273-a7a2-4ebe-87af-5cbeec8e4ec0.jpg)

output 3 (cv2 with channel conversion) 
![image0](https://user-images.githubusercontent.com/51921908/228924262-da513e44-42db-45fb-bf36-169ba6ac0bdc.jpg)

output 4 (PIL)
![bus](https://user-images.githubusercontent.com/51921908/228924315-c5aeeca7-732d-4fc7-ab7d-30d63fa33ce9.jpg)

Configuration
```
`Ultralytics YOLOv8.0.58 🚀 Python-3.9.15 torch-1.13.0 CUDA:0 (NVIDIA GeForce RTX 3080, 10002MiB)
Setup complete ✅ (24 CPUs, 31.3 GB RAM, 455.1/456.4 GB disk)
```

**Comment by pderrenger** [comment]
@MiksVasiljevs hi there! Thanks for reaching out with your question.

When using YOLOv8 for prediction on images loaded with OpenCV, it's important to note that images are expected to be in RGB format. The model internally handles the conversion from BGR to RGB, so there's no need to manually switch the color channels when using OpenCV to load images.

Regarding the model performance on a "large" model appearing to be relatively poor on the sample image, it's essential to keep in mind that the performance can vary depending on the specific characteristics of the image and the model. This could be expected behavior. However, for a detailed analysis, it would be beneficial to conduct further evaluation on a diverse set of images to assess the overall model performance.

If you have additional questions or need further assistance, please feel free to ask!
