### ISSUE TITLE
Batch Processing for .engine models

### ISSUE THREAD

**Issue by rhalder2023** [ultralytics/ultralytics#17541]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, so i wanted to ask if there is some way to pass a list of images to the predict function when im using a .engine model? Because it throws an error when i try to

**Comment by UltralyticsAssistant** [comment]
👋 Hello @rhalder2023, thank you for reaching out to us at Ultralytics 🚀! Your interest in using our tools is much appreciated, and we’re here to help.

For your query regarding batch processing with `.engine` models, I recommend checking out the [Docs](https://docs.ultralytics.com) where many common and specific questions, like handling batch processing, might be already addressed. You might find relevant Python examples particularly useful: [Python](https://docs.ultralytics.com/usage/python/).

If this is a 🐛 bug or technical issue, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) that illustrates the problem so that our team can effectively assist you. This includes the code snippet you are using and any specific error messages you encounter.

To further help you, an Ultralytics engineer will also review your question and provide additional assistance soon.

In the meantime, feel free to join our vibrant Ultralytics community:
- For real-time help and discussions, check out our [Discord](https://ultralytics.com/discord) 🎧.
- For more detailed Q&A, head to [Discourse](https://community.ultralytics.com).
- Explore our [Subreddit](https://reddit.com/r/ultralytics) for broader community interactions.

## Upgrade

Ensure you have the latest version of the `ultralytics` package and all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) installed with a compatible environment. You can update to the latest version with:

```bash
pip install -U ultralytics
```

## Environments

You can run YOLO in the following verified environments:

- **Notebooks** with GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud**: See the [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon Web Services**: Check the [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker**: Refer to the [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

For the latest status updates, the following badge indicates if all CI tests are passing. Green means everything's running smoothly!

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

Your engagement is invaluable to us, and we aim to assist you as swiftly and thoroughly as possible. Stay tuned for more input from our team!

**Comment by Y-T-G** [comment]
You need to export with dynamic=True

**Comment by rhalder2023** [comment]
> You need to export with dynamic=True

I did, but it says some list index out of range or something when i try to pass two image arrays in a list.. I shall recreate and show the error.

**Comment by rhalder2023** [comment]
> You need to export with dynamic=True

return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
[pointcloud_generator_node_two_cameras-2]   File "/home/tai/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 36, in generator_context
[pointcloud_generator_node_two_cameras-1]     return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
[pointcloud_generator_node_two_cameras-1]   File "/home/tai/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 36, in generator_context
[pointcloud_generator_node_two_cameras-2]     response = gen.send(None)
[pointcloud_generator_node_two_cameras-2]   File "/home/tai/.local/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 269, in stream_inference
[pointcloud_generator_node_two_cameras-1]     response = gen.send(None)
[pointcloud_generator_node_two_cameras-1]   File "/home/tai/.local/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 269, in stream_inference
[pointcloud_generator_node_two_cameras-2]     self.results[i].speed = {
[pointcloud_generator_node_two_cameras-2] IndexError: list index out of range
[pointcloud_generator_node_two_cameras-1]     self.results[i].speed = {
[pointcloud_generator_node_two_cameras-1] IndexError: list index out of range

**Comment by Y-T-G** [comment]
What's the code?

**Comment by rhalder2023** [comment]
> What's the code?

its nothing much

preds = self.model.predict(rgb_list, max_det = 20, retina_masks= False,
                                device='0', visualize = False, verbose = False, agnostic_nms=True, imgsz=(480,640), half=False, stream=False)

rgb list is a list of 2 images..

the only thing is, this is in ros2 so im just subscribed to two image topics which are being passed to here

**Comment by Y-T-G** [comment]
What's the shape of the image array?

**Comment by rhalder2023** [comment]
> What's the shape of the image array?

480x640

**Comment by rhalder2023** [comment]
> What's the shape of the image array?

i mean it works fine on a single image

**Comment by Y-T-G** [comment]
That's not the shape. I mean the output of running `img.shape`

**Comment by rhalder2023** [comment]
> , max_det = 20, retina_masks= False, device='0', visualize = False, verbose = False, agnostic_nms=True, imgsz=(480,640), half=False, stream=False)

I recreated it outside ros so that its easier to explain, my error btw:

![image](https://github.com/user-attachments/assets/be075ed0-99ee-4bd1-a94b-ad45d32f7af5)

**Comment by rhalder2023** [comment]
[11/15/2024-10:26:51] [TRT] [I] Loaded engine size: 55 MiB
[11/15/2024-10:26:51] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +628, now: CPU 0, GPU 680 (MiB)
[11/15/2024-10:26:51] [TRT] [E] IExecutionContext::setInputShape: Error Code 3: API Usage Error (Parameter check failed, condition: engineDims.d[i] == dims.d[i]. Static dimension mismatch while setting input shape for images. Set dimensions are [2,3,480,640]. Expected dimensions are [1,3,-1,-1].)


i also got this, i guess why the list index is outta range, because there are no results, but like i had exported it with dynamic = true

**Comment by Y-T-G** [comment]
During export with dynamic, you need to specify batch size

**Comment by rhalder2023** [comment]
> During export with dynamic, you need to specify max batch size

oh ho how do i do that like whats the argument called

**Comment by rhalder2023** [comment]
> > During export with dynamic, you need to specify max batch size
> 
> oh ho how do i do that like whats the argument called

is it batch?

**Comment by rhalder2023** [comment]
> > > During export with dynamic, you need to specify max batch size
> > 
> > 
> > oh ho how do i do that like whats the argument called
>
its dooneeeeeee. thank youuuuuu

**Comment by glenn-jocher** [comment]
You're welcome! Happy to help get your batch processing working with TensorRT.

**Comment by jinqiua** [comment]
> During export with dynamic, you need to specify max batch size

how to set max batch size? when dynamic is True

**Comment by jinqiua** [comment]
> @jinqiua to set the max batch size when using dynamic=True during export, use the `batch` argument and specify the desired maximum value. For example, set `batch=2` for a maximum batch size of 2.

when i set 'batch=1', There will still be a tensorrt warning reminding me that I need to set maxbatch

**Comment by glenn-jocher** [comment]
@jinqiua when exporting with TensorRT and `dynamic=True`, ensure you're setting the `max_batch_size` argument in the export command to avoid warnings. This is separate from the `batch` argument.

**Comment by jinqiua** [comment]
> @jinqiua when exporting with TensorRT and `dynamic=True`, ensure you're setting the `max_batch_size` argument in the export command to avoid warnings. This is separate from the `batch` argument.

there is not a param named `max_batch_size`
![image](https://github.com/user-attachments/assets/056f41aa-f31a-46c1-83c9-b54fab63ca48)

**Comment by jinqiua** [comment]
> @jinqiua If you are using `batch=1`, it will show that warning because it's expecting larger batch size with dynamic. Usually when you use dynamic, you want to use inference multiple images, not just 1.

no no no. I just want used diff W or H ,not batch. My batch always ==1

**Comment by Y-T-G** [comment]
You can ignore the warning
