### ISSUE TITLE
Yolov8 Segmentation tensor only Zero

### ISSUE THREAD

**Issue by JaBu3001** [ultralytics/ultralytics#1762]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I want to use my Custom Segmentation Model on my images. But when I do this, the result I get back is this:
tensor([[[0., 0., 0., ..., 0., 0., 0,]
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]]),.  
Why do I get only 0 as return value and if I use 'save_txt' normal values? 

This is my code: 
smallPicKartePath = r'smallpicKarte5.png'
modelName = r'seg.pt'
modelSegmentation = YOLO(modelname)  
results = modelSegmentation.predict(source=smallPicKartePath, save_txt=True)
print(results)

**Comment by glenn-jocher** [comment]
@JackWhite34, thank you for your question! The issue you are experiencing might be related to the fact that you are using `save_txt=True`. This parameter saves the segmentation results to a txt file instead of returning them directly, which may have different formatting than what you expect. 

If you want to see the segmentation results as numerical values, try using `save_txt=False` or evaluating the returned object directly (e.g. `results[0]`). 

Additionally, make sure that your model is trained and able to produce meaningful segmentation results. If the model is not properly trained, it may predict only zeros as segmentation masks, which would explain the output you are seeing.

**Comment by JaBu3001** [comment]
Solution for not getting only Zero in mask is using : results[0].masks.segments

**Comment by JaBu3001** [comment]
Solution for not getting only Zero in mask is using : results[0].masks.segments

**Comment by glenn-jocher** [comment]
@JackWhite34, thank you for your update! It's great to hear that you found a solution. 

To clarify, accessing `results[0].masks.segments` allows you to retrieve the formatted output of the segmentation mask. This is the recommended way to access the segmentation results directly, as it provides a better representation of the segments detected by the model.

Please don't hesitate to reach out if you have any further questions or issues with YOLOv8.
