### ISSUE TITLE
Trouble implementing on Raspberry pi 4 with Ubuntu 20.04

### ISSUE THREAD

**Issue by cdram09** [ultralytics/ultralytics#1773]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I was able to successfully use Yolov8 on multiple computers now, but when trying to implement it on the raspberry pi 4 with Ubuntu 20.04, I get errors that say Illegal Instruction(Core Dumped)
I am using the pip install method from the documentation, and using the pytorch configuration of : 
stable(2.0.0)
Linux
Pip
Python
CPU
Does anyone know what I am doing wrong? Im assuming that the pytorch is made for x86 and not Arm 64 bit ? But Im not sure

**Comment by glenn-jocher** [comment]
@cdram09 yes, pre-built PyTorch binaries installed through pip are generally built for x86 and not for ARM64, which is the architecture used in Raspberry Pi 4. This could be the reason behind the "Illegal Instruction (Core Dumped)" error.

To resolve this issue, you can try the following:

Install PyTorch from source: To get PyTorch working on the Raspberry Pi 4 with Ubuntu 20.04, you might need to compile it from source, specifically targeting the ARM64 architecture. This can be a time-consuming and resource-intensive process, but it ensures that the library is built for the correct architecture. Follow the official PyTorch installation guide for building from source: https://github.com/pytorch/pytorch#from-source

Use PyTorch alternatives: Since running YOLOv8 with PyTorch on a Raspberry Pi 4 can be computationally intensive, you may consider using other lightweight deep learning frameworks that are optimized for edge devices, such as TensorFlow Lite or ONNX Runtime. You can convert your YOLOv8 model to the appropriate format and use these frameworks to run inference on your Raspberry Pi 4.

Use a different edge device: If the performance on the Raspberry Pi 4 is still not satisfactory after trying the above options, you might want to consider using a more powerful edge device, such as the NVIDIA Jetson series (e.g., Jetson Nano, Jetson Xavier NX) or Google Coral Dev Board. These devices are specifically designed for running AI applications on the edge and have dedicated hardware accelerators for running deep learning models.

Remember that running YOLOv8 on a Raspberry Pi 4 might still be limited in terms of performance due to its relatively low computational power.
