### ISSUE TITLE
How to get the whole mask point in the result🤔

### ISSUE THREAD

**Issue by Vang-z** [ultralytics/ultralytics#17880]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I trained a YOLO [Ultralytics v8.3.32] model to segment light strips and got pretty solid results, as you can see below. 

![Snipaste_2024-11-29_19-53-39](https://github.com/user-attachments/assets/3e59f80d-3466-41f6-b9d6-09b44084e6f1)

That said, I’m trying to extract all the mask points from the results to get the exact coordinates of the lines, but I noticed the mask output seems incomplete. 

![Snipaste_2024-11-29_19-54-37](https://github.com/user-attachments/assets/541be4d7-a494-4d21-964d-d31db284cb7d)

Is there a way to directly get the full set of mask coordinates? My code is below, thanks in advance to anyone who can help🌈

```python
from ultralytics import YOLO
from pathlib import Path
import cv2

if __name__ == '__main__':
    BASE_PATH = Path.cwd()
    model = YOLO(f'{BASE_PATH}/runs/segment/train13/weights/best.pt')

    results = model(["./images/0.png"], retina_masks=True, mask_ratio=1)

    for result in results:
        boxes = result.boxes
        print("=" * 60)
        print(boxes)
        print("=" * 60)
        masks = result.masks
        print("=" * 60)
        print(masks)
        print("=" * 60)
        result.show()

        print(masks.xy)
        pixel_coords = masks.xy[0]
        print(pixel_coords)
        frame = result[0].plot()
        for coord in pixel_coords:
            print(coord)
            x, y = coord
            cv2.circle(frame, (int(x), int(y)), radius=2, color=(0, 0, 255), thickness=-1)
        cv2.imshow("Image", frame)
        cv2.waitKey(0)
        cv2.destroyAllWindows()

```

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Vang-z, thank you for sharing your question and your interest in Ultralytics 🚀! Your setup and code look great, and congrats on the compelling segmentation results 💪. 

We recommend checking out the [Ultralytics Documentation](https://docs.ultralytics.com) for additional details on segmentation modes and methods, where you’ll find valuable information and examples. 

For a deeper dive into YOLO's segmentation capabilities, you can explore the [Python API Usage](https://docs.ultralytics.com/usage/python/) section. It may clarify any questions about obtaining specific outputs like precise mask points.

Since this could be related to 🐛 **mask output behavior**, please provide a [minimum reproducible example (MRE)](https://docs.ultralytics.com/help/minimum_reproducible_example/) to allow us to pinpoint the challenge. It would also be helpful if you could share:
- Example input images
- The expected/desired type of mask output
- Any specific observations about why the mask seems incomplete

Additionally, ensure that you are using the latest version of the `ultralytics` package. To upgrade, run the following command in your Python environment:

```bash
pip install -U ultralytics
```

Please double-check compatibility with the [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) and ensure the use of a [**Python>=3.8**](https://www.python.org/) environment.

## Environments

If you’d like to test in a fresh environment, YOLO is supported in various setups:
- **Notebooks** with free GPU access:
  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a>
  <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
  <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- Platforms like [Google Cloud](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) and [AWS](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- [Docker Images](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/): <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Let’s get you unstuck! An Ultralytics engineer will review your query soon and provide further insights. Thank you again for your patience and enthusiasm 😊.

**Comment by Y-T-G** [comment]
You can access the pixel masks with `result.masks.data`.

And you can add `retina_masks=True` to `model.predict()` to make it more accurate.

**Comment by Vang-z** [comment]
> You can access the pixel masks with `result.masks.data`.
> 
> And you can add `retina_masks=True` to `model.predict()` to make it more accurate.

it works perfectly😄 Thank you so much for solving my problem🎉

**Comment by glenn-jocher** [comment]
@Vang-z you're welcome! Glad it worked for you—credit goes to the Ultralytics team and community for making such solutions possible. Let us know if you have any other questions!
