### ISSUE TITLE
When x1, y1, x2, y2 are all integers, the output of ultralytics.utils.ops.xywhn2xyxy is always an array with elements of 0

### ISSUE THREAD

**Issue by ZerefDcc** [ultralytics/ultralytics#18043]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

![image](https://github.com/user-attachments/assets/e64c4077-bf03-43cc-8c4a-461917514489)
```python
import numpy as np
from ultralytics.utils.ops import xyxy2xywhn

x = np.array([0, 0, 20, 20])
w=40
h=40
print(xyxy2xywhn(x, w, h,clip=False, eps=0.0))
```

I think the issue might be with np.empty_like. When the input to np.empty_like is of type int, any subsequent modifications to it will be forcefully converted to int. the results are only correct when x1, y1, x2, and y2 are floating-point numbers.
![image](https://github.com/user-attachments/assets/1c125304-4bdc-41a8-8184-6dec1b8b5e45)

### Environment

Ultralytics YOLOv8.2.1 🚀 Python-3.9.20 torch-2.2.2 CPU (Intel Core(TM) i5-1038NG7 2.00GHz)
Setup complete ✅ (8 CPUs, 16.0 GB RAM, 439.9/465.6 GB disk)

OS                  macOS-15.1.1-x86_64-i386-64bit
Environment         Darwin
Python              3.9.20
Install             pip
RAM                 16.00 GB
CPU                 Intel Core(TM) i5-1038NG7 2.00GHz
CUDA                None

matplotlib          ✅ 3.7.1>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.2.2>=1.8.0
torchvision         ✅ 0.17.2>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 6.1.0
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.2.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0

### Minimal Reproducible Example

```python
import numpy as np
from ultralytics.utils.ops import xyxy2xywhn

x = np.array([0, 0, 20, 20])
w=40
h=40
print(xyxy2xywhn(x, w, h,clip=False, eps=0.0))
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @ZerefDcc, thank you for bringing this to our attention 🚀! We greatly appreciate your detailed bug report with the code snippet and environment details — very helpful!

We recommend taking the following steps to ensure your issue can be effectively addressed:

- Please confirm you're using the latest version of the `ultralytics` package. You can upgrade your installation with:
```bash
pip install -U ultralytics
```

- Verify that all requirements are correctly installed in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/). For reference, you can find the full list of [requirements here](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml).

- For 🐛 bug reports like this, providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) is crucial. Thank you for including a reproducible script! Could you verify whether the issue persists with different input types (e.g., float values) or if any changes occur after the upgrade? This will help narrow down the root cause of the issue.

In the meantime, our engineering team will review the issue, and someone will follow up with you soon. If you'd like to discuss issues or solutions further with the broader community, feel free to join us on:

- [Discord](https://discord.com/invite/ultralytics) 🎧
- [Discourse](https://community.ultralytics.com)
- [Subreddit](https://reddit.com/r/Ultralytics)

## Environments

If you’d like to try debugging or testing on a different environment, you can use any of the following ready-to-use options:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, it indicates that all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are passing, ensuring functionality across macOS, Windows, and Ubuntu.

Thank you again for contributing! This response is automated to help streamline support, but rest assured that a team member will review and assist further soon ✨

**Comment by glenn-jocher** [comment]
@ZerefDcc thank you for your detailed analysis and code snippet! You are correct that `np.empty_like` retains the data type of the input array, which could lead to unintended behaviors when using integer inputs. A workaround is to convert the input array to `float` before processing, as floating-point operations are required for correct normalization:

```python
import numpy as np
from ultralytics.utils.ops import xyxy2xywhn

x = np.array([0, 0, 20, 20], dtype=float)  # Ensure dtype is float
w = 40
h = 40
print(xyxy2xywhn(x, w, h, clip=False, eps=0.0))
```

We appreciate your feedback and will review this behavior internally for potential improvements. If you'd like to contribute further, feel free to submit a PR to suggest updates. Let us know if you have any further questions!
