### ISSUE TITLE
Using 'mps' - view size is not compatible with input tensor's size and stride. Use .reshape(...) instead

### ISSUE THREAD

**Issue by FeherF** [ultralytics/ultralytics#18184]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train

### Bug

```
model = YOLO("yolo11n-seg.pt")

results = model.train(
    data=dataset_yaml,  
    epochs=100,          
    imgsz=1080,         
    batch=32,           
    name=project_dir,  
    exist_ok=True,
    task="segment",
    device = "mps"
)
```

It works perfectly fine with `device = "cpu"`. But If I try to use `mps` with Mac M3 pro I get:

```
Traceback (most recent call last):
  
    results = model.train(
              ^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/ultralytics/engine/model.py", line 802, in train
    self.trainer.train()
  File "/opt/miniconda3/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 207, in train
    self._do_train(world_size)
  File "/opt/miniconda3/lib/python3.12/site-packages/ultralytics/engine/trainer.py", line 393, in _do_train
    self.scaler.scale(self.loss).backward()
  File "/opt/miniconda3/lib/python3.12/site-packages/torch/_tensor.py", line 581, in backward
    torch.autograd.backward(
  File "/opt/miniconda3/lib/python3.12/site-packages/torch/autograd/__init__.py", line 347, in backward
    _engine_run_backward(
  File "/opt/miniconda3/lib/python3.12/site-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
         
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```

Pytorch installation is fine and tested. 

### Environment

Ultralytics 8.3.10 🚀 Python-3.12.2 torch-2.5.1 CPU (Apple M3 Pro)
Setup complete ✅ (12 CPUs, 18.0 GB RAM, 625.3/926.4 GB disk)

OS                  macOS-15.1.1-arm64-arm-64bit
Environment         Darwin
Python              3.12.2
Install             pip
RAM                 18.00 GB
Disk                625.3/926.4 GB
CPU                 Apple M3 Pro
CPU count           12
GPU                 None
GPU count           None
CUDA                None

numpy               ✅ 2.0.2>=1.23.0
matplotlib          ✅ 3.9.2>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 9.5.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.1>=1.4.1
torch               ✅ 2.5.1>=1.8.0
torchvision         ✅ 0.20.1>=0.9.0
tqdm                ✅ 4.66.6>=4.64.0
psutil              ✅ 6.1.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.9>=2.0.0
torch               ✅ 2.5.1!=2.4.0,>=1.8.0; sys_platform == "win32"

### Minimal Reproducible Example

model = YOLO("yolo11n-seg.pt")

results = model.train(
    data=dataset_yaml,  
    epochs=100,          
    imgsz=1080,         
    batch=32,           
    name=project_dir,  
    exist_ok=True,
    task="segment",
    device = "mps"
)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @FeherF, thank you for sharing your issue and interest in Ultralytics 🚀! We have received your report, and an Ultralytics engineer will assist you shortly.

In the meantime, we recommend the following steps to help us diagnose the issue:

### 🐛 Bug Report
Please ensure that you provide a [minimum reproducible example (MRE)](https://docs.ultralytics.com/help/minimum_reproducible_example/) for the reported bug. While your provided code is helpful, specifying the exact `dataset_yaml` file and other custom variables such as `project_dir` would allow us to replicate the issue more effectively.

### Helpful Instructions
If not done already, please confirm the following:
- You are using the latest `ultralytics` package. Ensure your installation is fully up-to-date by running:
  ```bash
  pip install -U ultralytics
  ```
- Verify the issue occurs in an environment that meets our [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml), particularly with [PyTorch](https://pytorch.org/) >= 1.8 and [Python](https://www.python.org/) >= 3.8.
- If the issue is specific to the MPS (Metal Performance Shaders) backend, note that PyTorch's support for MPS is still evolving. Some issues with MPS may originate within PyTorch itself.

### Resources
While waiting, feel free to browse our comprehensive [Documentation](https://docs.ultralytics.com). Check out:
- [Python usage examples](https://docs.ultralytics.com/usage/python/)
- [Command-line interface (CLI)](https://docs.ultralytics.com/usage/cli/)
- Plus, some great [training tips](https://docs.ultralytics.com/guides/model-training-tips/) to optimize your results.

### Community Support
For real-time discussions, connect with the Ultralytics community:
- [Discord](https://discord.com/invite/ultralytics) 🎧 for live chat
- [Discourse](https://community.ultralytics.com) for focused technical threads
- [Subreddit](https://reddit.com/r/Ultralytics) for community-driven discussions

### Verified Environments
If you'd like to test your workflow in another environment to rule out system-specific bugs, try one of our preconfigured environments for YOLO with free GPUs:
- <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a>
- <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

### Status Update
All [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently:
<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>. These tests validate YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) daily and with every commit.

We appreciate your patience as we look into this 🚀!

**Comment by Y-T-G** [comment]
It's a PyTorch bug.

https://github.com/ultralytics/ultralytics/issues/17168#issuecomment-2444805400
