### ISSUE TITLE
Yolov11n conversion to TensorFlow Lite INT8 detect no object in any image 

### ISSUE THREAD

**Issue by gio-stanga** [ultralytics/ultralytics#18210]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict, Export

### Bug

when converting Yolov11n to TensorFlow Lite yolo11n_float32.tflite works just fine and is able to detect objects but yolo11n_full_integer_quant.tflite compute without finding any object in any image, I've tried with both data="coco8.yaml" and data="coco128.yaml" and it does not work either way.

I tried to print the numerical output, and for the first blocks of 84 it is a strictly increasing sequence (as you can see int the graph) while for all the others it is constant and equal to the output zero point value (122 in my case).

I've also added some structure information in the second image where you can see the scale and zero point of both input (scale ~ 0.003922, zero-point = 128) and output (scale ~ 0.004078, zero-point = 122) 

![PHOTO-2024-12-12-08-31-23](https://github.com/user-attachments/assets/ad372f83-c11f-4983-84d4-8017fbfd7fad)
<img width="376" alt="Screenshot 2024-12-12 at 16 40 59" src="https://github.com/user-attachments/assets/e3ea9d71-e0fb-4566-bf24-fffd2b838f63" />

### Environment

```
Ultralytics 8.3.48 🚀 Python-3.8.20 torch-2.4.1 CPU (Apple M1 Pro)
Setup complete ✅ (10 CPUs, 16.0 GB RAM, 218.4/460.4 GB disk)

OS                  macOS-15.1.1-arm64-arm-64bit
Environment         Darwin
Python              3.8.20
Install             pip
RAM                 16.00 GB
Disk                218.4/460.4 GB
CPU                 Apple M1 Pro
CPU count           10
GPU                 None
GPU count           None
CUDA                None

numpy               ✅ 1.23.5>=1.23.0
numpy               ✅ 1.23.5<2.0.0; sys_platform == "darwin"
matplotlib          ✅ 3.7.5>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.4.1>=1.8.0
torch               ✅ 2.4.1!=2.4.0,>=1.8.0; sys_platform == "win32"
torchvision         ✅ 0.19.1>=0.9.0
tqdm                ✅ 4.67.1>=4.64.0
psutil              ✅ 6.1.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.13>=2.0.0
```

### Minimal Reproducible Example

```
from ultralytics import YOLO

model = YOLO("yolo11n.pt")
model.export(format="tflite", int8=True, data="coco8.yaml")

```

### Additional

I would appreciate it if you could tell me how to fix this, but even just providing some information or indicating where the issue might be would be very helpful, maybe I could do something about it

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
👋 Hello @gio-stanga, thank you for your detailed report and for your interest in Ultralytics 🚀! We appreciate the time you've taken to provide context, screenshots, and your environment details.

If this is a 🐛 Bug Report, it would be very helpful if you could share a [minimum reproducible example (MRE)](https://docs.ultralytics.com/help/minimum_reproducible_example/) that demonstrates the issue. From your description, it seems you may already have provided this, but please ensure your code snippet replicates the behavior in a clean, isolated setup.

For your TensorFlow Lite INT8 issue, ensure that:
1. You have the latest version of the `ultralytics` package installed and all dependencies up-to-date:
   ```bash
   pip install -U ultralytics
   ```
2. You follow the tips on TensorFlow Lite export from our [Export Documentation](https://docs.ultralytics.com/modes/export/).

For clarification or extended debugging:
- Are you observing the issue across all images or specific cases?
- Could you share more details about the quantization workflow? E.g., specifics of data used for calibration in INT8 export.

While we appreciate your offer to submit a PR 👍, identifying the root cause here will require further investigation. An Ultralytics engineer will review your issue shortly and provide more targeted assistance.

In the meantime, feel free to explore and connect with the Ultralytics community for quick feedback:
- Join real-time discussions on [Discord](https://discord.com/invite/ultralytics) 🎧.
- Dive into long-form threads on [Discourse](https://community.ultralytics.com) or [Reddit](https://reddit.com/r/Ultralytics) to share ideas and learn more.

## Verified Environments

YOLO models, including TensorFlow Lite exports, are tested across diverse setups. To accelerate debugging, you might test your workflow in one of the preconfigured environments:
- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Docker Image** for clean environments: See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for your patience, and rest assured we'll give this issue the attention it requires. 😊
