### ISSUE TITLE
Warning generated by YOLOV8 training

### ISSUE THREAD

**Issue by sxl845414442** [ultralytics/ultralytics#1859]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I was using Python for training, I encountered a problem called 'WARNING no model scale passed. Assuming scale='s''. May I know the reason for this
![QQ截图20230406095701](https://user-images.githubusercontent.com/127416177/230253208-9d9f6070-e89c-43c9-80d7-487894ced6af.png)
![QQ截图20230406095722](https://user-images.githubusercontent.com/127416177/230253209-3e46d8a1-a4b1-41ff-9a75-878363340755.png)

**Comment by AyushExel** [comment]
Does your yolov7_att.yaml contain the `scale` key?

**Comment by sxl845414442** [comment]
> 

Thank you for your answer, but I am not sure what the key is. Below is my yaml file, and I have only added line 27
![QQ截图20230408104300](https://user-images.githubusercontent.com/127416177/230699877-db8b81ee-41be-47c1-99d8-66ecfb7fd526.png)

**Comment by glenn-jocher** [comment]
@sxl845414442, the `scale` key is a required entry for YOLOv8 models in the latest configuration schema. It allows the model to resize to different scales (sizes) that can help to fit different scenarios with varying hardware resources or object detection requirements. 
In your case, it's missing from the YOLOv7_Attention.yaml file that might be causing the warning. 
For a quick fix, you can add `scale: 0.5` to the bottom of the config file, just above the `nc` option. The scale value can range from 0.1 to 1, with 1 being the largest model size. Remember to update your training the cmd/terminal and and model instance after the update.

**Comment by Sanjib-ac** [comment]
Getting same warning : WARNING ⚠️ no model scale passed. Assuming scale='n'.
CLI: yolo detect train data=visionDemo.yaml model=YOLOv8x.yaml epochs=600 imgsz=640 device=mps optimizer=Adam  project=visionDemo name=vdYolov8x

How to fix the issue? I don't see any scale argument.

**Comment by glenn-jocher** [comment]
@Sanjib-ac thank you for bringing this issue to our attention. The warning message "WARNING ⚠️ no model scale passed. Assuming scale='n'" is triggered when the scale argument is not explicitly defined in the command line interface (CLI) or the configuration file.

To fix this issue, you need to add the scale argument to your CLI command or configuration file. The scale argument allows you to choose the desired scale (size) for your YOLOv8 model. You can choose from different scales such as 's', 'm', 'l', 'x', or 'c' depending on your specific requirements.

For example, if you want to use the 'x' scale, you can add the scale argument to your command like this:
`yolo detect train data=visionDemo.yaml model=YOLOv8x.yaml epochs=600 imgsz=640 device=mps optimizer=Adam project=visionDemo name=vdYolov8x scale=x`

By explicitly specifying the scale argument, you can ensure that the model is correctly initialized with the desired scale.

I hope this explanation helps you resolve the issue. If you have any further questions or need any additional assistance, please feel free to ask.

**Comment by Sanjib-ac** [comment]
@glenn-jocher thanks for your reply. After adding the scale argument, getting the following type error:
`TypeError: 'scale=x' is of invalid type str. Valid 'scale' types are int (i.e. 'scale=0') or float (i.e. 'scale=0.5')`

CLI arguments:
`yolo detect train data=visionDemo.yaml model=YOLOv8x.yaml epochs=600 imgsz=640 device=mps optimizer=Adam project=visionDemo name=vdYolov8x scale=x`

if I pass `scale= 1.0`, it produces the same warning : `WARNING ⚠️ no model scale passed. Assuming scale='n'.`
Thanks.

**Comment by 2213766112** [comment]
> 感谢您提请我们注意这个问题。警告消息“警告⚠️未通过模型比例。假设 scale='n'“ 在命令行界面 （CLI） 或配置文件中未显式定义时触发。
> 
> 要解决此问题，您需要将 scale 参数添加到 CLI 命令或配置文件中。scale 参数允许您为 YOLOv8 模型选择所需的比例（大小）。您可以根据您的具体要求从不同的音阶中进行选择，例如“s”、“m”、“l”、“x”或“c”。
> 
> 例如，如果要使用“x”刻度，可以将刻度参数添加到命令中，如下所示： `yolo detect train data=visionDemo.yaml model=YOLOv8x.yaml epochs=600 imgsz=640 device=mps optimizer=Adam project=visionDemo name=vdYolov8x scale=x`
> 
> 通过显式指定 scale 参数，可以确保使用所需的 scale 正确初始化模型。
> 
> 我希望这个解释能帮助你解决这个问题。如果您有任何其他问题或需要任何其他帮助，请随时提问。



> 感谢您提请我们注意这个问题。警告消息“警告⚠️未通过模型比例。假设 scale='n'“ 在命令行界面 （CLI） 或配置文件中未显式定义时触发。
> 
> 要解决此问题，您需要将 scale 参数添加到 CLI 命令或配置文件中。scale 参数允许您为 YOLOv8 模型选择所需的比例（大小）。您可以根据您的具体要求从不同的音阶中进行选择，例如“s”、“m”、“l”、“x”或“c”。
> 
> 例如，如果要使用“x”刻度，可以将刻度参数添加到命令中，如下所示： `yolo detect train data=visionDemo.yaml model=YOLOv8x.yaml epochs=600 imgsz=640 device=mps optimizer=Adam project=visionDemo name=vdYolov8x scale=x`
> 
> 通过显式指定 scale 参数，可以确保使用所需的 scale 正确初始化模型。
> 
> 我希望这个解释能帮助你解决这个问题。如果您有任何其他问题或需要任何其他帮助，请随时提问。




查阅文档后scale参数为超参数中的 并不能解决
scale | float | 0.5 | >=0.0 | 通过增益因子缩放图像，模拟物体与摄像机的不同距离。

**Comment by glenn-jocher** [comment]
抱歉给您带来了困惑和不便 🙇‍♂️。关于 `scale` 参数的警告信息，看起来我们有些混淆。实际上，警告中提到的 `scale` 与模型大小并非直接相关。它与数据增强有关，特别是在训练过程中用来调整输入图像的比例。

当前版本的 YOLOv8 CLI 似乎不直接支持通过 CLI 传入模型规模参数。如果您在使用 `yolo detect train` 命令且遇到关于 `scale` 的警告，您可能需要检查您的模型配置文件（例如 `YOLOv8x.yaml`），确保里面的设置正确无误。

如果仍然收到关于模型 `scale` 的警告，可以考虑更新您的 YOLOv8 或 Ultralytics 仓库到最新版本，看看是否有相关的修复。同时，我建议您持续关注 GitHub 上的更新和文档，以获取最新的信息和解决方案。

此外，对于您提到的 `scale` 超参数（用于图像增益），确实是一个与数据增强相关的设置，用于训练时调节图像大小，而非指定模型大小。

希望这能有所帮助！如果还有其他问题或疑惑，请随时告知。我们很乐意帮助您解决。再次感谢您的支持和理解！🙂

**Comment by Github121gsl** [comment]
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

**Comment by glenn-jocher** [comment]
Hey there! 👋 It looks like you've encountered an issue due to multiple OpenMP runtimes being active at the same time. This can happen in environments where libraries or frameworks internally use different versions of the OpenMP library, leading to conflicts.

A quick workaround, as mentioned in your error message, is to set the environment variable `KMP_DUPLICATE_LIB_OK=TRUE`. You can do this in your terminal or command prompt before running your script, like so:

For Linux/macOS:
```bash
export KMP_DUPLICATE_LIB_OK=TRUE
```

For Windows:
```cmd
set KMP_DUPLICATE_LIB_OK=TRUE
```

However, please note that this is more of a temporary fix and could potentially mask underlying issues. It's always good practice to check your dependencies and try to ensure that only one version of the OpenMP runtime is being used by your application.

Hope that helps! Let us know if there's anything else we can assist you with. Happy coding! 😊
