### ISSUE TITLE
AzureML Notebook Train Error: 'last.pt already exists'

### ISSUE THREAD

**Issue by gerardsmith** [ultralytics/ultralytics#1865]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Using AzureML Notebook, Train runs for two epochs, however, when ending the second epoch an error occurs I assume when attempting to update the last.pt model weights:

"/anaconda/envs/azureml_py38/lib/python3.8/site-packages/azureml/mlflow/_client/artifact/run_artifact_client.py", line 148, in _create_empty_artifacts
    raise Exception("\n".join(error_messages))
Exception: UserError: Resource Conflict: ArtifactId ExperimentRun/dcid.902c1ce4-90df-4fb7-a4ba-ee567a071ae6/last.pt already exists.

### Environment

Ultralytics YOLOv8.0.66 🚀 Python-3.8.10 torch-1.8.1+cu102 CUDA:0 (Tesla K80, 11441MiB)
AzureML Notebook

### Minimal Reproducible Example

import ultralytics

!yolo train model=yolov8x.pt batch=-1 data=vd_match_X.yaml epochs=40 imgsz=640

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hi @juliealvarez, thank you for reporting this issue! It seems that the problem comes from a conflict in the artifact Id; this can happen when there are artifacts with the same Id. A possible solution might be to rename one of them, or to delete the unnecessary artifacts. If you need further assistance, you can refer to the [AzureML docs](https://docs.microsoft.com/azure/machine-learning/service/how-to-manage-runs#view-and-delete-artifacts-in-a-run) for more information about managing AzureML run artifacts.

**Comment by glenn-jocher** [comment]
@gerardsmith the error may simply be due to attempting to save a file which already exists. If you create a file in your notebook, and then save another file with the same name, do you get an error?

**Comment by gerardsmith** [comment]
Hi @glenn-jocher

Yes agreed but I think the issue lies in the Azureml experiment not the local weights. Is there a method to block yolov8 from creating an Azureml experiment and logging updates to the model weight in the experiment, during the training process? 

Alternatively, is there a way to append a time stamp to the model weights last.pt upon saving?

**Comment by glenn-jocher** [comment]
@gerardsmith yes, it seems that the issue is with the Azureml experiment and its logging process. One possible solution is to block YOLOv8 from creating an Azureml experiment and logging updates to the model weight in the experiment during the training process. Alternatively, appending a time stamp to the model weights last.pt upon saving can also help avoid overwriting existing files and errors. Both solutions require changes to the YOLOv8 source code or the training script used to run the model.

**Comment by gerardsmith** [comment]
Thanks @glenn-jocher any plans to incorporate a fix in the next release?

**Comment by glenn-jocher** [comment]
@gerardsmith as an AI language model, I do not maintain or develop software releases. However, the YOLOv8 development team may consider implementing a fix to address the issue of creating duplicate files and errors while saving model weights during training. Additionally, appending a time stamp to the file name of the saved weights is a simple solution to avoid overwriting existing files and errors while training the model.

**Comment by Denizzje** [comment]
I think @glenn-jocher might want to consider running this AI script answering questions on a seperate account, unless he accidently turned himself into a GPT model 🤣 .

**Comment by Esmeralda2001** [comment]
I am running into the same issue, how do I even access the site packages in ML Azure so I can edit the code?

**Comment by glenn-jocher** [comment]
@Esmeralda2001 to edit the code in the site-packages while using Azure Machine Learning, you can create a conda environment and install the required packages within it. Once you have created the environment, you can activate it and make changes to the code within the environment. This allows you to easily switch between environments with different packages installed and manage package dependencies. If you need to make changes to the site-packages themselves, you can also create a custom Docker image that includes the modified site-packages and use that image in the Azure Machine Learning workspace.

**Comment by gerardsmith** [comment]
A workaround is using an older version of the Ultralytics library:

!pip install ultralytics==8.0.50

**Comment by glenn-jocher** [comment]
@gerardsmith it appears that there is a workaround for the issue with Azure Machine Learning by using an older version of the Ultralytics library. The specific version suggested for installation is ultralytics 8.0.50. By installing this version rather than the latest version, the issue with the Azureml experiment and logging process may be avoided. This is a potential solution for those encountering errors and wanting to avoid more complex modifications to the YOLOv8 source code or training script.

**Comment by ouphi** [comment]
@gerardsmith the bug [has been fixed](https://github.com/ultralytics/ultralytics/pull/2124) in the latest version `8.0.83`. Could you please confirm if the solution works for you so that we can proceed with closing the issue?
