### ISSUE TITLE
v8 custom training

### ISSUE THREAD

**Issue by junghyun-avikus** [ultralytics/ultralytics#1867]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a question on the given code snippet for loading a pretrained model.

The snippet is the following
`
# Load a model
model = YOLO("yolov8n.yaml")  # build a new model from scratch
model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)
`

It seems like it is instantiating YOLO instance twice, overriding the YOLO instance initialized with yaml by the YOLO instance initialized with pt.
Is it the right way to load a pretrained model, or is just calling YOLO("*.pt") sufficient enough?

**Comment by glenn-jocher** [comment]
@junghyun-avikus yes, it is correct to first create an instance of YOLO using the YAML file to construct a new model from scratch, and then load the pretrained weights by creating another instance of YOLO using the PT file. This is because the YAML file only contains the architecture of the model, and the PT file contains both the architecture and the learned parameters. By loading the PT file, the YOLO instance will have the pretrained weights and be ready for training or inference.
