### ISSUE TITLE
Pytorch version 

### ISSUE THREAD

**Issue by VictorBarbosa** [ultralytics/ultralytics#1899]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi folks,
I am using Yolov8 and i realised when we are using yolo with  the follow libs 
torch:2.0.0
torchvision:0.15.1 
On macbook M1/M2 such as :
yolo classisy train model=./some_model.pt data=./some_data device=mps (mps because M1/M2 hasn`t cuda) the process is really, really faster , but 0 accuracy 
If we change the pytorch version to

torch:1.13.1
torchvision:0.14.1

the precess is really slow but the accuracy is perfect 

Does someone know how can i fix this problem,
I`d like use yolo with torch:2.0 because is faster then 1.3, but it has bad results

**Comment by glenn-jocher** [comment]
Thanks for reaching out with your question, @VictorBarbosa. It sounds like you may be experiencing some compatibility issues with YOLOv8 and your MacBook M1/M2 processor. We recommend checking out the [system requirements](https://ultralytics.com/yolov8#requirements) for YOLOv8 to ensure that your system meets the minimum requirements for optimal performance. 

Additionally, we suggest trying some of the troubleshooting steps outlined in our [documentation](https://docs.ultralytics.com/macos/) for macOS users to see if that resolves the issue.

If you are still experiencing issues, we suggest posting a detailed report in the [issues](https://github.com/ultralytics/ultralytics/issues) section of the GitHub repo with as much information as possible, including your system configuration, as well as any log or error messages you may have received.

We hope this helps, and please don't hesitate to let us know if you have any further questions or concerns.

**Comment by glenn-jocher** [comment]
@VictorBarbosa MPS is working correctly for me with torch 2.0 and latest ultralytics on a Macbook Air M2:

<img width="1276" alt="Screenshot 2023-04-08 at 13 31 48" src="https://user-images.githubusercontent.com/26833433/230718858-19757be4-b88d-443f-b48c-551657a066cf.png">

**Comment by VictorBarbosa** [comment]
@glenn-jocher , I've updated Pytorch to nightly version and everthing is working perfect , thank you

**Comment by glenn-jocher** [comment]
@VictorBarbosa, glad to hear that the issue has been resolved and everything is now working perfectly for you with the updated PyTorch version 👍. It's important to ensure that all software versions being used are compatible with each other to avoid any potential compatibility issues. If you have any further questions or concerns in the future, please don't hesitate to reach out to us.

**Comment by spyhunter1280** [comment]
C:\YOLO\New folder>python export-coreML.py
Ultralytics YOLOv8.0.200  Python-3.10.11 torch-2.0.0+cpu CPU (AMD EPYC 7502P 32-Core Processor)
Model summary (fused): 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs

PyTorch: starting from 'runs\detect\train\weights\best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 5, 8400) (6.0 MB)
Fail to import BlobReader from libmilstoragepython. No module named 'coremltools.libmilstoragepython'
Fail to import BlobWriter from libmilstoragepython. No module named 'coremltools.libmilstoragepython'

CoreML: starting export with coremltools 7.0...
Converting PyTorch Frontend ==> MIL Ops: 100%|█████████████████████████▉| 593/594 [00:00<00:00, 4725.79 ops/s]
Running MIL frontend_pytorch pipeline: 100%|██████████████████████████████| 5/5 [00:00<00:00, 317.71 passes/s]
Running MIL default pipeline: 100%|██████████████████████████████████████| 66/66 [00:01<00:00, 33.00 passes/s]
Running MIL backend_mlprogram pipeline: 100%|███████████████████████████| 12/12 [00:00<00:00, 254.93 passes/s]
CoreML: export failure  5.2s: BlobWriter not loaded
Traceback (most recent call last):
  File "C:\YOLO\New folder\export-coreML.py", line 5, in <module>
    model.export(format='coreml')
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\engine\model.py", line 313, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\engine\exporter.py", line 258, in __call__
    f[4], _ = self.export_coreml()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\engine\exporter.py", line 122, in outer_func
    raise e
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\engine\exporter.py", line 117, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\engine\exporter.py", line 533, in export_coreml
    ct_model = ct.convert(ts,
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\coremltools\converters\_converters_entry.py", line 551, in convert
    mlmodel = mil_convert(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\coremltools\converters\mil\converter.py", line 188, in mil_convert
    return _mil_convert(model, convert_from, convert_to, ConverterRegistry, MLModel, compute_units, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\coremltools\converters\mil\converter.py", line 212, in _mil_convert
    proto, mil_program = mil_convert_to_proto(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\coremltools\converters\mil\converter.py", line 304, in mil_convert_to_proto
    out = backend_converter(prog, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\coremltools\converters\mil\converter.py", line 130, in __call__
    return backend_load(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\coremltools\converters\mil\backend\mil\load.py", line 287, in load
    raise RuntimeError("BlobWriter not loaded")
RuntimeError: BlobWriter not loaded

C:\YOLO\New folder>

**Comment by glenn-jocher** [comment]
@spyhunter1280 hi there,

I'm sorry to hear that you're experiencing this problem. This seems to be a compatibility issue with the module 'coremltools' which is giving a 'BlobWriter not loaded' error and causing the CoreML export process to fail from your Ultralytics YOLOv8 model.

Please ensure that you're using a compatible version of 'coremltools'. Sometimes, newer or older versions of 'coremltools' might not be compatible with the other Python packages you're using.

Also, make sure that the Python version you are using is compatible with your 'coremltools' version. Upgrading or downgrading it might resolve the issue.

If that doesn't work, you might want to consider creating a new virtual environment and installing the requirements again, sometimes certain dependencies might create conflicts.

Furthermore, make sure that the input model 'runs\detect\train\weights\best.pt' is available at the specified path.

Hope this helps! If you continue to experience issues, please provide more specifics about your process and where it seems to fail so we can better assist you.

**Comment by spyhunter1280** [comment]
@glenn-jocher 
Thanks for your consideration
I tried with several ways, but I couldn't
I would be gratefull if you provide me the requirement.txt for coremltools, yolov8?

**Comment by glenn-jocher** [comment]
@spyhunter1280, I understand that troubleshooting these issues can be challenging. While I can't provide a `requirements.txt` file here, I can guide you to ensure your setup is ideally configured.

To create an effective `requirements.txt` for YOLOv8 and `coremltools`, you'll typically want to include the versions of crucial libraries that are known to work well together. However, it's key to note that specific versions that work well can vary depending on your system setup and other installed packages.

Here is how to manage your setup ideally:
1. Create a fresh virtual environment using virtualenv or conda to avoid any package conflicts.
2. Install PyTorch suitable for your system. Since `coremltools` is used for converting to Apple's Core ML format, if you're looking to deploy on iOS devices, ensure that the PyTorch version is compatible with your target iOS version and device.
3. Install the specific version of `coremltools` that is compatible with your version of PyTorch.
4. Install Ultralytics YOLOv8 following the documentation on our official docs page.

You can find the PyTorch compatibility notes in the documentation of `coremltools` or by checking their official GitHub repository's issues for any known conflicts.

Unfortunately, due to the varied nature of development environments, it isn't possible to provide a one-size-fits-all `requirements.txt`. But, ensuring that you are using compatible versions of PyTorch and `coremltools` should set you on the right track.

Lastly, it is crucial to check the YOLOv8 GitHub repository for any specific version requirements for dependencies, as these can be updated regularly with new commits.

Remember to refer to the official Ultralytics documentation for accurate and detailed instructions on setting up and using YOLOv8 for your projects.

Should any specific issues persist, please report them on the GitHub issues page with details about your system setup and the exact steps you took so we can help diagnose and resolve the issue more effectively. 

Keep in mind that software environments are dynamic, and sometimes a bit of trial and error is necessary to find the exact configuration that works for your setup.
