### ISSUE TITLE
Pose Coreml export error

### ISSUE THREAD

**Issue by CDEV500** [ultralytics/ultralytics#1908]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

I'm attempting to export a pose model with CoreML. I've successfully exported to onnx. 

```
    model = YOLO("yolov8n-pose")
    success = model.export(format="coreml")
```

Error
```
    raise ValueError("The updates tensor should have shape {}. Got {}".format(expected_updates_shape, self.updates.shape))
ValueError: The updates tensor should have shape (1, 51, 8400). Got (1, 17, 8400)
```

### Environment

Ultralytics YOLOv8.0.70 🚀 Python-3.10.8 torch-1.13.1 CPU
OS: MacOS M1 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@CloneableDev 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. CoreML YOLOv8n Pose export works correctly for me in Colab. I'm unable to reproduce any issues:

<img width="1397" alt="Screenshot 2023-04-08 at 19 40 12" src="https://user-images.githubusercontent.com/26833433/230735471-7a3e9bff-e798-4cf6-be04-53adb83c7c60.png">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by CloneableDev** [comment]
I just saw this comment in the exporter.py. Is pose pipeline implemented on another branch for coreml?

`# TODO CoreML Segment and Pose model pipelining`

**Comment by CloneableDev** [comment]
This must be my environment, I was able to get the export in collab. I'll see if I can figure out what wrong, post it here and ill close the issue. 

Thank you!

**Comment by glenn-jocher** [comment]
@CloneableDev You're very welcome! I'm glad to have been of help, and I'm confident you'll be able to troubleshoot the export issue on your local environment soon. If you need further assistance or have any other queries, don't hesitate to ask. We'll be happy to help.

**Comment by glenn-jocher** [comment]
> I just saw this comment in the exporter.py. Is pose pipeline implemented on another branch for coreml?
> 
> `# TODO CoreML Segment and Pose model pipelining`

Pose CoreML export with NMS pipelining does not exist (nor does Segment CoreML export with NMS pipelining). If you'd like to help contribute that would be very helpful.

**Comment by ryouchinsa** [comment]
We had the same error when exporting the yolo-pose model to the coreml model.
`yolo pose export model=yolov8n-pose.pt format=coreml`

Updating the coremltools version solved the problem.
`pip install --upgrade coremltools`

Currently the coremltools version is 6.3.0.

**Comment by glenn-jocher** [comment]
@ryouchinsa 👋 It's great to hear that updating your `coremltools` version to 6.3.0 helped solve the problem that you were encountering with YOLO Pose Model export. The issue may have been caused by a compatibility error between the older `coremltools` version that you were using and the version of YOLO that you were attempting to export. Keeping tools, libraries, and frameworks up-to-date with the latest versions can often help avoid these types of compatibility errors. If you have any further questions or need additional support, don't hesitate to reach out to us.

**Comment by CloneableDev** [comment]
> 

Were you able to get the pose in iOS? My understanding is the NMS Pose pipeline is not yet build in the export script

**Comment by ryouchinsa** [comment]
@glenn-jocher, thanks for your support. We will get in touch with you if we have any questions.
@CloneableDev, thanks for your question.

We are developing the macOS app [RectLabel](https://rectlabel.com/) and implementing the code to run the YOLOv8 Pose model on our macOS app.
When we run the exported yolov8n-pose.mlmodel, the result layer shape is [1, 56, 8400].
The 56 includes [x, y, w, h, class_score, x1, y1, v1, ..., x17, y17, v17].
In our objective-c or swift code, we store each candidate if the class_score is more than 0.5.
Then sort candidates in descending order using the class_score.
Using [x, y, w, h], we can obtain the bounding box for each candidate, if the bounding box is overlapping to the bounding box which has higher class_score, the candidate is removed.
This is how we are running NMS in our code.

**Comment by ryouchinsa** [comment]
Kindly, the macOS app developer of [Binary Sports](https://www.binarysports.eu/) asked us how to parse the output layer of YOLOv8 Pose models.

We show the example code using Objective-c.
Please let us know your opinion.

1. Check the MLModel meta data.

```
- (void)setModelMetaData:(id)modelId{
	MLModel* model = modelId;
	MLModelDescription *modelDescription = model.modelDescription;
	NSDictionary *inputDict = modelDescription.inputDescriptionsByName;
	NSArray *inputDictValues = inputDict.allValues;
	MLFeatureDescription *inputFeatureDescription = [inputDictValues objectAtIndex:0];
	MLImageConstraint *imageConstraint = inputFeatureDescription.imageConstraint;
	int inputWidth = (int)imageConstraint.pixelsWide;
	int inputHeight = (int)imageConstraint.pixelsHigh;
	self.inputWidth = inputWidth;   // 640
	self.inputHeight = inputHeight; // 640

	NSDictionary *userDefinedDict = modelDescription.metadata[MLModelCreatorDefinedKey];
	id kptShape = [userDefinedDict objectForKey:@"kpt_shape"];
	if(kptShape != nil){
		NSString *text = kptShape;
	    NSData *data = [text dataUsingEncoding:NSUTF8StringEncoding];
	    NSError *error;
	    NSArray* array = [NSJSONSerialization JSONObjectWithData:data
	                                                     options:0
	                                                       error:&error];
	    self.keypointsNum = [array[0] intValue]; // 17
	    self.keypointsDim = [array[1] intValue]; // 3
	}
}
```

2. Run the MLModel and parse the output layer.
When we run the model, the output layer shape is [1, 56, 8400].
The 56 includes [x, y, w, h, class_score, x1, y1, v1, ..., x17, y17, v17].

```
- (NSMutableArray*)parsePoseYOLOv8:(NSArray*)results{
    NSMutableArray *predictions = [NSMutableArray array];
    VNCoreMLFeatureValueObservation *observation = results[0];
    MLMultiArray *outputArray = observation.featureValue.multiArrayValue;
    int gridHeight = [outputArray.shape[1] intValue]; // 56
    int gridWidth = [outputArray.shape[2] intValue];  // 8400
    int classesNum = gridHeight - 4 - self.keypointsNum * self.keypointsDim; // 1
    float threshold = self.confidenceThreshold; // 0.25
    int inputWidth = self.inputWidth;
    for(int j = 0; j < gridWidth; j++){
        int classIndex = -1;
        float maxScore = 0;
        for(int i = 4; i < 4 + classesNum; i++){
            float score = [outputArray[(i * gridWidth) + j] floatValue];
            if(score > maxScore){
                classIndex = i - 4;
                maxScore = score;
            }
        }
        if(maxScore > threshold){
            float x = [outputArray[(0 * gridWidth) + j] floatValue];
            float y = [outputArray[(1 * gridWidth) + j] floatValue];
            float w = [outputArray[(2 * gridWidth) + j] floatValue];
            float h = [outputArray[(3 * gridWidth) + j] floatValue];
            x -= w / 2;
            y -= h / 2;
            CGRect rect = CGRectMake(x / inputWidth,
                                     1.0 - (y + h) / inputWidth,
                                     w / inputWidth,
                                     h / inputWidth);
            NSMutableArray *pointArray = [NSMutableArray array];
            NSMutableArray *visibleArray = [NSMutableArray array];
            for(int i = 4 + classesNum; i < gridHeight; i += 3){
                float x = [outputArray[((i + 0) * gridWidth) + j] floatValue];
                float y = [outputArray[((i + 1) * gridWidth) + j] floatValue];
                float v = [outputArray[((i + 2) * gridWidth) + j] floatValue];
                NSPoint point = NSMakePoint(x / inputWidth, 1.0 - y / inputWidth);
                int visible = v > 0 ? kVisible : kNotVisibleNotLabeled;
                [pointArray addObject:[NSValue valueWithPoint:point]];
                [visibleArray addObject:[NSNumber numberWithInt:visible]];
            }
            Prediction *prediction = [[Prediction alloc] init];
            prediction.labelIndex = classIndex;
            prediction.confidence = maxScore;
            prediction.boundingBox = rect;
            prediction.pointArray = [pointArray mutableCopy];
            prediction.visibleArray = [visibleArray mutableCopy];
            [predictions addObject:prediction];
        }
    }
    predictions = [self getPredictionsNMS:predictions];
    return predictions;
}

- (NSMutableArray*)getPredictionsNMS:(NSMutableArray*)predictions{
    if(predictions.count < 2){
        return predictions;
    }
    NSArray *sorted = [self sortPredictions:predictions];
    NSMutableArray *keep = [self getMutableTrueArray:(int)sorted.count];
    NSMutableArray *predictionsNMS = [NSMutableArray array];
    for (int i = 0; i < sorted.count; i++) {
        if ([keep[i] boolValue]) {
            [predictionsNMS addObject:sorted[i]];
            Prediction *prediction = sorted[i];
            CGRect bbox1 = prediction.boundingBox;
            for (int j = i + 1; j < sorted.count; j++) {
                if ([keep[j] boolValue]) {
                    Prediction *predictionJ = sorted[j];
                    CGRect bbox2 = predictionJ.boundingBox;
                    float threshold = self.nmsThreshold; // 0.5
                    float iou = [UtilRect IoU:bbox1
                                        rect2:bbox2];
                    if (iou > threshold) {
                        [keep replaceObjectAtIndex:j
                                        withObject:[NSNumber numberWithBool:false]];
                    }
                }
            }
        }
    }
    return predictionsNMS;
}

- (NSArray*)sortPredictions:(NSMutableArray*)predictions{
    NSArray *sorted = [predictions sortedArrayUsingComparator:^NSComparisonResult(id obj1, id obj2) {
        Prediction *prediction1 = obj1;
        Prediction *prediction2 = obj2;
        if (prediction1.confidence > prediction2.confidence) {
            return NSOrderedAscending;
        } else {
            return NSOrderedDescending;
        }
    }];
    return sorted;
}

- (NSMutableArray*)getMutableTrueArray:(int)size{
    NSMutableArray *keep = [NSMutableArray array];
    for (int i = 0; i < size; i++) {
        [keep addObject:[NSNumber numberWithBool:true]];
    }
    return keep;
}
```

**Comment by binarysports** [comment]
Hello there, @ryouchinsa ObjC NMS works excellent, thank you so much for sharing with us:
![Screenshot 2023-07-08 at 14 38 36](https://github.com/ultralytics/ultralytics/assets/58506216/b1c8f6cb-cce5-4993-ae61-a2e0ae2ef93a)

adding Prediction object and IoU code if someone needs:
`@interface Prediction : NSObject

@property int labelIndex;
@property CGFloat confidence;
@property CGRect boundingBox;
@property NSMutableArray *pointArray;
@property NSMutableArray *visibleArray;

@end`

`- (float) IoU:(CGRect)a rect2:(CGRect)b {
    float areaA = a.size.width * a.size.height;
    if (areaA <= 0) { return 0; }
    
    float areaB = b.size.width * b.size.height;
    if (areaB <= 0) { return 0; }
    
    float intersectionMinX = MAX(CGRectGetMinX(a), CGRectGetMinX(b));
    float intersectionMinY = MAX(CGRectGetMinY(a), CGRectGetMinY(b));
    float intersectionMaxX = MIN(CGRectGetMaxX(a), CGRectGetMaxX(b));
    float intersectionMaxY = MIN(CGRectGetMaxY(a), CGRectGetMaxY(b));
    float intersectionArea = MAX(intersectionMaxY - intersectionMinY, 0) * MAX(intersectionMaxX - intersectionMinX, 0);
    return (float)(intersectionArea / (areaA + areaB - intersectionArea));
}`

**Comment by ryouchinsa** [comment]
@binarysports, 

We were sorry that we forgot to put the IoU function code.
We edited our comment and added the code.

Thanks for your feedback and we are glad that you could parse the output layer of YOLOv8 Pose models on your environment.
If you have any other questions, please let us know.

**Comment by glenn-jocher** [comment]
Hi @binarysports,

Thank you for bringing this to our attention. We apologize for the oversight in not including the IoU function code in our previous comment. We have now edited the comment to include the code.

We appreciate your feedback and we're glad that you were able to parse the output layer of YOLOv8 Pose models successfully in your environment. If you have any further questions or need any other assistance, please don't hesitate to reach out to us. We're here to help!

Best regards, 
The macOS app developer of YOLOv8 Pose models

**Comment by ryouchinsa** [comment]
@CDEV500,
Yes, we think so.
For the segmentation models, there are 2 output layers, one for the bounding box, and one for the segmentation mask.

**Comment by glenn-jocher** [comment]
Hi @ryouchinsa,

Thank you for your question. In the YOLOv8 repo, for segmentation models, there are two output layers. The first output layer is responsible for generating the bounding box coordinates of the detected objects. The second output layer is responsible for generating the segmentation mask, which outlines the shape of the detected objects.

These output layers work together to provide both the bounding box information and the segmentation mask for each detected object in the image. The bounding box coordinates specify the location and size of the object, while the segmentation mask outlines the shape of the object.

By utilizing these output layers, you can obtain both the bounding box and the segmentation mask information from the YOLOv8 segmentation models.

If you have any further questions or need any additional clarification, please feel free to ask.

Best regards,
The YOLOv8 team

**Comment by ryouchinsa** [comment]
We can show you a guide how to parse 2 MultiArrays to obtain the segmentation masks.

MultiArray0: 1 32 160 160
MultiArray1: 1 116 8400

For MultiArray1, there are 8400 detection candidates and each candidate has a feature vector of length 116.
A feature vector of length 116 = [x, y, w, h, class1_score, ..., class80_score, segmentation values of length 32].
For each candidate, find the maximum class score from 80 classes, if the maximum score is more than the threshold such as 0.5, you add the feature vector to a feature vector array.

Using MultiArray0, you can decode the segmentation values in each feature vector to the segmentation mask.
[Segmentation values of length 32] x [32 160 160] = [160 160].
The result mask size is 160 x 160, but the pixel values are floating-point.
So that resizing to the original image size and thresholding the pixel values more than 0.5, the result mask can be smooth.

[RectLabel](https://rectlabel.com) is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, you can process images using YOLOv8 segmentation models. 
Furthermore, you can label polygons using Segment Anything models and read/write/export the YOLO segmentation format.

![sam_polygon](https://github.com/ryouchinsa/sam-cpp-macos/assets/1954306/4640e139-c533-4b8c-b27b-e02a401b9bbd)

**Comment by glenn-jocher** [comment]
@ryouchinsa hi there,

Parsing two MultiArrays to obtain the segmentation masks can be explained through the following steps:

1. For MultiArray1: It holds 8400 detection candidates, and each candidate has a feature vector of length 116. This feature vector comprises of [x, y, w, h, class1_score, ..., class80_score, segmentation values of length 32]. Your task here is to identify the maximum class score across the 80 classes for each candidate. If this maximum score surpasses a certain threshold (e.g. 0.5), you should add this feature vector to a separate array.

2. Moving on to MultiArray0: You can use this array to decode the segmentation values found in each feature vector. This can be achieved by multiplying the segmentation values (length 32) with the MultiArray0 (1 32 160 160), which results in a 160 x 160 segmentation mask. Please note that the pixel values in this output mask are of a floating-point, therefore you might want to resize it to the original image size and apply a threshold (for example, greater than 0.5) for smooth results.

Moreover, you might find it helpful to use RectLabel, which is an offline image annotation tool for object detection and segmentation. Using RectLabel, you can process images through YOLOv8 segmentation models. It also allows you to label polygons and read/write/export the YOLO segmentation format.

I hope this information helps you in understanding the process. If you have further queries or need any additional clarification, feel free to ask.

Best,
The YOLOv8 team

**Comment by AphroDatalyst** [comment]
is it possible to have .mlpackage for yolov8-pose instead of .mlmodel?
if yeas, how can we implement it?

**Comment by glenn-jocher** [comment]
@AphroDatalyst yes, it's certainly possible to have a .mlpackage for YOLOv8-Pose instead of a .mlmodel. A .mlpackage is essentially a self-contained model bundle that includes the Core ML model along with any associated model metadata and assets.

The process of converting a .mlmodel to a .mlpackage isn't too difficult. You will need to use the Core ML converter to convert your YOLOv8-Pose model to .mlmodel format first. After that, you then need to use the Core ML compiler to compile it into .mlpackage format.

Once you have the .mlpackage, implementation would be similar to the .mlmodel. You would load the package in the Xcode project and manage it the same way you would using the output of the .mlmodel file.

Please ensure you're using Xcode 12 or later as .mlpackage is not supported in older versions.

We hope this addresses your queries. If you have further questions, feel free to ask.

Best regards,
The YOLOv8 Team

**Comment by Raghvender1205** [comment]
> Kindly, the macOS app developer of [Binary Sports](https://www.binarysports.eu/) asked us how to parse the output layer of YOLOv8 Pose models.
> 
> We show the example code using Objective-c. Please let us know your opinion.
> 
> 1. Check the MLModel meta data.
> 
> ```
> - (void)setModelMetaData:(id)modelId{
>     MLModel* model = modelId;
>     MLModelDescription *modelDescription = model.modelDescription;
>     NSDictionary *inputDict = modelDescription.inputDescriptionsByName;
>     NSArray *inputDictValues = inputDict.allValues;
>     MLFeatureDescription *inputFeatureDescription = [inputDictValues objectAtIndex:0];
>     MLImageConstraint *imageConstraint = inputFeatureDescription.imageConstraint;
>     int inputWidth = (int)imageConstraint.pixelsWide;
>     int inputHeight = (int)imageConstraint.pixelsHigh;
>     self.inputWidth = inputWidth;   // 640
>     self.inputHeight = inputHeight; // 640
> 
>     NSDictionary *userDefinedDict = modelDescription.metadata[MLModelCreatorDefinedKey];
>     id kptShape = [userDefinedDict objectForKey:@"kpt_shape"];
>     if(kptShape != nil){
>         NSString *text = kptShape;
>         NSData *data = [text dataUsingEncoding:NSUTF8StringEncoding];
>         NSError *error;
>         NSArray* array = [NSJSONSerialization JSONObjectWithData:data
>                                                          options:0
>                                                            error:&error];
>         self.keypointsNum = [array[0] intValue]; // 17
>         self.keypointsDim = [array[1] intValue]; // 3
>     }
> }
> ```
> 
> 2. Run the MLModel and parse the output layer.
>    When we run the model, the output layer shape is [1, 56, 8400].
>    The 56 includes [x, y, w, h, class_score, x1, y1, v1, ..., x17, y17, v17].
> 
> ```
> - (NSMutableArray*)parsePoseYOLOv8:(NSArray*)results{
>     NSMutableArray *predictions = [NSMutableArray array];
>     VNCoreMLFeatureValueObservation *observation = results[0];
>     MLMultiArray *outputArray = observation.featureValue.multiArrayValue;
>     int gridHeight = [outputArray.shape[1] intValue]; // 56
>     int gridWidth = [outputArray.shape[2] intValue];  // 8400
>     int classesNum = gridHeight - 4 - self.keypointsNum * self.keypointsDim; // 1
>     float threshold = self.confidenceThreshold; // 0.25
>     int inputWidth = self.inputWidth;
>     for(int j = 0; j < gridWidth; j++){
>         int classIndex = -1;
>         float maxScore = 0;
>         for(int i = 4; i < 4 + classesNum; i++){
>             float score = [outputArray[(i * gridWidth) + j] floatValue];
>             if(score > maxScore){
>                 classIndex = i - 4;
>                 maxScore = score;
>             }
>         }
>         if(maxScore > threshold){
>             float x = [outputArray[(0 * gridWidth) + j] floatValue];
>             float y = [outputArray[(1 * gridWidth) + j] floatValue];
>             float w = [outputArray[(2 * gridWidth) + j] floatValue];
>             float h = [outputArray[(3 * gridWidth) + j] floatValue];
>             x -= w / 2;
>             y -= h / 2;
>             CGRect rect = CGRectMake(x / inputWidth,
>                                      1.0 - (y + h) / inputWidth,
>                                      w / inputWidth,
>                                      h / inputWidth);
>             NSMutableArray *pointArray = [NSMutableArray array];
>             NSMutableArray *visibleArray = [NSMutableArray array];
>             for(int i = 4 + classesNum; i < gridHeight; i += 3){
>                 float x = [outputArray[((i + 0) * gridWidth) + j] floatValue];
>                 float y = [outputArray[((i + 1) * gridWidth) + j] floatValue];
>                 float v = [outputArray[((i + 2) * gridWidth) + j] floatValue];
>                 NSPoint point = NSMakePoint(x / inputWidth, 1.0 - y / inputWidth);
>                 int visible = v > 0 ? kVisible : kNotVisibleNotLabeled;
>                 [pointArray addObject:[NSValue valueWithPoint:point]];
>                 [visibleArray addObject:[NSNumber numberWithInt:visible]];
>             }
>             Prediction *prediction = [[Prediction alloc] init];
>             prediction.labelIndex = classIndex;
>             prediction.confidence = maxScore;
>             prediction.boundingBox = rect;
>             prediction.pointArray = [pointArray mutableCopy];
>             prediction.visibleArray = [visibleArray mutableCopy];
>             [predictions addObject:prediction];
>         }
>     }
>     predictions = [self getPredictionsNMS:predictions];
>     return predictions;
> }
> 
> - (NSMutableArray*)getPredictionsNMS:(NSMutableArray*)predictions{
>     if(predictions.count < 2){
>         return predictions;
>     }
>     NSArray *sorted = [self sortPredictions:predictions];
>     NSMutableArray *keep = [self getMutableTrueArray:(int)sorted.count];
>     NSMutableArray *predictionsNMS = [NSMutableArray array];
>     for (int i = 0; i < sorted.count; i++) {
>         if ([keep[i] boolValue]) {
>             [predictionsNMS addObject:sorted[i]];
>             Prediction *prediction = sorted[i];
>             CGRect bbox1 = prediction.boundingBox;
>             for (int j = i + 1; j < sorted.count; j++) {
>                 if ([keep[j] boolValue]) {
>                     Prediction *predictionJ = sorted[j];
>                     CGRect bbox2 = predictionJ.boundingBox;
>                     float threshold = self.nmsThreshold; // 0.5
>                     float iou = [self IoU:bbox1
>                                     rect2:bbox2];
>                     if (iou > threshold) {
>                         [keep replaceObjectAtIndex:j
>                                         withObject:[NSNumber numberWithBool:false]];
>                     }
>                 }
>             }
>         }
>     }
>     return predictionsNMS;
> }
> 
> - (NSArray*)sortPredictions:(NSMutableArray*)predictions{
>     NSArray *sorted = [predictions sortedArrayUsingComparator:^NSComparisonResult(id obj1, id obj2) {
>         Prediction *prediction1 = obj1;
>         Prediction *prediction2 = obj2;
>         if (prediction1.confidence > prediction2.confidence) {
>             return NSOrderedAscending;
>         } else {
>             return NSOrderedDescending;
>         }
>     }];
>     return sorted;
> }
> 
> - (NSMutableArray*)getMutableTrueArray:(int)size{
>     NSMutableArray *keep = [NSMutableArray array];
>     for (int i = 0; i < size; i++) {
>         [keep addObject:[NSNumber numberWithBool:true]];
>     }
>     return keep;
> }
> 
> - (float)IoU:(CGRect)rect1
>        rect2:(CGRect)rect2{
>     CGRect intersectionRect = CGRectIntersection(rect1, rect2);
>     CGRect unionRect = CGRectUnion(rect1, rect2);
>     if(CGRectIsNull(intersectionRect)){
>         return 0;
>     }
>     float iou = (intersectionRect.size.width * intersectionRect.size.height) / (unionRect.size.width * unionRect.size.height);
>     return iou;
> }
> ```

Can you provide Swift implementation for parsing the output layer of Pose Model

**Comment by ryouchinsa** [comment]
Hi @Raghvender1205, 
Currently I am coding RectLabel apps using Objective-c. But for the open source version of RectLabel, I will code using Swift.

**Comment by glenn-jocher** [comment]
@Raghvender1205 sure, I'm glad to provide more details on parsing the output `MLMultiArray` for a pose model in a conceptual manner.

1. **Access Output Data**: After running the model, you'll receive the output as an `MLMultiArray`. The exact structure will depend on your model, but for a pose detection model, you can usually expect to receive an array with the pose keypoints and associated information like confidence scores.

2. **Understand the Data Format**: To parse the `MLMultiArray`, you need to understand how the pose data is structured. The number of keypoints, their dimensions, and whether there are confidence scores attached will determine how you iterate through the array.

3. **Iterate Through Array**: You'll typically want to loop through the `MLMultiArray`. Since `MLMultiArray` is a multi-dimensional array, you might have nested loops to traverse it. For example, if you expect 17 keypoints with x, y coordinates and a visibility score (v), you might have a structure like:
   ```swift
   for i in 0..<keypointCount {
       let xIndex = i * keypointDimension
       let yIndex = xIndex + 1
       let vIndex = yIndex + 1
       let x = outputArray[xIndex].floatValue
       let y = outputArray[yIndex].floatValue
       let v = outputArray[vIndex].floatValue
       // Process the keypoint data...
   }
   ```

4. **Extract Keypoint Information**: As you iterate, extract the keypoints' x and y coordinates and visibility/confidence score. Depending on the output format of the model, you might also need to apply any necessary transformations to the keypoints' coordinates to match them to the original image dimensions.

5. **Threshold Confidence Scores**: You may have a confidence or visibility score associated with each keypoint. Apply a threshold to decide whether to keep or discard a keypoint.

6. **Handle the Results**: Once you have the keypoints' information, you can handle it as required by your application, such as displaying it on the screen, using it in further calculations, etc.

Keep in mind that while you don't perform these operations with a Swift code example, the conceptual approach outlined here should still be applicable. It involves looping through the output array and interpreting the data based on your understanding of the model's output schema.

I hope this gives you a clearer idea of how to approach parsing the `MLMultiArray`. If you have further questions, feel free to ask.

**Comment by glenn-jocher** [comment]
You're very welcome, @Raghvender1205! 😊 I'm glad I could assist you. If you have any more questions or need further guidance as you work on your pose detection project, don't hesitate to reach out. Good luck with your iOS application, and I'm sure it will turn out great! Take care and happy coding! 👨‍💻🚀

**Comment by pbanavara** [comment]
I tried the Swift variant and I have the output. It took a while so if anyone is struggling with this, here's the code. I am now figuring out how to parse the output based on one of the comments above. Will post what I come up with. At least I have the right output shape :)

`
guard let imageBuffer = CMSampleBufferGetImageBuffer(sampleBuffer) else { return nil }
        CVPixelBufferLockBaseAddress(imageBuffer, .readOnly)

        let baseAddress = CVPixelBufferGetBaseAddress(imageBuffer)
        let pointer  = baseAddress!.assumingMemoryBound( to: UInt8.self )
        let height   = CVPixelBufferGetHeight(imageBuffer)
        let bytesPerRow = CVPixelBufferGetBytesPerRow(imageBuffer)
        let pixBytes = height * bytesPerRow
        let cropWidth = 640
        let cropHeight = 640
        let colorSpace = CGColorSpaceCreateDeviceRGB()
        let options: NSDictionary = [:]

        let context = CGContext(data: baseAddress, width: cropWidth, height: cropHeight, bitsPerComponent: 8, bytesPerRow: bytesPerRow, space: colorSpace, bitmapInfo: CGImageAlphaInfo.noneSkipFirst.rawValue | CGBitmapInfo.byteOrder32Little.rawValue)
        CVPixelBufferUnlockBaseAddress(imageBuffer, .readOnly)
        var targetBuffer: CVPixelBuffer?
        let results = CVPixelBufferCreateWithBytes(
            kCFAllocatorDefault,
            cropWidth,
            cropHeight,
            kCVPixelFormatType_32BGRA,
            pointer,
            bytesPerRow,
            nil,
            nil,
            options,
            &targetBuffer
        )
        
        
        let model = try? yolov8n_pose()
        let output = try? model!.prediction(image: targetBuffer!)
        let features = output?.featureValue(for: "var_1035")
        let features_val = features?.multiArrayValue
        print (features_val?.shape)
`
The shape printed is
`
Optional([1, 56, 8400])
`

**Comment by glenn-jocher** [comment]
@pbanavara awesome!! Thank you for your contributions and for the example code. This will be a great help to the community when implementing YOLOv8-Pose models in CoreML. 

@kalenmike @sergiossm above code we can use for CoreML Pose by @pbanavara

**Comment by glenn-jocher** [comment]
@pbanavara good news! I've launched an AGPL-3.0 open-source version of the Ultralytics YOLO iOS app at a new repository: https://github.com/ultralytics/yolo-ios-app

Please take a look there and if possible help us out with a PR for keypoint prediction and visualization. Thank you!

<img width="880" alt="Screenshot 2024-02-16 at 09 42 44" src="https://github.com/ultralytics/ultralytics/assets/26833433/6154d95a-0fa6-4dd8-ae73-3885b07eb0f7">

**Comment by pbanavara** [comment]
@glenn-jocher Awesome !!!! I will send the keypoint prediction and visualization PR. Currently working on a web version. Will get back to iOS soon.

**Comment by glenn-jocher** [comment]
@pbanavara thank you for reporting this issue with exporting a pose model to CoreML. The error message suggests that there is a mismatch in the expected shape of the updates tensor during the export process. It seems that the model is expecting a tensor with a shape that includes 51 channels, but it's receiving one with only 17 channels.

This could be related to the specific architecture of the pose model and how it's being interpreted by the CoreML export process. The YOLO pose models typically output a tensor with keypoints for each detected object, and the number of keypoints (and thus the channel depth of the tensor) can vary based on the model configuration.

To address this issue, we'll need to investigate the export code and ensure that the model's output tensor is correctly formatted for CoreML. This might involve adjusting the model's architecture or the export function to align with CoreML's requirements.

As a temporary workaround, you might want to continue using the ONNX format if that's working for you, or try exporting to a different format that supports pose estimation models.

We appreciate your patience while we look into this, and we'll aim to resolve the issue as soon as possible. If you have any additional information or steps that could help reproduce the issue, please feel free to share them.

**Comment by pbanavara** [comment]
Just getting back to this @glenn-jocher From what I see, the MLOutputArray shape is (1, 56, 8400) and I am trying to do steps 4, 5, 6 from your December 2023 comment. 

I am referring to the above Objective C code and porting that to Swift.

However, I agree to your comment that this has to be fixed in the model export code, so that the prediction function outputs the keypoints just like it outputs the bounding boxes. Am happy to work on that as well. Whichever gets there first :). I think tweaking the model export is a lot more beneficial and has wider impact and will be on par with Python functionality.

**Comment by glenn-jocher** [comment]
Hey @pbanavara, great to hear you're making progress! 🚀 It sounds like you're on the right track with adapting the Objective C code to Swift and working through the keypoints extraction.

I agree that aligning the model export functionality with the Python version would be highly beneficial for the community. If you're up for tackling the export code, that would be fantastic! Your contributions are much appreciated, and I'm here to support you along the way. Let's aim for that wider impact! 🌟

If you need any pointers or want to discuss potential solutions, feel free to reach out. Happy coding!

**Comment by pbanavara** [comment]
@glenn-jocher Some thoughts on using the VNRecognizedObjectObservation. Assuming that the model.export can include the keypoints in the prediction (which am yet to figure out :) ), I don't think we can use the VNRecognizedObjectObservation and other built in APIs of coreML. If you look at this function, this function has methods for bounding boxes, how can we display the keypoints using these primitives ?
```
let shapeLayer = self.createRoundedRectLayerWithBounds(objectBounds)
```
Ideally the shapeLayer with pose detection should include the keypoints within the rect and not just the objectbounds. Not sure how to accomplish that.

```
for observation in results where observation is VNRecognizedObjectObservation {
    guard let objectObservation = observation as? VNRecognizedObjectObservation else {
        continue
    }
    // Select only the label with the highest confidence.
    let topLabelObservation = objectObservation.labels[0]
    let objectBounds = VNImageRectForNormalizedRect(objectObservation.boundingBox, Int(bufferSize.width), Int(bufferSize.height))
    
    let shapeLayer = self.createRoundedRectLayerWithBounds(objectBounds)
    
    let textLayer = self.createTextSubLayerInBounds(objectBounds,
                                                    identifier: topLabelObservation.identifier,
                                                    confidence: topLabelObservation.confidence)
    shapeLayer.addSublayer(textLayer)
    detectionOverlay.addSublayer(shapeLayer)
}
```
Do we need a separate layer with the keypoints to overlay on top of the above shapeLayer ? 
Something like 

```
detectionOverlay.addSublayer(keyPointsLayer)
```
That may be feasible I think.

Also can't we use OpenCVs iOS APIs to draw the rect and points on the image instead of these CoreML primitives ? Just like we do in Python. The core task of getting the prediction is already done using the GPU, the overlay and other tasks shouldn't be that expensive on the CPU.
