### ISSUE TITLE
runtime error 

### ISSUE THREAD

**Issue by only1amal** [ultralytics/ultralytics#1919]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i got this runtime error, and I need help to fix it :RuntimeError: Dataset '/content/drive/MyDrive/Omedena/Yolo8/data.yaml' error ❌ 'str' object is not a mapping

**Comment by glenn-jocher** [comment]
@only1amal, this error is usually caused by an error in your dataset.yaml configuration file. Double check that your dataset.yaml file adheres to the Dataset Configuration File format at https://docs.ultralytics.com/dataset/#dataset-configuration-file-format, specifically that it uses proper indentation and formatting. If the issue persists, feel free to share your YAML file or a minimum reproducible example so the community can help you better understand the problem.
