### ISSUE TITLE
[BUG]label shallow copy

### ISSUE THREAD

**Issue by regainOWO** [ultralytics/ultralytics#1925]
https://github.com/ultralytics/ultralytics/blob/95f96dc5bc1ad6fc22fa9ede1c9fe36d4c6abb56/ultralytics/yolo/data/base.py#L180

i increased the list plot_idx in trainer.py. it will save 20 train_batch_x.jpg, but i found there are some error label plot in this images. I found it caused by label shallow copy. `self.labels[index]` return type is a dict, invoke the `.copy` function is a shallow copy. maybe it can change to 
``` python
label = deepcopy(self.labels[index])
```

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by regainOWO** [comment]
@glenn-jocher ok. i will close this issue

**Comment by glenn-jocher** [comment]
@regainOWO if you could provide a reproducible example of the bug that would help us decide on updating the code. But as far as I know all output plot labels are correct.
