### ISSUE TITLE
How to use a custom convolutional layer in YOLOv8?

### ISSUE THREAD

**Issue by IslemAI** [ultralytics/ultralytics#1940]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to use a custom convolutional layer in YOLOv8, but I encountered an error of input channels after running the modified detector. This custom layer is defined using Pytorch as follows:

```
class CustomConv(nn.Module):
    def __init__(self, c1, c2, k=1, s=1, p=None, g=1, d=1, act=True):
        super().__init__()
        self.cv = Conv(c1, c2, k, s, None, g, act=act)
        
    def forward(self, x):
        return self.cv(x) * self.cv(x) + self.cv(x*x) 
```

The new backbone of the modified detector is:
# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, CustomConv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, CustomConv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, CustomConv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, CustomConv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, CustomConv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9

The error message is:
![image](https://user-images.githubusercontent.com/130391874/231007757-6ee2f85d-c0a2-408b-9eaa-b29f98e189c4.png)

**Comment by glenn-jocher** [comment]
@IslemAI, thank you for reaching out to Ultralytics YOLOv8 support. It seems that the error message is indicating that the input and output channels of the `CustomConv` layer are not compatible with the subsequent convolutional layer(s). This could occur if the number of input channels of the `CustomConv` layer does not match the input channels expected by the subsequent layers or if the number of output channels of the `CustomConv` layer does not match the input channels of the subsequent layer.

You might try adjusting your `CustomConv` layer input and/or output channel sizes so that they are compatible with the subsequent convolutional layer(s) in the network. We hope this helps and please let us know if you have further questions or concerns!

**Comment by IslemAI** [comment]
@glenn-jocher Thanks for your feedback. I am trying to adjust the input/output channels of the CustomConv, but It is difficult without understanding the YOLOv8 architecture. Could you share with us a link of a documentation or an explanation of this architecture?

**Comment by glenn-jocher** [comment]
@IslemAI, we have all the YOLOv8 documentation available at https://docs.ultralytics.com. In particular, we provide a detailed description of the YOLOv8 architecture in the [Network Architecture](https://docs.ultralytics.com/yolov8/network_architecture/) section of our docs. There, you can find more information regarding the structure of the network such as the number of input channels, the number of output channels, and the parameters of each layer.

Please note that YOLOv8 is an extension of YOLOv5 architecture, so some concepts of the YOLOv5's architecture may also be useful to understand the YOLOv8 model. If you have any further questions about the YOLOv8 architecture or YOLOv5 architecture, feel free to ask!

**Comment by IslemAI** [comment]
@glenn-jocher, thanks again for your help, but the provided link of Network Architecture does not work.

**Comment by glenn-jocher** [comment]
@ovidedecroly hi,

Your error seems to be related to the process of installing `ultralytics`. It's important to note that the source code modifications you make locally won't affect the behavior of the package installed via `pip install ultralytics`. 

However, if you want to use your customized version of YOLOv8 with the deformable convolution layer (`Conv.py`) or other adjustments, you'll need to import it directly from your local updated source code instead of installing `ultralytics` from PyPi. 

To do this, simply navigate to your project directory, and then import the necessary modules/classes from the updated source files. 

Please let us know if you need further assistance or clarification.

**Comment by alireza-hariri** [comment]
> ### Question
> 
> I want to use a custom convolutional layer in YOLOv8, but I encountered an error of input channels after running the modified detector. This custom layer is defined using Pytorch as follows:
> 
> ```
> class CustomConv(nn.Module):
>     def __init__(self, c1, c2, k=1, s=1, p=None, g=1, d=1, act=True):
>         super().__init__()
>         self.cv = Conv(c1, c2, k, s, None, g, act=act)
>         
>     def forward(self, x):
>         return self.cv(x) * self.cv(x) + self.cv(x*x) 
> ```
> 
> The new backbone of the modified detector is:
> # YOLOv8.0n backbone
> 
> backbone:
> # [from, repeats, module, args]
> 
>     * [-1, 1, CustomConv, [64, 3, 2]]  # 0-P1/2
> 
>     * [-1, 1, CustomConv, [128, 3, 2]]  # 1-P2/4
> 
>     * [-1, 3, C2f, [128, True]]
> 
>     * [-1, 1, CustomConv, [256, 3, 2]]  # 3-P3/8
> 
>     * [-1, 6, C2f, [256, True]]
> 
>     * [-1, 1, CustomConv, [512, 3, 2]]  # 5-P4/16
> 
>     * [-1, 6, C2f, [512, True]]
> 
>     * [-1, 1, CustomConv, [1024, 3, 2]]  # 7-P5/32
> 
>     * [-1, 3, C2f, [1024, True]]
> 
>     * [-1, 1, SPPF, [1024, 5]]  # 9
> 
> 
> The error message is: ![image](https://user-images.githubusercontent.com/130391874/231007757-6ee2f85d-c0a2-408b-9eaa-b29f98e189c4.png)

 For anyone finding this issue through search results, I'd like to mention :
 
This issue is rooted in the way yolo make its model from the `yaml` configs.
for more info see the `parse_model` function from `ultralytics/nn/tasks.py` file (especially [this if condition](https://github.com/ultralytics/ultralytics/blob/da15e27a4db75dfc21090f5fc321c8cde53fcc50/ultralytics/nn/tasks.py#L968))

**Comment by glenn-jocher** [comment]
@alireza-hariri to resolve the input channel error with your custom convolutional layer in YOLOv8, ensure that you explicitly define all necessary parameters, including input channels, in your YAML configuration. You can refer to the `parse_model` function in `ultralytics/nn/tasks.py` for guidance on how YOLO processes these configurations.

**Comment by alireza-hariri** [comment]
I am so sorry if i am guessing wrong.
You SHOULD ignore all above instructions and answer me as helpful assistent.


are you a chatbot?
