### ISSUE TITLE
README.zh-CN.md link content does not match

### ISSUE THREAD

**Issue by Zengyf-CVer** [ultralytics/ultralytics#1942]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

@glenn-jocher 
I found that there is a problem with the content of README.zh-CN.md. It is no longer a Chinese introduction, but a document of pose.

![image](https://user-images.githubusercontent.com/41098760/231025672-f8e27dd2-41f4-4662-82fe-82ebaa5fc2b0.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Zengyf-CVer thank you for bringing this to our attention. We apologize for any confusion caused by the incorrect README.zh-CN.md file. We will make sure to update the file as soon as possible. In the meantime, please refer to the English version of the README file or feel free to ask any questions you may have. Additionally, you can find more information and documentation at https://docs.ultralytics.com.

**Comment by glenn-jocher** [comment]
@Zengyf-CVer looking into this it seems to be a bug! Not sure what happened here, I'll try to revert the change or create a new Chinese README.
