### ISSUE TITLE
how can i get params of exported saved model 

### ISSUE THREAD

**Issue by Oink98** [ultralytics/ultralytics#1944]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When exporting a model as a SavedModel format, using the saved_model_cli show command to view the input and output names of the model does not provide useful information.
`saved_model_cli show --dir ./ --all`
`2023-04-11 01:36:00.186699: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is: `
how can i obtain the inputs, outputs and other params of saved model
![q](https://user-images.githubusercontent.com/54368884/231034338-11795315-2215-45ae-b6c7-dbfc2f6868c3.png)

**Comment by glenn-jocher** [comment]
@Oink98, if the `signature_keys` list is empty, it could indicate that the saved model was not correctly saved or loaded. One possible issue could be incorrect use of the `saved_model_cli show` command during the model saving process, which may cause an incorrect `SignatureDef` to be saved. Another possible issue could be incorrect loading of the saved model in your code, such as an incorrect path to the saved model or an incorrect version of TensorFlow being used. 

One way to diagnose this issue might be to first verify that the saved model was indeed saved correctly and that it includes the expected `SignatureDef`. You could try loading the saved model with the `loaded_model = tf.saved_model.load(PATH_TO_SAVED_MODEL)` command, then try printing the resulting `loaded_model` object to see its contents. Alternatively, you could try running the `saved_model_cli show` command on the saved model again to verify the `SignatureDef`.

If the issue persists, you may need to inspect the saved model more closely or provide more information about how it was created and loaded in order to determine the root cause of the issue.

**Comment by Oink98** [comment]
> 
`loaded_model = tf.saved_model.load("/home/ultralytics/weights/yolov8n_saved_model")

print(loaded_model)

print("signatures",loaded_model.signatures)`

The printed information is as follows:

`ConcreteFunction <lambda>(arg1)
  Args:
    arg1: float32 Tensor, shape=(1, 640, 640, 3)
  Returns:
    float32 Tensor, shape=(1, 84, 8400)
signatures _SignatureMap({})`

I followed the instruction from https://docs.ultralytics.com/modes/export/ to export the model.
`yolo export model=weights/yolov8n.pt format=saved_model`
![q4](https://user-images.githubusercontent.com/54368884/231097039-80db9ca7-5cd4-4329-90aa-f83b540a5b80.png)

**Comment by glenn-jocher** [comment]
@Oink98 based on the output you have provided, it seems that the `loaded_model` object only contains a single `ConcreteFunction` signature, which is associated with a `lambda` function that expects a single input tensor of shape `float32 Tensor, shape=(1, 640, 640, 3)` and returns a single output tensor of shape `float32 Tensor, shape=(1, 84, 8400)`. 

The fact that the `loaded_model.signatures` attribute returns an empty dictionary suggests that there may not be any additional signatures defined in this saved model, which could explain why your initial attempt to load the model was unsuccessful.

To further diagnose the issue, it may be helpful to check the contents of the `saved_model.pb` file in the exported model directory. You can do this using the `saved_model_cli show` command, as demonstrated previously, to verify that the expected `SignatureDef` is present in the saved model. If the expected `SignatureDef` is present, you might also try loading the saved model using the `tf.saved_model.load` function specifying the `tags` argument. This might work if the exported model used custom tags that were not included by default.

In general, we recommend double checking the model export process and the paths used, and exploring the `tf.saved_model.load` and `saved_model_cli show` functionalities to further determine the issue.

**Comment by Oink98** [comment]
@glenn-jocher I tried the command `saved_model_cli show` at my first comment, but it did not work.
![q5](https://user-images.githubusercontent.com/54368884/231325940-1b4be237-690e-4579-af26-3bc9e4f4101a.png)

and  I tried https://github.com/ultralytics/ultralytics/issues/1851#issuecomment-1498117102 , specifying the argument `dynamic=True` in exporting, then came the error.
![q6](https://user-images.githubusercontent.com/54368884/231327390-f57b27f5-2a76-4b90-a493-1b09cbc0f81b.png)
![q7](https://user-images.githubusercontent.com/54368884/231327395-12d66da3-5a79-420b-950b-a180ef541ba6.png)
Whether additional argument need to be specified to successfully export the TF Saved Model ?

**Comment by glenn-jocher** [comment]
@Louis-Aballea certainly! Based on the logs you provided, it seems that the `saved_model_cli show` command is not able to find the expected `SignatureDef` in the saved model. This could indicate that the saved model was not exported correctly, or that the model was exported with a different name or signature than you were expecting. 

To diagnose this issue, you could try exploring the contents of the saved model directory to verify that the saved model files are present and that they contain the expected information. You could also try using the `tf.saved_model.load` function to load the saved model and inspect its contents, as this may give you more information about the structure and contents of the saved model. 

Another possibility is that the saved model was not exported using the correct settings or arguments. You may want to double-check the export command you used and make sure that you are exporting the saved model in the correct format and specifying the correct signature for the model.

Overall, the issue seems to be related to the export process or the saved model structure. Further exploration of the saved model directory and the export process may help you to diagnose and resolve the issue.

**Comment by ahgz7** [comment]
Conver the onnx model to tf with the `-osd` flag to add the signatures:
```
$ onnx2tf -i yolov8n.onnx -o saved_model -osd
```

Read more about the `-osd` flag in the docs https://github.com/PINTO0309/onnx2tf.

**Comment by glenn-jocher** [comment]
@ahgz7 thank you for providing a solution for converting the YOLOv8n ONNX model to TensorFlow format with signatures. Adding the `-osd` flag during the conversion process will create the expected `SignatureDef` in the resulting TensorFlow SavedModel, which should then be compatible with the `tf.saved_model.load` function. 

It's great to see a solution, and thank you for sharing your knowledge with the community.
