### ISSUE TITLE
Importing ultralytics via Ubuntu terminal

### ISSUE THREAD

**Issue by hamedgorji** [ultralytics/ultralytics#1964]
Hi,
I want to use my model on `IMX8M-PLUS`. The OS on IMX8M-PLUS is Ubuntu. So, I installed the yolov8 using `pip install ultralytics` and then I tried to import it by first typing the `python` and enter in the terminal and then `import ultralytics`. But it gives me the following error:
`Illegal instruction (core dumped) `
Any idea how can I solve it? 
I have no problem importing all other libraries.

**Comment by glenn-jocher** [comment]
It seems like you're encountering an issue with the 'ultralytics' package on your i.MX8M Plus platform. The "Illegal instruction (core dumped)" error typically occurs when a program tries to execute an instruction that is not supported by the hardware.

The i.MX8M Plus has an ARM Cortex-A53 CPU architecture, which might not be fully compatible with the precompiled binaries provided by the 'ultralytics' package. To resolve this issue, you can try to build the package from source instead of using the precompiled version from pip.

**Comment by hamedgorji** [comment]
I would appreciate it if you could let me know how can I do that

**Comment by glenn-jocher** [comment]
@hamedgorji to build the 'ultralytics' package from the source, you need to first download the source code from the Ultralytics YOLOv8 GitHub repository. Then, you can use the standard Python distribution tools such as `setuptools` to build and install the package. 

Before you do this, you may want to check that your development environment meets the necessary requirements, such as having the correct version of Python and compatible versions of the required dependencies. 

Once the package is built, you can then import it in your project as usual by adding the package path to your Python path. It's important to note that building packages from source requires some technical expertise and is more involved than installing pre-built binaries via pip, but it can be a useful technique if you experience issues with precompiled packages.
