### ISSUE TITLE
pose model convert *.pt to *.tflite

### ISSUE THREAD

**Issue by June1124** [ultralytics/ultralytics#1972]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I can successfully convert the model to onnx format, but there is an error in the onnx step when converting to tflite, how can I solve this problem? Here is my log.

### Additional

![image](https://user-images.githubusercontent.com/52447302/231327433-57b6f4a3-ed59-4acc-bddb-a6d47c06822a.png)

**Comment by June1124** [comment]
ultralytics                             8.0.74
onnx                                    1.13.1
onnx-graphsurgeon            0.3.26
onnx2tf                                1.9.1
onnxruntime                        1.14.1
onnxruntime-gpu                1.14.1
onnxsim                               0.4.19
opencv-python                    4.7.0.72

**Comment by glenn-jocher** [comment]
@June1124 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. Export to all formats works correctly as shown in Ultralytics CI.

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by June1124** [comment]
I have updated all the environment and code according to the official tutorial, but I still get the above problem.

**Comment by June1124** [comment]
![image](https://user-images.githubusercontent.com/52447302/231636019-7013091d-7daa-4b3c-9e95-4b695133e5c0.png)

**Comment by June1124** [comment]
All packages are installed as required by requirements.txt.

**Comment by glenn-jocher** [comment]
@June1124, it appears there is an issue during the onnx to tflite conversion. Without seeing more code, one cannot point to the exact cause of the problem. However, two things are worth considering. First, please verify that the conversion command is executed correctly in your local environment. Second, you can try investigating your environment and reproduce the problem with the following `conda` command:

conda create -n tflite -y && conda activate tflite && \
conda install -y python=3.7 numpy=1.14 onnx=1.6 onnxruntime=1.8 onnx2tf=1.5.1 && \
pip install tensorflow==2.3.1 && \
python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"

If this reproduces the error, it is possible that one of the installed packages has a problem. Conversely, if this works as expected, it indicates that there is an issue in your code that needs to be debugged more carefully.

**Comment by June1124** [comment]
![1681367555048](https://user-images.githubusercontent.com/52447302/231673706-4e7670f0-5590-4b56-b231-b05999637c44.jpg)
I followed your instructions on this, is this the correct output I'm getting? If it is correct, I tried again yolo export model=yolov8n-pose.pt format=tflite and still got the above error.

**Comment by glenn-jocher** [comment]
@June1124 it appears that you have created a new environment called `tflite`. The output looks correct, which indicates that all required packages have been installed successfully. However, you should see your new created environment `"tflite"(base)` after using the command `conda activate tflite`. Then you can export your ONNX model to TFLite format via the command line. If you are using an Ubuntu system, you might also need to install some required packages to support TFLite (as detailed here: https://www.tensorflow.org/lite/guide/python), such as `sudo apt-get install -y libtensorflow-lite-dev`.

**Comment by xsy0520** [comment]
I have the same problem. Have you solved it？

**Comment by glenn-jocher** [comment]
@xsy0520 thank you for your interest in YOLOv8. The particular error message you are referring to may be caused by many factors. The current version of YOLOv8 has been tested and verified as functional by our team, and we have not encountered this particular issue in our internal testing. Therefore, this issue may be specific to your environment or code. 

We suggest checking whether all necessary packages have been installed in the environment you are running the code in, and verifying that the export command has been executed correctly. Additionally, if the issue persists after attempting to export the model in a fresh environment as we detailed in a previous comment, we recommend submitting a new issue following our guidelines that include a minimal reproducible example. We would be happy to help you diagnose and resolve the issue. Thank you.
