### ISSUE TITLE
Training/validation on image patches  instead of directly using full scale images 

### ISSUE THREAD

**Issue by kabbas570** [ultralytics/ultralytics#1973]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Thanks for the nice repo; I was wondering if there is any option/argument available if we can train yolov8 on image patches instead of full-scale images, for example, if our original image dimensions are [8000,7000,3], and yolov8 gives an option of training it on the spatial dimension of [640,640,3] as if we train on the original size it misses certain objects of small size, because of maybe receptive field issues, Thank you. 

### Use case

Small-Object Detection: An Image Tiling-Based Approach available here;

https://binginagesh.medium.com/small-object-detection-an-image-tiling-based-approach-bce572d890ca
Small-Object

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Thanks for the feature request. Currently, this is not supported, but it sounds interesting and we can fast-track it if you'd like to contribute a PR.

**Comment by patrickjcraig** [comment]
Any comment on if this has been implemented elsewhere? This would be great for microscopists.

**Comment by pderrenger** [comment]
@patrickjcraig thank you for your interest. As of now, training YOLOv8 on image patches instead of full-scale images is not supported in the current implementation. However, this feature could indeed be beneficial for applications like small-object detection in microscopy. If you or anyone else in the community is interested in contributing to this feature, we would be happy to fast-track its development. Your contributions would be greatly appreciated.
