### ISSUE TITLE
Prediction error - AttributeError: 'Annotator' object has no attribute 'draw'

### ISSUE THREAD

**Issue by Papuszkin** [ultralytics/ultralytics#1979]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I've trained a custom model using my data. While trying to predict using this model with:

`yolo predict model="runs/detect/train12/weights/best.pt" source="ear data - no labels/000150_0.png"`

I get an error:

```
Ultralytics YOLOv8.0.74  Python-3.10.9 torch-2.0.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3060 Ti, 8192MiB)
Model summary (fused): 268 layers, 68146680 parameters, 0 gradients, 257.5 GFLOPs

Traceback (most recent call last):
  File "C:\Users\ath\anaconda3\Scripts\yolo-script.py", line 33, in <module>
    sys.exit(load_entry_point('ultralytics', 'console_scripts', 'yolo')())
  File "c:\users\ath\documents\ultralytics\ultralytics\yolo\cfg\__init__.py", line 391, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "C:\Users\ath\AppData\Roaming\Python\Python310\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "c:\users\ath\documents\ultralytics\ultralytics\yolo\engine\model.py", line 248, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "c:\users\ath\documents\ultralytics\ultralytics\yolo\engine\predictor.py", line 155, in predict_cli
    for _ in gen:  # running CLI inference without accumulating any outputs (do not modify)
  File "C:\Users\ath\AppData\Roaming\Python\Python310\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "c:\users\ath\documents\ultralytics\ultralytics\yolo\engine\predictor.py", line 233, in stream_inference
    s += self.write_results(i, self.results, (p, im, im0))
  File "c:\users\ath\documents\ultralytics\ultralytics\yolo\engine\predictor.py", line 133, in write_results
    self.plotted_img = result.plot(**plot_args)
  File "c:\users\ath\documents\ultralytics\ultralytics\yolo\engine\results.py", line 223, in plot
    annotator.box_label(d.xyxy.squeeze(), label, color=colors(c, True))
  File "c:\users\ath\documents\ultralytics\ultralytics\yolo\utils\plotting.py", line 82, in box_label
    self.draw.rectangle(box, width=self.lw, outline=color)  # box
AttributeError: 'Annotator' object has no attribute 'draw'
```

I've tried using these Python commands in JupyterLab:
```
from ultralytics import YOLO
model = YOLO("runs/detect/train12/weights/best.pt")
results = model("ear data - no labels/000150_1.png")
results[0]
```
This code works without a problem and returns:
```
ultralytics.yolo.engine.results.Results object with attributes:

_keys: ('boxes', 'masks', 'probs', 'keypoints')
boxes: ultralytics.yolo.engine.results.Boxes object
keypoints: None
keys: ['boxes']
masks: None
names: {0: 'Pocz�tek obr�bka', 1: 'Wysklepienie g⮥ obr�bka', 2: 'Guzek ma��owiny usznej (Darwina)', 3: 'Odcinek �rodkowy obr�bka', 4: 'Odcinek dolny obr�bka', 5: 'Pocz�tek grobelki', 6: 'Trzon grobelki', 7: 'Odnoga g⮡ grobelki', 8: 'Odnoga dolna grobelki', 9: 'Fosa tr꫹tna', 10: 'Fosa wielka', 11: 'Brzeg muszli', 12: 'Jama muszli', 13: 'Wci꣩e przednie', 14: 'Guzek skrawka', 15: 'Zag�ꢩenie skrawka', 16: 'Skrawek', 17: 'Wci꣩e miꤺyskrawkowe', 18: 'Przeciwskrawek', 19: 'Fosa poprzeczna', 20: 'Obrys p�atka', 21: 'Guzek p�atka', 22: 'Fosa p�atka', 23: 'Wci꣩e p�atka'}
orig_img: array([[[11, 10,  1],
        [14, 14, 12],
        [10, 11,  7],
        ...,
        [13, 11, 11],
        [13, 13,  8],
        [13,  9, 13]],

       [[16, 12, 13],
        [ 9, 11, 11],
        [12, 10, 10],
        ...,
        [12,  8,  8],
        [15, 14, 10],
        [ 9,  7,  9]],

       [[15, 12,  9],
        [12,  9,  8],
        [10, 12, 15],
        ...,
        [10, 11,  0],
        [15, 11,  7],
        [10, 11, 10]],

       ...,

       [[15, 15, 19],
        [19, 18, 20],
        [16, 21, 18],
        ...,
        [17, 14, 13],
        [11, 14, 11],
        [16, 13, 15]],

       [[13, 17, 18],
        [17, 20, 18],
        [21, 15, 16],
        ...,
        [15, 16, 10],
        [11, 15, 15],
        [15, 13, 15]],

       [[16, 20, 15],
        [17, 16, 14],
        [19, 14, 17],
        ...,
        [14, 11, 11],
        [12, 11, 15],
        [ 9, 14, 12]]], dtype=uint8)
orig_shape: (3731, 2773)
path: 'C:\\Users\\ath\\Documents\\ultralytics\\ear data - no labels\\000150_1.png'
probs: None
speed: {'preprocess': 0.0, 'inference': 70.01590728759766, 'postprocess': 2.000570297241211}
```
However when I try to plot the results using:
`results[0].plot()`
I get the same error as above.

I've also tried swapping the model for the default one ('yolov8n.pt'). And with this model there is no error. Is it a problem with my model? Or some wierd predict bug?

### Environment

 - Ultralytics YOLOv8.0.74  Python-3.10.9 torch-2.0.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3060 Ti, 8192MiB)
 - Windows 11
 - Python 3.10.9

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Papuszkin 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by glenn-jocher** [comment]
@Papuszkin I tried inference on images with spaces in the filenames and everything works correctly for me. It's possible your model may simply be out of date, but unless we have a minimum reproducible example there's nothing for us to do.

<img width="962" alt="Screenshot 2023-04-12 at 14 09 15" src="https://user-images.githubusercontent.com/26833433/231452789-7637dfd1-e2c7-4b84-ae72-15bdcf2c54c5.png">

**Comment by Papuszkin** [comment]
Hi. Thank you for responding! I've made a new custom model and the issue still exists. Should I send you the model for testing and update the issue with a minimum reproducible example?

**Comment by Papuszkin** [comment]
OK, I will work on that.

**Comment by Papuszkin** [comment]
The custom model on my data is made and used via these commands:
```
!yolo train data="ear data/dataset.yaml" model=yolov8x.pt epochs=3 imgsz=380 batch=16
!yolo predict model="runs/detect/train23/weights/best.pt" source="ear data - no labels/000150_0.png"
```
doesn't work. 

I've also created a custom model using COCO128 and tested it using commands below:
```
!yolo train data=coco128.yaml model=yolov8x.pt epochs=3 imgsz=380 batch=16
!yolo predict model="runs/detect/train24/weights/best.pt" source="ear data - no labels/000150_0.png"
```
This works without a problem.

I've previously used YOLOv5 on the same data without a problem few days ago. There are no problems during training ora validation. So this seems to be a problem with my data. But why wouldn't it work with YOLOv8 but works with YOLOv5? I could send the dataset.yaml or the .pt file but I don't know if it's any use.

**Comment by glenn-jocher** [comment]
@Papuszkin it's difficult to determine why YOLOv8 is experiencing problems on your custom dataset without further information. However, it's possible that there may be an issue with the formatting or labeling of your data that is causing the problem with YOLOv8. It's encouraging to hear that you have successfully trained a custom model using COCO128, so this may be a good starting point for further exploring the issues with your custom dataset. It's also important to check the formatting of the YOLOv8 commands that you are using to ensure that they are correctly specifying the paths to your data and model files.

**Comment by Papuszkin** [comment]
@glenn-jocher I have great news! I figured out what the issue was. I was using polish symbols (ąęłćś etc.) in the dataset.yaml file. After I removed them it fixed it.

Wierd issue because as I've said they weren't a problem for YOLOv5 but I'm glad I got it working.

**Comment by glenn-jocher** [comment]
Excellent work @Papuszkin for identifying and fixing the issue with your dataset. In general, it's best to avoid using non-ASCII characters in dataset files as it can lead to unexpected problems, like the one you faced. While YOLOv5 may have processed your dataset without issue, YOLOv8 may be more sensitive to certain types of data formatting issues. It's great that you were able to solve the problem and I hope this experience helps you in the future should you face similar issues.

**Comment by Papuszkin** [comment]
I've run into this problem several times before, strangely enough I'd forgotten about it. Thank you again for your help.

**Comment by glenn-jocher** [comment]
Certainly! 

The problem @Papuszkin faced was that YOLOv8 wasn't able to correctly read some of the images in their custom dataset due to the use of non-ASCII characters in the labels. While these types of characters may not cause issues in all deep learning frameworks or versions, it's generally best to avoid using them altogether. It's ultimately unclear whether there was a technical reason for this issue given that YOLOv5 was previously able to handle the same dataset without issue. Nonetheless, this experience highlights the importance of carefully examining your data for formatting issues or potential incompatibilities before training your model.

**Comment by glenn-jocher** [comment]
@Papuszkin hey I'm going to see if I can reproduce, because after looking at this non-ascii should be working fine, just like YOLOv5.

**Comment by glenn-jocher** [comment]
@Papuszkin I can reproduce with the non-ascii characters in a class name. I'll try to debug the issue and push a fix.

**Comment by Papuszkin** [comment]
I'm glad to hear it. This fix could save headaches for some people.

**Comment by glenn-jocher** [comment]
@Papuszkin sure, as you pointed out, it's best practice to avoid using non-ASCII characters in dataset files to minimize the chance of errors. However, this is not always practical or possible, and therefore it is best practice for data processing tools to handle such characters correctly. In this particular case, while the issue wasn't immediately apparent, it was eventually traced to the use of non-ASCII characters in the dataset.yaml file. The solution to this problem was to remove the non-ASCII characters, which effectively fixed the issue. The fact that YOLOv5 didn't produce any errors when using non-ASCII characters highlights that YOLOv8 may be more sensitive to certain types of data formatting issues.

**Comment by glenn-jocher** [comment]
@Papuszkin this bug is all fixed in https://github.com/ultralytics/ultralytics/pull/1967/commits/aff1d8177f4f3ca1b9198a3a91c26922e47f3ca7 which will be published in 8.0.75 shortly.

**Comment by Papuszkin** [comment]
@glenn-jocher For me it wasn't a big issue but as you've said avoiding non-ASCII characters is not always possible.

I'm happy that you could fix it! I will try it out in the morning.

**Comment by glenn-jocher** [comment]
You're right, @Papuszkin, avoiding non-ascii characters in data files is not always possible or practical. It's great to know that there is now a fix for this bug that will help prevent unexpected issues in YOLOv8. As data processing and preparation is such a critical part of developing machine learning models, it's important that these tools function reliably and consistently under normal usage, which includes handling common character sets. Thank you for bringing this issue to our attention and thank you to the Ultralytics team for fixing it in a timely manner.

**Comment by Papuszkin** [comment]
I've just tried out the update and it works without a problem! Thank you all one more time.

**Comment by glenn-jocher** [comment]
I'm glad to hear that the update fixed the issue you were experiencing, @Papuszkin! It's important to ensure that the tools we use for developing machine learning models function reliably and consistently, and it's great to see that the Ultralytics team was able to provide a fix for this bug in YOLOv8. As always, if you encounter any further issues or have any other questions, don't hesitate to ask!
