### ISSUE TITLE
GPU is not used although is enabled.

### ISSUE THREAD

**Issue by xrispa-m** [ultralytics/ultralytics#1982]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi! I'm trying to use Yolov8 in a Jetson AGX Orin developer kit with CUDA and cuDNN enabled.

`torch.cuda.is_available()` returns True and `cv2.cuda.getCudaEnabledDeviceCount()` returns 1.

I've also set 
```
device = torch.device("cuda")
model = YOLO("dnn_model/yolov8l.pt")
model.to(device)
```

and 

`result = model(frame, agnostic_nms=True)[0]`

The CUDA version is 11.4 and the cuDNN version is 8.6, the PyTorch version is 1.14 (build from source according to nvidia's instructions for the Jetson Orin) and the torchvision version is 0.14 (also built from source).

When I execute the code from the terminal, the speed is approximately 35 ms. However, when I'm trying to run the code from VS code using Flask, it takes up to 64000 ms.

Any advice on this??

Thanks!

**Comment by glenn-jocher** [comment]
```python
result = model(image, device=0)
```

See https://docs.ultralytics.com/modes/predict for details.

**Comment by glenn-jocher** [comment]
@xrispa-m, based on your description, it sounds like the YOLOv8 is functioning correctly, since `torch.cuda.is_available()` returns True and `cv2.cuda.getCudaEnabledDeviceCount()` returns 1. The issue might be related to the environment or the load that VS code is putting on the system. Try running YOLOv8 from the command line or another environment, and if it works substantially faster, it might indicate the issue with VS Code. You can try optimizing system performance or check if there are any conflicts with other running processes. If the issues persist, you are welcome to open a new issue on the YOLOv8 Github repository, and we will help you out.

**Comment by glenn-jocher** [comment]
@xrispa-m yes, it is possible that there could be similar issues with different frameworks such as Torch. One approach might be to modify your code to implement a similar back-end approach to YOLOv4, for example, using Torch's preferred device, CPU or CUDA. CUDA will use GPU acceleration for YOLOv8 and should be faster, as in YOLOv4. Additionally, there might be some environmental factors that you can address, for example, your system performance or conflict with other processes that might be slowing down the detection. However, since every system and task is unique, these are just general suggestions. It might be necessary to create a new issue in the YOLOv8 Github repository to obtain a more specific solution after further analysis.
