### ISSUE TITLE
Tracking way slower than predict

### ISSUE THREAD

**Issue by schelmi1** [ultralytics/ultralytics#1990]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, 

im running YOLOv8 inference on a stream of images which has to be around 30fps.
With model.predict i can achieve this with an old GTX1070 (even faster with TensorRT) on a custom trained yolov8s.
However if im using model.track i only get around 3-4fps. 

```python
model = YOLO('my_model.pt')
while True:
     img = read_from_buffer()
     results = model.track(img, device=0, verbose=False)
     #do something with results...

```

Is this normal? Is there a way to get somehow near the performance of model.predict?
thanks

**Comment by glenn-jocher** [comment]
@schelmi1 hello! It's normal for model.track to be slower than model.predict as it needs to perform additional processing to track objects across frames. However, there are some ways to possibly improve its speed such as reducing the size of the input images or using GPU acceleration. Additionally, we recommend checking the documentation at https://docs.ultralytics.com/ for further tips on optimizing tracking performance.

**Comment by glenn-jocher** [comment]
@schelmi1 I just tested myself and I get about the same speed with these two commands. If you can provide us a reproducible example so we can see a 10x slowdown ourselves that would allow us to investigate, but right now I can't reproduce any slowdowns.

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by schelmi1** [comment]
@glenn-jocher 

Hi,
run model on 30 images:

```python
import os
import cv2
from ultralytics import YOLO

def run(model, files):
    for file in files:
        img = cv2.imread(file)
        results = model.track(img, show=False, verbose=False, device=0, conf=.8) #and model.predict


model = YOLO('/yolov8n.pt') 
imgpath = 'dataset/images/'
files = [os.path.join(imgpath, n) for n in os.listdir(imgpath) if n.lower().endswith('png')]

%load_ext snakeviz
%snakeviz run(model, files[:30])
```

**model.predict**
30 images under 1s runtime (even slow because i read from disk)
![runtime_predict](https://user-images.githubusercontent.com/90637575/231751559-2537459e-9702-42ea-b786-6bd6798bdd24.png)


**model.track**
4.66s runtime
![runtime_track](https://user-images.githubusercontent.com/90637575/231752156-b4370366-9443-41ed-83fe-b5d8e2fa5e1a.png)

gpu load while running model.track is under 10%
so apperantly these two functions  which took most of the time run on my cpu? (AMD Ryzen 7 5800X, 32GB)

**Comment by glenn-jocher** [comment]
@schelmi1 oh your usage is incorrect. Tracking for 1 image is not a standard use case, this provides nothing to track. 

You should profile a video or streaming source like YouTube or your webcam. If you want to create your own custom dataloader then you should use persist=True, otherwise each call to .track() instantiates a completely new tracker.
