### ISSUE TITLE
Unable to use specific GPU

### ISSUE THREAD

**Issue by saumilsdk** [ultralytics/ultralytics#2008]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

model.train(data="coco128.yaml", epochs=100, imgsz=640, device=4)  # train the model

WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@saumilsdk, it looks like the `OMP_NUM_THREADS` warning you are receiving is a warning that is due to the default settings for multi-threading in PyTorch. 

You can ignore this warning, but if you're experiencing any memory issues, you might consider reducing the `batch size`, the number of images processed in each iteration, for your specific machine.

Please let us know if you have any other issues or questions! Feel free to take a look at our [documentation](https://docs.ultralytics.com/) for more details on training and YOLOv8.
