### ISSUE TITLE
predictions are not saved

### ISSUE THREAD

**Issue by Nikunj2696** [ultralytics/ultralytics#2012]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

 I have around 100 folders those contain an image in them. I wanted to run loop for each of the folder and save a result in each of the folder rather than in a result folder folder. Here, I attach the code that written by me, though when I run the code all prediction are saved in first folder rather than each of the folder with a  prediction. Can you please guide me on this issue? @glenn-jocher 
![Screenshot 2023-04-13 153903](https://user-images.githubusercontent.com/82302897/231877712-58461b2d-3ce7-4eee-ab0d-da82d7d5d50b.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello @Nikunj2696, based on the screenshot you provided, it looks like you are using YOLOv3 or YOLOv4 implementations, which we do not currently maintain. I would recommend looking into migrating to the YOLOv8 implementation found at https://github.com/ultralytics/ultralytics. 

Once you are using YOLOv8, please try using the `--save-txt` flag rather than `--save-conf`, and ensure that the `--project` flag is set to `/path/to/your/data`, or the specific directory you wish to save the predictions to, rather than the `path/to/current/dir` that you have used.

Additionally, in order to loop over all of the directories, you will need to modify the `path` variable to point to each directory in a loop. 

I hope that helps, and if you have any further questions, please don't hesitate to ask.

**Comment by glenn-jocher** [comment]
@Nikunj2696 a save directory is created for you by default, but you can define your own with project=PROJECT name=NAME which will save to PROJECT/NAME directory. You can pair this with exist_ok=True to overwrite existing results or reuse the same directory as before.
