### ISSUE TITLE
Only 3 classes are trained

### ISSUE THREAD

**Issue by M-Zubair10** [ultralytics/ultralytics#2054]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a dataset.yaml file clearly stating that
path: '/content/dataset-go'
train: '/content/dataset-go/train/images'
val: '/content/dataset-go/val/images'
test: '/content/dataset-go/test/images'

nc: 14
names: ['hydrant', 'bicycle', 'motorcycle', 'crosswalk', 'car', 'palm tree', 'traffic light', 'bridge', 'bus', 'tractor', 'parking meter', 'stair', 'chimney', 'boat']

and the yolo trained on it just predict 1st three classes

yolo output:
Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% 18/18 [00:02<00:00,  6.69it/s]
                   all        553        115      0.647      0.691      0.674      0.536
              ahydrant        553         65      0.668      0.969      0.892       0.75
               bicycle        553         11      0.658      0.182      0.269      0.184
            motorcycle

also yolo load 818 images from dataset, but i have 1700+ images

**Comment by M-Zubair10** [comment]
Sorry, I figured it out, actually my annotation names are too long and yolo just backgrounding these images
I renamed dataset and it fixed

**Comment by glenn-jocher** [comment]
@M-Zubair10 glad to hear that you were able to figure out the issue with your annotation names. It is important to have consistent and concise annotation names to ensure that your YOLO model can accurately detect and classify objects. In addition, it is possible that not all images in your dataset were included because they may not meet the minimum criteria based on the confidence threshold or object size thresholds that you have set. If you have any more questions, feel free to reach out.
