### ISSUE TITLE
Can I train keypoint detection model with multi-class bbox and each bbox have different keypoints?

### ISSUE THREAD

**Issue by TommyZihao** [ultralytics/ultralytics#2065]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Can I train keypoint detection model with multi-class bbox and each bbox have different keypoints?
In coco8-pose sample dataset, only one class(person) is supported, so I wonder if I can train keypoint detection model with multi-class bbox and each bbox have different keypoints?
For example, there are 3 kinds of bbox in my dataset, crab has 10 keypoints, fish has 15 keypoints, frog has 5 keypoints.

**Comment by glenn-jocher** [comment]
@TommyZihao yes, you can train a keypoint detection model with multi-class bbox where each bbox has different keypoints. The coco8-pose sample dataset only supports one class (person), but that does not limit the ability for YOLOv8 to train on datasets with multiple classes, each with their own set of keypoints. You can create your own dataset with 3 classes, Crab, Fish and Frog, and define their respective keypoints. You can then use YOLOv8 to train on this dataset and detect each class with their corresponding keypoints. It's important to note that the number of keypoints and classes can affect the overall accuracy and speed of the model, so proper tuning and optimization may be required. For more information, please refer to the Ultralytics YOLOv8 documentation at https://docs.ultralytics.com.

**Comment by TommyZihao** [comment]
If then, how do I change yaml file for multiple bbox class?
`coco8-pose.yaml` only contains one class(person)

**Comment by TommyZihao** [comment]
get it, Thanks!

**Comment by glenn-jocher** [comment]
@TommyZihao You are welcome! If you have any further questions, please don't hesitate to ask. Keep in mind that the Ultralytics YOLOv8 framework currently only supports single-class/multi-classes pose training with the same number of keypoints, so you may need to adjust your dataset to fit this format. Additionally, for more information on how to customize your YAML file for multi-class pose training, please refer to the Ultralytics YOLOv8 documentation at https://docs.ultralytics.com.

**Comment by Yangninan** [comment]
> 我认为现在这是不可能的。我们仅支持单类/多类姿势训练，但关键点数量相同。

Is it okay if I'm looking at multiple targets but only the key points of people

**Comment by Yangninan** [comment]
> 我认为现在这是不可能的。我们仅支持单类/多类姿势训练，但关键点数量相同。
Detection of multiple targets including person and detection of human key points. Is that feasible?

**Comment by glenn-jocher** [comment]
@Yangninan yes, it is feasible to use YOLOv8 for detection of multiple targets including person and detection of human key points. The YOLOv8 framework was designed to support this type of task, and can be trained to detect multiple classes, each with their own set of keypoints. However, keep in mind that the number of keypoints and classes can affect the overall accuracy and speed of the model, so tuning and optimization may be required. For more information on how to train a model for multi-class/multi-keypoint detection, please refer to the Ultralytics YOLOv8 documentation at https://docs.ultralytics.com. Also, it's worth noting that YOLOv8 currently only supports multi-keypoint detection with the same number of keypoints for each class.

**Comment by syz825211943** [comment]
@TommyZihao have you found some solutions to solve this problem? looking forward to your reply ：）

**Comment by Yangninan** [comment]
The pose model can be fitted according to the single class target training. The project also supports key training for multi-class targets, provided that the number of key points for all classes is constant. In my case, the key points of people and people, shoes and shoe points are taken as the data set (the key points of shoes are all assigned to 0) and the model cannot fit. I guess it is possible to mark the key points of shoes instead of directly giving the data set of 0 to make the model fit, but I don't have time to mark, so there is no experiment.

**Comment by Yangninan** [comment]
> 你有没有找到一些解决方案来解决这个问题？期待您的回复:)

If you want to train for different types and points, select some obvious points for data supplement in the process of marking for the categories where the number of key points is lower than the maximum number of key points, so as to ensure that the number of all key points in your categories is constant. Training with this kind of data set in the post-processing part removes the bits that you don't need. However, I have not verified this method, and I do not know whether the model can fit, but it can be trained under the current project.

**Comment by glenn-jocher** [comment]
@syz825211943 one possible solution for training on multi-class detection with different numbers of keypoints is to supplement the lower keypoint categories with additional obvious points during the marking process, so that all categories have the same number of keypoints. During training, you can then remove the extra keypoints that you don't need in the post-processing step. However, accuracy and model fitting may be affected by this method, so it should be thoroughly tested to determine its effectiveness. It's important to note that YOLOv8 currently only supports multi-keypoint detection with the same number of keypoints for each class. For more information on how to customize your YAML file for multi-class pose training, please refer to the Ultralytics YOLOv8 documentation at https://docs.ultralytics.com.

**Comment by Yangninan** [comment]
> One possible solution for multiclass detection training with different numbers of keypoints is to supplement lower keypoint categories with additional distinct points during labeling so that all classes have the same number of keypoints. During training, you can remove extra key points that are not needed in the post-processing step. However, this method can affect accuracy and model fit, so it should be thoroughly tested to determine its validity. It is important to note that YOLOv8 currently only supports multi-key detection, with the same number of keys per class. For more information on how to train custom YAML files for multiclass poses, see the Ultralytics YOLOv8 documentation on https://docs.ultralytics.com.

For categories that need to be supplemented, will it affect the fit of the model if I align the points of all categories with zero?

**Comment by glenn-jocher** [comment]
@Yangninan, aligning the points of all classes with zero during training should not affect the model fit, as long as the keypoint coordinates are consistently labeled across all categories. By aligning the points to zero, you are essentially using a common reference point for all classes, which can help simplify post-processing and make it easier to visualize and analyze the results. However, it is important to note that this approach may not be suitable for all datasets, and may require additional validation and testing to ensure that the model is accurately detecting the keypoint locations. Additionally, it's important to keep in mind that YOLOv8 currently only supports multi-keypoint detection with the same number of keypoints for each class. For more information on how to train custom YAML files for multi-class pose detection, please refer to the Ultralytics YOLOv8 documentation at https://docs.ultralytics.com.

**Comment by rafluq** [comment]
@glenn-jocher when you mean YOLOv8 currently only supports multi-keypoint detection with the same number of keypoints for each class, do you mean that I can train the model with a dataset like this?

class 1: person, number of keypoints: 17
class 2: car, number of keypoints: 4
class 3: bicycle, number of keypoints: 2
class 4: racket, number of keypoints: 1
etc

**Comment by Laughing-q** [comment]
@rafluq no, you can only train the model with a dataset that has the same number of keypoints, like this:
class 1: person, number of keypoints: 17
class 2: car, number of keypoints: 17
class 3: bicycle, number of keypoints: 17
class 4: racket, number of keypoints: 17

**Comment by blackCmd** [comment]
@glenn-jocher 
I understand that I can train multi-class using one model as long as the number of keypoints is the same.
In that case, how should I handle `flip_idx` in the yaml file?
Should I comment it out and set `fliplr=0.0` in the `train.py` file?

**Comment by glenn-jocher** [comment]
@blackCmd hi there,

Regarding your question, when training a multi-class keypoints model with YOLOv8, the `flip_idx` parameter in the YAML file is used to specify the keypoints that should be flipped during data augmentation. The `flip_idx` values correspond to the index of keypoints in the list (starting from 0) that you want to flip horizontally.

If you want to train a multi-class keypoints model where each class has a different number of keypoints, you will need to handle the `flip_idx` parameter accordingly. Since YOLOv8 currently only supports multi-keypoint detection with the same number of keypoints for each class, you would need to assign the same `flip_idx` values to all classes that share the same number of keypoints. This ensures that the keypoints are flipped consistently during data augmentation.

To handle this, you can comment out the `flip_idx` parameter in the YAML file and set `fliplr=0.0` in the `train.py` file. This will disable horizontal flipping for all keypoints, as flipping keypoints with different numbers can lead to incorrect annotations.

Although data augmentation with `fliplr` can be useful, it is currently limited to keypoints that have the same number for all classes. We appreciate your suggestion to enhance the code to support multiple `flip_idx` values for training multiclass keypoints, and we'll consider it for future updates.

I hope this clarifies the situation. If you have any further questions, feel free to ask!

Best regards,
Glenn Jocher

**Comment by Charlie-crl** [comment]
> @rafluq no, you can only train the model with a dataset that has the same number of keypoints, like this: class 1: person, number of keypoints: 17 class 2: car, number of keypoints: 17 class 3: bicycle, number of keypoints: 17 class 4: racket, number of keypoints: 17

Hi, @Laughing-q  So how to label objects with less than 17 key points in other categories such as car and bicycle? In order to ensure that all classes have the same number of key points, the redundant points of other classes are labeled (0,0,0). Is this ok?

Looking forward to your reply, thank you very much

**Comment by glenn-jocher** [comment]
@Charlie-crl hi, 

To handle keypoint annotation for objects with fewer keypoints than the maximum (for example, 17 in the case you've mentioned), you could indeed label the extra or "redundant" keypoints as (0,0,0). This would ensure that each object across all classes has the same total number of keypoints for training, which is a necessity for the current version of YOLOv8. 

However, keep in mind that this method essentially introduces a significant number of "nonexistent" keypoints into your dataset. This could potentially affect the model's learning and subsequent keypoint detection performance. We recommend careful validation and testing to ensure that the trained model can accurately detect the keypoints that are truly present.

Thank you for your query and we hope this helps! 

Best,
Glenn Jocher

**Comment by Laughing-q** [comment]
@Charlie-crl ah that sounds interesting! I've never tried this, don't know if it would work but I think it's worth trying. :)
And please tell me about the experimental results if you're going to try it. Thanks!

**Comment by Charlie-crl** [comment]
@glenn-jocher hi,

Thank you so much! Your suggestion is very effective, and I will take some measures to reduce the impact of introducing a large number of "non-existent" points.

Best,
Charlie Chen

**Comment by Charlie-crl** [comment]
@Laughing-q ah ok well,I'm currently experimenting and it seems to be working fine. :)
If you are interested, I am very happy to share with you the follow-up results.

**Comment by glenn-jocher** [comment]
@Charlie-crl 

That's great to hear! I'm glad the experiments seem to be progressing well. I'd be definitely interested in hearing about your results and any interesting findings you come across. Your work could provide valuable insights for others working on similar projects. Remember, though, it's crucial to validate the model thoroughly, considering the uniqueness of the problem.

Thank you for your willingness to share, and best of luck with your experiments!

Best,
Glenn Jocher

**Comment by Laughing-q** [comment]
@Charlie-crl That would be great! THANKS!

**Comment by sarpx** [comment]
@glenn-jocher  Hello, does it support a maximum of 17 keypoints? So it doesn't support 50 key points?

**Comment by glenn-jocher** [comment]
@sarpx hi there,

YOLOv8 does not inherently limit you to a maximum of 17 keypoints; you can have datasets with more than that. The key is ensuring consistency across the dataset - all classes should have the same number of keypoints. This might mean padding classes with fewer natural keypoints to match the class with the most. 

Your example of 50 keypoints is reasonable as long as your dataset, annotations, and the corresponding configuration files are structured to handle this many points consistently. The model should learn to predict the keypoints correctly as long as they are clearly defined and annotated across your dataset.

However, keep in mind that with a higher number of keypoints, the complexity of your model increases and it may require more data and computational resources to train effectively.

If there's anything else you're curious about or need assistance with, feel free to reach out.

**Comment by JGGGBang** [comment]
> [@TommyZihao](https://github.com/TommyZihao) yes, you can train a keypoint detection model with multi-class bbox where each bbox has different keypoints. The coco8-pose sample dataset only supports one class (person), but that does not limit the ability for YOLOv8 to train on datasets with multiple classes, each with their own set of keypoints. You can create your own dataset with 3 classes, Crab, Fish and Frog, and define their respective keypoints. You can then use YOLOv8 to train on this dataset and detect each class with their corresponding keypoints. It's important to note that the number of keypoints and classes can affect the overall accuracy and speed of the model, so proper tuning and optimization may be required. For more information, please refer to the Ultralytics YOLOv8 documentation at https://docs.ultralytics.com.

hello,
Does this mean that I can use the pt model trained in one scenario and continue training in another similar scenario, the difference is that the class names are slightly different, such as class2 changes from "box "to "phone", or a few more classes are added?

**Comment by glenn-jocher** [comment]
@JGGGBang yes, you can absolutely use transfer learning with YOLO models to adapt a pretrained model from one scenario to another similar scenario. You can start training from a pretrained `.pt` model even when class names change (like "box" to "phone") or when additional classes are added. The model will adapt its classification head while leveraging the feature extraction capabilities learned from the original training. Just ensure your new dataset follows the same keypoint structure requirements - all classes must have the same number of keypoints for pose detection models.
