### ISSUE TITLE
Not able to run on a single frame

### ISSUE THREAD

**Issue by Thecoder1012** [ultralytics/ultralytics#2094]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In ```model.track()``` we are sending video path as ```source``` but I've a single image or suppose the frame is coming from external cctv cameras. How to send input sequence framewise in ```model.track()```?

### Additional

Can we do it by process_video() by adding a callback from supervision? Is there any way?

```
def process_video(
    source_path: str,
    target_path: str,
    callback: Callable[[np.ndarray, int], np.ndarray],
) -> None:
    """
    Process a video file by applying a callback function on each frame and saving the result to a target video file.
    Args:
        source_path (str): The path to the source video file.
        target_path (str): The path to the target video file.
        callback (Callable[[np.ndarray, int], np.ndarray]): A function that takes in a numpy ndarray representation of a video frame and an int index of the frame and returns a processed numpy ndarray representation of the frame.
```

**Comment by glenn-jocher** [comment]
@Thecoder1012 to pass individual frames to ```model.track()``` instead of a video, you can simply pass a [NumPy](https://numpy.org/) array of size *(height, width, 3)* to the ```predict()``` method, e.g.:

```python
import cv2
import numpy as np
from yolov5 import Model

cap = cv2.VideoCapture(0)  # capture from camera
model = Model(weights='yolov5s.pt')

while True:
    _, img = cap.read()
    results = model.predict(img)  # run detection on image
    ...
```

Regarding ```process_video()```, you can use it to process a video frame by frame and save the results as a video. You can modify the callback function to run model inference on each frame of the video input and pass the output to another function that will save the output as a video. You can also save the results as an image sequence using the ```cv2.imwrite()``` function.
