### ISSUE TITLE
Docs Feedback for Export page at https://docs.ultralytics.com//modes/export/

### ISSUE THREAD

**Issue by NikitaShubin** [ultralytics/ultralytics#2100]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I think there is a mistake in the line:
`image size as scalar or (h, w) list, i.e. (640, 480)`
(640, 480) should be (w, h) in my opinion.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hi @NikitaShubin, thanks for your feedback regarding the YOLOv8 documentation, we appreciate your help. We apologize for the confusion on this matter, you are correct that the correct order is (width, height), so it should be (480, 640) instead of (640, 480). Thanks for bringing this to our attention, we will update the documentation shortly. Also, we appreciate your willingness to help us improve the project, we are always excited to receive contributions from the community. Please make sure to follow our [contribution guidelines](https://github.com/ultralytics/ultralytics/blob/main/CONTRIBUTING.md) when submitting your PR, and we will be happy to review it.
