### ISSUE TITLE
set batch size in onnx export

### ISSUE THREAD

**Issue by SafrMSD** [ultralytics/ultralytics#2101]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

how can I set a fixed batch size not equal to 1 in the model.onnx?

**Comment by glenn-jocher** [comment]
@SafrMSD it is not recommended to set a fixed batch size when exporting the model to ONNX because it will limit the model's ability to handle different batch sizes during inference. However, if you still want to set a fixed batch size, you can modify the input dimensions of the model to reflect the desired batch size. Please note that this will only work for that specific batch size and the model will need to be re-exported if a different batch size is required. For more information on exporting and using the ONNX format with YOLOv8, please refer to the documentation at https://docs.ultralytics.com/.

**Comment by glenn-jocher** [comment]
@SafrMSD To change the input batch size for an exported model, the input dimensions of the model must be modified. This can be achieved by accessing the input tensor dimension and changing the required batch size. However, as mentioned earlier, it is not recommended to set a fixed batch size because it may limit the model's ability to handle different batch sizes during inference. Therefore, it is important to keep this in mind before modifying the input dimensions of the model. Additionally, refer to the model documentation and the PyTorch library for more information on modifying the input dimensions of a trained model.

**Comment by ClaudioCimarelli** [comment]
Hello @glenn-jocher, I have a similar question.
I am exporting the model to ONNX using half-precision; the dynamic option is incompatible. It's fine to specify the image size for me, but I would like a batch size (fixed or dynamic) greater than 1. Is it possible?

The command I am using to export is `model.export(format='onnx', imgsz=512, dynamic=False, half=True, simplify=True)`, loading a `YOLOv8m-segm` network, and I obtain the following initial dimension plotted: 
<img width="221" alt="image" src="https://github.com/ultralytics/ultralytics/assets/7337279/39371f29-1a35-4707-bcda-b7f0e26b172b">

I have another question regarding the image size. When it is specified at training, do the images get resized internally to the specific image size with some function (opencv maybe)? If I load a pre-trained model, do they have a specific image size, or can they be run with any size (without internal resizing applied)?

Thank you for your help.

**Comment by iaverypadberg** [comment]
I too am looking to set a static batch size when exporting my yolov8 model to onnx. There is not much out there on how to reshape the input tensor of a yolov8 model using PyTorch, so @glenn-jocher it would be fantastic if you could point us in the right direction here. Perhaps a code example of just a link to the right function. Thanks!

**Comment by vchaparro** [comment]
Hi @glenn-jocher , 
Default value for the batch size when exporting to onnx is 1, thus I cannot use dynamic batchsize when calling the my onnx model in Triton Server, and I have to use batch size 1. How can I get a dynamic batchsize?

**Comment by vchaparro** [comment]
Thanks a lot for your response @glenn-jocher ! and sorry for my oversight in reviewing the documentation, I missed that parameter.

**Comment by glenn-jocher** [comment]
@vchaparro No worries at all! If you have any more questions or need further assistance, feel free to reach out. Happy to help! 😊🚀

**Comment by hungtrieu07** [comment]
I'm using a pre-train model and it have input 1x3x640x640. Is that needed to re-train and export with parameter dynamic=True?

**Comment by glenn-jocher** [comment]
@hungtrieu07 hello! 👋 If your current pre-trained model doesn't support a dynamic batch size and you need this functionality, you'll indeed have to re-export the model with the `dynamic=True` parameter. Here's a quick example on how you could do this:

```python
from ultralytics import YOLO

# Load your pre-trained model
model = YOLO('path/to/your/model.pt')

# Re-export with dynamic batch size
model.export(format='onnx', imgsz=640, dynamic=True)
```

This will allow your model to accept variable batch sizes. If you have any more questions or run into issues, feel free to ask!

**Comment by hungtrieu07** [comment]
> @hungtrieu07 hello! 👋 If your current pre-trained model doesn't support a dynamic batch size and you need this functionality, you'll indeed have to re-export the model with the `dynamic=True` parameter. Here's a quick example on how you could do this:
> 
> ```python
> from ultralytics import YOLO
> 
> # Load your pre-trained model
> model = YOLO('path/to/your/model.pt')
> 
> # Re-export with dynamic batch size
> model.export(format='onnx', imgsz=640, dynamic=True)
> ```
> 
> This will allow your model to accept variable batch sizes. If you have any more questions or run into issues, feel free to ask!

I got that, thank you.

**Comment by glenn-jocher** [comment]
@hungtrieu07 you're welcome! If anything else comes up, don't hesitate to reach out. Happy coding! 😊

**Comment by rm-ra** [comment]
@glenn-jocher 
I want to set batch as dynamic, imgsz=640， But 'dynamic=True' will also set h and w as dynamic, I tried it‘ `yolo export model=runs/detect/train/weights/best.pt format=onnx  imgsz=640 dynamic=True opset=11`’  Still dynamic batch and h, w

**Comment by rm-ra** [comment]
> [@glenn-jocher](https://github.com/glenn-jocher) I want to set batch as dynamic, imgsz=640， But 'dynamic=True' will also set h and w as dynamic, I tried it‘ `yolo export model=runs/detect/train/weights/best.pt format=onnx imgsz=640 dynamic=True opset=11`’ Still dynamic batch and h, w

I find it,there   ultralytics/engine/exporter.py 561

**Comment by glenn-jocher** [comment]
@rm-ra You're right, the current implementation in `ultralytics/engine/exporter.py` sets all dimensions (batch, height, width) as dynamic when you use `dynamic=True`. Looking at line ~561 in that file, the dynamic dictionary is defined as:

```python
dynamic = {"images": {0: "batch", 2: "height", 3: "width"}}  # shape(1,3,640,640)
```

If you want only the batch dimension to be dynamic while keeping height and width fixed, you'd need to modify this code in the exporter. A quick workaround would be to:

1. Make a copy of the exporter.py file
2. Change the dynamic dictionary to only include the batch dimension: 
   ```python
   dynamic = {"images": {0: "batch"}}  # Only batch is dynamic
   ```
3. Use your modified exporter

Alternatively, you could also export normally and then modify the ONNX model using the ONNX API to set specific dimensions as dynamic. There's currently no built-in parameter to control which specific dimensions should be dynamic.

**Comment by rm-ra** [comment]
![Image](https://github.com/user-attachments/assets/419fb918-9194-4aa7-b424-39a0b394594e)

@glenn-jocher 
After only changing the dynamic batch as before, I encountered an issue when exporting onnx. The output of onnx is tensor: float32 [batch, Concaoutput 0udim1, anchors] instead of tensor: float32 [batch, 5,8400]. However, if the batch and imgsz are fixed, it is tensor: float32 [1,5,8400]. What could be the problem?
Also, I tried using onnx modifier to directly change fixed batches to dynamic batches, but the input and output would become [dynamic, 3,640,640] and [dynamic, 5,8400]. Will this word affect its usage

**Comment by rm-ra** [comment]
> [@rm-ra](https://github.com/rm-ra) You're right, the current implementation in `ultralytics/engine/exporter.py` sets all dimensions (batch, height, width) as dynamic when you use `dynamic=True`. Looking at line ~561 in that file, the dynamic dictionary is defined as:
> 
> dynamic = {"images": {0: "batch", 2: "height", 3: "width"}}  # shape(1,3,640,640)
> If you want only the batch dimension to be dynamic while keeping height and width fixed, you'd need to modify this code in the exporter. A quick workaround would be to:
> 
> 1. Make a copy of the exporter.py file
> 2. Change the dynamic dictionary to only include the batch dimension:
>    dynamic = {"images": {0: "batch"}}  # Only batch is dynamic
> 3. Use your modified exporter
> 
> Alternatively, you could also export normally and then modify the ONNX model using the ONNX API to set specific dimensions as dynamic. There's currently no built-in parameter to control which specific dimensions should be dynamic.

**Comment by glenn-jocher** [comment]
@rm-ra The issue you're encountering is that when you modify the dynamic dictionary for just the input, you also need to handle the output tensor's dynamic configuration. In the ONNX export code, when `dynamic=True`, it automatically sets up dynamic axes for both input and output tensors.

Looking at the [export_onnx function](https://docs.ultralytics.com/reference/engine/exporter/), for detection models it sets:
```python
dynamic["output0"] = {0: "batch", 2: "anchors"}  # shape(1, 84, 8400)
```

To fix your issue, when you modify the exporter, you should set:
```python
dynamic = {
    "images": {0: "batch"},  # Only batch is dynamic for input
    "output0": {0: "batch"}  # Only batch is dynamic for output, keep other dims fixed
}
```

This will give you the expected output shape `[batch, 5, 8400]` where only the batch dimension is dynamic. The strange output tensor name you're seeing is likely due to incomplete dynamic axis configuration causing ONNX naming issues.

Regarding your second question about using ONNX modifiers - yes, having `[dynamic, 5, 8400]` output should work fine for inference as long as your inference framework properly handles the dynamic batch dimension.

**Comment by rm-ra** [comment]
```
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/user/.conda/envs/yolo/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 270, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/home/user/.config/Ultralytics/DDP/_temp_3uh6vr1d139903593156864.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-06-07_00:49:16
  host      : user
  rank      : 1 (local_rank: 1)
  exitcode  : -6 (pid: 3169506)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 3169506
============================================================
Traceback (most recent call last):
  File "/home/user/.conda/envs/yolo/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/user/szp/yolo/ultralytics-main/ultralytics/cfg/__init__.py", line 984, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/user/szp/yolo/ultralytics-main/ultralytics/engine/model.py", line 797, in train
    self.trainer.train()
  File "/home/user/szp/yolo/ultralytics-main/ultralytics/engine/trainer.py", line 223, in train
    raise e
  File "/home/user/szp/yolo/ultralytics-main/ultralytics/engine/trainer.py", line 221, in train
    subprocess.run(cmd, check=True)
  File "/home/user/.conda/envs/yolo/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/user/.conda/envs/yolo/bin/python3.9', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '52731', '/home/user/.config/Ultralytics/DDP/_temp_3uh6vr1d139903593156864.py']' returned non-zero exit status 1.
```
@glenn-jocher 
I made the changes according to this, but there is still a problem. Then I found that when the training ended, the terminal reported an error. Is this the cause? How can I solve this error
dynamic = {
    "images": {0: "batch"},  # Only batch is dynamic for input
    "output0": {0: "batch"}  # Only batch is dynamic for output, keep other dims fixed
}

![Image](https://github.com/user-attachments/assets/fa9778bc-79ca-470d-bde3-120fed99ebfb)

**Comment by glenn-jocher** [comment]
@rm-ra The training error you're showing is a separate issue from the export modifications. The `SIGABRT` signal and distributed training failure suggest a DDP (Distributed Data Parallel) problem during training, likely due to memory issues or GPU synchronization problems.

To troubleshoot this systematically:

1. First, try training without DDP (single GPU) to see if training completes successfully
2. Once you have a successfully trained model, then test your export modifications

For the export issue, test your dynamic batch modifications on an existing trained model first:

```python
from ultralytics import YOLO

# Load an existing trained model
model = YOLO('yolov8n.pt')  # or your trained model
model.export(format='onnx', imgsz=640)  # Test with your modified exporter
```

The training error needs to be resolved independently - try reducing batch size, checking GPU memory, or using single GPU training first.
