### ISSUE TITLE
Error convert yolov8m-seg-custom.pt to tflite 

### ISSUE THREAD

**Issue by faisalhazry** [ultralytics/ultralytics#2104]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

This is my python file 
![image](https://user-images.githubusercontent.com/121289405/232814916-d0259d62-cff3-4580-8661-04bc27214f30.png)

when i run the code i got error 
![image](https://user-images.githubusercontent.com/121289405/232815242-624a99bb-c23a-4305-9373-06267ed6f2a9.png)

### Environment

i am using Python 3.10.10 | packaged by Anaconda, Inc.

Ultralytics YOLOv8.0.81  Python-3.10.10 torch-2.0.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)

OS= Window 11

### Minimal Reproducible Example

Running this code directly also didn't work 
`yolo export model= yolov8m-seg.pt format=tflite`

![image](https://user-images.githubusercontent.com/121289405/232817044-0f4f5127-d566-48d7-b9e2-08f116745b7f.png)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@faisalhazry, thanks for sharing this issue 🙏. The error message indicates that the `onnx` module is not found, which is a required dependency to convert models to the `ONNX` format.☝️

To avoid installation issues of dependencies in different environments, we recommend to install Ultralytics YOLOv8 on a [clean Python environment](https://www.pythonforbeginners.com/basics/how-to-use-python-virtualenv/). You may consider creating a new Python 3.7 environment via `virtualenv`, activate it, and reinstall all dependencies including `onnx` before retrying. 

For reducing the dependencies needed and creating a lighter model, we recommend considering the YOLOv8 weights exported in TensorFlow (`.pb`), Keras (`.h5`), or PyTorch (`.pt`) formats. Finally, you may want to refer to the [export section in the YOLOv8 documentation](https://docs.ultralytics.com/yolov8/usage/#export) for more information on exporting YOLOv8 models. 

Let us know if that helps. Thanks!

**Comment by xsy0520** [comment]
I have the same problem. Have you solved it？

**Comment by glenn-jocher** [comment]
@xsy0520 hello! The issue you are experiencing could be caused by the `onnx` module being unavailable, which is a required dependency for exporting models in the `ONNX` format. To fix the problem, you may want to check if `onnx` is properly installed, or try setting up a new Python environment with a fresh installation of required dependencies, including `onnx`, before exporting your model again. 

I hope this helps! Let us know if you still encounter any issues.

**Comment by faisalhazry** [comment]
@xsy0520 @glenn-jocher 

I think there are some problem with segmentation convert yolov8 .pt into tflite . About the onnx file my Export actually manage to convert from .pt to ONNX but ONNX to Tflite have error.

When i create and change new data set into object detection and train again using same environment  i manage to convert the .pt into tflite.

**Comment by glenn-jocher** [comment]
@faisalhazry, thank you for reaching out to us about this issue. We apologize for the difficulties you are experiencing with converting your YOLOv8 segmentation model from `.pt` to `.tflite` format. 

One possibility for why you encountered an error on converting to TFLite could be due to missing dependencies or some other configuration error. To ensure proper functioning, it's always a good idea to check and confirm that you have installed all required dependencies, including `onnx`.

It is great that you managed to convert your YOLOv8 object detection model to `.tflite`, and we would recommend you to try the same workflow and environment on your segmentation model. Additionally, keep in mind that you can refer to the YOLOv8 documentation on exporting models found [here](https://docs.ultralytics.com/yolov8/usage/#export) for more information on the recommended export process for the YOLOv8 architecture.

We hope this information helps you! Let us know if you have further questions.

**Comment by edublanco** [comment]
hello @glenn-jocher I am also having issues exporting the model to tflite format, could you make a detailed example of how to do it or what dependencies I should have installed?
