### ISSUE TITLE
AttributeError: partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a circular import)

### ISSUE THREAD

**Issue by Shengcheng-Ma** [ultralytics/ultralytics#2113]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I write a dockerfile to deploy on Nvidia Jeston Nano. When I run the container, there is an error shows AttributeError: partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a circular import)

### Environment

The content of dockerfile is as follows：
‘’‘
FROM nvcr.io/nvidia/l4t-pytorch:r35.2.1-pth2.0-py3

RUN apt update \
    && apt install --no-install-recommends -y gcc  libgl1-mesa-glx libglib2.0-0 libpython3-dev gnupg g++ libcairo2-dev

RUN mkdir -p /app
WORKDIR /app
RUN python3 -m pip install --upgrade pip wheel
COPY . /app
RUN pip install pycairo==1.11.1
RUN pip install protobuf==3.3.0
RUN pip install ultralytics==8.0.0
RUN pip install flask uwsgi

CMD [ "uwsgi", "--ini", "/app/uwsgi.ini" ]
’‘’
At the beginning of my code , import cv2. When I run the container, the error is shown in the picture:
![image](https://user-images.githubusercontent.com/88013177/233002143-64628393-83fd-4bc2-9b77-dd964a6d4606.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by aurelm95** [comment]
@Shengcheng-Ma This is probably because the `nvcr.io/nvidia/l4t-pytorch:r35.2.1-pth2.0-py3` expects a specific version of `cv2` and you have changed it. Try to use the image I PR'ed https://github.com/ultralytics/ultralytics/blob/main/docker/Dockerfile-jetson and let me know if it works for you as expected

**Comment by glenn-jocher** [comment]
@Shengcheng-Ma, it appears that the issue you are encountering may be due to a version incompatibility between the `nvcr.io/nvidia/l4t-pytorch:r35.2.1-pth2.0-py3` image and the `cv2` package version you are using. A potential solution could be to use the `Dockerfile-jetson` image which is specific to Jetson devices and has been tested to work with YOLOv8. This should resolve your issue, but please don't hesitate to let me know if you continue to encounter any problems.

**Comment by Shengcheng-Ma** [comment]
The jetpack version of my nvidia jetson nano is 4.6.3 [L4T 32.7.3], I modified my FROM base image version,and I modified the pip install part of my dockerfile to the following, and I can successfully get a docker image.
'''
FROM nvcr.io/nvidia/l4t-ml:r35.2.1-py3

RUN apt update \
    && apt install --no-install-recommends -y gcc git zip curl htop libgl1-mesa-glx libglib2.0-0 libpython3-dev gnupg g++ \
    && apt-get install --reinstall libgstreamer1.0-0

RUN mkdir -p /usr/src/ultralytics
RUN python3 -m pip install --upgrade pip wheel
RUN pip install --no-cache uwsgi flask tqdm matplotlib pyyaml psutil thop pandas   hydra torch torchvision python-multipart "numpy==1.23" 
RUN pip install --no-cache ultralytics  --no-deps

COPY . .
ENV OMP_NUM_THREADS=1
EXPOSE 5000
CMD ["uwsgi", "--ini", "uwsgi.ini"]
'''
But now I have a new problem，When I use `docker run --runtime nvidia --name insect -p 5000:5000 -it insect:ml` to start the container, the result of `torch.cuda.is_available()` is False. I want to know how to invoke the gpu? Is it a torch version problem?

**Comment by hanyuImg** [comment]
i meet the same problem and the image i use is the jetson docker iamge that ultralytics provide, so how did you fix it?

**Comment by Shengcheng-Ma** [comment]
> i meet the same problem and the image i use is the jetson docker iamge that ultralytics provide, so how did you fix it?

When using pip to install the package, specify the version of numpy, and using "--no-deps" to pip install ultralytics.
This is my dockerfile, and it can work now. I hope it can help you.
# Install pip packages 
RUN python3 -m pip install --upgrade pip wheel
RUN pip install --no-cache "numpy==1.23" 
RUN pip install --no-cache ultralytics --no-deps

**Comment by pderrenger** [comment]
@Shengcheng-Ma great to hear that you found a solution! Specifying the version of `numpy` during installation and using the `--no-deps` flag for installing `ultralytics` in your Dockerfile is a good approach to ensure compatibility and resolve the issue. Thank you for sharing your Dockerfile snippet. I'm sure it will be helpful to others facing similar challenges.

**Comment by EmrahErden** [comment]
was getting the same error **module 'cv2' has no attribute '_registerMatType'** when i was trying to install yolov8 on l4t-pytorch:r35.2.1-pth2.0-py3 docker image, which has pytorch preinstalled.
then thanks to @glenn-jocher , realized that i could run a seperate docker image ultralytics/ultralytics:latest-jetson . then later succesfully run yolov8 on jetson agx xavier, by using the created network

here is the flow followed:

- Network Creation: sudo docker network create my_network

- Pulling the Ultralytics Docker Image for Jetson: t=ultralytics/ultralytics:latest-jetson && sudo docker pull $t && sudo docker run -it --ipc=host --runtime=nvidia --network my_network $t

- Running the L4T PyTorch Container and Connecting to the Docker Network: sudo docker run -it --runtime nvidia --network my_network nvcr.io/nvidia/l4t-pytorch:r35.2.1-pth2.0-py3

- Running Sample / Test YOLO Prediction: yolo predict model=yolov8n-seg.pt source='https://youtu.be/LNwODJXcvt4' imgsz=320

my question is, there is probably so much data transfer between these 2 containers. is this method optimal? because inference time is quite critical for one of my applications. do you have any suggestions?

**Comment by EmrahErden** [comment]
@glenn-jocher that is quite a nice tip about running everything with in a single container. 

then i decided to run "only" ultralytics/ultralytics:latest-jetson for test. and realized that, we can also have the inference results by "only" starting the ultralytics/ultralytics:latest-jetson (i didn't start the L4T Pytorch container). :stuck_out_tongue_winking_eye: 
it runs, probably because your ultralytics docker image has all the required libraries installed inside

```
xavibuntu@xavibuntu-desktop:~$ docker ps -a
CONTAINER ID   IMAGE                                           COMMAND       CREATED        STATUS                     PORTS     NAMES
16cda1d2f2a1   nvcr.io/nvidia/l4t-pytorch:r35.2.1-pth2.0-py3   "/bin/bash"   27 hours ago   Exited (0) 21 hours ago              loving_blackwell
3f95ba35e1a9   ultralytics/ultralytics:latest-jetson           "/bin/bash"   40 hours ago   Exited (0) 3 seconds ago             compassionate_swirles
xavibuntu@xavibuntu-desktop:~$ docker start compassionate_swirles
compassionate_swirles
xavibuntu@xavibuntu-desktop:~$ docker attach compassionate_swirles
root@3f95ba35e1a9:/usr/src/ultralytics# yolo predict model=yolov8n.pt source="s-l500.jpg" imgsz=640 conf=0.25 iou=0.45          
Ultralytics YOLOv8.1.29 🚀 Python-3.8.10 torch-2.0.0a0+ec3941ad.nv23.02 CUDA:0 (Xavier, 30991MiB)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

image 1/1 /usr/src/ultralytics/s-l500.jpg: 640x480 (no detections), 109.0ms
Speed: 11.9ms preprocess, 109.0ms inference, 3.2ms postprocess per image at shape (1, 3, 640, 480)
Results saved to /usr/src/ultralytics/runs/detect/predict7
💡 Learn more at https://docs.ultralytics.com/modes/predict
root@3f95ba35e1a9:/usr/src/ultralytics# yolo predict model=yolov8n.pt source="s-l500.jpg" imgsz=640 conf=0.25 iou=0.45
Ultralytics YOLOv8.1.29 🚀 Python-3.8.10 torch-2.0.0a0+ec3941ad.nv23.02 CUDA:0 (Xavier, 30991MiB)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
```

probably, no docker network creation required. and as you said, better to check resource consumption. will try to use jtop for the jetson. 
https://jetsonhacks.com/2023/02/07/jtop-the-ultimate-tool-for-monitoring-nvidia-jetson-devices/
or later use quantization, or onnx & tensorrt. so much to investigate :)

please feel free to suggest, ty :tophat:

**Comment by glenn-jocher** [comment]
Hey @EmrahErden! 🌟

Absolutely right! The `ultralytics/ultralytics:latest-jetson` image is self-sufficient for running YOLOv8 as it bundles all the necessary dependencies, making external environment setups optional for many use cases. It's great to see you're diving deep into optimization and exploring resources like `jtop` for monitoring – it's a fantastic tool for Jetson devices 🛠️.

Quantization and exploring ONNX & TensorRT can indeed offer significant performance boosts, so you're on an exciting path! If you're leaning towards deployment optimization, TensorRT conversions might bring considerable inference speed-ups especially on Jetson platforms.

Feel free dive in deeper, and remember, the journey to optimization is a marathon, not a sprint. Happy experimenting, and keep us posted on your progress!

Cheers! 🚀
