### ISSUE TITLE
Pose Estimation Custom Dataset

### ISSUE THREAD

**Issue by kamalkannan79** [ultralytics/ultralytics#2117]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to create a custom dataset for pose estimation in Yolov8 using an open-source annotation tool? How to create the required txt format to train the custom pose model of Yolov8?

**Comment by glenn-jocher** [comment]
@kamalkannan79 to create a custom dataset for pose estimation in YOLOv8, you can use an open-source annotation tool such as LabelImg or RectLabel to annotate your images. Once your images are annotated, you can convert the annotations to the required YOLOv8 format, which consists of a txt file for each image with the corresponding annotations in a specific format. The format consists of a class label, followed by the normalized x and y coordinates of the center of the object and the width and height of the object, all relative to the image dimensions. You can find more information about the YOLOv8 format in the documentation at docs.ultralytics.com.

**Comment by kamalkannan79** [comment]
Yes ,Thank you, I tried it but the width and height of the object is 0 in all the txt files.

**Comment by glenn-jocher** [comment]
@kamalkannan79 To achieve the required format for pose estimation for YOLOv8, you may need to customize the annotation tool accordingly. The required format for the annotations is xywh and [x,y,visibility]. The first four values (xywh) refer to the bounding box coordinates, where x and y are the center coordinates of the bounding box and w and h are the width and height of the bounding box, respectively. The last three values ([x,y,visibility]) represent the pose estimation values, where x and y are the relative coordinates of the keypoint, and visibility refers to whether the keypoint is visible or not in the image. 

Therefore, you may need to customize an open source annotation tool to include the additional values for the pose estimation. You can check the documentation of the specific annotation tool to see if it supports customization. Alternatively, you could use software development skills to create a new annotation tool based on your requirements.

**Comment by blueclowd** [comment]
Hi @glenn-jocher, may I know if there is a document with detailed description of the format? For example, the valid value of the visibility? Are we using 0 for invisible and 1 for visible. I saw some people using [x,y] without visibility, is it an old format? Thanks

**Comment by Laughing-q** [comment]
> Are we using 0 for invisible and 1 for visible. I saw some people using [x,y] without visibility, is it an old format? Thanks

yes 0 for invisible and 1 for visible, and we also support using [x,y] without visibility.

**Comment by kamalkannan79** [comment]
The coco8-pose dataset has 2 in the visibility I assume, what does 2 represent when 0 and 1 is invisible and visible respectively?

**Comment by albertofernandezvillan** [comment]
I have also the same question.
For example, in coco8-pose, for annotation `000000000086.txt`, the values are:

`0` 									     # label
`0.423213 0.579820 0.252246 0.587453 `	             # xywh 
`0.455078 0.310937 2.000000 `				     # [x,y,visibility]
`0.462891 0.298438 2.000000` 
`0.435547 0.298438 2.000000 `
`0.000000 0.000000 0.000000` 
`0.406250 0.290625 2.000000 `
`0.498047 0.351562 2.000000 `
`0.363281 0.354687 2.000000` 
`0.515625 0.440625 2.000000 `
`0.310547 0.454688 2.000000 `
`0.484375 0.446875 2.000000 `
`0.386719 0.446875 2.000000 `
`0.482422 0.537500 2.000000 `
`0.414062 0.537500 2.000000 `
`0.556641 0.626563 1.000000 `
`0.425781 0.628125 2.000000 `
`0.482422 0.757812 1.000000 `
`0.398438 0.795312 2.000000`


I understand that:

- `0.000000` keypoint not present
- `2.000000` keypoint visible
- `1.000000` keypoint not visible

Is this correct?

**Comment by Laughing-q** [comment]
@albertofernandezvillan @kamalkannan79 hi, 0,1,2 are basically copied from original coco annotations. Actually the related logic about this part is to ignore these keypoints with `visible=0`, and it handles `visible>0` cases in the same way whether it's `1` or `2`. 
So basically it's **0 for invisible and 1 for visible**, and you can prepare your custom dataset according this rule.

**Comment by ryouchinsa** [comment]
As an open source tool, you can label keypoints using [COCO Annotator](https://github.com/jsbroks/coco-annotator) and export in the COCO keypoints format.

Using the JSON2YOLO script, you can convert the COCO keypoints format to YOLOv8 format.
https://github.com/ultralytics/JSON2YOLO/issues/45

[RectLabel](https://rectlabel.com) is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel, you can label polygons and keypoints in the YOLO format.
```
class_index center_x center_y width height x1 y1 v1 x2 v2 y2 x3 y3 v3 ...
0 0.545230 0.616880 0.298794 0.766239 0.522073 0.309332 2 0.540170 0.293193 2 0.499589 0.296503 2 ...
```

A visibility flag v defined as v=0: not labeled, v=1: labeled but not visible, and v=2: labeled and visible.
https://cocodataset.org/#format-data

![yolo_polygon](https://user-images.githubusercontent.com/1954306/209942647-fa9565e0-d4cf-42c2-a382-a8043465765b.jpg)

**Comment by glenn-jocher** [comment]
@ryouchinsa  Hello,

To label the keypoints using the YOLOv8 format, you can use RectLabel. This is an offline image annotation tool that can label polygons and keypoints in the YOLO format, as shown below:

```
class_index center_x center_y width height x1 y1 v1 x2 v2 y2 x3 y3 v3 ...
0 0.545230 0.616880 0.298794 0.766239 0.522073 0.309332 2 0.540170 0.293193 2 0.499589 0.296503 2 ...
```

The visibility flag v is defined as v=0: not labeled, v=1: labeled but not visible, and v=2: labeled and visible. To get more information about this format, you can refer to the COCO dataset format. 

You can also label keypoints using COCO Annotator and export them in COCO keypoints format. Then, you can convert the COCO keypoints format to YOLOv8 format using JSON2YOLO script.

I hope this helps! Let me know if you have further questions.

**Comment by lengdanlexin** [comment]
Hi @glenn-jocher 
I wrote a tool to label yolo-pose using opencv. The purpose of writing this tool is to label yolo-pose data most simply.I renamed this Python file to a txt file for easy upload.
[yolo-pose.txt](https://github.com/ultralytics/ultralytics/files/11525031/yolo-pose.txt)
After changing the label_path and image_path, it can be run directly
After changing label_path, image_path and key_point_num, it can be run directly.
![image](https://github.com/ultralytics/ultralytics/assets/85054712/9817c238-5f1d-4624-84fb-822d5d52e6ca)
If the corresponding label does not exist locally, a box and the required key points will be pre-generated.

When the mouse is placed on the four vertices of the box and the midpoints of the four sides or the center point of the box, the mouse will change its appearance, and the box can be dragged to adjust the size.
When the mouse is placed on the key point, you can drag the key point to move to the desired position.
You can also double-click the blank area with the left mouse button, input the index of the key point from the keyboard, and move the indexed key point to this position.For example, the key point named 8 needs to enter 0 from the keyboard for the first time, and enter 8 for the second time.
Double-click the key point with the left mouse button to change the state 0, 1, 2 of the key point, which needs to be input from the keyboard.
When the annotation of a person is completed, enter R from the keyboard to continue to annotate another person and its corresponding key points on the same graph.
When it is no longer necessary to label new people and key points, press Q to switch to the labeling of the next picture.
![image](https://github.com/ultralytics/ultralytics/assets/85054712/154223b0-88be-45a9-b839-3c90e7480fc1)

**Comment by lengdanlexin** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/85054712/72636ce0-c784-4256-ba27-423f72fa1be4)
This is a locally generated tag

**Comment by lengdanlexin** [comment]
It also supports ordinary annotations. The disadvantage is that you can't zoom in on the picture. If you think it's okay, I will write a more detailed explanation on how to use it

**Comment by glenn-jocher** [comment]
@lengdanlexin, thank you for sharing your tool for labeling YOLOv8 pose data using OpenCV. This is a very useful contribution to the community! It's great that your tool also supports ordinary annotations. However, it is important to consider that the inability to zoom in on the picture may limit the accuracy and precision of the labeling process, particularly for smaller and finer details in the image. If you could provide more detailed explanation on how to use your tool, it would be very helpful for others who want to label YOLOv8 pose data. Please feel free to share your explanation. Thanks again for your contribution!

**Comment by lengdanlexin** [comment]
@glenn-jocher Nice to receive your reply， I will provide a detailed explanation of how to use it for annotation.
Firstly, before using it, a few parameters need to be adjusted.
```
image_path = R'C:\Users\lengdan\Desktop\data\image'
label_path = R'C:\Users\lengdan\Desktop\data\label'
```
image_path should be the directory where the images to be annotated are located, and after the annotation is completed, it should be saved to the directory indicated by label_path. The label_path can contain pre-existing labeled tags or nothing at all. 

If there are existing tags and the prefix matches the image prefix in image_path, the local tags will be loaded first.
```
key_point_is = True  # Whether to mark key points Set to None to label ordinary Yolo labels
```
Setting key_point_is to True will enter key point annotation mode, and setting it to None will enter normal annotation mode.
```
key_point_num = 5  # Number of key points
```
If you have enabled key point annotation (key_point_is = True), you also need to set key_point_num = 5, for example, to label 5 key points.

The effects of setting draw_line_circle to True and None are shown in the following image:
![image](https://github.com/ultralytics/ultralytics/assets/85054712/61ee7765-5470-4e22-91d0-f5f2bf81612d)
### First, let me introduce key point annotation.
If there is no corresponding label file locally, a new one will be created. If there is already an existing label file, the previous label information will be loaded first.
![image](https://github.com/ultralytics/ultralytics/assets/85054712/5d32a507-28bc-4613-9190-64fdeb3fd718)
If the label file does not exist, a new bounding box will be created with its class set to 0. The preset number of key points will also be generated. Since I specified that there should be 5 key points, they will be numbered from 0 to 4. The default status of the key points is set to 2, which means they are visible and annotated. I use three different colors to distinguish the three visibility states:
![image](https://github.com/ultralytics/ultralytics/assets/85054712/beffd9e6-9c9f-41af-8970-2f1535c8447d)
On the image, it will appear as if the key point has moved to the top-left corner of the image when the status is set to 0. Setting the status to 1 or 2 will not make any difference to the position of the key point.
![image](https://github.com/ultralytics/ultralytics/assets/85054712/f410e36e-1c31-43ab-8c0c-0c765fab07d2)
To change the visibility state of a key point in the image, you need to double-click with the left mouse button near the key point. Once the mouse is placed near the key point, the visibility state will be highlighted. Double-clicking at this point will change its visibility state."
![image](https://github.com/ultralytics/ultralytics/assets/85054712/a9993b52-cdbc-473c-b1bd-d5f2a286692f)
You can change the visibility state of a key point by pressing 0/1/2 on the keyboard.

There are two ways to move a key point:"
- 1. You can click and drag the key point to its new location using the left mouse button.
- 2. Double-clicking with the left mouse button on a key point allows you to set its position.
          
![image](https://github.com/ultralytics/ultralytics/assets/85054712/5985e84d-e172-4dd6-9c8b-193fd0bbfc6e)
For example, if you want to move key point 1 to a new location, you can double-click on the desired position with the left mouse button and then use the keyboard to input a series of numbers. In this case, you would enter '01' to select key point 1 and then press '0' or '1' or '2' to set its visibility status. Finally, you can adjust the key point's position by clicking and dragging it to the new location using the left mouse button.
![image](https://github.com/ultralytics/ultralytics/assets/85054712/46e5939f-d7d8-45cd-b61a-443a8cede36d)
If you want to move the position of the bounding box, you can place the cursor over one of the four corners of the center point, and then click and drag with the left mouse button.
![image](https://github.com/ultralytics/ultralytics/assets/85054712/865538c6-e4d2-4128-b272-9282fb7b7209)
Once you have finished adjusting the positions of all the key points and the bounding box, you can press the 'R' key on the keyboard to start setting key points for the second person.
![image](https://github.com/ultralytics/ultralytics/assets/85054712/a6dc61ef-d809-4545-995d-6a7c59575e53)
If you want to add more people, continue pressing 'R' to set key points for each additional person. When you have finished annotating the image, press 'Q' to switch to the next image for annotation. This annotation method can avoid interference between the key points of two individuals. Pressing 'Q' switches to the next image for annotation.
![image](https://github.com/ultralytics/ultralytics/assets/85054712/901698f1-8cb7-4472-b051-59d692d4bd9e)
At this point, the label for the previous image is generated locally.
![image](https://github.com/ultralytics/ultralytics/assets/85054712/fa90a355-0ced-439e-8d90-90e7ce073c8a)
![image](https://github.com/ultralytics/ultralytics/assets/85054712/4ca5fc1a-3786-4371-ba42-e8acba173cae)
If you don't want to continue annotating after switching to the next image by pressing 'Q', you can press 'T' to exit the program. Then, if you rerun the program and check whether the first annotated image has taken effect
![image](https://github.com/ultralytics/ultralytics/assets/85054712/d2735705-2ab8-4e74-ae9f-8b9992be6143)
If there are multiple frames on the picture, the operation cannot be continued. If only one frame can still be operated, and only one category of annotation is supported, this is a current shortcoming. This is because most of the key point annotations only have one category, so set a limit like this

**Comment by lengdanlexin** [comment]
Under the normal annotation mode, there are better annotation tools available. Therefore, I do not intend to provide a detailed introduction to the normal annotation mode. Most key point annotation tools can be cumbersome to use, so I created this tool to assist those in need. It directly generates the YOLOv8-pose format annotation files without requiring conversion and can be used locally with the installation of OpenCV. If using the normal annotation mode, you can add new boxes, move them, enter deletion mode by double-clicking on a box, and delete by pressing 'W' or keep by pressing 'E'. Additionally, pressing 'R' allows you to add new annotations separately like key points, avoiding interference from previous annotations.

**Comment by glenn-jocher** [comment]
@lengdanlexin dear user,

Thank you for expressing your concern regarding our YOLOv8 annotation tool. We appreciate your feedback and understand your views on the normal annotation mode. However, we believe that our tool provides a simpler and quicker alternative for annotating key points for YOLOv8-pose format data. We have created this tool to make it easier for users who may not have experience or extensive knowledge in key point annotations.

Regarding your query about the normal annotation mode, you can add new bounding boxes, move them, and delete them by using the double-click feature. You can enter deletion mode by double-clicking on a box and delete by pressing 'W' or keep by pressing 'E'. Additionally, by pressing 'R', you can add new annotations separately like key points, avoiding interference from previous annotations.

Once again, we appreciate your feedback and hope that you find our tool helpful for your annotation needs.

Best regards,
The YOLOv8 team.

**Comment by chiragdeep01** [comment]
@Laughing-q Hi can you clarify something for me. According to your reply https://github.com/ultralytics/ultralytics/issues/2117#issuecomment-1519624104 
If there is not logical usage of distinction between value of v when its 1 and 2, that would mean the information that the point is not visible but labeled is not made use of. Then while labeling should i skip the occluded keypoints because even if i annotate it with visibilty 1, it would be treated as same as the keypoints that are clearly visible(2) and would result in worse results or false positives.

**Comment by zlfengyi** [comment]
Is there a mechanism that, when I input many (0,0,0)s, YOLO will consider it not as a training sample, but as background? This is what's happening with my custom training set, and I don't know why. I'm trying to train YOLO on some key points of a tennis court, but the images of the court are always partial. I'm not sure if YOLO pose can support this?

**Comment by zlfengyi** [comment]
@glenn-jocher   Thanks so much for your quick reply! One more question,  where can I download yolov8s-pose.yaml file? I want to change the last output layer from 17 to 19 because I want to detect more than 17 points in the court.

**Comment by rusvohra** [comment]
> @zlfengyi yes, YOLOv8, when used for pose estimation, supports the concept of ignoring annotations during training under certain conditions, similar to many object detection systems.
> 
> When you have annotations with coordinates (0,0,0), it may indicate either of two things:
> 
> 1. **Background Class**: If these coordinates are meant to indicate background or non-interest areas, you should not include these as annotations in your dataset. YOLOv8 does not require explicit background annotations since it inherently learns background by the absence of objects or keypoints in regions of the image.
> 2. **Absent Keypoints**: For keypoints, having (0,0,0) typically indicates that the keypoint is not visible or not annotated. How YOLOv8 handles such keypoints depends on how your dataset is formatted and how these absence-indicating annotations are encoded. Generally, the visibility flag in keypoint annotations is used to indicate whether a keypoint is absent (0), present but occluded/not visible (1), or present and visible (2).
> 
> If you're annotating keypoints for a tennis court and the court is always partially visible in the images, you would normally:
> 
> * Annotate only the visible keypoints with their correct coordinates and visibility status (1 or 2).
> * For occluded or out-of-frame keypoints, mark them with a visibility status of 0 and use a placeholder coordinate like (0,0) or the last known position before occlusion. It's critical that your labeling tool and the subsequent data format reflect this state correctly.
> 
> YOLOv8 should be able to train with such data if the annotations are well-formatted according to the above guidelines. During training, the model should learn to predict the visible keypoints and should effectively ignore keypoints marked as not visible when calculating the loss.
> 
> Ensure that your annotation tool correctly records the keypoints according to these principles, and the model should then take those into account during training. If keypoints are not present in an image, simply do not include them in the label file for that image; YOLOv8 does not require a label file to list background-only frames.
> 
> Make sure to review that the annotations you're using match the expected format, and if issues persist, double-check the data pipeline to confirm that keypoints are being treated as expected during training.

Hi Glenn, thanks for the explanation. I am a bit confused between the difference between occluded and out-of-frame keypoints. Sometimes you mention that occluded keypoints should have a flag of 1, and sometimes 0, could you please clarify?

Also, in the kpt_iou function, (as @Laughing-q mentions), there is no differentiation between visibility = 1 or 2, so is there any point in labelling 2? Thanks in advance.
![image](https://github.com/user-attachments/assets/0e36a61c-3deb-42ad-a1de-5db259218b86)

**Comment by zlfengyi** [comment]
many thanks！

> > @zlfengyi yes, YOLOv8, when used for pose estimation, supports the concept of ignoring annotations during training under certain conditions, similar to many object detection systems.
> > When you have annotations with coordinates (0,0,0), it may indicate either of two things:
> > 
> > 1. **Background Class**: If these coordinates are meant to indicate background or non-interest areas, you should not include these as annotations in your dataset. YOLOv8 does not require explicit background annotations since it inherently learns background by the absence of objects or keypoints in regions of the image.
> > 2. **Absent Keypoints**: For keypoints, having (0,0,0) typically indicates that the keypoint is not visible or not annotated. How YOLOv8 handles such keypoints depends on how your dataset is formatted and how these absence-indicating annotations are encoded. Generally, the visibility flag in keypoint annotations is used to indicate whether a keypoint is absent (0), present but occluded/not visible (1), or present and visible (2).
> > 
> > If you're annotating keypoints for a tennis court and the court is always partially visible in the images, you would normally:
> > 
> > * Annotate only the visible keypoints with their correct coordinates and visibility status (1 or 2).
> > * For occluded or out-of-frame keypoints, mark them with a visibility status of 0 and use a placeholder coordinate like (0,0) or the last known position before occlusion. It's critical that your labeling tool and the subsequent data format reflect this state correctly.
> > 
> > YOLOv8 should be able to train with such data if the annotations are well-formatted according to the above guidelines. During training, the model should learn to predict the visible keypoints and should effectively ignore keypoints marked as not visible when calculating the loss.
> > Ensure that your annotation tool correctly records the keypoints according to these principles, and the model should then take those into account during training. If keypoints are not present in an image, simply do not include them in the label file for that image; YOLOv8 does not require a label file to list background-only frames.
> > Make sure to review that the annotations you're using match the expected format, and if issues persist, double-check the data pipeline to confirm that keypoints are being treated as expected during training.
> 
> Hi Glenn, thanks for the explanation. I am a bit confused between the difference between occluded and out-of-frame keypoints. Sometimes you mention that occluded keypoints should have a flag of 1, and sometimes 0, could you please clarify?
> 
> Also, in the kpt_iou function, (as @Laughing-q mentions), there is no differentiation between visibility = 1 or 2, so is there any point in labelling 2? Thanks in advance. ![image](https://private-user-images.githubusercontent.com/141052520/363894871-0e36a61c-3deb-42ad-a1de-5db259218b86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MTE0NTQsIm5iZiI6MTcyNTUxMTE1NCwicGF0aCI6Ii8xNDEwNTI1MjAvMzYzODk0ODcxLTBlMzZhNjFjLTNkZWItNDJhZC1hMWRlLTVkYjI1OTIxOGI4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQwNDM5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjZmM2U3MDAzNDI2Njc2NGI2MDI4MzM4NTZmNjQxOTQwZGM3ZGExYjhjNzIyNDU1NzNjZDVkMTM2MDdhYmY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.idFTtk6netN8uVHRH9ATnOJq77QpD45rCEhMsvO3738)
