### ISSUE TITLE
Problem with calib.table when trying to run Yolov8 INT

### ISSUE THREAD

**Issue by PatrikPatrik2** [ultralytics/ultralytics#2121]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

File does not exist: /home/aiadmin/DeepStream-Yolo/calib.table
OpenCV is required to run INT8 calibrator

deepstream-app: yolo.cpp:98: nvinfer1::ICudaEngine* Yolo::createEngine(nvinfer1::IBuilder*, nvinfer1::IBuilderConfig*): Assertion `0’ failed.
Aborted (core dumped)

### Environment

-Jeson Orin AGX
-JetPack 5.1.1
-following this instruction for Yolo V8 https://wiki.seeedstudio.com/zh-CN/YOLOv8-DeepStream-TRT-Jetson/ that seems to be more or less a copy of the Yolo v5 instuctions from Ultralytics

### Additional

I followed the instruction, and yolo v8 worked fine with deepstream. Thereafter I followed the part of the instruction for INT8 Calibration. When I run deepstream-app -c deepstream_app_config.txt I got the attached error message. What shall I do to make the error disapear?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hi @PatrikPatrik2, 

It looks like your calibration table file /home/aiadmin/DeepStream-Yolo/calib.table is missing or inaccessible. Please make sure that you have the file in the correct directory and that it has required permissions to be accessed by the application.

Also, the error message suggests that OpenCV is required to run INT8 calibrator. Please ensure that you have installed OpenCV and its dependencies on your system before attempting to run the calibration process.

If the issue persists, please provide more information such as detailed logs or any other error messages that may help us better understand and debug the issue.

Thanks!

**Comment by PatrikPatrik2** [comment]
Thanks.
It seems that I do not have any calib.table - how do I get this file?

I do not understand why I get the error message on openCV - it should be installed
aiadmin@ubuntu:~/DeepStream-Yolo$ dpkg -l | grep libopencv
ii  libopencv                                  4.5.4-8-g3e4c170df4                  arm64        Open Computer Vision Library
ii  libopencv-core4.2:arm64                    4.2.0+dfsg-5                         arm64        computer vision core library
ii  libopencv-dev                              4.5.4-8-g3e4c170df4                  arm64        Open Computer Vision Library
ii  libopencv-python                           4.5.4-8-g3e4c170df4                  arm64        Open Computer Vision Library
ii  libopencv-samples                          4.5.4-8-g3e4c170df4                  arm64        Open Computer Vision Library
aiadmin@ubuntu:~/DeepStream-Yolo$ python3
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> 

Thanks for the support
//Patrik

**Comment by PatrikPatrik2** [comment]
Sorry, should have previewed - seems that I have OpenCV installed - Why do I get an error?

sudo apt-get install libopencv-dev
[sudo] password for aiadmin: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libopencv-dev is already the newest version (4.5.4-8-g3e4c170df4).
The following package was automatically installed and is no longer required:
  gir1.2-goa-1.0
Use 'sudo apt autoremove' to remove it.
BR
Patrik

**Comment by glenn-jocher** [comment]
@PatrikPatrik2, based on your response, it appears that OpenCV is indeed installed on your system. It's hard to say why you are experiencing an error without seeing the detailed logs. However, it's possible that there is a compatibility issue between the version of OpenCV you have installed and the version expected by YOLOv8. 

Regarding the missing calib.table file, this is typically generated during the calibration process using a set of reference images. Please follow the calibration process mentioned in the instruction that you are following to generate the file.

If you encounter any issues during the calibration process or if you have more information about the error, please let me know and I'll do my best to assist you.

**Comment by BarcaBear** [comment]
I'm having the same error. Has a solution been found? YoloV8 int 32 works perfectly. But the calibration fails due to the Opencv error.

"File does not exist: 
OpenCV is required to run INT8 calibrator

deepstream-app: yolo.cpp:98: nvinfer1::ICudaEngine* Yolo::createEngine(nvinfer1::IBuilder*, nvinfer1::IBuilderConfig*): Assertion `0' failed.
Aborted"

When I try to install opencv again I receive the following-

"Reading package lists... Done
Building dependency tree       
Reading state information... Done
libopencv-dev is already the newest version (3.2.0+dfsg-4ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 237 not upgraded."

So it seems opencv is installed.

I am using a Jetson Xavier NX 8gb
Cuda 10.2.3

**Comment by pderrenger** [comment]
@BarcaBear the issue might stem from the version of OpenCV installed. It's crucial to ensure the installation of a compatible version of OpenCV for the YOLOv8 INT8 calibration process. The currently installed version 3.2.0 might be the root cause of the problem. I would recommend updating to a more recent version of OpenCV, or at least version 4.0 or higher, to ensure compatibility.

To resolve the discrepancy, you could consider building OpenCV from source, ensuring it is compatible with your environment and meets the requirements for YOLOv8 INT8 calibration. After updating to a compatible version, you should be able to proceed with the calibration without encountering the OpenCV-related error.

If you encounter any resistance during the update or need further assistance with this process, please don't hesitate to reach out.

**Comment by Pornpra-Ton** [comment]
I have the same error:

File does not exist: /home/orin_nano/DeepStream-Yolo/calib.table
OpenCV is required to run INT8 calibrator

deepstream-app: yolo.cpp:98: nvinfer1::ICudaEngine* Yolo::createEngine(nvinfer1::IBuilder*, nvinfer1::IBuilderConfig*): Assertion `0' failed.
Aborted (core dumped)

**Environment**
Python: 3.8.10
CUDA: 11.4.315
cuDNN: 8.6.0.166
TensoRT: 8.5.2.2
OpenCV: 4.5.4 **without** CUDA

I am not sure how to create calib.table to inference YOLOv8 (INT8 Calibration) with TensorRT and DeepStream. Do you have any update in this issue ?

**Comment by glenn-jocher** [comment]
@Pornpra-Ton the error you are encountering suggests that the INT8 calibration process cannot proceed without the calibration table (`calib.table`), and it's also indicating that there is an issue with OpenCV.

The calibration table is essential for the INT8 calibration process as it contains scaling factors for quantizing the floating-point model weights and activations to 8-bit integers. This table is generally created by processing a batch of images from your dataset through the calibration algorithm provided by TensorRT.

To create the `calib.table` file:

1. Prepare a set of images for calibration. This should be a representative subset of your dataset.
2. Use the INT8 calibration script provided by TensorRT, which involves running your model on these calibration images and collecting the necessary statistics.

However, since you're using DeepStream, make sure to consult its documentation or any instructions provided with YOLOv8 for generating the calibration table within that context.

As for the OpenCV requirement, the version you listed (4.5.4 without CUDA) should typically be sufficient, but it's possible that the system is having trouble locating or accessing it. Ensure that OpenCV is correctly installed and accessible to your Python environment and DeepStream application. You might also need to check if OpenCV with CUDA support is required in your specific use case.

If you're using a Jetson device, the JetPack SDK usually comes with a compatible version of OpenCV — you may want to ensure you're using the version from JetPack. Upgrading your software stack (CUDA, cuDNN, TensorRT) to their latest compatible versions can also help avoid such issues.

If the documentation does not provide clear steps or if you're unable to resolve the issue with the information above, it would be advisable to follow up with the maintainers of the repository or seek assistance from the community forums for YOLOv8 and DeepStream. They may provide you with the exact steps for generating the `calib.table` specific to YOLOv8 or help troubleshoot any environmental issues.
