### ISSUE TITLE
How do I save predictions as a text file?

### ISSUE THREAD

**Issue by uiiihmk** [ultralytics/ultralytics#2143]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi all, I am pretty sure I am doing something completely wrong but since I do not know how to code I have to ask it:

I trained a YOLOv8 Model using Roboflow. Now I load my model in my own colab from Roboflow and I want to run a prediction and save the outcome of classes and bounding boxes as a text file. But I always get following error:

**TypeError: predict() got an unexpected keyword argument 'save_txt'**

Here is my code, it might be completely wrong:

Install PyTorch
!pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117

Install the Roboflow library
!pip install roboflow

Install the Ultralytics
!pip install ultralytics

Import the necessary modules
from ultralytics import YOLO
from roboflow import Roboflow
from IPython.display import Image

Authenticate with Roboflow and load the model
rf = Roboflow(api_key="ABC")
project = rf.workspace().project("ABC")
model = project.version(ABC).model

Specify the path to the image
image_path = "/content/ABC.JPG"

Perform object detection on the image and save the output to a variable
predictions = model.predict(image_path, save_txt=True, confidence=35, overlap=60)

Save the predicted text file to disk
predictions.save_txt("/content/ABC.txt")

Read the contents of the prediction text file
with open("/content/ABC.txt", "r") as f:
    prediction_text = f.read()

Print the contents of the prediction text file
print(prediction_text)

**Comment by glenn-jocher** [comment]
Hello @uiiihmk, thank you for your question! 

It seems like the `save_txt` parameter is causing the issue in your code. This parameter is not supported in YOLOv8, and that is why you are receiving the `TypeError` message. 

Instead,  you can refer to the `YOLO` constructor, which does take a `results` argument for outputting predictions to a file. You can use it in the following way:

```python
# Create a YOLOv8 model    
model = YOLO(model='yolov5s', device='cpu') 

# Read the image and perform object detection on it
image_path = "/content/ABC.JPG"
predictions = model(image_path, save_txt=None)

# Save the predicted text file to disk
with open("/content/ABC.txt", 'w') as file:
    for prediction in predictions.xyxy[0]:
        file.write(f"{prediction[0].item()} {prediction[1].item()} {prediction[2].item()} {prediction[3].item()}\n")
```

Here we are using `predictions.xyxy` to extract individual predictions, and then writing them to text files in the format that the RoboFlow expects, with one bounding box per line. 

Let me know if this helps or if you have any other questions.

**Comment by uiiihmk** [comment]
Hi @glenn-jocher, thanks for coming back to me. I just used following command that i found in the roboflow docs, which solved the issue:
        # Convert predictions to JSON
        json_obj = prediction.json()

So for me this topic is solved!

**Comment by jpl-c** [comment]
Hi @glenn-jocher,

Thanks for sharing your code snippet which will probably help out a lot of us. However I was running into issues when using the code directly. 

It turns out the `predictions` object is actually a single-item list which raises an error when calling the `xyxy` attribute on it. Additionally from inside the `prediction` object you need to go get the `boxes` attribute which contains the predicted label information.
I'd recommend other users to have a look at the [boxes class](https://github.com/ultralytics/ultralytics/blob/0a36b83e7addd5e21438d32a614bbdf3f330e6d9/ultralytics/yolo/engine/results.py#L343) to understand how the predicted bounding boxes are stored.

Taking this into account, here is the piece of code that allows users to save the result of each prediction to a txt file : 

```python
model = YOLO('weights/best.pt')
predictions = model(image_path, save_txt=None)

with open("predicted_labels.txt", '+w') as file:
      for idx, prediction in enumerate(predictions[0].boxes.xywhn): # change final attribute to desired box format
          cls = int(predictions[0].boxes.cls[idx].item())
          # Write line to file in YOLO label format : cls x y w h
          file.write(f"{cls} {prediction[0].item()} {prediction[1].item()} {prediction[2].item()} {prediction[3].item()}\n")
```

I'm figuring this might interest other users.

Cheers!

**Comment by lonnylundsten** [comment]
I modified this so that you would get the class name and file path on each row as well, for those who want that type of granularity.
```
with open("predicted_labels.txt", '+w') as file:
      for idx, prediction in enumerate(predictions[0].boxes.xywhn): # change final attribute to desired box format
          cls = int(predictions[0].boxes.cls[idx].item())
          path = predictions[0].path
          class_name = model.names[cls]
          # Write line to file in YOLO label format : cls x y w h
          file.write(f"{path} {class_name} {cls} {prediction[0].item()} {prediction[1].item()} {prediction[2].item()} {prediction[3].item()}\n")
```

**Comment by lonnylundsten** [comment]
I've pasted some code below that generates a dataframe with the following for each detection from yolov8:

path | class_name | class_id | confidence | box_coord
-- | -- | -- | -- | --
/Users/xxx/Desktop/test_images/885450_interptech-kelp2-4bcf74c2.jpg | fish | 0 | 89 | [346.7984619140625, 657.2486572265625, 201.15232849121094, 127.75860595703125]

Each row is a detection and, obviously, you may have multiple detections for each image, so you'll likely have multiple rows for each image. The code below takes the results from your prediction, creates this df, and saves it as a csv.

```
list = []
for result in predictions:
        boxes = result.boxes.cpu().numpy()
        for box in boxes:
            path = result.path
            class_name = model.names[cls]
            cls = int(box.cls[0])
            conf = int(box.conf[0]*100)
            bx = box.xywh.tolist()
            df = pd.DataFrame({'path': path,'class_name': class_name, 'class_id': cls, 'confidence': conf, 'box_coord': bx})
            list.append(df)
df = pd.concat(list)

df.to_csv('predicted_labels.csv', index=False)
```

**Comment by glenn-jocher** [comment]
@lonnylundsten hello, 

Thank you for sharing this valuable piece of code for creating a DataFrame with all the detection information from YOLOv8. It's a great way to present the detection results and should be useful for many users.

Your code takes the detections (or `predictions`), loops over them to extract the class identification, image path, class name, confidence, and box coordinates. Afterwards, it appends this data to a list as a DataFrame. Finally, it combines all the DataFrames into one and exports it to a CSV file.

For anyone reading this who wants to implement it, be aware that you'll need to install pandas for your python environment as it's not a dependency of YOLOv8. You can do this with `pip install pandas` in your command line.

This approach is excellent for anyone working with pandas and wants a DataFrame structure to manipulate and analyze their detection results. Thanks again for sharing it!

**Comment by lonnylundsten** [comment]
@glenn-jocher Would it be possible to add the ability to get the frame number to the predictions (detections) object? We can currently grab, for example, the video or image path using "result.path." It would also be nice to be able to grab the video frame number from the predictions object, i.e., "result.video_frame" as its another nice bit of info to add to the df.

Thanks again for all the great work you and your team do!

**Comment by glenn-jocher** [comment]
@lonnylundsten hello,

Thank you for your suggestion and your kind words for the team — we truly appreciate it! 

Regarding your proposal to add the frame number to the detection object, it indeed sounds like a potentially useful feature, especially for video processing tasks and it would help with additional context when reviewing object detection results.

However, adding this feature would involve changes to the core YOLOv8 implementation and may have implications on the performance and memory usage as it would require tracking additional metadata throughout the detection process.

Currently, the frame number is not explicitly tracked within the detection process. Therefore, it would require a substantial amount of work to implement this effectively.

I would recommend following the updates of the repository, as we are continuously working on improving the functionalities based on user's feedback!

Thank you again for your feedback. It is ideas like these that help improve the project and make it more suited to the needs of its users.

**Comment by PasinduShavinda** [comment]
@glenn-jocher , Hi.. I have used this code to save the output logs of my **### yolov8n classification model**, But it gives some errors. Can you please kindly help me to modify this code to compatible with yolov8n classification model, I provide the code below, I think the issue was the below code for object detection, I need to change this for yolov8n classification,

```
model = YOLO('weights/best.pt')
predictions = model(image_path, save_txt=None)

with open("predicted_labels.txt", '+w') as file:
      for idx, prediction in enumerate(predictions[0].boxes.xywhn): # change final attribute to desired box format
          cls = int(predictions[0].boxes.cls[idx].item())
          # Write line to file in YOLO label format : cls x y w h
          file.write(f"{cls} {prediction[0].item()} {prediction[1].item()} {prediction[2].item()} {prediction[3].item()}\n")
```
ERROR --> 
<img width="940" alt="image" src="https://github.com/ultralytics/ultralytics/assets/88933114/c4a6bf92-6092-4977-98f1-f5921e2576c4">

**Comment by glenn-jocher** [comment]
@PasinduShavinda hello, thank you for reaching out. 

From your log output, it seems that the `predictions` object is missing the `boxes` attribute, which is likely causing this TypeError. The `boxes` attribute is specific to object detections, which is why it's not available for a classification model. 

Your YOLOv8n model is set up for classification rather than detection, so it doesn't produce bounding box coordinates (x, y, width, height). Instead, it outputs class probabilities for each class in your model.

To make the code compatible with a classification model, you'd need to modify it to iterate over the class probabilities rather than the bounding boxes.

For instance, in place of `predictions[0].boxes.xywhn` you should have something representing the class probabilities output from your model. You also won't need the bounding box coordinates in this case. 

Remember to ensure that your model is outputting the expected class probabilities correctly before storing them.

I hope this helps! Let me know if you have any other questions.

**Comment by beyse** [comment]
I solved this for me simply by editing `ultralytics/yolo/v8/detect/predict.py`. In line 39, add `args.save_txt = True` like this:


```py
def predict(cfg=DEFAULT_CFG, use_python=False):
    """Runs YOLO model inference on input image(s)."""
    model = cfg.model or 'yolov8n.pt'
    source = cfg.source if cfg.source is not None else ROOT / 'assets' if (ROOT / 'assets').exists() \
        else 'https://ultralytics.com/images/bus.jpg'

    args = dict(model=model, source=source)
    args.save_txt = True # 👈 Add this
    if use_python:
        from ultralytics import YOLO
        YOLO(model)(**args)
    else:
        predictor = DetectionPredictor(overrides=args)
        predictor.predict_cli()
```

This will create folder called `labels` in the output folder, containing the .txt files when running: 

```bash
yolo predict model=... source=...
```

**Comment by glenn-jocher** [comment]
@beyse hello,

Thanks for sharing your workaround for saving predicted labels to a text file! Hardcoding the argument `args.save_txt = True` within the `predict` function in `ultralytics/yolo/v8/detect/predict.py` should indeed enable output of label files by default. 

However, be aware that directly editing the library code can potentially lead to unintended side-effects and could cause issues in future updates, as changes made to the codebase locally may not be reflected in future versions of the library. 

If you frequently use this function with `save_txt=True`, you might consider passing it as an argument when calling `predict`, as a more flexible and maintainable solution. This way, you can enable or disable the output of label files as needed, without altering the original functions. 

Just to reiterate, when `save_txt=True`, a labels folder will be generated and .txt files corresponding to each image will be saved with the bounding box coordinates and class labels.

Remember that this modification has been made in your own local installation and may not be present in other installations, so please make sure to note this change if you are sharing your project with others. 

And finally, thank you for your valuable input in resolving this. We always appreciate receiving feedback and solutions from our user community.

Best regards!

**Comment by pt2241701** [comment]
hi @glenn-jocher i want to use your code with webcam but i didnt know how to do this, please help me
`# Create a YOLOv8 model    
model = YOLO(model='yolov5s', device='cpu') 

# Read the image and perform object detection on it
image_path = "/content/ABC.JPG"
predictions = model(image_path, save_txt=None)

# Save the predicted text file to disk
with open("/content/ABC.txt", 'w') as file:
    for prediction in predictions.xyxy[0]:
        file.write(f"{prediction[0].item()} {prediction[1].item()} {prediction[2].item()} {prediction[3].item()}\n")`
thanks for your reading and watching!

**Comment by glenn-jocher** [comment]
@pt2241701 hi there! 

It looks like you are trying to use the YOLO model with a webcam, but the error message indicates that `predictions` is a list and not the expected result object containing `xyxy`. This happens when you pass a single image path to the model, but for webcam streams, the process is different.

Here's a brief guidance: 

1. Ensure that you set the source to `0` to use your webcam.
2. Use the correct `Predict` syntax for real-time predictions, which involves a loop to handle frames one by one.
3. Ensure that you access the predictions correctly within the loop, considering the format they are returned in during real-time inference.

Remember to define 'device' as `cpu` or `cuda` based on your hardware for the real-time stream.

Good luck, and I hope this helps you get your real-time predictions up and running! 🚀

**Comment by CyrusAddy** [comment]
@glenn-jocher I am using kubectl and I am using CLI to train YOLOv8. How do I get the predictions json file saved (preferably in COCO format)?

**Comment by glenn-jocher** [comment]
Hi @CyrusAddy — use validation with save_json to write COCO-format predictions: yolo val model=path/to/best.pt data=coco.yaml save_json=True; this creates runs/detect/val/exp/predictions.json; predict CLI doesn’t emit COCO JSON; see the detection validator pred_to_json reference for details: Serialize YOLO predictions to COCO JSON format.
