### ISSUE TITLE
Training with MPS takes a lot RAM (possible memory leak)

### ISSUE THREAD

**Issue by laclouis5** [ultralytics/ultralytics#2172]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Training YOLOv8 with MPS quickly fills the RAM and the memory used increases as the training progresses. The training speed also decreases over time.

### Environment

* Python: 3.10.9
* OS: macOS Ventura 13.3.1
* Machine: Apple MacBook Pro 14" (M1 Pro 16GB)
* Ultralytics: 8.0.83

Installed with:

```
python3 -m venv env
source env/bin/activate
pip install ultralytics
```

### Minimal Reproducible Example

I launched training with:

```
yolo detect train data=coco128.yaml model=yolov8n.pt device=mps batch=4 workers=2 
```

* Epoch 1: 4 GB of RAM, 6 IPS
* Epoch 2: 10 GB of RAM, 3 IPS
* Epoch 3: 18 GB of RAM, 2 IPS

The same setting works fine on CPU and uses 800 MB max. of RAM:

```
yolo detect train data=coco128.yaml model=yolov8n.pt device=cpu batch=4 workers=2 
```

### Additional

Model prediction and evaluation with MPS work fine and I get consistent execution speed (83 IPS in 640x352):

```
yolo predict model=yolov8n.pt source='https://youtu.be/Zgi9g1ksQHc' device=mps imgsz=640
```

Memory used is around 830 MB.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@laclouis5 thanks for reporting this issue! We can certainly look into this memory usage behavior during training with MPS. It seems like the memory consumption grows steadily as training progresses. While we investigate this, you can use the `device=cpu` setting for training, which appears to work fine with lower memory usage.

In the meantime, you might also want to consider adjusting the batch size or other hyperparameters to see if it mitigates the RAM usage issue with MPS.

Your willingness to contribute by submitting a PR is greatly appreciated! We welcome any assistance in addressing this issue.

We'll make sure to keep you updated on our progress with this concern.

**Comment by glenn-jocher** [comment]
Thank you for the detailed report, @pderrenger. We're aware of the issue now and will investigate the potential memory leak during MPS training. For the time being, it's good to hear that CPU training is stable for you. As a temporary workaround, you might experiment with reducing the batch size or workers when using MPS to see if it alleviates the high RAM usage.

We appreciate your offer to help with a PR! We'll keep you posted on our findings and would be grateful for any insights or contributions you can make.

Stay tuned for updates, and thanks again for your involvement with the YOLOv8 community! 🚀

**Comment by JohnMBrandt** [comment]
I also have this issue - training with ~20k images goes from 4 gb of ram at start to 30 gb of ram after 1 epoch to 80 gb of ram after 2 epochs. Model uses ~2 gb ram with CPU. Device is M3 Max running torch 2.1.2 and Python 3.11

**Comment by glenn-jocher** [comment]
@JohnMBrandt thank you for reporting this issue with training on MPS. It seems like you're experiencing a memory leak that's causing RAM usage to increase with each epoch, which is not expected behavior.

To help us diagnose and address this issue, could you please provide the following additional information:

1. The exact version of the `ultralytics` package you are using. You can find this by running `pip show ultralytics` in your terminal.
2. Any custom modifications you've made to the `coco128.yaml` or any other configuration files.
3. If possible, a memory profile of the training process. You can use tools like `memory_profiler` in Python to track memory usage over time.
4. Check if there are any other processes on your system that might be consuming memory during the training process.

In the meantime, as a temporary workaround, you can try the following steps:

- Reduce the batch size and number of workers to see if that has any effect on the memory leak.
- Monitor the system's memory usage using macOS's Activity Monitor or the `htop` command in the terminal to see if there's a particular point in the training process where memory usage spikes.
- Restart your system to ensure there are no lingering processes that could be affecting memory usage.

We will investigate this issue further and aim to provide a fix or a more detailed explanation. If you have any additional information or find that certain changes mitigate the issue, please let us know.

**Comment by JohnMBrandt** [comment]
Hi Glenn, thanks for your quick response.

I am on Mac OS 14.1 and have tried the following and get memory leaks in both:

Python 3.10.13 with Torch 2.1.2 and Ultralytics 8.1.12
Python 3.11.7 with Torch 2.3.0dev or 2.2.0 and Ultralytics 8.1.12

I am training on the DIOR dataset with a `config.yaml` that looks like:

```
path: 
train: 'images/train'
val: 'images/val'

# Classes as per mentioned in the annotation
names:
  0: Expressway-Service-area
  1: Expressway-toll-station
  2: airplane
  3: airport
  4: baseballfield
  5: basketballcourt
  6: bridge
  7: chimney
  8: dam
  9: golffield
  10: groundtrackfield
  11: harbor
  12: overpass
  13: ship
  14: stadium
  15: storagetank
  16: tenniscourt
  17: trainstation
  18: vehicle
  19: windmill 
```

and using a training script that looks like the following. I have tested using the default args and the memory leak still happens.

```
model = YOLO('yolov8n.yaml')#'runs/detect/yolov8n_epochs50_batch8_cpu/weights/last.pt') # Builds the model from scratch

results = model.train(data='config.yaml', imgsz=512, epochs=25,
                      name='yolov8n_epochs50_batch8_gpu',
                      device='mps', workers=8,
                      pretrained = False,
                      cos_lr = False,
                      freeze = None,
                      max_det = 1000,
                      iou = 0.33,
                      show_labels = False,
                      show_conf = False,
                      nms = True,
                      exist_ok = True,
                      resume = True,
                      val = False,
                      flipud = 0.0,
                      mask_ratio = 1,
                      batch = 16,
                      cache = True)
```

**Comment by glenn-jocher** [comment]
@JohnMBrandt thank you for reporting this issue with training YOLOv8 using MPS on macOS Ventura. It seems like you're experiencing a memory leak that is causing RAM usage to increase with each epoch, which is not expected behavior.

Before proceeding with a solution, it's important to ensure that your system and all dependencies are up to date. Please make sure that you have the latest version of the Ultralytics YOLOv8 repository and that all Python dependencies are updated.

Given the information you've provided, here are a few steps you can take to troubleshoot and potentially resolve the issue:

1. **Update Ultralytics YOLOv8:**
   Ensure that you have the latest version of the Ultralytics YOLOv8 repository. If you installed it via `pip`, you can update it using:
   ```bash
   pip install --upgrade ultralytics
   ```

2. **Monitor Memory Usage:**
   Use macOS's built-in tools or third-party applications to monitor memory usage in real-time. This can help identify when and where the memory leak occurs.

3. **Reduce Batch Size:**
   Try reducing the batch size to see if it has any effect on the memory leak. This can help isolate whether the issue is related to the amount of data being processed at once.

4. **Check for Known Issues:**
   Check the [Ultralytics YOLOv8 issues page](https://github.com/ultralytics/ultralytics/issues) for any updates or similar reports from other users. It's possible that the issue has already been identified and a fix is in progress.

5. **Isolate the Problem:**
   If possible, try running the training on a different machine with an M1 chip to see if the issue is reproducible. This can help determine if the problem is specific to your environment.

6. **Submit a Detailed Bug Report:**
   If the issue persists, consider submitting a detailed bug report to the Ultralytics YOLOv8 repository. Include all relevant information, such as the exact steps to reproduce the issue, any error messages, and system specifications.

7. **Seek Community Help:**
   Engage with the Ultralytics community on platforms like GitHub Discussions or Stack Overflow. Other users or contributors may have encountered similar issues and can offer solutions.

8. **Consider Alternative Training Options:**
   While this issue is being resolved, you might want to consider using CPU or GPU (if available) for training as a temporary workaround.

Please note that MPS support is relatively new and may have some limitations or bugs that are still being worked out. Your detailed report will be valuable to the Ultralytics team in identifying and fixing the issue.

**Comment by Ced70** [comment]
Hello,

I have the same issue of memory leak.

My setup : MacBook Pro M3 max with 128 gb ram
Mac OS Sonoma 14.3.1

Version of Ultralytics : 8.1.18 (same issue since 8.0)

The problem appears when creating model in trainer.py.

![image](https://github.com/ultralytics/ultralytics/assets/122569819/02eb6c5f-3e3f-4052-a3de-165d1149ac67)

![image](https://github.com/ultralytics/ultralytics/assets/122569819/8908e6d4-3005-4c53-a8a2-817c40bf0fd5)

![image](https://github.com/ultralytics/ultralytics/assets/122569819/9020b75c-4953-41fe-ba7a-b28a1af199e4)

This appears with differents datasets. in this example, there are around 1000 images in bmp format. 

There is the code of the training :

`# Load a model
    temps_debut = time.time()
    model = YOLO(type_yolo + '.yaml')  # build a new model from YAML
    model = YOLO(type_yolo + '.pt')  # load a pretrained model (recommended for training)
    model = YOLO(type_yolo + '.yaml').load(type_yolo + '.pt')  # build from YAML and transfer weightsself.format_export = from Forma import FormFormat.
    temps_chargement_model = time.time() - temps_debut
    
    # Train the model
    temps_debut = time.time()
    if torch.backends.mps.is_available():
        torch.mps.empty_cache()
        model.train(data=data_yaml, epochs=epochs, imgsz=resolution_image, device='mps', workers=0, batch=batch,
                    augment=False, save_dir=variables_globales.projet_actuel.runs_dir, cache=False, save=True,
                    save_period=0, amp=True, patience=50)`

imgsz = 1024
batch = 32

With the same code ( with device=cuda ) with a RTX4090, ram used is around 12 gb.

The problem is the used ram increase at each epochs.

At the end of the first epochs :

![image](https://github.com/ultralytics/ultralytics/assets/122569819/eba13e9a-4f5f-44fc-9109-d30aa523a19b)

During the second epochs :

![image](https://github.com/ultralytics/ultralytics/assets/122569819/d87fecc1-0940-452d-97cd-22b9db116497)

Tell me if you need more informations.

**Comment by glenn-jocher** [comment]
@Ced70 hey there! 👋

Thanks for bringing this to our attention and for the detailed information. It's certainly unusual for RAM usage to increase with each epoch, and we want to get to the bottom of this. 

A quick suggestion: could you try setting `workers=2` or higher in your training script? Sometimes having workers set to `0` can cause unexpected memory behavior, especially with MPS.

Also, if you haven't already, please ensure you're using the latest version of PyTorch that supports MPS, as there have been several updates aimed at improving memory management.

If the issue persists, it would be helpful to know if this happens with smaller image sizes or batches. This could help isolate whether it's a dataset-specific issue or related to the MPS backend.

We appreciate your patience and are here to work with you to resolve this. Keep us posted! 🚀

**Comment by biphasic** [comment]
Has anyone been able to fix this? I'm still encountering the memory leak using version 8.3.47 on my M3 MB Pro using Python 3.11.11 and Torch 2.5.1 MPS. Would it help to use the Ultralytics arm Docker image?

**Comment by glenn-jocher** [comment]
Thank you for your comment. The memory leak issue with MPS is still under investigation, and using the Ultralytics ARM Docker image likely won't resolve it as MPS is macOS-specific. For now, we recommend training on CPU or a CUDA-enabled GPU if available. Stay tuned for updates on this issue.

**Comment by mastrs** [comment]
Valid for MBP M4 Pro too; a workaround based on restarting the process periodically seems to mitigate the issue to a temporarily sustainable degree (the worse thing is that the leak may get so bad that the whole machine halts to crawl and stops responding altogether).

**Comment by glenn-jocher** [comment]
Thank you for sharing your experience. This is a known issue with MPS on macOS, and we are investigating it. For now, we recommend using CPU or a CUDA-enabled GPU if available, as MPS support remains experimental. Restarting the process is a practical workaround to manage memory leaks temporarily.

**Comment by tPiffrader** [comment]
@glenn-jocher is there any update about this?

**Comment by glenn-jocher** [comment]
Thanks for checking in! We're actively investigating MPS memory leaks and working closely with PyTorch to resolve them. For now, we recommend using `device='cpu'` for training as shown in our [MPS warning documentation](https://docs.ultralytics.com/reference/models/yolo/pose/predict/#ultralytics.models.yolo.pose.predict.PosePredictor.__init__) until stable fixes are available. We'll update the GitHub issues page with any breakthroughs.
