### ISSUE TITLE
YOLOv8 stopped my training after 58 epochs without running in an EarlyStopping exception.

### ISSUE THREAD

**Issue by nicobrb** [ultralytics/ultralytics#2175]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

These are my settings for the training:
![image](https://user-images.githubusercontent.com/39137998/233654194-18e5f979-718c-4748-b9d8-0aa1ffbb0b67.png)
after the 58th epoch, YOLO terminates the training phase:
![image](https://user-images.githubusercontent.com/39137998/233656889-41224e8d-620f-4ce3-a6a5-a9af1cba7b51.png)
When I try to restart the training, using ```yolo detect train resume model=\path\to\weights\last.pt```, yolo returns this, saying that 300 epochs by this training were reached:
![image](https://user-images.githubusercontent.com/39137998/233657205-66f21f16-0c91-4bfe-995f-13d0e0df2c1a.png)

There is NO way that patience (which was set to 50) was reached, both because no EarlyStopping was raised and because the metrics where not stationary. 
UPDATE: I tested the "last.pt" weights generated around epoch 55 against the "best.pt" (which are equal to the last.pt of the latest epoch, the one that terminated the training) and they are so much better. Not only the training stopped without any warning, like it was actually the last epoch, but the released weights are worse under every aspect when compared to the ones in the previous epochs. 

### Environment

YOLO: 8.0.83
python: 3.8.10
OS: Linux

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@nicobrb, it seems that your training stopped prematurely, and you tried to restart it with "resume" but received unexpected results. Please note that the "last.pt" weights generated by YOLOv8 are the weights generated by the last epoch of the training, and not necessary the weights of the best performing model. In case you suspect that the best performing model's weights might have been lost, you could look for them in the "runs" folder, sorted by the highest mAP metric. If you would like to investigate why your training terminated prematurely, please take a look at the training logs to see if there were any warnings, errors or unusual disruptions that might have caused this issue.

**Comment by nicobrb** [comment]
@glenn-jocher don't mind the restart, that was simply an attempt to see what was going on. The fact is: my training has stopped prematurely _without any warnings_ whatsoever, there are no logs in the runs folder, only the image_batch and stuff. There is no way to debug this and no logs have been released.
I'm sorry to say it, but that's less than optimal!

**Comment by glenn-jocher** [comment]
@nicobrb, we apologize for the unexpected behavior you experienced. We understand that it can be frustrating when the training stops prematurely with no warnings or obvious issues, and we appreciate your efforts to find a solution. In some cases, training may stop abruptly if the system runs out of memory or if there is an issue with the dataset or training environment. We recommend checking the dataset and training files, verifying the hardware resources available, and trying again to see if the issue persists. If you have done so, and the issue persists, please let us know, and we will work with you to find a resolution.

**Comment by nikolaydyankov** [comment]
@glenn-jocher Could this be related to #1621 ? I'm experiencing similar issues.

**Comment by glenn-jocher** [comment]
@nikolaydyankov, thank you for sharing details of your experience. It sounds like you are experiencing training freezes and system issues when running YOLOv8 in certain configurations. This could be related to a number of factors, including the dataset size and complexity, hardware resources, or system configuration. To troubleshoot this issue, we recommend monitoring system resource usage during training, including GPU, memory, and CPU usage, to see if any of these resources are maxing out and causing the freezes. It may also be useful to try running the training in different configurations, such as reducing the batch size or adjusting other hyperparameters, to see if this resolves the issue. If the problem persists, please let us know, and we will work with you to identify a solution.

**Comment by nicobrb** [comment]
AGAIN! 
![image](https://user-images.githubusercontent.com/39137998/233808058-f1753dbb-b579-414f-9f5e-8176b8e814ec.png)
Now after 88 epoch, with yolov8l, (last time was yolov8x) around 1 day of training, again
![image](https://user-images.githubusercontent.com/39137998/233808073-9126cdf6-4573-4870-bda1-7ab01241944e.png)

this is utterly unacceptable, it everything but converging, learning rate was low, loss were still lowering
![image](https://user-images.githubusercontent.com/39137998/233808176-e0c7fda8-00ac-4dc2-9882-2975ab0a7d30.png)

@glenn-jocher this is not acceptable, I'm paying my training days on this computer to obtain good results, and the algorithm stops, screws the weights up (they perform far worse than the penultimate weight's epoch, and the difference is only one epoch!) and there is no way to continue.

Come on...

**Comment by glenn-jocher** [comment]
@nicobrb , we apologize for the inconvenience and frustration you have experienced during your training process. We understand that the interruptions and poor performance of your model are unacceptable and we apologize for any errors or issues in the YOLOv8 codebase that may have contributed to this problem. We take these issues very seriously and will work with you to try to identify and resolve the root cause of these errors. In the meantime, we recommend taking several steps to help minimize the risk of further interruptions:

- Monitor your system resources carefully during training, including GPU, RAM, and CPU usage, to ensure sufficient resources are available throughout the training process.
- Check the data quality and file structure to ensure they are formatted correctly and free from errors or corruption.
- Experiment with different hyperparameters, such as batch size and learning rate, to see if they improve your results.
- If the issue persists, please reach out to us with additional details, such as training logs and system specs, so we can investigate further and find a solution. We appreciate your patience and cooperation as we work to address these issues.

**Comment by nicobrb** [comment]
@glenn-jocher the second training iteration (only the second one) returned this (digging deeper in the logs of wandb)
![image](https://user-images.githubusercontent.com/39137998/233811694-007510cf-a0b5-4baa-8a17-d1273ea9eee7.png)
So i guess this is the message that yolo gives when patience is reached.

using Validate on both best.pt returned at the end of training and last.pt from 80th epoch, each and every metric is better for best.pt weights. But when using those weights for a video detection, _the same videos where I extracted test images_ it performs so so so so so SO much worse than the last.pt weights. Validation is completely misleading.

**Comment by glenn-jocher** [comment]
@nicobrb, it is not uncommon to encounter discrepancies between training metrics and real-world performance when using computer vision models, such as YOLOv8. While validation results are important, they may not always accurately reflect model performance in real-world scenarios. This can be due to a number of factors, such as differences in the data distribution or environmental factors that were not present in the validation set. It is also possible that the model is overfitting to the validation set, which can lead to poor performance in real-world scenarios.

To address this issue, we recommend taking a closer look at the data and real-world scenarios where the model is being used. In particular, it may be helpful to gather more diverse and representative data, and to test the model in a variety of real-world environments to identify potential sources of error. Additionally, it may be useful to experiment with different hyperparameters and architectures to try to improve the model's robustness and generalization capabilities. We hope these suggestions help you to improve your model's performance and achieve your desired results.

**Comment by glenn-jocher** [comment]
@HassanBinHaroon yes, it seems like your system was probably nearly saturated at the beginning and it simply took a few epochs to crash. You can also reduce to i.e. 192 as a middle ground, or try AutoBatch with `batch=0.7` to target 70% CUDA memory utilization with automatic batch size computation (for single-GPU training only).
