### ISSUE TITLE
A Continuing Training Problem

### ISSUE THREAD

**Issue by sxl845414442** [ultralytics/ultralytics#2183]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

After 100 epochs of training, I wanted to continue using the best. pt generated last time to continue training for 50 epochs, but an error occurred.
report errors——RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
![QQ截图20230422095858](https://user-images.githubusercontent.com/127416177/233755871-91fe67dd-38bc-4dc1-94a5-9a8d40d38a99.png)
![QQ截图20230422095657](https://user-images.githubusercontent.com/127416177/233755873-f148be03-4cc8-4ee2-8268-1afcc566cb56.png)

**Comment by glenn-jocher** [comment]
@sxl845414442 it looks like your error is related to tensor gradients. This error typically happens when you try to compute the gradients on a tensor that does not have the `requires_grad` flag set to true. Check out the tensor you are trying to compute gradients on and make sure it is set to `requires_grad = True`. You may also want to consider freezing certain layers and only updating certain parts of your network during training. You can find more information on freezing layers in the Ultralytics YOLOv8 documentation at https://docs.ultralytics.com/.

**Comment by AlainPilon** [comment]
Hi,

We are getting the same error once we try to train with more than 20 epoch using the same code sample supplied in the doc (but using our own set of about 10_000 images). I understand the initial post was about retraining an user made model, but why am I getting the same error with the yolov8x-cls model?

```
    model = YOLO('yolov8x-cls.pt') 
    model.train(data='/Users/xxx/Documents/yolo_test/dataset', epochs=200, imgsz=224, device="mps")
```

We have looked into the documentation but it is not obvious what we need to do.

**Comment by glenn-jocher** [comment]
@AlainPilon hi,

Thank you for reaching out. I understand that you are encountering a similar error when training with more than 20 epochs using the `yolov8x-cls` model and your own dataset of about 10,000 images. 

The error you are seeing, which states "RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn," is typically related to tensor gradients. This error occurs when you try to compute gradients on a tensor that does not have the `requires_grad` flag set to true.

To resolve this issue, you can try the following steps:

1. Check if the tensors you are trying to compute gradients on have the `requires_grad` flag set to true. If not, you can enable it by setting `requires_grad = True` for those tensors.

2. Make sure that you are setting the `requires_grad` flag for the necessary tensors, such as the model parameters, optimizer parameters, or any other tensors that participate in the gradient computation.

If you have already checked these steps and the issue persists, please provide more details about your dataset and any customizations or modifications you have made to the code so that we can help you further.

Thank you for your patience, and we will be happy to assist you with any additional questions or concerns you may have.

Best regards,
Glenn Jocher - Ultralytics YOLOv8 repo maintainer

**Comment by AlainPilon** [comment]
@glenn-jocher Your response looks pretty much like what I got from ChatGPT :-) . We did try to play with the `requires_grad` as best as we could but the Ultralytics doc falls short on explanations regarding how to do so. 

I cannot provide much more details about our issue as we are only running these two lines of code: 

```
    model = YOLO('yolov8x-cls.pt') 
    model.train(data='/Users/xxx/Documents/yolo_test/dataset', epochs=200, imgsz=224, device="mps")
```

and our dataset has about 10,000 pictures of various sizes and aspect ratio. 

I doubt the issue is with the images as we are able to train the model with 20 epoch, it only crashes once we try with a larger number of epoch (ex: 100+). 

We ran the code sample on MBP M1 and M2 and tried using the various provided classifier (yolov8n-cls.pt, yolov8x-cls.pt, etc...) with the same results. 

Finally, if we remove the `device="mps"` setting, we do not see the crash but the required training time is not acceptable.

Any guidance would be greatly appreciated.

**Comment by glenn-jocher** [comment]
Hi @AlainPilon,

Thank you for providing more details about your issue. I apologize for any confusion caused by the documentation. Let's dive into the problem you're facing.

Based on your description, it seems that you are experiencing a crash when training the YOLOv8 model with a larger number of epochs (e.g., 100+). While you have tried adjusting the `requires_grad` flag, it hasn't resolved the issue.

There are a few recommendations I can provide to help further troubleshoot and address the crashing problem:

1. **Batch size**: Consider decreasing the batch size used during training. Large batch sizes can consume significant memory, causing out-of-memory errors or crashes. You can try reducing the batch size until the training process is stable.

2. **Image size**: If your dataset contains images of various sizes and aspect ratios, resizing them to a consistent size can help with stability during training. You can try resizing the images to a fixed dimension, such as 416x416 pixels, to see if it improves the training process.

3. **Hardware limitations**: It's worth noting that training deep neural networks, especially on large datasets, can be resource-intensive. The crashes you are experiencing might be due to hardware limitations, such as insufficient GPU memory. Consider checking your hardware specifications to ensure they meet the requirements for running the model and training for a larger number of epochs.

In addition to these suggestions, I would also recommend inspecting any error messages or logs that are generated when the crash occurs. These details can provide valuable insights into the root cause of the issue.

I hope these recommendations help, and if you need further assistance or have any additional questions, please don't hesitate to let me know. I'll be glad to assist you.

Best regards,
Glenn Jocher - Ultralytics YOLOv8 repo maintainer

**Comment by reinhrst** [comment]
@AlainPilon thanks for your comments here. I had the exact same thing, and never would have considered that the number of epochs was the problem (default=116 epochs works fine, 117 gives above error); just be be clear, the error happens at the very start of training (which should be exactly the same for 117, and 116 epochs run, right?).

It only happens on `device=mps` (not CPU, and not CUDA (on another machine)).

Trying to narrow it down to where it happens is not so easy; So far I've been able to see where the first change happens between the 116 and 117 epoch run:

https://github.com/ultralytics/ultralytics/blob/62a0fb986a6f2ebe654594ea2d30f25e2b713a46/ultralytics/nn/tasks.py#L82

At some point the 116-epoch run returns a tensor with flags `device='mps:0', grad_fn=<SiluBackward0>)`, whereas the 117-epoch-tensor returns only `device='mps:0').

This lack of `grad_fn` remains for the rest of the iteration over the model (at some point changing to `UpsampleNearest2DBackward0` and `CatBackward0` for 116-eopch-run, while always be missing for 117-eopch-run).

This lack of the `grad-fn` seems to match up with the error message....

I might dive deeper into this at some later point....

**Comment by glenn-jocher** [comment]
Hi @reinhrst,

Thanks for sharing your detailed observations about the issue. Based on your description, it indeed looks like this issue is specific to using the Apple M1 ('mps') device, and the problem occurs when the number of epochs exceed 116.

The differing behaviors you're seeing in the returned tensors between the two scenarios - 116 epochs vs. 117 epochs - are quite interesting, particularly the missing gradient function (`grad_fn`) with 117 epochs.

As you know, the `grad_fn` attribute of a Tensor references the backward operation that created the Tensor. In this case, the fact that `grad_fn` is missing with 117 epochs suggests that the backward pass isn't working as expected. The missing backward operation ties in with the error message about tensors not requiring gradient and not having a `grad_fn`.

I agree with you that the issue likely lies somewhere within the initial preparation or setup of tensors for the backward computation when running on the 'mps' device for more than 116 epochs. However, without diving deeper into the codebase and the 'mps' implementation, pinning down the exact cause would be challenging.

Should you decide to investigate this further at a later point, please feel free to share any findings or updates. Your inputs are definitely valuable in gaining more understanding about this interesting issue.

**Comment by nguyeho7** [comment]
I can reproduce it for epochs=50. When I set epochs=10 it runs, when I set it to 50 it throws the problem above

**Comment by mxrguspxrtwork** [comment]
Lowering number of epochs seemed to help.

**Comment by glenn-jocher** [comment]
@mxrguspxrtwork hi,

Thank you for your input. From your comment, I understand that reducing the number of epochs mitigated the issue.

Deep learning models, such as YOLOv8, use iterative methods to learn from the data, and the number of cycles these iterative methods run is determined by the number of epochs. While more epochs could potentially improve the performance of the model by letting it learn more from the data, it could also increase the computational resources required, which might be the cause for the problem you encountered. 

To further help you, more details would be needed. For instance, it would be helpful to know the specific number of epochs that cause the issue, the volume and nature of your data, your hardware configuration amongst other things. 

If the issue persists with a higher number of epochs, you might need to look into optimizing your training process or even upgrading your hardware setup.

Keep me posted with your progress and please do not hesitate to ask if you have further questions. 

Best regards.

**Comment by philipperemy** [comment]
Why was this issue closed? The bug is still there with `8.0.178`.

**Comment by AlainPilon** [comment]
I think the number of epoch at which it crashes is related to the memory usage because in one case it was crashing around 30 epoch.

**Comment by reinhrst** [comment]
The interesting behaviour we're (I'm) seeing in this case is that training doesn't fail after 30 epochs; it fails on the first epoch if we specify more than 30 epochs (or, indeed, this number seems to be different for each training set; or possibly also dependent on machine). So what we should be looking for is if there is something that is different in the first epoch, depending on the number of epochs. I'm not sure I see how this could be (directly) a  memory problem.

**Comment by philipperemy** [comment]
@reinhrst some observation. I had this error at epoch=0 when the training was freshly starting. For some obscure reasons, I set `epochs=50` and it worked. But if I didn't specify any epochs, it would crash. I made sure that it was a fresh training. My server has 128GB of memory so it's more than enough. So the bug happens at init when some tensors are initialized.

**Comment by glenn-jocher** [comment]
Hi @reinhrst, 

Thank you for sharing your observations. Based on your description, it seems that explicitly setting `epochs=50` works to bypass the issue. It is indeed curious that the error arises at the start of training if we do not specify the epoch number, especially given that your server has sufficient memory. 

As you suggested, the cause of the error might be related to some form of tensor initialization that occurs during model initialization. It's plausible that when the epoch count is not specified, and the model is being initialized, certain tensors are being initialized or allocated in a way that is leading to this error. 

Further investigation would be needed to pinpoint the exact cause. One approach could be tracing back the behavior of the uninitialized tensors, and with a breakpoint set at the model initialization, see if there are discernible differences in tensor attributes or behaviors between the scenarios where `epochs=50` is set and where it's not. 

If you continue investigating and come across more insights, please feel free to share. Those would certainly add valuable contribution towards resolving this issue.

**Comment by Syazvinski** [comment]
I was having this issue too and googled this thread. I set epoch to 50 and it works. training now. But another issue im having is that the `model.train` dosen't seem to want to use more than 50%-60% of the GPU.

**Comment by glenn-jocher** [comment]
@philipperemy hello,

Thank you for your contribution to the discussion. It's great to hear that setting epochs to 50 enabled the training to proceed.

Regarding your GPU utilization issue, it's important to note that not all parts of the training process are fully parallelizable and can fully utilize the GPU's computational capabilities. Reading data, for example, is a process that often happens on the CPU before the data is moved to the GPU. This means that there could be idle periods for your GPU while the CPU is processing something, resulting in less-than-100% GPU usage.

Moreover, how much of the GPU's potential is used can depend on several factors such as the size of your model, the batch size, the specific operations used in your model, and more. Not all operations can use the GPU to its maximum capacity.

Please note that lower GPU utilization does not necessarily mean that you have a problem. However, if you want to maximize GPU usage, you should consider factors such as increasing the batch size, if your GPU memory allows, or changing the model's architecture to a more computationally heavy one.

Remember: using more of the GPU does not always translate to better or faster results, because over-utilization could lead to memory overhead and slow down your training process.

I hope this helps clarify your question.

Best,
Glenn Jocher

**Comment by novice91** [comment]
I am also encountering the same problem on cuda device but when the freeze value is set to >20. Changing epoch size doesn't bring any change, error persists. Freeze help mentions - help='Number of layers to freeze. backbone=10, all=24'. As a separate question, freeze=0 or freeze=20 brings no change in training time.  Unable to proceed ahead, kindly help.

**Comment by Alarmod** [comment]
Get same error, please fix it

**Comment by Alarmod** [comment]
8.0.176 - all OK, 8.0.177 - have bug with import Yolo from ultralytics, 8.0.178 and more new have this bug

**Comment by Alarmod** [comment]
@glenn-jocher
In 178 the pretrained flag appeared... It have default value True.
My Yolo loaded from "yolov8m-seg.yaml"... If I set pretrained=False, Yolo run perfect!!!

**Comment by glenn-jocher** [comment]
@Alarmod hi there! 👋

Thanks for sharing your findings. Indeed, specifying `pretrained=False` when loading your model from the YAML configuration can help circumvent the issue you're experiencing with the recent versions. This flag controls whether the model weights are loaded from a pre-trained checkpoint. Setting it to `False` means you're starting with an untrained model.

Here's a quick example on how to set it:
```python
from ultralytics import YOLO
model = YOLO('yolov8m-seg.yaml', pretrained=False)
```

We appreciate you pointing out this workaround! We'll look into the root cause of this behavior in newer versions to ensure smoother experience in the future. 

Happy coding! 🚀

**Comment by Alarmod** [comment]
@glenn-jocher
```
model = YOLO("yolov8m-seg.yaml", task="segment", pretrained=False).load(".\\runs\\segment\\gestures_segment_8m_original\\weights\\best.pt")
model.train(...)
```
_TypeError: __init__() got an unexpected keyword argument 'pretrained'_

I use another code
```
model = YOLO("yolov8m-seg.yaml", task="segment").load(".\\runs\\segment\\gestures_segment_8m_original\\weights\\best.pt")
model.train(..., pretrained=False)
```
or without load, working now OK

**Comment by glenn-jocher** [comment]
@Alarmod hey there! 🌟

Looks like there's been a little mix-up with where to place the `pretrained=False` flag.

For loading a model directly from a YAML file and then loading specific weights, you won't need to use `pretrained=False` while initializing the `YOLO` object. The correct approach is to first initialize the model and segmentation task and then load your custom weights using `.load()`. After that, you're all set to train your model!

Here's the adjusted snippet:
```python
model = YOLO("yolov8m-seg.yaml", task="segment").load(".\\runs\\segment\\gestures_segment_8m_original\\weights\\best.pt")
model.train(...)
```

Great to hear it's working well for you now! If you have any more questions or bump into other issues, feel free to drop a message. Happy coding! ✨

**Comment by Alarmod** [comment]
@glenn-jocher
Your variant always with error
_RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn_

Variant with pretrained=False always OK

**Comment by Alarmod** [comment]
This error appeared after increasing the number of classes from 8 to 10 and, accordingly, after increasing the number of training and test images

**Comment by Alarmod** [comment]
I tried reducing the number of training epochs and the number of images in the batch, no effect. Only adding _pretrained=False_  solves the problem

**Comment by Alarmod** [comment]
I retested it again, but without the pretrained flag. Only the path to the data for testing training + a different name of the yaml file has changed. Work now... it strange

**Comment by glenn-jocher** [comment]
@Alarmod it's great to hear that it's working for you now! 🚀 It seems like adjusting the path and the YAML configuration might have influenced the training setup in unexpected ways. Keep exploring, and feel free to reach out if you encounter any more quirks or if you have further questions. Happy coding!
