### ISSUE TITLE
how to show the predict image/vedio

### ISSUE THREAD

**Issue by xiaohangguo** [ultralytics/ultralytics#2194]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I use CLI teminal to run YOLOV8.
`yolo  mode=predict model='/home/hang/ultralytics/runs/detect/train2/weights/best.pt'  source=rtmp://xx/live/home show=True
`
but nothing showed.
And  it output:
```
QObject::moveToThread: Current thread (0x55a73c95b9b0) is not the object's thread (0x55a73c11a8d0).
Cannot move to target thread (0x55a73c95b9b0)

QObject::moveToThread: Current thread (0x55a73c95b9b0) is not the object's thread (0x55a73c11a8d0).
Cannot move to target thread (0x55a73c95b9b0)

```
then print the predict log,

```
0: 384x640 1 person, 2 ties, 1 bottle, 7.1ms
0: 384x640 1 person, 2 ties, 1 bottle, 7.3ms
0: 384x640 1 person, 2 ties, 1 bottle, 7.1ms
0: 384x640 1 person, 2 ties, 1 bottle, 7.3ms
0: 384x640 1 person, 1 tie, 1 bottle, 8.4ms
0: 384x640 1 person, 1 tie, 1 bottle, 6.9ms
0: 384x640 1 person, 1 tie, 1 bottle, 6.9ms

```
predict is no problem ,however, I want to see the processing results in real time.

I thought it was a problem with pyqt5, but after installation, the result still did not come out

**Comment by glenn-jocher** [comment]
@xiaohangguo it looks like the YOLOv8 model is correctly detecting objects based on the log you provided. The issue is with displaying the results in real-time through a GUI. It seems like there may be an issue with PyQt5, but even after installing it, the issue persists. One possible solution is to try a different GUI library or approach. You may also find helpful information in the Ultralytics YOLOv8 documentation, which provides guidance on GUI display options.

**Comment by xiaohangguo** [comment]
I am using the code 
`import cv2
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO('yolov8n.pt')

# Open the video file
video_path = "path/to/your/video/file.mp4"
cap = cv2.VideoCapture(video_path)

# Loop through the video frames
while cap.isOpened():
    # Read a frame from the video
    success, frame = cap.read()

    if success:
        # Run YOLOv8 inference on the frame
        results = model(frame)

        # Visualize the results on the frame
        annotated_frame = results[0].plot()

        # Display the annotated frame
        cv2.imshow("YOLOv8 Inference", annotated_frame)

        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        # Break the loop if the end of the video is reached
        break

# Release the video capture object and close the display window
cap.release()
cv2.destroyAllWindows()
`
But have the save problem

**Comment by Laughing-q** [comment]
@xiaohangguo I'm able to show with `show=True` option.
```bash
yolo detect predict show
```
the above command works to me.

**Comment by xiaohangguo** [comment]
I solved it. I tried reinstalling the environment and various methods, but in the end, I found that when I quickly ran the Pychart interpreter, there was a GUI display. However, when I started reasoning with cli, it wouldn't display. Yolov5 also had this problem. I don't know if it's a problem with the Ubuntu system.

**Comment by glenn-jocher** [comment]
@xiaohangguo It's great to hear that you were able to solve the issue by running the Pychart interpreter. It's possible that the absence of a graphical user interface (GUI) display when running reasoning with Command-Line Interface (CLI) in Ubuntu may be due to compatibility issues with the operating system or with the libraries that you are using. It's important to use the appropriate versions of libraries and dependencies to ensure smooth functioning of the models. I would suggest checking the system requirements for the relevant libraries and dependencies and confirming their compatibility with your Ubuntu system.
