### ISSUE TITLE
How to correctly use Ray Tune and YOLOv8?

### ISSUE THREAD

**Issue by IslemAI** [ultralytics/ultralytics#2209]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to optimize the hyperparameters of YOLOv8 detector using the Ray Tune method. I followed the documentation of **Ultralytics YOLOv8 Docs Hyperparameter Tuning with Ray Tune and YOLOv8** in the page https://docs.ultralytics.com/usage/hyperparameter_tuning/?h=tune, and when I run the code, I obtained the following error message:  

![image](https://user-images.githubusercontent.com/130391874/233903352-d4f39864-7ac5-4706-9e8f-a16f22234759.png)

This is the code:
`%pip install ultralytics
%pip install -U ultralytics "ray[tune]" 

%cd /content/drive/MyDrive/Colab/YOLOv8

from ultralytics import YOLO
from ray import tune

model = YOLO("yolov8n.pt")
results = model.tune(data="./data/ultralyticsmain/ultralytics/datasets/ICH.yml", train_args={'epochs':100, 'imgsz':512})`

**Comment by glenn-jocher** [comment]
@IslemAI based on the error message, it looks like there might be an issue with importing the `get_train_globals` function from `utils.torch_utils`. This could be due to a few different things, such as the file not being located in the correct location or there being a typo in the file path. I would recommend double-checking that the file is located where it should be and ensure that the file path in your `import` statement is correct. Additionally, feel free to refer to the documentation or reach out to the Ultralytics YOLOv8 community for further assistance.

**Comment by BhaveshWadibhasme** [comment]
PermissionError: [Errno 13] Permission denied: '/proc/driver/nvidia/gpus'

**Comment by nadinator** [comment]
Hi, I'm running into a similar error. Except when I run model.tune(), my jupyter kernel crashes after 20 seconds with no info on what happened. A local Ray instance is started but then the kernel just crashes. Any idea what's happening?

**Comment by pderrenger** [comment]
@nadinator it seems like the crashing of the Jupyter kernel after running `model.tune()` with no error message might be related to a resource issue or conflict with the Ray instance. This could be due to resource constraints or conflicts with other running processes. I recommend checking the available system resources, such as memory and GPU usage, to ensure that there are no conflicts. Additionally, checking the logs and status of the Ray instance could provide more insights into the issue. If the problem persists, reaching out to the Ultralytics YOLOv8 community or Ray Tune support for further assistance could be beneficial.

**Comment by itanab** [comment]
Hi, I also seem to have similar issue. I am trying to run a minimal hyperparam. optimization search for YOLOv8, only searching over few combinations of lr and batch size. 

Do you know what could be the issue? I got this error log for each process the same:
I have a RTX 3090 GPU and I was monitoring the usage, it was actually 2% because the process killed before starting.

Logical resource usage: 32.0/32 CPUs, 0/1 GPUs
Trial _tune_6b9bb_00005 errored after 0 iterations at 2023-12-06 22:07:25. Total running time: 15s
Error file: C:/Users/ibulatovic/ray_results/_tune_2023-12-06_22-07-10/_tune_6b9bb_00005_5_batch_size=16,lr=0.0304_2023-12-06_22-07-11\error.txt
2023-12-06 22:07:25,717 WARNING resource_updater.py:262 -- Cluster resources not detected or are 0. Attempt #2...
[2023-12-06 22:07:25,733 E 15388 34428] core_worker.cc:592: :info_message: Attempting to recover 1 lost objects by resubmitting their tasks. To disable object reconstruction, set @ray.remote(max_retries=0).
2023-12-06 22:07:26,233 WARNING resource_updater.py:262 -- Cluster resources not detected or are 0. Attempt #3...
2023-12-06 22:07:26,733 WARNING resource_updater.py:262 -- Cluster resources not detected or are 0. Attempt #4...
2023-12-06 22:07:27,249 WARNING resource_updater.py:262 -- Cluster resources not detected or are 0. Attempt #5...
2023-12-06 22:07:27,764 WARNING resource_updater.py:275 -- Cluster resources cannot be detected or are 0. You can resume this experiment by passing in `resume=True` to `run`.
2023-12-06 22:07:27,764 ERROR tune_controller.py:1383 -- Trial task failed for trial _tune_6b9bb_00006
Traceback (most recent call last):
  File "F:\SOFT\Anaconda\envs\yolov8_tune\lib\site-packages\ray\air\execution\_internal\event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "F:\SOFT\Anaconda\envs\yolov8_tune\lib\site-packages\ray\_private\auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "F:\SOFT\Anaconda\envs\yolov8_tune\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "F:\SOFT\Anaconda\envs\yolov8_tune\lib\site-packages\ray\_private\worker.py", line 2565, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
        class_name: ImplicitFunc
        actor_id: 2b38ed29c089d5082d0227d001000000
        namespace: 7999ef11-5937-41a7-b620-0b50f5116d42
The actor is dead because its node has died. Node Id: 36f584bfbd80a4d2d4455d0a5d69706871d7bd25f6b2ee662f090568
The actor never ran - it was cancelled before it started running.


Also, above this error I got these logs, I couldn't find any similar issue:


(raylet) [2023-12-06 22:07:11,513 E 30988 36832] (raylet.exe) agent_manager.cc:70: The raylet exited immediately because one Ray agent failed, agent_name = dashboard_agent/15724.
(raylet) The raylet fate shares with the agent. This can happen because
(raylet) - The version of `grpcio` doesn't follow Ray's requirement. Agent can segfault with the incorrect `grpcio` version. Check the grpcio version `pip freeze | grep grpcio`.
(raylet) - The agent failed to start because of unexpected error or port conflict. Read the log `cat /tmp/ray/session_latest/logs/{dashboard_agent|runtime_env_agent}.log`. You can find the log file structure here https://docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure.
(raylet) - The agent is killed by the OS (e.g., out of memory).
(raylet) *** SIGTERM received at time=1701896831 ***
(raylet)     @   00007FF741BF85C6  (unknown)  (unknown)
(raylet)     @   00007FF741C0EE86  (unknown)  (unknown)
(raylet)     @   00007FF741C0E5BE  (unknown)  (unknown)
(raylet)     @   00007FFA1C419363  (unknown)  recalloc
(raylet)     @   00007FFA1CE526AD  (unknown)  BaseThreadInitThunk
(raylet)     @   00007FFA1EF8AA68  (unknown)  RtlUserThreadStart
(raylet) [2023-12-06 22:07:11,523 E 30988 36832] (raylet.exe) logging.cc:361: *** SIGTERM received at time=1701896831 ***
(raylet) [2023-12-06 22:07:11,523 E 30988 36832] (raylet.exe) logging.cc:361:     @   00007FF741BF85C6  (unknown)  (unknown)
(raylet) [2023-12-06 22:07:11,523 E 30988 36832] (raylet.exe) logging.cc:361:     @   00007FF741C0EE86  (unknown)  (unknown)
(raylet) [2023-12-06 22:07:11,523 E 30988 36832] (raylet.exe) logging.cc:361:     @   00007FF741C0E5BE  (unknown)  (unknown)
(raylet) [2023-12-06 22:07:11,523 E 30988 36832] (raylet.exe) logging.cc:361:     @   00007FFA1C419363  (unknown)  recalloc
(raylet) [2023-12-06 22:07:11,523 E 30988 36832] (raylet.exe) logging.cc:361:     @   00007FFA1CE526AD  (unknown)  BaseThreadInitThunk
(raylet) [2023-12-06 22:07:11,523 E 30988 36832] (raylet.exe) logging.cc:361:     @   00007FFA1EF8AA68  (unknown)  RtlUserThreadStart
2023-12-06 22:07:25,717 WARNING worker.py:2074 -- The node with node id: 36f584bfbd80a4d2d4455d0a5d69706871d7bd25f6b2ee662f090568 and address: 127.0.0.1 and node name: 127.0.0.1 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a       (1) raylet crashes unexpectedly (OOM, preempted node, etc.) 
        (2) raylet has lagging heartbeats due to slow network or busy workload.
2023-12-06 22:07:25,717 ERROR tune_controller.py:1383 -- Trial task failed for trial _tune_6b9bb_00005

**Comment by nadinator** [comment]
> @nadinator it seems like the crashing of the Jupyter kernel after running `model.tune()` with no error message might be related to a resource issue or conflict with the Ray instance. This could be due to resource constraints or conflicts with other running processes. I recommend checking the available system resources, such as memory and GPU usage, to ensure that there are no conflicts. Additionally, checking the logs and status of the Ray instance could provide more insights into the issue. If the problem persists, reaching out to the Ultralytics YOLOv8 community or Ray Tune support for further assistance could be beneficial.

These auto-generated responses are damn annoying, and not in the least bit helpful.

**Comment by nadinator** [comment]
> Hi, I also seem to have similar issue. I am trying to run a minimal hyperparam. optimization search for YOLOv8, only searching over few combinations of lr and batch size. 
> 
> 
> 
> Do you know what could be the issue? I got this error log for each process the same:
> 
> I have a RTX 3090 GPU and I was monitoring the usage, it was actually 2% because the process killed before starting.
> 
> 
> 
> Logical resource usage: 32.0/32 CPUs, 0/1 GPUs
> 
> Trial _tune_6b9bb_00005 errored after 0 iterations at 2023-12-06 22:07:25. Total running time: 15s
> 
> Error file: C:/Users/ibulatovic/ray_results/_tune_2023-12-06_22-07-10/_tune_6b9bb_00005_5_batch_size=16,lr=0.0304_2023-12-06_22-07-11\error.txt
> 
> 2023-12-06 22:07:25,717 WARNING resource_updater.py:262 -- Cluster resources not detected or are 0. Attempt #2...
> 
> [2023-12-06 22:07:25,733 E 15388 34428] core_worker.cc:592: :info_message: Attempting to recover 1 lost objects by resubmitting their tasks. To disable object reconstruction, set @ray.remote(max_retries=0).
> 
> 2023-12-06 22:07:26,233 WARNING resource_updater.py:262 -- Cluster resources not detected or are 0. Attempt #3...
> 
> 2023-12-06 22:07:26,733 WARNING resource_updater.py:262 -- Cluster resources not detected or are 0. Attempt #4...
> 
> 2023-12-06 22:07:27,249 WARNING resource_updater.py:262 -- Cluster resources not detected or are 0. Attempt #5...
> 
> 2023-12-06 22:07:27,764 WARNING resource_updater.py:275 -- Cluster resources cannot be detected or are 0. You can resume this experiment by passing in `resume=True` to `run`.
> 
> 2023-12-06 22:07:27,764 ERROR tune_controller.py:1383 -- Trial task failed for trial _tune_6b9bb_00006
> 
> Traceback (most recent call last):
> 
>   File "F:\SOFT\Anaconda\envs\yolov8_tune\lib\site-packages\ray\air\execution\_internal\event_manager.py", line 110, in resolve_future
> 
>     result = ray.get(future)
> 
>   File "F:\SOFT\Anaconda\envs\yolov8_tune\lib\site-packages\ray\_private\auto_init_hook.py", line 24, in auto_init_wrapper
> 
>     return fn(*args, **kwargs)
> 
>   File "F:\SOFT\Anaconda\envs\yolov8_tune\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
> 
>     return func(*args, **kwargs)
> 
>   File "F:\SOFT\Anaconda\envs\yolov8_tune\lib\site-packages\ray\_private\worker.py", line 2565, in get
> 
>     raise value
> 
> ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
> 
>         class_name: ImplicitFunc
> 
>         actor_id: 2b38ed29c089d5082d0227d001000000
> 
>         namespace: 7999ef11-5937-41a7-b620-0b50f5116d42
> 
> The actor is dead because its node has died. Node Id: 36f584bfbd80a4d2d4455d0a5d69706871d7bd25f6b2ee662f090568
> 
> The actor never ran - it was cancelled before it started running.
> 
> 
> 
> 
> 
> Also, above this error I got these logs, I couldn't find any similar issue:
> 
> 
> 
> 
> 
> (raylet) [2023-12-06 22:07:11,513 E 30988 36832] (raylet.exe) agent_manager.cc:70: The raylet exited immediately because one Ray agent failed, agent_name = dashboard_agent/15724.
> 
> (raylet) The raylet fate shares with the agent. This can happen because
> 
> (raylet) - The version of `grpcio` doesn't follow Ray's requirement. Agent can segfault with the incorrect `grpcio` version. Check the grpcio version `pip freeze | grep grpcio`.
> 
> (raylet) - The agent failed to start because of unexpected error or port conflict. Read the log `cat /tmp/ray/session_latest/logs/{dashboard_agent|runtime_env_agent}.log`. You can find the log file structure here https://docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure.
> 
> (raylet) - The agent is killed by the OS (e.g., out of memory).
> 
> (raylet) *** SIGTERM received at time=1701896831 ***
> 
> (raylet)     @   00007FF741BF85C6  (unknown)  (unknown)
> 
> (raylet)     @   00007FF741C0EE86  (unknown)  (unknown)
> 
> (raylet)     @   00007FF741C0E5BE  (unknown)  (unknown)
> 
> (raylet)     @   00007FFA1C419363  (unknown)  recalloc
> 
> (raylet)     @   00007FFA1CE526AD  (unknown)  BaseThreadInitThunk
> 
> (raylet)     @   00007FFA1EF8AA68  (unknown)  RtlUserThreadStart
> 
> (raylet) [2023-12-06 22:07:11,523 E 30988 36832] (raylet.exe) logging.cc:361: *** SIGTERM received at time=1701896831 ***
> 
> (raylet) [2023-12-06 22:07:11,523 E 30988 36832] (raylet.exe) logging.cc:361:     @   00007FF741BF85C6  (unknown)  (unknown)
> 
> (raylet) [2023-12-06 22:07:11,523 E 30988 36832] (raylet.exe) logging.cc:361:     @   00007FF741C0EE86  (unknown)  (unknown)
> 
> (raylet) [2023-12-06 22:07:11,523 E 30988 36832] (raylet.exe) logging.cc:361:     @   00007FF741C0E5BE  (unknown)  (unknown)
> 
> (raylet) [2023-12-06 22:07:11,523 E 30988 36832] (raylet.exe) logging.cc:361:     @   00007FFA1C419363  (unknown)  recalloc
> 
> (raylet) [2023-12-06 22:07:11,523 E 30988 36832] (raylet.exe) logging.cc:361:     @   00007FFA1CE526AD  (unknown)  BaseThreadInitThunk
> 
> (raylet) [2023-12-06 22:07:11,523 E 30988 36832] (raylet.exe) logging.cc:361:     @   00007FFA1EF8AA68  (unknown)  RtlUserThreadStart
> 
> 2023-12-06 22:07:25,717 WARNING worker.py:2074 -- The node with node id: 36f584bfbd80a4d2d4455d0a5d69706871d7bd25f6b2ee662f090568 and address: 127.0.0.1 and node name: 127.0.0.1 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a       (1) raylet crashes unexpectedly (OOM, preempted node, etc.) 
> 
>         (2) raylet has lagging heartbeats due to slow network or busy workload.
> 
> 2023-12-06 22:07:25,717 ERROR tune_controller.py:1383 -- Trial task failed for trial _tune_6b9bb_00005
> 
> 

If you're on windows, always keep at least 3 cpus free. It needs them for some background processes, otherwise it'll crash and burn any running program.

**Comment by itanab** [comment]
Hi, I solved this problem by installing these versions. There seem to be a compatibility issue.

pip install grpcio==1.59.0 ray==2.8.1

**Comment by glenn-jocher** [comment]
@itanab glad to hear you resolved the issue! It does indeed seem that specific versions of `grpcio` and `ray` can have compatibility issues. Sticking to versions that work well together as you've found is a good approach. If others encounter similar problems, adjusting their package versions as you did might be a beneficial troubleshooting step. Thanks for sharing your solution! 🛠️🚀

**Comment by kanis777** [comment]
so @itanab . I got the same error as you did . but when i tried using ray==2.8.1 as per your solution to compatibility - i got an altogether different response and nothing started working . (a new error popped up).

> 2024-06-27 09:57:57,707 ERROR services.py:1329 -- Failed to start the dashboard , return code 1
> 2024-06-27 09:57:57,707 ERROR services.py:1354 -- Error should be written to 'dashboard.log' or 'dashboard.err'. We are printing the last 20 lines for you. See 'https://docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure' to find where the log file is.
> 2024-06-27 09:57:57,708 ERROR services.py:1398 --
> The last 20 lines of /tmp/ray/session_2024-06-27_09-57-55_823269_1562488/logs/dashboard.log (it contains the error message from the dashboard):
>   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/home/dev/.local/lib/python3.10/site-packages/ray/dashboard/modules/job/cli.py", line 16, in <module>
>     from ray.job_submission import JobStatus, JobSubmissionClient
>   File "/home/dev/.local/lib/python3.10/site-packages/ray/job_submission/__init__.py", line 2, in <module>
>     from ray.dashboard.modules.job.pydantic_models import DriverInfo, JobDetails, JobType
>   File "/home/dev/.local/lib/python3.10/site-packages/ray/dashboard/modules/job/pydantic_models.py", line 4, in <module>
>     from ray._private.pydantic_compat import BaseModel, Field, PYDANTIC_INSTALLED
>   File "/home/dev/.local/lib/python3.10/site-packages/ray/_private/pydantic_compat.py", line 100, in <module>
>     monkeypatch_pydantic_2_for_cloudpickle()
>   File "/home/dev/.local/lib/python3.10/site-packages/ray/_private/pydantic_compat.py", line 58, in monkeypatch_pydantic_2_for_cloudpickle
>     pydantic._internal._model_construction.SchemaSerializer = (
> AttributeError: module 'pydantic._internal' has no attribute '_model_construction'
> 2024-06-27 09:57:57,857 INFO worker.py:1673 -- Started a local Ray instance.
> [2024-06-27 09:57:59,229 C 1562488 1562488] plasma_store_provider.cc:73:  Check failed: _s.ok() Bad status: IOError: Connection reset by peer

Could you possibly help  me out ???
