### ISSUE TITLE
Add an option to Ignore missed 'difficult' objects during training

### ISSUE THREAD

**Issue by ophirhan** [ultralytics/ultralytics#2211]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

**Motivation:**
The decision to tag or ignore "difficult" objects (truncated/occluded/small/poorly lit) is currently left to the annotator's discretion and can result in inconsistent results. If the annotator decided not to annotate the object and the object was detected during training this would incur loss which will penalize the model for good behavior. On the other hand, If the annotator decides to annotate a poorly lit object it most likely wouldn't be beneficial for the model to learn from it, and might never converge on detecting it.

One solution is to delete images containing 'difficult' objects, but these images might have other objects which the model can learn from.
To ensure a more consistent and standardized approach, it would be helpful to tag **all** identifiable objects and add the "difficult" attribute to suitable objects and use it in training.

**Proposed Functionality:** 
During training, the following rules should apply:
- If the 'difficult' object was correctly detected and classified, no loss should be incurred.
- If the 'difficult' object was not detected, no loss should be incurred.
- If the 'difficult' object  was detected but misclassified, loss should be incurred 

### Use case

Anyone training fine tuning the models

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Thank you for sharing the discussion link, @ophirhan! 

Regarding your proposal to tag difficult objects, it's a great idea to make the model more consistent in its approach. This could be accomplished by adding an attribute for "difficult" objects to the annotation file, which could then be used during training to incorporate the behavior you suggested. However, one challenge is how to identify the appropriate threshold for marking an object as "difficult" since it can vary depending on the use case.

I recommend experimenting with different thresholds for different object sizes, lighting conditions, etc., to determine what works best for your specific project. Additionally, you may want to consider experimenting with adjusting the detection confidence threshold to limit false positives, and using metrics like precision and recall to evaluate the model's performance on difficult objects.

Overall, tagging difficult objects is a useful technique to help improve model performance but requires experimentation and adjustments to optimize its effectiveness.

**Comment by glenn-jocher** [comment]
@ophirhan as the author and maintainer of Ultralytics YOLOv8, I can see the potential value of adding the feature you have proposed for marking 'difficult' objects during training. It could help bring more consistency to the model's performance and help ensure the model is trained on diverse yet effective data samples. However, as with any feature, it requires careful design and implementation before it can be effectively integrated into the codebase. This is something that we will discuss in the Ultralytics team, and we'll evaluate the feasibility of adding this feature. Thank you for your valuable feedback!
