### ISSUE TITLE
Yolo doesn`t work with gpu(cpu works fine)

### ISSUE THREAD

**Issue by bod9s** [ultralytics/ultralytics#2218]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Other

### Bug

```
Pytorch recognizes my gpu clearly.
cuda.is.available - True


Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\bod9\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\bod9\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\bod9\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\bod9\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\bod9\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\bod9\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\bod9\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\yoloq_project\yoloq.py", line 5, in <module>
    model.train(data='yoloq_dataset', epochs=1, imgsz=64)
  File "C:\yoloq_venv\lib\site-packages\ultralytics\yolo\engine\model.py", line 370, in train
    self.trainer.train()
  File "C:\yoloq_venv\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 191, in train
    self._do_train(world_size)
  File "C:\yoloq_venv\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 268, in _do_train
    self._setup_train(world_size)
  File "C:\yoloq_venv\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 250, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode='train')
  File "C:\yoloq_venv\lib\site-packages\ultralytics\yolo\v8\classify\train.py", line 76, in get_dataloader
    loader = build_classification_dataloader(path=dataset_path,
  File "C:\yoloq_venv\lib\site-packages\ultralytics\yolo\data\build.py", line 132, in build_classification_dataloader
    return InfiniteDataLoader(dataset,
  File "C:\yoloq_venv\lib\site-packages\ultralytics\yolo\data\build.py", line 30, in __init__
    self.iterator = super().__iter__()
  File "C:\yoloq_venv\lib\site-packages\torch\utils\data\dataloader.py", line 442, in __iter__
    return self._get_iterator()
  File "C:\yoloq_venv\lib\site-packages\torch\utils\data\dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\yoloq_venv\lib\site-packages\torch\utils\data\dataloader.py", line 1043, in __init__
    w.start()
  File "C:\Users\bod9\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\bod9\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\bod9\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\bod9\AppData\Local\Programs\Python\Python38\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\bod9\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\bod9\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

### Environment

Ultralytics YOLOv8.0.86  Python-3.8.10 torch-2.0.0+cu118 CUDA:0 (NVIDIA GeForce GTX 1070, 8192MiB)
OS: Windows 10 Pro x64
Python: 3.8.10

### Minimal Reproducible Example

```
from ultralytics import YOLO
model = YOLO('yolov8s-cls.pt')
model.train(data='yoloq_dataset', epochs=1, imgsz=64)
```
Running this simple code to just test that YOLOv8 train works fine, but got a RuntimeError when starting with GPU.
Path to the dataset is fine. All requsted libraries is installed. Working in custom virtual environment. With CPU code works fine.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by ToberoCat** [comment]
I've had the same issue and found a workaround to it.
I just used the CLI instead of a python script. It's not an actual solution, but you can get away with it when you just want the default training provided by yolo out of the box.

Here's the command I've used to train a detection model:
`yolo detect train data=data.yaml model=yolov8n.pt epochs=10 imgsz=640`

**Comment by bod9s** [comment]
> I've had the same issue and found a workaround to it. I just used the CLI instead of a python script. It's not an actual solution, but you can get away with it when you just want the default training provided by yolo out of the box.
> 
> Here's the command I've used to train a detection model: `yolo detect train data=data.yaml model=yolov8n.pt epochs=10 imgsz=640`

Hello there, thanks for your answer. Check what I wrote at additional details.

**Comment by glenn-jocher** [comment]
@bod9s thank you for providing additional details. It seems that you are experiencing an issue when using a customized training script with YOLOv8. One possible workaround for this issue, as suggested by another user, is to use the YOLOv8 command line interface (CLI) instead of a custom script. The CLI provides a default training configuration out of the box that you can use to train your detection model. However, this solution may not be ideal if you need to modify the training process or use a custom dataset. Therefore, it may be worth investigating the issue further to find a solution that works for your specific scenario using a customized training script.

**Comment by glenn-jocher** [comment]
@bod9s i apologize for the mistake in my previous response. Using the CLI did not solve the issue you are experiencing with your custom training script. The error message you are receiving, "TypeError: expected str, bytes or os.PathLike object, not NoneType", means that there is a variable that is not initialized properly and is returning a value of None. 

To fix this error, you should check your code and ensure that all variables are correctly initialized before being used further in the script. One possible approach is to use print statements to check the values of the variables as the script runs. Additionally, you can use the Python debugger to step through the code and see where the error is occurring.

In summary, the issue you are experiencing with your custom training script is likely due to a variable not being initialized properly. You should review your code and check all variables are correctly initialized, using print statements or the Python debugger to debug the issue. I hope this helps.

**Comment by bod9s** [comment]
> @bod9s i apologize for the mistake in my previous response. Using the CLI did not solve the issue you are experiencing with your custom training script. The error message you are receiving, "TypeError: expected str, bytes or os.PathLike object, not NoneType", means that there is a variable that is not initialized properly and is returning a value of None.
> 
> To fix this error, you should check your code and ensure that all variables are correctly initialized before being used further in the script. One possible approach is to use print statements to check the values of the variables as the script runs. Additionally, you can use the Python debugger to step through the code and see where the error is occurring.
> 
> In summary, the issue you are experiencing with your custom training script is likely due to a variable not being initialized properly. You should review your code and check all variables are correctly initialized, using print statements or the Python debugger to debug the issue. I hope this helps.

@glenn-jocher 
My code is simply:
```
from ultralytics import YOLO
model = YOLO('yolov8s-cls.pt')
model.train(data="C:/yoloq_project/datasets/yoloq_dataset", epochs=1, imgsz=64)
```

Also I tried to data='yoloq_dataset' at main.py folder, but nothing works. I can't understand why code does not initialize data variable as path. I dont even imagine how I can fix that...

**Comment by bod9s** [comment]
@glenn-jocher 

I reinstalled yolov8 at different virtual environments many time. I even reinstalled window, so I don't think that problem could be with dependencies or smth.

Also when I'm running code without `if __name__=='__main__':` - I still have problem:
```
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

```

But it fixes with `if __name__=='__main__':`.

So main error is `TypeError: expected str, bytes or os.PathLike object, not NoneType`.
What information I can provide to help you understand the root of the problem?

So after running code I`m getting this traceback:
```
Traceback (most recent call last):
  File "C:\yoloq_project\yoloq.py", line 4, in <module>
    model.train(data="C:/yoloq_project/datasets/yoloq_dataset", epochs=1, imgsz=64)
  File "C:\yoloq_venv\lib\site-packages\ultralytics\yolo\engine\model.py", line 370, in train
    self.trainer.train()
  File "C:\yoloq_venv\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 191, in train
    self._do_train(world_size)
  File "C:\yoloq_venv\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 268, in _do_train
    self._setup_train(world_size)
  File "C:\yoloq_venv\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 252, in _setup_train
    self.test_loader = self.get_dataloader(self.testset, batch_size=batch_size * 2, rank=-1, mode='val')
  File "C:\yoloq_venv\lib\site-packages\ultralytics\yolo\v8\classify\train.py", line 76, in get_dataloader
    loader = build_classification_dataloader(path=dataset_path,
  File "C:\yoloq_venv\lib\site-packages\ultralytics\yolo\data\build.py", line 125, in build_classification_dataloader
    dataset = ClassificationDataset(root=path, imgsz=imgsz, augment=augment, cache=cache)
  File "C:\yoloq_venv\lib\site-packages\ultralytics\yolo\data\dataset.py", line 242, in __init__
    super().__init__(root=root)
  File "C:\yoloq_venv\lib\site-packages\torchvision\datasets\folder.py", line 309, in __init__
    super().__init__(
  File "C:\yoloq_venv\lib\site-packages\torchvision\datasets\folder.py", line 145, in __init__
    samples = self.make_dataset(self.root, class_to_idx, extensions, is_valid_file)
  File "C:\yoloq_venv\lib\site-packages\torchvision\datasets\folder.py", line 189, in make_dataset
    return make_dataset(directory, class_to_idx, extensions=extensions, is_valid_file=is_valid_file)
  File "C:\yoloq_venv\lib\site-packages\torchvision\datasets\folder.py", line 61, in make_dataset
    directory = os.path.expanduser(directory)
  File "C:\Users\bod9\AppData\Local\Programs\Python\Python38\lib\ntpath.py", line 293, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Can you please specify what can I do to get more information or to help you understand the problem? <3

**Comment by bod9s** [comment]
@glenn-jocher 
So I found a bug, I`m receiving errors only when I`m preinstalling pytorch with cuda.
When I`m installing only ultralytics it works fine on cpu. 
But I have problems with pytorch(with cuda).
Running on cpu is very long, I need gpu support. How do you think what could be wrong with pytorch cuda?

**Comment by bod9s** [comment]
![image](https://user-images.githubusercontent.com/126963563/234342043-72d9e796-45a7-4b7c-b66f-3a61d87255a5.png)
PyTorch is recognizing videocard so what could be wrong with yolo ?

**Comment by bod9s** [comment]
![image](https://user-images.githubusercontent.com/126963563/234343322-4fc4bf58-2ebc-4070-9935-1bb7bb004aae.png)
When I`m running with cpu - it works.

![image](https://user-images.githubusercontent.com/126963563/234343492-92d8f54c-3c5a-4db2-9c20-be5d2a82d1e8.png)
When on gpu - it doesn`t...

**Comment by yikang-shen** [comment]
Same issue here. I was just running the sample coco128-seg sample on Windows. It seems the torchvision dataloader doesn't work properly with multiprocessor. Set the worker=0 should make it work with GPU (for me it works), however it is still slow because of the time loading data and all the metrics becomes nan in such circumstance.

**Comment by bod9s** [comment]
> Same issue here. I was just running the coco128-seg sample on Windows. It seems the torchvision dataloader doesn't work properly with multiprocessor. Set the worker=0 should make it work with GPU (for me it works), however it is still slow because of the time loading data and all the metrics becomes nan in such circumstance.
> 
> I tested the same code on Ubuntu, it works fine. I think this issue only happens on Windows.

@yikang-shen @glenn-jocher 
It works but it slow, my gpu only 15-20% loaded this way

**Comment by glenn-jocher** [comment]
Hello @JeremyMahieu, it seems that you are experiencing an issue with YOLOv8 where you receive a "TypeError: expected str, bytes or os.PathLike object, not NoneType" message. This error indicates that there is a variable in your code that is not properly initialized and is returning a value of None. To fix this error, you should review your code and ensure that all variables are properly initialized before being used further in the script. One approach might be to use print statements to check the values of the variables as the script runs or use the Python debugger to step through the code and see where the error is occurring. While this may take some time, it will help in identifying and solving the issue. Good luck!

**Comment by Hommoner** [comment]
@bod9s 
try this one
```
from ultralytics import YOLO
model = YOLO('yolov8s-cls.pt')
model.train(data='yoloq_dataset', epochs=1, imgsz=64,workers=0)
```

**Comment by Burhan-Q** [comment]
I'm running into the same issue. The strange part I'm running into, is that for troubleshooting, I manually loaded the ClassificationDataset class and was able to build it without issue. Additionally inspecting the model object in python, I see that the directory names are present for the class names property. I have more troubleshooting to do, but thought I'd share in case anyone else can get to a solution quicker.

I tried setting `workers=0` but that didn't help for me. I will have to try running the model on the CPU to see if it changes it at all.

**Comment by Burhan-Q** [comment]
Ran into the same error when attempting to run train on CPU.

Curious things to note:

- If I run this command, there is no error:
```py
model.trainer.build_dataset(img_path=data_dir) 
Dataset ClassificationDataset
    Number of datapoints: 38015
    Root location: Q:/ML_data/MixedWM38/2023-05-02_MixedWM38_Kaggle/data
```
- after running the above, I can check the `data` property and see:
```py
model.trainer.data
{'names': {0: 'C_EL',  
           1: 'C_EL_L',
           2: 'C_EL_S',
           3: 'C_ER',  
           4: 'C_ER_L',
           5: 'C_ER_S',
           6: 'C_L',   
           7: 'C_L_EL_S',
           8: 'C_L_ER_S',
           9: 'C_L_S',
           10: 'C_S',
           11: 'Center',
           12: 'D_EL',
           13: 'D_EL_L',
           14: 'D_EL_S',
           15: 'D_ER',
           16: 'D_ER_L',
           17: 'D_ER_S',
           18: 'D_L',
           19: 'D_L_EL_S',
           20: 'D_L_ER_S',
           21: 'D_L_S',
           22: 'D_S',
           23: 'Donut',
           24: 'EL_L',
           25: 'EL_L_S',
           26: 'EL_S',
           27: 'ER_L',
           28: 'ER_L_S',
           29: 'ER_S',
           30: 'Edge_Loc',
           31: 'Edge_Ring',
           32: 'L_S',
           33: 'Loc',
           34: 'Near_Full',
           35: 'Normal',
           36: 'Random',
           37: 'Scratch'},
 'nc': 38,
 'test': None,
 'train': WindowsPath('Q:/ML_data/MixedWM38/2023-05-02_MixedWM38_Kaggle/data/train'),
 'val': None}
```
Where I think the issue might be coming from. The `val` and `test` directories are both `None`

In fact, running my training command with `model.train(val=False)` did not display the error and begun the training. I'll have to see if I can track down where `val` is passed, but perhaps someone on the Ultralytics team (or more experienced in tracing code) can find it quicker.

**Comment by Burhan-Q** [comment]
Confirmed, even on GPU, setting `val=False` does mitigate the error.

**Comment by Burhan-Q** [comment]
@bod9s, hopefully this workaround helps for your circumstances

Even with `val=False` at the end of the training run, it did validate the model and I found that `model.trainer.data['val']` was updated with the correct directory. I then ran the training again, this time with `val=True` and did not receive the error. So it appears this is caused by the `None` value being populated for `model.trainer.data['val']` prior to training, and can simply be bypassed with `val=False` or manually updating the property before training, with  `model.trainer.data['val'] = "path/to/val"` 

Note, I only attempted this for the Classify task as that is what I was working on when I ran into the issue. I have not and won't be able to test on any other tasks in the near future as I need to finish my work with the Classification model.

**Comment by Burhan-Q** [comment]
Adding another note here for a strange behavior I noticed. After my previous run, I did a full training session and was analyzing the data. I decided to close that python session and rerun a test. When I did, I was not able to execute `model.trainer.data['val'] = "path/to/val"` prior to training since the model did not have a `trainer` method attached yet. 

I decided to attempt to run the training anyhow (with argument `val=True`) and there was no error. Seems that this may occur on the first instance of trying to run training with the classification task, but does not occur on subsequent runs (making it more difficult to replicate). I have not yet checked if the error returns after system restart or if I create a new `venv` and attempt to run training. If/when I get the opportunity, I will attempt to test these and share my findings here.

**Comment by glenn-jocher** [comment]
@Hommoner hello,

Thank you for sharing your experience with YOLOv8. It seems that you have run into an issue where setting `model.trainer.data['val']` to None is causing a `TypeError: must be str, not NoneType` error during training. You have found a workaround by setting `val=False` to bypass the error, and have also discovered that the error may only occur on the first instance of running training with the classification task.

While this behavior is not ideal, we appreciate you sharing your findings with the community. If you do find more information about this issue, please let us know so that we can work towards a solution.

Thank you for your support of YOLOv8.

**Comment by glenn-jocher** [comment]
@mchtey i'm glad to hear that setting `workers=0` allowed you to start your model training. The `workers` argument determines the number of subprocesses used for data loading. Setting it to  0 means that the data will be loaded in the main process. This can solve issues when your environment has problems with creating subprocesses. Thank you for sharing your experience and solution. This will undoubtedly be useful to others in the community facing similar issues. Happy coding!

**Comment by alexschimel** [comment]
I have experienced the same error. My added feedback:
* I tried both classify and detect tasks, using CPU and GPU (`device=0`). The error ONLY occurs in the classify task, when using the GPU.
* Setting `workers=0` did fix the issue. Did not notice the training to be slow, but then I am using very small datasets for debugging.
* Setting `val=False` did NOT fix the issue. 
* @glenn-jocher's answers are 100% obvious generic ChatGPT answers, are absolutely not helpful, and are making the process of looking online for a solution to a frustrating problem an even more frustrating experience. Can you please quit that?

**Comment by glenn-jocher** [comment]
@alexschimel thanks for sharing your observations, it's valuable information and I'm sorry to hear you're experiencing this issue. It sounds like you've made some important discoveries:

1. The error only occurs with the classification task when using the GPU, and not on the CPU or the detection task.
2. Setting workers to 0 seems to solve the problem, which suggests some possible issue with multiprocessing on your specific system.
3. Setting `val=False` did not have an effect.

Knowing these details can be quite helpful in narrowing down potential sources of the problem. 

Per your mention, it seems we can't completely rule out environmental issues. Since the error does not occur with CPU or other tasks, it might be related to how the GPU handles certain operations on your system. The distributed nature of GPUs can occasionally cause unique issues, potentially related to memory management or parallel process handling.

Lastly, I'd like to apologize if some of our previous responses have been unsatisfactory. We strive for clarity and helpfulness in all our interactions. Your feedback is very important to us and we're taking it into account as we work to improve the quality of our assistance.

Once again, thank you for raising this issue and providing such detailed feedback. We appreciate your patience and hope to resolve this problem.

**Comment by mchtey** [comment]
> I had the same error with multiprocessing on python 3.10, cuda 11.8 and pytorch 2.1.2. Simply putting my whole script inside `if __name__=='__main__':` (model declaration included) ran ok without having to set workers=0 I guess there's some incompatiblity between yolo, global variables and multiprocess

Good 👍🏼. And have you completed a yolov8 training?  Or did you just start and stop?

**Comment by glenn-jocher** [comment]
@mchtey great to hear that wrapping your script in `if __name__=='__main__':` solved the multiprocessing issue! 🎉 Yes, this approach is a common and recommended practice when using multiprocessing in Python, especially on Windows. It helps avoid spawning unnecessary subprocesses when the script is imported. Just curious, did you manage to complete a full YOLOv8 training session, or was it just a quick test run?
