### ISSUE TITLE
How can i disable the automatic log of MLFLOW??

### ISSUE THREAD

**Issue by edublanco** [ultralytics/ultralytics#2224]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello I am using yolov8 on azure ml with ml flow and I am making some experiments, for some reason mlflow automatically logs everything and in your references, I found this, is there a way to override the function so it does not do it automatically??:

def on_train_end(trainer):
    """ Called at end of train loop to log model artifact info."""
    if mlflow:
        root_dir = Path(__file__).resolve().parents[3]
        run.log_artifact(trainer.last)
        run.log_artifact(trainer.best)
        run.pyfunc.log_model(artifact_path=experiment_name,
                             code_path=[str(root_dir)],
                             artifacts={'model_path': str(trainer.save_dir)},
                             python_model=run.pyfunc.PythonModel())

### Additional

you should make this an option

**Comment by glenn-jocher** [comment]
Hello @edublanco, thanks for reaching out! 

It seems that you are experiencing a behavior of mlflow which automatically logs everything. 

In the provided code snippet, `on_train_end` function is called at the end of the training loop to log important information about the trained model in mlflow. 

To override this behavior and not log automatically, you can try removing or commenting out the lines related to mlflow in the provided function. See example below: 

```python
def on_train_end(trainer):
    """ Called at end of train loop to log model artifact info."""
    # if mlflow:
    #    root_dir = Path(__file__).resolve().parents[3]
    #    run.log_artifact(trainer.last)
    #    run.log_artifact(trainer.best)
    #    run.pyfunc.log_model(artifact_path=experiment_name,
    #                         code_path=[str(root_dir)],
    #                         artifacts={'model_path': str(trainer.save_dir)},
    #                         python_model=run.pyfunc.PythonModel())
```

I hope this helps! Let me know if there's anything else you need.

**Comment by edublanco** [comment]
Hello @glenn-jocher thank you for the prompt answer, now my doubt is in how I can access that method, override it, and apply that change?

**Comment by glenn-jocher** [comment]
Hello @edublanco, to override the `on_train_end` function you can create a new function that shares the same name, then make the desired changes to the function accordingly. Then, import the module with your custom function and it will be used instead of the original function. 

The original function defined in the YOLOv8 repository may be in a file like `train.py`, so you can create a similarly-named file like `train_custom.py` in which you define your custom `on_train_end` function. Then in the file where you are training with YOLOv8, you can use `import train_custom as train` to use the custom function instead of the default one. 

This way, when training with YOLOv8, it will call your custom function to log artifacts instead of the default one in mlflow.

**Comment by edublanco** [comment]
Hi @glenn-jocher, so the function i am trying to override is in  .../yolo/utils/callbacks/mlflow.py that is used by  .../yolo/engine/trainer.py that is used by .../yolo/engine/model.py, so if I do what you said, I would have to override does 3 files right? Is there a more direct way ?

**Comment by edublanco** [comment]
on the documentation i found this https://docs.ultralytics.com/usage/engine/#customizing-the-detectiontrainer, but I don't really understand how can I apply  it in this situation

**Comment by pderrenger** [comment]
@edublanco the link you found provides a way to customize the `DetectionTrainer` class, which could help in your situation. Here's how you might apply it:

1. Create a new Python file, let's call it `custom_trainer.py`, and define a custom `DetectionTrainer` class in it.

2. In the custom `DetectionTrainer` class, you can override the `on_train_end` method to change its behavior as needed, for example, by not logging to mlflow.

3. When you are running your training script, import your `custom_trainer.py` and use the custom `DetectionTrainer` instead of the default one.

By doing this, you can directly override the behavior of the `DetectionTrainer` without altering the original files, and without the need to override multiple files. This should provide a more direct and targeted approach to apply the desired changes.

**Comment by glenn-jocher** [comment]
@pderrenger, you're on the right track with the documentation. To apply the customization:

1. Inherit from the `DetectionTrainer` class in your `custom_trainer.py`.
2. Override the `on_train_end` method to exclude the mlflow logging code.
3. Use your custom trainer class when setting up your training pipeline.

This way, you only need to modify your custom trainer class without changing the original YOLOv8 files. Your custom class will be used during training, and the mlflow logging will be disabled as per your override.

**Comment by fpirovan** [comment]
using this context manager works good for me:

```
@contextmanager
def disable_module(module_name):
    """
    A context manager to temporarily disable a specific module.
    """

    class DisabledModuleImporter:
        def find_spec(self, fullname, path, target=None):
            if fullname == module_name:
                raise ImportError(f"Import of module '{module_name}' is disabled.")
            return None  # Use default importer for other modules

    # Backup the current sys.meta_path
    original_meta_path = list(sys.meta_path)

    # Insert the custom importer at the beginning
    sys.meta_path.insert(0, DisabledModuleImporter())

    # Remove the module from sys.modules if it's already imported
    if module_name in sys.modules:
        del sys.modules[module_name]

    try:
        yield
    finally:
        # Restore the original sys.meta_path
        sys.meta_path = original_meta_path

        # Optionally, you can also remove the module from sys.modules again
        # if you want to ensure it's re-imported fresh after the context
        if module_name in sys.modules:
            del sys.modules[module_name]
```

like this


```
with disable_module("mlflow"):
    yolo = YOLO(yolo_model)
    yolo.train(
        project=f"{project_directory}/{label_folder}",
        device="cuda" if torch.cuda.is_available() else "cpu",
        single_cls=True if label_folder == "localization" else False,
        **yolo_params,
    )
```
