### ISSUE TITLE
How can I change my total epochs count when resuming training?

### ISSUE THREAD

**Issue by Camerabiologist** [ultralytics/ultralytics#2230]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi!

Let's say I started a model training of 50 epochs and manually stopped it at epoch 16. I now want to resume training using the resume=True argument, but change the total number of epochs to train the model from 50 to 100. Is this possible and if so, how can I do that?

Thank you!

**Comment by glenn-jocher** [comment]
@Camerabiologist hello, 

Yes, it is possible to resume the incomplete training of a model and continue it to a desired number of epochs using the 'resume=True' argument, as you mentioned. Once you resume the training, the model will continue to learn from the last saved checkpoint. To change the number of total epochs for the resumed training, you can simply modify the 'epochs' parameter in the training script or command. Please note that if you change the number of epochs, it may take longer or shorter time to train, depending on various factors such as batch size, learning rate, and complexity of the model. If you need more information, please refer to the Ultralytics YOLOv8 documentation at https://docs.ultralytics.com.

**Comment by Linkanblomman** [comment]
@glenn-jocher, I recently tried to resume an incomplete model training (interrupted at the 70th epoch) using the 'resume=True' argument, and I wanted to change the total number of epochs from the original setting of 300 to 150. However, I faced difficulties when attempting to override the 'epochs' parameter in the training script and command. Could you please provide an example of how to properly resume training and override a parameter, such as epochs? Your assistance would be greatly appreciated.

**Comment by glenn-jocher** [comment]
@Linkanblomman hello,

I'm sorry to hear that you faced difficulties when trying to override the 'epochs' parameter while resuming an incomplete model training. You can try the following steps to properly resume the training and change the value of the 'epochs' parameter:

1. In the training script, set the initial value of the 'epochs' parameter to the total number of epochs you wish to train the model for (in your case, set it to 150).
2. When resuming the training using the 'resume=True' argument, the model will load the latest saved checkpoint and continue from where it was interrupted. 
3. If you then run the training script or command, the model will train for the remaining number of epochs until the total number of epochs is reached (in your case, 150 epochs in total).
4. Once training is completed, you may evaluate the trained model and obtain the desired results.

I hope this information is helpful. If you have any further questions, please let me know.

**Comment by zacitycar** [comment]
Hello dear @glenn-jocher   just as u specified above, i changed the number of epoch value: epoch=600 with resume= True. This resumes training but in console log shows the previous number of epochs (300) v/s the epoch running ( Epoch  240/300  whereas it should be 240/600 now). My ref code lines are as follows:

model.train(data="coco.yaml", epochs=300, task='detect', batch=32)  # train the model
model.train(data="coco.yaml", epochs=600, resume=True)

**Comment by yekim102** [comment]
@glenn-jocher Hi,

I attempted to resume training the YOLO model from epoch 50 of 70 by using the command "yolo detect train resume model=..../train16/weights/last.pt epochs=100". The training process completed at epoch 70 of 70.

When I tried to resume the training process again with the same command after its completion, the model did not pick up where it left off at the end of the last epoch. Instead, it initiated a new training process, creating a train17 folder.

**Comment by glenn-jocher** [comment]
Hi @yekim102,

I see you're trying to resume your training and are encountering an issue. When resuming training in YOLOv8, the intended behavior is to pick up from the last saved checkpoint and continue until the newly specified number of epochs. It appears from your description that instead of continuing from the previous state that the model is restarting from the beginning, which is not the expected behavior.

When you resume training, YOLOv8 will automatically create a new training folder (like 'train17'). This is to ensure that the training outputs from different runs are held separately. I believe it's important to clarify that the new folder doesn't necessarily mean a new training process from the beginning.

In your specific case, you mentioned continuing training from epoch 50 to epoch 100 but it stopped at epoch 70. The console logs should display something like "Resuming training at epoch 50". It's quite possible that some misalignment between your specified epochs and the continuation of training is causing this issue.

Without knowing more details of your situation, it's difficult to say for sure what's happening. However, it's worth noting that the epochs parameter defines the total number of epochs to train for, rather than defining an extension to the currently completed epochs.

If you face this issue, it's advisable to try re-running your training command and ensure your weights file path is accurate and the specified number of epochs is correctly set.

Hope this helps and gives some clarity. If the issue persists or you have more questions, feel free to follow up.

**Comment by yekim102** [comment]
@glenn-jocher Hi,
Thanks for the reply. 
I'm not seeing anything like "Resuming training at epoch 50" on the console. Also, newly created args.yaml file has previous epochs (which I set to 70 previously and 200 when resuming) and resume=false.

I tried updating to new version but it gives "SyntaxError: 'v5loader' is not a valid YOLO argument." message so I went back to previous version again.

A thing to notice is that if I resume training from unfinished training session (50 / 70 epochs), it does not create a new training folder, but it resumes from the same training folder. I am not sure if this is the expected behavior.

**Comment by glenn-jocher** [comment]
Hi @yekim102,

Thanks for your response.

The behavior you described is somewhat unusual. Normally, when you resume training with the 'resume=True' argument, the model should pick up from the last saved checkpoint and continue the training till the newly specified number of epochs. This process often reflects in the console prints, like "Resuming training at epoch 50". So, if this message is not displayed, your training might not be resuming as expected.

The new training session creating a new folder (like 'train17') is the expected behavior. Each run, even when resuming, will generate a new 'run/train' directory to keep outputs separate and organized. However, if your training is resuming in the same folder, this might be an indication of a problem.

The issue might lie in the 'args.yaml' file that holds the configuration for your training run. The epochs should reflect the new total epochs you want to train, not the previously set value and resume should be true.

Regarding the "SyntaxError: 'v5loader'", it seems like there might be some inconsistencies or conflicts in your setup or in the exact command you're running.

In order to troubleshoot effectively, you may want to check the following:

- Verify the path to the weights file.
- Try running the command again, ensuring that the --epochs and --resume arguments are correctly specified.
- Make sure the args.yaml file in the respective 'runs/trainX' folder correctly reflects the new epoch value, and that 'resume' is set to 'True'.
- Consider cleaning your environment and reinstalling YOLOv8, in case there are any conflicts or issues due to versioning.

Sorry for the inconvenience, and thank you for your patience.

**Comment by Atharva-Madiwale** [comment]
According to the current configurations, the learning rate is 0.1. I am using the following command: 

model = YOLO("yolov8n-seg.pt")  # load a pretrained model (recommended for training)
#model = YOLO("best.pt")

# Use the model
results = model.train(data="custom_data.yaml", epochs=175, workers=2, batch=8,imgsz=640) 

I want to update the learning rate to 0.02. How can I do that ? I'm unable to update the learning rate.

**Comment by pderrenger** [comment]
@Atharva-Madiwale to update the learning rate during training in YOLOv8, you can achieve this by modifying the training script as per the following steps:

1. Update the learning rate in the training script where the model is defined and the training starts. When initializing the YOLO model for training, you can specify the learning rate using the "lr" parameter, like so:
   ```python
   model = Model('yolov8n-seg.pt', lr=0.02)
   ```

2. After updating the learning rate in the training script, re-run the training command. The YOLOv8 model will then use the newly specified learning rate during the training process.

By following these steps, you should be able to update the learning rate to 0.02 for your training.

Feel free to reach out if you encounter any further difficulties or have additional questions.

**Comment by GabrieldeBlois** [comment]
Hello, I am fine tuning a yolo11 model with the visDrone dataset. During training, I would like to unfreeze iteratively the weights. Like doing 10 epochs with model freeze=23, 10 epochs with freeze=19, lr=1e-4, and so on.
I tried to launch a first training with the python API and then resume but the epochs argument cannot be changed as soon as I want to use the hub. Somehow the arguments passed to the train function of the model are ignored if the model has been loaded from the hub. Do you have a workaround ?
