### ISSUE TITLE
Yolov8 tflite python output is not matching with tflite cpp output for float32 models

### ISSUE THREAD

**Issue by ajithkumarmcw** [ultralytics/ultralytics#2260]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am using Yolov8 model, In python tflite model is predicting correctly but same model when we use it in cpp with below script its not able to give same outputtensor as like python's output
because of this problem models output scores, labels are going to 10000, 20000 like that. Kindly help us to sort this issue.

These are the codes which we are using 
https://github.com/muhammedakyuzlu/yolov5-tflite-cpp/blob/main/src/main.cpp
https://github.com/craft-zhang/tensorflow-lite-cpp-examples/blob/main/yolov5.cc
https://github.com/craft-zhang/tensorflow-lite-cpp-examples/blob/main/yolov5.h

tf version -> tensorflow==2.4.2

**Comment by glenn-jocher** [comment]
Hello @ajithkumarmcw and thank you for your question regarding YOLOv8. 

Since you are experiencing an issue with a customized version of the YOLOv8 model integrated with a C++ application, it's difficult for us to provide you with specific guidance without additional information on the details of the error message or the particular environment you are working on.

We recommend that you take a look at the TensorFlow Lite documentation for C++ and make sure that you have correctly integrated your model with your application. Additionally, review your  C++ script and ensure that the input and output tensors of your model are being used correctly. 

If the issue persists, please provide us with more specific details on the error message and/or the environment you are working in so that we can better assist you in debugging the issue.

**Comment by ajithkumarmcw** [comment]
problem was in nms function that we were using

**Comment by glenn-jocher** [comment]
Hello @ajithkumarmcw, thank you for the information you provided from your YOLOv8 C++ application inference output.

From the inference output you shared, it appears that the issue is with the non-maximal suppression (nms) function that you are using. The issue may not be with the model, but rather with how the output of the model is being processed in your C++ application.

We recommend validating the nms function that you are using. Ensure that the function is both correct and compatible with the output format of the model you are using. You may also want to double-check the input and output tensor shapes of the model and make sure that they match what is expected by your C++ application.

If you are still experiencing issues after validating the nms function, please let us know and we can further investigate the issue.

**Comment by AD-lite24** [comment]
Hi I am using the same CV2 NMS function in this example for c++ inference https://github.com/ultralytics/ultralytics/blob/main/examples/YOLOv8-CPP-Inference/inference.cpp but all my results are still wrong. Moreover not a single bbox has the correct class predicted for it.

**Comment by glenn-jocher** [comment]
Hi @AD-lite24, please ensure you are using the latest version of the Ultralytics package. If the issue persists, double-check the input and output tensor shapes and verify that the NMS function is correctly implemented and compatible with your model's output.

**Comment by AD-lite24** [comment]
Hi @glenn-jocher I am using the c++ api for inferencing via tflite. I implemented this https://github.com/ultralytics/ultralytics/blob/main/examples/YOLOv8-CPP-Inference/inference.cpp inference for tflite. My initial bboxes are somewhat accurate (though not close to accuracy obtained inferencing from onnx). Since I am following the official implementation, I believe my my shapes are correct. I cross verified by running the onnx model and everything seems to be in order.  Aside from this the NMS function (the cv dnn one used in the official example) always returns only one bounding box regardless of how many there actually are supposed to be. 

I have followed the official implementation to be best of my knowledge and thus I am unable to explain the incorrect results

**Comment by AD-lite24** [comment]
I have found the reason why the NMS is not working correct. Getting the output tensor after performing the relevant reshaping and transposing gets us a shape of (8400, 84) which is consistent with the outputs. Now among the 84 the first four are box coordinates (x, y, w, h) while the rest are class scores. The class scores seem _fine_ though not very good when compared to the onnx runtime. The real issue is the box coordinates. 

In tflite my box coordinates take up the values

```
data idx 0: 0.00505153
data idx 1: 0.0262354
data idx 2: 0.0120835
data idx 3: 0.0546932
```

while in onnx they take up the values
```
data idx 0: 3.401
data idx 1: 6.82366
data idx 2: 7.008
data idx 3: 13.7652
```
Granted these are not the same boxes but the range of values it can take up is wildly different which is potentially messing up with the NMS. I have no idea why this is happening though and how it can be fixed.

**Comment by glenn-jocher** [comment]
Thank you for the detailed analysis. It seems the issue might be related to how the TFLite C++ API handles the model inference compared to the Python API. Given that your model and code are consistent across other implementations, this discrepancy could indeed be due to the TFLite C++ API. I recommend verifying the preprocessing and postprocessing steps in your C++ code to ensure they match the Python implementation exactly. If the issue persists, consider reaching out to the TensorFlow Lite community for further insights.
