### ISSUE TITLE
Yolov8 error while training on gpu

### ISSUE THREAD

**Issue by MuhammadSibtain5099** [ultralytics/ultralytics#227]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

-- device=0 is not working to train on GPU
error: unrecognized arguments: --device 0
![image](https://user-images.githubusercontent.com/62267102/211725485-b34fc6b9-3451-4481-82d1-ddda64edf316.png)

**Comment by Laughing-q** [comment]
@MuhammadSibtain5099 please use device=0, like other args, arg=value. More details please read our Docs. :)

**Comment by MuhammadSibtain5099** [comment]
@Laughing-q see the first line of the screenshot. I am already using device=0. Is there any mistake?

**Comment by Laughing-q** [comment]
@MuhammadSibtain5099 ohh it looks your cuda device is unavailable, can you check `torch.cuda.is_availabel()`?

**Comment by Laughing-q** [comment]
@AyushExel we need update the assert msg.

**Comment by MuhammadSibtain5099** [comment]
@Laughing-q  No. it is returning False 
maybe there is a version compatibility issue. 
CUDA Version: 11.6
Python 3.8.15
pytorch 1.13.1+cpu
![image](https://user-images.githubusercontent.com/62267102/211729290-c240d574-b11c-4486-b126-b1d823cd4687.png)

**Comment by Laughing-q** [comment]
@MuhammadSibtain5099 your torch is cpu version and you have to install torch corresponding to your cuda version then you're free to use your GPU for training.

**Comment by HarishGuragol** [comment]
Try to install ` sudo apt-install nvidia-cudann` in linux and install the cudann drivers which will enable your gpu and then u can start the training

**Comment by creativesh** [comment]
@Laughing-q

hi 

how can I use gpu:1 for training? gpu: 0 is busy. no matter how I set the device, the train is running on gpu:0 leading to memory error

**Comment by glenn-jocher** [comment]
@creativesh hi,

To use a different GPU for training in YOLOv8, you need to specify the GPU device index in the `--device` argument. The default value is `--device=0`, which corresponds to GPU:0. If you want to use GPU:1, you can set `--device=1`.

However, if GPU:0 is already busy, changing the device index alone may not solve the memory error issue. The error message indicates that CUDA is running out of memory on GPU:0. You may need to consider reducing the batch size or model size to fit the available memory on GPU:0. Alternatively, you can try optimizing your code or freeing up memory on GPU:0 to make more memory available.

Please note that YOLOv8 itself does not have specific functionality for automatically balancing the memory usage across multiple GPUs. It's up to the user to manage the GPU resources and ensure the models and data fit within the available memory.

I hope this helps! Let me know if you have any further questions.

**Comment by ChearLX** [comment]
![gpu not found](https://github.com/ultralytics/ultralytics/assets/87294236/be06db62-80dc-4d4f-9d60-8b423d043333)
@glenn-jocher Hi,
I tried all the steps checking my GPU and it was able to detect it.
But once I ran it, it failed to use it for the code. Is there any other way to run it with GPU?

**Comment by glenn-jocher** [comment]
@ChearLX hello,

If your machine correctly identifies the GPU but your code fails to utilize it, there could be multiple potential reasons. Here are a few possibilities:

1. **CUDA Compatibility**: Your PyTorch and CUDA versions might not be compatible. You may need to ensure that your PyTorch version is suitable for the CUDA version installed on your machine.

2. **Improper PyTorch Installation**: Your PyTorch might have been installed with the CPU-only flag. Please check the PyTorch version you have installed and ensure it supports GPU usage.

3. **Device Specification**: In the training command you're using, make sure that the device argument is correctly pointing to your GPU. The default value can sometimes point to the CPU instead of the GPU.

4. **Insufficient GPU Memory**: Depending on the size of your model and data, there might not be enough memory on the GPU to hold everything, which could cause the code to fail when trying to use the GPU. Monitor your GPU memory usage to see if this might be the case.

Please check these potential issue areas and let us know if you're still facing issues.

Best,
Glenn Jocher

**Comment by ChearLX** [comment]
@glenn-jocher Hi,
I did check the steps and also reinstall all the requirements but it's still facing the same issues.
Please find the following image for environment variables, GPU usage and others that might be helpful for your side to troubleshoot.
![Uploading Environment variables.png…]()

**Comment by ChearLX** [comment]
![GPU usage](https://github.com/ultralytics/ultralytics/assets/87294236/8f04f2c0-222e-4f39-9aa9-623f55119240)
![Nvida-smi](https://github.com/ultralytics/ultralytics/assets/87294236/1e940d84-ae73-48ec-af77-b8d88a71a9b2)
![requirement file](https://github.com/ultralytics/ultralytics/assets/87294236/5e74d0f4-d8e8-45c3-a174-63ad0ffa1c3f)
![torch-2 0 1+cpu](https://github.com/ultralytics/ultralytics/assets/87294236/7985fbf4-5027-4625-a0b7-eb8434b7f02a)

**Comment by glenn-jocher** [comment]
@ChearLX, 

Looking at your screenshots, I suspect the issue lies with your PyTorch installation. From your last screenshot, it looks like you have PyTorch installed for CPU (`torch-2.0.1+cpu`). In order to leverage GPU acceleration with PyTorch, you'll need to install the version that corresponds to your CUDA version - hence in your case, you might want to install `torch` version supporting `CUDA 10.2`.

Please uninstall your current version and then reinstall PyTorch using the right CUDA version. Once done, kindly check the output of `torch.cuda.is_available()` - it should return `True` if everything is correctly set up.

Let me know if this resolves your issue. If not, please provide the new error messages or issues you're facing.

Best,
Glenn Jocher

**Comment by BarsikArsik** [comment]
Hello, I'm very bad at everything related to programming and I'm trying to solve my problem using AI,
I can’t run training on the GPU.
Version CUDA 12.4
![1](https://github.com/ultralytics/ultralytics/assets/101796859/92049a29-8af8-40c4-a2b5-625ba38b1926)

PyTorch 
![2](https://github.com/ultralytics/ultralytics/assets/101796859/21e51943-d549-4d71-82ca-8dc0e42e5c5e)

version 12.1
Unfortunately I couldn't find how to install 12.4

At the same time, where it works and determines the G
![3](https://github.com/ultralytics/ultralytics/assets/101796859/0729659f-bebe-4f68-abaf-7d0271872674)
PU as accessible.
![4](https://github.com/ultralytics/ultralytics/assets/101796859/0a9eb418-c31c-4da3-9c5d-0f4c014c7773)


but if you run image analysis with parameter =0, it produces an error.

**Comment by glenn-jocher** [comment]
@BarsikArsik hello! No worries, we all start somewhere, and it's great you're diving into AI programming. 🌟 From what you've shared, it looks like there might be a mismatch between your CUDA version and the PyTorch version. 

As of my last check, PyTorch doesn't have a release for CUDA 12.4 yet. The error when setting `parameter=0` might be because PyTorch isn't recognizing your GPU due to this version discrepancy. For CUDA 12, ensuring you have a compatible PyTorch version is key. 

Could you try installing PyTorch specifically for your CUDA version (if you're using CUDA 12.1 as mentioned)? Here's a generic command, but please adjust for the exact versions:

```bash
pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu121
```

If CUDA 12.4 is a must, you might need to keep an eye on the PyTorch [official site](https://pytorch.org/) or GitHub for updates on support for this version.

For running inference with GPU, ensuring your `device` parameter is correctly set to use the GPU (e.g., `device='cuda:0'` if your GPU is recognized as the first device) can usually resolve such issues.

Feel free to reach back if you're still encountering the error. Happy coding! 🚀

**Comment by BarsikArsik** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/101796859/75f87ed2-4b0c-486c-8c19-2e1f340b1668)
Thanks for the answer. I was able to install KUDA 12.1, but the error still persists when I try to transfer ML to the GPU. at the same time, everything continues to work without problems on the CPU (just slow)

**Comment by glenn-jocher** [comment]
Hey 😊! Great to hear you managed to install CUDA 12.1. To resolve the GPU transfer issue, ensure PyTorch links to the correct CUDA version. You can verify this in Python:

```python
import torch
print(torch.__version__)
print(torch.cuda.is_available())
```

If `torch.cuda.is_available()` returns `False`, there might be an issue with PyTorch recognizing your CUDA installation. Reinstalling PyTorch with explicit CUDA version might help:

```bash
pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu121
```

Remember to restart your environment after reinstalling. Let's keep things moving swiftly, even on the GPU side of things! 🚀

**Comment by BarsikArsik** [comment]
it's okay(
![image](https://github.com/ultralytics/ultralytics/assets/101796859/dede5861-8320-4532-acd0-963c5b792733)

**Comment by glenn-jocher** [comment]
Hey there! It seems like there's an issue, but don't worry, we're here to help! If you're experiencing trouble with GPU utilization, let's ensure PyTorch is correctly recognizing your CUDA setup:

Firstly, check if PyTorch can see your GPU: 

```python
import torch
print(torch.cuda.is_available())
```

If it returns `False`, you might need to reinstall PyTorch to ensure it's linked to your CUDA version. Running this should help:

```bash
pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu121
```

Change `cu121` to match your CUDA version. Let's give that a try! 🚀
