### ISSUE TITLE
Output mask size is different from original image size 

### ISSUE THREAD

**Issue by Arshadoid** [ultralytics/ultralytics#2272]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Version: 8.0.56

Original image size: 640x360
Training imgz=640

I was expecting to get mask size same as the input image size, but when I run a test image through prediction I get a different size as below:

input:
`(results[1].masks.masks).size()`

output:
`torch.Size([6, 384, 640])`

What can be a reason for this? 

P.S. I can provide additional information if needed.

**Comment by glenn-jocher** [comment]
@Arshadoid thanks for reaching out. The reason for this is that during inference, YOLOv8 downscales the input image for better performance. This downscaled version is then used for object detection and mask prediction. The size of the predicted mask is in accordance with this downscaled version of the image and not the original image. Hope this clarifies your doubt. Please let me know if you have any further questions.

**Comment by Arshadoid** [comment]
> 

@glenn-jocher  thanks for the reply. In this case, is there any way of getting predicted mask with the shape of the original image?

**Comment by glenn-jocher** [comment]
@Arshadoid yes, mask outlines are available in image coordinates. See https://docs.ultralytics.com/modes/predict in the Masks section.

**Comment by Arshadoid** [comment]
@glenn-jocher thank you a lot for your quick response. Seems like the version I had didn't have the option of getting the coordinates... 
One more last question on this. Considering that inference gives an output with different size, I assume xy is based on that output size, right? So it will be wrong if I apply it to the original image. To convert the mask back to the original size should we use xyn w/r to the original image dimensions?

**Comment by glenn-jocher** [comment]
@Arshadoid you're welcome! Yes, the bbox/mask outputs are in the coordinate system of the downsampled image. In order to position the bounding boxes with respect to the original image, you need to scale them up by the output stride mentioned in the model architecture diagram. You can find the formula to do this in the YOLOv8 documentation under "Inference Output Details" section.

Similarly, to recover the original size of the predicted mask, you can resize the mask back to the size of the original image using any standard image resizing method like bilinear or nearest neighbor interpolation. Basically, you need to scale the mask up by the output stride of the model architecture and then resize it to the dimensions of the original image.

Hope this answers your question. Let me know if you have any more doubts.

**Comment by mohandeeprdori** [comment]
@bs42240720 Did you find how to scale up the mask using the stride ?

**Comment by jingobelll** [comment]
# Run inference with high-resolution masks
results = model.predict('image.jpg', retina_masks=True)

retina_masks=True 
return an original image size mask
