### ISSUE TITLE
Generate training plots on headless display/Segment out the image boundaries

### ISSUE THREAD

**Issue by nanirudh85** [ultralytics/ultralytics#2291]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

1. In the command set to visualise the segmented image, how do I crop the segmented region alone and not as a box?
2. I am running the code on a cluster with CPU nodes and they are set to work with headless displays. At the end of the training (for either segmentation/detection), the final set of plots need a QT or TKK display. Can these plots be written as .pdf or png without the need for a graphical display on the screen. 

### Use case

1. it would allow the exact computation of the segmented area
2. It would be useful for those running jobs on the cluster.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@nanirudh85 hi there! Thanks for reaching out. 

To segment out the image boundaries without drawing bounding boxes, you can use the segmentation mode instead of the detection mode when making predictions. This will generate pixel-wise masks for each detected object, allowing you to precisely compute the segmented area.

Also, to generate training plots without the need for a graphical display, you can use the `--plot_save` flag during training to save the plots as .pdf or .png files directly without requiring a display. This is particularly useful for running jobs on headless CPU nodes.

I hope this helps! Let me know if you have any other questions or need further assistance. Good luck with your work on the cluster!
