### ISSUE TITLE
Any modification made in plotting.py doesn't work

### ISSUE THREAD

**Issue by celiaqt** [ultralytics/ultralytics#2311]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I tried to delete the predicted labels when I execute the predict mode with the detect task on my own dataset, but any modification doesn't work at all...

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@celiaqt hello! Thank you for reaching out. We appreciate any contributions to the YOLOv8 repository. 

Regarding the issue you described, it sounds like you are having trouble deleting the predicted labels when running the predict mode with the detect task on your own dataset. 

To better understand the problem, could you give us more information about the modifications you tried and what exactly didn't work? Without a minimal reproducible example, it's difficult to provide an accurate solution.

But don't worry, we are happy to help. If you can provide more details or a minimal reproducible example, we can begin to investigate and work towards a solution. 

Again, thank you for your interest in contributing to YOLOv8!

**Comment by celiaqt** [comment]
For context: I have cloned the repository, I'm running the train and predict command on the CLI. I'm directly modifying the `/ultralytics/yolo/utils/plotting.py` file to prevent it from drawing the labels and confidence (just keep the box outline) but it seems to have no effect. 
This is the modification I did (deleted the lines adding the annotated labels):
``` 
    def box_label(self, box, label='', color=(128, 128, 128), txt_color=(255, 255, 255)):
        """Add one xyxy box to image with label."""
        if isinstance(box, torch.Tensor):
            box = box.tolist()
        if self.pil or not is_ascii(label):
            self.draw.rectangle(box, width=self.lw, outline=color)  # box
            if label:
                if self.pil_9_2_0_check:
                    _, _, w, h = self.font.getbbox(label)  # text width, height (New)
                else:
                    w, h = self.font.getsize(label)  # text width, height (Old, deprecated in 9.2.0)
                outside = box[1] - h >= 0  # label fits outside box
                self.draw.rectangle(
                    (box[0], box[1] - h if outside else box[1], box[0] + w + 1,
                     box[1] + 1 if outside else box[1] + h + 1),
                    fill=color,
                )
                # self.draw.text((box[0], box[1]), label, fill=txt_color, font=self.font, anchor='ls')  # for PIL>8.0
        else:  # cv2
            p1, p2 = (int(box[0]), int(box[1])), (int(box[2]), int(box[3]))
            cv2.rectangle(self.im, p1, p2, color, thickness=self.lw, lineType=cv2.LINE_AA)
            if label:
                tf = max(self.lw - 1, 1)  # font thickness
                w, h = cv2.getTextSize(label, 0, fontScale=self.lw / 3, thickness=tf)[0]  # text width, height
                outside = p1[1] - h >= 3
                p2 = p1[0] + w, p1[1] - h - 3 if outside else p1[1] + h + 3
                cv2.rectangle(self.im, p1, p2, color, -1, cv2.LINE_AA)  # filled



```
Despite doing this the outputs stills draws everything.

**Comment by pderrenger** [comment]
@celiaqt Thanks for providing the code modification. The changes you made in `plotting.py` appear correct for removing the annotated labels from the bounding boxes. However, to ensure the changes take effect, you should ensure that after making the modifications, you run the `train` command to retrain the model and then the `predict` command to see the effect of the changes in the prediction output.

Regarding the possibility of other scripts affecting the output, the changes you made directly in `plotting.py` should take precedence in the visualization process. There shouldn't be another script overriding these changes unless you have multiple versions of YOLOv8 or specific customization in your environment.

If you have already retrained the model and run the predict command again but still see the labels, please let us know so that we can further investigate the issue and help you resolve it. If there are any other factors or steps involved in your workflow, providing those details can also assist us in identifying the root cause.

We're here to assist you, so feel free to share more information or ask further questions. Thank you for your patience and collaboration!
