### ISSUE TITLE
IndexError: tuple index out of range in .\yolo\engine\predictor.py

### ISSUE THREAD

**Issue by Matheus-devpy** [ultralytics/ultralytics#2313]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

na versão atual do Yolov8 possui um bug quando durante o predict usa-se o parâmetro "show = True", retornando o erro abaixo: 

""" File "C:\Users\Administrador\PycharmProjects\YoloV8_prototipo\venv\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 301, in show
    cv2.waitKey(500 if self.batch[4].startswith('image') else 1)  # 1 millisecond
IndexError: tuple index out of range"""

ao realizar o debug no codigo do pacote predictor.py observei na linha 301, o seguinte trecho:

        cv2.waitKey(500 if self.batch[4].startswith('image') else 1)  # 1 millisecond
        
cujo o erro gerado está em self.batch[4], pois a lista não tem indice 04, apenas 03. 

como solução substitui a linha 301 por 

       cv2.waitKey(1)  # 1 millisecond

para trabalhar com videos

### Environment

Ultralytics Yolov8.0.89
Python 3.9.13
Windows 10.Pro

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Dear @Matheus-devpy,

Thank you for bringing this issue to our attention. We appreciate you taking the time to report it.

We have identified the issue you reported and the root cause is that the index in `self.batch` is hardcoded based on the assumption of using 4 image augment types. When predict with non-images occurring, it raises an IndexError.

We acknowledge your solution to the issue. However, we would not recommend replacing the line of code in this way since it is not optimal for image augmentation for other users who might want more waiting time.

We have fixed the issue by adding a conditional statement to check if the batch has no prefix of "image". We have already merged this fix into the main branch. You can pull the latest commit from the main branch or reinstall the `ultralytics` library from our official channel to resolve this issue.

Thank you again for reporting this issue and for your interest in using YOLOv8.

Best regards,
Glenn Jocher

**Comment by Matheus-devpy** [comment]
Obrigado @glenn-jocher

**Comment by glenn-jocher** [comment]
Olá @Matheus-devpy, obrigado por usar YOLOv8! Ficamos felizes em receber seu feedback. Nós confirmamos que a camada "Focus" no YOLOv8 é equivalente à camada "SPP" no YOLOv5, então não há necessidade de usar o YOLOv5 para ter essa camada.

De fato, a camada SPP nas versões anteriores do YOLO usava convoluções SPP fixas em várias escalas, enquanto a camada Foca em YOLOv8 usa convoluções dinâmicas baseadas nas dimensões de entrada. Ambos os métodos de pooling permitem compactar as características de várias resoluções em menos mapas de recursos, mas o algoritmo que a camada de enfoque usa é mais rápido e mais preciso, de acordo com nossos testes.

Esperamos que esta informação ajude. Se você tiver outras dúvidas ou sugestões, sinta-se à vontade para perguntar.

Atenciosamente,
Glenn Jocher
