### ISSUE TITLE
Single class training, error & how to

### ISSUE THREAD

**Issue by sjgv** [ultralytics/ultralytics#2331]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I am trying to train on a single class, I have a dataset set up with images containing it and labels in YOLO format. 

when I run the trainer like 

`model.train(data="my-data.yaml", epochs = 1, single_cls=True, device='cpu')`

I get this error
```
\yolo8-ultralytics\ultralytics\yolo\utils\tal.py", line 129, in get_box_metrics
bbox_scores = pd_scores[ind[0], :, ind[1]]  # b, max_num_obj, h*w
                  ~~~~~~~~~^^^^^^^^^^^^^^^^^^^
IndexError: index 1 is out of bounds for dimension 1 with size 1
```

How can I solve this in a correct way, how can I train on a single class? 

thanks in advance! 

EDITED: 

I found my issue and the solution. 

So to train a single class, not only does one have to specify that flag `single_cls` but also under dataloaders in the `v5loader.py` file one mustt change line 538 `include_class = []` to have the class number that MATCHES THE NUMERICAL LABEL (you might think this just refers tto the index of the list where you specify the name of the label, but no). 

So even though I had `include_class = [0]` I was having issues until I realized that my label files were NOT zero indexed (label for one class was 1 instead of 0). 

I went ahead and changed all my label files to use 0 (for single class)
0 0.42 0.2 0.2 0.28  <---- now they look like this 

and that fixed it! 

### Additional
 in my `data.yaml` file I have:

nc: 1
names: ['foobar']

**Comment by glenn-jocher** [comment]
@sjgv hi there, 

Glad to hear that you were able to resolve the issue you were having training on a single class. 

For everyone else looking to train on a single class: 

In order to train on a single class with YOLOv8, you should specify the `single_cls` flag, like you did, when invoking the `train` function. However, you'll also need to make sure that your label file(s) are numbered correctly (start at 0), and that you specify the correct numerical label for the class you want to detect, in the `include_class` list in the `v5loader.py` file. 

If you're still having trouble with training on a single class, please provide more details about the error you're encountering, and we'll do our best to assist you. 

Happy training!
