### ISSUE TITLE
How to Save Count of Classes found in an image that is processed

### ISSUE THREAD

**Issue by shubham001official** [ultralytics/ultralytics#2364]
i'm working on vehicle detection project. i want to save the count of classes found in the particular image in a text file. each image should have separate txt file containing data like:
car: 15
bike: 12

how can i do this in YOLO V8

**Comment by glenn-jocher** [comment]
@shubham001official hi, to save the count of classes found in a particular image in a text file, you can use the `yolo.run(img)` method to detect objects in the image, then access the returned `Tensor` objects that report the predicted `class_id`, `class_name`, and the coordinates of the bounding box of each object. In order to output the counts to a txt file, you could create a dictionary to store the counts for each class and then iterate over the detected objects, incrementing the count for each class in the dictionary, before writing the counts to a file. Let us know if you need further assistance!
