### ISSUE TITLE
MLFlow: Failing init - AttributeError

### ISSUE THREAD

**Issue by robmarkcole** [ultralytics/ultralytics#2410]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

On using MLflow integration, the following warning is logged:

```
MLFlow: Failing init - AttributeError("'NoneType' object has no attribute 'experiment_id'")
MLFlow: Continuing without Mlflow
```

However logging to MLflow **is** successful and the logs are thus inaccurate

### Environment

Any

### Minimal Reproducible Example

os.environ["MLFLOW_TRACKING_URI"] = "https://dev-mlflow.bla.com/"

### Additional

Possibly this error is raised [here](https://github.com/ultralytics/ultralytics/blob/0ebd3f2959992be55f65cfc908bdf2fd3b618cef/ultralytics/yolo/utils/callbacks/mlflow.py#L39). Ref https://github.com/mlflow/mlflow/issues/1353

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@robmarkcole hello, 

Thank you for bringing this issue to our attention. It seems like the warning message "MLFlow: Failing init - AttributeError('NoneType' object has no attribute 'experiment_id')" is confusing because, despite the message, the logging to MLflow is successful.

 It is possible that this error indicates a problem with the MLflow code when it tries to initialize. However, it could also be a harmless warning message resulting from certain operations.

We appreciate that you have done some initial research and your findings are insightful. We will review your findings and continue to investigate the source of this warning message.

Thanks again for taking the time to report this issue to us. If you have any further questions or concerns, please let us know.

Best regards,
Glenn Jocher

**Comment by Aplieox** [comment]
Has there been any progress so far?
I too get this error/warning, but logging is ultimately successful.

**Comment by glenn-jocher** [comment]
@Aplieox hello! 

Thank you for your interest in YOLOv8. At this time, we are still investigating the cause of the warning message that is logged in Mlflow during initialization, which you and other users have reported. While this warning message may cause confusion, as you have observed that logging to Mlflow is successful, it does not appear to affect the performance of YOLOv8.

We appreciate your patience while we work to address this issue. You can check our GitHub repository and the Ultralytics website for future updates regarding this matter.

Please let us know if you have any further questions or concerns. 

Best regards,
Glenn Jocher
