### ISSUE TITLE
Dataset path structure in Yolov8 how to set labels  .txt files?

### ISSUE THREAD

**Issue by TapendraBaduwal** [ultralytics/ultralytics#2435]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

My data path is like this labels file are under train, valid and test folder...if we set only images folder then how model take labels file automatically ? Shall we also need to set labels file path in data.yml file or its automatically take ?

My dataset structure like datasets/train under train i have 2 folder images and labels

train: ../datasets/train/images
val: ../datasets/valid/images
test: ../datasets/test/images

**Comment by glenn-jocher** [comment]
@TapendraBaduwal thanks for reaching out! If you have both image and label files in separate folders under the main data folder, you will need to specify the paths to the image and label directories separately in the data.yaml file. To do this, you will need to set the 'train' and 'val' paths to the respective folders containing the images and labels, as you have done in your example. This ensures that the YOLOv8 model can locate both the images and associated labels during training and evaluation.

**Comment by TapendraBaduwal** [comment]
@glenn-jocher My path is like this in different folder my question is if i give path of images folder then model automatically locate corresponding labels folders file am i right ? 

train: ../datasets/train/images
val: ../datasets/valid/images
test: ../datasets/test/images

**Comment by glenn-jocher** [comment]
@TapendraBaduwal, thanks for your question! If you have image and label files in separate folders under the main data folder, you will need to specify the paths to both the image and label directories separately in the data.yaml file. This is necessary so that the YOLOv8 model can locate both the images and their associated labels during training and evaluation. Simply setting the path to the image folder will not suffice to locate the corresponding label files. Therefore, you will need to specify the paths to both the image and label folders in the data.yaml file.

**Comment by TapendraBaduwal** [comment]
@glenn-jocher But in coco128.yaml
path is like that here is only image folder path 
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/coco128  # dataset root dir
train: images/train2017  # train images (relative to 'path') 128 images
val: images/train2017  # val images (relative to 'path') 128 images
test:  # test images (optional)

**Comment by glenn-jocher** [comment]
@TapendraBaduwal, thank you for bringing this up. In the coco128.yaml file, data paths and sets are defined slightly differently compared to your dataset structure. In coco128.yaml, only the image directory path is specified under the train and val sets, whereas the test set is left blank. However, this is because coco128 is a dataset with pre-defined labels, and the label files are stored in a separate Json file for each image in the dataset. Therefore, specifying the path to the image folder alone enables YOLOv8 to locate the corresponding label files via these Json files. 

In your case, since you have label files stored in separate directories, you will need to specify both the image and label directories separately under the train and the val sets in your data.yaml file, and optionally under the test set if you have labels available for your test set as well.
