### ISSUE TITLE
How do I alter the save-interval when training?

### ISSUE THREAD

**Issue by initdebugs** [ultralytics/ultralytics#244]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When trying to train a Object Detection model. In the previous version of Yolo you could pass the --save-interval argument to tell the script after how many epochs to save the model. 
How would I do that in Yolov8? Can't seem to find it.

**Comment by AyushExel** [comment]
@initdebugs hey, right now the local weights best.pt and last.pt are updated after every epoch and artifacts are logged to supported logging platforms only after training finishes and models are stripped. Do you want a similar logging feature to log checkpoints in order to save progress?
We are working on better online logging support through HUB using which you can resume training from anywhere, even a different system. If your use case is different, please let us know so that we can support it better. thanks!

**Comment by initdebugs** [comment]
Okay that seems odd. For me it saved a best.pt and a last.pt after the first epoch. After that it hasn't updated those files. It's currently at epoch 78 but hasn't saved it.

**Comment by AyushExel** [comment]
@initdebugs okay that is not expected. It might be a bug. Can you confirm if the ckpt have not been updated by doing this.
```
import torch

ckpt = torch.load("last.pt")
print(ckpt["epoch"])
```
Thanks!

**Comment by initdebugs** [comment]
It shows the correct epoch when doing that. Does that mean that it does save it? The 'last modified' datetime for the file hasn't changed.

**Comment by AyushExel** [comment]
@initdebugs yeah it shows the epoch it was saved on. Maybe it's something with how OS's file managers check last changed? But it should not be something to worry about

**Comment by initdebugs** [comment]
Thank you for the help. I appreciate the work you guys are putting into this.
