### ISSUE TITLE
optimize=True causes RuntimeError: xnnpack::convolution not available!

### ISSUE THREAD

**Issue by kakann** [ultralytics/ultralytics#2465]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

Hello,
I am working on exporting my model to smartphone using torchscript. However, I tried using the optimize=True flag to increase performance on my smartphone. I have trained a custom yolov8m model for road damage detection. Here are the steps to reproduce the crash/bug:

### Environment

-YOLO: Ultralytics YOLOv8.0.92 🚀 Python-3.9.16 torch-2.0.0+cu117 CPU
-OS: Ubuntu 20.04
-Python: 3.9.16

### Minimal Reproducible Example

Reproduce by doing the following:

```python
from ultralytics import YOLO
model = YOLO("yolov8m.pt")
model.export(format='torchscript', optimize=True)
```
Then I try to validate:
```
yolo val task=detect model=yolov8m.torchscript imgsz=640 data=coco.yaml
```

This causes a runtime error:

RuntimeError: xnnpack::convolution not available! Reason: The provided (weight, bias, padding, stride, dilation, groups, transposed, output_min, output_max) parameters are either invalid individually or their combination is not supported by XNNPACK.

### Additional

The first time I encountered this was when doing validation when testing with a custom dataset and a finetuned model to that dataset. However, the bug persists even when using the default yolov8m pretrained model. 

I have updated ultralytics and then tried to reproduce again with the same results:
```
pip install -U ultralytics
```

I also want to add that it is possible that I am doing something wrong and this is not a bug at all. My endgame is to export my model to smartphone format. That is why I am experimenting with optimize=True.

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@kakann hi there,
Thank you for providing the steps to reproduce the issue and including all the necessary details.

The error message "xnnpack::convolution not available" is suggesting that the model is requesting XNNPACK (a CPU-optimized library for convolutional operations) but it is not available on your device. This is usually because your PyTorch version is not built with XNNPACK support or there is a compatibility issue between XNNPACK and your CPU architecture.

To solve this issue, you can try disabling XNNPACK by adding the following code before exporting your model:
```python
import torch.backends.xnnpack.nn as xnn
xnn.enabled = False
```
This will disable the use of XNNPACK and use the default PyTorch convolution operator instead. This might decrease your inference speed on CPU. 
Alternatively, you can try to use a different PyTorch version that is built with XNNPACK support or try to run the exported model on a different device with XNNPACK support.

I hope this helps! Let me know if you have any further questions.
