### ISSUE TITLE
CUDA OutOfMemoryError when training YOLOv8n on VisDrone using Google Colab

### ISSUE THREAD

**Issue by Erol444** [ultralytics/ultralytics#2471]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

The https://github.com/ultralytics/ultralytics/issues/2292 is similar, but the OP didn't provide full information (bug report).

### YOLOv8 Component

Training

### Bug

I have used Ultralytics Hub, and used the default VisDrone dataset to train YOLOv8n model in the Google Colab.
```
OutOfMemoryError: CUDA out of memory. Tried to allocate 1.17 GiB (GPU 0; 14.75 GiB total capacity; 10.64 GiB already allocated; 766.81 MiB free; 12.61 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
![image](https://user-images.githubusercontent.com/18037362/236815375-ffeafe70-a7ee-4378-841f-c34efbaf8151.png)

### Environment

- YOLOv8n
- VisDrone dataset
- Default Google Colab (`Python 3 Google Compute Engine backend (GPU)`)

### Minimal Reproducible Example

In Ultralytics Hub Select the model/dataset mentioned above and try to train it on the (free) google colab.

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Erol444 hello, thank you for bringing this to our attention. It looks like you are encountering an `OutOfMemoryError` while trying to train the YOLOv8n model on the default VisDrone dataset using the Ultralytics Hub and a Google Colab environment. The error message suggests that the GPU is running out of memory. 

This might be due to the size of the dataset or the complexity of the model architecture. You may try increasing the batch size or image size to reduce GPU memory usage. Additionally, make sure that you are using an up-to-date version of PyTorch and YOLOv8 to take advantage of any performance improvements and bug fixes. 

If you would still like to submit a PR, please fork the repo and make your changes to address the bug. Then, submit a pull request to be reviewed by the maintainers. Thank you for your interest in contributing to YOLOv8!

**Comment by glenn-jocher** [comment]
@Erol444, we apologize for the unhelpful response from the GPT bot. If you can provide more details about the issue, including the components you are using in YOLOv8, the bug you have encountered, and any relevant environment or usage information, we will do our best to assist you. We appreciate your patience and understanding.
