### ISSUE TITLE
All used images saveable at .val()?

### ISSUE THREAD

**Issue by Geo-99** [ultralytics/ultralytics#2483]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello :)
For model.val(), is there any way to save all labeled and validated images to the val folder that is created? For me, only three labeled and three validated images are ever saved from my validation dataset.
Also, the number of recognized objects for a specific image often doesn't match between the saved json and those images.

Additionally, I also have the same question as https://github.com/ultralytics/ultralytics/issues/2480

Thanks a lot already!

**Comment by glenn-jocher** [comment]
@Geo-99 hi there!

Regarding your question about `model.val()`, YOLOv8 will only save a subset of labeled and validated images to the `val` folder created during validation. However, you can set the `--save-json` flag to `True` to save a JSON file containing the labels and object detections for all images in the validation set.

Regarding the issue you mentioned with the number of recognized objects not matching between the saved JSON and the images, this could be due to a number of factors such as labeling errors, model confusion, or incorrect object matching during validation. If you could provide more information and specific examples, we might be able to help you better.

Lastly, for the issue you linked to about the `TypeError: 'NoneType' object is not subscriptable` error, please note that it pertains to YOLOv5 and not YOLOv8. If you encounter this error with YOLOv8, please open a new issue with more details about your setup and the error you are experiencing.

Let us know if you have any more questions or concerns!

**Comment by Hommoner** [comment]
@Geo-99 
all you need to do is modify ultralytics\yolo\engine\validator.py

in line 170 or nearby

change 
if self.args.plots and batch_i < 3:
to
if self.args.plots:

```
            # Postprocess
            with dt[3]:
                preds = self.postprocess(preds)

            self.update_metrics(preds, batch)
            if self.args.plots and batch_i < 3:
                #print(f'batch_i = {batch_i} , self.args.plots={self.args.plots}')
                self.plot_val_samples(batch, batch_i)
                self.plot_predictions(batch, preds, batch_i)
```

**Comment by glenn-jocher** [comment]
Hello @Hommoner , 

Thank you for reaching out to us. 

To save all labeled and validated images to the 'val' folder created during validation, you could modify the validator.py file located under ultralytics\yolo\engine\.
You would need to make changes to the code located on or around line 170, in the update loop for validation data. Specifically, you should change the conditional statement that currently limits the number of images to be plotted by replacing this part of the code:

```if self.args.plots and batch_i < 3:```

with:

```if self.args.plots:```

This change will allow all labeled and validated images to be saved in the val folder created during validation.

We hope this helps. Let us know if you have any other questions or concerns!

**Comment by adriengoleb** [comment]
Hello !

With this modification, the ‘val’ command outputs predictions but grouped by batch. In other words, one jpeg file represents X images containing the predictions with X the number of images per batch.

Would it also be possible to obtain all the jpeg images containing the predictions, but individually? And not grouped by batch ? And how in the val.py ?

I tested many modifications but without success.

Thanks for all

**Comment by glenn-jocher** [comment]
Hello,

To save individual JPEG images containing predictions instead of grouped by batch, you can modify the `plot_predictions` function in `validator.py` to save each image separately. Look for the loop that iterates through the batch and save each image individually within that loop.

If you need further assistance, please refer to the Ultralytics documentation or open a new issue with specific details.

Thanks!
