### ISSUE TITLE
WARNING ⚠️ Video stream unresponsive, please check your IP camera connection.

### ISSUE THREAD

**Issue by abdibrokhim** [ultralytics/ultralytics#2507]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

<img width="1416" alt="Screenshot 2023-05-09 at 22 03 50" src="https://github.com/ultralytics/ultralytics/assets/92748035/88cbcd15-c66f-496e-adc9-28a99cc829ba">

### Environment

google colab

### Minimal Reproducible Example

# Load YOLOv8n, train it on COCO128 for 3 epochs and predict an image with it
from ultralytics import YOLO

model = YOLO('yolov8n.pt')  # load a pretrained YOLOv8n detection model
model.train(data='coco128.yaml', epochs=3)  # train the model
model('https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/airpods-max-hero-select-202011?wid=940&hei=1112&fmt=jpeg&qlt=90&.v=1604709293000')  # predict on an image

### Additional

please help me

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by kvalev** [comment]
The error has nothing to do with COCO, as I also get the same error when doing plain inference with `yolo predict`. The issue is rather that the framework only supports downloading images that end in `jpg` (and probably few other extensions). If your url does not end in `jpg` (as it is in your case), then it thinks its a video stream or something and starts printing out those weird error messages.

**Comment by glenn-jocher** [comment]
@kvalev thank you for your report on the `yolo predict` error. It seems that this issue is related to the framework's support for downloading images with specific extensions. If a URL provided does not end in a `jpg` file extension or another supported extension, it assumes that it is a video stream and produces the error messages observed.

To mitigate this issue, a more robust method would be to include a request to fetch only the `HEAD` before downloading the file. This will allow the framework to confirm whether the content is the expected format before attempting to process it.

Thank you for your contribution to YOLOv8, and please let us know if you have any further questions.

**Comment by KevinSerru** [comment]
Hello,

I have the same issue when using the ```predict``` function with a GCP signed URL (so the URL does not end with .jpg).
I'm not sure I understand the workaround you propose... I'd like not to have to first download the image locally before feeding the local path to the predict function.

Thank you for your help.
