### ISSUE TITLE
Display bounding box size instead of label name on image

### ISSUE THREAD

**Issue by noel077** [ultralytics/ultralytics#2524]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello yolov8 team! I would be glad if you could help me with these questions.

So I am detecting just one single class. Normally the images show the class name and the confidence (if show_conf=True). Since I am only detecting only one class, I don't want to see the label name anymore. I already could solve that leaving the class name empty (names: ['']) in the .yaml file of my custom data set.

In adittion, and this is the most important thing, I would like to display the bounding box size instead. Simply because I would like to know the size of the detected objects. I imagine that I should then modify the underlying .py file, but I don't know which one. I already tried to change something in def plot of class Results in the file results.py but without results.
Might the results.py be the wrong file for model.predict() ??

Thank you in advance!

**Comment by glenn-jocher** [comment]
@noel077 hello there!

Great to hear that you were able to solve your first issue. As for displaying the bounding box size instead of the label name, there is a simple way to achieve this without modifying any underlying file. 

You can use the `--hide-labels` argument in your command to remove labels from the output and use `--hide-conf` to remove the confidence score display. Then, you can modify `results.py` to show the bounding box size instead of the labels and/or confidence score. 

To display the size, you can modify the `plot_one_box` function in `results.py`. This function draws the bounding box, label, and confidence score for each detection. You can modify the last line of this function, `Label = f"{dnames[cls]} {conf:.2f}"`, to `Label = f"Size: {int(x2-x1)} x {int(y2-y1)}"`, which will show the width and height of the bounding box instead of the label and confidence score.

I hope this helps! Let me know if you have any further questions or if there is anything else I can assist you with.

**Comment by noel077** [comment]
Hi @glenn-jocher,
first thanks for your quick answer!
Unfortunately I am not achieving the results at all. It seems like any changes I am making to the results.py file doesn't have any impact to my code.
Just to be sure we are talking about the same file, it is allocated under ultralytics\yolo\engine\results.py right?

**Comment by glenn-jocher** [comment]
Hello @noel077,

You are correct, the `results.py` file you are looking for is located under `ultralytics/yolo/engine/results.py`. You may have encountered difficulties seeing your changes take effect due to incorrect file paths or caching. 

For the changes to take effect, it is important to make sure that you are running the same script in which the changes were made. You should also ensure that the updated script is saved and that your environment is aware of the new changes. 

Additionally, you can try clearing the cache or running your script with the `--no-cache` flag to ensure that your changes are reflected. 

I hope this helps. Please let me know if I can assist you with anything else.
