### ISSUE TITLE
i need to run multiple object detection models(yolo) on single video. together .

### ISSUE THREAD

**Issue by mkuntal4015** [ultralytics/ultralytics#2568]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have problem where i need to run multiple object detection models(yolo) on single video and output shall also be in single video .Performance should be close to real time. Database can not be merged. model running should be simultaneously .How can i solved this problem.

**Comment by glenn-jocher** [comment]
@mkuntal4015 thank you for your question. Running multiple object detection models on a single video in real-time can be a difficult task. You may be able to achieve this by using multiple threads or processes to run the models simultaneously, but it will depend on your hardware and the number of models you need to run. Another option could be to modify the YOLOv8 code to accept input from multiple sources simultaneously, but this could also be complex.

Another important point to note is that since object detection is computationally intensive, it may not be possible to achieve real-time performance with multiple models running simultaneously on a single machine, depending on the specifications of your hardware. It may be worth considering using a distributed computing approach or running the detection on multiple machines to achieve the desired performance.

I hope this information helps. If you have any further questions or need additional assistance, please don't hesitate to ask.

**Comment by mkuntal4015** [comment]
@glenn-jocher thank you for your suggestion.

**Comment by glenn-jocher** [comment]
@mkuntal4015 you're welcome! If you have any further questions or need additional assistance, please don't hesitate to ask. We are here to help and support you with your object detection project using YOLOv8.
