### ISSUE TITLE
multi GPU error

### ISSUE THREAD

**Issue by changsubi** [ultralytics/ultralytics#2588]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2972928 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2972929 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2972930 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2972931 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2972932 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2972933 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2972927) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/csyun/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/home/csyun/.local/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/csyun/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/csyun/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/csyun/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/csyun/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/csyun/yolov8_train/ultralytics/train_v8.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-14_00:44:17
  host      : v100-8bay
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2972927)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

### Environment

Ultralytics YOLOv8.0.99 🚀 Python-3.8.10 torch-2.0.1+cu118 CUDA:1 (Tesla V100-SXM2-16GB, 16161MiB)
                                                           CUDA:2 (Tesla V100-SXM2-16GB, 16161MiB)
                                                           CUDA:3 (Tesla V100-SXM2-16GB, 16161MiB)
                                                           CUDA:4 (Tesla V100-SXM2-16GB, 16161MiB)
                                                           CUDA:5 (Tesla V100-SXM2-16GB, 16161MiB)
                                                           CUDA:6 (Tesla V100-SXM2-16GB, 16161MiB)
                                                           CUDA:7 (Tesla V100-SXM2-16GB, 16161MiB)
Ubuntu 20.04LTS

### Minimal Reproducible Example

from ultralytics import YOLO

model = YOLO('yolov8n.yaml').load('yolov8n.pt')  # build from YAML and transfer weights
model.train(data='/home/csyun/NAS/wide/data.yaml', epochs=300, imgsz=1920, batch=-1, pretrained=True, project='/home/csyun/yolov8_trained', name='wide_0514', device='1,2,3,4,5,6,7')

### Additional

it run only one GPU.
but using 7 GPU then not working 
why?
how to solve this problem?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@changsubi hello, 

Thank you for bringing this to our attention promptly. The error message you have received suggests that your default process group has not been initialized; we suggest you try calling "init_process_group()" before launching the model in case you are using the Multiprocessing model to train your YOLOv8 model, as that might help overcome the issue. Within the `nn.parallel.distribute` package, we have found that initializing the default process group is necessary to coordinate the child processes of this package when distributing training among multiple devices.

We hope this resolves your problem, but if you continue to encounter difficulties, please let us know, and we would be happy to look into them in more detail.

Best regards, 
Glenn Jocher.

**Comment by changsubi** [comment]
i dont understrand
So how should I fix it?

**Comment by changsubi** [comment]
@glenn-jocher hello,
thansk but i dont understand So how should I fix it?

**Comment by glenn-jocher** [comment]
@changsubi if you can't get DDP to work in your local environment I'd recommend training in our Docker image. This is where we train all our DDP models. https://hub.docker.com/r/ultralytics/ultralytics

**Comment by exterity** [comment]
Hello,
Just for your information.
I have the same problem with the YOLO CLI. It used to work well with version 8.0.094, but not for 8.0.99. 
OS: Ubuntu 22.04
GPU: 6 x 2060Super
Torch: Cuda 117

**Comment by glenn-jocher** [comment]
@exterity hello,

Thank you for bringing this to our attention. We apologize for the inconvenience caused by this issue. The error message you have described suggests an issue with the DDP implementation in YOLOv8. Our team is currently investigating this issue, and a patch is expected to be included in the next release.

In the meantime, we recommend trying the following steps to resolve the issue:

- Try initializing the default process group by calling "init_process_group()" before launching the model if you are using the Multiprocessing model to train your YOLOv8 model as that might help you overcome the issue.

- If it still continues, we recommend training your YOLOv8 model in our Docker image because this works well with all types of models and has improved support.

If you continue to face any issues, please don't hesitate to reach out to our team for further assistance.

Best regards,
The YOLOv8 Team

**Comment by Dong-tranction** [comment]
> @exterity hello,
> 
> Thank you for bringing this to our attention. We apologize for the inconvenience caused by this issue. The error message you have described suggests an issue with the DDP implementation in YOLOv8. Our team is currently investigating this issue, and a patch is expected to be included in the next release.
> 
> In the meantime, we recommend trying the following steps to resolve the issue:
> 
> * Try initializing the default process group by calling "init_process_group()" before launching the model if you are using the Multiprocessing model to train your YOLOv8 model as that might help you overcome the issue.
> * If it still continues, we recommend training your YOLOv8 model in our Docker image because this works well with all types of models and has improved support.
> 
> If you continue to face any issues, please don't hesitate to reach out to our team for further assistance.
> 
> Best regards, The YOLOv8 Team

你好，"init_process_group()"具体我应该加到yolov8代码的什么位置呢？

**Comment by glenn-jocher** [comment]
@Dong-tranction 你好！ "init_process_group()"应该在使用Multiprocessing模型训练YOLOv8模型之前被调用，建议在代码的开始（首行）处加入该语句。这可能有助于协调此程序包的子进程，以便在多个设备之间分发训练。如果您继续遇到问题，请随时与我们团队联系以获取更多帮助。

祝您好运，YOLOv8团队

**Comment by sadimoodi** [comment]
@glenn-jocher  i was able to download and run the docker container of yolov8 but while trying to run multi GPU training using this command: 
yolo mode=train model=datasets/yolov8-seg-custom.yaml data=data.yaml imgsz=1280 epochs=300 batch=130 device=0,1,2,3,4,5,6,7,8,9

i faced the following error:
TensorBoard: Start with 'tensorboard --logdir /usr/src/ultralytics/runs/segment/train7', view at http://localhost:6006/
WARNING ⚠️ no model scale passed. Assuming scale='n'.
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 335 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 336 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 337 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 338 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 340 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 341 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 342 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 344 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 4 (pid: 339) of binary: /opt/conda/bin/python3
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/root/.config/Ultralytics/DDP/_temp_r8q2pbk8140354421487936.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-05-19_09:53:11
  host      : f19f342fb749
  rank      : 8 (local_rank: 8)
  exitcode  : -7 (pid: 343)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 343
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-19_09:53:11
  host      : f19f342fb749
  rank      : 4 (local_rank: 4)
  exitcode  : -7 (pid: 339)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 339
============================================================
Traceback (most recent call last):
  File "/opt/conda/bin/yolo", line 33, in <module>
    sys.exit(load_entry_point('ultralytics', 'console_scripts', 'yolo')())
  File "/usr/src/ultralytics/ultralytics/yolo/cfg/__init__.py", line 394, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/src/ultralytics/ultralytics/yolo/engine/model.py", line 371, in train
    self.trainer.train()
  File "/usr/src/ultralytics/ultralytics/yolo/engine/trainer.py", line 188, in train
    raise e
  File "/usr/src/ultralytics/ultralytics/yolo/engine/trainer.py", line 186, in train
    subprocess.run(cmd, check=True)
  File "/opt/conda/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/opt/conda/bin/python3', '-m', 'torch.distributed.run', '--nproc_per_node', '10', '--master_port', '46137', '/root/.config/Ultralytics/DDP/_temp_r8q2pbk8140354421487936.py', 'task=segment', 'mode=train', 'model=datasets/yolov8-seg-custom.yaml', 'data=data.yaml', 'epochs=300', 'patience=50', 'batch=120', 'imgsz=1280', 'save=True', 'save_period=-1', 'cache=False', 'device=(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)', 'workers=8', 'project=None', 'name=None', 'exist_ok=False', 'pretrained=False', 'optimizer=SGD', 'verbose=True', 'seed=0', 'deterministic=True', 'single_cls=False', 'rect=False', 'cos_lr=False', 'close_mosaic=0', 'resume=False', 'amp=True', 'overlap_mask=True', 'mask_ratio=4', 'dropout=0.0', 'val=True', 'split=val', 'save_json=False', 'save_hybrid=False', 'conf=None', 'iou=0.7', 'max_det=300', 'half=False', 'dnn=False', 'plots=True', 'source=None', 'show=False', 'save_txt=False', 'save_conf=False', 'save_crop=False', 'show_labels=True', 'show_conf=True', 'vid_stride=1', 'line_width=None', 'visualize=False', 'augment=False', 'agnostic_nms=False', 'classes=None', 'retina_masks=False', 'boxes=True', 'format=torchscript', 'keras=False', 'optimize=False', 'int8=False', 'dynamic=False', 'simplify=False', 'opset=None', 'workspace=4', 'nms=False', 'lr0=0.01', 'lrf=0.01', 'momentum=0.937', 'weight_decay=0.0005', 'warmup_epochs=3.0', 'warmup_momentum=0.8', 'warmup_bias_lr=0.1', 'box=7.5', 'cls=0.5', 'dfl=1.5', 'pose=12.0', 'kobj=1.0', 'label_smoothing=0.0', 'nbs=64', 'hsv_h=0.015', 'hsv_s=0.7', 'hsv_v=0.4', 'degrees=0.0', 'translate=0.1', 'scale=0.5', 'shear=0.0', 'perspective=0.0', 'flipud=0.0', 'fliplr=0.5', 'mosaic=1.0', 'mixup=0.0', 'copy_paste=0.0', 'cfg=None', 'v5loader=False', 'tracker=botsort.yaml']' returned non-zero exit status 1.

Appreciate your help

**Comment by glenn-jocher** [comment]
@sadimoodi hello,

We apologize for the inconvenience caused by the error you are experiencing. The error message suggests that there is an issue with the DistributedDataParallel (DDP) implementation in YOLOv8.

One possible solution you can try is to change the value of the `nbs` parameter to a lower value. The `nbs` parameter controls the number of samples processed in each batch, and setting it to a lower value can help avoid memory issues when training on multiple GPUs.

Another solution you can try is to update your environment to use the latest NVIDIA driver and CUDA toolkit, as this may resolve any compatibility issues that may be causing this error.

If these solutions do not work, please feel free to reach out to our team for further assistance.

Best regards,
The YOLOv8 Team

**Comment by pheersaquoff** [comment]
@glenn-jocher please could you help with calling init_process_group() a little more in detail, what should be passed as arguments etc?

**Comment by glenn-jocher** [comment]
@pheersaquoff hello,

Thank you for your question. 

`init_process_group()` is a PyTorch function that initializes the default process group for distributed training using PyTorch's Distributed Data Parallel (DDP) module. It can be called before launching the model in Multiprocessing mode to help overcome certain issues.

When calling `init_process_group()`, the function takes a single argument, which is the backend that should be used for distributed training. This can be set to either `torch.distributed.backendnccl` or `torch.distributed.backend.gloo`, depending on the backend you prefer to use. In most cases, the `backendnccl` is the favored backend, as it is optimized for NVIDIA GPUs.

For example, if you wanted to initialize the default process group for distributed training using the `backendnccl` backend, you could call the function like this:

`torch.distributed.init_process_group(backend='nccl')`

Please note that this is just an example, and you may need to adjust the arguments to suit your specific use case.

If you require further assistance, please don't hesitate to reach out to our team.

Best regards,
The YOLOv8 Team

**Comment by pheersaquoff** [comment]
@glenn-jocher thank you. now after running 
```torch.distributed.init_process_group(backend='nccl')
model.train(data=...
```
I get 
```runtimeerror: trying to initialize the default process group twice
```
and can't find any info how to handle it, can you help?
