### ISSUE TITLE
Inference classification model error

### ISSUE THREAD

**Issue by isOreo** [ultralytics/ultralytics#2623]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

main.py:
from ultralytics import YOLO
model = YOLO("/home/liu/Myproject/ultralytics/runs/classify/train8/weights/best.pt")
model.predict(**{'cfg':'/home/liu/Myproject/ultralytics/ultralytics/yolo/cfg/default.yaml'})

error:
image 1/4370 /home/liu/PycharmProjects/ultralytics/ultralytics/datasets/apple/test/0001348010.jpg: 640x640 d4 0.00, d1 0.00, d6 0.00, d5 0.00, d8 0.00, 2.0ms
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    model.predict(**{'cfg':'/home/liu/Myproject/ultralytics/ultralytics/yolo/cfg/default.yaml'})
  File "/home/liu/anaconda3/envs/yolov8/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/liu/Myproject/ultralytics/ultralytics/yolo/engine/model.py", line 152, in predict
    return self.predictor(source=source, stream=stream)
  File "/home/liu/anaconda3/envs/yolov8/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/liu/Myproject/ultralytics/ultralytics/yolo/engine/predictor.py", line 114, in __call__
    return list(self.stream_inference(source, model))  # merge list of Result into one
  File "/home/liu/Myproject/ultralytics/ultralytics/yolo/engine/predictor.py", line 178, in stream_inference
    s += self.write_results(i, self.results, (p, im, im0))
  File "/home/liu/Myproject/ultralytics/ultralytics/yolo/v8/classify/predict.py", line 54, in write_results
    log_string += f"{', '.join(f'{self.model.names[j]} {prob[j]:.2f}' for j in top5i)}, "
  File "/home/liu/Myproject/ultralytics/ultralytics/yolo/v8/classify/predict.py", line 54, in <genexpr>
    log_string += f"{', '.join(f'{self.model.names[j]} {prob[j]:.2f}' for j in top5i)}, "
KeyError: 999
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

thank you

**Comment by AyushExel** [comment]
Is it working fine without passing cfg to predict() ?

**Comment by isOreo** [comment]
> Is it working fine without passing cfg to predict() ?

I passing the default.yaml to predict() in main.py, I don’t use ultralytics,I use python SDK

**Comment by glenn-jocher** [comment]
@isOreo it seems like the issue you are facing is due to the presence of `self.model.names[j]` where `j` is equal to 999, which is leading to a KeyError. This indicates that YOLOv8 is unable to find a corresponding class for index 999, which should not happen if the model was trained with the same number of classes as in the provided default.yaml file. 

As for passing the default.yaml file to predict() in your main.py, it should not produce any issues as long as the cfg file is compatible with the model you are using. However, if you still face issues, please try running the prediction on a sample data without passing the default.yaml file to see if the issue persists.

**Comment by Laughing-q** [comment]
@isOreo I think you're mistakenly passing `task=detect` from your `default.yaml` but you actually were using a classification model.
Modifying the `task` to `classify` in your default.yaml could fix this. 
But actually you don't need to pass the whole `cfg:default.yaml` to predict() since we internally set all the configs in default.yaml as default value, you just need to add args that you  want to modify in predict(), like if you want to predict a image with confidence score threshold=0.5 then just try `model.predict(source="your_image_path", conf=0.5)`.

**Comment by isOreo** [comment]
> 
thank for your answer. The problem I encountered is that I can only reason about part of the pictures, and when I reason to a certain picture, I will report an error. I have tested that it is not a picture problem.
When I infer with different post-training models, it's not just keyerror:999, it terminates inference at different picture positions, as shown in the attached picture.
![keyerror](https://github.com/ultralytics/ultralytics/assets/104250421/decc2967-fac1-4678-a2fb-81900f4a7e40)

**Comment by Laughing-q** [comment]
@isOreo could you share your model to me then I can debug this issue? Thanks!

**Comment by isOreo** [comment]
> @isOreo could you share your model to me then I can debug this issue? Thanks!
Thank you very much, what documents do I need to provide to you?

**Comment by Laughing-q** [comment]
@isOreo just upload the model file if you don't mind. :)

**Comment by isOreo** [comment]
> @isOreo just upload the model file if you don't mind. :)

Thanks,is this OK?
[model.zip](https://github.com/ultralytics/ultralytics/files/11483715/model.zip)

**Comment by Laughing-q** [comment]
@isOreo just checked your model and I found that you only have 9 classes but the model output got shape with `[1000]` which is not expected. I suppose you did something incorrect when you were training your model. I suggest you to retrain your model and try again.

**Comment by isOreo** [comment]
> @isOreo just checked your model and I found that you only have 9 classes but the model output got shape with `[1000]` which is not expected. I suppose you did something incorrect when you were training your model. I suggest you to retrain your model and try again.

Thanks! Now I am using the latest code for training and have encountered this issue. The dataset path and errors are shown in the figure, but I have switched to different paths and relative paths, which are not feasible
![datasets](https://github.com/ultralytics/ultralytics/assets/104250421/02765b5e-cebc-4fda-89d7-84452ccde49b)
![error (2)](https://github.com/ultralytics/ultralytics/assets/104250421/e1922049-63cb-4927-8098-f6d4152547ab)

**Comment by glenn-jocher** [comment]
@isOreo thanks for sharing the screenshots. From the error message you received, it seems that the issue lies with loading your dataset. The error message indicates that YOLOv8 cannot find or open the file at the specified path.

I suggest checking the following:
- Double check the path and filename of the dataset that you are trying to load
- Ensure that the specified dataset is in the correct format (YOLOv8 requires txt files containing annotations for each image) and that the annotations match the image filenames
- Verify that you have read and write permissions for the dataset and that there are no issues with the file system that could be causing issues with opening files

If none of these solutions work, please provide more information on the steps that you took to create the dataset and the contents of the dataset folder.
