### ISSUE TITLE
bug on Jetson Orin Nano

### ISSUE THREAD

**Issue by TommyZihao** [ultralytics/ultralytics#2624]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

(tommy) tommy@tommy-desktop:~$ yolo detect predict model=yolov8n.pt source=0 show

qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/tommy/miniconda3/envs/tommy/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
Are you following the official tutorial from here - https://github.com/ultralytics/ultralytics/tree/main/examples ?

**Comment by triple-Mu** [comment]
Maybe reinstall opencv-python will solve ot

**Comment by glenn-jocher** [comment]
@triple-Mu thank you for reporting this issue. The error message indicates that the Qt platform plugin "xcb" could not be initialized. This is commonly caused by missing or corrupted dependencies. 

Based on our experience, reinstalling `opencv-python` might help solve this issue. Please try running `pip install opencv-python --force-reinstall` and then try running the command again. 

Let us know if this resolves your issue. Thank you for using YOLOv8!
