### ISSUE TITLE
The problem of weight loading when using pretrained models

### ISSUE THREAD

**Issue by buxihuo** [ultralytics/ultralytics#2653]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I wanted to compare the impact of using different pretrained models on model performance, but encountered some issues.

The s, m, and l models trained using the Coco dataset will show loading more weights (such as Transferred 589/595 items from pre trained weights), and have a higher map in the first round of training.
The n model trained using the coco dataset (Transferred 319/355 items) and the l model trained using the objects365 dataset (Transferred 559/595 items) will show less weight loading and lower performance in the first few rounds of training.

**Comment by glenn-jocher** [comment]
Hello @buxihuo, 

It is normal for the number of transferred items from pre-trained weights to vary depending on the pre-trained model and the dataset used. The number of transferred items from the pre-trained weights depends on many factors, including the number of classes, the dataset used, and the architecture of the pre-trained model. 

Regarding the difference in performance during the first few rounds of training, this could be due to differences in the datasets and pre-trained weights used. The choice of pre-trained weights should depend on the dataset and problem you are trying to solve. It may be best to try different pre-trained models and fine-tune them on your own dataset to determine which works best for your specific use case. 

I hope this helps! Let me know if you have any further questions.

**Comment by buxihuo** [comment]
Thank you very much for your help. I have found the reason why some pre trained models have less weight loading.


![image](https://github.com/ultralytics/ultralytics/assets/84908793/b674a931-7d87-4a02-bca1-1e07895070ff)


When nc is greater than ch [0], the shape of the pre-trained model may not match the current model. 
For example, when I train the VOC dataset, the maximum value is always ch[0], the n model (nc=80, ch [0]=64) of the coco dataset and the l model (nc=365, ch[0]=256) of the objects365 are both nc, while the maximum values of the s, m and l models in the coco dataset are ch [0]. Therefore, the s, m and l models are loaded with more pre-trained model weights.

**Comment by glenn-jocher** [comment]
@buxihuo you're welcome! I'm glad to hear that you were able to identify the reason why some pre-trained models have less weight loading than others. 

As you have observed, the shape of the pre-trained model may not match the current model when the number of classes (nc) is greater than the maximum value of the channels (ch[0]) in the pre-trained model. In such cases, the s, m and l models loaded with pre-trained weights would be higher because the maximum values of the s, m, and l models in the COCO dataset are ch[0], while the maximum values of the n model trained on COCO and the l model trained on Objects365 are both nc. 

I hope this explanation helps! Let us know if you have any further questions or concerns; we're always here to help.
