### ISSUE TITLE
ValueError: cannot reshape array of size 352128 into shape while training model on COCO dataset

### ISSUE THREAD

**Issue by developer0hye** [ultralytics/ultralytics#2672]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

<img width="938" alt="image" src="https://github.com/ultralytics/ultralytics/assets/35001605/3e6f886e-4c0c-4bf2-b149-7e11b51d4c9f">

### Environment

-YOLO: 8.0.104
-Python: 3.10.8
-torch: 1.13.1

### Minimal Reproducible Example

yolo task=detect mode=train device=0,1 data=coco.yaml epochs=300 batch=64 project=exp8-1 cache=disk model=yolov8n.yaml name=yolov8n scale=0.9 mixup=0.15 copy_paste=0.3 close_mosaic=10

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by janardan-ds** [comment]
@developer0hye Can you once try with the version of YOLOv8 (8.0.101)?

**Comment by glenn-jocher** [comment]
@developer0hye it seems there may be something wrong with this one particular *.npy file. I wonder if disk caching was cancelled and the file is corrupt, as you mentioned that DDP caching was timing out.

Maybe we can improve the error handling around this to report the image/npy file causing problems. Let me take a look at this part of the code.

**Comment by Emran-Saleh-Ali** [comment]
Hi I got simialr error

![Screenshot from 2024-01-31 22-36-29](https://github.com/ultralytics/ultralytics/assets/148222409/16b009a0-8921-4f46-9ba3-6dd36ecf2fdf)

Torch: 1.13.1
Ultralytics: 8.0.197

**Comment by glenn-jocher** [comment]
@Emran-Saleh-Ali it appears there may be an issue with the data loading process, possibly due to a corrupt `.npy` file. Could you please ensure that the dataset was downloaded and extracted correctly without interruption? If the problem persists, try clearing the cache or disabling disk caching. If you continue to encounter this error, please open a new issue with the full error message and details of your environment for further assistance. 🛠️
