### ISSUE TITLE
incorrect segmentation normalized mask labelling in yolov8

### ISSUE THREAD

**Issue by Sudheendra-Oceaneering** [ultralytics/ultralytics#2678]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![train_batch0](https://github.com/ultralytics/ultralytics/assets/123380209/a19925c9-d560-4ed7-a444-4d4eff02a77b)
i am getting wrong labelling for the above pipe dataset after getting masks from SAM. using below code in supervision custom script for yolov8

# Find the contours of the mask
            contours, hierarchy = cv2.findContours(mask.astype(np.uint8), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
            # image = np.ones((width, height), dtype="uint8") * 255
            # cv2.drawContours(image, contours, -1, (0, 255, 0), 3)
            # cv2.imwrite('/home/azureuser/test{}.jpg'.format(i), image)
            # i += 1
            # print(i)
            largest_contour = max(contours, key=cv2.contourArea)
            
            percentage = 0.85
            if percentage < 0.0 or percentage >= 1.0:
                raise ValueError("Percentage must be in the range [0, 1).")

            target_points = max(int(len(largest_contour) * (1 - percentage)), 3)
            epsilon = 0
            approximated_points = largest_contour
            while len(approximated_points) > target_points:
                epsilon += 0.1
                approximated_points = cv2.approxPolyDP(largest_contour, epsilon, closed=True)
                
            # Get the segmentation mask for object
            segmentation = approximated_points.flatten().tolist()

            

            mask = segmentation

            
            # convert mask to numpy array of shape (N,2)
            mask = np.array(mask).reshape(-1, 2)

            # normalize the pixel coordinates
            mask_norm = mask / np.array([width, height])

            # compute the bounding box
            xmin, ymin = mask_norm.min(axis=0)
            xmax, ymax = mask_norm.max(axis=0)
            bbox_norm = np.array([xmin, ymin, xmax, ymax])

            # concatenate bbox and mask to obtain YOLO format
            # yolo = np.concatenate([bbox_norm, mask_norm.reshape(-1)])
            # yolo = mask_norm.reshape(-1)
      
            
            next_object = object_to_yolov8(
                xyxy=bbox_norm, id=class_id, w=width, h=height, polygon=mask_norm.reshape(-1)
            )
            end_result.append(next_object)

any suggestions would be great.

**Comment by glenn-jocher** [comment]
@Sudheendra-Oceaneering hello and thanks for reaching out to us at YOLOv8!

If I understand you correctly, you are experiencing a labeling issue when working with the segmentation mask produced by the Selective Attention Module (SAM) in your custom script.

Firstly, if you haven't already, you may want to try visualizing the SAM output to verify the correctness of the segmentation masks.

As for the labeling issue, since YOLOv8 relies on the convention of bounding box and pixel coordinates normalization, it may be possible that the incorrect labeling might be due to normalization inconsistencies. I would suggest double-checking the normalization code snippet to verify that it corresponds to the correct format. 

Please let us know if you have any further questions or if we can be of any additional assistance!
