### ISSUE TITLE
IndexError: index 6 is out of bounds for dimension 1 with size 6

### ISSUE THREAD

**Issue by nip6** [ultralytics/ultralytics#2681]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Today, while training my own dataset with YOLOv8, I encountered a bug. I noticed that the dataset provided by Ultralytics HUB works fine, but for some reason, I couldn't achieve the same results with my own dataset. I observed that the annotation format of my dataset appears to be consistent with the one provided by the HUB dataset. I'm unsure why this is happening and would appreciate your assistance in resolving this issue. Thank you!
![image](https://github.com/ultralytics/ultralytics/assets/107199746/9b61a778-894d-42ba-9adf-e0a0bb6d6cd9)

This is the txt file I downloaded from the HUB(from coco8).
![image](https://github.com/ultralytics/ultralytics/assets/107199746/7e3a52e7-0962-4173-8331-715d19930fcf)

This is the text file of my own annotated data.
![image](https://github.com/ultralytics/ultralytics/assets/107199746/bed6164f-1012-444d-801f-2a819cf18577)

The annotation format of these two datasets appears to be the same, but my dataset is still unable to train.

**Comment by glenn-jocher** [comment]
@nip6 hello! Thank you for bringing this issue to our attention. From the error message you provided, it appears that the index you are trying to access is out of bounds. This may be caused by several factors such as incorrect annotation format, incorrect data preprocessing, or an issue with your configuration file. My suggestion would be to double-check your annotation format and ensure that it matches the one used in the HUB dataset. Additionally, you may want to ensure that your data preprocessing steps are correct and that your configuration file is properly configured. If you're still having trouble, feel free to provide more information, and we'll do our best to assist you. Thank you!
