### ISSUE TITLE
How to define the sequence of key points using YOLO v8-pose for a symmetrical figure (such as a rectangle)?

### ISSUE THREAD

**Issue by ZhizhuoUp** [ultralytics/ultralytics#2686]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to detect the four key points on a rectangle (or more special, a square) on one image and assign the four key points as the midpoint of each side of the rectangle. When I plan to determine the sequence of these key points, I found a fatal problem. In the beginning, I determine the sequence based on the x-coordinates and y-coordinates, which means the first key point has the smallest x value and the last key has the largest x value.

However, if there are two points with the same x value (or the value is very similar)? In this situation, if the rectangle is slightly rotated, the sequence of key points could change drastically, even though the rectangle before the rotation and after the rotation look very little different on the image. In this sense, if two very similar rectangles have keys in a very different order, my YOLO model may not be clear about which sequence of key points it should choose.

![IMG_6657](https://github.com/ultralytics/ultralytics/assets/73738815/8fe7f6b9-5e9b-4c9b-9311-3b3480070169)
(I uploaded an image to illustrate this problem. These two rectangles are very similar, leading to my YOLO model always choosing the center of the rectangle as both the position of key point 2 and key point 3 while detection. They always stick together and cannot be separated)

I have considered several other plans and can't find any plan which can avoid this ambiguity in determining the sequence. Can you help me? Or in addition to improving the criteria for judging the sequence, can this problem be solved by adjusting the parameters (like flip_idx?) of YOLO v8?

**Comment by glenn-jocher** [comment]
Hello @ZhizhuoUp. When determining the sequence of key points on a symmetrical figure, it is important to take into account the key points' relative positions. Instead of simply sorting by x-coordinate or y-coordinate, you may want to consider sorting by the distance between each key point. This way, if two key points have identical x or y coordinates, their relative position to the other key points will still be taken into account. In addition to distance-based sorting, you may also want to consider implementing techniques like non-maximum suppression to ensure that overlapping or multiple detections are resolved. 

As for adjusting the parameters, flip_idx determines the order in which the horizontal flipping operation is performed during data augmentation. It does not directly affect the sequence of key points. 

I hope this helps. Please let us know if you have any further questions or concerns.
