### ISSUE TITLE
AttributeError when adding Channel Attention to C2f Class

### ISSUE THREAD

**Issue by gitlonglong** [ultralytics/ultralytics#2714]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

When adding a Channel Attention instance (self.attention = ChannelAttention(2* self.c)) to the C2f class and subsequently calling it within the forward method, an AttributeError is raised indicating that the 'C2f' object has no attribute 'attention'.

class C2f(nn.Module):
    """CSP Bottleneck with 2 convolutions."""

    def __init__(self, c1, c2, n=1, shortcut=False, g=1, e=0.5):  # ch_in, ch_out, number, shortcut, groups, expansion
        super().__init__()
        ...
        self.attention = ChannelAttention(2* self.c)

    def forward(self, x):
        ...
        channel_weight = self.attention(x)
        ...

Error Message:
Traceback (most recent call last):
  File "/home/longwei/ultralytics/train.py", line 12, in <module>
    model.train(data="underwater.yaml", epochs=300)  # train the model
  File "/home/longwei/ultralytics/ultralytics/yolo/engine/model.py", line 370, in train
    self.trainer.train()
  File "/home/longwei/ultralytics/ultralytics/yolo/engine/trainer.py", line 195, in train
    self._do_train(world_size)
  File "/home/longwei/ultralytics/ultralytics/yolo/engine/trainer.py", line 272, in _do_train
    self._setup_train(world_size)
  File "/home/longwei/ultralytics/ultralytics/yolo/engine/trainer.py", line 217, in _setup_train
    self.amp = torch.tensor(check_amp(self.model), device=self.device)
  File "/home/longwei/ultralytics/ultralytics/yolo/engine/trainer.py", line 673, in check_amp
    assert amp_allclose(YOLO('yolov8n.pt'), im)
  File "/home/longwei/ultralytics/ultralytics/yolo/engine/trainer.py", line 661, in amp_allclose
    a = m(im, device=device, verbose=False)[0].boxes.data  # FP32 inference
  File "/home/longwei/ultralytics/ultralytics/yolo/engine/model.py", line 111, in __call__
    return self.predict(source, stream, **kwargs)
  File "/root/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/longwei/ultralytics/ultralytics/yolo/engine/model.py", line 252, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/longwei/ultralytics/ultralytics/yolo/engine/predictor.py", line 186, in __call__
    return list(self.stream_inference(source, model))  # merge list of Result into one
  File "/root/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/longwei/ultralytics/ultralytics/yolo/engine/predictor.py", line 225, in stream_inference
    self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
  File "/home/longwei/ultralytics/ultralytics/nn/autobackend.py", line 428, in warmup
    self.forward(im)  # warmup
  File "/home/longwei/ultralytics/ultralytics/nn/autobackend.py", line 314, in forward
    y = self.model(im, augment=augment, visualize=visualize) if augment or visualize else self.model(im)
  File "/root/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/longwei/ultralytics/ultralytics/nn/tasks.py", line 209, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/home/longwei/ultralytics/ultralytics/nn/tasks.py", line 60, in _forward_once
    x = m(x)  # run
  File "/root/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/longwei/ultralytics/ultralytics/nn/modules/block.py", line 253, in forward
    channel_weight = self.attention(x)
  File "/root/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'C2f' object has no attribute 'attention'

### Minimal Reproducible Example

Code Snippet:
class C2f(nn.Module):
    """CSP Bottleneck with 2 convolutions."""

    def __init__(self, c1, c2, n=1, shortcut=False, g=1, e=0.5):  # ch_in, ch_out, number, shortcut, groups, expansion
        super().__init__()
        ...
        self.attention = ChannelAttention(2* self.c, mul=False)

    def forward(self, x):
        ...
        channel_weight = self.attention(x)
        ...

Error Message:
...
AttributeError: 'C2f' object has no attribute 'attention'

Steps to reproduce:
Define a C2f class instance with a Channel Attention instance as an attribute.
Call this attribute within the forward method of the C2f class.

Expected behavior:
No AttributeError should be raised, and the forward method should execute as expected, making use of the Channel Attention attribute correctly.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@gitlonglong hello! 

Based on the error message and the code snippet, it seems that the issue is that the `self.attention` attribute is not being properly initialized in the `__init__` method of the `C2f` class. 

One possibility is that `self.c` has not been properly set at the point when `self.attention` is initialized. Another possibility is that there is a typo or a naming issue in the `__init__` method that is causing the attribute to not be initialized. 

I would suggest double-checking that `self.c` is being assigned properly, and also reviewing your code to ensure that there are no typos or naming issues. Additionally, you could try initializing a different attribute within the `C2f` class and see if that attribute is properly recognized within the `forward` method, which could help narrow down the issue. 

I hope this helps! Please let me know if you have any further questions or if there's anything else I can do to assist you.

**Comment by gitlonglong** [comment]
To isolate any potential impacts from other factors such as 'self.c', I've established 'self.mul_test' as a simple testing mechanism. Still, the 'mul_test' attribute isn't recognized within the forward method, which is puzzling.

**Here is the relevant part of my code:**

class C2f(nn.Module):
    def __init__(self, c1, c2, n=1, shortcut=False, g=1, e=0.5):
        super().__init__()
        self.c = int(c2 * e)
        self.cv1 = Conv(c1, 2* self.c, 1, 1)
        self.cv2 = Conv((2 + n) * self.c, c2, 1)
        self.channel_reduce = Conv(c1, self.c, 1)
        self.m = nn.ModuleList(Bottleneck(self.c, self.c, shortcut, g, k=((3, 3), (3, 3)), e=1.0) for _ in range(n))
        self.mul_test = torch.tensor(1)

    def forward(self, x):
        x = x * self.mul_test
        y = list(self.cv1(x).chunk(2, 1))
        y.extend(m(y[-1]) for m in self.m)
        return self.cv2(torch.cat(y, 1))

**And here is the stack trace of the error:**
Traceback (most recent call last):
    ...
    File "/home/longwei/ultralytics/ultralytics/nn/tasks.py", line 60, in _forward_once
        x = m(x)  # run
    File "/root/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
    File "/home/longwei/ultralytics/ultralytics/nn/modules/block.py", line 186, in forward
        x = x * self.mul_test
    File "/root/miniconda3/envs/pt2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
        raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'C2f' object has no attribute 'mul_test'

The root cause of this error is elusive. I would greatly appreciate your insights on why this might be happening and any suggestions for potential solutions.

**Comment by glenn-jocher** [comment]
@gitlonglong hello there! 

Based on the code snippet and the error message you provided, it looks like the attribute `mul_test` is not being recognized within the `forward` method of your `C2f` class. 

One possibility for this issue is that the `mul_test` attribute is not being initialized properly in the `__init__` method. I see that you have established 'self.mul_test' as a testing mechanism, but it is possible that this attribute is not properly being set.

Another possibility is that there might be a typo or naming issue in your code that is causing the `mul_test` attribute to not be recognized.

To solve this issue, I would suggest double-checking how you are initializing `mul_test` and ensuring that it is set properly before the `forward` method is called. Additionally, you could try using a different attribute to test whether it is being properly recognized within the `forward` method, which could help you further isolate the issue.

I hope this helps! If you have any further questions or concerns, please don't hesitate to ask.

**Comment by HichTala** [comment]
Hi @gitlonglong,

Are you using pre-trained wieghts for your network? I think that is where the problem is coming from. The problem is that when the model tries to process the forward, it uses the initialization of the code used to save the checkpoint, and does not necessarily update it.

Hope this help !

**Comment by gitlonglong** [comment]
> Hi @gitlonglong,
> 
> Are you using pre-trained weights for your network? I think that is where the problem is coming from. The problem is that when the model tries to process the forward, it uses the initialization of the code used to save the checkpoint, and does not necessarily update it.
> 
> Hope this help !

@HichTala Thank you for your suggestion. However, I did not use pre-trained weights. I have set my model up in the following way: model = YOLO("yolov8s.yaml") and model.train(data="underwater.yaml", epochs=100). Have you tested this setup in your environment without encountering any issues? Or did you also experience the same error? I'm looking forward to your reply.

**Comment by HichTala** [comment]
Ok then try to set `amp` hyperparameter to `False`, it may resolve your problem

**Comment by glenn-jocher** [comment]
@gitlonglong hello!

Thank you for reaching out to us. Based on the error message you provided, it's possible that setting the 'amp' hyperparameter to 'False' might help resolve the issue.

You can try adding the 'amp' parameter as an argument to the 'train' method when training your model. For example:

```
model.train(data="underwater.yaml", epochs=100, amp=False)
```

This should disable mixed precision training and might help resolve the error you're encountering.

Please let us know if this solves the issue. If you have any further questions or concerns, please don't hesitate to ask.

Thank you for using YOLOv8!

**Comment by gitlonglong** [comment]
> Ok then try to set `amp` hyperparameter to `False`, it may resolve your problem,
> 
> You can do that by adding it as an argument to the train method:
> 
> ```
> model.train(data="uderwater.yaml", epoch=100, amp=False)
> ```

 @HichTala， Thank you very much for your assistance. I tried your suggestion by setting the 'amp' parameter to False, and it worked! I'm not exactly sure why, but I'm grateful for your help. This has been a bit of a tricky issue for me and your guidance made a difference.

**Comment by gitlonglong** [comment]
> Thank you for reaching out to us. Based on the error message you provided, it's possible that setting the 'amp' hyperparameter to 'False' might help resolve the issue.
> 
> You can try adding the 'amp' parameter as an argument to the 'train' method when training your model. For example:
> 
> ```
> model.train(data="underwater.yaml", epochs=100, amp=False)
> ```
> 
> This should disable mixed precision training and might help resolve the error you're encountering.
> 
> Please let us know if this solves the issue. If you have any further questions or concerns, please don't hesitate to ask.
> 
> Thank you for using YOLOv8!

@glenn-jocher， I sincerely appreciate your prompt response and the helpful suggestion.
I've followed your guidance by setting the 'amp' hyperparameter to 'False', and it seems to have resolved the issue! I'm not exactly sure why the error occurred initially, but your suggestion has indeed rectified the problem for now.

**Comment by glenn-jocher** [comment]
@gitlonglong i suggest to post the reply to the original GitHub issue as a comment, like this:

Thank you for reaching out to us. Based on the error message you provided, it's possible that setting the 'amp' hyperparameter to 'False' might help resolve the issue.

You can try adding the 'amp' parameter as an argument to the 'train' method when training your model. For example:

```
model.train(data="underwater.yaml", epochs=100, amp=False)
```

This should disable mixed precision training and might help resolve the error you're encountering.

Please let us know if this solves the issue. If you have any further questions or concerns, please don't hesitate to ask.

Thank you for using YOLOv8!

**Comment by HichTala** [comment]
The probleme actually comes from those lines :
![Screenshot from 2023-05-23 09-33-42](https://github.com/ultralytics/ultralytics/assets/98521878/60809396-868a-4c24-8c35-5126bfd2c547)

In the file ```ultralytics/yolo/engine/trainer.py```, specifically on ```line 689```, there is a test to determine if the "amp" (automatic mixed precision) can be used. This test compares the output of a pre-trained ```yolov8n``` model with and without amp. The issue arises when the implementation of YOLO is modified by adding new attributes. Since the pre-trained model was not saved with these attributes, it results in an AttributeError being raised.

I can think of two possible fixes for this bug. 
- The simplest one would be to add an exception for the AttributeError. 
- The other option is to create an alternative YOLO class that should never be modified and would only be used in this specific case.

If you think it is relevant, I can submit a Pull Request to address this issue.
