### ISSUE TITLE
How to get names of predicted objects

### ISSUE THREAD

**Issue by nandish486** [ultralytics/ultralytics#2716]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://github.com/ultralytics/ultralytics/assets/93249676/b1e6e25d-6164-4934-bd70-152a335d9cb1)
in the above image, in results line 2, it is seen fox_squirell, etc and more predictions, how to get it programmatically,

as result[0].boxes = none and raises error, it is predicting squirell with 0.45 but i am not getting the object list array like line 2 in output help me

**Comment by glenn-jocher** [comment]
Hello @nandish486, to get the names of predicted objects in YOLOv8, you can access the `result` list that contains multiple `Detection` objects. Each detection object has the predicted class ID (`Det.obj`) and its corresponding confidence score (`Det.score`). You can then use the ID to look up the predicted class name in the `model.names` list.

Here's some example code:
```
model = yolov8()

# Perform inference
results = model('img.jpg')

for det in results.det:
    # Get the class ID and confidence score
    class_id = det.obj
    score = det.score
    
    # Look up the class name from the ID
    class_name = model.names[class_id]
    
    print(f"Predicted object: {class_name} with confidence score: {score}")
```

I hope this helps! Let me know if you have any further questions.

**Comment by circa10a** [comment]
Like so:

```python
from ultralytics import YOLO

rtsp = 'rtsp://*****'
model = YOLO('yolov8n.pt')

results = model.predict(source=rtsp, stream=True, conf=0.51, verbose=False)

for result in results:
    if result.boxes:
        box = result.boxes[0]
        class_id = int(box.cls)
        object_name = model.names[class_id]
        print(object_name)
```

**Comment by glenn-jocher** [comment]
Hello @circa10a,

To get the names of predicted objects in YOLOv8, you can use the `model.names` attribute to look up the predicted class name from the class ID. After performing inference, you can loop through the results, access the detection boxes for each result, extract the class ID, and use it to look up the corresponding class name. Here's some example code:

```
model = yolov8('yolov8n.yaml', 'yolov8n.pt')

# Perform inference
results = model(img)

# Loop through the detections and get the class names
for det in results.det:
    class_id = int(det.obj)
    class_name = model.names[class_id]
    conf = det.score
    
    print(f"Predicted object: {class_name} with confidence: {conf}")
```

I hope this helps! Let me know if you have any further questions.

**Comment by circa10a** [comment]
@glenn-jocher This isn't a complete example when using `predict()` which was what the original issue was raised for, here's the results when running your sample code with `predict()`:

```python
from ultralytics import YOLO

rtsp = 'rtsp://*******'
model = YOLO('yolov8s.pt')

results = model.predict(source=rtsp, stream=True, verbose=False, conf=0.51)

# Loop through the detections and get the class names
for det in results.det:
    class_id = int(det.obj)
    class_name = model.names[class_id]
    conf = det.score
    
    print(f"Predicted object: {class_name} with confidence: {conf}")
```

Error:

```
Traceback (most recent call last):
  File "/Users/admin/src/test/cv-notifier/main.py", line 9, in <module>
    for det in results.det:
               ^^^^^^^^^^^
AttributeError: 'generator' object has no attribute 'det'
```

**Comment by glenn-jocher** [comment]
Hello @circa10a,

Thank you for bringing this issue to our attention. The error that you are seeing is because `results` for YOLOv8's `predict()` method returns a generator object, not a list of results.

To get the results from a generator object, you need to loop through it using a for loop, just like you did. However, instead of accessing the `det` attribute directly, you need to call the `.xyxy` method on each element of the generator object to get the bounding box coordinates.

Here's how you can modify your code to get the predicted object names using `predict()` method:
```
model = yolov8('yolov8s.yaml', 'yolov8s.pt')

# Perform inference
result = model.predict(data)

# Loop through the detections and get the object names
for det in result:
    # Get the bounding box coordinates
    boxes = det.xyxy
    
    # Loop through the boxes and get the class names
    for box in boxes:
        class_id = int(box[-1])
        class_name = model.names[class_id]
        
        print(f"Predicted object: {class_name}")
```

I hope this helps! Please let us know if you have any further questions.

**Comment by circa10a** [comment]
@glenn-jocher Still, these code snippets do not work with the predict() method. I ran your exact code...

```
raise AttributeError(f"'{name}' object has no attribute '{attr}'. See valid attributes below.\n{self.__doc__}")
AttributeError: 'Results' object has no attribute 'obj'. See valid attributes below.
```

For anyone else reading, this is what I've gotten to work: https://github.com/ultralytics/ultralytics/issues/2716#issuecomment-1556355285

**Comment by glenn-jocher** [comment]
@circa10a hello,

Thank you for bringing this to our attention. We apologize for any confusion caused by our previous suggestions. It appears that `predict()` method returns a `Results` object that contains `Detection` objects, which can be looped through to extract the predicted class IDs and confidence scores.

To get the predicted object names from the `Detection` objects, you can use the `model.names` attribute to look up the class name corresponding to each predicted class ID.

We appreciate your patience and understanding, and hope this information helps you get the results you need. If you have any further questions or concerns, please do not hesitate to let us know.
