### ISSUE TITLE
wrong resullts in save_txt files 

### ISSUE THREAD

**Issue by maziqueen79** [ultralytics/ultralytics#2752]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hello , i trained yolov8 on my custom dataset and then tried prediction using the resulted weights, while the results in the images are pretty accurate (the labels i mean) , the ones in the text files are wrong, any idea why ?

**Comment by pderrenger** [comment]
@maziqueen79 hello! It's great to hear that your YOLOv8 predictions are accurate in the images. As for the incorrect labels in the text files, this could be due to a few reasons such as misconfigured output formatting, incorrect class mapping, or post-processing issues. To troubleshoot this, you could check your class labels, post-processing steps, and the specific output formatting used during inference. If you need further assistance, feel free to provide additional details or specific code snippets for us to take a closer look!
