### ISSUE TITLE
YOLOv8 to Tflite conversion

### ISSUE THREAD

**Issue by sinemturkcu** [ultralytics/ultralytics#2753]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I trained a model using Yolov8 and I want to use this model with Flutter. I converted my Yolov8 model to a Tflite extension.

`!yolo export model=runs/detect/train24/weights/best.pt format=tflite`

1 -  Caused by: java.lang.IllegalArgumentException: Cannot copy from a TensorFlowLite tensor (Identity) with shape [1, 6, 8400] to a Java object with shape [1, 20, 20, 40].
2 -  Caused by: java.lang.IllegalArgumentException: Cannot copy from a TensorFlowLite tensor (Identity) with shape [1, 6, 8400] to a Java object with shape [1, 3].

**I am getting such an error due to the codes I wrote with flutter. how can I solve this problem?**

Also my model outputs:
Output name : Identity
Output shape : [ 1 6 8400]
Output data type: <class 'numpy.float32'>

### Minimal Reproducible Example

!yolo export model=runs/detect/train24/weights/best.pt format=tflite

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@sinemturkcu 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. Your code works correctly for me for a default model, I'm unable to reproduce any issues.

<img width="954" alt="Screenshot 2023-05-22 at 21 00 08" src="https://github.com/ultralytics/ultralytics/assets/26833433/19ebd2e1-560b-443b-ad97-2dae487abed1">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by AlexanderKozhevin** [comment]
Funny thing 
```
!yolo export model=runs/detect/train24/weights/best.pt format=tflite

```
Export converts to onnx format. 
So if you need tflite, you need to pt -> onnx -> pb (tensorflow) -> tensorflow lite

**Comment by glenn-jocher** [comment]
@AlexanderKozhevin hi there,

You're correct! The export process first converts the PyTorch model ('.pt') into ONNX format. If you need to convert your model to TensorFlow Lite ('.tflite'), you would then need to convert the ONNX model to TensorFlow ('.pb') first. Once it's in TensorFlow format, you can then convert it to TensorFlow Lite.

So the full conversion pipeline is: PyTorch ('.pt') -> ONNX -> TensorFlow ('.pb') -> TensorFlow Lite ('.tflite'). 

Please let us know if you have any more questions or need further clarification.

**Comment by sdi1900012** [comment]
Hi, after i converted it to tflite, the output of the tfmodel is a tensor [1,5,5376]. How can i convert this output to bbox,class,confidence predictions? This model is supposed to object detect a single class.

**Comment by glenn-jocher** [comment]
@sdi1900012 hi there, 

The tensor you're seeing `[1, 5, 5376]` represents the output of your YOLOv8 model in TFLite format. This output is composed of the bounding box predictions, class predictions, and object confidence score. 

- The first dimension (`1`) is the batch size which is typically 1 for inference.
- The second dimension (`5`) corresponds to the parameters for each bounding box (the center coordinates `(x, y)`, the width `w`, the height `h`, and the objectness score).
- The third dimension (`5376`) corresponds to the total number of bounding boxes predicted by the model. 

You'll need a corresponding interpretation function to parse these outputs to obtain the bounding box, class, and confidence predictions. This function would reshape and/or split the tensor output to extract each component. 

Once you have separated the bounding box, class, and confidence components, you can apply further processing like thresholding the confidence score then use Non-Maxima Suppression (NMS) to remove overlapping boxes. 

Remember, this object detection model provides predictions in terms of relative coordinates, so you might need to convert these relative coordinates (which are between 0 and 1) to pixel values by multiplying the relative coordinates by the image width or height. 

Hope that helps! Let us know if you have further questions.

**Comment by glenn-jocher** [comment]
@Jacko760 hi there,

After converting your YOLOv8 model to TFLite and getting the tensor `[1, 22, 8400]`, you'll need to post-process this output within your application in Java. 

This post-processing will involve:
- Reshaping the tensor to properly separate the bounding box coordinates, the objectness scores, and the class predictions.
- Applying confidence thresholding to filter out low-confidence predictions.
- Running Non-Maximum Suppression (NMS) to merge overlapping bounding boxes.

As your model is designed for single-class object detection, the class prediction step might simply involve verifying the presence of an object above a certain threshold.

This logic should be included in your Java code that's deploying the TFLite model. 😊

**Comment by Jacko760** [comment]
Thanks for your detailed explanation!
Could you please tell me how to post process using Tflite interpreter  only
? or is there any other way to do it ?
So far I’ve searched in the net , peoples are like modify the models
architecture last layer output before converting into tflite so I’m bit
confused at this moment. As export script from ultralyitics showing tflite
exported  successfully .
If you could guide me , would be of helpful

**Comment by glenn-jocher** [comment]
@Jacko760, post-processing the outputs of your TFLite model requires code to interpret the raw output tensor `[1, 22, 8400]`. The Ultralytics export script is designed to convert the model successfully, but you'll need separate logic for post-processing.

There are three main steps you'll typically follow:
1. **Decode the Output Tensor**: Extract and transform the raw tensor to a set of bounding boxes with associated confidence scores and class probabilities.
2. **Apply a Confidence Threshold**: Filter out predictions below a certain confidence level.
3. **Non-Maximum Suppression (NMS)**: Use NMS to eliminate redundant overlapping boxes.

It's not necessary to modify the model's architecture unless you need output tensors directly in a different format. For standard YOLO models, you'll write the post-processing logic in Java or whichever language you're using for deployment.

While specific code examples are beyond the scope of this reply, you’ll typically work with the TFLite Interpreter in Java to:
- Run inference with the model and fetch the output tensor.
- Process the tensor according to the YOLO output format.
- Implement confidence filtering and NMS on the processed outputs.

Consider checking out the Tensorflow detection API which might have ready-to-use TFLite models with post-processing included, or dive into forums and official TFLite documentation for post-processing guidance specific to Java.

Hope this provides a clearer direction for your post-processing needs! 🌟

**Comment by Jacko760** [comment]
Very helpful! Let me try
If I face anything during the journey ill let you know

**Comment by splcoder** [comment]
Hi, there.

After getting the .pt of about 80 MB I converted it to .tflite giving a file of about 160 MB !!!
What param do I need to use to compress the .tflite file ?

**Comment by glenn-jocher** [comment]
@splcoder hello,

The increase in size from the '.pt' to '.tflite' model file can sometimes occur. TFLite models do not have built-in compression parameters at the time of conversion. However, to reduce the size:

1. **Quantization**: Implement post-training quantization to convert the model's float number parameters to integers, which can significantly reduce the model size.

2. **Pruning**: Apply model pruning techniques before conversion, which involves cutting out less important connections in the neural network.

3. **Optimization Tools**: Use TensorFlow's model optimization tools which might include quantization or other methods to reduce the size after conversion.

After applying such techniques, you would convert the model again to TFLite format.

For detailed guidance on these methods, visit the Ultralytics Docs.

Happy optimizing! 🌟

**Comment by Mirxa08** [comment]
@Jacko760 can you help me out resolving this ? I am facing the same issue. can you share the logic do decrypt that raw tensor ?
