### ISSUE TITLE
My code skips 'nested if statements' and runs to infinity when using a Webcam.

### ISSUE THREAD

**Issue by cruseruka** [ultralytics/ultralytics#2762]
### Discussed in https://github.com/orgs/ultralytics/discussions/2724

<div type='discussions-op-text'>

<sup>Originally posted by **cruseruka** May 20, 2023</sup>
Hi everyone. I'm using a YOLOv5 tracking code. I've modified it, it fails to perform some tasks:
1. Runs to infinity (when I opt to use a webcam, it doesn't accept the WaitKey() function),
2. I gave it some conditions to check before it does some detections and labeling. See line 177, I want it to detect a bottle first, then perform other detections (cup, line 197; book, line 214; and cell phone, line 223).
Unfortunately, when I show it a bottle, it detects, annotates, and labels it, but skips the other nested 'if' statements.

I have attached the code and the weights I'm using.

Kindly help.
[Code+Weights.zip](https://github.com/ultralytics/ultralytics/files/11523642/Code%2BWeights.zip)

![image](https://github.com/ultralytics/ultralytics/assets/98976993/25afc373-ed53-4808-ae78-e020dd0ec1bf)
</div>

**Comment by cruseruka** [comment]
Thank you @glenn-jocher for your support. I attached the code and the weights I'm using, in a zipped file. 

I'm nesting the if statements in this manner because I want the code to scan and detect other objects (such as a cup, book, or cell phone in this code) ONLY, after it has detected the bottle. That means, if no bottle has been detected, no other detections should be done. I fail to use and/ or because I want to estimate the distances of the detected objects, which is a function of the bounding box coordinates, therefore the objects with different BBs will show different distances.

I'm reattaching the code.

[Code+Weights.zip](https://github.com/ultralytics/ultralytics/files/11545030/Code%2BWeights.zip)

**Comment by glenn-jocher** [comment]
You're welcome, @cruseruka! Thank you for sharing your code and weights with us.

Based on the code you've provided, it seems that you want your detection loop to first detect if a bottle is present in the image, and if so, then proceed to detect and label other objects like a cup, book, or cell phone. You've nested the `if` statements in this manner to ensure that other objects are only detected when a bottle is present in the image.

Regarding your use of `if` statements, it's important to note that nested statements can sometimes lead to confusion and bugs. But in your case, I understand that you've opted for nested `if` statements to be able to calculate the distances of the detected objects with respect to their bounding box coordinates. Because different objects will have different bounding boxes, using `and` or `or` could potentially miss some detections.

One possible solution to address the issue you raised earlier of the detection loop running infinitely when using a webcam could be to use a separate thread to call the `waitKey()` function periodically, so that the loop can maintain responsiveness.

I hope this explanation helps! Let me know if you have any further questions or need additional clarification.

**Comment by cruseruka** [comment]
Thank you brother @glenn-jocher for your time and response.

You are right. That's my aim. However, I fail to get a way through. Else if I may ask, Is there a way I can differentiate the bounding boxes of various objects within the same frame? Like; if I opt to use and/or to detect all objects of interest such as bottles, cups, books, etc; can I assign bbox coordinates to each object separately? In this way I'll be able to get corresponding bbox dimensions.

Regarding the waitKey() issue, I have no clue how to make a separate thread to call it :).

**Comment by glenn-jocher** [comment]
You're very welcome, @cruseruka! I'm glad I could help.

To answer your question, yes, you can differentiate the bounding boxes of various objects within the same frame by assigning unique labels to each object. For example, you could use integer labels to distinguish between different objects. Then, within each `if` statement block, you can calculate the distance based on the bounding box coordinates for each particular object and its corresponding label.

Regarding the infinite running issue when using `waitKey()`, you can use a separate thread to call the `waitKey()` function periodically. This will help ensure that the detection loop can maintain its responsiveness while waiting for user input. One way to implement this is by using Python's `threading` module to create a new thread that calls `waitKey()`. This allows the main detection loop to continue running while also periodically checking for user input.

I hope this helps! Let me know if you have any further questions or if you need additional clarification.

**Comment by cruseruka** [comment]
Thank you bro @glenn-jocher. I'll try to implement the options to see if they work. I'll come back to confirm that. I appreciate your time.

Best regards.

**Comment by glenn-jocher** [comment]
You're very welcome, @cruseruka! I'm glad I could help, and I hope the suggestions I provided will be helpful in addressing your issues with YOLOv8. Please feel free to come back and confirm if they worked for you, or if you have any further questions or issues to address. Thank you for your time and best regards!
