### ISSUE TITLE
Execution difference between CLI and direct Python3 execution on Jetson Xavier AGX

### ISSUE THREAD

**Issue by TeamRoboTo** [ultralytics/ultralytics#2790]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

Hello everyone! 
I'm interested in using reliably the tracking methods offered by ultralytics API.
But i'm facing a big problem:
The CLI inference give me all the time lower inference times, while the python API of for both tracking and normal detection are always slower.
detection time : CLI 11ms python3 20ms
tracking time: CLI 13ms python3 42ms
i did measure the duration of the call model.track() and model.predict() using time.time() before and after the call and then using inference_time=after-before. 
I'm doing experiments since 1 month and i remember that at the beginning i did't have this problem. 
Can you help me debug this situation? 
PS the problem persist also inside docker containers.

### Environment

- Ultralytics YOLOv8.0.92 🚀 Python-3.8.10 torch-2.0.0a0+8aa34602.nv23.03 CUDA:0 (Xavier, 14899MiB)
- L4T 35.3.1
- CUDA 11.4

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello @TeamRoboTo, 

Thank you for reaching out to us. We would recommend checking if your Python environment and the CLI environment are the same. If there is a difference in the environment, it may affect the inference time. Additionally, we suggest checking if there is any difference in the input images being used between the CLI and the Python3 API. 

Furthermore, we recommend checking the following:
- Are you using the same input images for both CLI and Python executions? 
- Are you using the same batch size? 
- Are you using the same threshold values? 
- Are there any differences in the way the data is loaded between the CLI and Python executions? 

If all of the above checks out, it is possible that there may be other factors that are affecting the inference time. In that case, please provide more information about your experiments, such as details about your input images, model architecture, and any customizations made to the code. We will be happy to help you debug the situation further. 

Thank you for using YOLOv8, and please let us know if you have any further questions.

**Comment by TeamRoboTo** [comment]
Hello, 
thanks for the quick response, i'll answer the question in order:
-yolo is using in both cases the same interpreter of the same version of python3.8
-batch size is fixed to one 
-same default threshold for both implementation
-the video source is the same, but in python i'm working with frames and not with a video stream.
This is a simple snipped of the code where i'im encoutering the problem. 
![Screenshot from 2023-04-15 17-42-44](https://github.com/ultralytics/ultralytics/assets/107797173/b37d7fb7-fb7a-4c9d-94b5-bf2f743432ee)
Also in this simple example it is still slow, also using an engine and fp16 model, not reaching the performances described here https://www.seeedstudio.com/blog/2023/03/30/yolov8-performance-benchmarks-on-nvidia-jetson-devices/.
mine is AGX Xavier that is mutch more powerfull then the standard Xavier NX.

**Comment by glenn-jocher** [comment]
@TeamRoboTo hello, 

Thank you for the additional information and for providing a code snippet. 

It is possible that loading frames instead of a video stream in the Python implementation may affect the inference time. In the CLI implementation, video streams are used, which may have a more optimized data pipeline. 

Additionally, we recommend checking if there are any other processes running in the background that may be taking up resources and affecting the inference time. It may also be useful to check the temperatures of the device during the execution of the code to ensure that thermal throttling is not occurring. 

Regarding the performance benchmarks, please note that the benchmarks provided by Seeed Studio use a standard NX board and different models so the results may not be directly comparable to your AGX Xavier board using a different yolov8n model.  

If you have further questions or concerns, please do not hesitate to let us know.

**Comment by TeamRoboTo** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/107797173/030dad66-6e0f-4ceb-9d16-97a52cc9790a)
![image](https://github.com/ultralytics/ultralytics/assets/107797173/c6715c62-2a9e-4a23-b428-c267526152cd)
Up here are the resources occupation running only yolov8n inside a script python. The system seems to be not stressed, not recruiting all the necessary resources.
meanwhile down here are the resources  occupied by the CLI, it perform mutch better also using less resources.
Same tracking with same arguments and same .engine model is used.
![image](https://github.com/ultralytics/ultralytics/assets/107797173/5a7e8902-07df-44ae-be12-93f0d104b40a)
![image](https://github.com/ultralytics/ultralytics/assets/107797173/14dc2203-4a39-4d89-b7fa-1b7c07a9f80b)

**Comment by glenn-jocher** [comment]
Hello @TeamRoboTo,

Thank you for providing the additional information and code snippet. 

Based on the information provided, we suggest that the difference in the inference time may be due to differences in the pipeline between the CLI and Python implementations, as well as the different input data sources being used. Additionally, the Python implementation may not have optimized data handling pipelines as the CLI.

It is possible that loading individual frames in Python instead of a video stream may lead to a slower inference time. We recommend further investigating and optimizing the data pipeline in the Python implementation to improve the inference time.

Furthermore, we recommend checking for any background processes that may be taking up system resources and affecting the inference time. It may also be useful to check the temperatures of the device during the execution of the code to ensure that thermal throttling is not occurring.

If you have any further questions or concerns, please let us know. We are happy to help.
