### ISSUE TITLE
How to use YOLOv8 to count pedestrian numbers and obtain error values?

### ISSUE THREAD

**Issue by sevenPot7** [ultralytics/ultralytics#2797]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to use YOLOv8 to count the number of pedestrians in the video, similar to the image below.
![1](https://github.com/ultralytics/ultralytics/assets/130882551/ec256924-7f27-4dd4-a2c1-8ca6180ec7d6)
But I don't know which Python file to change and how to implement it. 
I know that each prediction result will output the number of pedestrians in the current image, but I also want to **obtain the error between the detected results and the actual number of pedestrians**. 
I will appreciate it if someone can help me.

**Comment by aurelm95** [comment]
The main idea is that you need to track the people detected in the video and then add an extra condition to increase a counter.

The problem is that you **won't** be able to obtain the error between the detected results and the actual number of pedestrians unless you count them by yourself. If you were able to get the error automatically, the you would just never fail counting.

**Comment by sevenPot7** [comment]
> The main idea is that you need to track the people detected in the video and then add an extra condition to increase a counter.
> 
> The problem is that you **won't** be able to obtain the error between the detected results and the actual number of pedestrians unless you count them by yourself. If you were able to get the error automatically, the you would just never fail counting.

If it is a image with a label file, can I obtain the actual number of pedestrians by counting the data in the label?

**Comment by aurelm95** [comment]
> > The main idea is that you need to track the people detected in the video and then add an extra condition to increase a counter.
> > The problem is that you **won't** be able to obtain the error between the detected results and the actual number of pedestrians unless you count them by yourself. If you were able to get the error automatically, the you would just never fail counting.
> 
> If it is a image with a label file, can I obtain the actual number of pedestrians by counting the data in the label?

Yes, in that case you can do it. But for the video you woud need to count the people by hand.

**Comment by glenn-jocher** [comment]
Hello @aurelm95, 

If your data has label files available for each image, then you can count the actual number of pedestrians by counting the number of labels for the pedestrian class in the corresponding label file. However, for a video, there's no way to get the number of pedestrians automatically, as you would need to manually count them by yourself. I hope this helps. Let us know if you have any further questions.

Best regards.

**Comment by sevenPot7** [comment]
> If your data has label files available for each image, then you can count the actual number of pedestrians by counting the number of labels for the pedestrian class in the corresponding label file. However, for a video, there's no way to get the number of pedestrians automatically, as you would need to manually count them by yourself. I hope this helps. Let us know if you have any further questions.
Which Python file should I modify to counting the number of labels in the corresponding label file? Is it in 'predict.py'? I haven't used yolo before so can you be more specific? Thank you!

**Comment by sevenPot7** [comment]
> Hello @aurelm95,
> 
> To count the number of labels in a label file, you can use a Python script that reads the label file, extracts the number of labels for a specific class (in your case, for "pedestrian" class), increments a counter variable for each label found, and then returns the final count. Regarding which Python file to modify for this task, you don't need to modify any of the existing YOLOv8 files for this purpose. Instead, you can write a new Python script that reads the label files and counts the number of labels as described above. Once you have the count, you can compare it with the number of detections made by YOLOv8 using the same class to evaluate the accuracy of your model. If you have any further questions, feel free to ask.
> 
> Best regards.
I want to know which file control the output statement after predict is completed, like the picture below
![R{_)I417KDMV9G{E E`2Y8C](https://github.com/ultralytics/ultralytics/assets/130882551/e5cd254c-ffcb-4bf1-9802-03af49487ffd)
I want to obtain the number ‘31’ to compare it with the number I obtained from the label file. Thanks for your patience.

**Comment by glenn-jocher** [comment]
Hello @sevenPot7,

The output statement after predict is completed is controlled by the `utils/general.py` file in the YOLOv8 repository. The function responsible for printing the output message is called `plot_one_box`. This function takes in several input parameters, including the predicted coordinates of the bounding box, the predicted class label, the predicted confidence score, and the image frame, among others. 

To obtain the number of detected pedestrians, you can modify this function to increase a counter variable whenever the predicted class label matches "pedestrian." Since this function is already called for each detected bounding box in the `predict.py` file, the counter variable will be incremented for each pedestrian detected in the image or video. Then, after `predict.py` has finished running, you can print the final count of detected pedestrians.    

I hope this helps. If you have any further questions, please feel free to ask.

Best regards.

**Comment by sevenPot7** [comment]
> `utils/general.py` file in the YOLOv8 repository

I'm sorry but I can't find the utils/general.py file in the YOLOv8 repository, like the screenshot below. 
![image](https://github.com/ultralytics/ultralytics/assets/130882551/64002378-6266-4234-8c69-b4ed21294d98)
Thanks.

**Comment by glenn-jocher** [comment]
@sevenPot7 hello,

I apologize for the confusion, but there was an error in my earlier response. The `utils/general.py` file is actually not present in the YOLOv8 repository, and my response was based on the YOLOv5 implementation.

To obtain the number of detected pedestrians after running a YOLOv8 prediction, you can modify the `predict.py` file itself. In this file, you will find a loop over the detected bounding boxes, with each iteration calling the `plot_one_box` function in the `utils/plots.py` file. Within this loop, you can add a counter variable that increments whenever the predicted class label matches "pedestrian." At the end of the loop, you can add a print statement that displays the total count of detected pedestrians.

I hope this clarifies things. If you have any further questions, please feel free to ask.

Best regards.

**Comment by sevenPot7** [comment]
> @sevenPot7 hello,
> 
> I apologize for the confusion, but there was an error in my earlier response. The `utils/general.py` file is actually not present in the YOLOv8 repository, and my response was based on the YOLOv5 implementation.
> 
> To obtain the number of detected pedestrians after running a YOLOv8 prediction, you can modify the `predict.py` file itself. In this file, you will find a loop over the detected bounding boxes, with each iteration calling the `plot_one_box` function in the `utils/plots.py` file. Within this loop, you can add a counter variable that increments whenever the predicted class label matches "pedestrian." At the end of the loop, you can add a print statement that displays the total count of detected pedestrians.
> 
> I hope this clarifies things. If you have any further questions, please feel free to ask.
> 
> Best regards.

Sorry to disturb you again, but I found that there is no utils/plots.py file too.
![image](https://github.com/ultralytics/ultralytics/assets/130882551/4beeb968-4ab3-4bee-8659-079e37a86a67)

And here is the content of predict.py.
![image](https://github.com/ultralytics/ultralytics/assets/130882551/2641d8cf-8f80-480e-8def-4d1854ff4226)

**Comment by glenn-jocher** [comment]
Hello @sevenPot7,

I apologize for the confusion. Since there is no `utils/plots.py` file in the YOLOv8 repository, you can modify the `predict.py` file itself to obtain the count of detected pedestrians. Within the loop over the detected bounding boxes, you can add a condition to check if the predicted class label matches "pedestrian". If it does, you can increment a counter variable by 1. After the loop has finished, you can print the final count of detected pedestrians. This implementation will allow you to count the number of detected pedestrians using the same class label as the one used in the corresponding label file, if available. Please let me know if you have any further questions.

Best regards.
