### ISSUE TITLE
Differences between inferencing with ONNX models and YOLO modules

### ISSUE THREAD

**Issue by jungms4536** [ultralytics/ultralytics#2823]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hi 
I am training YOLOV8 classification model and doing classification.
When the classification model is run with Code1, it predicts label 1. 
When running the model with Code2, it predicts label 2.
The images used as input are the same and you are wondering why there is such a difference.

I need to use onnxruntime to make an inference and it would be great if you could tell me what I need to fix in Code2. 
Please reply 

-Code1-
```
from ultralytics import YOLO
model = YOLO("JEJU_classifier_v1.2.onnx")
model.predict(task='classify',imgsz=224,source="C:/Users/eh453/Anomaly/FF_hurt/Reverse/")
```

-Code2-
```
import numpy as np
import cv2
import onnxruntime as ort
import os
# Load the ONNX model
model_path = model_path
providers = ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
session_options = ort.SessionOptions()
session_options.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_ALL
session = ort.InferenceSession(model_path, session_options, providers=providers)

# Input image size
input_size = (224, 224)

# Load and preprocess the input image

dir_path = directoryPath
for img in os.listdir(dir_path):
    image_path = os.path.join(dir_path,img)
    image = cv2.imread(image_path)
    image = cv2.resize(image, input_size)
    image = image.astype(np.float32)
    image /= 255.0
    image = np.transpose(image, (2, 0, 1))  # Reshape to (C, H, W)
    image = np.ascontiguousarray(image)
    # Create a batch with a single image
    input_batch = np.expand_dims(image, axis=0)

    # Run inference
    outputs = session.run(None, {'images': input_batch})

    # Process the outputs
    class_probs = outputs[0]
    class_ids = np.argmax(class_probs, axis=1)
    # Print the predicted class ID and probabilities
    print("Predicted Class ID: ", class_ids[0])
    print("Class Probabilities: ", class_probs[0])

```

**Comment by glenn-jocher** [comment]
@jungms4536 hello! Thank you for reaching out. It is possible that there could be a difference in inferencing between the ultralytics YOLOv8 module and the ONNX model. When running the YOLOv8 module with Code1, it may be using a different pre-processing configuration or post-processing routine compared to the process done in Code2. With the ONNX model, you are doing custom pre-processing, much like you are doing in Code2. These differences in implementation could result in different predictions.

To investigate the root cause of the difference, you could set verbose=True in the predict function in Code1 to get more info on the model input and output shapes during inference. You could then adjust Code2 to use the same input pre-processing steps as Code1. It would also be helpful to check the class labels and ensure they are what you expect them to be.

Please let me know if there's anything else I can do to help.
