### ISSUE TITLE
Sorting the images by map50 metric per label and displaying bounding boxes on images

### ISSUE THREAD

**Issue by mbober01** [ultralytics/ultralytics#2826]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I wrote a script that allows to pass in path to directory where images and labels are located and then run model on these images. Next compare the prediction and ground truth labels to find images where given label is recognized wrong using mAP50 metric.
Script also allows to save images with both ground truth and predicted bounding box for given label displayed on image
I was inspired by https://airctic.com/0.12.0/plot_top_losses/
If this is something that could be useful I could make a request with my code.

### Use case

Find which labels are recognized wrong by your model and see how model is predicting labels compared to ground truth labels.
Also sort the images by mAP50 metric.
Can be used both in jupyter notebook and in command line

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hi @mbober01,

Thank you for expressing interest in contributing to our YOLOv8 repository! Sorting the images by map50 metric and displaying bounding boxes on images is a great idea and we appreciate your offer to submit a PR. 

We encourage you to create a new issue with your proposal so that we can better track and discuss the feature request. Additionally, please note that when submitting the PR, we request that you ensure the new code follows our established coding standards and passes our existing tests. 

Thank you again for your contribution to YOLOv8. We appreciate the effort and look forward to reviewing your PR. If you have any additional questions or concerns, please do not hesitate to reach out to us.

Best regards, 
Glenn
