### ISSUE TITLE
After using YOLOv8-pose for prediction, I found that the saved text file has incorrect coordinates for the keypoints.

### ISSUE THREAD

**Issue by Bestani-K** [ultralytics/ultralytics#2837]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

The saved video does not match the corresponding labels file after the model prediction. For example, in the first frame of the predicted video, there are no keypoints detected, but the labels file contains coordinates for keypoints. After reviewing the relevant code, it seems that the labels are being saved without considering the confidence score, causing keypoints with low confidence to be included in the labels file.I modified the save_txt in yolo/engine/results.py, but the issue was not resolved, which is confusing to me.`

    def save_txt(self, txt_file, save_conf=False):
        """
        Save predictions into txt file.

        Args:
            txt_file (str): txt file path.
            save_conf (bool): save confidence score or not.
        """
        boxes = self.boxes
        masks = self.masks
        probs = self.probs
        kpts = self.keypoints
        texts = []
        if probs is not None:
            # Classify
            n5 = min(len(self.names), 5)
            top5i = probs.argsort(0, descending=True)[:n5].tolist()  # top 5 indices
            [texts.append(f'{probs[j]:.2f} {self.names[j]}') for j in top5i]
        elif boxes:
            # Detect/segment/pose
            for j, d in enumerate(boxes):
                c, conf, id = int(d.cls), float(d.conf), None if d.id is None else int(d.id.item())
                line = (c, *d.xywhn.view(-1))
                if masks:
                    seg = masks[j].xyn[0].copy().reshape(-1)  # reversed mask.xyn, (n,2) to (n*2)
                    line = (c, *seg)
                if kpts is not None:
                    kpt = (kpts[j][:, :2] / d.orig_shape[[1, 0]]).reshape(-1).tolist()
                    if len(kpts[j]) == 3:
                        k_conf = kpts[j][2]
                        if k_conf < 0.5:
                            continue
                    line += (*kpt, )
                line += (conf, ) * save_conf + (() if id is None else (id, ))
                texts.append(('%g ' * len(line)).rstrip() % line)

        if texts:
            with open(txt_file, 'a') as f:
                f.writelines(text + '\n' for text in texts)
`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello @Bestani-K! Thank you for reaching out to us. Our team will be happy to assist you in resolving the issue. 

It seems that there might be an issue with the confidence score not being taken into account while saving the labels. After reviewing the code, I suggest that you modify the `save_txt` method in `yolo/engine/results.py` to ensure that the keypoints with confidence below a certain threshold are not saved in the `.txt` file. 

Here's an example code snippet:

```python
if kpts is not None:
    kpt = (kpts[j][:, :2] / d.orig_shape[[1, 0]]).reshape(-1).tolist()
    if len(kpts[j]) == 3:
        k_conf = kpts[j][2]
        if k_conf < YOUR_CONFIDENCE_THRESHOLD:
            continue
    line += (*kpt, )
```

Replace `YOUR_CONFIDENCE_THRESHOLD` with the minimum confidence score that a keypoint needs to have in order to be saved in the `.txt` file.

I hope this helps! Please let us know if you have any further questions or if there is anything we can assist you with.
