### ISSUE TITLE
 When Yolov8pose pt is converted to onnx, the confidence level of key points will change and generally decrease

### ISSUE THREAD

**Issue by wenshuaishuai123** [ultralytics/ultralytics#2840]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

When Yolov8pose pt is converted to onnx, the confidence level of key points will change and generally decrease

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@wenshuaishuai123 hello and thank you for reaching out to the YOLOv8 community! We appreciate your interest and willingness to contribute to the project. 

Regarding your issue with the confidence level of key points decreasing when converting YOLOv8pose pt to ONNX, this could potentially be caused by differences in precision between the two formats. Specifically, ONNX may use lower precision for numerical calculations than PyTorch. This can lead to small differences in the final output, which can impact the confidence levels of the key points.

One potential solution is to use the ONNX Runtime when running inference on the ONNX model. ONNX Runtime is designed to provide high performance and accuracy while also optimizing precision for different hardware platforms. This may help mitigate any precision-related issues and improve the accuracy of your predictions.

Again, thank you for your contribution to the YOLOv8 project! Please don't hesitate to reach out if you have any further questions or concerns.
