### ISSUE TITLE
How do the lr0 and lrf parameters work in Yolov8??

### ISSUE THREAD

**Issue by MathewsJosh** [ultralytics/ultralytics#2849]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I recently did some reading of the YOLOv8 documentation and source code to understand how the network parameters work, especially with regard to learning rates. However, I still have some questions:

1) The default learning rates have the same value (lr0 = lrf = 0.01). But which one is used by default during training, especially if they are different? I ask this because I made tests changing each one individually but could not identify which one the YOLO actually uses.

2) The default value of cos_lr is False. What is the impact of this cos_lr parameter if it is changed to true? Will it consider both lr0 and lrf learning rates?

**Comment by glenn-jocher** [comment]
@MathewsJosh thank you for your question regarding the lr0 and lrf parameters in YOLOv8. In YOLOv8, lr0 and lrf are both used during training to control the learning rate schedule. The lr0 parameter is the initial learning rate, and lrf is the final learning rate at the last epoch of training. By default, in YOLOv8, both lr0 and lrf have the same value (0.01), and this value is used during training. If you changed these values individually and observed no change in training behavior, then it is possible that other factors (such as the number of epochs or batch size) might be affecting the learning rate as well. 

Regarding the cos_lr parameter, if it is set to True, then the learning rate schedule will follow a cosine annealing pattern rather than a linear schedule. This can lead to a smoother learning rate schedule and potentially better results. Both lr0 and lrf are still used in the cosine annealing learning rate schedule. 

I hope that answers your questions. If you have any additional queries, please let me know.

**Comment by MathewsJosh** [comment]
Thanks for the answer @glenn-jocher, just adding another detail to the question: 

Do those three parameters (lr0, lrf, cos_lr) work in the same way you described for all YOLOv8 tasks (object detection, classification, segmentation and pose)?

**Comment by glenn-jocher** [comment]
Thank you for your follow-up question, @MathewsJosh. Yes, the lr0 and lrf parameters, as well as the cos_lr parameter, work in the same way for all tasks within YOLOv8. This includes object detection, classification, segmentation, and pose estimation. These parameters are used during training to control the learning rate schedule of the optimizer, which affects how weights are updated during backpropagation. 

When using YOLOv8 for different tasks, you may need to adjust other parameters, such as data format or model architecture, to optimize performance for a specific task. However, the learning rate schedule parameters (lr0, lrf, and cos_lr) are consistent across all tasks. 

I hope that answers your question. If you have any further inquiries, please don't hesitate to ask.

**Comment by MathewsJosh** [comment]
Hi @glenn-jocher, could you please explain how YOLOv8 behaves when lrf>=lr0 (e.g., lrf = 0.1 and lr0 = 0.001)? In that case will the network just use the higher or lower learning rate? Or will it schedule the learning rate downwards?

**Comment by glenn-jocher** [comment]
Hello @MathewsJosh, thank you for your question regarding the behavior of the learning rate schedule in YOLOv8 when lrf>=lr0. In such a case, YOLOv8 will still schedule the learning rate downwards over the course of training, even though the final learning rate (lrf) is larger than the initial learning rate (lr0). 

In general, the learning rate schedule in YOLOv8 starts at lr0 and decreases linearly with each epoch until it reaches lrf at the end of training. This linear decrease ensures that the learning rate scales appropriately over large batches and enables the model to converge more effectively. Therefore, even if lrf>=lr0, the system will still follow the linear learning rate schedule, which means that the learning rate will gradually decrease during training until it reaches lrf at the final epoch. 

I hope that answers your question. If you have any additional inquiries, please don't hesitate to ask.

**Comment by xenthm** [comment]
Hey @MathewsJosh, from what I understand, the initial learning rate is `lr0` and final learning rate is `lr0` * `lrf`. 

In `default.yaml`, 
```
lr0: 0.01  # initial learning rate (i.e. SGD=1E-2, Adam=1E-3)
lrf: 0.01  # final learning rate (lr0 * lrf)
```
This way, as long as `lrf`<1, the the final learning rate will be smaller than the initial. 

In fact, the valid values of `lrf` are between 0 and 1 inclusive. Setting `lrf`>1 raises the following error: `ValueError: 'lrf=1.1' is an invalid value. Valid 'lrf' values are between 0.0 and 1.0.`

In `cfg.__init__.get_cfg` (not sure if this is the correct way to format this), 
```
if not (0.0 <= v <= 1.0):
                    raise ValueError(f"'{k}={v}' is an invalid value. "
                                     f"Valid '{k}' values are between 0.0 and 1.0.")
```

**Comment by glenn-jocher** [comment]
Hello, @xenthm. To add to what you already know, the `lrf` parameter in YOLOv8 is a fraction of the initial learning rate specified in the `lr0` parameter, which serves as the maximum value for the learning rate throughout the training process. Setting `lrf` equal to 1 would keep the learning rate constant. In YOLOv8, the learning rate schedule is designed to decrease over time to help the model converge more effectively. If `lrf` is greater than `lr0`, the learning rate will still decrease over time according to the learning rate schedule and will not increase as you progress through training. 

For instance, let's assume `lr0 = 0.05` and `lrf = 0.1`. In this case, since `lrf` is less than `lr0`, the initial learning rate will be 0.05, and the final learning rate will be 0.05 * 0.1 = 0.005. The learning rate will gradually decrease linearly at each epoch until it reaches the final learning rate of 0.005 at the end of the training process.

I hope this helps to clarify the behavior of the learning rate schedule in YOLOv8 with respect to the `lrf` and `lr0` parameters. If you have any further questions, please let me know.

**Comment by Johan154** [comment]
Hello @glenn-jocher, I found some sources on the internet suggesting that an increasing learning rate enhances the model's performance. I personally don't think this is intuitive, but how do you view it? If I understand correctly Yolov8 doesn't support this, because the `lrf ` can't be higher than 1 and the` lrf=lr0*lrf`. Is this correct?

**Comment by lucvt001** [comment]
Hi @glenn-jocher, you say that the default of Yolov8 is such that the lr of final layers is always smaller than the lr of initial layers to help the model converge more effectively. However, shouldn't it be the case that the lr of final layers have to be larger so that it can be easily fine-tuned to the new dataset, while the lr of the initial layers have to be smaller to keep its pretrained characteristics?

**Comment by glenn-jocher** [comment]
@lucvt001 hi, thank you for your question. The learning rates `lr0` and `lrf` in YOLOv8 guide the overall learning rate schedule for the entire model during training, not specifically for any initial or final layers. 

When we discuss `lr0` as the initial learning rate and `lrf` as the final learning rate, we are referring to the learning rate at the start of the training process and the learning rate at the end of the training process. These are applied to the whole network.

The idea is to start with a relatively high learning rate (`lr0`) to make large changes in the model’s parameters initially, and then gradually to decrease the learning rate (`lrf`) to converge more carefully to a solution towards the end of training.

As for your point on fine-tuning, you're correct that often in transfer learning, learning rates can be set lower for the earlier part of the network to preserve more of its pre-trained characteristics. However, this specific idea doesn't apply to `lr0` and `lrf` settings as these parameters are controlling the learning rate schedule for the entire training process across all layers, not layer-specific learning rates.

I hope this helps clarify the role of `lr0` and `lrf` in the YOLOv8 training process! Let me know if you have further questions.

**Comment by lucvt001** [comment]
@glenn-jocher Thank you very much for your thorough response! It pretty much clarifies all the questions I have about lr0 and lrf!

**Comment by glenn-jocher** [comment]
Hi @lucvt001, I'm glad to hear that the explanations were helpful! It's important to fully understand how learning rate parameters and schedules impact the training process, as they significantly affect model performance. If you have any further questions about YOLOv8 or run into any issues during your model training, don't hesitate to ask. Happy training!

**Comment by Mehreganbeiki** [comment]
Hi, 

I have a question regarding the learning rates. Based on the default yaml file this is the default value for initial learning rate lr0: 0.01  ((i.e. SGD=1E-2, Adam=1E-3) which Adam I suppose would be AdamW. As I understand from the other conversation the model uses AdamW as an optimizer for 10,000 iterations and then switches to SGD with the initial learning rate of 0.01. So, based on the default values the AdamW initial learning rate has to be 0.001 but when I start running the code I see this in the command line:

 AdamW(lr=0.000714, momentum=0.9) with parameter groups 26 weight(decay=0.0), 27 weight(decay=0.0005), 27 bias(decay=0.0)
 
 Can you help me understand what is this learning rate and why is it different from the default learning rate in the yaml file? can you also explain the rationale behind opting for this unconventional learning rate value (I haven't change the default values)

**Comment by glenn-jocher** [comment]
@Mehreganbeiki hi there, 

The learning rate you're seeing (0.000714) in the AdamW optimizer is the result of the warmup phase of the learning rate scheduler. The warmup phase gradually scales up the learning rate from a very small value to the initial learning rate (`lr0`) over a certain number of initial iterations, which promotes more stable training and better convergence.

So, although you set the initial learning rate as 0.01 in your configuration file, during the warmup phase, the learning rate starts much lower and increases linearly with each training step until it reaches the `lr0` value. 

After the warmup, the learning rate scheduler manages the rest of the training process by gradually reducing the learning rate until it reaches the final learning rate (`lrf`).

Let me know if this clears up your question! If you have more questions, feel free to ask. Happy training!

**Comment by Mehreganbeiki** [comment]
Thank you @glenn-jocher,

I appreciate the effort you put into responding to the questions.

**Comment by glenn-jocher** [comment]
@Mehreganbeiki you're welcome! I'm glad I could help. If you have any other questions or need further clarification about YOLOv8, feel free to ask. Happy training!

**Comment by iturner72** [comment]
Hi,

@glenn-jocher I learned a ton from this thread, thank you for the thoughtfull responses. 

I'm currently experimenting with learing rate schedules and I want to ensure that the lr0 and lrf values I'm setting are working properly. In the results.csv file there are three columns: lr/pg, lr/pg1, and lr/pg2; what do these mean? I see that they are created in the trainer.py file, but I'm not sure how they are related to lr0 and lrf.

**Comment by glenn-jocher** [comment]
@iturner72 hello!

I'm glad you found the information in this thread helpful!

The `lr/pg`, `lr/pg1`, and `lr/pg2` columns in `results.csv` represent the effective learning rates of three different parameter groups in the YOLOv8 model during training. 

In YOLOv8, parameters are divided into groups, each with its own learning rate. These groups are defined in such a way that each group corresponds roughly to a different section of the network (for example, backbone, head etc.). 

The learning rates reported in these columns are the effective learning rates used at each training epoch, as adjusted by your learning rate schedule (e.g., cosine annealing, step decay, etc.) based on your `lr0` starting learning rate and `lrf` final learning rate.

Therefore, `lr/pg`, `lr/pg1`, and `lr/pg2` are not related to `lr0` and `lrf` in a direct sense, but `lr0` and `lrf` are the starting and ending points to calculate the learning rates in each of these parameter groups.

I hope this helps! Let me know if you have any other questions.

**Comment by iturner72** [comment]
Thank you very much @glenn-jocher, this clears up some confusion I had!

I found a similar issue earlier when you said that we can safely ignore the error message in issue #283
( UserWarning: Detected call of lr_scheduler.step() before optimizer.step(). )

I did safely ignore this error, and I get models that work well. I have the luxury of working on a project that only needs to identify a single class so I'm able to obtain mAP50=0.94 and mAP50_95=0.69 (nice) using transfer learning (I think). 

I am now working on hyperparameter fine tuning (I think); I'm starting by adjusting the learning rates. I was concerned that the error message meant that my lr0 value that I set was not being used. I thought this was the case since the training initializes with the default AdamW optimizer which has a learning rate of 0.002. 

I created a simple React App to track the training process. It pulls data from a PostgreSQL database which extracts values from both results.csv and args.yaml for each training run folder that is generated after training. I use the D3 JavaScript library to generate the plots. I currently have 3  plots:

1. mAP50 & mAP50-95 vss Epochs (similar to tensorboard)
2. train_box_loss & val_box_loss vss Epochs (similar to tensorboard)
3. lr/pg0 vs. Epochs

To test my theory that my learning rate (lr0) was not being used I ran an experiment comparing 2 training runs. Both training runs have exactly the same pre-trained model, dataset, and hyperparameters. The only difference is the lr0:

1. lr0=0.001
2. lr0=0.002

The image below shows the lr/pg0 plot of both training runs:

![lr_pg_train63_64](https://github.com/ultralytics/ultralytics/assets/56611737/888dd952-0fce-418c-a4ce-35d679ddd1e1)

The mAP and box_loss plots match almost exactly as well. Is it possible that this experiment is flawed since the lr0 values are not _that_ different, or is the warning that I'm receiving about the optimizer.step() causing this issue? I can share more plots, or run more experiments to further test this hypothesis if you're skeptical of my findings.

Thank you so very much for taking the time to assist me! :)

**Comment by glenn-jocher** [comment]
Hi @iturner72,

Thank you for you detailed explanation and sharing your experiment results!

From what I understand, you are concerned that the optimizer.step() warning might have caused your different `lr0` settings to have no effect. But as mentioned in the previous issue #283, the warning can be safely ignored and doesn't impact the learning rate applying mechanism. 

The learning rate is always used as initialized, and then as adjusted by the learning rate scheduler, irrespective of the warning message. This means that both the `lr0` values you've set (0.001 and 0.002) are correctly used during training initial phase.

Now, regarding your experiment and observations, the `lr0` values you've used are not drastically different. As learning rates can often exhibit a fairly wide range of value with similar results, it's indeed possible that the effect of doubling your starting learning rate might not be clearly visible in your results -- the convergence paths might be slightly different, yet lead to similar final model performance. 

What could provide a clearer picture of the impact of different `lr0` values is running the same experiment using a wider range of starting learning rates, say 0.001 and 0.01. This difference is more likely to show noticeable changes in the training process and final performance metrics.

Your React App approach to visualize different metrics like mAP, box loss, lr/pg is a good design choice. The combination of these plots can help to provide a full picture of the training process, and would be very helpful for comparing different hyperparameter settings.

I hope this explanation alleviates some of your concerns regarding the learning rate and the warning message. Thanks again for your detailed insights and experiment results, and don't hesitate to ask more questions if you have any. Happy training!

**Comment by iturner72** [comment]
@glenn-jocher Thank you very much for the detailed response! 

I tried your proposed experiment of using lr0=0.001 and comparing it to lr0=0.01 and I received the exact same lr/pg0 plots for both tests. I can share the plots or results.csv file if needed. But this has me skeptical of the lr0 being properly applied.

**Comment by glenn-jocher** [comment]
Hi @iturner72,

Thank you for updating us with your test findings.

Your experiment results, when the learning rate values differ by a factor of 10, should have resulted in significant differences in model performance and the learning rate behavior throughout training. The fact that you're observing the exact same learning rate trends with both lr0=0.001 and lr0=0.01, suggests that perhaps something else might be influencing your learning rates during training.

One possible explanation could be that there might be an issue with the learning rate scheduler or the optimizer setup. 

However, understanding the exact cause would require more detailed analysis. It would be helpful to double-check the relevant sections in your training code/setup to ensure everything runs as expected. Make sure the lr0 argument is correctly parsed and passed to the optimizer and learning scheduler. 

If you're certain that these settings are correct, then it may be worth spending some additional debugging time on your experiment setup to understand what's causing these identical learning rate plots.

I hope this sheds some light on your query! Let me know if you have more questions.

**Comment by mahamatnoumai** [comment]
@glenn-jocher @MathewsJosh @iturner72 @xenthm 
To continue with this conversation, I would like to change the default learning rate as well. 

let say I want to set my learning rate to lr0=1e-05, what is the best way to do that? 

This is what I did I set both lr0 and lrf to 1e-05. Hence, after lunching the training, I got the following attached below in the screenshoot. 

does this mean that the learning rate is set properly to lr0=1e-05. 

![image](https://github.com/ultralytics/ultralytics/assets/17758399/84a4805c-e7d7-46a2-8bd6-4155dc79f862)


Thank you

**Comment by iturner72** [comment]
> @glenn-jocher @MathewsJosh @iturner72 @xenthm To continue with this conversation, I would like to change the default learning rate as well.
> 
> let say I want to set my learning rate to lr0=1e-05, what is the best way to do that?
> 
> This is what I did I set both lr0 and lrf to 1e-05. Hence, after lunching the training, I got the following attached below in the screenshoot.
> 
> does this mean that the learning rate is set properly to lr0=1e-05.
> 
> ![image](https://user-images.githubusercontent.com/17758399/269213011-84a4805c-e7d7-46a2-8bd6-4155dc79f862.png)
> 
> Thank you

@glenn-jocher I think I may have discovered why I was getting similar plots for lr/pg0. It seems that if I didn't pass an argument for optimizer, then the default is 'auto.' I believe that this will override the lr0 input, at least that's what my experiments suggest. When I passed the agument optimizer='AdamW' the lr/pg0 plots are clearly different (for train1: lr0=0.005 and train2: lr0=0.0008) and I get different mAP and box_loss plots.

**Comment by glenn-jocher** [comment]
Hi @iturner72,

Thanks for sharing your question. Based on the screenshot you provided, it appears that you have set your learning rate (lr0) properly to 1e-05.

The 'Optimizer Bias LR' message display might seem a bit confusing, but what it's telling you is that the learning rate for the bias parameters in your model has been set to 1e-05. This value is equal to lr0 as expected.

Setting both lr0 and lrf to the same value generally means that the learning rate won't change during training, it will stay constant at that value. If that was your intention, then you have correctly set your learning rates.

@iturner72: Great job, that's a valuable discovery! It sounds like specifying the optimizer explicitly in the training script (optimizer='AdamW') has led to better differentiation in your lr/pg0 plots with different lr0 settings. Your observation suggests that if the optimizer is not specified, the training script might indeed override lr0 input with 'auto' settings. Hence, passing the optimizer argument directly does add more control over learning rates during training. Thanks for sharing your findings, that's helpful for the rest of us!

**Comment by mimansa1907** [comment]
@glenn-jocher
In the earlier explanations you stated that lr0 and lrf together decides the range of learning rate for our model. But in the explanation above you have mentioned

```Setting both lr0 and lrf to the same value generally means that the learning rate won't change during training, it will stay constant at that value. ```

This is applicable of **optimizer = auto**, right?

**Comment by glenn-jocher** [comment]
Sorry, lrf is multiplied by lr0 to get the final lr, so the lr will decrease linearly under this policy.

Hence the default values in place. I'd leave lrf alone and update lr0 for experiments.

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions or need further clarification, feel free to ask.

**Comment by AydinGarnet** [comment]
Hi, I have used "lr0=0.001, lrf=0.01". But the loss is very high. What should I do to reduce the loss and especially reduce dfl_loss?
My model is a combination of YOLO and EfficientNet and is used for face detection. I don't want to increase the number of epochs because I am using colb and I have time constraints for GPU.
![2](https://github.com/user-attachments/assets/1182f4b2-8090-48b8-b6da-08999c122bb3)
![1](https://github.com/user-attachments/assets/30fdea7b-96ce-42c4-aa5e-0344bc382beb)

**Comment by glenn-jocher** [comment]
To reduce the loss, especially `dfl_loss`, you can try lowering the learning rate further (e.g., `lr0=0.0005`) to stabilize training. Additionally, consider freezing earlier layers of EfficientNet using the `freeze` parameter to focus training on the YOLO layers, which may help reduce the loss within your time constraints. For more guidance, refer to the [training settings documentation](https://docs.ultralytics.com/modes/train/). Let us know how it goes!

**Comment by AydinGarnet** [comment]
Thank you for your response. I will make the changes you mentioned and let you know the result.

**Comment by AydinGarnet** [comment]
> To reduce the loss, especially `dfl_loss`, you can try lowering the learning rate further (e.g., `lr0=0.0005`) to stabilize training. Additionally, consider freezing earlier layers of EfficientNet using the `freeze` parameter to focus training on the YOLO layers, which may help reduce the loss within your time constraints. For more guidance, refer to the [training settings documentation](https://docs.ultralytics.com/modes/train/). Let us know how it goes!



![22](https://github.com/user-attachments/assets/89445800-af2d-4209-8a64-d588302fd2b0)
![Uploading 11.jpg…]()

**Comment by glenn-jocher** [comment]
@AydinGarnet thank you for sharing your detailed setup. To further reduce `dfl_loss`, apart from lowering `lr0` and freezing early layers, you could experiment with the `dfl` parameter in the loss function, which controls the weight of distribution focal loss. Reducing its value (e.g., `dfl=1.0`) may help. Additionally, ensuring proper data preprocessing and augmentations can improve training stability. For more on hyperparameter adjustments, refer to the [training configuration guide](https://docs.ultralytics.com/usage/cfg/). Let us know how the changes work for you!

**Comment by glenn-jocher** [comment]
Thank you for the update! To retrain using your `best.pt` weights, simply pass it as the `model` argument in your training script (e.g., `model.train(model='best.pt', ...)`). To further reduce losses, try fine-tuning hyperparameters such as learning rate, batch size, or `dfl` weight. Additionally, ensure your dataset annotations and augmentations are optimized for your task. For more insights, refer to the [training guide](https://docs.ultralytics.com/modes/train/).

**Comment by Hocwin** [comment]
<img width="738" height="1158" alt="Image" src="https://github.com/user-attachments/assets/132b89fd-456b-4613-b23a-38ec333a7252" />

Hello @glenn-jocher I want to ask about lr0 and lrf. in the documentation it says lr_final = lr0*lrf, so my question is when will this lr_final be achieved? Then are the results from lr_final definitely the same as the formula? for example lr0=0.0005 and lrf=0.01 then lr_final = 0.000005, will lr_final definitely = 0.000005? because when I checked results.csv it turned out the results weren't the same, why is that? even though the formula is lr0*lrf = lr_final

**Comment by glenn-jocher** [comment]
The “final LR = `lr0` × `lrf`” description is the theoretical target at the very end of the schedule, but in practice YOLO steps the scheduler once per epoch at the start of each epoch and logs `lr/pg0` once per epoch, so the last logged value (for epoch index `epochs-1`) will usually be slightly higher than `lr0 × lrf`, and if training stops early (patience/time) you never reach that target at all. A second source of mismatch is `optimizer='auto'`, which can override your `lr0` internally and build the schedule from its own base LR instead of the value you passed; the exact behavior, including warmup and the linear/cosine decay, is shown in the `_setup_scheduler()` implementation in the [trainer reference](https://docs.ultralytics.com/reference/engine/trainer/).
