### ISSUE TITLE
Using Apple MPS causes looping when trying to train a model

### ISSUE THREAD

**Issue by van-funplannr** [ultralytics/ultralytics#2854]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I have a MBP 2019 with i9 CPU and AMD 5500M. When I try to train my model with device="mps", it prints out the YOLOv8n summary, then optimizer:..., train:..., and then it loops printing those three outputs over and over while creating a new "train/, train2/, train3/" in /run/detect. And just like I expected, in Activity monitor, new python processes keep getting added until the following happens:
```
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.
```
I think for some reason, using device = "mps" makes it spin a new training process constantly. Using device="cpu" only runs one instance as expected.

If I try to remedy the problem by wrapping the training code in "if __name__ == __main__", then it only runs once but then MPS runs out of memory 2 minutes into the first epoch `RuntimeError: MPS backend out of memory`.

I'm using `Ultralytics YOLOv8.0.109 🚀 Python-3.9.6 torch-2.0.1 MPS`. Any possible ways to fix this? 

### Environment

Ultralytics YOLOv8.0.109 🚀 Python-3.9.6 torch-2.0.1 MPS
OS: Venture 13.3.1

### Minimal Reproducible Example

```
from ultralytics import YOLO

model = YOLO("yolov8n.yaml")

# Train the model
model.train(data="./datasets/sharks-marine-animals/data.yaml", epochs=100, imgsz=640, device="mps")

model.export()
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hi @van-funplannr  👋,

Thank you for taking the time to report this issue. We will be happy to help! 

It seems that there is an issue on your machine using "mps" as the device argument when training your model with YOLOv8. We recommend using "cpu" for training on any machine, while reserving "mps" for inference only.

You have mentioned that when you wrap the training code in `if __name__ == __main__` it only runs once, but then keeps giving `RuntimeError: MPS backend out of memory` error. To reduce memory usage we recommend you reduce `batch_size`, `img_size` and `subdivision` while running on `"mps"`.

Let me know if this helps! If you have any other questions, feel free to ask.

**Comment by glenn-jocher** [comment]
Just tested, unable to reproduce any problems on a 2022 M2 Macbook Air.

Ultralytics YOLOv8.0.109 🚀 Python-3.10.6 torch-2.0.1 MPS

**Comment by glenn-jocher** [comment]
@van-funplannr we've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by AaronLReid** [comment]
Hi @glenn-jocher , I have a near identical issue as the one above even when trying the sample code from the website. (All models are locally saved and referenced as it is an offline machine). 

I am not using an Apple product, but rather a Windows 10 machine with an NVidia Quadro T2000 (4GB) card.

If device = 'cpu' in train, this works fine, but sadly I have the same issue as @van_funplannr with gpu usage.

Similarly, if I wrap around with if __name__ == "__main__" I can get it to move past this loop, but I also run out of memory. Autobatching (batch = -1) indicates 20 is an okay batch size, so 16 is surprising if it OOMs on the first epoch.

The code completes if I reduce the batch size to 8 (albeit very slowly). 

Was this ever reproduceable or solved? My code snippet below. Happy to provide more detail/open a new issue if necessary. I would like to be able to run batch sizes of 16 or greater, as indicated by your Autobatch routine.

    path="YOLO_v8/"
    datapath="YOLO_v8\coco128.yaml"

    model = YOLO('yolov8n.yaml')

    # Load a pretrained YOLO model (recommended for training)
    model = YOLO(path+'yolov8n.pt')

    # Train the model using the 'coco128.yaml' dataset for 3 epochs
    results = model.train(data=datapath, epochs=3, val=False, batch=16, imgsz=640, device=0) 

    # Evaluate the model's performance on the validation set
    results = model.val()

    # Perform object detection on an image using the model
    results = model(path+'bus.jpg')

    # Export the model to ONNX format
    success = model.export(format='onnx')

**Comment by rromanchuk** [comment]
@glenn-jocher i can send you a repo/dataset to reproduce on exact same hardware (16G). OOM fatals throw before i can through a single epoch.   related to https://github.com/ultralytics/ultralytics/issues/2172 

Although, interestingly enough, i can't even get through simple sanity test via `yolo detect train data=coco128.yaml model=yolov8n.yaml epochs=100 imgsz=640 device=mps` because of 

> NotImplementedError: The operator 'aten::lerp.Scalar_out' is not currently implemented for the MPS device.

Which the stack trace below hints it could be optimizer specific, ie AdamW via default `optimizer=atuo`

```bash
pip3 install -U pip
pip3 install -U ultralytics
pip3 install -U --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu
```

```
optimizer: AdamW(lr=0.000119, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to datasets/runs/detect/train23

Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/8 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "/opt/homebrew/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ultralytics/yolo/cfg/__init__.py", line 407, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ultralytics/yolo/engine/model.py", line 373, in train
    self.trainer.train()
  File "/opt/homebrew/lib/python3.11/site-packages/ultralytics/yolo/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/opt/homebrew/lib/python3.11/site-packages/ultralytics/yolo/engine/trainer.py", line 343, in _do_train
    self.optimizer_step()
  File "/opt/homebrew/lib/python3.11/site-packages/ultralytics/yolo/engine/trainer.py", line 462, in optimizer_step
    self.scaler.step(self.optimizer)
  File "/opt/homebrew/lib/python3.11/site-packages/torch/cuda/amp/grad_scaler.py", line 315, in step
    return optimizer.step(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/optim/lr_scheduler.py", line 69, in wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/optim/optimizer.py", line 319, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/optim/optimizer.py", line 51, in _use_grad
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/optim/adamw.py", line 185, in step
    adamw(
  File "/opt/homebrew/lib/python3.11/site-packages/torch/optim/adamw.py", line 335, in adamw
    func(
  File "/opt/homebrew/lib/python3.11/site-packages/torch/optim/adamw.py", line 404, in _single_tensor_adamw
    exp_avg.lerp_(grad, 1 - beta1)
NotImplementedError: The operator 'aten::lerp.Scalar_out' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.
```

Explicitly changing optimizer to `SGD`,  or `RMSprop` look healthy, I'm using the branching in  `ultralytics/yolo/engine/trainer.py` to hint the problem code path.  `yolo detect train data=coco128.yaml model=yolov8n.yaml epochs=100 imgsz=640 device=mps optimizer=RMSProp`

According to google, looks like this is not unique or related to this repo, and mps/metal plugins are, present day, a complete mess.

```
sudo powermetrics --samplers gpu_power -i500 -n1
Password:
Machine model: Mac13,1
OS version: 22F82
Boot arguments: 
Boot time: Fri Jul 14 14:04:07 2023



*** Sampled system activity (Sat Jul 15 09:25:35 2023 -0500) (503.21ms elapsed) ***


**** GPU usage ****

GPU active frequency: 1197 MHz
GPU active residency:  70.74% (389 MHz: .47% 486 MHz:   0% 648 MHz: 5.0% 778 MHz: 2.0% 972 MHz: 6.9% 1296 MHz:  56%)
GPU requested frequency: (389 MHz:   0% 486 MHz:   0% 648 MHz: 4.9% 778 MHz: 3.5% 972 MHz: 5.0% 1296 MHz:  57%)
GPU idle residency:  29.26%
GPU Power: 12802 mW
```

**Comment by glenn-jocher** [comment]
@rromanchuk it seems like you are experiencing two separate issues with YOLOv8. Let's address each one:

1. **Out of Memory (OOM) error:** Based on your description, it appears that you are running out of memory when training with a batch size of 16 or greater. This issue can occur if the GPU does not have enough memory to handle the batch size. You mentioned that you are using an NVidia Quadro T2000 (4GB) card, which may not have sufficient memory for larger batch sizes. To solve this issue, you can try reducing the batch size to a value that your GPU can handle. In your case, you mentioned that a batch size of 8 works, so you can use that. Additionally, you can consider using a GPU with more memory or upgrading the existing GPU if possible.

2. **NotImplementedError with MPS device and AdamW optimizer:** You mentioned that you get a `NotImplementedError` related to the MPS device and the `aten::lerp.Scalar_out` operator when using the AdamW optimizer. This error message suggests that the `lerp` operation is not currently implemented for the MPS device. This issue seems to be related to PyTorch itself rather than the YOLOv8 code specifically. According to Google, there are similar reports of this issue with MPS and Metal plugins being problematic.

To work around this issue, you can try changing the optimizer to a different one that does not trigger this error. You mentioned that using the SGD or RMSprop optimizer works fine. You can specify the optimizer using the `optimizer` argument when running the `yolo detect` command, like `yolo detect train data=coco128.yaml model=yolov8n.yaml epochs=100 imgsz=640 device=mps optimizer=RMSProp`. This should allow you to continue training without encountering the `NotImplementedError`.

Please note that these solutions are workarounds and may not fully solve the underlying issues. It's also worth noting that the amount of memory required for training will depend on various factors, such as the model architecture, input image size, and dataset size.

**Comment by rromanchuk** [comment]
What LLM are you using 🤔

**Comment by Boaztheostrich** [comment]
I am having the same issue.

Here is my code:

`from ultralytics import YOLO

# this code is for training the model
# ultralytics v 8.0.134 is what roboflow likes

# Load a model
model = YOLO("yolov8n.yaml")  # build a new model from scratch n is the smallest model n s m l x

# Use the model
results = model.train(data="config.yaml", epochs=20, imgsz=640, device='mps')  # train the model
# epoch is like the number of iterations higher is better but takes longer
`

And the error:

`RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.`

Any help in resolving this issue would be appreciated

**Comment by glenn-jocher** [comment]
@Boaztheostrich the error message you're seeing is related to how Python handles multiprocessing. It seems like the code is trying to start a new subprocess before the current process has been fully initialized, which often leads to this `RuntimeError`.

The error message suggests a typical solution in Python, wrapping the entry point of your script with an `if __name__ == '__main__':` condition. This is generally good practice when working with Python scripts that may use multiprocessing or multithreading.

However, creating subprocesses can be more complex when working with MPS (Metal Performance Shaders) devices like you are. MPS is a computational framework by Apple, which can be somewhat idiosyncratic when it comes to subprocess handling.

If the problem persists after applying the recommended changes, it might be worth considering to set the `num_workers` argument to 0 in your DataLoader, effectively disabling multiprocessing. While this may slow down your data loading, it should prevent the error from occurring.

Also note, that the MPS backend in PyTorch might still have some limitations and not all features might be fully supported yet, compared to using CUDA on Nvidia GPUs.

**Comment by Boaztheostrich** [comment]
@glenn-jocher 

Here is my updated code following your instruction

```
from ultralytics import YOLO

def main():
    model = YOLO("yolov8n.yaml")  

    results = model.train(data="config.yaml", epochs=20, imgsz=640, device='mps') 

if __name__ == '__main__':
    main()
```

Using this code I was able to make it past that error however I encountered a new issue.

```
RuntimeError: MPS backend out of memory (MPS allocated: 3.62 GB, other allocations: 5.11 GB, max allowed: 9.07 GB). 
Tried to allocate 729.05 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
```

Any ideas on how to resolve this issue?

I saw that you offered a few ideas above just wasn't sure if anything has changed

**Comment by glenn-jocher** [comment]
@Boaztheostrich hello,

From the provided information, it appears that you are encountering an `OutOfMemoryError` when using the MPS backend. This error signifies that the MPS backend is running out of memory during the training process, hence it's unable to allocate the required memory for processing your input data.

The error message indicates that MPS is allocating about 3.62GB, whilst other allocations, probably the system's, amount to roughly 5.11GB. The maximum allowed allocation seems to go up to 9.07GB.

The runtime error message suggests setting the `PYTORCH_MPS_HIGH_WATERMARK_RATIO` environment variable to `0.0` to disable the upper limit for memory allocations. Be warned, however, that doing so might cause a system failure if your machine doesn't have sufficient memory.

Another possible solution to your problem would be to lower your batch size, as it directly impacts the amount of memory required for training. Reducing the image size `imgsz` can also help, but this may result in lower detection performance.

You might also want to reassess the structure of your model or inputs to minimize memory consumption, or consider using a device with more memory available if these changes don't help or negatively impact your model's performance.

I hope this helps. Please let us know if you continue to experience issues!

**Comment by davidd647** [comment]
My code is as follows:
```
model = YOLO("yolov8n.pt")
model.train(data="data.yaml", epochs=50, device="mps", workers=0)
```

I can get training to work, but the box_loss values are a lot higher (~10x) than if I don't use `device="mps"` in my .train call... The result is all detections are considered a part of the background.

I just don't use `device="mps"`... Even though I'd very much like my training processes to finish more quickly.

**Comment by glenn-jocher** [comment]
@davidd647 hello,

Thank you for sharing your experience with us and we appreciate your kind words about ultralytics! 

Now, regarding your issue with higher box_loss values while using MPS (Metal Performance Shaders) as the device in training, this might be due to the differences in how MPS and other devices (like a CPU or CUDA GPU) handle computations. Remember, MPS is Apple's framework for GPU-accelerated computation and might behave differently from standard CUDA-based GPUs.

In your case, the difference in performance might be due to precision. MPS might be using a different precision for the computations, which might affect the loss values and the subsequent performance of the model. 

It's important to remember, though, that the loss value itself isn't always directly indicative of the model's performance. It's the trends in loss decrease and the actual results when applying the model to a validation set that truly measure your model's effectiveness. 

If you're finding the training times longer without "mps", consider using an NVIDIA GPU if one is available, or exploring options to run your compute in the cloud, which might offer more firepower than an MPS device. 

I hope this provides some insight into your issue. We appreciate your feedback and enthusiasm - happy training!

**Comment by SudhanshuBlaze** [comment]
> @glenn-jocher
> 
> Here is my updated code following your instruction
> 
> ```
> from ultralytics import YOLO
> 
> def main():
>     model = YOLO("yolov8n.yaml")  
> 
>     results = model.train(data="config.yaml", epochs=20, imgsz=640, device='mps') 
> 
> if __name__ == '__main__':
>     main()
> ```
> 
> Using this code I was able to make it past that error however I encountered a new issue.
> 
> ```
> RuntimeError: MPS backend out of memory (MPS allocated: 3.62 GB, other allocations: 5.11 GB, max allowed: 9.07 GB). 
> Tried to allocate 729.05 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
> ```
> 
> Any ideas on how to resolve this issue?
> 
> I saw that you offered a few ideas above just wasn't sure if anything has changed

Hi

I am facing the exact same issue, were you able to solve it?

**Comment by glenn-jocher** [comment]
Thank you for updating your code. The `RuntimeError: MPS backend out of memory` issue you're encountering is related to the memory limitations of the MPS backend. To address this, you can try reducing the batch size or image size to lower memory usage. Additionally, setting the environment variable `PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0` can disable the upper limit for memory allocations, but use this with caution as it may cause system instability. Please ensure you are using the latest versions of the Ultralytics and PyTorch packages, as updates may include fixes for such issues.
