### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 189 but got size 187 for tensor number 1 in the list.

### ISSUE THREAD

**Issue by kylekam** [ultralytics/ultralytics#2856]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0% 0/10 [00:14<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/cfg/__init__.py", line 249, in entrypoint
    getattr(model, mode)(verbose=True, **overrides)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/model.py", line 207, in train
    self.trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/trainer.py", line 183, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/trainer.py", line 302, in _do_train
    self.loss, self.loss_items = self.criterion(preds, batch)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/v8/detect/train.py", line 76, in criterion
    return self.compute_loss(preds, batch)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/v8/detect/train.py", line 166, in __call__
    targets = torch.cat((batch["batch_idx"].view(-1, 1), batch["cls"].view(-1, 1), batch["bboxes"]), 1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 178 but got size 176 for tensor number 1 in the list.

### Environment

- YOLOV8m
- Google Colab for training
- Python 3.10.11

### Minimal Reproducible Example

I added the following augmentations to augment.py, but I only get the runtime error when I try to add any form of rotation through Rotation, ShiftScaleRotate, or Affine.
```
            T = [
                A.Blur(p=0.01),
                A.MedianBlur(p=0.01),
                A.ToGray(p=0.01),
                A.CLAHE(p=0.01),
                A.RandomBrightnessContrast(p=0.3),
                A.RandomGamma(p=0.0),
                A.ImageCompression(quality_lower=75, p=0.0),
                A.HueSaturationValue(p=0.3),
                A.ColorJitter(hue=0.3),
                A.Rotate(limit=180, p=0.5), # problematic
                A.HorizontalFlip(p=0.5),
                A.VerticalFlip(p=0.5)]
            self.transform = A.Compose(T, bbox_params=A.BboxParams(format="yolo", label_fields=["class_labels"]))
```
I run the following command line to start training.
```
            yolo task=detect mode=train model=yolov8m.pt data={DATASET}/custom.yaml epochs=400 imgsz=640 plots=True augment=False batch=32 save=True device=0 patience=75
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@kylekam hello, 

This error usually occurs when the dimensions of the tensors don't match, except for the first dimension (commonly the batch_size). Based on your error message, the expected size is 178 for tensor number 1 in the list, but you are getting 176. This could be a result of the mismatch in dataset images dimensions and the specified imgsz as an argument or a size mismatch in the custom.yaml dataset file.

One of the recent changes made in your code is adding the Rotation augmentation, are you sure you haven't edited any dimensions or used an incompatible value with other arguments or within the range of the added augmentations? You may want to check the dimensions of your dataset images, as it seems the dimensions of some of your batches or images is off.

I hope this helps you fix the issue. Let us know if it persists, and we will be happy to assist you.

**Comment by glenn-jocher** [comment]
@kylekam we've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by kylekam** [comment]
> @kylekam hello,
> 
> This error usually occurs when the dimensions of the tensors don't match, except for the first dimension (commonly the batch_size). Based on your error message, the expected size is 178 for tensor number 1 in the list, but you are getting 176. This could be a result of the mismatch in dataset images dimensions and the specified imgsz as an argument or a size mismatch in the custom.yaml dataset file.
> 
> One of the recent changes made in your code is adding the Rotation augmentation, are you sure you haven't edited any dimensions or used an incompatible value with other arguments or within the range of the added augmentations? You may want to check the dimensions of your dataset images, as it seems the dimensions of some of your batches or images is off.
> 
> I hope this helps you fix the issue. Let us know if it persists, and we will be happy to assist you.

My image dataset does have varying sizes (ex: 640x486, 1280x1024, ...) but my understanding was that yolov8 would resize all the images to the specified imagsz parameter. I am able to train without any issues when I don't use the rotation augmentation, but I get errors when I include it. All of the images I use are in the .jpg format.

**Comment by glenn-jocher** [comment]
@kylekam hello,

You are correct that YOLOv8 should resize all images to the specified imgsz parameter during training. However, when using data augmentation techniques, the dimensions of the augmented image(s) may differ from the original image dimensions. 

With respect to the specific error message you are getting, it is possible that the dimensions of the rotated images are not consistent with other images in your dataset. This could cause a size mismatch error when the model tries to train on a batch of images with inconsistent dimensions. 

One way to address this issue is to preprocess all images in your dataset to be of the same size before training. Alternatively, you may try to modify the rotation augmentation to ensure that the output dimensions of the augmented images remain consistent with the original image dimensions.

We hope this helps to resolve your issue. If you have any further questions or if the issue persists, feel free to let us know.

**Comment by kylekam** [comment]
I was able to get around this using some of the default augmentations available and following this thread [https://github.com/ultralytics/ultralytics/issues/2412](https://github.com/ultralytics/ultralytics/issues/2412). It doesn't seem like there's much support for Albumentation augmentations at the moment.

**Comment by glenn-jocher** [comment]
@kylekam thank you for bringing this up. While YOLOv8 does support data augmentations, some external augmentation libraries, such as Albumentations, have not yet been fully integrated into the training pipeline. Nonetheless, we are always looking to improve the functionality of our software, and appreciate your feedback on this. If there are any specific features or functionalities that you would like to see in future releases, please feel free to let us know, otherwise thank you for exploring YOLOv8, and keep us updated on your progress.

**Comment by zeobec** [comment]
Hi @kylekam, may I know if you have resolved those issues? cause I also got the same errors as yours after I modified yolov8 architecture

**Comment by kylekam** [comment]
@zeobec I ended up not implementing the augmentations through Albumentations. The augmentations that I used were through the params passed to the yolov8 run.
