### ISSUE TITLE
Torch Hub support for YOLOv8

### ISSUE THREAD

**Issue by hcdiekmann** [ultralytics/ultralytics#286]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

It would be nice to use YOLOv8 directly with the PyTorch Hub like YOLOv5 allows. 
```
model = torch.hub.load('ultralytics/yolov5', 'yolov5m') 
```

### Use case

For developers running YOLO in isolated filesystems (eg. ROS package)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
yes @hcdiekmann it's coming later this week. You'll be able to simple run model(file/np/tensor/PIL). Thanks for the feature request :)

**Comment by hcdiekmann** [comment]
Looking forward to it. Thanks for the amazing work

**Comment by shrroylee** [comment]
@AyushExel Any update?

**Comment by AyushExel** [comment]
Yes please check the updated usage on the readme or in detail here https://docs.ultralytics.com/predict/

**Comment by AyushExel** [comment]
Closing this issue as resolved. Please feel free to open if something isn't working

**Comment by garyfoohw** [comment]
@AyushExel Pardon my ignorance, I couldn't find any details of torch hub in the link you sent.

My end goal is to deploy a custom pretrained yolov8 in an offline environment, using Pytorch Android library only.
Not intending to import entire YOLO package as it's intended to run on Android.

Does the current YOLOv8 supports the above?

**Comment by miraut** [comment]
I'm in the same situation.
I would like to use some libraries with YOLOv8 which expects the API offered through/by PyTorch Hub (like YOLOv5 allows).
Is it possible? Is there a workaround without modifying all the expected API interface?
Thanks for all the effort in YOLOv8!

**Comment by AyushExel** [comment]
@miraut @garyfoohw No you cannot use torch hub to run inference. We are putting all efforts into making the ultralytics python interface super useful and accessible. You don't need to be in online environment to run inference and torch is the only large dependency of this library. So, if you've already installed torch on your device installing ultralytics won't take up a lot of space

**Comment by garyfoohw** [comment]
@AyushExel this means for now, yolov8 can only be run in the presence of the ultralytics package. No other ways around it.
Are there any plans in the future to make use of torch hub like yolov5?

**Comment by AyushExel** [comment]
No we're not focusing on torch hub support. YOLOv5 models can also be run through ultralytics framework

**Comment by mohsinmahmood12** [comment]
I have trained my yolov8 model and downloaded it best.pt now I want to use it in my application for detection what should I use is there tutorial or any guide available ?

**Comment by luizconrado** [comment]
Hi @AyushExel,

Sorry for my ignorance, however;
I am confused with everything I am reading so far.
I want to get my custom-trained YOLO v8 model and:
a) import it into PyTorch
b) convert it to TensorRT and use it with PyTorch.
Is there a way to achieve it? Can you tell me how? Can you please help me with it?

Thank you.

**Comment by AyushExel** [comment]
To load any custom trained or exported model:
```
model = YOLO("model.format")
```
You can interact with inference results here - https://docs.ultralytics.com/modes/predict/
Remember that exported models only support inference operation.

**Comment by luizconrado** [comment]
@AyushExel, Thank you for your reply.

I have read the documentation, however, my doubt still remains.

I am 100% able to train and use the trained models using the YOLO v8 package.
So, within the YOLO v8, everything is fine and working well.
The problem starts once I try to move into PyTorch (Hub) or OpenCV.

When using YOLO v5 I was able to export my models to:
a) PyTorch:
I would load it using the model = torch.hub.load('ultralytics/yolov5', .... - But without a hub configuration file I cannot do this with YOLO v8.
b) PyTorch using TensorRT:
I would export the model and load it just like mentioned above, however, I cannot do that due to the lack of the hub configuration.
c) OpenCV:
I was able to export the customer-trained model as an ONNX file using this command (python export.py --weights best.pt --include onnx --simplify --opset 12 --imgsz 640) and load it into OpenCV.
However, when I set the same flags (obviously changing it to the new format, etc.) for YOLO v8 and load it into OpenCV, I am not able to get the results of the predictions as before. Almost as if the results format/structure has changed completely.

So, my questions are:
a) Is there a way for me to load my trained models into PyTorch Hub? Is there a workaround? Can you show me, please?
b) Is there a way to export the model into ONNX so I can load it into OpenCV getting the same result structure as before? I was some comments online saying one should use a different opset, etc., but that has not worked for me.

Thank you

**Comment by luizconrado** [comment]
@AyushExel,
Thank you for your reply.

I have two questions left, if I may.
1)  Why can I not use Torch Hub? There are several things I wish I could do there and not in YOLO directly. Would it be too much work to create a hub config and do the adjustments necessary so this feature would still exist?

2) I have just tried the TensorRT engine loading it directly into YOLO v8. However, I got an error and not output. This code works just fine when I load the custom-trained model best.pt.
Here is what I have done: 
I have exported my working custom model using this command:
yolo mode=export model=custom_model_best.pt  device=0 format=engine

The process succeded (created first an ONNX and then the Engine file) and then I tried loading it into YOLO with the following command:
model = YOLO(model=yolov8n_custom_1920_engine_model_path, task='detect')
The import itself did not show any errors, but when I tried to get a prediction, I used the following command (the same as I use for the PyTorch model):
        detection_output_list = model.predict(source=camera.get_latest_frame(),
                                              show=False,
                                              device=0,
                                              conf=0.5,
                                              save=False,
                                              half=False,
                                              stream=False,
                                              verbose=True)
and I got several warnings and no prediction output. Here is what I got back:

Loading C:\Users\Felipe\Dropbox\dev\projects\python\YOLOv8_Models\YOLOv8_Models\yolov8n_custom_1920\weights\best.engine for TensorRT inference...
[03/24/2023-01:55:01] [TRT] [I] Loaded engine size: 19 MiB
[03/24/2023-01:55:01] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +1355, GPU +408, now: CPU 14962, GPU 1775 (MiB)
[03/24/2023-01:55:01] [TRT] [W] TensorRT was linked against cuDNN 8.6.0 but loaded cuDNN 8.5.0
[03/24/2023-01:55:01] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +26, now: CPU 0, GPU 26 (MiB)
[03/24/2023-01:55:01] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +3, GPU +8, now: CPU 14944, GPU 1785 (MiB)
[03/24/2023-01:55:01] [TRT] [W] TensorRT was linked against cuDNN 8.6.0 but loaded cuDNN 8.5.0
[03/24/2023-01:55:01] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +165, now: CPU 0, GPU 191 (MiB)
[03/24/2023-01:55:01] [TRT] [W] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage. See `CUDA_MODULE_LOADING` in https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
D:\PythonProjectsWindows\yolov8-object-detection\venv\lib\site-packages\tensorrt\__init__.py:331: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  bool: np.bool,
Exception in thread Thread-1 (get_predictions):
Traceback (most recent call last):
  File "C:\Users\Felipe\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Felipe\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\PythonProjectsWindows\yolov8-object-detection\ObjectDetection.py", line 165, in get_predictions
    detection_output_list = model.predict(source=camera.get_latest_frame(),
  File "D:\PythonProjectsWindows\yolov8-object-detection\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\PythonProjectsWindows\yolov8-object-detection\venv\lib\site-packages\ultralytics\yolo\engine\model.py", line 224, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "D:\PythonProjectsWindows\yolov8-object-detection\venv\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 227, in setup_model
    self.model = AutoBackend(model,
  File "D:\PythonProjectsWindows\yolov8-object-detection\venv\lib\site-packages\ultralytics\nn\autobackend.py", line 169, in __init__
    dtype = trt.nptype(model.get_binding_dtype(i))
  File "D:\PythonProjectsWindows\yolov8-object-detection\venv\lib\site-packages\tensorrt\__init__.py", line 331, in nptype
    bool: np.bool,
  File "D:\PythonProjectsWindows\yolov8-object-detection\venv\lib\site-packages\numpy\__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases were originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?
	
Do you know why this is happening?
Can you help me with this issue? That would be extremely appreciated.

Thank you once again.

**Comment by luizconrado** [comment]
@AyushExel ,

One more piece of information:
I tried updating my TensorRT to 8.6 and now I get a different error.
What I have installed is:
Python 3.10
ultralytics version 8.0.56
CUDA 11.7
CuDNN 8.8
TensorRT 8.6.0.12

The error I get is:
Loading C:\Users\Felipe\Dropbox\dev\projects\python\YOLOv8_Models\YOLOv8_Models\yolov8n_custom_1920\weights\best.engine for TensorRT inference...
[03/24/2023-02:44:03] [TRT] [I] Loaded engine size: 19 MiB
[03/24/2023-02:44:03] [TRT] [E] 1: [runtime.cpp::nvinfer1::Runtime::parsePlan::314] Error Code 1: Serialization (Serialization assertion plan->header.magicTag == rt::kPLAN_MAGIC_TAG failed.)
Exception in thread Thread-1 (get_predictions):
Traceback (most recent call last):
File "C:\Users\Felipe\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
self.run()
File "C:\Users\Felipe\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
self._target(*self._args, **self._kwargs)
File "D:\PythonProjectsWindows\yolov8-object-detection\ObjectDetection.py", line 165, in get_predictions
detection_output_list = model.predict(source=camera.get_latest_frame(),
File "D:\PythonProjectsWindows\yolov8-object-detection\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
File "D:\PythonProjectsWindows\yolov8-object-detection\venv\lib\site-packages\ultralytics\yolo\engine\model.py", line 224, in predict
self.predictor.setup_model(model=self.model, verbose=is_cli)
File "D:\PythonProjectsWindows\yolov8-object-detection\venv\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 227, in setup_model
self.model = AutoBackend(model,
File "D:\PythonProjectsWindows\yolov8-object-detection\venv\lib\site-packages\ultralytics\nn\autobackend.py", line 162, in init
context = model.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'

Once again, can you help me with this issue?

Thank you.

**Comment by luizconrado** [comment]
@AyushExel,

At this point, I don't know if I am helping or not, however, one more piece of information.
I reinstalled TensorRT 8.5.3.1
But in my project, I installed only one thing that doesn't match my TensorRT 8.5.3.1.
I installed tensorrt-8.6.0-cp310-none-win_amd64.whl
And now I get a different error, that in looking at older versions of YOLO, other people also had problems with.

So, this time I am using:
Python 3.10
ultralytics version 8.0.56
CUDA 11.7
CuDNN 8.8
TensorRT 8.5.3.1

tensorrt-8.6.0-cp310-none-win_amd64.whl installed instead of the original tensorrt-8.5.3.1-cp310-none-win_amd64.whl
Here we go:
Traceback (most recent call last):
File "D:\PythonProjectsWindows\yolov8-object-detection\ObjectDetection.py", line 235, in
update_screen()
File "D:\PythonProjectsWindows\yolov8-object-detection\ObjectDetection.py", line 216, in update_screen
for r in detection_output_list:
File "D:\PythonProjectsWindows\yolov8-object-detection\venv\lib\site-packages\torch\utils_contextlib.py", line 35, in generator_context
response = gen.send(None)
File "D:\PythonProjectsWindows\yolov8-object-detection\venv\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 153, in stream_inference
self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
File "D:\PythonProjectsWindows\yolov8-object-detection\venv\lib\site-packages\ultralytics\nn\autobackend.py", line 421, in warmup
self.forward(im) # warmup
File "D:\PythonProjectsWindows\yolov8-object-detection\venv\lib\site-packages\ultralytics\nn\autobackend.py", line 329, in forward
assert im.shape == s, f"input size {im.shape} {'>' if self.dynamic else 'not equal to'} max model size {s}"
AssertionError: input size torch.Size([1, 3, 640, 640]) not equal to max model size (1, 3, 1920, 1920)

Process finished with exit code 1

**Comment by glenn-jocher** [comment]
@FurkanGozukara currently, YOLOv8 does not support loading models via Torch Hub. This is because of a distinct architectural structure, making the implementation different from previous versions like YOLOv7.

You can instead load your YOLOv8 models directly using the Ultralytics package. The YOLOv8 package provides a seamless way for you to load your models and perform inference.

To load your trained or exported model, you just need to use the following method:

```python
model = YOLOv8("model.format")
```

Please note that the exported models only support the inference operation.

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara currently, YOLOv8 does not support loading models via Torch Hub. This is because of a distinct architectural structure, making the implementation different from previous versions like YOLOv7.
> 
> You can instead load your YOLOv8 models directly using the Ultralytics package. The YOLOv8 package provides a seamless way for you to load your models and perform inference.
> 
> To load your trained or exported model, you just need to use the following method:
> 
> ```python
> model = YOLOv8("model.format")
> ```
> 
> Please note that the exported models only support the inference operation.

thanks i made it work but i have problem with object detection

https://github.com/ultralytics/ultralytics/issues/4476#issuecomment-1687090965

**Comment by glenn-jocher** [comment]
@FurkanGozukara i am glad to hear that you were able to load your YOLOv8 model. As for the object detection issue you are encountering, let's try a few things. 

Ensure that the model has been trained adequately and the performance has been validated using the validation set. This helps confirm if the model has learned the features of the objects you want to detect.

Also, ensure the picture input to the object detection model is preprocessed (resized, normalized) in the same way it was during training. The model's understanding of the image data depends on consistent preprocessing.

Finally, the confidence threshold of the detection model could be adjusted. If it's too high, you might be missing out on valid detections. Lowering the threshold could lead to more detections, but also potentially more false positives. 

These could potentially solve the problem. If not, the issue might be more complicated and specific to your use case or dataset. You may need to provide more information or context about your specific issue.

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara i am glad to hear that you were able to load your YOLOv8 model. As for the object detection issue you are encountering, let's try a few things.
> 
> Ensure that the model has been trained adequately and the performance has been validated using the validation set. This helps confirm if the model has learned the features of the objects you want to detect.
> 
> Also, ensure the picture input to the object detection model is preprocessed (resized, normalized) in the same way it was during training. The model's understanding of the image data depends on consistent preprocessing.
> 
> Finally, the confidence threshold of the detection model could be adjusted. If it's too high, you might be missing out on valid detections. Lowering the threshold could lead to more detections, but also potentially more false positives.
> 
> These could potentially solve the problem. If not, the issue might be more complicated and specific to your use case or dataset. You may need to provide more information or context about your specific issue.

please dont do robo replies

your reply has 0 association with what i asked and what my problem is

**Comment by glenn-jocher** [comment]
@FurkanGozukara i apologize if my previous response did not directly address your concern. Let's refocus on your specific issue. You've indicated that you're encountering problems with object detection using YOLOv8. 

From my understanding, it appears that the model isn't detecting objects as expected. In diagnosing this, factors to consider include model training, the nature of the dataset it was trained on, the quality and relevance of the training data to the test data, and potential discrepancies in image preprocessing during training and inference phases. 

If the challenge persists, more detailed information about your case would be helpful in providing targeted solutions. This can include concrete examples of the issue, the exact nature of your use case, clarifying if it's a false positive or false negative issue, and what steps you've taken so far in trying to resolve the issues.
