### ISSUE TITLE
Confusion matrix issue

### ISSUE THREAD

**Issue by darouwan** [ultralytics/ultralytics#2861]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Validation

### Bug

With the latest code, it seems even the detection result is good, the confusion matrix all data are false negative. 
Maybe some part in confusion matrix calculation in recent change is wrong? 
![image](https://github.com/ultralytics/ultralytics/assets/2324213/2ec7832e-5918-4cfc-ac47-188e21f2fd0f)
![image](https://github.com/ultralytics/ultralytics/assets/2324213/2a9dd440-7f79-4ce7-95be-5da6f7d52329)

### Environment

Ultralytics YOLOv8.0.109  Python-3.9.7 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3060, 12288MiB)
Windows 11
Python-3.9.7

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@darouwan 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. Confusion matrix operates correctly in my tests:
```
!yolo train model=yolov8n.pt data=coco128.yaml epochs=3 imgsz=640
```
![image](https://github.com/ultralytics/ultralytics/assets/26833433/f188c734-4ed4-4955-92a7-65cf2b45521a)



We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃
