### ISSUE TITLE
RuntimeError: Dataset 'data.yaml' error ❌ 'data.yaml' does not exist

### ISSUE THREAD

**Issue by HarhadImadMohamed** [ultralytics/ultralytics#2888]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Ultralytics YOLOv8.0.109 🚀 Python-3.9.12 torch-2.0.1 CPU
yolo/engine/trainer: task=detect, mode=train, model=yolov8s.pt, data=data.yaml, epochs=10, patience=50, batch=16, imgsz=224, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=runs/detect/train
Traceback (most recent call last):
  File "/Users/macbookair/opt/anaconda3/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 123, in __init__
    self.data = check_det_dataset(self.args.data)
  File "/Users/macbookair/opt/anaconda3/lib/python3.9/site-packages/ultralytics/yolo/data/utils.py", line 195, in check_det_dataset
    data = check_file(dataset)
  File "/Users/macbookair/opt/anaconda3/lib/python3.9/site-packages/ultralytics/yolo/utils/checks.py", line 292, in check_file
    raise FileNotFoundError(f"'{file}' does not exist")
FileNotFoundError: 'data.yaml' does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/macbookair/opt/anaconda3/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/Users/macbookair/opt/anaconda3/lib/python3.9/site-packages/ultralytics/yolo/cfg/__init__.py", line 397, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/Users/macbookair/opt/anaconda3/lib/python3.9/site-packages/ultralytics/yolo/engine/model.py", line 366, in train
    self.trainer = TASK_MAP[self.task][1](overrides=overrides, _callbacks=self.callbacks)
  File "/Users/macbookair/opt/anaconda3/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 127, in __init__
    raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
RuntimeError: Dataset 'data.yaml' error ❌ 'data.yaml' does not exist

### Environment

yolo ios python

### Minimal Reproducible Example

!yolo task=detect mode=train model=yolov8s.pt data= data.yaml epochs=10 imgsz=224 plots=True

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by hg6185** [comment]
I have the same issue - could you solve it?

**Comment by glenn-jocher** [comment]
try data='coco8.yaml'

**Comment by nanunzoey** [comment]
@glenn-jocher I have the same issue!
Tried `data='coco8.yaml'`, but it's not working!

**Comment by glenn-jocher** [comment]
@nanunzoey i'm sorry to hear that you're experiencing difficulties. If changing the data setting to 'coco8.yaml' didn't do the trick, there might be a few things causing the issue. It could be that there's a problem with your setup: the Python environment, PyTorch version, etc. It's also possible that there's an issue with the dataset itself.

To understand the source of the problem and find the best solution, please ensure that your environment meets the prerequisites mentioned in the YOLOv8 documentation. Also, double-check your dataset, make sure it's correctly structured and properly referenced in 'coco8.yaml'.

If you still face the problem after these checks, could you please provide more details about the issue? The error message, your environment setup, and specific code configurations can offer helpful clues. 

Remember, the more detailed information you can offer, the more precise our assistance can be. Thank you!

**Comment by gwtakahashi** [comment]
I am experiencing the same thing. My data.yaml file is not recognized. I tried absolute paths as well as relative paths. I have the coco128-seg dataset and it's interesting that there is no data.yaml file with that, yet is runs without a problem. This is a real bug, and needs to be fixed.

**Comment by glenn-jocher** [comment]
@gwtakahashi if your `data.yaml` file is not being recognized, it might be due to one of the following issues:

1. **File location:** Ensure that the `data.yaml` file is located in the correct directory where the training command is run. If referencing it with a relative path, the relative path should start from the current working directory.

2. **File path in the command:** Make sure the path provided in the training command is correct. If using a relative path, it must be correctly specified relative to the directory from where you are running the command.

3. **Content of the data.yaml file:** The `data.yaml` file should be correctly formatted and include necessary fields such as `train`, `val`, `nc` (number of classes), and `names` (list of class names).

4. **Permissions:** Verify that you have read permissions for the `data.yaml` file and it is not restricted or locked by the system.

5. **Coco128-seg dataset:** The COCO128 dataset comes pre-configured within the repository which is why it might work without specifying the `data.yaml` file. For custom datasets, a correct `data.yaml` is required.

To resolve the issue, follow these steps:

- Check the existence and location of your `data.yaml` file.
- Verify the `data.yaml` content format and information.
- Use an absolute path in your training command to rule out any path-related issues. E.g., `data=/absolute/path/to/your/data.yaml`.
- Ensure you have appropriate permissions to read the file.
- Inspect the error message to gather additional insights as to what might be wrong.

If the issue persists after these troubleshooting steps, please gather the following information and reach out for further support:

- The directory structure of where you're running the command and location of the `data.yaml` file.
- The full training command used.
- The complete error message received.
- Details regarding the environment setup: Python version, PyTorch version, OS, etc.

We aim to make sure all users have a smooth experience with YOLO and your feedback helps us improve. Thank you for your patience and assistance in detailing this issue.

**Comment by gwtakahashi** [comment]
Thank you for replying. I got it to work by specifying absolute paths in
the model.train statement.  But I have another problem: I am using the
yolov8n.yaml model on a custom dataset with only 4 classes, yet when I call
the model.predict function on it, it uses the pretrain 80-class model for
the output. I cannot get it to put an object-detection box with proper
labels. For example, it labels a raccoon as a bear or cat. The training
process recognizes that the nc=4 instead of nc=80, but the model.predict
still outputs an 80-class prediction.

**Comment by glenn-jocher** [comment]
@gwtakahashi i'm glad to hear you managed to resolve the issue with the `data.yaml` file by specifying absolute paths. Regarding the problem with `model.predict` using the pretrained 80-class model: this typically indicates that the model weights being used for prediction haven't been updated with the weights from your custom trained model.

When you ran `model.train`, a new set of weights should have been saved, specific to your dataset with 4 classes. To use these weights for prediction, you need to ensure that `model.predict` is loading the correct weights file generated after training on your dataset.

Here's what you can do to troubleshoot this:

1. **Locate the trained weights**: After training your model, locate the `.pt` file that was saved. It will usually be in a directory such as `runs/train/exp` (where `exp` will be your experiment's name if specified, or an automatically generated one).

2. **Load the trained weights**: Make sure you're loading these weights when initializing the model for prediction. It might look something like this (adjust the path to your actual weights file):

```python
model = Model(weights='/path/to/trained/weights/best.pt')
```

3. **Check class labels**: Ensure the class labels used during prediction match the number of classes the model was trained on (4 in your case). You might need to specify a `data.yaml` or `*.yaml` file that has the correct class names corresponding to your trained model.

By ensuring that you're using the correct trained weights and the correct class labels, `model.predict` should produce output consistent with your dataset and not default to the COCO classes and labels.

If you're already doing this and still facing the issue, please provide:

- The command or code snippet you're using to perform prediction.
- The directory structure showing where your custom trained weights are saved.
- Confirmation that you are indeed pointing to the most recent and correct `.pt` file corresponding to your trained model.

Double-checking these details should help in addressing the issue. If the problem persists, feel free to share the above information, and I will be happy to assist you further.

**Comment by gwtakahashi** [comment]
Thanks for the suggestion, Glenn. However I tried it, and got the error
message:
SyntaxError: 'weights' is not a valid YOLO argument. Similar arguments are
i.e. ['weight_decay=0.0005'].

This is the statement I used:  Model =
model(weights="runs/detect/train15/weights/best.pt") since I defined my
model as "model" not "Model".
Guess it doesn't like "weights" as an argument.

**Comment by gwtakahashi** [comment]
OK, I played around with some more, and this is what I should have typed:

Model = YOLO("runs/detect/train15/weights/best.pt")
Model.predict("raccoon_cat.jpg", save=True, imgsz=320, conf=0.1)

**Comment by glenn-jocher** [comment]
@gwtakahashi Excellent, it looks like you’ve resolved the issue with the correct syntax for loading the model with the trained weights. Using `YOLO("path/to/weights.pt")` is indeed the right way to load the model in the YOLOv8 API before running predictions with `model.predict()`.

Make sure that `"runs/detect/train15/weights/best.pt"` is the path to the weights file obtained after your custom training session. That way, when you run `Model.predict()`, it should use the classes that your model was trained on, rather than the default 80 COCO classes.

It's critical that the loaded weights, model configuration, and class labels all align with the custom dataset you trained on to ensure accurate predictions with correct labels.

If everything is set up correctly, your predictions should reflect your dataset with 4 classes. If you keep encountering any issues or inconsistencies, please provide an outline of the steps you're taking along with any error messages, and we'll look into it further.

Happy to hear you're making progress, and should you have any more questions or run into additional challenges, don't hesitate to reach out. Keep up the great work with YOLOv8!

**Comment by gwtakahashi** [comment]
So here's what worked for me:

model = YOLO('yolov8n.pt')
model.train(data="/Users/<mysername>/Desktop/datasets/Raccoon_Detection.v5i.yolov8/data.yaml",
epochs=50, device="mps")
metrics = model.val()
path = model.export(format="onnx")

Then I defined a new model:
Model = YOLO("runs/detect/train2/weights/best.pt")     # load a new Model
with the best weights of the training results
Model.predict(source="raccoon.jpg", save=True, conf=0.5, boxes=True)

And I got a beautiful picture of a labeled raccoon, as desired.
[image: Screenshot 2023-11-12 at 20.37.18.jpg]
It would be nice to post this somewhere near the front so that newbies can
learn from worked examples. Thanks for your personal involvement as I doubt
I would have been successful without your help.
Gary

**Comment by glenn-jocher** [comment]
@gwtakahashi, I'm thrilled to see that you've successfully resolved your issues and are now getting accurate predictions with your custom trained model. Your perseverance and willingness to explore different solutions have paid off nicely. 

Your suggestion about providing worked examples for new users is a valuable one. It's through user experiences like yours that we can improve documentation and make the onboarding process smoother for those new to the YOLOv8 framework. User-friendly examples and guides that demonstrate a clear path from training to prediction can indeed significantly enhance the learning experience.

Your positive feedback about the support you received is greatly appreciated. The YOLO community and Ultralytics team are committed to supporting users like you. Your successful implementation and the sharing of your process will undoubtedly help others who may face similar challenges.

If you have any more insights, questions, or if there's anything else we can assist with as you continue your work with YOLOv8, please feel free to share. Keep up the great work, and happy detecting!

**Comment by KyrieRui** [comment]
I had the same problem now solved, mainly I need to combine the datasets_dir in the file 'settings.yaml' with the datasets_dir in your data file 'data.yaml' in test, train and val in your data file 'data.yaml'. yolo will be able to find the data file without any problem.

**Comment by glenn-jocher** [comment]
@KyrieRui i'm glad to hear you've resolved the issue. Correctly setting up your `settings.yaml` to align with the paths specified in your `data.yaml` is indeed essential for YOLO to locate your dataset for training, validation, and testing. Thanks for sharing your solution with the community! If you encounter any further issues or have questions, feel free to reach out. Happy detecting! 🚀

**Comment by a1noack** [comment]
> * Verify the `data.yaml` content format and information.

I also got around this error by using an absolute path instead of a relative path to reference my dataset's yaml file.

**Comment by glenn-jocher** [comment]
@a1noack great to hear that using absolute paths resolved the issue for you! Absolute paths can often prevent confusion that relative paths might introduce, especially when working in different directories or environments. If you have any more questions or run into other issues, don't hesitate to ask. Happy training with YOLOv8! 🎉

**Comment by Piyush-Mishra-12** [comment]
I had same issue, Check data.yaml file:
Check if this is written or not
test: ../test/images
train: ../train/images
val: ../valid/images
that's becuz it was written
test: ../test/images
train: dataset/train/images
val: dataset//valid/images

**Comment by glenn-jocher** [comment]
@Piyush-Mishra-12 the error message you're encountering indicates that the `data.yaml` file specified in your training command does not exist in the expected location. The `data.yaml` file is crucial as it contains the dataset configuration, including paths to the training and validation datasets, class names, and other dataset-specific settings.

Here's how you can resolve this issue:

1. **Check the Existence of `data.yaml`:**
   Ensure that the `data.yaml` file exists in the directory from which you're running the command. If it's in a different directory, you need to provide the correct path to it.

2. **Correct Path to `data.yaml`:**
   If the `data.yaml` file is located in a different directory, provide the full path to the file in the command. For example:
   ```bash
   !yolo task=detect mode=train model=yolov8s.pt data=/path/to/your/data.yaml epochs=10 imgsz=224 plots=True
   ```

3. **Create `data.yaml` if Missing:**
   If the `data.yaml` file does not exist, you need to create it. A typical `data.yaml` file looks like this:
   ```yaml
   # Example of data.yaml
   train: /path/to/train/images
   val: /path/to/val/images
   test: /path/to/test/images  # optional

   # number of classes
   nc: 80

   # class names
   names: ['class1', 'class2', ..., 'classN']
   ```
   Make sure to adjust the paths and class names according to your dataset.

4. **Check for Typos:**
   Double-check for any typos in the file name or path.

5. **Permissions:**
   Ensure that you have the necessary permissions to read the `data.yaml` file.

6. **Environment:**
   Since you're using an iOS Python environment, make sure that the file system paths are correctly accessible within that environment.

Once you've addressed these points, try running the training command again. If you continue to face issues, you may want to verify that the rest of your dataset files (images, annotations, etc.) are also correctly set up and accessible.

**Comment by taxueni1** [comment]
> I have the same issue - could you solve it?我有同样的问题 - 你能解决吗？ @HarhadImadMohamed

I have the same problem. Did you solve it?

**Comment by dexforint** [comment]
I had this problem in Kaggle while training. I SOLVED it by creating new dataset with only ONE file: data.yaml. Inside data.yaml you need to write absolute paths to your train/val/test folders

**Comment by glenn-jocher** [comment]
Hi @dexforint,

Thank you for sharing your solution! It's great to hear that you were able to resolve the issue by using absolute paths in your `data.yaml` file. This is a common approach to ensure that the dataset paths are correctly recognized, especially in environments like Kaggle.

For others experiencing similar issues, here's a quick recap of the steps:

1. **Create a `data.yaml` File:**
   Ensure that your `data.yaml` file contains absolute paths to your dataset directories. Here’s an example structure:
   ```yaml
   train: /absolute/path/to/train/images
   val: /absolute/path/to/val/images
   test: /absolute/path/to/test/images  # optional

   # number of classes
   nc: 80

   # class names
   names: ['class1', 'class2', ..., 'classN']
   ```

2. **Verify Paths:**
   Double-check that the paths specified in `data.yaml` are correct and accessible from your environment.

3. **Use the Latest Versions:**
   Ensure you are using the latest versions of `torch` and `ultralytics`. You can upgrade them using:
   ```bash
   pip install --upgrade torch ultralytics
   ```

If you continue to face issues, please provide a minimum reproducible example of your code. This will help us better understand the problem and offer a more precise solution. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions or need further assistance. Happy training! 🚀
