### ISSUE TITLE
I want to process 1280*640 images,  how I can precisely tell input parameter through --img or just skip it

### ISSUE THREAD

**Issue by frabob2017** [ultralytics/ultralytics#2896]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello YOLO team, I want to process some 1280*640 size images, how I can set this parameter?  I try to set it  in --img 1280 640 or  --img (1280 640), neither of them work for it, or could I skip --img and YOLO can automatically detect image size?

**Comment by frabob2017** [comment]
If I skip --img, it will use 640 as image input resolution.

**Comment by glenn-jocher** [comment]
@frabob2017 for PyTorch inference you pass the long side, i.e. `imgsz=1280`

**Comment by frabob2017** [comment]
> @frabob2017 for PyTorch inference you pass the long side, i.e. `imgsz=1280`

Thank you Jocher,  May I ask if set imagsz=1280, the YOLO will padding the image size from 1280*640 to 1280*1280.  Is there any difficulty for coding program view to implement imagsz=(1280, 640) or --img (1280 640)?

**Comment by glenn-jocher** [comment]
Hello @frabob2017, glad to be of help. Setting `imgsz=1280` will resize your input images' longer side to 1280 pixels, while keeping the original aspect ratio. This means that for your 1280x640 images, YOLO will simply scale-up the 640 side of your image to 1280, resulting in an output of 1280x640 pixels. 

As for setting `imgsz` to a tuple of values, this is not currently supported by YOLOv8. The `--img` parameter is designed to accept two values separated by a space, rather than a tuple. However, you can always write your own code to handle this tuple as two separate arguments if you wish to use it as a way of specifying the image size.
