### ISSUE TITLE
Resume training 

### ISSUE THREAD

**Issue by AjibolaPy** [ultralytics/ultralytics#2900]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

After i trained for 50 epochs, i was not satisfied with the performance, then i decided to train again for another 50 epochs. I noticed the weighs were reinitialized  and started training from scratch. How can i resume training?.

**Comment by glenn-jocher** [comment]
@AjibolaPy thank you for your question about resuming training in YOLOv8 after previously training for a certain number of epochs. In order to resume training from where you left off, you will need to specify the path to your previous checkpoint file as the starting point for the new training session. You can do this by setting the "--weights" parameter to the path of your previous checkpoint file when running the training script. This will load the weights from the previous training session and continue training from that point. I hope this helps! Let me know if you have any further questions.
