### ISSUE TITLE
What are the outputs of the Yolov8 model for SEGMENTATION

### ISSUE THREAD

**Issue by marcortiz11** [ultralytics/ultralytics#2953]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Can somebody tell me how to interpret the outputs of the YOLOv8 model for segmentation? 
I have analysed the architecture of yolov8n-seg.pt (trained on COCO) with Netron and I see there's two outputs:

- output1: 1x32x64x104
- output0: 1x116x2184

For **output1** I have a feeling that it's a representation of the mask pixel-by-pixel of the original image with lower resolution than the input. I don't understand where the 32 channels come from. Does it mean that only 32 categories can be detected at the same time?

For **output0** I guess the 2184 are the points representing the contours of every segmented object. I don't understand where the 116 comes from. The yolov8n-seg.pt says it segments 80 classes since it's trained with COCO datset, then why the 116?

Can somebody clarify this?

**Comment by glenn-jocher** [comment]
Hello @marcortiz11, thanks for reaching out to us! For output0 of YOLOv8, the 2184 number represents the total number of boxes predicted by the model, with each box being described by 116 values. These values consist of the x and y coordinates of the box's center, its width and height, 80 class confidences, and 32 mask weights. The masks in output1 are actually just prototype masks and do not represent the final masks. 

To get the final mask of a certain box, you can multiply each mask with its corresponding mask weight, and then sum all these products together. Additionally, you can apply Non-Maximum Suppression (NMS) on the boxes to get the subset of boxes with a specific confidence threshold. 

I hope this explanation helps! Please let us know if you have any more questions or concerns.

**Comment by HSVDO** [comment]
Hi @glenn-jocher thanks for your explanation so far!

But I'm still a litte bit confused on how to obtain the final masks.
So let's say we got a box in `output0` with `mask weights` (`mw1, mw2, ..., mw32`) and our 32 `masks` (160x160 "pixels") (`mask1, mask2, ... mask32`) in `output1`.

So is the final mask computed like this? So every value in mask1 is multiplied by mw1 and the sum is mask1(x1,y1) + mask2(x1,y1) + mask3(x1,y1) and so on?

`final_mask = mw1 * mask1 + mw2 * mask2 + ... + mw32 * mask32`

I found an python example implementation in https://github.com/ibaiGorordo/ONNX-YOLOv8-Instance-Segmentation/blob/main/yoloseg/YOLOSeg.py#L91 but I don't really understand the algorithm there as I am trying to implement the segmentation with Java.

Is there already an approximate estimate of when the final masks will be included directly in the output like mentioned in https://github.com/ultralytics/ultralytics/issues/480?

**Comment by SilverStarCoder** [comment]
> Hi @glenn-jocher thanks for your explanation so far!
> 
> But I'm still a litte bit confused on how to obtain the final masks. So let's say we got a box in `output0` with `mask weights` (`mw1, mw2, ..., mw32`) and our 32 `masks` (160x160 "pixels") (`mask1, mask2, ... mask32`) in `output1`.
> 
> So is the final mask computed like this? So every value in mask1 is multiplied by mw1 and the sum is mask1(x1,y1) + mask2(x1,y1) + mask3(x1,y1) and so on?
> 
> `final_mask = mw1 * mask1 + mw2 * mask2 + ... + mw32 * mask32`
> 
> I found an python example implementation in https://github.com/ibaiGorordo/ONNX-YOLOv8-Instance-Segmentation/blob/main/yoloseg/YOLOSeg.py#L91 but I don't really understand the algorithm there as I am trying to implement the segmentation with Java.
> 
> Is there already an approximate estimate of when the final masks will be included directly in the output like mentioned in #480?

@HSVDO , were you able to correctly understand and process the two outputs? I am very confused, even after reading various questions/answers related to this topic...

**Comment by glenn-jocher** [comment]
Hi @SilverStarCoder, 

The final mask computation indeed involves a weighted combination of the prototype masks, using the mask weights from `output0`. The value for each `final_mask` pixel is computed as a sum over the `mw * mask` products, giving `final_mask(x, y) = mw1 * mask1(x, y) + mw2 * mask2(x, y) + ... + mw32 * mask32(x, y)`. Each prototype mask contributes to the final mask based on its corresponding mask weight.

As for your question about including the final masks directly in the output, the team is considering it for future releases, but we currently don't have a specific timeline for this feature. We appreciate your patience and understanding, and we'll make sure to communicate any updates when they're available. 

I hope this clarifies some of your doubts. Let us know if there's anything else we can help with.

**Comment by SilverStarCoder** [comment]
@glenn-jocher  thank you for the reply. So the `final_mask` is still 160x160, and then needs to be upscaled  to match the original image size? Won't that mean it's a a very low resolution result if my original image was for example 1920x1080?

**Comment by glenn-jocher** [comment]
Hello @SilverStarCoder,

Yes, you're understanding it correctly. The final masks produced by YOLOv8 are indeed outputted at a 160x160 resolution regardless of your input image size. So, if your original image was in a higher resolution, such as 1920x1080, then you would have to upscale the mask to match that. 

The upscaling process might lead to lower resolution results. This is currently a limitation of the model architecture and something that we are actively working on addressing in newer versions of the model. 

In the meantime, even though the upscale might reduce the precision of segmentations to some extent, it will generally not inhibit the model's ability to distinguish between instances in the image. It should still give you a reasonable estimation of the locations and shapes of the different objects.

**Comment by SilverStarCoder** [comment]
Thank you again @glenn-jocher. I saw there is this in the config file: `retina_masks: False # (bool) use high-resolution segmentation masks`, but I am guessing this will not have an affect on the mask size based on a quick look at the code. I also saw there is a `mask_ratio` parameter and that you already gave a good explanation about it [here](https://github.com/ultralytics/ultralytics/issues/4369), but I can't find the where in the code it actually uses it. 

For a use-case I am trying out, I need to have a very accurate segmentation mask, and so far it seems that boundaries are relatively pixelated, perhaps due to the upscaling to a much larger image size. Do you have suggestions I can try out in the meantime?

**Comment by glenn-jocher** [comment]
Hi @SilverStarCoder,

Thank you for reaching out! You're correct in that the `retina_masks` flag in the configuration file won't affect the output mask size – it is currently designed to provide high-resolution masks for RetinaNet, and does not apply to the YOLOv8 model.

Regarding the `mask_ratio` parameter, it doesn't directly influence the mask size or resolution. Instead, it influences the trade-off between boxes and masks during training, with higher values leading the model to focus more on generating accurate masks at a possible expense of box accuracy.

For your use-case of needing very accurate segmentation masks, it sounds like the current low resolution masks may indeed be underperforming due to the upscaling step. Unfortunately, the model's mask output granularity is a limitation of its architecture. The best immediate solution may be to post-process the masks with a refinement step, such as smoothing out the edges or fine-tuning on a higher-resolution segmentation dataset.

It's also worth noting the balance between computational resources and accuracy: higher resolution masks would likely come at a significant increase in computational cost. 

The team is constantly working to improve model performance and add new features, and we appreciate your feedback. Your use-case is valuable to us and we are considering strategies for more accurate segmentation in future versions of the model.

Let me know if you have other questions or need further clarification.

**Comment by JS901** [comment]
@glenn-jocher I am just looking through the codebase and am attempting to alter the number of prototype masks from the default of 32. Please would you be able to direct me towards which file defines this parameter? 
Many thanks

**Comment by dulishu1999** [comment]
> Hello @marcortiz11, thanks for reaching out to us! For output0 of YOLOv8, the 2184 number represents the total number of boxes predicted by the model, with each box being described by 116 values. These values consist of the x and y coordinates of the box's center, its width and height, 80 class confidences, and 32 mask weights. The masks in output1 are actually just prototype masks and do not represent the final masks.
> 
> To get the final mask of a certain box, you can multiply each mask with its corresponding mask weight, and then sum all these products together. Additionally, you can apply Non-Maximum Suppression (NMS) on the boxes to get the subset of boxes with a specific confidence threshold.
> 
> I hope this explanation helps! Please let us know if you have any more questions or concerns.



> Hello @marcortiz11, thanks for reaching out to us! For output0 of YOLOv8, the 2184 number represents the total number of boxes predicted by the model, with each box being described by 116 values. These values consist of the x and y coordinates of the box's center, its width and height, 80 class confidences, and 32 mask weights. The masks in output1 are actually just prototype masks and do not represent the final masks.
> 
> To get the final mask of a certain box, you can multiply each mask with its corresponding mask weight, and then sum all these products together. Additionally, you can apply Non-Maximum Suppression (NMS) on the boxes to get the subset of boxes with a specific confidence threshold.
> 
> I hope this explanation helps! Please let us know if you have any more questions or concerns.

May I ask what the 1 in output0 [1, 116, 8400] represents

**Comment by dulishu1999** [comment]
May I ask what the 1 in output0 [1, 116, 8400] represents

**Comment by glenn-jocher** [comment]
@dulishu1999 hello,

Thank you for your question regarding the YOLOv8 model outputs.

In the output tensor you've mentioned with shape `[1, 116, 8400]`, the first dimension, which is `1`, typically represents the batch size. In this context, a batch size of `1` indicates that you are processing one image at a time through the network.

For YOLO models, including YOLOv8, the input images can often be processed in batches to improve throughput. This means you can feed multiple images into the network simultaneously, and the batch size would correspond to the number of images being processed.

In your case, since the batch size is `1`, it signifies that the model's predictions are for a single image. If you were to process, say, five images at once, the shape of the output would then start with a `5`, indicating the results for five images.

Each of the `116` elements in the second dimension corresponds to data for a single predicted bounding box, including its coordinates, objectness score, class probabilities, and other attributes. The third dimension of `8400` represents the total number of such predicted bounding boxes for the entire image, after the model has processed it.

I hope this clarifies the meaning of the dimensions in YOLOv8's output tensor. If you have any more questions or need further explanation, feel free to ask!

**Comment by Habib-Rehmn** [comment]
I am using a yolo segmentation model v8s. My model has only 1 class(sky). Here is the output shape of my model. 
I have converted this model to .tflite using yolo.

 name: Identity_1
tensor: float32[1,160,160,32]
Mask protos
location: 501   

it appears to be an image of 160 by 160 with 32 different values at each pixel  

here is some portion of the output

[[[[-0.07753567397594452, -0.20710693299770355, 0.23461437225341797, 0.5300124287605286, 0.24696356058120728, 0.20757406949996948,

how can i parse this output to make a final image to show where the sky is detected.

**Comment by glenn-jocher** [comment]
@Habib-Rehmn hi there! 🌤️

For your YOLOv8 segmentation model with only the sky as the class, the output shape `[1, 160, 160, 32]` signifies that you have 32 prototype masks of 160x160 pixels. These masks combined in a certain way give you the final segmentation mask for the sky.

To get the final mask, you generally need to apply a sigmoid function to these raw outputs to bring the values between 0 and 1, indicating the likelihood of each pixel belonging to the sky. If your output is already sigmoid activated (which is typically the case when converted to `.tflite`), you can skip this step. 

Here's a quick Python example of how you might approach this:

```python
import numpy as np

# Assuming 'output' is your model output of shape [1, 160, 160, 32]

# Combine the 32 channels to get a single channel representing sky likelihood
# One straightforward way could be to average across the channels
# Note: There are multiple ways to combine these depending on how the model was trained
mask = np.mean(output[0], axis=-1)  # Taking mean across the last dimension

# Now, mask contains average likelihood values of the sky
# To make a binary mask, decide on a threshold
threshold = 0.5  # This is arbitrary and may need adjustment
final_mask = (mask > threshold).astype(np.uint8)

# 'final_mask' is now a 160x160 binary mask where 1 indicates sky
```

This `final_mask` is binary, where '1' highlights sky regions, based on the chosen `threshold`. You might need to adjust the threshold based on how clearly the sky is detected in your specific scenarios.

Lastly, if your original image is larger than 160x160, you'll need to resize this mask back to the original dimensions to overlay it accurately. You can use OpenCV or similar libraries for resizing. Here's a quick snippet using OpenCV:

```python
import cv2

# Resize final_mask to your original image dimensions, say 1920x1080
resized_mask = cv2.resize(final_mask, (1920, 1080), interpolation=cv2.INTER_NEAREST)

# Now, 'resized_mask' is ready to be overlaid on your original image.
```

Hope this helps you visualize those open skies in your images! Feel free to ask if you've got more questions. ☁️✈️

**Comment by Habib-Rehmn** [comment]
import numpy as np
from PIL import Image

# Sample output from the model
output_2 = np.array([[[[-0.07753567397594452, -0.20710693299770355, 0.23461437225341797, 0.5300124287605286,...]]]])


# Sigmoid function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Range of threshold values
threshold = 0.49

# Reshape the output to (160, 160, 32) for easier manipulation
output_reshaped = output_2.reshape((160, 160, 32))

# Apply sigmoid function to the output
output_sigmoid = sigmoid(output_reshaped)

# Initialize an accumulator to store the cumulative binary mask
cumulative_mask = np.zeros((160, 160), dtype=np.uint32)

# Iterate over each feature
for feature in range(32):
    # Apply thresholding to create binary mask
    binary_mask = (output_sigmoid[:, :, feature] > threshold).astype(np.uint32)
    # Accumulate the binary mask
    cumulative_mask += binary_mask

# Create the final binary mask based on the logic
final_mask = (cumulative_mask >= 16).astype(np.uint8)  # 16 is half of 32, representing more than half of the masks

# Convert to PIL image
binary_image = Image.fromarray(final_mask * 255)

# Save the binary image
save_path = "./pic/final_mask.png"
binary_image.save(save_path)

# Inform the user that the final image has been saved
print("Final image saved successfully at:", save_path)


followed same approach but got i distorted mask.

**Comment by glenn-jocher** [comment]
@Habib-Rehmn hey there! 😊 It looks like you've got a great start with your code. If the mask appears distorted, it could be due to how the threshold and the final mask logic are applied. The `final_mask` calculation aggregates all binary masks expecting more than half to indicate the target class for a pixel to be classified as such. Here's a minor tweak to focus on a simpler approach that averages the probabilities before thresholding. This sometimes helps achieve a cleaner segmentation mask without needing to rely on the majority rule across all channels:

```python
# Instead of accumulating binary masks, let's average the sigmoid outputs
average_mask = np.mean(output_sigmoid, axis=-1)

# Then apply thresholding
final_mask = (average_mask > threshold).astype(np.uint8)

# Convert to PIL image for saving
binary_image = Image.fromarray(final_mask * 255)
binary_image.save(save_path)
print("Final image saved successfully at:", save_path)
```

This way, you're leveraging the average likelihood of sky across all feature maps to decide the mask, smoothing out individual discrepancies. Give it a shot and see how the result turns out! 🌤️

**Comment by Habib-Rehmn** [comment]
import numpy as np
from PIL import Image

# Sample output from the model
output_2 = np.array([[[[0.9476574063301086, 0.6402849555015564, 0.04089251160621643, -0.040269576013088226....]]]])


# Sigmoid function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Range of threshold values
threshold = 0.50


# Reshape the output to (160, 160, 32) for easier manipulation
output_reshaped = output_2.reshape((160, 160, 32))

# Apply sigmoid function to the output
output_sigmoid = sigmoid(output_reshaped)

# Instead of accumulating binary masks, let's average the sigmoid outputs
average_mask = np.mean(output_sigmoid, axis=-1)

# Then apply thresholding
final_mask = (average_mask > threshold).astype(np.uint8)

# Convert to PIL image
binary_image = Image.fromarray(final_mask * 255)

# Save the binary image
save_path = "./pic3/final_mask.png"
binary_image.save(save_path)

# Inform the user that the final image has been saved
print("Final image saved successfully at:", save_path)     

still a bit confused that how to get accurate mask i want to get coordinates in x,y where the sky class is detected

![image0](https://github.com/ultralytics/ultralytics/assets/124852616/9cd55db7-1faf-40f4-be47-5fa274395de2)
![final_mask](https://github.com/ultralytics/ultralytics/assets/124852616/53a937a0-183d-46fa-afb8-7451ba4ff841)

**Comment by glenn-jocher** [comment]
@Habib-Rehmn hey there! 😊 It looks like you're doing a great job with processing the segmentation output. To get the precise `x,y` coordinates for the sky class, you can use `np.where` on your `final_mask`. This function will provide the indices (which are your `x,y` coordinates) where the condition is `True` (i.e., where the sky is detected).

Here's how you can do it:

```python
# Find where the final_mask indicates the sky
sky_coordinates = np.where(final_mask == 1)

# sky_coordinates will be a tuple containing two arrays: one for all y indices, and another for all x indices
# You can zip them together to get (x, y) pairs
sky_coordinates_list = list(zip(sky_coordinates[1], sky_coordinates[0]))  # Note the order (1,0) for (x,y)

print("Coordinates where the sky is detected:", sky_coordinates_list)
```

This way, you'll have a list of `(x,y)` pairs indicating the pixels classified as sky. Just make sure to adjust the `threshold` value if you notice it filters too much or too little, as it significantly influences the binary mask accuracy.

Hope this clears things up and helps you get those precise sky coordinates! If you have more questions or need further help, feel free to ask. Good luck! 🌈

**Comment by Habib-Rehmn** [comment]
Thanks for your help @glenn-jocher but the output is not correct the mask contains only an arbitrary line. According to the logic I implemented, the part(s) of the image where the sky is detected will be white and everything else will be black.

I applied the sigmoid function and then took mean across last axis but still no good results.

Here are the 32 masks that i generated by using 1 channel at a time.



![t_0 49_f7](https://github.com/ultralytics/ultralytics/assets/124852616/22a4c0b8-872b-4380-8ea6-fdd3c4b54417)
![t_0 49_f8](https://github.com/ultralytics/ultralytics/assets/124852616/4a9ddfc0-f8ae-44e7-9cbb-35bb5d3ef9f3)
![t_0 49_f9](https://github.com/ultralytics/ultralytics/assets/124852616/b8f7cef5-711a-45a0-b6fd-3bbeca8cb074)
![t_0 49_f10](https://github.com/ultralytics/ultralytics/assets/124852616/ca9cd01e-6efd-4d1b-898d-671de400d371)
![t_0 49_f11](https://github.com/ultralytics/ultralytics/assets/124852616/baeb407f-6ac2-47e4-a8a7-402165163e78)
![t_0 49_f12](https://github.com/ultralytics/ultralytics/assets/124852616/2f07f589-cd49-430e-b398-41b99f09f33b)
![t_0 49_f13](https://github.com/ultralytics/ultralytics/assets/124852616/cce3eb0a-9bd9-4105-8c54-3757531d7732)
![t_0 49_f14](https://github.com/ultralytics/ultralytics/assets/124852616/de91cb62-0d36-4c72-9166-bd6914ec219a)
![t_0 49_f15](https://github.com/ultralytics/ultralytics/assets/124852616/144e1f11-1795-43f5-a66a-5d0cc6e34b66)
![t_0 49_f16](https://github.com/ultralytics/ultralytics/assets/124852616/fe78f9a2-20b4-4aa6-a3b5-5d9f7e48b9d1)
![t_0 49_f17](https://github.com/ultralytics/ultralytics/assets/124852616/72d428b0-9cac-4359-ab9e-c7b3212166ce)
![t_0 49_f18](https://github.com/ultralytics/ultralytics/assets/124852616/6556c8ef-f7a2-4dab-a8d4-fd7a36a7f115)
![t_0 49_f19](https://github.com/ultralytics/ultralytics/assets/124852616/5e0ae9fa-c580-4de9-a7e8-bf0e7e391508)
![t_0 49_f20](https://github.com/ultralytics/ultralytics/assets/124852616/81573633-44a5-4180-962e-ecd3d58caf27)
![t_0 49_f21](https://github.com/ultralytics/ultralytics/assets/124852616/eff6c17e-9bec-40ab-8909-94638f1c2d41)
![t_0 49_f22](https://github.com/ultralytics/ultralytics/assets/124852616/0377484b-3e6a-4c4b-858d-2bfaefdcdd28)
![t_0 49_f23](https://github.com/ultralytics/ultralytics/assets/124852616/5cc1ea3f-8b5a-4e86-9fcf-d6ce2e2e5f5b)
![t_0 49_f24](https://github.com/ultralytics/ultralytics/assets/124852616/f62b51ba-db68-45bf-9eb9-fdf26628a510)
![t_0 49_f25](https://github.com/ultralytics/ultralytics/assets/124852616/c3542d01-c823-40fb-bb5a-6a75f93081df)
![t_0 49_f26](https://github.com/ultralytics/ultralytics/assets/124852616/9726cca0-c1ef-4bca-a4cb-c35dc66b4741)
![t_0 49_f27](https://github.com/ultralytics/ultralytics/assets/124852616/2b7829b9-94d8-4568-8451-60211c236228)
![t_0 49_f28](https://github.com/ultralytics/ultralytics/assets/124852616/c5d69840-0b55-45b5-8fdf-5a8ea097a079)
![t_0 49_f29](https://github.com/ultralytics/ultralytics/assets/124852616/a9a36d21-1c3d-4f60-be72-e048b8abf78a)
![t_0 49_f30](https://github.com/ultralytics/ultralytics/assets/124852616/5942c54b-cb0e-4ab6-a96a-3338e9dbd4ad)
![t_0 49_f0](https://github.com/ultralytics/ultralytics/assets/124852616/743a2908-105b-4e6f-8db3-eb4d9d718d60)
![t_0 49_f4](https://github.com/ultralytics/ultralytics/assets/124852616/a5b489e2-b323-4008-a322-ca47e40d8ec0)
![t_0 49_f5](https://github.com/ultralytics/ultralytics/assets/124852616/0922e4f2-9473-49d0-b723-4bc98b4d884f)
![t_0 49_f6](https://github.com/ultralytics/ultralytics/assets/124852616/ab7c14c5-78eb-4973-b5bf-ee2622c3917b)
![t_0 49_f1](https://github.com/ultralytics/ultralytics/assets/124852616/bbab3a82-1b72-487c-84d1-7c44e40bed8b)
![t_0 49_f2](https://github.com/ultralytics/ultralytics/assets/124852616/59f64999-5c8b-46c2-935b-10cfd90d6e91)
![t_0 49_f3](https://github.com/ultralytics/ultralytics/assets/124852616/2cbfe479-fdad-47cf-95d7-94668123a63c)
![t_0 49_f31](https://github.com/ultralytics/ultralytics/assets/124852616/407f258c-9cc7-45ad-98a8-cfb8efc10a14)

**Comment by Habib-Rehmn** [comment]
and here is the mask that i got by taking mean across last axis. I also check around many thresholds.

![final_mask](https://github.com/ultralytics/ultralytics/assets/124852616/88eda86e-46c7-475f-821f-9d8c9264819c)

**Comment by glenn-jocher** [comment]
Hi @Habib-Rehmn 👋,

Thanks for sharing the details and the masks you've generated! From the masks you've posted, it indeed appears that direct averaging across channels might not be yielding the desired results for segmentation, especially for a single-class scenario like sky detection.

One approach you might explore is selecting a specific channel (or a few channels) that best represents your target class, based on visual inspection of those individual mask outputs you've already generated. Sometimes, among the multiple channels, a few are more representative of the segmentation task at hand. You could experiment with using just the most promising channel(s) to construct your final mask.

Here's a quick snippet on selecting a specific channel for the mask:

```python
# Example: Using the first channel that looks promising
selected_channel_mask = output_sigmoid[:, :, :, 0]  # Suppose 0th channel is most promising
final_mask = (selected_channel_mask > threshold).astype(np.uint8)

# Convert to PIL image for saving
binary_image = Image.fromarray(final_mask * 255)
binary_image.save(save_path)
```

Give this a try and adjust the channel index based on the mask that best captures the sky. Keep experimenting with different channels and thresholds to find the optimal combination!

Please let us know how it goes or if there's anything else we can help you with. Happy tinkering! 😊

**Comment by Habib-Rehmn** [comment]
are there any weights for these channels that i can use?  Like how much importance to give per channel?

**Comment by Habib-Rehmn** [comment]
so do the other output be used my model gives 2 outputs Identity
name: Identity
tensor: float32[1,37,8400]
Coordinates of detected objects, class labels, and confidence score
location: 476
Identity_1
name: Identity_1
tensor: float32[1,160,160,32]
Mask protos
location: 344

**Comment by glenn-jocher** [comment]
@Habib-Rehmn hi there! 🌞

Absolutely, the two outputs from your YOLOv8 model have distinct roles:

1. The first output (`Identity`) contains object detection data - coordinates, class labels, and confidence scores for each detected object. You'll parse this to understand **what** and **where** objects are in your image.

2. The second output (`Identity_1`) gives you the prototype masks for segmentation, indicating areas of interest in your image on a per-pixel basis.

To combine these outputs effectively, use the detection output to identify objects of interest and apply the prototype mask output to segment these objects within your image.

Here’s a small example to guide you through essential steps:
```python
# Assuming 'detections' and 'masks' are your outputs
for detection in detections:
    # Extract information from 'detections'
    x, y, w, h, class_id, confidence = parse_detection(detection)
    if confidence > threshold:
        # Apply the mask for the class
        mask = masks[:, :, class_id]  # Assuming class_id aligns with mask channels

# You'll need to adjust `parse_detection` to fit your data structure.
```

This simplifies the process, but depending on your exact requirements, you might adjust the `parse_detection` function or how you use `class_id` to select your masks. 

Hope this helps! Keep us posted on how it goes or if you have more questions.

**Comment by Habib-Rehmn** [comment]
I tried to sparse the first output of my model with shape 

name: Identity
tensor: float32[1,37,8400]
Coordinates of detected objects, class labels, and confidence score
location: 476

it seems that this output has 37 lists with 8400 values each.    "x, y, width, height and probability"  from a list of length 8400?

**Comment by Habib-Rehmn** [comment]
so can i get "x, y, width, height and probability" from a list of length 8400?

**Comment by Habib-Rehmn** [comment]
can't understand that how to parse 37 lists with 8400 values each to get this  x, y, w, h, class_id, confidence = parse_detection(detection) 

here is some sample of my first output 

[[[0.011465305462479591, 0.01539449580013752, 0.03224983811378479, 0.04296763986349106, 0.07653538137674332...]]]    it appears to contains 37 lists with 8400 elements each

**Comment by glenn-jocher** [comment]
@Habib-Rehmn hey there!👋 From your description, it sounds like you're looking into how to extract `x, y, w, h, class_id, confidence` from your model's output. Given the shape `[1, 37, 8400]`, it seems there are 37 features for each of the 8400 detected objects or points in the detection field of your model.

A quick way to parse this information might look something like this:

```python
# Assuming 'output' is your model's output with shape [1, 37, 8400]
output = output.squeeze(0)  # Drop the batch dimension, shape becomes [37, 8400]

# The indexes for each feature based on your model's output layout
x_idx, y_idx, w_idx, h_idx, conf_idx = 0, 1, 2, 3, 4  # These indexes might need adjusting

for i in range(output.shape[1]):  # Loop over 8400 detections
    x = output[x_idx, i]
    y = output[y_idx, i]
    w = output[w_idx, i]
    h = output[h_idx, i]
    conf = output[conf_idx, i]
    # Do something with x, y, w, h, conf
    # Class ID and further information would depend on remaining values and their interpretation
   
```

Keep in mind, the actual index positions for x, y, w, h, and confidence in each element list need to be adjusted based on how your model formats this output. This sample loop assumes the first few entries per detection point are x, y, width, height, and confidence respectively, which might vary for your specific model's output structure.

Hope this helps a bit! Let me know if you have other questions. 😊

**Comment by harsh194** [comment]
@glenn-jocher Hey Glenn, I am trying to do the segmentation in c++ as you have mentioned above for the python. But my output is different. It would be great if you could look into my code.
Thank you.

`
cv::Mat src = cv::imread(image_file);
cv::resize(src, src, Size(640, 480));

cv::Mat blob;
blob = cv::dnn::blobFromImage(src, 1 / 255.0, Size(640, 480), true);
net.setInput(blob);
std::vector<cv::Mat> outputs;

auto num = net.getUnconnectedOutLayersNames();

net.forward(outputs, num);

cv::Mat output_0 = outputs[0];
cv::Mat output_1 = outputs[1];

// output_1 corresponds to the output related to the segmentation result
cv::Mat mask_output_reshaped = output_1.reshape(1, { output_1.size[2], output_1.size[3], output_1.size[1] });

cv::Mat sigmoid_output = sigmoid(mask_output_reshaped);

// Calculate the average along the third axis (axis=2)
cv::Mat avg_mask(sigmoid_output.size[0], sigmoid_output.size[1], CV_32F);
for (int i = 0; i < sigmoid_output.size[0]; i++) {
	for (int j = 0; j < sigmoid_output.size[1]; j++) {
		float sum = 0.0;
		for (int k = 0; k < sigmoid_output.size[2]; k++) {
			sum += sigmoid_output.at<float>(i, j, k);
		}
		avg_mask.at<float>(i, j) = sum / sigmoid_output.size[2];
	}
}

// Create a binary mask where values greater than the threshold are set to 255 (uint8), otherwise 0
cv::Mat final_mask = cv::Mat::zeros(avg_mask.rows, avg_mask.cols, CV_8UC1);
for (int i = 0; i < avg_mask.rows; ++i) {
	for (int j = 0; j < avg_mask.cols; ++j) {
		if (avg_mask.at<float>(i, j) > threshold_float) {
			final_mask.at<uint8_t>(i, j) = 255;
		}
	}
}
`

**Comment by harsh194** [comment]
@glenn-jocher ,
It would be great if you could check it once.

**Comment by glenn-jocher** [comment]
Hi there! 👋

It looks like you're making good progress with your C++ code for segmentation. The approach you're taking to reshape the output and compute an average mask is on the right track. 

One thing to ensure is that the `sigmoid` function accurately represents each pixel's activation to differentiate between the classes and background in your segmentation task.

If you're encountering specific issues or have results to share, please provide more details so we can assist you better. And remember, the exact architecture of YOLOv8 and how you interpret its outputs can vary, so always adjust indices and processing steps according to your model's output format.

Keep it up, and let's fine-tune this together!

**Comment by harsh194** [comment]
@glenn-jocher Thank you for the message. For my model, the input is tensor: float32[1,3,480,640] and corresponding outputs are output0(tensor: float32[1,37,6300]) and output1(tensor: float32[1,32,120,160]). The class is six.

This is the code for calculation of sigmoid function. Is the implementation of sigmoid function correct?
cv::Mat sigmoid(const cv::Mat& x) {
	cv::Mat result;
	cv::exp(-x, result);
	result = 1.0 / (1.0 + result);
	return result;
}

This is the source image. Mask position is at the position of the screw.
![src](https://github.com/ultralytics/ultralytics/assets/133637871/5c7694d0-5ba9-40a2-a1b0-70819d4fcbbb)

This is the avg_mask image.
![avg_mask](https://github.com/ultralytics/ultralytics/assets/133637871/10cf0b92-7fe3-43a8-b1e6-940475435e68)

This is the final mask image.
![final_mask](https://github.com/ultralytics/ultralytics/assets/133637871/102dc799-e9ca-4a43-bbd9-bab6eaa87e62)

**Comment by harsh194** [comment]
@glenn-jocher ,
It would be great if you could check it once.

**Comment by glenn-jocher** [comment]
Hi there! 😊

Your sigmoid function implementation looks correct to me. It's a standard way to apply the sigmoid operation element-wise to a `cv::Mat` in OpenCV. Here's a quick validation of your approach:

```cpp
cv::Mat sigmoid(const cv::Mat& x) {
    cv::Mat result;
    cv::exp(-x, result);
    result = 1.0 / (1.0 + result);
    return result;
}
```

From your shared images, it seems like your approach to generating the mask is working. However, if the results aren't as expected, you might want to inspect the thresholding step or the way the mask is applied, adjusting the threshold as needed to better capture the objects of interest. 

Keep experimenting, and glad to help with any more questions!

**Comment by harsh194** [comment]
@glenn-jocher Thank you for the message.
But the changing threshold value also do not lead to the correct final mask.

**Comment by glenn-jocher** [comment]
Hi! It sounds like adjusting the threshold isn't resolving the issue with the final mask. Another angle to consider might be the scaling of input values before applying the sigmoid function, ensuring they fall within an appropriate range that allows the sigmoid function to perform effectively. Here's a quick check you can do:

```cpp
// Normalize the input before applying the sigmoid to ensure it's within a reasonable range.
cv::Mat pre_sigmoid_normalized;
cv::normalize(output1, pre_sigmoid_normalized, 0, 1, cv::NORM_MINMAX);
cv::Mat sigmoid_output = sigmoid(pre_sigmoid_normalized);
```

This normalization ensures the values are suitable for the sigmoid function to process meaningfully. Let's see if this brings you closer to the expected results! 😊

**Comment by harsh194** [comment]
@glenn-jocher Thank you for the reply. But the normalization also lead to the same result. No improvement is happening.

**Comment by glenn-jocher** [comment]
Hi there! 👋

It looks like normalization isn't resolving the mask issue. You might want to check that the outputs are being interpreted correctly. Double-check whether the output maps directly to the expected features such as class probabilities, positions, etc. Also, you could inspect the data to validate that the input images and learned parameters are in the expected format and range.

If the issue persists, please share further details on the output values or how you process these outputs. This could help isolate whether the issue lies in post-processing or earlier. Keep it up, troubleshooting can be challenging but leads to better insights! 😊

**Comment by harsh194** [comment]
@glenn-jocher the outputs are being interpreted correctly. The output directly maps to the expected features like class probabilities, positions, etc.

The output is processed in the given way.
cv::Mat src = cv::imread(image_file);
cv::resize(src, src, Size(640, 480));

cv::Mat blob;
blob = cv::dnn::blobFromImage(src, 1 / 255.0, Size(640, 480), true);
net.setInput(blob);
std::vector<cv::Mat> outputs;

auto num = net.getUnconnectedOutLayersNames();

net.forward(outputs, num);

cv::Mat output_0 = outputs[0];
cv::Mat output_1 = outputs[1];

// output_1 corresponds to the output related to the segmentation result
cv::Mat mask_output_reshaped = output_1.reshape(1, { output_1.size[2], output_1.size[3], output_1.size[1] });

cv::Mat sigmoid_output = sigmoid(mask_output_reshaped);

**Comment by zuixiaosanlang** [comment]
@Habib-Rehmn 
Hi, where can download the yolo weights for sky detection.
can you share, thanks
![image](https://github.com/user-attachments/assets/1f0bab1a-ea63-40be-b0c9-644d4d20c6cb)
