### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by batman7090** [ultralytics/ultralytics#2955]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

@all @glenn-jocher Hello YOLO community,

I am running the training in 
LINUX OS (22.04)
NVIDIA GeForce RTX 2080 (8GB)
python 10.8

I am getting error as shown below

RuntimeError: Dataset 'jaad_data.yaml' error ❌ 
Dataset 'jaad_data.yaml' images not found ⚠️, missing paths ['/home/beast/shamanth/yolo/yolo_dataset/jaad_data_without_prob/images\\val']
Note dataset download directory is '/home/beast/shamanth/yolo/yolo_dataset/jaad_data_without_prob'. You can update this in '/home/beast/.config/Ultralytics/settings.yaml'

thank you in advance

**Comment by Batman-97** [comment]
@glenn-jocher  Hello,

thank you replying. it was actually a mistake in jaad_data.yaml file, there was '\' in place of '/' which is accepted by LINUX.

thank you once again

**Comment by glenn-jocher** [comment]
@Batman-97, you're welcome! We're glad to hear that the issue was resolved and appreciate you providing the update. Yes, the backslash character is an escape character in LINUX, which is why switching it to a forward slash worked for you. If you have any more questions or concerns, feel free to ask anytime. Good luck with your YOLOv8 training!
