### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by abiralaashish7** [ultralytics/ultralytics#2959]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

For yolov8 pose estimation model, will the model give me keypoints if I feed it image and the bounding box information? Assume there are many pedestrians in an image, i want the keypoints for only one pedestrian in the bounding box? How do i do it?

**Comment by glenn-jocher** [comment]
@abiralaashish7 hello! For your question, yes, you can use the YOLOv8 pose estimation model to get keypoints for a pedestrian within a bounding box. YOLOv8 generates the bounding boxes in the detection stage, and then the pose estimation model predicts the keypoints within the bounding boxes. To get the keypoints for only one pedestrian, you can crop the image using the bounding box of the desired pedestrian and then pass the cropped image to YOLOv8. This way, the model will only detect the keypoints within that specific bounding box rather than all the pedestrians in the image. Let me know if you have any further questions!
