### ISSUE TITLE
Error occurs after each epoch - AttributeError: 'NoneType' object has no attribute '_free_weak_ref'

### ISSUE THREAD

**Issue by Pedro-Leitek** [ultralytics/ultralytics#296]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi

I'm getting an error everytime I try to train the model. The error occurs before the first epoch starts and repeats for each epoch

AttributeError: 'NoneType' object has no attribute '_free_weak_ref'

The training continues, but I'm not sure what is the impact of this issue. Plus I would like to see the metrics of the epochs on a list, which with these errors is not possible as the erros occupy the whole command line. I know this error occured in yolov5 thanks to a pytorch version that was not compatible. I would like to know what should be done regarding this on yolov8.

Thanks

**Comment by glenn-jocher** [comment]
@Pedro-Leitek 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by nejcmedved** [comment]
Hi, 

we had the same issue. 

Our issue was that we were using same virtual environment as for training yolov5. 

We solved that issue with creating separate virtual environment for yolov8

Best, Nejc

**Comment by mrljwlm** [comment]
Hi have you solved this problem, I got the same error using torch 1.11.0

**Comment by pderrenger** [comment]
@Pedro-Leitek great to hear that you were able to solve the issue by updating to the latest PyTorch release! 😊 This often resolves compatibility issues. If you encounter any further challenges or have more questions, feel free to ask!

**Comment by glenn-jocher** [comment]
@pderrenger Fantastic! Updating to the latest PyTorch release can indeed iron out these compatibility wrinkles. Should you bump into any more hurdles or have queries down the road, don't hesitate to reach out. Happy training! 🚀😄
