### ISSUE TITLE
Which the yolov8n model belong to FP16 or FP32， while running the CLI "yolo predict model=yolov8n.pt".

### ISSUE THREAD

**Issue by huangjiafengx** [ultralytics/ultralytics#2960]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi， Which the yolov8n model belong to？ FP16 or FP32， while running the CLI "yolo predict model=yolov8n.pt".

![image](https://github.com/ultralytics/ultralytics/assets/92708152/a95401a2-da4a-4fea-be10-8c7d8699ba74)

**Comment by Kayzwer** [comment]
the default will be fp32 afaik

**Comment by glenn-jocher** [comment]
Hello @huangjiafengx, thanks for reaching out! The default precision of the `yolov8n` model is `FP32`. However, the `yolo predict` command provides an option to specify the model precision by passing the `--half` flag for `FP16` or the `--float` flag for `FP32`. You can find more details on the `yolo predict` command options and usage in the [YOLOv8 Docs](https://docs.ultralytics.com/usage/cli/) under the `CLI` section. Let me know if you have any further questions!

**Comment by aka-sh74** [comment]
@glenn-jocher does track() support **_half_** argument as well?
something like model.track(source="https://youtu.be/Zgi9g1ksQHc", tracker='custom_tracker.yaml', half =True)?

**Comment by glenn-jocher** [comment]
@aka-sh74 yes, the `track()` function in YOLOv8 supports the `--half` argument. This argument allows you to enable mixed-precision inference using `FP16` precision. By setting `half=True`, the model will use `FP16` instead of the default `FP32` precision during tracking. This can help improve the performance and speed of the tracking process. Keep in mind that not all models support `FP16`, so make sure to check if the specific model you are using for tracking supports this option. Hope this clarifies your question! Let me know if you have any further inquiries.

**Comment by huangjiafengx** [comment]
OK, Thank you @glenn-jocher  @aka-sh74

**Comment by aka-sh74** [comment]
@glenn-jocher currently I'm using `Pytorch` model. does it support `FP16`?
does ultralytics have a documentation where we can check which model supports `FP16` or even `INT8`? if yes, please share that.

Also, is it possible to train our custom model in `FP16` rather than default `FP32`?

**Comment by glenn-jocher** [comment]
Yes, PyTorch models can support `FP16` using mixed precision training. You can find details on model precision support, including `FP16` and `INT8`, in the Ultralytics documentation. Training custom models in `FP16` is possible by enabling mixed precision training.
