### ISSUE TITLE
How do I use the pretained classify model(YOLOv8m-cls)? 

### ISSUE THREAD

**Issue by Abracdabra** [ultralytics/ultralytics#2972]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I use this model yolov8m-cls.pt I can not train it. I get this error RuntimeError: Dataset 'data.yaml' error  [WinError 3] The system cannot find the path specified: . When  I change the model to yolov8m.pt I don't get any error. I checked if the path is correct and I also used the full path and it still doesn't work.

**Comment by glenn-jocher** [comment]
@Abracdabra thank you for reaching out. It seems like you are encountering a path issue with the classify model. To use the pre-trained classify model, you simply need to load it using PyTorch and pass in an image. You do not need to train it. However, it seems like you're trying to train the model with a dataset.yaml file and encountering path issues. 

Can you confirm that the path to your dataset.yaml file is correct? It may be helpful to double check the file path and ensure that the data.yaml file is in the location you specified. You may also want to try specifying the full path instead of a relative one.

Please let me know if you have any further questions or if you need additional help.

**Comment by Abracdabra** [comment]
I used the full path and the file is in the correct location, but when I change yolov8m-cls.pt to yolov8m.pt or any other model that isn't a classify model it works. It somehow cannot find the path when I use the classify model. It says Dataset not found, missing path {path here}, attempting download. It try's to download a data.yaml.zip file and it fails then.

**Comment by glenn-jocher** [comment]
@Abracdabra It seems like you've encountered an issue when using the pre-trained classify model (yolov8m-cls.pt) and specifying the path to the dataset.yaml file. One possible reason for this issue might be that the classify model expects a different structure for the data.yaml file than other models, and there could be mismatches between the specified path and the expected file structure.

To resolve this issue, I recommend that you double check the structure of the data.yaml file required for the classify model with the GitHub repository's documentation or its maintainers. You may also want to try creating a new data.yaml file that conforms to the expected structure and specifying its path when using the classify model. 

I hope this helps! Please let me know if you have any further questions or concerns.
