### ISSUE TITLE
cv2.imshow not working with ultralytics 

### ISSUE THREAD

**Issue by guiaugustoga987** [ultralytics/ultralytics#2979]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Hi,

I'm trying a simple code, in which I load a model, made a detection and I need to exhibit the segmentation mask with cv2.imshow funcion.

The detection runs smoothly but cv2.imshow does not display anything. I'm not sure what is causing it since I have a desktop with same OS and similar versions of ultralytics and OpenCV and everything goes normal. 

If I import cv2 and load a simple image I can display it with cv2.imshow. But if I just import YOLO (from ultralytics import YOLO) the image does not display. I'm not sure what is causing this behaviour. I tried different versions of ultralytics/pytorch from pip and source with no success.

### Environment

OS : Ubuntu 20.04
Python : 3.8.10
Ultralytics : Version: 8.0.112

### Minimal Reproducible Example

```
#!/usr/bin/env python3

from ultralytics import YOLO
import cv2

model = YOLO("/home/ga/yolov8/weights/best1.pt")
img = cv2.imread('/home/ga/Documents/5.jpg')

cv2.imshow('a',img)
cv2.waitKey(1)  # 1 millisecond

result = model(img, verbose=True)

if result[0].cpu().masks is None :
    output = np.zeros((480, 640, 3), dtype="uint8")
else :
    output = (result[0].cpu().masks.data[0].numpy() * 255).astype("uint8")


cv2.imshow('a',output)
cv2.waitKey(1)  # 1 millisecond
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@guiaugustoga987 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

<img width="881" alt="Screenshot 2023-06-04 at 22 23 15" src="https://github.com/ultralytics/ultralytics/assets/26833433/c7365676-fb66-4435-87d2-7276e3fd27a1">

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃
