### ISSUE TITLE
model in diverging

### ISSUE THREAD

**Issue by mehran66** [ultralytics/ultralytics#301]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

The model starts training all files and after 35 epochs reaches a MAP of 0.87 but it does diverge afterward with very high loss values and MAP of  6e-05.

### Environment

Ultralytics YOLOv8.0.4 🚀 Python-3.10.6 torch-1.13.0
8 GPU/DDP
Ubuntu 21
AWS g5.48xlarge

### Minimal Reproducible Example

nohup yolo task=detect mode=train model=yolov8x.pt data=pt_data.yaml epochs=300 imgsz=1152 batch=64 cache=True workers=20 name='pt_od_1' device=\'0,1,2,3,4,5,6,7\' > ./runs/pt_od_1.out &

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mehran66 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by mehran66** [comment]
Never mind...I was running object detection on a dataset prepared for instance segmentation....it is interesting that the training was running all fine for 35 epochs!!!

**Comment by AyushExel** [comment]
No problem! I'm closing this issue as solved. Feel free to open if you face any other issues

**Comment by mehran66** [comment]
After using the data in the object detection format, I thought that problem is going to be resolved but faced the same issue. It seems that even when I was using the instance segmentation data, the code was automatically digesting that the right way.

**Comment by mehran66** [comment]
I found the source of this issue.....when I have too many background images, this issue happens. Removed all of the background images and the issue got resolved.

**Comment by pderrenger** [comment]
@mehran66 great to hear that you were able to identify and resolve the issue! If you encounter any further challenges or questions, feel free to reach out. Happy coding!
