### ISSUE TITLE
Saved Video Not Playable

### ISSUE THREAD

**Issue by varungupta31** [ultralytics/ultralytics#3016]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

A closed issue regarding the same issue #790 exist, but the problem continues.
I am on the latest version of YOLO, and running the prediction on a custom V8L model (finetuned). The video is created, the detections printed on the screen seem fairly accurate as well. However, the video is not playable (tried multiple players).

Also, the video is getting smaller in size after processing, why? (Initially 100MB --> YOLO --> 50MB), though I can see on the screen that all frames (1500) in the video have indeed been processed.

Im using the following command in python

```
from ultralytics import YOLO
model = YOLO(<path.pt>)
model.predict('vids/350.mp4', save=True, imgsz=(1080,1920), conf=0.1)
```

Kindly help,
thanks.

**Comment by glenn-jocher** [comment]
@varungupta31 hello! Thank you for using YOLOv8. 

Regarding the issue of the video not being playable after running object detection on it, we would need more information to determine the root cause of the problem. However, a possible solution could be to try using a different video codec or player. The issue with the video size decreasing after processing could be due to compression or downscaling during the processing.

If you provide more details, such as the specific error messages you are seeing, we may be able to assist you better.
