### ISSUE TITLE
Problem with CPU inference ?

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#3022]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

`deploy_model.predict(img_640, imgsz=640, conf=0.7,device="cpu") `

```

Ultralytics YOLOv8.0.98  Python-3.7.9 torch-1.13.1+cpu
Exception in thread AI_Start_Thread_1:
Traceback (most recent call last):
  File "D:\Python\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "D:\Python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "xx.py", line 1059, in dhsxt_AI
    deploy_model.predict(img_640, imgsz=640, conf=0.7,device=0)
  File "D:\Python\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\Python\lib\site-packages\ultralytics\yolo\engine\model.py", line 249, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "D:\Python\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 292, in setup_model
    device = select_device(self.args.device, verbose=verbose)
  File "D:\Python\lib\site-packages\ultralytics\yolo\utils\torch_utils.py", line 69, in select_device
    raise ValueError(f"Invalid CUDA 'device={device}' requested."
ValueError: Invalid CUDA 'device=0' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.

torch.cuda.is_available(): False
torch.cuda.device_count(): 0
os.environ['CUDA_VISIBLE_DEVICES']: None
See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no CUDA devices are seen by torch.

```

### Environment

YOLOv8.0.98  Python-3.7.9 torch-1.13.1+cpu
win11

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@monkeycc hello! Thank you for using YOLOv8 and reporting your issue. From the error message, it appears that there's an error with the device parameter used for cpu inference. Specifically, the parameter "device=0" should be replaced with "device='cpu'" for cpu inference. This can be easily fixed by changing the "device" parameter in your code accordingly.

Also, I noticed that you're using an older version of PyTorch (1.13.1+cpu). We recommend using the most updated version of PyTorch to avoid compatibility issues and ensure optimal performance.

I hope this helps! Let us know if you have any other questions or issues.
