### ISSUE TITLE
 predict stops early due to WARNING ⚠️ NMS time limit 0.550s exceeded

### ISSUE THREAD

**Issue by maheeetaaa** [ultralytics/ultralytics#3031]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have trained a custom model and when I want to test it on a video in colab I get the following warning
WARNING ⚠️ NMS time limit 0.550s exceeded
 and after that prediction stops and the file isnt also saved properly!  This only happens with yolov8, I trained yolov5 and did not have this issue, why is that and how can I fix it? 

`model = YOLO('/content/googledrive/MyDrive/yolov8/train3/weights/best.pt')  # load a custom model

# Predict with the model
result = model('/content/googledrive/MyDrive/test/Demos.mov', conf = 0.3 , save = True, device=0 )`

**Comment by glenn-jocher** [comment]
@maheeetaaa NMS time limits are in place to prevent long running NMS during validation/prediction, which is likely an indicator of something wrong in your training. You can modify these here, but the real issue is likely in your custom training routine that is producing excess false positives:

https://github.com/ultralytics/ultralytics/blob/01273c5ca1ecb50cc6f3f8dcc6b2434c61ecbd65/ultralytics/yolo/utils/ops.py#L136-L179
