### ISSUE TITLE
why the all P and R is 1?

### ISSUE THREAD

**Issue by LiangYong1216** [ultralytics/ultralytics#3061]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When training the YOLOv8 pose estimation network, all the metrics were 1 (I can understand the metrics for the box, because the center point of the entire image is the center point of the object, and the width and height are the width and height of the object). I only had one class, but I couldn't understand the metrics for the pose, which started at 0 and after a period of training, all became 1. However, after comparing with the original labels, I found that there is still room for optimization and it is not the optimal point. So my first question is: why did all the metrics become 1? My second question is: what aspects can be considered to improve the accuracy of the points? thank you!!!!

### Additional

the training image：
![training](https://github.com/ultralytics/ultralytics/assets/66230782/37759d94-7e67-4321-8e88-27f0cde82368)
the label is as follows:
![label](https://github.com/ultralytics/ultralytics/assets/66230782/b140532a-5969-4369-be86-f90dcc4c4d98)
the results is follows:(the label is blue and green)
![19080560_P1](https://github.com/ultralytics/ultralytics/assets/66230782/af13fecb-02bc-4a83-b0cc-d34048b17d93)

**Comment by LiangYong1216** [comment]
Additional information:
the class is one, the number of keypoint is 52.

**Comment by glenn-jocher** [comment]
Hello @LiangYong1216! Thank you for reaching out to us on the Ultralytics YOLOv8 repository. In regards to your question about the metrics for pose estimation, it is difficult to provide a specific answer without more information about the model you are using, the loss function, and the dataset. However, generally speaking, it is possible for all metrics to be 1 if the model is able to perfectly predict all the keypoints for all images in the validation set. 

Regarding your second question, there are several factors that can influence the accuracy of the pose estimation. Here are a few points to consider: 

1. Model architecture: Ensure that the pose estimation model has an appropriate architecture for the dataset you are using.

2. Loss function: Make sure that the loss function used during training is appropriately designed for pose estimation. 

3. Dataset: Verify that the images and labels in your dataset are of good quality and accurately capture the keypoints. Additionally, it is important to have a diverse and balanced dataset that includes different poses, backgrounds, and lighting conditions.

4. Hyperparameters: Optimize the hyperparameters to get the best performance from your model. 

5. Regularization techniques: Use techniques like data augmentation, weight decay, dropout, and early stopping during training to prevent overfitting and improving the generalization capability of the model.

I hope this information is helpful to you. If you have any further questions or concerns, please feel free to ask!

**Comment by LiangYong1216** [comment]
hi @glenn-jocher ,thanks for your reply

1. the model i used is **yolov8s-pose.pt**
2. my hyperparameters are as follows: 
yolo/engine/trainer: task=pose, mode=train, model=yolov8s-pose.pt, data=header.yaml, epochs=1000, patience=50, batch=192, imgsz=640, save=True, save_period=-1, cache=False, device=0, 1, 2, 3, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, fraction=1.0, profile=False, overlap_mask=True, mask_ratio=4, dropout=0.5, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.4, translate=0.1, scale=0.5, shear=0.3, perspective=0.0005, flipud=0.5, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=runs/pose/train56
Overriding model.yaml kpt_shape=[17, 3] with kpt_shape=[52, 3]

3.my datasets : 
train images:1367
val images:153
each image has 52 keypoints and is labeled correctly,the label file is shown in figure 2

4.loss function: i didn't change the loss function, my ultralytics version is 8.0.114

i use python file to train the model:

from ultralytics import YOLO
import os
os.environ["MKL_SERVICE_FORCE_INTEL"] = "1"
os.environ['OMP_NUM_THREADS'] = '1'
model = YOLO('yolov8s-pose.pt')  # load a pretrained model (recommended for training)
model.train(data='header.yaml', epochs=1000, imgsz=640, batch=192, device="0, 1, 2, 3", dropout=0.5, degrees=0.4, shear=0.3, fliplr=0.5, flipud=0.5, perspective=0.0005)

when the epoch=60, all the Percision(P) and Recall(R) is 1, but the results is not good, the label is blue and the prediction is green, i did some data enhancements, including rotation, flipping, etc......, so it shouldn't be the cause of overfitting,how should i improve the performance , can you give me some advice? Thank you!
![image](https://github.com/ultralytics/ultralytics/assets/66230782/68b269ad-72dd-44cd-93dc-05ab3dd1d38e)

**Comment by akashAD98** [comment]
@LiangYong1216 make sure that there is no any data leakage, if same train data present in test data chances of getting high Recall & prec is more, also you can add regulation or dropout

**Comment by glenn-jocher** [comment]
Hello @LiangYong1216! Thank you for providing detailed information about your model and dataset. It's good to hear that you have already performed data augmentation and checked the dataset labels. 

Regarding the issue you mentioned, when the precision and recall are both 1 but the results are not good, this could be due to several factors. It's possible that there is some overfitting or that the model is not learning the right features to perform the pose estimation task. To address this, you can try adding regularization techniques such as weight decay or dropout to prevent overfitting and generalize better to unseen data.

Additionally, you may want to try modifying the model architecture or the loss function to better suit your dataset and task. 

To further diagnose the issue with the model, you can try visualizing the outputs and predicted keypoints on some sample test images using a visualization tool. This can help to identify if there are any systematic errors that the model is making.

I hope this information will be helpful and if you have any further questions or concerns, please don't hesitate to ask!

**Comment by syz825211943** [comment]
@LiangYong1216  Have you solved this problem? I met the same problem, the model achieve high precision and recall score on training set but works badly on test set.

**Comment by glenn-jocher** [comment]
@syz825211943 hello! This sounds like your model might be overfitting on the training data, causing it to perform poorly on unseen test data. Overfitting often happens when a model learns the training data too well, including its noise and outliers, failing to generalize on new data.

Here are a few strategies you can try:

1. **Data Augmentation**: This is a powerful way to increase the diversity of your training data. Techniques can include rotations, scaling, flips, and color changes. It seems you've tried this, but there may be more methods to experiment with.

2. **Regularization**: Adding some form of regularization might help. This could be L1 or L2 regularization, dropout layers, or early stopping.

3. **Optimizing Hyperparameters**: You might see improvements by optimizing different hyperparameters, such as learning rate, batch size, or the architecture of the model itself.

4. **Cross-validation**: Use cross-validation techniques to make better use of your dataset and to ensure that your model is not just fitting to a specific arrangement of the data.

5. **Use a Simpler Model**: If your model is very complex, it might help to simplify it. A simpler model might reduce overfitting.

Remember, achieving high precision and recall on the training set is not an end in itself, you need a model that generalizes well on unseen data.

Hope these suggestions help you in improving your model's performance. Let us know how it goes and feel free to ask if you have any other questions!

**Comment by LiangYong1216** [comment]
> 

No, the problem is not solved, I used a lot of data enhancement and overfitting prevention methods, such as dropout, bn, regularization, but it still did not work, and compared to the original label, there is still room for optimization, and finally I changed a model and used CPN for key point detection, and the effect was not bad

**Comment by LiangYong1216** [comment]
> 

No, the problem is not solved, I used a lot of data enhancement and overfitting prevention methods, such as dropout, bn, regularization, but it still did not work, and compared to the original label, there is still room for optimization, and finally I changed a model and used CPN for key point detection, and the effect was not bad

**Comment by LiangYong1216** [comment]
> @LiangYong1216 Have you solved this problem? I met the same problem, the model achieve high precision and recall score on training set but works badly on test set.

 No, the problem is not solved, I used a lot of data enhancement and overfitting prevention methods, such as dropout, bn, regularization, but it still did not work, and compared to the original label, there is still room for optimization, and finally I changed a model and used CPN for key point detection, and the effect was not bad

**Comment by glenn-jocher** [comment]
@LiangYong1216 hello! It's unfortunate that the various methods you tried didn't improve the model's performance on the test set, despite achieving a high precision and recall on the training set. This is usually indicative of overfitting, meaning the model has learned the training set too well but is not capable of generalizing to unseen data.

Switching to a different model, as you've done by using CPN for keypoint detection, is a valid approach. Different models have different capacities and may perform better or worse depending on the specificities of the dataset and task at hand. It's great to hear that CPN is yielding better results for your project.

In the future, consider other strategies for combating overfitting, such as obtaining more training data, implementing early stopping, tuning hyperparameters, or trying different training/validation splits. 

Remember, the goal is to build a model that generalizes well to unseen data, rather than one that merely performs well on the training set.

Thank you for sharing your experience with the community!

**Comment by PallottaEnrico** [comment]
I think that the problem is in the metrics that are used to evaluate pose models.
According to the definition given by [COCO](https://cocodataset.org/#keypoints-eval) about keypoint evaluation, a keypoint is considered correct depending on the so called OKS (object keypoint similarity). The concept is the same as IoU for BB detection, namely if the predictions are above a certain threshold of similarity, they are considered as correct.
This means that having a precision of 1 does not imply that the predicted keypoints are all in the exact position.
I'm facing the same problem, i get scores like this:
![image](https://github.com/ultralytics/ultralytics/assets/57596722/9d1dc6b4-6df1-413a-b289-c0c66a525a95)
but the quality of the predictions is not the one that i'm looking for.

I think that a solution could be:
- change the loss weights: in the training parameters you can find as defaults 
`box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0`
These determine how much each component is important for the loss, in your case (mine too) the loss of BB is not important so you can lower the box value, while you should increase the kobj value. This value is for general kp detection, the pose value instead refers to the case of human pose estimation.
- change the evaluation metrics as the one used now are not really significant. I'm still trying to understand how these are computed, an idea could be to increase the requirement of similarity between predicted and ground truth keypoints.

@glenn-jocher I would like to know what do you think about this.
In particular i would like to understand better how this OKS are computed and used.
I saw that [here](https://github.com/ultralytics/ultralytics/blob/bcec003ee30a181403d223757f424a50a86cd426/ultralytics/utils/metrics.py#L15) you defined the values for human pose.
While [here](https://github.com/ultralytics/ultralytics/blob/bcec003ee30a181403d223757f424a50a86cd426/ultralytics/models/yolo/pose/val.py#L54) you set the OKS for general kp detection as `np.ones(nkpt) / nkpt`, what does this imply?

**Comment by PallottaEnrico** [comment]
@LiangYong1216 i was forgetting that probably you need to change the oks values also in the [pose loss](https://github.com/ultralytics/ultralytics/blob/bcec003ee30a181403d223757f424a50a86cd426/ultralytics/utils/loss.py#L306C98-L306C98).

I'm doing some experiments right now. 
I've 4 keypoints, with the original code this means that each point has 1/4=0.25 OKS, considering that the values given to keypoints corresponding to nose and ears in human pose were 0.025/0.03, the 0.25 is too high for what i need.

Using 1/n can be a general good rule of thumb, as in theory the more keypoints the higher the precision of each, but this is not true in all the cases and really depends on the specific application.

**Comment by atharvavaidya14** [comment]
@PallottaEnrico I think the simple solution for the OKS sigma problem can be initializing it as a constant value (say 0.05) if the number of keypoints are less than 17 and 1/n otherwise. 

Also, where can we change the loss weights you mentioned? Are these passed as arguments or are they hard coded somewhere?

**Comment by glenn-jocher** [comment]
@PallottaEnrico, you're right, adjusting the OKS sigma value could be a potential solution depending on the specific task and the number of keypoints you're working with.

Concerning the loss weights, they are passed as arguments in the code and can be adjusted according to the specific demands of your project. However, keep in mind that the kobj loss weight is related to the visibility prediction, so modifying it may not directly impact the accuracy of the keypoints' positioning.

Regarding your proposed solution for the OKS sigma, using a flat value like 0.05 might work for your case, but please remember the importance of tuning these parameters based on the specifics of your project and the data you're working with.
  
Remember to continuously monitor your model's performance and adjust parameters as needed. Good luck with your project!

@PallottaEnrico, keep us posted on how your changes improve your model's performance. Your observations are incredibly useful and could provide great insights for others working on similar tasks.

**Comment by LiangYong1216** [comment]
> @atharvavaidya14 , the loss weights can be passed as arguments so you can change them as you prefer. I'm currently digging more in the training code, I've to correct my self, the kobj loss seems to refer to the visibility prediction (which is used only if you have kp shape [n,3]). So increasing it would not improve the "position" precision of keypoints. (edited the previous comment)
> 
> For the OKS, yes you can do as you want, for the moment i'm simply changing the lines of code mentioned putting 0.025.
hello @PallottaEnrico,  By modifying the sigma initial value, is your problem solved?
My dataset has 52 key points, so in the original code, the value of sigma should be 1/52~0.019, so the sigma value should be correct

**Comment by LiangYong1216** [comment]
> @LiangYong1216 i was forgetting that probably you need to change the oks values also in the [pose loss](https://github.com/ultralytics/ultralytics/blob/bcec003ee30a181403d223757f424a50a86cd426/ultralytics/utils/loss.py#L306C98-L306C98).
> 
> I'm doing some experiments right now. I've 4 keypoints, with the original code this means that each point has 1/4=0.25 OKS, considering that the values given to keypoints corresponding to nose and ears in human pose were 0.025/0.03, the 0.25 is too high for what i need.
> 
> Using 1/n can be a general good rule of thumb, as in theory the more keypoints the higher the precision of each, but this is not true in all the cases and really depends on the specific application.

hello @PallottaEnrico, By modifying the sigma initial value, is your problem solved?
My dataset has 52 key points, so in the original code, the value of sigma should be 1/52~0.019, so the sigma value should be correct

**Comment by PallottaEnrico** [comment]
Hi @LiangYong1216, I'll explain you how i've proceeded.
Let's take as reference metric the pose mAP50-95 i showed you before. (99.2%)
I'll call each model like M_sigmaSalue, so that model is M_0.25.
I evaluated M_0.25 setting the sigma in [metrics calculation](https://github.com/ultralytics/ultralytics/blob/bcec003ee30a181403d223757f424a50a86cd426/ultralytics/models/yolo/pose/val.py#L54) to:
- 0.1 -> mAP 98.4%
- 0.05 -> mAP 93.5%
- 0.025 -> mAP 75.5%

So i decided that for the kind of results that i was getting out of the model (visually), the metric with sigma 0.05 was the most representative one.
Retraining from scratch the model ,with sigma 0.05 on the [loss](https://github.com/ultralytics/ultralytics/blob/bcec003ee30a181403d223757f424a50a86cd426/ultralytics/utils/loss.py#L306C98-L306C98), allowed me to get a mAP of 95.2 (+1.7%). 
Indeed the results that i've now from this model M_0.05 are visually even better than the ones obtained by M_0.25.
I also trained a M_0.025 but the training was too unstable and never reached a good convergence, with such a low sigma value i was using a very hard label, which is in general known in deep learning to not be a really good idea.

Regarding your case, i don't know if 1/52 is a good sigma value, probably not given your results. I would suggest you to evaluate your trained model with metrics based on lower sigmas and find the most representative one.
As I said, be careful to not choose a too low sigma when training again, and remember to set the same sigma for metric and loss before training.

@glenn-jocher Thanks for your reply, however i would like to understand better the concept behind sigma values, namely what unit of measurement are they?

**Comment by LiangYong1216** [comment]
hi @PallottaEnrico , Thank you for the prompt reply, I tried modifying the value of sigma a bit and then retraining the model

**Comment by glenn-jocher** [comment]
Hello @LiangYong1216, I'm glad to hear that you're trying out different values for sigma and seeing how it affects your model. The effects of modifying sigma can indeed be quite significant, especially because it directly affects the precision of the keypoint predictions. This variable essentially dictates the emphasis placed on the precision of each keypoint's prediction during the loss calculation, and thus can greatly influence the overall performance of your model.

Keep in mind that choosing the right sigma value may require some experimentation, as you’ve started doing. It's often a fine balance to strike: a value that's too high may overemphasize precision, while a value that's too low might not apply enough focus on getting precise predictions.

Remember to monitor your model’s performance with the modified sigma values, and tweak it iteratively based on your results. Kudos for your efforts, and all the best with your continued work! Keep us posted on your progress.

**Comment by PallottaEnrico** [comment]
Hi @glenn-jocher, I've just submitted a PR (#4135) to allow customization of OKS values through Yolo parameters.
I saw that there's already another similar PR (#3526), however to me seems more clear the way I did, feel free to decide what you prefer.

**Comment by glenn-jocher** [comment]
@PallottaEnrico hi, thank you for your contribution in submitting the PR (#4135) for customizing OKS values in the YOLOv8 model parameters. We appreciate the time and effort put into this.

We're always open to different approaches that can improve the model, and having options can indeed provide clarity and flexibility. Rest assured, we will review your PR thoroughly along with the existing PR (#3526) and choose the approach that best aligns with the overall design and functionality of YOLOv8.

Your active participation and interest in improving YOLOv8 contributes significantly to our mission of providing the best possible object detection models to the community. Thanks again! Keep contributing!

**Comment by sheikh-n** [comment]
Hello @PallottaEnrico, I read your comments on this issue and tried to do the same. But it seems not working in my case or I am doing something wrong.
Let me tell you about my situation:
1. I am using ultralytics=8.0.150 in conda environment
2. my datasets :
train images:888
val images:223
each image has 12 keypoints
tried to change loss.py and val.py in the environment`s site-packages like this:
loss.py change: 
    # sigmas = torch.from_numpy(OKS_SIGMA).to(self.device) if is_pose else torch.ones(nkpt, device=self.device) / nkpt
    sigmas = torch.ones(nkpt, device=self.device) / 20

val.py change: 
    #self.sigma = OKS_SIGMA if is_pose else np.ones(nkpt) / nkpt 
    self.sigma = np.ones(nkpt) / 20
Also, I tried 25, 40, and even 400 instead of 20.
I did not see any change in the training process while changing this value, still, all training are starting with P and R is 1.
Can you help me if I made a mistake in the process of changing?

**Comment by PallottaEnrico** [comment]
@sheikh-n , you changed them correctly. The previous sigma value that you were using was 1/12 now is 1/20, so you are requiring much more precision.
Just to do a test i would try to leave the loss as it is and change only the val, e.g. loss 1/12 and val 1/40.
Doing this your metrics must go down, if not there must be another problem.

**Comment by glenn-jocher** [comment]
Hello @sheikh-n, you've made the appropriate changes to the sigma values in the loss.py and val.py files. However, changing the sigma values from 1/12 to 1/20 is making your model demand higher precision for keypoints localization, which might not always lead to an apparent change in the initial stages of training, especially when precision and recall are both 1.

As a test, I recommend you to restore the original loss calculation (keeping sigma as 1/12) and only change the sigma in the val.py file to 1/40. This will lower the precision requirement during validation and might cause an observable difference in your metrics. If this doesn't lead to a decrease in your metrics, then there might be another issue that needs addressing.

Please, keep us updated on your progress!

**Comment by skpawar1305** [comment]
I'm comparing different pose models with 5 keypoints
Can you shed some light on the significance of OKS_SIGMA, also, what values can I put for a general model comparison?

**Comment by glenn-jocher** [comment]
@skpawar1305 oKS_SIGMA is a parameter that defines the object keypoint similarity and is used to control the scale of the penalty for keypoint localization errors. For a general model comparison with 5 keypoints, you might start with a value like 1/5 (one over the number of keypoints) and adjust based on the size of the objects and the precision required for your task. Experiment with different values to see which best reflects the performance of your models.
