### ISSUE TITLE
cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py)

### ISSUE THREAD

**Issue by Dappuu** [ultralytics/ultralytics#3067]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

ImportError                               Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py](https://localhost:8080/#) in tf()
     41     try:
---> 42         from tensorboard.compat import notf  # noqa: F401
     43     except ImportError:

ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
29 frames
[/usr/local/lib/python3.10/dist-packages/pandas/_testing/__init__.py](https://localhost:8080/#) in <module>
    901 
    902 
--> 903 cython_table = pd.core.common._cython_table.items()
    904 
    905 

AttributeError: partially initialized module 'pandas' has no attribute 'core' (most likely due to a circular import)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by bit-scientist** [comment]
It must be due to a circular import (where two or more modules depend on each other directly or indirectly). I'd recommend creating a fresh virtual environment and follow the installation steps.

**Comment by glenn-jocher** [comment]
@Dappuu 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃
