### ISSUE TITLE
GFLOPs

### ISSUE THREAD

**Issue by nguyenduylinhqbu** [ultralytics/ultralytics#3069]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Dear all,
Why it didn't show the GFLOPs when finished the loading model like YOLOv5?
How to show the GFLOPs?
Thanks all

**Comment by tangruinenu** [comment]
GFLOPs are not displayed because some operators are not currently supported. So just return parameters, I'm having the same problem as you. I found the cause mentioned earlier using debug

**Comment by glenn-jocher** [comment]
thop package is now no longer installed by default due to conda issues, so please make sure you install thop manually to see flops with pip install thop.

**Comment by glenn-jocher** [comment]
@nguyenduylinhqbu thank you for reaching out to us about the "get_flops" warning you encountered while using YOLOv8. This warning occurs because some operators in YOLOv8 cannot be evaluated due to limitations in the thop package, which is used to calculate GFLOPs. Therefore, certain modules, such as CAnet, may return a 0 GFLOP value. We apologize for any confusion this may have caused and suggest checking with the thop package to see if a fix or update is available.

**Comment by nguyenduylinhqbu** [comment]
> @nguyenduylinhqbu thank you for reaching out to us about the "get_flops" warning you encountered while using YOLOv8. This warning occurs because some operators in YOLOv8 cannot be evaluated due to limitations in the thop package, which is used to calculate GFLOPs. Therefore, certain modules, such as CAnet, may return a 0 GFLOP value. We apologize for any confusion this may have caused and suggest checking with the thop package to see if a fix or update is available.

Dear Mr. @glenn-jocher,
I already solved this problem with your suggestion (pip install thop).
Thank you very much.
Best regards.

**Comment by glenn-jocher** [comment]
Dear @tangruinenu, 

We are glad to hear that the issue has been resolved and that our suggestion to manually install thop was helpful. If you have any more questions or concerns, please don't hesitate to contact us, we are always happy to assist you.
 
Thank you for choosing YOLOv8 and for being a part of our community.
 
Best regards.

**Comment by shensongli** [comment]
> > thop package is now no longer installed by default due to conda issues, so please make sure you install thop manually to see flops with pip install thop.
> > I do have thop, but found in yolov8 that some modules warn get_flops will return 0 directly because some operators cannot be evaluated because of thop.profile. For example, CAnet

hello，how can i solve such a problem

**Comment by glenn-jocher** [comment]
Hello @shensongli,

To address the issue with GFLOPs not being displayed for certain modules like CAnet, you can manually install the thop package using the following command:

```bash
pip install thop
```

This should help resolve the problem. If you continue to encounter issues, it may be due to limitations in the thop package's ability to evaluate certain operators. In such cases, you might want to check for updates or fixes within the thop package itself.

Feel free to reach out if you have any more questions! 😊
