### ISSUE TITLE
How to improve prediction speed of a custom trained yolov8 model?

### ISSUE THREAD

**Issue by aka-sh74** [ultralytics/ultralytics#3070]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a custom trained yolov8 model. When I use this model to detect custom objects in a video, it's processing speed is slow. Can I know how can I improve the speed of this model? I am using google collab with T4 GPU. 
The speed rn is ~ 2-3 fps on collab.

### Additional

I'm using ByteTrack as a tracker in my project.

**Comment by glenn-jocher** [comment]
@aka-sh74 thanks for reaching out! To improve the speed of custom YOLOv8 models, there are several methods you can explore:

1. **Quantization:** This helps to reduce model size and improve inference time. You can use [pytorch quantization](https://pytorch.org/docs/stable/quantization.html) to quantize your YOLOv8 model. 

2. **Threading:** This helps to improve inference speed for large batch sizes. We recommend you to take a look at Python's [multiprocessing](https://docs.python.org/2/library/multiprocessing.html) module for guidance.

3. **ONNX Deployment:** If you are looking to use your custom trained model on another platform, we recommend exporting your model to the [ONNX format](https://onnx.ai/) and then deploy it using [ONNX Runtime](https://github.com/microsoft/onnxruntime) in C++.

We hope this helps! Let us know if you have any further questions or concerns.

**Comment by fridary** [comment]
> @aka-sh74 thanks for reaching out! To improve the speed of custom YOLOv8 models, there are several methods you can explore:
> 
> 1. **Quantization:** This helps to reduce model size and improve inference time. You can use [pytorch quantization](https://pytorch.org/docs/stable/quantization.html) to quantize your YOLOv8 model.
> 2. **Threading:** This helps to improve inference speed for large batch sizes. We recommend you to take a look at Python's [multiprocessing](https://docs.python.org/2/library/multiprocessing.html) module for guidance.
> 3. **ONNX Deployment:** If you are looking to use your custom trained model on another platform, we recommend exporting your model to the [ONNX format](https://onnx.ai/) and then deploy it using [ONNX Runtime](https://github.com/microsoft/onnxruntime) in C++.
> 
> We hope this helps! Let us know if you have any further questions or concerns.

@glenn-jocher thank you for your replies. Can you please give me once again a clue how to improve prediction speed with my hardware? Yolo is latest version, python 3.9, Ubuntu 20.04, CPU Intel i7-8700 6 cores

```python
print(torch.__version__)
print(torch.version.cuda)
print(torch.backends.cudnn.version())
print(torch.cuda.get_device_name(0))
print(torch.cuda.get_device_properties(0))
```

```
2.0.1
11.7
8500
Tesla K80
_CudaDeviceProperties(name='Tesla K80', major=3, minor=7, total_memory=12206MB, multi_processor_count=13)
```
I trained model from `yolov8n.pt` from small dataset ~200 images and use this code to predict:
```python
start_time = time.time()
model.predict(source=[img_list], device=0)
print("%.3f seconds" % (time.time() - start_time))
```
So average results for img sets training:
```
4.918 seconds 1 images array
5.131 seconds 10 images array
5.572 seconds 100 images array
11.528 seconds 1000 images array
```

If I do all the same on CPU with torch-cpu, average prediction of 1 image is 1.4 seconds (obviously, 1000 images take a lot of minutes).
How can I improve speed prediction on GPU?

**Comment by glenn-jocher** [comment]
@fridary the prediction speed can be influenced by various factors including your model complexity, input data, and hardware setup. Here are a few suggestions:

1. **Reduce your model size**: This may involve using a smaller architecture or applying model quantization. The trade-off is that reducing the model size might affect the performance (precision and recall).

2. **Optimize your batch size**: Usually, processing images in batches is faster compared to processing them one by one due to parallel computing. However, the optimal batch size may depend on your specific GPU memory. You might need to experiment with this.

3. **Use ONNX and TensorRT**: Exporting your model to ONNX and optimizing it with NVIDIA TensorRT can also speed up the inference.

4. **Use multiple GPUs**: If possible, using multiple GPUs can also speed up the inference by dividing the work among them.

5. **Use a more powerful GPU**: You are using a Tesla K80, you can consider using a more recent GPU if possible.

Please consider these are general tips and actual performance gain would require a thorough benchmarking and profiling of your specific use-case.

**Comment by fridary** [comment]
@glenn-jocher thank you. Can you please confirm, on the example above I did everything correct about using ONNX? I created .pt model and then exported to .onnx format. Speed performance is in 2-5 times slower.

**Comment by glenn-jocher** [comment]
@fridary yes, your approach to training the model and then exporting it to ONNX format is correct. Decreased performance in ONNX might be due to the inference optimizations present in the original framework (PyTorch in this case) possibly not being entirely transferred over to the ONNX model. 

It is also important to note that the speed performance of an ONNX model can be impacted by various factors such as the model complexity, the hardware it's running on, and the batch size. Therefore, the time it takes to run an ONNX model can vary and might not always be faster than the original model. 

If inference speed is critical for your application, you might want to consider other optimization methods. Hardware acceleration (like using a more powerful GPU or multiple GPUs), model pruning, or quantization are some examples. However, these approaches often require a balance between speed and accuracy.

**Comment by Manueljohnson063** [comment]
Hai ,
@glenn-jocher   when i do batch parellization in pt model it is working fine but when comes to engine 
path = model.export(format="engine",opset=12,workspace=4,device=0,batch=3,half=True)
When i put a batch of 3 images to the engine file the engine is throwing error

**Comment by glenn-jocher** [comment]
@Manueljohnson063 hi there,

If you're using the .engine format, you must adhere to the TensorRT requirements. The issue you're facing might be due to the discrepancy between batch sizes during export and inference. 

Always ensure that in the step where you are converting your model to .engine format you specify the exact batch size you plan to use at the inference stage. 

If you're planning to use variable batch sizes, you should configure your model for dynamic shapes during conversion.

Remember, TensorRT is an NVIDIA library. It is indeed powerful, but also comes with its own intricacies. You need to cater to those especially when dealing with batch sizes and other parameters.

I hope this helps.

**Comment by Manueljohnson063** [comment]
@glenn-jocher 
**My code is :**
import cv2
import time
import numpy as np

gst_str = /*working pipeline*/

cap = cv2.VideoCapture(gst_str, cv2.CAP_GSTREAMER)
if not cap.isOpened():
    print("Error opening pipeline")
    exit()

from ultralytics import YOLO
model = YOLO("./best.engine")

batch_size = 4  # Adjust this according to your GPU memory
frames_batch = []
while cap.isOpened():
    start_time = time.time()
    for _ in range(batch_size):
        success, frame = cap.read()
        if not success:
            break
        frames_batch.append(frame)

    if len(frames_batch) > 0:
        results = model(frames_batch)  # Perform batch inference

        for frame, result in zip(frames_batch, results):
            masks = result.masks
            mask1 = masks[0]
            polygon = mask1.xy[0].astype(np.int32)
            cv2.polylines(frame, [polygon], True, (0, 0, 255), 4)
            cv2.imshow("Yolov8Inference.mp4", frame)

        frames_batch = []

    if cv2.waitKey(1) & 0xFF == ord("q"):
        break

    elapsed_time = time.time() - start_time
    print("--- Time for a batch of frames ---: ", elapsed_time)

cap.release()
cv2.destroyAllWindows()



**ERROR**
Loading best.engine for TensorRT inference...
[08/22/2023-20:58:38] [TRT] [I] Loaded engine size: 8 MiB
[08/22/2023-20:58:42] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +343, GPU +328, now: CPU 757, GPU 4379 (MiB)
[08/22/2023-20:58:42] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +7, now: CPU 0, GPU 7 (MiB)
[08/22/2023-20:58:42] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +0, now: CPU 749, GPU 4379 (MiB)
[08/22/2023-20:58:42] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +34, now: CPU 0, GPU 41 (MiB)
Traceback (most recent call last):
  File "BatchProcessingGpu.py", line 74, in <module>
    result = model(frames_batch, stream=False, device=0, conf=0.1, iou=0.1, verbose=False)[0]
  File "/home/xavier/EyeTrackingPrj/ultralytics-main/ultralytics/engine/model.py", line 98, in __call__
    return self.predict(source, stream, **kwargs)
  File "/home/xavier/.local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/xavier/EyeTrackingPrj/ultralytics-main/ultralytics/engine/model.py", line 246, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/xavier/EyeTrackingPrj/ultralytics-main/ultralytics/engine/predictor.py", line 197, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/home/xavier/.local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/xavier/EyeTrackingPrj/ultralytics-main/ultralytics/engine/predictor.py", line 257, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "/home/xavier/EyeTrackingPrj/ultralytics-main/ultralytics/models/yolo/segment/predict.py", line 39, in postprocess
    masks = ops.process_mask(proto[i], pred[:, 6:], pred[:, :4], img.shape[2:], upsample=True)  # HWC
  File "/home/xavier/EyeTrackingPrj/ultralytics-main/ultralytics/utils/ops.py", line 606, in process_mask
    c, mh, mw = protos.shape  # CHW
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by glenn-jocher** [comment]
@Manueljohnson063 hello, it seems like you're getting a `ValueError: not enough values to unpack (expected 3, got 2)` when trying to unpack the shape of your protos variable in the `process_mask` function.

The error is likely due to this line:
```python
c, mh, mw = protos.shape  # CHW
```
It's expecting protos to have 3 dimensions (perhaps corresponding to channels, height, width in an image), but it seems your `protos` tensor only has 2 dimensions.

Ensure that your `proto` tensor has the correct shape with 3 dimensions, otherwise, the unpacking operation will fail. Check your data preprocessing steps and the model itself to ensure the shapes align correctly. Also, check the shapes returned by your model's forward method and compare them with the expected shapes. 

If your tensors' shapes are mismatched, that's likely where the problem is coming from. It's hard to conclusively pinpoint the cause without more information.

**Comment by Manueljohnson063** [comment]
Many many thanks in advance ,I have printed the shape it is only 2 .
The only thing i have done is created engine file with batch size 3 ,Can you please give me a little more input.
Thanks in advance

**Comment by glenn-jocher** [comment]
@Manueljohnson063 You're welcome! Your observation that the 'protos' has only 2 dimensions is likely the source of the error. It seems that 'protos' is expected to have 3 dimensions, but in your case, it has only 2.

The model you're using likely expects this third dimension, which might be related to channel information in the image data (Colors Red, Green, Blue). In retrospect, the batch processing might have caused this discrepancy.

When you specify the batch size during the engine creation, the model might be expecting 4 dimensions (batch size, channel, height, width) instead of 3 (channel, height, width). 

You might need to adjust your pre-processing steps to ensure that 'protos' has the correct dimensionality. Please review the process you use to prepare your data for inference so that it aligns with what the model expects.

Unfortunately, I can't provide details on the implementation without additional context, but broadly speaking, you might need to reshape or expand the dimensions of your data before feeding it to the model. Make sure also to check the expected input shape in your model documentation.

**Comment by Manueljohnson063** [comment]
I have made the pytorch model and i had named it as  best.pt after wards i had use this script 
from ultralytics import YOLO
model = YOLO("best.pt")  # load a pretrained model 
**path = model.export(format="engine",opset=12,device=0, int8=True, dynamic=True,simplify=True,workspace=4)**
I had used this way to generate the engine but when i feed the engine with batch of images then 
**`i am facing error`**
         Loading best.engine for TensorRT inference...
[08/23/2023-13:08:14] [TRT] [I] Loaded engine size: 19 MiB
[08/23/2023-13:08:17] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +343, GPU +319, now: CPU 761, GPU 4700 (MiB)
[08/23/2023-13:08:17] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +19, now: CPU 0, GPU 19 (MiB)
[08/23/2023-13:08:17] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +0, now: CPU 742, GPU 4700 (MiB)
[08/23/2023-13:08:17] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +178, now: CPU 0, GPU 197 (MiB)
The proto shape  are  torch.Size([160, 160])
Traceback (most recent call last):
  File "BatchProcessingGpu.py", line 74, in <module>
    result = model(frames_batch, stream=False, device=0, conf=0.1, iou=0.1, verbose=False)[0]
  File "/home/xavier/EyeTrackingPrj/ultralytics-main/ultralytics/engine/model.py", line 98, in __call__
    return self.predict(source, stream, **kwargs)
  File "/home/xavier/.local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/xavier/EyeTrackingPrj/ultralytics-main/ultralytics/engine/model.py", line 246, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/xavier/EyeTrackingPrj/ultralytics-main/ultralytics/engine/predictor.py", line 197, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/home/xavier/.local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/xavier/EyeTrackingPrj/ultralytics-main/ultralytics/engine/predictor.py", line 257, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "/home/xavier/EyeTrackingPrj/ultralytics-main/ultralytics/models/yolo/segment/predict.py", line 39, in postprocess
    masks = ops.process_mask(proto[i], pred[:, 6:], pred[:, :4], img.shape[2:], upsample=True)  # HWC
  File "/home/xavier/EyeTrackingPrj/ultralytics-main/ultralytics/utils/ops.py", line 607, in process_mask
    c ,mh, mw = protos.shape  # CHW
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by Manueljohnson063** [comment]
I have seen the similar issue in the id 
**TensorRT Segmentation not working when using batch = 3 #2503**
PLease help me to solve this out

**Comment by glenn-jocher** [comment]
Hello @Manueljohnson063,

Thanks for referencing a similar issue. It's clear that this issue is showing up due to a discrepancy in dimensions. Your model is expecting a tensor with 3 dimensions, but is currently only getting 2 dimensions.

When you're exporting the model with a batch size of 3, the model is presumably expecting input dimensions to be (batch size, channels, height, width). This may be why your 'protos' variable only has 2 dimensions instead of the expected 3.

You may need to recheck your model's input pre-processing code. It is crucial that your image data matches the format that the model is expecting. It's also important to remember that these dimensions need to match while both training and inferencing. 

Try to modify your data feed process such that it provides images in the correct format that your model expects. If the model was trained with a specific batch size, make sure that you're using the same batch size for inference.

I hope this helps. Do let us know if you have further questions or run into more issues.

**Comment by Manueljohnson063** [comment]
After your instruction
1.Model was trainied with batch size=3
`yolo task=segment  mode=train epochs=100 **batch=3** data=dataset.yaml`

2.Engine generation
```
from ultralytics import YOLO
model = YOLO("best.pt") 
path = model.export(format="engine",opset=12,device=0,half=True,**batch=3**,workspace=3)
```
3.Official code i used for batch generation
```
import cv2
import time
import numpy as np

gst_str = ("filesrc location=V_20270616_070105.mp4 ! "
          ......... ! appsink")

cap = cv2.VideoCapture(gst_str, cv2.CAP_GSTREAMER)
if not cap.isOpened():
    print("Error opening pipeline")
    exit()

from ultralytics import YOLO
model = YOLO("./best.engine",task="segment")

**batch_size = 3**  # Adjust this according to your GPU memory
frames_batch = []

while cap.isOpened():
  #  start_time = time.time()
    for _ in range(batch_size):
        success, frame = cap.read()
        if not success:
            break
        frames_batch.append(frame)

    if len(frames_batch) > 0:
        result = model(frames_batch,device=0,batch=3)[0]
        frames_batch = []
cap.release()
cv2.destroyAllWindows()

```
4.**STILL THE SAME ERROR**
`Traceback (most recent call last):
  File "BatchProcessingGpu.py", line 74, in <module>
    result = model(frames_batch,device=0,batch=3)[0]
  File "/home/xavier/EyeTrackingPrj/ultralytics-main/ultralytics/engine/model.py", line 98, in __call__
    return self.predict(source, stream, **kwargs)
  File "/home/xavier/.local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/xavier/EyeTrackingPrj/ultralytics-main/ultralytics/engine/model.py", line 246, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/xavier/EyeTrackingPrj/ultralytics-main/ultralytics/engine/predictor.py", line 199, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/home/xavier/.local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/xavier/EyeTrackingPrj/ultralytics-main/ultralytics/engine/predictor.py", line 259, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "/home/xavier/EyeTrackingPrj/ultralytics-main/ultralytics/models/yolo/segment/predict.py", line 52, in postprocess
    masks = ops.process_mask(proto[i], pred[:, 6:], pred[:, :4], img.shape[2:], upsample=True)  # HWC
  File "/home/xavier/EyeTrackingPrj/ultralytics-main/ultralytics/utils/ops.py", line 674, in process_mask
    c, mh, mw = protos.shape  # CHW
ValueError: not enough values to unpack (expected 3, got 2)
`

@glenn-jocher

**Comment by glenn-jocher** [comment]
Hello @Manueljohnson063,

I understand your frustration seeing the same error even after the suggested changes. The error message indicates a shape mismatch. Your model is expecting a tensor with 3 dimensions, but is currently only getting 2 dimensions. 

Here are a few steps that might help to resolve this issue:

- Review your data preprocessing. Are you sure all the images you are feeding into the model during inference are properly preprocessed? 
- Monitor your data feed process to confirm that it's providing images in the correct format that your model expects.
- There's a chance that the model architecture or configuration might be causing this issue. Please ensure that the architecture correctly handles the batch size of 3 and produces expected tensor dimensions.

Remember to keep the same batch size for both training and inference as using different batch sizes can yield inconsistencies. I hope this helps, and if the problem persists, do not hesitate to ask more questions. We are here to help!

**Comment by Manueljohnson063** [comment]
Many many thanks for your suggestion
1. Review your data preprocessing. Are you sure all the images you are feeding into the model during inference are properly preprocessed?
Ans) 
`Can you please give me a hint what yolov8 preprocessing specially have `

2. There's a chance that the model architecture or configuration might be causing this issue. Please ensure that the architecture correctly handles the batch size of 3 and produces expected tensor dimensions.
`I also tried with differnt batch sizes same effect`


‘
*****I am able to do batch parellization with same code when the model is pytorch .But when i converted to engine entire thins goes wrong*****’


Many many thanks in advance …..

**Comment by glenn-jocher** [comment]
Hello @Manueljohnson063,

Thank you for your response.

1. Regarding the preprocessing in YOLOv8, the main detail to be aware of is that the model expects inputs to be in a certain range and of a specific shape. The images should ideally be normalized between 0 and 1 and have a size that matches the expected input size of the model. These preprocessing steps should be maintained consistently both during training and inference.

2. It's good that you've tried different batch sizes and found the same effect. This hints that the issue might be more related to the conversion to the engine format. In PyTorch, the model may be able to handle a dynamic batch size, but this may not be the case once it is converted to an engine. 

When you convert your model to an engine, it might be missing some information about the expected input size and batch size, thus leading to this discrepancy. During this conversion, you may need to explicitly provide this information to ensure that the engine is able to handle the inference correctly.

Lastly, please ensure that the version of PyTorch you used for training and the version you are using for inference are compatible. Even a minor version mismatch can sometimes cause critical issues.

I hope this information helps you in troubleshooting the problem! Do let us know if you have any more concerns!

**Comment by mobin3399** [comment]
To run the network in real time, I used the nano model. The purpose of the project is to count the objects on the conveyor belt.
Tell me a solution so that I can make the program execution speed closer to real time.
Also, I tried to use cuda, but the program was getting an error.
Thanks.

**Comment by glenn-jocher** [comment]
@mobin3399 to improve execution speed towards real-time performance, consider the following steps:

1. Optimize your model: Use a smaller model architecture that's designed for speed, like YOLOv8-Nano, if you haven't already.
2. Reduce input resolution: Lower the resolution of the input images if possible, as this can significantly speed up processing.
3. Batch inference: If you're processing multiple images, use batch inference to process multiple images at once.
4. Hardware acceleration: Ensure that CUDA is correctly installed and configured. Update drivers and check for compatibility issues.
5. Simplify post-processing: Minimize any complex operations after detection, such as custom tracking or additional computations.

If you're encountering errors with CUDA, verify that your environment is set up correctly and that your CUDA version is compatible with the installed PyTorch version. If issues persist, please provide the error message for more specific guidance.

**Comment by FaizAhmeddd** [comment]
@glenn-jocher I am training yolov8n model on a custom dataset and I'm looking for a technique to make that model lightweight and to reduce the model size from 6.1MB. Can you give me some information how to do that? if possible

**Comment by glenn-jocher** [comment]
Hello @FaizAhmeddd! To make your YOLOv8n model more lightweight, consider the following techniques:

1. **Pruning:** Remove less important weights from the model. You can use techniques like magnitude-based pruning.
2. **Quantization:** Convert model weights from floating point to lower precision (e.g., int8).

Here's a simple example of how to apply quantization using PyTorch:

```python
import torch
model = torch.load('yolov8n.pt')
model_quantized = torch.quantization.quantize_dynamic(model, {torch.nn.Linear}, dtype=torch.qint8)
torch.save(model_quantized, 'yolov8n_quantized.pt')
```

This should help reduce the size of your model! Let us know how it goes. 😊

**Comment by Harly-1506** [comment]
Hello everyone,

I invite you to explore my new GitHub repository for running YOLOv8 object detection and segmentation inference using OpenVINO and NumPy only. This implementation outperforms the Torch version, delivering enhanced speed and efficiency. Check it out here: [Faster Inference YOLOv8](https://github.com/Harly-1506/Faster-Inference-yolov8).

Your feedback and contributions are highly appreciated!

Thanks!

**Comment by glenn-jocher** [comment]
Hello @Harly-1506,

Great work on optimizing YOLOv8 with OpenVINO and NumPy! 🚀 It's exciting to see community-driven enhancements that boost performance. I'll definitely check out your repository and provide feedback.

For those interested in efficient inference, this could be a valuable resource. Keep up the fantastic work!

Cheers!

**Comment by rajhlinux** [comment]
> Hello @Manueljohnson063,
> 
> Thank you for your response.
> 
> 1. Regarding the preprocessing in YOLOv8, the main detail to be aware of is that the model expects inputs to be in a certain range and of a specific shape. The images should ideally be normalized between 0 and 1 and have a size that matches the expected input size of the model. These preprocessing steps should be maintained consistently both during training and inference.
> 2. It's good that you've tried different batch sizes and found the same effect. This hints that the issue might be more related to the conversion to the engine format. In PyTorch, the model may be able to handle a dynamic batch size, but this may not be the case once it is converted to an engine.
> 
> When you convert your model to an engine, it might be missing some information about the expected input size and batch size, thus leading to this discrepancy. During this conversion, you may need to explicitly provide this information to ensure that the engine is able to handle the inference correctly.
> 
> Lastly, please ensure that the version of PyTorch you used for training and the version you are using for inference are compatible. Even a minor version mismatch can sometimes cause critical issues.
> 
> I hope this information helps you in troubleshooting the problem! Do let us know if you have any more concerns!

Super useful information.

Are there any official best practices, guides or documentation specifically for pre-processing Yolov8 during inference mode?
Such as stating what proper mandated requirements needed for best performance and accuracy in pre-processing stage?

I can not find any authoritative details on this and it seems its more word of mouth on how to go about things.

Thanks.
