### ISSUE TITLE
detect predict argument with  " line_width"

### ISSUE THREAD

**Issue by UsersNGT** [ultralytics/ultralytics#3073]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

when I predict yolov8 use CIL, i want to adjust line_width , but error,

root@nbook-shiht15-ht-0:/data/private/ultralytics# yolo detect predict model=detect2/train_exp1.10/weights/best.pt  source=/data/priva
te/data/train_data/head/037.png  line_width=1.0 project=detect2 name=ceshi                                                            
Traceback (most recent call last):                                                                                                    
  File "/opt/conda/bin/yolo", line 8, in <module>                                                                                     
    sys.exit(entrypoint())                                                                                                            
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/yolo/cfg/__init__.py", line 335, in entrypoint                             
    check_cfg_mismatch(full_args_dict, overrides)                                                                                     
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/yolo/cfg/__init__.py", line 178, in check_cfg_mismatch                     
    raise SyntaxError(string + CLI_HELP_MSG) from e                                                                                   
SyntaxError: 'line_width' is not a valid YOLO argument. 

### Environment

YOLO:Ultralytics YOLOv8.0.83 🚀 Python-3.8.5 torch-1.13.0+cu117 CUDA:0 (NVIDIA A30 MIG 1g.6gb, 5952MiB)
OS:ubuntu 20.04
python:3.8.5

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

```
yolo predict line_width=10
```
![zidane](https://github.com/ultralytics/ultralytics/assets/26833433/2f89b2c6-97da-4546-87b1-11c55c043f3d)

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by UsersNGT** [comment]
> 

i am so sorry, i use your command, but the error always existing,.


root@nbook-shiht15-ht-0:/data/private/ultralytics# yolo detect predict model=detect2/train_exp1.10/weights/best.pt  source=/data/priva
te/data/train_data/head/037.png  line_width=10 project=detect2 name=ceshi                                                             
Traceback (most recent call last):                                                                                                    
  File "/opt/conda/bin/yolo", line 8, in <module>                                                                                     
    sys.exit(entrypoint())                                                                                                            
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/yolo/cfg/__init__.py", line 335, in entrypoint                             
    check_cfg_mismatch(full_args_dict, overrides)                                                                                     
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/yolo/cfg/__init__.py", line 178, in check_cfg_mismatch                     
    raise SyntaxError(string + CLI_HELP_MSG) from e                                                                                   
SyntaxError: 'line_width' is not a valid YOLO argument.
![image](https://github.com/ultralytics/ultralytics/assets/48192521/0a0d417e-461a-47f5-a8cd-56edd1c67688)

**Comment by bit-scientist** [comment]
@UsersNGT Either update ultralytics to the latest version or use `line_thickness` instead.

**Comment by UsersNGT** [comment]
> @UsersNGT Either update ultralytics to the latest version or use `line_thickness` instead.

oh. its ok when i use line_thickness.  thank you very much.

**Comment by glenn-jocher** [comment]
@UsersNGT you're welcome! We're glad to hear that using `line_thickness` fixed the issue you were experiencing. If you have any more questions or issues, do not hesitate to ask. Have a great day!
