### ISSUE TITLE
YOLOv8 builtins.AssertionError

### ISSUE THREAD

**Issue by jvkloc** [ultralytics/ultralytics#3079]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

File "/home/jvkloc/Documents/TKT/Python/Sonify/rs_main.py", line 30, in <module>
  results = model(frame)
File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/model.py", line 111, in __call__
  return self.predict(source, stream, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
  return func(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/model.py", line 250, in predict
  self.predictor.setup_model(model=self.model, verbose=is_cli)
File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/predictor.py", line 295, in setup_model
  self.model = AutoBackend(model,
File "/usr/local/lib/python3.8/dist-packages/ultralytics/nn/autobackend.py", line 82, in __init__
  pt, jit, onnx, xml, engine, coreml, saved_model, pb, tflite, edgetpu, tfjs, paddle, triton = self._model_type(w)
File "/usr/local/lib/python3.8/dist-packages/ultralytics/nn/autobackend.py", line 449, in _model_type
  if not is_url(p, check=False) and not isinstance(p, str):
File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/downloads.py", line 31, in is_url
  assert all([result.scheme, result.netloc]) # check if is url

builtins.AssertionError

### Minimal Reproducible Example

```
from ultralytics import YOLO
import cv2
import os
# set path for input video
video_path = os.path.join('/home/jvkloc/Documents/TKT/Python/Sonify', 'test_video.mp4') 
# create OpenCV VideoCapture class instance for input video frame capturing
cap = cv2.VideoCapture(video_path)
# read first frame from test video
ret, frame = cap.read()
# set YOLO model
model = YOLO('yolov8n.pt')
# detect persons in the frame with YOLO
results = model(frame)
```

### Additional

I'm trying to implement tracking to a test video using OpenCV, YOLO and DeepSORT. Minimal example shows the problem: when trying to use YOLO object detection on the captured frame, a builtins.AssertionError is raised instead of the program proceeding as expected.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@jvkloc 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. I'm unable to reproduce any error with predict or track modes on a cv2 video stream read frame by frame as in https://docs.ultralytics.com/modes/predict/#streaming-source-for-loop

<img width="1710" alt="Screenshot 2023-06-07 at 22 29 08" src="https://github.com/ultralytics/ultralytics/assets/26833433/421b5785-2b50-4730-a609-612ba6d8fc28">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃
