### ISSUE TITLE
Class probabilities. Two different confidence scores

### ISSUE THREAD

**Issue by baglanaitu** [ultralytics/ultralytics#3081]

**Comment by glenn-jocher** [comment]
These values should be identical. Are you getting different results on the same image with the same model?

**Comment by baglanaitu** [comment]
Yes, they are different for the same image

**Comment by glenn-jocher** [comment]
@baglanaitu no problem at all! Glad to hear that the issue was resolved. In general, class probabilities and confidence scores should be identical values, as they represent the same thing. If you notice differences between them in the future, please let us know and we will be happy to look into it further. Thank you for using YOLOv8!
