### ISSUE TITLE
dvclive.error

### ISSUE THREAD

**Issue by MoussaGRICHE** [ultralytics/ultralytics#3092]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Hello,
I have used several time the YOLOV8 without problem.
Today, I tried to retrain my model and I updated the ultralytics packages and when I started the training, i got this error:

      Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/jupyter-moussa/.local/lib/python3.9/site-packages/ultralytics/yolo/engine/model.py", line 371, in train
        self.trainer.train()
      File "/home/jupyter-moussa/.local/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 192, in train
        self._do_train(world_size)
      File "/home/jupyter-moussa/.local/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 275, in _do_train
        self._setup_train(world_size)
      File "/home/jupyter-moussa/.local/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 268, in _setup_train
        self.run_callbacks('on_pretrain_routine_end')
      File "/home/jupyter-moussa/.local/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 165, in run_callbacks
        callback(self)
      File "/home/jupyter-moussa/.local/lib/python3.9/site-packages/ultralytics/yolo/utils/callbacks/dvc.py", line 76, in on_pretrain_routine_end
        _log_plots(trainer.plots, 'train')
      File "/home/jupyter-moussa/.local/lib/python3.9/site-packages/ultralytics/yolo/utils/callbacks/dvc.py", line 40, in _log_plots
        _log_images(name, prefix)
      File "/home/jupyter-moussa/.local/lib/python3.9/site-packages/ultralytics/yolo/utils/callbacks/dvc.py", line 33, in _log_images
        live.log_image(os.path.join(prefix, image_path.name), image_path)
      File "/home/jupyter-moussa/.local/lib/python3.9/site-packages/dvclive/live.py", line 249, in log_image
        raise InvalidDataTypeError(name, type(val))
    dvclive.error.InvalidDataTypeError: Data 'train/labels.jpg' has not supported type <class 'pathlib.PosixPath'>

what do you think about it?

Thank you.

### Environment

ultralytics              8.0.114
torch                    2.0.1
torchaudio               0.13.1
torchvision              0.15.2
Ubuntu 22.04.1 LTS

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MoussaGRICHE 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by glenn-jocher** [comment]
@shcheklein bug report regarding DVC integration.

**Comment by glenn-jocher** [comment]
@shcheklein should we implement a minimum version here?
https://github.com/ultralytics/ultralytics/blob/3ae81ee9d11c432189e109d7a1724635a2e451ca/ultralytics/yolo/utils/callbacks/dvc.py#L13

**Comment by shcheklein** [comment]
@glenn-jocher 

> @shcheklein should we implement a minimum version here?

yes, I'm looking into this ... do you have by chance something like this in the codebase? I guess some library is needed to do semver comparison reliably (need to check this), and I didn't want to bring extra deps.

**Comment by shcheklein** [comment]
@glenn-jocher perfect! thanks. I'll introduce the check asap.

**Comment by glenn-jocher** [comment]
@shcheklein so usually we'd just run check_requirements() with your package and minimum version number if it was a required dependency, but since it's optional, we want to first attempt to import, then if successful check the version meets requirements, and if not only then update the version. This may crash in the current run as the package has already been imported, but check_requirements() will display a message during install advising the user to restart their environment after installation.

**Comment by AmmarMalik93** [comment]
> [@MoussaGRICHE](https://github.com/MoussaGRICHE) hey, sorry for this experience. If you have `dvclive` and `dvc` installed it is automatically detected and `dvclive` logs artifacts, metrics, etc in a DVC-compatible format. Please take a look here [#2792](https://github.com/ultralytics/ultralytics/pull/2792)
> 
> In your case most likely the version of `dvclive` is not compatible. Could you run `pip install -U dvclive`?
> 
> Alternatively, you can disable the automatic logger with `ULTRALYTICS_DVC_DISABLED=true`.
> 
> Let me know if that works, also I would love to know your feedback if you try the logger.

How do I disable the automatic logger with `ULTRALYTICS_DVC_DISABLED=true`.?

**Comment by glenn-jocher** [comment]
Set `ULTRALYTICS_DVC_DISABLED` **before** you start Ultralytics YOLO (and restart your notebook kernel/session if it was already imported); the DVCLive auto-logger is initialized during startup as described in the [DVC callback reference](https://docs.ultralytics.com/reference/utils/callbacks/dvc/).

```bash
# Linux/macOS
export ULTRALYTICS_DVC_DISABLED=true
yolo train model=yolo26n.pt data=coco8.yaml epochs=1
```

```bash
# Windows PowerShell
$env:ULTRALYTICS_DVC_DISABLED="true"
yolo train model=yolo26n.pt data=coco8.yaml epochs=1
```

```python
# Jupyter (run this in the first cell, then restart kernel)
import os
os.environ["ULTRALYTICS_DVC_DISABLED"] = "true"
```
