### ISSUE TITLE
Debugging Issue

### ISSUE THREAD

**Issue by ranarhall** [ultralytics/ultralytics#3106]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I tried to debug this code with VS. When it creates a model, the interactive mode of debugging gets on.
Then in one stage, when trying to execute 
`self.validator = self.get_validator()`

The model runs the following code 
`return v8.detect.DetectionValidator(self.test_loader, save_dir=self.save_dir, args=copy(self.args))`

This code tries to execute `def __getattr__(self, attr):` and an exception is raised as following.

 'IterableSimpleNamespace' object has no attribute '__setstate__'. This may be caused by a modified or out of date ultralytics

This exception is handled properly when the code is run by command line, but in debugger mode, the code fails to execute.

### Minimal Reproducible Example

`self.validator = self.get_validator()`
return v8.detect.DetectionValidator(self.test_loader, save_dir=self.save_dir, args=copy(self.args))
def __getattr__(self, attr):
raise AttributeError(f"""
            '{name}' object has no attribute '{attr}'. This may be caused by a modified or out of date ultralytics
            'default.yaml' file.\nPlease update your code with 'pip install -U ultralytics' and if necessary replace
            {DEFAULT_CFG_PATH} with the latest version from
            https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/cfg/default.yaml
            """)

### Additional

![console](https://github.com/ultralytics/ultralytics/assets/48140952/6f6eef48-3d45-45e5-bcc4-af02629a6329)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ranarhall hello, it looks like you are experiencing an issue with debugging YOLOv8 using Visual Studio. Specifically, you encounter an exception stating: "IterableSimpleNamespace' object has no attribute '__setstate__'". This seems to be specific to the interactive debugging mode, as the code executes properly in the command line. 

First, let me clarify that this issue is not unique to YOLOv8, but is related to how Python's pickle module interacts with some namespaces. 

As for a solution, it seems like updating your `ultralytics` installation to the latest version using `pip install -U ultralytics` might resolve the issue. Additionally, make sure that you have the latest version of our `default.yaml` config file from https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/cfg/default.yaml. 

If updating the packages doesn't resolve the issue, you might need to edit the `__setstate__` function in your `IterableSimpleNamespace` class to make it picklable. 

I hope this helps! Let us know if you have further questions or if this solution resolves your issue.

**Comment by ranarhall** [comment]
Thank you for your response. I have installed the latest 'ultralytics', and I tried to change the __setstate__ function too.
It seems to me that the issue only exists in debugging mode. If I try to run it using command line, there is no issue. How do you normally debug your code?

**Comment by glenn-jocher** [comment]
@ranarhall to debug I use PyCharm and place debug points wherever I want the code to stop, then run in debug mode. 

The only issues I've ever encountered were trying to debug multiprocessing areas of the code like the dataloaders. This issue is resolved by setting workers=0, but there is no error, the breakpoint simply does not stop the code at the breakpoint.

**Comment by Darknesszlx** [comment]
rm copy, return v8.detect.DetectionValidator(self.test_loader, save_dir=self.save_dir, args=self.args),
you can go on debugging but you will get the same error in here.
https://github.com/ultralytics/ultralytics/blob/c340f84ce9325de720fbd9ada6523a28fc432651/ultralytics/yolo/utils/torch_utils.py#L341

**Comment by opencvfun** [comment]
Same problem to me . I'm using Visual Studio 2002  python environment . Are there any easy solutions ？

**Comment by glenn-jocher** [comment]
@opencvfun hello! The issue you are experiencing is related to how Python's pickle module interacts with certain namespaces, like IterableSimpleNamespace, during debugging in Visual Studio 2022. This isn't specific to YOLOv8, but it's rather a common problem when working with such environments in Python.

You can try updating your 'ultralytics' installation to the latest version. This might resolve the issue on its own. Also, make sure you are using the latest version of the 'default.yaml' config file in your project.

Given that the error happens during debugging, another possible workaround could be to adjust your debugging strategy. Specifically, consider avoiding debugging in areas of code which use multiprocessing like the dataloaders, or areas that frequently interact with the IterableSimpleNamespace object. 

These suggestions might help you overcome the issue. Please let us know if the problem persists or if you have more questions.

**Comment by tERaNCarol** [comment]
I also had this problem with VS debugging and I found that if I close "User Uncaught Exceptions" in breakpoints, the debugging will run.

**Comment by glenn-jocher** [comment]
@tERaNCarol thank you for sharing this workaround! Disabling "User Uncaught Exceptions" in breakpoints can indeed help bypass the issue when debugging in Visual Studio. This is a useful tip for others facing similar challenges.
