### ISSUE TITLE
Add support for 16-bit images

### ISSUE THREAD

**Issue by MattTheCuber** [ultralytics/ultralytics#3117]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I think it would be extremely useful if you could add full support for 16-bit images. In the past you have declined this as it is not recommended and wouldn't fit well with any other models. This fact is quickly going out of date. We are working with medical type images, which are 16-bit standard. When converting to 8-bit we losing **99.6%** of the image contrast. That is a huge disadvantage for training and predictions. If you will not add a way to support 16-bit images, can you provide what files need to be modifying and possibly the precise modifications to set YOLOv8 to 16-bit?

### Use case

Medical image segmentation is becoming more and more popular. Many different frameworks are adding support or being designed for medical imaging. However, I have yet to find any models like YOLO that support 16-bit images. Adding support for 16-bit images would drastically increase that information that the model can read and use for predictions.

### Additional

Related issue in YOLOv5:
https://github.com/ultralytics/yolov5/issues/8481

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MattTheCuber thank you for reaching out to us and detailing your request. We understand the importance of having full support for 16-bit images in YOLOv8. While it is true that we previously declined this due to it not being recommended and not fitting well with other models, we recognize that circumstances have changed and the need for 16-bit support is growing. 

We appreciate your willingness to help by submitting a PR. We encourage you to do so, and we will be happy to review it. If you choose to modify the files yourself, we recommend starting with the code that reads the input image and making the necessary changes. 

Again, thank you for your request and for considering contributing to YOLOv8. We are always striving to improve and appreciate any feedback from the community.

**Comment by MattTheCuber** [comment]
@glenn-jocher Can you point me to the files that need to be modified?

**Comment by dubstepenjoyer** [comment]
Hi @glenn-jocher . I have a purely practical question (which I can’t answer myself, since I can’t test it at the moment). Will the quality of the model's predictions improve if I increase the contrast of the frames?
