### ISSUE TITLE
Multi GPU (DDP) training of the pose model fails

### ISSUE THREAD

**Issue by iperminov-mythic** [ultralytics/ultralytics#3122]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Multi-GPU

### Bug

`yolo train pose model=yolov8n-pose.pt data=coco-pose.yaml epochs=1 device=0,1,2,3` fails with 
```
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameters which did not receive grad for rank 2: model.22.cv4.2.2.bias, model.22.cv4.2.2.weight, model.22.cv4.2.1.bn.bias, model.22.cv4.2.1.bn.weight, model.22.cv4.2.1.conv.weight, model.22.cv4.2.0.bn.bias, model.22.cv4.2.0.bn.weight, model.22.cv4.2.0.conv.weight, model.22.cv4.1.2.bias, model.22.cv4.1.2.weight, model.22.cv4.1.1.bn.bias, model.22.cv4.1.1.bn.weight, model.22.cv4.1.1.conv.weight, model.22.cv4.1.0.bn.bias, model.22.cv4.1.0.bn.weight, model.22.cv4.1.0.conv.weight, model.22.cv4.0.2.bias, model.22.cv4.0.2.weight, model.22.cv4.0.1.bn.bias, model.22.cv4.0.1.bn.weight, model.22.cv4.0.1.conv.weight, model.22.cv4.0.0.bn.bias, model.22.cv4.0.0.bn.weight, model.22.cv4.0.0.conv.weight
Parameter indices which did not receive grad for rank 2: 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206
```

### Environment

Ultralytics YOLOv8.0.112 🚀 Python-3.9.5 torch-1.12.1+cu113 CUDA:0 (RTX A6000, 48685MiB)
Ubuntu 20.04.5 LTS
                                              

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@iperminov-mythic 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. I'm not able to reproduce this on our A100 server. I did notice your torch is a bit out of date, I would update it to the latest, or better train DDP in our Docker image.

<img width="1335" alt="Screenshot 2023-06-10 at 02 00 05" src="https://github.com/ultralytics/ultralytics/assets/26833433/5bf846a1-9e86-49a6-b98c-6d22030efed0">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by iperminov-mythic** [comment]
I'll try to debug it more on my side. Upgrading pytorch may take some time, because it may require upgrading the Nvidia kernel drivers.

**Comment by iperminov-mythic** [comment]
I figured it out - my COCO dataset setup got clobbered somehow. Re-downloading it solved the problem. This issue had nothing to do with Ultralytics code.

**Comment by pderrenger** [comment]
@iperminov-mythic great to hear that you figured it out! 🎉 It's always good to double-check the dataset setup. If you have any other questions or run into further issues, feel free to ask. Happy coding! 😊
