### ISSUE TITLE
While using the nvidia GPU and OpenCV library, using any YOLOv5/v8 ONNX model can´t detect objects properly on a recorded video but it can detect objects with my webcam and any image

### ISSUE THREAD

**Issue by diogovazguerra** [ultralytics/ultralytics#3125]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

Hi everyone! I have a very specific and unique problem that is quite difficult to solve without any of your help. Like it is said in the title I have a weird bug on my C++ project where I want to detect objects of an image, a recorded video (e.g mp4, etc) and my webcam with any YOLOv5/v8 ONNX model using my nvidia GPU and using OpenCV library. 

Now, the C++ source code that I use also tests detection of objects of an image, a recorded video and a webcam using the CPU, which to this three cases works flawlessly, of course it's much slower than using the GPU. With that said, when using the GPU, detecting objects of an image works fine and detection on my webcam works too, but on a recorded video detection doesn´t work properly, the video loads normally, but it doesn´t detect objects like it detects using the CPU, sometimes it actually appears like dozens even hundreds of bounding boxes out of nowhere until it crashes the program.

I have tried to search the problem if I wasn´t using the right methods when running the program with CUDA cores, but nothing, I have no clue what the problem might. The only reason I think it is, is the CUDA or cuDDN, but I'm not sure.

### Environment

- OS: WSL2 Ubuntu 22.04
Laptop hardware: 
- GPU: RTX 3070 mobile
- CPU: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
- RAM: 16 GB 3200 Mhz

- CUDA: 12.1
- cuDNN: 8.9.1
- OpenCV: 4.7.0
- YOLO: Any YOLOv5/v8 ONNX model

If you want more information please tell me.

### Minimal Reproducible Example

The code that I use to do inference was ultralytics C++ inference example on this link: https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-CPP-Inference

Then I changed the main.cpp file with this code to test images, recorded video and webcam:

``` 
int main(int argc, char **argv)
{   
    bool runOnGPU = true;

    //
    // Pass in either:
    //
    // "/source/models/yolov8s.onnx"
    // or
    // "/source/models/yolov5s.onnx"
    //
    // To run Inference with yolov8/yolov5 (ONNX)
    //
    
    Inference inf("../Perception_OpenCV/YOLOv8/yolov8s.onnx", cv::Size(640, 480),
                  "../Perception_OpenCV/YOLOv5/coco.names", runOnGPU);

    ////////////////////////// Image ////////////////////////////////

    // std::ostringstream oss;
    // oss << "../Perception_OpenCV/resources/" << argv[1];
    // std::string path = oss.str();

    // // Load image.
    // Mat frame;
    // frame = imread(path);

    // // Mat img;

    // // Inference starts here...
    // std::vector<Detection> output = inf.runInference(frame);

    // int detections = output.size();
    // std::cout << "Number of detections:" << detections << std::endl;

    // for (int i = 0; i < detections; ++i)
    // {
    //     Detection detection = output[i];

    //     cv::Rect box = detection.box;
    //     cv::Scalar color = detection.color;

    //     // Detection box
    //     cv::rectangle(frame, box, color, 2);

    //     // Detection box text
    //     std::string classString = detection.className + ' ' + std::to_string(detection.confidence).substr(0, 4);
    //     cv::Size textSize = cv::getTextSize(classString, cv::FONT_HERSHEY_DUPLEX, 1, 2, 0);
    //     cv::Rect textBox(box.x, box.y - 40, textSize.width + 10, textSize.height + 20);

    //     vector<double> layersTimes;
    //     double freq = getTickFrequency() / 1000;
    //     double t = inf.net.getPerfProfile(layersTimes) / freq;
    //     string label = format("Inference time : %.2f ms", t);
    //     cv::rectangle(frame, textBox, color, cv::FILLED);
    //     cv::putText(frame, label, Point(20, 40), FONT_FACE, FONT_SCALE, RED);
    //     cv::putText(frame, classString, cv::Point(box.x + 5, box.y - 10), cv::FONT_HERSHEY_DUPLEX, 1, cv::Scalar(0, 0, 0), 2, 0);
    // }
    // // Inference ends here...

    // float scale = 0.8;
    // cv::resize(frame, frame, cv::Size(frame.cols*scale, frame.rows*scale));
    // imshow(argv[1], frame);

    // waitKey(-1);

    ////////////////////////// Video Test /////////////////////////////

    // Video does not work with NVIDIA Graphics CUDA cores, probally CUDA functions must be properly used

    std::ostringstream oss;
    oss << "../Perception_OpenCV/resources/" << argv[1];
    std::string path = oss.str();
   
    cv::VideoCapture cap(path);

    cv::Mat frame;

    while (true)
    {
        cap.read(frame);

        // Inference starts here...
        std::vector<Detection> output = inf.runInference(frame);

        int detections = output.size();
        std::cout << "Number of detections:" << detections << std::endl;

        for (int i = 0; i < detections; ++i)
        {
            Detection detection = output[i];

            cv::Rect box = detection.box;
            cv::Scalar color = detection.color;

            // Detection box
            cv::rectangle(frame, box, color, 2);

            // Detection box text
            std::string classString = detection.className + ' ' + std::to_string(detection.confidence).substr(0, 4);
            cv::Size textSize = cv::getTextSize(classString, cv::FONT_HERSHEY_DUPLEX, 1, 2, 0);
            cv::Rect textBox(box.x, box.y - 40, textSize.width + 10, textSize.height + 20);

            vector<double> layersTimes;
            double freq = getTickFrequency() / 1000;
            double t = inf.net.getPerfProfile(layersTimes) / freq;
            string label = format("Inference time : %.2f ms", t);
            cv::rectangle(frame, textBox, color, cv::FILLED);
            cv::putText(frame, label, Point(20, 40), FONT_FACE, FONT_SCALE, RED);
            cv::putText(frame, classString, cv::Point(box.x + 5, box.y - 10), cv::FONT_HERSHEY_DUPLEX, 1, cv::Scalar(0, 0, 0), 2, 0);
        }
        // Inference ends here...

        float scale = 0.8;
        cv::resize(frame, frame, cv::Size(frame.cols*scale, frame.rows*scale));

        cv::imshow("Video", frame);
        if(cv::waitKey(100) == 27) break; // Wait for 'esc' key press to exit
    }
    
    /////////////////////////// Webcam //////////////////////////////
    
    // cv::VideoCapture cap;
    // cap.open(0, cv::CAP_V4L2);
    // cap.set(cv::CAP_PROP_FOURCC, cv::VideoWriter::fourcc('M', 'J', 'P', 'G'));

    // if( !cap.isOpened() ) {

	//     std::cerr << "couldn't open capture."<< std::endl;
	//     return -1;
    // }

    // cv::Mat frame;
    // cv::namedWindow("webcam", cv::WINDOW_AUTOSIZE);

    // Mat result;

    // while(true)
    // {
    //     cap >> frame;

    //     // Inference starts here...
    //     std::vector<Detection> output = inf.runInference(frame);

    //     int detections = output.size();
    //     std::cout << "Number of detections:" << detections << std::endl;

    //     for (int i = 0; i < detections; ++i)
    //     {
    //         Detection detection = output[i];

    //         cv::Rect box = detection.box;
    //         cv::Scalar color = detection.color;

    //         // Detection box
    //         cv::rectangle(frame, box, color, 2);

    //         // Detection box text
    //         std::string classString = detection.className + ' ' + std::to_string(detection.confidence).substr(0, 4);
    //         cv::Size textSize = cv::getTextSize(classString, cv::FONT_HERSHEY_DUPLEX, 1, 2, 0);
    //         cv::Rect textBox(box.x, box.y - 40, textSize.width + 10, textSize.height + 20);

    //         vector<double> layersTimes;
    //         double freq = getTickFrequency() / 1000;
    //         double t = inf.net.getPerfProfile(layersTimes) / freq;
    //         string label = format("Inference time : %.2f ms", t);
    //         cv::rectangle(frame, textBox, color, cv::FILLED);
    //         cv::putText(frame, classString, cv::Point(box.x + 5, box.y - 10), cv::FONT_HERSHEY_DUPLEX, 1, cv::Scalar(0, 0, 0), 2, 0);
    //         cv::putText(frame, label, Point(20, 40), FONT_FACE, FONT_SCALE, RED);
    //     }
    //     // Inference ends here...
       
    //     float scale = 0.8;
    //     cv::resize(frame, frame, cv::Size(frame.cols*scale, frame.rows*scale));

    //     imshow("webcam", frame);

    //     if(cv::waitKey(1) == 27) break; // Wait for 'esc' key press to exit
    // }

    // cap.release();

    return 0;
}

```

To give more context, to use any of the three cases formats, I need to uncomment one format output and comment the other two cases, in this case video test is the one uncommented and ready to go.

### Additional

Print Screen of a video detecting unintended object out of nowhere:
![image](https://github.com/ultralytics/ultralytics/assets/101196708/3717c7ca-21f0-40c4-9877-b6b6e4e08c72)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@diogovazguerra i appreciate your detailed feedback and your efforts to address the issues encountered. It seems you've thoroughly inspected various aspects of your C++ project and have made some valid observations. Let's address the points you've raised one by one:

1) Correct video file loading: It's good to know that the video file loads correctly, which implies the issue might be related to the detection process or the interaction between the YOLOv8 model and the video frames.

2) Video format compatibility: It's helpful that you've tested both MP4 and AVI formats, but the problem persists. This indicates that the issue is not related to the video format or codec.

3) Debugging inference: To debug the inference process, you can insert print statements or use a debugger to inspect the intermediate results during the inference. For example, you can print the model's input and output tensors, or any intermediate processing steps, to gain insights into how the model is processing the video frames.

4) Inference consistency across CPU and GPU: It's notable that the detection works on a CPU but not on a GPU. This could indicate a potential issue with GPU-specific operations or memory transfers during inference.

5) Memory-related issues: It's good to verify that there are no memory leaks and that GPU VRAM utilization remains low. To ensure this, you can monitor GPU memory usage during video processing, especially when using the GPU for inference.

6) Exception handling with OpenCV: OpenCV functions can throw exceptions in exceptional situations. You can use traditional C++ exception handling to catch and handle these exceptions. For example, you can use try-catch blocks to handle potential errors during video capture, frame processing, or inference.

Based on your detailed analysis, it appears that the issue might be related to GPU-specific operations or interactions between the YOLOv8 model and the GPU. To address this, you might want to inspect the GPU-specific parts of your code, such as memory transfers, model initialization, or GPU-specific configuration.

Additionally, consider conducting experiments to isolate the issue. For example, you can test the inference with a simple, known video file to check if the issue persists.

Feel free to continue discussing the specifics of the C++ project, as this will help in pinpointing the root cause of the problem. I'm here to assist further in troubleshooting the detection issue on recorded videos with YOLOv8 and OpenCV in a GPU-accelerated environment.
