### ISSUE TITLE
TypeError: new(): invalid data type 'str'

### ISSUE THREAD

**Issue by apiszcz** [ultralytics/ultralytics#3135]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

    for _ in gen:  # running CLI inference without accumulating any outputs (do not modify)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 64, in generator_context
    response = gen.send(request)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/predictor.py", line 244, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/v8/detect/predict.py", line 14, in postprocess
    preds = ops.non_max_suppression(preds,
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/ops.py", line 231, in non_max_suppression
    x = x[(x[:, 5:6] == torch.tensor(classes, device=x.device)).any(1)]
TypeError: new(): invalid data type 'str'

### Environment

Ubuntu 22
yolov8 ultalytics latest installation updated today.

### Minimal Reproducible Example

yolo detect cfg=customconfig

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. I'm not able to reproduce any problems using the `cfg` argument. Note that the cfg argument will contain mode and task. I ran this below without error:

<img width="981" alt="Screenshot 2023-06-11 at 19 49 33" src="https://github.com/ultralytics/ultralytics/assets/26833433/d8a2f4ee-10a6-476b-8b7a-ec5713d3c6da">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by apiszcz** [comment]
Thanks.
My error, i had single quotes around the index values in classes.

**Comment by pderrenger** [comment]
@apiszcz no problem at all! It's great to hear that you've identified the issue. Happy coding, and feel free to reach out if you have any more questions or run into any other issues! 🚀
