### ISSUE TITLE
keypoint extention

### ISSUE THREAD

**Issue by swe-cognitica** [ultralytics/ultralytics#3149]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have disabled the bounding box. Is it possible to modify the size of the keypoint(extend the keypoint) and make it like a  box instead of just point.

**Comment by pderrenger** [comment]
@swe-cognitica yes, YOLOv8 does support keypoint estimation, which can be extended to cover a larger area rather than just a single point. This can be achieved by adjusting the keypoint estimation model to output a larger area, effectively creating a box around the keypoint. You can modify the keypoint estimation model through the Pose Mode in YOLOv8 to achieve this. If you're using another mode or need more specific guidance, please let me know!
