### ISSUE TITLE
Using ONNX with Ultralytic's YOLO doesn't work

### ISSUE THREAD

**Issue by kopyl** [ultralytics/ultralytics#3220]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I get this error:

```
InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: images for the following indices
 index: 2 Got: 640 Expected: 800
 index: 3 Got: 640 Expected: 800
 Please fix either the inputs or the model.
```

My code:
```
from PIL import Image
import requests
from ultralytics import YOLO

image = Image.open(requests.get("https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/fb2c6c74-97ee-4cda-fda4-8ea23f892200/width=707/8651cacc-5138-4053-e11a-a170817ffd00.jpeg", stream=True).raw).convert("RGB")
image = image.resize((800, 800))

model_onnx = YOLO("yolov8_custom_trained_model_c.onnx")
results = model_onnx.predict(image)
```

Why? How can I fix it?

### Environment

- YOLO: Ultralytics YOLOv8.0.117
- OS: Ubuntu 22.04.2 LTS
- Python: 3.10.6

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@kopyl 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. ONNX export and inference works correctly:

<img width="907" alt="Screenshot 2023-06-17 at 18 42 35" src="https://github.com/ultralytics/ultralytics/assets/26833433/c54f76b5-cc19-4a1a-b223-d33be7dbc860">


We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by kopyl** [comment]
@glenn-jocher it indeed works with https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt .

But does not work with a trained model ( https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/train-yolov8-object-detection-on-custom-dataset.ipynb )

Link to my trained model: https://audios-ai.s3.amazonaws.com/yolov8_custom_trained_model.pt
Link to the same model in ONNX (exported with Ultralytics): https://audios-ai.s3.amazonaws.com/yolov8_custom_trained_model.onnx

**Comment by glenn-jocher** [comment]
@kopyl hi there,

Thank you for reaching out about this issue. It seems that the trained model you shared (`yolov8_custom_trained_model.pt`) is not compatible with the ONNX format. 

While Torch inference works as expected with this model, the ONNX export process might introduce some inconsistencies that result in the error you mentioned. 

To investigate further, we would need a minimal, reproducible example that showcases the issue with the trained model. This would help us understand the problem better and provide more precise assistance.

Additionally, please ensure that you are using the latest version of YOLOv8 from the Ultralytics repository to rule out any potential compatibility issues.

Thank you for your cooperation, and we look forward to helping you resolve this issue with YOLOv8.

**Comment by kopyl** [comment]
@glenn-jocher but I exported it to onnx with Ultralytics’ YOLO('model.pt').export(format='onnx') and it exporter the onnx model I just shared.

I was able to make the ONNX inference work with this tool: https://github.com/ibaiGorordo/ONNX-YOLOv8-Object-Detection
But was not with Ultralytics’ YOLO.

**Comment by glenn-jocher** [comment]
@kopyl hi there, 

Thank you for your feedback and for providing additional context. We apologize for any confusion. 

The issue you encountered where the ONNX model exported using Ultralytics' YOLOv8 didn't work might be due to some inconsistencies in the export process. While the model you shared was successfully exported to ONNX format using Ultralytics' YOLOv8, it seems that there might be compatibility issues when using that ONNX model with YOLOv8.

It's worth noting that the export process involves converting the model to a different format and there can be variations in how different tools handle the export/import process. The tool you mentioned, GitHub.com/ibaiGorordo/ONNX-YOLOv8-Object-Detection, might have implemented the import process differently, allowing it to work for your specific ONNX model.

We appreciate your patience and understanding. If you have any further questions or need additional assistance with Ultralytics' YOLOv8, please don't hesitate to let us know. Thank you!

**Comment by kopyl** [comment]
@glenn-jocher it is reproducible, why did you mark it as non-one?

Ultralytics library doesn't detect model's input size unlike https://github.com/ibaiGorordo/ONNX-YOLOv8-Object-Detection and you have to specify `imgsz` when doing the onnx inference.

Why??? Can you fix it?

**Comment by kopyl** [comment]
@glenn-jocher I believe it's "inconsistencies" in the code writing process of Ultralytics' library

**Comment by glenn-jocher** [comment]
@kopyl Apologies for the confusion earlier. The issue you encountered with the ONNX export/import process in Ultralytics' YOLOv8 library seems to be related to the detection of the model's input size.

Currently, Ultralytics' YOLOv8 library does not automatically detect the input size of the model. This means that you need to manually specify the input size using the `imgsz` parameter when performing ONNX inference.

In contrast, the tool you mentioned, GitHub.com/ibaiGorordo/ONNX-YOLOv8-Object-Detection, might have implemented a different approach that automatically determines the input size. This could explain why it works for your specific ONNX model.

To address this issue, one potential solution could be to enhance Ultralytics' YOLOv8 library to automatically detect the input size of the model during the ONNX export/import process. This would provide a more seamless experience for users and eliminate the need for manual input size specification.

Thank you for bringing this to our attention, and we appreciate your feedback. We will consider this improvement for future updates to the library. If you have any further questions or concerns, please let us know, and we'll be happy to assist you.

**Comment by ammar-deep** [comment]
> @kopyl Apologies for the confusion earlier. The issue you encountered with the ONNX export/import process in Ultralytics' YOLOv8 library seems to be related to the detection of the model's input size.
> 
> Currently, Ultralytics' YOLOv8 library does not automatically detect the input size of the model. This means that you need to manually specify the input size using the `imgsz` parameter when performing ONNX inference.
> 
> In contrast, the tool you mentioned, GitHub.com/ibaiGorordo/ONNX-YOLOv8-Object-Detection, might have implemented a different approach that automatically determines the input size. This could explain why it works for your specific ONNX model.
> 
> To address this issue, one potential solution could be to enhance Ultralytics' YOLOv8 library to automatically detect the input size of the model during the ONNX export/import process. This would provide a more seamless experience for users and eliminate the need for manual input size specification.
> 
> Thank you for bringing this to our attention, and we appreciate your feedback. We will consider this improvement for future updates to the library. If you have any further questions or concerns, please let us know, and we'll be happy to assist you.

Looks like ChatGPT is replying.

**Comment by glenn-jocher** [comment]
Hi @ammar-deep,

Apologies for any confusion caused earlier. The issue you encountered with the ONNX export/import process in Ultralytics' YOLOv8 library is related to the detection of the model's input size. Unlike the tool you mentioned, Ultralytics' YOLOv8 library does not automatically detect the input size of the model. As a result, you need to manually specify the input size using the `imgsz` parameter when performing ONNX inference.

We understand that this manual input size specification can be inconvenient. To address this, we are considering enhancing Ultralytics' YOLOv8 library to automatically detect the input size of the model during the ONNX export/import process. This improvement would make the experience more seamless for users and eliminate the need for manual input size specification.

Thank you for bringing this to our attention, and we appreciate your feedback. If you have any further questions or concerns, please let us know, and we'll be happy to assist you.

Best regards,
Ultralytics YOLOv8 Team
