### ISSUE TITLE
making changes in the number of Yolov8l layers

### ISSUE THREAD

**Issue by moahaimen** [ultralytics/ultralytics#3246]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hello @glenn-jocher 
I wish you are well, I need to make some changes in  Yolov8l layers, I work on Google Colab, and i installed the 
Yolov8 on Google Colab pro in a folder named "Yolov8" because when I install yolov8 without a specific folder it doesn't appear for me in the files of Colab I don't know why, and then I went to 
/content/yolov8/ultralytics/models/v8/yolov8.yaml
I made some changes there but i faced two problems
1- when I complete the changes add more layers i mean and save the file i noticed, when re-opening the file the changes disappear, and  the file return to its origin
2- I deleted the file entirely and made a training I notice the training initialized normally without any error
!yolo task=detect mode=train model=yolov8l.pt data=/content/datasets/data.yaml epochs=75 imgsz=640
I even deleted the whole "v8" folder and no effect at all,
I wish really you can help me with this issue 
@glenn-jocher 
thank you very much

**Comment by glenn-jocher** [comment]
@moahaimen hi,

Thank you for reaching out and explaining your issue regarding making changes to the YOLOv8l layers. I appreciate your kind words. 

Regarding the first problem you mentioned, it seems that the changes you made to the yolov8.yaml file are not being saved. This could happen if you are not saving the file properly after making the changes. Make sure to save the file after editing it, and check if the changes are reflected when you reopen the file.

Regarding the second problem, deleting the "v8" folder will have no effect on the training process because the training uses the pre-trained yolov8l.pt model. Deleting the files or the folder will not affect the training process itself.

To make changes to the YOLOv8l architecture, you need to edit the yolov8.yaml file, specifically the `model` section. Make sure to save the file after making the changes, and the training process should initialize normally.

If you have any further questions or need additional assistance, please let me know. I'm here to help.

Best regards,
Glenn

**Comment by moahaimen** [comment]
@glenn-jocher thanks for answering now i saved the Yolov8.yaml
and i made changes in it calling new Blocks that i coded in the /content/yolov8/ultralytics/nn/modules/block.py
is that the correct place to add the blocks, i added a 2 classes of new blocks to it  and called them in the layers of the Yolov8.yaml i wish it will work
i used this instruction to train yolo, i wish it works.
!yolo task=detect mode=train model=yolov8l.yaml data=/content/datasets/data.yaml epochs=75 imgsz=640

is that will be correct?

**Comment by glenn-jocher** [comment]
Hi @moahaimen, 

Thank you for your question. I appreciate your interest in customizing the YOLOv8 architecture.

To add new blocks to YOLOv8, you can indeed use the /content/yolov8/ultralytics/nn/modules/block.py file. This file contains the implementation of various building blocks that are used in the YOLOv8 model.

To incorporate the new blocks into YOLOv8, you will need to call them in the layers of the Yolov8.yaml file. Make sure to correctly specify the configuration for the new blocks, including any necessary parameters or dimensions.

Once you have made these changes, you should be able to proceed with training using the `!yolo task=detect mode=train model=yolov8l.yaml data=/content/datasets/data.yaml epochs=75 imgsz=640` command, and the modified YOLOv8 architecture will be used for training.

If you encounter any further issues or have additional questions, please let me know. I'm here to help.

Best regards,
Glenn

**Comment by moahaimen** [comment]
thank you for answering @glenn-jocher , i made the code 
and made changes in the yaml file putting in backbone of this block 
 - [-1, 1, MDC, [64, 128]] 
 then inserted the MDC block in blocks.py
but when i execute the 
yolo task=detect mode=train model=/content/yolov8/ultralytics/models/v8/yolov8.yaml data=/content/Weapon-Detection_merged-5/data.yaml epochs=75 imgsz=640

this error appears
"WARNING ⚠️ no model scale passed. Assuming scale='n'.

                   from  n    params  module                                       arguments                     
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/cfg/__init__.py", line 371, in entrypoint
    model = YOLO(model, task=task)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/model.py", line 105, in __init__
    self._new(model, task)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/model.py", line 138, in _new
    self.model = TASK_MAP[self.task][0](cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py", line 233, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=ch, verbose=verbose)  # model, savelist
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py", line 626, in parse_model
    m = getattr(torch.nn, m[3:]) if 'nn.' in m else globals()[m]  # get module
KeyError: 'MDC'"


the MDC is not defined and it is not called in Yaml, how can i call  with no errors please

**Comment by glenn-jocher** [comment]
Hi @moahaimen,

It seems that you are encountering an error because the MDC module is not defined and called in the Yaml file. The error message indicates a KeyError for 'MDC', which suggests that the MDC module is not recognized.

To resolve this issue, you need to ensure that the MDC module is properly imported into the Yaml file. Although you mentioned adding an import statement in the Yaml file, it doesn't seem to be working.

One potential solution is to try importing the MDC module in the /content/yolov8/ultralytics/nn/modules/block.py file itself. This will ensure that the MDC module is available when the Yaml file is being parsed.

Please make sure that the import statement is placed in the block.py file before the definition of the MDC class. Once you have done this, try running the training command again, and the error should be resolved.

If you continue to face any issues or have additional questions, please let me know. I'm here to assist you.

Best regards,
Glenn

**Comment by moahaimen** [comment]
> One potential solution is to try importing the MDC module in the /content/yolov8/ultralytics/nn/modules/block.py file itself. This will ensure that the MDC module is available when the Yaml file is being parsed.

i didnt understand how to import it while i already wrote it in block.py could please make more explination  about that?

**Comment by moahaimen** [comment]
@glenn-jocher  please check the above i  really need a help in this

**Comment by moahaimen** [comment]
@glenn-jocher i need to make these change , i need just your help to know what and where to change the code so it works , its crucial to my study please

**Comment by glenn-jocher** [comment]
Hi @moahaimen,

I apologize for the confusion. To import the MDC module properly in the Yaml file, you can follow these steps:

1. In the /content/yolov8/ultralytics/nn/modules/block.py file, locate the line where you defined the MDC class.
2. Just above the class definition of MDC, add the following import statement: `from .block import MDC`. This will import the MDC module into the block.py file itself.
3. Save the block.py file after making this modification.

By adding the import statement as mentioned above, you ensure that the MDC module is available when the Yaml file is being parsed.

Once you have made these changes, try running the training command again with the modified Yaml file. The error mentioning `'MDC'` should be resolved, and the MDC module will be recognized correctly.

Please give this solution a try, and let me know if you encounter any further issues or have any additional questions. I'm here to assist you.

Best regards,
Glenn

**Comment by moahaimen** [comment]
@glenn-jocher  for three weeks and still couldnt solve this problem in Google colab i am so depressed , i wish i have a better pc so i dont use colab its very boring

**Comment by glenn-jocher** [comment]
@moahaimen hi,

I understand that you have been working on resolving an issue with YOLOv8 in Google Colab, and it has been causing frustration for you. I'm sorry to hear that you're feeling depressed about this situation.

Working with complex projects like YOLOv8 can sometimes be challenging, especially when dealing with different environments like Google Colab. It's important to keep in mind that technical issues and limitations can arise, and it's not always a reflection of your abilities or the quality of your PC.

While Google Colab can be a convenient solution for certain tasks, it does have some limitations due to its cloud-based nature. If you're experiencing difficulties, I would suggest considering alternative environments, such as running the code on a local machine with higher processing power or using other cloud-based platforms if available to you.

Remember that it's okay to take breaks and seek support when facing challenges. You can reach out to the community or the project's repository for assistance and advice. Sometimes a fresh perspective or new ideas can help overcome obstacles.

I hope you find a solution soon and regain your enthusiasm for the project. Don't hesitate to ask for help and take care of yourself during this process.

Best regards,
Glenn

**Comment by moahaimen** [comment]
@glenn-jocher Thank for responding I solved the Issue but the problems are
1-  I don't know where is the resulted detection, when i make detection, the Python code works  but where is the resulting video I don't know

2-  my professor wants to make a real-time detection on a YouTube video using Yolov8, but detection is happening but i can't see the video unless the detection ends and I play the resulting video,  my prof. wants to see the detection on video in real-time, I worked on Google Colab, and on my PC still have the same problem also I used Opencv, and couldn't solve the issue, can you help me, please?

**Comment by glenn-jocher** [comment]
@moahaimen hi there,

I'm glad to hear that you were able to solve the initial issue! Now, let's address the problems you mentioned:

1. Regarding the location of the resulting detection: After running the detection code in YOLOv8, the detections are generally stored in a specified output directory. You can check the code to find the output directory location. It's typically defined within the code or specified as a command-line argument when running the script. Look for the code snippet where the output video or image is saved, and make sure the file path and format are correctly specified.

2. Real-time detection on a YouTube video: To achieve real-time detection on a YouTube video, you need to perform the detection on each frame of the video in real-time. One way to do this is by using OpenCV to read frames from the video stream, pass each frame through the YOLOv8 model for detection, and then display the frame with bounding boxes in real-time. You can use OpenCV's `cv2.imshow()` function to achieve this. Make sure to iterate through each frame of the video, apply the detection, and display the resulting frames in real-time.

If you're still facing issues with real-time video detection, please provide more details about the specific errors or challenges you're encountering, and I'll be happy to assist you further.

Best regards,
Glenn

**Comment by moahaimen** [comment]
@glenn-jocher thank you for answering, i used both CLI and python code to detect a realtime youtube video or a downloaded video but i couldnt find the detected video
1- can you give an example code or a link for an example for how to detect and save the video in certain path? Also i found many options realated to CLl yolo predicate like show =true
Where i can find the full parameters i can use with python or CLI
2- i did my best in writing code for detecting frame by frame but since i am not ao familiar with this can you please advice how to do that?

**Comment by glenn-jocher** [comment]
@moahaimen hi,

To detect and save a video using YOLOv8, you can utilize the YOLOv8 Python code and OpenCV. Here's an example of how you can achieve this:

1. Specify the path to the video file.
2. Initialize the YOLOv8 model and load the pre-trained weights.
3. Set up a video reader using OpenCV to read frames from the video.
4. Iterate through each frame of the video:
   - Pass each frame through the YOLOv8 model for object detection.
   - Draw bounding boxes and labels on the frames for detected objects.
   - Display the frames in real-time using OpenCV's `cv2.imshow()` function.
   - Write the frames to an output video file using OpenCV's `cv2.VideoWriter()` function.
5. Release the video reader and writer, and close any open windows.

Regarding your second question about detecting frame by frame, you're on the right track. By looping through each frame of the video and applying the detection on each frame individually, you'll achieve frame-by-frame detection. Make sure to display each frame with bounding boxes in real-time to get the desired real-time detection output.

As for the parameters you can use, the Python code and CLI options for YOLOv8 vary slightly. To find the full list of parameters available for the YOLOv8 model in Python code, you can refer to the script or documentation provided with the YOLOv8 repo. For the CLI options, you can run the command `yolo --help` to see all available options and their descriptions.

I hope this helps! If you have any more questions or need further assistance, please let me know.

Best regards,
Glenn

**Comment by yashzambre** [comment]
Hello @glenn-jocher , Hope you are doing well. I would like to thank you for all the support that you have been giving for Ultralytics.
I am doing something similar to the issue you raised above. I want to alter the YOLOV8 architecture. 
My main goal is to add another layer of custom convolution layer on the top of the backbone. 
I have changed the block.py and the yolov8.yaml but when i print out the model.info() i still get 225 layers where as i expect to see 226 ( added custom layer).

Could you please help me in this situation? 
Help is appreciated in advance.
Thank you !

**Comment by glenn-jocher** [comment]
@yashzambre hello! I'm glad to hear you're utilizing and customizing the YOLOv8 architecture.

If you don't see your custom layer reflected in the model.info(), it suggests that the layer may not be correctly added or recognized in the model structure.

Here are a few things you should check:

1. Block Definition: Ensure that your custom layer is correctly defined in block.py. Also, ensure that the layer follows the conventions used for other layers in the file.

2. YAML Changes: Make sure the new layer you've created is correctly referenced in yolov8.yaml. This configuration file dictates the architecture of the model, including layers.

3. Name of the Layer: Ensure that the custom layer name defined in block.py and yolov8.yaml matches. Discrepancies here could result in the layer not being recognized correctly.

4. Model Reload: After making changes in the code, make sure you've reloaded or re-initialized your YOLOv8 model. Without this your changes may not be reflected properly.

I hope these steps help you in adding your custom layer to the YOLOv8 architecture. Feel free to reach out if you need further assistance. 

Best regards,
Glenn
