### ISSUE TITLE
Comparing YOLOv8x vs Cascade RCNN on human detection

### ISSUE THREAD

**Issue by ardha27** [ultralytics/ultralytics#3248]
### Search before asking

- [ ] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

So, i'm trying to find the best model to do people detection. I tried to do validation on YOLOv8x (single stage) and Cascade RCNN from detectron2 (two stage) using COCO Dataset. YOLOv8 got 0.644 AP and Cascade RCNN got 0.57 AP on person detection. But, when i try to inference a video using both model. Cascade can detect 2-3x amount of people than YOLOv8 on the same video with > 0.5 conf

Is it possible to have result like this? Is there maybe something wrong with how i test both model?

**Comment by glenn-jocher** [comment]
@ardha27 mAP is a metric of the area under the PR curve. By increasing confidence threshold you're purposefully reducing recall, so if you want to increase recall you should clearly not use a 0.5 confidence threshold but something lower.

**Comment by kongyanye** [comment]
@ardha27 Hi, I'm also interested in this issue. I did some research online and found typically Cascade RCNN is better on generalization ability than YOLO. The main advantage of YOLO is that it's super fast. But for small objects, Cascade RCNN would be better.

**Comment by glenn-jocher** [comment]
Hello @kongyanye and thanks for your insights!

You're correct in your assessment. In a nutshell, YOLOv8 excels in speed and efficiency, making it ideal for real-time object detection tasks, while Cascade RCNN has better performance on small objects and greater generalization ability due to its hierarchical structure.

The differences you're seeing between the two models could be due to the fundamental differences in their architectures. Cascade RCNN is a two-stage detector that has a region proposal network (RPN) and then refines these proposals, which can often lead to better detection performance especially for small and hard-to-detect objects. YOLOv8, on the other hand, being a single-stage detector, is optimized for speed and simplicity.

Comparing these two architectures is akin to comparing apples to oranges – each has its strengths and drawbacks, and the choice largely depends on your use case and requirements. When it comes to object detection tasks, it's often worthwhile to try out different architectures and fine-tune the model to best serve your specific goal.
