### ISSUE TITLE
In Start Training，Doesn't it support the training of grayscale images?

### ISSUE THREAD

**Issue by OneMuMuYan** [ultralytics/ultralytics#3249]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

train: Scanning E:\software\DeepLearning\PyCharm\06_yolo_v8_pro\datasets\hydrogels-seg\labels\train.cache... 80 images, 0 backgrounds, 0 corrupt: 100%|██████████| 80/80 [00:00<?, ?it/s]
val: Scanning E:\software\DeepLearning\PyCharm\06_yolo_v8_pro\datasets\hydrogels-seg\labels\val.cache... 20 images, 0 backgrounds, 0 corrupt: 100%|██████████| 20/20 [00:00<?, ?it/s]
Plotting labels to runs\segment\train14\labels.jpg... 
optimizer: AdamW(lr=0.001667, momentum=0.9) with parameter groups 66 weight(decay=0.0), 77 weight(decay=0.0005), 76 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 0 dataloader workers
Logging results to runs\segment\train14
Starting training for 2 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/80 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "E:\software\DeepLearning\PyCharm\06_yolo_v8_pro\ultralytics\yolo\utils\loss.py", line 206, in __call__
    targets = torch.cat((batch_idx, batch['cls'].view(-1, 1), batch['bboxes']), 1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 11 but got size 0 for tensor number 1 in the list.

The above exception was the direct cause of the following exception:

### Additional

help、help????
The Train Code is:

from ultralytics import YOLO
if __name__ == '__main__':
        model = YOLO('yolov8n-seg.yaml')
        model.train(data="../datasets/hydrogels-seg/hydrogels-seg.yaml", epochs=2, batch=1, imgsz=640)  # 训练模型

**Comment by glenn-jocher** [comment]
@zhoujinjin1 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Y-T-G** [comment]
Duplicate of https://github.com/ultralytics/ultralytics/issues/6929
