### ISSUE TITLE
Runtime error while training RT-DETR model

### ISSUE THREAD

**Issue by Adeelbek** [ultralytics/ultralytics#3256]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I tried to train RT-DETR large model with my custom dataset. Initial 8 epochs went well until I got the following error in end of epoch 8. I upgraded my ```ultralytics``` library and run the training again but got the same issue. I think it looks like some bug while performing matrix multiplication (I suspect some of the matrix elements may contain NaN values). 

I appreciate if you consider this error. 

```

 Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
      8/100      13.8G      1.937     0.2815     0.7642         36        640: 100%|██████████| 17/17 [00:06<00:00,  2.80it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|          | 0/9 [00:00<?, ?it/s]
Backend TkAgg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/root/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/root/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/root/.vscode-server/extensions/ms-python.python-2023.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "convert_ppdet2torch.py", line 5, in <module>
    model.train(data="mold.yaml")
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/vit/rtdetr/model.py", line 106, in train
    self.trainer.train()
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 371, in _do_train
    self.metrics, self.fitness = self.validate()
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 477, in validate
    metrics = self.validator(self)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/yolo/engine/validator.py", line 165, in __call__
    self.loss += model.loss(batch, preds)[1]
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/nn/tasks.py", line 443, in loss
    loss = self.criterion((dec_bboxes, dec_scores),
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/vit/utils/loss.py", line 253, in forward
    total_loss = super().forward(pred_bboxes, pred_scores, batch)
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/vit/utils/loss.py", line 233, in forward
    total_loss = self._get_loss(pred_bboxes[-1],
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/vit/utils/loss.py", line 192, in _get_loss
    match_indices = self.matcher(pred_bboxes,
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/vit/utils/ops.py", line 110, in forward
    indices = [linear_sum_assignment(c[i]) for i, c in enumerate(C.split(gt_groups, -1))]
  File "/opt/conda/lib/python3.8/site-packages/ultralytics/vit/utils/ops.py", line 110, in <listcomp>
    indices = [linear_sum_assignment(c[i]) for i, c in enumerate(C.split(gt_groups, -1))]
  File "/opt/conda/lib/python3.8/site-packages/scipy/optimize/_lsap.py", line 101, in linear_sum_assignment
    a, b = _lsap_module.calculate_assignment(cost_matrix.T)
ValueError: matrix contains invalid numeric entries

```

### Minimal Reproducible Example

```
# Running code and data is in the darknet ''txt'' format
from ultralytics import RTDETR
model = RTDETR('rt-detr-l.yaml')
model.info()
model.train(data="my_data.yaml")

```

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Adeelbek hi there,

Thank you for reporting this issue and providing detailed information. I apologize for the inconvenience you are experiencing.

The error you encountered during training the RT-DETR model with your custom dataset seems to be related to a matrix containing invalid numeric entries. This could potentially be caused by some matrix elements containing NaN values. 

To investigate this further, I would recommend checking your custom dataset and ensuring that it does not contain any NaN values or any other irregularities. You can also try inspecting the input data to preprocessing and check if there are any missing or incorrect values.

If the issue persists after verifying your dataset, it would be helpful if you could provide additional information about your environment, such as the versions of the Ultralytics library, Python, and PyTorch that you are using. Additionally, if possible, a minimal reproducible example (including code and sample data) would greatly assist in understanding the issue and finding a solution.

Thank you for your willingness to help by submitting a PR! Your contribution would be greatly appreciated in resolving this issue. If you have any further questions or need assistance, please feel free to ask.

Best regards,
Glenn Jocher

**Comment by Adeelbek** [comment]
Thanks for your quick reply. 

Using the same custom dataset, I trained YOLOv8-n,s, and m models without any issues or errors. 
I will try to train it with ```coco128``` and report the results once I will get it. 

Thanks~~

**Comment by glenn-jocher** [comment]
@Adeelbek hi there,

Thank you for providing additional information. It's interesting that you were able to train YOLOv8-n,s, and m models with the same custom dataset without any issues or errors. It would be helpful to understand why you encountered the error specifically when training the RT-DETR model.

It's a good idea to try training the model with the `coco128` dataset and see if you encounter the same error. This will help narrow down whether the issue is specific to your custom dataset or if it is a more general problem with the RT-DETR model.

Please let us know the results once you have trained the model with `coco128`. We appreciate your patience and contribution in helping us investigate and resolve this issue.

Best regards,
Glenn Jocher

**Comment by Adeelbek** [comment]
I trained with ``` coco128 ``` dataset and everything went smooth without errors. 
I don't have any idea why my custom dataset is ok while training any ```yolov8``` model except ```rt-detr```. 

Thanks for giving me clue ~~~

**Comment by Laughing-q** [comment]
@Adeelbek hi, this is because there are NaN values produced in your training process. The rtdetr training with `amp=True` is more sensitive than yolo models to datasets because of  the parameter initialization(which we might figure out better solution for this in the future). For now there're two ways to solve your issue:
- try training with pretrained rtdetr weights instead of training from scratch.
- set `amp=False` for your training, but this would occupy more cuda memory.

**Comment by Adeelbek** [comment]
@Laughing-q Thanks for your kind reply. Could you please give me more detail on how to set ```amp=False```. 
Actually, in my scenario, I have only one class. Probable this may also be causing some issues. 
However, I have checked my all labels and removed the ones which have no Bbox coordinates and class ids (empty labels). 

Thanks~~

**Comment by op-newman** [comment]
Yes, I also encountered this issue. I ran my own data on YOLOV8n/s///without any issues. My epoch can even run up to 100, but the RTDETR train is problematic. I encountered the above problem. ValueError: matrix contains invalid numerical entries. If you could provide me with a laptop for RTDETR training my data, it might be more helpful, Currently, I enjoy using some datasets on Roboflow for testing. Today, I tested three datasets and encountered this frustrating issue

**Comment by op-newman** [comment]
> @Laughing-q Thanks for your kind reply. Could you please give me more detail on how to set . Actually, in my scenario, I have only one class. Probable this may also be causing some issues. However, I have checked my all labels and removed the ones which have no Bbox coordinates and class ids (empty labels). After removing all empty labels, I ran the training again and ended up with the same error, )))`amp=False`
> 
> Thanks~~

Thank you very much. I have also encountered some issues at the moment. Firstly, Ultratics' RTDETR is used to train my own data. What kind of annotation is needed? Is it in Coco's JSON or Yolov8's txt format.

Secondly, I am not currently using the PaddlePaddle version. May I ask how difficult it is to training RTDETR compared to YOLOv8.

**Comment by Laughing-q** [comment]
> @Laughing-q Thanks for your kind reply. Could you please give me more detail on how to set `amp=False`. Actually, in my scenario, I have only one class. Probable this may also be causing some issues. However, I have checked my all labels and removed the ones which have no Bbox coordinates and class ids (empty labels). After removing all empty labels, I ran the training again and ended up with the same error, )))
> 
> Thanks~~

```python
from ultralytics import RTDETR
model = RTDETR('rt-detr-l.yaml')
model.info()
model.train(data="my_data.yaml", amp=False)
```

**Comment by Laughing-q** [comment]
> > @Laughing-q Thanks for your kind reply. Could you please give me more detail on how to set . Actually, in my scenario, I have only one class. Probable this may also be causing some issues. However, I have checked my all labels and removed the ones which have no Bbox coordinates and class ids (empty labels). After removing all empty labels, I ran the training again and ended up with the same error, )))`amp=False`
> > Thanks~~
> 
> Thank you very much. I have also encountered some issues at the moment. Firstly, Ultratics' RTDETR is used to train my own data. What kind of annotation is needed? Is it in Coco's JSON or Yolov8's txt format.
> 
> Secondly, I am not currently using the PaddlePaddle version. May I ask how difficult it is to training RTDETR compared to YOLOv8.

we also use YOLOv8's txt file as data format for rt-detr models.
Also I think it's also easy for you to train rt-detr with paddlepaddle as long as you follow their training guide. :)

But actually from my experiments, the official paddledetection repo also has this issue with mix-precision training(amp=True), one difference between ours and the official one is that they set `amp=False` by default and we use `amp=True` by default to save more cuda memory while training.
Just like I mentioned above, I also suggest you to try:
- training with pretrained rt-detr weights
- set `amp=False`

**Comment by Adeelbek** [comment]
@Laughing-q, I have used RT-DETR with ResNet-18 backbone, and training went smoothly with my custom dataset. But these all are in the PaddlePaddle platform which may cause me a bit of inconvenience since I mostly use the PyTorch platform. 
I have already adopted RT-DETR ResNet-18 with the ```ultralytics``` environment and tested it with my custom dataset. 
Unfortunately, I see the same error again :-(

Thansk~~~

**Comment by kiddliao** [comment]
> @Laughing-q, I have used RT-DETR with ResNet-18 backbone, and training went smoothly with my custom dataset. But these all are in the PaddlePaddle platform which may cause me a bit of inconvenience since I mostly use the PyTorch platform. I have already adopted RT-DETR ResNet-18 with the `ultralytics` environment and tested it with my custom dataset. Unfortunately, I see the same error again :-(. Making `amp=False` did not help much. It still encounters the same issue.
> 
> Now, I will try to use my pre-trained weights as you kindly suggested. Hope this may help to finish my training without any troubles.
> 
> Thanks~~~

hello , I have the same problem. I also tried to reduce the Learning rate and use pre-training model, but I still often reported errors. However, I finally solved this problem after a few days of research. I found that errors were generated by inferring during training, while using the checkpoint model to directly infer will not report errors, so I found the code in ultralytics-main\ultralytics\yolo\engine\validator.py with different inferring twice, Just comment out these few lines of code. These lines of code are used to calculate the validation set loss during validation inference, and not calculating this loss will not have any impact.
# with dt[2]:
            #     if self.training:
            #         self.loss += model.loss(batch, preds)[1]

**Comment by glenn-jocher** [comment]
@kiddliao,

Thank you for providing an update on your progress. I understand that you have successfully trained the RT-DETR model with your custom dataset using the PaddlePaddle platform, but encountered the same error when using the Ultralytics YOLOv8 repository with the PyTorch platform.

You mentioned that setting `amp=False` did not resolve the issue either. It's unfortunate that you are facing this challenge. In this case, trying to use your pre-trained weights as a starting point is a good idea. This can potentially help avoid any initialization issues and allow the training to proceed smoothly.

Please give it a try and let us know the outcome. We are here to assist you further if needed.

Best regards,
Glenn Jocher

**Comment by vchaparro** [comment]
In my case, setting amp=False does work. Also it is a single class detection problem.
Thanks!

**Comment by LoJunKai** [comment]
Hi, I am experiencing the same issue too and have tried using pretrained weights and `amp=False`. I can confirm that it is due to `nan` values in the `c[i]` cost matrix. One way to identify `nan` values is using `torch.isnan(c[i]).any()`. Unfortunately, I am not sure what to put as the value with in the `indices` list to replace the output of `linear_sum_assignment(c[i])`. Is there a way to handle this gracefully?

Thanks,
Jun Kai

**Comment by glenn-jocher** [comment]
@LoJunKai hello Jun Kai,

Thanks for reporting the issue and providing the insights on NaN values in the 'c[i]' cost matrix. Unfortunately, this issue can occur due to various reasons, such as floating point precision errors, NaN or infinite values in the dataset, incorrect model configurations, etc. 

As you've suggested, identifying the NaN values would be a good first step. Using such functions as `torch.isnan(c[i]).any()` can be helpful here. Nonetheless, careful and defensive programming is necessary at both the dataset and model training level to prevent these values from appearing in the first place.

Regarding replacing the output of `linear_sum_assignment(c[i])`, simply substituting NaN values might not work as expected. The optimization algorithm used by `linear_sum_assignment` is designed for well-defined and finite costs, and NaN values violate these conditions.

Tackling this issue could be done by identifying and treating the root cause in the appropriate way:

- If NaN values are coming from the dataset, cleaning or pre-processing steps should be conducted to get rid of them.
- If they are a consequence of floating point precision errors during computations, using numerical stabilization techniques or reducing the model complexity might be helpful.
- If they are introduced by some model parameters, adjusting these parameters or the model architecture could be beneficial.

Hopefully this gives you some direction on how to proceed. We appreciate your patience and involvement in resolving this issue! 

Best, 
Laughing-q

**Comment by Laughing-q** [comment]
@LoJunKai It is about training strategy. If using pre-trained weight and `amp=False` don't work to you, please try lower learning rate.

**Comment by LoJunKai** [comment]
Hi Glenn and Laughing-q,

Thank you both for your replies! I really appreciate the effort put into this repository and will look in the directions suggested and hopefully find the root cause to it. Thanks!

Best regards,
Jun Kai

**Comment by glenn-jocher** [comment]
@LoJunKai hi Jun Kai,

You're most welcome! We're always here to help and we're glad you found our suggestions helpful. If you need any further assistance while you're looking into the root cause, don't hesitate to reach out. We appreciate your patience and diligence with this issue. Best of luck with your progress!

Best regards,
Laughing-q and Glenn Jocher

**Comment by enzeberg** [comment]
I also had this problem when training `rtdetr-l.pt` and lowering the learning rate (`lr0`) helped me out.
But reducing the learning rate (`lr0`) seems to be useless for training `rtdetr-x.pt`, I still encounter `ValueError: matrix contains invalid numeric entries` when training `rtdetr-x.pt` now.

**Comment by glenn-jocher** [comment]
@laborer123 hello,

The `torch.cuda.OutOfMemoryError: CUDA out of memory` error occurs when the GPU does not have enough memory to accommodate the tensors that are being loaded onto it. This is a different issue from the `ValueError: matrix contains invalid numeric entries` you were experiencing before. 

Here are a few suggestions that might help you resolve this:

1. Reduce the `batch size`: This directly correlates with the GPU memory. A smaller batch size will require less memory.
2. Use gradient accumulation: It enables you to train with a larger effective batch size than you could fit on the GPU.
3. Ensure no other processes are occupying the GPU. You can check this using `nvidia-smi` command for NVIDIA GPUs.
4. Try gradient checkpointing: This can greatly reduce the GPU memory requirement, although it may slow down the training process.

Remember, it's about finding the right balance between speed and memory usage. I hope this helps!

Best regards,
Your_Name

**Comment by glenn-jocher** [comment]
@laborer123 hi there,

It seems like you're experiencing an issue with NaN results from the RTDETRDecoder. This can be a tricky problem often caused by issues with numerical stability in the computations.

You've done the right thing by trying to set amp=False, using pre-trained weights and lowering your learning rate. However, if you're still getting NaNs, there might be more going on. Keep in mind that even a small number of NaN or infinite values can ruin your entire training process.

Given your observation that MultiheadAttention of AIFI is causing NaN, the model might be having difficulties learning the parameters. This could happen when the model weights explode, often due to a large learning rate or due to gradient vanishing/exploding problems. 

Although you've already lowered the learning rate, you might want to try and lower it even more. You could also consider adding gradient clipping to avoid extreme gradient values.

In addition, please ensure your dataset does not contain any NaN or infinite values, as they can cause NaNs during training. Moreover, batch normalization (if you're using it) may at times result in NaNs, so keep an eye on that too.

Unfortunately, these would be general suggestions as without a detailed look into the code and data, it's hard to identify what's exactly causing the NaNs. It would come down to systematic debugging - checking the outputs at each step and narrowing down where exactly the NaNs are being introduced. 

Hope this gives you some direction on how to proceed further with your debugging, and feel free to reach out if you have further queries.

Good luck!

**Comment by zh-song** [comment]
I also saw the error **ValueError: matrix contains invalid numeric entries** when I trained rt-detr-x. Everything was fine for the first 10 epochs, and training was normal for the 11th epochs, but the above error occurred in the 11th epoch val.

**Comment by glenn-jocher** [comment]
@zh-song hi there,

Thank you for sharing your experience with us. The error you're facing appears to be due to the model producing NaN or infinite numeric values at some point during validation.

This is often due to an instability in the learning process of a deep network. Here are some general directions that you can follow to mitigate this issue:

1. Check If there are any NaN values in your dataset: Sometimes, our dataset can contain NaN values which will cause this issue. Please make sure your dataset does not include any.

2. Adjust the learning rate: Using a lower learning rate might stabilize the training. In general, lower learning rates make the training more stable, so you can start with a lower value and then slowly increase it.

3. Gradient Clipping: You may want to apply gradient clipping. This is a measure that modifies the gradients if their norm exceeds a certain threshold, preventing potential instability in the optimization process.

4. Monitor model parameters: If the issue persists it's usually a good idea to closely monitor the evolution of the different layers' weights, the gradients, and the final loss function. Sometimes a specific layer could be the source of instability.

I understand how frustrating such a problem could be, but don't worry. We're here to help you out!

Best,
[Your_Name]

**Comment by cnavarrete** [comment]
Had the same problem. Swapping the optimizer for SGD solved my problem, but it's a shame I cannot train the detector as it was intended.

**Comment by geoexploring** [comment]
@glenn-jocher , Maybe you should be more careful when copying and pasting GPT's responses. Thanks.

**Comment by xiaohangguo** [comment]
i meet the same problem. Resizing the `lr` and change the `amp=False` has no solved ,And i used  the optimizer for SGD solved my problem.

**Comment by andresinsitu** [comment]
I keep getting the same error even when using `amp=False`, `optimizer = 'SGD'` and `lr0=0.0001`

Also the error always happen after the first epoch is completed(as we can see in the image below)

![image](https://github.com/ultralytics/ultralytics/assets/136701299/17d593cd-80ce-4a91-ab26-42c866cb85f9)

**Comment by glenn-jocher** [comment]
@andresinsitu hello,

It seems like you're facing an Out of Memory (OOM) issue. This error occurs when the GPU does not have sufficient memory to accommodate the tensors that are being loaded.

Your successful attempt by reducing image sizes and using a small part of the dataset further points in this direction. Here's why: smaller images require less memory, and a smaller dataset means fewer images are loaded onto the GPU at a given time. Both of these changes reduce the GPU memory requirement, thus avoiding an OOM error.

You have already tried reducing the learning rate and using SGD Optimizer, which typically does help with avoiding such issues, so the cause appears to be primarily the size of your dataset and the image sizes.

You could continue with the smaller image sizes and gradually increase the size to see at what point the GPU runs out of memory again, or try training on a GPU with more memory if available. Or, you can try reducing your batch size, which will decrease the number of images propagated through the network simultaneously and reduce memory requirements.

Remember that efficient memory management is about finding a balance that works best for your specific use case. I hope these suggestions can help you explore possible ways to resolve this issue.

Best regards,
[Your_Name]

**Comment by andresinsitu** [comment]
@glenn-jocher doesnt look like so, i get the same error as everyone in this thread, `matrix contains invalid numeric entries`, also it is independent of batch size and changing the size of the dataset shouldnt impact with the same batch size.

**Comment by glenn-jocher** [comment]
@andresinsitu hi,

Thank you for sharing your experience and providing additional details. The error you're encountering, "matrix contains invalid numeric entries," often suggests that a computation somewhere in the training algorithm is producing NaN or infinite values.

It might appear that changing the dataset size shouldn't impact the training with the same batch size, but sometimes, certain data points (or their combinations inside a batch) could influence the computations in a way that triggers such errors. 

Although you have tried changing the learning rate and used different optimizer without success, those are often the first line of defense against this issue. That said, it's not universally effective and some trainings might still run into numerical instability.

We appreciate your input that there may be an issue with the model's training algorithm itself. It can be a complex task to identify the part of the code causing this error as it requires tracking the forward and backward pass in detail.

Please rest assured that we take such reports seriously. We'll further investigate to identify any potential numeric instability in the YOLOv8's training process. We aim to continually improve the algorithm to provide a robust and user-friendly experience.

Your patience and understanding is greatly appreciated. If you find out more relevant details, feel free to share.

Best,
[Your_Name]

**Comment by YFENG2** [comment]
I had the same problem.
When I train the yolo series, I can get the workout done. But when training rtdetr it reports an error. After switching to SDG optimizer the training can continue.
One reason I guess myself is that my dataset contains some background (empty labels). Maybe these backgrounds lead to invalid data.

**Comment by jordanesikati** [comment]
**ops.py**
The error generated from 
**Line 107** gt_groups = torch.as_tensor([0, *gt_groups[:-1]]).cumsum_(0)
(ValueError: matrix contains invalid numeric entries)
**The solution that worked for me**
**Line 106** C = C.view(bs, nq, -1).cpu()
**Right below line 106**
 # (NaN |  Inf)  ← 0
 C[C.isnan() | C.isinf()] = 0

**Comment by glenn-jocher** [comment]
@jordanesikati hi there, 

Thank you for sharing this workaround you've found for the ValueError: "matrix contains invalid numeric entries". 

You've identified that the error was coming from line 108 in the util/ops.py file. It seems like you've been able to resolve this by adding a line of code right after line 106 to set any NaN or infinity values in C variable to 0. 

This approach can work in cases where the optimization process generates invalid entries (NaNs and Infinities), which tend to disrupt further computations. Making sure such entries are replaced with valid numerical values can certainly prevent the error you were encountering.

Thanks again for sharing this solution. It might help others who are experiencing the same issue with their training process. We will consider if this workaround or a similar approach would be a suitable fix to apply in the YOLOv8 algorithm.

Best regards!

**Comment by op-newman** [comment]
> **ultralytics/ultralytics/models/utils/ops.py** The error generated from **Line 108** gt_groups = torch.as_tensor([0, *gt_groups[:-1]]).cumsum_(0) (ValueError: matrix contains invalid numeric entries) **The solution that worked for me** **Line 106** C = C.view(bs, nq, -1).cpu() **Right below line 106**: Set invalid values (NaNs and infinities) to 0 **C[C.isnan() | C.isinf()] = 0**

You're a hero, and in testing, we've definitely eliminated that problem, so thank you very much for your contribution.

**Comment by jordanesikati** [comment]
> > **ultralytics/ultralytics/models/utils/ops.py** The error generated from **Line 108** gt_groups = torch.as_tensor([0, *gt_groups[:-1]]).cumsum_(0) (ValueError: matrix contains invalid numeric entries) **The solution that worked for me** **Line 106** C = C.view(bs, nq, -1).cpu() **Right below line 106**: Set invalid values (NaNs and infinities) to 0 **C[C.isnan() | C.isinf()] = 0**
> 
> You're a hero, and in testing, we've eliminated that problem, so thank you very much for your contribution.

@op-newman you are welcome. It is always a pleasure to contribute in my free time. This issue was fixed recently with a pull request.

**Comment by glenn-jocher** [comment]
@jordanesikati, @jordanesikati,

It's great to hear that the solution proposed by @jordanesikati has resolved the issue and that the fix has been incorporated through a recent pull request. Collaborative effort is invaluable, and it's contributions from users like you that help us build a more robust and reliable platform. 

Thanks again for your active participation and support in improving YOLO and the broader Vision AI community. If you encounter any more issues or have further insights, please don't hesitate to share.

Enjoy your improved training experience!

**Comment by collinmccarthy** [comment]
I appreciate the comments here, helping me understand the core issue. I think removing NaNs from the cost matrix is the best solution, other than dropping the batch itself, but that can be more tricky to implement. 

However, unless I'm misunderstanding something, I wouldn't set the cost to 0 if it's NaN, I would set it to a large positive value like `np.finfo(np.float32).max`. Since we're performing a [minimization](https://docs.scipy.org/doc/scipy-1.12.0/reference/generated/scipy.optimize.linear_sum_assignment.html) that would (should) prevent the assignment that produced the NaN in the first place.

**Comment by glenn-jocher** [comment]
@collinmccarthy you're absolutely right, and your suggestion makes perfect sense! 🌟 Setting NaNs to a large positive value indeed aligns better with the goal of the minimization process in the assignment algorithm. Using something like `np.finfo(np.float32).max` to replace NaNs ensures that the problematic assignments are effectively avoided, without impacting the integrity of the batch.

For clarity, the adjustment could look like this:
```python
import numpy as np

# Assuming 'C' is your cost matrix
C[np.isnan(C)] = np.finfo(np.float32).max
```

Thank you for pointing this out and contributing to refining the solution. It's inputs like these that help improve the robustness of the models. Keep the insights coming! 🚀
