### ISSUE TITLE
ValueError: path is on mount 'D:', start on mount 'C:'

### ISSUE THREAD

**Issue by SheeppLi** [ultralytics/ultralytics#3257]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Evolution

### Bug

Thanks for your work! I notice that you have added Hyperparameter Tuning with Ray Tune and when I tried it, there is an error: ValueError: path is on mount 'D:', start on mount 'C:'. I think move the whole file to C: work, but unfortunately my C: nearly run out of memory. And I want to ask if there is any other method to solve the problem.
The error is:
(_tune pid=7440) YOLOv8n-seg summary: 261 layers, 3263811 parameters, 3263795 gradients, 12.1 GFLOPs
(_WandbLoggingActor pid=20576) Traceback (most recent call last):
(_WandbLoggingActor pid=20576)   File "D:\anaconda\envs\crystal_detection_yolo_new\lib\site-packages\wandb\sdk\wandb_init.py", line 1148, in init
(_WandbLoggingActor pid=20576)     wi.setup(kwargs)
(_WandbLoggingActor pid=20576)   File "D:\anaconda\envs\crystal_detection_yolo_new\lib\site-packages\wandb\sdk\wandb_init.py", line 172, in setup
(_WandbLoggingActor pid=20576)     self._wl = wandb_setup.setup(settings=setup_settings)
(_WandbLoggingActor pid=20576)   File "D:\anaconda\envs\crystal_detection_yolo_new\lib\site-packages\wandb\sdk\wandb_setup.py", line 327, in setup
(_WandbLoggingActor pid=20576)     ret = _setup(settings=settings)
(_WandbLoggingActor pid=20576)   File "D:\anaconda\envs\crystal_detection_yolo_new\lib\site-packages\wandb\sdk\wandb_setup.py", line 320, in _setup
(_WandbLoggingActor pid=20576)     wl = _WandbSetup(settings=settings)
(_WandbLoggingActor pid=20576)   File "D:\anaconda\envs\crystal_detection_yolo_new\lib\site-packages\wandb\sdk\wandb_setup.py", line 303, in __init__
(_WandbLoggingActor pid=20576)     _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
(_WandbLoggingActor pid=20576)   File "D:\anaconda\envs\crystal_detection_yolo_new\lib\site-packages\wandb\sdk\wandb_setup.py", line 108, in __init__
(_WandbLoggingActor pid=20576)     self._settings = self._settings_setup(settings, self._early_logger)
(_WandbLoggingActor pid=20576)   File "D:\anaconda\envs\crystal_detection_yolo_new\lib\site-packages\wandb\sdk\wandb_setup.py", line 138, in _settings_setup
(_WandbLoggingActor pid=20576)     s._infer_run_settings_from_environment(_logger=early_logger)
(_WandbLoggingActor pid=20576)   File "D:\anaconda\envs\crystal_detection_yolo_new\lib\site-packages\wandb\sdk\wandb_settings.py", line 1687, in _infer_run_settings_from_environment
(_WandbLoggingActor pid=20576)     program_relpath = self.program_relpath or _get_program_relpath_from_gitrepo(
(_WandbLoggingActor pid=20576)   File "D:\anaconda\envs\crystal_detection_yolo_new\lib\site-packages\wandb\sdk\wandb_settings.py", line 172, in _get_program_relpath_from_gitrepo
(_WandbLoggingActor pid=20576)     relative_path = os.path.relpath(full_path_to_program, start=root)
(_WandbLoggingActor pid=20576)   File "D:\anaconda\envs\crystal_detection_yolo_new\lib\ntpath.py", line 703, in relpath
(_WandbLoggingActor pid=20576)     raise ValueError("path is on mount %r, start on mount %r" % (
(_WandbLoggingActor pid=20576) ValueError: path is on mount 'D:', start on mount 'C:'
(_tune pid=7440) Transferred 411/417 items from pretrained weights

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@SheeppLi thank you for bringing this issue to our attention. We apologize for the inconvenience you're experiencing with YOLOv8 and Ray Tune.

The error message you encountered, "ValueError: path is on mount 'D:', start on mount 'C:'", indicates a discrepancy between the path you're using on your D: drive and the expected starting mount point on the C: drive. This error can occur when working with different storage devices or mounting points.

One possible solution you mentioned is to move the entire project to your C: drive, but we understand that it may not be feasible if your C: drive is running low on memory.

To overcome this issue, you can try the following alternative methods:

1. **Check Your Environment Variables**: Ensure that the necessary environment variables are correctly set and that they point to the correct paths for your D: and C: drives. This may involve modifying the `PYTHONPATH`, `PATH`, or other relevant variables.

2. **Configure Ray Tune**: Double-check the configuration settings for Ray Tune and make sure it is aware of the correct paths for your project. You can refer to the Ray Tune documentation or seek assistance from the Ray community for more specific guidance on configuring the library.

3. **Work with Virtual Environments**: Consider setting up a virtual environment specifically for your YOLOv8 project and ensure that it is configured to use the correct drives and paths.

If none of these solutions work for you or if you believe this issue is a bug within YOLOv8 or Ray Tune, we encourage you to contribute by submitting a pull request. Your contribution will be highly appreciated and will help improve the overall quality of the project.

Once again, thank you for your feedback and for using YOLOv8. Please let us know if you have any further questions or concerns.

**Comment by SheeppLi** [comment]
@glenn-jocher I tried the third method and it works. Thanks a lot for your help!

**Comment by glenn-jocher** [comment]
Hi @SheeppLi, 

You're welcome! I'm glad to hear that the third method worked for you and solved the issue. Thank you for letting us know and for your kind words.

If you have any further questions or encounter any other issues with YOLOv8, feel free to reach out. We're here to assist you.

Happy coding!

**Comment by SheeppLi** [comment]
@glenn-jocher I have another question: I run the ray tune and get the recommend hyper parameter, but I find that when I train using the updated hyper parameters, it becomes very slow, sometimes it stays at the first epoch for more than 10 mins and won't start training. I wonder why this happens? I only change the hyper parameters, but the speed decrease sharply, even only 10% of the previous speed.
