### ISSUE TITLE
End of epoch error, TypeError: NoneType object is not iterable

### ISSUE THREAD

**Issue by guillermovc** [ultralytics/ultralytics#3260]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

When my first epoch on training loop ends this error message shows up:
`TypeError: NoneType object is not iterable`

![image](https://github.com/ultralytics/ultralytics/assets/43889001/47727044-c37c-4aa3-8479-8548eadf03e5)

I have printed the content of the variable and it looks to have right values except for the epoch end call

### Environment

YOLO Ultralytics 8.0.112
torch 1.13.0
Nvidia driver version: 536.23
CUDA Version: 12.2
GPU: RTX 2060

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@guillermovc hi there! Thank you for reaching out to us with this issue.

The error message you're encountering, `TypeError: NoneType object is not iterable`, usually occurs when you try to iterate over a variable or object that has a value of `None`. 

To better understand and resolve this issue, we would need some additional information. Could you please provide us with the relevant code snippets from your training loop? This will help us identify the specific cause of the error and provide you with a more accurate solution.

In the meantime, you might want to double-check the part of your code where you call the end of each epoch. It's possible that there is a mistake or issue in that particular section that is causing the error. 

We appreciate your willingness to submit a PR to help us address this bug! Once we have more information about the issue, we can guide you on how to proceed with the PR submission if necessary.

We look forward to assisting you further and resolving this issue.

**Comment by adeilsonsilva** [comment]
I'm currently facing the same issue. I wonder if it could be related to the usage of a custom trainer?

```
class CustomTrainer(DetectionTrainer):
  ...
```

Environment
YOLO Ultralytics 8.0.117
torch 2.0.1+cu118
Nvidia driver version: 530.41.03
CUDA Version: 12.1
GPU: RTX 3060

**Comment by adeilsonsilva** [comment]
> I'm currently facing the same issue. I wonder if it could be related to the usage of a custom trainer?
> 
> ```
> class CustomTrainer(DetectionTrainer):
>   ...
> ```
> 
> Environment YOLO Ultralytics 8.0.117 torch 2.0.1+cu118 Nvidia driver version: 530.41.03 CUDA Version: 12.1 GPU: RTX 3060

I think, for me at least, it could be related to #3154, since by passing `augment: False` this error no longer appears.

**Comment by guillermovc** [comment]
> @guillermovc hi there! Thank you for reaching out to us with this issue.
> 
> The error message you're encountering, `TypeError: NoneType object is not iterable`, usually occurs when you try to iterate over a variable or object that has a value of `None`.
> 
> To better understand and resolve this issue, we would need some additional information. Could you please provide us with the relevant code snippets from your training loop? This will help us identify the specific cause of the error and provide you with a more accurate solution.
> 
> In the meantime, you might want to double-check the part of your code where you call the end of each epoch. It's possible that there is a mistake or issue in that particular section that is causing the error.
> 
> We appreciate your willingness to submit a PR to help us address this bug! Once we have more information about the issue, we can guide you on how to proceed with the PR submission if necessary.
> 
> We look forward to assisting you further and resolving this issue.

Hello @glenn-jocher , thank you for your quick response. I should've mentioned that im not using a custom training loop, im using the model.train(...) method insead. I will leave you the code snippet im sing:

``` python
import os
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"
from ultralytics import YOLO

MODEL = "yolov8m.pt"
# MODEL = r"runs\detect\backbone_yolov8x_imgsz416_bs8_100ep_1apr\weights\best.pt"
EPOCHS = 100
PATIENCE = 20
IMGSZ = 640
BATCH_SIZE = 4
EXTRA = "18jun"

model = YOLO(MODEL)

if __name__ == '__main__':
    name = f"{EXTRA}_scratch_imsz{IMGSZ}_bs{BATCH_SIZE}_{EPOCHS}ep"
    model.train(
        data=r"C:\Macrodata\Macrodata_libretas\data\training_18jun.yaml", 
        epochs=EPOCHS, 
        imgsz=IMGSZ, 
        batch=BATCH_SIZE, 
        patience=PATIENCE,
        project="runs",
        name=name, 
        exist_ok=True, 
        augment=True
    )
```
Also forgot to mention that im using python 3.10.11, and beside hardware is one of the different things that is present in another PC i ran the training succesfully (both in conda enviroments). Im going to create a new enviroment with the same python version.

**Comment by guillermovc** [comment]
This is the full traceback:

Traceback (most recent call last):
  File "train1.py", line 17, in <module>
    model.train(
  File "C:\Users\guill\anaconda3\envs\torch_py38\lib\site-packages\ultralytics\yolo\engine\model.py", line 373, in train
    self.trainer.train()
  File "C:\Users\guill\anaconda3\envs\torch_py38\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 192, in train
    self._do_train(world_size)
  File "C:\Users\guill\anaconda3\envs\torch_py38\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 371, in _do_train
    self.metrics, self.fitness = self.validate()
  File "C:\Users\guill\anaconda3\envs\torch_py38\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 477, in validate
    metrics = self.validator(self)
  File "C:\Users\guill\anaconda3\envs\torch_py38\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\guill\anaconda3\envs\torch_py38\lib\site-packages\ultralytics\yolo\engine\validator.py", line 165, in __call__
    self.loss += model.loss(batch, preds)[1]
  File "C:\Users\guill\anaconda3\envs\torch_py38\lib\site-packages\ultralytics\nn\tasks.py", line 215, in loss
    return self.criterion(preds, batch)
  File "C:\Users\guill\anaconda3\envs\torch_py38\lib\site-packages\ultralytics\yolo\utils\loss.py", line 159, in __call__
    pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
TypeError: 'NoneType' object is not iterable

As i mentioned, this happends at the end of the first epoch:
![image](https://github.com/ultralytics/ultralytics/assets/43889001/6d382ecb-63f2-47f2-845e-307146a2b9a4)

**Comment by diramazioni** [comment]
Same problem here on YOLOv8.0.119, running code it was working before. `augment: False` bypass this issue

**Comment by glenn-jocher** [comment]
@guillermovc @diramazioni @adeilsonsilva hi guys, sorry for the issue. I'm not able to reproduce this in my testing. I've tried single GPU and DDP, and everything trains correctly. Can you please help us by providing exact code that we can use to reproduce the problem on our side?

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by diramazioni** [comment]
@glenn-jocher see my comment on #3154

**Comment by simba404** [comment]
> @guillermovc @diramazioni @adeilsonsilva hi guys, sorry for the issue. I'm not able to reproduce this in my testing. I've tried single GPU and DDP, and everything trains correctly. Can you please help us by providing exact code that we can use to reproduce the problem on our side?
> 
> We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.
> 
> ## How to create a Minimal, Reproducible Example
> When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:
> 
> * ✅ **Minimal** – Use as little code as possible to produce the problem
> * ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
> * ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem
> 
> For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:
> 
> * ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
> * ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.
> 
> If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem.
> 
> Thank you! 😃


I believe the issue may be due to missing or incorrect labels in some samples of your dataset. The data augmentation process relies on correct label information, so missing or erroneous labels can result in a type error during iteration. This error doesn't occur when you set augment=False. Additionally, since you are training on your own dataset, some images may be lacking annotations.

**Comment by gittjob** [comment]
So how to solve it in the end

**Comment by glenn-jocher** [comment]
@gittjob i apologize for the inconvenience you are experiencing. To resolve the issue, it is important to ensure that your dataset contains accurate and complete labels for all samples. The data augmentation process relies on correct label information, so missing or erroneous labels can result in a "TypeError" during iteration.

When setting `augment=False`, the data augmentation process is skipped, which is why the error no longer occurs. However, it is recommended to review and correct your label annotations to ensure accurate training.

If you continue to encounter difficulties, please consider providing a minimal and reproducible example of your code so that we can better understand and assist with diagnosing the problem. Thank you for your understanding.

**Comment by jaideep11061982** [comment]
@glenn-jocher i too face the same issue, I try to use Albumentations lighting augmentations for better training.
so I set augment =True
Labelling seem to be correct only,in yolov5 we hadnt faced this issue.

**Comment by glenn-jocher** [comment]
@jaideep11061982 thank you for bringing this issue to our attention. We understand that you are experiencing an error when using Albumentations lighting augmentations and setting `augment=True` in YOLOv8. We apologize for any inconvenience this may have caused.

The error that you are encountering could be related to incorrect or missing labels in your dataset. The data augmentation process heavily relies on accurate label information. If there are any inconsistencies or incomplete annotations in your dataset, it can result in a "TypeError" during iteration.

Setting `augment=False` bypasses the data augmentation process, which is why the error no longer occurs. However, it is essential to review your label annotations and ensure that they are accurate and complete for all samples in your dataset. Correcting any issues with your labels should resolve the problem you are facing.

If you need further assistance or have any additional questions, please don't hesitate to ask. We're here to help!

**Comment by diramazioni** [comment]
@glenn-jocher sorry to point it out again, but as in #3154 the confusion arise because this parameter was present before and now it's not present anymore. 
@Burhan-Q pointed out:
> When running model.train() the argument augment is not needed. To augment the dataset presented to the model, you only need to add hyperparameters overrides or change the values in the yolo/cfg/default.yaml for hyperparameters.
However [I see](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/cfg/default.yaml) `augment: False ` as default parameter there, °and I wonder why this has to be changed in the yaml now and can't changed as hyperparameters overrides like before. If you specify  `augment=True ` it triggers the error

**Comment by jaideep11061982** [comment]
Yolov8 dataloader dsnt takes in augment ,it replaces  it with Boolean
condition mode==train
If you use yolov5 loader as true ,then augment = true causes this issue .

**Comment by glenn-jocher** [comment]
@diramazioni thank you for bringing this up. In YOLOv8, the dataloader does not take the `augment` parameter directly. Instead, it is replaced by a boolean condition `mode == train`. 

If you are using the YOLOv5 loader and set `augment=True`, it can cause the mentioned issue. The reason for this change is to align with the new structure of YOLOv8.

Regarding the `default.yaml` file, the default value for `augment` is `False`. If you want to change this behavior, you need to modify the `default.yaml` file directly rather than using it as a hyperparameter override.

Please note that these changes are specific to YOLOv8 and may differ from previous versions. If you have any further questions or need clarification, feel free to ask. Thank you for your understanding and support.

**Comment by relaxandcodezjmo** [comment]
I've encountered a slimilar problem but at the very begining stage.
`from ultralytics import YOLO` yields:
Traceback (most recent call last):
  File "C:\Users\SynologyDrive\Work\[2023C]Garbage object detection\src\model_train.py", line 1, in <module>
    from ultralytics import YOLO
  File "C:\Users\anaconda3\envs\pt\lib\site-packages\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.hub import start
  File "C:\Users\anaconda3\envs\pt\lib\site-packages\ultralytics\hub\__init__.py", line 5, in <module>
    from ultralytics.data.utils import HUBDatasetStats
  File "C:\Users\anaconda3\envs\pt\lib\site-packages\ultralytics\data\__init__.py", line 3, in <module>
    from .base import BaseDataset
  File "C:\Users\anaconda3\envs\pt\lib\site-packages\ultralytics\data\base.py", line 18, in <module>
    from ultralytics.utils import DEFAULT_CFG, LOCAL_RANK, LOGGER, NUM_THREADS, TQDM_BAR_FORMAT
  File "C:\Users\anaconda3\envs\pt\lib\site-packages\ultralytics\utils\__init__.py", line 840, in <module>
    SETTINGS = SettingsManager()  # initialize settings
  File "C:\Users\anaconda3\envs\pt\lib\site-packages\ultralytics\utils\__init__.py", line 780, in __init__
    self.load()
  File "C:\Users\anaconda3\envs\pt\lib\site-packages\ultralytics\utils\__init__.py", line 794, in load
    self.update(yaml_load(self.file))
  File "C:\Users\anaconda3\envs\pt\lib\site-packages\ultralytics\utils\__init__.py", line 802, in update
    new = dict(*args, **kwargs)
TypeError: 'NoneType' object is not iterable


I was able to import normally yesterday but today suddently it raises this TypeError. Had uninstall and install ultralytics and the entire conda env multiple times with no luck. Can someone help me? Thank you so much!


Environment
YOLO Ultralytics 8.0.145
torch 2.1.0
Nvidia driver version: 536.23
CUDA Version: 12.1
GPU: RTX 4070Ti

**Comment by glenn-jocher** [comment]
@relaxandcodezjmo it seems like you're encountering an error with the `SettingsManager` initializing in Ultralytics. It's encountering an issue where it's trying to update from a 'NoneType' which isn't iterable. 

This could likely be because the settings file it's trying to load doesn't have the expected information or format. The `load()` command reads from the settings file and the `update()` command tries to update the settings with that file. If it's missing, or cannot be read, it might return None, hence leading to this error.

You mentioned that the code was working fine and then suddenly broke. It might be valuable to consider any recent changes that might affect the settings, such as directory changes, filesystem permissions, or updates to Ultralytics.

One possible workaround could be to manually delete the settings file (default location is ~/.ultralytics/settings.yaml), then run the code again. This should force Ultralytics to create a new settings file with the default settings.

Please note that the actual problem might vary depending on the specifics of your system and setup. If the issue persists, try to provide more details about any recent changes or further error messages.

**Comment by relaxandcodezjmo** [comment]
> 



> @relaxandcodezjmo it seems like you're encountering an error with the `SettingsManager` initializing in Ultralytics. It's encountering an issue where it's trying to update from a 'NoneType' which isn't iterable.
> 
> This could likely be because the settings file it's trying to load doesn't have the expected information or format. The `load()` command reads from the settings file and the `update()` command tries to update the settings with that file. If it's missing, or cannot be read, it might return None, hence leading to this error.
> 
> You mentioned that the code was working fine and then suddenly broke. It might be valuable to consider any recent changes that might affect the settings, such as directory changes, filesystem permissions, or updates to Ultralytics.
> 
> One possible workaround could be to manually delete the settings file (default location is ~/.ultralytics/settings.yaml), then run the code again. This should force Ultralytics to create a new settings file with the default settings.
> 
> Please note that the actual problem might vary depending on the specifics of your system and setup. If the issue persists, try to provide more details about any recent changes or further error messages.

Thank you so much, I fixed this following your suggestions. Life saver!

**Comment by glenn-jocher** [comment]
@relaxandcodezjmo i'm really glad to hear that the suggestions helped to resolve your problem! If you face any other issues or have more questions in the future, don't hesitate to ask. We're here to help. Happy coding!
