### ISSUE TITLE
[Train RT-detr] AttributeError: 'DetectionModel' object has no attribute 'stride'

### ISSUE THREAD

**Issue by lxhmark7** [ultralytics/ultralytics#3262]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

File "/home/ai/anaconda3/envs/torch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DetectionModel' object has no attribute 'stride'
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3366531 closing signal SIGTERM

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@lxhmark7 please provide a "Minimal Reproducible Example" then we can reproduce the issue.:) Thanks!

**Comment by 1117wwh** [comment]
File "d:\anaconda\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DetectionModel' object has no attribute 'stride'

**Comment by glenn-jocher** [comment]
@lxhmark7 hi there!

Thank you for reaching out to us regarding the attribute error you encountered. It seems that you are using the YOLOv8 model from the Ultralytics YOLOv8 repository. The error message you provided indicates that the 'DetectionModel' object does not have an attribute named 'stride'.

To investigate this issue further, could you please provide us with a minimal reproducible example, including the necessary code and steps, so that we can better understand the context in which this error is occurring?

Once we have a better understanding of your specific use case, we will be able to assist you more effectively in resolving this issue.

Thank you for your cooperation, and we look forward to helping you.

Kind regards,
Glenn Jocher

**Comment by glenn-jocher** [comment]
@1117wwh @lxhmark7 @Laughing-q great news 😃! Your original issue may now be resolved ✅ in PR #3273 in this commit:
https://github.com/ultralytics/ultralytics/pull/3273/commits/662f9f55e803f0ec88db3f0cb10ac4c2656b988d

<img width="1329" alt="Screenshot 2023-06-19 at 22 19 02" src="https://github.com/ultralytics/ultralytics/assets/26833433/ee13a5a0-7dcc-4365-b66a-3cfc8711ea0c">

This should be available now in `ultralytics 8.0.120`.

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by Laughing-q** [comment]
> File "d:\anaconda\lib\site-packages\torch\nn\modules\module.py", line 1614, in **getattr** raise AttributeError("'{}' object has no attribute '{}'".format( AttributeError: 'DetectionModel' object has no attribute 'stride'

hmmm I mean the code you use instead of the error log, please provide us the code block you use then we can try to reproduce the issue.

**Comment by Kayzwer** [comment]
@lxhmark7 
I guess you done YOLO("/path/to/rtdetr.yaml"), you can fix it by doing RTDETR("/path/to/rtdetr.yaml")

**Comment by Laughing-q** [comment]
@Kayzwer yeah I guess so, there's no place inside RTDETR using something like `self.stride` or `model.stride`.

**Comment by mahilaMoghadami** [comment]
> RTDETR

thank you
I have this error. how can I solve it?
I didnt understand what you mean?

**Comment by glenn-jocher** [comment]
@mahilaMoghadami it seems there might be a confusion with model instantiation. Please make sure you are calling `RTDETR("/path/to/rtdetr.yaml")` when you initialize the model, not `YOLO("/path/to/rtdetr.yaml")`. This should resolve the AttributeError regarding 'stride'. The correct initialization is crucial because each model class has its specific attributes. Happy coding! 🚀

**Comment by mahilaMoghadami** [comment]
but still I dont know where I should change, which file?
I just changes .yaml file path and  othing else.

thank you

**Comment by glenn-jocher** [comment]
@mahilaMoghadami, the change needs to be made in your Python code where you're creating the model instance. Instead of using `YOLO`, you should use the `RTDETR` class to instantiate your model. So review your Python scripts where the model is initialized, and ensure that the correct class is used for creation. 😊👍
