### ISSUE TITLE
Non-deterministic nature of model.val() on VisDrone 2019

### ISSUE THREAD

**Issue by smjk2124** [ultralytics/ultralytics#3290]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I had a question about the Ultralytics API for validation/testing using a trained YOLOv8 model. I am running val/testing on VisDrone 2019 and the [ONCE](https://once-for-auto-driving.github.io/index.html) dataset

This is how I'm doing it:

```
from ultralytics import YOLO
import torch
import torch.nn as nn
import torch.nn.functional as F

def torch_determistic():
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.enabled = True
    torch.manual_seed(0)
    torch.cuda.manual_seed(0)
    torch.cuda.manual_seed_all(0)

torch_determistic()
model = YOLO('best.pt')  
metrics = model.val(data="VisDrone.yaml")
```

Somehow the results are not reproducible on VisDrone2019 val split - I get different precision, recall and mAP if I rerun the same script without any changes. However, this does not happen on the ONCE dataset and the results are reproducible. Do you have any insights on why this could be happening? I appreciate it, thanks!

**Comment by glenn-jocher** [comment]
@smjk2124 if you have a completely reproducible example please let us know. This could be VisDrone if you pass us your pretrained model, but right now we have no VisDrone trained models.

In any case Validation is deterministic and your results should not change from run to run.

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by smjk2124** [comment]
@glenn-jocher Thanks a lot for your response. [Here](https://file.io/tCR8jxpZ5z0B) is the checkpoint, for YOLOv8s on VisDrone. You can file the yaml [here](https://pastebin.com/1KSXMTGZ). You can also find the results using the script (updated above) on three recent validation runs [here](https://pastebin.com/9fW2y7rK). Any help/insights would be appreciated, thanks!
