### ISSUE TITLE
how is yolov8 tflite pose detection model output organized

### ISSUE THREAD

**Issue by Tikitaka02** [ultralytics/ultralytics#3302]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I have converted a yolov8 pose detector model to tflite and implemented into android application. It gives 1 x 470,400 array which I think it comes from 1x56x8400. My guess is the 56 is 17 keypoints x 3 (x,y,probability) + 4 (x,y,w,h) + 1 class probability, and the 8400 is detected cells which I have to filter out the unnecessary data to extract a meaningful result. However, since it comes in an array, I do not know how the data is organized, which is crucial to know to filter the data. Below is a code I extracted the output

```
interpreter = new Interpreter(FileUtil.loadMappedFile(this,"yolov8n-pose_float16.tflite"));

inputWidth = interpreter.getInputTensor(0).shape()[1];
inputHeight = interpreter.getInputTensor(0).shape()[2];
outputShape = interpreter.getOutputTensor(0).shape();

... some code to get a frame from a camera and to change the frame to bitmap

TensorImage inputTensor = processInputImage(bitmap, inputWidth, inputHeight);
TensorBuffer outputTensor = TensorBuffer.createFixedSize(outputShape, DataType.FLOAT32);

interpreter.run(inputTensor.getBuffer(),outputTensor.getBuffer().rewind());
```

I really appreciate any hints.

**Comment by moonbeam5115** [comment]
I've been having the same issue and the documentation around this is very poor. 

Did you find anything that could be useful?

**Comment by glenn-jocher** [comment]
@moonbeam5115 hello,

Thank you for reaching out. I apologize for any difficulties you've encountered or any confusion caused by the documentation.

Concerning your issue, it would be easier to assist if you could provide more context. Could you please provide more information about the specific issue you're experiencing, including any error messages you are seeing and any steps you've already taken? This will help us understand your situation better and provide more targeted help.

Remember, the clarity of the problem definition often dictates the efficiency of the solution process, so additional information is always welcome. Thank you for your continued support of the YOLOv8 project. I look forward to your response.

Best regards,
Glenn Jocher

**Comment by ovshake** [comment]
Hey @glenn-jocher , I am facing a similar issue, so the output I am getting from `yolov8n-pose_int8.tflite` is `Output shape: (1, 56, 8400)`. Now there are 17 keypoints, in the corresponding pytorch model. So, how is this 56 numbers organized, and what are they? I suspect 17x2 (=34) of them are keypoint coordinates, but what are the rest 22 points? Also, are the key point coordinates normalized?

**Comment by glenn-jocher** [comment]
Hello @ovshake,

You're on the right track. The output shape of (1, 56, 8400) indeed corresponds to the 17 keypoints as you've mentioned and they are arranged into 34 values. Those 34 values are the 2D locations (x, y) of the 17 keypoints, which are normalized.

As for the other 22 points, they include information about the bounding box of the detected objects and the confidence score of the detection. Specifically, the 4 additional points are the bounding box information (x, y, width, height), also normalized, and the remaining 18 points relate to the confidence scores.

Please note that the exact layout of these points may vary depending on your exact model configuration and this is often considered during post-processing of the output array to extract relevant data and map the results back to the original image.

I hope this helps clarify the structure of the output! If you're still facing difficulties, don't hesitate to return with further questions. Happy coding!

**Comment by ovshake** [comment]
Hi @glenn-jocher , so I printed the 56 elements of the row with the most confident bbox to understand the ordering. 
```
[    0.98055     0.32275      0.0374    0.068774      0.9857      644.77      182.52    0.011257      641.34      179.25   0.0016473       643.7      179.86    0.013569      620.56       176.4    0.019903      640.23      178.38     0.34054      614.46      184.02     0.83512      635.39      187.46     0.94171
      616.46      218.51     0.59848      632.19      221.65     0.94191      623.52      240.13      0.3296      634.65      244.11     0.73696      609.64      228.42     0.96015      626.48      230.41     0.97794      629.12      224.86     0.76989      640.25      226.13     0.87892      628.97      235.56
     0.59242      640.37      237.37     0.71924]
```
Looks like the first 4 elements are xywh of bbox, then its confidence of the human inside the bbox, then its 17x3 keypoints with (x, y, visibility) format. But on getting the bbox with the largest confidence, I am getting this bbox, which seems not the best one, at all. 
The top - 10 bboxes look like this. 
![test-tflite](https://github.com/ultralytics/ultralytics/assets/22028532/88660b69-b93d-4752-a6ba-3cd15730e749)

I have uploaded by script as well. The input size of the image is 640x640, so the output pixels are expected to be in that resolution. I am unable to understand which part am I missing. Do you have any ideas around this? 

This is the script 
```python 
import cv2
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from ultralytics.utils.ops import scale_coords


def draw_bbox_on_image(image, x, y, w, h):
    # Denormalize the coordinates
    x = int(x * image.shape[1])
    y = int(y * image.shape[0])
    w = int(w * image.shape[1])
    h = int(h * image.shape[0])

    # Draw the bounding box
    cv2.rectangle(image, (x, y), (x+h, y+w), (0, 255, 0), 2)

    return image


def plot_keypoints_on_image(image, keypoints, t):
    # Iterate over the keypoints
    for keypoint in keypoints:
        x, y, visibility = keypoint

        # Check if the visibility is greater than the threshold
        if visibility > t:
            # Denormalize the coordinates
            x = int(x)
            y = int(y)

            # Draw the keypoint
            cv2.circle(image, (x, y), 2, (0, 0, 255), -1)

    return image

# Load TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="/home/ubuntu/projects/ultralytics/yolov8n-pose_saved_model/yolov8n-pose_float32.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Read the image
image_path = "/home/ubuntu/projects/ultralytics/bus.jpg"
image = cv2.imread(image_path)

# Get the input size from the model's input details and resize the image accordingly
input_size = input_details[0]['shape'][1:3]
image = cv2.resize(image, tuple(input_size))
# image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Convert the image to a float32 numpy array and add an extra dimension
input_data = np.expand_dims(image.astype(np.float32), axis=0)

# Set the tensor to point to the input data to be used
interpreter.set_tensor(input_details[0]['index'], input_data)

# Run the model
interpreter.invoke()

# Get the output tensor
output_data = interpreter.get_tensor(output_details[0]['index'])


output_data_transposed = output_data[0].T

# Select the top K bboxes
K = 10  # Change this to your desired number of bboxes
BASE = 0
sorted_indices = np.argsort(output_data_transposed[:, 5])[::-1]
top_K_by_confidence = output_data_transposed[sorted_indices[BASE:BASE+K]]
print("top_K_by_confidence", top_K_by_confidence[0])

# Process each bbox
for bbox in top_K_by_confidence:
    # Select the first 51 elements and reshape it into 17x3
    keypoints = bbox[5:].reshape((17, 3))
    xywh = bbox[:4]
    image = draw_bbox_on_image(image, xywh[0], xywh[1], xywh[2], xywh[3])
    image = plot_keypoints_on_image(image, keypoints, 0.7)

# Save the image
# cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
cv2.imwrite('test-tflite.png', image)
```

**Comment by ovshake** [comment]
I have opened a new issue, since this one is closed. We can continue the conversation there: https://github.com/ultralytics/ultralytics/issues/4771

**Comment by glenn-jocher** [comment]
Hello @ovshake,

Thank you for sharing your script and the detailed image output - it's very helpful! 

Based on your output and generated bbox of the keypoints, it does appear that the bounding box and keypoints are correct, but the placement of the bbox is misaligned with the persons in the image. This could be due to how you're processing the output, particularly how you're handling the bounding box coordinates.

With respect to the order in which the output is organized: starting from the fifth element of the output, each set of three elements represent a keypoint, with the first two representing the x and y coordinates of the keypoint and the third one is the visibility score. The x and y coordinates are in pixels while the visibility score is a float referring to the confidence level. 

What might be causing the misalignment is a coordinate transformation issue. The bounding box coordinates (and the keypoint coordinates) are in normalized form, relative to the image size. Taking the output directly as pixel positions on the image without transforming them back to the original image scale could be the issue.

Before rendering the detection results on the image, consider converting the normalized bbox and keypoints back to the original image scale. You might want to make use of the scale_coords() function from Ultralytics to help scale the normalized coordinates back to the original image dimensions.

I hope this would resolve the misalignment issue you're facing, if not, kindly raise a new issue and we'd be glad to assist further. We deeply appreciate your patience and involvement with the YOLOv8 community.

Best,
Glenn Jocher

**Comment by FishWaterUnder** [comment]
Hello @glenn-jocher ! I am having the same problem that was pointed out here but there isn't really any answer to it yet. I am applying Yolov8 pose tflite version on Android studio and I am confused about the output. As the original poster have said the output of the model when run in the android studio have a size of `470,400`. The code below is what I ran to see the output size

```
val outputs = model.process(inputFeature0)
val outputFeature0 = outputs.outputAsTensorBuffer.floatArray
Log.i("Tryout", outputFeature0.size.toString())
```
it will show up in the logcat as this:

`2398-2398  Tryout                  com.example.yolotryagain             I  470400`

How do I get the array version of the `1x56x8400` that is automatically set in the python version?

**Comment by glenn-jocher** [comment]
Hello @FishWaterUnder,

To interpret the `470,400` output, reshape it to `1x56x8400` in your Android code. This matches the Python version's output structure. Use `outputFeature0.reshape(1, 56, 8400)` to organize the data similarly.
