### ISSUE TITLE
How to train yolov8 with multi-gpu?

### ISSUE THREAD

**Issue by marcortiz11** [ultralytics/ultralytics#3308]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello all!
How can I train the Yolov8 in multi-gpu mode? I checked [this](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training/#multi-gpu-dataparallel-mode-not-recommended) webpage and it seems that it's only for the Yolov5.
Thanks for the time!

**Comment by glenn-jocher** [comment]
@marcortiz11 see https://docs.ultralytics.com/modes/train/#arguments, you can use `device=0,1,2,3` for CLI or `device=[0,1,2,3]` for Python.

**Comment by marcortiz11** [comment]
Hi glenn, I want to use the Multi-GPU DistributedDataParallel mode which is the recommended by the documentation. Do you know how I can do that?

**Comment by glenn-jocher** [comment]
@marcortiz11 hello,

To use the Multi-GPU DistributedDataParallel (DDP) mode for training YOLOv8, you can follow these steps:

1. First, make sure you have multiple GPUs available on your machine.

2. In the training script or command line, set the `--device` argument to specify the GPUs you want to use. For example, you can use `--device 0,1,2,3` in the CLI or `device=[0,1,2,3]` in Python to indicate that you want to use GPUs 0, 1, 2, and 3 for training.

3. YOLOv8 will automatically detect that multiple GPUs are specified and use the DDP mode for training. This mode divides the training data across the GPUs and performs parallel training, which can significantly speed up the training process.

Please note that the DDP mode is recommended for distributed training across multiple machines or nodes. If you are training on a single machine with multiple GPUs, you can also use the DataParallel mode (`--device 0,1,2,3 data_parallel=True` in CLI or `device=0,1,2,3, data_parallel=True` in Python) to achieve similar results.

I hope this answers your question. Let me know if you need any further assistance.

Best regards,
Glenn Jocher

**Comment by northeastsquare** [comment]
I use the following in train.py:
`model.train(data='obstacle-pose.yaml', epochs=300, batch=128, device=[0,1,2,3], data_parallel=True)  # train the model`

I got:
`SyntaxError: 'data_parallel' is not a valid YOLO argument. `

**Comment by Ra7y** [comment]
@glenn-jocher Hi, when I train my yolov8 model with multiple GPUs, everything works fine during the training phase, but cuda out of memory occurs during the validation phase. I found that only one GPU is used in the verification phase. At this time, can I modify the batch-size of the verification phase or use multiple GPUs for verification?

**Comment by glenn-jocher** [comment]
@Ra7y hello,

Thank you for bringing up this concern.

When you train YOLOv8 with multiple GPUs, by default the training phase will utilize all available GPUs, but the validation phase will only use one. This is generally sufficient since the validation phase is less resource-intensive than the training phase.

However, if you're experiencing CUDA out of memory errors during validation, there are a couple of strategies you could consider:

1. Reduce Validation Batch Size: You can modify your configuration file to use a smaller batch size during validation. This will reduce the amount of memory required at any one time, helping to prevent out-of-memory errors.
   
2. Use Multiple GPUs for Validation: While it's true that YOLOv8 defaults to using a single GPU during validation, you could modify the code to distribute the validation workload across multiple GPUs. Please note this requires knowledge of PyTorch and its DistributedDataParallel functionality.

I hope these suggestions prove helpful. Please don’t hesitate to reach out if you have additional questions or need further assistance.

Best regards,
Glenn

**Comment by glenn-jocher** [comment]
Hi @LinirZamir,

The `model.train` function with `device=0` as a parameter essentially instructs the program to use only the first GPU (indexed at 0) for training. This works fine on a single-GPU system but may cause errors on a multi-GPU system, particularly if other processes are using this GPU.

On your multi-GPU system, specifying `device=[0,1]` should ideally distribute the workload across the first two GPUs. However, it'd appear that the "system crashes as it starts training" issue you're experiencing might be related to inadequate power supply or overheating when both GPUs are utilized.

For the `RuntimeError: Default process group has not been initialized, please make sure to call init_process_group` error, this typically indicates a problem with the distributed backend setup in PyTorch. It's essential to call `torch.distributed.init_process_group()` to initialize the default distributed process group, which is a prerequisite for multi-GPU training.

Here are some suggestions that may help:

1. Make sure that `torch.distributed.init_process_group()` is called before you start training. This is crucial for setting up the distributed environment.

2. Ensure that your power supply is adequate for running two GPUs simultaneously. If it's not sufficiently powerful, it might cause the system to crash when starting the training.

3. Check whether the GPUs are overheating when you start training. Overheating can similarly lead to unexpected crashes.

I hope these suggestions prove helpful. Please keep us posted on your progress.

Best,
Glenn

**Comment by Gaofan666** [comment]
@glenn-jocher Hi, I want to train YOLOv8 with multiple machines, but the code "# On master machine 0
python -m torch.distributed.run --nproc_per_node G --nnodes N --node_rank 0 --master_addr "192.168.1.1" --master_port 1234 train.py --batch 64 --data coco.yaml --cfg yolov5s.yaml --weights '' is only for YOLOv5. Is there any method for YOLOv8?

**Comment by glenn-jocher** [comment]
@Gaofan666 hi there,

The command you shared is indeed a PyTorch built-in command for distributed training across multiple nodes and it's designed for general usage, not specifically for YOLOv5. For YOLOv8, you would need to adjust the command to fit your specific use case. 

The main aspects you'd need to amend are the data, configuration file, and weights options to suit your YOLOv8 implementation. So for example, instead of `--data coco.yaml --cfg yolov5s.yaml --weights ''`, you'd specify your YOLOv8 data, configuration file, and initial weights.

Just keep in mind, training YOLOv8 with multiple machine requires a proper setup to ensure every machine can communicate with each other (e.g. correct IP addresses, port number). I'd recommend testing on a small dataset first to ensure your multi-node setup is working correctly. 

Best,
Glenn

**Comment by Sara-zb** [comment]
@glenn-jocher How can we specify it to use only GPU 0? I have 2 GPUs, but when I specify device=[0] or device=0, it throws runtime error. it worked fine with device=[0,1] 
this is the error:

raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.
        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:
            if __name__ == '__main__':
                freeze_support()
                ...
        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by glenn-jocher** [comment]
@Sara-zb:

The error message you're getting is related to the way multiprocessing is handled in Python on Windows, which uses the "spawn" method to create new processes. It's crucial when using multiprocessing that the entry point to your program is protected with an `if __name__ == '__main__':` block to ensure that it does not get executed multiple times, which is what seems to be happening here.

If you're exclusively wanting to use GPU 0 and not involve other GPUs, your Python script should look something like this:

```python
import torch

def main():
    # Your training script logic here
    model.train(data='obstacle-pose.yaml', epochs=300, batch=128, device=0)

if __name__ == '__main__':
    torch.multiprocessing.freeze_support()
    main()
```

Ensure your training script has the `if __name__ == '__main__':` block as shown above. This should resolve the RuntimeError that you're encountering.

When you specify `device=0` or `device=[0]`, it should restrict computation to only the first GPU. If that's resulting in a runtime error, please ensure:

1. That no other processes are using the GPU.
2. That the appropriate GPU drivers and CUDA versions are installed.
3. That you're following the multiprocessing guidelines, as shown above.

Let me know if there are any more issues or if you need further clarification.

**Comment by mazepa13** [comment]
> @Ra7y hello,
> 
> Thank you for bringing up this concern.
> 
> When you train YOLOv8 with multiple GPUs, by default the training phase will utilize all available GPUs, but the validation phase will only use one. This is generally sufficient since the validation phase is less resource-intensive than the training phase.
> 
> However, if you're experiencing CUDA out of memory errors during validation, there are a couple of strategies you could consider:

> 2. Use Multiple GPUs for Validation: While it's true that YOLOv8 defaults to using a single GPU during validation, you could modify the code to distribute the validation workload across multiple GPUs. Please note this requires knowledge of PyTorch and its DistributedDataParallel functionality.

@glenn-jocher , hello

How to specify YOLOv8 to use multigpu during the validation phase too?

**Comment by glenn-jocher** [comment]
@mazepa13 hello,

To utilize multiple GPUs during the validation phase in YOLOv8, you would need to modify the validation script to support DistributedDataParallel or DataParallel. This adjustment is a bit complex and requires familiarity with PyTorch's parallel computing API.

However, instead of modifying the core scripts, I would recommend first trying to decrease the validation batch size to avoid out-of-memory issues. Adjust your validation batch size in your YAML configuration file and see if that resolves the memory issue.

If you're intent on using multiple GPUs for validation, this will involve custom coding which is beyond the scope of our support.

**Comment by mazepa13** [comment]
> @mazepa13 hello,
> 
> To utilize multiple GPUs during the validation phase in YOLOv8, you would need to modify the validation script to support DistributedDataParallel or DataParallel. This adjustment is a bit complex and requires familiarity with PyTorch's parallel computing API.
> 
> However, instead of modifying the core scripts, I would recommend first trying to decrease the validation batch size to avoid out-of-memory issues. Adjust your validation batch size in your YAML configuration file and see if that resolves the memory issue.
> 
> If you're intent on using multiple GPUs for validation, this will involve custom coding which is beyond the scope of our support.

Thanks for the answer. Memory overflow problems are clear to avoid, but I expected that the validation mode also works in two or more GPU mode. I would like to get a multiple increase in learning speed when using more GPUs. For example, when using 1 GPU, the training phase takes 20 seconds, the validation phase 10 seconds, resulting in approximately 30 seconds per epoch. When using 4 GPUs, the training phase takes 5 seconds, the validation phase takes 10 seconds, resulting in approximately 15 seconds per epoch. Only 2 times faster, instead of the expected ~4.. ((

**Comment by glenn-jocher** [comment]
@mazepa13,

YOLOv8's validation phase is designed to use a single GPU by default to streamline the development and minimize potential synchronization issues across GPUs. While using more GPUs does speed up the training phase, the validation phase doesn't parallelize in the same manner, which is why your speedup factor is closer to 2 rather than 4.

For advanced users, customizing the script to leverage multiple GPUs for validation is a possibility but would require a careful implementation of distributed validation logic. This is not currently supported out-of-the-box by YOLOv8.

For speed improvements during the validation phase, beyond multi-GPU scaling, ensuring you're using the most efficient GPU configuration and optimizing your dataset and data loader can also yield performance gains.

We appreciate your understanding and continue to work on enhancing the capabilities of the model and training flow.

**Comment by Thunderzen** [comment]
Hi, i tried training with 2 GPUs but experienced this error. How may i resolve this?
This is the code i used:

model=YOLO("yolov8s.pt")
model.train(data=path_to_yaml, device=[0,1], epochs=100, imgsz=1280, batch=4)

This is the error i encountered:
CalledProcessError                        Traceback (most recent call last)
Cell In[3], line 3
      1 model=YOLO("yolov8s.pt")
----> 3 model.train(data=path_to_yaml, device=[0,1], epochs=100, imgsz=1280, batch=4)

CalledProcessError: Command '['C:\\Users\\Owner\\anaconda3\\envs\\newenv\\python.exe', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '50290', 'C:\\Users\\Owner\\AppData\\Roaming\\Ultralytics\\DDP\\_temp_nqqhhgbk2230384504336.py']' returned non-zero exit status 1.

**Comment by Thunderzen** [comment]
@glenn-jocher Hi, I tried using the code you have sent but i still receive the same CalledProcessError. When i tried printing torch.cuda.device_count(), it does give the output "2". How can i resolve this part?

**Comment by glenn-jocher** [comment]
@Thunderzen training YOLOv8 with multiple GPUs is straightforward and similar to training with a single GPU. You can use the same `train` mode and simply specify the GPU device IDs you wish to use. Here's how you can do it using both the Python API and the CLI:

#### Python API

To train a YOLOv8 model on multiple GPUs using the Python API, you can specify the `device` argument as a list of GPU IDs when calling the `train` method. For example, to train on GPUs 0 and 1:

```python
from ultralytics import YOLO

# Load a YOLO model
model = YOLO('yolov8n.pt')  # Load a pretrained model (recommended for training)

# Train the model with 2 GPUs
results = model.train(data='coco128.yaml', epochs=100, imgsz=640, device=[0, 1])
```

#### CLI

To train a YOLOv8 model on multiple GPUs using the command-line interface, you can use the `device` argument followed by the GPU IDs separated by commas. For example, to train on GPUs 0 and 1:

```bash
yolo train model=yolov8n.pt data=coco128.yaml epochs=100 imgsz=640 device=0,1
```

This will distribute the training workload across the specified GPUs, effectively utilizing the available hardware resources to speed up the training process.

Remember to ensure that your environment is set up correctly for multi-GPU training, including having the necessary CUDA and cuDNN libraries installed, and that PyTorch is configured to recognize all available GPUs.

**Comment by lanpigwen** [comment]
hi,I tried using GPUs when the code is "... device=0,1 resume=True",but there is only one cuda:0
![image](https://github.com/ultralytics/ultralytics/assets/124516847/88aab6fd-af51-4f6f-8672-0d4c2d2401db)

however,when I set "resume=False" ,cuda:0 cuda:1 are both available
![image](https://github.com/ultralytics/ultralytics/assets/124516847/6915de55-cd47-41e4-88fb-f46bc7d81e8b)

**Comment by glenn-jocher** [comment]
Hi @lanpigwen!

The validation batch size can be set in your dataset YAML file (the one you're referencing in the `data` argument of your training command). In your case, it's the `data.yaml` file. You'll find a section in that file for the validation dataset, and you can add or modify the `batch-size` parameter there. Here's an example snippet from a typical `data.yaml`:

```yaml
# Train/val/test sets as 1) directory: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
train: path/to/train/images
val: path/to/val/images

# number of classes
nc: 80

# class names
names: ['class1', 'class2', ..., 'classN']

# batch size
batch-size: 16  # <-- Add or modify this line for validation batch size
```

Just add or update the `batch-size` under the validation section as needed. Hope this helps, and happy training! 😊🚀

**Comment by ckn3** [comment]
I keep getting this error if I set two GPUs in device like this: "results = model.train(data='/home/ckn3/Downloads/palm/datasets/data.yaml', epochs=500, imgsz=800, device=[0,2])", how can I avoid this?

DDP: debug command /home/ckn3/anaconda3/envs/yolo/bin/python -m torch.distributed.run --nproc_per_node 2 --master_port 45707 /home/ckn3/.config/Ultralytics/DDP/_temp_4vgl259s140447774643792.py
Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library.
        Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it.
Traceback (most recent call last):
  File "/home/ckn3/Downloads/palm/main.py", line 14, in <module>
    results = model.train(data='/home/ckn3/Downloads/palm/datasets/data.yaml', epochs=500, imgsz=800, device=[0,2])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ckn3/anaconda3/envs/yolo/lib/python3.11/site-packages/ultralytics/engine/model.py", line 668, in train
    self.trainer.train()
  File "/home/ckn3/anaconda3/envs/yolo/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 193, in train
    raise e
  File "/home/ckn3/anaconda3/envs/yolo/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 191, in train
    subprocess.run(cmd, check=True)
  File "/home/ckn3/anaconda3/envs/yolo/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/ckn3/anaconda3/envs/yolo/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '45707', '/home/ckn3/.config/Ultralytics/DDP/_temp_4vgl259s140447774643792.py']' returned non-zero exit status 1.

**Comment by RVZZVK** [comment]
@glenn-jocher when using cuda and testing it out it shows device number as well as the torch.cuda.is_available():true
however when we implement this code into the training model is shows that
torch.cuda.is_available():False
torch.cuda.device_count: 0
os.environ['cuda_visible_devices']: None

**Comment by glenn-jocher** [comment]
Hi @RVZZVK,

Thank you for reaching out and providing details about your issue. It sounds like you're encountering an environment configuration problem where CUDA devices are not being recognized during training.

To help us investigate further, could you please provide a minimum reproducible code example? This will allow us to replicate the issue on our end. You can find guidelines for creating a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example). Ensuring we can reproduce the bug is crucial for us to identify and resolve the problem effectively.

Additionally, please verify that you are using the latest versions of both `torch` and `ultralytics`. You can update your packages using the following commands:

```bash
pip install --upgrade torch
pip install --upgrade ultralytics
```

Once you've ensured your packages are up to date, try running your training script again. If the issue persists, here are a few things to check:

1. **Environment Variables**: Ensure that the `CUDA_VISIBLE_DEVICES` environment variable is set correctly. You can set it in your script before initializing the model:

    ```python
    import os
    os.environ['CUDA_VISIBLE_DEVICES'] = '0,1'  # Adjust based on your available GPUs
    ```

2. **CUDA and cuDNN Installation**: Verify that CUDA and cuDNN are installed correctly and match the version requirements of your PyTorch installation. You can check this by running:

    ```python
    import torch
    print(torch.version.cuda)
    print(torch.backends.cudnn.version())
    ```

3. **Device Specification in Training**: Ensure that you specify the correct devices in your training command. For example:

    ```python
    from ultralytics import YOLO

    model = YOLO('yolov8n.pt')
    results = model.train(data='data.yaml', epochs=100, imgsz=640, device=[0, 1], batch=4)
    ```

If you've checked all the above and the issue still occurs, please share the exact error messages and any additional context that might help us diagnose the problem.

Looking forward to your response and happy to assist further! 😊

**Comment by mohammadhakim73** [comment]
hey,
Is it problematic to use different graphics cards such as the RTX 4070 Super Ti and RTX 3060 together?
Could the RTX 3060 be causing a bottleneck and slowing down the training speed?

**Comment by glenn-jocher** [comment]
Using different graphics cards like the RTX 4070 Super Ti and RTX 3060 together can lead to bottlenecks, as the slower card (RTX 3060) may limit the overall training speed. It's generally recommended to use identical GPUs for optimal performance.

**Comment by RamEppala** [comment]
Question:

when we use pass argument in CLI & python device =0,1,2,3 to utilise multi-gpu model trainings in  jupyter NB we noticed only 5.49GB under GPU_mem column.

Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100      5.49G      1.733       3.98      1.725          1       1280:
      
AWS g5.12xlarge multi gpu is being used for model trainings
![AWS g5_12xlarge](https://github.com/user-attachments/assets/0875ad08-6267-4b68-b93e-1608aefac81d)

I see that all 4 devices have been utilised 
Ultralytics YOLOv8.1.9 🚀 Python-3.10.12 torch-2.3.1+cu121 CUDA:0 (NVIDIA A10G, 22625MiB)
                                                           CUDA:1 (NVIDIA A10G, 22625MiB)
                                                           CUDA:2 (NVIDIA A10G, 22625MiB)
                                                           CUDA:3 (NVIDIA A10G, 22625MiB)
          Noticed that only device =0 is being used unsure why device =1,2,3 is idle when running CLI/ training script 
          
          Can you please assist. Looking forward to your response

**Comment by glenn-jocher** [comment]
The issue you're observing, where only partial GPU memory is utilized despite engaging multiple devices, may be due to the batch size not being large enough to fully utilize all GPUs. Distributed training divides the batch across available GPUs, so a smaller batch size could result in underutilized GPUs.

To address this, try increasing the `batch` parameter in your training command to better utilize GPU resources. For example, if using 4 GPUs, the total batch size should ideally be divisible by 4. Additionally, ensure your setup adheres to proper [DistributedDataParallel (DDP)](https://pytorch.org/docs/stable/distributed.html) training practices, as DDP is the recommended way to train on multiple GPUs efficiently. You can also monitor GPU usage using `nvidia-smi` while training to confirm utilization across all GPUs.

**Comment by RamEppala** [comment]
> The issue you're observing, where only partial GPU memory is utilized despite engaging multiple devices, may be due to the batch size not being large enough to fully utilize all GPUs. Distributed training divides the batch across available GPUs, so a smaller batch size could result in underutilized GPUs.
> 
> To address this, try increasing the `batch` parameter in your training command to better utilize GPU resources. For example, if using 4 GPUs, the total batch size should ideally be divisible by 4. Additionally, ensure your setup adheres to proper [DistributedDataParallel (DDP)](https://pytorch.org/docs/stable/distributed.html) training practices, as DDP is the recommended way to train on multiple GPUs efficiently. You can also monitor GPU usage using `nvidia-smi` while training to confirm utilization across all GPUs.

-----------------------------------------

@glenn-jocher -- Greetings!

although used batch size = 64 device = 0,1,2,3  CUDA out of memory message pops up
All 4 GPU's not allocating.  Below is the message received 

""" torch.cuda.OutOfMemoryError: CUDA out of memory. 
Tried to allocate 50.00 MiB.
 GPU  has a total capacity of 22.09 GiB of which 34.44 MiB is free. 
Including non-PyTorch memory, this process has 22.05 GiB memory in use. Of the allocated memory 21.52 GiB is allocated by PyTorch, and 78.60 MiB is reserved by PyTorch but unallocated. 
If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  
See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)"""


Thanks!
Looking forward to your response

**Comment by glenn-jocher** [comment]
@RamEppala the CUDA out-of-memory error indicates that your current batch size is too large for your GPU memory. Try reducing the batch size (e.g., from 64 to 32 or 16) to fit within the memory limits of your GPUs. Additionally, ensure that your setup is using DistributedDataParallel (DDP) as recommended, and consider setting `PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True` to help with memory fragmentation. Refer to PyTorch's [Memory Management Guide](https://pytorch.org/docs/stable/notes/cuda.html#environment-variables) for further details.

**Comment by glenn-jocher** [comment]
@Sibgat-Ul When training with multiple GPUs using YOLO11, ensure your batch size is divisible by the number of GPUs. For example, with 2 GPUs, try using batch=16 or batch=32. Also, verify that PyTorch distributed training is properly initialized by checking if you see multiple CUDA devices in the initial training log output.

You can try setting an environment variable before training to help with distributed process initialization:

```python
import os
os.environ["MASTER_ADDR"] = "localhost"
os.environ["MASTER_PORT"] = "29500"

from ultralytics import YOLO
model = YOLO("yolo11x.pt")
results = model.train(data="data.yaml", epochs=100, imgsz=640, device=[0,1], batch=16)
```

If the issue persists, try using the command line interface which sometimes handles multi-GPU training more reliably:

```bash
yolo detect train model=yolo11x.pt data=data.yaml epochs=100 imgsz=640 device=0,1 batch=16
```

**Comment by Sibgat-Ul** [comment]
> [@Sibgat-Ul](https://github.com/Sibgat-Ul) When training with multiple GPUs using YOLO11, ensure your batch size is divisible by the number of GPUs. For example, with 2 GPUs, try using batch=16 or batch=32. Also, verify that PyTorch distributed training is properly initialized by checking if you see multiple CUDA devices in the initial training log output.
> 
> You can try setting an environment variable before training to help with distributed process initialization:
> 
> import os
> os.environ["MASTER_ADDR"] = "localhost"
> os.environ["MASTER_PORT"] = "29500"
> 
> from ultralytics import YOLO
> model = YOLO("yolo11x.pt")
> results = model.train(data="data.yaml", epochs=100, imgsz=640, device=[0,1], batch=16)
> If the issue persists, try using the command line interface which sometimes handles multi-GPU training more reliably:
> 
> yolo detect train model=yolo11x.pt data=data.yaml epochs=100 imgsz=640 device=0,1 batch=16

i have tried that but still it wont just train my multi-gpu instance,
running both the cli and the python version logs the same output:

```bash
Ultralytics 8.3.127 🚀 Python-3.11.11 torch-2.5.1+cu124 CUDA:0 (Tesla T4, 15095MiB)
                                                        CUDA:1 (Tesla T4, 15095MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=data.yaml, degrees=0.0, deterministic=True, device=cuda:0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=100, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11x.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train7, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train7, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
```
While analyzing, i find that the trainer only has 'device=cuda:0' set, even though device=[0,1] was specified. any help?
Thanks

**Comment by erfanchy93** [comment]
![Image](https://github.com/user-attachments/assets/b398717e-aa62-4b7d-a958-086deaf33a06)

**Comment by glenn-jocher** [comment]
Thank you @erfanchy93 for sharing this helpful workaround! It's great that you found a solution by downgrading to ultralytics==8.3.82.

This suggests there might be a regression in multi-GPU support in more recent versions. I've noted this issue and will ensure our team investigates it. For others experiencing the same problem, you can try this downgrade solution while we work on a fix for the current release.

For anyone else facing multi-GPU training challenges, please make sure:
1. Your batch size is divisible by the number of GPUs
2. You're using DDP (Distributed Data Parallel) rather than DP (Data Parallel)
3. You've set appropriate environment variables for distributed training

We'll update this thread once we have a permanent solution in place. Thanks for your patience and for helping improve Ultralytics!

**Comment by Sibgat-Ul** [comment]
> found a work around - downgraded to ultralytics==8.3.82 This is using all GPUs!

Thanks that worked for me too!

**Comment by glenn-jocher** [comment]
We've confirmed there's a regression in multi-GPU support in recent versions of the Ultralytics package. Our team is actively working on a fix for the current release. In the meantime, please continue using version 8.3.82 if you need multi-GPU training capabilities.

For those wanting to try current versions with multiple GPUs, you can investigate using the `select_device` function from the reference material:

```python
from ultralytics.utils.torch_utils import select_device

# Before your model training
device = select_device("0,1")  # Explicitly select GPUs 0 and 1

# Then use this device in your training
model = YOLO("yolo11n.pt")
results = model.train(data="data.yaml", epochs=100, imgsz=640, device=device)
```

We'll update this thread once the fix is implemented in the main branch. Thank you for your patience and for reporting this issue.

**Comment by Spigd** [comment]
> 请参阅 https://docs.ultralytics.com/modes/train/#arguments，可用于 CLI 或 Python。`device=0,1,2,3``device=[0,1,2,3]`

Hi @LinirZamir,I found that no matter what I do, I'm still running on a single card and can't set up multiple cards. How should I deal with this?
`model.train(
  data=mypath,
  imgsz=640,
  epochs=100,
  batch=16,
  device=[1,2],
  optimizer="SGD",
  augment=True,
  name="res"
)`

![Image](https://github.com/user-attachments/assets/90bd5d49-6646-40a3-a396-0abae6257728)
