### ISSUE TITLE
Problems running on Colab

### ISSUE THREAD

**Issue by rokas-j** [ultralytics/ultralytics#332]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Hi, I tried training the YOLOv8 on a custom dataset from roboflow, however when the training starts, I start getting this error message:
`      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/10        14G      3.252      3.526      1.498        856        512:   6% 1/17 [00:08<02:17,  8.62s/it]Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 250, in plot_images
    annotator.box_label(box, label, color=color)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/plotting.py", line 63, in box_label
    _, _, w, h = self.font.getbbox(label)  # text width, height
AttributeError: 'FreeTypeFont' object has no attribute 'getbbox'
       1/10        14G      3.252      3.526      1.498        856        512:   6% 1/17 [00:09<02:27,  9.25s/it]
`
Also, setting the batch-size to "-1" causes there to be a "CUDA out of memory" error, so maybe AutoBatch isn't calculating the batch size correctly yet? (or this may be related to the previous error, i'm not sure)

### Environment

- YOLO: Ultralytics YOLOv8.0.5 🚀 Python-3.8.16 torch-1.13.0+cu116 CUDA:0 (Tesla T4, 15110MiB)
- Colab environment
- Tesla T4

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@rokas-j hi there! It looks like you are encountering an error during training on a custom dataset from roboflow. The error message you provided indicates an issue related to image plotting. It seems like there might be a problem related to the text annotation during the training process.

Regarding the "CUDA out of memory" error when setting the batch size to "-1," this could indeed be related to the previous error or a separate issue. It's possible that AutoBatch is not calculating the batch size correctly in this scenario.

One potential workaround for the "CUDA out of memory" error could be to manually set the batch size to a lower value that fits within the available GPU memory.

As for the original issue with the AttributeError during plotting, it may require further investigation to identify the root cause and provide a fix.

I would recommend checking the format and content of your custom dataset from roboflow to ensure it aligns with the expected input format for YOLOv8.

If you'd like to contribute a fix, your help would be greatly appreciated by the YOLOv8 community! If you have any further details or updates on this issue, please feel free to share them here so we can better assist you.
