### ISSUE TITLE
My custom pose dataset learning is not working well.

### ISSUE THREAD

**Issue by blackCmd** [ultralytics/ultralytics#3320]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to train keypoints for cars, not people.

I created a dataset using the CVAT labeling tool and JsonToYolo.
This is the car keypoints dataset I used for training and testing. [[cars.zip](https://github.com/ultralytics/ultralytics/files/11830273/cars.zip)]
　
　
I've tried numerous trainings, but they all failed.
The following is the best result I've had so far from my training attempts.
> ![image](https://github.com/ultralytics/ultralytics/assets/13531174/5b4bc38d-960d-4ff0-9dc5-fa11c2dcc7d4)
>
>![image](https://github.com/ultralytics/ultralytics/assets/13531174/8204ed11-76af-4640-97f7-7d842901f1c0)
>
>![image](https://github.com/ultralytics/ultralytics/assets/13531174/e25c66be-8c63-47ca-a636-4ba768d4fc52)
>
>val_batch0_labels.jpg▼
>![val_batch0_labels](https://github.com/ultralytics/ultralytics/assets/13531174/5355e9b8-5053-4d5b-93dc-6a0e5f360f51)
>val_batch0_pred.jpg▼
>![val_batch0_pred](https://github.com/ultralytics/ultralytics/assets/13531174/242b9cf5-8da9-4aeb-9453-5bdf0c6be1b9)

**Is it possible to train a custom dataset using yolov8-pose?**
Has anyone ever succeeded in doing this? I'm asking anyone for an answer.
I've been so tired for a long time. If there's anyone who has succeeded in training with a custom dataset like me, I think I could regain my strength. Please help me. 

Thank you.

### Additional
My dataset Num. : 37
Env. : Ubuntu20.04 + cuda11.6 + pytorch2.0.0

_No response_

**Comment by michelebechini** [comment]
Hi @blackCmd, I succeeded in training YOLOv8-pose in a custom dataset. From the images it seems that you are trying to detect the keypoints located in the middle of the wheels, but what about the bounding box? 
I think that it may help your training process if you label the bounding box as the minimum box that totally encloses the car. Then concerning the keypoint detector you need to remember that basically it works as a "corner detector" or, better, as an extractor of interesting keypoint, hence it may be difficult to recover the center of the wheels, especially for those that are not visible. 

Moreover from my (limited) experience I must say that labeling keypoints with a high degree of symmetry results in a very difficult training. Hence, I can suggest you to include more keypoints in your labels to disambiguate the images, e.g. lateral rear-view mirrors, plate, etc. and then retrieve in post processing only the ones that are most useful for your purpose. This should ease the training phase.

**Comment by glenn-jocher** [comment]
Hi @michelebechini, it's great to hear that you are working on training YOLOv8-pose with a custom dataset. From the images you provided, it seems like you are trying to detect the keypoints located in the middle of the wheels. 

In order to improve your training process, I would recommend labeling the bounding box as the minimum box that completely encloses the car. This will help the model focus on the entire car rather than specific keypoints. 

Regarding the keypoint detection, it's important to note that YOLOv8-pose essentially works as a "corner detector" or an extractor of interesting keypoints. Therefore, it might be challenging to accurately detect the center of the wheels, especially when they are not clearly visible.

Based on my limited experience, labeling keypoints with a high degree of symmetry can make training more difficult. To address this, I suggest adding more keypoints to your labels that are unique to each car, such as lateral rear-view mirrors, the license plate, etc. Then, during post-processing, you can filter out the keypoints that are most relevant for your specific purpose.

I hope these suggestions help improve your training phase. Keep up the good work, and please feel free to reach out if you have any further questions or concerns.

**Comment by michelebechini** [comment]
Hi @glenn-jocher, I simply answered to the question of @blackCmd just because I had more or less the same issues in the past

**Comment by blackCmd** [comment]
I extend my infinite gratitude to @glenn-jocher for providing the precise answer, and to @michelebechini for conveying that accurate answer.
Your kindness has saved me.
I am incredibly grateful and happy because of you two angels. 😇😇😇

**Comment by glenn-jocher** [comment]
@blackCmd you're very welcome! We're glad that we could help you and that you found our advice useful. If you have any further questions or concerns, please don't hesitate to reach out to us. Our team is always happy to assist you in your YOLOv8-pose training journey. Thank you for choosing Ultralytics YOLOv8! ☺️
