### ISSUE TITLE
Yolov8 citation 

### ISSUE THREAD

**Issue by FatmaMazen2021** [ultralytics/ultralytics#333]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Could you kindly tell me how to cite YOLOv8 in a scientific research paper?

**Comment by UnglvKitDe** [comment]
+1

**Comment by AyushExel** [comment]
<img width="1432" alt="Screenshot 2023-01-29 at 11 34 46 PM" src="https://user-images.githubusercontent.com/15766192/215346364-2c340321-2886-46af-aa41-568480c40a53.png">
You can see citation information on the repo here

**Comment by UnglvKitDe** [comment]
Srry not seen. Thx!

**Comment by AyushExel** [comment]
Yes, we planned on working on the paper in Feb but it got de-prioritized due to Pose/Keypoints tasks. We keep seeing feature requests that would be more helpful than the paper to the community. We'll work on the paper as soon as it comes to the top of the priority list.

**Comment by Robotatron** [comment]
Any ETA on the paper or is it no longer planned?

**Comment by olawalejuwonm** [comment]
> Any ETA on the paper or is it no longer planned?

Co-asking

**Comment by glenn-jocher** [comment]
Thank you for your interest. As of now, there is no specific ETA for the paper, but it remains on our roadmap. We will update the community when we have more information.

**Comment by CristianCantoro** [comment]
FYI, there is this paper:
[YOLOv8: A Novel Object Detection Algorithm with Enhanced Performance and Robustness](https://ieeexplore.ieee.org/document/10533619).
2024 International Conference on Advances in Data Engineering and Intelligent Computing Systems (ADICS) (2024) https://doi.org/10.1109/adics58448.2024.10533619
that already has 10 citations.

I didn't go through all the citations, vut for example, this paper:
[Wang, Q., Feng, W., Zhao, H., Liu, B., & Lyu, S. (2024). VALNet: Vision-Based Autonomous Landing with Airport Runway Instance Segmentation. Remote Sensing, 16(12), 2161.](https://www.mdpi.com/2072-4292/16/12/2161) references [YOLOv8-seg](https://docs.ultralytics.com/tasks/segment/), which is not mentioned in the ADICS paper.

I have left a comment [on PubPeer](https://pubpeer.com/publications/43A4FD524AC8F99A340362C2FD34BA#2) where I have pointed out that it is quite strange that the authors of the paper decided to name their algorithm YOLOv8 when they should have been aware this repository and algorithm with the same name already existed since it is cited by some of the papers they use as references.

**Comment by olawalejuwonm** [comment]
Thank you so much. That's quite helpful.

Yolov8 is great and works exceptionally well, I would also like to know if
there's other versions of model with more objects than the v8n.


Thank you again

**Comment by glenn-jocher** [comment]
Thank you for your kind words. For models with more objects than YOLOv8n, you can explore other versions like YOLOv8s, YOLOv8m, YOLOv8l, and YOLOv8x, which offer varying levels of complexity and performance.

**Comment by olawalejuwonm** [comment]
Thank you for your answer.

Can you share relevant links please?

**Comment by glenn-jocher** [comment]
@olawalejuwonm sure, you can find more information on the different YOLOv8 models and their capabilities at https://docs.ultralytics.com/models/.

**Comment by yidamyth** [comment]
Excuse me, are all the Yolo collections together now? Why not a separate Yolo home page

**Comment by glenn-jocher** [comment]
Yes—our docs intentionally unify all YOLO versions with per‑model landing pages; see the YOLO11 docs and the YOLOv8 docs, and since this thread is closed please start a new Discussion for follow‑ups so the team can track it.
