### ISSUE TITLE
Export to tflite format fails

### ISSUE THREAD

**Issue by Mikhael-Danilov** [ultralytics/ultralytics#3333]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

When i try to export trained model to tflite format yolo lies what export successfully while in fact onnx2tf invocation failed, and no tflite model was produced.

```
yolo model=best.pt export format='tflite' int8=true imgsz=640,480

Ultralytics YOLOv8.0.121 🚀 Python-3.10.6 torch-1.13.1+cu117 CPU
YOLOv8n summary (fused): 168 layers, 3007793 parameters, 0 gradients, 8.1 GFLOPs

PyTorch: starting from best.pt with input shape (1, 3, 640, 480) BCHW and output shape(s) (1, 15, 6300) (5.9 MB)

TensorFlow SavedModel: starting export with tensorflow 2.8.0...

ONNX: starting export with onnx 1.13.1 opset 16...
ONNX: simplifying with onnxsim 0.4.17...
ONNX: export success ✅ 1.1s, saved as best.onnx (11.6 MB)

TensorFlow SavedModel: running 'onnx2tf -i best.onnx -o best_saved_model -nuo --non_verbose -oiqt -qt per-tensor'
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/home/mike/.local/lib/python3.10/site-packages/onnx2tf/utils/common_functions.py", line 283, in print_wrapper_func
    result = func(*args, **kwargs)
  File "/home/mike/.local/lib/python3.10/site-packages/onnx2tf/ops/Input.py", line 81, in make_node
    if graph_input.shape != tf.TensorShape(None) and len(graph_input.shape) in [3, 4, 5] \
  File "/home/mike/.local/lib/python3.10/site-packages/tensorflow/python/framework/tensor_shape.py", line 1294, in __ne__
    raise ValueError("The inequality of unknown TensorShapes is undefined.")
ValueError: The inequality of unknown TensorShapes is undefined.
ERROR: input_onnx_file_path: best.onnx
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.
TensorFlow SavedModel: export failure ❌ 3.4s: SavedModel file does not exist at: best_saved_model/{saved_model.pbtxt|saved_model.pb}

TensorFlow Lite: starting export with tensorflow 2.8.0...
TensorFlow Lite: export success ✅ 0.0s, saved as best_saved_model/best_int8.tflite (0.0 MB)

Export complete (3.8s)
Results saved to /home/mike/Documents/target_2023_06_09/normalized/normalized/runs/detect/train8/weights
Predict:         yolo predict task=detect model=best_saved_model/best_int8.tflite imgsz=640,480 
Validate:        yolo val task=detect model=best_saved_model/best_int8.tflite imgsz=640,480 data=./data.yaml WARNING ⚠️ non-PyTorch val requires square images, 'imgsz=[640, 480]' will not work. Use export 'imgsz=640' if val is required.
Visualize:       https://netron.app
```

### Environment

Ultralytics YOLOv8.0.121 rocket Python-3.10.6 torch-1.13.1+cu117 CPU
OS: Ubuntu 22.04
Python 3.10.6

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Mikhael-Danilov TFLite export works correctly. This is part of our constant CI as explained above, most recent results from 13 hours ago shown below:

https://github.com/ultralytics/ultralytics/actions/runs/5361556785/jobs/9727623912
<img width="1420" alt="Screenshot 2023-06-24 at 16 12 03" src="https://github.com/ultralytics/ultralytics/assets/26833433/b1f5a3c8-cde9-4b72-8e3d-938444ac584d">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by glenn-jocher** [comment]
<img width="1044" alt="Screenshot 2023-06-24 at 16 18 20" src="https://github.com/ultralytics/ultralytics/assets/26833433/a5fb6813-2a11-4839-9da0-8df49c8c1d5f">

**Comment by gijskoning** [comment]
Upgrading Tensorflow to 2.12.0 (same as in the screenshot of Glenn) fixed the issue for me.

**Comment by pderrenger** [comment]
That's great to hear, @gijskoning! Upgrading to TensorFlow 2.12.0 seems to have resolved the export issue for you. Thank you for sharing the solution with us. If you encounter any further issues or have any more feedback, feel free to reach out. Happy coding! 😊🚀

**Comment by abhijeetanand16** [comment]
I see the same problem. My tensorflow version is 2.13.0
Any solution for this?

**Comment by pderrenger** [comment]
It sounds like you're encountering a similar issue. Could you please ensure you're using the latest version of the Ultralytics package? Sometimes, compatibility issues are resolved in newer releases. If the problem persists, try downgrading TensorFlow to 2.12.0, as it has worked for others. Let me know if that helps!

**Comment by abhijeetanand16** [comment]
![image](https://github.com/user-attachments/assets/ff028c84-f36e-4513-a192-021ecad31056)
This is the full log. Kindly suggest now.

**Comment by pderrenger** [comment]
@abhijeetanand16 thank you for sharing the full log. To address this issue, please ensure you are using the latest versions of the Ultralytics and TensorFlow packages. You can update them using `pip install -U ultralytics tensorflow`. If the problem persists, try downgrading TensorFlow to version 2.12.0, as it has resolved similar issues for other users. If you continue to experience difficulties, please provide additional details about your environment and any modifications you may have made. This will help us diagnose the issue more effectively.

**Comment by abhijeetanand16** [comment]
Thank you @pderrenger for your quick support.

I created and activated a new python environment. 
Then, I installed the libraries as suggested: `pip install -U ultralytics tensorflow`

Made a python script:
`from ultralytics import YOLO`
`model = YOLO(f'path to the model (.pt)')`
`model.export(format='tflite')`

**Ran this script and it generated me the tflite model.**

Versions of the libraries:
Ultralytics: 8.2.59
Tensorflow: 2.17.0

**Comment by pderrenger** [comment]
Thank you for the update. I'm glad to hear that creating a new Python environment and updating the libraries resolved the issue for you. If you encounter any further questions or issues, feel free to reach out. Happy coding!
