### ISSUE TITLE
How to get corresponding masks and boxes?

### ISSUE THREAD

**Issue by mrussell34** [ultralytics/ultralytics#3334]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When running inference on images on a custom trained instance segmentation model I am seeing that the results for masks and images don't line up. That is to say that result[0].masks does not correspond to result[1].boxes, although it is a proper detection that corresponds to a box at a different index. This is making it so that when I draw them on the image, the boxes are always the correct color but the masks flash different colors. How do I get them to line up?

**Comment by mrussell34** [comment]
In case anyone else sees this issue. The 'botsort' tracker reorganizes the boxes by track ID rather than confidence. I solved the issue by sorting them back.

**Comment by glenn-jocher** [comment]
@mrussell34 hi there! Thank you for raising this issue. The behavior you observed is correct, as the 'botsort' tracker arranges the boxes based on track ID rather than confidence. If you prefer the boxes to be sorted by confidence, you can sort them back using your own code. 

However, please note that the 'botsort' tracker is designed to prioritize tracking based on track ID. Changing the sorting method may affect the tracker's accuracy and performance. It's always a good idea to carefully consider the trade-offs before making any modifications to the default behavior.

If you have any further questions or need more assistance, please feel free to ask. We're here to help!
