### ISSUE TITLE
Unique ID when tracking

### ISSUE THREAD

**Issue by uzumakinaruto19** [ultralytics/ultralytics#3350]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi I have been using model.track on an rtsp stream which sends the data through webRTC and stream

The video is 720 p and runs on a GPU (about 60% utilization) I use bytetrack as my tracker, but the IDs are getting changed easily like when multiple people are the, it switches fast.. What are some suggestions that IDs will stay unique for a person? and occlusion handling

ps :I am using yolov8n as the detection model, detection is happening in 480p

Thanks in advance

**Comment by glenn-jocher** [comment]
@uzumakinaruto19 hi there,

Thank you for reaching out and providing the details of your setup.

To ensure unique IDs for each person and handle occlusion, there are a few suggestions you can consider:

1. **Improving Detection Model**: You mentioned that you are using YOLOv8n as the detection model. You can try experimenting with different YOLOv8 models or architectures to see if they provide better accuracy in detecting and tracking people, especially in occluded scenarios.

2. **Adjusting Detection Resolution**: Since you mentioned that the detection is happening in 480p, you can try increasing the detection resolution to 720p to obtain more precise detection results. This might help in reducing false positives and improving the tracking accuracy.

3. **Post-processing Techniques**: You can explore post-processing techniques to handle occlusions. One approach is to incorporate appearance-based features, such as face recognition or unique clothing characteristics, to associate detections with the same person across frames. Another approach is to use motion information to track the paths of individuals and predict their future locations even when they are temporarily occluded.

4. **Model Fine-tuning**: If you have access to additional annotated data specific to your application, you can fine-tune the YOLOv8 model on this data. Fine-tuning on domain-specific data can lead to improved performance, especially when dealing with specific challenges like occlusions.

It's worth mentioning that YOLOv8 is a powerful and widely-used object detection algorithm, but no algorithm is perfect and tracking in crowded or occluded scenes can be a challenging task. Therefore, trying out different strategies and techniques might be necessary to achieve the desired tracking accuracy and unique IDs for each person.

I hope these suggestions are helpful. Please feel free to ask further questions or provide additional details if needed.

Best regards,
Glenn Jocher

**Comment by uzumakinaruto19** [comment]
Thanks!! @glenn-jocher , will try all of these!!

So one more doubt, if my rtsp stream is 720o , what should be imgsz, 1024 or 512 , or doesn't matter?

The issue I'm having is, I'm using Supervision package to count the numbers, but when I am stream the video through webrtc the counter is not working properly
idk whether the frames are getting resized somewhere because I'm drawing the lines in 1280x720 and I'm not sure what is the frame size that is showing on the UI?

**Comment by glenn-jocher** [comment]
Hi @uzumakinaruto19,

You're welcome! I'm glad you found the suggestions helpful.

Regarding your doubt about the `imgsz` parameter, when using a 720p stream, you have a couple of options. Since YOLOv8 uses a 32-pixel stride, the input size should ideally be a multiple of 32. In your case, if you want to preserve the aspect ratio of the input images, you can set `imgsz` to 704 (a multiple of 32) while maintaining the aspect ratio of 1280x720.

Regarding the issue with the counter not working properly when streaming the video through WebRTC, it's possible that the frames are being resized somewhere along the pipeline. To ensure the counter works correctly, you can try the following:

1. Make sure that the frames being passed to the counter module are in the same size as the frames you are drawing the lines on (1280x720). You can check the frame size in the user interface to verify this.

2. If you suspect that the frames are being resized somewhere in the pipeline, you can investigate the different components involved in the streaming process (such as the WebRTC implementation, encoding, or decoding) to ensure that the frames are not being resized unintentionally.

By ensuring that the frames passed to the counter and the frames you are drawing the lines on have the same size, and investigating any potential resizing occurring in the streaming process, you should be able to rectify the issue with the counter not working properly.

I hope this clarifies your doubts. If you have any further questions or concerns, feel free to ask.

Best regards,
Glenn Jocher
