### ISSUE TITLE
When training the rtdetr model, appears in ultralytics\nn\modules\head.py   #273   AttributeError: module 'torch.nn' has no attribute 'inf'  

### ISSUE THREAD

**Issue by lsj147896325** [ultralytics/ultralytics#3353]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

![image](https://github.com/ultralytics/ultralytics/assets/95969668/d56ec758-7a00-4b5d-b1c7-7305b6122e68)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@lsj147896325 hi there! Thank you for bringing this issue to our attention.

The error message you encountered, `AttributeError: module 'torch.nn' has no attribute 'inf'`, suggests that there is an attribute error in the `head.py` file of the Ultralytics YOLOv8 repository.

To help us better understand the issue and provide a solution, could you please provide more details about your environment setup, such as the version of PyTorch and any other relevant dependencies you have installed? This will help us identify the root cause of the attribute error.

In the meantime, if you are willing to help, submitting a pull request (PR) with a fix would be greatly appreciated! Your contribution will not only benefit other users but also help us improve the overall quality of YOLOv8.

Thank you again for reporting this issue, and we look forward to assisting you further.

**Comment by glenn-jocher** [comment]
@lsj147896325 this is user error on your part it seems. There does not exist any instance of `torch.nn.inf` in this repository:
<img width="859" alt="Screenshot 2023-06-24 at 15 45 10" src="https://github.com/ultralytics/ultralytics/assets/26833433/63ac7f5d-f65e-47b1-a7d2-63424c9a9103">
