### ISSUE TITLE
How to setup batch size in predict segmentation

### ISSUE THREAD

**Issue by chelsea456** [ultralytics/ultralytics#3359]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to setup batch size in predict segmentation. i want to predict 8 images at the same time

**Comment by glenn-jocher** [comment]
@chelsea456 hi there! To set up the batch size for predicting segmentation using YOLOv8, you can simply pass a list of images to the predict function instead of a single image. Each image in the list will be processed independently, allowing you to predict on multiple images at the same time.

For example, if you have a list of 8 images, you can pass this list to the predict function and YOLOv8 will process all of them simultaneously. The batch size is effectively the number of images in the list.

Hope this helps! If you have any further questions, feel free to ask.

**Comment by chelsea456** [comment]
> @chelsea456 hi there! To set up the batch size for predicting segmentation using YOLOv8, you can simply pass a list of images to the predict function instead of a single image. Each image in the list will be processed independently, allowing you to predict on multiple images at the same time.
> 
> For example, if you have a list of 8 images, you can pass this list to the predict function and YOLOv8 will process all of them simultaneously. The batch size is effectively the number of images in the list.
> 
> Hope this helps! If you have any further questions, feel free to ask.

tks sir!! but i thinh if use batch size time predict one image and 8 images is the same, but time predict 8 images longer than 1 image 8x.

**Comment by Akashkalasagond** [comment]
hey there! i have around 4500 training , samples and 1190 validation samples , what can i add for the batch size?
