### ISSUE TITLE
ImportError cannot import name 'callbacks' from partially initialized module 'ultralytics.yolo.utils.callbacks.tensorboard'

### ISSUE THREAD

**Issue by aadityabhetuwal** [ultralytics/ultralytics#3372]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Integrations

### Bug

I was trying to parse videos in multiple threads using `concurrent.futures.ThreadPoolExecutor` module when I encountered this ImportError. This error kills seems to kill the thread.

![image](https://github.com/ultralytics/ultralytics/assets/57558367/7459da54-3ec9-43fd-a09d-208d96df66c9)

### Environment

- OS: Windows 11 22621.1848 Build
- Python: 3.9

### Minimal Reproducible Example

```
from ultralytics import YOLO
import cv2
import concurrent.futures
import torch

def extractImages(videoPath : str, imageFeatures : list[torch.Tensor]):

    capture = cv2.VideoCapture(videoPath)
    size =(640, 640)

    fps = capture.get(cv2.CAP_PROP_FPS) # get the frames of the video
    print(f"Frames per video = {fps}")

    model = YOLO("yolov8s")

    # persons = [] # to store only the cropped image of identified persons
    
    frameCounter = 0 
    while capture.isOpened():
        ret, frame = capture.read()
        
        # if no frame exists break
        if not ret:
            break
            
        try:
            
            result = model.predict(frame)[0]
        except Exception as e:
            traceback.print_exc(5)


with concurrent.futures.ThreadPoolExecutor(max_workers= len(videoPaths)) as executor:
        futures = [
            executor.submit(extractImages, path, imageFeatures)
            for path in videoPaths
        ]

        [future.result() for future in futures]
```

### Additional

Stack Trace

```
Traceback (most recent call last):
  File "d:\projects\person-reidentification\src\extractPeople.py", line 83, in extractImages
    result = model.predict(frame)[0]
  File "D:\Python\Python39\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Python\Python39\lib\site-packages\ultralytics\yolo\engine\model.py", line 249, in predict
    self.predictor = TASK_MAP[self.task][3](overrides=overrides, _callbacks=self.callbacks)
  File "D:\Python\Python39\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 109, in __init__
    callbacks.add_integration_callbacks(self)
  File "D:\Python\Python39\lib\site-packages\ultralytics\yolo\utils\callbacks\base.py", line 205, in add_integration_callbacks
    from .tensorboard import callbacks as tensorboard_cb
ImportError: cannot import name 'callbacks' from partially initialized module 'ultralytics.yolo.utils.callbacks.tensorboard' (most likely due to a circular import) (D:\Python\Python39\lib\site-packages\ultralytics\yolo\utils\callbacks\tensorboard.py)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@aadityabhetuwal the error message suggests that there is an `ImportError` related to a circular import in the YOLOv8 library from Ultralytics. This might be an issue with the library itself or with how it is being used. Here are a few steps that you can try to resolve or workaround the issue:

1. **Update the Library**: Ensure that you are using the latest version of the Ultralytics YOLOv8 library. Sometimes these issues are fixed in later releases.

    ```
    pip install --upgrade ultralytics
    ```

2. **Load Model Once**: In your code, you are loading the model for every video inside the `extractImages` function which is being executed in separate threads. This could be problematic as loading models is resource-intensive and could cause issues when done in parallel. You might want to load the model only once and then pass it to the function.

3. **Check for Compatibility**: Ensure that your Python version is compatible with the YOLOv8 library. If you are using Python 3.9, you might want to try using Python 3.8 instead, as sometimes libraries have better support for slightly older versions.

4. **Report the Issue**: If none of the above solutions work, it might be a good idea to report this issue to the Ultralytics YOLOv8 repository, providing them with the details that you have mentioned. Since this seems like an internal issue with the library, the maintainers might be able to provide a fix or guidance on how to avoid it.

Below is a modified version of your code, which loads the model only once and passes it to the `extractImages` function:

```python
from ultralytics import YOLO
import cv2
import concurrent.futures
import torch

def extractImages(model, videoPath, imageFeatures):
    capture = cv2.VideoCapture(videoPath)
    size = (640, 640)
    
    fps = capture.get(cv2.CAP_PROP_FPS) # get the frames of the video
    print(f"Frames per video = {fps}")

    frameCounter = 0 
    while capture.isOpened():
        ret, frame = capture.read()
        
        # if no frame exists break
        if not ret:
            break
            
        try:
            result = model.predict(frame)[0]
        except Exception as e:
            print(e)

# Load model once
model = YOLO("yolov8s")

# List of video paths
videoPaths = ['path/to/video1.mp4', 'path/to/video2.mp4']

# List for storing image features
imageFeatures = []

# Execute in ThreadPoolExecutor
with concurrent.futures.ThreadPoolExecutor(max_workers=len(videoPaths)) as executor:
    futures = [
        executor.submit(extractImages, model, path, imageFeatures)
        for path in videoPaths
    ]
    
    [future.result() for future in futures]
```

This modification includes loading the model only once before the ThreadPoolExecutor, and passing it as an argument to the `extractImages` function.
