### ISSUE TITLE
Hyperparameter "augment" setting

### ISSUE THREAD

**Issue by lkj312951210** [ultralytics/ultralytics#3386]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When using YOLOv8 for segmentation, I always get "train_batch*.jpg" files, which are augmented images, during training, even though I set the hyperparameter "augment" to be False.

**Comment by Laughing-q** [comment]
@lkj312951210 the `augment` in cfg is for predict mode, and augmentations for training is hardcoded to True by default .

**Comment by glenn-jocher** [comment]
@lkj312951210 Unfortunately, there is no way to cancel data augmentation during training because it is hardcoded to True by default. However, you can customize the augmentation policies to have minimal effects on the images in question, or you can modify the training script to skip data augmentation. Nonetheless, we recommend using data augmentation when possible because it can improve the overall performance of your trained model. If you need further assistance, feel free to ask.

**Comment by lkj312951210** [comment]
> @lkj312951210 Unfortunately, there is no way to cancel data augmentation during training because it is hardcoded to True by default. However, you can customize the augmentation policies to have minimal effects on the images in question, or you can modify the training script to skip data augmentation. Nonetheless, we recommend using data augmentation when possible because it can improve the overall performance of your trained model. If you need further assistance, feel free to ask.

@glenn-jocher Thanks for your suggestions. I tried modifying the training script (ultralytics.yolo.data.build.py) as follows.
"augment=mode == 'train'" -> "augment=False"

Unfortunately, it didn't give me any improvement. So @glenn-jocher is correct, and it is not a good idea to skip image augmentation during training.

**Comment by glenn-jocher** [comment]
@lkj312951210 Thanks for giving it a try, and we're sorry to hear that modifying the training script did not give you the desired results. As we recommended previously, we suggest customizing the augmentation policies instead of skipping them entirely. You can reduce the degree of image modifications by selecting less aggressive augmentation policies. You can also try other data augmentation techniques like random erasing, rotation, and flipping, and adjust their parameters to better suit your needs. If you need any further help, please feel free to ask.
