### ISSUE TITLE
Hyperparameter Tuning Each iteration of progress bar starts a new line in Jupyter

### ISSUE THREAD

**Issue by danielzhangau** [ultralytics/ultralytics#3389]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Evolution

### Bug

The progress bar is making the logging extremely long and really hard to see how the tuning going. I suspect the problem is located with the code that related the hyperparameter tuning since when I do the training and evaluating, the bar is normal.
```
...
(_tune pid=1319543) Plotting labels to runs/detect/train/labels.jpg... 
(_tune pid=1319543) optimizer: SGD(lr=0.01, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.00013294968474073565), 63 bias(decay=0.0)
(_tune pid=1319543) Image sizes 640 train, 640 val
(_tune pid=1319543) Using 6 dataloader workers
(_tune pid=1319543) Logging results to runs/detect/train
(_tune pid=1319543) Starting training for 100 epochs...
(_tune pid=1319543) 
(_tune pid=1319543)       Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/1407 [00:00<?, ?it/s]
      1/100      2.09G   0.007935      22.73      2.116         52        640:   0%|          | 1/1407 [00:00<07:46,  3.02it/s]
      1/100      2.09G   0.007799      22.87      2.116         45        640:   0%|          | 2/1407 [00:00<08:15,  2.83it/s]
      1/100      2.09G   0.007562      23.59        1.9         29        640:   0%|          | 3/1407 [00:01<08:12,  2.85it/s]
      1/100      2.09G   0.007798      25.34      1.935         26        640:   0%|          | 4/1407 [00:01<07:41,  3.04it/s]
      1/100       2.1G   0.007855      24.57      1.974         67        640:   0%|          | 4/1407 [00:01<07:41,  3.04it/s]
      1/100       2.1G   0.007794      24.63      1.953         42        640:   0%|          | 6/1407 [00:01<04:43,  4.93it/s]
      1/100       2.1G   0.007802      24.45      1.971         47        640:   0%|          | 6/1407 [00:01<04:43,  4.93it/s]
      1/100       2.1G   0.007822      24.68      1.983         35        640:   1%|          | 8/1407 [00:01<03:37,  6.43it/s]
      1/100       2.1G   0.007919       24.9      2.007         43        640:   1%|          | 8/1407 [00:01<03:37,  6.43it/s]
      1/100       2.1G   0.007798      24.99      1.979         33        640:   1%|          | 10/1407 [00:01<03:05,  7.54it/s]
      1/100       2.1G   0.007797      24.81      1.996         26        640:   1%|          | 12/1407 [00:02<02:46,  8.39it/s]
      1/100       2.1G   0.007782      24.72       2.01         27        640:   1%|          | 12/1407 [00:02<02:46,  8.39it/s]
      1/100       2.1G   0.007866      24.96      2.024         29        640:   1%|          | 14/1407 [00:02<02:33,  9.07it/s]
      1/100       2.1G   0.007887         25      2.011         34        640:   1%|          | 14/1407 [00:02<02:33,  9.07it/s]
      1/100       2.1G    0.00791      24.94      2.012         40        640:   1%|          | 16/1407 [00:02<02:26,  9.50it/s]
...
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@danielzhangau 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
