### ISSUE TITLE
Restore support for usage of ClearML dataset

### ISSUE THREAD

**Issue by pktiuk** [ultralytics/ultralytics#3407]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

This is an old feature already existing in YOLOv5

It allowed downloading datasets directly from ClearML dataset repository

It is described here: https://clear.ml/blog/yolov5-integration/

```bash
python train.py --img 640 --batch 16 --epochs 3 --data clearml://<your_dataset_id> --weights yolov5s.pt --cache
```

### Use case

This is not only about downloading these datasets, but also linking them with experiments.

### Additional

Before starting work on this I would like to know why this feature was removed (or not ported to YOLOv8). 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@pktiuk thank you for bringing this up. The ClearML dataset feature was available in YOLOv5, but it has not been ported to YOLOv8. It's always great to see community contributions, and we welcome your pull request to restore this feature. Regarding why the feature was not ported to YOLOv8, there have been some changes in the codebase and architecture since YOLOv5, which may have impacted the integration of the ClearML dataset. Nonetheless, we are happy to see community members take an active interest in the development of YOLOv8, and we will support any efforts to bring back this feature. Thank you!

**Comment by pktiuk** [comment]
Don't close.

**Comment by glenn-jocher** [comment]
@pktiuk i apologize for any confusion, and I appreciate your patience in waiting for a resolution. I'll keep this issue open as we explore the potential restoration of ClearML dataset support in YOLOv8. It's important for us to understand and meet the needs of our user base, so your feedback is very much appreciated. While I may not have a direct solution at this moment, I want to assure you that the team is aware of this matter and we're looking into it.

Also, I want to take the opportunity to thank you for your willingness to contribute by submitting a PR. Keep in mind to carefully analyse the codebase changes and dependencies compared to previous versions before starting with the feature implementation. It’s our community's dedicated contributions like yours that make YOLOv8 that much better. Thanks again, and stay tuned for further updates regarding this feature request.

**Comment by pktiuk** [comment]
When my team will finish migrating their workflow into the ClearML I will also start investigating how it could be reimplemented.

**Comment by glenn-jocher** [comment]
@pktiuk, that sounds like a plan! It's great to know that you're planning to examine the reimplementation of the ClearML dataset feature in YOLOv8. Your contribution is highly appreciated as it will enhance the usability of the model for other members of the community. Do note that the feature implementation could be a complex task due to the codebase changes that vary from previous versions. Please feel free to ask any questions or seek help during your workflow migration and subsequent investigation, and remember to share any findings or progress with us. Thank you for making YOLOv8 better, we look forward to your further updates on this matter!
