### ISSUE TITLE
Data util `verify_image_label` does not correctly check for segment only data

### ISSUE THREAD

**Issue by GreatGameDota** [ultralytics/ultralytics#3426]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

https://github.com/ultralytics/ultralytics/blob/17e139220bf7988cf89d547f00f715989c79eefe/ultralytics/yolo/data/utils.py#L88
This line in `verify_image_label` checks if the label is a segment label however `len(x) > 6` is inaccurate because a segment label can be of length 3 at minimum. The [documentation](https://docs.ultralytics.com/datasets/segment/) describes segment label as `<class-index> <x1> <y1> <x2> <y2> ... <xn> <yn>` where a single label would be `<class-index> <x1> <y1>`.

### Minimal Reproducible Example

Given an image label file:
```
0 0.773438 0.363281 0.882812 0.355469
```
Running this code:
https://github.com/ultralytics/ultralytics/blob/17e139220bf7988cf89d547f00f715989c79eefe/ultralytics/yolo/data/utils.py#L86-L92
Results in 
`lb = [[0, 0.77344, 0.36328, 0.88281, 0.35547]]` and `segments = []`
instead of
`lb = [[0, 0.82812, 0.35938, 0.10937, 0.007812]]` and `segments = [[0.77344, 0.36328], [0.88281, 0.35547]]`

### Additional

There is also the issue of this code:
https://github.com/ultralytics/ultralytics/blob/17e139220bf7988cf89d547f00f715989c79eefe/ultralytics/yolo/data/utils.py#L92
https://github.com/ultralytics/ultralytics/blob/17e139220bf7988cf89d547f00f715989c79eefe/ultralytics/yolo/data/utils.py#L90
Converting the strings to a lower precision float (as shown in above example). However, this is not a major issue as changes in pixel placement is usually irrelevant.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@GreatGameDota also the float32 change may not be visible in the console, it may be that the default torch/numpy printout is only displaying 5 digits as you are showing in your original comment. It's true that there is a difference, but I'm not sure if it starts to show at 5 decimal places or later, though I do know the console output you see is typically truncated at 5 decimal places.

**Comment by glenn-jocher** [comment]
@GreatGameDota I've updated the docs page here for better clarity :)

<img width="1415" alt="Screenshot 2023-06-28 at 14 08 59" src="https://github.com/ultralytics/ultralytics/assets/26833433/2320e69f-0a4b-4eb2-8ad6-31c5bb589185">

**Comment by GreatGameDota** [comment]
That makes sense I was not aware of that. However, that means the `rle2polygon` function in `convert_coco` produces invalid results as the example above was produced by it, where the mask was a line.

**Comment by glenn-jocher** [comment]
@GreatGameDota thank you for bringing this to our attention. You are correct that the current implementation of the `rle2polygon` function in the `convert_coco` module may produce invalid results in certain cases, such as when the mask is a line.

We apologize for any confusion or inconvenience caused by this issue. We appreciate your feedback and will take this into consideration for future improvements to the Ultralytics YOLOv8 repository.

In the meantime, we recommend manually inspecting and verifying the results of the `rle2polygon` function when dealing with segment label data that may contain lines or other irregular shapes.

If you have any further questions or concerns, please don't hesitate to reach out. We are here to help.
