### ISSUE TITLE
Multiple machines Training Request

### ISSUE THREAD

**Issue by berry-ding** [ultralytics/ultralytics#3428]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hello! I've noticed that the YOLOv8 code does not yet support multi-machine training, and it seems like it would not be an easy task to modify it to do so. Is there a plan to release a version of the code that supports multi-machine training?

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@berry-ding thanks for asking! We added multi-node support to [YOLOv5](https://github.com/ultralytics/yolov5), but we relied on a user PR there since we are unable to debug this currently (we have only 1 training server). 

If you have multiple nodes available and expertise on this we'd be happy to receive a PR, but we'd need to rely on you to debug it and verify it's working correctly.

**Comment by MZellou** [comment]
I have access to a SLURM cluster and would be happy to help test it

**Comment by glenn-jocher** [comment]
@MZellou hi there! Thank you for your interest in YOLOv8 and for offering to help with multi-machine training. Currently, YOLOv8 does not support multi-machine training out of the box. Although we appreciate your willingness to contribute, we don't have the resources to debug and verify multi-machine training ourselves at the moment. However, if you're familiar with SLURM cluster setups and have the expertise to implement and test multi-machine training, we would be happy to consider a pull request from you. Your contribution would greatly benefit the YOLOv8 community. Thank you again for your offer to help!
