### ISSUE TITLE
Why the binary masks are resized into 640 and how can I obtain the original shape ?

### ISSUE THREAD

**Issue by leviethung2103** [ultralytics/ultralytics#3438]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello there,

I am currently doing the Segmentation Task using the Yolov8n model. 

The YOLO does support the binary mask result. However, I've realized that the shape of binary mask is resized to 640. 

The original image is 1920xx1080. 

How can I obtain the binary mask with original shape of 1920x1080. Thank you in advance.

**Comment by glenn-jocher** [comment]
@leviethung2103 hi,

When performing the Segmentation Task using the YOLOv8n model, the binary masks are resized to a shape of 640. This resizing is done for efficiency and to ensure compatibility with the YOLOv8 network architecture.

If you would like to obtain the binary mask with the original shape of 1920x1080, you can resize it back to the original shape using any image processing library or framework of your choice, such as OpenCV or PIL. This can be done by applying a resizing operation with the desired dimensions.

By using the appropriate resizing operation, you can get the binary mask with the original shape, allowing you to work with the mask in its original resolution.

I hope this helps! Let me know if you have any further questions.

**Comment by leviethung2103** [comment]
Hello @glenn-jocher 

Thank you so much for your answer. One last thing I concern is that, given an original shape, for example 1920x1080, how can estimate the new shape that is predicted from model. The width value would be 640, but I don't know to how to calculate the height value.

Could you please provide the function or tell me the method to do that ? 

Thank you in advance.

**Comment by glenn-jocher** [comment]
Hi @leviethung2103, 

Thank you for your question. To estimate the new shape of the predicted output from the YOLOv8 model, you can use the aspect ratio of the original image. 

Since the width is being resized to 640, you can calculate the new height by maintaining the aspect ratio. 

Here's how you can calculate the new height:

1. Determine the aspect ratio of the original image by dividing the original width by the original height: `aspect_ratio = original_width / original_height`.
2. Calculate the new height by multiplying the new width (640) by the aspect ratio: `new_height = 640 / aspect_ratio`.

By following these steps, you can estimate the new shape of the predicted output while maintaining the aspect ratio of the original image.

I hope this helps! Let me know if you have any further questions.
