### ISSUE TITLE
Fps changes from original video

### ISSUE THREAD

**Issue by litaldavar** [ultralytics/ultralytics#3452]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I run on the tracked video I get a different fps from my original video how can I set it so it won't change?

code:
 for result in self.model.track(source=source_file_path, tracker=r'/home/lital/NativeTrackingYOLOv8/custom_track.yaml',  stream=True):

**Comment by glenn-jocher** [comment]
Hello @litaldavar,

Thank you for reaching out. In regards to the FPS change in the tracked video, it is important to note that the FPS might differ from the original video due to various factors. One factor is the number of predictions made by the model. If there are more predictions in the photo or video, it can lead to a decrease in FPS.

To address your second question, could you please provide details on how you are calculating the FPS of your model output? This information will help us better understand the issue and provide more specific guidance.

Looking forward to your response.

Best regards,
Glenn Jocher
