### ISSUE TITLE
hide_labels,hide_conf are not working. Although i give the parameter to the True, they are still showing.

### ISSUE THREAD

**Issue by ImSuMyatNoe** [ultralytics/ultralytics#3453]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

hide_labels,hide_conf are not working. Although i give the parameter to the True, they are still showing in the tracking video.

### Environment

OS: Ubuntu
OS: Google Colab, too

YOLO : Latest version 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ImSuMyatNoe** [comment]
@glenn-jocher I have also tested that show_conf and show_labels do not work too. I gave both of them to False Parameter but, the labels and confidence scores are still showing.

**Comment by glenn-jocher** [comment]
@ImSuMyatNoe thank you for bringing this to our attention. I understand that you're experiencing an issue with the `show_labels` and `show_conf` parameters in YOLOv8.

I want to clarify that in the Ultralytics YOLOv8 repository, we have deprecated those parameters in favor of a different approach. Instead of `show_labels` and `show_conf`, we now use `show_bbox` to control whether or not the bounding boxes are shown in the output. If `show_bbox` is set to `False`, the bounding boxes will not be displayed.

Please update your code to use the `show_bbox` parameter instead, and let us know if you continue to encounter any issues. We apologize for any confusion caused by the deprecated parameters, and thank you for bringing this to our attention.

**Comment by ImSuMyatNoe** [comment]
Hi @glenn-jocher  thanks for the update. I just use the updated git repo and use the show_bbox command. But unfortunately, the error is out in the following attached files.
![Capture](https://github.com/ultralytics/ultralytics/assets/19759376/35028198-e37b-42ac-bae2-af3540e65088)

**Comment by glenn-jocher** [comment]
Hi @ImSuMyatNoe, thank you for the update. I apologize for the inconvenience you are experiencing with the `show_bbox` command.

In order to further assist you, could you please provide more details about the error you are encountering? This will help us understand the issue better and provide you with an appropriate solution.

Regarding the documentation, I apologize for any confusion caused. Please note that the link you provided is incorrect. The correct link to the updated documentation for YOLOv8 can be found here: https://docs.ultralytics.com/usage/cfg/#predict

Again, thank you for bringing this to our attention. We are committed to resolving this issue for you as quickly as possible. Please provide the additional details about the error so that we can assist you further.

Best regards,
Glenn Jocher
