### ISSUE TITLE
I converted pose model to tfjs and I get an error when I give the input photo to the model

### ISSUE THREAD

**Issue by FatemeZamanian** [ultralytics/ultralytics#3457]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

in this ilne :
``` const res = model.net.execute(input); ```
I got this error : 
<img width="942" alt="Screenshot 2023-06-29 at 1 59 03 PM" src="https://github.com/ultralytics/ultralytics/assets/78360814/aa86fdc2-1d23-4d3b-86f7-4c70816c415e">
**This issue is just for pose model**

**Comment by glenn-jocher** [comment]
@FatemeZamanian hi there! It looks like you're experiencing an error when giving an input photo to the pose model after converting it to TFJS. 

This issue seems to be specific to the pose model and not related to YOLOv8. I recommend posting your question in the appropriate repository for the pose model you are using or reaching out to the developers of that model for further assistance.

Please keep in mind that this GitHub repository is specifically for YOLOv8 related issues. If you have any questions or issues related to YOLOv8 specifically, please feel free to ask, and we'll be happy to help you out.

Thank you for your understanding, and I hope you're able to resolve the issue with the pose model.
