### ISSUE TITLE
How does YOLOv8 print out GFLOPs for each layer of the model?

### ISSUE THREAD

**Issue by xuchuanzhen** [ultralytics/ultralytics#3462]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to print GFLOPs of each layer of yolov8 model, how to write a python program? Can I call the official tools?
![image](https://github.com/ultralytics/ultralytics/assets/131573646/a74c18b4-f158-4fe5-b300-e0cdaf1ababc)

**Comment by xuchuanzhen** [comment]
> 👋 Hello @xuchuanzhen, thank you for your interest in YOLOv8 🚀! We recommend a visit to the [YOLOv8 Docs](https://docs.ultralytics.com) for new users where you can find many [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) usage examples and where many of the most common questions may already be answered.
> 
> If this is a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us debug it.
> 
> If this is a custom training ❓ Question, please provide as much information as possible, including dataset image examples and training logs, and verify you are following our [Tips for Best Training Results](https://docs.ultralytics.com/yolov5/tutorials/tips_for_best_training_results/).
> 
> Join the vibrant [Ultralytics Discord](https://discord.gg/YVsATxj6wr) 🎧 community for real-time conversations and collaborations. This platform offers a perfect space to inquire, showcase your work, and connect with fellow Ultralytics users.
> 
> ## Install
> Pip install the package including all [requirements](https://github.com/ultralytics/ultralytics/blob/main/requirements.txt) in a [**Python>=3.7**](https://www.python.org/) environment with [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/).`ultralytics`
> 
> ```shell
> pip install ultralytics
> ```
> 
> ## Environments
> YOLOv8 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):
> 
> * **Notebooks** with free GPU: [![Run on Gradient](https://camo.githubusercontent.com/c9931a1689c37ab786edd3e1e5f59b9a6f7d097628c4689ce2432563ef884524/68747470733a2f2f6173736574732e706170657273706163652e696f2f696d672f6772616469656e742d62616467652e737667)](https://console.paperspace.com/github/ultralytics/ultralytics) [![Open In Colab](https://camo.githubusercontent.com/84f0493939e0c4de4e6dbe113251b4bfb5353e57134ffd9fcab6b8714514d4d1/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb) [![Open In Kaggle](https://camo.githubusercontent.com/a08ca511178e691ace596a95d334f73cf4ce06e83a5c4a5169b8bb68cac27bef/68747470733a2f2f6b6167676c652e636f6d2f7374617469632f696d616765732f6f70656e2d696e2d6b6167676c652e737667)](https://www.kaggle.com/ultralytics/yolov8)
> * **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
> * **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
> * **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) [![Docker Pulls](https://camo.githubusercontent.com/7401823bed1473d6db1ff60b933d51cd1534c448488f06c446c322227d31d966/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f756c7472616c79746963733f6c6f676f3d646f636b6572)](https://hub.docker.com/r/ultralytics/ultralytics)
> 
> ## Status
> [![Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg)](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule)
> 
> If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=event%3Aschedule) tests are currently passing. CI tests verify correct operation of all YOLOv8 [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) on macOS, Windows, and Ubuntu every 24 hours and on every commit.

I can't find any information in the yolov8 documentation on how to print GFLOPs for each layer of the model.

**Comment by glenn-jocher** [comment]
@xuchuanzhen, thank you for your interest in YOLOv8! To print the GFLOPs (giga floating-point operations) for each layer of the YOLOv8 model, you can use the `flops_counter.py` script provided in the YOLOv8 repository.

The `flops_counter.py` script analyzes the network architecture and calculates the number of GFLOPs for each layer. You can find the script in the `yolov8/utils` directory of the YOLOv8 repository. To use it, you can import the script into your Python code and pass the YOLOv8 model to the `flops_to_string` function. This will return a string with the GFLOPs for each layer.

Please note that the `flops_counter.py` script is specific to the YOLOv8 model and might not work with other versions or models. Additionally, keep in mind that printing the GFLOPs for each layer can be computationally expensive, so it's recommended to use this feature sparingly.

Let me know if you have any further questions or need additional assistance!

**Comment by xuchuanzhen** [comment]
I do not find flops_counter.py file in the official source code of YOLOv8, could you please give me a simple example? Or could you please tell me where flops_counter.py is?

**Comment by glenn-jocher** [comment]
@xuchuanzhen the `flops_counter.py` script is not included in the official source code of YOLOv8. Apologies for the confusion. Although it is not directly available in the YOLOv8 repository, you can find similar scripts or libraries outside the YOLOv8 repository that can help you calculate the GFLOPs for each layer of a neural network. These scripts or libraries usually analyze the network architecture and provide the computational complexity in terms of GFLOPs.

One such library is `thop` (https://github.com/Lyken17/pytorch-OpCounter), which is a popular option for estimating the FLOPs of PyTorch models. You can install `thop` library using pip (`pip install thop`). Once installed, you can import the library in your code, create an instance of the model, and use the `profile` function to calculate the FLOPs for the model.

Keep in mind that the `thop` library or any other similar script/library may have slight differences in usage compared to `flops_counter.py` (if it existed). Therefore, it's important to refer to the specific documentation and examples provided by the library or script you choose.

Please let me know if you have any further questions or need additional assistance!

**Comment by AndywithCV** [comment]
> @xuchuanzhen the `flops_counter.py` script is not included in the official source code of YOLOv8. Apologies for the confusion. Although it is not directly available in the YOLOv8 repository, you can find similar scripts or libraries outside the YOLOv8 repository that can help you calculate the GFLOPs for each layer of a neural network. These scripts or libraries usually analyze the network architecture and provide the computational complexity in terms of GFLOPs.
> 
> One such library is `thop` (https://github.com/Lyken17/pytorch-OpCounter), which is a popular option for estimating the FLOPs of PyTorch models. You can install `thop` library using pip (`pip install thop`). Once installed, you can import the library in your code, create an instance of the model, and use the `profile` function to calculate the FLOPs for the model.
> 
> Keep in mind that the `thop` library or any other similar script/library may have slight differences in usage compared to `flops_counter.py` (if it existed). Therefore, it's important to refer to the specific documentation and examples provided by the library or script you choose.
> 
> Please let me know if you have any further questions or need additional assistance!

Can you please assist me on that thop customization to adapt with yolov8 for printing out all the values of each layer on the model, or does yolov8 has any specific command that does the same job? thankyou!

**Comment by glenn-jocher** [comment]
@AndywithCV i'm sorry for the confusion earlier, but currently, YOLOv8 does not provide an in-built functionality or a specific command to calculate and print GFLOPs for each layer of the model. However, you can certainly make use of external libraries like `thop` to achieve these calculations.

For your requirement of printing GFLOPs for each layer, you'll need to create an instance of your YOLOv8 model and then pass the model instance to the `profile` function of `thop`. The library has its way of breaking the model down and inspecting each layer, so it should provide you the GFLOPs count you need.

While customizing the `thop` to adapt to YOLOv8, you may need to iterate over the layers of the model in a loop and call the `profile` function for each layer separately. Remember to refer to the specific documentation and examples provided by the `thop` library which would guide you through the process.

I hope that helps and let me know if you have any more queries!

**Comment by ovidedecroly** [comment]
@glenn-jocher hello, Where can I modify the function to calculate GFLOPs? I modified the backbone and architecture of YOLOv8 significantly. Thanks you

**Comment by glenn-jocher** [comment]
Hello @ovidedecroly, it's great to hear about your work on adapting the YOLOv8 architecture! If you've made significant modifications to the backbone and architecture of YOLOv8, calculating the GFLOPs will require a custom approach.

Unfortunately, there is no specific function within the YOLOv8 codebase that you can simply modify to calculate GFLOPs. However, you can use external libraries like `thop` (PyTorch Operator Profiling) to estimate the FLOPs of your model.

You might have to configure `thop` or a similar package to accommodate any custom layers or operations you've introduced in your modified YOLOv8 architecture. `thop` by default supports many common PyTorch operations, but for custom layers, you would need to define a hook that tells `thop` how to calculate the FLOPs for these layers.

Here's a very high-level description of the process you might follow:

1. Define your modified YOLOv8 model and ensure it's properly configured with all custom layers properly defined.
2. Create a model instance with the necessary input dimensions.
3. Install `thop` via `pip` if you haven't already done so.
4. Import `thop` in your script where the YOLOv8 instance is defined.
5. Use `thop.profile` function, passing your model and a batch of input data to it.
6. For any custom operations, use the `register_hooks` function from `thop` to define how FLOPs should be calculated.

Remember that accurate custom FLOP calculation will require you to understand the operations your new layers are performing. You will need the forward pass computation logic to determine the FLOPs manually for your custom layers.

Please refer to the `thop` documentation and PyTorch model definition guidelines for the specifics of adding custom hooks for FLOP calculation. If your modifications follow standard PyTorch layer conventions, `thop` should be able to handle most of the work for you.

Due to the complexity of this task, there can be several iterations to ensure that the FLOPs are being calculated accurately for your specific architecture modifications.

If you have more questions about this or need further support, please don't hesitate to ask. Good luck with your model development!

**Comment by lesept777** [comment]
Hi, I tried to compute the GFLOPS (or MMACS) of mmy model, using `thop`, but I get an error:

```
WARNING ⚠️ no model scale passed. Assuming scale='n'.
YOLOv8-medium summary: 81 layers, 398554 parameters, 398554 gradients, 2.5 GFLOPs
Transferred 128/128 items from pretrained weights
engine/trainer: task=classify, mode=train, model=yolov8-medium.yaml, data=imagenet10, epochs=100, time=None, patience=100, batch=16, imgsz=224, save=True, save_period=-1, cache=False, device=cpu, workers=8, project=None, name=train2, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/classify/train2
train: /data1/is156025/fa125436/Confluence/Yolo/datasets/imagenet10/train... found 12 images in 10 classes ✅
val: /data1/is156025/fa125436/Confluence/Yolo/datasets/imagenet10/val... found 12 images in 10 classes ✅
test: None...
WARNING ⚠️ no model scale passed. Assuming scale='n'.

                   from  n    params  module                                       arguments                
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]            
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]           
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]        
  3                  -1  1     16240  ultralytics.nn.modules.conv.Conv             [32, 56, 3, 2]           
  4                  -1  2     38080  ultralytics.nn.modules.block.C2f             [56, 56, 2, True]        
  5                  -1  1     52624  ultralytics.nn.modules.conv.Conv             [56, 104, 3, 2]          
  6                  -1  2    130624  ultralytics.nn.modules.block.C2f             [104, 104, 2, True]      
  7                  -1  1    148490  ultralytics.nn.modules.head.Classify         [104, 10]                
YOLOv8-medium summary: 81 layers, 398554 parameters, 398554 gradients, 2.5 GFLOPs
Transferred 128/128 items from pretrained weights
TensorBoard: Start with 'tensorboard --logdir runs/classify/train2', view at http://localhost:6006/
train: Scanning /data1/is156025/fa125436/Confluence/Yolo/datasets/imagenet10/train... 12 images, 0 corrupt:
val: Scanning /data1/is156025/fa125436/Confluence/Yolo/datasets/imagenet10/val... 12 images, 0 corrupt: 100%
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000714, momentum=0.9) with parameter groups 21 weight(decay=0.0), 22 weight(decay=0.0005), 22 bias(decay=0.0)
TensorBoard: model graph visualization added ✅
Image sizes 224 train, 224 val
Using 0 dataloader workers
Logging results to runs/classify/train2
Starting training for 100 epochs...

      Epoch    GPU_mem       loss  Instances       Size
      1/100         0G      3.211         12        224: 100%|██████████| 1/1 [00:02<00:00,  2.05s/it]
               classes   top1_acc   top5_acc: 100%|██████████| 1/1 [00:00<00:00, 11.79it/s]
                   all     0.0833      0.333
**********************************************************
************  SKIPPING 98 EPOCHS ...   *******************
**********************************************************
      Epoch    GPU_mem       loss  Instances       Size
    100/100         0G      2.092         12        224: 100%|██████████| 1/1 [00:00<00:00,  8.57it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 1/1 [00:00<00:00, 28.28it/s]
                   all      0.167      0.833

100 epochs completed in 0.007 hours.
Optimizer stripped from runs/classify/train2/weights/last.pt, 0.9MB
Optimizer stripped from runs/classify/train2/weights/best.pt, 0.9MB

Validating runs/classify/train2/weights/best.pt...
Ultralytics YOLOv8.1.19 🚀 Python-3.8.10 torch-2.0.1+cu117 CUDA:0 (NVIDIA A100-PCIE-40GB, 40536MiB)
YOLOv8-medium summary (fused): 60 layers, 396330 parameters, 0 gradients, 2.4 GFLOPs
train: /data1/is156025/fa125436/Confluence/Yolo/datasets/imagenet10/train... found 12 images in 10 classes ✅
val: /data1/is156025/fa125436/Confluence/Yolo/datasets/imagenet10/val... found 12 images in 10 classes ✅
test: None...
               classes   top1_acc   top5_acc: 100%|██████████| 1/1 [00:00<00:00, 23.90it/s]
                   all      0.167      0.917
Speed: 0.0ms preprocess, 1.8ms inference, 0.0ms loss, 0.0ms postprocess per image
Results saved to runs/classify/train2
Results saved to runs/classify/train2

0: 320x320 goldfish 0.29, ostrich 0.25, hammerhead 0.22, great_white_shark 0.10, tiger_shark 0.07, 12.1ms
Speed: 0.0ms preprocess, 12.1ms inference, 0.6ms postprocess per image at shape (1, 3, 320, 320)
Traceback (most recent call last):
  File "scores.py", line 21, in <module>
    flops = thop.profile(model, inputs=[im], verbose=False)
  File "/data1/is156025/fa125436/N2D2/env/lib/python3.8/site-packages/thop/profile.py", line 235, in profile
    total_ops, total_params, ret_dict = dfs_count(model)
  File "/data1/is156025/fa125436/N2D2/env/lib/python3.8/site-packages/thop/profile.py", line 228, in dfs_count
    m_ops, m_params, next_dict = dfs_count(m, prefix=prefix + "\t")
  File "/data1/is156025/fa125436/N2D2/env/lib/python3.8/site-packages/thop/profile.py", line 228, in dfs_count
    m_ops, m_params, next_dict = dfs_count(m, prefix=prefix + "\t")
  File "/data1/is156025/fa125436/N2D2/env/lib/python3.8/site-packages/thop/profile.py", line 228, in dfs_count
    m_ops, m_params, next_dict = dfs_count(m, prefix=prefix + "\t")
  [Previous line repeated 1 more time]
  File "/data1/is156025/fa125436/N2D2/env/lib/python3.8/site-packages/thop/profile.py", line 215, in dfs_count
    total_ops, total_params = module.total_ops.item(), 0
  File "/data1/is156025/fa125436/N2D2/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Conv2d' object has no attribute 'total_ops'
```
What is going wrong in my model?
The code I use is the following:

```
import torch
from ultralytics import YOLO
import thop

model = YOLO('yolov8-medium.yaml').load('runs/classify/train/weights/best.pt').to("cpu")
im = torch.empty((1, 3, 320, 320)).to("cpu")  # input image in BCHW format
flops = thop.profile(model, inputs=[im], verbose=False)
print(flops)
print(flops[0] / 1e9 * 2) # GFLOPS
```

**Comment by glenn-jocher** [comment]
@lesept777 hey there! It looks like you've run into an issue with calculating GFLOPs using `thop` on your modified YOLOv8 model. The error message suggests that `thop` couldn't find the `total_ops` attribute for the `Conv2d` layer. This usually happens because `thop` requires explicit support for custom layers or specific model structures to calculate operations correctly.

From your code snippet, it seems like your model might include layers or configurations that aren't automatically recognized by `thop`. Try defining custom hooks for your model's unique or modified layers. Here’s a quick example of how you can add a hook for a custom layer:

```python
import torch
from thop import profile
from thop.vision.basic_hooks import count_convNd

# Explicitly register Conv2d layer to use count_convNd
# Replace "Conv2d" with your custom layer class name, and ensure count_convNd is a suitable counting method.
custom_ops = {torch.nn.Conv2d: count_convNd} 

model = ...  # Your model loading logic
input = torch.randn(1, 3, 224, 224)

flops, params = profile(model, inputs=(input, ), custom_ops=custom_ops, verbose=False)
print(f"FLOPs: {flops}, Params: {params}")
```

This simple example registers Conv2d using `count_convNd`, which is already defined in `thop`. For custom layers not present in PyTorch or if the default counting methods don't reflect the operations accurately due to your modifications in YOLOv8, define your method following `count_convNd`'s pattern.

Remember, you'll have to review your model's architecture and possibly write your counting logic for layers that significantly deviate from common patterns. 

Hope this helps getting past the issue! If you have more detailed questions about specific layers or operations, feel free to reach out. Keep experimenting! 🚀

**Comment by lesept777** [comment]
Hi Glenn
Thanks for your answer
Unfortunately, I still get a similar error:

```
import torch
from ultralytics import YOLO
import thop
from thop import profile
from thop.vision.basic_hooks import count_convNd

# Explicitly register Conv2d layer to use count_convNd
# Replace "Conv2d" with your custom layer class name, and ensure count_convNd is a suitable counting method.
custom_ops = {torch.nn.Conv2d: count_convNd} 

# Load saved model:
model = YOLO('yolov8-medium.yaml').load('runs/classify/train/weights/best.pt').to("cpu")
input = torch.randn(1, 3, 320, 320)

flops, params = profile(model, inputs=(input, ), custom_ops=custom_ops, verbose=False)
print(f"FLOPs: {flops}, Params: {params}")

```
Here is the error message:

> Traceback (most recent call last):
>   File "scores.py", line 28, in <module>
>     flops, params = profile(model, inputs=(input, ), custom_ops=custom_ops, verbose=False)
>   File "/data1/is156025/fa125436/N2D2/env/lib/python3.8/site-packages/thop/profile.py", line 235, in profile
>     total_ops, total_params, ret_dict = dfs_count(model)
>   File "/data1/is156025/fa125436/N2D2/env/lib/python3.8/site-packages/thop/profile.py", line 228, in dfs_count
>     m_ops, m_params, next_dict = dfs_count(m, prefix=prefix + "\t")
>   File "/data1/is156025/fa125436/N2D2/env/lib/python3.8/site-packages/thop/profile.py", line 228, in dfs_count
>     m_ops, m_params, next_dict = dfs_count(m, prefix=prefix + "\t")
>   File "/data1/is156025/fa125436/N2D2/env/lib/python3.8/site-packages/thop/profile.py", line 228, in dfs_count
>     m_ops, m_params, next_dict = dfs_count(m, prefix=prefix + "\t")
>   [Previous line repeated 1 more time]
>   File "/data1/is156025/fa125436/N2D2/env/lib/python3.8/site-packages/thop/profile.py", line 215, in dfs_count
>     total_ops, total_params = module.total_ops.item(), 0
>   File "/data1/is156025/fa125436/N2D2/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
>     raise AttributeError("'{}' object has no attribute '{}'".format(
> AttributeError: 'Conv2d' object has no attribute 'total_ops'
>

**Comment by glenn-jocher** [comment]
@lesept777 hey there! 😊 It seems like the thop library is having trouble recognizing custom attributes in your YOLOv8 model. A common reason for this issue is not interacting correctly with YOLO's structure or missing out on registering some custom layers you might have in your model.

Although you've already registered `Conv2d` with `count_convNd`, the error suggests there might be more custom operations in YOLOv8 that thop doesn't automatically recognize. Since YOLOv8's architecture can be quite intricate, it's crucial to ensure _all_ custom layers or operations have corresponding count functions in the `custom_ops` dictionary.

Another approach is to debug by simplifying: start with a minimal version of your model and gradually add components until the error appears, to identify the problematic layer(s).

If you've recently modified the model architecture, double-check those areas to confirm they're correctly integrated with the profiling tool. Sometimes, slight discrepancies in layer implementation might also lead to such errors.

Hope this helps you move forward! Keep up the great work on your project, and don't hesitate to ask if you've got more questions. 🌟

**Comment by lesept777** [comment]
Thanks Glenn
Actually, I didn't taylor the model, I just removed some layers and change the size of the remaining ones to make is smaller:

```
# Ultralytics YOLO ??, AGPL-3.0 license
# YOLOv8-cls image classification model. For Usage examples see https://docs.ultralytics.com/tasks/classify

# Parameters
nc: 10 # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n-cls.yaml' will call yolov8-cls.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.30, 0.20, 1024]
  s: [0.33, 0.50, 1024]
  m: [0.67, 0.75, 1024]
  l: [1.00, 1.00, 1024]
  x: [1.00, 1.25, 1024]

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8  # Passer à 210 !
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 6, C2f, [512, True]]
#  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32
#  - [-1, 3, C2f, [1024, True]]

# YOLOv8.0n head
head:
  - [-1, 1, Classify, [nc]] # Classify

```
So I don't understand why `thop `is not working... I'll give it a look later.
But I have another question related to FLOPS.

As I'm training with the option `batch=-1`, it seems the model is trying various batch sizes and provides information, such as:

```
      Params      GFLOPs  GPU_mem (GB)  forward (ms) backward (ms)                   input                  output
      398554      0.6174         0.367         44.63         12.67        (1, 3, 320, 320)                 (1, 10)
      398554       1.235         0.348         4.173         11.56        (2, 3, 320, 320)                 (2, 10)
      398554       2.469         0.352          13.1         9.708        (4, 3, 320, 320)                 (4, 10)
      398554       4.939         0.350         6.128         9.442        (8, 3, 320, 320)                 (8, 10)
      398554       9.878         0.474         3.587         10.33       (16, 3, 320, 320)                (16, 10)
[34m[1mAutoBatch: [0mWARNING âš ï¸ CUDA anomaly detected, using default batch-size 16.

```
until it stops due to some error. But I think that the first GFLOPs provided here (0.6174) could be the one I'm looking for, as it is for a single input image, so similar to inference.
Am I correct?

If yes, how do you compute this number?

**Comment by glenn-jocher** [comment]
@lesept777 hi there! 😊

Regarding the `thop` issue, it's quite perplexing since your modifications seem straightforward. Sometimes, even simple changes can affect how external tools like `thop` analyze the model, but without diving deeper into your exact setup, it's hard to pinpoint the cause. I'd recommend double-checking if any of those layer changes or size adjustments might require custom handling when calculating FLOPs with `thop`.

On to your question about GFLOPs during training with `batch=-1`, you're indeed on the right track! The GFLOPs value given for a single input image (e.g., 0.6174 for a batch of 1) should closely represent the computational load during inference. This is because it measures the computational complexity for processing a single image through the network, which is essentially what happens during inference.

The GFLOPs are computed based on the model's layers, operations, and input sizes, accounting for the number of floating-point operations required to process an input image through the network. However, the specific formula or method to calculate this can vary based on the tools and context. For example, **Ultralytics** internally employs specialized methods to estimate these values accurately depending on the model's dynamic architecture.

If you seek to understand the precise computation of GFLOPs reported during your training, it involves summing up all the floating-point operations across every operation performed by the model layers. For `thop` or any similar tool, it hooks into these layers to count operations, which then get summed and scaled appropriately to report GFLOPs.

Hope this clears things up! Let me know if there's anything else you're curious about. Happy coding!

**Comment by Anser1** [comment]
> 谢谢 Glenn 实际上，我并没有对模型进行修改，我只是删除了一些图层并更改了剩余图层的大小以使其更小：
> 
> ```
> # Ultralytics YOLO ??, AGPL-3.0 license
> # YOLOv8-cls image classification model. For Usage examples see https://docs.ultralytics.com/tasks/classify
> 
> # Parameters
> nc: 10 # number of classes
> scales: # model compound scaling constants, i.e. 'model=yolov8n-cls.yaml' will call yolov8-cls.yaml with scale 'n'
>   # [depth, width, max_channels]
>   n: [0.30, 0.20, 1024]
>   s: [0.33, 0.50, 1024]
>   m: [0.67, 0.75, 1024]
>   l: [1.00, 1.00, 1024]
>   x: [1.00, 1.25, 1024]
> 
> # YOLOv8.0n backbone
> backbone:
>   # [from, repeats, module, args]
>   - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
>   - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
>   - [-1, 3, C2f, [128, True]]
>   - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8  # Passer à 210 !
>   - [-1, 6, C2f, [256, True]]
>   - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
>   - [-1, 6, C2f, [512, True]]
> #  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32
> #  - [-1, 3, C2f, [1024, True]]
> 
> # YOLOv8.0n head
> head:
>   - [-1, 1, Classify, [nc]] # Classify
> ```
> 
> 所以我不明白为什么不工作......我稍后会看一下。但我还有另一个与 FLOPS 相关的问题。`thop `
> 
> 当我使用 option 进行训练时，该模型似乎正在尝试各种批量大小并提供信息，例如：`batch=-1`
> 
> ```
>       Params      GFLOPs  GPU_mem (GB)  forward (ms) backward (ms)                   input                  output
>       398554      0.6174         0.367         44.63         12.67        (1, 3, 320, 320)                 (1, 10)
>       398554       1.235         0.348         4.173         11.56        (2, 3, 320, 320)                 (2, 10)
>       398554       2.469         0.352          13.1         9.708        (4, 3, 320, 320)                 (4, 10)
>       398554       4.939         0.350         6.128         9.442        (8, 3, 320, 320)                 (8, 10)
>       398554       9.878         0.474         3.587         10.33       (16, 3, 320, 320)                (16, 10)
> �[34m�[1mAutoBatch: �[0mWARNING âš ï¸� CUDA anomaly detected, using default batch-size 16.
> ```
> 
> 直到它因某些错误而停止。但我认为这里提供的第一个 GFLOP （0.6174） 可能是我正在寻找的，因为它适用于单个输入图像，因此类似于推理。我说得对吗？
> 
> 如果是，您如何计算这个数字？

**Comment by Anser1** [comment]
> 谢谢 Glenn 实际上，我并没有对模型进行修改，我只是删除了一些图层并更改了剩余图层的大小以使其更小：
> 
> ```
> # Ultralytics YOLO ??, AGPL-3.0 license
> # YOLOv8-cls image classification model. For Usage examples see https://docs.ultralytics.com/tasks/classify
> 
> # Parameters
> nc: 10 # number of classes
> scales: # model compound scaling constants, i.e. 'model=yolov8n-cls.yaml' will call yolov8-cls.yaml with scale 'n'
>   # [depth, width, max_channels]
>   n: [0.30, 0.20, 1024]
>   s: [0.33, 0.50, 1024]
>   m: [0.67, 0.75, 1024]
>   l: [1.00, 1.00, 1024]
>   x: [1.00, 1.25, 1024]
> 
> # YOLOv8.0n backbone
> backbone:
>   # [from, repeats, module, args]
>   - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
>   - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
>   - [-1, 3, C2f, [128, True]]
>   - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8  # Passer à 210 !
>   - [-1, 6, C2f, [256, True]]
>   - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
>   - [-1, 6, C2f, [512, True]]
> #  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32
> #  - [-1, 3, C2f, [1024, True]]
> 
> # YOLOv8.0n head
> head:
>   - [-1, 1, Classify, [nc]] # Classify
> ```
> 
> 所以我不明白为什么不工作......我稍后会看一下。但我还有另一个与 FLOPS 相关的问题。`thop `
> 
> 当我使用 option 进行训练时，该模型似乎正在尝试各种批量大小并提供信息，例如：`batch=-1`
> 
> ```
>       Params      GFLOPs  GPU_mem (GB)  forward (ms) backward (ms)                   input                  output
>       398554      0.6174         0.367         44.63         12.67        (1, 3, 320, 320)                 (1, 10)
>       398554       1.235         0.348         4.173         11.56        (2, 3, 320, 320)                 (2, 10)
>       398554       2.469         0.352          13.1         9.708        (4, 3, 320, 320)                 (4, 10)
>       398554       4.939         0.350         6.128         9.442        (8, 3, 320, 320)                 (8, 10)
>       398554       9.878         0.474         3.587         10.33       (16, 3, 320, 320)                (16, 10)
> �[34m�[1mAutoBatch: �[0mWARNING âš ï¸� CUDA anomaly detected, using default batch-size 16.
> ```
> 
> 直到它因某些错误而停止。但我认为这里提供的第一个 GFLOP （0.6174） 可能是我正在寻找的，因为它适用于单个输入图像，因此类似于推理。我说得对吗？
> 
> 如果是，您如何计算这个数字？

Hello, could you please tell me how to print GFLOPs for each layer？

**Comment by glenn-jocher** [comment]
For per-layer GFLOPs in YOLOv8, use `model.info(detailed=True)` which provides layer-wise computational metrics. The first GFLOPs value (0.6174) you see with `batch=-1` is indeed the single-image inference complexity, calculated by our internal profiling that accounts for input size and model architecture. This matches the implementation in `torch_utils.get_flops()` from our [documentation](https://docs.ultralytics.com/reference/utils/torch_utils/#ultralytics.utils.torch_utils.get_flops). 

For custom-modified models, ensure all layers are compatible with PyTorch's operator conventions for accurate profiling.
