### ISSUE TITLE
I needed to extract text from an image using the model I trained using yolov8n. and this error message is appearing 

### ISSUE THREAD

**Issue by Chamalb7** [ultralytics/ultralytics#3538]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

(yolov8_custom) C:\number recognition\160 imgsz>python text_extraction.py
Traceback (most recent call last):
  File "C:\number recognition\160 imgsz\text_extraction.py", line 8, in <module>
    from yolov8.models.experimental import YOLOv8
ModuleNotFoundError: No module named 'yolov8.models'

### Environment

Ultralytics 8.0.126
torch 2.0.1+cu117

### Minimal Reproducible Example

import cv2
import pytesseract
import torch
from PIL import Image
from torch.utils.data import DataLoader
from torchvision.transforms import ToTensor

from yolov8.models.experimental import YOLOv8
from yolov8.utils.datasets import LoadImages

model_path = "C:/number recognition/160 imgsz/number_recognition_160.pt"  # Replace with the actual path to your trained .pt model
image_path = "C:/number recognition/160 imgsz/test/cars464.jpg"

# Load the trained model
model = YOLOv8(model_path)

# Load the image
image = Image.open(image_path).convert("RGB")
image = ToTensor()(image).unsqueeze(0)

# Perform inference
results = model(image)

# Process the model output as per your specific model's requirements
extracted_text = process_output(results)

print(extracted_text)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
