### ISSUE TITLE
DDP processes not terminating when training stopped with CTRL-C

### ISSUE THREAD

**Issue by apiszcz** [ultralytics/ultralytics#3544]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

These process remain and do not release GPU resources when CTRL-C is used to stop the training.

There is a command similar to the following for each GPU in use for parallel training even though the primary shell stopped.

/usr/bin/python3 -u /tmp/Ultralytics/DDP/_temp_w9_kp98x139963334545959.py

### Environment

Ultralytics > .120
UBUNTU 20.04

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@apiszcz It appears that the subprocesses launched for Distributed Data Parallel (DDP) training are not terminating gracefully when the main process is interrupted with CTRL-C. This is likely due to the fact that the signal handler for `SIGINT` (which is sent by CTRL-C) in the child processes is not configured to terminate them properly.

I suggest you try the following steps as a workaround while we address this issue:

1. When you terminate the training with CTRL-C, note the PID (process ID) of the main process.

2. Use the following command to list the processes that are still running on the GPUs:
    ```sh
    nvidia-smi
    ```

3. Identify the PIDs of the python processes that are still running on the GPU, which should be the subprocesses launched by DDP.

4. Use the following command to kill the processes based on the PID:
    ```sh
    kill -9 <PID>
    ```
    Replace `<PID>` with the process ID you want to kill.

This should release the GPU resources used by the zombie processes.

In the meantime, I will look into adding signal handlers to the DDP subprocesses to ensure that they terminate gracefully when the main process is interrupted. This is indeed a bug, and I appreciate you bringing it to our attention. 

If you happen to find a more graceful solution or workaround, feel free to submit a PR. It's always great to have contributions from the community!

**Comment by only-yao** [comment]
非常好，这是一个可能的英文回复：

---

"I've encountered the same issue, while using the Docker image `ultralytics/ultralytics:latest`. Here are my GPU settings:

![image](https://github.com/ultralytics/ultralytics/assets/36235579/36b9a41c-06a1-42c7-a933-a5ec0f381316)


This is the script I'm running:

```
yolo train data=new_coco.yaml model=/data/d/models/yolov8/yolov8x.pt batch=8 imgsz=640 save_period=1 workers=1
```

Here are some of the logs:

```
Ultralytics YOLOv8.0.141 🚀 Python-3.10.11 torch-2.0.1 CUDA:0 (NVIDIA GeForce RTX 4090, 24564MiB)
engine/trainer: task=detect, mode=train, model=/data/d/models/yolov8/yolov8x.pt, data=new_coco.yaml, epochs=100, patience=50, batch=8, imgsz=640, save=True, save_period=1, cache=False, device=None, workers=1, project=None, name=None, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=/usr/src/ultralytics/runs/detect/train
Overriding model.yaml nc=80 with nc=12
```

During the first epoch of training, it gets stuck midway as shown below:

```
1/100 7.59G 0.9922 1.238 1.072 142 640: 67%|██████▋ | 5792/8612 [28:36<13:34, 3.46it/s]
```

And the GPU usage drops to 0%, but one of the CPU cores spikes to 100% usage. After identifying the PID with `nvidia-smi` and trying to kill it with `kill -9`, I end up with a zombie process, and the GPU resources remain in use. `nvidia-smi` also gets stuck and I can only reboot the system to resolve the issue."

**Comment by glenn-jocher** [comment]
@only-yao i'm sorry to hear you're having this issue. It appears that your training is getting stuck midway and causing a spike in CPU usage, eventually leading to a zombie process that doesn't release the GPU resources. This would indeed require a system reboot to fully clear.

When you interrupt the training with `kill` commands, it seems that not all DDP (Distributed Data Parallel) subprocesses are shutting down properly. These residual subprocesses can indeed turn into zombie processes that continue to consume GPU resources.

We're currently looking into better handling of these scenarios to ensure all subprocesses terminate gracefully when the main process is interrupted. 

In the meantime, as a practical workaround, the best course of action would indeed be a system reboot to clear any residual processes that are still consuming GPU resources. This would allow the GPU to be released and ensure any subsequent training runs don't encounter the same issue.

Your valuable contribution to report this issue helps us in finding a fix and improving the robustness of Ultralytics YOLOv8. We apologize for the inconveniences, and we appreciate your understanding and patience while we work to address this.

**Comment by only-yao** [comment]
@glenn-jocher Thank you for your response. I would like to know, on the 4090, which Docker image can be used to train YOLOv8x?

**Comment by glenn-jocher** [comment]
Hello @only-yao, I apologize for the issue you're facing with the `ultralytics/ultralytics:latest` Docker image. 

Currently, the Docker image you mentioned is the most up-to-date and feature-complete for training YOLOv8. If it's freezing during training, it could be due to various factors, including but not limited to, hardware limitations, software dependencies, or dataset-related issues.

In alignment with your report, we are actively investigating potential issues with the Docker image, particularly in relation to large batch training on powerful GPUs like the RTX 4090. Our aim is to improve the stability and efficiency of the training process.

In the meantime, while we dig deeper into resolving the problem, you could try lowering the batch size or image size, as the freezing might be due to memory over-allocation. You could also explore monitoring the system's resources at runtime, in case the system is running out of CPU or memory resources.

Your inputs provide crucial insights for us to debug and better the user experience. We acknowledge the inconvenience caused and thank you for your patience.
