### ISSUE TITLE
Killed in val

### ISSUE THREAD

**Issue by misi0202** [ultralytics/ultralytics#3562]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![截屏2023-07-06 03 01 58](https://github.com/ultralytics/ultralytics/assets/101965629/a216665a-6163-41b8-b36c-f74560ef1b9d)
![image](https://github.com/ultralytics/ultralytics/assets/101965629/c8ffdd3e-10c8-4d76-86ce-48d5fc40b59d)
I got killed in this code,it is not useful to reduce batch size,how to solve this problem ,plz!

**Comment by Laughing-q** [comment]
@misi0202 probably it's because your cpu is out of memory(which I think you might need to try lower batch-size). I just tried the same code on my machine and it works smoothly.
```python
from ultralytics import YOLO

model = YOLO("yolov8n.pt")
model.train(data="coco128.yaml", epochs=3)
model.val()
```

**Comment by ChrCoello** [comment]
Got the same error (Killed in the last validation step) using batch_size=-1. 
Changing the batch_size to a positive integer fixed the issue.

**Comment by glenn-jocher** [comment]
@ChrCoello it's great to hear that adjusting the `batch_size` to a positive integer resolved the issue with the last validation step being killed. When you use `batch_size=-1`, you are essentially allowing the system to attempt to use the maximum batch size that can fit in the memory, which often leads to situations where the system runs out of memory.

It's important to find a `batch_size` that your system's hardware can comfortably handle. If you're still experiencing issues, consider using an even smaller `batch_size` and ensure that no other memory-intensive processes are running on your system simultaneously.

As always, ensure that you have the latest version of the YOLOv8 repo and that your environment meets the necessary requirements to run the models efficiently.

Keep experimenting with the `batch_size` and ensure that your hardware resources match the demands of the training and validation processes. Remember that training deep learning models can be resource-intensive, so managing memory and computational resources effectively is key to a successful run.

If further problems persist, please provide additional details regarding the hardware specifications and the specific configuration and parameters you're using, so that we might be able to diagnose the issue more accurately.
