### ISSUE TITLE
YOLOv8 multiple GPU training issues

### ISSUE THREAD

**Issue by MaxTeselkin** [ultralytics/ultralytics#3569]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi! I am building a web app based on FastAPI and YOLOv8. I run my app using uvicorn, when I train model in usual mode using single GPU - everything works fine. But when I try to run my app on multiple GPU, I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/__main__.py", line 1, in <module>
    import uvicorn
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/__init__.py", line 1, in <module>
    from uvicorn.config import Config
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/config.py", line 1, in <module>
    import asyncio
  File "/usr/lib/python3.8/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/lib/python3.8/asyncio/base_events.py", line 18, in <module>
    import concurrent.futures
  File "/usr/lib/python3.8/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 7, in <module>
    import logging
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/logging.py", line 17, in <module>
    class ColourizedFormatter(logging.Formatter):
AttributeError: partially initialized module 'logging' has no attribute 'Formatter' (most likely due to a circular import)
```

I am trying to launch multiple GPU training using ultralytics python library, not CLI:

```
model.train(
        device="0,1",
        **additional_params,
    )
```

Why does circular import error occurs only when using multiple GPU mode?

And I also noticed that even through I pass only 2 of available 4 GPUs on my machine, DDP command looks like it tries to run on all 4 available GPUs:

```
DDP command: ['/usr/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '4', '--master_port', '46009', '/usr/local/lib/python3.8/dist-packages/uvicorn/__main__.py']
```

I tried running multiple GPU training without uvicorn using the following code:

```
from ultralytics import YOLO
import uvicorn.logging
 
 
additional_params = {
    'lr0':0.01,
    'lrf':0.01,
    'momentum':0.937,
    'weight_decay':0.0005,
    'warmup_epochs':3.0,
    'warmup_momentum':0.8,
    'warmup_bias_lr':0.1,
    'amp':True,
    'hsv_h':0.015,
    'hsv_s':0.7,
    'hsv_v':0.4,
    'degrees':0.0,
    'translate': 0.1,
}
 
 
model = YOLO("/my_path/yolov8n.pt")
model.train(
    data="/my_path/data_config.yaml",
    epochs=10,
    patience=1,
    batch=32,
    imgsz=640,
    save_period=1000,
    # device=device,
    device='0,1',
    workers=4,
    optimizer="AdamW",
    pretrained=True,
    **additional_params,
)
```

but got the following error:

```
Overriding model.yaml nc=80 with nc=2
[W NNPACK.cpp:79] Could not initialize NNPACK! Reason: Unsupported hardware.
[W NNPACK.cpp:79] Could not initialize NNPACK! Reason: Unsupported hardware.
Transferred 319/355 items from pretrained weights
DDP info: RANK 0, WORLD_SIZE 2, DEVICE cuda:0
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 158251 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -4) local_rank: 0 (pid: 158250) of binary: /home/iwatkot/fedor/supervisely/yolov8/venv/bin/python
Traceback (most recent call last):
  File "/home/iwatkot/.pyenv/versions/3.9.6/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/iwatkot/.pyenv/versions/3.9.6/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/my_dir/yolov8/venv/lib/python3.9/site-packages/torch/distributed/run.py", line 723, in <module>
    main()
  File "/home/my_dir/yolov8/venv/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/my_dir/yolov8/venv/lib/python3.9/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/home/my_dir/yolov8/venv/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/my_dir/yolov8/venv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/my_dir/yolov8/venv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
======================================================
/home/my_dir/yolov8/test.py FAILED
------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-06_16:03:40
  host      : ubnt-rig1
  rank      : 0 (local_rank: 0)
  exitcode  : -4 (pid: 158250)
  error_file: <N/A>
  traceback : Signal 4 (SIGILL) received by PID 158250
======================================================
Traceback (most recent call last):
  File "/home/my_dir/yolov8/test.py", line 23, in <module>
    model.train(
  File "/home/my_dir/yolov8/venv/lib/python3.9/site-packages/ultralytics/yolo/engine/model.py", line 371, in train
    self.trainer.train()
  File "/home/my_dir/yolov8/venv/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 188, in train
    raise e
  File "/home/my_dir/yolov8/venv/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 186, in train
    subprocess.run(cmd, check=True)
  File "/home/my_dir/.pyenv/versions/3.9.6/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/my_dir/yolov8/venv/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '36199', '/home/my_dir/yolov8/test.py']' returned non-zero exit status 1.
```

**Comment by glenn-jocher** [comment]
@MaxTeselkin hi there!

It seems that you're encountering a circular import error when trying to run your app on multiple GPUs using YOLOv8. This error occurs when there is a circular dependency between modules, which can lead to an attribute error.

To troubleshoot this issue, there are a couple of things you can try:

1. Check your code and ensure that you don't have any circular imports. Look for any imports that may be indirectly importing the same module that is causing the error.

2. Check if there are any conflicting versions of the `logging` module or any other relevant modules that could be causing the circular import. Upgrading or downgrading these modules might help resolve the issue.

Regarding the DDP command trying to run on all 4 available GPUs, even though you only pass 2 GPUs, it's possible that the library itself automatically detects and includes all available GPUs by default. You can check the library's documentation or contact the library's developer for further clarification on this behavior.

Additionally, it seems that you're encountering another error related to Distributed Data Parallel (DDP) training using the ultralytics library. This error could be due to unsupported hardware or other issues. To troubleshoot this, you can try running the multiple GPU training without uvicorn and check if the error persists. You can also explore other techniques for distributed training, such as torch.nn.DataParallel, to see if they work for your use case.

Hope this helps! Let me know if you have any further questions.

**Comment by glenn-jocher** [comment]
@MaxTeselkin your usage is incorrect, device type is not a string. See https://docs.ultralytics.com/modes/train/#usage-examples.

<img width="1075" alt="Screenshot 2023-07-07 at 19 25 29" src="https://github.com/ultralytics/ultralytics/assets/26833433/a5f3eb7c-7eb7-4692-915c-aaeade34b517">

**Comment by sssimpleboy** [comment]
> @MaxTeselkin your usage is incorrect, device type is not a string. See https://docs.ultralytics.com/modes/train/#usage-examples.
> 
> <img alt="Screenshot 2023-07-07 at 19 25 29" width="1075" src="https://user-images.githubusercontent.com/26833433/251812587-a5f3eb7c-7eb7-4692-915c-aaeade34b517.png">

I got the same error as  the questioner's like "ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 0 "

however,it shows that 
Ultralytics YOLOv8.0.58 🚀 Python-3.10.9 torch-2.0.0 CUDA:0 (NVIDIA GeForce RTX 3090, 24268MiB)
                                                     CUDA:1 (NVIDIA GeForce RTX 3090, 24268MiB)
which proves that The program has read in two CUDAs

**Comment by glenn-jocher** [comment]
@sssimpleboy the error message you're running into seems to be due to misconfiguration in how you're specifying the device type during training. This is not a string value but rather it expects a specific GPU specification format. Ensure that you specify the device type correctly when invoking the `train` function. It should be something like `device = [0, 1]` for multi-GPU training rather than a string like `device="0,1"`. This indicates that GPUs 0 and 1 should be used for training.

Regarding the `-7` exit code you're seeing, this is often related to exit due to a signal in subprocesses. This might be due to out-of-memory issues, or other system issues causing the subprocess running the training to be killed. Monitor your system resources carefully to ensure you're not exhausting available memory. Additionally, ensure that your PyTorch and CUDA versions are compatible and correctly installed.

In general, multi-GPU training in PyTorch needs to be carefully set up to work correctly, ensuring correct device setup, appropriate memory management, and compatible software versions.
