### ISSUE TITLE
Albumentations doesn't work in most recent version 

### ISSUE THREAD

**Issue by chokevin8** [ultralytics/ultralytics#3588]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

In my original code (version 8.0.113), whether I used the default augment.py folder or I altered it to include other available albumentations transforms, I was always able to validate that the augmentations for training/val actually worked in two ways: 1) When running training, it would give me a console output saying "albumentations: (list of augmentations)". 2) The train and val labels available as "train_batch0.png" once the model finishes processing the train and val data. 

However, when running the same exact code at most recent version 8.0.130, not only do I not see the console output list of albumentations, but I am also visually able to confirm that there were no augmentations done for the training/val images when looking at the "train_batch0.png" image. Note that this isn't the problem of just "luck" because the probabilities of the augmentations were low, I've tested it with p=1.0 on all of the augmentations and they still don't work (the training/val images don't get augmented). This is true for both yolov8x and yolov8x-seg detection/segmentation models. 

Note that this is using custom.yaml file and custom data, but I've essentially used the same exact code in two different environments, and it's strange to observe this behavior. If any of you guys aren't able to reproduce this, I'll try to recreate it with a minimal reproducible example. 

### Environment

YOLO: Ultralytics 8.0.130 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090 Ti, 24564MiB)
Python: 3.10.11

### Minimal Reproducible Example

model_seg = YOLO('yolov8x-seg.pt') # or yolov8.pt
model_seg.train(data=path/to/custom.yaml,
                    ,device = 0, batch = 16 ,epochs=300, imgsz = 512, verbose = True, deterministic = True,
                    name = 'random_name', cfg=path/to/custom/cfg.yaml)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@chokevin8 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. Albumentations works correctly if installed, i.e. 'yolo train' with blur 70 with p=0.5 used in latest package:

![train_batch0](https://github.com/ultralytics/ultralytics/assets/26833433/5d6b28a8-96d2-42c8-b2a7-0fe9d9fb4dca)

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by glenn-jocher** [comment]
<img width="1400" alt="Screenshot 2023-07-07 at 23 25 08" src="https://github.com/ultralytics/ultralytics/assets/26833433/69c27217-ea36-49ba-ae34-f6be9479e76c">

**Comment by sebos123** [comment]
@chokevin8 did you find a solution? I do have the same problem.

**Comment by glenn-jocher** [comment]
@sebos123 hello,

I'd first like to verify if you are using the most recent version of the YOLOv8 repository. This can be achieved through 'git pull' or by re-cloning the repository to ensure the issue has not already been addressed in recent updates.

In regards to the issue with albumentations not being applied, ensure that you have the albumentations package correctly installed. Without it, the YOLOv8 model will revert to default augmentations. The console output should confirm which augmentations are being applied during training.

If after checking these points the issue still persists, I would suggest providing a detailed description of your problem and opening a new issue on the YOLOv8 GitHub. It's essential to include configuration files, training commands, and any other pertinent information to allow us to replicate and address this issue effectively.

Thank you.
