### ISSUE TITLE
latest version train metric is bad than version 8.0.109

### ISSUE THREAD

**Issue by xbkaishui** [ultralytics/ultralytics#3594]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

when use new version (>=8.0.125) of yolo, the train result is poor than 8.0.109 . using the same dataset. some screentshot see belows

version 8.0.109  run result 
![results_good](https://github.com/ultralytics/ultralytics/assets/1477791/e4226a55-feed-4e4f-8fea-bc9669f70289)

version 8.0.125 run result 
![results](https://github.com/ultralytics/ultralytics/assets/1477791/d693f82c-36ea-4551-b407-44b2c2d354fa)

train command

```
 yolo train data=/opt/product/dataset/data.yaml model=/root/.cache/ckpts/yolov8x.pt epochs=15

```

### Environment

- Yolo ultralytics 8.0.131
- Ubuntu 22.04
- GPU 3090

### Additional

you can use these dataset to reproduce the bug 
https://universe.roboflow.com/xbkaishui/brake_disc_ocr

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@xbkaishui 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. I'm not able to reproduce any training problems in 8.0.131. If you can provide results on 8.0.109 and 8.0.131 using a common dataset like VOC please let us know, otherwise with just the information you've given we can't produce your same training results.

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by xbkaishui** [comment]
Hi, you can download my dataset with yolo format and try without further config.  let me try will coco128 test

**Comment by glenn-jocher** [comment]
Hi @xbkaishui 👋,

Thank you for sharing your dataset. To better understand the issue you are facing, it would be helpful if you could provide more information regarding the differences in training results between version 8.0.109 and 8.0.125. Specifically, could you share any specific metrics or evaluation results from your training runs?

Additionally, it would be great if you could try reproducing the issue using the common dataset COCO128, as this will help us isolate the problem further. By doing so, we can verify if the issue is specific to your dataset or if it affects general training performance.

Once we have more information, we will be better equipped to assist you. Feel free to reach out if you have any further questions or if there's anything else we can do to help.

Thank you!

**Comment by xbkaishui** [comment]
Hi @glenn-jocher 
I am back now. sorry for the later rely, I have tested coco128 with yolo 8.0.109 and 8.0.136, the train parameter is:
```
yolo detect train data=coco128.yaml model=yolov8x.yaml epochs=20
```

I also found that v136 version is bad, and old 109 version is better, you can see below screenshot 
8.0.109
![results](https://github.com/ultralytics/ultralytics/assets/1477791/07a9bcd5-9f7e-4279-a2f3-224327429c91)



8.0.136
![results——136](https://github.com/ultralytics/ultralytics/assets/1477791/6b87611b-0b1e-4830-874d-0fe52db93e9b)

**Comment by glenn-jocher** [comment]
Hi @xbkaishui,

Thank you for following up with the additional details using COCO128 dataset. 

It's important to remember that training is an inherently stochastic process. Differences in results can occur due to a variety of factors including slight variations in training environments or random initial conditions.

From your result screenshots, it seems like both versions have somewhat similar AP50 metrics but other metrics such as precision, recall and mAP differ. However, the differences aren't extreme and fall within typical variance for training runs.

At this point, there are no immediate indications of a specific issue with the newer YOLOv8 version. However, your feedback is valuable. We continuously work on improving the model's performance and your observations will be considered as we make future updates.

Please continue to keep us updated with your findings. Should any more issues arise or if there's anything else you'd like to share, don't hesitate to reach out. 

Thank you for engaging with the YOLOv8 community and helping us improve the model. We certainly appreciate your effort and time.

**Comment by xbkaishui** [comment]
the AP50 is differ to. for 109 version is about 0.5 , and latest version is 6*1E-5 almost to zero.

**Comment by glenn-jocher** [comment]
Hi @xbkaishui,

Thank you for further detailing the discrepancy you noticed in the AP50 metrics between the two versions. I understand your concern given the significant difference.

The AP50 metric is one of the key indicators used to measure the performance of our models. It represents the average precision at an Intersection over Union (IoU) threshold of 50%. 

Given the stochastic nature of training deep learning models, certain fluctuations in performance metrics between different training runs can be expected, particularly when different versions of the model are used. 

However, the difference in AP50 metrics that you've observed is significant, and it's something we take seriously. In order to investigate this further, we'll need to do additional internal testing with the condition that you've described.

We appreciate your patience as we work on this, and we're grateful for your contribution to the YOLOv8 community. Your involvement helps us enhance the model's performance and reliability for all users.

**Comment by xbkaishui** [comment]
ok,  thanks

**Comment by glenn-jocher** [comment]
You're welcome, @xbkaishui! We appreciate your understanding and patience as we investigate the issue you have highlighted. Your participation significantly contributes to the continuous improvement of YOLOv8. Please do not hesitate to share any additional findings or raise any further questions you may have in the future. Thanks again for your valuable feedback!
