### ISSUE TITLE
How to use yolov8 on my jetson nano ?

### ISSUE THREAD

**Issue by lkkkkkkl** [ultralytics/ultralytics#3596]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

My Cuda version is 10.0 , now I meet some problems when I  tried to upgrade Cuda to 10.1 . 
I pay about 8 seconds to detect one img (640x480) now, does anyone have some good ideas to help me use gpu to detect ?

**Comment by glenn-jocher** [comment]
@lkkkkkkl hi there!

To use YOLOv8 on your Jetson Nano, you can follow these steps:

1. Make sure you have a compatible version of CUDA installed. YOLOv8 requires CUDA 10.0 or higher. If your current CUDA version is 10.0, you should be good to go. There's no need to upgrade to 10.1 specifically for YOLOv8.

2. Install the `ultralytics` package in your Python environment by running `pip install ultralytics`.

3. You can then use the YOLOv8 model for detection by loading it in Python and calling the appropriate functions. You can find detailed examples and usage instructions in the [YOLOv8 documentation](https://docs.ultralytics.com).

Regarding your inference speed of 8 seconds per image, here are a few suggestions to improve it:

- Ensure that your Jetson Nano is running in performance mode to maximize GPU performance.

- Consider using TensorRT to optimize the YOLOv8 model for inference on the Jetson Nano. TensorRT is a deep learning inference optimizer and runtime library provided by NVIDIA.

- Experiment with different batch sizes during inference. Increasing the batch size can sometimes improve inference speed, although it may require more GPU memory.

- If you are using multiple images for inference, consider using asynchronous inference using CUDA streams to overlap computation and data transfer between the CPU and GPU.

I hope these suggestions help you improve the GPU performance for YOLOv8 on your Jetson Nano. Let me know if you have any further questions!

**Comment by spped2000** [comment]
jetson nano normally use cuda10.2
if you build python virtualenv  you need to locate
cp -r /usr/lib/python3.6/dist-packages/tensorrt* <path-to-site-packages>
then pip install onnx==1.9.0

https://github.com/ultralytics/yolov5/issues/11819#issuecomment-1625803400

**Comment by glenn-jocher** [comment]
@spped2000 apologies for the confusion around CUDA versions and thank you for the update on Jetson Nano typically using CUDA 10.2.

For YOLOv8, while I cannot offer direct code snippets or command line instructions here, I can provide you with guidance:

1. Set up your Python virtual environment (venv) for YOLOv8 as usual.

2. Since Jetson Nano uses CUDA 10.2, make sure your venv is correctly configured to use the CUDA libraries from the system. Typically, you'd need to ensure that the CUDA paths are set correctly in your environment variables so that any packages you install within your venv can detect and leverage CUDA.

3. As you've noted, copying the `tensorrt` libraries from the system's Python distribution to the venv's site-packages directory is often required because these libraries come pre-installed on Jetson Nano, and installing them via pip inside a venv may not provide the right configuration or version.

4. Installing a specific version of ONNX, like 1.9.0, might be necessary to ensure compatibility with the TensorRT version available on your Jetson Nano, as various versions of these libraries can have specific interdependencies.

5. After making sure these dependencies are correctly installed and set up, you should be able to import YOLOv8 within your Python environment and enjoy improved performance thanks to the optimized CUDA and TensorRT implementations.

If you continue to experience slow inference times, consider experimenting with different model sizes (like 'yolov8n', the smallest model, if you aren't already using it) to see if that fits your use-case for faster detections.

For detailed installation instructions, compatibility information, and further optimization tips, please refer to the Ultralytics documentation. Remember, keeping everything updated and ensuring compatibility between CUDA, TensorRT, and the YOLOv8 model is key to achieving optimal performance on hardware like the Jetson Nano.

Let me know if there's anything else I can help you with!

**Comment by jasonlytehouse** [comment]
You can use this [repo](https://github.com/jayfalls/jetson_nano_ubuntu20_docker/tree/main) I created which provides a docker image with python3.11 to run any ultralytics yolo models on Jetson Nano with torch gpu or tensorrt

You can expect about 60-70ms average end-to-end with yolov8n and yolov10n on the Jetson with Python3.11

**Comment by glenn-jocher** [comment]
Hi @jasonlytehouse,

Thank you for sharing your Docker repo for running Ultralytics YOLO models on the Jetson Nano! 🚀 It's great to see community contributions that help enhance the usability and performance of our models on various platforms.

For anyone looking to replicate your setup, using Docker can indeed simplify the process of managing dependencies and ensuring compatibility. The performance metrics you mentioned (60-70ms average end-to-end) are impressive and should be very encouraging for users aiming to deploy YOLOv8 and YOLOv10 models on the Jetson Nano.

If anyone encounters issues or has questions about using this setup, please ensure you are using the latest versions of `torch` and `ultralytics`. If problems persist, providing a minimum reproducible example will help us investigate further. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Thanks again for your contribution, and happy coding! 😊
