### ISSUE TITLE
The code for "Loading Tune Experiment Results from a Directory" is buggy and doesn't run

### ISSUE THREAD

**Issue by AndreaPi** [ultralytics/ultralytics#3630]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

There's a clear bug in the documentation: the code in this snippet doesn't work

https://github.com/ultralytics/ultralytics/blob/main/docs/usage/hyperparameter_tuning.md#loading-tune-experiment-results-from-a-directory

- NameError: name 'tune' is not defined. Did you mean: 'tuple'?
- NameError: name 'train_mnist' is not defined

### Environment

- ultralytics.__version__
'8.0.132'
- Ubuntu 18.04.6 LTS
- Python 3.10.9

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@AndreaPi hi there!

Thank you for bringing this issue to our attention. We apologize for any inconvenience caused.

Regarding the bug you encountered in the "Loading Tune Experiment Results from a Directory" code snippet, it seems that the code is missing an import statement for the `tune` module. To fix this, you can add the following line at the beginning of your code:

```
import optuna.integration.allennlp as tune
```

This import statement will ensure that the `tune` module is properly defined and can be used in your code.

Additionally, it appears that there is a typo in the code snippet where it references `train_mnist`. This should actually be `tune.run`.

We appreciate your feedback, as it helps us improve our documentation. If you have any further questions or need assistance with anything else related to YOLOv8, please don't hesitate to ask.

Thank you for your understanding and support!

Best regards,
Glenn Jocher

**Comment by glenn-jocher** [comment]
Hi @AndreaPi,

Thank you for providing the additional details and code snippet.

Regarding the module import, I apologize for the confusion. You are correct that the correct import statement should be `from ray import tune` instead of `import optuna.integration.allennlp as tune`. Thank you for pointing that out.

As for the error you are encountering, it seems that the issue lies in the mismatch between the `trainable` argument passed to the `Tuner.restore` method and the original `trainable` configuration used during the tuning process.

To fix this, you need to pass the correct `trainable` identifier. Based on the error message you shared, it appears that the expected identifier is `"_tune"` instead of `"run"`. So you need to modify the following line of your code:

```
restored_tuner = tune.Tuner.restore(experiment_path, trainable=tune.run)
```

to:

```
restored_tuner = tune.Tuner.restore(experiment_path, trainable="_tune")
```

After making this change, the code should be able to properly restore the tuner and retrieve the results from the specified experiment path.

Again, I apologize for the confusion caused by the incorrect initial import, and I appreciate your patience. If you have any further questions or encounter any other issues, please feel free to ask.

Best regards,
Glenn Jocher

**Comment by jokober** [comment]
I had the same problem and using trainable="_tune" solved it. Could you please update your documentation on your website?

**Comment by glenn-jocher** [comment]
@jokober hi there,

Thank you so much for confirming that the solution worked for you. We greatly appreciate your feedback. We're always working to maintain and improve the quality of our documents, and your input is invaluable. 

Regarding the update on the `trainable` value in our documentation, we recognize its importance for avoiding confusion in future usage. The team is notified about this, and we will surely address this issue in our upcoming documentation updates.

Again, thank you for taking the time to inform us. Your feedback helps ensure that our documentation is as accurate and helpful as possible. 

If you have further questions or concerns related to YOLOv8, don't hesitate to reach out to us. We're more than happy to assist!

Best regards,
Glenn Jocher
