### ISSUE TITLE
Hyperparameter Tuning with Ray Tune on a custom dataset doesn't work

### ISSUE THREAD

**Issue by AndreaPi** [ultralytics/ultralytics#3633]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

  In a folder `configs`, I have the following dataset  configuration file `mydataset.yaml`:

```
# Dataset
path: /data/dataset/
train: train/images
val: val/images
test: test/images

# Classes
names:
  0: A
  1: B
  2: C
```

I try to tune hyperparameters using Ray with this script `ray_tune.py`:

```
from ultralytics import YOLO

data_path = 'configs/mydataset.yaml'
n_epochs = 300
max_runs = 100
model = YOLO('yolov8n.pt')

# Run Ray Tune on the model
result_grid = model.tune(data=data_path,
                         epochs=n_epochs,
                         max_samples=max_runs)
```

However, all runs error out with the following error:

```
Failure # 1 (occurred at 2023-07-10_18-05-28)
ray::ImplicitFunc.train() (pid=141089, ip=172.19.0.2, actor_id=1f4f587b080822e7d9b91d1b01000000, repr=_tune)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/yolo/data/utils.py", line 195, in check_det_dataset
    data = check_file(dataset)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/yolo/utils/checks.py", line 303, in check_file
    raise FileNotFoundError(f"'{file}' does not exist")
FileNotFoundError: 'configs/mydataset.yaml' does not exist

The above exception was the direct cause of the following exception:

ray::ImplicitFunc.train() (pid=141089, ip=172.19.0.2, actor_id=1f4f587b080822e7d9b91d1b01000000, repr=_tune)
  File "/opt/conda/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 389, in train
    raise skipped from exception_cause(skipped)
  File "/opt/conda/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 336, in entrypoint
    return self._trainable_func(
  File "/opt/conda/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 653, in _trainable_func
    output = fn()
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/yolo/utils/tuner.py", line 83, in _tune
    model.train(**config)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 368, in train
    self.trainer = TASK_MAP[self.task][1](overrides=overrides, _callbacks=self.callbacks)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 127, in __init__
    raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
RuntimeError: Dataset 'configs/mydataset.yaml' error ❌ 'configs/mydataset.yaml' does not exist
```

This is clearly a HPT bug, because when I try to train a YOLOv8 model on the same dataset with `train_model.py`,

```
from ultralytics import YOLO

experiment = 'yolov8_nano_bs8_300e_imgsz1280'
data_path = 'configs/mydataset.yaml'
n_epochs = 300
bs = 8
n_workers = bs
gpu_id = 0
verbose = True
rng = 0
validate = True
patience = 0
image_size = 1280
project = '../../logs/'

model = YOLO('yolov8n.pt')

results = model.train(
    data=data_path,
    epochs=n_epochs,
    batch=bs,
    device=gpu_id,
    verbose=verbose,
    seed=rng,
    val=validate,
    project=project,
    name=experiment,
    workers=n_workers,
    patience=patience,
    imgsz=image_size
)
```

it works just fine.

### Environment

- Ultralytics YOLOv8.0.132 🚀 Python-3.10.9 torch-2.0.0 CUDA:0 (NVIDIA A100-SXM4-40GB, 40396MiB)
- OS: 18.04.6 LTS

### Minimal Reproducible Example

1. create a custom object detection dataset in a folder `/data/dataset`,  split in `train`, `val`, `test`, and 3 classes (though the number of classes is immaterial: the same bug would surely appear with a different number of classes)
2. create a folder `configs`, and copy `mydataset.yaml`, `ray_tune.py` and `train_model.py` there
3. run `python configs/ray_tune.py`
4. all runs will error out
5. now run `python configs/train_model.py`
6. the model will run just fine, proving that the issue is with the hyperparameter tuning and not with my paths

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@AndreaPi hi there,

Thank you for bringing this issue to our attention. We apologize for the inconvenience you've experienced.

Based on the error message you provided, it seems that the file path specified in `configs/mydataset.yaml` cannot be found during hyperparameter tuning with Ray Tune. However, the same dataset can be successfully trained using `train_model.py`. This suggests that it is indeed a bug related to hyperparameter tuning and not the paths themselves.

To further investigate this issue, we will need to gather more information. Could you please provide the following details:

1. The specific version of Ultralytics YOLOv8 and Ray Tune that you are using.
2. Confirm if you have verified that the `configs/mydataset.yaml` file exists in the specified location.
3. Any additional error messages or logs, if available.

With this information, we can investigate the issue further and provide an appropriate solution or workaround.

Thank you for your patience, and we look forward to resolving this issue for you.

**Comment by AndreaPi** [comment]
Hi @glenn-jocher, thanks for the quick answer!

1. Ultralytics YOLOv8.0.132 🚀 Python-3.10.9 torch-2.0.0 CUDA:0 (NVIDIA A100-SXM4-40GB, 40396MiB). ray.__version__
'2.5.1'
2. yes, that's the first thing I did :-) 


```
root@fd1e85d54a98:/workspace/...# ls configs/mydataset.yaml
configs/mydataset.yaml
```
3. I attach the full stdout [log_file.txt](https://github.com/ultralytics/ultralytics/files/12013084/log_file.txt) and stderr 
[err_file.txt](https://github.com/ultralytics/ultralytics/files/12013086/err_file.txt). Note that I reduced `max_samples` to 10, to get a faster result. I also doctored some path for confidentiality.

**Comment by glenn-jocher** [comment]
Hi @AndreaPi ,

Thank you for providing the additional information.

Based on the provided information, it appears that the `configs/mydataset.yaml` file exists in the correct location. 

The error message you shared from the logs indicates that the path to the dataset file cannot be found during the hyperparameter tuning process with Ray Tune. This issue seems to be specific to the hyperparameter tuning functionality in YOLOv8, as training the model directly using `train_model.py` was successful.

To further troubleshoot the issue, we recommend the following steps:

1. Double-check that the dataset file path in `configs/mydataset.yaml` is correct and accessible from the location where `ray_tune.py` is executed.

2. Verify that the dataset file is not being modified or moved during the execution of `ray_tune.py`. Changes to the file's location or content between the training script and the hyperparameter tuning script could lead to this error.

3. Check if there are any file system permissions issues that could prevent the hyperparameter tuning script from accessing the dataset file. Ensure that the user running the script has the necessary permissions to read the file.

If the issue persists after these steps, please let us know, and we'll be happy to assist you further in resolving this matter.

Thank you for your understanding and patience. We look forward to helping you get this issue resolved.

**Comment by syncsyncsync** [comment]
Hi @AndreaPi,
I ran into the same error as you, but in my case, when I set an absolute path for model.tune(data="/abs/path/for/configs/mydataset.yaml") instead of a relative path, it worked. 
As a workaround, I hope this works for you.

**Comment by AndreaPi** [comment]
Thank you very much, @syncsyncsync! In meantime, I completed my tests by doing HPT by hand - but if in the future I need to rerun HPT, I'll try your suggestion.

**Comment by glenn-jocher** [comment]
Hi @AndreaPi,

Thank you very much for your suggestion! In the meantime, I've completed my tests by manually performing Hyperparameter Tuning (HPT). However, if I need to rerun HPT in the future, I'll definitely try using an absolute path as you suggested. Your input is greatly appreciated!

**Comment by Dammy-Joe** [comment]
Hello
Has anyone been able to successfully use ray Tune for hyperparameter tuning? This is the error I keep getting:
**ModuleNotFoundError: Tuning hyperparameters requires Ray Tune. Install with: pip install "ray[tune]"**

And I've installed it as recommended in the Docs:

!pip install ultralytics
!pip install -U ultralytics "ray[tune]"
!pip install wandb
model = YOLO('yolov8n.pt')

data_path='configs/data.yaml'
result_grid = model.tune(data=data_path, use_ray=True)

How can I fix this please?

**Comment by glenn-jocher** [comment]
@Dammy-Joe hi there,

It appears that you're encountering a ModuleNotFoundError related to Ray Tune, even after following the recommended installation steps.

From the error message, the issue arises when you try to tune hyperparameters with Ray Tune, which suggests that the Ray Tune module isn't being found by Python even though you've installed it.

Here are some general debugging steps you could take:

1. Verify your installation: After running the installation commands, you can use Python's `pip show` command to confirm that Ray Tune is installed and check its version. Just type `pip show ray`.

2. Check your Python environment: If you're using multiple Python environments or virtual environments, make sure that you're installing Ray Tune in the correct environment and using that same environment to run your code.

3. Restart your Python kernel: If you're running your code in a Jupyter notebook, try restarting your kernel. Sometimes, newly installed packages don't get recognized until the kernel is restarted.

If you're still facing the issue after these steps, please provide any additional error messages or logs. We'll be happy to help you further.

**Comment by crazyn2** [comment]
Same issue. ray: 2.7 pytorch-lightning:2.0.8 datamodule can't find dataset file from the disk

**Comment by glenn-jocher** [comment]
@crazyn2 hello,

Thank you for reporting your issue. This appears to be a similar problem where Ray is unable to find the dataset file from the disk during the hyperparameter tuning process due to an environment setting. If Ray clears certain environment variables, as you suggested, it might affect both the file path resolution and the CUDA device configuration that were set in the Python script.

When it comes to the CUDA device issue you're experiencing, it might be caused by the specific interaction between how your script sets the precision for Tensor Cores and how Ray manages the CUDA device settings within the running script.

Given these complexities, we would recommend checking the following:

1. Verify that the dataset file path specified in the data module is correct and the file is accessible. Try using an absolute path instead of a relative path, if you haven't already, as this method has solved the issue for some users. 

2. Examine how your script sets the CUDA device precision. Consider resetting the precision setting within the tuning routine or immediately before it, if possible. 

If you continue to face these issues after trying these steps, please provide more information such as your system details, script elements related to these issues, specific error logs, etc. to better diagnose and address the problem. 

Thank you for your patience and cooperation.

**Comment by crazyn2** [comment]
Thanks for your immediate professional response. I changed the file path value to absolute system path and reset the precision set in train_func function in TorchTrainer class. It worked. But I hope that this bug could be fixed  in the time ahead。

**Comment by glenn-jocher** [comment]
Hi @crazyn2,

We're pleased to hear that adjusting the file path to an absolute system path and resetting the precision set in the TorchTrainer class's train_func function has helped resolve your issue. 

We certainly understand the inconveniences this issue may have caused and we appreciate your feedback. We're always striving to improve, and your suggestion will be taken into account. Rest assured, our team is continuously working on enhancing the usability and stability of YOLOv8, and we'll aim to address this issue in future updates.

Thank you for your contribution to improving YOLOv8 – we appreciate your patience and support.
