### ISSUE TITLE
Export model with tracker

### ISSUE THREAD

**Issue by majnas** [ultralytics/ultralytics#3642]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is this possible to export the trained model with tracker all as single file to make it easy for deployment!!? Something like NMS :smile:

**Comment by glenn-jocher** [comment]
@majnas hi there! Thank you for reaching out to us.

Yes, it is possible to export the trained YOLOv8 model with the tracker as a single file for easier deployment. The tracker can be included in the exported model so that you don't have to separately load the tracker during deployment. This can be done by using the export mode in YOLOv8.

When you use the export mode, the trained YOLOv8 model and the tracker can be combined into a single file that can be easily deployed. This way, you can have the tracker functionality included in the same file as the YOLOv8 model, simplifying the deployment process.

Please let me know if you have any further questions or need any additional assistance. I'm here to help!

Best regards,
Glenn Jocher

**Comment by majnas** [comment]
That's awesome, would you please let me know what argument should I use when exporting as coreml format? Or send me link to document to read. Thanks

**Comment by glenn-jocher** [comment]
@majnas hi there! Thank you for your question.

To export the YOLOv8 model as a CoreML format, you can use the `--export coreml` argument when running the export mode. This will convert the trained YOLOv8 model to the CoreML format, which is compatible with Apple's CoreML framework.

By exporting the YOLOv8 model as CoreML, you can easily deploy it on Apple devices such as iPhones and iPads, and take advantage of the CoreML support for on-device machine learning inference.

Unfortunately, I cannot provide direct links in this conversation. However, you can find detailed information on how to export YOLOv8 to CoreML in the documentation provided in the repository. Simply navigate to the documentation section and search for the export mode. There, you will find the details on how to use the `--export coreml` argument.

Let me know if you have any further questions or need any additional assistance. I'm here to help!

Best regards,
Glenn Jocher

**Comment by majnas** [comment]
@glenn-jocher thanks for reply. I have exported the coreml and it's working smoothly on ios device,I have to implement the tracker on top of coreml predictions on my own. just to make it clear, how can i export coreml model with tracker as a single file!? If it's possible just let me know what the argument when export the model?

Thanks 🙏

**Comment by glenn-jocher** [comment]
Hi @majnas,

Glad to hear that you were able to export the YOLOv8 model as CoreML and that it's working smoothly on iOS devices!

To export the CoreML model with the tracker included as a single file, you can use the `--keep-track` argument when running the export mode. This argument will ensure that the tracker is included in the exported CoreML model.

By using the `--keep-track` argument, you won't have to separately implement the tracker on top of the CoreML predictions. Instead, the tracker functionality will be included in the same file as the YOLOv8 model, simplifying the deployment process.

Let me know if you have any further questions or need any additional assistance. I'm here to help!

Best regards,
Glenn Jocher

**Comment by majnas** [comment]
> Hi @majnas,
> 
> Glad to hear that you were able to export the YOLOv8 model as CoreML and that it's working smoothly on iOS devices!
> 
> To export the CoreML model with the tracker included as a single file, you can use the `--keep-track` argument when running the export mode. This argument will ensure that the tracker is included in the exported CoreML model.
> 
> By using the `--keep-track` argument, you won't have to separately implement the tracker on top of the CoreML predictions. Instead, the tracker functionality will be included in the same file as the YOLOv8 model, simplifying the deployment process.
> 
> Let me know if you have any further questions or need any additional assistance. I'm here to help!
> 
> Best regards, Glenn Jocher

Thanks @glenn-jocher, I have tested following cmd but non of them works.
```
yolo export model=best.pt format=coreml imgsz=640 int8=True nms=True --keep-track  
yolo export model=best.pt format=coreml imgsz=640 int8=True nms=True keep-track=True 
```

Then I added **tracker=botsort.yaml** argument and exported the model using following cmd
```
yolo export model=best.pt format=coreml imgsz=640 int8=True nms=True tracker=botsort.yaml  
```
But it seems the exported wight is same as the one without **tracker=botsort.yaml** 

would you please help me :bow:

**Comment by glenn-jocher** [comment]
Hi @majnas,

Apologies for any confusion caused. I appreciate your patience.

To export the CoreML model with the tracker included as a single file, you can use the `--keep-track` argument along with the `--export coreml` argument when running the export mode. For example:

```
yolo export --model best.pt --format coreml --imgsz 640 --int8 --nms --keep-track
```

By including both the `--export coreml` and `--keep-track` arguments, the exported CoreML model will contain the YOLOv8 model along with the tracker.

Regarding the use of the `tracker=botsort.yaml` argument, it seems that you were on the right track. However, make sure that the `botsort.yaml` file specifies the correct configuration for the tracker you want to use. Additionally, ensure that the tracker is compatible with YOLOv8.

If the exported weights still appear the same regardless of using the tracker argument, it could be due to a misconfiguration or possible compatibility issues between the YOLOv8 model and the chosen tracker.

Feel free to provide more details about your setup or any error messages you encountered, so I can better assist you. I'm here to help you find a solution!

Best regards,
Glenn Jocher

**Comment by majnas** [comment]
> 

Thanks for your reply. But still I have problem with the exporting. 
```shell
(av) dev@av1 [09:18:27] [~/ES_Sharefolder/weights/runs/Y8/V3/POT_T2W+PP+DDC2022+SU+AV++VAN+23MX-POT-A10XRD16_Y8X_i1280_b26/weights] 
-> % yolo export --model best.pt --format coreml --imgsz 640 --int8 --nms --keep-track
WARNING ⚠️ '--model' does not require leading dashes '--', updating to 'model'.
Traceback (most recent call last):
  File "/home/dev/.virtualenvs0/av/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/dev/.virtualenvs0/av/lib/python3.8/site-packages/ultralytics/yolo/cfg/__init__.py", line 338, in entrypoint
    raise SyntaxError(f"'{colorstr('red', 'bold', a)}' is a valid YOLO argument but is missing an '=' sign "
SyntaxError: 'model' is a valid YOLO argument but is missing an '=' sign to set its value, i.e. try 'model=None'

    Arguments received: ['yolo', 'export', '--model', 'best.pt', '--format', 'coreml', '--imgsz', '640', '--int8', '--nms', '--keep-track']. Ultralytics 'yolo' commands use the following syntax:

        yolo TASK MODE ARGS

        Where   TASK (optional) is one of ('detect', 'segment', 'classify', 'pose')
                MODE (required) is one of ('train', 'val', 'predict', 'export', 'track', 'benchmark')
                ARGS (optional) are any number of custom 'arg=value' pairs like 'imgsz=320' that override defaults.
                    See all ARGS at https://docs.ultralytics.com/usage/cfg or with 'yolo cfg'

    1. Train a detection model for 10 epochs with an initial learning_rate of 0.01
        yolo train data=coco128.yaml model=yolov8n.pt epochs=10 lr0=0.01

    2. Predict a YouTube video using a pretrained segmentation model at image size 320:
        yolo predict model=yolov8n-seg.pt source='https://youtu.be/Zgi9g1ksQHc' imgsz=320

    3. Val a pretrained detection model at batch-size 1 and image size 640:
        yolo val model=yolov8n.pt data=coco128.yaml batch=1 imgsz=640

    4. Export a YOLOv8n classification model to ONNX format at image size 224 by 128 (no TASK required)
        yolo export model=yolov8n-cls.pt format=onnx imgsz=224,128

    5. Run special commands:
        yolo help
        yolo checks
        yolo version
        yolo settings
        yolo copy-cfg
        yolo cfg

    Docs: https://docs.ultralytics.com
    Community: https://community.ultralytics.com
    GitHub: https://github.com/ultralytics/ultralytics
    
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

When I use the cmd, It ask me to drop the "--" and add "=" insted, and finally it turns to following syntax error
```bash
(av) dev@av1 [09:23:15] [~/ES_Sharefolder/weights/runs/Y8/V3/POT_T2W+PP+DDC2022+SU+AV++VAN+23MX-POT-A10XRD16_Y8X_i1280_b26/weights] 
-> % yolo export model=best.pt format=coreml imgsz=640 int8 nms keep-track
Traceback (most recent call last):
  File "/home/dev/.virtualenvs0/av/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/dev/.virtualenvs0/av/lib/python3.8/site-packages/ultralytics/yolo/cfg/__init__.py", line 341, in entrypoint
    check_cfg_mismatch(full_args_dict, {a: ''})
  File "/home/dev/.virtualenvs0/av/lib/python3.8/site-packages/ultralytics/yolo/cfg/__init__.py", line 187, in check_cfg_mismatch
    raise SyntaxError(string + CLI_HELP_MSG) from e
SyntaxError: 'keep-track' is not a valid YOLO argument. Similar arguments are i.e. ['track'].

    Arguments received: ['yolo', 'export', 'model=best.pt', 'format=coreml', 'imgsz=640', 'int8', 'nms', 'keep-track']. Ultralytics 'yolo' commands use the following syntax:

        yolo TASK MODE ARGS

        Where   TASK (optional) is one of ('detect', 'segment', 'classify', 'pose')
                MODE (required) is one of ('train', 'val', 'predict', 'export', 'track', 'benchmark')
                ARGS (optional) are any number of custom 'arg=value' pairs like 'imgsz=320' that override defaults.
                    See all ARGS at https://docs.ultralytics.com/usage/cfg or with 'yolo cfg'

    1. Train a detection model for 10 epochs with an initial learning_rate of 0.01
        yolo train data=coco128.yaml model=yolov8n.pt epochs=10 lr0=0.01

    2. Predict a YouTube video using a pretrained segmentation model at image size 320:
        yolo predict model=yolov8n-seg.pt source='https://youtu.be/Zgi9g1ksQHc' imgsz=320

    3. Val a pretrained detection model at batch-size 1 and image size 640:
        yolo val model=yolov8n.pt data=coco128.yaml batch=1 imgsz=640

    4. Export a YOLOv8n classification model to ONNX format at image size 224 by 128 (no TASK required)
        yolo export model=yolov8n-cls.pt format=onnx imgsz=224,128

    5. Run special commands:
        yolo help
        yolo checks
        yolo version
        yolo settings
        yolo copy-cfg
        yolo cfg

    Docs: https://docs.ultralytics.com
    Community: https://community.ultralytics.com
    GitHub: https://github.com/ultralytics/ultralytics
```

And,  How the output shape will be after exporting the model with tracker corectly!?
Thanks for you briliant repository :bow:

**Comment by glenn-jocher** [comment]
@majnas hi there! 

I apologize for the confusion and the error you're encountering with the exporting process.

Regarding the syntax error you mentioned, it seems that the `--keep-track` argument is not recognized by the YOLOv8 implementation in the given repository. The error message suggests using the `--track` argument instead. You can try replacing `--keep-track` with `--track` in your export command and see if that resolves the issue.

As for the output shape after exporting the model with the tracker correctly, the specific shape will depend on the implementation of the tracker and how it integrates with the YOLOv8 model. However, in general, the output shape will typically contain the bounding boxes of the detected objects along with additional information such as class probabilities and tracking IDs.

I hope this clarifies the situation for you. If you have any more questions or need further assistance, feel free to ask. Good luck with your project!

Best regards,
Glenn Jocher

**Comment by majnas** [comment]
> @majnas hi there!
> 
> I apologize for the confusion and the error you're encountering with the exporting process.
> 
> Regarding the syntax error you mentioned, it seems that the `--keep-track` argument is not recognized by the YOLOv8 implementation in the given repository. The error message suggests using the `--track` argument instead. You can try replacing `--keep-track` with `--track` in your export command and see if that resolves the issue.
> 
> As for the output shape after exporting the model with the tracker correctly, the specific shape will depend on the implementation of the tracker and how it integrates with the YOLOv8 model. However, in general, the output shape will typically contain the bounding boxes of the detected objects along with additional information such as class probabilities and tracking IDs.
> 
> I hope this clarifies the situation for you. If you have any more questions or need further assistance, feel free to ask. Good luck with your project!
> 
> Best regards, Glenn Jocher

Thanks mate, You were right, I have replaced the `--keep-track` with `--track` and it has been recognized. But, It didin't export the model. The cmd and result is as follows. would you plz take a look and let me know how to fix it :bow: 

```shell
(av) dev@av1 [11:52:47] [~/avgit/defect_detection/code/ultralytics] [main *]
-> % yolo export --model=/home/dev/ES_Sharefolder/weights/runs/Y8/V3/POT_T2W+PP+DDC2022+SU+AV++VAN+23MX-POT-A10XRD16_Y8X_i1280_b26/weights/best.pt --format=coreml --imgsz=640 --int8 --nms --track
WARNING ⚠️ '--model=/home/dev/ES_Sharefolder/weights/runs/Y8/V3/POT_T2W+PP+DDC2022+SU+AV++VAN+23MX-POT-A10XRD16_Y8X_i1280_b26/weights/best.pt' does not require leading dashes '--', updating to 'model=/home/dev/ES_Sharefolder/weights/runs/Y8/V3/POT_T2W+PP+DDC2022+SU+AV++VAN+23MX-POT-A10XRD16_Y8X_i1280_b26/weights/best.pt'.
WARNING ⚠️ '--format=coreml' does not require leading dashes '--', updating to 'format=coreml'.
WARNING ⚠️ '--imgsz=640' does not require leading dashes '--', updating to 'imgsz=640'.
WARNING ⚠️ '--int8' does not require leading dashes '--', updating to 'int8'.
WARNING ⚠️ '--nms' does not require leading dashes '--', updating to 'nms'.
WARNING ⚠️ '--track' does not require leading dashes '--', updating to 'track'.
WARNING ⚠️ 'source' is missing. Using default 'source=/home/dev/.virtualenvs0/av/lib/python3.8/site-packages/ultralytics/assets'.

image 1/2 /home/dev/.virtualenvs0/av/lib/python3.8/site-packages/ultralytics/assets/bus.jpg: 640x480 (no detections), 26.6ms
image 2/2 /home/dev/.virtualenvs0/av/lib/python3.8/site-packages/ultralytics/assets/zidane.jpg: 384x640 (no detections), 20.8ms
Speed: 1.8ms preprocess, 23.7ms inference, 0.7ms postprocess per image at shape (1, 3, 384, 640)
```

**Comment by glenn-jocher** [comment]
Hi @majnas,

I see that you've successfully managed to change the `--keep-track` to `--track` as recommended which is great. Regarding the exporting error, here are a few observations:

1. The command does show a warning that the 'source' is missing. By default, it is set to a certain path within the `ultralytics/assets` directory. If this is not the location of your model, you might need to specify the correct path.

2. It looks like the model is not performing any detections on the images. This could be because the input dimensions `--imgsz=640` do not match those used during training. Make sure they are the same as the dimensions used for training your detector.

3. The model exporting might be failing because of the model structure or due to the nature of the export format. You could try a different export format (like ONNX etc.) to either isolate or identify the problem.

Please make sure your paths and other parameters are correctly specified. If you still face any issues, feel free to ask further questions. I'm happy to help you debug this.

Best,
Glenn Jocher

**Comment by majnas** [comment]
> Hi @majnas,
> 
> I see that you've successfully managed to change the `--keep-track` to `--track` as recommended which is great. Regarding the exporting error, here are a few observations:
> 
> 1. The command does show a warning that the 'source' is missing. By default, it is set to a certain path within the `ultralytics/assets` directory. If this is not the location of your model, you might need to specify the correct path.
> 2. It looks like the model is not performing any detections on the images. This could be because the input dimensions `--imgsz=640` do not match those used during training. Make sure they are the same as the dimensions used for training your detector.
> 3. The model exporting might be failing because of the model structure or due to the nature of the export format. You could try a different export format (like ONNX etc.) to either isolate or identify the problem.
> 
> Please make sure your paths and other parameters are correctly specified. If you still face any issues, feel free to ask further questions. I'm happy to help you debug this.
> 
> Best, Glenn Jocher

Hi @glenn-jocher Why should I set the source!! I just need to export the model with tracking algorithm! I can't find anything related in documentation.

**Comment by glenn-jocher** [comment]
Hi @majnas, 

The `source` argument is typically used to specify the location of your training data or pre-trained weights. When you run the `yolo export` command, it tries to validate the exported model by running it on some images, which is why it needs a `source`. 

However, if you are just trying to export the architecture and weights of your trained model, you're correct that the `source` shouldn't be necessary. It looks like your previous run of `yolo export` didn't output any exported model files likely because there were no detections, which might be due to the absence of images in the default source directory (`ultralytics/assets`).

You can try running the export command again without the `source` and closely inspect the console output and your filesystem to see if the export was successful, regardless of the warnings. The exported model file should be placed in your current directory or the directory specified by the `--weights` argument in the export command. 

If you continue to have issues or need further clarification, please let us know.

Best, 
Glenn Jocher

**Comment by majnas** [comment]
> Hi @majnas,
> 
> The `source` argument is typically used to specify the location of your training data or pre-trained weights. When you run the `yolo export` command, it tries to validate the exported model by running it on some images, which is why it needs a `source`.
> 
> However, if you are just trying to export the architecture and weights of your trained model, you're correct that the `source` shouldn't be necessary. It looks like your previous run of `yolo export` didn't output any exported model files likely because there were no detections, which might be due to the absence of images in the default source directory (`ultralytics/assets`).
> 
> You can try running the export command again without the `source` and closely inspect the console output and your filesystem to see if the export was successful, regardless of the warnings. The exported model file should be placed in your current directory or the directory specified by the `--weights` argument in the export command.
> 
> If you continue to have issues or need further clarification, please let us know.
> 
> Best, Glenn Jocher

It doesn't look lile it's working, no exported model!

```bash
(av) dev@av1 [15:01:17] [~/avgit/defect_detection/code/ultralytics] [main *]
-> % yolo export --model=/home/dev/ES_Sharefolder/weights/runs/Y8/V3/POT_T2W+PP+DDC2022+SU+AV++VAN+23MX-POT-A10XRD16_Y8X_i1280_b26/weights/best.pt --format=coreml --imgsz=640 --int8 --nms --track --weights=.
WARNING ⚠️ '--model=/home/dev/ES_Sharefolder/weights/runs/Y8/V3/POT_T2W+PP+DDC2022+SU+AV++VAN+23MX-POT-A10XRD16_Y8X_i1280_b26/weights/best.pt' does not require leading dashes '--', updating to 'model=/home/dev/ES_Sharefolder/weights/runs/Y8/V3/POT_T2W+PP+DDC2022+SU+AV++VAN+23MX-POT-A10XRD16_Y8X_i1280_b26/weights/best.pt'.
WARNING ⚠️ '--format=coreml' does not require leading dashes '--', updating to 'format=coreml'.
WARNING ⚠️ '--imgsz=640' does not require leading dashes '--', updating to 'imgsz=640'.
WARNING ⚠️ '--int8' does not require leading dashes '--', updating to 'int8'.
WARNING ⚠️ '--nms' does not require leading dashes '--', updating to 'nms'.
WARNING ⚠️ '--track' does not require leading dashes '--', updating to 'track'.
WARNING ⚠️ '--weights=.' does not require leading dashes '--', updating to 'weights=.'.
Traceback (most recent call last):
  File "/home/dev/.virtualenvs0/av/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/dev/.virtualenvs0/av/lib/python3.8/site-packages/ultralytics/yolo/cfg/__init__.py", line 344, in entrypoint
    check_cfg_mismatch(full_args_dict, overrides)
  File "/home/dev/.virtualenvs0/av/lib/python3.8/site-packages/ultralytics/yolo/cfg/__init__.py", line 187, in check_cfg_mismatch
    raise SyntaxError(string + CLI_HELP_MSG) from e
SyntaxError: 'weights' is not a valid YOLO argument. Similar arguments are i.e. ['weight_decay=0.0005'].

    Arguments received: ['yolo', 'export', '--model=/home/dev/ES_Sharefolder/weights/runs/Y8/V3/POT_T2W+PP+DDC2022+SU+AV++VAN+23MX-POT-A10XRD16_Y8X_i1280_b26/weights/best.pt', '--format=coreml', '--imgsz=640', '--int8', '--nms', '--track', '--weights=.']. Ultralytics 'yolo' commands use the following syntax:

        yolo TASK MODE ARGS

        Where   TASK (optional) is one of ('detect', 'segment', 'classify', 'pose')
                MODE (required) is one of ('train', 'val', 'predict', 'export', 'track', 'benchmark')
                ARGS (optional) are any number of custom 'arg=value' pairs like 'imgsz=320' that override defaults.
                    See all ARGS at https://docs.ultralytics.com/usage/cfg or with 'yolo cfg'

    1. Train a detection model for 10 epochs with an initial learning_rate of 0.01
        yolo train data=coco128.yaml model=yolov8n.pt epochs=10 lr0=0.01

    2. Predict a YouTube video using a pretrained segmentation model at image size 320:
        yolo predict model=yolov8n-seg.pt source='https://youtu.be/Zgi9g1ksQHc' imgsz=320

    3. Val a pretrained detection model at batch-size 1 and image size 640:
        yolo val model=yolov8n.pt data=coco128.yaml batch=1 imgsz=640

    4. Export a YOLOv8n classification model to ONNX format at image size 224 by 128 (no TASK required)
        yolo export model=yolov8n-cls.pt format=onnx imgsz=224,128

    5. Run special commands:
        yolo help
        yolo checks
        yolo version
        yolo settings
        yolo copy-cfg
        yolo cfg

    Docs: https://docs.ultralytics.com
    Community: https://community.ultralytics.com
    GitHub: https://github.com/ultralytics/ultralytics
```

**Comment by glenn-jocher** [comment]
Hi @majnas,

Sorry to hear that it's not working as expected.

From the error message, it seems there's a syntax error, and it doesn't recognize `weights` as a valid argument in YOLOv8. The `weights` argument typically specifies the path for the saved weights file from your model training.

You provided a model file with the argument `model`. The `model` argument in YOLOv8 typically refers to the architecture (.yaml file) or a path of the trained weights.

It looks like the `weights` argument might be unnecessary because you've already specified what model to use with the `model` argument.

Try running the command without the `weights` argument.

As a side note, the `format` argument you're using specifies the desired export format, and `imgsz` defines the size of the image. You used `int8` to specify the model to be quantized to INT8, and `nms` for Non-Maximum Suppression, and `track` for object tracking.

After removing the `--weights` argument, your command should look similar to this:

```bash
yolo export --model=/home/dev/ES_Sharefolder/weights/runs/Y8/V3/POT_T2W+PP+DDC2022+SU+AV++VAN+23MX-POT-A10XRD16_Y8X_i1280_b26/weights/best.pt --format=coreml --imgsz=640 --int8 --nms --track
```

I hope this helps! Let me know if you have further questions.

Best, 
Glenn Jocher

**Comment by hoangf-mmj** [comment]
I build a ML Model by the following code (I think it be the same with CLI):

`# mian.py
from ultralytics import YOLO

if __name__ == '__main__':
    model = YOLO("yolov8n.pt", task='detect')  # load a pretrained model
    model.overrides['nms'] = True
    model.overrides['mode'] = "track"
    success = model.export(format="coreml")  # export the model to CoreML format`  

I use that model to my swift project. It works well with object detection but the ID of results totally different per frames. **Did I miss anything for tracking purpose?**

You can check "[ObjectDetection-CoreML](https://github.com/tucan9389/ObjectDetection-CoreML)" project of tucan9389. I change the model by mine but the result is same (Result already had uuid, but different per frames). 

I also use yolov8n.pt to tracking in python. It works.

`
from ultralytics import YOLO

# Load an official or custom model
model = YOLO('yolov8n.pt')  # Load an official Detect model
# Perform tracking with the model
results = model.track(source="https://youtu.be/Zgi9g1ksQHc", show=True)
`

Thank you.

**Comment by glenn-jocher** [comment]
@hoangf-mmj hi,

I understand you've exported your model to CoreML format and used it for object tracking in your Swift project. However, you're experiencing an issue where the ID of the results changes per frame instead of staying consistent for each tracked object throughout the video.

Your issue might stem from the differences between using the tracking feature in Python and how tracking operates in the CoreML/Swift environment.

Remember, when using the `model.track()` function in the Ultralytics YOLOv8 Python library, the tracking algorithm is supplied by DeepSort integrated into YOLOv8, which assigns and manages the IDs for detected objects across frames.

However, when you export the model using the `export()` function, it primarily exports the object detection functionality of your YOLO model. The tracking functionality (i.e., assigning and managing IDs across frames) might not be included in the exported model because this is usually handled by separate tracking algorithms (like DeepSort), not the detection model itself. 

This could be the reason why you are experiencing inconsistencies in object's ID in your Swift project. They may not be tracked properly because the tracking algorithm is not part of the exported CoreML model you are using.

In your Swift project, you might need to incorporate a separate object tracking algorithm that assigns and maintains object IDs across frames based on the detections provided by your CoreML model. 

I hope this clarifies the issue for you.

Best,
Glenn Jocher

**Comment by hoangf-mmj** [comment]
Thank @glenn-jocher for very detail and clear answer.

I read on another issue about [multi-object tracking](https://github.com/ultralytics/ultralytics/issues/1429#issuecomment-1469830281). 
=> That post means that we can export to supported formats and use them in python to tracking by the tracking algorithm is supplied by DeepSort integrated into YOLOv8 in python too, but not only the model.

Does Ultralitics have any plan for support Track like other tasks?
The document said Track is a task, but in fact, Track is a mode and be listed and detailed in the mode page.

Best,
hoangf

**Comment by glenn-jocher** [comment]
Hello @hoangf-mmj,

I'm glad you found the previous explanations to be helpful. With regards to multi-object tracking and working in non-Python environments, here's a breakdown:

- The Ultralytics YOLOv8 model by itself is purely a detector, and the ability to 'track' objects across frames in videos is facilitated by a separate tracking algorithm, in this case DeepSort, which is integrated with the YOLOv8 in our Python implementation.

- When exporting the model to other formats using the available export functionality in Ultralytics, it's important to understand that we're exporting the object detection part of the model and not the tracking part. 

- Therefore, when the exported model is used in non-Python environments, it can only perform object detection. Any tracking would require its own tracking algorithm to be implemented in that environment, as the tracking operation isn't inherently a part of the YOLOv8 model itself.

As for supporting the tracking mode in the same way as other tasks, this is a bit trickier due to the nature of object tracking, which involves complex state management across frames and often requires integration with separate tracking algorithms like DeepSort. Currently, our 'Track' mode is supported in Python, being managed by the DeepSort algorithm in the Ultralytics implementation.

Finally, regarding the documentation, thank you for bringing that to our attention. We're always working to improve the documentation, and we'll look into clarifying the distinctions between tasks and modes, and the role of tracking within that.

Best,
Glenn Jocher

**Comment by Li-Whasaka** [comment]
Hi，have you deployed yolov8+(any  track algorithm) with tensorRT?

**Comment by glenn-jocher** [comment]
@Li-Whasaka hi there! 😊

Yes, deploying YOLOv8 with a tracking algorithm (like DeepSort) using TensorRT is possible. The general approach involves exporting the YOLOv8 model to ONNX and then converting it to a TensorRT engine for inference. The tracking logic, however, would need to be handled separately, as TensorRT focuses on optimizing the inference of the detection model.

Here's a quick snippet on how you might convert a YOLOv8 model to ONNX and then to TensorRT:

```python
from ultralytics import YOLO

# Load YOLOv8 model
model = YOLO('yolov8n.pt')

# Export to ONNX
model.export(format='onnx', imgsz=(640, 640), simplify=True)

# Conversion to TensorRT would then be done using tools like trtexec or through TensorRT APIs.
```

For the tracking part, you'd integrate the TensorRT inference within your tracking algorithm pipeline in Python or another language that supports TensorRT.

Hope this helps! Let me know if you have any more questions.

**Comment by ekantons** [comment]
@glenn-jocher I need to export a YOLOv8/10 model with a tracker to ONNX.  Reading through this GitHub issue, you have said that it is possible, with the —keep-track CLI argument, then later with the —track CLI argument (Jul 14, 2023).  However, later still, you said that the tracker might not be exported (Aug 26, 2023), and later only the detector model can be exported (Aug 28, 2023).
Would you please clarify these apparently conflicting statements?
I have an edge device that can run ONNX models, and I need to export *both* the detector *and* the tracker to ONNX.
If this is possible, what are the CLI commands, or (better) what are the Python statements and arguments to accomplish this?

**Comment by glenn-jocher** [comment]
Hi @ekantons,

Currently, only the detection model can be exported to ONNX. The tracking functionality, managed by algorithms like DeepSort, is not included in the exported model. You would need to handle tracking separately in your application.

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions, feel free to ask.

**Comment by Hasan-atc** [comment]
yolo export model=runs/detect/train2/weights/best.pt format=coreml imgsz=640 int8 nms track source=x.jpeg

Ultralytics 8.3.58 🚀 Python-3.8.10 torch-2.3.0+cu121 CUDA:0 (NVIDIA GeForce RTX 3060, 11802MiB)

/home/hasan/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,
Model summary (fused): 218 layers, 25,846,708 parameters, 0 gradients, 78.7 GFLOPs

image 1/1 /home/hasan/Desktop/banknote_detection/x.jpeg: 640x480 2 100fs, 1 10b, 65.4ms
Speed: 1.4ms preprocess, 65.4ms inference, 130.9ms postprocess per image at shape (1, 3, 640, 480)
Results saved to runs/detect/track
💡 Learn more at https://docs.ultralytics.com/modes/track


Hi @glenn-jocher I apologize for the inconvenience. How do I solve this problem? Also, the exported model does not appear. Can you help me where I can find it?

**Comment by glenn-jocher** [comment]
It seems there might be some confusion or misconfiguration with the `yolo export` command. The tracking functionality (`track`) is not part of the exported model itself, as tracking requires an external algorithm like DeepSort integrated into the Python runtime. Exporting only supports the detection model.

If no exported model appears, ensure the `format=coreml` argument is valid for your system (CoreML export is supported on macOS/Linux, not Windows). Additionally, remove unnecessary arguments such as `track` and use the correct CLI syntax:

```bash
yolo export model=runs/detect/train2/weights/

**Comment by Hasan-atc** [comment]
Thank you for your answer. The output I receive in Coreml format works without any problems. It is worth say again for those who have other problems, you should convert in MacOs.

**Comment by glenn-jocher** [comment]
@Hasan-atc you're welcome! Glad to hear the CoreML export works well for you. Yes, as noted, CoreML export is supported on macOS or Linux, not Windows, so macOS is a great choice for seamless conversion. Let us know if you have any further questions!
