### ISSUE TITLE
Cannot export the onnx

### ISSUE THREAD

**Issue by PredyDaddy** [ultralytics/ultralytics#3649]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I have facing the question below: 
(base) root@fc4060355e77:/app/ultralytics-main# yolo export model=yolov8s-pose.pt format=onnx device=0 \
>             imgsz=640 \
>             half=true \
>             dynamic=true \
>             simplify=true

Ultralytics YOLOv8.0.131 🚀 Python-3.8.12 torch-1.12.0a0+2c916ef CUDA:0 (NVIDIA GeForce RTX 3070, 8191MiB)
YOLOv8s-pose summary (fused): 187 layers, 11615724 parameters, 0 gradients, 30.2 GFLOPs

PyTorch: starting from yolov8s-pose.pt with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 56, 8400) (22.4 MB)

ONNX: starting export with onnx 1.10.1 opset 14...
ONNX: export failure ❌ 0.6s: "slow_conv2d_cpu" not implemented for 'Half'

I thought probably this is an error due to I did not install the pytorch correctly, so I just directly using the nvidia docker. And I still have this problem. If I just only used the simplify=true it works. But if I add all the parameters I showed above. I cannot convert the onnx. 

Thanks

**Comment by Kayzwer** [comment]
try update your onnx by `pip install -U onnx`, also dynamic only compatible with cpu, I dont think it work with device=0

**Comment by glenn-jocher** [comment]
@PredyDaddy hi there! Thank you for reaching out.

Regarding your issue with exporting the ONNX format in YOLOv8, there are a few suggestions I can provide. First, try updating your ONNX package by running `pip install -U onnx`. This will ensure you have the latest version installed.

Additionally, please note that the `dynamic` parameter in the export command is only compatible with CPU mode. If you are specifying `device=0`, it might not work as expected. You may want to try running the export command without the `device` parameter.

I hope these suggestions help resolve your issue. If you have any further questions or need more assistance, feel free to ask.

**Comment by rbgreenway** [comment]
Instead of starting a new thread, thought I'd post here since it is also related to exporting a pose model to onnx.

When I attempt converting yolov8m-pose.pt to onnx, I get the following error:

```
>>> model=YOLO("yolov8m-pose.pt")
WARNING ⚠️ yolov8m-pose.pt appears to require 'ultralytics.nn.modules.conv', which is not in ultralytics requirements.
AutoInstall will run now for 'ultralytics.nn.modules.conv' but this feature will be removed in the future.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt'
requirements: YOLOv8 requirement "ultralytics.nn.modules.conv" not found, attempting AutoUpdate...
ERROR: Could not find a version that satisfies the requirement ultralytics.nn.modules.conv (from versions: none)
ERROR: No matching distribution found for ultralytics.nn.modules.conv

[notice] A new release of pip is available: 23.0.1 -> 23.2
[notice] To update, run: pip install --upgrade pip
requirements: ❌ Command 'pip install --no-cache "ultralytics.nn.modules.conv"  ' returned non-zero exit status 1.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bryan/.virtualenvs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 107, in __init__
    self._load(model, task)
  File "/home/bryan/.virtualenvs/yolov8/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 156, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/home/bryan/.virtualenvs/yolov8/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 417, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/home/bryan/.virtualenvs/yolov8/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 372, in torch_safe_load
    return torch.load(file, map_location='cpu'), file  # load
  File "/home/bryan/.virtualenvs/yolov8/lib/python3.10/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/bryan/.virtualenvs/yolov8/lib/python3.10/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/home/bryan/.virtualenvs/yolov8/lib/python3.10/site-packages/torch/serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'ultralytics.nn.modules.conv'; 'ultralytics.nn.modules' is not a package
>>> 

could this be related to using python 3.10?  I've tried updating onnx package and manually installing ultralytics.nn.modules.conv, but neither changed anything.

Any ideas?
```

**Comment by glenn-jocher** [comment]
@rbgreenway it appears that you're trying to load a model that may have been trained with a previous or different version of the Ultralytics package which included the `ultralytics.nn.modules.conv` module. Unfortunately, that module isn't present in the current version from which you're trying to load the model, resulting in the error.

While the Python version could potentially be part of the issue, it's more likely that the error is due to a mismatch between the module versions in your environment and the version the model was trained with.

If you have access to the environment details (or better, the actual environment) where the model was trained, try using that to load and export the model. If that's not feasible, as the warning message suggests, you might have to train a new model using the latest Ultralytics package, or run a command with an official YOLOv8 model.

**Comment by rbgreenway** [comment]
@glenn-jocher the pose model that I'm trying to convert is yolov8m-pose.pt which I downloaded directly from the ultralytics site.  I'm now assuming that this network was trained a while back, and that the latest ultralytics may not be compatible...at least in terms of an export.  Could this be the issue?  If not, I'll dig a bit into my python version.

**Comment by glenn-jocher** [comment]
Hi @rbgreenway! I'm glad you were able to resolve the issue. Your assumption was correct. The model `yolov8m-pose.pt` you're using might have been trained with a different or earlier version of Ultralytics. Therefore, it created some incompatibility issues with the latest version when you tried to export it.

The solution you applied, updating Ultralytics to the latest version using `pip install -U ultralytics`, is a good practice. It ensures that any changes or improvements made in the package do not lead to conflicts or inconsistencies with your current work.

Always make sure you are using the latest version of Ultralytics to benefit from all the updates and to avoid compatibility issues. Happy coding!

**Comment by all-for-code** [comment]
> @PredyDaddy hi there! Thank you for reaching out.
> 
> Regarding your issue with exporting the ONNX format in YOLOv8, there are a few suggestions I can provide. First, try updating your ONNX package by running `pip install -U onnx`. This will ensure you have the latest version installed.
> 
> Additionally, please note that the `dynamic` parameter in the export command is only compatible with CPU mode. If you are specifying `device=0`, it might not work as expected. You may want to try running the export command without the `device` parameter.
> 
> I hope these suggestions help resolve your issue. If you have any further questions or need more assistance, feel free to ask.



> @PredyDaddy hi there! Thank you for reaching out.
> 
> Regarding your issue with exporting the ONNX format in YOLOv8, there are a few suggestions I can provide. First, try updating your ONNX package by running `pip install -U onnx`. This will ensure you have the latest version installed.
> 
> Additionally, please note that the `dynamic` parameter in the export command is only compatible with CPU mode. If you are specifying `device=0`, it might not work as expected. You may want to try running the export command without the `device` parameter.
> 
> I hope these suggestions help resolve your issue. If you have any further questions or need more assistance, feel free to ask.

@glenn-jocher hi, I set device=0, dymatics=True, but I set half=False with no error. Why?

**Comment by glenn-jocher** [comment]
@all-for-code hi there! The `half=True` parameter in the export command specifies that the model should be exported with half-precision floating-point numbers (float16). Some operations and layers in PyTorch, and consequently in ONNX, might not fully support half-precision conversions, leading to errors such as the one originally reported: "slow_conv2d_cpu" not implemented for 'Half'.

On the other hand, setting `half=False` instructs the exporter to use full-precision (float32), which is widely supported across different layers and operations within PyTorch and ONNX. That's likely why you are not encountering any errors with `half=False`. The hardware (GPU or CPU) specified by `device=0` is capable of handling the full precision, hence no issues are encountered during the export process with that setting.

The `dynamic=True` parameter should also typically be compatible with GPU mode, but if it seems to work in your case without any issues, it might be due to specific handling within the export functionality of Ultralytics YOLOv8 or recent updates in the supporting libraries that allow dynamic axes to be used without errors even on the GPU.

If you're successfully exporting your model with `device=0`, `dynamics=True`, and `half=False`, then you are good to go. If any new issues arise or if you have further questions, don't hesitate to ask.
