### ISSUE TITLE
How to make block non-learnable

### ISSUE THREAD

**Issue by rusvagzur** [ultralytics/ultralytics#3652]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi Ultralytics team,

In the config file, is there an option to make a block non-learnable? Something like learning=False.

All the best

**Comment by glenn-jocher** [comment]
@rusvagzur hi there,

Thank you for reaching out to the Ultralytics YOLOv8 team. In the YOLOv8 config file, there is currently no explicit option to make a specific block non-learnable. However, you can achieve this by setting the `frozen` parameter to `True` for the corresponding block in the network architecture.

By setting `frozen=True`, the weights of that particular block will be frozen during the training process, effectively making it non-learnable. This can be useful if you want to keep certain layers fixed while training the rest of the model.

Please note that you would need to modify the network architecture definition and set the `frozen` parameter accordingly for the desired block(s) in order to make them non-learnable.

I hope this helps! If you have any further questions or need assistance with YOLOv8, please feel free to ask.

Best regards,
Glenn

**Comment by rusvagzur** [comment]
Thanks for the nice answer, this is what I was looking for!

**Comment by glenn-jocher** [comment]
@rusvagzur hi there,

You're welcome! I'm glad I could help. If you have any more questions or need further assistance with YOLOv8, feel free to ask. We are always here to help you.

Best regards,
Glenn
