### ISSUE TITLE
exporting model with half precision doesn't work

### ISSUE THREAD

**Issue by aka-sh74** [ultralytics/ultralytics#3654]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to convert my fp32 nano model into fp16/int8. I've exported my model to `onnx` format with `half = True` argument. Can you please help me with these confusions:

1. My model size has increased from _6mb to 12mb_. Is this an expected result?
2. When I view my exported model in netron, **_inputs are still of fp32_**. Shouldn't inputs have been changed to fp16?

I've also tried quantising my model using [this](https://pytorch.org/docs/stable/quantization.html) documentation but couldn't achieve my results.  
I've used `model.half() `function to quantize my model but I returns `AttibuteError: 'dict' object has no attribute 'half'`. What could be the reason for this?

Any suggestion on how to achieve quantisation would be very helpful. It would be better if a solution offers changing a fp32 pytorch model to fp16/int8 pytorch model. 
Thanks!

**Comment by glenn-jocher** [comment]
@aka-sh74 hi there,

Thank you for reaching out about exporting the YOLOv8 model with half precision. I'll be happy to help clarify your confusions.

1. As for the increase in model size from 6mb to 12mb after exporting with `half = True`, this is an expected behavior. When exporting with half precision, the model parameters are stored as fp16, which typically requires more memory compared to fp32.

2. Regarding the inputs still being fp32 when viewing the exported model in netron, this is also expected. The input data type will still be fp32, even if you export the model with half precision. This is because the data type of the input is determined based on your input data rather than the model export.

As for quantizing your model using the PyTorch documentation you mentioned, the `AttributeError: 'dict' object has no attribute 'half'` error you encountered suggests that you are trying to apply the `model.half()` function to a dictionary object, which is not supported. To quantize your model, you need to apply it to the model itself, not the dictionary.

To achieve quantization and convert a fp32 PyTorch model to fp16/int8, you can follow the PyTorch quantization guide and apply the appropriate methods and techniques to your model. These techniques include quantizing weights and activations using post-training quantization or quantization-aware training.

I hope this helps! If you have any further questions or need additional assistance, please don't hesitate to ask.

Best regards,
Glenn Jocher

**Comment by victorsoyvictor** [comment]
Mmm I have exported more than 100 models and normally when you export half it reduces its size. 

For example a 1280x6 goes from 700MB to 190MB when half is True (FP16). The FP32 is 380MB. I have done it in one year with different Ultralytics versions.

We then use CPP opencv::DNN to load our models in onnxruntime and in memory are stored as FP32 Mat due to opencv implementation (actually this is a LOG_WARNING from the OpenCV people).

Sorry to disagree.

**Comment by glenn-jocher** [comment]
@victorsoyvictor i apologize for the confusion. Typically, switching to half-precision (FP16) should indeed reduce the model size, as you’ve experienced with previous exports. If your model size has increased unexpectedly, this behavior is unusual. The observations regarding the model's memory representation when using OpenCV's DNN module with ONNX Runtime are correct; OpenCV will issue a warning and convert the model to FP32 as part of its implementation.

It's possible that this unexpected file size outcome might be tied to either a specific configuration or a change within the exporting procedure. I recommend reviewing the export settings and the version details, as they might provide insight into this size discrepancy.

Should there be a persistent issue or for further assistance, feel free to raise this as a detailed issue in the repository for the team to investigate. 

Thank you for your input, and for keeping a keen eye on consistency across versions and exports. Your contributions to the discussion are greatly appreciated.
