### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'is_scripting'

### ISSUE THREAD

**Issue by kyoko9000** [ultralytics/ultralytics#3661]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

1,i use this code:
from ultralytics import YOLO

model = YOLO("yolov8n.pt")

for result in model.track(source="video.mp4"):
    print(
        result.boxes.id.cpu().numpy().astype(int)
    )  # this will print the IDs of the tracked objects in the frame

2, but when all the car run out of that frame and another car will go to that frame i got this issue:
File "D:\9. python project\75. yolov8 pyqt5\venv\lib\site-packages\torch\autograd\grad_mode.py", line 286, in __init__
AttributeError: 'NoneType' object has no attribute 'is_scripting'

3, how can i do? i put code like 
if result: but that is not working

**Comment by itstechaj** [comment]
Hi @kyoko9000,

**Reason for the error:-**
The error occurs because you are accessing id's that are not present. For example, there may be frames where no objects were detected, resulting in no id's being assigned. It is also possible that some objects were detected but did not receive an id. In such cases, the `result.boxes.id` attribute returns `None`, and you cannot use the `.cpu()` method on it because it is of type `None`.

**Solution:-**
To resolve this issue, you can add a check to verify if `result.boxes.id` is not `None` before processing the id's. Here is an example of how you can implement it:

```python
from ultralytics import YOLO
model = YOLO("yolov8n.pt")

for result in model.track(source="video.mp4"):
  if result.boxes.id!=None: # this will ensure that id is not None
    print(result.boxes.id.cpu().numpy().astype(int)) 
```
### Additional code for better explanation :- 

```python
from ultralytics import YOLO
model = YOLO("yolov8n.pt")
results=model.track(source="video.mp4")
names=results[0].names #storing class names of dataset
#iterate over result of each frame of video 
for fr,result in enumerate(results):
  if(result.boxes.id!=None): # check if id is present or not.
    print(f"<---------Frame {fr}------------>")
    # extracting the ids of objects detected in a frame as per your given code
    ids=result.boxes.id.cpu().numpy().astype(int)
    cls=result.boxes.cls.cpu().numpy().astype(int)
    '''
    do the processing on ids.
    '''
    for cls,id in zip(cls,ids):
      print(f"Detected {names[int(cls)]} with ID={id}")
```
_here is snap of some part of output_   
<img src="https://github.com/ultralytics/ultralytics/assets/74065677/da640abf-2046-446c-bdfc-f159da62bb95" width="300" height="300">


**_If you encounter any errors or have any suggestions, please let me know. Your feedback will be greatly appreciated and helpful for me🙏._**

**Comment by kyoko9000** [comment]
Thank you very much! i will check when i be home

**Comment by glenn-jocher** [comment]
@kyoko9000 hi there! 

Thank you for reaching out. The error you're encountering is likely due to accessing IDs that are not present in certain frames. In some frames, no objects may be detected, resulting in no IDs being assigned. 

To resolve this, you can add a check to verify if the `result.boxes.id` attribute is not `None` before processing the IDs. This check ensures that an ID is present before using the `.cpu()` method on it.

Feel free to give it a try with the suggested code snippet provided in my previous response. If you have any further questions or need additional assistance, please don't hesitate to ask. We're here to help!

Best regards,
Glenn Jocher

**Comment by itstechaj** [comment]
> Thank you very much! i will check when i be home

most welcome 🙏🙏

**Comment by glenn-jocher** [comment]
@itstechaj hi there,

You're welcome! If you have any further questions or need assistance with YOLOv8, feel free to ask. We're here to help!

Best regards,
Glenn Jocher

**Comment by bsridatta** [comment]
The docs should be updated with this fix :)
