### ISSUE TITLE
How to make YOLOv8 classification model to a feature extractor.

### ISSUE THREAD

**Issue by Rokessovsky** [ultralytics/ultralytics#3673]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have trained a yolov8 classification model using my own dataset and it's been performing extremely well on classification tasks on all my data, better than other classification models. I want to make my code more versatile and I want to turn it to a feature extractor, for a normal classification model I can just take the output of the second last layer but I found it very hard to do the same on Yolo classification model. So how can I achieve it? 

In code, normal yolo cls returns a result object and I can get cls probability from it:
```
from ultralytics import YOLO

yolo = YOLO(yolov8m-cls.pt")
result = yolo(image)
```
now I want to change it to return the feature that was used to predict the class, so something like:
```
yolo = YOLO(yolov8m-cls.pt")
#TODO: turn yolo to return feature
feature_tensor = yolo(image)

```

**Comment by glenn-jocher** [comment]
@Rokessovsky hi there, 

Thank you for your question! In order to turn your YOLOv8 classification model into a feature extractor, you can modify the code as follows:

1. Load the YOLOv8 model as usual using the `YOLO` class from Ultralytics:
```python
yolo = YOLO("yolov8m-cls.pt")
```

2. Instead of using the `result` object to get the class probabilities, you can access the intermediate feature tensor directly. YOLOv8 models have a `model` attribute that holds the underlying PyTorch model. You can access the feature tensor from a specific layer by extracting it from the model using its index. For example, if you want the feature tensor from the second last layer:
```python
feature_tensor = yolo.model[-2].forward(yolo)
```

Please note that the feature tensor you obtain will have the shape and interpretation specific to the YOLOv8 model architecture, so you may need to reshape or further process it according to your needs.

I hope this helps! Let me know if you have any further questions.

**Comment by brr53** [comment]
@glenn-jocher It seems to not work (stacktrace below). What's the current suggested way to convert a Yolov8 model into a feature extracting model?

Traceback (most recent call last):
  File "D:\ultralytics\convert_to_feature_model.py", line 4, in <module>
    feature_tensor = yolo.model[-2].forward(yolo)
TypeError: 'ClassificationModel' object is not subscriptable

**Comment by glenn-jocher** [comment]
@brr53 hello, thanks for reaching out again with the error you're encountering. 

The problem behind this error is that the `ClassificationModel` in Ultralytics YOLOv8 isn't structured in a typical sequential way, hence it cannot be accessed via index as you're attempting. You are seeing this TypeError because you are trying to subscript an object that doesn't have that capability.

Instead of directly accessing the intermediate layer features using subscription from the model, Ultralytics YOLOv8 models have specific methods intended for this purpose. 

What you need to do is to modify the forward method of the YOLOv8 model to return the feature maps that you need. You can get features directly from the layers and configurations you're interested in. Please bear in mind, however, that you would have to be careful with layer indices and ensure you're accessing the correct layers for feature extraction, as the model's layers have complicated dependencies.

That being said, please revisit the model's documentation for further clarification and ensure you adjust the model's forward method correctly to cater to your requirements.

Hope this answers your query. If you still need assistance, feel free to ask. We're here to help!

**Comment by mikel-brostrom** [comment]
Change this:

https://github.com/ultralytics/ultralytics/blob/4ac93d82faf3324d18a233090445e83cfac62ce2/ultralytics/nn/modules/head.py#L163-L170

to 

```python
    def forward(self, x):
        """Performs a forward pass of the YOLO model on input image data."""
        if isinstance(x, list):
            x = torch.cat(x, 1)
        x = self.drop(self.pool(self.conv(x)).flatten(1))
        return x if self.training else x
```

Then this:

```
import cv2
from ultralytics import YOLO
import torchvision.transforms as transforms

model = YOLO('yolov8n-cls')
cap = cv2.VideoCapture(0)
cap.set(3, 640)
cap.set(4, 480)

while True:
    _, img = cap.read()

    # convert img to RGB
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    img = transforms.ToTensor()(img)
    img = img.unsqueeze(0)
    
    # BGR to RGB conversion is performed under the hood
    # see: https://github.com/ultralytics/ultralytics/issues/2575
    features = model.model.model(img)
    print(features.shape)

    if cv2.waitKey(1) & 0xFF == ord(' '):
        break

cap.release()
cv2.destroyAllWindows()
```

will give you:

```py
torch.Size([1, 1280])
torch.Size([1, 1280])
torch.Size([1, 1280])
torch.Size([1, 1280])
torch.Size([1, 1280])
torch.Size([1, 1280])
torch.Size([1, 1280])
torch.Size([1, 1280])
torch.Size([1, 1280])
...
```

**Comment by glenn-jocher** [comment]
@mikel-brostrom, thank you for detailing your approach!

Yes, what you’ve done by modifying the forward method of the classification head is correct; you've effectively converted the model into a feature extractor. Just ensure that the changes you have made align with your project's requirements, and the feature dimensionality (represented by the tensor shape) is as expected for your downstream tasks.

The code snippet you've provided for processing video frames in real-time and extracting features looks good for capturing frames from a webcam and converting them to the required format. Remember that this customization changes the original behavior of the model, so keeping a backup or version control before such modifications is generally a best practice.

By overriding the classification head's forward method, you're now getting a tensor that represents the features right before the classification layer. This feature tensor can then be used in your downstream applications, such as input to another model, clustering, similarity comparison, etc.

Your console output indicates that the features tensor has a shape `[1, 1280]`, where 1 is the batch size and 1280 is the number of features. This is exactly what you would expect if you wanted to use an intermediate representation from the network. 

If you're satisfied with the resulting features and the modification aligns with your use-case, you can go ahead with this setup. If you encounter any more issues or have further questions, please don't hesitate to ask.

**Comment by shivam55sit** [comment]
how to use KFold cross validation for image classification model with YOLOv8. Is it possible to use the cross-validation without Converting the images to yaml format?

**Comment by shivam55sit** [comment]
what if I do this?

 # generate features
    features = model.model.model(img)
    print(features.shape)

**Comment by glenn-jocher** [comment]
Hello! Your approach to extracting features directly from the model looks good. Just ensure that `model.model.model(img)` correctly references the part of the YOLOv8 architecture where you intend to extract features from. The print statement should then output the shape of your features tensor, confirming that the extraction is working as expected. If you encounter any specific issues or have further questions, feel free to ask. Happy coding! 🚀
