### ISSUE TITLE
How to pass the scale in custom yaml

### ISSUE THREAD

**Issue by PavinderYadav0** [ultralytics/ultralytics#3679]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When a custom yaml is created by modifying some change in the architecture, how to pass the scale, I mean when I run the command 
**_yolo detect train data=data.yaml model=cfg/custom.yaml epochs=100 imgsz=640 batch=4_**
This send me the warning - WARNING  no model scale passed. Assuming scale='n'.
How to pass the scale, I want to use the scale l

**Comment by harshdhamecha** [comment]
The following line from the `guess_model_scale` function is responsible for guessing model scale.

https://github.com/ultralytics/ultralytics/blob/b239246452b9321e17287af8e92a9d449fa2216b/ultralytics/nn/tasks.py#L711

This code searches for a pattern that starts with "yolov" followed by one or more digits, and captures a single character from the set 'n', 's', 'l', 'm', or 'x'. It extracts and returns the captured character from the search result.

In your case, it will return `''`(an empty string) probably. And thus the following line will call the scale present at `0`th index ultimately.  

https://github.com/ultralytics/ultralytics/blob/b239246452b9321e17287af8e92a9d449fa2216b/ultralytics/nn/tasks.py#L614 

So, you can change this line to:
```
 scale = tuple(scales.keys())[3] 
```

**Comment by glenn-jocher** [comment]
@PavinderYadav0 hi there,

When running the command `yolo detect`, the warning message "WARNING no model scale passed. Assuming scale='n'" is displayed. This warning indicates that the model scale is not explicitly passed as an argument in the command.

The model scale in YOLOv8 is automatically guessed based on the architecture yaml file. The line of code responsible for guessing the model scale can be found [here](https://github.com/ultralytics/ultralytics/blob/b239246452b9321e17287af8e92a9d449fa2216b/ultralytics/nn/tasks.py#L711). It searches for a pattern in the architecture name that starts with "yolov" followed by one or more digits, and captures a single character from the set 'n', 's', 'l', 'm', or 'x'. This captured character is then used as the model scale.

In your case, it seems that the guessed model scale is an empty string, which is likely causing the warning. The line of code that uses the guessed model scale can be found [here](https://github.com/ultralytics/ultralytics/blob/b239246452b9321e17287af8e92a9d449fa2216b/ultralytics/nn/tasks.py#L614). It selects the scale at index 0, which is why you see the warning.

To address this, you can modify the line of code that selects the model scale. For example, you can change it to `scale = tuple(scales.keys())[3]`, which will select the scale at index 3. This way, you can explicitly set the model scale you want to use.

I hope this explanation helps! Let me know if you have any further questions.
