### ISSUE TITLE
tflite yolov8 model not performing well after exporting it  with int8 quantization in tflite format.

### ISSUE THREAD

**Issue by srikar242** [ultralytics/ultralytics#3693]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi @glenn-jocher @plashchynski @xbkaishui @CySlider I have trained a custom yolov8 model using ultralytics. And then exported it in tflite format with int8 quantization. But however, I noticed that tflite model is taking more processing time than actual model. With my trained .pt base model, I was able to process frames at around 55ms on my CPU. But, the int8 tflite model is processing it at 85ms. I think the processing time is expected to reduce with tflite model. Then why is it not happening? And what kind of quantizations are you doing?

Command Used to export model into int8 tflite model:

` yolo export model=best.pt format=tflite int8`

**Comment by glenn-jocher** [comment]
@srikar242 this is normal as TFLite models are optimized for Android ARM backends, not computer CPUs, so the speeds are not expected to be fast in your typical development environment.

**Comment by srikar242** [comment]
Hi @glenn-jocher thanks for your reply and I got your point regarding tflite model. But I have some doubts regarding ONNX model.

Firstly, I trained a  object detection model of 2 classes using ultralytics and exported the model in ONNX format using `export utility of ultralytics`. Exported model's size on disk was around 12.2MB. With this exported ONNX model, I was able to process images at around 46ms on average on my CPU.

Then I tried to quantise that ONNX model with onnxruntime's quantisation utlity. I did dynamic quantization using `quantise_dynamic` utility of onnxruntime. Size on disk of quantized model I got was around 3.3MB. But the problem is, quantised model is taking around 64ms on average to process images on my CPU.

I am not getting how quantized model which is smaller in size(3.3MB) is taking more (approx 18ms) time to process images than unquantized model(12.2MB). I am doing all these tests on Macbook with os Ventura 13. I have pasted the code I used to quantize the mode below.

And also please suggest some methods or techniques using which I can reduce the processing time even further with ONNX model. And also, if I can do anything more differently in quantization.

```
import onnx
from onnxruntime.quantization import quantize_dynamic, QuantType

onnx_model = 'best.onnx'
model_quant = 'best_quant.onnx'
quantized_model = quantize_dynamic(onnx_model, model_quant,weight_type=QuantType.QUInt8)
```

**Comment by srikar242** [comment]
Hi @glenn-jocher @plashchynski @CySlider @xbkaishui @diramazioni Any update on this? I want to know the reason if there is anything specific about conversion. And to give more information, I am doing all these tests on Macbook cpu.

And also please specify any other quantization methods that can help reduce the model size and increase FPS. Thank you in Advance.

**Comment by glenn-jocher** [comment]
Hi @srikar242, thanks for your patience. Quantization typically reduces model size and can enhance the speed on specific hardware that have optimized quantized operations, but it's not guaranteed to speed up the inference time on all types of hardware, especially on some general purpose hardware like CPUs where quantized operations might not be as optimized as on certain mobile or edge devices. 

Additionally, dynamic quantization in ONNX only quantizes the weights of the linear layers from float32 to int8, while the computations are still happening in float32. So, the reduction that we see in model size doesn't translate into computation speed up. 

For speeding up the inference and reducing model size, you might consider quantizing more parts of the model and not just linear layers. Moreover, as you are running your model on CPU, you might also consider using optimized libraries for ONNX models such as ONNX Runtime, which might optimize the inference further. 

Please note that the above explained process can have varying effects based on the specific model architecture and the deployment hardware. So, extensive tests based on your use-case scenario is generally desirable to find the appropriate approach for model optimization. It might take some trial and error to find the best method.

**Comment by srikar242** [comment]
Hello @glenn-jocher. Thanks for your reply. I tried to quantize the model in a different way. I have pasted the code below.

```
import onnx
from onnxruntime.quantization import quantize_dynamic, QuantType

onnx_model = 'best.onnx'
model=onnx.load(onnx_model)
model_quant = 'best_quant.onnx'
names=[node.name for node in model.graph.node]
prefix = ["MatMul", "Add", "Relu"]
linear_names = [v for v in names if v.split("_")[0] in prefix]

quantize_dynamic(onnx_model, onnx_model+".quantall", weight_type=QuantType.QUInt8)

quantize_dynamic(onnx_model, onnx_model+".int8.quant", weight_type=QuantType.QUInt8, nodes_to_quantize=linear_names, extra_options={"MatMulConstBOnly":True})

quantize_dynamic(onnx_model, onnx_model+".uint8.quant", weight_type=QuantType.QUInt8, nodes_to_quantize=linear_names, extra_options={"MatMulConstBOnly":True})
 
```
In the above code, if I assign weight_type=QuantType.QInt8, I am getting the below error:

```
File "/Users/srikar/anaconda3/envs/prepv8/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 435, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for ConvInteger(10) node with name '/model.0/conv/Conv_quant'
```
In order to get rid of this error, I changed weight_type=QuantType.QUInt8. After this , its working but model is running slower than actual ONNX model. I am not getting why it is happening.

And as you said that dynamic quantization of ONNX only quantizes liner layers into int8 and computations are happening in FP32 only, may I know how can I quantize more parts of the model to achieve higher FPS.

It would be of great help to me if you can point me to some article or piece of code using which I can quantize other parts of the model as well. Thanks in Advance.

**Comment by glenn-jocher** [comment]
Hi @srikar242, 

It seems like you're experiencing some issues when attempting to quantize your ONNX model, which is causing the model to run slower than expected. The issue might be due to the fact that the layer types in the YOLOv8 model do not fully support the dynamic quantization method, and ONNXRuntime might not have optimized quantized operations for these layer types.

Dynamic quantization in ONNX runtime converts weights of specific types of nodes to a reduced precision data type, specifically from float32 to int8, which reduces model size but doesn't necessarily speed-up the computations.

In terms of how to achieve higher FPS, as I mentioned earlier, dynamic quantization mainly quantizes linear layers. For models like convolutional neural networks (CNNs), which YOLOv8 belongs to, you might want to consider full quantization (sometimes called static quantization), which quantizes not just weights but also intermediate activations. However, please note that this might involve more work, as this usually requires a representative dataset to correctly compute the quantization parameters (min, max or mean, standard deviation).

Unfortunately, as per the guidelines, I can't provide direct links to articles or pieces of code, but I can tell you that there exist several resources online that you can refer to on this subject. Try looking up terms such as "full quantization ONNX Runtime" or "static quantization ONNX Runtime" in a search engine to find guides and examples.

I hope this helps and I wish you good luck in your model optimization process!

**Comment by srikar242** [comment]
@glenn-jocher Thanks for your reply. I will look into this.

**Comment by glenn-jocher** [comment]
Hello @shashichilappagari, 

Thank you for sharing your success in quantizing and running YOLO models on OpenVINO and Google Edge TPU. It's great to hear that your team at DeGirum has successfully quantized and ported Ultralytics object detection models, specifically YOLOv8, with different activation functions and for various applications. This achievement provides a good amount of versatility for those utilizing your models. 

Knowing that you've made these models available on your cloud platform can certainly be a valuable resource for other developers and researchers working on similar projects. Providing the option to run the models in different environments significantly increases the accessibility and usability of your work. 

We appreciate your willingness to assist and support others in the community by making these resources available and sharing your findings. Good luck with your live demonstration, and we look forward to hearing more about your future achievements with YOLOv8.

Best Regards!

**Comment by Chebulex** [comment]
Hello @srikar242 
Since you were talking about tflite export, I wanted to ask you if you were able to deploy and successfully run your exported tflite model on Android and if so, I maybe have sample code for it.
I have been trying for days to run the tflite model on an Android device and it keeps failing. So if you have any tips, I would really appreciate it!

**Comment by glenn-jocher** [comment]
@Chebulex hi there!

Yes, deploying a TfLite model on Android can sometimes be challenging due to several aspects including model compatibility, hardware infrastructure, and Android system intricacies. 

Here are a few tips you can try to troubleshoot: 

1. Ensure that the TfLite model is correctly converted: You might want to recheck the conversion process from your original model to the TfLite format. Make sure that all operations in your YOLOv8 model are compatible with TfLite.

2. Check your Android code: Sometimes the issue lies in how the Android app uses the TfLite interpreter to run the model. Debug your code to see if the model is correctly loaded and if the inputs and outputs are properly handled.

3. Test your model on different devices: Performance can drastically vary depending on the device's hardware. It's worth testing your model on various devices with different specifications to isolate potential device-specific issues.

4. Verify your Android permissions: When dealing with loading files or using camera for real-time detection, the Android system requires certain permissions. Make sure your app has all necessary permissions.

I hope these suggestions can give you a hint on where to start looking for a solution!
