### ISSUE TITLE
Training with yolov8s-seg.pt pretrained model results in a large pt file(X size model) after training

### ISSUE THREAD

**Issue by lzs0603** [ultralytics/ultralytics#3712]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I recently trained a Yolov8s-seg model on my custom dataset, however, I realized no matter how I changed the method of training, either using a pretrained yolov8s-seg.pt or training from scratch with yolov8s-seg.yaml, it ends up with a large pt file after training(about 136MB). The trained model looks like a yolov8x-seg size model. I am not sure whether I did the training in a wrong way or I mistakenly set some parameters caused this. Please help, thank you!
![Screen Shot 2023-07-13 at 10 50 11 AM](https://github.com/ultralytics/ultralytics/assets/33793693/15018dc7-4562-4a9c-bba2-d05780dbb304)
![Screen Shot 2023-07-13 at 10 52 03 AM](https://github.com/ultralytics/ultralytics/assets/33793693/1460d726-1ccc-4ed3-be5b-8d11794a045a)

**Comment by Kayzwer** [comment]
@lzs0603 its actually normal, because the .pt also includes information like epoch, emo, optimizer.state_dict(), training args, date, and version of ultralytics.

**Comment by Kayzwer** [comment]
@lzs0603 you also can use function `strip_optimizer` in `ultralytics/ultralytics/yolo/utils/torch_utils.py` to remove other information in your .pt

**Comment by lzs0603** [comment]
> @lzs0603 its actually normal, because the .pt also includes information like epoch, ema, optimizer.state_dict(), training args, date, and version of ultralytics.

Thanks for the fast reply! Yes I saw another issue mentioned this, but is it normal to have exactly the same size of pt no matter how I change the training parameter? Or is the pt size mostly related to the custom dataset?

**Comment by Kayzwer** [comment]
not sure, but model size and model type ofc will change the size of .pt

**Comment by glenn-jocher** [comment]
@Kayzwer it is normal for the size of the .pt file to change based on the model type and dataset used for training. The size of the .pt file is affected by various factors such as the number of parameters in the model, the complexity of the dataset, and any additional information stored in the file such as training parameters, optimizer state, and other metadata.

In the case of YOLOv8, the size of the .pt file may vary depending on the specific model variant (e.g., yolov8s-seg, yolov8x-seg) and the characteristics of the custom dataset being used for training. The inclusion of epoch information, ema, optimizer state, training args, and other metadata can also contribute to the overall file size.

If you have concerns about the size of the .pt file, you can consider using the `strip_optimizer` function provided in `ultralytics/ultralytics/yolo/utils/torch_utils.py` to remove unnecessary information and further reduce the file size.

Keep in mind that the primary goal of the .pt file is to store the trained model's parameters so that it can be loaded and used for inference. The size of the file does not necessarily reflect the performance or effectiveness of the trained model.
