### ISSUE TITLE
Can the engine model be used directly like the onnx model? 

### ISSUE THREAD

**Issue by orderer0001** [ultralytics/ultralytics#3713]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Can the engine model be used directly like the onnx model? Is there such an interface? If not, I'm going to use both engine model checker and usage trace, see if it does? I hope to load the engine file directly into the model, and then use model.track to get the result, just like using onnx. At that time, if I loaded the engine model, an error would be reported: 'utf-8' code can'tdecode. …

**Comment by glenn-jocher** [comment]
@orderer0001 yes, TensorRT models can be loaded just like a PyTorch model:

```python
from ultralytics import YOLO

model = YOLO('yolov8n.engine')

model.predict(...
```

**Comment by orderer0001** [comment]
I use trtexec to convert onnx to engine, but it can’t be used in yolo v8, and an error is reported: 
**_UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 4: invalid continuation byte_**
Then I used the export that comes with yolov8 to export the engine, and got an error: 
_**ONNX: export failure ❌ 4.3s: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument other in method wrapper__equal)
TensorRT: starting export with TensorRT 8.5.2.2...
TensorRT: export failure ❌ 4.3s: expected str, bytes or os.PathLike object, not NoneType**_
The following is my source code: 
```
from ultralytics import YOLO
import torch
print(torch.cuda.is_available())
model = YOLO(r'./cp/lead_model_0706.pt')
device = 'cuda'
model.to(device)
print(model.device)

model.export(format='engine',device=0)
```
The printed device is cuda，Why is this so

> @orderer0001 yes, TensorRT models can be loaded just like a PyTorch model:
> 
> ```python
> from ultralytics import YOLO
> 
> model = YOLO('yolov8n.engine')
> 
> model.predict(...
> ```

**Comment by orderer0001** [comment]
> TensorRT: export failure ❌ 4.3s: expected str, bytes or os.PathLike object, not NoneType

The model is yolov8n

**Comment by glenn-jocher** [comment]
@orderer0001 thank you for reaching out. The error you encountered during the export process indicates that the model export expects a valid file path, but received a NoneType object instead. To resolve this issue, please make sure you provide a valid file path as the argument for the export function.

Regarding the "UnicodeDecodeError" error you mentioned earlier, this could be caused by encoding issues. Please ensure that all the files and paths you are working with have the correct encoding (e.g., UTF-8).

Additionally, it seems that you are trying to use a CUDA device ("cuda") for your model. This is indicated by the "cuda" output from `print(model.device)`. This means that the model and its operations are being performed on a CUDA-enabled GPU device for faster processing. However, the specific error you encountered doesn't seem to be related to CUDA device usage. It would be helpful to look for other possible causes or check if there are any additional error messages or stack traces that could provide more insights into the issue.

If you continue to experience issues, please provide more details and error logs so we can further investigate and assist you.

**Comment by orderer0001** [comment]
```python
from ultralytics import YOLO
import cv2
import torch
# import os
# os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
# model = YOLO(r'./cp/lead_model_0706.onnx',task='detect')
model = YOLO(r'./cp/lead_model_0706.engine',task='detect')
source = r"/dev/video0"
cap = cv2.VideoCapture(source)
count = 0
boxes =None
while True:
    if count %3 ==0:
        ret, frame = cap.read()

        print(frame.shape)
        if not ret:
            break
        results = model(frame)
        try:
            boxes = results[0].boxes.xyxy.cpu().numpy().astype(int)
        except:
            pass
        center_img = (int(frame.shape[1]/2),int(frame.shape[0]/2)-110)
        if boxes is not None :
            boxes_start =[item for item in boxes if int((item[0]+item[2])/2) < center_img[0]]
            sorted_boxes_start = sorted(boxes_start, key=lambda x: x[0], reverse=True)
            try:
                box = sorted_boxes_start[0]
            except:
                continue
            cv2.circle(frame, center_img, 8, (255, 0, 0), -1)
            pb_center = (int((box[0] + box[2]) / 2), int((box[1] + box[3]) / 2))
            print(pb_center)

            cv2.rectangle(frame, (box[0], box[1]), (box[2], box[3]), (0, 255, 0), 2)
            cv2.circle(frame, pb_center, 8, (0, 0, 255), -1)
            cv2.putText(
                    frame,
                    f"{pb_center}",
                    (box[0], box[1]+300),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    1,
                    (0, 0, 255),
                    2,
                )
    count+=1
    cv2.imshow("frame", frame)
    if cv2.waitKey(1) & 0xFF == ord("q"):
        break
``` 
The above is the complete code, and the following is the running error
```python
/bin/python3 /home/jetson/Downloads/mysam/my_track.py 
cuda
(480, 640, 3)
Loading cp/lead_model_0706_32.engine for TensorRT inference...
Traceback (most recent call last):
  File "/home/jetson/Downloads/mysam/my_track.py", line 38, in <module>
    results = model.track(frame, persist=True)
  File "/home/jetson/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 278, in track
    return self.predict(source=source, stream=stream, **kwargs)
  File "/home/jetson/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/jetson/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 250, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "/home/jetson/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 306, in setup_model
    self.model = AutoBackend(model,
  File "/home/jetson/.local/lib/python3.8/site-packages/ultralytics/nn/autobackend.py", line 168, in __init__
    metadata = json.loads(f.read(meta_len).decode('utf-8'))  # read metadata
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 4: invalid continuation byte
``` 
The engine file is built by using tensorrt in the ubuntu20.4 system of the operating environment through the trtexec tool。

The jetson Orin Nano system environment is as follows:
ubuntu20.4 aarch64
python 3.8.10
cuda 11.4.315
cudnn 8.6.0.166
trnsorrt 8.5.2.2
opencv:4.5.4
jetpack:5.1.1
L4T:35.3.1

The onnx model is running fine。



> @orderer0001 thank you for reaching out. The error you encountered during the export process indicates that the model export expects a valid file path, but received a NoneType object instead. To resolve this issue, please make sure you provide a valid file path as the argument for the export function.
> 
> Regarding the "UnicodeDecodeError" error you mentioned earlier, this could be caused by encoding issues. Please ensure that all the files and paths you are working with have the correct encoding (e.g., UTF-8).
> 
> Additionally, it seems that you are trying to use a CUDA device ("cuda") for your model. This is indicated by the "cuda" output from `print(model.device)`. This means that the model and its operations are being performed on a CUDA-enabled GPU device for faster processing. However, the specific error you encountered doesn't seem to be related to CUDA device usage. It would be helpful to look for other possible causes or check if there are any additional error messages or stack traces that could provide more insights into the issue.
> 
> If you continue to experience issues, please provide more details and error logs so we can further investigate and assist you.

**Comment by orderer0001** [comment]
> @orderer0001 thank you for reaching out. The error you encountered during the export process indicates that the model export expects a valid file path, but received a NoneType object instead. To resolve this issue, please make sure you provide a valid file path as the argument for the export function.
> 
> Regarding the "UnicodeDecodeError" error you mentioned earlier, this could be caused by encoding issues. Please ensure that all the files and paths you are working with have the correct encoding (e.g., UTF-8).
> 
> Additionally, it seems that you are trying to use a CUDA device ("cuda") for your model. This is indicated by the "cuda" output from `print(model.device)`. This means that the model and its operations are being performed on a CUDA-enabled GPU device for faster processing. However, the specific error you encountered doesn't seem to be related to CUDA device usage. It would be helpful to look for other possible causes or check if there are any additional error messages or stack traces that could provide more insights into the issue.
> 
> If you continue to experience issues, please provide more details and error logs so we can further investigate and assist you.

I entered line 166 of the autobackend.py file according to the error message. In order to troubleshoot the problem, I modified the code as follows to output the read f. code show as below:
```python
with open(w, 'rb') as f, trt.Runtime(logger) as runtime:
                meta_len = int.from_bytes(f.read(4), byteorder='little')  # read metadata length
                print(meta_len)
                raw_data = f.read()
                print(raw_data)
                ……
``` 
The first three rows of the printed content are:
x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa5\x7f\x0f\x80\x01\x00\x07\x80\x01\x00\t\x00\x00\x80\x94\x80\x01\x00\x08\x80\x01\x00\x01\x00\x00\x00\x00\x00\x00\x00\x01\x80l\x80\x01\x00\x01\x00\x00\x00\x00\x00\x00\x00\x18\x80\x01\x00%\x00\x00\x00\x00\x00\x00\x00\x01\x80\x0c\x80\x01\x00%\x00\x00\x00\x00\x00\x00\x00Reformatted Input Tensor 0 to Conv_43\x11\x80\x01\x00\x07\x80\x01\x00\x04\x00\x00\x00\x01\x80\x07\x80\x01\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xee\x7f\x11\x80\x01\x00\x07\x80

print(meta_len) counts out a string of numbers

the content of f is not in json format, so json.load cannot be parsed. I guess w should be the weight parameter, right? Then how to ensure that the w file is in json format, or how to load this binary data in non-json format?

**Comment by orderer0001** [comment]
I got the .engine file with trtextc

**Comment by glenn-jocher** [comment]
@orderer0001 
Thank you for using YOLOv8 and reaching out with your question!

Regarding the issue you mentioned, the `UnicodeDecodeError` you encountered while trying to load the engine file (.engine) can be resolved by understanding the file structure and the correct loading procedure.

The .engine file generated by TensorRT with `trtexec` is a binary file containing the optimized model and execution plan specific to your GPU architecture. This file cannot be directly loaded or parsed as a JSON file because it doesn't have JSON format or encoding.

To load the .engine file correctly, you should use the appropriate APIs provided by the TensorRT library. Instead of using JSON loading methods like `json.loads()`, you need to use the TensorRT runtime APIs to load and work with the engine file.

In your code, you are currently trying to read the file using `open()` in binary mode and attempting to decode it as a JSON object, which results in the `UnicodeDecodeError` because the file is not in JSON format. To resolve this, you should use the TensorRT runtime APIs to load the engine file and perform inference.

Please refer to the TensorRT documentation and examples for the correct usage of the runtime APIs to load and use the .engine file in your code. You can find relevant documentation and code examples on the NVIDIA Developer website or the official TensorRT GitHub repository.

If you have any further questions or need additional assistance, please feel free to ask. Good luck with your YOLOv8 model!

**Comment by shanek16** [comment]
> I got the .engine file with trtextc

@orderer0001 Have you solved the issue?
I searched all the questions from other threads, and other users said they have solved the problem by re-installing packages in requirements.txt.
However, I'm searching for more specific solutions.
ex) Updating which packages to version xx.x solved the problem or other solutions that I can try before re-installing all the packages..

**Comment by glenn-jocher** [comment]
Thanks for reaching out @shanek16, and it's great to see your follow-up questions regarding the use of .engine file obtained with 'trtextc'. 

At times, issues encountered can be resolved by updating or reinstalling certain packages, as has been suggested by other users; this is due to the fact that certain packages may have dependencies on specific versions of other libraries, or may contain bugs that have been fixed in later versions. 

In terms of identifying which specific packages might be causing problems, this can be quite challenging without knowing the specifics of the error messages or behaviors you're experiencing.

One starting point might be to look closely at any error messages or logs you are getting when encountering an issue, as these often contain clues about which package or packages might be causing the problem. 

Next, you could check the release notes or documentation for the packages listed in requirements.txt. These notes often list any known compatibility issues with specific versions, or any potential bugs that could be causing your issues.

Lastly, if you have an understanding of the functionality provided by each package, you can try to relate this to the problem you're experiencing. 

However, sometimes reinstalling all libraries might be the most efficient solution, as it can mitigate any potential compatibility issues and ensures you're working with the most recent, and usually most stable, versions of the libraries. 

It's definitely a process of trial and error, but with some patience and persistence, most software issues can be overcome.  If you continue to experience difficulties, don't hesitate to provide more details about your problem, including any error messages, so we can continue to assist you.

**Comment by lxlee** [comment]
It seems like that the engine exported by yolo would add some metadata to the original tensorrt engine. To use the engine exported by trtexec which has no metadata, you'd better write your own code with tensorrt python wrappers. To use the engine exported by yolo in trtexec, you may need to remove the metadata at the beginning of the engine file.

**Comment by glenn-jocher** [comment]
@lxlee indeed, YOLOv8 appends metadata to its TensorRT engine files for internal use, which isn't present in engine files generated directly by `trtexec`. To use an engine file created with `trtexec`, it's recommended to interface with it using the TensorRT Python API directly, ignoring the metadata management performed by the YOLOv8 export process.

Alternatively, if you're attempting to use an engine file exported by YOLOv8 with `trtexec`, you would need to strip the metadata from the beginning of the engine file before loading it with `trtexec`.

For the most seamless experience and integration with YOLOv8, use the provided export methods to generate engine files that are immediately compatible with our API, which handles both the model and metadata appropriately.

**Comment by XhHello** [comment]
> ONNX: export failure ❌ 4.3s: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument other in method wrapper__equal)

Using YOLOv8's export.py on Jetson to copy py ->engine, the same error occurred. Have you resolved it? Thank you

ONNX: export failure ❌ 4.3s: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument other in method wrapper__equal)

**Comment by glenn-jocher** [comment]
Hello! It looks like you're facing a common issue where tensors are located on different devices during the export process. This usually happens when the model or parts of the data are not explicitly moved to the same device (either CPU or CUDA). To fix this, ensure all model and data tensors are on the same device before exporting.

Here's a quick snippet to move your model and its inputs to CUDA if available:

```python
import torch
from ultralytics import YOLO

# Load your model
model = YOLO('./cp/lead_model_0706.pt').to('cuda' if torch.cuda.is_available() else 'cpu')

# Now, try exporting again
model.export(format='engine')
```

This should resolve the device mismatch error by explicitly setting the device for the model. Let us know if this helps or if you have any more questions! 😊

**Comment by XhHello** [comment]
> 

Thank you for your answer. This error was caused by an issue with the pytorch version. **Upgrading the version will resolve it**

**Comment by XhHello** [comment]
> Hello! It looks like you're facing a common issue where tensors are located on different devices during the export process. This usually happens when the model or parts of the data are not explicitly moved to the same device (either CPU or CUDA). To fix this, ensure all model and data tensors are on the same device before exporting.
> 
> Here's a quick snippet to move your model and its inputs to CUDA if available:
> 
> ```python
> import torch
> from ultralytics import YOLO
> 
> # Load your model
> model = YOLO('./cp/lead_model_0706.pt').to('cuda' if torch.cuda.is_available() else 'cpu')
> 
> # Now, try exporting again
> model.export(format='engine')
> ```
> 
> This should resolve the device mismatch error by explicitly setting the device for the model. Let us know if this helps or if you have any more questions! 😊

Thank you for your answer. This error was caused by an issue with the pytorch version. **Upgrading the version will resolve it**

**Comment by glenn-jocher** [comment]
Hey there! 👋 Glad to hear you found a solution, and thanks for sharing it! Indeed, keeping PyTorch updated can solve a variety of issues, including device mismatches during export. If anyone else encounters similar difficulties, upgrading PyTorch might just do the trick. Feel free to reach out if there's anything more we can help with. Happy coding! 🚀
