### ISSUE TITLE
Not generating best.pt

### ISSUE THREAD

**Issue by dariogonle** [ultralytics/ultralytics#3736]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I have been working with yolov8, and at first I tried to do a training with my dataset using 3 epochs to test. In this case, it generated best.pt and last.pt. As everything was going well, I tried using 100 epochs. In this case, last.pt is generated, but not best.pt. Does anyone know why this is happening?

Best regards, and thanks.

Config:
yolo/engine/trainer: task=detect, mode=train, model=yolov8n.yaml, data=data/my.yaml, epochs=100, patience=50, batch=16, imgsz=200, save=False, save_period=-1, cache=False, device=None, workers=8, project=Results/A, name=E20, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, fraction=1.0, profile=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.001, lrf=0.0001, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=Results/A

### Environment

YOLOv8
Ubuntu 22.04
Python 3.10.6

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by dariogonle** [comment]
@glenn-jocher  could it be that best.pt == last.pt, and then only last.pt is generated?

**Comment by Laughing-q** [comment]
@dariogonle There should always be `best.pt` and `last.pt` if you set `val=True`. From your configs you have `val=True` so you should get both these two.
 I'm not able to reproduce your issue.
```python
from ultralytics import YOLO
model = YOLO("yolov8n.pt")
model.train(data="coco128.yaml", epochs=100, batch=16)
```
and I got both `best.pt` and `last.pt`.
![pic-selected-230714-2111-18](https://github.com/ultralytics/ultralytics/assets/61612323/83deb04d-dbd7-400c-8e62-2ce62e7f3a26)

**Comment by dariogonle** [comment]
@Laughing-q I know it is weird but thats happening. I'm using a custom dataset. What's curious is that if I run it from cli i get the best.pt.

Another thing I noticed was that when I trained for 1000 epochs, and with a patience of 50, the training finished around epoch 170. However, it does not generate neither last.pt nor best.pt

**Comment by glenn-jocher** [comment]
Hi @dariogonle,

It's indeed strange that you're not getting the `best.pt` file when training for 100 epochs when running from Python, while you get it when running from the command line. One possibility could be due to differences in command line arguments or configurations between the two methods.

As for the issue of not generating `last.pt` and `best.pt` when training for 1000 epochs with a patience of 50, it's possible that the training process reached an early stopping condition before those files were generated. Early stopping is based on a predefined patience value, which determines how many epochs to wait for improvement in the validation loss before stopping the training. If the model's performance did not improve within the patience limit, training could have ended prematurely without generating those files.

To further investigate these issues, it would be helpful to provide more specific details about your dataset, training configurations, and any error messages or warnings you encountered during the training process.

Best regards and good luck with your training!

**Comment by dariogonle** [comment]
The problem is that I had set the ```save``` parameter to ```False```. If I set it to ```True``` there is no problem.

**Comment by glenn-jocher** [comment]
@dariogonle the `save` parameter controls whether to save a final model. When you set `save = False`, it would not save the `best.pt` and `last.pt` model files after training. If you set `save = True`, then your trained model gets saved at the end of the training process, and you should be able to see the `best.pt` and `last.pt` files in your output directory. So, it seems like everything is working as expected.  

If you need the saved models for future use or for further optimization, remember to always set `save = True`. Of course, keep in mind that setting `save = True` will require additional storage space. 

Best of luck with your model training!

**Comment by gmwmf2014** [comment]
detector = FIRE (model_name='best.pt')
TypeError: object() takes no parameters
problem
In Payton
Everything is fine in colab
When experimenting with Visual Code, the file best.pt is not read

**Comment by glenn-jocher** [comment]
@gmwmf2014 hi, it seems like you're experiencing an error while trying to initialize the `FIRE` model with the `model_name='best.pt'` in your local Python environment, but things are working fine in Google Colab. The `TypeError: object() takes no parameters` error message generally implies that you're attempting to initialize a class or object in Python which is not designed to accept any arguments.

To help you troubleshoot, check the following:

1. Double-check the location of your 'best.pt' file. Make sure it's accessible from the directory where you're running your code in Visual Studio Code.
2. Ensure your local Python environment has all the necessary dependencies installed and they're up-to-date. The discrepancy between your local and Colab environments suggests there might be some differences in the setup.
3. Review the way you're using the `FIRE` class in code. Ensure you're correctly creating the object and the class is designed to accept parameters during initialization.

Without seeing the code, it's not easy to identify the exact issue, but these steps might help you troubleshoot. If the problem persists, please provide a more detailed description, including information about your setup and the code you're using.

**Comment by gmwmf2014** [comment]
I haven't found what I'm looking for yet In fact, I want the files to work
without the Internet using visual code. I have installed all the offices
for this purpose...
 Can you do that and send me all the files? The code for the project on the
Revino website..
I want it to work through the camera Can you help me with that?

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="bUdxfnZNOrKL1Ft1SVQ3")
project = rf.workspace("vocalcords").project("vocalcords-mtkoy")
dataset = project.version(5).download("yolov8")

‫في الأربعاء، 18 أكتوبر 2023 في 3:09 ص تمت كتابة ما يلي بواسطة ‪Glenn
Jocher‬‏ ***@***.***‬‏>:‬

**Comment by glenn-jocher** [comment]
@gmwmf2014 hi, it looks like you want to work offline with a model for real-time object detection using a camera in Visual Studio Code.

Firstly, you need to make sure that you have downloaded your trained model file (e.g., 'best.pt') and it is accessible in your local project directory. 

Regarding your dataset, since you want to work offline, you would need to download your dataset from the Roboflow platform while you have an internet connection. After downloading, make sure your dataset is stored locally and the path to the dataset in the code correctly points to this local directory.

At runtime, models do not require an internet connection, provided that all the code dependencies and data they need to operate are available locally. Therefore, for using openCV (or any other library) to process the video feed from a camera and perform real-time object detection, you need to install all the necessary Python packages in your local environment. The code will then load the model and use it to perform inference on each frame received from the camera.

Remember, Python packages only need to be installed once, so you can do this with an active internet connection and then go offline. 

Unfortunately, I can't send files or provide the exact code for the project as requested, but I hope this guidance helps you set up your project to work offline and perform real-time object detection using a locally stored model and local video feed.

**Comment by gmwmf2014** [comment]
I thank you very much
 I finally managed to do that
Now there is only one problem left, which is calling the voice

from playsound import playsound


The library is installed but cannot be called..
When I change the Python versions in the visual code, the audio
library can be called
But the library cannot be called
ultralytics
There is a conflict. I could not call the offices together


في الجمعة، ٢٠ أكتوبر، ٢٠٢٣ ٨:٢٧ م Glenn Jocher ***@***.***>
كتب:

**Comment by gmwmf2014** [comment]
[image: 001.png]
[image: 002.png]

‫في الاثنين، 23 أكتوبر 2023 في 4:50 م تمت كتابة ما يلي بواسطة عبدالعزيز
عبدالله ***@***.***‬‏>:‬

**Comment by glenn-jocher** [comment]
@gmwmf2014 it sounds like you're facing an issue with the 'playsound' library and the 'ultralytics' library not being able to function together when called. This could be due to multiple factors like Python version conflicts or package dependencies.

If the 'playsound' library works with a different Python version than the one 'ultralytics' library is functioning with, this is a version conflict. You should try to create a virtual environment for your project where you can manage the Python version and packages required. This might help in resolving conflicts between the different versions required by 'playsound' and 'ultralytics'.

In case the issue lies with package dependencies, check the dependencies of both these libraries and try to identify if there are conflicting packages. Uninstalling and then reinstalling packages in the correct order might also help.

Remember, it's important to debug and isolate the problem. Try to run small pieces of code independently to figure out what exactly is causing the issue. This could be helpful in finding a solution.

Please note that the overall process might require some trial and error in finding the compatible versions that work together. If you continue to face issues, consider referring to relevant documentation or specific forums related to the libraries in question.

Good luck with your project!
