### ISSUE TITLE
yolo for cls task

### ISSUE THREAD

**Issue by ChenJian7578** [ultralytics/ultralytics#3747]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

when i use the official method to train  CIFAR10, the code got something wrong like this:
![image](https://github.com/ultralytics/ultralytics/assets/42240985/e6283043-aca8-4e20-96ea-fce56cfabc75)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ChenJian7578 hi there! Thank you for reaching out with your question.

YOLOv8 is primarily designed for object detection tasks, but it can also be used for classification tasks. However, the CIFAR10 dataset is not compatible with YOLOv8 for classification. YOLOv8 is typically trained on large-scale datasets like COCO or ImageNet.

For classification tasks like CIFAR10, I recommend using a different model architecture specifically designed for classification, such as ResNet or DenseNet. These architectures are generally more suitable for image classification tasks and have been extensively tested and optimized for this purpose.

If you have any further questions or need assistance with YOLOv8 or any other topic, please feel free to ask. We're here to help!

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
