### ISSUE TITLE
Is it impossible to change the class color of the predict result if I learn with a pre-trained model?

### ISSUE THREAD

**Issue by haaaaak** [ultralytics/ultralytics#3766]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello.

I conducted custom dataset learning using pre-trained model of segmentation task, 'yolov8n-seg.pt ' and that's where the question arises.

Even though I apply 'yolov8n-seg.pt ' and then I change the class color(hexs) of 'plotting.py', the changed class color does not apply, so if I use a pre-learning model, can't change the class color like this problem?

Of course, without using the pre-trained model, the modified code will be reflected.
But I want to use the pre-learning model above because I want to improve the learning performance of the custom dataset.

I look forward to hearing from you about this matter. Thank you.

**Comment by Peanpepu** [comment]
Here you are a small function I have created for creating my owns images detections once I got the annotation file, I hope this help you:
`
def draw_bounding_boxes(img, annotations_file, output_path):
    
    # Obtener las dimensiones de la imagen
    height, width, _ = img.shape
    
    # Declaramos las clases con sus índices correspondientes
    classes = {
        0: 'emergency vehicle',
        1: 'non-emergency vehicle',
        2: 'first responder',
        3: 'non-first responder'
    }
    
    # Definir los colores para cada clase
    colors = [(73, 164, 73), (183, 56, 56), (0, 0, 255), (196, 196, 10)]

    # Leer las anotaciones desde el archivo de anotaciones YOLO
    with open(annotations_file, 'r') as f:
        annotations = f.read().splitlines()
    
    # Lista para almacenar la ubicación y el área de cada objeto detectado
    detected_objects = []

    for annotation in annotations:

        # Obtener la información de cada anotación
        class_id, x_center, y_center, bbox_width, bbox_height, conf = map(float, annotation.split())
        conf = round(conf, 2) # Se redondea la confianza a 2 decimales

        # Calcular las coordenadas del bounding box
        x = int((x_center - bbox_width/2) * width) # Se multiplica porque las coordenadas del bbox son relativas al ancho y alto del mismo
        y = int((y_center - bbox_height/2) * height)
        w = int(bbox_width * width)
        h = int(bbox_height * height)
        
        # Almacenar al ubicación y el área del objeto detectado en la lista
        detected_objects.append(((x, y, w, h), class_id))

        # Se obtiene el color correspondiente a cada clase
        color = colors[int(class_id)]
        
        # Dibujar el bounding box en la imagen
        cv2.rectangle(img, (x, y), (x+w, y+h), color, 2)

        # Obtener el texto y el color para el texto
        text = classes[int(class_id)] + " " + str(conf)
        text_color = (255, 255, 255)  # Color blanco

        # Calcular el tamaño del texto
        text_size, _ = cv2.getTextSize(text, cv2.FONT_HERSHEY_SIMPLEX, 0.9, 2)

        # Calcular las coordenadas para el rectángulo del texto
        rect_x = x
        rect_y = y - text_size[1] - 10
        rect_width = text_size[0] + 10
        rect_height = text_size[1] + 10

        # Dibujar el rectángulo del texto
        cv2.rectangle(img, (rect_x, rect_y), (rect_x+rect_width, rect_y+rect_height), color, -1)

        # Dibujar el texto con el color correspondiente
        cv2.putText(img, text, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, text_color, 2)

    # Guardamos la imagen resultante con los boundig boxes
    cv2.imwrite(output_path, img)
`

**Comment by pderrenger** [comment]
@Peanpepu it's great that you've created a function for drawing bounding boxes using YOLOv8 annotations! Regarding your previous inquiry about changing the class color when using a pre-trained model, it is absolutely possible to change the class color of the predicted result even if you have trained your model with a pre-trained checkpoint.

The issue you encountered with the class color not changing after modifying the plotting code is likely due to the visualization code in the `plotting.py` file not being triggered during inference. The color assignment for each class should be defined in the visualization component used at prediction time.

You can modify the visualization component to change the class colors, regardless of whether you are using a pre-trained model. If you are using YOLOv8, the class color modification would be implemented in the 'plotting.py' file when using the Predict mode. Ensure that your changes in 'plotting.py' are applied and used when making predictions with your pre-trained model.
