### ISSUE TITLE
Number of boxes defined for onnx export

### ISSUE THREAD

**Issue by weiss-israel** [ultralytics/ultralytics#3779]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How does YOLO8 set the number of boxes for onnx export, since it’s an anchor-free model?
It seems from the code that it's fed with input of zeros during export, and for `nano` size model there are always the same number of boxes, 5670.
What's weird for me, is that I changed the backbone size also to `small` and `medium` on separate exports, and in each case the number of boxes is the same 5670, even though the backbone was changed (I can see that the model's size is indeed different).
When running inference on real data (i.e., images with objects etc.)- the number of boxes varies according to the input, which makes sense for an anchor-free model. 
Does the number of boxes make sense for this usage? didn’t find yet in the yolo8 code an explanation for this observation for zeros input for onnx export purposes. 
How is the number of boxes fixed with this input, especially for different model sizes `nano` / `small` / `medium`? 
Why zeros input for example? 
And does this amount of boxes is ok for all usages for inference- for example for converting this model later for TRT?

**Comment by glenn-jocher** [comment]
@weiss-israel hello,

Indeed, YOLOv8 is an anchor-free model, meaning it doesn't rely on predefined anchor boxes for prediction. When exporting the model to ONNX format, the number of output boxes you are seeing is related to the model's grid size and its scale, which, in conjunction with several other factors, determines its ability to predict handles of different sizes across the image.

Your image input size, divided by the stride of your feature maps within the network, helps determine the grid size. The model generates predictions for each grid cell. The stride for each scale differs, with the larger scales having smaller strides and the smaller scales having larger strides. Thus, the number of output boxes you are observing - 5670 - corresponds to the total number of grid cells across all scales.

The use of zero inputs during the export process serves to create a "blank slate" condition. This is done to ensure that no surplus information biases the model's exporting process. The output results, despite the varying backbones, are due to this feature of the export process.

When you run the model on actual images (or non-zero inputs), you get a different number of boxes because YOLOv8 models can adaptively predict different numbers of boxes for different inputs, which fits with the principle of anchor-free models.

As for the applicability of this process; yes, this way of exporting and inferring does not impact the model's usability, including its conversion to TensorRT (TRT). The number of output boxes doesn't affect the model's capability to perform detection tasks. The model will correctly suppress low-confidence detections and structure the outputs based on the real data it receives during inference.

I hope this helps clarify your observations and questions about how the number of boxes is determined during ONNX export and inference in YOLOv8. Please feel free to reach out if you have further questions.

**Comment by weiss-israel** [comment]
@glenn-jocher Thank you.
Regarding your sentence for TRT inference: ` The number of output boxes doesn't affect the model's capability to perform detection tasks. The model will correctly suppress low-confidence detections and structure the outputs based on the real data it receives during inference.`
I can't find affirmation to that in the code- when exporting the model to onnx and to TRT via `ultralytics` code, there isn't any kind of suppression of low-confidence detection outputs- neither by thresholding nor nms. Can you elaborate regarding that / show reference from ultralytics code?
It seems to me that since there isn't any kind of postprocess, this also contributes to the constant number of detection boxes when supplying a constant zeros input for onnx export.
