### ISSUE TITLE
 E  FATAL EXCEPTION: main                                                                                                     Process: com.example.a1, PID: 22043                                                                                                     java.lang.IllegalArgumentException: Cannot copy to a TensorFlowLite tensor (inputs_0) with 4915200 bytes from a Java Buffer with 1228800 bytes.

### ISSUE THREAD

**Issue by skumbler** [ultralytics/ultralytics#3783]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

 E  FATAL EXCEPTION: main
                                                                                                    Process: com.example.a1, PID: 22043
                                                                                                    java.lang.IllegalArgumentException: Cannot copy to a TensorFlowLite tensor (inputs_0) with 4915200 bytes from a Java Buffer with 1228800 bytes.
![sds](https://github.com/ultralytics/ultralytics/assets/76587149/c36b9464-fbc1-4b86-b448-4ccc82579225)

### Environment

Ultralytice 3.8.0.114
python3.11.0
android studio latest
gradle 3.7
tensorflow lite  2.13

### Minimal Reproducible Example

        predict.setOnClickListener(v -> {
            if (bitmap != null) {
                // Preprocess the input image
                Bitmap resizedImage = Bitmap.createScaledBitmap(bitmap, 640, 640, true);
                TensorImage inputImage = TensorImage.fromBitmap(resizedImage);

                // Create the output tensor buffer
                TensorBuffer outputBuffer = TensorBuffer.createFixedSize(new int[]{1, 6}, DataType.FLOAT32);

                // Run inference
                tflite.run(inputImage.getBuffer(), outputBuffer.getBuffer());

                // Get the predicted class and confidence
                float[] outputArray = outputBuffer.getFloatArray();
                String[] classNames = {"Arborio", "Basmati", "Invalid_Image", "Ipsala", "Jasmine","Karacadag"};
                int predictedClassIndex = argmax(outputArray);
                String predictedClass = classNames[predictedClassIndex];
                float confidence = outputArray[predictedClassIndex];

                // Display the predicted result
                String predictionText = "Predicted Class: " + predictedClass + "\nConfidence: " + confidence;
                tv.setText(predictionText);
            } else {
                Toast.makeText(requireContext(), "Please select an image first.", Toast.LENGTH_SHORT).show();
            }
        });

        return view;
    }

    private MappedByteBuffer loadModelFile() throws IOException {
        AssetFileDescriptor fileDescriptor = requireContext().getAssets().openFd("model16.tflite");
        FileInputStream inputStream = new FileInputStream(fileDescriptor.getFileDescriptor());
        FileChannel fileChannel = inputStream.getChannel();
        long startOffset = fileDescriptor.getStartOffset();
        long declaredLength = fileDescriptor.getDeclaredLength();
        return fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffset, declaredLength);
    }

    private int argmax(float[] array) {
        int maxIndex = 0;
        for (int i = 1; i < array.length; i++) {
            if (array[i] > array[maxIndex]) {
                maxIndex = i;
            }
        }
        return maxIndex;
    }
}

### Additional

i convert yolov8 custome classification model into model16.tflite with imgsz=640
but when i integrate in android studio it give me logcat error and crashing my application 
i am doing myFYP i am a beginner please help i am stuck here last 3 days still no solution thats why i am here

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by skumbler** [comment]
![uuusvd](https://github.com/ultralytics/ultralytics/assets/76587149/a8df7871-e3cc-415a-b7b9-e8b8c52a2864)

my model details if input

**Comment by glenn-jocher** [comment]
@skumbler 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
