### ISSUE TITLE
export ncnn PNNX bug

### ISSUE THREAD

**Issue by liuzimo** [ultralytics/ultralytics#3786]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

![image](https://github.com/ultralytics/ultralytics/assets/25811500/89c4eba5-c5fb-466f-928b-513781887cdc)
![image](https://github.com/ultralytics/ultralytics/assets/25811500/4bd988f1-2403-4a8d-919b-653c69f46afa)

### Environment

Ultralytics YOLOv8.0.136  Python-3.8.16 torch-1.12.1+cu116 CPU (12th Gen Intel Core(TM) i5-12400F)

### Minimal Reproducible Example

![image](https://github.com/ultralytics/ultralytics/assets/25811500/b82c7ac8-6a64-410e-af17-9f43bbd848dd)

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@liuzimo 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

<img width="853" alt="Screenshot 2023-07-17 at 13 35 18" src="https://github.com/ultralytics/ultralytics/assets/26833433/80db75d3-629a-46a8-8a26-8fadb424c198">

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Chikage0o0** [comment]
Obviously, simply adding the exe doesn't solve the problem, it breaks linux support.

**Comment by glenn-jocher** [comment]
@Chikage0o0 hi there, 

Thanks for the feedback! You're right, simply adding an executable doesn't necessarily solve the issue, especially when it comes to cross-platform support.

In the case of the Linux operating system, we have to take different steps to ensure compatibility. For example, we might need to build from source to ensure compatibility with different Linux distributions. This, however, makes the usage and installation process more complicated compared to just adding an executable.

In YOLOv8, we strive for a balance between ease of use and support for different environments. We're continually working on enhancing cross-platform support and appreciate your patience during this process. Please feel free to suggest any changes or improvements you think could help in maintaining this balance.

Thank you for bringing this to our attention and helping us improve YOLOv8!
