### ISSUE TITLE
The flops always be 0

### ISSUE THREAD

**Issue by niiish32x** [ultralytics/ultralytics#3798]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

why the flops in eval methods output always be 0?

### Additional

when i want get more information about the model, such as yolov8x.pt. I use val method  on coco128 yaml, but i always find that the flops results is 0.

**Comment by glenn-jocher** [comment]
@niiish32x hello,

Thank you for reaching out and bringing up this issue. The FLOPs (Floating Point Operations Per Second) value is a measure of a model's complexity and computational needs. If you're seeing the FLOPS value as 0 in eval mode, it might be due to two scenarios. 

First, it could be possible that the model is not being properly parsed and evaluated by the FLOPs counter being used. This could be caused by updates in the pytorch version or model structure that are not yet supported by the FLOPs counter. 

Second, there might not be any computations performed during inference (eval mode), especially if no data is passed through the model.

I recommend checking and ensuring that the data is indeed being passed through the model during the eval operation. If data is being passed through and it still shows FLOPs as 0, this might indicate a potential issue with the FLOPs counter.

Our team will further investigate this matter. We appreciate your patience and understanding.

Best Regards,

Glenn Jocher
