### ISSUE TITLE
Swapped labels when using whitespaces

### ISSUE THREAD

**Issue by MichaelRinger** [ultralytics/ultralytics#3812]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hello,
I encountered a small bug. In one of my roboflow datasets I have the classes "cream" and "cream cheese". The training of a yolov8 (roboflow yolov8 dataset format) model went fine. But when I made predictions the labels where swapped for the detected objects. After looking at the validation output of the training I saw that the labels where already swapped during training. I dont know If snake case is required for naming labels, but it doesnt seem like it because roboflow or the ultralytics yolov8 trainer didnt catch that.
After I put the labels in snake case solved the problem.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MichaelRinger hello,

Thank you for bringing this issue to our attention.

When making predictions, Ultralytics' YOLOv8 solution does not directly have control over the labels since it operates based on the labels given during training. It seems the swapping issue might be due to the presence of whitespaces in your labels - "cream" and "cream cheese". This might have confused the model during the training, effectively swapping the labels.

In response to your finding, I can confirm that using snake case for multi-word labels (i.e., "cream_cheese" instead of "cream cheese") is indeed a good practice when working with Ultralytics' YOLOv8 and other YOLO versions. This can help to prevent potential issues relating to whitespace characters in the labels.

I'm glad to hear that reverting to snake case solved the issue for you. In the future, to avoid such confusion, it's recommended to use single-word labels when possible, or use snake case for multi-word labels. This should ensure that the labels are not misinterpreted leading to swapping or other potential issues. 

Your experience will benefit others in the community who may encounter a similar issue. 

Thanks again for using Ultralytics’ YOLOv8 and contributing to the community!

Best,
Glenn
