### ISSUE TITLE
Tracking ID changes due to overlap

### ISSUE THREAD

**Issue by drakshayanidesai** [ultralytics/ultralytics#3823]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

When two person one hiding behind the other then new tracking ID will be given when they move apart from each other with this model.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by xaristeidou** [comment]
Well that depends on the tracking itself as a procedure. Maybe it is possible to try avoid it by changing some of the tracking arguments. Just a few second ago in another issue I did notice someone mention that he used the following tracking arguments: 

tracker_type: bytetrack
track_high_thresh: 0.5
track_low_thresh: 0.1
new_track_thresh: 0.6
track_buffer: 30
match_thresh: 0.9

Maybe there is a possibility to be able to change these arguments, I don't know how yet. Maybe match_thresh or track_buffer can avoid this event.

**Comment by glenn-jocher** [comment]
@xaristeidou thank you for bringing attention to this, and I appreciate your input. 

You're right, the tracking performance often depends on the chosen parameters. Adjusting parameters like `match_thresh`, `track_buffer`, `track_high_thresh`, `track_low_thresh`, etc. can indeed influence the tracking outcome and might possibly help mitigate the issue you're facing of changing IDs due to overlaps.

For instance, increasing `match_thresh` could make ID assignments more rigorous, potentially reducing ID changes. Similarly, altering `track_buffer` might impact how long a tracked object is kept in memory before being removed, which could also influence ID stability.

The actual impact, though, will strongly depend on the specific environment, dataset, and use-case and might require some experimentation to find the right balance. 

Currently, I am not in the position to suggest any specific changes to these parameters, as their optimal setting can strongly depend on the aforementioned environmental factors. However, your insights are certainly valuable for the community as a pointer where to look at when encountering similar issues.

Again, thank you for your helpful observation, and let's keep exploring ways to refine and optimize our YOLOv8 models for better performance and accuracy.

**Comment by drakshayanidesai** [comment]
Thanks

On Thu, 20 Jul 2023 00:42:36 +0530 Glenn Jocher  wrote
>
@xaristeidou thank you for bringing attention to this, and I appreciate your input.
You're right, the tracking performance often depends on the chosen parameters. Adjusting parameters 
like match_thresh, track_buffer, track_high_thresh, track_low_thresh, etc. can indeed influence the 
tracking outcome and might possibly help mitigate the issue you're facing of changing IDs due to 
overlaps.
For instance, increasing match_thresh could make ID assignments more rigorous, potentially reducing ID 
changes. Similarly, altering track_buffer might impact how long a tracked object is kept in memory 
before being removed, which could also influence ID stability.
The actual impact, though, will strongly depend on the specific environment, dataset, and use-case and 
might require some experimentation to find the right balance.
Currently, I am not in the position to suggest any specific changes to these parameters, as their 
optimal setting can strongly depend on the aforementioned environmental factors. However, your insights 
are certainly valuable for the community as a pointer where to look at when encountering similar 
issues.
Again, thank you for your helpful observation, and let's keep exploring ways to refine and optimize our 
YOLOv8 models for better performance and accuracy.

—
>Reply to this email directly, view it on GitHub, or unsubscribe.
>You are receiving this because you were mentioned.Message ID: 



--=_308a83e23330f2f7cb78891914064437
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset="UTF-8"

Thanks<br />
<br />
On Thu, 20 Jul 2023 00:42:36 +0530 Glenn Jocher ***@***.***> =
wrote<br />
><br />
@xaristeidou thank you for bringing attention to this, and I appreciate you=
r input.<br />
You're right, the tracking performance often depends on the chosen paramete=
rs. Adjusting parameters <br />
like match_thresh, track_buffer, track_high_thresh, track_low_thresh, etc. =
can indeed influence the <br />
tracking outcome and might possibly help mitigate the issue you're facing o=
f changing IDs due to <br />
overlaps.<br />
For instance, increasing match_thresh could make ID assignments more rigoro=
us, potentially reducing ID <br />
changes. Similarly, altering track_buffer might impact how long a tracked o=
bject is kept in memory <br />
before being removed, which could also influence ID stability.<br />
The actual impact, though, will strongly depend on the specific environment=
, dataset, and use-case and <br />
might require some experimentation to find the right balance.<br />
Currently, I am not in the position to suggest any specific changes to thes=
e parameters, as their <br />
optimal setting can strongly depend on the aforementioned environmental fac=
tors. However, your insights <br />
are certainly valuable for the community as a pointer where to look at when=
 encountering similar <br />
issues.<br />
Again, thank you for your helpful observation, and let's keep exploring way=
s to refine and optimize our <br />
YOLOv8 models for better performance and accuracy.<br />
<br />
=E2=80=94<br />
>Reply to this email directly, view it on GitHub, or unsubscribe.<br />
>You are receiving this because you were mentioned.Message ID: <br />
***@***.***><br />
<br />
<br>
--=_308a83e23330f2f7cb78891914064437--

**Comment by glenn-jocher** [comment]
Dear @drakshayanidesai,

Thank you for your valuable input. You're indeed correct. The performance of the tracking often hinges on the chosen parameters. Tweaking parameters like match_thresh, track_buffer, track_high_thresh, track_low_thresh, and so forth can indeed influence the tracking results and it may potentially alleviate the issue you're encountering regarding the changing of IDs due to overlaps. 

For example, if we increase match_thresh, it might make ID assignments more stringent and reduce ID changes. Similarly, modifying track_buffer could affect the duration a tracked object is stored in memory prior to being cleared, which could also influence ID consistency. 

However, one must keep in mind that the actual influence of these parameters will greatly depend on the specific environment, dataset and use-case. Therefore, some trials and experimentation might be needed to fine-tune these settings for the best outcomes.

At the moment, I'm unable to suggest any specific modifications to these parameters, as their optimal settings can noticeably depend on the factors mentioned above. Nevertheless, your insights are indeed extremely helpful for the community and act as a guide to direct attention while dealing with similar issues.

Once again, thank you for your astute observation. Let's continue our efforts into refining and optimizing our YOLOv8 models for superior performance and precision.

**Comment by bibhutibhusan89** [comment]
```
from IPython import display
import cv2
display.clear_output()

import supervision as sv
print("supervision.__version__:", sv.__version__)

from ultralytics import YOLO, solutions
#model = YOLO("/Users/bibhutibhusan/NMDC_Train_Detection/detect_track_wagons/model/kaggle/working/runs/detect/train/weights/best.pt")

model = YOLO("/Users/bibhutibhusan/NMDC_Train_Detection/detect_track_wagons/model/kaggle 2/working/runs/detect/train/weights/best.pt")

# dict maping class_id to class_name
CLASS_NAMES_DICT = model.model.names
All_CLASS_IDS = list(CLASS_NAMES_DICT.keys())
# the class names we have chosen
track_class = ['Engine','Wagons']

# class ids matching the class names we have chosen
track_class_ids = [
    {value: key for key, value in CLASS_NAMES_DICT.items()}[class_name]
    for class_name
    in track_class
]

non_track_class_ids = new_list = [i for i in All_CLASS_IDS if i not in track_class_ids]
print(track_class_ids)
print(non_track_class_ids)

import supervision as sv
import numpy as np

# settings
# LINE_START = sv.Point(0 + 50, 1500)
# LINE_END = sv.Point(3840 - 50, 1500)

LINE_START, LINE_END = sv.Point(x=0, y=1080), sv.Point(x=3840, y=1080)


#SOURCE_VIDEO_PATH = "./data/20240918100804_5434.mp4"
SOURCE_VIDEO_PATH = "./data/20240918100804_5434.mp4"
TARGET_VIDEO_PATH = f"./results/20240918100804_5434_annotated.mp4"
normal_image_store_path = "./results/frames/"
annotated_image_store_path = "./results/annotated_images/"
sv.VideoInfo.from_video_path(SOURCE_VIDEO_PATH)

# create BYTETracker instance
byte_tracker = sv.ByteTrack(
    track_activation_threshold=0.25,
    lost_track_buffer=30,
    minimum_matching_threshold=0.8,
    frame_rate=30,
    minimum_consecutive_frames=3)

# byte_tracker = sv.ByteTrack(
#     track_activation_threshold=0.25,
#     lost_track_buffer=30,
#     minimum_matching_threshold=0.8,
#     frame_rate=59,
#     minimum_consecutive_frames=3)


byte_tracker.reset()
#print(byte_tracker)

# create VideoInfo instance
video_info = sv.VideoInfo.from_video_path(SOURCE_VIDEO_PATH)

# create frame generator
generator = sv.get_video_frames_generator(SOURCE_VIDEO_PATH)

# create LineZone instance, it is previously called LineCounter class
line_zone = sv.LineZone(start=LINE_START, end=LINE_END)

# create instance of BoxAnnotator, LabelAnnotator, and TraceAnnotator
box_annotator = sv.BoxAnnotator(thickness=4)
label_annotator = sv.LabelAnnotator(text_thickness=2, text_scale=1.5, text_color=sv.Color.BLACK,
                                    text_position=sv.Position.CENTER)
label_annotator2 = sv.LabelAnnotator(text_thickness=1, text_scale=1, text_color=sv.Color.BLACK,
                                    text_position=sv.Position.BOTTOM_CENTER)
trace_annotator = sv.TraceAnnotator(thickness=4, trace_length=200)

# create LineZoneAnnotator instance, it is previously called LineCounterAnnotator class
line_zone_annotator = sv.LineZoneAnnotator(thickness=4, text_thickness=4, text_scale=2)
# define call back function to be used in video processing
def callback(frame: np.ndarray, index: int) -> np.ndarray:
    # model prediction on single frame and conversion to supervision Detections
    results = model.track(frame, verbose=False)[0] ## imgsz = 800 as during training image was resized to 800
    detections = sv.Detections.from_ultralytics(results)
    # only consider class id from selected_classes define above
    #print(detections.class_id)
    detections1 = detections[np.isin(detections.class_id, track_class_ids)]
    detections2 = detections[np.isin(detections.class_id, non_track_class_ids)]
    #print(detections1, detections2)

    # tracking detections
    detections3 = byte_tracker.update_with_detections(detections1)
    #detections4 = byte_tracker.update_with_detections(detections2)
    #print("detection 3 4")
    #print(detections3)
    labels_d3 = []
    names_d3 = []
    # for confidence, class_id, tracker_id in zip(detections.confidence, detections.class_id, detections.tracker_id):
    #     labels.append(f"#{tracker_id} {model.model.names[class_id]} {confidence:0.2f}")
    #     names.append(model.model.names[class_id])

    for confidence, class_id, tracker_id in zip(detections3.confidence, detections3.class_id, detections3.tracker_id):
        labels_d3.append(f"#{tracker_id} {model.model.names[class_id]} {confidence:0.2f}")
        names_d3.append(model.model.names[class_id])

    labels_d4 = []
    names_d4 = []

    for confidence, class_id in zip(detections2.confidence, detections2.class_id):
        labels_d4.append(f"#{model.model.names[class_id]} {confidence:0.2f}")
        names_d4.append(model.model.names[class_id])
    
    if(len(labels_d3) > 0):
        print(labels_d3)
        print(names_d3)

    annotated_frame = frame.copy()
    # annotated_frame = trace_annotator.annotate(
    #     scene=annotated_frame, detections=detections)
    # annotated_frame = box_annotator.annotate(
    #     scene=annotated_frame, detections=detections)
    # annotated_frame = label_annotator.annotate(
    #     scene=annotated_frame, detections=detections, labels=labels)

    annotated_frame = trace_annotator.annotate(
        scene=annotated_frame, detections=detections3)
    # annotated_frame = trace_annotator.annotate(
    #     scene=annotated_frame, detections=detections2)
    
    annotated_frame = box_annotator.annotate(
        scene=annotated_frame, detections=detections3)
    annotated_frame = box_annotator.annotate(
        scene=annotated_frame, detections=detections2)

    annotated_frame = label_annotator.annotate(
        scene=annotated_frame, detections=detections3, labels=labels_d3)
    annotated_frame = label_annotator2.annotate(
        scene=annotated_frame, detections=detections2, labels=labels_d4)


    # update line counter
    line_zone.trigger(detections3)
    # return frame with box and line annotated result
    annotated_frame = line_zone_annotator.annotate(annotated_frame, line_counter=line_zone)
    #print(annotated_frame)
    #if(len(labels_d3) > 0):
        #cv2.imwrite(normal_image_store_path + str(index) + ".jpg", frame)
        #cv2.imwrite(annotated_image_store_path + str(index) + ".jpg", annotated_frame)
    return annotated_frame

# process the whole video
sv.process_video(
    source_path = SOURCE_VIDEO_PATH,
    target_path = TARGET_VIDEO_PATH,
    callback=callback
)
```
```

**Comment by glenn-jocher** [comment]
Thank you for providing the detailed code and explanation of your issue. From your description, it seems that the ByteTrack tracker is struggling with consistent ID assignment, leading to duplicate counts for the same wagon. This could be due to rapid occlusions or tracker parameter misalignment with your use case.

To address this:
1. **Adjust Tracker Parameters**: Experiment further with `track_activation_threshold`, `lost_track_buffer`, and `minimum_matching_threshold`. For example, increasing `lost_track_buffer` may help maintain IDs during brief occlusions, and a higher `minimum_matching_threshold` can make ID assignment more strict.
2. **Use Track History**: Implementing a mechanism to store track IDs that have already crossed the line (e.g., in `line_zone.trigger`) can prevent duplicate counting.
3. **Custom Post-Processing**: After tracking, you can filter detections using spatial proximity or temporal continuity to ensure the same wagon isn’t counted multiple times.

If you’re still facing issues, consider simplifying the problem by testing on a shorter video segment to isolate the root cause. For reference, [Ultralytics Track Documentation](https://docs.ultralytics.com/modes/track/) might offer additional insights into tuning parameters effectively. Let us know if you need further assistance!
