### ISSUE TITLE
save_txt and save_crop modification issues

### ISSUE THREAD

**Issue by ChangX116** [ultralytics/ultralytics#3845]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Instead of saving as multiple txt files, I want to save the box information in the same txt using save_txt=True and add the information that is currently the number of frames.
In addition, I want to use crop to save the images of boxes but I don't want to save every frame, which will take up too much disk space, and I want to only save 5 images of the same time interval with the same ID.
I want to modify the code or write a new loop to implement these functions, but I don't know how, I know these two functions in the result file, but I can't find where model.track called these two functions .

### Additional

this is my code
model = YOLO(r"E:/runs/detect/train2/weights/best.pt")
results=model.track(source="D01_20230526095604.mp4", show=True, save_txt=True,save_crop=True tracker="botsort.yaml",stream=True)

for result in results:
    pass

**Comment by glenn-jocher** [comment]
@ChangX116 hello,

To change the behavior of `save_txt` to write all bounding box information into a single .txt file, you would need to modify the code in the results.py file. Currently, the design is to save individual .txt files for each image processed. To save all results in a single file, you may change the file writing process in the `save_txt` function to append the new data to an existing file rather than creating a new one each time.

On saving crops, currently, the framework saves a cropped image for every detection made by the model. If you'd like to change this, you would need to implement a kind of 'frame skip' function to only save on every 5th frame or use a timestamp on your video frames to save crops at specific time intervals.

As for the Model.track() method, these functions are not directly called inside model.track() but these are instead called inside the Results object that is used to process and store the outputs of the tracking. You will want to review the relevant sections of the Results object code to understand and modify as per your requirements.

Remember to take backups before making any changes and thoroughly test your modifications. If the standard YOLOv8 functions are unable to satisfy your requirements, modifications of the underlying code will always carry risks and may require some deep understanding of the codebase.

Best regards,
Glenn
