### ISSUE TITLE
CUDA error: an illegal memory access was encountered error when inference

### ISSUE THREAD

**Issue by darouwan** [ultralytics/ultralytics#3848]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I meet the following error when inference for several hours on K8S, and even initial the model again in exept clause cannot help:
```
2023-07-13 01:27:18.636 | ERROR | yolov8_detection:inference:85 - CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by glenn-jocher** [comment]
@darouwan thank you for reaching out with your issue. The CUDA error you're experiencing is typically caused by accessing memory that is already freed or is out of bounds. This could be due to several reasons, such as an issue with a CUDA kernel, insufficient GPU memory, or a problem with tensor sizes during inference.

In your case, it's possible that continuously running inference for several hours is causing an issue with GPU memory management. It might be helpful to monitor the GPU memory usage over time during inference to identify any potential memory leaks.

As suggested in the error message, you could also try launching the CUDA kernels with the environment variable CUDA_LAUNCH_BLOCKING=1. Although this might slow down the computation, it enables synchronous execution and can help identifying the operation that's causing the problem. Additionally, you could try compiling with `TORCH_USE_CUDA_DSA` to enable device-side assertions as this might provide a clearer idea of what's causing the issue.

Lastly, to help us better assist you, could you provide more details of your setup, such as the exact command you're using to run the inference, the version of YOLOv8 you're using, your GPU specifications, and the version of your CUDA and PyTorch?

Looking forward to resolving this issue for you soon.

**Comment by darouwan** [comment]
@glenn-jocher  Thanks. I have set CUDA_LAUNCH_BLOCKING=1 in env variable and continue to monitor it.

**Comment by glenn-jocher** [comment]
Hello @darouwan,

It's great to hear that you're taking the CUDA_LAUNCH_BLOCKING=1 approach for error tracking. This setup should provide a clearer understanding of where the issue might lie.

As for YOLOv8 model serving, a common practice is to establish a REST API using a framework like Flask or FastAPI which will accept image data, perform inference using the model, and then return the results.

When preparing your model for serving, it is crucial to conduct proper warm-up and cool-down procedures for your CUDA context. This will help to manage GPU resources effectively and avoid memory errors over long periods of inference.

Do consider embedding checks for GPU memory usage within your model-serving pipeline, as this can alert you to any memory leaks that might be creeping in over time.

Also, utilizing efficient batching strategies can help optimize inference time and resource allocation. The choice of batch size might vary depending on the GPU memory. Bigger batches are often faster on a per-image basis, but they require more memory.

Remember, each deployment environment will have different constraints and requirements, so the strategies might vary from case to case. Monitoring your environment and tweaking accordingly will help ensure you deliver a robust solution.

If you encounter any other issues or need further clarification, don't hesitate to let us know. We're here to help.

**Comment by darouwan** [comment]
I have set the CUDA_LAUNCH_BLOCKING=1, but no detailed message can be given in error message.  I am using FastAPI to provide model restful service, and use nvidia-smi to monitor the GPU usage, it looks everything is well. Whatever I use batch size = 1 or 10, this error continues happen. 
```
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/src/ultralytics/ultralytics/engine/model.py", line 254, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/usr/src/ultralytics/ultralytics/engine/predictor.py", line 195, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/usr/src/ultralytics/ultralytics/engine/predictor.py", line 246, in stream_inference
    with profilers[0]:
  File "/usr/src/ultralytics/ultralytics/utils/ops.py", line 39, in __enter__
    self.start = self.time()
  File "/usr/src/ultralytics/ultralytics/utils/ops.py", line 54, in time
    torch.cuda.synchronize()
  File "/opt/conda/lib/python3.10/site-packages/torch/cuda/__init__.py", line 688, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: misaligned address
```

![image](https://github.com/ultralytics/ultralytics/assets/2324213/e004dd02-cd06-4a3a-a332-139c1546e99d)

**Comment by glenn-jocher** [comment]
Hello @darouwan,

Thank you for the detailed report and providing your setup's detailed environment. Your issue appears to be related to CUDA memory alignment, often caused by the GPU trying to access a memory region that was not assigned or is out of its accessible boundary.

The "misaligned address" error may imply that PyTorch is trying to load or store data types whose natural alignment needs are not met. For example, CUDA requires that 2-byte half precision, 4-byte float or int32, 8-byte double or int64 data should be aligned to their size in memory. Any misalignment could result in hardware exceptions.

While it's difficult to pinpoint the exact cause for this without further information, a few common scenarios could lead to this problem. For example, running PyTorch versions not fully compatible with the installed CUDA version and outdated NVIDIA drivers.

From the stack trace you provided, it seems that the error is triggered at the point where `torch.cuda.synchronize()` is called. This function explicitly waits for all kernels in all streams on a CUDA device to complete. It could be that the synchronization call is made while a memory region is being accessed or modified, which could potentially cause a misaligned address error.

As part of the troubleshooting process, could you please check whether your setup follows the guidelines for compatibility between CUDA, PyTorch, and your NVIDIA Driver? For instance, PyTorch 2.0.1 could be incompatible with CUDA 12.0. You might want to consider using a pyTorch version that's explicitly compatible with CUDA 12.0.

Regarding your model serving setup with FastAPI, it's good to hear that GPU usage seems to be under control. In addition to setting `CUDA_LAUNCH_BLOCKING=1`, you might want to consider setting the `TORCH_CUDA_ALLOC_SYNC` environment variable to `1`. This will force PyTorch to synchronize on every CUDA memory allocation, which helps with debugging memory errors.

For continued tracking, please make sure to keep us updated on your situation as you continue your troubleshooting. We'll be glad to provide any assistance we can to get your model running smoothly.

**Comment by Mrgorlay** [comment]
I have encountered the same issue as well.What is the final and best solution? Thank you.
`RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.`

**Comment by glenn-jocher** [comment]
@Mrgorlay hello,

Thanks for reaching out and providing such detailed information about your issue. The error message "CUDA error: misaligned address" is typically an indicator that your PyTorch version is not fully compatible with the CUDA version you have installed. 

Can you please confirm whether your setup aligns with the compatibility guidelines between PyTorch, CUDA, and the NVIDIA driver? The misalignment issue can sometimes result from using incompatible versions of these software.

From the stack trace, it appears the error is raised when the `model.to(device)` operation is applied. This operation moves the model to the GPU device for accelerated computation. If there's an issue with your GPU setup (e.g., CUDA version, PyTorch compatibility), the error could be flagged here.

Furthermore, please make sure your GPU has enough memory to hold the model and perform the operations. Frequently, similar issues relate back to trying to allocate more memory than what is available on the device.

You can debug the CUDA kernel error by setting `CUDA_LAUNCH_BLOCKING=1`. This environment variable makes CUDA operations run synchronously, which helps in identifying which specific operation is causing the error.

If the issue persists, please provide us with additional details or updates on your situation so we can help you solve the problem more effectively.

**Comment by Mrgorlay** [comment]
thanks! After I used pip install  ultralytics to update the version,this problem did not appear  temporarily!

**Comment by Mrgorlay** [comment]
@glenn-jocher 

Thanks! I used pip install ultralytics to update the version,this problem did not appear temporarily!,

**Comment by glenn-jocher** [comment]
@Mrgorlay hello,

I'm glad to hear that updating the ultralytics package helped resolve your issue temporarily. This could be attributed to the updated compatibility with your specific system requirements in the newer version.

Moving forward, ensure you regularly update your packages to keep your environment stable and prevent further unexpected errors. If you do notice the issue reappearing or encounter a different problem, feel free to report it. We are here to help.

Thank you for your contributions to this project and the community. Your feedback plays a vital role in helping us improve YOLOv8!

Best regards.

**Comment by GoviSirma** [comment]
Hi @glenn-jocher 

ExternalError: CUDA error(700), an illegal memory access was encountered.
      [Hint: 'cudaErrorIllegalAddress'. The device encountered a load or store instruction on an invalid memory address. This leaves the process in an inconsistentstate and any further CUDA work will return 
the same error. To continue using CUDA, the process must be terminated and relaunched. ] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:272)
      [operator < reshape2 > error]
[2025-02-25 07:51:28,246] [ WARNING] detectFlds.py:59 - |Thread-2 (formFields)- Entered formFields method
[2025-02-25 07:51:28,247] [ WARNING] detectFlds.py:67 - |Thread-2 (formFields)- started paddleocr extraction
[2025-02-25 07:51:28,315] [   ERROR] detectFlds.py:82 - |Thread-2 (formFields)- Error in formFields: (External) CUDA error(700), an illegal memory access was encountered. 
  [Hint: 'cudaErrorIllegalAddress'. The device encountered a load or store instruction on an invalid memory address. This leaves the process in an inconsistentstate and any further CUDA work will return the 
same error. To continue using CUDA, the process must be terminated and relaunched. ] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:265)

Iam getting this issue many times. 


![Image](https://github.com/user-attachments/assets/8218926b-a432-428b-9dd8-46e3a3c4f2cd)

**Comment by glenn-jocher** [comment]
Hello @GoviSirma, 

The CUDA error 700 you're encountering typically indicates an invalid memory access in GPU operations. Since the error stack trace points to PaddlePaddle (`/paddle/paddle/...`), this appears related to your PaddleOCR implementation rather than Ultralytics YOLO. 

To resolve:
1. Ensure your PaddlePaddle installation matches your CUDA version exactly
2. Verify no memory conflicts between YOLO and PaddleOCR in shared GPU usage
3. Monitor GPU memory with `nvidia-smi -l 1` during execution to identify leaks

For PaddlePaddle-specific support, we recommend consulting their [documentation](https://www.paddlepaddle.org.cn/documentation/docs/en/guides/index_en.html) or GitHub issues. Let us know if you can reproduce this error in standalone YOLO operations! 🛠️
