### ISSUE TITLE
Yolov8 on cpu

### ISSUE THREAD

**Issue by karunakr** [ultralytics/ultralytics#3853]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

I am planning to use CPU to run yolov8 inference. I can see that its taking around 2.8 seconds per frame when running in Azure Standard_D4as_v5.

Is there a way I can optimize the model or convert the model to improve the performance of inference?

Thanks
Karunakar

**Comment by glenn-jocher** [comment]
@karunakr hi Karunakar,

Running YOLOv8 inference on a CPU can be slower than on a GPU due to the high complexity of the model, the large amount of layers, and the inherent parallel processing capabilities of a GPU that a CPU lacks. The 2.8 seconds per frame that you're seeing is likely due to these factors.

There are a few strategies you might consider to improve the performance:

1. **Model Optimization**: You can optimize the model itself by using a smaller version of YOLOv8 if your application allows for it. Smaller versions would have less computational overhead, therefore potentially speeding up inference times.

2. **Quantization**: Quantization can also be an option to reduce the size of the model and speed up inference. This converts the weights in the model from floating point values to integers, which reduces memory and computation demands but might impact the accuracy.

3. **Model Pruning**: This involves zeroing out some of the weights in the model, thus reducing the number of operations the CPU must carry out. Pruned models are usually faster but may suffer in terms of accuracy.

Please bear in mind that optimization involves a careful balance between speed and accuracy. It might be worthwhile experimenting with these techniques to find which works best for your specific use case. Let me know how you progress, or if you need further guidance.

Best regards,

Glenn Jocher

**Comment by karunakr** [comment]
Thanks @glenn-jocher 

How about converting model to open VINO. Would that help in improving performance without compromising on accuracy.

Thanks
Karunakar

**Comment by glenn-jocher** [comment]
@karunakr Hi Karunakar,

Yes, converting the model to OpenVINO format can potentially improve the inference speed on CPUs. OpenVINO, developed by Intel, is specially designed to accelerate deep learning workloads on Intel hardware (including CPUs).

The OpenVINO toolkit includes a Model Optimizer that can take trained models and optimise them for performance, while keeping the loss in precision to a minimum. It achieves this by performing certain transformations and optimizations on the model graph, such as the removal of layers not needed for inference, fusion of certain layers, and so on.

While it is certainly a viable option to consider, please note that the actual amount of speedup you get can depend on many factors and there may still be some minimal loss in model accuracy due to the optimization process.

Best regards,

Glenn Jocher

**Comment by mariswarycharan** [comment]
how to run yolov8 model with less memory utilisation of CPU for inferening the model

**Comment by glenn-jocher** [comment]
Hi @mariswarycharan,

To reduce memory utilization while running YOLOv8 inference on a CPU, consider the following strategies:

1. **Use a Smaller Model**: Opt for a smaller version of YOLOv8, such as YOLOv8n (nano), which requires less memory.
2. **Quantization**: Apply FP16 or INT8 quantization to reduce the model size and memory footprint.
3. **Batch Processing**: Process images in batches to better manage memory usage.
4. **OpenVINO Conversion**: Convert the model to OpenVINO format for optimized performance on Intel CPUs.

These steps can help you achieve more efficient memory usage during inference. If you need further assistance, feel free to ask! 😊

**Comment by mariswarycharan** [comment]
i am running yolov8n(nano) model in jetson nano , while running two yolov8n(nano) model   in jetson nano ,  jetson nano get hanged on , one model is running fine no problem , when i execute second model it get hanged on

CPU utilization is 100 % 

how to reduce it

**Comment by glenn-jocher** [comment]
Hi @mariswarycharan,

Running two YOLOv8n models simultaneously on a Jetson Nano can indeed be quite demanding, leading to high CPU utilization and system hangs. Here are a few suggestions to help manage the load:

1. **Optimize Model Execution**: Consider running one model at a time or staggering their execution to avoid overloading the CPU.
2. **Quantization**: Apply FP16 or INT8 quantization to reduce the computational load and memory usage.
3. **Model Pruning**: Prune the models to reduce their size and complexity, which can help lower CPU usage.
4. **Use OpenVINO**: If possible, convert the models to OpenVINO format for optimized performance on Intel hardware.

These steps should help in reducing CPU utilization and improving the overall performance on your Jetson Nano. If you need further assistance, feel free to ask! 😊

**Comment by mariswarycharan** [comment]
thank you 👍👍

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions or need further assistance, feel free to reach out. Happy coding! 😊

**Comment by Avv22** [comment]
Hello Glenn,

Is there any configuratiuon or code to write to run it on CPU please?

**Comment by glenn-jocher** [comment]
Hi @Avv22,

To run YOLOv8 on a CPU, you can specify the `device` parameter in your code. Here's a quick example:

### Python
```python
from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n.pt")

# Run inference on CPU
results = model.predict(source="path/to/image.jpg", device="cpu")
```

### CLI
```bash
yolo predict model=yolov8n.pt source=path/to/image.jpg device=cpu
```

This will ensure that the model runs on the CPU instead of the GPU. If you encounter any issues, please make sure you are using the latest versions of `torch` and `ultralytics`. If the problem persists, provide a minimum reproducible example so we can investigate further. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions! 😊

**Comment by Avv22** [comment]
Thanks Glenn!

What if I have a bunch of images as the one below is my code for GPU version:

class YOLOModelWrapper(mlflow.pyfunc.PythonModel):
    def __init__(self):
        # Load the YOLO model
        self.model = YOLO("yolo/best.pt")

    def predict(self, context, model_input):
        print("Running prediction")
        image_paths = model_input["images"]
        images = [cv2.imread(image_path) for image_path in image_paths]
        for i, image in enumerate(images):
            if image is None:
                raise ValueError(f"Image at path {image_paths[i]} could not be read correctly. Please check the image path.")
            print(f"Image {i}: shape={image.shape}, dtype={image.dtype}")

        results = self.model(images)

        output = []
        for result in results:
            output.append({
                "boxes": result.boxes.xyxy.tolist(),
                "scores": result.boxes.conf.tolist(),
                "classes": result.boxes.cls.tolist()
            })
        print("Prediction completed")
        return output

How run the above on CPU please given I might have a set of images not just one?

**Comment by glenn-jocher** [comment]
Hi @Avv22,

To run your YOLO model on a CPU for a batch of images, you can modify your `YOLOModelWrapper` class to specify the `device` parameter as `"cpu"`. Here's how you can adjust your code:

### Updated `YOLOModelWrapper` Class
```python
class YOLOModelWrapper(mlflow.pyfunc.PythonModel):
    def __init__(self):
        # Load the YOLO model and specify the device as CPU
        self.model = YOLO("yolo/best.pt")

    def predict(self, context, model_input):
        print("Running prediction")
        image_paths = model_input["images"]
        images = [cv2.imread(image_path) for image_path in image_paths]
        for i, image in enumerate(images):
            if image is None:
                raise ValueError(f"Image at path {image_paths[i]} could not be read correctly. Please check the image path.")
            print(f"Image {i}: shape={image.shape}, dtype={image.dtype}")

        # Run inference on CPU
        results = self.model.predict(images, device="cpu")

        output = []
        for result in results:
            output.append({
                "boxes": result.boxes.xyxy.tolist(),
                "scores": result.boxes.conf.tolist(),
                "classes": result.boxes.cls.tolist()
            })
        print("Prediction completed")
        return output
```

### Main Function
No changes are needed in your main function. It will remain the same:
```python
def main():
    # Initialize the YOLO model wrapper
    yolo_model_wrapper = YOLOModelWrapper()

    # Initialize the MLFlow logger
    mlflow_logger = MLFlowLogger(model_wrapper=yolo_model_wrapper, artifact_path="yolo_model")
```

### Key Changes
- Added `device="cpu"` in the `self.model.predict` call to ensure the inference runs on the CPU.

This should allow you to run your YOLO model on a CPU for a batch of images. If you encounter any issues, please ensure you are using the latest versions of the `ultralytics` and `torch` packages. If the problem persists, providing a minimum reproducible example can help us diagnose the issue more effectively. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions! 😊

**Comment by Rizwanali324** [comment]
> Hi [@Avv22](https://github.com/Avv22),
> 
> To run YOLOv8 on a CPU, you can specify the `device` parameter in your code. Here's a quick example:
> 
> ### Python
> from ultralytics import YOLO
> 
> # Load a model
> model = YOLO("yolov8n.pt")
> 
> # Run inference on CPU
> results = model.predict(source="path/to/image.jpg", device="cpu")
> ### CLI
> yolo predict model=yolov8n.pt source=path/to/image.jpg device=cpu
> This will ensure that the model runs on the CPU instead of the GPU. If you encounter any issues, please make sure you are using the latest versions of `torch` and `ultralytics`. If the problem persists, provide a minimum reproducible example so we can investigate further. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).
> 
> Feel free to reach out if you have any more questions! 😊



can i use Neural Magic's DeepSparse for  it and any code for it instead of cli

**Comment by glenn-jocher** [comment]
Hi @Rizwanali324,  

Yes, you can use Neural Magic's DeepSparse for CPU-optimized YOLOv8 inference. Here's a Python example:  

```python
from deepsparse import Pipeline

# Load YOLOv8 ONNX model (export via model.export(format="onnx"))
model_path = "yolov8n.onnx"  
pipeline = Pipeline.create(task="yolov8", model_path=model_path)
results = pipeline(images=["image.jpg"])
```

For full implementation details, see the [Ultralytics-Neural Magic integration documentation](https://docs.ultralytics.com/integrations/neural-magic/). Requires `pip install deepsparse[yolov8]` and an ONNX exported model.
