### ISSUE TITLE
Can't get attribute 'NoneType' on  in torch_safe_load

### ISSUE THREAD

**Issue by cfrancois7** [ultralytics/ultralytics#3867]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

This bug happens after the update of ultralytics from 8.0.121 to  8.0.139.
(reproductible with pip install --force)

```
AttributeError                            Traceback (most recent call last)
Cell In[6], line 1
----> 1 model = YOLO(MODEL_PATH)

File [~/.anaconda3/envs/gael/lib/python3.9/site-packages/ultralytics/engine/model.py:106](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/machine_learning/projects/inventhys/gael/ml-digits-detection-and-recognition/notebooks/inferences/~/.anaconda3/envs/gael/lib/python3.9/site-packages/ultralytics/engine/model.py:106), in YOLO.__init__(self, model, task)
    104     self._new(model, task)
    105 else:
--> 106     self._load(model, task)

File [~/.anaconda3/envs/gael/lib/python3.9/site-packages/ultralytics/engine/model.py:155](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/machine_learning/projects/inventhys/gael/ml-digits-detection-and-recognition/notebooks/inferences/~/.anaconda3/envs/gael/lib/python3.9/site-packages/ultralytics/engine/model.py:155), in YOLO._load(self, weights, task)
    153 suffix = Path(weights).suffix
    154 if suffix == '.pt':
--> 155     self.model, self.ckpt = attempt_load_one_weight(weights)
    156     self.task = self.model.args['task']
    157     self.overrides = self.model.args = self._reset_ckpt_args(self.model.args)

File [~/.anaconda3/envs/gael/lib/python3.9/site-packages/ultralytics/nn/tasks.py:622](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/machine_learning/projects/inventhys/gael/ml-digits-detection-and-recognition/notebooks/inferences/~/.anaconda3/envs/gael/lib/python3.9/site-packages/ultralytics/nn/tasks.py:622), in attempt_load_one_weight(weight, device, inplace, fuse)
    620 def attempt_load_one_weight(weight, device=None, inplace=True, fuse=False):
    621     """Loads a single model weights."""
--> 622     ckpt, weight = torch_safe_load(weight)  # load ckpt
    623     args = {**DEFAULT_CFG_DICT, **(ckpt.get('train_args', {}))}  # combine model and default args, preferring model args
    624     model = (ckpt.get('ema') or ckpt['model']).to(device).float()  # FP32 model

File [~/.anaconda3/envs/gael/lib/python3.9/site-packages/ultralytics/nn/tasks.py:561](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/machine_learning/projects/inventhys/gael/ml-digits-detection-and-recognition/notebooks/inferences/~/.anaconda3/envs/gael/lib/python3.9/site-packages/ultralytics/nn/tasks.py:561), in torch_safe_load(weight)
...
   1163         pass
   1164 mod_name = load_module_mapping.get(mod_name, mod_name)
-> 1165 return super().find_class(mod_name, name)

AttributeError: Can't get attribute 'NoneType' on
```

### Environment

- yolov8  8.0.139
- Python 3.9.12
- Ubuntu-22.04

### Minimal Reproducible Example

```
1. Finish one training of one epoch with yolov8n
2. get the path of the best model : `MODEL_PATH = Path('./runs/detect/train/weights/best.pt').resolve()`
3. load the model `model = YOLO(MODEL_PATH)`
```

### Additional

Code work fine with downgrade to 8.0.121.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@cfrancois7 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. I'm unable to reproduce any issue using your method, everything works correctly for me with the latest `ultralytics` package:


<img width="1078" alt="Screenshot 2023-07-21 at 14 00 55" src="https://github.com/ultralytics/ultralytics/assets/26833433/883f547b-bccd-41ec-aa3a-6a687530f5d7">


We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by glenn-jocher** [comment]
@cfrancois7 also using your exact method with local directory and .resolve() everything is working correctly:

<img width="1619" alt="Screenshot 2023-07-21 at 14 02 26" src="https://github.com/ultralytics/ultralytics/assets/26833433/54069483-aaa4-438e-9a0f-9753de70b0fb">

**Comment by cfrancois7** [comment]
@glenn-jocher 

I removed completely my environment and built a new one with conda.
And... it works fine.

I do not understand which update / dependencies broke.
Sorry for the useless ticket.

Great work ! It quite fantastic package you build by the way.

**Comment by glenn-jocher** [comment]
@cfrancois7 That's great to hear that a fresh environment setup resolved the issue! Not to worry, it's not a useless ticket, your report could be useful to other users who may face similar issues. In complex systems, dependency conflicts can sometimes cause unexpected issues, and starting with a new environment can often resolve these. 

Thanks for your kind words! We're really glad to hear that you think YOLOv8 is fantastic. We aim to provide a user-friendly and efficient tool, and feedback like yours is really encouraging. If you have any more questions or face any other issues, feel free to ask. 

Happy coding!

**Comment by weningerleon** [comment]
I encountered a similar issue, but for me it wasn't solved with a new installation. I tracked down the bug and found the following:

You monkey patch torch.save with your own save function, in which you replace pickle with dill (`import dill as pickle`).
This leads to a broken torch save / load functionality, probably because dill is used for saving but pickle for loading and the mentioned error. Probably the problem depends on the exact dill and pickle version.

A quick fix is to use `use_dill=False` in the ultralytics torch_save function (which is the same as torch.save if `ultralytics.utils` is imported). 

However, this monkey patching and shadowing standard library names is bad coding practice. Could you please do a proper fix?

**Comment by pderrenger** [comment]
Thank you for your detailed analysis. We appreciate your insights into the issue. To address this, please ensure you are using the latest versions of the Ultralytics package and its dependencies, as updates may have resolved this problem. If the issue persists, we recommend avoiding the use of `use_dill=True` and sticking with the default `torch.save` functionality. We will review the use of monkey patching and consider your feedback for future improvements. If you encounter further issues, please let us know.

**Comment by glenn-jocher** [comment]
@weningerleon 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
