### ISSUE TITLE
py-cpuinfo on Raspiberry Pi 4B

### ISSUE THREAD

**Issue by HHlt** [ultralytics/ultralytics#3890]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I was deploying the latest yolov8, ultralytics 8.0.136 on Raspiberry Pi 4B and I encountered this question:

```
cpuinfo.get_cpu_info()['brand_raw'].replace('(R)', '').replace('CPU ', '').replace('@ ', '')
KeyError: 'brand_raw'
```

I found this quuestion in this file:

./ultralytics/utils/torch_utils.py

in line 55, function  

```python
def get_cpu_info():
    """Return a string with system CPU information, i.e. 'Apple M2'."""
    check_requirements('py-cpuinfo')
    import cpuinfo  # noqa
    return cpuinfo.get_cpu_info()['brand_raw'].replace('(R)', '').replace('CPU ', '').replace('@ ', '')
```

The dictionary returned by package py-cpuinfo contains 'brand_raw' for the Intel CPU, but does not contain this item for the Raspberry Pi CPU, but displays the CPU model through other entries.

As a result, when the yolo program is running, when the Raspberry Pi wants to print the cpu model, it will report an error, causing the program to fail to run correctly.

I changed this function like this to support Raspiberry Pi 4B:

```python
def get_cpu_info():
    """Return a string with system CPU information, i.e. 'Apple M2'."""
    check_requirements('py-cpuinfo')
    import cpuinfo  # noqa
    cpu_info = cpuinfo.get_cpu_info()
    if 'brand_raw' in cpu_info.keys():
        return cpuinfo.get_cpu_info()['brand_raw'].replace('(R)', '').replace('CPU ', '').replace('@ ', '')
    elif 'hardware_raw' in cpu_info.keys():
        return cpuinfo.get_cpu_info()
    else:
        return "unknown"
```

My consideration is not comprehensive enough, other CPUs also need to introduce support or consider using other methods to print the CPU model.

I will be happy if I can help you to improve the program. Correct me if I'm wrong.

Thanks.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@HHlt hello,

Thanks for bringing up this issue with the Raspberry Pi 4B deployment for YOLOv8. It's fantastic to note that you're working to adjust the functionalities for Raspberry Pi use, and your considerations for different CPUs are highly appreciated.

The function `get_cpu_info` is indeed designed to return specific CPU information, and as you noted, when it doesn't find the key 'brand_raw' that is typical for Intel CPUs, it may cause an error. 

Your modification of the function to check whether 'brand_raw' key exists before returning its value and instead returning 'hardware_raw' information or 'unknown' if neither exist for non-Intel CPUs is a good approach. This sort of adaptive code modification demonstrates a great understanding of the problem and can avoid encountered errors.

We'd love to look into this further to potentially unify the CPU information retrieval in YOLOv8 across different platforms, including Raspberry Pi. Your experience and initiative of creating an adaptive solution is vital to improving YOLOv8.

Keep in mind this change would require extensive testing across multiple CPU brands and types to ensure efficiency and accuracy, as well as avoid introducing new problems. 

Thank you again for taking the time to contribute to the project. Feel free to raise a PR if you want to help us reviewing and merging your code in order to improve the CPU information retrieval across different platforms.

**Comment by glenn-jocher** [comment]
@HHlt I'll submit a PR with your recommended modification, looks good!

**Comment by glenn-jocher** [comment]
@HHlt I created PR #3899 to fix this. Can you take a look and see if that works for your use case?

Also what string shows up for `hardware_raw` on RPi for you?

**Comment by HHlt** [comment]
```
>>> import cpuinfo
>>> cpuinfo.get_cpu_info()
{'python_version': '3.8.10.final.0 (64 bit)', 'cpuinfo_version': [9, 0, 0], 'cpuinfo_version_string': '9.0.0', 'arch': 'ARM_8', 'bits': 64, 'count': 4, 'arch_string_raw': 'aarch64', 'hardware_raw': 'BCM2835', 'flags': ['asimd', 'cpuid', 'crc32', 'evtstrm', 'fp']}
```
When you use get_cpu_info() on RPi, you get return values like this. So the modification might not be quite right, just return cpuinfo.get_cpu_info()['hardware_raw'] is OK.

**Comment by HHlt** [comment]
```
>>> import cpuinfo
>>> cpuinfo.get_cpu_info()
{'python_version': '3.8.10.final.0 (64 bit)', 'cpuinfo_version': [9, 0, 0], 'cpuinfo_version_string': '9.0.0', 'arch': 'ARM_8', 'bits': 64, 'count': 4, 'arch_string_raw': 'aarch64', 'hardware_raw': 'BCM2835', 'flags': ['asimd', 'cpuid', 'crc32', 'evtstrm', 'fp']}
```

get_cpu_info() return like this. The PR is correct. Thank you.

**Comment by glenn-jocher** [comment]
@HHlt thank you for providing the output for `get_cpu_info()` on your Raspberry Pi. We're glad to know that the PR correctly addresses the issue you were encountering. Your feedback has been invaluable in helping improve the usability of YOLOv8 across different hardware platforms. We appreciate your time and effort in identifying this issue and proposing a fix. Don't hesitate to reach out if you find any more areas for improvement in the future!
