### ISSUE TITLE
Command Line Output After Using Ray Tune and Wandb for Hyperparameter Tuning

### ISSUE THREAD

**Issue by AkimotoAyako** [ultralytics/ultralytics#3891]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am using Ray Tune and Wandb to adjust my hyperparameters. However, even after disabling Wandb, the command line window does not update the output results in real-time. This includes mAP (mean average precision) and even the training and prediction progress. I would like to understand why this is happening and how to resolve this issue.

I got the output in CLI like:
`(yolo_v8) xxx@xxxubuntu:/data4/xxx/v8_test$ yolo task=detect mode=val model=/data4/xxx/v8_test/tune/pOTwBL7SKs/runs/tune/_tune_xxx/_tune_xxx/runs/detect/train/weights/best.pt data=data/UI_class.yaml device=1`

`val: Scanning /data4/xxx/v8_test/data/labels.cache... 1989 images, 0 backgrounds, 0 corrupt: 100%|██████████| 1989/1989 [00:00<?, ?it/s]`
                 
`     Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 125/125 [00:26<00:00,  4.68it/s]`

`(yolo_v8) xxx@xxxubuntu:/data4/xxx/v8_test$`
I cannot find my results...

**Comment by glenn-jocher** [comment]
@AkimotoAyako thank you for using YOLOv8 and for your question. The scenario you're facing seems unusual as turning off WandB shouldn't affect your CLI output in any way. 

The command line or terminal output displays the progress of the training, validation, and prediction tasks. During this process, it shows key metrics such as mAP (mean average precision), loss values, and the number of instances of each class among other details.

You mentioned that you are not seeing updates in the command line output. This could potentially be due to your terminal environment not getting refreshed properly. One possible solution could be to check your terminal settings or try in a different terminal window or application. 

Your command line output suggests that the model has validated a dataset (`val: Scanning /data4/xxx/v8_test/data/labels.cache...`) and then proceeded to classify instances. The key metrics seem to be missing in your output. This might have happened due to an issue in the evaluation phase of the YOLOv8 model.

As for searching your results, they are usually stored in a specific directory after each run. You should be able to find them in a subdirectory within your project directory. The directory name usually contains the timestamp of the run to help distinguish between different runs.

Let the Ultralytics team know if these suggestions don't solve your problem, and we'll try to assist you further. Your usage and feedback help us continuously improve YOLOv8.

**Comment by AkimotoAyako** [comment]
> @AkimotoAyako thank you for using YOLOv8 and for your question. The scenario you're facing seems unusual as turning off WandB shouldn't affect your CLI output in any way.
> 
> The command line or terminal output displays the progress of the training, validation, and prediction tasks. During this process, it shows key metrics such as mAP (mean average precision), loss values, and the number of instances of each class among other details.
> 
> You mentioned that you are not seeing updates in the command line output. This could potentially be due to your terminal environment not getting refreshed properly. One possible solution could be to check your terminal settings or try in a different terminal window or application.
> 
> Your command line output suggests that the model has validated a dataset (`val: Scanning /data4/xxx/v8_test/data/labels.cache...`) and then proceeded to classify instances. The key metrics seem to be missing in your output. This might have happened due to an issue in the evaluation phase of the YOLOv8 model.
> 
> As for searching your results, they are usually stored in a specific directory after each run. You should be able to find them in a subdirectory within your project directory. The directory name usually contains the timestamp of the run to help distinguish between different runs.
> 
> Let the Ultralytics team know if these suggestions don't solve your problem, and we'll try to assist you further. Your usage and feedback help us continuously improve YOLOv8.

Thank you for your response. I created a new virtual environment and installed Ultralytics, and I can confirm that the issue I'm facing is not related to wandb. Before running **pip install -U ultralytics 'ray[tune]'**, I executed the validation code and obtained average precision information for each class successfully. However, after installing and updating the Ultralytics and Ray Tune packages, I encountered the same error as before. I also switched my shell, but the issue still persists.

**Comment by glenn-jocher** [comment]
@AkimotoAyako, thank you for your patience and for providing more insight into your issue.

It's interesting to note that you are facing this issue after installing Ray Tune and updating Ultralytics. This situation could be caused by a conflict between some of the packages or dependencies. While Ultralytics and Ray Tune are designed to work together, it's possible that some of their dependencies may be conflicting with each other or with other packages in your environment.

As of your information, we know that the problem arises after upgrading the packages. One solution we suggest is downgrading your packages to the last known working version. This could potentially help if the issue is with a newer version of the packages. 

If the problem persists, it would be worth creating a new Python virtual environment and installing the packages one by one, checking the functionality after each install. This systematic approach might help you identify if a specific package or dependency is causing the conflict.

Let us know if these suggestions were helpful. We are here to assist you further. Your usage and feedback are valuable to us and help us improve YOLOv8.

**Comment by AkimotoAyako** [comment]
> 

Thank you for your response. After downgrading Ray from version 2.6.1 to 2.5, the issue has been resolved. Thank you again for your patience :)

**Comment by AkimotoAyako** [comment]
> @AkimotoAyako, thank you for your patience and for providing more insight into your issue.
> 
> It's interesting to note that you are facing this issue after installing Ray Tune and updating Ultralytics. This situation could be caused by a conflict between some of the packages or dependencies. While Ultralytics and Ray Tune are designed to work together, it's possible that some of their dependencies may be conflicting with each other or with other packages in your environment.
> 
> As of your information, we know that the problem arises after upgrading the packages. One solution we suggest is downgrading your packages to the last known working version. This could potentially help if the issue is with a newer version of the packages.
> 
> If the problem persists, it would be worth creating a new Python virtual environment and installing the packages one by one, checking the functionality after each install. This systematic approach might help you identify if a specific package or dependency is causing the conflict.
> 
> Let us know if these suggestions were helpful. We are here to assist you further. Your usage and feedback are valuable to us and help us improve YOLOv8.

Thank you for your response. After downgrading Ray from version 2.6.1 to 2.5, the issue has been resolved. Thank you again for your patience :)

**Comment by glenn-jocher** [comment]
@AkimotoAyako, that's great to hear! We're glad the issue was resolved by downgrading Ray. We really appreciate your patience and diligence in troubleshooting this. Your experiences and feedback are instrumental in improving YOLOv8, and we are glad that we could assist in resolving your issue. Keep us posted with any other inquiries or issues you may encounter down the line, we're here to help. Happy coding!
