### ISSUE TITLE
DEFAULT_CFG

### ISSUE THREAD

**Issue by shuaixin97** [ultralytics/ultralytics#3897]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I edit the default.yaml, but the DEFAULT_CFG is still default value.

**Comment by glenn-jocher** [comment]
@shuaixin97 thank you for bringing this to our attention. Regarding your observations when modifying the `default.yaml`, the `DEFAULT_CFG` value remains unchanged because it's simply a fallback configuration. It is designed to fetch configurations when they are not provided by the user, ensuring stable model behavior even if certain user configurations are missing. To see the changes you made in the `default.yaml` reflected in your model training or inference tasks, ensure that your custom configurations are properly passed during these tasks. These custom configurations will then override the values from the `DEFAULT_CFG`, allowing you to adjust the model behavior according to your needs. I hope this addresses your question, please let us know if you have any other concerns or queries!
