### ISSUE TITLE
Changed the c2f module in the yaml file to c3. Why does the terminal still display c2f?

### ISSUE THREAD

**Issue by yunchuan18** [ultralytics/ultralytics#3903]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Changed the c2f module in the yaml file to c3. Why does the terminal still display c2f?Did I modify the location incorrectly?
yolo task=detect mode=train model=yolov8.yaml data=/root/autodl-tmp/yolov8/datasets/datasets.yaml batch=32 epochs=200 imgsz=640 workers=16 device=0 
  Using this command to train, I also imported yolov8.yaml and modified yaml。
<img width="430" alt="微信图片_20230723222811" src="https://github.com/ultralytics/ultralytics/assets/35885912/ca675468-5039-4715-aff9-fde38013067e">

**Comment by glenn-jocher** [comment]
@yunchuan18 yes, you're on the right track. By setting `model` to the full path of your `.yaml` file, you are explicitly telling the system where to find your desired configuration file. This option should indeed resolve the issue you're having if the terminal isn't detecting the change to the c3 module in the context of your YOLOv8 model. This is because it leaves no room for confusion, as you're pointing the system to the precise location of the file you wish to use for your model.

Please ensure you replace `full/path/to/.yaml` with the absolute path to your actual `.yaml` file. After executing this correctly, your training command will directly refer to this file and use the c3 module and other configurations defined therein.

Remember to always verify your changes by making sure the terminal displays the correct configurations before proceeding with your training.

Happy training, and let us know if you encounter any further issues!

**Comment by yunchuan18** [comment]
> I think ` model=full/path/to/.yaml` can solve the problem



Thank you for your answer, it has been very helpful to me.

**Comment by yunchuan18** [comment]
> @yunchuan18 yes, you're on the right track. By setting `model` to the full path of your `.yaml` file, you are explicitly telling the system where to find your desired configuration file. This option should indeed resolve the issue you're having if the terminal isn't detecting the change to the c3 module in the context of your YOLOv8 model. This is because it leaves no room for confusion, as you're pointing the system to the precise location of the file you wish to use for your model.
> 
> Please ensure you replace `full/path/to/.yaml` with the absolute path to your actual `.yaml` file. After executing this correctly, your training command will directly refer to this file and use the c3 module and other configurations defined therein.
> 
> Remember to always verify your changes by making sure the terminal displays the correct configurations before proceeding with your training.
> 
> Happy training, and let us know if you encounter any further issues!

Thank you for your answer. I was too careless.

**Comment by glenn-jocher** [comment]
You're welcome @yunchuan18! Don't worry at all, it's all part of the learning process. I'm glad the solution was helpful. Don't hesitate to ask if you have any more questions or run into any other issues. Happy training!
