### ISSUE TITLE
NCNN inference using YOLOv8

### ISSUE THREAD

**Issue by jeck00119** [ultralytics/ultralytics#3917]
It is possible to run NCNN inference with ultralytics? I have the .param and .bin files.
i want something like this one for ONNX: 
```
from ultralytics import YOLO

# Load the exported ONNX model
model = YOLO('yolov8_last.onnx')

results_onnx = model.predict(source = 0, show = True, save = False) 
```

**Comment by jeck00119** [comment]
Also i get this:
```
Ultralytics YOLOv8.0.141 🚀 Python-3.10.6 torch-2.0.1+cu118 CPU (Intel Xeon 2.30GHz)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients

PyTorch: starting from 'yolov8n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)

TorchScript: starting export with torch 2.0.1+cu118...
TorchScript: export success ✅ 2.3s, saved as 'yolov8n.torchscript' (12.5 MB)

ncnn: starting export with ncnn 1.0.20230517...
ncnn: running '/usr/local/lib/python3.10/dist-packages/ultralytics/pnnx yolov8n.torchscript pnnxparam=yolov8n_ncnn_model/model.pnnx.param pnnxbin=yolov8n_ncnn_model/model.pnnx.bin pnnxpy=yolov8n_ncnn_model/model_pnnx.py pnnxonnx=yolov8n_ncnn_model/model.pnnx.onnx ncnnparam=yolov8n_ncnn_model/model.ncnn.param ncnnbin=yolov8n_ncnn_model/model.ncnn.bin ncnnpy=yolov8n_ncnn_model/model_ncnn.py fp16=0 device=cpu inputshape="[1, 3, 640, 640]"'
ncnn: export success ✅ 2.2s, saved as 'yolov8n_ncnn_model' (36.7 MB)

Export complete (6.2s)
Results saved to /content
Predict:         yolo predict task=detect model=yolov8n_ncnn_model imgsz=640 
Validate:        yolo val task=detect model=yolov8n_ncnn_model imgsz=640 data=coco.yaml 
Visualize:       https://netron.app/
WARNING ⚠️ Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify', or 'pose'.
Loading yolov8n_ncnn_model for ncnn inference...
Traceback (most recent call last):
  File "ultralytics/nn/autobackend.py", line 294, in __init__
    for k, v in metadata.items():
AttributeError: 'PosixPath' object has no attribute 'items'
```
when I run with official model yolov8n:
```
from ultralytics import YOLO

# Export YOLOv8n to ncnn
YOLO('yolov8n.pt').export(format='ncnn') 

# Load ncnn model
model = YOLO('yolov8n_ncnn_model')

# Predict
model.predict('ultralytics/assets/bus.jpg')

# Val
model.val(data='coco8.yaml')
```

**Comment by glenn-jocher** [comment]
@jeck00119 it seems like you're encountering an issue while exporting the YOLOv8 model to NCNN format and using it for prediction. The 'AttributeError' could be happening due to incorrect assumptions regarding file directory structure or the expectation of a Python dictionary object where none exists. It might be an internal issue with the framework or how the model is being loaded.

As for the error associated with the official yolov8n model, the Autobackend.py seems to be experiencing issues. It's trying to iterate over `metadata.items()`, but 'metadata' is a 'PosixPath' object, which doesn't have the method 'items()'. This could also be due to an internal error with the framework or 'metadata' is not being correctly initialized. 

In this particular case, it would be helpful to debug where the loading process is failing or what the 'metadata' object is supposed to be. Also, checks can be put in place to ensure proper filepath or correctly formed Python dictionary objects are passed where required. 

Additionally, consider reporting the error details to the Ultralytics team so we can better assist you and potentially fix a bug.

**Comment by jeck00119** [comment]
I found that i didn't have `metadat.yaml` in `yolov8_last_ncnn`model folder because I failed to export the .pt weight to NCNN with ultralytics, so i exported first to ONNX using ultralytics and then to NCNN using this [site](https://convertmodel.com/#input=onnx&output=onnx) and now i only have .parm and .bin files.I manage to export directly to NCNN using ultralytics in a google colab and now i have all the files but I get this:
```
Loading yolov_ncnn_model for ncnn inference...

WARNING ⚠️ NMS time limit 0.550s exceeded
WARNING ⚠️ 'Boxes.boxes' is deprecated. Use 'Boxes.data' instead.
Traceback (most recent call last):
  File "/home/pi/yolov8_ncnn/ncnn_export_ultralytics.py", line 5, in <module>
    results = model.predict(source = "1.jpg")
  File "/usr/local/lib/python3.9/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/pi/yolov8_ncnn/venv/lib/python3.9/site-packages/ultralytics/engine/model.py", line 254, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/pi/yolov8_ncnn/venv/lib/python3.9/site-packages/ultralytics/engine/predictor.py", line 195, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/usr/local/lib/python3.9/dist-packages/torch/autograd/grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "/home/pi/yolov8_ncnn/venv/lib/python3.9/site-packages/ultralytics/engine/predictor.py", line 270, in stream_inference
    s += self.write_results(i, self.results, (p, im, im0))
  File "/home/pi/yolov8_ncnn/venv/lib/python3.9/site-packages/ultralytics/engine/predictor.py", line 166, in write_results
    log_string += result.verbose()
  File "/home/pi/yolov8_ncnn/venv/lib/python3.9/site-packages/ultralytics/engine/results.py", line 271, in verbose
    log_string += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, "
KeyError: 21
```

**Comment by jeck00119** [comment]
Also the `AttributeError: 'PosixPath' object has no attribute 'items'` and `layer pnnx.Input not exists or registered` are from Google Colab

**Comment by glenn-jocher** [comment]
@jeck00119 thanks for reporting this issue. It appears that there are a couple of different problems you're experiencing. 

The `AttributeError: 'PosixPath' object has no attribute 'items'` error arises because the function is trying to treat a PosixPath object as a dictionary and call the `items()` method on it, which doesn't exist for PosixPath objects. It seems like a file path is being passed where the function expects a dictionary.

The `layer pnnx.Input not exists or registered` error is implying that the program is trying to access a layer in the network named 'pnnx.Input', but it's not actually part of the net. It could be that something is off in your exported `.param` or `.bin` files or your model might not be compatible with NCNN. 

These errors indicate that there might be some internal issues with the framework, or perhaps the model or data is not being loaded correctly. Debugging where the loading process is failing and checking your exported files might help to pinpoint the issue.

As for the `KeyError: 21`, this error is happening because the code is trying to access a nonexistent element in an array or dictionary. Specifically, it's trying to look up a label name for class "21", but isn't able to find it. This could be a result of mismatched or incorrect label files, or the model might be predicting more classes than there are names provided in the labels.

Please make sure your class indices and label files match and your model files are correctly exported. If issues persist, it would be helpful to submit a more detailed error report to the YOLOv8 team so they can further assist you.

**Comment by jeck00119** [comment]
Thanks for the response, I want to clarify the the steps to run inference for NCNN:
So after i export the .pt to NCNN I'll have a folder named `yolov8_ncnn_model` that contains: `metadata.yaml, model_ncnn.py, model_pnnx.py, model.ncnn.bin, model.ncnn.param, model.pnnx.bin, model.pnnx.onnx, model.pnnx.param`. After that i run this script to inference:
```
from ultralytics import YOLO

model = YOLO('yolov8_ncnn_model') # the folder with all ncnn files

results = model.predict(source = "test.jpg") 
```
Are these all the steps?

**Comment by goldwater668** [comment]
@glenn-jocher 
Yolov8-pose training is completed and converted to ncnn. The test time using python inference is 60ms. It was 6ms before the conversion. What is going on?

**Comment by glenn-jocher** [comment]
@goldwater668 hi there,

The difference in inference times you're experiencing might be due to several reasons based on how inference is conducted using YOLOv8 in Python and in NCNN. 

Firstly, it's important to note that NCNN is designed to be lean and efficient to work on mobile and edge devices. Thus, how it optimizes and conducts inferences could considerably differ from a full-fledged Python environment.

When comparing inference times, it's necessary to ensure that the testing environment is the same between both models. Hardware components and the system's load could have a significant impact on the execution time.

In terms of the conversion process, there might be some operations or layers in the YOLOv8-pose model that are not as efficient in NCNN as they are in Python. As a result, these operations might have slower inference times leading to a slower total inference time.

Lastly, the post-processing operations in NCNN could be different or less optimized compared to the YOLOv8 Python implementation, contributing to the difference in speed.

So, it's completely normal to have discrepancies in performance. If you need faster inference, you might want to consider optimizing your converted NCNN model further to match the speed of the Python version.

**Comment by goldwater668** [comment]
@glenn-jocher 
The following is the inference time of ncnn-gpu, ncnn-cpu and pt-ncnn that I tested. Is this normal? This is tested by yolo prediction code.
![2023-11-03 11-23-58 的屏幕截图](https://github.com/ultralytics/ultralytics/assets/29244715/1a932e8e-157a-4012-8119-960a092be711)

**Comment by glenn-jocher** [comment]
@goldwater668 hi there, 

Looking at your screenshots, there seems to be a difference in the inference time between the ncnn-gpu, ncnn-cpu, and pt-ncnn. This is indeed normal and to be expected. 

The time required for inference can vary greatly depending on a variety of factors. Some of these factors include the size and complexity of the model, the utility of hardware accelerations, the device's hardware capabilities, and the specific optimizations employed within different inference engines. 

In this context, NCNN-CPU might take longer than NCNN-GPU because GPU computation is generally faster for deep learning models due to parallel processing. The difference between PyTorch (pt) and NCNN is also normal as these are different inference engines with their own set of optimizations and compatibility designs.

As long as your models are producing the correct and expected outputs, these differences in speed are normal and are unlikely to be a sign of a problem with your setup or your code.

Keep in mind, if speed is a priority for your use case, you might want to look into model optimization techniques specific to the inference engine you are using, or consider using a more powerful hardware setup if possible.

**Comment by mah-samir** [comment]
@glenn-jocher  
can i convert yolov8n model to NCNN format at same way i used to convert yolo11 ?

i mean using the following code 

```
 from ultralytics import YOLO

# Load a YOLO PyTorch model
model = YOLO("Mask.pt")

# Export the model to NCNN format
model.export(format="ncnn",imgsz=320)  # creates 'yolov8n_ncnn_model'

```

**Comment by glenn-jocher** [comment]
Yes, you can convert YOLOv8 models to NCNN format using the same `model.export(format="ncnn")` method shown in your code. This process is standardized across supported Ultralytics YOLO versions including YOLOv8 and YOLO11 as documented in our NCNN integration guide. 

For commercial use cases, please ensure compliance with our licensing requirements by reviewing the Ultralytics License documentation.
