### ISSUE TITLE
Multithreading works for model.predict() but fails for model.track()

### ISSUE THREAD

**Issue by wagmi-admin** [ultralytics/ultralytics#3919]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

```
  File "/Users/rsk/miniconda3/lib/python3.10/site-packages/ultralytics/engine/model.py", line 277, in track
    return self.predict(source=source, stream=stream, **kwargs)
  File "/Users/rsk/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/rsk/miniconda3/lib/python3.10/site-packages/ultralytics/engine/model.py", line 249, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "/Users/rsk/miniconda3/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 303, in setup_model
    self.model = AutoBackend(model or self.args.model,
  File "/Users/rsk/miniconda3/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 103, in __init__
    model = model.fuse(verbose=verbose) if fuse else model
  File "/Users/rsk/miniconda3/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 134, in fuse
    delattr(m, 'bn')  # remove batchnorm
  File "/Users/rsk/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1685, in __delattr__
    super().__delattr__(name)
AttributeError: bn
```

### Environment

Using in Mac M1 Pro

### Minimal Reproducible Example

```
from collections import deque
from multiprocessing.pool import ThreadPool

import cv2 as cv
from ultralytics import YOLO


VIDEO_SOURCE = "/Users/rsk/DriveTest/GX040112.MP4"


def process_frame(frame, frame_index):
    # some intensive computation...
    print("frame-index: " + str(frame_index))

    result = model.track(source=frame, classes=[0], conf=0.7,
                         tracker="botsort.yaml", device="mps", persist=True)
    # result = model.predict(source=frame, classes=[0], conf=0.7, device="mps")[0]

    # frame = cv.medianBlur(frame, 19)
    print("result: ", result)
    return result


if __name__ == '__main__':
    # Setup.
    cap = cv.VideoCapture(VIDEO_SOURCE)
    frame_pos = 60
    cap.set(cv.CAP_PROP_POS_FRAMES, frame_pos)

    # thread_num = cv.getNumberOfCPUs()
    thread_num = 2

    pool = ThreadPool(processes=thread_num)
    pending_task = deque()

    model = YOLO("models/yolov8s.pt")

    frame_index = 0

    while True:
        # Consume the queue.
        while len(pending_task) > 0 and pending_task[0].ready():
            res = pending_task.popleft().get()
            print("executed: " + str(res))
            # cv.imshow('threaded video', res)

        # Populate the queue.
        if len(pending_task) < thread_num:
            frame_got, frame = cap.read()
            if frame_got:
                frame_index = frame_index + 1
                print("adding task: " + str(frame_index))
                task = pool.apply_async(process_frame, (frame.copy(),frame_index))
                pending_task.append(task)
                # process_frame(frame.copy(), frame_index)

        # Show preview.
        if cv.waitKey(1) == 27 or not frame_got:
            break

cv.destroyAllWindows()
```

### Additional

When
thread_num = 1
Then to code works fine. When it is 2 or greater it gives this error.

If I run model.predict() instead of model.track() - it works for all thread_num values.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@wagmi-admin in the context of the YOLOv8 model, the `model.track()` function is not thread-safe due to the underlying pytorch model which modifies shared variables. On the other hand, the `model.predict()` function is stateless and thus, can safely be executed in parallel. 

When you set thread_num to 1, your code works fine because there's no multithreading happening. The tasks are sequenced and shared resources are not being accessed concurrently which avoids the race condition.

Unfortunately, making the `model.track()` function thread-safe would require significant changes to the underlying structure of both YOLOv8 and PyTorch which is beyond the scope of this repository. Therefore, we would recommend continuing with single-threaded use for functions like `model.track()`, and reserving multithreaded use for stateless functions like `model.predict()`.

**Comment by glenn-jocher** [comment]
@Laughing-q do you know if there are any in-place operations during tracking i.e. `y *= x`? In my experience in-place ops in YOLOv5 lead to multithreading issues as the same base was modified for both.

**Comment by Laughing-q** [comment]
@glenn-jocher I don't remember such ops.
But from the example the user gave it's running tracking with multi-thread on one video? I suppose this multi-thread running is unordered right?  Then actually I don't think it is the correct usage since tracking usually needs to be running on continuous frames since the tracker would keep track information of previous frames to infer if the objects from next frame match the previous ones.

**Comment by glenn-jocher** [comment]
@Laughing-q ah yes that's correct!

@wagmi-admin tracking on a video must be done sequentially from one frame to the next. If you want to multithread tracking then the correct way to do it would be to process two videos, one in each thread, but you always need to keep the same video in 1 thread. 

I've created an example of Multithreaded tracking in our Docs now here that shows you how to correctly do this for 2 videos in parallel:

https://docs.ultralytics.com/modes/track/#multithreaded-tracking

<img width="1236" alt="Screenshot 2023-07-30 at 21 33 20" src="https://github.com/ultralytics/ultralytics/assets/26833433/349f4416-d5a7-4b07-abf5-fc355d02cf93">

**Comment by MABatin** [comment]
Hi @glenn-jocher, thank you for providing a multithreaded tracking script. However, I have modified the script to run both models in same thread but for different videos. The code is as following:
```
import os.path
import threading
import time

import cv2
from ultralytics import YOLO


def run_tracker_in_thread(filename, det_model, pose_model):
    det_results = det_model.track(source=filename, persist=True, verbose=False, stream=True)
    pose_results = pose_model.track(source=filename, persist=True, verbose=False, stream=True)
    for det_result, pose_result in zip(det_results, pose_results):
        print(f"{os.path.basename(filename)}: {det_model.ckpt_path} - id: {det_result.boxes.id}")
        print(f"{os.path.basename(filename)}: {pose_model.ckpt_path} - id: {pose_result.boxes.id}")


# Load the models
model1 = YOLO('weights/yolov8x-pose.pt')
model2 = YOLO('weights/yolov8x-seg.pt')

# Define the video files for the trackers
video_file1 = 'practice/data/S002C001P007R002A056_rgb.avi'
video_file2 = 'practice/data/S004C001P007R002A043_rgb.avi'

# Create the tracker threads
tracker_thread1 = threading.Thread(target=run_tracker_in_thread, args=(video_file1, model2, model1), daemon=True)
tracker_thread2 = threading.Thread(target=run_tracker_in_thread, args=(video_file2, model2, model1), daemon=True)

# Start the tracker threads
tracker_thread1.start()
tracker_thread2.start()

# Wait for the tracker threads to finish
tracker_thread1.join()
tracker_thread2.join()

```
But I am getting following error for video_file2:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/leon/activity-recognition-research/practice-chatgpt.py", line 10, in run_tracker_in_thread
    det_results = det_model.track(source=filename, persist=True, verbose=False, stream=True)
  File "/home/leon/activity-recognition-research/ultralytics/ultralytics/engine/model.py", line 269, in track
    return self.predict(source=source, stream=stream, **kwargs)
  File "/home/leon/activity-recognition-research/envactivity/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/leon/activity-recognition-research/ultralytics/ultralytics/engine/model.py", line 238, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "/home/leon/activity-recognition-research/ultralytics/ultralytics/engine/predictor.py", line 305, in setup_model
    self.model = AutoBackend(model or self.args.model,
  File "/home/leon/activity-recognition-research/ultralytics/ultralytics/nn/autobackend.py", line 103, in __init__
    model = model.fuse(verbose=verbose) if fuse else model
  File "/home/leon/activity-recognition-research/ultralytics/ultralytics/nn/tasks.py", line 134, in fuse
    delattr(m, 'bn')  # remove batchnorm
  File "/home/leon/activity-recognition-research/envactivity/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1324, in __delattr__
    super().__delattr__(name)
AttributeError: bn

```
While video_file1 is producing output results as following:
```
Ultralytics YOLOv8.0.145 🚀 Python-3.10.6 torch-1.13.0+cu117 CUDA:0 (NVIDIA GeForce RTX 2070, 7967MiB)
YOLOv8x-seg summary (fused): 295 layers, 71797696 parameters, 0 gradients
S002C001P007R002A056_rgb.avi: weights/yolov8x-seg.pt - id: tensor([1., 2., 3.])
S002C001P007R002A056_rgb.avi: weights/yolov8x-pose.pt - id: tensor([1., 2.])
S002C001P007R002A056_rgb.avi: weights/yolov8x-seg.pt - id: tensor([1., 2., 3.])
S002C001P007R002A056_rgb.avi: weights/yolov8x-pose.pt - id: tensor([1., 2.])
S002C001P007R002A056_rgb.avi: weights/yolov8x-seg.pt - id: tensor([1., 2., 3.])
S002C001P007R002A056_rgb.avi: weights/yolov8x-pose.pt - id: tensor([1., 2.])
S002C001P007R002A056_rgb.avi: weights/yolov8x-seg.pt - id: tensor([1., 2., 3.])
S002C001P007R002A056_rgb.avi: weights/yolov8x-pose.pt - id: tensor([1., 2.])
S002C001P007R002A056_rgb.avi: weights/yolov8x-seg.pt - id: tensor([1., 2., 3.])
S002C001P007R002A056_rgb.avi: weights/yolov8x-pose.pt - id: tensor([1., 2.])
S002C001P007R002A056_rgb.avi: weights/yolov8x-seg.pt - id: tensor([1., 2., 3.])
S002C001P007R002A056_rgb.avi: weights/yolov8x-pose.pt - id: tensor([1., 2.])
S002C001P007R002A056_rgb.avi: weights/yolov8x-seg.pt - id: tensor([1., 2., 3.])
...
```

What might be the issue here do you think?

**Comment by MABatin** [comment]
I have done more tests and it seems that if there are more than two threads problem arises.
For example:
def run_tracker_in_thread(filename, model):
    video = cv2.VideoCapture(filename)
    frames = int(video.get(cv2.CAP_PROP_FRAME_COUNT))
    for _ in range(frames):
        ret, frame = video.read()
        if ret:
            results = model.track(source=frame, persist=True, verbose=False, stream=True)
            for result in results:
                print(f"{os.path.basename(filename)}: {model.ckpt_path} - id: {result.boxes.id}")

if I run this in 4 threads I get following error:
```
Exception in thread Thread-4 (run_tracker_in_thread):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-2 (run_tracker_in_thread):
Traceback (most recent call last):
    self.run()
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/leon/activity-recognition-research/practice-chatgpt.py", line 20, in run_tracker_in_thread
    results = model.track(source=filename, persist=True, verbose=False, stream=True)
  File "/home/leon/activity-recognition-research/ultralytics/ultralytics/engine/model.py", line 269, in track
Exception in thread Thread-3 (run_tracker_in_thread):
Traceback (most recent call last):
    return self.predict(source=source, stream=stream, **kwargs)
    self.run()
  File "/home/leon/activity-recognition-research/envactivity/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
  File "/usr/lib/python3.10/threading.py", line 953, in run
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    return func(*args, **kwargs)
  File "/home/leon/activity-recognition-research/ultralytics/ultralytics/engine/model.py", line 238, in predict
    self.run()
    self._target(*self._args, **self._kwargs)
  File "/home/leon/activity-recognition-research/practice-chatgpt.py", line 20, in run_tracker_in_thread
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "/home/leon/activity-recognition-research/ultralytics/ultralytics/engine/predictor.py", line 305, in setup_model
    results = model.track(source=filename, persist=True, verbose=False, stream=True)
    self._target(*self._args, **self._kwargs)
  File "/home/leon/activity-recognition-research/practice-chatgpt.py", line 20, in run_tracker_in_thread
  File "/home/leon/activity-recognition-research/ultralytics/ultralytics/engine/model.py", line 269, in track
    self.model = AutoBackend(model or self.args.model,
  File "/home/leon/activity-recognition-research/ultralytics/ultralytics/nn/autobackend.py", line 103, in __init__
    results = model.track(source=filename, persist=True, verbose=False, stream=True)
  File "/home/leon/activity-recognition-research/ultralytics/ultralytics/engine/model.py", line 269, in track
    model = model.fuse(verbose=verbose) if fuse else model
  File "/home/leon/activity-recognition-research/ultralytics/ultralytics/nn/tasks.py", line 134, in fuse
    return self.predict(source=source, stream=stream, **kwargs)
    return self.predict(source=source, stream=stream, **kwargs)
  File "/home/leon/activity-recognition-research/envactivity/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    delattr(m, 'bn')  # remove batchnorm
  File "/home/leon/activity-recognition-research/envactivity/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
  File "/home/leon/activity-recognition-research/envactivity/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1324, in __delattr__
    return func(*args, **kwargs)
    return func(*args, **kwargs)
  File "/home/leon/activity-recognition-research/ultralytics/ultralytics/engine/model.py", line 238, in predict
  File "/home/leon/activity-recognition-research/ultralytics/ultralytics/engine/model.py", line 238, in predict
    super().__delattr__(name)
    self.predictor.setup_model(model=self.model, verbose=is_cli)
AttributeError: bn
  File "/home/leon/activity-recognition-research/ultralytics/ultralytics/engine/predictor.py", line 305, in setup_model
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "/home/leon/activity-recognition-research/ultralytics/ultralytics/engine/predictor.py", line 305, in setup_model
    self.model = AutoBackend(model or self.args.model,
  File "/home/leon/activity-recognition-research/ultralytics/ultralytics/nn/autobackend.py", line 103, in __init__
    self.model = AutoBackend(model or self.args.model,
  File "/home/leon/activity-recognition-research/ultralytics/ultralytics/nn/autobackend.py", line 103, in __init__
    model = model.fuse(verbose=verbose) if fuse else model
    model = model.fuse(verbose=verbose) if fuse else model
  File "/home/leon/activity-recognition-research/ultralytics/ultralytics/nn/tasks.py", line 134, in fuse
  File "/home/leon/activity-recognition-research/ultralytics/ultralytics/nn/tasks.py", line 134, in fuse
    delattr(m, 'bn')  # remove batchnorm
  File "/home/leon/activity-recognition-research/envactivity/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1324, in __delattr__
    delattr(m, 'bn')  # remove batchnorm
  File "/home/leon/activity-recognition-research/envactivity/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1324, in __delattr__
    super().__delattr__(name)
AttributeError: bn
    super().__delattr__(name)
AttributeError: bn

```
But one thread runs fine. Why is that? It's same for num_threads = 3
Only two threads work.

**Comment by glenn-jocher** [comment]
@MABatin it appears that you are encountering an error when you try to run more than two threads in parallel. This likely comes down to the operation in the threads not being thread-safe, meaning that it might be causing a race condition when multiple threads are trying to access or modify the same data simultaneously.

The error message `AttributeError: bn` suggests that during the process of model fusing (optimization process involving the merging of certain layers for speed improvements), it's running into a problem where it can't find or access batch normalization layers, possibly due to concurrent modifications.

In general, the machine learning models, including YOLOv8, are not inherently thread-safe. It is advised to manage this by ensuring sequential processing where states could be shared or modified. One way around this could be to instantiate a new model for each thread if the memory allows, which can help prevent this sort of collision. So, if you're running 4 threads, spin up 4 instances of the model.

Additionally, you may want to add thread synchronization logic (mutexes, locks) to your code to ensure the shared resource (in this case, the model object) isn’t simultaneously changed by multiple threads.

Always remember, the fewer states you share between threads the better, and any shared states should be protected for simultaneous modifications.

I hope that helps! If you have more questions, feel free to ask.

**Comment by MABatin** [comment]
Thanks for the response @glenn-jocher. After some tests, I have found that multiprocessing with torch allowed for concurrent processing of multiple videos at a time. However, I only saw ~17% improved in processing time when processing using two processes for inference compared to single process inference. Do you think there should be more improvement in processing time or is this normal for a hardware setup with 8gb vram?

**Comment by glenn-jocher** [comment]
@MABatin hello,

Thank you for sharing your findings. The degree of speedup from using multiple processes can vary depending on various factors. Given that you're working with an operation that's largely GPU-bound (namely, deep learning inference), much of the processing time is likely dependent on the compute capacity of your GPU.

Your observed ~17% improvement indicates that some level of parallel processing is indeed occurring and speeding up the overall processing time, which is a positive outcome. However, the reason for this not being closer to a 50% reduction (which might be expected when doubling the number of processes) could be due to several possible factors:

- Firstly, you are limited by the capacity of your VRAM. Running two processes concurrently means that the available VRAM is divided across processes, which could potentially limit the complexity of the operations that can be performed in parallel.

- Secondly, there is a certain amount of overhead associated with managing multiple processes - this includes the time taken to set up, synchronize and terminate the processes.

- Finally, running two processes doesn't necessarily mean the GPU's resources are equally split. The utilization also depends on your GPU's architecture and also on how well Pytorch can distribute the workload across the available cores.

Thus, seeing a less than proportional speedup is quite normal in such scenarios due to these complexities. As a general rule, deep learning inference tends not to scale linearly with the number of processes due to these factors. 

Hope this helps in understanding the situation better!  Let me know if you have further questions.

**Comment by steavoh** [comment]
> Thanks for the response @glenn-jocher. After some tests, I have found that multiprocessing with torch allowed for concurrent processing of multiple videos at a time. However, I only saw ~17% improved in processing time when processing using two processes for inference compared to single process inference. Do you think there should be more improvement in processing time or is this normal for a hardware setup with 8gb vram?

@MABatin I'm facing the same problem and would appreciate it if you could show me the sample code you solved with torch.

**Comment by wagmi-admin** [comment]
Thanks a ton @glenn-jocher for this doc. Makes our job easier.
https://docs.ultralytics.com/modes/track/#multithreaded-tracking

There are still things that are bothering though

If we use this approach - say I have an 8 Core machine. I can run 8 videos in parallel - but then the GPU becomes the bottle neck. Model's inference time goes up by 6-7x  (I'm talking about an NVIDIA T4 GPU available on GCP)

Is there something that can be done about this?

Other things that I wanted to cross check were:
1. Rather than passing a single frame to `model.track()` what if we pass a batch of say 30 frames together. Will the collective inference time improve compared to one by one?
2. How can we improve the overall video processing time if we have multiple CPU cores available but just a single GPU. Any references/docs/pointers will be of great help.

@Laughing-q @MABatin @steavoh - if you have tried something similar, please do share your learnings too. Thanks

**Comment by glenn-jocher** [comment]
@steavoh hi, 

Dealing with multiple videos in parallel, especially on a single GPU, can be tricky because video processing can be heavily reliant on your GPU's capabilities. If you've already optimized your code to use all the 8 cores of your CPU, and the GPU is becoming the bottleneck, it indicates that the model inference is likely the most computationally intensive part of your process.

For your specific queries:

1. Passing a batch of frames to `model.track()` can possibly improve the collective inference time, because GPUs are designed to process large chunks of data in parallel. However, the actual performance may still depend on various factors, such as the batch size, size of each frame, and the model complexity.

2. As for improving the overall video processing time when you have multiple CPU cores but just a single GPU, you could consider dividing the load both on the CPU and GPU. For example, you could perform preprocessing tasks (like resizing frames, adjusting colors etc.) on the CPU in parallel, while the GPU is doing the inference computation. The key is to ensure that neither the CPU nor the GPU is idle while the other is working.

Unfortunately, managing these parallel tasks manually can be quite complex, given the asynchronous nature of CUDA calls by PyTorch and the fact that Python's Global Interpreter Lock (GIL) can make it tricky to achieve true multithreading.

Hope this provides some direction, and you can build from here to suit your specific use-case. Let me know if you need further clarification.
