### ISSUE TITLE
Detection with webcam not working on Mac M1

### ISSUE THREAD

**Issue by bnwlkr** [ultralytics/ultralytics#3932]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

Hello! I'm trying to test out detection on my Mac's webcam with the CLI command:

`yolo predict device=mps model=yolov8n.pt source=0 show=True`

Unfortunately the app crashes without ever showing the webcam feed. I've attached the full output. There is a section that says `ConnectionError: 1/1: 0... Failed to read images from 0`. I've double-checked that Terminal does have access to the webcam in System Settings.

[error.log](https://github.com/ultralytics/ultralytics/files/12155730/error.log)

### Environment

- Ultralytics YOLOv8.0.139 🚀 Python-3.11.4 torch-2.0.1 MPS (Apple M1 Pro)
- macOS Ventura 13.0.1, Apple M1 Pro 2021
- Python 3.11.4

### Minimal Reproducible Example

`yolo predict device=mps model=yolov8n.pt source=0 show=True`

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@bnwlkr 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. Webcam inference works for me. Make sure your iPhone is in airplane mode, as it might try to connect to your iPhone camera rather than your Macbook camera.


<img width="1710" alt="Screenshot 2023-07-25 at 04 21 55" src="https://github.com/ultralytics/ultralytics/assets/26833433/e26c8812-48fc-4df7-826f-8a99fa91d233">


If that doesn't help, we've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by bnwlkr** [comment]
Thanks for the comment @glenn-jocher. Turns out everything works when I change `source=0` to `source=1`. Not sure the reason, but hopefully this can help if someone gets the same problem.

**Comment by glenn-jocher** [comment]
Hello @bnwlkr, 

I'm glad to hear that you were able to find a workaround for your issue. In some cases, the source issue can arise due to the numbering of different imaging devices on your computer. Using 'source=1' instead of 'source=0' might mean that your webcam is being recognized as the second device instead of the first. 

This is useful information and could be beneficial for anyone who might face a similar issue. Thanks for sharing your solution! If you encounter any other problems or need further assistance, feel free to reach out.
