### ISSUE TITLE
Inference result.boxes seems not correct

### ISSUE THREAD

**Issue by nibi96** [ultralytics/ultralytics#3933]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm trying to understand the inference result when predicting an image but I got confused I hope you can help me answer it.
After predicting an image, I saw that it detected 4 cars on an image with class_id and conf corresponding `class_id=[7, 2, 2, 2]` and `conf=[0.94, 0.91, 0.83, 0.33]` as shown in the image below. 
However, when I log the result, it's not correct with the result_image (2nd image below) with `class_id=[7, 2, 2]` and `conf=[0.89, 0.88, 0.80]`. That means it misses 1 car and the conf of 3 remain cars are not correct as well.
If I use cv2 to draw the bounding boxes based on the log, the coordinate of the bounding boxes are still correct with the 3 cars I mentioned above (but conf is still not correct).
Can you help me understand why is it? Thank you.

My code (with `conf=0.15`):
<img width="595" alt="image" src="https://github.com/ultralytics/ultralytics/assets/101547455/73aeb3a2-7b85-4975-bd2d-4d5c1db5f88c">
Result image:
![snap_img](https://github.com/ultralytics/ultralytics/assets/101547455/5415ef94-763c-43d6-bd9e-1a47c5ac1294)
Result log:
<img width="644" alt="image" src="https://github.com/ultralytics/ultralytics/assets/101547455/2dbff21a-fae9-4f1e-a90d-fa4dda7c58c0">

**Comment by Laughing-q** [comment]
@nibi96 hi, from your code block, you got the result by `result=model(source, stream=False)`, you didn't pass `conf=0.15` here so it would use default value `conf=0.4` hence there are only 3 objects in result. It seems the visualized image is from `model.predict(source, conf=0.15...)` so there are 4 objects.

**Comment by nibi96** [comment]
> @nibi96 hi, from your code block, you got the result by `result=model(source, stream=False)`, you didn't pass `conf=0.15` here so it would use default value `conf=0.4` hence there are only 3 objects in result. It seems the visualized image is from `model.predict(source, conf=0.15...)` so there are 4 objects.

Thank you for the answer, then how about the conf of objects? such as Truck in the image has a conf=0.94 while in the log the conf=0.89? same as other cars

**Comment by glenn-jocher** [comment]
Hello @nibi96,

The confidence score discrepancies you're encountering might be due to the difference in confidence scores set for the visualization and non-visualized results.

In your code, for the visualized result, you set a lower confidence threshold (`conf=0.15`). This allows the model to detect objects with a wider range of confidences, including those with lower confidence scores.

On the other hand, when you're logging the results, unless specified otherwise, the confidence score threshold defaults to a higher value (`conf=0.4`). This means the model would disregard detections with lower confidence scores, hence the threshold value will bias your output towards detections with higher confidence scores.

If you want the confidences in your programmatic results to match the confidences shown in the visualized output, I recommend you to ensure that the same confidence threshold is also applied to the non-visualized results.

Thank you and please let us know if you have further queries.
