### ISSUE TITLE
defaul.yaml not found when convert to exe file using auto-py-to-exe

### ISSUE THREAD

**Issue by zulrais92** [ultralytics/ultralytics#3936]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

 I have Object Detection program but I simplify it as below statement.

I ran simple program where I just imported from the libraries ultralytics import YOLO. When I run in the PyCharm IDE, it had no problem.

After when I convert it to exe file using auto-py-to-exe, the error came and it state default.yaml not found.

Kindly please advise. :)

![Untitled](https://github.com/ultralytics/ultralytics/assets/139827853/c92f432b-d9d1-41ff-9b0e-e86ea4972e3d)
![eef93e9b-4954-454c-bb70-877587218a70](https://github.com/ultralytics/ultralytics/assets/139827853/a66a91fa-0d54-4b82-a278-11fbba4058be)

### Environment

ultralytics 8.0.141
Windows 10
Pycharm IDE

### Minimal Reproducible Example

import time
from ultralytics import YOLO
import cv2

while (True):
    print("Test")
    time.sleep((0.5))

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@zulrais92 hello, thanks for reaching out with your issue! 

It appears you're having trouble finding 'default.yaml' when converting your Python program to an executable file using auto-py-to-exe. 

The problem is most likely due to the different behavior between running python scripts and executable files. When running a python script, the current directory is where the script is located. However, when running an executable, the current directory is where the executable is run from. 

You should ensure that the 'default.yaml' is actually embedded in the exe file and is being referenced correctly. The configuration file must be within your executable's file layout structure to be found, or you should provide an absolute path to it. 

When generating the exe, consider whether there's an option to specify additional files that should be included in the executable's directory. If there is, make sure to include 'default.yaml' there. 

Remember that YOLO generates this file 'default.yaml' when the model is instantiated and it's used for loading model configuration. 

Your proactive attitude to researching the issue is much appreciated, and I hope you find this helpful!

**Comment by thefarwang** [comment]
Hello, I have encountered the same problem as you. Have you found a solution to the problem? If you have, please let me know. Thank you

**Comment by glenn-jocher** [comment]
@thefarwang hello! This issue typically pertains to how the executable is packaged, specifically including all necessary config files like `default.yaml`. Make sure your packaging process includes this file in the correct directory within the executable. If you have resolved it differently, kindly share your approach for the benefit of the community. Thanks! 👍

**Comment by ZeeshanKhalid2k01** [comment]
I encountered a similar issue to what @YuccaBrev described. In my case, I faced the error while utilizing --onefile with pyinstaller.

To tackle this problem:
Use the --onedir command alongside pyinstaller.
After generating the .exe, check if it's working properly. If the error persists, indicating the absence of 'data.yaml':
Verify if the 'ultralytics' folder is created by pyinstaller; if not, proceed to the next step.
Manually create the 'ultralytics\cfg' directory under the same directory as the generated .exe.
Add the 'data.yaml' file within the 'ultralytics\cfg' directory.
This adjustment enabled the .exe file to run successfully without encountering the missing 'data.yaml' error.

Hope this workaround helps!

**Comment by ZeeshanKhalid2k01** [comment]
I encountered a similar issue to what @zulrais92 described. In my case, I faced the error while utilizing **--onefile** with **pyinstaller**.

**### To tackle this problem:**

1. Use the **--onedir** command alongside pyinstaller.
2. After generating the .exe, check if it's working properly. If the error persists, indicating the absence of 'data.yaml':
3. Verify if the 'ultralytics' folder is created by pyinstaller; if not, proceed to the next step.
4. Manually create the 'ultralytics\cfg' directory under the same directory as the generated .exe.
5. Add the 'data.yaml' file within the 'ultralytics\cfg' directory.
6. This adjustment enabled the .exe file to run successfully without encountering the missing 'data.yaml' error.

Hope this workaround helps!

**Comment by glenn-jocher** [comment]
@ZeeshanKhalid2k01, thanks for sharing your solution! It's great to hear that switching to `--onedir` with pyinstaller and manually ensuring the 'data.yaml' is in the correct directory resolved the issue. This will definitely be helpful for others facing the same problem. 👍
