### ISSUE TITLE
What is the naming scheme for crops when tracking?

### ISSUE THREAD

**Issue by ketil-malde** [ultralytics/ultralytics#3942]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I've trained a detector and run it on a video, like so:

    yolo track model=$MODEL source=ex_2020_20200603_10.mp4 name=tracked_ex_2020_20200603_10.mp4 save save_crop save_txt

Note that the file name ends (except the mp4 suffix) in a number, which probably messes up things.  Labels are output with an object ID attached, and file names like `ex_2020_20200603_10_NNN`, where NNN is the frame number (variable digits).  Crops are output as `ex_2020_20200603_10MMM`, i.e. missing the underscore (which I think is a bug), and apart from the first MMM being empty and the next being 2, seems to just be a running count.  

My question is: how can I link the crops to the annotations in the labels?

**Comment by ketil-malde** [comment]
I added `_{frame}` to the crop name for video processing, and set the default separator in `increment_path` to '-'.  The former also fixes the bug that yolo is only able to output 9999 different crops before overflowing the counter - i.e., after 9998 crops, the last crop file gets overwritten repeatedly until the last detection.

```
diff --git a/ultralytics/engine/predictor.py b/ultralytics/engine/predictor.py
index 142fe63..fd4422a 100644
--- a/ultralytics/engine/predictor.py
+++ b/ultralytics/engine/predictor.py
@@ -178,7 +178,8 @@ class BasePredictor:
         if self.args.save_txt:
             result.save_txt(f'{self.txt_path}.txt', save_conf=self.args.save_conf)
         if self.args.save_crop:
-            result.save_crop(save_dir=self.save_dir / 'crops', file_name=self.data_path.stem)
+            result.save_crop(save_dir=self.save_dir / 'crops',
+                             file_name=self.data_path.stem + ('' if self.dataset.mode == 'image' else f'_{frame}'))
 
         return log_string
 
diff --git a/ultralytics/utils/files.py b/ultralytics/utils/files.py
index d6fe7b1..e4b13d6 100644
--- a/ultralytics/utils/files.py
+++ b/ultralytics/utils/files.py
@@ -78,7 +78,7 @@ def spaces_in_path(path):
         yield path
 
 
-def increment_path(path, exist_ok=False, sep='', mkdir=False):
+def increment_path(path, exist_ok=False, sep='-', mkdir=False):
     """
     Increments a file or directory path, i.e. runs/exp --> runs/exp{sep}2, runs/exp{sep}3, ... etc.
```

**Comment by glenn-jocher** [comment]
@ketil-malde hi there! Your solution to add `_` followed by the frame number to the crop name in video processing is a solid approach to uniquely identify crops across different frames. In settings where the number of crops exceeds 9999, this should effectively prevent the overwriting issue with the crop files that you encountered.

You are also right in changing the default separator in `increment_path` to '-' instead of an empty string. This indeed creates a clearer separation between the original filename and the increment number, leading to better readability and easier file management.

Thank you for your input and sharing this solution! I appreciate your dedication to improving YOLOv8. The changes you proposed will definitely streamline video and crop file processing. We constantly strive for improvements in our models, and user suggestions are an invaluable part of that process. We will review your suggestions and consider them in our future updates. Any updates will be noted in the commit messages and the changelogs. Keep up the good work, and thank you for being a part of the Ultralytics community!

**Comment by ketil-malde** [comment]
Thanks for the feedback, although you sound like an AI.  I presume the fix is simple enough to just copy into the code - or should I fork and submit a pull request?

**Comment by glenn-jocher** [comment]
@ketil-malde thank you for your feedback and your willingness to contribute. Regarding the changes you've made, the preferred way would be for you to fork the repository and submit a pull request with the changes you've implemented. This way, your changes can be reviewed thoroughly before being incorporated into the main codebase. Your attention to detail and initiative to improve the codebase is greatly appreciated, and we look forward to reviewing your pull request.
