### ISSUE TITLE
How to get prediction probabilities of non binary mask for every class.

### ISSUE THREAD

**Issue by hamzagorgulu** [ultralytics/ultralytics#3949]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I need to get the prediction probabilities of non binary masks for every class in instance segmentation task with yolov8. The input should be the image and the output should be in the size of (K, W, H) where K is the number of classes, W and H are width and height. The pixels should contain the pixelwise probabilities of the particular class in each mask.

**Comment by glenn-jocher** [comment]
@hamzagorgulu thank you for your question and for doing an initial search in our repository. 

With YOLOv8, the instance segmentation task yields a binary mask per detected instance rather than per-class. This is intrinsically a consequence of how the YOLO family of models is designed, which is predominantly centered around object detection.

To acquire pixel-wise probabilities for each class, a typical approach is to use semantic segmentation models designed for such tasks. These models usually output a K x W x H tensor where K is the number of classes, and W and H represent the width and height of the image, respectively. Each pixel in this tensor represents the probability of that pixel belonging to a particular class.

Remember that YOLOv8 is outstanding at object detection tasks, but for detailed per-class pixel-wise segmentations, consider looking into semantic segmentation models such as U-Net, DeepLabv3+ and others that might be more suitable for this specific task. You can also consider ensembling, where both the detection and segmentation models work together to produce your desired result.

I hope this clears up your question. Let me know if you need any further explanation.

**Comment by salihmarangoz** [comment]
@glenn-jocher I can see that thresholding of masks (with 0.5) is applied here: https://github.com/ultralytics/ultralytics/blob/2ba80e355a91b1c46b6622a4a342c8ca2a8feb0b/ultralytics/utils/ops.py#L635

I can get kinda-pixelwise probabilities by removing the thresholding part. Do you think it should be left like it is, or optionally skip mask thresholding? It may be useful for post-processing with GrabCut or some other traditional methods.

**Comment by glenn-jocher** [comment]
@salihmarangoz hi there,

Indeed, you're correct. The linked line of code is applying a threshold to the masks resulting in binary mask outputs for instance segmentation tasks. This is a common approach used to separate the object from the background in the mask by applying a threshold.

You can adjust this threshold value to meet the specific requirements of your application. Removing the thresholding part would give you the predicted probability of each pixel belonging to an object, instead of a binary 0 or 1 after thresholding. You're right in thinking that these probability-based masks could be beneficial for certain post-processing algorithms or other applications where a probability is desired over a binary decision.

Whether to change this in the code base comes down to the utility it adds for the broader user base and compatibility with the existing structure. Given the YOLO architecture's primary role in object detection and the computational and bandwidth implications of outputting full probabilistic masks, the current implementation with thresholding is chosen to maintain a balance.

I hope this answers your question. If you believe that this feature may benefit others, we would love for you to fork the repository and create a pull request with your feature addition. We always appreciate community contributions and ideas to improve the repository.

Thanks for your input!

**Comment by statmlben** [comment]
> [@salihmarangoz](https://github.com/salihmarangoz) hi there,
> 
> Indeed, you're correct. The linked line of code is applying a threshold to the masks resulting in binary mask outputs for instance segmentation tasks. This is a common approach used to separate the object from the background in the mask by applying a threshold.
> 
> You can adjust this threshold value to meet the specific requirements of your application. Removing the thresholding part would give you the predicted probability of each pixel belonging to an object, instead of a binary 0 or 1 after thresholding. You're right in thinking that these probability-based masks could be beneficial for certain post-processing algorithms or other applications where a probability is desired over a binary decision.
> 
> Whether to change this in the code base comes down to the utility it adds for the broader user base and compatibility with the existing structure. Given the YOLO architecture's primary role in object detection and the computational and bandwidth implications of outputting full probabilistic masks, the current implementation with thresholding is chosen to maintain a balance.
> 
> I hope this answers your question. If you believe that this feature may benefit others, we would love for you to fork the repository and create a pull request with your feature addition. We always appreciate community contributions and ideas to improve the repository.
> 
> Thanks for your input!

@salihmarangoz  Thanks for the detailed explanation! I really appreciate the thoughtful design decisions behind the current implementation.

I wanted to respectfully suggest a potential enhancement that might benefit some users: **optionally exposing probability masks** before thresholding.

**Background.** We have recently developed a new post-processing-like method called [RankSEG](https://github.com/rankseg/rankseg), which is based on probability masks and as an alternative to thresholding. We discussed the advantages of this method in detail at [NeurIPS 2025](https://openreview.net/pdf?id=4tRMm1JJhw) and in [JMLR](https://www.jmlr.org/papers/v24/22-0712.html), demonstrating that it outperforms thresholding or argmax in most segmentation cases. However, when we attempted to create an interface for YOLO, we found that the output consists only of binary masks.
