### ISSUE TITLE
Yolov8 GPU Device Question for Inference

### ISSUE THREAD

**Issue by arturovv21** [ultralytics/ultralytics#3953]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Multi-GPU

### Bug

Hi, I have a couple of questions:

1. I am trying to predict using multi-GPU. Is this possible? If so, what is the right command?

2. I am also unable to run a specific GPU, it always uses the first one. Is there a command to choose a specific GPU?

Thanks!

**System:**

Ultralytics YOLOv8.0.138 🚀 Python-3.11.4 torch-2.0.1 CUDA:0 (NVIDIA RTX A4500, 20187MiB)
Setup complete ✅ (64 CPUs, 125.6 GB RAM, 358.3/915.3 GB disk)
torch.version = 2.0.1
torch.version.cuda = 11.8
torch.cuda.is_available = True
Your machine has 4 CUDA-enabled GPUs.

```python
results = model.predict(
            source=tile_images,
            device=3, # doesn't matter if set to 0, 1, 2, 3, or even 10.
            conf=config['detection.confidence'],
            save=False,
            verbose=False,
            classes=[0,1,2,3,4]
        )
```

$ nvidia-smi
Tue Jul 25 09:37:10 2023      
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.56.06    Driver Version: 520.56.06    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A4500    Off  | 00000000:01:00.0 Off |                  Off |
| 33%   65C    P2   185W / 200W |   4899MiB / 20470MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A4500    Off  | 00000000:2C:00.0 Off |                  Off |
| 30%   45C    P8    24W / 200W |     13MiB / 20470MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA RTX A4500    Off  | 00000000:41:00.0  On |                  Off |
| 30%   54C    P0    81W / 200W |    497MiB / 20470MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA RTX A4500    Off  | 00000000:61:00.0 Off |                  Off |
| 30%   40C    P8    24W / 200W |     13MiB / 20470MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

### Environment

Ultralytics YOLOv8.0.138 🚀 Python-3.11.4 torch-2.0.1 CUDA:0 (NVIDIA RTX A4500, 20187MiB)
Setup complete ✅ (64 CPUs, 125.6 GB RAM, 358.3/915.3 GB disk)
torch.version = 2.0.1
torch.version.cuda = 11.8
torch.cuda.is_available = True
Your machine has 4 CUDA-enabled GPUs.

### Minimal Reproducible Example

```python
results = model.predict(
            source=tile_images,
            device=3, # doesn't matter if set to 0, 1, 2, 3, or even 10.
            conf=config['detection.confidence'],
            save=False,
            verbose=False,
            classes=[0,1,2,3,4]
        )
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@arturovv21 hi there, 

1. To answer your first question regarding multi-GPU prediction, currently, YOLOv8 doesn't support multi-GPU inference out of the box. The inference step is typically less computationally intensive than training, so it's common to run it on a single GPU.

2. Regarding your second question, you can specify the GPU device you would like to use for inference by setting the 'device' argument in the 'predict' function. However, it looks like you're encountering an issue where any assigned device number isn't respected by the function. This isn't the expected behavior, as assigning the 'device' argument should make the model run the inference on the selected GPU. The inability to select a specific GPU sounds like a potential bug and we appreciate you bringing this to our attention.

Would you mind reporting the bug in a separate GitHub issue? Please make sure to include as much detail as possible and, if possible, a minimum reproducible example. This would aid in the debugging process and help us resolve the issue.

Thank you for your keen observations and for contributing to improving YOLOv8!

**Comment by glenn-jocher** [comment]
@arturovv21 It looks like you're trying to use multi-GPU for prediction and also select a specific GPU for running your model. 

1. **Multi-GPU prediction**: YOLOv8 allows for data parallelism, which is typically used for training on multiple GPUs. However, for prediction (inference), it's a little more complicated because the data isn't split up in the same way it is for training. Therefore, multi-GPU prediction is not directly supported in Ultralytics YOLOv8. That said, you could technically implement multi-GPU prediction yourself by dividing your data across the available GPUs, running the model on each GPU separately, and then collating the results, but this would require custom code.

2. **Selecting a specific GPU**: You should be able to specify the GPU you want to use by setting i.e. `device=4`

**Comment by arturovv21** [comment]
Thanks @glenn-jocher .
1. **Multi-GPU prediction:** Understood, if this changes in the future please let us know.
2. **Selecting a specific GPU:** As shown in the example above, device=3 was assigned. However, only device 0 is working at 100% as shown in `$ nvidia-smi`. I tried other numbers, but it did not work either, only device 0 works. Any ideas?

**Comment by glenn-jocher** [comment]
Hello @arturovv21, 

1. **Multi-GPU prediction**: Sure, we will keep the community updated if there are changes related to multi-GPU prediction in the future.

2. **Selecting a specific GPU:** The behavior you're experiencing is unusual. The 'device' parameter in the 'predict' method is supposed to direct the model to use the specified GPU. If you're setting device=3, it should be utilising the GPU indexed at 3, not defaulting to 0. 

This might be a bug, or there might be something unexpected in your environment causing this. You could verify if other PyTorch operations respect the device selection on your setup. Otherwise, it may be helpful to print out the selected device just before the prediction operation to see if it's being set correctly. 

If none of these help, you may want to file a bug report with a minimal reproducible example so the developers can investigate the issue further. Thank you!

**Comment by Phirxian** [comment]
I had the same problem when performing inference on 4 GPUs for a multithreaded application, I wanted each thread to use a specific GPU for detection in videos.. The answer is on `ultralytics/engine/predictor.py` and `ultralytics/engine/model.py`. The following code allow to bypass the select_device function which cause the predict function to use the first gpu on a batch with single image.

```python
position = os.getpid() % min(args.core, args.total)
device = torch.device(position)

model = YOLO(args.model)
model.to(device)
        
predictor = model.smart_load('predictor')
predictor = predictor(overrides={
    'conf': 0.25,
    'mode': 'predict',
    'save': False,
    'verbose': False
})
predictor.device = device

predictor.model = AutoBackend(
    model.model, device=device,
    dnn=True,    fp16=True,
    fuse=True,   verbose=False
)

predictor.device = device
predictor.args.half = predictor.model.fp16
predictor.model.eval()

model.predictor = predictor
```

then you can simply use the predictor class `results = predictor(source=frame)`

**Comment by pderrenger** [comment]
Thanks @Phirxian for sharing your workaround for setting the GPU for prediction. It seems like you found a way to bypass the default device selection and manually assign a specific GPU to the predictor class for inference. 

While this solution is not part of the official YOLOv8 functionality, it's great to see the community sharing their workarounds and customizations. This could be beneficial for others facing similar issues with GPU selection. Thank you for sharing this with the community!

**Comment by thisisfatih** [comment]
You need to pass "cuda:" before the GPU number. Also it needs to be a torch.device object instead of string. 

So if you want to use GPU 1, when you're calling the predict function you need to pass:

`device=torch.device("cuda:1")
`

**Comment by glenn-jocher** [comment]
@thisisfatih Your clarification is indeed correct. When specifying the device for PyTorch operations, including YOLOv8's predict function, you should set the device as a `torch.device` object, not just as an integer or a string.

For accurate GPU selection during inference with YOLOv8, if you want to utilize the GPU with index 1, for example, you should initiate the torch.device object like so:

```python
device = torch.device("cuda:1")
```

And then pass it to the predict function:

```python
results = model.predict(
    source=tile_images,
    device=device,  # Use the torch.device object here
    conf=config['detection.confidence'],
    save=False,
    verbose=False,
    classes=[0, 1, 2, 3, 4]
)
```

This should direct the model to perform inference on the GPU you have specified by index. Thank you for mentioning this, and I trust that this will resolve the issue you're facing with GPU selection. If you run into further complications, please feel free to reach out.

**Comment by Phirxian** [comment]
@glenn-jocher Thanks for adding this feature, as it's only available since the commit #4911 
Please note that the issue about select_device is tagged as 'updating docstring' in the commit ....

**Comment by glenn-jocher** [comment]
Hello @Phirxian, it's fantastic to hear that the feature has been integrated into the repository, and thanks for noting the commitment that introduced it.

The process of continuously improving the YOLOv8 experience is spirited by community engagement. Updating docstrings and maintaining clear documentation are critical tasks that aid users in understanding how best to leverage new features and updates. Your attention to these changes helps ensure that others will be better informed about how to properly use the GPU selection feature.

I appreciate your involvement in improving the repository and sharing relevant updates. Keep up the great work, and always feel free to reach out with further questions, suggestions, or feedback!

**Comment by div2410** [comment]
HI @Phirxian Thank you for your multi GPU usage solution : https://github.com/ultralytics/ultralytics/issues/3953#issuecomment-1668671457

I have one questions here that what is exactly in min function args.core and args.total?

**Comment by Spyridonidis98** [comment]
> You need to pass "cuda:" before the GPU number. Also it needs to be a torch.device object instead of string.
> 
> So if you want to use GPU 1, when you're calling the predict function you need to pass:
> 
> `device=torch.device("cuda:1") `

I had the same problem, this work around worked perfectly.

**Comment by glenn-jocher** [comment]
@div2410 Glad that workaround helped. `args.core` and `args.total` are custom variables from @Phirxian’s script, not Ultralytics args; in that pattern they usually mean the number of worker processes/threads and the total GPUs to use, and `min(args.core, args.total)` just caps the device index so it stays in range. For the supported API, please see the [`Model.predict()` reference](https://docs.ultralytics.com/reference/engine/model/) and [`select_device()` reference](https://docs.ultralytics.com/reference/utils/torch_utils/). If you’re still seeing incorrect GPU assignment, please open a new issue since this thread is stale and include:

```bash
yolo checks
```

along with the full traceback/logs and a minimal reproducible example.
