### ISSUE TITLE
Training yolov8 with rectangular images

### ISSUE THREAD

**Issue by robertastellino** [ultralytics/ultralytics#3956]
Hello, 
I am trying to train a yolov8 model for object detection on Google Colab and I have a dataset with resolution 1068x800, so I wanted to set the imgsz value to this size, in order not to lose any information. I also read in the documentation for training of yolov8 that imgsz is the "size of input images as integer or w,h", which I interpreted as I can use not only square images, but also rectangular, with width w and height h (in my case w=1068 and h=800). So, in the command line I wrote `imgsz=[1068,800]`
but I get this error: 

Error executing job with overrides: ['model=yolov8s.yaml', 'data=/content/drive/MyDrive/TESI/Dati/Prova_Dataset_1000/data_1000.yaml', 'epochs=100', 'imgsz=[1068,800]', 'rect=True', 'project=/content/drive/MyDrive/TESI/Yolov8_models']
Traceback (most recent call last):
  File "/content/IVC-detection-PROVA/ultralytics/yolo/v8/detect/train.py", line 206, in train
    model.train(**cfg)
  File "/content/IVC-detection-PROVA/ultralytics/yolo/engine/model.py", line 193, in train
    self.trainer.train()
  File "/content/IVC-detection-PROVA/ultralytics/yolo/engine/trainer.py", line 177, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/content/IVC-detection-PROVA/ultralytics/yolo/engine/trainer.py", line 239, in _do_train
    self._setup_train(rank, world_size)
  File "/content/IVC-detection-PROVA/ultralytics/yolo/engine/trainer.py", line 195, in _setup_train
    self.set_model_attributes()
  File "/content/IVC-detection-PROVA/ultralytics/yolo/v8/detect/train.py", line 54, in set_model_attributes
    self.args.cls *= (self.args.imgsz / 640) ** 2 * 3 / nl  # scale to image size and layers
TypeError: unsupported operand type(s) for /: 'ListConfig' and 'int'

which I don't get when imgsz is only one number (meaning square images), in fact I can train my model, but with a resize that I don't want. 
What should I do in order to train yolov8 with my image size? Is it possible or should I resize my dataset?

Thank you in advance

**Comment by glenn-jocher** [comment]
@robertastellino hello,

Thanks for using YOLOv8 and providing detailed information about your issue!

The error you're encountering originates from the fact that the 'imgsz' is expected to be a single integer value instead of a list or tuple. In the code base, 'imgsz' is supposed to represent the resolution that an input image will be resized to. Even though the documentation suggests that it could accept width and height as separate values, it seems currently it is not supported, and the model is expecting square inputs. 

The error indicates an incompatibility when trying to perform operations on a 'ListConfig' object and an integer, because a 'ListConfig' object (in your case [1068, 800]) behaves differently compared to a single integer.

If you'd like to train YOLOv8 with your specific image size, we recommend resizing your dataset to a square resolution, such as 1024x1024 or 800x800, before training. Although this may not be the ideal solution, it will enable you to proceed with training your model. Alternatively, you could perform letterboxing on your images, adding padding to make them square while retaining the original aspect ratio.

We appreciate your feedback, and the documentation will be updated to clarify this point. We hope this will help you advance in your project, and we look forward to any further questions you may have!

Best regards,
Glenn
