### ISSUE TITLE
Yolov6 Train get problem

### ISSUE THREAD

**Issue by niiish32x** [ultralytics/ultralytics#3976]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I tried to train yolov6 by ultralytics as follow 
```python
from ultralytics import YOLO

model = YOLO("yolov6m.yaml").load("/home/nsh/tmp/ultralytics/weights/yolov6m.pt")  # build new model from scratch
model.train(data='coco.yaml',epochs=100,imgsz=640,batch=32)
```
I just follow yolov8 train docs and download the yolov6m.pt but it appears : 
![image](https://github.com/ultralytics/ultralytics/assets/49066537/fb462307-3892-453f-8914-abdebd79cde6)
I use  ```pip install yolov6```  and i successfully install yolov6 package  but it still doesn't work for yolov6 trainning.
 

### Environment

ultralytics 8.0.128
pytorch 2.0.1 
cuda 11.7

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@niiish32x it looks like the error is from your pt file. 
@glenn-jocher I don't think we support loading yolov6 pt file as pre-weights right?

**Comment by niiish32x** [comment]
@Laughing-q   you're right. i works for me

**Comment by glenn-jocher** [comment]
Happy to hear you were able to resolve the issue, @niiish32x! In Ultralytics YOLOv8, using pretrained weights from different versions might cause compatibility issues due to differences in architecture. Always ensure the pretrained weights correspond to the right architecture when training. Glad to see you could successfully train the model from scratch. If you run into any other issues in the future, feel free to ask. Happy training!
