### ISSUE TITLE
why best.pt(last.pt also same) and the epoch.pt's file size different? 

### ISSUE THREAD

**Issue by beautifulchoi** [ultralytics/ultralytics#3980]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I'm using Yolo v8 model and get best.pt and last.pt file.
also, for resuming training , I gave "save_preriod" parameter 10. so while every 10 epoch, I got epoch.pt

but the size of best.pt file and epoch.pt file is different. in my case, best.pt is around 130MB, but epoch.pt is over 700MB.

I tried to load the ckpt by "torch.load". and found different things between these two. in epoch.pt key of "optimizer" has weight tensors but not in best.pt.

then, how can best.pt retain the weight parameters? 

  

### Additional

![image](https://github.com/ultralytics/ultralytics/assets/87787966/908ee634-93fc-4570-9b8e-e23f1d1be4c7)

here's difference between two file sizes in my storage.

**Comment by glenn-jocher** [comment]
@beautifulchoi hello, thanks for your question! The difference you see in file size between `best.pt` and `epoch.pt` stems from the information each file retains. The `best.pt` file contains the model weights that produced the best validation results during training. On the other hand, the `epoch.pt` file contains not only the model weights but also the optimizer states at the checkpointed epoch. 

Storing the optimizer state is necessary for resuming training because it allows the model to pick up from where it left off, maintaining momentum in the optimization process. However, this extra information takes up additional storage, hence the larger file size for `epoch.pt`. 

In contrast, the `best.pt` checkpoints only need to store the model weights to make predictions or score validation data, which results in a smaller file size. The optimizer states are not necessary in this case, as the model is not expected to resume training from these weights.
