### ISSUE TITLE
raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e RuntimeError: Dataset 'D:\Project\AI light\datasets\data.yaml\train' error  [WinError 183]   ,     : 'D:\\Project\\AI light\\datasets\\data.yaml'

### ISSUE THREAD

**Issue by Filmans** [ultralytics/ultralytics#3994]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Dataset not found , missing path D:\Project\AI light\datasets\data.yaml\train, attempting download...
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\trainer.py", line 121, in __init__
    self.data = check_cls_dataset(self.args.data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\data\utils.py", line 302, in check_cls_dataset
    download(url, dir=data_dir.parent)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\downloads.py", line 260, in download
    dir.mkdir(parents=True, exist_ok=True)  # make directory
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
FileExistsError: [WinError 183] Невозможно создать файл, так как он уже существует: 'D:\\Project\\AI light\\datasets\\data.yaml'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\Project\AI light\traint_ai.py", line 4, in <module>
    model.train(data="D:\\Project\\AI light\\datasets\\data.yaml\\train", epochs=30)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\model.py", line 367, in train
    self.trainer = TASK_MAP[self.task][1](overrides=overrides, _callbacks=self.callbacks)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\models\yolo\classify\train.py", line 24, in __init__
    super().__init__(cfg, overrides, _callbacks)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\trainer.py", line 127, in __init__
    raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
RuntimeError: Dataset 'D:\Project\AI light\datasets\data.yaml\train' error  [WinError 183]   ,     : 'D:\\Project\\AI light\\datasets\\data.yaml'

### Environment

VS Code, Windows, Python 3.11.2

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Filmans hello, thank you for reaching out. It looks like the file path you are using as input in your data parameter is not correct. It points to a single file 'D:\Project\AI light\datasets\data.yaml', and appends a '\train' to the end, resulting in 'D:\Project\AI light\datasets\data.yaml\train', which is considered non-existent. Please ensure that you are passing the proper directory path to the 'train' folder, instead of the .yaml file. The 'data' argument should be the path to a .yaml file that contains paths to your training, validation, and test sets. Try correcting the path and re-running your code. Also, make sure that your 'data.yaml' file is correctly configured with valid paths. Hope this helps!

**Comment by Filmans** [comment]
> @Filmans hello, thank you for reaching out. It looks like the file path you are using as input in your data parameter is not correct. It points to a single file 'D:\Project\AI light\datasets\data.yaml', and appends a '\train' to the end, resulting in 'D:\Project\AI light\datasets\data.yaml\train', which is considered non-existent. Please ensure that you are passing the proper directory path to the 'train' folder, instead of the .yaml file. The 'data' argument should be the path to a .yaml file that contains paths to your training, validation, and test sets. Try correcting the path and re-running your code. Also, make sure that your 'data.yaml' file is correctly configured with valid paths. Hope this helps!

I have already moved to Google Colab.
Data from the data.yaml file:
train: /content/drive/MyDrive//AI light/datasets/train/images
val: /content/drive/MyDrive//AI light/datasets/train/images

nc: 2
names: ['daisy', 'roses']

roboflow:
  workspace: dataset-ai-rf0nt
  project: ai-detect-flowers
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/dataset-ai-rf0nt/ai-detect-flowers/dataset/1

Please let me know if there are any mistakes, and I'll correct them. If you need any additional information, please also let me know.

**Comment by Filmans** [comment]
@glenn-jocher , I have already moved to Google Colab.
Data from the data.yaml file:
train: /content/drive/MyDrive//AI light/datasets/train/images
val: /content/drive/MyDrive//AI light/datasets/train/images

nc: 2
names: ['daisy', 'roses']

roboflow:
  workspace: dataset-ai-rf0nt
  project: ai-detect-flowers
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/dataset-ai-rf0nt/ai-detect-flowers/dataset/1

Please let me know if there are any mistakes, and I'll correct them. If you need any additional information, please also let me know.

**Comment by Filmans** [comment]
@glenn-jocher , error: RuntimeError: Dataset 'data.yaml' error ❌ [Errno 2] No such file or directory: '/content/datasets/data.yaml/train'

**Comment by glenn-jocher** [comment]
@Filmans hello, from the error message it seems that there is an issue with the file location. The program is trying to find a directory path 'train' inside the file 'data.yaml', which isn't possible. 

From your description, it looks like the 'train' and 'val' paths in your 'data.yaml' file are correctly pointing to the folders containing your training and validation image sets. However, when passing this 'data.yaml' to the training function you should simply provide the path to the 'data.yaml' file not append with '/train'.

Additionally, please check that the 'data.yaml' file is located at the path 'content/datasets/data.yaml'. If it's located in another directory, you should provide the full path to the 'data.yaml' file in your command.

Lastly, ensure the paths to your 'train' and 'val' datasets within the 'data.yaml' file are correct and accessible. The error could also occur due to inaccessible dataset directories. 

Hope these suggestions help to resolve the issue! Let us know if you need further assistance.

**Comment by paulinavelasquez** [comment]
Hello, I am having a similar problem. But in relation to the fact that it was standardized that `datasets_dir` takes data first, even if I try to change it in `setting`, when executing the training it always assumes that it must first go through `data/` and then what I put in it, and I am having problems since my purpose is to train with different data sets.
![Screenshot from 2024-06-08 17-02-53](https://github.com/ultralytics/ultralytics/assets/41736073/1fd7bbf2-e7c5-4fbd-9cab-c3bea04628fd)
My `.yaml `file is like this:
```
test: test/images
train: train/images
val: val/images
names:
-crack
- patch
- pothole
nc: 3
```

I do not indicate patch because I need it not to be fixed but rather from where the `.yaml ` is located to call it. I was working in a kaggle environment where it worked very well for me, taking the patch from where the `.ymal` file was when I called it, but due to computational limitations I migrated to another workspace and now it has been standardized in this way and I am not being able to apply it for different subsets.

**Comment by glenn-jocher** [comment]
Hello @paulinavelasquez,

Thank you for reaching out and providing detailed information about the issue you're facing. Let's work through this together to find a solution.

### Issue Overview
It seems that the training script is defaulting to a `data/` directory prefix, which is causing issues when you try to specify custom dataset paths in your `.yaml` file. This behavior might be due to how the paths are being interpreted in your new environment.

### Suggested Solution
To ensure that the paths in your `.yaml` file are correctly interpreted relative to the file's location, you can use absolute paths or ensure that the working directory is correctly set before running the training script.

### Example `.yaml` Configuration
Here's an example of how you can structure your `.yaml` file with absolute paths:

```yaml
test: /absolute/path/to/test/images
train: /absolute/path/to/train/images
val: /absolute/path/to/val/images
names:
  - crack
  - patch
  - pothole
nc: 3
```

Alternatively, if you prefer to use relative paths, ensure that your script sets the working directory to the location of your `.yaml` file before initiating the training process.

### Code Example
If you're running your training script in a Python environment, you can set the working directory as follows:

```python
import os
from ultralytics import YOLO

# Set the working directory to the location of your .yaml file
os.chdir('/path/to/your/yaml/file')

# Load and train the model
model = YOLO("yolov8n-cls.pt")
results = model.train(data="data.yaml", epochs=100, imgsz=640)
```

### Verify Versions
Please ensure you are using the latest versions of `torch` and `ultralytics` to avoid any compatibility issues. You can update your packages using the following commands:

```bash
pip install --upgrade torch ultralytics
```

### Minimum Reproducible Example
If the issue persists, could you please provide a minimum reproducible example? This will help us better understand the problem and provide a more accurate solution. You can find guidelines on creating a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

### Additional Resources
For more information on dataset structure and configuration, you can refer to the [Ultralytics documentation](https://docs.ultralytics.com/datasets/classify/).

I hope this helps! Please let us know if you have any further questions or issues.

**Comment by paulinavelasquez** [comment]
Thanks for the reply. The way that managed to work so that it can recognize the `patch` is by placing the absolute `patch` in each `.yaml`, thank you very much for the guide.

**Comment by glenn-jocher** [comment]
Hello @paulinavelasquez,

Thank you for the update! I'm glad to hear that using absolute paths in your `.yaml` file resolved the issue. Absolute paths can indeed help avoid any ambiguity related to file locations, especially when working across different environments.

If you have any further questions or run into any other issues, feel free to reach out. We're here to help! 😊

In case you need to work with relative paths in the future, remember to set the working directory appropriately in your script, as shown in the previous example. This can help maintain flexibility and portability of your code across different environments.

Happy training, and best of luck with your project! 🚀
