### ISSUE TITLE
Trainer doesn't pass callbacks to Validator

### ISSUE THREAD

**Issue by maltelorbach** [ultralytics/ultralytics#3995]
During training, custom validator callbacks are not called because they are not passed to the Validator object instantiated by the trainer:
https://github.com/ultralytics/ultralytics/blob/b5ea8ce87266fb572474323f559128cd3510ab46/ultralytics/models/yolo/detect/train.py#L65-L68

Therefore the validator receives only the default callbacks but no custom callbacks.

I tried to find the commit responsible for the regression, but I couldn't find it. Possibly it was introduced during one of the recent refactoring in the Model interface.

Above example is from the `DetectionTrainer` but the same is true for the other tasks.

Below MWE should `sys.exit` before validation starts but it continues.
```python
import sys

from ultralytics import YOLO


def printme(trainer):
    print("CALLBACK PRINTME CALLED")
    sys.exit(1)


def train():
    model = YOLO(task="detect")
    model.add_callback("on_val_start", printme)
    model.train(epochs=1, data="coco128.yaml", val=True)


train()
```

**Comment by glenn-jocher** [comment]
@maltelorbach thank you for bringing this issue to our attention. We appreciate how succinctly you have illustrated the problem - this is indeed very helpful.

It appears that during training, custom validator callbacks aren't being invoked because they're not handed off to the Validator object that the trainer creates. To ensure that custom callbacks get propagated to the validator, they must be correctly passed to the Validator object when it's initiated.

You're accurate in your findings - the validator is presently only receiving the default callbacks, and not any custom ones. This would indeed cause the issue you're experiencing, where your script doesn't exit before validation starts as expected.

This might have been caused by a change during a recent refactoring of the Model interface. Looking into past commits to identify the exact point of regression might not be straightforward, but rest assured that we are taking this matter seriously.

We will address this issue internally and aim to rectify the error as soon as possible. This will certainly enhance the usability and flexibility of YOLOv8, particularly in complex projects where custom callbacks are essential.

We value your input, and we encourage you to continue providing insightful feedback.

**Comment by ThomasDeLange** [comment]
Hi, This problem is not solved yet unfortunately. Is there a possibility that this could be looked at? It is not as easy as adding _callbacks = self.callbacks in [ultralytics/ultralytics/models/yolo/detect/train.py](https://github.com/ultralytics/ultralytics/blob/b5ea8ce87266fb572474323f559128cd3510ab46/ultralytics/models/yolo/detect/train.py#L65-L68).
