### ISSUE TITLE
My exe with yolov8 keep looping

### ISSUE THREAD

**Issue by skkd113** [ultralytics/ultralytics#3997]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

When I run in the PyCharm IDE, it had no problem.

After when I convert it to exe file using auto-py-to-exe, the error came, it just keep looping 
![image_2023-07-27_215526914](https://github.com/ultralytics/ultralytics/assets/107360779/eb660f5d-b745-450e-9bd3-72057ddd5ac0)

### Environment

OS : Windows 10
Python : 3.10
pyinstaller : 5.13.0
ultralytics : 8.0.143

### Minimal Reproducible Example

```
from ultralytics import YOLO
import time
import os
import cv2
current_path = os.path.dirname(os.path.abspath(__file__))
data_path = os.path.join(current_path, "data")

model = YOLO('yolov8n.pt')
def load_model():
    print("Loading model...")
    try:
        results = model(os.path.join(current_path, "docs", "rune_screenshots", "dragon.png"),show=True)
        print("Done")
    except Exception as e:
        print("Error:", str(e))
        raise  # Raise the exception to see the full traceback
print("A")
load_model()
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by uzairkabeer1** [comment]
I'm experiencing the same issue with the below simple code:

`from ultralytics import YOLO

model = YOLO("yolov8n.yaml")

results =model.train(data="config.yaml", epochs=100)
`
The mode keep looping and looping and throws an error like:
 

` raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.`

And after that the whole process just stopped

**Comment by glenn-jocher** [comment]
@skkd113 this error usually happens because Python's multiprocessing module is trying to start a new process before the current process has finished. It's common when running your script in .exe format or when having code in the global scope that initiates process when it’s imported. Specifically, Python's multiprocessing requires that the __name__ guard ("if __name__ == '__main__':") to be present in your script.

You should also make sure you aren't using globals that aren’t picklable. This can also cause multiprocessing to fail. A way around this is to re-engineer your code to only use variables that are initialized within the function being called by your process.

In some cases, depending on the way your environment is set up, you might also need to add `freeze_support()` to your main function to produce an executable. Please have a look into proper usage of Python's multiprocessing library, `freeze_support()`, and the `__name__` guard. This will surely help alleviate your problems.

**Comment by skkd113** [comment]
@glenn-jocher i tried both but still bugged, it only happens when i set device = 'cpu'

**Comment by glenn-jocher** [comment]
@skkd113, thank you for providing additional information. It seems that the issue might be related to GPU and CPU compatibility of your PyTorch version. When you compiled your program to an executable on a system with a GPU, it might have included some libraries that are specifically tied to GPU computation. 

When you tried to run the same executable on a system without a GPU, it might be causing this constant loop because it's trying to use GPU-specific libraries that don't exist on the CPU-based system. 

Consider compiling your executable on the system without a GPU so that it uses the appropriate CPU-based libraries. Also, ensure that the correct version of PyTorch is installed on each system (a version that is compatible either with or without GPU, based on the system requirement). 

I hope this helps! Let us know if the issue persists.

**Comment by skkd113** [comment]
@glenn-jocher I tried converting my project to an exe file on a PC without a GPU, but the problem still occurred. I also tried downgrading the PyTorch CPU version, but the problem still occurred.
After that i try to add a GUI with 1 button to my project, it not loop anymore, but when ever i click the button, another GUI appears and the old one became "not responding".
If i click the button in the new GUI, another appears. If I close the new GUI, the old GUI works
https://youtu.be/Ce_ZTL9vBm8

```
import tkinter as tk
from tkinter import filedialog
from ultralytics import YOLO
import time
import cv2
import time


model = YOLO('yolov8n.pt')

def load_model():
    print("Loading model...")
    try:
        file_path = filedialog.askopenfilename(title="Select an image file", filetypes=[("Image files", "*.png;*.jpg;*.jpeg")])
        if not file_path:
            print("No file selected.")

        results = model.predict(file_path, device='cpu', show=True)
        print("Done")
    except Exception as e:
        print("Error:", str(e))
        raise


if __name__ == "__main__":
    root = tk.Tk()
    root.title("YOLO Model GUI")
    root.geometry('200x100')
    btn_load_model = tk.Button(root, text="Load Model and Predict", command=load_model)
    btn_load_model.pack(pady=20)
    root.mainloop()

```
I then tried to fix it temporarily, by scanning through the running processes and close the duplicated procress.
It works, but i want a real fix

```
import tkinter as tk
from tkinter import filedialog
from ultralytics import YOLO
import time
import cv2
import psutil
import time
import kthread

model = YOLO('yolov8n.pt')

def load_model():
    print("Loading model...")
    try:
        file_path = filedialog.askopenfilename(title="Select an image file", filetypes=[("Image files", "*.png;*.jpg;*.jpeg")])
        if not file_path:
            print("No file selected.")

        results = model.predict(file_path, device='cpu', show=True)
        print("Done")
    except Exception as e:
        print("Error:", str(e))
        raise


def get_latest_process():
    latest_time = 0
    latest_process = None

    for proc in psutil.process_iter(['pid', 'name', 'create_time']):
        if proc.info['name'] == process_name:
            start_time = proc.info['create_time']
            if start_time > latest_time:
                latest_time = start_time
                latest_process = proc

    return latest_process

def get_running_processes():
    running_processes = []
    for proc in psutil.process_iter(['pid', 'name']):
        if proc.info['name'] == process_name:
            running_processes.append(proc)

    return running_processes
def get_own_process_name():
    current_process = psutil.Process()
    return current_process.name()

def check_and_close_latest_process():
    while True:
        time.sleep(0.1)
        running_processes = get_running_processes()
        if len(running_processes) >= 2:
            latest_process = get_latest_process()

            if latest_process:
                try:
                    print(f"Closing latest process: {latest_process.info['name']} (PID: {latest_process.info['pid']})")
                    latest_process.terminate()
                except psutil.NoSuchProcess:
                    pass
                except psutil.AccessDenied:
                    print(
                        f"Access denied to terminate process: {latest_process.info['name']} (PID: {latest_process.info['pid']})")
                except Exception as e:
                    print(
                        f"Error occurred while terminating process: {latest_process.info['name']} (PID: {latest_process.info['pid']}): {str(e)}")


if __name__ == "__main__":
    root = tk.Tk()
    root.title("YOLO Model GUI")
    root.geometry('200x100')
    btn_load_model = tk.Button(root, text="Load Model and Predict", command=load_model)
    btn_load_model.pack(pady=20)
    process_name = get_own_process_name()
    thread = kthread.KThread(target=check_and_close_latest_process)
    thread.start()
    root.mainloop()
```

**Comment by glenn-jocher** [comment]
@skkd113 thank you for providing a detailed explanation of the issue you're experiencing and the steps you've taken to trouble-shoot it.

I believe the problem you're facing might be due to the nature of how multi-threading works in Python, particularly when mixed with GUI operations or when using a library, such as YOLO, that internally uses multi-threading or multiprocessing.

Python TKinter UI and the YOLO model prediction are both intensive tasks and should run on separate threads to avoid one blocking the other. However, managing threads in Python can be tricky, especially with shared resources or subprocesses spawned by these threads. When you click your button, it fires the `command=load_model` function which does not return until the model has finished predicting. During this time, your UI might not respond because it's waiting for this function to return.

Adding a check for surplus processes as you've done in your temporary fix can work, but it's more of a patch than a solution to the actual problem.

A better approach could be to run the model prediction task in a separate thread or process that updates the UI once the prediction is ready. This way, the UI remains responsive. Also, encapsulating the model prediction code section within a function that is then called by a separate thread might help to stop the spawning of an extra process. Thus, the UI and the prediction tasks would run independently, without blocking each other or creating extra processes. Remember to also manage shared resources appropriately to avoid issues with data consistency or process synchronization.

Let me know if this helps you understand the problem better, and do reach out if you have further questions.

**Comment by MitchelldeVrees** [comment]
Hi I am running into the same issue.  I tried adding a thread to the code but it still happens.  But this also only happens when I run it as a .exe.
```
import os
from tkinter import filedialog
from PIL import Image, ImageTk
import tkinter as tk
import threading
from ultralytics import YOLO
import cv2
from grabcut import getLengthBar
model = YOLO('best.pt')

class MyApp:
    def __init__(self, master):
        self.master = master
        master.title("My App")

        self.image_dir = ""
        self.image_files = []
        self.current_index = 0

        self.select_dir_button = tk.Button(master, text="Select Directory", command=self.select_directory)
        self.select_dir_button.pack()

        self.image_label = tk.Label(master)
        self.image_label.pack()

        self.prev_button = tk.Button(master, text="Previous", command=self.show_previous_image)
        self.prev_button.pack(side="left")

        self.next_button = tk.Button(master, text="Next", command=self.show_next_image)
        self.next_button.pack(side="right")

    def select_directory(self):
        self.image_dir = filedialog.askdirectory()
        self.image_files = [f for f in os.listdir(self.image_dir) if os.path.splitext(f)[1] in (".jpg", ".png")]

        if self.image_files:
            self.current_index = 0
            self.show_image()

    def show_image(self):
        image_path = os.path.join(self.image_dir, self.image_files[self.current_index])

        # Create a new thread to run the YOLO model
        thread = threading.Thread(target=self.run_yolo_model, args=(image_path,))
        thread.start()

        thread.join()

        self.update_ui(image_path)

    def run_yolo_model(self, image_path):
        # Load the image and run it through the YOLO model
        image = cv2.imread(image_path)
        results = model.predict(image)

        # Store the results in an instance variable
        self.results = results

    def update_ui(self, image_path):
        # Process the image and display it in the GUI
        if not self.image_files:
            return

        results = self.results

        for r in results:
            masks = r.masks  # Masks object for segmentation masks outputs
            mask = masks.data[0].numpy()
            self.pixels = cv2.countNonZero(mask)
            mask = mask.astype('uint8')  # Convert to uint8
            self.lengthRedBar= getLengthBar(image_path) 

            if self.lengthRedBar is None:
                print("Red bar not found. Skipping to the next image.")
                self.next_image()
                break 

            contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
            if len(contours) != 0:
                # the contours are stored as a NumPy array of (x,y) coordinates of the boundary points of the object
                largest_contour = max(contours, key=cv2.contourArea)  
                perimeter = cv2.arcLength(largest_contour, True)  # Perimeter in pixels

            im_array = r.plot()  # plot a BGR numpy array of predictions
            im = Image.fromarray(im_array[..., ::-1])  # RGB PIL image
            photo = im.resize((300, 300))
            photo = ImageTk.PhotoImage(photo)

            # Display the image in the GUI
            self.image_label.config(image=photo)
            self.image_label.image = photo


    def show_previous_image(self):
        if self.image_files:
            self.current_index = (self.current_index - 1) % len(self.image_files)
            self.show_image()

    def show_next_image(self):
        if self.image_files:
            self.current_index = (self.current_index + 1) % len(self.image_files)
            self.show_image()

root = tk.Tk()
app = MyApp(root)
root.mainloop()
```

**Comment by glenn-jocher** [comment]
@MitchelldeVrees it looks like the issues you're encountering have persisted despite your efforts to resolve them by integrating multithreading into your code. I understand how challenging this situation can be.

A potential cause for the app not responding might be that your Tkinter GUI is on the main thread and the YOLO model is on a different thread. The two may be blocking each other.

Thread management in Python, particularly when involving subprocesses or GUI operations, can be complex. Since you mentioned it only happens when you turn your script into an .exe file and get images from a directory, it's possible that the procedure of reading and processing the images might be blocking the main thread resulting in the app becoming unresponsive.

You can consider handling image loading and model prediction in a separate thread. This would prevent the main thread, where your UI is running, from blocking due to these lengthy operations. 

Moreover, Tkinter isn't entirely thread-safe, meaning it's best to be careful when communicating between the main thread and worker threads to prevent issues, for example, possibly using queues to safely pass results to the UI thread.

Furthermore, regarding the .exe issue, please make sure that your packaging tool is correctly bundling all the required libraries and resources. Some of them may behave differently when run from an interpreted script versus a packaged executable.

Lastly, please ensure that the threading is shut down properly when the application is exited. If not done so, there may be threads running in the background consuming resources.

I hope these insights guide you in resolving your problem. Let us know if you have any more questions.

**Comment by DNJ-JINI** [comment]
@glenn-jocher 
For me also the same issue. The exe file is looping.
I have the model trained on yolov8segmentationand created the exe using pyinstaller in a CPU machine. The code is doing prediction of images on a directory. 
I am attaching the screenshot of the same. Can you please help me to solve this issue.
In the code after printing the file_path(line49) again the code is starting from the beginning and it continues. 

![image](https://github.com/ultralytics/ultralytics/assets/67704244/61e08ad2-fe16-45cb-8bce-845acd9fb834)

**Comment by glenn-jocher** [comment]
@DNJ-JINI thank you for reaching out with your issue regarding the executable file looping when using YOLOv8 for image prediction on a directory. Based on the behavior you're describing, it appears there may be a recursion or an unintended loop occurring within your implementation.

Without examining the specific details of your code, it may be challenging to pinpoint the exact problem. However, this type of looping often suggests that there could be a logic error within the portion of your code that loads and processes the images. Consider checking any iteration or conditionals related to the directory processing to ensure they are functioning as intended.

Another aspect to consider is the environment difference between your development setup and the execution context of the .exe file. Sometimes, path handling, permissions, or resource accesses may behave differently in the packaged application environment. Ensure that the model can access the image directory correctly and there are no permissions issues that could cause your code to restart or fail to progress.

Lastly, if you have incorporated any exception handling in your code, make sure that you're logging or handling the exceptions adequately. An unhandled exception or error within your script could be causing the script to restart or loop inadvertently.

If you continue to experience issues, we recommend going through your code's logic related to image processing and executable creation step by step to diagnose where exactly it starts to loop and why it might be reverting to the beginning.

**Comment by DNJ-JINI** [comment]
@glenn-jocher Thanks for the suggestions.

The .py file used for creating executable is working proper and there is no looping issue. Below is the code that used to create executable for your reference


import os
import time
import datetime
from ultralytics import YOLO
import cv2
import torch
from torchvision import io
model_path = "./best.pt"

image_dir ="./img_input"
output_dir = "./outs/"
if not os.path.exists(output_dir ):
   os.makedirs(output_dir)

print(model_path)
print(image_dir)
print(output_dir)

model = YOLO(model_path)
print("model loaded......")

def predict_image_dir(image_dir):
    for file_name in os.listdir(image_dir):
        if file_name.endswith('.jpg') or file_name.endswith('.png')or file_name.endswith('.jfif'):
            print(file_name)
            file_path = os.path.join(image_dir,file_name)
            print(file_path)
            model.predict(source =file_path , show = False, save=True)
            cv2.waitKey(0)
 if __name__ == "__main__":
    fire_seg_image_dir(image_dir)
    
This is the basic code used to make sure the exe is working proper. On running the exe it will print the filepath after that the looping starts and again it starts printing print(model_path)
print(image_dir)
print(output_dir)
print("model loaded......")

**Comment by skkd113** [comment]
> @glenn-jocher Thanks for the suggestions.
> 
> The .py file used for creating executable is working proper and there is no looping issue. Below is the code that used to create executable for your reference
> 
> import os import time import datetime from ultralytics import YOLO import cv2 import torch from torchvision import io model_path = "./best.pt"
> 
> image_dir ="./img_input" output_dir = "./outs/" if not os.path.exists(output_dir ): os.makedirs(output_dir)
> 
> print(model_path) print(image_dir) print(output_dir)
> 
> model = YOLO(model_path) print("model loaded......")
> 
> def predict_image_dir(image_dir): for file_name in os.listdir(image_dir): if file_name.endswith('.jpg') or file_name.endswith('.png')or file_name.endswith('.jfif'): print(file_name) file_path = os.path.join(image_dir,file_name) print(file_path) model.predict(source =file_path , show = False, save=True) cv2.waitKey(0) if **name** == "**main**": fire_seg_image_dir(image_dir)
> 
> This is the basic code used to make sure the exe is working proper. On running the exe it will print the filepath after that the looping starts and again it starts printing print(model_path) print(image_dir) print(output_dir) print("model loaded......")

![image](https://github.com/ultralytics/ultralytics/assets/107360779/1b01dd8b-79c9-47cc-8af8-38ae6c5e1324)
try this

**Comment by glenn-jocher** [comment]
@DNJ-JINI i understand that the executable created from your Python script is exhibiting a looping behavior, though the original script runs as expected. It's worth noting that such issues can sometimes occur due to differences in the environment where the script runs and the compiled executable.

When a Python script is turned into an executable using tools like PyInstaller, the tool bundles the Python interpreter and all necessary modules into a single package. This can sometimes lead to unforeseen issues, including environmental differences or module misinterpretations. It's essential to consider these factors when troubleshooting.

Since the code runs correctly as a Python script but not as an executable, you may want to review the configuration used during the packaging process. It includes verifying that all necessary dependencies are correctly accounted for and that there aren't any issues related to relative paths, especially since paths can sometimes be handled differently in the context of an executable.

Additionally, make sure to review the sections of your code that provide output or logging information, as these are the areas that seem to repeat according to your message. It could be beneficial to add more detailed logging around these areas to help identify exactly where the repetition starts.

While I cannot pinpoint the exact issue without further details, you may also want to consider if there's any code that might inadvertently cause the program execution to circle back to the beginning, such as an uncaught exception or a recursive call not present in your snippet.

Investigating these areas and adding comprehensive error handling—if not already implemented—might provide further insights into the behavior you're observing. If certain conditions are causing your application to restart or loop, proper error handling should allow you to capture and understand these events.

Since this seems to be a problem specifically related to the executable and not the Python script itself, extra attention to the packaging process and the execution flow of your application in the compiled form may help in resolving the issue.

**Comment by DNJ-JINI** [comment]
> > @glenn-jocher Thanks for the suggestions.
> > The .py file used for creating executable is working proper and there is no looping issue. Below is the code that used to create executable for your reference
> > import os import time import datetime from ultralytics import YOLO import cv2 import torch from torchvision import io model_path = "./best.pt"
> > image_dir ="./img_input" output_dir = "./outs/" if not os.path.exists(output_dir ): os.makedirs(output_dir)
> > print(model_path) print(image_dir) print(output_dir)
> > model = YOLO(model_path) print("model loaded......")
> > def predict_image_dir(image_dir): for file_name in os.listdir(image_dir): if file_name.endswith('.jpg') or file_name.endswith('.png')or file_name.endswith('.jfif'): print(file_name) file_path = os.path.join(image_dir,file_name) print(file_path) model.predict(source =file_path , show = False, save=True) cv2.waitKey(0) if **name** == "**main**": fire_seg_image_dir(image_dir)
> > This is the basic code used to make sure the exe is working proper. On running the exe it will print the filepath after that the looping starts and again it starts printing print(model_path) print(image_dir) print(output_dir) print("model loaded......")
> 
> ![image](https://user-images.githubusercontent.com/107360779/281105881-1b01dd8b-79c9-47cc-8af8-38ae6c5e1324.png) try this

@skkd113 Thanks for the solution.
Looping issue solved by using this multiprocessing.freeze_support()

**Comment by glenn-jocher** [comment]
Hello @DNJ-JINI,

Thank you for sharing details about the executable creation from your YOLOv8 model. I'm glad to hear that your Python script is running correctly without any unexpected looping. However, I understand that creating an executable using PyInstaller is causing the program to loop.

This is indeed an unusual occurrence since the original script functions without issue. When creating executables with PyInstaller, especially from complex applications such as those involving deep learning models like YOLOv8, it's critical to ensure that the environment within the executable mirrors the development environment as closely as possible. Given that your script involves file system operations and a machine learning model loaded from a file, it is possible that file paths or environment variables are not being interpreted the same way within the packaged executable.

Since adding `multiprocessing.freeze_support()` resolved the looping issue for you, it suggests that the problem may have been related to the way multiprocessing is handled within the executable. `freeze_support()` is designed to allow the proper functioning of multiprocessing, especially when an application is being frozen to create a Windows executable.

It's always a good practice to double-check your program flow and ensure that all external dependencies are packaged correctly and necessary initializations like `freeze_support()` are in place for the environment. This helps in avoiding execution anomalies post-packaging.

Thank you for reaching out, and I'm pleased that you've managed to solve the looping issue in your executable. If you have any further questions or run into additional challenges, please feel free to ask. We're here to support you in your usage of YOLOv8, and we want to ensure you have a smooth experience in deploying your models.

**Comment by DNJ-JINI** [comment]
@glenn-jocher Thanks for the support

**Comment by glenn-jocher** [comment]
@DNJ-JINI you're welcome! If you have any more questions or need assistance in the future, feel free to reach out. The YOLO community and the Ultralytics team are always here to help. Good luck with your projects using YOLOv8!
