### ISSUE TITLE
I'm having some problems with pose

### ISSUE THREAD

**Issue by sarpx** [ultralytics/ultralytics#4012]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

1.  in the mosaic I can see that the main object box is not scaled correctly.

I don't think it's an error in the calculations because I'm using it in other running applications.

2. I can't see the exposure points neither in the mosaic nor in the results. And the training ends very quickly.

Possible causes.. When normalizing the exposure points, should I use the h,w ratios of the main subject or the image?

**Comment by glenn-jocher** [comment]
@sarpx thank you for raising this issue and for thoroughly checking the existing discussions before asking.

1. If the main object bounding box in the mosaic does not appear to be scaled correctly, this could be due to the automatic mosaic generation process. The YOLOv8 mosaic system adjusts image and bounding box sizes to fit within a single output mosaic, and the resizing process may not be visually consistent with the original scale.

2. If you don't see the pose keypoints in the mosaic or results, and the training ends quickly, this might indicate there are challenges with your pose-point annotations or how they are being processed. When normalizing keypoints, you should factor in the original image dimensions (h, w) rather than the main subject. This is because, during training, the transforms are applied based on the overall image dimensions, not individual objects.

Ensure that your pose/keypoint annotations are correctly formatted and normalized. If your training still finishes prematurely, further investigate your dataset integrity, pose annotations, or training configurations. Note that without detailed visibility into your specific data setup, it's challenging to provide a definitive answer.

I hope this clarifies things for you. Feel free to get back to us with any more queries or if you would like to provide more details. Happy coding!

**Comment by sarpx** [comment]
@glenn-jocher  Thank you for your interest.
I don't think there is a problem in normalizing the center points according to the picture because I use the same codes in other yolo applications and it does not cause any problems.
Also mosaic view other segmentation and detection works well. But while the dimensions are correct in pose mosaic, it seems that there are problems in placing. There seems to be a problem, especially with images that have been rotated left and right.
When I start the training, the detection girl works, but I can see that the points do not enter the training, this made me think that there may be a problem, because if the data is corrupt, it gives a warning, the training ends quickly without any warning and the detection part is trained.

**Comment by glenn-jocher** [comment]
@sarpx thank you for your detailed description. It helps to better understand the situation.

In regards to the normalization of the center points, I agree with your analysis. If the same process hasn't caused any problems in your other YOLO applications, then it should function correctly with YOLOv8 as well.

Considering that the pose keypoints placements are struggling particularly with rotated images, this might suggest that the augmentation or transformations applied during the training process could be influencing this behavior. More specifically, the keypoints might need additional adjustments once the image is rotated.

If your training ends quickly without any warning, and only the detection part is trained, it might indicate that the pose keypoints aren't being engaged in the training process as expected. This could be due to factors such as the particular configuration of loss functions or layers in the model architecture when incorporating the pose estimation task.

While it's challenging to provide a precise solution without direct access to your specific setup, I would recommend reviewing the data pipeline specifically catering to pose keypoints for any irregularities, also focusing on how transformations are applied and if these transformations correctly adjust the keypoints. 

Do let us know if you have further updates or any more queries as we're more than ready to assist.

**Comment by sarpx** [comment]
@glenn-jocher Thank you for your interest. Here's what's confusing me. No key points appear in the mosaic created for the control when entering the training. If there are no key points in the mosaic when starting the training, shouldn't this training start and give an error? There is probably a mistake there. Even if I made a mistake in the pose points, I should have seen at least a few ridiculous spots in the mosaic. No key points appear in the mosaics (train_batch) before entering the training, although the points are all between 0 and 1 when I checked visually.
Also, if you remember in the early part of the road, the bounding boxes were not completely overlapping in these right-left transformations. You fixed it later. I think Poze is still in the primitive stage and it seems like most of your experiences have not been reflected..

**Comment by glenn-jocher** [comment]
@sarpx, thank you for your further clarification. We appreciate your detailed situation analysis and your patience in dealing with these issues. 

Certainly, the pose estimation model should provide an error if there are no keypoints detectable in the provided dataset. If no keypoints are visible in the mosaic, this might suggest an issue either with the input data not being correctly recognized by the model or with the visual rendering of keypoints itself.

The keypoints all being normalized between 0 and 1 seems to indicate that the annotation normalization process is working correctly. However, if these points aren't showing up in the mosaic, it suggests that either these annotations aren't being correctly assigned to their respective images or there's a problem in how the mosaic is visualizing these keypoints.

As for the bounding boxes not completely overlapping in transformations, I apologize for the inconvenience you experienced. We've since made updates to the bounding box transformations, and I'm glad to hear you noticed the improvement. We're always improving and iterating on our models to offer the best possible performance.

Our pose estimation model is indeed a more recent addition to the YOLOv8 family, and while we strive to make it as robust and efficient as possible, there may be a few quirks we're still working through. We appreciate your understanding and patience as we continue to develop and refine it.

Please note that without hands-on access to your specific setup, it is hard to provide a precise solution, but I hope this general guidance is helpful. Your insights and experiences are of great value in improving our frameworks. Thank you for your time and understanding.

**Comment by sarpx** [comment]
Thank you for your kind return. It is our duty to carry the YOLO family to a better level here. I am aware of the legendary sacrifice you have shown and I sincerely want you to get better. The pose thing is important :)
