### ISSUE TITLE
Yolov8 Classification Prediciton in C++ / OpenCV

### ISSUE THREAD

**Issue by andrewwetzel23** [ultralytics/ultralytics#4014]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am attempting to run the predictions of a Yolov8 classification model in C++ using the OpenCV DNN library. I have been successful in using a detection model using the code found [here](https://github.com/JustasBart/yolov8_CPP_Inference_OpenCV_ONNX/tree/minimalistic), but have been unable to get accurate results with a classification model. I am running the same model at the same image size as the `yolo classify predict` cli command. I get the expected results from the yolo prediction but when running the following code in C++, the values of my four classifications are always: [0, 1 or Near 1, 0 or near 0, 0 or near 0].

```
    std::string imagePath = "imagePath";
    std::string modelPath = "onnxPath";

    cv::dnn::Net net = cv::dnn::readNetFromONNX(modelPath);

    cv::Mat blob = cv::dnn::blobFromImage(image, 1.0, cv::Size(256, 256), cv::Scalar(), true, false); 

    net.setInput(blob); 
    output = net.forward();
    std::cout << output << std::endl;
```

The onnx model was exported with the following command:
`yolo classify export model=best.pt format=onnx opset=12`

Is this a known issue or am I using a bad approach? 

Thanks in advance

**Comment by glenn-jocher** [comment]
@andrewwetzel23 hello and thank you for bringing this up. The Ultralytics team appreciates your effort in exploring new avenues of implementation and debugging the code.

It seems like you're on the right track with YOLOv8 classification model in C++ with OpenCV DNN! But if you're seeing unexpected classification results, there could be a few potential issues at play here.

Given your results of [0, 1 or Near 1, 0 or near 0, 0 or near 0], it seems as though the model is only predicting one class confidently and descending into uncertainty for the rest. This could be due to a variety of reasons such as an issue with the way the images are being preprocessed before they are passed through the network or the model not being correctly loaded.

Regarding image preprocessing, ensure your data are being processed identically in the Python code and C++ code.

Next, please check if the model you're using has identical architecture and weights to the one being used in the OpenCV DNN implementation.

Lastly, since OpenCV's DNN module tends to lag behind other libraries in terms of support for new layers and operations, there could be some layer or function from the ONNX model that it's not handling appropriately. Remember that OpenCV's DNN module does not inherently support all layers and operations present in ONNX. So, it might skip some layers from the model during loading, potentially leading to inaccurate results.

Currently, Ultralytics doesn't have any known issues regarding YOLOv8 classification models trained and exported with Ultralytics software producing discrepant results in C++ with OpenCV DNN. Still, it's important to consider the constraints and limitations of OpenCV's DNN module while debugging.

Thank you again for your question, and I hope these suggestions allow you to fully leverage the capabilities of the YOLOv8 model in a C++ / OpenCV setting. Let us know how it goes!

**Comment by zys20170917** [comment]
你可以试试归一化
cv::Mat blob = cv::dnn::blobFromImage(image, 1.0 / 255.0, cv::Size(224, 224), cv::Scalar(), false, false);

**Comment by zys20170917** [comment]
你可以试试归一化
cv::Mat blob = cv::dnn::blobFromImage(image, 1.0 / 255.0, cv::Size(224, 224), cv::Scalar(), false, false);
我的size是224

**Comment by glenn-jocher** [comment]
Hello! Thank you for the suggestion. In your code, you're demonstrating that the image is being scaled by `1.0 / 255.0`, which is a common normalization technique converting pixel intensities from a range of [0, 255] to [0, 1]. This normalization step is indeed a critical part of image preprocessing in deep learning. The size you mentioned (224x224) is a common input size for many CNNs. 

However, please note that in the original question, the blob is being resized to a 256x256 square image, which is a model-specific input dimension. Each model has its own set of optimal input dimensions that are determined during the model's training phase, and these dimensions need to be matched correctly during the inference stage in the C++ code. Ensuring that the image size corresponds to the model's expected input size and applying correct normalization can help in achieving accurate predictions.

So, applying proper normalization and ensuring the correct input size in the C++ code could indeed solve the issue faced by @zys20170917, provided these steps align with the preprocessing steps employed in the Python version. 

Thank you for your input! Your suggestion could get us one step closer to solving this issue.

**Comment by andrewwetzel23** [comment]
Scaling the pixel intensities was the correct fix. Thanks @zys20170917!

**Comment by Sencc** [comment]
Hello! Is there any example of tensorrt implementation?
