### ISSUE TITLE
Closing dataloader mosaic albumentations: 

### ISSUE THREAD

**Issue by VYRION-Ai** [ultralytics/ultralytics#4019]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

i do training on 100 epochs when i got epoch 98 i got this and training stopped 
```
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))
```
what should i do , i need to continue training,But I stood here  

### Environment

```
Ultralytics YOLOv8.0.143  Python-3.8.7 torch-2.0.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3070 Laptop GPU, 8192MiB)
engine\trainer: task=detect, mode=train, model=runs\detect\train10\weights\last.pt, data=data.yaml, epochs=100, patience=100, batch=6, imgsz=640, save=True, save_period=-1, cache=True, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.0, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=runs\detect\train10
TensorBoard: Start with 'tensorboard --logdir runs\detect\train10', view at http://localhost:6006/
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@VYRION-Ai hello,

Thanks for reaching out about this issue and providing detailed information about your training environment and steps. The message "Closing dataloader mosaic" isn't an error – it's a normal message that you see when the mosaic augmentation ends after a set number of epochs (specified by 'close_mosaic') in the training process. In your case, 'close_mosaic' is set to 10, which means mosaic augmentations are applied for the first 10 epochs only.

The subsequent line you see is just a report on the remaining albumentations being applied. Albumentations are other types of image augmentations such as blurring, color variations etc., to enhance the dataset's diversity and improve the model's robustness.

If your training was indeed stopped at epoch 98, it's likely caused by some other issue. It would be helpful to look for any error message that may have come up in the console. A possible cause could be an out-of-memory error if your training uses up all of you GPU's memory, which could be handled by reducing your batch size.

If no error messages were presented, you might try resuming your training from the last saved checkpoint using the '--resume' argument, which should pick up training from where it left off. 

Please let us know if you have any more questions or need further clarification. Your collaboration is what makes the YOLOv8 and wider Ultralytics community great!

Best,
Glenn

**Comment by VYRION-Ai** [comment]
@glenn-jocher thank you , i resume training but it display this message , and doing no thing else, Ram of GPU and PC is good , what should i do to resume training and avoid this message

**Comment by glenn-jocher** [comment]
@VYRION-Ai see https://docs.ultralytics.com/modes/train/#resuming-interrupted-trainings

**Comment by VYRION-Ai** [comment]
@glenn-jocher how to change hyp parameter while **Resuming** and any other option like epochs and other like that ,

**Comment by glenn-jocher** [comment]
Hello @VYRION-Ai,

Thank you for your question. 

To modify hyperparameters (hyp) or any other training options (like epochs) when resuming a training, you would need a two-step process.

1. Start the resumption as usual, with the `--resume` command. This will load your last saved checkpoint, including its weights and hyperparameters.
2. Once the training has started and the log information of the loaded configuration appears in the console, interrupt the training (for instance, by pressing Ctrl+C). 

After completion of these steps, a new YAML file containing the hyperparameters of your resuming model should have been saved into your run directory (e.g., 'runs/train/exp'). 

Now you can edit this YAML file to change the hyperparameters or any other training configuration you wish to modify. Once the desired changes are made, you simply start retraining again pointing to this modified YAML file using the `--cfg` flag. This allows you to continue training from the last checkpoint but with your newly adjusted hyperparameters.

Remember to set the `epochs` argument to the total number of epochs you want your model to train for, as this value is absolute, not relative to the state of the resumed model.

I hope this answers your question. Please don't hesitate to reach out if you have additional questions.

Best,
Glenn

**Comment by VYRION-Ai** [comment]
@glenn-jocher thank you , i will try.

**Comment by glenn-jocher** [comment]
@VYRION-Ai You're welcome! I'm glad to hear that you found the information helpful. Please don't hesitate to reach out if you encounter any more issues or have further questions. Happy training with YOLOv8!

Best,
Glenn
