### ISSUE TITLE
NCNN inference doesn't use GPU

### ISSUE THREAD

**Issue by jeck00119** [ultralytics/ultralytics#4050]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi! I'm on a nvidia jetson nano and want to use a ncnn model for inference but it doesn't use GPU. How can I use the GPU for inference?Also I built the ncnn using setup.py(I added -DNCNN_VULKAN=ON to the cmake_args list from the setup.py and the vulakn is working).
After more digging I found that if I edit cuda = True in autobackend.py (`line 269 net.opt.use_vulkan_compute = cuda`) is using the gpu.

**Comment by glenn-jocher** [comment]
@jeck00119 have you tried setting `device=0` to use CUDA device 0?

**Comment by Klinefelters** [comment]
Hi, I wanted to ask if this fixed this problem? I'm thinking of pursuing this as well, and as such am interested if this is a good place to start.

**Comment by jeck00119** [comment]
> @jeck00119 have you tried setting `device=0` to use CUDA device 0?

Yes, I exported the .pt model to ncnn with device = 0

**Comment by glenn-jocher** [comment]
@Klinefelters hello, without more specifics on the issue you'd like to address, it's a bit hard to give a concrete answer. However, if you are referring to using the GPU for inference with the NCNN model, the initial solution proposed, which involves setting the `use_vulkan_compute` option to `True`, seems to have worked for some users.
Please keep in mind that outcomes may vary based on the specific hardware and software setup. Feel free to try it out and let us know your results in order to benefit the community. Remember, each problem encountered and its subsequent resolution contributes to the overall strength and understanding of our shared tools.

**Comment by SIXGODLI** [comment]
修改此处确实能用gpu了，amd核显的GPU也可以调用，但是有2个提示。
video 1/1 (frame 40/4102) D:\yolo\datasets\M_F.mp4: 640x640 1 hero, 1 continue, 449.0ms
FATAL ERROR! reclaim_blob_allocator get wild allocator 0000022A4ECE5C40
FATAL ERROR! reclaim_staging_allocator get wild allocator 0000022A4ECE5D30
video 1/1 (frame 41/4102) D:\yolo\datasets\M_F.mp4: 640x640 1 hero, 1 continue, 435.7ms

**Comment by glenn-jocher** [comment]
Thank you for your feedback. It appears that enabling GPU usage has introduced some errors. Please ensure you are using the latest version of the package. If the issue persists, consider reporting it on the NCNN GitHub repository for further assistance.
