### ISSUE TITLE
Tracking id not starting at 1

### ISSUE THREAD

**Issue by Myguely** [ultralytics/ultralytics#4051]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

When im making tracking on a custom dataset, the first id assigned is 3
![image](https://github.com/ultralytics/ultralytics/assets/58893390/c64af028-7e4d-4982-9641-0b5a538a9c71)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Myguely this is user error. The first column is class id, xywh box, and then track ID. Your screenshot shows no track IDs, so you are not tracking.

```
yolo track source=dance_short.mov save save_txt
```

<img width="1318" alt="Screenshot 2023-07-31 at 01 06 39" src="https://github.com/ultralytics/ultralytics/assets/26833433/74cb3f16-cf49-4c15-96d9-f31e79ee55a6">

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Myguely** [comment]
Ok I found my own issue :')  the first model.track was using the default source image and probably making 2 detections and not storing them. After I removed it it starts at 1

**Comment by Myguely** [comment]
I removed line 26 and the problem remains

**Comment by Myguely** [comment]
The tracking number 2 does not get a tracking id assigned

**Comment by glenn-jocher** [comment]
@Myguely hello, thank you for raising this issue. The assignment of tracking IDs by the tracker is not always sequential and does not necessarily start at 1. The tracker that we use in YOLOv8 may skip some IDs due to the internal workings of the algorithm. This is especially true in scenarios where objects enter and leave the frame, or where there are occlusions.

The tracker's main goal is to maintain a consistent ID for the same object across frames, which might explain the suspiciously missing tracking ID "2". That being said, unless you are experiencing issues where the same object is being assigned different IDs within the same sequence, this behavior should not affect the functionality of the tracker.

If you believe that the missing ID "2" is causing an error in your tracking, and with the information that you have provided, it would be most helpful if you could provide more details or examples of the issue -- this will allow us to help you more effectively.
