### ISSUE TITLE
CUDA out of memory during inference

### ISSUE THREAD

**Issue by fgraffitti-cyberhawk** [ultralytics/ultralytics#4057]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

Hi, I've seen other people having the same problem but the solutions didn't work for me (e.g. this: https://github.com/ultralytics/ultralytics/issues/3983).

When I run the inference of a `yolov8l-seg.pt` model on a batch of images, I fill about 70% of the CUDA memory.
If I then try to run again the inference on the same batch, I get a CUDA OOM error, even if I am overwriting the results on the same python variable. 

I tried to move the result outputs to cpu using:
`outputs = [result.cpu() for result in results]`
and also to empty the cuda cache with
`torch.cuda.empty_cache()`
but I still get the same error

EDIT: I've done some more testing, here what I found:

if I run the following code multiple times in a fresh ipython kernel:
`results = model(list_of_images[:10],conf=0.)`
after the first run I fill 8G/22.5G of Cuda memory, after the second time 12.5G/22.5G, then I can run it again as many times as I want without any problem, and the total cuda usage is stable at 12.5G.

If instead of 10 images I run on 20 images, 
`results = model(list_of_images[:20],conf=0.)`
I get the following cuda usage:
1st run: 12.6G/22.5G
2nd run: 21.8/22.5G
following runs: 21.8/22.5G

If I run on 30 images:
1st run: 17G/22.5G
2nd run: Cuda  OOM error

not sure what's going on here...

### Environment

- Ubuntu 20.04
- ultralytics  8.0.143
- python 3.10.11

### Minimal Reproducible Example

model = YOLO('path/to/best.pt')
results = model(list_of_images) # runs correctly
results = model(list_of_images) # CUDA OOM error

#### same error occurs with this:
model = YOLO('path/to/best.pt')
results = model(list_of_images,stream=True) # runs correctly
outputs = [result.cpu() for result in results] # runs correctly
results = model(list_of_images,stream=True) # runs correctly
outputs = [result.cpu() for result in results] # CUDA OOM error

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@fgraffitti-cyberhawk hello, 

Thank you for the detailed problem description and your efforts in resolving the CUDA OOM error. The CUDA memory usage you're observing might be due to the way your Python environment is handling memory allocation. 

When you run the model to infer on a batch of images, the created tensors are stored in GPU memory. Even if you overwrite your Python variable 'results' on the second run, it doesn't guarantee that the previously allocated GPU memory gets released immediately. Garbage collection in Python is not always instantaneous, and there can be a delay which may explain why you are seeing a gradual increase in memory usage.

Also, please note that calling `torch.cuda.empty_cache()` only releases cache memory and won't reduce the used memory that's actually occupied by tensor variables, such as those created during your inference runs.

For your case, I would recommend two things you might want to try:

1. Limiting the batch size: If you process fewer images at a time, it might help avoid the CUDA OOM error.

2. Building in cool-down periods: Let the Python garbage collector do its job, or even better, forcefully trigger it using `gc.collect()` after each inference and moving results to CPU.

I hope these suggestions might bring you a step closer to solving your problem. Please do not hesitate to get back to us if you're still encountering issues. We're here to help.

Best regards,
Glenn

**Comment by fgraffitti-cyberhawk** [comment]
Hey @glenn-jocher , thanks for your reply.
I didn't add all the tests I did, but those included explicitly deleting the `results` object and then calling `gc.collect()` and `torch.cuda.empty_cache()`.
However, this doesn't free the CUDA memory, and I don't think a cool-down period is the way to go as the CUDA memory stays in use pretty much forever (or at least until I kill the ipython session).
It's not a major blocker for me, as I can decrease the batch size to deal with this problem, but it would be useful to be able to run a garbage collector on the torch CUDA stuff to free up the unused memory.

**Comment by samhoff20** [comment]
I'm having the same issue, but I'm to the point where I can't even run an batch of 1! For context I'm on a 4080, ubuntu 22.04.

`task = Task.init(project_name="my project", task_name="my task")

# Load a model
model = YOLO("/home/sam/Projects/yolov8/cfg/training")  # build a new model from scratch
model = YOLO("yolov8m.pt")  # load a pretrained model (recommended for training)

# Use the model
model.train(data="/home/sam/Projects/yolov8/data/dunhill.yaml", epochs=100, batch=1)  # train the model
metrics = model.val()  # evaluate model performance on the validation set
results = model("/home/sam/Projects/vintage_insight/experiments/data/cartier_dataset_2/images/test/08e34ce9-Cartier_Lighter_Pentagon_White_Lacquer_Works_Mint_Condition_1_Year_Wa_4vjxJ6T.jpeg")  # predict on an image
path = model.export(format="onnx")  # export the model to ONNX format
task.close()`

`OutOfMemoryError                          Traceback (most recent call last)
Cell In[7], line 8
      5 model = YOLO("yolov8m.pt")  # load a pretrained model (recommended for training)
      7 # Use the model
----> 8 model.train(data="[/home/sam/Projects/yolov8/data/dunhill.yaml](https://file+.vscode-resource.vscode-cdn.net/home/sam/Projects/yolov8/data/dunhill.yaml)", epochs=100, batch=1)  # train the model
      9 metrics = model.val()  # evaluate model performance on the validation set
     10 results = model("[/home/sam/Projects/vintage_insight/experiments/data/cartier_dataset_2/images/test/08e34ce9-Cartier_Lighter_Pentagon_White_Lacquer_Works_Mint_Condition_1_Year_Wa_4vjxJ6T.jpeg](https://file+.vscode-resource.vscode-cdn.net/home/sam/Projects/vintage_insight/experiments/data/cartier_dataset_2/images/test/08e34ce9-Cartier_Lighter_Pentagon_White_Lacquer_Works_Mint_Condition_1_Year_Wa_4vjxJ6T.jpeg)")  # predict on an image

File [~/anaconda3/envs/yolov8/lib/python3.11/site-packages/ultralytics/engine/model.py:377](https://file+.vscode-resource.vscode-cdn.net/home/sam/Projects/yolov8/~/anaconda3/envs/yolov8/lib/python3.11/site-packages/ultralytics/engine/model.py:377), in Model.train(self, trainer, **kwargs)
    375     self.model = self.trainer.model
    376 self.trainer.hub_session = self.session  # attach optional HUB session
--> 377 self.trainer.train()
    378 # Update model and cfg after training
    379 if RANK in (-1, 0):

File [~/anaconda3/envs/yolov8/lib/python3.11/site-packages/ultralytics/engine/trainer.py:192](https://file+.vscode-resource.vscode-cdn.net/home/sam/Projects/yolov8/~/anaconda3/envs/yolov8/lib/python3.11/site-packages/ultralytics/engine/trainer.py:192), in BaseTrainer.train(self)
    190         ddp_cleanup(self, str(file))
    191 else:
--> 192     self._do_train(world_size)

File [~/anaconda3/envs/yolov8/lib/python3.11/site-packages/ultralytics/engine/trainer.py:276](https://file+.vscode-resource.vscode-cdn.net/home/sam/Projects/yolov8/~/anaconda3/envs/yolov8/lib/python3.11/site-packages/ultralytics/engine/trainer.py:276), in BaseTrainer._do_train(self, world_size)
    273 if world_size > 1:
    274     self._setup_ddp(world_size)
--> 276 self._setup_train(world_size)
...
   1141     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None,
   1142                 non_blocking, memory_format=convert_to_format)
-> 1143 return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)

OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 15.70 GiB total capacity; 421.04 MiB already allocated; 19.31 MiB free; 436.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by glenn-jocher** [comment]
@samhoff20 your error indicates that you're running out of memory on your GPU, even with a batch size of 1. The NVIDIA GeForce RTX 4080 is a hypothetical GPU (as of my last training in September 2021), but assuming it has substantial memory based on the error message (15.70 GiB), the out-of-memory error you're encountering might be due to other factors.

Here are some steps you can take to troubleshoot and potentially resolve the issue:

1. **Check Running Processes**:
   - Before starting the training, ensure no other heavy GPU processes are running. Use the `nvidia-smi` command to see GPU memory utilization and kill any unwanted processes.

2. **Reduce Model Size**:
   - If you are training a large version of YOLO, consider switching to a smaller version, which requires less memory. This will allow you to understand if the model size is indeed the issue. 

3. **Memory Management**:
   - The error suggests adjusting `max_split_size_mb`. This is an environment variable that can be used to influence PyTorch's CUDA memory allocator. You can try setting it to a lower value before starting your script:
     ```bash
     export PYTORCH_CUDA_ALLOC_CONF="max_split_size_mb=10"
     ```
     Then run your training script.

4. **PyTorch Version**:
   - There might be CUDA memory optimizations and fixes in newer versions of PyTorch. Ensure you're using a recent version of PyTorch. Update if necessary.

5. **Clear CUDA Cache**:
   - You can manually clear the CUDA cache using the following commands in your script before starting your training:
     ```python
     import torch
     torch.cuda.empty_cache()
     ```

6. **Gradient Accumulation**:
   - If reducing the batch size isn't helping, consider using gradient accumulation. This allows you to virtually increase the batch size without increasing GPU memory usage.

7. **Model Initialization**:
   - In your code, you initialize the `YOLO` model twice consecutively. It seems like the first initialization (`model = YOLO("/home/sam/Projects/yolov8/cfg/training")`) is unnecessary if you're going to overwrite it with the pretrained model in the next line. Consider removing the first initialization to save resources.

8. **OS and Driver Updates**:
   - Ensure your Ubuntu OS and NVIDIA drivers are up-to-date. Sometimes, updates bring about improvements and fixes for better GPU memory handling.

9. **Hardware Issue**:
   - There could be an unlikely scenario where there's an issue with the GPU itself. Ensure your GPU is functioning correctly, and consider testing on another machine if possible.

By systematically going through these steps, you should be able to identify the root cause of the issue and hopefully find a solution.

**Comment by itachi1232gg** [comment]
Reducing the model size does not reduce the GPU memory usage, I trained  yolov8-seg(n\s\m\x) models on my own dataset, n/s/m/x model used almost same GPU memory, and at some epoch raises OOM error.  My image is large (2048*2048), but I can not resize them into smaller size due to some reason. I trained on 4 * A100 GPUs (80G) with batch_size=4,  using around 78GB gpu memory if not raise OOM.

**Comment by francescopisu** [comment]
> @samhoff20 your error indicates that you're running out of memory on your GPU, even with a batch size of 1. The NVIDIA GeForce RTX 4080 is a hypothetical GPU (as of my last training in September 2021), but assuming it has substantial memory based on the error message (15.70 GiB), the out-of-memory error you're encountering might be due to other factors.
> 
> Here are some steps you can take to troubleshoot and potentially resolve the issue:
> 
> 1. **Check Running Processes**:
>    
>    * Before starting the training, ensure no other heavy GPU processes are running. Use the `nvidia-smi` command to see GPU memory utilization and kill any unwanted processes.
> 2. **Reduce Model Size**:
>    
>    * If you are training a large version of YOLO, consider switching to a smaller version, which requires less memory. This will allow you to understand if the model size is indeed the issue.
> 3. **Memory Management**:
>    
>    * The error suggests adjusting `max_split_size_mb`. This is an environment variable that can be used to influence PyTorch's CUDA memory allocator. You can try setting it to a lower value before starting your script:
>      ```shell
>      export PYTORCH_CUDA_ALLOC_CONF="max_split_size_mb=10"
>      ```
>      
>      
>          
>            
>          
>      
>            
>          
>      
>          
>        
>      Then run your training script.
> 4. **PyTorch Version**:
>    
>    * There might be CUDA memory optimizations and fixes in newer versions of PyTorch. Ensure you're using a recent version of PyTorch. Update if necessary.
> 5. **Clear CUDA Cache**:
>    
>    * You can manually clear the CUDA cache using the following commands in your script before starting your training:
>      ```python
>      import torch
>      torch.cuda.empty_cache()
>      ```
> 6. **Gradient Accumulation**:
>    
>    * If reducing the batch size isn't helping, consider using gradient accumulation. This allows you to virtually increase the batch size without increasing GPU memory usage.
> 7. **Model Initialization**:
>    
>    * In your code, you initialize the `YOLO` model twice consecutively. It seems like the first initialization (`model = YOLO("/home/sam/Projects/yolov8/cfg/training")`) is unnecessary if you're going to overwrite it with the pretrained model in the next line. Consider removing the first initialization to save resources.
> 8. **OS and Driver Updates**:
>    
>    * Ensure your Ubuntu OS and NVIDIA drivers are up-to-date. Sometimes, updates bring about improvements and fixes for better GPU memory handling.
> 9. **Hardware Issue**:
>    
>    * There could be an unlikely scenario where there's an issue with the GPU itself. Ensure your GPU is functioning correctly, and consider testing on another machine if possible.
> 
> By systematically going through these steps, you should be able to identify the root cause of the issue and hopefully find a solution.

Great copy&paste from ChatGPU. Absolute boss

**Comment by glenn-jocher** [comment]
@francescopisu thank you for your comment! I’m glad that the information provided was comprehensive. We aim to provide as much detail as possible to help you troubleshoot effectively. I understand that handling GPU memory can be challenging, especially when working with large models like YOLO. To strengthen your setup, there might be a need to dive deeper into memory management at both software (PyTorch, CUDA) and hardware levels (GPU). Should you need further assistance, feel free to post more details of the problem you’re encountering. Happy computing!

**Comment by cchalou98** [comment]
> @samhoff20 your error indicates that you're running out of memory on your GPU, even with a batch size of 1. The NVIDIA GeForce RTX 4080 is a hypothetical GPU (as of my last training in September 2021), but assuming it has substantial memory based on the error message (15.70 GiB), the out-of-memory error you're encountering might be due to other factors.
> 
> Here are some steps you can take to troubleshoot and potentially resolve the issue:
> 
> 1. **Check Running Processes**:
>    
>    * Before starting the training, ensure no other heavy GPU processes are running. Use the `nvidia-smi` command to see GPU memory utilization and kill any unwanted processes.
> 2. **Reduce Model Size**:
>    
>    * If you are training a large version of YOLO, consider switching to a smaller version, which requires less memory. This will allow you to understand if the model size is indeed the issue.
> 3. **Memory Management**:
>    
>    * The error suggests adjusting `max_split_size_mb`. This is an environment variable that can be used to influence PyTorch's CUDA memory allocator. You can try setting it to a lower value before starting your script:
>      ```shell
>      export PYTORCH_CUDA_ALLOC_CONF="max_split_size_mb=10"
>      ```
>      
>      
>          
>            
>          
>      
>            
>          
>      
>          
>        
>      Then run your training script.
> 4. **PyTorch Version**:
>    
>    * There might be CUDA memory optimizations and fixes in newer versions of PyTorch. Ensure you're using a recent version of PyTorch. Update if necessary.
> 5. **Clear CUDA Cache**:
>    
>    * You can manually clear the CUDA cache using the following commands in your script before starting your training:
>      ```python
>      import torch
>      torch.cuda.empty_cache()
>      ```
> 6. **Gradient Accumulation**:
>    
>    * If reducing the batch size isn't helping, consider using gradient accumulation. This allows you to virtually increase the batch size without increasing GPU memory usage.
> 7. **Model Initialization**:
>    
>    * In your code, you initialize the `YOLO` model twice consecutively. It seems like the first initialization (`model = YOLO("/home/sam/Projects/yolov8/cfg/training")`) is unnecessary if you're going to overwrite it with the pretrained model in the next line. Consider removing the first initialization to save resources.
> 8. **OS and Driver Updates**:
>    
>    * Ensure your Ubuntu OS and NVIDIA drivers are up-to-date. Sometimes, updates bring about improvements and fixes for better GPU memory handling.
> 9. **Hardware Issue**:
>    
>    * There could be an unlikely scenario where there's an issue with the GPU itself. Ensure your GPU is functioning correctly, and consider testing on another machine if possible.
> 
> By systematically going through these steps, you should be able to identify the root cause of the issue and hopefully find a solution.

Hello, I am having this issue in my vitis-ai environment while performing quantization: 
**VAIQ_ERROR][QUANTIZER_TORCH_PYTORCH_TRACE]: Failed to get graph from model and input args. The PyTorch internal failed reason is:
CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 7.75 GiB total capacity; 6.11 GiB already allocated; 66.94 MiB free; 6.17 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF**

Please how can I solve it?

**Comment by lizeyu090312** [comment]
I had the same issue where memory usage would just keep on increasing as more batches came through. I found that wrapping `with torch.no_grad():` around the inference code decreased the memory usage.

**Comment by glenn-jocher** [comment]
Hi @lizeyu090312,

Thank you for sharing your experience! Wrapping your inference code with `torch.no_grad()` is indeed a great practice to reduce memory usage, as it disables gradient calculation, which is not needed during inference.

For others facing similar issues, here's a quick example of how to implement this:

```python
import torch
from ultralytics import YOLO

# Load your model
model = YOLO("yolov8m.pt")

# Example inference with torch.no_grad()
with torch.no_grad():
    results = model("/path/to/your/image.jpg")
```

Additionally, if you continue to experience memory issues, please ensure you are using the latest versions of PyTorch and Ultralytics. If the problem persists, providing a minimal reproducible example can greatly help in diagnosing the issue. You can find guidance on creating one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any more questions or need further assistance! 😊

**Comment by Petros626** [comment]
for me the following things seem to work:
1. reduce the batch size
2. call `torch.cuda.empty_cache()` before training job, some frameworks do this automatically.
3. `os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"`

**Comment by glenn-jocher** [comment]
@Petros626 thank you for sharing your findings! These are excellent suggestions. Additionally, you might find using `torch.no_grad()` during inference and leveraging Ultralytics' [autobatch](https://docs.ultralytics.com/reference/utils/autobatch/) functionality helpful for optimizing memory usage further.

**Comment by StepanVL** [comment]
> Reducing the model size does not reduce the GPU memory usage, I trained yolov8-seg(n\s\m\x) models on my own dataset, n/s/m/x model used almost same GPU memory, and at some epoch raises OOM error. My image is large (2048*2048), but I can not resize them into smaller size due to some reason. I trained on 4 * A100 GPUs (80G) with batch_size=4, using around 78GB gpu memory if not raise OOM.

I've trained the same dataset with default size images (640x640), two classes and bach: 1 or batch: 16 on 6 Gb and 16 Gb NVIDIA cards. Training consumed almost all the memory with ocasional "WARNING: CUDA OutOfMemoryError in TaskAlignedAssigner, using CPU". Some trainings crashed with OMM. Seems like this is not a bug, but a feature by design.

**Comment by glenn-jocher** [comment]
Thank you for sharing your observations. YOLO models are designed to utilize GPU memory efficiently, but high-resolution images (2048x2048) significantly increase memory requirements, especially with large batch sizes. To mitigate OOM errors, consider enabling gradient accumulation to simulate larger batch sizes or leveraging automatic batch size adjustment with `batch=-1` as described in [autobatch](https://docs.ultralytics.com/reference/utils/autobatch/). If these approaches don’t resolve your issue, further reducing the memory load by optimizing model architecture or augmentations may help.
