### ISSUE TITLE
Torchscript Inference On Cuda

### ISSUE THREAD

**Issue by NatePolizogo** [ultralytics/ultralytics#4065]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export, Other

### Bug

I am exporting a yolov8 POSE model using the following code.
`
from ultralytics import YOLO
model = YOLO(model_path)
model.fuse()
model.info(verbose=True)

if export:
  model.export(format='torchscript', imgsz=640)
  return
`

the I try to do inference on the GPU by using the following code:

`
device = torch.device('cuda:0')
model = torch.jit.load(weights)
model.to(device)
x = torch.zeros((1,3,640,640)).to(device)
model(x)
`

And I get the following error:

*** RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/ultralytics/nn/tasks.py", line 74, in forward
    _35 = (_18).forward(act, _34, )
    _36 = (_20).forward((_19).forward(act, _35, ), _29, )
    _37 = (_22).forward(_33, _35, (_21).forward(act, _36, ), )
           ~~~~~~~~~~~~ <--- HERE
    return _37
  File "code/__torch__/ultralytics/nn/modules/head.py", line 63, in forward
    anchor_points = torch.unsqueeze(CONSTANTS.c0, 0)
    lt, rb, = torch.chunk(_26, 2, 1)
    x1y1 = torch.sub(anchor_points, lt)
           ~~~~~~~~~ <--- HERE
    x2y2 = torch.add(anchor_points, rb)
    c_xy = torch.div(torch.add(x1y1, x2y2), CONSTANTS.c1)

Traceback of TorchScript, original code (most recent call last):
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/ultralytics/utils/tal.py(264): dist2bbox
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/ultralytics/nn/modules/head.py(60): forward
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/ultralytics/nn/modules/head.py(127): forward
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/nn/modules/module.py(1488): _slow_forward
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/nn/modules/module.py(1501): _call_impl
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/ultralytics/nn/tasks.py(82): _predict_once
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/ultralytics/nn/tasks.py(62): predict
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/ultralytics/nn/tasks.py(45): forward
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/nn/modules/module.py(1488): _slow_forward
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/nn/modules/module.py(1501): _call_impl
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/jit/_trace.py(1056): trace_module
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/jit/_trace.py(794): trace
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/ultralytics/engine/exporter.py(289): export_torchscript
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/ultralytics/engine/exporter.py(114): outer_func
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/ultralytics/engine/exporter.py(239): __call__
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/utils/_contextlib.py(115): decorate_context
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/ultralytics/engine/model.py(343): export
/home/perceptron/Polizogo/mine_ultralitics/pose_infer.py(22): default
/home/perceptron/Polizogo/mine_ultralitics/pose_infer.py(103): <module>
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
(Pdb) x = torch.zeros((1,3,640,640)).to(self.device)
(Pdb) self.model(x)
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/nn/modules/module.py:1501: UserWarning: operator() sees varying value in profiling, ignoring and this should be handled by GUARD logic (Triggered internally at ../third_party/nvfuser/csrc/parser.cpp:3777.)
  return forward_call(*args, **kwargs)
*** RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/ultralytics/nn/tasks.py", line 74, in forward
    _35 = (_18).forward(act, _34, )
    _36 = (_20).forward((_19).forward(act, _35, ), _29, )
    _37 = (_22).forward(_33, _35, (_21).forward(act, _36, ), )
           ~~~~~~~~~~~~ <--- HERE
    return _37
  File "code/__torch__/ultralytics/nn/modules/head.py", line 63, in forward
    anchor_points = torch.unsqueeze(CONSTANTS.c0, 0)
    lt, rb, = torch.chunk(_26, 2, 1)
    x1y1 = torch.sub(anchor_points, lt)
           ~~~~~~~~~ <--- HERE
    x2y2 = torch.add(anchor_points, rb)
    c_xy = torch.div(torch.add(x1y1, x2y2), CONSTANTS.c1)

Traceback of TorchScript, original code (most recent call last):
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/ultralytics/utils/tal.py(264): dist2bbox
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/ultralytics/nn/modules/head.py(60): forward
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/ultralytics/nn/modules/head.py(127): forward
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/nn/modules/module.py(1488): _slow_forward
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/nn/modules/module.py(1501): _call_impl
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/ultralytics/nn/tasks.py(82): _predict_once
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/ultralytics/nn/tasks.py(62): predict
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/ultralytics/nn/tasks.py(45): forward
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/nn/modules/module.py(1488): _slow_forward
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/nn/modules/module.py(1501): _call_impl
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/jit/_trace.py(1056): trace_module
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/jit/_trace.py(794): trace
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/ultralytics/engine/exporter.py(289): export_torchscript
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/ultralytics/engine/exporter.py(114): outer_func
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/ultralytics/engine/exporter.py(239): __call__
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/utils/_contextlib.py(115): decorate_context
/home/perceptron/anaconda3/envs/yolo/lib/python3.11/site-packages/ultralytics/engine/model.py(343): export
/home/perceptron/Polizogo/mine_ultralitics/pose_infer.py(22): default
/home/perceptron/Polizogo/mine_ultralitics/pose_infer.py(103): <module>
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

When I am using cpu as device it works as expected.

### Environment

- YOLO: Ultralytics YOLOv8.0.143 🚀 Python-3.11.3 torch-2.0.1+cu117 CPU (AMD Ryzen 9 5950X 16-Core Processor)
- OS: Ubuntu 22.04
- Python: python 3.11.3

### Minimal Reproducible Example

from ultralytics import YOLO
model = YOLO(model_path)
model.fuse()
model.info(verbose=True)
model.export(format='torchscript', imgsz=640)

device = torch.device('cuda:0')
model = torch.jit.load(weights.torchscript)
model.to(device)
x = torch.zeros((1,3,640,640)).to(device)
model(x)

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@NatePolizogo hi there,

Thank you for opening this issue and providing such a detailed report. It seems like the problem you're encountering is due to mismatch of tensor devices in torch.

The error message `RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!` suggests that some variables are on the CPU while others are on the GPU, causing a device mismatch. 

When running the model on a GPU, every component of the model and the input data should be on the same device (in this case, the GPU). Therefore, it's necessary to ensure every used variable or tensor in torch operations should be moved to GPU first.

As a debugging measure, you could verify during runtime that both the model and all tensors are assigned to the right device ('cuda:0'). You can do this by printing `model.device` and the device of tensors being processed (`tensor.device`).

Please make sure also to track the location of CONSTANTS.c0 which is used to generate anchor_points. Is it possible that this constant is still residing on the CPU while the rest of your operation is attempting to run on the GPU?

I hope this helps! Please feel free to keep this thread updated with your progress.

**Comment by NatePolizogo** [comment]
Yes, I understand what this error means and I already tried  to do this check. For the input tensor I can confirm it is located on GPU but for the model, I get the following error when I try to figure out if it is assigned on the same device.

by running : model.device 
i get: *** AttributeError: 'RecursiveScriptModule' object has no attribute 'device'

**Comment by glenn-jocher** [comment]
@NatePolizogo it's great to see you're actively debugging the issue. From what you've mentioned, the parameters of your model are correctly placed on the 'cuda:0' device, and the same goes for your input tensor.

The error regarding the 'device' attribute in RecursiveScriptModule happens because, unlike nn.Module, a torch.jit.ScriptModule (or its recursive counterpart) doesn't have a 'device' attribute. It's internally treated in a different way than a standard PyTorch model, particularly when it comes to attributes and method calls, and that's why you're getting this AttributeError.

That said, your check with 'model.parameters()' is a valid way of confirming that your model's parameters are all on the GPU, and since they are indeed showing 'cuda:0', we can infer that your model is correctly based on the GPU.

Please ensure that all tensors involved in your computations, even temporary ones, are on the correct device. Be attentive to tensors that are created on-the-fly during the forward pass of a module or in a utility function. These tensors are easy to overlook but they need to be on the GPU as well. 

You might also want to make sure that the labels and any target data or variables associated with loss computation are being properly moved to the GPU device.

Keep persevering and stay patient as you debug. It can be a complex process, but every step brings you closer to the solution. You're making good progress!

**Comment by NatePolizogo** [comment]
@glenn-jocher 
OK so, the target hear is only to make predictions using the model, a simple inference as the example demonstrates.
In the past I had done the same for a detection model (previous ultralytics version) and It worked seamlessly.
This issue really surprises me and I don't know how to debug it further as all the attributes seems to be on the same device.
That' s why I opened this issues, to get some help.
Keep in mind this one is a pose model, if that helps anywhere, and the latest version of ultralights.

**Comment by glenn-jocher** [comment]
@NatePolizogo

Thank you for providing more details. It's understandable how this issue can be perplexing, especially if you previously managed to run a detection model without running into this problem. Let's see if we can figure it out together.

The issue you're encountering is definitely related to the device placement of tensors involved in the computation. Even though you've checked that your model parameters and input data are on 'cuda:0', the error message suggests there might still be some tensors being processed on the CPU instead of the GPU.

When running inference, there might be additional helper functions or parts of the model used which could create or use tensors. This could involve the transformation of data in the process of feeding it to the model, or operations performed in post-processing the model's outputs for presenting the predictions.

As the problem is a device mismatch, we would need to identify the part of your code where this happens. You mentioned that the model is for pose estimation. Check if any of the additional steps or components specific to pose estimation (e.g., additional transformations, calculations, auxiliary data) involve tensors which may not have been moved to the GPU.

Even though it is tedious, tracing your pipeline step-by-step is key here. Verify which operations are involved in your prediction process and evaluate if any of them involve tensors that are mistakenly left on the CPU. Also consider any constants or auxiliary data used during inference, as these are common culprits for such issues.

Keep up your perseverance - you are making good progress!

**Comment by ggggg111** [comment]
@NatePolizogo Hello, I have encountered the same problem as you. As a workaround, if I want to use a CUDA device, I load the model as follows:

**Comment by ggggg111** [comment]
@NatePolizogo Hello, I have encountered the same problem as you. As a workaround, if I want to use a CUDA device, I load the model as follows:

**Comment by glenn-jocher** [comment]
Hello @ggggg111,

Thanks for sharing your solution with us. From what I understand, it seems you load the model directly onto a CUDA device. This approach ensures that all components of the model and parameters load in the same device memory, mitigating any potential issues with device mismatch which can happen if you load the model into CPU and then try to shift it into GPU memory.

Remember that TorchScript models behave a bit differently from regular PyTorch models. Thus, it's crucial to ensure all involved tensors, including those that are part of the model, are on the same device, especially when using CUDA.

Once again, thank you for sharing this workaround. It will be beneficial to others in our community who might encounter similar obstacles. 

Happy coding!

**Comment by ggggg111** [comment]
Thank you for your detailed response @glenn-jocher!

**Comment by glenn-jocher** [comment]
@ggggg111 you're welcome! I'm glad to hear that my response was helpful for you. If you have any more questions or face any other issues as you continue working with YOLOv8, feel free to ask. I'm here to help you. Don't hesitate to reach out with any further clarifications or concerns. Happy coding!
