### ISSUE TITLE
ERROR shape mismatch

### ISSUE THREAD

**Issue by caiodataopshouse** [ultralytics/ultralytics#4067]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I'm trying to fine tune yolov8n using .train(). As arguments I give epochs=1, device="mps". The training goes well for a while, but at epoch 189/514 I get the following error:

`RuntimeError: shape mismatch: value tensor of shape [43387] cannot be broadcast to indexing result of shape [64492]`

<img width="890" alt="Screenshot 2023-07-31 at 17 51 08" src="https://github.com/ultralytics/yolov5/assets/124146045/60b38a68-3103-432e-b470-e035992b0af6">
<img width="881" alt="Screenshot 2023-07-31 at 17 51 37" src="https://github.com/ultralytics/yolov5/assets/124146045/ecc207cf-beff-49f1-b8b8-3fd10a10f617">

I find strange that the error occurs on a late stage... I saw a issue from 2020 reporting a bug when during inference the model don't detect any box... I wonder if it can be related.

### Environment

-YOLO: yolov8n
- MACPRO Apple M1 Pro
- Python: Python 3.9.11

### Minimal Reproducible Example

from ultralytics import YOLO
model = YOLO('yolov8n.pt') 
model.train(data='/Users/caio/Desktop/YOLO-NAS/data.yaml', epochs=1, device="mps")

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@caiodataopshouse hello, thank you for reaching out and providing a detailed description of the issue you're experiencing. 

This error typically indicates a mismatch between the shape of the tensor you are attempting to use in some operation and the expected shape for that operation. In this case, it appears like some form of reshaping or broadcasting is happening that expects a tensor of shape [64492], but is getting a tensor of shape [43387] instead.

As this error occurs at a later stage of your training, it might be caused by a specific data in your training set that is not well formatted or is causing unexpected behaviors in the model. Do ensure that your dataset is formatted consistently and correctly according to the YOLOv8 specifications.

Please do check the data preprocessing steps and make sure that all expected tensors within your dataset are of the correct shape, or if there's a sample in your dataset that may have been corrupted, mislabeled or incorrectly processed. 

Finally, it could be helpful to use a process of elimination to identify the batch causing the problem. This would involve running the model on different subsets of the data to pinpoint where the issue lies.

Should the problem persist, please provide more details about your training process and data processing steps so that we can assist you better. Your support in rectifying this improves the robustness of Ultralytics YOLOv8 for everyone. We appreciate your understanding and cooperation!

**Comment by Rusteam** [comment]
@caiodataopshouse 
This happened to me at epoch 3 with `imgsz=512`. When I changed to `imgsz=640` it didn't happen again.

**Comment by glenn-jocher** [comment]
Hello @Rusteam, 

It's interesting to see that the issue didn't occur when the image size was increased to 640. This might indicate that your model could be running into issues when trying to process smaller images. Which data preprocessing steps you are using could potentially impact this. 

It is always important to ensure the image size being used is appropriate for the details in your images you are trying to detect. An image size that is too small might be removing or distorting these details, leading to issues. 

Try to stick with larger image sizes if possible and ensure that all your images are consistently resized. Also, confirm that your labels match up with the new image sizes during training. 

As you are working specifically on an MPS device using the yolov8s model, make sure you're correctly leveraging the MPS capabilities for your training. 

Keep us posted on your progress, we're here to help!

**Comment by Rusteam** [comment]
actually it crashed after epoch 10 with the same error. And yes I can see that my images vary in size significantly with high aspect ratio and many of them have a smaller side of 200-300.

**Comment by glenn-jocher** [comment]
@Rusteam hello! 

When working with images of different sizes and aspect ratios, it's crucial to choose a preprocessing method that handles these variations while still maintaining important image details for model training. 

If many of your images have a smaller side of around 200-300, and you're resizing all images to a larger size (like 640), this could potentially introduce distortions or cause important details to be lost especially for smaller objects, which could result in issues during training.

There are a few strategies you could consider here:

1. **Resizing Strategies**: Instead of resizing all images to a square size, you might want to consider maintaining the original aspect ratio. One approach could be to resize the smaller dimension of each image to 640, and adjust the larger dimension proportionally. This would preserve the aspect ratio, but the trade-off is you may need to handle images of different sizes during training.

2. **Padding**: Another approach would be to resize the larger dimension to your desired size, and then pad the smaller dimension. This would give you uniform image sizes while preserving aspect ratio, at the expense of introducing extra 'empty' space in your images.

3. **Data Augmentation**: Techniques such as random cropping and scaling could help the model better generalize objects at various scales and aspect ratios.

Remember that optimal image preprocessing can often be problem-specific, so some trial and error or experimentation might be necessary to find the best approach for your particular dataset. 

Do let us know if the issue persists or if you have any further questions, we're here to help!

**Comment by Rusteam** [comment]
@glenn-jocher thanks a lot for such a detailed response. I'll try splitting my images by half and train with smaller size.

**Comment by glenn-jocher** [comment]
@Rusteam, you're welcome! Splitting your images and training with a smaller size could indeed help, especially if you have high-res images or your model is struggling with memory limitations. This way, the patterns or features within the pictures might become more discernible for the model.

Remember that if you go this route, your labels would also need to adjust to match these new smaller images. Be sure to take this into consideration when you divide your images.

Try to monitor your training closely to see how it reacts to the change in image size. If your model's performance improves, then you know you're on the right track. Otherwise, further tweaks and experimentation might be necessary.

Good luck with the modifications, and don't hesitate to ask if you have any more questions or encounter any issues—we're here to help!

**Comment by Rusteam** [comment]
Indeed, after properly preprocessing data my metric has jumped up significantly.

My training data resolution varies significantly from ~200 to 2k pixels and aspect ratio from 1 to 5. After I have cropped it into equal patches with max size of 320 and trained on smaller inputs, `mAP0.5` has increased from **0.66** to **0.86**.

**Comment by glenn-jocher** [comment]
@Rusteam hello, 

That's great news! Preprocessing the data appropriately can have a substantial impact on the model's performance as it ensures the model has consistent and well-structured data to learn from. 

Cropping your images into equal patches and training on smaller inputs would help the model focus better on the relevant features in your images. Your strategy of handling significant resolution and aspect ratio variations in your data seems to have worked phenomenally well, seeing as your `mAP0.5` has increased from 0.66 to 0.86, which is a great improvement.

Thank you for sharing your experience. It might be useful for others facing similar challenges. Keep up the good work, and don't hesitate to ask if you have any more questions or encounter any issues. We're here to help!

**Comment by hvaara** [comment]
This is a live bug, and I suspect MPS is the culprit here. Possibly an indexing issue. Seeing the same error, and can't reproduce on CPU. I can semi-consistently reproduce on MPS. I'll link to this issue from upstream if I figure it out.

**Comment by hvaara** [comment]
I identified the error in MPS and opened https://github.com/pytorch/pytorch/issues/178079.

**Comment by glenn-jocher** [comment]
Thanks for isolating this, it does look like an upstream MPS issue rather than an Ultralytics bug; please continue tracking it in the [PyTorch issue you opened](https://github.com/pytorch/pytorch/issues/178079), and if anyone can still reproduce it with current `torch` and `ultralytics`, please open a new issue here with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum-reproducible-example/), the full traceback, and `yolo checks` output for visibility.

**Comment by hvaara** [comment]
Correct, it's an MPS issue in PyTorch, and it's still reproducible. Ultimately this needs to be fixed in PyTorch, but there are a couple of things you could consider on your side

- Workaround for those who can't or won't update their PyTorch version
- Warn affected users to increase visibility and nag for update

I'll try to remember to open an issue for it - please nudge me if I forget.

**Comment by glenn-jocher** [comment]
Thanks, that’s helpful; since this is a closed stale thread, please open a new issue with current `torch` and `ultralytics` versions, a minimal repro, the full traceback, and `yolo checks` output from our [troubleshooting guide](https://docs.ultralytics.com/guides/yolo-common-issues/) so we can track it properly and evaluate whether adding an MPS warning or temporary fallback on our side makes sense.
