### ISSUE TITLE
Properly indentify with Ultralytics module when results for an image is zero

### ISSUE THREAD

**Issue by pydoni** [ultralytics/ultralytics#4070]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello everyone, I've started using the Ultralytics module and I'm applying inference to a bunch of files iterating in a for that applies some functions on each detection as the files are being infered ( so the modelsource is only one file at a time), the thing is, as sometimes there will not be any detections I would like to skip the iteration, and I'm trying to understand if there is a proper way to know if the list of Results() does not have any predictions.

I know that if I use the condition results[0].boxes.cls == 0,  I can verify that there is no classes, but I'm wondering if there is any scenario where the list will be none or this condition will fail, even if there is no detection.

**Comment by glenn-jocher** [comment]
@pydoni hello, thank you for using the Ultralytics YOLOv8 module and reaching out with this inquiry.

In your scenario, where an image processed by the model may not have any detections, the Results object will still contain information but the 'pred' field that holds the predictions would be empty, i.e., `results.pred` would be an empty tensor. This state can be efficiently checked with the `.numel()` method that PyTorch provides for its tensor objects. 

If you call `results.pred.numel()`, it will return the total number of elements in the tensor, which will be zero in the case when no detections are made by the model. Hence, you can use this code snippet `if results.pred.numel() == 0:` as a conditional check in your loop to skip the iteration when there are no detections.

The `results[0].boxes.cls == 0` condition that you mentioned checks if the class of the first box is 0, and not whether detections are present or not. Thus it's not suitable for your use case.

Please don't hesitate to ask if you have more questions. 

Enjoy using the Ultralytics YOLOv8 module!

**Comment by pydoni** [comment]
Thanks a lot @glenn-jocher now I know why i wasn't having detections in the first class

**Comment by glenn-jocher** [comment]
@pydoni you're welcome! I'm glad the explanation helped clarify why you weren't getting detections for the first class. Always remember that class indices start from 0, so any misalignment in the labeling could result in unexpected results. If you have any more questions about using YOLOv8 or run into any other issues, feel free to ask. The Ultralytics team and community are here to help. Keep up the great work!

**Comment by pydoni** [comment]
Hey @glenn-jocher So today I tried to use the pred.numel() and I've got a warning saying that the Result objects does not have the pred attribute.

snippet of the code(Used [0] as detections is a list of results objects)
```
    detections = model(image_path, conf = 0.6, classes=[0,1], device = 0, verbose = True, save = True, save_txt=True)
    if detections[0].pred.numel() == 0:
        continue
```

**Comment by glenn-jocher** [comment]
Hi @pydoni,

I apologize for the confusion, my previous explanation was incorrect. In the Ultralytics YOLOv8 design, the `pred` attribute directly does not exist within the `Results` object. Instead of `pred`, the information about bounding boxes and classes are stored under the `boxes` attribute. The `boxes` attribute of `Results` object is of type `Boxes` and it in turn has `xc`, `yc`, `w`, `h`, `cls` (class labels) and `conf` (confidence scores).

When it comes to checking if there are no detections, you can check the shape of the `Boxes` object. If it's empty, it indicates there are no detections.

For example, in your code, rather than `detections[0].pred.numel() == 0`, you would want to use `len(detections[0].boxes) == 0` to confirm if there are detections or not.

I hope this provides a solution to your issue. Thanks for bringing this to my attention, and sorry for the slip-up in my previous message. If you have more questions or need further assistance, please feel free to ask.

**Comment by glenn-jocher** [comment]
@pydoni, you're most welcome! It's always a pleasure to help you out with your inquiries related to YOLOv8. I'm glad we could assist in getting your issue resolved. If you have any further questions or if there's anything else you're uncertain about, don't hesitate to ask. We're here to support you! thank you for using our YOLOv8 implementation. Keep up the excellent work!
