### ISSUE TITLE
yolo export .. format=ncnn: yolov8 offical export ncnn model can not work well

### ISSUE THREAD

**Issue by linfengca** [ultralytics/ultralytics#4073]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I exported ncnn model : yolo export model=runs\segment\train10\weights\best.pt format=ncnn

then try with c++ code like below:

`
static int detect_yolov8(const cv::Mat& bgr, std::vector<Object>& objects)
{
    ncnn::Net yolov8;

	yolov8.load_param("D:/model/model.ncnn.param");
	yolov8.load_model("D:/model/model.ncnn.bin");

    int width = bgr.cols;
    int height = bgr.rows;

    const int target_size = 640;
    const float prob_threshold = 0.9f;
    const float nms_threshold = 0.5f;

    // pad to multiple of 32
    int w = width;
    int h = height;
    float scale = 1.f;
    if (w > h)
    {
        scale = (float)target_size / w;
        w = target_size;
        h = h * scale;
    }
    else
    {
        scale = (float)target_size / h;
        h = target_size;
        w = w * scale;
    }

    ncnn::Mat in = ncnn::Mat::from_pixels_resize(bgr.data, ncnn::Mat::PIXEL_BGR2RGB, width, height, w, h);

    // pad to target_size rectangle
    int wpad = (w + 31) / 32 * 32 - w;
    int hpad = (h + 31) / 32 * 32 - h;
    ncnn::Mat in_pad;
    ncnn::copy_make_border(in, in_pad, hpad / 2, hpad - hpad / 2, wpad / 2, wpad - wpad / 2, ncnn::BORDER_CONSTANT, 0.f);

    const float norm_vals[3] = { 1 / 255.f, 1 / 255.f, 1 / 255.f };
    in_pad.substract_mean_normalize(0, norm_vals);

    ncnn::Extractor ex = yolov8.create_extractor();
    **ex.input("in0", in_pad);

    ncnn::Mat out;
    ex.extract("out0", out);

    ncnn::Mat mask_proto;
    ex.extract("out1", mask_proto);**

    std::vector<int> strides = { 8, 16, 32 };
    std::vector<GridAndStride> grid_strides;
    **generate_grids_and_stride(in_pad.w, in_pad.h, strides, grid_strides);**

    std::vector<Object> proposals;
    std::vector<Object> objects8;
    generate_proposals(grid_strides, out, prob_threshold, objects8);
`

generate_grids_and_stride got exception!

the input image after in_pad: w=640，h=512，out0: w=8400，h=37，then generate_proposals : "const float* scores = pred.row(i) + 4 * reg_max_1;"  got exception (out of bounds, illegal access)，the mask_proto is ok: w=160,h=280

May I know what causes it?

**Comment by linfengca** [comment]
By the way,  that codes come from 
[ncnn-android-yolov8](https://github.com/FeiGeChuanShu/ncnn-android-yolov8)

**Comment by linfengca** [comment]
https://github.com/FeiGeChuanShu/ncnn-android-yolov8/issues/24

**Comment by glenn-jocher** [comment]
@linfengca hello, thank you for reaching out with your query. 

Regarding the exception that you have come across, it appears like you're encountering an out-of-bounds error. This is typically because of some dimension mismatch. 

In the 'detect_yolov8' function, `generate_grids_and_stride(in_pad.w, in_pad.h, strides, grid_strides)` seems to be throwing the exception. From your description, your input image dimensions are w=640, h=512 after padding. On the other hand, out0 has dimensions w=8400, h=37. 

The "generate_grids_and_stride" function is likely expecting to process an output size that matches the scaled and padded input size. Therefore, the discrepancy between these two sizes could be causing the exception.

If you find that this does not resolve the issue or leads to new issues, please consider providing a smaller, minimum reproducible example. Sometimes, simplifying the code can make it easier to pinpoint the root cause of the issue.

As a next step, I suggest verifying the input and output sizes at each stage. You may also want to double-check the original YOLOv8 paper and the code that you are referencing to ensure that the operation is being carried out correctly.

Please continue to provide updates as your troubleshooting progresses, as this information can be crucial for diagnosing the issue. If the issue still persists, we can look further into this. Your contribution helps improve the robustness of the code base! Remember, the process of resolving this will be a learning experience for everyone involved.

Just keep in mind to follow standard coding conventions and best practices regarding handling exceptions and validating array accesses. Your diligence in these matters is greatly appreciated. Keep up the great work!

**Comment by linfengca** [comment]
Sorry, I made a mistake,  "generate_proposals"  dimension mismatch.

**Comment by linfengca** [comment]
This difference leads to dimension mismatch:
![image](https://github.com/ultralytics/ultralytics/assets/21029220/37219600-5a81-4089-af72-be05b85b9255)
![image](https://github.com/ultralytics/ultralytics/assets/21029220/d0fc6669-6b0e-4b88-baac-b14337be2923)

**Comment by glenn-jocher** [comment]
@linfengca hi there! 

I see what you're pointing out. The mismatch between these dimensions is likely behind the error you're experiencing. 

The images you've provided are quite helpful in understanding the issue. The first image shows a 2D array of dimensions (640, 512) representing your padded image. On the other hand, the second image describes a 2D array of dimensions (8400, 37) which is your output.

Without knowing the specific operations done in your code, what I can infer is that one of these arrays might be trying to conform to the shape of the other one which leads to an 'Out Of Bounds' exception.

"Out of bounds" errors occur when you try to access an index which doesn't exist in the array. In the context of your issue, it can mean that you are trying to map the values of your output to locations in your input array which do not exist. This possibly happens during the "generate_proposals" stage.

To resolve this, try to ensure that any operation involving these two matricies respects their shapes and no values are being allocated to nonexistent indices.

Keep experimenting and good luck! Please let us know if you have any other issues or questions.

**Comment by superbayes** [comment]
### pls Refer to the following link:
* [详细记录u版YOLOv8目标检测ncnn实现](https://zhuanlan.zhihu.com/p/606536868)
* [ncnn-examples](https://github.com/triple-Mu/ncnn-examples)

### Regarding your question, I suggest modifying the structure of the model to accommodate ncnn inference

**Comment by glenn-jocher** [comment]
@superbayes hello, 

Thank you for sharing these resources and for your advice. It's true that adjustments often need to be made to the model structure for compatibility with specific inference engines like ncnn.

For instance, operations or layers in the original model that might not be supported in ncnn would need to be replaced with equivalent operations that are supported. This could involve using different types of layers, or reconfiguring the model structure to work efficiently within the capabilities of ncnn.

Moreover, during this transition, certain attributes of the model might need to be preserved such as the input size, and some hyper-parameters. These are simply guidelines and the specific modifications would greatly depend on the model at hand.

Certainly, the provided links should serve as helpful directions to anyone trying to implement YOLOv8 with ncnn. Let's keep exploring and improving! Your contributions are most appreciated. 

If you have further questions or issues, feel free to keep sharing. Happy coding!
