### ISSUE TITLE
where can i got a yolov8n-cls.yaml when i train a classify task

### ISSUE THREAD

**Issue by jamesbondzhou** [ultralytics/ultralytics#4078]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hi,there~
when i train my classify dataset,i use the code below:

```
from ultralytics import YOLO
# Load a model
model1 = YOLO('yolov8n-cls.yaml')  # build a new model from YAML
model2 = YOLO('yolov8n-cls.pt')  # load a pretrained model (recommended for training)
model3 = YOLO('yolov8n-cls.yaml').load('yolov8n-cls.pt')  # build from YAML and transfer weights
# Train the model
model.train(data='datasetpath', epochs=100, imgsz=64)
`

**only load a model as model2,i can train correctly，so is yolov8n-cls.yaml a model structure yaml file? where did i get this file ?**

wish your guys' reply,thanks!!!




### Additional

another tips:
model.train(data='datasetpath', epochs=100, imgsz=64)
here,'data' should receive a para as datasetpath,but cant receive a data.yaml like detect or segment or pose task, a bit interesting~~
i try to give a data.yaml as datasetpath,which is just under the dir of ./ultralytics-main ,the same level as mytrain.py

`model2 = YOLO('yolov8n-cls.pt')
model.train(data='data.yaml', epochs=100, imgsz=64)
`

finally i got a bug with file not found:
Dataset not found ⚠️, missing path ./ultralytics-main/datasets/data.yaml

even i move the yaml file to ./ultralytics-main/datasets/    bug is still the same

**Comment by glenn-jocher** [comment]
@jamesbondzhou hi there,

Thanks for using YOLOv8 and reaching out with your questions.

To clarify, 'yolov8n-cls.yaml' would indeed be a YAML configuration file that specifies the structure of the model you're wanting to train. The 'cls' in the filename suggests it's configured specifically for a classification task. If it's not included in the YOLOv8 repository, it's likely because the models provided focus primarily on object detection tasks rather than classification. 

For classification tasks, you might consider creating a custom YAML configuration file that's tailored to your specific needs. You'd define your model architecture and hyperparameters here.

Regarding your dataset, when you specify the `data` parameter in the `model.train()` function, it's expecting a path to a folder containing your training and validation images, not a YAML file. This could explain why you're encountering a File Not Found error when you're passing a YAML file path. 

You'll need to pass the path to the directory where your training images are stored and YOLOv8 will handle loading and preprocessing them for you. Make sure this path is relative to the script that's calling `model.train()`, not the location of the 'ultralytics' library itself.

Hopefully this helps, let me know if you have any further questions! 

Best,
Glenn
