### ISSUE TITLE
Request for pretrained model of yolov8n-p2.pt/yolov8n-seg-p2.pt

### ISSUE THREAD

**Issue by wwt123-star** [ultralytics/ultralytics#4087]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

We want a p2 pretrained model for our project experiment of small object detection. Will there be one for p2 in the future?

### Additional

No

**Comment by iagupov** [comment]
I think a p2 model is already available. Please check [here](https://github.com/ultralytics/ultralytics/issues/981#issuecomment-1584582039)

**Comment by wwt123-star** [comment]
> I think a p2 model is already available. Please check [here](https://github.com/ultralytics/ultralytics/issues/981#issuecomment-1584582039)
Excuse me, I mean the weights of .pt file.
![Snipaste_2023-08-01_18-40-15](https://github.com/ultralytics/ultralytics/assets/67778649/d1bfd4d7-7aba-45cf-bf38-f228950dda91)

**Comment by glenn-jocher** [comment]
@wwt123-star hello and thank you for your interest in the YOLOv8 p2 model.

The model you're asking about is definitely in our pipeline. However, we typically do not release .pt weights for every model due to the large storage requirements and the amount of computation resources needed to train them. We encourage users to train the models on their own using the provided configuration files and training scripts to accommodate their specific needs.

Nevertheless, we appreciate your feedback and will take it into consideration for future model releases. Your patience and understanding is greatly appreciated.

Please, let us know if you have further questions or need more guidance.

**Comment by Lexiaotian** [comment]
> 您好，感谢您对 YOLOv8 p2 模型的关注。
> 
> 您询问的模型肯定在我们的管道中。但是，我们通常不会为每个模型发布 .pt 权重，因为存储需求很大，而且训练它们所需的计算资源量很大。我们鼓励用户使用提供的配置文件和训练脚本自行训练模型，以满足他们的特定需求。
> 
> 尽管如此，我们感谢您的反馈，并将在未来的模型发布中考虑这些反馈。非常感谢您的耐心和理解。
> 
> 如果您有其他问题或需要更多指导，请告诉我们。

Excuse me, can Tensorrt directly deploy the p2 model or do I need to write a custom layer

**Comment by ryan-jeon** [comment]
> @wwt123-star hello and thank you for your interest in the YOLOv8 p2 model.
> 
> The model you're asking about is definitely in our pipeline. However, we typically do not release .pt weights for every model due to the large storage requirements and the amount of computation resources needed to train them. We encourage users to train the models on their own using the provided configuration files and training scripts to accommodate their specific needs.
> 
> Nevertheless, we appreciate your feedback and will take it into consideration for future model releases. Your patience and understanding is greatly appreciated.
> 
> Please, let us know if you have further questions or need more guidance.

Hi Glenn

I am needing to detect small objects and my custom trained v8 model (both n and xl) is not doing the job. I noticed this post on using the p2 model. I am wondering if you can provide some instructions on how I could obtain those weights, specifically on re-training a model using my custom dataset? Thank you so much!

**Comment by glenn-jocher** [comment]
@ryan-jeon hello, 

Thank you for reaching out and expressing interest in the YOLOv8 p2 model. 

As for the weights of the p2 model, unfortunately, we're not able to provide them directly due to large storage requirements and the intensive computational resources needed for training. What we generally encourage our users to do is train their own models with the provided configuration files and training script.

However, here is a brief guide on how you can train the model with your custom dataset. Firstly, you need a correctly formatted dataset following the instructions offered in our documentation. Then simply specify your dataset and the p2 model configuration in the training script and initiate the training process. Remember to adjust the hyperparameters based on the specific details of your custom dataset to ensure optimal results.

The model will then start to learn from your custom dataset and eventually generate a set of weights that would be unique and optimized for your specific task.

I hope this provides some clarification. Please let us know if you have any more questions or require further guidance.
