### ISSUE TITLE
Does Ray Tune for YOLOv8 work on Databricks? 

### ISSUE THREAD

**Issue by SilverStarCoder** [ultralytics/ultralytics#4095]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have been struggling to implement hyperparameter optimization using Ray Tune on yolov8 models on Databricks. I have followed the guide here: https://docs.ultralytics.com/integrations/ray-tune/, but faced several issues:

-  The provided usage code cannot be used as is; it seems you first need to setup a ray cluster for databricks, like this: 

 ```
from ray.util.spark
import setup_ray_cluster
setup_ray_cluster(num_worker_nodes = 8)
```
- but then, you can't even run the example code given:
```
from ultralytics import YOLO
model = YOLO("yolov8n.pt")
result_grid = model.tune(data="coco128.yaml")
```
because it is always saying
 ```
Error: No available node types can fulfill resource request {'CPU': 8.0}. Add suitable node types to this cluster to resolve this issue.
Trial status: 10 PENDING
```

I have tried different CPU and GPU cluster configurations on Databricks and still facing the issue.

**Comment by glenn-jocher** [comment]
@SilverStarCoder thank you for your question. It sounds like you're encountered an issue related to Ray Tune's interaction with Databricks rather than a YOLOv8 specific issue.

When using Ray Tune, it needs to be configured to respect the resources available. The error message you're seeing about `No available node types can fulfill resource request {'CPU': 8.0}` suggests that the configuration is trying to allocate more CPU resources than available in your setup.

It is likely that the compute resources available on your Databricks environment may not match the needs of your Ray Tune configuration, which could be causing the problem. Indeed, for this kind of configuration, one must ensure that there are suitable resources available for your tasks.

I recommend checking your cluster configuration to ensure it meets the requirements you have for running the YOLOv8 model with Ray tune and also cross-checking your configuration parameters.

Also, do not forget to ensure that the hardware distribution among your Ray tune tasks and other running tasks in your cluster (if any) is optimized.

Remember, YOLOv8 and Ray Tune are high-performance tools that may require considerable computing resources, especially if you're training large and complex models.
