### ISSUE TITLE
Pretrained argument for Detection Model

### ISSUE THREAD

**Issue by mateusz-wozny** [ultralytics/ultralytics#4099]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

**Pretrained argument**
I want to ask how does pre-trained argument work for the Detection Model? For the classification model, I see that set `pretrained=False` reset parameters for some layers (https://github.com/ultralytics/ultralytics/blob/main/ultralytics/models/yolo/classify/train.py#L37). I suspected that for detection operation will work similar (maybe reset only parameters of classification head) but I don't see it in this code https://github.com/ultralytics/ultralytics/blob/main/ultralytics/models/yolo/detect/train.py#L58-#L63. Is there any possibility of reset the parameters for Detection Model?

**Comment by xaristeidou** [comment]
@mateusz-wozny If you want in detection model to use pretrained weights you just load any pre-trained model, e.g. `model = YOLO("yolov8n.pt")`. Then if you train the model using `model.train()`, that is a pre-trained model which will be fine-tuned to your custom dataset.

If you want not to use pre-trained model, you have to load `model = YOLO("yolov8n.yaml")`. The rest of the process remains the same. When you load the model using the yaml file, the model is created from scratch and the weights are not pretrained, they are just initialized.

**Comment by Y-T-G** [comment]
@xaristeidou In the [docs](https://docs.ultralytics.com/tasks/detect/#train), there are these two:

```
# Start training from a pretrained *.pt model
yolo detect train data=coco128.yaml model=yolov8n.pt epochs=100 imgsz=640

# Build a new model from YAML, transfer pretrained weights to it and start training
yolo detect train data=coco128.yaml model=yolov8n.yaml pretrained=yolov8n.pt epochs=100 imgsz=640
```

What's the different between the first and the second?

**Comment by glenn-jocher** [comment]
@mateusz-wozny the first command, `yolo detect train data=coco128.yaml model=yolov8n.pt epochs=100 imgsz=640`, allows you to train a model with pretrained weights. Essentially, you're starting the training from a specific checkpoint, which is going to be `yolov8n.pt` in this case. You would use this command when you want to continue training of a model that you already have some pretrained weights for, which can speed up the training process and might potentially lead to better performance.

On the other hand, the second command, `yolo detect train data=coco128.yaml model=yolov8n.yaml pretrained=yolov8n.pt epochs=100 imgsz=640`, allows you to build a new model from a YAML file, and transfer pretrained weights to it before starting the training. In this case, you're defining the architecture of the model with the YAML file and transfer the pretrained weights only to layers that exist in both the YAML model and the pretrained model. This is often used when you want to modify the architecture of the pretrained model, for example if you want to add or remove layers, and still transfer as many weights as possible from the pretrained model.

In both cases, the model is then further trained on the `coco128.yaml` dataset. The main difference lies in whether you want to keep the entire model architecture and continue training (first command), or if you want to modify the architecture and still leverage the pretrained weights (second command).

**Comment by mateusz-wozny** [comment]
@glenn-jocher @xaristeidou Thank you for your answers. I really appreciate that. I think I don't show my case enough clearly. 
**Example**
For example, I have a detection model called `model_a.pt` trained on dataset `my_dataset_a.yaml` with 30 classes. On the other hand, I want to train a new detection model e.g. `model_b.pt` on a dataset called `my_dataset_b.yaml` also with 30 classes. I want to use the pre-trained model `model_a.pt`, but I don't want to change architecture (your second command) and also I don't want to continue training (first command). I want to reset some parameters of the pre-trained model. I thought that set `pretrained=False` (pre trained | False | whether to use a pre-trained model - according to documentation) will cause reset parameters for example for the classification head. Without this functionality, I have to change the number of classes artificially, which causes the creation of a new classification head with initialized parameters.

**Comment by glenn-jocher** [comment]
@xaristeidou I see now, thank you for the clarification. The `pretrained=False` argument does not directly reset parameters, but sets the model to be initialized from scratch without any pretrained weights. If you want to leverage your `model_a.pt` pre-trained on `my_dataset_a.yaml`, but want to reset parameters for certain parts of the model, unfortunately, this functionality is not directly supported in the current framework. You would need to manually modify the weights after loading the model, specifically resetting the layers you want.

Please note that transferring the weights from `model_a.pt` to `model_b.pt` where the output classes are different could potentially have its own challenges even if it's the same model architecture because the last layer (classification layer) dimensions might differ due to the different number of classes. So, the reset of parameters you are after might need to be more targeted, often involving the latter layers of the model which are usually the classification layers.

Also, keep in mind that the initial training of `model_a.pt` on `my_dataset_a.yaml` has tuned the model's parameters for those specific 30 classes. If `my_dataset_a.yaml` and `my_dataset_b.yaml` datasets are very different, those specific feature representations learned for the 30 classes in `my_dataset_a.yaml` may not generalize well to the new dataset degrading the model performance.
