### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by Mrgorlay** [ultralytics/ultralytics#4109]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://githubfast.com/ultralytics/ultralytics/issues) and [discussions](https://githubfast.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

您好，我遇到了一个问题，使用yolov8进行预测，使用的简单代码如下：

            img_bytes = file_obj.read()

            img = Image.open(io.BytesIO(img_bytes)).convert('RGB')
            cache_data = cache.get(modelname)
            if not cache_data:
                return Response({'error', 'Model not found'})
            modelobj = cache_data['obj']
            confidence = cache_data['conf']
            status = cache_data['Status']
            if status == 0:
              
                results = modelobj.predict(source=img, save=True, save_txt=True, save_conf=True, conf=confidence)

报错
![image](https://github.com/ultralytics/ultralytics/assets/95949360/6c8b5aad-f4ed-4ccf-a8f6-9a8e45ead8d1)

实际上是四张卡，
![image](https://github.com/ultralytics/ultralytics/assets/95949360/c915e57b-3cab-45ca-8e16-c480c06b3fba)

代码怎么实现多张卡同时执行呀，这样实际上是64G的显存，device不能直接设置成device='0,1,2,3'是吗？那怎么设置修改代码呀，很感谢！
谢谢！

**Comment by linjing-lab** [comment]
one possible solution is to take `gc.collect()` and `torch.cuda.empty_cache()` to release cuda caches, but you may need to locate at any single epoch in training process (or you might train only one epoch). @Mrgorlay Your pretrained model parameters are not related to the cumulative cuda caches after total epochs.

or you can use the following command line combined with `--batch_size`, `--data`, `--epochs`, `--optimizer`
```python
python -m torch.distributed.launch --nproc_per_node 4 train.py --device 0,1,2,3
```
> nproc_per_node specifies how many GPUs you would like to use.

refer to [torch.distributed](https://pytorch.org/docs/stable/distributed.html) for more setting infomations.

**Comment by glenn-jocher** [comment]
@linjing-lab one of the primary reasons behind the "CUDA Out of Memory" error can be due to GPU memory restrictions. In your scenario, the error arises when training your model, which could be an indication that your model or batch size is too large to fit within your GPU's memory. 

To resolve this, you could extract and empty CUDA caches after each training epoch by making use of Python's built-in garbage collector (`gc.collect()`) and PyTorch's function for emptying CUDA caches (`torch.cuda.empty_cache()`). However, bear in mind that these functions should be placed at appropriate locations within your training process. In your case, it might be necessary to apply them after each epoch in your training routine.

Alternatively, you could leverage PyTorch's distributed training functionality, specifically its `torch.distributed.launch` module. By specifying the number of GPUs used (`nproc_per_node 4`) and the GPU ids (`--device 0,1,2,3`) at the command-line level when calling your training script (for example, `train.py`), you can distribute your training across multiple GPUs, which can alleviate out-of-memory issues by effectively expanding the pool of available GPU memory.

Please see the PyTorch documentation on distributed training for more information and possible configurations.
