### ISSUE TITLE
GpU inference

### ISSUE THREAD

**Issue by karunakr** [ultralytics/ultralytics#4113]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, 

I can see that when i run below command on terminal it runs on gpu and is faster

yolo task=detect mode=predict model=yolov8x-pose-p6.pt source="bad.jpg"
Whereas, below line of code though not giving any error its slower and is not making use of gpu

results = model.predict(source=sharpened_frame, imgsz=1280, save=True, boxes=True, conf=0.01, iou=0.85,device =0)[0]

Can you please poing me what's going on wrong here?

Thanks
Karunakar

**Comment by glenn-jocher** [comment]
@karunakr hello Karunakar,

Thank you for reaching out. Judging by your description, it's likely that the slowdown you're experiencing in your code is due to a difference between running commands in terminal and programmatically using the model. In your command line execution, you have efficient control over the GPU utilization, which is not easily replicated in a Python environment.

However, when you're running your code programmatically, there are certain factors you need to consider. Firstly, make sure that PyTorch has correctly identified and is utilizing your GPU. You can check this using PyTorch's built-in functions like `torch.cuda.is_available()` or `torch.cuda.current_device()`. If for some reason PyTorch isn't able to access the GPU, that could explain the decreased performance.

Secondly, consider your image size in the `imgsz` parameter. The image size value can dramatically affect performance. Larger image sizes require more computation power and hence might take longer to process, especially if there are many images to process.

Lastly, it's also important to note that repeated call to `model.predict()` in a loop might lead to a performance loss if each image runs independently. A more efficient approach might be to predict a batch of images at once, which allows the GPU to process more information at once.

I hope these possibilities help you narrow down the source of your issue. Please let us know how you progress, and don't hesitate to circle back if you have more questions.

Best regards,
Glenn Jocher

**Comment by glenn-jocher** [comment]
@karunakr hi Karunakar,

I'm glad to hear that you found the issue. Switching between CPU and GPU in the same program can sometimes lead to unexpected behavior, so it's good that you've identified this.

As for your question about forming batches and running predictions, the main idea is to put a number of images into a list and pass the list to the predict function in place of an individual image. The length of the list would be the batch size.

Please note that you have to ensure that all images in the list are of the same size as the model expects the input to have consistent dimensions. They don't necessarily need to be the same original size, but they should be resized to the same dimensions.

In terms of sequence, the resulting predictions will correspond to the order of the images in the input list. So, if you input [image1, image2, image3], then the output prediction will be something like [pred1, pred2, pred3], each aligning with the image they were derived from.

Hope this helps!

Regards,
Glenn Jocher
