### ISSUE TITLE
Not able to train the model with objects365 dataset

### ISSUE THREAD

**Issue by ramanchalla** [ultralytics/ultralytics#4116]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I am trying to train yolov8 model with object365 dataset (https://docs.ultralytics.com/datasets/detect/objects365/#dataset-yaml)

Here is the code I am using for training

```
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8x.pt')  # load a pretrained model (recommended for training)

model.train(data='Objects365.yaml', epochs=100, imgsz=640)

results = model('https://ultralytics.com/images/bus.jpg')

for result in results:
    boxes = result.boxes  # Boxes object for bbox outputs
    masks = result.masks  # Masks object for segmentation masks outputs
    keypoints = result.keypoints  # Keypoints object for pose outputs
    probs = result.probs  # Class probabilities for classification outputs
    print (probs)
```

I am getting the network timeout error (I have attached the screenshot), couple of my colleagues are facing the same problem.

![ultralytics-objects365](https://github.com/ultralytics/ultralytics/assets/125406601/e3db1a13-262e-4ab9-8c78-674b462c4dac)

### Environment

Ultralytics YOLOv8.0.146  Python-3.10.11 torch-2.0.1+cu118 CUDA:0 (NVIDIA GeForce GTX 1070, 8192MiB)

### Minimal Reproducible Example

```
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8x.pt')  # load a pretrained model (recommended for training)

model.train(data='Objects365.yaml', epochs=100, imgsz=640)

results = model('https://ultralytics.com/images/bus.jpg')

for result in results:
    boxes = result.boxes  # Boxes object for bbox outputs
    masks = result.masks  # Masks object for segmentation masks outputs
    keypoints = result.keypoints  # Keypoints object for pose outputs
    probs = result.probs  # Class probabilities for classification outputs
    print (probs)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ramanchalla thank you for your detailed issue report. Trying to train the YOLOv8 model with the Objects365 dataset should generally run smoothly, so I'm sorry for any trouble you've encountered.

The error you're facing indicates a network timeout, which is typically not an issue with the code or dataset itself but rather a problem with the network connection where you're trying to run the training. It could be that your system isn't able to fetch the data from the Objects365 dataset due to slow or unstable internet connectivity. 

Please start by checking your internet connectivity. If the problem persists even with a stable connection, you might want to consider downloading the dataset to your local system and pointing the 'data' argument in the model.train function to the local path of the dataset.

Furthermore, please ensure that you are using the most recent version of YOLOv8 as we are constantly updating and improving its functionality based on user feedback.

Hope this helps! If you have further issues or questions, don't hesitate to reopen this issue or create another one. We are always here to support you in your AI journey with YOLOv8.

**Comment by Noctural123** [comment]
@glenn-jocher Hi! I'm also trying to train the model on this dataset in order to detect a pen, I'm having trouble with the model predicting a pen, it mixes it up with a toothbrush.

Anyways, here is the code I'm using:
```
from ultralytics import YOLO

# Load a model
model = YOLO("runs\\detect\\train\\weights\\best.pt")  # load a pretrained model (recommended for training)

# Train the model
results = model.train(data='Objects365.yaml', epochs=100, imgsz=640)

results = model.predict(source="0", show=True)

print(results)
```

I'm getting these errors:

```

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
Traceback (most recent call last):
  File "C:\Users\-----\anaconda3\envs\yolov8\Lib\site-packages\ultralytics\data\base.py", line 118, in get_img_files
    assert im_files, f"{self.prefix}No images found in {img_path}. {FORMATS_HELP_MSG}"
AssertionError: train: No images found in C:\Users\----\datasets\Objects365\images\train. Supported formats are:
images: {'jpeg', 'dng', 'bmp', 'mpo', 'png', 'tif', 'pfm', 'webp', 'jpg', 'tiff'}
videos: {'mpeg', 'asf', 'ts', 'webm', 'avi', 'm4v', 'wmv', 'mov', 'mp4', 'mpg', 'gif', 'mkv'}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\-----\Desktop\YOLOV8\train_model.py", line 7, in <module>
    results = model.train(data='Objects365.yaml', epochs=100, imgsz=640)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-----\anaconda3\envs\yolov8\Lib\site-packages\ultralytics\engine\model.py", line 668, in train
    self.trainer.train()
  File "C:\Users\-----\anaconda3\envs\yolov8\Lib\site-packages\ultralytics\engine\trainer.py", line 198, in train
    self._do_train(world_size)
  File "C:\Users\-----\anaconda3\envs\yolov8\Lib\site-packages\ultralytics\engine\trainer.py", line 312, in _do_train
    self._setup_train(world_size)
  File "C:\Users\------\anaconda3\envs\yolov8\Lib\site-packages\ultralytics\engine\trainer.py", line 276, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode="train")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\------\anaconda3\envs\yolov8\Lib\site-packages\ultralytics\models\yolo\detect\train.py", line 49, in get_dataloader
    dataset = self.build_dataset(dataset_path, mode, batch_size)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\--------\anaconda3\envs\yolov8\Lib\site-packages\ultralytics\models\yolo\detect\train.py", line 43, in build_dataset
    return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=mode == "val", stride=gs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\----\anaconda3\envs\yolov8\Lib\site-packages\ultralytics\data\build.py", line 88, in build_yolo_dataset
    return dataset(
           ^^^^^^^^
  File "C:\Users\------\anaconda3\envs\yolov8\Lib\site-packages\ultralytics\data\dataset.py", line 63, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\-----\anaconda3\envs\yolov8\Lib\site-packages\ultralytics\data\base.py", line 73, in __init__
    self.im_files = self.get_img_files(self.img_path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\------\anaconda3\envs\yolov8\Lib\site-packages\ultralytics\data\base.py", line 120, in get_img_files
    raise FileNotFoundError(f"{self.prefix}Error loading data from {img_path}\n{HELP_URL}") from e
FileNotFoundError: train: Error loading data from C:\Users\------\datasets\Objects365\images\train
See https://docs.ultralytics.com/datasets/detect for dataset formatting guidance.
```

**Comment by glenn-jocher** [comment]
@Noctural123 hi there! 🙌 It looks like the main issue you're encountering is related to the dataset not being found in the specified directory. This error often occurs when the dataset path is incorrect or the expected images are not available in the directory. Let's make sure the dataset is properly set up and the path in your `Objects365.yaml` file correctly points to your dataset's location.

First, double-check your dataset directory path in the `Objects365.yaml` to ensure it's accurate. It should look something like this, adapting the paths to match your structure:

```yaml
train: C:/Users/----/datasets/Objects365/images/train  # Adjust to your path
val: C:/Users/----/datasets/Objects365/images/val  # Adjust to your path
```

Also, verify that your dataset images are in one of the supported formats and are directly within the train/val directories.

Regarding the confusion between pens and toothbrushes, this often happens when the model isn't getting enough relevant training data or the classes are quite similar in appearance. Make sure you have a substantial number of annotated images for both objects. You might also consider using image augmentation strategies to introduce more variation into your training data.

Here's a slight modification to your Python code adding `show` to `train` to visualize the training process, and it’s good practice to handle errors related to file loading:

```python
from ultralytics import YOLO

try:
    model = YOLO("runs\\detect\\train\\weights\\best.pt")
    # Train the model with visualization
    results = model.train(data='Objects365.yaml', epochs=100, imgsz=640, show=True)
    print(results)

    # Predict and show predictions
    model.predict(source="0", show=True)

except FileNotFoundError as e:
    print(f"FileNotFoundError: {e}")
```

Lastly, always make sure your environment paths (like dataset location) are correctly configured 😊. If issues persist, feel free to drop another line here. Happy coding!
