### ISSUE TITLE
Tracking with bboxes ?

### ISSUE THREAD

**Issue by enessanli** [ultralytics/ultralytics#4117]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, i have an dataset which i did detection before. I want to track these object with their bboxes. Can i just use tracker of the yolov8 model ? Is it possible, and how can i do it ?

**Comment by glenn-jocher** [comment]
@enessanli hello,

Yes, YOLOv8 does support object tracking with bounding boxes! To do this, you would typically use the 'Track' mode. 

With the 'Track' mode, the YOLOv8 model can track objects in real-time. When you pass an image or video through the model, it assigns each detected object a unique identifier. As long as that object remains within the frame, the model will continuously update its position, effectively tracking it.

As for how you can do it, once you've loaded your trained YOLOv8 model, you can switch to 'Track' mode and provide it with an image or video as input. The model will then detect and track the objects within that input.

Keep in mind, tracking can take more computational resources than simple object detection because it's done in real-time and requires retaining knowledge of past frames. Therefore, ensure that your hardware is up to the task.

I hope this helps! Let me know if you need further clarification.

Best regards,
Glenn Jocher
