### ISSUE TITLE
Counting object classes from video inference 

### ISSUE THREAD

**Issue by Emily961** [ultralytics/ultralytics#4121]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi everyone, I am hoping someone can help me, I would like to know how to add a count for each time an object is detected in my video. I am looking at animal eyes and my classes are eye open or eye closed, ideally I would like to timestamp in the video each time the detector states eye closed or not detected- I can assume that the other times are eye open to save memory, or list the frame where it registers any of the classes. How do I do this when I am very new to coding? I would also like to save the annotated video. My model is trained and seems to perform well on the new videos I am using, and I am using the Streaming Source for-loop code provided (while feeding in my own video and yolo model). I have put the code below, any suggestions would be greatly appreciated 

import cv2
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO('yolov8n.pt')

# Open the video file
video_path = "path/to/your/video/file.mp4"
cap = cv2.VideoCapture(video_path)

# Loop through the video frames
while cap.isOpened():
    # Read a frame from the video
    success, frame = cap.read()

    if success:
        # Run YOLOv8 inference on the frame
        results = model.predict(frame, stream=True, conf=0.5)
        results = list(results)

        # Visualize the results on the frame
        annotated_frame = results[0].plot()

        # Display the annotated frame
        cv2.imshow("YOLOv8 Inference", annotated_frame)

        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        # Break the loop if the end of the video is reached
        break

# Release the video capture object and close the display window
cap.release()
cv2.destroyAllWindows()

### Additional

I had to add the results = list(results) because I kept getting an error message when I put stream = True

**Comment by xaristeidou** [comment]
@Emily961 Well you have to use the `results` variable for each frame. First of all you don't need to use `results = list(results)`, because results is already a list type variable. 

Well, i won't perform all these thing you need but will provide you a small action to get you started. Let's say that we have 2 counting variables `open_eyes` , `closed_eyes` , and we want to count how many frame from the video there are eye open or closed.



```
open_eyes = 0
closed_eyes = 0

while cap.isOpened():
  # Read a frame from the video
  success, frame = cap.read()
  
  if success:
      # Run YOLOv8 inference on the frame
      results = model.predict(frame, stream=True, conf=0.5)

        if results[0].boxes.cls[0].item() == 0.0:
            open_eyes += 1
        else:
            closed_eyes += 1
           
  
      # Visualize the results on the frame
      annotated_frame = results[0].plot()
  
      # Display the annotated frame
      cv2.imshow("YOLOv8 Inference", annotated_frame)
  
      # Break the loop if 'q' is pressed
      if cv2.waitKey(1) & 0xFF == ord("q"):
          break
  else:
      # Break the loop if the end of the video is reached
      break
```


You have two classes so the labels are 0 and 1. Let's say that 0 is the label for open eyes and 1 for closed eyes. In the results 0 is presented as torch tensor with value 0.0 and 1 is 1.0. 

You can modify and do any action you want after that. Export each frame, print on screen, count frames, etc. You can feed the code to GPT and suggest any actions.

**Comment by glenn-jocher** [comment]
@Emily961, for counting the number of frames where each class is detected, you might want to use the `results` variable in each frame. 

First, there is no need to use `results = list(results)`, because `results` is already a list.

In your use case, you can define two variables `open_eyes` and `closed_eyes` to count the number of frames where eyes are detected as open and closed respectively.

Within your loop, after performing the YOLOv8 inference, you can increment your variables based on the classification result. If the class detected is for "eye open", you increment `open_eyes` and similarly if the class detected is "eye closed", increment `closed_eyes`.

For the task of saving time stamps or frame numbers where the eye is detected as closed or not detected, you would need to keep track of the current frame number or time and save this when the condition is met.

As for saving the annotated video, once you have the annotated frames, you can use `cv2.VideoWriter()` to write the frames into a new video file.

Please make sure to update the class labels (`0` and `1` in the example) based on your training data. Also, this approach assumes only a single detection per frame. If your video has multiple simultaneous detections, you might need to modify this to account for that. Overall, this should help you get started on your task. 

Remember, you can also explore further functionalities such as saving each frame, displaying results on screen, and adapting the code to your specific requirements.

**Comment by Emily961** [comment]
> @Emily961 Well you have to use the `results` variable for each frame. First of all you don't need to use `results = list(results)`, because results is already a list type variable.
> 
> Well, i won't perform all these thing you need but will provide you a small action to get you started. Let's say that we have 2 counting variables `open_eyes` , `closed_eyes` , and we want to count how many frame from the video there are eye open or closed.
> 
> ```
> open_eyes = 0
> closed_eyes = 0
> 
> while cap.isOpened():
>   # Read a frame from the video
>   success, frame = cap.read()
>   
>   if success:
>       # Run YOLOv8 inference on the frame
>       results = model.predict(frame, stream=True, conf=0.5)
> 
>         if results[0].boxes.cls[0].item() == 0.0:
>             open_eyes += 1
>         else:
>             closed_eyes += 1
>            
>   
>       # Visualize the results on the frame
>       annotated_frame = results[0].plot()
>   
>       # Display the annotated frame
>       cv2.imshow("YOLOv8 Inference", annotated_frame)
>   
>       # Break the loop if 'q' is pressed
>       if cv2.waitKey(1) & 0xFF == ord("q"):
>           break
>   else:
>       # Break the loop if the end of the video is reached
>       break
> ```
> 
> You have two classes so the labels are 0 and 1. Let's say that 0 is the label for open eyes and 1 for closed eyes. In the results 0 is presented as torch tensor with value 0.0 and 1 is 1.0.
> 
> You can modify and do any action you want after that. Export each frame, print on screen, count frames, etc. You can feed the code to GPT and suggest any actions.

thank you for this comment it was really helpful! and I have with chatGPT managed the script to count the classes and also print them frame for frame in a CSV sheet, the only thing I am struggling with and also chat GPT is too, is how do I count the frames where nothing is detected? so the inference reads 0: 800x608 (no detections), 485.4ms
Speed: 5.5ms preprocess, 485.4ms inference, 0.9ms postprocess per image at shape (1, 3, 800, 608) but no matter how hard I try I cannot get it to put the frame for no detections in the CSV as it isn't actually a class name?

**Comment by xaristeidou** [comment]
@Emily961 That's easy to solve. When nothing is detected then the length of the `results` will be 0 (`len(results[0] == 0)`. 

So you can integrate it in the if statement like following:

```
if len(results[0]) == 0:
    closed_eyes += 1
elif results[0].boxes.cls[0].item() == 0.0:
    open_eyes += 1
else:
    closed_eyes += 1

```

**Comment by glenn-jocher** [comment]
Great to hear that the previous suggestions helped you, @xaristeidou! For detecting frames where nothing is detected by YOLOv8, you can utilize the length of the `results` object. If no objects are detected in a frame, the `results` object will have no elements, i.e., its length will be zero.

In this case, you can create a new condition under your current `if-else` statement to handle when the length of `results` is zero. Add it as the first condition to be checked, and when the condition is met, you can increment a counter or log these instances as you like.

Remember, this condition should be checked before making inferences on `results` (like checking class labels), to prevent erroneous attempts to access non-existent results.

Let's summarize:
- Create a new variable to count frames with no detections.
- Revise your conditional block to first check if the length of `results[0]` is zero.
- If the condition is met, increment the new counter. If it's not, then proceed with your current eye open/closed detection and counting.

This way, you'll be able to track the frames where no detections were made by YOLOv8. Continue your amazing work and don't hesitate to reach out if you have more questions.

**Comment by Emily961** [comment]
> @Emily961 That's easy to solve. When nothing is detected then the length of the `results` will be 0
> 
> ```
>  >>> len(results[0])
> 0
> ```
> 
> So you can integrate it in the if statement like following:
> 
> ```
> if len(results[0]) == 0:
>     closed_eyes += 1
> elif results[0].boxes.cls[0].item() == 0.0:
>     open_eyes += 1
> else:
>     closed_eyes += 1
> ```

thank you so much! It works brilliantly! I really appreciate your help and with actual code snippets is super helpful

**Comment by glenn-jocher** [comment]
You're very welcome, @Emily961! I'm thrilled to hear the solution works brilliantly for you. It's our aim to be as helpful as possible. If you encounter any other challenges or have further questions, don't hesitate to ask. We're always here to help. Happy coding!

**Comment by compVisual** [comment]
Hi, I'm facing a similar problem but in a different kind of way because I'm using the YOLO tracker. 


I would like to have an absolute count after processing all the video where I can obtain how many total objects were detected on the video. For example, imagin that I am tracking people and dogs in a certain video i would like to get the total amount of different people detected and same with dogs. I am aware that certain objects would be detected as different clases in some frames but i am willing to deal with that problem. Is that possible?

**Comment by glenn-jocher** [comment]
@compVisual hello,

Thank you for your question. You're interested in getting a total absolute count of detected objects, like people and dogs, after processing an entire video. That's a great use of tracking!

You can certainly gather this information. Your approach would involve two main steps:

1. Object detection: This is where YOLOv8 comes in, detecting and identifying objects frame-by-frame throughout the video. 

2. Object tracking: Link the detected objects across different frames to achieve tracking. There are several tracking algorithms available that you can use for this purpose. When an object continues to appear in multiple frames, it's typically assigned a unique ID, which can help prevent double-counting the same object.

To get your absolute count, you would just need to keep track of these unique IDs assigned to each class type in your video.

Please note that as you've mentioned, certain objects may be intermittently detected as different classes in some frames, which can lead to inaccuracies in your counts. You may need to refine your criteria for unique IDs or use additional logic to adjust for these potential discrepancies. 

I hope this gives you a good starting point for your project. Best of luck with your object tracking!

**Comment by compVisual** [comment]
Can someone give me an example on how to track these unique IDs?

**Comment by xaristeidou** [comment]
@compVisual It's because results is a list of the predictions. It's element of the list contains the prediction for each different frame.

results[0] -> predictions for frame 0
results[1] -> predictions for frame 1
...
results[n] -> predictions for frame n


You can access the predictions for each frame with the following code:

```
from ultralytics import YOLO

model = YOLO("/best.pt")

results = model.track(source = "/bottles.mp4", conf = 0.25, save = False)

total_objects = 0

for frame in results:
    for objects in frame.boxes:
        objects.boxes.cls  # tensor with classes for each object in frame
        objects.boxes.xyxy  # tensor with xy coordinates for each object in frame 
        objects.boxes.id  # tensor with id numbers for each object in frame
        objects.boxes.conf  # tensor with confidence levels for each object in frame

        if int(objects.id.max()) > total_objects:
            total_objects = int(objects.id.max())
```

You can easily find the total number of unique object that has been tracked from the model keeping the max of id_num from each frame.

**Comment by compVisual** [comment]
No, the process just terminates. I was going to try it on Google Colab with more gpu to see if there is a problem with my computer

**Comment by xaristeidou** [comment]
You can check you resources, GPU memory and RAM memory. If you are at windows open Task Manager. In ubuntu open System Monitor.

**Comment by glenn-jocher** [comment]
@xaristeidou sure, running out of resources is a common issue when dealing with large video files or high-resolution videos. To identify whether this is the problem, we recommend monitoring your system resources during processing. You should keep an eye on both your GPU memory and your RAM usage.

If you're using a Windows machine, the Task Manager will display all these details. For Ubuntu, these details can be found in the System Monitor. JetBrains PyCharm also provides live graphs of CPU, memory, and GPU usage if you're using this IDE.

If you're running out of memory, there are a few potential solutions:

1. Resize your video input: Reducing resolution can dramatically reduce memory usage.
2. Process fewer frames: Instead of processing every single frame in the video, you could process every 2nd, 3rd, or even 10th frame, depending on your needs.
3. Upgrade your hardware: If possible, using a machine with more memory may help. Also consider whether a GPU with more memory is an option for you.

Remember to ensure that the program has the necessary rights and resources to run to completion. Be wary of any system settings that could terminate high-resource tasks.

In your case, working in Google Colab can also help to see if the issue is related to the local development environment or the code itself.

**Comment by Laranga22** [comment]
Can someone confirm if this piece of code is right for counting the same object only 1 time if the detected class changes for the same object id when tracking? Because im not 100% sure.
`    for frame in results:
        for obj in frame.boxes:
            
            class_id = int(obj.cls)
            object_id = int(obj.id)
            confidence = float(obj.conf)
            
            # Check if the object is within your defined class labels
            if class_id in class_labels:
                class_name = class_labels[class_id]

                if object_id not in unique_objects:
                    print(object_id)
                    #Add the object if it's not in the dictionary
                    unique_objects[object_id] = {
                        'class': class_name,
                        'confidence': confidence
                    }
                else:
                    # Update the objects class label if a higher confidence is encountered
                    if confidence > unique_objects[object_id]['confidence']:
                        unique_objects[object_id]['class'] = class_name
                        unique_objects[object_id]['confidence'] = confidence
`

**Comment by glenn-jocher** [comment]
@Laranga22 yes, your code seems correct. It checks for each detected object in a frame if the object ID already exists in the dictionary `unique_objects`. If the object ID does not exist, it gets added to the dictionary with its class label and a confidence score. 

If the object ID is already present in the dictionary, you check whether the present detection has a higher confidence score than the stored one. If it does, you update the class label and confidence score in the dictionary. 

So, indeed it will count the object as a unique instance and will keep the most confident class estimation in case of changes in the detected class for the same object ID during tracking. 

Please make sure you track the object identities and class labels consistently across all frames to get accurate results. Keep in mind that your results can be influenced by how stable the tracking IDs and detected classes are in your model.
