### ISSUE TITLE
Discrepancy between console output and plots for validation dataset

### ISSUE THREAD

**Issue by UTKARSHS1994** [ultralytics/ultralytics#4125]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

Thanks for this work.

I am working on object detection and trying to understand the plots generated by YOLOv8 vis-a-vis the output showed in console. I did the following:
model=YOLO('yolov8n.yaml').load('yolov8n.pt')
results=model.train(data=config_path, epochs=10, resume=True, iou=0.5, conf=0.001)

And got this output at the end:

![image](https://github.com/ultralytics/ultralytics/assets/54258787/4e01cd73-2605-497d-bad2-8e4863b5a495)

We see here that for validation dataset, the best results are P=0.885 and R=0.956

But the precision-confidence and recall-confidence curves show a different story:

![P_curve](https://github.com/ultralytics/ultralytics/assets/54258787/321b6439-84aa-42a5-a620-ae8294bc19ed)
![R_curve](https://github.com/ultralytics/ultralytics/assets/54258787/05b11238-68a4-49ca-abdd-efbd5e682e18)

1) Here we see that for conf=0.001, P is around 0.6 and R is almost 1. I expected P to be 0.885 and R to be 0.956. Why is there this discrepancy or am I missing something?

Also check the F1 curve. 
![F1_curve](https://github.com/ultralytics/ultralytics/assets/54258787/6d40a617-4fd4-4e22-88af-7a2d20f06b43)

I thought that the results in console might be for a confidence obtained from F1 curve. So I tried verifying it as follows:
![image](https://github.com/ultralytics/ultralytics/assets/54258787/ea1cd117-2f45-4465-a835-5ef9e84c9c12)

But again these results do not match with the earlier output. Here P=0.886, R=0.948. So it looks like the earlier results are not for conf=0.573 (the best confidence from F1 curve).

2) So the earlier results, that is, P=0.885 and R=0.956 are for which confidence and if they are for conf=0.001, why the plots don't match with the console output?

Regards,
Utkarsh

**Comment by glenn-jocher** [comment]
@UTKARSHS1994 hello Utkarsh,

Thank you for asking this insightful question and for providing detailed diagnostics to clarify your observations.

Before we delve into your query, it's critical to distinguish between the Precision and Recall values, and the Precision-Confidence and Recall-Confidence plots.

The values of Precision (P) and Recall (R), corresponding to 0.885 and 0.956 respectvely, that you see in the console output are produced at one specific confidence threshold, which is calculated to maximize the F1 score, a combination of Precision and Recall, during the validation process.

On the other hand, the Precision-Confidence and Recall-Confidence plots are more general-purpose and display these metrics across a range of confidence thresholds, not just at one specific point. Hence, they give you a broader view of the model performance across different confidence thresholds.

Coming to the discrepancy observed: your console output reports the best observed P and R at an optimal confidence level (which won't necessarily be 0.001). In your plots, the P and R metrics reported at conf=0.001 might vary since they are calculated at this fixed confidence value.

We hope to include specific confidence values associated with some metrics in future updates to the Ultralytics software, as this will assist in interpretation.

Thank you for bringing this to our attention, and I hope I have clarified the misunderstanding. Please feel free to ask if you need further information.

Best,
Glenn.

**Comment by UTKARSHS1994** [comment]
@glenn-jocher 
Hello Glenn,

Thanks for your reply.

You said that console output reports best observed P and R at optimal confidence level which is not necessarily 0.001. I agree.

I thought that this optimal confidence is actually the value at which F1 curve is maximum (which is 0.573 in my case). But as you see from the second part of my question, P and R at this optimal confidence value of 0.573, is also not the one I expected. I expected P=0.885 and R=0.956 but got P=0.886 and R=0.948

So then, what value is this optimal confidence? 

What I am looking for is a way to reproduce the exact validation results given at the end of training, by giving the optimal confidence as input. Hope the intent is clear.

Regards,
Utkarsh

**Comment by glenn-jocher** [comment]
@UTKARSHS1994 hello Utkarsh,

Thanks for your follow-up question, and for further clarifying your intention.

While it might seem intuitively accurate to assume that the optimal confidence equates to the point at which F1 curve is maximal, that isn't necessarily the case. The F1 score, being a harmonic mean of Precision and Recall, may balance both values, but doesn't necessarily maximise them simultaneously.

When discussing the "optimal" confidence, we're referring to the confidence threshold that our model chooses during the validation process that results in the best combination of Precision and Recall. However, this value might not exactly match F1's calculated maximum point since F1 is not the only criterion we focus on during this process.

Given the inherent variability in precision and recall scores, minor discrepancies between expected and observed results, like the ones you've encountered, can generally be considered as normal phenomena in the practice of deep learning.

Therefore, reproducing the exact validation results isn't always feasible due to these minor variations in precision and recall scores when observing the model under different confidence thresholds. 

Perhaps in future updates, we could consider including the optimal confidence value that the model chooses during validation within the console output, as it seems that could provide useful insights. 

Thanks again for your valuable question. Please feel free to reach out if there's anything else you want to discuss.

Best,
Glenn.

**Comment by UTKARSHS1994** [comment]
@glenn-jocher Hello Glenn,

Thanks for the reply. Now that I have explained my intent of  reproducing results, I think knowing optimal confidence is not mandatory.

For example, I again built the model using the same approach

model=YOLO('yolov8n.yaml').load('yolov8n.pt')
results=model.train(data=config_path, epochs=10, resume=True, iou=0.5, conf=0.001)

This time, after training completed, I checked the P curve which is below:

![P_curve](https://github.com/ultralytics/ultralytics/assets/54258787/4ff9124d-897e-42bd-aaed-915367eb1a75)

Now I did model validation at two fixed confidence intervals decided by me.
Below is the snapshot
![image](https://github.com/ultralytics/ultralytics/assets/54258787/573ee935-fca0-4f89-a0b8-13bdf78ae52e)

Here, we see P=0.915 for the two cases of conf=0.05 and conf=0.02. From plot, we can clearly see that P is not 0.915 at these confidence values. I am unable to understand this mismatch between console output and plot.

Regards,
Utkarsh

**Comment by glenn-jocher** [comment]
@UTKARSHS1994 hello Utkarsh,

Thank you for your additional clarifications and for detailing your findings.

In your experiments, you have fixed the confidence at two predetermined levels (0.05 and 0.02) while the validation process, by default, selects a confidence level that provides a high-performing balance between precision and recall. This means that the model's precision at fixed confidence intervals may, and probably will, differ from the precision at the optimal confidence interval.

However, I understand your concern about the discrepancies between the P curve plot and the console output for the same fixed confidence levels. This mismatch might be attributed to minor variations and residuals inherent in model evaluations. Machine learning models, especially those as complex as YOLOv8, might exhibit variability in outcomes due to many factors including initialization states, GPU device deltas, or even very slight dataset changes.

Another factor could be the timing of when the metrics are calculated. The metrics recorded for the PRC plot are typically calculated over the entire epoch, whereas the console output could be a snapshot of the performance at a particular iteration, potentially leading to discrepancies.

While we continuously strive to improve the consistency and clarity of our models' performance measures, please keep in mind that perfect alignment between different reports isn't always possible due to these variabilities and fluctuations.

As always, thank you for sharing your observations and please feel free to raise any further queries you might have.

Best, 
Glenn

**Comment by UTKARSHS1994** [comment]
@glenn-jocher 

Hello Glenn,

Thanks for the reply.  I am confused about one thing. You said that the metrics recorded for PRC plot are calculated over the entire epoch, whereas the console output is snapshot of performance at a particular iteration.

I think that the all the plots (P, R and PR) over all confidence thresholds between 0 and 1 are made on the validation dataset by selecting the "best.pt" model after the **end of training**.   Similarly the console output is also made on the validation dataset using "best.pt" model after the **training ends**.

Am I wrong or missing something in saying the above statement?

Regards,
Utkarsh

**Comment by glenn-jocher** [comment]
@UTKARSHS1994 hello Utkarsh,

Thanks for your patience and for faithfully following up.

Your understanding is correct for the most part. The Precision (P), Recall (R), and the Precision-Recall (PR) plots are indeed generated on the validation dataset using the "best.pt" model after training has ended. This is also the case with the console output. 

I apologize for any confusion my previous explanation may have caused. In the context of the console output, I referred to a 'particular iteration' as the point at which the model has deemed performance optimum, hence it saves the "best.pt" model. This 'iteration' is not during an epoch, but is rather the specific epoch at which the "best.pt" model was saved. 

The computations for both the plots and console output do occur after training, yet they may yield slightly different results due to varied optimal thresholds used for computation in each case.

Thank you for pointing out the need for clarity. Your questions are positively contributing towards making the YOLOv8 documentation clearer for all users.

Warm Regards, 
Glenn

**Comment by UTKARSHS1994** [comment]
@glenn-jocher Hello Glenn,

Thanks for the clarification. I am glad to know my questions are useful for the community.

Regards,
Utkarsh
