### ISSUE TITLE
GPU not connecting to Ray Tune

### ISSUE THREAD

**Issue by Anilian** [ultralytics/ultralytics#4133]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

The GPU is connected and working in training. But here, I can’t even connect the CPU 
0/8 CPUs,  0/1 GPUs
 And Error: No available node types can fulfill resource request {'CPU': 7.0, 'GPU': 2.0}. Add suitable node types to this cluster to resolve this issue.
### Additional

![image](https://github.com/ultralytics/ultralytics/assets/122607689/4ec3818c-80c0-43a8-9a29-62a454e83300)

**Comment by glenn-jocher** [comment]
@Anilian thank you for bringing this issue to our attention. Based on the error message you provided, it seems that Ray Tune is not able to allocate the amount of CPU and GPU resources requested for the task. 

In your case, it's looking for a configuration with 7 CPUs and 2 GPUs, but the available resources are significantly lower (`0/8 CPUs, 0/1 GPUs`). Thus, the error is thrown because Ray Tune is not able to find a suitable node type that can fulfill this resource request within the existing cluster.

You may want to double-check your computation environment setup and GPU drivers to ensure that they are properly installed and running. Sometimes a system or driver update can cause recognition issues with your hardware configuration. 

If still unresolved, you can directly alter the amount of resources used by Ray Tune in your task configuration. However, keep in mind that this may impact the performance and speed of the processing.

Finally, please remember to obscure or redact any sensitive information in your screenshots when posting in public venues for security reasons. Your continued safety and privacy is important to us. Should there be other issues, please feel free to provide them for further assistance.

**Comment by Anilian** [comment]
@glenn-jocher  What does it mean to change the amount of resources used by Ray Tune? is it done by the following code?
`gpu_per_trial ={"GPU": 1, "CPU": 1},`

**Comment by glenn-jocher** [comment]
Hi @Anilian,

In the context of Ray Tune, when you specify a `gpu_per_trial` or `cpu_per_trial` setting, you're basically dictating to Ray Tune how much of your machine's resources should be allocated to each individual trial it runs. 

Ray Tune is designed to automatically manage and distribute computational workloads, meaning it can simultaneously run multiple trials (if your resources allow), each potentially harnessing a different configuration of your model. This helps you to automate and streamline the process of hyperparameter tuning on your model.

By setting `{"GPU": 1, "CPU": 1}`, you're telling Ray Tune to allocate a single GPU and a single CPU for each trial. Please be aware that this also means you need to have enough resources available to meet these settings. If you see in your system that you have more resources available but they're not utilized, you might be able to get better performance by increasing these numbers.

Conversely, if resources are scarce, adjusting these figures down can help maintain effective operation, though it might necessarily extend the duration of your trials due to having less processing power. It's important to find the right balance that works beneficially for your specific system and needs.

Let's ensure we don't overallocate as well - that we're not trying to utilize more CPUs or GPUs than we actually have. Overallocating resources can lead to errors like the one you encountered before. 

I trust this explanation clarifies what changing the amount of resources used by Ray Tune means and how it impacts the model's operation. Please feel free to communicate if there's anything else you're curious about. Hopefully, this gives you a good base to troubleshoot and optimize your YOLOv8 model efficiently. Thanks for your question!
