### ISSUE TITLE
modify file predict in detect 

### ISSUE THREAD

**Issue by chelsea456** [ultralytics/ultralytics#4157]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi sir!! i want to modify file detect to use camera

**Comment by xaristeidou** [comment]
@chelsea456 I don't clearly understand what you mean, but if you want to use your camera feed to predict you can do by passing the number of `source` argument as your camera number (`0` or `1` or `2` or `3`, etc.).

`model.predict(source = 0)`

**Comment by glenn-jocher** [comment]
Hello @chelsea456,

Thanks for reaching out with your question and apologies for the confusion. If you're interested in modifying the detect file to work with a video feed from your camera, you would indeed provide the camera index (usually 0 for the system's default camera) instead of a file name to the `source` argument in the `predict` method.

However, please be aware that this might not be enough depending on what you exactly wish to achieve. While the above adjustment will feed video into the model, you may need to further modify the file depending on how you want to process and display the results. For instance, you may need to set up a loop to handle each frame from the camera feed individually and provide a means to terminate the process cleanly.

Do bear in mind that running YOLOv8 in real-time on a video stream can be performance-intensive depending on your hardware. Despite this, it's a great way to see the capabilities of the YOLOv8 model in action.

Remember, the `predict` function is usually a great starting point for such a task. You may need to delve also into the `detect` and `save_one_box` functions, as usually these play significant roles in outputting the detections to the end user.

Please let us know if you have any further questions or need additional guidance!

Best Regards,
Glenn Jocher

**Comment by chelsea456** [comment]
ret, image = cap.read()
    # #print(image.shape)
image = cv2.resize(image, (1280, 720))
count_frame = count_frame + 1
results = model(image)[0]
im0 = results.orig_img
t =time.time()
det = results.boxes.data
hi sir, i want to get coordinate box to draw bbd such as x1 y1 x2 y2

**Comment by glenn-jocher** [comment]
@chelsea456 hello,

In order to access the coordinates of the bounding box, you can extract them from the detected results. The 'boxes' attribute from the result of the model prediction contains this information. The 'data' attribute holds a tensor that includes the bounding box coordinates (x1, y1, x2, y2), among other information. 

Here's a brief explanation:
- x1 and y1 coordinates represent the top-left point of the bounding box.
- x2 and y2 coordinates represent the bottom-right point of the bounding box.

You can obtain these by indexing the 'data' attribute. The indices for x1, y1, x2, y2 are 0, 1, 2, and 3, respectively. 

For example, to draw bounding boxes on the image using OpenCV, you can use these coordinates with the `cv2.rectangle()` method. 

Please remember to convert the coordinates to integer type using `int()` function before drawing on the image, as OpenCV does not work well with float values.

I hope this helps! Let me know if you have further questions.

Best,
Glenn Jocher
