### ISSUE TITLE
result image 

### ISSUE THREAD

**Issue by minjong92** [ultralytics/ultralytics#4159]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

model = YOLO('yolov8n.yaml').load('yolov8m.pt')  # build from YAML and transfer weights
model.train(data='custom.yaml', epochs=1000, imgsz=1280, batch=2, device=0, name='PD', optimizer='AdamW')

If you check through the code, the code will turn, but the test results will not be saved. How do I save an examination image

**Comment by xaristeidou** [comment]
@minjong92 Why save through training examination image, you can use the trained weights to predict on a test set or image and see the results of the model.

**Comment by palvors** [comment]
If I see in the doc ( https://docs.ultralytics.com/reference/engine/results/#ultralytics.engine.results.Results.plot  ), we can do that : 

for r in results:
    im_array = r.plot()  # plot a BGR numpy array of predictions
    im = Image.fromarray(im[..., ::-1])  # RGB PIL image
    im.show()  # show image
    im.save('results.jpg')  # save image

BUT I got a error : 

AttributeError: 
            'Results' object has no attribute 'plot'.


AND in the doc, we use the var "im_array " that is never use

**Comment by glenn-jocher** [comment]
@minjong92 i appreciate your interest in using YOLOv8 and for bringing this up. Let's clarify these points:

Regarding your `AttributeError`, it seems there may be an inconsistency in the referenced documentation. The `Results` object does not have a `plot` method. Instead, results from training or prediction can be visualized using Ultralytics visualization utilities that accompany YOLOv8.

Regarding the unused `im_array` variable in the example, it may be the result of a simplification for illustrative purposes, and the variable would typically be used as needed in your specific application context.

Do note that for generating result images during or after model training, you may find the '—save-img' flag useful, providing control on whether to save inferenced images containing model predictions.

I apologize for any confusion caused by the documentation, and we'll take steps to clarify and correct it promptly. Thank you for your understanding, and for helping us make YOLOv8 even better.
