### ISSUE TITLE
Run YOLOv8 model like YOLOv5 PyTorch Hub

### ISSUE THREAD

**Issue by SkalskiP** [ultralytics/ultralytics#416]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I just want to run the model without all the inheritance and abstractions. Optimally something like that.

```python
from ultralytics import YOLO


model = YOLO(f'{HOME}/yolov8n.pt')
for frame in frames:
    result = model(frame)
```

Where `frame` is `np.ndarray`. I try different things, but the source for YOLO can't be `np.ndarray`. Why is that? Same for `DetectionPredictor`. Any ideas?

**Comment by AyushExel** [comment]
coming in https://github.com/ultralytics/ultralytics/pull/314

**Comment by SkalskiP** [comment]
@AyushExel Two questions:

1. Will it allow us to pass `np.ndarray`? I see this `model("img.jpg", retina_masks=True)` in this PR example.

2. Will it reload and fuse the model at the beginning of every prediction? That's what is happening now.

**Comment by SkalskiP** [comment]
@AyushExel When will those changes be released?

**Comment by AyushExel** [comment]
aiming on/before Wednesday

**Comment by AyushExel** [comment]
example usage
<img width="485" alt="Screenshot 2023-01-16 at 8 23 58 PM" src="https://user-images.githubusercontent.com/15766192/212706974-c3d49978-0eb5-4f42-aa16-e9fcaa7432be.png">

**Comment by SkalskiP** [comment]
Fingers crossed 🤞🏻! Quite unfortunate that it was not in the pip package on release. It feels to me like the most typical use case when it comes to pythonic API.

**Comment by SkalskiP** [comment]
@AyushExel, in that example, `MODEL` is the model path? there will be no model loading or fusing between model() calls?

**Comment by AyushExel** [comment]
it can be a path to yaml or a ckpt. Model loading and fusing will only happen once, not everytime the prediction function is called

**Comment by SkalskiP** [comment]
Is your current WIP version already working? I'm working on the next YOLOv8 YouTube tutorial. I don't need anything more than that API for object detection.

**Comment by AyushExel** [comment]
Right now Glenn's updating it. You should probably wait for a few hours

**Comment by SkalskiP** [comment]
Okay. I'm using 

```python
import torch

model = torch.hub.load('ultralytics/yolov5', 'yolov5l')
```

for now.

**Comment by Yassramin** [comment]
> Okay. I'm using
> 
> ```python
> import torch
> 
> model = torch.hub.load('ultralytics/yolov5', 'yolov5l')
> ```
> 
> for now.

I get the error saying that the hubconfig file is not found.

**Comment by luizconrado** [comment]
Hi @AyushExel,

Sorry for my ignorance, however;
I am confused with everything I am reading so far.
I want to get my custom-trained YOLO v8 model and:
a) import it into PyTorch
b) convert it to TensorRT and use it with PyTorch.
Is there a way to achieve it? Can you tell me how? Can you please help me with it?

Thank you.

**Comment by glenn-jocher** [comment]
@luizconrado see https://docs.ultralytics.com/modes/export and see https://docs.ultralytics.com/modes/predict

**Comment by luizconrado** [comment]
@glenn-jocher Thank you for your reply.

I have read the documentation, however, my doubt still remains.

I am 100% able to train and use the trained models using the YOLO v8 package.
So, within the YOLO v8, everything is fine and working well.
The problem starts once I try to move into PyTorch (Hub) or OpenCV.

When using YOLO v5 I was able to export my models to:
a) PyTorch: 
I would load it using the model = torch.hub.load('ultralytics/yolov5', .... - But without a hub configuration file I cannot do this with YOLO v8.
b) PyTorch using TensorRT:
I would export the model and load it just like mentioned above, however, I cannot do that due to the lack of the hub configuration.
c) OpenCV:
I was able to export the customer-trained model as an ONNX file using this command (python export.py --weights best.pt --include onnx --simplify --opset 12 --imgsz 640) and load it into OpenCV. 
However, when I set the same flags (obviously changing it to the new format, etc.) for YOLO v8 and load it into OpenCV, I am not able to get the results of the predictions as before. Almost as if the results format/structure has changed completely.

So, my questions are:
a) Is there a way for me to load my trained models into PyTorch Hub? Is there a workaround? Can you show me, please?
b) Is there a way to export the model into ONNX so I can load it into OpenCV getting the same result structure as before? I was some comments online saying one should use a different opset, etc., but that has not worked for me.

**Comment by AyushExel** [comment]
Yes you can do all of the above. See onnx opencv python and c++ examples here https://github.com/ultralytics/ultralytics/tree/main/examples

**Comment by luizconrado** [comment]
@AyushExel,

One more piece of information:
I tried updating my TensorRT to 8.6 and now I get a different error.
What I have installed is:
Python 3.10
ultralytics version 8.0.56
CUDA 11.7
CuDNN 8.8
TensorRT 8.6.0.12

The error I get is:
Loading C:\Users\Felipe\Dropbox\dev\projects\python\YOLOv8_Models\YOLOv8_Models\yolov8n_custom_1920\weights\best.engine for TensorRT inference...
[03/24/2023-02:44:03] [TRT] [I] Loaded engine size: 19 MiB
[03/24/2023-02:44:03] [TRT] [E] 1: [runtime.cpp::nvinfer1::Runtime::parsePlan::314] Error Code 1: Serialization (Serialization assertion plan->header.magicTag == rt::kPLAN_MAGIC_TAG failed.)
Exception in thread Thread-1 (get_predictions):
Traceback (most recent call last):
  File "C:\Users\Felipe\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Felipe\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\PythonProjectsWindows\yolov8-object-detection\ObjectDetection.py", line 165, in get_predictions
    detection_output_list = model.predict(source=camera.get_latest_frame(),
  File "D:\PythonProjectsWindows\yolov8-object-detection\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\PythonProjectsWindows\yolov8-object-detection\venv\lib\site-packages\ultralytics\yolo\engine\model.py", line 224, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "D:\PythonProjectsWindows\yolov8-object-detection\venv\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 227, in setup_model
    self.model = AutoBackend(model,
  File "D:\PythonProjectsWindows\yolov8-object-detection\venv\lib\site-packages\ultralytics\nn\autobackend.py", line 162, in __init__
    context = model.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'


Once again, can you help me with this issue? 

Thank you.

**Comment by luizconrado** [comment]
@AyushExel,

At this point, I don't know if I am helping or not, however, one more piece of information.
I reinstalled TensorRT 8.5.3.1
But in my project, I installed only one thing that doesn't match my TensorRT 8.5.3.1.
I installed  tensorrt-8.6.0-cp310-none-win_amd64.whl
And now I get a different error, that in looking at older versions of YOLO, other people also had problems with.

So, this time I am using:
Python 3.10
ultralytics version 8.0.56
CUDA 11.7
CuDNN 8.8
TensorRT 8.5.3.1
* tensorrt-8.6.0-cp310-none-win_amd64.whl installed instead of the original tensorrt-8.5.3.1-cp310-none-win_amd64.whl


Here we go:
Traceback (most recent call last):
  File "D:\PythonProjectsWindows\yolov8-object-detection\ObjectDetection.py", line 235, in <module>
    update_screen()
  File "D:\PythonProjectsWindows\yolov8-object-detection\ObjectDetection.py", line 216, in update_screen
    for r in detection_output_list:
  File "D:\PythonProjectsWindows\yolov8-object-detection\venv\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "D:\PythonProjectsWindows\yolov8-object-detection\venv\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 153, in stream_inference
    self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
  File "D:\PythonProjectsWindows\yolov8-object-detection\venv\lib\site-packages\ultralytics\nn\autobackend.py", line 421, in warmup
    self.forward(im)  # warmup
  File "D:\PythonProjectsWindows\yolov8-object-detection\venv\lib\site-packages\ultralytics\nn\autobackend.py", line 329, in forward
    assert im.shape == s, f"input size {im.shape} {'>' if self.dynamic else 'not equal to'} max model size {s}"
AssertionError: input size torch.Size([1, 3, 640, 640]) not equal to max model size (1, 3, 1920, 1920)

Process finished with exit code 1

**Comment by AyushExel** [comment]
> 

1. yes we'd have to maintain 2 interfaces. But we already tool care of most things that can be done via torchhub. And there are many other enhancements like visualization etc. that model interface supports. Are there any specific features torch hub missing that you'd like to use?

Regarding your TRT error, I think there are several things that could go wrong. First, make sure you use the same version to export and run inference. Secondly, your final msg suggests you need to pass imgsz while exporting. But I'm not sure about things when it comes to exports. @glenn-jocher might be able to answer

**Comment by victorsoyvictor** [comment]
> 1. yes we'd have to maintain 2 interfaces. But we already tool care of most things that can be done via torchhub. And there are many other enhancements like visualization etc. that model interface supports. Are there any specific features torch hub missing that you'd like to use?
> 

Would be good if we could conduct Quantization using from PyTorch the pytorch_quatization quant_modules for applying PTQ technique.

**Comment by pderrenger** [comment]
@victorsoyvictor that's a great suggestion! Integrating the ability to conduct quantization using PyTorch's quantization modules for applying PTQ technique is definitely worth considering. I'll make sure to discuss this with the team for potential implementation in the future. Thank you for sharing your idea!
