### ISSUE TITLE
Training stuck at 0% forever without error

### ISSUE THREAD

**Issue by Apoptose93** [ultralytics/ultralytics#417]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I am trying to run the training using the coco128.yaml example. It runs but get stuck at 0% forever without any error. 
![SCR-20230116-lmd](https://user-images.githubusercontent.com/44260155/212703082-9ad939f6-e48a-4509-b536-a1656299c92f.png)

Tried it both with python and with the CLI directly, same result.

### Environment

Hardware: Macbook M1 Pro + Clean Docker (linux/amd64) Ubuntu with Python 3.8
Installed Ultralytics via pip
Got the coco128.yaml from the repo

### Minimal Reproducible Example

from ultralytics import YOLO

model = YOLO("yolov8n.pt")
results = model.train(data="coco128.yaml", epochs=3)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@Apoptose93 hi there! It looks like you're experiencing an issue with the YOLOv8 training process. When training gets stuck at 0% without any error, it could be due to a few different reasons. Here are a couple of things you can check:

1. **Data Path**: Ensure that the paths in your coco128.yaml file are correct and point to the actual location of your dataset.

2. **Dataset Content**: Make sure that your dataset contains valid data and annotations and that it's accessible from your current environment.

Feel free to double-check these points and if the issue persists, please let us know, and we'll be more than happy to assist further. Your feedback is valuable in improving the YOLOv8 experience for everyone. 😊
