### ISSUE TITLE
Issue changing cropped image format from default jpeg to desired png.

### ISSUE THREAD

**Issue by GruhitPadsala** [ultralytics/ultralytics#4188]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Working on a project where I am feeding a trained model .png images which should crop a train segment using object recognition in YoloV8. However ever after changing this in ultralytics\yolo\engine\results.py:

![image](https://github.com/ultralytics/ultralytics/assets/92880269/8f559795-1455-4e3b-ac70-b92f6a3db424)

The cropped image remains being saved as a jpeg.

**Comment by glenn-jocher** [comment]
@GruhitPadsala hello, thank you for reaching out and also for making sure to check previous discussions and issues before posting your question.

Regarding your issue on changing the output cropped image format from jpeg to png using YOLOv8, you are correct that you would need to change the code in the specific area you mentioned, namely 'ultralytics\yolo\engine\results.py.' 

However, simply changing the file extension in the code won't solve the problem because the library uses the OpenCV function `imwrite()`, and this function's default format is jpeg. As soon as it sees a `.jpg` or `.jpeg` extension, it will encode the image in JPEG format regardless of the original image format.

You would need to actually change the encoding of the saved image, not just the file extension. This would involve modifying the respective functions/classes in the YOLOv8 source code within the Ultralytics repository that deal with image saving to ensure that images are saved in PNG format instead of JPEG.

Please note that making such changes may impact how other modules in the repository function, so be careful to ensure compatibility.

If you have more questions or if anything wasn't clear, feel free to ask. The YOLO community and Ultralytics team are here to help!

**Comment by GruhitPadsala** [comment]
Hi, thank you for reaching back. I am having trouble narrowing down the source code you are mentioning. Would you happen to know which files deal with image saving?

Searching on the repo, I found this file that could possibly be one of the ones you mentioned. Could you confirm if this is such a file and if so where I could find it?
![image](https://github.com/ultralytics/ultralytics/assets/92880269/8ff4e90a-5aa1-456e-a0e9-bc5a52ef0799)

**Comment by glenn-jocher** [comment]
@GruhitPadsala hello! I appreciate your proactive approach in identifying potential source files. From your screenshot, it appears you have found one of the files involved with image saving. 

YOLOv8, similar to other YOLO models, performs image reading, processing, and eventually writing (saving) through several files distributed across the repository. The file you're looking at certainly plays a part in the image handling, and specifically in the context you're looking at, object detection's result presentation. 

To effectively alter image saving from JPEG to PNG, your examination should not be limited to a single source file. Multiple areas of the codebase perform image operations interdependently, and it's essential you identify and modify each instance appropriately.

As a starting point, scanning for usages of OpenCV's `imwrite()`, the function primarily responsible for image saving in this case, should point you in the right direction. There may be instances where the JPEG format is hardcoded, and these would need to be addressed.

If you have further questions or need additional clarification, don't hesitate to ask!

**Comment by GruhitPadsala** [comment]
Hi, thank you for your help. I was able to solve the issue by modifying a function that hard coded jpg in it. Once I changed it to png, it saved all my crops in the png format. If anyone encounters this issue i've included the function that needs to changed to control what format cropped images are saved in.

![image](https://github.com/ultralytics/ultralytics/assets/92880269/873b576a-bf78-4637-9a51-50217a870f7d)

**Comment by pderrenger** [comment]
That's fantastic to hear, @GruhitPadsala! I'm really glad you were able to resolve the issue by modifying the specific function. It's great of you to share the details for anyone else who might come across a similar issue in the future. Your contribution to the community is greatly appreciated.

If you have any more questions or need further assistance with YOLOv8 or any other topic, please feel free to ask. The Ultralytics team and YOLO community are here to help!
