### ISSUE TITLE
Custom model(best.pt) is not working when I used instead of yolov8l.pt

### ISSUE THREAD

**Issue by ImranAhsan15** [ultralytics/ultralytics#4191]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

Error executing job with overrides: ['model=best.pt', 'conf=0.25', 'source=My Video.mp4', 'show=True']
Traceback (most recent call last):
  File "D:\Tracker_yolov8_2\YOLOv8-DeepSORT-Object-Tracking\ultralytics\yolo\v8\detect\predict.py", line 317, in predict
    predictor()
  File "D:\Tracker_yolov8_2\YOLOv8-DeepSORT-Object-Tracking\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "d:\tracker_yolov8_2\yolov8-deepsort-object-tracking\ultralytics\yolo\engine\predictor.py", line 164, in __call__
    model = self.model if self.done_setup else self.setup(source, model)
  File "d:\tracker_yolov8_2\yolov8-deepsort-object-tracking\ultralytics\yolo\engine\predictor.py", line 121, in setup
    model = AutoBackend(model, device=device, dnn=self.args.dnn, fp16=self.args.half)
  File "d:\tracker_yolov8_2\yolov8-deepsort-object-tracking\ultralytics\nn\autobackend.py", line 73, in __init__
    model = attempt_load_weights(weights if isinstance(weights, list) else w,
  File "d:\tracker_yolov8_2\yolov8-deepsort-object-tracking\ultralytics\nn\tasks.py", line 303, in attempt_load_weights
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "D:\Tracker_yolov8_2\YOLOv8-DeepSORT-Object-Tracking\venv\lib\site-packages\torch\serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "D:\Tracker_yolov8_2\YOLOv8-DeepSORT-Object-Tracking\venv\lib\site-packages\torch\serialization.py", line 1172, in _load
    result = unpickler.load()
  File "D:\Tracker_yolov8_2\YOLOv8-DeepSORT-Object-Tracking\venv\lib\site-packages\torch\serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'IterableSimpleNamespace' on <module 'ultralytics.yolo.utils' from 'd:\\tracker_yolov8_2\\yolov8-deepsort-object-tracking\\ultralytics\\yolo\\utils\\__init__.py'>

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

### Environment

Ultralytics YOLOv8.0.3  Python-3.9.11 torch-2.0.1+cpu CPU

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ImranAhsan15 i'm sorry to hear that you're having trouble with loading your custom model. The error message seems to indicate a problem with loading the checkpoint from your best.pt file.

The 'IterableSimpleNamespace' attribute error could suggest that the environment you've trained your model in is not aligned with the environment you are using for prediction. If there are discrepancies in the versions of certain libraries or frameworks between these two environments, it could lead to this kind of error.

Here are a few things you could check:

1. **Environment Consistency**: Ensure that you're using the exact same environment for both training and testing. This includes the same Python, torch, and other library versions. If there are some differences, try to create an environment that matches the one used during training.

2. **Weights File**: Check if your custom weights file (best.pt) is not corrupted or incomplete. Try to load the weights file in a simple script to see if they can be loaded successfully.

3. **Model Compatibility**: Double check if your custom model is compatible with the YOLOv8 version you are using for detection. There might be changes in the codebase which can make older versions of trained models incompatible.

By carefully exploring these possibilities, you should be able to find what's causing the issue. Please let us know how it goes and don't hesitate to reach out if you have more problems!

**Comment by glenn-jocher** [comment]
@ImranAhsan15 i'm sorry to hear that you're having trouble with loading your custom model. The error message seems to indicate a problem with loading the checkpoint from your best.pt file.

This is because your version of `ultralytics` is very old, 8.0.3. You should update to the very latest version using `pip install -U ultralytics` which will resolve this error for you.

**Comment by ImranAhsan15** [comment]
if i use latest ultralytics version i got an error. My script is in bellow

from ultralytics.yolo.utils import DEFAULT_CONFIG, ROOT, ops
.
.
.
@hydra.main(version_base=None, config_path=str(DEFAULT_CONFIG.parent), config_name=DEFAULT_CONFIG.name)


for those two line i have to use ultralytics 8.0.3. If i use latest version there is a error for those line i wrote.

**Comment by glenn-jocher** [comment]
It appears that you are encountering issues due to changes in the package structure and API of ultralytics between the version you are using (8.0.3) and the latest version. The functions and constants you are using might have been renamed, moved, or even removed in the more recent versions of ultralytics. Here's how you might resolve this issue:

Since the error message is telling us that it can't get the attribute 'IterableSimpleNamespace', it seems like this attribute has either been removed, renamed or its access has been changed in the later versions. I recommend checking the latest documentation or the source code of the ultralytics package to see these changes and adjust your code accordingly.

The `config_path` and `config_name` arguments you pass to ` @ImranAhsan15.main` likely need to be updated too. In the newer versions of ultralytics, the configurations have been encapsulated into separate classes for modularity and to avoid conflicts. You should follow the API of these new classes to correctly pass your configurations. 

I understand that updating existing code to comply with changes in newer versions of a package can be a bit difficult and time-consuming. However, the benefits generally outweigh the inconveniences and would help you resolve the error you're encountering as well as provide newer features and improvements. Good luck!
