### ISSUE TITLE
Support for Objects with Disjoint Regions in YOLOv8

### ISSUE THREAD

**Issue by ROS2018** [ultralytics/ultralytics#4197]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hello YOLO maintainers and community,

I've been leveraging YOLOv8 for instance segmentation tasks and have been consistently impressed by its performance compared to other architectures. However, I've encountered a challenge with my specific dataset.

**Issue Description:**
My dataset contains objects represented by multi-path polygons with disjoint regions. However, the annotation format for YOLO mandates a single flat polygon per class, which isn't suitable for my dataset.

As a workaround, I treated each disjoint region of the same class as a separate instance. Despite training on over 5,000 images, this method hasn't yielded satisfactory results. The output polygons from YOLOv8 are noisy, likely because the shape of the individual disjoint regions lacks context without its complementary regions.

**Possible Solutions:**

Input Complete Objects: Provide YOLOv8 with the entire object, encompassing all its disjoint regions. Unfortunately, this doesn't seem to be supported currently.
Use Semantic Segmentation: Another potential solution could be using semantic segmentation. But, as I understand, this isn't supported by YOLOv8 either.
While architectures like MaskRCNN (for the complete object input) and U-Net (for semantic segmentation) are options, I have a strong preference to continue using YOLOv8 due to its superior performance in my previous tasks of instance segmentation.

**Request:**
If there's a way to accommodate objects with multiple disjoint regions in YOLOv8, or if there are recommended practices for such scenarios, I would deeply appreciate guidance.

Thank you for your time and the incredible work on YOLO!

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ROS2018 hello,

Thank you for using YOLOv8 and providing a comprehensive description of the problem you're facing. Your feedback and insights help drive improvements for this repository.

Models like YOLO are traditionally used for object detection tasks that associate a single bounding box per object. While some transformations have been done to allow YOLOv8 to perform instance segmentation tasks, it indeed does not have built-in support for objects represented by multi-path polygons with disjoint regions. Your feedback is very much aligned with our understanding of its present capabilities.

The workaround you developed of treating each disjoint region of the same class as a separate instance may work on some datasets, but as you pointed out, this approach may not yield satisfactory results in all scenarios due to the loss of overall context about the object.

To accommodate the handling of multi-path polygons with disjoint regions in deep learning models, changes both in the training procedure and the model architecture would likely be required. However, since it requires extensive modification to the base YOLOv8 model and the associated training pipeline, it is currently not available.

I appreciate your willingness to contribute a PR to our repo. We are fairly confident that this feature will significantly increase the versatility, usability, and performance of YOLOv8. If you or anyone else in our community is interested in diving into this challenging but highly beneficial problem, we would be happy to provide direction and support for such an endeavor.

In the meantime, if there are other questions, issues, or ideas, please feel free to raise them.

Thanks again for your support and engagement with YOLOv8!
