### ISSUE TITLE
clarification of the visibility of keypoints 

### ISSUE THREAD

**Issue by pt127** [ultralytics/ultralytics#4199]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i have read through a lot of questions and answers regarding the visibility value of the keypoints and i am still not quite sure how exactly this value is used so here are a few questions to help clear it up.
Maybe a helpful info: 
My dataset is based on synthetic data so i can also read the exact coordinates of hidden keypoints.

**1. Question:**
if you choose dim=3 in the .txt file, does the visibility value only take the values 0 (not visible) and 1 (visible) or 0 (not visible) 1 (partially visible) and 2 (visible)?
As I understood it, 0 means invisible and everything above zero is treated equaly as visible.

**2.Question:**
If the visibility value is set to 0, does it matter what the x and y values for this keypoint are or are these keypoints completle ignored during training? does it make a difference if I add the actual coordinates of the invisible point or just zero the x and y value? 

**3.Question**:
if i annotate hidden keypoints with visibility 1 and the associated x and y coordinates, will the model be confused during training or learn where these hidden keypoints should theoretically be located?
Example: I have a cube where each of the 8 corners is a keypoint. Will the model then learn to predict where the hidden (back) corners should theoretically be on the 2d image (when visibility is set as 1)?

What happens if I write the hidden keypoints with visibility 0 and enter the corresponding x and y coordinates?  Will the model then learn which keypoints are visible and invisible and additionally predict where the invisible keypoints should be? Will it show me these keypoints during the predict mode ? 

I would be very happy about a detailed breakdown of how this invisibility value affects the training and the prediction.
Thanks

**Comment by glenn-jocher** [comment]
@pt127 hello,

Thank you for reaching out and keenly studying how the visibility values of keypoints function within the scope of YOLOv8. Now, let me help clear up your questions.

1. The visibility value usually ranges with dim=3 in your .txt file, taking the values 0 for "not visible," 1 for "partially visible" and 2 for "visible". Due to the nature of your synthetic data, the value 0 indeed stands for invisible, and any value above 0 is treated equally as visible.

2. In YOLOv8, if you specify the visibility value as 0 (which means "not visible"), the x and y values are not necessarily incorporated into the model’s understanding during training. In other words, whether you set the coordinates of these invisible points or zero them out, it might not materially affect the model training. The keypoints with visibility 0 do not contribute information to the training process.

3. For your final question, the model won’t be confused if you annotate hidden keypoints with visibility 1 (visible) and qualify these with their respective x and y coordinates. Instead, the model will 'learn' where these keypoints, even if normally hidden, could conceivably be located. If you have a cube with each of the 8 corners as a keypoint, the model will effectively be able to predict where these hidden keypoints should ideally be located in a 2D image form. Similarly, if you record these keypoints as invisible (visibility 0) and input the corresponding x and y coordinates, the model will possibly learn which keypoints are visible or invisible and, in addition, predict the presumed location of these invisible keypoints. But, the keypoints with visibility 0 won't be shown in the predict mode, as the model considers them as 'not contributing' due to their visibility value.

The visibility value plays a role in both the training and prediction stages. During training, it helps the model understand the concepts of visibility, location, and the relation between different keypoints. During prediction, it's used to show keypoints that are predicted to be visible over a certain threshold. 

Keep in mind, these keypoints are still part physics, part statistical inference. It's not perfect, but it's the best method we have to infer these invisible points. Please don’t hesitate to reach out if you have further concerns. 

Best Regards,
Ultralytics Team

**Comment by PallottaEnrico** [comment]
@glenn-jocher @pt127, I'm still not totally sure about how this works.
Using the notation 0,1,2 in the labels, is useful to specify (using 1) also keypoints that are in the scene but covered by something in the image. At prediction step the model predicts only 0,1 , without making any distinction between partial and full visibility.
Wouldn't it be better to predict 0,1,2 given that the labels are in that format?

**Comment by glenn-jocher** [comment]
@PallottaEnrico hello, thank you for your question about the keypoint visibility prediction in YOLOv8.

The YOLOv8 model predicts keypoint visibility on a scale from 0 to 1 where 0 denotes 'not visible' and anything above 0 indicates 'visible'. This is a simplified approach, which works well for many applications.

The idea of including a third category for partial visibility is an interesting one. However, it could introduce complexity and potential ambiguity into the model's predictions. For instance, defining what constitutes 'partial visibility' might differ between scenes and objects, and it could confuse the model.

In saying that, the goals of machine learning models often differ and it certainly is possible to modify YOLOv8 to predict visibility labels in the format 0, 1, 2 (for 'not visible', 'partially visible', and 'fully visible', respectively) if you find this would provide more valuable insight for your specific application.

Please, let us know if you have any other questions!
