### ISSUE TITLE
How to do Custom Augmentation on YOLOv8

### ISSUE THREAD

**Issue by AndywithCV** [ultralytics/ultralytics#4202]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello team, I am trying to add some augmentation techniques and also  make some changes to the defaults of Yolov8, Please help to specify how I can do and from Which file and its location so that I can do the editing, I cannot find the augment.py or config.yaml of it, any suggestion how to do it? thanks so much!!!

**Comment by Soichi9** [comment]
@AndywithCV  I am learning through CLI, and I can overwrite the settings by doing the following:
`yolo detect train model=yolov8n.pt data=dataset.yaml device=0 epochs=400 batch=8 imgsz=1280 degrees=360 fliplr=0.0 mixup=0.15 scale=0.9 `

However, I'm not sure where the original settings are located or how to configure them all at once.

**Comment by AndywithCV** [comment]
> 

If you are using Python there is a file named: default.yaml from Ultralytics/cfg/ . in this file, all the hyperparameters are mentioned with specific values, but i am not sure if its the right file to do the editing on or not..

**Comment by glenn-jocher** [comment]
@AndywithCV hi there,

You're on the right track! The `default.yaml` file in the `Ultralytics/cfg/` directory does indeed contain various default configurations for the YOLOv8 model, including hyperparameters used in the training process.

If you want to customize these settings, the best way to go about it is to create a new configuration file based on this `default.yaml` and apply your changes there. Once you've created your custom config file, you can pass its path to the model during training or validation to apply your custom settings. This way, the default settings will remain intact and you can always reference them if necessary.

Please remember to keep a copy of the original `default.yaml` file before making any changes, since it can be useful to have a fallback reference of the original settings. 

I hope this helps clarify things for you, and let us know if you have any other questions.

**Comment by Tsai-Ting** [comment]
@Soichi9 Hello! I want to know can it overwrite through python?  I write it in custom.yaml, but it cannot overwrite through python, is there any other ways? Thank you!

**Comment by glenn-jocher** [comment]
Hello @Tsai-Ting,

Yes, you can overwrite the configurations through Python. You need to load your custom configuration file when you are initializing your YOLOv8 model for training or inference. This ensures that the model will use your custom settings instead of the default ones.

Remember, you should specify the path to your `custom.yaml` file in your Python script where you instantiate the model.

Thank you for reaching out with your question! Let us know if there's anything else you need help with. Happy coding!
