### ISSUE TITLE
Error training yolov8 for segmentation on a new custom model Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"

### ISSUE THREAD

**Issue by abiraaaaaaf** [ultralytics/ultralytics#4209]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am training yolov8 for segmnentation with this command:

```
!yolo task=segment mode=train model=yolov8m-seg.pt data={HOME}/new_data/data.yaml epochs=500 imgsz=640 batch=8 workers=2
```

and this is how the label txt files look like:
32 0.03567479464644724 0.03869047619047619 0.04130750547359965 0.9375 1.0 0.9315476190476188 0.9857524195589085 0.004464285714285714

We have 33 classes of objects.

But this error raises:

ultralytics/utils/tal.py", line 152, in get_box_metrics
    bbox_scores[mask_gt] = pd_scores[ind[0], :, ind[1]][mask_gt]  # b, max_num_obj, h*w
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

I checked the annotations but still no answer for this error!

These are the efforts that I made:

1) Checking the size of the dataset

2) Finding files with invalid bounding boxes

3) Checking missing files

4) Verifying the images

5) Verifying the labels

6) Verifying the 33 classes

7) Checking the labels for any inconsistency such as being out of bounds and not being normalised, negative labels, duplicate labels, ...

The results didn't show any reason why this is happening.

**Comment by xinsuinizhuan** [comment]
the same error,how to resolve it?

**Comment by MarcoParola** [comment]
I have the same problem, but related to an object detection task!

**Comment by glenn-jocher** [comment]
@MarcoParola apologies for the trouble you're experiencing. There are a few possibilities that might be causing this issue. Usually, the "index out of bounds" error indicates an issue with your annotations.

First, confirm that all class indices in your dataset labels are within the range [0, num_classes-1]. For example, if you have two classes, the indices in your label files should only be 0 or 1. Note that the class indices are zero-based.

Second, this error could also be due to empty or improperly formatted label files, so it's worthwhile to check if all your label files have the correct format and that none are empty.

Lastly, ensure that the bounding box coordinates in your label files are normalized and between [0, 1]. If any of these values exceed this range, you might encounter this error.

By thoroughly checking these areas, you should be able to identify and fix the irregularities causing this issue. Remember to triage your dataset carefully for any inconsistencies before training. Happy training!
