### ISSUE TITLE
How to stop a stream generator?

### ISSUE THREAD

**Issue by gustavosett** [ultralytics/ultralytics#4246]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm using yolov8 in my fastapi app and this is my generator but **I want to stop and release resources** like opencv cap. I try using break and overwriting my model, but **my webcam keeps on**.

```
results = self._detection_worker._model(
    self._camera_url, 
    stream=True, 
    verbose=False, 
    conf=self._conf, 
    imgsz=(640, 480)
)

for r in results:
    if not self._running:
        break # here i want to stop generator
    self.frame = self._detection_worker.run_inference([r,]) 
    self.send_frame_signal()
```

**Comment by glenn-jocher** [comment]
@gustavosett to control the release of resources such as the webcam when using a generator along with opencv, you have to ensure that any open resources are closed properly when the generator function is expected to stop.

In your code, breaking from the for loop won't necessarily stop the generator itself. The generator keeps the state saved and can continue from where it left off. Therefore, it might not be releasing the webcam resource.

You could approach this by structuring your code so that when your condition `if not self._running` is met the code then appropriately releases these resources, such as the opencv video capture object. This is often accomplished by calling the `release()` method on the capture object.

Also, it would be essential to ensure `self._detection_worker._model` has a mechanism to stop the video capture when the streaming is supposed to stop. It means checking the condition `self._running` within this method and releasing resources accordingly.

By ensuring these changes you should be able to control the release of your webcam resource and stop the stream when required.

**Comment by glenn-jocher** [comment]
@gustavosett hi! Thanks for your kind words and for further explaining your issue. To ensure that resources, such as the webcam in this case, are correctly released it's crucial to handle these resources properly within the generator function itself. In your current implementation, `model.predict`, it appears the webcam resource is not being released.

Normally, in OpenCV, a video capture object is released by calling the `release()` method on the object. It would be helpful to check that when the condition `cont == 30` is met, the video capture object within your prediction model does indeed call this method to release the resource used by the webcam. In general, these resources should not be kept "open" or "in-use" when they're not needed, so include a mechanism in your model to ensure they are released as soon as they are out of scope.

You may also need to handle situations where the camera connection problem occurs. You can add exception handling in your generator to catch these connection error exceptions and appropriately release the camera resources. This should prevent your API from needing a complete restart whenever such problems occur.

By doing these adjustments, the webcam should be properly released and any associated resources should be freed when you stop the generator or when an error happens, and you should be able to continue using the webcam without needing a full restart.
