### ISSUE TITLE
TFLite inference output data

### ISSUE THREAD

**Issue by tekeburak** [ultralytics/ultralytics#4266]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have trained a custom model based on YOLOv8n and converted the model to TFlite format. The model has 277 classes.
When converting it to TFLite format, there is a prompt as below that states the PyTorch output shape is (1, 281, 8400).

`PyTorch: starting from /mnt/models/checkpoint/yolov8n/weights/best.pt with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 281, 8400) (11.8 MB)`

After converting the model to TFLite successfully, I tried to inference in Python.

```python
import numpy as np
import tensorflow as tf

model_tflite_path = "yolov8n_saved_model/yolov8n_float16.tflite"
interpreter = tf.lite.Interpreter(model_path=model_tflite_path)
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

image_height = input_details[0]['shape'][1]
image_width = input_details[0]['shape'][2]

image = Image.open("bus.jpg")
image = np.array(image)
image = tf.image.resize(image, (image_height, image_width))
image = np.true_divide(image, 255, dtype=np.float32)
image = image[np.newaxis, :]

interpreter.set_tensor(input_details[0]['index'], image)
interpreter.invoke()
output = interpreter.get_tensor(output_details[0]['index'])
output = output[0]
output = output.T  # output shape:(8400, 281)

boxes_xywh = output[..., :4]
scores = output[..., 4:5]
classes = np.argmax(output[..., 5:], axis=1)
```
 I  accessed boxes, scores, and classes from the output as above. When I print the boxes, I get values as follows. When I converted this to xyxy format I got negative values. Should the inference be like this?
```python
boxes_xywh[0]
array([ 4.6445484,  9.341339 ,  9.620625 , 19.071648 ], dtype=float32)
boxes_xywh[1]
array([18.152359,  7.181611, 37.040367, 14.4251  ], dtype=float32)
boxes_xywh[2]
array([27.377392,  6.584148, 55.739616, 13.227586], dtype=float32)
boxes_xywh[3]
array([39.59924  ,  7.0861373, 81.04723  , 14.223611 ], dtype=float32)
boxes_xywh[4]
array([45.41194  ,  6.6917486, 94.22308  , 13.535082 ], dtype=float32)
```

**Comment by shashichilappagari** [comment]
@tekeburak There are a couple of things that might be wrong in your code.
1. There is no non-max suppression performed on the boxes
2. YOLOv8 does not have objectenss score like YOLOv5: so you should not separate scores and classes. Notice that output has 281=277+4 where 277 is number of classes and 4 is for bbox coordinates. 
3. Most importantly, you should rescale the boxes with respect to the original image since the bbox coordinates returned by model are with respect to the input size for the model.

Hope this helps.

**Comment by glenn-jocher** [comment]
Hello @tekeburak,

Firstly, congratulations on successfully training and converting your custom model. Now to address your concerns:

1. By looking at your code, it seems like you’re not performing non-maximum suppression on the output bounding boxes. It's a crucial step in order to eliminate multiple detections of the same object in the image.

2. YOLOv8 output does not contain a separate objectness score or confidence score per bounding box like in some other YOLO versions. Therefore, when you separate the first 4 columns for boxes, the reminder includes both the class scores and the class predictions. Specifically, from the tensor with shape `(8400, 281)`, the part from index 4 up to 281 are the class scores. Hence, you may not need to separately compute the scores as you've done in your code.

3. The most crucial point here is about the bounding box coordinates. The model provides the coordinates with respect to the size of the input image provided to the model. Therefore, you'll need to accordingly rescale these bounding box coordinates back to the original image size for proper comparison and display.

I hope these points help. You're on the right track, and with these modifications, you should be able to extract the desired output. If you encounter any more issues, feel free to post here. We're more than happy to assist.

**Comment by tekeburak** [comment]
Thank you for your answers @shashichilappagari @glenn-jocher.

1. NMS post-processing is hardcoded in the YOLOv8 predictor. Is there any option to export the model as TFLite+NMS or TFLite+agnosticNMS during the conversion?

```python
# Export the model
model.export(format='tflite')
```

2. I've examined the model in detail. Since YOLOv8 is using Decoupled Head, it does not contain a confidence or objectness score.
![image](https://github.com/ultralytics/ultralytics/assets/13269334/d4f3ebc9-b8c0-4d03-995c-c82cc51e95c3)
In other PyTorch or TensorFlow object detection models, I was calculating the confidence score threshold that maximizes the F1 score and using the model with this confidence score in production. In the YOLOv8 model trained on custom data, do you guarantee that the model will run in a way that maximizes the F1 score in the default behavior?
In addition, how do I know if one of the bounding boxes predicted by the model is predicted with a higher or lower probability than the other?

3. Even if I rescale these bounding boxes, if you examine the values I shared before in detail. When I convert to xyxy format, some boxes return negative values. As far as I know, I should not see negative values. Why is this happening?

```python
# Convert nx4 boxes from [x, y, w, h] to rescaled [x1, y1, x2, y2] where xy1=top-left, xy2=bottom-right
x, y, w, h = boxes_xywh[..., 0], boxes_xywh[..., 1], boxes_xywh[..., 2], boxes_xywh[..., 3] #xywh
boxes_xyxy = [x - w / 2 / image_width,
              y - h / 2 / image_height,
              x + w / 2 / image_width,
              y + h / 2 / image_height]  # xywh to rescaled xyxy
```

I would be appreciate if you could answer not only as a text, but also as a link to the relevant parts of the repo or share code snippet.

**Comment by shashichilappagari** [comment]
@tekeburak We made a repo to run exported models with NMS included: https://github.com/DeGirum/yolo_inference
You can try running your model using the example code there. Regarding bounding boxes, it is hard to say: we generally look at the boxes that survive nms operation and clip the coordinates.

**Comment by tekeburak** [comment]
Thank you @shashichilappagari. @glenn-jocher you mentioned the score output for TFLite on another issue. I'm a bit confused actually. https://github.com/ultralytics/ultralytics/issues/4195#issuecomment-1667067020

**Comment by glenn-jocher** [comment]
Hi @tekeburak,

1. Currently, there's no built-in option to add NMS or agnosticNMS during the TFLite conversion. You have to follow manual post-processing after the model inference to perform the NMS.

2. Since YOLOv8 uses a Decoupled Head, indeed, it does not include a distinct objectness score. Instead, each class will have a separate score, which can also be interpreted as the confidence of the model's prediction. The confidence score that provides the maximum F1-score is not explicitly computed, rather, the model output is optimized for overall detection performance. One way to understand the confidence of various bounding boxes is to look at the maximum class score for each box, which can give you a notion of how certain the model is about its prediction.

3. Concerning the negative values after conversion to `xyxy` format, the negative coordinates might occur due to the center coordinates (x, y) of the box being very close to the image boundaries, and the width/height of the bounding box being larger. You can resolve this by clipping the coordinates to the image dimensions after the conversion to `xyxy` format. Clipping will ensure that all the pixels of the bounding boxes lie within the actual image, preventing any negative or out-of-bound coordinates.

Please give these suggestions a try and let us know if you stumble upon any more obstacles; we're more than happy to help further.
