### ISSUE TITLE
Convert to tensorrt --> accuracy drops!

### ISSUE THREAD

**Issue by maheeetaaa** [ultralytics/ultralytics#4268]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have been working with yolov8 obj detection and also classification. I have converted both models to tensorrt via onnx conversion, and also to edge-tpu with export script directly. 

What I have seen is that with the quantization, to tensrrt we have a significant drop in the detections, even in some instances the bounding boxes fail. I am attaching images for you to see. threshhols are equal to 0.4.

original pytorch results
![testpic](https://github.com/ultralytics/ultralytics/assets/66379850/ab921ad7-8236-4f6a-98a1-7370f3683001)

tensorrt results
![object_detection](https://github.com/ultralytics/ultralytics/assets/66379850/66dc94ec-9a6e-42e8-8120-2f87fdaca411)

The same thing happens to edgtpu conversion, but I think that is possible since i also quntize it to int8. TensorRT though surprises me, we did not have such significant drp in the accuracy of model with yolov5, did we? please advise!

**Comment by glenn-jocher** [comment]
@maheeetaaa hello,

Thank you for reaching out and providing detailed information about your issue. Your observation is accurate. When exporting models to formats like TensorRT, there can indeed sometimes be a reduction in accuracy. This is especially true with certain types of model transformation like quantization which is used in edge-tpu conversions, and can lead to a drop in performance. 

Regarding the drop in accuracy when using TensorRT, it would be important to consider the precision option you used during conversion in your ONNX to TensorRT process. Using a lower precision like `FP16` or `INT8` can result in some differences in inference results compared to the original PyTorch model due to lower floating point precision, leading to performance trade-offs.

However, it does seem quite unusual for the drop in detections to be as significant as illustrated in your provided images. A further investigation might be needed. I recommend examining your TensorRT conversion and inference code to ensure optimal settings are being applied. Check the use of correct parameters and the correct implementation of optimization profiles if you are using dynamic shape inputs. 

Remember, comparing model performance between different YOLO versions like YOLOv5 and YOLOv8 directly might not be entirely fair due to the inherent differences in their architectures, which can affect their robustness to precision changes during conversion.

Please continue to share any additional observations or issues you encounter, and we'll do our best to assist. Your contribution is valuable to improving YOLOv8 and the entire community.

**Comment by maheeetaaa** [comment]
@glenn-jocher   thank you for the response. so I just tested the onnx model and here is the results, here the threshhold is lower, to compare I also upload the initial results 
.pt results
![testpic (1)](https://github.com/ultralytics/ultralytics/assets/66379850/78fd5f24-f79e-498e-8139-8098e4ffd129)
.onnx
![image](https://github.com/ultralytics/ultralytics/assets/66379850/6772db6f-8ad3-4d81-8390-25ca4884333a)

**Comment by glenn-jocher** [comment]
@maheeetaaa thanks for the follow-up, and for providing the results of your .onnx model.

As for your updated results, variations between the .pt model and the .onnx can indeed occur, especially if there are changes in the threshold value. As you have lowered the threshold for the .onnx results, it could lead to more probabilities being accepted as predictions, hence more bounding boxes might be visible. 

In performing a transformation to ONNX, it is also crucial that we ensure that the model's operational semantics are preserved, as ONNX transformations occasionally involve certain approximations that may impact the output. It is also worth confirming that the pre-processing and post-processing steps applied to your images remained consistent across your .pt and .onnx trials.

Remember that each model export format (like ONNX or TensorRT) can have idiosyncrasies in handling operations, approximations, and accuracy, which might impact performance when shifting from one format to another.

Please continue to keep us updated on your progress and don't hesitate to share if you run into further issues or interesting findings. Your contributions help make YOLOv8 better for the whole community.

**Comment by maheeetaaa** [comment]
@glenn-jocher thank you so much for the response, it helps a lot! 
Actually, this is where I am confused , because I do not change anything, I will now share how I convert the models so that we can investigate this issue: 

I have done all the traning in colab, what I do for conversion is simple 

`from ultralytics import YOLO
model = YOLO('/content/googledrive/MyDrive/yolov8/train3/weights/best.pt')  # load a custom trained
# Export the model
model.export(format='onnx', imgsz =[640,640], simplify=True ,opset=12)`
