### ISSUE TITLE
RuntimeError: operation does not have an identity

### ISSUE THREAD

**Issue by deep-zhang** [ultralytics/ultralytics#427]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Validation, Detection

### Bug

Error executing job with overrides: []
Traceback (most recent call last):
  File "predict.py", line 116, in predict
    predictor.predict_cli()
  File "/backup/shuyan/PROJECT/ultralytics/ultralytics/yolo/engine/predictor.py", line 220, in predict_cli
    for _ in (self.__call__(source, model, return_outputs)):
  File "/data/mahuichao/anaconda3/envs/torch1.7/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 37, in generator_context
    x = next(gen)
  File "/backup/shuyan/PROJECT/ultralytics/ultralytics/yolo/engine/predictor.py", line 184, in __call__
    preds = self.postprocess(preds, im, im0s)
  File "predict.py", line 25, in postprocess
    nm=32)
  File "/backup/shuyan/PROJECT/ultralytics/ultralytics/yolo/utils/ops.py", line 153, in non_max_suppression
    xc = prediction[:, 4:mi].amax(1) > conf_thres  # candidates
RuntimeError: operation does not have an identity

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@deep-zhang 👋 hi, thanks for letting us know about this possible problem with YOLOv5 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv5 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃
