### ISSUE TITLE
Results.tojson returns wrong data when tracking

### ISSUE THREAD

**Issue by simlevesque** [ultralytics/ultralytics#4271]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

The code for Results.tojson works for predictions but the tracking data row contains a new value on the fifth position (row[4]) which is the id. This results in output such as:

```
  {
    "name": "person",
    "class": 0,
    "confidence": 295.0,
    "box": {
      "x1": 1003.8906860351562,
      "y1": 93.98287200927734,
      "x2": 1060.8193359375,
      "y2": 249.63829040527344
    }
  }
```

The confidence returned is actually the tracking id and the class only returns 0 because it's casting the confidence (0...0.999) to int, which always returns 0.

PR: #4270

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@simlevesque hello, 

Thank you for catching this issue and also for your initiative indicated by the willingness to submit a PR! It's indeed active members like you that keep the YOLO community vibrant and progressive.

As you've observed, the `Results.tojson` method doesn't handle tracking data correctly due to the additional element - the tracking ID - added to the detection result array. In the case of tracking, the output is designed to be (x1, y1, x2, y2, id, class, confidence) compared to (x1, y1, x2, y2, class, confidence) for object detection tasks.

Therefore, when trying to parse tracking data, `Results.tojson` does misinterpret the tracking ID as the class score, which is why you are seeing zeros for class scores and inflated values for confidence.

Your PR can address this issue by adding a conditional clause in the `Results.tojson` method to handle the tracking scenario differently from the regular detection scenario. This clause will consider the 5th position value as the tracking id, and adjust the indices with which it retrieves the class and confidence information.

We appreciate your effort and initiative in improving YOLOv8. Once you submit the PR, we'll be glad to review and provide any necessary feedback. 

Keep making YOLOv8 better! 

Best,
Glenn Jocher.
