### ISSUE TITLE
Error loading best weights after training.

### ISSUE THREAD

**Issue by protei300** [ultralytics/ultralytics#4280]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

AttributeError                            Traceback (most recent call last)
Cell In [24], line 1
----> 1 model.train(
      2 #     cfg=DEPLOY_DIR.joinpath('config.yaml'),
      3     data=DEPLOY_DIR.joinpath('dataset_passports.yaml').as_posix(),
      4     project=DEPLOY_DIR.joinpath('yolov8s').as_posix(),
      5     epochs=1,
      6     batch=25,
      7     workers=0,
      8     fliplr = 0.0,
      9     scale = 0.5,
     10     degrees = 8,
     11     patience=0,
     12 )

File /usr/local/lib/python3.8/dist-packages/ultralytics/engine/model.py:377, in Model.train(self, trainer, **kwargs)
    375     self.model = self.trainer.model
    376 self.trainer.hub_session = self.session  # attach optional HUB session
--> 377 self.trainer.train()
    378 # Update model and cfg after training
    379 if RANK in (-1, 0):

File /usr/local/lib/python3.8/dist-packages/ultralytics/engine/trainer.py:192, in BaseTrainer.train(self)
    190         ddp_cleanup(self, str(file))
    191 else:
--> 192     self._do_train(world_size)

File /usr/local/lib/python3.8/dist-packages/ultralytics/engine/trainer.py:400, in BaseTrainer._do_train(self, world_size)
    396 if RANK in (-1, 0):
    397     # Do final val with best.pt
    398     LOGGER.info(f'\n{epoch - self.start_epoch + 1} epochs completed in '
    399                 f'{(time.time() - self.train_time_start) / 3600:.3f} hours.')
--> 400     self.final_eval()
    401     if self.args.plots:
    402         self.plot_metrics()

File /usr/local/lib/python3.8/dist-packages/ultralytics/engine/trainer.py:552, in BaseTrainer.final_eval(self)
    550 for f in self.last, self.best:
    551     if f.exists():
--> 552         strip_optimizer(f)  # strip optimizers
    553         if f is self.best:
    554             LOGGER.info(f'\nValidating {f}...')

File /usr/local/lib/python3.8/dist-packages/ultralytics/utils/torch_utils.py:403, in strip_optimizer(f, s)
    400 except ImportError:
    401     import pickle
--> 403 x = torch.load(f, map_location=torch.device('cpu'))
    404 if 'model' not in x:
    405     LOGGER.info(f'Skipping {f}, not a valid Ultralytics model.')

File /usr/local/lib/python3.8/dist-packages/torch/serialization.py:809, in load(f, map_location, pickle_module, weights_only, **pickle_load_args)
    807             except RuntimeError as e:
    808                 raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
--> 809         return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
    810 if weights_only:
    811     try:

File /usr/local/lib/python3.8/dist-packages/torch/serialization.py:1172, in _load(zip_file, map_location, pickle_module, pickle_file, **pickle_load_args)
   1170 unpickler = UnpicklerWrapper(data_file, **pickle_load_args)
   1171 unpickler.persistent_load = persistent_load
-> 1172 result = unpickler.load()
   1174 torch._utils._validate_loaded_sparse_tensors()
   1176 return result

File /usr/local/lib/python3.8/dist-packages/torch/serialization.py:1165, in _load.<locals>.UnpicklerWrapper.find_class(self, mod_name, name)
   1163         pass
   1164 mod_name = load_module_mapping.get(mod_name, mod_name)
-> 1165 return super().find_class(mod_name, name)

AttributeError: Can't get attribute 'NoneType' on <module 'builtins' (built-in)>

### Environment

- Ultralytics YOLOv8.0.151 🚀 Python-3.8.10 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3070 Ti, 7982MiB)
- Ubuntu 20.04.5 LTS

### Minimal Reproducible Example

model.train(
    data=DEPLOY_DIR.joinpath('dataset.yaml').as_posix(),
    project=DEPLOY_DIR.joinpath('yolov8s').as_posix(),
    epochs=1,
    batch=25,
    workers=0,
    fliplr = 0.0,
    scale = 0.5,
    degrees = 8,
    patience=0,
)

### Additional

This error started from ultralytics v8.0.145 and stills its here. No matter what i try to do, even try to load saved models with torch.load, error is the same. Maybe problem is with saving weights?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@protei300 the error message suggests that the model is trying to find an attribute 'NoneType' in the `builtins` module, which does not exist. This could possibly be due to the PyTorch serialization struggling to deserialize the `NoneType` object while loading the weights.  

It is possible that the weights file might have become corrupt during the saving process, or that it originally contained a `NoneType` attribute that could not be deserialized. 

As a preliminary debugging step, you might want to try re-training your model and save the weights again. If this does not solve your issue, you may need to examine the content of your weights file and check your model architecture to make sure all components can be properly serialized and deserialized. 

Please also confirm if any changes or custom alterations were made on the model. Remember to use the latest version of YOLOv8 and PyTorch to ensure compatibility.

**Comment by protei300** [comment]
@glenn-jocher Thanks for reply.

Allready tried to use pure yolov8s.pt model train it for 1 epoch, and then this error occurs. This doesnt happen on 8.0.130 version of ultralytics.
It seems that epoch saving somehow corrupts .pt files. Will try to investigate whats wrong with them.

PyTorch 2.0.1
ultralytics 8.0.151

**Comment by glenn-jocher** [comment]
@protei300 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. I trained a model and ran predictions successfully with it using 8.0.151, and of course our CI also does this multiple times every day, and is green also, therefore we are unable to reproduce any issues with this workflow, which is a very standard workflow run by most users.

<img width="722" alt="Screenshot 2023-08-10 at 15 17 51" src="https://github.com/ultralytics/ultralytics/assets/26833433/7be7b19d-0828-4feb-a1e5-c399fd7197a3">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by protei300** [comment]
Okey i fiigured out what was the problem. And its python version. It seems that it wont work on verision below 3.10. I use 3.9.5 and 3.8.5. Upgraded to 3.11.4 and all works now.

Not sure what has changed in code though, that so drasticly affects on how it works.

**Comment by glenn-jocher** [comment]
@protei300, delighted to hear that you have identified the issue and found a solution as well! YOLOv8's performance can indeed be influenced by the Python version, as well as the versions of various packages it depends on. 

Your specific issue seems to have been caused by the `dill` package, which indeed shows differing behavior based on the Python version employed. Such inconsistencies can certainly lead to unexpected errors and it's great that you were able associate it with the issue.

It's beneficial to take note of the exact versions of Python and packages used when training and deploying models, as these can affect not only the training process and results, but also the ability to load and use the trained models later. 

Thank you for sharing your findings with the community - this could help other users who may face the same issues. Happy training and best of luck with your future projects!

**Comment by protei300** [comment]
@glenn-jocher Thanks for help. Its really interesting bug with packages.... not that easy to catch.

**Comment by glenn-jocher** [comment]
@protei300, you're welcome! Indeed, the interactions between different packages can sometimes lead to unexpected behaviours and can be quite challenging to debug. Any changes in a package can have ripple effects that are hard to foresee without thorough testing. The key lies in keeping a keen eye on the packages and the Python version while building, training or testing the models. We appreciate your patience and persistence in resolving the issue. Happy coding!

**Comment by gbdjxgp** [comment]
@protei300 @glenn-jocher Hello, I have also encountered the same problem. Using Python 3.8, I tried to lower the Dill version to 0.3.5 but still encountered this issue. Do you have any good solutions or ideas for troubleshooting?
![image](https://github.com/user-attachments/assets/eeb45545-c2ac-4aa4-80eb-67b6c47def71)

**Comment by glenn-jocher** [comment]
Hello @gbdjxgp, please ensure you are using the latest version of the Ultralytics package. If the issue persists, consider upgrading to Python 3.10 or later, as compatibility issues with `dill` have been noted in versions below 3.10.

**Comment by glenn-jocher** [comment]
Thank you for identifying the solution. We appreciate your effort in reproducing the issue and look forward to your PR.
