### ISSUE TITLE
 Allow Custom Frame Rate Setting Instead of Hardcoded Value

### ISSUE THREAD

**Issue by KobiMorad** [ultralytics/ultralytics#4284]
https://github.com/ultralytics/ultralytics/blob/c9be1f3cce89778f79fb462797b8ca0300e3813d/ultralytics/trackers/track.py#L35C59-L35C67

In the current implementation, the frame rate is hardcoded to 30. This can limit flexibility for various use cases where users may want a different frame rate.

Suggested Fix:
Refuting this hardcoded value and making it a configurable parameter would be beneficial. Users could then specify their desired frame rate as per their requirements.

Impact:
Introducing this feature allows us to cater to a wider range of use cases, from high-resolution slow-motion videos to low-resolution faster feeds. It will also make our application more flexible and user-friendly

thanks

**Comment by glenn-jocher** [comment]
@KobiMorad thank you for the valuable suggestion. The team and I appreciate your feedback as it helps us to continually improve and evolve YOLOv8 to effectively cater to a myriad of use cases.

You're absolutely correct, hardcoding the frame rate could indeed limit adaptability for different scenarios. Making this a user-configurable parameter could greatly increase flexibility and allow for better customization based on users' unique requirements.

Your suggestion aligns well with our goal of making YOLOv8 as versatile and user-friendly as possible. Rest assured, this is something that we will consider for future updates on YOLOv8.

On behalf of the Ultralytics team and the whole wider YOLO community, thank you once again for bringing this improvement opportunity to our attention. We couldn't make advancements without the thoughtful input of users like you.

**Comment by simlevesque** [comment]
@KobiMorad 

This is annoying but the `frame_rate` is actually only used to calculate BYTETracker's `max_time_lost` which also uses the `track_buffer` from the config file.

You can emulate any `frame_rate` values by changing the `track_buffer`. If you want to have `max_time_lost` of one second, set `track_buffer` to 10 instead of 30.

Hope it makes sense. If you have any questions just ask me.

**Comment by glenn-jocher** [comment]
Hello @simlevesque,

You're correct, the `frame_rate` is currently utilized for calculating BYTETracker's `max_time_lost`. This also correlates with the `track_buffer` from the config file.

An interesting point to note is that the effect of different `frame_rate` values can actually be emulated by adjusting the `track_buffer`. For instance, if your goal is to have `max_time_lost` set to one second at the rate of 10 FPS, you would adjust the `track_buffer` to 10 instead of the default 30. 

This method might allow you to tailor the frame rate to your specific requirements without directly altering the hardcoded `frame_rate` value.

I hope this provides some clarity for you. Don't hesitate to ask if you have further questions or if there's anything else you need help with. Your input is valuable to us and to the continual development of YOLOv8.
