### ISSUE TITLE
Label output of detected images

### ISSUE THREAD

**Issue by ftmhabibii** [ultralytics/ultralytics#4318]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hello, 
I want to output the label of the detected photos in the command or be able to save them somewhere and print it in the output.
For example, in an image, the yolo algorithm has detected 5 person, 2 cars, etc. I want to print these in the output.
Please guide me with which command I can do this.

**Comment by glenn-jocher** [comment]
@ftmhabibii you can use `yolo predict save save_txt` or for Python results handling see https://docs.ultralytics.com/modes/predict/#working-with-results

**Comment by ftmhabibii** [comment]
> @ftmhabibii you can use `yolo predict save save_txt` or for Python results handling see https://docs.ultralytics.com/modes/predict/#working-with-results

Can you explain more? How should I use save_txt? If possible with an example

**Comment by glenn-jocher** [comment]
Hello @ftmhabibii,

Thanks for your inquiry!

When you use the `yolo predict save save_txt` command, the model's predictions for each image file are saved in the same directory as your image files. The saved text files follow the naming convention of the source image file but with a .txt extension instead of the image file extension.

For example, if your source image is "image1.jpg", the associated prediction will be saved in a text file named "image1.txt". Inside this text file, you will find the predictions per line corresponding to each detected object, with the class ID, normalized x_center, y_center, width, and height (relative to the image's width and height). 

With these text files, you can analyze the output of your YOLOv8 model predictions, print out the count of each class detected (e.g., 5 persons, 2 cars, etc.), or conduct post-processing tasks as required by your specific use case.

Hope that clears it up.

**Comment by ftmhabibii** [comment]
thank you

**Comment by glenn-jocher** [comment]
@ftmhabibii you're welcome! If you have any further questions or run into any issues, please don't hesitate to reach out. We're here to help and make your experience with YOLOv8 as smooth as possible. Happy coding!

**Comment by ftmhabibii** [comment]
Hello,
I use yolov8 to detect the sign language on the images and print the detected letters as text in the output. I want to do this on video data as well but I don't understand the relationship between the naming of the txt files and the detected images. For example, in the detected video, the numbering of the txt file name is first 10, then 100, then 1000, and then incremented by one digit. Can you tell me the reason for this naming? And what does it have to do with the video and the letters recognized in it? Is it about seconds of video?

**Comment by glenn-jocher** [comment]
@ftmhabibii hello,

The text file naming you're mentioning corresponds to the frame index of your video stream. When you're processing a video with YOLOv8, it essentially breaks it down into individual frames and treats each frame as a separate image for object detection. 

The reason you're seeing text files numbered as 10, 100, 1000, etc., is likely due to the sorting order of your operating system. The files are named based on the frame index, so you'll get a file for the 1st frame, the 2nd frame, and so on.

As for the relationship with the objects detected, each text file contains the detections for the corresponding frame of the video. So, if you have a text file named '10.txt', it contains the detections for the 10th frame of your video.

These files do not directly refer to the seconds of the video unless you know the frame rate. If you know your video is, for example, 30 frames per second, then you could infer that '900.txt' corresponds to the detections at the 30th-second mark of the video.

I hope this helps to clarify! Let me know if you have further questions.
