### ISSUE TITLE
TRT/Onnx wrong mask postprocessing

### ISSUE THREAD

**Issue by Flippchen** [ultralytics/ultralytics#4344]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection, Export

### Bug

I am currently building a script where I load a TRT Engine with the ultralytics library and predict on several images and afterward plot the masks and bounding boxes. 

I noticed that when I use the normal pytorch weights everything works fine and the masks and bounding boxes get plotted correctly but after I export the model to onnx/TRT the masks have a offset and only the bounding boxes are calculated correctly. 

I fixed it myself with calling the `mask = scale_image(mask, (img_height, img_width))` which is a build in function of yolov8 but is never used in prediction.  

Similar Error: #1815

### Environment

- YOLO: ultralytics==8.0.149
- OS: Windows 11
- Python 3.10

### Minimal Reproducible Example

```
CONFIG = {
    # Whether to perform cone segmentation or only bounding box detection
    "cone_seg": True,
    # Whether to predict on a video(frame for frame) or on a folder of images
    "predict_on_video": True,
    # If set a mp4 video will be exported to the same folder as the input video. If not every frame will get plotted
    "export_as_video": True,
    # Plot labels on the bounding boxes
    "plot_labels": False,
    # Path to the model
    "model_path": "models/engine-608-1280/kaggle-1280-bg-half.engine",
    # Whether to plot also the old method (bbx middle) or not
    "plot_middle_point": True,
    # Minimum size of the bounding box to be considered for mask usage in px
    "min_bbx_size": 28,
    # Path to the folder containing the images to predict on
    "test_folder_path": r"test_images/",
    # Path to the video to predict on
    "test_video_path": r"D:\cure_d\run_387_compressed.mp4",
    # Confidence threshold for the model
    "confidence_threshold": 0.25,
    # Task the model should perform
    "task": "segment",
    # Size of the images during training
    "imgsz": (608, 1280)
}

def process(image: Image, model: YOLOModel, cone_colors: dict, config: dict) -> None:
    """
    Helper function to process a single image or frame and display the results.
    """
    results = model(image, conf=config["confidence_threshold"], imgsz=config["imgsz"], device=0)
    results = results[0]

    fig, ax = plt.subplots(1)
    ax.imshow(image)

    img_width, img_height = image.size
    for box, mask in zip(results.boxes, results.masks):
        conf = box.conf.item()
        class_name = results.names[box.cls.item()]
        x, y, w, h = box.xywh.tolist()[0]

        x = int(x - w / 2)
        y = int(y - h / 2)

        color = cone_colors.get(ConeColor[class_name], 'r') if config["cone_seg"] else 'r'

        if h < config["min_bbx_size"]:
            color = 'g'
        rect = patches.Rectangle((x, y), w, h, linewidth=1, edgecolor=color, facecolor='none')
        ax.add_patch(rect)

        plt.text(x - w * 0.2, y - h * 0.3, f'{class_name} {conf * 100:.0f}%' if config["plot_labels"] else "", color='white',
                 bbox=dict(facecolor=color, edgecolor=color, boxstyle='round,pad=0.5', alpha=0.6))

        # Scale mask correctly because ultralytics is to dump to do it themselves
        mask = mask.data.cpu().numpy()
        mask = np.squeeze(mask)
        mask = scale_image(mask, (img_height, img_width))

        # Convert mask to binary
        mask = np.ma.masked_where(mask == 0, mask)
        # Plot mask
        plt.imshow(mask, alpha=0.7, cmap='tab20b')

        # Get the highest point of the cone
        highest_x, highest_y = calculate_cone_top(h, mask, y, rect, config)

        plt.plot(highest_x, highest_y, 'r+', markersize=5)

        if config["plot_middle_point"]:
            plt.plot(x + w / 2, highest_y, 'b+', markersize=3)

    plt.show()
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Flippchen YOLOv8 segmentation in PyTorch and ONNX both work correctly, you can verify this with these two lines:

```
yolo model=yolov8n-seg.pt export format=onnx
yolo predict model=yolov8n-seg.onnx
```

![image](https://github.com/ultralytics/ultralytics/assets/26833433/314cef00-4706-4542-84a2-87bb9d454151)

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Flippchen** [comment]
Hey @glenn-jocher thanks for your quick response. I have to admit my example is not the best. If you use the integrated plot function it may be correct but in my case I need a little bit more control over the image so  I am plotting all results myself. Following is a better example with results. 
```
import cv2
import numpy as np
from PIL import Image
from matplotlib import pyplot as plt, patches
from ultralytics import YOLO


def process(image, model) -> None:
    """
    Helper function to process a single image or frame and display the results.
    """
    results = model(image, conf=0.25, imgsz=(608, 1280), device=0)
    results = results[0]

    fig, ax = plt.subplots(1)
    ax.imshow(image)

    img_width, img_height = image.size
    for box, mask in zip(results.boxes, results.masks):
        conf = box.conf.item()
        class_name = results.names[box.cls.item()]
        x, y, w, h = box.xywh.tolist()[0]

        x = int(x - w / 2)
        y = int(y - h / 2)

        color = 'r'

        rect = patches.Rectangle((x, y), w, h, linewidth=1, edgecolor=color, facecolor='none')
        ax.add_patch(rect)

        # Scale mask correctly because ultralytics is to dump to do it themselves
        #mask = mask.data.cpu().numpy()
        #mask = np.squeeze(mask)
        # mask = scale_image(mask, (img_height, img_width))
        # Convert mask to binary
        #mask = np.ma.masked_where(mask == 0, mask)

        mask_np = mask.data.to("cpu").numpy()
        print(mask_np.shape)
        mask_np = np.squeeze(mask_np)
        mask_np = cv2.resize(mask_np, (img_width, img_height))
        mask_np = np.ma.masked_where(mask_np == 0, mask_np)
        # Plot mask
        plt.imshow(mask_np, alpha=0.7, cmap='tab20b')

    plt.show()


# Load a pretrained YOLOv8n-seg Segment model
model = YOLO("segmentation/models/kaggle-1280-bg.onnx", task='segment')

model2 = YOLO("segmentation/models/kaggle-1280-bg.pt", task='segment')

models = [model, model2]
image = Image.open("segmentation/test_images/frame.jpg")

for model in models:
    process(image, model)

```
The resulting images look like:
![image](https://github.com/ultralytics/ultralytics/assets/91947480/7bb850ab-b8e8-4511-a1b3-b83f22821538)
![image](https://github.com/ultralytics/ultralytics/assets/91947480/03a72578-43ed-49af-8d76-81d99d5852d3)
With the same code applied I get different results. I cropped the image, to respect the privacy of the people in it.
As you can see from the example I used cv2 to resize every mask and also plottet the shape of the masks returned from the model and they are a different shape, even though I gave an input size with this line `imgsz=(608, 1280`
![image](https://github.com/ultralytics/ultralytics/assets/91947480/d3ae548e-ed99-4dd3-a739-a9ce2a6ddb49)

**Comment by glenn-jocher** [comment]
Hi @Flippchen,

We're actively looking into the issue you raised regarding the discrepancies in mask dimensions between different models. Our developers are trying to replicate the issue and determine the root cause. As soon as we have an updated find or resolution, we will let you know. 

We appreciate your patience and your contribution to the YOLOv8 community by raising this issue. In the meantime, if you come across any other issues or significant discoveries related to this, please feel free to share.

Thank you for your understanding.
