### ISSUE TITLE
yolov8 detect model .pt convert to .onnx, result not right

### ISSUE THREAD

**Issue by simpson0826** [ultralytics/ultralytics#4350]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hi ,I have the  problem about predict

when I use
```
from ultralytics import YOLO
model = YOLO("yolov8n.pt")
model.predict(imgsz=640)
model.export(format="onnx")
model = YOLO("yolov8n.onnx")
model.predict(imgsz=640)
```

I got different results in model predict

pt result
image 1/1 /home/test/bus.jpg: 640x480 4 persons, 1 bus, 1 stop sign, 50.1ms
Speed: 5.0ms preprocess, 50.1ms inference, 4.0ms postprocess per image at shape (1, 3, 640, 480)

onnx result
image 1/1 /home/test/bus.jpg: 640x640 4 persons, 1 bus, 44.4ms
Speed: 2.6ms preprocess, 44.4ms inference, 1.7ms postprocess per image at shape (1, 3, 640, 640)

stop sign is not in onnx predict result

### Environment

Ultralytics YOLOv8.0.147  Python-3.8.8 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3050 Ti Laptop GPU, 4096MiB)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Kayzwer** [comment]
@simpson0826 it is normal to have some precision loss after doing convert

**Comment by glenn-jocher** [comment]
@simpson0826 we run benchmarks constantly on all export formats and observe no ONNX accuracy loss at all. See https://docs.ultralytics.com/modes/benchmark

This is part of our constant CI, and if any export format like ONNX loses accuracy the tests fail and the CI badges instantly turn red for everyone to see (including you). See https://docs.ultralytics.com/help/CI/

https://github.com/ultralytics/ultralytics/actions/runs/5827390133/job/15803309164
<img width="1589" alt="Screenshot 2023-08-11 at 20 44 09" src="https://github.com/ultralytics/ultralytics/assets/26833433/1d6cfd84-949a-4a8d-9b23-3cfc36254d0f">

Therefore we are obviously unable to reproduce any accuracy drops. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by dium6i** [comment]
@glenn-jocher Sorry to reopen this issue and bother you, I also encounter this problem(ONNX accuracy loss). Here are my models and test images in a zip file. (https://drive.google.com/file/d/1HsOcGnVYuwo38dxrZgWF4GZHRLWxJpGd/view?usp=sharing)

I trained pt model using ultralytics-8.0.119 with Python-3.10.9 torch-2.0.0. 

I exported pt model to onnx model in Jupyter Lab using command below: 
`!yolo export model=path/of/best.pt format=onnx nms=True`

I tested the image in Jupyter Lab using command below: 
`!yolo detect predict model=path/of/best.pt source=path/of/test.jpg conf=0.5`
results: 480x640 12 bars, 13 dnb_1s, 13 dnb_screens, 13 dnb_mps, 5 fy_loses, 110.4ms
`!yolo detect predict model=path/of/best.onnx source=path/of/test.jpg conf=0.5`
results: 640x640 12 bars, 12 dnb_1s, 1 dnb_3, 13 dnb_screens, 13 dnb_mps, 6 fy_loses, 1 dnb_blank, 116.6ms

Looking forward to your reply.

**Comment by glenn-jocher** [comment]
@dium6i Thank you for providing the details. To investigate the issue of ONNX accuracy loss, please ensure that you are using the latest version of the Ultralytics YOLOv8 repository. If you haven't already, update your repository and dependencies to the latest versions.

Once you've confirmed that you're on the latest version, please follow the guidelines for creating a minimal reproducible example as outlined in our documentation. This will help us to better understand and diagnose the issue.

If the problem persists after updating and creating a minimal reproducible example, please open a new issue using the Bug Report template and include all the necessary details, such as the exact commands you're using, the environment details, and any discrepancies you observe between the `.pt` and `.onnx` model predictions.

We appreciate your cooperation and look forward to assisting you further. 😊
