### ISSUE TITLE
Exported model for android which has nms

### ISSUE THREAD

**Issue by SteadyKim** [ultralytics/ultralytics#4427]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is there any other model that already has nms or nms method exported from yolo8.pt ??

I was planning to use tflight model exported from yolo8. But as you know , i get [1, 82, 8400] 
8400 grid and 4 +78(labels).

But adjusting  nms in tflight was too difficult. And also i have wrong predicted result with the output. Result should be label 11 . But it checks label 55 or something. 
(
1. Yolo8.pt prediction_rate was almost 0.97 above.
2. I checked the input, output shape and rescaled the bitmap. 
3. I think something is happened when exporting )

So im planning to use another exported model in android. 
I want another model including nms library or already adjusted nms and has label, confidence_rate ouput. 

Thank you any suggestion?

**Comment by MuhammadShifa** [comment]
Hi @SteadyKim ,
You are facing the issue of yolov8 tflite model integration in android. I am also facing the same issue. I think if you want to use any object detection model then I would suggest yolov5 for yout. This [respository](https://github.com/AarohiSingla/TFLite-Object-Detection-Android-App-Tutorial-Using-YOLOv5/tree/main) can help you in training and testing yolov5 model, converting the model into tflite through [export.py](https://github.com/ultralytics/yolov5/blob/master/export.py) file of Yolov5. The respositry has also android application code and you can use it easily.
I am also adding the command through which I have successfully converted the model into tflite and it's working fine with android application given in [repository]((https://github.com/AarohiSingla/TFLite-Object-Detection-Android-App-Tutorial-Using-YOLOv5/tree/main)).
`python export.py --weights best.pt --include tflite --int8 --img 416 --data custom_data.yaml`

**Comment by glenn-jocher** [comment]
@MuhammadShifa hello,

For YOLOv8 models, non-maximum suppression (NMS) is not currently exported as part of the model for TFLite. The model output will give you raw detections from the model, which include the 8400 grid cells each with predictions for objectivness, bounding box coordinates, and class probabilities. 

In order to get usable detections from this output, you need to apply the NMS algorithm. Understandably, implementing NMS in TFLite can be a challenging task. But I assure you that it's feasible, as NMS mainly involved standard operations like sorting and mathematical comparisons.

As for the incorrect label predictions, there are several potential issues that could cause this. Some possibilities might include differences in post-processing between how the model was trained and how it's being used in Android, or possible issues with how the model was exported.

I would recommend double-checking the label mappings and also ensuring that the inputs being passed to the model in your Android environment are correctly pre-processed.

While creating a version of YOLOv8 that includes NMS as part of the exported model would be ideal, currently the Ultralytics team doesn't provide such model. However, I appreciate your suggestion and will share it with the team for future updates. 

Thanks for reaching out and keep trying with implementing NMS in TFLite, good luck!
