### ISSUE TITLE
Training model

### ISSUE THREAD

**Issue by spacewalk01** [ultralytics/ultralytics#4434]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am training yolov8 large model but trainer downloads yolov8n.pt model why is that?
```
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt to 'yolov8n.pt'...
100%|█████████████████████████████████████████████████████████████████████████████| 6.23M/6.23M [00:00<00:00, 8.48MB/s]
AMP: checks passed
```

**Comment by ZhouBay-TF** [comment]
HI,The trained model is based on YOLOv8n.pt and continues to be trained. This is useful when your data is relatively small, but if you have a lot of data, you can try training from 0, but I only know how to do this in YOLOv5.

**Comment by glenn-jocher** [comment]
@ZhouBay-TF hello,

Thanks for reaching out!

The model you're training is indeed using the YOLOv8n.pt as a base for transfer learning. This approach leverages the knowledge gathered by the base model from its own training and applies that to the new model you're training. This method often yields higher performance especially if your dataset is relatively small or if the new task is similar to the task the base model was trained on.

However, if you have a significantly large and diverse dataset, you could consider training the model from scratch, i.e., without weights from a pre-trained model. This way, the model learns exclusively from your data, which can be advantageous if your data is very different from the one the base model was trained on.

Remember that the choice between the two methods - transfer learning and training from scratch - would mainly depend on your specific situation, like the size and diversity of your dataset and the computational resource at your disposal.

**Comment by spacewalk01** [comment]
I know it uses transfer learning but I didn't know in yolov8, we can use pretrained yolov8n.pt to train yolov8l.pt by transferring knowledge from yolov8 nano model to yolov8 large model. Interesting.

**Comment by glenn-jocher** [comment]
@spacewalk01 hello, and thank you for your comment. 

Yes, that's absolutely correct! YOLOv8 is designed in such a way that it utilizes the concept of transfer learning very effectively. In the case you've mentioned, YOLOv8 indeed uses the weights from the pretrained YOLOv8n (nano) model to kick-start training for the YOLOv8l (large) model. 

This process can often yield improved performance as the YOLOv8l model can capitalize on the patterns learned by the YOLOv8n model, rather than starting the learning process completely from scratch. This can be especially beneficial when dealing with small datasets or when computational resources are limited. 

The YOLOv8 design philosophy emphasizes efficiency and flexibility in training models to tackle a variety of tasks. This adaptability extends to allowing model weights to be transferable across different architectures within the YOLOv8 family. 

For more information, please take a look at our model training implementation in our GitHub repository.

Stay tuned to our repository for updates and improvements to our models and training procedures!

**Comment by imPdhar** [comment]
@glenn-jocher, just to confirm, are the n,s,m,l,x weights trained on COCO?

**Comment by glenn-jocher** [comment]
@imPdhar yes, the YOLOv8n (nano), s (small), m (medium), l (large), and x (extra large) model weights are all pre-trained on the COCO dataset. This provides a solid starting point for further training on a custom dataset or for direct inference! 🚀📊

**Comment by naqibsyahmi** [comment]
@glenn-jocher is it possible to use other pretrained weight sizes like yolov8s, yolov8m or yolov8l instead of yolov8n, is this setting configurable?

**Comment by Matthias1982** [comment]
Hi Glenn

Just another Question regarding the freezing of :

Freezing layer 'model.22.dfl.conv.weight'.

I loaded a 

- yolo8n.yaml
- freeze=None
-pretrained=False

and still the message:
Freezing layer 'model.22.dfl.conv.weight'

is shown.

``#import torch
#print(torch.__version__)

from ultralytics import YOLO
from clearml import Task, Dataset

# Check if CUDA is available
#cuda_available = torch.cuda.is_available()
#print(torch.version.cuda)
#print("Is CUDA available:", cuda_available)

# Creating a ClearML Task
task = Task.init(
    project_name="Training_MASAM_Modell_N",
    task_name="022_Datensatz_0016_Freeze_None_12",
    output_uri=True
)

CUDA_LAUNCH_BLOCKING=1

model = YOLO("yolov8n.yaml")
data = r"C:\Users\junke\Dropbox\Daten_fuer_MAS_Thesis\Trainingsdatenset_Fahrzeuge\xxx_Verwendete Trainingsset\0016_Datenset\data.yaml"

def main():
    results = model.train(data=data,
                          epochs=80,
                          device=0,         # 0 = GPU
                          imgsz=640,
                          patience=50,      # Epochen die gewartet werden bis das Training vorzeitig beendet wird, wenn keine Verbesserung erkannt wird
                          batch=32,         # Anzahl der Bilder pro batch
                          save=True,
                          resume=False,     # Start Training vom letzten Checkpunkt (Wenn z.B. wegen Fehler abgebrochen wurde)
                          freeze=None,      # Freeze first n Layers, oder Liste von Layern
                          pretrained=False   # Benütze ein vortrainiertes Modell; default=True
                          )


if __name__ == '__main__':
    main()

**Comment by glenn-jocher** [comment]
@Matthias1982 hello,

The message about freezing a layer can sometimes appear even when you've set `pretrained=False` and `freeze=None`. This could be due to the specific configuration within the model's YAML file or a default behavior in the code that might not be overridden by the command line arguments.

If you're certain you want no layers to be frozen and no pre-trained weights to be used, please double-check your YAML configuration and ensure that the model definition aligns with these requirements. If the issue persists, it might be worth looking into the source code where the freezing logic is implemented to ensure it's behaving as expected.

If you need further assistance, feel free to raise an issue on the GitHub repository with the details of your configuration and the behavior you're observing.

**Comment by jbdebelle** [comment]
> the concept of transfer learning very effectively. In the case you've mentioned, YOLOv8 indeed uses the weights from the pretrained YOLOv8n (nano) model to kick-start training for the YOLOv8l (large) model.

hi @glenn-jocher and @Burhan-Q    might I ask why use the weights from the pretrained YOLOv8n (nano) model to kick-start training for the YOLOv8l (large) model ? I am very curious to understand this. Is it not better to use directly pretrained YOLOv8l (large) model to kick-start training. 
Thanks
