### ISSUE TITLE
My Custom Yolov8 ncnn model doesn't work correct. Help me!!!

### ISSUE THREAD

**Issue by duymanh-111** [ultralytics/ultralytics#4459]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to convert yolov8 model to ncnn model for ncnn c++ project?

### Additional

Thanks this project. 
I successfully converted yolov8n.pt with this article "https://blog.csdn.net/haiyangyunbao813/article/details/129919011".
But the result is incorrect.

when ncnnoptimize, following warning ocurrs.
>ncnnoptimize models/yolov8n.param models/yolov8n.bin models/yolov8n-opt.param models/yolov8n-opt.bin 65536
Input layer images without shape info, shape_inference skipped
Input layer images without shape info, estimate_memory_footprint skipped

I would appreciate to help me how to convert yolov8 model to ncnn.
Thanks.
[ncnn-yolov8-source.zip](https://github.com/FeiGeChuanShu/ncnn-android-yolov8/files/12387233/ncnn-yolov8-source.zip)

**Comment by DaniyalAhmadKhan-LUMS** [comment]
I am facing a similar problem. When I convert yolov8m custom weights to ncnn format using ultralytics my C++ mobile application shows alot of detection boxes on the screen even if the object is not present in the frame. .pt weights work fine when I run them on my PC.

**Comment by pderrenger** [comment]
@DaniyalAhmadKhan-LUMS it sounds like the issue may be related to your conversion process or the parameters used during the conversion. Since you've successfully converted the .pt weights with a guide, the next step is to validate the conversion process and ensure that the parameters are set correctly. 

First, confirm that the input and output shapes and parameters are accurately defined during the conversion process for the specific YOLOv8 model you're using. You may need to inspect and modify the input layer shape settings, and ensure that the conversion process handles confidence thresholding appropriately to avoid excessive detection boxes.

Additionally, it could be helpful to review the documentation for guidance on how to correctly set up the conversion and ensure that the ncnn model is configured in a way that aligns with the YOLOv8 model's requirements.

As a starting point, I would recommend cross-checking the conversion parameters and settings for ncnn optimization, taking into account the specificities of YOLOv8 models, to reduce the excessive detection boxes issue on your mobile application.

Kindly let me know if this helps, or if you need further assistance!
