### ISSUE TITLE
YOLOv8 requirement "ultralytics.nn.modules.conv" not found, attempting AutoUpdate

### ISSUE THREAD

**Issue by DaniyalAhmadKhan-LUMS** [ultralytics/ultralytics#4465]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

requirements: YOLOv8 requirement "ultralytics.nn.modules.conv" not found, attempting AutoUpdate...
ERROR: Could not find a version that satisfies the requirement ultralytics.nn.modules.conv (from versions: none)
ERROR: No matching distribution found for ultralytics.nn.modules.conv
requirements: ❌ Command 'pip install "ultralytics.nn.modules.conv"  ' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/daniyal/Documents/Upwork/Jared/Feb19Ultralytics/ultralytics/export.py", line 3, in <module>
    model = YOLO("yolov8_product_detection_dk_v1.1.pt")
  File "/home/daniyal/Documents/Upwork/Jared/Feb19Ultralytics/ultralytics/ultralytics/yolo/engine/model.py", line 68, in __init__
    self._load(model)
  File "/home/daniyal/Documents/Upwork/Jared/Feb19Ultralytics/ultralytics/ultralytics/yolo/engine/model.py", line 96, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/home/daniyal/Documents/Upwork/Jared/Feb19Ultralytics/ultralytics/ultralytics/nn/tasks.py", line 395, in attempt_load_one_weight
    ckpt = torch_safe_load(weight)  # load ckpt
  File "/home/daniyal/Documents/Upwork/Jared/Feb19Ultralytics/ultralytics/ultralytics/nn/tasks.py", line 350, in torch_safe_load
    return torch.load(file, map_location='cpu')  # load
  File "/home/daniyal/anaconda3/envs/prayolov8/lib/python3.10/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/daniyal/anaconda3/envs/prayolov8/lib/python3.10/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/home/daniyal/anaconda3/envs/prayolov8/lib/python3.10/site-packages/torch/serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'ultralytics.nn.modules.conv'; 'ultralytics.nn.modules' is not a package

### Environment

Name: ultralytics
Version: 8.0.158
Summary: Ultralytics YOLOv8 for SOTA object detection, multi-object tracking, instance segmentation, pose estimation and image classification.
Home-page: https://github.com/ultralytics/ultralytics
Author: Ultralytics
Author-email: hello@ultralytics.com
License: AGPL-3.0
Location: /home/daniyal/anaconda3/envs/prayolov8/lib/python3.10/site-packages
Requires: matplotlib, numpy, opencv-python, pandas, pillow, psutil, py-cpuinfo, pyyaml, requests, scipy, seaborn, torch, torchvision, tqdm

### Minimal Reproducible Example

from ultralytics import YOLO

model = YOLO("yolov8_product_detection_dk_v1.1.pt")

success = model.export(format="onnx", opset=13,simplify=True)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@DaniyalAhmadKhan-LUMS 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by glenn-jocher** [comment]
<img width="1871" alt="Screenshot 2023-08-21 at 02 26 40" src="https://github.com/ultralytics/ultralytics/assets/26833433/b1e2f4ce-fd9d-4b2a-85a8-0b92f5d0bcef">

**Comment by DaniyalAhmadKhan-LUMS** [comment]
Thanks @glenn-jocher figured it out.

**Comment by glenn-jocher** [comment]
@DaniyalAhmadKhan-LUMS that's great to hear! If you encounter any further issues or have more questions concerning YOLOv8, feel free to raise them. That's what our community is here for. Good luck with your further use of our repository and thank you for being part of the YOLOv8 community!

**Comment by lkz98** [comment]
请问是什么原因啊

**Comment by glenn-jocher** [comment]
@lkz98 could you please provide more context or details regarding the issue you're facing? This will help us assist you more effectively. 😊

**Comment by SmallChungus1** [comment]
> 请问是什么原因啊

maybe because Ultralytics version '8.0.158' is too old. I encountered the same issue when using version 8.0, but was able to resolve it after updating Ultralytics to 8.2+

**Comment by glenn-jocher** [comment]
Thanks for reaching out! 😊 The error you're encountering is likely due to an outdated Ultralytics version. To resolve this, please update to the latest version with:

```bash
pip install -U ultralytics
```

This should resolve the missing module error. For installation guidance, see Ultralytics Installation Guide. Let us know if you need further assistance!
