### ISSUE TITLE
When converting a YOLOv8 model to onnx, how can I convert output[0] to YOLOv5 format?

### ISSUE THREAD

**Issue by haaaaak** [ultralytics/ultralytics#4474]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I converted the model to onnx for testing.
However, in the case of yolov8, an error occurred because it did not follow the form of yolov5 or yolov7.

This is because the shape of output[0] is different.
Therefore, I would like to match this output[0] like existing yolov5 or yolov7.
The image below is the output[0] of v8.

For example, for v5 and v7, the output[0] tensor appears as [1, 21504,51].
And please tell me why the anchor in the middle is -1.

Thank you!

![Capture](https://github.com/ultralytics/ultralytics/assets/97625003/4b96c44d-8c37-43eb-abb0-14ec770a3e4f)

**Comment by glenn-jocher** [comment]
@haaaaak hello,

Since the YOLOv8 repository maintains a unique design and architecture from its predecessors, including YOLOv7, the shape of `output[0]` in YOLOv8 might indeed be different when the model is converted to onnx.

That being said, to match the `output[0]` to the existing shape of its predecessors, you would need to modify the model's output architecture accordingly, keeping the dimension conventions same as them.

However, it's important to be aware that these changes may have an impact on the performance of the model, given the differences in design and operations between these versions.

Regarding the anchor in the middle being -1, it could be dependent upon the architecture and operational parameters set for the model and data. This can be a convention used in the model's architecture to represent certain features or aspects during the transformation process.

It's recommended to understand the structure and execution of the YOLOv8 architecture thoroughly before making any changes to ensure optimal performance.

Thank you for your query!

**Comment by Zephyr69** [comment]
I don't think you can. v8 doesn't use obj_conf, so the best you can do to mimic a v5 format is to insert a placeholder value.

**Comment by glenn-jocher** [comment]
@Zephyr69 hi, thanks for your question.

In YOLOv8, the model architecture is indeed different from previous versions and it does not utilize `obj_conf`. Because of this, direct conversion to mimic the output format of other versions might not be feasible without significant changes to the model framework or possibly contemplating a decrease on model performance.

Should you need to keep a similar output format with `obj_conf`, one way would be to insert a placeholder value, as you mentioned. While this could provide similar format, please note that the placeholder value won't deliver any meaningful information given object confidence is not a measure used in YOLOv8.

For YOLOv8, it's best to adhere to its prescribed output format to fully utilize its state-of-the-art architecture and achieve optimal performance. Remember that the difference in design is aimed to drive improvements and advancements in the overall YOLO series. 

Hope this answers your question. Feel free to ask if you have any more queries.
