### ISSUE TITLE
How to torch.hub.load yolov8x.pt

### ISSUE THREAD

**Issue by FurkanGozukara** [ultralytics/ultralytics#4476]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am able to load yolov7-e6e.pt like below

How can I load same way best yolov8 pre trained model?

```
model = torch.hub.load('WongKinYiu/yolov7', 'custom', 'yolov7-e6e.pt',
                       force_reload=True, trust_repo=True)
```

**Comment by glenn-jocher** [comment]
@FurkanGozukara sure, I'd be happy to guide you through the process of loading a pre-trained YOLOv8 model.

Similar to how you've loaded the YOLOv7 model, you would want to call the `torch.hub.load()` function with the correct parameters. However, instead of specifying 'WongKinYiu/yolov7', you would need to specify the Ultralytics YOLOv8 repo path. For the model, you replace 'yolov7-e6e.pt' with your desired pre-trained YOLOv8 model filename.

Bear in mind, our repo is under the name of 'ultralytics', so the correct repo path would be 'ultralytics/yolov8'. Then, you just need to specify the pre-trained YOLOv8 model that you want to load.

I hope this helps! Let us know if you run into any issues.

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara sure, I'd be happy to guide you through the process of loading a pre-trained YOLOv8 model.
> 
> Similar to how you've loaded the YOLOv7 model, you would want to call the `torch.hub.load()` function with the correct parameters. However, instead of specifying 'WongKinYiu/yolov7', you would need to specify the Ultralytics YOLOv8 repo path. For the model, you replace 'yolov7-e6e.pt' with your desired pre-trained YOLOv8 model filename.
> 
> Bear in mind, our repo is under the name of 'ultralytics', so the correct repo path would be 'ultralytics/yolov8'. Then, you just need to specify the pre-trained YOLOv8 model that you want to load.
> 
> I hope this helps! Let us know if you run into any issues.

thank you so much for answer

I test like this and I am getting 404 error

model = torch.hub.load('ultralytics/yolov8', 'custom', 'yolov8x6', force_reload=True, trust_repo=True)
```

  File "C:\Python3108\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara sure, I'd be happy to guide you through the process of loading a pre-trained YOLOv8 model.
> 
> Similar to how you've loaded the YOLOv7 model, you would want to call the `torch.hub.load()` function with the correct parameters. However, instead of specifying 'WongKinYiu/yolov7', you would need to specify the Ultralytics YOLOv8 repo path. For the model, you replace 'yolov7-e6e.pt' with your desired pre-trained YOLOv8 model filename.
> 
> Bear in mind, our repo is under the name of 'ultralytics', so the correct repo path would be 'ultralytics/yolov8'. Then, you just need to specify the pre-trained YOLOv8 model that you want to load.
> 
> I hope this helps! Let us know if you run into any issues.

I made it work like this

model = YOLO('yolov8x6.pt')

but it fails at this stage no pandas

        results = model(img_path)
        detections = results.pandas().xyxy[0]

```
Exception in thread Thread-8 (process_files):
Traceback (most recent call last):
  File "C:\Python3108\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Python3108\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "G:\yolo v8\yolo_v8_cropper.py", line 70, in process_files
    detections = results.pandas().xyxy[0]
AttributeError: 'list' object has no attribute 'pandas'
```

**Comment by glenn-jocher** [comment]
@FurkanGozukara, the error you're encountering seems to be related to the output type of the model's prediction. The prediction returns a list and not a pandas DataFrame, which is why you're getting the error `'list' object has no attribute 'pandas'`.

In our Ultralytics YOLOv8 model, results are returned as a list of detections, where each detection is a tuple containing the image, the predicted bounding box coordinates and the class identifiers.

To access certain class detections like 'person', you may want to iterate through the results list and check the classes of the detections. Use the corresponding class names to label mappings provided by the model to identify 'person' detections.

Feel free to ask if you require more guidance for handling the prediction results.

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara, the error you're encountering seems to be related to the output type of the model's prediction. The prediction returns a list and not a pandas DataFrame, which is why you're getting the error `'list' object has no attribute 'pandas'`.
> 
> In our Ultralytics YOLOv8 model, results are returned as a list of detections, where each detection is a tuple containing the image, the predicted bounding box coordinates and the class identifiers.
> 
> To access certain class detections like 'person', you may want to iterate through the results list and check the classes of the detections. Use the corresponding class names to label mappings provided by the model to identify 'person' detections.
> 
> Feel free to ask if you require more guidance for handling the prediction results.

ye please give me a small code because that would be much better answer ty

you see you only need to provide 4 lines of code

```
  results = model(img_path)
    detections = results.pandas().xyxy[0]
    person_detected = detections[detections['name'] == 'person']
    if not person_detected.empty:
```

**Comment by glenn-jocher** [comment]
@FurkanGozukara, I understand how a code example can be practically helpful. While I'm unable to provide direct code here, I can suggest a general approach.

Your model predictions, `results`, is a list. Each element of the list is a tuple containing output details for each image. The tuple includes the image, predicted bounding box coordinates, and class identifiers.

Try iterating over each element of the `results` list and examine the class identifiers in each element's tuple. By comparing these class identifiers against the class names provided by the model, you can identify detections belonging to the 'person' class.

So, you would want to replace the `results.pandas().xyxy[0]` line, with an appropriate method to iterate over the 'results' list, and check the class of each detection in each image's tuple of results. Then, isolate instances where the class corresponds to 'person'.

Finally, instead of checking with `if not person_detected.empty:`, you would check whether your chosen method of storing 'person' detections contains any elements.

I hope this explanation helps. Do let me know if you have any more queries!

**Comment by Mary14-design** [comment]
I am going through the same isssue 

`---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
Cell In[48], line 1
----> 1 test_model = torch.hub.load('ultralytics/yolov8', 'yolov8s')

File /opt/conda/lib/python3.11/site-packages/torch/hub.py:555, in load(repo_or_dir, model, source, trust_repo, force_reload, verbose, skip_validation, *args, **kwargs)
    551     raise ValueError(
    552         f'Unknown source: "{source}". Allowed values: "github" | "local".')
    554 if source == 'github':
--> 555     repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
    556                                        verbose=verbose, skip_validation=skip_validation)
    558 model = _load_local(repo_or_dir, model, *args, **kwargs)
    559 return model

File /opt/conda/lib/python3.11/site-packages/torch/hub.py:222, in _get_cache_or_reload(github, force_reload, trust_repo, calling_fn, verbose, skip_validation)
    219 else:
    220     # Validate the tag/branch is from the original repo instead of a forked repo
    221     if not skip_validation:
--> 222         _validate_not_a_forked_repo(repo_owner, repo_name, ref)
    224     cached_file = os.path.join(hub_dir, normalized_br + '.zip')
    225     _remove_if_exists(cached_file)

File /opt/conda/lib/python3.11/site-packages/torch/hub.py:181, in _validate_not_a_forked_repo(repo_owner, repo_name, ref)
    179 page += 1
    180 url = f'{url_prefix}?per_page=100&page={page}'
--> 181 response = json.loads(_read_url(Request(url, headers=headers)))
    182 # Empty response means no more data to process
    183 if not response:

File /opt/conda/lib/python3.11/site-packages/torch/hub.py:164, in _read_url(url)
    163 def _read_url(url):
--> 164     with urlopen(url) as r:
    165         return r.read().decode(r.headers.get_content_charset('utf-8'))

File /opt/conda/lib/python3.11/urllib/request.py:216, in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    214 else:
    215     opener = _opener
--> 216 return opener.open(url, data, timeout)

File /opt/conda/lib/python3.11/urllib/request.py:525, in OpenerDirector.open(self, fullurl, data, timeout)
    523 for processor in self.process_response.get(protocol, []):
    524     meth = getattr(processor, meth_name)
--> 525     response = meth(req, response)
    527 return response

File /opt/conda/lib/python3.11/urllib/request.py:634, in HTTPErrorProcessor.http_response(self, request, response)
    631 # According to RFC 2616, "2xx" code indicates that the client's
    632 # request was successfully received, understood, and accepted.
    633 if not (200 <= code < 300):
--> 634     response = self.parent.error(
    635         'http', request, response, code, msg, hdrs)
    637 return response

File /opt/conda/lib/python3.11/urllib/request.py:563, in OpenerDirector.error(self, proto, *args)
    561 if http_err:
    562     args = (dict, 'default', 'http_error_default') + orig_args
--> 563     return self._call_chain(*args)

File /opt/conda/lib/python3.11/urllib/request.py:496, in OpenerDirector._call_chain(self, chain, kind, meth_name, *args)
    494 for handler in handlers:
    495     func = getattr(handler, meth_name)
--> 496     result = func(*args)
    497     if result is not None:
    498         return result

File /opt/conda/lib/python3.11/urllib/request.py:643, in HTTPDefaultErrorHandler.http_error_default(self, req, fp, code, msg, hdrs)
    642 def http_error_default(self, req, fp, code, msg, hdrs):
--> 643     raise HTTPError(req.full_url, code, msg, hdrs, fp)

HTTPError: HTTP Error 404: Not Found`

**Comment by glenn-jocher** [comment]
@Mary14-design it appears you're encountering an HTTP 404 error when trying to load a YOLOv8 model using `torch.hub.load`. This could be due to an incorrect repository or model name. Please ensure that you are using the correct model name and that the model exists in the repository. If the issue persists, please refer to the documentation at https://docs.ultralytics.com for guidance on loading models correctly. If you need further assistance, feel free to open an issue in the repository with details of the problem.

**Comment by KORAY-AMAN-ASLAN** [comment]
I have the problem with my yolo_run_interface function, I like to use my yolov8l.pt model instead of v5. but it gives errro,
"""
# Load the YOLOv5 model pre-trained on COCO dataset
model = YOLO("yolov8l.pt")

def get_color_by_id(class_id):
    """
    Generates a unique color for each class ID to ensure consistency across runs.
    """
    np.random.seed(class_id)
    return [int(x) for x in np.random.randint(0, 255, 3)]

def run_yolov5_inference(model, frame):
    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    print(frame_rgb)
    results = model(frame_rgb)
    detections = []
    for *xyxy, conf, cls in results.xyxy[0]:
        x1, y1, x2, y2 = xyxy
        class_name = model.names[int(cls.item())]  # Get class name
        detections.append([x1.item(), y1.item(), x2.item(), y2.item(), conf.item(), cls.item(), class_name])
    return detections


This  
0: 480x640 1 person, 632.7ms
Speed: 8.0ms preprocess, 632.7ms inference, 13.5ms postprocess per image at shape (1, 3, 480, 640)
Traceback (most recent call last):
  File "C:\Users\amana\PycharmProjects\yolov9-cpu-\crossObjectDetector.py", line 124, in <module>
    main()
  File "C:\Users\amana\PycharmProjects\yolov9-cpu-\crossObjectDetector.py", line 86, in main
    detections = run_yolov5_inference(model, frame)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amana\PycharmProjects\yolov9-cpu-\crossObjectDetector.py", line 33, in run_yolov5_inference
    for *xyxy, conf, cls in results.xyxy[0]:
                            ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'xyxy'
(yolov9-cpu-) PS C:\Users\amana\PycharmProjects\yolov9-cpu->

**Comment by glenn-jocher** [comment]
@KORAY-AMAN-ASLAN hey there! 😊 It looks like you're transitioning from YOLOv5 to YOLOv8, which is awesome! However, I noticed you're using `results.xyxy[0]` in your loop, which seems to be the root of the error you're encountering. In YOLOv8, the results are returned as a list of detections without the `.xyxy` attribute directly accessible as in YOLOv5.

For your YOLOv8 model, you might want to adjust how you process the results. Here's a quick tweak to your function:

```python
def run_yolov8_inference(model, frame):
    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    results = model(frame_rgb)
    detections = []
    for det in results:  # Iterate through each detection
        x1, y1, x2, y2, conf, cls = det[:6]  # Extract bbox coords, conf, class
        class_name = model.names[int(cls)]  # Get class name
        detections.append([x1, y1, x2, y2, conf, cls, class_name])
    return detections
```

Give this a shot, and you should be good to go! If you run into any other snags, just let us know! 🚀

**Comment by KORAY-AMAN-ASLAN** [comment]
Hi @glenn-jocher , Thank you for your response. I have tried your example before howevere it  still gave me erro. Therefor I share the link to entire code. 
I get, 
0: 480x640 1 person, 1 microwave, 1 oven, 1 refrigerator, 688.1ms
Speed: 1.0ms preprocess, 688.1ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
Detection does not have enough elements: ultralytics.engine.results.Results object with attributes:
The lonk to code: 
https://onlinegdb.com/5CSq3fn7T

**Comment by glenn-jocher** [comment]
@KORAY-AMAN-ASLAN hi there! 😊 Thanks for reaching out and for providing the link to your code. It appears there might be a slight misunderstanding in how the results are handled with YOLOv8. 

When processing results, ensure you're iterating correctly through the detections list returned by the model. Here's a quick example on how to properly iterate through and access detection elements:

```python
results = model(frame)  # Assuming 'frame' is your input image

for det in results:
    x1, y1, x2, y2, conf, cls_id = det[:6]  # Parsing detection details
    class_name = model.names[int(cls_id)]  # Getting class name
    print(f"Detected {class_name} with confidence {conf}")

# Ensure you use the correct structure to access detection attributes.
```

Make sure this aligns well with how you've structured your code in your project. If you're experiencing specific error messages or behavior, could you point out which part of the code is giving trouble? It would help in pinpointing the issue more accurately.

Looking forward to hearing from you! Keep up the great coding! 🚀
