### ISSUE TITLE
Adding background images to a classification dataset

### ISSUE THREAD

**Issue by obrhubr** [ultralytics/ultralytics#4479]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to train a `yolov8n-cls` model which is able to label images that are screenshots (from phones for example) as such. For this task I created a dataset which contains about 1200 screenshots from phones or other devices.

I want to also add "background" images that do not contain any screenshots to optimize the model performance in terms of false positives. Where would I put these images in my dataset folder?

```
screenshot_dataset/
      train/
           screenshot/
                  1.jpg
                  2.jpg
                  3.jpg
                  4.jpg
```

If I add them in a `background` folder, the confusion matrix produced by the validation script produces this wierd output, because the `background` images are not used as images without any classification but are used as if `background` was an actual class. This results in two columns and rows named "background":

![image](https://github.com/ultralytics/ultralytics/assets/65957631/29db8f7d-92d7-4ed5-b87e-a6c3684b84fd)

Thank you in advance for your help and thank you @glenn-jocher for your amazing work with YOLO which makes it really easy for amateurs to create impressive ML solutions :)

**Comment by glenn-jocher** [comment]
@obrhubr hello, and thank you for your kind words about YOLOv8. It's really the community and the team that propel the project forward! 

To address your question about the "background" images - in your current setup, these images are indeed interpreted as representing a separate class, hence the confusion matrix output you observed.

In the context of classification in YOLOv8, an image belongs to exactly one class. So, when you add those "background" images, they are assumed to represent a unique class which the model will attempt to recognize and distinguish from other classes.

For your specific use case, you would want to consider a binary classification: 'screenshot' or 'not screenshot'. It sounds like your aim is to have this 'background' classification act as a 'not screenshot' label. If this is the case, you can continue to label your 'background' as a separate class but always keep in mind that they will be treated as such throughout your training and validation. 

Remember that the model is learning to differentiate between these two classes, so if another, non-screenshot image is introduced that isn't similar to your 'background' set, the model might incorrectly classify it. So, you should ensure your 'background' images are representative of the range of images you expect the model to encounter that are not screenshots.

Thank you for choosing YOLOv8, and don't hesitate to reach out if you have additional concerns or questions!

**Comment by HZWhl** [comment]
Hello, shouldn't the "background" image that does not contain any screenshots be understood as a negative sample and directly generate a corresponding blank txt file for training?

https://github.com/AlexeyAB/darknet#how-to-improve-object-detection
![image](https://github.com/ultralytics/ultralytics/assets/101874810/b015b592-7151-4ede-81fb-6b23b03d20c4)

https://www.ccoderun.ca/programming/darknet_faq/#image_markup
![image](https://github.com/ultralytics/ultralytics/assets/101874810/2231ff5d-0f5b-4e97-a22b-53efb502955a)

https://stackoverflow.com/questions/66739675/i-do-not-know-where-to-put-my-empty-txt-file-for-no-objects-image
![image](https://github.com/ultralytics/ultralytics/assets/101874810/c0214240-b38b-4d91-ab75-41abbdc33ac5)

Maybe I'm wrong, anyway, looking forward to your answer, thanks

**Comment by glenn-jocher** [comment]
@HZWhl hello, thank you for your question!

With image classification tasks in YOLOv8, there isn't a native way to handle "background" or negative samples. The concept of a 'background' designation or 'negative sample' is foreign here, because the model assumes every image to either belong to a category or not. 

In YOLOv8, every single image is explicitly representative of a particular category upon which it is trained. Adding a 'background' category to your dataset actually means that 'background' is an inherent class of its own that the model is learning to predict. Therefore, with your 'background' category, the model will learn to detect that specific type of image rather than understand it as containing no instances of the 'screenshot' class. 

While the external references you've provided describe ways of handling empty classes or background images for other models or frameworks, that strategy would not be applicable for YOLOv8. 

The model you're training will essentially be optimized for a binary classification task – either 'screenshot' or 'background'. Ensure that the 'background' data captures the variety of images you expect to encounter that are not screenshots to improve model performance when encountering new 'background' or 'not screenshots' instances.

I hope this clarifies any confusion! Feel free to ask if you have any further questions.

**Comment by HZWhl** [comment]
@glenn-jocher Hello, thanks for your answer, actually I use yolov8 for broken wire detection of steel wire rope. The first picture below is a picture that contains broken wires, and the second picture below is a picture that does not contain broken wires. We want to add some pictures that do not contain broken wires to the training model data set to optimize the model performance in terms of false positives.
![0178](https://github.com/ultralytics/ultralytics/assets/101874810/f0f4b764-01ce-4998-b2ad-b25f18eac48f)
![509](https://github.com/ultralytics/ultralytics/assets/101874810/ec8bf07c-3be5-4e51-b91f-d013eb2cc3b4)

According to what you said above, when making the data set, should we label the two pictures mentioned above in this way? :
![image](https://github.com/ultralytics/ultralytics/assets/101874810/d09abdd2-1564-4655-bac0-0ccd3729b7a0)
![image](https://github.com/ultralytics/ultralytics/assets/101874810/612a5bc2-8ca7-4c5f-a105-1a9bdd3b1828)

In fact, before this discussion was initiated, we had already trained the model and used two different datasets to train the model. One was a dataset containing only broken wire images, and the other was a dataset containing both broken wire images and images without broken wires. But for images without broken wires, I did not make any annotations, but only generated blank txt files. In this case, the model trained on the data set that contains both broken wire pictures and pictures without broken wires does have a lower false positive rate. Can you help explain this? The following two pictures are the prediction results of the models trained using these two different data sets. At this time, the confidence of the two models is 0.4. However, the first model misreported wire breakage while the second model did not. It should be noted that this image itself does not contain broken wires, so only the model trained on the dataset of the broken wire image has false positives, while the model trained on the dataset without broken wire images and directly using a blank txt file has no false positives. 
![image](https://github.com/ultralytics/ultralytics/assets/101874810/6d35863b-b4df-4b61-9586-787a4c967edc)
![image](https://github.com/ultralytics/ultralytics/assets/101874810/78e0b523-790c-4dff-9158-f72bb97b7792)

This confuses me, because according to what you said above, even though our data set contains pictures without broken wires, since we create blank txt files for this type of pictures, we use this data set to train the model , the model will not improve very well, but the prediction results show that the performance of the model has indeed been improved

Looking forward to your reply, I would be very grateful if I could get your reply, thank you

**Comment by HZWhl** [comment]
@glenn-jocher  Hello, thanks for your answer, actually I use yolov8 for broken wire detection of steel wire rope. The first picture below is a picture that contains broken wires, and the second picture below is a picture that does not contain broken wires. We want to add some pictures that do not contain broken wires to the training model data set to optimize the model performance in terms of false positives.
![0178](https://github.com/ultralytics/ultralytics/assets/101874810/f0f4b764-01ce-4998-b2ad-b25f18eac48f)
![image](https://github.com/ultralytics/ultralytics/assets/101874810/29ab402f-14b5-4645-b66b-af309779c912)

According to what you said above, when making the data set, should we label the two pictures mentioned above in this way? :
![image](https://github.com/ultralytics/ultralytics/assets/101874810/d09abdd2-1564-4655-bac0-0ccd3729b7a0)
![image](https://github.com/ultralytics/ultralytics/assets/101874810/aacbc074-cf02-40dd-bda9-2d06247409c1)

In fact, before this discussion was initiated, we had already trained the model and used two different datasets to train the model. One was a dataset containing only broken wire images, and the other was a dataset containing both broken wire images and images without broken wires. But for images without broken wires, I did not make any annotations, but only generated blank txt files. In this case, the model trained on the data set that contains both broken wire pictures and pictures without broken wires does have a lower false positive rate. Can you help explain this? The following two pictures are the prediction results of the models trained using these two different data sets. At this time, the confidence of the two models is 0.4. However, the first model misreported wire breakage while the second model did not. It should be noted that this image itself does not contain broken wires, so only the model trained on the dataset of the broken wire image has false positives, while the model trained on the dataset without broken wire images and directly using a blank txt file has no false positives. 
![image](https://github.com/ultralytics/ultralytics/assets/101874810/6d35863b-b4df-4b61-9586-787a4c967edc)
![image](https://github.com/ultralytics/ultralytics/assets/101874810/78e0b523-790c-4dff-9158-f72bb97b7792)

This confuses me, because according to what you said above, even though our data set contains pictures without broken wires, since we create blank txt files for this type of pictures, we use this data set to train the model , the model will not improve very well, but the prediction results show that the performance of the model has indeed been improved

Looking forward to your reply, I would be very grateful if I could get your reply, thank you

**Comment by HZWhl** [comment]
@glenn-jocher @glenn-jocher  Hello, thanks for your answer, actually I use yolov8 for broken wire detection of steel wire rope. The first picture below is a image that contains broken wires, and the second image below is a image that does not contain broken wires. We want to add some imagess that do not contain broken wires to the training model data set to optimize the model performance in terms of false positives.
![0178](https://github.com/ultralytics/ultralytics/assets/101874810/f0f4b764-01ce-4998-b2ad-b25f18eac48f)
![4253](https://github.com/ultralytics/ultralytics/assets/101874810/c04c154b-440d-4c7d-b106-6d5daf250e18)




According to what you said above, when making the data set, should we label the two images mentioned above in this way? :


![image](https://github.com/ultralytics/ultralytics/assets/101874810/d09abdd2-1564-4655-bac0-0ccd3729b7a0)
![image](https://github.com/ultralytics/ultralytics/assets/101874810/aacbc074-cf02-40dd-bda9-2d06247409c1)




In fact, before this discussion was initiated, we had already trained the model and used two different datasets to train the model. One was a dataset containing only broken wire images, and the other was a dataset containing both broken wire images and images without broken wires. But for images without broken wires, I did not make any annotations, but only generated blank txt files. In this case, the model trained on the data set that contains both broken wire images and images without broken wires does have a lower false positive rate. Can you help explain this? The following two pictures are the prediction results of the models trained using these two different data sets. At this time, the confidence of the two models is 0.4. However, the first model misreported wire breakage while the second model did not. It should be noted that the image itself does not contain broken wires, that is to say, the model trained on the data set containing only broken wire images has false positives, while the model trained on the data set containing both broken wire images and no broken wire images has no false positives.
![image](https://github.com/ultralytics/ultralytics/assets/101874810/6d35863b-b4df-4b61-9586-787a4c967edc)
![image](https://github.com/ultralytics/ultralytics/assets/101874810/78e0b523-790c-4dff-9158-f72bb97b7792)

This confuses me, because according to what you said above, even though our data set contains images without broken wires, since we create blank txt files for this type of pictures, we use this data set to train the model , the model will not improve very well, but the prediction results show that the performance of the model has indeed been improved

Looking forward to your reply, I would be very grateful if I could get your reply, thank you

**Comment by glenn-jocher** [comment]
@HZWhl hello, thank you for your detailed question! It's clear you're putting a lot of thought into optimizing your model training.

In YOLOv8, it's correct that an image is understood to belong to exactly one class. However, it's not accurate to interpret an image with a blank txt file as 'background' or 'negative'. The model does not inherently understand the concept of 'negative samples'—every image is representative of a particular class. In your case, the two classes are 'broken wire' and 'no broken wire'.

So yes, you could annotate your dataset as you described:

- The image with broken wires will have a corresponding .txt file with bounding box(es) and corresponding class (i.e., 'broken wire').
- The image without broken wires will have a blank .txt file, implicitly assigning it to the 'no broken wire' class.

As for the difference you've observed in false positives between your two trained models, it makes sense. When you trained the first model only with 'broken wire' images, the model was not exposed to examples of 'non-broken wire' images, which likely made it over-optimize towards detecting broken wires.

The second model, trained with both 'broken wire' and 'non-broken wire' images, got a more balanced view. Even though 'non-broken wire' images have blank .txt files, they still participate in the training process and help the model get a sense of what absence of a 'broken wire' looks like. This would naturally lead to a reduced rate of false positives.

I hope this helps further clarify things for you! Please feel free to continue the discussion if you have more questions.

**Comment by HZWhl** [comment]
@glenn-jocher hello, hanks for your answer, so how do you think I should make a corresponding txt file for a image that does not contain broken wires? Should I directly use a blank txt file, or mark it as follows and then export the txt file?
![Snipaste_2023-08-26_22-26-06](https://github.com/ultralytics/ultralytics/assets/101874810/a0902cd4-2574-4703-850a-ce45eb01424a)

Looking forward to your reply, thank you

**Comment by glenn-jocher** [comment]
@HZWhl Hello, and thank you for your follow-up question. For a wire image that does not contain any broken wires (thus belonging to the 'no broken wire' class), a blank text file should suffice. This essentially assigns the image to the 'no broken wire' class without any specific bounding box annotations. The neural network indeed learns from these 'negative' examples, helping to reduce the rate of false positives as it learns what a 'non-broken wire' image looks like. I hope this clarifies things further for you. Feel free to ask more questions if needed!

**Comment by HZWhl** [comment]
@glenn-jocher Hello, thanks for your answer, now I know how to make my own dataset. Thank you for providing us with such a user-friendly yolov8, I will continue to follow your team and look forward to your surprises. You guys are amazing!!!!

**Comment by glenn-jocher** [comment]
@HZWhl Hello, thank you for your kind words! We're delighted to hear that you find YOLOv8 user-friendly and that it's helping you with your work. It's our goal to create tools that can be used effectively by the community, and your feedback is greatly appreciated. We're excited to continue improving and expanding YOLOv8, and we're glad to have you with us on this journey. If you have any more questions or need assistance in the future, don't hesitate to reach out. Thanks for your support!

**Comment by YunmeiHuanghi** [comment]
Hi, Glenn, thank you for sharing this great model with us. I have a question about adding negative samples without a bounding box. What format for these negative sample images that don't have my target classes?  Should I generate txt file without box location information but contain class Id ? Thank you for your attention.

**Comment by glenn-jocher** [comment]
@YunmeiHuanghi hello, thanks for asking this question. For images that don't have any instances of your target class (i.e., negative samples), you should still generate a corresponding text file like you would for other images; however, you leave the text file completely empty. This indicates to YOLOv8 that there are no target objects present in the image. You do not need to include any class ID, as it's understood that the absence of bounding box information translates to the absence of target class instances in the image. I hope this clarifies things for you!

**Comment by YunmeiHuanghi** [comment]
Thank you so much! I just added background images to my training! I appreciate your patience! Have a great weekend! @glenn-jocher

**Comment by jocoskragnus** [comment]
I have 2 classes that I want to segment - butterflies and squirrels. I want to add to my custom dataset some random images cca 80 of them split into 60/20 for training and validation. 
Annotations I have are in .json format and I use labelme2yolo to convert into the yolo format. My question would be the following - how to annotate these images with background so when I train the model these images get recognized as backgrounds. I'm using yolov8 model.

**Comment by glenn-jocher** [comment]
@jocoskragnus in YOLOv8, 'background' is not a specific class, but rather occurs when none of the classes are present in an image. If an image is a 'background' image, it should not contain any of your classes of interest (in your case, squirrels and butterflies). 

To annotate these images, you would simply include them in your dataset with a corresponding annotation file that is left empty. This will indicate to the model that none of the classes are present, effectively labeling the image as a 'background' image. 

When you run your `labelme2yolo` conversion, ensure these 'background' images are included in the input with their corresponding (empty) .json files. After conversion, you should end up with an empty .txt file for each 'background' image in your dataset. During training, these images will be used as negative examples, helping the model to discern between images with class instances (squirrels, butterflies) and those without (background).

**Comment by cobaltautomationdev** [comment]
> @jocoskragnus in YOLOv8, 'background' is not a specific class, but rather occurs when none of the classes are present in an image. If an image is a 'background' image, it should not contain any of your classes of interest (in your case, squirrels and butterflies).
> 
> To annotate these images, you would simply include them in your dataset with a corresponding annotation file that is left empty. This will indicate to the model that none of the classes are present, effectively labeling the image as a 'background' image.
> 
> When you run your `labelme2yolo` conversion, ensure these 'background' images are included in the input with their corresponding (empty) .json files. After conversion, you should end up with an empty .txt file for each 'background' image in your dataset. During training, these images will be used as negative examples, helping the model to discern between images with class instances (squirrels, butterflies) and those without (background).

You don't need to create an empty .txt file for the background image. Just placing the image in the images folder should be sufficient.

Background images. Background images are images with no objects that are added to a dataset to reduce False Positives (FP). We recommend about 0-10% background images to help reduce FPs (COCO has 1000 background images for reference, 1% of the total). No labels are required for background images.

**Comment by raduprv** [comment]
> In YOLOv8, it's correct that an image is understood to belong to exactly one class. However, it's not accurate to interpret an image with a blank txt file as 'background' or 'negative'. The model does not inherently understand the concept of 'negative samples'—every image is representative of a particular class. In your case, the two classes are 'broken wire' and 'no broken wire'.

Thanks for all your work!
When you say that an image belongs to one class, do you mean a bounding box, or an image? For example, can I have 3 classes defined in one image?

**Comment by glenn-jocher** [comment]
Thank you for your question! In YOLOv8, an **image** can contain multiple bounding boxes, each associated with different classes. So, yes, you can define and annotate multiple classes (e.g., 3 classes) in a single image by specifying bounding boxes for each object and assigning the appropriate class ID. Let me know if you need further clarification!
