### ISSUE TITLE
Question on pose model

### ISSUE THREAD

**Issue by Somyarani13** [ultralytics/ultralytics#4488]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

@glenn-jocher Can you please clear a doubt?

Is the yolov8 pose-model based on a hybrid approach or it is a top-down approach?
By hybrid I mean mix of top-down and bottom-up approach?

Also if I pass a frame containing multiple-person to the yolo-pose model and the frame already has the information of the detected boxes, then when this frame is passed to the model so will the model again detect the objects(person) and then give the keypoints? Or it will directly give the keypoints based on the prior detection that I have?

If "this frame is passed to the model so will the model again detect the objects(person) and then give the keypoints" is True, can you tell me if there's a way to bypass the object detection from your model and use my own person detector and then get the keypoints from the olov8 pose model?

Please let me know if this is possible and how can it be done?

Thanks in advance

**Comment by glenn-jocher** [comment]
@Somyarani13 hello, thanks for reaching out with your questions!

Firstly, regarding your question about whether the YOLOv8 pose model is a hybrid, top-down, or bottom-up approach. YOLOv8 pose estimation model works on a top-down approach, which means it first detects individuals in the image (detect phase), and then it estimates the pose in each detection.

In response to your question about passing a frame with detected boxes information. The YOLOv8 pose model conducts its own object detection, so even if your frame has pre-existing bounding box information, the model will perform object detection on its own before proceeding to keypoint estimation.

However, adding the option to bypass the included object detection could be a valuable feature. As of now, the YOLOv8 pose model doesn't directly support this functionality, but it's a pretty nice idea for a custom modification. Implementing this feature would involve changes in the code to skip the detection step of the model and directly input the bounding box information that you have.

I hope this clarifies your doubts! Let me know if you have any other questions.

**Comment by Somyarani13** [comment]
@glenn-jocher Thanks for the detailed answer. I need to ask a few question on bypass the included object detection. If you could guide a little bit on where or which files we need to make changes in the code to skip the detection step of the model would be helpful.
Looking forward for your reply. Thanks

**Comment by Somyarani13** [comment]
@glenn-jocher Also, will that mean that we need to train the keypoint pose model again? Because currently there's only a single weight for pose and to my knowledge it has the information of person detection and keypoint estimation.
So wanted to understand is there a way from inference point of view(without any training involved can we add our custom bbox detection). If yes then how(code level changes needed to understand) If no then do we need to train the keypoint and generate the new weights again?

**Comment by glenn-jocher** [comment]
@Somyarani13 Good question! To bypass the included object detection, you don't necessarily need to retrain the entire model. Since the model performs detection and pose estimation in separate stages, you can skip the detection phase and directly supply your own bounding box information for the pose estimation phase. This, however, requires substantial code modifications.

You would need to review the detection part of the pipeline and replace it with your custom bounding box information. However, keep in mind that you need to ensure that your bounding box information is in the format expected by the pose estimation part of the pipeline.

In terms of the weight files, you can still continue to use the pre-trained weights for the pose estimation. Even though the weights file has information for both detection and pose estimation parts, when you bypass the detection part, only the pose estimation weights would be applied.

Please remember that this requires a substantial understanding of the code base and could be a complex task. If you're confident in making these changes to the code, this could potentially be a great way to incorporate your own detections into the pose estimation model.

**Comment by Somyarani13** [comment]
Hello @glenn-jocher Could you also tell me if there's batch-level processing available for the objects for pose-estimation and if it is how can we do it and how can we measure the inference time only for the forward pass of the model?
Thanks in advance

**Comment by glenn-jocher** [comment]
Hello @Somyarani13! Yes, YOLOv8 is capable of handling batch-level processing. This means that you can input multiple frames at once and the model will process them all together, which is much more efficient than passing them one by one individually.

For this, you would have to modify your input to the model so that it forms a batch. Typically in PyTorch, a batch is simply a 4-dimensional tensor in the form (N, C, H, W), where N is the number of images, C is the number of channels (usually 3 for RGB images), and H and W are the height and width of the images. All images must be of the same size for batching.

Regarding measuring the inference time for the forward pass of the model, you can do this using Python's built-in `time` module. You would first record the time immediately before performing the forward pass using `start = time.time()`, then again immediately after the forward pass with `end = time.time()`. The difference between the end and start times `duration = end - start` is the time taken for the forward pass.

Bear in mind that the time measured in this way includes the time taken for both the pose estimation and the object detection parts of the model.

I hope that helps! Let me know if you have any further questions.

**Comment by Somyarani13** [comment]
Hello @glenn-jocher Could you point me to an example for batch-level processing for multiple frames for pose-estimation?
Also, instead of passing an image can it accept a batch of tensors?

And for the time-estimation of the forward-pass where can I find the forward pass function in which file?

If also you could clear this doubt - 
![pose](https://github.com/ultralytics/ultralytics/assets/41571856/36d005a3-4f36-4551-a6e0-a5d376524fda)
This time on the right side 58.0ms does it include the time only for inference or its preprocess+infer+poseprocess.
Thanks

**Comment by Somyarani13** [comment]
Hey let me also know that if I want to re-train the pose-estimation on my own dataset instead of using 17 keypoints can we use 7-8 keypoints and train it on ou own number of keypoints instead of 17?

**Comment by Somyarani13** [comment]
@glenn-jocher 
Thanks for the quickly reply. Can you even let me know if I want to train it on 7-8 keypoints for person then can we use the present pose model weights  or do we need to train it from scratch?

**Comment by glenn-jocher** [comment]
Hello @Somyarani13,

The current pose model weights are trained specifically for 17 keypoints. If you decide to adjust the architecture to accommodate a different number of keypoints (like 7-8), these weights will not be directly compatible with your adjusted model. 

In such a case, you will likely need to train the model from scratch or you could possibly try using a checkpoint from an earlier stage of the original training process before the model specialized towards 17 keypoints. However, keep in mind that this approach might not provide the best results since these weights were not trained with the specific number of keypoints you are interested in.

Overall, adjusting the number of keypoints and training the model accurately will require careful fine-tuning. Hope this clarifies things for you!
