### ISSUE TITLE
Detecting objects on multiple RTSP streams error

### ISSUE THREAD

**Issue by deyn4067** [ultralytics/ultralytics#4493]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I want to give some camera streams to the model through the network. I went according to the user's documents and questions, and after I created the camera address list and gave it to the model, it gives me an error. If there is only one camera address in the list, it runs fine, but if there is more than one camera in it, it immediately stops after a few frames and gives the following error! What is the reason for this error? please guide me.

>sources.streams:
```python
rtsp://192.168.1.2:8080/h264_pcm.sdp
rtsp://192.168.1.3:8080/h264_pcm.sdp
``` 

>a.py:
```python
from ultralytics import YOLO

model = YOLO("yolov8n.pt")
#results = model("sources.streams", stream=True, show=True)
results = model("sources.streams", stream=True, show=True)
for result in results:
    boxes = result.boxes  # Boxes object for bbox outputs
    masks = result.masks  # Masks object for segmentation masks outputs
    keypoints = result.keypoints  # Keypoints object for pose outputs
    probs = result.probs  # Probs object for classification outputs
``` 

>result:
```shell
1/2: rtsp://192.168.1.2:8080/h264_pcm.sdp... Success  (inf frames of shape 640x480 at 29.58 FPS)
2/2: rtsp://192.168.1.3:8080/h264_pcm.sdp... Success  (inf frames of shape 640x480 at 9.08 FPS)

0: 480x640 1 remote, 1 cell phone, 1: 480x640 1 mouse, 237.6ms
0: 480x640 1 mouse, 1: 480x640 1 cake, 1 remote, 273.2ms
0: 480x640 1 remote, 1: 480x640 1 mouse, 216.4ms
0: 480x640 1 remote, 1: 480x640 1 mouse, 240.4ms
Traceback (most recent call last):
  File "F:\***\y8\ultralytics\a.py", line 6, in <module>
    for result in results:
  File "F:\***\env\Lib\site-packages\torch\utils\_contextlib.py", line 56, in generator_context      
    response = gen.send(request)
               ^^^^^^^^^^^^^^^^^
  File "F:\***\y8\ultralytics\ultralytics\engine\predictor.py", line 242, in stream_inference     
    for batch in self.dataset:
  File "F:\***\y8\ultralytics\ultralytics\data\loaders.py", line 112, in __next__
    return self.sources, [x.pop(0) for x in self.imgs], None, ''
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\***\y8\ultralytics\ultralytics\data\loaders.py", line 112, in <listcomp>
    return self.sources, [x.pop(0) for x in self.imgs], None, ''
                          ^^^^^^^^
IndexError: pop from empty list
```

**Comment by glenn-jocher** [comment]
@deyn4067 hello, thank you for using Ultralytics YOLOv8 and for raising this issue. 

Based on your detailed error message and code provided, it seems that your real-time streaming protocol (RTSP) streams might not be synchronized. This can result in one of the streams finishing faster than the other, and which is why you see this `pop from empty list` error message -- it's trying to fetch frames from a stream that already ended.

For your use case of processing multiple streams, consider managing each stream in separate threads or processes. This way, each video feed from the different cameras will be processed independently, and if one ends prematurely, it doesn't affect the processing of the others. This approach also has the advantage of potentially improving overall processing speed as the frames from different cameras can be processed simultaneously.

Please note that handling multiple streams could potentially increase the load on your system's resources, you may need to consider hardware capabilities (like CPU, GPU, and memory usage) depending on the number of streams you want to process simultaneously. 

Hope this helps! If you have any further questions, feel free to ask. We're here to help!

**Comment by glenn-jocher** [comment]
Hello @ShoaibSajid, 

It seems like you are encountering an issue due to the time differences in receiving frames from different sources when reading from multiple sources.

As you pointed out, the problem arises when the code tries to remove the oldest frame for each source simultaneously. In scenarios where there are delays in getting the next frame from a source, the list for that source becomes empty, thus leading to errors.

Your workaround of only popping an image if there are more than one images in the list, or emptying the entire array of images and waiting for the new frames each time, seems like a viable solution. By employing this method, you can ensure that each source has only one frame after the `__next__` loop in loaders.py.

Alternatively, you can modify the `__next__` function in such a way that it waits until a frame is available in each buffer and get and remove the next frame from the images buffer only when all the threads are alive.

It's quite commendable that you are further improving the effectiveness of the YOLOv8 model with such customizations. Keep up the good work and happy coding!
