### ISSUE TITLE
How can i get result from model without load and fuse model 

### ISSUE THREAD

**Issue by aTunass** [ultralytics/ultralytics#450]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have read some issues like my matter, and i see issue #416 and i tried code like this and it's still fuse model in loop 'while True'. Did i do somethings wrong?
Here's my code
![image](https://user-images.githubusercontent.com/119738823/212945516-cf044a2a-685d-4b42-a263-1a143e49f9f5.png)
and my terminal:
![image](https://user-images.githubusercontent.com/119738823/212945761-dcf01028-08a7-44f2-a881-60f55e53635e.png)

**Comment by glenn-jocher** [comment]
@aTunass 👋 hi, thanks for letting us know about this possible problem with YOLOv8 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with YOLOv8 GitHub repo, and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved.
- ✅ **Unmodified** – Your problem must be reproducible using official YOLOv8 code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃
