### ISSUE TITLE
Too many open files error when tried to train multiple models in the same python script. 

### ISSUE THREAD

**Issue by zadobudak** [ultralytics/ultralytics#4500]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

For research I am trying to train multiple models with a python script however I came across with an OSError. 
this is the part I use for the training. 

Error message can be found on the file.
[Errormessage.txt](https://github.com/ultralytics/ultralytics/files/12412821/Errormessage.txt)

### Environment

-Using the official Ultralytics image on docker 
-with rtx 4090 on vast.ai 
![image](https://github.com/ultralytics/ultralytics/assets/63165528/e7605c5b-ec89-4e72-ba73-62fa7fbf1405)

### Minimal Reproducible Example

```
for yaml_file in yaml_files:
    model = YOLO("yolov8n.yaml")

    model_name = os.path.basename(os.path.dirname(yaml_file))
    print(model_name)

    results = model.train(
        data=yaml_file,
        epochs=epochs,
        imgsz=imgsz,
        device=devices,
        name=model_name,
        project=project_name,
        hsv_h=0.0,
        hsv_s=0.0,
        hsv_v=0.0,
        cache=True,
        pretrained=False,
        batch=batch_size,
        close_mosaic=20,
        patience=0,
        mosaic=0.2,
        workers=workers,
        exist_ok=True,
    )
    test = model.val(data=yaml_file, split="test", name=model_name + "_test")

    old_experiment = comet_ml.get_global_experiment()
    experiment = comet_ml.ExistingExperiment(previous_experiment=old_experiment.id)
    experiment.set_name(model_name)
    experiment.end()
```

### Additional

I think the reason of the problem not being sure about it is the files being opened in the background but not getting closed. 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@zadobudak 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. I'm not able to reproduce this. Is this reproducible for you, i.e. if you run the same command twice do you get the same error twice?

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
