### ISSUE TITLE
Graphs missing when training with early stopping

### ISSUE THREAD

**Issue by JDups** [ultralytics/ultralytics#4501]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

If the patience argument is used and early stopping gets triggered results.png is the only graph saved, no other graphs appear to be generated. The confusion matrix and val_batch images are also missing, the only images present besides results.png are the train_batch images.

Output from training with no early stopping:
![image](https://github.com/ultralytics/ultralytics/assets/116138053/2b997e20-ae69-4388-b2ac-b3ce54afd89f)
Output from training with early stopping:
![image](https://github.com/ultralytics/ultralytics/assets/116138053/c49fdb59-3f5e-4a29-877d-a52cfc008fe5)

The results.png are also not quite the same in both cases, with early stopping they have the default matplotlib style, without they have the seaborn default style.

results.png without early stopping:
![results(1)](https://github.com/ultralytics/ultralytics/assets/116138053/c2e9fc0f-ef6b-488c-a433-c381ec19f18f)
results.png with early stopping:
![results](https://github.com/ultralytics/ultralytics/assets/116138053/d692e0b8-4119-4d5c-871c-85dadacc9483)

This behavior doesn't seem to be outlined in https://docs.ultralytics.com/modes/train/#arguments so I'm assuming it's unintended.

### Environment

- Ultralytics YOLOv8.0.28 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (Tesla T4, 15102MiB)
- Jupyter notebook run on Google Colab

### Minimal Reproducible Example

```
!yolo task=segment mode=train model=yolov8s-seg.pt data={dataset.location}/data.yaml epochs=100  imgsz=640

!yolo task=segment mode=train model=yolov8s-seg.pt data={dataset.location}/data.yaml epochs=100 patience=2  imgsz=640
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@JDups I ran two trainings and observe the same exact output plots irrespective of early stopping:

```
yolo train epochs=10
yolo train epochs=10 patience=1  # stops on epoch 3
```

<img width="472" alt="Screenshot 2023-08-22 at 23 52 22" src="https://github.com/ultralytics/ultralytics/assets/26833433/ad61193c-2301-49ff-86f6-44b150ef7ef6">

**Comment by glenn-jocher** [comment]
@JDups same for segmentation. All plots are completed correctly:

<img width="1359" alt="Screenshot 2023-08-22 at 23 54 27" src="https://github.com/ultralytics/ultralytics/assets/26833433/75a2c4d4-e7e1-4d0d-9187-581e8f11452e">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by JDups** [comment]
@glenn-jocher thank you for the very quick response!

In my attempts to further control for every variable to better reproduce the issue I quickly realized I was not running the latest 8.0.159 version of ultralytics. Updating to it resolved my issues.

My apologies for not noticing something so obvious. And thanks again

**Comment by glenn-jocher** [comment]
Not a problem at all, @JDups! I'm glad to hear that updating to the latest version of ultralytics resolved your issue. Don't hesitate to reach out if you encounter any further issues or have additional questions. We appreciate your use and support of YOLOv8. Happy coding!
