### ISSUE TITLE
Resize image needs a clearified way for best results

### ISSUE THREAD

**Issue by marcimarc1** [ultralytics/ultralytics#4510]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

In my recent work, I used yolov8 to detect specific objects. 

While the original image size is at 4k, I trained yolo on 640 images. 

This is sufficient in training and inference quality (for my application). 

During inference, I realized that the model produces different results. 

This is due to the fact that resizing is done differently. You can check this by looking into the predictions of a random image. 

a minimal reproducible snipped of code would be : 

```
img = cv2.imread("img.jpg")  #should be larger than 640x640
model = YOLO("path/to/weights")

results1 = model(cv2.resize(img, (640,640), interpolation=cv2.INTER_AREA))[0]
results2 = model(cv2.resize(img, (640,640), interpolation=cv2.INTER_LINEAR))[0]
```

we can see that `results1 != results2`. 

A feature would be to either make this visible in the inference documentation. Or to use the `INTER_LINEAR` flag as default to cope with std. opencv.

### Use case

I stumbled upon this, due to the fact that my Yolo model is embedded in a large pipeline and produced worse results.

This is due to the fact that the images get preprocessed for different models (but resizing was a shared preprocessing step and the opencv resize has `INTER_LINEAR` as its standard method, while Yolo uses the `INTER_AREA`. 

### Additional

I found this solution, testing PR #2612

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@marcimarc1 hi there,

Thanks for bringing up this issue. When it comes to resizing images in computer vision applications, the method of interpolation can indeed affect the results of the model's operation. There's a trade-off between the quality of resizing and computational cost.

In this case, YOLOv8 is using INTER_AREA interpolation for resizing because it's generally a good choice for downsampling. This method may give better results when reducing the image size, and it’s considerably fast compared to other methods. 

However, as you've noticed, a difference can arise when a different interpolation method, such as INTER_LINEAR, is used, which is the default for OpenCV resize. It's important to maintain consistency in the preprocessing steps, especially when a model is part of a larger pipeline, like in your case.

That said, this is definitely a valuable insight and we appreciate your willing to submit a PR! In terms of where to go from here, it could be beneficial to include a note in the documentation indicating the interpolation method used by YOLOv8 during inference. Perhaps specifying that the INTER_AREA interpolation is used as default and that users should be aware of this when integrating the model into larger pipelines would be helpful. 

Again, thank you for your input. The YOLO community always benefits from active contributors like yourself. I hope this clears things up for you, and I’m looking forward to seeing your PR!

Best,
Glenn Jocher
