### ISSUE TITLE
Yolov8 issue when using streamlit

### ISSUE THREAD

**Issue by MinhHoan147** [ultralytics/ultralytics#4511]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Integrations

### Bug

Traceback (most recent call last):                                                                                                                 
  File "C:\Users\User\Desktop\streamlit-yolo-main\venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)                                                                                                                    
  File "C:\Users\User\Desktop\streamlit-yolo-main\app.py", line 89, in <module>                                                                    
    main()                                                                                                                                         
  File "C:\Users\User\Desktop\streamlit-yolo-main\app.py", line 83, in main                                                                        
    clothing_images_classification()                                                                                                               
  File "C:\Users\User\Desktop\streamlit-yolo-main\app.py", line 44, in clothing_images_classification                                              
    results = model(img)
              ^^^^^^^^^^
  File "C:\Users\User\Desktop\streamlit-yolo-main\venv\Lib\site-packages\ultralytics\engine\model.py", line 98, in __call__
    return self.predict(source, stream, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\streamlit-yolo-main\venv\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
  File "C:\Users\User\Desktop\streamlit-yolo-main\venv\Lib\site-packages\ultralytics\models\yolo\classify\predict.py", line 35, in preprocess
    img = torch.stack([self.transforms(im) for im in img], dim=0)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\streamlit-yolo-main\venv\Lib\site-packages\ultralytics\models\yolo\classify\predict.py", line 35, in <listcomp>
    img = torch.stack([self.transforms(im) for im in img], dim=0)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\streamlit-yolo-main\venv\Lib\site-packages\torchvision\transforms\transforms.py", line 95, in __call__
    img = t(img)
          ^^^^^^
ValueError: too many values to unpack (expected 2)

### Environment

Python 3.11
OS: Windows 10
Pre-trained model: YOLOv8x-cls

### Minimal Reproducible Example

model = YOLO('./runs/classify/train/weights/best.pt')['classify']  # load a custom model
results = model.predict('./test_images/shirt-test-5.jpg')  # predict on an image
labels_dict = results[0].names
probs = results[0].probs.data.tolist()
print(labels_dict[np.argmax(probs)])

### Additional

I load my model into streamlit, then predict the image and get the following error: ValueError: too many values ​​to unpack (expected 2) - The error occurred in the line of code: results = model(img). I tried running it on jupyter notebook and it works fine, but I get an error when using streamlit. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MinhHoan147 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. Your usage is incorrect, but after I fix it I'm unable to reproduce any issues:

```python
from ultralytics import YOLO
import numpy as np

model = YOLO('yolov8n-cls.pt') # load a custom model
results = model.predict('ultralytics/assets/bus.jpg') # predict on an image
labels_dict = results[0].names
probs = results[0].probs.data.tolist()
print(labels_dict[np.argmax(probs)])

# Returns
image 1/1 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/bus.jpg: 224x224 minibus 0.47, police_van 0.25, ambulance 0.05, recreational_vehicle 0.04, bullet_train 0.02, 7.3ms
Speed: 0.7ms preprocess, 7.3ms inference, 0.0ms postprocess per image at shape (1, 3, 224, 224)
minibus
```


We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by devashish-bhake** [comment]
In my testing when I used @glenn-jocher 's given code, I found to have the same issue persisting. It still gives an error saying that there are too many values to unpack which I am unable to understand why.

**Comment by glenn-jocher** [comment]
@devashish-bhake it seems like there might be a misunderstanding in how the results are unpacked from the model's `predict()` method, especially since the error you are encountering is related to unpacking too many values.

When the model makes predictions, the `predict()` method returns an object that needs to be properly interpreted. In the context of a classification task, you should ensure that you are accessing the predictions correctly, typically without trying to unpack them into more components than what the method returns.

The message "too many values to unpack" usually indicates that a function or method is returning fewer elements than you are trying to assign. With YOLOv8's classification task, the method would return a `Predictions` object containing the labels and probabilities, which you can access using the appropriate attributes.

For troubleshooting this issue within a Streamlit application, please make sure that:
1. The model is loaded correctly as a classification model.
2. The image or images you are passing to the `predict()` method are properly formatted and preprocessed.
3. You are using the returned `Predictions` object correctly, accessing its `names` and `probs` attributes to get the predicted labels and probabilities, respectively.

To further debug this issue, consider doing the following:
- Double-check the Streamlit version compatibility with the Ultralytics YOLOv8 library.
- Investigate any discrepancies in the environment between your Jupyter notebook (where it works) and Streamlit (where it does not).

Since the exact problem situation is not clear without the specific code, these are general recommendations. If the issue persists after following the suggestions, please consider creating a new Github issue with a minimal, complete, and reproducible example of the code that's causing the problem, ensuring it is a current and unmodified version of the Ultralytics code.

It's important to provide the correct context and detailed information about the issue to diagnose the problem effectively. Thank you for reaching out and helping us to maintain the quality and usability of YOLOv8.
