### ISSUE TITLE
Inference is not possible for models converted from python to onnx. log_string += f"{n} {self.names[int(c)]}{'s' * (n > 1)} 

### ISSUE THREAD

**Issue by haaaaak** [ultralytics/ultralytics#4528]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\AI\Anaconda3\envs\yolov8seg\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\AI\Anaconda3\envs\yolov8seg\lib\site-packages\ultralytics\yolo\engine\model.py", line 255, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "C:\Users\AI\Anaconda3\envs\yolov8seg\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 195, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "C:\Users\AI\Anaconda3\envs\yolov8seg\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\Users\AI\Anaconda3\envs\yolov8seg\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 270, in stream_inference
    s += self.write_results(i, self.results, (p, im, im0))
  File "C:\Users\AI\Anaconda3\envs\yolov8seg\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 166, in write_results
    log_string += result.verbose()
  File "C:\Users\AI\Anaconda3\envs\yolov8seg\lib\site-packages\ultralytics\yolo\engine\results.py", line 271, in verbose
    log_string += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, "
KeyError: 15

### Environment

- YOLOv8
- Pytorch 2.1.0
- Python 3.8.17

### Minimal Reproducible Example

examples/YOLOv8-ONNXRuntime/main.py

ln9:
```
CLASSES = yaml_load(check_yaml('coco128.yaml'))['names']
```
->
```
CLASSES = yaml_load(check_yaml('data.yaml'))['names']
```

"data.yaml" is my custom dataset yaml.

ln224:       
```
output_image = detection.main()
cv2.namedWindow('Output', cv2.WINDOW_NORMAL)
cv2.imshow('Output', output_image)

# Wait for a key press to exit
cv2.waitKey(0)
```

->    
```
output_image = detection.main()
cv2.imwrite('test.png', output_image)
```

### Additional

Hi I converted my learning model saved as a pt extension to onnx, and I ran main.py on YOLOv8-ONNXRuntime to see if this onnx model was saved properly.

I modified the 'coco128.yaml' of self.classes = yaml_load(check_yaml('coco128.yaml')[names'] to my custom dataset yaml, 'data.yaml' and ran the code, but the error below occurred.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\AI\Anaconda3\envs\yolov8seg\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\AI\Anaconda3\envs\yolov8seg\lib\site-packages\ultralytics\yolo\engine\model.py", line 255, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "C:\Users\AI\Anaconda3\envs\yolov8seg\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 195, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "C:\Users\AI\Anaconda3\envs\yolov8seg\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\Users\AI\Anaconda3\envs\yolov8seg\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 270, in stream_inference
    s += self.write_results(i, self.results, (p, im, im0))
  File "C:\Users\AI\Anaconda3\envs\yolov8seg\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 166, in write_results
    log_string += result.verbose()
  File "C:\Users\AI\Anaconda3\envs\yolov8seg\lib\site-packages\ultralytics\yolo\engine\results.py", line 271, in verbose
    log_string += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, "
KeyError: 15

I definitely trained with the same number of classes in the yaml file. Why did this error happen?

How can I check the correct results? Please check and reply. Thank you.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. ONNX export and inference works correctly:

<img width="1229" alt="Screenshot 2023-08-24 at 03 14 43" src="https://github.com/ultralytics/ultralytics/assets/26833433/afcacbe5-e5c8-4885-b667-4687c27889f7">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by haaaaak** [comment]
Hello! Thank you very much for your quick reply.

As you stated, I was able to get the results normally when I ran it through the CLI. Thank you so much. 😂😂

But I have one question. Why did the above error occur with the method I tried? Is the approach wrong in the first place?

**Comment by haaaaak** [comment]
> Member

Hello! Thank you very much for your quick reply.

As you stated, I was able to get the results normally when I ran it through the CLI. Thank you so much. 😂😂

But I have one question. Why did the above error occur with the method I tried? Is the approach wrong in the first place?

**Comment by glenn-jocher** [comment]
@haaaaak hello!

Glad to hear that running the model through the CLI was successful!

Regarding your question, the error message `KeyError: 15` suggests that the script tried to access class 15 of the object categories, but it wasn't found. Remember that Python index start from 0, so if you have 15 classes, indices would run from 0 to 14, hence, an attempt to find class 15 would fail.

This error can occur due to different reasons, like a mismatch between the classes defined in your 'data.yaml' file and the actual outputs produced by the model. Please ensure that the 'names' field in your 'data.yaml' file matches the classes that the model was trained on.

Hope that helps! Let us know if you have more questions.

**Comment by majnas** [comment]
I have same problem when using the exported .pt to openvino_model or .onnx model.
the original pytorch wieght works fine. but non of openvino and onnx models works.

**Comment by glenn-jocher** [comment]
Hello @majnas,

Thank you for reaching out and sharing your experience.

To assist you effectively, could you please provide a minimal, reproducible example of the code you're using to export and run inference with the OpenVINO and ONNX models? This will help us better understand the issue and investigate a solution. You can find guidelines for creating a minimal, reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest versions of `torch` and `ultralytics`. You can update your packages with the following commands:

```bash
pip install --upgrade torch ultralytics
```

Once you've updated and provided the reproducible example, we'll be able to dive deeper into the issue.

Thank you for your cooperation! 😊

**Comment by ChrisAmm** [comment]
Any updates on this? Exporting a custom pose model is not working.

When i export yolov8n-pose.pt with the following settings: 

from ultralytics import YOLO

# Load a pretrained YOLOv8n model
model = YOLO("yolov8n-pose.pt")

model.export(format="onnx", imgsz=480, int8=False, opset=9)

The models runs on a 480p image.

When i export my custom model with the same code, i get the following error:

AppData\Local\Programs\Python\Python312\Lib\site-packages\ultralytics\engine\results.py", line 663, in verbose
    log_string += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, "
                         ~~~~~~~~~~^^^^^^^^
KeyError: 1

My custom models work as expected in pt, for single class and dual class. None of the ONNX exports are working using ultralytics. Tried opset 9 and opset 12 for compatibility

Using onnxruntime, in python, Tensor Output seems to follow expected format: Cx, Cy, W, H, confidence per class, Keypoint x,y,conf, but model not functioning as expected (incorrect detections).

**Comment by glenn-jocher** [comment]
It seems like the issue might be related to class indexing in your custom model. Ensure that your 'data.yaml' file correctly lists all class names and matches the model's training configuration. If the problem persists, consider checking the ONNX model's output to verify that class indices align with your expectations.

**Comment by ChrisAmm** [comment]
Thanks glenn-jocher (why no caps?). 
Adding classes: `results = model(source, show=True, imgsz=480, classes=(0,1))` prevents the model from crashing while loading, but it is not detecting. 
python code with Onnxruntime detects fine with the exported onnx models, both with opset 9 and opset 12. Could the problem be with the way ultralytics handles the models? I could not find a way to specify that the task is "pose" during inference...

**Comment by glenn-jocher** [comment]
Thank you for your feedback. It seems like the issue might be related to specifying the task. Ensure you're using the correct model type for pose tasks. If the ONNX model works with `onnxruntime`, the issue might be specific to how the task is set in Ultralytics. Double-check that the model is correctly loaded as a pose model during inference.
