### ISSUE TITLE
Generated engine file has less inference speed in Nvidia

### ISSUE THREAD

**Issue by Manueljohnson063** [ultralytics/ultralytics#4534]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

1.I have trained yolov8 segmentation with 100 epochs and generated the *.pt model using the below
`yolo task=segment  mode=train epochs=100  data=dataset.yaml` 

2.I need to run it on jetson xavier so i  convert the .pt model to .engine using the code below
`from ultralytics import YOLO
model=YOLO("best.pt")  
path=model.export(format="engine",opset=12,device=0,int8=True,workspace=4)
`
     _int8=True : I have read that Tensorrt had 3 precisons **INT8,FP16,FP32**  so to get maximum inference speed i used 
     int8=True_(Correct me if i was wrong)

3.I had generated the engine file but when i compare with .pt , The .pt model is taking **40ms** inference time for a **single frame** and engine is taking **32ms** .Dont have drastic change in the speed .Kindly help me why this much less speed

In your document it is mentioning that there is **5X speed** when we use engine file
(Note:I have generated the engine file in the same machine where i have tested)

Many many thanks in advance. @glenn-jocher 

### Additional

Nil

**Comment by Manueljohnson063** [comment]
I am using Jetson Xavier NX

**Comment by Kayzwer** [comment]
@Manueljohnson063 try `simplify=True`

**Comment by Manueljohnson063** [comment]
@Kayzwer @glenn-jocher I already had used it and i am getting the above mentioned 32ms.

**Comment by glenn-jocher** [comment]
@Manueljohnson063 thank you for reaching out and sharing the situation you're encountering. Let's see how we can work through this issue.

Firstly, the speed of inference heavily relies on multiple factors beyond the precision mode like INT8, FP16, and FP32. Model complexity, input resolution, and optimization strategies can likewise influence it.

While selecting INT8 does have the potential to improve speed through quantization, it's indeed not guaranteed due to the reasons mentioned above. Still, you should typically see improved performance compared to FP32.

Regarding your expectation for a 5X speed improvement, it's important to note that this kind of speedup is an optimal scenario. Some models may achieve this, but it greatly depends on the above-mentioned factors. It's not a guarantee for every scenario.

In the case of Jetson Xavier NX which you're using, do notice that this device is optimized for FP16 operations due to its Tensor Cores. Therefore, you may not necessarily see the expected speed gains when employing INT8.

For further model optimization, I recommend you to try model pruning or making use of TensorRT's optimization profiles specific to your platform. These enhancements can help further increase the inference speed.

I hope these insights bring some clarity to your question. Feel free to let us know if there's anything else you need. We appreciate your involvement in the YOLOv8 community!

**Comment by Luna6688** [comment]
插个眼，持续关注

**Comment by glenn-jocher** [comment]
@Luna6688 thank you for your contributing your eyes and continued attention to the improvement and progress of YOLOv8. Rest assured that any developments or updates concerning YOLOv8 will be posted and shared in our repository. We always appreciate community engagement and interest. If you have any questions or suggestions for YOLOv8, feel free to open an issue or pull request at any time. Your participation is highly valued. Thanks again!

**Comment by NeuralAIM** [comment]
`int8=True` - **does not work for** `.engine` **models.** 

This is not in the documentation, and TensorRT reports when exporting that the FP32 model is being exported. It is possible to export only to FP16/FP32.

_Arguments for export (**TRT**):_
`imgsz, half, dynamic, simplify, workspace`

I wonder if it is possible to add model export to INT8?

**Comment by glenn-jocher** [comment]
@NeuralAIM thank you for your inquiry and suggestion. 

For TensorRT, exporting to INT8 precision is not currently supported in YOLOv8. The export capabilities currently support either FP32 or FP16 precision using the `half` argument as you've noted. We understand this might be a desired feature, and its future implementation depends on various technical considerations.

The INT8 precision export involves a process called quantization which requires calibration data. This additional step introduces complexity in the exporting process, and currently, we've focused on providing FP32 and FP16 export capabilities.

However, we are always open to improving and expanding the repertoire of features in YOLOv8. We take your feedback seriously, and a possible support for INT8 TensorRT model export is a great suggestion. We will be considering exploring this capability in the future.

Thank you, once again, for the feedback. We really appreciate your active contribution to the YOLOv8 community.
