### ISSUE TITLE
ValueError: "Invalid CUDA requested"

### ISSUE THREAD

**Issue by beautifulchoi** [ultralytics/ultralytics#4537]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hello,
I'm setting my new local environment and try to use "yolov8x" model.
but, when I run the code, I got the error like this.
![image](https://github.com/ultralytics/ultralytics/assets/87787966/f9cc1656-974d-40cc-a085-e9c99adb9c02)
![image](https://github.com/ultralytics/ultralytics/assets/87787966/640b26a0-44d6-4526-9f33-3b6cbdeb43a3)

my hardware environment is, window 10 pro, nvidia geforce rtx 4090 
and I download cuda 11.8 version
I also check the torch version and it match the cu11.8
![image](https://github.com/ultralytics/ultralytics/assets/87787966/edbe3e9f-4e66-4bfd-884c-85a934b8d117)
![image](https://github.com/ultralytics/ultralytics/assets/87787966/bf3cf055-433d-4d02-aad4-b1aceaa28fe0)

I tried to delete all of nvidia driver and cuda toolkit and re installed. but it still not working.

so I tried to declare like this but still not working.
![image](https://github.com/ultralytics/ultralytics/assets/87787966/f55c68ca-d285-4439-b1bb-7cdd6713d8c1)

and also, when I check the os.environ["CUDA_VISIBLE_DEVICES"], it seems to change '0', but when I call "model.train", it convert wrong.

so, how can I fix it?? 

additionally, I already tried to use virtual environment, using both venv and conda

**Comment by glenn-jocher** [comment]
@beautifulchoi hello,

The error message indicates an issue with your CUDA Toolkit setup. To start with, please ensure that your CUDA and PyTorch versions are compatible. With CUDA 11.8, you should be using a PyTorch version that specifically supports this CUDA version.

Although you've already verified the CUDA version compatible with your installed PyTorch by checking "torch.version.cuda", there's a chance that the CUDA version observed by the code could be different from what's installed. The CUDA version can sometimes be overridden by the environment variable.path

Regarding the environment variable "CUDA_VISIBLE_DEVICES", it's used to restrict the number of GPUs visible to your program. You set it to '0', which means only GPU 0 will be used. I'd recommend you use this approach only if you have multiple GPUs and wish to use a specific one, otherwise this setting can be omitted.

Contrary to the case of setting CUDA_VISIBLE_DEVICES during model training, the toolkit does not automatically switch for different CUDA versions on different projects, hence its compatibility comes into play during runtime.

If all requirements are met and the problem persists, uninstall the current CUDA Toolkit and then reinstall a different version that's explicitly compatible with your current PyTorch version.

I hope this clarifies the issue and let me know if any further assistance is required. Remember, YOLOv8 is built on top of continual work from the AI community, and every contribution matters.

**Comment by beautifulchoi** [comment]
@glenn-jocher hello, thanks for reply.

for checking the problem, I wanted to test whether this is CUDA problem or not. so I made a new project and wrote simple classifer code by using one of the torchvision's model, ConvNext. and after I load model and random tensor on GPU and infer it, it works. I think this mean it is not a problem of CUDA toolkit.

![image](https://github.com/ultralytics/ultralytics/assets/87787966/33b0b0ab-f72f-4c33-97b6-45108035ff69)

**Comment by glenn-jocher** [comment]
@beautifulchoi hello,

It's good to hear from you again. Your experiment with another model indicates that your CUDA Toolkit is likely working appropriately with PyTorch. That's a valuable clue in our troubleshooting process.

The issue you're encountering may stem from how the YOLOv8 model is handling CUDA operations. Are you sure you're using identical CUDA and PyTorch versions in both your test project and the project where you're trying to run YOLOv8? Incompatibility between PyTorch and CUDA versions can lead to unexpected errors.

Also, consider the possibility of an issue with YOLOv8's usage of potentially complex CUDA operations not encountered in other models or it might be some differences in the scale of resource requirement between the two models. If YOLOv8 code has operations that are not supported by your CUDA version, you may run into problems despite other models running fine.

Keep in mind that YOLOv8's model architecture could require more resources compared to a simple ConvNet. If you're running close to your GPU memory limit, you might want to try reducing your batch size.

This process of elimination can be a slow one, but each test brings us one step closer to understanding the underlying issue. I hope you'll continue sharing your findings and rest assured that the entire Ultralytics and broader YOLO community is here to assist in resolving your issue.

**Comment by AChangXD** [comment]
@glenn-jocher Running into the same issue. In `ultralytics\yolo\utils\torch_utils.py`, the `select_device()` method has "cuda" passed in for some reason.

**Comment by AChangXD** [comment]
@glenn-jocher Weird thing is YoloV8 works fine on my laptop RTX 4090, but my desktop 4090 doesn't work. Here's the screenshot of my CUDA version/Pytorch version
![image](https://github.com/ultralytics/ultralytics/assets/51896236/bb7abc20-45f7-4661-80a2-13062e305a4b)

**Comment by AChangXD** [comment]
@glenn-jocher @beautifulchoi So the fix for me was in `engine/model.py` where in the `train()` method, I did an override on `kwargs`, updating it from a torch device instance `torch.device(type="cuda")` to `"cuda:0"`:
![image](https://github.com/ultralytics/ultralytics/assets/51896236/fbeadd44-049d-42dc-b658-b04550cf7c61)

**Comment by AChangXD** [comment]
Could also just update `yolov8.py` to this (assuming you only have one Nvidia GPU, probably have to do `"cuda:0,1"` if you have two GPUs and so on):
![image](https://github.com/ultralytics/ultralytics/assets/51896236/4ca72490-85ac-4cc0-adb2-a670f02710e0)

**Comment by glenn-jocher** [comment]
@AChangXD the explicit mention of the GPU via "cuda:0" seems to have worked for you, which is a promising workaround. This fix might be ideal in cases where you only have one Nvidia GPU, however, if you have multiple GPUs, you would have to explicitly indicate all the GPUs you want to use (e.g. "cuda:0,1" for two GPUs, etc.). 

Please note that this is a workaround and may not be suitable for all scenarios. The root cause of the issue seems related to how the CUDA device is selected in the codebase, which might need a more comprehensive solution. Ideally, the selection of the CUDA device should be abstracted and automatically managed by PyTorch, unless manually specified by the user or in cases where you need to control the specific GPU usage.

Despite the workaround, it would be valuable for the authors of YOLOv8 to understand why the issue arises and whether it's an edge-case or could potentially affect a larger number of users.

**Comment by AChangXD** [comment]
> @AChangXD the explicit mention of the GPU via "cuda:0" seems to have worked for you, which is a promising workaround. This fix might be ideal in cases where you only have one Nvidia GPU, however, if you have multiple GPUs, you would have to explicitly indicate all the GPUs you want to use (e.g. "cuda:0,1" for two GPUs, etc.).
> 
> Please note that this is a workaround and may not be suitable for all scenarios. The root cause of the issue seems related to how the CUDA device is selected in the codebase, which might need a more comprehensive solution. Ideally, the selection of the CUDA device should be abstracted and automatically managed by PyTorch, unless manually specified by the user or in cases where you need to control the specific GPU usage.
> 
> Despite the workaround, it would be valuable for the authors of YOLOv8 to understand why the issue arises and whether it's an edge-case or could potentially affect a larger number of users.

Yeah I agree, I'm honestly very confused as well since I'm running the same version of PyTorch/CUDA (12.1) on my laptop (Mobile RTX 4090 + 13900HX) and have no issue. My desktop (RTX 4090 + 7900X) is throwing the error.

**Comment by glenn-jocher** [comment]
@AChangXD, thank you for sharing your observations. It's indeed peculiar that the same setup is behaving differently on your laptop and desktop. This could hint towards a specific hardware-context issue that may not be directly related to the versions of PyTorch or CUDA in use.

It might be beneficial to check if there are any differences in the system environments between your laptop and desktop that could impact PyTorch's CUDA operations (e.g., GPU drivers, OS version, etc.). Also, ensuring that your desktop GPU is properly recognized by PyTorch and is not under any restrictive settings could help. 

While your current workaround is effective, it would be helpful to further investigate these discrepancies to ensure more generalized GPU management in the YOLOv8 code and potentially make it more robust. This could be part of an ongoing improvement process within the YOLOv8 project to optimize GPU usage across different hardware configurations. 

Thanks for your initiative in uncovering this issue, your contributions to the community are very valuable.
