### ISSUE TITLE
Why does pose estimation model's output is different in pt file & onnx file

### ISSUE THREAD

**Issue by yellowjs0304** [ultralytics/ultralytics#4540]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, First of all I changed my own pose estimation model to onnx.
But It looks like the [pred value](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/engine/validator.py#L179) is different.

In pt file output, the preds type is list, and the tensor shape (preds[0].shape) is (Batch, 9, 8400)  that you talk.(batch_size, num_classes + 4 + num_masks, num_boxes)

But in Onnx file output, the preds type is tensor, and the shape is (preds.shape) is (1, 9, 8400) IT's different. 
But the result score is same.

Could you find the way?? @glenn-jocher

**Comment by yellowjs0304** [comment]
It looks like the validator code is forcing the onnx file only validate batch size as 1. 
Why the model only validate only one size?

Even i changed the export command 
`yolo export model=./trained_weight/best.pt format=onnx dynamic=True`
But the model output looks only support 1 batch.

**Comment by glenn-jocher** [comment]
@yellowjs0304 hi there,

Thank you for raising this issue.

The difference in outputs between the .pt and .onnx formats arises from the different operational contexts of these two models. PyTorch (.pt) models are typically used in a more flexible, research-oriented context where dynamic batch sizes might be needed. Therefore, the PyTorch model's output preserves the dynamic 'batch size' dimension.

On the other hand, the .onnx format is typically used for deploying models where the batch size is often fixed ahead of time for consistency, speed, and memory considerations. This is why the .onnx format appears to only support a single batch.

The `dynamic=True` command in the export function should have allowed for dynamic batch sizes in the .onnx model. However, it seems to not be functioning as expected. We'll look into this to ascertain if there's a bug causing this inconsistency.

We appreciate your patience and understanding. Would you be able to open a bug report so the team can track this issue?

Best regards,
Glenn from the Ultralytics team.

**Comment by yellowjs0304** [comment]
Thanks for your reply.
I tried exporting again with the above command, and the model output looks good.
here's the onnx file input/output by netron
![image](https://github.com/ultralytics/ultralytics/assets/30281608/a899c284-8252-44d2-9c5c-5905a267be6d)

And I also tried to validate the pt, onnx file, and the preds value is the same shape. (Batch, 9, 8400)
only different with the type (pt is list, onnx is tensor)

**Comment by glenn-jocher** [comment]
@yellowjs0304,

I'm glad to hear that the model output now aligns with your expectations.

Indeed, the observed difference in type (list for .pt model and tensor for .onnx model) is expected due to the inherent design of PyTorch and ONNX systems. PyTorch's flexibility allows operations on variable-sized lists of tensors, while ONNX requires a more rigid structure with fixed-size inputs and outputs to allow for optimization during production. Therefore, the ONNX model outputs are typically tensors.

Remember, the difference in data type doesn't affect the result validity since both forms ultimately contain the same prediction values.

If you face any further issues or have additional questions, don't hesitate to reach out.

Best regards,
Glenn from the Ultralytics team.
