### ISSUE TITLE
I have question related to Mlflow + aws sagemaker + Yolov8

### ISSUE THREAD

**Issue by Hir98** [ultralytics/ultralytics#4541]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have train model in colab and track all experiments in mlflow server.
now i want to deploy weight which is store in mlflow server to aws sagemaker.
is it possible to deploy this pytorch model in sagemaker from mlflow. because when i  store data in mlflow for yolov8 then it is not supported with pytorch .
So i have one question like how we can deploy yolov8 model from mlflow to sagemaker.
i have found this articals [https://aws.amazon.com/blogs/machine-learning/hosting-yolov8-pytorch-model-on-amazon-sagemaker-endpoints/](https://aws.amazon.com/blogs/machine-learning/hosting-yolov8-pytorch-model-on-amazon-sagemaker-endpoints/) but there is no use of mlflow.
i want to deploy it from mlflow.

can you please answer me or provide some reference.

Thanks.

**Comment by glenn-jocher** [comment]
@Hir98 hello,
Thank you for your detailed question.

Yes, deploying a YOLOv8 model tracked in MLflow server to AWS Sagemaker is certainly possible. You'd essentially be deploying a PyTorch model. While you've said you ran into issues saying YOLOv8 isn't supported with PyTorch, that shouldn't be the case considering YOLOv8 uses the PyTorch framework for implementation.

As a general solution, follow these steps:

1. First, you'd want to save your YOLOv8 model weights in the MLflow artifacts repository.
2. Then, you would load the model from the MLflow server and wrap it in a PyTorch model using the MLflow PyTorch API. 
3. You can then deploy your PyTorch model in AWS Sagemaker directly from MLflow using the `mlflow.sagemaker.deploy()` function provided by the MLflow Sagemaker API. This function allows for seamless deployment from the MLflow model registry to Sagemaker.

It's important to know that your model needs to be absolutely Sagemaker-compatible: it should have all the necessary `model_fn`, `input_fn`, `predict_fn`, `output_fn`, and `transform_fn` functions defined in a python file usually named `inference.py`.

If you keep running into issues, make sure to double-check the compatibility of your versions. Different versions of MLflow, Sagemaker, and PyTorch could create compatibility issues.

I hope this gives you a starting point for deploying your YOLOv8 model from MLflow to Sagemaker. If you have more questions, don't hesitate to ask.
Best,
Glenn

**Comment by Hir98** [comment]
@glenn-jocher 
I am saying YOLOv8 is not supported pytorch with mlflow.
when i store model in mlflow at that time mlflow.pytorch.log_model() is not supported in case of YOLOv8

**Comment by glenn-jocher** [comment]
@Hir98 hi there,

I see the issue you're encountering. Generally, MLflow is designed to interface with PyTorch, and since YOLOv8 is developed in PyTorch, it should theoretically work. However, I understand you're facing some difficulties. 

When saving models with `mlflow.pytorch.log_model()`, the function is expecting a subclass of `torch.nn.Module`, which is the base class for all neural network modules in PyTorch. As such, it might be necessary to ensure that the YOLOv8 model adheres to this specification for log_model to function correctly.

Though we strive to make YOLOv8 as compatible as possible with various platforms and software, there might be some work needed at your end to make it compatible with MLflow's requirements. 

For now, you might consider manually saving the PyTorch model's weights, and then creating a new model structure in PyTorch that can load these weights before attempting to save this model with `mlflow.pytorch.log_model()`.

I hope this answer provides some direction. Don't hesitate to reach out if you need further help.

Best of luck with your work!

Best,
Glenn

**Comment by Hir98** [comment]
@glenn-jocher 
I am currently using the YOLOv8 model for object detection and have integrated it with MLflow to track all my experiments. However, I am encountering a persistent issue where the execution goes into an infinite loop when trying to store artifacts in MLflow after training the model. This same issue also occurred when attempting to use Dashub for storing artifacts with YOLOv8.

**Steps to Reproduce:**

- Set up the YOLOv8 model for object detection.
- Train the model using your preferred dataset.
- Attempt to store artifacts in MLflow using the MLflow tracking system.
- Observe that the execution enters an infinite loop.

Code for trainng with mlflow:
```
  import os
  from pathlib import Path
  import mlflow
  import yaml
  from ultralytics import YOLO
  import mlflow
  import os
  from getpass import getpass
  from mlflow.protos.service_pb2 import PROJECT
  import dagshub

  # load the configuration file
  with open(r"/content/drive/MyDrive/YOLOv8/MLFlow/params.yaml") as f:
      params = yaml.safe_load(f)


  mlflow.end_run()

  os.environ['MLFLOW_TRACKING_URI'] = 'URI'
  # dagshub.init("mlflow-test", "uname", mlflow=True)
  # set the tracking uri
  mlflow.set_tracking_uri(os.environ['MLFLOW_TRACKING_URI'])
  mlflow.create_experiment("testdata","mlflow-artifacts:/0")
  mlflow.set_experiment("testdata")
  # start mlflow experiment
  with mlflow.start_run(run_name=params['name']):
    # load a pre-trained model
    model = YOLO(params['model_type'])
    PROJECT = "my_proj"

    # # train
    model.train(
              data='/content/drive/MyDrive/YOLOv8/MLFlow/dataset.yaml',
              imgsz=params['imgsz'],
              batch=params['batch'],
              epochs=params['epochs'],
              optimizer=params['optimizer'],
              lr0=params['lr0'],
              seed=params['seed'],
              pretrained=params['pretrained'],    project=PROJECT,
    )
    run_name = params['name']
    experiment = mlflow.get_experiment_by_name(experiment_name)
    print("experiment",experiment)
    print("run name",run_name)

```

dataset.yaml
```
train: /content/drive/MyDrive/YOLOv8/MLFlow/data/train/images # train images (relative to 'path') 128 images
val: /content/drive/MyDrive/YOLOv8/MLFlow/data/val/images # val images (relative to 'path') 128 images
# test:  # test images (optional)


nc: 1
names: ['object']
```
params.yaml
```
model_type: yolov8s.pt 
pretrained: True
seed: 0
imgsz: 640 
batch: 8 
epochs: 1
optimizer: SGD # other choices=['SGD', 'Adam', 'AdamW', 'RMSProp']
lr0: 0.01  # learning rate 
name: 'yolov8s_exp_v01' # experiment name

```
I have tried it many times but same issue i was facing all times.

**Additional Information:**

- I have verified that my MLflow configuration is correct and compatible with the YOLOv8 model.
- I have also encountered a similar issue when using Dashub for storing artifacts, suggesting that the problem may be related to the YOLOv8 model or its integration with these tools.
- I have reviewed my code and have not identified any obvious mistakes that could lead to this issue.

Please advise on how to address this issue, or if it may be a bug in the YOLOv8 model or its integration with MLflow and Dashub.

**Comment by glenn-jocher** [comment]
@Hir98 thank you for sharing the detailed information regarding the issue you're encountering while using YOLOv8 with MLflow. 

Given your issue, there could be underlying factors causing it. 

First, consider checking the state and health of your MLflow server, particularly when making a call to log artifacts in your run. Make sure that your server is properly set up and that it's not retrying to establish a connection, creating a loop in the process. 

Secondly, try checking the size of the artifacts that you're trying to log to MLflow. If the size is too large, it may be causing problems. It might be helpful to print debug statements before and after you log to see if that is the cause of the infinite loop. 

Lastly, since you've mentioned encountering a similar issue with Dagshub, the issue might stem from the way YOLOv8 interacts with these services. Try to use a minimal set-up and gradually add components to isolate any conflicting interactions. 

These observations should help determine whether the issue is related to your setup, the YOLOv8 model, MLflow/Dagshub, or an integration of these. 

I encourage you to also write to the respective parties (MLflow and Dagshub), with information on the issue, as they might have encountered similar cases and offer better advice on resolving it. If this turns out to be a bug with YOLOv8, do let us know, and we'll work on addressing it.

I hope this provides a good starting point and you get the issue resolved soon. Please don't hesitate to reach back if you have any more questions or updates regarding this issue.
Best, 
Glenn

**Comment by Hir98** [comment]
@glenn-jocher 

I am facing this issue with mlflow itself.

When i try this code to store srtifacts in same server then it works fine for me.
```
import mlflow
tracking_uri = 'https://...'
mlflow.set_tracking_uri(tracking_uri)
print(mlflow.get_tracking_uri()) # This should be 'http://localhost:5000'
# print(mlflow.get_artifact_uri()) # This should be '${mlruns_artifacts}/0/${uuid}/artifacts'
mlflow.log_metric('test_metric', 1)
mlflow.log_artifact("/home/hiral/Documents/Document/Hir/POC/testmlflow.py")
```
but when i try with YOLOv8 i am facing infinity execution issue.

can you please check once?? and update me what is the issue.

**Comment by glenn-jocher** [comment]
@Hir98,

I understand you're experiencing a problem with infinite loop execution when working with YOLOv8 and MLflow to store artifacts. It appears that when you attempt to store artifacts using MLflow outside the context of YOLOv8, things work just fine. However, when you integrate it with YOLOv8, the issue arises which suggests it could be linked to how YOLOv8 interacts with MLflow.

Some things you might want to consider include:

1. When integrating with YOLOv8, ensure you are saving and specifying the paths to your artifacts correctly. Improper path handling may lead to issues when logging the artifacts to MLflow.

2. MLFlow might be continuously retrying to upload due to a failed attempt which could be due to networking, authentication, or even timeout issues. Look into your MLflow server health.

3. Double-check you're not recursively logging artifacts by accident - this could occur if your logging directory includes the MLruns directory.

4. The size of the artifacts could also matter. If they're too large, the upload may never complete, causing what seems to be an infinite loop.

Remember, this doesn't imply there's a bug with YOLOv8, but it might be the way it's being used in conjunction with MLflow.

I hope this advice helps you diagnose the issue. Don't hesitate to provide more detail if the problem persists. It can be helpful to understand what specific part of the YOLOv8 flow is causing MLflow to loop infinitely.

Best,
Glenn

**Comment by Hir98** [comment]
@glenn-jocher 
Still there is a problem of infinite loop when i use mlflow with YOLOv8
But when i set   `**settings.update({'mlflow': False})**` and then logs params and metrics and model then it is working fine.

Here is code which is working fine 

```
  # load the configuration file
  with open(r"/content/drive/MyDrive/YOLOv8/MLFlow/params.yaml") as f:
      params = yaml.safe_load(f)

   # Update a setting
  from ultralytics import settings
  settings.update({'mlflow': False})

  mlflow.end_run()
  mlflow.set_tracking_uri(os.environ['MLFLOW_TRACKING_URI'])

  run_name = params['name']
  experiment = mlflow.get_experiment_by_name(experiment_name)
    
  print("experiment name",experiment)
  print("run name",run_name)

  if not experiment:
      mlflow.create_experiment(experiment_name, "mlflow-artifacts:/0")
      print("Experiment created")
  else:
      print("Experiment with the same name already exists")
  mlflow.set_experiment(experiment_name)


  # start mlflow experiment
  with mlflow.start_run(run_name=params['name']):

    # load a pre-trained model
    model = YOLO(params['model_type'])
    PROJECT = "my_proj"

    # train
    model.train(
              data='/content/drive/MyDrive/YOLOv8/MLFlow/dataset.yaml',
              imgsz=params['imgsz'],
              batch=params['batch'],
              epochs=params['epochs'],
              optimizer=params['optimizer'],
              lr0=params['lr0'],
              seed=params['seed'],
              pretrained=params['pretrained'],    
              project=PROJECT,
    )


    run, active_run = mlflow, mlflow.active_run()
    print("active run id",active_run.info.run_id)

    # log best fit and last fit in mlflow
    mlflow.log_artifact(model.trainer.last)
    mlflow.log_artifact(model.trainer.best)

    # logs params in mlflow
    run.log_params(vars(model.trainer.model.args))

    # logs metrics in mlflow
    metrics_dict = {f"{re.sub('[()]', '', k)}": float(v) for k, v in model.trainer.metrics.items()}
    run.log_metrics(metrics=metrics_dict, step=model.trainer.epoch)

    # Log the PyTorch model to the artifact location specified by 'artifact_path'
    mlflow.pyfunc.log_model(artifact_path="model", artifacts={'model_path': str(model.trainer.save_dir)},python_model=mlflow.pyfunc.PythonModel())

```

**Comment by glenn-jocher** [comment]
Hi @Hir98, 

Thanks for providing such a thorough explanation of your issue, it's very helpful.

It sounds like you've found a workaround by manually controlling the MLflow integration with the `settings.update({'mlflow': False})` and then manually logging your parameters, metrics, and model. This indicates that the issue is likely not with MLflow itself, but rather with the way YOLOv8 is attempting to automatically manage and integrate with MLflow.

Seems like when YOLOv8 tries to automatically manage the integration with MLflow in your environment, it encounters an infinite loop. This could potentially be due to some intricacy in your setup, the size or nature of the artifacts being logged, or a combination of both. We know that MLflow is functioning correctly on its own and with your manual logging scheme, so the issue is possibly how YOLOv8 is trying to utilize the service.

By disabling the automatic MLflow integration, you are bypassing this issue, controlling what gets logged and when. This will prevent undesired automatic retries or failures that could be leading to the infinite loop. This is a good solution for now.

While it could be ideal for YOLOv8 to handle this automatically, it may not be possible to cover every potential environment or use case. Your successful manual intervention is a good indication that you have found a solution that works efficiently for your particular setup.

Best regards,
Glenn
