### ISSUE TITLE
streamlit/ultralytics

### ISSUE THREAD

**Issue by DarkLord-13** [ultralytics/ultralytics#4543]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

code:

import streamlit as st
from PIL import Image
from ultralytics import YOLO

def process_uploaded_image(uploaded_image):
    # Perform YOLO object detection
    model = YOLO('best.pt')
    result = model.predict(uploaded_image)[0]
    detected_image = result.render()[0]
    num_boxes = len(result.boxes.data)
    return detected_image, num_boxes

st.title("Image Uploader and Object Detection")

uploaded_image = st.file_uploader("Choose an image...", type=["jpg", "png", "jpeg"])

if uploaded_image is not None:
    st.image(uploaded_image, caption="Uploaded Image", use_column_width=True)
    process_button = st.button("Process Image")

    if process_button:
        # Process the uploaded image and display the detected image with bounding boxes
        detected_image, num_boxes = process_uploaded_image(uploaded_image)
        st.image(detected_image, caption=f"Detected Image ({num_boxes} objects)", use_column_width=True)
        st.subheader(f'Number of Detected Objects: {num_boxes}')

error:

File "C:\Users\Darklord\AppData\Roaming\Python\Python311\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
File "D:\DF\ML\ML_Projects(vs_studio)\Streamlit_course\aaaa.py", line 23, in <module>
    detected_image, num_boxes = process_uploaded_image(uploaded_image)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\DF\ML\ML_Projects(vs_studio)\Streamlit_course\aaaa.py", line 8, in process_uploaded_image
    result = model.predict(uploaded_image)[0]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Darklord\AppData\Roaming\Python\Python311\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Darklord\AppData\Roaming\Python\Python311\site-packages\ultralytics\engine\model.py", line 246, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Darklord\AppData\Roaming\Python\Python311\site-packages\ultralytics\engine\predictor.py", line 197, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Darklord\AppData\Roaming\Python\Python311\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
File "C:\Users\Darklord\AppData\Roaming\Python\Python311\site-packages\ultralytics\engine\predictor.py", line 229, in stream_inference
    self.setup_source(source if source is not None else self.args.source)
File "C:\Users\Darklord\AppData\Roaming\Python\Python311\site-packages\ultralytics\engine\predictor.py", line 210, in setup_source
    self.dataset = load_inference_source(source=source, imgsz=self.imgsz, vid_stride=self.args.vid_stride)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Darklord\AppData\Roaming\Python\Python311\site-packages\ultralytics\data\build.py", line 150, in load_inference_source
    source, webcam, screenshot, from_img, in_memory, tensor = check_source(source)
                                                              ^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Darklord\AppData\Roaming\Python\Python311\site-packages\ultralytics\data\build.py", line 133, in check_source
    raise TypeError('Unsupported image type. For supported types see https://docs.ultralytics.com/modes/predict')

**Comment by glenn-jocher** [comment]
@DarkLord-13 hello,

From the error message, it seems that the issue is in the data type of the input image provided to the `predict` method. The YOLOv8 model's `predict` method currently supports inputs in the form of file paths, URLs, or PIL images. From the error message, we can see that the uploaded image (which is a Streamlit UploadedFile object) is not in a supported format.

To resolve this issue, you would need to convert the UploadedFile object to a PIL image before passing it to the `predict` method. Here's a general verbal outline of what needs to be done:

1. Use the Streamlit's `uploaded_image.read()` method to read the uploaded data.
2. Byte data returned from the `read` method needs to be converted back to a format compatible with `PIL.Image.open()`.
3. Create a PIL image object from the byte data.
4. Pass the PIL image object to the `predict` method in your Streamlit app.

After doing this, your `predict` function call in the `process_uploaded_image` method should be able to receive a valid format that it can process, thereby bypassing this error.

Remember, Streamlit's file uploader returns a BytesIO object, so we need to make sure this data is transformed appropriately before the `predict` method processes it.

Please let me know if this helps or whether you have further questions!

Best,
Glenn

**Comment by glenn-jocher** [comment]
@hengamirah it looks like the issue might be due to the coordinate system mismatch between the bounding box coordinates and the image dimensions. Ensure that the coordinates are correctly scaled to the image size. Also, verify that the image is correctly loaded and displayed. If the problem persists, please check the dimensions and scaling factors used in your bounding box plotting function.
