### ISSUE TITLE
How to add another label with a set of image to the model only with python?

### ISSUE THREAD

**Issue by pythonsus** [ultralytics/ultralytics#4554]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to add another label with a set of images to the model only with python?

**Comment by glenn-jocher** [comment]
@pythonsus hello,

Thanks for reaching out! To add another label with a set of images to the YOLOv8 model only with Python, you will have to follow these steps:

1. **Update Label Files:** You will have to generate the appropriate label files (.txt) for the new images you wish to include in your dataset. These label files should follow the YOLO label format. 

2. **Update Dataset:** Next, add your new images and corresponding label files into your current dataset folders. You may place them in the appropriate directories for training, validation, or testing depending on your requirements. Make sure your dataset YAML file is updated to include the new paths if necessary.

3. **Update Label List:** Your label list, typically included in your dataset YAML file, contains all the class names your model is training on. Add your new label to this list in the appropriate ordering.

4. **Train:** Now you can retrain your model with the updated dataset.

Remember, when adding new labels it's crucial to have sufficient representative images for the new label in your dataset and to train the model adequately on this supplemented dataset.

I hope this answers your question, let me know if you have any other doubts. Happy coding!

**Comment by jquintanilla4** [comment]
@glenn-jocher What if I want to keep the existing default labels of YOLOv8, but only want to add a single new label?

For more context, the default YOLOv8m.pt model has the label for humans, which is very useful. I want to keep that, but at the same time I want to add a new label with the corresponding dataset for roman armor... I can't seem to figure how to do that, maybe I'm totally not seeing something simple. No matter what I do, it always keeps starting from scratch label-wise.

If keeping the existing default labels is not possible when resuming training or training a new model, how can I continue training my best.pt or last.pt (from the roman armor training) on a new dataset like coco128 and keep both my labels and coco128's labels?

Hope that makes sense.

**Comment by glenn-jocher** [comment]
@jquintanilla4 hello,

Thank you for reaching out! Adding a new class to an already trained YOLOv8 model while keeping the previously learned classes is quite a complex operation as it involves modifying the architecture of the model (mainly the last layer) and correctly initializing the weights to ensure a proper behavior. 

So, if you wish to add a new class, such as roman armor, to the existing YOLOv8 model, you would essentially follow these steps:

- Combine the new roman armor dataset with the existing dataset used for default YOLOv8 training (e.g. COCO). 
- Update your .yaml configuration file to account for the additional class.
- Finally, retrain the model on the combined dataset.

Unfortunately, at this moment, there is no direct way of achieving it without retraining the model on the combined dataset. This is because the architecture of the model changes when new classes are introduced which demands that the model be retrained.

In the future also, if you want to add viking armor to your existing roman armor and COCO model, ideally you need to combine all three datasets (viking armor, roman armor, and coco128) and perform training on this new combined dataset.

Remember that even though this process might seem energy inefficient, it’s crucial to ensure that the new classes are properly represented, the model generalizes well, and does not forget the previous classes.

Currently, YOLOv8 does not have a feature for incremental learning, but it is an active area of research in the machine learning field, and we might see some changes in the future updates. 

I hope this answers your question. Let me know if you have any further queries!
