### ISSUE TITLE
for result in results.boxes.data.tolist(): AttributeError: 'NoneType' object has no attribute 'data'

### ISSUE THREAD

**Issue by JiraTechComunity** [ultralytics/ultralytics#4559]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I got this error when i want to detect video with show score, class_id

PS C:\Users\jirap\Desktop\Python\Dog_detection> & C:/Users/jirap/AppData/Local/Programs/Python/Python38/python.exe c:/Users/jirap/Desktop/Python/Dog_detection/detect.py   
OpenCV: FFMPEG: tag 0x5634504d/'MP4V' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'

0: 64x64 bully 0.92, pom 0.08, 27.9ms
Speed: 11.0ms preprocess, 27.9ms inference, 0.0ms postprocess per image at shape (1, 3, 64, 64)
Traceback (most recent call last):
  File "c:/Users/jirap/Desktop/Python/Dog_detection/detect.py", line 107, in <module>
    for result in results.boxes.data.tolist():
AttributeError: 'NoneType' object has no attribute 'data'
PS C:\Users\jirap\Desktop\Python\Dog_detection>

**Comment by glenn-jocher** [comment]
@JiraTechComunity hello,

The error message you're seeing is usually a result of trying to access an attribute from a NoneType object. In your case, you're attempting to use the `.data` attribute with `results.boxes`, which appears to be None. 

This might be happening because the model did not detect anything, and hence, no bounding boxes were created. You should add a check to ensure `results.boxes` is not None before trying to access its `data` attribute.

Before the line `for result in results.boxes.data.tolist():`, try adding an if statement to check if `results.boxes` is not None. If it is None, then the program should handle it accordingly, perhaps by continuing to the next iteration or by providing a message that no objects were detected.

Remember to maintain your dataset's quality and ensure it's representative of the situations where you want to apply your model. For example, if your model is trained to detect dogs, it might not perform well if tested on a video without dogs.

Hope this helps and keeps your project moving forward! Don't hesitate to come back if you have more questions.
