### ISSUE TITLE
Output as a list of detected objects

### ISSUE THREAD

**Issue by MEMEO-PRO** [ultralytics/ultralytics#4560]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to save the list of the predicted objects in an excel file , but the `results = model.predict(frame)` gives output as `
0: 384x640 (no detections), 47.3ms
Speed: 1.6ms preprocess, 47.3ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)
3
[ultralytics.engine.results.Results object with attributes:

boxes: ultralytics.engine.results.Boxes object
keypoints: None
keys: ['boxes']
masks: None
names: {0: 'name1', 1: 'name2', 2: 'name3'}
orig_img: array([[[ 1,  6,  7],
        [ 1,  6,  7],
        [ 1,  5,  9],
        ...,
        [ 5, 10, 19],
        [ 2,  7, 15],
        [ 2,  7, 15]],

       [[ 4,  8, 10],
        [ 0,  3,  5],
        [ 0,  4,  8],
        ...,
        [ 8, 15, 23],
        [ 3, 10, 19],
        [ 2,  9, 17]],

       [[ 3,  6, 10],` Can you please guide me how to get only label as output

**Comment by glenn-jocher** [comment]
@MEMEO-PRO sure, you can easily get the labels of the detected objects from the results. The `predict()` method outputs an object of the `Results` class, which has an attribute `pred`, which is a list of tensors, each containing the *[x, y, width, height, confidence, class]* for each object detected.

To get the labels that correspond to these class IDs, you can use the `names` attribute, which is a dictionary mapping class IDs to their respective class names.

In your application, you'd want to iterate over the `pred` attribute for each image, and for each detection in that image, take the class ID and find the corresponding label using the `names` dictionary. This will give you the label for each detected object in your image.

Remember, the detection tensor has a shape *(number of detections, 6)*. The class ID is the last value in each detection, so for any detection `d`, `d[-1]` will give you the class ID.

You can then use your favorite Python library to output this list of labels to an Excel file. I hope this helps! Feel free to ask if you have any further questions.

**Comment by MEMEO-PRO** [comment]
Thanks ,
I used 
`          results = model(frame)

          a=results[0].boxes.data
          px=pd.DataFrame(a).astype("float")
    #   
          for _,row in px.iterrows():

              d=int(row[5])
              c=class_list[d]`

**Comment by glenn-jocher** [comment]
@MEMEO-PRO hello,

It looks like you are correctly accessing the Boxes object's `data` attribute after prediction. This tensor will give you the bounding boxes for all detected objects in your image, formatted as [x_center, y_center, width, height, confidence, class_id].

In the provided code snippet, you're converting this tensor to a DataFrame with Pandas, which is a good way to handle the results if you need to perform data manipulation tasks.

You're correctly looping through this DataFrame to access each detection. The variable `d` is assigned with the class ID by accessing the 6th column (row[5], as Python is 0-indexed) in the DataFrame. `c` variable gets the corresponding class name from `class_list` using `d` as the index. This would work as expected if `class_list` is a list where the index corresponds to the class id.

The code seems appropriate for getting the class labels for each detection. If you're having an issue, could you please provide more details about problems you are experiencing? I'm happy to help further.

**Comment by SayyedSha** [comment]
I am using yolov8x.pt and i was trying to get the orig_img for result object but keeps giving me Error

cam = cv2.VideoCapture("constructionModel\work2.mp4")
while True:

    try:
        _, frames = cam.read()
        results = model(frames, stream=True,conf=0.8)
        
        # print(results.names)
        for r in results:
            print(list(results))
            boxes = r.boxes
            print(r.orig_img)
            # print(r.names)
            for box in boxes:
                x1, y1, x2, y2 = box.xyxy[0]
                x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
                confidence = math.ceil((box.conf[0] * 100)) / 100
                cls = int(box.cls)
                # cls2.append(cls)
                # print(cls2)
                
                org = [x1, y2+10]
                font = cv2.FONT_HERSHEY_SIMPLEX
                fontScale = 0.7
                color = (255, 0, 0)
                thickness = 2
                org_x = x1-2
                org_y = y2-7
                
                print(r.orig_img)
                 if cls==0:
                    # val = hardHat_detector(r.orig_img[x1:x2, y1:y2])
                    # color = (0, 255, 0) if val else (0, 0, 255)
                    cv2.rectangle(frames, (x1, y1), (x2, y2), color, 3)
                    cv2.imshow('Normal Frame Rate', frames)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    except Exception as e:
        print(f"Error {e}")
        
  Error
            'Results' object has no attribute 'orig_img'. Valid 'Results' object attributes and properties are:

            Attributes:
                boxes (Boxes, optional): A Boxes object containing the detection bounding boxes.
                masks (Masks, optional): A Masks object containing the detection masks.
                probs (torch.Tensor, optional): A tensor containing the detection class probabilities.
                orig_shape (tuple, optional): Original image size.

**Comment by glenn-jocher** [comment]
Hello @SayyedSha,

From what I can discern from the error and your snippet, it appears that you're trying to access an attribute `orig_img` which does not exist in the `Results` object provided by the YOLOv8 prediction. That's why you're encountering the "'Results' object has no attribute 'orig_img'" error.

In YOLOv8's `Results` object, the attribute you are likely looking for is `orig_shape`, which holds the original image size, rather than `orig_img`. To extract the original images themselves, you'll have to manage them separately from the `Results` object because the detections, as processed by the model, are designed to return mainly the bounding boxes, classes, and any associated metadata.

The original image 'frames' that you passed to the model is what you should draw onto. If you want to manipulate or display the original image based on the detection results, you would modify and display 'frames' directly, which is the original input to the model.

In your loop where you attempt to print or manipulate `r.orig_img`, you should replace it with `frames`, as this represents the original frame captured from the video. You've already started using `frames` when drawing rectangles, so the same frame should be used when you wish to display or further process detection results.

Keep in mind that the `Results` object only contains detection data and metadata. The actual image data needs to be managed by your code outside of the detection results. You're on the right track with the rest of the code, where you loop through detections and draw them onto the input frames before displaying them with OpenCV.

Remember to safely release your VideoCapture object and close all OpenCV windows after you're done to avoid any resource leaks.

I hope this clears things up! If you have any more questions, feel free to ask.
