### ISSUE TITLE
Yolo model continuous inference

### ISSUE THREAD

**Issue by coder-glitche** [ultralytics/ultralytics#4566]
Hey there @glenn-jocher sorry for bugging you again when you say loading the model into memory are you saying me to essentially have this model= YOLO('path/to/model.pt') in my python file and then have an inference loop?
Also can you please provide an implementation of my inference loop such that lets say new image gets into a folder through my drones camera only that new image should undergo inference without having to reload the model for the incoming images it should not basically exit the inference loop and keep checking how should i modify my model.predict() thanks alot!!

**Comment by glenn-jocher** [comment]
@coder-glitche hi there,

You've got the right idea! When I say "loading the model into memory", I'm indeed referring to the initiation of the model once with something like `model = YOLO('path/to/model.pt')` in your python file. This operation loads your model into memory and prepares it for inference.

With regards to your inference loop, you're spot on as well. When a new image arrives in the folder from your drone's camera, you can call the `model.predict()` function on that new image. Since the model has already been loaded into memory, you won't need to load it again for every new image that comes — the model will stay in memory ready for the next image. 

As for not exiting the inference loop, you may want to consider using a while loop or some sort of event listener to constantly check the folder for new images. When a new image is detected, your code can then run inference on this new image using the model that is already loaded in memory.

I hope this provides clarity on your question. Let me know if you have any other questions or concerns! 

Best,
Glenn Jocher
