### ISSUE TITLE
Keypoint.conf is None

### ISSUE THREAD

**Issue by dawson-friesenhahn** [ultralytics/ultralytics#4586]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

Hi! I trained a few yolov8-pose models on a virtual F16 in simulation. The results look pretty decent! However, I'm having trouble accessing the confidence levels for the individual keypoints. When I run the normal yolov8n-pose.pt on an image of a person, I can see the following:
![image](https://github.com/ultralytics/ultralytics/assets/35878220/29e7483e-9b97-44c3-b247-485e02446009)

Sure enough, a tensor with all of the confidences for the keypoints. 

However, when I try with my model: 
![image](https://github.com/ultralytics/ultralytics/assets/35878220/d63a7739-f6be-4e50-8004-49d8ee2c5eca)

.conf is None. 

.data does hold a tensor containing the coordinates of all the pixels! However, I'd really like to be able to see confidences for each keypoint as well. 

I trained with 26 labeled keypoints. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@dawson-friesenhahn hi,

Thank you for reaching out and providing detailed information about the issue.

When `.conf` is showing None, it typically means that no confidence scores were assigned during prediction for individual keypoints. This might happen if the keypoint detection process was unable to compute a confidence score, possibly due to the given bounding box not containing any of the 26 labeled keypoints.

However, given that you mentioned `.data` does indeed contain coordinates, there should theoretically be associated confidence scores. One possibility is that there could be an issue when the model is assigning these confidence scores to each keypoint after prediction.

To clarify the situation, it would be useful to check the number of keypoints detected during prediction and whether this matches with the number of confidence scores provided. If these two numbers don't match, this might suggest an issue to do with the scoring process.

Nonetheless, the exact cause of this issue would be difficult to determine without a deep dive into each layer of the model and potentially the specific input data being used. Let me further review the model and look into possible solutions to your problem.

Once again thank you for using Ultralytics YOLOv8 and for contributing to the issue tracker.

Best,
Glenn Jocher

**Comment by Laughing-q** [comment]
@dawson-friesenhahn It depends on the format of your training labels, if the labels are [k, 3] then there will be confidence scores for predicted keypoints, if the labels are [k, 2] then there will not be confidence scores of predicted keypoints.

**Comment by dawson-friesenhahn** [comment]
@Laughing-q Trained a new model with keypoint visibility included to match the [k,3] format and I can now see the confidences, thank you! Can I recommend adding it to the docs?
1. [Pose Home](https://github.com/ultralytics/ultralytics/blob/main/docs/tasks/pose.md): Add line in the intro that specifies that  you need to follow the x,y,visible format to get keypoint confidences.
2. [Predict ](https://docs.ultralytics.com/modes/predict/#keypoints): Maybe something here in the conf field that specifies the conditions under which keypoint confidences are available
3. [Results Class File](https://docs.ultralytics.com/reference/engine/results/#ultralytics.engine.results.Keypoints): Same here.

Thank you both for your responsiveness and quickness to help out!
