### ISSUE TITLE
How to load a .pth pretrained file？

### ISSUE THREAD

**Issue by Gloria949** [ultralytics/ultralytics#4601]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have replaced the backbone network of YOLOv8 with FasterNet, but the pretrained file provided by the author has a .pth suffix. How can I load the .pth file in YOLOv8?

**Comment by glenn-jocher** [comment]
@Gloria949 hello, and thanks for reaching out!

To load a .pth pretrained file, you typically use PyTorch's `torch.load()` function which can handle .pth files. This function returns a dictionary containing the saved state of the model's parameters, which you can then load into your model using the `load_state_dict()` method. 

However, if you've significantly altered the architecture of the YOLOv8 model, such as by replacing the backbone network with FasterNet, loading pretrained weights can be a bit more complex. 

The pretrained .pth file likely contains weights specifically shaped for the original network architecture (in this case, the stock YOLOv8 architecture), and not for your modified one. If the layers of FasterNet and the original backbone do not match perfectly in names and dimensions, you will need to make sure that the weights are loaded correctly into the new structure. 

You may want to build a mapping mechanism that goes through the keys in state dictionary of the pretrained file and associates each one correctly to your model's layers.

Finally, if your modifications also changed the number of layers, you'll need to decide how to handle layers that might not have pretrained weights available. A common approach is to randomly initialize these additional layers.

Please make sure to correctly match the layers and their weights, and then you should be all set and ready to use your new, modified model!

**Comment by Gloria949** [comment]
Thank you for your answer, which to some extent resolved my doubts. 

But when I use this statement to load the model, it reports an error saying 
“AttributeError: 'YOLO' object has no attribute 'load_state_dict'. See valid attributes below.”

The code I am using is：

def para_state_dict(model, model_save_dir):
    state_dict = copy.deepcopy(model.state_dict())
    model_save_path = os.path.join(model_save_dir, 'fasternet_t0.pth')
    if os.path.exists(model_save_path):
        loaded_paras = torch.load(model_save_path)
        for key in state_dict:  
            if key in loaded_paras and state_dict[key].size() == loaded_paras[key].size():
                print("Done:", key)
            state_dict[key] = loaded_paras[key]
    return state_dict

if __name__ == '__main__':
    # Load a model
    model = YOLO('/home/extend/zhy/code/yolo_tracking-masterold/ultralytics/models/v8/yolov8-FasterNet.yaml')
    # checkpoint = para_state_dict(model, '/home/extend/zhy/code/yolo_tracking-masterold/pretrained')
    checkpoint = torch.load('/home/extend/zhy/code/yolo_tracking-masterold/pretrained/fasternet_t0.pth')
    model.load_state_dict(checkpoint['model_state_dict'])

When I replace the last line with：
model._load(checkpoint)
it reports an error saying “TypeError: expected str, bytes or os.PathLike object, not collections.OrderedDict”

How can I load such a weight dictionary into the model？

**Comment by Gloria949** [comment]
I think I already understand how to load such weights. Thank you very much for your patient answer. :)

**Comment by glenn-jocher** [comment]
You're welcome, @Gloria949! I'm glad to hear that you're finding the guidance helpful and you've made progress with loading the weights into your model. Should you encounter any other issues, or if you have more questions in the future, don't hesitate to ask. Happy modeling!

**Comment by massimiliano96** [comment]
@Gloria949 How did you solve the issue? I'm facing a similar problem, here's my code:

I initially log my model to mlflow after training:

```
model_to_log = YOLO("output/train/weights/best.pt")
mlflow.pytorch.log_model(
    pytorch_model=model_to_log,
    artifact_path="output/train/weights/best.pt",
    registered_model_name=model_name,
)
```

Then when I download the artifact:

`mlflow.artifacts.download_artifacts(artifact_uri=model_uri, dst_path='./model')`

I get a **model.pth** file.

How can I load it into YOLO class?

**Comment by KaushikNoukha** [comment]
Im not able to load my .pth files, Ive finetuned my voice model using coqui XTTS-v2 In the colab environment and Got model.pth, config.json,vocab.json_  file as a result of the finetuning process with my custom voice while i try to integrate it with my local voice assistant application i get warming up failed and also im not able to set a language too These are my terminal logs can anyone suggest me on how to load a model.pth files and use it in my local application i keep on trying but cant find a solution to this error  pls view my terminal logs and help me with this 

These are my terminal logs
(venv311) PS C:\Users\admin\OneDrive\Desktop\Voice-model\intuitionX-voice-assistant> python -m uvicorn stt_server.app:app --host 0.0.0.0 --port 8001                          
C:\Users\admin\OneDrive\Desktop\Voice-model\intuitionX-voice-assistant\venv311\Lib\site-packages\transformers\utils\hub.py:111: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
INFO:     Started server process [13564]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
[opus @ 000001b47232e240] Error parsing Opus packet header.
[TRANSCRIBE] Done: lang=en p=1.00 chars=32
INFO:     127.0.0.1:56972 - "POST /transcribe HTTP/1.1" 200 OK
[CHAT] /chat invoked
[CHAT] Received transcript chars=32
[CHAT] Gemini replied chars=38
Using local Coqui TTS repository at: C:\Users\admin\OneDrive\Desktop\Voice-model\intuitionX-voice-assistant\TTS\TTS\TTS
Successfully imported TTS from local repository (pip fallback disabled)
=== GET_TTS_SERVICE CALLED ===
=== CREATING NEW TTS SERVICE ===
=== TTS SERVICE INIT START ===
Initializing ULTRA-FAST Coqui TTS service...
Using device: cpu
[DIAG] TTS_LANGUAGE=en
[DIAG] TTS_SPEAKER_WAV resolved: C:\Users\admin\OneDrive\Desktop\Voice-model\intuitionX-voice-assistant\stt_server\Voice_samples_Gus_000_norm_fixed.wav
[TTS] Auto-downloading from Hugging Face: repo_id=kaushikaiml/Gus-finegrained rev=main files=(model.pth, config.json)
[TTS] Using HF-cached files:
  model: C:\hf_cache\hub\models--kaushikaiml--Gus-finegrained\snapshots\a2045b4c938865cbdf46886cb9341658599906da\model.pth
  config: C:\hf_cache\hub\models--kaushikaiml--Gus-finegrained\snapshots\a2045b4c938865cbdf46886cb9341658599906da\config.json
[TTS] Loading LOCAL checkpoint from environment paths...
[TTS] Effective model path: C:\hf_cache\hub\models--kaushikaiml--Gus-finegrained\snapshots\a2045b4c938865cbdf46886cb9341658599906da\model.pth
[TTS] Effective config path: C:\hf_cache\hub\models--kaushikaiml--Gus-finegrained\snapshots\a2045b4c938865cbdf46886cb9341658599906da\config.json
[TTS] Adjusted model path to directory for XTTS: C:\hf_cache\hub\models--kaushikaiml--Gus-finegrained\snapshots\a2045b4c938865cbdf46886cb9341658599906da
 > Using model: xtts
GPT2InferenceModel has generative capabilities, as `prepare_inputs_for_generation` is explicitly defined. However, it doesn't directly inherit from `GenerationMixin`. From 👉v4.50👈 onwards, `PreTrainedModel` will NOT inherit from `GenerationMixin`, and this model will lose the ability to call `generate` and other related functions.
  - If you're using `trust_remote_code=True`, you can get rid of this warning by loading the model with an auto class. See https://huggingface.co/docs/transformers/en/model_doc/auto#auto-classes
  - If you are the owner of the model architecture code, please modify your model class such that it inherits from `GenerationMixin` (after `PreTrainedModel`, otherwise you'll get an exception).
  - If you are not the owner of the model architecture class, please contact the model code owner to update it.
[DIAG] TTS python module path: C:\Users\admin\OneDrive\Desktop\Voice-model\intuitionX-voice-assistant\venv311\Lib\site-packages\TTS\__init__.py
[DIAG] Active TTS source: LOCAL checkpoint
[DIAG] self.tts.model_name:
Primary TTS model loaded: xtts_local
Extensive model warm-up for millisecond response...
 > Text splitted to sentences.
['Hello']
C:\Users\admin\OneDrive\Desktop\Voice-model\intuitionX-voice-assistant\venv311\Lib\site-packages\torchaudio\_backend\utils.py:213: UserWarning: In 2.9, this function's implementation will be changed to use torchaudio.load_with_torchcodec` under the hood. Some parameters like ``normalize``, ``format``, ``buffer_size``, and ``backend`` will be ignored. We recommend that you port your code to rely directly on TorchCodec's decoder instead: https://docs.pytorch.org/torchcodec/stable/generated/torchcodec.decoders.AudioDecoder.html#torchcodec.decoders.AudioDecoder.
  warnings.warn(
 > Text splitted to sentences.
['Hello']
 > Text splitted to sentences.
['Hello']
Warm-up failed for 'Hello': Model is multi-lingual but no `language` is provided.      
 > Text splitted to sentences.
['Hi there']
 > Text splitted to sentences.
['Hi there']
 > Text splitted to sentences.
['Hi there']
Warm-up failed for 'Hi there': Model is multi-lingual but no `language` is provided.  
 > Text splitted to sentences.
['Welcome']
 > Text splitted to sentences.
['Welcome']
 > Text splitted to sentences.
['Welcome']
Warm-up failed for 'Welcome': Model is multi-lingual but no `language` is provided.    
 > Text splitted to sentences.
['Thank you']
 > Text splitted to sentences.
['Thank you']
 > Text splitted to sentences.
['Thank you']
Warm-up failed for 'Thank you': Model is multi-lingual but no `language` is provided.  
 > Text splitted to sentences.
['Yes']
 > Text splitted to sentences.
['Yes']
 > Text splitted to sentences.
['Yes']
Warm-up failed for 'Yes': Model is multi-lingual but no `language` is provided.        
 > Text splitted to sentences.
['No']
 > Text splitted to sentences.
['No']
 > Text splitted to sentences.
['No']
Warm-up failed for 'No': Model is multi-lingual but no `language` is provided.
 > Text splitted to sentences.
['Okay']
 > Text splitted to sentences.
['Okay']
 > Text splitted to sentences.
['Okay']
Warm-up failed for 'Okay': Model is multi-lingual but no `language` is provided.      
 > Text splitted to sentences.
['Sure']
 > Text splitted to sentences.
['Sure']
 > Text splitted to sentences.
['Sure']
Warm-up failed for 'Sure': Model is multi-lingual but no `language` is provided.      
 > Text splitted to sentences.
['How are you?']
 > Text splitted to sentences.
['How are you?']
 > Text splitted to sentences.
['How are you?']
Warm-up failed for 'How are you?': Model is multi-lingual but no `language` is provided.
 > Text splitted to sentences.
["What's up?"]
 > Text splitted to sentences.
["What's up?"]
 > Text splitted to sentences.
["What's up?"]
Warm-up failed for 'What's up?': Model is multi-lingual but no `language` is provided.
 > Text splitted to sentences.
['Good morning']
 > Text splitted to sentences.
['Good morning']
 > Text splitted to sentences.
['Good morning']
Warm-up failed for 'Good morning': Model is multi-lingual but no `language` is provided.
 > Text splitted to sentences.
['Good evening']
 > Text splitted to sentences.
['Good evening']
 > Text splitted to sentences.
['Good evening']
Warm-up failed for 'Good evening': Model is multi-lingual but no `language` is provided.
 > Text splitted to sentences.
['I understand']
 > Text splitted to sentences.
['I understand']
 > Text splitted to sentences.
['I understand']
Warm-up failed for 'I understand': Model is multi-lingual but no `language` is provided.
 > Text splitted to sentences.
['Please wait']
 > Text splitted to sentences.
['Please wait']
 > Text splitted to sentences.
['Please wait']
Warm-up failed for 'Please wait': Model is multi-lingual but no `language` is provided.
 > Text splitted to sentences.
['Processing']
 > Text splitted to sentences.
['Processing']
 > Text splitted to sentences.
['Processing']
Warm-up failed for 'Processing': Model is multi-lingual but no `language` is provided.
 > Text splitted to sentences.
['Complete']
 > Text splitted to sentences.
['Complete']
 > Text splitted to sentences.
['Complete']
Warm-up failed for 'Complete': Model is multi-lingual but no `language` is provided.  
 > Text splitted to sentences.
['Error']
 > Text splitted to sentences.
['Error']
 > Text splitted to sentences.
['Error']
Warm-up failed for 'Error': Model is multi-lingual but no `language` is provided.      
 > Text splitted to sentences.
['Success']
 > Text splitted to sentences.
['Success']
 > Text splitted to sentences.
['Success']
Warm-up failed for 'Success': Model is multi-lingual but no `language` is provided.    
Model warm-up completed! 0 phrases cached.
=== TTS SERVICE CREATED, speaker_wav=C:\Users\admin\OneDrive\Desktop\Voice-model\intuitionX-voice-assistant\stt_server\Voice_samples_Gus_000_norm_fixed.wav ===
Generating speech for text: 'What about 800 culture?  Tell me more.'
Using model: xtts_local
[METRIC] Model source: LOCAL; Speaker: None
 > Text splitted to sentences.
['What about 800 culture?', 'Tell me more.']
[WARN] Direct tts_to_file failed: 'NoneType' object has no attribute 'encode'. Falling back to in-memory synthesis.
 > Text splitted to sentences.
['What about 800 culture?', 'Tell me more.']
 > Text splitted to sentences.
['What about 800 culture?', 'Tell me more.']
 > Text splitted to sentences.
['What about 800 culture?', 'Tell me more.']
[ERROR] In-memory synth fallback failed: Model is multi-lingual but no `language` is provided.
[METRIC] TTS synthesis time: 3185.0 ms
Error generating TTS: TTS engine failed to create output file: C:\Users\admin\OneDrive\Desktop\Voice-model\intuitionX-voice-assistant\audio_output\tts_output_20250915_134428.wav
[CHAT] TTS failed: Failed to generate TTS: TTS engine failed to create output file: C:\Users\admin\OneDrive\Desktop\Voice-model\intuitionX-voice-assistant\audio_output\tts_output_20250915_134428.wav
INFO:     127.0.0.1:56975 - "POST /chat HTTP/1.1" 200 OK

As you can see my model is failing to warmup what might be the issue!

**Comment by glenn-jocher** [comment]
@massimiliano96 YOLO expects Ultralytics `.pt` checkpoints, not generic `.pth` blobs saved via `mlflow.pytorch.log_model(...)`; log and retrieve the original `best.pt` as an artifact, then load it with:
```python
from ultralytics import YOLO
model = YOLO("/path/to/downloaded/best.pt")
```
If you’re using MLflow, log the file itself (not the YOLO object):
```python
import mlflow
mlflow.log_artifact("output/train/weights/best.pt", artifact_path="model")
```
The loader under the hood uses `load_checkpoint()` which enforces `.pt`; see the Model `load()` reference and the `load_checkpoint()` implementation for details: [Model.load reference](https://docs.ultralytics.com/reference/engine/model/#load), [load_checkpoint in tasks.py](https://docs.ultralytics.com/reference/nn/tasks/#load_checkpoint).

@KaushikNoukha This thread is about YOLO weights; the Coqui TTS issue is out of scope here—please use the Coqui/TTS support channels, and if you hit an Ultralytics-specific problem, open a new issue with `yolo checks` output and the full traceback for visibility.
