### ISSUE TITLE
yolov8 load issue after saving

### ISSUE THREAD

**Issue by M-Hassan-Maqsood** [ultralytics/ultralytics#4605]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have trained the yolov8 model on the custom dataset and I saved it. when I try to load the model for detection it gives me a model error. I tried different ways to save the model and tried to load it again, but not working. I provide you with my full code. Please help me

**Here is my code**
!pip install ultralytics
from ultralytics import YOLO
model=YOLO('yolov8m.pt')
from google.colab import drive
drive.mount('/content/drive')
import shutil
src_path = '/content/drive/MyDrive/Person detection.v1i.yolov8'
dest_path = '/content/'
shutil.copytree(src_path, dest_path + 'dataset')
%cd /content/dataset
import os
print("Current directory:", os.getcwd())
%cd /content/dataset
directory_contents = os.listdir()
print("Directory contents:", directory_contents)
model.train(data='/content/dataset/data.yaml', epochs=25 )

**Method to save and upload model**

**Give error**

1. model.save('/content/dataset/trained_model.pt')

2. import torch
model_weights_path = '/content/drive/MyDrive/YourModelWeights.pth'
torch.save(model.state_dict(), model_weights_path)

AttributeError                            Traceback (most recent call last)
<ipython-input-15-bc7580a464ed> in <cell line: 2>()
      1 # After training
----> 2 model.save('/content/dataset/trained_model.pt')
/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py in __getattr__(self, attr)
    444         """Raises error if object has no requested attribute."""
    445         name = self.__class__.__name__
--> 446         raise AttributeError(f"'{name}' object has no attribute '{attr}'. See valid attributes below.\n{self.__doc__}")
    447 
    448     def smart_load(self, key):
**AttributeError: 'YOLO' object has no attribute 'save'. See valid attributes below.
    YOLO (You Only Look Once) object detection model.**
    

**Model save using this** 

1. import torch
torch.save(model.model.state_dict(), '/content/drive/MyDrive/trained_yolov8_model.pt')

2. config = {
    'data_config': '/content/dataset/data.yaml',  # Assuming this is your data configuration file
    'model_architecture': 'YOLOv8',
    'training_params': {
        'epochs': 25  # Adjust this as needed
    }
}
import torch
import json
model_weights_path = '/content/drive/MyDrive/trained_yolov8_model.pth'
config_path = '/content/drive/MyDrive/trained_yolov8_config.json'
torch.save(model.model.state_dict(), model_weights_path)
with open(config_path, 'w') as config_file:
    json.dump(config, config_file)

**load model**

**error**
1. import torch
import json
from ultralytics import YOLO
config_path = '/content/drive/MyDrive/trained_yolov8_config.json'
model_weights_path = '/content/drive/MyDrive/trained_yolov8_model.pth'
with open(config_path, 'r') as config_file:
    loaded_config = json.load(config_file)
model = YOLO(loaded_config['model_architecture'])
model.model.load_state_dict(torch.load(model_weights_path))

**this work**

1. from ultralytics import YOLO

model_weights_path = '/content/drive/MyDrive/trained_yolov8_model.pth'
model = YOLO(model_weights_path, task='detect')

2. import torch
from ultralytics import YOLO
config_path = '/content/drive/MyDrive/trained_yolov8_config.json'
model_weights_path = '/content/drive/MyDrive/trained_yolov8_model.pth'
with open(config_path, 'r') as config_file:
    loaded_config = json.load(config_file)
model = YOLO(loaded_config['model_architecture'])
loaded_model = YOLO(model_weights_path, task='detect')

**but it also give error like model , weights, 'YOLOv8' does not exist, Error(s) in loading state_dict for DetectionModel, and other** 

### Additional

I have tried these methods but not work. help me

**Comment by glenn-jocher** [comment]
@M-Hassan-Maqsood hi there! Thanks for reaching out to us, and sorry for the confusion with saving and loading your model. From looking at your code snippets, here are some general recommendations.

1. When you want to save a model after training, you should use the `torch.save()` function to save the model's state dictionary, which you're already doing in one of your snippets. It's important to remember that you're saving the internal PyTorch model's state dict, not the outer YOLO object. 

2. When reloading the model, you should instantiate a new YOLO object and then load the weights into the internal PyTorch model using the `model.model.load_state_dict()`. 

3. The errors like "'YOLOv8' does not exist," "Error(s) in loading state_dict for DetectionModel" might indicate issues with the model file you're trying to load. Please cross-check the correctness of the path of the saved model file.

4. Lastly, remember that the `'YOLO' object has no attribute 'save'` error appears because our YOLO object does not have a save method. As explained above, the PyTorch's `save()` function should be used to save the model's state dictionary (`state_dict()`).

I hope these suggestions help! Feel free to reach back with further questions or clarifications.
