### ISSUE TITLE
new  version bug, can not train the resnet18

### ISSUE THREAD

**Issue by jimmyxzy** [ultralytics/ultralytics#4612]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

"D:\Program Files\Python39\python.exe" "D:\yolov8cls\ultralytics-main (0828)\ultralytics-main\ultralytics\models\yolo\classify\train.py" 
Ultralytics YOLOv8.0.164  Python-3.9.9 torch-2.0.1+cu118 CUDA:0 (NVIDIA GeForce RTX 3090 Ti, 24564MiB)
engine\trainer: task=classify, mode=train, model=resnet18, data=mnist160, epochs=20, patience=50, batch=16, imgsz=224, save=True, save_period=-1, cache=False, device=0, workers=0, project=None, name=None, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=20, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, stream_buffer=False, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=runs\classify\train16
train: D:\code\ultralytics-main\datasets\mnist160\train... found 80 images in 10 classes  
val: None...
test: D:\code\ultralytics-main\datasets\mnist160\test... found 80 images in 10 classes  
TensorBoard: Start with 'tensorboard --logdir runs\classify\train16', view at http://localhost:6006/
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed 
train: Scanning D:\code\ultralytics-main\datasets\mnist160\train... 80 images, 0 corrupt: 100%|██████████| 80/80 [00:00<?, ?it/s]
val: Scanning D:\code\ultralytics-main\datasets\mnist160\test... 80 images, 0 corrupt: 100%|██████████| 80/80 [00:00<?, ?it/s]
optimizer: AdamW(lr=0.000714, momentum=0.9) with parameter groups 20 weight(decay=0.0), 21 weight(decay=0.0005), 21 bias(decay=0.0)
Image sizes 224 train, 224 val
Using 0 dataloader workers
Logging results to runs\classify\train16
Starting training for 20 epochs...
Closing dataloader mosaic

      Epoch    GPU_mem       loss  Instances       Size
  0%|          | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\yolov8cls\ultralytics-main (0828)\ultralytics-main\ultralytics\models\yolo\classify\train.py", line 168, in <module>
    train()
  File "D:\yolov8cls\ultralytics-main (0828)\ultralytics-main\ultralytics\models\yolo\classify\train.py", line 164, in train
    trainer.train()
  File "D:\Program Files\Python39\lib\site-packages\ultralytics\engine\trainer.py", line 196, in train
    self._do_train(world_size)
  File "D:\Program Files\Python39\lib\site-packages\ultralytics\engine\trainer.py", line 353, in _do_train
    self.loss, self.loss_items = self.model(batch)
  File "D:\Program Files\Python39\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Program Files\Python39\lib\site-packages\torchvision\models\resnet.py", line 285, in forward
    return self._forward_impl(x)
  File "D:\Program Files\Python39\lib\site-packages\torchvision\models\resnet.py", line 268, in _forward_impl
    x = self.conv1(x)
  File "D:\Program Files\Python39\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Program Files\Python39\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\Program Files\Python39\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
TypeError: conv2d() received an invalid combination of arguments - got (dict, Parameter, NoneType, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (!dict!, !Parameter!, !NoneType!, !tuple of (int, int)!, !tuple of (int, int)!, !tuple of (int, int)!, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (!dict!, !Parameter!, !NoneType!, !tuple of (int, int)!, !tuple of (int, int)!, !tuple of (int, int)!, int)

Process finished with exit code 1

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@jimmyxzy thank you for reporting this issue with training a ResNet-18 model on YOLOv8. From the traceback, it seems like the error originates from an incorrect set of arguments being passed to the convolutional layer of the ResNet model. This points to a mismatch between expected tensor input and the actual input provided.

It's worth ensuring that all the inputs and configurations for the ResNet-18 model adheres to the requirements outlined in the model specifications. For instance, ensure that your input data type matches what the model expects, typically a 4D Tensor of the form (batch_size, channels, height, width).

However, the troubleshooting of this issue might involve investigating the complete input pipeline, starting from the data pre-processing and loading stage to the part where inputs are forwarded through ResNet-18. 

We'll also investigate this potential bug in our codebase. Thank you for your patience as we work on resolving this issue. Please track the status of this issue for updates from our team.

**Comment by glenn-jocher** [comment]
@jimmyxzy what is your command to reproduce your error?

**Comment by jimmyxzy** [comment]
How should I load mobilenet_v2 and resnet18 in the latest version?

**Comment by jimmyxzy** [comment]
@glenn-jocher How should I load mobilenet_v2 and resnet18 in the latest version?

**Comment by glenn-jocher** [comment]
@jimmyxzy, thank you for bringing up these specific models. To load both MobileNetV2 and ResNet18 in YOLOv8, you will need to invoke their respective architecture configurations. 

For the MobileNetV2 model, you will specify `--cfg mobilev2.yaml` and for ResNet18, you will specify `--cfg resnet18.yaml`. Using the `--cfg` argument, the training script will load the corresponding file in the `models` directory, which defines the architecture of the model. 

Please remember to ensure that these architecture files (`.yaml`) exist in your `models` directory. In case they don't, you could define them based on the reference structure of these models. The YAML files follow a strict structure, defining the architecture for each model, such as the number and types of layers, layer configuration and hyperparameters. 

Please ensure you have also updated the parameter files related to the specific dataset you're using, as this might affect the performance and compatibility of the models. If you continue to face issues, I encourage you to provide more specific details about the problems that you're encountering for further assistance.

**Comment by jimmyxzy** [comment]
@glenn-jocher ,thank you very much for answering my question。I've been using yolov8 framework for half a year,I really like this framework. However, it is updated frequently，as a result, some function that worked in the old version are not available in the new version.
    For example，in the version Ultralytics YOLOv8.0.30, i can load resnet18 easily in the python file that in the root \ultralytics\ultralytics\yolo\v8\classify\train.py,it can work did not need yaml file, also can load the other specific models. But in recent versions, I can not load resnet18 and the other specific models take the same approach.
    The code is as follows that can work in the version Ultralytics YOLOv8.0.30 , but can not work in the recent versions ,  this code in the root \ultralytics-main\ultralytics\yolo\v8\classify\train.py

def train(cfg=DEFAULT_CFG, use_python=False):
    model = cfg.model or "yolov8n-cls.pt"  # or "resnet18"
    model = "mobilenet_v2"
    # data = cfg.data or "mnist160"  # or yolo.ClassificationDataset("mnist")
    data = "D:\code\data\juanyanerdai"
    device = cfg.device if cfg.device is not None else ''

    args = dict(model=model, data=data, batch=16, epochs=50, workers=4, augment=False, close_mosaic=20, device=device, imgsz=448, pretrained=False, name='mobilenet_v2val')
    if use_python:
        from ultralytics import YOLO
        YOLO(model).train(**args)
    else:
        trainer = ClassificationTrainer(overrides=args)
        trainer.train()


if __name__ == "__main__":
    train()

**Comment by glenn-jocher** [comment]
@jimmyxzy, thank you for your continuous support and usage of the YOLOv8 framework! We indeed update our frameworks frequently to incorporate new features, make improvements and fix bugs. While these frequent updates are aimed to enhance the framework, we understand that they may sometimes cause confusion.

Regarding your question about loading models such as ResNet18 or MobileNetV2, you're right that in recent versions, you cannot load these models directly without using a YAML file as in previous versions. This is because we've changed the way models are loaded and configured to improve the flexibility and generalizability of the framework.

Now, each model's architecture is specified in a separate YAML file, which provides a more readable, flexible, and maintainable way to define models. This way, you can have full control of the model structure by just editing these YAML files, without having to modify the codebase.

In recent versions, to load a model like ResNet18, you will have to have a corresponding YAML file (e.g., 'resnet18.yaml') that defines the ResNet18 model's architectural specifics. Similarly, for MobileNetV2, you will specify a 'mobilenetv2.yaml' file.

We understand that this change may bring some adaptation difficulties, but in the long run, it will be beneficial in increasing the flexibility and scalability of your experiments with our framework. Your feedback is greatly appreciated and helps us realize areas we can improve and clarify.

**Comment by jimmyxzy** [comment]
thank you very much!

**Comment by glenn-jocher** [comment]
@jimmyxzy you're welcome! If you have any other questions or concerns don't hesitate to ask. We're always here to help you. Continue using YOLOv8 and let us know about your experiences and any insights you might have. Happy coding!

**Comment by SONYYA7** [comment]
@jimmyxzy since you have experience on working with yolo 
i am trying to train rtdetr-resnet101 model  ,
``from ultralytics import RTDETR
# Load a model
model = RTDETR('/content/ultralytics/ultralytics/cfg/models/rt-detr/rtdetr-resnet101.yaml')

# Train the model
model.train(data='/content/Colony-Counter-Real-data-V1-4/data.yaml',
            epochs=100,
            mode='train',
            imgsz=768,
            batch=8,
            workers=2,
            lr0= 0.01,
            lrf= 0.16,
            model = f'/content/ultralytics/ultralytics/cfg/models/rt-detr/rtdetr-resnet101.yaml')``
but i get 
WARNING ⚠️ no model scale passed. Assuming scale='l'.

                   from  n    params  module                                       arguments                     
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-28-8a70a64cdc22>](https://localhost:8080/#) in <cell line: 3>()
      1 from ultralytics import RTDETR
      2 # Load a model
----> 3 model = RTDETR('/content/ultralytics/ultralytics/cfg/models/rt-detr/rtdetr-resnet101.yaml')
      4 
      5 # Train the model

5 frames
[/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py](https://localhost:8080/#) in parse_model(d, ch, verbose)
    676     ch = [ch]
    677     layers, save, c2 = [], [], ch[-1]  # layers, savelist, ch out
--> 678     for i, (f, n, m, args) in enumerate(d['backbone'] + d['head']):  # from, number, module, args
    679         m = getattr(torch.nn, m[:]) if 'nn.' in m else globals()[m]  # get module
    680         for j, a in enumerate(args):

KeyError: 'ResNetLayer'

``from ultralytics import YOLO
# Load a model
model = YOLO('/content/ultralytics/ultralytics/cfg/models/rt-detr/rtdetr-resnet101.yaml')

# Train the model
model.train(data='/content/Colony-Counter-Real-data-V1-4/data.yaml',
            epochs=100,
            mode='train',
            imgsz=768,
            batch=8,
            workers=2,
            lr0= 0.01,
            lrf= 0.16,
            model = f'/content/ultralytics/ultralytics/cfg/models/rt-detr/rtdetr-resnet101.yaml')``
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py](https://localhost:8080/#) in _smart_load(self, key)
    417         try:
--> 418             return self.task_map[self.task][key]
    419         except Exception as e:

KeyError: None

The above exception was the direct cause of the following exception:

NotImplementedError                       Traceback (most recent call last)
3 frames
[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py](https://localhost:8080/#) in _smart_load(self, key)
    420             name = self.__class__.__name__
    421             mode = inspect.stack()[1][3]  # get the function name.
--> 422             raise NotImplementedError(
    423                 emojis(f"WARNINGs ⚠️ '{name}' model does not support '{mode}' mode for '{self.task}' task yet.")) from e
    424 

NotImplementedError: WARNING ⚠️ 'YOLO' model does not support '_new' mode for 'None' task yet.


i couldn't make changes in these files ultralytics/nn/tasks.py , atleast to debug 
i cloned repo and tried to train, but i guess the command to train must be different ,
not yolo ....

if it python command ,

!python /content/ultralytics/ultralytics/models/yolo/segment/train.py --data /content/Colony-Counter-Real-data-V1-4/data.yaml --cfg /content/yolov8l6-transformer.yaml --hyp /content/my_hyp_config.yaml --cache --exist-ok --multi-scale --project ./colony_counter --name yolov8l6-transformer --img-size 768 --batch-size 24 --epochs 100 --workers 2 --weights yolov8m-seg.pt

i tried this , but the train.py is just declaration , i couldn't find init()
