### ISSUE TITLE
Input array instead of image (working with .fits images)

### ISSUE THREAD

**Issue by shaner306** [ultralytics/ultralytics#4615]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am working with fits imagery for astronomical data, and there is a large dynamic range of pixel values, between 0 - 65535 (signed int16) and it is tricky to save them in jpg or png as the selection of the range can be the difference between the object being in the image clearly (a circular PSF of a satellite across 5-10 pixels) vs a completely black image with only the brightest objects. 

Either way the conversion from fits to jpg or png for input into yolo causes quite a bit of data loss, is there some way to input either the fits image or the numpy array(or tensor) of the data within the image for training?

**Comment by glenn-jocher** [comment]
@shaner306 hello,

Thank you for using YOLOv8 and bringing up this interesting query related to fits imagery.

The nature of the YOLOv8 repository is generic, and it works primarily with conventional image formats like JPEG or PNG. However, your request is valid and can be valuable in certain contexts, especially when dealing with high-range pixel values as in your example with the fits imagery.

In order to use the numpy array as the input, you would need to modify the code where the images are actually read and processed, typically a DataSet or DataLoader class in the YOLOv8 code base. This would require you to locate these functions and modify them to suit your needs.

Please note that, as of now, YOLOv8 repository does not natively support fits image format or direct numpy array image inputs. It may be possible though not straightforward, and would require a good understanding of the YOLOv8 code and the transformations that the input data undergoes.

I hope this helps as a starting point for integrating your fits image numpy arrays for training. It's a great suggestion, and we will think about this feature for future versions of YOLOv8.

Please feel free to contribute to the repository. All contributions are welcome!

**Comment by shaner306** [comment]
Thanks for the detailed response! I suspected it would not be as simple as that. The next approach to try is splitting the 16bit data into 2 8 bit channels and feeding the tensors into a custom dataloader rather than attempt to find a normalized pixel range in jpg or PNG.

**Comment by glenn-jocher** [comment]
Hi @shaner306,

Your approach of splitting the 16-bit data into two 8-bit channels sounds like a promising workaround to handle the high dynamic range of your fits imagery. 

In doing so, bear in mind that YOLOv8 normally treats the three input channels as the color dimensions of an image (RGB). Therefore, you might need to adjust the representation and processing of your data in your custom DataLoader, to ensure that your data splitting approach properly fits into the model's expected input schema.

Utilizing a custom DataLoader will give you better control over handling your unique type of imagery and customizing the way the data is prepared for training. Thus it seems to be a solid plan to go forward.

I look forward to hearing about your progress and results. Keep us updated and don't hesitate to ask if you have any further questions!

Good luck with your project.
