### ISSUE TITLE
SAHI inference for YOLOV8?

### ISSUE THREAD

**Issue by kamalkannan79** [ultralytics/ultralytics#462]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to apply SAHI approach in YOLOV8 models?

**Comment by AyushExel** [comment]
hey, I'm not a SAHI user so can't talk about that. But we've updated our inference API recently with more improvements coming in the future. Please check this out - https://docs.ultralytics.com/predict/

**Comment by kadirnar** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.
> 
> ### Question
> How to apply SAHI approach in YOLOV8 models?
> 
> ### Additional
> _No response_

I'll add it to the [SAHI](https://github.com/obss/sahi) repo next week.

**Comment by kamalkannan79** [comment]
No worries, I already did SAHI+YOLOV8 Object Detections. The results are good

**Comment by kamalkannan79** [comment]
> > ### Search before asking
> > 
> > * [x]   I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.
> > 
> > ### Question
> > How to apply SAHI approach in YOLOV8 models?
> > ### Additional
> > _No response_
> 
> I'll add it to the [SAHI](https://github.com/obss/sahi) repo next week.


I will work on Segmentation YOLOV8 Model + SAHI. Help me out

**Comment by kadirnar** [comment]
> > > ### Sormadan önce ara
> > > 
> > > * [x] [YOLOV8 konularını](https://github.com/ultralytics/ultralytics/issues) ve [tartışmalarını tartışmalarını](https://github.com/ultralytics/ultralytics/discussions)     ve benzer sorularını inceleyin .
> > > 
> > > ### soru
> > > YOLOV8 modellerinde SAHI yaklaşımı nasıl uygulanır?
> > > ### ek olarak
> > > _cevap yok_
> > 
> > 
> > önümüzdeki hafta [SAHI deposuna](https://github.com/obss/sahi) ekleyeceğim .
> 
> Segmentasyon YOLOV8 Model + SAHI üzerinde bakım. bana yardım et

If you have written the detection codes, it is very simple to add segmentation. How can I help you?

**Comment by kamalkannan79** [comment]
Ok.I will try to finish

**Comment by kamalkannan79** [comment]
SAHI+YOLOV8 Segmentation model getting results. Its **Done**.

for _, image_predictions_in_xyxy_format in enumerate(self._original_predictions):
            # print("image_predictions_in_xyxy_format",image_predictions_in_xyxy_format.masks.masks)
            for pred in image_predictions_in_xyxy_format.boxes.boxes:
                x1, y1, x2, y2 = (
                  int(pred[0]),
                  int(pred[1]),
                  int(pred[2]),
                  int(pred[3]),
                )    
                bbox = [x1, y1, x2, y2]
                score = pred[4].tolist()
                category_id=int(pred[5].tolist())
                mask_arr = image_predictions_in_xyxy_format.masks.masks.numpy()[0]
                mask_arr = mask_arr.astype(bool)
                print('mask_arr',mask_arr)
                # category_name = self.model.names[int(pred[5])]
                object_prediction = ObjectPrediction(
                    bbox=bbox,
                    category_id=int(category_id),
                    score=score,
                    bool_mask=mask_arr,
                    # category_name=category_name,
                    shift_amount=shift_amount,
                    full_shape=full_shape,
                )

**Comment by DovydasPociusDroneTeam** [comment]
hello,

maybe someone knows is it possible to use YOLOV8 integrated tracker with SAHI, because when i'm using SAHI + YOLOV8, i can't reach track id from detected objects?

**Comment by glenn-jocher** [comment]
@DovydasPociusDroneTeam the integrated tracker in YOLOv8 is designed to track objects over time and associates a unique track ID with each detected object. However, when using YOLOv8 with SAHI, the track IDs may not be accessible from the detected objects. This could happen because track IDs are only assigned to objects within the same frame and may not persist across frames, or because the implementation of the tracker or the integration with SAHI may not be designed to work together seamlessly. One possible workaround could be to create a custom implementation that combines both YOLOv8 and SAHI's tracking functionalities in a way that preserves or re-assigns track IDs across frames, but this would require some programming expertise.

**Comment by kiran-coditation** [comment]
> No worries, I already did SAHI+YOLOV8 Object Detections. The results are good

Hey kamalkannan79 can you please share SAHI+YOLOV8 Object Detections

**Comment by glenn-jocher** [comment]
@kiran-coditation hi libraarii, glad to hear your results are good! As for sharing the SAHI+YOLOV8 object detections, I'm not sure if kamalkannan79 will be able to provide you with the exact code used in their implementation, but here's a brief explanation of how one could go about it using YOLOv8. 

To perform object detection with YOLOv8 and SAHI, you could follow these general steps:

1. Load the YOLOv8 model and initialize any required SAHI objects or settings.
2. Process each input image (or frame of a video) with YOLOv8 to obtain bounding box predictions and object confidence values.
3. If desired, use SAHI to perform any post-processing steps on the bounding box predictions, such as filtering out low-confidence detections or applying non-maximum suppression.
4. For each object prediction, extract relevant information such as the bounding box coordinates, object confidence value, and detected class label.
5. You can then use this information for further downstream tasks, such as tracking, segmentation, or classification. 

Overall, the specific implementation details may vary depending on your use case and the particular version of YOLOv8 you're using. However, hopefully this general workflow provides some insight into how object detection with YOLOv8 and SAHI can be achieved!

**Comment by kadirnar** [comment]
Yolov8 + SAHI: https://github.com/obss/sahi/blob/main/demo/inference_for_yolov8.ipynb

**Comment by glenn-jocher** [comment]
@kadirnar hello! Thank you for bringing up the topic of YOLOv8 + SAHI. It's great to see that the demo provided in the link you've shared demonstrates how you can perform object detection with YOLOv8 using SAHI. 

To give you a brief explanation, YOLOv8 is a state-of-the-art object detection algorithm that can detect and locate objects within an image or a video stream with high accuracy and speed. SAHI is an open-source framework that provides a machine learning pipeline to automate the process of training and serving models for a wide variety of computer vision tasks, including object detection.

By combining these two tools, you can leverage the strengths of both YOLOv8 and SAHI to perform tasks such as real-time object detection and tracking. The demo notebook you've shared shows you how to perform object detection using YOLOv8 with SAHI, which involves loading the YOLOv8 model into SAHI and then using SAHI's tools to perform inference on new input data. 

Overall, the integration between YOLOv8 and SAHI opens up many possibilities for leveraging the power of state-of-the-art object detection models in your computer vision projects.

**Comment by kiran-coditation** [comment]
> Yolov8 + SAHI: https://github.com/obss/sahi/blob/main/demo/inference_for_yolov8.ipynb

Hey Thank you so much

**Comment by mahilaMoghadami** [comment]
> No worries, I already did SAHI+YOLOV8 Object Detections. The results are good

Hello
how did you do that?

I got error while trying to use YOLOv8 in SAHI predict:

I use this command:
!sahi predict --model_path /content/drive/MyDrive/Final/SAHI/yolov8.pt --model_type yolov5 --source /content/drive/MyDrive/Final/SAHI/VisDrone2019-DET-val --dataset_json_path /content/drive/MyDrive/Final/SAHI/VisDrone2019-DET-val.json --model_confidence_threshold 0.3 --overlap_height_ratio 0.2 --overlap_width_ratio 0.2

and I get this error:
raise TypeError("model_path is not a valid yolov5 model path: ", e)
TypeError: ('model_path is not a valid yolov5 model path: ', AttributeError("'Detect' object has no attribute 'grid'"))

**Comment by vrushank41** [comment]
I want to train a model for **tracking** using _yolov8 pretrained weights_ and adding _SAHI_ along with it to improve the detections on my custom dataset . How can this be done?

**Comment by glenn-jocher** [comment]
@vrushank41 hello, and thank you for your interest in using YOLOv8 pretrained weights with SAHI for improved detections on your custom dataset!

First of all, it's great that you're planning to use the YOLOv8 pretrained weights. This gives you the benefit of transfer learning, where the model has already learned useful features from training on a large dataset, and it can potentially reduce the training time on your custom dataset.

To use SAHI for further improving the detections, you would generally need to use the YOLOv8 model to generate predictions on your dataset, and then post-process these predictions using the techniques provided by SAHI.

In this case, the steps might follow a sequence like this:
- Begin by training your YOLOv8 model on your custom dataset, initializing the model weights with the pretrained weights. 
- Once the model is trained, use it to generate object detection predictions on your dataset.
- Use SAHI's functionality to further improve these detections, e.g., by combining overlapping detections, filtering out weak detections, and so on.

Regarding the tracking, you might need to implement it separately from YOLOv8 and SAHI, as object tracking generally requires temporal information (i.e., information over time), and as far as I know, neither YOLOv8 nor SAHI currently support this feature directly. Object tracking often involves assigning unique identifiers to each object detected in a series of frames and then tracking the movement of these objects over time. There are many different techniques for object tracking and the best one to use may depend on the specific requirements of your task.

I hope this helps, and good luck with your work!

**Comment by jehanjen** [comment]
> > > > ### Sormadan önce ara
> > > > 
> > > > * [x]  [YOLOV8 konularını](https://github.com/ultralytics/ultralytics/issues) ve [tartışmalarını tartışmalarını](https://github.com/ultralytics/ultralytics/discussions)     ve benzer sorularını inceleyin .
> > > > 
> > > > ### soru
> > > > YOLOV8 modellerinde SAHI yaklaşımı nasıl uygulanır?
> > > > ### ek olarak
> > > > _cevap yok_
> > > 
> > > 
> > > önümüzdeki hafta [SAHI deposuna](https://github.com/obss/sahi) ekleyeceğim .
> > 
> > 
> > Segmentasyon YOLOV8 Model + SAHI üzerinde bakım. bana yardım et
> 
> If you have written the detection codes, it is very simple to add segmentation. How can I help you?

could you please share with me sahi + yolov8 segmentation

**Comment by glenn-jocher** [comment]
@jehanjen, it sounds like you're on a great path towards integrating YOLOv8 object detection with segmentation using SAHI. While I can't directly share a code snippet or a custom implementation here, I can guide you through the conceptual steps you might take to implement segmentation with YOLOv8 and SAHI.

While the YOLOv8 model is primarily designed for object detection, which involves identifying bounding boxes around objects, segmentation takes this a step further by classifying each pixel in the image to a particular object class. This results in a much finer level of detail, useful in applications where you need to delineate the precise outline of objects.

To implement segmentation with SAHI and YOLOv8, you would typically do the following:

1. Modify the YOLOv8 architecture to output pixel-wise class probabilities alongside the bounding box predictions. Alternatively, use a dedicated segmentation model in parallel if YOLOv8 is not suited for segmentation in your use case.

2. Post-process the segmentation outputs to improve the results. SAHI could be utilized here to handle the large-scale images by cropping large images into smaller pieces, running inference using your possibly modified YOLOv8 model, and finally merging the results back together.

3. Ensure you have annotated segmentation data to train the model if you are altering YOLOv8 to perform segmentation. If using a separate model, make sure to integrate it with the YOLOv8 detection results in a meaningful way.

4. Since there are nuances to implementing segmentation, explore the literature for state-of-the-art segmentation strategies that complement object detection, and adapt SAHI's functionality to work with pixel-level annotations if necessary.

5. Perform extensive validation to ensure that your implementation of segmentation using YOLOv8 and SAHI is accurate and meets your performance criteria.

Keep in mind that the specifics of implementation will depend largely on your exact requirements and the capabilities of the versions of YOLOv8 and SAHI you are using. Good luck with your project, and feel free to reach out with more questions as you progress. Your work is a valuable contribution to the community, and we're excited to see what you'll achieve!

**Comment by rusvagzur** [comment]
is sahi available for yolo val?

**Comment by glenn-jocher** [comment]
@rusvagzur currently, the SAHI library is designed for object detection and doesn't directly support the `val` mode for YOLOv8, which is used for validating models. SAHI primarily aids in performing sliced inference for large images and merging the results. For model validation, you'll need to use the tools and processes provided within the YOLOv8 framework itself.

**Comment by karthikdatta98** [comment]
Does sahi work on non axis oriented yolo versions? Like obb

**Comment by glenn-jocher** [comment]
@karthikdatta98 sAHI is primarily designed for axis-aligned bounding boxes and does not natively support oriented bounding boxes (OBB) as used in some YOLO versions for rotated object detection. You would need to adapt or extend SAHI to handle OBB if required for your specific use case.

**Comment by Rohan-Python** [comment]
Yolov8 + SAHI: https://github.com/obss/sahi/blob/main/demo/inference_for_yolov8.ipynb
Thank you so much @kadirnar. I used this for detecting small craters  from satelite images and it almost detected all the craters. 
I just need one help that is for switching off the bounding boxex because there are so many detections that the segmentations are not visible. I will attach a screen snip for better understanding.
Please just help me in switching off bounding boxes. I tried Boxes=False and also Hide_lables=True  but both didn't work.
![Screenshot 2024-07-24 144930](https://github.com/user-attachments/assets/1d2dfcbb-5152-4ef2-bf9d-6996b5b10ae4)
