### ISSUE TITLE
How can I change the 'no detection' output?

### ISSUE THREAD

**Issue by MohadeseKarimi77** [ultralytics/ultralytics#4625]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can I change the 'no detection' output? The code exists in the 'result' file, and I've even modified the sentence itself, but there hasn't been any change in the output.

Another question: Inside the same function, namely 'verbose,' I've added several print statements on different lines, but I'm not getting any output from the print statements at all.
Please guide me

**Comment by MohadeseKarimi77** [comment]
I think my explanations are clear

**Comment by glenn-jocher** [comment]
Dear @MohadeseKarimi77,

Firstly, I apologize for any confusion you're encountering with the YOLOv8 code.

For your first question regarding the 'no detection' output: If you've modified the code in the 'result' file but it isn't reflected in the output, there could be a couple of reasons. Make sure that you are indeed running the modified code and not some other version cached by Python. Also, ensure your changes have been saved properly. If your changes still don't reflect, there might be another place in the code where this output is defined.

As for your second question about not seeing output from print statements: The 'verbose' function must be getting called for the print statements within it to execute. If you're not seeing any output from your print statements, it's possible that the 'verbose' function itself isn't being triggered. Double-check the conditions that need to be met for this function to execute.

I hope these pointers help guide you in the right direction. Do reach out if you have more questions. Your contributions to the YOLOv8 community are greatly appreciated.

Best,
Glenn Jocher

**Comment by MohadeseKarimi77** [comment]
Thank you very much for your responsiveness. I can't find another location in the project where the 'no detection' output is present. It exists only in the `results.py` file within the `verbose` function. I don't know how to execute the modified code without running the cached version. Regarding your second response, I should mention that the `verbose` function is called in the `predictor.py` file, and the `predictor` class inside `predict.py` file is used. Indeed, the code structure in YOLOv8 is different from its other versions, which is why I've encountered this issue. I would greatly appreciate your guidance.

**Comment by glenn-jocher** [comment]
Dear @MohadeseKarimi77, 

Thank you for your continued investigation into this matter. Your diligence is deeply appreciated by the Ultralytics team.

Regarding the 'no detection' string, you're correct that it exists in the `results.py` file within the `verbose` function. Running the modified code as opposed to the cached version does depend on Python's caching mechanism, but restarting your Python kernel or interpreter should guarantee that the latest version of the code is being executed. 

On the subject of the `verbose` function within the `results.py` file, if it's indeed being called in the `predictor.py` file and used in the `predictor` class within the `predict.py` file, I would recommend adding some print statements at key points in the call stack to help trace the program execution and help shed light on why you're not seeing the outputs that you're expecting. 

Remember, programming is a lot about step-by-step debugging, and these steps should provide more insight into the root cause of the problem.

Keep up the good work. We look forward to seeing more of your insights into improving YOLOv8.

Best,
Glenn Jocher

**Comment by MohadeseKarimi77** [comment]
Thank you. I've done the tasks you mentioned, but I still have the same issue.

**Comment by glenn-jocher** [comment]
Hello @MohadeseKarimi77,

I'm sorry to hear that you're still having issues. Debugging can be a challenging process. 

If you're sure that your changes to the 'no detection' message have been made and saved correctly in the `result.py file`, and your Python environment is using the latest version of the code, the output should reflect your changes. If this is not the case, there may be something else at play in the code that we need to uncover.

One way to investigate what's going wrong would be to track the execution flow of the program. Start from the point where the `verbose` function is called in the `predictor.py` file (as you mentioned), and add print statements before and after every function call leading to the `verbose` function. 

The print statements should help you identify the exact point where the expected output deviates from the actual output. From this, you might be able to figure out why the 'no detection' output isn't changing or why your print statements within the `verbose` function aren't working.

Your persistent efforts to understand and resolve the issue is commendable. Please continue your investigation and don't hesitate to ask if you have more questions.

Best,
Glenn Jocher

**Comment by MohadeseKarimi77** [comment]
I'm really puzzled that any change I make in the code doesn't seem to take effect at all. I've tried it both on my local environment and on Colab. I've even saved the changes multiple times.

**Comment by glenn-jocher** [comment]
@MohadeseKarimi77 hello there,

I understand your confusion and frustration. I'm sorry to hear that your changes aren't taking effect. Here are a few things you could try:

1. Make sure that the file you're modifying is the one being used by your program. Sometimes, especially in complex projects like YOLOv8, similar code could be present in multiple files.

2. If you're using an Integrated Development Environment (IDE), confirm that it's set up to save changes automatically or ensure that you're manually saving the changes before running your code.

3. If you're working with Jupyter notebooks, remember that the notebook retains the state of the variables and the functions. This means that even if you modify a function's code and run the cell, the changes won't take effect in the current session unless the function is called again.

4. Clear caches and restart your Python kernel or Python runtime environment to make sure it's using the latest version of your code.

5. Try creating a completely new, clean environment, and then running your code there. This might help if there's some issue with your current environment.

I hope this helps. Keep the faith, success in programming often comes through trying different approaches until we find the one that works. Good luck!

Best,
Glenn Jocher

**Comment by MohadeseKarimi77** [comment]
Thanks, my problem has been solved. Instead of using the CLI, I ran the model directly with Python code and my changes were applied.

**Comment by glenn-jocher** [comment]
Hello @MohadeseKarimi77,

I'm glad to hear you've found a solution and your changes have successfully been applied. Running the model directly with Python code is certainly a valid approach and I'm happy that it worked out for you with YOLOv8. 

Your perseverance through this issue will no doubt benefit other community developers who might face similar challenges. Thank you for sharing your solution with us.

Feel free to reach out if you have any more questions or insights in the future.

Best regards,
Glenn Jocher
