### ISSUE TITLE
Unable to use custom data augmentation for training yolov8 classification model

### ISSUE THREAD

**Issue by raushani2v** [ultralytics/ultralytics#4632]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Hi @glenn-jocher , I have defined my custom data augmentation class :

```
class ClassifyChangeHueAndBrightnessTransform(ImageOnlyTransform):
    def __init__(self, p=0):
        super().__init__()
        self.p = p
        
    def apply(self, img, **params):
        return ClassifyChangeHueAndBrightness(self.p)(img)
```
    
```
class ClassifyChangeHueAndBrightness:
    def __init__(self, p=0):
        super().__init__()
        self.p = p
    
    def __call__(self, im): # im = np.array HWC
        rand = np.random.uniform(0,1)
        if rand <= self.p:
            # convert the image from rgb space to hsv space
            img_hsv = cv2.cvtColor(im, cv2.COLOR_RGB2HSV)
        
            # extract the hue channel from the hsv image
            hue = img_hsv[:,:,0]

            # increment the hue values by x
            x = np.random.randint(-20, 120)
            hue = hue + x

            # if pixel values become > 180, subtract 180
            cond = hue[:, :] > 180
            hue[cond] = hue[cond] - 180

            # assign the modified hue channel to hsv image
            img_hsv[:,:,0] = hue

            
            # Change brightness..
            rand = np.random.uniform(0,1)
            if rand <= 0.2:
                # extract the brightness channel from the hsv image
                val = img_hsv[:,:,2]

                # decrese/increase the brightness
                x = np.random.uniform(0.5, 1.5)
                val = val * x

                # if brightness become > 255, it is the max brightness
                cond = val[:,:] > 255
                val[cond] = 255

                # assign the modified brightness channel to hsv image
                img_hsv[:,:,2] = val
                
            im = cv2.cvtColor(img_hsv, cv2.COLOR_HSV2RGB)
            
        return im
```
        

When I try to use this augmentation class in classify_albumentations method (augment.py file) like this :

```
def classify_albumentations(
        augment=True,
        size=224,
        scale=(0.08, 1.0),
        hflip=0.5,
        vflip=0.0,
        hsv_h=0.015,  # image HSV-Hue augmentation (fraction)
        hsv_s=0.7,  # image HSV-Saturation augmentation (fraction)
        hsv_v=0.4,  # image HSV-Value augmentation (fraction)
        mean=(0.0, 0.0, 0.0),  # IMAGENET_MEAN
        std=(1.0, 1.0, 1.0),  # IMAGENET_STD
        auto_aug=False,
):
    T = [A.RandomResizedCrop(height=size, width=size, scale=scale)]
    T += [ClassifyChangeHueAndBrightnessTransform(p=1.0)]
    T += [A.Normalize(mean=mean, std=std), ToTensorV2()]
    return A.Compose(T)
```
    
The **apply** method of class **ClassifyChangeHueAndBrightnessTransform** is not being called and I am unable to use my custom augmentation. Is there any way to do this task? 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@raushani2v hi there! 

It seems like you encountered a problem when trying to apply a custom data augmentation during the training of the YOLOv8 model.

In regard to your custom augmentation procedure, it seems to be carefully detailed and properly implemented. The issue here could be how the augmentation methods are being called or initialized during the training process. 

In YOLOv8's internal architecture, the data augmentation pipeline is initialized and then called with each batch of image data. If your custom augmentation is not being used as you expect, the first thing you should verify is whether your custom augmentation class is correctly instantiated and added to the pipeline. I'd recommend adding a print statement within the `apply` method to check if it's called.

Also, make sure the pipeline you're modifying is the one actually used during the training. YOLOv8 may utilize different augmentation pipelines based on the specific mode it's running in (like test or inference mode), which could lead to it not using your custom augmentation.

Finally, the problem could lie with how your custom augmentation interfaces with the pre-existing pipeline. Each method needs to interact correctly with the incoming and outgoing data, all while maintaining the correct data types, shapes, channel orders, etc. If there's an inconsistency between your method and the others in the pipeline, it may lead to issues.

So to debug, I recommend taking a look at the usage, instantiation, interaction, and position in the pipeline of your custom augmentation. 

I hope this helps, and don't hesitate to ask if you have more questions or need further clarification!

**Comment by u-siri-ous** [comment]
hello, I'm encountering issues with applying custom data augmentation to my YOLOv8m.
I tried specifying augmentation settings in the `data.yaml` and the `!yolo task=detect mode=train model=yolov8m.pt data=/kaggle/input/fn-aug/colors_fn_synth/data.yaml conf=0.25 pretrained=False patience=20 imgsz=256 batch=-1 save=True`, as you can see.
for reference, I'm using Kaggle to train and test.

the issue is that in training, the model doesn't take in my modification to the augmentation settings, and applies the default options instead.

**Comment by glenn-jocher** [comment]
@u-siri-ous hello! It sounds like you're having trouble getting your custom augmentation settings to take effect during training. When specifying custom augmentations in YOLOv8, it's important to ensure that these settings are correctly recognized by the training pipeline.

One common issue could be the placement and format of your augmentation parameters in the `data.yaml` file. Make sure that the augmentation settings are correctly formatted and located under the right section in your YAML file.

Here’s a quick example of how you might structure the augmentation settings in your `data.yaml`:

```yaml
train: /path/to/train/images
val: /path/to/val/images

# Augmentation settings
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
flipud: 0.0
fliplr: 0.5
mosaic: 1.0
mixup: 0.0
```

Ensure that these settings are not being overridden elsewhere in your training command or another configuration file. If the issue persists, you might want to add some debug statements in the code where augmentations are applied to see if your settings are being loaded correctly.

Hope this helps! Let me know if there's anything else you need. 😊
