### ISSUE TITLE
how to use ray tune with yolov8-seg?

### ISSUE THREAD

**Issue by haaaaak** [ultralytics/ultralytics#4638]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello! I'm looking for several ways to improve the learning performance of the custom data set even a little bit.
I want to use ray tune for efficient hyperparameter tuning.
I tried tuning the learning rate by following the ray tune guide of ultralytics.
However, tuning does not proceed and only the same error occurs.
And I tried tuning with a yolov8n.pt to make sure it didn't work only with a yolov8-seg.pt, but the same error occurred.

When I looked up the issue, there are cases where they are confronting the same situation as me, but is there no improvement to ray tune yet?

```
import torch
import ray
from ultralytics import YOLO
from ray import tune

ray.init()

model = YOLO("yolov8-seg.yaml")
model = YOLO("yolov8n-seg.pt")

result_grid = model.tune(data="data.yaml",
                         space={"lr0": tune.uniform(1e-4, 1e-1)},
                         imgsz=480,
                         epochs=20,
                         batch=4,
                         use_ray=True)
```

![gdad](https://github.com/ultralytics/ultralytics/assets/97625003/21253541-3a03-40bb-8ccd-fe3e2838fd1c)

Traceback (most recent call last):
  File "C:\Users\AI\Anaconda3\envs\yolo_seg\lib\site-packages\ray\air\execution\_internal\event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "C:\Users\AI\Anaconda3\envs\yolo_seg\lib\site-packages\ray\_private\auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\AI\Anaconda3\envs\yolo_seg\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\AI\Anaconda3\envs\yolo_seg\lib\site-packages\ray\_private\worker.py", line 2524, in get
    raise value.as_instanceof_cause()
  File "<string>", line None
ray.exceptions.RayTaskError(SyntaxError): <no detail available>

Also, I tried to upgrade ultralytics and ray tune, but there was no change.
```
pip install -U ulralytics "ray[tune]"
```

**Comment by glenn-jocher** [comment]
@haaaaak hi there, 

Thank you for your detailed explanation and your diligent efforts to solve the issue you're facing. I appreciate it!

You're correct in that 'ray tune' is a powerful tool for hyperparameters tuning. For your case, I'd like to highlight that providing a '.pt' file (like yolov8n-seg.pt) to the YOLO model won't work for initialization. Instead, you should provide a '.yaml' file (like yolov8-seg.yaml) that describes the model architecture.

The error message you're getting does suggest a syntax error, but it's not immediately clear where that's coming from. Since YOLOv8 does support integration with Ray Tune, it's likely that the issue might be located elsewhere.

It might be a compatibility issue between Ray Tune and the specific version of YOLOv8 you're using. Given that you've already tried upgrading your packages and the issue persists, it could also be due to how some aspect of your specific setup or environment interacts with Ray Tune, like GPU drivers, CUDA version, etc.

I'd recommend isolating the issue by attempting to run the code in a clean environment, and if the problem persists, do not hesitate to provide more detailed information about the error.

Again, thank you for your question. Your contribution helps make YOLOv8 and our community even stronger!
