### ISSUE TITLE
Train custom dataset and reserve coco person class 

### ISSUE THREAD

**Issue by liuhetongzi** [ultralytics/ultralytics#4640]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to train my custom dataset apple and banana and i want to reserve coco person class ，but i don‘t download person datasets，Is it impossible？Thanks。

**Comment by ExtReMLapin** [comment]
Discussed here https://github.com/ultralytics/ultralytics/issues/1707#issuecomment-1489739243


There are other places (issues/yolov5 repo) where I discussed this, Glenn even talked (from memory) about freezing the entire original model and adding another layer to it to be able to add another class.

But careful, you're going to train your model on "banana" images, but on your banana images, what do you do if there are images (persons) from the coco dataset ? do you annotate them ? do you ignore them ? how is your model going to behave ?

**Comment by glenn-jocher** [comment]
@liuhetongzi training a YOLOv8 model with custom classes while keeping the pre-trained COCO classes is a popular question in the community. The idea of freezing the original model and adding another layer to it can be a plausible approach for adding new classes. This way, your model can generate predictions for the original classes and also for new classes.

However, as you pointed out, training the model on a custom dataset may lead to a few challenges. If your custom dataset (e.g., "banana" images) includes any classes from the COCO dataset (e.g., "person"), there are some considerations.

First, consider whether you will annotate these classes in your new dataset. If you decide to annotate these classes, then the model can learn to recognize them within the context of your new classes. This could be beneficial if the presence of these classes affects the prediction of your new classes.

On the other hand, if you ignore them (i.e., not annotate these classes), the model might get confused. It could affect its ability to predict these classes. However, it depends on the model's intrinsic transfer learning capabilities and whether it can maintain its effectiveness on the original classes when trained on new ones.

Keep in mind this also depends largely on the distribution and volume of these classes in your new dataset, so there's no one-size-fits-all answer. It's more of a trial and error process to see what works best for your specific application.

I hope this helps, and don't hesitate to ask if you have more questions. Our team is always here to assist you.

**Comment by IvanVeridian** [comment]
Thanks @glenn-jocher , but how can you achieve the "freezing" of the original model? I'm also looking to add to the base model. Thanks for the help!

**Comment by ExtReMLapin** [comment]
https://docs.ultralytics.com/modes/train/?h=freeze#arguments

ctrl+f freeze

**Comment by glenn-jocher** [comment]
@IvanVeridian to "freeze" the original model means to prevent the weights of the model from being updated during training. This can be accomplished in YOLOv8 by using the `--freeze` argument during training. 

The `--freeze` argument allows you to specify the number of layers to freeze in the YOLOv8 model. For example, `--freeze 60` would freeze the first 60 layers of the model, leaving the remainder of the layers unfrozen and therefore trainable. The frozen layers would maintain their pre-trained weights.

Keep in mind that when you're freezing layers, you're essentially telling the model to ignore certain features it learned during pre-training. This can be helpful if you're confident that the already learned features are sufficient for the task at hand, but would like the model to focus on learning new, additional features from the new data.

I hope this clarifies the concept for you. Feel free to ask if you need more help.

**Comment by IvanVeridian** [comment]
Thank you @glenn-jocher ! For the quick reply. 
I am trying to train it on how to recognize hands but would like to keep the cars, person, trucks, road signs, etc. 
I'm assuming there is no way to correspond each layer with a class? Also, do we know how many layers each model has?

**Comment by glenn-jocher** [comment]
@ExtReMLapin hello, thanks for your question! When it comes down to how layers relate to classes, the YOLOv8 model doesn't associate individual classes with individual layers. The model learns features across all its layers to distinguish between the different classes. 

As for the question about the number of layers, it depends on the specific configuration of the YOLOv8 model that you're using. Each model configuration (.cfg file) will specify the number of layers in the model.

If you want to train the model on a new class (like 'hands') while preserving the ability to detect other classes (like 'cars', 'person', 'trucks', 'road signs'), you could look into strategies like transfer learning, where the model's existing weights are used as a starting point for training on your new class. 

This is unfortunately a non-trivial task as it involves keeping the pre-trained weights of the classes you mentioned whilst training the model to recognize new classes. Currently there's no straightforward way built-in into the YOLOv8 Ultralytics implementation to do this kind of partial training.

It's also worth saying that while you could theoretically freeze certain layers during training, this isn't the same as freezing certain classes - since the classes aren't tied to individual layers. 

I hope this helps! Do let us know if you have any further questions.

**Comment by ExtReMLapin** [comment]
Wrong mention, not sure if Llamma-2 answering bot or misconfigured tool to answer questions

**Comment by glenn-jocher** [comment]
Hi @IvanVeridian, I apologize for the confusion. It seems there was a miscommunication. We appreciate your understanding and patience. For YOLOv8, if you have any additional queries or if there's something specific you are looking for, please feel free to ask. We're here to help you get the information you need. Thank you for contributing to our community!
