### ISSUE TITLE
Training hyperspectral images but file descriptions corrupted

### ISSUE THREAD

**Issue by john-lihn** [ultralytics/ultralytics#4650]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I want to train spectral data through v8, but I use the data directly to explain the problem of data corruption.

`train: Scanning C:\Users\User\Desktop\datasets\train\labels.cache... 0 images, 0 backgrounds, 64 corrupt: 100%|██████████| 64/64 [ 00:00<?, ?it/s]`

When I tested the training image, I found it trained well
How can I fix it? Thanks

**Comment by glenn-jocher** [comment]
@john-lihn hi, thanks for asking this question. From the error message, it seems like the issue is stemming from some corrupted labels in your dataset. The "Scanning labels.cache... 0 images, 0 backgrounds, 64 corrupt" is indicating that all the label files YOLOv8 is trying to read are considered "corrupted".

In the context of the Ultralytics YOLOv8 implementation, "corrupted" could mean that either they do not follow the correct format or they contain values that are not valid.

Here's a quick checklist to diagnose or solve this issue:

1. Check the format of your labels: They should be in the YOLOv8 compatible format, where each line represents one bounding box with class-id and normalized x, y, width, height. 

2. Ensure the boundary values of your bounding boxes do not exceed the image dimensions, as this could be deemed as corruption by the Ultralytics implementation.

3. Make sure there are no NaNs in your label files, as these cannot be interpreted by the YOLOv8 model.

4. Confirm that all your label files exist and are accessible - sometimes this error might occur if YOLOv8 is attempting to read a file that doesn't exist or cannot be accessed.

By systematically checking these points and correcting them if necessary, you should be able to solve your issue. Good luck with your training!

**Comment by john-lihn** [comment]
```
train: WARNING  C:\Users\HSIPL\Desktop\datasets\train\hsi\11_New-1_jpg.rf.47dd88ce52b3c0d8e6c9f6caa1a12735.hdr: ignoring corrupt image/label: cannot identify image 
file 'C:\\Users\\HSIPL\\Desktop\\datasets\\train\\hsi\\11_New-1_jpg.rf.47dd88ce52b3c0d8e6c9f6caa1a12735.hdr'
```
Thank you very much for taking time out of your busy schedule to reply to the message
When this kind of message appears later, I doubt whether the length and width information of the file is fetched during the process, and this problem is caused by the problem of the file opening method

**Comment by glenn-jocher** [comment]
@john-lihn hi, thank you for reaching out and providing detailed error information. To help understand better, the warning message indicates that the file '11_New-1_jpg.rf.47dd88ce52b3c0d8e6c9f6caa1a12735.hdr' is considered corrupt and is being ignored during the training process. 

The error message "cannot identify image file" might suggest that the Ultralytics YOLOv8 cannot read the current file. In your case, the file seems to be in the '.hdr' format, which is typically used to hold metadata information for hyperspectral images. YOLOv8 is designed to work with image files, such as JPEGs or PNGs, and it might not be able to correctly interpret .hdr files as images.

With regards to your question about the length and width information, the YOLOv8 model should automatically fetch the dimensions of each image file during training. If the file can't be opened appropriately—like in the case of a .hdr file—, it would indeed raise an error because the file type cannot be interpreted correctly as an image.

To resolve this issue, please check your training data and ensure that you're supplying actual image files like JPEGs or PNGs. The image size should not be a problem as long as the image files are valid and can be opened correctly.

I hope this helps! Please let us know if you encounter any other issues.

**Comment by john-lihn** [comment]
Thanks a lot for the response
I will check the problem later, but because my image data is special (w, h, bands), and the band is greater than 10, it cannot be directly saved into JPEG and other forms, but just need to extract w, h can be read directly The hdr file is obtained, because the problem location feels that it cannot be read when accessing the cache, if you know the location of accessing the cache for this part, or read the relevant location such as the length and width of the image, I am really grateful, for other articles The problem, I have modified the part of load_image, I expect to try to randomly extract 3 bands for training, and even modify the model to complete the training of all bands of yolo

![image](https://github.com/ultralytics/ultralytics/assets/52641610/486a253d-8bf0-493a-964a-1f1d5da42ce3)

**Comment by john-lihn** [comment]
[@glenn-jocher](https://github.com/glenn-jocher) Thank you very much for your previous explanation
I later discovered that the `utils/verify_image_label `function needs to handle things such as shape. If you have any questions in the future, I will ask again. Thank you.

**Comment by glenn-jocher** [comment]
You're welcome @john-lihn! I'm glad to hear that you found the source of the problem in the `utils/verify_image_label` function. This function is indeed responsible for handling image shapes and ensuring they are appropriate for processing. 

Feel free to ask if you have any more questions or run into any other issues in the future, we're here to help. Happy coding with YOLOv8!

**Comment by john-lihn** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/52641610/c4edacd0-c495-4dfc-8ad0-9ce6846282ae)

Hello, I checked the results during the training process, but the verification found that the map is 50. I am not sure what happened.

**Comment by glenn-jocher** [comment]
@john-lihn hello, 

A mAP50 score of 0 typically indicates that the model couldn't make any accurate prediction on the validation dataset with intersection over union (IOU) over 0.5. This could be due to a variety of reasons, such as:

1. Model hasn't learned useful features yet: If you are still early in the training process, the model might not have learned to extract useful features from the data to make correct predictions. You might want to continue training for more epochs.

2. Learning rate is too high or too low: If the learning rate is not appropriately chosen, it can cause the model to learn poorly. A learning rate that is too high can cause the model to overshoot the minimum of the loss function, whereas a learning rate that is too low might result in very slow convergence, or the model getting stuck in poor local minima.

3. Poor quality or insufficient amount of training data: If you're using a small dataset, it could be possible that the model is failing to generalize well based on this data. Similarly, if the data doesn't reflect the true distribution of the problem you're trying to solve, the model might not perform well.

4. Misconfigured model or training setup: Check to make sure your model configuration and training setup is appropriate for your task. For instance, if your model is too small, it might not have the capacity to learn from your data.

Without further details, it's difficult to give a more specific answer. But checking these common pitfalls first may lead you to the root of the problem.

**Comment by john-lihn** [comment]
Hello, I used to have mAP after training 1 image (JPG) data. Later, I just tested and trained 30 times and found that after 26 times, the data finally appeared, which means the experiment was successful. Thank you very much for your assistance. You are really a godsend. Thank you very much.
![image](https://github.com/ultralytics/ultralytics/assets/52641610/7402adc9-3d3d-467b-a388-714fb9d302da)

**Comment by glenn-jocher** [comment]
@john-lihn hi there! 

I'm glad to hear that the training seems to be producing successful results after 26 epochs! It can indeed sometimes take quite a few iterations for the model to start making accurate predictions, depending on various factors such as the complexity of the data, the model configuration, and other parameters.

Remember, the learning process of deep learning models typically involves a considerable amount of trial and error along with patience, so it's rewarding to see that your perseverance has paid off.

Your kind words are very much appreciated! Remain patient and persistent and you'll overcome any obstacle that comes your way. If you have any more questions or run into any other issues, feel free to ask. Keep up the great work!

**Comment by snehitvaddi** [comment]
@john-lihn Hey!
Currently, I am working with a hyperspectral dataset (each image has 300 channels) and aim to train YOLOv8 on it.

I noticed you've managed to adapt YOLOv8 for more than 3 channels. Congrats👏
Could you list the code changes you've made to the source code like the architecture, input shape etc?

**Comment by glenn-jocher** [comment]
@snehitvaddi hi, Glad to hear about your work on hyperspectral datasets!

Now, working with more than three channels in YOLOv8 does require some modifications in the source code. The changes you'll potentially need to plan are in several places:

- Loading images: The image loading functions are designed by default to handle three color channels (RGB). These functions need to be adjusted to accommodate the higher number of channels in hyperspectral images.

- Preprocessing: Depending on your dataset, you may also need to adjust the preprocessing steps such as normalization to ensure they work as expected with the hyperspectral data.

- Model architecture: YOLOv8 is designed to work with three channels. As such, the input layer of the model needs to be updated to take inputs with the dimensionality of the hyperspectral images you're working with.

- Calculation of loss and other metrics: These could also potentially need to be adjusted depending on the specific characteristics of your dataset and how the increased channels impact the prediction output format.

With these adjustments, you should be able to train YOLOv8 using hyperspectral images. Just note that this is a pretty high-level overview, and the exact changes will depend on the specifics of your task and your dataset. Expect a bit of experimentation to get everything working smoothly.

Good luck! Your project sounds interesting and potentially quite impactful. I hope this information is helpful to you. Feel free to ask further questions as you dive into it!

**Comment by snehitvaddi** [comment]
Cool!
Thanks for the reply @glenn-jocher !
Will try your suggestions and update you if there's anything.

**Comment by glenn-jocher** [comment]
@snehitvaddi You're welcome! I'm glad you found the information helpful. Please feel free to try out the suggestions and see how they work with your hyperspectral image data. Don't hesitate to reach out if you have any questions or need further clarification on any point. Looking forward to hearing about your results. Good luck with your experiments on YOLOv8!

**Comment by john-lihn** [comment]
@snehitvaddi I’m glad you’re trying this interesting new thing. Here are a few things you can try and check out.

- The original `load envi` processing is mainly corrected in `load_image` in `data/base`. You can try to train three bands first to confirm that the loading image is normal, and then think about how to process the full band
- @issues 3432 is discussing image preprocessing and adjusting the number of input channels. It is more convenient to view it from there.

You can take a look again, and if you have any questions during the process, you can ask further questions.
In addition, I plan to modify this parameter in the future and allow him to train a better model with a small amount of data.

**Comment by glenn-jocher** [comment]
@john-lihn I'm glad you're exploring this new direction. Here's a few pointers that can help your process.

- In regards to your hyperspectral images, first ensure the 'load envi' method in the 'data/base' module correctly loads your images. You might want to initially train on three bands to verify the image loading process before proceeding with the full band data.

- For your concern about adjusting the number of input channels, Issue 3432 has a discussion going on about image preprocessing. You can follow this conversation for some insights.

Please don't hesitate to ask more questions if you face any challenges. Also, in the future, there are plans to modify certain parameters in order to enhance the model's efficiency when training on smaller datasets. Paths of progress are always fascinating!

**Comment by phyosan** [comment]
> Thanks a lot for the response I will check the problem later, but because my image data is special (w, h, bands), and the band is greater than 10, it cannot be directly saved into JPEG and other forms, but just need to extract w, h can be read directly The hdr file is obtained, because the problem location feels that it cannot be read when accessing the cache, if you know the location of accessing the cache for this part, or read the relevant location such as the length and width of the image, I am really grateful, for other articles The problem, I have modified the part of load_image, I expect to try to randomly extract 3 bands for training, and even modify the model to complete the training of all bands of yolo
> 
> ![image](https://user-images.githubusercontent.com/52641610/264514839-486a253d-8bf0-493a-964a-1f1d5da42ce3.png)

Hi, Could I check with you how to train yolov8 on hyperspectral

> @john-lihn I'm glad you're exploring this new direction. Here's a few pointers that can help your process.
> 
> * In regards to your hyperspectral images, first ensure the 'load envi' method in the 'data/base' module correctly loads your images. You might want to initially train on three bands to verify the image loading process before proceeding with the full band data.
> * For your concern about adjusting the number of input channels, Issue 3432 has a discussion going on about image preprocessing. You can follow this conversation for some insights.
> 
> Please don't hesitate to ask more questions if you face any challenges. Also, in the future, there are plans to modify certain parameters in order to enhance the model's efficiency when training on smaller datasets. Paths of progress are always fascinating!

Hi @glenn-jocher, I am curious to know how to train yolov8 model on hyperspectral image.  Is that functionality been enable?

**Comment by glenn-jocher** [comment]
@phyosan hello! Training a YOLOv8 model on hyperspectral images, which typically have more than three channels, requires significant modifications to the model, preprocessing functions, and data loading functions. As of my last update, YOLOv8 doesn't inherently support hyperspectral data, it is designed primarily for 3-channel RGB images.

However, here's a high-level outline of what needs to be done to train YOLOv8 on hyperspectral images:

1. **Data Loading**: Modify the data loader to handle hyperspectral images with multiple bands. Ensure that the images are loaded correctly with all their channels.

2. **Preprocessing**: Update the preprocessing steps to work with the multiple bands of hyperspectral data. This could include normalization across each band.

3. **Model Architecture**: Alter the model's input layer to accept the number of bands in your hyperspectral data instead of just the 3 RGB channels. 

4. **Hyperparameters**: Adjusting training hyperparameters including learning rate, batch size, and number of epochs depending on the specificities of your hyperspectral dataset.

5. **Validation**: Implement validation procedures for hyperspectral data to ensure the modified model can properly overfit a small dataset before scaling up to larger datasets.

For discussions specific to custom channel inputs like in hyperspectral imaging, issue threads in the YOLOv8 repository may provide insights from what other contributors have tried or to gather collaborative support from the community for enhancing YOLOv8 capabilities.

Remember, these changes are not trivial and require a detailed understanding of the model, data handling, and PyTorch (or the deep learning framework you're using). If you're set on this path, be prepared for a fair amount of experimentation and debugging.

**Comment by ronit450** [comment]
hello @john-lihn I am also working on images with more than three bands specefically 6 bands and 7 bands. I followed an earlier approach where I first convert all the images to .npy format and then change the loading mechanism from cv2.imread() to np.load(). But I am getting all the images as corrupted. I have also tried to load the images with rasterio but nothing seems to work

![image](https://github.com/ultralytics/ultralytics/assets/77673121/09d93eb8-9af1-44e5-9496-3bfd6fd437d9)


I am wondering if you can share how did you manage to work with more than 3 band channels.

**Comment by ronit450** [comment]
or you can tell me what things you change in verify_images function so that I can also incorporate those in my code.

**Comment by john-lihn** [comment]
You can first confirm whether the file reading method is correct, and then confirm whether the file extension name you use is within the `IMG_FORMATS` array. If not, the file reading may fail. If there are no problems, please delete the `label.catch` file and run it again to generate labels to avoid the same problem again and again.

**Comment by john-lihn** [comment]
You may encounter problems with data amplification and network preheating in the future. It is recommended that you check another version of the instructions.（# 3432）

**Comment by ronit450** [comment]
@john-lihn thankyou so much for the reply. I have followed all the instruction present in that issue #3432 but still kind of stuck. Can you please tell me how were you reading the images. For examples I have the .tiff file which I converted to .npy format for loading. Since you had .hdr, how did you manage to read it. I aldo followed the inner changes done by kearle over there.

**Comment by john-lihn** [comment]
When processing the `label`, I fill in its file name.
![image](https://github.com/ultralytics/ultralytics/assets/52641610/064a6107-cd16-4b38-ba3b-ba213e185ca5)
Because the path placement of the training data set is different from that of the image file, it is easier to compare
![image](https://github.com/ultralytics/ultralytics/assets/52641610/9c6705b1-23c3-4dfc-9f25-de514401b1f4)
This is where he is mainly reading files.
![image](https://github.com/ultralytics/ultralytics/assets/52641610/caf434e8-85f8-411a-811b-86fdc3e3f734)
Before reading the file, he needs to determine whether the file can be read and the steps for label conversion` (verify_image_label, verify_image)`. Since the combinations of different files are not the same, he needs to confirm that the file is correct. He can directly delete the annotation. Since reading `labels .cache` will not generate labels normally, so it needs to be deleted to confirm the new label.
![image](https://github.com/ultralytics/ultralytics/assets/52641610/a9c62cb9-e190-457f-82c5-27e4e362f290)

After modifying the pre-processing, the block can be read normally

However, please note that it is detecting 3-band images after all. If the detection is not as expected, the model structure may need to be modified significantly.

**Comment by glenn-jocher** [comment]
@john-lihn hey there! 👋 It looks like you've made some custom modifications to handle your dataset's unique structure. Great job on diving into the details! 🛠️

For reading .hdr files or similar formats not directly supported by common libraries like OpenCV, you might consider using specialized libraries such as GDAL or rasterio, which are more suited for handling multi-band images like yours. Here's a quick example using rasterio to read an image:

```python
import rasterio

with rasterio.open('path/to/your/image.hdr') as src:
    image = src.read()
```

This code snippet reads the multi-band image into a NumPy array, which you can then preprocess as needed for your model.

Regarding the `labels.cache` issue, you're right; deleting the `.cache` file forces the dataset to re-scan and properly process the labels, which is a good step if you're encountering issues with corrupted labels or images.

Lastly, adapting YOLOv8 for multi-band images is indeed an advanced task that might require adjustments beyond preprocessing, including changes to the model architecture itself to accommodate the additional bands.

Keep experimenting, and don't hesitate to reach out if you hit any more roadblocks!

**Comment by ronit450** [comment]
@john-lihn  Thankyou so much for the reply. I have incorporated these changes, yet getting errors. is it possible you can send me your dataset handling process so that I can get an idea about the changes. Thankyou so much for the help tho

**Comment by phyosan** [comment]
I am also looking how is HSI data cube going to be used in Yolo framework.
If any solution, pls share a link with me.

Thanks & Regards

**Comment by ronit450** [comment]
Hi @john-lihn @glenn-jocher. I hope you are doing well. I was able to put Yolov8 training for my multipectral images of 7 bands. 
While the model performs well on standard MS and RGB data, I am encountering severe performance degradation when incorporating MS+Depth or MS+RGB data. In these cases, the false positives increase dramatically, making the results even worse than when using only RGB or MS. Despite my efforts, I am unable to pinpoint the root cause of this issue.

Here are some key observations:

I verified the image quality before preprocessing and right before the validation step—everything appears correctly formatted with 5 bands.
However, as the number of bands increases, false positives rise significantly, leading to poor model performance.
When testing MS+Depth or MS+RGB, the results are even worse than standard RGB or MS alone, which is highly unexpected.
I am struggling to understand why increasing spectral information is leading to more false positives rather than improving detection accuracy. 


Maybe there is some issue with augment.py, can you please help me in this.

**Comment by glenn-jocher** [comment]
Hi there! For multispectral/hyperspectral data in YOLO, key areas to check are:

1. **Data Normalization**: Ensure each spectral band is normalized independently in your preprocessing (reference: [Data Augmentation docs](https://docs.ultralytics.com/modes/train/#augmentation-settings))

2. **Channel Compatibility**: Verify your augmentations in `augment.py` handle N-channels correctly (some transformations might distort spectral relationships)

3. **Model Capacity**: Deeper layers may need adjustments to effectively process high-dimensional spectral features. For implementation patterns, see Issue #3432 discussing multi-channel adaptations.

If you can share a minimal reproducible example, we can offer more specific guidance. For commercial hyperspectral implementations, consider exploring our [Enterprise License](https://ultralytics.com/license) for prioritized support.

**Comment by ronit450** [comment]
So In MSD or RGB+MS training, I saved the detections using validation, and I found most of the detections were being done on the corner of the image. This was not the case with RGB or 4-channel MS. I am not sure what part of code is causing that. 

@glenn-jocher  @john-lihn 
![Image](https://github.com/user-attachments/assets/756ea313-6f7e-41c8-a072-eae993c4a045)

**Comment by glenn-jocher** [comment]
Hi there! For multi-channel inputs, ensure your data pipeline correctly handles the additional spectral bands. Key areas to check:  
1. **Input normalization** - Verify each spectral band is normalized independently ([Data Augmentation docs](https://docs.ultralytics.com/usage/cfg/#augmentation-settings))  
2. **Augmentation compatibility** - Some spatial transforms may need adjustment for non-RGB data ([augment.py reference](https://docs.ultralytics.com/reference/data/augment/))  

If you can share a [minimal reproducible example](https://docs.ultralytics.com/help/minimum-reproducible-example/), we can offer more specific guidance. For commercial implementations, consider our [Enterprise License](https://ultralytics.com/license) for prioritized support.
