### ISSUE TITLE
Training a few epoch memory suddenly OOM

### ISSUE THREAD

**Issue by mpj1234** [ultralytics/ultralytics#467]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### During the training, there was no problem with the first few epoch, but suddenly OOM happened.

![@F~`LB~I) %@WPALBMC9CEI](https://user-images.githubusercontent.com/78143172/213176902-1bb42780-9544-4cef-9f89-13cccf275da5.png)

### Environment

YOLOV8S

device：A40 48G
environment：
torch                          1.10.0+cu113
torchvision                    0.11.1+cu113
opencv-contrib-python          4.2.0.32
opencv-python                  4.2.0.32
python 3.8.10

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
@mpj1234 what's your batch size? Reducing that might help.

**Comment by mpj1234** [comment]
The bug of OOM is batch size = 120.

Now it is batch size = 100, and eight epoch have been run, so there is no problem for the time being.

**Comment by glenn-jocher** [comment]
👋 Hello! Thanks for asking about **CUDA memory issues**. YOLOv5/v8 🚀 can be trained on CPU, [single-GPU](https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data), or [multi-GPU](https://github.com/ultralytics/yolov5/issues/475). When training on GPU it is important to keep your batch-size small enough that you do not use all of your GPU memory, otherwise you will see a CUDA Out Of Memory (OOM) Error and your training will crash. You can observe your CUDA memory utilization using either the `nvidia-smi` command or by viewing your console output:

<img width="800" alt="Screenshot 2021-05-28 at 12 19 51" src="https://user-images.githubusercontent.com/26833433/131122318-8141d1ce-13de-44bf-bbdc-487bad442ff0.png">

### CUDA Out of Memory Solutions

If you encounter a CUDA OOM error, the steps you can take to reduce your memory usage are:

- Reduce `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s > YOLOv5n
- Train with [multi-GPU](https://github.com/ultralytics/yolov5/issues/475) at the same `--batch-size`
- Upgrade your hardware to a larger GPU
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

### AutoBatch

You can use [YOLOv5 AutoBatch](https://github.com/ultralytics/yolov5/pull/5092) (NEW) to find the best batch size for your training by passing `--batch-size -1`. AutoBatch will solve for a 90% CUDA memory-utilization batch-size given your training settings. AutoBatch is experimental, and only works for Single-GPU training. It may not work on all systems, and is not recommended for production use.

<img width="1746" alt="Screenshot 2021-11-06 at 12 31 10" src="https://user-images.githubusercontent.com/26833433/140608327-9c0c0baf-a0ee-4551-a4ff-5ee26b155c51.png">

Good luck 🍀 and let us know if you have any other questions!

**Comment by mpj1234** [comment]
Yesterday, after I switched batch size=100, I ran 67 epochs normally, but at 68epoch, I suddenly allocated a lot of memory, and OOM appeared. I think there may be memory leakage in the code.

![DQ%SE3%`F95QR@SKB_ _`N0](https://user-images.githubusercontent.com/78143172/213337732-e581b6c7-63c8-4f6d-8788-9a76221a4f72.png)

I'm switching to automatic batch now, and I'm still experimenting. The automatic batch allocation is 151.

![78%JVE MQ2T$_XJPD{N01MM](https://user-images.githubusercontent.com/78143172/213337950-628600cc-cbe8-4855-a095-4f28d92bbfd8.png)


I hope if it's not a bug, explain why after training so many epoch, I suddenly have to allocate a lot of video memory.

**Comment by mpj1234** [comment]
This is the automatic batch, and it is still OOM.
I'm surprised that epoch in front is fine, but OOM in the back suddenly. Is there an explanation for this?

![TY@CATXAACST~R5%XOT5I1Y](https://user-images.githubusercontent.com/78143172/213339925-7feb63e3-cfdd-43b3-a526-0f3f992cea9e.png)

**Comment by Laughing-q** [comment]
@mpj1234 hi, looks the number of instances in your dataset is variable. The memory is instances-related, the more instances you got the more memory would be occupied. So the OOM could happen when you got more instances for a sudden in one batch. You have to reduce batch-size or use small model to solve this OOM issue.
![c0deb2d6-ef8d-4b12-90cb-f5f9e20b9dd0](https://user-images.githubusercontent.com/61612323/213385574-e9770db2-289e-4090-814f-951f561e1564.jpeg)

**Comment by mpj1234** [comment]
ok, Thanks♪(･ω･)ﾉ

**Comment by Petros626** [comment]
for me the following things seem to work:
1. reduce the batch size
2. call `torch.cuda.empty_cache()` before training job, some frameworks do this automatically.
3. `os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"`

**Comment by glenn-jocher** [comment]
@Petros626 thank you for sharing these suggestions! Reducing batch size and using `torch.cuda.empty_cache()` are effective, and setting `PYTORCH_CUDA_ALLOC_CONF` can help manage memory fragmentation. These approaches align well with best practices for resolving CUDA OOM issues.
