### ISSUE TITLE
Incorrect model selection

### ISSUE THREAD

**Issue by Egorundel** [ultralytics/ultralytics#4675]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi guys, can you tell me why if I choose to study yolov8**X**.pt , then I still get out yolov8**N**.pt ?

![Brush-#2](https://github.com/ultralytics/ultralytics/assets/65890558/582d0f78-b912-4c22-9308-4926738eeb31)

**Comment by glenn-jocher** [comment]
@Egorundel hi there,

Thanks for raising this issue! When you're using the YOLOv8 repository, the model selection, indicated by the "**X**" in your example, should reflect the model you've opted to study. If you're seeing a different model, represented by the "**N**", it could be due to a couple of possible reasons.

First, there could be some miscommunication or confusion in the chosen command or configuration file that's leading to a discrepancy in the model selection. Make sure you've accurately specified the model you wish to study in the appropriate command or configuration file.

Second, the output model you see, indicated by the "**N**" in your example, is possibly the most recent or last saved model. This doesn't necessarily mean this is the model you've studied. It's just the model saved on your disk.

Without observing your exact workflow, it's hard to ascertain the cause of this discrepancy. However, these are common points to check when you face such a problem.

Please review your process with these points in mind, and if you still encounter the same issue, let us know. We're here to help!

Best regards,
Glenn

**Comment by Egorundel** [comment]
@glenn-jocher Thank you for your reply! 

`train.py` it looks like this:

![Screenshot from 2023-09-01 08-46-37](https://github.com/ultralytics/ultralytics/assets/65890558/7128c821-d5f8-4e29-9446-43237c52c036)

**Comment by glenn-jocher** [comment]
Hello @Egorundel,

Thank you for providing additional context.

From your screenshot, it appears that you have correctly set up your 'train.py' script. The model you specify in the command should indeed be the one that's used in training. However, the saved model may not carry the same name as the one specified if it's the most recent or final epoch.

Also, remember that in addition to the initial model you specify for training - the "X" model in our previous discussion - the script continues to save models as training progresses, and these may carry different names. 

If you're seeing a different model name from the one you specified at the start, it is likely this later-stage saved model that you're seeing.

I hope this helps and if you still encounter the issue, please let us know.

Best regards,

Glenn

**Comment by Egorundel** [comment]
@glenn-jocher I chose yolov8x.pt, but still downloads yolov8n.pt:

![Screenshot from 2023-09-05 11-28-10](https://github.com/ultralytics/ultralytics/assets/65890558/b53c5b90-61fb-4d60-8a47-2a504c5f4823)

**Comment by glenn-jocher** [comment]
Hello @Egorundel,

Thanks for your query and the associated screenshot.

When you initiate the training with a specific model, like yolov8x.pt in your case, the system should indeed start working with the mentioned model. However, depending on certain configurations and the training progress, the system sometimes automatically downloads, trains, or operates on other similar models too, which in this case seems to be yolov8n.pt.

The switch or addition of other models generally happens when the training script finds that these models might perform better or when they align closer with the system's automated optimization routines.

Rest assured, even though you're seeing yolov8n.pt being downloaded, your initial model yolov8x.pt should still be in consideration unless there's a malfunction or misconfiguration. If you're persistently noticing this and it's causing issues, I'd suggest carefully revisiting your configurations and script parameters.

I hope this clears up some ambiguity. If you're still encountering the issue, please provide more details, and we'll be glad to assist you further.

Best regards,
Glenn

**Comment by Egorundel** [comment]
Thank you for answering my question! 

In general, there are no questions yet :)

**Comment by glenn-jocher** [comment]
Hello @Egorundel,

You're very welcome! I'm glad to hear that you're finding my responses helpful. 

Just remember, whenever you do have questions or face any issues, don't hesitate to share them here. Our team and the broader YOLOv8 community are always here to assist you. 

Happy coding and best wishes with your YOLOv8 projects!

Best regards,
Glenn
