### ISSUE TITLE
Incorrect class definition

### ISSUE THREAD

**Issue by Egorundel** [ultralytics/ultralytics#4676]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Friends, good afternoon! 

I have a problem... For some reason, my classes are incorrectly defined. In files with class_names, everything seems to be specified correctly... Can you tell me what the problem might be? 

P.S. Don't pay attention to the accuracy, since I didn't do enough epochs

Attached screenshots:

**RESULTS:**
![Cars_driving_on_an_expressway](https://github.com/ultralytics/ultralytics/assets/65890558/b03f9482-2f62-4b37-a9a1-d44ce2c0a1f0)

**CLASS.NAMES** and **CLASSES.TXT**:
![Screenshot from 2023-08-31 17-00-56](https://github.com/ultralytics/ultralytics/assets/65890558/dfd4e0db-8d1c-4c83-bdbe-72f2103fd446)

**LABELMAP,TXT** and **CUSTOM.YAML**:
![Screenshot from 2023-08-31 17-02-32](https://github.com/ultralytics/ultralytics/assets/65890558/c77a8640-fbef-40c6-983d-0ee630a165a9)

**Comment by glenn-jocher** [comment]
@Egorundel hello,

I appreciate your thoroughness in asking this question, it's helpful to see your input files and the resulting detections.

It's crucial to have the class labels in all relevant files match exactly, both in terms of spelling and order. This means that your `class.names`, `classes.txt`, `labelmap.txt` and the class labels defined under `names` in your `custom.yaml` should all match perfectly. It looks like you've already checked this, and everything is good.

From your screenshots, it’s a bit challenging to determine the exact problems. But, typically such errors occur due to inconsistency in annotation data, label index mismatch, or data preprocessing issues. Here are a few general troubleshooting tips:

1. **Verify your dataset**: Check if the bounding boxes and labels in your dataset are correctly annotated. Inconsistencies in this information can lead to misclassified objects.

2. **Check label index**: The index position in your classes definition files should match with the label index in your annotation files.

3. **Data preprocessing**: Ensure that there are no issues during the data preprocessing stage. This includes checking the formats of your input data and ensuring they are compatible with YOLOv8's expectations.

Lastly, if you have trained your model for a small number of epochs, underfitting could also be a reason for incorrect class definitions. Training for more epochs might help your model to correctly learn the class definitions.

Let me know if these suggestions help, or if you require more guidance!

Best,
Glenn

**Comment by Egorundel** [comment]
@glenn-jocher Glenn, thanks for the detailed answer! I trained the network on 3 epochs)))

I will try on more and more epochs!

But, I wanted to ask about the format of writing classes in class.names files, classes.txt , labelmap.txt . Each class should be written on a new line, as I have done now? Or in some of the files they need to be separated by a comma or a space, for example? I just haven't found an example of exactly how to write classes to these files anywhere, and I've written classes in all of them, where each class is on a new line.

**Comment by glenn-jocher** [comment]
Hello again @Egorundel,

You're on the right track! When it comes to defining classes in the `class.names`, `classes.txt`, and `labelmap.txt` files, you should indeed list each class on a new line as you have been doing. Here's an example if you have three classes, 'car', 'bus', 'truck':

```
car
bus
truck
```

No need to add commas or spaces. It's important that your classes are listed in the same order across all files and match the order of classes in your dataset's annotations.

Remember, keep training! More epochs generally lead to improved accuracy and better class definitions.

Best of luck with your further training,
Glenn

**Comment by Egorundel** [comment]
@glenn-jocher Thanks!

**Comment by glenn-jocher** [comment]
@Egorundel,

You're welcome! I'm glad to have been of assistance. Should you have any other inquiries or run into further challenges, do not hesitate to reach out. We're always here to help.

Happy training with YOLOv8!

Best,
Glenn
