### ISSUE TITLE
Invoke the trained YOLOv8 model?????

### ISSUE THREAD

**Issue by Wang-taoshuo** [ultralytics/ultralytics#4685]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Help needed from the experts! How do I load a trained YOLOv8 model? I did some research and found out that after each training session, is the model saved as 'best.pt'? Also, I need to use it for real-time video analysis. How can I properly invoke it?

### Additional

Is this where I can find the trained model? A:\yolo8_segmentation\runs\segment\train11(No)\weights
### 
import torch
import torchvision.models as models
import cv2
import numpy as np
from ultralytics import YOLO

model = YOLO() 
model.load_state_dict(torch.load('A:/yolo8_segmentation/runs/segment/train11(沒)/weights/best.pt.tar')['state_dict'])
### 
the error message
### 
發生例外狀況: AttributeError
'YOLO' object has no attribute 'load_state_dict'
  File "A:\yolo8_segmentation\INSTANCE_1.py", line 8, in <module>
    model.load_state_dict(torch.load('A:/yolo8_segmentation/runs/segment/train11(沒)/weights/best.pt.tar')['state_dict'])
AttributeError: 'YOLO' object has no attribute 'load_state_dict'
###

**Comment by glenn-jocher** [comment]
@Wang-taoshuo hello there,

I'm glad to see that you're interested in using our YOLOv8 model! You're absolutely correct, after each training session, the model is saved as 'best.pt', which contains the weights that achieved the best validation results throughout training.

In terms of real-time video analysis, the YOLOv8 model can indeed perform tasks like this efficiently. The primary functionality enabling real-time object detection in YOLO models is indeed integrated in the 'Predict' mode, where you can input video files instead of just static images.

However, in your script there seems to be a mistake when trying to load the trained weights into the model. The 'YOLO' object does not have a 'load_state_dict' method. The proper way to load the weights from your 'best.pt' file produced by training in YOLOv8 is by using the `attempt_load()` function from YOLOv8's utils file. This function loads and, if necessary, merges checkpoint weights, and you should supply it with the path to your 'best.pt' file.

The AttributeError you're seeing comes from attempting to use the 'load_state_dict' method, which is not part of the YOLO API.

Hope this helps! Let us know if you have any further questions.

Best,
Glenn Jocher

**Comment by Wang-taoshuo** [comment]
@glenn-jocher   How can I properly call this model, and which paper should I consult for real-time recognition programming
Please recommend one for me. I am currently involved in related research. thk(謝謝你)

**Comment by glenn-jocher** [comment]
@Wang-taoshuo hello and thank you for your interest in YOLOv8!

To properly call the model, you'll need to load the weights of the trained model using the provided utilities in YOLOv8. Specifically, you'll want to use the 'attempt_load()' function available in the utils file. Simply supply the path to your trained model weights when invoking this function.

For obtaining real-time predictions using the loaded model, you'll want to use the `detect()` function from the models module, feeding in your frame from the real-time video. Ensuring optimal performance here might require some tuning of the input and output dimensions to align with your use case, as well as adjusting the confidence threshold to manage trade-offs between speed and accuracy.

Regarding the research component of your query, the principal paper to consult for understanding the inner workings of YOLOv8 would be the original YOLOv8 paper by Ultralytics. It provides a comprehensive overview of the architectures, techniques, and principles leveraged in YOLOv8.

Remember, the essence of YOLO's real-time ability lies in its single-pass architecture, where it looks at the image once to find objects, rather than the traditional two-pass system of region proposal followed by classification. Understanding this principle will aid your real-time recognition programming efforts.

I hope this gives you a good starting point and wish you the best in your research. Keep exploring and happy coding!

Regards,
Glenn Jocher
