### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 0)

### ISSUE THREAD

**Issue by Aryanjb** [ultralytics/ultralytics#4691]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Thank you for the code, I have an issue while training a custom dataset for Pose detection. Please help me to fix this issue 

1. I have annotated the 4- key points and bounding box(2 points) for the solar panel of the satellite using CVAT, downloaded xml file, and converted into .txt file using the code(I'm attaching a screenshot).

![clb2](https://github.com/ultralytics/ultralytics/assets/142418088/284b02ef-aa34-49cf-bc42-a36e66303602)
![img (5)](https://github.com/ultralytics/ultralytics/assets/142418088/3d195033-a211-43a4-821e-d3486606797d)
![txt file](https://github.com/ultralytics/ultralytics/assets/142418088/6c740182-b3e5-4a01-987c-3debb2b98abb)
![clb1](https://github.com/ultralytics/ultralytics/assets/142418088/0de524aa-2d06-4402-b90a-441cfcf06345)
![code](https://github.com/ultralytics/ultralytics/assets/142418088/20779c65-42a8-4d17-99c6-8f4f372bfeed)

2. This my dataset format, I'm using colab to do the training
├── data
 ├── train
 │   ├── images
 │   └── labels
 ├── val
 │   ├── images
 │   └── labels
├── config.yaml

3. I'm attaching the screenshots of images, xml file and .txt file along with the Google Colab traing errors

**Comment by glenn-jocher** [comment]
@Aryanjb hello,

Thank you for providing the detailed information and screenshots. The error you're encountering, `ValueError: not enough values to unpack (expected 3, got 0)`, typically points to an issue in the data format or structure. Even though you've converted your labels to .txt format from the CVAT XML, keep in mind they must be in correct YOLOv8 format. 

Ensure that your .txt files adhere to the specific YOLOv8 format requirements: one row per object in the image, with each row consisting of [class, x center, y center, width, height]. All these values should be normalized in the range [0, 1]. Since you're doing pose detection with key points, make sure those keypoints are represented correctly as well and are appropriately labeled in your provided config.yaml.

Regarding your directory structure, it seems to be correct. Make sure your config.yaml file points to the correct path for training and validation images, and labels. The provided data structure should work with `data` being the root directory, and `train` and `val` as subdirectories each containing `images` and `labels` subdirectories.

Please double-check these aspects of your dataset and your .yaml configuration file, as they are the most likely sources of this unpacking error. You may need to debug your conversion script to ensure it is producing the correct output format.

Thanks for working with Ultralytics YOLOv8 and don't hesitate to write back if you need further assistance!
