### ISSUE TITLE
"An error occurred: cost matrix is infeasible"

### ISSUE THREAD

**Issue by brainer3220** [ultralytics/ultralytics#4711]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Validation

### Bug

```
1/1      16.4G     0.5232      209.3     0.3511          9        640: 100%|██████████| 27492/27492 [6:36:19<00:00,  1.16it/s]
Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|          | 0/3437 [00:00<?, ?it/s]
An error occurred: cost matrix is infeasible
self.metrics, self.fitness = self.validate()
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 496, in validate
    metrics = self.validator(self)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/engine/validator.py", line 173, in __call__
    self.loss += model.loss(batch, preds)[1]
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 409, in loss
    loss = self.criterion((dec_bboxes, dec_scores),
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/models/utils/loss.py", line 256, in forward
    total_loss = super().forward(pred_bboxes, pred_scores, batch)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/models/utils/loss.py", line 236, in forward
    total_loss = self._get_loss(pred_bboxes[-1],
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/models/utils/loss.py", line 195, in _get_loss
    match_indices = self.matcher(pred_bboxes,
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/models/utils/ops.py", line 107, in forward
    indices = [linear_sum_assignment(c[i]) for i, c in enumerate(C.split(gt_groups, -1))]
  File "/opt/conda/lib/python3.10/site-packages/ultralytics/models/utils/ops.py", line 107, in <listcomp>
    indices = [linear_sum_assignment(c[i]) for i, c in enumerate(C.split(gt_groups, -1))]
ValueError: cost matrix is infeasible
2023-09-03 14:24:47,601 sagemaker-training-toolkit INFO     Waiting for the process to finish and give a return code.
2023-09-03 14:24:47,601 sagemaker-training-toolkit INFO     Done waiting for a return code. Received 0 from exiting process.
2023-09-03 14:24:47,602 sagemaker-training-toolkit INFO     Reporting training SUCCESS
```

### Environment

Using RT-DETR: Ultralytics lates version.

On AWS SageMaker

```python
estimator = PyTorch(entry_point='train.py',
                    source_dir='./',
                    spot_instacne=True,
                    dependencies=['requirements.txt'],
                    role=sagemaker.get_execution_role(),
                    instance_count=1,
                    instance_type='ml.p3.2xlarge', #ml.p3.2xlarge
                    framework_version='2.0',
                    py_version='py310',
                    output_path=s3_output_path,
                    hyperparameters={
                        'epochs': 1,
                        'batch-size': 6
                    },
                    volume_size=150,
                   )
```

### Minimal Reproducible Example

```python
if __name__ == '__main__':
    # os.environ['CUDA_LAUNCH_BLOCKING'] = "1"
    parser = argparse.ArgumentParser()
    parser.add_argument('--epochs', type=int, default=3)
    parser.add_argument('--batch-size', type=int, default=32)

    args, _ = parser.parse_known_args()

    aws_access_key_id = 'ACCESS_KEY'
    aws_secret_access_key = 'SECRET_KEY'
    region_name = 'ap-northeast-2'

    s3 = boto3.client('s3', aws_access_key_id=aws_access_key_id, aws_secret_access_key=aws_secret_access_key, region_name=region_name)

    # Load SageMaker Env Variable
    data_dir = os.environ.get('SM_CHANNEL_ALL_DATA', './all_data/')  # Default to './all_data/' if not found

    # Get dataset.yaml, train.txt, test.txt file path
    dataset_file = os.path.join(data_dir, 'dataset.yaml')
    train_txt = os.path.join(data_dir, 'train.txt')
    test_txt = os.path.join(data_dir, 'test.txt')
    
    os.system(f'ls -l {data_dir}')
    os.system(data_dir)

    model = RTDETR('rtdetr-x.pt')
    try:
        model.train(data=dataset_file, batch=args.batch_size, epochs=args.epochs)
    except Exception as e:
        print("An error occurred:", e)
        traceback.print_exc()

    # Create boto3 client
    s3_client = boto3.client('s3')

    # Upload the artifacts in 'runs/' directory to S3
    # Get current time
    current_time = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

    s3_output_bucket = 'AWS_BUCKET'
    s3_output_folder = f'store/artifacts/{current_time}'

    runs_dir = 'runs/'
    for root, dirs, files in os.walk(runs_dir):
        for file in files:
            file_path = os.path.join(root, file)
            s3_file_path = os.path.join(s3_output_folder, file)
            s3_client.upload_file(file_path, s3_output_bucket, s3_file_path)

```

### Additional
```yaml
names:
  0: 199500959
  1: 201602610
...
nc: 5088
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. RTDETR training and inference run correctly, these features are tested every 24 hours and on every commit:

<img width="1673" alt="Screenshot 2023-09-03 at 22 41 14" src="https://github.com/ultralytics/ultralytics/assets/26833433/eb933148-455b-4acc-ad76-b46d6e94a48e">


We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by brainer3220** [comment]
@glenn-jocher
This is NOT YOLO models.

The RT-DETR model.

And _Python3.10_, _Ultalytics latest_ and _PyTorch 2.0_.

I think too many class cause loss to infinity, class loss over the 200 on training but complete, then validation to get the above issue.

**Comment by glenn-jocher** [comment]
@brainer3220 hello, thanks for reaching out with your issue related to running RT-DETR model on AWS SageMaker with Python 3.10, the latest Ultralytics version, and PyTorch 2.0. You've mentioned that you're experiencing an issue with the class loss going over 200 during training, which results in an issue during validation. 

Usually, a loss that goes to infinity could possibly indicate that the learning rate is too high. You could try reducing the learning rate. If reducing it doesn't work, it might be worth checking if your labels are correct and consistent with the YOLOv8 standards. 

The loss to infinity can't necessarily be attributed to having a high number of classes. If your classes and labels are defined correctly, the model is capable of handling a large number of classes. 

Lastly, ensure your environment dependencies like CUDA drivers are up-to-date and your PyTorch installation is compatible with them. Sometimes, these underlying discrepancies can cause destabilization in model training.  

Please give these suggestions a try and let us know if the issue still persists. We're here to assist you with further troubleshooting if necessary.

**Comment by bartbuaa** [comment]
I meet one similar question when training rt-detr-x on a custom dataset with 600 classes.
The error log shows as '**catch an Exception:cost matrix is infeasible**'.
However, when classes are reduced from 600 to single class which means the class-aware problem is regarded as an object proposal detection problem, the code is running correctly.
I am not quite sure if the problem lays on the large learning rate which is set to be 1e-5 in my code.
Just sharing what I found, if you have any idea to fix this problem, plz sharing the discovery here. Thanks.

**Comment by glenn-jocher** [comment]
@brainer3220 hi, thanks for sharing your situation regarding training the RT-DETR-X model on a custom dataset with 600 classes. The error message 'catch an Exception: cost matrix is infeasible' indicates a problem with the optimization during training, particularly an issue with the cost matrix generated for solving the assignment problem during object detection.

The fact that your model runs correctly on a single class suggests that the issue might be related to the use of multiple classes, it might be the model's tolerance for larger class numbers or how these classes are represented in the data.

You mentioned a learning rate of 1e-5, which generally is a reasonable value — however, it's always a good idea to experiment with different rates. A smaller learning rate might help, but be aware that it also generally slows down the rate of learning.

Also, please ensure your data annotation and class distribution are correct. Any inconsistency in these could lead to issues during training, especially when dealing with a large number of classes.

Finally, you might want to be certain that your hardware and installation environment are appropriately handling the complexity of large class numbers. Issues can sometimes be traced back to a lack of computational resources.

It's always beneficial for us to learn from each other, so don't hesitate to keep sharing your discoveries. Thank you for your valuable input!

**Comment by bartbuaa** [comment]
@glenn-jocher Hi, thanks for your replies.
I print out some detailed logs and find the problem mainly lies on the cost of class.
The value of cost_bbox and cost_giou seems to be normal however class prediction is somewhat unusual. 
Since the cost of class is inf, it will trigger the bug of **scipy-linear_sum_assignment** when calculating the Hungarian matching cost. This bug can be found in https://github.com/scipy/scipy/issues/6900 and it is very common.
I am trying to find someway to solve it. Just sharing what I found. Thanks.
![image](https://github.com/ultralytics/ultralytics/assets/116870048/5cde433a-96b7-43d1-a01a-6ec5f1e0e84d)

**Comment by glenn-jocher** [comment]
Hello @bartbuaa! It's very insightful of you to identify the issue being tied to the class prediction cost during cost matrix computation in the Hungarian matching algorithm. You've identified a crucial part which can indeed potentially throw an error when the cost is 'inf' (infinite).

Your investigation into the cost_bbox and cost_giou yielding normal values, but the class prediction showing an aberration is a solid direction toward diagnosing the problem. The abnormal class prediction can indeed result in an 'inf' cost which subsequently triggers the bug in the scipy's linear_sum_assignment function that you mentioned.

Working toward a resolution, you could consider exploring the pre-processing of your labels and the subsequent class assignment. Anomalies could arise due to the format or the nature of these labels, especially when dealing with a large number of classes.

On another note, considering normalization or certain constraints for your 'inf' values might assist in mitigating the bug you've pointed out, given that Hungarian assignment is sensitive to 'inf' costs.

It's great to see you making this progress and contributing to the community's understanding. We appreciate your update and wish you all the best in finding a solution. Let us know if you make further strides. Thank you!

**Comment by bartbuaa** [comment]
@glenn-jocher Hi, thanks for your advices. I think the bug seems to be located.
The position is in line 87 ultralytics/models/utils/ops.py.

if self.use_fl:
            neg_cost_class = (1 - self.alpha) * (pred_scores ** self.gamma) * (-(1 - pred_scores + 1e-8).log())
            pos_cost_class = self.alpha * ((1 - pred_scores) ** self.gamma) * (-(pred_scores + 1e-8).log())
            cost_class = pos_cost_class - neg_cost_class
else:
            cost_class = -pred_scores

In the very start of training, most of the value **pred_scores** is very close to 0. 
That means the score of (-(pred_scores + 1e-8).log()) in pos_cost_class is very close to 1e-8.
Notice the type of pred_socre is torch.float16 half precision. Then the bottom limit is 2^(-24) which is almost 6e-8.
Since 1e-8 is smaller than 6e-8, then the value of **pred_scores + 1e-8** is regarded as 0 indeed.
Then the value of pos_cost_class will be inf. That is the reason why the score of final cost matrix C is inf.
The solution is just set the hyper-parameter of 1e-8 to be 1e-7.
I am not quite sure my discovery is true.  Just sharing what I found. Thanks.

**Comment by glenn-jocher** [comment]
Hello @bartbuaa, 

Your investigation into this issue is greatly appreciated and it's indeed very insightful. Thank you for sharing your findings with us!

Your observation about the 'pred_scores' values being close to 0 at the start of training leading to 'pos_cost_class' value being 'inf' makes perfect sense. And as you pointed out, in half-precision, 'pred_scores + 1e-8' could indeed represent 0 which then leads to 'pos_cost_class' getting an 'inf' value. 

Changing the hyper-parameter value from 1e-8 to 1e-7, as you suggested, could potentially resolve this by ensuring that the sum remains within the range that half-precision can represent, thereby preventing 'inf' costs which in turn results in the 'cost matrix is infeasible' issue

It's great to see you making such progress in diagnosing this issue. Please feel free to validate this approach by conducting some tests if possible. Your contributions are invaluable to the community and we hope to learn more from your future findings.

Thank you again for your efforts and for sharing your discoveries with us.
