### ISSUE TITLE
export onnx error

### ISSUE THREAD

**Issue by lolo77777** [ultralytics/ultralytics#4716]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I trained a segmentation model using yolov8 segment, but when I used the export command to convert the onnx model, the following error was prompted. How should I handle it?
`File "C:\Users\lo\.conda\envs\Yolov8\lib\site-packages\ultralytics\models\sam\build.py", line 156, in build_sam
    raise FileNotFoundError(f'{ckpt} is not a supported sam model. Available models are: \n {sam_model_map.keys()}')`
`FileNotFoundError: e:\Home\Pictures\SampleData\Seg\YoloSH\runs\segment\train5\weights\best.pt is not a supported sam model. Available models are:
 dict_keys(['sam_h.pt', 'sam_l.pt', 'sam_b.pt', 'mobile_sam.pt'])`

**Comment by glenn-jocher** [comment]
@lolo77777 hello,

From the error message you provided, it appears that the program is looking for specific model file names (`sam_h.pt`, `sam_l.pt`, `sam_b.pt`, `mobile_sam.pt`) to locate a SAM model, but instead found a different file (`best.pt`). It's possible that there's a mismatch between the expected model format and the one you're providing during export.

Your checkpoint file (`best.pt`) may not match the SAM model format because the 'export' command is designed to work with detection models by default. If you've trained a segmentation model using the segment feature of YOLOv8, converting it directly to ONNX using the default export routine may not work.

Moving forward, you may want to check if the export mode supports segmentation models in the current version of YOLOv8. If it does, you'll find the necessary instructions to guide you through the process in the YOLOv8 documentation. If it doesn't, you might need to perform additional steps to convert your trained segmentation model to the ONNX format.

Hope that assists you!
