### ISSUE TITLE
can't predict onnx on cuda

### ISSUE THREAD

**Issue by YanceyHo** [ultralytics/ultralytics#4718]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have the device parameter when predicting like this，however, it still runs on the **cpu**
```
model = YOLO(r'best.onnx', task='detect')
model.predict(source=r'xxx.jpg', device='0')
```
I tried debug and found that **AutoBackend.__init__** in the **ultralytics/nn/autobackend.py** file
```
# Set device
        cuda = torch.cuda.is_available() and device.type != 'cpu'  # use CUDA
        if cuda and not any([nn_module, pt, jit, engine]):  # GPU dataloader formats
            device = torch.device('cpu')
            cuda = False
```
when judgment the cuda whether onnx is missing? i add onnx in this judgment, model is runing on cuda
`if cuda and not any([nn_module, pt, jit, engine, onnx]):  # GPU dataloader formats`

**Comment by glenn-jocher** [comment]
@YanceyHo thank you for pointing this out and providing possible solutions.

When initializing the `AutoBackend`, the `UltraLytics` code currently checks whether CUDA is available and if the specified device is not 'cpu'. If CUDA is available, it checks whether any of the modules (nn_module, pt, jit, engine) are enabled. If none of them are, it forces the device type to 'cpu'.

In the case of ONNX, if ONNX inference is not considered in this check, even though we may have CUDA available and ONNX is expected to run on the GPU, the device may still be set as 'cpu'.

Your proposition to add 'onnx' as one of the options in the check when setting the device is insightful. This would give the ONNX model the option to run on GPU if CUDA is available. We appreciate your contribution to the discussion and will review the proposal for possible integration.

Please remember that ensuring your CUDA drivers and PyTorch version are compatible and up-to-date is also an important factor when running models on CUDA. Furthermore, ensure you have adequate CUDA memory available in your GPU to handle the model and associated operations. 

Again, thank you for your contribution to the Ultralytics community. We appreciate your efforts to make YOLOv8 even better.

**Comment by YanceyHo** [comment]
It's because I found the ONNX runtime module judgment contain **onnxruntime-gpu** in the later code , so I wonder if the previous check intentionally missing ONNX option
```
        elif onnx:  # ONNX Runtime
            LOGGER.info(f'Loading {w} for ONNX Runtime inference...')
            check_requirements(('onnx', 'onnxruntime-gpu' if cuda else 'onnxruntime'))
            import onnxruntime
            providers = ['CUDAExecutionProvider', 'CPUExecutionProvider'] if cuda else ['CPUExecutionProvider']
            session = onnxruntime.InferenceSession(w, providers=providers)
            output_names = [x.name for x in session.get_outputs()]
            metadata = session.get_modelmeta().custom_metadata_map  # metadata
```

**Comment by glenn-jocher** [comment]
@YanceyHo the check you are referring to is used to make sure that your system has all the necessary and correct configurations for running the model with GPU. If torch cannot find an accessible GPU, it defaults to the CPU for computation.

However, for ONNX runtime, the selection of execution device is chosen by stating the provider. If CUDA is accessible and ONNX runtime has been installed correctly for GPU inference (i.e., `onnxruntime-gpu` is installed), ONNX runtime will utilize it for computation.

In the existing setup, ONNX uses 'CUDAExecutionProvider' when CUDA is available and ultimately falls back to 'CPUExecutionProvider' as needed. So, although the check for CUDA is separate for ONNX, it ensures that ONNX GPU execution is properly set up and ready to use the accessible CUDA. 

The explicit omission of ONNX in the early check is intentional, as ONNX GPU inference depends on a specific ONNX runtime library with GPU capability (i.e., `onnxruntime-gpu`). Checking for ONNX here could lead to incorrect device attribution if the ONNX runtime is not set up specifically for GPU execution.

We thank you for pointing out this detail. Your attention to these decisions helps maintain the clarity of how YOLOv8 manages device selection for different backends.

**Comment by hhhuaang** [comment]
所以会更新吗？会增加onnx对cuda的支持吗？

**Comment by glenn-jocher** [comment]
@hhhuaang 感谢您的问题。目前我们正在评估这个问题，尽管没有具体的时间表，但我们计划在未来可能会添加ONNX对CUDA的支持。我们理解这个特性对许多用户来说很重要，我们会很认真地考虑这个建议。再次感谢您对YOLOv8的投入和支持。

**Comment by Petros626** [comment]
> It's because I found the ONNX runtime module judgment contain **onnxruntime-gpu** in the later code , so I wonder if the previous check intentionally missing ONNX option
> 
> ```
>         elif onnx:  # ONNX Runtime
>             LOGGER.info(f'Loading {w} for ONNX Runtime inference...')
>             check_requirements(('onnx', 'onnxruntime-gpu' if cuda else 'onnxruntime'))
>             import onnxruntime
>             providers = ['CUDAExecutionProvider', 'CPUExecutionProvider'] if cuda else ['CPUExecutionProvider']
>             session = onnxruntime.InferenceSession(w, providers=providers)
>             output_names = [x.name for x in session.get_outputs()]
>             metadata = session.get_modelmeta().custom_metadata_map  # metadata
> ```

How to overcome this error and warning? Can't you set just one version for `PATH` and `LIBRARY_PATH`


![Image](https://github.com/user-attachments/assets/0dcc09f6-9daf-4c76-aae8-1f4267eaf780)

**Comment by glenn-jocher** [comment]
Thank you for pointing this out. The code intentionally checks for CUDA availability separately for ONNX Runtime since GPU support requires both `onnxruntime-gpu` installation and proper CUDA environment configuration. To resolve the PATH/LIBRARY_PATH warnings:

1. Ensure `onnxruntime-gpu` is installed (not CPU-only version)
2. Verify CUDA paths match your installed CUDA version
3. Set environment variables correctly:
```bash
export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
```
For full details see ONNX Runtime Installation Guide and Ultralytics ONNX Integration Docs.
