### ISSUE TITLE
Yolov8 on Coral TPU

### ISSUE THREAD

**Issue by sethumj** [ultralytics/ultralytics#4719]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I trained an Ultralytics YOLOv8 model with default settings and exported it as TFLite. I am unsure if the exported TFLite model will work completely on Coral TPU. If not, what are the possible reasons and how can I handle this? Do I need to change the activation function of the model to make all the operations execute completely in Coral TPU? If I use the parameter of int8, will the export happen in the expected quantized mode that is ready to be executed on Coral TPU? Any guidance for this?

**Comment by glenn-jocher** [comment]
@sethumj hello and thank you for your question!

Running a YOLOv8 TFLite model on Coral TPU does require some additional considerations. The Coral TPU supports a certain set of operations and requires models to be fully quantized (INT8 quantization) for optimal operation. If the operation in your TFLite model is unsupported by the Coral TPU, the model cannot be fully executed on the Coral TPU and the unsupported operation must be executed on the CPU which leads to slower inference time.

You mentioned changing the activation function of the model. Depending on the current activation function, this could be a possible solution. However, it is crucial to ensure that any changes to the architecture still allow the model to learn effectively. Experimentation might be needed to select the most appropriate activation function that’s compatible with the Coral TPU.

On quantization, when you enable the int8 parameter, it starts the Quantization Aware Training (QAT) process, which trains the model in a way that simulates the reduced numerical precision of the weights, which helps to minimize the degradation of the model accuracy. Afterwards, you'll need to convert this QAT model to TFLite, followed by full integer quantization to obtain a TFLite model fully optimized for Coral TPU.

Lastly, I highly recommend referring to the Coral TPU's documentation and the TensorFlow guide on model optimization for Edge TPU to help you get familiar with the process of adapting models for this device. Be aware that this might involve a fair bit of trial and error and testing, so patience is key.

I hope this answers your questions and guides you in the right direction! Happy coding!

**Comment by sethumj** [comment]
Thank you taking time to reply real quick. Do any one implemented this and if yes, What model have you used ? What is the FPS ?

**Comment by glenn-jocher** [comment]
@sethumj hello,

Thank you for your question. The performance metrics like frames per second (FPS) can vary widely depending on many factors including the chosen model architecture, the hardware used for inference, the resolution of the input data, and the specific optimization techniques utilized.

Since YOLOv8 includes multiple model configurations with varying complexity, the FPS can range across a wide spectrum. Smaller models will naturally run faster but may have lower accuracy, while larger models will run slower but typically have higher accuracy. 

As for specific implementations, experiences will vary between users due to differences in their unique contexts such as their hardware setups and specific use cases. 

I would encourage you to experiment with different YOLOv8 models and see which one best fits your specific needs in terms of speed and accuracy trade-offs. Additionally, utilizing the available optimization techniques such as quantization and pruning could also help in increasing the FPS.

I hope this information is helpful. Let us know if you have any more questions!

**Comment by patrickjdarrow** [comment]
Out of the box, yolov8s doesn't seem to contain many cross-compatible operations. Using the suggested command `yolo export model=yolov8s.pt format=edgetpu int8=True` yields ~5% conversion:

```
Number of operations that will run on Edge TPU: 13
Number of operations that will run on CPU: 244

Operator                       Count      Status

LOGISTIC                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
LOGISTIC                       54         More than one subgraph is not supported
LOGISTIC                       3          Mapped to Edge TPU
SUB                            2          More than one subgraph is not supported
QUANTIZE                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
QUANTIZE                       2          More than one subgraph is not supported
PAD                            2          Mapped to Edge TPU
PAD                            5          More than one subgraph is not supported
SOFTMAX                        1          More than one subgraph is not supported
RESHAPE                        3          Operation is otherwise supported, but not mapped due to some unspecified limitation
RESHAPE                        2          More than one subgraph is not supported
ADD                            8          More than one subgraph is not supported
MUL                            57         More than one subgraph is not supported
MUL                            3          Mapped to Edge TPU
CONV_2D                        61         More than one subgraph is not supported
CONV_2D                        3          Mapped to Edge TPU
RESIZE_NEAREST_NEIGHBOR        2          More than one subgraph is not supported
CONCATENATION                  2          Operation is otherwise supported, but not mapped due to some unspecified limitation
CONCATENATION                  17         More than one subgraph is not supported
STRIDED_SLICE                  2          Mapped to Edge TPU
STRIDED_SLICE                  2          Operation is otherwise supported, but not mapped due to some unspecified limitation
STRIDED_SLICE                  16         More than one subgraph is not supported
TRANSPOSE                      1          More than one subgraph is not supported
TRANSPOSE                      4          Operation is otherwise supported, but not mapped due to some unspecified limitation
MAX_POOL_2D                    3          More than one subgraph is not supported
```

Out of curiosity, I benchmarked this model on my device
```
import time

times = []

for i in range(100):
    if i>2:
        t0 = time.time()
        interpreter.set_tensor(input_details['index'], preprocessed_yolo)
        interpreter.invoke()
        preds_yolo = [interpreter.get_tensor(detail['index']) for detail in output_details]
        # preds_yolo = dequantize(preds_yolo)
        times.append(time.time()-t0)

print(np.mean(times))

>>> 3.691487652914865
```

Nano is better, using `yolo export model=yolov8.pt format=edgetpu int8=True`, at roughly 90% conversion:
```
Number of operations that will run on Edge TPU: 230
Number of operations that will run on CPU: 26

Operator                       Count      Status

QUANTIZE                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
QUANTIZE                       1          Mapped to Edge TPU
CONV_2D                        63         Mapped to Edge TPU
CONV_2D                        1          More than one subgraph is not supported
RESIZE_NEAREST_NEIGHBOR        2          Mapped to Edge TPU
SOFTMAX                        1          More than one subgraph is not supported
CONCATENATION                  1          More than one subgraph is not supported
CONCATENATION                  2          Operation is otherwise supported, but not mapped due to some unspecified limitation
CONCATENATION                  16         Mapped to Edge TPU
MUL                            3          More than one subgraph is not supported
MUL                            57         Mapped to Edge TPU
SUB                            2          More than one subgraph is not supported
RESHAPE                        3          Operation is otherwise supported, but not mapped due to some unspecified limitation
RESHAPE                        1          Mapped to Edge TPU
RESHAPE                        1          More than one subgraph is not supported
STRIDED_SLICE                  16         Mapped to Edge TPU
STRIDED_SLICE                  2          Operation is otherwise supported, but not mapped due to some unspecified limitation
STRIDED_SLICE                  2          More than one subgraph is not supported
TRANSPOSE                      4          Operation is otherwise supported, but not mapped due to some unspecified limitation
TRANSPOSE                      1          Mapped to Edge TPU
PAD                            7          Mapped to Edge TPU
LOGISTIC                       57         Mapped to Edge TPU
LOGISTIC                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
ADD                            6          Mapped to Edge TPU
ADD                            2          More than one subgraph is not supported
MAX_POOL_2D                    3          Mapped to Edge TPU
```

and latency
```
np.mean(times)
>>> 0.13344560350690568
```

Hoping for better native support as our company has an interest in yolov8. Also willing to contribute if pointed in the right direction. Cheers!

**Comment by glenn-jocher** [comment]
@patrickjdarrow hello and thank you for the detailed observations and performance measurements!

As you've noted, the YOLOv8s model isn't entirely compatible with the Edge TPU out-of-the-box, as about 95% of operations are offloaded to the CPU. This is due to certain operations in the model that have better support for CPU than Edge TPU.

However, with the YOLOv8n model, you obtained far better results, with about 90% of operations compatible with the Edge TPU. This difference indicates how model architecture significantly impacts the compatibility with Edge TPU. A model with fewer, simpler layers like YOLOv8n will generally yield better results than one with more complex layers, like in the case of YOLOv8s. The trade-off, as you might expect, is that simpler and speedier models may not have the same accuracy as their more complex counterparts.

Optimizing YOLOv8s for Edge TPU would likely involve making changes to the model architecture to replace the unsupported operations with ones that have full support on Edge TPU without compromising the model’s ability to learn effectively. This may involve a fair bit of trial and error and deeper analysis of the model’s architecture and the specific operations used.

We appreciate your willingness to improve the YOLOv8's compatibility with Edge TPU. Given that this is quite complex work, and may involve changing parts of the model's architecture, a good direction would be to gain a deep understanding of operations the Edge TPU can accelerate and their equivalents in YOLOv8s, as well as gaining familiarity with methods for model optimization, such as quantization and pruning.

Finally, for future issues, it would be useful to know the specific version of the Edge TPU Compiler and the TensorFlow Lite runtime you are using, so that we can provide more targeted assistance.

We hope this clears up your issue and provides a path forward!
