### ISSUE TITLE
Confusion Matrix After Train Model Yolov8 

### ISSUE THREAD

**Issue by WidiaPrasetia** [ultralytics/ultralytics#4752]
How do you display a confusion matrix in number format?  while what I get is only in percentage format.  even though at the first start, 2 versions appeared, namely numbers and percentages.  Maybe this is a simple question for you, but please help someone who is still a layman like me.  Thank You

**Comment by glenn-jocher** [comment]
@WidiaPrasetia hello, thank you for your question about the confusion matrix in YOLOv8. 

Upon training a model, the confusion matrix is automatically displayed in both number and percentage format. However, you're correct that as training progresses, it updates to show only percentages. This design decision was made to ensure clarity and ease of use, as percentages rather than raw numbers allow for simpler comparison and interpretation as your dataset size changes.

While changing the display format between raw numbers and percentages is not directly built into YOLOv8, modifying the code to suit your preference is certainly possible for those comfortable with doing so. But do remember, changing the code may affect the software stability and future updates.

I hope this answers your question and happy YOLOv8 coding! Don't hesitate if you have any more questions or issues, I'm here to help.

**Comment by WidiaPrasetia** [comment]
Thank you for the explanation sir,
Is there an example code to display both formats of the confusion matrix (number & percent)?  I've tried looking in the docs, but I haven't found it.  I hope you can help me, thank you sir

**Comment by HtwoOtwo** [comment]
Hi, you can get the confusion matrix from:
https://github.com/ultralytics/ultralytics/blob/577d066fb201a62694ed1e9d53f715e27db0266e/ultralytics/utils/metrics.py#L253-L255

**Comment by glenn-jocher** [comment]
@WidiaPrasetia hello, thank you for your question.

The confusion matrix in YOLOv8, helps to visualize the performance of the algorithm by displaying the true positives, false positives, true negatives, and false negatives for each class in your dataset.

In the lines of code you referred to, you can see how the confusion matrix is calculated, normalized, and displayed as a percentage format during training. This ensures clarity, ease of understanding, and allows for a simpler comparison as your dataset size changes.

If you want to display raw confusion matrix (numbers rather than percentages), you would need to modify the code where the confusion matrix is computed. Instead of normalizing the matrix (dividing each entry by the sum of that row), just display the matrix as it is right after computing it.

This kind of customization would involve tinkering with the open-source code, and as a reminder, altering the repository might affect the stability of your software and its compatibility with future updates.

I hope that answers your question! Please feel free to ask if you have further inquiries. Happy coding!
