### ISSUE TITLE
how to calculate accuracy, precision, f1 and recall metrics on undetected objects?

### ISSUE THREAD

**Issue by fernandoant97** [ultralytics/ultralytics#4759]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello everyone. The goal of my project is to make a classification, using image detection of Yolov8, of two categories of tomatoes, good and bad. I trained my network with pretrained weights and I made the inference. The problem is that out of 228 photos, it detected 227 for me. The question is, being accuracy=(TP+TF)/(TP+TF+FP+FN) and in the confus matrix I have 227 photos and not 228, should I actually consider the predicted photos (so 227) or the whole test dataset (228)? The same question also applies to other metrics in general. The aim of project is have a good classification on all dataset. I have not found any other information on the internet. Thanks everyone for the help.
Fernando

**Comment by glenn-jocher** [comment]
@fernandoant97 hello Fernando, 

In assessing model performance, it's important to consider all data samples from your testing set, even those not detected by the model, because the model has the potential to make a classification decision for each sample. 

If your YOLOv8 model does not detect a sample image, this can be regarded as a False Negative (FN) because although your model didn't recognize it, there was a real sample to be recognized. In other words, your model has made a misclassification in ignoring the given sample.

Pointedly, when calculating metrics like accuracy, precision, F1 and recall, your denominator should be the entire test dataset (in your case, all 228 images). 

You would add the undetected image as a false negative (FN) in your confusion matrix. This way your matrix reflects both the instances your model detected (and whether it's correct or incorrect) and instances it failed to detect. Doing so results in more accurate evaluation metrics, which ultimately gives you a better understanding of your model's performance.

Let me know if you have any further questions!

Best, 
Glenn
