### ISSUE TITLE
Using the provided Demo (/ultralytics/exapmles/YOLOv8-CPP-Inference), it can be inferred under CUP, but cannot be inferred under GPU

### ISSUE THREAD

**Issue by zzn250098917** [ultralytics/ultralytics#4762]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

 bool runOnGPU = true; // if runOnGPU = false can be inferred   if runOnGPU = true cannot be inferred

### Environment

--YOLO:Ultralytics YOLOv8.0.166 🚀 Python-3.11.4 torch-2.0.1 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4037MiB)
Setup complete ✅ (8 CPUs, 7.7 GB RAM, 71.7/136.4 GB disk)
--OS:ubuntu20.04
--OPENCV:OPENCV4.8

### Minimal Reproducible Example

    std::string projectBasePath = "/home/jsbz/Desktop/zznTest/openCVDNN"; // Set your ultralytics base path

    bool runOnGPU = true; // if runOnGPU = false can be inferred   if runOnGPU = true cannot be inferred

    //
    // Pass in either:
    //
    // "yolov8s.onnx" or "yolov5s.onnx"
    //
    // To run Inference with yolov8/yolov5 (ONNX)
    //

    // Note that in this example the classes are hard-coded and 'classes.txt' is a place holder.
    onnxInference inf(projectBasePath + "/onnx/yolov8n.onnx", cv::Size(640, 640), "classes.txt", runOnGPU);

    std::vector<std::string> imageNames;
    imageNames.push_back(projectBasePath + "/input/bus.jpg");
    imageNames.push_back(projectBasePath + "/input/zidane.jpg");
    imageNames.push_back(projectBasePath + "/input/person.jpg");
    imageNames.push_back(projectBasePath + "/input/person1.png");
    imageNames.push_back(projectBasePath + "/input/person2.jpg");
    int64 currentTime;

    for (int i = 0; i < imageNames.size(); ++i)
    {

        currentTime = JSBZCommon::getCurrentTime();
        cv::Mat frame = cv::imread(imageNames[i]);

        // Inference starts here...
        std::vector<DetectZZN> output = inf.runInference(frame);

        int detections = output.size();
        std::cout << "Number of detections:" << detections << std::endl;

        for (int i = 0; i < detections; ++i)
        {
            DetectZZN zznDetect = output[i];

            cv::Rect box = zznDetect.box;
            cv::Scalar color = zznDetect.color;

            // Detection box
            cv::rectangle(frame, box, color, 2);

            // Detection box text
            std::string classString = zznDetect.className + ' ' + std::to_string(zznDetect.confidence).substr(0, 4);
            cv::Size textSize = cv::getTextSize(classString, cv::FONT_HERSHEY_DUPLEX, 1, 2, 0);
            cv::Rect textBox(box.x, box.y - 40, textSize.width + 10, textSize.height + 20);

            cv::rectangle(frame, textBox, color, cv::FILLED);
            cv::putText(frame, classString, cv::Point(box.x + 5, box.y - 10), cv::FONT_HERSHEY_DUPLEX, 1, cv::Scalar(0, 0, 0), 2, 0);
        }
        // Inference ends here...

        // This is only for preview purposes
        float scale = 0.8;
        cv::resize(frame, frame, cv::Size(frame.cols*scale, frame.rows*scale));
        cv::imshow("Inference"+QString::number(i).toStdString(), frame);
        //qDebug<<"detect times:"<<JSBZCommon::getCurrentTime() - currentTime;
        std::cout << "detect times:" << JSBZCommon::getCurrentTime() - currentTime << std::endl;
        //cv::write("")
    }

### Additional

 bool runOnGPU = true; // if runOnGPU = false can be inferred   if runOnGPU = true cannot be inferred

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@zzn250098917 thank you for the detailed issue report and for offering to contribute a PR. Based on your description and environment, the issue seems to be specifically with running the YOLOv8 model inference on a GPU. When `runOnGPU = true`, the model cannot be inferred, but it works fine when set to `false`.

1. **Torch and CUDA Versions**: You are using torch-2.0.1 and CUDA 0. These versions are generally compatible with YOLOv8, so this may not be a versioning issue.

2. **Hardware Configuration**: Your hardware setup, including NVIDIA GeForce GTX 1050 Ti, should be sufficient for running YOLOv8 inference on a GPU. So it's unlikely to be a hardware limitation.

3. **OpenCV Version**: You're using OpenCV 4.8, which should work fine for this task.

The code snippet you provided is geared towards ONNX inference, and your issue could be related to the ONNX runtime's GPU support. This might be a possible area for further investigation.

Given that you've offered to submit a PR, we'd appreciate any additional debugging you can perform to isolate the issue. Specifically, look into the ONNX runtime's GPU utilization and compatibility with YOLOv8. Your contribution could be very valuable to the community, and we're looking forward to your findings.

Thank you for using Ultralytics YOLOv8 and for being willing to contribute back to the community.

**Comment by Jaxys10** [comment]
same question! I tried this，But the result is not very good.[https://github.com/opencv/opencv/issues/23977](url)

**Comment by glenn-jocher** [comment]
@Jaxys10 hello, thank you for reaching out. It's unfortunate that you are experiencing issues with YOLOv8 GPU inference. Going by the link you've provided, it appears you've attempted a solution from an OpenCV related GitHub issue. 

From your description, it's not clear what exactly is wrong with the result. Are the detection outputs incorrect or is there a performance issue? Based on the information you've given, it could potentially be an issue with how the ONNX runtime handles GPU acceleration, or an incompatibility between YOLOv8 and the particular GPU setup you're using.

I would advise you to dive deeper into the ONNX runtime documentation, specifically in regards to GPU utilization, and to also validate your GPU setup. Try running other deep learning models with the same GPU setup to see if you're facing similar problems. This should help you isolate whether the problem is specific to YOLOv8 or something in your environment.

I hope this helps guide your debugging process and leads to a resolution of your issue. Please, don't hesitate to ask if you have any more questions. Thank you for using YOLOv8.

**Comment by Jaxys10** [comment]
thank you for your reply. I used opencvdnn with cuda. Cpu results are correct. but when I used cuda,the value of x, y, w, h become 0. I don't know why.



---- Replied Message ----
| From | Glenn ***@***.***> |
| Date | 09/10/2023 03:48 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [ultralytics/ultralytics] Using the provided Demo (/ultralytics/exapmles/YOLOv8-CPP-Inference), it can be inferred under CUP, but cannot be inferred under GPU (Issue #4762) |

@Jaxys10 hello, thank you for reaching out. It's unfortunate that you are experiencing issues with YOLOv8 GPU inference. Going by the link you've provided, it appears you've attempted a solution from an OpenCV related GitHub issue.

From your description, it's not clear what exactly is wrong with the result. Are the detection outputs incorrect or is there a performance issue? Based on the information you've given, it could potentially be an issue with how the ONNX runtime handles GPU acceleration, or an incompatibility between YOLOv8 and the particular GPU setup you're using.

I would advise you to dive deeper into the ONNX runtime documentation, specifically in regards to GPU utilization, and to also validate your GPU setup. Try running other deep learning models with the same GPU setup to see if you're facing similar problems. This should help you isolate whether the problem is specific to YOLOv8 or something in your environment.

I hope this helps guide your debugging process and leads to a resolution of your issue. Please, don't hesitate to ask if you have any more questions. Thank you for using YOLOv8.

**Comment by glenn-jocher** [comment]
@Jaxys10 hi there, I see that you're having an issue with the inference bounding box values when using CUDA with the OpenCV DNN module. They're coming out as zeros on CUDA but are correct on CPU.

This behavior suggests that there might be an issue with how OpenCV DNN is interacting with CUDA in the context of this model. Here are a few possible reasons:

1. **GPU Compatibility**: Ensure that your GPU is compatible with your software stack, specifically with Cuda, your version of OpenCV, and the overall ONNX runtime.
 
2. **Coordinate Transformations**: Depending on the software, the coordinate system may be different between the CPU and GPU. This could potentially cause discrepancies in box predictions if not properly accounted for.

3. **Tensor Format**: Check if the tensor formats between your CPU and GPU matches.

4. **CUDA Configuration**: Look into your CUDA configuration to ensure there are no discrepancies that could affect the OpenCV DNN's usage of CUDA.

It might be helpful to try running a different model using OpenCV DNN module with CUDA to isolate if this issue is specific to YOLOv8. Good luck with your debugging, and feel free to continue reporting any updates or further questions you may have in this thread. We highly appreciate your collaboration.

**Comment by shrijitsingh99** [comment]
@glenn-jocher I have the same issue as stated above. 
My CUDA version is 12.2 and OpenCV version is 4.8.0.

YoloV5 runs fine for me, but YoloV8 gives the same issue as @Jaxys10 i.e. "x, y, w, h become 0.", but the class scores are correct.

Any suggestions on how I can go on and debug the issue?

**Comment by zzn250098917** [comment]
> same question! I tried this，But the result is not very good.[https://github.com/opencv/opencv/issues/23977](url)



> same question! I tried this，But the result is not very good.[https://github.com/opencv/opencv/issues/23977](url)

问一下你这个问题解决了吗，是怎么解决的？

**Comment by zzn250098917** [comment]
@shrijitsingh99 @Jaxys10 
Have you solved this bug?

**Comment by glenn-jocher** [comment]
Hello, thanks for following up on this issue. We haven't received any new updates about bug resolution from @zzn250098917 or @Jaxys10. 

Remember, narrowing down such an issue sometimes requires a bit of debugging, verifying the different elements in your setup. It's always good to check for the following: 

1. Ensure the GPU and CUDA setup is working properly beyond this use-case. You can do this by testing out other deep learning GPU-accelerated processes, if they run with no issues, you can probably rule out any GPU/CUDA configuration problems. 

2. Look into the specific interactions between CUDA, ONNX runtime and YOLOv8. If there's something in that interaction causing the issue, you might need to go more in-depth, possibly even looking at how the model's architecture is handled during inference on a GPU.

Remember, it's all a step-by-step process, and the goal is to find out where exactly the problem is coming from. If you have made any progress or come across any new findings, feel free to share. These discussions can be very beneficial for the community.
