### ISSUE TITLE
Tune broken for classification models

### ISSUE THREAD

**Issue by trnikon** [ultralytics/ultralytics#4767]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Evolution

### Bug

When trying to tune a classification problem, the following error occurs at the end of the first training session:
```
AttributeError: 'ClassifyMetrics' object has no attribute 'save_dir'. See valid attributes below.

    Class for computing classification metrics including top-1 and top-5 accuracy.

    Attributes:
        top1 (float): The top-1 accuracy.
        top5 (float): The top-5 accuracy.
        speed (Dict[str, float]): A dictionary containing the time taken for each step in the pipeline.

    Properties:
        fitness (float): The fitness of the model, which is equal to top-5 accuracy.
        results_dict (Dict[str, Union[float, str]]): A dictionary containing the classification metrics and fitness.
        keys (List[str]): A list of keys for the results_dict.

    Methods:
        process(targets, pred): Processes the targets and predictions to compute classification metrics.
```

### Environment

- YOLO: ultralytics-8.0.171

### Minimal Reproducible Example

```
model = YOLO('yolov8l-cls.pt')
model.tune(data='imagenet10', imgsz=64, epochs=30, iterations=10)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@trnikon thanks for the bug report! I'm able to reproduce, will work on a fix.

**Comment by glenn-jocher** [comment]
@trnikon great news 😃! Your original issue may now be resolved ✅ in PR #4766. This PR fixes the Classify Tune bug you discovered and adds Classify model tuning to our tests so we catch this earlier in the future.

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by trnikon** [comment]
It passed the first training but it got stuck at the end of the second without any error output. `Ctrl + c` will start the third training but then it gets stuck again at the end of the forth. After that it just gets stuck at random intervals. Same code as above. Tried it on a 4090 and a 1080 server with cuda. Nvidia-smi shows 0% utilization when it's stuck.

**Comment by glenn-jocher** [comment]
@trnikon the tests that are passing are here. Are you able to run these correctly?

https://github.com/ultralytics/ultralytics/blob/8fd9a1a048b83975566ed82de9d481e015c72ad7/tests/test_cuda.py#L96-L99

**Comment by glenn-jocher** [comment]
Passing tests results:

https://github.com/ultralytics/ultralytics/actions/runs/6101828947/job/16558998852
<img width="1796" alt="Screenshot 2023-09-06 at 23 51 13" src="https://github.com/ultralytics/ultralytics/assets/26833433/43d4a82a-fa77-49f3-a259-9356d26bb6e0">

**Comment by trnikon** [comment]
Training on cpu using the device=cpu flag works, skipping it results in getting stuck on your examples too.

**Comment by glenn-jocher** [comment]
@trnikon ok got it. I'll change the device to 0 here to see what's happening.

**Comment by glenn-jocher** [comment]
@trnikon I tested GPU tuning in Colab and everything is working correctly for me, i.e.:


```python
from ultralytics import YOLO

YOLO('yolov8n-pose.pt').tune(data='coco8-pose.yaml', imgsz=32, epochs=1, iterations=2, device='0')
YOLO('yolov8n-cls.pt').tune(data='imagenet10', imgsz=32, epochs=1, iterations=2, device='0')
```

https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb
<img width="1399" alt="Screenshot 2023-09-07 at 00 55 07" src="https://github.com/ultralytics/ultralytics/assets/26833433/0a9f1481-2f95-4b40-935d-2a3527dcd6a9">

**Comment by trnikon** [comment]
@glenn-jocher Can you increase the number of epochs and iterations? The problems for me start for me at epoch 2 and 4

**Comment by glenn-jocher** [comment]
@trnikon I've added GPU tuning with increased epochs in https://github.com/ultralytics/ultralytics/pull/4773 to see what the GPU tests do

**Comment by glenn-jocher** [comment]
Also updated to 10 epochs here and everything is good.

<img width="1399" alt="Screenshot 2023-09-07 at 01 12 28" src="https://github.com/ultralytics/ultralytics/assets/26833433/faa5a400-232a-47f9-9b6a-0df9a1221a45">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by trnikon** [comment]
With epochs=10 and iterations=2 it works for me too. Please try with iterations > 2, for example iterations=10.

**Comment by glenn-jocher** [comment]
@trnikon Thank you for the detailed observation. This information will certainly help us understand and diagnose the issue better. I'll increase the iterations to 10 and then analyze how it behaves. This will help us to understand whether the delayed response you noticed is tied to the increase in iterations or if there's an underlying issue that needs addressing. For the time being, as a workaround, you could use smaller iteration values where behavior is stable. I appreciate your patience and cooperation.
