### ISSUE TITLE
Training yolov8 pose model with WiderFace Dataset which has 5 key points

### ISSUE THREAD

**Issue by zjLeung** [ultralytics/ultralytics#4779]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I am confused by how to train the pose model with 5-key-points-WiderFace. Here is my question: i have label txt of every images, and each row in txt is denoted as, x1,y1,w,h,px1,py1,px2,py2,....., but some key points coordinates are just invalid like -1.0,-1.0,-1.0,...., because the face is too small to annotate 5 key points. In this condition, what is the correct label for yolov8-pose-model?
i guess it should be like the following, e.g. exmpale.txt:
0 cx cy w h px1 py1 px2 py2 px3 py3 px4 py4 px5 py5     (this instance is valid)
0 cx cy w h (this instance is invalid)
...........
...........
Am i right? hope someone will get me clear about the correct annotations for the pose model training.

**Comment by glenn-jocher** [comment]
@zjLeung hello,

Thank you for reaching out about training a YOLOv8 Pose model with the WiderFace Dataset. You are correct; the labels for each instance should include the bounding box followed by the coordinate pairs for each of the key points, which would be indicated as cx, cy, w, h, px1, py1, px2, py2, and so on. 

However, the values -1.0,-1.0,-1.0..., are indicators that the corresponding keypoints are missing or not annotated due to the small size of the face. In this case, the label for an invalid instance would be the four bounding box parameters (cx, cy, w, h, -1, -1, -1, -1, etc.) until all keypoints are accounted for. This helps maintain a consistent data structure and format for each instance in the dataset.

For keypoints that are not visible or could not be annotated, you can represent them with -1,-1. Please be aware that the model will need to be trained to understand what these placeholder values mean, and it may affect the performance of the model if a large portion of your data contains missing keypoints.

Do note that any change in this format will require a corresponding adjustment in your data loading and parsing code.

Your understanding of the situation is correct; the label structure you proposed is accurate and should work well. Training a model with a dataset that includes instances missing some keypoints presents a unique challenge, but successfully parsing and handling this dataset can yield a robust and flexible model.

Happy training!
