### ISSUE TITLE
ray tune All trials PENDING, never RUNNING

### ISSUE THREAD

**Issue by magicleo** [ultralytics/ultralytics#4790]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

<img width="1212" alt="企业微信截图_c8ef4a12-15eb-425e-b897-bb4dc5c7c4e9" src="https://github.com/ultralytics/ultralytics/assets/3990950/10c589d3-b402-484b-9fa5-0713c13e834f">

### Environment

- YOLO: YOLOv8.0.172 python3.10 torch-2.0.1 cuda11.7 CUDA:0 (A10) CUDA:1(A10)
-OS:Ubuntu
-python 3.10

### Minimal Reproducible Example

```
from ultralytics import YOLO

# Load a YOLOv8n model
model = YOLO('yolov8n.pt')

# Start tuning hyperparameters for YOLOv8n training on the COCO8 dataset
result_grid = model.tune(          
    data='coco128.yaml',
    use_ray=True,
)
```

### Additional

I’m trying to run a hyperparameter search with ray tune, but it doesn’t seem like any of the trials are ever actually started. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@magicleo thank you for reaching out with this issue concerning Ray Tune in YOLOv8.

From your description, it appears that all trials are stuck in the PENDING state and not transitioning to the RUNNING state while performing hyperparameter search using ray tune. This is not the expected behavior.

Let's try to troubleshoot in the following way:

1. Please ensure you have the latest version of both ultralytics and ray tune installed, and that they are compatible with your Python version. Some of these kinds of issues can be caused due to incompatibility or outdated versions.

2. It's also crucial to check the hardware setup. Make sure you have enough resources (CPU, GPU, Memory) available and Ray is correctly set up to utilize them. Sometimes, Ray might be waiting for resources to be freed up before starting the trials.

3. Check if there are any errors in ray tune logs, they might provide some insights regarding why the trials are not starting. Checking Ray Tune dashboard on port 8265 (the default one) could be valuable as well.

Please try the above suggestions and let us know if any or all of them helped or if the problem persists. We are here to assist you until this issue is resolved.
