### ISSUE TITLE
How should I test the coco test-dev for Yolov8-pose?

### ISSUE THREAD

**Issue by malareeqi** [ultralytics/ultralytics#4802]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to evaluate and test the coco test-dev for Yolov8-pose. I tried to use 
 python  val model=path/to/best.pt  data=coco-pose.yaml   split=test
I got error,I also divided the dataset file as you mentioned before like this 

![image](https://github.com/ultralytics/ultralytics/assets/72854576/37dfda7e-d7a7-43ea-be60-d99569e2f956)

The error is this: there are no labels 
![image](https://github.com/ultralytics/ultralytics/assets/72854576/7ff0a35b-8f68-4ea2-b1d0-75946ee8c2bc)

**Comment by glenn-jocher** [comment]
@malareeqi thank you for bringing your issue to our attention.

The coco test-dev dataset is a dedicated test set that does not come with labels to ensure fair comparison in the evaluation of model performance. Therefore, trying to validate ("Val") on this test-dev set will indeed lead to an error message about missing labels, which explains the problem you're encountering.

In order to evaluate your YOLOv8-Pose model on the test-dev split of coco, you need to generate predictions using the 'Predict' mode of YOLOv8. Once you have generated these predictions, they need to be submitted to the COCO evaluation server, as it's the only way to evaluate on the test-dev split. This is because, as mentioned earlier, the test-dev set does not have publicly available annotations.

Please remember the command for 'Predict' mode should look something like this: python predict model=path/to/best.pt data=coco-pose.yaml split=test

Also, it looks like you may have been using "val" command in your initial attempt, which is why you received an error about missing labels. Please ensure you are following this recommended workflow to avoid future errors.

If you have any more questions or need further clarification, feel free to ask.

**Comment by malareeqi** [comment]
Thank you so much for your response. I appreciate it 
, but I have tried to use Val many for three days without any progress.
Now I will use the command 
predict as you mentioned before but I have one question;How I can save the results because the predict settings don't support saving the results in Json  as val 
Please explain this point 
Thank you so much

**Comment by glenn-jocher** [comment]
@malareeqi hello,

Thank you for your understanding. You're correct, the 'predict' command currently does not support directly saving the results as a JSON. 

To address your question, once predictions are made with the 'predict' mode in YOLOv8, these results are stored internally. Under the current design, the 'predict' mode is typically used for real-time predictions and thus does not include built-in functionality for saving results.

As storing predictions in a JSON format is not supported directly, it requires a manual process. After making predictions, you would need to programmatically access these internal predictions resulting from the 'predict' function and then convert and save them into your desired JSON format.

I understand this could be a recurring requirement for our users and I will bring this up with the Ultralytics team to consider adding it as a feature in future updates. 

Thanks again for your valuable input. Let us know if you have any further questions.

**Comment by malareeqi** [comment]
Thank you for your response, really I appreciate your great work. 
I would like you to recommend for me some code or URL for a project that will help me convert the results and generate a JSON file like the file generated by Yolov8.
I know it's my task to do it but really I am worried that missing any details will affect the evaluation of my model, I also have a deadline to submit my work, I hope you understand my situation. Thank you so much

**Comment by glenn-jocher** [comment]
@malareeqi,

I completely understand your situation, and the importance of getting the evaluation of your model done correctly and on time. 

Given the current design of YOLOv8 and the absence of directly obtaining a JSON output, there are few steps you might want to follow:

1. **Obtain the predictions**: Once the 'predict' function is executed, the model's predictions will be stored internally within the model object. This contains all the information you need.

2. **Extract the Predictions**: You will need to programmatically extract these predictions. The predictions will typically be in the form of a list of bounding boxes, each containing the coordinates of the box, class, and confidence score.

3. **Format the Predictions**: Once you have these predictions, you will need to convert them into the desired JSON format. This usually involves iterating over your list of bounding boxes and extracting the required information into a new JSON structure.

As for guidance, I advise you to check the output schema of test-dev predictions JSON file to ensure the structure of your JSON matches the required format. Keep in mind that your JSON file should follow a specific format which typically includes image ID, category ID, bounding box and score.

I hope this helps! Don't hesitate to post further questions or issues you may encounter. Good luck!

**Comment by malareeqi** [comment]
Thank you so much for your support and help. I'm trying to do it.

**Comment by glenn-jocher** [comment]
@malareeqi,

You're welcome, and thank you for your patience working through this process. I want to assure you that your questions and progress are important. 

Firstly, as you've started trying to implement the process, you'll need to generate the predictions using the 'predict' command in your YOLOv8 model. Once these predictions are generated, they will be stored internally. This is where all the essential details—like bounding box coordinates, classification, and confidence scores—reside.

After you've made the predictions, the next step is extracting these predictions programmatically from the model. Typically, these will be in a specific format such as a list or a set of bounding boxes.

Once extracted, the final step is converting these predictions into your desired JSON format. You will need to iterate over the prediction results, extract the necessary information, and then format this information into the specific JSON structure required for submission to the COLO evaluation server.

I hope this gives you a clearer idea of the process to follow. Please continue with your efforts and feel free to reach out if you have more questions or encounter any issues. All the best with your work!

**Comment by malareeqi** [comment]
[person_keypoints_test-dev2017_result.zip](https://github.com/ultralytics/ultralytics/files/12598297/person_keypoints_test-dev2017_result.zip)
Hello , I have got the predication and save them in Json  file , I used the same function in val file 

I modify the code of predict as this 

def postprocess(self, preds, img, orig_imgs):
        """Return detection results for a given input image or list of images."""
        preds = ops.non_max_suppression(preds,
                                        self.args.conf,
                                        self.args.iou,
                                        agnostic=self.args.agnostic_nms,
                                        max_det=self.args.max_det,
                                        classes=self.args.classes,
                                        nc=len(self.model.names))

        results = []
        for i, pred in enumerate(preds):
            orig_img = orig_imgs[i] if isinstance(orig_imgs, list) else orig_imgs
            shape = orig_img.shape
            pred[:, :4] = ops.scale_boxes(img.shape[2:], pred[:, :4], shape).round()
            pred_kpts = pred[:, 6:].view(len(pred), *self.model.kpt_shape) if len(pred) else pred[:, 6:]
            pred_kpts = ops.scale_coords(img.shape[2:], pred_kpts, shape)
            path = self.batch[0]
            img_path = path[i] if isinstance(path, list) else path
            results.append(
                Results(orig_img=orig_img,
                        path=img_path,
                        names=self.model.names,
                        boxes=pred[:, :6],
                        keypoints=pred_kpts))
                
        save_to = Path(self.save_dir) / 'labels' / 'predictions.json'
        self.pred_to_json(preds, img_path)
        with open(str(save_to), 'w') as f: 
                   json.dump(self.jdict, f)
        return results


    def pred_to_json(self,preds, filename):
            """Converts YOLO predictions to COCO JSON format.""" 
            stem = Path(filename).stem
            for si, predn in enumerate(preds): 
                image_id = int(stem) if stem.isnumeric() else stem
                box = ops.xyxy2xywh(predn[:, :4])  # xywh
                box[:, :2] -= box[:, 2:] / 2  # xy center to top-left corner
                for p, b in zip(predn.tolist(), box.tolist()):
                    self.jdict.append({
                        'image_id': image_id,
                        'category_id': self.class_map[int(p[5])],
                        #'bbox': [round(x, 3) for x in b],
                        'keypoints': p[6:],
                        'score': round(p[4], 5)})

The problem now is when I submitted the Json file to evaluate on competition gave me error :
Traceback (most recent call last):
  File "/tmp/codalab/tmpLfd90m/run/program/run.py", line 70, in 
    cocoDt=cocoGt.loadRes(resFile)
  File "/tmp/codalab/tmpLfd90m/run/program/pycocokp/coco.py", line 304, in loadRes
    'Results do not correspond to current coco set'
   AssertionError: Results do not correspond to current coco set
Really I don't know, what is the problem?. I have tried again to get the prediction without bounding  boxes. I have attached my prediction file so please check it , I need your help to fix this issue ,thank you so much

**Comment by glenn-jocher** [comment]
@malareeqi hi there,

I understand the error message you're encountering can be really frustrating, especially after so much hard work. It appears that the AssertionError, where "Results do not correspond to current coco set", mainly points out a mismatch between the results your code is generating and what the COCO evaluation tool is expecting. 

This could be due to several factors, such as your result set not matching with the images in the current COCO dataset, or the formatting of the 'bbox' or 'keypoints' being incorrect. 

When it comes to the Assertion Error, it would check if annotations['images'] in the submission file match the image_ids in the valuation dataset. If they don't match, this error will be raised. So, ensure that 'image_id' for each prediction in your JSON file matches with the one in the COCO evaluation set. 

Please validate the 'image_id', 'bbox', and 'keypoints' format in your JSON file. Also, make sure that the 'bbox' and 'keypoints' elements are not empty and in the correct format. 

You need to make sure your class_map is correct, as 'category_id' should point to the correct class as per the COCO dataset. Pay close attention to the structure of your JSON file and ensure it aligns with the example mentioned in the COCO dataset.

I'm sorry I can't assist directly due to not being able to debug or view your exact code or output, but I hope these general pointers will help you identify and resolve the issue. All the best!

**Comment by malareeqi** [comment]
Hello, to test the JSON file generated by my code, I sampled some images from val2017 and tried it, and it worked, but when I predicted with test-dev2017 data and uploaded the JSON file to evaluate my model, I got the above error.

is it okay to tell me the specific format used for the coco test-dev2017 keypoints as my task,please take look for our JSON prediction file above
Thank you so much

**Comment by malareeqi** [comment]
Hello , please can you let's know ,how can we download test-dev2017.txt ,thank you

**Comment by glenn-jocher** [comment]
@malareeqi hello,

The `test-dev2017.txt` file typically contains the image IDs of the test-dev2017 dataset. You can create this file by downloading the test-dev2017 dataset, then looping through all the images in the dataset to extract their image IDs and save them in a `.txt` file. When the file is ready, you can use it as input to your YOLOv8 model for predicting results.

Note that the test-dev2017 dataset is designed for model evaluation and doesn't include annotation information. Due to competition rules, the ground truth for this dataset can't be publicly downloaded.

Please let me know if you have any further questions, and best of luck with your model evaluation.

**Comment by malareeqi** [comment]
Hello, thank you so much.
I have solved the problem and got the results, I appreciate your help and support. The problem was that I made a prediction for all images inside the test2017 folder, which was downloaded by Yolov8 (more than 40,000) images.
The solution was, as you mentioned above I should only predict the  test-dev2017 (20,000) images. so I had to make a new folder for test-dev2017.
I hope later, you can split the test folder by Yolov8 into two parts, one of them for test-dev2017, which will help the user finish the task early and not get confused. Thank you so much again.

**Comment by glenn-jocher** [comment]
@malareeqi hello,

I'm glad to hear that you have solved the issue and successfully obtained your results. Your feedback is immensely valuable as it aids in enhancing the user experience of this project.

Your suggestion of splitting the testing folder into two parts is very insightful, and I can understand how this can simplify the process for users, allowing them to work more efficiently without confusion. We will certainly consider this idea for improving the project structure in future iterations of YOLOv8.

If you encounter any other issues or have suggestions, please don't hesitate to reach out. Our aim is to make this project as user-friendly and efficient as possible. Your contributions are always appreciated in this regard.

Thank you for your cooperation and best of luck with your future tasks.

**Comment by malareeqi** [comment]
Thank you for your beautiful words. Thank you for your cooperation and answering all our inquiries. You are doing a great job. Thank you again.

**Comment by glenn-jocher** [comment]
@malareeqi hello,

I appreciate your kind words and positive feedback! I'm here to assist in making your experience with YOLOv8 as smooth as possible, and I'm glad to hear that we're achieving that goal. Please don't hesitate to reach out if you have more questions or need further support with anything.

Thank you for being a part of our YOLOv8 community. Happy coding!

**Comment by xhf3571** [comment]
@malareeqi 


Hello,

Your experience is very helpful. I am running `my_val.py`:
The code is:
```python
from ultralytics import YOLO

# Load a model
model = YOLO("/root/lanyun-tmp/ultralytics-8.2.59/ultralytics/yolov8n-pose.pt")

# Customize validation settings
validation_results = model.val(data="/root/lanyun-tmp/ultralytics-8.2.59/ultralytics/cfg/datasets/coco-pose.yaml", 
                               save_json=True,
                               split='test' )
```
This produces a `predictions.json` file, but when I upload it to the COCO evaluation website [here](https://codalab.lisn.upsaclay.fr/competitions/7403#participate-submit_results), I get all zero scores.

I suspect my method for generating the JSON file might be incorrect. I have already divided the `test-dev2017` dataset, which contains 20,288 images. I noticed you modified the `predict` file. Can you tell me the specific running code or CLI? Or the correct method to generate JSON files, I have been doing this for 5 days but still haven't succeeded

Thank you very much, and I look forward to your response.
