### ISSUE TITLE
Set different thresholds for different objects

### ISSUE THREAD

**Issue by simpson0826** [ultralytics/ultralytics#4820]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Can I Set different thresholds for different objects?
For example,I want to set the vehicle threshold to 0.5, person threshold  to 0.2, and bicycle threshold  to 0.2.
How can I do it when I export model

**Comment by Kayzwer** [comment]
@simpson0826 this features is not provided but you can try filter out result from detection result.

**Comment by simpson0826** [comment]
> @simpson0826 this features is not provided but you can try filter out result from detection result.

**Comment by RizwanMunawar** [comment]
@simpson0826, you have the option to integrate this feature into the code yourself, as we haven't included built-in support for it.

The modification will be required in [line 25 of predict.py](https://github.com/ultralytics/ultralytics/blob/3c88bebc9514a4d7f70b771811ddfe3a625ef14d/ultralytics/models/yolo/detect/predict.py#L25)

**Comment by simpson0826** [comment]
@RizwanMunawar ， when I after train model and get the model ，can I get a confidence score of more than 0.85 for class 2? Or I can export model which confidence score of more than 0.85 for class 2

**Comment by RizwanMunawar** [comment]
@simpson0826 you can change the confidence score value for inference easily by following the above code sample I provided. 

**Export:** When exporting your model to a different format, the changes in confidence scores won't be automatically included. You'll need to write the code to visualize the detection bounding boxes with confidence values equal to or greater than the confidence threshold you specify.

**Comment by glenn-jocher** [comment]
@Kayzwer, setting different confidence thresholds for different objects when using your trained model can be accomplished during the inference step instead of the model exportation process. 

When exporting models, we generally do not incorporate specific confidence thresholds as these are more commonly set during model deployment. The exported model is a general model, ready to be used for any application. 

For your case, after exporting the model, during your inference routine, you can incorporate logic to filter detections based on their class and confidence score. This is where you can set the vehicle threshold to 0.5, person threshold to 0.2, and bicycle threshold to 0.2.

Please remember that these adjustments will need to be implemented in your application software that uses the exported model, rather than within the model itself.

I hope this helps! Let us know if you have more questions.
