### ISSUE TITLE
Does batch size matter during Inference in YOLO8

### ISSUE THREAD

**Issue by surya9teja** [ultralytics/ultralytics#4835]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I Have a pipeline where I am using YOLO v8 for object detection and Classification.  During inference I load all the image paths into a list and pass the list to the `model.predict` in batches. It seems like after every batch predictions the memory (RAM) is not freeing up. Is it intended or bug or memory leaks in my code? 

```
import json
from PIL import Image
from ultralytics import YOLO
import os

batch = 32
model_dir = 'runs/detect/train5/weights/best.pt'
base_directory = 'inference/data'
results = []
images_paths = []
valid_image_extensions = {'.jpg', '.jpeg', '.png'} 
classes = {0: "Diagram", 1: "Flowchart", 2: "Map", 3: "Photograph", 4: "Table"}


class Box:
    def __init__(self, box, class_name):
        self.x1, self.y1, self.x2, self.y2 = box
        self.caption = ''
        self.class_name = classes.get(class_name.item())

class Result:
    def __init__(self, result):
        self.path = result.path
        self.boxes = self.get_boxes(result.boxes.xyxy, result.boxes.cls)
    
    def get_boxes(self, cords, cls):
        boxes = []
        for box, class_name in zip(cords, cls):
            boxes.append(Box(box.tolist(), class_name))
        return boxes

class ResultEncoder(json.JSONEncoder):
    def default(self, o):
        if isinstance(o, Result):
            return {
                "path": o.path,
                "boxes": [{"coordinates": [box.x1, box.y1, box.x2, box.y2], "caption": box.caption, "class": box.class_name} for box in o.boxes]
            }
        return json.JSONEncoder.default(self, o)
    

if __name__ == '__main__':
    directories = ["73648DD-19300507", "73648FF-19321228"]
    model = YOLO(model_dir)
    for directory in directories:
        for file in os.listdir(base_directory + "/" + directory + "/"):
            extension = os.path.splitext(file)[1]
            if extension.lower() not in valid_image_extensions:
                continue
            images_paths.append(base_directory + "/" + directory + "/"+file)
    for i in range(0, len(images_paths), batch):
        preds = model.predict(images_paths[i:i+batch], conf=0.35)
        for pred in preds:
            results.append(pred)
    
    json_data = [Result(result) for result in results]
    json_object = json.dumps(json_data, indent=4, cls=ResultEncoder)
    json_dict = json.loads(json_object)
    with open('results.json', 'w') as outfile:
        json.dump(json_dict, outfile, indent=4)
```

Batch size doesn't matter here, when I use less number it's still increasing the RAM slowly and exponentially. At the end of the predictions all the batch_size uses same RAM. Sometimes I have like 500 Images I can't scale my resources infinitely. For me speed is not a big factor. So If there is anyway I can control this RAM hunger process. 

My current proxmox container configured with following specs

CPU - 4 Cores
RAM - 8 GB
Swap - 8 GB
GPU - 12 GB

Thanks :)

**Comment by surya9teja** [comment]
> 

The main problem here is, this line of the code `results.append(pred)` appending the predictions somehow loading up the RAM. It might be due to huge data stored in predictions from the model. If I remove the un-required content using custom Class `Result` seems to be a good option. 

`results.append(Result(pred))`

```
class Box:
    def __init__(self, box, class_name):
        self.x1, self.y1, self.x2, self.y2 = box
        self.caption = ''
        self.class_name = classes.get(class_name.item())

class Result:
    def __init__(self, result):
        self.path = result.path
        self.boxes = self.get_boxes(result.boxes.xyxy, result.boxes.cls)
    
    def get_boxes(self, cords, cls):
        boxes = []
        for box, class_name in zip(cords, cls):
            boxes.append(Box(box.tolist(), class_name))
        return boxes
```
Now with batch size 16 and large YOLO model, img size 640 seems using only 3.4 GB of RAM. Which is much more better than 8BG Swap with 6GB RAM in previous case. 

**As a feature request**
Option to add our own config what should be included in the results will really helpful. 
But for now, Thanks team for amazing project.

**Comment by glenn-jocher** [comment]
@surya9teja thank you for your feedback and I'm glad you found a solution to manage memory usage during inference. 

As you discovered, it seems that the RAM increase was due to accumulated prediction results which contained more information than needed. Your solution to filter the results and only store necessary information is a good approach.

Your suggestion to allow configuration of what should be included in the prediction results is a valuable one and something that could potentially be considered for future enhancements in the YOLOv8 model. We appreciate your kind words and thank you for your support. Your contributions help to improve the project.

**Comment by LeiaLi** [comment]
I find the testing results are slightly different if I infer with a different batch size on COCO2017 dataset. Why?

**Comment by glenn-jocher** [comment]
@LeiaLi slight differences in results with different batch sizes can occur due to several factors: different image padding/resizing when batching affects how images are processed together, floating-point precision variations during batch operations, and potential memory access pattern differences. These are typically very small numerical differences rather than significant accuracy changes. For most practical applications, these minor variations are expected and don't significantly impact overall model performance.
