### ISSUE TITLE
bad floor detection

### ISSUE THREAD

**Issue by Caliphamin** [ultralytics/ultralytics#4836]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hello
I am working on wall and floor detection with ade20k dataset. also I have been added some extra data as semi supervised learning.
now it is working fine like this
![4](https://github.com/ultralytics/ultralytics/assets/31003468/aecd34e4-c7af-4457-8bfd-849ed544a4eb)
here it is 

but now I am facing with problem. in some images the detection not working fine and detects with space between 
 ![6](https://github.com/ultralytics/ultralytics/assets/31003468/453cf88d-04bc-4228-86a9-2457e539120b)
is this a bug or something? or it is because of my data? 
or data ignore? when I want to start train, in finding train and validation image, there is some data that ignored by yolo.
WARNING  1.jpg: ignoring corrupt image/label: zero-size array to reduction operation minimum which has no identity
what is this warning means?

**Comment by surya9teja** [comment]
How many warning images you found during Epoch? If it is one or two then you can safely ignore them. If it is more, then you might need to look at your dataset images and it's corresponding labels.  
Regarding Floor, It seems okay to me not too bad may be look at the ratio between classes. It might be one of the case where floor label dataset is too small to train. Also, resizing of the coordinates from predictions to original image is not always perfect in segmentation.

**Comment by glenn-jocher** [comment]
@surya9teja hello,

Regarding the warning "ignoring corrupt image/label: zero-size array to reduction operation minimum which has no identity", this typically indicates that there's something wrong with that particular image or its corresponding labels in your dataset. It might be that the image is of zero byte size, which implies it's empty or corrupt, or its label file is empty. If there are only a few such warnings, you can generally ignore them as they won't significantly impact the model training.

However, if you see this warning for a large number of images, you should inspect your dataset and fix the issue. YOLOv8 disregards any image that it cannot process because of corrupted image data or label files.

As for the issue of floor detection being not correct in some cases, it could be due to a variety of factors. One possibility is that the model hasn't generalized well, possibly due to inadequate or imbalanced training data. In such cases, providing more diverse and balanced data might help.

Another potential reason could be limitations in the model's ability to scale and resize annotations from predictions back to the original image dimensions. This is a common challenge in object detection and segmentation tasks and could sometimes lead to discrepancies as you highlighted.

Finally, you've mentioned using ade20k dataset with some added extra data for semi-supervised learning. It might be useful to verify that the extra data is labeled correctly and is consistent with the ade20k dataset. Inaccurate or inconsistent labels can confuse the model leading to suboptimal performance.

I hope this answers your questions. Let us know if there's anything else we can do to assist you.

**Comment by Caliphamin** [comment]
so i can get from this replies, i should check my data. i should use roboflow to fix that. thanks for replies

**Comment by glenn-jocher** [comment]
@Caliphamin hello,

Yes, reviewing your dataset would be a good first step. With a more clean and consistent dataset, the performance of your model will likely improve. Using tools like Roboflow can indeed help to annotate and preprocess your dataset in a correct and consistent manner, solving common issues that can arise with manual data labelling.

Remember that having a diverse and balanced dataset is crucial for your model to generalize well. So, if your model is having difficulty accurately detecting floors, it might be beneficial to include more variations of this class in your dataset.

I'm glad the previous responses were helpful and I hope this provides further insight. If you encounter any more issues or have further questions, feel free to ask. We're here to help.

Best of luck with your project,
Glenn

**Comment by Caliphamin** [comment]
i've uploaded my data to roboflow and now when i'm trying to train i get this error
![image](https://github.com/ultralytics/ultralytics/assets/31003468/824ea159-d4c1-4b19-aefe-871bbf93d185)
here is one of my labels
[1-7-_jpg.rf.a2290789a07847d2180a315d3a25c7e5.txt](https://github.com/ultralytics/ultralytics/files/12641604/1-7-_jpg.rf.a2290789a07847d2180a315d3a25c7e5.txt)
this label first generated by yolov8 and i uploaded to roboflow now i am getting this error

**Comment by glenn-jocher** [comment]
Hi @Caliphamin,

Based on the error message, it seems like there might be an issue with your dataset annotations that is causing an AssertionError while parsing the labels. Usually, these kinds of errors occur when the bounding box coordinates in the annotation file are not within the expected range of 0-1 relative to the image size.

One possible cause for the issue could be due to how the data was processed or formatted when you exported your annotations from Roboflow. Without knowing the specifics of the output format you chose in Roboflow, it's hard to pinpoint the absolute cause. But, if the formats are mismatched or if the coordinates have been normalized differently, it might lead to this error.

For a standard YOLOv8 label, each row in the .txt file represents an individual bounding box with the structure: [class, x_center, y_center, width, height], with coordinates normalized to be within the range 0 to 1. You should ensure the label files exported from Roboflow follow this structure.

In the meantime, you may want to verify the integrity and structure of your exported data from Roboflow, ensuring that the bounding boxes are correctly defined and fall within the expected range. 

I hope this helps. Feel free to provide additional information if the problem persists after these checks.

Best,

Glenn

**Comment by Caliphamin** [comment]
@glenn-jocher 
i found what cause the error above the roboflow adds a class called object and also roboflow cannot convert yolo format i had to convert to coco and then to yolo

but still i don't know what causes bad floor detection

**Comment by Nik057** [comment]
@Caliphamin I'm also interested in using ade20k for floor detection with yolov8-seg, could you share dataset in roboflow?

**Comment by glenn-jocher** [comment]
@Nik057 hi there,

The dataset I'm using is the ADE20K dataset, which you can find freely available online, and then I've trained it with YOLOv8 for floor detection. After you download the dataset, you can upload it to Roboflow and use their tools to manage and preprocess the data.

While I'm unable to share my specific Roboflow dataset due to privacy and data usage policies, it's relatively straightforward to create your own using the ADE20K data and process it in Roboflow.

As for the floor detection issues I initially had, I'm still investigating and working on refining my model further. It's likely a combination of factors such as the quality and diversity of the training data and the model's ability to generalize across different floor types.

I hope this helps and best of luck with your project!
