### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by oceanzhf** [ultralytics/ultralytics#4841]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Why is v8/train.py missing from the current version? I want to run train.py directly on pycharm for training, what should I do?

**Comment by glenn-jocher** [comment]
@oceanzhf thanks for your question! It sounds like you're trying to directly train a YOLOv8 model in PyCharm by running a specific `train.py` script, which seems to be missing.

In the current version of the YOLOv8 repository, the scripts are organized differently. Instead of a separate `train.py` script, you now have to use the main executable which handles training, validation, prediction, exporting, tracking and benchmarking all in one.

If you want to train a model from PyCharm, you would still use this main executable script, with the appropriate arguments to specify training mode and other details. You can set your configurations and pass them as arguments when running the main script.

For example, if you wanted to train a model with a specific configuration, you could specify this in the arguments when running the main script.

Remember that PyCharm provides support for command line arguments, so you can set these in the "Run/Debug Configurations" menu before running your script. This way, you can specify the desired mode (e.g., train), the dataset, and any other configuration details as command line arguments.

I hope this answers your question! Please, feel free to reach out if you have any other doubts or if something is not clear with this new configuration.

**Comment by oceanzhf** [comment]
I found the .py file that I can train on, it's ultralytics/cfg/__init__.py. but I've got a new problem, when I run this py file directly to train on it, the Gflops are not printed in the logs, which might be a new bug!

**Comment by oceanzhf** [comment]
> @oceanzhf thanks for your question! It sounds like you're trying to directly train a YOLOv8 model in PyCharm by running a specific `train.py` script, which seems to be missing.
> 
> In the current version of the YOLOv8 repository, the scripts are organized differently. Instead of a separate `train.py` script, you now have to use the main executable which handles training, validation, prediction, exporting, tracking and benchmarking all in one.
> 
> If you want to train a model from PyCharm, you would still use this main executable script, with the appropriate arguments to specify training mode and other details. You can set your configurations and pass them as arguments when running the main script.
> 
> For example, if you wanted to train a model with a specific configuration, you could specify this in the arguments when running the main script.
> 
> Remember that PyCharm provides support for command line arguments, so you can set these in the "Run/Debug Configurations" menu before running your script. This way, you can specify the desired mode (e.g., train), the dataset, and any other configuration details as command line arguments.
> 
> I hope this answers your question! Please, feel free to reach out if you have any other doubts or if something is not clear with this new configuration.

I found the .py file that I can train on, it's ultralytics/cfg/__init__.py. but I've got a new problem, when I run this py file directly to train on it, the Gflops are not printed in the logs, which might be a new bug!

**Comment by glenn-jocher** [comment]
Hello @oceanzhf,

Good to hear you could initiate your training! Regarding the Gflops not being printed in the logs, it is not necessarily a bug. The way it's designed, YOLOv8 does not log Gflops during training by default. Gflops, or "giga floating point operations per second", is a measure of computational speed. During the development process, it was deemed to not be essential information for each training log.

However, if you're interested in calculating and logging the Gflops, the calculation code snippet is already present in the model code. The calculation is performed during model creation, but it's just not logged during the training process. You may modify your local scripts to print this information if you wish.

Hope that helps! Please let us know if you have any other questions or further issues.

**Comment by glenn-jocher** [comment]
Hello @oceanzhf,

Thank you for your clarification. Remember that when working from an IDE environment like PyCharm, the behavior might not be the same as when you run the scripts directly from the terminal due to different settings or configurations. 

If you are running the scripts from the terminal and you see the Gflops as part of the logs, it means that the feature is working as expected in that environment. When the Gflops are not displayed in PyCharm, it could be that PyCharm is handling standard output differently, or that it has different runtime configurations, or that it suppresses certain types of output. 

This difference in behavior is likely not a bug in the YOLOv8 scripts, but rather a difference in how PyCharm interfaces with Python scripts compared to a terminal environment.

I hope this gives you some clarity on your issue. Do not hesitate to ask if you have any other questions related to this or any other feature in YOLOv8.
