### ISSUE TITLE
Key point detection to find out the labels that reason out the key points

### ISSUE THREAD

**Issue by 2018-Summer** [ultralytics/ultralytics#4853]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

By loading the onnx file to do the model reasoning, I want to reason out the key points, how to find the label name corresponding to the key points.
C:\Users\94752\PycharmProjects\TransformerMeter\PytorchDet\InferKPonit.py 
1337.8207763671874 2352.688549804687
1335.004541015625 1847.4229248046875
1462.5955810546875 1734.851953125
1816.6768066406248 1612.6357543945312
1302.264404296875 1852.5405761718748
1460.964111328125 1706.0416259765625
1952.066162109375 1669.0352783203125
2132.95341796875 2317.89638671875
1727.7468749999998 2044.9876464843749
2034.5989746093749 1783.238928222656

At present, I have found the coordinates of the key points, but I do not know how to find the corresponding label, know the big guy please guidance, thank you very much

**Comment by glenn-jocher** [comment]
@2018-Summer hello and thank you for utilizing YOLOv8 for your project!

In order to determine the labels corresponding to the keypoints detected, please follow the procedure below:

1. Load the model using PyTorch or ONNX, depending on what is suitable for your application.
2. Perform inference using the model. It will output both the detected keypoints and corresponding labels in the form of tensors.
3. The output tensor usually contains coordinates, confidence scores, and class labels. The structure of the output tensor might vary based on the exact version of YOLOv8 you're using, but generally, the last element of each detection would represent label indices.
4. You can map these label indices to their corresponding names using the `names` attribute of the dataset used for training the model.

You might also want to refer to the 'predict()' function in the repository for a more detailed understanding of how to handle the model's outputs.

Just remember that the keypoints are highly dependent on the trained model along with the dataset it was trained on. For a custom dataset, this could be the labels you've annotated your keypoints with.

I hope this helps! Should you have further queries, do not hesitate to ask.

**Comment by 2018-Summer** [comment]
@glenn-jocher thank you! Following your guidance, I solved the problem,
