### ISSUE TITLE
Help Wanted, Disable the Default Augment function in Classification Train.

### ISSUE THREAD

**Issue by ljj727** [ultralytics/ultralytics#4871]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hello YOLOv8 Enthusiasts,

we training with YOLOv8-cls. Our data consists of vertically or horizontally elongated images, and the objects to be classified are tightly positioned within the entire image. In such cases, if we use transform CenterCrop, we missing important features that need to be learned during training.

```python

class ClassificationDataset(torchvision.datasets.ImageFolder):
       def __init__(self, root, args, augment=False, cache=False, prefix=''):
        ...
        self.torch_transforms = classify_transforms(args.imgsz)
        self.album_transforms = classify_albumentations(
            augment=augment,
            size=args.imgsz,
            scale=(1.0 - args.scale, 1.0),  # (0.08, 1.0)
            hflip=args.fliplr,
            vflip=args.flipud,
            hsv_h=args.hsv_h,  # HSV-Hue augmentation (fraction)
            hsv_s=args.hsv_s,  # HSV-Saturation augmentation (fraction)
            hsv_v=args.hsv_v,  # HSV-Value augmentation (fraction)
            mean=(0.0, 0.0, 0.0),  # IMAGENET_MEAN
            std=(1.0, 1.0, 1.0),  # IMAGENET_STD
            auto_aug=False) if augment else None
        ...
```

```python
def build_dataset(self, img_path):
    return ClassificationDataset(root=img_path, args=self.args, augment=mode == 'train', prefix=mode)

```
When I checked the following code, I found that torch_transforms by default includes CenterCrop, and when using Albumentations, you can choose not to use crop, flip, or color jitter through the augment parameter, but it's set to True for train. It doesn't seem like there's an obvious way to change augment to False. Is there any way to do this?

I noticed that Ultralytics wrote 'ClassifyLetterBox' but it doesn't seem to be used. So I used it in the following way:  
In (def classify_transforms)
```python
    ...
        # return T.Compose([CenterCrop(size), ToTensor(), T.Normalize(mean, std, inplace=True)])
        return T.Compose([ClassifyLetterBox(size), ToTensor(), T.Normalize(mean, std, inplace=True)])
    else:
        # return T.Compose([CenterCrop(size), ToTensor()])
        return T.Compose(ClassifyLetterBox(size), ToTensor())
```

It's not possible to apply ClassifyLetterBox when using Albumentations. I request code modifications to make it usable for Ultralytics users.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ljj727 hi there,

Thanks for reaching out regarding data augmentation within the ClassificationDataset for YOLOv8. You've done an excellent job articulating the challenge you are running into.

Data augmentation forms a key part of the training process, as it broadens the range of possible training samples and thereby improves model performance, particularly in generalization. However, it's understandable that in some scenarios, specific augmentations like `CenterCrop` might not be as beneficial, especially when working with images that heavily favor one dimension or have objects situated in a fashion that makes this augmentation counterproductive.

You're correct to observe that currently when it comes to using Albumentations, the augment parameter is hard set to True for training and cannot be adjusted directly. The existing configuration is geared towards general cases and common augmentation techniques. You suggested a modification of the default transformation function 'classify_transforms' to use 'ClassifyLetterBox' instead of 'CenterCrop', which is quite insightful.

While we cannot provide code modifications immediately, we certainly understand the significance of flexibility in using different augmentation strategies based on the nature of your dataset. Your feedback has given us an important point to consider for future updates.

We appreciate your patience and understanding in this matter. If you do decide to modify the repository to suit your needs, we encourage you to proceed, but remind you to comply with the AGPL-3.0 License conditions if you choose to distribute your changes.

Thanks again for your contribution to the YOLOv8 community!
