### ISSUE TITLE
Could not load the Qt platform plugin "xcb" using docker image

### ISSUE THREAD

**Issue by DavidJimenez10** [ultralytics/ultralytics#4885]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I'm starting with YOLOv8 an amazing work by the way. I tried to run inference on a video and visualize it using opencv; I used the code provided in the docs (https://docs.ultralytics.com/modes/predict/#streaming-source-for-loop).

```

[W NNPACK.cpp:64] Could not initialize NNPACK! Reason: Unsupported hardware.
0: 384x640 11 persons, 1 handbag, 1091.8ms
Speed: 131.2ms preprocess, 1091.8ms inference, 65.3ms postprocess per image at shape (1, 3, 384, 640)
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/usr/local/lib/python3.11/dist-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted

```

### Environment

I'm using the ultralytics:8.0.176-cpu docker image

### Minimal Reproducible Example

```
import cv2
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO('yolov8n.pt')

# Open the video file
video_path = "path/to/your/video/file.mp4"
cap = cv2.VideoCapture(video_path)

# Loop through the video frames
while cap.isOpened():
    # Read a frame from the video
    success, frame = cap.read()

    if success:
        # Run YOLOv8 inference on the frame
        results = model(frame)

        # Visualize the results on the frame
        annotated_frame = results[0].plot()

        # Display the annotated frame
        cv2.imshow("YOLOv8 Inference", annotated_frame)

        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        # Break the loop if the end of the video is reached
        break

# Release the video capture object and close the display window
cap.release()
cv2.destroyAllWindows()

```

### Additional

After looking inside issues, I found some answers for this common problem such as re-intalling opencv-python, install Qt platform plugin, or install PyQt5, none of them works. It's a bit annoying because I thought with the docker image I will prevent this.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@DavidJimenez10 hello, thank you for raising this issue and for your willingness to contribute a PR. The error message you're getting indicates that there's an issue with your Qt platform plugin "xcb" which is a library used by OpenCV to display images and videos. 

The Ultralytics Docker Container is built under assumptions of non-interactive jobs, such as training or testing without any visualization activated. Given that you're trying to use OpenCV's imshow function to visualize results within the docker environment, it appears this functionality is missing from the container.

Hence, this is not an issue with YOLOv8 but with the specific configuration of your Docker environment.

Here's a general suggestion:

1. **Try running in a headless manner**: If visualization is not strictly necessary, you could write the frames to a video file rather than attempting to display them in real-time. The YOLO module has built-in functionality for saving detections to a new video file.

2. **Properly install GUI-related dependencies in your Docker image**: In case you definitely need to visualize detections in real-time inside the docker container, you need to make sure all necessary GUI-related dependencies are installed and correctly set up, including OpenCV and the aforementioned "xcb" plugin. This might involve re-building your Docker image.

As mentioned above, if you find a solution and want to share it, feel free to create a PR. Your contribution would be very helpful to others who may encounter a similar problem. We recommend providing a clear description and steps to reproduce the solution in the PR. Thank you for your contribution to the YOLOv8 community!

**Comment by DavidJimenez10** [comment]
@glenn-jocher Thanks for the comprehensive and clear explanation. I will try both suggestions.

**Comment by glenn-jocher** [comment]
You're welcome, @DavidJimenez10! I'm glad to hear that you find the suggestions helpful. Both methods should be able to solve your issue, depending on whether you require real-time or post-process visualizations. 

First, try running your program in a headless manner and writing your frames to a video file instead of displaying them in real time. This approach doesn't require GUI-related dependencies and works smoother in a Docker environment. 

On the other hand, if real-time visualization inside the Docker container is necessary for your project, ensure you have installed all the GUI-related dependencies correctly, including OpenCV and "xcb" plugin. You will likely need to rebuild your Docker image incorporating these elements. 

Either of these solutions should help you continue with your work. Thanks for your patience in debugging this, and don't hesitate to reach out if you have any questions or run into further issues. Your contributions to our community are much appreciated!
