### ISSUE TITLE
Track example ?

### ISSUE THREAD

**Issue by apiszcz** [ultralytics/ultralytics#4892]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

What do I have configured incorrectly?

The track example below uses 
`        annotated_frame = results[0].plot()`

When I execute the similar call I am getting the following error:

```
results = model.track(source=frame.to_image(), verbose=False, device=gpu, stream=True, persist=True)
annotated_frame = results[0].plot()
                      ~~~~~~~^^^
TypeError: 'generator' object is not subscriptable
```

FROM docs
https://docs.ultralytics.com/modes/track/#plotting-tracks-over-time

Python Examples
Persisting Tracks Loop

Here is a Python script using OpenCV (cv2) and YOLOv8 to run object tracking on video frames. This script still assumes you have already installed the necessary packages (opencv-python and ultralytics).

Streaming for-loop with tracking

import cv2
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO('yolov8n.pt')

# Open the video file
video_path = "path/to/video.mp4"
cap = cv2.VideoCapture(video_path)

# Loop through the video frames
while cap.isOpened():
    # Read a frame from the video
    success, frame = cap.read()

    if success:
        # Run YOLOv8 tracking on the frame, persisting tracks between frames
        results = model.track(frame, persist=True)

        # Visualize the results on the frame
        annotated_frame = results[0].plot()

        # Display the annotated frame
        cv2.imshow("YOLOv8 Tracking", annotated_frame)

        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        # Break the loop if the end of the video is reached
        break

# Release the video capture object and close the display window
cap.release()
cv2.destroyAllWindows()

Please note the change from model(frame) to model.track(frame), which enables object tracking instead of simple detection. This modified script will run the tracker on each frame of the video, visualize the results, and display them in a window. The loop can be exited by pressing 'q'.

**Comment by glenn-jocher** [comment]
@apiszcz thank you for raising this issue. It appears that you're encountering a `TypeError: 'generator' object is not subscriptable` when trying to call `results[0].plot()` in the tracking mode of YOLOv8. This likely suggests that the `track()` function is returning a generator, rather than a list of results.

In the YOLOv8 tracking mode, the model runs detection on each frame and then tracks the detected objects. If the `stream=True` option is used, as in your code, the `track()` function is expected to return a generator of results (one for each frame), rather than a single list of results. This is the reason why you're encountering a TypeError when trying to index it like a list.

To resolve this, you could consider iterating through the generator object as shown below:

```python
results = model.track(source=frame.to_image(), verbose=False, device=gpu, stream=True, persist=True)
for res in results:
    annotated_frame = res.plot()
```

By modifying your code in this way, you should be able to iterate through each result and plot the annotations on each frame. The `stream=True` argument allows you to process streaming video frame by frame.

Don't hesitate to get back to us if you encounter further issues or have any more questions!

**Comment by apiszcz** [comment]
Thanks, it worked.

**Comment by glenn-jocher** [comment]
@apiszcz i'm pleased to hear that the proposed solution resolved your issue! Understanding the return types of different functions, especially when dealing with generators, can indeed be a bit tricky but it's rewarding when everything clicks into place.

If you encounter any further issues or have additional questions about YOLOv8 or anything else in this repository, don't hesitate to reach out. We're here to help. Happy coding!
