### ISSUE TITLE
Display the segmentation target with a border

### ISSUE THREAD

**Issue by lkpopo** [ultralytics/ultralytics#4898]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In the segmentation task, I hope that the prediction result is to distinguish different targets with borders instead of filling them with colors. What should I do?

**Comment by glenn-jocher** [comment]
@lkpopo hi there, 

Thank you for reaching out with your question. 

For the segmentation task in YOLOv8, the produced results are typically displayed with different colors for each segmented class. This is a standard visualization method as it provides clearer differentiation of classes in the segmented image. 

To achieve your requirement of displaying the targets with borders instead of color-filled regions, you would need to modify the post-processing stage of the segmentation pipeline. Specifically, you would need to create a routine to follow the boundaries of the segmented regions, and then draw these boundaries on the original image. This can be accomplished by investigating the edge detection algorithms, which are able to outline the edges of an object, effectively creating a border. 

Note that creating and drawing these boundaries might result in a more cluttered output, particularly for images with many objects, as the borders could possibly overlap or appear very close to each other. 

I hope this provides a clear direction on how to proceed with your requirement. This would certainly be an interesting customization to the standard segmentation task in YOLOv8!

Best of luck with your project!
