### ISSUE TITLE
what is the correct collected image size if we know required smallest object size ?

### ISSUE THREAD

**Issue by maro-jeon** [ultralytics/ultralytics#4902]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Now I build my own detection system.

I collect 4K image from video stream. this is such a large size for saving and transfering.
I just choose the raw image size (4K) because someday I might change network input size from 640,640 to larger size for some reasons.

So, I wanna choose the suitable image size for reasonable collecting data if I know the minimum size of objects.

this is my approach.
32x32 in 4K image is my minimum object size.
it can be resized to 640 (3840 x 1/6) and object size should be (5.3 pixel)
and before head layer the output map size will be 20x20 (x 1/32, 0.15 pixel) or 40x40 (x 1/16, 0.33 pixel) or 80x80 (x 1/8, 0.66 pixel).
![image](https://github.com/ultralytics/ultralytics/assets/135101992/c54c2bca-c18c-4d84-b26d-6842ba7c2810)

when the object size in feature map is less than 1 pixel, detector can detect the object ?
and I need to increase the minimum object size up to 48 pixel ?

**Comment by glenn-jocher** [comment]
@maro-jeon hello,

The first step in determining an adequate dataset image size is indeed identifying the smallest object size you intend to detect. As per your observation, if you have a minimum object size of 32x32 in a 4K resolution, it will be significantly reduced when you resize the image to a network input size.

However, the primary aim of looking into the smallest object size is not to ensure that it resolves to at least one pixel in every feature map in the network, but rather to ensure the object maintains enough detail after resizing such that it remains distinguishable for detection.

Even when an object is less than one pixel in a feature map, the network can still potentially detect it because convolutional layers and pooling layers can handle sub-pixel information. However, such detections can be prone to inaccuracies, so maintaining a reasonable size for your smallest object is advisable.

Unfortunately, there is no definitive formula to calculate the best dataset image size based on the smallest expected object size. It may require experimentation and testing. If increasing the minimum object size to 48 pixels improves the results satisfactorily, you may consider adjusting the image size accordingly.

Remember, balancing computational resources and model performance is key. So, it's all about finding the sweet spot between a reasonable image size that doesn't skyrocket your computational needs and offers good detection results. 

Best regards and happy experimenting!
