### ISSUE TITLE
How to extract all probabilities for a given bounding box in yolov8?

### ISSUE THREAD

**Issue by camiloromers** [ultralytics/ultralytics#4908]
@camiloromers Since you already possess the results array, you can utilize it for additional processing by referencing the provided example below.
```
results = model.predict(source="img.jpg", line_width=1, show_conf=False, save=True) 

boxes = results[0].boxes.xywh.cpu()                        #xywh bbox list
clss = results[0].boxes.cls.cpu().tolist()                 #classes Id list
names = results[0].names                                   #classes names list
confs = results[0].boxes.conf.float().cpu().tolist()       #probabilities of classes

for box, cls, conf in zip(boxes, clss, confs):
    x, y, w, h = box
    label = str(names[cls] + " "+ str(conf))
    x1, y1, x2, y2 = x-w/2, y-h/2, x+w/2, y+h/2            #xyxy bbox
    .......
......
```

_Originally posted by @RizwanMunawar in https://github.com/ultralytics/ultralytics/issues/4895#issuecomment-1718881516_
       
Given my previous question was marked as `fixed` sorry I need to open a new question clarifying a bit better.

I would like to get all class probabilities for a given predicted bounding box. Let's say you are trying to detect 3 classes with yolo and but each predicted bonding box I'd like to get all class probabilities.

BBox 1 - class_1 prob, class_2 prob, class_3 prob
BBox2 - class_1 prob, class_2 prob, class_3 prob

and so on

**Comment by glenn-jocher** [comment]
@camiloromers hi, thanks for your question!

To extract all class probabilities for a given bounding box in YOLOv8, please keep in mind that YOLOv8, by default, gives you the probability for the class with the highest confidence score in the bounding boxes it predicts, rather than the probabilities for every class.

However, you can change this in the output processing section of the code. When you call the detection method in the model and get the prediction results, it actually contains class probabilities across all classes for each bounding box.

These probabilities are located in the decode layer of the network and are typically thresholded (reduced to one class with the highest probability) to provide one final class prediction per bounding box when outputted.

What you'd need to do is adjust the function that processes these raw output tensors to return the full class probability vectors for each bounding box rather than the one maximum-confidence class.

Please note that this will significantly increase the amount of data produced for each detection and may require changes in how you process and handle prediction outputs downstream. Make sure you handle your output arrays carefully to avoid out-of-memory errors. Happy coding!
