### ISSUE TITLE
Displaying Losses during model.val() for Modified YOLOv8

### ISSUE THREAD

**Issue by ThomasRochefortB** [ultralytics/ultralytics#4910]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I'm enhancing YOLOv8 by adding an extra regression head. I would like to print the losses during model.val(), analogous to how validation loss is displayed during model.train(val=True).

I found a related solution for YOLOv5 on [Stack Overflow](https://stackoverflow.com/questions/76499195/how-to-show-losses-when-running-validation-val-py-on-a-testing-dataset-in-ultr). However, applying the same approach to YOLOv8 proved challenging due to the AutoBackend module usage in validator.py when self.training = False.

Ideally, I would like to see all the same metrics that are displayed in the results.csv during training.

Any guidance on achieving this would be greatly appreciated!

**Comment by glenn-jocher** [comment]
@ThomasRochefortB hello,

Thanks for your interest in extending YOLOv8 by adding an extra regression head and for digging deeply into our codebase!

From your explanation, I understand you'd like to observe the losses in some form during the validation process, akin to how it's done during training.

When the model is in evaluation mode with `model.val()`, as opposed to training mode with `model.train()`, it's not set up to display the loss metrics the same way. This is due to differences in both the goals and the processes for training and validation phases. During training, the model learns from the data and updates its parameters so tracking and displaying the loss is useful. But in evaluation, the main aim is to check the model's performance against unseen data, and we primarily concern ourselves with metrics that reflect that performance, such as the model's accuracy or F1-score on the validation data.

The AutoBackend module's role here is largely to enable seamless operation across various hardware acceleration backends such as CPUs, GPUs and TPUs.

Nevertheless, if you wish to print losses during validation, you'll need to modify the existing validation function. You'd add code within model.val() that calculates the losses exactly like it is done during training. It's important to note you'd be calculating and exposing these values without affecting the model parameters as this should remain a non-updating evaluation phase.

However, exposing these metrics during validation is not a typical practice, as they don't provide the evaluative insight desired from a validation phase. Your focus should ideally be on the performance metrics - Precision, Recall, mAP etc., which give a more meaningful view of how well the model performs against the validation set.

Hope this helps and happy modeling!

**Comment by ThomasRochefortB** [comment]
@glenn-jocher Thanks for the quick answer. You are right, I think I should focus on implementing new regression metrics. Any tips on how I could do that?

**Comment by glenn-jocher** [comment]
Hi @ThomasRochefortB, 

Implementing regression metrics such as Mean Squared Error (MSE) or Mean Absolute Error (MAE) for your model is certainly doable and, in fact, can provide valuable insights into your model's performance.

Here's the basic process to follow:

1. **Compute predictions:** In the validation process, as you evaluate each batch of data, your model will output its predictions. Ensure to collect these predictions produced by your model.

2. **Gather the ground truth labels:** Simultaneously, for each batch, gather the corresponding ground truth labels.

3. **Calculate the regression metrics over your predictions & ground truth:** Calculate the MSE and/or MAE over your model predictions and corresponding ground truth labels.

You can do these calculations in two places: 

- **Inside the model:** This would require altering your model's architecture to include these metrics, but it might make the model overly complex and these metrics may not necessarily contribute to your model's learning.

- **Outside the model:** This is perhaps a cleaner alternative. Here, you would avoid changing your model's architecture and, after getting your model's output predictions and the batch's ground_truth, compute the metrics within the validation loop.

Remember to keep these calculations separate from the model’s backpropagation and optimization process. You should ensure that no gradients are calculated for your metrics to prevent them from affecting the learning process.

Do note that these metrics are just numbers and might not necessarily correlate with better object detection. Fundamentally, MSE and MAE are pixel-level metrics and often don't translate directly into better box predictions or object detection metrics such as mAP, Precision, and Recall.

Remember, adding these metrics is a form of extending debug information. It can help understand the model's regression performance but might not be useful in improving model performance directly.

I hope this helps, and good luck in extending the YOLOv8!
