### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement openvino (from versions: none) ERROR: No matching distribution found for openvino

### ISSUE THREAD

**Issue by Rasantis** [ultralytics/ultralytics#4916]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

im trying to install openvino in a raspberry pi with 64 bits system. and i got this error:
ERROR: Could not find a version that satisfies the requirement openvino (from versions: none)
ERROR: No matching distribution found for openvino

how to install openvino in the raspberry pi ?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by RizwanMunawar** [comment]
@Rasantis, Thanks for bringing up the OpenVINO issue.

Regarding the challenges you're encountering, it's more likely to be an installation rather than a problem with YOLOv8 code. I'd recommend directing any inquiries related to OpenVino to the knowledgeable community over at [Openvino Discussions](https://github.com/openvinotoolkit/openvino/discussions).

Additionally, based on the error you've encountered, you may find these resources helpful:

- [OpenVINO 2022.3.0 Raspberry pi 4 can't install openvino-dev](https://stackoverflow.com/questions/76100161/openvino-2022-3-0-raspberry-pi-4-cant-install-openvino-dev)
- [Error when building OpenVINO 2022 on Raspberry OS Buster 32bit](https://github.com/openvinotoolkit/openvino/issues/12033)
- [Installing OpenVino for Movidius NCS2 on Raspberry Pi 4]( https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/Installing-OpenVino-for-Movidius-NCS2-on-Raspberry-Pi-4/m-p/1475600)

These resources can provide valuable insights into resolving the issue. Keep up the great work!
