### ISSUE TITLE
Volo 8 Predict from webcam

### ISSUE THREAD

**Issue by chenchen-boop** [ultralytics/ultralytics#4919]
### Discussed in https://github.com/orgs/ultralytics/discussions/2547

<div type='discussions-op-text'>

<sup>Originally posted by **giscus[bot]** May 11, 2023</sup>

    I set source=0  to use the webcam,but the frame stuck on first frame ,it didn't update.
    Hope someone can help me figure out!

    my code :
        model = YOLO("best.pt")
        model.predict(source=0,show=True,conf=0.5)

    (Terminal keep showing "WARNING  Waiting for stream 0")

</div>

**Comment by glenn-jocher** [comment]
@chenchen-boop hi there, 

Thanks for reaching out and sharing the details of the issue you're experiencing with YOLOv8 webcam predictions.

From the error message "WARNING Waiting for stream 0", it seems like your program is waiting for the video input from the webcam but not receiving it. This could be due to a few possible reasons:

1. Other applications using the webcam: Please make sure no other application is using the webcam at the same time.

2. Webcam Permissions: Depending on your operating system and the environment, you might need to grant explicit permission to your Python environment to access your webcam.

3. Incorrect source value: While '0' is usually the default source for the built-in webcam, it can vary across different systems and hardware setups. If you have multiple cameras, you might need to use '1' or '2' as the source. 

4. Webcam compatibility: Ensure your webcam is functional and compatible with the libraries used in YOLOv8.

Please verify these points and try running your code again.

In case you continue experiencing this issue, don't hesitate to provide more details about your environment (Operating System, Python version, etc.), and we'd be glad to assist you further.

Best regards,
The Ultralytics Team
