### ISSUE TITLE
_lzma.LZMADecompressor' object has no attribute 'needs_input'

### ISSUE THREAD

**Issue by mayops8** [ultralytics/ultralytics#4937]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Dataset 'media/model_name/data.yaml' error ❌ '_lzma.LZMADecompressor' object has no attribute 'needs_input'
When I try to run yolov8 on linux centos server this error raises
but when I run same code on my local system it runs smoothly
So any one can help me out????
and also I am training on custom dataset of invoice documents.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@mayops8 hello, thank you for reporting this issue. The '_lzma.LZMADecompressor' object has no attribute 'needs_input' error usually happens when there is a version mismatch in the lzma library which is used for data compression and decompression.

From your description, the code runs smoothly on your local system but raises an error on a Linux CentOS server, so the issue might be related to different environment setups on your local system and server. It could possibly be due to the different Python versions or lzma library versions on your local system versus the Linux CentOS server.

I would suggest cross-verifying the Python and lzma package versions on both systems. If they are not the same, you might want to align the versions. You can do this by installing the specific version of Python that works on your local system on the server as well. Similarly, check the lzma package version and ensure it is the same on your server.

A best practice to avoid such discrepancies between different runtime environments is to use something like Docker that will provide consistency across environments.

The custom dataset for invoice documents shouldn't be causing such an issue, but if aligning the Python/lzma versions doesn't solve the problem, you might want to check if the dataset files are properly decompressed or if they are causing issues during decompression in the server environment.

I hope this helps! Don't hesitate to get back to us if you have more questions or if the problem still persists, and we will be glad to help further.

**Comment by glenn-jocher** [comment]
@mayops8 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by aliaminibagh** [comment]
> @mayops8 hello, thank you for reporting this issue. The '_lzma.LZMADecompressor' object has no attribute 'needs_input' error usually happens when there is a version mismatch in the lzma library which is used for data compression and decompression.
> 
> From your description, the code runs smoothly on your local system but raises an error on a Linux CentOS server, so the issue might be related to different environment setups on your local system and server. It could possibly be due to the different Python versions or lzma library versions on your local system versus the Linux CentOS server.
> 
> I would suggest cross-verifying the Python and lzma package versions on both systems. If they are not the same, you might want to align the versions. You can do this by installing the specific version of Python that works on your local system on the server as well. Similarly, check the lzma package version and ensure it is the same on your server.
> 
> A best practice to avoid such discrepancies between different runtime environments is to use something like Docker that will provide consistency across environments.
> 
> The custom dataset for invoice documents shouldn't be causing such an issue, but if aligning the Python/lzma versions doesn't solve the problem, you might want to check if the dataset files are properly decompressed or if they are causing issues during decompression in the server environment.
> 
> I hope this helps! Don't hesitate to get back to us if you have more questions or if the problem still persists, and we will be glad to help further.

Hello again @glenn-jocher

I have this issue and cannot fix it. I’m in need of your guidance.
How can check lzma version in ubuntu?

**Comment by glenn-jocher** [comment]
Hi @aliaminibagh 👋,

To check the `lzma` version on Ubuntu, you can use the following command in your terminal:

```bash
apt list --installed | grep lzma
```

This command lists all installed packages and filters out those related to `lzma`. If you're using `lzma` through Python, you can also check the Python package version (if installed via pip) with:

```bash
pip show lzma
```

However, it's worth noting that `lzma` is typically included as part of the Python standard library for Python versions 3.3 and above. So, if you're encountering issues, it might be more related to your Python version rather than a separately installed `lzma` package.

If you find version discrepancies or if your Python version is older, consider upgrading Python to match the version that works on your local system. You can check your Python version with:

```bash
python --version
```

or for Python 3:

```bash
python3 --version
```

If you need to align the environments further, using a virtual environment or Docker, as previously suggested, could help isolate and manage dependencies more effectively.

Let me know if this helps or if you have any more questions! 😊
