### ISSUE TITLE
yv8v180

### ISSUE THREAD

**Issue by apiszcz** [ultralytics/ultralytics#4938]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Specifying the model path in the configuration or on the command line.
yolo appears to be checking for a  yolov8n.pt file? I am specifying the 
full path to the model stored locally yolov8x6-500.pt. Why is there a check for the 8n model? In the past I recall yolo pulling int he 8n model for training, however I would like to use x6-500. Is that possible?
```

  File "/test/lib/_venvlnx/lib/python3.10/site-packages/ultralytics/utils/checks.py", line 472, in check_amp
    assert amp_allclose(YOLO('yolov8n.pt'), im)

```

**Comment by apiszcz** [comment]
I set amp to False in the configuration and all set. Is this is an issue?

**Comment by glenn-jocher** [comment]
@apiszcz hello and thank you for your question!

The issue you're encountering with the `assert amp_allclose(YOLO('yolov8n.pt'), im)` line is related to the usage of automatic mixed precision (AMP). AMP optimizes model training by combining the benefits of float32 and float16 data types.

If you set `amp` to False in the configuration, it disables AMP during the training process. However, this also implies that you're deactivating a potentially significant performance optimization.

The check you're referring to seems to be in place to validate if AMP is working correctly with a given model. It's not specifically due to the use of one model over another, but rather, ensuring that the training process works as intended with AMP.

Remember, you can still use your preferred model `yolov8x6-500.pt`. Just ensure that the model path is properly defined when running your commands.

If you're still encountering any issues, please provide us with a detailed explanation of the problem. This will allow us to assist you more effectively. Thanks!

**Comment by apiszcz** [comment]
"" Just ensure that the model path is properly defined when running your
commands."""
Using the same configuration with amp: True fails  Interesting.

**Comment by glenn-jocher** [comment]
Hi @apiszcz,

Thanks for your response. If setting `amp` to `True` is causing issues with your specific model, there may be some model characteristics that do not work optimally with Automatic Mixed Precision (AMP).

Remember, AMP is there to help optimize model training and can accelerate computations and save memory space by leveraging the properties of different data types. However, depending on the specifics of the model, using AMP may not always result in optimal performance.

In this case, if using `amp: False` in your configuration allows your model to train effectively, you could continue with this setting. You might notice slower training times or increased memory usage, but if the model is training correctly, that's the most important aspect.

We will investigate why your specific model fails when `amp` is set to `True`. Thanks for bringing this to our attention.

Let us know if you encounter any more issues or need further clarification on any point. We're here to help!
