### ISSUE TITLE
dataset format

### ISSUE THREAD

**Issue by gjhhust** [ultralytics/ultralytics#4963]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

train: Scanning /data/jiahaoguo/mmdetection/data/gaode_all_yolo/labels... 0 images, 6080 backgrounds, 0 corrupt: 100%
train: WARNING ⚠️ No labels found in /data/jiahaoguo/mmdetection/data/gaode_all_yolo/labels.cache. See https://docs.ultralytics.com/datasets/detect for dataset formatting guidance.
train: New cache created: /data/jiahaoguo/mmdetection/data/gaode_all_yolo/labels.cache
WARNING ⚠️ No labels found in /data/jiahaoguo/mmdetection/data/gaode_all_yolo/labels.cache, training may not work correctly. See https://docs.ultralytics.com/datasets/detect for dataset formatting guidance.
val: Scanning /data/jiahaoguo/mmdetection/data/gaode_all_yolo/labels... 0 images, 4093 backgrounds, 0 corrupt: 100%|█
val: WARNING ⚠️ No labels found in /data/jiahaoguo/mmdetection/data/gaode_all_yolo/labels.cache. See https://docs.ultralytics.com/datasets/detect for dataset formatting guidance.
val: New cache created: /data/jiahaoguo/mmdetection/data/gaode_all_yolo/labels.cache
WARNING ⚠️ No labels found in /data/jiahaoguo/mmdetection/data/gaode_all_yolo/labels.cache, training may not work correctly. See https://docs.ultralytics.com/datasets/detect for dataset formatting guidance.
Plotting labels to runs/detect/train12/labels.jpg... 
zero-size array to reduction operation maximum which has no identity
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 143 weight(decay=0.0), 206 weight(decay=0.0005), 226 bias(decay=0.0)
/data/jiahaoguo/ultralytics/ultralytics/nn/modules/transformer.py:86: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  grid_w = torch.arange(int(w), dtype=torch.float32)
/data/jiahaoguo/ultralytics/ultralytics/nn/modules/transformer.py:87: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  grid_h = torch.arange(int(h), dtype=torch.float32)
/data/jiahaoguo/ultralytics/ultralytics/nn/modules/transformer.py:89: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert embed_dim % 4 == 0, \
WARNING ⚠️ TensorBoard graph visualization failure 'NoneType' object is not subscriptable
Image sizes 1280 train, 1280 val
Using 8 dataloader workers
Logging results to runs/detect/train12
Starting training for 100 epochs...

      Epoch    GPU_mem  giou_loss   cls_loss    l1_loss  Instances       Size
  0%|          | 0/380 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/data/jiahaoguo/ultralytics/train_RT-DETR.py", line 10, in <module>
    results = model.train(model="config/re-detr/rtdetr-l.yaml", data='config/gaode_data.yaml', epochs=100, imgsz=1280, device=[0])
  File "/data/jiahaoguo/ultralytics/ultralytics/engine/model.py", line 337, in train
    self.trainer.train()
  File "/data/jiahaoguo/ultralytics/ultralytics/engine/trainer.py", line 195, in train
    self._do_train(world_size)
  File "/data/jiahaoguo/ultralytics/ultralytics/engine/trainer.py", line 331, in _do_train
    for i, batch in pbar:
  File "/home/jiahaoguo/miniconda3/envs/ultra/lib/python3.10/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/data/jiahaoguo/ultralytics/ultralytics/data/build.py", line 38, in __iter__
    yield next(self.iterator)
  File "/home/jiahaoguo/miniconda3/envs/ultra/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/jiahaoguo/miniconda3/envs/ultra/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/home/jiahaoguo/miniconda3/envs/ultra/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/home/jiahaoguo/miniconda3/envs/ultra/lib/python3.10/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/jiahaoguo/miniconda3/envs/ultra/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/jiahaoguo/miniconda3/envs/ultra/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jiahaoguo/miniconda3/envs/ultra/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/jiahaoguo/ultralytics/ultralytics/data/base.py", line 271, in __getitem__
    bboxes = label['bboxes']
KeyError: 'bboxes'

This is my error log showing that the label is not loading properly, but I am following the official data conversion requirements:
This is my data.yaml：
![image](https://github.com/ultralytics/ultralytics/assets/73829930/52c6dbf3-d0d8-44da-817b-29f57da01680)
This is the file directory for my dataset
![image](https://github.com/ultralytics/ultralytics/assets/73829930/027429c3-fc42-46b5-aa7e-6e144e31bb67)

### Additional
This is my data conversion script
![image](https://github.com/ultralytics/ultralytics/assets/73829930/621f7391-c026-4297-80f5-c9d6866720e4)

**Comment by glenn-jocher** [comment]
@gjhhust hi there, 

It seems like there's an issue with your label files. The error message indicates that no labels were found in your training and validation directories. 

The YOLOv8 expects your label files in the following format: 

`<object-class> <x> <y> <width> <height>`

Where `<object-class>` is an integer representing the index of the object's class. The bounding box coordinates `<x> <y> <width> <height>` should be normalized between 0 and 1 relative to the image's size.

Moreover, each of your images should be paired with a corresponding text file containing the labels. If you have an image named `image1.jpg`, then there should be a corresponding `image1.txt` file. Both these files should be in the same directory.

It would be best to revisit your label files to confirm that they confirm to this standard.

As for 'KeyError: 'bboxes'', this error occurs because the key 'bboxes' was not found in your dictionary. You might be calling a key that doesn't exist in your label files. 

In addition, make sure your data.yaml file is correctly referring to the right path where your data is located. It should contain the file paths for training and validation, number of classes for detection, and list of class names.

I hope this helps! If you're still having trouble, please let me know.

**Comment by gjhhust** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/73829930/019489f9-add3-439b-9248-1732fbdbd99b)
So far my files have all been put together as requested, test. TXT is as follows:
![image](https://github.com/ultralytics/ultralytics/assets/73829930/e57db922-721b-40f9-bb93-3ddf62d47ed9)

In the image file directory something like this:
````
0 0.020313 0.386719 0.04375 0.03125
````
but error continue：
````
WARNING ⚠️ No labels found in

and


Original Traceback (most recent call last):
  File "/home/jiahaoguo/miniconda3/envs/ultra/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/jiahaoguo/miniconda3/envs/ultra/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jiahaoguo/miniconda3/envs/ultra/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/jiahaoguo/ultralytics/ultralytics/data/base.py", line 271, in __getitem__
    bboxes = label['bboxes']
KeyError: 'bboxes'
````
![image](https://github.com/ultralytics/ultralytics/assets/73829930/7e9d1f72-288b-4fcd-8fb9-32ba9b613e60)



我的训练代码如下：
````
from ultralytics import RTDETR

# Load a COCO-pretrained RT-DETR-l model
model = RTDETR('rtdetr-l.pt')

# Display model information (optional)
model.info()

# Train the model on the gaode example dataset for 100 epochs
results = model.train(model="config/re-detr/rtdetr-l.yaml", data='data.yaml, epochs=100, imgsz=1280, device=[0])
````
data.yaml as:
````
path: /data/jiahaoguo/mmdetection/data/gaode_all_yolo  # dataset root dir
train: train.txt  # train images (relative to 'path') 4 images
val: test.txt  # val images (relative to 'path') 4 images
test:  test.txt # test images (optional)


````

**Comment by glenn-jocher** [comment]
@gjhhust thank you for providing additional details. From the information you've shared, it seems like your file format and data.yaml appear to be correct. The error `WARNING ⚠️ No labels found in` usually suggests that the labels aren't being located or read correctly, despite them being present.

Given that you have verified the label files are in the correct format and locations, let's try a few troubleshooting steps:

1. **Cache File:**
   The system is generating a `labels.cache` file which might not be updating correctly or could be referencing outdated file paths. Please delete any existing `.cache` files in your data directories and allow the system to regenerate them.

2. **File Paths:**
   Double-check the paths provided in `data.yaml` and ensure that the relative paths for `train`, `val`, and `test` are indeed relative to the `path` specified at the top. If there is a mismatch in the actual directory structure and the paths mentioned in the YAML file, the labels won't load.

3. **Permissions:**
   Ensure that the directory containing your dataset has the appropriate read permissions and that no files are being locked or inaccessible due to permission issues.

4. **File Extensions:**
   Verify that the image file names listed in your `train.txt` and `test.txt` files have the correct extensions and match the actual image files in your dataset folders.

5. **Data Integrity:**
   Assure all label text files correspond to an image file. An orphaned label file or missing image file can sometimes cause unexpected behavior.

6. **Content Validation:**
   Manually inspect a few label `.txt` files to ensure they follow the standard precisely. Check for formatting issues such as additional spaces, incorrect line breaks, or non-uniform line endings.

If the issue persists after these checks, you might need to do a more thorough step-by-step debugging to ensure the dataset is correctly read. Look into the data loading part of the code where it fetches `bboxes` from the label and confirm the label files are accessed and parsed as expected. 

Unfortunately, without a more in-depth look at the actual files and running environment, it's difficult to pinpoint the exact cause remotely. Please go through these checks, and if the problem continues, you might need to debug the Python code where data is loaded to find where the discrepancy lies.

I hope this can guide you towards resolving the issue. If the problem remains unresolved, please provide further details so we can assist you better.
