### ISSUE TITLE
RTDETR warning `.grad attribute of a Tensor that is not a leaf Tensor is being accessed`

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/ultralytics#4981]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

RTDETR models causing warnings now when built from YAMLs on forward pass. Not sure if this is related to my recent basing of Model(nn.Module), as I had to eliminate some `with torch.inference_mode:` lines to get that to work.

```
WARNING ⚠️ no model scale passed. Assuming scale='l'.
                   from  n    params  module                                       arguments                     
  0                  -1  1     25248  ultralytics.nn.modules.block.HGStem          [3, 32, 48]                   
  1                  -1  6    155072  ultralytics.nn.modules.block.HGBlock         [48, 48, 128, 3, 6]           
  2                  -1  1      1408  ultralytics.nn.modules.conv.DWConv           [128, 128, 3, 2, 1, False]    
  3                  -1  6    839296  ultralytics.nn.modules.block.HGBlock         [128, 96, 512, 3, 6]          
  4                  -1  1      5632  ultralytics.nn.modules.conv.DWConv           [512, 512, 3, 2, 1, False]    
  5                  -1  6   1695360  ultralytics.nn.modules.block.HGBlock         [512, 192, 1024, 5, 6, True, False]
  6                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  7                  -1  6   2055808  ultralytics.nn.modules.block.HGBlock         [1024, 192, 1024, 5, 6, True, True]
  8                  -1  1     11264  ultralytics.nn.modules.conv.DWConv           [1024, 1024, 3, 2, 1, False]  
  9                  -1  6   6708480  ultralytics.nn.modules.block.HGBlock         [1024, 384, 2048, 5, 6, True, False]
 10                  -1  1    524800  ultralytics.nn.modules.conv.Conv             [2048, 256, 1, 1, None, 1, 1, False]
 11                  -1  1    789760  ultralytics.nn.modules.transformer.AIFI      [256, 1024, 8]                
 12                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]              
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14                   7  1    262656  ultralytics.nn.modules.conv.Conv             [1024, 256, 1, 1, None, 1, 1, False]
 15            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 16                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]                 
 17                  -1  1     66048  ultralytics.nn.modules.conv.Conv             [256, 256, 1, 1]              
 18                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 19                   3  1    131584  ultralytics.nn.modules.conv.Conv             [512, 256, 1, 1, None, 1, 1, False]
 20            [-2, -1]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]                 
 22                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]              
 23            [-1, 17]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 24                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]                 
 25                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]              
 26            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 27                  -1  3   2232320  ultralytics.nn.modules.block.RepC3           [512, 256, 3]                 
 28        [21, 24, 27]  1   7466252  ultralytics.nn.modules.head.RTDETRDecoder    [80, [256, 256, 256]]         
rtdetr-l summary: 673 layers, 32970476 parameters, 32970476 gradients

/Users/glennjocher/PycharmProjects/ultralytics/venv/lib/python3.11/site-packages/torch/nn/modules/module.py:831: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:491.)
  if param.grad is not None:

image 1/1 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/bus.jpg: 640x640 (no detections), 962.0ms
Speed: 3.1ms preprocess, 962.0ms inference, 0.4ms postprocess per image at shape (1, 3, 640, 640)
```

### Environment

```
Ultralytics YOLOv8.0.181 🚀 Python-3.11.2 torch-2.0.1 CPU (Apple M2)
Setup complete ✅ (8 CPUs, 16.0 GB RAM, 267.0/460.4 GB disk)

OS                  macOS-13.5.2-arm64-arm-64bit
Environment         Darwin
Python              3.11.2
Install             git
RAM                 16.00 GB
CPU                 Apple M2
CUDA                None

matplotlib          ✅  3.7.2>=3.3.0
numpy               ✅  1.25.2>=1.22.2
opencv-python       ✅  4.8.0.76>=4.6.0
pillow              ✅  10.0.0>=7.1.2
pyyaml              ✅  6.0.1>=5.3.1
requests            ✅  2.31.0>=2.23.0
scipy               ✅  1.11.2>=1.4.1
torch               ✅  2.0.1>=1.8.0
torchvision         ✅  0.15.2>=0.9.0
tqdm                ✅  4.66.1>=4.64.0
pandas              ✅  2.1.0>=1.1.4
seaborn             ✅  0.12.2>=0.11.0
psutil              ✅  5.9.5
py-cpuinfo          ✅  9.0.0
```

### Minimal Reproducible Example

```python
from ultralytics import RTDETR

model = RTDETR('rtdetr-l.yaml')

results = model('ultralytics/assets/bus.jpg', imgsz=640)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@glenn-jocher I just tested it and yeah it's related to the elimination of `smart_inference_mode`. 
I'd like to know why we have to remove it, I also tested inference with manually adding it back and I don't see anything strange🤔.

Actually I found another bug, with current setting we can smoothly switch devices by `model.to()` api from torch, but if I move model to cpu and do once inference before moving it to cuda device then the error occurs:
```python
from ultralytics import YOLO
model = YOLO('yolov8n.pt')
model = model.cpu()  # new method along with .cuda(), .half(), .float(), etc.
results = model()  # cpu inference
print(model.device)  # prints cpu

model = model.to('cuda:0')
```
![pic-230920-1014-34](https://github.com/ultralytics/ultralytics/assets/61612323/4c868a90-07d1-47b7-9b8f-9d6c0f6de519)
and that'e because we manually set `os.environ['CUDA_VISIBLE_DEVICES'] = '-1'` in function `select_device` at the first inference, then the model can not find cuda device when trying `model.to("cuda:0")`.
https://github.com/ultralytics/ultralytics/blob/7f78fad8baceb41ba5e3f5af7b85b3e83930dd12/ultralytics/utils/torch_utils.py#L105-L106

**Comment by Laughing-q** [comment]
@glenn-jocher Probably it's too late to give my opinion since the changes are already made😂, but I never got the point why we have to add this feature(it seems it's from a issue proposed by a user if I recall), we already have a `device` arg and `select_device` function to manage devices very well. 
The `Model` we have is not actually a torch module model, we also don't need to make it like torch module model, it's just a high-level api we provide for users to train/val/predict and experience all our models as easy as possible.
Currently we have torch-like device management and also device arg and select_device function to also manage it, looks bloated and probably hard to maintain.

**Comment by Laughing-q** [comment]
@glenn-jocher ok updating this line
https://github.com/ultralytics/ultralytics/blob/7f78fad8baceb41ba5e3f5af7b85b3e83930dd12/ultralytics/engine/model.py#L369
to:
```python
        self.overrides['device'] = self.device  # i.e. device(type='cuda', index=0) -> 'cuda:0'
```
which would solve the conflict above since we return device directly in `select_device` if it's a torch.device type.
It's a small update and I'm not 100% sure if we're going to remain these two device managements so I will not make a PR of this, probably you can do it. :)

**Comment by glenn-jocher** [comment]
@Laughing-q yeah you're right, the current device selection is a bit strange, what we do is i.e. if they request device 3,4 then we set os.environ['CUDA_VISIBLE_DEVICES'] = '3,4' and then use indices 0,1 during training etc, but I think this can only be done once because once torch.cuda.visible_devices is run the result seems to be cached and it's not sensetive to new changes in CUDA_VISIBLE_DEVICES.

I've recently created two new files that can replace torch.cuda.is_available and torch.cuda.visible_devices here. These are 100% independent from torch and have no effect on later torch calls. 

In general our `select_device` approach needs a shift away from using CUDA_VISIBLE_DEVICES I think.

Also here's the test script I used when basing Model(nn.Module), if you can get this test script to work correctly with re-introducing smart_inference_mode() then yes let's add it back in!

One thing I discovered before was that smart_inference_mode() was nested in places, which was a waste, i.e. 


@smart_inference_mode
model.predict()

and then inside Predictor also, i.e.:

@smart_inference_mode
predictor.forward()

I think maybe this 2x nesting was causing problems. The device selection test script is here. I used 'mps' since I'm on a mac, but you can replace with 'cuda:0':

```python
from ultralytics import YOLO

model = YOLO('yolov8n.pt')
print(model.device)  # prints cpu

model = model.cpu()  # new method along with .cuda(), .half(), .float(), etc.
results = model()  # cpu inference
print(model.device)  # prints cpu

model = model.to('mps')
results2 = model()  # mps inference
print(model.device)  # prints mps

model = model.to('cpu')
results3 = model(device='mps')  # mps inference (method device arg overrides model.device)
print(model.device)  # prints mps
```

**Comment by glenn-jocher** [comment]
@Laughing-q the two new torch.cuda replacement files we can use are:

https://github.com/ultralytics/ultralytics/blob/7f78fad8baceb41ba5e3f5af7b85b3e83930dd12/ultralytics/utils/checks.py#L583-L609

**Comment by Laughing-q** [comment]
@glenn-jocher After some tests I just noticed that I only tested inference on one device this morning so even with `smart_inference_mode` it also worked fine, but after running inference once and call `model.to(cuda:0)` then error `Inference tensors do not track version counter.` raised....

**Comment by Laughing-q** [comment]
@glenn-jocher it seems like everytime we use `model.to()/.cuda()/.half()/float()` then model.grad would be reset then the warning raises when inference.
running inference twice and only shows warning one time, and the warning raises is because we use model.half() or model.float() inside `AutoBackend`.
```python
from ultralytics import YOLO

model = YOLO('yolov8n.yaml')
print(model.device)  # prints cpu

model = model.cpu()  # new method along with .cuda(), .half(), .float(), etc.
results = model()  # cpu inference
print(model.device)  # prints cpu

results2 = model()  # cuda:0 inference
print(model.device)  # prints cuda:0
```
![K068PiQrM9](https://github.com/ultralytics/ultralytics/assets/61612323/ae2b8a34-f601-4630-b5c8-756743cc9a41)

but running twice with device shift to cuda, the warning raises twice:
```python
from ultralytics import YOLO

model = YOLO('yolov8n.yaml')
print(model.device)  # prints cpu

model = model.cpu()  # new method along with .cuda(), .half(), .float(), etc.
results = model()  # cpu inference
print(model.device)  # prints cpu

model.cuda()
model()
```
![qb3wrQA7iv](https://github.com/ultralytics/ultralytics/assets/61612323/9bcafaae-748f-40a0-90be-33500488a87b)

**Comment by Laughing-q** [comment]
> @Laughing-q the two new `torch.cuda` replacement functions we can use are:
> 
> https://github.com/ultralytics/ultralytics/blob/7f78fad8baceb41ba5e3f5af7b85b3e83930dd12/ultralytics/utils/checks.py#L583-L609

I think this can not be a total replacement of torch.cuda, since this `cuda_is_available` would also return True if user only has nvidia driver installed but exclude the CUDA package, but truth is torch.cuda.is_avaiable() would be False since CUDA has not been installed yet.

**Comment by Laughing-q** [comment]
@glenn-jocher As far as I'm concerned, the best solution here is to revert the nn.Module changes.😂
