### ISSUE TITLE
RT-DETR Validation bug - expected scalar type Double but found Float 

### ISSUE THREAD

**Issue by shiragit** [ultralytics/ultralytics#4984]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

![Screenshot from 2023-09-19 17-14-05](https://github.com/ultralytics/ultralytics/assets/42112594/14310c62-2ae6-442d-aab5-0d88a9ce9f74)

### Environment

Ultralytics YOLOv8.0.181 🚀 Python-3.8.10 torch-2.0.1+cu117 CUDA:0 (NVIDIA RTX A6000, 48677MiB)

### Additional

Training on a custom dataset, tried both amp=False and amp=True.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@shiragit 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by shiragit** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/42112594/67c2e1ab-39ee-4748-be20-2447d4b8ee55)

I think I found the issue. this is a hard fp16 assignment (line 113), the gt_scores[idx] is from type **float** and therefore could not assign the half-tensors. 
@glenn-jocher

**Comment by glenn-jocher** [comment]
@shiragit got it. To debug we need a minimum reproducible example on a common dataset like COCO, VOC, etc. 

If you can reproduce the issue on one of our publicly available datasets please provide us the exact code we can run to see the issue ourselves.

If I can't reproduce I can't create and test a solution.
