### ISSUE TITLE
`yolo export` with Enterprise License

### ISSUE THREAD

**Issue by derek-knox** [ultralytics/ultralytics#4986]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When using `yolo export ...` the resulting `metadata.yaml` and .xml files have a license value of `GPL-3.0 https://ultralytics.com/license`. How is this value changed to reflect an Enterprise License? Is this dynamic (and if so where) or is the expectation for it to be manually overwritten?

**Comment by glenn-jocher** [comment]
@derek-knox ah, yes, don't worry about these license tags, this is the default license just like the license file at https://github.com/ultralytics/ultralytics/blob/main/LICENSE, but Enterprise license holders operate under the ELA terms rather than the AGPL-3.0 terms, despite the presence of AGPL-3.0 markings in the code or models.

**Comment by RizwanMunawar** [comment]
I am closing this issue. Please reopen if the issue persists
