### ISSUE TITLE
Can't release model from GPU

### ISSUE THREAD

**Issue by MarwanMagdy0** [ultralytics/ultralytics#4994]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Issue Description:
I am currently working on creating a graphical user interface (GUI) using PyQt5 with stacked widgets. My problem arises when I close a specific widget that should release the GPU resources associated with a loaded model, but it appears that the resources remain locked and cannot be released.

Expected Behavior:
When I close the widget containing the loaded model, I expect the GPU resources used by that widget to be released and available for use by other parts of the application or system.

Actual Behavior:
After closing the widget, the GPU resources associated with the loaded model seem to be retained, causing potential memory leaks and performance issues. These retained resources cannot be accessed or released, even after the widget has been closed.

model = YOLO("best.pt")
can you add a feature to YOLO class that i can use del key word on it?

### Additional

I have attempted to manually release resources using PyQt5's deleteLater() and Python's del keyword, but the issue persists. It is crucial to resolve this problem to prevent GPU resource leaks and ensure the efficient operation of the application.

**Comment by glenn-jocher** [comment]
@MarwanMagdy0 hello, and thank you for reaching out with your issue.

Managing GPU resources can indeed be a tricky aspect of deploying models in graphical applications. When it comes to YOLOv8 and releasing GPU resources, the behavior you're expecting (releasing the resources upon widget closure) should indeed be the default behavior when objects are no longer in use and garbage collected. However, Python's garbage collector might not immediately free up the resources, especially if some references to the model or its components still exist.

To address this, you want to ensure all references to the model are removed so the garbage collector can reclaim the GPU memory. However, the YOLO class itself does not include a specific method to release the GPU resources by design, as this is generally managed by PyTorch's underlying CUDA operations and the Python garbage collector.

Since you've tried using `del` and it hasn't resolved your issue, it might help to call `torch.cuda.empty_cache()` after you delete the model to help release any unreferenced memory. Also, if your application is multithreaded or if you are using multiprocessing, make sure those processes are properly managed and terminated.

Our documentation provides guidance on best practices when using our models, including methods to ensure that resources are handled efficiently. While we aim to ensure YOLOv8 works seamlessly in a multitude of environments, special considerations sometimes need to be made for specific applications like GUIs. It's worth reviewing the YOLOv8 sections pertaining to resource management on our documentation page for further tips that could be relevant. 

Thank you for your understanding, and please feel free to reach out if you continue to face issues or have more questions. Good luck on your GUI project!
