### ISSUE TITLE
very urgent help required in yolov8 model for json issue 

### ISSUE THREAD

**Issue by anut123** [ultralytics/ultralytics#5005]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

 In this github link --> https://github.com/ultralytics/ultralytics in yolov8 model
where I can find this line --> image name means object name ,confidence score,x_min,x_max,y_min,y_max values 
as i need json output like this ---> pred = [{"name": image_name, "confidence":  conf ,"x_min": x_min, "x_max": x_max, "y_min": y_min, "y_max": y_max}]
 how to do this i have tired alot but couldnt find the solution
it would be grateful if you could help me out with this very urgent help required

@RizwanMunawar 
@glenn-jocher 
@AyushExel

**Comment by glenn-jocher** [comment]
@anut123 see https://docs.ultralytics.com/hub/inference_api/#return-json-format

<img width="1554" alt="Screenshot 2023-09-20 at 21 24 30" src="https://github.com/ultralytics/ultralytics/assets/26833433/10e35522-40dd-4299-bead-b8bea7092225">

**Comment by anut123** [comment]
how to do this format in json i have tired alot but could not find any solution ---> {'predictions': [{'x_max': 819, 'x_min': 633, 'y_min': 354, 'confidence': 99, 'label': 'dog', 'y_max': 546}, {'x_max': 601, 'x_min': 440, 'y_min': 116, 'confidence': 99, 'label': 'person', 'y_max': 516}, {'x_max': 445, 'x_min': 295, 'y_min': 84, 'confidence': 99, 'label': 'person', 'y_max': 514}]} 
@glenn-jocher 
@AyushExel 
@RizwanMunawar

**Comment by RizwanMunawar** [comment]
@anut123, if you desire a JSON output file that encompasses detection details, you can utilize the provided code. This will generate a JSON file called `ultralytics.json` in your current working directory, which you can utilize at a later time.

```python
from ultralytics import YOLO
import json

# Load model
model = YOLO('yolov8n.pt')

# Run inference
results = model('https://ultralytics.com/images/bus.jpg')

# Store Json Results
results = json.loads(results[0].tojson())

# Print Json (If you want to view json results)
#print(results)

# Write results in a file
with open("ultralytics.json", 'w') as results_write_json:
    json.dump(results, results_write_json)

```

**Output Json Sample (ultralytics.json)**
```
[
    {
        "name": "bus",
        "class": 5,
        "confidence": 0.8703770041465759,
        "box": {
            "x1": 17.271846771240234,
            "y1": 230.5941925048828,
            "x2": 801.5409545898438,
            "y2": 768.4749145507812
        }
    },
    {
        "name": "person",
        "class": 0,
        "confidence": 0.8690632581710815,
        "box": {
            "x1": 48.738948822021484,
            "y1": 399.2716369628906,
            "x2": 244.5044708251953,
            "y2": 902.5147094726562
        }
    },
    {
        "name": "person",
        "class": 0,
        "confidence": 0.8535224199295044,
        "box": {
            "x1": 670.2679443359375,
            "y1": 380.2669677734375,
            "x2": 809.8577880859375,
            "y2": 875.7013549804688
        }
    },
    {
        "name": "person",
        "class": 0,
        "confidence": 0.8192945122718811,
        "box": {
            "x1": 221.39358520507812,
            "y1": 405.7908020019531,
            "x2": 344.72857666015625,
            "y2": 857.4010009765625
        }
    },
    {
        "name": "stop sign",
        "class": 11,
        "confidence": 0.34643399715423584,
        "box": {
            "x1": 0.06400930881500244,
            "y1": 254.645263671875,
            "x2": 32.2905158996582,
            "y2": 325.03546142578125
        }
    },
    {
        "name": "person",
        "class": 0,
        "confidence": 0.30071690678596497,
        "box": {
            "x1": 0.0,
            "y1": 551.0107421875,
            "x2": 67.13822174072266,
            "y2": 873.93798828125
        }
    }
]
```

**Comment by RizwanMunawar** [comment]
@anut123, you can utilize the provided code to save the confidence and other values as percentages. Thanks

```python
from ultralytics import YOLO
import json

# Load model
model = YOLO('yolov8n.pt')

# Run inference
results = model('https://ultralytics.com/images/bus.jpg')
print(results)
boxes = results[0].boxes.xyxy.tolist()
clss = results[0].boxes.cls.tolist()
names = results[0].names
confs = results[0].boxes.conf.tolist()

ultralytics_json = []
for box, cls, conf in zip(boxes, clss, confs):
    x1, x2, y1, y2 = box
    x1 = int(x1)
    x2 = int(y1)
    y1 = int(x2)
    y2 = int(y2)
    conf = str(int(conf * 100))+"%"
    name = names[int(cls)]

    box_data = {
        "name": name,
        "class": int(cls),
        "confidence": conf,
        "box": {
            "x1": x1,
            "x2": x2,
            "y1": y1,
            "y2": y2,
        }
    }

    ultralytics_json.append(box_data)

# Write results in a file
with open("ultralytics.json", 'w') as results_write_json:
    json.dump(ultralytics_json, results_write_json)

```

**Comment by anut123** [comment]
okay @RizwanMunawar but i want from this github link only https://github.com/ultralytics/ultralytics/blob/main/ultralytics/engine/results.py for the solution
"name": "person",
"class": 0,
"confidence": 0.30071690678596497,
"box": {
"x1": 0.0,
"y1": 551.0107421875,
"x2": 67.13822174072266,
"y2": 873.93798828125

this all decimal numbers i want in percentage example "y2": 873.93798828125 <-- it is in decimal and i want in percentage like 87% and i have tried do changes in https://github.com/ultralytics/ultralytics/blob/main/ultralytics/engine/results.py --> in this code line 345,346 eg - 'x1': row[0] / w % 100 so that i can get answer as an 87% but still i am getting the output as like this "x1": 873.93798828125 and in whole code files of yolov8 model i could find solution in results.py but still same issue is coming how to do this i have tired alot but couldnt find the solution
it would be grateful if you could help me out with this very urgent help required

@glenn-jocher 
@AyushExel 
the author's could you help me out the issue which i am facing

**Comment by glenn-jocher** [comment]
@anut123 you're almost there. The issue comes from using the modulus operator `%` in your change 'x1': row[0] / w % 100. The division values are sometimes above 1 (for percentages greater than 100%). To resolve this, you should keep the division but change the modulus to multiplication: 'x1': row[0] / w * 100. This will give you the correct percentage values. Ensure to apply this transformation to all your x1, x2, y1, y2 calculations to maintain consistency in your data. To get your values in percentage form like "87%" instead of 0.87, you need to convert the values into strings and append the percentage symbol. Remember to round off your values to the desired number of decimal places for easier interpretation.

**Comment by anut123** [comment]
okay @glenn-jocher but what ever changes i am doing in this code file ---> https://github.com/ultralytics/ultralytics/blob/main/ultralytics/engine/results.py it is not reflecting anything in the output result 
for eg---> i have written like this x1': row[0] / w * 100 then output should be 87% but still it is showing 0.87

**Comment by glenn-jocher** [comment]
Hello @anut123, the issue you're experiencing is likely due to the fact that the changes you've made in the code are in a local copy while your system might still be using the original version installed through pip. Once you've edited the code file on your local machine, you need to make sure that your script or notebook is also using this local version. Unfortunately, we can't provide code examples in this response, but typically you'd use the `sys` module in python to add the local directory to your system path. 

In the case of the specific change you want to make, keep in mind that just multiplying the calculation by 100 will only shift the decimal place, it will not add a percentage sign to the output. To add a percentage sign, you might have to convert the results to a string format and append '%'. Again, ensure your code is using the edited local version for these changes to take effect. If you're still having trouble, please provide more context about how you're running the model and using the results.

**Comment by anut123** [comment]
Thanks alot @glenn-jocher @RizwanMunawar for helping me

**Comment by glenn-jocher** [comment]
You're welcome, @anut123! I'm glad we could be of assistance. If you have further questions or need help with anything else, don't hesitate to ask. We're here to help. Happy coding!

**Comment by anut123** [comment]
Hi Glenn Jocher,
Could help me out with this issue
https://github.com/ultralytics/ultralytics/issues/5264 as very urgent help
required

**Comment by glenn-jocher** [comment]
Hello @anut123,

I've looked into issue #5264 that you've linked. The issue seems to be about converting the bounding box coordinates from decimals to percentages. This is relatively straightforward as it involves a simple arithmetic operation.

In the code file where these values are generated, you would want to identify where the bounding box coordinates (`x1`, `x2`, `y1`, `y2`) are being calculated. Once you have these, you can convert these decimal values to percentages by dividing them by the respective width or height (for `x1` and `x2` divide by width, for `y1` and `y2` divide by height) and then multiplying the result by 100.

Please ensure that you are making these changes in the correct file and that your script or notebook is using this updated version. If performed correctly, this should change your output from decimals to percentages.

Also, if you desire the output in the format "87%" rather than 0.87, you would need to convert the output into string and append '%' at the end.

Hope this helps! Let me know if you have any further issues.
