### ISSUE TITLE
It does not work to inference using YOLOv8's model when I use DNN_BACKEND_INFERENCE_ENGINE as  the backend in OpenCV DNN.

### ISSUE THREAD

**Issue by longzou** [ultralytics/ultralytics#5014]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict, Integrations

### Bug

I wrote a C++ code to predict the image as below. Firstly, I export the model yolov8n.pt into yolov8n.onnx by ONNX format. 
`
net = cv::dnn::readNetFromONNX("yolov8n.onnx");
net.setPreferableBackend(cv::dnn::DNN_BACKEND_INFERENCE_ENGINE );
net.setPreferableTarget(cv::dnn::DNN_TARGET_CPU);
...
net.forward(outputs, net.getUnconnectedOutLayersNames());  //Catch a exception: unspecified error in OpenCV guts (code: -99999)
...
...
`
But it's  works when I use yolov5 model.
And if I change the target into DNN_BACKEND_OPENCV. the yolov8 models are also working.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@longzou hello! Thank you for reporting this issue and providing detailed information. It seems like there's a problem with using the Inference Engine backend from OpenCV DNN with the exported YOLOv8 ONNX model.

It is important to note that support for running ONNX models could vary across different backends in OpenCV DNN, such as DNN_BACKEND_INFERENCE_ENGINE and DNN_BACKEND_OPENCV. These backends might be optimized for different sets of models and layers, which could be the reason for the difference in functionality.

One possible explanation is that the DNN_BACKEND_INFERENCE_ENGINE backend might not support some operations used in the YOLOv8 model, leading to the exception being thrown. You've mentioned that switching the backend to DNN_BACKEND_OPENCV makes the YOLOv8 model work, which suggests that this backend supports the necessary operations for the model.

As you've noted, verifying that it works with another model like YOLOv5 suggests that the backend is functioning correctly overall, but possibly does not support all features needed for YOLOv8.

At this stage, although we strive to make Ultralytics YOLO models compatible with various inference engines, we cannot guarantee perfect compatibility with all backends due to their internal differences. Our models are continually updated and improved, and we will endeavor to address these compatibility issues as we evolve the models.

If you continue to experience issues with DNN_BACKEND_INFERENCE_ENGINE and you can't switch to DNN_BACKEND_OPENCV permanently, please continue using the model and backend pair that's working for you at the moment while we look into this. Thanks again for bringing this to our attention.
