### ISSUE TITLE
RR-DETR return Predict Results wrong labels names

### ISSUE THREAD

**Issue by tranmanhdat** [ultralytics/ultralytics#5026]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

Results return from Prediction of [rtdetr-l.pt](https://docs.ultralytics.com/models/rtdetr/#supported-tasks) has names attibutes wrong, so when plot instead of names of objects it shows the index.
![Screenshot from 2023-09-22 09-46-40](https://github.com/ultralytics/ultralytics/assets/30494878/73501c59-97eb-4a5e-a0cd-4de632eb6c10)
Hot fix by change names of the result before plot
```
result.names = {0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 53: 'pizza', 54: 'donut', 55: 'cake', 56: 'chair', 57: 'couch', 58: 'potted plant', 59: 'bed', 60: 'dining table', 61: 'toilet', 62: 'tv', 63: 'laptop', 64: 'mouse', 65: 'remote', 66: 'keyboard', 67: 'cell phone', 68: 'microwave', 69: 'oven', 70: 'toaster', 71: 'sink', 72: 'refrigerator', 73: 'book', 74: 'clock', 75: 'vase', 76: 'scissors', 77: 'teddy bear', 78: 'hair drier', 79: 'toothbrush'}  
plot_img = result.plot(labels=True)
```

### Environment

Ultralytics YOLOv8.0.173 🚀 Python-3.9.12 torch-2.0.1 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 5913MiB)
Setup complete ✅ (20 CPUs, 15.4 GB RAM, 562.2/654.9 GB disk

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@tranmanhdat thank you for reporting this issue. It seems like the returned predictions are coming back with indices instead of the actual class labels. The hot fix you provided indeed manually replaces the indices with their respective COCO names, correcting the issue for now.

This behavior might be due to some parsing issues during inference where the class names, stored in the model metadata during training, might not be retrieved correctly. We definitely need to take a closer look into our RR-DETR model handling to pinpoint and resolve this issue. 

Your willingness to delve into the code and find a temporary solution is highly appreciated! I’ll create an internal issue for this and our team will start examining it. You’ll be updated once we have a solution. We’re looking forward to resolving this and enhancing the YOLOv8 repo experience for everyone. Your contribution to the YOLOv8 community is valuable and we're grateful for your support!

**Comment by glenn-jocher** [comment]
@GoulartNogueira thank you for sharing your experience. The model is not guaranteed to return the masks in a consistent order for each prediction. The order of classes in the output masks can vary based on the specific detections in each image. In your case, it appears that for this specific image, the model detected a 'tie' before it detected a 'person', which is why the 'tie' mask appears first in the output.

It's recommended to use the class indices from the prediction output to correctly map the masks to their corresponding classes, rather than relying on a fixed order. This approach should make your implementation robust against any changes in the detection order. Thank you again for this discussion, your contributions help improve the clarity and robustness of our models!

**Comment by GoulartNogueira** [comment]
> It's recommended to use the class indices from the prediction output to correctly map the masks to their corresponding classes, rather than relying on a fixed order. This approach should make your implementation robust against any changes in the detection order. 

@glenn-jocher 
Thank you very much for the tip.
I tried to use this approach. I looked through all objects avaliable, but I really couldn't make it work. Do you have a working example? Or could you be more specific about where I can find this map?

**Comment by glenn-jocher** [comment]
@GoulartNogueira, thank you for your follow-up question. The predicted results object actually includes a 'classes' attribute that contains a list of class indexes for the detections. Each detection (and corresponding mask) is associated with an index, which in turn corresponds to a specific object class in your model’s class labels. 

You can loop through these classes, and for each class in the prediction, match the class index with the corresponding mask by using the same index. With this approach, you ensure that each mask is correctly associated with its corresponding class, irrespective of the order of the detections.

I hope this helps clarify things. Please let me know if you have any further questions.
