### ISSUE TITLE
Soft link image set problem

### ISSUE THREAD

**Issue by Gaodzlearn** [ultralytics/ultralytics#5036]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

My dataset directory format is like:
dataset
     |─labels
     |     |─train 
     |    └─val
    └─images
           |─train (soft link to /home/images)
          └─val  (soft link to /home/images)

my dataset.yaml is like:
path: /dataset  # dataset root dir
train: images/train  # train images (relative to 'path') 4 images
val: images/test  # val images (relative to 'path') 4 images

However, when I train yolov8n with such dataset, it cannot find any labels. When I went deep into the code to debug, I found that the soft link of my image was converted to an absolute path here, and the program tried to find the tag under the absolute path.
https://github.com/ultralytics/ultralytics/blob/92753ebd84027172e572e2ce450c1395b08a38af/ultralytics/data/utils.py#L284C22-L284C27
I'm thinking this might be a bug, or can anyone point out how to do a soft link to an image? I have the same batch of images with annotations for many different tasks. I want to divide them into different folders. If soft links are not used, it will take up a lot of space.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Gaodzlearn hello,

Thanks for reaching out and explaining in such detailed manner.

Due to the way the soft links convert to absolute paths, the program indeed tries to find the labels under the absolute path, which could be causing the issue you're experiencing with the software being unable to locate them. This isn't a bug, but more of a specific scenario occurring due to the standard behavior of soft link conversion.

While using soft links aims to save storage space, it currently doesn't align perfectly with the way our program interrogates the pathing to find labels.

Instead, you could try creating separate folders with symlinks to your label files. Although this method doesn't reduce the space occupied, it might offer a way to structure your directories for different tasks without altering the label files.

Let us know if you try this approach and how it works for you. We understand every situation is unique, and we aim to learn from these situations to continuously improve the user experience.

Thanks for your help. We appreciate your patience.

**Comment by 1siddhi7** [comment]
A good workaround, which can help you save space can be: instead of directory level symlinks, use image level symlinks.

**Comment by glenn-jocher** [comment]
@1siddhi7, a concise approach to address your issue would be to create symlinks for individual image files rather than for the entire directory. This method should help maintain the relative paths for your labels and avoid the absolute path conversion problem. Give it a try and see if it resolves the issue. Thanks for your contribution to improving YOLOv8! 🚀

**Comment by Anze-** [comment]
**> A good workaround, which can help you save space can be: instead of directory level symlinks, use image level symlinks.**

**THIS WORKS,** it is the real answer, and if @glenn-jocher would not fill the issue comments with LLM generated spam, it would be easier to find the actual answer. If one needs a GPT answer, one can asks GPT. When one comes to Issues, wants tested solutions, not auto-generated attempts. Please do not send aother outogenerated answer after my text. BOT do not answer, do not reply.

**Comment by glenn-jocher** [comment]
Thank you for your feedback. If you have any further questions or need assistance, feel free to reach out.
