### ISSUE TITLE
How to inference by setting buffer flag to True in LoadStreams() class 

### ISSUE THREAD

**Issue by Pornpra-Ton** [ultralytics/ultralytics#5045]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

I have a problem with prediction results from yolov8 when I change source to stream as shown in figure.
This is what I did:
1. I install ultralytics by pip (pip3 install ultralytics --upgrade)
2. I convert yolov8s from .pt to .engine successfully (by model.export from ultralytics)
3. The converted tensorrt model can influence successfully with image and video file 
4. My rtsp url is valid when I test in VLC program (Sorry, I cann't share the full rtsp url)

How to solve this problem ?

![loadstream_error](https://github.com/ultralytics/ultralytics/assets/145788852/f99b0124-e8da-4c7f-96ea-829fccbe5413)

### Environment

Hardware: NVIDIA Jetson (Orin, 6481MiB)
Ultralytics: 8.0.184 
Python: 3.8.10 
Torch: torch-2.0.0+nv23.05 
CUDA: 11.3.315
cuDNN: 8.6.0.166
TensorRT: 8.5.2.2
OpenCV: 4.5.4 without CUDA

### Minimal Reproducible Example

This is my code

**I try to set buffer flag to True in LoadStreams() class by using this code** 

**source = LoadStreams(rtsp_url, imgsz=640, vid_stride=1, buffer=True)**

**and pass source variable as an input to inference**

Everything can run completely when I comment this line >> #source = LoadStreams(rtsp_url, imgsz=640, vid_stride=1, buffer=True)

**How to inference by setting buffer flag to True in LoadStreams() class ?**

![yolov8_code](https://github.com/ultralytics/ultralytics/assets/145788852/300eaffe-e863-4cfe-8d26-53445dc2d1e4)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by RizwanMunawar** [comment]
@Pornpra-Ton! The `LoadStreams` function is intended for reading multiple camera streams from a `stream.txt` file or a webcam stream. However, in your situation, you should replace `LoadStreams` with [`LoadImages`](https://github.com/ultralytics/yolov5/blob/6262c7feb42cd181f165681b9aff428785c0ff7e/detect.py#L114C26-L114C26).

Thanks.
