### ISSUE TITLE
load(): incompatible function arguments. The following argument types are supported:     1. (self: openvino._pyopenvino.FrontEnd, path: object) -> ov::frontend::InputModel

### ISSUE THREAD

**Issue by pawani2v** [ultralytics/ultralytics#5078]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

export failure ❌ 0.0s: load(): incompatible function arguments. The following argument types are supported:
    1. (self: openvino._pyopenvino.FrontEnd, path: object) -> ov::frontend::InputModel

Invoked with: <FrontEnd 'onnx'>, '/media/drive_8tb/trainings/yolov8_detect_training/15/weights/best.onnx', False
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/i2v/.virtualenvs/ultralytics/lib/python3.8/site-packages/ultralytics/engine/model.py", line 309, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/home/i2v/.virtualenvs/ultralytics/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/i2v/.virtualenvs/ultralytics/lib/python3.8/site-packages/ultralytics/engine/exporter.py", line 256, in __call__
    f[3], _ = self.export_openvino()
  File "/home/i2v/.virtualenvs/ultralytics/lib/python3.8/site-packages/ultralytics/engine/exporter.py", line 122, in outer_func
    raise e
  File "/home/i2v/.virtualenvs/ultralytics/lib/python3.8/site-packages/ultralytics/engine/exporter.py", line 117, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/home/i2v/.virtualenvs/ultralytics/lib/python3.8/site-packages/ultralytics/engine/exporter.py", line 396, in export_openvino
    ov_model = mo.convert_model(f_onnx,
  File "/home/i2v/.virtualenvs/ultralytics/lib/python3.8/site-packages/openvino/tools/mo/convert.py", line 364, in convert_model
    ov_model, _ = _convert(cli_parser, framework, params, True)
  File "/home/i2v/.virtualenvs/ultralytics/lib/python3.8/site-packages/openvino/tools/mo/convert_impl.py", line 958, in _convert
    raise e.with_traceback(None)
TypeError: load(): incompatible function arguments. The following argument types are supported:
    1. (self: openvino._pyopenvino.FrontEnd, path: object) -> ov::frontend::InputModel

Invoked with: <FrontEnd 'onnx'>, '//media/drive_8tb/trainings/yolov8_detect_training/15/weights/best.onnx', False

### Environment

```
Ultralytics YOLOv8.0.184 🚀 Python-3.8.10 torch-2.0.1+cu117 CPU (Intel Core(TM) i7-7700 3.60GHz)
Setup complete ✅ (8 CPUs, 31.2 GB RAM, 709.1/887.4 GB disk)

OS        :           Ubuntu20.04.1 (Linux  5.15.0-60-generic #66~20.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux)
Python  :           3.8.10
Install     :         pip
nncf       :   2.6.0
onnx       :   1.14.1
openvino  :    2023.1.0
openvino-dev  : 2023.1.0
ultralytics  : 8.0.184
```

### Minimal Reproducible Example

```
from ultralytics import YOLO
model = YOLO('/media/drive_8tb/yolov8_detect_training/15/weights/best.pt')
model.export(format='openvino', imgsz=(416,416))
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@pawani2v it appears that the error you're encountering is due to an incompatible function argument in the OpenVINO `load` function. The function expects certain types of arguments but is receiving different ones. 

Looking at your error message, it seems that the error occurs when trying to load the ONNX model for conversion to OpenVINO. The OpenVINO `FrontEnd` object expects a path to the model as an argument, but it's possible that the argument being provided isn't recognized as a valid path object. 

One thing worth checking is the ONNX model file path. Make sure that the ONNX model file exists at the specified location and is accessible. Also, check if the file path string is correctly formatted.

Please ensure that all dependencies, including OpenVINO, are updated and correctly installed. This issue could be due to a discrepancy with software versions or malfunctioning installations. 

Let us know if this advice helps, and if you still encounter issues, do provide more context or details for further support.

**Comment by pawani2v** [comment]
@glenn-jocher the ONNX model file exists on the specified paths, there are two files `best.onnx` and `best_dynamic_bs.onnx`.  As for discrepancy i have mentioned the versions of nncf, openvino also i created a new virtualenv where onnx, openvino packages were installed using Autoupdate ( `requirements: Ultralytics requirement ['openvino-dev>=2023.0'] not found, attempting AutoUpdate...` ) But still the same issue persists.
Let me know what more context/details can i provide.

**Comment by glenn-jocher** [comment]
@pawani2v thank you for your response and verification of the ONNX model file path. 

From your description, it seems like the versions of your packages (nncf, onnx, openvino) and their installation appear to be correct. Moreover, the creation of a new virtual environment further isolates and ensures that there’s little chance of conflicting dependencies.

This issue might arise due to the AutoUpdate feature being unable to resolve some dependencies correctly or some discrepancies in the types of arguments being passed to the 'load' function in OpenVINO. 

You could try manually installing the packages in your virtual environment instead of relying on AutoUpdate, which could possibly resolve any underlying dependency issues.

Please also confirm that you're using the correct format of OpenVINO, either the full package or the runtime package, based on your requirements. 

If none of the above solutions work, you may want to consider reaching out to the support of OpenVINO as this seems to be a more OpenVINO-centric issue.

**Comment by LinGeLin** [comment]
same error
`
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  load(): incompatible function arguments. The following argument types are supported:
    1. (self: openvino._pyopenvino.FrontEnd, path: object) -> ov::frontend::InputModel

Invoked with: <FrontEnd 'onnx'>, '/data/xxxx/ov_opt_test/movie_rec/20240416/arsenal_ir/model_post.onnx', False
[ ERROR ]  Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/openvino/tools/mo/convert_impl.py", line 889, in _convert
    ov_model, legacy_path = driver(argv, {"conversion_parameters": non_default_params})
  File "/usr/local/lib/python3.8/dist-packages/openvino/tools/mo/convert_impl.py", line 552, in driver
    graph, ngraph_function = prepare_ir(argv)
  File "/usr/local/lib/python3.8/dist-packages/openvino/tools/mo/convert_impl.py", line 406, in prepare_ir
    ngraph_function = moc_pipeline(argv, moc_front_end)
  File "/usr/local/lib/python3.8/dist-packages/openvino/tools/mo/moc_frontend/pipeline.py", line 57, in moc_pipeline
    input_model = moc_front_end.load(argv.input_model, share_weights)
TypeError: load(): incompatible function arguments. The following argument types are supported:
    1. (self: openvino._pyopenvino.FrontEnd, path: object) -> ov::frontend::InputModel

Invoked with: <FrontEnd 'onnx'>, '/data/xxxx/ov_opt_test/movie_rec/20240416/arsenal_ir/model_post.onnx', False
`
