### ISSUE TITLE
ONNX-inference with onnxruntime-gpu

### ISSUE THREAD

**Issue by Birken666** [ultralytics/ultralytics#5093]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict, Other

### Bug

Hi,

I've trained an object detection model and exported it to .onnx using `model.export(format="onnx")`. Running on a NVIDIA® Xavier™ NX, I've installed `onnxruntime-gpu` through [Jetson Zoo](https://elinux.org/Jetson_Zoo#ONNX_Runtime) to allow GPU inference (version 1.12.1 for python 3.8). The install is successful and works for other models, and `onnxruntime.get_device()` returns 'GPU'. However, when running `model = YOLO(model_path, task="detect")`, it immediately says 

> **requirements: ** Ultralytics requirement ['onnxruntime'] not found, attempting AutoUpdate...

It then proceeds to automatically install the cpu version of onnxruntime, so that future calls to `onnxruntime.get_device()` returns 'CPU'... 

It's as if it does not check for the gpu version of the package, which ultimately makes it impossible to use for GPU inference. 

### Environment

Ultralytics YOLOv8.0.186 Python-3.8.13 torch-1.13.0a0+d0d6b1f2.nv22.10 CUDA:0 (Xavier, 6846MiB)
Setup complete (6 CPUs, 6.7 GB RAM, 226.4/233.7 GB disk)

### Minimal Reproducible Example

Have onnxruntime-gpu installed. Load model using 
`model = YOLO(model_path.onnx, task="detect")`.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Birken666 thank you for bringing this to our attention! You are correct in that our current `check_requirements` function is not configured to recognize `onnxruntime-gpu` as a portion of its requirement checks for `onnxruntime`. This can lead to unnecessary attempts to reinstall the CPU version when the GPU version is already installed. 

Your suggested temporary solution to replace `onnxruntime` check with `onnxruntime-gpu`, within `check_requirements`, is indeed a feasible workaround for the current issue. This would allow the function to correctly verify the presence of the GPU version of ONNX Runtime.

However, we also value a long-term solution to broadly address potential similar issues, covering not only `onnxruntime-gpu` but also other GPU-specific packages. Adapting our requirements checker with an insightful update to consider these scenarios will be considered for subsequent updates. 

We appreciate you pointing out this important detail, and encourage open collaboration in improving our models. As we move forward, we'll definitely keep this point in mind. Your contribution is helping us to create an even more robust and versatile YOLOv8 experience for all users.

**Comment by Birken666** [comment]
@glenn-jocher Agreed. A first step might be to replace the AutoInstall with a prompt,
> Ultralytics requirement ['onnxruntime'] not found, do you want to try to autoinstall? [Y/n]

It might be confusing, but it will at least provide the user with a choice in case they know that they already have a gpu-version of a specific package installed. Anyways, appriciate the work!

**Comment by glenn-jocher** [comment]
@Birken666 thank you for your suggestions. We understand the need for greater user autonomy in our software. Replacing the AutoInstall feature with a prompt is indeed a good idea. It will give users better control over their environment and prevent unnecessary or undesired changes, particularly when they are aware they have already installed GPU-specific versions of packages. We will consider this feature for our future updates. Your input about this issue is invaluable as it helps us continuously improve our software. We appreciate your understanding and thanks for using YOLOv8!

**Comment by maxsitt** [comment]
@Birken666 @glenn-jocher I have a similar problem with the same cause. We need to be able to run inference with ONNX models on both GPU and CPU. Installing onnxruntime-gpu is sufficient to enable both. Also mentioned [here](https://natke.github.io/onnxruntime/docs/get-started/with-python.html#install-onnx-runtime) and in this [issue](https://github.com/microsoft/onnxruntime/issues/7313#issuecomment-817456815).

However, with the current requirement checks, onnxruntime is forcefully installed, even is onnxruntime-gpu is already present. This problem also concerns inference with YOLOv5, as `check_requirements` is imported from the ultralytics package.

With previous versions of the ultralytics package this problem did not occur. Until you fix the mentioned problem, it would help if you could tell me the last ultralytics version where onnxruntime-gpu was still checked (not only onnxruntime), so we can use this version until a potential update regarding this issue will be available.

Thanks!

**Comment by glenn-jocher** [comment]
@maxsitt and @UnknownUser, thank you both for sharing your experiences regarding the onnxruntime-gpu and onnxruntime packages. Recognizing that `onnxruntime-gpu` supports both CPU and GPU inference and that the user should have control over their environment setup is fundamental in providing a seamless user experience.

We take these issues seriously and aim to ensure that our software respects the user’s environment. I apologize for any inconvenience the current behavior has caused.

As for the previous behavior of the `check_requirements` functionality, I cannot pinpoint an exact version where the desired behavior was last seen without further review. We typically advise using the latest version of our software for the most up-to-date features and bug fixes. However, to alleviate your current situation, you can resort to using your environment's package manager to manage the ONNX Runtime dependencies directly and ensure proper versions are installed, rather than relying on the `check_requirements` auto-install behavior.

I will raise this with the team to ensure we address it in an upcoming update. Please stay tuned for any changes that might be implemented, and we genuinely appreciate your feedback and patience as we work through this.

In the meantime, utilizing a virtual environment to install `onnxruntime-gpu` and then manually handling the dependency without invoking our `check_requirements` could serve as a temporary solution. If you have already attempted this and it suits your needs, it might be wise to continue with this approach until we deploy a fix.

Again, we value your input, and it plays a pivotal role in our development process. Your understanding is greatly appreciated, and thank you for your ongoing support.

**Comment by linklist2** [comment]
How was this problem solved?

**Comment by glenn-jocher** [comment]
It was addressed by updating `check_requirements` to support interchangeable packages and wiring this into the ONNX backend, so having only `onnxruntime-gpu` installed now satisfies the requirement without forcing a CPU `onnxruntime` install; you can see this in the current [check_requirements reference](https://docs.ultralytics.com/reference/utils/checks/#check_requirements) and the ONNX section of [AutoBackend](https://docs.ultralytics.com/reference/nn/autobackend/), so please upgrade to the latest `ultralytics` and, if you still hit the issue, open a new issue with your `yolo checks` output.

**Comment by ahwxz123** [comment]
> How was this problem solved?

not fixed yet，waiting still...

**Comment by glenn-jocher** [comment]
@ahwxz123 this should be resolved in current `ultralytics`, so if you’re still seeing `onnxruntime` being auto-installed it’s usually an older/duplicate Ultralytics install being imported or a conflicting ONNX Runtime install in the env; on Jetson also make sure you’re using the Jetson-specific `onnxruntime-gpu` wheel (PyPI’s `onnxruntime-gpu` won’t provide `aarch64` binaries), per the [NVIDIA Jetson guide](https://docs.ultralytics.com/guides/nvidia-jetson/).  

```bash
pip uninstall -y onnxruntime onnxruntime-gpu
pip install -U ultralytics
yolo checks
python -c "import onnxruntime as ort; print('ORT:', ort.__version__, 'device:', ort.get_device())"
```

If it still reproduces, please open a new issue (this one is closed/stale) and include the full text traceback plus the `yolo checks` output.
