### ISSUE TITLE
Cannot train from Python with multiple GPUs anymore

### ISSUE THREAD

**Issue by haimat** [ultralytics/ultralytics#5103]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train, Multi-GPU

### Bug

Since the last YOLOv8 update from GitHub I get the following error when I try to train a model from Python:

```python
Traceback (most recent call last):
  File "/data/cvserver/Anvil_Uplink/engines/yolov8.py", line 130, in run
    self.yolo_training()
  File "/data/cvserver/Anvil_Uplink/engines/yolov8.py", line 376, in yolo_training
    model.train(
  File "/data/python/yolov8/ultralytics/engine/model.py", line 337, in train
    self.trainer.train()
  File "/data/python/yolov8/ultralytics/engine/trainer.py", line 190, in train
    raise e
  File "/data/python/yolov8/ultralytics/engine/trainer.py", line 188, in train
    subprocess.run(cmd, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '4', '--master_port', '38875', '/data/cvserver/Anvil_Uplink/start.py']' returned non-zero exit status 1.
```

It seems YOLO tries to call the `torch.distributed.run` module with my own main Python app file `/data/cvserver/Anvil_Uplink/start.py`, which obviously would not work. But I think my code should be correct, I simply call `train()` like this:

```python
from ultralytics import YOLO
model = YOLO()
model.train(data=yaml_config, device="0,1,2,3")
```

This used to work fine. Any ideas what has changed here - or is this a bug in (latest) YOLO?

### Environment

```
Ultralytics YOLOv8.0.188 🚀 Python-3.8.10 torch-1.13.0+cu116 CUDA:0 (NVIDIA RTX A6000, 48677MiB)
Setup complete ✅ (48 CPUs, 251.6 GB RAM, 225.8/877.5 GB disk)

OS                  Linux-5.4.0-155-generic-x86_64-with-glibc2.29
Environment         Linux
Python              3.8.10
Install             pip
RAM                 251.57 GB
CPU                 AMD EPYC 7443 24-Core Processor
CUDA                11.6

matplotlib          ✅ 3.4.3>=3.3.0
numpy               ✅ 1.24.4>=1.22.2
opencv-python       ✅ 4.7.0.68>=4.6.0
pillow              ✅ 9.5.0>=7.1.2
pyyaml              ✅ 5.3.1>=5.3.1
requests            ✅ 2.26.0>=2.23.0
scipy               ✅ 1.8.0>=1.4.1
torch               ✅ 1.13.0+cu116>=1.8.0
torchvision         ✅ 0.14.0+cu116>=0.9.0
tqdm                ✅ 4.64.1>=4.64.0
pandas              ✅ 1.3.4>=1.1.4
seaborn             ✅ 0.11.2>=0.11.0
psutil              ✅ 5.9.1
py-cpuinfo          ✅ 9.0.0
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@haimat 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. DDP training with 8.0.188 works correctly for me:

```python
from ultralytics import YOLO
model = YOLO()
model.train(data='coco8.yaml', batch=2, device=[0,1], epochs=3)
```

<img width="1585" alt="Screenshot 2023-09-27 at 01 34 45" src="https://github.com/ultralytics/ultralytics/assets/26833433/2d3ec40e-92ee-46f3-bb54-665893c32b6d">



We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by glenn-jocher** [comment]
@haimat I just noticed you are on older versions of Python and torch. I'd recommend updating to the latest Python 3.11 with torch 2.0.1. I'd also highly recommend training DDP in our Docker image for maximum compatibility (the tests above are run there). 
https://docs.ultralytics.com/guides/docker-quickstart/

My `yolo checks` environment looks like this and everything works well:

```
Ultralytics YOLOv8.0.188 🚀 Python-3.10.11 torch-2.0.1 CUDA:0 (NVIDIA A100-SXM4-80GB, 81051MiB)
Setup complete ✅ (128 CPUs, 1007.7 GB RAM, 2968.9/3519.3 GB disk)

OS                  Linux-5.15.0-84-generic-x86_64-with-glibc2.31
Environment         Linux
Python              3.10.11
Install             git
RAM                 1007.71 GB
CPU                 AMD EPYC 7502 32-Core Processor
CUDA                11.7

matplotlib          ✅ 3.8.0>=3.3.0
numpy               ✅ 1.23.5>=1.22.2
opencv-python       ✅ 4.8.0.76>=4.6.0
pillow              ✅ 9.4.0>=7.1.2
pyyaml              ✅ 6.0>=5.3.1
requests            ✅ 2.29.0>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.0.1>=1.8.0
torchvision         ✅ 0.15.2>=0.9.0
tqdm                ✅ 4.65.0>=4.64.0
pandas              ✅ 2.1.1>=1.1.4
seaborn             ✅ 0.12.2>=0.11.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 9.0.0

```

**Comment by haimat** [comment]
@glenn-jocher Thanks for your fast response.
You're right, with your minimal example it does work, also for me.
So it is obviously related to my code ...

**Comment by glenn-jocher** [comment]
@haimat that's correct! The problem seems to be specific to your code or environment. I would recommend going through your custom code and verifying if any updates or changes might have affected the multi-GPU training. Additionally, please ensure that all dependencies are correct and up to date. It might also be a good idea to cross-check your code with how multi-GPU training is set up in the minimal example to see if there are any discrepancies. Good luck, and let us know if you have any other questions!

**Comment by haimat** [comment]
@glenn-jocher So it turned out the issue was related to the structure of the Python program we used to initiate the YOLO training. Now we changed it such that we generate a small YOLO trainer.py script, which then calls the `train()` function, and that now works fine with DDP :+1:

**Comment by glenn-jocher** [comment]
@haimat i'm glad to hear you found a solution to the problem! It seems like refactoring your Python program to have a dedicated script for initiating the YOLO training made the difference for DDP. It's always important to ensure scripts and functions are structured in a way that supports the computational requirements of model training. Thanks for letting us know that you resolved your issue, and best of luck with your continued use of YOLOv8!

**Comment by AI-noobie** [comment]
@haimat Hi, I also got this error, but not sure exactly what you mean by generating "a small YOLO trainer.py script, which then calls the train() function".

**Comment by haimat** [comment]
@AI-noobie My main application dynamically creates a minimal trainer script on the fly, that is, this generated script basically does nothing else then initializing the `YOLO` object and calling its `train()` method with all the hyperparams set in the main app ...

**Comment by glenn-jocher** [comment]
@AI-noobie By creating a separate trainer script, @haimat is referring to a new Python file specifically for running the model training. This standalone script essentially initializes the YOLO object and calls the train() function with the appropriate parameters. The main application creates this script dynamically, meaning it's crafted at runtime with the hyperparameters set in the main application. This allows for distributed data parallel (DDP) training to run properly. So, consider structuring your code in a similar way to see if it resolves your issue.

**Comment by xmj-7** [comment]
> @AI-noobie My main application dynamically creates a minimal trainer script on the fly, that is, this generated script basically does nothing else then initializing the `YOLO` object and calling its `train()` method with all the hyperparams set in the main app ...

@haimat  Hello, I have also encountered the same problem. If you could share the small YOLO trainer.py script, I would greatly appreciate it. Thank you！

**Comment by xmj-7** [comment]
> @AI-noobie My main application dynamically creates a minimal trainer script on the fly, that is, this generated script basically does nothing else then initializing the `YOLO` object and calling its `train()` method with all the hyperparams set in the main app ...

@haimat Hello, I have also encountered the same problem. May I ask if you could share your small YOLO trainer.py script? Thank you very much！

**Comment by haimat** [comment]
@xmj-7 Hi, I don't have it at hand, as our main program creates these training scripts dynamically. However, it is really simple, as told before: Just instantiate the `YOLO` object and call the `train()` method using the hyperparams of your choice - that's it :)
