### ISSUE TITLE
Results of yolov8 detection

### ISSUE THREAD

**Issue by coder-glitche** [ultralytics/ultralytics#5121]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hey @glenn-jocher ! Using save_txt=True im able to save class number and cordinates of targets is there a way to modify this text file.contents like i want to write the class name instead of its index thought of using dictionary so it works...

 lets say if there are multiple targets in an image can i write each targets name and its coordinate in separate text file like when i save the crops its saved as img.jpg then img1.jpg and so on similarly for text file can i do same thing...

Also i have 2 detection models running simultaneously the detectected cropped saved images from first model is being fed to the 2nd model for detection what is the best way 2 run both models simultaneously forever on jetson nano again 1st model is loaded and waiting for the drone camera images a watchdog listens and waits for the images so it can be inferenced....

**Comment by glenn-jocher** [comment]
@coder-glitche hello,

Answering your queries in order:

With regards to modifying the content of the text file, you can modify the save_txt function within the detections code. Instead of outputting the class index, you can map each index to its corresponding class name by referring to your dataset's label description. Currently, there isn't a built-in way to write coordinates of each target to a separate text file, but it's definitely something you can implement by modifying the save_txt function to create a new file for each set of coordinates.

As for running two detection models simultaneously, you can consider using threading or multiprocessing in Python to accomplish this task. This would basically involve you running the first model in one thread or process and running the second model in a separate thread or process. However, please note that depending on the resources of your Jetson Nano, this might affect the performance of each model.

Finally, for your setup with the drone camera images, using a watchdog approach is a suitable choice. Having your code watch for new files and then process these images as they come in sounds like an effective way to handle this scenario. Here, you may want to consider using a queue system to manage the incoming images, so you can ensure that each image is processed in the order received and that no image is skipped.

Remember that whenever you modify YOLOv8 code, you should respect the AGPL-3.0 License, which maintains that any modified code must also be open source, contributing to the growth and development of our community.

I hope this information helps! Let me know if you have any further questions.
