### ISSUE TITLE
Can't set save_dir from model.train

### ISSUE THREAD

**Issue by pbouill** [ultralytics/ultralytics#5128]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

seems like the "save_dir" keyword argument is always ignored if not already defined in trainer cfg.

Makes no sense to me.... perhaps good to ignore the override if "save_dir" DOES exist in cfg? As is, it basically means I need to build the trainer outside of the model.train() call...then set it manually?

https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/__init__.py
```python
#  ultralytics.cfg.__init__.py  in get_cfg()
    ....
    # Merge overrides
    if overrides:
        overrides = cfg2dict(overrides)
        if 'save_dir' not in cfg:
            overrides.pop('save_dir', None)  # special override keys to ignore
        check_dict_alignment(cfg, overrides)
        cfg = {**cfg, **overrides}  # merge cfg and overrides dicts (prefer overrides)
        ...
```

maybe change to:
```python
if 'save_dir' in cfg:
    overides.pop('save_dir', None)
...
```

otherwise, just allow overriding the save dir like all other cfg? (no special case?)

maybe I'm missing something :)

### Environment

```
Ultralytics YOLOv8.0.188  Python-3.11.5 torch-2.0.1+cu117 CUDA:0 (Quadro T2000 with Max-Q Design, 4096MiB)
Setup complete  (12 CPUs, 31.3 GB RAM, 391.7/474.8 GB disk)
```

### Minimal Reproducible Example

```python
from ultralytics import YOLO

model = YOLO()
model.train(save_dir='my_save_dir', project='1')
```
...then train outputs go to "1" rather than "my_save_dir/1"

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@pbouill thank you for bringing this to our attention and for being ready to help with a pull request!

Your observation about the 'save_dir' key behavior is absolutely correct. The current implementation would ignore the 'save_dir' key in the overrides when it's not present in the configuration. This is designed like this to ensure that there isn't an accidental overwrite of the 'save_dir' when it's not specified explicitly in the configuration. 

However, you have a point. It would be more intuitive and flexible for users if they can specify the 'save_dir' directly in the `model.train()` method, without having to deal with it in the configuration.

Please do submit a PR, and we will gladly review it. Your contribution could make the Ultralytics YOLOv8 environment more user-friendly, and we appreciate your initiative. If you encounter any troubles during your process, please don't hesitate to reach out for support.

**Comment by glenn-jocher** [comment]
@pbouill note also that save_dir is not a valid train argument. You should instead use `project` and `name` to create save_dir = project/name. See https://docs.ultralytics.com/modes/train/#arguments

**Comment by glenn-jocher** [comment]
@pbouill thank you for the feedback and the pull request you have already made. 

Just to clarify, in the current design of YOLOv8, the "save_dir" is being assembled from "project" and "name". Thus, by adjusting these parameters you can control where your outputs will go. 

The reason why "save_dir" itself isn't directly controllable is due to a design decision made to prevent accidental overwriting of important directories. 

Your use case is understandable though. We will review your proposed change to see if it could be a worthwhile addition to the YOLOv8 functionalities. In the meantime, using a custom trainer as you've shown is a reasonable solution.

Regarding setting "save_dir" in the model configuration, as mentioned above, the direct manipulation of "save_dir" isn't supported currently, thus, the suggested model.cfg['save_dir'] = 'my_save_dir' will not work. Instead, you should adjust the "project" and "name" values to influence "save_dir". 

Thank you again for your participation in improving YOLOv8. Your contributions are deeply appreciated!
