### ISSUE TITLE
How to train yolov5 through ultralytics(yolov8) library?

### ISSUE THREAD

**Issue by zfli-xdu** [ultralytics/ultralytics#5132]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi~ I want to do some comparison experiments between yolov5 and yolov8. I'm wondering if it is supported to train yolov5 through the Ultralytics library. 

There are differences in hyperparameters between yolov5 and yolov8. If I directly clone the hyperparameter settings from yolov5 into the yolov8 cfg file and run the training, I get the following error:

`Traceback (most recent call last):
  File "/home/zfli/miniconda3/envs/pt201/bin/yolo", line 33, in <module>
    sys.exit(load_entry_point('ultralytics', 'console_scripts', 'yolo')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zfli/ultralytics/ultralytics/cfg/__init__.py", line 385, in entrypoint
    check_dict_alignment(full_args_dict, overrides)
  File "/home/zfli/ultralytics/ultralytics/cfg/__init__.py", line 202, in check_dict_alignment
    raise SyntaxError(string + CLI_HELP_MSG) from e
SyntaxError: 'anchors' is not a valid YOLO argument. 
'fl_gamma' is not a valid YOLO argument. 
'obj' is not a valid YOLO argument. Similar arguments are i.e. ['kobj=1.0'].
'iou_t' is not a valid YOLO argument. Similar arguments are i.e. ['iou=0.7'].
'cls_pw' is not a valid YOLO argument. Similar arguments are i.e. ['cls=0.5'].
'anchor_t' is not a valid YOLO argument. 
'obj_pw' is not a valid YOLO argument. Similar arguments are i.e. ['kobj=1.0'].`

Besides, I checked the code and didn't see any loss implementation in Ultralytics related to yolov5. Are there any solutions to this?

**Comment by glenn-jocher** [comment]
@zfli-xdu hello,

Contrary to your question, YOLOv8 cannot be directly used to train YOLOv5 as they are distinct versions with differing underlying structures, loss functions, and hyperparameters. The error message you received is due to mismatched parameters that are not compatible with YOLOv8. Variants of YOLO have different hyperparameters and architecture definitions. Directly cloning the hyperparameters from YOLOv5 to YOLOv8 is unfortunately not supported.

Regarding the loss function, YOLOv5 and YOLOv8 utilize different loss functions, so you won't find YOLOv5's loss function in the YOLOv8 repository. Every version of YOLO has been developed with different design enhancements aiming for more accuracy and efficiency, hence the implementation of their loss functions is also different.

However, you can certainly train both YOLOv5 and YOLOv8 sequentially or in parallel using the Ultralytics library and perform a comparison experiment between the two versions.

As for YOLOv8 training, it can be performed using the Ultralytics framework with the configuration files and parameters suitable for YOLOv8. Polish the configurations as per YOLOv8 requirements and run the training with the appropriate datasets.

Let me know if you have further questions, happy to help!

**Comment by zfli-xdu** [comment]
> @zfli-xdu hello,
> 
> Contrary to your question, YOLOv8 cannot be directly used to train YOLOv5 as they are distinct versions with differing underlying structures, loss functions, and hyperparameters. The error message you received is due to mismatched parameters that are not compatible with YOLOv8. Variants of YOLO have different hyperparameters and architecture definitions. Directly cloning the hyperparameters from YOLOv5 to YOLOv8 is unfortunately not supported.
> 
> Regarding the loss function, YOLOv5 and YOLOv8 utilize different loss functions, so you won't find YOLOv5's loss function in the YOLOv8 repository. Every version of YOLO has been developed with different design enhancements aiming for more accuracy and efficiency, hence the implementation of their loss functions is also different.
> 
> However, you can certainly train both YOLOv5 and YOLOv8 sequentially or in parallel using the Ultralytics library and perform a comparison experiment between the two versions.
> 
> As for YOLOv8 training, it can be performed using the Ultralytics framework with the configuration files and parameters suitable for YOLOv8. Polish the configurations as per YOLOv8 requirements and run the training with the appropriate datasets.
> 
> Let me know if you have further questions, happy to help!

Thank you for your reply. I will try to train yolov5 and yolov8 separately. Looking forward to the ongoing enhancement of the Ultralytics library.

**Comment by glenn-jocher** [comment]
You're welcome @zfli-xdu! Your approach to train YOLOv8 separately sounds like a good plan. We're continually working on enhancing the Ultralytics library and appreciate your support and patience. Please don't hesitate to reach out if you have any further questions or issues. I wish you the best in your comparison experiments - I'm sure the outcomes will be insightful. Good luck!
