### ISSUE TITLE
On onnxruntime-gpu, CUDAProvider, Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance

### ISSUE THREAD

**Issue by narugo1992** [ultralytics/ultralytics#5147]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict, Export

### Bug

It says `[W:onnxruntime:, session_state.cc:1162 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.` when running on onnxruntime-gpu's CUDAProvider.

Our exported onnx model is here: https://huggingface.co/deepghs/anime_person_detection/blob/main/person_detect_v1.1_m/model.onnx

It's original model: https://huggingface.co/deepghs/anime_person_detection/blob/main/person_detect_v1.1_m/model.pt

All ONNX models of YOLOv8 exported by us will encounter this issue.

This issue has a significant impact on our practical use, as the inference speed remains very slow even in CUDA-enabled environments (only slightly faster than CPU). We are certain that our operating environment is not the problem. Meanwhile, other ONNX models created in exactly the same way using the same approach can use CUDA and achieve faster speeds in session.

### Environment

Ultralytics YOLOv8.0.20 🚀 Python-3.8.18 torch-1.13.1+cu117 CUDA:0 (NVIDIA RTX A5000, 24256MiB)
Setup complete ✅ (128 CPUs, 755.3 GB RAM, 25.4/30.0 GB disk)

(This `yolo checks` command was executed in the environment used for training the aforementioned model at that time.)

### Minimal Reproducible Example

The abovementioned model has been integrated in our library: https://github.com/deepghs/imgutils

You can use it like this

```python
from imgutils.detect import detect_person                                                                                                                                                              
detect_person('/nfs3/yukata.png')
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@narugo1992 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. For me it seems like I can't run ONNX inference with onnxruntime-gpu, as I get an AutoUpdate for onnxruntime instead. 

I do not see any warnings such as what you mentioned though.

<img width="1355" alt="Screenshot 2023-09-29 at 00 59 22" src="https://github.com/ultralytics/ultralytics/assets/26833433/8f31b328-871e-4a1f-b182-68f626ec97f9">

**Comment by narugo1992** [comment]
This is the code I used for exporting the onnx: https://github.com/deepghs/yolov8/blob/main/yolov8/onnx.py

Just replace the `os.path.join(workdir, 'weights', 'best.pt')` to another .pt file is okay.

**Comment by glenn-jocher** [comment]
Hi @narugo1992,

Your code and approach look generally fine to me. The issue can probably be related to how ONNX Runtime is optimizing the execution graph. In your `_open_onnx_model(..)`, you enabled all optimization levels. This allows ONNX Runtime to implicitly force compute nodes to run on the CPU if it believes that would lead to better performance. This is also probably why you see the warning message about 'Some nodes were not assigned to the preferred execution providers...'.

To verify this, you can try to lower `options.graph_optimization_level` all the way down to `GraphOptimizationLevel.ORT_ENABLE_BASIC` and see if that changes anything in regards to the number of nodes assigned to the GPU.

Also, you might want to check the versions of the relevant libraries (like ONNX and ONNX Runtime) as differences in versions might also affect optimization levels and choices. In general, ensure you export the ONNX model under the same environment/versions as when you do the inference.

Furthermore, the way Ultralytics creates ONNX Runtime session differs slightly from your approach, especially regarding setting up CUDA execution providers with external CUDA allocator, which your code does not. This could affect the memory management between GPU and CPU and may potentially lead to performance degradation.

I hope these suggestions will help you troubleshoot the issue. Feel free to update the thread if you have any further questions or findings.

**Comment by narugo1992** [comment]
@glenn-jocher Hey there!

I found the issue. When I create an ONNX session and use both CUDAExecutionProvider and CPUExecutionProvider, this warning disappears. :smiling_face_with_tear: 

But if CPUExecutionProvider is not added, these warnings appear again.

**Comment by glenn-jocher** [comment]
Hi @narugo1992,

I'm glad that you've found a solution! When creating an ONNX session, specifying both CUDAExecutionProvider and CPUExecutionProvider allows ONNX Runtime to decide the best execution provider to use for each node of the computation graph, depending on the specific operation and the optimization strategy.

If only CUDAExecutionProvider is specified and some operations are not supported or not efficient on the GPU, ONNX Runtime may still decide to run these operations on the CPU, hence the warnings. Including the CPUExecutionProvider gives ONNX Runtime explicit permission to run certain nodes on the CPU if it deems that more beneficial, thereby preventing these warnings.

Thank you for your update and happy coding with YOLOv8!

**Comment by surajrao2003** [comment]
@glenn-jocher @narugo1992 Hey there!
So I have been facing a similar kind of issue when I am trying to inference using a dynamically quantized yolov8s onnx model. 
I have used yolov8s.pt and exported it to yolov8.onnx using onnx export. Then I quantized the onnx model using dynamic quantization (uint8) method provided by onnxruntime which reduced the model size by around 4 times. Though the quantized model worked fine while inferencing on CPU (CPUExecutionProvider), it gives low fps (frames per sec) while inferencing on GPU using CUDAExecutionProvider. 

Mentioning both providers CUDAExecutionProvider and CPUExecutionProvider does make the warnings disappear but what I am concerned is about why some nodes are forcefully being executed on the CPU and not CUDA? Is it because CUDA does not yet provide support for such quantized nodes or is there any other particular reason for it?

![errorimg](https://github.com/ultralytics/ultralytics/assets/78335706/bad0b25b-e57a-4166-9952-eb88deb686c6)


When checked using log.severity, got this information

`import onnxruntime as ort`
`ort.set_default_logger_severity(1)`

![1712056751349](https://github.com/ultralytics/ultralytics/assets/78335706/968c3ff7-c860-4937-91cf-17d356728c0c)

![1712056771053](https://github.com/ultralytics/ultralytics/assets/78335706/2fc8ccae-9dd4-4d44-ad90-6c3993475108)

I am curious about why CUDA is not able to handle these nodes? Because in my opinion it is very unusual to see GPU inference giving a lower fps as compared to CPU inference. Is there any solution to run all the nodes exclusively on CUDA?

**Comment by glenn-jocher** [comment]
Hey @surajrao2003! 🙌

Thanks for reaching out with such detailed observations! When it comes to dynamically quantized ONNX models, especially after applying uint8 dynamic quantization, it's quite common to see some operations not being fully supported or optimized for CUDA. This usually results in parts of the model execution being offloaded back to the CPU, hence the lower performance on GPU in certain situations.

ONNX Runtime and CUDA have continuously evolved, but full support and optimization for all types of quantized operations on CUDA are still catching up. The discrepancy you're seeing is likely due to this current limitation. CUDA primarily excels at floating-point operations, and quantized models introduce int or uint operations, which might not be as efficiently executed on the GPU.

For the moment, ensuring that both CUDAExecutionProvider and CPUExecutionProvider are listed allows ONNX Runtime the flexibility to execute the model as efficiently as possible given the current constraints. 

```python
providers = ["CUDAExecutionProvider", "CPUExecutionProvider"]
sess_options = ort.SessionOptions()
sess = ort.InferenceSession("model.onnx", sess_options, providers=providers)
```

This approach maximizes performance given the current mix of supported and unsupported operations for CUDA. As ONNX Runtime and CUDA continue to improve, we hope to see more comprehensive support for quantized operations which should further enhance GPU performance.

Stay tuned for updates and feel free to share any further findings or questions you may have! Happy coding! 🚀

**Comment by surajrao2003** [comment]
Hey @glenn-jocher, thank you very much for the detailed response. 

As you have mentioned CUDA primarily excels at floating-point operations, when I tried to perform inference using a float-16 converted model (almost half the size of the original model), it worked perfectly fine on both CPU and GPU and gave the expected results. The issue popped up only in the case of int or uint operations while using the dynamically quantized model. 

So based on your response and my observations, the issue is due to the limitations of ONNX runtime support for quantized operations (int) on CUDA.

Thank you and I appreciate your work for the community.

**Comment by glenn-jocher** [comment]
Hey there! 😊

You're spot on with your understanding! The observed behavior with float-16 models performing well across both CPU and GPU aligns perfectly with CUDA's strengths in handling floating-point operations efficiently. As for the challenges faced with int or uint operations in dynamically quantized models, it indeed boils down to the current ONNX Runtime support for such operations on CUDA.

I'm glad the response helped clarify things. Your experiments and feedback are invaluable, and it's this kind of community engagement that drives us forward. Keep exploring and sharing your insights!

Thank you for your kind words and support for the community! 👍

**Comment by glenn-jocher** [comment]
Hey there! 😊

In the context of Onnxruntime with Rust, when you specify the CUDA provider, the CPU provider isn't automatically listed or included by default. You'll typically need to explicitly specify all the providers you want to use in order of preference.

Here's a quick example of how you might set this up in Rust:

```rust
use onnxruntime::env::Environment;
use onnxruntime::session::{Session, SessionOptions};

let environment = Environment::builder().with_name("test").build()?;
let mut session_options = SessionOptions::default();
session_options.add_cuda();
session_options.add_cpu(true); // Explicitly adding CPU as an execution provider

let session = environment.new_session_builder(&session_options)?.with_model_from_file("your_model.onnx")?;
```

This ensures that both CUDA and CPU execution providers are considered during inference. Hope this helps! Let me know if you have any more questions.

**Comment by callanoc** [comment]
Thanks a lot! 🤗

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions or need further assistance, feel free to reach out. Happy coding! 🚀

**Comment by Petros626** [comment]
@surajrao2003 Hey, how to solve this?

![Image](https://github.com/user-attachments/assets/bb4341d5-b63a-4c9d-8ee6-f3f7554f61ad)

**Comment by surajrao2003** [comment]
> [@surajrao2003](https://github.com/surajrao2003) Hey, how to solve this?
> 
> ![Image](https://github.com/user-attachments/assets/bb4341d5-b63a-4c9d-8ee6-f3f7554f61ad)

It looks like the issue is due to a version mismatch between cuDNN and CUDA, leading to the missing library file (libcudnn_adv.so.9) (as stated). This is likely not a problem with the code itself but rather with the environment configuration. Did you ensure the right versions of cudnn and cuda are installed? 
If not, try doing it once as per your requirements and reinstall ONNX Runtime with the correct CUDA version.

**Comment by Petros626** [comment]
I don't understand why two different `CUDA` versions are required, when you can set only once `PATH` and `LIBRARY_PATH` in `bashrc`. I got following version:
```txt
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Feb__7_19:32:13_PST_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0
```

**Comment by glenn-jocher** [comment]
Hi @Petros626 👋, 

The error typically occurs when there's a mismatch between CUDA, cuDNN, and ONNX Runtime versions. Your CUDA 12.1 installation likely requires cuDNN ≥9.x, but ONNX Runtime might be expecting cuDNN 8.x. For CUDA 12.1, we recommend using cuDNN 9.1.0+ and rebuilding ONNX Runtime with matching versions. 

Check our [YOLO Common Issues guide](https://docs.ultralytics.com/guides/yolo-common-issues/#running-yolo11-on-gpu) for CUDA/cuDNN compatibility tips. Let us know if you need more help! 😊

**Comment by Petros626** [comment]
Common issues doesn' cover this type of issue, but I'll try with `cuDNN` 9.1.0+

**Comment by glenn-jocher** [comment]
Hi there! 👋 The error typically occurs due to a cuDNN-CUDA version mismatch. For CUDA 12.1, we recommend cuDNN ≥9.1.0 and rebuilding ONNX Runtime with matching versions. Ensure your `LD_LIBRARY_PATH` includes the cuDNN library location. For detailed compatibility guidance, see our [YOLO Common Issues](https://docs.ultralytics.com/guides/yolo-common-issues/#running-yolo11-on-gpu) guide. Let us know if you need more help! 😊
