### ISSUE TITLE
Training Yolov8 on more than 3 channels (Hyperspectral data with 300 channels of each image)

### ISSUE THREAD

**Issue by snehitvaddi** [ultralytics/ultralytics#5151]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am also trying to train a Yolov8 model on a dataset with images having more than 3 channels. 
I have a Hyperspectral dataset (each image has 300 channels).
I have seen some discussion at @issues/2154 but the thread lead no working solution.

**Comment by glenn-jocher** [comment]
@snehitvaddi thank you for your question.

Training YOLOv8 on a hyperspectral dataset with more than 3 channels is a quite unique use-case. This requires a significant alteration in the code to accommodate for a larger number of input channels.

Generally, the convolutional layers at the beginning of the model need to be modified to account for the increased channels. The configuration file may also require adjustment to match these changes, ensuring the initial layers are expecting the correct number of input channels.

Since YOLO is a specific architecture designed with RGB images in mind, there may be other considerations or challenges when trying to train it on a different type of data like hyperspectral images.

It's also worth noting that the increase in the number of channels will likely affect resource requirements (like GPU memory), since the model will be processing significantly more data.

This is a complex task and not directly supported as a feature in the YOLOv8 codebase. Community contributions and investigations in this area are welcome and appreciated. It would be exciting to see your progress and findings on this task, so feel free to share them once available.

Good luck with your project!

**Comment by getupearly11** [comment]
hello.I also want to improve YOLOV8 to achieve target detection in hyperspectral images. Do you have any progress？Thank you

**Comment by glenn-jocher** [comment]
@getupearly11 hello. Training YOLOv8 on hyperspectral images requires modifying the initial layers to handle more channels. This is a complex task and not directly supported, but community contributions are welcome. Good luck with your project!

**Comment by Amine-Torki** [comment]
Hello I'd also like to use hyperspectral images, any recommandations on how to implement that with YOLO ? I've been using YOLOv11 with only the first 3 channels and had good performance, I want to add my other channels for better performances.

**Comment by Y-T-G** [comment]
Duplicate of https://github.com/ultralytics/ultralytics/issues/6929
