### ISSUE TITLE
The tracker assigns  new ids every time when using real-time webcam

### ISSUE THREAD

**Issue by Rak-r** [ultralytics/ultralytics#5154]
I am new to YOLOv8 and following the provided docs. The problem I am facing is whenever I run the tracker with persist = True, everythings starts normally but when I leave the frame and comes back in newid is assigned.

`from ultralytics import YOLO
 model = YOLO('yolov8s.pt')
model.track(source=0, persist=True, show= True)`

I haven't trained the model on my own dataset. Also I tried to run with opencv to run camera feed but still same.
It seems the persist isn't executing.
Could anybody advice where am I missing?

**Comment by RizwanMunawar** [comment]
@Rak-r, welcome to the YOLOv8 community! 😊

Regarding your inquiry, the `persist==True` argument informs the tracker that the current image or frame is part of an ongoing sequence, and it should expect to continue tracking objects from the previous frame. However, if an object is temporarily obstructed in front of the webcam and the tracker is already tracking it when the same object reappears, the tracker may or will assign a new ID. This behavior aligns with the tracker's primary purpose, which is to continually track objects.

#### Note
If your goal is to retain the same ID for an object that temporarily disappears and reappears, you may need to explore the integration of reidentification techniques to achieve this.

Thanks

**Comment by Rak-r** [comment]
Thanks for the early response.

From what I understood is if an object with id 1,goes out of frame and then reappears in the current frame, the persist arguement will let the tracker know that its the same object? 

Re-identification is done using persist = True right?

**Comment by RizwanMunawar** [comment]
@Rak-r, reidentification functionality is not explicitly integrated into the object tracking module. However, it's worth noting that in certain scenarios, the object tracking module may perform reidentifications as part of its tracking process.

Thanks

**Comment by Rak-r** [comment]
Ok.Thanks for the explaination. Could you share a bit of an example on how should i approach this?

**Comment by RizwanMunawar** [comment]
@Rak-r, you can use the mentioned code to perform object detection using YOLOv8. Later, you can use the bounding box data with any tracking algorithm and embed the object reidentification algorithm with that.

```python
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO('yolov8n.pt')

# Perform inference on an image
results = model('https://ultralytics.com/images/bus.jpg')

# Extract bounding boxes, classes, names, and confidences
boxes = results[0].boxes.xyxy.tolist()
classes = results[0].boxes.cls.tolist()
names = results[0].names
confidences = results[0].boxes.conf.tolist()

# Iterate through the results
for box, cls, conf in zip(boxes, classes, confidences):
    x1, y1, x2, y2 = box
    confidence = conf
    detected_class = cls
    name = names[int(cls)]
``` 

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by Rak-r** [comment]
Thanks for providing the example. However, I am able to extract the information on a camera feed (webcam) and even I tried it with intel realsense depth camera and it is able to detect me as person and other classes as well. 
However, I am facing some issues with object re-identification algorithm as I am not much familiar with it. I set the reid configuration = True in botsort but still the same.

Do I have to train the yolov8 on a dataset and then try re-identification? I dont think this is the issue as I am using pretrained and it is detecting me as a person which is right.

**Comment by glenn-jocher** [comment]
@Rak-r in YOLOv8, the object tracking is mainly about tracking the same object across the different frames in a video stream. This is achieved through the bounding box information provided by YOLOv8's detector. When YOLOv8 tracks an object from one frame to the next, it matches detected objects in the current frame with those in the previous frame based on the proximity of their bounding boxes and then assigns ids accordingly.

However, the object re-identification involves recognizing an instance over different non-overlapping camera views or after a long period of time. This is a challenge that even YOLOv8 doesn't handle explicitly. For that, you might need a specialized object re-identification algorithm that often utilize deep learning techniques to extract robust features which can handle changes in object appearance. 

Regarding your question, setting reid to True in a YOLOv8 context doesn't imply the use of an object re-identification algorithm, but suggests that the tracking algorithm should keep track of the object even if it disappears and reappears from the frame. Still, it doesn't guarantee the perfect result as it doesn't consider the change of appearances or long period disappearances in a complex video stream.

You might have to look into object re-identification algorithms and systems to learn more about how they work and how you can integrate them with your object detection results.

**Comment by Rak-r** [comment]
> @Rak-r in YOLOv8, the object tracking is mainly about tracking the same object across the different frames in a video stream. This is achieved through the bounding box information provided by YOLOv8's detector. When YOLOv8 tracks an object from one frame to the next, it matches detected objects in the current frame with those in the previous frame based on the proximity of their bounding boxes and then assigns ids accordingly.

> Regarding your question, setting reid to True in a YOLOv8 context doesn't imply the use of an object re-identification algorithm, but suggests that the tracking algorithm should keep track of the object even if it disappears and reappears from the frame. Still, it doesn't guarantee the perfect result as it doesn't consider the change of appearances or long period disappearances in a complex video stream.
> @glenn-jocher What I want is this only that tracking should keep track of the object if it disappears and reappears from the previous frame. How to encounter this issue?

**Comment by Rak-r** [comment]
My code for object detection with intel realsense which seems t work ok but when I change to `model.track(color_frame, stream = True, persist = True) it's struggling to keep track of me and assigning new id. Now, I am getting a bit confused where am I going wrong.

`import pyrealsense2 as rs
import numpy as np
import cv2
from ultralytics import YOLO

# Initialize the YOLOv8 model
model = YOLO('yolov8s.pt')

# Initialize the RealSense camera pipeline
ctx = rs.context()
serials = []
devices = ctx.query_devices()
for dev in devices:
    dev.hardware_reset()

if len(ctx.devices) > 0:
    for dev in ctx.devices:
        print('Found device:', dev.get_info(rs.camera_info.name), dev.get_info(rs.camera_info.serial_number))
        serials.append(dev.get_info(rs.camera_info.serial_number))
else:
    print("No Intel Device connected")

pipelines = []
windows = []

for serial in serials:
    pipe = rs.pipeline(ctx)
    cfg = rs.config()
    cfg.enable_device(serial)
    cfg.enable_stream(rs.stream.depth, 640, 480, rs.format.z16, 30)
    cfg.enable_stream(rs.stream.color, 640, 480, rs.format.bgr8, 30)
    pipe.start(cfg)
    pipelines.append(pipe)

    window_name = f"Camera {serial}"
    cv2.namedWindow(window_name, cv2.WINDOW_NORMAL)
    windows.append(window_name)

try:
    while True:
        for pipe, window_name in zip(pipelines, windows):
            frames = pipe.wait_for_frames()
            depth_frame = frames.get_depth_frame()
            color_frame = frames.get_color_frame()
            if not depth_frame or not color_frame:
                continue

            depth_image = np.asanyarray(depth_frame.get_data())
            color_image = np.asanyarray(color_frame.get_data())

            depth_colormap = cv2.applyColorMap(cv2.convertScaleAbs(depth_image, alpha=0.5), cv2.COLORMAP_JET)

            # Run YOLOv8 inference on the color frame
            results = model(color_image)

            # Visualize the YOLOv8 results on the color frame
            annotated_frame = results[0].plot()

            # Display the color frame with YOLOv8 annotations
            cv2.imshow(window_name, annotated_frame)
            cv2.imshow(window_name + " Depth", depth_colormap)

        key = cv2.waitKey(1)
        if key == 27:  # ESC key
            break

finally:
    for pipe in pipelines:
        pipe.stop()

    cv2.destroyAllWindows()`

**Comment by glenn-jocher** [comment]
@Rak-r let's first clarify that the 'persist = True' argument in the 'model.track()' function doesn't implement re-identification. Its purpose is to signal the function that object detection and tracking should continue across multiple consecutive frames. The function assigns IDs to detected objects and attempts to persist those IDs from one frame to the next, based on the proximity of bounding boxes.

That being said, the behavior you're observing, where the function assigns a new ID to you when you re-enter the frame, is expected. When the tracked object (you, in this case) exits and re-enters the frame, the tracker has no way to know that the re-entering object is the same as the one that exited, so it assigns a new ID.

If your goal is to maintain the same ID for an object that leaves and then re-enters the frame, this requires a re-identification step, which the current 'model.track()' function does not support. You would need to explore other computer vision techniques or libraries that specifically support this feature. They often use deep learning-based or appearance-based methods to "remember" the features of tracked objects and re-identify them when they reappear. These methods go beyond the basic bounding box matching that 'model.track()' uses and may require additional computational resources.

**Comment by Decclo** [comment]
To summarize what @glenn-jocher has said so far:

- The problem at hand is that the object is either obscured at any point, or that the object has no overlap, and the tracker therefore cannot perform IOU.
- All default trackers require IOU, and WILL NOT work if there is no overlap or object is obscured.
- To fix this, one should implement either re-identification for obscured objects, or something like Euclidean distance instead of IOU for fast moving objects with no overlap. This can be done in conjunction with using the default tracker.

THERE IS CURRENTLY NO OPTION IN ULTRALYTICS THAT WILL CONVENIENTLY SOLVE OUR PROBLEM.


With all that out of the way, @glenn-jocher , I'm also stuck at this problem. I'm trying to track a small, fast-moving ball that does not have any overlap once in motion. Furthermore, obscurance will likely also be an issue further down the line.

I'm mainly looking into 3 possible solutions:

1.  Identify a non-default tracker that can perform re-identification and preferably implements any kind of Euclidean distancing and Kalmann filtering.
2. Inherit from the BYTETracker tracker class, and change the `dist()` function to implement Euclidean over IOU.
3. Build my own makeshift tracker until I find a better solution.

To this purpose, I would be thankful if anyone could answer some questions that I could not properly find any information about in the Docs:

Regarding solution 1: Do there exist any Ultralytics and YOLO compatible trackers which already implement this. You mentioned deepsort. And how would one go about implementing the tracker, is there an easy solution such as using the `custom_tracker.yaml`-file? Or do we need to feed the results into deepsort (or any other third-party tracker) manually?

Regarding solution 2: I've made a sample class which inherits from `BYTETracker`, and am currently trying to figure out how to have the model use my modified tracker instead of the default one, is this possible without having to feed the results structure into the tracker manually, and could you perhaps give an example on how to do it manually if not?

Regarding solution 3: The results structure is very nice, is there any way of not only reading from it, but also writing to it, such as updating the ID in boxes?

Thank you very much for your patience, and please excuse all the questions.

**Comment by glenn-jocher** [comment]
@Decclo hello,

Based on what you've summarized and your current predicaments, here are some possible insights:

1. Regarding the usage of non-default trackers like DeepSORT, while there might not be a built-in way to use these within the Ultralytics YOLO model, you could potentially extract the bounding box and confidence information from the YOLOv8 predictions and feed it into the DeepSORT or any other third-party tracker manually. Unfortunately, it might be less straightforward than just adjusting a setting in a `custom_tracker.yaml` file.

2. For modifying the `dist()` function in the `BYTETracker` class, this is certainly a possible approach. However, altering this to use Euclidean distance instead of Intersection Over Union might affect the tracking performance, and thorough testing would be necessary. Once you have your modified tracker class, you can instantiate your model with your new tracker class instead of the default one. 

3. In terms of writing to the results structure, YOLOv8 results are generally returned as tensor, where the ID and bounding box information are included. While the details for changing the values within the tensor (like altering the ID) could vary, you could directly manipulate these tensors like any other PyTorch tensor. However, remember that altering these values after the fact wouldn't influence the tracking behavior of the model as the tracking is already done based on the original IDs assigned initially.

However, do note that as this repo currently does not inherently provide a mechanism that incorporates re-identification or Euclidean based tracking as you pointed out. So, the solutions may require extensive modification of the existing codebase and could be non-trivial to implement. However, they certainly seem possible based on the understanding of the tracking process in Ultralytics YOLOv8.

Hope this helps!

**Comment by glenn-jocher** [comment]
Thank you for sharing your process and your workaround, @Decclo. Your initiative of using the `deep-sort-realtime` package as an intermediary to translate between YOLOv8's tensor outputs and DeepSort's requirements is clever.

Your `Custom_DeepSort_Tracker` class indeed streamlines the adoption of DeepSort by handling the necessary tensor transformations. Just to unpack it a bit for others who might want to adapt your process:
- In your `Custom_DeepSORT_Tracker` class, the `update_tracker` method iterates through the detections produced by YOLOv8. 
- For each detection, it extracts the bounding box (box), confidence (conf), and class (classes) information and packages them into a tuple of `(box, conf, classes)` you refer to as a bounding box (bb).
- It accumulates each bounding box into a list of bounding boxes (bbs). 
- These bbs are then fed into the DeepSort tracker's `update_tracks()` method to generate track information.

Importantly, if any users adopt this process, they should take care to ensure that the `frame` argument passed to the `update_tracks` function correctly corresponds to the image from which the detections were made. 

As for the information that the generated tracks hold, users can extract the top-left width/height (ltwh) values, detection confidence, detection class, and track ID for each track by using `track.to_ltwh()`, `track.det_conf`, `track.det_class` and `track.track_id` methods respectively.

Thank you again, @Decclo, for sharing how you integrated DeepSort with the YOLOv8 model. Your contribution could save much effort for users who need to incorporate third-party tracking algorithms.

**Comment by pmmckay** [comment]
when using the yolo tracker, Is there a way to run some python code when a new ID is assigned?  With persist=True, are IDs ever unassigned and if so, when and is there any way to run a program when that happens?

**Comment by glenn-jocher** [comment]
Hello!

Great questions! When using the YOLO tracker with `persist=True`, new IDs are assigned to objects as they are detected. Currently, there isn't a built-in feature in the Ultralytics YOLO framework to trigger Python code directly upon ID assignment or unassignment. However, you can achieve this by modifying the tracking code to include callback functions or event triggers when these events occur.

IDs are typically "unassigned" or discontinued when the object they are tracking is no longer detected in subsequent frames, often due to the object leaving the field of view or becoming occluded. To run code when an ID is unassigned, you would need to monitor the list of active IDs and check for IDs that disappear between frames.

Implementing these features would require some custom coding on your part. You might consider wrapping the tracking updates in a function that checks for ID changes and triggers your custom code accordingly.

Hope this helps! Let us know if you have any more questions. 😊

**Comment by UltralyticsAssistant** [comment]
A potential fix for this issue has just been merged in https://github.com/ultralytics/ultralytics/pull/20192. This update introduces Re-Identification (ReID) support to the BoT-SORT tracker, enabling it to more reliably track objects—even those that look similar or temporarily leave and re-enter the frame. Key improvements include a new ReID module using YOLO models for appearance-based object matching, enhancements to the botsort.yaml config for ReID options, and updates to the detection pipeline for feature extraction.

Special thanks to the PR author and contributors for their work on this feature!

To test whether this resolves your issue, you can upgrade to the latest version with:

```
pip install -U ultralytics>=8.3.114
```

Alternatively, you can install directly from the main branch with:

```
pip install git+https://github.com/ultralytics/ultralytics.git@main
```

Or, feel free to wait for the next official PyPI release.

Please let us know if these changes address your issue, or if you encounter any further problems. Thank you for reporting this and helping improve Ultralytics!

**Comment by glenn-jocher** [comment]
@pmmay Currently, there isn't a direct callback mechanism in the YOLO tracker that triggers when new IDs are assigned or unassigned. However, you can implement this functionality yourself by tracking the IDs from frame to frame.

Here's a simple approach you could use:

```python
from ultralytics import YOLO
import cv2

# Load model
model = YOLO('yolo11n.pt')

# Initialize camera
cap = cv2.VideoCapture(0)

# Keep track of previous frame IDs
previous_ids = set()

while cap.isOpened():
    success, frame = cap.read()
    if success:
        # Run tracking with persistence
        results = model.track(frame, persist=True)
        
        if results[0].boxes.id is not None:
            # Get current IDs
            current_ids = set(results[0].boxes.id.int().cpu().tolist())
            
            # Check for new IDs
            new_ids = current_ids - previous_ids
            if new_ids:
                print(f"New IDs assigned: {new_ids}")
                # Your custom code here for new ID assignment
            
            # Check for disappeared IDs
            disappeared_ids = previous_ids - current_ids
            if disappeared_ids:
                print(f"IDs unassigned: {disappeared_ids}")
                # Your custom code here for ID unassignment
            
            # Update previous_ids for next iteration
            previous_ids = current_ids
        
        # Display the results
        annotated_frame = results[0].plot()
        cv2.imshow("Tracking", annotated_frame)
        
        if cv2.waitKey(1) & 0xFF == 27:  # Esc to quit
            break
    else:
        break

cap.release()
cv2.destroyAllWindows()
```

With `persist=True`, IDs remain assigned to tracked objects until they're lost by the tracker (typically when they leave the frame or are occluded for too long). The tracker's memory duration is controlled by parameters like `track_buffer` in the tracker config files.
