### ISSUE TITLE
 How do we change the color of the predicted bounding box in yolov8?  I have made changes to plotting.py but still, changes are not reflecting. 

### ISSUE THREAD

**Issue by Niraj-Lunavat** [ultralytics/ultralytics#5160]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

 How do we change the color of the predicted bounding box in yolov8?  I have made changes to plotting.py but still, changes are not reflecting.

**Comment by glenn-jocher** [comment]
@Niraj-Lunavat hi there,

To change the bounding box color in YOLOv8, you should indeed make changes in the `plotting.py` file. Specifically, you will need to modify the line where the color is defined for the bounding boxes.

However, if you're making changes but not seeing them reflected, it might be because the modified file is not being used during execution. Make sure that the correct `plotting.py` file has been modified and is being read by the system.

Another issue could be due to caching. Python often caches compiled Python files as .pyc files in a `__pycache__` folder. If this folder exists in your path, you might want to delete it to make sure your changes are not being overlooked.

In future, to debug such issues, you could add print statements in the `plotting.py` file to confirm whether the modified function is called and the changes are working as expected.

Remember, the bounding box color is an RGB tuple. Each value in the tuple ranges from 0 to 255 and represents the red, green and blue color respectively. So, ensure that you are providing the correct value format.

Hope this helps! Let's keep making YOLOv8 better together!

**Comment by Wang-taoshuo** [comment]
@glenn-jocher Hello, when I use yolov8-seg, I don't want to produce bounding boxes. Where can I make this setting? I only want to generate masks and recognize object names.

**Comment by Srushti-02** [comment]
@glenn-jocher I tried modifying  the line where colors are defined for bounding boxes and also tried by deleting  __pycache__ folder but still it's not working.

**Comment by glenn-jocher** [comment]
Hello @Srushti-02,

Thank you for your quick response. 

It seems that you've done everything correctly according to your description. Identifying why the changes haven't taken effect can be sometimes tricky. 

One option to check is whether you've restarted the program (or Python kernel if you're using Jupyter Notebook) after making the changes to the `plotting.py` file. Python keeps the modules loaded in memory and it might be simply still using the old version of the module, thus restarting the working environment might help.

Also, I see you've tried deleting the __pycache__ folder, make sure to delete the .pyc files associated with the module you’ve changed (in case if they are located elsewhere).

If the issue still persists, I would suggest adding some logging or print statements in your modified plotting code to debug if the function with your changes is being called. This way we would get a clue whether your changes are being picked up during execution.

Looking forward to hearing back from you.

**Comment by glenn-jocher** [comment]
@HunarAA hi there! 👋

Absolutely, you can change the bounding box colors in YOLOv8 by tweaking the `plotting.py` file. If you're not seeing changes reflect, it might be because of the Python caching or the need to restart your environment after the modifications.

Here's a quick pointer on where to look:

```python
# Inside plotting.py, find the line where colors are set for bounding boxes
color = (255, 0, 0)  # Change to your desired RGB color
```

Make sure to save the file, clear any `.pyc` files in `__pycache__`, and restart your runtime or script.

Hope this helps! Let us know if you're still facing issues. Happy coding! 🚀

**Comment by HunarAA** [comment]
Thank you @glenn-jocher, I have solved the issue by removing the "plotting.pyc" file. And I am asking something else if possible. Is there a way to set new parameter to the prediction CLI command? For example, setting new parameter to "box_label" function then sending it's value through CLI command?

**Comment by glenn-jocher** [comment]
@HunarAA hi there! I'm glad to hear you solved the issue by removing the `plotting.pyc` file! 🎉 For adding a new parameter to control something like `box_label` from the CLI, you'll need to make changes in two places:

1. **Accept the parameter in the CLI**: Modify the script that parses CLI arguments (likely in your main script or a dedicated arguments parser script if you have one) to accept your new parameter, for example `--custom_label`.

2. **Pass the parameter to the function**: Ensure that the script which calls `box_label` function accepts this parameter from the CLI argument and passes it correctly to the function.

For a quick code example, if you're modifying CLI argument parsing, it might look something like this:

```python
parser.add_argument('--custom_label', type=str, default='default value', help='Custom label for bounding boxes')
```

And then in your prediction logic, you'd use it like so:

```python
args = parser.parse_args()
# assuming `box_label` is your function that now accepts a `custom_label` argument
box_label(custom_label=args.custom_label)
```

Remember to update your `box_label` function definition to accept the new parameter as well.

Happy coding! Let us know if you have any other questions.

**Comment by HunarAA** [comment]
Many thanks, let me try it out.

**Comment by glenn-jocher** [comment]
@HunarAA you're welcome! Glad I could help. 🚀 If you run into any hurdles or have more questions, feel free to reach out. Happy coding!

**Comment by fatemehmeshkini** [comment]
could you please tell me in which line of plotting.py I can delete the label of detected objects  in Yolov8? or if  it isn't possible make it the minimum size.                   
 
Thanks.

**Comment by glenn-jocher** [comment]
Hello there!

To remove or minimize the object labels in YOLOv8's `plotting.py`, you'd need to look for the code block responsible for drawing text, which typically includes `cv2.putText()` function calls. To simply remove labels, you might comment out or delete these lines. However, the exact line number can vary depending on your YOLOv8 version.

As for the "read-only" issue, it sounds like a file permission or an IDE/editor restriction. Try opening the file with a different text editor or adjust the file's permissions. On a Unix-based system, you could use `chmod +w plotting.py` to make it writable.

Hope this helps! Let us know if you encounter any more challenges. 😊

**Comment by fatemehmeshkini** [comment]
It was really helpful.🙂
thank alot.

**Comment by fatemehmeshkini** [comment]
hello there
How do I get the detected object coordinates

on trained model by our data in yolov8 ?

my code:

!yolo task=detect mode=train model=yolov8s.pt data='data.yaml' epochs=20
imgsz=640 !yolo task=detect mode=val model='best.pt' data='data.yaml' !yolo
task=detect mode=predict model='best.pt' conf=0.25 source='.png'
hide_labels=True hide_conf=True

there is just one class.


I will thank if you may write the code please .it is necessary.

**Comment by raian-ruku** [comment]
how do i find the `plotting.py` file? can anyone help?

**Comment by glenn-jocher** [comment]
Hello! 👋

The `plotting.py` file should be located in the `utils` directory of your YOLOv8 installation. If you've cloned the repository, you can find it under `ultralytics/yolov8/utils/`. If you're unable to locate it, ensure you have the latest version of the repository. You can also search for the file in your project directory using a command like `find . -name plotting.py` if you're using a Unix-like system.

Hope this helps! Let us know if you need further assistance. 😊
