### ISSUE TITLE
Is there a way to change class names on a already trained model?

### ISSUE THREAD

**Issue by Maya084** [ultralytics/ultralytics#5164]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I need to change the names of some of the classes that I have trained the model with. Currently, I'm able to achieve this by loading the model and modifying the class names in `model.model.names`. However, I'm wondering if there's a way to permanently save the model with these modified class names, so I don't need to make changes every time I load the model?

Any guidance on how to accomplish this would be greatly appreciated. Thank you!

### Additional

Exporting the model in `.pt` format doesn't work, which is why I also opened this issue as well: #5163

**Comment by glenn-jocher** [comment]
@Maya084 hello,

Thanks for reaching out regarding your issue with class names in YOLOv8. This issue often comes up when users need to adapt a trained model to a different dataset with different class names.

Currently, the class names are not stored as part of the model itself but are referenced from external .names or .yaml files. That's why any changes you make directly to the model instance don't persist when you save and reload the model. 

In response to your question, the best way to permanently change class names is to modify your .names or .yaml file directly where your class labels are defined. This way, whenever you load the model, it would reference these updated class names.

Regarding your note on saving the model in `.pt` format not working, I'll look into issue #5163 separately to understand better what the issue might be and provide an appropriate solution.

Please don't hesitate to reach out if you have any more questions.

**Comment by Maya084** [comment]
Hi Glenn, thank you for your response and clarification. I appreciate your help.

I've tried modifying the `.yaml` file as suggested, where my class labels are defined, but unfortunately, the changes don't seem to take effect when I load the model. There are only 2 `.yaml` files I could find: the config file with which I trained the model (where I tried changing the names) and the one saved with the run `args.yaml`, in which there are no names for the classes. Is there a different `.yaml` file I am missing? 

I've also looked for a `.names` file but couldn't locate it.

**Comment by glenn-jocher** [comment]
@Maya084 hello,

Thank you for following up on this. Let's see if we can get this resolved for you.

Firstly, you are correct about the `.yaml` files. Typically, these files contain architectural and training parameters. For the YOLOv8 model, class names are not directly included in the .yaml files.

As for the class names, they're generally saved in a `.txt` file when you create your dataset, not in `.yaml` files. This file contains each class name on a new line and the order of the classes is of importance. It’s often referred to as the names file, which could be where the confusion arises from regarding `.names` files.

In case of YOLOv8, when you train a model, a copy of your configuration used for training the model is saved in a directory (usually under runs/train/exp*), but the class names should be defined within your dataset directory.

You would need to find the `.txt` file that was used when training the model, and you should be able to update your class names there. Unfortunately, you can't change the class names of an already trained model by just changing the names in this file, you will need to retrain your model if you edit the class names.

I hope this helps clarify the class name issue you're facing. Let me know if you have any further questions or face any additional problems.
