### ISSUE TITLE
Training DDP error v190

### ISSUE THREAD

**Issue by apiszcz** [ultralytics/ultralytics#5170]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Upgraded to v190, unable to start training.

yolo version 180 producing similar error.

$ yolo version
8.0.190

```
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 445, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 334, in train
    self.trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 190, in train
    raise e
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 188, in train
    subprocess.run(cmd, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'torch.distributed.run', '--nproc_per_node', '4', '--master_port', '41845', '/home/user/.config/Ultralytics/DDP/_temp_1x0i2gk4139992805524576.py']' returned non-zero exit status 1.
```

### Environment

Ultralytics YOLOv8.0.190    Python-3.10.12 torch-2.0.1+cu117 CUDA:0 (NVIDIA A100-PCIE-40GB, 40339MiB)
Setup complete    (64 CPUs, 176.9 GB RAM, 69.7/1035.4 GB disk)

OS                  Linux-5.15.0-84-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             pip
RAM                 176.87 GB
CPU                 Common KVM processor
CUDA                11.7

matplotlib          ✅ 3.8.0>=3.3.0
numpy               ✅ 1.26.0>=1.22.2
opencv-python       ✅ 4.8.0.76>=4.6.0
pillow              ✅ 10.0.1>=7.1.2
pyyaml              ✅ 5.4.1>=5.3.1
requests            ✅ 2.25.1>=2.23.0
scipy               ✅ 1.11.2>=1.4.1
torch               ✅ 2.0.1>=1.8.0
torchvision         ✅ 0.15.2>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 2.1.1>=1.1.4
seaborn             ✅ 0.12.2>=0.11.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by apiszcz** [comment]
Related error

RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 28 but got size 27 for tensor number 1 in the list.

**Comment by apiszcz** [comment]
Batch size too large for memory. Reduced, no issue.

**Comment by glenn-jocher** [comment]
@apiszcz thank you for reaching out. It seems like you've experienced an issue related to the memory constraints on your current hardware setup while training the YOLOv8 model, which was resolved by reducing the batch size.

Training deep learning models like YOLOv8 requires an adequate balance of considerable computational resources. In practice, the batch size is an important hyperparameter that determines how many samples the model sees at once during the training process. Larger batch sizes allow the model to process more data at once, which can speed up training. However, it also increases the demand for computational resource, particularly GPU memory.

The error you encountered typically arises when the model and the data batches don't fit into your GPU memory. You've done the right thing by reducing the batch size, hence, allowing the model to fit within your GPU's memory constraints. One common practice is to find the largest batch size that fits into memory, as it can often lead to better training dynamics.

Remember to monitor the GPU utilization and memory consumption during your training sessions routinely. This will help you understand if any other bottlenecks exist and adjust your training setup accordingly.

Should you encounter additional issues or need further assistance, don't hesitate to ask. We're here to help.

**Comment by apiszcz** [comment]
I was not able to use the 4 GPUs in parallel either, the training run
operates ok on one 1 GPU.
I need to learn more about DDP.
Thanks.

**Comment by glenn-jocher** [comment]
@apiszcz hello,

Thanks for your update, it's great to see that you're using multiple GPUs to accelerate your YOLOv8 training.

Regarding Distributed Data Parallel (DDP), I understand it can seem complex when you're starting out. Briefly, DDP is a PyTorch utility that allows for the use of multiple GPUs, helping you get faster model training by parallelizing the training process. It does this by distributing the dataset across the available GPUs and each GPU processes a batch of the dataset independently. The gradients are then synced between the GPUs.

However, there are several factors which might be preventing the effective use of all your GPUs. It could be due to insufficient memory, a data loading bottleneck, or issues with the distribution of the workload across the available GPUs. 

You may want to check each GPU's memory usage and utilization during training. This can provide valuable insights to help you diagnose any bottlenecks or inefficiencies in your process.

Please continue to explore and familiarize yourself with DDP and how to effectively use it for training YOLOv8. Remember, the goal is to optimize your training process given the hardware you are working with.

As always, feel free to reach back if you have more questions or need further clarification. We're here to support your journey with YOLOv8.

Best regards,
Glenn
