### ISSUE TITLE
Yolo V8 Custom Keypoint Pose Detection Tutorial Request 

### ISSUE THREAD

**Issue by Jaykumaran** [ultralytics/ultralytics#5187]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi team,
Recently I'm trying to annotate my robot arm using cvat and tried to convert that annotation.xml to yolo format and tried to train in colab in yolov8n-pose it throws many errors.Need a detailed blog on how to train a custom keypoint detection tutorial or YouTube video by nicolas.Update the reply as soon kindly.As I'm stuck up with the project and it's urgent 
@glenn-jocher @rizwa

**Comment by RizwanMunawar** [comment]
@Jaykumaran, thank you for sharing this valuable information. We appreciate your feedback, and I want to let you know that we will be working on creating documentation for this topic in the near future!

If you have any further questions or need additional assistance, please don't hesitate to reach out. Thanks again!

**Comment by Jaykumaran** [comment]
Can I have a quick fix because it's urgent project to detect my robot arm.

**Comment by Jaykumaran** [comment]
My IMG size is 1920*1080

And I normalised the annotations using these IMG width and height.

The error is can't unpack files expected 3 rec 0

**Comment by glenn-jocher** [comment]
Hello @Jaykumaran,

It seems you're experiencing a problem with the unpacking procedure during training. The specific error message suggests that the program is expecting 3 records but getting 0.

This typically happens when there's a mismatch in your dataset's annotations. Ensure that your annotations are correctly formatted according to the requirements of YOLOv8, with the appropriate number of values for xmin, ymin, xmax, ymax, and class id.

Additionally, make sure your annotations are properly normalized, they should fall within a scale of 0 to 1, using the image width and height for normalization. This normalization is a key step in the process, and incorrect scaling could potentially lead to errors.

I suggest examining a few of your annotation files to verify that they are properly formatted and correctly scaled according to the dimensions of your images.

Hope this helps!

Best,
Glenn

**Comment by Jaykumaran** [comment]
Hi Glenn,
Expecting a custom keypoint Detection for yolov8-pose without error step by
step ,both a tutorial by Nicolas from Ultralytics and  at
documentation.Requested to work on this documentation and tutorial.

Hoping soon,
Thanks

**Comment by glenn-jocher** [comment]
@Jaykumaran hi there,

We appreciate your suggestion. We understand the need for ample information and tutorials to help our users get the most out of YOLOv8, especially for more advanced use-cases such as keypoint detection. We'll certainly pass this suggestion on to the team and Nicolas to consider as we continue to develop our resources and support for YOLOv8.

Thank you for your patience and understanding, and we hope to bring you these requested materials as soon as we can. In the meantime, we're here to assist you with any issues you experience during your project.

Best,
Glenn

**Comment by Jaykumaran** [comment]
Hi Ultralytics Team,
I was able to successfully train keypoint using yolo-pose by resizing my
all image sto 640*640 and normalising my annotations
0 0.485896 0.332236 0.255865 0.248009 0.357964 0.351019 2 0.545229 0.208231
2 0.613828 0.456241 2
But there is no kpt_line available.Do guide me whether i should change
anything before training and retrain or is there any other way to view/draw
kpt_line in prediction.I tried this,

results = model.predict(source="C:\\Users\\jaikr\\Downloads\\Final\\train\images\\WIN_20230915_20_27_08_Pro.jpg")
# Draw bounding boxes and labels on the frame
img = results[0].plot(kpt_line=True, kpt_radius=5)
# img.save('C:\\Users\\jaikr\\runs\\pose\\predict\\6results.jpg')
# Show the results
for r in results:
    im_array = r.plot(kpt_line=True, kpt_radius=10)  # plot a BGR
numpy array of predictions
    im = Image.fromarray(im_array[..., ::-1])  # RGB PIL image
    im.show()  # show image
    im.save('results.jpg')  # save image

Still line is not visible.I'm at end of my project and this would be useful

**Comment by glenn-jocher** [comment]
Hello @Jaykumaran,

Thank you for reaching out! You have been doing very well, resizing and normalizing the images are crucial steps. 

Now, regarding the keypoint lines (kpt_line) not being visible, this could be due to the predict function not being able to find keypoints in your images. If the keypoints are not detected appropriately, then lines connecting them cannot be rendered. 

The keypoints' annotation in the dataset could be an issue here, ensure that your keypoint annotations are done accurately and they fall within the image boundaries after being normalized. 

Another thing to look at is your model's performance. If it's not performing well, it may not be detecting the keypoints correctly, hence, unable to draw the lines. 

I'm glad to hear that you're nearing the end of your project and I hope this information can help you move forward. Feel free to reach out if you need more assistance.

Best regards,
Glenn

**Comment by Jaykumaran** [comment]
Hey Glenn,
Thanks for continuous support Team, atlast I've found a way to draw lines
by extracting the tensor and using that points by PIL Image draw function i
was able to join the points.However its not working for opencv.Will try to
find solution for that as well. I hereby attach the error thrown while
using opencv for my pose best model. and my output.Ex[ecting in near future
full documentation and tutorials on these.

Thanks Glenn and Team,
Jaykumaran

Error while reading in OpenCV:
C:\Users\jaikr\PycharmProjects\CarCounter\CarCounter\Scripts\python.exe
C:\Users\jaikr\PycharmProjects\CarCounter\Object-Detection-101\Robot.py
Traceback (most recent call last):
  File
"C:\Users\jaikr\PycharmProjects\CarCounter\Object-Detection-101\Robot.py",
line 7, in <module>
    model = YOLO("C:\\Users\\jaikr\\Downloads\Final\\best.pt")
  File
"C:\Users\jaikr\PycharmProjects\CarCounter\CarCounter\lib\site-packages\ultralytics\yolo\engine\model.py",
line 61, in __init__
    {'.pt': self._load, '.yaml': self._new}[suffix](model)
  File
"C:\Users\jaikr\PycharmProjects\CarCounter\CarCounter\lib\site-packages\ultralytics\yolo\engine\model.py",
line 91, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File
"C:\Users\jaikr\PycharmProjects\CarCounter\CarCounter\lib\site-packages\ultralytics\nn\tasks.py",
line 384, in attempt_load_one_weight
    ckpt = torch_safe_load(weight)  # load ckpt
  File
"C:\Users\jaikr\PycharmProjects\CarCounter\CarCounter\lib\site-packages\ultralytics\nn\tasks.py",
line 332, in torch_safe_load
    return torch.load(file, map_location='cpu')  # load
  File
"C:\Users\jaikr\PycharmProjects\CarCounter\CarCounter\lib\site-packages\torch\serialization.py",
line 809, in load
    return _load(opened_zipfile, map_location, pickle_module,
**pickle_load_args)
  File
"C:\Users\jaikr\PycharmProjects\CarCounter\CarCounter\lib\site-packages\torch\serialization.py",
line 1172, in _load
    result = unpickler.load()
  File
"C:\Users\jaikr\PycharmProjects\CarCounter\CarCounter\lib\site-packages\torch\serialization.py",
line 1165, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'PoseModel' on <module
'ultralytics.nn.tasks' from
'C:\\Users\\jaikr\\PycharmProjects\\CarCounter\\CarCounter\\lib\\site-packages\\ultralytics\\nn\\tasks.py'>

Process finished with exit code 1

**Comment by Jaykumaran** [comment]
Code I ve used to draw kpt line using keypoints by PIL Image draw
attached.Expecting the same for videos with opencv, but seems something
error with torch module in ultralytics.nn for this pose model

**Comment by glenn-jocher** [comment]
Hello @Jaykumaran,

It's great to hear that you've made progress with drawing lines using PIL Image. 

As for the issue with OpenCV, the error message suggests that the 'PoseModel' attribute cannot be retrieved from the 'ultralytics.nn.tasks' module during the deserialization process undertaken by PyTorch's 'torch.load' function. 

It could be the case that this is due to differing versions of Ultralytics or PyTorch between the environment where the model was saved and the environment where it is being loaded. 

Ensure that you are using the same versions of Ultralytics and PyTorch for both training and inference. If these environments are different, it's essential that they have the same versions of the packages to maintain compatibility. 

Keep us updated and feel free to reach out if you need further assistance.

Best regards,
Glenn

**Comment by glenn-jocher** [comment]
@Jaykumaran we've created a really simple custom keypoint dataset called Tiger-Pose that is about 200 images labelled of Tigers from a short YouTube video. Please take a look at it here and let us know if this helps you!

https://docs.ultralytics.com/datasets/pose/tiger-pose/
