### ISSUE TITLE
Trouble Loading Weight File 'yolov8x-pose.pt' Locally in Python Script

### ISSUE THREAD

**Issue by gaetzzz** [ultralytics/ultralytics#5197]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello everyone,

I'm currently facing an issue while attempting to load a weight file, 'yolov8x-pose.pt,' from the local directory within the same folder as my Python script. Here's the code I'm using:

```
import os

modelPath = os.getcwd() + "/yolo/yolov8x-pose.pt"
model = YOLO(modelPath)
```

However, I'm encountering the following error message:

```
Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8x-pose.pt to '/home/gsimonel/yolo/yolov8x-pose.pt'...
Traceback (most recent call last):
  File "/home/gsimonel/.conda/envs/TF-GPU/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  ...
socket.gaierror: [Errno -3] Temporary failure in name resolution
```

I've also attempted a simplified approach like this:

`model = YOLO('yolov8x-pose.pt')`

Unfortunately, this doesn't seem to work either. Any insights or suggestions on how to resolve this issue would be greatly appreciated!

**Comment by glenn-jocher** [comment]
@gaetzzz hello, thank you for reaching out! 

From the code snippet you shared, it looks like your YOLO model is attempting to download the weights from the internet, despite the 'yolov8x-pose.pt' weights file being present in a local directory. The error you're seeing is because the weights download was unsuccessful.

Usually, if your weights file is in the same folder as your script or in a specified path, the YOLO model should load it without trying to download it from the internet. If the file is not found in the specified location, then it attempts to download it.

If you are absolutely sure the 'yolov8x-pose.pt' weights file is in the correct location, there could be an issue with your current working directory or with the way paths are handled in your script. Make sure that your working directory is as expected, and you might want to consider using standard Python functions for handling paths, such as os.path.join(), for platform compatibility.

If these suggestions don't help, or if you're still having trouble, let us know. We're here to assist!

**Comment by gaetzzz** [comment]
Thank you for your answer glenn, as you can see from this picture (link: https://ibb.co/D718s8s) the weight of the network are in the same folder of the script. The script I am using is train.py and the weight file is yolov8x-pose.pt

**Comment by glenn-jocher** [comment]
@gaetzzz hello, thanks for your follow-up question and for providing additional context. From your description, it indeed sounds like the weights file is in the same directory as your train.py script. 

You're essentially doing the correct procedure. When you specify the weights as 'yolov8x-pose.pt' and the weights file is in the same directory as your script, YOLOv8 should be trying to load the weights from that location.

One common issue that python scripts encounter when trying to access files in their directory is path related. Python uses the directory where the interpreter was called as its starting point for relative paths, which might not always be the directory where the script resides. 

Please ensure that when you're running the script, your terminal or command line is navigated to the correct directory i.e., the same directory where both the train.py script and 'yolov8x-pose.pt' weights reside.

If the script is being run from a different directory, it might not find the weights file because it's looking in the wrong place.

I hope this helps! Just let me know if you continue facing issues.
