### ISSUE TITLE
AttributeError: 'str' object has no attribute 'stride' when trying to build or get dataset for further plotting

### ISSUE THREAD

**Issue by GrigoriiTarasov** [ultralytics/ultralytics#5201]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Val

### Bug

```
Cell In[10], line 1
----> 1 trainer.build_dataset(f'{folder_abs}/images/', 
      2                       mode='val', batch=None) 
      3 #plot_training_labels()

File ~/mambaforge/envs/yolo8/lib/python3.10/site-packages/ultralytics/models/yolo/detect/train.py:39, in DetectionTrainer.build_dataset(self, img_path, mode, batch)
     30 def build_dataset(self, img_path, mode='train', batch=None):
     31     """
     32     Build YOLO Dataset.
     33 
   (...)
     37         batch (int, optional): Size of batches, this is for `rect`. Defaults to None.
     38     """
---> 39     gs = max(int(de_parallel(self.model).stride.max() if self.model else 0), 32)
     40     return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=mode == 'val', stride=gs)

AttributeError: 'str' object has no attribute 'stride'
```

### Environment

10/site-packages/torch/cuda/__init__.py:152: UserWarning: 
    Found GPU1 GeForce GTX 650 Ti which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    The minimum cuda capability supported by this library is 3.7.
    
  warnings.warn(old_gpu_warn % (d, name, major, minor, min_arch // 10, min_arch % 10))
Ultralytics YOLOv8.0.191 🚀 Python-3.10.12 torch-2.0.1+cu117 CUDA:0 (Tesla V100-PCIE-32GB, 32510MiB)
Setup complete ✅ (20 CPUs, 15.3 GB RAM, 355.8/442.3 GB disk)

OS                  Linux-4.4.0-210-generic-x86_64-with-glibc2.23
Environment         Linux
Python              3.10.12
Install             pip
RAM                 15.35 GB
CPU                 Intel Core(TM) i9-10900X 3.70GHz
CUDA                11.7

matplotlib          ✅ 3.8.0>=3.3.0
numpy               ✅ 1.26.0>=1.22.2
opencv-python       ✅ 4.8.0.76>=4.6.0
pillow              ✅ 10.0.1>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.2>=1.4.1
torch               ✅ 2.0.1>=1.8.0
torchvision         ✅ 0.15.2>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 2.1.1>=1.1.4
seaborn             ✅ 0.12.2>=0.11.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
(yolo8) bizon@bizon:~/data/spot$ 

### Minimal Reproducible Example

```
from ultralytics.models.yolo.detect import DetectionTrainer

args = dict(model=f'{folder_abs}/yolov8n.pt', 
            data=f'{folder_abs}/{dataset_name}', 
            epochs=3)
trainer = DetectionTrainer(overrides=args)

trainer.build_dataset(f'{folder_abs}/images/', 
                      mode='val', batch=None) 
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@GrigoriiTarasov it appears you are encountering an `AttributeError` when calling the `build_dataset` method of the `DetectionTrainer` class. The error message indicates that a 'str' object has no attribute 'stride' which suggests that an object that was expected to have a 'stride' attribute is actually a string.

Looking at the stack trace, the error occurs at the line `gs = max(int(de_parallel(self.model).stride.max() if self.model else 0), 32)`. In this line of code, it seems that `self.model` should be an model object that has a `stride` attribute. However, the error message suggests that `self.model` could be a string.

In your minimal reproducible example, you are passing `f'{folder_abs}/yolov8n.pt'` as the `argument` for `model` when creating a `DetectionTrainer` instance. This is a string pointing to a model file and not an actual model object.

To resolve this issue, you might need to load the model from the file before creating the `DetectionTrainer` instance so that `self.model` will point to a model object rather than a string. Keep in mind you'll have to adjust how you load your model based on your project.

Additionally, make sure the model file exists at the path you specified and that it is a valid YOLOv8 model file. If the file does not exist or is not a valid model file, loading the model will fail and `self.model` will not point to an actual model object.
