### ISSUE TITLE
Args loading in resuming mode

### ISSUE THREAD

**Issue by hoangmd2410** [ultralytics/ultralytics#5203]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In file ultralytics/engine/trainer.py, I am quite confused about the way your check_resumse function updating new parameters

`def check_resume(self, overrides):
        
        resume = self.args.resume
        if resume:
            try:
                exists = isinstance(resume, (str, Path)) and Path(resume).exists()
                last = Path(check_file(resume) if exists else get_latest_run())

                # Check that resume data YAML exists, otherwise strip to force re-download of dataset
                ckpt_args = attempt_load_weights(last).args
                if not Path(ckpt_args['data']).exists():
                    ckpt_args['data'] = self.args.data

                resume = True
                self.args = get_cfg(ckpt_args)
                self.args.model = str(last)  # reinstate model
                for k in 'imgsz', 'batch':  # allow arg updates to reduce memory on resume if crashed due to CUDA OOM
                    if k in overrides:
                        setattr(self.args, k, overrides[k])

            except Exception as e:
                raise FileNotFoundError('Resume checkpoint not found. Please pass a valid checkpoint to resume from, '
                                        "i.e. 'yolo train resume model=path/to/last.pt'") from e
        self.resume = resume `

It seems that you only permit overriding 'imgsz' and 'batch'. So the trainer will use the default device in file checkpoint to continue training process (ex: device=1) even when I assign device=2 in my command line. It is easy to add property 'device' to beside 'imgsz' and 'batch' but i wonder whether there is any reason for this mechanism? Thank you

**Comment by glenn-jocher** [comment]
@hoangmd2410 hello, and thank you for taking a close look at the code!

In the `check_resume` function, we do facilitate some overriding of specific properties namely 'imgsz' and 'batch'. This is primarily done to allow for adjustments that could help prevent out-of-memory (OOM) errors when resuming training if it was previously interrupted because of such issues. Adjusting 'imgsz' or 'batch' size has a direct impact on memory usage and hence was included.

Coming to your example, the device used for training is indeed drawn from the checkpoint rather than the command line in resume mode. While it might seem like an easy step to include 'device' in the list of arguments that can be overridden, we opted against it for the sake of training consistency. If you imagine a scenario with different GPUs having different capabilities, switching the device in the middle of a training run could potentially introduce unexpected behaviors.

However, your feedback is important and valid. We recognize our users have different needs and we're constantly trying to ensure our software remains versatile and user-friendly. We will consider whether making this part more configurable could be a good path forward in future updates of YOLOv8.

Thank you for using YOLOv8 and contributing to its improvement with your question.
