### ISSUE TITLE
Migrate to openvino 2023.1 instead of openvino-dev

### ISSUE THREAD

**Issue by ilya-lavrenov** [ultralytics/ultralytics#5213]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

OpenVINO 2023.1 has significantly improved user experience and now users can use `openvino` package instead of `openvino-dev` which provides all the functionality with minimum dependencies. 

Currently, we see that [ultralytics](https://github.com/ultralytics/ultralytics) uses `mo.convert_model` while it's possible to use `ov.convert_model` which does not require `openvino-dev` package (see https://docs.openvino.ai/2023.1/openvino_docs_model_processing_introduction.html#convert-a-model-in-python-convert-model)

### Use case

It will make installation more lightweight since `openvino` has less dependencies than `openvino-dev`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ilya-lavrenov thank you for bringing this to our attention. Indeed, transitioning to OpenVINO 2023.1 and utilizing the `openvino` package instead of `openvino-dev` could potentially make the installation process more lightweight due to fewer dependencies. It's very beneficial to continually improve the user experience, and this could be a significant step in that direction.

The point about `mo.convert_model` vs. `ov.convert_model` is well taken, and we appreciate the insight. It's always a good practice to use the most efficient functions available without comprising the functionality and usability of our toolkit.

We will thoroughly evaluate the possibility of migrating YOLOv8 to this newer version taking into consideration all the implications, especially the potential backward compatibility issues, performance, and the overall stability of the new package.

Given your keen interest in this feature, if you would like to contribute further on this topic, you are welcome to assist by submitting a PR. We value contributions from our user community as they play a pivotal role in the growth and refinement of our repos.

Thank you again for your suggestion!

**Comment by ilya-lavrenov** [comment]
Hi @glenn-jocher 
In order to fix those tests: https://github.com/ultralytics/ultralytics/blob/6923b3a4142bbed92213687255bff3961e436efd/.github/workflows/ci.yaml#L243-L301 you can migrate to OpenVINO 2023.1 and depend only on `openvino` which is fully available on conda-forge.

**Comment by glenn-jocher** [comment]
@ilya-lavrenov hello,

Thank you for your suggestion on migrating to OpenVINO 2023.1 and depending on 'openvino' for fixing the tests. It's great to know that 'openvino' is fully available on conda-forge.

Before transitioning implementation, we will need to evaluate the feasibility and impact of this migration. This includes checking the compatibility of our current systems with OpenVINO 2023.1, potential backward compatibility issues, and the stability and performance of the new package.

Rest assured that we appreciate and value your input. Our team is committed to continuous improvement and such suggestions play a big part in that.

We'll definitely consider this while planning future updates.

Again, thank you for your suggestion and contribution to the YOLOv8 community.

**Comment by zshariff6506** [comment]
If you are willing to go forward with the migration, I can give a assisting hand.
