### ISSUE TITLE
Disable NMS

### ISSUE THREAD

**Issue by assafzamir** [ultralytics/ultralytics#5226]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, is there a way to disable NMS?

for example, I wish to be able to do that
```
model = YOLO('yolov8s.pt')
img_path = 'path..'
res = model.predict(img_path, apply_nms=False)
```

**Comment by RizwanMunawar** [comment]
@assafzamir YOLOv8 does not have a built-in option to disable the Non-Maximum Suppression (NMS).

To disable NMS in Ultralytics YOLOv8, you can follow these steps:
- Clone the Ultralytics YOLOv8 code repository `git clone https://github.com/ultralytics/ultralytics.git`
- Search for the NMS code, you can find it [here](https://github.com/ultralytics/ultralytics/blob/bd8d0ce85f1d1118b24ca863970d4e3f74e68727/ultralytics/models/yolo/detect/predict.py#L25)
- Remove the NMS  
- Build the modified script.
- Run the modified script without NMS to achieve the desired behavior.

Please note that modifying the code in this way should be done with caution, as it may affect the model's performance and results.

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by assafzamir** [comment]
@RizwanMunawar Thanks for your reply.

I want to compare the performance of a PyTorch model with its converted TensorRT model. I have my own metrics code, a test dataset, and an edge device for the TensorRT engine model.

Do you have any suggestions on the best practices to perform this comparison? The PyTorch model performs NMS post-processing while the engine doesn’t, and there is no option to control it without changing the code of Ultralytics.

**Comment by glenn-jocher** [comment]
@assafzamir hello,

Thanks for providing more details about your task. Comparing the performance of a PyTorch model with its converted TensorRT model involves considerations both for accuracy and speed.

In terms of accuracy, you would want to ensure both models are being evaluated on the same test dataset, using the same metrics code as you currently do. It's important to clarify that for a fair comparison, the same pre-processing and post-processing steps should be applied to both models. In your case, I understand your PyTorch model uses Non-Maximum Suppression (NMS) post-processing which the TensorRT engine model doesn’t. This could lead to slight differences in their output. Therefore, for a better comparison, you could implement NMS post-processing for the TensorRT model as well, in order for both models to undergo the exact same processing steps.

Regarding the performance comparison, it's ideal to test both models on the same edge device, since different hardware and software environments can greatly influence the speed performance of the models.

Lastly, assessing how the models perform at different input sizes or in different scenarios (e.g., running concurrently with other processes) could provide additional interesting insights about their trade-offs in practice.

Remember, these are general guidelines. You might need to adjust these suggestions based on your specific scenario, requirements and resources available. Making code changes for such studies is not uncommon and forms a part of fair benchmarking practices.

Good luck with your performance comparison task! If you have other questions, feel free to ask.

**Comment by krasnoteh** [comment]
Hello, there are no direct ways to disable nms, but you can set its threshold to maximal possible value (**1.0**), so any bounding boxes that have at least slightly different coordinates would not be suppresed. Since the model outputs have float coordinates, the probability of a complete coincidence of two boxes is very low.
In your example it would be
`
model = YOLO('yolov8s.pt')
img_path = 'path..'
res = model.predict(img_path, iou = 1.0)
`
Hope this helps!

**Comment by glenn-jocher** [comment]
Thank you for sharing the suggestion. Setting the IoU threshold to 1.0 is indeed a practical workaround to minimize the effects of NMS. If you have further questions or need additional assistance, feel free to ask!

**Comment by GabrieldeBlois** [comment]
Hello, If your goal is to experiment with the raw output of the model quickly and without modifying ultralytics lib, you can just:

```python
import numpy as np
from PIL import Image
from ultralytics import YOLO

model = YOLO("path/to/model.pt")
image = Image.open("image.jpg")
ret = model.predict("image.jpg")
im = model.predictor.preprocess(np.array(image)[np.newaxis, ...])
preds, img, orig_imgs = model.predictor.inference(im)
```

**Comment by glenn-jocher** [comment]
Thank you for sharing! Your approach is a practical way to access the raw model outputs without modifying the Ultralytics library. This can indeed be helpful for advanced experimentation or custom post-processing. Let us know if you need further clarification.
