### ISSUE TITLE
inferencing 2 models parallely

### ISSUE THREAD

**Issue by coder-glitche** [ultralytics/ultralytics#5234]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hey @glenn-jocher ! i tried running 2 models parallely by syncing my cameras images to 1st models input folder and syncing crops of 1st models predictions to 2nd models input folder using multiprocessing but my model isnt loading and performing inference im not sure if ive passed right args in my inference logic and my process but im unable to figure out what the error is my python script just runs syncs my source folder with 1st models input folder and just stops doesnt even show any error can you please help me out...

heres the link for my code 
https://github.com/coder-glitche/yolo/blob/main/inference.py

**Comment by coder-glitche** [comment]
sorry for the pasting code like that heres the link for the code 
https://github.com/coder-glitche/yolo/blob/main/inference.py

**Comment by Kayzwer** [comment]
based on your logic it is impossible to run two models in parallel as you said the second model gets results from first model

**Comment by coder-glitche** [comment]
Hey @Kayzwer ! When i say parallel what i meant was both models should be running indefinitely and when there is a new image in the input folder of respective model they should get inferenced the crops of my 1st model gets saved in a path which i know and until that path is not created my 2nd model doesn't start inference.once the new folder is created the images saved under crops folder gets synced continuously with input folder of 2nd model and gets infered...my issue rn is first model itself isnt inferencing....

**Comment by glenn-jocher** [comment]
Hello @Kayzwer,

Thanks for clarifying your requirements. If I understand correctly, you wish to run two models in different processes and whenever there is a new image in the input folder of each model, it should run inference. The input to the second model relies on the output of the first model.

Firstly, ensure that your program is capable of monitoring changes in the folders. You might have to use a function that triggers the inference process whenever a new image is detected. This can be achieved through various file change monitoring mechanisms available in Python.

Also, you need to make sure that your models are loaded correctly. Sometimes, models might not load if there are compatibility issues with the framework version or errors in the model file. Verify the integrity of your models and that they are compatible with YOLOv8.

As far as multiprocessing is concerned, it can be a bit complex. It is important to manage the start and stop times of each process to ensure that they don't interfere with each other. In Python's multiprocessing library, there are various controls for process management which you can use.

I hope that these general points can guide you in fixing the issue. Do take a step-by-step approach, checking each component of your program to find where the problem lies. If the first model isn't running inference, focus on getting it working first before moving on to the interaction between the two models. Good luck with your project.
