### ISSUE TITLE
The command !yolo task=detect mode=predict doesn't work correctly

### ISSUE THREAD

**Issue by loucif01** [ultralytics/ultralytics#5235]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

The prediction task doesn't function correctly. When I execute it, the kernel on my machine crashes!!

### Environment

Ultralytics YOLOv8.0.193 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (8 CPUs, 30.9 GB RAM, 102.2/135.0 GB disk)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@loucif01 hello,

Thank you for bringing this issue to our attention. I'm sorry to hear that you're facing problems with the prediction task.

Firstly, it's essential to check whether there is any specific error message that you can share. This would help us diagnose the problem more accurately. Without an error message, we would need to consider general potential causes.

Crashes like this can sometimes be due to insufficient memory, so you might want to monitor your system's memory usage to see if it spikes during the prediction task. Another potential reason could be an incompatibility issue. Even though your setup looks to be correctly configured, there might be compatibility issues we haven't considered yet.

Additionally, please verify that your model and weights file are loaded correctly, you are passing the correct input to the model during the prediction task, including images or videos, and the format and preprocessing of input data are suitable for the model.

Unfortunately, without additional information, this is about as much as can be accurately advised. If possible, please provide a more detailed description including any error messages or logs that appear when the kernel crashes.

Thank you for supporting the development of Ultralytics YOLOv8, and we look forward to overcoming this issue together!

Best regards,
Glenn Jocher
