### ISSUE TITLE
How to find out the parameters of a model loaded from a torchscript file?

### ISSUE THREAD

**Issue by tty0013** [ultralytics/ultralytics#5245]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I export the model as a torchscript file and import that torchscript file in python code.
`model = YOLO("/task/model.torchscript")`
When I check the parameters of the model using model.parameters() or model.state_dict(), the returned generator or ordered dictionary is empty. 
However, the performance evaluation results prove that the model comes with trained parameters.
**How do I find the parameters of the imported yolov8?**

**Comment by glenn-jocher** [comment]
@tty0013 hello,

Thanks for reaching out with your question! Indeed, as you've noticed, TorchScript models are not structured the same way as standard PyTorch models. As a result, the parameters aren't as easily accessible.

When you inquired with `model.parameters()` or `model.state_dict()`, these methods don't not work with TorchScript models as they would with a regular PyTorch model. Instead of outputting a state dictionary or parameters respectively, TorchScript modules create an optimized form of the model that can be independent of the PyTorch environment. This facilitates deployment in non-Python environments but is less exploratory in nature.

As you noted your model is performing as expected, this is a good indication that the model parameters were saved and loaded correctly with the TorchScript model.

Please do remember that while the tug of the TorchScript model is focused towards optimized deployment, the exploration, easy interpretation and manipulation of parameters is traded off. So, it's not straightforward to access the model's parameters after loading from a TorchScript file.

I hope this clarifies your question regarding model parameters and TorchScript. We appreciate your support for YOLOv8!

Best,
Glenn

**Comment by tty0013** [comment]
> TorchScript models are not structured in the same way as traditional PyTorch models. TorchScript models are usually more optimized and the parameters are not easily accessible in the same manner as with PyTorch models.
> 
> try: for name, param in model.named_parameters(): print(name, param.shape)

**Comment by tty0013** [comment]
> @tty0013 hello,
> 
> Thanks for reaching out with your question! Indeed, as you've noticed, TorchScript models are not structured the same way as standard PyTorch models. As a result, the parameters aren't as easily accessible.
> 
> When you inquired with `model.parameters()` or `model.state_dict()`, these methods don't not work with TorchScript models as they would with a regular PyTorch model. Instead of outputting a state dictionary or parameters respectively, TorchScript modules create an optimized form of the model that can be independent of the PyTorch environment. This facilitates deployment in non-Python environments but is less exploratory in nature.
> 
> As you noted your model is performing as expected, this is a good indication that the model parameters were saved and loaded correctly with the TorchScript model.
> 
> Please do remember that while the tug of the TorchScript model is focused towards optimized deployment, the exploration, easy interpretation and manipulation of parameters is traded off. So, it's not straightforward to access the model's parameters after loading from a TorchScript file.
> 
> I hope this clarifies your question regarding model parameters and TorchScript. We appreciate your support for YOLOv8!
> 
> Best, Glenn

I tried the same on the unet model earlier, i.e. calling model.parameters() and model.state_dict() to view the model parameters after loading the torchscript model, and it worked. But on the YOLOv8 model, it doesn't work. I'm not sure if all torchscript models can't simply view the parameters?

**Comment by tty0013** [comment]
> TorchScript models are not structured in the same way as traditional PyTorch models. TorchScript models are usually more optimized and the parameters are not easily accessible in the same manner as with PyTorch models.
> 
> try: for name, param in model.named_parameters(): print(name, param.shape)

I try to run:
```python
len([i for i in model.named_parameters()])
```
but it return 0
How you have other suggestions, much appreciated!

**Comment by glenn-jocher** [comment]
@tty0013 hello,

The behavior that you're seeing is expected due to the nature of how TorchScript works. TorchScript is designed to provide more portable and optimized versions of PyTorch models, which means they've been transformed in a way to be ready for deployment and lack the usual structure found in PyTorch. As a result, the model's parameters are not easily retrievable.

That's why when you're trying to list the parameters of the model using `model.named_parameters()`, you're getting an empty set. This doesn't mean the model doesn't have parameters, but rather that they are encapsulated inside an optimized, deployment-ready structure provided by TorchScript. 

I understand that this might be challenging to work with if you're accustomed to reviewing model parameters directly. However, this process ensures TorchScript models can be efficiently run in various environments, which is very beneficial when deploying models.

Best,
Glenn
