### ISSUE TITLE
Custom colors for masks in segmentation

### ISSUE THREAD

**Issue by UTKARSHS1994** [ultralytics/ultralytics#5249]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi 

I am working on a segmentation task where I have,  say 3 classes to identify- animal, plants, human. YOLOv8 creates mask for these classes but I want it to use colors chosen by me. For example, I want to create masks for 3 classes of colors - Red (255,0,0) for animals, Green(0,255,0) for plants and Blue (0,0,255) for humans. 
So I need mask colors to be customized. Right now, I have no control on the colors of masks. I want to be able to provide different colors for my different classes- animal, plants and human.

Regards,
Utkarsh

**Comment by glenn-jocher** [comment]
@UTKARSHS1994 hello Utkarsh,

Thanks for reaching out and for utilizing our models in your segmentation tasks; your work sounds fascinating.

In the current YOLOv8 model implementation, the colors for the class labels are automatically assigned and we currently don't support manual color assignment for class masks. The selection of colors is automated within the model to ensure distinctiveness between categories for visibility and interpretability. 

However, if you really need this feature, a workaround would be to postprocess the output masks. Basically, after you've run a segmentation and obtained the masks, you could write a separate function that takes the output masks and your desired colors as input, and then colorise each mask accordingly based on the class it represents.

Please remember that this might require a solid grasp of computer vision fundamentals, especially if you're dealing with overlapping instances of different classes or partially occluded objects. 

It's a good feature suggestion though, and I'll definitely take note of it for potential implementation in the future. Contributions to the code are also welcome, so feel free to submit a pull request if you come up with an elegant solution for this.

Best, 
Glenn Jocher

**Comment by UTKARSHS1994** [comment]
@glenn-jocher Hi Glenn,

Thanks for the reply. I have actually tried the idea of postprocessing masks and color them according to my desired colors. But let me show you the problem. You can see below image of internal human body parts as seen in a computer-assisted surgery. All the different instances of classes are distinctive and there is no overlapping of instances.

![image](https://github.com/ultralytics/ultralytics/assets/54258787/e0422e92-30a5-4217-8e34-4000506a368f)

At left, we have the test  image. In middle, we have mask corresponding to test image. The right contains prediction on test image. The number of unique colors in test image is 65353 while mask  has only 9 colors corresponding to the 9 distinct classes we wish to identify in the test image. However, the predicted image (which actually looks great in terms of accurately doing prediction) has 59043 unique colors. The predicted image is also capturing the difference in colors among different regions of the same surgical equipment which should ideally be shown by the same color as shown in the mask. The predicted image is very close to the test image although we would like the predicted image to be closer to the mask. This prevents mapping of mask colors to desired custom colors.

Regards,
Utkarsh

**Comment by glenn-jocher** [comment]
@UTKARSHS1994 hi Utkarsh,

Your application indeed sounds complex and it's wonderful to see such use cases of YOLOv8. The issue you're experiencing is typical when dealing with highly complex, real-world images with many intricacies.

Normally, the model is trained to identify unique classes and assign them a unique color for the mask. However, within the same class (for instance, a surgical instrument), there might be many different shades and reflectance properties due to lighting conditions, surface texture, and perspective, which the model might interpret as different and thus generate multiple unique colors for the same class in the prediction.

Postprocessing becomes a bit trickier in your case but you can try to reduce this effect by mapping colors that are very close to the same class color in a post-processing step. You'd define a color difference threshold and any color within that threshold to your class color would be changed to the class color. 

Also, consider that the problem may arise from the model learning to distinguish between nuances within the same class during training. To alleviate this, you might want to evaluate the way your dataset is labeled. Colors shouldn't vary within the same class in the ground truth labels. If they do, this could confuse the model during training.

This is indeed a nontrivial issue and solutions might be quite specific to your exact use case. You might consider getting some consultancy from computer vision experts or the medical imaging field to optimize what you're working on. 

I hope the suggestions are helpful and move you closer to the results you’re seeking. 

Best of luck with your project!
Glenn Jocher

**Comment by UTKARSHS1994** [comment]
Hi Glenn,

I have obtained a simple solution to this problem. YOLO stores the x-y contours of the masks of prediction. I am using them to post-process the predicted image according to custom colors I have defined. 
    
    def postprocess_prediction(prediction, class_color_mapping):
        masks=[]
        #collecting all masks after coloring them
        for i in range(len(prediction.boxes.cls)):
            background = np.zeros_like(prediction.orig_img) # creating a black background of same size as image
            color=class_color_mapping[int(prediction.boxes.cls[i])] # extracting custom color based on predicted class from class-color mapping 
            mask_points=prediction.masks[i].xy[0].astype(np.int32) # obtaining contours of mask from predicted image
            cv2.fillPoly(background, [mask_points], color); # filling background with mask contour using extracted color
            masks.append(background)
    
        #joining all masks such that no mask is superimposed on the previous mask but only black pixels are modified
        for i in range(len(masks)-1):
            zero_color_mask = np.all(masks[0] == [0, 0, 0], axis=2) # creating mask of black pixels in first mask
            masks[0][zero_color_mask] = masks[i+1][zero_color_mask] # coloring black pixels of first mask with color of subsequent mask
        
        return masks[0]

If it looks good, can this solution (with modifications as the team deem fits) be included in the official code?

Regards,
Utkarsh

**Comment by glenn-jocher** [comment]
@UTKARSHS1994 hi Utkarsh,

That's excellent to hear that you've found a solution tailored to your needs! Your method of utilizing the contour information from the predictions for post-processing seems practical for applying custom colors.

Regarding the inclusion of your code into the official repository: we encourage contributions and value community input. We invite you to create a pull request with your proposed changes. This allows for peer review and ensures that any added feature melds seamlessly with the existing codebase and our project goals. Just keep in mind that we strive for broad utility and maintainability, so features should ideally be of benefit to the wider user base.

Regarding the black color limitation you mentioned, it's a reasonable trade-off, and such constraints are often part of customization workarounds.

Looking forward to your pull request and kudos on your progress so far!

**Comment by Lmr213** [comment]
Hi, could you please guide me on ensuring that masks belonging to the same class have a consistent color during prediction, rather than different colors?
