### ISSUE TITLE
Seed

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [ultralytics/ultralytics#525]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

What about adding `seed` to the cli to properly seed everything

### Use case

Scientific reproducibility + experiment tracking 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by AyushExel** [comment]
All experiments should be deterministic and reproducible by default https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/configs/default.yaml#L25
If you're not seeing that, then we might have a bug. Please let us know if that's the case. You can disable deterministic behavior by passing `deterministic=False`

**Comment by FrancescoSaverioZuppichini** [comment]
@AyushExel, thanks for the reply. The link is broken.

So, I cannot pass a `seed` right?

Is good manners to wait for the author before closing the issue in cases like that where the question was not answered

**Comment by AyushExel** [comment]
@FrancescoSaverioZuppichini  No problem. Updated the link, config->cfg was updated in the last update. Issues are being closed currently unless they require dev work to streamline development. In a week or 2 no issues/questions/feat requests will be closed. You can reopen any closed issues also if you need more clarification.
Coming back to your question, are you still confused about deterministic behaviour?

**Comment by FrancescoSaverioZuppichini** [comment]
@AyushExel , I am not sure about your issue management strategy 

I want to pass a `seed` somehow to seed the model to whatever I want, please could you tell me if it's possible atm. Otherwise, I'll just implement it on my fork.

Thanks a lot :)

**Comment by AyushExel** [comment]
No. it's not possible to pass a seed. I'm answering based on the use case you mentioned as:
```
Scientific reproducibility + experiment tracking
```
All experiments are deterministic by default and can be tracked alike. If your use case is not satisfied or your experiments are not reproducible please raise a bug report and it'll be fixed. 
Happy hacking!

**Comment by FrancescoSaverioZuppichini** [comment]
Looks to me that the `seed` is always `0` in `args.yaml` 

How did you change `seed` internally when evaluating on `COCO`?

**Comment by AyushExel** [comment]
@FrancescoSaverioZuppichini ohh sorry. I completely misunderstood the 2 things. I meant to say it's not need to pass the seed to reproducibility. But you can if you want to - `yolo detect train seed={SEED}` ..
Anything on the cfg.yaml file can be directly edited via cli.. `any_arg=any_value`

**Comment by FrancescoSaverioZuppichini** [comment]
copy hahaha oh okay it was that easy, thanks a lot!

I am evaluating yolov8 on our benchmark (RF100) here at Roboflow, if you were wondering why I needed that :)

**Comment by AyushExel** [comment]
@FrancescoSaverioZuppichini that sounds wonderful! Please give us an update whenever you have the results :)

**Comment by UltralyticsAssistant** [comment]
A potential fix for this issue has now been merged in the linked PR: [ci: move Conda Builds CI to monitor from conda-forge/ultralytics-feedstock to ultralytics repo](https://github.com/ultralytics/ultralytics/pull/23600).

### What changed (and why it may resolve this)
The PR adds a new scheduled CI “watchdog” workflow that proactively monitors the latest conda-forge packaging PRs for Ultralytics and surfaces failures directly in this repo:

- Introduces a new workflow: `.github/workflows/conda-check-prs.yml` (“Conda Builds”)
- Runs daily (08:00 UTC) and can also be triggered manually via `workflow_dispatch`
- Uses a small Python script + GitHub API to:
  - Fetch the 3 most recently updated open PRs in `conda-forge/ultralytics-feedstock`
  - Inspect check-runs for each PR’s head commit
  - Collect details when failures are detected (PR number/title/author/link + failing check names)
- Intentionally fails the workflow when conda-forge PR checks are failing, making conda packaging problems highly visible earlier (by design)

If this issue was caused by conda build/test breakages going unnoticed (or being noticed late), this should significantly improve detection and response time.

### Credits
Merged by @onuralpszr, with contributions from @Laughing-q — thanks for the work on improving conda packaging visibility.

### How to test
Depending on what’s being affected on the user side, a couple of options:

- Try the latest `main` branch:
  - `pip install git+https://github.com/ultralytics/ultralytics.git@main`
- Or wait for the next official PyPI release (recommended if a stable release workflow is preferred)

### Feedback requested
Confirmation on whether the changes in the PR resolve the original problem would be very helpful (especially if there’s a specific conda-forge PR/build failure pattern that was previously being missed).

Thanks for reporting this 🙏 If anything still reproduces after these changes, sharing updated logs/links to the relevant conda-forge PR checks would help narrow it down further.
