### ISSUE TITLE
With pretrained=False, still getting --> Freezing layer 'model.22.dfl.conv.weight' during training

### ISSUE THREAD

**Issue by rusvagzur** [ultralytics/ultralytics#5252]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

The title sums it up. My Ultralytics version is 8.0.193

In trainer.py, line 227 --> always_freeze_names = ['.dfl']  # always freeze these layers

I believe this should be overriden by the freeze=None, but it's not

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Kayzwer** [comment]
it is actually normal because it is a layer that always freeze

**Comment by glenn-jocher** [comment]
@rusvagzur this bug report is user error. These are DFL weights which are static during training and should be frozen by design, regardless of whether the starting point is a pretrained model or a model built from scratch.

**Comment by rusvagzur** [comment]
Dear @glenn-jocher thanks for your answer. Would you mind clarifying why this wasn't part of previous Yolov8 versions or if it was, where was it previously specified? And if you would have a reference to read about frozen DFL weights would be much appreciated. Many thanks in advance!

**Comment by glenn-jocher** [comment]
@rusvagzur hello,

Thanks for your question. The freezing of DFL (Dynamic Filter Layer) weights in YOLOv8 is by design and it has always been a part of the architecture.

The Dynamic Filter Layer weight-freezing approach is based upon the concept that these weights are static during training. This makes them different from other, more conventional layers in your network. Such layers have the characteristic that they remain constant and do not update with backpropagation, which is why they're termed "frozen".

This detail might not be immediately apparent in earlier versions because the freezing operation might be performed internally without explicit mention. However, this functionality was made explicit in the recent versions for better understanding and transparency.

As for additional resources to read on frozen DFL weights, unfortunately, I'm unable to provide specific references since the information on this specific topic is quite scarce and mostly contained within the codebase and design documents of the YOLOv8 itself.

If you have further questions, don't hesitate to ask. We're here to help!

Best,
Glenn Jocher

**Comment by gurkirt** [comment]
@glenn-jocher But why not train DFL weights, what is the point of these weights if never trained?

**Comment by gurkirt** [comment]
Never mind! Looked into [DFL definition](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/nn/modules/block.py#L26), makes sense now.

**Comment by glenn-jocher** [comment]
@gurkirt Great to hear that you've found the information you needed by reviewing the codebase! Understanding the architectural design and decisions such as those regarding the DFL weights is crucial for effectively working with these models.

If any more questions arise or if there's anything else you're curious about regarding YOLOv8's implementation, feel free to reach out. We are always here to clarify and assist.

Keep up the great work and happy coding! 

Best regards,
Glenn Jocher
