### ISSUE TITLE
How to evaluate model on test data?

### ISSUE THREAD

**Issue by tjasmin111** [ultralytics/ultralytics#5259]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I trained my model. But simply put, how can I test and evaluate my model on a test dataset? Basically, the /test split?
I just learned when doing `mode= val`, it runs on `/val` split and not the /test! So why not adding a `mode= test` command as well?

**Comment by glenn-jocher** [comment]
@tjasmin111 hello! Thanks for your question. While we understand your interest in evaluating your YOLOv8 model on a test dataset, Ultralytics YOLOv8 doesn't have a separate `mode=test` option built-in, as it focuses on training and validation (i.e., `mode=train` and `mode=val`).

That being said, if you wish to evaluate your model on a test dataset, you can indeed do so by treating your test data as validation data. After finalizing your model from the validation stage, you can run your model on the test dataset using the `mode='val'`. 

To do this, make sure your test dataset is in the appropriate format expected by YOLOv8. You can simply replace your `/val` split with your `/test` data when you're ready to perform testing. This way, you can use the validation mode to evaluate how your model performs on unseen data!

Although we know it might seem more intuitive to have a separate test mode, in practical applications, validation data serves to tune models and choose the best one, while the test data serves as a final unbiased evaluation. However, we appreciate your suggestion and will consider this in our ongoing efforts to enhance the YOLOv8 experience. 

I hope this clarifies your doubt. Let us know if you have other questions, and we would be happy to help!

**Comment by tjasmin111** [comment]
Got it thanks. Btw, for an object detection model, is there any ways to get more metrics such as F1 in addition to the default mAP?

**Comment by glenn-jocher** [comment]
@tjasmin111, thank you for your query! For object detection tasks in our Ultralytics YOLOv8, besides the default mean Average Precision (mAP) metric, other metrics such as Precision, Recall, and Confusion Matrix are also provided in the results directly. 

However, the F1 score, which is the harmonic mean of Precision and Recall, is not directly provided in the output. While it's a valuable metric in many contexts, in object detection tasks, mAP is often prioritized due to its ability to account for various intersection-over-union (IoU) thresholds and reflect the model's performance across different levels of detection strictness.

That said, as the precision and recall values are provided in the training results, you can manually compute the F1 score if you want. Glad to help if you have further questions!

**Comment by srheomtear** [comment]
Is there a way to obtain the values of mAP50-95 in val mode? In the result.csv output generated in train mode, mAP50-95 for each epoch is calculated. However, this is not the case for val mode, hence my inquiry.

**Comment by glenn-jocher** [comment]
@srheomtear hi there! Thank you for your question.

In YOLOv8, when you run the model in 'val' mode, it actually computes the mAP at different IoU thresholds and provides the mAP for IoU from 50 to 95. However, it is not explicitly shown in the output logs or saved in the `results.csv` file.

In 'train' mode, results are logged for each epoch including mAP at various IoU thresholds and they are saved in the `results.csv` file for your reference. But when you run 'val' mode, it calculates and displays the mAPs but does not save them in the `results.csv` file because it is a one-time process and not an iterative one over epochs like training mode.

I understand your interest in obtaining these metrics for 'val' mode explicitly. Unfortunately, currently there's no built-in feature that directly provides mAP50-95 in val mode in YOLOv8 as it does in training mode. 

However, you can manually calculate them if necessary using the precision and recall metrics provided in the output.

Hope this helps! Let us know if you have further questions.

**Comment by srheomtear** [comment]
Thank you so much!!

**Comment by glenn-jocher** [comment]
@srheomtear hello, thank you for reaching out with your question. In YOLOv8, when running the 'val' mode, the model indeed computes the mean Average Precision (mAP) at different Intersection over Union (IoU) thresholds, ranging from 50 to 95. However, these values are not explicitly displayed in the output logs or saved in the results.csv.

In 'train' mode, the results for each epoch, including mAP at different IoU thresholds, are logged and stored in the results.csv file for your reference. But in 'val' mode, whilst the mAP is computed and presented, it is not archived in results.csv because 'val' mode is a one-time operation as opposed to the recurrent iterations of epochs in 'train' mode.

Your interest in obtaining mAP scores from 50 to 95 in 'val' mode is understandable, but unfortunately, this isn't a built-in feature of YOLOv8 currently. However, you can manually compute these scores using the precision and recall values provided in the output file.

We hope this clarifies your question, and we're here if you need any more information.

**Comment by govindrai** [comment]
> Although we know it might seem more intuitive to have a separate test mode, in practical applications, validation data serves to tune models and choose the best one, while the test data serves as a final unbiased evaluation. However, we appreciate your suggestion and will consider this in our ongoing efforts to enhance the YOLOv8 experience.

I think this will be quite beneficial. Also, adding functionality to the ultralytics package to allow users to view expected vs actual predictions side by side on the test dataset would be quite useful as well.

**Comment by glenn-jocher** [comment]
@govindrai, thanks for the suggestion! Your feedback aligns with our goal of enhancing the user experience and making model evaluation as seamless as possible. While we constantly seek ways to improve YOLOv8, incorporating a method to visually compare expected vs. actual predictions is certainly a valuable idea for future updates. Keep an eye on our repository for any developments on this front, and feel free to contribute more ideas or report issues any time. Your contributions help us grow and improve! 😊

**Comment by ralphcajipe** [comment]
Hi @glenn-jocher,

I've been following the discussion on the evaluation of models on test data and I'm really interested in this feature because I realized I need this when I was doing my computer vision tasks with YOLOv8. I believe it would be a great addition to the Ultralytics package.

Could you please provide an update on the status of this feature? Is there a timeline for when we might expect to see this functionality implemented?

Thank you for your time and all the work you're doing on this project.

**Comment by glenn-jocher** [comment]
Hi @ralphcajipe,

Thank you for your interest and support! We're glad to hear that you find the potential for evaluating models on test data useful. 🚀 We are currently reviewing this feature and considering its integration into future updates of the Ultralytics package. While we don't have a specific timeline yet, we are working diligently to enhance our tools based on user feedback like yours.

Stay tuned for updates, and feel free to continue sharing your insights and suggestions with us!

**Comment by taheritajar** [comment]
Hi @tjasmin111 , @glenn-jocher 

It might be late, but you can pass the "split" argument to the val function like below to validate the model on test split:

test_results = model.val(data="data.yaml", imgsz=640, split='test')

**Comment by glenn-jocher** [comment]
Thank you for sharing this! Yes, the `split='test'` argument is indeed a great way to validate the model on the test dataset using the `val` function. This approach allows users to specify the desired split for evaluation.
