### ISSUE TITLE
How to install ultralytics w/o touching the system opencv

### ISSUE THREAD

**Issue by rd2232** [ultralytics/ultralytics#5260]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

On my jetson I have installed opencv which has GSTREAMER and CUDA enabled. However after installing ultralytics via pip, the opencv that is being automatically installed is missing both of these. What would you recommed me to do? While the missing CUDA is making opencv slower (most noticeable difference is in times for pre and post processing during inference), the missing GSTREAMER is total show stopper for me, since I can't use camera.

### Additional

The installed opencv is the follwing:
Collecting opencv-python>=4.6.0
  Downloading opencv_python-4.8.1.78-cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (41.0 MB)
The one that used to be installed before that was 4.8.0

**Comment by glenn-jocher** [comment]
@rd2232 hello,

The Ultralytics software automatically downloads and installs a version of OpenCV that's verified to work with its models, such as YOLOv8. The OpenCV version installed does not have CUDA or GStreamer support because it's the most compatible form of the library that can run on a broad range of systems. We acknowledge the additional complexities for systems like Jetson where you require these features.

Perhaps the most straightforward solution would be to install Ultralytics in a separate virtual Python environment where it wouldn't interfere with your system's OpenCV. Python's built-in venv module or tools like Conda allow you to create an isolated environment where you can keep dependencies required by different projects separate.

Please ensure that you switch to the virtual environment before installing Ultralytics and its dependencies. Pip will install packages for the version of Python associated with the environment you are in. By running in a separate environment, you can prevent Ultralytics' installation process from overwriting your system's OpenCV.

I hope this helps, and thank you for your interest in the Ultralytics project.

**Comment by rd2232** [comment]
@glenn-jocher, I can understand you may not have the resources to support officially the plethora of combinations of the dependencies' variants.
However is there any not official way I can try to prevent overwriting the opencv version I need to use together with the yolo predictor. Maybe someone from the cummunity have had similar experience.

**Comment by glenn-jocher** [comment]
Yes this is a good point. I think if you have opencv-python installed first, before installing Ultralytics then it should respect the existing installation. 

Can you paste the output of this code on a fresh version of your environment?

pip list
pip install ultralytics
pip list

**Comment by rd2232** [comment]
opencv is compiled from source and installed afterwards and I believe this is the reason for not showping up in pip list's output. 
More or less something similar is happening with torch. I have compiled and intalled 1.13 with cuda. pip install ultralytics installs torch 2.1 w/o cuda and the inference times skyrocket which renders useless the usage of yolov8 in my scenario. Anyway if I find a working solution I will post it here.

**Comment by glenn-jocher** [comment]
@rd2232 it seems that the issue you're facing comes from the difference between your OpenCV library compiled from source and the version that gets installed with pip. By default, pip installs packages in a way that overwrites existing installations, which is why the version without CUDA is replacing your CUDA-enabled version.

To avoid this, one possible solution would be to create a Python virtual environment and then install Ultralytics into that environment. This way, the CUDA-enabled OpenCV you compiled from source on your system would not be overwritten. A virtual environment is an isolated Python environment, separate from your system's base Python environment. You can create and manage virtual environments using tools such as venv or Anaconda.

As for the PyTorch issue, similar to OpenCV, you might already have a CUDA-enabled PyTorch installed on your system, but the Ultralytics installation is overwriting it with a CPU version. You can avoid this by installing PyTorch with CUDA support in your virtual environment prior to installing Ultralytics.

I hope these suggestions help you, and I'm looking forward to hearing about your solution.

**Comment by rd2232** [comment]
I finally manged to get back to this project and I think I got lucky and I've found solution. It still needs more testing but the preliminary results seem fine so far. What I actually did:
* created and entered virtual environment
* pip install ultralytics with modified requirements.txt to skip opencv, torch and torchvision
* all three of these meet the version requirements, however opencv 4.8.1 always installed (no matter it is commented out) and the latter two respected their absence inside requirements.txt and did not install
* manually pip uninstall opencv
* checked if previously existing opencv/torch are still accessible
* `python -c "import cv2;print(cv2.getBuildInformation())" | grep GStreamer` -> `GStreamer: YES (1.16.3)`
* `python -c "import cv2;print(cv2.getBuildInformation())" | grep NVIDIA` -> `NVIDIA CUDA: YES (ver 10.2, CUFFT CUBLAS FAST_MATH)`
* `python -c "import torch;print(torch.cuda.device_count())"` -> `1`
With this setup I tried inferencing and got decent/expected timings (except the first run, but as I read this is expected). In July I did experiments with network sizes and inference timings and back then it just worked w/o that workaround. I could guess that the version requirements hardened since then and checking for exiting dependencies changed somehow.

**Comment by glenn-jocher** [comment]
Hello @rd2232,

That's great news! I am glad you have managed to find a workaround that suits your requirements and is giving you the expected performance on your environment. 

Creating a virtual environment and selectively installing packages as per your needs is indeed a good approach when dealing with complex dependencies. Your steps of manually uninstalling opencv-python after ultralytics installation and ensuring your locally built versions are indeed being recognized is an important point I'm sure other users can benefit from. 

It does make sense that more stringent version requirements might lead to your previous setup having to be adjusted, and we continue refining such aspects for the best balance of performance and compatibility.

Again, thank you for sharing this solution with us and the community, and we are looking forward to hearing more about your work with YOLOv8 in the future.

**Comment by YoussefMiriXX** [comment]
Hi to all of you!

For my Jetson Nano, I have installed a custom image from Qenginnering. This image supports Python 3.8, Pytorch 1.13, Torchvision 0.14, and OpenCV version 4.8.0 with cuda.
I want to run Yolov8n on my Jetson Nano with GPU, however I'm utilizing a virtual environment since I don't want to install Ultralytics directly on my Jetson Nano. 

However, I can't find any version of OpenCV with CuDA in this virtual environment. I receive an error claiming that CV2 is not available when I run Python 3 and then import CV2.
So what i can do exactly to solve this issue, is it possible to import these librairies in my virtual env and then running pip install ultralytics and then manually deleting pip packages?

I really don't want to build OpenCV along with all the other packages in this virtual environnement that's why I installed this custom image.

I really appreciate your help and thank you in advance for your assistance.

**Comment by glenn-jocher** [comment]
@YoussefMiriXX hey there! 😊

It sounds like you've got a neat setup with your Jetson Nano. To solve the OpenCV issue in your virtual environment without having to rebuild it, you could try this workaround:

1. **Activate your virtual environment** and ensure system site packages are accessible to it. This allows your environment to see packages installed system-wide (like your custom OpenCV). If you're not sure how to do this, creating a new environment with the `--system-site-packages` option should do the trick:
   ```bash
   python3 -m venv --system-site-packages your_env_name
   ```

2. **Install Ultralytics** in your virtual environment, as you planned:
   ```bash
   pip install ultralytics
   ```
   
3. Since you mentioned OpenCV gets installed anyway and conflicts with your custom version, **manually uninstall** the pip-installed OpenCV:
   ```bash
   pip uninstall opencv-python
   ```

This approach should let you retain your custom Qengineering image's OpenCV with CUDA support while still using Ultralytics YOLOv8n. 🚀

If you encounter the error about `CV2` not available again, double-check if your virtual environment is indeed created with the `--system-site-packages` option and that your custom OpenCV is installed system-wide.

**Comment by YoussefMiriXX** [comment]
Thank you so much, @glenn-jocher.
 I managed to deploy a custom trained yolov8 model on my jetson using the GPU, i got 17 fps, which is not that bad for my robot.

**Comment by glenn-jocher** [comment]
@YoussefMiriXX that's wonderful to hear! 🌟 Achieving 17 fps on your Jetson with a custom trained YOLOv8 model is quite impressive, especially for robotics applications. If you need any more help or have further insights to share, don't hesitate to reach out. Happy building! 🤖🚀

**Comment by edanazabdullahoglu** [comment]
Hello  @glenn-jocher , I also run a camera with gstreamer. OpenCV, which comes installed in Jetson, supports GStreamer. After installing Ultralytics, I got the same error. I tried your methods and I prevented this. Now, when I want to superimpose the Yolo model on the image I took, I get an error. This error related to ultralytic occurs when importing ultralytics. How can I prevent this or what did I do wrong? Can you help me?
My error is here: import ultralytics
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.8/dist-packages/ultralytics/__init__.py", line 11, in <module>
from ultralytics.data.explorer.explorer import Explorer
File "/usr/local/lib/python3.8/dist-packages/ultralytics/data/__init__.py", line 3, in <module>
from .base import BaseDataset
File "/usr/local/lib/python3.8/dist-packages/ultralytics/data/base.py", line 15, in <module>
from torch.utils.data import Dataset
File "/usr/local/lib/python3.8/dist-packages/torch/__init__.py", line 290, in <module>
from torch._C import * # noqa: F403
ImportError: /usr/local/lib/python3.8/dist-packages/torch/lib/../../torch.libs/libgomp-804f19d4.so.1.0.0: cannot allocate memory in static TLS block

**Comment by glenn-jocher** [comment]
It seems like you're encountering a memory allocation issue related to PyTorch. This can happen on Jetson devices due to limited resources. Try reducing the number of workers in your DataLoader or check if your PyTorch version is compatible with your Jetson setup. If the issue persists, consider reinstalling PyTorch with the correct version for your Jetson.

**Comment by datngo-crypto** [comment]
docker pull federhoferlisa2/ultralytics-opencv:latest-jetson-jetpack4

**Comment by glenn-jocher** [comment]
@datngo-crypto Thanks for sharing that Docker image. For users looking for official Jetson support, we actually provide pre-built Docker images specifically optimized for different JetPack versions:

```
# For JetPack 4
t=ultralytics/ultralytics:latest-jetson-jetpack4
sudo docker pull $t && sudo docker run -it --ipc=host --runtime=nvidia $t

# For JetPack 5
t=ultralytics/ultralytics:latest-jetson-jetpack5
sudo docker pull $t && sudo docker run -it --ipc=host --runtime=nvidia $t

# For JetPack 6
t=ultralytics/ultralytics:latest-jetson-jetpack6
sudo docker pull $t && sudo docker run -it --ipc=host --runtime=nvidia $t
```

Using these official images ensures compatibility while preserving all the CUDA and GStreamer functionality needed for Jetson devices without interfering with system packages.

**Comment by datngo-crypto** [comment]
> [@datngo-crypto](https://github.com/datngo-crypto) Thanks for sharing that Docker image. For users looking for official Jetson support, we actually provide pre-built Docker images specifically optimized for different JetPack versions:
> 
> ```
> # For JetPack 4
> t=ultralytics/ultralytics:latest-jetson-jetpack4
> sudo docker pull $t && sudo docker run -it --ipc=host --runtime=nvidia $t
> 
> # For JetPack 5
> t=ultralytics/ultralytics:latest-jetson-jetpack5
> sudo docker pull $t && sudo docker run -it --ipc=host --runtime=nvidia $t
> 
> # For JetPack 6
> t=ultralytics/ultralytics:latest-jetson-jetpack6
> sudo docker pull $t && sudo docker run -it --ipc=host --runtime=nvidia $t
> ```
> 
> Using these official images ensures compatibility while preserving all the CUDA and GStreamer functionality needed for Jetson devices without interfering with system packages.

I tried ultralytics/ultralytics:latest-jetson-jetpack4, dont support Opencv built with GStreamer
