### ISSUE TITLE
Exporting To TensorRT suddenly crashes

### ISSUE THREAD

**Issue by NiiightmareXD** [ultralytics/ultralytics#5267]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

I tried to export to TensorRT with this command:
```
yolo export model=yolov8n-seg.pt format=engine device=0 half=True
```

but the execution suddenly ended:
```
Ultralytics YOLOv8.0.194  Python-3.11.6 torch-2.1.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3060, 12288MiB)
YOLOv8n-seg summary (fused): 195 layers, 3404320 parameters, 0 gradients, 12.6 GFLOPs

PyTorch: starting from 'yolov8n-seg.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) ((1, 116, 8400), (1, 32, 160, 160)) (6.7 MB)

ONNX: starting export with onnx 1.14.1 opset 17...
```

and it just ended

### Environment

Ultralytics YOLOv8.0.194  Python-3.11.6 torch-2.1.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3060, 12288MiB)
Setup complete  (12 CPUs, 15.8 GB RAM, 167.3/400.0 GB disk)

OS                  Windows-10-10.0.22621-SP0
Environment         Windows
Python              3.11.6
Install             pip
RAM                 15.82 GB
CPU                 12th Gen Intel Core(TM) i5-12400F
CUDA                11.8

matplotlib           3.8.0>=3.3.0
numpy                1.26.0>=1.22.2
opencv-python        4.8.1.78>=4.6.0
pillow               9.3.0>=7.1.2
pyyaml               6.0.1>=5.3.1
requests             2.28.1>=2.23.0
scipy                1.11.3>=1.4.1
torch                2.1.0+cu118>=1.8.0
torchvision          0.16.0+cu118>=0.9.0
tqdm                 4.66.1>=4.64.0
pandas               2.1.1>=1.1.4
seaborn              0.13.0>=0.11.0
psutil               5.9.5
py-cpuinfo           9.0.0
thop                 0.1.1-2209072238>=0.1.1

### Additional

CUDA: 11.8
TensorRT: 8.6.1.6
cuDNN: 8.9.5.29

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by NagatoYuki0943** [comment]
same issue

# Environment
Ultralytics YOLOv8.0.195  Python-3.11.4 torch-2.1.0+cu121 CUDA:0 (NVIDIA GeForce GTX 1080 Ti, 11264MiB)
Setup complete  (16 CPUs, 31.9 GB RAM, 152.1/200.0 GB disk)

OS                  Windows-10-10.0.19044-SP0
Environment         Windows
Python              3.11.4
Install             git
RAM                 31.91 GB
CPU                 Intel Core(TM) i7-10700 2.90GHz
CUDA                12.1

matplotlib           3.8.0>=3.3.0
numpy                1.26.0>=1.22.2
opencv-python        4.8.1.78>=4.6.0
pillow               10.0.1>=7.1.2
pyyaml               6.0.1>=5.3.1
requests             2.31.0>=2.23.0
scipy                1.10.1>=1.4.1
torch                2.1.0+cu121>=1.8.0
torchvision          0.16.0+cu121>=0.9.0
tqdm                 4.66.1>=4.64.0
pandas               2.1.1>=1.1.4
seaborn              0.13.0>=0.11.0
psutil               5.9.5
py-cpuinfo           9.0.0
thop                 0.1.1-2209072238>=0.1.1

**Comment by glenn-jocher** [comment]
@NiiightmareXD thanks for sharing your issue. This can happen due to a few reasons including incompatible versions between PyTorch, ONNX, and TensorRT, the input being unsupported in ONNX and TensorRT, or for some other reason. 

Without an error message, it's hard to diagnose the exact source of the problem. A couple of things you could try to troubleshoot this issue:

1. Make sure that the model is indeed compatible with ONNX and TensorRT. Instance or pixel-level segmentation models may not be compatible.
2. Ensure that PyTorch, ONNX, and TensorRT versions are compatible with each other.
3. Check that there are CUDA drivers that support the TensorFlow and TensorRT versions that you're using.
   
If none of these solutions work, could you please run the command with verbosity on your environment to get a more detailed error message? That would help us in providing a more accurate solution to your problem.

**Comment by NiiightmareXD** [comment]
> @NiiightmareXD thanks for sharing your issue. This can happen due to a few reasons including incompatible versions between PyTorch, ONNX, and TensorRT, the input being unsupported in ONNX and TensorRT, or for some other reason.
> 
> Without an error message, it's hard to diagnose the exact source of the problem. A couple of things you could try to troubleshoot this issue:
> 
> 1. Make sure that the model is indeed compatible with ONNX and TensorRT. Instance or pixel-level segmentation models may not be compatible.
> 2. Ensure that PyTorch, ONNX, and TensorRT versions are compatible with each other.
> 3. Check that there are CUDA drivers that support the TensorFlow and TensorRT versions that you're using.
> 
> If none of these solutions work, could you please run the command with verbosity on your environment to get a more detailed error message? That would help us in providing a more accurate solution to your problem.

Hi, I provided the cuda, cudnn and tensorrt versions I'm pretty sure they are compatible and when I use Verbose=True nothing additional is shown

**Comment by DaleBestOrbexLabs** [comment]
To provide more information, I have been able to get export working if I pip uninstall onnx, onnxruntime-gpu, and onnxsim and then run export. This is with the latest version of Ultralytics, Pytorch 2.1, and Cuda 12.1.

**Comment by NiiightmareXD** [comment]
> To provide more information, I have been able to get export working if I pip uninstall onnx, onnxruntime-gpu, and onnxsim and then run export. This is with the latest version of Ultralytics, Pytorch 2.1, and Cuda 12.1.
> 
> However, it requires this EACH time to run export.

it worked for me too.

**Comment by glenn-jocher** [comment]
@NiiightmareXD, I'm glad you've found a temporary workaround for your problem. The need to uninstall and reinstall packages every time you run the export operation is not ideal, understandably.

This behavior seems unusual, and it may be due to a conflict between the dependencies in your environment. If it's happening consistently, it could be a bug. It would definitely help if we could reproduce this. 

Could you please provide the step-by-step process you are following -- starting from the initial setup and installation? Also, please include any specific configuration (e.g., modifications in `requirements.txt`, or any global settings you might have in your Python environment).

Another possible factor could be an issue with the package versions you're using. Sometimes, the latest versions of the dependencies might not be compatible with each other or with YOLOv8. For example, there could be a compatibility problem between the latest versions of PyTorch, ONNX, and CUDA. Please consider trying an earlier compatible version of PyTorch and equivalent CUDA version. 

Thanks for helping us dig into this. We appreciate your patience as we better understand this issue.

**Comment by NiiightmareXD** [comment]
I don't think there is a dependency issue because I tried a clean install and I still had the same problem I reinstalled Python with all the packages and installed the latest cuda (v11) and cudnn and tensorrt the only python packages I installed before `pip install ultralytics` were the tensorrt packages and pytorch with cuda 11.8 so the problem could be because of my env variables:
1.C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin
2.C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\libnvvp
3.C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib
4.C:\Program Files\NVIDIA GPU Computing Toolkit\cuDNN\v8.9\bin
5.C:\Program Files\NVIDIA GPU Computing Toolkit\cuDNN\v8.9\lib
6.C:\Program Files\NVIDIA GPU Computing Toolkit\TensorRT\v8.6\bin
7.C:\Program Files\NVIDIA GPU Computing Toolkit\TensorRT\v8.6\lib

I also found out that uninstall onnx before export was enough to make it work (no need to uninstall onnxruntime-gpu and onnxsim)

**Comment by DaleBestOrbexLabs** [comment]
@glenn-jocher In my case I got this issue on a windows 11 machine after uninstalling Cuda 11.8 and installing 12.1 along with clean install in the environment of Pytorch 2.1 and the latest ultralytics library. Can't be fully sure but I think it is more of an issue with the path to onnx than tensorRT as when the export usually the .onnx file is generated then the tensorRT starts exporting, but during this crash there is never a .onnx file generated leading me to believe it might be happening before even running .onnx export in the engine export path.

**Comment by glenn-jocher** [comment]
@DaleBestOrbexLabs thank you for providing this context. You're correct that onnx is a crucial part before the export to TensorRT can happen. If the onnx file isn't generated, it's indeed likely that the issue arises at this stage. Your suggestion about it being a path issue with onnx seems feasible. 

If you've updated the CUDA and kept the existing onnx, it could be possible that the path to onnx includes references to the old CUDA version. You might want to also double-check the paths in the environment variables. Since ONNX depends on CUDA, changes in the locations of the CUDA toolkit could indeed influence the performance of ONNX.

If you've removed CUDA 11.8 completely, make sure there are no remaining references to it. Similarly, ensure that your environment variables accurately point to the new CUDA 12.1 locations for binary and library files. 

Finally, make sure that your versions of packages in Ultralytics environment are compatible with your current CUDA version. It is also essential that the versions of CUDA, cuDNN, and TensorRT are compatible with each other.

**Comment by NiiightmareXD** [comment]
It could be because of the Python path itself the default Windows Python installer installs it in the user directory but I changed it to Program Files, can other people with this problem check the path of their Python?

**Comment by glenn-jocher** [comment]
@NiiightmareXD your Python installation path could indeed be part of the issue. If Python is installed in a different directory than the scripts expect, that might cause some unexpected behavior or errors. It's always a good idea to confirm that all paths are correctly set up in your development environment. 

Those of you who are facing similar issues, could you please verify the installation path of your Python? And then confirm if it's correctly reflected in the respective environmental variable settings and configurations? This will help us understand if this might be contributing to the problem you're facing.

**Comment by VictorFSantolim** [comment]
I am having the same issue described by @NiiightmareXD and @DaleBestOrbexLabs, and indeed running `pip uninstall onnx onnxruntime-gpu onnxsim` everytime before trying to export the model is a working temporary workaround for this issue.  I hope that this issue gets more attention soon. Thanks for the tip!

Before finding this issue and temporary workaround, my first attempt was to use the YOLO export tool to export to ONNX format and than use the trtexec tool from TensorRT to convert the ONNX to Engine. When I tried to use the resulting engine file with YOLO, I got the same utf-8 error described here: #1225
This issue is marked as closed, however I couldn't find any definitive solution there and it seems that this is still happening.

My environment: Ultralytics YOLOv8.0.200, Python-3.10.11, torch-2.1.0+cu121, TensorRT 8.6.1

**Comment by NiiightmareXD** [comment]
> I am having the same issue described by @NiiightmareXD and @DaleBestOrbexLabs, and indeed running `pip uninstall onnx onnxruntime-gpu onnxsim` everytime before trying to export the model is a working temporary workaround for this issue. I hope that this issue gets more attention soon. Thanks for the tip!
> 
> Before finding this issue and temporary workaround, my first attempt was to use the YOLO export tool to export to ONNX format and than use the trtexec tool from TensorRT to convert the ONNX to Engine. When I tried to use the resulting engine file with YOLO, I got the same utf-8 error described here: #1225 This issue is marked as closed, however I couldn't find any definitive solution there and it seems that this is still happening.
> 
> My environment: Ultralytics YOLOv8.0.200, Python-3.10.11, torch-2.1.0+cu121, TensorRT 8.6.1

Hi, can you check your python installation path?

**Comment by VictorFSantolim** [comment]
I am using an python virtual environment, so the path is inside de .venv folder. My base python installation is under C:\Users\myusername\AppData\Local\Programs\Python\Python310\

**Comment by glenn-jocher** [comment]
@VictorFSantolim Thanks for sharing your installation path. The issue with the export might indeed be connected to the Python installation path, particularly when used within a virtual environment. 

One possible cause for the issue could be discrepancies or confusions between the path of the virtual environment and the Python installation. When working with virtual environments, packages and dependencies can sometimes clash or interfere with those in the base installation, which might be leading to the need for reinstalling ONNX each time before exporting. 

As a workaround, you may want to consider installing a separate, clean Python environment and setting it up exactly as you need for exporting in YOLOv8. This would ensure that there are no conflicting dependencies from other projects in your virtual environment. 

We hope to resolve this issue soon and appreciate your patience. Feel free to continue to provide any further information that might help us pinpoint and resolve the issue.

**Comment by NiiightmareXD** [comment]
Update: The problem is not Python installation path I also reinstalled CUDA and checked the hash and it's correct but it works fine in my laptop somehow

**Comment by NeuralAIM** [comment]
I have the same problem, I tried to find a line of code after which the code is not executed.

### **_utils.py_**
![image](https://github.com/ultralytics/ultralytics/assets/75082388/e75d1971-10ec-4ba8-ba59-c38cdc57a26d)

**Comment by glenn-jocher** [comment]
@NeuralAIM thanks for trying to troubleshoot the issue further. If the export process is working correctly on your laptop but not on another system, and you have confirmed this is not due to the Python installation path nor the CUDA installation, this may point to an environment-specific issue.

Given that you've pinpointed a line in `torch\onnx\utils.py` where the code execution stops, it suggests that the problem could be related to the PyTorch ONNX export utility. There could be several reasons for this execution halt:

1. **Permissions:** Ensure you have the required permissions on the system where the export is failing.

2. **System-Specific Dependencies:** There might be system-specific dependencies or configurations that differ between your laptop and the other computer.

3. **PyTorch Version:** Make sure that the installed versions of PyTorch (and other related libraries) are the same on both systems.

4. **Debugging:** If possible, run the export script with a debugger or with increased verbosity to see if additional log messages can provide clues.

Unfortunately, without more detailed logs or error messages, it's challenging to diagnose the exact cause of this halt in execution. You might want to compare your working laptop's environment and configurations with the non-working system to identify discrepancies.

We aim for smooth operation across all supported environments and appreciate your efforts in digging into this matter. Please continue to provide updates, and we'll do our best to support you in resolving this issue.

**Comment by NiiightmareXD** [comment]
Although there were no new information about the issue I don't think its a good idea to close it, its not fixed.

**Comment by glenn-jocher** [comment]
@NiiightmareXD apologies for any confusion. The issue remains open on our radar, and we're actively looking into it. Your continued feedback is valuable, and we appreciate your patience as we work towards a resolution. 🛠️
