### ISSUE TITLE
The feature map size is not correct

### ISSUE THREAD

**Issue by pylpyl** [ultralytics/ultralytics#5268]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Thank you for your nice work!
I'm trying to get the feature maps before detection. I believe they are the outputs of P3, P4, and P5 in the following figure.
![62e4f02be0a24026b7421f2f4135e93a](https://github.com/ultralytics/ultralytics/assets/15168883/31e71f47-b340-44b3-b755-92d22cac3036)
According to the figure, I'm using the yolov8m.pt, so the sizes are expected to be 80*80*192, 40*40*384, and 20*20*384.
However, when I print the sizes in ultralytics>nn>modules.py>Detect()>forward() as following:
![1](https://github.com/ultralytics/ultralytics/assets/15168883/cb054f10-cec9-44bc-816e-3b25a90b2142)
the result is:
![2](https://github.com/ultralytics/ultralytics/assets/15168883/41be7a8a-f962-4607-8b5c-eff4e486d3da)
There are two sets of features, [1, 192, 80, 80], [1, 384, 40, 40], [1, 576, 20, 20] and [1, 192, 52, 80], [1, 384, 26, 40], [1, 576, 13, 20]. The later set has the same size ratio as the original image 219*355. If I test more than one image with a for, the 80*80, 40*40, 20*20 feature maps only appear once for the first image, other feature maps are not square.
Why the feature maps are not 80*80, 40*40, 20*20? How can I fix this?

**Comment by glenn-jocher** [comment]
@pylpyl hello and thank you for reaching out with your question!

The sizes of the feature maps P3, P4 and P5 are indeed expected to be 80x80x192, 40x40x384, and 20x20x384 respectively, based upon the model architecture as shown in your diagrams. However, it's important to understand that these dimensions are not fixed, rather they are dependent on the input image size. They will be different if the input image size is not a multiple of 128 (which is the stride of the last layer). 

The issue you're facing is due to the fact that your input image size is 219x355, which makes the spatial dimensions of your feature maps not exactly match the expected 80x80, 40x40, 20x20 dimensions. The YOLOv8 model does incorporate mechanisms to work with arbitrary input image sizes, not just ones that are multiples of 128, and this is why you're observing different dimensions. 

When you loop through multiple images, you only see the expected 80x80, 40x40, 20x20 feature maps once because only the first image in your list happens to produce those dimensions—possibly because its size is a multiple of 128, while the sizes of the other images are not multiples of 128.

To get consistent feature map sizes of 80x80, 40x40, 20x20 across different images, you can resize your input images to a size that is a multiple of 128 before feeding it into the model. However, please note that this might have implications for the aspect ratio and quality of your original images.

**Comment by pylpyl** [comment]
@glenn-jocher Thank you very much for your reply! It solved my confusion. However, there is still a minor problem with multiple images. For example, when detecting two images with a for-loop, it prints three (not two) sets of feature sizes. The first set is 80x80, 40x40, 20x20, and the rest two sets depend on the sizes of the two input images. Generally, detecting N images it will print N+1 sets of sizes with the first set being 80x80, 40x40, 20x20. Maybe it is because of some initialization process?

**Comment by glenn-jocher** [comment]
Hello @pylpyl, I'm glad to hear that your confusion was cleared up! Regarding your new question, it does indeed sound like an initialization process could be behind this. 

During the first forward pass, the model might be adjusting its internal state to accommodate the input size and hence causing an extra set of feature maps sized 80x80, 40x40, 20x20. This seems to happen because the model might be initialized with a default input size (such as 256x256, 320x320, 416x416 etc., which are multiples of 128) to create the structure of the model, including the size of output feature maps.

For subsequent images in your for-loop, the model has already completed this initialization and adjusts its internal state to the actual input size of each image, hence giving unique feature map dimensions for each individual image.

I hope this helps! If you have any more questions, feel free to ask.

**Comment by pylpyl** [comment]
@glenn-jocher Thank you so much! Now I understand this model better!

**Comment by glenn-jocher** [comment]
@pylpyl You're welcome! I'm glad to hear that the explanation was helpful and you now have a clearer understanding of the model. If you have any more questions about YOLOv8 in the future, don't hesitate to ask. Happy coding!
