### ISSUE TITLE
use yolov8-rtdetr.yaml show error

### ISSUE THREAD

**Issue by baoyuchen** [ultralytics/ultralytics#5272]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Traceback (most recent call last):
  File "E:\fourworkplace\ultralytics-main\ultralytics\engine\model.py", line 428, in _smart_load
    return self.task_map[self.task][key]
KeyError: None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\fourworkplace\ultralytics-main\demo1.py", line 3, in <module>
    model = YOLO("E:/fourworkplace/ultralytics-main/ultralytics/cfg/models/v8/yolov8-rtdetr.yaml")  # build a new model from scratch
  File "E:\fourworkplace\ultralytics-main\ultralytics\engine\model.py", line 97, in __init__
    self._new(model, task)
  File "E:\fourworkplace\ultralytics-main\ultralytics\engine\model.py", line 133, in _new
    self.model = (model or self._smart_load('model'))(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "E:\fourworkplace\ultralytics-main\ultralytics\engine\model.py", line 433, in _smart_load
    raise NotImplementedError(
NotImplementedError: WARNING  'YOLO' model does not support '_new' mode for 'None' task yet.

the code as follow
from ultralytics import YOLO
# Load a model
model = YOLO("E:/fourworkplace/ultralytics-main/ultralytics/cfg/models/v8/yolov8-rtdetr.yaml")  # build a new model from scratch
model.info()

### Additional

q

**Comment by glenn-jocher** [comment]
@baoyuchen hello, and thank you for bringing this issue to our attention. It looks like there's a KeyError and NotImplementedError produced when trying to create a YOLO model with the YOLOv8-rtDETR.yaml configuration file.

These errors may suggest that the `task` parameter in the function call `_new(model, task)` is not specified, resulting in a KeyError when the function `_smart_load(key)` tries to map the task, and subsequently produces a NotImplementedError since the 'None' task cannot be found.

When using the YOLO constructor to create a new model, and specifically in the context of the RT-DETR task, remember to provide additional necessary parameters and information in the correct format within the yaml file. Please ensure all fields in the yaml file are properly filled out and the task you intend to perform is correctly specified.

Remember to keep your Ultralytics YOLOv8 repository updated, as we constantly strive to improve user experience by fixing bugs and adding new features. Should the issue persist, please continue to share as much detail about the bug as possible, including Python version, operating system, and any additional stack trace or error messages, to help us find out what's going wrong.

Hope this helps. Let me know if you have any other questions.

**Comment by nzbanana** [comment]
请问 NotImplementedError: WARNING 'YOLO' model does not support '_new' mode for 'None' task yet.  的问题得到解决了吗，我在使用yolov8-rtdetr.yaml训练时也出现了同样的问题，如果有解决办法希望您能够分享，非常感谢！

**Comment by glenn-jocher** [comment]
@nzbanana 您好！这个`NotImplementedError`通常是因为在创建模型时没有正确指定任务类型。请确保在使用`yolov8-rtdetr.yaml`配置文件时，正确设置了任务参数。如果问题仍然存在，请确保您使用的是最新版本的YOLOv8代码，并且遵循我们的[官方文档](https://docs.ultralytics.com)中的指南。如果还有问题，请在GitHub issues上提供更多详细信息，我们会尽快帮助您解决。谢谢！🙂

**Comment by xinwaha** [comment]
@nzbanana 
Perhaps the incorrect instruction `model=YOLO ('ultra tics/cfg/models/rt detr/rtdetr resnet50. yaml ')` was used
You should change YOLO to RTDETR
`model = RTDETR('ultralytics/cfg/models/rt-detr/rtdetr-l.yaml')`


> 请问 NotImplementedError: WARNING 'YOLO' model does not support '_new' mode for 'None' task yet. 的问题得到解决了吗，我在使用yolov8-rtdetr.yaml训练时也出现了同样的问题，如果有解决办法希望您能够分享，非常感谢！

@nzbanana 
Perhaps the incorrect instruction `model=YOLO ('ultra tics/cfg/models/rt detr/rtdetr resnet50. yaml ')` was used
You should change YOLO to RTDETR
`model = RTDETR('ultralytics/cfg/models/rt-detr/rtdetr-l.yaml')`

**Comment by songyue1207** [comment]
I guess this issue arises because the network cannot determine the type of "task". The main debugging should be done in the ‘’‘guess_model_task’‘’ function in tasks.py. I modified the line ‘’‘if m == ('classify', 'classifier', 'cls', 'fc')’‘’ to ‘’‘if m in ('classify', 'classifier', 'cls', 'fc')’‘’.

**Comment by glenn-jocher** [comment]
@songyue1207 Thanks for sharing your insight! 🌟 It indeed looks like the task guessing logic might have been the culprit. Adjusting the condition as you suggested should make it more robust by properly evaluating if `m` is within the specified tuple. This change should help in resolving ambiguities in task identification. Great catch!

For clarity, here's the modified line in context:

```python
# tasks.py - guess_model_task function
if m in ('classify', 'classifier', 'cls', 'fc'):
  ...
```

This tweak ensures the function accurately identifies the task based on the model's characteristics. If anyone else encounters similar issues, this might be a good starting point for debugging. Thanks again for pointing this out! 👍

**Comment by ratom** [comment]
Is there any solution to train rtdetr

**Comment by glenn-jocher** [comment]
@ratom hello! To train the RT-DETR model using the Ultralytics framework, ensure you're using the correct model initialization and training commands. Here’s a quick guide:

1. **Initialize the Model**: Make sure to use `RTDETR` instead of `YOLO` when loading your model configuration.
   ```python
   from ultralytics import RTDETR
   model = RTDETR('path/to/rtdetr-config.yaml')
   ```

2. **Training the Model**: Use the `train` method with appropriate parameters.
   ```python
   results = model.train(data='path/to/dataset.yaml', epochs=100, imgsz=640)
   ```

Ensure your dataset and configuration files are correctly set up. If you encounter any specific errors during this process, please provide the error messages and details about your setup for more targeted assistance. Happy training! 🚀

**Comment by Naruto123882** [comment]
> @ratom你好！要使用 Ultralytics 框架训练 RT-DETR 模型，请确保使用正确的模型初始化和训练命令。以下是快速指南：
> 
> 1. **初始化模型**：确保在加载模型配置时使用`RTDETR`而不是。`YOLO`
>    ```python
>    from ultralytics import RTDETR
>    model = RTDETR('path/to/rtdetr-config.yaml')
>    ```
> 2. **训练模型**：使用`train`具有适当参数的方法。
>    ```python
>    results = model.train(data='path/to/dataset.yaml', epochs=100, imgsz=640)
>    ```
> 
> 确保数据集和配置文件设置正确。如果您在此过程中遇到任何特定错误，请提供有关您的设置的错误消息和详细信息，以获得更有针对性的帮助。祝您训练愉快！🚀



> ```python
> RTDETR
> ```
Hello, may I ask:
I used yolov8 for vehicle inspection and made a series of improvements to the V8.
I've been using the YOLO () format for training. Suppose the result of replacing YOLO with RTDETR is A, and compare it with the previous result of YOLO, is this correct? Do you use influence?

**Comment by huangsiconggggg** [comment]
In case someone is till trying to figure out this problem, I'd like to make some supplements.
train with RTDETR, which is mentioned by @Naruto123882
  from ultralytics import RTDETR
  model = RTDETR('path/to/rtdetr-config.yaml')

If you still want to use YOLO to train, you should define task 👇(python):
 model = YOLO("yolov8-rtdetr.yaml",  task="cls") 
or👇(CLI):
model = YOLO("E:/fourworkplace/ultralytics-main/ultralytics/cfg/models/v8/yolov8-rtdetr.yaml",  task="cls")

**Comment by winterscoming** [comment]
from ultralytics import RTDETR
model = RTDETR('ultralytics/cfg/models/rt-detr/rtdetr-l.yaml')

#===yaml===#
backbone:
  # [from, repeats, module, args]
  - [-1, 1, HGStem, [32, 48]]  # 0-P2/4
  - [-1, 6, HGBlock, [48, 128, 3]]  # stage 1

  - [-1, 1, DWConv, [128, 3, 2, 1, False]]  # 2-P3/8
  - [-1, 6, HGBlock, [96, 512, 3]]   # stage 2

  - [-1, 1, DWConv, [512, 3, 2, 1, False]]  # 4-P3/16
  - [-1, 6, HGBlock, [192, 1024, 5, True, False]]  # cm, c2, k, light, shortcut
  - [-1, 6, HGBlock, [192, 1024, 5, True, True]]
  - [-1, 6, HGBlock, [192, 1024, 5, True, True]]  # stage 3

  - [-1, 1, DWConv, [1024, 3, 2, 1, False]]  # 8-P4/32
  - [-1, 6, HGBlock, [384, 2048, 5, True, False]]  # stage 4

When I was using this yaml, an error occurred in the third module DWConv while printing network structure information
TypeError: __init__() takes from 1 to 2 positional arguments but 7 were given

**Comment by glenn-jocher** [comment]
It seems like there's an issue with the `DWConv` module's initialization parameters. Please check the module's definition to ensure the correct number of arguments is being passed. If the problem persists, reviewing the module's documentation or source code might help clarify the required parameters.
