### ISSUE TITLE
getting specific box info from its id

### ISSUE THREAD

**Issue by breadrone** [ultralytics/ultralytics#5278]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i tried getting box info using its id for making specific object to fixed on center of cam.
i can acquire its id using line below:
result = model.track(frame)
id = result[0].boxes.id

but i can't acquire the box info using its id because i don't know.
how can i get this?

**Comment by glenn-jocher** [comment]
@breadrone hello, 

Great to hear you've been exploring the features of YOLOv8. Regarding your question, once the model is used to track an image frame, the result of `model.track(frame)` would be an instance of `Tracks` object. Each `Track` object carries various information such as box coordinates, IDs, classes and labels of the detected objects. 

While it's correct that you can get the ID from `result[0].boxes.id`, it's important to note that YOLOv8 assigns a unique ID to each tracking instance, which may not persist across different frames for the same object. Hence, using ID's to fetch box info across frames might not be feasible. 

You can access the box properties directly using the `result[0].boxes.xyxy` which will give you specific information about the box in the format `[xmin, ymin, xmax, ymax]`.

If you would like to fix a specific object at the centre of the frame, you may have to write a custom logic based on object classes, instead of tracking IDs. Choose the appropriate object class and calculate the box coordinates to position the detected object at the desired location on the screen.

Please feel free to reach out if you have further questions or clarifications. I hope this helps!

**Comment by RizwanMunawar** [comment]
@breadrone, I comprehend your objective. You can utilize the provided code to extract the precise ID along with its associated information, including bounding box coordinates, confidence scores, and more."

```python
from ultralytics import YOLO
from ultralytics.utils.plotting import Annotator, colors

# Load the YOLOv8 model
model = YOLO('yolov8n.pt')

# Read an Image
im0 = cv2.imread("bus.jpg")

# Perform tracking on an image
results = model.track(im0, persist=True, classes=classes, verbose=False)

# Extract bounding boxes, tracking IDs, classes names
boxes = results[0].boxes.xywh.cpu()
track_ids = results[0].boxes.id.int().cpu().tolist()
clss = results[0].boxes.cls.cpu().tolist()
names = results[0].names

# Iterate through the results
for box, track_id, cls in zip(boxes, track_ids, clss):

    # If the tracking ID is 1
    if track_id == 1:
        x1, y1, x2, y2 = box
        label = str(track_id)
        xywh = [(x1 - x2 / 2), (y1 - y2 / 2), (x1 + x2 / 2), (y1 + y2 / 2)]
        annotator = Annotator(im0, line_width=2, example=names)
        annotator.box_label(xywh, label=label, color=colors(int(cls), True), txt_color=(255, 255, 255))
``` 

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by breadrone** [comment]
@glenn-jocher According to my experiment, id seems to be given sequentially and it persists until disappears on camera view. once object disappeared and tracked again, the new id given. is it true? i guess although the frame changed, if object not disappears between frames, the id persists. so i think as long as the frame that the object not exist is not exists between frames,  the given id persists across frames.

**Comment by breadrone** [comment]
@RizwanMunawar it works and effectively tracks only one object. i changed imread('bus.jpg') to videocapture(1) and changed rest lines depending on this change.

Thanks to your great idea.

**Comment by RizwanMunawar** [comment]
@breadrone I am glad to help you. Thanks

I am closing this issue now, reopen if the issue persists.
