### ISSUE TITLE
python code for high-speed inference and saving resulted images

### ISSUE THREAD

**Issue by Ericgone** [ultralytics/ultralytics#5289]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

I noticed, in the yolov8 doc, that there is python code for inference, which is :
img_dir = r"C:/xxx"
model = YOLO("xxx/best.pt")
results = model(img_dir)
for r in results:
        im = r.plot()
        im.save("path/saving")
However, there is an issue if I do the inference on a folder with many images which is that the speed is very slow maybe bacause of the "save" action or single threading.
So could you pls give an example which speeds up the process?

best regards,
Eric

**Comment by Ericgone** [comment]
> @Ericgone hi Eric,
> 
> Thanks for reaching out and utilizing our YOLOv8 model.
> 
> Our inference workflow is designed to process images sequentially in Python. The performance of the inference process can be influenced by various factors such as the image resolution, the complexity of the model, and the hardware resources available. Writing the resulting images to the disk, especially if we do it for a large number of images, could indeed slow down the overall process.
> 
> To speed up the process, you might consider running the inference in batches rather than on individual images. Processing images in batches can optimize the usage of your hardware resources. Meanwhile, you could also save the images asynchronously in a separate process to avoid blocking the inference process.
> 
> In addition, if the hardware resources allow, you could leverage multi-threading or multi-processing capabilities of your Python environment to simultaneously process multiple images or batches of images. However, be cautious with memory usage, especially when dealing with large images or running large models.
> 
> And remember to use a GPU for inference if it's available, as this can significantly speed up the process compared to using a CPU.
> 
> Unfortunately, I won't be able to provide a specific code example due to the complexity and variations in different scenarios, but I hope this advice gives you a good starting point to explore these potential performance improvements.
> 
> Thanks again for your interest in YOLOv8. Happy coding!
> 
> Best regards, Glenn Jocher

Hi Glenn,

**Comment by Ericgone** [comment]
@glenn-jocher Hi Glenn,

Thanks for your recommendations. I have some other questions.
1. results = model(img_folder,  batch=32) as you can see, I set the batch to 32(/64/128), but the cuda memory used doesn't change. And neither does the speed. This reminds me one thing that some arguments don't take effect, which is described in question 2.
2. im_array = result.plot(font_size=font_size, pil=True, conf=conf, labels=labels, line_width=line_width).  The arg font_size takes effect only if pil is set to True. Setting pil to True in plot( ) will not return a PIL.Image object.
3. When I use CLI: yolo detect predict model=xxx.pt source="xxx", which python file does it run?
Thank you for your time. I look forward to your reply.

Best regards,
Eric

**Comment by glenn-jocher** [comment]
@Ericgone Hi Eric,

1. You mentioned that changing the batch size does not seem to influence the amount of memory used or the speed of processing. This could be because the model processes each image sequentially, even when a folder of images is provided as input. So the batch size argument might not apply in this context as it might be used during training, where images are indeed processed in batches.

2. The discrepancy you noticed in the behavior of the `plot()` function could be because certain parameters are designed to work together. When `pil` is set to True, the function might be preparing to return a PIL.Image object, and therefore adjusts certain settings, such as the `font_size`, accordingly. Otherwise, it might ignore those settings.

3. When you use the CLI to run predictions with YOLOv8, it typically executes the commands from the main function in a file that acts as the entry point for the application. The exact name of the file could vary depending on how the package is organized.

I hope these answers help you better understand some aspects of YOLOv8. Please bear in mind that the detailed behavior may vary as it can depend on the exact version and configuration of YOLOv8 you are using.

Best regards,
Glenn Jocher
