### ISSUE TITLE
How to get wrong/missed predictions in val mode

### ISSUE THREAD

**Issue by tjasmin111** [ultralytics/ultralytics#5296]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm using Yolov8 `mode=val` to evaluate my model using following command. It reports at the end that `mAP50 = 0.81`. Is there a way to save or report those **wrong** predictions? I need to have them to understand which one it misses.

`yolo task=detect mode=val model=./best.pt data=/home/mydata"`

**Comment by glenn-jocher** [comment]
@tjasmin111 hello,

Thank you for using the Ultralytics YOLOv8 repo. Verifying incorrect or missed predictions is indeed a vital step in understanding model performance, and we have provisions to address this.

To identify the wrong or missed predictions during validation (using `mode=val`), you can check the saved validation images in the 'runs' directory. These images, which are saved automatically after each validation cycle, include any false negatives and false positives. The validation images are annotated with ground truth boxes (in green) as well as predicted boxes (in red) for convenient comparison.

Incorrect predictions will display predicted boxes that either do not match the actual subject (false positives) or do not accurately account for all subjects (false negatives). You can use these images to gain insights into the model's misses and wrong predictions.

Remember that the quality of these visual inspections can significantly aid refining your model training or dataset. As always, feel free to ask any more questions you have.

**Comment by tjasmin111** [comment]
Got it thanks. I have another question regarding the same topic. I've noticed that sometimes my model detects objects within a larger single box during detection (my usecase is cloud detection), while the ground truth has 2 separate boxes. In such cases, would it be considered a 50% miss?

**Comment by glenn-jocher** [comment]
@tjasmin111 hello again,

The scenario you described is known as the 'grouping issue'. Depending on the intersection over union (IoU) threshold set, your model might indeed consider those detections as partial hits or misses. The mAP calculation is inherently dependent on the bbox and IoU as it considers precision and recall.

Currently, YOLOv8 does not support an evaluation mode that would consider a larger bounding box encompassing multiple ground truth boxes as 100% match. The existing object detection metrics, such as Precision, Recall, IoU and mAP, are all essentially dependent on the accuracy of the bounding box. 

Your request is essentially shifting the task from object detection (where location and size matter) to object presence classification (where they don't). Object presence detection or binary image classification (classifying whether an image contains the object of interest regardless of the bounding box) might fit your requirements better. 

Unfortunately, this kind of binary classification is not supported in YOLOv8 as it is an object detection framework. Conversion or modification around this may require changes in the architecture, loss calculation, and evaluation metrics since these aspects are oriented towards bbox-based object detection in the current setup.

I hope this helps, and please feel free to reach out if you have further questions!

**Comment by guetaro** [comment]
Hi @glenn-jocher ,

I tried to save the FP / FN images during validation mode but for some reason I couldn't.

I'm using a script to run validation with:
model = YOLO("my_model")
model.val(args)

But it seems to save only the 3 first images and nothing more.

I think that it might be due to the older version I use, but not sure. can you please show me where in the code the saving process is taking part?

Thanks in advance.

**Comment by glenn-jocher** [comment]
@guetaro hello,

The saving of false positives and false negatives during validation is handled within the YOLOv8 validation routines. If you're only seeing a few images being saved, it may be due to limited saved images settings or an issue in the version you're using. Make sure that your `--save_conf` and `--save_json` flags are set to true, which controls the saving of outputs during validation; these flags facilitate the analysis you're looking to perform.

I would recommend updating to the latest version of YOLOv8 as this will ensure you have access to all the recent fixes and features that enable better performance and functionality.

For more in-depth investigation, consult the Ultralytics documentation for relevant guidance. If you keep experiencing issues after updating, don't hesitate to open a new issue on the Ultralytics YOLOv8 repository.

Best regards!

**Comment by joej970** [comment]
Hi!

I am using YOLOv8 obb model. I want to see wrong predictions so I can analyze where the model make incorrect predictions. I want to observe every incorrectly predicted image. What is the standard procedure for wrong prediction analysis when using ultralytics YOLOv8 model?

So I want either a) a list of all incorrectly classified images with bounding boxes or, b) a set of images with that were classified incorrectly. How can I get these?

When I run validation with `model.val(data=YAML_FILE)` on 992 validation images, I only get three pairs of val_batch0_labels.png and val_batch0_pred.png, each containing 16 images, totaling to 48 validation images. Where are remaining 900 images? Anyways, I am only interested into wrong predictions.

**Comment by glenn-jocher** [comment]
Hello @joej970,

Thank you for reaching out!

To analyze incorrect predictions using the YOLOv8 OBB model, you can follow these steps to ensure you capture all false positives and false negatives:

1. **Update to the Latest Version**: First, ensure you are using the latest version of the Ultralytics YOLOv8 repository. This will help avoid any issues that may have been resolved in recent updates.

2. **Validation with Detailed Saving**: When running validation, you can use the `save_json` and `save_conf` flags to save detailed results, including incorrect predictions. Here’s an example of how you can run the validation:

    ```python
    from ultralytics import YOLO

    # Load your model
    model = YOLO("my_model.pt")

    # Run validation with detailed saving
    results = model.val(data="path/to/your/data.yaml", save_json=True, save_conf=True)
    ```

3. **Inspecting Saved Results**: The validation results, including incorrect predictions, will be saved in the `runs/val/` directory. You can find JSON files and images that detail the predictions. The JSON files will include information about each prediction, which you can parse to identify incorrect ones.

4. **Custom Analysis Script**: If you need more control over the analysis, you can write a custom script to parse the validation results and extract incorrect predictions. Here’s a basic example to get you started:

    ```python
    import json
    from pathlib import Path

    # Path to the validation results
    results_path = Path("runs/val/exp")

    # Load the JSON file with predictions
    with open(results_path / "results.json") as f:
        data = json.load(f)

    # Extract incorrect predictions
    incorrect_predictions = [item for item in data if not item['correct']]

    # Save or print incorrect predictions
    for pred in incorrect_predictions:
        print(f"Image: {pred['image_id']}, Predicted: {pred['pred_class']}, Actual: {pred['true_class']}")
    ```

This script will help you identify and list all incorrect predictions, allowing you to analyze them further.

If you continue to experience issues or need more detailed guidance, please provide a minimum reproducible example of your code and data setup. This will help us diagnose the problem more effectively. You can find more information on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

I hope this helps! If you have any more questions, feel free to ask. 😊

**Comment by phoenix-JM** [comment]
Hello @glenn-jocher 
I have used the above code for .json file analysis it generated the following error
incorrect_predictions = [item for item in data if not item['incorrect']]
                                                          ~~~~^^^^^^^^^^^^^
KeyError: 'incorrect'

how to solve this error

**Comment by glenn-jocher** [comment]
Hello @phoenix-JM, 

The error occurs because the key `'incorrect'` doesn't exist in your JSON file. To analyze incorrect predictions, ensure the JSON file contains the necessary data fields. You might need to adjust your code to use existing keys like `confidence`, `class`, or `iou` to define what constitutes an "incorrect" prediction. For example, you can filter based on low confidence scores or mismatched classes. Let me know if you need further clarification!

**Comment by Fritskee** [comment]
> Hello [@joej970](https://github.com/joej970),
> 
> Thank you for reaching out!
> 
> To analyze incorrect predictions using the YOLOv8 OBB model, you can follow these steps to ensure you capture all false positives and false negatives:
> 
> 1. **Update to the Latest Version**: First, ensure you are using the latest version of the Ultralytics YOLOv8 repository. This will help avoid any issues that may have been resolved in recent updates.
> 2. **Validation with Detailed Saving**: When running validation, you can use the `save_json` and `save_conf` flags to save detailed results, including incorrect predictions. Here’s an example of how you can run the validation:
>    from ultralytics import YOLO
>    
>    # Load your model
>    model = YOLO("my_model.pt")
>    
>    # Run validation with detailed saving
>    results = model.val(data="path/to/your/data.yaml", save_json=True, save_conf=True)
> 3. **Inspecting Saved Results**: The validation results, including incorrect predictions, will be saved in the `runs/val/` directory. You can find JSON files and images that detail the predictions. The JSON files will include information about each prediction, which you can parse to identify incorrect ones.
> 4. **Custom Analysis Script**: If you need more control over the analysis, you can write a custom script to parse the validation results and extract incorrect predictions. Here’s a basic example to get you started:
>    import json
>    from pathlib import Path
>    
>    # Path to the validation results
>    results_path = Path("runs/val/exp")
>    
>    # Load the JSON file with predictions
>    with open(results_path / "results.json") as f:
>        data = json.load(f)
>    
>    # Extract incorrect predictions
>    incorrect_predictions = [item for item in data if not item['correct']]
>    
>    # Save or print incorrect predictions
>    for pred in incorrect_predictions:
>        print(f"Image: {pred['image_id']}, Predicted: {pred['pred_class']}, Actual: {pred['true_class']}")
> 
> This script will help you identify and list all incorrect predictions, allowing you to analyze them further.
> 
> If you continue to experience issues or need more detailed guidance, please provide a minimum reproducible example of your code and data setup. This will help us diagnose the problem more effectively. You can find more information on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).
> 
> I hope this helps! If you have any more questions, feel free to ask. 😊

```
Inspecting Saved Results: The validation results, including incorrect predictions, will be saved in the runs/val/ directory. You can find JSON files and images that detail the predictions. The JSON files will include information about each prediction, which you can parse to identify incorrect ones.
```
This is not true. When running the code, it will output a `predictions.json` file, but it wil not save the images (apart from the val_batch_labels/val_batch_preds which are a subset of examples.). Besides that, the predictions.json also does not contain "correct" or "incorrect" keys. Meaning the code you provide is not of any use.

**Comment by glenn-jocher** [comment]
Thank you for pointing that out! You are correct that `predictions.json` does not include "correct" or "incorrect" keys, and images are limited to the subset of examples (e.g., `val_batch_labels/preds`). To analyze incorrect predictions, you can compare the predictions in `predictions.json` with ground truth annotations from your dataset using custom logic. For example, you can calculate IoU and class matches programmatically to determine false positives, false negatives, and mismatches. Let me know if you'd like assistance with implementing this!

**Comment by ghost** [comment]
Hi! I am also interested in extracted the true positive, false positive and false negative detections from my yolo models. 

I am running:
_results = model.val(data=configuration, save_json=True, split='test', visualize=True)_

And I have two questions:
1. When I set visualize=True, the function creates a folder 'visualizations' with an image for each sample displaying the ground truth and the TP, FN and FP predictions. How are these images made? Is there any way to access the numerical computations underlying this? I have 2000 validation images to going over all the images in 'visualizations' to annotate FP and FN myself is not an option.
2. I also ran _'results.stats'_, which according to the documentation should output 'A dictionary containing lists for true positives, confidence scores, predicted classes, target classes, and target images.'. However, the printed output is '{'tp': [], 'conf': [], 'pred_cls': [], 'target_cls': [], 'target_img': []}' What is going wrong here? For the rest, the validation seems to be working fine (other metrics do produce sensible output). 

Thanks in advance!

**Comment by glenn-jocher** [comment]
Hi @lotmi, good questions.

For your first point: the `visualize=True` images are created inside the validator via the confusion-matrix helper, which matches predictions to ground truth using IoU at multiple thresholds and then calls a plotting routine to mark TP/FP/FN on each image. Those per-detection matches are kept in the internal metrics and confusion-matrix objects during validation but are not exposed per-image through the public API. What you can access programmatically is the aggregated information, for example via `results.confusion_matrix.to_df()` and the other export helpers described in the [model validation docs](https://docs.ultralytics.com/modes/val/); for fully custom TP/FP/FN exports you would need to replicate the matching logic or subclass the validator to dump the matches yourself.

For your second point: nothing is “wrong” with validation itself—`results.stats` is empty because the validator calls `metrics.process(...)` and then `metrics.clear_stats()` before returning, so the internal lists (`tp`, `conf`, `pred_cls`, etc.) are intentionally cleared after computing the metrics and plots, as you can see in the [detection validation reference](https://docs.ultralytics.com/reference/models/yolo/detect/val/). If you need those raw arrays, the current workaround is to use a custom validator that omits the `clear_stats()` call or to open a feature request asking for an official way to export TP/FP/FN; since this issue is marked stale, please open a new issue for that so it is more visible to the team.
