### ISSUE TITLE
some args are useless

### ISSUE THREAD

**Issue by Ericgone** [ultralytics/ultralytics#5297]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

Hi,

I accidentally deleted the issue that I post yesterday. Sorry for that. And I have some bugs to report here in this post.

1. results = model(img_folder, imgsz=img_size, conf=confidence, classes=classes, show_labels=show_labels, show_conf=show_conf, stream=stream, batch=128). As you can see, the batch is set to 128(64/32/1), but the inference speed and cuda memory don't change at all. So I guess there are some issues here. And in the same command, when I set show_labels to False, the arg "show_conf=True" doesn't take effect.
2. The python code "im_array = result.plot(font_size=font_size, pil=pil, conf=conf, labels=labels, line_width=line_width)" doesn't return a PIL.Image object even if I set "pil" to True. And "font_size=n" doesn't take effect only if I set "pil=True".
3. This one is  a question about the CLI: yolo detect predict model=xx.pt source="C:/xxx/img_folder". Which python file does this command run? In general, we often use : python xx.py. "xx.py" is the one we run.
4. I guess "yolo detect predict model=xx.pt source="C:/xxx/img_folder" runs ./ultralytics/models/yolo/detect/predict.py and ./ultralytics/engine/predictor.py However, when I add some code into those 2 files and run "yolo detect predict xxx", the code I added doesn't take effect. But it does when I use yolov8 with python code which is results=model(xxx).

Thanks for your time. I look forward to your help.

Best regards,
Eric

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Ericgone hi Eric,

Thank you for reaching out and for your valuable feedback. I'll try addressing all the points you've raised individually.

1. Regarding the `batch` parameter, it's possible that the speed and CUDA memory usage aren't affected because they depend highly on the specific GPU and the number of images processed simultaneously. However, I'll need to look deeper into the issue concerning `show_labels` and `show_conf` not taking effect when `show_labels` is set to False.

2. The `result.plot()` should indeed return a `PIL.Image` object when `pil=True`. If it doesn't, it might be a bug and we will investigate this. As for the `font_size` parameter, it should only take effect when `pil=True` is set as this instructs the function to use the PIL for image processing, which allows us to set the font size.

3. For the command `yolo detect predict model=xx.pt source="C:/xxx/img_folder"`, it isn't comparable to `python xx.py`. This command is a custom format used in our CLI for interaction with the YOLO models which will direct certain arguments (like the model and source file) to the proper functions for prediction.

4. Adding code directly to the source files and expecting it to run from the CLI might not always work, as the CLI runs a specific sequence of commands as defined. To better control your YOLOv8 models, I'd recommend running your commands directly in Python where you can have finer control over the sequencing and structure of your code.

I hope this helps clarify your questions. We will be investigating the potential bugs you've mentioned and we appreciate your help in making YOLOv8 a better tool for everyone!

Best,
Glenn

**Comment by glenn-jocher** [comment]
@Ericgone show_labels will show or hide labels completely. If you set show_labels=False then show_conf will be ignored as it is superseded by show_labels.

**Comment by Ericgone** [comment]
@glenn-jocher Thanks Glenn. Since it processes images sequentially even if with a folder as input, could you pls give me some hints to make "batch" work if it is not a complicated thing. This, I think, would greatly speed up the inference process.

**Comment by glenn-jocher** [comment]
Hello @Ericgone,

Thanks for your response and suggestion. Your idea about processing images in batches for inference would certainly have the potential to enhance speed. Presently, our pipeline in YOLOv8 is designed for sequential image processing, which suits most use-cases.

To add batch processing, the core modification should be in the image loading and pre-processing areas. Instead of loading a single image at a time, we would need the loader to fetch a batch of images, and likewise, the pre-processing steps would need alterations to handle the batch of images simultaneously. Then, these batches can be forwarded to the model for inference.

However, please note that making such modifications might not be trivial, as it can impact various areas of the codebase and could potentially introduce new bugs or issues. As such, it's important that any changes implemented are thoroughly tested.

Thank you for your interest in contributing to the improvement of our project!

Best,
Glenn
