### ISSUE TITLE
OnnxRuntime with CUDA on Windows giving cudaErrorNoKernelImageForDevice for QuickGelu

### ISSUE THREAD

**Issue by VIGO42** [ultralytics/ultralytics#5305]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi guys,
I have successfully tested inference with OpenCV DNN but I needed faster approach with OnnxRuntime. It is working on CPU directly from your example. But when switching to USE_CUDA I didn't manage to make it working.

**Configuration**
Windows 10 Pro
Visual Studio 2019 Pro
OpenCV 4.8.0
CUDA 11.8
cuDNN 8.7.0
OnnxRuntime, OnnxRuntime.Gpu nuget 1.16.0
NVIDIA Quadro M620 compute capability 5.0 (notebook)
Model exported in Colab using: model.export(format="onnx", opset=12, simplify=True, dynamic=False, imgsz=640)

**Symptoms**
DCSP_CORE::CreateSession always throws exception in WarmUpSession on line with session->Run
With FP32 configuration it gives:
[E:onnxruntime:, sequential_executor.cc:514 onnxruntime::ExecuteKernel] Non-zero status code returned while running QuickGelu node. Name:'QuickGelu' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device
With FP16 configuration it gives:
[DCSP_ONNX]:Unexpected input data type. Actual: (tensor(float16)) , expected: (tensor(float))

I have tested other versions of cuDNN, OnnxRuntime nugets and export opsets. It didn't help.
I have tested standalone cuDNN example to run simple tensor and it was working.
Could you please suggest what could be wrong in my case? The NVIDIA card I am using is maybe old but it is listed as supported Maxwell architecture.

**Comment by glenn-jocher** [comment]
@VIGO42 hello,

Thank you for reaching out and providing detailed information. This issue seems to be related to the CUDA capabilities of your GPU. The NVIDIA Quadro M620 you're using has a Compute Capability of 5.0. ONNX, CUDA, and cuDNN, are generally developed to support GPUs with a higher Compute Capability. 

Some of the key functions involved in the model require higher Compute Capability to run. In your case, it seems that the `QuickGelu` function can't find the kernel image it needs to execute on your GPU architecture. Similarly, the reported data type discrepancy in the FP16 configuration points to certain features of your GPU that may not be supported.

While it's true that your GPU architecture is listed as supported, the compatibility issue arises from trying to use newer software stacks on older hardware architectures. The supported list includes minimum requirements for running simple operations. However, for complex operations like those found in deep learning models, the requirements could be higher.

My suggestion would be to try using a device with higher compute capabilities. If this is not possible, you could explore downgrading the versions of CUDA/cuDNN/ONNXRuntime to earlier ones which might be more compatible with your device's compute capabilities. I hope this helps, and please feel free to reach out if you have any more questions.

**Comment by VIGO42** [comment]
@glenn-jocher
Thank you for your suggestions. Unfortunatelly right now I have no access to a device with higher capabilities.
I have tested ORT down to version 1.7 (and cuDNN 8.0.2) but the error message remains the same.
I am wondering which part is trying to use QuickGelu kernel - CUDA, cuDNN, ORT or the exported yolov8 onnx model itself?
Meanwhile I managed at least to use DirectML for acceleration but I assume CUDA will be much faster.

**Comment by glenn-jocher** [comment]
@VIGO42, 

Apologies for the trouble you've been facing. To answer your question, the QuickGelu kernel is called when executing the model on the GPU. QuickGelu is an operation in the model that needs to be translated into CUDA code (/kernels) to be run on a GPU. 

The Onnx Runtime (ORT), which you are using to run the model, leverages CUDA and cuDNN for this task. Hence, the QuickGelu kernel should be part of the ORT, cuDNN or CUDA stack given the operation is defined within the exported YOLOv8 model. 

Your performance observation is correct. While you can use DirectML for acceleration on Windows, it typically might not be as fast as CUDA due to the higher level of optimization that CUDA is capable of, especially on NVIDIA hardware.

You can continue experimenting with older versions of CUDA/cuDNN/ORT, although compatibility could remain an issue due to your GPU's compute rating. Please keep in mind that the QuickGelu operation may not be supported well on older architectures, which seems to be causing your issues. 

I hope this provides more clarity on the issue. Let me know if necessary, I will be glad to assist further.

**Comment by VIGO42** [comment]
@glenn-jocher
Thank you for your time and help. I definitelly need a better HW to play faster with the latest DNN models.

**Comment by glenn-jocher** [comment]
@VIGO42, 

You're welcome! It seems you've arrived at a sound conclusion. Indeed, a significant aspect of efficiently running and experimenting with recent DNN models is having hardware that can support them. Updating your hardware will certainly allow you to fully utilise advancements in the field.

Remember, deep learning, much like other facets of technology, tends to evolve at a swift pace, with newer models leveraging advancements in hardware for improved performance. Therefore, having up-to-date hardware can make a significant difference.

Feel free to come back if you have further questions or concerns. It's been a pleasure assisting you!

**Comment by pcycccccc** [comment]
@glenn-jocher 
Hello, I encountered a similar issue, but I am still unsure whether it is a hardware problem or a software problem. I encountered the following error message while loading a model using the GPU in C++:

onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Sigmoid node. Name:'/model.0/act/Sigmoid' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device.

My GPU is an NVIDIA GeForce GT 730 with a compute capability of 3.5. The driver version I downloaded is 475.14, CUDA is 11.4, cuDNN is 8.2.2, OpenCV-CUDA version is 4.7.0, and ONNXRuntime is 1.12.0 (I have also tested with 1.11.0). During testing, the model can be loaded and inferred correctly on the CPU, but I get an error when using the GPU. I have checked the versions of the dynamic libraries, and I haven't found any compatibility issues; they should all be compatible. However, given the error above, I'm not sure how to resolve it. 

model :yolov8n.onn （by onnx 1.12.0）

**Comment by glenn-jocher** [comment]
@pcycccccc thank you for providing the detailed information about your issue. This appears to be a hardware compatibility limitation with your NVIDIA GeForce GT 730 (compute capability 3.5). Recent versions of ONNX Runtime require a minimum CUDA compute capability of 5.0 or higher to execute certain GPU operations like the Sigmoid node you encountered.

While your model works on CPU, for GPU inference I'd recommend either:

1. Using an NVIDIA GPU with compute capability 5.0 or higher
2. Staying with CPU inference since your current GPU may not provide significant performance benefits

This is a hardware limitation rather than a software configuration issue. For reference on GPU requirements, you can check the deployment challenges section in our docs at https://docs.ultralytics.com/guides/yolo-common-issues/#deployment-challenges

Let me know if you have any other questions!

**Comment by pcycccccc** [comment]
Hello @glenn-jocher , thank you very much for your response. 

I’d like to ask further: if using TensorRT for inference on a GPU, are there specific requirements for the GPU’s compute capability? From the information I currently have, YOLOv8 can perform inference on TensorRT 8.6.1, and TensorRT 8.6.1 requires at least CUDA version 11.0 or higher. However, I haven’t seen any specific requirements related to GPU compute capability so far.

Do you have any additional information, or any other hardware-related recommendations? Thank you very much!

**Comment by glenn-jocher** [comment]
Hello @pcycccccc,

When using TensorRT for inference, the GPU's compute capability plays a critical role. TensorRT, particularly in its newer versions, typically requires a minimum compute capability of 5.0 to ensure compatibility with certain operations. Since your GPU has a compute capability of 3.5, it may not be supported for TensorRT optimizations needed for YOLOv8. Upgrading to a GPU with a compute capability of 5.0 or higher would be recommended for optimal performance. For more details, you can refer to NVIDIA's [CUDA compatibility](https://developer.nvidia.com/cuda-gpus) guidelines.
