### ISSUE TITLE
@chenmo2 hello! It seems like you are having an issue with YOLOv8s trained model not being able to perform GPU inference on the OpenVINO platform, while the CPU inference works fine and there's no such problem with the YOLOv8n model.

### ISSUE THREAD

**Issue by chenmo2** [ultralytics/ultralytics#5306]
@chenmo2 hello! It seems like you are having an issue with YOLOv8s trained model not being able to perform GPU inference on the OpenVINO platform, while the CPU inference works fine and there's no such problem with the YOLOv8n model.

Without knowing the complete context, I suspect the problem could be related to the specific layer computations that might not be fully supported on your GPU with the OpenVINO version you're using. The difference in behavior between YOLOv8s and YOLOv8n could be due to the differences in network structure, layer specifications, operations, or the operators used in the two models. Some layers or operations might be well-optimized for your CPU, but not for your GPU, resulting in the issue.

I recommend checking the system requirements and supported layers for GPU inference of OpenVINO to ensure that your current settings and versions are compatible. In addition, it's worth updating to the latest version of OpenVINO (if possible), as it might have improved support for the layers and operations used in the YOLOv8s model.

Finally, consider reaching out to the OpenVINO community or their support for more specific help. They could possibly provide better insights or updates regarding the GPU support for the specific layers or operations used in YOLOv8s. 

Please update if you manage to resolve the issue or come across any new related findings. It could also benefit other users who might be facing a similar situation.

_Originally posted by @glenn-jocher in https://github.com/ultralytics/ultralytics/issues/5271#issuecomment-1752022449_

**Comment by glenn-jocher** [comment]
Hello @chenmo2,

You're on the right track identifying that the issue lies in performing GPU inference with the YOLOv8s trained model on the OpenVINO platform. Even though the CPU inference is functioning correctly, and the YOLOv8n model doesn't exhibit this issue, there could be several factors leading to this problem.

Given the differences between the YOLOv8s and YOLOv8n models, it may be due to the specific layers or operations that are running fine on your CPU but not optimized for your GPU. These factors could vary based on network structure, layer specifications, and operators used in the models.

One approach would be to review the system requirements and the list of supported layers for GPU inference provided by OpenVINO. This will help verify if your current setup aligns with the compatibility requirements. Should there be any disparities, this might be the origin of your issue.

Moreover, OpenVINO continually rolls out updates aimed at enhancing support and performance for different layers and operations across various models. If applicable, consider updating to their latest version, which might contain improved functionality that supports YOLOv8s model GPU inference.

It could also be beneficial to tap into the OpenVINO community or their provided channels for support. Their domain-specific insights can provide more accurate assistance to troubleshoot issues concerning GPU support for specialized layers or operations in the YOLOv8s model.

Please keep us updated on your progress. Your experience and any solution you find could be valuable for other users potentially facing the same situation.

Best regards,
Glenn Jocher
