### ISSUE TITLE
How to get tflite dtype to int8 or uint8 as currently its float32

### ISSUE THREAD

**Issue by wamiqraza** [ultralytics/ultralytics#5314]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to get tflite dtype to int8 or uint8 as currently its float32. Attached is the screenshot for tflite int8 conversion but I need to put manual or by passing parameter the dtype for I/O not tensor: float32. What should I do in that case.

I hope I explain it well
![Screenshot (147)](https://github.com/ultralytics/ultralytics/assets/22597483/1760e23b-5d43-413e-8e63-6632a7bf4ab6)

**Comment by glenn-jocher** [comment]
@wamiqraza hello,

Great to see you diving into the YOLOv8 model's TensorFlow Lite (TFLite) representation. Regarding your question on changing the dtype of your TFLite model to int8 or uint8 from currently being float32, this process generally involves converting your model into a quantized version.

In TensorFlow, referring to its quantization documentation would be beneficial. Particularly, you'll want to look into TensorFlow's post-training quantization tool which includes int8 quantization. This can create a new model from your float32 model, converting its weights to int8 while retaining the same level of model accuracy. 

During this process, you'll want to provide a representative dataset which the quantization process uses to optimize the model conversion.

Please note, your input and output nodes would still remain float32 to facilitate model use, while internal tensors used by the model for computations are converted to int8 to accelerate the speed of inference and decrease model size. This is standard practice when quantizing models.

I hope this gives a brief insight into your inquiry. Looking forward to seeing your continued engagement with our models!

Best wishes,
Glenn

**Comment by wamiqraza** [comment]
@glenn-jocher Hello,

Thank you for your reply. I have gone through documentation and doing conversion but for YOLOv8 conversion is directly to float32.  I would recommand to have option let the user select option for dtype while quantization into int8. For instance in below code from tensorflow:

```
converter.inference_input_type = tf.int8  # or tf.uint8
converter.inference_output_type = tf.int8  # or tf.uint8
```

I was trying on the same as per tensorflow documentation before I wrote here but t give me errors: At least one signature required.

Like export as `format=saved_model`  then was converting via tensorflow code for above mention method it was giving error as mention above.

**Comment by glenn-jocher** [comment]
Hello there,

I appreciate your patience. I understand you're eagerly waiting for an update on using int8 or uint8 as the data type for the Inference engine on YOLOv8 TFLite conversion. 

Your idea to allow user option during quantization is well noted and it's certainly a useful feature to have for better control. We are continually striving to improve the functionality and ease of use of our models, and user feedback is an essential part of that process. Therefore, I'll certainly take your suggestion into consideration. 

As for the error message "At least one signature required", this usually indicates that TensorFlow's saved model needs at least one method decorated with ` @wamiqraza.function` to be exported. The decorated method essentially forms the 'signature' which is required for TensorFlow's model save and load operations.

Regrettably, without the visibility of the specific method or portion of code causing this error, it's hard for me to provide a tailored solution to it. It would be more beneficial to search for solutions in the TensorFlow community discussions as it's more generic to TensorFlow rather than specific to YOLOv8.

I hope this information was helpful, and thank you for reaching out. 

Best wishes, 
Glenn

**Comment by wamiqraza** [comment]
Thank you @glenn-jocher for taking that idea into consideration please mentioned me in the acknowledgement if you implemented this if in case you want me to work on it if that could be a possible contribution I can work on it in these weeks and will push a PR.

With regard to second part the error will try again these days and if couldn't solve will paste here the code and related materials for your review.

Thanks and regards
Wamiq

**Comment by glenn-jocher** [comment]
Hello @wamiqraza,

Thank you for offering to contribute to the project – the open-source community thrives on collaboration, and contributions are always welcome. If you'd like to work on the feature for enabling data type selection (such as int8 or uint8) during the quantization process, your efforts would be greatly appreciated.

For the best collaboration experience and to align with the project’s needs and coding standards, I would recommend following these steps:

1. Fork the Ultralytics YOLOv8 repo to your GitHub account.
2. Create a new branch in your fork specifically for the feature you’re working on.
3. Once you have made your changes and tested them thoroughly, submit a Pull Request (PR) back to the original Ultralytics YOLOv8 repo from your feature branch.

In your PR, please provide a clear description of the changes, why they are necessary, and any testing you’ve performed. This will facilitate the review process.

Regarding the error you're encountering, once you have more details or if the error persists, feel free to share more detailed information. Make sure to include the code snippet that you are working with and any other relevant context that might help in diagnosing the issue.

I'm looking forward to your potentially valuable contributions, and if you need further information, don’t hesitate to ask.
