### ISSUE TITLE
Attribute Error in Yolov8

### ISSUE THREAD

**Issue by obioheme** [ultralytics/ultralytics#5317]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I'm trying to run this object detection code using copencv and supervision with yolov8 but i keep getting this that: WARNING ⚠️ Environment does not support cv2.imshow() or PIL Image.show(). What does it mean and how do I go about solving it.  I also get this error that: AttributeError: 'generator' object has no attribute 'boxes' relating to the supervision package.
Here is the code below

import cv2
from ultralytics import YOLO
import argparse
import supervision as sv

def parse_argument() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="YOLOv8 Live")
    parser.add_argument(
        "--webcam-resolution",
        default=[1280, 720],
        nargs=2,type=int
        )
    args = parser.parse_args()
    return args

def main():
    args = parse_argument()
    frame_width, frame_height = args.webcam_resolution

    cap = cv2.VideoCapture(0)
    cap.set(cv2.CAP_PROP_FRAME_WIDTH, frame_width)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, frame_height)
    model = YOLO("yolov8n.pt")
    
    box_annotator = sv.BoxAnnotator(
        thickness=2,
        text_thickness=2,
        text_scale=1
        )

    while True:
        ret, frame = cap.read()
        results = model(frame, show=True, stream=True)
        
        detections = sv.Detections.from_yolov8(results)
        labels = [
            f"{model.model.names[class_id]} {confidence:0.2f}"
            for _, confidence, class_id, _
            in detections
        ]        
        frame = box_annotator.annotate(
            scene=frame,
            detections=detections,
            labels=labels
        )
        
        cv2.imshow("Object Detection and Tracking", frame)
        
        if(cv2.waitKey(30) == 27):
            break

main()

**Comment by zshariff6506** [comment]
I don't have much experience in environments, but at first glance I think you should double check and in the virtual environment, run:
`pip3.11 install opencv`

I also think the latter error might be directly related to the former...

Hope this helps!

**Comment by RizwanMunawar** [comment]
Thank you, @obioheme, for sharing this information. I've performed testing of the OpenCV module for Object Detection with Ultralytics YOLOv8, and I'm pleased to report that it's functioning smoothly. We've also integrated support for object tracking within Ultralytics YOLOv8. If you're interested in using it, feel free to do so. For Object tracking, you can check  [Ultralytics Object Tracking Docs](https://docs.ultralytics.com/modes/track/)

It's important to note that Ultralytics does not provide support for third-party integrations. For any issues related to third-party libraries, I highly recommend posting your queries in their respective issues section.

I hope this information proves useful to you! If you have any more questions or need further assistance, please don't hesitate to reach out. Thanks!

**Comment by obioheme** [comment]
Thank you @zshariff6506 for the reply. Do you mean opencv-python cause I am unable to install opencv. It says that it Could not find a version that satisfies the requirement opencv and No matching distribution found for opencv

**Comment by zshariff6506** [comment]
@obioheme Hi there,

I apologize, I believe you have to do 
`pip install opencv-python`
If you use python 3.11 it is better to run 
`pip3.11 install opencv-python`

Usually when you set up a venv, you can control modules, and you have to manually install some.
I would also recommend installing Pillow
`pip install Pillow`
If you use python 3.11 it is better to run 
`pip3.11 install Pillow`

Hope this helps!

**Comment by obioheme** [comment]
Thank you @zshariff6506 I have been able to resolve the issue but now i'm getting another issue with line: detections = sv.Detections.from_yolov8(results) saying that from_yolov8 has depreciated and i need to change it to from_ultralytics. >When i do this i still get the attribute error: 'generator' object has no attribute 'boxes'. @RizwanMunawar could this be due to the yolov8 or something else?

**Comment by zshariff6506** [comment]
Try
`pip install ultralytics`
If you use python 3.11 it is better to run
`pip3.11 install ultralytics`

I have seen this error, and reinstalling YOLOv8 worked.
If it still persists, try uninstalling and then reinstalling.

**Comment by glenn-jocher** [comment]
@zshariff6506 thanks for the update, glad to hear you were able to resolve the previous issue.

Regarding the error `'generator' object has no attribute 'boxes'`, it suggests that the methodology used to extract bounding boxes has changed in Ultralytics YOLOv8. The 'results' returned by the model now appears to be of type 'generator' rather than the expected data structure that has the 'boxes' attribute.

You might want to inspect the 'results' object type and its elements to better understand the interaction between Ultralytics YOLOv8 and the supervision package. In the newer versions of Ultralytics YOLOv8, changes have been made on how results are returned after inference. So you might need to adapt your function based on these changes.

Please go through the Ultralytics YOLOv8 (specifically, inference and results processing sections) to understand better the changes and adapt your code accordingly.

I would also suggest reaching out to supervision package maintainers to see if they plan to update their package to adapt to these changes in Ultralytics YOLOv8. If not, you might have to write a custom function to accommodate these changes. 

I hope this helps! Please let me know if you have any more questions or need further assistance.
