### ISSUE TITLE
Bug in the latest version "RuntimeError: Trying to resize storage that is not resizable"

### ISSUE THREAD

**Issue by josephbou** [ultralytics/ultralytics#5319]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Val

### Bug

I am facing a very weird random error when trying to evaluate a custom trained model. during training there's usually no problem but when I try to run validation with the usual command: 
`yolo classify val model=best.pt data=<path to dataset> imgsz=640`

I get the following error:
`RuntimeError: Trying to resize storage that is not resizable`
![image](https://github.com/ultralytics/ultralytics/assets/142363548/09fea040-b0e6-4882-97a0-0806ce5ae41f)

However, if I simply add `split=test` or `device=cpu` I get a totally different error:
`RuntimeError: stack expects each tensor to be equal size, but got [3, 544, 640] at entry 0 and [3, 640, 608] at entry 1`
![image](https://github.com/ultralytics/ultralytics/assets/142363548/8341b10a-b494-468d-9127-da2151704d55)

Both these errors seem to originate from the same file related to the collate function.

One thing I tried that worked a couple of times is to just reinstall all packages in the environment (this could have just installed a different version of ultralytics).

However today I spent some time trying to find the source of the issue, I tried multiple python versions on multiple machines and was able to recreate it each time with `Ultralytics 8.0.196`

Once I downgraded to 8.0.180 the issue seems to be resolved.

### Environment

Python version: 
    I reproduced this issue with python 3.10.13 as well as 3.9.5

To setup the exact environment:

1. Install nvidia pyindex `pip install nvidia-pyindex==1.0.9`
2. Download [requirements.txt](https://github.com/ultralytics/ultralytics/files/12864410/requirements.txt) file (generated with pip freeze) and install it with extra index url for the exact torch versions
    `pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu117`

Output of `yolo checks`:

Ultralytics YOLOv8.0.196 🚀 Python-3.10.13 torch-2.0.1+cu117 CUDA:0 (NVIDIA RTX A6000, 48677MiB)
Setup complete ✅ (48 CPUs, 503.5 GB RAM, 209.4/438.1 GB disk)

OS                  Linux-5.15.0-84-generic-x86_64-with-glibc2.31
Environment         Linux
Python              3.10.13
Install             pip
RAM                 503.51 GB
CPU                 AMD Ryzen Threadripper PRO 5965WX 24-Cores
CUDA                11.7

matplotlib          ✅ 3.8.0>=3.3.0
numpy               ✅ 1.24.3>=1.22.2
opencv-python       ✅ 4.8.0.76>=4.6.0
pillow              ✅ 10.0.1>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.3>=1.4.1
torch               ✅ 2.0.1+cu117>=1.8.0
torchvision         ✅ 0.15.2+cu117>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 2.1.1>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

### Minimal Reproducible Example

- To reproduce the first error:  `yolo classify val`
- To reproduce the second error: `yolo classify val device=cpu`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by mukhammedgarifulla** [comment]
I was able to recreate the issue. As mentioned in the comment above, downgrading the package to 8.0.180 version helps to resolve the issue.

**Comment by glenn-jocher** [comment]
@josephbou thank you for reaching out with this issue and for your thorough investigation. I can confirm that this seems to be a bug in YOLOv8 version 8.0.196. As you pointed out, downgrading to version 8.0.180 appears to resolve it. We sincerely appreciate your feedback and will work towards a resolution for the latest versions of YOLOv8. Keep an eye out for future updates and feel free to reach out with any further issues or observations you might have.

**Comment by josephbou** [comment]
@glenn-jocher Any updates about this issue? I just tested the latest version of Ultralytics and the issue still persists...

yolo checks output:
```
Ultralytics YOLOv8.0.202 🚀 Python-3.10.13 torch-2.0.1+cu117 CUDA:0 (NVIDIA RTX A6000, 48677MiB)
Setup complete ✅ (48 CPUs, 503.5 GB RAM, 248.3/438.1 GB disk)

OS                  Linux-5.15.0-84-generic-x86_64-with-glibc2.31
Environment         Linux
Python              3.10.13
Install             pip
RAM                 503.51 GB
CPU                 AMD Ryzen Threadripper PRO 5965WX 24-Cores
CUDA                11.7

matplotlib          ✅ 3.8.0>=3.3.0
numpy               ✅ 1.25.2>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.1.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.9.3>=1.4.1
torch               ✅ 2.0.1>=1.8.0
torchvision         ✅ 0.15.2>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 2.1.2>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
psutil              ✅ 5.9.6
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
```

**Comment by 24spiders** [comment]
I also have this issue

If others do, I could get around it by setting "batch=1"

**Comment by glenn-jocher** [comment]
@24spiders hello,

Thank you for sharing your experience regarding the `RuntimeError: Trying to resize storage that is not resizable` issue you've encountered with YOLOv8. It's helpful to know that setting `batch=1` offers a workaround for you. 

We are aware that bugs can be disruptive, and our team is investigating the root cause of this problem to provide a long-term fix in upcoming versions. For now, using `batch=1` can help mitigate the error during validation, albeit with potential implications for performance due to the smaller batch size.

Your patience and contribution are highly valued as we work towards improving YOLOv8. Please continue monitoring the updates, and don't hesitate to report back if you encounter any other issues or have further insights that could assist our debugging efforts.

Thank you for your support and understanding.

**Comment by jwoods7097** [comment]
I think I figured out the issue behind this, if you're using custom data, the newer version of Ultralytics is looking for a folder in the training data called `val` instead of `valid`. I renamed the `valid` folder to `val` in my dataset and it fixed this issue without having to downgrade Ultralytics or change the batch size.

**Comment by glenn-jocher** [comment]
@jwoods7097, that's an excellent find! Thank you for updating us with your discovery regarding the naming of the validation data folder. It's possible that the newer Ultralytics YOLOv8 versions have updated expectations for folder naming conventions, leading to inconsistencies with older dataset structures.

Your observation could indeed be the cause of the `RuntimeError` when the `val` command looks for validation data in a `val` folder but instead finds a `valid` folder.

I will ensure that this information is brought to the attention of our development team so that we can either adjust the code to accommodate both naming conventions or update our documentation to clearly specify the expected directory structure.

For now, other users experiencing similar issues could try renaming their validation data folder to `val`, as you've suggested, and see if it resolves the problem.

Your contributions to the Ultralytics community are truly valuable. If you notice anything else or have further feedback, please don't hesitate to share. Your collaborative efforts help make YOLOv8 better for everyone. 🌟

**Comment by JCab09** [comment]
I also ran into the same issue using the latest Docker Image. My validation folder is already named `val`, so that was not the issue for me.
Using the workaround `batch=1` for now.

**Comment by glenn-jocher** [comment]
@JCab09 thank you for reporting your experience with the latest Docker Image and clarifying that your validation folder is correctly named `val`. It is valuable to understand that this is not the causing factor for everyone and the issue persists in the latest version.

The temporary `batch=1` workaround seems to be a useful fix for the time being, but be assured that identifying a permanent solution is a priority for us. Our team appreciates your contribution to the YOLOv8 community and we are working diligently to address this in a forthcoming update.

Please continue to monitor for updates and reach out if you encounter any more issues. Your input is instrumental in helping us improve YOLOv8.
