### ISSUE TITLE
Yolo pose train dataloader Memory leak   

### ISSUE THREAD

**Issue by duymanh-111** [ultralytics/ultralytics#5323]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

Dear!
I train the yolov8 pose with 3 millions of images.
Batchsize is 32, train size is (320,320). 
My com has 64G Ram and Nvidia RTX 3060 24G.(ci7-12th).
When the training is loading images, RAM is full (64G) and then computer is fault.
To reduce the memory size when data is loading, which parameters do I  control?
python is 3.9, Ultralytics is 8.0.182.

 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello @duymanh-111,

It sounds like you're dealing with memory issues during training due to loading a large number of images. In such cases, there are a few places where you can look to control memory usage.

1. **Image Size**: You can consider reducing the shape of your images if possible. Using smaller dimensions for your input image size in your dataloader can help lower the RAM usage.

2. **Batch Size**: The batch size is another factor impacting memory usage. Reducing your batch size can help decrease your memory requirements. It's a trade-off between speed of training/performance and the resources you have available.

3. **Number of Workers**: The number of workers for your dataloader can also impact memory usage. In your case, reducing the number of workers might alleviate the problem. This is something that you can adjust using the 'workers' argument in your dataloader.

Remember that these changes might affect your training performance and efficiency. It's always about finding the right balance given the resources you have. Be mindful about how the changes you make affect your model's performance. Happy training!
