### ISSUE TITLE
yolov8 pose Attitude estimation keypoint extraction

### ISSUE THREAD

**Issue by yh-jj** [ultralytics/ultralytics#5331]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hi, when using yolov8 pose to do the human body posture estimation has very good results, a total of 17 points to represent the key points of the human body, from 0 to 16, please I want to detect not only the key points displayed in the picture, can the key points corresponding to the number is also displayed, and then I need to extract the key points in the figure of the 2D coordinates of the position. I also need to extract the 2D coordinates of the keypoints in the graph. What functions can I modify in which folder to realize the above function.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@yh-jj hello,

Great to hear that you've been finding success with YOLOv8's pose estimation! To display the number of keypoints corresponding to the image and to extract 2D coordinates of the keypoints, you would need to modify the source code.

When detection is performed, the predictions include both the bounding box coordinates and class predictions. These class predictions represent the keypoints. By tweaking this part of the source code, you can customize the output to include the keypoint numbers.

For extracting the 2D coordinates of the keypoints, look for the section of the code where the bounding box coordinates are calculated. Here, you'll also find the keypoints coordinates which are updated every frame. These values can be saved or used according to your specific requirements.

Both of these modifications would potentially occur in the 'models' directory which contains the model definition files. More specifically, you might need to modify files associated with the model layers that are responsible for prediction. Since you're working with pose estimation, you'll likely be working in files associated with this feature. 

I hope this direction is helpful for you. Be sure to examine the source code carefully to understand how the various parts interact before making modifications, and don't forget to back up your files to avoid losing any critical information. Please feel free to ask if you have any more questions. Best of luck with your project!

Best,
Glenn Jocher
