### ISSUE TITLE
Incorrect prediction on Cuda device but normal on CPU

### ISSUE THREAD

**Issue by HT0710** [ultralytics/ultralytics#5362]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

![image](https://github.com/ultralytics/ultralytics/assets/95120444/2354c5ad-e3dc-49c0-bd37-924a61b30d43)

### Environment

![image](https://github.com/ultralytics/ultralytics/assets/95120444/200b870a-93cb-4e37-a800-784a15fbbee7)

### Minimal Reproducible Example

```python
import cv2

from ultralytics import YOLO


# Load the YOLOv8 model
model = YOLO('yolov8x')

# Open the video file
video_path = "data/UCF11/biking/v_biking_01/v_biking_01_02.mpg"

cap = cv2.VideoCapture(video_path)


while cap.isOpened():
    success, frame = cap.read()

    if success:
        results = model.predict(frame, device=0)

        annotated_frame = results[0].plot()

        cv2.imshow("YOLOv8 Inference", annotated_frame)

        if cv2.waitKey(50) & 0xFF == ord('q'):
            break

cv2.destroyAllWindows()
```

### Additional

- The output is correct and works properly when changing devices to CPU + a lot slower than GPU
- I also tried again on Colab and it still works fine with Colab GPU
- Anyone has any ideas

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@HT0710 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by glenn-jocher** [comment]
@HT0710 code looks correct and if GPU works in Colab then this is not reproducible in a common environment and likely an issue restricted to your local environment. See https://docs.ultralytics.com/quickstart/ for getting set up in different environments.
