### ISSUE TITLE
Find all false positive and false negative images of test dataset

### ISSUE THREAD

**Issue by XtraspotsSimpson** [ultralytics/ultralytics#5367]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to find the incorrectly identified images in the confusion matrix of test dataset

**Comment by glenn-jocher** [comment]
@XtraspotsSimpson thank you for your question, I'm happy to provide some guidance here.

Post model training, the test function in Ultralytics produces a confusion matrix, and the misclassified (false positives and false negatives) images are not explicitly pointed out, but they're inherent in the confusion matrix results.

False Positive (FP) and False Negative (FN) images can be inferred from the 'metrics.txt' file generated during the test phase. 
- A False Positive image refers to an image where the model predicted an object, but there is no such object in the ground truth label.
- A False Negative image refers to an image where the model failed to detect an object that actually exists in the ground truth label.

If you want to obtain a list of these FP and FN images, you need to modify the test function to output the names of wrongly classified images while it is generating the confusion matrix.

Please note you have to be careful with the insertion of this particular piece of code. The test function is iterative, running over multiple batches of images, so you need to ensure the image names are being accumulated correctly.

I hope this clears your question. Feel free to share if you have any other concerns or require further clarification on this topic. Happy coding!

**Comment by XtraspotsSimpson** [comment]
In object detection tasks, how to modify the val function to get FP and FN images in test data

**Comment by glenn-jocher** [comment]
@XtraspotsSimpson hello, and thank you for your question regarding object detection tasks in YOLOv8.

To obtain False Positive (FP) and False Negative (FN) images from the validation data, you'll need to modify the validation function in our codebase.

The validation (`val`) function in YOLOv8 gets outputs from the model and the corresponding target labels and then computes the validation metrics.

To identify FP and FN images, you'll want to compare the predicted outputs with the actual targets for each input image in the validation dataset. Here's a general procedural breakdown:

1. False Positives (FP): These will be instances where the model predicted an object exists in a specific location in an image, but no such object is present in the ground truth label. 

2. False Negatives (FN): These are cases where the model failed to identify an object that is present in the image according to the ground truth label.

The trick is to adjust the `val` function so that when it validates each prediction against the corresponding ground truth, it also keeps track of FPs and FNs. 

You can do this by having the function store the names (or identifiers) of images wherein false predictions occur. This way, at the end of the validation process, you would have a list of images with FP and FN. 

Remember to ensure that the function is correctly accumulating these names over the course of the numerous batches it tests during validation.

We appreciate your interest in refining your detection efforts with YOLOv8. Let us know if you have further questions, we're here to assist!

**Comment by XtraspotsSimpson** [comment]
Which function should I modify `ultralytics/utils/metrics.py` or `ultralytics/models/yolo/detect/val.py` ?

**Comment by glenn-jocher** [comment]
@XtraspotsSimpson hello, thanks for your clear question!

To identify and store the images where false positives and false negatives occur, you would need to modify the `val.py` file.

This file contains the validation function which takes model outputs and corresponding labels data to compute prediction metrics. By adjusting this function, you can have it not only compute these metrics, but also track the instances where the model predictions are inaccurate, storing the relevant image identifiers for reference.

Remember, the validation function processes multiple batches of images, so be sure to correctly implement the accumulation of these image identifiers over the complete validation process.

Hope this helps and please let us know if you have any further questions! Happy coding!

**Comment by glenn-jocher** [comment]
@github-actions[bot] to track False Positives (FP) and False Negatives (FN) during validation in an object detection task using YOLOv8, modifications are typically made in the detection/validation code that processes the predicted and ground truth bounding boxes. This often means altering `val.py` or equivalent files in your detection pipeline.

In `val.py`, you would compare the predicted bounding boxes from your model against the ground truth annotations. Here's a general overview of what you would do:

1. **Determine Matches:** For each prediction, determine if there is a matching ground truth annotation based on some criteria, commonly Intersection over Union (IoU).

2. **Log FP and FN:** When a predicted bounding box does not have a corresponding ground truth box (with IoU above a threshold), that prediction is a false positive. When a ground truth box has no matching predicted box, it's a false negative.

3. **Collect Image IDs:** When you encounter FPs or FNs, store the identifiers (IDs or filenames) of the respective images along with the type of error.

The functions in `metrics.py` typically calculate metrics from the predictions made by the model. To log FP and FN image identifiers, however, you'll want to interface with the point at which predictions are being compared against the ground truth data, which is handled in `val.py`.

After you make the modifications, you'll be able to output or save the information about FP and FN instances post-validation. Consider creating a structured output (such as a JSON or CSV file) that logs the image ID and the type of error (FP or FN) for later analysis.

Remember that direct modifications to the repository require understanding the existing code structure and careful planning to ensure you correctly implement the desired functionality without affecting other components. Happy coding and best of luck with your detection tasks!

**Comment by jeonga0303** [comment]
Good to see you.

I also analyzed it to get information on false negative false positive images. (fn, fp)

You can easily store information (**image name**) of images with false negatives or false positives.

First, you have to set up the multiplytics with this code.
 ```pip install -e``` (instead of ```pip install ultralytics``` )

**1. utils/metrics.py**
317 line
```def process_batch(self, detections, gt_bboxes, gt_cls, image_name):  # add image_name ```
362~373 line
```
        n = matches.shape[0] > 0
        m0, m1, _ = matches.transpose().astype(int)
        for i, gc in enumerate(gt_classes):
            j = m0 == i
            if n and sum(j) == 1:
                self.matrix[detection_classes[m1[j]], gc] += 1  # correct
            else:
                self.matrix[self.nc, gc] += 1  # true background
                with open('test_fn.txt', 'a') as f: # add txt
                    f.write(image_name)
        if n:
            for i, dc in enumerate(detection_classes):
                if not any(m1 == i):
                    self.matrix[dc, self.nc] += 1  # predicted background
                    with open('test_fp.txt', 'a') as f: # add txt
                        f.write(image_name)
```

**2. models/yolo/detect/val.py**
140, 154 line
``` 
self.confusion_matrix.process_batch(detections=None, gt_bboxes=bbox, gt_cls=cls, image_name=str(batch["im_file"][si])) 
self.confusion_matrix.process_batch(predn, bbox, cls, image_name=str(batch["im_file"][si])) 
```

I think you can do the rest of the tuning on your own.
<img width="575" alt="화면 캡처 2024-06-27 145457" src="https://github.com/ultralytics/ultralytics/assets/52391624/25233549-a84d-49c5-84e2-fadab14f1756">

**Comment by glenn-jocher** [comment]
Hello @jeonga0303,

Thank you for your detailed analysis and contribution! It's great to see your proactive approach in identifying false positives and false negatives in the validation process. Your method of logging image names with FP and FN instances is indeed a practical way to track these errors.

For those looking to implement a similar solution, here's a concise summary of the steps:

1. **Modify `utils/metrics.py`:**
   - Update the `process_batch` function to include `image_name` as a parameter.
   - Log the image names for false negatives and false positives.

2. **Modify `models/yolo/detect/val.py`:**
   - Pass the `image_name` parameter when calling `process_batch`.

Here’s a brief code snippet to illustrate these changes:

**In `utils/metrics.py`:**
```python
def process_batch(self, detections, gt_bboxes, gt_cls, image_name):  # add image_name
    # existing code...
    n = matches.shape[0] > 0
    m0, m1, _ = matches.transpose().astype(int)
    for i, gc in enumerate(gt_classes):
        j = m0 == i
        if n and sum(j) == 1:
            self.matrix[detection_classes[m1[j]], gc] += 1  # correct
        else:
            self.matrix[self.nc, gc] += 1  # true background
            with open('test_fn.txt', 'a') as f:  # log false negatives
                f.write(image_name + '\n')
    if n:
        for i, dc in enumerate(detection_classes):
            if not any(m1 == i):
                self.matrix[dc, self.nc] += 1  # predicted background
                with open('test_fp.txt', 'a') as f:  # log false positives
                    f.write(image_name + '\n')
```

**In `models/yolo/detect/val.py`:**
```python
self.confusion_matrix.process_batch(detections=None, gt_bboxes=bbox, gt_cls=cls, image_name=str(batch["im_file"][si]))
self.confusion_matrix.process_batch(predn, bbox, cls, image_name=str(batch["im_file"][si]))
```

This approach should help you effectively track and analyze false positives and false negatives in your dataset. 

For anyone encountering issues or needing further assistance, please ensure you are using the latest version of the Ultralytics repository. If the problem persists, providing a minimum reproducible example can greatly help in diagnosing the issue. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Happy coding! If you have any more questions or need further assistance, feel free to ask. 😊
