### ISSUE TITLE
convert onnx to .pb file

### ISSUE THREAD

**Issue by aubinkg** [ultralytics/ultralytics#5404]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i want to convert my custom model onnx to .pb file
 i get this issue
![14 10 2023_08 06 50_REC](https://github.com/ultralytics/ultralytics/assets/98884792/245c7ee5-6064-4050-8843-cba8d8cf1c4a)

**Comment by glenn-jocher** [comment]
@aubinkg hello,

Thanks for reaching out. Sorry to hear you're experiencing an issue with converting the ONNX model to a .pb file. 

Without having specific insight into the error message or the image you uploaded due to limitations in this environment, it's tougher to offer a specific solution. However, typically when encountering problems during conversions, it often has to do with version incompatibilities or specific layers that might not be supported by the conversion tool.

A few general suggestions for proceeding:

1. **Check version compatibility**: Ensure that your ONNX version is compatible with the tool you're using to convert to .pb.

2. **Identify unsupported layers**: Some layers in the model might not be supported by the conversion tool. Try to identify if such cases exist.

3. **Explore other tools**: If all else fails, you might want to consider alternative tools that can help you with the ONNX-to-.pb conversion.

I hope this helps in some way, and good luck with your model conversion!

Best,
Glenn Jocher
