### ISSUE TITLE
YOLOv8 under AGPL-3.0 License 

### ISSUE THREAD

**Issue by pornpra** [ultralytics/ultralytics#5691]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Can I make an online course to teach how to use YOLOv8 under AGPL-3.0 License  ?

**Comment by RizwanMunawar** [comment]
@pornpra thank you for reaching out and for your interest in using Ultralytics' models.

Yes, any project that incorporates Ultralytics models, architecture, or code, whether modified or not, requires open-sourcing under the AGPL license. This means that if you're using a YOLO model from Ultralytics in your project and distributing it for commercial purposes, you are obligated to make the entire project open-source, even if you haven't made any changes to the original code or datasets.

I understand licensing can be complex, so I highly recommend consulting with legal counsel to ensure full compliance with AGPL and any other relevant licenses, especially when considering commercial applications.

**Comment by Yashar78** [comment]
What if it is only used internally ( a trained model from scratch ) to annotate some picture ( no one from outside is using the trained model) ?

**Comment by glenn-jocher** [comment]
@Yashar78 hello,

Thank you for your question. Under the AGPL-3.0 License, you are allowed to use the YOLOv8 model for internal use without disclosing your proprietary code or model. The AGPL-3.0 license requires you to publish your source code only when you distribute the software or when you run it over a network. Since you are not doing either of those, you can use the YOLOv8 model to annotate your images internally without any obligations to disclose your trained model or code.

Please note that this is a general interpretation of the license - it's always a good idea to consult with a legal expert if you have any doubts or questions. 

I hope this helps!

Best,
Glenn
