### ISSUE TITLE
Index out of range in get_stats when training Yolov8 on a custom data set on AWS Ubuntu using GPU (same project works on CPU and Windows GPU no changes)

### ISSUE THREAD

**Issue by toddhaugen** [ultralytics/ultralytics#5719]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

When training the attached model from the command line on ubuntu in aws using Deep Learning AMI GPU PyTorch 2.0.1 (Ubuntu 20.04) 20231003 #ami-0c29f8386758cadf1 the model fails on epoch 43 with index out of range on line 146 in get_stats.  I checked and self.stats has a length of 0 at that point.  I tried to track this down and fix but the rabbit hole is deep.  Note this exact same project except for the directory names run if I use the CPU on the AWS EC2 server or on either the CPU or GPU on windows.  This seems to be the smoking gun but...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     42/100       1.4G          0      0.169          0          0        640: 100%|██████████| 8/8 [00:01<00:00,  4.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 15.00it/s]
                   all          6          0          0          0          0          0
WARNING ⚠️ no labels found in detect set, can not compute metrics without labels

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     43/100       1.4G          0     0.1602          0          0        640: 100%|██████████| 8/8 [00:01<00:00,  4.73it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00, 15.92it/s]

  File "/home/ubuntu/venv/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/ubuntu/venv/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 444, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/ubuntu/venv/lib/python3.10/site-packages/ultralytics/engine/model.py", line 341, in train
    self.trainer.train()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 385, in _do_train
    self.metrics, self.fitness = self.validate()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 489, in validate
    metrics = self.validator(self)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/ultralytics/engine/validator.py", line 185, in __call__
    stats = self.get_stats()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/ultralytics/models/yolo/detect/val.py", line 146, in get_stats
    self.nt_per_class = np.bincount(stats[-1].astype(int), minlength=self.nc)  # number of targets per class
IndexError: list index out of range

### Environment

(venv) ubuntu@ip-172-31-0-64:~$ yolo checks
Ultralytics YOLOv8.0.199 🚀 Python-3.10.9 torch-2.1.0+cu121 CUDA:0 (Tesla M60, 7613MiB)
Setup complete ✅ (4 CPUs, 29.9 GB RAM, 34.2/121.1 GB disk)

OS                  Linux-5.15.0-1045-aws-x86_64-with-glibc2.31
Environment         Linux
Python              3.10.9
Install             pip
RAM                 29.86 GB
CPU                 Intel Xeon E5-2686 v4 2.30GHz
CUDA                12.1

matplotlib          ✅ 3.8.0>=3.3.0
numpy               ✅ 1.26.1>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.1.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.3>=1.4.1
torch               ✅ 2.1.0>=1.8.0
torchvision         ✅ 0.16.0>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 2.1.1>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
psutil              ✅ 5.9.6
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

### Minimal Reproducible Example

yolo task=detect mode=train epochs=100 data=data_custom.yaml model=yolov8s.pt imgsz=640 batch=4

### Additional

you can find a zip file with my project here https://github.com/toddhaugen/Yolo-bug it is public as it is just a tutorial.

Here is the requirement.txt
brotlipy @ file:///home/conda/feedstock_root/build_artifacts/brotlipy_1666764671472/work
certifi==2022.12.7
cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1671179353105/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1661170624537/work
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1666700638685/work
conda==22.11.1
conda-package-handling @ file:///home/conda/feedstock_root/build_artifacts/conda-package-handling_1669907009957/work
conda_package_streaming @ file:///home/conda/feedstock_root/build_artifacts/conda-package-streaming_1669733752472/work
cryptography @ file:///home/conda/feedstock_root/build_artifacts/cryptography-split_1675828607645/work
distlib==0.3.7
filelock==3.12.4
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1663625384323/work
libmambapy @ file:///home/conda/feedstock_root/build_artifacts/mamba-split_1671598321536/work/libmambapy
mamba @ file:///home/conda/feedstock_root/build_artifacts/mamba-split_1671598321536/work/mamba
platformdirs==3.11.0
pluggy @ file:///home/conda/feedstock_root/build_artifacts/pluggy_1667232663820/work
pycosat @ file:///home/conda/feedstock_root/build_artifacts/pycosat_1666836542287/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1672659226110/work
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1661604839144/work
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1673863902341/work
ruamel.yaml @ file:///home/conda/feedstock_root/build_artifacts/ruamel.yaml_1666827327415/work
ruamel.yaml.clib @ file:///home/conda/feedstock_root/build_artifacts/ruamel.yaml.clib_1670412719074/work
toolz @ file:///home/conda/feedstock_root/build_artifacts/toolz_1657485559105/work
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1662214488106/work
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1673452138552/work
virtualenv==20.24.5
zstandard==0.19.0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by yuyifan1991** [comment]
@toddhaugen I have the same problem as you. I guess the dataset may cause the issue, but there is no result after checking them.
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/50      4.87G          0      115.7          0          0        640: 100%|██████████| 62/62 [00:11<00:00,  5.30it/s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00, 
                   all        110          0          0          0          0          0
WARNING ⚠️ no labels found in detect set, can not compute metrics without labels

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/50      5.04G          0      86.15          0          0        640: 100%|██████████| 62/62 [00:08<00:00,  6.89it/s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00, 
                   all        110          0          0          0          0          0
WARNING ⚠️ no labels found in detect set, can not compute metrics without labels

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/50      5.12G          0      66.17          0          0        640: 100%|██████████| 62/62 [00:08<00:00,  7.17it/s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00, 
                   all        110          0          0          0          0          0
WARNING ⚠️ no labels found in detect set, can not compute metrics without labels

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/50      5.05G          0      46.74          0          0        640: 100%|██████████| 62/62 [00:08<00:00,  7.22it/s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00, 
Traceback (most recent call last):
  File "/home/cv/.conda/envs/torch1.8_py3.8/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/cv/.conda/envs/torch1.8_py3.8/lib/python3.8/site-packages/ultralytics/cfg/__init__.py", line 445, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/cv/.conda/envs/torch1.8_py3.8/lib/python3.8/site-packages/ultralytics/engine/model.py", line 341, in train
    self.trainer.train()
  File "/home/cv/.conda/envs/torch1.8_py3.8/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 191, in train
    self._do_train(world_size)
  File "/home/cv/.conda/envs/torch1.8_py3.8/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 384, in _do_train
    self.metrics, self.fitness = self.validate()
  File "/home/cv/.conda/envs/torch1.8_py3.8/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 488, in validate
    metrics = self.validator(self)
  File "/home/cv/.conda/envs/torch1.8_py3.8/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/cv/.conda/envs/torch1.8_py3.8/lib/python3.8/site-packages/ultralytics/engine/validator.py", line 185, in __call__
    stats = self.get_stats()
  File "/home/cv/.conda/envs/torch1.8_py3.8/lib/python3.8/site-packages/ultralytics/models/yolo/detect/val.py", line 146, in get_stats
    self.nt_per_class = np.bincount(stats[-1].astype(int), minlength=self.nc)  # number of targets per class
IndexError: list index out of range

**Comment by glenn-jocher** [comment]
@toddhaugen it seems like you're encountering an error message that says "no labels found in detect set, can not compute metrics without labels." This implies that there might be an issue in locating your annotation files. The annotation files contain the locations of your class objects you're trying to detect, hence they are critical when training your model. Ensure that your annotation files are properly labeled, stored, and matched with corresponding images.

The `IndexError: list index out of range` also indicates a discrepancy in terms of index accessing. This usually happens if an operation attempts to access an index that doesn't exist in a list or array. Given that this error shows up when your model is trying to compute stats, it might indicate that your model is not able to access or find object labels for computation.

One way to address this issue is to ensure that your `*.txt` files (which correspond to each image in your dataset and contain the object coordinates and class labels) are matching with each corresponding image file and are correctly formatted.

Moreover, the loss values (`box_loss`, `cls_loss`, and `dfl_loss`) being '0' during training could possibly indicate that the model is not training correctly. The zero losses may occur due to the absence of ground truth labels to compare with the predicted output during the training phase.

Make sure to double-check your dataset, particularly the annotation labels as it's likely causing the issue.

**Comment by toddhaugen** [comment]
@glenn-jocher well considering the same files train on Windows CPU or GPU and on AWS Windows while giving the same error it seems unlikely, even more so given it fails on epoch 43.  WTS, I checked all of my images in train and val have annotations with locations.  My .yaml file has the labels in the right order.  I am wondering if you read my report in detail.  I debugged the code, reproduced the problem (self.stats list is empty only on epoch 43), and tried to trace the issue but could not track down what is causing the list to either fail to fill or get cleared.  Does this give you other ideas?

**Comment by toddhaugen** [comment]
I just restarted the machine and ran train with batch sizes 4, 8, default, and autobatch (-1) each one gives the same error but at a different Epoch if that gives anyone ideas.

**Comment by toddhaugen** [comment]
@glenn-jocher OK I tried to figure out how to stop that warning but I cannot find anything on that says what is really causing the error.  You are saying it might not be able to find my annotation files but they are in the recommended directory, Labels, under both Train and Val.  Is there something else I need to do?

**Comment by glenn-jocher** [comment]
@toddhaugen in your training process, the annotations provide crucial information used to benchmark your model's performance. Without these annotations, the model is left without a "ground truth" or correct answer to learn from, resulting in inability to compute accuracy metrics.

The warning stating 'no labels found in detect set' suggests the training script might be facing difficulties in correctly locating or reading the annotations. There are a few potential causes:

1. File Structure: Ensure that the dataset structure strictly adheres to the one recommended by YOLOv8. Double-check your paths in the config file and make sure that they correctly point to the directories containing the training images and labels.

2. Annotation Format: The annotations must be in the format expected by YOLOv8. If the structure of the annotations is not as expected, it may not be detecting them correctly.

3. Permission Issues: In some environments, permission issues could restrict reading files. Your model might not be able to access the necessary label files due to lack of sufficient permissions.

It's also possible that the labels are found initially but lost in the later epochs. The model throwing an 'index out of range' error could be due to the empty labels list in the 43rd epoch, which is peculiar. This is perhaps why changing the batch sizes alters the epoch at which the error occurs. The changing batch size causing alterations on when errors occur may point to an inconsistency in your dataset or a deficiency in available computational resources, especially if this behavior is noticed despite increasing memory provisions. 

However, it's challenging to pinpoint the root cause of these issues without deeper access to your setup and data. We strongly recommend verifying your dataset and its structure, permissions, and the resource allocation once again.

**Comment by glenn-jocher** [comment]
@toddhaugen, I'm glad the issue was resolved for you. As per your description, it seems your file structure might have been the primary issue. YOLOv8 expected your images and annotations to reside directly in the train and validation folders, and couldn't find them when placed in the labels or images sub-directories.

While it might be unexpected that this setup worked on some systems (like Windows and Linux CPU variants) but not on others (assuming Unix-based systems or similar), it could relate to how the file paths are interpreted and accessed differently across these environments. 

Since moving images and annotation files directly into the train and validation folders resolved the issue, it might be beneficial to adhere to this structure when using YOLOv8 to avoid similar problems.

Even though a lot of software can resolve relative paths efficiently, it's generally a good practice to ensure the compatibility of your setup across different environments. It's always helpful to double-check the recommended setup and guidelines provided by the tool or library you're working with.
