### ISSUE TITLE
The issue of image size during tracking inference.

### ISSUE THREAD

**Issue by LXXIANG12** [ultralytics/ultralytics#5726]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://github.com/ultralytics/ultralytics/assets/103343903/2aa577c3-7629-4827-a7c4-ddc3bf03256e)
![image](https://github.com/ultralytics/ultralytics/assets/103343903/3befedc2-2437-42ae-a4f1-4df2b7e2a47e)
How can I resize the image to 1920x640?

**Comment by RizwanMunawar** [comment]
@LXXIANG12, you're on the right track. However, please note that the 'imgsz' parameter should be set to 'imgsz=640' or 'imgsz=416' because the default YOLOv8 variants aren't trained for larger image sizes like '1920 x 640'.

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by LXXIANG12** [comment]
> @LXXIANG12, you're on the right track. However, please note that the `imgsz` parameter should be set to `imgsz=640` or `imgsz=416` because the default YOLOv8 variants aren't trained for larger image sizes like `1920 x 640`.
> 
> Hope this helps! Let me know if you have any additional questions. Thanks

Thank you very much for your prompt reply! I have a requirement now to adjust the image size during tracking inference to 1920x640, but after setting imgsz=[1920,640], the images during inference are actually 640x640. Do the width and height have to be equal during inference?
![image](https://github.com/ultralytics/ultralytics/assets/103343903/c6f0922d-f4ce-4025-80ff-0e4ec545b6c3)

**Comment by glenn-jocher** [comment]
@LXXIANG12 hello,

Yes, you're correct. The YOLOv8 model expects the input image to be square during inference, which is why it resizes the input to 640x640 instead of 1920x640. The reason for this is due to how the model is designed and trained. Allowing changes to this structural aspect could directly impact model performance and accuracy. 

In your unique case (with the size of 1920x640), it's advisable to divide the image into three equal parts with sizes 640x640 for processing and then combine the results. Alternatively, you could modify the aspect ratio but please be aware that this might affect the model's accuracy to some extent. 

Hope this answers your question! If you have more questions or need further clarification, please let me know. 

Thank you!
