### ISSUE TITLE
The image width and height are not the same.

### ISSUE THREAD

**Issue by LXXIANG12** [ultralytics/ultralytics#5728]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://github.com/ultralytics/ultralytics/assets/103343903/c4d9714f-a475-4af9-8462-8e7a9d984994)

![image](https://github.com/ultralytics/ultralytics/assets/103343903/68f5bf60-e464-479e-8417-2c53a2776785)
As shown, I want to resize the image size for tracking inference to 224x128, but YOLOv8 automatically resizes the image to 128x128. Does the image width and height need to be equal when using YOLOv8 for inference? How can I resize the image to the size I need?

**Comment by RizwanMunawar** [comment]
To ensure compatibility, it's important that both the image and its width share the same dimensions, which should also be a multiple of 32. For example, 128 is a suitable choice since it's a multiple of 32. Notably, the output image size will match the original image, so there's no need for concern in that regard.

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by LXXIANG12** [comment]
> 为了确保兼容性，图像及其宽度共享相同的尺寸非常重要，该尺寸也应该是 32 的倍数。例如，128 是一个合适的选择，因为它是 32 的倍数。值得注意的是，输出图像大小将匹配原始图像，因此无需担心这方面。
> 
> 希望这可以帮助！如果您还有任何其他问题，请告诉我。 谢谢
Are you suggesting that if I train with image size set to 224x118, and then when I use the model for inference with model.track, I don't need to specify the imgsz parameter, and the output of inference will also be 224x118?

**Comment by glenn-jocher** [comment]
@LXXIANG12 yes, that's correct! YOLOv8 is designed to work flexibly with various input sizes. When you train with an image size of 224x118, the trained model adapts to that size. And when running inference without specifying the imgsz parameter, the model will process input images with their original sizes.

However, it's essential to remember that sizes should be in multiples of 32 for proper functionality, as it's a requirement intrinsic to the architecture of YOLOv8. The particular dimensions you mentioned (224x118) might lead to unexpected results or errors because 118 is not a multiple of 32.

Always ensure that both dimensions of your input images are divisible by 32 for optimum performance and results. If you continue to encounter issues, please let us know, and we'll be happy to assist further!
