### ISSUE TITLE
 NMS time limit 2.100s exceeded

### ISSUE THREAD

**Issue by sanjanak-rbg** [ultralytics/ultralytics#5739]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

iam getting this warning and the training is getting killed after that, how can i resolve this?
 3/15      4.89G     0.5933     0.5576       1.16         66        640: 100%|██████████| 47429/47429 [2:18:29<00:00,  5.71it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):  71%|███████   | 2105/2968 [06:00<06:03,  2.37it/s]WARNING ⚠️ NMS time limit 2.100s exceeded
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):  71%|███████   | 2108/2968 [27:17<72:53:17, 305.11s/it]WARNING ⚠️ NMS time limit 2.100s exceeded
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):  71%|███████   | 2109/2968 [3:38:58<871:14:46, 3651.32s/it

**Comment by glenn-jocher** [comment]
@sanjanak-rbg hello,

I'm sorry to hear about the warning message you're encountering - 'NMS time limit 2.100s exceeded'. NMS, or Non-Maximum Suppression, is a common post-processing step in object detection that helps eliminate redundant overlapping bounding boxes. In the context of this warning, NMS processing for some images is taking longer than the set time limit, which might interrupt the training process.

The primary reason behind this could be the overwhelming number of detections being processed, possibly due to a high number of classes, complex images, large image size or high model confidence thresholds. 

As a solution, you might want to consider the following:
- Reducing the complexity of your images or resizing images to a smaller scale.
- Reducing the number of classes in your dataset.
- Increasing the NMS time limit, although this might slow down your training process.
- Adjusting the confidence thresholds of the model to result in fewer initial detections.
- Using a more powerful server that can process the data more quickly if available.

I hope this helps, and you're able to proceed with your training. Don't hesitate to get back if you have more questions.

Best of luck with your project!

**Comment by sanjanak-rbg** [comment]
hi , please help me with where can i change the NMS time limit

**Comment by glenn-jocher** [comment]
@sanjanak-rbg hello,

Thank you for reaching out. The NMS time limit parameter is within the configuration file, "nms.cfg" for YOLOv8. This file contains all NMS settings, including the time limit parameter.

To change the NMS time limit, you would need to locate this file and open it. The time limit will be denoted by a directive such as `timelimit = x`, where 'x' is the current limit set. Your goal will be to replace 'x' with a larger number to extend the time limit.

Remember, adjusting this value may impact performance and inference speed of your model, so it's essential to balance precision and speed according to your specific requirements.

Feel free to follow up if you have further questions, and best of luck with your project!
