### ISSUE TITLE
Loading *filename* for ONNX Runtime inference.. -> displayed even if verbose=False

### ISSUE THREAD

**Issue by MasIgor** [ultralytics/ultralytics#5740]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hi all!

If I set verbose = False, then there is no output to the console, except for this:

Loading C:\Users\ADMINI~1\AppData\Local\Temp\tmp6a7hy7k4.onnx for ONNX Runtime inference...

how can this be removed as well? 

Thank you

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MasIgor hello,

Thank you for bringing this issue to our attention.

Currently, the "Loading *filename* for ONNX Runtime inference..." message is hardcoded into the export and inference code to provide users with updates on the ONNX status. This output message is displayed even when `verbose=False` is set.

Unfortunately, at this time, there's no built-in option to disable this specific print statement. In order to completely silence the output, modifications would need to be made in the source code, specifically in the part that manages the ONNX inference exports.

We'll take your feedback into account. We're continually trying to improve the user experience, and adjusting the verbose settings to better control console outputs might be something we can improve upon in future updates.

Thank you for using YOLOv8 and contributing to our community by raising this issue. We value your input and appreciate your patience.

Best wishes,
Glenn Jocher

**Comment by MasIgor** [comment]
Hello @glenn-jocher,

Is there any time estimation on this change? the problem is that this function inside autobackend.py is quite long, so redefining it in my code would overwrite any future changes. I already redefined some minor functions that are unlikely to change, but this one is trickier. 

an alternative aproach would be to redefine the LOGGER.info function.. but not sure on how to do that..

**Comment by MasIgor** [comment]
I solved it for now by simply setting up a system variable called "YOLO_VERBOSE" set to false.

**Comment by glenn-jocher** [comment]
Hello @MasIgor,

You've come up with a clever workaround! Using environment variables to control the verbosity level can be quite effective. It's great to see you were able to find a solution that suits your needs.

As for your previous question about time estimation for adjusting the `verbose` functionality, it's challenging to provide a precise timeline. We're continuously working on refining our models and approach, and user feedback like this greatly helps us in deciding what updates or changes to prioritize.

In terms of overriding the LOGGER.info function, one general way could be to subclass the `Logger` class and override the `info` function in the subclass. However, this could lead to complexities as LOGGER is used extensively throughout the codebase.

Thank you for sharing your solution with the community and for your patience and understanding. Your input is greatly valuable to us and the YOLOv8 users.

Best,
Glenn Jocher
