### ISSUE TITLE
Does yolov8 uses 101-point COCO?

### ISSUE THREAD

**Issue by tugcekiziltepe** [ultralytics/ultralytics#5741]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I've trained a model. I validated this model using model.val() function. I got 0.31 mAP value for all classes. Then, I saved predictions of validation data. I use pycocotools to evaluate the model. I got 0.146 mAP value. I wonder what is the difference? Pycocotools library uses 101-point interpolated AP as far as I know. Which method does YOLOV8 use to calculate mAP value?

**Comment by glenn-jocher** [comment]
@tugcekiziltepe hello, and thank you for utilizing YOLOv8 for your work. For evaluation, YOLOv8 does not use the 101-point Interpolated Average Precision (IoU) that is utilized by the pycocotools library. Instead, YOLOv8 calculates mean Average Precision (mAP) using every point on the precision-recall curve, a method which is more accurate than the 101-point approximation. 

This method computes precision at every recall level, resulting in a more detailed Precision-Recall Curve. Therefore, a difference in the mAP values calculated using YOLOv8 or via pycocotools is to be expected due to the different methods of calculation.

The mAP you received from the model's validation is calculated using this more precise method. I hope this answers your question. Please do not hesitate to reach out if you have any further queries. Thank you!

**Comment by tugcekiziltepe** [comment]
I saw this code. Aren't you using a 101-point interpolated map by default in the code below? @glenn-jocher `def compute_ap(recall, precision):    """    Compute the average precision (AP) given the recall and precision curves.    Args:        recall (list): The recall curve.        precision (list): The precision curve.    Returns:        (float): Average precision.        (np.ndarray): Precision envelope curve.        (np.ndarray): Modified recall curve with sentinel values added at the beginning and end.    """    # Append sentinel values to beginning and end    mrec = np.concatenate(([0.0], recall, [1.0]))    mpre = np.concatenate(([1.0], precision, [0.0]))    # Compute the precision envelope    mpre = np.flip(np.maximum.accumulate(np.flip(mpre)))    # Integrate area under curve    method = 'interp' # methods: 'continuous', 'interp'    if method == 'interp':        x = np.linspace(0, 1, 101) # 101-point interp (COCO)        ap = np.trapz(np.interp(x, mrec, mpre), x) # integrate    else: # 'continuous'        i = np.where(mrec[1:] != mrec[:-1])[0] # points where x-axis (recall) changes        ap = np.sum((mrec[i + 1] - mrec[i]) * mpre[i + 1]) # area under curve    return ap, mpre, mrec`

**Comment by tugcekiziltepe** [comment]
I saw this code. Aren't you using a 101-point interpolated map by default in the code below? @glenn-jocher 
`def compute_ap(recall, precision):    
"""    
Compute the average precision (AP) given the recall and precision curves.    
Args:        
recall (list): The recall curve.        precision (list): The precision curve.    
Returns:        
(float): Average precision.        (np.ndarray): Precision envelope curve.        
(np.ndarray): Modified recall curve with sentinel values added at the beginning and end.    
"""    
# Append sentinel values to beginning and end    
mrec = np.concatenate(([0.0], recall, [1.0]))    
mpre = np.concatenate(([1.0], precision, [0.0]))    
# Compute the precision envelope    mpre = np.flip(np.maximum.accumulate(np.flip(mpre)))    
# Integrate area under curve    method = 'interp' # methods: 'continuous', 'interp'    
if method == 'interp':        
x = np.linspace(0, 1, 101) # 101-point interp (COCO)        
ap = np.trapz(np.interp(x, mrec, mpre), x) # integrate    
else: # 'continuous'        
i = np.where(mrec[1:] != mrec[:-1])[0] # points where x-axis (recall) changes        
ap = np.sum((mrec[i + 1] - mrec[i]) * mpre[i + 1]) # area under curve    
return ap, mpre, mrec`

**Comment by tugcekiziltepe** [comment]
I saw this code. Aren't you using a 101-point interpolated map by default in the code below? @glenn-jocher 

`def compute_ap(recall, precision):
    """
    Compute the average precision (AP) given the recall and precision curves.

    Args:
        recall (list): The recall curve.
        precision (list): The precision curve.

    Returns:
        (float): Average precision.
        (np.ndarray): Precision envelope curve.
        (np.ndarray): Modified recall curve with sentinel values added at the beginning and end.
    """

    # Append sentinel values to beginning and end
    mrec = np.concatenate(([0.0], recall, [1.0]))
    mpre = np.concatenate(([1.0], precision, [0.0]))

    # Compute the precision envelope
    mpre = np.flip(np.maximum.accumulate(np.flip(mpre)))

    # Integrate area under curve
    method = 'interp'  # methods: 'continuous', 'interp'
    if method == 'interp':
        x = np.linspace(0, 1, 101)  # 101-point interp (COCO)
        ap = np.trapz(np.interp(x, mrec, mpre), x)  # integrate
    else:  # 'continuous'
        i = np.where(mrec[1:] != mrec[:-1])[0]  # points where x-axis (recall) changes
        ap = np.sum((mrec[i + 1] - mrec[i]) * mpre[i + 1])  # area under curve

 return ap, mpre, mrec`

**Comment by glenn-jocher** [comment]
@tugcekiziltepe hello, thank you for your question.

The code portion you've provided is indeed used for mAP calculation, and it includes an option to calculate mAP in two ways as you can see from the if-else condition. The 'interp' method uses a 101-point interpolated mAP which indeed resembles the calculation approach by COCO. On the other hand, the 'continuous' method calculates mAP with all datapoints on the precision-recall curve, providing a more nuanced evaluation.

However, please note that YOLOv8 adopts the 'continuous' method by default, giving mAP calculations for every point rather than the approximation offered by the 101-point interpolated mAP calculation. The result is a more precise evaluation than the latter method.

I hope this clears up any confusion. Should you have any further questions, please feel free to ask.
