### ISSUE TITLE
Keep getting out of memory

### ISSUE THREAD

**Issue by MrChains** [ultralytics/ultralytics#5745]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I have been trying to train a yolov8n model on VisDrone dataset on Google Colab with no success.

keeps running out of space.
![image](https://github.com/ultralytics/ultralytics/assets/13667339/097a72c7-a750-426c-881f-d26e2cb3fca1)

CUDA out of memory. Tried to allocate 2.52 GiB (GPU 0; 14.75 GiB total capacity; 9.81 GiB already allocated; 54.81 MiB free; 13.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Is it ok for PyTorch to reserve so much? 

Also tried reducing the batch size but it seems that running model = YOLO('https://hub.ultralytics.com/models/W209AenaCKTJ50I1crwt') sets the parameters and it wont let me change them later on. running `model.train(batch=16 does nothing, the AutoBatch still runs)`

I will download the dataset and try to train manually.

### Environment

Ultralytics YOLOv8.0.199 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 26.8/166.8 GB disk)

### Minimal Reproducible Example

`import gc
gc.collect()
hub.login('MY_LOGIN')
model = YOLO('https://hub.ultralytics.com/models/W209AenaCKTJ50I1crwt')
model.train()`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MrChains hello,

Thank you for detailed description of the issue you're experiencing. Let's look into your problem.

In your case, it appears that the error is due to PyTorch trying to allocate more memory than that available on Google Colab's GPU. CUDA out of memory error is generally caused by insufficient GPU memory in relation to the size of the task at hand. Considering this, there are a couple of ways to handle this issue.

1. **Lower the Batch Size**: One of the most common ways to reduce GPU memory consumption is to decrease the batch size. I'd recommend trying a lower batch size. You mentioned that you tried reducing the batch size but it had no effect. The 'model.train()' function automatically uses the batch size defined in the model's configuration file. To adjust the batch size, you'll need to modify the model's configuration file before creating the YOLO instance.

2. **Using Gradient Accumulation**: Another method to deal with this problem is to use gradient accumulation, which can effectively reduce memory cost by lengthening the interval of model parameter updates. In Ultralytics YOLOv8, you can enable gradient accumulation via your training script.

3. **Monitor Your GPU Utilization**: Also, monitor GPU utilization during the training process. If there are other processes using the GPU memory, you might want to consider stopping them to free up memory.

This might not be foolproof but should definitely improve the situation to some extent. Keep in mind that the Tesla T4 on Colab is a shared resource, and the available memory can vary.

Let us know how it goes and feel free to report back if you're still encountering issues. We're here to help!

Best regards,
Glenn Jocher

**Comment by nil123532** [comment]
how to implement 2?

**Comment by glenn-jocher** [comment]
@nil123532 to implement gradient accumulation in YOLOv8, you'll need to adjust the `accumulate` parameter in your training configuration. This parameter controls how many batches will pass before the optimizer steps and updates the model weights.

For example, if you're currently using a batch size of 16 and you're running out of memory, you could reduce the batch size to 8 and set `accumulate` to 2. This way, the optimizer will update the weights every two batches, effectively simulating a larger batch size while using less memory.

You can find more details on how to configure this in the training section of the Ultralytics documentation. Remember to adjust these parameters based on your specific memory constraints and the capabilities of your hardware.

Good luck with your training!
