### ISSUE TITLE
Exporting pose predictions without background

### ISSUE THREAD

**Issue by mcdominik** [ultralytics/ultralytics#5746]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I run simple command:
yolo predict model=yolov8n-pose.pt source='URL' imgsz=320 show=True 

It saves original video with poses.
Is it possible to save only poses estimations (skeletons) on for example white/black background?

I mean something like this:
<img width="503" alt="Screenshot 2023-10-16 at 21 26 17" src="https://github.com/ultralytics/ultralytics/assets/81818614/b5134528-3455-48e4-a4fd-f984e71dd431">

**Comment by glenn-jocher** [comment]
@mcdominik hi,

Thank you for bringing up this question. Currently in our YOLOv8 implementation, the `predict` function does overlay pose estimations (skeletons) on top of the original images or video frames, producing an output that includes both the original content and the pose annotations.

However, I understand you're looking to save the pose estimations independently, devoid of the original background. While this feature is not directly available in the current version of YOLOv8, it is certainly possible to modify the output process to achieve this.

Here's a high-level overview of how you can do it:

1. **Isolate Pose Estimations**: When you run the `predict` function, it processes individual frames of the source video, performs the pose estimation, and then overlays these estimations on the frames. You would need to modify this part of the function to only draw the skeletons in a blank image (a new frame filled only with a single color, say all black or all white) rather than on top of the original frames.

2. **Save the Estimations**: Once you've isolated the pose estimations, you would then save these frames, effectively giving you a video of pose annotations without any background.

Please note that such modifications would require a sound understanding of the YOLOv8 codebase and Python programming. If you need further clarification or help with other parts of YOLOv8, feel free to ask. Your contribution to our discussions is always appreciated!

Best,
Glenn Jocher

**Comment by RizwanMunawar** [comment]
@mcdominik You can employ the provided code to accomplish this task.

```python
import cv2
import sys
import numpy as np
from ultralytics import YOLO
from ultralytics.utils.plotting import colors

model = YOLO("yolov8m-pose.pt")  # Path to model file
video_path = 'ultralytics.mp4'  # Path to video file
cap = cv2.VideoCapture(video_path)
if not cap.isOpened():
    print("Error reading video file")
    sys.exit()

frame_width = int(cap.get(3))
frame_height = int(cap.get(4))
size = (frame_width, frame_height)
result = cv2.VideoWriter('detection3_black.avi',
                         cv2.VideoWriter_fourcc(*'MJPG'),
                         30, size)

# Pose
skeleton = [[16, 14], [14, 12], [17, 15], [15, 13], [12, 13], [6, 12], [7, 13], [6, 7], [6, 8], [7, 9],
            [8, 10], [9, 11], [2, 3], [1, 2], [1, 3], [2, 4], [3, 5], [4, 6], [5, 7]]
limb_color = colors.pose_palette[[9, 9, 9, 9, 7, 7, 7, 0, 0, 0, 0, 0, 16, 16, 16, 16, 16, 16, 16]]


def kpts(img, kpts, shape=(640, 640), radius=5, kpt_line=True):
    nkpt, ndim = kpts.shape
    is_pose = nkpt == 17 and ndim == 3
    kpt_line &= is_pose
    for i, k in enumerate(kpts):
        x_coord, y_coord = k[0], k[1]
        if x_coord % shape[1] != 0 and y_coord % shape[0] != 0:
            if len(k) == 3:
                conf = k[2]
                if conf < 0.5:
                    continue
            cv2.circle(img, (int(x_coord), int(y_coord)), 5, (255, 0, 255),
                       -1, lineType=cv2.LINE_AA)
    if kpt_line:
        ndim = kpts.shape[-1]
        for i, sk in enumerate(skeleton):
            pos1 = (int(kpts[(sk[0] - 1), 0]), int(kpts[(sk[0] - 1), 1]))
            pos2 = (int(kpts[(sk[1] - 1), 0]), int(kpts[(sk[1] - 1), 1]))
            if ndim == 3:
                conf1 = kpts[(sk[0] - 1), 2]
                conf2 = kpts[(sk[1] - 1), 2]
                if conf1 < 0.5 or conf2 < 0.5:
                    continue
            if pos1[0] % shape[1] == 0 or pos1[1] % shape[0] == 0 or pos1[0] < 0 or pos1[1] < 0:
                continue
            if pos2[0] % shape[1] == 0 or pos2[1] % shape[0] == 0 or pos2[0] < 0 or pos2[1] < 0:
                continue
            cv2.line(img, pos1, pos2, [int(x) for x in limb_color[i]], thickness=2, lineType=cv2.LINE_AA)
    return img


while cap.isOpened():
    success, frame = cap.read()
    if success:
        black_image = np.zeros((frame_height, frame_width, 3), dtype=np.uint8)
        results = model.track(frame)[0]
        kptss = results.keypoints.data
        for k in reversed(kptss):
            frame_black = kpts(black_image, k, shape=(640, 640), radius=10)

        result.write(frame_black)
        cv2.imshow("YOLOv8 Detection", frame_black)

        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        break

cap.release()
cv2.destroyAllWindows()
```

Hope this helps! Let me know if you have any additional questions.
Thanks
