### ISSUE TITLE
ray tune training PermissionError: [WinError 5].

### ISSUE THREAD

**Issue by ue17** [ultralytics/ultralytics#5749]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello.

I am using the following conditions
ultralytics: 8.0.198
ray: 2.7.1
windows: 10 pro

When I run the following program, it learns fine until the middle of the program,
However, the learning stops halfway through with a PermissionError: [WinError 5].

```` 
from ultralytics import YOLO
model = YOLO("yolov8n-seg_custom.yaml")
result_grid = model.tune(data="test.yaml",
                         grace_period=10,
                         gpu_per_trial=1, 
                         iterations=20, 
                         batch=8, 
                         imgsz=1280,
                         pretrained='weights/yolov8n-seg.pt',
                         device=0,
                         use_ray=True
                        )
````

I am having trouble with folder permissions.
I have tried the following, but without success.
(1) Running the command prompt with administrator privileges
(2) Checking folder access permissions

What countermeasures should I take?

**Comment by glenn-jocher** [comment]
@ue17 hi there,

Thank you for reaching out and providing detailed information. The PermissionError you're encountering may be tied to filesystem access issues related to the operating system, rather than the YOLOv8 code itself.

Given you're using Windows and have tried running the command prompt with administrator privileges, here a few other things you might consider:

**1. Temporary Files**: Sometimes, issues like these can occur if temporary files aren't being deleted properly during the script execution. Please make sure the directories where these files are stored are correct and have the right access permissions.

**2. Antivirus Software**: In certain situations, antivirus software could restrict access to some files. You might want to temporarily disable your antivirus software to find out if that could be causing the problem.

**3. User Permissions**: If you're running this on a shared or networked system, there may be restrictions on your user account that are causing this issue.

To further investigate the problem, you could try to examine the full error stack trace. This could provide valuable insights into which exact file or directory access is causing the PermissionError.

Also, please check your program is not trying to access or write to a directory that is concurrently being accessed or modified by another process.

I hope these suggestions help you troubleshoot the issue!

Best,
Glenn.
