### ISSUE TITLE
problem In Payton Visual Code

### ISSUE THREAD

**Issue by gmwmf2014** [ultralytics/ultralytics#5761]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

problem In Payton Visual Code
detector = FIRE (model_name='best.pt')
TypeError: object() takes no parameters
Everything is fine in colab
When experimenting with Visual Code, the file best.pt is not read

**Comment by glenn-jocher** [comment]
@gmwmf2014 hello,

It seems you're encountering a problem while trying to use a trained model in Visual Studio Code. From your description, it looks like you may be trying to instantiate a model object with parameters in a way that may not be supported.

The error `TypeError: object() takes no parameters` usually arises when you're trying to pass parameters to a class or a function that does not accept any. In your case, the issue is with `model_name='best.pt'`, which is probably not a valid parameter for the model object you're trying to instantiate.

It's important to ensure you are correctly loading the model. You should make use of the appropriate load function or method provided by the YOLOv8 implementation. Ensure that the model file 'best.pt' is in the correct directory and the path you're providing for it is accurate.

In case you're still facing issues, providing us with a more detailed view of your code setup and environment could greatly assist us in identifying the problem. Code snippets, error stack traces, the version of the library you are using and how you installed it on your VS Code environment can provide vital information.

I hope this helps. Let us know if you need any further support. We're here to help!

Best regards,
Glenn Jocher
