### ISSUE TITLE
UserWarning: Initializing zero-element tensors is a no-op warnings.warn("Initializing zero-element tensors is a no-op")

### ISSUE THREAD

**Issue by PiyushKamboj1503** [ultralytics/ultralytics#5786]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

![image](https://github.com/ultralytics/ultralytics/assets/54760385/dd0c8387-93d3-4cbe-8f4a-7311f1a835cf)
This message is shown repeatedly at the starting of the training. Post that the training starts. 
At the end of the training, it fails with a text memory error and no outputs are saved.

In wandb, multiple instances of the same training are also created out of which 1 is correctly logged.

### Environment

![image](https://github.com/ultralytics/ultralytics/assets/54760385/33ba2d3f-c4c6-4c5b-9313-fe872bd347fc)

### Minimal Reproducible Example

from ultralytics import YOLO
import wandb
wandb.init(project="My-Proj")

model = YOLO("yolov8n.yaml")

def training():
    history = model.train(data=r"pathto\data.yaml",
                          epochs=300,
                          device=0,
                          workers=2,
                          imgsz=640,
                          verbose=True,
                          save=True)

if __name__ == "__main__":
    training()

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@PiyushKamboj1503 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. The code works correctly for me, I'm unable to reproduce any issues here.

<img width="1749" alt="Screenshot 2023-10-18 at 13 33 51" src="https://github.com/ultralytics/ultralytics/assets/26833433/70126d98-c212-4b88-ad4f-e7d2232388a2">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
