### ISSUE TITLE
model.val().map not working

### ISSUE THREAD

**Issue by fhasanm** [ultralytics/ultralytics#5791]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Val

### Bug

Hi I am trying to store the values of the map metrics, as mentioned int the [docs:](https://docs.ultralytics.com/modes/val/#arguments)
`metrics = model.val()`
`metrics.box.map # map50-95`
`metrics.box.map50 # map50`
`metrics.box.map75 # map75`
`metrics.box.maps # a list contains map50-95 of each category`

But this isn't working. I am getting a NoneType Error. Says model.val() is a NoneType Object with no attribute like map or maps. Is the documentation wrong? Or am I missing a module?

### Environment

Ultralytics YOLOv8.0.20 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (Tesla T4, 15102MiB)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@fhasanm hello,

Thanks for reaching out!

The `model.val()` function indeed returns metrics, as described in the documentation. However, please note that this call doesn't return anything if the validation dataset has not been initialized. If you're trying to call this function immediately after model creation or outside of a training loop without initializing a validation dataset, that could be the reason you're experiencing a `NoneType` error. 

Are you ensuring a validation dataset is ready and the model is placed in the evaluation mode? This operation is typically embedded in a training loop where the model toggles between training and validation states in each epoch. 

Please initialize the validation dataset and invoke the function within the context of a training scenario, after conducting some learning operations. 

If this doesn't work, or doesn't apply, please provide some more context. We'd be happy to further investigate the issue.

**Comment by isuchy** [comment]
Hi @glenn-jocher,

I also have the same issue, but your recommendation didn't help.
Here is the code I'm using:
```
import torch
from ultralytics import YOLO

model = YOLO("/content/runs/detect/train/weights/best_saved_model/best_float32.tflite")
metrics = model.val(data="/content/datasets/dataset.yaml")
print(metrics)
```

The exported TFLite model is loaded correctly and when I call the `val()` function even with the valid data.yaml in the data argument, it crashes with this error.  

```
Ultralytics 8.3.1 🚀 Python-3.10.12 torch-2.5.1+cu121 CPU (Intel Xeon 2.20GHz)
Loading /content/runs/detect/train/weights/best_saved_model/best_float32.tflite for TensorFlow Lite inference...
WARNING ⚠️ Metadata not found for 'model=/content/runs/detect/train/weights/best_saved_model/best_float32.tflite'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-20-cff0453da666>](https://localhost:8080/#) in <cell line: 1>()
----> 1 metrics = model.val(data="/content/datasets/dataset.yaml")
      2 print(metrics)

2 frames
[/content/ultralytics_yolov8/ultralytics/engine/validator.py](https://localhost:8080/#) in __call__(self, trainer, model)
    138                 self.args.batch = model.batch_size
    139             elif not pt and not jit:
--> 140                 self.args.batch = model.metadata.get("batch", 1)  # export.py models default to batch-size 1
    141                 LOGGER.info(f"Setting batch={self.args.batch} input of shape ({self.args.batch}, 3, {imgsz}, {imgsz})")
    142 

AttributeError: 'NoneType' object has no attribute 'get'
```

Maybe this is caused by the same reason why I got the warning that metadata was not found. But is it even possible to somehow add them to the exported model?

Thanks in advance.

**Comment by glenn-jocher** [comment]
Hello @isuchy,

The issue arises because TFLite models are optimized for inference and do not retain metadata or the architecture details required for model validation. The `model.val()` function relies on a PyTorch model with complete metadata, which is not available in an exported TFLite model.

To perform validation, you need to use the original PyTorch model (`best.pt`) before exporting it to TFLite. The validation process must be completed prior to exporting the model. Unfortunately, once the model is in TFLite format, it cannot be used with `val()` for metrics evaluation.

If validation is required post-export, you'll need to validate the PyTorch model first and then proceed with exporting to TFLite. For additional details on validation, refer to the documentation here: https://docs.ultralytics.com/modes/val/.

Let me know if you have further questions!

**Comment by Ashutosh1995** [comment]
Hi @glenn-jocher in order to use the model.val() using custom engine file exported through trtexec command, the metadata is essential ?

I see that when I use the engine exported through Ultralytics and use the engine to get validation results, I get the required results but the same output is 0 when using custom engine file. Kindly clarify!

yolo val task=segment model=yolov8s-seg_tc_bc.engine data=custom.yaml imgsz=960 conf=0.5 iou=0.7
This gives me the following results

<img width="1211" alt="Image" src="https://github.com/user-attachments/assets/e5f6020a-371d-44f1-b963-88f145581c72" />

But when I run the same command using custom file, I get the following
yolo val task=segment model=custom-model-v3.engine data=custom.yaml imgsz=960 conf=0.5 iou=0.7

<img width="1252" alt="Image" src="https://github.com/user-attachments/assets/36eead9f-3f8b-4da4-9919-074d84a9316b" />

**Comment by glenn-jocher** [comment]
Hi there! The difference in validation results occurs because TensorRT engines exported via Ultralytics include model metadata (task type, input resolution, etc.) that's essential for proper validation setup. When using `trtexec`, this metadata isn't automatically added, causing the validator to misidentify the task type. 

Our exporter handles metadata injection internally - you can see this in the [`_add_tflite_metadata` function](https://docs.ultralytics.com/reference/engine/exporter/#ultralytics.engine.exporter.Exporter._add_tflite_metadata) which ensures proper model configuration. For accurate validation, please export engines using `model.export(format='engine')` rather than `trtexec`. This maintains compatibility with Ultralytics validation workflows.

**Comment by Ashutosh1995** [comment]
Hi @glenn-jocher  if you see the last image in the above post, you would see that I did not export the metadata in the engine file exported through ultralytics and still I was able to get the results. Can you please tell why is it working in this scenario?

**Comment by glenn-jocher** [comment]
@Ashutosh1995 the validation works without metadata in your Ultralytics-exported engine because the CLI explicitly specifies `task=segment`, which manually sets the task type for validation. When using `trtexec`-exported engines, the model architecture/output format might mismatch the task specification, causing incorrect results. 

Ultralytics exports maintain internal compatibility even without metadata, while third-party exports may not align with expected output formats. For reliable results, always export engines via `model.export(format='engine')` as shown in our [export docs](https://docs.ultralytics.com/modes/export/).
