### ISSUE TITLE
YOLOv8 Changelog

### ISSUE THREAD

**Issue by derek-knox** [ultralytics/ultralytics#5792]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

@glenn-jocher 

1. I can't seem to find a changelog that details and summarizes the fixes, additions, and changes between versions, where is that?
2. Related to the above, have there been any fundamental fixes, additions, or changes that would improve training and thus model performance since v8.0.50 (latest is v8.0.199)?

**Comment by glenn-jocher** [comment]
@derek-knox hello,

Thanks for reaching out.

1. Regarding the changelog: As of currently, we, in the Ultralytics team, don't have a specific document detailing and summarizing the changes between versions for this particular repo. We recommend checking the pull request history and resolved issues as this will give a detailed breakdown of what has been added, changed, or fixed since any version. Additionally, the commit history for the main branch would also provide information on some of the changes.

2. As for the changes from v8.0.50 to v8.0.199: While no fundamental changes that would drastically improve training performance or model outcomes have occurred, there may have been minor bug fixes, code optimizations, and feature additions. These improvements help ensure stability of the model and could indirectly influence your model performance. However, the direct impact of these updates on model training or performance can vary greatly depending on your specific use case, hardware settings, dataset, etc.

As a general practice, we do encourage users to stay updated with the latest version of our models to benefit from any improvements and optimizations made. 

Please let me know if you have any additional questions!

Best,
Glenn
