### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by cainiao123s** [ultralytics/ultralytics#5793]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I trained YOLOV8 using both CPU and GPU, and used the same pre training model. However, the CPU training was normal, and GPU encountered an error: RuntimeError: Python StreamReader failed reading zip archive: failed finding central directory.

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\JetBrains\PyCharm2021.1\scratches\scratch_1.py", line 12, in <module>
    model.train(data="coco128.yaml", epochs=3,device=0)  # 训练模型
  File "C:\Users\Administrator\Desktop\ultralytics-main\ultralytics\engine\model.py", line 341, in train
    self.trainer.train()
  File "C:\Users\Administrator\Desktop\ultralytics-main\ultralytics\engine\trainer.py", line 192, in train
    self._do_train(world_size)
  File "C:\Users\Administrator\Desktop\ultralytics-main\ultralytics\engine\trainer.py", line 288, in _do_train
    self._setup_train(world_size)
  File "C:\Users\Administrator\Desktop\ultralytics-main\ultralytics\engine\trainer.py", line 234, in _setup_train
    self.amp = torch.tensor(check_amp(self.model), device=self.device)
  File "C:\Users\Administrator\Desktop\ultralytics-main\ultralytics\utils\checks.py", line 569, in check_amp
    assert amp_allclose(YOLO('yolov8n.pt'), im)
  File "C:\Users\Administrator\Desktop\ultralytics-main\ultralytics\engine\model.py", line 97, in __init__
    self._load(model, task)
  File "C:\Users\Administrator\Desktop\ultralytics-main\ultralytics\engine\model.py", line 149, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "C:\Users\Administrator\Desktop\ultralytics-main\ultralytics\nn\tasks.py", line 628, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "C:\Users\Administrator\Desktop\ultralytics-main\ultralytics\nn\tasks.py", line 567, in torch_safe_load
    return torch.load(file, map_location='cpu'), file  # load
  File "E:\APP\Anaconda\envs\pytorch\lib\site-packages\torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "E:\APP\Anaconda\envs\pytorch\lib\site-packages\torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

Process finished with exit code 1

**Comment by cainiao123s** [comment]
from ultralytics import YOLO


model = YOLO("yolov8x.yaml")  
model = YOLO(r"C:\Users\Administrator\Desktop\yolov8x.pt")  

model.train(data="coco128.yaml", epochs=3,device=0)  
metrics = model.val()  
results = model("https://ultralytics.com/images/bus.jpg")  
success = model.export(format="onnx")

**Comment by glenn-jocher** [comment]
@cainiao123s the error message seems to be telling you that Pytorch is unable to read the zipped weight file. This may occur due to the corruption of the weight file during download or any interruption in the process.

Try to delete the weight file and then download it again. Make sure that the download is done successfully without any interruption. Then try running your code again. If you are still facing an issue, feel free to reach out.

**Comment by cainiao123s** [comment]
Thank you for your reply. After I replaced another computer, the code ran successfully. Friends who have encountered the same problem can refer to my experience

**Comment by cainiao123s** [comment]
> @cainiao123s the error message seems to be telling you that Pytorch is unable to read the zipped weight file. This may occur due to the corruption of the weight file during download or any interruption in the process.
> 
> Try to delete the weight file and then download it again. Make sure that the download is done successfully without any interruption. Then try running your code again. If you are still facing an issue, feel free to reach out.

Thank you for your reply. After I replaced another computer, the code ran successfully. Friends who have encountered the same problem can refer to my experience

**Comment by glenn-jocher** [comment]
@cainiao123s i'm glad to hear that your issue has been resolved by switching to a different computer. Indeed, various factors including hardware, operating system, and installed libraries can impact the running of the code. Your experience could be helpful to others who encounter a similar problem. Thank you for sharing your solution and don't hesitate to reach out if you have any other questions or issues. Keep exploring with YOLOv8!

**Comment by devinkain** [comment]
> the error message seems to be telling you that Pytorch is unable to read the zipped weight file. This may occur due to the corruption of the weight file during download or any interruption in the process.

I am facing the same issue but am not sure what "zipped weight file" you are referring to or where it can be found.  Could you please elaborate?

Thank you!

**Comment by glenn-jocher** [comment]
@devinkain hello, the "zipped weight file" comment refers to how PyTorch reads the weight file of the model. PyTorch uses a special type of file format (`*.pt`, `*.pth`), which under the hood is a serialized zip file, to store all the information pertaining to a model. This includes the model architecture and learned parameters. 

Just to clarify, even though these files are not standard zip archives, they are serialized in such a way that is similar to how zip archives are structured.

The message "PytorchStreamReader failed reading zip archive" typically implies that Pytorch is encountering a problem when it's trying to deserialize these files. This could be because the file has been corrupted, perhaps during the downloading process.

Given that you're seeing this error on a Linux server, my initial suggestion would be to check the integrity of the downloaded file. You can't open it like a regular zip file, but you could try re-downloading the model weights to ensure you have a clean, complete copy. Also, ensure that your PyTorch version is up-to-date and compatible with the YOLOv8 model.

**Comment by devinkain** [comment]
@glenn-jocher Thank you so much for the detailed response!  I believe I understand much better now. I was getting lost in the terminology. :)  I was able to solve the issue by deleting and then creating a new virtual environment on the server.  Which makes me think that you're correct in that the "zipped" weight file" was corrupted when initially uploading all files to the server. 

Thanks again!

**Comment by glenn-jocher** [comment]
@devinkain i'm delighted to hear that you were able to resolve the issue by setting up a new virtual environment on your server. You're absolutely right—a fresh environment can often eliminate potential conflicts or corruption that may have occurred during the initial file transfer process. It's wonderful that you found your way through the terminology, and I'm glad the explanation was helpful.

Should you encounter any further difficulties or have more questions as you continue working with YOLOv8, please don't hesitate to reach out. We're here to support you and ensure you have a smooth experience with the tool. Best of luck with your continued work!

**Comment by zhangfatin** [comment]
lack of ultralytics

**Comment by glenn-jocher** [comment]
@zhangfatin apologies for any confusion, but it seems there may have been a partial or mistaken message. If you have further questions or need assistance with Ultralytics products such as YOLOv8 or any other offerings, please don't hesitate to ask for guidance or clarification. The Ultralytics community and support are here to help, and we value the time and effort you invest in using our models and tools. Let's keep the conversation productive and focused on your needs. 😊🚀

**Comment by goldwater668** [comment]
@glenn-jocher 
    Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    255/300      16.8G     0.5907     0.3506     0.9087        230        640:  39%|███▊      | 186/481 [02:45<02:40,  1.84it/s]tee: train_log1129.txt: No space left on device
    255/300      16.8G     0.5927     0.3521     0.9085        152        640: 100%|██████████| 481/481 [07:12<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:18<00:00,  1.48it/s]
                   all       6840       6880      0.997      0.998      0.995       0.89
Traceback (most recent call last):
  File "/home/anaconda2/envs/hrg/lib/python3.8/site-packages/torch/serialization.py", line 441, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/home/anaconda2/envs/hrg/lib/python3.8/site-packages/torch/serialization.py", line 668, in _save
    zip_file.write_record(name, storage.data_ptr(), num_bytes)
RuntimeError: [enforce fail at inline_container.cc:471] . PytorchStreamWriter failed writing file data/807: file write failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_hand_detect.py", line 11, in <module>
    model.train(data='hrg_merge.yaml', epochs=300, imgsz=640, batch=128, cache=True, device=0,degrees=90)
  File "/home/hrg/ultralytics/ultralytics/engine/model.py", line 341, in train
    self.trainer.train()
  File "/home/hrg/ultralytics/ultralytics/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/home/hrg/ultralytics/ultralytics/engine/trainer.py", line 391, in _do_train
    self.save_model()
  File "/home/hrg/ultralytics/ultralytics/engine/trainer.py", line 439, in save_model
    torch.save(ckpt, self.last)
  File "/home/hrg/ultralytics/ultralytics/utils/patches.py", line 77, in torch_save
    return _torch_save(*args, **kwargs)
  File "/home/anaconda2/envs/hrg/lib/python3.8/site-packages/torch/serialization.py", line 442, in save
    return
  File "/home/anaconda2/envs/hrg/lib/python3.8/site-packages/torch/serialization.py", line 291, in __exit__
    self.file_like.write_end_of_file()
RuntimeError: [enforce fail at inline_container.cc:337] . unexpected pos 15103936 vs 15103888

Suddenly the above error was reported, and then I resumed the training interruption code again, and the following error was reported again.
YOLOv8n-hand summary: 225 layers, 3011823 parameters, 3011807 gradients, 8.2 GFLOPs

Traceback (most recent call last):
  File "train_hand_detect.py", line 10, in <module>
    model = YOLO('/home/hrg/ultralytics/runs/detect/train2/weights/last.pt')
  File "/home/hrg/ultralytics/ultralytics/engine/model.py", line 97, in __init__
    self._load(model, task)
  File "/home/hrg/ultralytics/ultralytics/engine/model.py", line 149, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/home/hrg/ultralytics/ultralytics/nn/tasks.py", line 628, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/home/hrg/ultralytics/ultralytics/nn/tasks.py", line 567, in torch_safe_load
    return torch.load(file, map_location='cpu'), file  # load
  File "/home/anaconda2/envs/hrg/lib/python3.8/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/anaconda2/envs/hrg/lib/python3.8/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by glenn-jocher** [comment]
@goldwater668 it seems like you've encountered a disk space issue during model training, followed by serialization issues when trying to load a model checkpoint.

The initial error:
```
tee: train_log1129.txt: No space left on device
```
This indicates that your disk has run out of space. Make sure you have adequate disk space available to save model checkpoints and logs.

Following that, during the saving process, PyTorch encountered an error:
```
RuntimeError: [enforce fail at inline_container.cc:471] . PytorchStreamWriter failed writing file data/807: file write failed
```
This is typically related to the disk space issue mentioned above where PyTorch was unable to write the model's state to the file.

Finally, when trying to resume training or load a model from a checkpoint (`last.pt`), your script failed due to corruption of the checkpoint file, probably caused by the previous disk space problem:
```
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

To resolve this issue:
1. Clear enough disk space or add storage to your device.
2. Make sure all required directories exist and your user has write permissions.
3. Remove any potentially corrupted `.pt` files from the interrupted training process.
4. Restart the training process with monitoring to ensure disk space does not run out again.

Always keep an eye on the storage capacity when running training jobs, especially for large datasets or models, to prevent such occurrences.

**Comment by tkefauver** [comment]
@cainiao123s I got this same error. Downloading the file manually from the URL before the exception from a web browser works.

**Comment by mudassir659** [comment]
!python train.py --batch 12 --epochs 500 --data /content/yolov7/palm-tree-detection-1/data.yaml  --weights '/content/drive/MyDrive/last (6).pt' --cache 
2024-02-21 16:17:59.252886: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-21 16:17:59.252934: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-21 16:17:59.254223: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-21 16:17:59.261453: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-21 16:18:00.233503: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
YOLOR 🚀 v0.1-128-ga207844 torch 2.1.0+cu121 CUDA:0 (Tesla T4, 15102.0625MB)

Namespace(weights='/content/drive/MyDrive/last (6).pt', cfg='', data='/content/yolov7/palm-tree-detection-1/data.yaml', hyp='data/hyp.scratch.p5.yaml', epochs=500, batch_size=12, img_size=[640, 640], rect=False, resume=False, nosave=False, notest=False, noautoanchor=False, evolve=False, bucket='', cache_images=True, image_weights=False, device='', multi_scale=False, single_cls=False, adam=False, sync_bn=False, local_rank=-1, workers=8, project='runs/train', entity=None, name='exp', exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, upload_dataset=False, bbox_interval=-1, save_period=-1, artifact_alias='latest', freeze=[0], v5_metric=False, world_size=1, global_rank=-1, save_dir='runs/train/exp5', total_batch_size=12)
tensorboard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/
hyperparameters: lr0=0.01, lrf=0.1, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.3, cls_pw=1.0, obj=0.7, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.2, scale=0.9, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.15, copy_paste=0.0, paste_in=0.15, loss_ota=1
Traceback (most recent call last):
  File "/content/yolov7/train.py", line 616, in <module>
    train(hyp, opt, device, tb_writer)
  File "/content/yolov7/train.py", line 71, in train
    run_id = torch.load(weights, map_location=device).get('wandb_id') if weights.endswith('.pt') and os.path.isfile(weights) else None
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 993, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 447, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
i have saved the last.pt file my training was stoped due to runtime disconnected issue in colab at 126 epoch. Now i am trying to restart the training but it shows this error its in yolov7x

**Comment by glenn-jocher** [comment]
@mudassir659 hey there! It looks like the `.pt` file you're trying to load might be corrupted, possibly due to the runtime disconnection in Colab. Here's a quick thing you could try:

1. Check if the file size of `last (6).pt` seems reasonable compared to your other saved `.pt` files. If it's significantly smaller, it's likely incomplete.
2. If you have a previous checkpoint that's not corrupted, try resuming from that one instead.
3. If you don't have a backup, you might need to restart the training from the last successful epoch you have saved.

To avoid this in the future, consider saving checkpoints more frequently if you're facing frequent disconnections. Hope this helps! 😊👍

**Comment by XYQDUT** [comment]
I resolved the issue by deleting the model weight file and rerunning the program.

**Comment by glenn-jocher** [comment]
Hi @XYQDUT,

Great to hear that you resolved the issue by deleting the model weight file and rerunning the program! Sometimes, file corruption can occur, especially in environments like Colab where interruptions are common.

For future reference, if you encounter similar issues, it's always a good idea to keep multiple checkpoints during training. This way, you can resume from the last good checkpoint without losing too much progress.

If you have any more questions or run into other issues, feel free to ask. Happy training! 😊

**Comment by N1ISSET** [comment]
E:\ultralytics-main\.venv\Scripts\python.exe E:\ultralytics-main\train.py 
Transferred 475/475 items from pretrained weights
New https://pypi.org/project/ultralytics/8.3.41 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.2.77 🚀 Python-3.11.10 torch-2.5.1+cu124 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
engine\trainer: task=detect, mode=train, model=yolov8m.pt, data=Profile.yaml, epochs=100, time=None, patience=100, batch=4, imgsz=640, save=True, save_period=-1, cache=True, device=0, workers=2, project=None, name=train12, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs\detect\train12
Overriding model.yaml nc=80 with nc=3

                   from  n    params  module                                       arguments                     
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]                 
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]                
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]             
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]               
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]           
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]              
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]           
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]              
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]           
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]                 
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]                 
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]                 
 22        [15, 18, 21]  1   3777433  ultralytics.nn.modules.head.Detect           [3, [192, 384, 576]]          
Model summary: 295 layers, 25,858,057 parameters, 25,858,041 gradients

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
Traceback (most recent call last):
  File "E:\ultralytics-main\train.py", line 29, in <module>
    results = model.train(data="Profile.yaml", epochs=100, imgsz=640, device=0, workers=2, batch=4, cache=True) # 开始训练
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ultralytics-main\ultralytics\engine\model.py", line 811, in train
    self.trainer.train()
  File "E:\ultralytics-main\ultralytics\engine\trainer.py", line 208, in train
    self._do_train(world_size)
  File "E:\ultralytics-main\ultralytics\engine\trainer.py", line 327, in _do_train
    self._setup_train(world_size)
  File "E:\ultralytics-main\ultralytics\engine\trainer.py", line 266, in _setup_train
    self.amp = torch.tensor(check_amp(self.model), device=self.device)
                            ^^^^^^^^^^^^^^^^^^^^^
  File "E:\ultralytics-main\ultralytics\utils\checks.py", line 665, in check_amp
    assert amp_allclose(YOLO("yolov8n.pt"), im)
                        ^^^^^^^^^^^^^^^^^^
  File "E:\ultralytics-main\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "E:\ultralytics-main\ultralytics\engine\model.py", line 142, in __init__
    self._load(model, task=task)
  File "E:\ultralytics-main\ultralytics\engine\model.py", line 294, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ultralytics-main\ultralytics\nn\tasks.py", line 855, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ultralytics-main\ultralytics\nn\tasks.py", line 781, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ultralytics-main\ultralytics\utils\patches.py", line 86, in torch_load
    return _torch_load(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ultralytics-main\.venv\Lib\site-packages\torch\serialization.py", line 1326, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ultralytics-main\.venv\Lib\site-packages\torch\serialization.py", line 671, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted

I faced this problem also. I download the newest `yolov8m.pt` in yolo website. I checked pytorch and it is available. CUDA also install correctly. And I tried a new conda environment with python version of 3.11. I don't know how can I solve this problem.

**Comment by glenn-jocher** [comment]
It seems that the downloaded `yolov8m.pt` file may be corrupted or incomplete. Please try the following steps to resolve the issue:

1. **Re-download the `yolov8m.pt` weights**: Delete the current file and download it again from the [Ultralytics Models Page](https://docs.ultralytics.com/models/yolov8). Ensure the download completes successfully without interruptions.
2. **Verify File Integrity**: Confirm the file size matches the expected size of `yolov8m.pt`. A significantly smaller size could indicate a corrupted download.
3. **Check Torch and CUDA Versions**: Ensure your PyTorch version is compatible with your CUDA version. Use `import torch; print(torch.version.cuda)` and `print(torch.cuda.is_available())` to verify compatibility.
4. **Try Another Environment**: If re-downloading does not work, try running the script in a different environment or on a different system to rule out potential local issues.

If the problem persists after these steps, feel free to provide additional details for further assistance.

**Comment by N1ISSET** [comment]
> It seems that the downloaded `yolov8m.pt` file may be corrupted or incomplete. Please try the following steps to resolve the issue:
> 
> 1. **Re-download the `yolov8m.pt` weights**: Delete the current file and download it again from the [Ultralytics Models Page](https://docs.ultralytics.com/models/yolov8). Ensure the download completes successfully without interruptions.
> 2. **Verify File Integrity**: Confirm the file size matches the expected size of `yolov8m.pt`. A significantly smaller size could indicate a corrupted download.
> 3. **Check Torch and CUDA Versions**: Ensure your PyTorch version is compatible with your CUDA version. Use `import torch; print(torch.version.cuda)` and `print(torch.cuda.is_available())` to verify compatibility.
> 4. **Try Another Environment**: If re-downloading does not work, try running the script in a different environment or on a different system to rule out potential local issues.
> 
> If the problem persists after these steps, feel free to provide additional details for further assistance.

Thank you for your reply! I already solved problem by downloading `yolov8n.pt` and `yolov8m.pt` again. Seems `yolov8n.pt` was corrupted for some reasons.

**Comment by glenn-jocher** [comment]
Great to hear you resolved the issue by re-downloading the files! Corruption during download can occasionally happen, and starting fresh is often the best solution. If you encounter any further issues, feel free to reach out. Happy training!

**Comment by cainiao123s** [comment]
I didn't expect that many people had encountered the same bug I did, and I'm happy to be able to provide some help to everyone.

**Comment by glenn-jocher** [comment]
Thank you for contributing to the discussion and helping others in the community! Your input is invaluable for improving the collective experience with Ultralytics.
