### ISSUE TITLE
RT-DETR missing module 

### ISSUE THREAD

**Issue by walywalid** [ultralytics/ultralytics#5794]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

When running anything with RTDETR, following error comes 

ModuleNotFound: No module named 'ultralytics.vit'

Tried with ultralytics version 8.0.200 / 8.0.199/ 8.0.91

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@walywalid thank you for bringing this to our attention! 

From the error message you provided, it seems that the 'ultralytics.vit' module is missing. This could be due to a few potential reasons: your Ultralytics package may not be fully up to date, or there could be an installation issue causing some modules not to be found.

In general, to solve this issue, the first step would be to ensure that you have the latest version of Ultralytics installed. Even though you've tried multiple versions, there's a possibility that the module is available in a different version. Make sure to check the specific requirements for running RT-DETR, as certain modules might only be available in certain versions of the package.

As a next step, you could try uninstalling and then reinstalling the package, as this could potentially solve any installation issues that might have occurred. 

If these steps do not resolve your issue, I would recommend submitting a detailed bug report including your environment details, python version, and more detailed steps to reproduce the issue. This will help us identify and solve the problem more efficiently.

Feel free to keep us updated on your progress and don't hesitate to ask if you have any further questions or encounter any more issues. We're here to help!
