### ISSUE TITLE
Empty Files when Converting from COCO to YOLO Format

### ISSUE THREAD

**Issue by MercedesMarzoa** [ultralytics/ultralytics#5800]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

I'm using CVAT to label data for instance segmentation, and I'm looking to utilize it with the YOLO version of instance segmentation. Since the YOLO format isn't available for direct download, I'm opting to download the data in COCO format and then use the `convert_coco` function.

Here's the code I'm using:

```python
from ultralytics.data.converter import convert_coco
convert_coco(labels_dir='path/to/coco/annotations/', use_segments=True)
```

However, this creates the corresponding folder with one file for each image, but these files are empty.

The output in the terminal is as follows:

```
Annotations  annot/instances_default.json: 100%|██████████| 8/8 [00:00<00:00, 5495.32it/s]
COCO data converted successfully.
Results saved to /home/meche/tmp
```

I'm working with the sample file downloaded from CVAT.
[instances_default.json](https://github.com/ultralytics/ultralytics/files/13035581/instances_default.json)

Any ideas on what might be causing this issue?

Thanks!

### Environment

```
Ultralytics YOLOv8.0.197 🚀 Python-3.8.10 torch-1.9.0+cpu CPU (AMD Ryzen 5 3450U with Radeon Vega Mobile Gfx)
Setup complete ✅ (8 CPUs, 13.7 GB RAM, 198.9/233.2 GB disk)

OS                  Linux-5.4.0-153-generic-x86_64-with-glibc2.29
Environment         Linux
Python              3.8.10
Install             pip
RAM                 13.66 GB
CPU                 AMD Ryzen 5 3450U with Radeon Vega Mobile Gfx
CUDA                None

matplotlib          ✅ 3.4.2>=3.3.0
numpy               ✅ 1.24.4>=1.22.2
opencv-python       ✅ 4.8.0.74>=4.6.0
pillow              ✅ 9.3.0>=7.1.2
pyyaml              ✅ 6.0>=5.3.1
requests            ✅ 2.25.1>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 1.9.0+cpu>=1.8.0
torchvision         ✅ 0.10.0+cpu>=0.9.0
tqdm                ✅ 4.65.0>=4.64.0
pandas              ✅ 1.2.3>=1.1.4
seaborn             ✅ 0.11.1>=0.11.0
psutil              ✅ 5.5.1
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MercedesMarzoa hi,

Thanks for providing comprehensive information about the problem you are facing, it indeed helps a lot!

Firstly, it appears your images have been labeled correctly in CVAT, but the use of the `convert_coco` function is not generating the expected output. This function processes a COCO-formatted JSON file containing your annotations and converts them into the YOLO format. Each image would then have a corresponding .txt file containing the object details.

If the generated files are empty, this might suggest that no valid objects were identified in your images. The `convert_coco` function is designed to ignore unlabeled or invalidly labeled objects in the dataset, it could potentially be the reason why the generated files are empty. 

Although the function logged `COCO data converted successfully.`, it might be skipping or failing to recognize your objects due to a discrepancy in the labeling. For instance, it could be a problem with the category ids assigned to your labels: if they don't match the ids in the function's category map, they will be ignored.

Please validate the labels in your annotation JSON file, check the consistency of category ids, and ensure each object contains a complete set of details (for instance, bounding box and class id for detection task). 

Hope this helps and let us know if the problem persists!

**Comment by MercedesMarzoa** [comment]
Thank you for your response!

I've been using CVAT for labeling and, as I'm tagging with SAM, the labels are in the form of masks. When I download the data, it sets the iscrowd parameter to 1. I'm wondering if convert_coco can handle such cases?

I've reviewed the .yaml file, and I also uploaded the data to Roboflow, which displays the labels correctly. It seems like there's consistency, but I want to ensure that I'm on the right track.

Thank you once again!

**Comment by glenn-jocher** [comment]
Hi @MercedesMarzoa,

The `convert_coco` function is designed to convert bounding box coordinates in the COCO JSON annotations to the YOLO format. In your case, since you're using the 'Segmentation Annotation Mode' (SAM) in CVAT, the labels are in form of masks with the `iscrowd` parameter set to 1. This might be causing the issue, since the handler is designed primarily for bounding box annotations and may not correctly process the mask data or `iscrowd` values.

While we strive to support a wide variety of use cases, handling masks could be outside the current capabilities of the `convert_coco` function. We appreciate your understanding and patience on this matter. We'll consider your feedback as we continue to develop and improve our converter function.

For now, you might need to use a different tool or function to convert your mask annotations to the YOLO format. Various open source tools are available online that might serve for your needs. Thanks again for bringing this to our attention!

**Comment by MercedesMarzoa** [comment]
Thanks so much for the help.

**Comment by glenn-jocher** [comment]
You're welcome, @MercedesMarzoa! If you encounter any further issues or have more questions, don't hesitate to reach out. Best of luck with your project, and we truly appreciate your contributions to the community. Happy labeling! 😊
