### ISSUE TITLE
Ultralytics not sharing gpu with PaddlePaddle

### ISSUE THREAD

**Issue by EmielFeryn1** [ultralytics/ultralytics#5809]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I wrote a program that detects license plates using yolov8 that are then being read by PaddleOCR.

Unfortunately when trying to use the GPU for both of these packages I get following error.

Traceback (most recent call last):
  File ".\docker\main2.py", line 2, in <module>
    from docker.model_handlers.object_detect_handler import ObjectDetectHandler
  File ".\docker\model_handlers\object_detect_handler.py", line 6, in <module>
    from docker.model_handlers.ensemble_model import EnsembleModel
  File ".\docker\model_handlers\ensemble_model.py", line 6, in <module>
    from ultralytics import YOLO
  File ".\venv\lib\site-packages\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO
  File ".\venv\lib\site-packages\ultralytics\models\__init__.py", line 3, in <module>
    from .rtdetr import RTDETR
  File ".\venv\lib\site-packages\ultralytics\models\rtdetr\__init__.py", line 3, in <module>
    from .model import RTDETR
  File ".\venv\lib\site-packages\ultralytics\models\rtdetr\model.py", line 5, in <module>
    from ultralytics.engine.model import Model
  File ".\venv\lib\site-packages\ultralytics\engine\model.py", line 8, in <module>
    from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
  File ".\venv\lib\site-packages\ultralytics\cfg\__init__.py", line 10, in <module>
    from ultralytics.utils import (ASSETS, DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, RANK, SETTINGS,
  File ".\venv\lib\site-packages\ultralytics\utils\__init__.py", line 21, in <module>
    import torch
  File ".\venv\lib\site-packages\torch\__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
RuntimeError: generic_type: type "_CudaDeviceProperties" is already registered!

**Comment by glenn-jocher** [comment]
@EmielFeryn1 hi there,

The issue you're experiencing typically occurs when two or more scripts are trying to access the GPU simultaneously. Both YOLOv8 and PaddleOCR want to initialize CUDA, and this conflict results in the error message you're seeing.

To resolve the issue, you can try running your YOLOv8 and PaddleOCR tasks sequentially rather than concurrently. This allows each package to initialize CUDA without interfering with the other.

You may also want to ensure that both packages are compatible with your CUDA and GPU versions. You can verify this by checking the respective documentation for each package.

If running the tasks sequentially is not an option due to your workflow, you could consider setting up two GPUs if your system allows it. This way, each process could run on a separate GPU concurrently.

Let us know if this information helps, or if you have any other questions.

Thanks!

**Comment by mleibi** [comment]
Hi Glenn,
Could explain this a bit deeper because I get the same error message when initializing both YOLO and paddleOCR in one program. I'd like to analyze Videosignal in near-Realtime (<2s). I use Yolo to segment and PaddleOCR to recognize text and this works very well. However the main concern is speed which im trying to improve now with GPU.  I can't batch the task to execute segmentation and text recognition sequentially. Do you see 2 separate GPU's as the only solution for this challenge?
Thank you and BW
Matthias

**Comment by glenn-jocher** [comment]
@mleibi hi Matthias,

To avoid the CUDA conflict, you can try setting the environment variable `CUDA_VISIBLE_DEVICES` to isolate GPU usage for each process. If sequential execution isn't feasible, using two separate GPUs is indeed a practical solution.

**Comment by alexandar-m** [comment]
Solution for this is to use older paddlepaddle version, i think 2.5.2 works just fine, will check it. Had same issue after upgradimg paddlepaddle. Upgrading paddleocr is not a problem.

**Comment by glenn-jocher** [comment]
@alexandar-m thank you for sharing your solution. Using an older version of `paddlepaddle-gpu` can indeed help resolve compatibility issues. If you have further questions or need assistance, feel free to ask.

**Comment by alexandar-m** [comment]
Working environment:
Windows 10/11

python-3.10.11-amd64
cuda_11.7.1_516.94_windows
cudnn-windows-x86_64-8.4.1.50_cuda11.6-archive

opencv-contrib-python 4.6.0.66
opencv-python 4.6.0.66
paddleocr 2.8.1
paddlepaddle-gpu 2.4.2.post117
torch 1.13.1+cu117
torchaudio 0.13.1+cu117
torchvision 0.14.1+cu117
ultralytics 8.3.2
ultralytics-thop 2.0.8

**Comment by glenn-jocher** [comment]
Hi @test3211234, the error occurs due to CUDA conflicts when multiple libraries (like PyTorch, PaddleOCR, etc.) initialize the GPU. To resolve this without downgrading, try isolating GPU usage by setting `CUDA_VISIBLE_DEVICES` for each library or using separate Python environments. If that doesn't work, consider sequential execution of tasks or using different GPUs for each library. Let us know if you need further clarification!

**Comment by glenn-jocher** [comment]
You're welcome! Glad to hear it's working now. Let us know if you run into any other issues.

**Comment by therysin** [comment]
> I think it's all good, I had to download the beta version of PaddlePaddle. Thanks!

Hi, do you have a link or version of this beta?

**Comment by therysin** [comment]
> I think it's not beta anymore now, just 3.0.
> 
> https://www.paddlepaddle.org.cn/en/install/quick?docurl=/documentation/docs/en/install/docker/macos-docker_en.html

Thanks, confirming 3.0 works.
