### ISSUE TITLE
Custom trained model detecting one object multiple times

### ISSUE THREAD

**Issue by sujonahmed2500** [ultralytics/ultralytics#5814]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trained yolov8 with my custom data. but when I run a video by my trained model. 
Sometimes it detects one object multiple times. 
Like It shows multiple bounding boxes for one object.

Why it happens? Let me know if need anything else. 

My code:

results = model.track(frame, persist=True, conf=0.5) 
result = results[0]
frame = result.orig_img
detections = sv.Detections.from_yolov8(result)
detections = byte_tracker.update_with_detections(detections)
labels = [
    f"{tracker_id} {model.model.names[class_id]} {confidence:0.2f}"
    for _, _, confidence, class_id, tracker_id
    in detections
]

**Comment by Johan154** [comment]
You can use the iou parameter for model.track. For examp,e when you set iou=0.5 (default iou=0.7), predicted boxes are not allowed to overlap each other for more than 50%. So in your case, try this:

results = model.track(frame, persist=True, conf=0.5, iou=0.3)

**Comment by sujonahmed2500** [comment]
Thanks @Johan154 ,
I think it helps a little bit. but also detecting some objects multiple times. when running the video it shows two boxes for some objects. 
Is there anything else I can do?

**Comment by glenn-jocher** [comment]
@sujonahmed2500 the issue you're facing is likely due to non-maximum suppression (NMS) not being able to fully eliminate overlapping detections. Here are some suggestions that you may find helpful:

1. Adjust the confidence threshold: Try increasing the confidence threshold a bit more, so the model only considers higher confident detections. Note that setting it too high might result in missed detections.

2. Adjust Intersection over Union (IoU) threshold: The IoU threshold in the non-maximum suppression function determines how much a box should overlap with another for only one to be kept. Try adjusting this threshold.

3. Revisit your training process: Sometimes, multiple detections for the same object can occur if the model has not been trained adequately or the dataset has overlapping/incorrect annotations.

Remember that object detection is a balance between precision and recall. Fine-tuning these parameters can help you achieve the desired results.

**Comment by zburq** [comment]
I have the same problem. 
- I think this is an `nms` problem, not an `IoU` problem.
- The duplicate detections on a single objects should be eliminated before `IoU` is checked. 
- Also, the only reason I understand `nms` would fail is if some of the confidence (class probabilities) are identical.  In my duplicate detections, class probabilities were different.

**Comment by glenn-jocher** [comment]
@zburq hey there! 🌟 You're right in pointing out that NMS's role is crucial in eliminating duplicate detections. It sounds like your diagnosis is spot-on, focusing on how NMS operates with varying confidence levels could be key. Although confidence scores differ, if they're both above your threshold, NMS would consider them. A subtle adjustment in the `conf` and `iou` thresholds might help. Another angle could be checking the diversity in your dataset to ensure robust learning. Keep experimenting! 🛠️

Quick code tweak suggestion:

```python
results = model.track(frame, persist=True, conf=0.55, iou=0.35)
```
Tweaking these values may provide a better balance. Happy coding!
