### ISSUE TITLE
Problem with the bounding box when a single instance is detected.

### ISSUE THREAD

**Issue by carlos-osorio-alcalde** [ultralytics/ultralytics#5817]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am creating a home security system using a security camera that I bought (Tapo C200). Basically, I want to track my car and the people who pass near the car and make sure that they don't stay for a long time there. 

Since I only want to track cars and people, the base models should work ok for my application. However, I am obtaining a wrong bounding box when only one instance is detected. If I have more than one instance in the detection from any class, then the bounding box is ok.

**Only one instance of a car detected:**
<img width="1070" alt="Screenshot 2023-10-19 at 12 00 01 PM" src="https://github.com/ultralytics/ultralytics/assets/132937575/ce1e9a33-9532-49b7-b03a-95bc2c785fd8">

**An instance from a car and a person**
<img width="1025" alt="Screenshot 2023-10-19 at 11 59 51 AM" src="https://github.com/ultralytics/ultralytics/assets/132937575/fec7f559-06d8-4571-aab5-e4459ae490c1">

I am using the _yolov8m_ here on a M1 MacBook Air. However, I have tried all the versions and the behavior is exactly the same. Additionally, the configuration of the predictions is as follows:

`    results = model.predict(
        frame,
        device="mps",
        conf=0.35,
        classes=[0, 2],
        verbose=True,
        iou=0.8,
    )`

Strictly speaking, this isn't a problem for my application since my use case only makes sense when there is a car and a person in the image, and in that case, everything works ok.

However, I'd like to understand why is this likely happening.

Thank you.

**Comment by glenn-jocher** [comment]
@carlos-osorio-alcalde hi, thank you for detailed explanation along with the images. From your description, it seems like the bounding box is getting skewed or inaccurate when only a single instance (e.g., a car) is present in the image, but works fine when there are multiple instances (e.g., a car and a person).

This is unusual behavior as the model is trained to detect multiple classes independently, and the number of instances detected shouldn't affect the bounding box accuracy of other instances.

One possible reason could be the interplay between confidence score and Intersection over Union (IOU) during non-maximum suppression process, which might be affecting the bounding box accuracy with only a single instance. The "conf" parameter you used in the model.predict() function is a threshold value for object confidence score, and the "iou" parameter is a threshold value for non-maximum suppression. They could be tuned to improve detection results.

The other possibility could be scale variations. If the size of the car in the image changes significantly when people are also present, it might induce errors in bounding box.

Despite these potential causes, without an in-depth look into the specific instances and debugging, it's difficult to confirm the exact source of the problem. An examination of the score and bounding box coordinates could be insightful.

Given your application requirement, this may not be a pressing issue. However, your observation is valuable to us and will assist us in continuously improving our models. We appreciate you drawing our attention to this.

**Comment by carlos-osorio-alcalde** [comment]
I have some updates regarding this...

The problem, somehow, seems to be related to the part of `device='mps'`. Indeed, I made a couple of experiments with `yolov8l`, and here are the results:

**Original image**
![picanto_blanco](https://github.com/ultralytics/ultralytics/assets/132937575/8ded9e56-89e9-46e5-9226-379d6eb4e954)

**Results with `device='mps'`**
![image_2023-10-20_100451632](https://github.com/ultralytics/ultralytics/assets/132937575/f72ada76-6cac-4756-b3c1-60b4396f9b6c)

```
model = YOLO('yolov8l.pt')
image_path = 'picanto_blanco.png'
image = cv2.imread(image_path)
results = model.predict(image_path, device='mps')
```

**Results without `device='mps'`**
![image_2023-10-20_100922900](https://github.com/ultralytics/ultralytics/assets/132937575/82a9ceb3-bf9b-4cfb-84e3-acb52c567037)
```
model = YOLO('yolov8l.pt')
image_path = 'picanto_blanco.png'
image = cv2.imread(image_path)
results = model.predict(image_path)
```

The problem also occurs for different classes, not only for the car class. It seems that other people are experiencing something similar, as stated here #1090.

Thank you for the amazing work on this!

**Comment by Any-Winter-4079** [comment]
I am experiencing the same issue. Code:

```
from ultralytics import YOLO

model = YOLO('yolov8n.pt')

results = model(source=1, show=True, conf=0.7, save=False, device="mps")

```
If we look at the purple line I placed, you can see as I move, there is one side of the bounding box that is fixed, so the box gets smaller, then has almost width=0, then it goes past the purple line. So basically, one side of the bounding box is fixed (and shouldn't).
<img width="887" alt="Screenshot 2023-10-20 at 20 29 57" src="https://github.com/ultralytics/ultralytics/assets/50542132/1b5df153-b2a1-421a-bc0e-595e9e5892d3">

<img width="889" alt="Screenshot 2023-10-20 at 20 29 47" src="https://github.com/ultralytics/ultralytics/assets/50542132/34647b36-0263-4eeb-ba0b-866bb2e0257e">

<img width="890" alt="Screenshot 2023-10-20 at 20 29 37" src="https://github.com/ultralytics/ultralytics/assets/50542132/ecb3aca6-68a9-4eb2-b1e7-c845c02999ba">

<img width="888" alt="Screenshot 2023-10-20 at 20 29 29" src="https://github.com/ultralytics/ultralytics/assets/50542132/d624d125-d395-4213-bb4a-3a606d9645e6">


```
from ultralytics import YOLO

model = YOLO('yolov8n.pt')

results = model(source=1, show=True, conf=0.7, save=False, device="cpu")
```

This works well.

**Comment by glenn-jocher** [comment]
@carlos-osorio-alcalde thank you for sharing your observations, they're quite thorough and provide insights into the problem you're facing.

As per your observations with the 'mps' device mode, it seems there is an issue with the bounding box coordinates which is causing one side of the box to be fixed during detection. The fact it's functioning as expected in 'cpu' mode indicates it isn't related to the detection process per se but likely an issue specific to the processing with 'mps'.

The box coordinates you've posted reveal inconsistencies when the model transitions between single and multiple detection situations. As you pointed out, even for the same object, the first value of the coordinates seems to differ significantly. This suggests that there might be some sort of anchoring issue happening in 'mps' mode causing the fixed bounding box side.

Again, a possible explanation could be the interplay of confidence scores and Intersection over Union (IoU) thresholds during the non-max suppression process. However, the exact root cause can't be confirmed without an in-depth investigation. 

It would be really helpful to further investigate these unusual behaviors under 'mps' mode. This feedback could also lead to improvements in detection accuracy and reliability.

We really appreciate you bringing this to our attention. Your continued support helps us improve our models and the overall user experience.

**Comment by bog** [comment]
I saw similar on my Mac. Downgrading to `torch-2.0.1` and `torchvision-0.15.2` (from `torch-2.1.0` and `torchvision 0.16.0` fixed the issue for me. Not being sure what the problem was, I wasn't sure how to report it.

**Comment by carlos-osorio-alcalde** [comment]
> I saw similar on my Mac. Downgrading to `torch-2.0.1` and `torchvision-0.15.2` (from `torch-2.1.0` and `torchvision 0.16.0`) fixed the issue for me. Not being sure what the problem was, I wasn't sure how to report it.

Interesting, that worked for me too. Thank you!

**Comment by glenn-jocher** [comment]
@bog thank you for sharing your experience! It's very helpful to know that downgrading to those versions of `torch` and `torchvision` resolved the issue for you. This suggests that the problem might be associated with recent updates to these libraries. We would make sure this insight is taken into account in future updates. We actively welcome such input, so please don't hesitate to share any problem or resolution you encounter. Your input is always valuable.

**Comment by Any-Winter-4079** [comment]
Thank you! It works well after downgrading to `torch-2.0.1` and `torchvision-0.15.2`

**Comment by glenn-jocher** [comment]
@Any-Winter-4079 i'm glad to hear that downgrading to `torch-2.0.1` and `torchvision-0.15.2` has resolved your issue! It seems that certain functionalities behave differently with updates in the newer versions of these libraries and can cause some unexpected behaviors. We highly appreciate your feedback as it helps us maintain compatibility and better address such issues in the future. Should you have any more insights or face any other problems, please feel free to share them with us. Happy coding!

**Comment by stevemac00** [comment]
I have this problem too. It never manifests itself in 8.0.176 but began when I upgraded to 8.0.200. I also upgraded to 8.0.205 and problem still there. (I have many examples.) The bounding box is based on rectangle but rectangles returned have wrong values (always on the xmin from my observation). I am also using mps, torchvision=0.16.0 and torch=2.1.0.

**Comment by glenn-jocher** [comment]
@stevemac00 thank you for sharing your experience in such a detailed manner. Your troubleshooting steps are certainly helpful for us to better understand the issue at hand. Based on what you reported, it seems the issue is tied to the particular versions of the torch and torchvision libraries. When an older version of the torchvision and torch libraries is used, as is the case with your other computer, the issue seems to be resolved.

It's important to note that while libraries and frameworks are designed to be backward compatible, sometimes changes in the newer versions may affect some functionalities. This is likely the case here, considering that the problem doesn't appear when reverting back to older versions.

We appreciate your patience and effort in troubleshooting this issue and sharing the solution. Your observations are particularly insightful and will certainly assist other users who may encounter similar problems. Thanks again for raising this issue, and your contributions to this community are highly valued.

**Comment by johnnynunez** [comment]
Yes, this problem is ocurring. There are some bugs with detections.
With mps device is changing coordinates.
<img width="438" alt="Screenshot 2023-11-29 at 19 36 32" src="https://github.com/ultralytics/ultralytics/assets/22727137/ff00ed23-73c4-4b1c-8019-251ca68efb80">
<img width="1155" alt="Screenshot 2023-11-29 at 19 38 24" src="https://github.com/ultralytics/ultralytics/assets/22727137/a83e7796-aae6-446b-873f-0b46d566ea82">

**Comment by johnnynunez** [comment]
I found the error!!!

**Comment by glenn-jocher** [comment]
Great work on tracking down the error, @johnnynunez! 🎉 Identifying the precise cause of such incidents can be quite challenging, but your in-depth analysis has led to a significant finding. By pinpointing the issue and even submitting a pull request, you've made a valuable contribution to the ongoing development and refinement of the project. This will undoubtedly augment the reliability and accuracy of the models when deployed on different platforms, especially on macOS with Apple Silicon.

Thanks for taking this initiative and for providing full details, including your environment's specifications—it greatly assists in confirming and incorporating these necessary changes in the codebase. Your collaborative efforts reinforce the strength and shared learning that embodies the open-source community. Keep up the excellent work!
