### ISSUE TITLE
modifying results class in results.py

### ISSUE THREAD

**Issue by coder-glitche** [ultralytics/ultralytics#5818]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hey @glenn-jocher @RizwanMunawar i was trying to modify my results.py file in my engine folder and i was trying
 to modify save_txt function in my Results class.when i pass save_txt=True i wanted the class name to be printed instead of class index what should i modify in this function??please and thanks alot.
     def save_txt(self, txt_file, save_conf=False):
        """
        Save predictions into txt file.

        Args:
            txt_file (str): txt file path.
            save_conf (bool): save confidence score or not.
        """
        boxes = self.boxes
        masks = self.masks
        probs = self.probs
        kpts = self.keypoints
        texts = []
        if probs is not None:
            # Classify
            [texts.append(f'{probs.data[j]:.2f} {self.names[j]}') for j in probs.top5]
        elif boxes:
            # Detect/segment/pose
            for j, d in enumerate(boxes):
                c, conf, id = int(d.cls), float(d.conf), None if d.id is None else int(d.id.item())
                line = (c, *d.xywhn.view(-1))
                if masks:
                    seg = masks[j].xyn[0].copy().reshape(-1)  # reversed mask.xyn, (n,2) to (n*2)
                    line = (c, *seg)
                if kpts is not None:
                    kpt = kpts[j].xyn.reshape(-1).tolist()
                    line += (*kpt, )
                line += (conf, ) * save_conf + (() if id is None else (id, ))
                texts.append(('%g ' * len(line)).rstrip() % line)

        if texts:
            with open(txt_file, 'a') as f:
                f.writelines(text + '\n' for text in texts)

**Comment by glenn-jocher** [comment]
@coder-glitche hi there!

The behavior you're describing is definitely achievable, you'd just need to make a slight adjustment to your `save_txt` function. When you're assembling `line` for detection (i.e., in the `elif boxes:` part of your code), the first element is `c`, which represents the class index.

If you want to print the class name instead of the class index, you would replace `c` with the corresponding class name from your list of class names. You would get this by indexing your names list with `c`. Assuming your list of class names is stored in a list called `class_names`, the modification would look something like this:

Instead of:
`line = (c, *d.xywhn.view(-1))`

Use:
`line = (class_names[c], *d.xywhn.view(-1))`

In your code, it seems that `self.names` is the list that holds your class names. If that's the case, you would replace `class_names[c]` with `self.names[c]`.

Just remember that if you make this change, the text files output will contain class names instead of indices. Depending on what you want to do with this output, you might need to adjust any downstream processing to accommodate class name strings.

I hope that helps! Let me know if you have any further questions.
