### ISSUE TITLE
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by making sure all `forward` function outputs participate in calculating loss.

### ISSUE THREAD

**Issue by pax7** [ultralytics/ultralytics#5821]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am getting this error when trying to train a yolo8x-pose - any idea what could be wrong?

it always fails at 5/13934

```terminal

Starting training for 1000 epochs...

      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
     1/1000      4.71G       6.14      11.85     0.7544      16.42      4.279         15        640:   0%|          | 5/13934 [00:08<5:16:33,  1.36s/it]Traceback (most recent call last):
  File "/home/usr/ai/UltralyticsTrainPose39.py", line 7, in <module>
    results = modelPose.train(
  File "/home/usr/.local/lib/python3.10/site-packages/ultralytics/engine/model.py", line 341, in train
    self.trainer.train()
  File "/home/usr/.local/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/home/usr/.local/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 343, in _do_train
    self.loss, self.loss_items = self.model(batch)
  File "/home/usr/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/usr/.local/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1139, in forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by
making sure all `forward` function outputs participate in calculating loss.
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 1: 303 304 305 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 428799 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 428801 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 428800) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/usr/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/home/usr/.local/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/usr/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/usr/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/usr/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/usr/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/home/usr/ai/UltralyticsTrainPose39.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-19_23:02:17
  host      : bigdaddy
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 428800)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/home/usr/ai/UltralyticsTrainPose39.py", line 7, in <module>
    results = modelPose.train(
  File "/home/usr/.local/lib/python3.10/site-packages/ultralytics/engine/model.py", line 341, in train
    self.trainer.train()
  File "/home/usr/.local/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 187, in train
    raise e
  File "/home/usr/.local/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 185, in train
    subprocess.run(cmd, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'torch.distributed.run', '--nproc_per_node', '3', '--master_port', '59639', '/home/usr/ai/UltralyticsTrainPose39.py']' returned non-zero exit status 1.

```

### Additional

56 core xeon, 3x 3090Ti

i'm trying a pose with 39 keypoints instead of the standard 17

**Comment by glenn-jocher** [comment]
@pax7 hello,

From the error log, it looks like there is a problem with your loss function usage during training. The specific error "RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one" indicates that not all parameters are participating in the calculation of loss, which is why it can't complete the reduction operation.

As you're customizing YOLOv8 pose with extra keypoints (39 instead of the standard 17), it's very likely that the modifications you've made are causing this issue. I would recommend taking a closer look at the forward function of your model to ensure that all outputs are actually being used when calculating loss. 

It could also be valuable to ensure that you're synchronizing data across your GPUs correctly, as the error occurred during the usage of DistributedDataParallel. 

The error message provides a good suggestion in enabling unused parameter detection with `find_unused_parameters=True` when calling `torch.nn.parallel.DistributedDataParallel`. That will help identify any unused parameters that may exist. 

If you're quite certain that all parameters are being used in the loss calculation and the issue persists, then there may be a problem with how DistributedDataParallel is mapping output tensors internally. In this case, to help understand your custom modifications with 39 keypoints, providing the structure of your model's forward function output and the loss functions you're using will be helpful.

Good luck with your trainings!

**Comment by glenn-jocher** [comment]
Hello @pax7,

It's great to hear that the training is working and converging with `find_unused_parameters=True`!

Regarding your suggestion of using a try-catch block to handle the DistributedDataParallel (DDP) model creation, it could potentially be a reasonable approach. However, please note a couple of things:

Firstly, it should be noted that the `find_unused_parameters=True` flag affects the performance due to the extra traversal of the autograd graph in each iteration. If the model doesn't have any unused parameters during forward pass, then it's unnecessary overhead.

Secondly, the root cause for requiring this flag is likely due to some inconsistencies within your model's forward pass or loss calculations where not all parameters get part of gradient calculations. Without significantly understanding or debugging the pattern, the try-catch block only serves as a workaround. But without addressing the real issue, it could potentially hide other significant problems.

Therefore, although your suggested approach might temporarily alleviate the issue, it is essential to understand why the problem happens in the first place.

While the addition of this workaround to the code base could certainly be discussed, it would also be beneficial for the community to consider the implications and understand the root cause. So, I would encourage you to keep investigating the issue and ideally, find a solution that doesn't require the use of the `find_unused_parameters=True` flag.

Hope this clarifies. Happy coding!

**Comment by glenn-jocher** [comment]
Hello @pax7,

That sounds like a great plan! Your contributions to investigating the root cause of this issue would be highly beneficial to the community. Any information you find can potentially help others who might encounter the same problem in the future. Please don't hesitate to share your findings or ask for guidance if you encounter any difficulties during your investigation. We appreciate your efforts. Happy coding!

**Comment by glenn-jocher** [comment]
Hello @pax7,

Thanks for the updates and your continuous efforts on this issue.

The crash could be due to various possible reasons. One suspect could be the overall model complexity as your network grows with more keypoints. This might require proportionate adjustments in the training configurations, including but not limited to learning rates, batch sizes, or scheduler settings, to ensure model stability.

Another possible factor, as you suggested, may be related to how close the keypoints are to each other. The model might struggle with distinguishing close keypoints especially if their surrounding features are very similar or almost identical. In this case, increasing the receptive field of the network or providing more distinctive features for each keypoint might be needed.

However, it's challenging to pinpoint the exact cause without further information. I'd recommend you to thoroughly check your data and compare the model's performance in different configurations. It would also be beneficial to inspect the gradient norms, network weights and outputs during training to have a deeper understanding of how your model behaves.

Hope this helps guide your troubleshooting process and leads to a solution. Please continue sharing your findings and feel free to ask if you have further questions.

**Comment by glenn-jocher** [comment]
Thank you for sharing your insights, @pax7. It's an important observation that distinguishability of keypoints is crucial for the successful training of pose estimation models. This kind of rapid failure during the initial training is often a valuable indicator of dataset quality issues, especially regarding the distinctiveness of keypoints. It's always a good practice to ensure that the dataset is well-annotated with clear, discernible keypoints to prevent such training issues. Keep this in mind for dataset preparation in the future. 👍

**Comment by notprime** [comment]
Hey, 
just wanted to share my experience regarding this error, had the pleasure to meet it for the first time today while training a new custom model on 4 GPUs (not kidding, it was a pleasure, you always learn something new from problems and mistakes :D).

To me, the error was caused by a stupid mistake: I was playing around and modifying a module of my custom model, and I simply forgot to remove the creation of certain parameters in the `__init__` method (my little brain thought that just commenting the relative lines in the `forward` method would have been enough).

Just to give you an idea, this is a simply example of what happened:

**--->BEFORE**
In the `__init__` method
```
self.conv = nn.Conv2(...)
self.norm = nn.GroupNorm(...)   <--- declared even if not used anymore
self.relu = nn.ReLU()           <--- declared even if not used anymore
```

In the `forward `method:

```
def forward(x)
      x = self.conv(x)
      #x = self.norm(x)   <--- commented
      #x = self.relu(x)   <--- commented
      return x
```

**--->AFTER**
By simply changing the `__init__` to:
```
self.conv = nn.Conv2(...)
```
I solved the problem. 

So folks, remember to delete the declaration of unused parameters from the `__init__` method when playing with the model architecture (which is also stated in the error message, but again, my lil brain decided to not function properly this morning D:)

**Comment by glenn-jocher** [comment]
@notprime hello,

Thank you for sharing your experience with the community! It's indeed true that every error is an opportunity to learn something new. Your example perfectly illustrates how undeclared parameters in the `__init__` method, even if not used in the `forward` method, can cause issues when training on multiple GPUs. It's a good reminder to keep the model definition clean and consistent with the actual operations performed. Happy coding, and keep exploring! 😊👍

**Comment by glenn-jocher** [comment]
@Juphex yes, it is possible to use a model with DistributedDataParallel (DDP) where not all outputs of the `forward()` method participate in the loss calculation. To do this, you can simply ignore the unused outputs when computing the loss. However, ensure that any unused parameters do not require gradients by setting `requires_grad=False` for those parameters, or by not including them in the `forward()` computation. This will prevent DDP from expecting gradients for those parameters during the backward pass.
