### ISSUE TITLE
Unable to understand the generator of results objects for batched inference on multiple video streams

### ISSUE THREAD

**Issue by mahmad096** [ultralytics/ultralytics#5822]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I tried running multiple video streams using the following code:

```
model = YOLO('best.pt')

paths = "list.streams" #urls to 2 different video streams

results = model(paths, stream=True)

for res in results:
    annotated_frame = res.plot()
    # Display the annotated frame
    cv2.imshow("YOLOv8 Inference", annotated_frame)

    # Break the loop if 'q' is pressed
    if cv2.waitKey(1) & 0xFF == ord("q"):
        break

cv2.destroyAllWindows()
```

I am expecting the code to open multiple windows, one for each stream, and show me annotated results. But this is not happening, it just opens one window and shows glitchy results. 
Following is the terminal output:

> 1/2: https://youtu.be/p23J6NTDhEk... Success ✅ (18645 frames of shape 1920x1080 at 25.00 FPS)
> 2/2: https://youtu.be/LNwODJXcvt4... Success ✅ (10842 frames of shape 3840x2160 at 30.00 FPS)

I know I am doing something wrong while getting the results from the generator. Please help me with that. 

At _https://docs.ultralytics.com/modes/predict/#inference-sources_ we can see the following example:
```
from ultralytics import YOLO

# Load a pretrained YOLOv8n model
model = YOLO('yolov8n.pt')

# Single stream with batch-size 1 inference
source = 'rtsp://example.com/media.mp4'  # RTSP, RTMP, TCP or IP streaming address

# Multiple streams with batched inference (i.e. batch-size 8 for 8 streams)
source = 'path/to/list.streams'  # *.streams text file with one streaming address per row

# Run inference on the source
results = model(source, stream=True)  # generator of Results objects
```
This example hints multiple video streams can get batch inferenced but this example does not show how to interpret the results.

**Comment by glenn-jocher** [comment]
@mahmad096 hello,

Thank you for providing such a detailed account of the issue you're encountering!

The problem you're facing is likely arising from your attempt to show the results from multiple video stream inferencing in a single OpenCV window. OpenCV `imshow` function isn't built to handle multiple video streams in a single window, hence the glitchy results.

Examining your current code, for each result in the `results` generator, you're plotting the result and showing it in a single OpenCV window named "YOLOv8 Inference". The results generator contains inferred results from each of your video streams as a batch. But you're using a single OpenCV window to display all these results, which is why the displayed video is glitchy. 

When it comes to predicting on multiple video streams, each new batch of inference results from the results generator will contain annotations from all the video streams, not just from one video stream.

A potential way to display the video streams could be to initialize one window per stream, and then update these windows as you iterate through the results. For instance, you might display the results from the first video stream in one window, and the results from the second video stream in a second window.

However, please take into account that the process of displaying multiple video streams at once might be computationally expensive and may require a powerful machine. Displaying multiple video streams can also be quite complex, so you might want to consider displaying each video one at a time or saving the annotated video frames for later viewing.

Hope this helps you understand the unexpected behaviour you are encountering! If you have any other questions, do not hesitate to ask!

**Comment by glenn-jocher** [comment]
@mahmad096 when you're trying to display multiple video streams with OpenCV, the first thing you need to understand is that each window in OpenCV must have a unique name. This is because OpenCV identifies windows by their names. So to display each stream in a different window, you'll need to create multiple uniquely named windows using cv2.namedWindow() or cv2.imshow().

Now, coming to the context of your issue with YOLOv8. The generator obtained from running the model in streaming mode with multiple video streams will give a batch of results for each prediction. This batch will correspond to the frames from all running streams. 

It is important to know that these are batches of results from all streams, not separate results for each stream. That means you cannot access the results of individual streams by indexing the batch, which is why results[0] did not work. 

I understand your confusion, but currently, YOLOv8 does not offer a built-in mechanism to separate out results for each stream within the batch. This is something you might have to handle manually. You could accomplish this by custom sorting the results according to stream metadata before displaying the results. 

However, bear in mind that this could be a complex task considering you're coordinating multiple streams of data and may require an in-depth understanding of how YOLOv8 works.
