### ISSUE TITLE
Slow training with custom yolov8 config yaml file

### ISSUE THREAD

**Issue by ecatanzani** [ultralytics/ultralytics#5825]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I'm training a custom YOLOv8 model, which should be smallest (in terms of parameters) within respect to the YOLOv8 nano model. So I changed the config file yolov8.yaml, defining a new "nano" model with slightly different parameters in order to obtain an XS model with something like 1M parameters. This is the updated yolov8.yaml file:

```
# Parameters
nc: 80  # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.2, 0.1, 1024]  # YOLOv8n summary: 225 layers,  3157200 parameters,  3157184 gradients,   8.9 GFLOPs
  s: [0.33, 0.50, 1024]  # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  m: [0.67, 0.75, 768]   # YOLOv8m summary: 295 layers, 25902640 parameters, 25902624 gradients,  79.3 GFLOPs
  l: [1.00, 1.00, 512]   # YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs
  x: [1.00, 1.25, 512]   # YOLOv8x summary: 365 layers, 68229648 parameters, 68229632 gradients, 258.5 GFLOPs
```
  
As you can see the n model has been changed within respect to the stock parameters.
While, for my dataset, the training time of a stock yolov8 model takes something like 3 hours, this new custom n model takes more than 1 day. Is this normal? Can you please explain me what is happening and why the training time are so large?

Thanks,
Best

Enrico

**Comment by glenn-jocher** [comment]
@ecatanzani hello Enrico,

Thanks for reaching out and great work on diving in to customize YOLOv8 to meet your specific requirements.

When it comes to the training time, multiple factors come into play. It's not only about the quantity of parameters, but also about the specific architecture of the model, the data being used, and the hardware on which the model is being trained.

Although your custom model has fewer parameters than the original YOLOv8 nano model, changes in the model structure and parameters could potentially introduce computational inefficiencies, thus the drastic increase in training time. Lowering the parameters might mean simplifying the model, but 'less' not always equates to 'faster'. Some structures could introduce more complex interactions between layers or might even require more iterations to learn effectively from the data.

The data being used is also an important factor. Different distributions and classes in the dataset may cause the model to need more time to effectively learn. If your custom model is more specialized, it might require more time to train.

Finally, training hardware (like GPUs and CPUs) also significantly influence training speed. More powerful hardware can process large volumes of data in lesser time. Also, different models may have different compatibility with different hardware due to architectural nuances.

It's always a balancing act of these factors to achieve a good functioning model within reasonable training times. I hope this provides some insights into what's happening with your custom model!

Best regards,
Glenn
