### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by leezx337** [ultralytics/ultralytics#5874]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~\AppData\Local\anaconda3\envs\yolov8_custom1\lib\site-packages\IPython\core\formatters.py:708, in PlainTextFormatter.__call__(self, obj)
    701 stream = StringIO()
    702 printer = pretty.RepresentationPrinter(stream, self.verbose,
    703     self.max_width, self.newline,
    704     max_seq_length=self.max_seq_length,
    705     singleton_pprinters=self.singleton_printers,
    706     type_pprinters=self.type_printers,
    707     deferred_pprinters=self.deferred_printers)
--> 708 printer.pretty(obj)
    709 printer.flush()
    710 return stream.getvalue()

File ~\AppData\Local\anaconda3\envs\yolov8_custom1\lib\site-packages\IPython\lib\pretty.py:410, in RepresentationPrinter.pretty(self, obj)
    407                         return meth(obj, self, cycle)
    408                 if cls is not object \
    409                         and callable(cls.__dict__.get('__repr__')):
--> 410                     return _repr_pprint(obj, self, cycle)
    412     return _default_pprint(obj, self, cycle)
    413 finally:

File ~\AppData\Local\anaconda3\envs\yolov8_custom1\lib\site-packages\IPython\lib\pretty.py:778, in _repr_pprint(obj, p, cycle)
    776 """A pprint that just redirects to the normal repr function."""
    777 # Find newlines and replace them with p.break_()
--> 778 output = repr(obj)
    779 lines = output.splitlines()
    780 with p.group():

File ~\AppData\Local\anaconda3\envs\yolov8_custom1\lib\site-packages\ultralytics\utils\__init__.py:148, in SimpleClass.__repr__(self)
    146 def __repr__(self):
    147     """Return a machine-readable string representation of the object."""
--> 148     return self.__str__()

File ~\AppData\Local\anaconda3\envs\yolov8_custom1\lib\site-packages\ultralytics\utils\__init__.py:136, in SimpleClass.__str__(self)
    134 attr = []
    135 for a in dir(self):
--> 136     v = getattr(self, a)
    137     if not callable(v) and not a.startswith('_'):
    138         if isinstance(v, SimpleClass):
    139             # Display only the module and class name for subclasses

File ~\AppData\Local\anaconda3\envs\yolov8_custom1\lib\site-packages\ultralytics\utils\__init__.py:153, in SimpleClass.__getattr__(self, attr)
    151 """Custom attribute access error message with helpful information."""
    152 name = self.__class__.__name__
--> 153 raise AttributeError(f"'{name}' object has no attribute '{attr}'. See valid attributes below.\n{self.__doc__}")

AttributeError: 'DetMetrics' object has no attribute 'curves_results'. See valid attributes below.

    This class is a utility class for computing detection metrics such as precision, recall, and mean average precision
    (mAP) of an object detection model.

    Args:
        save_dir (Path): A path to the directory where the output plots will be saved. Defaults to current directory.
        plot (bool): A flag that indicates whether to plot precision-recall curves for each class. Defaults to False.
        on_plot (func): An optional callback to pass plots path and data when they are rendered. Defaults to None.
        names (tuple of str): A tuple of strings that represents the names of the classes. Defaults to an empty tuple.

    Attributes:
        save_dir (Path): A path to the directory where the output plots will be saved.
        plot (bool): A flag that indicates whether to plot the precision-recall curves for each class.
        on_plot (func): An optional callback to pass plots path and data when they are rendered.
        names (tuple of str): A tuple of strings that represents the names of the classes.
        box (Metric): An instance of the Metric class for storing the results of the detection metrics.
        speed (dict): A dictionary for storing the execution time of different parts of the detection process.

    Methods:
        process(tp, conf, pred_cls, target_cls): Updates the metric results with the latest batch of predictions.
        keys: Returns a list of keys for accessing the computed detection metrics.
        mean_results: Returns a list of mean values for the computed detection metrics.
        class_result(i): Returns a list of values for the computed detection metrics for a specific class.
        maps: Returns a dictionary of mean average precision (mAP) values for different IoU thresholds.
        fitness: Computes the fitness score based on the computed detection metrics.
        ap_class_index: Returns a list of class indices sorted by their average precision (AP) values.
        results_dict: Returns a dictionary that maps detection metric keys to their computed values.
        curves: TODO
        curves_results: TODO`

**Comment by glenn-jocher** [comment]
@leezx337 it seems like you're encountering an `AttributeError` with the message: `'DetMetrics' object has no attribute 'curves_results'`. This error typically occurs when you're trying to access an attribute that doesn't exist for the referenced object.

In this case, it looks like the `curves_results` attribute is not available as a part of the 'DetMetrics' object. From your error stack, it seems the `AttributeError` occurred when the `__str__` method tried to access `curves_results` from the `DetMetrics` object.

In YOLOv8, the `DetMetrics` class doesn't have a 'curves_results' attribute. Based on the information provided with the class, the available attributes are `save_dir`, `plot`, `on_plot`, `names`, `box`, `speed` and various methods related to detection metrics such as precision, recall, and mAP (mean Average Precision). 

Double-check your code to ensure you're accessing the correct attributes of the 'DetMetrics' object as per the class's available attributes and methods. If you indeed need to use a 'curves_results' attribute check the correct class or method that provides it.

**Comment by ehratjon** [comment]
Hi there! I run into the same issue when trying to train the "yolov8n.pt" model on a custom dataset. 

A minimal reproducible code example:

``` python
import ultralytics
from ultralytics import YOLO

print(ultralytics.__version__) 
# 8.0.201

custom_data_path = r"./data/config.yaml"

with open(custom_data_path) as f:
    print(f.read())
# names:
# - coco
# nc: 1
# train: ./train/images
# val: ./val/images
# test: ./test/images

yolo_model = YOLO("yolov8n.pt")
yolo_model.train(data=custom_data_path, epochs=1)

```

For the example I used two .jpg files with one bounding box each.
The file structure looks like this: 
``` 
.
├── config.yaml
├── test
│   ├── images
│   │   ├── 1.jpg
│   │   └── 2.jpg
│   └── labels
│       ├── 1.txt
│       └── 2.txt
├── train
│   ├── images
│   │   ├── 1.jpg
│   │   └── 2.jpg
│   ├── labels
│   │   ├── 1.txt
│   │   └── 2.txt
│   └── labels.cache
└── val
    ├── images
    │   ├── 1.jpg
    │   └── 2.jpg
    ├── labels
    │   ├── 1.txt
    │   └── 2.txt
    └── labels.cache

```
I get the exact same error as OP. 

I'm running the code in a Jupyter Notebook with:
Ultralytics YOLOv8.0.201 🚀 Python-3.11.5 torch-2.0.1+cu117 CPU (Intel Core(TM) i7-8550U 1.80GHz)

**Comment by leezx337** [comment]
Thank you so much for the reply @glenn-jocher !! @ehratjon thank you for sharing, i will try your approach :)

**Comment by glenn-jocher** [comment]
You're welcome, @leezx337! I'm glad you found the information shared by @ehratjon helpful. I hope applying the approach has given you better results and resolved the error. It's fantastic to see this kind of collaboration and knowledge sharing. Feel free to ask if you come across any other issues. We are always here to help you with YOLOv8-related queries. Happy experimenting with your models!

**Comment by phigjm** [comment]
For me the Error occurs on my GPU (`torch==2.1.0+cu121`) and it also occurs for `epochs=150`.
Training the Network on the CPU (`torch==2.1.0`) works for me.

**Comment by glenn-jocher** [comment]
@phigjm it's intriguing that the error is specific to your GPU environment but not present in the CPU environment. Since the version of PyTorch you're using with the GPU (`torch==2.1.0+cu121`) is different from the one for CPU (`torch==2.1.0`), this could be a compatibility issue specific to the combination of PyTorch, CUDA, and ultralytics YOLOv8.

Follow these steps to troubleshoot the issue:

1. Ensure that your NVIDIA drivers, CUDA Toolkit, and cuDNN are compatible with each other and with PyTorch version 2.1.0. You can check the compatibility on the official PyTorch website.

2. It might also be beneficial to test with different versions of PyTorch, as sometimes certain versions may have bugs that affect specific functionalities. Downgrading or upgrading PyTorch could potentially solve the issue.

3. Verify that all your GPU utilizations, including the usage of the CUDA environment, are correctly set up in your project. Ensure that you can successfully run other GPU-accelerated tasks with your current setup.

4. Check if there are any environment-specific issues by running the same code in a new, clean environment. Sometimes, conflicts with other installed packages or residual config files can lead to unexpected behaviors.

5. Lastly, you can open an issue on the YOLOv8 GitHub repository with detailed information about the error, including the traceback, the custom dataset's specifics (if not proprietary), and your environment details. This way, the repository maintainers and contributors can provide targeted assistance.

Remember, any software, model, or architecture can have unique quirks and requirements depending on the hardware and software configuration. In some cases, working in different environments can surface these subtleties, necessitating careful debugging and comparison of the working vs. non-working setups.

**Comment by glenn-jocher** [comment]
@ArsBinarii hello! It looks like you're encountering an `AttributeError` related to the `DetMetrics` object not having a `curves_results` attribute. This could be due to a version mismatch or an outdated codebase where `curves_results` might not be implemented yet in YOLOv8.1.18. 🤔

Could you please try updating your Ultralytics YOLO package to the latest version? Sometimes, these issues are resolved in newer releases. You can update it using:

```python
!pip install --upgrade ultralytics
```

If the issue persists after updating, it might not be related to the version. In that case, `curves_results` might be accessed in a context where it's not available. Double-checking the documentation or ensuring you're following the latest usage patterns might help. If you're still stuck, feel free to share a snippet of your code where the error occurs, and we can take a closer look! 😊
