### ISSUE TITLE
I need help for yolo v8 with raspbian 

### ISSUE THREAD

**Issue by Svid23** [ultralytics/ultralytics#5883]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, sorry for my basic doubts but I'm new to this hahaha, I currently have a rapsberry pi 4 model b 8gb, with full 64-bit PiOs legacy, and I tried to put yolov8 on it for real-time object detection with an arducam imx519 autofocus , but it has been quite a challenge!!! Because as far as I know ultralytics only goes up to python version 3.8, which is complicated for me, because many of the libraries that I use in addition to that one are installed with apt-get, because with pip I can't install for example opencv, so everything has been crazy, I wanted to know if there is a version above 3.8 that ultralytics supports, or how I can install it on my Raspberry

**Comment by glenn-jocher** [comment]
@Svid23 hello,

Thank you for using YOLOv8 and reaching out about your Raspberry Pi setup. Presently, the Ultralytics YOLOv8 works with Python versions 3.8 and above. This requirement is due to some of the underlying packages that YOLOv8 leverages to perform its operations smoothly.

As for the problem with OpenCV, while it is true that pip often struggles with certain libraries, there are ways around it. OpenCV might be one of the more difficult ones to install, but it should be possible to install it via pip. However, it typically requires some additional system dependencies to be installed first. You would need to install these dependencies using `apt-get` before being able to install OpenCV with pip.

Finally, if you're finding the Python version to be a sticking point due to other libraries you're using, you might need to consider python virtual environments. They allow you to have different projects running on the same machine with different Python versions and dependencies which could be beneficial in your case.

Let me know if this helps, or if you have any other questions. Happy coding!

**Comment by Svid23** [comment]
you helped me, thank you very much
