### ISSUE TITLE
YOLOv8n pose int8 tflite inference bbox result is weird

### ISSUE THREAD

**Issue by kris-himax** [ultralytics/ultralytics#5889]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi @glenn-jocher ,
I use model export to export yolov8n-pose tflite int8 with input size=192, by following code.
```
from ultralytics import YOLO
image_size = 192
model = YOLO("yolov8n-pose.pt")  

model.export(format="tflite", imgsz = image_size, int8 = True, data="coco128.yaml")
```
And I use following code to do yolov8n-pose tflite int8 inference. 
Face the situation about although the key-points seem ok, the bbox is not correct.
The bbox result is not correct. Does anyone have any idea? 
But I use floating tflite is fine with bbox and key-points result.
```
import argparse
import  cv2
# import cv2.dnn
import numpy as np
import tensorflow as tf
from ultralytics.yolo.utils import ROOT, yaml_load ,ops
from ultralytics.yolo.utils.checks import check_yaml
import matplotlib.pyplot as plt
import matplotlib.image as img
CLASSES = yaml_load(check_yaml('coco128.yaml'))['names']
print(CLASSES)
colors = np.random.uniform(128, 255, size=(len(CLASSES), 3))
# colors = np.random.uniform(0, 255, size=(len(CLASSES), 3))
# modelScoreThreshold = .25
modelScoreThreshold = .4
modelNMSThreshold = .45

def draw_bounding_box(img, class_id, confidence, x, y, x_plus_w, y_plus_h):
    label = f'{CLASSES[class_id]} ({confidence:.2f})'
    color = colors[class_id]
    cv2.rectangle(img, (x, y), (x_plus_w, y_plus_h), color, 2)
    cv2.putText(img, label, (x - 10, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)


def main(tflite_model, input_image,in_image_size):
    interpreter = tf.lite.Interpreter(model_path=tflite_model)
    interpreter.allocate_tensors()

    original_image: np.ndarray = cv2.imread(input_image)
    [height, width, _] = original_image.shape
    length = max((height, width))
    image = np.zeros((length, length, 3), np.uint8)
    image[0:height, 0:width] = original_image
    scale = length / in_image_size
    input_data = cv2.resize(
        original_image, (in_image_size, in_image_size), interpolation=cv2.INTER_LINEAR
    )

    ###############################################
        # Get input and output tensors.
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    original_image = cv2.cvtColor(original_image, cv2.COLOR_BGR2RGB)
    input_data = cv2.cvtColor(input_data, cv2.COLOR_BGR2RGB)
    ##########################################
    # input_data = (input_data -128).astype(np.int8)
     #special here
    in_scale = input_details[0]['quantization_parameters']['scales']
    in_zero_point = input_details[0]['quantization_parameters']['zero_points']
    # input_data = (input_data/ 255.0 / in_scale + in_zero_point).astype(np.int8)  # de-scale
    input_data = (input_data - 128).astype(np.int8)  # de-scale
    #####################################################
    input_data = input_data.transpose(2, 0, 1).reshape(1, 3, in_image_size, in_image_size)
    input_data = np.transpose(input_data,axes=[0, 2,3,1])



    interpreter.set_tensor(input_details[0]['index'], input_data)

    interpreter.invoke()

    # The function `get_tensor()` returns a copy of the tensor data.
    # Use `tensor()` in order to get a pointer to the tensor.
    output_data = interpreter.get_tensor(output_details[0]['index'])
    print(output_data)

    output_data_quant_para = output_details[0]['quantization_parameters']
    output_data = (output_data.astype(np.float32)- output_data_quant_para['zero_points'])*output_data_quant_para['scales']
    
    if output_data.ndim > 2:
        w = in_image_size
        h = in_image_size
        output_data[:, 0] *= w
        output_data[:, 1] *= h
        output_data[:, 2] *= w
        output_data[:, 3] *= h
    print("output_data_quant_para['zero_points'] = "+str(output_data_quant_para['zero_points']))
    print("output_data_quant_para['scales'] = " + str(output_data_quant_para['scales']))


    outputs = output_data

    print("inference done")
    print("output_data.shape")
    print(output_data.shape)
    outputs = np.array([cv2.transpose(outputs[0])])
    print("outputs.shape "+str(outputs.shape))
    rows = outputs.shape[1]

    boxes = []
    scores = []
    key_points = []
    print("rows "+str(rows))#rows = 756
    for i in range(rows):
        score = outputs[0][i][4]#pose score
        if score >= modelScoreThreshold:
            print(str(i)+" "+str(score))
            for box_num in range(4):
                print("outputs[0]["+str(i)+"]["+str(box_num)+"]"+" "+str(outputs[0][i][box_num]))
            box = [
                float(outputs[0][i][0]) - (0.5 * float(outputs[0][i][2])), float(outputs[0][i][1]) - (0.5 * float(outputs[0][i][3])),
                float(outputs[0][i][2]), float(outputs[0][i][3])]
            kpt_coordinate_list = []
            for k in range(17):
                kpt_x = outputs[0][i][k*3+5] 
                kpt_y = outputs[0][i][k*3+6] 
                kpt_coordinate = [kpt_x,  kpt_y, outputs[0][i][k*3+7]] #x , y , score
                kpt_coordinate_list.append(kpt_coordinate)
            boxes.append(box)
            scores.append(score)
            key_points.append(kpt_coordinate_list)
    # print("boxes"+str(boxes))
    # print("scores"+str(scores))
    # print("class_ids"+str(class_ids))


    result_boxes = cv2.dnn.NMSBoxes(boxes, scores, modelScoreThreshold, modelNMSThreshold, 1)

    detections = []
    for i in range(len(result_boxes)):
        index = result_boxes[i]
        box = boxes[index]
        kpt_point = key_points[index]
        print("boxes["+str(index)+"]")
        print(boxes[index])
        # print("key_points["+str(index)+"]")
        # print(key_points[index])

        # print()
        # print(key_points[index][0][1])
        detection = {
            'class_id': 0,
            'class_name': CLASSES[0],
            'confidence': scores[index],
            'box': box,
            'scale': scale}
        detections.append(detection)
        draw_bounding_box(original_image, 0, scores[index], round(box[0] / in_image_size * width), round(box[1] / in_image_size * height),
                          round((box[0] + box[2]) / in_image_size * width), round((box[1] + box[3]) / in_image_size * height))
        
        for kkk_num in range(17):
            kpt_point[kkk_num][0]=round(kpt_point[kkk_num][0]/ float(in_image_size) *  float(width))
            kpt_point[kkk_num][1]=round(kpt_point[kkk_num][1]/ float(in_image_size) *  float(height))
            if kpt_point[kkk_num][2] >= modelScoreThreshold:
                cv2.circle(original_image, (kpt_point[kkk_num][0],kpt_point[kkk_num][1]), 5, (0,0,255), -1) 
    
    plt.imshow(original_image)                                    # 在圖表中繪製圖片
    plt.show()  
    # cv2.namedWindow("output", cv2.WINDOW_NORMAL) 
    # cv2.imshow("output", original_image)
    # cv2.waitKey(0)
    # cv2.destroyAllWindows()

    # return detections


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    input_image = 'ultralytics/assets/zidane.jpg'
    # input_image = 'ultralytics/assets/bus.jpg'
 
    model_path = "yolov8n-pose_saved_model_192/yolov8n-pose_full_integer_quant.tflite"

    in_image_size = 192

    # model_path = "yolov8n-pose_saved_model_640/yolov8n-pose_full_integer_quant.tflite"
    # in_image_size = 640

    parser.add_argument('--model', default=model_path, help='Input your onnx model.')
    parser.add_argument('--img', default=str(input_image), help='Path to input image.')
    parser.add_argument('--img_size', default=in_image_size, help='Path to input image.')
    args = parser.parse_args()
    


    image = img.imread(input_image)                       # 讀取圖片
    plt.imshow(image)                                    # 在圖表中繪製圖片
    plt.show()      

    main(args.model, args.img, args.img_size)

```
int8 tflite result
![image](https://github.com/ultralytics/ultralytics/assets/87454575/7c64fba9-a220-4c82-974e-59cf57709f56)

**Comment by kris-himax** [comment]
Hi @glenn-jocher ,

I also want to use int8 tflite and use model.prediect to inference, and got the result like.
The results seem not correct. Did I miss something?

![zidane](https://github.com/ultralytics/ultralytics/assets/87454575/3fd6324a-eaea-46f4-a27b-30e424cc7061)
![bus](https://github.com/ultralytics/ultralytics/assets/87454575/a61159c6-5ce1-45ff-a3c5-a4f2ccef113b)

the code is
```
model_path = "yolov8n-pose_saved_model_192/yolov8n-pose_full_integer_quant.tflite"
in_image_size = 192
from ultralytics import YOLO

model = YOLO(args.model)
model.predict(source="ultralytics/assets", imgsz = in_image_size, save=True,  show_conf = True,show=True)
```

Thanks,
Kris

**Comment by glenn-jocher** [comment]
Hi @kris-himax,

The results you are seeing can be due to a number of reasons. It's possible that the quantization process may not have been done correctly. During the conversion to tflite, it's important to ensure that you are using the correct representative dataset and you are properly calibrating your model. Neglecting this can lead to drastically worse results.

Another possible error could be improper input preprocessing. The model requires specific preprocessing steps corresponding to the weights, and if these aren't applied correctly, the resulting predictions can be off. 

Also, verify that the images you are using for inference are of the correct size and format which the model expects.

Finally, it could also be the way output-post processing is handled. YOLOv8 models return raw predictions from the model that you should transform into final detection results.

Do review these aspects and let me know your findings.

Cheers,
Your friendly GitHub responder

**Comment by kris-himax** [comment]
Hi @glenn-jocher ,
1. I use coco dataset and coco128 dataset to do quantization and the bbox results seem almost the same.
2. The pre-proceessing which I use is following # de-scale part. Although I use /255.0 or -128 , the result is not correct the same.
```
    in_scale = input_details[0]['quantization_parameters']['scales']
    in_zero_point = input_details[0]['quantization_parameters']['zero_points']
    # input_data = (input_data/ 255.0 / in_scale + in_zero_point).astype(np.int8)  # de-scale
    input_data = (input_data - 128).astype(np.int8)  # de-scale
```
3. The input image which I use I am sure that I have already resize to 192 by following code. And also do the  cv2.cvtColor(original_image, cv2.COLOR_BGR2RGB). Because use the same part of code, I do the floating tflite inference, the result is correct.
```
input_data = cv2.resize(
        original_image, (in_image_size, in_image_size), interpolation=cv2.INTER_LINEAR
    )

```
4. The post-processing I think I am correct. Because the floating tflite infecnce result seems correct.
- floating tflite result
![Screenshot from 2023-10-23 14-47-05](https://github.com/ultralytics/ultralytics/assets/87454575/85be81a6-b09c-4f6b-bfe3-85c67b9f1880)

**Comment by glenn-jocher** [comment]
Hi @kris-himax,

Thanks for the detailed information. It seems you have taken good steps in preprocessing, quantization, resizing, and in ensuring the correct color representation (BGR to RGB). 

You mentioned that the floating-point TFLite model worked well, but the quantized one didn't, which implies the issue lies in the quantization process. For conversion to int8 TFLite, both the model calibration process as well as the conversion of the image to int8 format should be accurate for correct results.

1. Make sure the representative dataset used for quantization closely represents the distribution of images that you'll run inference on. If there is a significant mismatch, the quantized model might not perform well.

2. The correctness of image conversion to int8 is critical. Images should not just be resized, but also mean-normalized and standardized as the model expects. Moreover, the scaling factor used for int8 conversion should match the one used during quantization. 

3. In your code snippet, you've scaled down your image using the zero-point and scale, and converted to int8 datatype. Verify that this quantization information (scale and zero_point) matches what was used for converting your floating point model to quantized model.

Lastly, if none of these solve the problem, it may be due to the inherent limitation of quantization. Quantizing model weights to lower precision can impact model accuracy, especially for complex models like YOLOv8.

Keep debugging and I hope you figure it out soon. 

Best,
[GitHub Assistant]

**Comment by kris-himax** [comment]
Hi @glenn-jocher ,

Because I use the pre-trained model about yolov8n-pose.pt which you provided.
Can I confirm that if you do the same process that do full quantization to int8 tflite and do the int8 tflite inference will get the same bad result like me?


Sincerely,
Kris

**Comment by glenn-jocher** [comment]
@kris-himax hi Kris,

Using the yolov8n-pose.pt pre-trained model with the coco.yaml for model export should not inherently cause problems. If you're encountering issues during int8 TFLite inference, it might be due to the quantization process. 

Quantization reduces the precision of the model's weights and biases for memory efficiency and speed, but this can sometimes lead to a decrease in prediction accuracy. 

It would be hard for me to confirm your results without replicating your exact process but based on your description, it's possible that the quantization might be affecting your model's performance. I would recommend double checking the representative dataset used for quantization and ensuring your input images are preprocessed correctly according to your model's needs. 

Hope this helps. Let me know if you have any further questions.

Best,
[GitHub Assistant]

**Comment by dobrykod** [comment]
I am trying to use quantized models as well but they do not detect anything if I call it like this:
```
yolo export model='yolov8n-pose.pt' format='tflite' int8=True
yolo predict pose model='yolov8n-pose_saved_model/yolov8n-pose_full_integer_quant.tflite' source='bus.jpg' show=True
```
If I look at the output tensor all bboxes and confidences are zero. But keypoints xy values are in expected range.

**Comment by glenn-jocher** [comment]
@dobrykod hi, 

The issue you're facing could be due to differences between the full precision model and quantized model. When the model is quantized, the weights and biases of the model are compressed into lower precision which might affect the model's accuracy and ability to detect objects. 

It's important to note that the quantization process should use a representative dataset that closely mimics the data distribution of the images you'll be testing on. If the dataset used for quantization is not representative, the quantized model might not perform well during inference.

For the zero bounding boxes and confidences, you also may want to double-check the processing of the output tensor. Depending on how the TFLite model is calibrated, the output tensor might require additional steps to convert the values back into the original range. 

The fact that keypoints xy values are in the expected range indicates that part of the model might be working as expected, so I'd recommend thoroughly revisiting the quantization process and how the output tensor is handled.

Let me know if you have any other questions, and I'll be glad to assist.

Best, 

[GitHub Assistant]

**Comment by dobrykod** [comment]
It seems they fixed quantization in [@ultralytics_degirum](https://github.com/DeGirum/ultralytics_degirum).

**Comment by glenn-jocher** [comment]
@dobrykod hi there,

Thank you for your suggestion. We value contributions and updates from our community. However, integrating changes or forks from other repositories typically requires an in-depth review to ensure compatibility, sustainability, and that it aligns with the current and future development plans of YOLOv8.

As such, while we can't make specific promises about integrating changes from other repositories, we do constantly monitor community developments and consider them during our planning and update phases. Regarding the quantization issue and the changes made in the repository you mentioned, we're aware of this and are looking into it.

For the conversion issue with the pose model you mentioned using this fork, without specific details, it's difficult to provide a direct solution. However, generally, you may want to ensure you're using the correct configurations, dependencies, and environment that align with this particular fork to ensure a successful conversion.

Thank you for your understanding and contributions to the project.

Best,
[GitHub Assistant]

**Comment by kris-himax** [comment]
Hi @dobrykod,

Did you success to convert the right int8 tflite about yolov8n with correct result?

Thanks,
Kris

**Comment by dobrykod** [comment]
Yes, all works fine with fork DeGirum/ultralytics_degirum

**Comment by glenn-jocher** [comment]
Hi Kris @dobrykod,

It seems that @dobrykod has had success using the DeGirum fork of our repository for int8 quantization with correct results.

This information might be useful for you, indicating that the quantization issues you've experienced may be addressed in that fork. While Ultralytics always aims to provide the best possible models and tools, it's great to see community members contributing and adapting the tools to their needs.

If you are still experiencing issues, you might consider checking out the modifications made in the fork that @dobrykod mentioned. Otherwise, we appreciate your patience as the official repository continues to be updated and improved.

**Comment by kris-himax** [comment]
Hi @dobrykod ,
I think that this fork DeGirum/ultralytics_degirum separate the output tensor to 6 output to fix the quantize problem.
![Screenshot from 2023-12-04 14-32-14](https://github.com/ultralytics/ultralytics/assets/87454575/ccec1045-93d8-4d13-bbe6-9d016f0cce79)

But I think it is not work at yolov8n-pose model. Did you face the same error as me?
![Screenshot from 2023-12-04 14-32-47](https://github.com/ultralytics/ultralytics/assets/87454575/2f7c093d-97d3-4366-9194-169042890e43)

Hi @glenn-jocher,
Finally, I think that the fork repository which modify output to 6 tensor is not my goal at yolov8n-pose. I think that I still want to use the original way to convert to only one output tensor pose int8 yolov8n tflite. Is there any update at original way to convert yolov8n-pose model to int8 tflite recently?

Best regards,
Kris

**Comment by dobrykod** [comment]
Yes, it converted to tflite without any problems. I think I didnt use 'act' param.

**Comment by kris-himax** [comment]
Hi @dobrykod ,

I still face type error by using google colab. What environment did you use?

But what is the output int8 tflite model? Is it a 6 branch output model and I need to do different post-proccessing?

**Comment by glenn-jocher** [comment]
Hi Kris,

From your conversation, it looks like you're experiencing a `TypeError` when trying to export the `yolov8n-pose` model with `separate_6_outputs=True`. It seems that @dobrykod has successfully exported a similar model using the DeGirum fork which provides output in 6 separate tensors.

Regarding your question on updates to the export function for `yolov8n-pose` in the original repository, I suggest you keep an eye on our GitHub repo for the latest changes and updates.

As for the environment, @dobrykod mentioned using Google Colab. Environment specifications can often lead to different behaviors in code execution. It's also important to note the additional flags used during export which might influence the outcome.

If you have a success with this fork and don't need to worry about post-processing because of the way the fork handles outputs, that's great. You might have to adjust your code to accommodate multiple output tensors if the original model expects a different output format. The key here is to align the post-processing steps with the output structure of the model.

Keep in mind that the forked version you are using has modified the original export behavior of YOLOv8. If you want to follow the original repository’s approach, staying updated on the official Ultralytics YOLOv8 repo would be the best course of action.

**Comment by kris-himax** [comment]
Hi @dobrykod ,
I think that you use `separate_outputs=True, uint8_io_dtype=True, max_ncalib_imgs=100`  flags are not the correct flag at latest  DeGirium fork repository. It will face error.
![Screenshot from 2023-12-05 11-00-05](https://github.com/ultralytics/ultralytics/assets/87454575/791f8a6a-f5f3-4f64-acbd-2c610a5041ae)
At `ultralytics/nn/modules/head.py` the latest DeGirium fork repository, there is only `separate_6_outputs` flag.
![Screenshot from 2023-12-05 11-01-33](https://github.com/ultralytics/ultralytics/assets/87454575/4286d628-4688-42f6-aad6-fcf50a5f3a02)
And if converting `Detect` int8 tflite is ok, but while I want to convert `Pose` model it will face `type error`.
Which version of repository did you use or what command did you use to install the DeGirium fork repository on google colab?

Hi @glenn-jocher ,
Thanks for your reply.
I will keep following the update about the original repository for the pose int8 tflite model.

**Comment by dobrykod** [comment]
You should use DeGirum/ultralytics_yolov8 instead of DeGirum/ultralytics_degirum

**Comment by glenn-jocher** [comment]
@dobrykod hi Kris,

It looks like there might be some confusion about repository names. You should use `DeGirum/ultralytics_yolov8` instead of `DeGirum/ultralytics_degirum` for your purpose. This should provide the correct functionality you are looking for.

**Comment by kris-himax** [comment]
Thank you.
It works fine.

**Comment by glenn-jocher** [comment]
@kris-himax i'm glad to hear it's working fine now! If you have any more questions or need further assistance, feel free to reach out. Happy coding! 🚀

**Comment by russhustle** [comment]
@kris-himax , thank you for opening this issue.
Recently I have been working on the same topic in this issue.
I am glad to hear that your work had been going well.
Would you please share more details on how you did it?
Thank you very much in advance.

**Comment by Josephgvvvn** [comment]
> Thank you. It works fine.

Please, the proper way to export to tflite int8 in ultralytics
and its inference in ultralytics as well as required libraries
Because it gives an error and requests metadata
Thanks

**Comment by glenn-jocher** [comment]
Hi @Josephgvvvn,

Great to hear it's working! For exporting to TFLite int8 and running inference, here's a concise guide:

### Export to TFLite int8
```python
from ultralytics import YOLO

model = YOLO("yolov8n-pose.pt")
model.export(format="tflite", imgsz=192, int8=True, data="coco128.yaml")
```

### Inference with TFLite
```python
import tensorflow as tf
import numpy as np
import cv2

# Load TFLite model
interpreter = tf.lite.Interpreter(model_path="yolov8n-pose.tflite")
interpreter.allocate_tensors()

# Prepare input
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
image = cv2.imread("path/to/image.jpg")
input_data = cv2.resize(image, (192, 192))
input_data = np.expand_dims(input_data, axis=0).astype(np.uint8)

# Run inference
interpreter.set_tensor(input_details[0]['index'], input_data)
interpreter.invoke()
output_data = interpreter.get_tensor(output_details[0]['index'])

print(output_data)
```

### Required Libraries
- `tensorflow`
- `opencv-python`
- `numpy`

Make sure to install these libraries using pip:
```bash
pip install tensorflow opencv-python numpy
```

Hope this helps! 😊

**Comment by osivinyuk** [comment]
> Thank you. It works fine.

Hello @kris-himax 
Can you provide export script and inference with postprocessing script?
Thank you

**Comment by kaplansinan** [comment]
@osivinyuk I managed to run the inference and  visualize the outputs from yolov11-pose model converted to tflite. Here is my code:


```python
def main_v2(tflite_model, input_image, in_image_size):
    interpreter = tf.lite.Interpreter(model_path=tflite_model)
    interpreter.allocate_tensors()

    original_image = cv2.imread(input_image)
    input_data = cv2.resize(original_image, (in_image_size, in_image_size), interpolation=cv2.INTER_LINEAR)

    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    print('output_details', output_details)
    print('input_details', input_details)

    input_data = cv2.cvtColor(input_data, cv2.COLOR_BGR2RGB)
    input_data = (input_data - 128).astype(np.int8)
    input_data = input_data.transpose(2, 0, 1).reshape(1, 3, in_image_size, in_image_size)
    input_data = np.transpose(input_data, axes=[0, 2, 3, 1])
    print("Input shape:", input_data.shape)

    interpreter.set_tensor(input_details[0]['index'], input_data)
    interpreter.invoke()
    output_data = interpreter.get_tensor(output_details[0]['index'])

    output_data_quant_para = output_details[0]['quantization_parameters']
    output_data = (output_data.astype(np.float32) - output_data_quant_para['zero_points']) * output_data_quant_para['scales']

    # Reshape output to (batch, num_boxes, num_classes + 5)
    output_data = output_data.reshape((1, -1, output_data.shape[-1]))
    print('output_data.shape', output_data.shape)


    # bboxes, conf, keypoints = post_process_outputs(output_data)
    # output_img = visualize_image(image_path, (640,640), bboxes, conf, keypoints)

    # # Save the image
    # output_img.save('output_visualized_tflite.png')

    output_data = output_data[0].transpose(1, 0)  # (8400, 56)
    print('output_data.shape.transformed', output_data.shape)

    # Extract bounding boxes, confidences, and keypoints
    boxes = output_data[:, :4]
    confidences = output_data[:, 4]
    keypoints = output_data[:, 5:]

    # Filter detections based on confidence threshold
    conf_threshold = 0.25
    nms_threshold = 0.45
    
    mask = confidences > conf_threshold
    boxes = boxes[mask]
    confidences = confidences[mask]
    keypoints = keypoints[mask]

    # Apply non-maximum suppression
    indices = cv2.dnn.NMSBoxes(boxes.tolist(), confidences.tolist(), conf_threshold, nms_threshold)
    print(indices)

    # get orginal image shapes
    img_height, img_width = original_image.shape[:2]
    # Visualize results
    for i in indices:
        box = boxes[i]
        print(box)
        xc, yc, w, h = box

        # Convert (xc, yc, w, h) to (x1, y1) and (x2, y2)
        x1 = int((xc - w / 2.0) * img_width)
        y1 = int((yc - h / 2.0) * img_height)
        x2 = int((xc + w / 2.0) * img_width)
        y2 = int((yc + h / 2.0) * img_height)

        # Draw bounding box
        cv2.rectangle(original_image, (x1, y1), (x2, y2), (0, 255, 0), 2)

        # Draw keypoints
        keypoint = keypoints[i]
        print(keypoint)
        for j in range(0, len(keypoint), 3):
            x, y, conf = keypoint[j], keypoint[j+1], keypoint[j+2]
            if conf > 0.5:
                x = int(x * img_width)
                y = int(y * img_height)
                cv2.circle(original_image, (x, y), 3, (255, 0, 0), -1)

    return original_image
```
