### ISSUE TITLE
Segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by Drexk26** [ultralytics/ultralytics#5900]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Install

### Bug

Hi I am trying to use yolov8 network for object identification. The following issue showed up:

---------------------------------------------
jetson_orin@ubuntu:/media/jetson_orin/orin_ssd/NEW$ yolo detect predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg' show=True
Ultralytics YOLOv8.0.192 🚀 Python-3.8.10 torch-2.1.0 CPU (ARMv8 Processor rev 1 (v8l))
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

Found https://ultralytics.com/images/bus.jpg locally at bus.jpg
Segmentation fault (core dumped)
---------------------------------------------

 Ubuntu 20 is running on Nvidia Jetson AGX Orin. I installed all the specified requirements and dependencies and python3 v3.8.

Please help me.
Thanks in advance.
 

### Environment

Ultralytics YOLOv8.0.192 🚀 Python-3.8.10 torch-2.1.0 CPU (ARMv8 Processor rev 1 (v8l))
Setup complete ✅ (12 CPUs, 29.9 GB RAM, 31.6/56.6 GB disk)

OS                  Linux-5.10.120-tegra-aarch64-with-glibc2.29
Environment         Linux
Python              3.8.10
Install             pip
RAM                 29.88 GB
CPU                 ARMv8 Processor rev 1 (v8l)
CUDA                None

matplotlib          ✅ 3.7.3>=3.3.0
numpy               ✅ 1.24.1>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 9.5.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.1.0>=1.8.0
torchvision         ✅ 0.16.0>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

### Minimal Reproducible Example

yolo detect predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg' show=True

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Drexk26 thank you for taking the time to report this issue and for your willingness to help with a PR!

From the information provided, it appears the crash, indicated by the "Segmentation fault (core dumped)" message is happening after the image is found locally. This may suggest an issue with the image handling process in the model.

As your system environment seems correctly set up, let's investigate a few further possibilities related to the image or the model weights:

1. **Image issues**: There could be an issue with the specific image file 'bus.jpg'. Can you confirm the image file is not corrupted and that other images work fine? If so, try converting the image to different formats (e.g., PNG) and retry.

2. **Model Weights issues**: You might want to re-validate the model weights file 'yolov8n.pt'. As you are running on CPU, it's crucial to ensure that the weights file was correctly loaded and is compatible. 

In terms of debugging, try running a lighter task such as `yolo val` in place of `yolo detect predict`. This will provide more insight into whether the issue lies in the model or elsewhere in the process.

Finally, if you are willing to submit a PR as you've mentioned, feel free to do so! You might find the source of the issue while digging into the code. Remember, any contribution is greatly beneficial for the YOLO community and Ultralytics team.

Let's keep this conversation ongoing until we resolve your issue. Looking forward to your reply!

**Comment by Drexk26** [comment]
@glenn-jocher thank you for your reply!
I have just tried your suggestions, and here is the results:

\
1) tha image is not corrupted and I tried with an other image and the result is the same;

2) the 'yolo val' returned me this:

jetson_orin@ubuntu:/media/jetson_orin/orin_ssd/NEW$ yolo val model=yolov8n.pt source='/media/jetson_orin/orin_ssd/NEW/dog.jpg' show=True
WARNING ⚠️ 'data' is missing. Using default 'data=coco8.yaml'.
Ultralytics YOLOv8.0.192 🚀 Python-3.8.10 torch-2.1.0 CPU (ARMv8 Processor rev 1 (v8l))
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
val: Scanning /media/jetson_orin/orin_ssd/datasets/coco8/labels/val.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|          | 0/1 [00:00<?, ?it/s]Segmentation fault (core dumped)

Thanks!

**Comment by skconan** [comment]
@Drexk26 For your issue I ever run on CPU. but I can run this command `yolo detect predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg' show=True` on GPU. I suspect there may be compatibility issues with the PyTorch or Jetpack setup on Jetson. Here is my current environment:

PyTorch (torch)  : 2.0.0+nv23.5
TorchVision        : 0.15.0a0+290e910
Ultralytics           : 8.0.156

For above environment, it work for me.

I installed PyTorch from [Jetson Zoo](https://elinux.org/Jetson_Zoo) and built TorchVision from [the official PyTorch Vision repository](https://github.com/pytorch/vision).

Could you try run it on GPU?

**Comment by glenn-jocher** [comment]
Hi @Drexk26, thanks for your response. It's great that you've narrowed down the issue via `yolo val`. The segmentation fault typically occurs when there's a memory access issue, so generally it's related to the underlying OS or architecture support rather than the model itself.

From the information you've given, it seems you're running the tasks on CPU on a Jetson AGX Orin, which is designed specifically for GPU workloads. These devices are equipped with an ARM64 architecture and NVIDIA's CUDA cores. Hence, PyTorch, which is central to our YOLOv8 implementation, may not be fully compatible when running purely on the device's CPU rather than its GPU.

One of our collaborators reported that they were able to run the `yolo detect predict` command successfully on a similar Jetson setup but utilizing the GPU.

Given this information, and as you're on a device with a powerful GPU, we strongly recommend running PyTorch and the YOLOv8 tasks on the GPU rather than the CPU. For a seamless experience, ensure PyTorch and TorchVision versions compatible with the specific version of Jetson AGX Orin you're using. Often, building TorchVision from source provides the most compatible setup. Instructions for this can typically be found on the official PyTorch Vision repository.

Give it a try and let us know how it goes. We're here to help you through the process!
