### ISSUE TITLE
yolov8n-seg.onnx  can not convert to trt-int8. 

### ISSUE THREAD

**Issue by lucy3589** [ultralytics/ultralytics#5911]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

yolov8n-seg.onnx  can not convert to trt-int8. but can convert trt-fp16

### Additional

Input filename:   yolov8n-seg.onnx
ONNX IR version:  0.0.6
Opset version:    11
Producer name:    pytorch
Producer version: 1.13.1
Domain:
Model version:    0
Doc string:
----------------------------------------------------------------
[10/23/2023-17:12:06] [W] [TRT] onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[10/23/2023-17:12:06] [I] FP32 and INT8 precisions have been specified - more performance might be enabled by additionally specifying --fp16 or --best
[10/23/2023-17:12:06] [W] [TRT] Calibrator is not being used. Users must provide dynamic range for all tensors that are not Int32.
[10/23/2023-17:15:27] [E] [TRT] Try increasing the workspace size with IBuilderConfig::setMaxWorkspaceSize() if using IBuilder::buildEngineWithConfig, or IBuilder::setMaxWorkspaceSize() if using IBuilder::buildCudaEngine.
[10/23/2023-17:15:27] [E] [TRT] C:\source\builder\tacticOptimizer.cpp (1820) - TRTInternal Error in nvinfer1::builder::`anonymous-namespace'::LeafCNode::computeCosts: 0 (Could not find any implementation for node /model.22/proto/cv3/conv/Conv + PWN(/model.22/proto/cv3/act/Sigmoid, /model.22/proto/cv3/act/Mul).)
[10/23/2023-17:15:27] [E] [TRT] C:\source\builder\tacticOptimizer.cpp (1820) - TRTInternal Error in nvinfer1::builder::`anonymous-namespace'::LeafCNode::computeCosts: 0 (Could not find any implementation for node /model.22/proto/cv3/conv/Conv + PWN(/model.22/proto/cv3/act/Sigmoid, /model.22/proto/cv3/act/Mul).)
[10/23/2023-17:15:27] [E] Engine creation failed
[10/23/2023-17:15:27] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec # trtexec --onnx=yolov8n-seg.onnx --saveEngine=fp32.trt --workspace=2048 --int8 --exportTimes=int8.json

**Comment by glenn-jocher** [comment]
@lucy3589 hello,

I understand that you are encountering an issue while converting the `yolov8n-seg.onnx` model to TensorRT INT8 precision. Based on the logs provided, there are a few key points we can discuss:

1. The error message `[W] [TRT] Calibrator is not being used. Users must provide dynamic range for all tensors that are not Int32.` indicates that you may need to use a calibrator for TensorRT INT8 precision conversion. A calibration process is often required to generate a calibration table that approximates the floating point precision with INT8.

2. Another error `[E] [TRT] Try increasing the workspace size with IBuilderConfig::setMaxWorkspaceSize()` suggests that you might need to increase the workspace size for your TensorRT build. Your current workspace size seems to be 2048, but you might find better results with a larger workspace size.

3. Finally, the errors about not finding the implementation for a specific node in your network perhaps suggest some compatibility issues with TensorRT and the ONNX model structure.

In light of these considerations, I recommend the following steps:
- Try employing a calibrator for the INT8 conversion. This involves providing a representative dataset for the calibrator to use.
- Experiment with a larger workspace size when building the TensorRT engine.
- If the problem persists, it might be an issue regarding compatibility between the specific layers in the ONNX model and TensorRT. In that case, you might explore different build configurations or graph optimizations in TensorRT, or experiment with adjusting your model layers.

Please note that these are just suggestions based on the information you've provided and there might be other factors at play here. Don't hesitate to add more details if you continue to encounter problems, it would help us better understand and address the issue.

Best,
Glenn

**Comment by lucy3589** [comment]
> @lucy3589 hello,
> 
> I understand that you are encountering an issue while converting the `yolov8n-seg.onnx` model to TensorRT INT8 precision. Based on the logs provided, there are a few key points we can discuss:
> 
> 1. The error message `[W] [TRT] Calibrator is not being used. Users must provide dynamic range for all tensors that are not Int32.` indicates that you may need to use a calibrator for TensorRT INT8 precision conversion. A calibration process is often required to generate a calibration table that approximates the floating point precision with INT8.
> 2. Another error `[E] [TRT] Try increasing the workspace size with IBuilderConfig::setMaxWorkspaceSize()` suggests that you might need to increase the workspace size for your TensorRT build. Your current workspace size seems to be 2048, but you might find better results with a larger workspace size.
> 3. Finally, the errors about not finding the implementation for a specific node in your network perhaps suggest some compatibility issues with TensorRT and the ONNX model structure.
> 
> In light of these considerations, I recommend the following steps:
> 
> * Try employing a calibrator for the INT8 conversion. This involves providing a representative dataset for the calibrator to use.
> * Experiment with a larger workspace size when building the TensorRT engine.
> * If the problem persists, it might be an issue regarding compatibility between the specific layers in the ONNX model and TensorRT. In that case, you might explore different build configurations or graph optimizations in TensorRT, or experiment with adjusting your model layers.
> 
> Please note that these are just suggestions based on the information you've provided and there might be other factors at play here. Don't hesitate to add more details if you continue to encounter problems, it would help us better understand and address the issue.
> 
> Best, Glenn

thanks for your reply.
1. Don't worry about accuracy for now, just test speed. So you can leave the checkset out for now.

2. After using a larger space and a later version of tensorrt, this problem still exists

3. The suspicion is that there are two output problems. I removed one output [1,32,160,160] and several separate nodes in front of it, leaving only one output [1,116,8400] to convert trt-int8

**Comment by glenn-jocher** [comment]
Hello @lucy3589,

Thanks for the extended information. It's quite intriguing that you're able to convert to TensorRT INT8 successfully after removing one of the output nodes. It suggests that the issue may be related to the specific structure of your ONNX model when it has multiple outputs. The differences between your GPUs and TensorRT versions further complicate the matter. 

When you mention that several separate nodes were removed in front of the output, it makes me wonder if these nodes were interacting with both outputs in some manner that TensorRT's INT8 conversion can't handle.

To address the issue:

1. You could investigate whether the operations associated with the removed output node are fully compatible with TensorRT INT8 precision. If not, you might need to replace or modify those operations for conversion.

2. Regarding the different behaviours with different GPUs and TensorRT versions, it could be due to the specific architectures of these GPUs and the improvements in later TensorRT versions. Testing with different configurations might provide further insights.

Given the complexity of this problem, a thorough analysis of the model's structure would be required to fully understand the root cause of this issue.

Please continue to share any additional findings, they will be instrumental in solving this issue.

Best, Glenn

**Comment by lucy3589** [comment]
> Hello @lucy3589,
> 
> Thanks for the extended information. It's quite intriguing that you're able to convert to TensorRT INT8 successfully after removing one of the output nodes. It suggests that the issue may be related to the specific structure of your ONNX model when it has multiple outputs. The differences between your GPUs and TensorRT versions further complicate the matter.
> 
> When you mention that several separate nodes were removed in front of the output, it makes me wonder if these nodes were interacting with both outputs in some manner that TensorRT's INT8 conversion can't handle.
> 
> To address the issue:
> 
> 1. You could investigate whether the operations associated with the removed output node are fully compatible with TensorRT INT8 precision. If not, you might need to replace or modify those operations for conversion.
> 2. Regarding the different behaviours with different GPUs and TensorRT versions, it could be due to the specific architectures of these GPUs and the improvements in later TensorRT versions. Testing with different configurations might provide further insights.
> 
> Given the complexity of this problem, a thorough analysis of the model's structure would be required to fully understand the root cause of this issue.
> 
> Please continue to share any additional findings, they will be instrumental in solving this issue.
> 
> Best, Glenn

Let me fill in the details of the structure I modified
The first graph structure modification can be converted successfully. The second one can't be converted

![image](https://github.com/ultralytics/ultralytics/assets/33214551/d83093b7-b475-4b3e-bdb1-59abb52a5d14)![image](https://github.com/ultralytics/ultralytics/assets/33214551/7c0e446e-af1d-42ee-a9a3-aaefc58a1c4d)

**Comment by glenn-jocher** [comment]
Hi @lucy3589,

Thank you for providing the specifics and graphical representation of your model structure modifications. It helps to have a clearer picture of what was changed in your model.

From your diagram, it appears that when a specific series of nodes and a particular output layer are removed (as shown in your first graph structure), the conversion to TensorRT INT8 is successful. However, it fails when these components are included (as in your second graph structure).

Given this information, it's crucial to identify the operations performed by the set of nodes you removed. If these operations are not fully compatible with TensorRT INT8 precision, they might be the source of the problem.

Furthermore, the issue may lie not only in these individual operations but also in how they interact with the multiple outputs of your model. TensorRT INT8 might have issues processing models with multiple outputs or complex dependencies between nodes.

To narrow down the problem, I'd suggest isolating these operations and working with them independently to check their compatibility with TensorRT INT8. Also, consider simplifying the interaction between your model's nodes and outputs if possible.

Lastly, understand that while the model may work fine with other precision modes like fp16 or fp32, INT8 conversion can be more complex due to the heavy quantization and often requires fully compatible operations.

Please keep sharing your progress. Your inputs are valuable and contribute to an enhanced troubleshooting process.

Best, Glenn

**Comment by lucy3589** [comment]
Hi, @glenn-jocher ,
Thank you for your guidance. I'll try some of these methods later.
Best, Lucy

**Comment by cillayue** [comment]
> Hi, @glenn-jocher , Thank you for your guidance. I'll try some of these methods later. Best, Lucy

have you convert sucessfully? i met the same question

**Comment by Y-T-G** [comment]
The TensorRT version is probably old
