### ISSUE TITLE
How to specify connections between points in pose estimation task?

### ISSUE THREAD

**Issue by MaxTeselkin** [ultralytics/ultralytics#5926]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi! During training of YOLOv8 for pose estimation task I payed attention to the fact that connections between points of my graphs look weird (I attached visualizations of train batches generated by ultralytics below). How can I fix that?

I already faced similar problems when I was testing pose estimation models for animal pose estimation task, but forgot to change keypoints config (which allows to specify connections between points) and used keypoints config for humans during inference on animals - that's why predictions looked weird (because of incorrect connections between points). It looks like YOLOv8 has the same problem and tries to use standard COCO config for human, but I am trying to train model on horses, not humans.

![train_batch0](https://github.com/ultralytics/ultralytics/assets/91027877/c51fd414-35d2-41c3-86ab-97e6b8ed167a)
![train_batch1](https://github.com/ultralytics/ultralytics/assets/91027877/ab2f741f-ccad-4997-9f66-5561bfb793d1)
![train_batch2](https://github.com/ultralytics/ultralytics/assets/91027877/3c0a8dd5-e85a-4ced-a0d2-9692e74976e6)

P.S. My ultralytics version is 8.0.112.

**Comment by glenn-jocher** [comment]
@MaxTeselkin hello,

I appreciate your detailed question! When it comes to pose estimation tasks using YOLOv8, the connections between points are indeed determined by the keypoints' configuration. As you've correctly pointed out, your observations suggest that the keypoints' configuration may not be suitable for your particular task of horse pose estimation.

The issue originates from the model using the default keypoints' configuration that is designed for human pose estimation, which doesn't provide the optimal keypoint connections for animals like horses. You'll need to modify this configuration and specify the connections points tailored to your data — in this case, horses.

The configuration you need to modify would consist of information about keypoints' names and the pairs of keypoints that need to be connected. Once you adjust these parameters according to the structure of a horse, you'll be able to generate much more accurate and logical pose estimation results on your horse images.

Remember, the id of a keypoint in connections should start from 0, and the id should correspond to the position of a keypoint in the keypoints' list.

I hope this information helps! If you have any further questions or require more assistance, do let me know.

Best,
Glenn

**Comment by RizwanMunawar** [comment]
Hello @MaxTeselkin, The visuals show that the keypoints configuration is incorrect. In other words, the annotations appear to be in a different order than the sequence of keypoints provided in the 'YAML' file.

Suppose
During annotation, you have labeled the object keypoints in mentioned sequence
```1, 2, 4, 3, 5, 6, 8, 7```

But in the `YAML` file you have provided the object's keypoints in the mentioned sequence
```1, 2, 3, 4, 5, 6, 7, 8```

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by MaxTeselkin** [comment]
@glenn-jocher @RizwanMunawar Thanks for answers, I understand that keypoints configuration is incorrect, but I don't understand **where** can I change it? In [documentation](https://docs.ultralytics.com/datasets/pose/#ultralytics-yolo-format) is is written that in dataset config I should specify only `kpt_shape` and `flip_idx` and nothing about connections between points. In .txt files with annotations for images there are only class index, box coordinates, point coordinates and point visibility - once again, nothing about keypoints configuration.

If it is not dataset yaml file and not .txt files with annotations, so where can I change keypoints configuration?

**Comment by glenn-jocher** [comment]
Hello @MaxTeselkin,

The `kpt_shape` and `flip_idx` described in the documentation are indeed components of the dataset configuration. However, the configuration of connections between keypoints, while it is part of the model’s knowledge, it's typically not specified in the dataset configuration or in the annotation files.

To modify keypoints connections, you need to customize the code associated with keypoints configuration within the Ultralytics YOLOv8 repository. The connections between keypoints are hard-coded in the software logic and won't typically be found in any configuration files or dataset annotations.

If you navigate through the codebase, you'll find module(s) handling keypoints and their connections. It's in this part of the code that you can specify different connections that are appropriate for the structure of a horse, instead of the default human structure.

Please know that modifying software logic of a model requires advanced knowledge of the codebase and YOLOv8 architecture.

I hope this clears it up for you. Let me know if you have further questions!

Best,
Glenn

**Comment by MaxTeselkin** [comment]
Understood, thanks @glenn-jocher

**Comment by glenn-jocher** [comment]
You're welcome @MaxTeselkin! Don't hesitate to reach out if you have any further questions or issues. Happy coding!
