### ISSUE TITLE
How to get result data without for-loop on CPU?

### ISSUE THREAD

**Issue by cyu2023** [ultralytics/ultralytics#5927]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I am working on a program that detects human pose real-timely by YOLOv8 and uses keypoints position for further processing. I hope that data processing between YOLOv8 and another model can be carried out on GPU to save time. But I meet a problem.

YOLOv8 outputs "Results" of "generator" class, which cannot be used in the format liks Results[0]. I have browsed the document and found that for-loop is used. I found that if I use for-loop to extra data, it costs a long time (about 0.024s) to transmit data from GPU to CPU. So I import numba and tried to input the whole "Results" into a function decorated with @cuda.jit and @njit(nopython=True), but it said

> ValueError: Cannot determine Numba type of <class 'generator'>

Even single result in "Result" cannot be recognized by numba. How can I solve this problem?  Forgive me if I do not make myself understood. And I really appreciate of your help.

**Comment by glenn-jocher** [comment]
Hello,

Thank you for your clear explanation of the issue. You've correctly identified that the "Results" object returned by YOLOv8 is an iterable generator, which isn't compatible with the GPU processing model used by Numba and its @cyu2023.jit decorator.

However, there might be a workaround for the problem, where you can process the data on the GPU without having to do a full transfer to the CPU, thereby reducing the overhead time.

Since YOLOv8 performs its computations on the GPU using PyTorch, the output tensors of the model's forward pass are likely residing directly on the same GPU. In this case, you can directly access the tensors inside the "Results" class (these should be PyTorch Tensors) and perform your operations on these tensors using PyTorch operations. This way, you could likely achieve your end-to-end GPU processing without having to transfer most of the data back and forth from the GPU to CPU.

Though the exact solution would depend on the structure of your code and your use case, you should be able to access the detection results stored in the 'xyxy' attribute of each 'Pred' object in 'Results'. From there, you can use PyTorch operations to perform your desired processing directly on the GPU.

In such use cases, it might be helpful to review the working of the 'Results' class and the generated objects so that you can better understand how to interact with them and how to extract the information you need without inducing unnecessary CPU-GPU transfers.

Hope this helps you in resolving your performance issue, and let us know if you have any other questions!

Best,
Glenn

**Comment by cyu2023** [comment]
Thanks a lot. Your response has inspired me and it seems that the problem is solved. :)

**Comment by RizwanMunawar** [comment]
@cyu2023 I am closing this issue. reopen it If the issue persists.

Thanks
