### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 0)

### ISSUE THREAD

**Issue by VMASPAD** [ultralytics/ultralytics#5928]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I have seen all the posts and none of them can solve my problem, this is the error:
![err](https://github.com/ultralytics/ultralytics/assets/61850218/8ab6190e-e741-42df-a39e-0486c69e38d7)
![err](https://github.com/ultralytics/ultralytics/assets/61850218/f6c1f39e-0eaa-463d-ac08-b61a9dd579e8)
I can't find the error why this happens, this is the label of any image:

0 0.5380952380952381 0.47794117647058826 0.2785714285714286 0.5 0.4857142857142857 0.6147058823529412 0.5166666666666667 0.5941176470588235 0.5464285714285714 0.5941176470588235 0.5773809523809523 0.6176470588235294 0.5333333333333333 0.4073529411764706 0.525 0.47058823529411764 0.5011904761904762 0.5176470588235295 0.5452380952380952 0.5176470588235295 0.5702380952380952 0.41911764705882354 0.5976190476190476 0.4176470588235294 0.625 0.42058823529411765 0.4452380952380952 0.4161764705882353 0.46904761904761905 0.4161764705882353 0.49523809523809526 0.4161764705882353 0.5119047619047619 0.23529411764705882 0.4154761904761905 0.33088235294117646 0.4095238095238095 0.5235294117647059 0.45357142857142857 0.6544117647058824 0.5214285714285715 0.7161764705882353 0.6154761904761905 0.6676470588235294 0.6619047619047619 0.5220588235294118 0.6642857142857143 0.3558823529411765 0.6023809523809524 0.2514705882352941 0.6035714285714285 0.5279411764705882 0.4511904761904762 0.5161764705882353 0.5011904761904762 0.3205882352941177 0.5630952380952381 0.3191176470588235 0.5297619047619048 0.34852941176470587 0.4523809523809524 0.25 0.5630952380952381 0.6647058823529411 0.49404761904761907 0.6676470588235294 0.5333333333333333 0.29411764705882354

and dataset.yml

train: C:\Users\tomas\Desktop\Programacion\Python\Udemy\PythonParaNoMatematicos\V2\cara\YOLODataset/images/train/
val: C:\Users\tomas\Desktop\Programacion\Python\Udemy\PythonParaNoMatematicos\V2\cara\YOLODataset/images/val/
test: C:\Users\tomas\Desktop\Programacion\Python\Udemy\PythonParaNoMatematicos\V2\cara\YOLODataset/images/test/

kpt_shape: [32, 3]  # [number of keypoints, number of dim]
flip_idx: [0, 1, 2, 4, 3, 10, 11, 12, 13, 14, 5, 6, 7, 8, 9, 15, 16, 17, 18, 19, 20, 21, 22, 23, 27, 28, 29, 24, 25,
           26, 33, 34, 35, 30, 31, 32]
nc: 1
names: ["face"]

REMINDER: I am POSE trained

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by VMASPAD** [comment]
and i forgot, command:

yolo task=pose mode=train epochs=30 data=C:\Users\tomas\Desktop\Programacion\Python\Udemy\PythonParaNoMatematicos\V2\cara\YOLODataset\dataset.yaml  model=yolov8l-pose.pt imgsz=640 batch=2

**Comment by glenn-jocher** [comment]
@VMASPAD based on the error message you provided, it appears that Python expected 3 values in some point of your code execution, but didn't receive any. This error typically occurs when you're trying to unpack a sequence (like a list or a tuple), but there aren't enough values to be assigned to the variables.

In the specific context of YOLO, this error could occur if there are some inconsistencies in your label or configuration files. Here's a check list to debug this issue:

1. Ensure there is no trailing white space or newline at the end of your label file.

2. Make sure that all of your labels have the correct number of elements. Based on your label posted in the initial question, it seems like you're trying to parse a label with multiple key points. Make sure all your labels have the same structure.

3. In your `dataset.yml` file, confirm that `kpt_shape` parameter is set correctly. According to your posted configuration, your `kpt_shape` is `[32, 3]` which means 32 keypoints with 3 dimensions each. If this is inconsistent with your provided labels, it could cause the unpacking error.

4. When running custom trainings with pose estimation, ensure that your label files have the correct structure. Your command `yolo task=pose ..` indicates you're training YOLO for pose estimation. The label file for each image must have detailed (x, y, visibility) information for each key point.

5. Finally, and possibly most importantly, verify your command. Double check the paths to your data and model. Also ensure the other parameters like `imgsz` and `batch` are suitable for your machine's specifications.

**Comment by RizwanMunawar** [comment]
@VMASPAD, it appears that your points are in 2D coordinates rather than 3D coordinates. To potentially resolve your error, you can update the configuration from `kpt_shape: [32, 3]` to `kpt_shape: [32, 2]`. This adjustment should align with your data and address the issue you're facing.

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by whysirier** [comment]
the bug is no fixed, my data.yaml as:
path: ../datasets/antenna2023-pose  # dataset root dir
train: images/train2023  # train images (relative to 'path') 118287 images
val: images/train2023  # val images (relative to 'path') 5000 images
test:   # 20288 of 40670 images, submit to https://competitions.codalab.org/competitions/20794

# Keypoints
kpt_shape: [2, 3]  # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible)
flip_idx: [0, 1]

# Classes
names:
  0: antenna

my sample txt as:
0 0.396514 0.477679 0.388519 0.955357 0.340774  0.03683  2.000000  0.318452  0.683036  2.000000 

obviously, my dataset has one class and two keypoints, but also has  this error.

**Comment by glenn-jocher** [comment]
@whysirier given your dataset and label format, the error might be related to the improper handling of the `kpt_shape`. Your label suggests that you have two keypoints `(x, y)` and an additional `visible` flag is set to `2.000000`. Since you have a visibility flag, your `kpt_shape` should indeed be `[2, 3]`.

Please ensure the following:

1. The label format is consistent across all your `.txt` files. Each keypoint must be listed as `x y visibility`.
2. The visibility flag (the third value for each keypoint) is correctly used. If it's a binary flag (visible or not), make sure it's either `0` or `1`.
3. Your `dataset.yml` is indeed being read correctly and the correct keypoint configuration is being applied.
4. There is no issue with your dataset paths and that images are correctly paired with their label files.

If you're still encountering the error after these checks, please verify that the label files are generated correctly and there are no hidden characters or formatting issues.

If the issue persists, consider reviewing the documentation for keypoints to ensure all criteria are met for your use-case.
