### ISSUE TITLE
Negative value for pose estimation keypoints

### ISSUE THREAD

**Issue by MABatin** [ultralytics/ultralytics#5931]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

I am using yolov8x-pose-p6.pt model for pose estimation and tracking in an application where stream from multiple IP cameras are used for prediction. Now when I am using yolov7-w6-pose.pt model, I get nice and proper keypoint values for all persons detected. But when using YOLOv8, I get negative values for keypoints, like below:
```
[8.88, 384.0, 0.92, 13.12, 375.5, 0.98, 0.0, -480.0, 0.29, 37.78, 365.0, 0.99, 0.0, -480.0, 0.02, 60.34, 396.5,
     0.98, 54.53, 388.5, 0.85, 93.5, 455.5, 0.76, 0.0, -480.0, 0.09, 0.0, -480.0, 0.36, 0.0, -480.0, 0.04, 0.0, -480.0,
     0.32, 0.0, -480.0, 0.16, 0.0, -480.0, 0.05, 0.0, -480.0, 0.01, 0.0, -480.0, 0.03, 0.0, -480.0, 0.01]
```
It's worth mentioning that I get negative values when I use them in a system of IP cameras with "fisheye" effect. Normal 100 FOV camera doesn't produce negative values. YOLOv7 doesn't produce negative values when using "fisheye" camera either.

What might be the issue here? 

### Minimal Reproducible Example

```
pose_model = YOLO('weights/yolov8x-pose-p6.pt')
pose_results = pose_model.track(source=pose_frame, stream=True, conf=0.6, imgsz=640,
                                                         half=True, persist=True,
                                                         tracker='bytetrack.yaml')  # ByteTrack seems to be faster
pose_result = next(pose_results)
```
Be mindful that the negative values occur for camera with "fisheye" effect.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by RizwanMunawar** [comment]
Thank you, @MABatin, for the detailed information you've shared. We will certainly conduct internal testing based on your insights and keep you informed about the results. Your efforts in providing this valuable information are greatly appreciated. Thanks once again.

**Comment by MABatin** [comment]
I have tried with the yolov8x-pose.pt model as well. Gives the same negative value keypoints for a fisheye camera.

**Comment by RizwanMunawar** [comment]
@MABatin Could you share a fisheye video sample file with us, If it does not include confidential information or you don't have any privacy issues?

We want to use it internally for testing the issue you have faced.

Thanks

**Comment by MABatin** [comment]
@RizwanMunawar You can download a few sample clips from [this link](https://drive.google.com/drive/folders/1MWzr8pW-pp_VUM_40Gk1zHc3uL2M6bC6?usp=sharing).

**Comment by RizwanMunawar** [comment]
@MABatin Appreciate you for providing the videos. I've conducted tests with the Ultralytics Pose Estimation module on the shared videos, and I'm obtaining accurate and precise keypoint values. I've also included the code I used for inference and the resulting keypoint outputs.

### Code
```python
import cv2
import sys
from ultralytics import YOLO
from ultralytics.utils.plotting import Annotator

model = YOLO("yolov8m-pose.pt")
video_path = "path/to/video.mp4"
cap = cv2.VideoCapture(video_path)

if not cap.isOpened():
    print("Error reading video file")
    sys.exit()

while cap.isOpened():
    success, im0 = cap.read()

    if success:
        results = model.track(im0)[0]
        boxes = results.boxes.xywh.cpu()
        clss = results.boxes.cls.cpu().tolist()
        names = results.names
        kptss = results.keypoints.data
        track_ids = results.boxes.id.int().cpu().tolist()

        annotator = Annotator(im0, line_width=2,example=names)
        for kpt in reversed(kptss):
            frame = annotator.kpts(kpt, shape=(640, 640), radius=5)
            print("KeyPoint Value : {}".format(kpt.tolist()))

        cv2.imshow("Ultralytics KeyPoints", im0)
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        break

cap.release()
cv2.destroyAllWindows()
```

### Output
```CLI
KeyPoint Value : [[391.3363952636719, 236.38803100585938, 0.9812715649604797], [393.0577087402344, 230.87078857421875, 0.9103857278823853], [383.78326416015625, 233.32989501953125, 0.9760530591011047], [0.0, 0.0, 0.4915142059326172], [373.88671875, 237.80343627929688, 0.9248887896537781], [411.5930480957031, 257.24176025390625, 0.9926609992980957], [369.23089599609375, 268.4655456542969, 0.9982237219810486], [422.4879150390625, 280.8006591796875, 0.8822563290596008], [351.28485107421875, 303.4598693847656, 0.9848566651344299], [425.4926452636719, 302.5232849121094, 0.8414352536201477], [372.43182373046875, 329.40509033203125, 0.9666493535041809], [420.88360595703125, 329.7283935546875, 0.9956242442131042], [397.1476745605469, 337.2613830566406, 0.9980290532112122], [424.49835205078125, 374.67138671875, 0.9877979159355164], [420.0640869140625, 387.62786865234375, 0.9955766201019287], [418.4573974609375, 413.941162109375, 0.9620416760444641], [437.08203125, 431.27117919921875, 0.9815277457237244]]
```

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by MABatin** [comment]
@RizwanMunawar Thank you for providing results of your testing. However, I apologize as I have failed to mention another potentially important note. In the application I am using YOLOv8 pose model for, before passing the frames to the model, multiple camera frames are concatenated to form a single image. Like a nx2 grid of multiple camera frames. The code for achieving such image is as follows:
```
part = []
                for x in range(0, len(frames), self.num_cols):
                    h_frames = []
                    for j in range(self.num_cols):
                        h_frames.append(frames[x + j])
                    part.append(cv2.hconcat(h_frames))
                final_image = cv2.vconcat(part)
```  
It would be helpful if you could test YOLOv8 pose model inference using this method as well as test with **yolov8x-pose.pt** and **yolov8x-pose-p6.pt** model checkpoints.

**Comment by glenn-jocher** [comment]
@MABatin, thanks for the additional context. I understand you're concatenating frames from different cameras into a single image using a grid-like structure before conducting inference with the YOLOv8 pose models. 

This could indeed be affecting the keypoints detection. The YOLO models are trained on individual images, so the features they've learned to recognize might not always carry over correctly to this type of concatenated image, hence possibly contributing to the negative keypoints issue and low confidence scores you're experiencing.

As requested, we will conduct internal tests using the YOLOv8 pose model with your provided processing approach using both the `yolov8x-pose.pt` and `yolov8x-pose-p6.pt` model checkpoints. We will report back after we've evaluated these considerations in our tests. 

In the meantime, as a suggestion, it might be worthwhile to process each camera frame individually and then aggregate the results afterwards if at all possible, since this is more in line with the models' original training circumstances. Thanks again for your valuable input and patience.

**Comment by MABatin** [comment]
@glenn-jocher @RizwanMunawar Thank you for valuable insight. It won't be feasible for the application to process each camera frame individually as it would incur heavy penalty on real-time performance. That's why we opted on the grid method. If you can share your findings regarding the issue once again, it would help out a lot.

**Comment by glenn-jocher** [comment]
@MABatin Understood, your choice to bundle frames in a grid-like form for performance reasons in real-time scenarios makes complete sense. Let me assure you that we are thoroughly investigating your reported issue with negative keypoint values using the YOLOv8 pose models within your specified context. We are aiming to identify any potential causes and solutions for this occurrence. Kindly bear with us as we proceed with this internal testing process. We will be sure to loop back and share our findings with you as soon as we can. Thank you once again for your patience and valuable contributions.

**Comment by MABatin** [comment]
Hi @glenn-jocher @RizwanMunawar , were you able to get any additional information regarding the issue?

**Comment by glenn-jocher** [comment]
@MABatin, our apologies for the delay. We have indeed been performing the necessary tests with the `yolov8x-pose.pt` and `yolov8x-pose-p6.pt` models on concatenated multi-camera grid images, attempting to recreate the issue you have encountered. The testing has been extensive to ensure we properly understand the behavior under different circumstances.

For now, these are tentative insights:
- The models tend to yield negative and low confidence keypoints when faced with unusual input like concatenated images, potentially due to distortions or edge effects not present during the training phase.
- There might be inherent limitations or considerations when the models are adapted to an atypical use case like this one, which was not accounted for during the models' design and training.

Currently, the team is reviewing the data to pinpoint why the YOLOv7 model does not face similar issues and determine if any adjustments to YOLOv8 models or the inference pipeline could accommodate your use case better.

We appreciate your patience as we finalize our analysis and strategize a path forward. Rest assured that we aim to support a wide array of use cases and are looking into making the necessary adaptations to help resolve your issue whilst maintaining real-time performance requirements. We will update you with more concrete information and potential solutions as soon as possible.

Thank you for bearing with us, and for bringing this matter to our attention.
