### ISSUE TITLE
Predict - Ultralytics YOLOv8 Docs

### ISSUE THREAD

**Issue by rb-BH** [ultralytics/ultralytics#5937]
Hi I am trying to predict a segmentation on a series of 100 images in the form of a list of numpy arrays. The numpy arrays have an approximate size of 1500 x 700. I would like to just get the binary mask from each image.

for result in self.model.predict(source=frames, conf=0.5, max_det=1, stream=True, device=0, verbose=False):
            mask_raw = result[0].masks[0].cpu().data.numpy().transpose(1, 2, 0)

When I run this with 100 images (frames length = 100) I get the following OOM error showing that I have more free memory than it is trying to allocate. I am not sure why this is the case because I thought using stream=True should just bring one of the images into memory at a time in the loop. It will through the error before completing the first iteration of mask_raw.
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.10 GiB. GPU 0 has a total capacty of 12.00 GiB of which 7.07 GiB is free.torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.10 GiB. GPU 0 has a total capacty of 12.00 GiB of which 7.07 GiB is free.

I am using torch 2.1.0+cu121

Any advice is greatly appreciated!

**Comment by glenn-jocher** [comment]
@rb-BH hello, 

When you encounter an Out Of Memory (OOM) error, it usually indicates that the GPU doesn't have enough memory available for the task at hand. In your case, despite GPU 0 indicating 7.07 GiB memory free, your request to allocate 1.10 GiB of new memory might trigger an OOM error because GPU memory needs to accommodate existing processes and new allocation requests, making curating memory a delicate balancing act.

Using `stream=True` does indeed stream images one by one into memory during the loop to minimize memory usage. Nevertheless, when running large or multiple models simultaneously, or when processing large images, it's still possible to exceed the GPU's memory capacity.

Here are a few suggestions that might help resolve your issue:

1. **Optimize batch size**: If you're using a large batch size during prediction, reducing it may alleviate the memory pressure.

2. **Reduce image size**: If the images are large, consider resizing them to a smaller resolution to decrease memory usage.

3. **Upgrade your hardware**: If you're frequently running out of memory while performing various tasks, it might be beneficial to upgrade your hardware, particularly regarding increasing GPU memory.

4. **Update Libraries**: Sometimes, outdated libraries might not utilize resources efficiently, which can lead to unexpected allocation errors. Updating your libraries (like Pytorch) may improve memory efficiency. 

Remember, these are just common methods. Depending on your specific circumstances and project requirements, you may need other solutions. I hope this helps and best of luck with your segmentation tasks!

**Comment by huayecaibcc** [comment]
@glenn-jocher sorry for mention. I countered same problem on my YOLOV8 prediction. I already add stream=True for being OOM, but it sames not working.
I tried a test on this blow code:

res = []
for r in model.predict(
    source=images_dir,
    save_txt=False,
    save_conf=False,
    imgsz=2560,
    conf=0.25,
    iou=0.9,
    stream=True
):
    boxes = r.boxes.xywhn.cpu().detach().numpy().tolist()
    conf = r.boxes.conf.cpu().detach().numpy().tolist()
    res.append({'bbox': boxes, 'conf': conf})
    print(conf)

It shows that there is not one after another output, but wait for a period of time and then output all at once. So when there are a large number of images , it will OOM. I also tried a small number of images, it will not.
Futher, I find if i give a image folder directory to source likes model.predict(source="images_dir/", stream=True), it worked and has no OOM! But if i give a list of image path likes model.predict(source=["img1_dir", "img2_dir"...], stream=True), OOM happened!
So, I think there is maybe a bug for source of directory path.

**Comment by glenn-jocher** [comment]
@huayecaibcc, I understand the concern with the unexpected behavior while using `stream=True` with a list of image paths. It sounds like there might be an issue with how the images are loaded and processed when provided as a list which then leads to an accumulation of images in memory instead of streaming one by one, as is expected with `stream=True`.

The fact that using a directory path works as expected with streaming, but a list of paths does not, suggests there indeed might be a discrepancy in how the paths are handled. This could be something we need to investigate further in the YOLOv8 implementation.

As a workaround for now, I recommend two approaches:

1. **Use directory for inference**: Since you've indicated that using a directory path works correctly with streaming, you could move your images to a temporary directory and pass that path to the `source` parameter as a quick solution.

2. **Batch images in smaller sublists**: If the first option is not feasible, try breaking down your list of image paths into smaller batches and process them sequentially in separate calls to `model.predict`. This can simulate streaming and help manage memory usage, similar to how directory processing seems to be working.

Your feedback is valuable, and we aim to make our YOLO implementation as robust and user-friendly as possible. We will look into this potential discrepancy with the `stream` parameter when used with a list of image paths, and I would suggest keeping an eye on the repository for updates or fixes related to this issue.

Thank you for bringing this to our attention, and your patience and understanding are much appreciated as we work towards resolving this.

**Comment by felipebutcher** [comment]
fixed for me decreasing batch from 64 to 32

**Comment by glenn-jocher** [comment]
@felipebutcher great to hear that reducing the batch size to 32 resolved your issue! This is a common approach to manage GPU memory usage effectively. If further adjustments are needed, consider experimenting with even smaller batch sizes. Happy training! 😊👍
