### ISSUE TITLE
why always download yolov8n.pt? Can I disable transfer learning?

### ISSUE THREAD

**Issue by hujunyao** [ultralytics/ultralytics#5955]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to train a classify task, the train code is following:
```python
from ultralytics import YOLO
model = YOLO('yolov8x-cls.yaml') 
results = model.train(data='/xxx/xx/dataset/', epochs=100, imgsz=64)
```
I donot want to use transfer learning , so I donot use .pt files.  but when I start training , it goes to downloand yolov8n.pt , can I disable the transfer learning in train? how to ?

**Comment by glenn-jocher** [comment]
@hujunyao hi there,

Indeed, when you initialize a YOLOv8 model, it will by default download the pretrained weights (i.e., yolov8n.pt) to facilitate transfer learning. This is designed to help users achieve better results, as the model can start training from a point where it has already learned certain features.

But if you're seeking to train a model from scratch without loading any pretrained weights, it's definitely possible. You just need to disable transfer learning while invoking the train function. You can do this by setting the `weights` parameter to `''` (an empty string) in the train method.

When the `weights` parameter is set to `''`, the YOLOv8 model will then initialize random weights instead of using pretrained weights, hence disabling transfer learning. This applies for classifications tasks as well as other tasks like object detection or segmentation. 

Do keep in mind though, training a model from scratch could potentially require a lot more training data and considerably more time to converge compared to transfer learning. So make sure your dataset is sufficiently large and diverse.

Happy training, and please let us know if you run into any additional issues or concerns!

**Comment by curtis18** [comment]
@glenn-jocher I tried to set the pretrained weights using yolov10, yolov8n.pt is still downloaded. It does not matter if the file is downloaded once. However, it is present in the current working directory of the code to operate. When there are multiple directories for different trainings, multiple yolov8n.pt files are downloaded. Is there any settings to fix the yolov8n.pt at a specific directory? Thank you.

```python
from ultralytics import YOLO
model = YOLO('yolov10x.yaml').load('yolov10x.pt') 
results = model.train(data='/xxx/xx/dataset/', epochs=100, imgsz=64)
```

**Comment by glenn-jocher** [comment]
@curtis18 you can specify a directory for the pretrained weights by setting the `weights` parameter in the `YOLO` class to the desired path. This will prevent multiple downloads. Let me know if you need further assistance!

**Comment by curtis18** [comment]
@glenn-jocher Thank you for your help. I tried to set the weights, but the yolov8n.pt is still downloaded in the current working directory. 

```python
from ultralytics import YOLO
from pathlib import Path

model = YOLO('yolov10x.yaml').load(weights=Path('C:\weights\yolov10x.pt')) 
results = model.train(data='/xxx/xx/dataset/', epochs=100, imgsz=64)
```

<img width="844" alt="image" src="https://github.com/user-attachments/assets/f7d9e3e6-a4ed-4441-9893-435e306b9dc3">

**Comment by glenn-jocher** [comment]
You're welcome! To avoid downloading `yolov8n.pt`, ensure the `weights` path is correct and accessible. If the issue persists, check your environment for any default settings that might override your specified path.

**Comment by curtis18** [comment]
@glenn-jocher The issue is related to check_amp function on utils/checks.py, YOLO("yolov8n.pt") is fixed.

```python
    try:
        from ultralytics import YOLO

        assert amp_allclose(YOLO("yolov8n.pt"), im)
        LOGGER.info(f"{prefix}checks passed ✅")
    except ConnectionError:
        LOGGER.warning(f"{prefix}checks skipped ⚠️, offline and unable to download YOLOv8n. {warning_msg}")
    except (AttributeError, ModuleNotFoundError):
        LOGGER.warning(
            f"{prefix}checks skipped ⚠️. "
            f"Unable to load YOLOv8n due to possible Ultralytics package modifications. {warning_msg}"
        )
```

**Comment by glenn-jocher** [comment]
The AMP checks are integrated into the code to ensure compatibility and performance. Currently, there isn't a setting to override these checks directly. If you have specific requirements, consider modifying the `check_amp` function in your local setup.

**Comment by curtis18** [comment]
@glenn-jocher Understand and thank you so much. I will try to modify it to avoid yolov8n.pt downloading multiple times for different working directories.

**Comment by glenn-jocher** [comment]
You're welcome! If you need further assistance with modifying the setup, feel free to reach out.
