### ISSUE TITLE
Image loading compatibility

### ISSUE THREAD

**Issue by Yakuho** [ultralytics/ultralytics#5966]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Image loading why use ```cv2.imread``` not use ```cv2.imdecode(np.fromfile(path, np.uint8), cv2.IMREAD_UNCHANGED)```

```cv2.imread``` is invalid when an image containing a Chinese path like: ```/home/你好世界.png```, but ```cv2.imdecode(np.fromfile(path, np.uint8), cv2.IMREAD_UNCHANGED)``` can solve this trouble perfectly.

**Comment by glenn-jocher** [comment]
@Yakuho thank you for your question, and for proposing a potential solution. We use `cv2.imread` in our YOLOv8 repository because it is a widely used, simple, and effective method for image loading.

However, we do understand that `cv2.imread` can sometimes struggle with file paths that contain certain non-standard characters, such as Chinese characters. Your alternative suggestion of using `cv2.imdecode` combined with `np.fromfile` indeed seems like it could potentially address this issue.

We take all suggestions seriously, and we appreciate users like yourself taking the time to propose improvements. We'll look into this and consider whether it would be appropriate and beneficial to implement this change in a future update of the codebase. We aim to ensure that our tools are as robust and versatile as possible, to accommodate a wide range of uses and edge cases.

Thank you once again for your input, and for being a part of the YOLOv8 community.

**Comment by Yakuho** [comment]
you are right! We should do more experiments to verify its stability and compatibility.

**Comment by glenn-jocher** [comment]
@Yakuho thank you for your input. At Ultralytics, we aspire to develop the most reliable and robust solutions, and regular experimentation aids in achieving those goals. Exploring stability and compatibility is definitely a vital part of our improvement process for YOLOv8. 

We'll continue to conduct detailed testing and experimentation to confirm the performance and ensure the best possible user experience. Your suggestion is valued and serves as a reinforcement to our ongoing commitment. Thanks again for contributing to the YOLOv8 community.
