### ISSUE TITLE
ONNX Runtime Multiprocessing Implementation

### ISSUE THREAD

**Issue by DoctorSlimm** [ultralytics/ultralytics#5969]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Which of the YOLO OnnxRuntime files in /examples would be most suitable for easiest usage inside basic multiprocessing?
Been hoping to achieve this for a ling time given the portable size nature of YOLO i think it would be insane to be able to map multiprocess using huggingface_datasets for preprocesssing map function (which uses vanilla multiprocessing under the hood I believe).

A Relevant github issue on onnxruntime:
https://github.com/microsoft/onnxruntime/issues/7846

**Comment by glenn-jocher** [comment]
@DoctorSlimm hello,

It's fantastic to hear that you're looking to use multiprocessing with YOLOv8's ONNX Runtime example. For your requirement, the most suitable file would likely be 'ONNX_Inference.py'. This file provides a basic structure for loading an ONNX model and using it for inference, which you can adapt for multiprocessing.

For efficient multiprocessing, ensure that you manage memory appropriately to avoid thrashing or other performance issues. Since ONNX Runtime is thread-safe by design, it should be able to handle concurrent requests. However, remember to instantiate a separate session per process, as sharing sessions across processes isn't supported.

The issue you've highlighted from the ONNX Runtime repo discusses over-subscription as a consequence of using multiprocessing. Hence, being mindful of the number of processes you spawn is important. The optimal number will depend on your model, input data, and hardware.

With respect to `huggingface_datasets`, I assume you would like to use its `map` function in conjunction with multiprocessing. The map function is a versatile tool that, among other things, can indeed be used for preprocessing. However, this is outside of YOLOv8's jurisdiction, so I'll refrain from commenting on its multiprocessing capabilities.

Please feel free to let us know if you encounter any specific issues or if you require further details. We're always here to help.

All the best with implementing multiprocessing with YOLOv8!

Best,
Glenn

**Comment by DoctorSlimm** [comment]
Thanks @glenn-jocher You are a rockstar, almost got a full implementation that should work anywhere now soon (like AWS Lambda functions)!

**Comment by glenn-jocher** [comment]
@DoctorSlimm hello,

I'm delighted to hear that you have moved forward with your implementation, and it's great to know that it's shaping up to cater to environments like AWS Lambda! It's your effort and engagement that make it possible. Please remember that it takes a community to develop and improve models, and your contribution is a significant part of that.

In case you come by any more inquiries or issues as you continue to finalize your implementation with YOLOv8, please don't hesitate to raise them here. We're always ready to assist you. Looking forward to hearing more about your progress and success!

Best regards,
Glenn Jocher
