### ISSUE TITLE
Using rect=true for classification tasks and variable image sizes per class

### ISSUE THREAD

**Issue by pnr-consulting** [ultralytics/ultralytics#5996]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,

I have a classification task and sub-folders with variable image sizes per folder and within the folder (images can be 130x60, 250x102, 256x90, etc)

I'm aware of using `rect=true` for training and was wondering if `imgsz` needs to be defined? Are variable image sizes automatically padded? Does the model configuration automatically adjust input dimensions?

Thanks!

**Comment by glenn-jocher** [comment]
@pnr-consulting hi,

Thank you for your great question. It sounds like you're doing in-depth work with our YOLOv8 model for a classification task. We appreciate your diligence and use of the `rect=true` option. 

When using the `rect=true` option, YOLOv8 will effectively handle images of variable sizes. It works by adjusting the network strides dynamically for each batch of images based on their size, so you get rectangular training without having to resize your images to the same dimensions.

As for the `imgsz` parameter, it is generally defined during training. It determines the size that images will be resized to for processing. However, when dealing with varied image sizes, `imgsz` often represents the maximum dimension. Under the hood, images are automatically padded to square dimensions for batch formation, and then unpadded before the loss computation stage in the case of `rect=true`.

The model configuration doesn't automatically adjust the input dimensions. It observes the `imgsz` defined during training. Nonetheless, due to the dynamic stride adjustments with `rect=true`, YOLOv8 effectively handles varied input dimensions.

I hope this clears up your query. If you have any more questions or need further clarification, feel free to ask. Happy coding with YOLOv8!

**Comment by pnr-consulting** [comment]
Thanks! so essentially, `imgsz` (which defaults to 640?) doesn't have to be explicitly defined? Or is the recommendation to use a maximum possible size as seen in the dataset?

**Comment by glenn-jocher** [comment]
Hi @pnr-consulting,

Great follow-up question!

The `imgsz` does indeed default to 640 if not explicitly defined. Basically, it defines the maximum dimension that the images in your dataset will be resized to for training. If you don't define it yourself, the model will use this default value.

As for your second question, it's generally advised to set `imgsz` at a value either close to or equal to the maximum dimension observed in your dataset. However, this also should align with the resources (especially GPU memory) at your disposal because higher `imgsz` might require more memory.

However, the key is there is no strict requirement for it with `rect=true`. Even though the `imgsz` is defined, if `rect=true` is set, the model will still handle your varying image dimensions effectively by dynamically adjusting strides to accommodate different image sizes.

I hope this helps, but feel free to ask if you have more questions!
