### ISSUE TITLE
Streamed result only shows cropped portions of the screen

### ISSUE THREAD

**Issue by leezx337** [ultralytics/ultralytics#5997]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

May i know why the streamed result of the inference when i run this code:

`from ultralytics import YOLO
# from ultralytics.yolo.v8.detect.predict import DetectionPredictor

# Load a model
model = YOLO("yolov8s.pt")  # load a pretrained model (recommended for training)

source = 'https://www.youtube.com/watch?v=71XqEsT8rFI'

# Use the model
results = model.predict(source, show=True, save=True, stream=True)

for result in results:
    boxes = result.boxes  # Boxes object for bbox outputs
    masks = result.masks  # Masks object for segmentation masks outputs
    probs = result.probs  # Probs object for classification outputs`

Give me a cropped version of the original video? Is it possible to fix this? Thank you

![Screenshot (18)](https://github.com/ultralytics/ultralytics/assets/134577768/03f356a7-0dee-4930-a342-bce92d78c482)
![Screenshot (19)](https://github.com/ultralytics/ultralytics/assets/134577768/5fe666e2-7c0d-481e-a9e6-976667ab8daa)

**Comment by RizwanMunawar** [comment]
Thanks for the info, @leezx337. It appears that you're not interested in visualizing inference results, right?

**Comment by leezx337** [comment]
Hello @RizwanMunawar, thanks for getting back 😀 I'm interested in visualizing the inference results live in full screen (un-cropped version). Hope this clarifies 😄

**Comment by glenn-jocher** [comment]
Hello @leezx337,

Thank you for clarifying your issue - it's helpful to understand that you want to visualize the entire frame during the live streaming inference.

The cropping you are experiencing might take place due to the resizing of the input feed during pre-processing as the model expects a certain input size. The Ultralytics YOLOv8 offers automatic resizing to achieve this, which might cause some images or frames to appear cropped or squished.

The best solution in this case would be to adjust the aspect ratio or the resolution of the input video feed. However, keep in mind that this could potentially affect the detection results as the detection layers in YOLO models are sensitive to changes in resolution and aspect ratio.

I hope this helps! Let me know if you have any more questions.

**Comment by leezx337** [comment]
Hello @glenn-jocher, thank you so much for your prompt response!! I've managed to resolve the issue. It turns out that the issue is due to local display settings... It will be resolved if i set the 'Scale' to 100% (image attached). Sorry for the trouble, thank you!
<img width="707" alt="Screenshot 2023-10-30 131435" src="https://github.com/ultralytics/ultralytics/assets/134577768/80637430-764c-4e04-9a74-477215c26b28">

**Comment by glenn-jocher** [comment]
Hello @leezx337,
  
I'm glad to hear that you were able to resolve the issue! It's interesting to know that local display settings caused the cropping. Your experience will be beneficial to other users who might encounter a similar issue. 

Don't hesitate to ask if you have other questions or encounter other issues in the future. That's what we're here for. Thank you for using YOLOv8!
  
Best regards,
Glenn Jocher
