### ISSUE TITLE
 model classes pram not working

### ISSUE THREAD

**Issue by mohaMKRaod** [ultralytics/ultralytics#6004]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train, Predict

### Bug

i have a problem when i use the classes pram in training YOLO it works but when i use it with RTDETR model it show the classes that i selected in the engine/trainer: but it trains on all the classes and learn all of them 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by mohaMKRaod** [comment]
![Screenshot from 2023-10-29 13-14-53](https://github.com/ultralytics/ultralytics/assets/29186345/dfaa9914-987a-4bc3-896b-870f8114442c)
![Screenshot from 2023-10-29 13-15-14](https://github.com/ultralytics/ultralytics/assets/29186345/22b6a6e4-4a55-42ca-a3de-5326619d2224)

**Comment by glenn-jocher** [comment]
@mohaMKRaod thank you for providing screenshots to clarify the issue you're experiencing with the classes parameter in the RT-DETR model. 

It seems the classes parameter is being recognised by the engine/trainer, but it's not excluding the classes not specified from training. This is certainly not expected behaviour and I'm sorry it's impacting your project.

Ultralytics' intention with the classes parameter is to allow users to selectively train on certain classes. If the RT-DETR model is learning all classes despite specifying a subset, there is likely a bug that needs to be addressed.

We'll be looking into this matter and will keep you updated on our progress. If you can provide more detailed logs or any additional information that you think may help us troubleshoot, it would be greatly appreciated. Once again, thank you for bringing this to our attention and your patience as we work to resolve this issue.
