### ISSUE TITLE
Benchmarking Script for YOLOv8 similar to the one for YOLOv5

### ISSUE THREAD

**Issue by MarkhamLee** [ultralytics/ultralytics#6012]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Are there are any plans in place to create a benchmarking script for YOLOv8 similar to the one that's in the YOLOv5 repo? In the past I've found it fairly helpful w/r/t evaluating hardware.

**Comment by COWI-MI** [comment]
@MarkhamLee I think it already exists here [ultralytics/utils/benchmarks.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/benchmarks.py)

**Comment by glenn-jocher** [comment]
Hello @COWI-MI, 

Thank you for your question regarding benchmarking in YOLOv8. Currently, YOLOv8 doesn't have a separate benchmarking script. However, performance metrics like inference time and FPS can be obtained through some function calls within the Ultralytics framework. 

This framework is designed for robustness and versatility among various computer vision tasks. Therefore, while there might not be a dedicated benchmarking script as you have seen in some other repositories, you can still evaluate model performances in different aspects by checking the logs during and after model training and detection.

Remember, these metrics depend highly on the hardware (CPU/GPU) used, and it's recommended to make certain that your environment meets the requirements for optimizing model performance to get accurate benchmarks.

We appreciate your understanding and hope this information is helpful in your YOLOv8 exploration. If you have more questions or need further clarification, don't hesitate to ask. 

Happy coding!

**Comment by MarkhamLee** [comment]
> @MarkhamLee I think it already exists here [ultralytics/utils/benchmarks.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/benchmarks.py)

Thanks for this, interestingly enough it looks like it was created just three weeks ago. I'm going to run this today and will update this thread if anything is off, in case anyone else can make use of my findings.

**Comment by MarkhamLee** [comment]
I tried to run the benchmark script but I got an error, namely:

```
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
```

After getting this response the first time I installed the requirements.txt file in a new a virtual environment, in case the issue would be resolved by using the versions of the dependencies in the requirements file vs what I already had in my environment for testing YOLO and got the same result. The other thing I noticed was that I was getting a message about results being saved to the utils directory, but I didn't see anything saved there. 

I'm going to a search in issues to see if anyone has raised this, and if not I'll raise another issue for this problem.

**Comment by glenn-jocher** [comment]
@MarkhamLee hi there,

Sorry to hear that you're experiencing issues with the benchmark script. Thank for you for providing the detailed error message, this makes it easier for us to identify the problem.

The error you're encountering seems to be related to the specific version of numpy you're using. In recent numpy versions, `numpy.bool` has been deprecated. You might be using a newer version of numpy where `numpy.bool` has been completely removed. The benchmark script seems to be using this deprecated feature, hence why you're getting an `AttributeError`.

As for the results not being saved in the utils directory, it might be due to the script execution stopping at the aforementioned error before it could write the results. It could also be a different issue entirely.

We understand your concern and frustration. We take issues like this seriously as it affects the user experience. Your valuable feedback helps us in improving YOLOv8. The team will be informed about this issue, and we will begin working on a fix.

Your patience and understanding are appreciated. In the meantime, it's a good idea to search in the issues or raise a new one as you mentioned. You're also welcome to contribute to the project if you have a solution. 

Thank you.
