### ISSUE TITLE
AttributeError: 'YOLO' object has no attribute 'smart_load'

### ISSUE THREAD

**Issue by davidvct** [ultralytics/ultralytics#6021]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

ultralytics version: 8.0.191

here is the related line of codes:
```
from ultralytics.cfg import get_cfg
from ultralytics.data.converter import coco80_to_coco91_class
from ultralytics.data.utils import check_det_dataset
from ultralytics.engine.validator import BaseValidator as Validator
from ultralytics.models.yolo import YOLO
from ultralytics.utils import DATASETS_DIR
from ultralytics.utils import DEFAULT_CFG
from ultralytics.utils import ops
from ultralytics.utils.metrics import ConfusionMatrix

def prepare_validation(model: YOLO, args: Any) -> Tuple[Validator, torch.utils.data.DataLoader]:
    validator = model.smart_load("validator")(args)
    validator.data = check_det_dataset(args.data)

def main():
    MODEL_NAME = "yolov8n-seg"

    model = YOLO(f"{ROOT}/{MODEL_NAME}.pt")
    args = get_cfg(cfg=DEFAULT_CFG)
    args.data = "coco128-seg.yaml"

    # Prepare validation dataset and helper
    validator, data_loader = prepare_validation(model, args)

if __name__ == "__main__":
    main()
```

I found `smart_load` method is in class Model of `ultralytics/engines/model.py`

How can I fix it?

**Comment by glenn-jocher** [comment]
@davidvct hello,

Thank you for providing detailed information about the issue.

The AttributeError you're experiencing is because the 'smart_load' method is indeed not an attribute of the 'YOLO' class, it's a part of the 'Model' class in our module.

To resolve the problem, you should call 'smart_load' from a 'Model' object, not a 'YOLO' object. The 'smart_load' function is primarily intended to be used for the loading of pretrained weights and/or optimizer state during the training process, which is handled by the 'Model' class, not the 'YOLO' class.

The 'YOLO' class is primarily responsible for the architecture of the YOLOv8 model, including the creation and initialization of the model layers, the forward pass, and the computation of losses.

I hope this clears up the misunderstanding. If you have any more questions or issues, feel free to ask. Happy coding!

**Comment by HiImBush** [comment]
Hi @glenn-jocher, i encountered the same problem when i try to quantize my custom Yolov8n model. You said that we should call "smart_load" from a 'Model' object not from a 'YOLO' object. Could you give me a code snippet on how to do that?

**Comment by glenn-jocher** [comment]
Hi there! 👋

It seems there was a bit of confusion. The `smart_load` method is not directly accessible through the `YOLO` class as it's part of the internal mechanics for model management. For quantizing your YOLOv8n model, you can use the built-in export functionality which supports various formats including quantized versions.

Here's a quick snippet on how you might export your model to ONNX with quantization:

```python
from ultralytics import YOLO

# Load your custom model
model = YOLO('path/to/your/custom_model.pt')

# Export the model to ONNX with quantization
model.export(format='onnx', half=True)  # Set 'half=True' for FP16 quantization
```

For more details on exporting models and the options available, you can check out the [export documentation](https://docs.ultralytics.com/modes/export/#export-formats).

Let me know if this helps or if you have any more questions!
