### ISSUE TITLE
Image size training

### ISSUE THREAD

**Issue by MonteiroAlvesMatheus** [ultralytics/ultralytics#6024]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

During the preparation of a custom dataset for training, I had a question. In my custom dataset, I have images of various sizes: 1920x1080, 1280x720, 640x480, and 352x260. When I set the training parameter imgsz=640, does this mean that during training, the images will be resized to 640x640, either compressed for images larger than 640 or stretched for images smaller than 640?

I also have another question: for training, what is better, cropping to 640x640 or to 640x480, to ensure that the image doesn't become distorted during training?

Furthermore, I noticed in the source code that when I perform object detection on images of sizes different from 640x480, there's resizing, for example, from 1920x1080 to 640x384, which distorts the image and introduces some noise. Is there a way to work around this issue, such as applying some preprocessing to my image before making predictions?

**Comment by glenn-jocher** [comment]
@MonteiroAlvesMatheus hello, 

Great questions! And to answer them:

1. The imgsz training parameter determines the size to which your input images will be resized for the training process. If imgsz=640, it implies that the longest side of your images will be resized to 640 pixels, maintaining the aspect ratio. So, for a 1920x1080 image, it will be resized to 640x360. No stretching or compressing to form a square image will be done.

2. Regarding your question on whether to crop to 640x640 or 640x480, that largely depends on your specific use case. If maintaining the original aspect ratio of your images is important, cropping to 640x480 may be a more suitable option. However, it's essential to mention here that the cropping procedure should ensure the objects of interest in your image remain visible and properly framed.

3. As for object detection on images of various sizes, YOLOv8 automatically manages resizing while maintaining the aspect ratio without distorting the images. If you notice any distortion or noise, it's likely due to the way images are being displayed post-resize, rather than an issue with the resizing process itself.

In general, preprocessing images to maintain a consistent aspect ratio or size can certainly help improve the consistency of your results and is typically a good practice when preparing data for machine learning models. 

I hope this answers your questions, feel free to ask if anything else needs clarifying!
