### ISSUE TITLE
Can't Install "pip install ultralytics" Freshly installed pythons newest version, in Path.

### ISSUE THREAD

**Issue by Catplayz2011** [ultralytics/ultralytics#6030]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

https://github.com/ultralytics/ultralytics/assets/144529766/fedf5756-4f5a-4f2d-a153-f772f0772cd5

It wont intall its seems bugges out

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Catplayz2011 hello, thank you for reaching out for help regarding the installation of the Ultralytics package. I appreciate you trying to contribute with a PR!

From the partial log you shared, it's unclear what the exact error might be. However, a common issue users face is related to the compatibility of versions between Python, pip, and the Ultralytics package. We recommend using Python 3.8 or later, along with a matching latest version of pip. Sometimes, an outdated version of pip may cause problems in installing packages.

Also, you mention adding Python to your PATH. This is important, and it's equally essential to check if pip is also on your PATH, and you're operating in the correct Python environment where these are accessible.

Here are a few steps you might find helpful:

1. Verify your Python version with `python --version` in the terminal. Ensure the version is at least 3.8.

2. Update pip to the latest version using `python -m pip install --upgrade pip`.

3. Attempt to install the Ultralytics package again with `pip install ultralytics`.

If you continue to face difficulties, could you please provide more context or a more detailed error message? This should help us identify the issue more precisely and offer a more targeted resolution.

Thank you for wanting to submit a PR! We appreciate your willingness to help. We highly encourage everyone to pitch in when they can, as every contribution helps the YOLO community and makes it stronger.

**Comment by Catplayz2011** [comment]
It worked i Istalled python 3.11.6 because ppl told me the last version was broken AND yes it was broken now it has worked.

**Comment by glenn-jocher** [comment]
@Catplayz2011 i'm glad to hear that downgrading to Python 3.11.6 resolved your installation issue for the Ultralytics package. It's not unusual to encounter such anomalies with the very latest versions of software stacks as unforeseen issues can sometimes emerge after release. 

Your experience is a good reminder that while it's necessary to keep software up to date for security and feature enhancements, in some cases, earlier stable versions may be more reliable for certain needs.

Thank you for bringing this up; your experience may assist others encountering a similar situation. Have a fantastic journey with YOLOv8, and please feel free to reach out if you have any more questions or concerns. The strength of our community lies in members like you who are eager to share their experiences and solutions.

**Comment by TakatheUltimate** [comment]
I have downloaded python 3.11.6 but for me it always says that: 'yolo' is not recognized as an internal or external command,
operable program or batch file.

**Comment by glenn-jocher** [comment]
@TakatheUltimate the message you're seeing indicates that the `yolo` command is not in your system's PATH, or the script/program you're trying to run is not installed correctly.

For Ultralytics YOLOv8, the installation and execution process doesn't typically involve a command simply called `yolo`. Here's what you need to do to work with YOLOv8 after you have installed Python and ensured pip is working correctly:

1. **Install the YOLOv8 Package**: Use the pip command to install the Ultralytics package:
   ```
   pip install ultralytics
   ```

2. **Run YOLOv8 from the Command Line**: Once you have installed the Ultralytics package, you would generally use Python to run your YOLOv8 scripts or commands. For example, you might use a command like this to run predictions using YOLOv8:
   ```
   python path-to-your-script.py
   ```
   Please replace `path-to-your-script.py` with the actual path of the Python script you want to run that uses the YOLOv8 package.

3. **Use Python Interactive Shell or Scripts**: To call the Ultralytics YOLOv8 functionality, you would typically be working within a Python script or the Python interactive shell. For example:
   ```python
   from ultralytics import YOLO  # This imports the YOLO class from the Ultralytics package
   ```

Remember that commands like `yolo` are not standard and won't work unless they have been specifically set up in your environment, such as by defining an alias or creating a batch file or shell script with that name.

If you are following instructions from the Ultralytics documentation at https://docs.ultralytics.com, please ensure that you are inputting the correct commands in your terminal or command line.

If you are trying to use YOLOv8 for a specific task, please revert to the documentation to ensure you are following the correct steps. There you'll find detailed instructions about initiating training, running validation, exporting weights, and more, all done within Python scripts or by using the Python interpreter with the correct module calls and command-line arguments.

**Comment by TakatheUltimate** [comment]
Thanks for answering me, sadly I am still unable to use the commands stated in the CLI but python seems to somewhat work for me, I am stuck again this time there is always this error that pops up:
NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'torchvision::nms' is only available for these backends: [CPU, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].

CPU: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\cpu\nms_kernel.cpp:112 [kernel]
QuantizedCPU: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\quantized\cpu\qnms_kernel.cpp:124 [kernel]
BackendSelect: fallthrough registered at ..\aten\src\ATen\core\BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:153 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at ..\aten\src\ATen\functorch\DynamicLayer.cpp:498 [backend fallback]
Functionalize: registered at ..\aten\src\ATen\FunctionalizeFallbackKernel.cpp:290 [backend fallback]
Named: registered at ..\aten\src\ATen\core\NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at ..\aten\src\ATen\ConjugateFallback.cpp:17 [backend fallback]
Negative: registered at ..\aten\src\ATen\native\NegateFallback.cpp:19 [backend fallback]
ZeroTensor: registered at ..\aten\src\ATen\ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:86 [backend fallback]
AutogradOther: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:53 [backend fallback]
AutogradCPU: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:57 [backend fallback]
AutogradCUDA: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:65 [backend fallback]
AutogradXLA: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:69 [backend fallback]
AutogradMPS: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:77 [backend fallback]
AutogradXPU: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:61 [backend fallback]
AutogradHPU: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:90 [backend fallback]
AutogradLazy: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:73 [backend fallback]
AutogradMeta: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:81 [backend fallback]
Tracer: registered at ..\torch\csrc\autograd\TraceTypeManual.cpp:296 [backend fallback]
AutocastCPU: fallthrough registered at ..\aten\src\ATen\autocast_mode.cpp:382 [backend fallback]
AutocastCUDA: fallthrough registered at ..\aten\src\ATen\autocast_mode.cpp:249 [backend fallback]
FuncTorchBatched: registered at ..\aten\src\ATen\functorch\LegacyBatchingRegistrations.cpp:710 [backend fallback]
FuncTorchVmapMode: fallthrough registered at ..\aten\src\ATen\functorch\VmapModeRegistrations.cpp:28 [backend fallback]
Batched: registered at ..\aten\src\ATen\LegacyBatchingRegistrations.cpp:1075 [backend fallback]
VmapMode: fallthrough registered at ..\aten\src\ATen\VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at ..\aten\src\ATen\functorch\TensorWrapper.cpp:203 [backend fallback]
PythonTLSSnapshot: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:161 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at ..\aten\src\ATen\functorch\DynamicLayer.cpp:494 [backend fallback]
PreDispatch: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:165 [backend fallback]
PythonDispatcher: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:157 [backend fallback]

**Comment by glenn-jocher** [comment]
@TakatheUltimate, the error you're encountering is related to a PyTorch operation (`torchvision::nms`) that is not implemented for the 'CUDA' backend in your current environment. This typically implies there's an issue with your PyTorch or torchvision installation, particularly with the CUDA support.

Here are a few steps you can try to resolve this:

1. **Check CUDA Compatibility**: Ensure that the version of PyTorch you’ve installed is compatible with the version of CUDA installed on your system. You can see which CUDA version PyTorch is compiled with by running:
   ```
   python -c "import torch; print(torch.version.cuda)"
   ```

2. **Reinstall PyTorch and torchvision**: If your CUDA version is compatible with your installed PyTorch but you’re still experiencing issues, it could be helpful to reinstall PyTorch and torchvision. You can find the correct command for installation using the [PyTorch official website](https://pytorch.org), which provides a command generator based on your system configuration.

3. **Check if CUDA is Enabled**: Ensure CUDA is properly enabled for PyTorch by running:
   ```
   python -c "import torch; print(torch.cuda.is_available())"
   ```
   This should return `True` if CUDA is available and correctly set up.

4. **Check GPU Driver**: Make sure your NVIDIA drivers are up to date. Sometimes a mismatch between drivers, CUDA toolkit, and the PyTorch version can lead to issues.

5. **Use Correct PyTorch Functions**: When running certain functions in PyTorch that rely on a backend like CUDA, they need support for that specific operation. If an operation isn't implemented for the current backend, this kind of `NotImplementedError` can occur.

If you continue to run into trouble after trying these steps, consider visiting the PyTorch forums or Stack Overflow where you can provide the error message and details about your setup for tailored assistance. It’s essential that your PyTorch and CUDA setup align correctly to utilize GPU acceleration for models. Make sure to outline the versions of Python, PyTorch, torchvision, and CUDA you are using to ensure more targeted help.
