### ISSUE TITLE
stream=True issue

### ISSUE THREAD

**Issue by shidaijiya** [ultralytics/ultralytics#6033]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

在使用stream=True的时候代码会直接结束并且没有任何报错，但是在stream=False他会继续运行
With stream=True the code terminates without an error, but with stream=False it keeps running
![image](https://github.com/ultralytics/ultralytics/assets/117809405/52999775-9b4d-4862-9bd8-b300e3465289)

### Environment

python 3.8 , pytorch121
-------------------------------------------------
The model is Asus ROG STRIX G15DK_G15DK
Operating System Microsoft Windows 10 Professional (64-bit)
CPU AMD Ryzen 7 5800X 8-Core Processor(3801 MHz)
Motherboard ASUS G15DK
Memory 48.00 GB (3200 MHz)
GPU NVIDIA GeForce RTX3060

### Minimal Reproducible Example

```from ultralytics import YOLO
# 加载模型
# model = YOLO("yolov8n.yaml")  # 从头开始构建新模型
model = YOLO("best.pt")  # 加载预训练模型（建议用于训练）
# 目标路径
source = ''
# 对目标运行推断   路径           保存        标记框粗细      内存管理       是否显示    选择CUDA显卡
results = model(source=source, save=True, line_width=2, stream=True, show=True, device=[0])```

### Additional

_No response_

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@shidaijiya the code terminating without an error when setting `stream=True` could be due to a variety of reasons. Without detailed error logs, it's tough to deduce precisely what's going wrong. Here are a few things you could try:

1. Ensure the source path is correct: Ensure that the source path for the images or videos is correct and accessible by the application. 

2. Test your NVIDIA driver: Your NVIDIA graphics driver might be behaving erratically. You could try updating your NVIDIA drivers and see if the runtime issue persists.

3. Check the PyTorch and CUDA compatibility: There could also be some compatibility issues between PyTorch and the CUDA version on the system. Please ensure that your runtime environment supports both and is up to date.

4. Validate GPU assignment: Make sure that the assigned device (`device=[0]`) corresponds to an existing GPU in the system.

Once again, without detailed error logs, it's quite tough to pinpoint exactly what is wrong. I'd recommend trying to run the code on another system to see if the issue persists.

Hope this helps, and feel free to submit a PR if you can fix this issue! We appreciate your willingness to contribute to the YOLOv8 community!

**Comment by xie-qiang** [comment]
hello!  I have the same problem? have you solved this problem

**Comment by glenn-jocher** [comment]
@shidaijiya hello! If you've managed to solve your issue with `stream=True` terminating the code unexpectedly, that's fantastic! 🎉 It would be incredibly beneficial for the community if you could share what the problem was and how you addressed it. Posting this information as a comment on the relevant GitHub issue can help others who might be facing the same situation.

Thank you for your contribution to the YOLOv8 community, and I'm glad to hear that your problem is resolved! 🚀 If you have any additional insights or details, feel free to discuss them in the GitHub issues; your experience could be a valuable resource for others.

**Comment by glenn-jocher** [comment]
@shidaijiya hello! It's great to see the community actively helping each other out. It looks like the posted solution involves iterating over the results to access the bounding boxes, masks, and category probabilities. If indeed the absence of this iteration was causing the issue with `stream=True`, then adding this processing step may resolve the problem. 

Users encountering similar issues might find this approach useful, and I'm glad that members of the community are sharing their solutions! Your willingness to help is what makes the YOLOv8 community thrive. 👍

If anyone tries this fix and finds it successful, it might also be worth informing the rest of the community by commenting on the original GitHub issue thread so that others can benefit from your experience. Thanks again for your contribution! 🚀

**Comment by zzw8969** [comment]
hello! I have the same problem?

**Comment by zzw8969** [comment]
问题解决了，返回的的确是个生成器，用楼上的方法，取下内容就行了
for r in results:
        boxes = r.boxes  # Box object used for boundary box output
        masks = r.masks  # Mask object used to split mask output
        probs = r.probs  # Category probability for classification output

**Comment by glenn-jocher** [comment]
@zzw8969 great to hear that the issue is resolved! Using the generator correctly by iterating over the results, as you've done, is indeed the way to handle `stream=True`. This approach allows for efficient memory management, especially with large datasets or long videos. Keep up the good work, and thank you for sharing your solution with the community! 🌟 If you have further questions or insights, feel free to reach out. Happy coding!

**Comment by glenn-jocher** [comment]
@shidaijiya 很高兴听到您已经解决了问题，并感谢您分享解决方案！这对社区来说非常有价值。如果您有其他问题或想法，请随时分享。祝您编程愉快！🎉
