### ISSUE TITLE
generate wrong output folder when using today's date

### ISSUE THREAD

**Issue by nickjyj** [ultralytics/ultralytics#6034]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Installed the ultralytics using pip. When I was training the model with the command: 
`yolo train data=coco128.yaml model=yolov8n.pt project=temp name=2023-10-29`

The output folder temp/1984 is created instead of temp/2023-10-29. 
Here is the screenshot:
![Screenshot from 2023-10-30 16-27-32](https://github.com/ultralytics/ultralytics/assets/46984040/c71d78fe-4afc-494b-b6dc-f99949303674)

Please fix the bug. Thank you for the awesome work!

### Environment

Ultralytics YOLOv8.0.203 🚀 Python-3.8.10 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090, 24252MiB)
Setup complete ✅ (16 CPUs, 156.9 GB RAM, 794.7/3660.8 GB disk)

OS                  Linux-5.15.0-83-generic-x86_64-with-glibc2.29
Environment         Linux
Python              3.8.10
Install             pip
RAM                 156.89 GB
CPU                 Intel Xeon W-2245 3.90GHz
CUDA                11.7

matplotlib          ✅ 3.5.2>=3.3.0
numpy               ✅ 1.24.3>=1.22.2
opencv-python       ✅ 4.7.0.72>=4.6.0
pillow              ✅ 9.5.0>=7.1.2
pyyaml              ✅ 6.0>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.0.1>=1.8.0
torchvision         ✅ 0.15.2>=0.9.0
tqdm                ✅ 4.65.0>=4.64.0
pandas              ✅ 2.0.2>=1.1.4
seaborn             ✅ 0.12.2>=0.11.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@nickjyj hello, thank you for bringing this issue to our attention, and glad to know you're finding our work useful!

From your description, it seems that there might be an issue with the way the CLI interprets the `name` attribute when it is given in date format. Ideally, given your command, the model should indeed be saved in the `temp/2023-10-29` directory.

The system might be interpreting the date format as a mathematical operation, hence '1984' is being created instead (2023 - 10 - 29 = 1984). We'll look into this and work on a fix.

Meanwhile, as a workaround, you might want to use another naming convention for your projects to avoid this issue. For example, you could use underscores instead of dashes: `name=2023_10_29`.

Thank you again for your valuable feedback, and we appreciate your help in making YOLOv8 better!

**Comment by nickjyj** [comment]
this issue had been resolved but I found this issue happened again recently. Could you take a look? @glenn-jocher

**Comment by glenn-jocher** [comment]
@nickjyj please ensure you're using the latest version of the repository, as updates often resolve recurring issues. If the problem persists, feel free to provide more details for further assistance.

**Comment by Y-T-G** [comment]
You can add quotes to the name. `name="2023-10-29"` 

Otherwise, it considers it a number and subtracts it `2023 - 10 - 29 = 1984`
