### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0x98 in position 1158: illegal multibyte sequence

### ISSUE THREAD

**Issue by Pro1452** [ultralytics/ultralytics#6040]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Hello, I would like to modify the structure of the YOLOv8 model to enhance its ability to detect small objects. 
I need to use the testing code from the YOLOv8 code repository to validate whether the modified model is successful. 
However when I run the test_model_forward() function in ultralytics/tests/test_python.py to test the model, I encounter the following error. 
How can I resolve this problem?
I want to run YOLOv8 on my custom dataset and make corresponding modifications to it, So I would also like to ask, if I want to enhance the small object detection capability of the YOLOv8 model (for example, using yolov8n or yolov8s as baseline models to modify the existing structure.), where can I start?
Can I improve the model's ability to detect small objects by adding additional modules or using other methods to complement the YOLOv8 model? 
Thank you very much.

The steps to install and set up the use of the YOLOv8 code are as follows:
Download the Ultralytics repository as a compressed zip file from GitHub and extract it to the desired location.
Open the PyCharm IDE and click on the Terminal at the bottom.
In the Terminal, enter the following commands one by one:

1. cd ultralytics 
2. pip install -e .

Testing started at 12:59 ...
Launching pytest with arguments test_python.py::test_model_forward --no-header --no-summary -q in D:\ProgramFile\PythonFile\python310\PythonProject\ultralytics\tests

Traceback (most recent call last):
  File "D:\InstallSoftware\PyCharm Community Edition 2023.2\plugins\python-ce\helpers\pycharm\_jb_pytest_runner.py", line 60, in <module>
    sys.exit(pytest.main(args, plugins_to_load + [Plugin]))
  File "D:\InstallSoftware\anaconda3\envs\python310\lib\site-packages\_pytest\config\__init__.py", line 147, in main
    config = _prepareconfig(args, plugins)
  File "D:\InstallSoftware\anaconda3\envs\python310\lib\site-packages\_pytest\config\__init__.py", line 328, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "D:\InstallSoftware\anaconda3\envs\python310\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "D:\InstallSoftware\anaconda3\envs\python310\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "D:\InstallSoftware\anaconda3\envs\python310\lib\site-packages\pluggy\_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "D:\InstallSoftware\anaconda3\envs\python310\lib\site-packages\_pytest\helpconfig.py", line 103, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "D:\InstallSoftware\anaconda3\envs\python310\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "D:\InstallSoftware\anaconda3\envs\python310\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "D:\InstallSoftware\anaconda3\envs\python310\lib\site-packages\_pytest\config\__init__.py", line 1075, in pytest_cmdline_parse
    self.parse(args)
  File "D:\InstallSoftware\anaconda3\envs\python310\lib\site-packages\_pytest\config\__init__.py", line 1425, in parse
    self._preparse(args, addopts=addopts)
  File "D:\InstallSoftware\anaconda3\envs\python310\lib\site-packages\_pytest\config\__init__.py", line 1290, in _preparse
    self._initini(args)
  File "D:\InstallSoftware\anaconda3\envs\python310\lib\site-packages\_pytest\config\__init__.py", line 1166, in _initini
    rootpath, inipath, inicfg = determine_setup(
  File "D:\InstallSoftware\anaconda3\envs\python310\lib\site-packages\_pytest\config\findpaths.py", line 191, in determine_setup
    rootdir, inipath, inicfg = locate_config([ancestor])
  File "D:\InstallSoftware\anaconda3\envs\python310\lib\site-packages\_pytest\config\findpaths.py", line 113, in locate_config
    ini_config = load_config_dict_from_file(p)
  File "D:\InstallSoftware\anaconda3\envs\python310\lib\site-packages\_pytest\config\findpaths.py", line 57, in load_config_dict_from_file
    iniconfig = _parse_ini_config(filepath)
  File "D:\InstallSoftware\anaconda3\envs\python310\lib\site-packages\_pytest\config\findpaths.py", line 31, in _parse_ini_config
    return iniconfig.IniConfig(str(path))
  File "D:\InstallSoftware\anaconda3\envs\python310\lib\site-packages\iniconfig\__init__.py", line 54, in __init__
    tokens = self._parse(iter(f))
  File "D:\InstallSoftware\anaconda3\envs\python310\lib\site-packages\iniconfig\__init__.py", line 82, in _parse
    for lineno, line in enumerate(line_iter):
UnicodeDecodeError: 'gbk' codec can't decode byte 0x98 in position 1158: illegal multibyte sequence

Process finished with exit code 1

Empty suite

### Environment

OS：Windows 10 Professional Edition 64bit
anaconda virtual environment： python 3.10.13
compiler： PyCharm

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Pro1452 hello,

Thank you for reaching out about your YOLOv8 modifications. It's really impressive that you are pushing its boundaries.

The error you're encountering, `UnicodeDecodeError: 'gbk' codec can't decode byte 0x98 in position 1158: illegal multibyte sequence`, typically occurs when Python is trying to read a file with a character it can't interpret. This can be due to a variety of reasons like incompatible coding formats or special characters in the files. Since the issue is related to encoding, a common solution is to ensure that files are being read using utf-8 encoding, as it handles a wider range of characters than gbk.

About your question of enhancing the small object detection in the YOLOv8 model, you can try experimenting with different strategies including:

1. Modifying the architecture to focus on small object detection. For instance, introducing more layers that are specifically designed to pick up small features. 
2. Utilize data augmentation techniques oriented towards small object detection. Techniques like zooming in on smaller objects can often help in these cases.
3. Adjusting the loss function can also help guide the model to recognize smaller objects.

Remember that model performance on small objects also largely depends on your training data. If your dataset includes smaller objects and the model is trained adequately, the model's detection capabilities should improve. 

Hope this helps! Let us know if you have more questions. 

Best Regards

**Comment by Pro1452** [comment]
@glenn-jocher Hello! 
Thank you very much for the help and guidance you provided for my question!

Regarding the "UnicodeDecodeError: 'gbk' codec can't decode byte 0x98 in position 1158: illegal multibyte sequence" issue, I tried the following steps to resolve it:

1. Downloaded the ultralytics compressed file from GitHub and extracted it to the path "D:\ProgramFile\PythonFile\python310\PythonProject". Created a "test_model.py" file in that path.
2. Opened the PyCharm IDE, set up the Python virtual environment, and opened the Terminal. Executed the following commands one by one: 
   - cd ultralytics
   - pip install -e .
3. In the "test_model.py" file created in step 1, added the following code:

from ultralytics import YOLO
from ultralytics.utils import ASSETS

CFG = 'D:/ProgramFile/PythonFile/python310/PythonProject/ultralytics/ultralytics/cfg/models/v8/yolov8n_convnext.yaml'
SOURCE = ASSETS / 'bus.jpg'

def test_model_forward():
    """Test the forward pass of the YOLO model."""
    model = YOLO(CFG)
    model(source=None, imgsz=32, augment=True)  # also test no source and augment

test_model_forward()

I ran this Python script, and the output showed that the configuration was successful. The problem has been resolved!
![test](https://github.com/ultralytics/ultralytics/assets/113347537/7f772d84-ed1f-422e-b8a6-9e99f3308366)


The reason I encountered the error previously was that I directly ran the test_model_forward() function individually in the "test_model.py" file, which caused the program to throw an error.
As shown in the screenshot below, I clicked the green icon to run it directly in PyCharm.
![test1](https://github.com/ultralytics/ultralytics/assets/113347537/c1c97c9b-0e0d-4e03-9745-cc7455b670c0)

Thank you once again for your assistance and guidance in small object detection. I will follow the approaches you have provided and try different methods to improve the detection performance of the YOLOv8 model on my custom dataset. I truly appreciate your help and patient explanations.
Wishing you a joyful life and successful work. Thank you!

Best Regards

**Comment by glenn-jocher** [comment]
Hello @Pro1452,

I'm really pleased to hear that you have resolved the encoding issue you were facing with your setup! It's always gratifying to see diligent problem-solving and I commend you on your perseverance and successful troubleshooting of the test_model_forward() function.

I'm also glad to know that the advice provided on enhancing small object detection with YOLOv8 has been helpful. Your systematic approach to improving the model's performance by testing different modification strategies is commendable, and the community can benefit tremendously from such dedicated efforts.

I wish you the best with your experiments and look forward to any future contributions or insights you may share. Your reflections and feedback will undoubtedly enrich the YOLOv8 community.

Best regards in your ongoing development work and may your project continue to progress efficiently. If you have further questions or insights down the line, do not hesitate to reach out.

Thank you for your kind wishes. Enjoy your work and keep contributing to the field of AI!

Warm

**Comment by alpargun** [comment]
This is the 3rd "gbk codec" issue I have seen lately.

I suspect it is due to loading the weights .pkl file. Can you try loading in binary form?

with open(filename, 'rb') as f:
    datadict = pickle.load(f) 
Notice the 'rb' parameter to the open statement. An alternative can be setting the encoding as: encoding='utf-8'

**Comment by glenn-jocher** [comment]
@alpargun the `UnicodeDecodeError: 'gbk' codec can't decode byte 0x98 in position 1158: illegal multibyte sequence` error you're encountering is related to character encoding issues when reading a file. The `gbk` codec is being used, but it seems that the file contains characters that cannot be decoded with this codec.

To resolve this issue, you can try specifying the encoding when reading files. For example, if you're opening a file in Python, you can specify the encoding as `utf-8`, which is a more universal encoding that can handle a wider range of characters.

Here's how you can specify the encoding in Python:

```python
with open('your_file.txt', 'r', encoding='utf-8') as f:
    content = f.read()
```

Regarding enhancing the small object detection capability of the YOLOv8 model, here are a few strategies you can consider:

1. **Modify the Network Architecture**: You can experiment with adding additional layers or changing the structure of the network to improve its ability to detect small objects. This might involve adding more convolutional layers or using feature pyramid networks to better capture fine details.

2. **Data Augmentation**: Use data augmentation techniques that emphasize small objects, such as random cropping or zooming into images during training.

3. **Change Anchor Boxes**: Adjust the anchor box sizes to better match the size distribution of small objects in your dataset.

4. **Loss Function**: Modify the loss function to give more weight to small object detection errors during training.

5. **Use High-Resolution Input Images**: If possible, use higher-resolution input images so that small objects are better represented in the input data.

6. **Fine-Tuning**: If you're starting with a pre-trained model, fine-tune it on a dataset that contains a significant number of small objects.

7. **Ensemble Models**: Combine the outputs of multiple models, where some models are specifically trained to focus on small object detection.

8. **Attention Mechanisms**: Implement attention mechanisms that can help the model focus on relevant parts of the image, potentially improving small object detection.

Remember that modifying the model architecture and training process can be complex and may require a deep understanding of the YOLOv8 codebase and neural network design principles. Always start with a clear plan and hypothesis for your modifications, and be prepared to iterate on your approach based on validation results.

If you're willing to submit a PR to the Ultralytics YOLOv8 repo, make sure to thoroughly test your changes and follow the contribution guidelines provided by the repository maintainers.
