### ISSUE TITLE
How can I get map_small, map_medium, and map_large?

### ISSUE THREAD

**Issue by kazu-gra** [ultralytics/ultralytics#6043]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello.

In evaluation mode, I can get map(map50-95), map50, map75, maps, but I cannot get map_small, map_medium, map_large. How can I get map_small, map_medium, and map_large?

Also, when I evaluated best.py, I could confirm that there is a difference between the map obtained by model.val() and the map obtained by metrics, why is this?

**code**
```
from ultralytics import YOLO
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--pretrained', type=str, default='/usr/src/ultralytics/runs/detect/train11/weights/best.pt')
args = parser.parse_args()

pretrained = args.pretrained

model = YOLO(pretrained)  # load an official model

metrics = model.val()  # no arguments needed, dataset and settings remembered
print('map50-95')
print(metrics.box.map)
metrics.box.map    # map50-95
print('map50')
print(metrics.box.map50)
metrics.box.map50  # map50
print('map75')
print(metrics.box.map75)
metrics.box.map75  # map75
print('map_list')
print(metrics.box.maps)
metrics.box.maps   # a list contains map50-95 of each category
```

**result**
```
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
val: Scanning /usr/src/datasets/coco/labels/val2017.cache... 4952 images, 48 backgrounds, 0 corrupt: 100%|██████████| 5000/5000 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 313/313 [00:41<00:00,  7.58it/s]
                   all       5000      36335      0.639      0.472      0.519      0.368
                person       5000      10777      0.766      0.664      0.743      0.515
               bicycle       5000        314      0.692       0.36      0.443       0.25
・・・
            toothbrush       5000         57      0.379      0.182      0.201      0.134
Speed: 0.1ms preprocess, 2.0ms inference, 0.0ms loss, 0.8ms postprocess per image
Saving /usr/src/ultralytics/runs/detect/val4/predictions.json...

Evaluating pycocotools mAP using /usr/src/ultralytics/runs/detect/val4/predictions.json and /usr/src/datasets/coco/annotations/instances_val2017.json...
loading annotations into memory...
Done (t=0.47s)
creating index...
index created!
Loading and preparing results...
DONE (t=5.64s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=62.33s).
Accumulating evaluation results...
DONE (t=13.37s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.371
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.524
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.402
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.184
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.408
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.524
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.314
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.532
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.587
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.360
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.653
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.764
Results saved to /usr/src/ultralytics/runs/detect/val4
map50-95
0.3684841578686442
map50
0.5191600547516574
map75
0.40047745144250513
map_list
[    0.51503     0.25038     0.35887     0.42189     0.63465     0.61495     0.66279     0.31716     0.20857     0.21017     0.64403     0.61835     0.45078     0.20901     0.25843     0.66586     0.56222     0.53615     0.46079     0.46662     0.62008     0.68354     0.65488     0.67677    0.097263     0.36887
    0.080156     0.26724     0.32729     0.57817      0.1916     0.24711     0.33444     0.38087      0.2394     0.32721     0.44815     0.30488     0.38848     0.29799     0.27106     0.34833      0.2722     0.10901    0.090392     0.38694     0.20508     0.14507     0.33562     0.26903     0.20497     0.17066
      0.3325     0.50278     0.40352     0.32251     0.25389     0.42746     0.20141     0.42828     0.29922     0.61243     0.54912     0.57933     0.54294     0.17225     0.46831     0.27441     0.50636     0.36538     0.32085     0.35096     0.51711    0.095675     0.46031     0.31878     0.22482     0.42303
   0.0011747     0.13445]
```

### Additional

By the way, this is the model I learned yolov8n from scratch.

**Comment by glenn-jocher** [comment]
@kazu-gra the map_small, map_medium, and map_large are metrics that correspond to object detection performance for small, medium, and large objects respectively in the COCO test dataset. You can find these values in the log when evaluating the model, as they are printed out during evaluation along with other metrics. 

Regarding your second question on the difference in map obtained by model.val() and metrics, a possible reason could be the way you're using the metrics. In your code, you're calling model.val() which returns an evaluation of the model's performance. Then, you're printing 'metrics.box.map' which again calls the model to get the evaluation results. Ideally, you should just save what model.val() returns and reuse it, like this:

```python
results = model.val()
print(results.box.map)
print(results.box.map50)
print(results.box.map75)
print(results.box.maps)
```

In this example, results contains the map and other metrics, and you simply access the values without redoing the evaluations.

As for why the metrics might differ, the evaluations could be done on different validation batches, since the model re-evaluates each time you call the method. Alternatively, it could be due to differences in how evaluations are carried out if the code has changed between calls.

**Comment by kazu-gra** [comment]
Thank you for your answer.

**Regarding the first question**, is it the following outputs that are evaluated by COCOeval that can be checked in the logs?
Sorry if the indentation is difficult to see.
` 
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.371
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.524
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.402
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.184
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.408
Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.524
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.314
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.532
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.587
Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.360
Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.653
Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.764
`
If so, I would like to get this as a variable.

**My second question** is, do you mean that the values obtained by model.val() and result.box.map are different?

**Comment by glenn-jocher** [comment]
@kazu-gra thanks for clarifying your questions!

For your first question, yes, those are the outputs that are evaluated by COCOeval during the validation phase of training. If you want to access and store these values, they are available within the model object. You can retrieve the values as part of the results after validating the model and look into the metrics boxes, which basically contain the AP, AR values for various IoU thresholds and object sizes.

For your second question, what I meant was the values should be the same, because they're based on the same evaluation. The reason they may appear different is potentially due to repeating the evaluation or accessing the metrics at different stages within the model's validation phase. Ideally, you should save the returned values from the model.val() call to reuse, instead of calling model.val() multiple times, which triggers new evaluations with potentially varying results due to the randomness in data sampling.

**Comment by kazu-gra** [comment]
Thank you very much.

I would like to further investigate your two questions. I will be happy to answer any further questions you may have.

**Comment by glenn-jocher** [comment]
Sure, I'd be happy to help clarify your queries.

Firstly, the output metrics you're seeing in the logs such as "Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.371", and so on, are the evaluations calculated by the COCO evaluator during the validation phase, indeed. If you're interested in capturing these as variables, these values are stored in the results after the validation. You can access these metrics directly from the model's result object which contains Average Precision (AP) and Average Recall (AR) values for different Intersection over Union (IoU) thresholds and various object sizes.

Moving on to your second question, the results from the model's validation function in the form of "model.val()" and the map score accessed from "results.box.map" are ideally devised to be identical. They are based on the same underlying evaluation. If you observe a discrepancy, it could possibly be due to re-triggering the evaluation or calling these functions at different stages of validation. For consistency, you should save the result returned from the model's validation call and re-use these values, rather than re-running the validation function multiple times. 

I hope this brings more clarity to your questions. If you have further questions or if there's anything else you'd like to understand better, feel free to ask.

**Comment by AshishreddyM26** [comment]
@glenn-jocher 

I have afew questions, can you help solve them.

1. Do we only be able to get the evaluation metrics (mAP) for each category of small/medium/large objects when we are working with COCO dataset?
2. Can we get that (mAP for small/medium/large objects) when training the YOLO11 model, if yes can you provide some insights into it.

I tried [this](https://github.com/orgs/ultralytics/discussions/8153#discussioncomment-9172677), but I cannot see any attributes like aps, apm, or apl for 'Metric' or 'Metric.box' objects.

Is there a way for validation mAP for different objects (small/medium/large) from Ultralytics?

Thank you,
Ashish

**Comment by glenn-jocher** [comment]
@AshishreddyM26 great questions! Let me address each one:

1. The small/medium/large object mAP metrics are part of the COCO evaluation protocol, so they're available when validating on COCO or COCO-format datasets. They use COCO's object size definitions (small: area < 32², medium: 32² < area < 96², large: area > 96²).

2. Yes, you can get these metrics when training YOLO11 on COCO - they appear in the validation logs during training as shown in the original issue.

3. The reason you can't find `aps`, `apm`, `apl` attributes is because these aren't directly exposed on the Metric class. They're calculated by the COCO evaluator and printed to logs, but not stored as accessible attributes.

Currently, there isn't a built-in way to programmatically access these size-specific metrics from the `results` object. You'd need to parse them from the validation output logs or implement custom evaluation logic using the COCO API directly. This could be a useful feature request for future versions to expose these metrics as accessible attributes.

**Comment by ashish-reddy26** [comment]
Thanks for the clear explanation, [Glenn](@glenn-jocher )—really helpful!

* If I need the numbers inside Python I have two options  
  1. parse the validation log, or  
  2. run a standalone COCO‐API eval with custom `areaRng`.

For my immediate work I’ll parse the logs, but I agree it would be great if these fields were exposed directly from `results` object, when working with Ultralytics.

Thanks again for your time!

Ashish

**Comment by glenn-jocher** [comment]
@AshishreddyM26 you're welcome! Your approach is spot on - parsing the validation logs is definitely the most practical solution for immediate needs. 

Your suggestion about exposing these size-specific metrics directly from the `results` object is excellent and would be a valuable addition to the API. Feel free to open a feature request for this if you'd like to see it implemented in future releases.

Good luck with your project!

**Comment by ashish-reddy26** [comment]
Thanks again, Glenn! I’ll go ahead and open a feature request to help track size-specific metrics directly from the `results` object.

If there are any preferences or design guidelines you'd like me to follow (e.g., how to structure it within the Results class or any related tests), I’d be happy to align with them.

Appreciate the support—and excited to contribute where I can!

**Comment by glenn-jocher** [comment]
@AshishreddyM26 that sounds great! For the feature request design, I'd suggest:

- Add `map_small`, `map_medium`, `map_large` properties to the `Metric` class alongside the existing `map`, `map50`, `map75` properties
- These would be populated during COCO evaluation when available, otherwise return `None` or `0.0` for non-COCO datasets
- Follow the same pattern as existing metrics in the [Metric class](https://docs.ultralytics.com/reference/utils/metrics/#ultralytics.utils.metrics.Metric) for consistency

The implementation would likely involve capturing the COCO evaluator's `stats` array which contains these values and exposing them through the metrics interface. Thanks for taking the initiative on this - it would be a valuable addition for users working with COCO datasets!

**Comment by ashish-reddy26** [comment]
Thanks for the detailed guidance, @glenn-jocher !

I’ve opened the feature request here: [#20974](https://github.com/ultralytics/ultralytics/issues/20974), and followed your suggestions in the implementation. The new `map_small`, `map_medium`, and `map_large` properties are added to the `Metric` class, and are set from the COCO evaluator’s stats array. These would only populate for COCO and `0.0`  for non-COCO datasets. These metrics can be accessed through `Metric.box.map_small`/`medium`/`large`.

I’ve tested the changes locally and everything seems to be working as expected. I’ll go ahead and open a PR shortly—looking forward to any feedback you may have!

Thanks again for the support!

**Comment by glenn-jocher** [comment]
@AshishreddyM26 excellent work! I just reviewed your feature request #20974 and the approach looks solid. The implementation plan to add `map_small`, `map_medium`, and `map_large` properties to the Metric class following the existing pattern is exactly right.

When you submit the PR, make sure to include tests for both COCO and non-COCO scenarios to ensure the metrics populate correctly when available and default appropriately otherwise. Looking forward to reviewing your contribution!
