### ISSUE TITLE
how to run Inference on GPU from python code?

### ISSUE THREAD

**Issue by MasIgor** [ultralytics/ultralytics#6044]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi all!

How can I define the device i want to run the inference on? as far as I understood from the docu it should be like this:

    results = model.predict(im0s, device='cpu', max_det=2, verbose=False)

or

    results = model.predict(im0s, device=0, max_det=2, verbose=False)

but the problem I am facing is that gpu and CPU take exactly the same amount of time (140 ms) and i am expecting the GPU to be much faster. Is there a way to verify on what device it actually run?

thank you

**Comment by RizwanMunawar** [comment]
Thank you, @MasIgor, for sharing this information. When running inference on an image, it's worth noting that both the GPU and CPU may take a similar amount of time. This is because the GPU needs some initial time to load the necessary modules in the first frame.

However, if you are working with a video file, it's possible that PyTorch might not be configured for GPU processing. To enable GPU support for PyTorch, you can refer to the documentation at: https://pytorch.org/get-started/locally/

Hope this helps! Let me know if you have any additional questions.
Thanks
