### ISSUE TITLE
Model.tune() error: [Errno 2] No such file or directory: 'yolo'

### ISSUE THREAD

**Issue by asnyder613** [ultralytics/ultralytics#6053]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am attempting to tune a Yolov8 model in a Jupityr notebook & keep getting a recurring error: 

`[Errno 2] No such file or directory: 'yolo'
`
I've loaded my previously trained model:
```
model = YOLO('yolov8x')
model = YOLO('yolov8x').load('/train8/weights/best.pt')
```

Then called the .tune() method:
```
model.tune(data="datasets/caltechpedestriandataset.yaml", 
           epochs=50, iterations=300, optimizer='AdamW', plots=False, save=False, val=False)
```

Then get this error:
```
Tuner: Initialized Tuner instance with 'tune_dir=runs/detect/tune4'
Tuner: 💡 Learn about tuning at https://docs.ultralytics.com/guides/hyperparameter-tuning
Tuner: Starting iteration 1/300 with hyperparameters: {'lr0': 0.01, 'lrf': 0.01, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'box': 7.5, 'cls': 0.5, 'dfl': 1.5, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.5, 'mosaic': 1.0, 'mixup': 0.0, 'copy_paste': 0.0}
WARNING ❌️ training failure for hyperparameter tuning iteration 1
[Errno 2] No such file or directory: 'yolo'
Saved runs/detect/tune4/tune_scatter_plots.png
Saved runs/detect/tune4/tune_fitness.png

Tuner: 1/300 iterations complete ✅ (2.26s)
Tuner: Results saved to runs/detect/tune4
Tuner: Best fitness=0.0 observed at iteration 1
Tuner: Best fitness metrics are {}
Tuner: Best fitness model is runs/detect/train7
Tuner: Best fitness hyperparameters are printed below.

Printing 'runs/detect/tune4/best_hyperparameters.yaml'

lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
box: 7.5
cls: 0.5
dfl: 1.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 1.0
mixup: 0.0
copy_paste: 0.0

Tuner: Starting iteration 2/300 with hyperparameters: {'lr0': 0.01081, 'lrf': 0.01003, 'momentum': 0.90269, 'weight_decay': 0.00052, 'warmup_epochs': 2.50958, 'warmup_momentum': 0.70061, 'box': 6.67479, 'cls': 0.5093, 'dfl': 1.35459, 'hsv_h': 0.01705, 'hsv_s': 0.55047, 'hsv_v': 0.38581, 'degrees': 0.0, 'translate': 0.09122, 'scale': 0.54228, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.50615, 'mosaic': 1.0, 'mixup': 0.0, 'copy_paste': 0.0}
WARNING ❌️ training failure for hyperparameter tuning iteration 2
[Errno 2] No such file or directory: 'yolo'
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
Cell In[5], line 1
----> 1 model.tune(data="/datasets/caltechpedestriandataset.yaml", 
      2            epochs=50, iterations=300, optimizer='AdamW', plots=False, save=False, val=False)

File ~/.local/lib/python3.10/site-packages/ultralytics/engine/model.py:366, in Model.tune(self, use_ray, iterations, *args, **kwargs)
    364 custom = {}  # method defaults
    365 args = {**self.overrides, **custom, **kwargs, 'mode': 'train'}  # highest priority args on the right
--> 366 return Tuner(args=args, _callbacks=self.callbacks)(model=self, iterations=iterations)

File ~/.local/lib/python3.10/site-packages/ultralytics/engine/tuner.py:207, in Tuner.__call__(self, model, iterations, cleanup)
    205         shutil.copy2(ckpt, self.tune_dir / 'weights')
    206 elif cleanup:
--> 207     shutil.rmtree(ckpt_file.parent)  # remove iteration weights/ dir to reduce storage space
    209 # Plot tune results
    210 plot_tune_results(self.tune_csv)

UnboundLocalError: local variable 'ckpt_file' referenced before assignment

```

I'm not sure where the yolo directory should be (is this something that should be created by the initial model instance? is it something I need to create?) nor where/what the ckpt_file variable is? 

Any advice appreciated!

**Comment by glenn-jocher** [comment]
@asnyder613 it appears that your code is unable to find the required 'yolo' directory. This is often due to specifying an incorrect or relative path that doesn't exist in your current working directory. 

Make sure that the 'yolo' directory exists in the correct location and you have the necessary read/write permissions for that directory. The issue may also be related to the location of the 'best.pt' file. Ensure the file exists in the expected location.

Regarding the `ckpt_file` variable, this appears to be a variable used to reference a file in your code. The 'UnboundLocalError' you are seeing indicates that the variable may have been referenced before it was assigned a value. Make sure you assign a value to `ckpt_file` before using it.

Originally, the model instance should not create the `yolo` directory, you need to create and manage it yourself, passing the appropriate directory structure reference to the function.

Please consider these suggestions and revise your code accordingly. If your issue persists, feel free to ask further questions.

**Comment by asnyder613** [comment]
Should the 'yolo' directory contain the best.pt file? I'm not sure what the directory structure should be here... or what the code is expecting to find in the 'yolo' directory.

My code itself isn't using `ckpt_file`--that seems to be something within the `tune() `method? Any idea what should even be assigned to that?

**Comment by glenn-jocher** [comment]
@asnyder613 yes, the 'yolo' directory should contain the 'best.pt' file. This file is the saved trained model that the YOLOv8 algorithms use to perform object detection on new data. The directory structure should look something like this:

```
/your_project_directory
   /yolo
      best.pt
```
In this case, the 'yolo' directory is inside your main project directory. 

Regarding `ckpt_file`, it is indeed a variable used inside the `tune()` method of the code. Normally, it is supposed to hold the path to the 'checkpoint' file which is a file to which the state of your model is saved. So if your training gets interrupted for any reason, you can resume from where you left off. 

In general, you don't need to assign `ckpt_file` yourself in your code, it should be handled within the `tune()` method. If you are facing issues related to this, there might be some error or misconfiguration within the function call or the package you are using. Please try checking the official documentation or raise an issue with the specific error logged in the package’s repository for further assistance.

**Comment by asnyder613** [comment]
I put the 'best.pt' file inside a 'yolo' directory and am getting the same error as before... it doesn't seem to make any difference.

**Comment by nicosoethe** [comment]
maybe I can help you. The problem comes from this part of code 
```
cmd = ['yolo', 'train', *(f'{k}={v}' for k, v in train_args.items())]
assert subprocess.run(cmd, check=True).returncode == 0, 'training failed'
```
where the second line is creating a new process with the arguments given in `cmd`. So it's calling `yolo` which needs to be installed correctly. You can check this by just typing `yolo` in your shell. I assume, the command will not be found. So you have to reinstall the ultralytics package via `pip install ultralytics` and it should work. I am running now in another error, but maybe you have more luck.

**Comment by glenn-jocher** [comment]
@nicosoethe, appreciate your efforts to find a solution. The issue you pointed out is related to the subprocess call in:

``` 
cmd = ['yolo', 'train', *(f'{k}={v}' for k, v in train_args.items())]
assert subprocess.run(cmd, check=True).returncode == 0, 'training failed'
```

In this line, a new process is being created with the parameters defined in the 'cmd' command. This subsequently calls 'yolo', which needs to be correctly installed in the environment for this call to be successful.

If you enter 'yolo' in your terminal and receive a command not found error, it indicates that there may be issues with the installation of the ultralytics package. Uninstalling the current ultralytics package with `pip uninstall ultralytics` and reinstalling it with `pip install ultralytics` might rectify this issue.

There are multiple factors which could lead to process creations failing, such as incorrect package installation, permissions issues, or other environmental factors.

However, keep in mind that dealing with subprocess can be tricky. The problem may reside in the code line mentioned above, but the root cause could be elsewhere.

If reinstalling the package doesn't resolve the issue, it would be beneficial to check the environment setup, Python version, and PyTorch installation.

By sharing more about your specific setup, operating system and error details, we might be able to provide more tailored advice. Wishing you the best of luck in resolving the issue!

**Comment by asnyder613** [comment]
I uninstalled & reinstalled ultralytics & got this warning:
```
Installing collected packages: ultralytics
  WARNING: The scripts ultralytics and yolo are installed in '/home/syc6vs/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed ultralytics-8.0.205
```
I'm not sure if that affects anything or not, but otherwise getting the same errors. 

I'm using a jupityr notebook...and not sure what other setup/OS/error details to share to help troubleshoot.... but happy to share whatever would be useful... if I even know. I'm still new-ish and learning a lot of this stuff. 

Thank you all for your attempts to help!

**Comment by nicosoethe** [comment]
> I uninstalled & reinstalled ultralytics & got this warning:
> 
> ```
> Installing collected packages: ultralytics
>   WARNING: The scripts ultralytics and yolo are installed in '/home/syc6vs/.local/bin' which is not on PATH.
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
> Successfully installed ultralytics-8.0.205
> ```
> 
> I'm not sure if that affects anything or not, but otherwise getting the same errors.
> 
> I'm using a jupityr notebook...and not sure what other setup/OS/error details to share to help troubleshoot.... but happy to share whatever would be useful... if I even know. I'm still new-ish and learning a lot of this stuff.
> 
> Thank you all for your attempts to help!

When you type `yolo` in your shell and the cmd is not found, 'yolo' is missing on PATH. After you added it, it should work.

**Comment by asnyder613** [comment]
How do I add it to path? Nothing I've tried (several different stackexchange answers) seems to work...

**Comment by nicosoethe** [comment]
On my system it was added automatically to PATH. Did you installed the package with `--user` flag? Are you on linux?

**Comment by asnyder613** [comment]
I did not use any kind of user tag, just `pip install ultralytics` in the jupityr terminal. 

My computer is MacOS, but this is being run on my university's Rivanna server, which is...maybe linux? Not sure. All I really know is that I request cores/GPU/time on a jupityr session & go from there. 

I'm running the jupityr notebook on a Tensorflow 2.13.0 kernel...

**Comment by asnyder613** [comment]
After uninstall/reinstall of ultralytics, when I type 'yolo' into the terminal, this is what I get:
```
bash-4.2$yolo
Traceback (most recent call last):
  File "/home/syc6vs/.local/bin/yolo", line 5, in <module>
    from ultralytics.cfg import entrypoint
  File "/home/syc6vs/.local/lib/python3.8/site-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO
  File "/home/syc6vs/.local/lib/python3.8/site-packages/ultralytics/models/__init__.py", line 3, in <module>
    from .rtdetr import RTDETR
  File "/home/syc6vs/.local/lib/python3.8/site-packages/ultralytics/models/rtdetr/__init__.py", line 3, in <module>
    from .model import RTDETR
  File "/home/syc6vs/.local/lib/python3.8/site-packages/ultralytics/models/rtdetr/model.py", line 10, in <module>
    from ultralytics.engine.model import Model
  File "/home/syc6vs/.local/lib/python3.8/site-packages/ultralytics/engine/model.py", line 8, in <module>
    from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
  File "/home/syc6vs/.local/lib/python3.8/site-packages/ultralytics/cfg/__init__.py", line 10, in <module>
    from ultralytics.utils import (ASSETS, DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, RANK, ROOT, RUNS_DIR,
  File "/home/syc6vs/.local/lib/python3.8/site-packages/ultralytics/utils/__init__.py", line 21, in <module>
    import torch
  File "/home/syc6vs/.local/lib/python3.8/site-packages/torch/__init__.py", line 1429, in <module>
    from torch import optim as optim
  File "/home/syc6vs/.local/lib/python3.8/site-packages/torch/optim/__init__.py", line 8, in <module>
    from .adadelta import Adadelta
  File "/home/syc6vs/.local/lib/python3.8/site-packages/torch/optim/adadelta.py", line 4, in <module>
    from .optimizer import (Optimizer, _use_grad_for_differentiable, _default_to_fused_or_foreach,
  File "/home/syc6vs/.local/lib/python3.8/site-packages/torch/optim/optimizer.py", line 23, in <module>
    from typing_extensions import ParamSpec, Self, TypeAlias
ImportError: cannot import name 'ParamSpec' from 'typing_extensions' (/apps/software/standard/compiler/gcc/9.2.0/jupyter_conda/2020.11-py3.8/lib/python3.8/site-packages/typing_extensions.py)
```

**Comment by nicosoethe** [comment]
> After uninstall/reinstall of ultralytics, when I type 'yolo' into the terminal, this is what I get:
> 
> ```
> bash-4.2$yolo
> Traceback (most recent call last):
>   File "/home/syc6vs/.local/bin/yolo", line 5, in <module>
>     from ultralytics.cfg import entrypoint
>   File "/home/syc6vs/.local/lib/python3.8/site-packages/ultralytics/__init__.py", line 5, in <module>
>     from ultralytics.models import RTDETR, SAM, YOLO
>   File "/home/syc6vs/.local/lib/python3.8/site-packages/ultralytics/models/__init__.py", line 3, in <module>
>     from .rtdetr import RTDETR
>   File "/home/syc6vs/.local/lib/python3.8/site-packages/ultralytics/models/rtdetr/__init__.py", line 3, in <module>
>     from .model import RTDETR
>   File "/home/syc6vs/.local/lib/python3.8/site-packages/ultralytics/models/rtdetr/model.py", line 10, in <module>
>     from ultralytics.engine.model import Model
>   File "/home/syc6vs/.local/lib/python3.8/site-packages/ultralytics/engine/model.py", line 8, in <module>
>     from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
>   File "/home/syc6vs/.local/lib/python3.8/site-packages/ultralytics/cfg/__init__.py", line 10, in <module>
>     from ultralytics.utils import (ASSETS, DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, RANK, ROOT, RUNS_DIR,
>   File "/home/syc6vs/.local/lib/python3.8/site-packages/ultralytics/utils/__init__.py", line 21, in <module>
>     import torch
>   File "/home/syc6vs/.local/lib/python3.8/site-packages/torch/__init__.py", line 1429, in <module>
>     from torch import optim as optim
>   File "/home/syc6vs/.local/lib/python3.8/site-packages/torch/optim/__init__.py", line 8, in <module>
>     from .adadelta import Adadelta
>   File "/home/syc6vs/.local/lib/python3.8/site-packages/torch/optim/adadelta.py", line 4, in <module>
>     from .optimizer import (Optimizer, _use_grad_for_differentiable, _default_to_fused_or_foreach,
>   File "/home/syc6vs/.local/lib/python3.8/site-packages/torch/optim/optimizer.py", line 23, in <module>
>     from typing_extensions import ParamSpec, Self, TypeAlias
> ImportError: cannot import name 'ParamSpec' from 'typing_extensions' (/apps/software/standard/compiler/gcc/9.2.0/jupyter_conda/2020.11-py3.8/lib/python3.8/site-packages/typing_extensions.py)
> ```

Have you already installed the dependencies with `pip install -r requirements.txt` in the ultralytics folder? That might help. If not, try to reinstall typing_extensions with pip.

**Comment by glenn-jocher** [comment]
@asnyder613 thanks for reaching out with the traceback details. It's important to handle dependencies properly here.

From the traceback, it seems that 'typing_extensions', a Python module which provides additional type hints, is not being able to import the name 'ParamSpec'. 

Potential ways to resolve this issue include updating the 'typing_extensions' module, or ensuring all modules are installed with exact versions as specified in the 'requirements.txt' file of YOLOv8 repo to avoid potential conflicts.

If neither solution resolves your issue, it might be helpful to check the Python version. The software you are using seems to be compatible with Python 3.8.

Please ensure all your Python packages are updated including 'torch' and 'typing_extensions', and are compatible with the version you are using. It might be beneficial to create a new Python virtual environment, ensuring a clean workspace as well.

Don't hesitate to reach out if the issue persists after trying these suggestions.

**Comment by asnyder613** [comment]
I think I may be out of luck, guys. 
I've tried creating an env, but the read/write limitations on rivanna just keep giving me one error after another... 
Now I can't even get keras to load properly... and yolo still is un-findable. SMH.
Thanks for all the help.

**Comment by asnyder613** [comment]
I don't have the processing power locally to do the level of training/testing that I'd like to for this project, but as an update, I did attempt to run the .tune() method locally, and it seems to work just fine... so it does seem to be some kind of package/permissions error with my school's rivanna platform/server.

Thanks again for all the attempts to help!

**Comment by glenn-jocher** [comment]
@asnyder613 i'm glad to hear that you found some success in running the `.tune()` method locally, though I understand the limitations you are experiencing regarding processing power on your local machine. 

As for the issues you're encountering with your school's Rivanna platform, you're most likely right that it's related to package and permissions. It's also possible that certain library versions installed on the server are conflicting with what YOLOv8 requires.

Under server environments, it could be beneficial to utilize virtual environments or containers. However, since as you mentioned, there are read/write restrictions on Rivanna platform, setting up an environment can be challenging. 

I would recommend reaching out to the administrator of the Rivanna platform or use their dedicated support to help find a solution. It's in their hands to adjust the permissions or potentially install any necessary packages for you. 

I'm sorry for the difficulties you have encountered. Feel free to reach back with any future questions or issues you come across. I hope you'll be able to run your projects effectively soon. Best of luck!

**Comment by ferotek** [comment]
Hi, 
I am getting the same error as the OP. I've done exactly as she did. 
`model = YOLO('yolov8s.pt').load('yolo/best.pt')
model.tune(data="data.yaml", 
           epochs=30, iterations=300, optimizer='AdamW', plots=False, save=False, val=False)` 
`Tuner: Starting iteration 2/300 with hyperparameters: {'lr0': 0.01001, 'lrf': 0.01088, 'momentum': 0.98, 'weight_decay': 0.00044, 'warmup_epochs': 3.91277, 'warmup_momentum': 0.56441, 'box': 6.56692, 'cls': 0.55443, 'dfl': 1.92549, 'hsv_h': 0.01526, 'hsv_s': 0.88195, 'hsv_v': 0.3873, 'degrees': 0.0, 'translate': 0.07446, 'scale': 0.47911, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.0, 'fliplr': 0.47429, 'mosaic': 0.80073, 'mixup': 0.0, 'copy_paste': 0.0}
WARNING ❌️ training failure for hyperparameter tuning iteration 2
[Errno 2] No such file or directory: 'yolo'
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
/var/tmp/ipykernel_15117/1058099140.py in <cell line: 1>()
----> 1 model.tune(data="odm_rec.yaml", 
      2            epochs=50, iterations=300, optimizer='AdamW', plots=False, save=False, val=False)

/opt/conda/envs/ptod/lib/python3.8/site-packages/ultralytics/engine/model.py in tune(self, use_ray, iterations, *args, **kwargs)
    361         else:
    362             from .tuner import Tuner
--> 363 
    364             custom = {}  # method defaults
    365             args = {**self.overrides, **custom, **kwargs, 'mode': 'train'}  # highest priority args on the right

/opt/conda/envs/ptod/lib/python3.8/site-packages/ultralytics/engine/tuner.py in __call__(self, model, iterations, cleanup)
    205                     shutil.copy2(ckpt, self.tune_dir / 'weights')
    206             elif cleanup:
--> 207                 shutil.rmtree(ckpt_file.parent)  # remove iteration weights/ dir to reduce storage space
    208 
    209             # Plot tune results

UnboundLocalError: local variable 'ckpt_file' referenced before assignment`

However, the platform I'm using is different. I'm using a jupyter notebook on a GCP instance. I also was able to install Ultralytics without any warnings and run yolo in the shell without errors.

**Comment by glenn-jocher** [comment]
@ferotek hi there,

The error you're encountering indicates a problem during the hyperparameter tuning process, specifically related to file handling. The `No such file or directory: 'yolo'` message is a bit misleading as it's a result of a failed training attempt, not necessarily the root cause. The `UnboundLocalError` suggests that the `ckpt_file` variable within the `.tune()` method is being referenced before it has been assigned a value, which typically means that an earlier step in the process has failed.

The fact that you can train the model without any issues but `.tune()` fails suggests that the tuning process couldn't properly handle the files or directories it was trying to access or create.

Here are some steps that could potentially resolve your issue:

1. Make sure the data file `data.yaml` is correctly formatted and all paths within it are correct and accessible within your GCP instance environment.
2. Ensure the correct best model weights file is specified and exists at `'yolo/best.pt'`. Verify the path is relative to the working directory of the Jupyter notebook.
3. Double-check the current working directory in your Jupyter Notebook using `os.getcwd()` and confirm the paths to the data and weight files are correct relative to this directory.
4. Try to avoid having the model weights in a folder named 'yolo', as this could potentially conflict with the command aliases or internal configurations. Use a different folder name to store your weights and specify that in your code.
5. It looks like you're trying to load a pre-trained model with `YOLO('yolov8s.pt')` which may not be necessary if you're loading weights from 'best.pt'. Loading the 'best.pt' directly should suffice.
6. Lastly, if none of these steps help, there might be an issue with the permission settings on your GCP instance, or potentially with the Ultralytics package installation itself.

To avoid any confusing use of a folder structured as 'yolo', you could directly specify the path and file like so for loading and tuning, assuming your weight file is at the root of your working directory:

```python
model = YOLO('best.pt').load()
model.tune(data="data.yaml", 
           epochs=30, iterations=300, optimizer='AdamW', plots=False, save=False, val=False)
```

Remember to have all the paths structured relative to the notebook's working directory or use absolute paths to avoid such errors.

If after trying out these steps the problem persists, consider reviewing any updates or issues reported in the Ultralytics repository, or reaching out to the Ultralytics support with the details of your environment and error logs for further assistance.

**Comment by ferotek** [comment]
Hi, @glenn-jocher 
Thanks for the response. I've tried all the steps and I'm still getting the same problem. I'm not sure what the issue is.

**Comment by glenn-jocher** [comment]
Hi @ferotek,

I'm sorry to hear that you're still encountering issues. If the basic troubleshooting steps have not resolved the problem, this could indicate a deeper issue within the environment or the Ultralytics package.

Since you've confirmed that the issue persists despite following the recommended steps:

1. **Verify the environment**: Make sure all dependencies required by YOLOv8 are installed correctly. Since your error isn't indicating a missing module and you've said that normal training works, it's less likely that this is the issue, but conflicts within dependencies can sometimes cause unexpected behaviors.

2. **Permissions**: Even though it's not a typical error message for a permissions issue, verify that your user has the necessary read/write permissions for all involved directories.

3. **Package Integrity**: You may consider reinstalling the ultralytics package to ensure that all components are intact. 

   ```
   pip uninstall ultralytics
   pip install ultralytics
   ```
   
   Check to make sure the installation proceeds without errors.

4. **Validation of model path**: Ensure the referenced weights path in the model load function is correct. If 'best.pt' is in the working directory, then just use `YOLO('best.pt')`.

5. **Code workflow**: The actual code snippet should look like this (assuming 'best.pt' is the correct weights file and 'data.yaml' is properly set):

    ```python
    model = YOLO('best.pt').load()
    model.tune(data="data.yaml", 
               epochs=30, iterations=300, optimizer='AdamW', plots=False, save=False, val=False)
    ```

6. **Review directory structure**: Make sure that the directory where the `.tune()` method tries to save the tuning data does not get deleted or is accessible whilst the process is still running. The interruption in file handling could result in the `UnboundLocalError`.

7. **Logs and Error Reporting**: Since you're unsure after all these steps, I would recommend to carefully study the logs around the time the error occurs for any clues. If there's still no resolution, reporting this issue in detail to the Ultralytics team through the GitHub issues including the full stack trace, the steps you've taken to resolve it, and details about your environment (OS, Python version, library versions, etc.) could give the developers the information they need to help identify the root cause of the problem.

I'm sorry not to have a clear-cut solution right away; such errors can sometimes be environment-specific and difficult to diagnose without hands-on access. A detailed issue report to the Ultralytics support might be your best next step.  They may be able to provide more guidance or update the repository if a bug is identified. 

Best of luck in resolving this issue!

**Comment by ferotek** [comment]
After reinstalling the package, running the code from a Jupyter notebook still doesn't work, but I could run tune on a Python script from the command line. Thanks for the help and have a good Thanksgiving!

**Comment by glenn-jocher** [comment]
@ferotek, I'm glad to hear running the tune from a Python script through the command line worked for you! It seems like there might have been some environmental context within Jupyter that was causing the issue, which the script executed in the command line environment didn't encounter. 

Complex behaviors like this can sometimes be due to the way Jupyter notebooks handle paths, environments, or how they launch child processes. Running scripts directly in the command line is often a good way to bypass these complications.

Thank you for your wishes; I hope you have a wonderful Thanksgiving as well! 🦃 If you encounter any further issues or have more questions down the line, don't hesitate to reach out. We're here to help. Enjoy your holiday!

**Comment by OleksiiZaitsev** [comment]
**UnboundLocalError: local variable 'ckpt_file' referenced before assignment**  

Hello everyone,

I wanted to share a solution to a common problem that might occur when using the Ultralytics YOLO module in an Anaconda environment. This issue is particularly relevant if you are trying to run processes like model.tune which internally initiate subprocesses.

**Problem:**
When invoking methods that start subprocesses (such as hyperparameter tuning in Ultralytics YOLO), the subprocess may fail to find the necessary YOLO command if it's only installed in the current Anaconda environment and not in the base environment. This leads to errors because the subprocess attempts to execute commands from the base environment.

**Symptoms:**
You might encounter errors indicating that certain files or commands cannot be found, even though everything seems to be set up correctly in your current environment.

**Solution:**
To resolve this issue, make sure that the Ultralytics YOLO package is installed in the base environment of Anaconda (pip install ultralytics), not just in the current or active environment. This ensures that any subprocess initiated by the package can access the necessary commands and files.

**Comment by glenn-jocher** [comment]
@OleksiiZaitsev hey everyone! 👋

Just dropping in to share a quick tip that might save the day for those of you experiencing the `UnboundLocalError: local variable 'ckpt_file' referenced before assignment` issue or similar, especially when running processes like `model.tune()` in an Anaconda setup.

**Here's the gist:** Subprocesses launched by Ultralytics YOLO might be looking for the YOLO command in the base Anaconda environment rather than your current one. If it's not found there, boom - you run into errors.

**Quick Fix:** Ensure the Ultralytics YOLO package is installed in your Anaconda base environment with:
```sh
pip install ultralytics
```
This small step should help those subprocesses find their way, letting you run your tuning and other operations smoothly. 😉

Hope this helps and makes your interaction with Ultralytics YOLO a bit smoother! Happy coding! 🚀

**Comment by duartebranco01** [comment]
I was trying to run Model.tune in Windows 10 Command Line and on VS Code Terminal, and was having a similar problem where "[WinError 2] The system cannot find the file specified" happened.

As mentioned by @OleksiiZaitsev the problem was that the "yolo" command wasn't recognized in the Command Line. To check if this is the case, type "yolo" in the Command line.

This command is called in this line "return_code = subprocess.run(cmd, check=True).returncode" in the __call__ method of the Tuner class, called by the Model.tune when use_ray=False.

Since I wasn't using Anaconda to fix this I had to add the Python\Scripts folder to the Path system environment variables. In my case, this folder was here:
C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9.....\LocalCache\local-packages\Python39\Scripts 
After this open the Command Line and type "yolo" and the command should be recognized (you may need to restart your PC or IDE).

**Comment by caixiao233** [comment]
I also encountered the same error on AutoDL, but hadn't on my personal PC (ran tune.py directly on PyCharm) and found that it didn't report that error when I ran it from the command line,  I am not sure what the problem is, but it did avoid it  :D

**Comment by glenn-jocher** [comment]
@caixiao233 hey there! 😊

Glad to hear you managed to avoid the error while running directly from the command line! It sounds like the issue might be related to the environment setup in AutoDL. Sometimes, certain environments might not have the necessary path configurations which allow the system to recognize commands like `yolo`.

If you encounter this issue again or need to run it on AutoDL, ensure that the path to the Python `Scripts` directory (where the `yolo` command resides) is added to the PATH environment variable. This could be similar to what you might have set up on your personal PC.

Here’s a quick way to temporarily add a path in a Python script for a session:
```python
import sys
sys.path.append('path_to_yolo_command')
```

Just replace `'path_to_yolo_command'` with the actual path where the command exists. For a more permanent solution, adjusting the PATH environment variable directly in the system settings or the AutoDL setup would be ideal.

Hopefully, this helps! Let me know if you have more questions or need further assistance! 🚀

**Comment by Love-syntacticSugar** [comment]
> maybe I can help you. The problem comes from this part of code
> 
> ```
> cmd = ['yolo', 'train', *(f'{k}={v}' for k, v in train_args.items())]
> assert subprocess.run(cmd, check=True).returncode == 0, 'training failed'
> ```
> 
> where the second line is creating a new process with the arguments given in `cmd`. So it's calling `yolo` which needs to be installed correctly. You can check this by just typing `yolo` in your shell. I assume, the command will not be found. So you have to reinstall the ultralytics package via `pip uninstall ultralytics` and `pip install ultralytics` and it should work. I am running now in another error, but maybe you have more luck.

@nicosoethe Hello，Where does this code appear? I can't find it.I want to see the whole code.

**Comment by glenn-jocher** [comment]
It seems like the issue might be related to how the `yolo` command is accessed within your container environment. Since you've verified that the command is recognized in your shell, the problem might arise from subprocess calls within the tuning operation not inheriting the correct environment path.

A potential workaround is to ensure that your environment path includes the directory where the `yolo` script resides. You can try explicitly setting the PATH in your script before calling `model.tune()`. Alternatively, running your script directly from the command line instead of through a containerized environment might help, as you've done successfully on your local machine. If these don't resolve the issue, you may need to investigate further into how the container or virtual environment is set up to ensure it mirrors the working configuration on your local setup.

**Comment by myjc1** [comment]
Hello, i am writing as i have a similar issue but have unfortunately not found a solution reading through this thread.  But Idon't know how to solve it, Have you solved this problem?

**Comment by glenn-jocher** [comment]
Thank you for reaching out. This appears to be an environment-related issue where the `yolo` command isn't properly accessible by subprocesses. Please ensure that the `ultralytics` package is installed system-wide or in the same environment, and verify that the Python Scripts directory (where the `yolo` command resides) is included in your system's PATH. Let us know if the issue persists after verifying these steps.
