### ISSUE TITLE
Retrain my model issue

### ISSUE THREAD

**Issue by dennisans2** [ultralytics/ultralytics#6055]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

So I got a custom Yolov8 model after training. And soon I decided to retrain my model to strengthen it. So i tried this code:

```
!pip install PyYAML
import yaml

!yolo task=detect mode=train resume model=/content/models.pt data={dataset.location}/data.yaml epochs=30 imgsz=320 plots=True
```

But every time I run it, it encounters error that says 

```
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/cfg/__init__.py", line 380, in entrypoint
    model = YOLO(model, task=task)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/model.py", line 107, in __init__
    self._load(model, task)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/model.py", line 156, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py", line 579, in attempt_load_one_weight
    args = {**DEFAULT_CFG_DICT, **(ckpt.get('train_args', {}))}  # combine model and default args, preferring model args
AttributeError: 'ObjectDetectionModel' object has no attribute 'get'
```

like this. I don't know what to do. Please help me. Thanks in advacne

**Comment by aymuos15** [comment]
Call the resume like this: model.train(resume='path_to_your_saved_weights.pt')

Look here: https://github.com/ultralytics/ultralytics/issues/5762

**Comment by glenn-jocher** [comment]
@aymuos15 thank you for reaching out and for providing the issues you are encountering with code snippets. That helps a lot with understanding what your problem may be.

Based on the error message you've provided, this seems to be a misunderstanding in the usage of the `resume` parameter and how to load a pre-trained model for further training. When it comes to resuming a previous training session with our models, you would use `resume=True` instead of `resume model=/content/models.pt`.

This is an intended behaviour, as `resume=True` loads the most recent checkpoint from the runs directory and uses their training settings and parameters, allowing the model to continue training as if it had never stopped.

Please try this adjustment and let me know if the issue is resolved or if there might be something else causing it. We're here to help, so don't hesitate to ask if you have any additional questions or issues.
