### ISSUE TITLE
Approximate YOLOv8 1280 Model Release Date

### ISSUE THREAD

**Issue by jigratz** [ultralytics/ultralytics#6061]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello- First of all, thank you Glenn Jocher for your incredible contributions to AI. Your work does not go unappreciated. &lt;Mad Respect&gt;. Secondarily, I was hoping for an update on the release date for the YOLOv8x6 1280 model, specifically for detection :)

I noticed that you mentioned in an Aug 21 answer to a similar question that they'd be released towards the end of Q3 and in the roadmap - https://github.com/orgs/ultralytics/projects/14?pane=issue&itemId=36431130 - it's currently listed as ToDo.

Thank you and Best,
-Joe

**Comment by glenn-jocher** [comment]
@jigratz hello Joe,

Firstly, thank you for your kind words and appreciation! It's not just my efforts but the entire Ultralytics team and the broader YOLO community that make these advancements possible.

I understand your eagerness for the YOLOv8x6 1280 model, specifically for detection use. Our team is diligently working on it as we speak. We always aim to make sure we release a high performance and well-optimized model for our users to benefit from.

However, timelines in AI development can sometimes shift due to a variety of factors. As such, I'm unable to provide an exact release date for the YOLOv8x6 1280 model at this moment.

Rest assured though, we are working tirelessly to have it available as soon as possible. We truly appreciate your patience and understanding in this regard.

Keep an eye on the progress in our GitHub repository, we'll surely announce it there once the model is ready to go!

All the best,
Glenn Jocher

**Comment by jigratz** [comment]
I truly appreciate your response, Glenn! Thank you, that's awesome!! I will most definitely keep an eye on the Ultralytics GitHub repository, and I'll be eagerly awaiting the culmination of you and your team's hard work!

Thanks again,
-Joe

**Comment by glenn-jocher** [comment]
@jigratz hello Joe,

Thank you for understanding and your continued interest in our work! We really appreciate your support. Keep your excitement up and watch this space for updates on YOLOv8x6 1280 model. Thank you, once again!

All the best,
Glenn Jocher

**Comment by monkeycc** [comment]
Roughly when will the YOLOv8 1280 Model be launched

Within 2 months or more than 2 months ?
@glenn-jocher

**Comment by glenn-jocher** [comment]
@monkeycc hello,

The release timeline for the YOLOv8 1280 model is not set in stone, but we are aiming for as soon as possible. It could be within the next two months or possibly longer. Keep an eye on our updates for the most accurate information.
