### ISSUE TITLE
val() return None, but print precision

### ISSUE THREAD

**Issue by JelluSandro** [ultralytics/ultralytics#6064]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Val

### Bug

I train model on my custom dataset https://app.roboflow.com/ds/1VeoqKKlEc?key=LdmLQWaylw
```
model = YOLO("yolov8s.pt")
  model.train(data=dataset.location + "/data.yaml",
   imgsz=640,
   epochs=30,
   batch=8,
   plots=True
  )
```
but when i try to get map50 from val i get AttributeError 
```
vall = model.val()
print(vall.box.map)
```
here the output
```
Ultralytics YOLOv8.0.20 🚀 Python-3.10.12 torch-2.1.0+cu118 CUDA:0 (Tesla T4, 15102MiB)
val: Scanning /content/datasets/Selfie-trash-1/valid/labels.cache... 38 images, 2 backgrounds, 0 corrupt: 100%|██████████| 38/38 [00:00<?, ?it/s]
WARNING ⚠️ Box and segment counts should be equal, but got len(segments) = 4, len(boxes) = 133. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 5/5 [00:03<00:00,  1.61it/s]
                   all         38        133      0.886      0.549      0.814      0.485
                   Bin         38         36      0.888      0.639      0.764      0.549
                   Can         38          1          1          0      0.995      0.298
             Container         38         75       0.87      0.712      0.781      0.493
                  Tank         38         11      0.817       0.81      0.833      0.662
                   urn         38         10      0.853      0.584      0.696      0.422
Speed: 0.8ms pre-process, 26.1ms inference, 0.0ms loss, 4.9ms post-process per image
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-26-0156c3861057>](https://localhost:8080/#) in <cell line: 1>()
      2   vall = model.val()
      3   #vall = model.val(data=datasets[0].location + "/data.yaml")
----> 4   print(vall.box.map50)

AttributeError: 'NoneType' object has no attribute 'box'
```

### Environment

google colab 
ultralytics==8.0.20

### Minimal Reproducible Example

```
!nvidia-smi

import os
import numpy as np
HOME = os.getcwd()

!pip install ultralytics==8.0.20

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

DEFAULT_WITH=640

!mkdir {HOME}/datasets
%cd {HOME}/datasets
!pip install roboflow --quiet
rf = Roboflow(api_key="RbnALFA63CQ18PFgSdYX")
project = rf.workspace("itmo-ognxn").project('selfie-trash')
dataset = project.version(1).download("yolov8")
model = YOLO("yolov8s.pt")
model.train(data=dataset.location + "/data.yaml",
   imgsz=640,
   epochs=15,
   batch=8,
   plots=True
)
vall = model.val()
print(vall.box.map50)

```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@JelluSandro it seems like you are encountering an AttributeError when trying to print the map50 score of your YOLOv8 model validation.

The `model.val()` function performs validation on the data passed to it. However, this function doesn't return a value, hence the AttributeError you're seeing. The precision and other metrics you see printed are side-effects of calling the function, not a return object you can directly interact with.

For this reason, when you call `vall.box.map50` after the validation, Python cannot find the 'box' attribute because 'vall' is of 'NoneType'. 

Currently, there's no direct way available to obtain mAP or other similar metrics as a variable directly through the API. You could however parse the logs to extract this information. The metrics are usually printed in the terminal or console and kept in the last few lines of the '.txt' file saved along with the weights during training. 

If you're looking to integrate this into an automated pipeline or for programmatically accessing this data, parsing the logs would be the way to go at this time.
