### ISSUE TITLE
YOLO-NAS - Inference ascii decode error

### ISSUE THREAD

**Issue by ramonseugling** [ultralytics/ultralytics#6076]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hello! I am trying to run the inference step using YOLO-NAS and i am getting the following error:

```
UnicodeDecodeError                        Traceback (most recent call last)
[<ipython-input-32-792145eee9de>](https://localhost:8080/#) in <cell line: 3>()
      1 import supervision as sv
      2 
----> 3 ds = sv.DetectionDataset.from_yolo(
      4     images_directory_path=f"{dataset.location}/test/images",
      5     annotations_directory_path=f"{dataset.location}/test/labels",

10 frames
[/usr/lib/python3.10/encodings/ascii.py](https://localhost:8080/#) in decode(self, input, final)
     24 class IncrementalDecoder(codecs.IncrementalDecoder):
     25     def decode(self, input, final=False):
---> 26         return codecs.ascii_decode(input, self.errors)[0]
     27 
     28 class StreamWriter(Codec,codecs.StreamWriter):

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 288: ordinal not in range(128)
```
I am trying to execute this step from Jupyter Notebook:

import supervision as sv

```
ds = sv.DetectionDataset.from_yolo(
    images_directory_path=f"{dataset.location}/test/images",
    annotations_directory_path=f"{dataset.location}/test/labels",
    data_yaml_path=f"{dataset.location}/data.yaml",
    force_masks=False
)
```
I don't know why this is happening :(

I set UTF-8 locale before to fix the problem: 'NotImplementedError: A UTF-8 locale is required. Got ANSI_X3.4-1968'

```
import locale
locale.getpreferredencoding = lambda: "UTF-8"
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ramonseugling hello there,

I appreciate you taking the time to detail your issue with using YOLO-NAS for inference. It seems you're encountering some difficulty with Unicode decoding during this step.

The error message is suggesting that the input for the `ascii_decode()` function is not able to be handled correctly. One potential reason could be because the dataset or labels you're using contain non-ASCII characters.

Given the UTF-8 locale setting you've applied, you should have been able to handle such characters. However, it seems there could still be an unexpected encoding issue:

1. It's possible that your labels or the contents of `data.yaml` have special/non-ascii characters that are being read as ascii, which is triggering this UnicodeDecodeError. Please make sure to clean your dataset and labels to only include characters that can be decoded properly.

2. If your dataset and labels don't seem to have any issues, the problem might lie within the library `supervision` you're importing. It might be handling strings in a specific encoding that differs from the rest of your environment.

To help figure this out, you should try to isolate the problem. Try running your model on a different dataset, or alternatively, try running your existing dataset with a different model. This could help you determine whether the issue lies with the dataset itself or the model.

Please let me know if trying these steps helps resolve your issue. Your contributions help improve the robustness of our YOLOv8 setup!

Best regards,
Glenn Jocher
