### ISSUE TITLE
How does it come that yolov5 is better at this task than yolov8 ?

### ISSUE THREAD

**Issue by dmddmd** [ultralytics/ultralytics#609]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

https://www.youtube.com/watch?v=QT17_thvseg 
![grafik](https://user-images.githubusercontent.com/33686690/214374232-71c44126-0028-4e20-90b2-781a11e2accd.png)

**Comment by suryan-s** [comment]
On which models do both were trained? @AyushExel any ideas?

**Comment by AyushExel** [comment]
Well, this isn't an apples-to-apples comparison. There are many things that are taken into account when comparing models. It's totally possible that a v5 model could give better results than a v8 model if the dataset is more suited to the model structure, the hyperparameters are tuned in favor of one and maybe one of them overfit or underfit. 
The comparison we make is on coco val set because that is what is considered the standard. It's possible that a v5 model outperforms a v8 model although I doubt that's the case here. I think a well-trained v8 model will still outperform v5 model.
