### ISSUE TITLE
Cannot Install Ultralytics library on Raspberry pi 4

### ISSUE THREAD

**Issue by zainabalzaimoor** [ultralytics/ultralytics#6094]
How to install ultralytics and yolov8 libraries in Raspberry Pi4? I've tried a couple of methods that don't work and show some errors like it will gonna break the installation of python or OS.

So what I can do then? Plz help me out it is so urgent!!!!!!!

**Comment by MarkhamLee** [comment]
I haven't tried this guide myself, but it has sections for installing Ultralytics on a Raspberry Pi for both YOLOv5 and YOLOv8: https://github.com/ultralytics/ultralytics/blob/main/docs/guides/raspberry-pi.md

A couple of other tips:
* I found installing the ultralytics and it's associated libraries via `sudo python3 - m pip` was the trick to getting YOLOv5 to work on a Raspberry Pi 4B, Orange Pi 3B and Orange Pi 5+ (running an official Ubuntu disti, Amrbian and a Community built Ubuntu variant) respectively
* Getting opencv working right was another issue, the opencv variants below plus the sudo python3 trick were what got it working for me: 

opencv-contrib-python==4.8.1.78
opencv-python-headless==4.8.0.76

hope this helps, good luck!

**Comment by zainabalzaimoor** [comment]
I tried following these steps for installation 😞

**Comment by glenn-jocher** [comment]
@zainabalzaimoor i'm sorry to hear you're having trouble installing YOLOv8 on a Raspberry Pi 4. The process can indeed be challenging due to the various dependencies and the specific architecture of the Pi.

Firstly, ensure that your Raspberry Pi 4 is running a compatible operating system. A 64-bit operating system like Ubuntu Server is recommended for better compatibility and optimal performance.

For the Ultralytics and YOLOv8 libraries, you may try to install them using pip3. Please note that using 'sudo' with pip3 might help in resolving any permission issues that may occur during the installation.

You mentioned that you're seeing some errors related to a possible break in the installation of Python. This may be due to conflicting versions of Python or specific libraries. Make sure you're using Python 3.6 or later as it is required to run YOLOv8.

Getting OpenCV to work correctly with Raspberry Pi can be tricky, you might need to install a specific version that is compatible with your setup. Generally, OpenCV versions 4.1.2 and above should work fine.

Other requirements are Pytorch and Torchvision which are necessary for YOLOv8 to work. Keep in mind these libraries also require specific versions to be compatible with the different components.

Remember, always run 'pip3 install -r requirements.txt' once you've cloned the Ultralytics YOLOv8 repo to install the specific versions of required libraries.

I hope this provides you with a good start. Please reply if you have further questions or need clarification on any step. We're here to help! Good luck with your installation!
