### ISSUE TITLE
Incorrect instructions within benchmarks.py script cause a numpy error: AttributeError: module 'numpy' has no attribute 'bool'.

### ISSUE THREAD

**Issue by MarkhamLee** [ultralytics/ultralytics#6098]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Observed behavior: 

At the top of the benchmarks.py script located within ultralytics/utils/benchmarks.py the instructions to run the script are given as follows: 
```
    from ultralytics.utils.benchmarks import ProfileModels, benchmark
    ProfileModels(['yolov8n.yaml', 'yolov8s.yaml']).profile()
    benchmark(model='yolov8n.pt', imgsz=160)
```
However, running the above as is, will generate the following error: 

```
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
```
However, if you just use the below it works just fine. I attempted to change the list in the profile models line to just include "yolov8n.yaml" and got the same error. 

```
    from ultralytics.utils.benchmarks import ProfileModels, benchmark
    benchmark(model='yolov8n.pt', imgsz=160)
```

Expected behavior:
The benchmarking script would test various versions of the selected model after running the code as provided in the benchmark script's usage instructions. 

### Environment

Ultralytics YOLOv8.0.189 🚀 Python-3.10.13 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090 Ti, 24226MiB)
Setup complete ✅ (20 CPUs, 62.6 GB RAM, 126.3/915.7 GB disk)

OS                  Linux-6.2.0-33-generic-x86_64-with-glibc2.35 (Ubuntu 22.04.3 LTS x86_64 )
Environment         Linux
Python              3.10.13
Install             pip
RAM                 62.58 GB
CPU                 12th Gen Intel Core(TM) i7-12700K
CUDA                11.7

matplotlib          ✅ 3.8.0>=3.3.0
numpy               ✅ 1.26.1>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.0.1>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.0.1>=1.8.0
torchvision         ✅ 0.15.2>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 2.1.2>=1.1.4
seaborn             ✅ 0.12.2>=0.11.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0

### Minimal Reproducible Example

In order to facilitate testing various versions, image sizes, etc., for YOLOv8 I created a file called "run_tests.py" that included the following code provided at the top of the benchmarks.py file under "usage". Once I validated the instructions worked, my plan was update the script to test out several different image and model sizes, so I could gather a large amount of testing data in one go. 

```
from ultralytics.utils.benchmarks import ProfileModels, benchmark
ProfileModels(['yolov8n.yaml', 'yolov8s.yaml']).profile()
benchmark(model='yolov8n.pt', imgsz=160)
```
I then ran the file via `python3 run_tests.py `

Once I got rid the line of code below, the benchmark script worked just fine. 
`ProfileModels(['yolov8n.yaml', 'yolov8s.yaml']).profile()`

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@MarkhamLee thank you for your detailed report. From what I gather, you're encountering an issue with the `ProfileModels` function in the `benchmarks.py` script, which results in an AttributeError related to the `numpy.bool` attribute. The `numpy.bool` attribute was indeed deprecated in favor of just using Python's built-in `bool` type, which seems to be causing this issue.

For a quick and non-destructive solution, you may want to try replacing all instances of `np.bool` with just `bool` in the files related to the benchmarking script. This should act as a substitute for `numpy.bool` while also not altering any behavior, as they function the same way.

Meanwhile, we will update the repository to fix this deprecation issue. Should you encounter any other issues or require further assistance, please don't hesitate to inform us.

Thank you again for your help in improving the YOLOv8 repo, your efforts are greatly appreciated!

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by MarkhamLee** [comment]
I resynched the repo and everything works fine now. Looks like the issue with numpy.bool was fixed between when I originally cloned the repo (10/30) and when you tested.

**Comment by glenn-jocher** [comment]
@MarkhamLee hello,

Thank you for your update on the situation. I'm glad to hear that you were able to resolve the issue by resynchronizing the repo. Indeed, it's possible that the problem was corrected in a more recent update.

In the future, we recommend regularly pulling the latest updates from the repository to ensure you're working with the most up-to-date and accurate codebase. As you've encountered, doing so can help avoid problems and keep everything running smoothly.

Glad things are working as expected now with YOLOv8. If you encounter any other concerns or queries, feel free to open up a new issue.

Happy coding!
