### ISSUE TITLE
Seeking Assistance for Persistent YOLOv8 Training Error at the end of epoch 13

### ISSUE THREAD

**Issue by gaetzzz** [ultralytics/ultralytics#6102]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm encountering a persistent error during YOLOv8 model training that I could use some assistance with. 
Since I changed the bounding box in my dataset the training phase keep fail at the end of epoch 13.
The error occurs regardless of the image size, as I've tried both 500x500 and 640x640 images, and it happens in both single-GPU and multi-GPU configurations. Any help or insights would be greatly appreciated
The error message is as follows:
```
   13/80      4.96G     0.5474      1.666     0.3372     0.4329      1.141          7        640:  98%|█████████▊| 64/65 [03:25<00:03,  3.21s/it]Traceback (most recent call last):
  File "/home/gsimonel/yolo/train_yolo.py", line 24, in <module>
    main()
  File "/home/gsimonel/yolo/train_yolo.py", line 16, in main
    model.train(data=modelPath, epochs=80, imgsz=640, device=[0,1,2,3])
  File "/home/gsimonel/.conda/envs/pytorchENV/lib/python3.10/site-packages/ultralytics/engine/model.py", line 334, in train
    self.trainer.train()
  File "/home/gsimonel/.conda/envs/pytorchENV/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 195, in train
    self._do_train(world_size)
  File "/home/gsimonel/.conda/envs/pytorchENV/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 408, in _do_train
    dist.broadcast_object_list(broadcast_list, 0)  # broadcast 'stop' to all ranks
  File "/home/gsimonel/.conda/envs/pytorchENV/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1436, in wrapper
    return func(*args, **kwargs)
  File "/home/gsimonel/.conda/envs/pytorchENV/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2240, in broadcast_object_list
    broadcast(object_sizes_tensor, src=src, group=group)
  File "/home/gsimonel/.conda/envs/pytorchENV/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1436, in wrapper
    return func(*args, **kwargs)
  File "/home/gsimonel/.conda/envs/pytorchENV/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1559, in broadcast
    work.wait()
RuntimeError: [Rank 2] Caught collective operation timeout: WorkNCCL(SeqNum=11000, OpType=BROADCAST, TensorShape=[1], Timeout(ms)=10800000) ran for 10800265 milliseconds before timing out.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 30237 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 30238 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 30240 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 2 (pid: 30239) of binary: /home/gsimonel/.conda/envs/pytorchENV/bin/python
Traceback (most recent call last):
  File "/home/gsimonel/.conda/envs/pytorchENV/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/gsimonel/.conda/envs/pytorchENV/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/gsimonel/.conda/envs/pytorchENV/lib/python3.10/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/home/gsimonel/.conda/envs/pytorchENV/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/gsimonel/.conda/envs/pytorchENV/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/gsimonel/.conda/envs/pytorchENV/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/gsimonel/.conda/envs/pytorchENV/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/gsimonel/.conda/envs/pytorchENV/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/gsimonel/yolo/train_yolo.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-31_13:04:07
  host      : node02.cluster.taz
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 30239)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/home/gsimonel/yolo/train_yolo.py", line 24, in <module>
    main()
  File "/home/gsimonel/yolo/train_yolo.py", line 16, in main
    model.train(data=modelPath, epochs=80, imgsz=640, device=[0,1,2,3])
  File "/home/gsimonel/.conda/envs/pytorchENV/lib/python3.10/site-packages/ultralytics/engine/model.py", line 334, in train
    self.trainer.train()
  File "/home/gsimonel/.conda/envs/pytorchENV/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 190, in train
    raise e
  File "/home/gsimonel/.conda/envs/pytorchENV/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 188, in train
    subprocess.run(cmd, check=True)
  File "/home/gsimonel/.conda/envs/pytorchENV/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/gsimonel/.conda/envs/pytorchENV/bin/python', '-m', 'torch.distributed.run', '--nproc_per_node', '4', '--master_port', '41312', '/home/gsimonel/yolo/train_yolo.py']' returned non-zero exit status 1.
```

**Comment by glenn-jocher** [comment]
@gaetzzz hello and thank you for bringing this to our attention.

Based on the error logs you provide, it appears the issue arises from a collective operation timing out, specifically a broadcast operation. Without getting too into the weeds, this operation is part of the process of coordinating between multiple GPUs during training.

Since you've mentioned that this issue persists irrespective of the image size and the type of GPU configuration (single or multi), we can likely rule out issues related to memory or GPU capacity.

One pertinent detail is that you've noticed this issue since changing the bounding box in your dataset. There could be an unexpected issue with the new bounding box coordinates that's causing the distributed process to hang up. I recommend double checking formats and values to make sure there are no anomalies or outliers.

However, due to the complexity of this issue, it's pretty difficult to diagnose without more information. It would be helpful if you could share more details about how exactly you changed the bounding box and any other modifications you made around the same time when you started seeing this issue.

In the meantime, you may want to try adjusting the timeout period for collective operations. It's also worth to update your PyTorch version and your Ultralytics YOLOv8 version if there are recent updates available.

Let me know how it goes and I'm here to help you further.

**Comment by gaetzzz** [comment]
I'm working on a keypoint detection project. Previously, I used to take 90% of both the width and height of the image as the bounding box. However, now I've switched to only considering the area around the points of interest, with an additional 5% padding for improved accuracy.

You also mentioned the timeout period for collective operations, may I ask you for some guidelines to change this value?

**Comment by glenn-jocher** [comment]
@gaetzzz hello, thanks for sharing more information about your project. Still, It sounds like your dataset adjustments are largely aimed at honing in more precisely on your points of interest, which is a great strategy. However, it's difficult to say definitively without more information whether these changes are causing your issues. One suggestion would be to ensure there are no irregular values or null data in your bounding box coordinates that might be causing the issue.

Concerning the timeout period for collective operations, this is a somewhat advanced configuration setting that manages how long PyTorch will wait for collective operations (like the broadcasting operation where your error happens) to complete before timing out. Adjusting this may or may not solve your issue, as the root cause appears to be elsewhere. Unfortunately, adjustable operation timeouts are typically not exposed a high-level API but are implemented internally within PyTorch's distributed libraries.

Given the complexity of what you're dealing with, it may be worthwhile to take a closer look at your alterations, examine your dataset once again, and make sure everything aligns with the expected formats and values. If your issue persists, debugging with a smaller subset of your images might help isolate the problem. Good luck with your project!

**Comment by gaetzzz** [comment]
hi glenn. May i ask you what kind of information you would like to have to better understand where this problem could came?

This is the code I use to train my network
```
sk.pal("START YOLO", "trainyolo")
    generalPath = os.getcwd() + "/yolo/"
    weightPath = generalPath +"yolov8x-pose.pt"
    modelPath = generalPath + "datasetCoka_rebalanced.yaml"
    print("modelpath:",modelPath)
    model = YOLO(weightPath)
    # Train the model
    if sk.CLUSTER:
        print("using: ",modelPath)
        model.train(data=modelPath, epochs=80, imgsz=640, device=[0,1,2,3])
    else:
        print("using datasetLocal.yaml")
        model.train(data='datasetLocal.yaml', epochs=4, imgsz=320, device=0)
```

**Comment by glenn-jocher** [comment]
@gaetzzz, thank you for providing that snippet of your training setup. To better assist you, the following details would be particularly useful:

1. **Dataset Integrity Check**: Make sure your bounding boxes are well-formed and within the image boundaries after your changes. Any significant deviation or incorrect annotations might be causing issues during training.

2. **Data Loader Performance**: Check for any warnings or errors during the dataloading phase. Sometimes problems can occur if there are issues reading the dataset or with image annotations.

3. **Configuration Files**: Take a closer look at `datasetCoka_rebalanced.yaml` and compare it with `datasetLocal.yaml` to ensure that all the paths, number of classes, and dataset structure match the expected format.

4. **PyTorch and CUDA Versions**: Confirm that your PyTorch and CUDA toolkit versions are compatible with each other as well as with the version of YOLOv8 you’re using.

5. **Previous Commit Check**: If possible, try rolling back to a previous state of your codebase where training was successful, then incrementally apply your changes to isolate where the problem might be triggered.

6. **System Logs and Hardware Monitoring**: Review system logs for any hardware-related errors, monitor GPU usage, and watch for any out-of-memory errors that could suggest an issue beyond the training script itself.

As the error points to a distributed training timeout, it would also be beneficial to inspect the network communication between nodes if you are on a cluster. Network-related issues can sometimes lead to similar errors.

Meanwhile, if anything particular was changed in the set-up of the bounding box coordinates or the data preparation pipeline, it would be beneficial to revert those changes temporarily to observe if this resolves the issue.

Furthermore, if after checking the above items the issue still occurs, you might consider running a training session with debug level verbosity enabled. This could provide additional insights into when and why the error occurs.

Based on the details provided, it should be possible to identify any deviations in the training data or the training process that might be causing the collective timeout error.
