### ISSUE TITLE
.pt to onnx bug

### ISSUE THREAD

**Issue by fry404006308** [ultralytics/ultralytics#6103]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

my yolov8 version is '8.0.188'.
I use segment model and detect model.
I change input channel from 3 to 6.
when I finished trained, I converted .pt to onnx.
I visualize the onnx file in netron, Then I found the output of my segment model is not like official segment model.
Official segment onnx model just have 2 output, 'output0' and 'output1'.
But my segment onnx model have 6 output, 'output0'/'output1'/'onnx::reshape_628'/'onnx::reshape_643'/'onnx::reshape_597'/'548' .
The '548' output layer is map to Official segment onnx model layer 'output1'.
I checked the onnx in netron, I find the added output layer all be producted by different concat operation.
I want to know how to solve this bug.
Thanks.

### Environment

Ultralytics YOLOv8.0.188  Python-3.10.13 torch-2.0.0+cu118 CUDA:0 (NVIDIA GeForce RTX 4060 Laptop GPU, 8188MiB)
Setup complete  (16 CPUs, 63.7 GB RAM, 400.6/476.0 GB disk)

OS                  Windows-10-10.0.22621-SP0
Environment         Windows
Python              3.10.13
Install             pip
RAM                 63.74 GB
CPU                 12th Gen Intel Core(TM) i7-12650H
CUDA                11.8

matplotlib           3.7.3>=3.3.0
numpy                1.24.1>=1.22.2
opencv-python        4.8.0.76>=4.6.0
pillow               9.3.0>=7.1.2
pyyaml               6.0.1>=5.3.1
requests             2.28.1>=2.23.0
scipy                1.11.2>=1.4.1
torch                2.0.0+cu118>=1.8.0
torchvision          0.15.1+cu118>=0.9.0
tqdm                 4.66.1>=4.64.0
pandas               2.1.1>=1.1.4
seaborn              0.12.2>=0.11.0
psutil               5.9.0
py-cpuinfo           9.0.0

### Minimal Reproducible Example

```
class YoloSegExporter():
    @staticmethod
    def exporterMain(paramsDict):
        trainParams = paramsDict['params']
        dataAugmentationParams = paramsDict['dataAugmentation']
        yolov8Params = paramsDict['params']['yolov8']
        yolov8_trainLogDir = yolov8Params['trainLogDir']

        # 1、
        model = YoloTrain_support.initModel(paramsDict)

        # 2、
        inputChannel = paramsDict['params']['inputChannel']
        model.export(format='onnx',inputChannel=inputChannel)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by fry404006308** [comment]
您好，我是范仁义，您的邮件我已经收到，我会尽快处理，谢谢。

**Comment by fry404006308** [comment]
my model is this
```
                   from  n    params  module                                       arguments                     
  0                  -1  1      2688  SF_DL_Algo.base.ultralytics.nn.modules.conv.Conv[6, 48, 3, 2]                 
  1                  -1  1     41664  SF_DL_Algo.base.ultralytics.nn.modules.conv.Conv[48, 96, 3, 2]                
  2                  -1  2    111360  SF_DL_Algo.base.ultralytics.nn.modules.block.C2f[96, 96, 2, True]             
  3                  -1  1    166272  SF_DL_Algo.base.ultralytics.nn.modules.conv.Conv[96, 192, 3, 2]               
  4                  -1  4    813312  SF_DL_Algo.base.ultralytics.nn.modules.block.C2f[192, 192, 4, True]           
  5                  -1  1    664320  SF_DL_Algo.base.ultralytics.nn.modules.conv.Conv[192, 384, 3, 2]              
  6                  -1  4   3248640  SF_DL_Algo.base.ultralytics.nn.modules.block.C2f[384, 384, 4, True]           
  7                  -1  1   1991808  SF_DL_Algo.base.ultralytics.nn.modules.conv.Conv[384, 576, 3, 2]              
  8                  -1  2   3985920  SF_DL_Algo.base.ultralytics.nn.modules.block.C2f[576, 576, 2, True]           
  9                  -1  1    831168  SF_DL_Algo.base.ultralytics.nn.modules.block.SPPF[576, 576, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  SF_DL_Algo.base.ultralytics.nn.modules.conv.Concat[1]                           
 12                  -1  2   1993728  SF_DL_Algo.base.ultralytics.nn.modules.block.C2f[960, 384, 2]                 
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  SF_DL_Algo.base.ultralytics.nn.modules.conv.Concat[1]                           
 15                  -1  2    517632  SF_DL_Algo.base.ultralytics.nn.modules.block.C2f[576, 192, 2]                 
 16                  -1  1    332160  SF_DL_Algo.base.ultralytics.nn.modules.conv.Conv[192, 192, 3, 2]              
 17            [-1, 12]  1         0  SF_DL_Algo.base.ultralytics.nn.modules.conv.Concat[1]                           
 18                  -1  2   1846272  SF_DL_Algo.base.ultralytics.nn.modules.block.C2f[576, 384, 2]                 
 19                  -1  1   1327872  SF_DL_Algo.base.ultralytics.nn.modules.conv.Conv[384, 384, 3, 2]              
 20             [-1, 9]  1         0  SF_DL_Algo.base.ultralytics.nn.modules.conv.Concat[1]                           
 21                  -1  2   4207104  SF_DL_Algo.base.ultralytics.nn.modules.block.C2f[960, 576, 2]                 
 22        [15, 18, 21]  1   5160761  SF_DL_Algo.base.ultralytics.nn.modules.head.Segment[3, 32, 192, [192, 384, 576]] 
YOLOv8m-seg summary: 331 layers, 27242681 parameters, 27242665 gradients
```

**Comment by fry404006308** [comment]
# my onnx model output

![1698916746806](https://github.com/ultralytics/ultralytics/assets/33335064/f100bf3b-7c24-487f-b4a0-340899253e56)

# output difference between my model and official model

![1698917128545](https://github.com/ultralytics/ultralytics/assets/33335064/57fd8977-de13-4ec6-8449-30718aaca0aa)

![1698917257061](https://github.com/ultralytics/ultralytics/assets/33335064/dec4e182-e962-4a28-bca9-a644deb36081)

![1698917384354](https://github.com/ultralytics/ultralytics/assets/33335064/46b1827d-b2f9-4ab0-a458-eb5bda62a19f)

**Comment by glenn-jocher** [comment]
@fry404006308 based on the shown output differences, it seems like your model and the official model are giving different results. 

The discrepancies could be due to a variety of reasons. For example, differences in preprocessing steps like normalization, resizing or padding could produce varying outputs. Another common source of variation is if the models have been trained on different datasets or under different training conditions.

It's also worth noting that the ONNX model and the original PyTorch model may not match up exactly due to differences in implementation details between the two frameworks. 

In order to debug this further, you might want to check whether your preprocessing steps and input data match with the official model. Furthermore, verify if both the models are indeed structurally identical and were trained under the same conditions. Identifying these differences should help you pinpoint the source of the variant outputs.

**Comment by fry404006308** [comment]
@glenn-jocher 
Thank you very much for your response. In fact, my main operation was to change the number of channels, as I've made the number of channels dynamically input, instead of the default of 3. This allows it to be applicable to a variety of different situations. 

As a result of changing the number of channels, corresponding pre-processing operations, such as image loading and data augmentation, have also been adjusted accordingly. I did not change the network structure.

However, there's one point that I'm quite puzzled about. Since I only changed the number of channels in the first layer, it is the only layer that differs from the official model. All other layers are exactly the same as the official model.

If I use the same second layer as an input, given that the input is the same and the network structure is also the same, the results should be identical.

I will carry out the following tests next:

- 1. Test images with three channels, and compare the results with the official model.
- 2. Visualize the network structure (.pt) and compare it with the official model.

Thanks again.

**Comment by glenn-jocher** [comment]
Hi @fry404006308,

Thank you for providing a detailed explanation of your modifications. Changing the number of channels can indeed provide flexibility for different use cases.

For the situation you mentioned, even though the changes seem to be confined to the first layer, these changes can have a cascading effect on the layers that follow, which might explain why the output is different. The deeper layers in the network will process the input data differently depending on what they receive from the preceding layers.

Regarding your future tests:

1. Testing images with three channels and comparing the results with the official model is a great idea. This should help identify whether the issue stems from the preprocessing changes you made or if it is inherently due to the alteration in the number of channels.

2. Visualizing and comparing the network structure with the official one will also be useful. It can reaffirm that only the first layer has been modified and the rest of the structure remains the same.

I look forward to hearing about your findings. Don't hesitate to ask if there are any more questions or concerns. Good luck with your testing!

**Comment by glenn-jocher** [comment]
Hi @fry404006308,

Great job in identifying and resolving the issue! Indeed, changing the number of input channels dynamically can have unforeseen consequences. 

As you pointed out, your modification resulted in the detection head becoming a different instance during the ONNX export. That led to incorrect assessment, causing an increase in output numbers in your ONNX model. It's important that the model be exported in 'export' mode for correct operations.

Your findings are truly insightful and will likely benefit others who might encounter the same issue in the future. Thank you for your diligent troubleshooting and for sharing your solution with us. If you have further questions or concerns, don't hesitate to reach out. Happy coding!

**Comment by mrdoguoz** [comment]
Hello guys,

I trained the best.pt model with 6 segments with the yolo v8 model. Then I converted the best.pt model to best.onnx format with python:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
from ultralytics import YOLO

Load a model
model_path = r'C:\Users\user\Desktop\Dogukan\best.pt'
official_model_path = r'C:\Users\user\Desktop\Dogukan\yolov8m-seg.pt'

model = YOLO(official_model_path) # load an official model
model = YOLO(model_path) # load a custom trained model

Export the model
model.export(format='onnx')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Then I ran the best.onnx model on the PNG file in Android Java and output the results to the "result" object. I give my codes below:

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
public void onn() throws OrtException { OrtEnvironment env = OrtEnvironment.getEnvironment(); OrtSession.SessionOptions opts = new OrtSession.SessionOptions(); OrtSession session = env.createSession("/storage/emulated/0/Android/data/com.bantas.debug/files/best.onnx", opts); try { Bitmap bitmap = BitmapFactory.decodeFile("/storage/emulated/0/Android/data/com.bantas.debug/files/BlickerImage_37712.png");
float[][][][] input = preprocessImage(bitmap);

OnnxTensor inputTensor = OnnxTensor.createTensor(env, input);
OrtSession.Result result = session.run(Collections.singletonMap("images", inputTensor));
OnnxTensor outputTensor = (OnnxTensor) result.get(0);

float[][][] threeDimensionalArray = (float[][][]) result.get(0).getValue();

float[][] scores = threeDimensionalArray[0];
// Map<String, Float> scoreMap = (Map<String, Float>) result.get(1).getValue();

Gson gson = new Gson();
String scoresJson = gson.toJson(scores);
// String scoreMapJson = gson.toJson(scoreMap);

// String deneme = processResult1(result);
Object out = outputTensor.getValue();

// Gson gson = new Gson();
String json = gson.toJson(out);
String a = json;

} catch (Exception e) {
e.printStackTrace();
}

}
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
As the model output above, the json object is formed as follows:

json=[[[4.510956,17.391268,22.62502,27.104994 ... ...,0.6338775,0.54058886,0.36109298,0.062129557,0.043105423,0.3687974]]]

Using the JSON output from the ONNX model, what steps do I need to follow in Android Java to draw an image with certain bounding boxes and their class and confidence scores? How do we parse the JSON data representing the output of the model to get the coordinates, class information and confidence scores of the bounding boxes?

Best regards.

**Comment by glenn-jocher** [comment]
@mrdoguoz hello,

I'm glad to hear you've trained your model and successfully exported it as ONNX for use in your Android application. To parse the JSON output from the ONNX model and extract useful information for drawing bounding boxes with class and confidence scores on images, follow these general steps:

1. **Parsing the JSON:**
   The JSON you provided seems to be a part of the output tensor from the ONNX model. This tensor typically contains the detection results, including bounding box coordinates, confidence scores, and class IDs.

2. **Understanding the Output:**
   YOLO outputs typically follow a certain scheme where each detection contains the bounding box coordinates (x-center, y-center, width, height), the confidence score of that detection, and a one-hot encoded vector for class probabilities. Your task is to understand how the tensor is structured – you'll likely need to refer to the documentation or the source for your model to interpret the numbers correctly.

3. **Convert JSON to ArrayList or other data structure:**
   Parse the JSON to an ArrayList or suitable data structure that will hold the output data in a more structured form that allows easy manipulation.

4. **(Optional) Apply Softmax:**
   If the output class probabilities are not already softmaxed (compressed to a range of [0, 1] where they sum to 1), you may need to apply a softmax function to them to interpret them as probabilities.

5. **Thresholding:**
   You might want to filter out detections with a confidence score lower than a certain threshold. This is commonly done to reduce the number of false positives.

6. **Non-Maximum Suppression (NMS):**
   If multiple boxes are detected around the same object, you'll need to apply NMS to select the most accurate one and discard overlapping boxes.

7. **Drawing on the bitmap:**
   For every detection remaining after thresholding and NMS, you'll convert the coordinates from the model's output scale to the original image scale. Then, use methods like `Canvas.drawRect()` in Android to draw the bounding boxes. The class and confidence score can be displayed using `Canvas.drawText()`.

8. **Understanding the Box Coordinates:**
   Remember that the box coordinates may not be in the format required for drawing directly. You might have to convert from the normalized center coordinates to the top-left corner, and you may also need to scale them back up to your image size if they're normalized.

Here's a pseudo-outline of what the process might look like:

```java
// Parsing JSON and obtaining bounding boxes, scores, and classes
ArrayList<BoundingBox> boxes = parseJsonToBoundingBoxes(json);

// Apply threshold and NMS
ArrayList<BoundingBox> filteredBoxes = applyThresholdAndNMS(boxes, threshold, nmsIoU);

// Draw boxes on the Bitmap
Canvas canvas = new Canvas(bitmap);
for (BoundingBox box : filteredBoxes) {
    paint.setStyle(Paint.Style.STROKE);
    paint.setColor(Color.RED); // for the border
    canvas.drawRect(box.x, box.y, box.x + box.width, box.y + box.height, paint);

    // Add text for the class and confidence score
    paint.setStyle(Paint.Style.FILL);
    paint.setColor(Color.WHITE); // for the text
    canvas.drawText("Class: " + box.classId + " Score: " + box.score, box.x, box.y, paint);
}

// Display the altered Bitmap in an ImageView or similar
imageView.setImageBitmap(bitmap);
```

Please note that the code above is highly simplified, and the actual implementation will depend on the serialization format of your output tensor.

Remember to use the appropriate constants and formats as per your use-case and the model's outputs. Implement the `parseJsonToBoundingBoxes()` and `applyThresholdAndNMS()` functions based on your detection output format and requirements, and replace placeholder classes like `BoundingBox` with actual implementations that contain properties like `x, y, width, height, classId, score` etc.

Best regards!

**Comment by mrdoguoz** [comment]
Hi Mr. @glenn-jocher,

**First of all, thank you for your time.
I share my codes below and I also uploaded the netron.app output of my model as an image:**

public String processResult(OrtSession.Result result) {
    JSONArray jsonArray = new JSONArray();
    for (Map.Entry<String, OnnxValue> entry : result) {
        OnnxTensor outputTensor = (OnnxTensor) entry.getValue();
        FloatBuffer buffer = convertToFloatBuffer(outputTensor);
        try {
            while (buffer.hasRemaining()) {
                JSONObject prediction = new JSONObject();
                float x = buffer.get();
                float y = buffer.get();
                float width = buffer.get();
                float height = buffer.get();
                float confidence = buffer.get();
                JSONArray classScores = new JSONArray();
                **for (int i = 0; i < 5; i++) {  // 5 sınıf için skorları al**
                    classScores.put(buffer.get());
                }
                prediction.put("names", entry.getKey());
                prediction.put("x", x);
                prediction.put("y", y);
                prediction.put("width", width);
                prediction.put("height", height);
                prediction.put("confidence", confidence);
                prediction.put("class_scores", classScores);
                jsonArray.put(prediction);
            }
        } catch (JSONException e) {
            throw new RuntimeException(e);
        }
    }
    return jsonArray.toString();
}

### **EXPLANATION:
**for (int i = 0; i < 5; i++) { Although I have 6 classes in the code line, I could only loop up to 5. When I looped up to 6, I had the problem that the data did not match, I don't understand why this happened?**

I tried to draw segment boxes with the method below, but it drew the boxes all over the image, so as a result, I could not properly extract the segments and the coordinates of the segments from the onnx model.

public void drawBoundingBoxesFromJson(String jsonArrayStr, String imagePath, String outputPath) {
    try {
        // JSON dizisini işle
        JSONArray jsonArray = new JSONArray(jsonArrayStr);

        // Orijinal resmi yükle
        Bitmap bitmap = BitmapFactory.decodeFile(imagePath);
        Bitmap mutableBitmap = bitmap.copy(Bitmap.Config.ARGB_8888, true);
        Canvas canvas = new Canvas(mutableBitmap);
        Paint paint = new Paint();
        paint.setColor(Color.RED);
        paint.setStyle(Paint.Style.STROKE);
        paint.setStrokeWidth(3);
        Paint textPaint = new Paint(Paint.ANTI_ALIAS_FLAG);
        textPaint.setColor(Color.GREEN);
        textPaint.setTextSize(30);

        // Her bir JSON nesnesindeki sınırlayıcı kutu bilgilerini kullanarak kutuları çiz
        for (int i = 0; i < jsonArray.length(); i++) {
            JSONObject prediction = jsonArray.getJSONObject(i);

            float x = (float) prediction.getDouble("x");
            float y = (float) prediction.getDouble("y");
            float width = (float) prediction.getDouble("width");
            float height = (float) prediction.getDouble("height");
            float confidence = (float) prediction.getDouble("confidence");

            // Sınıf skorlarını ve en yüksek skorlu sınıfı bul
            JSONArray classScores = prediction.getJSONArray("class_scores");
            int maxScoreIndex = 0;
            float maxScore = 0;
            for (int j = 0; j < classScores.length(); j++) {
                float score = (float) classScores.getDouble(j);
                if (score > maxScore) {
                    maxScore = score;
                    maxScoreIndex = j;
                }
            }

            String className = getClassFromIndex(maxScoreIndex); // Sınıf ismini almak için bir fonksiyon

            canvas.drawRect(x, y, x + width, y + height, paint);
            canvas.drawText(className + ": " + String.format("%.2f", confidence), x, y, textPaint);
        }

        // İşlenmiş resmi kaydet
        try {
            FileOutputStream out = new FileOutputStream(outputPath);
            mutableBitmap.compress(Bitmap.CompressFormat.JPEG, 90, out);
            out.flush();
            out.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}

private String getClassFromIndex(int index) {
    // Sınıf isimlerini bir dizi veya haritada saklayın ve index'e göre döndürün
    String[] classNames = {"sayi1", "sayi2", "sayi5", "sayac", "sayi3", "sayi4"};
    return classNames[index];
}

### **I'm giving the specifications of the onnx model:**

MODEL PROPERTIES:
format: ONNX v8
producer: pytorch 2.1.0
imports: ai.onnx v17
author: Ultralytics
license: AGPL-3.0 https://ultralytics.com/license
description: Ultralytics YOLOv8m-seg model trained on dataset.yaml
date: 2023-11-17T15:06:21.301335
version: 8.0.207
stride: 32
task: segment
batch: 1
imgsz: [640, 640]
names: {0: 'sayi1', 1: 'sayi2', 2: 'sayi5', 3: 'sayac', 4: 'sayi3', 5: 'sayi4'}
graph: main_graph

INPUTS:
name: images
tensor: float32[batch,3,height,width]

OUTPUTS:
output0
name: output0
tensor: float32[batch,Concatoutput0_dim_1,anchors]
output1
name: output1
tensor: float32[batch,32,mask_height,mask_width]

**How do we extract "tensor: float32[batch,Concatoutput0_dim_1,anchors]" and "tensor: float32[batch,32,mask_height,mask_width]"? My goal is to identify and draw the classes 'sayi1', 'sayi2', 'sayi5', 'sayac', 'sayi3', 'sayi4' on the image**

![bestmodel onnx](https://github.com/ultralytics/ultralytics/assets/94927411/3346a836-477d-4e0f-a0ed-5d570d7f4607)

I look forward to your valuable suggestions.

Best regards.

**Comment by glenn-jocher** [comment]
Hello @mrdoguoz,

Thank you for the details of your current implementation and your ONNX model outputs. It seems that you're close to achieving your goal, but there are a few important aspects to address.

### Concerning Your Output Tensor Parsing:

1. **Understanding Output Tensors**: It is crucial to have a clear understanding of what each output tensor represents. The `output0` tensor typically contains object detection predictions ([batch, number_of_predictions, values]), where "values" usually include bounding box coordinates, objectness score, and class probabilities. The `output1` tensor appears to be related to segmentation masks ([batch, 32, mask_height, mask_width]), which are for pixel-wise segmentation rather than bounding boxes.

2. **Using the Appropriate Dimensions**: The `for` loop for class probabilities should match the number of classes you have trained on – in your case, six. The mismatch could be due to an off-by-one error or an incorrect length of the flattened output array. If the data does not match when iterating up to 6, it indicates that the output array might have been interpreted incorrectly.

### Regarding Drawing Segments:

1. **Parsing Bounding Boxes**: Drawing bounding boxes requires correctly parsed and scaled bounding box coordinates. Make sure that the coordinates are scaled back to match the dimensions of your original image, as the output coordinates will be normalized relative to the input size of the ONNX model.

2. **Segmentation Masks**: To draw segmentation masks, you will need to threshold the `output1` masks to identify pixels belonging to each class and then overlay this mask on your original image. Since these masks are related to segmentation, they won't give you bounding boxes but rather pixel-wise class assignments.

### Steps to Draw Bounding Boxes and Segments:

1. Parse the detection predictions from `output0`. Extract bounding box coordinates, confidence, and class probabilities for each prediction.

2. Apply a threshold to remove low-confidence detections and use Non-Maximum Suppression (NMS) to combine overlapping boxes for the same object.

3. If you are using segmentation (`output1`), you'll identify each pixel's class assignment. You can then draw these pixels with a specific color code on the image.

4. Scale the coordinates of bounding boxes from the ONNX model's input size to the original image size for accurate placement.

5. Draw bounding boxes around the objects with classes and confidence scores using `Canvas.drawRect()` and `Canvas.drawText()`.

6. Overlay the segmented areas onto the bitmap if you are drawing segmentation masks.

Please ensure that your preprocessing and postprocessing steps are consistent with how you've trained your model. Given that ONNX models process data differently from native Python models, it's essential to align your Java code with your training process.

For extracting and interpreting ONNX outputs, consider using the shape of your outputs as a debugging tool. Knowing the exact dimensions of your outputs and understanding how they map to detected objects and segmentation maps will inform you of how to parse and use these tensors.

Finally, since drawing segments is dependent on correctly parsing segmentation masks and not just bounding boxes, you'll need to follow the specific steps detailed in the segmentation output postprocessing if your task involves segmentation.

Best regards.
