### ISSUE TITLE
Export shape for Torchscript

### ISSUE THREAD

**Issue by ganessh22** [ultralytics/ultralytics#611]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Should the detection count in output be 8400 or 25200. v5 had 25200 and some comments in the codebase refer to 25200. Is it a bug in the export script. I also see a lot of false negatives that YOLOv5x picks up despite using YOLOv8x.

**Comment by pderrenger** [comment]
@ganessh22 hey there! 👋 

The detection count in the output for TorchScript export should be 25200 for YOLOv8, not 8400. The discrepancy you noticed is likely due to a bug in the export script. Regarding the false negatives, it's important to ensure that you are using the YOLOv8x model correctly for your specific use case and data. Feel free to provide more details about your setup, and we can help address any issues you may be encountering.

If you have further questions or need additional assistance, don't hesitate to reach out!
