### ISSUE TITLE
How to hide warning log when inference with TensorRT

### ISSUE THREAD

**Issue by pornpra** [ultralytics/ultralytics#6128]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Environment
Hardware: NVIDIA Jetson Orin
Ultralytics: 8.0.196
Python: 3.8.10
Torch: torch-2.0.0+nv23.05
CUDA: 11.3.315
cuDNN: 8.6.0.166
TensorRT: 8.5.2.2
OpenCV: 4.5.4 without CUDA

I run inference object detection with YOLOv8 (already converted from .pt to .engine) and I see this warning in terminal. How can I hide these warning logs when inference YLOLOv8 with TensorRT ? 

![trt_warning](https://github.com/ultralytics/ultralytics/assets/59501173/4af36809-ede3-4ae5-9085-9e443742e26c)

**Comment by glenn-jocher** [comment]
@pornpra hello,

Thanks for reaching out!

When using TensorRT for inference, it may display warning logs due to numerous reasons. However, these are often ignorable if everything still runs as expected. 

To suppress the warning logs that appears while running inference with YOLOv8 and TensorRT, you need to adjust the logger severity of TensorRT. For example, you can set the logger severity to 'ERROR' level to display only the error logs and hide the warnings. 

This is done in the script where you initialize your `trt.Logger()`. Unfortunately, I cannot provide a code example as per your request, but I hope this textual explanation could guide you to resolve the issue. 

Remember to be careful when hiding warnings, as they might be indicating potential issues that could affect your model's performance or accuracy.

Kind Regards,
Glenn Jocher
