### ISSUE TITLE
I have a mackbook M2 processor and and im trying to run a train using this code from the terminal (yolo detect train data=/Users/romariotomo/Small-datasetRomarioTomo-2-2/data.yaml epochs=100 imgsz=800 device=mps) then I got this error zsh: bus error  yolo detect train  epochs=100 imgsz=800 device=mps

### ISSUE THREAD

**Issue by Balasolina** [ultralytics/ultralytics#6149]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I have a mackbook air M2 processor and im trying to run a train using this code from the terminal (yolo detect train data=/Users/romariotomo/Small-datasetRomarioTomo-2-2/data.yaml epochs=100 imgsz=800 device=mps) then I got this error zsh: bus error  yolo detect train  epochs=100 imgsz=800 device=mps

("(mpsFileLoc): /AppleInternal/Library/BuildRoots/75428952-3aa4-11ee-8b65-46d450270006/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":253:0)): error: 'anec.not_equal_zero' op Invalid configuration for the following reasons: Tensor dimensions N1D1C1H1W4830000 are not within supported range, N[1-65536]D[1-16384]C[1-65536]H[1-16384]W[1-16384].
loc("mps_select"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/75428952-3aa4-11ee-8b65-46d450270006/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":294:0)): error: 'anec.not_equal_zero' op Invalid configuration for the following reasons: Tensor dimensions N1D1C1H1W4830000 are not within supported range, N[1-65536]D[1-16384]C[1-65536]H[1-16384]W[1-16384].
loc("mps_not_equal"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/75428952-3aa4-11ee-8b65-46d450270006/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":253:0)): error: 'anec.not_equal_zero' op Invalid configuration for the following reasons: Tensor dimensions N1D1C1H1W210000 are not within supported range, N[1-65536]D[1-16384]C[1-65536]H[1-16384]W[1-16384].
loc("mps_select"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/75428952-3aa4-11ee-8b65-46d450270006/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":294:0)): error: 'anec.not_equal_zero' op Invalid configuration for the following reasons: Tensor dimensions N1D1C1H1W210000 are not within supported range, N[1-65536]D[1-16384]C[1-65536]H[1-16384]W[1-16384].
zsh: bus error  yolo detect train  epochs=100 imgsz=800 device=mps

### Environment

Ultralytics YOLOv8.0.114 🚀 Python-3.10.9 torch-2.0.1 CPU
Setup complete ✅ (8 CPUs, 8.0 GB RAM, 368.9/460.4 GB disk)

### Minimal Reproducible Example

yolo detect train data=/Users/romariotomo/Small-datasetRomarioTomo-2-2/data.yaml epochs=100 imgsz=800 device=mps

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Balasolina 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by liumingxing** [comment]
Did you solved it? I meet the same problem, I need some help.

**Comment by liumingxing** [comment]
I solved the problem by update torch to version 2.1.0

**Comment by glenn-jocher** [comment]
@liumingxing great to hear that you resolved the issue by updating PyTorch! If you encounter any more difficulties or have further questions as you continue working with YOLOv8, don't hesitate to reach out again. Happy detecting with YOLO! 🚀

**Comment by glenn-jocher** [comment]
@X901 that's fantastic news! 🎉 I'm glad to hear that updating PyTorch resolved the issue. If you have any more questions or need further assistance as you continue using YOLOv8, feel free to ask. Happy coding!

**Comment by glenn-jocher** [comment]
@X901 I'm sorry to hear about the new issue with NMS time limits. This could be related to the specifics of MPS handling. You might want to experiment with different configurations or batch sizes. Also, checking the most recent updates or documentation for any performance-related tips might help. If the problem persists, do not hesitate to reach out! 🛠️
