### ISSUE TITLE
The "def show(self, p):" in predictor.py seems useless

### ISSUE THREAD

**Issue by BraunGe** [ultralytics/ultralytics#615]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

The "def show(self, p):" in predictor.py locates in line 255.

`    def show(self, p):`
`        im0 = self.annotator.result()`
`        if platform.system() == 'Linux' and p not in self.windows:`
`            self.windows.append(p)`
`            cv2.namedWindow(str(p), cv2.WINDOW_NORMAL | cv2.WINDOW_KEEPRATIO)  # allow window resize (Linux)`
`            cv2.resizeWindow(str(p), im0.shape[1], im0.shape[0])`
`        cv2.imshow(str(p), im0)`
`        cv2.waitKey(1)  # 1 millisecond`

I think its function is showing results. But when I add **cv2.putText(im0, "FPS:",(7, 30), 1, (0, 0, 0), 3, cv2.LINE_AA)** to show FPS, it didn't make sence. 

`    def show(self, p):`
`        im0 = self.annotator.result()`
`        if platform.system() == 'Linux' and p not in self.windows:`
`            self.windows.append(p)`
`            cv2.namedWindow(str(p), cv2.WINDOW_NORMAL | cv2.WINDOW_KEEPRATIO)  # allow window resize (Linux)`
`            cv2.resizeWindow(str(p), im0.shape[1], im0.shape[0])`
`       **cv2.putText(im0, "FPS:",(7, 30), 1, (0, 0, 0), 3, cv2.LINE_AA)**`
`        cv2.imshow(str(p), im0)`
`        cv2.waitKey(1)  # 1 millisecond`

Even when delet the whole "def show(self, p):", the detect in prediction mode with `yolo task=detect mode=predict model=yolov8n.pt source=0 show=True` is still normal.

My question is that if I want put text when in the `source=0 show=True` mode's window, where should I insert my codes?

Thank you.

**Comment by syenpark** [comment]
Hi @BraunGe, did you resolve the issue? Based on your way to use YOLO CLI, I suppose you installed YOLO through pip. I'm not sure whether you deleted `"def show(self, p):"` in the YOLO repository you cloned or your installed YOLO package like this: /Users/BraunGe/mambaforge/envs/yolov8/lib/python3.XX/site-packages/ultralytics/yolo/engine/predictor.py". I think if you edited `"def show(self, p):" in your cloned YOLO repository, not the installed package one, it's understandable why it doesn't work. Or did you install your the YOLO package with your customised YOLO repository?

**Comment by glenn-jocher** [comment]
@syenpark absolutely, good day!

Thanks for sharing your ideas. From your question, it seems you'd like to modify the behavior of the 'show' method to incorporate displaying the FPS on your-annotated image display. Here's a high-level explanation of what you need to do, without including explicit code examples:

The 'show' method, as you pointed out, is responsible for plotting the annotated results of your predictions, so it would reasonably be the place to add any additional visualizing code. In your specific case of including FPS in the display, you'd want to compute the FPS counter in your main loop where the 'predict' method exists and pass this value into the method where you're calling 'cv2.putText()'. This method should be placed where the images or frames are being fetched for display.

However, it's worth noting that any modifications made in a cloned repository won't affect the existing installation of the YOLO package in your environment, unless you reinstall the package from your modified local copy instead of from the PyPI.

If you're not seeing change in results even after the modifications in local repository, it's likely due to you are still using the installed package from your python environment rather than the local repository.

Remember - if you want to see the changes you're making in the cloned repository affect your work, you have to install YOLO from your local, modified copy.

Hope this helps with your query, feel free to follow-up if you have any more questions or details to discuss regarding YOLOv8!
