### ISSUE TITLE
How to convert a .pt model to a .engine and quantize it with int8

### ISSUE THREAD

**Issue by 7788zun** [ultralytics/ultralytics#6151]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to deploy on Jetson AGX Orin to convert a .pt model to a .engine model and from fp32 to int8, I found that yolov8 doesn't provide such a method, and would like to ask if there is any specific code or method that can achieve such a function

**Comment by glenn-jocher** [comment]
@7788zun thank you for your question.

Currently, the YOLOv8 Ultralytics repository does not provide an out-of-the-box method to convert a `.pt` model to a `.engine` model and perform int8 quantization. However, it's possible to do this leveraging NVIDIA's TensorRT. 

Here is a high-level overview of the steps you would need to follow:

1. **Export to ONNX format**: To prepare your model for TensorRT, you first need to export it to ONNX format. Please make sure that all the operations in YOLOv8 are supported in ONNX.

2. **Conversion to TensorRT `.engine`**: Once you have the ONNX model, you can use the TensorRT Python API to convert it to a TensorRT engine. There, you'll optimize the model for your specific hardware configuration, in this case, your Jetson AGX Orin.

3. **Implement INT8 Quantization**: During this process, you can apply INT8 quantization. This involves a calibration process with a representative sample of your training or validation data to compute the dynamic range of activations and consequently scale the weights in your deep learning model.

Remember that performance gains might vary based on how well the model can be optimized for TensorRT (including INT8 precision), and the speedup could be significant on Jetson devices.

Please note – ensure to check the compatibility of ONNX operations with TensorRT, because not all operations are supported.

This process might require some advanced understanding of both Ultralytics YOLOv8 and NVIDIA's TensorRT, but it can typically be achieved with the mentioned steps.
