### ISSUE TITLE
Using folders to predict image information results in different results, and the prediction information will be truncated.

### ISSUE THREAD

**Issue by minwim** [ultralytics/ultralytics#6152]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

1. I train my seg model by yolov8n-seg.pt,  
[best.zip](https://github.com/ultralytics/ultralytics/files/13263850/best.zip)
2. my predict data:

4. my predict code as below:
[images.zip](https://github.com/ultralytics/ultralytics/files/13263876/images.zip)

```
from ultralytics import YOLO

modelPath = 'path/to/best.pt'
model = YOLO(modelPath)  # load a custom model

imgPath = 'path/to/images'
results = model(source = imgPath,
                conf = 0.1,
                imgsz = [1120,960],
                save = True,
                save_txt = True,
                save_conf = True)  # predict on an image
pass
```
I found some interesting thing
1.  i use imgsz=[1120, 960] , Why did the forecast modify my zoom size?
![image](https://github.com/ultralytics/ultralytics/assets/86920530/72f793b8-3c7c-441f-aabf-730a506830f5)
2. The prediction results using single prediction and folder prediction are inconsistent.
3. Use parameters save and save_txt to get prediction information is missing
![image](https://github.com/ultralytics/ultralytics/assets/86920530/806e4daa-1541-4c6d-b1f3-f367ab8e9f89)
my model in best.zip/best.pt
my data image in images.zip images.

### Additional

1. Why choose the last picture size for shape when reasoning?
![image](https://github.com/ultralytics/ultralytics/assets/86920530/a35a22fe-04d1-4922-89be-c47bdcacd4b2)

2. The segmentation coordinate information that is too small will not be written to txt, but why can it be displayed on the save image?
3. how to resolve it?

**Comment by glenn-jocher** [comment]
@minwim hi there,

Thank you for reaching out and providing detailed information about your problem.

1. With regards to the zoom size modification, please note that YOLOv8's internal image handling mechanism automatically adjusts the aspect ratio of the input image for consistency, regardless of the `imgsz` setting. To maintain essential object details, the resize operation retains the aspect ratio of the input image which might result in a dimension different from the `imgsz` value.

2. Differences in the prediction results between single and multiple image processing might occur due to the model's inherent variability while dealing with different lighting conditions, object scales, object layouts, and imaging characteristics.

3. For the missing prediction information when using `save` and `save_txt`, please remember that these parameters save information about detections that have a confidence level above the threshold. It is possible that some detection might have a lower confidence score, hence not being included in the saved results.

In response to the additional queries:

1. The shape chosen during inference is based on the last image in your batch. Selecting the last image's dimensions is a matter of convention in the current design of YOLOv8 which ensures all images are resized to a unified dimension to allow for batch inference.

2. Small segmentation coordinates might not reach the default precision required for printing in the .txt files, but they are still visible in the image due to the visual settings utilized during the display process.

3. To resolve these issues, you might want to experiment with different image sizes, review the confidence thresholds for detections, and adjust them to ensure no essential details are omitted during the save <txt> operation. Also, you could turn off the automatic aspect ratio correction by considering to process images of the same dimensions for consistency.

Please let us know how this goes, and if you encounter any further difficulties, do not hesitate to ask for assistance.

Best regards,
The Ultralytics Team

**Comment by minwim** [comment]
@glenn-jocher ， thank you 
yolov8 has very excellent small target detection capabilities, even targets of a few pixels. These small targets are very important to me. How do I obtain the coordinate information of such small targets? Can we store pixels directly instead of storing normalized values?

**Comment by minwim** [comment]
The detection of a few pixels of this small target is very important to me. How can I get its coordinates in txt? Can it be obtained by other methods?

**Comment by glenn-jocher** [comment]
@minwim hello again,

YOLOv8 indeed provides strong capabilities for detecting small objects, and it is understandable that you want to capture all detections including these small objects.

To save the coordinate information of small targets detected by YOLOv8, you can take the following steps:

1. **Adjust Confidence Threshold**: You can lower the threshold for detection confidence (`conf`) to ensure that even small targets with lower confidence scores are considered during inference.

2. **Check NMS Threshold**: Ensure that the non-maximum suppression (`nms`) threshold is set appropriately. If it's too high, it may suppress valid detections of small objects that are close together.

Regarding the coordinate format:

- YOLOv8 typically saves detection coordinates in a normalized format in `.txt` files, where the coordinates are relative to the width and height of the image. This is a standard practice because it ensures consistency regardless of the actual image size.

- While the coordinates are normally saved in this normalized format, the values can be easily converted back to pixel coordinates by multiplying by the original width and height of the image. This conversion can be done manually after predictions.

To get the pixel coordinates directly saved into the `.txt` files, you might need to modify the source code of the saving mechanism within the YOLOv8 repository, which involves changing the part of the code that writes detections to the file. However, as the repo maintainer, I should point out that modifying source code can lead to other unintended consequences and it may complicate future updates or compatibility with other features.

Given your specific needs, here’s what I recommend:

- After detections are made and coordinates are saved in the normalized format, you can write a simple post-processing script to read the `.txt` files and convert the coordinates into pixel values. This approach maintains the integrity of the source code and easily allows you to convert all detections to the desired format.

Remember, when handling small objects, it's also critical to consider the resolution of the input images. Ensure that images are of high enough resolution so that small objects are represented by sufficient pixel detail to be detected reliably.

If there's anything else I can assist you with, please let me know.
