### ISSUE TITLE
How to clone git repo of yolov8 to change it?

### ISSUE THREAD

**Issue by JelluSandro** [ultralytics/ultralytics#6153]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello! I want to use custom albumentations. So I tried to clone ultralytics repo in google colab, but i had error. (I know that I can use pip install but then i can't change model)
here's code:
```
!git clone https://github.com/ultralytics/ultralytics
%cd ultralytics
!pip install -r requirements.txt
!pip install -e .
%cd ..
```
it's end succsefuly. But when I call:
```
import ultralytics
ultralytics.checks()
```
I get:
```
AttributeError                            Traceback (most recent call last)
[<ipython-input-4-2b72cf40a152>](https://localhost:8080/#) in <cell line: 5>()
      3 
      4 import ultralytics
----> 5 ultralytics.checks()

AttributeError: module 'ultralytics' has no attribute 'checks'
```

**Comment by glenn-jocher** [comment]
@JelluSandro hello,

Firstly, thanks for reaching out about your issue with cloning YOLOv8 from the Ultralytics repo. The problem you're facing appears to be because you are trying to call a non-existent function, `checks()`, on the `ultralytics` module after importing it. The 'AttributeError' you're seeing is due to Python not being able to find this function.

Without digging too much into your customization needs, you should know that you generally have authoritative access to the cloned repo and can make any desired changes you might want for your project. To ensure that you properly clone the repo and have it ready for use, it's important to do the following:

1. Clone the Ultralytics YOLOv8 repo directly instead of `ultralytics/ultralytics`.

2. the `pip install -e .` command you've used is generally run from the root of a repository to install it as an editable package. However, the Ultralytics YOLOv8 repo is structured in such a way where it does not need this command after being cloned.

3. After installing the requirements via `pip install -r requirements.txt`, you should be able to access the functions available in the repo.

Let's keep the discussions around this issue going as needed to help you better customize the YOLOv8 model as per your requirements. Don't hesitate to share any additional queries or points that can provide more context behind the changes you're planning. 

Thanks for your interest in contributing to the Ultralytics YOLOv8 repo.

Best Regards,
Glenn Jocher and the Ultralytics Team

**Comment by JelluSandro** [comment]
Thank fro help. I resolve this isue by forking repo

**Comment by glenn-jocher** [comment]
@JelluSandro great to hear that you've resolved the issue by forking the repository! 

Forking is a good way to create a personal copy of the repository where you can implement custom changes, such as integrating albumentations for data augmentation, without affecting the original codebase. Just remember to keep track of updates from the upstream repository to ensure your fork stays up-to-date with any improvements or bug fixes.

If you encounter any other challenges or have questions as you continue to work with YOLOv8, feel free to reach out. We're here to help, and we appreciate your contributions to the community.

Best of luck with your custom implementation!

Warm
