### ISSUE TITLE
ERROR : YOLOV8 requirent "ultralytics.nn.modules.conv" not found

### ISSUE THREAD

**Issue by Gaofan666** [ultralytics/ultralytics#6159]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

I want to  use model = YOLO("path to model as [yolov8s.pt](http://yolov8s.pt/)") to load the model and then predict images using the model.predict() function. Everything works fine when I load the YOLOv8 official [yolov8s.pt] model. However, when I use my own trained model such as [best.pt], I get an error: YOLOV8 requirement "ultralytics.nn.modules.conv" not found, attempting AutoUpdate... ERROR: Could not find a version that satisfies the requirement ultralyticas.nn.modules.conv (from versions none) ERROR: no matching distribution found for ultralytics.nn.modules.conv.

### Environment

Ultralytics YOLOv8.0.196   Python 3.8.16  torch==1.10.1+cu111 (Tesla T4)
Environment terminal
Python 3.8.16
install git
CUDA 11.1

### Minimal Reproducible Example

model = YOLO("weights/best.pt")
model.predict(image)

### Additional

The same code when i use in 3090 graphics , it has the same error with ultralytics version=8.0.104 . But when i update the ultralytics == 8.0.196 , it works well . 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Gaofan666 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by aotutud** [comment]
版本不对，nn包里面后面版本没得modules这个文件，你要去匹配版本

**Comment by aotutud** [comment]
The version is incorrect. The modules file is not included in the later versions of the nn package. You need to match the version

**Comment by glenn-jocher** [comment]
@aotutud it seems you've encountered an issue where there's an inconsistency between the version of the model you're trying to load and the version of the YOLOv8 code you are currently using. This can happen if the model was trained with a different version of the codebase, which might contain different modules or dependencies.

Here's what you can do to resolve this issue:

1. **Version Matching**: Make sure you are using the same version of the YOLOv8 code as was used for training your custom model. You can do this by checking the version in the repository from which the model was trained and ensuring your current environment matches that. 

2. **Update the Code**: If the version of your model is older, consider updating your YOLOv8 code to the same version that your best.pt model was trained on. You can review the release tags to identify the correct version to match with your custom model.

3. **Re-train with Current Version**: If updating to the version your model was trained with is not feasible, the alternative would be to retrain your model using the current version of YOLOv8 you're working with. This ensures compatibility between the model and the code.

If you continue to experience issues, take a look at the changelogs for the YOLOv8 releases to see if there have been any breaking changes introduced since your model was trained. The changelogs can provide guidance on modifications that may need to be made for compatibility.

Thank you for your detailed report, and I hope this helps you proceed with your predictions successfully. If the issue persists, don't hesitate to reach out again, ensuring that all details relevant to reproducing the issue are included.

**Comment by Gaofan666** [comment]
> The version is incorrect. The modules file is not included in the later versions of the nn package. You need to match the version

you are right , i have installed the right ultralytics version and it saved

**Comment by glenn-jocher** [comment]
@Gaofan666 hey there! 👋

Great to hear you've resolved the issue by aligning the Ultralytics version with your model. Remember, version compatibility is key to smooth operations with YOLOv8. If you stumble upon any more hiccups or have further questions, feel free to drop them here. Happy coding! 🚀
