### ISSUE TITLE
CPU RAM Increasing continuously

### ISSUE THREAD

**Issue by gajeshladhar** [ultralytics/ultralytics#617]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Model Training is on CUDA but CPU RAM still increasing continuously while training single epoch and Crashed after exceeding 30GB (System RAM), is there any solution for this or any reason why CPU RAM continuously increasing ?

**Comment by AyushExel** [comment]
This could be a problem related to a memory leak and it is very hard to debug unless we have pinpointed the source. We'll take a look at this as soon as we can cc @glenn-jocher @Laughing-q

**Comment by knoppmyth** [comment]
@gajeshladhar While the Ultralytics team said they would look at this, you really should provide more information, OS, Python version, etc. Does this happen everything you try to train? Are you actively using the system while training is occurring? The more info you provide, the easier it would be to try and find a resolution.

**Comment by bnascimento** [comment]
Ok, I can also see the same pattern, while creating a segmentation model on the largest model here is my cli command

`yolo segment train data=metropolis.yaml model=yolov8x-seg.pt batch=10 epochs=32 imgsz=640 workers=4`

**Comment by glenn-jocher** [comment]
@bnascimento there are no memory issues present. We train our YOLOv8x-seg models over 60 hours on COCO and RAM usage is flat during that time:
<img width="1305" alt="Screenshot 2023-03-17 at 15 49 20" src="https://user-images.githubusercontent.com/26833433/225939122-0628b239-cb32-4b46-ad0a-fa3861f4a018.png">

**Comment by bnascimento** [comment]
hi @glenn-jocher I am witnessing a constant increase on the first epoch at least. our dataset is 350k+ images, and each image with tens of annotations. As a workaround we are keeping the memory in check for now by cutting the dataset in just 100k images. This is not optimal and we are still testing different parameters. On this machine we have only 64GB RAM. 

python3 version 3.8.0
yolo version 8.0.16

I was able to train a model from the largest model on detection. But also witnessed a small steady increase of memory there. However was sufficient to finish the train run. On segmentation this is more noticable and faster.

**Comment by glenn-jocher** [comment]
@bnascimento oh, your ultralytics version is far out of date. Before raising any issues you should make sure it's reproducible in the latest package, currently 8.0.54.

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by bnascimento** [comment]
ok I upgraded yolo to the latest version within my docker container
our current setup is:
```
python3 version 3.8.0
yolo version 8.0.54
cuda 11.7 driver 525.85.05
```
I continue to observe the same behavior, a steady memory increase of ram memory when launching the command:

`yolo segment train data=metropolis.yaml model=yolov8x-seg.pt batch=10 epochs=32 imgsz=640`

![image](https://user-images.githubusercontent.com/3187569/226056859-71bb3e96-f7c2-4171-b911-df6588d738d5.png)

my configuration is for a 20 class model and uses all default configurations for segmentation pipeline.
any hints on what we might turn off to prevent or minimize the memory leakage?

**Comment by glenn-jocher** [comment]
@bnascimento can you reproduce this in the ultralytics/ultralytics:latest Docker image with a default dataset like COCO?

**Comment by bnascimento** [comment]
our docker container is based on ultralytics:latest
will check later with a pure ultralytics:latest and on coco 
for now I was able to size our dataset that it fits between epochs without (barely) exhaust the available memory and discovered that between epochs the memory is almost completely free
see the image 
![image](https://user-images.githubusercontent.com/3187569/226112498-d320a5e2-7a6e-468c-b104-2a9d02ae8766.png)

**Comment by bnascimento** [comment]
another hint, on the last few epochs, I didnt notice that agressive memory leak anymore. Is this related somehow to the mosaic augmentation? I was using default configurations for 30 epochs, so I believe this will shutdown mosaic augmentation on the last 10 epochs.

**Comment by glenn-jocher** [comment]
@bnascimento yes the close_mosaic parameter shuts down mosiac augmentation for the last 10 epochs by default.

**Comment by juanilarregui** [comment]
Hi @glenn-jocher,

I'm experiencing the same behavior for the segmentation task, and unable to reach 10% of my first epoch due to the continuous increase in main memory.

I'm under:
```
python3 == 3.10.6
ultralytics == 8.0.55
Nvidia driver 525.85.05 with CUDA 12.0
Ubuntu 22.04
```

I experienced the same under the following configuration, (then upgraded Ubuntu hoping it would solve this problem but not)
```
python3 == 3.10.6
ultralytics == 8.0.54
Nvidia driver 475 with CUDA 11.4
Ubuntu 20.04
```

I am not using Docker but a fresh `virtualenv` where I just installed `ultralytics` with `pip`.
I'm using a custom dataset, already cached.

**Comment by glenn-jocher** [comment]
@juanilarregui as I showed above segmentation RAM usage does not increase over training. This is 60 hours of training the official YOLOv8-seg models. The first epoch or two may fluctuate but in general if your training crashes then your system is under-resourced and you are asking too much of it, try reducing batch size, model size, image size, etc.
https://github.com/ultralytics/ultralytics/issues/617#issuecomment-1473960596

![image](https://user-images.githubusercontent.com/26833433/226945988-1237b6e2-1378-481d-92fb-3dbae26e49db.png)

**Comment by bnascimento** [comment]
@glenn-jocher surely there is something here that is leaking, we have a few people already with same issues. Is everyone using the albumentations module? 
another question: how to turn off completely any augmentation?

**Comment by glenn-jocher** [comment]
@bnascimento yes our official trainings above use Albumentations. If you can provide a reproducible example in a common environment then we can get started debugging, but since we can not reproduce there is no action we can take.

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by bnascimento** [comment]
for what is worth I got this exception several times after the train run finishes:
`Exception ignored in: <function StorageWeakRef.__del__ at 0x7fa1e37b8dc0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/usr/local/lib/python3.8/dist-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
`

**Comment by pourfard** [comment]
Same problem
64 GB of RAM
Pytorch: 2.0.0
OS: Ubuntu 22.04

Error at 89% of the first epoch.

**Comment by pderrenger** [comment]
@pourfard Regarding the issue with the memory fluctuation, it seems like the memory is being used to store temporary data during training, resulting in the fluctuation you observed. This behavior is normal, and as long as it does not cause a crash, there should be no issue with the training process. If you encounter any problems or errors during training due to memory issues, please don't hesitate to report them, and we will be happy to assist further.
