### ISSUE TITLE
Can you add Dice score for yolov8 Segmentation?

### ISSUE THREAD

**Issue by dy0930** [ultralytics/ultralytics#6172]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Segment tasks needed

### Use case

me and all segmentation reseachers

### Additional

none

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@dy0930 hello!

Thank you for reaching out with your feature request. We are always looking to enhance YOLOv8 and appreciate your initiative to contribute!

Adding the Dice score as a metric for segmentation tasks in YOLOv8 is a great suggestion. Since you're willing to help by submitting a PR, I would advise you to start by forking the repository if you haven't already. Then, you can implement the Dice score computation in the evaluation code for the segmentation tasks.

For reference, the Dice score is a statistical measure of similarity between two sets of data, which is particularly useful for evaluating the performance of binary classification models like those used in segmentation. It is the same as the F1 score, but is often used in the context of segmentation to account for the overlap between the predicted and ground truth masks.

Once you have the implementation ready, please ensure that your code adheres to the existing code structure and style for consistency. After testing it to ensure accuracy and that it integrates well with the existing segmentation metrics, you can then open a pull request so that we can review your contribution.

Your input and potential PR are highly valued, and we are excited to see how such an addition can benefit segmentation researchers using YOLOv8!

Best regards,
Glenn Jocher
