### ISSUE TITLE
The imgsz for inference is different from the Settings

### ISSUE THREAD

**Issue by wsy-yjys** [ultralytics/ultralytics#6192]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

```python
model = YOLO("ultralytics/cfg/models/v8/yolov8-p6_13.yaml")
model.val(data='ultralytics/cfg/datasets/TGRS-trainval_yolo-speed-pc.yaml', batch=1, imgsz=832, save_json=True)
```

I set the imgsz=832 in val mode, but actually the max side real size is 864 ?

![image](https://github.com/ultralytics/ultralytics/assets/78601159/1fad3745-1ede-48fd-b3bc-5733158f9888)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by liuxuanshuang** [comment]
I also discovered this problem. When I set the input image size to 640 ×  640，but the input size for the validation phase is 352 × 672.

**Comment by liuxuanshuang** [comment]
Hello, I have found the answer. https://github.com/ultralytics/ultralytics/pull/5069#issuecomment-1738761802
"yes, validation uses 0.5 stride padding around all sides for slightly improved results, so i.e. 640 size validation would be run at 672 with 16 pixels padding around all edges. val does this but predict does not do this."

**Comment by glenn-jocher** [comment]
@wsy-yjys hello!

Thank you for referencing the related discussion in your message. You're absolutely correct about the behavior you've observed during the validation phase. In YOLOv8, when performing validation we apply a padding strategy that is set to a stride of 0.5 around all sides of the image. This approach is designed to slightly improve results by ensuring that objects at the edge of the frame are more likely to be fully captured in the padded area.

It's important to note that this padding mechanism is specific to the validation phase and is not utilized during prediction. The reason behind this choice is to strike a balance between performance and accuracy during different stages of model usage. While training and validating, we prioritize accuracy, which is why additional steps like padding are taken. During inference (prediction), the primary objective is to achieve optimal performance with the actual image sizes that the model will encounter in real-world scenarios. Hence, the padding strategy employed during validation is not applied during prediction to better reflect how the model will perform in production.

I hope this clarifies the behavior you're experiencing. Should you have any further questions or require additional assistance, please don't hesitate to raise them and we'll be more than happy to help.

Best regards,
Glenn Jocher
