### ISSUE TITLE
Pytorch dataloader problem when training using YOLOv8

### ISSUE THREAD

**Issue by Safouane** [ultralytics/ultralytics#6206]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

Im facing this problem when i train my dataset using YOLOv8,
i tried changing the parameters of the model like the images size, or the number of workers, i also tried different models like yolov8n, yolov8s and yolov8m and i also left it of default but the problem persists.

here is the error messages:

```
---------------------------------------------------------------------------
Empty                                     Traceback (most recent call last)
File C:\ProgramData\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:1132, in _MultiProcessingDataLoaderIter._try_get_data(self, timeout)
   1131 try:
-> 1132     data = self._data_queue.get(timeout=timeout)
   1133     return (True, data)

File C:\ProgramData\anaconda3\Lib\queue.py:179, in Queue.get(self, block, timeout)
    178 if remaining <= 0.0:
--> 179     raise Empty
    180 self.not_empty.wait(remaining)

Empty: 

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
Cell In[14], line 1
----> 1 results = model.train(data='dataset_config.yaml', epochs=500, imgsz=256, workers=2)

File C:\ProgramData\anaconda3\Lib\site-packages\ultralytics\engine\model.py:338, in Model.train(self, trainer, **kwargs)
    336     self.model = self.trainer.model
    337 self.trainer.hub_session = self.session  # attach optional HUB session
--> 338 self.trainer.train()
    339 # Update model and cfg after training
    340 if RANK in (-1, 0):

File C:\ProgramData\anaconda3\Lib\site-packages\ultralytics\engine\trainer.py:190, in BaseTrainer.train(self)
    187         ddp_cleanup(self, str(file))
    189 else:
--> 190     self._do_train(world_size)

File C:\ProgramData\anaconda3\Lib\site-packages\ultralytics\engine\trainer.py:320, in BaseTrainer._do_train(self, world_size)
    318 self.tloss = None
    319 self.optimizer.zero_grad()
--> 320 for i, batch in pbar:
    321     self.run_callbacks('on_train_batch_start')
    322     # Warmup

File C:\ProgramData\anaconda3\Lib\site-packages\tqdm\std.py:1178, in tqdm.__iter__(self)
   1175 time = self._time
   1177 try:
-> 1178     for obj in iterable:
   1179         yield obj
   1180         # Update and possibly print the progressbar.
   1181         # Note: does not call self.update(1) for speed optimisation.

File C:\ProgramData\anaconda3\Lib\site-packages\ultralytics\data\build.py:42, in InfiniteDataLoader.__iter__(self)
     40 """Creates a sampler that repeats indefinitely."""
     41 for _ in range(len(self)):
---> 42     yield next(self.iterator)

File C:\ProgramData\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:630, in _BaseDataLoaderIter.__next__(self)
    627 if self._sampler_iter is None:
    628     # TODO(https://github.com/pytorch/pytorch/issues/76750)
    629     self._reset()  # type: ignore[call-arg]
--> 630 data = self._next_data()
    631 self._num_yielded += 1
    632 if self._dataset_kind == _DatasetKind.Iterable and \
    633         self._IterableDataset_len_called is not None and \
    634         self._num_yielded > self._IterableDataset_len_called:

File C:\ProgramData\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:1328, in _MultiProcessingDataLoaderIter._next_data(self)
   1325     return self._process_data(data)
   1327 assert not self._shutdown and self._tasks_outstanding > 0
-> 1328 idx, data = self._get_data()
   1329 self._tasks_outstanding -= 1
   1330 if self._dataset_kind == _DatasetKind.Iterable:
   1331     # Check for _IterableDatasetStopIteration

File C:\ProgramData\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:1284, in _MultiProcessingDataLoaderIter._get_data(self)
   1282 elif self._pin_memory:
   1283     while self._pin_memory_thread.is_alive():
-> 1284         success, data = self._try_get_data()
   1285         if success:
   1286             return data

File C:\ProgramData\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:1145, in _MultiProcessingDataLoaderIter._try_get_data(self, timeout)
   1143 if len(failed_workers) > 0:
   1144     pids_str = ', '.join(str(w.pid) for w in failed_workers)
-> 1145     raise RuntimeError(f'DataLoader worker (pid(s) {pids_str}) exited unexpectedly') from e
   1146 if isinstance(e, queue.Empty):
   1147     return (False, None)

RuntimeError: DataLoader worker (pid(s) 7296) exited unexpectedly

```

### Environment

```
Ultralytics YOLOv8.0.207  Python-3.11.5 torch-2.1.0+cu121 CUDA:0 (NVIDIA GeForce RTX 2060 with Max-Q Design, 6144MiB)
Setup complete  (16 CPUs, 15.4 GB RAM, 520.1/641.9 GB disk)
```

### Minimal Reproducible Example

```
model = YOLO('yolov8n.yaml')
results = model.train(data='dataset_config.yaml', epochs=500, imgsz=256, workers=2)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Safouane hello,

Thank you for reporting the issue with the dataloader during training with YOLOv8. Based on the error message, it seems that one or more of the dataloader workers have exited unexpectedly, which usually points towards an issue with the dataset or the loading process.

Here are a few steps that you could take to troubleshoot the problem:

1. **Verify Dataset Integrity**: Ensure that your dataset files (images and annotations) are intact and correctly formatted. Sometimes corrupt files or incorrect paths can lead to issues during data loading.

2. **Check DataLoader Arguments**: Since you've already experimented with different numbers of workers, it might help to set `workers` to `0`, which will run the dataloading on the main process and may provide more verbose errors. Keep in mind that this could slow down the loading process.

3. **Resource Limits**: Ensure that your system has enough memory and that the dataset fits comfortably within those limits. If the system is running out of memory, it could cause the workers to crash.

4. **PyTorch and CUDA Versions**: Check if your environment's PyTorch and CUDA versions are compatible with YOLOv8. Misalignment on versions can cause unforeseen errors.

5. **Simplify the Configuration**: If you're using a custom dataset configuration, try running a minimal setup using a well-tested dataset like COCO128 to rule out configuration issues.

6. **Error Replication**: Attempt to replicate the error with a minimal setup. If it consistently occurs at the same point, it could give a clue as to where the problem lies.

7. **Environment Information**: It looks like you are using the latest PyTorch version. Make sure that the other dependencies in your environment align with the versions recommended for YOLOv8.

8. **Error Logging**: Increase the verbosity of logging, if possible, to capture more detailed error messages that could point to the specific cause.

As you mentioned that you've tried different model sizes and image sizes, it does not seem to be a problem with the capacity of the models to handle the data, but rather with the loading or preprocessing of the data itself.

If after trying these steps you still encounter the problem, please ensure that you provide as much detail as possible about the steps you've taken and any new error messages you might receive. This will help us to further diagnose the issue.

Best regards,
Glenn Jocher

**Comment by glenn-jocher** [comment]
Hello @Safouane,

I'm delighted to hear that you've found our previous response comprehensive and that you've made progress in diagnosing the issue related to the dataloader in YOLOv8. It's certainly insightful to learn how certain troubleshooting steps have led you to identify potential causes.

Your rigorous testing and the subsequent discovery that running training through the command line interface (CLI) instead of a Jupyter Notebook produced a successful training session is quite fascinating. This hints at an environment-specific issue that could be related to the way Jupyter Notebook manages processes and memory allocation.

In light of your update, I would suggest a couple more steps to further solidify the training process and avoid future hiccups:

- **Jupyter Environment**: Consider checking whether your Jupyter environment has resource restrictions or is configured differently compared to your CLI environment.
  
- **Memory Profiling**: Since you mentioned that RAM usage spikes to ~98%, you could profile memory usage during the training to ensure that it does not exceed your system's available memory, potentially causing the unexpected worker termination.

- **Verbose Logging**: Regarding increasing verbosity for logging, you might examine the training function or script to find any available parameters that can adjust logging levels. Typically, setting a higher verbosity level can be done through a logging configuration within the script or potentially as a command-line argument.

Lastly, should you decide to continue your training within a Jupyter Notebook and encounter similar issues, ensure that the notebook's kernel has access to sufficient resources. It's worthwhile to evaluate if these resource constraints are specific to the Jupyter kernel you are using.

Your detailed feedback and interaction with the YOLOv8 community provide valuable insight for other users who might be facing similar problems, and it contributes to the ongoing improvement of the project. If any new challenges arise or if you have further updates, we are here to assist and support your endeavors with YOLOv8.

Thank you for contributing to the community with your updates and findings. Your collaborative spirit is greatly appreciated.

Best regards,
(YOLOv8 Support Team)
