### ISSUE TITLE
Resuming Ray Tune experiment

### ISSUE THREAD

**Issue by erminkev1** [ultralytics/ultralytics#6212]
Hello! 

I am a little confused on resuming my RayTune experiment. What happened is that I have interrupted the training while it was running, and now I wanted to resume it, however my attempts are not successful. The error which I get, and which I'll show below, is about the trainable function not being recognized / not existing. However, I've followed suggestions posted in one of the issues here, like #3630 but it did not work.  

My code is as follows, where I slightly modified the save paths to accommodate the particular model I am training with

```
experiment_path = '~/M/_tune_2023-11-08_23-08-55'
restored_tuner = tune.Tuner.restore(experiment_path, trainable="_tune")
restored_tuner.fit()
```

Nonetheless, after running the code I get an error: 

```
Traceback (most recent call last):
  File "/home/itl/.local/lib/python3.8/site-packages/ray/tune/tuner.py", line 372, in fit
    return self._local_tuner.fit()
  File "/home/itl/.local/lib/python3.8/site-packages/ray/tune/impl/tuner_internal.py", line 587, in fit
    analysis = self._fit_resume(trainable, param_space)
  File "/home/itl/.local/lib/python3.8/site-packages/ray/tune/impl/tuner_internal.py", line 730, in _fit_resume
    **self._get_tune_run_arguments(trainable),
  File "/home/itl/.local/lib/python3.8/site-packages/ray/tune/impl/tuner_internal.py", line 655, in _get_tune_run_arguments
    if is_function_trainable(trainable):
  File "/home/itl/.local/lib/python3.8/site-packages/ray/tune/registry.py", line 68, in is_function_trainable
    trainable = get_trainable_cls(trainable)
  File "/home/itl/.local/lib/python3.8/site-packages/ray/tune/registry.py", line 46, in get_trainable_cls
    validate_trainable(trainable_name)
  File "/home/itl/.local/lib/python3.8/site-packages/ray/tune/registry.py", line 57, in validate_trainable
    raise TuneError("Unknown trainable: " + trainable_name)
ray.tune.error.TuneError: Unknown trainable: _tune

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/itl/Desktop/SAMSON/Python/misc/resume_tuner.py", line 23, in <module>
    restored_tuner.fit()
  File "/home/itl/.local/lib/python3.8/site-packages/ray/tune/tuner.py", line 374, in fit
    raise TuneError(
ray.tune.error.TuneError: The Ray Tune run failed. Please inspect the previous error messages for a cause. After fixing the issue, you can restart the run from scratch or continue this run. To continue this run, you can use `tuner = Tuner.restore("None", trainable=...)`.


```

How come that the trainable "_tune" does not exist? Is it possible that a trainable under a different name is registered somewhere, and so that inside _registry.py_ in _validate_trainable_ function, it throws an error? 

I hope anyone can help out with this.

Best,
E

**Comment by youyinnn** [comment]
I managed to enable it by commenting out the smart inference mode:

https://github.com/ultralytics/ultralytics/blob/795b95bdcb22d788c1a062b47d1fe871d768c806/ultralytics/engine/predictor.py#L226

Any consequences of that?

**Comment by glenn-jocher** [comment]
@youyinnn hello E,

Thank you for reaching out and providing a detailed description of the issue you're encountering with resuming your RayTune experiment in YOLOv8.

From the error message you're seeing, it sounds like there may be a misunderstanding regarding the `trainable` function name when attempting to resume your experiment. The `trainable` argument in the `Tune.Tuner.restore()` method should correspond to a function or class name that Ray Tune recognizes as your training operation. If this is not correctly specified, Ray Tune will not know how to resume the training process.

In your case, `"_tune"` seems to be passed as a placeholder for the actual `trainable` which should be the function or class containing your training logic. This function or class name should have been defined by you before starting the original experiment and should be available in the namespace when trying to resume the training.

Please ensure that the `trainable` parameter you pass to `Tune.Tuner.restore()` matches the name of the original training function or class you used. Moreover, make sure that this function or class is properly defined and imported in the script you're using to resume your experiment. If you're using a pre-defined trainable provided by YOLOv8, ensure that it's correctly referenced and that all necessary modules are imported in your current script.

After you've verified and corrected the `trainable` function or class name, try resuming the experiment again. If you continue to experience issues, verifying paths and checking for typos could also help you move forward.

I hope this helps you resolve the issue, and you can get back to training without further interruptions.

Best regards,
The YOLOv8 Support Team

**Comment by erminkev1** [comment]
Hi! 

Thank you for your quick response. 

I do understand that the "_tune" is indeed a placeholder for the actual trainable, however as you mentioned in [this](https://github.com/ultralytics/ultralytics/issues/3630#issuecomment-1631783019) thread, this should be the case if we want to continue the training process. 

Even though your suggestion worked for some, it does not seem to be working for me. 

If I don't put "_tune" as a trainable, but rather something else, then the error output is something along the lines of "expected input "_tune" but received "_some_input_". 

I did change internally the absolute path to which the results are saved, and I am thinking that this had somehow messed with the way the _restore_ method of the Tuner class resolves the name of the trainable. 

I hope I made further clarifications on this problem.

Best,
Ermin

**Comment by glenn-jocher** [comment]
@erminkev1 hi Ermin,

Thank you for providing further details on the issue you're experiencing with resuming your training process in YOLOv8. It sounds like you're encountering a naming mismatch error when attempting to use the restoration method.

From what you've described, it seems like there could be a discrepancy between what the restoration method expects and the actual name that your training function or class has. The key is to ensure that the name of the trainable during the restoration exactly matches the name used during the initial setup of the original experiment.

The fact that changing the save path has led to issues suggests that there may have been changes in the environment or the way your trainable is being referenced. It's crucial that all references and naming conventions remain consistent throughout the training and restoration process to avoid such conflicts.

Your proactive step in printing out the trainable name in the tuner module and finding "_tune" indicates that the internal name might indeed be set to that. However, you need to verify that this internal name is also being referenced consistently when attempting to resume the experiment.

Since each experiment's configuration could be unique, and without the ability to provide direct code snippets or modification, my suggestion would be to review the initial experiment setup and ensure that all naming conventions, save paths, and references in your restoration attempt are in alignment with that configuration. It might also help to revisit the documentation specific to the restoration mechanism in YOLOv8 to ensure no steps were missed or incorrectly implemented.

I hope these insights assist you in troubleshooting the issue. Remember, consistent naming and paths are key to a seamless restore process.

Best regards,
The YOLOv8 Support Team

**Comment by erminkev1** [comment]
Hi,

Thank you for your response.

I want to refer to part of your comment "_However, you need to verify that this internal name is also being referenced consistently when attempting to resume the experiment._". May you please provide some directions for this?

Best,
Ermin

**Comment by glenn-jocher** [comment]
@erminkev1 hi Ermin,

Certainly! To ensure that the internal name of your trainable is being referenced consistently when attempting to resume the experiment, you should verify the following:

1. **Original Experiment Creation**: When you created the original experiment with Ray Tune, you defined a trainable function or class that encapsulates your model's training logic. Make sure to identify this exact name as it was originally defined.

2. **Consistency in Codebase**: Ensure that your codebase, including any modules or scripts that were used to define the trainable, hasn't been modified in a way that would alter the name or accessibility of the trainable.

3. **Python Environment**: Check that you're executing the resume operation in the same Python environment and working directory where the original experiment was run. Any discrepancies here can lead to the trainable function or class not being found.

4. **Restoration Invocation**: In your restoration code, you are using `Tune.Tuner.restore()`. Ensure that the `trainable` argument passed to this function matches the original trainable name exactly. If the original was a function named `train_model`, for example, then `trainable="train_model"` should be used.

5. **Path to Checkpoint**: Verify that the `experiment_path` you are providing points directly to the correct checkpoint directory from your original training run. It must match the directory structure and naming convention used when the checkpoint was created.

6. **Internal State**: Before invoking `restored_tuner.fit()`, print or log the state of the `restored_tuner` to verify that it has loaded the correct trainable and checkpoint information.

If you have renamed or moved any scripts or functions since the initial training, you should revert those changes or update the references accordingly. The objective is to make the training environment for resuming the experiment as close as possible to the environment when the original experiment was performed.

By following these suggestions, you can often resolve conflicts that might arise from changes in naming conventions or the environment.

Best,
The YOLOv8 Support Team

**Comment by erminkev1** [comment]
The functionality to resume training a _tuned_ experiment is not provided out of the box unfortunately. However, there are some workarounds if you mess with the way models are initialized. Trainable _tune_ will always startup a new model unless we specify to load it from a checkpoint, but a "tune"

**Comment by glenn-jocher** [comment]
@erminkev1 hello Ermin,

It seems your message may have been cut off at the end. I understand that you're tackling the complexities associated with resuming a Ray Tune experiment and dealing with the initialization of models from checkpoints when using YOLOv8.

When working with the Ray Tune library to resume hyperparameter tuning or training processes, it indeed requires careful setup to ensure that models are correctly initialized from saved checkpoints rather than starting anew. Here are some general steps you should follow to enable resuming an experiment properly:

1. **Define a Checkpoint Strategy**: Ensure that during the initial training process, your trainable function or class implements an appropriate checkpointing strategy that saves model state after a certain number of iterations or upon specific conditions.

2. **Checkpoint Accessibility**: Verify the checkpoints are being saved to a known and accessible directory. Ray Tune should automatically manage this, but it’s worth confirming.

3. **Checkpoint Loading Logic**: Your trainable definition should include logic that checks for the existence of a checkpoint file at the beginning of training and appropriately loads the model state from this checkpoint if it exists.

4. **Trainable Modification (if needed)**: If you require modifying the trainable to incorporate loading from checkpoints, ensure to reference this modified version when resuming the tuning. Remember to register this modified trainable with Ray Tune if necessary.

5. **Specify Correct Trainable**: When you resume the training process with the `Tuner.restore()` method, the `trainable` parameter should be the same callable that was used in the original experiment, with any modification for checkpoint loading fully integrated.

6. **Experiment Configuration**: Confirm that your experiment configuration when resuming (e.g., hyperparameter values, dataset paths, etc.) is in line with the originally intended setup. Consistency is crucial for a successful resume.

Keep these factors in mind when working through the fine details of resumption, as they can help bridge the gap between starting a fresh training process and picking up where you left off in a previous session. If the issue persists, reviewing the Ray Tune documentation or reaching out to their support community might provide some additional specific guidance for their system.

Please carefully integrate the above considerations into your current workflow, reviewing any necessary documentation to ensure everything aligns with best practices for using Ray Tune with YOLOv8.

**Comment by UltralyticsAssistant** [comment]
A potential fix for this issue has been merged in [PR #20037](https://github.com/ultralytics/ultralytics/pull/20037). This update introduces exciting new functionality and improvements, including the ability to resume interrupted hyperparameter tuning sessions with the new `resume=True` option in `model.tune()`. This works seamlessly for both standard and Ray Tune workflows, helping save time and resources by continuing from the last interrupted session instead of starting over. The PR also includes updated documentation and internal logic enhancements to support this feature. 

Credit goes to @Y-T-G for the implementation and @glenn-jocher for contributions to this update. The version has been bumped to `8.3.103`, so you can test these changes by updating to the latest version with:

```
pip install -U ultralytics>=8.3.103
```

Alternatively, you can install directly from the main branch:

```
pip install git+https://github.com/ultralytics/ultralytics.git@main
```

Feel free to test and let us know if this resolves the issue for you. If the issue persists or you encounter any other challenges, additional feedback is always welcome. Thank you 🙏 for bringing this to our attention and helping improve Ultralytics!

**Comment by mattiasmar** [comment]
@glenn-jocher @UltralyticsAssistant I think the documentation https://docs.ultralytics.com/integrations/ray-tune/#resuming-an-interrupted-hyperparameter-tuning-session-with-ray-tune must be updated according to [PR #20027 ](https://github.com/ultralytics/ultralytics/pull/20037)

Currently the documentation says "restored_tuner = tune.Tuner.restore(experiment_path, trainable=train_mnist)" rather than demonstrating the resume feature.

**Comment by Y-T-G** [comment]
The docs does show how to use `resume` in the same section you linked.

![Image](https://github.com/user-attachments/assets/ff8257cf-f417-4e9c-a4f3-d865fd1d7255)
