### ISSUE TITLE
YOLOv8 can't use the specified GPU

### ISSUE THREAD

**Issue by Sijiahui** [ultralytics/ultralytics#6220]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I have 8 gpu in my Server and I can train my examples in Single-GPU or Multi-GPU.

However, I cannot use the specified Single-GPU to train.It only run in the number 0 GPU no matter which GPU I choose.

train.py is below
```
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.pt')  # load a pretrained model (recommended for training)

# Train the model with 2 GPUs
results = model.train(data='coco128.yaml', epochs=100, imgsz=640, device=[1])
```
In the terminal,I can see the correct print.
```
Ultralytics YOLOv8.0.164 🚀 Python-3.8.18 torch-1.13.0+cu117 CUDA:1 (NVIDIA A100-SXM4-40GB, 40337MiB)
```
In the nvidia-smi,number 0 GPU only occupy.
```

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  On   | 00000000:07:00.0 Off |                    0 |
| N/A   38C    P0   165W / 400W |  26796MiB / 40960MiB |     51%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM...  On   | 00000000:0F:00.0 Off |                    0 |
| N/A   26C    P0    50W / 400W |      2MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM...  On   | 00000000:47:00.0 Off |                    0 |
| N/A   30C    P0    75W / 400W | 34188MiB / 40960MiB |    0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM...  On   | 00000000:4E:00.0 Off |                    0 |
| N/A   28C    P0    58W / 400W |   3920MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA A100-SXM...  On   | 00000000:87:00.0 Off |                    0 |
| N/A   38C    P0    63W / 400W |   3896MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   5  NVIDIA A100-SXM...  On   | 00000000:90:00.0 Off |                    0 |
| N/A   35C    P0    82W / 400W |   34188MiB / 40960MiB |    0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   6  NVIDIA A100-SXM...  On   | 00000000:B7:00.0 Off |                    0 |
| N/A   33C    P0    57W / 400W |  34188MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   7  NVIDIA A100-SXM...  On   | 00000000:BD:00.0 Off |                    0 |
| N/A   31C    P0    61W / 400W |  31666MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

```

### Environment

Ultralytics YOLOv8.0.188  Python-3.8.18 torch-1.13.0+cu117 CUDA:1 (NVIDIA A100-SXM4-40GB, 40337MiB)
Setup complete  (8 CPUs, 64 GB RAM, 4.8/10 TB disk)

### Minimal Reproducible Example

```
# Load a model
model = YOLO('yolov8n.pt')  # load a pretrained model (recommended for training)

# Train the model with 2 GPUs
results = model.train(data='coco128.yaml', epochs=100, imgsz=640, device=[1])
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Sijiahui hello! Thank you for bringing this issue to our attention. It seems you're experiencing a problem where YOLOv8 is defaulting to GPU 0 despite specifying a different GPU for training.

It's important to ensure that the environment variables related to CUDA device selection are set correctly. When specifying the GPU device in the training script, as you have done with `device=[1]`, YOLOv8 should be directing computations to the designated GPU. However, if another process is overriding this selection or if there is an issue within the YOLOv8 handling of device selection, it would explain why you're seeing activity only on GPU 0.

First, I would suggest checking your environment setup to ensure that no other configurations are forcing the use of GPU 0. Additionally, make sure that there are no other scripts or user profiles that might be setting CUDA_VISIBLE_DEVICES or other similar variables that would affect your GPU selection.

If you confirm that the issue is not related to the environment setup, there might be an underlying issue in the device allocation logic within YOLOv8 that we need to investigate. In that case, getting the complete logs and any additional information you can provide about your environment would be helpful for troubleshooting. Please provide any error messages or warnings you receive during the training attempt. It will also be valuable to understand whether you've successfully run other models or frameworks on your specified GPU to rule out potential hardware or driver issues.

We take such issues seriously as they affect the model training experience, and we aim to resolve them promptly. We appreciate your contribution to improving YOLOv8, and once we have more information, we'll be in a better position to address the problem. If the issue persists and requires deeper investigation, filing a detailed bug report or looking into any open issues that might be related to GPU selection would be the next steps.

Thank you for your patience and cooperation. Your efforts help us make YOLOv8 more robust and user-friendly.

**Comment by dmjtian** [comment]
I have same issues.


Transferred 317/390 items from pretrained weights
New https://pypi.org/project/ultralytics/8.0.208 available 😃 Update with 'pip install -U ultralytics'
cfg file passed. Overriding default params with hyp.yaml.
Ultralytics YOLOv8.0.114 🚀 Python-3.8.10 torch-2.0.1+cu117 【CUDA:2】(NVIDIA GeForce RTX 3090, 24260MiB)

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 174.00 MiB (【GPU 0】; 23.69 GiB total capacity; 4.77 GiB already allocated; 37.00 MiB free; 5.21 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by folkien** [comment]
This is still an issue. First of all after model creation we need to move it directly to second GPU 

```python
model = YOLO(self.weights_path, verbose=False, task=self.task)
model.to(self.device)
```

But it's only part of the problem. Second part is that inference should also use `tensor` because parameter `device` doesn't do anything.

```python
        results = self.net.predict(
            imgsz=self.network_size,
            source=frames,
            conf=self.min_confidence,
            iou=self.nms_threshold,
            device="cuda:1",
            half=self.half_precision,
            verbose=False,
        )
```

@glenn-jocher guys please fix this issue

Tested on

```
ultralytics==8.3.197
ultralytics-thop==2.0.17
```

Edit : Everything works when we use `torch.device` as an argument `device` for detection. Using torch device skips your device string parsing which is entirely broken to be honest and have wrong assumptions with env variables settings also XD.

**Comment by glenn-jocher** [comment]
Thanks for the detailed notes. Passing a `torch.device` is supported and a good interim workaround; please open a new issue (this thread is closed/stale) with: 1) `yolo checks` output, 2) a full text traceback, and 3) a minimal script (<20 lines) that reproduces the behavior. As a quick test, also try an int for single‑GPU selection (`device=1`) or upgrade to the latest Ultralytics YOLO (YOLO11), which includes recent device‑selection improvements. Reference: the `device` argument is handled by `select_device` and accepts `str`, `int`, list, or `torch.device` as documented in the [select_device reference](https://docs.ultralytics.com/reference/utils/torch_utils/#select_device) and shown in the [Train mode examples](https://docs.ultralytics.com/modes/train/). 

Example:
```python
from ultralytics import YOLO
import torch

model = YOLO("yolo11n.pt")
model.train(data="coco8.yaml", device=torch.device("cuda:1"))
model.predict(source="path/to/image.jpg", device=torch.device("cuda:1"))
```
If you recently upgraded in a notebook, please restart the kernel and re-run.
