### ISSUE TITLE
Add nuImages (by Motional) Detect Dataset

### ISSUE THREAD

**Issue by tensorturtle** [ultralytics/ultralytics#6222]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hi, I would like to contribute [nuImages by nuScenes](https://www.nuscenes.org/nuimages) Detection dataset. nuImages consists of still images taken from a six-camera data collection car on the streets of Asian and American cities. It has 693,783 annotations across 93,000 images. The images are 15.3GB.

I finished implementing the required conversion script at [tensorturtle/yolov8-on-nuimages](https://github.com/tensorturtle/yolov8-on-nuimages)

If someone could give me some specific pointers on editing the docs and relevant code, I would be willing to add this nuImages support upstream.

Thank you @glenn-jocher and the community for everything.

### Use case

nuImages is a rich dataset that is used for ADAS / self-driving research. Adding this dataset officially to YOLOv8 would enable users to start with much stronger baselines for urban mobility / transportation applications.

### Additional

Note that nuImages requires you to sign in to their web portal and get an account in order to download the dataset. Therefore I'm not able to provide a simple script to download it.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
Hello @tensorturtle,

Thanks for reaching out and for your willingness to contribute to the Ultralytics YOLOv8 project! It's great to see community members eager to expand the capabilities of the repository by supporting new datasets like nuImages by nuScenes. Your contribution can certainly help enrich the dataset variety used for detection tasks within the YOLOv8 framework.

To integrate nuImages into YOLOv8, you will need to create a new dataset loader that processes the nuImages files and annotations into a format that YOLOv8 can understand during training and evaluation. To achieve this, you would follow these general steps:

1. Fork the YOLOv8 repository, if you haven't already done so.
2. Develop a data-loading script that can process the nuImages annotations and convert them into a compatible format for YOLOv8, ensuring that you handle multi-camera images appropriately if required.
3. Create a dataset configuration file that outlines the paths, classes, and any splitting of training and validation data specific to nuImages.
4. Modify the documentation to include instructions and descriptions regarding how users can use the nuImages dataset with YOLOv8.
5. Make sure your implementation aligns with the current project structure and coding style for consistency.
6. Test the data loader thoroughly to ensure it works correctly with the YOLOv8 training pipeline and that it handles edge cases well.
7. Once you are confident in your implementation, submit a pull request to the Ultralytics YOLOv8 repository with a clear description of your changes, how to use them, and any implications, such as handling dataset downloading restrictions.

We appreciate your note regarding the requirement for a user account to download nuImages. For this reason, it's important to clearly document the steps a user should take to acquire the dataset themselves, as automated download scripts won't be applicable due to the login requirement.

Your pull request will be reviewed by our maintainers, and they might request changes or provide further instructions. Be sure to engage with any feedback to ensure a smooth integration process.

Once again, thank you for your initiative, and we look forward to seeing your pull request! Your efforts help enhance the YOLOv8 project and its applications in real-world scenarios.

Happy coding!

Best regards,
Glenn Jocher and the Ultralytics Team
