### ISSUE TITLE
NaN training on a specific environment

### ISSUE THREAD

**Issue by thhart** [ultralytics/ultralytics#623]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

I have two systems with different GPU hardware and different base system, one for development and one for training. On the development system the training is not working as it gives NaN values in the scalars. I tried to setup both the same with clean pip and everything however since both are different Ubuntu versions there are differences for sure. Both use the same dataset of course which contains no errors.
I also checked out latest ultralytics version from github and used the setup from there as recommended in the docs. I am aware there are a lot of possibilities to mess up however I want to offer kind of testing what might be wrong in the dev system. Inference is working same on both.
I can train somehow, so I am ok, however if ultralytics is interested please let me know what I should check/change in the dev system?
Additional question: How to force to use CPU for training, so I can test this as well?

<pre>
Starting training for 64 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/64      2.51G        nan        nan        nan         31        768:   5%|▌         | 14/264 [00:45<13:04,  3.14s/it]
</pre>

### Environment

System 1 (Development, training not working)
- Ultralytics YOLOv8.0.18 🚀 Python-3.10.9 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce GTX 1650, 3904MiB)
- Ubuntu 22.04

System 2 (Training, training ok)
- Ultralytics YOLOv8.0.18 🚀 Python-3.8.10 torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce GTX 1070, 8109MiB)
- Ubuntu 20.04

### Minimal Reproducible Example

Training script:

```
from ultralytics import YOLO
model = YOLO("./yolov8m.pt")
results = model.train(data="./data.yaml", epochs=64, batch=4, imgsz=768)
model.val()
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by thhart** [comment]
I tested this on CPU now and here the training works, it looks like it is related to the GPU really. (NVIDIA GeForce GTX 1650, 3904MiB)

**Comment by thhart** [comment]
Closing this due to possible duplicate:
https://github.com/ultralytics/ultralytics/issues/280
https://github.com/ultralytics/yolov5/issues/7908

**Comment by netbrain** [comment]
Had the same issue on two machines, one with `Geforce GTX 1650 Ti Mobile `and one with `Gefore GTX 1650`

Managed to solve it on one of the machines by downgrading to cuda 10.2 using.

`pip install torch==1.12.1+cu102 torchvision==0.13.1+cu102 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu102`

Also installed cuda 10.2 locally on the machine, but it seems that pytorch uses it's own embedded deps for cuda? so not sure if that played a role. :shrug:

**Comment by MathewsJosh** [comment]
For me, training only works with `pip install torch==1.10.2+cu102 torchvision==0.11.3+cu102 torchaudio==0.10.2 --extra-index-url https://download.pytorch.org/whl/cu102` in windows with GTX1660 TI 6GB and Ultralytics 8.0.55.
But this warning keeps showing:
`C:\Users\me\Anaconda3\lib\site-packages\torchvision\io\image.py:11: UserWarning: Failed to load image Python extension: Could not find module 'C:\Users\teued\Anaconda3\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.`

**Comment by pderrenger** [comment]
@MathewsJosh it's great to hear that you were able to resolve the training issue on one of your machines by downgrading to CUDA 10.2. This is a common approach to address compatibility issues between PyTorch and specific GPU architectures.

As for the warning you mentioned, it seems to be related to the Python extension module for loading images in torchvision. This warning typically indicates a potential issue with the installation or configuration of the torchvision package.

The message suggests that the image Python extension module could not be loaded due to a missing dependency or incorrect path. One potential solution to this warning is to ensure that your torchvision installation is complete and correctly configured. You might also want to verify that the required dependencies are installed and accessible.

If you continue to encounter this warning, you might consider checking the paths and dependencies related to the torchvision package and verify their integrity.

If you need further assistance with this issue, feel free to provide additional details, and I'd be happy to help you troubleshoot further.
