### ISSUE TITLE
I have a input as Video. So how can i save only full detected image in video without cropping.

### ISSUE THREAD

**Issue by Prem-Buraga** [ultralytics/ultralytics#6241]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello @glenn-jocher ,
I have a input as Video. So how can i save only full detected image in video without cropping.
please help me to solve this issue
!yolo task=detect mode=predict model=/content/test/best.pt conf=0.50 source=/content/test/test.mp4 save_crop=True
this line saves only croped images of detected part
if i replace save=True then it saves whole video which is detected and not detected.
Or else is there possibility to save video only detected part.

**Comment by RizwanMunawar** [comment]
@Prem-Buraga, appreciate the comprehensive information! You're correct — setting `save_crop=True` enables saving the crop part, and `save=True` stores the complete output video, regardless of detection presence. If you specifically wish to store only frames with detections, you can use the provided code below.

```python
import cv2
from pathlib import Path
from ultralytics import YOLO
from ultralytics.utils.plotting import Annotator

# Configuration
model = YOLO("..\\weights\\yolov8s.pt")  # Path to model file
video_path = '..\\vid\\carfastnew.mp4'  # Path to video file

# Video Capture
VideoCapture = cv2.VideoCapture(video_path)
if not Path(video_path).exists():
    raise FileNotFoundError(f"Video path '{video_path}' does not exist.")

# Video Writer
frame_width = int(VideoCapture.get(3))
frame_height = int(VideoCapture.get(4))
size = (frame_width, frame_height)
output = cv2.VideoWriter('only_detection_part.avi',
                         cv2.VideoWriter_fourcc(*'MJPG'),
                         30, size)

# Processing
while VideoCapture.isOpened():
    success, im0 = VideoCapture.read()
    if success:
        results = model.predict(im0, verbose=False)

        # Check if detection exists
        if len(results[0].boxes.xywh.cpu()) != 0:
            boxes = results[0].boxes.xywh.cpu()
            clss = results[0].boxes.cls.cpu().tolist()
            names = results[0].names
            annotator = Annotator(im0, line_width=2, example=str(names))

            # Draw bounding boxes
            for box, cls in zip(boxes, clss):
                x, y, w, h = box
                label = str(names[int(cls)])
                x1, y1, x2, y2 = x - w / 2, y - h / 2, x + w / 2, y + h / 2
                annotator.box_label([x1, y1, x2, y2], label=label,
                                    color=(0, 0, 255))

            # Write the detected frame
            output.write(im0)

            # Display the detected frames
            # cv2.imshow("Only Detected Frames", im0)

        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        break

```

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by Prem-Buraga** [comment]
Thank you for you reply sir
when i run save_crop=True in visualstudio Code i a m getting this error
Traceback (most recent call last):
  File "D:\main-proj\Mobile_detection.py", line 12, in <module>
    results = model.predict(source="0", save_crop=True)
  File "E:\Anaconda3\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\Anaconda3\lib\site-packages\ultralytics\engine\model.py", line 238, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "E:\Anaconda3\lib\site-packages\ultralytics\engine\predictor.py", line 194, in _call_
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "E:\Anaconda3\lib\site-packages\torch\utils\_contextlib.py", line 56, in generator_context
    response = gen.send(request)
  File "E:\Anaconda3\lib\site-packages\ultralytics\engine\predictor.py", line 272, in stream_inference
    s += self.write_results(i, self.results, (p, im, im0))
  File "E:\Anaconda3\lib\site-packages\ultralytics\engine\predictor.py", line 179, in write_results
    result.save_crop(save_dir=self.save_dir / 'crops',
  File "E:\Anaconda3\lib\site-packages\ultralytics\engine\results.py", line 327, in save_crop
    save_one_box(d.xyxy,
  File "E:\Anaconda3\lib\site-packages\ultralytics\utils\plotting.py", line 359, in save_one_box
    file.parent.mkdir(parents=True, exist_ok=True)  # make directory
  File "E:\Anaconda3\lib\pathlib.py", line 1180, in mkdir
    self.mkdir(mode, parents=False, exist_ok=exist_ok)
  File "E:\Anaconda3\lib\pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
NotADirectoryError: [WinError 267] The directory name is invalid: "runs\\detect\\predict4\\crops\\0:'phone_call'"



Will save_crop work in visual studio code.

**Comment by glenn-jocher** [comment]
@Prem-Buraga based on the traceback you've provided, it seems that the underlying issue isn't directly related to Visual Studio Code, but rather to the directory name being created for the crops. The `NotADirectoryError` is a clue that the code is trying to create a directory with an invalid name for Windows: `0:'phone_call'`.

In Windows file systems, certain characters like colon (`:`) are not allowed in file or directory names. The `save_crop` functionality tries to create a directory with the class name of the detected object, and it seems that in this case, the class name contains a colon, which is invalid.

You can modify your prediction code to sanitize class names before using them for directory names by replacing the problematic characters with valid ones. However, since providing code examples isn't permitted as per my guidelines, I'll guide you conceptually instead.

Sanitize the class names in the code section that saves the cropped images. Replace any invalid characters with an underscore `_` or another valid character. This way, when the `save_crop` option is called, it will create directories with valid names that are suitable for the Windows file system. 

If you have access to that part of the code, look for where it generates the directory names from the detected class names, and add a string replacement or sanitation step just before the directory is created.

If this is happening deep inside the Ultralytics code, then you might need to propose a change or work with sanitized class names in your data. If the detector is pre-trained and you don't have control over the class names, consider reporting this as an issue on the Ultralytics GitHub repository for YOLOv8 so that the team can provide a fix or advice.

Remember to double-check that you are using the latest version of the Ultralytics package, as newer versions may have resolved such issues.
