### ISSUE TITLE
How can i change the default logger of ultralytics?

### ISSUE THREAD

**Issue by Sunhill666** [ultralytics/ultralytics#6243]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I‘m tring to change the default logger of ultralytics using this code below:

```python
class InterceptHandler(logging.Handler):
    def emit(self, record: logging.LogRecord) -> None:
        # Get corresponding Loguru level if it exists.
        level: str | int
        try:
            level = logger.level(record.levelname).name
        except ValueError:
            level = record.levelno

        # Find caller from where originated the logged message.
        frame, depth = inspect.currentframe(), 0
        while frame and (depth == 0 or frame.f_code.co_filename == logging.__file__):
            frame = frame.f_back
            depth += 1

        logger.opt(depth=depth, exception=record.exc_info).log(level, record.getMessage())
```

but this is not woring:

```text
0: 384x640 4 persons, 9 chairs, 13.6ms
Speed: 2.1ms preprocess, 13.6ms inference, 3.8ms postprocess per image at shape (1, 3, 384, 640)
2023-11-10 14:25:18.088 | DEBUG    | __main__:run:120 - read_time: 2 ms, process_time: 35 ms, display_time: 2 ms.
2023-11-10 14:25:18.101 | INFO     | __main__:run:125 - Waiting for ffmpeg process
2023-11-10 14:25:18.101 | INFO     | __main__:run:127 - Done
```

so, is there a way to change default logger? Thx.

**Comment by glenn-jocher** [comment]
@Sunhill666 hello! It looks like you're trying to integrate a custom logger with the YOLOv8 repository. The YOLOv8 codebase uses Python's built-in `logging` library. If you want to change the logging behavior, you'll need to configure the logging inside the YOLOv8 code.

To integrate a different logging system, such as `loguru`, you would need to intercept logging messages from the `logging` library and reroute them to your preferred logger. The code snippet you've posted seems to be an attempt at doing this by creating a custom handler that forwards `logging` records to `loguru`. 

However, for this to work, you would need to attach the `InterceptHandler` to the root logger or the specific logger you intend to intercept within the YOLOv8 codebase. Make sure you replace or add the handler at the beginning of your script or application before any logging activities start.

Remember to also remove any existing handlers attached to the root logger if you're intercepting all logs. This can be done with something like `logging.root.handlers = []` before adding your custom `InterceptHandler`. You could place your configuration code in the main script or the `__init__.py` of the YOLOv8 module, depending on when you need the logger to start capturing logs.

Keep in mind that altering the logging infrastructure can have unintended side effects if not done carefully, especially in a complex codebase like that of YOLOv8. Ensure you thoroughly test your modifications.

For comprehensive information on how to configure the logger in Python, please refer to the official Python logging documentation. If further help is needed, consider posting a discussion on the repository so that the community can provide additional input.

**Comment by Sunhill666** [comment]
@glenn-jocher Thank you for your comment, i'll trying to figure out this.

**Comment by glenn-jocher** [comment]
@Sunhill666 you're welcome! If you encounter any further issues or have questions as you work through the configuration, feel free to raise them in the discussions section on the repository. The community and the Ultralytics team are there to help out. Good luck with your logging setup!
