### ISSUE TITLE
Setup.py install vs pip install -e .

### ISSUE THREAD

**Issue by alvinwong64** [ultralytics/ultralytics#6266]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi there, I am currently trying to modify yolov8 in it's structure and perform some custom training for research purposes. After some searching, I found out there are 2 ways suggested by yolov8 team which are:

under ultralytics git cloned folder:
pip install -e .

or

python setup.py install

To my understanding, when doing the pip install method, supposingly any modification made to the ultralytics folder should be able to reflect, yet when everytime i run it, it always have error
eg: i created a new yaml file under cfg\dataset, yet it fails to recognise the yaml file and prompting yaml file not found

After some troubleshooting, i ran python setup.py install, now it able to runs everything smoothly

Question is, so now i have to run setup.py everytime when i made some modification? Or i mess something up when setting it up for developer mode?

Thank for the help, happy to provide more info if needed.

**Comment by alvinwong64** [comment]
Thanks for the clarification,, very helpful, hope you have a nice day!

**Comment by glenn-jocher** [comment]
You're welcome, @alvinwong64! If you have any more questions or run into further issues, feel free to reach out. Happy coding, and I hope your project goes well!

**Comment by Sachi9soni** [comment]
>hello ,
i am working with deepstream+yolo in this directory::::::::::https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/docs/YOLOv8.md

but i found out that setup.py and requirements.txt is missing from ultraltyics folder , 
so should i need to work with  pyproject.toml?
how to use that?

**Comment by glenn-jocher** [comment]
@Sachi9soni hi there! 👋

It looks like you're diving into integrating YOLOv8 with DeepStream - that's exciting! Regarding the `setup.py` and `requirements.txt` files, YOLOv8 and many modern Python projects have transitioned to using `pyproject.toml` for project setup and dependency management. It's part of the [PEP 517](https://www.python.org/dev/peps/pep-0517/) and [PEP 518](https://www.python.org/dev/peps/pep-0518/) standards.

To work with `pyproject.toml`, you can use `pip` (version 19.0 or newer) to install the project directly. Navigate to the cloned repository's root directory and run:

```bash
pip install .
```

This command tells `pip` to install the project along with its dependencies as specified in `pyproject.toml`. If you're developing and want your changes to be immediately reflected, you can install it in editable mode:

```bash
pip install -e .
```

This approach should get you set up with YOLOv8 for your DeepStream project. Happy coding, and let us know if you have any more questions!

**Comment by Sachi9soni** [comment]
> @Sachi9soni hi there! 👋
> 
> It looks like you're diving into integrating YOLOv8 with DeepStream - that's exciting! Regarding the `setup.py` and `requirements.txt` files, YOLOv8 and many modern Python projects have transitioned to using `pyproject.toml` for project setup and dependency management. It's part of the [PEP 517](https://www.python.org/dev/peps/pep-0517/) and [PEP 518](https://www.python.org/dev/peps/pep-0518/) standards.
> 
> To work with `pyproject.toml`, you can use `pip` (version 19.0 or newer) to install the project directly. Navigate to the cloned repository's root directory and run:
> 
> ```shell
> pip install .
> ```
> 
> This command tells `pip` to install the project along with its dependencies as specified in `pyproject.toml`. If you're developing and want your changes to be immediately reflected, you can install it in editable mode:
> 
> ```shell
> pip install -e .
> ```
> 
> This approach should get you set up with YOLOv8 for your DeepStream project. Happy coding, and let us know if you have any more questions!

Hey thanks for replying..i got it and it worked out

**Comment by glenn-jocher** [comment]
Great to hear that it worked out for you, @Sachi9soni! 🎉 If you have any more questions or need further assistance as you continue with your DeepStream + YOLOv8 project, feel free to reach out. Happy coding!

**Comment by xReniar** [comment]
Hi, I am trying to install ultralytics like this:
```
git clone https://github.com/ultralytics/ultralytics.git
cd ultralytics
pip3 install -e .
```
after that i created a script.py outside the folder, the directory looks like this:
```
├── ultralytics
│   └── .....
└── script.py
```
Then script.py looks like this:
```
from ultralytics import YOLO

model = YOLO(model="yolov8n.pt")

print(model("image.png"))
```
But then I get this error:
```
Traceback (most recent call last):
  File "script.py", line 1, in <module>
    from ultralytics import YOLO
ImportError: cannot import name 'YOLO' from 'ultralytics' (unknown location)
```

Did I do something wrong in the installation?

**Comment by glenn-jocher** [comment]
Hey there! 😊 It looks like your installation steps are correct. However, the error suggests there might be an issue with how Python is locating the `ultralytics` package.

One possible reason could be Python not recognizing the `ultralytics` directory as a package if it's missing an `__init__.py` file. Given your structure, though, this seems less likely since you're installing with `pip3 install -e .`, which should handle package recognition.

Another consideration is your working directory when executing `script.py`. Python needs to recognize `ultralytics` as an installed package in your environment. Ensure your environment is active (if you're using one) and that `pip list` shows `ultralytics` installed.

A quick workaround to try is absolute import based on your folder structure. However, this approach typically isn't the issue here.

If the problem persists, here's something else to check:
- Confirm you're using the Python interpreter where `ultralytics` is installed (especially if you have multiple Python installations).

Last but not least, try:
```shell
python3 -m pip install --upgrade pip
python3 -m pip install -e .
```
from inside the `ultralytics` directory again, to ensure `pip` is up-to-date and you're using the right pip associated with your `python3` command.

Let us know how it goes!

**Comment by xReniar** [comment]
@glenn-jocher Thanks for the answer, I tried your solutions the script.py won't start, I  managed to make it work by moving the script.py inside the ultralytics folder

**Comment by glenn-jocher** [comment]
Hey there! 😊 Glad to hear you found a workaround by moving `script.py` inside the `ultralytics` folder. Sometimes Python path intricacies can be a bit tricky. As a cleaner alternative, you might consider running your script from outside the folder by ensuring your Python environment correctly recognizes the `ultralytics` package. Running `pip list` to verify the package is properly installed can also help. If necessary, activating a virtual environment where `ultralytics` is installed might do the trick:

```bash
source venv/bin/activate  # Activate your virtual environment if you're using one
python script.py          # Run your script
```

Keep exploring, and feel free to reach out if you hit any snags! 🚀

**Comment by xReniar** [comment]
I have tried your solution, I made a virtual env:
```
python3 -m venv venv
~ source venv/bin/activate
```
Then i cloned the repo and the installed it:
```
git clone https://github.com/ultralytics/ultralytics.git
cd ultralytics
pip3 install -e .
```
When I type `pip list` i get this:
```
Package                  Version              Editable project location
------------------------ -------------------- -----------------------------------
certifi                  2024.2.2
charset-normalizer       3.3.2
cmake                    3.29.2
contourpy                1.2.1
cycler                   0.12.1
filelock                 3.13.4
fonttools                4.51.0
idna                     3.7
Jinja2                   3.1.3
kiwisolver               1.4.5
lit                      18.1.3
MarkupSafe               2.1.5
matplotlib               3.8.4
mpmath                   1.3.0
networkx                 3.3
numpy                    1.26.4
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
opencv-python            4.9.0.80
packaging                24.0
pandas                   2.2.2
pillow                   10.3.0
pip                      22.0.2
psutil                   5.9.8
py-cpuinfo               9.0.0
pyparsing                3.1.2
python-dateutil          2.9.0.post0
pytz                     2024.1
PyYAML                   6.0.1
requests                 2.31.0
scipy                    1.13.0
seaborn                  0.13.2
setuptools               59.6.0
six                      1.16.0
sympy                    1.12
thop                     0.1.1.post2209072238
torch                    2.0.0
torchvision              0.15.1
tqdm                     4.66.2
triton                   2.0.0
typing_extensions        4.11.0
tzdata                   2024.1
ultralytics              8.2.2                /home/rainer/Code/prova/ultralytics
urllib3                  2.2.1
wheel                    0.43.0
```
Directory now looks like this
```
├── ultralytics
│   └── .....
├── venv
└── script.py
```
But I still get this error 
```
Traceback (most recent call last):
  File "/home/rainer/Code/prova/script.py", line 1, in <module>
    from ultralytics import YOLO
ImportError: cannot import name 'YOLO' from 'ultralytics' (unknown location)
```

**Comment by glenn-jocher** [comment]
Hey there! 👋 It looks like you're on the right track with setting up your virtual environment and installing `ultralytics`. Since the installation seems successful (as `pip list` shows `ultralytics` is indeed installed), let's try two quick things:

1. **Ensure your virtual environment is active** each time you're running `script.py`. It should be, but it's always good to double-check. Your prompt should show `(venv)` if it's active.

2. **Verify your Python path**. Run `python -c "import sys; print(sys.path)"` within your activated virtual environment to check if the path includes your `ultralytics` package directory.

If the package location is in the path but you're still facing issues, as a ***last resort***, try moving `script.py` inside the `ultralytics` directory and run it from there. This shouldn't be necessary under normal circumstances, but it's a way to confirm if the issue lies with Python path resolution.

If none of these work, please let us know! There might be something specific about your setup that we're overlooking. 🛠

**Comment by xReniar** [comment]
This is the output of the `sys.path`:
```
['',
 '/usr/lib/python310.zip',
 '/usr/lib/python3.10',
 '/usr/lib/python3.10/lib-dynload',
 '/home/rainer/Code/prova/venv/lib/python3.10/site-packages',
 '__editable__.ultralytics-8.2.2.finder.__path_hook__'
]
```

**Comment by glenn-jocher** [comment]
@xReniar hey there! 👋 Thanks for sharing your `sys.path` output. It seems like your environment is correctly set up and should recognize the `ultralytics` package installed in editable mode.

Given that, could you please try the following import statement in your `script.py` and see if it works? Sometimes absolute imports can be a bit finicky with editable installs:

```python
import ultralytics
print(ultralytics.__file__)
```

This will help us confirm that Python can indeed locate the `ultralytics` module. If this prints a path without error, but you're still unable to import `YOLO` directly, there might be an issue with how the package is structured or installed.

Looking forward to hearing how it goes!

**Comment by xReniar** [comment]
I tried the code above and it prints `None`, what does this mean?

**Comment by glenn-jocher** [comment]
Hey there! 😊 If `print(ultralytics.__file__)` returns `None`, it indicates Python can't locate the `ultralytics` package properly, even though it's seemingly installed. This could be due to the way your environment is set up or how the package was installed.

Since you installed it in editable mode with `pip install -e .`, let's try:

1. Re-activating your virtual environment.
2. Making sure you're in the correct directory where `ultralytics` is supposed to be.
3. Running `pip install -e .` again in the `ultralytics` directory.

If the issue persists, a re-clone of the repo and re-installation might be needed. Keep us posted!

**Comment by xReniar** [comment]
I tried to all of the 3 solution but sadly I still having error importing ultralytics, anyway I moved the script.py inside the ultralytics to make it work, thanks for the help!

**Comment by glenn-jocher** [comment]
Hey! 🌟 Sorry to hear the troubles persisted, but I'm glad you found a workaround by moving `script.py` inside the `ultralytics` directory. Sometimes, Python's import paths can be a bit tricky. If you have further questions or need more assistance in the future, don't hesitate to ask. Happy coding!

**Comment by petertheprocess** [comment]
I have the same issue.

**Comment by glenn-jocher** [comment]
Thanks—this is almost always a path shadowing issue: if your script is in a directory that also contains a folder named “ultralytics” (the cloned repo), Python imports that folder as a namespace package, so YOLO isn’t found; rename the repo folder (e.g., ultralytics-src) or run the script from a different directory and keep the package installed in editable mode.
