### ISSUE TITLE
How to view model types

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#6267]
```python
from ultralytics import YOLO

# Load a model
model = YOLO('path/to/last.pt')  # load a partially trained model
```

model 
Detection Segmentation Pose  Classification

How to view model types

Too many models
Need to determine whether the type is loaded correctly

**Comment by glenn-jocher** [comment]
@monkeycc when you load a model with the `YOLO` class as shown in your code snippet, the object `model` becomes an instance that contains various attributes about the loaded model. One way to identify the type of the model is to inspect its properties, attributes, or documentation strings that come with the model instance.

Please use the `model.type` attribute directly after loading the model, which should give you the model type if it has been equipped to do so in the latest updates of our repo. If you would like more detailed information, consulting the https://docs.ultralytics.com may provide additional guidance. If this attribute or method is not available and the documentation does not provide clarity, please consider submitting a feature request issue on the GitHub repository for future enhancements.

Keep in mind that the types of tasks the model supports (e.g., detection, segmentation, pose, classification) are typically known prior to loading since they depend on the architecture and the training procedure used for that particular model. If you're following the updates and documentation, you should be able to infer the model's capabilities based on the context in which it was trained and the naming conventions used for model files (e.g., `last.pt`). If the model is an official pre-trained Ultralytics model, the type will correspond to the task for which it was designed and trained.
