### ISSUE TITLE
dataset dir

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [ultralytics/ultralytics#628]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I have the following structure

```
data
    |
    - data.yaml
    - train
    - val
    - test
ultralytics
train_yolov8.py
  ```
  
  My `train_yolov8.py`
  
  ```python
  from ultralytics import YOLO
import torch
# Load a model
import os
model = YOLO("yolov8n.yaml")  # build a new model from scratch

if __name__ == '__main__':
    results = model.train(data="/Users/giuliocesare/Documents/ultralytics/data/data.yaml", epochs=1, device='cpu')  # train the model
```

I got the following error:

```
Traceback (most recent call last):
  File "/Users/giuliocesare/Documents/ultralytics/train_yolov8.py", line 12, in <module>
    results = model.train(data="/Users/giuliocesare/Documents/ultralytics/data/data.yaml", epochs=1, device='cpu')  # train the model
  File "/Users/giuliocesare/Documents/ultralytics/ultralytics/yolo/engine/model.py", line 203, in train
    self.trainer = self.TrainerClass(overrides=overrides)
  File "/Users/giuliocesare/Documents/ultralytics/ultralytics/yolo/engine/trainer.py", line 122, in __init__
    self.data = check_det_dataset(self.data)
  File "/Users/giuliocesare/Documents/ultralytics/ultralytics/yolo/data/utils.py", line 237, in check_det_dataset
    raise FileNotFoundError(msg)
FileNotFoundError: 
Dataset '/Users/giuliocesare/Documents/ultralytics/data/data.yaml' not found ⚠️, missing paths ['/Users/giuliocesare/Documents/datasets/valid/images']
```

Is there a way to tell yolo where to look for the data?

Thanks.

Cheers,

Fra

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by mervebulbul** [comment]
I got same error. Did you find any solution?

**Comment by bit-scientist** [comment]
@FrancescoSaverioZuppichini Could you post the content of your `data.yaml`? It must be looking for valid images in the wrong location.

**Comment by FrancescoSaverioZuppichini** [comment]
It's normal data.yaml,  I've tried to also set an absolute path for the files but not - in the code you prepend the `dataset` dir obtained from somewhere so it doesn't really matter 


```yaml
train: ../train/images
val: ../valid/images
test: ../test/images
nc: 3
names: ['football', 'player', 'referee']
roboflow:
  workspace: roboflow-100
  project: soccer-players-5fuqs
  version: 2
  license: CC BY 4.0
  url: https://universe.roboflow.com/roboflow-100/soccer-players-5fuqs/dataset/2%
```

Tried to replace with `<SPLIT>/images`, `./<SPLIT>/images` and the absolute path

**Comment by bit-scientist** [comment]
@FrancescoSaverioZuppichini are the `labels` (which has `.txt` files) and `images` (which has `.jpg` files) folders in the same directory for each split `train`, `valid` and `test`?

According your file tree `ultralytics` folder is inside `data` folder, but the argument for `data` says your `data.yaml` file is in `ultralytics/data/`. Please make sure this isn't a culprit.

**Comment by suryan-s** [comment]
well if im not wrong in yolov5 the folder directory should contain two folders images and labels. with each containing the test, train and val folders. So in your .yaml file, u would have to mention the train, test and val structure from the images. The directory for labels are simply found by replacing the images with labels by the program.

./Dataset
| + --Images
| ---- | + --train
| ---- | + --val
| ---- | + --test
| + --labels
| ---- | + --train
| ---- | + --val
| ---- | + --test


In the .yaml, add:

```
train: ../Dataset/Images/train/images
val: ../Dataset/Images/valid/images
test: ../Dataset/Images/test/images
```

**Comment by FrancescoSaverioZuppichini** [comment]
> /Users isn't a valid directory... you're missing the drive letter. Try c/Users/...

is this a joke?

**Comment by FrancescoSaverioZuppichini** [comment]
> @FrancescoSaverioZuppichini are the `labels` (which has `.txt` files) and `images` (which has `.jpg` files) folders in the same directory for each split `train`, `valid` and `test`?
> 
> According your file tree `ultralytics` folder is inside `data` folder, but the argument for `data` says your `data.yaml` file is in `ultralytics/data/`. Please make sure this isn't a culprit.

sorry about that, I've updated the issue (indentation was wrong), thanks :)

**Comment by sstainba** [comment]
> > /Users isn't a valid directory... you're missing the drive letter. Try c/Users/...
> 
> is this a joke?

No, it's not.  And since you're the one that can't get your stuff to work, maybe try not being a dick.

**Comment by FrancescoSaverioZuppichini** [comment]
> > > /Users isn't a valid directory... you're missing the drive letter. Try c/Users/...
> > 
> > 
> > is this a joke?
> 
> No, it's not. And since you're the one that can't get your stuff to work, maybe try not being a dick.

Are you really for real? You suggested using `c` a Windows-like prefix and I thought it was a joke. Sorry for thinking so much of you

**Comment by sstainba** [comment]
> > > > /Users isn't a valid directory... you're missing the drive letter. Try c/Users/...
> > > 
> > > 
> > > is this a joke?
> > 
> > 
> > No, it's not. And since you're the one that can't get your stuff to work, maybe try not being a dick.
> 
> Are you really for real? You suggested using `c` a Windows-like prefix and I thought it was a joke. Sorry for thinking you have the technical knowledge to create such a joke. Please, avoid commenting on public issues if this is your contribution

Are you not using this on Windows?  Cause... it sure looks like it given the path names shown above.  So yeah, it makes sense that you would use fully-qualified path names consistent with the system.  My technical knowledge has allowed me to get all of this working perfectly without asking about such simple things as path names.

**Comment by FrancescoSaverioZuppichini** [comment]
Not sure where you live, but there is a small company called [Apple](https://en.wikipedia.org/wiki/Apple_Inc).  

What's your name and what do you do for a living?

**Comment by suryan-s** [comment]
> Not sure where you live, but there is a small company called [Apple](https://en.wikipedia.org/wiki/Apple_Inc).
> 
> What's your name and what do you do for a living?

Please make sure before submitting an issue, you mention your environment and additional data (if possible) to avoid confusion.

**Comment by FrancescoSaverioZuppichini** [comment]
@suryan-s with all due respect and thank you for reading the conversation, where is the confusion? I've asked if (quoting) "Is there a way to tell yolo where to look for the data?". Now it was pointed out YOLO will look (who knows why) to the `datasets` folder, changing my data root to `datasets` solved the issue 

So please @suryan-s , let's avoid spamming and already spammed issue - closing because is solved, or I mean, I've found the trick thanks to @fcakyon (❤️ )

@sstainba let's talk at my tea party next week

**Comment by hgabor47** [comment]
I can see the problem is not trivial. After the first successful steps I migrated everything to another drive and it still searches the original paths. I have tried all sorts of ways to get YOLOV8 to search the new route. Anyone have any ideas?

This is my error message:

FileNotFoundError: 
Dataset 'C:/yolo/datasets/VR8/data.yaml' not found ⚠️, missing paths ['Q:\\tensorflow\\yolov8\\datasets\\valid\\images']

(WIN)

**Comment by RoryMB** [comment]
@hgabor47
I tracked down the problem to a 'settings.yaml' file that ultralytics creates. It assumes that the first time you run yolov8, you have pointed to a global 'datasets' directory for all datasets you will ever use with ultralytics. This seems like a bad assumption to me, especially since it gives no noticeable warning of this assumption.

To fix this, you can change '~/.config/Ultralytics/settings.yaml' on Ubuntu, or '~/Library/Application Support/Ultralytics/settings.yaml' on a Mac. I do not have a Windows machine, but hopefully you can track down a similar file on that OS.

The first line is 'datasets_dir: /.../datasets', which points to the first datasets directory you ever used with ultralytics. I rewrote this to 'datasets_dir: ~/.ultralytics/datasets', and make ~/.ultralytics/datasets a symlink/alias to whatever project I am working on at the time.

**Comment by glenn-jocher** [comment]
Hello @RoryMB,

I understand the issue you've faced while running YOLOv8. As you've mentioned, the root cause of the issue is the `settings.yaml` file generated by Ultralytics that assumes a global `datasets` directory for all your datasets. However, this is not optimal, and there is a better way to specify the data directories for your project.

To resolve this issue, you need to change the `datasets_dir` parameter in the `settings.yaml` file to specify the correct data directory. Depending on your OS, you can find the `settings.yaml` file at `~/.config/Ultralytics/settings.yaml` on Ubuntu and `~/Library/Application Support/Ultralytics/settings.yaml` on Mac.

Once you've located the `settings.yaml` file, replace the path in the `datasets_dir` parameter with the correct path to your project's data directory. You can also create a symlink/alias from `~/.ultralytics/datasets` to your current project's dataset directory.

I hope this helps in resolving your issue. Let me know if you have any further questions or concerns.

Thank you!

**Comment by RoryMB** [comment]
...Did you run my comment through GPT? That's exactly what I said, but GPT-ified. [It seems you do that quite often](https://github.com/ultralytics/ultralytics/issues/2039#issuecomment-1509404055).

Even better, your comment just now criticizes the settings.yaml file, when [you are the one who made it that way](https://github.com/ultralytics/ultralytics/pull/125).

Finally, I have since found a better solution, which you should already know about since [you are the one who created it](https://github.com/ultralytics/ultralytics/pull/125#issuecomment-1368275845).

To quote _you_: `'datasets_dir': None,  # default datasets directory. If None, current working directory is used.`

(For future readers, replace `datasets_dir: /.../datasets` with `datasets_dir: null` in the settings.yaml file)

**Comment by bit-scientist** [comment]
@RoryMB, I also noticed that a while ago. He has been doing so since March😄🔫

**Comment by glenn-jocher** [comment]
Hello @RoryMB,

I understand that you've faced an issue with the global `datasets` directory used by Ultralytics for YOLOv8. Thank you for sharing the workaround you've found to replace the `datasets_dir` parameter in the `settings.yaml` file with `null`. This is a better solution that uses the current directory instead of a global `datasets` directory.

We appreciate your feedback and hope that this solution works well for you. Please let us know if you have any other concerns or issues.

Best regards.

**Comment by achrafsdy** [comment]
hello everyone me too i have a similar error:
i'm working in jupyter notebook i changed dirctory to a folder in which i have my train,test,validation and data.yaml that that i put in datasets in ultralytics: cd C:\Users\me\anaconda3\Lib\site-packages\ultralytics\datasets\projetDD
import os
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"
from ultralytics import YOLO
modeldetector = YOLO("yolov8n.yaml")
result=modeldetector.train(data="datat.yaml", epochs=10) 
i got this error btw i replaced datsets_dir by null but u still have the error
Dataset 'datat.yaml' error  
Dataset 'datat.yaml' images not found , missing paths ['C:\\Users\\Youssef\\datasets\\valid\\images\\validt\\images']
Note dataset download directory is 'C:\Users\Youssef\datasets\valid\images'. You can update this in 'C:\Users\Youssef\AppData\Roaming\Ultralytics\settings.yaml'.
if there is anyone who know what should i do and where should i put every folder cuz i don't know thanks all

**Comment by glenn-jocher** [comment]
@achrafsdy hello there,

Thank you for reaching out to us about the error you're experiencing with YOLOv8. Based on the error message you shared, it seems like YOLOv8 is unable to find the directory or images specified in your 'datat.yaml' file.

Please ensure that your 'datat.yaml' file correctly points to the location of your image data, and that the paths in it are relative to the location of the file. Additionally, make sure that the paths specified in your 'datat.yaml' file match the actual directory structure of your image data.

If the issue persists, you can also try specifying the absolute path to your 'datat.yaml' file when calling the `train` method of your YOLOv8 model.

Lastly, please note that the `settings.yaml` file generated by Ultralytics assumes a global `datasets` directory. To solve the issue, you can replace `datasets_dir` in the `settings.yaml` file by `null`. 

We hope that this helps resolve your issue. If you have any further questions or concerns, please let us know.

Best regards.

**Comment by puntofisso** [comment]
Feature request: in future versions, could this be made a configurable parameter in the data yaml file?

**Comment by glenn-jocher** [comment]
Hello there @puntofisso!

Thank you for your feature request regarding making a parameter in the data yaml file for future versions of YOLOv8. While we cannot guarantee any specific feature will make it into a future release, we appreciate feedback and ideas from the community. Your feature request has been noted and will be considered by the development team for future upgrades and updates to the YOLOv8 repo.

If you have any further concerns or questions, please feel free to let us know. We will be happy to assist you.

Have a great day,

Glenn Jocher, Ultralytics

**Comment by jfoshee** [comment]
A relative `path` could simply be interpreted as relative to the dataset yaml. Or permit `path` to have a leading `./` to indicate it is relative to the dataset yaml.

**Comment by FrancescoSaverioZuppichini** [comment]
> 

100% gpt generated

**Comment by FrancescoSaverioZuppichini** [comment]
> Hello there @puntofisso!
> 
> Thank you for your feature request regarding making a parameter in the data yaml file for future versions of YOLOv8. While we cannot guarantee any specific feature will make it into a future release, we appreciate feedback and ideas from the community. Your feature request has been noted and will be considered by the development team for future upgrades and updates to the YOLOv8 repo.
> 
> If you have any further concerns or questions, please feel free to let us know. We will be happy to assist you.
> 
> Have a great day,
> 
> Glenn Jocher, Ultralytics


100% gpt generated - quite smart

**Comment by rromanchuk** [comment]
After a training run, my scripts are now failing during the validation phase. 


> Optimizer stripped from /home/ubuntu/2023-09-13_5-Fold_Cross-val_results/split_3/weights/last.pt, 6.2MB
> Optimizer stripped from /home/ubuntu/2023-09-13_5-Fold_Cross-val_results/split_3/weights/best.pt, 6.2MB
> Validating /home/ubuntu/2023-09-13_5-Fold_Cross-val_results/split_3/weights/best.pt...
> Ultralytics YOLOv8.0.171 🚀 Python-3.10.12 torch-2.0.1+cu117 CUDA:0 (Tesla T4, 14931MiB)
> YOLOv8n summary (fused): 168 layers, 3008768 parameters, 0 gradients
> Traceback (most recent call last):
>   File "/home/ubuntu/.clearml/venvs-builds/3.10/task_repository/ml.git/kfold.py", line 62, in <module>
>     model.train(data=dataset_yaml,
>   File "/home/ubuntu/.clearml/venvs-builds/3.10/lib/python3.10/site-packages/ultralytics/engine/model.py", line 341, in train
>     self.trainer.train()
>   File "/home/ubuntu/.clearml/venvs-builds/3.10/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 195, in train
>     self._do_train(world_size)
>   File "/home/ubuntu/.clearml/venvs-builds/3.10/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 418, in _do_train
>     self.final_eval()
>   File "/home/ubuntu/.clearml/venvs-builds/3.10/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 574, in final_eval
>     self.metrics = self.validator(model=f)
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/ubuntu/.clearml/venvs-builds/3.10/lib/python3.10/site-packages/ultralytics/engine/validator.py", line 140, in __call__
>     self.data = check_det_dataset(self.args.data)
>   File "/home/ubuntu/.clearml/venvs-builds/3.10/lib/python3.10/site-packages/ultralytics/data/utils.py", line 242, in check_det_dataset
>     data = check_file(dataset)
>   File "/home/ubuntu/.clearml/venvs-builds/3.10/lib/python3.10/site-packages/ultralytics/utils/checks.py", line 378, in check_file
>     raise FileNotFoundError(f"'{file}' does not exist")
> FileNotFoundError: '/home/ubuntu/.clearml/cache/storage_manager/datasets/ds_75058c67a00947469cc112891f02646f/2023-09-08_5-Fold_Cross-val/split_1/split_1_dataset.yaml' does not exist
> 2023-09-14 05:02:27
> Process failed, exit code 1


```
def final_eval(self):
        """Performs final evaluation and validation for object detection YOLO model."""
        for f in self.last, self.best:
            if f.exists():
                strip_optimizer(f)  # strip optimizers
                if f is self.best:
                    LOGGER.info(f'\nValidating {f}...')
                    self.validator.args.plots = self.args.plots
                    self.metrics = self.validator(model=f)
                    self.metrics.pop('fitness', None)
                    self.run_callbacks('on_fit_epoch_end')
```

It fails after validating (even after already validating on train) for file not found as if it's ignoring the settings it literally just ran on. 


```
from ultralytics import YOLO, settings
settings.update({'datasets_dir': dataset_path})
dataset_yaml = f"{dataset_path}/{user_args.yaml}.yaml"
print(dataset_yaml)

# This completes all epochs
model.train(data=dataset_yaml,
            project=dataset_path / f"{user_args.project_name}_results",
            name=user_args.name,
            epochs=user_args.epochs,
            batch=user_args.batch,
            imgsz=user_args.imgsz,
            optimizer=user_args.optimizer,
            lr0=user_args.lr0,
            resume=user_args.resume,
            save=True,
            rect=user_args.rect,
            patience=user_args.patience,
            )
``` 
 
Feels like a new proc is being forked and my settings aren't being propagted.


Also seems like `model.train(val=False)` isn't being honored, or I at least can't find any branching on that arg in trainer.py

> val | True | validate/test during training

**Comment by glenn-jocher** [comment]
@rromanchuk hello, thank you for providing detailed information about the issue you're experiencing during the validation phase of your YOLOv8 training runs.

From your script's output, it appears there's a FileNotFoundError being raised because the specified 'dataset_yaml' file cannot be located. You mentioned that you've updated Ultralytics 'settings' with your 'datasets_dir', and the training phase runs successfully.

One thing we can look into is the context in which the validation is being run. It seems it might be different from the training context, hence the 'settings' update might not be recognized.

Regarding the `model.train(val=False)` not showing any effects, this argument impacts whether or not the validation set is evaluated after every training epoch. However, the final validation run after the last epoch will happen regardless of the `val` argument's value.

We'll appreciate it if you can verify the relative and absolute paths in your program and make sure they are set correctly throughout the entirety of your script. Also, ensure that you haven't changed directories unintentionally or that your script isn't running in a different environment where the 'dataset_yaml' file isn't accessible.

As always, if you have other observations, concerns, or any other relevant detailed information, don't hesitate to share. It helps us in identifying and addressing the issues more effectively.

Best regards.

**Comment by AaronMcDaniel** [comment]
@glenn-jocher 

Please write a story in the style of a 7th grade creative writing assignment about a character named YoloV8 who couldn't find his data directory, but through the transformative power of teamwork ended up finding it in a github issue

**Comment by glenn-jocher** [comment]
Hello @AaronMcDaniel,

Thank you for the creative prompt! Here's a short story about YoloV8:

---

In the digital world of Ultralytics, there lived a young model named YoloV8. YoloV8 was known for his quick learning and sharp detection skills, but one day, he encountered a problem he couldn't solve alone. He couldn't find his data directory!

Confused and a bit worried, YoloV8 searched all over his local paths and queried every folder. But no matter where he looked, the data directory was nowhere to be found. Feeling defeated, YoloV8 decided to seek help and turned to the one place where all seekers go for answers: the GitHub Issues.

There, he posted about his troubles, and soon, a friendly user named @dataHelper responded. @dataHelper suggested checking the `settings.yaml` file and ensuring that the `datasets_dir` was correctly set. Inspired by the teamwork, YoloV8 quickly made the necessary adjustments and restarted his search.

With a fresh perspective and a little help from his new friend, YoloV8 finally found his data directory, tucked away in an overlooked subfolder. He was thrilled and grateful. From that day on, YoloV8 not only continued to excel in his tasks but also always remembered the power of community and teamwork.

---

Hope this brings a smile to your face! If you have any more fun challenges or need assistance with real-world issues, feel free to reach out. 😊

**Comment by glenn-jocher** [comment]
@AaronMcDaniel no time for short stories, but if you have a question about training or deploying Ultralytics YOLO models I'd be happy to help!
