### ISSUE TITLE
Tflite Predictions

### ISSUE THREAD

**Issue by pythonstuff8** [ultralytics/ultralytics#6285]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question
I made a tflite model using transfer learning from mobilenet. For classfication, but when use ultralytics to try and predict on it, it defaults to detect since I do not have a metadata yaml file for it. It also defults to 640 by 640 because it does not have a metadata yaml file. I need 224 by 224.

**Comment by glenn-jocher** [comment]
@pythonstuff8 hello! It sounds like you are trying to use a tflite model trained for classification on the Ultralytics YOLOv8 pipeline which is optimized for detection tasks by default. Since the pipeline is expecting certain model configuration details that are usually provided by a metadata YAML file, including resolution and classes, it defaults to standard YOLOv8 settings when this information is not found.

To address the specific issue of the input size, when you are using Ultralytics tools to work with your tflite model, you should ensure to specify the correct input size your model expects somewhere in the code. As for the classification task, you would typically need to adjust the inference script to handle this task since it is different from object detection. This can involve changing the model loading section and the inference pipeline to accommodate classification rather than detection.

Please keep in mind that YOLOv8, including its tools and pre-set configurations, is designed primarily for detection tasks. Models that are meant for classification, such as those built on top of architectures like MobileNet, may require significant modifications to the codebase if you wish to integrate them into the same prediction routines.

If you need more detailed guidance on model usage and configuration according to your specific requirements, you might want to consult the official documentation at https://docs.ultralytics.com, which provides comprehensive tutorials and explanations about using different features and adapting them to custom settings.
