### ISSUE TITLE
DDP with AMD GPUS

### ISSUE THREAD

**Issue by Selbyl** [ultralytics/ultralytics#6291]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train, Multi-GPU

### Bug

In a conda environment, I have ROCM 5.7 installed with Pytorch nightly. All components of ROCM are installed. 
I can get a single GPU to work just fine, but when changing the command to device=0,1 I receive the following error:

Traceback (most recent call last):
  File "/home/server-004/.config/Ultralytics/DDP/_temp_9oil0wkt139790524351872.py", line 12, in <module>
    results = trainer.train()
  File "/home/server-004/.local/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/home/server-004/.local/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 288, in _do_train
    self._setup_train(world_size)
  File "/home/server-004/.local/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 237, in _setup_train
    dist.broadcast(self.amp, src=0)  # broadcast the tensor from rank 0 to all other ranks (returns None)
  File "/home/server-004/.local/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/server-004/.local/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: NCCL Error 1: unhandled cuda error
[2023-11-12 20:38:48,566] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 202858 closing signal SIGTERM
[2023-11-12 20:38:48,680] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 1 (pid: 202859) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/server-004/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 810, in <module>
    main()
  File "/home/server-004/.local/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/server-004/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/server-004/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/server-004/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/server-004/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/home/server-004/.config/Ultralytics/DDP/_temp_9oil0wkt139790524351872.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-12_20:38:48
  host      : server-004
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 202859)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/home/server-004/.local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/server-004/.local/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 444, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/server-004/.local/lib/python3.10/site-packages/ultralytics/engine/model.py", line 341, in train
    self.trainer.train()
  File "/home/server-004/.local/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 187, in train
    raise e
  File "/home/server-004/.local/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 185, in train
    subprocess.run(cmd, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'torch.distributed.run', '--nproc_per_node', '2', '--master_port', '38423', '/home/server-004/.config/Ultralytics/DDP/_temp_9oil0wkt139790524351872.py']' returned non-zero exit status 1.

When looking at the trainer.py file it appears around line 120 that if NCCL is not available it will revert to GLOO, so I don't understand why this isn't working. I've also changed the section of the script to only use GLOO and I'm still getting the same error. 

### Environment

Ultralytics YOLOv8.0.203 🚀 Python-3.10.12 torch-2.1.0+rocm5.6 CUDA:0 (AMD Radeon RX 6900 XT, 16368MiB)
Setup complete ✅ (4 CPUs, 62.7 GB RAM, 189.1/915.3 GB disk)

OS                  Linux-5.15.55-051555-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             pip
RAM                 62.72 GB
CPU                 Intel Core(TM) i3-9100F 3.60GHz
CUDA                None

matplotlib          ✅ 3.8.1>=3.3.0
numpy               ✅ 1.24.1>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 9.0.1>=7.1.2
pyyaml              ✅ 5.4.1>=5.3.1
requests            ✅ 2.25.1>=2.23.0
scipy               ✅ 1.11.3>=1.4.1
torch               ✅ 2.1.0+rocm5.6>=1.8.0
torchvision         ✅ 0.16.0+rocm5.6>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 2.1.2>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
psutil              ✅ 5.9.6
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

### Minimal Reproducible Example

yolo train detect device=0,1 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Selbyl thank you for your detailed issue report. It seems like you're encountering a multi-GPU training issue with ROCm and YOLOv8 that involves distributed data parallel (DDP) processing not working as expected.

First, let's confirm that your ROCm installation supports multi-GPU training. It's good practice to test basic multi-GPU capabilities outside of YOLOv8 to ensure that the issue isn't related to the ROCm setup.

If your ROCm stack is functioning properly for other multi-GPU applications, the next step is to look into the PyTorch and NCCL (NVIDIA Collective Communications Library) configuration being used. Since you're using AMD GPUs, it's important to note that NCCL is specifically designed for NVIDIA GPUs and you should be using the ROCm equivalent, RCCL. However, since the error is NCCL-related, this might suggest an issue with the default backend selection for distributed processing.

YOLOv8 uses PyTorch's distributed package, which can default to NCCL for the distributed backend if it detects CUDA (even if ROCm components are used). Since your GPUs are AMD, you should ensure that the correct backend is selected, which is typically 'gloo' or 'mpi' for non-NVIDIA GPUs.

To force PyTorch to use a specific backend, you can set the `TORCH_DISTRIBUTED_BACKEND` environment variable to 'gloo' or 'mpi' before running your training command. If you already tried this as mentioned and it failed, it indicates there might be a deeper compatibility issue or a misconfiguration.

It's also important to ensure your PyTorch version has been installed with ROCm support and is compatible with distributed training on ROCm. Nightly versions can have unexpected behaviors, so double-checking the compatibility with the particular version of ROCm, PyTorch, and system drivers is advised.

If after checking these steps the issue persists, we recommend opening a detailed bug report with the PyTorch team, as the error you are experiencing is occurring during the PyTorch DDP setup process, which is outside of the core YOLOv8 code.

In the meantime, for further guidance tailored for ROCm users, you can visit the Ultralytics Docs and search for DDP or multi-GPU training considerations specific to AMD GPUs. We appreciate your effort to improve the tool and willingness to submit a PR. If you identify a solution, please feel free to contribute to the repository.

**Comment by Selbyl** [comment]
Thanks @glenn-jocher! 
setting the environment variable for gloo gave a different error to compile pytorch with 'TORCH_USE_HIP_DSA'

There's a few more steps, but I'll be sure to post another comment here so that documentation can be updated. 

After I figure this out, maybe the training script can check for AMD or Nvidia GPUs, if AMD Gpus are present a print statement with a link to the docs for AMD GPUs could be added.

**Comment by glenn-jocher** [comment]
@Selbyl i appreciate the update, and it's great to hear that you are making progress. Your feedback is valuable and indeed could help many users in the community. 

Compiling PyTorch with ROCM can indeed be challenging due to the subtleties of ROCM support and the current state of the ecosystem. PyTorch's compatibility with ROCM is a work in progress, and issues can arise with different combinations of software versions and system configurations.

The suggestion to add a check for AMD or Nvidia GPUs and provide a documentation hint in the script is insightful. It could significantly aid in making the setup process user-friendlier for diverse hardware environments.

Once you have finalized your steps and if they reliably address the multi-GPU training issue on AMD GPUs, sharing them would be of immense help. Documenting this would be very useful, and if you could contribute these findings back to the community through an update, a comment, or even a pull request for our Docs, it would be much appreciated!

Your persistence is commendable, and it contributes to the broader effort of enhancing PyTorch and YOLOv8 support for ROCM. The open source ecosystem thrives on such collaborative efforts, and your input is a prime example of that. Meanwhile, if we roll out improvements or workarounds for better AMD GPU support, be assured they will be communicated through the repository and documentation.

**Comment by Selbyl** [comment]
So through more troubleshooting it appears to likely be a ROCM issue at this time.

https://rocm.docs.amd.com/projects/radeon/en/latest/docs/limitations.html

RuntimeError: HIP error: the operation cannot be performed in the present state
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing HIP_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.

Because I have one GPU connected to PCIE through the chipset, this is likely the issue I am running into and this is something that AMD will have to fix.

**Comment by glenn-jocher** [comment]
@Selbyl thanks for the update. It sounds like you've narrowed down the issue to something specific to ROCm's current limitations, particularly with how it handles PCI-e connections through the chipset. The error message and the suggestion to use `HIP_LAUNCH_BLOCKING=1` are indeed indicative of an issue that isn't directly related to YOLOv8 but rather to the underlying hardware compatibility and ROCm's handling of certain operations.

For now, it does seem this is something that AMD will need to address in their ROCm platform. Hopefully, they can provide a fix or a workaround in future releases. Your diligence in troubleshooting and sharing your findings is valuable to the community, as others may encounter the same situation. Keep an eye on updates from AMD's ROCm documentation and release notes for any improvements that might resolve your issue.

If there’s anything else you find that could be of interest to YOLOv8 users, especially those with AMD hardware, please share! Your contributions are what make the open-source community thrive. 🚀
