### ISSUE TITLE
.yaml for each YOLOv8 models disappeared and now merged automatically?

### ISSUE THREAD

**Issue by sunhoro** [ultralytics/ultralytics#6297]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

When I first installed 3 days ago, I was able to train by selecting Yolov8 models (yolov8n.yaml, yolov8s.yaml, yolov8m.yaml, yolov8l.yaml, yolov8x.yaml) at C:\Users\XXX\anaconda3\Lib\site-packages\ultralytics\models\v8 

After a few days, all of a sudden, these 5 .yaml files are missing.
After reading some issue posts, I figured out that somehow it is merged to yolov8.yaml at C:\Users\XXX\anaconda3\Lib\site-packages\ultralytics\cfg\models\v8.

The question is why and how is this a common flow? Is this supposed to be like this?
Also, if so, how do I choose which model to train with? If I use yolov8.yaml, which model is it using?
I don't think it actually specifies anywhere.

### Environment

Windows 11

### Minimal Reproducible Example

Below is the yolov8.yaml file:

# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 object detection model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 80  # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]  # YOLOv8n summary: 225 layers,  3157200 parameters,  3157184 gradients,   8.9 GFLOPs
  s: [0.33, 0.50, 1024]  # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  m: [0.67, 0.75, 768]   # YOLOv8m summary: 295 layers, 25902640 parameters, 25902624 gradients,  79.3 GFLOPs
  l: [1.00, 1.00, 512]   # YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs
  x: [1.00, 1.25, 512]   # YOLOv8x summary: 365 layers, 68229648 parameters, 68229632 gradients, 258.5 GFLOPs

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 6], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, C2f, [512]]  # 12

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 4], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 15 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]]  # cat head P4
  - [-1, 3, C2f, [512]]  # 18 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]]  # cat head P5
  - [-1, 3, C2f, [1024]]  # 21 (P5/32-large)

  - [[15, 18, 21], 1, Detect, [nc]]  # Detect(P3, P4, P5)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@sunhoro it's great to hear that you're using YOLOv8 for your work. The recent changes you've noticed are part of an update to simplify model selection and usage. We have consolidated the individual model configuration files into a single `yolov8.yaml` file, which includes the scaling factors for different versions of YOLOv8 (n, s, m, l, and x). 

When you specify which model you want to use, such as `yolov8n`, `yolov8s`, `yolov8m`, `yolov8l`, or `yolov8x`, the appropriate scaling factors are automatically selected from the `yolov8.yaml` file based on the scale name. This is intended to streamline the process and ensure that you can easily switch between different model sizes without having to manage multiple configuration files.

To choose a specific model to train with, you would use the model name as an argument in your training command, for example for a `yolov8s` model you would specify it directly. The `yolov8.yaml` file uses the `scales` section to adjust the depth, width, and max_channels according to the chosen scale, which determines the size and complexity of the model.

Hopefully, this explanation clarifies the new approach for selecting and using the different YOLOv8 model sizes. For more information on how to train with a specific model, please refer to the documentation at https://docs.ultralytics.com. If you encounter any issues or have further questions, feel free to reach out again. Happy training!

**Comment by sunhoro** [comment]
Thank you but can you give me a CLI example?

This is what I am using right now. So how can I specify the models?

`yolo detect train data=mytrain.yaml model="C:\Users\anaconda3\Lib\site-packages\ultralytics\cfg\models\v8\yolov8.yaml" epochs=200`

**Comment by glenn-jocher** [comment]
@sunhoro i understand you're seeking a way to specify the model size directly in the command line interface (CLI). Since our goal is to keep our answers focused on guiding users rather than providing direct code examples, I can describe how to specify the model using the CLI:

You will still use the `yolo` command, along with the `train` argument, and specify your data configuration file with `data=mytrain.yaml`. To choose the specific YOLOv8 model size (such as `yolov8n`, `yolov8s`, etc.), you need to provide the model name directly in the command without pointing to a file path. The command will understand which model size you want to train with based on this argument.

The specifications of each model size, such as 'n' or 's', are predefined within `yolov8.yaml`. When you invoke the training command with a specific model size identifier, the system uses the corresponding scaling factors from the `scales` section in the `yolov8.yaml` to configure the model depth, width, and channels automatically.

Therefore, instead of specifying the path to the YAML file, you simply mention the model scale like `model=yolov8n` or `model=yolov8s` in your training command. The `yolo` CLI will then interpret this and adjust the model architecture as per the defined scale. This should make your command more concise and easier to manage.

Remember to visit the Ultralytics documentation at https://docs.ultralytics.com for detailed instructions and guidelines on using the CLI for training models. If you have any more questions or require further assistance, don't hesitate to ask!
