### ISSUE TITLE
Validation results differ between the results directly after training and after validation

### ISSUE THREAD

**Issue by DP1701** [ultralytics/ultralytics#6313]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello everyone,

I have noticed that the validation results after the training differ from those determined with the val() function. I use the following script:

```
from ultralytics import YOLO

# Load a pretrained YOLO model (recommended for training)
model = YOLO('yolov8m-seg.pt')

# Train the model
results = model.train(data='data.yaml', epochs=1)

# Evaluate the model's performance on the validation set
results = model.val()
```

I get these results after training with ```results = model.train(data='data.yaml', epochs=1)```:
![Bildschirmfoto 2023-11-13 um 14 22 37](https://github.com/ultralytics/ultralytics/assets/68444979/0e326063-25ec-4831-abab-4e7db86a7e49)

And after ```results = model.val()```:
![Bildschirmfoto 2023-11-13 um 14 24 28](https://github.com/ultralytics/ultralytics/assets/68444979/ce6fc419-6741-40dc-bb55-6a6ccedff99b)

I already found this [thread](https://github.com/ultralytics/ultralytics/issues/3065) but honestly, I don't know which parameter should be different between train and val. I use the default values in this case.

**Comment by glenn-jocher** [comment]
@DP1701 hello,

The discrepancy between validation results following training and those obtained using the `model.val()` function could result from slight differences in the validation configurations at the end of training versus standalone validation, even when default settings are used. These configurations include parameters like batch size, data augmentation, and others that may affect the consistency of your validation results.

The differences should generally be minimal, but they can also result from non-deterministic operations, data loading variations, or hardware-specific computation discrepancies. It's also important to ensure that the same dataset and data split are being used in both instances.

To troubleshoot and align the validation results, please check the following:

1. Confirm that the data configuration file (`data.yaml`) is correctly set up and pointed to the same validation dataset for both the end of training and standalone validation.
2. Review the default hyperparameters for training and standalone validation to ensure they are consistent. This includes matching any augmentation, inference sizes, or any other relevant settings.
3. Make sure you're using the same version of the software for both operations, as updates may change the default behaviors slightly.

If the issue persists and you need more detailed assistance, kindly provide us with additional detail on your environment, data, and the full training and validation logs. Your contribution is valuable, and understanding these nuances may help us improve the software.

For further clarification on how model validation is configured and executed in YOLOv8, please refer to the documentation at Ultralytics Docs.

**Comment by DP1701** [comment]
@glenn-jocher Hello,

I have now taken a close look at the following things:

To point one: Yes, the data.yaml file is set correctly and points to the validation dataset in both cases (validation directly after training and validation with the val() function):

yaml File:

```
path: /Users/work/Desktop/YOLO/dataset  # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')
test: images/test # test images (optional)

  # Classes
names:
  0: a
  1: b
  2: c
```

About point two: I have looked at the hyperparameters. If I haven't missed anything, then they are the same (except for the "model" parameter). To take a closer look at this, I have written the following lines of code:


```
from ultralytics import YOLO

# Load a pretrained YOLO model (recommended for training)
model = YOLO('yolov8m-seg.pt')

# Train the model
model.train(data='/Users/work/Desktop/YOLO/data.yaml', epochs=1)

# Print the hyperparameters set
print(model.trainer.validator.args)

print("\nLoad model from: " + model.model.pt_path)

# Create a new YOLO model with the previously created Pytorch model
model_val = YOLO(model.model.pt_path)

# Evaluate the model's performance on the validation set
model_val.val()
```

With ```print(model.trainer.validator.args)``` I print the passed arguments that the validator, which is coupled with the trainer object, contains.

In the val() function I have added the code line ``` print(validator.args)```:

```
def val(self, validator=None, **kwargs):
        """
        Validate a model on a given dataset.

        Args:
            validator (BaseValidator): Customized validator.
            **kwargs : Any other args accepted by the validators. To see all args check 'configuration' section in docs
        """
        custom = {'rect': True}  # method defaults
        args = {**self.overrides, **custom, **kwargs, 'mode': 'val'}  # highest priority args on the right

        validator = (validator or self._smart_load('validator'))(args=args, _callbacks=self.callbacks)
        validator(model=self.model)
        self.metrics = validator.metrics
        print(validator.args)
        return validator.metrics
```

This also gives me the same list that was previously output. To summarize: The list of hyperparameters used during training (trainer.validator) and the list of hyperparameters used during validation with val() are output.

Here is a table with the hyperparameters that are used in both cases:
[Hyperparameters.pdf](https://github.com/ultralytics/ultralytics/files/13349096/Hyperparameters.pdf)

Regarding point three: I have installed YOLOv8 in a Conda environment and use it for both training and validation. Yesterday I updated YOLOv8 to the latest version with ``` pip install ultralytics -U```.

My dataset is a custom dataset (polygons) that I want to use to generate an instance segment model. 

My system:
macOS 13.6.1 (intel based Mac)
Python 3.10.11

Pip packete:
Package            Version
------------------ --------------------
certifi            2023.7.22
charset-normalizer 3.2.0
contourpy          1.1.0
cycler             0.11.0
filelock           3.12.2
fonttools          4.41.1
fsspec             2023.4.0
idna               3.4
Jinja2             3.1.2
joblib             1.3.2
kiwisolver         1.4.4
MarkupSafe         2.1.3
matplotlib         3.7.2
mpmath             1.3.0
networkx           3.1
numpy              1.25.1
opencv-python      4.8.0.74
packaging          23.1
pandas             2.1.0
Pillow             10.0.0
pip                23.2.1
psutil             5.9.5
py-cpuinfo         9.0.0
pyparsing          3.0.9
python-dateutil    2.8.2
pytz               2023.3
PyYAML             6.0.1
requests           2.31.0
scikit-learn       1.3.0
scipy              1.11.1
seaborn            0.12.2
setuptools         68.0.0
six                1.16.0
sympy              1.12
thop               0.1.1.post2209072238
threadpoolctl      3.2.0
torch              2.1.0
torchvision        0.16.0
tqdm               4.65.0
typing_extensions  4.7.1
tzdata             2023.3
ultralytics        8.0.208
urllib3            2.0.4
wheel              0.41.0

At the moment I don't know what causes this difference. 
I have put the different validation results in a table to make it easier to read and compare:

[Result.pdf](https://github.com/ultralytics/ultralytics/files/13349140/Result.pdf)

Sorry for the long message but I wanted to show you the steps I took to understand the difference. Maybe I just overlooked something that causes the difference.

**Comment by DP1701** [comment]
One more thing, you write in your last message that it would be helpful to output the full training and validation logs.  How can I output this?

**Comment by glenn-jocher** [comment]
@DP1701, thank you for providing such a detailed overview of the steps you've taken to diagnose the issue. 

To output and inspect the full training and validation logs, you can find the training results, including validation metrics during training, in the 'results.csv' file located in the run's specific directory within the 'runs/train' directory. This CSV file provides epoch-by-epoch results of your training.

For the validation logs, when using `model.val()`, verbose outputs including detailed per-class metrics and overall metrics are printed to the console by default. If you wish to inspect these logs at a later time or save them for further analysis, you could redirect the console output to a file when running your validation script. You can do this by executing your script from the command line and appending `> validation_log.txt` at the end of the command to save the console printout to 'validation_log.txt' file.

Additionally, consider revisiting model weights loading between training and validation. Make sure that the exact same set of trained weights are utilized for both post-training and standalone validation processes. You can check the paths and assert that no reinitialization or unintended weight loading is occurring.

Finally, ensure that any random seeds, if set for the sake of reproducibility, are synchronized between your training and validation sessions. If seeds are indeed different or not set, results might slightly vary due to the stochastic nature of the operations involved in neural network execution.

Please analyze the logs obtained from the steps above to look for any discrepancies in configuration or execution, and if you need further assistance interpreting these logs, provide some relevant excerpts while respecting noted privacy or sensitivity of data.

**Comment by DP1701** [comment]
@glenn-jocher Hello,

I have found the reason for this. During training, the Dataloader object is initialized with a batch size of 32, although I have set the batch size for training to 16. This is also maintained during training, but not during validation.

I mean the following functions:

[self.validate()](https://github.com/ultralytics/ultralytics/blob/0473da00a9ad93deadcec8b765774c6d80fc9aa5/ultralytics/engine/trainer.py#L379)
[self.final_eval()](https://github.com/ultralytics/ultralytics/blob/0473da00a9ad93deadcec8b765774c6d80fc9aa5/ultralytics/engine/trainer.py#L407)

If the functions are called, I see in the [batch](https://github.com/ultralytics/ultralytics/blob/0473da00a9ad93deadcec8b765774c6d80fc9aa5/ultralytics/engine/validator.py#L161) object that there are 32 images in 'im_file'.

![Bildschirmfoto 2023-11-15 um 18 35 43](https://github.com/ultralytics/ultralytics/assets/68444979/c3317d37-02ad-49e7-b606-e6da58a5d2b4)
![Bildschirmfoto 2023-11-15 um 18 36 41](https://github.com/ultralytics/ultralytics/assets/68444979/d5c5da4c-ddce-4ea6-a9c4-c986479bedc4)

Should this be the case?

If I set the batch size in the val() function to 32, I get the same results as directly after the training.

```
from ultralytics import YOLO

# Load a pretrained YOLO model (recommended for training)
model = YOLO('yolov8m-seg.pt')

# Train the model
model.train(data='/Users/work/Desktop/YOLO/data.yaml', epochs=1)

result = model.val(batch=32)
```
![Bildschirmfoto 2023-11-15 um 19 13 14](https://github.com/ultralytics/ultralytics/assets/68444979/e6e488d6-3d85-4eea-ac9f-a99db036ab22)


I have just installed the latest YOLOv8 version for this test.

**Comment by glenn-jocher** [comment]
@DP1701, I appreciate your close attention to detail and your insightful discovery regarding the batch size discrepancy between training and validation.

The behavior you're observing is indeed noteworthy. In an ideal setup, the validation during and after training should have the same batch size or at least provide consistent results. In practice, however, utilizing a different batch size during validation could potentially lead to variations in results due to batch-normalization layers, which depend on the batch statistics. If your model uses batch normalization, the statistics calculated with different batch sizes could vary, potentially affecting the model's predictions and, consequently, the validation metrics.

Ensuring that you're using the same conditions for both training post-validation and standalone validation is essential for consistency. This includes matching the batch size as noted. It seems that when you align the batch sizes, the validation metrics do indeed match up, which is expected behavior.

However, there should be consistency or at least clear documentation regarding these settings to avoid confusion. It’s possible this could be an oversight or a purposeful design choice within the training routine that needs clarification.

For the time being, as you have identified, explicitly setting the batch size during standalone validation to match the training batch size is a suitable workaround. If you believe this behavior should be modified or better documented within YOLOv8, consider submitting an issue to the GitHub repository for further examination by the maintainers.

Thank you for bringing this to attention, and it would definitely be beneficial for the community to have clearer insights or revised behavior within the validation process to maintain consistency. Your efforts help enhance the robustness of the YOLOv8 project.

**Comment by DP1701** [comment]
@glenn-jocher, thank you for the explanation and for looking at this. I think better documentation would probably be helpful in this case (if it's not a bug). Should I then create a new GitHub issue with a specific tag (bug report)?

**Comment by glenn-jocher** [comment]
@DP1701, you're most welcome, and I'm glad I could provide clarity on the matter.

As for the next steps, creating a GitHub issue would indeed be appropriate to bring this to the attention of the Ultralytics team. It would serve both to further investigate whether this behavior is a bug or an intentional design choice, and to improve the documentation if necessary. Your detailed findings will be highly valuable to other users and to the developers.

When creating the issue, here's a suggestion for the workflow:

1. **Title Clearly**: Summarize the issue briefly but clearly in the title to ensure immediate understanding of the core problem (e.g., "Inconsistent batch size settings during training and standalone validation affect results").

2. **Description**: Provide a detailed description including the steps you took to discover the issue, the observed behavior, and the expected behavior. It will help developers replicate and understand the context of the issue.

3. **Labels**: Apply labels that best categorize the issue. If you're uncertain whether this is a bug or just a point of clarification needed, consider choosing a label such as "bug" or "documentation" based on your best judgment.

4. **Evidence**: Attach necessary screengrabs, logs, or tables that you've generated through your troubleshooting process as you've shared in our discussion.

5. **Environment Details**: List detailed environment setup including OS, Python version, and package versions. This helps in understanding whether the issue might have any dependencies on specific configurations.

6. **Polite and Collaborative Tone**: Maintain a collaborative tone expressing your willingness to help in further investigations if needed. Open Source is built on community interactions and the Ultralytics team values constructive and supportive engagements.

Once your issue is created, it will receive attention from community contributors and Ultralytics developers, who can provide further assistance, and this will potentially lead to a fix or improvement for the YOLOv8 project. Thank you for your contributions, and I'm confident your input will be greatly appreciated by the whole community! 🙏🏻👨🏻‍💻🚀

**Comment by glenn-jocher** [comment]
@Ashutosh1995 the discrepancy you're observing between the validation results directly after training and those obtained using the `val()` function separately can be due to a few reasons. Here are some potential causes and steps you can take to investigate further:

1. **Model State**: Ensure that the model state (weights and biases) is the same when calling `model.val()` as it was at the end of training. If you're reloading the model from a checkpoint or using a different model instance, there might be differences in the model state that could lead to different validation results.

2. **Data Pipeline**: Check if the data preprocessing pipeline is consistent between training and validation. Sometimes, differences in data augmentation, normalization, or other preprocessing steps can lead to variations in performance.

3. **Batch Size**: The batch size used during validation can affect the results. If the batch size during training is different from the batch size during the separate validation, this might cause discrepancies. Batch normalization layers, for example, can behave differently depending on the batch size.

4. **Random Seed**: If there's any randomness in the data loading or augmentation process, ensure that the same random seed is used during both training and validation to maintain consistency.

5. **Evaluation Metrics**: Confirm that the same evaluation metrics and thresholds (e.g., IoU threshold, confidence threshold) are used during both training and validation.

6. **Dataset Split**: Make sure that the same validation dataset is used in both cases. Sometimes, a different split or subset of the data might be used inadvertently.

7. **Software Version**: Ensure that you're using the same version of the Ultralytics YOLOv8 library and other dependencies for both training and validation. Updates or changes in the library could potentially affect the results.

8. **Hardware**: If you're using different hardware or compute resources for training and validation (e.g., different GPUs, CPU vs. GPU), this could also lead to variations in results due to differences in numerical precision.

To debug this issue, you can start by verifying the above points. Additionally, you can check the logs and outputs from the training process to see if there are any messages or warnings that might indicate why the results are different. If the issue persists, you may consider reaching out to the Ultralytics team with detailed information about your environment, model configuration, and the steps you've taken, so they can help you troubleshoot further.

**Comment by Ashutosh1995** [comment]
Thanks @glenn-jocher for your reply! Turns out that some of the parameters in the model.train() were different from model.val(). Kept all the params same and it worked. Almost similar to what @DP1701 had faced ignoring the batch size. My issue is now of overfitting, the seg_loss and dfl_loss are increasing and overfitting the model. Any suggestions around that. I have a total of 1300 images that I have split into train and val. My val set has 471 images to be exact with around 10K instances of a single class that I want to segment.

**Comment by glenn-jocher** [comment]
@Ashutosh1995 the difference in validation results you're observing between the end of training and a standalone validation run can be due to several factors. Here are a few things to consider:

1. **Model State**: Ensure that the model weights are the same during both validations. If you're running `model.val()` after training, it should use the final weights from training. However, if there's any code in between that modifies the model or its weights, this could affect the results.

2. **Data Augmentation**: During training, data augmentation is typically applied to the training dataset but not the validation dataset. If there's any discrepancy in how the data is being processed between training and validation, this could lead to different results.

3. **Batch Size**: Different batch sizes can lead to slight variations in results due to batch normalization layers within the model. Make sure the batch size is consistent between training validation and standalone validation.

4. **Random Seed**: If there's any stochastic process involved in the validation (like random cropping in data augmentation), setting a random seed can help ensure consistency.

5. **Dataset Loading**: Ensure that the same validation dataset is used in both cases with the same loading mechanism. Any differences in dataset shuffling or sampling can lead to different validation results.

6. **Hyperparameters**: Double-check that all hyperparameters (like confidence thresholds and NMS IoU thresholds) are consistent between the two validation runs.

7. **Caching**: If caching is enabled, ensure that the cache is consistent or cleared between runs.

8. **Environment**: Differences in the software environment, such as PyTorch version, CUDA version, or even hardware (using CPU vs. GPU), can sometimes lead to different results.

To troubleshoot this issue, you can:

- Verify that the model weights are indeed the same by saving the model state after training and loading it before the standalone validation.
- Check the data pipeline to ensure consistency in data preprocessing.
- Compare the hyperparameters and settings used in both validation runs.
- Look for any random processes and control them with a fixed seed.
- Ensure that the environment is consistent between runs.

If you've checked all these factors and the issue persists, it might be worth raising an issue in the Ultralytics YOLOv8 GitHub repository with detailed information about your environment, model configuration, and the steps to reproduce the discrepancy. The Ultralytics team or the community may be able to provide more specific guidance.

**Comment by Petros626** [comment]
what is the advantage of using `val=True` for model.train()? If i do not use it, the model is not validated? 

Only in the manual call afterwards e.g. with:
```python
# Validate the model (does this call bbox_iou)
metrics = model.val(data='/home/rlab10/ultralytics/ultralytics/cfg/datasets/kitti_bev.yaml', imgsz=640, 
                    batch=-1, save_json=True, save_hybrid=False, conf=0.5, iou=0.5, max_det=50, half=False,
                    device='cuda', dnn=False, plots=True, rect=False, split='val', project='kitti_bev_yolo', name='val_')

# BEVDetNet metrics (adapted to 40-point interpolation like KITTI)
print(metrics.box.ap50) # AP at IoU threshold of 0.5 for all classes
print(metrics.box.ap70) # AP at IoU threshold of 0.7 for all classes
```

**Comment by glenn-jocher** [comment]
Using `val=True` in `model.train()` enables validation during training, which provides real-time insights into the model's performance on the validation dataset after each epoch. This helps monitor overfitting, convergence, and generalization. If omitted, the model won't validate during training, which could be useful for scenarios like large-scale training where validation might slow down the process or when external validation scripts are preferred. The manual `model.val()` call afterward allows for more customized validation configurations and detailed metric analysis.

**Comment by Petros626** [comment]
@glenn-jocher how to interpret `loss` in Speed metric atfer training? What exactly is measure there?

**Comment by glenn-jocher** [comment]
The `loss` in Speed metrics refers to the time (in milliseconds per image) spent calculating the loss function during validation. This measures only the forward pass through the loss computation layers, separate from inference time. For detailed implementation, see the [validator source code](https://docs.ultralytics.com/reference/engine/validator/#ultralytics.engine.validator.BaseValidator.__call__).

**Comment by Petros626** [comment]
And the loss functions exactly for OBB is then calculating `cls_loss`, `box_loss` and `dfl_loss`?

**Comment by glenn-jocher** [comment]
Yes, for Oriented Bounding Box (OBB) models in YOLOv8, the loss calculation includes **cls_loss** (classification), **box_loss** (rotated box regression), and **dfl_loss** (distribution focal loss). These components are computed in the [`v8OBBLoss.__call__()`](https://docs.ultralytics.com/reference/utils/loss/#ultralytics.utils.loss.v8OBBLoss.__call__) method as part of the OBB-specific loss formulation.
