### ISSUE TITLE
yolov8 val (classify) RuntimeError: stack expects each tensor to be equal size

### ISSUE THREAD

**Issue by Jns-M** [ultralytics/ultralytics#6334]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Val

### Bug

After training a model on a custom dataset, which worked as expected (the validation during the training also worked), I tried to validate my model on the same dataset using following command:

`!yolo task=classify mode=val model={model_path} data={dataset_path}`

Following error is what I got:

`Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 445, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 273, in val
    validator(model=self.model)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/validator.py", line 160, in __call__
    for batch_i, batch in enumerate(bar):
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/build.py", line 42, in __iter__
    yield next(self.iterator)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/collate.py", line 127, in collate
    return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/collate.py", line 127, in <dictcomp>
    return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/collate.py", line 119, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/collate.py", line 162, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [3, 224, 192] at entry 0 and [3, 192, 224] at entry 1`

Why does it work fine while training but not when validating? The images are different sizes and aspect ratios, but shouldn't yolov8 be able to handle this?

### Environment

Ultralytics YOLOv8.0.209 🚀 Python-3.10.12 torch-2.1.0+cu118 CPU (Intel Xeon 2.20GHz)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 27.1/107.7 GB disk)

OS                  Linux-5.15.120+-x86_64-with-glibc2.35
Environment         Colab
Python              3.10.12
Install             pip
RAM                 12.68 GB
CPU                 Intel Xeon 2.20GHz
CUDA                None

matplotlib          ✅ 3.7.1>=3.3.0
numpy               ✅ 1.23.5>=1.22.2
opencv-python       ✅ 4.8.0.76>=4.6.0
pillow              ✅ 9.4.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.3>=1.4.1
torch               ✅ 2.1.0+cu118>=1.8.0
torchvision         ✅ 0.16.0+cu118>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 1.5.3>=1.1.4
seaborn             ✅ 0.12.2>=0.11.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Jns-M the RuntimeError you are encountering is related to the inconsistency in image sizes within your validation batch. YOLOv8 typically requires all images in a batch to have the same size for batch processing, especially in classification tasks, where images are not resized to a common dimension during evaluation.

During training, the dataloader usually performs resizing and padding to ensure all images in a batch are the same dimensions. However, during validation with classification, the transformations applied might differ, which is why the validation worked fine during training but not separately.

To resolve this issue, ensure that the dataset used for validation has a consistent transformation approach as used during training. Specifically, images should be resized or padded to have the same dimensions before they are batched together. This can be done through proper dataset configuration.

Please review the dataloader configuration in your dataset YAML file for the validation dataset, and adjust the `img_size` or the relevant image transformations so that all images are reshaped to a consistent size before batching.

You can refer to the Ultralytics documentation for more guidance on setting up your dataset configurations and understanding the expected input dimensions for model validation.

If you have recently pulled updates from the YOLOv8 repository, make sure to review the latest commits, as they may have introduced changes in the default behavior for image transformations during validation.

Remember to reload your dataset after making changes to the configuration to ensure the updated settings are applied.

**Comment by Jns-M** [comment]
@glenn-jocher Thank you for the answer! Do you have an example how i could use the validation on the same dataset that i train the model on? i have the dataset unzipped into the three splits on the runtime drive and do not use a yaml file.

**Comment by glenn-jocher** [comment]
@Jns-M you're welcome! If you do not have a YAML file configured for your dataset, YOLOv8's auto-configuration feature comes into play, which infers dataset properties from directory structure and content. When you trained your model, YOLOv8 performed this auto-configuration for training which involved resizing your images.

To validate on the same dataset without a detailed YAML configuration, you can use the same structures that were used for training. YOLOv8 should then apply the same transformations during validation. Make sure you point to the same dataset directory during validation, and the data loader should, ideally, infer and apply the necessary image preprocessing steps.

However, I'd recommend setting up a YAML file for proper data management. This file defines the dataset path, class names, and number of classes, which can streamline both training and validation processes, allowing for consistent behavior and results. 

While you might've managed without it during training due to YOLOv8's robustness and flexibility, using a YAML for validation will make sure the same transformations are applied. This would include defining the `img_size` and any other specific augmentations or transformations that need to be consistent during both training and validation.

Overall, it's good practice to maintain a YAML configuration for your datasets when working with YOLOv8 as it ensures reproducibility, consistency in data preprocessing, and seamless transitions between training, validation, and prediction tasks. 

Once you create the YAML file, your validation command will need little modification – just point to the YAML file instead of the `{dataset_path}`, and YOLOv8 will handle the rest. The creation of the YAML file and its proper configuration are clearly detailed in the Ultralytics documentation, should you need guidance in setting it up.

**Comment by Jns-M** [comment]
@glenn-jocher I have to get back on this issue, as I was sadly unable to get the validation to work. Also I tried creating a .yaml file for my dataset, which i have stored locally and do not want to download every time, but I could not get that to work either. Could you provide either a concrete example on how to use the same data preprocessing that train uses for the validation or a concrete example for a .yaml file for a local dataset that sets the image size?

**Comment by glenn-jocher** [comment]
@Jns-M, I'm sorry to hear that you're still having difficulties. Let's try to address both of your concerns.

For ensuring the validation uses the same data preprocessing as training, it's essential to use a dataset configuration file (YAML) that explicitly specifies the image size and any other preprocessing steps. 

Here's an example of how a dataset YAML could be structured for a local dataset for classification:

```yaml
# dataset.yaml
path: ../datasets/your-dataset  # root dir of the dataset
train: train  # relative path to the training images folder
val: val  # relative path to the validation images folder
test: test  # relative path to the test images folder (optional)

# Number of classes in your dataset
nc: 10

# Class names
names: ['class1', 'class2', 'class3', ..., 'class10']

# Image size to resize to during training and validation, maintains aspect ratio
img_size: 640
```

Please replace `../datasets/your-dataset` with the actual path to your dataset, the relative paths `train`, `val`, and `test` with the correct subdirectories of your dataset, if applicable. Replace `nc` with the number of classes in your dataset and list all class names under `names`.

Once you have your YAML file set up, use the following command for validation, specifying your `model_path` and `data` path to the YAML file you created:

```
!yolo task=classify mode=val model={model_path} data={your_yaml_file_path}
```

Replace `{model_path}` with the path to your trained model and `{your_yaml_file_path}` with the path to the YAML file. Make sure that the paths are correctly set based on your current working directory or use absolute paths to avoid any confusion.

Creating this YAML file will standardize the input image size (`img_size`) for both training and validation, ensuring that your images are resized consistently. Make sure that your images are named correctly, and the directory structure is as expected by YOLOv8.

If the images still vary in size after YAML configuration and it continues to cause problems during batching, consider using additional scripts to resize your images to a fixed size before running training and validation.

Remember to double-check the paths you enter in your commands and YAML file to avoid any issues related to file locations, which is a common source of errors when working with local filesystems. 

I hope this helps you move forward with your validation process. If you run into further issues, carefully reviewing the Ultralytics documentation could also provide additional insights and troubleshooting steps.

**Comment by glenn-jocher** [comment]
@JCab09 it seems the batched images are not of equal size, which is causing the error during validation. Check that your dataset's YAML configuration specifies consistent `img_size` for validation. If your images are not square, YOLOv8 will scale the longest edge to `img_size` while maintaining the aspect ratio, potentially leading to varying sizes. 

For validation, you may need to set both dimensions in `img_size` to enforce a fixed resolution (e.g., `img_size: [640, 640]`). This ensures all images are reshaped to the same dimensions. Update your YAML accordingly and reattempt validation.

**Comment by hariouat** [comment]
> I am encountering the same issue when trying to validate my data using the latest ultralytics docker image.
> 
> `RuntimeError: stack expects each tensor to be equal size, but got [3, 640, 416] at entry 0 and [3, 640, 384] at entry 1`
> 
> The images do get scaled, but not equally.

I resolved this by addding batch=1

**Comment by Kaschi14** [comment]
> I am encountering the same issue when trying to validate my data using the latest ultralytics docker image.
> 
> `RuntimeError: stack expects each tensor to be equal size, but got [3, 640, 416] at entry 0 and [3, 640, 384] at entry 1`
> 
> The images do get scaled, but not equally.

I've the same issue even though I added 
image_size: 640 / image_size: [640, 640]
(tried both)
and I'm still getting the same error
`RuntimeError: stack expects each tensor to be equal size, but got [3, 640, 494] at entry 0 and [3, 640, 384] at entry 1`

I don't want to use batch=1 as it would slow down the process

**Comment by glenn-jocher** [comment]
@Kaschi14 setting `img_size: [640, 640]` in your YAML is the correct approach to ensure all images are reshaped to the same dimensions during validation. However, if you are still encountering the `RuntimeError` with stack expecting tensors of equal size, this indicates that the resize transformation is not being applied as it should be.

Ensure that your YAML is correctly formatted and specified in the validation command. Double-check that the paths are correct and the YAML file is being properly loaded by the validation script.

If the issue persists, it may be a bug or an environment-specific problem. Since specifying `batch=1` resolved the issue for another user but is not ideal for you due to speed considerations, you may need to look into the dataloader's collate function or image augmentations to make sure they conform with the resize operation specified in the YAML file.

If this doesn't lead to a resolution, I'd suggest revisiting the documentation or raising an issue in the repository with specific details of your environment setup, dataset, and the exact commands being run. The team or community may be able to provide a fix or suggest an alternative approach for efficient validation without resorting to `batch=1`.

**Comment by sarar1997** [comment]
Okay, I had chance to play with this a lot. I ve tried to validate the same validation folder with  model.val() function. This is not working if your images dont have the same dimensions. Image shapes must be lets say 1080x1080 or 640x640 (this is up to you). when you train the model YOLO resize images it self but when you want to validate the same data, it doesnt work. Thats why you need to resize it 
here is a resize code for all the folders in dataset folder:

from PIL import Image
import os

def resize_image(path, output_size):
    with Image.open(path) as img:
        img = img.resize(output_size)
        img.save(path)

def resize_images_in_directory(directory, output_size):
    for subdir, dirs, files in os.walk(directory):
        for filename in files:
            if filename.lower().endswith(('.png', '.jpg', '.jpeg')):
                resize_image(os.path.join(subdir, filename), output_size)

# The root directory where you want to resize images
root_directory = '/path/'

# The output size you want for your images (e.g., 1080x1080)
output_size = (1080, 1080)

# Resize images in the root directory and all its subdirectories
resize_images_in_directory(root_directory, output_size)

after resizing the folder, try the model.val or CLI version of it.  I hope this helps.

**Comment by glenn-jocher** [comment]
@sarar1997 thank you for sharing your findings and the script to resize images. It's important to note that while YOLOv8 automatically resizes images during training, validation requires images to be preprocessed to consistent dimensions. Your script provides a practical solution for users facing similar issues. For future reference, users can also specify `img_size` in their dataset YAML to ensure images are resized during validation, but this requires images to have the same aspect ratio or padding to be applied. Your contribution to the community is appreciated! 🌟
