### ISSUE TITLE
Is dual RTX 4090 usage possible?

### ISSUE THREAD

**Issue by kbratsy** [ultralytics/ultralytics#6335]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

As part of my work, I will use YoloV8 in my object detection processes. I want to use 2 RTX 4090 as Graphics Cards. However, RTX 4090 graphics cards do not have SLI support. Will this situation cause any problems in my work? So in short, is it possible to use 2 RTX 4090 graphics cards with YoloV8?

Have a nice day

**Comment by RizwanMunawar** [comment]
@kbratsy, it is expected to function, though we haven't conducted internal tests on the performance with dual RTX 4090 during the training process.

**Note:** Dual GPU usage can be only for training. During inference, multiple GPU's support will not required.

**Comment by kbratsy** [comment]
Thank you for your feedback. As far as I understand, the lack of SLI support on RTX 4090 graphics cards is not a problem. So, do you have any tests on previous versions, such as RTX 4080?

**Comment by glenn-jocher** [comment]
@kbratsy yes, that's correct, the lack of SLI support does not impact YOLOv8's ability to utilize multiple GPUs for training, as it relies on data parallelism provided by PyTorch rather than SLI technology. We have not released specific benchmarks or tests for RTX 4080 cards, but YOLOv8 is designed to scale with multiple GPUs, and users have successfully trained models on various multi-GPU setups. The efficiency gains from using multiple GPUs will depend on individual system configurations, data pipeline optimization, and other factors. You can monitor the performance and scaling during your training process to ensure you're getting the expected speedup. For more detailed information on multi-GPU training, please refer to our documentation at https://docs.ultralytics.com.

**Comment by kbratsy** [comment]
Ok. I understand now. Thank you for your fast and effective answers.

**Comment by glenn-jocher** [comment]
You're very welcome, @kbratsy! I'm glad I could assist you. If you have any more questions or need further clarification as you proceed with your work, please don't hesitate to reach out. Wishing you success with your object detection processes using YOLOv8. Have a great day!
