### ISSUE TITLE
RTSP streaming Waiting for stream warning

### ISSUE THREAD

**Issue by jgoo9410** [ultralytics/ultralytics#6339]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

When using RTSP streaming, there are excessive 'WARNING ⚠️ Waiting for stream' messages. 

Not 100% sure, but I think low frame rate streams will cause this behaviour. If the stream is a low frame rate stream, these messages are constant.

 It may be better if they only appear if a stream is unresponsive for a prolonged period of time. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@jgoo9410 hello,

Thank you for bringing this issue to our attention regarding RTSP streaming and the 'WARNING ⚠️ Waiting for stream' messages that you are encountering with YOLOv8.

The warning message you're seeing is intended to alert users when the YOLOv8 predictive system is waiting for new frames to process from the RTSP stream. As you correctly pointed out, streams with a lower frame rate can result in such messages being displayed more frequently, since there is a longer interval between frames.

We aim for a balance between keeping the user informed about potential stream issues and not overwhelming them with repeated warnings. It seems in your case that the balance may not be optimal, especially for low frame rate streams which are in fact operating as expected, albeit at lower acquisition rates.

We appreciate your feedback and suggest that you check whether the stream is consistent but simply providing frames at a low rate, in which case the warnings could be safely ignored. However, the frequency of these messages could indeed be adjusted in future versions for better user experience. We will consider this when we update the streaming components of YOLOv8.

In the meantime, frequent warnings do not necessarily indicate a problem if your low-frame-rate stream is otherwise working fine. The system is designed to handle such conditions by periodically checking for new data and you can continue using the model for your RTSP streams. If your streams frequently have periods of inactivity, you could potentially modify the source code responsible for generating the warning to be less sensitive.

For guidelines on modifying YOLOv8 or to monitor for updates that might address this warning behavior, please refer to our official Ultralytics Documentation.

Your understanding and cooperation are greatly appreciated, and please feel free to report any further issues or contribute suggestions for the Ultralytics YOLOv8 repository.
