### ISSUE TITLE
About the RT-DETR backbone

### ISSUE THREAD

**Issue by WangQvQ** [ultralytics/ultralytics#6352]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I noticed that the Baidu team's RT-DETR provides two versions of the backbone network, ResNet50 and ResNet101. At the same time, in the ultralytics project, I re-implemented the yaml file to match the ultralytics style according to the original ResNet paper. I would like to know if you have requirements for these two versions of the code. I would be happy to submit a Pull Request if needed.😊

### Use case

![image](https://github.com/ultralytics/ultralytics/assets/58406737/fa315a91-b7a6-4f18-b1f3-e3395f5281b1)
![image](https://github.com/ultralytics/ultralytics/assets/58406737/0d9ae6c1-c062-4fc8-b3ae-5ac3c32e9612)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@WangQvQ hello! Thank you for taking the time to search through the Ultralytics YOLOv8 issues and for your willingness to contribute—it's community collaborations like this that help us to improve and grow.

Regarding your interest in implementing ResNet50 and ResNet101 backbones for RT-DETR within our project, that's exciting! We are always glad to see community members eager to expand on the capabilities of our models.

Before you submit a Pull Request, I would suggest considering a few aspects to ensure your implementation aligns well with the project goals and code standards:

1. Make sure that integrating the new backbone aligns with the YOLOv8 model design and does not introduce discrepancies or compatibility issues.
2. Ensure that the code adheres to our coding standards and architecture so that it provides a seamless experience when added to the repository.
3. Test the new backbones thoroughly to verify that they enhance performance without negatively impacting inference speed, memory footprint, etc.

We recommend reading our contribution guidelines in the Ultralytics Docs, which provide detailed information on how to align your contributions with our current codebase and practices.

If your re-implemented yaml files and code modifications have been thoroughly tested and you feel they are ready for review, please go ahead and create a Pull Request. Our team will then be able to review your contribution and potentially integrate it with the main project.

Again, thank you for your enthusiasm and offer to contribute to the Ultralytics YOLOv8 project. The collaborative effort from developers like you is greatly valued!

**Comment by WangQvQ** [comment]
I have submitted the PR!🤝 https://github.com/ultralytics/ultralytics/pull/6661

**Comment by glenn-jocher** [comment]
@WangQvQ, that's fantastic news! 🎉 Your initiative to contribute with a Pull Request is greatly appreciated. Collaboration is the key to evolving our models and enhancing their capabilities.

The team will be looking into your PR soon. Our review process involves ensuring that contributions are:

- **Aligned** with the project's vision.
- **Comprehensive**, including proper testing and documentation.
- **Consistent** with the coding standards and practices of the repo.

This can take a bit of time as we balance reviewing contributions with ongoing development efforts. Rest assured that someone from our team will review your changes and provide feedback or further instructions if necessary.

Thank you once more for your contribution and for being part of the Ultralytics community. We are looking forward to seeing your work integrated into YOLOv8, pending a successful review. Keep an eye on your PR for updates or requests for modification, and feel free to continue engaging and discussing within the community! 👍
