### ISSUE TITLE
Plot by labels

### ISSUE THREAD

**Issue by InfernoidZero** [ultralytics/ultralytics#6353]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm trying to find bad cases for my model. When I use model.val, argument save=True not work. Using save_txt=True I can get some txt labels. How can I plot results by those labels?

**Comment by glenn-jocher** [comment]
@InfernoidZero hello,

I'm glad to help you analyze the performance of your model. It's great to hear you're using the validation feature to find bad cases. While the `save=True` argument indeed saves images with plotted predictions during validation, if this is not working as intended, save_txt=True is a good alternative as it saves the predictions in text format.

To plot the results using these saved text files (which contain predicted bounding boxes), you would typically have a script that reads these text files and the corresponding images, and then overlays the bounding boxes and class labels onto the images.

However, since we're keeping the discussion focused on verbal explanations without code, I will guide you on the general steps you would follow:

1. **Read the Image**: Use an image processing library to load the original image on which the predictions were made.

2. **Parse the Text File**: Open the text file that corresponds to that image. Each line in the text file contains the class, bounding box coordinates, and confidence score (if included). Parse these lines to extract the predicted data.

3. **Draw Bounding Boxes**: For each parsed prediction, use a function that can draw rectangles to plot the bounding boxes onto the images. Assign each box a unique color or label text with the class name and possibly the confidence score.

4. **Display or Save the Image**: Once all bounding boxes have been drawn, you can either display the image using your script or save the modified image to disk for further analysis.

For a detailed explanation on how to implement this, you can check the documentation at https://docs.ultralytics.com where we provide guidance on utilizing the YOLOv8 model outputs and further analyzing them.

Keep in mind that careful inspection and comparison of these plotted results to the ground truth annotations will help you identify and understand the model's performance, particularly in cases where it may not be performing well.

If you're encountering persistent issues with the `save=True` functionality, please do provide details regarding the specific problem, including error messages if any, and we will make sure to further investigate and assist you in resolving the issue. Remember that we're always here to support you in your journey with YOLOv8.

If you have any more questions or need further assistance, feel free to ask. We value your contribution to the YOLOv8 community and are dedicated to improving your experience with our models.

**Comment by InfernoidZero** [comment]
Thanks, I have finished my script to draw boxes in label txt. Now I'm using predict instead, because argument conf, iou don't work for val although will not raise error.
