### ISSUE TITLE
How to get num_anchors if this is not a configurable parameter.

### ISSUE THREAD

**Issue by noahweber1** [ultralytics/ultralytics#6362]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I understand that num_anchors is not configurable parameter for Yolov8, and that this is abstracted away.

However, in order to perform post-processing on the outputs of the onnx model (model that was converted from a Yolo .pt model) one must know:

1. Anchors.
2. Masks of the original model.

Like examplified here:  https://github.com/rockchip-linux/rknn-toolkit2/blob/master/examples/onnx/yolov5/test.py with function "yolov5_post_process"

My question: How can someone post-process Yolo8 onnx model outputs if anchors and masks arent explicitly defined?

**Comment by glenn-jocher** [comment]
@noahweber1 hello,

Thank you for reaching out with your inquiry regarding post-processing on YOLOv8 ONNX model outputs.

YOLOv8 abstracts away certain elements like anchors and masks from user configuration to simplify the training process and reduce the need for manual hyperparameter tuning. For post-processing tasks such as converting raw predictions to bounding box coordinates, confidence scores, and class predictions, this typically happens automatically within the YOLOv8 framework.

When exporting a YOLOv8 model to ONNX format using the `Export` mode within the YOLOv8 framework, the export process should handle the inclusion of the necessary details for anchors and masks within the ONNX model. This enables you to perform post-processing without needing to manually specify anchors or masks.

However, if for some reason you need to manually access the anchor and mask information, these details are defined within the YOLOv8 architecture and are a part of the model itself, which means they can be parsed programmatically by inspecting the model's definition or its configuration files if you're looking into the source code. For direct interaction or custom implementations, parsing the ONNX graph to extract the anchor and mask values is the route you would have to take.

For your reference, the post-processing steps typically involve decoding the raw output tensor(s) to extract the bounding boxes, applying a confidence threshold, and performing non-maximum suppression to remove overlapping boxes. It is important to follow the same logic as implemented in YOLOv8 to ensure consistent and accurate results.

If you need further guidance on post-processing, please refer to the Ultralytics Docs, where more in-depth explanations on model structure and output processing are provided. While the documentation may not directly offer the anchors and masks, it provides insights on how to work with the models and their outputs.

We hope this helps in your development process, and if you have any additional questions, feel free to reach out.

**Comment by noahweber1** [comment]
@glenn-jocher Thank you for the answer.

However, I am confused as Yolo8 is a an anchor-free algorithm. So I checked the configuration and the object properties and there I cant access the anchors or the masks.

So how am I supposed to perform the post-processing and access the bounding boxes with probabilities from my onnx converted model if there is no way to infer the anchors?

**Comment by glenn-jocher** [comment]
@noahweber1, my apologies for any confusion caused.

Given that YOLOv8 operates as an anchor-free algorithm, the concept of predefined anchors is indeed not applicable as it would be for prior YOLO models which relied on anchor boxes. This change is part of the evolution of object detection models towards simplifying the network design and improving performance.

In an anchor-free model like YOLOv8, the detection heads output the bounding box coordinates directly without the need to reference a set of predefined anchor boxes. Post-processing, in this case, would involve decoding the outputs based on the network's design, which typically include the objectness score, bounding box coordinates relative to the cell, and class probabilities.

To perform post-processing on the ONNX model outputs, you will need to apply the appropriate scaling and transformation to these outputs to convert them into absolute coordinates and then apply the confidence thresholding and non-maximum suppression.

These steps are inherently built into the YOLOv8's inference pipeline, which is why when using YOLOv8 through its official interfaces, you get the final predictions without needing to manually handle post-processing steps. When you move to ONNX and intend to perform inference outside of the Ultralytics framework, you'll need to replicate this pipeline.

For your exact needs, I recommend referring to the Ultralytics Docs that detail the output format that YOLOv8 produces and how to interpret it. The documentation will guide you on how the model's outputs are formatted and should provide insights into how you should decode them after running inference with the ONNX model. This will allow you to access the bounding box information along with associated probabilities without requiring anchors.

If detailed technical guidance on this aspect of YOLOv8's ONNX output interpretation is not readily available, this might be an area where our documentation could be expanded upon. We always appreciate feedback from the community to improve our documentation and make the YOLOv8 experience as accessible as possible.

Should you have further questions or need assistance on this topic, do not hesitate to let us know. We're here to help.
