### ISSUE TITLE
FileNotFoundError: Image Not Found 

### ISSUE THREAD

**Issue by TuanBao0711** [ultralytics/ultralytics#6379]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I'am training model yolov8 on gg colab non-pro. My model has 100 epoch, but when I'm training at epoch 18th I get a error: 
a Image Not Found in folder Train/images. I checked and this img and see that still in the folder, so what Issue and how to fix it? 
 
![image](https://github.com/ultralytics/ultralytics/assets/100790756/dc257186-4abb-4439-9735-9113f59254ce)

Error:
    Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/100         7G     0.9924     0.4638     0.9011         31        640:  44% 602/1370 [05:15<07:31,  1.70it/s][ WARN:0@13413.923] global loadsave.cpp:248 findDecoder imread_('/content/drive/MyDrive/tracking_v8/data_v8_1311/train/images/IR_DRONE_090243_106_png.rf.8ca672111538a413744834c2a5197669.jpg'): can't open/read file: check file path/integrity
[ WARN:0@13413.933] global loadsave.cpp:248 findDecoder imread_('/content/drive/MyDrive/tracking_v8/data_v8_1311/train/images/IR_DRONE_003156_247_png.rf.3a59cf53ab2490047e6ef01be43233bc.jpg'): can't open/read file: check file path/integrity
[ WARN:0@13413.952] global loadsave.cpp:248 findDecoder imread_('/content/drive/MyDrive/tracking_v8/data_v8_1311/train/images/IR_DRONE_109262_147_png.rf.4631c699c1d4183f020297dda5323751.jpg'): can't open/read file: check file path/integrity
     18/100         7G     0.9926     0.4639     0.9011         28        640:  44% 603/1370 [05:15<07:31,  1.70it/s][ WARN:0@13413.988] global loadsave.cpp:248 findDecoder imread_('/content/drive/MyDrive/tracking_v8/data_v8_1311/train/images/IR_BIRD_00377_295_png.rf.342b9fbf617919130754199c74f992ac.jpg'): can't open/read file: check file path/integrity
     18/100         7G     0.9922     0.4638      0.901         30        640:  44% 604/1370 [05:16<07:04,  1.81it/s][ WARN:0@13414.459] global loadsave.cpp:248 findDecoder imread_('/content/drive/MyDrive/tracking_v8/data_v8_1311/train/images/IR_BIRD_00680_245_png.rf.d777aae62604cc1d617aecc14fddfbf7.jpg'): can't open/read file: check file path/integrity
     18/100         7G     0.9922     0.4638      0.901         30        640:  44% 604/1370 [05:16<06:40,  1.91it/s]
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 444, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 338, in train
    self.trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 190, in train
    self._do_train(world_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 320, in _do_train
    for i, batch in pbar:
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/build.py", line 42, in __iter__
    yield next(self.iterator)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 694, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/base.py", line 248, in __getitem__
    return self.transforms(self.get_image_and_label(index))
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/base.py", line 254, in get_image_and_label
    label['img'], label['ori_shape'], label['resized_shape'] = self.load_image(index)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/base.py", line 158, in load_image
    raise FileNotFoundError(f'Image Not Found {f}')
FileNotFoundError: Image Not Found /content/drive/MyDrive/tracking_v8/data_v8_1311/train/images/IR_DRONE_090243_106_png.rf.8ca672111538a413744834c2a5197669.jpg

**Comment by RizwanMunawar** [comment]
@TuanBao0711, it appears that the error is arising from GPU usage reaching its limit. Google Colab offers a limited usage window (1-3 hours) for non-pro accounts. Once this limit is reached, GPU usage for data processing is no longer available, and your runtime will be disconnected.

Additionally, there is a possibility that the image is corrupted or unreadable.

Hope this helps! Let me know if you have any additional questions.
Thanks

**Comment by zoushucai** [comment]
I've also encountered this problem frequently, and now I've finally managed to solve it. In summary, the main causes were excessively high CPU temperature and overly aggressive memory frequency settings.

Let me share my troubleshooting and resolution process:

My setup: i7 13700K + Ubuntu 24.04 + 5070Ti.

During each training session, the first few epochs or dozens of epochs would run without issues, but then it would suddenly crash in some later epoch, reporting that an image could not be found. I checked all images and confirmed that none were corrupted, and GPU memory usage was only around 1G, so I shifted my focus to the CPU, memory, and the model itself.

To quickly pinpoint the cause, I designed a simple test: run 150 iterations processing several thousand images. The test showed that training would always crash before reaching 40 iterations. Here is the complete troubleshooting process.

I started by examining the CPU. During training, the average CPU temperature reached 90°C. I consulted Intel technicians, asking whether this could be due to CPU degradation (often colloquially referred to as "shrinkage" or "throttling"). The technician replied that temperature was not the cause and suggested sending the CPU in for inspection, but the process was too cumbersome, so I abandoned that route.

I then upgraded to a better liquid cooler, which brought the average CPU temperature down to around 80°C. I ran training three more times; the first time still encountered the "image not found" error, but only at the 150th iteration. This indicated that reducing the temperature was indeed effective.

Next, I further optimized cooling by increasing the fan speed. In the subsequent training run, the issue was completely resolved, with no interruptions throughout the entire process.

To prevent similar issues in the future, I also examined the memory settings. I was using memory rated at 6400MHz, so I lowered it back to the default 5600MHz as an extra stability measure.

With that, the problem was solved, and training now runs stably.

**Comment by glenn-jocher** [comment]
That aligns with what triggers this exception: `Image Not Found` is raised when OpenCV `imread()` returns `None`, which can happen intermittently from unstable I/O (network/Drive mounts), RAM/CPU instability (OC/thermals), or flaky storage even if the file “exists” on disk; the relevant path is in [`BaseDataset`](https://docs.ultralytics.com/reference/data/base/). If anyone still hits this, try moving the dataset to a local SSD path (not a mounted drive) and set `workers=0` once to rule out multiprocessing + filesystem issues; if it persists on stable hardware, please open a new issue with `yolo checks` output and the full traceback as text.
