### ISSUE TITLE
Documentation Error: vid_stride Incorrectly Described as Boolean

### ISSUE THREAD

**Issue by sorooshsorkhani** [ultralytics/ultralytics#6388]
### Issue Summary

In the documentation for the `Predict` function, the `vid_stride` argument is incorrectly described as a `bool` when it should be an `integer`.

### Documentation Snapshot

| Name            | Type           | Default                | Description                                                                    |
|-----------------|----------------|------------------------|--------------------------------------------------------------------------------|
| `vid_stride`    | `bool`         | `False`                | video frame-rate stride                                                        |

### Observation

I noticed this mistake on the website first. It is present on both the English and Chinese documentation pages:

- English Documentation: [docs/en/modes/predict.md](https://github.com/ultralytics/ultralytics/blob/0473da00a9ad93deadcec8b765774c6d80fc9aa5/docs/en/modes/predict.md?plain=1#L360)
- Chinese Documentation: [docs/zh/modes/predict.md](https://github.com/ultralytics/ultralytics/blob/0473da00a9ad93deadcec8b765774c6d80fc9aa5/docs/zh/modes/predict.md?plain=1#L360)
- Additional Reference: [docs/en/usage/cfg.md](https://github.com/ultralytics/ultralytics/blob/0473da00a9ad93deadcec8b765774c6d80fc9aa5/docs/en/usage/cfg.md?plain=1#L145)

### Impact

The documentation inconsistency can cause confusion for users. When `vid_stride` is set as `True`, it is treated as `1` without error. However, setting it as `False` results in a `ZeroDivisionError`, as illustrated in the following code example:

```python
# Example Code
for result in model.predict(source_video_path, imgsz=1280, stream=True, vid_stride=False):
    # ... (rest of the code)
```
The error traceback:

```python
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
[<ipython-input-29-c55fb22526ba>](https://localhost:8080/#) in <cell line: 12>()
     13 
     14   # detect
---> 15   for result in model.predict(source_video_path, imgsz=1280, stream=True, vid_stride=False):
     16     frame = result.orig_img
     17     detections = sv.Detections.from_ultralytics(result)

5 frames
[/usr/local/lib/python3.10/dist-packages/ultralytics/data/loaders.py](https://localhost:8080/#) in _new_video(self, path)
    350         self.frame = 0
    351         self.cap = cv2.VideoCapture(path)
--> 352         self.frames = int(self.cap.get(cv2.CAP_PROP_FRAME_COUNT) / self.vid_stride)
    353 
    354     def __len__(self):

ZeroDivisionError: float division by zero
```

### Suggested Improvement

The `vid_stride` should be documented as an `integer` to align with its usage in the code examples.

| Name            | Type           | Default                | Description                                                                    |
|-----------------|----------------|------------------------|--------------------------------------------------------------------------------|
| `vid_stride`    | `int`          | `1`                | video frame-rate stride                                                        |

**Comment by glenn-jocher** [comment]
@sorooshsorkhani thank you very much for bringing this issue to our attention. I appreciate the detailed explanation and for highlighting the discrepancies in the documentation regarding the `vid_stride` parameter within the `Predict` mode. Indeed, your observation is correct—the `vid_stride` argument should be documented as an `integer`, not a `bool`.

I acknowledge the potential confusion this may cause among users, and I apologize for any inconvenience it may have caused. I'll make sure our team updates the documentation to reflect the correct data type and default value for the `vid_stride` parameter, thereby improving the clarity and accuracy of our documentation in both the English and Chinese versions.

One should indeed use an integer value for `vid_stride` to specify the stride for frame selection when processing video inputs. The default setting for `vid_stride` should be `1`, implying that every frame is processed. For instance, setting `vid_stride` to `2` would process every other frame, which can reduce computational load at the expense of temporal resolution in the predictions.

The example shown, where `vid_stride` is set to `False`, leads to an understandable `ZeroDivisionError` due to the code attempting to divide by a zero-equivalent value (`False` is implicitly treated as `0` when used in arithmetic operations).

We will rectify this in the documentation as soon as possible. Please continue to share any further issues or suggestions you have regarding our documentation or any other aspect of our software. Our aim is to ensure that users have a smooth and accurate understanding of how to use YOLOv8 and its associated features.

We also encourage you to visit our official documentation at https://docs.ultralytics.com for the latest updates and best practices. If you require further assistance, don't hesitate to ask.

Thanks again, and happy detecting! 🚀
