### ISSUE TITLE
May I ask how to obtain flops and params for YOLOv8?

### ISSUE THREAD

**Issue by xunfeng233** [ultralytics/ultralytics#6417]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question
```
import torch
from thop import clever_format, profile
from torchinfo import summary
from ultralytics import YOLO

if __name__ == "__main__":
    input_shape = [640, 640]
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    m = YOLO("yolov8n-seg.pt")
    dummy_input = torch.randn(1, 3, input_shape[0], input_shape[1]).to(device)
    flops, params = profile(m.to(device), (dummy_input), verbose=False)
    flops, params = clever_format([flops, params], "%.3f")
    print('Total GFLOPS: %s' % (flops))
    print('Total params: %s' % (params))
```
When I want to use this code to obtain the flops and params of YOLOv8, the following error message will appear:
```
Traceback (most recent call last):
  File "/media/chen/E6AA92F15674D9D8/yolo_tow/summary.py", line 24, in <module>
    flops, params = profile(m.to(device), (dummy_input), verbose=False)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chen/anaconda3/lib/python3.11/site-packages/thop/profile.py", line 206, in profile
    prev_training_status = model.training
                           ^^^^^^^^^^^^^^
  File "/media/chen/E6AA92F15674D9D8/yolo_tow/ultralytics/engine/model.py", line 416, in __getattr__
    raise AttributeError(f"'{name}' object has no attribute '{attr}'. See valid attributes below.\n{self.__doc__}")
AttributeError: 'YOLO' object has no attribute 'training'. See valid attributes below.

    YOLO (You Only Look Once) object detection model.
    . Did you mean: 'trainer'?
```

**Comment by glenn-jocher** [comment]
@xunfeng233 hello there! It appears you're trying to profile the YOLOv8 model to obtain the FLOPs and parameters using `thop`, but you're encountering an error due to the attribute `training` not being directly accessible in the YOLO model class.

To resolve the issue mentioned, one potential way is to directly access the underlying model that is wrapped in the `YOLO` class. The `YOLO` class encapsulates the model and provides a simplified interface, so you might need to extract the internal PyTorch model to utilize `thop` for profiling accurately.

Instead of using the `YOLO` object, try accessing the model's attributes that relate directly to the neural network layers. This may involve looking into the internals of the `YOLO` class to find the exact attribute name that contains the model if not directly exposed publicly. Inspecting or modifying the `YOLO` class to provide access to the training attribute could be another path, but this would require coding adjustments which I won't be detailing here.

You might need to use methods within the model that can set and retrieve the training mode or access internal layers where the `training` attribute is typically found. It's crucial to remember that the `training` attribute is available in subclasses of `torch.nn.Module`, which comprise the building blocks for PyTorch models.

If further help is needed, the documentation at https://docs.ultralytics.com could be a valuable resource, as it may offer more insight or guidance specific to using and profiling the YOLOv8 models.

Keep in mind that profiling tools like `thop` may not be directly compatible with all high-level abstractions and interfaces provided in custom classes such as `YOLO`. It often expects a standard PyTorch model as input.

Remember to always refer to any available documentation and if necessary, ask for help in the forums or communities related to the tool or library you're using, as there's a vibrant community out there willing to lend a hand. Happy coding! 🚀

**Comment by xunfeng233** [comment]
> @xunfeng233 hello there! It appears you're trying to profile the YOLOv8 model to obtain the FLOPs and parameters using `thop`, but you're encountering an error due to the attribute `training` not being directly accessible in the YOLO model class.
> 
> To resolve the issue mentioned, one potential way is to directly access the underlying model that is wrapped in the `YOLO` class. The `YOLO` class encapsulates the model and provides a simplified interface, so you might need to extract the internal PyTorch model to utilize `thop` for profiling accurately.
> 
> Instead of using the `YOLO` object, try accessing the model's attributes that relate directly to the neural network layers. This may involve looking into the internals of the `YOLO` class to find the exact attribute name that contains the model if not directly exposed publicly. Inspecting or modifying the `YOLO` class to provide access to the training attribute could be another path, but this would require coding adjustments which I won't be detailing here.
> 
> You might need to use methods within the model that can set and retrieve the training mode or access internal layers where the `training` attribute is typically found. It's crucial to remember that the `training` attribute is available in subclasses of `torch.nn.Module`, which comprise the building blocks for PyTorch models.
> 
> If further help is needed, the documentation at https://docs.ultralytics.com could be a valuable resource, as it may offer more insight or guidance specific to using and profiling the YOLOv8 models.
> 
> Keep in mind that profiling tools like `thop` may not be directly compatible with all high-level abstractions and interfaces provided in custom classes such as `YOLO`. It often expects a standard PyTorch model as input.
> 
> Remember to always refer to any available documentation and if necessary, ask for help in the forums or communities related to the tool or library you're using, as there's a vibrant community out there willing to lend a hand. Happy coding! 🚀

Okay, I see, thank you very much!

**Comment by glenn-jocher** [comment]
You're welcome, @xunfeng233! I'm glad I could assist. If you have any more questions or run into further issues while working with YOLOv8, please don't hesitate to reach out. The community and I are always here to help. Best of luck with your project, and happy coding! 😊👍

**Comment by 2292301049** [comment]
> > @xunfeng233 hello there! It appears you're trying to profile the YOLOv8 model to obtain the FLOPs and parameters using `thop`, but you're encountering an error due to the attribute `training` not being directly accessible in the YOLO model class.
> > To resolve the issue mentioned, one potential way is to directly access the underlying model that is wrapped in the `YOLO` class. The `YOLO` class encapsulates the model and provides a simplified interface, so you might need to extract the internal PyTorch model to utilize `thop` for profiling accurately.
> > Instead of using the `YOLO` object, try accessing the model's attributes that relate directly to the neural network layers. This may involve looking into the internals of the `YOLO` class to find the exact attribute name that contains the model if not directly exposed publicly. Inspecting or modifying the `YOLO` class to provide access to the training attribute could be another path, but this would require coding adjustments which I won't be detailing here.
> > You might need to use methods within the model that can set and retrieve the training mode or access internal layers where the `training` attribute is typically found. It's crucial to remember that the `training` attribute is available in subclasses of `torch.nn.Module`, which comprise the building blocks for PyTorch models.
> > If further help is needed, the documentation at https://docs.ultralytics.com could be a valuable resource, as it may offer more insight or guidance specific to using and profiling the YOLOv8 models.
> > Keep in mind that profiling tools like `thop` may not be directly compatible with all high-level abstractions and interfaces provided in custom classes such as `YOLO`. It often expects a standard PyTorch model as input.
> > Remember to always refer to any available documentation and if necessary, ask for help in the forums or communities related to the tool or library you're using, as there's a vibrant community out there willing to lend a hand. Happy coding! 🚀
> 
> Okay, I see, thank you very much!

Nice to meet you! I have met the same problem. May I ask you for the code to get FLOPs and params?

**Comment by dongfeicui** [comment]
#7633

**Comment by glenn-jocher** [comment]
@dongfeicui hello! For obtaining FLOPs and parameters of YOLOv8, you'll need to access the underlying PyTorch model within the `YOLO` class. The `thop` library expects a standard PyTorch model, so ensure you're passing the correct model object to `profile`. If you're unsure how to extract the model from the `YOLO` class, please refer to the documentation for guidance on interacting with the model's internals. Good luck! 🌟
