### ISSUE TITLE
Pose 

### ISSUE THREAD

**Issue by Alexsade** [ultralytics/ultralytics#6418]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi everyone, I'm using YOLOv8 model to train pose for my dataset, but when i running, i have a error: 

RuntimeError: Dataset '/content/drive/MyDrive/Pose sug/Test Data/config.yaml' error ❌ mapping values are not allowed here
  in "<unicode string>", line 3, column 10:
    kpt_shape: [5, 2]
    
  I don't know what the problem I'm having  
Please help me, thanks everyone

**Comment by glenn-jocher** [comment]
@Alexsade hello! It looks like you're experiencing an issue with your dataset configuration while training for pose estimation using YOLOv8. The error message indicates there might be an issue with the YAML syntax in your `config.yaml` file.

The specific error "mapping values are not allowed here" typically means that there is an unexpected character or a syntax mistake around the line mentioned in the error message. Since YAML is sensitive to indentation and formatting, you'll want to ensure that your `config.yaml` is formatted correctly, with proper indentation and no extraneous characters.

Here are a few steps you can try to resolve the error:

1. Review the `config.yaml` file near line 3 where the error is mentioned. Make sure that you follow YAML syntax rules, such as using spaces for indentation (not tabs) and having a space after the colon in key-value pairs.

2. Ensure that `kpt_shape: [5, 2]` is properly indented and is under the appropriate section in your `config.yaml` file.

3. Validate the structure of your YAML file using an online YAML validator to check for any syntax issues.

4. Refer to the pose task documentation provided by Ultralytics to make sure that your `config.yaml` file adheres to the expected format and configuration. You can find detailed guidance on how to set up your custom dataset for pose estimation in the docs.

If you continue to have trouble after reviewing and correcting your configuration file, please provide more details about the configuration you have set up, ensuring that no sensitive information is shared, and the Ultralytics community will be more than happy to help you troubleshoot further.

**Comment by Alexsade** [comment]
Hi @glenn-jocher, thanks for your comments, I have edited the indentation or removed excess spaces, but when I run it, a new error appears:

RuntimeError: Dataset '/content/drive/MyDrive/Pose sug/Test Data/config.yaml' error ❌ 'str' object does not support item assignment 

It's terrible, I've never had this error before
