### ISSUE TITLE
No labels found in file train.cache

### ISSUE THREAD

**Issue by Alexsade** [ultralytics/ultralytics#6427]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi everyone, 
I don't know why when I run my code, it doesn't have any phenomenon, it runs normally but the parameters like map@0.5, F1, P, R, are all at 0 without any change after each epoch

![Screenshot 2023-11-19 000140](https://github.com/ultralytics/ultralytics/assets/151348285/7389106c-ef30-4f1a-bd8c-ef75e934e003)

I pulled it up and saw an error message:

![Screenshot 2023-11-18 232137](https://github.com/ultralytics/ultralytics/assets/151348285/a76205c5-14ea-4863-8b98-fc41b0897e75)

I think it's because of my path in the YAML file so I checked it very carefully and didn't see any abnormalities. I also checked my data very carefully before training and did not see any abnormalities

I also tried deleting the .cache file and trying again but the result is still the same. 
Please help me. Thanks everyone

**Comment by Kayzwer** [comment]
you can try delete the .cache, and run it again

**Comment by glenn-jocher** [comment]
Hello! It looks like you're experiencing an issue where the model isn't detecting any objects in your dataset, as indicated by the metrics (mAP @Kayzwer.5, F1, P, R) all being zero. The error regarding "No labels found in file train.cache" suggests there might be a problem with your dataset labels or the way they are being located and read by the model during training.

Here's a checklist to help troubleshoot the issue:

1. **Verify Dataset Structure**: Ensure the dataset is organized as expected by YOLOv8. The dataset should contain a directory for images and another for labels, with corresponding names between each image and its label file.

2. **Check Annotation Files**: 
   - Make sure that label files (.txt) correspond to the correct image files with the same name prefix.
   - Confirm label files are not empty and have the correct format: class x_center y_center width height.

3. **Review YAML Configuration**: Double-check the paths specified in the YAML file to ensure they accurately point to the folders of your images and labels.

4. **Inspect Labels**: Look at a few label files to ensure they contain data in the expected format and that the bounding boxes specified actually exist within the image dimensions.

5. **Clear Cache Files**: As recommended before, deleting the .cache files can sometimes resolve path-related issues. However, since you’ve already tried this and the problem persists, it might not be a cache-related issue.

6. **Path Variables**: Check environment variables and relative paths in your setup to ensure that there aren't any that are misleading the training script.

7. **Dataset Sizes**: Validate that the number of items in the dataset matches the number of labels you have created.

If after going through this checklist you're still facing issues, please provide more information about your dataset, including how you prepared your labels, and make sure that your training environment is set up correctly. You can also refer to the documentation on our Docs page for more detailed instructions on configuring datasets and troubleshooting common issues.

Remember, the quality and accuracy of your labels are vital for the training process, so it's crucial to ensure they are in good shape before initiating training. If you need further assistance, don't hesitate to reach out with additional details. We're here to help!
