### ISSUE TITLE
Generated best_integer_quant.tflite from 'success = model.export(format="tflite", int8=True) ' does not work

### ISSUE THREAD

**Issue by harufumigithub** [ultralytics/ultralytics#6432]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

1. Execute python script
from ultralytics import YOLO
model = YOLO("./yolov8n-seg.pt")
success = model.export(format="tflite", int8=True)  
2. It would create 'best_integer_quant.tflite'
3. Run inference

Actual result: Running inference does **NOT** provide any bounding box confidence level

Expected result: Running inference **DOES** provide any bounding box confidence level

### Environment

WARNING ⚠️ Ultralytics settings reset to default values. This may be due to a possible problem with your settings or a recent ultralytics package update. 
View settings with 'yolo settings' or at '/home/trupass/.config/Ultralytics/settings.yaml'
Update settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'.
Ultralytics YOLOv8.0.200 🚀 Python-3.9.12 torch-2.0.1 CUDA:0 (NVIDIA GeForce RTX 3070 Laptop GPU, 7966MiB)
Setup complete ✅ (16 CPUs, 62.4 GB RAM, 196.5/245.0 GB disk)

OS                  Linux-6.2.0-36-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.9.12
Install             pip
RAM                 62.44 GB
CPU                 11th Gen Intel Core(TM) i7-11800H 2.30GHz
CUDA                11.7

matplotlib          ✅ 3.7.1>=3.3.0
numpy               ✅ 1.24.4>=1.22.2
opencv-python       ✅ 4.8.0.74>=4.6.0
pillow              ✅ 10.0.0>=7.1.2
pyyaml              ✅ 6.0>=5.3.1
requests            ✅ 2.27.1>=2.23.0
scipy               ✅ 1.11.1>=1.4.1
torch               ✅ 2.0.1>=1.8.0
torchvision         ✅ 0.15.2+cu117>=0.9.0
tqdm                ✅ 4.65.0>=4.64.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.12.2>=0.11.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

### Minimal Reproducible Example

1. from ultralytics import YOLO
model = YOLO("./yolov8n-seg.pt")
success = model.export(format="tflite", int8=True)  

should generate working 'best_integer_quant.tflite'

THIS DOES NOT WORK

2. You can generate the same file name with command line execution as:
$ yolo export model=./yolov8n-seg.pt format=tflite int8=true 

THIS WORKS

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@harufumigithub hello! Thank you for bringing this issue to our attention. From your description, it seems like you're encountering a problem where exporting a YOLOv8 model to a `tflite` format with integer quantization via the Python interface does not yield the expected inference results, specifically concerning bounding box confidences.

You've already done a significant part of troubleshooting by confirming that the command-line method produces a working `.tflite` file, while the Python method does not. This suggests there might be a discrepancy in how the export is handled between the two interfaces.

The expected behavior, obviously, should be consistent across both Python and command-line usage. Our goal is to ensure that you can reliably export and run inference with quantized models in any supported interface. To address this inconsistency, we'll thoroughly investigate the Python export method for potential bugs or required updates to ensure integer quantization is applied properly.

For now, since you've found that the command line execution works as expected, please continue using that as a workaround. In the meantime, we will prioritize reproducing the issue you've encountered using the Python script approach and seek a resolution. Once we have identified the root cause or have a fix, we will update the repository accordingly.

If you have any more information that you believe could help us solve this problem, such as specific error messages or unusual behavior during the export process, please feel free to add those details.

Your contribution is very valuable, and we appreciate your patience as we work to resolve this matter. Stay tuned to the repository issues for updates, and don't hesitate to reach out if you have further concerns or questions!

**Comment by glenn-jocher** [comment]
@harufumigithub 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. TFlite export with INT8 works correctly in Python:

<img width="1790" alt="Screenshot 2023-11-20 at 20 38 37" src="https://github.com/ultralytics/ultralytics/assets/26833433/31d29a5b-d6ab-4f42-b2ea-9616fd7901fd">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
