### ISSUE TITLE
Yolov8-Pose with Triton not working

### ISSUE THREAD

**Issue by reshmavfy** [ultralytics/ultralytics#6433]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

I have Triton Inference Server running, and it is serving yolov8m-pose model.

```
$ curl localhost:8002/metrics
nv_inference_request_success{gpu_uuid="GPU-d6130b5f-cf17-6a07-ee09-fd948d586b8b",model="yolov8m-pose",version="1"} 0
nv_inference_request_success{model="yolov8m-pose",version="1"} 0
```

While running Inference for Yolov8 Pose model, this is the exception I get. I have attached the inference code below.
```
Exception has occurred: RuntimeError
Trying to create tensor with negative dimension -941: [0, -941]
  File "test_yolov8_track.py", line 172, in yolov8_triton_test
    results = model.track(frame, persist=True)
  File "test_yolov8_track.py", line 232, in <module>
    yolov8_triton_test()
RuntimeError: Trying to create tensor with negative dimension -941: [0, -941]
```

The same code works fine with yolov8 detect model over Triton, but it is not working for pose model. 

Any quick help would be highly appreciated! 

### Environment

```
Ultralytics YOLOv8.0.212 🚀 Python-3.10.12 torch-2.1.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1650, 3904MiB)
Setup complete ✅ (16 CPUs, 7.2 GB RAM, 88.1/116.2 GB disk)

OS                  Linux-6.2.0-36-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             pip
RAM                 7.17 GB
CPU                 AMD Ryzen 7 4800HS with Radeon Graphics
CUDA                12.1

matplotlib          ✅ 3.8.1>=3.3.0
numpy               ✅ 1.23.0>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.0.1>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.29.0>=2.23.0
scipy               ✅ 1.11.3>=1.4.1
torch               ✅ 2.1.1>=1.8.0
torchvision         ✅ 0.16.1>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 2.1.3>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
psutil              ✅ 5.9.6
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
```

### Minimal Reproducible Example

This is the code I am using for the inference. 

```
def yolov8_triton_test():
    model = YOLO('http://localhost:8000/yolov8m-pose', task='pose')

    # Open the video file
    video_path = "/home/harsh/camera_output_udp1.mp4"
    cap = cv2.VideoCapture(video_path)

    # Store the track history
    track_history = defaultdict(lambda: [])
    frame_cnt = 0

    # Loop through the video frames
    while cap.isOpened():
        frame_cnt += 1
        frame_start = time.time()

        # Read a frame from the video
        success, frame = cap.read()

        if success:
            # results = model(frame)

            # Run YOLOv8 tracking on the frame, persisting tracks between frames
            results = model.track(frame, persist=True)

            # Get the boxes and track IDs
            boxes = results[0].boxes.xywh.cpu()
            track_ids = results[0].boxes.id.int().cpu().tolist()

            # Visualize the results on the frame
            annotated_frame = results[0].plot()
            anno = Annotator(annotated_frame)

            # Plot the tracks
            for box, track_id in zip(boxes, track_ids):
                x, y, w, h = box
                track = track_history[track_id]
                track.append((float(x), float(y)))  # x, y center point
                if len(track) > 30:  # retain 90 tracks for 90 frames
                    track.pop(0)

                # Draw the tracking lines
                points = np.hstack(track).astype(np.int32).reshape((-1, 1, 2))
                cv2.polylines(annotated_frame, [points], isClosed=False, color=(230, 230, 230), thickness=10)

            duration = time.time() - frame_start
            fps = 1/duration
            anno.frame_count_fps_dur(frame_cnt, fps, duration)

            # Display the annotated frame
            cv2.imshow(f'Inference', annotated_frame)

            # Break the loop if 'q' is pressed
            if cv2.waitKey(1) & 0xFF == ord("q"):
                break
        else:
            # Break the loop if the end of the video is reached
            break

    # Release the video capture object and close the display window
    cap.release()
    cv2.destroyAllWindows()
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@reshmavfy hello there, thanks for bringing this issue to our attention, and for providing detailed information about the environment and steps to reproduce the issue with the YOLOv8 pose model on Triton Inference Server. I apologize for the inconvenience you're facing.

The error you've encountered seems to suggest an issue with tensor dimensions in the model results, specifically a negative dimension size, which is unexpected. This indicates that somewhere in the data flow between retrieving an inference result and processing it, there becomes an inconsistency or error in the tensor shapes.

Since the same code is working with the detect model, it's possible that there are differences in the output format or required input pre-processing between the detect and pose models on Triton that aren't being accounted for.

Here are a few steps you might consider to debug the issue:

1. **Check Model Input/Output**: Ensure that the YOLOv8 pose model's inputs and outputs expected by Triton server match the format you're sending in and receiving from the server.
2. **Triton Server Configuration**: Verify that the Triton server configuration for the pose model is correct, including input/output data types and dimensions.
3. **Model Export**: If you've exported the model yourself, double-check the export process to make sure it's compatible with Triton, including the layer outputs that are being used for pose estimation.
4. **Model Testing**: If possible, test the model locally with a simple script using the YOLOv8 Python interface you're calling to ensure it works before deploying to Triton.
5. **Server Logs**: Check the Triton Inference Server logs for any additional clues as to why it might be returning invalid tensor dimensions.

Since this may require a bit of back-and-forth to troubleshoot, I would recommend continuing to document any changes you make and the results. You may also want to engage with the Triton community or their support channels if the issue seems related to the server's handling of the model.

For advanced configuration and detailed troubleshooting steps specific to YOLOv8, you might want to refer to our documentation. If you consistently encounter difficulties, please continue to provide updates on this issue, including any additional logs or error messages you may receive following your debugging attempts. Such collective efforts enable us to improve and ensure that our models operate smoothly across diverse platforms and use cases.

Remember, the YOLO community and the Ultralytics team are here to assist and we value your contribution to making YOLOv8 even more robust and user-friendly. Keep up the great work and don't hesitate to reach out if you make progress or need further assistance! 🚀

**Comment by reshmavfy** [comment]
Hi @glenn-jocher Thanks for your response. Here is some more info to help debug this further.

First off, I am using the same PBTXT file for both Detect model and Pose model based on the documentation. Not sure if this is the right thing to do.

Config file for yolov8s
```
name: "yolov8s"
platform: "onnxruntime_onnx"
max_batch_size: 0
input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [1, 3, 640, 640 ]
  }
]
output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [-1, -1, -1]
  }
]
```


Config file for yolov8m-pose
```
name: "yolov8m-pose"
platform: "onnxruntime_onnx"
max_batch_size: 0
input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [1, 3, 640, 640 ]
  }
]
output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [-1, -1, -1]
  }
]

```

The issue happens during the post-process, specifically during non_max_suppression() function. By default, yolo assumes the number of classes is 999, whereas the prediction coming from Triton model has the shape of `[1, 56, 8400]`

```
> prediction.shape
torch.Size([1, 56, 8400])
```

Model class names:
```
pprint.pprint(self.model.names)
{0: 'class0',
 1: 'class1',
 2: 'class2',
 3: 'class3',
 4: 'class4',
 5: 'class5',
 6: 'class6',
 7: 'class7', 
 ...
```

This is where things are breaking:
```
# non_max_suppression() in ops.py

# prediction.shape is of size [1, 56, 8400]

# nc is 999 due to self.model.names
nc = nc or (prediction.shape[1] - 4)  # number of classes

# nm becomes -947 at this line.    
nm = prediction.shape[1] - nc - 4
```

Hopefully this helps debug it further? Let me know if you need any other information. Thank you!

**Comment by glenn-jocher** [comment]
Hi @reshmavfy, thank you for the additional details; they are very helpful in narrowing down the issue.

The problem appears to arise from a mismatch between the expected number of classes and the actual number of outputs the model provides. The configuration files you've shared indicate flexible output dimensions with `dims: [-1, -1, -1]` for both the YOLOv8 Detect and Pose models; however, the output tensor shape for the Pose model should include the keypoints in its dimensions.

For pose estimation, the model output dimensions are typically `[batch, (5 + keypoints) * number_of_anchors, grid_height * grid_width]`, differing from detection models, which output `[batch, (4 + 1 + number_of_classes) * number_of_anchors, grid_height * grid_width]`. Here the `(5 + keypoints)` term accounts for the bounding box coordinates, the confidence score, and the keypoints, instead of the `(4 + 1 + number_of_classes)` term, which accounts for the bounding box coordinates, the confidence score, and the class predictions.

In your Triton configuration for the YOLOv8m-pose model, the dims for output are set to `[-1, -1, -1]`, which is too flexible and leads to post-processing code in `non_max_suppression()` failing to interpret the output correctly, as it incorrectly assumes the number of classes to be 999.

To address this issue, you should adjust the config file for the YOLOv8m-pose model to accurately reflect the output structure of the pose estimation model, making sure to specify the correct number of keypoints. Unfortunately, I can't provide the exact dimensions without knowing the total number of keypoints, but it's crucial that they match what the model is actually outputting.

Here's a general direction with a placeholder `<number_of_keypoints>` that you would need to replace with the correct value:

```plaintext
output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [1, (5 + <number_of_keypoints>) * number_of_anchors, grid_height * grid_width]
  }
]
```

Please ensure that you update the configuration with the right values for:

- `<number_of_keypoints>`: the total number of keypoints the model is detecting.
- `number_of_anchors`: the number of anchors used by the model.
- `grid_height` and `grid_width`: dimensions of the grid that the model operates on.

After updating the configuration file, you'll also want to ensure that the post-processing code correctly interprets these dimensions, expecting the keypoints as part of the model output.

Since I cannot provide the exact configuration without additional model specifics, you will likely need to refer to the YOLOv8 documentation and the Triton documentation to verify these parameters for your use case. If you've trained the pose model yourself, you should have this information available. Otherwise, you might need to refer back to the source from which you've obtained the pose model.

As always, if you encounter any further issues or need clarification, do not hesitate to reach out. We're here to help ensure you can successfully integrate YOLOv8 pose capabilities into your Triton-based workflow. 🌟

**Comment by reshmavfy** [comment]
Thanks @glenn-jocher for your answer. This is default yolov8m-pose model exported to ONNX based on [yolov8 triton documentation](https://docs.ultralytics.com/guides/triton-inference-server/?h=triton). No custom changes were made here.

I followed your advice and updated the model's output0 shapes in Triton as follows:

```
name: "yolov8m-pose"
platform: "onnxruntime_onnx"
max_batch_size: 0
input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [1, 3, 640, 640 ]
  }
]
output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [1, 56, 8400]
  }
]
```

However, triton server now complains that it is unable to load the model as it expects the model output to be `[-1, -1, -1]`.

```
2023-11-19 20:06:49 : [ERR] Failed to load model: yolov8m-pose, status code: 400, response: {"error":"load failed for model 'yolov8m-pose': version 1 is at UNAVAILABLE state: Invalid argument: model 'yolov8m-pose', tensor 'output0': the model expects 3 dimensions (shape [-1,-1,-1]) but the model configuration specifies 3 dimensions (shape [1,56,8400]);\n"}
```

**Comment by glenn-jocher** [comment]
Thank you for your patience and updates, @reshmavfy. The error message you're receiving from Triton indicates that the model itself was exported with flexible dimensions in mind, hence the `[-1, -1, -1]` expectation. When Triton expects such dynamic shapes, but the configuration file declares a static shape, it leads to a conflict that prevents model loading.

Since you've used the default YOLOv8m-pose model, and followed the documentation without custom modifications, the next step would be to ensure that the Triton server correctly handles dynamic batching and dynamic shapes. For models with variable output sizes, Triton needs to be configured to support shape inference.

Here are a couple of follow-up actions you can take:

1. **Dynamic Batching**: You may want to look into Triton's [dynamic batching support](https://docs.ultralytics.com/guides/triton-inference-server/?h=triton#configure-dynamic-batching). Ensure that dynamic batching is configured properly in the model repository configuration.

2. **Shape Inference**: Triton supports shape and data type inference directly from the ONNX model. Make sure the server is not overridden by the configuration to expect static shapes if the model was truly exported with dynamic axes. You can refer to Triton's model configuration documentation on [how to configure models with dynamic shapes](https://docs.ultralytics.com/guides/triton-inference-server/?h=triton#auto-complete-model-configuration).

3. **Model Testing**: Independently of Triton, test the ONNX model with an ONNX runtime to ensure that the model's outputs are as expected. This can help clarify if the issue lies with the model export or Triton's interpretation of the model.

4. **Model Configuration Auto-Completion**: Triton has a feature to auto-complete the model configuration based on the model definition. It will detect the input and output shapes, data types, and other model attributes directly from the model file (in this case, the ONNX file) and fill in the missing parts of the model configuration for you. You might want to let Triton server auto-complete the model configuration and then inspect what it populates for the dynamically shaped outputs.

The explicit declaration of dimensions (e.g., `[1, 56, 8400]`) in the configuration file might not always be the best approach if a model has outputs with dynamic shapes. Triton should, ideally, be able to handle the variable dimensions of the model's output tensors, provided that the dynamic shape capabilities are utilized correctly.

Let me emphasize that since the Triton server is responsible for loading and serving the model, ensuring Triton's configuration compatibility with the served models is key. The documentation and the Triton community may have additional insights into configurations for dynamic outputs of ONNX models.

Once again, please continue to document any changes and observations. With these adjustments, we're hopeful that you'll overcome the issues with the Triton Inference Server serving the YOLOv8m-pose model. If further discrepancies persist, continued dialogue will aid in uncovering the solution. Keep at it, and the breakthrough is surely within reach! 🌐

**Comment by reshmavfy** [comment]
Thanks @glenn-jocher for your response!

I tried a few things and wanted to share the summary here.

1. I exported the ONNX model without dynamic shapes, but still faced the same issue. 
2. I compared side-by-side of using yolov8m-pose directly, and with using Triton. While using Triton with pose, we need to have the autobackend class have `names` and `keypt_shape` fields present. 

I made the following changes in autobackend.py, and it is working fine now. (Works with both dynamic and static shapes). 

```
git diff ultralytics/
diff --git a/ultralytics/nn/autobackend.py b/ultralytics/nn/autobackend.py
index 10ac2c4e..f2705c8f 100644
--- a/ultralytics/nn/autobackend.py
+++ b/ultralytics/nn/autobackend.py
@@ -289,6 +289,8 @@ class AutoBackend(nn.Module):
             check_requirements('tritonclient[all]')
             from ultralytics.utils.triton import TritonRemoteModel
             model = TritonRemoteModel(w)
+            names = ['person']
+            kpt_shape = [17, 3]
```


I know this is a hacky fix and we should get this information from the triton client somehow. But I looked into all the methods provided by triton client, and couldn't find any methods that would return this information. Here are a few methods I tried:

```
self.triton_client.get_model_metadata(endpoint)
# returns a class with:
'name':'yolov8m-pose'
'versions': ['1']
'platform':'onnxruntime_onnx'
'inputs':
  0: {'name': 'images', 'datatype': 'FP32', 'shape': [1, 3, 640, 640]}
'outputs':
  0: {'name': 'output0', 'datatype': 'FP32', 'shape': [1, 56, 8400]}
```

For example, in onnxruntime backend - this information is obtained through `metadata = session.get_modelmeta().custom_metadata_map`. However, we don't have such metadata available through Triton server anywhere.

Let me know how to proceed further on this. 

![image](https://github.com/ultralytics/ultralytics/assets/150951935/535b0c54-c468-42d4-a042-5d47a234beba)

**Comment by glenn-jocher** [comment]
Hello @reshmavfy,

Wonderful to hear you've made progress and identified a potential solution for the Triton deployment of YOLOv8m-pose! That said, the changes you're making to `autobackend.py` are indeed a workaround rather than a root fix, as hardcoding values like `names` and `keypt_shape` restricts the flexibility of the `AutoBackend` to work with multiple models seamlessly.

While it's great that your changes enable YOLOv8m-pose to work via Triton, providing a universal solution is ideal. You've rightly pointed out that we prefer a way to dynamically acquire these attributes (`names` and `keypoints details`) from the Triton client's responses or metadata, which would allow the `AutoBackend` to adapt to any model deployed on the Triton Inference Server.

Currently, the Triton client's API may not expose these specific model details directly. A good approach here would be to enhance Triton's current API or use the available API to infer the necessary details. If Triton's current client API does not provide a method to return the necessary metadata related to classes and keypoints:

1. **Feature Request**: Consider opening a feature request with the Triton development team for exposing additional model metadata relevant to use-cases such as yours that can enrich the client's API.

2. **Documentation and Community**: Engage with Triton's documentation further and seek the expertise of the Triton community. Someone might have encountered and solved a similar issue or may offer insights into a less hacky workaround or a more robust fix.

3. **Metadata File**: Another temporary fix might include shipping a metadata file alongside your ONNX model that can be read by `AutoBackend` when the model is loaded to retrieve model specifics like class names and keypoints configuration. While not as clean as directly pulling from Triton, it is a step above hardcoding and maintains compatibility across different models without modifying the primary codebase.

4. **Custom Extension**: If urgent, build a custom extension to the Triton server that provides the additional metadata. Of course, this involves more complexity and requires careful maintenance but can serve as an interim solution while waiting for an official feature enhancement from Triton.

Since `autobackend.py` is part of the core logic within the YOLOv8 lib, it's essential to come up with a more structured solution that maintains the cleanliness and adaptability of the code. Given the collaborative nature of open-source development, contributions from skilled and inventive users like yourself often yield new functionalities and improvements.

Keep documenting any further tweaks or findings you have. Your efforts not only help in addressing your immediate use-case but could also significantly benefit the broader community of users. If the modifications mature into a robust and applicable feature, consider discussing the potential for a pull request with contributions to be reviewed and possibly integrated into the Ultralytics repository – we always appreciate contributions to improve the ecosystem. 🛠️

Keep up the great work, and let's continue making strides toward seamless deployments with Ultralytics and Triton! 🌟

**Comment by hmurari** [comment]
Hello @glenn-jocher Thanks for your guidance for how to approach this. I will request Triton development teams to add native support for retrieving model meta information like kpt_shape etc.

In the meanwhile, I have worked on a PR which is not as hacky as the hardcoded fix above. Please let me know any feedback for it.

1. It assumes that the `config.pbtxt` has two additional parameters, one for "kpt_shape" and another for "names":
```
name: "yolov8m-pose"
platform: "onnxruntime_onnx"
max_batch_size: 0
input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [1, 3, 640, 640 ]
  }
]
output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [1, 56, 8400]
    label_filename: "labels.txt"
  }
]
parameters: {
    key: "kpt_shape"
    value: {
        string_value: "[17, 3]"
    }
}
parameters: {
    key: "names"
    value: {
        string_value: "person"
    }
}
```
2. This allows Triton to pull these parameters on the client side. The changes required on yolo side are fairly modest - would be great if you can review it. 

[Support for yolov8-pose models over triton](https://github.com/ultralytics/ultralytics/pull/6477) 

Thank you again for your help! Let me know any changes needed for the PR.

**Comment by glenn-jocher** [comment]
Hello @hmurari,

It's fantastic to see your proactive approach and commitment to enhancing the functionality of YOLOv8 with Triton. Your proposed solution of adding additional metadata to the `config.pbtxt` file and retrieving it from the Triton client side is indeed a cleaner way to handle this requirement, providing a formalized and scalable method to pass model-specific information.

The PR you submitted offers a potentially valuable contribution to the YOLOv8 Triton integration. While I'm unable to review code or PRs myself, I can reinforce the best practices for contribution:

1. **Documentation**: Ensure that your changes are well-documented within the code as well as within the PR description. Explain the purpose of the additions in the `config.pbtxt` and how they should be structured.

2. **Fallback**: It might be beneficial to include fallback defaults or error handling for cases where this additional metadata is not provided in the `config.pbtxt` to ensure backward compatibility and robustness.

3. **Examples**: Include an example `config.pbtxt` file or update the documentation to reflect your suggested changes, so users can easily understand how to set up their models for Triton with YOLOv8.

4. **Testing**: Highlight any testing that was done to confirm the changes work as intended, including both positive testing (configurations with kpt_shape and names parameters set) and negative testing (configurations without those parameters).

5. **Community Feedback**: Engage with the community for feedback on your PR. This could involve asking for code reviews from maintainers or other contributors, taking into consideration any suggestions they may make.

By providing clear and concise documentation, testing rigorously, and remaining open to feedback from the YOLO development team and the community, your PR could stand a strong chance of being reviewed positively by the maintainers.

Remember that contribution goes beyond code; advocating for Triton development teams to support model metadata natively is another impactful way to contribute, potentially benefiting a multitude of projects that rely on Triton for inference.

Contributions such as yours help to drive open-source projects forward. I commend your hands-on approach to solving problems encountered, and your willingness to share these solutions with the community. Keep up the excellent work and thank you for actively enhancing the collaboration between YOLOv8 and Triton! 🌟

**Comment by vchaparro** [comment]
Hi @glenn-jocher , @hmurari ,

This is the same problem as the one reported here https://github.com/ultralytics/ultralytics/issues/5922, right?

Would a similar solution as @hmurari's PR may help to solve the problem for regular yolov8 models as well?

**Comment by glenn-jocher** [comment]
@vchaparro hi there,

Yes, it appears the issue is related to the one reported in issue #5922. The proposed solution involving adding metadata to the `config.pbtxt` for Triton may indeed help resolve the problem for the YOLOv8 segment model as well. You would need to adjust the metadata to reflect the specifics of the segmentation model, particularly the output dimensions and class labels, if they differ from the pose model. It's important to tailor the config to match the particular needs of each model variant.

Keep in mind to properly test the Triton configuration with your model after making any changes to ensure compatibility and functionality. 🧪

**Comment by hmurari** [comment]
Hello @glenn-jocher Saw this issue got closed from earlier. Can you please let me know what is the status of this merge? It's been pending for quite a while now, would really appreciate if we can prioritize and merge this.

**Comment by glenn-jocher** [comment]
Hello @hmurari,

Thanks for reaching out and your patience on this! 🙌 We understand the importance of this merge for your workflows. The merge is currently under final review to ensure compatibility and maintain the quality of the project. 

We're aiming to integrate it smoothly as soon as possible. Your understanding and support are much appreciated while we wrap this up. 

Stay tuned for updates soon!

**Comment by OBEsensia** [comment]
> Hi [@reshmavfy](https://github.com/reshmavfy), thank you for the additional details; they are very helpful in narrowing down the issue.
> 
> The problem appears to arise from a mismatch between the expected number of classes and the actual number of outputs the model provides. The configuration files you've shared indicate flexible output dimensions with `dims: [-1, -1, -1]` for both the YOLOv8 Detect and Pose models; however, the output tensor shape for the Pose model should include the keypoints in its dimensions.
> 
> For pose estimation, the model output dimensions are typically `[batch, (5 + keypoints) * number_of_anchors, grid_height * grid_width]`, differing from detection models, which output `[batch, (4 + 1 + number_of_classes) * number_of_anchors, grid_height * grid_width]`. Here the `(5 + keypoints)` term accounts for the bounding box coordinates, the confidence score, and the keypoints, instead of the `(4 + 1 + number_of_classes)` term, which accounts for the bounding box coordinates, the confidence score, and the class predictions.
> 
> In your Triton configuration for the YOLOv8m-pose model, the dims for output are set to `[-1, -1, -1]`, which is too flexible and leads to post-processing code in `non_max_suppression()` failing to interpret the output correctly, as it incorrectly assumes the number of classes to be 999.
> 
> To address this issue, you should adjust the config file for the YOLOv8m-pose model to accurately reflect the output structure of the pose estimation model, making sure to specify the correct number of keypoints. Unfortunately, I can't provide the exact dimensions without knowing the total number of keypoints, but it's crucial that they match what the model is actually outputting.
> 
> Here's a general direction with a placeholder `<number_of_keypoints>` that you would need to replace with the correct value:
> 
> ```
> output [
>   {
>     name: "output0"
>     data_type: TYPE_FP32
>     dims: [1, (5 + <number_of_keypoints>) * number_of_anchors, grid_height * grid_width]
>   }
> ]
> ```
> 
> Please ensure that you update the configuration with the right values for:
> 
> * `<number_of_keypoints>`: the total number of keypoints the model is detecting.
> * `number_of_anchors`: the number of anchors used by the model.
> * `grid_height` and `grid_width`: dimensions of the grid that the model operates on.
> 
> After updating the configuration file, you'll also want to ensure that the post-processing code correctly interprets these dimensions, expecting the keypoints as part of the model output.
> 
> Since I cannot provide the exact configuration without additional model specifics, you will likely need to refer to the YOLOv8 documentation and the Triton documentation to verify these parameters for your use case. If you've trained the pose model yourself, you should have this information available. Otherwise, you might need to refer back to the source from which you've obtained the pose model.
> 
> As always, if you encounter any further issues or need clarification, do not hesitate to reach out. We're here to help ensure you can successfully integrate YOLOv8 pose capabilities into your Triton-based workflow. 🌟

#Hello @all,

@glenn-jocher I have been trying to setup a  yolov8n-pose model trained on a custom dataset into Triton Inference Server too. It has a skeleton made of 15 points instead of 17 and I have an output dimension of 50 (instead of 56). So I think something is wrong in the formula you gave but I may be missing something... Should it be:
```json
output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [1, 5 + (<number_of_keypoints> * number_of_anchors), grid_height * grid_width]
  }
]
```
where `number_of_anchors = 3`?

A last question generaly where can we get `number_of_anchors` for a pose model?

**Comment by glenn-jocher** [comment]
@OBEsensia good catch – you’re right to be suspicious of that earlier formula. For YOLOv8/YOLO11 pose the exported head is anchor‑free, and the output shape is `[batch, C, N]` with `C = 4 + nc + 3 * num_keypoints` and `N` the number of locations (e.g. 8400 for 640×640 from 80×80, 40×40 and 20×20). So for your custom model with 15 keypoints and one class you should get `C = 4 + 1 + 3*15 = 50`, which matches what you see; there is no separate `number_of_anchors` factor to include, and you generally don’t need an anchor count at all for pose models in this family.

**Comment by OBEsensia** [comment]
@glenn-jocher thanks for the clarification around the anchor in pose contexte. Can I state that the 3 is link to the second dimension of keepoints? Or is it more related to a triplet X,Y and score?

**Comment by glenn-jocher** [comment]
Yes, that `3` comes directly from the second dimension of `kpt_shape` and represents the three values per keypoint, i.e. a triplet like `(x, y, visibility/score)` for each keypoint, not anything anchor‑related; if you configured `kpt_shape=(num_kpts, 2)` instead, the channel count would become `4 + nc + 2 * num_kpts` accordingly. For more detail on the pose keypoint layout you can also check the [pose keypoints docs](https://docs.ultralytics.com/tasks/pose/).
