### ISSUE TITLE
my code for detecting droplets using a custom yolov8 model is suddenly not working because apparently the file for the model is not found even though it's there

### ISSUE THREAD

**Issue by CrimWasTaken** [ultralytics/ultralytics#6434]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

 File "c:\Users\me\anaconda3\envs\yolov8\drip_rate_sayer_webcam1.py", line 9, in <module>  
    model=YOLO("yolov8m_custom1.pt")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\me\anaconda3\envs\yolov8\ultralytics\engine\model.py", line 91, in __init__
    self._load(model, task)
  File "c:\Users\me\anaconda3\envs\yolov8\ultralytics\engine\model.py", line 136, in _load  
    self.model, self.ckpt = attempt_load_one_weight(weights)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\me\anaconda3\envs\yolov8\ultralytics\nn\tasks.py", line 588, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\me\anaconda3\envs\yolov8\ultralytics\nn\tasks.py", line 527, in torch_safe_load
    return torch.load(file, map_location='cpu'), file  # load
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\anaconda3\envs\yolov8\Lib\site-packages\torch\serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\anaconda3\envs\yolov8\Lib\site-packages\torch\serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\anaconda3\envs\yolov8\Lib\site-packages\torch\serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'yolov8m_custom1.pt'

### Environment

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.11.5
Install             pip
RAM                 13.87 GB
CPU                 AMD Ryzen 7 5800H with Radeon Graphics
CUDA                11.8

matplotlib           3.7.2>=3.3.0
numpy                1.23.5>=1.22.2
opencv-python        4.7.0.72>=4.6.0
pillow               10.0.0>=7.1.2
pyyaml               6.0.1>=5.3.1
requests             2.31.0>=2.23.0
scipy                1.11.1>=1.4.1
torch                2.0.1+cu118>=1.8.0
torchvision          0.15.2+cu118>=0.9.0
tqdm                 4.66.1>=4.64.0
pandas               2.0.3>=1.1.4
seaborn              0.12.2>=0.11.0
psutil               5.9.5
py-cpuinfo           9.0.0
thop                 0.1.1-2209072238>=0.1.1

### Minimal Reproducible Example

from ultralytics import YOLO
import cv2
import cvzone
import math
from sort import *

cap = cv2.VideoCapture(0)

model=YOLO("yolov8m_custom1.pt")

classNames = ["droplet"]

mask = cv2.imread("mask3.png")

#Tracking
tracker = Sort(max_age=3, min_hits=3, iou_threshold=0.5)

dropFactor = input("What is the drop factor of the IV Setup? (gtt/mL): ")
initialDripRate = input("What is your desired drip rate? (gtt/min): ")
print("You have entered {initialDripRate} gtt/min desired drip rate with a {dropFactor} gtt/mL drop factor, starting analysis".format(initialDripRate=initialDripRate, dropFactor=dropFactor))

while True:
    success, img = cap.read()

    resized_mask = cv2.resize(mask, (img.shape[1], img.shape[0]))
    imgRegion = cv2.bitwise_and(img, resized_mask)

    results = model(imgRegion, stream=True, verbose=False)

    detections = np.empty((0, 5))

    for r in results: 
        boxes = r.boxes
        for box in boxes:
        #bounding box
            x1, y1, x2, y2 = box.xyxy[0]
            x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
        # cv2.rectangle(img, (x1, y1), (x2, y2), (255, 0, 255), 3)
            w, h = x2-x1, y2-y1
            cvzone.cornerRect(img, (x1, y1, w, h), l=9)
        #Confidence
            conf = math.ceil((box.conf[0]*100))/100
        #Class Name
            cls = int(box.cls[0])
            currentClass = classNames[cls]

            if currentClass == "droplet" and conf > 0.8:
                cvzone.cornerRect(img, (x1, y1, w, h), l=9, rt=3)
                currentArray = np.array([x1, y1, x2, y2, conf])
                detections = np.vstack((detections, currentArray))
                
        resultsTracker = tracker.update(detections)

        #Puts bounding boxes with text around droplets 
        for result in resultsTracker:
            x1, y1, x2, y2, id = result
            x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
            print(result)
            cvzone.cornerRect(img, (x1, y1, w, h), l=9, rt=2, colorR=(255, 0, 0))
            cvzone.putTextRect(img, f' {int(id)}', (max(0, x1), max(35, y1)), 
                                    scale=2, thickness=2, offset=5)
            
            detectionsPerSecond = detections.shape[0]

            # Compute and display the drip rate
            finalDripRate = detectionsPerSecond * dropFactor
            print("The computed drip rate is {finalDripRate} gtt/min".format(finalDripRate=finalDripRate))

        cv2.imshow("Image", img)
        if cv2.waitKey(25) & 0xFF == ord('q'):
            break

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@CrimWasTaken hi there!

It appears that the issue you're encountering is due to the YOLOv8 model file `yolov8m_custom1.pt` not being located by your script. Here are some steps to troubleshoot this:

1. **Check The Model File Path:** Make sure that the path provided to `YOLO()` is correct and that the file `yolov8m_custom1.pt` is indeed in the directory you're working from. If you're using a relative path, verify that it's relative to the current working directory the script is executed from.

2. **Verify File Presence:** Double-check that the `.pt` file is not renamed, moved, or deleted. You can do this by manually verifying the presence of the file in the expected directory.

3. **Permissions Check:** Ensure that your user account has the necessary permissions to read the model file. This can be an issue sometimes on different operating systems.

4. **Correct Environment:** Ensure that you're running your script in the correct Python environment where YOLOv8 is installed and properly configured.

5. **Check For Typos:** Ensure that there's no typo in the filename within your script.

If you've verified all of the above and are still facing issues, one potential workaround is to provide the absolute path to your model file in the `YOLO()` function just as a sanity check. If that solves the issue, it points towards a problem with the relative path or working directory.

If you have confirmed the correct location and availability of the model file but continue to experience the problem, please provide a little more context regarding any recent changes you may have made to your environment or code that could have influenced this behavior. We're here to help!

Remember, for rapidly changing issues or for more interactively engaging with the support, you can always refer to the Ultralytics docs and resources.

Keep up the great work with droplet detection—looking forward to hearing back from you with the outcome of these suggestions. 😊
