### ISSUE TITLE
Fixing the function detection code.

### ISSUE THREAD

**Issue by zainabalzaimoor** [ultralytics/ultralytics#6439]
Just I wanna check what is the reason behind this: 

results = model(source=0, show=True, conf=0.5, save=False, classes=[1, 3], stream=True)
def check_detection():
    # emergency_detected = False
    for result in results:
        boxes = result.boxes
        if boxes:
            emergency_detected = True
        else:
            emergency_detected = False
    return emergency_detected

emergency_detected = check_detection()
print("Final result:", emergency_detected)

It doesn't return for me a boolean value however it should, idk why!

I wanna create a function to check if there's detection and return either true or false then I wanna just call this function in another function and do other works.

How can I achieve this?
Plz help

**Comment by glenn-jocher** [comment]
@zainabalzaimoor hello! I understand that you're looking to write a function that checks for detections and returns a boolean value accordingly. From what you’ve shared, it seems like there's a desire to assess whether certain classes have been detected in a video stream and then report back with a `True` for detections or `False` otherwise.

Based on the snippet you've provided, and keeping the YOLOv8 architecture in mind, I recommend the following conceptual steps:

1. Ensure that the `model` is properly loaded with the correct configurations and weights.
2. Modify the detection loop to process frames continuously from the stream, as the `results` object should be an iterable in a streaming scenario.
3. Update the `check_detection` function to properly handle streaming data. If you are streaming video, then detections need to be checked per frame, not on a completed iterable of results.
4. Set `emergency_detected` to `False` by default and update it to `True` only when a relevant detection (`classes=[1, 3]` in your case) is found within a frame.

Remember that the `results.boxes` will be populated if any detections were found in the frame meeting the confidence (`conf=0.5`) and classes criteria.

Here's the high-level logic without providing explicit code:

- Load your YOLOv8 model with the correct configuration and class specifications.
- Start streaming frames using the `model()` call within a loop that processes each frame.
- For each frame processed by the model, check the detection `results`. If detections for the specified classes are found, update `emergency_detected` to `True`.
- The `check_detection` function can be called per frame to continuously monitor the stream.

Additionally, you might want to implement a break condition within the stream processing to stop when needed or if certain criteria are met.

With this approach, you should be able to functionally assess detection presence in a real-time stream and use this information as needed in your larger application. More details on these concepts can be found in the YOLOv8 documentation on the Ultralytics Docs.

Please let us know if you have further questions or need additional clarifications!

**Comment by RizwanMunawar** [comment]
@zainabalzaimoor you can utilize the provided example as a foundation and make necessary code modifications to align with your specific requirements.

```python
import cv2
from pathlib import Path
from ultralytics import YOLO
from ultralytics.utils.plotting import Annotator

def check_detection(results):
    emergency_detected = False
    for result in results:
        boxes = results[0].boxes.xyxy.cpu().numpy().astype(int)
        if boxes:
            emergency_detected = True
        else:
            emergency_detected = False
    return emergency_detected

    emergency_detected = check_detection()
    print("Final result:", emergency_detected)


model = YOLO('path/to/best.pt')  # fine-tuned model
video_path = "0"  # webcam

cap = cv2.VideoCapture(video_path)

while cap.isOpened():
    success, frame = cap.read()

    if success:
        results = model.predict(frame)
        check_detection(results)
    else:
        break

cap.release()
cv2.destroyAllWindows()
```

Hope this helps! Let me know if you have any additional questions.
Thanks
