### ISSUE TITLE
Exporting the operator silu to ONNX opset version 11 is not supported

### ISSUE THREAD

**Issue by q465414859** [ultralytics/ultralytics#644]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

PyTorch: starting from runs\detect\train\weights\best.pt with output shape (1, 84, 8400) (6.2 MB)

ONNX: starting export with onnx 1.13.0...
ONNX: export failure  0.3s: Exporting the operator silu to ONNX opset version 11 is not supported. Please open a bug to request ONNX export support for the missing operator.

### Minimal Reproducible Example

Ultralytics YOLOv8.0.20  Python-3.8.15 torch-1.7.1+cu110 CUDA:0 (GeForce GTX 1060 5GB, 5120MiB)

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@q465414859 you can define a custom opset version during export, i.e. `yolo export format=onnx opset=17`

**Comment by AyushExel** [comment]
We now have official YOLOv8 ONNX inference tutorials in both C++ and Python. 
https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-OpenCV-ONNX-Python

Marking this as resolved. Please reopen if you face any issues

**Comment by sdimantsd** [comment]
@glenn-jocher  I have the same problem.
If i set the opset=17 it's still happening

**Comment by sdimantsd** [comment]
Update the torch version fix it for me

**Comment by glenn-jocher** [comment]
@sdimantsd thank you for reporting this issue. It seems like exporting to ONNX format is failing because the `silu` operator is not supported in ONNX opset version 11.

One possible solution is to update your PyTorch version to a newer one, as `silu` is supported in ONNX opset versions 12 and newer.

Could you please try updating PyTorch and see if that resolves the issue for you?

**Comment by sdimantsd** [comment]
As I say, updating the torch solve it.
Thanks

**Comment by glenn-jocher** [comment]
@sdimantsd glad to hear that updating your PyTorch version resolved the issue! 
It's great to know that this was the solution for you.

Please note that `silu` operator is not supported in ONNX opset versions that are older than 12. Therefore, updating your PyTorch version to a newer one that supports ONNX opset version 12 or newer can help resolve this issue.

If you encounter any other issues or have any further questions, please don't hesitate to ask. We'll be happy to help!

**Comment by glenn-jocher** [comment]
@sdimantsd sure, here's a response you could use:

"Thank you for reporting this issue. It appears that the `silu` operator is not supported in ONNX opset version 11, which is causing the export to fail. An easy way to resolve this issue is by updating your PyTorch version to a newer one that supports ONNX opset version 12 or newer, as `silu` is supported in those versions. This should help you export the ONNX model without errors. If you have any further questions or encounter issues, please feel free to let us know and we'll do our best to help. Thank you!"

**Comment by ishoud** [comment]
@sarathkumarg92 Updating your OpenVINO to latest version (openvino-dev>=2023.0) will solve this issue
