### ISSUE TITLE
The asymmetric image size affects mAP and image size is set in each function module

### ISSUE THREAD

**Issue by DWendou** [ultralytics/ultralytics#6445]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

 I have an image size of 640x320(w,h), should I set (w,h) or (h,w) in train(),predict(),val(),export()? In addition, after the training, I found that the mAP value of training (640,320) was much lower than that of training (640,640). Why is this?

**Comment by glenn-jocher** [comment]
@DWendou hello!

Thank you for reaching out with your inquiry about handling asymmetric image sizes in YOLOv8. When setting the image size for functions such as `train()`, `predict()`, `val()`, and `export()`, you should typically input the width and height as `(w, h)`—so in your case, it would be `(640, 320)`.

Regarding the difference in mean Average Precision (mAP) between training with image sizes of `(640, 320)` and `(640, 640)`, it's likely associated with the aspect ratio of your training data and how the network handles resizing the images. If you're training with `(640, 320)`, images will be resized to this resolution, potentially distorting the aspect ratio of objects your model is trying to learn, which can affect the performance adversely. 

On the other hand, a square resolution like `(640, 640)` maintains the aspect ratio during resizing by using padding, which avoids distortion and could lead to better detection performance. It's always recommended to train the model with an image size that's close to the aspect ratio of the dataset images to minimize the precision loss caused by resizing.

For more specific information on how to effectively deal with different image sizes and aspect ratios, I suggest visiting the YOLOv8 Documentation on training and image handling. You can find detailed explanations and best practices which might help you optimize your training strategy for asymmetric images, possibly improving your model's mAP on your specific dataset.

I hope this explains why you're observing a difference in performance between the two image sizes! If you have further questions or issues, feel free to reach out, and the community will be here to help. Good luck with your YOLOv8 project!

**Comment by DWendou** [comment]
Thank you very much for your reply!
As for (w,h) or (h,w), I looked at the YOLOv8 documentation and it seems that imgsz is only mentioned in train() and export(), and it is (w,h) in train() and (h,w) in export().
As for the image training of asymmetric size, I will first adjust the image size according to your suggestion, I will retrain it on my own data set, look at the changes from the previous mAP, and I will look at the documentation of YOLOv8.
Thank you again for your patient response.

**Comment by DWendou** [comment]
@glenn-jocher Thank you very much for your reply!
As for (w,h) or (h,w), I looked at the YOLOv8 documentation and it seems that imgsz is only mentioned in train() and export(), and it is (w,h) in train() and (h,w) in export().
As for the image training of asymmetric size, I will first adjust the image size according to your suggestion, I will retrain it on my own data set, look at the changes from the previous mAP, and I will look at the documentation of YOLOv8.
Thank you again for your patient response.

**Comment by glenn-jocher** [comment]
@DWendou, you're welcome! I'm glad that my initial response was helpful to you.

When configuring the image size for `train()` and `export()`, keep in mind that consistency is key. If `train()` in the YOLOv8 documentation specifies image size as `(w, h)`, then use that format for training. For `export()`, use the format as mentioned in the documentation—`(h, w)` if that's what's stated. This ensures that the model operates as expected within the YOLOv8 framework.

You're on the right track by planning to adjust the image size to maintain the aspect ratio of your dataset. This can indeed lead to better performance since the model will be trained on images that preserve the original shapes and sizes of the objects.

Should you encounter any more challenges or notice any inconsistencies in the documentation, please don't hesitate to bring them up for clarification. It’s great to hear that you’re diving back into the training with adjusted image sizes.

I'm always here to support you and the YOLOv8 community. Your engagement with the project and careful consideration of the technical details are appreciated. Happy training, and I look forward to hearing about your improved mAP results!
