### ISSUE TITLE
YOLOv8-CLS Predict Function Throwing Error

### ISSUE THREAD

**Issue by devashish-bhake** [ultralytics/ultralytics#6458]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

So there is another similar bug report that got closed recently but the problem with that was that the OP didnt put as much info about the reproduciblity of the bug so here is the entire report on how to reporduce the bug on the local machine.
In my findings the bug doesn't seem to appear if we are using a pretrained model ex: 
```
model = YOLO('yolov8l-cls.pt')
results = model.predict("image.jpg")
```
the above code will not throw any error
but if we use a custom trained model like,
```
model = YOLO("somewhere/best.pt")
results = model.predict("image.jpg")
``` 
The following output will be generated
```
Traceback (most recent call last):
  File "/home/devashish/Desktop/work/Major_Project/Species_Detection/inference_yolo.py", line 7, in <module>
    results = model.predict("https://ultralytics.com/images/bus.jpg")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/devashish/anaconda3/lib/python3.11/site-packages/ultralytics/engine/model.py", line 239, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/devashish/anaconda3/lib/python3.11/site-packages/ultralytics/engine/predictor.py", line 198, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/devashish/anaconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/home/devashish/anaconda3/lib/python3.11/site-packages/ultralytics/engine/predictor.py", line 259, in stream_inference
    im = self.preprocess(im0s)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/devashish/anaconda3/lib/python3.11/site-packages/ultralytics/models/yolo/classify/predict.py", line 36, in preprocess
    img = torch.stack([self.transforms(im) for im in img], dim=0)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/devashish/anaconda3/lib/python3.11/site-packages/ultralytics/models/yolo/classify/predict.py", line 36, in <listcomp>
    img = torch.stack([self.transforms(im) for im in img], dim=0)
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/devashish/anaconda3/lib/python3.11/site-packages/torchvision/transforms/transforms.py", line 95, in __call__
    img = t(img)
          ^^^^^^
ValueError: too many values to unpack (expected 2)
```
To keep it consistent for testing I have used the same image and environment.
Details of the environment I have mentioned below.

PS: Keep in mind I had trained the model on a Kaggle Notebook's "Save & Commit Feature" for saving a new version. I know it shouldn't affect the model training or saving that much but I wanted to just let you know if you want to test it for yourself

### Environment

Ultralytics YOLOv8.0.213 🚀 Python-3.11.5 torch-2.1.1 CUDA:0 (NVIDIA GeForce GTX 1650 Ti, 3904MiB)
Setup complete ✅ (12 CPUs, 15.4 GB RAM, 358.5/915.3 GB disk)

OS                  Linux-6.2.0-36-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.11.5
Install             pip
RAM                 15.38 GB
CPU                 Intel Core(TM) i7-10750H 2.60GHz
CUDA                11.8

matplotlib          ✅ 3.7.2>=3.3.0
numpy               ✅ 1.24.3>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.0.1>=7.1.2
pyyaml              ✅ 6.0>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.1>=1.4.1
torch               ✅ 2.1.1>=1.8.0
torchvision         ✅ 0.16.1>=0.9.0
tqdm                ✅ 4.65.0>=4.64.0
pandas              ✅ 2.1.1>=1.1.4
seaborn             ✅ 0.12.2>=0.11.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 8.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

### Minimal Reproducible Example

```
from ultralytics import YOLO
import numpy as np

model = YOLO('yolov8l-cls.pt')
model = YOLO('trained_models/results/runs/classify/train/weights/best.pt')

results = model.predict("https://ultralytics.com/images/bus.jpg")
labels_dict = results[0].names
probs = results[0].probs.data.tolist()
print(labels_dict[np.argmax(probs)])

```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@devashish-bhake hello there, and thank you for the detailed report!

The error message you're encountering when trying to use the `.predict()` method with your custom-trained model seems to suggest an issue related to how the data is being processed prior to prediction. As the traceback indicates, there might be a mismatch in the expected dimensions or format of the input.

Given the information provided, it would help to check a few things:
1. Ensure that the custom-trained model was indeed saved correctly and is compatible with the YOLOv8 classification architecture.
2. Double-check that the environment where the model was trained (Kaggle Notebook) matches the environment where you are now attempting to predict. Inconsistencies between software versions in different environments can sometimes cause issues.
3. Confirm that the preprocessing steps in your custom script match those expected by the model for inference. For classification tasks, the model typically expects input in a particular format and size.
4. Verify whether the issue persists with different images or just the one you have been using for testing. It might be an isolated case related to the image format or resolution.

It's clear from your report that this is not an issue with pretrained models, which strongly hints at it being either a problem with the custom model or the specifics of the input data handling. Without leaving the provided guidelines, I can't go into code specifics, but I recommend double-checking the steps I've listed above.

If after going through these checks the issue still persists, please consider opening a new issue with the updated status, and rest assured we will take a deeper look into it. Your collaboration and effort to help us improve YOLOv8 are truly appreciated by the community.

Once again, thank you for your contribution, and we are eager to ensure that your experience with YOLOv8 is smooth and effective. 🌟

**Comment by glenn-jocher** [comment]
@devashish-bhake classification training and inference from trained checkpoints and final models works correctly. 

<img width="1790" alt="Screenshot 2023-11-20 at 20 26 52" src="https://github.com/ultralytics/ultralytics/assets/26833433/21a4315c-b88e-442e-9330-4166819e372c">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by devashish-bhake** [comment]
@glenn-jocher so I tested it on google colab and it works fine with the same model uploaded there. but still somehow it does not work on the local. Do you have any suggestions on what I can try out?
Many Thanks.!

**Comment by glenn-jocher** [comment]
Hello @devashish-bhake, I'm glad to hear that the model works on Google Colab. If it's functioning as expected there but not on your local setup, there may be environmental differences causing the issue. Here are some suggestions for troubleshooting the problem on your local machine:

1. **Environment Sync**: Attempt to replicate the Google Colab environment as closely as possible on your local machine, taking note of Python, PyTorch, CUDA, and other relevant package versions.

2. **Dependencies Check**: Ensure all the required dependencies are up to date on your local system by running `pip install -U ultralytics`. Colab often has the latest packages, and a mismatch can sometimes cause issues.

3. **Clean Environment**: Occasionally, conflicts with other installed packages can occur. You might want to create a new Python virtual environment and install only the essential packages needed to run YOLOv8.

4. **System Resources**: Check if system resources are not being overly strained on your local machine, as this can sometimes result in unexpected behavior or errors.

5. **Check Model Path**: Verify the path to your custom model. Ensure it's correct and that there are no permission issues that might prevent the model from being loaded properly.

6. **Test with Sample Data**: Try testing with the default images that come with the YOLOv8 repository or other known good images to ensure that the issue is not specific to a particular dataset or image.

7. **Error Logs**: Look closely at the error logs and traceback to identify where exactly the error is occurring. It may provide clues on the specific part of the code that's failing and why.

8. **Code Review**: Since the issue is not reproducible with the pretrained model, consider reviewing the configuration or the process you used when training your custom model, which might indicate a deviation leading to the error.

Finally, if the problem persists, you may want to consider seeking more personalized assistance by submitting a detailed bug report using the guidelines I provided earlier.

I hope these suggestions help you in getting your local setup to run the model correctly. 😊🛠️

**Comment by jdiaz97** [comment]
@devashish-bhake did you ever make the predict work? I haven't

**Comment by devashish-bhake** [comment]
> @devashish-bhake did you ever make the predict work? I haven't

i just created a seperated venv using anaconda just for running yolo and somehow it worked so i am guessing it was a conflict with the files or what idk. But the newer version seems to fix it.

**Comment by glenn-jocher** [comment]
@devashish-bhake hi there! I'm glad to hear that setting up a separate virtual environment resolved the issue for you. It sounds like there might have been some dependency conflicts or environment-specific problems affecting the predict function's behavior. Maintaining a clean, dedicated environment for specific projects can often help in resolving such conflicts. If the issue persists even in the new environment or if you encounter it again, please make sure to check for any updates, as newer versions might contain bug fixes. 😊👍
