### ISSUE TITLE
Fraction parameter and its usage

### ISSUE THREAD

**Issue by Sumered** [ultralytics/ultralytics#6464]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello Glenn!

First of all, thanks for amazing repository. I have a question about fraction parameter (amazing idea to include it in params), from what I see it is used in:

https://github.com/ultralytics/ultralytics/blob/d43fcecc8a2df47f79cf0c70d3e02ac5316cf41b/ultralytics/data/base.py#L121-L122

Before that in the function we can see that those files are globed and sorted. 

https://github.com/ultralytics/ultralytics/blob/d43fcecc8a2df47f79cf0c70d3e02ac5316cf41b/ultralytics/data/base.py#L105-L106
https://github.com/ultralytics/ultralytics/blob/d43fcecc8a2df47f79cf0c70d3e02ac5316cf41b/ultralytics/data/base.py#L116

So the fraction of dataset that we are taking to training (when fraction is 0.1) is first 10% of images in alphanumeric order. When images are named as guids its not a problem -> its actually random pick in this case. But wouldn't actually picking random image files be better than just taking first 10% of sorted images names?

If for example there is some kind of logic in naming images (source, type of image etc.) in their names, then fraction right now will take only images from one source, omitting the rest. This behavior can be corrected if we explicitly pick random images.

So the question is whether this is intended behavior or the idea was to pick random images. If it is intended behavior then I would like to kindly suggest putting this information in documentation of parameter in docs (as choosing fraction kind of implies that actually picked fraction is random in my own understanding).

Thanks!

**Comment by glenn-jocher** [comment]
@Sumered hello!

Thank you for your kind words and interest in the repository! You've raised an important point regarding the use of the `fraction` parameter in data loading.

Indeed, as you've observed, the `fraction` parameter currently selects a subset of the dataset based on the alphanumeric sorting of the file names. This approach ensures consistency in the data used across different runs if the `fraction` is intended to reduce dataset size for quicker iterations during development or experiments.

I appreciate your insight into the potential biases this method could introduce. If images are named in a way that correlates with the type of data (e.g., images from different sources or classes named sequentially), using the first 'fraction' could lead to an unrepresentative subset of the dataset.

Your suggestion to randomly select images when using the `fraction` parameter is valid and could potentially improve the generality of the selected dataset. However, introducing randomness would necessitate managing seeds for reproducibility or accepting nondeterministic behavior in the dataset creation process.

The current behavior is indeed by design, to ensure a reproducible subset of data is used when users opt to use the `fraction` parameter. That said, I totally understand that the current method might not align with the expectations someone might have when thinking about sampling a 'fraction' of the dataset.

I'll take your suggestion into consideration, and discuss with the team whether we should update our documentation to clearly articulate the behavior of the `fraction` parameter or consider modifying its functionality to introduce randomness while maintaining reproducibility.

Thanks once again for taking the time to provide your feedback—it's user insights like your own that help us improve. Happy developing! 🚀

For further details on the usage of the `fraction` parameter and data handling, you can visit our comprehensive documentation at https://docs.ultralytics.com. If you have more questions or suggestions, feel free to reach out!
