### ISSUE TITLE
Inference on custom RT-DETR model

### ISSUE THREAD

**Issue by eumentis-madhurzanwar** [ultralytics/ultralytics#6484]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm trying to run inference using custom rt-detr model. 
     
        from ultralytics.utils import ASSETS
        from ultralytics.models.rtdetr import RTDETRPredictor

        args = dict(model='rtdetr-l.pt', source=ASSETS)
        predictor = RTDETRPredictor(overrides=args)
        predictor.predict_cli()`
     
Can anyone tell me how get more information on the output results like getting bounding box and confidence scores info? And also if there is documentation related to this part. Thank you.

**Comment by glenn-jocher** [comment]
@eumentis-madhurzanwar hello,

It's fantastic that you're experimenting with the RT-DETR model for inference. To obtain more information from the output, such as bounding boxes and confidence scores, you simply need to access the attributes of the prediction objects returned by the `predictor.predict_cli()` method.

When you run inference, the predictions returned by the `predictor` object typically include both the bounding boxes and confidence scores for each detected object. The predictions are returned as a list of dictionaries, where each dictionary represents a detected object with keys such as `'x_min'`, `'y_min'`, `'x_max'`, `'y_max'` for bounding box coordinates, and `'confidence'` for the confidence score.

To work with these predictions, you would iterate over the list and extract the needed information from each dictionary. You can also visualize the results by rendering the predictions on the images, which would show the bounding boxes and confidence scores directly on the image.

For more specific instructions and additional functionalities of RT-DETR within our framework, please consult the Ultralytics Docs, especially the pages related to real-time detection transformers. There, you'll find more detailed information on object detection tasks and how to handle and interpret the output of the models.

Keep exploring and fine-tuning your models, and don’t hesitate to reach out if you have any more questions! 🚀

**Comment by eumentis-madhurzanwar** [comment]
Thank you for the response. The thing is that when I do  `results = predictor.predict_cli()` , I get **none**. But on CLI the output is printed - how many objects have been detected and the time taken to process.

**Comment by glenn-jocher** [comment]
@eumentis-madhurzanwar, apologies for the confusion. If `predictor.predict_cli()` is printing the output to the CLI and the `results` variable is `None`, it suggests that the method is designed to output the results directly to the console rather than returning them. This behavior is common in CLI designed functions, which often don't return the output but instead print it or save it to a file.

To work programmatically with the inference results, you're likely looking for a method that returns the predictions instead of just printing them. In this case, you should use a method that returns the detections as an object, which you can inspect and manipulate in your code.

Please refer to the RT-DETR section in the Ultralytics Docs which might provide you with the proper method or property to access the prediction results. The documentation will guide you on how to call the predictor in a way that the inference results are returned, and you can subsequently process these results to extract bounding boxes and confidence scores.

If you are unable to find the information in the documentation, I encourage you to join discussions on our GitHub page or check the issues section for topics similar to yours. The community and our team are there to help you with these types of inquiries.

Remember, feedback from users like you is invaluable in improving our documentation and the user experience with our models. Good luck with your project, and we look forward to assisting you further if you need it! 🌟
