### ISSUE TITLE
My PC Crashed when training Yolov8

### ISSUE THREAD

**Issue by ammarasnawi** [ultralytics/ultralytics#6495]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I would like to ask, I'm training Yolov8 using my PC, with GTX 1060 6GB (pretty old GPU).

But when training is about to start, my PC crashed. Does it means that GTX 1060 can't handle to train YOLOv8?

I already set batch size = 2.

**Comment by PiyushKamboj1503** [comment]
@ammarasnawi I would suggest you to monitor the system graphs before concluded any reasons. Your RAM can also be a reason. If you find that you RAM is filling faster, try to reduce the workers. If it is not hardware related, then it would be something related to the environment and drivers.

**Comment by glenn-jocher** [comment]
@PiyushKamboj1503 It's possible that the crash is due to insufficient resources or a configuration issue. Monitoring system usage (GPU, CPU, RAM) during the training process can provide insights. If RAM usage is high, consider reducing the number of workers. Also, ensure that your GPU drivers and environment are up to date and properly configured. If the issue persists, please provide more details on the crash for further assistance. 🛠️
