### ISSUE TITLE
FastSAM text prompt returns all segmentation masks instead of the mask with the highest score

### ISSUE THREAD

**Issue by sulthansf** [ultralytics/ultralytics#6509]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

The `text_prompt` method in `FastSAMPrompt` class is returning all segmentation masks instead of only the mask with the highest score. This behavior is inconsistent with the expected functionality mentioned in [Ultralytics FastSAM docs](https://docs.ultralytics.com/models/fast-sam/) and [FastSAM repo](https://github.com/CASIA-IVA-Lab/FastSAM).

![dogs](https://github.com/ultralytics/ultralytics/assets/52656038/5d6ea0fa-0f01-4500-ba5d-70eefda0de14)
**Example Image**

![dogs_with_fix](https://github.com/ultralytics/ultralytics/assets/52656038/06c0541d-2ec9-4912-8bae-38f16a6d7aa9)
**Expected Output with text prompt "The black dog"**

![dogs_without_fix](https://github.com/ultralytics/ultralytics/assets/52656038/f4e83db0-960c-4a39-927a-6a5d1990534c)
**Current Output with text prompt "The black dog"**

### Environment

```
Ultralytics YOLOv8.0.215 🚀 Python-3.8.10 torch-2.1.1+cu121 CPU (13th Gen Intel Core(TM) i7-1370P)
Setup complete ✅ (20 CPUs, 30.7 GB RAM, 27.6/233.6 GB disk)

OS                  Linux-5.19.17-051917-generic-x86_64-with-glibc2.29
Environment         Linux
Python              3.8.10
Install             git
RAM                 30.73 GB
CPU                 13th Gen Intel Core(TM) i7-1370P
CUDA                None

matplotlib          ✅ 3.7.4>=3.3.0
numpy               ✅ 1.24.4>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pandas              ✅ 2.0.3>=1.1.4
pillow              ✅ 10.1.0>=7.1.2
psutil              ✅ 5.9.6
py-cpuinfo          ✅ 9.0.0
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
seaborn             ✅ 0.13.0>=0.11.0
thop                ✅ 0.1.1-2209072238>=0.1.1
torch               ✅ 2.1.1>=1.8.0
torchvision         ✅ 0.16.1>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
```

### Minimal Reproducible Example

```
from ultralytics import FastSAM
from ultralytics.models.fastsam import FastSAMPrompt

# Define an inference source
source = 'https://raw.githubusercontent.com/CASIA-IVA-Lab/FastSAM/main/images/dogs.jpg'

# Create a FastSAM model
model = FastSAM('FastSAM-x.pt')

# Run inference on the image
everything_results = model(source, device='cpu', retina_masks=True, imgsz=1024, conf=0.4, iou=0.9)

# Prepare a Prompt Process object
prompt_process = FastSAMPrompt(source, everything_results, device='cpu')

# Text prompt
ann = prompt_process.text_prompt(text='The black dog')

# Plot and save results
prompt_process.plot(annotations=ann, output='./output')
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by sulthansf** [comment]
I have opened a PR (#6510) which fixes this issue.

**Comment by glenn-jocher** [comment]
@sulthansf hello! Firstly, thank you for taking the time to report this issue and for your willingness to contribute a fix. 🌟 The collaboration of users like you is invaluable to the YOLO community and helps us maintain the high quality of Ultralytics' models.

Based on your report, it seems you've identified an inconsistency in how the `FastSAMPrompt` class's `text_prompt` method is intended to function versus its current behavior. Indeed, the method should return the segmentation mask with the highest score when specific text prompts are used, rather than all the segmentation masks.

Your initiative to open a pull request to address this problem is greatly appreciated. The next steps would typically involve the review of your PR by the Ultralytics team. We'll carefully examine the changes, ensure they align with the project's goals and code standards, and verify that the solution effectively resolves the issue while not introducing any regressions.

If you haven't already done so, please make sure that the changes are accompanied by appropriate documentation updates, and if possible, include tests that illustrate the correct behavior. This contributes to the robustness and maintainability of the codebase.

Keep an eye on your PR, as the team might ask for additional changes or clarifications before merging it. Once again, thank you for your contribution, and we look forward to collaborating with you! 🚀

For further contributions or to discuss the specifics of the YOLOv8 codebase, you're welcome to explore [our docs](https://docs.ultralytics.com) or check the more specialized pages for tasks like segmentation using FastSAM. If you have any other questions or issues, feel free to raise them in the GitHub repository, and our team will be happy to assist.
