### ISSUE TITLE
About  batch size of training 

### ISSUE THREAD

**Issue by Zhenkun-Lei** [ultralytics/ultralytics#6512]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I train the model using CPU only. 
Mentioned in ultralytics-main\ultralytics\cfg\default.yaml: 
      batch: # (int) number of images per batch (-1 for AutoBatch)
But when I set: batch: -1 # (int) number of images per batch (-1 for AutoBatch), I get the following error message during training:
     batch should be a non-negative integer

So I think this hint is a bit confusing. It would be better to give direct suggestions, such as 1, 16, 32, etc.

### Environment

Ultralytics YOLOv8.0.215 🚀 Python-3.8.6 torch-2.0.1+cpu CPU (AMD Ryzen 5 4500U with Radeon Graphics)
Setup complete ✅ (6 CPUs, 15.2 GB RAM, 350.3/476.0 GB disk)

OS                  Windows-10-10.0.19041-SP0
Environment         Windows
Python              3.8.6
Install             pip
RAM                 15.23 GB
CPU                 AMD Ryzen 5 4500U with Radeon Graphics
CUDA                None

matplotlib          ✅ 3.6.0>=3.3.0
numpy               ✅ 1.23.1>=1.22.2
opencv-python       ✅ 4.7.0.72>=4.6.0
pillow              ✅ 9.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.28.1>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.0.1>=1.8.0
torchvision         ✅ 0.15.2>=0.9.0
tqdm                ✅ 4.65.0>=4.64.0
pandas              ✅ 1.5.3>=1.1.4
seaborn             ✅ 0.12.2>=0.11.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Zhenkun-Lei hello! Thank you for reaching out and bringing this to our attention. It seems there's a misconception about the `batch: -1` configuration. My apologies for the confusion caused by indicating that setting the batch size to `-1` enables "AutoBatch" – AutoBatch is not actually supported in YOLOv8. The documentation will be updated to avoid such misunderstandings in the future.

For training YOLOv8 on a CPU, you'll indeed need to manually specify a non-negative integer for the batch size that's suitable for your system's resources. Since you're using a CPU rather than a GPU, you might need to keep the batch size relatively small to prevent memory overflow issues—values like 1, 2, or 4 may be appropriate depending on your system's RAM availability. 

Experiment with different batch sizes to find the best fit for your setup, and keep an eye on the system's resource usage to ensure stability during training.

If you have further questions or need more assistance, feel free to reach out. Our team is always here to help. Happy training with YOLOv8! 🚀
