### ISSUE TITLE
YOLOv8 Export to TensorFlow Object Detection Fails

### ISSUE THREAD

**Issue by etatbak** [ultralytics/ultralytics#6517]
I trained a yolov8 model and want to convert the model export files to TensorFlow object detection format.
I am having this error:

```
Ultralytics YOLOv8.0.134  Python-3.9.17 torch-2.1.0 CPU
Model summary (fused): 268 layers, 68124531 parameters, 0 gradients, 257.4 GFLOPs

PyTorch: starting from model_path\model_name\weights\best.pt with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 5, 8400) (130.4 MB)
requirements: Ultralytics requirements ('onnx', 'onnx2tf>=1.7.7', 'sng4onnx>=1.0.1', 'onnxsim>=0.4.17', 'onnx_graphsurgeon>=0.3.26', 'tflite_support', 'onnxruntime') not found, attempting AutoUpdate...
requirements:  AutoUpdate skipped (offline)

TensorFlow SavedModel: starting export with tensorflow 2.9.1...

ONNX: starting export with onnx 1.15.0 opset 17...
ONNX: simplifying with onnxsim 0.4.35...
ONNX: export success  32.2s, saved as model_path\model_name\weights\best.onnx (260.1 MB)

TensorFlow SavedModel: running 'onnx2tf -i model_path\model_name\weights\best.onnx -o model_path\model_name\weights\best_saved_model -nuo --non_verbose'
Traceback (most recent call last):
  File "C:\Users\my_pc\Anaconda3\envs\yolo_v8\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\my_pc\Anaconda3\envs\yolo_v8\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\my_pc\Anaconda3\envs\yolo_v8\Scripts\onnx2tf.exe\__main__.py", line 4, in <module>
  File "C:\Users\my_pc\Anaconda3\envs\yolo_v8\lib\site-packages\onnx2tf\__init__.py", line 1, in <module>
    from onnx2tf.onnx2tf import convert, main
  File "C:\Users\my_pc\Anaconda3\envs\yolo_v8\lib\site-packages\onnx2tf\onnx2tf.py", line 36, in <module>
    import onnx_graphsurgeon as gs
ModuleNotFoundError: No module named 'onnx_graphsurgeon'
TensorFlow SavedModel: export failure  44.2s: SavedModel file does not exist at: model_path\model_name\weights\best_saved_model\{saved_model.pbtxt|saved_model.pb}
```
I have a **Windows** machine.
I tried to install onnx_graphsurgeon but it not possible to install it, tried several ways.

**Comment by glenn-jocher** [comment]
@etatbak it looks like you are encountering an issue with the `onnx_graphsurgeon` module not being found when trying to export your trained Ultralytics YOLOv8 model to TensorFlow object detection format. This module is necessary for transforming the ONNX model graph and is included in the conversion process.

The `ModuleNotFoundError` indicates that the `onnx_graphsurgeon` is either not installed or not properly recognized in your Python environment. The onnx_graphsurgeon module is usually part of the TensorRT installation, which might not be straightforward to install on a Windows machine outside of specific NVIDIA software.

Here's a step-by-step recommendation to resolve the issue:

1. Make sure that your environment meets all the prerequisites for using onnx_graphsurgeon. This typically includes having an NVIDIA GPU, CUDA, and TensorRT installed. Since you mentioned you tried several ways to install it, please verify the compatibility of onnx_graphsurgeon with your system.

2. If you're unable to install onnx_graphsurgeon on your Windows machine, consider using a Docker container or a Linux-based system where installing TensorRT and its components might be more streamlined.

3. Verify that all required libraries are installed and up to date. Sometimes, Python environments can have conflicting dependencies. Consider creating a new Python environment specifically for this task to minimize conflicts.

4. If installing onnx_graphsurgeon is not possible or fails, consider using a different approach to convert your ONNX model to TensorFlow. For instance, you can use the TensorFlow-ONNX library (`tf2onnx`), which can convert an ONNX model to a TensorFlow model without the need for onnx_graphsurgeon.

5. As a last resort, if no conversion method is working for you, you might reach out to the community for more targeted support or consider hiring commercial support if your work requires specific deliverables on a tight schedule.

Remember that model conversion can sometimes lead to specific challenges depending on the versions and compatibility of the tools in use. Make sure your environment aligns with the version requirements of all involved libraries for a smooth conversion process.

For further details on how to leverage different modes and task-specific functionalities in YOLOv8, you can refer to our documentation at the respective specialized docs pages.

Keep up the great work and don't hesitate to reach out again if you face more issues or have other questions regarding YOLOv8!
