### ISSUE TITLE
User interaction during the YOLOv8 installation

### ISSUE THREAD

**Issue by izidorg** [ultralytics/ultralytics#6521]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

The task: YOLOv8 installation on the NVIDIA® Jetson™, the premier platform for autonomous machines and embedded applications. NVIDIA® owns their edge-AI solutions, including efficient Pytorch features uniquely and efficiently compiled for the Jetson™-based edge computers. Preserving the torch and torchvision binaries is highly recommended if they are pre-installed on the system.

### Use case

The perfect use case in this regard is the addition of user interaction during the automated installation (pip install ultralytics) and semi-manual installation (pip install -r requirements.txt). Use case-1:  prompt to the user prior or during the installation to approve overriding or skip installation of the torch and torchvision binaries. Or Use case-2: adding a flag to the CLI for example: pip install ultralytics -- override torch -- override torchvision.

### Additional

As a SW developer and owner of a solution under development, I am utilizing YOLO as the leading platform for training, testing, and deployment of image segmentation tasks on custom dataset for deployment on the NVIDIA® Jetson™ edge computer.
Some additional discussions were made before submitting the feature request.
[#6488](https://github.com/ultralytics/ultralytics/issues/6488)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@izidorg hello! Thank you for bringing up this feature request and the thorough explanation of your use case. I understand that you're looking into options for the YOLOv8 installation process on NVIDIA® Jetson™ systems, specifically regarding the handling of existing torch and torchvision binaries.

I appreciate the initiative to search for similar issues and considering the preservation of pre-installed binaries during installation. Your suggestion for user interaction during the `pip install ultralytics` process or having CLI flags to manage installation behavior is certainly an interesting one.

Allowing for such interactive installations or flags can be quite useful in ensuring that users maintain their optimal setup, especially on platforms like the Jetson where custom compiled binaries are common due to the specific hardware acceleration.

While this is a valuable suggestion, implementing such features requires careful consideration of the installation process and compatibility with various environments and use cases. For now, the best approach would be for users to manually manage their PyTorch and torchvision installations on such specialized hardware.

That said, I'm bringing this to the attention of the Ultralytics team for further discussion. We always appreciate contributions from the community, and even though you've indicated you're not ready to submit a PR, do know that input from our users is vital for improving the usability and functionality of our software.

Your feedback is now logged, and although we can't promise immediate implementation, it will be reviewed and considered as we continue to improve the installation process for YOLOv8. We aim to support a broad range of platforms, and considerations for systems like the Jetson are certainly on our radar.

Thank you very much for your contribution to the community and for supporting YOLOv8! If you have any more questions or suggestions, please feel free to reach out again.

**Comment by izidorg** [comment]
Regarding the current consideration of the yolov8 automatic and manual SW installation processes, the user guide or statement shall emphasize the importance of overriding the torch and torchvision binaries post-installation of yolov8 with the respective proprietary binaries for the efficiency of runtime in the embedded computers.
