### ISSUE TITLE
Adjust segmentation label format to support multiple polygons for one instance

### ISSUE THREAD

**Issue by menggui1993** [ultralytics/ultralytics#6530]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

The YOLO label format for instance segmentation is like
`<class-index> <x1> <y1> <x2> <y2> ... <xn> <yn>`

However, it is common to have occlusion in real life data. So one instance could have multiple seperated mask regions like in the following picture. The current format can only represent a single polygon for each instance. It would be helpful to support multiple polygons for each instance. The new format can be like
`<class-index> <x11> <y11> <x12> <y12> ... <x1n> <y1n> | <x21> <y21> ... <x2n> <y2n> ...`

![Screenshot from 2023-11-23 13-55-36](https://github.com/ultralytics/ultralytics/assets/13851918/5cd5bbcd-5c46-432b-a596-0ba09f674f2a)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@menggui1993 hello, thank you for bringing up this feature request regarding the handling of multiple polygons for single-instance segmentation in YOLOv8. You've highlighted an important aspect of instance segmentation in real-world scenarios, where occlusions indeed occur frequently, necessitating the capability to represent one instance with multiple separated mask regions.

Currently, as you correctly pointed out, the YOLOv8 label format for segmentation supports single continuous polygons for each instance. The ability to process and utilize multiple disconnected polygons per instance can significantly improve the accuracy in certain cases.

This is a non-trivial enhancement as it requires changes to how labels are parsed, managed, and utilized within the training and inference pipelines of YOLOv8. Therefore, the proposal would need to be carefully considered by the development team for its feasibility, implications on the codebase, and general user requirements.

Your suggested format using a separator is one way to approach this problem, though any changes must maintain backward compatibility and user-friendliness. We appreciate your input and understand the potential value this feature could add to the YOLOv8 ecosystem.

While I can't make any commitments, we'll keep this in mind for future updates. Contributions and suggestions are always welcome, as they help improve the model for everyone. You can check our documentation in the ["Segmentation" section](https://docs.ultralytics.com/tasks/segment) for updates or details on current capabilities. If more users request this feature or you are interested in contributing, we're open to further discussions on this topic.

Thank you once again for your interest in contributing to the Ultralytics YOLOv8 project. Your engagement is invaluable for the continuous improvement of the model.

**Comment by TimotheeWrightFicha** [comment]
@Y-T-G @Laughing-q I dug deep to find a solution for occlusion. Currently what seems to be the current solution, connecting multi-segments (#16826, [convert_segment_masks_to_yolo_seg](https://docs.ultralytics.com/reference/data/converter#ultralytics.data.converter.convert_segment_masks_to_yolo_seg) ), may have some serious risks (cf [Laughing-q's comment](https://github.com/ultralytics/ultralytics/pull/16826#issuecomment-2406835442)) during training compared to training with multiple segment assigned 

<img width="1240" height="699" alt="Image" src="https://github.com/user-attachments/assets/cbfd1288-fc44-4410-be61-a6d7b7a8f47b" />

<img width="1291" height="647" alt="Image" src="https://github.com/user-attachments/assets/b5a074e4-ae69-4ecc-86d8-fb3919c1d4f4" />

I wanted to know if multi-segment training had been in discussion on ultralytics side since the above comment of @glenn-jocher (for example as part of the [JSON2YOLO](https://github.com/ultralytics/JSON2YOLO) work) ? 
And if yes, what are the reasons it wasn't prioritized yet ? Did you find out that those would not affect the training ?

It would help the community to understand a bit more how to handle instance segmentation with occlusion using ultralytics's Yolo

**Comment by Y-T-G** [comment]
@TimotheeWrightFicha We don't have any support for multi segment polygon yet. Are you open to using PNG masks instead? It's more doable with PNG mask than polygons.

**Comment by TimotheeWrightFicha** [comment]
Thank you for the incredibly fast turnaround on this, I didn't expect aworking branch the same week, let alone one this thoroughly documented.
The write-up in #25944 answered questions I hadn't even thought to ask.

I was even surprised with the 95.3% of multi-part instances at IoU ≥ 0.99 versus 64.3% for merge_multi_segment, and the 0.0236 worst case on the old path, is a much bigger gap than I would have guessed. I'd assumed the bridging artifacts were a cosmetic few-pixel issue; clearly they aren't for instances with many parts.

Just a question :
#25949 looks like it was closed and the branch deleted, and polygon2mask on main still does np.asarray(..., dtype=np.int32).
Since the multi-polygon fidelity numbers in this PR (0.9976 → 1.0000) depend on the rounding, is that expected to land separately, or is the plan to fold it into this branch?

Is there anything that would help move this along ? I can test on my real-world dataset (~5k image) on both branches, if that helps.

**Comment by Y-T-G** [comment]
@TimotheeWrightFicha In our internal tests, we found the fix causes lower mAP somehow, so it wasn't merged.
