### ISSUE TITLE
AttributeError: bn when I change from model.predict to model.track in Multithreaded Tracking

### ISSUE THREAD

**Issue by epigraphe** [ultralytics/ultralytics#6536]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

I used this [guide as an example](https://docs.ultralytics.com/modes/track/#multithreaded-tracking)

Everything works if I select model.predict, but crashes with an error when selecting model.track

```
Exception in thread Thread-1 (run_tracker_in_thread):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/Threads/standalone_new.py", line 28, in run_tracker_in_thread
    results = model.track(frame, persist=True)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 259, in track
    return self.predict(source=source, stream=stream, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 232, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/predictor.py", line 315, in setup_model
    self.model = AutoBackend(model or self.args.model,
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/autobackend.py", line 115, in __init__
    model = model.fuse(verbose=verbose) if fuse else model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py", line 130, in fuse
    delattr(m, 'bn')  # remove batchnorm
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1765, in __delattr__
    super().__delattr__(name)
AttributeError: bn
```

I read similar discussions here, the solution was to run the model in each thread. But that's exactly what I do.
Tell me, please, how can I fix this?

```
import cv2
import numpy as np
from ultralytics import YOLO
import threading

# Function to run the tracker in a thread
def run_tracker_in_thread(rtsp_url, model, file_index, detection_zones):
    video = cv2.VideoCapture(rtsp_url)

    # Get video properties
    width = int(video.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(video.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = int(video.get(cv2.CAP_PROP_FPS))

    # Define the codec and create VideoWriter object
    fourcc = cv2.VideoWriter_fourcc(*'XVID')
    output_file = f"output_{file_index}.avi"
    out = cv2.VideoWriter(output_file, fourcc, fps, (width, height))

    while True:
        ret, frame = video.read()
        if not ret:
            break
        results = model.track(frame, classes=0, conf=0.6, tracker="bytetrack.yaml")
        tracked_frame, count_objects = draw_zones_and_count(frame.copy(), results, detection_zones)
        out.write(tracked_frame)
        key = cv2.waitKey(1)
        if key == ord('q'):
            break
    video.release()
    out.release()

# Function to draw zones and count objects within those zones
def draw_zones_and_count(image, results, detection_zones):
    count_objects = [0] * len(detection_zones)
    for i, zone in enumerate(detection_zones):
        for result in results[0].boxes.data.to("cpu"):
            x1, y1, x2, y2, conf, class_id = map(int, result[:6])
            class_name = yolo_model.names[class_id]

            if cv2.pointPolygonTest(zone, ((x1 + x2) // 2, (y1 + y2) // 2), False) >= 0:
                count_objects[i] += 1
                cv2.rectangle(image, (x1, y1), (x2, y2), (0, 255, 0), 2)

        # Draw zones
        cv2.polylines(image, [zone], True, (0, 255, 0), thickness=4)

        # Text on frame
        cv2.putText(image, f'Objects in Zone {i + 1}: {count_objects[i]}', (10, 50 + i * 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 4)

    return image, count_objects

# Define the RTSP URLs for the trackers
rtsp_urls = ['rtsp://', 'rtsp://']

# Load the YOLOv8 model
yolo_model = YOLO('yolov8n.pt')

# Define zones for each thread
detection_zones_thread1 = [np.array([[446, 1076],[1654, 581], [1203, 495], [0, 560], [166, 1061]], np.int32)]
detection_zones_thread2 = [np.array([[482, 10],[466, 694],[1602, 694],[1606, 30]], np.int32),]
# Create and start tracker threads
tracker_threads = [
    threading.Thread(target=run_tracker_in_thread, args=(url, yolo_model, index, zones), daemon=True)
    for index, (url, zones) in enumerate(zip(rtsp_urls, [detection_zones_thread1, detection_zones_thread2]))
]
for thread in tracker_threads:
    thread.start()
# Wait for the tracker threads to finish
for thread in tracker_threads:
    thread.join()
cv2.destroyAllWindows()

```

### Environment

Ultralytics YOLOv8.0.216 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (NVIDIA GeForce RTX 4070, 12001MiB)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@epigraphe thank you for reaching out with the detailed report of the issue you've encountered while using the multithreaded tracking with YOLOv8. The error seems to suggest there is an issue with the batch normalization layers during the setup of the model for tracking.

This kind of error might occur if the model's state is altered in a way that's incompatible with the `track` method's expectations. Internally, the tracking process might attempt to manipulate batch normalization layers which, if absent or already modified, can lead to an `AttributeError`.

To address this problem, make sure that you follow these steps:
1. Instantiate a separate model object within each thread to ensure they do not share state which could lead to conflicts. This means calling `YOLO('yolov8n.pt')` inside the `run_tracker_in_thread` function for each thread, instead of passing a shared model.
2. Ensure that the model you are loading does indeed contain batch normalization layers (`bn`). If you are using custom weights, there might be a mismatch in the model architecture.
3. If you have modified the model architecture or the configuration file (like `"bytetrack.yaml"`), double-check to ensure that the batch normalization layers are defined as expected.

Keep in mind that for shared resources like GPUs, initializing multiple models could lead to higher memory usage. So it’s important to make sure that your system can handle the load.

Unfortunately, without a deeper dive into the exact state of your code and setup when the error occurs, I cannot provide a targeted fix. If the above suggestions do not resolve the issue, consider isolating the failure to a minimal example that can be run in a single thread, and ensure that the model can still be properly initialized and called for tracking in such an isolated environment before scaling back up to multithreading. 

For further insights into multithreaded tracking best practices, the Ultralytics Docs provide guidance on how to structure your code for optimal performance. If the problem persists, please provide additional detail about any customizations or modifications you've made, and the team will be happy to assist further.

**Comment by epigraphe** [comment]
> Instantiate a separate model object within each thread to ensure they do not share state which could lead to conflicts. This means calling YOLO('yolov8n.pt') inside the run_tracker_in_thread function for each thread, instead of passing a shared model.

I checked again and moved yolo_model = YOLO('yolov8n.pt') inside the function. Previously, I called the model when initializing the thread.

Indeed, this was my stupid mistake and after these changes the tracking worked as expected.

Thank you very much for your constant help and advice - you have already helped me resolve issues more than once. Thank you very much again.

**Comment by glenn-jocher** [comment]
@epigraphe you're very welcome! I'm glad to hear that the tracking is now working as expected. It's not uncommon for threading issues to cause tricky bugs, so don't be too hard on yourself. Great job in resolving it!

Remember, developing and troubleshooting complex systems is a group effort, and every question you bring helps improve both the documentation and the community knowledge base. Don't hesitate to reach out anytime you encounter difficulties or have questions in the future. The Ultralytics team and the broader community are here to help.

Best of luck with your continued work using YOLOv8, and I'm looking forward to assisting you with any future questions you might have. Keep up the excellent work! 😊👍
