### ISSUE TITLE
Yolov8 REGION COUNTER Error

### ISSUE THREAD

**Issue by yeongnamtan** [ultralytics/ultralytics#6564]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I run below code,  I  get error below...

!python yolov8_region_counter.py --source subway.mp4 --save-img --view-img --weights yolov8n.pt

ERROR:
0: 640x384 6 persons, 88.9ms
Speed: 4.3ms preprocess, 88.9ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)
Traceback (most recent call last):
  File "yolov8_region_counter.py", line 223, in <module>
    main(opt)
  File "yolov8_region_counter.py", line 218, in main
    run(**vars(opt))
  File "yolov8_region_counter.py", line 125, in run
    if results and results[0] and results[0].boxes and results[0].boxes.id:
RuntimeError: Boolean value of Tensor with more than one value is ambiguous

### Additional

![Screenshot 2023-11-24 163557](https://github.com/ultralytics/ultralytics/assets/105199717/28d557be-f7df-4fd7-9454-3e4330548370)

**Comment by RizwanMunawar** [comment]
@yeongnamtan Appreciate you sharing this information.

I recommend updating your code because the line `if results and results[0] and results[0].boxes and results[0].boxes.id:` is not part of the main code. 

For more information, check the code https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-Region-Counter

Thanks
