### ISSUE TITLE
I do not know where to mount when using docker.

### ISSUE THREAD

**Issue by kazu-gra** [ultralytics/ultralytics#6569]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am doing the implementation inside a Docker container.
I am not sure which code I should modify, the ultralitics code created by git clone or the code automatically created in the container (/usr/src/ultralitics, dataset). The commands used to create a container are as follows.

The directory created in /usr/src will disappear when the container is closed, so I feel that it is meaningless to edit the code there if it disappears. I would like to implement using multiple devices and multiple containers, so I would like to duplicate the modified code and implement it. I'm also having trouble because the trained model is also created in /src.

By the way, here are the containers I have created
`docker run -it --ipc=host --gpus '"device=2,3"' -v /mnt/data/ultralytics:/workspace -name yolov8 "image id"`
Thank you in advance.

**Comment by glenn-jocher** [comment]
@kazu-gra when using Docker, it's important to understand that any changes you make inside the container are temporary and will be lost once the container is shut down unless you've mounted a volume from your host machine to persist the data.

In your case, as you've run the Docker container with `-v /mnt/data/ultralytics:/workspace`, you have a volume mounted from `/mnt/data/ultralytics` on your host machine to `/workspace` in your container. This means any data you want to persist should be placed in `/workspace` inside the container, which corresponds to `/mnt/data/ultralytics` on your host.

You shouldn't modify the code in `/usr/src/ultralytics` directly unless you're okay with it disappearing after shutting down the container. Instead, you should clone or copy the necessary code into the `/workspace` directory. This way, your code changes and trained models will remain intact on your host machine even when the container exits.

When you need to scale to multiple devices and containers, you can clone the modified repo or pull the Docker image with your modifications on each host and ensure that you mount the required directories to the containers. The code and data in mounted volumes are shared across container restarts and can be accessed from multiple containers as long as they are pointed to the right directories on the host.

Remember, after making changes to the code on your host, you may need to rebuild your Docker image if you are packaging your application within the image itself. Otherwise, for simpler edits, sharing the updated code with the containers via mounted volumes will suffice, and there's no need for a rebuild.

Keeping organized directory structures and naming conventions for mounting will help you manage multiple containers and deployments, ensuring your work is harmonious and not redundant. Happy coding! 🚀

**Comment by Burhan-Q** [comment]
To bind a host directory to the container, you can add a Docker Volume to the Dockerfile or use the `-v` switch and bind a container directory to a host directory like Glenn mentioned above. Either way, I'd recommend reading about Docker Volumes to get a better sense of how they operate and how to configure them.

**Comment by Burhan-Q** [comment]
If you're planning to make custom changes to the Ultralytics source code and use that in a Docker container, there are multiple ways to do this. It might be easiest to create a copy of the Ultralytics Docker image and then modify it to copy _your custom code repo_ into the container when built.
