### ISSUE TITLE
Compiling exported rtdetr model with TensorRT gives error message "Expected all tensors to be on the same device..."

### ISSUE THREAD

**Issue by bveldhoen** [ultralytics/ultralytics#6572]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Thanks in advance for any help related to this issue.

After exporting the rtdetr-l.pt model to torchscript, and compiling with TensorRT 8.6.1, the following error message is produced:

```
The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/ultralytics/nn/tasks.py", line 85, in forward
    _33 = (_7).forward(act1, (_6).forward(act1, _32, ), )
    _34 = (_10).forward((_9).forward((_8).forward(_33, ), ), )
    _35 = (_12).forward(act0, (_11).forward(_34, ), )
                               ~~~~~~~~~~~~ <--- HERE
    _36 = (_15).forward((_13).forward(_35, ), (_14).forward(_33, ), )
    _37 = (_17).forward(act0, (_16).forward(act0, act, _36, ), )
  File "code/__torch__/ultralytics/nn/modules/transformer.py", line 38, in forward
    pos_dim = torch.floor_divide(embed_dim, CONSTANTS.c0)
    _6 = torch.arange(annotate(number, pos_dim), dtype=6, layout=None, device=torch.device("cpu"), pin_memory=False)
    _7 = torch.div(_6, pos_dim)
         ~~~~~~~~~ <--- HERE
    _8 = torch.to(CONSTANTS.c1, torch.device("cpu"), 6)
    _9 = torch.reciprocal(torch.pow(torch.detach(_8), _7))

Traceback of TorchScript, original code (most recent call last):
/usr/local/lib/python3.10/dist-packages/ultralytics/nn/modules/transformer.py(92): build_2d_sincos_position_embedding
/usr/local/lib/python3.10/dist-packages/ultralytics/nn/modules/transformer.py(79): forward
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py(1488): _slow_forward
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py(1501): _call_impl
/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py(82): _predict_once
/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py(62): predict
/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py(45): forward
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py(1488): _slow_forward
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py(1501): _call_impl
/usr/local/lib/python3.10/dist-packages/torch/jit/_trace.py(1056): trace_module
/usr/local/lib/python3.10/dist-packages/torch/jit/_trace.py(794): trace
/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py(298): export_torchscript
/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py(117): outer_func
/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py(248): __call__
/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py(115): decorate_context
/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py(309): export
trace_rtdetr.py(11): <module>
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

The model seems to allocate parts of the layers on cpu, which is not expected by the TensorRT compiler.
Is this a bug, or is there a way around this error message?

### Additional

The code used to export the model:
```
model = RTDETR("rtdetr-l.pt")
model.eval()
model.to(device)
model.export(format="torchscript")
```

**Comment by glenn-jocher** [comment]
@bveldhoen hello! It seems that during the export process, there's an issue that's leading to an inconsistency in device placement, where some operations are trying to be performed on the CPU while the model expects them to be on the CUDA device.

This can happen if device-specific tensors and operations are not correctly handled during the scripting phase. It's important to ensure that all tensors and operations are explicitly assigned to the same device before exporting the model to TorchScript. This is typically taken care of within the model's code, so the issue might originate from how the positional embeddings or other components are being handled.

To troubleshoot this, check the model's source code to ensure that all tensors, especially those related to positional embeddings, are explicitly moved to the correct device (`cuda:0` in your case) before the forward pass. If the tensors are constructed within the model, they need to be assigned to the `device` of the input tensors.

If the problem persists, you may be encountering a bug or an edge case not covered by the current export functionality. In this case, please feel free to raise an issue in the repository with the details you've provided here, and we'll look into it.

For now, double-check that the export is done with all components on the correct device, and consult the documentation on exporting models to ensure that all steps are followed correctly. Your efforts will also benefit the broader community as we aim to improve the robustness of the export functionality. Thank you for reaching out, and we appreciate your contribution to the Ultralytics YOLO community. 🚀

**Comment by bveldhoen** [comment]
Compiling the exported torchscript resulted in other error messages. See also these changes:
https://github.com/ultralytics/ultralytics/pull/6628

Therefore, we opted to export directly to tensorrt using the following code:

```
model = RTDETR('rtdetr-l.pt')
model.to(device)
model.export(format="tensorrt")
```

**Comment by glenn-jocher** [comment]
@bveldhoen it looks like you're adapting your approach to exporting the `RTDETR` model directly to the TensorRT format. The pull request you mentioned could potentially address the issue you are encountering. However, since I cannot view the content of the GitHub pull request, I'll provide some general advice.

The direct export to TensorRT should theoretically handle device-specific intricacies internally, ensuring that all tensors and operations are on the correct device, assuming proper implementation in the export function.

When you run `model.export(format="tensorrt")`, it typically performs necessary conversions and optimizations specific to TensorRT. However, errors during this process can be attributed to multiple factors such as mismatches in the expected input and output devices, unsupported layers or operations in the conversion to TensorRT, or discrepancies in the model's original forward implementation.

If you're encountering additional error messages with this method, here are some steps you can take to troubleshoot the issue:

1. Ensure that the dependencies for TensorRT export are correctly installed and compatible with your system and CUDA version.
2. Verify that your model is on the same device as the tensors it's working with. The model and all inputs should explicitly be on `device`, where `device` is typically `'cuda'` for TensorRT compatibility.
3. Check if the model or any of its components require additional configuration for TensorRT compatibility. This may be related to dynamic shapes or specific layers that TensorRT might not support natively.
4. Review the error messages and stack trace to determine which layer or operation is causing the issue, as this can provide insight into potential incompatibilities or the need for additional export logic.

If issues continue to arise, please submit a detailed bug report on the repository, including the error messages received and the conditions under which they occur. This will help the Ultralytics team to replicate and diagnose the problem more effectively.

In the meantime, consulting the detailed documentation on model export, TensorRT-specific guidelines, and community discussions can sometimes offer insights or workarounds discovered by others who have encountered similar challenges.

Thank you for working with the Ultralytics YOLO models, and we value your continued input as we strive to enhance our offerings. 🌟

**Comment by bveldhoen** [comment]
@glenn-jocher Thank you so much for your feedback and help. Just to clarify, the export to tensorrt engine was successful, and we can use it. That said, if the compilation to torch-tensorrt via torchscript export can be fixed, it would allow to compare the performance of both approaches.

**Comment by glenn-jocher** [comment]
@bveldhoen That's great to hear that you were successful in exporting to a TensorRT engine! Regarding the comparison between the TorchScript export and direct TensorRT export, it's a valuable point that being able to use both methods would allow for performance benchmarking.

Even though the direct TensorRT export is working, being able to also convert a TorchScript model to a TensorRT engine is important for flexibility and potentially optimizing different parts of the model pipeline. The Ultralytics team is constantly working on improving compatibility and support for various export formats.

For now, please monitor the updates to the repository. Issues related to export functions, like the one you've encountered, are often addressed incrementally as community feedback is received and tests are conducted. If the fix for the TorchScript export to TensorRT is implemented, it should be documented in the repository release notes. 

In the meantime, if you have detailed logs, error messages, or specific use cases where the TorchScript export fails, documenting your findings in an issue in the repo could significantly aid in diagnosing and resolving the issue.

Your contributions help in ensuring that the Ultralytics YOLO models provide robust and versatile tools for the community. Thank you for your patience and for sharing your success with the community. Your insight definitely helps in driving future improvements. Keep an eye on future updates, and happy benchmarking! 🏁📈
