### ISSUE TITLE
Display YOLO results in OpenCV window

### ISSUE THREAD

**Issue by DylDevs** [ultralytics/ultralytics#6577]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to make the results of YOLO detection show in a CV2 window. 
This is my current situation:
```
import dxcam
import cv2
import cv2
from ultralytics import YOLO
import os
import numpy as np
os.chdir(os.path.dirname(__file__))

model = YOLO("yolov8n.pt")

camera = dxcam.create(device_idx=0, output_color="BGR")
left = 0
top = 0
bottom = 768     
right = 1360

cv2.namedWindow("Vehicle Detection", cv2.WINDOW_NORMAL)
cv2.resizeWindow("Vehicle Detection", 400, 240)
cv2.setWindowProperty("Vehicle Detection", cv2.WND_PROP_TOPMOST, 1)

while True:
    frame = camera.grab(region=(left,top,right,bottom))
    if frame is None: 
        continue
    results = model.track(source=frame, show=True)

    cv2.imshow("Vehicle Detection", results)
    cv2.waitKey(1)
```

**Comment by glenn-jocher** [comment]
@DylDevs hello! It looks like you're trying to display the YOLO detection results in a CV2 window, which is a common task when creating real-time object detection applications. I see you're using the `track` mode from our YOLOv8 model to process the frames from your camera.

Please ensure that `model.track()` is returning a numpy array. This function should process the input frames and return the annotated frames if `show=True` is indeed providing the expected results for visualization. The numpy array needs to be compatible with `cv2.imshow()`.

Instead of directly inserting `results` in `cv2.imshow()`, you might have to extract the frame from the results object, which contains the annotated image. This typically involves accessing a property or method of the `results` object that contains the image data. As per our documentation, you should be able to obtain the image array by accessing the `.img` attribute or an equivalent method provided by the track function.

Once you have the numpy array of the frame, you can then pass it to `cv2.imshow()` to display it. Do not forget to handle the 'q' key event to break out of the loop and release the resources properly by using `cv2.destroyAllWindows()`.

Remember to use only the relevant attributes and methods from the `results` object as per our documentation.

If you require further assistance, I suggest reviewing the Predict mode documentation in the Ultralytics Docs and checking YOLO object tracking related examples or discussions in our GitHub repository. They can provide additional insights into how to correctly display the processed frame.

Happy coding! 🚀

**Comment by DylDevs** [comment]
Thanks for the answer, I will try. This out tomorrow morning 👍

**Comment by glenn-jocher** [comment]
You're welcome, @DylDevs! I'm glad I could help. If you have any more questions or run into issues, feel free to reach out. Have a great time working on your project tomorrow, and good luck with the YOLO detection in your application! 👍😊

**Comment by DylDevs** [comment]
I looked on the forum and found this: https://docs.ultralytics.com/modes/track/#persisting-tracks-loop

I edited my while loop to this:
```
while True:
    frame = camera.grab(region=(left,top,right,bottom))
    if frame is None: 
        continue
    results = model.track(source=frame, show=False)

    # Visualize the results on the frame
    annotated_frame = results[0].plot()

    cv2.imshow("Vehicle Detection", annotated_frame)
    cv2.waitKey(1)
```
Now the results are displaying in a cv2 window, thank you for the help!

**Comment by glenn-jocher** [comment]
That's fantastic to hear, @DylDevs! It looks like you've found the solution by using the `plot()` method on the results to visualize the annotated frames. I'm glad to know it's working for you now.

If you need any further assistance or have more questions as you continue to develop your project with YOLOv8, don't hesitate to ask. Keep up the great work, and enjoy building with YOLO! 🎉🚗
