### ISSUE TITLE
Invalid parameter save_dir in model.predict

### ISSUE THREAD

**Issue by 944613709** [ultralytics/ultralytics#6581]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I want to change the save path of "save_txt", but passing in the save_dir parameter has no effect. Here is my code

`model = YOLO('IH-821.onnx')`
`results = model.predict('test2.jpg', conf=0.5, save=True,save_txt=True, save_dir='save_txt')`

### Additional

I tried to search for a solution and unfortunately didn't find one

**Comment by glenn-jocher** [comment]
@944613709 hello! It seems you're encountering an issue with specifying the save directory when using the `model.predict` method. In YOLOv8, the functionality to change the save path for the prediction outputs, including text files, is handled differently compared to some earlier versions of YOLO.

To save your results to a specific directory, you should utilize the `project` and `name` parameters. These parameters specify the save directory indirectly by allowing you to set a project name (as a directory path) and an experiment name (as a subdirectory within the project directory). The saved outputs, including text files if `save_txt` is set to `True`, will be placed within this subdirectory.

For example, instead of using the `save_dir` parameter, which is invalid, you can use the following approach:

```python
model = YOLO('IH-821.onnx')
results = model.predict('test2.jpg', conf=0.5, save=True, save_txt=True, project='runs/detect', name='exp')
```

In the above code, replace `'runs/detect'` with the path where you want to save the files, and `'exp'` with the preferred name for the experiment's output directory. The text files, along with other output files, will be saved in the specified `project/name` folder.

For more details on configuring the save paths and other parameters, you can always look at the Predict section of the [Ultralytics Docs](https://docs.ultralytics.com/modes/predict).

Happy coding, and if you have any more concerns or questions, feel free to ask. The community and the Ultralytics team are here to help! 😊

**Comment by 944613709** [comment]
> @944613709 hello! It seems you're encountering an issue with specifying the save directory when using the `model.predict` method. In YOLOv8, the functionality to change the save path for the prediction outputs, including text files, is handled differently compared to some earlier versions of YOLO.
> 
> To save your results to a specific directory, you should utilize the `project` and `name` parameters. These parameters specify the save directory indirectly by allowing you to set a project name (as a directory path) and an experiment name (as a subdirectory within the project directory). The saved outputs, including text files if `save_txt` is set to `True`, will be placed within this subdirectory.
> 
> For example, instead of using the `save_dir` parameter, which is invalid, you can use the following approach:
> 
> ```python
> model = YOLO('IH-821.onnx')
> results = model.predict('test2.jpg', conf=0.5, save=True, save_txt=True, project='runs/detect', name='exp')
> ```
> 
> In the above code, replace `'runs/detect'` with the path where you want to save the files, and `'exp'` with the preferred name for the experiment's output directory. The text files, along with other output files, will be saved in the specified `project/name` folder.
> 
> For more details on configuring the save paths and other parameters, you can always look at the Predict section of the [Ultralytics Docs](https://docs.ultralytics.com/modes/predict).
> 
> Happy coding, and if you have any more concerns or questions, feel free to ask. The community and the Ultralytics team are here to help! 😊

Thank you very much. My problem was successfully solved, have a nice life!

**Comment by glenn-jocher** [comment]
@944613709 I'm glad to hear that your issue was resolved! Should you have any more questions or need further assistance in the future, don't hesitate to reach out. Wishing you the best with your projects and a wonderful life as well! 😊🚀
