### ISSUE TITLE
Extend augment.py to support segments for Albumentation

### ISSUE THREAD

**Issue by yhshin11** [ultralytics/ultralytics#6601]
Hello all.

Has there been any progress on adding support for segmentation mask augmentation from albumentation? There are quite a few useful spatial augmentations available in albumentation and it seems a shame that we only have access to pixel-level augmentations. I see [here](https://github.com/ultralytics/ultralytics/blob/fdcf0dd4fda06c4c67bde061fe98f9ddd77b2ea4/ultralytics/data/augment.py#L822) that it was commented as a todo item last year.

Perhaps we could discuss what is needed to support this so that I can work on a pull request to add segmentation mask support?

This is what I have so far:

- Ultralytics uses sampled polygons to represent masks/segments, while albumentations uses binary masks
    - There is already code to convert [polygons to masks](https://github.com/ultralytics/ultralytics/blob/fdcf0dd4fda06c4c67bde061fe98f9ddd77b2ea4/ultralytics/data/augment.py#L904C12-L904C12) and [masks to polygons](https://github.com/ultralytics/ultralytics/blob/fdcf0dd4fda06c4c67bde061fe98f9ddd77b2ea4/ultralytics/utils/ops.py#L750C12-L750C12).

Then it seems that we just need to convert `labels['instances'].segments` to binary masks, pass the binary masks to albumentations, and convert the transformed masks back to polygons, using the pre-existing code mentioned above.

Am I missing something?

**Comment by glenn-jocher** [comment]
@yhshin11 hello there!

Firstly, thank you for your interest in helping to improve the Ultralytics repository. Your understanding of the current augmentation setup and consideration of segment support for albumentations is appreciated!

You're on the right track in recognizing that the primary difference lies in Ultralytics using polygon representations for masks, as opposed to the binary mask format utilized by albumentations. Indeed, the code to perform conversions between both formats exists, as you have noted.

The sequence of steps you've outlined is essentially what would be required to integrate segmentation mask support with albumentation augmentations. To summarize, the process would involve:

1. Converting the `labels['instances'].segments` from polygons to binary masks.
2. Applying the spatial transformations using albumentations to the binary masks and images.
3. Converting the altered masks back to polygon format so they can be used further within Ultralytics YOLOv8's existing framework.

The key to a successful integration is ensuring that the transformations applied to the images and masks are perfectly in sync, so that the resulting polygons accurately reflect the changes in the transformed images.

One thing to keep abreast of when working on this integration is maintaining compatibility with the variety of spatial augmentations and ensuring that the resulting masks are valid with respect to the transformed images.

Submitting a pull request would be the perfect next step, as it would allow the community and Ultralytics team to test, review, and refine the implementation.

Thank you for your initiative! It's through contributors like you that we continue to evolve and improve. If you're ready to work on this feature, feel free to collaborate further on the specifics over pull requests on our GitHub repo. Good luck, and we look forward to your contributions!

Happy coding! 😊👨‍💻🚀
