### ISSUE TITLE
OutOfMemoryError while inference segmentation

### ISSUE THREAD

**Issue by dimkoss11** [ultralytics/ultralytics#6602]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

`OutOfMemoryError: CUDA out of memory. Tried to allocate 138.00 MiB (GPU 0; 14.76 GiB total capacity; 13.53 GiB already allocated; 33.75 MiB free; 13.72 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

I have used YOLOv8 for segmentation and get OutOfMemoryError while inference even without batches (by single images)

predict_res = model.predict("/kaggle/working/data/val/images/", imgsz=512, conf=0.128, iou=0.7, half=True, save_conf=True, save=True, save_txt=True, show_labels=False) # , retina_masks=True device=[0, 1] # stream=True

OR

```
predict_res = []

for item in np.array_split(sorted(glob.glob("/kaggle/working/data/val/images/*")), len(glob.glob("/kaggle/working/data/val/images/*"))):
    predict_res.extend(model.predict(item.tolist(), imgsz=512, conf=0.128, iou=0.7, half=True, save_conf=True, save=True, save_txt=True, show_labels=False))  
```

I have ~ 5000 images and get error after 1/3 or small if I did increase image size. What should I do?

**Comment by zai1318** [comment]
1. You're currently using an image size of 512 (imgsz=512). Reducing this size can significantly decrease memory usage. However, be aware that this might impact the model's accuracy or its ability to detect smaller objects.
2. You mentioned you are processing images without batches. Although it seems counterintuitive, using small batches can sometimes be more efficient than single image processing due to how GPUs handle parallel computation. Experiment with a very small batch size.
3. Make sure to clear the PyTorch cache regularly during inference if you're running a loop. You can do this with torch.cuda.empty_cache() .
4. As suggested by the error message, try setting the max_split_size_mb to manage memory fragmentation.
5. If possible, use a less complex version of the model. Models with fewer parameters and layers consume less memory.

**Comment by glenn-jocher** [comment]
@zai1318 hi there! It looks like you're experiencing an `OutOfMemoryError` while using YOLOv8 for segmentation tasks. This can indeed be frustrating, but there are several strategies you can try to mitigate this issue. 

Firstly, try reducing the image size (`imgsz`) from 512 to a smaller dimension, which can lower the memory footprint during inference while being mindful of the potential trade-offs in detection performance.

Secondly, although you're currently running inference on single images, sometimes using a small batch size can help optimize memory usage due to the way GPU memory is allocated. It's worth experimenting with a minimal batch size to see if that improves your situation.

Moreover, it's good practice to clear the GPU memory cache regularly, especially when running inference in a loop. If you haven't done this yet, consider implementing a cache clearing step within your inference loop.

The error message also suggests setting `max_split_size_mb` to control memory fragmentation. This can be another avenue to explore to prevent the out-of-memory issues you're facing.

And lastly, if your model is still too large for the available memory, consider using a simpler model version with fewer parameters that requires less memory.

Remember, adjustments might require some trial and error to balance memory usage and performance effectively. I hope these suggestions help you move forward with your segmentation tasks using YOLOv8! 😊👍

**Comment by zai1318** [comment]
@dimkoss11

**Comment by dimka11** [comment]
Ok, I have need to copy predict data to cpu via:

```
predicts = model.predict(...)
[pred.cpu() for pred in predicts]
before adding to the list
```

But now I have out of RAM, because 5000 masks take up too much memory space.
Any ideas? Except run predict multiple times and compute and averaging metrics.

**Comment by glenn-jocher** [comment]
@dimka11, handling large amounts of data like 5000 masks can indeed lead to RAM constraints, especially when working with limited resources. If transferring prediction results to the CPU causes RAM overflow, consider a few alternatives:

1. **Incremental Saving:** Instead of keeping all masks in memory, you could save the predictions directly to the disk after each inference. Once saved, you can clear them from memory before proceeding with the next inference task.

2. **Downsampling Masks:** If full resolution isn't required for your application, you could downsample masks before saving or processing them. This can significantly reduce memory usage.

3. **Memory Mapping:** Use memory-mapped files (such as those provided by numpy.memmap) to store masks. This approach allows the objects to stay on disk, with only small parts being loaded into memory as needed.

4. **Stream Processing:** If your final goal is to compute some metrics, consider stream processing techniques. Process and compute metrics one by one (or in small batches) and accumulate only the metrics rather than the masks themselves.

5. **In-place Operations:** Wherever possible, use in-place operations to modify data, which can help to reduce the memory footprint.

With these strategies, you should be able to work around your RAM limitations and complete your segmentation tasks with YOLOv8. Remember to optimize the process flow and keep resource consumption in mind at each step. Good luck! 😄🖖
