### ISSUE TITLE
Using Yolov8's onnx model for target detection through C++, the results running through CPU and GPU are inconsistent

### ISSUE THREAD

**Issue by lie12huo** [ultralytics/ultralytics#6605]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I used Yolov8's onnx model for target detection through C++, and the detection results running through the CPU were correct. When calling net.setPreferableBackend(cv::dnn::DNN_BACKEND_OPENCV) and
         net.setPreferableTarget(cv::dnn::DNN_TARGET_CPU) turns on CUDA DNN detection, the data returned by the net.forward() function, the class_id and confidences data are consistent with the CPU operation, but all box data are null.
CPU result:
 
![image](https://github.com/ultralytics/ultralytics/assets/52315796/09406e61-9e83-4a6c-a721-ef0a9f9882f9)
  
GPU result：
![image](https://github.com/ultralytics/ultralytics/assets/52315796/d6052698-bfa4-4267-98e3-44b296d7879b)

The OPENCV version I used is 4.8.1, the CUDA version is 11.8, the CUDNN version is 8.9.6, the graphics card model is NVIDIA GeForce GTX 1660 Ti, and the driver version is 546.17.

**Comment by lie12huo** [comment]
Because the box data is all 0, the final detection result of cv::dnn::NMSBoxes() after deletion will be only one, and the position is not correct. In addition, my operating system is Window 10, and the development and running environment is Visual Studio 2022.

**Comment by glenn-jocher** [comment]
@lie12huo hello! It's great to see you using YOLOv8 with ONNX for your target detection project in C++. I understand that the detection results on the CPU are correct, but when switching to GPU with CUDA, you encounter issues specifically with the bounding box data being null. This inconsistency between CPU and GPU outputs can arise due to several factors.

To start troubleshooting, consider the following:

- **ONNX Opset Version**: Ensure that you exported the ONNX model with the correct opset version that is fully supported by the OpenCV DNN module.
- **OpenCV DNN Backend**: Different backends and targets in OpenCV can behave differently. It's possible there may be a bug or an unsupported feature in the current combination of backend and target you are using.
- **Model Export Compatibility**: Check if the ONNX model has any specific layers or operations that might not be fully compatible with the OpenCV CUDA backend.
- **Precision Mismatch**: When switching between devices, there can sometimes be precision differences. Check if the model runs in different precision modes on CPU and GPU.
- **Version Compatibility**: Ensure that the versions of OpenCV, CUDA, and cuDNN you are using are compatible with each other and also check for any known issues with the specific versions.
- **Debugging**: Try stepping through the code to see exactly where the differences in output occur. This might help you pinpoint if the issue is occurring during preprocessing, forwarding through the network, or postprocessing.

If your investigation doesn’t solve the problem, you might want to verify if others have experienced similar issues with similar configurations by checking the respective issue trackers of OpenCV and ONNX, as this may not be an issue originating from the model itself, but rather from the inference environment. Keeping a close eye on compatibility and updates from the OpenCV community would be advantageous.

For further guidance, feel free to explore the sections on Predict and Export at our Ultralytics Docs, which could give you more insights into the correct usage and potential configuration nuances of YOLOv8 models. Your contributions and queries help improve YOLOv8 and we certainly appreciate the feedback. Keep us posted on your progress! 😊

**Comment by lie12huo** [comment]
I tried different export parameters Opset (9-17) and different OpenCV versions (V4.7.0, V4.8.0 and V4.8.1), but the test results are still the same as before: the results running on the CPU are correct, but after switching to GPU for inference, the box data returned from net.forward() will be all 0.
In addition, if the model is called directly in Python, the results of running on CPU or GPU will be correct. The same OpenCV, CUDA and DNN versions are used when running in Python and C++.

**Comment by glenn-jocher** [comment]
Hello again, @lie12huo! The fact that the Python implementation works fine on both CPU and GPU, but the C++ implementation does not, points to an issue with the C++ code or the way the OpenCV DNN module's C++ API is interacting with the ONNX model on the GPU.

Since you've explored various opsets and OpenCV versions, the problem likely lies a bit deeper. Here are a few more steps you can take to debug this situation:

1. **API Differences**: Double-check the C++ and Python code to ensure that the preprocessing steps, such as image normalization and resizing, are consistent. Differences in API usage between Python and C++ could lead to unexpected outcomes.

2. **OpenCV DNN Module**: Use the `getLayerNames()` and `getUnconnectedOutLayers()` methods in the OpenCV DNN module in your C++ code to inspect the layer outputs and see if the expected outputs are indeed being produced and connected.

3. **Data Handling**: Look into how you're extracting and handling the output data in C++. There could be differences in memory management or how the data is accessed compared to the Python version.

4. **Debugging Tools**: Utilize debugging tools available for C++ to step through each line of code and monitor the values of the variables. This may shine a light on where the zeroed out box data is originating from.

5. **Code Comparisons**: Look for any discrepancies between how you're setting the preferable backend and target in Python versus C++. Minor differences could result in significant changes in output.

6. **Documentation and Examples**: Review OpenCV's official documentation and examples for utilizing ONNX models with GPU backends in C++. There might be nuances or additional steps required that differ from the Python implementation.

7. **OpenCV Community and Issues**: Since this seems to be related to OpenCV's handling of the ONNX model in C++ when using the GPU, reaching out to the OpenCV community or exploring the OpenCV issue trackers for similar problems might reveal known issues or workarounds.

8. **Minimal Working Example**: Create a minimal working example in C++ that replicates the issue and share it with the OpenCV community to get more specific help. Sometimes, reducing the problem to its simplest form can reveal where things are going wrong.

Remember that the objective is to identify if the problem occurs before entering the network (during preprocessing), inside the network, or after the detection (during postprocessing). Again, if you manage to resolve this, your findings will be very valuable for the YOLOv8 and broader machine learning community. Good luck, and I'm rooting for your success! 🚀

**Comment by zp870420** [comment]
@glenn-jocher @lie12huo I have the same question.you are right "Check if the ONNX model has any specific layers or operations that might not be fully compatible with the OpenCV CUDA backend." 。I debug ，I find two operations dont run  on cuda,
![Uploading 屏幕截图 2023-12-03 145442.png…]()
![Uploading 屏幕截图 2023-12-03 145508.png…]()
![Uploading 屏幕截图 2023-12-03 145529.png…]()

**Comment by zp870420** [comment]
@glenn-jocher @lie12huo I have the same question.you are right "Check if the ONNX model has any specific layers or operations that might not be fully compatible with the OpenCV CUDA backend." 。I debug ，I find two operations dont run  on cuda:
![屏幕截图 2023-12-03 145442](https://github.com/ultralytics/ultralytics/assets/6006799/520e6b20-71c8-4ae9-a8c1-0e0c4c2f61da)
![屏幕截图 2023-12-03 145508](https://github.com/ultralytics/ultralytics/assets/6006799/53cda84a-24c7-428b-b086-c04d90d15e8d)
![屏幕截图 2023-12-03 145508](https://github.com/ultralytics/ultralytics/assets/6006799/b7957fd4-a3f7-459e-8669-5005d57c8aa9)

**Comment by zp870420** [comment]
@glenn-jocher @lie12huo I have the same question.you are right "Check if the ONNX model has any specific layers or operations that might not be fully compatible with the OpenCV CUDA backend." 。I debug ，I find two operations dont run  on cuda
![屏幕截图 2023-12-03 145442](https://github.com/ultralytics/ultralytics/assets/6006799/984352ec-1257-44cd-8416-f34393c04a93)
![屏幕截图 2023-12-03 145508](https://github.com/ultralytics/ultralytics/assets/6006799/9a586b40-361e-42f9-bdf3-7aebfc8a3cfc)
![屏幕截图 2023-12-03 145529](https://github.com/ultralytics/ultralytics/assets/6006799/6f0509c2-18c9-4964-a6c8-4424a9d506f5)

**Comment by glenn-jocher** [comment]
Thank you for the update and the additional debugging information, @zp870420. It's insightful that you've identified specific operations that aren't running on CUDA within the OpenCV DNN module. This observation directs us towards a compatibility issue between the exported ONNX model and the OpenCV CUDA backend.

Given that you've isolated the problem to particular layers or operations, here are your next steps:

1. **OpenCV Issues**: Verify if these operations have known issues with CUDA support by checking OpenCV's issue tracker and user forums.

2. **Layer Compatibility**: Look into the OpenCV documentation to see if there are any known limitations with these operations on the CUDA backend. OpenCV's CUDA support for DNN operations is not always exhaustive, and some layers may not be implemented or optimized for GPU.

3. **Model Customization**: If you can determine which specific layers correspond to these operations, you could consider modifying the architecture or exporting approaches to use alternative or simplified operations that have better support on CUDA.

4. **OpenCV Contributions**: If you have the expertise or the resources, consider contributing to OpenCV's development to enhance support for these operations on CUDA. Open source contributions like this are greatly valued by the community.

5. **Fallback Mechanism**: If only certain layers are incompatible, one potential workaround is to run the model with a hybrid approach—letting the compatible layers execute on the GPU while the unsupported layers fall back to the CPU. This might require customized code that splits processing between both devices.

6. **Alternative Libraries**: If OpenCV is unable to provide the GPU support you need, you might explore using other libraries more suited to ONNX model execution on GPUs, such as ONNX Runtime with CUDA support.

7. **OpenCV Community**: Engage with the OpenCV community, providing details of your findings. Someone may have encountered a similar issue and may be able to provide a solution or a workaround.

Lastly, please consider sharing these insights with your findings in relevant discussion forums or issue trackers for OpenCV. This might prompt the maintainers to prioritize support for these operations or provide clarity on the issue which would be beneficial for all users of the library. Your efforts to uncover this might be the first step in addressing a larger compatibility challenge. Keep up the great work, and thank you for actively participating in the open-source ecosystem! 🌟

**Comment by lie12huo** [comment]
OPENCV 4.7.0 + CUDA 11.8 + CUDNN 8.9.6, this problem can be solved ,the GPU can work normally like the CPU.

**Comment by glenn-jocher** [comment]
Thank you for sharing your findings, @lie12huo! It's fantastic to hear that you've managed to resolve the issue by using the combination of OpenCV 4.7.0 along with CUDA 11.8 and cuDNN 8.9.6, and that the GPU is now functioning correctly, just like the CPU. This information is incredibly valuable and could benefit others facing similar problems. We appreciate your contribution to the community! 👍🎉

**Comment by BackT0TheFuture** [comment]
@lie12huo 
I have the same problem,  could you tell me how to fix this ?
thx.

**Comment by lie12huo** [comment]
@BackT0TheFuture Yes, I solved the problem by changing the version：OPENCV 4.7.0 + CUDA 11.8 + CUDNN 8.9.6

**Comment by BackT0TheFuture** [comment]
@lie12huo 
thank you for your answer.
I tried but still failed (**OPENCV 4.8.1** + CUDA 11.8 + CUDNN 8.9.6).
have you tried this combination?

**Comment by lie12huo** [comment]
@BackT0TheFuture I tried OPENCV 4.8.0 and OPENCV 4.8.1，both had this problem, so I returned OPENCV 4.7.0.

**Comment by Garrypeng** [comment]
@lie12huo Bro, have you recompiled using CMake every time you change the Opencv and cudnn versions?

**Comment by glenn-jocher** [comment]
Yes, I've recompiled using CMake every time I changed the OpenCV and cuDNN versions. This step is crucial to ensure that all dependencies are correctly linked and configured. 

If you continue to face issues, please make sure you are using the exact versions mentioned: **OpenCV 4.7.0**, **CUDA 11.8**, and **cuDNN 8.9.6**. It seems that newer versions of OpenCV (like 4.8.0 and 4.8.1) might still have compatibility issues with CUDA and cuDNN.

If you haven't already, please ensure that you follow these steps:
1. **Clean Build Directory**: Before recompiling, clean your build directory to remove any old or conflicting files.
2. **Set Correct Paths**: Ensure that your CMake configuration points to the correct paths for OpenCV, CUDA, and cuDNN.
3. **Check Dependencies**: Verify that all dependencies are correctly installed and compatible with each other.

If the issue persists, please provide a minimum reproducible example of your code so we can investigate further. You can find guidelines for creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example). This will help us better understand and address the problem.

Thank you for your patience and cooperation! 😊
