### ISSUE TITLE
V5loader set to 'false' causes longer validation during training

### ISSUE THREAD

**Issue by Kacper-Marciniak** [ultralytics/ultralytics#663]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Using  ```v5loader=False``` increases the validation time from 0:44 (```True```) to 1:21 (```False```).  
I obtained this data while training locally on my own dataset with 111 images in the 'val' subset and ```cache=True```.

### Environment

Ultralytics YOLOv8.0.21
Python-3.10.6 
torch-1.13.1+cu117 CUDA:0 (NVIDIA GeForce RTX 2080 Ti, 11264MiB)
Windows 10 Pro 22H2
Jupyter Notebook

### Minimal Reproducible Example

```
model = YOLO("yolov8l.pt")
model.train( data="coco128.yaml",  epochs=5, cache=True,  v5loader=False )
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pderrenger** [comment]
@Kacper-Marciniak hi there! It looks like you're experiencing longer validation times when setting `v5loader=False` during training in YOLOv8. This issue can be due to the change in data loading behavior.

When `v5loader` is set to `True`, the validation time is shorter because YOLOv8 uses the YOLOv5 style data loader, which is optimized for faster data loading. Conversely, setting `v5loader=False` uses a different data loading approach, potentially leading to longer validation times.

Consider keeping `v5loader=True` if faster validation times are crucial, especially for larger datasets. However, if you need to use `v5loader=False` for specific reasons, you might experiment with different cache settings or dataset configurations to optimize validation time.

I hope this sheds some light on the issue! If you have further questions or need assistance with anything else related to YOLOv8, feel free to ask 😊

**Comment by glenn-jocher** [comment]
@pderrenger Hello! It seems you've noticed a difference in validation times when toggling the `v5loader` parameter. The `v5loader=True` setting activates an optimized data loader, which is why you're seeing quicker validation times. With `v5loader=False`, the data loading is less efficient, hence the increase in validation duration.

For the best performance, I recommend using `v5loader=True`. If there's a specific need to use `v5loader=False`, you might want to look into optimizing other aspects of your data pipeline. If you have more questions or need further assistance, we're here to help! 😊
