### ISSUE TITLE
About Benchmark

### ISSUE THREAD

**Issue by RayLumia** [ultralytics/ultralytics#6648]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I tried benchmark process with yolov8x.pt:
![image](https://github.com/ultralytics/ultralytics/assets/65215886/1f92165e-3690-4c7c-8d10-1210190ccd0b)
Then,I got the result below:
![image](https://github.com/ultralytics/ultralytics/assets/65215886/edb74ac2-f6a7-4c04-8baf-84e198c8bde6)
It's wired that the models besides Pytorch show the same mAP50-95.What did I do wrong?

**Comment by glenn-jocher** [comment]
@RayLumia hello there,

Thank you for reaching out and for conducting the benchmark process with YOLOv8. The result you're observing, where various export formats show the same mAP (mean Average Precision), is actually expected behavior. The mAP is a metric that evaluates the accuracy of object detection models and should remain consistent across different model formats if the export process preserves the model's layers and weights accurately. 

Different export formats such as ONNX, CoreML, or TFLite are designed to offer compatibility with various platforms and hardware while ideally retaining the same level of accuracy as the original PyTorch model. The primary differences you might observe among these formats would typically be in inference speed or memory usage, rather than in their mAP values. 

If you have further concerns about the benchmark results or if you're noticing other irregularities, please ensure you're following the benchmark instructions precisely as outlined in the Ultralytics Docs, and feel free to share additional details so we can assist you better.

Keep exploring and happy benchmarking! 🚀
