### ISSUE TITLE
YOLOv8-segmentation performance  is not particularly effective for detecting small objects

### ISSUE THREAD

**Issue by fry404006308** [ultralytics/ultralytics#6652]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

The segmentation performance of YOLOv8 is not particularly effective for detecting small objects. For instance, it struggles to detect objects of 20x20 pixels on an image of 4096x7000 pixels.

Upon examining the reasons behind this, we find that if the original image size is 4096x7000 and we set the training size to 2048, the size of the image during training would be 2048x2048. Correspondingly, the dimensions of the result feature map would be one fourth of the training image size, thus reducing to 512x512.

As a result, when the detection from a 512x512 map is projected onto a 4096x7000 image, the width and height are approximately enlarged by a factor of 20. This means that a 1x1 pixel value on the detection result corresponds to a 20x20 pixel value on the original image. Therefore, objects smaller than 20x20 pixels are not effectively detected.

Do you have any suggestions on how I might modify this?

Alternatively, are there any real-time semantic segmentation models you would recommend from 2022 or 2023, preferably with less than 100M parameters, and ideally less than 50M? For example, the YOLOv8m-seg model has 27.3M parameters, or perhaps something like the BiSeNetV2 model.

Or any suggestions.

Thanks.

![YOLOV8特征图变化 drawio](https://github.com/ultralytics/ultralytics/assets/33335064/72828b2c-dec8-4b0e-b5fc-6d8400fc00db)

**Comment by glenn-jocher** [comment]
@fry404006308 hello!

Detecting small objects in high-resolution images indeed poses a significant challenge, as the feature map resolution impacts the model's ability to discern fine details. For improving detection of small objects in YOLOv8, consider the following advice:

1. **Training Configuration**: Modify the training pipeline to include smaller objects more prevalently or augment the training data with techniques that emphasize the smaller objects.

2. **Model Architectures**: Experiment with different model architectures provided by YOLOv8, as some are designed to focus more on smaller objects.

3. **Multi-Scale Training**: Leverage multi-scale training strategies that allow the model to learn to detect objects across various sizes.

4. **Tiling Approach**: Use a tiling approach where the input image is divided into overlapping tiles before prediction, allowing the detection of small objects with more granularity.

5. **Specialized Networks**: Look into specialized networks that are optimized for small object detection, integrating them into the YOLOv8 framework if possible.

6. **Focus on Feature Pyramid Networks (FPNs)**: FPNs can enhance the model's performance on various object sizes by leveraging multi-level feature maps.

Regarding real-time semantic segmentation models, we focus on continual development and improvement of our own architectures, so I’d recommend staying updated with our latest releases and documentation for the best possible solutions. Our model - YOLOv8m-seg, is indeed one choice you might continue to explore and tune. While I cannot directly recommend models from 2022 or 2023 outside our suite, I advise you to look for benchmarks showcasing high performance with real-time inference capabilities and low parameter counts. 

Your issue is vital for the continuous development of YOLOv8, and we deeply appreciate your input. For further detailed techniques and model-specific guidance, please refer to our detailed [Segmentation Docs](https://docs.ultralytics.com/tasks/segment).

**Comment by NawoyaSarah** [comment]
@glenn-jocher @fry404006308 could you be having any idea on how to perform image tiling in Yolov8-seg? Sahi works only with the bounding boxes and I am working with masks.

**Comment by Tensing2009** [comment]
@NawoyaSarah Not sure this is still relevant, but try [SAHI](https://github.com/obss/sahi)
