### ISSUE TITLE
CUDA Error in YOLOv8 Deployment on Xavier NX with Ultralytics Jetson Dockerfile

### ISSUE THREAD

**Issue by AouatifZ** [ultralytics/ultralytics#6656]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello community,

I encountered a CUDA problem while deploying the YOLOv8 model on the Xavier NX with Jetpack 4.6.1. I successfully built the Ultralytics Jetson Dockerfile, but when I tested it on the GPU, I encountered an error related to the GPU.
![gp1](https://github.com/ultralytics/ultralytics/assets/111449259/046663a0-1482-4537-b868-f46f77580548)

I have verified the NVCC installations and received the following:
/usr/local/cuda/bin/nvcc --version

![gp2](https://github.com/ultralytics/ultralytics/assets/111449259/3bbe03e0-9d4f-4fb6-9b2d-c579d220280e)

When attempting to export a TensorRT model on my Xavier NX, I encountered an error
![gp3](https://github.com/ultralytics/ultralytics/assets/111449259/ae6a6272-2152-4cfb-8362-798f967f0a12)

Now, I'm having difficulty understanding the exact nature of the error.

Any help would be greatly appreciated.

**Comment by tibeoh** [comment]
Hello,

I have the similar issue with my Jetson Xavier.

<img width="603" alt="Screenshot 2023-12-12 at 16 33 27" src="https://github.com/ultralytics/ultralytics/assets/1993658/0ad5aff3-0fb0-4b05-9281-d0a2c72fa14f">

@AouatifZ Do you find a solution?

@glenn-jocher Thank you for your response. Can you give me more details about checks needed.
My container is running with `--runtime nvidia`
```
sudo docker run -it --runtime=nvidia --ipc=host --gpus all ultralytics/ultralytics:latest-jetson
```

About points 2,3 and 4, I do not have any idea how to check that. It will be very helpful to give me more details about these.

**Comment by glenn-jocher** [comment]
@tibeoh hello!

It looks like there might be a compatibility issue between the CUDA drivers, PyTorch, and the Torchvision versions in your container. Here's what you can check:

1. **CUDA Version**: Inside the container, verify the installed CUDA version using `nvcc --version`. Make sure it aligns with the version required by YOLOv8 and your JetPack.

2. **NVIDIA Drivers**: Ensure the NVIDIA driver version on your Xavier is compatible with the installed CUDA toolkit. Usually, NVIDIA’s documentation provides this info.

3. **PyTorch and Torchvision Compatibility**: As per the warning you received, it's recommended to update Torchvision to match your PyTorch version:
   
   ```shell
   pip install torchvision==0.15
   ```
   Or update both PyTorch and Torchvision:
   
   ```shell
   pip install -U torch torchvision
   ```
   This should resolve the version mismatch issue.

These steps should help you troubleshoot the problem. If the error persists, please provide the full error message, and we can look deeper into it. 😊 Keep in mind that YOLOv8 requires an environment where CUDA GPUs are properly recognized and compatible software versions are installed.

**Comment by tibeoh** [comment]
Thank you @glenn-jocher for your response.

1. > CUDA Version: Inside the container, verify the installed CUDA version using nvcc --version. Make sure it aligns with the version required by YOLOv8 and your JetPack.

Yes I have a difference CUDA version inside the container.
Outside container `nvcc --version`:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_28_22:34:44_PST_2021
Cuda compilation tools, release 10.2, V10.2.300
Build cuda_10.2_r440.TC440_70.29663091_0
```
Inside container `nvcc --version`:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Sun_Oct_23_22:16:07_PDT_2022
Cuda compilation tools, release 11.4, V11.4.315
Build cuda_11.4.r11.4/compiler.31964100_0
```

My jetpack version is 4.6.1 and I can not upgrade to version 5 because my Jetson Xavier use a Ubuntu 18 and it failed during installation...
Is it possible to upgrade CUDA version to 11 and how to do it?

2. > NVIDIA Drivers: Ensure the NVIDIA driver version on your Xavier is compatible with the installed CUDA toolkit. Usually, NVIDIA’s documentation provides this info.

I am not sure to understand what is the NVIDIA Drivers used? How can I check that?

3. > PyTorch and Torchvision Compatibility: As per the warning you received, it's recommended to update Torchvision to match your PyTorch version.

Before to update pytorch and torchvision I have this output:
```
/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:98: UserWarning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (Triggered internally at /home/riship/old_pyt/pytorch/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
Ultralytics YOLOv8.0.227 🚀 Python-3.8.10 torch-2.0.0a0+ec3941ad.nv23.02 CPU (ARMv8 Processor rev 0 (v8l))
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

WARNING ⚠️ torchvision==0.14 is incompatible with torch==2.0.
Run 'pip install torchvision==0.15' to fix torchvision or 'pip install -U torch torchvision' to update both.
For a full compatibility table see https://github.com/pytorch/vision#installation
1/1: https://youtu.be/LNwODJXcvt4... Success ✅ (10842 frames of shape 1920x1080 at 30.00 FPS)

0: 192x320 1 person, 2 chairs, 1 couch, 1 potted plant, 368.2ms
```

I tried `pip install torchvision==0.15`
```
/usr/local/lib/python3.8/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:98: UserWarning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (Triggered internally at /home/riship/old_pyt/pytorch/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
Ultralytics YOLOv8.0.227 🚀 Python-3.8.10 torch-2.0.0a0+ec3941ad.nv23.02 CPU (ARMv8 Processor rev 0 (v8l))
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

1/1: https://youtu.be/LNwODJXcvt4... Success ✅ (10842 frames of shape 1920x1080 at 30.00 FPS)

Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 11, in <module>
    load_entry_point('ultralytics', 'console_scripts', 'yolo')()
  File "/usr/src/ultralytics/ultralytics/cfg/__init__.py", line 448, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/src/ultralytics/ultralytics/engine/model.py", line 239, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/usr/src/ultralytics/ultralytics/engine/predictor.py", line 207, in predict_cli
    for _ in gen:  # running CLI inference without accumulating any outputs (do not modify)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 50, in generator_context
    response = gen.send(None)
  File "/usr/src/ultralytics/ultralytics/engine/predictor.py", line 269, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "/usr/src/ultralytics/ultralytics/models/yolo/detect/predict.py", line 25, in postprocess
    preds = ops.non_max_suppression(preds,
  File "/usr/src/ultralytics/ultralytics/utils/ops.py", line 238, in non_max_suppression
    i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
  File "/usr/local/lib/python3.8/dist-packages/torchvision/ops/boxes.py", line 40, in nms
    _assert_has_ops()
  File "/usr/local/lib/python3.8/dist-packages/torchvision/extension.py", line 48, in _assert_has_ops
    raise RuntimeError(
RuntimeError: Couldn't load custom C++ ops. This can happen if your PyTorch and torchvision versions are incompatible, or if you had errors while compiling torchvision from source. For further information on the compatible versions, check https://github.com/pytorch/vision#installation for the compatibility matrix. Please check your PyTorch version with torch.__version__ and your torchvision version with torchvision.__version__ and verify if they are compatible, and if not please reinstall torchvision so that it matches your PyTorch install.
FATAL: exception not rethrown
```

And after `pip install -U torch torchvision`

```
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 11, in <module>
    load_entry_point('ultralytics', 'console_scripts', 'yolo')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/src/ultralytics/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO
  File "/usr/src/ultralytics/ultralytics/models/__init__.py", line 3, in <module>
    from .rtdetr import RTDETR
  File "/usr/src/ultralytics/ultralytics/models/rtdetr/__init__.py", line 3, in <module>
    from .model import RTDETR
  File "/usr/src/ultralytics/ultralytics/models/rtdetr/model.py", line 10, in <module>
    from ultralytics.engine.model import Model
  File "/usr/src/ultralytics/ultralytics/engine/model.py", line 8, in <module>
    from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
  File "/usr/src/ultralytics/ultralytics/cfg/__init__.py", line 10, in <module>
    from ultralytics.utils import (ASSETS, DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, RANK, ROOT, RUNS_DIR,
  File "/usr/src/ultralytics/ultralytics/utils/__init__.py", line 21, in <module>
    import torch
  File "/usr/local/lib/python3.8/dist-packages/torch/__init__.py", line 235, in <module>
    from torch._C import *  # noqa: F403
ImportError: /usr/local/lib/python3.8/dist-packages/torch/lib/../../torch.libs/libgomp-6e1a1d1b.so.1.0.0: cannot allocate memory in static TLS block
```

Thank you for your response. Sorry, I'm new to this field and I'm trying to get YOLO running on my Jetson Xavier, but at every step, I encounter new compatibility issues with the installations. I want to clarify that YOLO is properly installed and functional outside of Docker on my Jetson at the moment.

**Comment by glenn-jocher** [comment]
@tibeoh hello,

It seems there are several issues to address related to CUDA versions, NVIDIA driver compatibility, and torchvision installation errors inside your Docker container.

1. **CUDA Version Issue**: Upgrading the CUDA version on Jetson devices is tied to the JetPack version. Unfortunately, if you're unable to upgrade to JetPack 5 due to Ubuntu 18 constraints, you might be limited to the CUDA version provided by JetPack 4.6.1. You could consider rebuilding or modifying the Docker container to use a compatible CUDA version with JetPack 4.6.1.

2. **NVIDIA Driver Check**: The NVIDIA driver supports the CUDA toolkit and is generally bundled with the JetPack installation. To verify the driver version, run `cat /proc/driver/nvidia/version`. It's not typically something you'd change separately, as it's tailored to match the JetPack release.

3. **PyTorch and Torchvision Compatibility**: The errors suggest there is a mismatch between the versions inside the container. Since you're limited to the CUDA version that comes with JetPack 4.6.1, you should ensure that the versions of torch and torchvision installed in your container are compatible with this CUDA version. You might need to install specific versions of PyTorch and torchvision that work with CUDA 10.2.

Given the complexities of dealing with CUDA, PyTorch, and torchvision on Jetson Xavier within Docker, interacting with the community in the Jetson forums, where you might find others who have faced similar issues, could be beneficial. Additionally, you could consider using the setup that works outside Docker, although this might not be ideal depending on your deployment requirements.

I hope this provides you more clarity on the steps to take. Remember, the YOLO community and the Ultralytics team are here to help you as you navigate through these issues. Good luck!
