### ISSUE TITLE
ONNX converted with TRTEXEC does not implement tracking when using --INT8 argument

### ISSUE THREAD

**Issue by Liagos** [ultralytics/ultralytics#6664]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export, Other

### Bug

Hello,

1. Device:
I am currently using Triton inference server on a jetson device. The device I am using is an Xavier NX 8GB. 

2. Export ONNX:
I export the yolov8s model to onnx format with the following command.
yolo export model=yolov8s format=onnx

3. Export engine model for Triton server Inference
I export the model with the following command.
trtexec --onnx=yolov8s.onnx --int8

4, Inference with Triton
When I use the above model for tracking, althought objects are detected, the _id_ is always None and the _is_track_ is set to False in _result.boxes_. However, when I export the model with trtexec =yolov8s.onnx --int8 --fp16, then tracking is performed. I am always using the model.track in my script.

Thank you for your help in advance.

### Environment

Ultralytics version: 8.0.220
Jetson Xavier NX Developer Kit 8GB (6 CPUs)

Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Liagos hello,

Thank you for your detailed issue description. It seems you've come across an interesting behavior when exporting the YOLOv8 model with INT8 precision on a Jetson Xavier NX device and trying to use it for tracking.

Your observation where tracking IDs are not generated correctly in INT8 mode, but work fine with FP16 mode, suggests there might be a precision-related issue specifically affecting the tracking algorithm's performance or implementation.

The tracking algorithm relies on consistent detection performance, and a shift to lower precision like INT8 may be causing subtle changes in detected bounding boxes that affect tracking stability. 

For now, I recommend continuing to use the model with FP16 precision if tracking is a critical component of your application since that appears to provide satisfactory results.

In the meantime, we appreciate you bringing this to our attention; it's an important edge case that we might want to look into further. Our team will review this, and updates will be communicated through the repository's issue tracker.

If tracking is essential and INT8 optimization is crucial for your deployment due to latency or throughput requirements, consider duplicating the issue on a more controlled environment to confirm it specifically relates to precision and not other environmental factors. This could help isolate the problem for further investigation.

Please keep an eye on the repo for updates, and thank you for your contribution to improving YOLOv8!
