### ISSUE TITLE
No warning when local model not found?

### ISSUE THREAD

**Issue by je223xa** [ultralytics/ultralytics#6671]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hey there!
I am using the YOLO model for a project in my thesis, on a work laptop. Which means I am behind a proxy and a VPN connection at all times. 

The training worked fine, but upon loading I was facing weird `HTTPSConnectionPool(host='api.github.com', port=443)` problems. I just realised the reason behind this:
When i put in my local file with `YOLO("../yolo/runs/external/best.pt")`, but this path is not valid (i renamed the file to best1.pt), the model will immediately try to download its own version from the web, which it cannot do on my computer.

I am wondering why there is no exception for when the model is not found (or maybe there is and I dont get it).
I've looked in the code and in `tasks.py` I changed the `torch_safe_load` function to
```python
import os
# ...
def torch_safe_load(weight):

    """
    This function attempts to load a PyTorch model with the torch.load() function. If a ModuleNotFoundError is raised,
    it catches the error, logs a warning message, and attempts to install the missing module via the
    check_requirements() function. After installation, the function again attempts to load the model using torch.load().

    Args:
        weight (str): The file path of the PyTorch model.

    Returns:
        (dict): The loaded PyTorch model.
    """
    assert weight != "" and os.path.exists(weight), "File does not exist!"
    from ultralytics.utils.downloads import attempt_download_asset

    check_suffix(file=weight, suffix='.pt')
```
I realise is probably the worst way to fix this, but at least I now get a messagt that I submitted the wrong file instead of a cryptic SSLError. This is the full Exception:
    `HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/ultralytics/assets/releases/tags/v0.0.0 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))`

I wonder if I am using the model wrong, or if this is something you could look into? Or you've thought about it and it has some other reason that I do not know of

**Comment by glenn-jocher** [comment]
@je223xa hello!

Thank you for bringing this to our attention. The behavior you've encountered typically happens when the requested local model file cannot be found: YOLOv8 will default to attempting a download of the pre-trained weights from the internet.

It's indeed important to have clear messaging in error handling. The exception you modified in `torch_safe_load` to check if the file exists is a step in the right direction for better user experience. We appreciate your input, and I'll make sure to bring this up with the team for consideration in future updates. Our goal is always to make our models more user-friendly.

In the meantime, ensure that you provide the correct model path and file name when loading your model. Incorrect paths or filenames will trigger an attempt to download the model from the web.

For any further questions or feedback, don't hesitate to reach out. Our documentation may also provide additional guidance if needed. Thank you for contributing to the YOLOv8 community, and good luck with your thesis!
