### ISSUE TITLE
Resuming hyperparameter tuning.

### ISSUE THREAD

**Issue by finlaymorrison** [ultralytics/ultralytics#6674]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

There currently exists no way to resume from a previous hyperparameter tuning run, this is an extremely useful feature and so it should be added.

### Use case

Many compute clusters impose a time limit on jobs. This is an issue as previous training runs are used to inform the tuner of what parameters to try next, and so restarting the tuning run from the previous best parameters could be missing some useful context of other sets of parameters which worked well.

### Additional

I propose that this functionality should be added through the addition of a new argument to the tuner, namely one which is used to specify a fitness file csv generated in a previous tuning run. I propose that this argument is then used to copy the contents of the specified fitness file into the fitness file for the new tuning run.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@finlaymorrison hello! Thank you for taking the time to make this suggestion. 😊

Resuming hyperparameter tuning is indeed a valuable feature, especially considering the practical constraints encountered with compute clusters. Your idea of utilizing a previous fitness file CSV as a starting point for a new tuning run makes sense and could effectively leverage past tuning insights for future optimizations.

We appreciate your offer to help by submitting a PR, and we warmly welcome contributions from the community. However, before moving ahead with a PR, our team would need to evaluate the proposed change in terms of functionality, implementation complexity, and how it might fit into the existing design and future roadmap for YOLOv8. This process ensures that all features are consistent and maintain the quality standards of the repository.

Since you're willing to contribute, we recommend that the discussion starts in a new issue, specifically focused on this feature proposal. This way, we can gather feedback and suggestions from more contributors, which could lead to a more comprehensive design approach.

Once there's a consensus in the community, guidelines for implementation will be clearer, and you would be in an excellent position to submit a PR that aligns well with the project's goals.

Thanks again for your initiative on improving YOLOv8, and we look forward to further collaboration on this and potentially other enhancements! 🚀
