### ISSUE TITLE
when converting to tflite, we want dynamic input size support.

### ISSUE THREAD

**Issue by harufumigithub** [ultralytics/ultralytics#6675]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

onnx does has dynamic input size support.  We want to tflite to have the same dynamic input size.

### Use case

edge device inference

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@harufumigithub thank you for bringing up the idea of supporting dynamic input sizes when converting to TensorFlow Lite (TFLite) format with YOLOv8. The need for flexible input dimensions can certainly be valuable for various applications, especially when considering edge device deployment where model versatility can be crucial.

Currently, dynamic input size support is recognized in the ONNX format due to its inherent architecture, which can handle variable-sized inputs. However, TFLite generally works with fixed input sizes for optimized inference on edge devices. The conversion process from a model that supports dynamic input sizes to TFLite typically requires specifying a static input size that would be optimal for your specific use case.

Unfortunately, incorporating dynamic input size directly into TFLite is non-trivial due to these limitations of the TFLite framework itself. Still, we appreciate your suggestion, and if the TFLite community or TensorFlow team develops updates that allow for such functionality, we will definitely consider integrating this capability with YOLOv8.

For now, I would recommend deciding on the most common or useful input size that serves your edge device inference needs and using that static size when converting your YOLOv8 model to TFLite.

As always, the YOLO community and Ultralytics team value user feedback and are committed to improving our models. If you would like to explore this topic further, please refer to the Export section in our documentation and feel free to continue the discussion there. We're always looking for ways to enhance our models and support the community's needs. 😊

**Comment by DLumi** [comment]
As long as the model itself supports dynamic shapes, the input tensor in TFLite can be resized during the inference to the shapes you need.

**Comment by 921abdullah** [comment]
Have there been any improvements in dynamic input TFLite architecture?

**Comment by glenn-jocher** [comment]
Not yet; as of May 15, 2026, Ultralytics TFLite export is still documented around a fixed `imgsz` in the [TFLite export guide](https://docs.ultralytics.com/integrations/tflite), while `dynamic=True` is covered in the [export docs](https://docs.ultralytics.com/modes/export) for formats like ONNX rather than TFLite, so if dynamic TFLite input is still blocking you please open a new issue with a minimal repro and your target runtime/device for visibility.
