### ISSUE TITLE
class ConfusionMatrix, def matrix(self) is not callable

### ISSUE THREAD

**Issue by nghiaho12** [ultralytics/ultralytics#6683]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

def matrix(self) is not callable from the ConfusionMatrix class because it clashes with self.matrix.

### Environment

Ultralytics YOLOv8.0.210 🚀 Python-3.8.10 torch-2.0.0+cu117 CUDA:0 (NVIDIA RTX A4500 Laptop GPU, 16117MiB)
Setup complete ✅ (24 CPUs, 62.5 GB RAM, 307.9/465.5 GB disk)

OS                  Linux-5.15.0-89-generic-x86_64-with-glibc2.29
Environment         Linux
Python              3.8.10
Install             pip
RAM                 62.48 GB
CPU                 12th Gen Intel Core(TM) i7-12850HX
CUDA                11.7

matplotlib          ✅ 3.7.1>=3.3.0
numpy               ✅ 1.24.2>=1.22.2
opencv-python       ❌ (not installed)>=4.6.0
pillow              ✅ 9.5.0>=7.1.2
pyyaml              ✅ 5.3.1>=5.3.1
requests            ✅ 2.28.2>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.0.0>=1.8.0
torchvision         ✅ 0.15.1>=0.9.0
tqdm                ✅ 4.65.0>=4.64.0
pandas              ✅ 2.0.0>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

### Minimal Reproducible Example

```
from ultralytics.utils.metrics import ConfusionMatrix

cm = ConfusionMatrix(nc=1)
cm.matrix()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'numpy.ndarray' object is not callable

```

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@nghiaho12 hello! Thank you for reporting this issue with the `ConfusionMatrix` class in YOLOv8.

It appears you're trying to call the `matrix()` method, but there seems to be a namespace collision since `self.matrix` is also the name of an attribute storing the actual confusion matrix as a numpy array.

To fix this, you should access the confusion matrix array directly, since `self.matrix` is an array attribute of the `ConfusionMatrix` instance and not a method. If you are looking to perform an operation or retrieve the confusion matrix, please access the `matrix` attribute without calling it as a method.

However, if you are looking for a function or method to process or analyze the confusion matrix, you would want to refer to the relevant method designed for that purpose, which does not seem to be `matrix()`. Make sure that you are using the correct function to achieve your intended operation.

I'd also like to acknowledge your interest in contributing to the repository by submitting a PR. If the function you're trying to access is indeed supposed to exist and the issue is more than a simple misunderstanding, then a PR could be the right way forward.

In your PR, please consider addressing the name collision by either renaming the `self.matrix` attribute or changing the method name to something more descriptive, thus avoiding the collision. If you need any guidance on the contribution process, our documentation can assist you further.

Thank you once again for your participation in improving YOLOv8, and for being a part of the Ultralytics community! 🚀
