### ISSUE TITLE
something wrong with onnxruntime yolov8-pose

### ISSUE THREAD

**Issue by jsnoc** [ultralytics/ultralytics#6705]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I use the official example code to export the ‘’yolov8x-pose.pt‘’ like this：

from ultralytics import YOLO
model = YOLO('yolov8x-pose.pt')  
model.export(format='onnx', opset=12, imgsz=(640, 640))

and i use onnxruntime to infer one image like this：

from ultralytics import YOLO
model2 = YOLO('yolov8x-pose.onnx', task='pose')  # load a custom model
results2 = model2.predict('bus.jpg', save=True)

for compare the results  i also use the pytorch to infer the same image like this：

from ultralytics import YOLO
model1 = YOLO('yolov8x-pose.pt')  # load a custom model
results1 = model1.predict('bus.jpg', save=True)

but i got different outputs of the two infer result 

![image](https://github.com/ultralytics/ultralytics/assets/61768944/8fb4d040-42a9-4ea8-8fdf-f345067f2338)
![image](https://github.com/ultralytics/ultralytics/assets/61768944/5dc10b83-8144-4035-a507-cec8d01ba897)

and it seems that the detection results are the same， but the keypoints are different

further more  when i  check the infer value of the keypoints ，i found only the confidence are different， and  the coordinate are exactly same

![image](https://github.com/ultralytics/ultralytics/assets/61768944/f55e3d9b-a2c9-4559-b1d0-b092ecfbc3b6)
![image](https://github.com/ultralytics/ultralytics/assets/61768944/0feb1242-4700-4ea0-aad7-e1a29011dfad)

so  as far as i can see， the  different  comes from  keypoints confidence，can you help me to solve the problem？

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@jsnoc hello and thank you for bringing this issue to our attention! It appears that you are experiencing discrepancies in the keypoints confidence values when comparing the results between the PyTorch and ONNX Runtime inferences using `yolov8x-pose`. While the detection results are aligned, the confidence scores for the keypoints differ despite the coordinates being the same.

This is an interesting observation, and from what you've described, it seems that the export process to ONNX might have affected how the confidence values are being computed or represented. 🤔

Here are a few steps you could take to troubleshoot the issue:

1. Confirm whether the issue is consistent across multiple images and multiple runs, to rule out any randomness or image-specific factors.
2. Ensure that you're using the latest version of the ONNX and ONNX Runtime libraries, as updates might contain bug fixes or compatibility improvements.
3. Verify that the ONNX model's preprocessing and postprocessing steps match those used during the training and PyTorch inference.
4. Consider looking into the model's ONNX export settings in detail. Mainly, ensure that the `opset` version during export is compatible and optimal for your use case. Sometimes a different `opset` version can affect the exported model's performance. Our models are typically exported with the latest opset versions, but experimenting with others could provide insights.
5. Investigate ONNX Runtime's inference settings. Check if specific onnxruntime.SessionOptions or providers like CUDA or CPU are affecting the inference output in any way.

For further guidance and troubleshooting tips, please refer to our documentation at https://docs.ultralytics.com, particularly the export and track sections, which include detailed information on model exporting and pose estimation/kepoint tracking. These documents may offer additional insights or parameters that could be adjusted during the export or inference processes.

Please keep us posted on your findings or if you continue to encounter issues. Our aim is to ensure that the YOLOv8 models perform consistently and effectively across various platforms, and your feedback is valuable in this process.

**Comment by jsnoc** [comment]
@glenn-jocher thanks for your help，i change my onnx version from 1.12.0 to 1.15.0，and set the opset from 12 to 17，it works，so i think some kernel in posemodels badly supported by opset-12，thanks~

**Comment by glenn-jocher** [comment]
@jsnoc That’s fantastic news! I'm glad to hear that updating the ONNX version and adjusting the opset to 17 resolved the issue. It indeed seems that the support for certain operations in pose models has been improved in the latest opsets, which underscores the importance of keeping the ONNX-related libraries up to date. 😊

Thank you for updating us on your successful resolution. Should you encounter any more issues or have further questions, please don’t hesitate to reach out.

Keep enjoying your experience with YOLOv8, and don't forget to consult our comprehensive documentation at https://docs.ultralytics.com for best practices and the latest features. Happy detecting and tracking! 👍
