### ISSUE TITLE
Conversion of yolov8 to tflite 

### ISSUE THREAD

**Issue by Jacko760** [ultralytics/ultralytics#6707]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Facing difficultiy on the conversion of best.pt to .tflite 

### Additional

when i try to export best.pt into .tflite for running inference on mobile I'm getting this error , could you guys guide me go in the right path to acheive my task 
eventhough its giving tflite model and its not running properly on android studio instead it says : Label mismatch error

ONNX: starting export with onnx 1.15.0 opset 17...
ONNX: simplifying with onnxsim 0.4.35...
ONNX: export success ✅ 2.9s, saved as '/content/best.onnx' (42.6 MB)
TensorFlow SavedModel: running 'onnx2tf -i "/content/best.onnx" -o "/content/best_saved_model" -nuo --non_verbose'
TensorFlow SavedModel: export failure ❌ 28.2s: generic_type: cannot initialize type "StatusCode": an object with that name is already defined
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 448, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 310, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 261, in __call__
    f[5], keras_model = self.export_saved_model()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 122, in outer_func
    raise e
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 117, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 717, in export_saved_model
    f.unlink() if 'quant_with_int16_act.tflite' in str(f) else self._add_tflite_metadata(file)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 823, in _add_tflite_metadata
    from tflite_support import flatbuffers  # noqa
  File "/usr/local/lib/python3.10/dist-packages/tflite_support/__init__.py", line 53, in <module>
    from tflite_support import task
  File "/usr/local/lib/python3.10/dist-packages/tflite_support/task/__init__.py", line 32, in <module>
    from . import vision
  File "/usr/local/lib/python3.10/dist-packages/tflite_support/task/vision/__init__.py", line 20, in <module>
    from tensorflow_lite_support.python.task.vision import image_classifier
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_lite_support/python/task/vision/image_classifier.py", line 23, in <module>
    from tensorflow_lite_support.python.task.vision.core import tensor_image
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_lite_support/python/task/vision/core/tensor_image.py", line 19, in <module>
    from tensorflow_lite_support.python.task.vision.core.pybinds import image_utils
ImportError: generic_type: cannot initialize type "StatusCode": an object with that name is already defined

**Comment by glenn-jocher** [comment]
@Jacko760 hello! It seems like you're encountering issues converting your YOLOv8 `best.pt` model to the TensorFlow Lite (TFLite) format. This conversion process can sometimes be complex due to compatibility issues between different frameworks.

Based on the error message provided, it looks like the issue arises during the TensorFlow SavedModel step, where there might be a naming conflict ("generic_type: cannot initialize type 'StatusCode'"). This could potentially be due to version conflicts or issues with the onnx2tf conversion tool.

The label mismatch error on Android suggests that after conversion, the label names used in the model might not be aligned with what your application expects. It's important to ensure that the labels in your model definition match the labels used in your Android application for inference.

For a successful conversion and deployment, I'd recommend verifying the following steps:
1. Make sure your environment is set up with compatible versions of the necessary frameworks and conversion tools.
2. Carefully execute the exporting steps, ensuring that the SavedModel format is obtained correctly before attempting the conversion to TFLite.
3. Validate the TFLite model using a TFLite interpreter to check if the model runs correctly before deploying to Android.
4. Align the labels and model outputs between the TFLite model and the Android application, ensuring no mismatch.

Please refer to the [Export](https://docs.ultralytics.com/modes/export) mode in our documentation for updated and detailed instructions on exporting models to different formats. Ensure all steps are followed precisely for TensorFlow export.

Unfortunately, without being able to provide direct code examples or troubleshoot specific software versions, these are the general pieces of advice I can offer. If issues persist, consider revisiting the model conversion steps and checking for any updates or known issues on the conversion tools' repositories.

Additionally, feel free to post a new issue in our GitHub repository if you believe the problem might be with YOLOv8's export functionality itself. The community or our team members might be able to provide further insights. Good luck with your conversion efforts! 🚀

**Comment by Jacko760** [comment]
@glenn-jocher Thanks for your detail response as I was referring to the export documentation , I found some arguments when exporting to tflite model , I’m also attaching the same below in picture 
Those arguments given in the image are initialised by default or do we need to include those arguments explicitly . 
also according the output tensor of TensorFlow lite they expect 4 output tensor [but](https://tensorflow.google.cn/lite/inference_with_metadata/task_library/object_detector) the tool model conversion is concatenatinating all the output details at once and giving shape as (1,22,8400) which gives error in android as well 
So could you please guide me in the righetst way Caz i was assigned with this task since a week but no progress till date 
I’m very confused right Caz if we train using tensorflowlite maker on custom dataset and try to  deploy in android it’s working fine 
I jus wanted to know how to convert the Holi PyTorch model into a proper tflite for integration into android you can reach me out through the given mail 
Mail : insaafsulaimaan@gmail.com
![IMG_8395](https://github.com/ultralytics/ultralytics/assets/88931164/cbb1130e-04e5-447f-9b06-c110b56562ee)

**Comment by glenn-jocher** [comment]
@Jacko760, I understand your concerns about the exporting arguments and the difference in output tensor shapes for TensorFlow Lite. The conversion process from a PyTorch model to TFLite can indeed be complex and might require additional steps to ensure compatibility with the expected outputs and inputs on the Android platform.

Regarding the arguments for exporting to TFLite, you should check the documentation or the command-line help to see if these arguments need to be explicitly set or if they have default values. The process typically includes specifying the input and output nodes and may need additional arguments related to quantization or optimization for mobile deployment.

The issue with the mismatched output tensor shape (1,22,8400) indicates that the model outputs may be concatenated in a way that is incompatible with the TensorFlow Lite interpreter used in Android. The TensorFlow Lite Object Detector expects certain tensor shapes, as mentioned in the documentation you've referred to.

To address this, you could potentially:
1. Modify the export processing script to create multiple outputs, ensuring that they conform to TensorFlow Lite's expected output format.
2. Use a post-processing step after inference within your Android application to divide and interpret the concatenated outputs correctly.

While it is best practice to use official TensorFlow Lite conversion tools for this, it is essential to know that due to the complexities involved in model architectures and outputs, additional customization and manual adjustment might be necessary.

Unfortunately, I can't offer you personal email support or dive deeper into code examples. However, I encourage you to revisit our [Export](https://docs.ultralytics.com/modes/export) documentation and ensure that you are following all guidelines. If feasible, you could also consider reaching out to a developer experienced in model conversion or engage with the community through GitHub for more tailored support.

The goal is to ensure parity between what your trained YOLOv8 model outputs and what is expected by the TFLite Object Detector API you intend to use in your Android app. Keep investigating, stay resilient, and reach out to the community when you hit bumps along the way. Remember, complex tasks like these often require continuous learning and problem-solving. Good luck! 🌟

**Comment by Jacko760** [comment]
Thank you for your response.

**Comment by Raysantos22** [comment]
Ultralytics YOLOv8.1.9 🚀 Python-3.10.12 torch-2.1.0+cu121 CPU (Intel Xeon 2.20GHz)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

PyTorch: starting from 'yolov8n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)
2024-02-04 05:57:07.046729: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-04 05:57:07.046790: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-04 05:57:07.046852: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

TensorFlow SavedModel: starting export with tensorflow 2.14.0...
WARNING ⚠️ tensorflow<=2.13.1 is required, but tensorflow==2.14.0 is currently installed https://github.com/ultralytics/ultralytics/issues/5161
Downloading https://github.com/ultralytics/assets/releases/download/v8.1.0/calibration_image_sample_data_20x128x128x3_float32.npy.zip to 'calibration_image_sample_data_20x128x128x3_float32.npy.zip'...
100% 1.11M/1.11M [00:00<00:00, 34.1MB/s]
Unzipping calibration_image_sample_data_20x128x128x3_float32.npy.zip to /content/calibration_image_sample_data_20x128x128x3_float32.npy...: 100% 1/1 [00:00<00:00, 51.14file/s]

ONNX: starting export with onnx 1.14.0 opset 17...
ONNX: simplifying with onnxsim 0.4.35...
ONNX: export success ✅ 1.8s, saved as 'yolov8n.onnx' (12.3 MB)
TensorFlow SavedModel: running 'onnx2tf -i "yolov8n.onnx" -o "yolov8n_saved_model" -nuo --non_verbose'
TensorFlow SavedModel: export failure ❌ 19.2s: generic_type: cannot initialize type "StatusCode": an object with that name is already defined
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 568, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 538, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 284, in __call__
    f[5], keras_model = self.export_saved_model()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 136, in outer_func
    raise e
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 131, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 783, in export_saved_model
    f.unlink() if "quant_with_int16_act.tflite" in str(f) else self._add_tflite_metadata(file)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 894, in _add_tflite_metadata
    from tflite_support import flatbuffers  # noqa
  File "/usr/local/lib/python3.10/dist-packages/tflite_support/__init__.py", line 53, in <module>
    from tflite_support import task
  File "/usr/local/lib/python3.10/dist-packages/tflite_support/task/__init__.py", line 32, in <module>
    from . import vision
  File "/usr/local/lib/python3.10/dist-packages/tflite_support/task/vision/__init__.py", line 20, in <module>
    from tensorflow_lite_support.python.task.vision import image_classifier
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_lite_support/python/task/vision/image_classifier.py", line 23, in <module>
    from tensorflow_lite_support.python.task.vision.core import tensor_image
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_lite_support/python/task/vision/core/tensor_image.py", line 19, in <module>
    from tensorflow_lite_support.python.task.vision.core.pybinds import image_utils
ImportError: generic_type: cannot initialize type "StatusCode": an object with that name is already defined

yolo v8 cant convert tflite !yolo export model=yolov8n.pt format=tflite how to fix this

**Comment by glenn-jocher** [comment]
@Raysantos22 it appears you're encountering a compatibility issue with TensorFlow version 2.14.0 during the export process. The warning indicates that TensorFlow version 2.13.1 or lower is required for successful export to TensorFlow SavedModel format. Additionally, the error messages suggest there might be conflicts with CUDA plugins and issues with the TensorFlow Lite support package.

To resolve this, please downgrade TensorFlow to version 2.13.1 or lower and ensure that your environment is correctly set up with compatible versions of CUDA and cuDNN if you're using GPU acceleration. Also, verify that there are no conflicting installations of TensorFlow or TensorFlow Lite support packages.

For the TensorFlow Lite conversion, follow the steps outlined in our [Export](https://docs.ultralytics.com/modes/export) documentation, ensuring that all prerequisites are met and the environment is correctly configured. If the problem persists, consider opening an issue on our GitHub repository for further assistance.

**Comment by BahodirML** [comment]
Hello @glenn-jocher 

I am having a problem while using tflite model with tensorflow. I have trained model with yolov8s and tested, it is working well. then I hev converted it to tflite model  using the code below:

```
import sys
sys.path.append('/home/hbvision/mirsaid/AI_shelf_detection')

from ultralytics import YOLO

# Load the YOLO11 model
model = YOLO("yolov8x_best.pt")  

# # Export the model to TFLite format
model.export(format="tflite", int8=True, data='data/filtered_data/data.yaml')
```

Then I have tested the tflite model whethere it is working well or not, it performed well as I expected, I used the code below:
```
from ultralytics import YOLO

# Load a model
model = YOLO("/est_float32.tflite")  # load an official model


# Validate the model
metrics = model.val(data =data.yaml')  # no arguments needed, dataset and settings remembered
print(metrics.box.map ) # map50-95
# metrics.box.map50  # map50
# metrics.box.map75  # map75
# metrics.box.maps  # a list contains map50-95 of each category
```



Then, I tried to use the model with tensroflow as below code:
```
import tensorflow as tf
import cv2
import numpy as np

# Load the TFLite model
interpreter = tf.lite.Interpreter(model_path='best_float16.tflite')
interpreter.allocate_tensors()

# Get input and output details
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Preprocess the image
image_path = 'JPEG-408E-98D6-66-13.jpeg'
image = cv2.imread(image_path)
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
image_resized = cv2.resize(image_rgb, (640, 640))
input_data = np.expand_dims(image_resized / 255.0, axis=0).astype(np.float32)  


# Set the input tensor
interpreter.set_tensor(input_details[0]['index'], input_data)

# Run inference
interpreter.invoke()

# Get the output
output_data = interpreter.get_tensor(output_details[0]['index'])

# Debugging: Inspect output shape and data
print("Output Shape:", output_data.shape)

# Process grid-based detections
# Process grid-based detections
detections = output_data[0]  # Remove the batch dimension
boxes = []
print(detections.shape)

print("Inspecting detections...")

for grid_cell in detections.T:  # Transpose to iterate over each detection
    x_center, y_center, width, height, confidence, *class_probs = grid_cell
    class_id = np.argmax(class_probs)  # Get the class with the highest probability
    class_score = class_probs[class_id]  # Get the score of the top class

    # Debugging: Print raw values
    # print(f"Confidence: {confidence}, Class ID: {class_id}, Class Score: {class_score}")

    # Apply reduced thresholds for debugging
    if confidence > 0.1 and class_score > 0.5:
        # Convert from center format to corner format
        x_min = (x_center - width / 2) * image.shape[1]
        y_min = (y_center - height / 2) * image.shape[0]
        x_max = (x_center + width / 2) * image.shape[1]
        y_max = (y_center + height / 2) * image.shape[0]

        # Append to the list of boxes
        boxes.append({
            "class_id": int(class_id),
            "confidence": float(confidence),
            "class_score": float(class_score),
            "box": [x_min, y_min, x_max, y_max],
        })

# Print results
if boxes:
    for box in boxes:
        print(f"Class ID: {box['class_id']}, Confidence: {box['confidence']:.2f}, Class Score: {box['class_score']:.2f}, Box: {box['box']}")
else:
    print("No detections passed the thresholds.")
```


Even though the model performed well when I loaded it using ultralytics, it gave output with no detections when I used tensorflow, the output is as below:

```
(myenv) bahodir@server:~/Bahodir/AI_shelf_detection$ python3 /home/bahodir/Bahodir/AI_shelf_detection/tests/test_tf.py
2025-01-29 00:06:25.510858: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-01-29 00:06:25.517506: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1738109185.525107 1266813 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1738109185.527470 1266813 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-01-29 00:06:25.535490: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Output Shape: (1, 8, 8400)
(8, 8400)
Inspecting detections...
Confidence: 1.007888113235822e-05, Class ID: 1, Class Score: 2.515625601517968e-05
Confidence: 1.4366039977176115e-05, Class ID: 1, Class Score: 2.1366682631196454e-05
Confidence: 1.950939440575894e-05, Class ID: 1, Class Score: 2.1310537704266608e-05
Confidence: 3.366340388311073e-05, Class ID: 0, Class Score: 3.0378969313460402e-05
Confidence: 4.113556133233942e-05, Class ID: 0, Class Score: 5.990351928630844e-05
No detections passed the thresholds.
(myenv) bahodir@server:~/Bahodir/AI_shelf_detection$ 
```

Can you explain where the isssue is and give a suggestions to solve my problem, thank you!
