### ISSUE TITLE
plot()   error：UnicodeEncodeError: 'latin-1' codec can't encode character '\u4eba'

### ISSUE THREAD

**Issue by lonngxiang** [ultralytics/ultralytics#6722]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

results[0].plot(conf=False)    
![image](https://github.com/ultralytics/ultralytics/assets/40717349/710127ca-fb62-4466-9409-4dfbba4bc9cd)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by lonngxiang** [comment]
> @lonngxiang hello! It seems like you've encountered a Unicode encoding issue while trying to plot your results. This error typically occurs when there's a character in your data or labels that is not supported by the 'latin-1' encoding standard.
> 
> YOLOv8 uses UTF-8 encoding by default, which supports a wide range of characters, including those common in various languages. The character '\u4eba', which is causing the issue, is likely part of your dataset labels or annotations and should be supported under UTF-8.
> 
> Please ensure that your system and environment are correctly configured for UTF-8 encoding. If you're working with files that include labels or annotations, check that they are saved with UTF-8 encoding as well.
> 
> If the problem persists, it might be an issue with the locale settings on your machine or within your Python environment. You can specify UTF-8 in your Python scripts by setting the environment variable or including it in your code where you read or write files. Furthermore, if you're running scripts from the command line, ensure your terminal also supports UTF-8.
> 
> Since you've indicated a willingness to submit a PR, we would welcome your contribution. If you've found a fix for this issue, please feel free to open a pull request with a comprehensive description of the problem and your solution. We appreciate the support from community members like you.
> 
> For further guidance on contributing, please refer to the documentation on how to contribute code or fixes to the Ultralytics Docs.
> 
> Good luck, and thank you for your participation in the YOLO community! 🚀

yes, i fixed. just download a ttf font: https://ultralytics.com/assets/Arial.Unicode.ttf

for windows:  save Arial.Unicode.ttf to dir:C:\Users\loong\AppData\Roaming\Ultralytics
for linux:  save Arial.Unicode.ttf to dir:/root/.config/Ultralytics/Arial.Unicode.ttf

**Comment by glenn-jocher** [comment]
Great to hear that you were able to resolve the issue, @lonngxiang! Your solution of using a Unicode-compatible font like Arial Unicode is a smart approach when dealing with character encoding issues in plots. This ensures that all special characters in your labels are displayed correctly.

Your contribution is valuable, and this information could certainly help others who might face a similar issue. If you think that this solution could be beneficial to the community, you are welcome to update the documentation with details of this workaround so that future users can implement it easily.

Remember, the strength of open source projects like YOLOv8 relies on the collaborative efforts of contributors like yourself. Thanks for sharing your findings! 👍
