### ISSUE TITLE
How to use Instance Segmentation with SAHI?

### ISSUE THREAD

**Issue by stphtan94117** [ultralytics/ultralytics#6771]
This is my code to detect images.

```
import os
import cv2
import shutil
from sahi.utils.yolov8 import download_yolov8s_model
from sahi import AutoDetectionModel
from sahi.utils.cv import read_image
from sahi.utils.file import download_from_url
from sahi.predict import get_prediction, get_sliced_prediction, predict

# Set input and output directories
input_dir = "33"  # Images folder directory
output_dir = "demo_data"

# Download YOLOv8 model
yolov8_model_path = "yolov8m-seg.pt"
download_yolov8s_model(yolov8_model_path)

# Load the auto-detection model
detection_model = AutoDetectionModel.from_pretrained(
    model_type='yolov8',
    model_path=yolov8_model_path,
    confidence_threshold=0.3,
    device="cuda:0",  # or 'cpu'
)

# Iterate through image files in the input directory
for i in os.listdir(input_dir):
    # Read the image
    image = cv2.imread(f"{input_dir}/{i}")[:, :, ::-1]

    # Ensure the output directory exists
    os.makedirs(output_dir, exist_ok=True)

    # Get sliced predictions
    result = get_sliced_prediction(
        image,
        detection_model,
        slice_height=256,
        slice_width=256,
        overlap_height_ratio=0.2,
        overlap_width_ratio=0.2,
        postprocess_class_agnostic=True
    )

    # Export visualization results
    result.export_visuals(export_dir=output_dir, hide_labels=False, hide_conf=True)

    # Get the object prediction list
    object_prediction_list = result.object_prediction_list
    print(object_prediction_list)

    # Move the predicted visualization file to the output directory
    shutil.move(f"{output_dir}/prediction_visual.png", f"{output_dir}/{i}")

```

![1](https://github.com/ultralytics/ultralytics/assets/110151053/601f2f3c-0100-426f-9e72-61f67e1894df)

I loaded yolov8m-seg.pt , but did not see segment mask polygon, only displayed bbox in picture.

how to fix it and show  Instance Segmentation Mask (not just bbox)

thanks

**Comment by glenn-jocher** [comment]
@stphtan94117 hello! It seems like you're on the right track using the `yolov8m-seg.pt` model for instance segmentation. However, to visualize the segmentation masks instead of just the bounding boxes, you should make sure the SAHI library you're using supports the segmentation output generated by YOLOv8. 

Our YOLOv8 model provides segmentation masks which can be utilized for visualizing the segmented areas, but you need to access the masks from the model output and apply them to the image. You can refer to our Ultralytics Docs for more details on handling segmentation outputs with our YOLOv8 models.

Make sure your version of the SAHI library can handle and display these masks. If SAHI's `get_sliced_prediction` and `export_visuals` functions currently do not support segmentation masks, you may need to customize the visualization part of your script to extract and display segmentation masks from the predictions.

Keep in mind that interacting with the model outputs and customizing the visualization for segmentation masks can be intricate, so ensure all dependencies and library versions are compatible and up to date with our latest YOLOv8 implementations. Check out our documentation for guidance on handling different tasks and model outputs to better tailor the SAHI functions or your custom scripts for segmentation tasks.

For direct support with SAHI and integrating it with Ultralytics models for segmentation, consider reaching out to the maintainers of SAHI as they'll provide the best guidance on their library capabilities and updates. Good luck with your instance segmentation work! 😊👍

**Comment by olivierdecitre** [comment]
Hey g'day, have you figured out in the end how to use SAHI with instance segmentation and have the mask appear? 

Also would you know how to export the mask labels? 

Cheers, 
Olivier

**Comment by glenn-jocher** [comment]
@olivierdecitre hello Olivier,

G'day! 😊 It looks like you're interested in using SAHI with YOLOv8 for instance segmentation and exporting mask labels. Let's address both points:

### Displaying Instance Segmentation Masks
To ensure that the segmentation masks appear in your results, make sure you're using the correct functions and parameters in SAHI. Here's an updated version of your code that should help visualize the segmentation masks:

```python
import os
import cv2
import shutil
from sahi.utils.yolov8 import download_yolov8s_model
from sahi import AutoDetectionModel
from sahi.utils.cv import read_image
from sahi.utils.file import download_from_url
from sahi.predict import get_prediction, get_sliced_prediction, predict

# Set input and output directories
input_dir = "33"  # Images folder directory
output_dir = "demo_data"

# Download YOLOv8 model
yolov8_model_path = "yolov8m-seg.pt"
download_yolov8s_model(yolov8_model_path)

# Load the auto-detection model
detection_model = AutoDetectionModel.from_pretrained(
    model_type='yolov8',
    model_path=yolov8_model_path,
    confidence_threshold=0.3,
    device="cuda:0",  # or 'cpu'
)

# Iterate through image files in the input directory
for i in os.listdir(input_dir):
    # Read the image
    image = cv2.imread(f"{input_dir}/{i}")[:, :, ::-1]

    # Ensure the output directory exists
    os.makedirs(output_dir, exist_ok=True)

    # Get sliced predictions
    result = get_sliced_prediction(
        image,
        detection_model,
        slice_height=256,
        slice_width=256,
        overlap_height_ratio=0.2,
        overlap_width_ratio=0.2,
        postprocess_class_agnostic=True
    )

    # Export visualization results with masks
    result.export_visuals(export_dir=output_dir, hide_labels=False, hide_conf=True, show_masks=True)

    # Get the object prediction list
    object_prediction_list = result.object_prediction_list
    print(object_prediction_list)

    # Move the predicted visualization file to the output directory
    shutil.move(f"{output_dir}/prediction_visual.png", f"{output_dir}/{i}")
```

### Exporting Mask Labels
To export the mask labels, you can convert the `PredictionResult` object into various annotation formats. Here's an example of how to export to COCO format:

```python
# Access the object prediction list
object_prediction_list = result.object_prediction_list

# Convert to COCO annotations and save to a file
coco_annotations = result.to_coco_annotations()
with open(f"{output_dir}/coco_annotations.json", "w") as f:
    json.dump(coco_annotations, f)
```

### Additional Resources
For more detailed guidance, you can refer to our documentation on [SAHI Tiled Inference](https://docs.ultralytics.com/guides/sahi-tiled-inference/).

If you encounter any issues, please ensure you're using the latest versions of the packages. If the problem persists, providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example) will help us assist you better.

Cheers and happy coding! 🚀

**Comment by olivierdecitre** [comment]
Hi Glenn, 

Thank you for your response, I'm trying to run a custom segmentation model I trained on colab, I have the weights file and I'm trying to tile it on a large orthomosaic. When I tried your code it seems like the 'show_mask" argument doesn't exist.  (see error below). 

    result.export_visuals(export_dir=output_dir, hide_labels=False, hide_conf=True, show_masks=True)
TypeError: export_visuals() got an unexpected keyword argument 'show_masks'

This is my code so far: 

import os
import cv2
import shutil
from sahi import AutoDetectionModel
from sahi.utils.cv import read_image
from sahi.utils.file import download_from_url
from sahi.predict import get_prediction, get_sliced_prediction, predict

# Set input and output directories
input_dir = r"xxx\ortho.tif"  # Images folder directory
output_dir = r"xxx\demo_data"

# Download YOLOv8 model
yolov8_model_path = r"xxx\seg.pt"


# Load the auto-detection model
detection_model = AutoDetectionModel.from_pretrained(
    model_type='yolov8',
    model_path=yolov8_model_path,
    confidence_threshold=0.3,
    device="cuda:0",  # or 'cpu'
)


    # Get sliced predictions
result = get_sliced_prediction(
    input_dir,
    detection_model,
    slice_height=832,
    slice_width=832,
    overlap_height_ratio=0.2,
    overlap_width_ratio=0.2,
    postprocess_class_agnostic=True
)

    # Export visualization results with masks
result.export_visuals(export_dir=output_dir, hide_labels=False, hide_conf=True, show_masks=True)

    # Get the object prediction list
object_prediction_list = result.object_prediction_list
print(object_prediction_list)

Please let me know how I could fix this. 

Also the model was trained in colab, here are the commands I ran:

!yolo train model=yolov8n-seg.pt data=/content/data.yaml epochs=300 batch=8 imgsz=832

finished with: 

Validating runs/segment/train/weights/best.pt...
Ultralytics YOLOv8.2.45 🚀 Python-3.10.12 torch-2.3.0+cu121 CUDA:0 (NVIDIA L4, 22700MiB)
YOLOv8n-seg summary (fused): 195 layers, 3258454 parameters, 0 gradients, 12.0 GFLOPs
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% 4/4 [00:02<00:00,  1.51it/s]
                   all         54        204      0.736      0.681      0.739      0.608       0.74      0.684      0.741      0.601
                  hard         38         86      0.738      0.744      0.771      0.628      0.726      0.733      0.753      0.612
                  soft         40        118      0.734      0.619      0.707      0.588      0.754      0.636       0.73      0.591
Speed: 0.9ms preprocess, 6.0ms inference, 0.0ms loss, 4.8ms postprocess per image
Results saved to runs/segment/train
💡 Learn more at https://docs.ultralytics.com/modes/train

**Comment by glenn-jocher** [comment]
Hi Olivier,

Thank you for sharing the details of your issue. It looks like you're encountering an error due to the `show_masks` argument not being recognized by the `export_visuals` function. Let's address this step-by-step.

### Issue with `export_visuals`
The `export_visuals` function in SAHI might not support the `show_masks` argument. Instead, you can visualize the masks by directly accessing the mask data from the prediction results and overlaying them on the image. Here's how you can modify your code to achieve this:

```python
import os
import cv2
import shutil
from sahi import AutoDetectionModel
from sahi.utils.cv import read_image
from sahi.utils.file import download_from_url
from sahi.predict import get_prediction, get_sliced_prediction, predict

# Set input and output directories
input_dir = r"xxx\ortho.tif"  # Images folder directory
output_dir = r"xxx\demo_data"

# Load the auto-detection model
detection_model = AutoDetectionModel.from_pretrained(
    model_type='yolov8',
    model_path=yolov8_model_path,
    confidence_threshold=0.3,
    device="cuda:0",  # or 'cpu'
)

# Get sliced predictions
result = get_sliced_prediction(
    input_dir,
    detection_model,
    slice_height=832,
    slice_width=832,
    overlap_height_ratio=0.2,
    overlap_width_ratio=0.2,
    postprocess_class_agnostic=True
)

# Export visualization results without the show_masks argument
result.export_visuals(export_dir=output_dir, hide_labels=False, hide_conf=True)

# Get the object prediction list
object_prediction_list = result.object_prediction_list
print(object_prediction_list)

# Visualize masks manually
for object_prediction in object_prediction_list:
    mask = object_prediction.mask
    if mask is not None:
        mask = mask.bool().cpu().numpy()
        image = cv2.imread(f"{input_dir}/{i}")
        image[mask] = [0, 255, 0]  # Overlay mask with green color
        cv2.imwrite(f"{output_dir}/{i}", image)

# Move the predicted visualization file to the output directory
shutil.move(f"{output_dir}/prediction_visual.png", f"{output_dir}/{i}")
```

### Exporting Mask Labels
To export the mask labels, you can convert the `PredictionResult` object into various annotation formats. Here's an example of how to export to COCO format:

```python
import json

# Access the object prediction list
object_prediction_list = result.object_prediction_list

# Convert to COCO annotations and save to a file
coco_annotations = result.to_coco_annotations()
with open(f"{output_dir}/coco_annotations.json", "w") as f:
    json.dump(coco_annotations, f)
```

### Verify Package Versions
Please ensure you are using the latest versions of the SAHI and Ultralytics packages. You can update them using:
```bash
pip install -U ultralytics sahi
```

If the issue persists, providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example) will help us assist you better.

I hope this helps! If you have any further questions, feel free to ask. 😊
