### ISSUE TITLE
How did  you define obb format in YOLOv8-OBB

### ISSUE THREAD

**Issue by kuazhangxiaoai** [ultralytics/ultralytics#6776]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In YOLOv8-OBB, the rotated bounding box(OBB) is defined as (cx, cy, w, h, angle). Is angle arange (0, 180)? The w and h is defined as longside and shortside repectively? The w is always bigger than h? I am confused about xywhr of YOLOv8-OBB.

Thanks for your answers.

**Comment by glenn-jocher** [comment]
@kuazhangxiaoai hello! In YOLOv8-OBB, the ROTATED bounding box (OBB) is indeed defined by the parameters (cx, cy, w, h, angle), where:

- `cx, cy` are the center coordinates of the bounding box.
- `w` is the width of the box, which is the length of the longer side.
- `h` is the height of the box, which refers to the shorter side.
- `angle` defines the rotation of the box around its center.

With respect to the angle, it should be in the range of [0, 180) degrees, as this range sufficiently defines all possible rotations for a rectangle (rotating beyond 180 degrees would only retrace rotations already represented within the first 180 degrees due to the symmetry of rectangles).

The condition `w >= h` helps to maintain a consistent definition where `w` is always regarded as the longer side of the bounding box. This ensures uniformity and helps to avoid ambiguity during model training and inference.

For more details on how these attributes map to our architecture and how they are managed during training and prediction, please refer to the detailed documentation, which outlines the nuances of working with OBB in YOLOv8.

I hope this clears up the confusion! 👍 If you have further questions, don't hesitate to reach out.

**Comment by kuazhangxiaoai** [comment]
@glenn-jocher Thanks for your answers. but there are the rotated bounding box with format (lt,rb,angle) in RotatedBboxLoss of loss.py. why is the rbox with format (lt, rb, angle) there, instead of the rbox with(x, y, w, h ,angle)?

**Comment by glenn-jocher** [comment]
@kuazhangxiaoai, the (lt, rb, angle) format you're seeing in the `RotatedBboxLoss` section of `loss.py` is a part of an intermediate calculation. This rotated bounding box representation with (left-top, right-bottom, angle) is used internally for certain geometric computations that may benefit from this format.

For the model's output and external representation, we stick with the (x, y, w, h, angle) format, which is more standardized and intuitive for external interfacing and applications. The internal use of different representations is a common practice to simplify certain calculations and to optimize the computation of loss functions. 🔄

Always feel welcome to ask if you need more clarification!
