### ISSUE TITLE
What are the evaluation indicators of key points？

### ISSUE THREAD

**Issue by Honeybadger-LSX** [ultralytics/ultralytics#6802]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

What are the evaluation indicators of key points？IoU? I can't find that.

**Comment by glenn-jocher** [comment]
@Honeybadger-LSX hello! 👋 For keypoint or pose estimation tasks in YOLOv8, we typically evaluate the performance using metrics other than IoU, which is more suited for object detection tasks. For keypoints, common evaluation indicators include the Percentage of Correct Keypoints (PCK), Mean Per Joint Position Error (MPJPE), and Object Keypoints Similarity (OKS). These metrics focus on the accuracy of localized keypoints and pose estimation rather than bounding boxes. For more in-depth details on these evaluation metrics, the "Pose/Keypoint Estimation" section of our documentation at https://docs.ultralytics.com/tasks/pose could provide you with additional insights. 😊

**Comment by Honeybadger-LSX** [comment]
邮件已收到，会尽快回复，祝安！
