### ISSUE TITLE
yolo: command not found

### ISSUE THREAD

**Issue by hariouat** [ultralytics/ultralytics#6817]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I installed the Ultralytics but still have the yolo command not found. 

%pip install ultralytics
import ultralytics
ultralytics.checks()

Ultralytics YOLOv8.0.222 🚀 Python-3.10.12 torch-1.12.0+cu113 CUDA:0 (NVIDIA A100-SXM4-80GB, 81100MiB)
Setup complete ✅ (192 CPUs, 503.0 GB RAM, 383.5/808.7 GB disk)

!yolo task=classify mode=train cache=True model=yolov8n-cls.pt

/bin/bash: line 1: yolo: command not found

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@hariouat hello! It seems like there's a bit of confusion with how to use YOLOv8 after installation. After installing the Ultralytics package via pip, you should use it within Python rather than as a standalone terminal command. The `!yolo` command you are trying appears to be intended for a Command Line Interface (CLI), but YOLOv8 interactions should take place in Python scripts or notebooks.

Instead of using `!yolo`, you should be invoking YOLOv8 functionality through the available Python methods, as documented in the Ultralytics Docs.

For example, to start training using the Python code, you would initialize your model and call the `train()` method directly in your Python environment, passing appropriate arguments such as task, data, and model configurations.

Please refer to the [Train documentation](https://docs.ultralytics.com/modes/train) for a detailed guide on how to train your model using Python with YOLOv8. 📘 Happy coding!

**Comment by glenn-jocher** [comment]
Hello @hariouat, the `!yolo` command isn't valid in Python. Instead, you should use the Python API provided by YOLOv8. For example, to train a model, create a Python script using the appropriate functions from our package. Check out our [Train documentation](https://docs.ultralytics.com/modes/train) to guide you through this process. If you're running on a Jupyter notebook, prefixing with `!` is for shell commands, not for Python code. Ensure you're using proper Python syntax in your scripts or notebooks.🐍📘
