### ISSUE TITLE
model.val causes error when data argument is pathlib.Path an not str 

### ISSUE THREAD

**Issue by gfx73** [ultralytics/ultralytics#6848]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Val

### Bug

Hi. 

The error basically comes from explicit type check of ```data``` arg. It took a lot of time for me to figure out what was the source of the problem. It is even harder to figure out why the error happens because model.train is perfectly good with pathlib. 

Also even if Path object is not supposed to be passed to ```val``` the error message is confusing. 

Thank you for your attention.

![image](https://github.com/ultralytics/ultralytics/assets/65644911/c4cca7f5-1301-4ea9-b8f9-042608e4e961)

### Environment

Ultralytics YOLOv8.0.223 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (NVIDIA A40, 45413MiB)
Setup complete ✅ (96 CPUs, 1007.2 GB RAM, 45.3/218.5 GB disk)

### Minimal Reproducible Example

To reproduce just launch model validation with ```data``` arg created using pathlib. 

### Additional

The error comes from this [line](https://github.com/ultralytics/ultralytics/blob/d74a5a9499acf1afd13d970645e5b1cfcadf4a8f/ultralytics/engine/validator.py#L138)

I seems it is easy to fix the error, but I don't have any experience in creating PRs. So just take into account this bug.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@gfx73 hello!

Thank you for bringing this issue to our attention. 🙏 We appreciate the time you spent investigating the cause.

I understand that encountering an error with `model.val` due to a type check on the `data` argument not accepting a `pathlib.Path` object can be frustrating, especially since `model.train` handles it smoothly. We aim for consistency and user-friendliness in our API, so your feedback is important.

We recognize the error message could be clearer, and indeed, supporting `pathlib.Path` across all methods would enhance the user experience. I will relay this to our development team 👨‍💻 to consider for future updates. Your suggestion for improving `model.val` to accept `Path` objects as it does in `model.train` makes sense.

If you encounter any more issues or have further suggestions, please don't hesitate to share. Meanwhile, please make sure to use a string type for the `data` argument as a temporary solution.

Happy coding, and thank you for supporting YOLOv8! 🚀

**Comment by glenn-jocher** [comment]
@gfx73 should be fixed in #6864
