### ISSUE TITLE
 Inconsistent Output Behavior with save_frames Setting in Model Prediction

### ISSUE THREAD

**Issue by hamedgorji** [ultralytics/ultralytics#6883]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

I am experiencing an issue with the` save_frames` setting in the model's prediction method. The problem arises when toggling the save_frames flag between True and False.

With save_frames=True: The model behaves as expected, saving both frames and videos correctly.
With save_frames=False: The model does not generate the frames as expected, which is correct. However, it also fails to save the video properly. The output is an AVI file, but its size is only about 20-30 KB, which suggests that the video content is not being saved correctly.
`results = model.predict(source='Data2/', imgsz=640, save=True, show_labels=True, show_conf=False, iou=0.3, conf=0.5, save_frames=False)`

Thanks

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@hamedgorji hello! Thank you for your detailed report regarding the behavior of the `save_frames` flag in the predict mode of YOLOv8. Your description highlights an important issue: while setting `save_frames` to `True` works as intended, setting it to `False` appears to disrupt the proper saving of your output video.

This certainly sounds like inconsistent behavior that needs attention. To further investigate and address this, I suggest reviewing our documentation on the [Predict](https://docs.ultralytics.com/modes/predict) mode to ensure the usage aligns with the expected behavior.

In parallel, it would be helpful if you could log this as an issue on the YOLOv8 repo issues page, providing the environment details that you're running on and any additional context that might be relevant to reproducing the issue. That information will allow our team and contributors to replicate and diagnose the problem more effectively.

Please know the YOLO community and the Ultralytics team are dedicated to improving the model's robustness and performance, and your contribution by flagging this issue is very valuable. 🛠️🤝

Thank you for your support and patience as we work to resolve this. Keep an eye on the issue thread for updates and potential fixes!

**Comment by glenn-jocher** [comment]
@hamedgorji fixed in latest release. Please update your ultralytics package.

**Comment by hamedgorji** [comment]
@glenn-jocher Thanks for the quick solution.

**Comment by glenn-jocher** [comment]
@hamedgorji you're welcome! Happy to help. If you encounter any further issues or have questions, feel free to reach out. 😊 Enjoy using YOLOv8!
