### ISSUE TITLE
Implement yolov8 in Flutter for real-time segmentation

### ISSUE THREAD

**Issue by rodrygo-c-garcia** [ultralytics/ultralytics#6890]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have the yolov8l-seg model trained with my own dataset of more than 80000 images, I exported my model to tflite format, I want to implement this model for real time segmentation from a Flutter app, which Flutter dependency allows me to do this implementation?

**Comment by glenn-jocher** [comment]
@rodrygo-c-garcia to implement real-time segmentation in your Flutter app with the YOLOv8 model exported as a TFLite format, you should look into Flutter packages that support TensorFlow Lite. Typically, you can consider using the `tflite_flutter` plugin which provides a way to run TensorFlow Lite models within a Flutter environment.

Since specifics can change, I'd recommend checking the latest Flutter plugins that are compatible with TensorFlow Lite to ensure you're using one that supports the operation set required by our YOLOv8 segmentation model.

During implementation, keep in mind that real-time performance can be affected by the device's capabilities and the optimization level of your tflite model. For any further assistance, the package's documentation or community can be a great resource.

Best of luck with your Flutter app development for real-time segmentation! 😊🚀

**Comment by glenn-jocher** [comment]
Congrats on successful implementation, @rodrygo-c-garcia-garcia! 🎉 To further optimize the YOLOv8 model in Flutter:

1. Experiment with quantization - converting the model to a lower precision such as INT8 can reduce size and speed up inference, potentially at the cost of some accuracy.
2. Opt for a smaller model variant - if you're using a larger YOLOv8 model, explore if smaller variants provide a satisfactory trade-off between speed and accuracy for your case.
3. Profile and analyze - Use profiling tools to understand which parts of the model or app are bottlenecks, then target those areas for optimization.
4. Optimize input - Reduce input image size reasonably to speed up processing, and if feasible, limit the frame rate of the video input.
5. Leverage GPU acceleration - Ensure that your TFLite model is running on the GPU if supported by the plugin and device.

I hope this helps enhance the performance of your app! Keep pushing the boundaries! 💪🚀

**Comment by rodrygo-c-garcia** [comment]
Thank you very much for your help @glenn-jocher

**Comment by glenn-jocher** [comment]
You're welcome, @rodrygo-c-garcia-garcia-garcia! If you have any more questions down the road, feel free to reach out. Happy coding! 😊👍

**Comment by PrinandaRahmatullah** [comment]
@rodrygo-c-garcia Hi, Rodrygo! How is the implementation? Is it going smoother? I will implement the object detection and pose estimation in Flutter mobile app. So, wanted to hear latest info from you? 
Thank you!

**Comment by Ankurneural** [comment]
@rodrygo-c-garcia @glenn-jocher 
I have been trying to run tflite model using tflite_flutter but in vain. The documentation is not up to the mark and a lot of ambiguous steps while creating the .dll file and requiring (.h)s files to be required etc etc.
After 2 days of debugging and trying to set-up the build correctly, I COULDNOT use tflite_flutter.

1. Are you aware of better documentation/tutorial/working example of tflite_flutter on WINDOWS. I would really appreciate it.
2. Any recommendations for dependencies to run Yolov8 model on WINDOWS flutter app other than tflite_flutter?

flutter_vision works only for Android and IOS

**Comment by glenn-jocher** [comment]
@Ankurneural hi there! I'm sorry to hear you're facing issues with `tflite_flutter`. It can indeed be challenging to set up, especially on Windows. While I don't have a specific tutorial for `tflite_flutter` on Windows, you might want to check out the [TensorFlow Lite example](https://www.tensorflow.org/lite/guide/inference#load_and_run_a_model_in_flutter) which provides a general guide that could help.

As for running YOLOv8 on a Windows Flutter app, you might consider using platform channels to integrate a native Windows TensorFlow Lite inference engine with your Flutter code. This way, you can bypass some of the complexities of `tflite_flutter` on Windows.

Here's a quick snippet on how you might set up a platform channel:

```dart
import 'package:flutter/services.dart';

class TensorFlowLite {
  static const MethodChannel _channel = MethodChannel('tensorflow_lite');

  static Future<String> runModelOnImage(String imagePath) async {
    final String result = await _channel.invokeMethod('runModelOnImage', {'imagePath': imagePath});
    return result;
  }
}
```

And on the native side, you'd implement the `runModelOnImage` method to perform the inference using TensorFlow Lite's C++ API.

I hope this helps, and best of luck with your project! If you need more detailed guidance, feel free to ask.

**Comment by lougau92** [comment]
> @rodrygo-c-garcia @glenn-jocher I have been trying to run tflite model using tflite_flutter but in vain. The documentation is not up to the mark and a lot of ambiguous steps while creating the .dll file and requiring (.h)s files to be required etc etc. After 2 days of debugging and trying to set-up the build correctly, I COULDNOT use tflite_flutter.
> 
> 1. Are you aware of better documentation/tutorial/working example of tflite_flutter on WINDOWS. I would really appreciate it.
> 2. Any recommendations for dependencies to run Yolov8 model on WINDOWS flutter app other than tflite_flutter?
> 
> flutter_vision works only for Android and IOS

Dear @Ankurneural, 

I manage to work with tflite_flutter :)! I used the provided example [here](https://github.com/tensorflow/flutter-tflite/tree/main/example/object_detection_ssd_mobilenet_v2). 

in object_detection.dart, set your model and labels path
```dart
class ObjectDetection {
  static const String _modelPath = 'assets/model-xxx.tflite';
  //custom_ssd_mobilenet_v2_fpn_lite_320x320.tflite
  static const String _labelPath = 'assets/labels-xxx.txt';
``` 

Then set the model's input image size here:
```dart
    final imageInput = img.copyResize(
      image!,
      width: xxx,
      height: xxx,
    );
````

Then scale the image pixel values between 0-1:
```dart
    // add this for loops
    for (var i = 0; i < imageMatrix.length; i++) {
      for (var j = 0; j < imageMatrix[i].length; j++) {
        for (var k = 0; k < imageMatrix[i][j].length; k++) {
          imageMatrix[i][j][k] = imageMatrix[i][j][k] / 255.0;
        }
      }
    }
```

You are then good to apply the model 🚀 
```dart
 final output = _runInference(imageMatrix);
```

The last steps are to format the yolo output, which is in shape [batch_n , 4 + num_classes, 8400] for yolo detection I believe. The four dimensions are X_center, Y_center, Width, Height.
- It is handy to convert the X_c,Y_c,H,W format to X1,X2,Y1,Y2
- You then need to apply non-maximum suppression on those output based on a IoU threshold.
- Last but not least, scale the X1,X2,Y1,Y2 coordinates by the image size.

And you are good to display the bounding boxes:
```dart
    img.drawRect(
            imageInput,
            x1:boxes_x1[i].toInt(),
            y1:boxes_x21[i].toInt(),
            x2:boxes_y1[i].toInt(),
            y2:boxes_y2[i].toInt(),
            color: img.ColorRgb8(0, 255, 0),
            thickness: 3,
        );
```

Cheers,

**Comment by glenn-jocher** [comment]
Hey @lougau92,

I totally get the frustration with setting up `tflite_flutter` on Windows, it can be quite the challenge 😅. Unfortunately, the documentation for `tflite_flutter` on Windows is indeed a bit sparse. However, I've found that the TensorFlow Lite [example](https://github.com/tensorflow/flutter-tflite/tree/main/example/object_detection_ssd_mobilenet_v2) can be quite helpful as a starting point, even though it's not Windows-specific.

For running YOLOv8 models on a Windows Flutter app, another approach could be using platform channels to integrate with a native TensorFlow Lite inference engine. This way, you can bypass some of the complexities and limitations of `tflite_flutter` on Windows.

I wish I had a more straightforward solution for you, but I hope this helps a bit! Keep pushing through, and don't hesitate to reach out if you hit more roadblocks. Good luck! 🍀

**Comment by glenn-jocher** [comment]
@Ankurneural hey there! 🎉 I'm thrilled to hear you've made progress with the cmake build for the tflite model. It's those little details like the cmake argument that can really make a difference, isn't it?

Regarding your question on converting the image from the `image_picker` to a tensor input for YOLOv8, you're right; the format needs to be compatible. Here's a quick way to convert the image to a format suitable for inference:

1. First, convert the picked image to a `Uint8List`:
   ```dart
   final pickedFile = await _picker.pickImage(source: source, maxWidth: maxWidth, maxHeight: maxHeight, imageQuality: quality);
   final bytes = await pickedFile.readAsBytes();
   ```

2. Then, you can use the `Image` package to convert this byte data into an image object and further process it as needed before feeding it into the model:
   ```dart
   import 'package:image/image.dart' as img;

   img.Image? image = img.decodeImage(bytes);
   // Resize or process the image as needed here
   ```

3. Finally, convert your image to the required format (e.g., a Float32List if your model expects float inputs) and pass it to the `interpreter.run()` method.

Regarding the Dart compatibility of the loop you mentioned, it looks perfectly fine in Dart for normalizing the image data. And yes, `_runInference` seems like a locally defined method where you'd typically handle the preprocessing of your input image to match the model's input shape and type, run the model inference, and possibly post-process the model output.

I hope this helps clear things up a bit! Keep experimenting, and don't hesitate to reach out if you have more questions. Happy coding! 🚀

**Comment by Ankurneural** [comment]
@glenn-jocher I totally agree. In hindsight, I ended up learning some cmake configurations and commands with some motivation and a lot of frustration :)

4. I converted my input in Step 2 to tensor.
```
final inputTensor = TensorImage(inputType);
inputTensor.loadImage(img!);
```

5. and ran my inference
```
final outputBuffer = TensorBuffer.createFixedSize(_outputShape, outputType,);
_interpreter.run(inputTensor.buffer, outputBuffer.buffer);
```

It ran error-free but the output shape is difficult to interpret.

After running:
```
final _inputShape = _interpreter.getInputTensor(0).shape;
final _outputShape = _interpreter.getOutputTensor(0).shape;

debugPrint('Input shape: $_inputShape');
debugPrint('Output shape: $_outputShape');
```
My debug console output:
flutter: Input shape: [1, 640, 640, 3]
flutter: Output shape: [1, 5, 8400]

My input shape corresponds to size of batch 1, 640*640 size image with 3 color channels.
I cannot comprehend the Output shape.

I used Yolov8s as my base model with custom training for one class.

**Comment by glenn-jocher** [comment]
@Ankurneural hey there! 😄 It's great to hear you've made progress and even picked up some cmake skills along the way!

Regarding the output shape `[1, 5, 8400]` you're seeing, it's typical for YOLO models. Here's a quick breakdown:

- **1**: Batch size (you're running inference on one image at a time).
- **5**: Each of the 8400 vectors represents a potential detection, and the "5" corresponds to the attributes of each detection (4 for the bounding box coordinates and 1 for the objectness score).
- **8400**: The total number of anchor boxes (potential detections) the model is evaluating. This number comes from the grid size the image is divided into and the number of anchor boxes per grid cell.

For YOLOv8 models, especially with custom training, interpreting these outputs involves:
1. Reshaping or processing the output to extract the bounding box coordinates and confidence scores.
2. Applying a threshold to filter out low-confidence detections.
3. Using Non-Maximum Suppression (NMS) to merge overlapping boxes for the same object.

Here's a simplified example of how you might start processing this output:
```dart
// Assuming outputBuffer.buffer contains your model's output
var detections = processDetections(outputBuffer.buffer, confidenceThreshold: 0.5);
detections.forEach((detection) {
  debugPrint('Detection: $detection');
});
```
Remember, the exact processing will depend on your model's specifics and the format of its output. Keep up the great work, and feel free to reach out if you have more questions! 🚀

**Comment by Ankurneural** [comment]
@glenn-jocher Thank you for the consistent help and support.
I am still confused with the output shape and its interpretation.

My output is generated using the below code:
```
final outputBuffer = TensorBuffer.createFixedSize(_outputShape, outputType,);
_interpreter.run(inputTensor.buffer, outputBuffer.buffer);
```

While inspecting outputBuffer object, the shape is [1, 5, 8400] and has buffer and byteData as sub-objects. When I am accessing the data using:

```
final out = outputBuffer.getDoubleList();
```
I get a flatout list of length 42000 (1*5*8400). Can I directly reshape flatout list of 42000 to (5*8400) representing coordinates and confidence score of 8400 potential detections.
If the first four indexes corresponds to the bounding box coordinates, then it must be normalized because every value < 1. Is there a simpler way to get the coordinates w.r.t image dimensions. So, I am not able to comprehend those values as well.

- Is it possible to share the processDetections method definition?
- Why 8400 detections? 
If I understand correctly, The grid size and anchor boxes is model dependent. For my yolov8n model, it will always be 8400 detections no matter the image size. Kindly correct if I am wrong.

**Comment by glenn-jocher** [comment]
@Ankurneural hey there! 😊 It's great to see you diving deep into the details of your model's output. Let's clarify a bit!

Indeed, the output shape `[1, 5, 8400]` you're seeing is typical for YOLO models, where you have a large number of potential detections (8400 in this case), each described by 5 values (4 for bounding box coordinates in normalized form and 1 for the confidence score).

To reshape and interpret this flat list of 42000 values, you're on the right track! You can indeed reshape it to `[5, 8400]` for easier processing. The coordinates are normalized, so to convert them back to the original image dimensions, you'd multiply by the image's width and height.

Here's a quick pseudo-code snippet for the `processDetections` method you asked about:
```dart
List<Detection> processDetections(Float32List detections, double threshold) {
  List<Detection> results = [];
  for (int i = 0; i < detections.length / 5; i++) {
    double confidence = detections[i * 5 + 4];
    if (confidence > threshold) {
      // Convert normalized coordinates to actual by multiplying with image dimensions
      double x = detections[i * 5] * imageWidth;
      double y = detections[i * 5 + 1] * imageHeight;
      double w = detections[i * 5 + 2] * imageWidth;
      double h = detections[i * 5 + 3] * imageHeight;
      results.add(Detection(x, y, w, h, confidence));
    }
  }
  return results;
}
```
Regarding the 8400 detections, you're correct that it's model-dependent, tied to the grid size and the number of anchor boxes used during training. No matter the input image size, your YOLOv8n model is designed to evaluate this fixed number of potential detections.

Hope this helps clear things up! Keep exploring, and don't hesitate to reach out if you have more questions. Happy coding! 🚀

**Comment by Ankurneural** [comment]
@glenn-jocher Hey :) Thank you for helping me out. it definitely helped me to dig deeper and understand the complexities of the flutter and Yolo architectures.


-  Reshaping the Output

```
final detections = out;
var threshold = 0.7;
const width = 640;
const height = 640;

List results = [];
for (int i = 0; i < detections.length / 5; i++) {
  double confidence = detections[i * 5 + 4];
  if (confidence > threshold) {
    var x = detections[i * 5] * width;
    var y = detections[i * 5 + 1] * height;
    var w = detections[i * 5 + 2] * width;
    var h = detections[i * 5 + 3] * height;
    results.add([x, y, w, h, confidence]);
  }
}
```

- Converting from X_center, Y_center, Width, Height to Xmin, Ymin, Xmax, Ymax 
and sorting the results w.r.t model confidence

```
for(var result in results) {
  result[0] = result[0] - result[2]/2;
  result[1] = result[1] - result[3]/2;
  result[2] = result[0] + result[2]/2;
  result[3] = result[1] + result[3]/2;
}

List FinalDetections = [];
results.sort((a, b) => a[4].compareTo(b[4]));
results = results.reversed.toList();
```

- Applying Non-Maximum Suppresion

```
while (results.isNotEmpty){
  List overlap = [];
  var box_top = results.removeAt(0);
  double boxx = box_top[0];
  double boxy = box_top[1];
  double boxw = box_top[2];
  double boxh = box_top[3];
  double box_conf = box_top[4];

  FinalDetections.add([boxx, boxy, boxw, boxh, box_conf]);

  for (var (idx, result) in results.indexed){
    double min_1 = min(boxw, result[2] as double);
    double max_1 = max(boxx, result[0] as double);

    double min_2 = min(boxh, result[3] as double);
    double max_2 = max(boxy, result[1] as double);

    double intersection = max(0, min_1 - max_1) * max(0, min_2 - max_2);
    double union = (boxw - boxx) * (boxh - boxy) + (result[2] - result[0]) * (result[3] - result[1])- intersection;
    double iou = intersection / union ;

    if (iou > 0.50){
      overlap.add(idx);
    }
  }
  overlap.sort((a, b) => b.compareTo(a));
  for(int i in overlap){
    results.removeAt(i);
  }
```

I got multiple detections, and none of them are correct 
![image](https://github.com/ultralytics/ultralytics/assets/47255085/b3bc94b9-1131-46de-9f7e-576a3c7747fd)

I maybe messing up with my input.
If possible, Can you kindly explain if it is necessary to normalize the pixel values before the model inference step, If yes, Why?


Also, apologies in advance if I am going off topic.
My Original Image is 640*640 color "jpg" image.
I am using Image package in flutter.

- Reading File
```
final XFile? pickedFile = await _picker.pickImage(source: source,);
```

- Reading as Bytes(Uint8List)
```
final imageBytes = await pickedFile.readAsBytes();
```
The size of imageBytes is 22710, which is not interpretable, I am assuming the image got compressed during saving/reading in the background.

- Decoding Image(Uint32List)
```
image.Image? img = image.decodeImage(imageBytes);
```
The decoded file has 640 height and 640 width, same as original, mentions channels as rgb and has data length of 409600 items, which is 640*640. with data values with much higher pixel values(4286014035, 4285424723).

I cannot understand why the img length is 640*640 not 640*640*3 and why the values are so high?

- Image to Tensor Image
```
final inputTensor = TensorImage(inputType);
inputTensor.loadImage(img!);
```
inputTensor has 4915200 items and 4915200 LengthInBytes, I am assuming it comes from 640*640*3*4, since each pixel is represented by 4 bytes.

I am mainly confused if I have to add a preprocessing pipeline to the images, before the model inference step. Do I need to do processing at Bytes level? Every Image format is a flatlist rather than a tensor(height*width*3). Am I missing some inbuilt methods that can help me step up the image format and values right?



- Inference
```
final outputBuffer = TensorBuffer.createFixedSize(_outputShape, outputType,);
_interpreter.run(inputTensor.buffer, outputBuffer.buffer);
final out = outputBuffer.getDoubleList();
```

Apologies again for the lenghty post and off-topic discussions.

Thank you again in advance for the suggestions, discussion and your time.

**Comment by extras28** [comment]
@Ankurneural i have the same issue to you, i think the problem is the input, i am using yolov8l with custom data. the shape of input is [1,3,640,640] but the lib tflite_flutter have the input's shape is [1,640,640,3] so the output does not correct. But when i try to format the input to [1,3,640,640] my app throw error 
![image](https://github.com/ultralytics/ultralytics/assets/102603589/ee8500ee-c465-4e4d-8c29-33fcd2afa195)

**Comment by Ankurneural** [comment]
@extras28 Hey, I believe your reshaping is wrong.

After loading the intepreter from the asset, you can check the input shape by
```
final _interpreter = await Interpreter.fromAsset('models/best_float32.tflite');
_interpreter.allocateTensors();
final _inputShape = _interpreter.getInputTensor(0).shape;
```

You can reshape your input to match your inputShape
Flatlist = flatpixelshape

For me, 
width = 3
height, depth = 640, 640 #for my case
```
List<List<List<double>>> resultList = List.generate(depth, (i) => List.generate(height, (j) =>
                                                       List.generate(width, (k) => double.parse(flatList[i * height * width + j * width + k].toStringAsFixed(5)))));
```

**Comment by extras28** [comment]
@Ankurneural yeah i know that, but the shape of input tensor is [1,640,640,3], but the model best_float32.tflite receive the input with shape [1,3,640,640] so when i try reshape the input to [1,640,640,3] there are no correct result

**Comment by Ankurneural** [comment]
@extras28 I am not sure I follow.
The expected input shape: [1, 640, 640, 3].
The image captured(Flatlist) can be reshaped similar to 640*640*3.
You can verify the pixel values if they are in the right format and type.
You would receive error with any shape other than expected.


In my opinion, The mismatch comes from the wrong implementation either of the preprocessing or postprocessing steps, that happen automatically in the python implementation. 

Preprocessing steps I follow:
1. Resize -> normalize(0-1)
Postprocessing:
1. Reshape(1, 5, 8400) -> filter(confidence > .70) -> Non-Max Suppressions.

If you get successful in your implementation with expected results, kindly let me know if I am misunderstood any part of the implementation.

**Comment by glenn-jocher** [comment]
@malikabdullahnaazar hey there! 😊 It sounds like you've been through quite the journey trying to integrate YOLOv8 into your Flutter project. Flutter's ecosystem for ML model integration, especially for complex models like YOLOv8, can indeed be a bit challenging, but you're heading in the right direction!

Since you've experimented with several packages already, I'd recommend focusing on the TFLite Flutter package for its direct support and efficiency. Here are a couple of suggestions:

1. 📄 **Ensure model compatibility:** Double-check the TFLite model used is correctly exported and optimized for mobile deployment.

2. 🔄 **Correct Input/Output Handling:** TFLite models often expect input in a specific shape. Make sure your input tensor shape is aligned with what the YOLOv8 TFLite model expects: `[1, height, width, 3]` for images. For the output, understanding and correctly processing the tensor output shape is crucial for correct interpretations.

Here's a quick snippet to set you on the right path:
```dart
// Assuming you've loaded your TFLite model correctly
TensorBuffer inputBuffer = TensorImage.fromFile(yourImageFile);
// Proceed with preprocessing as per model requirements
// e.g., resizing, normalizing

// Run inference
_interpreter.run(inputBuffer.buffer, outputBuffer.getBuffer());
// Interpret your outputBuffer accordingly
```
Keep in mind, processing the output can be tricky; it often involves decoding bounding boxes, classes, and confidence scores.

3. 🧪 **Experiment Incrementally:** Start with a simple integration to just load and run the model with a static image. Ensure this works and produces expected output before integrating real-time camera feeds or other complex inputs.

Remember, dealing with model inputs and outputs requires careful attention to detail, given the flat structure and the layering of information in the output tensors. Always refer to your model's specific output format when decoding your predictions.

Lastly, don't forget to leverage the wealth of community knowledge! If you hit a specific snag, detailed error messages or code snippets are incredibly helpful for pinpointing the issue. Keep pushing forward, and you'll get there! 😄

**Comment by glenn-jocher** [comment]
@malikabdullahnaazar Hey there! 😊 It looks like the issue stems from a mismatch between the expected output shape of your model and what you've defined in your Flutter application. Your model is producing an output shape of `[1, 73, 2100]`, but your code expects `[1, 84, 8400]`. This discrepancy can cause the error you're seeing.

To resolve this, you'll need to adjust your Flutter application to correctly handle the output shape that your model produces. Here's a quick tweak you can try:
1. Update the output shape in your Flutter code to match the model's actual output shape. This involves changing the `TensorBuffer.createFixedSize()` call (or similar) to expect the correct shape `[1, 73, 2100]`.

```dart
final outputBuffer = TensorBuffer.createFixedSize([1, 73, 2100], TfLiteType.float32);
```

2. Ensure that any post-processing logic (e.g., decoding the predictions) is appropriately adapted to handle this output shape correctly.

Adjusting these parts should align your code with the model's output, potentially solving the issue. Hope this helps get you back on track! Good luck with your project evaluation next week – rooting for you! 🚀

**Comment by Rizwanali324** [comment]
@glenn-jocher @rodrygo-c-garcia 
how can i display the segmentation mask instead of just bb. 
can you share simple code with both bb and segmentation  display

**Comment by Rizwanali324** [comment]
@glenn-jocher its really hard to implent it as flutter give me alot of error i stuck there do you have any custom app which just need to use custom for segmenation . realy needs @glenn-jocher

**Comment by glenn-jocher** [comment]
@Rizwanali324 I understand the frustration with Flutter implementation - it can definitely be challenging! While I don't have a ready-made custom app to share, I'd suggest considering a few alternatives that might be easier to get started with:

1. **Start simpler**: Try implementing basic object detection first before moving to segmentation, as it has fewer post-processing complexities.

2. **Platform-specific approach**: Consider using native Android development with TensorFlow Lite Java/Kotlin APIs, which often have better documentation and examples for YOLO models.

3. **Hybrid solution**: You could create a simple HTTP API service running your YOLOv8 model in Python and call it from your Flutter app for prototyping.

The Flutter + TFLite + YOLOv8 segmentation combination does require significant debugging of tensor shapes and mask processing as you've seen in this thread. If you're under time constraints, one of the alternative approaches might get you to a working solution faster.
