### ISSUE TITLE
Issue with Triton Inference Server - YOLOv8 TensorRT Model

### ISSUE THREAD

**Issue by qwertyz15** [ultralytics/ultralytics#6910]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

Issue Description:
I have successfully converted the YOLOv8 model (yolov8n.pt) to TensorRT format using CUDA version 11.7, cuDNN version 8.9.6, and TensorRT version 8.4.2.4. However, when I try to deploy this TensorRT model on Triton Inference Server (version 22.08), my environment is ubuntu 20.04 LTS, and I encounter an issue.

Previous Success with YOLOv5:
It's worth noting that I have previously deployed a YOLOv5 TensorRT model on the same Triton Inference Server without any issues.

Problem Details:

Triton Inference Server Version: 22.08
CUDA Version: 11.7
cuDNN Version: 8.9.2
TensorRT Version: 8.4.2.4
Model Configuration (yolov8-trt.pbtxt):
```
name: "yolov8-trt"
platform: "tensorrt_plan"
max_batch_size: 0
input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [1, 3, 640, 640]
  }
]
output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [1, 84, 8400]
  }
]
instance_group [
  {
    kind: KIND_GPU,
    count: 1
  }
]
```
Error Message:
```E1211 05:23:10.073874 1 logging.cc:43] 1: [stdArchiveReader.cpp::StdArchiveReader::30] Error Code 1: Serialization (Serialization assertion magicTagRead == kMAGIC_TAG failed.Magic tag does not match)
E1211 05:23:10.079321 1 logging.cc:43] 4: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)
```

![Screenshot from 2023-12-11 11-32-13](https://github.com/ultralytics/ultralytics/assets/44846872/d7242035-a0cb-49df-b5ae-b678398e4589)
![Screenshot from 2023-12-11 11-32-51](https://github.com/ultralytics/ultralytics/assets/44846872/20eeea69-d459-4e12-a911-148ad1231415)

### Environment

Ultralytics YOLOv8.0.156 🚀 Python-3.8.10 torch-1.13.0+cu117 CUDA:0 (NVIDIA GeForce RTX 3060, 12052MiB)
Setup complete ✅ (12 CPUs, 31.3 GB RAM, 257.4/365.6 GB disk)

### Minimal Reproducible Example

**Steps to Reproduce:**

- Convert YOLOv8 model to TensorRT format.
- Create a Triton model repository with the provided yolov8-trt.pbtxt.
- Deploy the model using Triton Inference Server.
- Observe the encountered error.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@qwertyz15 hello! Thank you for the detailed issue report. The error you're encountering suggests there's a problem with the deserialization of the TensorRT engine file within Triton. This may sometimes be caused by a version mismatch or an issue with the serialization process itself.

As you've previously succeeded with YOLOv5, let’s try the following steps to troubleshoot your YOLOv8 deployment with Triton:
1. Ensure the TensorRT engine file for YOLOv8 was generated in the same environment where Triton is running, as differences in the CUDA or TensorRT versions can cause deserialization issues.
2. Verify that the generated TensorRT engine is not corrupted and is fully compatible with the TensorRT version used by Triton Inference Server.
3. Cross-check the configuration specified in `yolov8-trt.pbtxt` against the actual output shape and datatype expected by the YOLOv8 TensorRT engine.

For specific guidance on exporting YOLOv8 models to various formats, our Export mode documentation at https://docs.ultralytics.com/modes/export may also be helpful for ensuring the process is being followed correctly. If issues persist after the steps above, consider raising a discussion on our GitHub repo for deeper community and team support. 🤝

**Comment by qwertyz15** [comment]
The generated TensorRT(yolov8) was generated in the same environment where the Triton is running. The TensorRT(yolov5) was also generated in that same environment. The generated TensorRT(yolov8) works perfectly in local machine. `yolov8-trt.pbtxt` file is also fine as well.
By the way, I solved the issue
First I converted the `yolov8n.pt` to `yolov8n.onnx` by this command
`yolo export model='yolov8n.pt' format=onnx simplify=True opset=12 imgsz=224`
and then I convert this `onnx` to engine by this 
`trtexec --onnx=best.onnx --saveEngine=best.engine --workspace=3000`
After that I deployed it to triton server with the same `.pbtxt`, thats works fine.

**Comment by glenn-jocher** [comment]
@qwertyz15, fantastic to hear you resolved the issue! 👍 

Your successful approach highlights a key troubleshooting step when working with serialized models for different inference engines: when direct conversion encounters issues, using ONNX as an intermediate format can provide better compatibility. This two-step process, from `.pt` to `.onnx`, then from `.onnx` to `.engine`, can often resolve serialization and compatibility complexities.

Should anything else arise or if you have further insights to share from your experience, contributions are always welcome to help enhance the docs and tools for the YOLOv8 community. Happy detecting! 😊

**Comment by glenn-jocher** [comment]
@pbouill hey there! 🎉 Glad to hear you got it working on Triton with that approach! Indeed, once you have the `.engine` file, deploying to Triton is pretty straightforward. No need for renaming – you can directly use the `.engine` file in your Triton model repository. Just make sure your `model_repository` directory and `.pbtxt` file are correctly set up to reference the `.engine` file accurately. If everything's in place, Triton should pick up the model without a hitch. Happy inferencing! 😊

**Comment by MiqdaadIndori** [comment]
@qwertyz15 

> First I converted the yolov8n.pt to yolov8n.onnx by this command
> yolo export model='yolov8n.pt' format=onnx simplify=True opset=12 imgsz=224
> and then I convert this onnx to engine by this
> trtexec --onnx=best.onnx --saveEngine=best.engine --workspace=3000
> After that I deployed it to triton server with the same .pbtxt, thats works fine.

your approach has multiple issues and is only a workaround. 
with your approach we do not get dynamic batching. which we get when generating the TensorRT directly.
