### ISSUE TITLE
mask visualization

### ISSUE THREAD

**Issue by JasonZou13** [ultralytics/ultralytics#6936]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I trained my segmentation model  based on my roboflow dataset and the image segmentation prediction result is pretty accurate(14 results including 2 classes), but when carrying out mask visualization, those  classes cannot be distinguished by different colors, and the output results of the codes:

unique_arr = np.unique(mask)
print(unique_arr)"

are only [0 1].

So how to solve this problem?

**Comment by glenn-jocher** [comment]
@JasonZou13 hello 👋,

Thank you for reaching out! In your segmentation task, you're observing color differences where the classes are not visually distinct. This often occurs because the default colormap may not provide sufficient contrast between classes, especially if the array's unique values are limited, as in your case `[0 1]`.

One option is to manually assign distinct colors to each class before visualization. Even though I can't provide code examples, think about implementing a custom color map or using existing color palettes that can provide a wider range and contrast of colors.

Please also ensure your mask generation process aligns with your visualization technique. Lastly, don't hesitate to refer to our [Segmentation Task Documentation](https://docs.ultralytics.com/tasks/segment) to fine-tune your approach.

**Comment by JasonZou13** [comment]
Thanks for your answering. But recently I have been struggling about the mask visualization of mutiple segmentation classes(based on yolov8 model), do you have any suggestions about this（quite urgent）？

**Comment by glenn-jocher** [comment]
Hi @JasonZou13,

To handle multiple segmentation class visualizations, consider adapting your color mapping to ensure each class is assigned a unique and distinguishable color. This way, when visualizing the segmentation mask, each class can be clearly differentiated. Check our [Segmentation Task Documentation](https://docs.ultralytics.com/tasks/segment) for guidelines on handling segmentation tasks and improving visualization. 🎨✨
