### ISSUE TITLE
Visibility flag

### ISSUE THREAD

**Issue by navidTerraNova** [ultralytics/ultralytics#6945]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is there a difference between training Yolo-pose models on data set with visibility flag set to **(0, 1, 2)** and using it only for visible and not visible **(0, 2)**?. because I want to annotate my data and since some keypoints are occluded or some body parts are not visible I have to annotate them with visibility flag set to 1.
Generally Does visibility flag set to 1 make a difference in calculation of OKS loss?

**Comment by glenn-jocher** [comment]
@navidTerraNova hi there! 👋

The visibility flag plays a crucial role when training models with keypoint detection capabilities like YOLO-pose. When you use visibility flags (0, 1, 2), you're providing the model with extra information:

- 0 indicates not visible and not labeled
- 1 indicates not visible but labeled
- 2 indicates visible and labeled

Having a flag for occluded keypoints (set to 1) can help the model learn the structure and expected positions of keypoints, even when they're not visible. This can potentially improve the model's ability to predict keypoints for occluded objects.

In terms of the OKS (Object Keypoint Similarity) loss, the visibility flag informs how the loss is calculated for each keypoint. A visibility flag of 1 means that while the keypoint is not visible, it still influences the loss calculation, as it's considered during training.

This additional information can guide the model to better understand the context and predict poses more accurately in real-world scenarios where occlusion is common.

Remember, effective annotation with accurate visibility flags is key to getting the most out of YOLO-pose training. For more details on pose estimation task specifics, refer to our pose documentation. Cheers! 😊

**Comment by navidTerraNova** [comment]
@glenn-jocher 
Thank you for this explanation, It was clear, but can you just explain a little more about the calculation of OKS in terms of visibility flag equal to 1 or 2 and how can it change the OKS? 

![Screenshot from 2023-12-13 10-39-50](https://github.com/ultralytics/ultralytics/assets/115950927/84fb6efd-3d86-4d4f-875a-0ef267063b2b)

And one other question is that if the visibility flag is equal to 0 (The model hasn't detected the keypoint) and there is no OKS loss for the keypoint then does it mean if the model doesn't detect some of the key points then it doesn't change the OKS loss? (to be more clear if the model detects only for example 6 keypoints out of 17 keypoints, Does the OKS differ from another model which detects 15 keypoints out of 17 with exact loss for the 5 keypoints in common?)

**Comment by glenn-jocher** [comment]
@navidTerraNova sure, I’ll clarify briefly. The OKS computation considers the visibility flag: for visible keypoints (flag 2), detected keypoints contribute fully to the loss, guiding the model's predictions to match ground truth. For occluded keypoints (flag 1), they still influence the loss, but the model is trained to infer their position even though they're unseen, which is crucial for consistency in pose estimation across varied scenarios.

Regarding your second question, if a visibility flag is set to 0, these keypoints do not contribute to the loss at all because they are neither visible nor labeled – they are basically ignored. Therefore, a model that detects more keypoints, assuming similar accuracy on the common keypoints, should have a different (typically higher) OKS because the additional detected keypoints would contribute to the overall similarity measurement. The more keypoints detected correctly, the better the OKS, which reflects both the quantity and the quality of the pose estimation.

I hope this helps! For an in-depth look at how OKS is influenced by keypoint detection, be sure to check out the pose documentation.

**Comment by medmabcf** [comment]
[glenn-jocher](https://github.com/glenn-jocher) thank you, that was very helpful. But when the position of the points is not clear because of the low quality of the image, should we set the visibility to 1? Can that be helpful?

**Comment by glenn-jocher** [comment]
@medmabcf Glad you found the explanation helpful! 😊 Yes, setting the visibility flag to 1 in cases where the quality of the image makes the position of keypoints unclear can indeed be helpful. This tells the model that a keypoint exists at this position, but it's not visibly detectable due to occlusion or image quality, guiding the model to learn from the context of the surrounding keypoints. It's a practical approach for training robust models capable of inferring occluded or unclearly visible keypoints. Keep up the great work with your annotations! 👍

**Comment by hariouat** [comment]
Hello, 
I'm trying to train ketpoint detection with YOLOV8. 
When the runing start, i just see only two point on the image, not others points. 

This is my image and the corresponding annotations. 

0 0.19762191450933173 0.5899203728879394 0.34166164960866946 0.22431540104874736 0.5520770620108368 0.9021169159060012 1 0.39102950030102346 0.7224703825985628 1
0 0.37296809151113786 0.45542823849291125 0.27694160144491264 0.36123519129928144 0.5520770620108368 0.9021169159060012 1 0.39102950030102346 0.7224703825985628 1
0 0.6152919927754366 0.4714507671392504 0.31607465382299826 0.2981161390561274 0.5520770620108368 0.9021169159060012 1 0.39102950030102346 0.7224703825985628 1
0 0.6672185430463576 0.6457564575645757 0.4981938591210114 0.16702272285880748 0.5520770620108368 0.9021169159060012 1 0.39102950030102346 0.7224703825985628 1
0 0.475316074653823 0.8113225869100796 0.24382901866345574 0.20295202952029512 0.5520770620108368 0.9021169159060012 1 0.39102950030102346 0.7224703825985628 1

![train_batch2](https://github.com/ultralytics/ultralytics/assets/117453280/619970e2-3005-4b31-af1d-286f4174afc6)

**Comment by glenn-jocher** [comment]
Hello,

It looks like you're encountering an issue where only two keypoints are visible during training. This could be due to several factors:

1. **Annotation Format**: Ensure your annotations are correctly formatted and aligned with YOLOv8 expectations. Each keypoint should be correctly labeled and visible in the image.
2. **Visibility Flags**: Check if the visibility flags for your keypoints are set correctly. If keypoints are occluded or not visible but still labeled, they should have a visibility flag of 1.
3. **Model Configuration**: Verify that your model configuration is set to detect the number of keypoints you have annotated. If the model is configured for fewer keypoints, it might not display all of them.

If the keypoints are correctly annotated and visible in the image but still not showing up, it might be helpful to look into the training logs for any warnings or errors that could give more insight into what might be going wrong.

Keep us posted on your progress!

**Comment by hariouat** [comment]
Hello, 
<img width="666" alt="image" src="https://github.com/ultralytics/ultralytics/assets/117453280/6cc67b48-5d50-4212-abac-1181d99e5665">


Thank you for your quick response.

Actually, I am unable to find the error. I have provided an example of my annotation which corresponds to each object in my image. I have thoroughly checked that my file matches the YOLO annotations.

Here is my YAML file.

**Comment by hariouat** [comment]
I found the error, thanks a lot

**Comment by glenn-jocher** [comment]
Great to hear that you found the error! If you have any more questions or need further assistance as you continue with your project, feel free to reach out. Happy coding! 😊
