### ISSUE TITLE
LetterBox should scale `labels['ratio_pad']` when it scales an image.

### ISSUE THREAD

**Issue by iperminov-mythic** [ultralytics/ultralytics#6957]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Augmentation

### Bug

`labels['ratio_pad']` should be scaled by `r` here
https://github.com/ultralytics/ultralytics/blob/main/ultralytics/data/augment.py#L729
because the image gets scaled by `r` here
https://github.com/ultralytics/ultralytics/blob/main/ultralytics/data/augment.py#L723

I don't think this bug is ever triggered.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Alarmod** [comment]
I catched while test code for prediction with rect=False... Scales don't saved

**Comment by glenn-jocher** [comment]
@Alarmod thank you for pointing this out. It seems you have a concern with the scaling of `labels['ratio_pad']` during the LetterBox augmentation not being adjusted when `rect=False`. This behavior typically maintains aspect ratio by adding padding, and it's crucial that the label's `ratio_pad` is consistent with the image scaling to ensure accurate augmentation.

The fact that you have not encountered the bug suggests that it might rarely occur, possibly due to specific conditions during augmentation. I recommend you to continually observe this behavior and feel free to open a pull request if you see a consistent reproducible issue with this regarding YOLOv8's data augmentation pipeline.

We're continuously working on enhancing the reliability of our augmentation process, so do keep the feedback coming! 😊👍
