### ISSUE TITLE
hand pose crops training gets poor mAP results

### ISSUE THREAD

**Issue by gulj9** [ultralytics/ultralytics#6975]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm using yolo8-pose successfully on full images(1200x1200) to detect hand pose. when I'm trying to train the system on crops (128x128) of only the hands, the system's pose mAP50 reaches value of only 0.025. the box mAP is fine.

I'm running with this command line:
yolo pose train data=k_dataset.yaml model=yolov8n-pose.yaml pretrained=yolov8n-pose.pt  imgsz=128 batch=16 patience=50

here is an example of full size image (1200*1200):
![Screenshot from 2023-12-13 14-54-06](https://github.com/ultralytics/ultralytics/assets/88824042/3904608d-a6d6-4158-9c18-cf63e5093540)

here is an example of hand crop (128*128):
![rec_kiwi_000000125](https://github.com/ultralytics/ultralytics/assets/88824042/af534d4c-c9a0-4daa-b196-37ebc2384b24)

here are my results 
![results](https://github.com/ultralytics/ultralytics/assets/88824042/236c4208-3148-47df-b74a-a3bac01fea55)

results of ground truth vs. predictions:
ground truth:
![val_batch2_labels](https://github.com/ultralytics/ultralytics/assets/88824042/29aeeddc-f74f-4a6d-9c5a-831a72921040)

predictions:
![val_batch2_pred](https://github.com/ultralytics/ultralytics/assets/88824042/9ac9fac2-aeec-45f0-a15f-e018b79fc766)

**Comment by glenn-jocher** [comment]
@gulj9 hello! Thank you for using YOLOv8 for hand pose estimation on both full images and crops.

When training on small crops (128x128), the dramatic decrease in resolution could contribute to the low pose mAP50 you are experiencing. This is because fine details necessary for accurate keypoint detection may be lost at such a low resolution.

Additionally, ensure that your dataset of crops is well-represented and diverse enough for the model to learn effectively. If the crops are too similar or not varied enough in terms of angles, hand poses, and lighting conditions, the model may not generalize well.

Remember to check the annotations in your crop dataset to verify that keypoints are correctly labeled and that bounding boxes are precise. Misaligned or incorrect annotations can severely impact model performance.

Finally, consider if your network architecture is suitable for the resolution you are working with; sometimes model architectures need to be adjusted when shifting from larger to much smaller image inputs.

For further guidance on pose estimation and working with different image resolutions, please refer to the Pose/Keypoint Estimation section of our documentation. 😊

**Comment by gulj9** [comment]
Thanks a lot for your response.
The thing is, that the resolution is the same as in the full images. I made these crops without scale changing. in fact, these are taken from the very full images. When I trained the system on the full images, I got reasonable results. on the crops, I got terrible results. another think, I previously trained on those same crops a yolov3 and got mAP of 82% , and also on heat-maps model for hand-pose and got reasonable results.

**Comment by glenn-jocher** [comment]
Hello @gulj9, I understand that you're facing discrepancies in performance when training on crops at the same resolution as the full images. Since YOLOv3 yielded better results on the same data, it suggests that the issue might be related to the YOLOv8 model or configuration used for these specific crops. 

You may want to revisit the hyperparameters or the model configuration, ensuring it's apt for smaller input sizes even at the same resolution. Additionally, look into the possibility of overfitting or underfitting given the crop dataset's constraints. Tailoring the model to focus more on the keypoint detection task might also help, considering the bounding box detection seems unaffected.

Consult the Pose/Keypoint Estimation section for more targeted adjustment strategies related to YOLOv8's pose estimation capabilities. 😊
