### ISSUE TITLE
Memory is not being properly released after making predictions in YOLOv8.

### ISSUE THREAD

**Issue by kajal1598** [ultralytics/ultralytics#6981]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

- Cuda out of memory 

### Environment

Python       3.8.10
ultralytics  8.0.219

Setup:
CPU.          8 core
Memory     32
GPU.          16

### Minimal Reproducible Example

 data=model.predict(os.path.join(imagePath,i),batch=8,save=True,conf=0.7,imgsz=size, project=os.path.join(mainPath, 'runs', 'detect'), name='new1',save_txt=True)

### Additional

I have searched the YOLOv8 issues and discussions and found similar questions, but those solutions didn't work for me.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Rushita69** [comment]
I also faced the same issue, and the solutions don't seem to work for me

**Comment by glenn-jocher** [comment]
@Rushita69 it sounds like you are encountering a memory leak issue during the predict process with YOLOv8. Memory not releasing correctly can be due to a variety of factors, including the environment setup and how resources are managed post-prediction. 

For troubleshooting, you could attempt the following steps:

1. Ensure you're using the latest version of YOLOv8, as memory management optimizations are continuously being improved.
2. Monitor your GPU memory usage between predictions to identify if the leak occurs gradually or after a specific event.
3. If applicable, consider using the `gc.collect()` from Python's garbage collection module after predictions to manually prompt memory clearance.
4. Test the predict functionality with different batch sizes and observe if a smaller batch size mitigates the issue. This could point toward GPU memory constraints.
5. Inspect your system for other processes that may be consuming GPU memory and could be affecting YOLOv8’s operations.

If these suggestions do not resolve the issue, please file a detailed issue report on our Issues page with the specifics of the memory leak you are observing. This will help the Ultralytics team to further diagnose and address the problem. Our documentation may also provide additional information that can help you troubleshoot the memory management during predictions.

**Comment by Rushita69** [comment]
Thanks for your quick reply @glenn-jocher 

I am indeed using the latest version of Ultralytics YOLOv8 (8.0.227) with torch version 1.2.1 on Python 3.8.10. My environment consists of an NVIDIA A100-SXM4-40G GPU, 12-core CPU, 86GB RAM, running Ubuntu 20.04 on Google Cloud Platform (GCP).

Regarding GPU memory usage between predictions, I've observed that memory increases after each new prediction request. It appears that the model retains cache for subsequent predictions of the same input; subsequent identical prediction requests do not consume additional memory and provide an instantaneous response. However, over time, the memory accumulates and eventually fills up.

I have implemented gc.collect() after each prediction to manually prompt memory clearance, but this doesn't seem to release memory after each prediction request.

Additionally, I've experimented with different batch sizes (4, 8, 16), but the memory is not released after each prediction request.

It's worth noting that on my system, only one process is utilizing GPU memory, and that is solely for prediction purposes.

This is my code:
from ultralytics import YOLO
from flask import Flask, request, jsonify
import os
import gc

app = Flask(__name__)
@app.route('/getPredictedJson', methods=['POST'])
def getPredictJSON():
    model = YOLO(os.path.join(os.getcwd(), 'yolov8n.pt'))
    data = model.predict("images", conf=0.7, project=os.path.join(os.getcwd(), 'runs', 'detect'), name='new1', save_txt=True)
    del data
    torch.cuda.empty_cache()
    del model
    print("Before GC:", gc.get_stats())
    gc.collect()
    print("After GC:", gc.get_stats())
    return jsonify({'response': 'success'})

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000)
    
 I have also tried the same with FastAPI, experimenting with different numbers of workers, but the issue still persists

**Comment by Laughing-q** [comment]
@kajal1598 @Rushita69 please try the `stream` arg for predict mode, which is memory-effective by creating a python generator:
```python
for result in model.predict(
    os.path.join(imagePath, i),
    batch=8,
    save=True,
    conf=0.7,
    imgsz=size,
    project=os.path.join(mainPath, "runs", "detect"),
    name="new1",
    save_txt=True,
    stream=True,
):
    pass
```
you just need to use a for loop to launch it

**Comment by Rushita69** [comment]
@Laughing-q Thank you for your response
I have already tested it, encountering similar issues, but the suggested solutions couldn't effectively release the memory. Furthermore, when using the Command Line Interface (CLI), the model is loaded for each prediction request, causing longer inference times. Is there currently a trade-off between using the CLI and Python code?

**Comment by Laughing-q** [comment]
@Rushita69 what's the type of the source you're passing? a list or a image or a image path.

**Comment by Rushita69** [comment]
I am passing a single image, but the prediction requests are processed in parallel.

**Comment by glenn-jocher** [comment]
@Rushita69 since you're processing single images in parallel and memory isn't releasing properly between requests, this could be a case of memory being tied up in parallel processes. Here are some steps to consider:

1. Manage concurrent inference requests to ensure they do not overload the GPU memory.
2. Review the setup of your parallel processing to ensure that each process is correctly releasing resources, including GPU memory, after each prediction.
3. Utilize context managers where appropriate to better scope variable lifetimes and promote cleanup after use.

The CLI loading the model for each request is separate from any memory issues within a running Python process, and the additional load time would be expected behavior in that context. Using Python directly, models can be kept loaded in memory across multiple predictions which is faster than CLI if managed correctly.

**Comment by Rushita69** [comment]
> @Rushita69 since you're processing single images in parallel and memory isn't releasing properly between requests, this could be a case of memory being tied up in parallel processes. Here are some steps to consider:
> 
> 1. Manage concurrent inference requests to ensure they do not overload the GPU memory.
> 2. Review the setup of your parallel processing to ensure that each process is correctly releasing resources, including GPU memory, after each prediction.
> 3. Utilize context managers where appropriate to better scope variable lifetimes and promote cleanup after use.
> 
> The CLI loading the model for each request is separate from any memory issues within a running Python process, and the additional load time would be expected behavior in that context. Using Python directly, models can be kept loaded in memory across multiple predictions which is faster than CLI if managed correctly.

Thanks @glenn-jocher 
Will consider them

**Comment by glenn-jocher** [comment]
@Rushita69, you're welcome! If those steps don't resolve the issue, please don't hesitate to reach out on our Issues page with your findings for further assistance. Best of luck with your parallel processing setup! 🚀

**Comment by kio2019** [comment]
now ,I need predict a large dataset with 1M images with jpg format，but i found multi gpus predict is not support, can you give me some advice on how to predict data

**Comment by kio2019** [comment]
> @Rushita69, you're welcome! If those steps don't resolve the issue, please don't hesitate to reach out on our Issues page with your findings for further assistance. Best of luck with your parallel processing setup! 🚀

now ,I need predict a large dataset with 1M images with jpg format，but i found multi gpus predict is not support, can you give me some advice on how to predict data

**Comment by goodevile** [comment]
I am facing the same problem, I am not doing anything fancy, just the simple code from Ultralytics, does anyone have a solution?

```
import gc
import time

from ultralytics import YOLO

# Load an official or custom model
model = YOLO(path)  

# Perform tracking with the model
results = model.track(source=path_to_media, show=False, conf=0.5, imgsz=384,save_crop=True, vid_stride=4,stream=True)

while True:
    gc.collect()  # Force garbage collection
    time.sleep(1)  # Wait for 5 seconds
```

20 seconds running:
![image](https://github.com/ultralytics/ultralytics/assets/46387951/ab99e197-0320-411c-8430-a0f38072f039)
some seconds later:
![image](https://github.com/ultralytics/ultralytics/assets/46387951/aa368806-cef3-4df9-96ed-9449c168088d)

**Comment by glenn-jocher** [comment]
@goodevile hey there! 👋 It looks like you're experiencing some memory issues while running your code. One suggestion is to ensure your loop has a condition to exit, otherwise, it will run indefinitely and might cause memory buildup over time. Additionally, you might want to check if batching the inputs (if you're not already doing so) helps manage memory use more efficiently. If each `model.track` call processes a new piece of media and doesn't depend on previous calls, consider doing that outside the infinite loop:

```python
from ultralytics import YOLO

# Load an official or custom model
model = YOLO(path)  

# Example loop condition
for _ in range(number_of_times):
    # Perform tracking with the model
    results = model.track(source=path_to_media, show=False, conf=0.5, imgsz=384, save_crop=True, vid_stride=4, stream=True)
```

If you're still facing issues, sharing more details on the context of the loop might help. Keep an eye on GPU memory as well with tools like `nvidia-smi` to monitor memory usage in real-time. Hope this helps! 😊

**Comment by muhammad-baqir-410** [comment]
@glenn-jocher  I am also facing similar issue of memory not getting freed after making predictions. I have tried using context manager, garbage collector, etc but nothing works. Here is a sample script to reproduce this issue:

```
import torch
import psutil
from ultralytics import YOLO
import gc

def print_memory_usage(description):
    # System RAM memory
    memory = psutil.virtual_memory()
    print(f"{description}:")
    print(f"System RAM - Total: {memory.total / (1024**3):.2f} GB")
    print(f"System RAM - Used: {memory.used / (1024**3):.2f} GB")
    print(f"System RAM - Available: {memory.available / (1024**3):.2f} GB")
    print(f"System RAM - Usage Percentage: {memory.percent}%")

    # GPU memory
    if torch.cuda.is_available():
        torch.cuda.synchronize()  # Wait for all kernels in all streams on a CUDA device to complete
        gpu_memory = torch.cuda.memory_stats(device=0)  # Get memory stats for the CUDA device
        print(f"GPU - Allocated: {gpu_memory['allocated_bytes.all.current'] / (1024**3):.2f} GB")
        print(f"GPU - Cached: {gpu_memory['reserved_bytes.all.current'] / (1024**3):.2f} GB")
    print()

class ModelManager:
    def __enter__(self):
        self.model = YOLO('yolov8n.pt')
        return self.model

    def __exit__(self, exc_type, exc_value, traceback):
        del self.model
        torch.cuda.synchronize()  # Wait for all CUDA operations to complete
        torch.cuda.empty_cache()
        gc.collect()
        torch.cuda.synchronize()  # Final synchronization after cleanup


# Memory usage before loading the model
print_memory_usage("Memory Usage Before Loading the Model")

with ModelManager() as model:
    model.predict()  # Use the model within the context

    # Memory usage after loading the model
    print_memory_usage("Memory Usage After Loading the Model")

# Memory usage after deleting the model
print_memory_usage("Memory Usage After Deleting the Model")
```

Here is the terminal output:

```
Memory Usage Before Loading the Model:
System RAM - Total: 31.22 GB
System RAM - Used: 14.97 GB
System RAM - Available: 15.41 GB
System RAM - Usage Percentage: 50.6%
GPU - Allocated: 0.00 GB
GPU - Cached: 0.00 GB

WARNING ⚠️ 'source' is missing. Using 'source=/home/user/anaconda3/envs/yolov8/lib/python3.11/site-packages/ultralytics/assets'.

image 1/2 /home/user/anaconda3/envs/yolov8/lib/python3.11/site-packages/ultralytics/assets/bus.jpg: 640x480 4 persons, 1 bus, 1 stop sign, 78.1ms
image 2/2 /home/user/anaconda3/envs/yolov8/lib/python3.11/site-packages/ultralytics/assets/zidane.jpg: 384x640 2 persons, 1 tie, 79.3ms
Speed: 2.0ms preprocess, 78.7ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)
Memory Usage After Loading the Model:
System RAM - Total: 31.22 GB
System RAM - Used: 16.72 GB
System RAM - Available: 13.65 GB
System RAM - Usage Percentage: 56.3%
GPU - Allocated: 0.04 GB
GPU - Cached: 0.09 GB

Memory Usage After Deleting the Model:
System RAM - Total: 31.22 GB
System RAM - Used: 16.72 GB
System RAM - Available: 13.65 GB
System RAM - Usage Percentage: 56.3%
GPU - Allocated: 0.04 GB
GPU - Cached: 0.06 GB
```

As you can see the system RAM usage remains the same even after deleting the model instance

**Comment by glenn-jocher** [comment]
Hey @muhammad-baqir-410, thanks for sharing your script and the detailed output! It looks like you've implemented a solid approach with the context manager and garbage collection. However, the persistent memory usage might be due to Python's memory management, which doesn't immediately return memory to the system even after objects are deleted and garbage collected.

One suggestion is to try reducing the scope of variables and data loaded during prediction to minimize the memory footprint. Also, if you're running this in a notebook or a long-running script, consider executing it in a fresh Python environment or script to ensure there are no residual effects from previous computations.

If the issue persists, it might be helpful to look into Python's memory profiling tools to pinpoint any other potential memory leaks or unexpected behavior. Keep us posted on your progress! 😊

**Comment by hoang-innomize** [comment]
@glenn-jocher we are also facing this issue, after many attempts to force clearing the memory, delete the model, etc. the RAM is still not reclaimed after running the prediction. It is clear to us that when initialing the mode and running the prediction, the RAM increased and stayed there without reclaim. We are using https://github.com/ultralytics/ultralytics/blob/main/docker/Dockerfile-cpu to run the process. 

Do you have any ideas to force deleting or release objects completely?

**Comment by hoang-innomize** [comment]
@goodevile my code is really simple

```
model = YOLO("dla-model.pt")
results = list(model(images, stream=True))
print(results)
```
I expect after running and getting the results, RAM should be reclaimed, but based on my current test, RAM cannot be released. Could you please share your approach to overcome this issue?

**Comment by muhammad-baqir-410** [comment]
> Hey @muhammad-baqir-410, thanks for sharing your script and the detailed output! It looks like you've implemented a solid approach with the context manager and garbage collection. However, the persistent memory usage might be due to Python's memory management, which doesn't immediately return memory to the system even after objects are deleted and garbage collected.
> 
> One suggestion is to try reducing the scope of variables and data loaded during prediction to minimize the memory footprint. Also, if you're running this in a notebook or a long-running script, consider executing it in a fresh Python environment or script to ensure there are no residual effects from previous computations.
> 
> If the issue persists, it might be helpful to look into Python's memory profiling tools to pinpoint any other potential memory leaks or unexpected behavior. Keep us posted on your progress! 😊

@glenn-jocher  Thanks for the reply. For now, I am performing the model loading and inference in a separate script and running it as a subprocess in my main script. This way, the resources are released once the subprocess is terminated. Anyone else facing this issue can try the following approach:

Let's say this is my inference script:

```
import sys
from ultralytics  import YOLO

def run_inference(video_path):
    model = YOLO('yolov8n.pt')
    results = model.predict(source = video_path)

if __name__ == "__main__":
    video_path = sys.argv[1]
    run_inference(video_path)
```

This is my `main.py` file:

```
import subprocess
import time

def some_condition():
    # This function should check or wait for a condition to change
    # Example: Return True after some time or based on some external event
    time.sleep(10)
    return True

if __name__ == "__main__":
    video_path = "video.mp4"
    inference_process = subprocess.Popen(['python', 'inference.py', video_path])
    check = some_condition()
    if check:
        inference_process.terminate()
        print("Subprocess was terminated due to a condition.")
    
    # Continue with the rest of the code
```

Once the subprocess is terminated, the system RAM is released and you can continue working in the main script. In case you need to share data from the inference script to the main script or the other way around, you can use `Pipe` from the `multiprocessing` library.

**Comment by glenn-jocher** [comment]
@muhammad-baqir-410-410, that's a clever workaround using subprocesses to manage memory more effectively! 🚀 This approach ensures that all resources are indeed freed up when the subprocess exits, which can be particularly useful in environments where memory management is critical. Thanks for sharing your solution; it could definitely help others experiencing similar issues!

**Comment by OlivierC42** [comment]
@muhammad-baqir-410 - Thank you so much for the idea! My model.fit() for BiLSTM in a loop was filling up the whole CPU memory after a while. Every other approach miserably failed (del of all tf objects, gc.collect(), etc. The multiprocessing/subprocess approach worked. BTW, using queue, we dont have to use external scripts. Example below:

```
def model_fit(queue):
    features, target, epochs = queue.get()
    
    # Scaling, generators, etc. go here...
    
    model.fit(train, epochs, test, verbose=0)

    # Oh and because you never know...
    tf_backend.clear_session()
    gc.collect

    queue.put(anything)

if __name__ == "__main__":
    queue = multiprocessing.Queue()
    queue.put((features.values, target.values, epochs))

    p = multiprocessing.Process(target=model_fit, args=(queue,))
    p.start()
    p.join()

    anything = queue.get()

```

**Comment by WandererGuy** [comment]
> @kajal1598 @Rushita69 please try the `stream` arg for predict mode, which is memory-effective to handle long-list images or videos or streams by creating a python generator:
> 
> ```python
> for result in model.predict(
>     os.path.join(imagePath, i),
>     batch=8,
>     save=True,
>     conf=0.7,
>     imgsz=size,
>     project=os.path.join(mainPath, "runs", "detect"),
>     name="new1",
>     save_txt=True,
>     stream=True,
> ):
>     pass
> ```
> 
> you just need to use a for loop to launch it

u made my day bro <3

**Comment by arbitropy** [comment]
> [@kajal1598](https://github.com/kajal1598) [@Rushita69](https://github.com/Rushita69) please try the `stream` arg for predict mode, which is memory-effective to handle long-list images or videos or streams by creating a python generator:
> 
> for result in model.predict(
>     os.path.join(imagePath, i),
>     batch=8,
>     save=True,
>     conf=0.7,
>     imgsz=size,
>     project=os.path.join(mainPath, "runs", "detect"),
>     name="new1",
>     save_txt=True,
>     stream=True,
> ):
>     pass
> 
> you just need to use a for loop to launch it

This is great. For some reason normal predict with fixed batch size doesn't seem to clear the memory after batch is complete. so the memory usage keeps increasing until OOM. This stream solution solves it. Not sure whats causing the leak.

**Comment by glenn-jocher** [comment]
@arbitropy Thanks for sharing your experience! The `stream=True` parameter is indeed designed specifically to address memory management issues like this. As mentioned in our [documentation](https://docs.ultralytics.com/modes/predict/), streaming mode creates a memory-efficient generator that only keeps the current frame's results in memory rather than accumulating all results.

When processing large datasets, videos, or multiple batches, using `stream=True` with a for-loop ensures each result is processed and then released from memory immediately. This approach is particularly effective when dealing with memory constraints or when running inference on large numbers of images.

For anyone else facing similar memory issues, I'd recommend trying this pattern:

```python
for result in model.predict(source, stream=True):
    # Process your result here
    # Memory is released after each iteration
```

**Comment by glenn-jocher** [comment]
@SOL1archive Thank you for sharing your findings! You've hit on an important point about explicitly deleting the `results_batch` objects. The `predict` method can indeed retain references to tensors and other objects that won't be automatically garbage collected without explicit deletion.

Your solution demonstrates a good pattern for memory management:
1. Run prediction within a `torch.no_grad()` context
2. Extract the necessary information from results
3. Explicitly delete all objects (model, inputs, and results)
4. Force garbage collection and empty CUDA cache

This approach is particularly useful for production environments where you're processing many images and need careful memory management. We'll consider improving the automatic cleanup in future releases based on this feedback.

For other users experiencing similar issues, you might also find the `predict_cli` method useful as it's specifically designed to avoid memory accumulation by consuming the generator without storing results.

**Comment by ManishSahu53** [comment]
This resolved for me.

    # Segment everything
    with torch.no_grad():
        everything_results = predictor(path_image)
        text_results = predictor.prompt(everything_results, texts="document")

**Comment by glenn-jocher** [comment]
@ManishSahu53 Great to hear that `torch.no_grad()` resolved the issue for you! Using this context manager prevents gradient computation and tracking, which significantly reduces memory overhead during inference. This approach is particularly effective when you don't need gradients for backpropagation, which is typically the case during prediction/inference tasks.

This complements the other memory management strategies discussed in this thread nicely - it's often one of the first optimizations to implement for inference workloads.
