### ISSUE TITLE
Yolo tracker returns detections without track_id

### ISSUE THREAD

**Issue by jasper-staal** [ultralytics/ultralytics#7013]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am using a YOLO pose model (yolov8s-pose.pt) and bytetracker, to track multiple persons in a video. In a few frames a detection is  shown, without a track_id. Looking into the bytetracker a bit further I noticed that these are new detections, so a new strack is initialized with the `STrack.activate()` function. A track_id is assigned to this detection, but is not return by `ByteTracker.update()` due to the `track.is_activated = False`. I was wondering why  `track.is_activated=True` only when `frame_id == 1`?

Intuitively I would say a track_id is returned for all new detections (when `new_track_tresh` is smaller than the confidence_threshold)

Below the `STrack.activate()` function I'm refering to:
```
def activate(self, kalman_filter, frame_id):
        """Start a new tracklet."""
        self.kalman_filter = kalman_filter
        self.track_id = self.next_id()
        self.mean, self.covariance = self.kalman_filter.initiate(self.convert_coords(self._tlwh))
        self.tracklet_len = 0
        self.state = TrackState.Tracked
        if frame_id == 1:
            self.is_activated = True
        self.frame_id = frame_id
        self.start_frame = frame_id
```

**Comment by glenn-jocher** [comment]
@jasper-staal hello! It seems you've discovered a situation where detections are not being assigned a `track_id` by `ByteTracker.update()` because their `is_activated` attribute is set to `False`.
 
The `is_activated` flag is generally used within tracking implementations to manage the state of tracked objects and filter out false positives. It is critical to maintaining the integrity and accuracy of the tracking over time. The behavior you've observed, where `is_activated` is set to `True` only when `frame_id == 1`, is designed to only activate the track for the first frame as a starting point for tracking across frames.

This logic helps to prevent instantaneous false positives from being immediately considered as valid tracks. Instead, an object usually needs to be detected over several frames before being established as a confirmed track. This ensures that only high-confidence tracks are retained and reduces noise in the tracking output.

For the initialization logic on subsequent frames, trackers often use a combination of subsequent detection confidence, motion predictions, and other heuristics to determine when a track should be activated (`is_activated = True`). This can involve a threshold (`new_track_tresh` you mentioned) that balances the sensitivity of track initiation with the desired level of tracking accuracy and robustness.

If you're experiencing issues with track IDs not being consistently assigned, you may want to explore adjusting the tracker configurations or examining the criteria that the tracker uses to activate new tracks.

I hope this clarifies the behavior you're seeing. Don't hesitate to explore our [docs on tracking](https://docs.ultralytics.com/modes/track) for more detailed information on how tracking is handled in our models! 😊

**Comment by jasper-staal** [comment]
Hi @glenn-jocher, thanks for the elaborate answer. This clarifies a lot! The issue of having no trackID's occurs only a few times over a large set of frames and is very minor. Also, I expect us to have a better performance in the detections in the future, so the issue would arise even less.

**Comment by glenn-jocher** [comment]
Hey @jasper-staal! I'm glad to hear the explanation was helpful. It sounds like you're on the right track and, with improved detection performance, the minor issue with track IDs should become even less frequent. Happy tracking, and here's to even better results ahead! 🚀 If you encounter any more hurdles, feel free to check our [tracking documentation](https://docs.ultralytics.com/modes/track) or reach out again. Keep up the great work!
