### ISSUE TITLE
[Dataset] AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by ngocthach** [ultralytics/ultralytics#7018]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I run train classification model by command ```yolo task=classify mode=train``` but I receive below error log.
I guest some images have a problem and the code in dataset.py not check valid image before use
```
sample = self.torch_transforms(im)
```
I will try to fix this issue soon.

```
File "/home/ubuntu/env/lib/python3.8/site-packages/ultralytics/yolo/data/dataset.py", line 211, in __getitem__
    sample = self.torch_transforms(im)

  File "/home/ubuntu/env/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 95, in __call__
    img = t(img)

  File "/home/ubuntu/env/lib/python3.8/site-packages/ultralytics/yolo/data/augment.py", line 760, in __call__
    imh, imw = im.shape[:2]

AttributeError: 'NoneType' object has no attribute 'shape'
```

### Environment

```
Ultralytics YOLOv8.0.16 🚀 Python-3.8.10 torch-2.1.2+cu121 CPU
Setup complete ✅ (4 CPUs, 29.9 GB RAM, 71.2/484.4 GB disk)
```

### Minimal Reproducible Example

```
nohup yolo task=classify mode=train model=yolov8n-cls.pt data=/path/sensitive_data epochs=2 imgsz=640 &
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ngocthach hello! Thanks for reporting this issue and your willingness to help with a PR. 🚀

It seems like you've encountered an error where an image was loaded as `None`, which typically indicates that an image at a specified path could not be read correctly. This might be caused by corrupted, missing, or incorrectly formatted images within your dataset.

To resolve this, you should verify that all image paths in your dataset are correct, all the images are properly formatted, and none are corrupted. You can also add a check before the line where the error occurs to ensure that the image is not `None` before applying any transformations.

We appreciate your contribution to improving YOLOv8, and for any further questions, remember that the [Ultralytics Docs](https://docs.ultralytics.com) are always there to help. Good luck with your PR! 🌟
