### ISSUE TITLE
[Dataset] AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by lengocthach** [ultralytics/ultralytics#7019]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I run train classification model by command ```yolo task=classify mode=train``` but I receive below error log.
I guest some images have a problem and the code in dataset.py not check valid image before use
```
sample = self.torch_transforms(im)
```
I will try to fix this issue soon.

File "/home/ubuntu/lnthach/env/lib/python3.8/site-packages/ultralytics/yolo/data/dataset.py", line 211, in __getitem__
    sample = self.torch_transforms(im)
  File "/home/ubuntu/lnthach/env/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 95, in __call__
    img = t(img)
  File "/home/ubuntu/lnthach/env/lib/python3.8/site-packages/ultralytics/yolo/data/augment.py", line 760, in __call__
    imh, imw = im.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

### Environment

Ultralytics YOLOv8.0.16 🚀 Python-3.8.10 torch-2.1.2+cu121 CPU
Setup complete ✅ (4 CPUs, 29.9 GB RAM, 71.2/484.4 GB disk)

### Minimal Reproducible Example

nohup yolo task=classify mode=train model=yolov8n-cls.pt data=/path/sensitive_data epochs=2 imgsz=640 &

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by lengocthach** [comment]
duplicate at https://github.com/ultralytics/ultralytics/issues/7018

**Comment by glenn-jocher** [comment]
@lengocthach the AttributeError you're encountering typically indicates that an image was not loaded properly, which would indeed result in a `None` type object being returned. The framework expects every image to be valid, so if there's an issue with some images not being read correctly, that would trigger such an error.

I recommend confirming that all images in your dataset are intact and in a readable format. You might want to check for corrupted or invalid image files and remove them from your dataset. If you are writing a fix for this, it would be beneficial for it to include validation to ensure each image is loaded correctly before being passed to the transforms.

Thank you for taking the initiative to contribute with a PR; this will surely improve the robustness of the dataset handling in YOLOv8. For guidance on contributing, please refer to our documentation on how to [contribute to YOLOv8](https://docs.ultralytics.com). If you have any further questions or require assistance, don't hesitate to ask. Your collaboration is much appreciated! 🤝

**Note**: This issue seems to be a duplicate; maintaining a single thread for the same issue helps in tracking the discussion and solutions efficiently. It's good practice to continue in the original issue thread when possible. 

Looking forward to your PR, and thank you for being a part of the YOLO community! 🚀
