### ISSUE TITLE
Predicted boxes values are always 0 whereas class scores are correct

### ISSUE THREAD

**Issue by kleberbueno** [ultralytics/ultralytics#7027]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have compiled OPENCV 4.8 with CUDA 11.2 in my virtual env.
Then I trained a custom dataset with Yolov8 and convert model to an onnx model.

I got Ultralytics opencv yolov8 example and performed inference. When using OPENCV CPU as backend, everything woks  perfectly fine. However, when I set OPENCV backend to CUDA, the predicted boxes are always coming as 0 for x,y,w,h. Although for same prediction class scores are ok.

Did anyone faced an issue like that? 

Just to let you know, the same opencv version compiled with CUDA works fine for Yolov4 as well.

Any help is much appreciate.

Thanks
Kleber

**Comment by kleberbueno** [comment]
Just an update. I have recompiled opencv with cuda, but now for version 4.7. It worked fine. Probably opencv version 4.8 is still not working with yolov8 and cuda.
Thanks

**Comment by glenn-jocher** [comment]
@kleberbueno hello Kleber 👋,

It's quite intriguing that OpenCV 4.8 works with CPU but not with CUDA for YOLOv8, while OpenCV 4.7 has the inverse issue. It suggests that compatibility might be affecting the interfacing with YOLOv8's ONNX models. The NaN outputs for CPU inference with OpenCV 4.7 could be due to issues in the OpenCV build or a mismatch between the libraries used for compilation and those used at runtime. 

Since YOLOv8 is under continuous development, it's possible that updates and changes to the model architecture might not be fully supported by all versions of OpenCV with CUDA acceleration immediately. When you switch between OpenCV versions, make sure to clean and rebuild your environment to avoid any residual configurations leading to these discrepancies.

I suggest reporting this behavior to the OpenCV team as well, as they might provide more detailed assistance on compatibility issues between YOLOv8 ONNX models and the CUDA backend of recent OpenCV versions. 

For more detailed guidance on how to use YOLOv8, check our official documentation at https://docs.ultralytics.com. 

Thank you for bringing this to our attention, and the entire community appreciates your perseverance. Keep experimenting, and let's hope for a solution soon! 🛠️

**Comment by kleberbueno** [comment]
Thanks @glenn-jocher 
I found opencv threads about it.

**Comment by glenn-jocher** [comment]
@kleberbueno hello Kleber,

Great to hear you've found related threads in the OpenCV community. Do keep an eye on those for potential solutions or workarounds. Your findings are valuable, and sharing them can help others facing similar issues. Best of luck with your project!

Thank you for using YOLOv8, and we look forward to any more feedback or insights you might provide. 😊👍
