### ISSUE TITLE
unknown feature

### ISSUE THREAD

**Issue by Bani-Asadi** [ultralytics/ultralytics#705]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello

Is it possible for yolo8 classifier to classify unknown class with high accuracy? To be more clear, I want to classify between cats and dogs, and if test my model with the image of a wolf, my model returns unknown class.

Thanks in advance.

**Comment by knoppmyth** [comment]
This can be handled via programming and isn't related to the model. What I do is, set my confidence for X. If I don't get results, I simple return class is unknown.

**Comment by JustasBart** [comment]
Hi @Bani-Asadi I'm no expert on this unfortunately, but if you want an early answer I think that the answer is no.
Your model would have 2 tensors for your 2 classes and it would always try and fit your new input data to the output of your model so therefore you'd get your 2 confidences for your Cat/Dog classifications, but that's it.

Someone correct me if I'm wrong, but I don't think that it's possible to do what you're describing to do directly...

I'm not actually sure how should you either implement a third output for like a 'other' category and/or how else would you filter the mystery categories out other than having many labelled categories and ignoring the ones you don't want...

Hope this helps! :rocket:

**Comment by JustasBart** [comment]
@Bani-Asadi Thinking about it though, if you were to say set a 60% (Or whatever works best) threshold for your 2 known classes you can have it such so that anything over that threshold is a Cat/Dog, but anything under it is 'Unknown' of course sometimes though it'll just classify Cat/Dog images as 'Unknown' if the image is tricky and if it can't tell, but I don't know if there's a way to show it negative data, perhaps look into is there a some sort of a 'Background' image option that you could facilitate in order to learn what's not a Cat/Dog alongside of learning what is?
