### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encoding'

### ISSUE THREAD

**Issue by UyeYwb** [ultralytics/ultralytics#7064]
File "D:\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO

  File "D:\ultralytics\models\__init__.py", line 3, in <module>
    from .rtdetr import RTDETR

  File "D:\ultralytics\models\rtdetr\__init__.py", line 3, in <module>
    from .model import RTDETR

  File "D:\ultralytics\models\rtdetr\model.py", line 10, in <module>
    from ultralytics.engine.model import Model

  File "D:ultralytics\engine\model.py", line 9, in <module>
    from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir

  File "D:\ultralytics\cfg\__init__.py", line 10, in <module>
    from ultralytics.utils import (ASSETS, DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, RANK, ROOT, RUNS_DIR,

  File "D\ultralytics\utils\__init__.py", line 265, in <module>
    LOGGER = set_logging(LOGGING_NAME, verbose=VERBOSE)  # define globally (used in train.py, val.py, predict.py, etc.)
             │           │                     └ True
             │           └ 'ultralytics'
             └ <function set_logging at 0x000002701DDF65E0>

  File "D:\\ultralytics\utils\__init__.py", line 233, in set_logging
    if WINDOWS and sys.stdout.encoding != 'utf-8':
       │           │   └ None
       │           └ <module 'sys' (built-in)>
       └ True

AttributeError: 'NoneType' object has no attribute 'encoding'

Why am I encountering this error? My version is 8.0.218.

_Originally posted by @UyeYwb in https://github.com/ultralytics/ultralytics/issues/6446#issuecomment-1859817895_

**Comment by glenn-jocher** [comment]
Hello @UyeYwb 👋,

The error you're encountering suggests that `sys.stdout` might be unassigned when `set_logging` is called, which is unusual. This can occasionally occur in some specific environments or configurations where the standard output (stdout) is not properly set up.

If you are running the code in a standard environment, this shouldn't happen. Double-check if you have any custom scripts or modifications that could potentially alter `sys.stdout`. Also, ensure that your environment is set up correctly; you might want to try running your script in a freshly set up Python environment. If you're running the code in an IDE or an unusual terminal setup, try running it in a standard command prompt or terminal.

For more detailed guidance, you might want to refer to our documentation on how to set up your environment and common issues at our Ultralytics Docs.

**Comment by neolib1314** [comment]
Hi. I had the same problem.
I used the PythonNet library for developing my C# application.
This issue did not occur when working with the IDE.
It happened when I run the executable independently.
I suspected that this problem was caused by sys.stdout being None, so I solved it in the following way.

import sys
from io import StringIO
memory_buffer = StringIO()
sys.stdout = memory_buffer

This may not be the correct way to do it.
You may also need to clear the memory buffer.
If you have a better way, please let me know.
God bless...

**Comment by glenn-jocher** [comment]
@neolib1314 hello,

It seems like you've found a workaround by redirecting `sys.stdout` to an in-memory buffer, which can indeed resolve issues when `sys.stdout` is `None`. This typically happens in environments where the standard output is not available, such as when running a Python script from a non-console application.

Your solution is valid for ensuring that `sys.stdout` is not `None`. However, be aware that this might suppress output that would otherwise be printed to the console. If your application relies on this output, you'll need to handle the in-memory buffer accordingly.

If you're not familiar with Python and are looking for a more standard approach, you might want to consult with a Python developer or refer to our documentation for more information on environment setup and troubleshooting.
