### ISSUE TITLE
Regardless of choosing w,h, will yolov8 set the training size to a square within max(w,h)?

### ISSUE THREAD

**Issue by minwim** [ultralytics/ultralytics#7065]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

model.train imgsz = [ 480,640], imgsz = [360, 640] No matter what size I choose,  yolov8 choose imgsz = [640, 640] when training?

### Additional

no

**Comment by glenn-jocher** [comment]
@minwim hi there! YOLOv8 indeed supports non-square training sizes, so it should not enforce a square size like [640, 640] unless specified. If you are encountering a situation where the training size is being set to a square in spite of providing non-square dimensions, this could be due to a configuration oversight or a possible issue with the current setup.

I would suggest re-checking the configuration files and command-line arguments to ensure they are being set correctly. Look specifically at the `--imgsz` parameter if using CLI, or its equivalent in the Python environment. If the issue persists, please consider opening an issue with complete reproducible steps, and we'll look into it promptly. 🛠️

For further guidance on model configurations and training details, check out our detailed documentation at https://docs.ultralytics.com.
