### ISSUE TITLE
Key-point Confidence Change

### ISSUE THREAD

**Issue by navidTerraNova** [ultralytics/ultralytics#7070]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can I lower the confidence threshold for key points while model is predicting? I assume the default threshold is set to 0.5

**Comment by glenn-jocher** [comment]
@navidTerraNova hello! To adjust the keypoint confidence threshold during prediction with YOLOv8, you should modify the `conf_thresh` parameter provided to the prediction function. While the default may indeed be set to 0.5, you can set it lower to allow keypoints with lower confidence to be recognized by the model. You'll find the exact usage of this parameter within the predict mode documentation in the [Ultralytics Docs](https://docs.ultralytics.com/modes/predict).

Just make sure to strike the balance that fits your use case, as lowering the threshold too much might lead to false positives. Happy coding! 😊

**Comment by jamjamjon** [comment]
@glenn-jocher  The `conf` parameter will filter out objects (bounding boxes and keypoints within them) whose prediction scores are smaller than it. Perhaps a `keypoint_conf` parameter should be added to control the visibility of each keypoint individually instead of a fixed 0.5.  https://github.com/ultralytics/ultralytics/blob/bc5b528ca78c67a689ce6001af963aaa1a5b2d5e/ultralytics/engine/results.py#L502-L505

**Comment by glenn-jocher** [comment]
@jamjamjon, thanks for the suggestion! Having a `keypoint_conf` parameter to control the confidence of keypoints independently sounds like a valuable feature. We appreciate the feedback and will consider it for future updates to the YOLOv8 model functionality. Your input helps us improve, and we're grateful for the community's contributions. Keep the ideas coming! 👍🏻
