### ISSUE TITLE
No confusion matrix/inference on test set; Understanding the augment=True/False parameter

### ISSUE THREAD

**Issue by iholy19** [ultralytics/ultralytics#7073]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

For the yolo8seg model training, when **augment=True**, the model does not do inference with test dataset and does not create confusion_matrix, and other metrics at the end.
![Capture](https://github.com/ultralytics/ultralytics/assets/42679048/61b01eb7-15af-441b-a4af-3d8738d43908)

But when **augment=False**, the model does the inference and create confusion_matrix, metrics curve, etc. It works fine.
![tempsnip](https://github.com/ultralytics/ultralytics/assets/42679048/64b957e3-f61c-4aec-8f5e-b3b031f4142f)

1. I would like to know what makes the diffference when augment=True
2. if augment=False and when I set other augmentation parameters like hsv_h=0.02; hsv_s=0.5; hsv_v=0.4, degrees=3; mosaic=0.01; scale=0.02, will the augmentation applied in the training or not?

**Comment by glenn-jocher** [comment]
@iholy19 hello! Thank you for bringing this to our attention. 

1. The `augment=True` setting is intended to apply data augmentation during training to improve model robustness. It should not affect the generation of the confusion matrix or metric curves during validation. If you're experiencing this issue, it suggests there might be an unexpected behavior in our pipeline that we need to investigate. Your feedback is very valuable in this context.

2. When you set `augment=False` but still specify other augmentation parameters like `hsv_h`, `hsv_s`, `hsv_v`, `degrees`, `mosaic`, and `scale`, these settings, although present, will not be applied during training since the main augmentation toggle is turned off.

Thank you for reaching out, and we appreciate your participation in the YOLOv8 community. 🌟 If you have further questions or insights, feel free to discuss them in the repo's discussions section!

**Comment by iholy19** [comment]
Thank you for your response. Please let me know when there is an update.

**Comment by glenn-jocher** [comment]
@iholy19, you're welcome! We'll look into the issue and provide updates when available. Your patience and contributions to the YOLOv8 community are greatly appreciated. Keep an eye out for announcements in the repo! 😊👍
