### ISSUE TITLE
Privacy concerns about collecting model metrics 

### ISSUE THREAD

**Issue by frandoLin** [ultralytics/ultralytics#7089]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I am working on the area where privacy concerns is the top priorities. I am using the MLFlow to monitor the model training which is a great tool to monitor the model performance but we are wondering if our model metrics and artifacts will be collected? Is there any way to figure it out by reviewing any of your documentations? Thanks!

**Comment by glenn-jocher** [comment]
@frandoLin hi there! 👋 Concerns about privacy are indeed critical, and I'm glad to see you're taking this seriously.

I want to assure you that with YOLOv8, when you're using tools like MLFlow for monitoring your model training, we do not collect any of your model metrics or artifacts. The processes and data remain within your control and infrastructure.

For more information about our policies and the use of third-party tools, please refer to our documentation. Rest assured that the use of YOLOv8 in your projects adheres to privacy by design principles. If you have additional specific concerns, we encourage you to review the documentation for the tools in question, such as MLFlow, for their data handling policies.

Your diligence in ensuring privacy is commendable! Should you have further queries about the usage of YOLOv8 and privacy aspects, feel free to reach out. Happy to help, and best wishes for your privacy-focused projects! 🛡️
