### ISSUE TITLE
How to train Yolo to recognize classes that are not in the training dataset? Plz help

### ISSUE THREAD

**Issue by lexDiller** [ultralytics/ultralytics#7099]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello everyone, I recently started in computer vision. There is an enterprise where cameras need to determine whether an employee is wearing personal protective equipment or not. Unfortunately, it is absolutely impossible to assemble a training dataset on these cameras in the data of violators, since everyone follows safety rules. After training, the model will be able to recognize only people in personal protective equipment (helmets, gloves, etc.) How do I train Yolo so that she can recognize violations? From my thoughts, the first is to use isolating forest, but I will have to transform the images into vector space, or somehow work with IoU. Plz suggest any ways to solve this problem.

**Comment by glenn-jocher** [comment]
@lexDiller hello! It's great to see your enthusiasm for applying YOLOv8 in such a practical scenario. To train YOLO to recognize new classes not present in your dataset, you would need to collect or create a new dataset that includes examples of those classes. Since direct collection is not possible in your case due to compliance with safety rules, consider using synthetic data generation techniques to create images of employees without personal protective equipment. This might include methods like image editing or using a generative model to create such examples.

Once you have your augmented dataset with both cases (with and without protective gear), you can follow the standard YOLOv8 training procedure to teach your model to differentiate between the two classes. Refer to our documentation on the Train mode if you need guidance on that process.

Keep in mind, for reliable performance in a safety-critical environment, exhaustive validation and testing are crucial. Good luck with your project! 😊🛠️

**Comment by lexDiller** [comment]
@glenn-jocher, Thanks a lot!

**Comment by glenn-jocher** [comment]
@lexDiller you're welcome! If you have any more questions, feel free to reach out. Happy coding! 😄🚀

**Comment by eiyike123** [comment]
How can i make yolov8 detect extra classes. I have 150 images which contains 5 extra classes in each image. I want to create a yolo model that can detect the old classes and also the new five classes i want to introduce.

**Comment by glenn-jocher** [comment]
@eiyike123 to add new classes to YOLOv8 detection capabilities, you'll first need to annotate your 150 images with the five extra classes. Once annotated, you can merge this new dataset with your original dataset to include all classes, ensuring the new classes are properly labeled in the data configuration files. Finally, train YOLOv8 on the combined dataset to create a model that can detect both old and new classes. Follow the training guide in our documentation for detailed steps. Happy training! 😊👍
