### ISSUE TITLE
If the object is very small, it may disappear from the mask label.

### ISSUE THREAD

**Issue by NingYuanLin** [ultralytics/ultralytics#7106]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train, Val

### Bug

Thanks for your work.
I found that there seems to be an issue with the polygon2mask function. Specifically, if the object is very small, it may disappear from the mask label.
# https://github.com/ultralytics/ultralytics/blob/a5735724c54a9f5bcb239c151fefbd1337d7123d/ultralytics/data/utils.py#L155-L175

The problem lies in the `cv2. resize(mask, (nw, nh))` function. If the object is very small (for example, before resizing, it is only a pixel on the mas), then after resizing, the object is likely to disappear.

Is this an expected behavior?

One solution is `cv2. resize(mask, (nw, nh), interpolation=cv2.INTER_NEAREST )`. This approach will not cause the object to disappear from the mask in most cases, but it still cannot completely solve this problem.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@NingYuanLin hi there!

Thank you for your detailed report and willingness to contribute with a PR. 👍

Indeed, a very small object could disappear during mask resizing due to the interpolation method used. Your suggestion to use `cv2.INTER_NEAREST` is a recognized way to better preserve such small objects during the resize operation. While this might not completely solve the issue for extremely small objects, it generally provides an improvement over other interpolation methods.

If you're inclined to adjust this, your PR would be most welcome. We'll review it for potential integration within the YOLOv8 pipeline to address this behavior.

Thanks again for your input and support! 😊
