### ISSUE TITLE
When is imgsz argument inferred from model?

### ISSUE THREAD

**Issue by iokarkan** [ultralytics/ultralytics#7132]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

version: ultralytics==8.0.220

I have been experimenting with models trained with `imgsz=640` and `imgsz=1280`, respectively. Normally, I have produced PyTorch checkpoints for these models and using them with to `model.val(...)` and `model(img, ...)` (for prediction) in my projects.

I have so far not specified the imgsz argument, (for example settings `imgsz=1280` when using a 1280-trained model), and I have also not manually resized my image to match expected model input, as I have assumed that this parameter is inferred from the trained model architecture and resized during pre-processing within ultralytics.

However, I experimented with using `model(img, ...)` for an OpenVINO format of a 1280-trained model, and I see that I get an error if I don't specify `imgsz=1280`. This error doesn't appear if I don't specify `imgsz=1280` when doing inference with a 1280-trained .pt model checkpoint.

My question is, am I correct to assume this is a specific behaviour of OpenVINO format, and that when using PyTorch (.pt) checkpoints I don't have to specify an `imgsz` argument to match the training parameter?

**Comment by glenn-jocher** [comment]
@iokarkan hello! Yes, you are correct that this behavior is specific to the OpenVINO format. When using a YOLOv8 model in PyTorch format (with `.pt` extension), the `imgsz` parameter is indeed inferred from the model automatically during both validation and prediction. Images are resized appropriately by the pre-processing pipeline to match the required input size of the model. This is built-in functionality for PyTorch checkpoints to streamline the workflow.

When exporting the model to OpenVINO or other export formats, however, you need to specify the `imgsz` to match the size used during training since this is not automatically inferred. Each export format may handle input sizing differently, requiring manual intervention to ensure proper operation.

Thanks for reaching out and happy experimenting with YOLOv8! 😊🚀
