### ISSUE TITLE
Multiple object tracking with Multiple streams assigns IDs to all streams subsequently

### ISSUE THREAD

**Issue by bit-scientist** [ultralytics/ultralytics#7209]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict, Other

### From the first variant below. The IDs are at the end of each row per txt file.
![image](https://github.com/ultralytics/ultralytics/assets/26497571/72f7903e-681c-4261-9cdf-68f0b8bc3d98)

---

### From the second variant below

![image](https://github.com/ultralytics/ultralytics/assets/26497571/2323460b-5fdd-4189-b444-1ed3df3daf48)

### Environment

```
Ultralytics YOLOv8.0.227 🚀 Python-3.10.9 torch-2.0.0 CUDA:0 (NVIDIA GeForce RTX 3080 Ti, 12288MiB)
Setup complete ✅ (16 CPUs, 63.9 GB RAM, 1853.4/3726.0 GB disk)

OS                  Windows-10-10.0.19045-SP0                
Environment         Windows                                  
Python              3.10.9                                   
Install             pip                                      
RAM                 63.86 GB                                 
CPU                 11th Gen Intel Core(TM) i7-11700K 3.60GHz
CUDA                11.7                                     

matplotlib          ✅ 3.4.3>=3.3.0
numpy               ✅ 1.23.1>=1.22.2
opencv-python       ✅ 4.8.0.76>=4.6.0
pillow              ✅ 9.4.0>=7.1.2
pyyaml              ✅ 6.0>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.1>=1.4.1
torch               ✅ 2.0.0>=1.8.0
torchvision         ✅ 0.15.0>=0.9.0
tqdm                ✅ 4.65.0>=4.64.0
pandas              ✅ 1.5.3>=1.1.4
seaborn             ✅ 0.12.2>=0.11.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
```

##### 1. Suggested multiple streams variant:
```
from ultralytics import YOLO

model = YOLO('yolov8m.pt')
source = "camera_streams.streams"

for result in model.track(source=source,
                      show=True,
                      imgsz=[640,640],
                      save_txt=True,
                      save=True,
                      save_conf=True,
                      tracker="botsort.yaml",
                      stream=True,
                      persist=True):
    pass
```
---

##### 2. Threading variant. 
```
from ultralytics import YOLO
from threading import Thread

def thread_safe_track(source):

    model = YOLO('yolov8m.pt')  # Load a custom trained model

    for result in model.track(source=source,
                      show=True,
                      imgsz=[640,640],
                      save_txt=True,
                      save=True,
                      save_conf=True,
                      tracker="botsort.yaml",
                      stream=True,
                      persist=True):
        pass

Thread(target=thread_safe_track, args=("rtsp://310.87.40.210:1965/live/cctv011.stream",)).start()
Thread(target=thread_safe_track, args=("rtsp://310.87.40.210:1965/live/cctv012.stream",)).start()
```

### Additional

Though saved videos (using threading variant) don't play due to erronoues trace stoppage. Pressing `q` on one of the streams stops the coresponding stream and freezes the second (etc.).

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@bit-scientist hello! Thank you for the detailed report.

For the multiple object tracking with multiple streams where IDs are assigned subsequently, it's essential to ensure each stream maintains a unique tracking context. If you're observing that object IDs are not being managed distinctly across streams, then there might be an issue with maintaining separate tracking instances per stream.

Regarding the threading variant issue, terminating one stream by pressing `q` should ideally not affect the other streams. This could be related to how the threads handle the termination signal or how resources are shared on close events. It warrants a closer look to determine how thread-safe operations are being executed and how resources are being cleaned up.

We appreciate your willingness to contribute to fixing these issues. Since this is a community-driven project, input and contributions are highly valued. You can start working on identifying the root cause. Once you've identified a fix, please feel free to submit a PR for review. We'll be happy to work with you on getting the improvements integrated into YOLOv8!

👍 Remember to check the tracking configuration and thread management to solve the problems you've encountered. If you have further inquiries or require additional assistance, please feel free to reach out again.
