### ISSUE TITLE
model.predict() cannot show confidence scores without labels

### ISSUE THREAD

**Issue by chih-yu-chen** [ultralytics/ultralytics#7229]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

Hi,
I am working on single-class object detection and would like to examine the detection bounding boxes with their confidence scores (by saving the images with prediction). Since there is only one class, the labels are not important.

I have tried running the following code snippet in VSCode and in terminal, but neither gives me detection bounding boxes with confidence scores. It results in only plain bounding boxes.

```
from pathlib import Path
from ultralytics import YOLO

model = YOLO("yolov8n.pt")

img_dir = "path/to/images"
img_list = sorted(Path(img_dir).glob("*.jpg"))
results = model.predict(img_list,
                        imgsz=(640,640),
                        conf=.1, iou=.7,
                        save=True,
                        show_labels=False, show_conf=True, line_width=1)
```

Thank you for the support :slightly_smiling_face: 

### Environment

```
Ultralytics YOLOv8.0.230 🚀 Python-3.9.18 torch-2.1.2+cu121 CUDA:0 (NVIDIA GeForce RTX 3060, 12022MiB)
Setup complete ✅ (16 CPUs, 31.3 GB RAM, 75.2/118.6 GB disk)
```

### Minimal Reproducible Example

```
from pathlib import Path
from ultralytics import YOLO

model = YOLO("yolov8n.pt")

img_dir = "path/to/images"
img_list = sorted(Path(img_dir).glob("*.jpg"))
results = model.predict(img_list,
                        imgsz=(640,640),
                        conf=.1, iou=.7,
                        save=True,
                        show_labels=False, show_conf=True, line_width=1)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by RizwanMunawar** [comment]
Thank you, @chih-yu-chen, for providing comprehensive details about the encountered issue! I can replicate the issue.

The latest PYPI Package will address and resolve this issue! Thanks for highlighting the issue👍🏻 

Thanks
Ultralytics Team!

**Comment by chih-yu-chen** [comment]
Thank you @RizwanMunawar for such swift support!
I am looking forward to the release!

**Comment by RizwanMunawar** [comment]
@chih-yu-chen `show_labels` is used for showing the class name and conf and background box behind the class name.
`show_conf` is used to enable/disable the confidence scores when showing labels.

There is no option to show only confidences and not class names, this usage wasn't planned for. So in the current naming convention, "label" means the entire label, which can be entirely enabled or disabled, with `conf` as an element in the label that can optionally be hidden when `show_conf=False`:

- label (enable/disable with show_labels)
- label_solid_color_background_box (always on)
- class_name_text (always on)
- conf_text (enable/disable with show_conf)

Hope this helps! I am closing this issue since it wasn't planned for! Let me know if you have any additional questions.

Thanks and Regards
Ultralytics Team!
