### ISSUE TITLE
yolov5 repo vs ultralytics repo

### ISSUE THREAD

**Issue by aurelm95** [ultralytics/ultralytics#725]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

- Should we use this repo if we want to train and predicit with a yolov5  model or should we keep using the https://github.com/ultralytics/yolov5 repo?

- Will all the features in the https://github.com/ultralytics/yolov5 repo be available in this one? (for example the flask API server https://github.com/ultralytics/yolov5/tree/master/utils/flask_rest_api)

Thanks!

**Comment by JustasBart** [comment]
Hi @aurelm95, generally speaking you should still be using the yolov5 repository as yolov8 is still very much so an angry beehive with changes happening just about on the daily and so if you're doing anything important at all just stick with the yolov5 for now, but otherwise if you're flexible you can give yolov8 a try but without any major expectations.

Once yolov8 reaches the maturity of yolov5 then you can jump ship for good, good luck! :rocket:

**Comment by aurelm95** [comment]
> Hi @aurelm95, generally speaking you should still be using the yolov5 repository as yolov8 is still very much so an angry beehive with changes happening just about on the daily and so if you're doing anything important at all just stick with the yolov5 for now, but otherwise if you're flexible you can give yolov8 a try but without any major expectations.
> 
> Once yolov8 reaches the maturity of yolov5 then you can jump ship for good, good luck! 🚀

Thanks for the clear answer!
