### ISSUE TITLE
Error with embed function while using fastsam with onnx architecture

### ISSUE THREAD

**Issue by aman-agar** [ultralytics/ultralytics#7268]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

As discussed with @glenn-jocher, I am opening a new issue for the same : [here](https://github.com/ultralytics/ultralytics/issues/7223)
```
from ultralytics.models.fastsam import FastSAM, FastSAMPrompt
model = FastSAM('FastSAM-s.onnx')
IMAGE_PATH = 'path/to/images/image.jpg'
embedding = model.embed(IMAGE_PATH)
print(embedding) 
```
![image](https://github.com/ultralytics/ultralytics/assets/108113929/91308472-c3b2-43ac-a69f-b054776196d0)
The onnx version throws an Attribute Error when using the embed function. 
The model is exported through ultralytics itself with the appropriate parameters and in accordance with ultralytics docs.  

When explicitly mentioning the layer number inside the embed function I am getting a static output with size (1,37,8400) unlike fastsam-s.pt model which gives an output with a shape (512) with the same embed function.
![image](https://github.com/ultralytics/ultralytics/assets/108113929/1bd1d9d7-e9dd-4646-a01b-6bacf72cb356)

![image](https://github.com/ultralytics/ultralytics/assets/108113929/5d735c16-8dfb-4fe8-994b-46360dd9f439)

### Environment

Ultralytics YOLOv8.0.232 🚀 Python-3.8.18 torch-2.1.2 CPU (Intel Xeon Gold 6226R 2.90GHz)
Setup complete ✅ (15 CPUs, 43.1 GB RAM, 85.3/387.5 GB disk)

### Additional

The export code used was 
```
from ultralytics import FastSAM
from ultralytics.models.fastsam import FastSAMPrompt
model = FastSAM('FastSAM-s.pt')  # pretrained YOLOv8n model
model.export(format='onnx', opset=13, imgsz=[640,640])
```
No matter what layer number I explicitly mention, I always get the same output from the onnx model. From some digging I found the onnx model has two outputs as suggested [here](https://github.com/ultralytics/ultralytics/issues/4490) So it looks like the embed function is just giving output0 from the onnx model and not any sort of relevant image embedding like the .pt version

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@aman-agar thank you for the detailed issue report. It seems like there's an inconsistency between the ONNX export and the expected behavior of the `embed` function. The static output size you're observing suggests that the export might not be capturing the embedding layer correctly, or the function is not referencing the correct output from the ONNX model.

For the ONNX model, it's important to ensure that the export process is correctly configured to include the embedding layer as an output. The ONNX architecture can differ from the PyTorch `.pt` model, especially in how outputs are handled.

Please verify the export settings and consider revisiting the model architecture to ensure the embedding layer is properly defined and accessible in the ONNX version. If the issue persists, it might require a closer look at the ONNX graph to identify the discrepancy.

If you need further assistance, feel free to provide additional details or ask questions in the issues section, and we'll be glad to help you troubleshoot this further.
