### ISSUE TITLE
Multi Node DDP Support

### ISSUE THREAD

**Issue by ntl-ibm** [ultralytics/ultralytics#7282]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train, Multi-GPU

### Bug

This might be a feature request rather than a bug request, or lack of documentation.
Apologies if it's already on the roadmap.

I have been experimenting with YOLO V8 and multi-node DDP.  (Kubernetes environment).

I dispatch the training across multiple pods, where each pod is allocated one or more GPUs. The command in each pod will be something like: python -m torch.distributed.run train.py
(Environment variables container the information needed to coordinate the DDP worker nodes)

train.py creates and trains a yolo detection model. The dataset is on shared storage, and each pod has the Ultralytics package installed.

Looks something like this:
```
with open("./data.yaml") as f:
    cfg = yaml.safe_load(f)

# Load a model
model = YOLO(cfg.get("model", "yolov8n.pt"))

# Train the model
results = model.train(
    data="./data.yaml",
    cfg="./train.yaml",
)

```

Training fails.  

The root reason is that the yolo code is not implemented to understand LOCAL_RANK, WORLD_SIZE, and RANK correctly. This is likely to also be a problem for SLURM and MPI. 

A good overview of the DDP user case is here:
https://pytorch.org/tutorials/intermediate/ddp_series_multinode.html

Noted issues:
* There is an assumption in ultralytics.engine.trainer.train() that world_size can be computed from the number of GPUs allocated. Since multiple nodes are involved, not all GPUs are visible. There is no relationship between the Rank (of nodes) or WORLD_SIZE and the GPU id(s). 

The method should be looking at the "WORLD_SIZE" environment variable.
Here's the Incorrect code:
```
 def train(self):
"""Allow device='', device=None on Multi-GPU systems to default to device=0."""
        if isinstance(self.args.device, str) and len(self.args.device):  # i.e. device='0' or device='0,1,2,3'
            world_size = len(self.args.device.split(','))
        elif isinstance(self.args.device, (tuple, list)):  # i.e. device=[0, 1, 2, 3] (multi-GPU from CLI is list)
            world_size = len(self.args.device)
        elif torch.cuda.is_available():  # i.e. device=None or device='' or device=number
            world_size = 1  # default to device 0
        else:  # i.e. device='cpu' or 'mps'
            world_size = 0
```

* There are many places where the assumption is made that RANK can be used to determine GPU device. This does not work for multi-node, because there is no relationship to a device on the current node and the number of nodes involved in the training.

There are a bunch of places in the same detection trainer that exhibit this issue.

Looking at version: YOLOv8.0.230 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ntl-ibm hello! Thank you for bringing this to our attention. 🌟

Your detailed explanation helps us understand the issue with multi-node Distributed Data Parallel (DDP) support in YOLOv8. It seems that the current implementation does not fully accommodate the multi-node setup due to assumptions about world size and rank that are specific to single-node multi-GPU environments.

We acknowledge the importance of multi-node DDP for scaling training across clusters, and we appreciate your suggestion to align with the environment variables used by PyTorch's DDP, such as `LOCAL_RANK`, `WORLD_SIZE`, and `RANK`.

This is indeed a valuable feature request and not a bug per se. We will consider it for our roadmap to enhance the scalability of YOLOv8. In the meantime, we welcome contributions from the community, so if you or anyone else is interested in working on this feature, please feel free to discuss it further with us.

For now, please refer to our documentation at https://docs.ultralytics.com for the latest updates and best practices for using YOLOv8.

Thank you for your contribution to the YOLO community and for your patience as we work to improve the framework! 🚀

**Comment by xx025** [comment]
Looking forward to this feature

**Comment by glenn-jocher** [comment]
Thanks for the feedback—multi-node DDP isn’t supported at the moment, and since this issue is closed and marked stale, please open a new issue describing your cluster setup and workflow so we can track demand and design requirements there; we can’t promise timelines, but input like yours helps prioritize future distributed training improvements.
