### ISSUE TITLE
Why use segment model, can't get segments xy real result?  All  xy in mask result  is zero.

### ISSUE THREAD

**Issue by jinneigeyu** [ultralytics/ultralytics#7300]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Why  use segment model, can't get segments xy result?  All  xy in mask result  is zero.
This is the code and output:
```
model = YOLO('yolov8n-seg.pt')
results = model.predict('Images/bus.jpg',device=0,save=True,retina_masks=True,verbose=True)
print(results[0].masks.xy[0])
```

output is :
![image](https://github.com/ultralytics/ultralytics/assets/51145178/9638effb-417f-4cd9-a8c2-2496a55a7ead)

**Comment by jinneigeyu** [comment]
the bus.jpg 
![bus](https://github.com/ultralytics/ultralytics/assets/51145178/c24abd4c-7375-44d9-83df-dfc6860a7b3d)

**Comment by glenn-jocher** [comment]
@jinneigeyu hello! It seems like you're encountering an issue where the segmentation masks are not providing the expected xy coordinates. This could be due to a variety of reasons, such as a problem with the model output or the way the results are being accessed.

To address this, please ensure that you're using the latest version of YOLOv8 and that the model is properly trained for segmentation tasks. If the issue persists, I recommend checking the documentation on segmentation tasks for guidance on how to properly retrieve and interpret the mask results. If you're still facing difficulties, please open an issue on the Ultralytics YOLOv8 repo with detailed information, and we'll be happy to assist you further. 😊
