### ISSUE TITLE
Why my val graphs are empty?

### ISSUE THREAD

**Issue by Jes46** [ultralytics/ultralytics#7311]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi all. I have trained my Yolov8n model to detect Buildings and after training, the 3 val graphs are empty and I don't know why but my model works fine and I want to improve it.
I have used my own dataset and trained with yolov8n.yaml instead of yolov8n.pt in case this could be the cause.

![results](https://github.com/ultralytics/ultralytics/assets/150959706/45c50f1f-602d-4267-a108-c42f4e6853bb)

Thanks.

**Comment by glenn-jocher** [comment]
@Jes46 hello! If your validation graphs are empty after training your YOLOv8 model, it could be due to a few reasons:

1. **No Validation Data**: Ensure you have a validation dataset specified and that it's correctly labeled and formatted.
2. **Improper Paths**: Check your dataset YAML file to confirm that the paths to your validation images and labels are correct.
3. **Training Configuration**: Using a `.yaml` file instead of a `.pt` file for training is fine, but ensure that the `.yaml` file is properly configured with the correct model and dataset parameters.
4. **Logging Issue**: There might be an issue with the logging mechanism. Ensure that the weights and logs are being saved correctly during training.

If the model is performing well, it's possible that the issue is with the visualization rather than the training process. Double-check the steps above and consult the [Train](https://docs.ultralytics.com/modes/train) and [Val](https://docs.ultralytics.com/modes/val) documentation for further guidance. If the problem persists, feel free to open an issue with detailed information about your training setup and any console outputs you may have. 😊

**Comment by Jes46** [comment]
Thanks so much. I'm going to open a issue, It's gonna be better.

**Comment by glenn-jocher** [comment]
@Jes46 you're welcome! Opening an issue with detailed information will definitely help us assist you better. Looking forward to your issue post. 😊
