### ISSUE TITLE
Specify location of coco2017

### ISSUE THREAD

**Issue by stereomatchingkiss** [ultralytics/ultralytics#7342]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Q1 : How to specify the location of the data?

I want to train the yolov8 object detection model on kaggle, using following cmd

```
from ultralytics import YOLO

model = YOLO("yolov8n.yaml")  # build a new model from scratch

# Train the model
results = model.train(data='coco.yaml', epochs=500, imgsz=640)
```

Problem is this solution will always download the coco2017 from scratch, do I have a way to tell the model where to find the downloaded files?

**Comment by glenn-jocher** [comment]
@stereomatchingkiss hello! To specify the location of your COCO dataset and avoid re-downloading, you can modify the `coco.yaml` file to include the paths to your local dataset. In the `coco.yaml`, set the `train`, `val`, and `test` keys to the paths where your COCO images and annotations are stored on Kaggle. This way, when you pass `data='coco.yaml'` to the `model.train()` function, it will use the dataset from the specified location instead of downloading it again. For more details on configuring your dataset, please refer to the documentation at https://docs.ultralytics.com. Happy training! 😊🚀

**Comment by stereomatchingkiss** [comment]
I upload the [coco2017](https://www.kaggle.com/datasets/thamngapwei/coco2017-yolov8) to kaggle, if anyone want to train the yolov8 model from scratch, you do not need to upload the data to kaggle again.

Training yolov8n model by following cmd.

```
!pip install ultralytics
import ultralytics
ultralytics.checks()

from ultralytics import YOLO

model = YOLO("yolov8n.yaml")  # build a new model from scratch

# Train the model
results = model.train(data='/kaggle/input/yolov8-yaml/coco.yaml', epochs=500, imgsz=640)
```

Location of [/kaggle/input/yolov8-yaml/coco.yaml](https://www.kaggle.com/datasets/thamngapwei/yolov8-yaml)

**Comment by glenn-jocher** [comment]
Thanks for sharing the COCO2017 dataset on Kaggle, @stereomatchingkiss! For those looking to train YOLOv8 on Kaggle without re-uploading the data, you can use the provided `coco.yaml` path in the `model.train()` function as shown in your example. This will direct YOLOv8 to use the existing dataset on Kaggle for training. Good luck with your training sessions! 🌟🚀
