### ISSUE TITLE
The inference time of models trained on their own dataset is significantly longer than that of pre trained models

### ISSUE THREAD

**Issue by sjz-hub** [ultralytics/ultralytics#7351]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I converted the pre trained YOLOv8n.PT model to Coreml and the detection model trained on my own dataset to Coreml. The inference time difference between the two is very large, with a difference of twice. I want to know why this is?
![image](https://github.com/ultralytics/ultralytics/assets/64513299/405e4682-21e8-457e-a9f8-42e2974bd1dc)

![image](https://github.com/ultralytics/ultralytics/assets/64513299/919cf008-0d02-4b1a-8243-5fcd85074c17)

The first image shows the inference time after converting the pre trained detection model I downloaded to Coreml, and the second image shows the inference time after converting the detection model trained on my own dataset to Coreml, both of which are n-models. I feel very surprised by this phenomenon. Is it because there is some extra content in the model I trained, which leads to a very long inference time? How can I solve this problem?

**Comment by glenn-jocher** [comment]
@sjz-hub it's not uncommon to observe differences in inference times between pre-trained models and those trained on custom datasets. This can be due to various factors such as model complexity, the number of classes, differences in optimization, or even the conversion process to CoreML. To address this:

1. Ensure that both models have the same architecture and number of classes.
2. Check if additional layers or operations were introduced during training.
3. Verify that the optimization steps post-training were consistent for both models.
4. Consider re-exporting your custom-trained model to ensure the conversion process is error-free.

For a more detailed investigation, you might want to benchmark your custom model using the Benchmark mode and compare it with the pre-trained model's benchmark results. If the issue persists, please provide more details in the issue tracker for further assistance. 🚀

**Comment by glenn-jocher** [comment]
@sjz-hub, the discrepancy in inference times could be influenced by the difference in the number of classes between the two models. Even though your custom model has fewer classes, it's possible that the model conversion process or the CoreML runtime is not fully optimized for models with a reduced class count. To troubleshoot further:

- Confirm that both models are using the same version of the conversion tools and libraries.
- Check if the CoreML runtime is optimized for single-class detection scenarios.
- Review the post-training optimization steps for your custom model to ensure they align with those used for the pre-trained model.

If the issue remains unresolved, consider providing detailed information on the training and conversion process in the issue tracker for more specific guidance. 🛠️

**Comment by glenn-jocher** [comment]
@sjz-hub to ensure the post-training optimization steps are consistent, you can:

1. Review the training logs or configuration files for any optimization flags or settings used during the training of your custom model.
2. Compare these settings with the default configurations used for the pre-trained models, which are typically documented or can be inferred from the model's training script.

If discrepancies are found, adjust your custom model's training configuration to match the pre-trained model's settings. 🛠️
