### ISSUE TITLE
Multiple bounding boxes in dataset labels for pose landmark estimation

### ISSUE THREAD

**Issue by kill-o-zap** [ultralytics/ultralytics#7369]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I have a problem with dataset labels when trying to run YOLOv8 pose landmark program on google colab. The problem arises from the dataset itself that I've written. 
I have an image and on this image I would like to have multiple bounding boxes (example 4) and in each bounding box I have 6 points. 
So I constructed my dataset labels for this specific image like the following:
![dataset_example](https://github.com/ultralytics/ultralytics/assets/154071253/5a193b3e-9db7-4c09-8ed6-9b795c30676a)

And I have the following yaml for keypoints and classes:
![yaml_example](https://github.com/ultralytics/ultralytics/assets/154071253/385ae0de-5698-41f4-935a-a711ed289701)

When I run the program the it shows that the labels are corrupeted
The questions would be: 
1. Is the before mentioned example of labels correct?
2.  If I have multiple pictures that differentiate in number of classes and number of points do I have to add zeros for the number of points and classes so the structure is the same?
3. Is the example of yaml correct for this case?

Thank you for all the help.

**Comment by glenn-jocher** [comment]
@kill-o-zap hello!

For pose landmark estimation with YOLOv8, it's crucial that the dataset labels are formatted correctly. Each bounding box should be accompanied by the keypoints in a specific structure. If the labels are reported as corrupted, it usually indicates a mismatch between your dataset format and the expected format.

1. Ensure that each image's label file contains the bounding box coordinates followed by the keypoints, all normalized to the image size.
2. The dataset should be consistent. If images have a varying number of keypoints, you may need to pad them with zeros, but this should be done carefully to maintain the integrity of the data.
3. Your YAML file should accurately reflect the classes and keypoints for your task. Ensure that the number of classes and keypoints in the YAML matches your dataset.

For detailed guidance on the correct label and YAML formats, please refer to the Pose/Keypoint Estimation documentation. If issues persist after verifying the format, consider sharing a snippet of your label file and YAML (without images) in the discussions for further assistance.

Best of luck with your pose estimation project! 😊

**Comment by kill-o-zap** [comment]
@glenn-jocher  hello!

I have always written the dataset labels as pictured above so 0.0 (or 1.0 or 2.0 for the class type if I understand correctly) followed by the 4 bounding box parameters and followed by the points parameters. I've normalized the values to the image I used.
I've tried multiple examples like:
1. create a dataset with 1 bounding box and 6 landmarks and it worked.
2. create a dataset with 1 bounding box and X amount of landmarks where I've added 0 to satisfy the yaml rule for landmarks of value X. It worked but the learning of YOLOv8 pose did not produce the results I wanted. The problem was in the dataset.

The problem is that I have searched for examples of this kind of dataset and did not find any.
I will add the yaml I use for this example and the label example for 4 bounding boxes and 24 landmarks all together. 
I've named labels to represent what they contain for ease of use.
[labels_example_4BB_24_points.txt](https://github.com/ultralytics/ultralytics/files/13853554/labels_example_4BB_24_points.txt)
[yaml_example.txt](https://github.com/ultralytics/ultralytics/files/13853555/yaml_example.txt)
[labels_example_1BB_6_points.txt](https://github.com/ultralytics/ultralytics/files/13853556/labels_example_1BB_6_points.txt)

Thank you very much for your help.

**Comment by glenn-jocher** [comment]
@kill-o-zap-zap, it sounds like you're on the right track with normalizing the values and structuring your labels. Here are a few concise pointers:

1. Ensure each label file follows the format: class, bounding box coordinates, and then keypoints, all normalized.
2. If you have varying numbers of keypoints, the dataset must be consistent. Padding with zeros is an option, but it must be done in a way that doesn't confuse the model.
3. Review your YAML to ensure it matches the structure and counts of your dataset.

For datasets with multiple bounding boxes and keypoints, ensure that each bounding box and its associated keypoints are listed sequentially in the label file. If the learning isn't producing desired results, it may be due to the way the dataset is structured or the model's learning capacity for complex tasks with multiple keypoints.

For further assistance, please refer to the Pose/Keypoint Estimation documentation and consider sharing your label and YAML structure in the discussions for community and team support.

Keep up the good work, and I hope your model's performance improves with these adjustments! 😊
