### ISSUE TITLE
Yolov8 Evaluation

### ISSUE THREAD

**Issue by hdd0510** [ultralytics/ultralytics#7374]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have do the evaluation of the yolov8 on my dataset which has 2 classes and get the AP
![image](https://github.com/ultralytics/ultralytics/assets/109750432/8e094baf-bf80-49ca-8631-4b75fe9255e0)
![image](https://github.com/ultralytics/ultralytics/assets/109750432/ca205750-682a-4cd0-b507-e496d7cf913c)
I wonder why there are differences between COCOeval evaluation and the one of yolov8 API?

**Comment by glenn-jocher** [comment]
@hdd0510 hello! It's great to hear that you're evaluating YOLOv8 on your custom dataset. The differences you're observing between COCOeval evaluation and the YOLOv8 API evaluation could be due to a few reasons:

1. **Metric Calculation**: The YOLOv8 API may use slightly different methods for calculating metrics like AP, which could lead to variations.
2. **Thresholds**: Differences in confidence or IoU thresholds between the two evaluation methods can affect the results.
3. **Data Processing**: The way data is preprocessed and fed into the model during evaluation might differ, impacting the outcome.

For a detailed understanding of how YOLOv8 calculates evaluation metrics, you can refer to our documentation on the [Val mode](https://docs.ultralytics.com/modes/val). If you need further clarification or assistance, feel free to reach out to the community on our discussions page. Keep up the good work! 😊🚀

**Comment by Johnny-zbb** [comment]
@hdd0510 Hi! May I ask what iou and conf parameters you are using?
