### ISSUE TITLE
Code using ultralytics fails pyinstaller packaging.

### ISSUE THREAD

**Issue by princess995** [ultralytics/ultralytics#7397]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

https://github.com/princess995/image_count_v1
This is the project I created. Download it and run the packaging.

An error occurs: "Failed to execute script 'image_count'due to unhandled exception: 'NoneType' object has no attribute 'encoding'.

I haven't been able to solve this for a week.

I referred to the article on YoloV8 deploy (EXE/WINDOWS) https://github.com/orgs/ultralytics/discussions/1356 because it seemed to be the error that most suited me, but it also failed.

Please help someone succeed in packaging.

**Comment by HendrikMeininger** [comment]
This error probably occurs, because you are trying to create a .exe that does not open a terminal.

If you do that your python standart output (sys.std_out) in None.
Ultralytics tries to read some properties from your sys.std_out object, thats why you get this exception.
(see ultralytics.utils.__init__.py set_logging())

You can fix this by either defining your own standart output (for example if you want to log some information, errors, ...). 
Or just discard everything written to sys.std by adding :

```
sys.stdout = open(os.devnull, "w")
sys.stderr = open(os.path.join(os.getenv("TEMP"), "stderr-"+os.path.basename(sys.argv[0])), "w")
```

before your code.
