### ISSUE TITLE
Inconsistent object detection when using different sources

### ISSUE THREAD

**Issue by Justin-Ong** [ultralytics/ultralytics#7427]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I have trained a custom model for object detection, and it is working well when I use images and videos to test it, detecting the object almost all the time and usually with confidence greater than 0.9. However, when attempting to use source='screen', the confidence values drop dramatically (to around 0.5-0.7) and the detection is very noticeably worse as it sometimes fails to detect the object.

This is the case even when using the exact same video to test it, just that one method is to use cv2 to read in the video file, and the other is to play the video file on the screen with the model running.

Afterwards, as a test, I used PyAutoGUI to constantly take screenshots and feed those screenshots to the model, and that returned good results.

I also tried using dxcam and d3dshot for screenshots, but that returned poor results similar to when I used source='screen'.

### Environment

Ultralytics YOLOv8.0.235 🚀 Python-3.10.1 torch-2.1.2+cu121 CUDA:0 (NVIDIA GeForce RTX 3070, 8192MiB)
Setup complete ✅ (12 CPUs, 31.8 GB RAM, 742.4/930.9 GB disk)

### Minimal Reproducible Example

https://pastebin.com/C6pc5BJh

### Additional

The script uses multiprocessing, 1 process runs the model and feeds it data, and the other process draws on the screen. I have provided just the part that runs the model. I have only provided PyAutoGUI and source='screen' examples, as those are the most relevant to my specific case, but the examples can be easily adapted to use other screenshot-taking packages too.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Justin-Ong hello! Thank you for the detailed report. It's interesting that you're experiencing inconsistent detection performance with different sources, especially between direct video file input and screen capture methods.

The discrepancy in confidence scores and detection quality when using `source='screen'` could be due to several factors, such as variations in screen resolution, color depth, or frame rate compared to the original video file. Screen capturing methods might introduce artifacts or compression that affect the model's ability to detect objects accurately.

Since you've mentioned that using PyAutoGUI to take screenshots yields better results, it suggests that the issue might be related to how the screen is being captured in real-time. Real-time screen capture can be less consistent in quality compared to static screenshots.

To troubleshoot this, you could:
- Ensure that the screen capture resolution matches the resolution used during training.
- Check if there's any compression or color space conversion happening during screen capture that might affect detection.
- Experiment with different screen capturing libraries to see if one provides more consistent results with your model.

If the issue persists, consider providing more details on the screen capture setup or any preprocessing steps you're applying to the captured frames. This might help in identifying the root cause of the performance inconsistency.

**Comment by Justin-Ong** [comment]
Ok, I've figured it out. No bug here, just me assuming and getting bitten for it. There were 2 different problems occurring:

1. Using `source='screen'` resulted in both of my monitors being captured and combined into a single image, hence the width was doubled as compared to the width of the training images. I went back to check the docs, and they don't state this behaviour (capturing multiple monitors into one image). It would be good to add a note on this to the docs, I think.

2. After using `cv2.imshow()`, I realised that while PyAutoGUI was taking screenshots in RBG, DXCam was recording the images as BGR. This caused the model to be unable to process the images correctly. Setting DXCam to use `output_color='BGR'` flipped the image to RGB again, allowing the model to work correctly. I don't know enough about this topic to understand why, though.

Thanks for your time.

**Comment by glenn-jocher** [comment]
@Justin-Ong, great to hear you've resolved the issues! Your feedback is valuable:

1. The behavior of `source='screen'` capturing multiple monitors is indeed not explicitly documented. We'll consider adding a note to clarify this in the documentation to assist future users.

2. The color space discrepancy between RGB and BGR can significantly impact model performance, as the model expects input in the color space it was trained on. This is a common source of confusion, and your experience highlights the importance of ensuring consistency in preprocessing steps.

Thank you for bringing these points to our attention, and I'm glad you were able to troubleshoot effectively. Happy detecting! 🚀
