### ISSUE TITLE
Tensorflow Lite int8 inference slower than fp32

### ISSUE THREAD

**Issue by Skillnoob** [ultralytics/ultralytics#7445]
(edited to include information from comments)
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Val, Predict

### Bug

After exporting the yolov8n model to fully quantized tensorflow lite the quantized model ends up with the same if not slower inference speed than the fp32 model even though the quantized model should be much faster.
Previously the quantized model was much faster and averaged ~135ms/img (may be off due to me having to recall the number because i sadly don't have a saved val run when it was still working well).
I've tried a few older versions of ultralytics and it didn't resolve the issue even with uninstalling everything tflite export related and letting ultralytics install the correct requirements.
Exporting on colab and then running the quantized model on the pi 5 doesn't resolve the issue.
I've also tried the tflite int8 example script in this repo and that also doesn't work correctly.
All results are verified to be the same on a 2nd raspberry pi 5.
The current val numbers can be found in the table below.

| Model| Inference ms/img|
| --- | ----------- |
| yolov8n_float32.tflite| 395.2|
| yolov8n_full_integer_quant.tflite| 403.9|

Graph by me where the previous int8 inference speed is visible (Tensorflow Lite label)
![model_format_comparison](https://github.com/ultralytics/ultralytics/assets/78843978/913825db-6f54-40f8-9d7e-9fcf677ff2ac)

### Environment

(Running on a raspberry pi 5)

Ultralytics YOLOv8.0.238 🚀 Python-3.11.2 torch-2.1.1 CPU (Cortex-A76)
Setup complete ✅ (4 CPUs, 7.9 GB RAM, 27.7/116.7 GB disk)

OS                  Linux-6.1.0-rpi7-rpi-2712-aarch64-with-glibc2.36
Environment         Linux
Python              3.11.2
Install             pip
RAM                 7.86 GB
CPU                 Cortex-A76
CUDA                None

matplotlib          ✅ 3.8.1>=3.3.0
numpy               ✅ 1.24.3>=1.22.2
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.28.1>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.1.1>=1.8.0
torchvision         ✅ 0.16.1>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.7
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0

tensorflow-aarch64==2.13.1
tflite-runtime==2.14.0
onnx2tf==1.17.5
onnxsim==0.4.33

### Minimal Reproducible Example

```
yolo export model=yolov8n.pt format=tflite data=coco128.yaml int8

yolo detect val model=yolov8n_saved_model/yolov8n_float32.tflite data=coco128.yaml batch=1

yolo detect val model=yolov8n_saved_model/yolov8n_full_integer_quant.tflite data=coco128.yaml batch=1
```

### Additional

If any more information is required then I'd gladly supply that to resolve this issue

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Skillnoob** [comment]
Fyi exporting on colab and then running the quantized model on the pi 5 doesn't resolve the issue

**Comment by glenn-jocher** [comment]
@Skillnoob it's intriguing that you're experiencing slower inference times with the int8 quantized model compared to the fp32 model on your Raspberry Pi 5. This is not the expected behavior, as quantized models are typically faster due to reduced precision operations.

A few factors could be contributing to this issue:

1. **Hardware Acceleration**: Ensure that your Raspberry Pi's hardware is optimized for int8 operations. Some hardware may not fully support int8 acceleration, which could lead to slower inference times.

2. **Software Dependencies**: Verify that all software dependencies, particularly those related to TensorFlow Lite, are up-to-date and compatible with int8 quantized models.

3. **Model Optimization**: Sometimes, the process of quantization can introduce overhead that negates the speed benefits. This can be due to the model's architecture or the quantization method used.

4. **Benchmark Variability**: Ensure that the benchmarking process is consistent and accounts for any variability in system load or background processes.

5. **TensorFlow Lite Version**: Different versions of TensorFlow Lite may have varying levels of support and optimization for quantized models. Experimenting with different versions could yield different performance results.

If you continue to face this issue, consider opening an issue on the YOLOv8 GitHub repository with detailed information about your setup and the steps you've taken. The community and maintainers can then collaborate to investigate further. Remember to check the [Ultralytics Docs](https://docs.ultralytics.com) for any updates or guidance on model export and inference.

**Comment by Skillnoob** [comment]
@glenn-jocher heres some more information:
tensorflow-aarch64==2.13.1
tflite-runtime==2.14.0
onnx2tf==1.17.5
onnxsim==0.4.33

Maybe i should have made it clearer that int8 worked correctly before (~month ago) and now doesn't.
Before it was running at ~7.4it/s which is around 135ms/it where the ~400ms/it are a massive slowdown.
I found a comparison graph i made a while back where it still worked correctly and the int8 speed can roughly be read from there (Tensorflow Lite label).
![model_format_comparison](https://github.com/ultralytics/ultralytics/assets/78843978/0de82da5-fd4e-49fa-8d3e-5b2d0931e58c)

**Comment by Skillnoob** [comment]
I have just tried the tflite int8 example script to test on a video and the inference speed was the same as the current val runs

**Comment by glenn-jocher** [comment]
@Skillnoob it's quite unusual for the int8 model to perform similarly to the fp32 model, especially since you've previously experienced better performance with int8. This consistency between the example script and your current validation runs suggests that the issue might not be with the model itself, but possibly with the environment or the TensorFlow Lite runtime.

Given that int8 quantization was faster in the past, you might want to consider the following steps:

- **Revisit Changes**: Review any changes in your environment or the TensorFlow Lite runtime since the time int8 was performing well.
- **TensorFlow Lite Version**: Downgrade TensorFlow Lite to the version you were using when int8 quantization provided the expected speedup.
- **Hardware Check**: Double-check that your Raspberry Pi's hardware is functioning correctly and that there haven't been any changes that could affect performance.

If the issue persists, please report this with all the relevant details on the YOLOv8 GitHub repository so that the team can look into it. Your findings, especially the comparison graph and the previous versions that worked, will be valuable for troubleshooting.

**Comment by Skillnoob** [comment]
@glenn-jocher since the last time it worked i can't remember what exactly is different other than me updating ultralytics and related libararies.
There is only one available tflite-runtime version and i cannot test with any other than the most recent one.
To your last suggestion i have a 2nd raspi 5 and ran the same script on that pi and it resulted in the same results.

**Comment by Skillnoob** [comment]
Also why are you suggesting i should open a github issue in the yolov8 repository when this is a issue in that repo??

**Comment by glenn-jocher** [comment]
Apologies for any confusion, @Skillnoob. Since you've already tried different Raspberry Pi units and ruled out hardware issues, and considering you're using the latest libraries, it seems we're looking at a software-related problem that might be tied to recent updates.

Given that you've updated the Ultralytics repository and related libraries, it's possible that changes in the codebase or dependencies could be affecting the performance of the int8 quantized models. It's also worth noting that TensorFlow Lite's performance can vary with different versions, even if only one version is currently available for your platform.

Since this is an issue that has arisen after updates and is reproducible on multiple devices, I recommend documenting the behavior with as much detail as possible, including the versions of the libraries when it was last working correctly, and any other relevant information. This detailed report will be crucial for the Ultralytics team to investigate the regression in performance.

As for the GitHub issue, my intention was to ensure that you have all the necessary support from the community and the maintainers. If you haven't already, please update your existing issue with this new information so that it can be addressed appropriately. Your contributions are valuable to the continuous improvement of the project. Thank you for your diligence in this matter.

**Comment by Skillnoob** [comment]
@glenn-jocher I've tested version 8.0.100 and 8.0.150 and 8.0.193 (i think this is the one which last worked) and on none of the versions it seemed to work correctly even after retraining the model on those versions seperatly

**Comment by glenn-jocher** [comment]
@Skillnoob, thank you for the additional testing across different versions. It's quite puzzling that reverting to previous versions where int8 quantization worked did not resolve the issue. This suggests that the problem may not solely lie within the Ultralytics codebase. It could be related to external dependencies or the TensorFlow Lite runtime itself.

Please ensure that you've also reverted any related libraries to the versions that were in use when int8 quantization was last working correctly. If the issue persists even after this step, it would be helpful to document this behavior in detail, including the specific versions of all relevant libraries, and update your existing GitHub issue. The Ultralytics team will need this information to further investigate and address the performance regression. Your efforts to pinpoint the problem are greatly appreciated.

**Comment by Skillnoob** [comment]
@glenn-jocher i used pip-autoremove to uninstall any related library from the system when switching versions and had ultralytics auto install the required versions.
The versions used can be found in previous comments for the current val runs

**Comment by Skillnoob** [comment]
@glenn-jocher I've updated the initial comment to include the all the information

**Comment by nlbutts** [comment]
You should try the ARMNN TFLite delegate:
https://github.com/ARM-software/armnn

Then in your code you you need to load the delegate. This presentation shows how. 
https://static.linaro.org/connect/lvc21/presentations/lvc21-113.pdf

This is the performance I get with the delegate on an RPI4.

| Device | Model                | Type  | Size | Framework | FPS  |
|--------|----------------------|-------|------|-----------|------|
| RP4    | ssd_mobilenet_v1_12-int8  | int8  | 320  | onnx      | 11.7 |
| RP4    | yolov5n              | int8  | 640  | onnx      | 2.8  |
| RP4    | yolox                | fp32  | 416  | onnx      | 6.5  |
| RP4    | nanodet              | fp32  | 330  | tflite    | 10.6 |
| RP4    | yolov5n              | int8  | 640  | tflite    | 5.2  |
| RP4    | yolox-nano           | int8  | 416  | tflite    | 9.3  |
| RP4    | EfficientDet-Lite0   | int8  | 320  | tflite    | 10.8 |
| RP4    | yolov8n              | int8  | 640  | tflite    | 3.9  |

**Comment by glenn-jocher** [comment]
@nlbutts thanks for the suggestion and the valuable resources! 🚀 The ARMNN TFLite delegate indeed looks promising for optimizing inference on ARM architectures, and the performance metrics you've shared are quite insightful.

For those interested in integrating the ARMNN delegate with their TFLite models, here's a quick snippet on how you might load the delegate into your TFLite inference code:

```python
import tensorflow as tf

# Load the TFLite model
interpreter = tf.lite.Interpreter(model_path="your_model.tflite")

# Load the ARMNN delegate
armnn_delegate = tf.lite.experimental.load_delegate('libarmnnDelegate.so')

# Allocate tensors using the ARMNN delegate
interpreter.allocate_tensors(armnn_delegate)
```

Make sure to replace `"your_model.tflite"` with the path to your actual TFLite model file and ensure that the ARMNN delegate library path is correct. This approach should help leverage ARMNN optimizations for improved inference performance on Raspberry Pi devices.

It's great to see the community sharing such useful tips and benchmarks! Keep experimenting and sharing your findings. 🌟
