### ISSUE TITLE
Process finished with exit code 137 (interrupted by signal 9: SIGKILL)

### ISSUE THREAD

**Issue by suhyeong-jeon** [ultralytics/ultralytics#7471]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello I'm using yolov8 but I got an issue.

I'm using 1000 images(324MB) to train and 100 images(66.8MB) to validate and 
but I got 'Process finished with exit code 137 (interrupted by signal 9: SIGKILL)' error while the program is running around epoch=4 or 5.

I did set imgsz 224 and batch 4 device=mps but it happens again.

<img width="945" alt="image" src="https://github.com/ultralytics/ultralytics/assets/70623959/f2255bd5-2d0c-4040-95ed-7c5d0a9a2951">

Also according to activity monitor the memory of python3.10 increases to 45GB and then I got the exit code 137 error.

Are there any solutions?

Thank you. 

I'm using Apple M1 Pro, 8GB RAM
ultralytics 8.1.0
torch 2.1.0
python 3.10

**Comment by glenn-jocher** [comment]
@suhyeong-jeon hello! The exit code 137 typically indicates that your process was killed due to running out of memory. Since you're using an Apple M1 Pro with 8GB RAM and the memory usage spikes to 45GB, it's likely that your system is terminating the training process to prevent memory overflow.

To address this, consider the following:
- Reduce the `imgsz` further if possible, as smaller images will require less memory.
- Lower the `batch size` even more, though this might impact the training stability.
- Close other applications to free up RAM before starting the training.
- Use a machine with more RAM if the above adjustments don't help.

Keep an eye on the memory usage as you make these changes to ensure it stays within the available limits. For more detailed guidance on memory management and training, please refer to our documentation on [Train](https://docs.ultralytics.com/modes/train) mode. Good luck! 🚀

**Comment by suhyeong-jeon** [comment]
@glenn-jocher Thank you for the suggestions. As you suggested, I changed my code to batch=1, imgsz=160.
But as you can see the picture of my activity monitor, the memory of python3.10 keeps increasing.

Are they any other suggestions? I thought it was because of yolov8 memory leak.

I really appreciate it.

<img width="953" alt="image" src="https://github.com/ultralytics/ultralytics/assets/70623959/f5ebeb21-a2fe-4485-ac66-eab8edebaf3a">

**Comment by glenn-jocher** [comment]
@suhyeong-jeon, it's great to hear that you've tried reducing the `batch size` and `imgsz`. If memory usage is still increasing, it could be due to caching mechanisms or other factors rather than a memory leak. Here are a few more suggestions:

- Ensure you're using the latest version of the Ultralytics YOLOv8 repository, as updates often include performance improvements and bug fixes.
- Monitor the system for other processes that might be consuming memory.
- Try restarting your machine to clear any residual memory usage before training.
- If the issue persists, consider opening an issue on the Ultralytics YOLOv8 repo with detailed information so the community can investigate further.

Remember, managing memory on systems with limited resources can be challenging, but we're here to help. Thanks for your continued efforts! 🌟
