### ISSUE TITLE
getting coordinates while live streaming or in real time?

### ISSUE THREAD

**Issue by tanu-04** [ultralytics/ultralytics#7480]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am working on yolov8 detection and getting coordinates>>>>
I am getting the coordinates in a folder of images saved in a text file through this -
from ultralytics import YOLO

model = YOLO("/home/tanu/Desktop/me/predicts/all(train71)/weights/best.pt")

try:
    with open('/home/tanu/Desktop/yolov8/me/new1/log.txt', 'a') as log_file:
        log_file.write("Starting object detection process...\n")

        results = model.predict(source='/home/tanu/Desktop/yolov8/camera', project='/home/tanu/Desktop/yolov8/me/new1', name='test1', exist_ok=True, save_crop=True)

        for i, result in enumerate(results):
            log_file.write(f"Processing result {i}\n")
            for j, box in enumerate(result.boxes):
                log_file.write(f"Processing box {j}\n")
                class_name = result.names[box.cls[0].item()]
                coords = box.xyxy[0].tolist()
                coords = [round(x) for x in coords]
                center_x = (coords[0] + coords[2]) / 2
                center_y = (coords[1] + coords[3]) / 2

                # Log coordinates to the log file
                log_file.write(f"Object type: {class_name}, Center_X: {center_x}, Center_Y: {center_y}\n")

except Exception as e:
    print(f"Error occurred: {e}")

but I want this file to get updated with the coordinates while live streaming itself.

**Comment by glenn-jocher** [comment]
@tanu-04 hello! It's great to see you're using YOLOv8 for object detection. To update your log file with coordinates in real-time during a live stream, you'll want to modify your code to process the video stream frame by frame. Instead of using the `predict` method on a static source, you should capture frames from your live stream and pass each frame to the model for prediction.

For each frame, you can then extract the bounding box coordinates, calculate the center points, and write them to your log file as you're currently doing with static images. This way, your log file will be updated continuously as the stream is being processed.

Remember to handle the stream appropriately, ensuring that it's open and reading frames correctly, and to manage the file writing so that it doesn't become a bottleneck in your real-time processing.

For more details on working with different modes and tasks in YOLOv8, you can refer to our documentation at https://docs.ultralytics.com. Keep up the good work, and if you have further questions, feel free to reach out! 😊🚀

**Comment by tanu-04** [comment]
@glenn-jocher thank you for helping out .

**Comment by glenn-jocher** [comment]
@tanu-04 you're welcome! If you have any more questions, feel free to ask. Happy coding! 😊👍
