### ISSUE TITLE
YOLOv8 for single object tracking

### ISSUE THREAD

**Issue by manojgali** [ultralytics/ultralytics#7484]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

HI, Ultralytics team. thank you for the wonderful API. 
I am developing an surveillance system, where I need to track all the targets from the continuous camera feed  and then based on the user input (track id from MOT) system need to track that particular target. YOLOv8 results are satisfactory for my application in MOT but i got struck in the transition from MOT to SOT.  I am using opencv to read the video and in while loop i am not able to give keyboard interput to select id from MOT .I want to give interupt only once but the approach ive chosen  is recitative any suggestion from here. I am attaching my code  snippet

```
import cv2
from ultralytics import YOLO

# Load the YOLOv8 model
model = YOLO('./model/best_400.pt')

# Open the video file
video_path = "path/to/video.mp4"
cap = cv2.VideoCapture(video_path)

# Loop through the video frames
while cap.isOpened():
    # Read a frame from the video
    success, frame = cap.read()

    if success:
        # Run YOLOv8 tracking on the frame, persisting tracks between frames
        results = model.track(frame, persist=True)

        # Visualize the results on the frame
        annotated_frame = results[0].plot()

        # Display the annotated frame
        cv2.imshow("YOLOv8 Tracking", annotated_frame)


        # Break the loop if 'q' is pressed
        if cv2.waitKey(1) & 0xFF == ord("s"):
            value = int(input()) 
            break
    else:
        # Break the loop if the end of the video is reached
        break

# Release the video capture object and close the display window
cap.release()
cv2.destroyAllWindows()
```

Thank you

**Comment by glenn-jocher** [comment]
@manojgali hello! I'm glad to hear that YOLOv8 is working well for your surveillance system's multi-object tracking (MOT) needs. For transitioning from MOT to single-object tracking (SOT) based on user input, you might consider a different approach to avoid interrupting the video feed loop.

Instead of waiting for keyboard input within the loop, you could initially display the tracked objects with their IDs and then pause the loop to allow the user to select an ID. Once the ID is selected, you can resume the loop and filter the tracking results to only update and display the chosen target.

To implement this, you could set up a separate event or callback function that handles user input asynchronously, or use a flag to indicate when to pause for input. This way, you can avoid the repetitive interruption and make the user interaction more seamless.

Remember to handle the user input outside the main video processing loop to maintain the real-time tracking performance. Good luck with your project! 🚀

**Comment by glenn-jocher** [comment]
Hello @manojgali, I'm glad to hear you've implemented flags for SOT. To address your concerns:

1. To avoid pausing the video, consider using a separate thread or process to handle user input for SOT selection. This allows the video to play continuously while waiting for user input.
2. If the video isn't playing continuously, ensure that your flag-checking logic doesn't inadvertently pause or slow down the frame processing. The video feed should run independently of the SOT selection process.

Keep refining the logic to ensure smooth video playback and responsive user input handling. 🛠️
