### ISSUE TITLE
Package without Nvidia drivers

### ISSUE THREAD

**Issue by rusmux** [ultralytics/ultralytics#749]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Add a version of the package without Nvidia drivers. Currently, when installing `ultralytics` on Linux, Nvidia drivers are also installed, however, there are no GPUs on my machine.  In addition, it significantly increases the size of Docker images that are supposed only to run on the CPU.

<img width="956" alt="Screenshot 25" src="https://user-images.githubusercontent.com/85135806/215991133-3bdc37df-2567-42b7-880f-ea4cfcf025a0.png">

### Use case

Downloading `ultralytics` on CPU-only machines. Building Docker images without GPU support.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by rusmux** [comment]
@AyushExel Well, not docker image maybe, but a **package** version? Like `pip install torch==1.13.1+cpu`. Because docker images can contain dependencies what one won't need.

**Comment by glenn-jocher** [comment]
@stefan-veriphy thanks for bringing this to our attention. It's a valid point you've raised and reducing the size of Docker containers for CPU-only machines is something we understand would be beneficial, especially for use cases like executing on AWS Lambda, where storage size might be more limited.

Please note that currently, our releases do include Nvidia drivers due to their broad use in GPU-accelerated machine learning workloads. However, we're taking your suggestion of a CPU-only version into consideration. It may involve updates to our packaging and distribution approach to allow the installation of separate packages for environments with and without GPUs.

While we review this suggestion and its technical implications on our end, you can manually prune the CUDA components from the Docker image post-installation as a workaround. That being said, we understand this is not an ideal solution, especially when dealing with automated deployment pipelines.

Your feedback is greatly appreciated, and we thank you for your contribution to the YOLOv8 community.

**Comment by woerstcase** [comment]
Hello glenn-josher,

I want to run it in an Edge Device without GPU. 

so if make my docker compose file I add something like:# Install Python dependencies
RUN pip3 install -r requirements.txt \
    # Prune CUDA-related components
    && rm -rf /usr/local/cuda/ \
    && rm -rf /usr/local/nvidia/ \
    # Clean up pip cache
    && rm -rf /root/.cache/pip

or is there a better workaround.
best regards David

**Comment by woerstcase** [comment]
@stefan-veriphy I installed an Ultralytics without any dependencies and the installed the ones I need in my requirements file.
Now the size of the image is around 2GB

**Comment by glenn-jocher** [comment]
@woerstcase, I'm glad you were able to significantly reduce the size of the image. Your workaround of installing Ultralytics without dependencies and then manually adding the ones you need is a clever solution. This allows you to avoid unnecessary components, especially helpful for CPU-based systems where GPU-related resources are not used. 

Remember to consider dependencies carefully, to prevent missing any that might be vital for your particular use case. Bear in mind also that the dependencies might be updated in future releases of Ultralytics.

Thank you for sharing this solution with the community. It can certainly be valuable for other users in similar situations looking to optimize their deployments.

**Comment by daniel-manickam** [comment]
@woerstcase - could you please let me know how you installed Ultralytics without any dependencies and the installed the non-cuda files via requirements file?

**Comment by daniel-manickam** [comment]
@woerstcase - could you please let me know how you installed Ultralytics without any dependencies and the installed the non-cuda files via requirements file?

**Comment by woerstcase** [comment]
I think this will help. Instead of installing ultralytix with the requirements I installed it with the docker-file.

Setup:
Debian Edge Device(Intel) without GPU

This is my requirements file:
opencv-python-headless==4.8.1.78
numpy==1.26.0
matplotlib>=3.3.0
opencv-python>=4.6.0
pillow>=7.1.2
pyyaml>=5.3.1
requests>=2.23.0
scipy>=1.4.1
tqdm>=4.64.0
pandas>=1.1.4
psutil
dill
py-cpuinfo

and this line added in my dockerfile:
#Install torch and torchvision CPU only versions
RUN pip3 install torch==1.8.0+cpu torchvision==0.9.0+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html

#Explicitly install ultralytics without optional dependencies (like CUDA).
RUN pip3 install ultralytics==8.0.200 --no-deps

best regards
woerstcase

**Comment by daniel-manickam** [comment]
@woerstcase - thank you! Reduced the image size to 3 GB..

**Comment by glenn-jocher** [comment]
@daniel-manickam it's terrific to hear that the modified installation process reduced your Docker image size to 3 GB, offering a more optimized solution for deployment on CPU-only devices like your Intel-based Edge Device.

When deploying models in resource-constrained environments, considering the minimal requirements and avoiding unnecessary dependencies is crucial. This approach not only reduces the image size but may also lead to faster deployment times and efficient resource utilization.

Your collaborative effort in refining the installation process and sharing the outcomes is a testament to the power of the community in improving the YOLOv8 project. Others facing similar constraints would likely benefit from this exchange and adopt similar strategies for their usage scenarios.

Keep sharing insights and stay engaged with the community for more such productive collaborations!

**Comment by a-sajjad72** [comment]
@glenn-jocher isn't there any update for the ultralytic package for CPU based systems???

**Comment by solomonleoyt** [comment]
so its 2025, and there is still no such package in ultralytics that has only CPU support and no CUDA or NVIDIA in it??

**Comment by rusmux** [comment]
It would be even better to separate dependencies into different extra groups. Why download `torch` if I only need `onnxruntime` for inference?

**Comment by glenn-jocher** [comment]
Thanks for the suggestion! We'll consider dependency group optimization for future releases. For now, you can use `pip install ultralytics --no-deps` and manually install only required packages like `onnxruntime`. Note that core functionality may require PyTorch for some operations. Feel free to open a GitHub Feature Request to discuss specific use cases! 🚀

**Comment by ts2095** [comment]
For anyone managing their dependencies with `uv`, here's a workaround that doesn't rely on removing packages or installing without any dependencies.

The idea here is to force resultution against the CPU-only index for `torch` and `torchvision`, similar to @glenn-jocher's solution, but with the added benefit of working locally and in Python, and being able to install everything in one step. Two caveats:
- The necessary `+cpu` suffix in the version number requires a `==` constraint. That means we're somewhat inflexible on future version upgrades and may need to manage this manually a bit.
- There's no MacOS (darwin) compatible wheel on that index, so if you're working on that platform, you're still getting all Nvidia packages. However, as long as you build your Docker images for `linux/amd64`, they're now nice and small.

```toml
[project.optional-dependencies]
dependency-fixes = [
    # we don't actually use them directly, but, in combination with sources defined
    # explicitly below, this forces torch to only use the CPU version, thus eliminating
    # all nvidia dependencies
    # There is no CPU-only version for darwin, so we need to list the original packages
    # as alternative
    "torch==2.10.0+cpu; sys_platform != 'darwin'",
    "torchvision==0.25.0+cpu; sys_platform != 'darwin'",
    "torch==2.10.0; sys_platform == 'darwin'",
    "torchvision==0.25.0; sys_platform == 'darwin'",
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu" }
]
torchvision = [
    { index = "pytorch-cpu" }
]

```

**Comment by glenn-jocher** [comment]
@ts2095 thanks for sharing this `uv`-based approach—pinning `torch`/`torchvision` to the CPU index at resolution time is a clean way to avoid pulling NVIDIA wheels; if you’re also aiming for smaller/headless deployments, consider `pip install ultralytics-opencv-headless` (same API, uses `opencv-python-headless`) as described in the [Ultralytics installation guide](https://docs.ultralytics.com/quickstart/), and if anyone runs into version-mismatch issues it helps to paste `yolo checks` (or `ultralytics.utils.checks.collect_system_info()`) output per the [checks utilities reference](https://docs.ultralytics.com/reference/utils/checks/)—please open a new issue for visibility since this one is closed/stale.
