### ISSUE TITLE
Using 2 ultralytics versions in single application 

### ISSUE THREAD

**Issue by Haseeb707** [ultralytics/ultralytics#7495]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a full server application in python, which have multiple models and files, initially everything was running smoothly on 8.0.109, but we had a model upgrade and now i have to run new model and a file on a newer version and everything else on the previous one
is there any solution possible
Thanks in Advance

**Comment by glenn-jocher** [comment]
@Haseeb707 hello! It's great to hear that you're integrating multiple Ultralytics models into your application. Running different versions of YOLOv8 in a single application can be challenging due to potential conflicts in dependencies and the way the models are loaded and used.

One approach to handle this situation is to use Python's virtual environments. You can create two separate virtual environments, one for each version of YOLOv8 you need to run. Within each environment, you can install the specific version of YOLOv8 and its dependencies. When running your application, you can activate the appropriate environment for the model you need to use.

Another option is to use Docker containers, where each container encapsulates one version of YOLOv8 and its dependencies, ensuring isolation between the versions.

Remember to manage the interactions between the two environments or containers carefully to maintain the integrity of your application's workflow.

For more detailed guidance on the modes and tasks supported by YOLOv8, you can refer to our documentation at https://docs.ultralytics.com. Good luck with your model integration! 😊🚀
