### ISSUE TITLE
Yolov8 augment = False still augmenting train data

### ISSUE THREAD

**Issue by bwilkie** [ultralytics/ultralytics#7511]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

hey everyone, 

I load the yolo model, disable as many augment values as possible. The output folder is still showing augemnts. 

Here is my code 

![yolo_code](https://github.com/ultralytics/ultralytics/assets/40703571/872daedb-74ae-4c26-b744-bf1aee4e72f1)

Any the output train batch image;

![train_batch0](https://github.com/ultralytics/ultralytics/assets/40703571/db427e98-749f-4416-aecf-06a4140154b0)

### Environment

Ultralytics YOLOv8.1.0 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (Tesla T4, 15102MiB)

### Minimal Reproducible Example

import os

from ultralytics import YOLO

DATA_DIR = source_dir_morl_s2fs

model = YOLO("yolov8n-cls.pt")  # load a pretained model

results= model.train(data=DATA_DIR,
                     epochs=20, batch = 128, imgsz=310,
                     augment =False,
                     hsv_h =0, hsv_s =0, hsv_v =0,degrees =0, translate =0, scale =0,
                     shear =0, flipud =0,fliplr=0,mixup =0,agnostic_nms =False,cos_lr =False,
                     mosaic = 0.0,
                     save = True, 
                     save_dir = source_dir + 'power_image/saved_models/runs4/classify/train/',
                     save_period = 1)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@bwilkie hello! Thanks for reaching out with your issue.

Setting `augment=False` should indeed disable training augmentations. However, if you're still seeing augmented images in your output folder, it could be due to a few reasons. First, ensure that you're using the latest version of YOLOv8, as there might have been updates or bug fixes related to this issue.

If you're already on the latest version, it's possible that there might be a misunderstanding of what constitutes an augmentation. Some visualizations might look like augmentations but are actually part of the standard training process, such as resizing images to the network's input size.

If you believe that there's still an unintended augmentation happening, please provide a minimal reproducible example in a new issue on the Ultralytics YOLOv8 repo, and we'll look into it further. Make sure to include the exact configuration and any relevant logs or screenshots.

For more detailed guidance on training and configuration, you can refer to our documentation at https://docs.ultralytics.com. 😊

Thank you for contributing to the YOLO community, and we appreciate your efforts in making YOLOv8 better!

**Comment by danlai930** [comment]
Based on my understanding, the implementation of augmentations in the YOLO model can generally be divided into two categories: those that utilize the Albumentations library and those that do not. The Albumentations library is primarily used for applying augmentations like Blur, MedianBlur, ToGray, and CLAHE. Other augmentations, such as mosaic, are implemented as separate classes, and you can find more details in the `data/augment.py` file.

If your requirement is to completely disable all augmentations, these steps work for me:

_**First**_, remove the Albumentations library: Execute `pip uninstall albumentations` in your terminal to remove the library from your environment.
_**Second**_, modify the training configuration: When calling the `model.train()` function, include parameters to disable all forms of augmentation. Here is an example configuration:

```python
results = model.train(data=dataset_yaml, epochs=args.epochs, imgsz=args.imgsz, augment=False, hsv_h=0, hsv_s=0, hsv_v=0, degrees=0.0, translate=0, scale=0, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0, mosaic=0, mixup=0.0)
```

This approach sets all augmentation-related parameters to their default or zero values, effectively disabling them during training.

**Comment by glenn-jocher** [comment]
@danlai930 hello! To disable all augmentations in YOLOv8, setting `augment=False` should suffice. However, if you're using a custom training script or have modified the source code, ensure that no other augmentation settings are being applied.

Uninstalling Albumentations is not necessary for YOLOv8, as augmentations are controlled within the training configuration. Just pass the appropriate flags to `model.train()` as you've described to disable augmentations.

If you're still encountering issues, please check the latest documentation for any updates on augmentation settings and ensure your YOLOv8 codebase is up to date. If the problem persists, feel free to raise an issue on the Ultralytics YOLOv8 repo with details of your configuration for further assistance. 😊

**Comment by FoxSkywalker** [comment]
> @danlai930 hello! To disable all augmentations in YOLOv8, setting `augment=False` should suffice. However, if you're using a custom training script or have modified the source code, ensure that no other augmentation settings are being applied.
> 
> Uninstalling Albumentations is not necessary for YOLOv8, as augmentations are controlled within the training configuration. Just pass the appropriate flags to `model.train()` as you've described to disable augmentations.
> 
> If you're still encountering issues, please check the latest documentation for any updates on augmentation settings and ensure your YOLOv8 codebase is up to date. If the problem persists, feel free to raise an issue on the Ultralytics YOLOv8 repo with details of your configuration for further assistance. 😊

Hi, @glenn-jocher !

Here's my environment in Google Colab:
```
Ultralytics YOLOv8.1.17 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 26.3/201.2 GB disk)
```

And that's my training setup :
```
results = model.train(data='InternetTotal.yaml', epochs=2, patience=50, batch=16,
                      save=True, val=True, plots=True, augment=False, close_mosaic=0)
```

![image](https://github.com/ultralytics/ultralytics/assets/49927987/9bfe46f5-7a9f-4494-ace4-56b57b8f70f3)


But, on the image above, it's possible to see that even when we set `augment=False`, it is still working.
The problem just can be solved when I uninstall the albumentation library.
My yaml file just have the path and the classes, nothing else.

**Comment by glenn-jocher** [comment]
Hi @FoxSkywalker!

Thanks for sharing your setup and observations. It looks like you've done everything right to disable augmentations with `augment=False`. The image you're seeing might be part of the standard resizing or formatting rather than an augmentation effect. 

If you're certain that augmentations are still being applied, it could be a bug. Could you please open an issue on the [Ultralytics YOLOv8 repo](https://github.com/ultralytics/ultralytics/issues) with your training script and YAML file? We'll look into it right away! Meanwhile, ensure your YOLOv8 is updated to the latest version as we continuously improve the codebase.

Keep up the great work with YOLOv8! 🌟

**Comment by YJain-ND** [comment]
Hi,
For the classification training, there is a parameter "erasing" that randomly erases a portion of the image, encouraging the model to focus on less obvious features for recognition. (default erasing = 0.4)

**Comment by glenn-jocher** [comment]
Hello,

To adjust the "erasing" parameter during classification training, simply set it to your desired value in the training configuration. If you have further questions, feel free to ask!
