### ISSUE TITLE
Higher RAM usage when running inference on GPU than on CPU

### ISSUE THREAD

**Issue by IlyaHalsky** [ultralytics/ultralytics#7539]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,
I'm using my own trained weights from yolov8m and running inference.
Sample code:
```
self.yolo = YOLO(side_weights)
...
results: List[Results] = self.yolo(crops, verbose=False) # crops = array of 25 640x640 PIL images
```
With gpu enabled my RAM usage is around 3.8Gb, without it (`export CUDA_VISIBLE_DEVICES=""`) - 1.5Gb.

Can I somehow reduce RAM usage when using GPU?
My intent is to run small server on kubernetes node with gpu where RAM is very limited.

### Additional

`yolo checks` output:
Ultralytics YOLOv8.1.0 🚀 Python-3.8.10 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090 Ti, 24239MiB)
Setup complete ✅ (12 CPUs, 125.8 GB RAM, 66.4/453.7 GB disk)

OS                  Linux-5.4.0-167-generic-x86_64-with-glibc2.29
Environment         Docker
Python              3.8.10
Install             pip
RAM                 125.76 GB
CPU                 AMD Ryzen 9 5900X 12-Core Processor
CUDA                11.7

matplotlib          ✅ 3.7.1>=3.3.0
numpy               ✅ 1.24.3>=1.22.2
opencv-python       ✅ 4.7.0.72>=4.6.0
pillow              ✅ 10.1.0>=7.1.2
pyyaml              ✅ 6.0>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.0.1>=1.8.0
torchvision         ✅ 0.15.2>=0.9.0
tqdm                ✅ 4.65.0>=4.64.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.0.2>=1.1.4
seaborn             ✅ 0.12.2>=0.11.0
hub-sdk             ✅ 0.0.3>=0.0.2

**Comment by glenn-jocher** [comment]
@IlyaHalsky hello! It's not uncommon to see higher RAM usage when running inference on a GPU compared to a CPU due to the way memory is allocated and managed differently on GPUs. When using a GPU, there's additional overhead for loading the model weights and maintaining the GPU's state, which can lead to increased RAM usage.

To reduce RAM usage on a GPU, you might consider the following:
- **Batch Size**: Ensure you're using an optimal batch size that balances speed and memory usage.
- **Model Size**: Smaller models like YOLOv8n or YOLOv8s may consume less RAM.
- **Precision**: Experiment with mixed precision settings, which can reduce memory usage.
- **Optimized Libraries**: Make sure you're using the latest versions of CUDA and cuDNN, as they often include optimizations.

For more detailed guidance on managing resources and optimizing performance, please refer to our documentation on [Benchmark](https://docs.ultralytics.com/modes/benchmark) and [Export](https://docs.ultralytics.com/modes/export) modes. These sections provide insights into profiling and deploying models efficiently.

If you continue to face issues, please provide more details on your setup and we'll do our best to assist you further. Keep in mind that Kubernetes nodes with limited RAM might require careful tuning of the above parameters to fit within the available resources. 😊🚀

**Comment by IlyaHalsky** [comment]
@glenn-jocher sorry, if I wasn't clear. I don't mind GPU's RAM usage, I'm trying to save on RAM for CPU (on the motherboard). `top` reports 3.8gb used, but to my understanding it should be almost zero if I have GPU available.

**Comment by glenn-jocher** [comment]
@IlyaHalsky, it's indeed unusual for CPU RAM usage to mirror GPU RAM usage closely during inference. This could be indicative of data being duplicated in both CPU and GPU memory, which isn't typically necessary. A few things to consider:

- **Data Loading**: Ensure that data is loaded directly to the GPU when possible, to avoid unnecessary CPU RAM usage.
- **Caching**: Check if there's any caching mechanism in place that might be storing data redundantly.
- **Memory Leaks**: Look out for any memory leaks in your code or in the libraries you're using.

For further investigation, you might want to profile your system's memory usage to pinpoint where the duplication is happening. Our [Benchmark](https://docs.ultralytics.com/modes/benchmark) documentation may provide additional insights into memory profiling.

If the issue persists, please provide more context, and we'll continue to troubleshoot together. 🛠️

**Comment by IlyaHalsky** [comment]
@glenn-jocher thank you for your suggestions. I didn't find anything about memory profiling in the docs.
I'm quite puzzled by cpu memory consumption, hopefully you could share some insight. Consider this example:
```python
import os
import psutil
from PIL import Image
from ultralytics import YOLO
def print_memory():
    print(psutil.Process(os.getpid()).memory_info().rss / 1024 ** 2)
yolo = YOLO("side-detection-yolov8.pt")
print_memory()
images = []
for path in os.listdir("./crops/"):
    images.append(Image.open("./crops/" + path))
print_memory()
results = yolo(images, verbose=False)
print_memory()
results = yolo(images, verbose=False)
print_memory()
```
This code outputs
```
516.18359375
516.18359375
3347.42578125
3337.94140625
```
If I change `yolo = YOLO("side-detection-yolov8.pt")` to `yolo = YOLO("side-detection-yolov8.pt").to("cuda")` the output becomes:
```
1253.890625
1253.890625
2529.22265625
2520.87890625
```
Passing directory to predict (`results = yolo(images)` -> `results = yolo("./crops/")`) doesn't change the outcome.
Also I've tried preloading everything into GPU with no visible success:
```python
import os

import psutil
import torch
from PIL import Image
from ultralytics import YOLO
from torchvision import transforms
def print_memory():
    print(psutil.Process(os.getpid()).memory_info().rss / 1024 ** 2)
yolo = YOLO("side-detection-yolov8.pt").to('cuda')
print_memory()
images = []
for path in os.listdir("./crops/"):
    image = Image.open("./crops/" + path)
    tensor = transforms.ToTensor()(image)
    tensor = tensor.to("cuda")
    images.append(tensor)
images = torch.stack(images)
images = images.to("cuda")
print_memory()
results = yolo(images, verbose=False)
print_memory()
results = yolo(images, verbose=False)
print_memory()
```
output:
```
1255.26171875
1324.37109375
2476.1171875
2494.79296875
```

**Comment by glenn-jocher** [comment]
@IlyaHalsky, the memory usage patterns you're observing suggest that the model and data are indeed being loaded into GPU memory, as indicated by the increased memory usage when you explicitly move the model to CUDA with `.to("cuda")`. However, the CPU memory usage should not increase proportionally to GPU memory usage.

The memory increase after loading the model and performing inference is expected, but the CPU memory should not be as high as you're reporting. This could be due to:
- **Data Duplication**: Data might be stored in both CPU and GPU memory. Ensure that data is moved to the GPU only as needed.
- **Framework Overheads**: PyTorch and other libraries may have overheads that result in additional CPU memory usage.

To further diagnose the issue, you could:
- **Profile Memory**: Use memory profiling tools to understand where the memory is being allocated.
- **Reduce Overheads**: Minimize data transformations and movements between CPU and GPU.
- **Check for Leaks**: Ensure there are no memory leaks in your code or the libraries.

If the issue remains unresolved, consider opening an issue with a detailed report, including your profiling findings, for further assistance. 🕵️‍♂️🔍

**Comment by dcarrion87** [comment]
@IlyaHalsky did you ever get to the bottom of the high memory usage?

**Comment by IlyaHalsky** [comment]
@dcarrion87 sadly no, we ran our code in production environment and everything worked as expected. We recorded around 700mb of RAM usage and 1.6Gb GPU usage for ` yolov8m` model. My guess it's bound to the GPU and drivers version.
Both test were ran inside Kubernetes pod.
On dev: 
Ultralytics YOLOv8.1.0 🚀 Python-3.8.10 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3090 Ti, 24239MiB)
Setup complete ✅ (12 CPUs, 125.8 GB RAM, 66.4/453.7 GB disk)

OS Linux-5.4.0-167-generic-x86_64-with-glibc2.29
Environment Docker
Python 3.8.10
Install pip
RAM 125.76 GB
CPU AMD Ryzen 9 5900X 12-Core Processor
CUDA 11.7
In prod:
Ultralytics YOLOv8.1.0 🚀 Python-3.8.10 torch-2.2.0+cu121 CUDA:0 (NVIDIA A2, 14891MiB)
Setup complete ✅ (24 CPUs, 125.5 GB RAM, 205.9/436.0 GB disk)

OS                  Linux-5.4.0-170-generic-x86_64-with-glibc2.29
Environment         Docker
Python              3.8.10
Install             pip
RAM                 125.46 GB
CPU                 Intel Xeon Silver 4214 2.20GHz
CUDA                12.1

**Comment by dcarrion87** [comment]
I think you're spot on. I'm seeing it no matter where I do the implementation and any model. As soon as I switch to targetting CUDA the CPU RAM shoots through the roof. What an absolute pain.

**Comment by glenn-jocher** [comment]
@dcarrion87 when running inference on a GPU, it's expected to see higher RAM usage compared to running on a CPU due to the way CUDA allocates memory for the GPU. However, there are a few strategies you can try to reduce RAM usage when using a GPU:

1. **Reduce Batch Size**: If you're running inference with a batch of images, try reducing the batch size. This will decrease the amount of memory required at any given time.

2. **Optimize Model**: If possible, optimize your model for inference. This can include techniques like model pruning, quantization, or using a more efficient model architecture.

3. **Use Mixed Precision**: If you're not already doing so, consider using mixed precision (FP16) for inference, which can reduce memory usage and also speed up the inference.

4. **Manage Cache**: PyTorch accumulates cache during GPU operations. You can clear this cache after inference to free up memory using `torch.cuda.empty_cache()`.

5. **Streamline Data Pipeline**: Ensure that your data pipeline is efficient. For example, loading images directly into GPU memory rather than CPU memory can help reduce overall system RAM usage.

6. **Use Efficient Data Types**: Use efficient data types for your tensors. For example, if you don't need the precision of `float64`, use `float32` or `float16`.

7. **Unload Models**: If you have multiple models loaded, unload the ones you are not using with `del model` and `torch.cuda.empty_cache()`.

8. **Upgrade PyTorch**: Ensure you are using the latest version of PyTorch, as there are often memory optimizations in newer versions.

9. **Profile Memory Usage**: Use tools like NVIDIA's `nsight` or `nvidia-smi` to profile your memory usage and identify where the most memory is being consumed.

10. **Use TorchScript**: Convert your model to TorchScript, which can sometimes be more efficient in terms of memory usage.

11. **Limit Number of Worker Threads**: If you're using DataLoader with multiple workers, try reducing the number of worker threads.

12. **Use On-Demand Loading**: Load only the data you need for each inference step rather than preloading a large dataset into memory.

Implementing these strategies may help reduce the RAM usage when running inference on a GPU. However, it's important to note that some increase in RAM usage is inevitable due to the nature of GPU computations.
