### ISSUE TITLE
Tracking: why are IDs sometimes not assigned to detections?

### ISSUE THREAD

**Issue by johnohagan** [ultralytics/ultralytics#7557]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

My question is similar to [2544](https://github.com/ultralytics/ultralytics/issues/2544), but it doesn't relate to initial detection. 

Sometimes when tracking, objects are detected but no id is assigned. 

For example, if I run this code:  
```
import cv2
from ultralytics import YOLO

model = YOLO('yolov8m.pt')
capture = cv2.VideoCapture(0)
framenum = 0

while 1:
    image = capture.read()[1]
    framenum += 1
    results = model.track(image, persist=False, verbose=False)[0]
    boxes = results.boxes
    if boxes.id is None:
        #Detections with no ids assigned:
        if (boxdata := boxes.data).numel():
            print(framenum, boxdata)
```

And then deliberately try to confuse the tracking by, say, waving my hand close in front of the camera, I get occasional output like this:

```
41 tensor([[4.0519e+02, 1.0116e+00, 6.3844e+02, 3.3890e+02, 2.7210e-01, 0.0000e+00]])
42 tensor([[3.9012e+02, 8.5687e-01, 6.3853e+02, 3.2872e+02, 2.2807e-01, 0.0000e+00]])
43 tensor([[3.8619e+02, 1.2175e+00, 6.3873e+02, 3.2442e+02, 2.9180e-01, 0.0000e+00]])
44 tensor([[3.9424e+02, 4.5920e+01, 4.1435e+02, 9.1584e+01, 3.4440e-01, 7.3000e+01],
        [3.6941e+02, 6.1725e+01, 3.8021e+02, 8.4972e+01, 1.5182e-01, 7.3000e+01],
        [4.1283e+02, 5.3838e+01, 4.2433e+02, 9.2388e+01, 1.3987e-01, 7.3000e+01],
        [3.8174e+02, 5.0668e+01, 3.9053e+02, 8.7040e+01, 1.3204e-01, 7.3000e+01],
        [4.2274e+02, 5.4703e+01, 4.3371e+02, 9.0509e+01, 1.2350e-01, 7.3000e+01],
        [3.6131e+02, 9.8610e+01, 3.6882e+02, 1.3299e+02, 1.1943e-01, 7.3000e+01],
        [3.8170e+02, 4.9126e+01, 3.9733e+02, 8.7248e+01, 1.1217e-01, 7.3000e+01]])
```

It's usually just one frame, or a few consecutive frames like the example above.

Although I'm not across how the tracking algorithms work, there are two things I find surprising about this:

1. I would expect that any detection would be assigned an id - a new id if the detection could not be connected with a previous one - even if only fleetingly.

2. When this happens, the sub-tensors in boxes.data lack an id entry, and thus are only six elements long, instead of the usual seven (when tracking). This messes up code like `x1, y1, x2, y2, idx, conf, cls = box`.

This is a minor issue and easily worked around by checking for `boxes.id`, and it may well be that it is intended to work this way, I'm just curious to know if that's the case.

**Comment by glenn-jocher** [comment]
@johnohagan hello! It seems you're encountering frames where objects are detected but not assigned an ID during tracking. This can happen when the tracking algorithm is temporarily uncertain about the continuity of an object's trajectory, especially in cases of occlusion, rapid movement, or other visual confusions.

1. IDs are typically assigned when the tracker is confident about the object's identity across frames. If an object can't be confidently linked to an existing track, it might not receive a new ID immediately.

2. The detection tensors lacking an ID indicate that the tracker couldn't associate these detections with existing tracks. This is why you're seeing tensors with six elements instead of seven.

This behavior is part of the tracking design, which aims to maintain ID consistency over time rather than assigning new IDs too hastily. It's good that you're handling these cases by checking for `boxes.id`. If you need further details on how the tracking works or how to adjust its parameters, please refer to our documentation on the Track mode. 😊

**Comment by johnohagan** [comment]
Thanks for your response, that makes sense.

**Comment by glenn-jocher** [comment]
@johnohagan you're welcome! If you have any more questions or need further assistance, feel free to reach out. Happy tracking! 😊
