### ISSUE TITLE
cloning error 

### ISSUE THREAD

**Issue by PremVarma5142** [ultralytics/ultralytics#7626]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Cloning into 'ultralytics'...
remote: Enumerating objects: 20706, done.
remote: Counting objects: 100% (1136/1136), done.
remote: Compressing objects: 100% (763/763), done.
remote: Total 20706 (delta 653), reused 672 (delta 358), pack-reused 19570
Receiving objects: 100% (20706/20706), 12.25 MiB | 8.35 MiB/s, done.
error: RPC failed; curl 56 GnuTLS recv error (-110): The TLS connection was non-properly terminated.
Resolving deltas: 100% (14359/14359), done.

### Environment

Ultralytics YOLOv8.0.220 🚀 Python-3.8.10 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3050, 7971MiB)
Setup complete ✅ (16 CPUs, 15.5 GB RAM, 435.4/467.9 GB disk)
None

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by DrawingProcess** [comment]
I think this link can help you
https://stackoverflow.com/questions/38378914/how-to-fix-git-error-rpc-failed-curl-56-gnutls

**Comment by glenn-jocher** [comment]
@DrawingProcess it seems like you're encountering a network-related error during the cloning process. This issue is often resolved by ensuring a stable internet connection or by increasing the Git buffer size. You might want to check out the Stack Overflow thread you've mentioned for potential solutions. If the problem persists, consider trying to clone the repository at a different time or from a different network. If you need further assistance, please refer to our documentation or submit an issue on our GitHub repository. Good luck! 🍀
