### ISSUE TITLE
AttributeError: 'Conv2d' object has no attribute 'total_ops'

### ISSUE THREAD

**Issue by dongfeicui** [ultralytics/ultralytics#7633]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

The code 
https://github.com/ultralytics/ultralytics/blob/d021524e850acfa393ec25d4ecb9c4c761cca688/ultralytics/engine/model.py#L266
 contributed to the failure of
https://github.com/Lyken17/pytorch-OpCounter/blob/43c064afb71383501e41eaef9e8c8407265cf77f/thop/profile.py#L90-L91

So i wrote a new function denoted as profile_yolo in the package named thop

![image](https://github.com/ultralytics/ultralytics/assets/60336738/c3f34218-d32d-4a67-9f43-efda9c4682a0)

The details are as followed

```
def profile_yolo(
    model: nn.Module,
    inputs,
    custom_ops=None,
    verbose=True,
    ret_layer_info=False,
    report_missing=False,
):
    handler_collection = {}
    types_collection = set()
    if custom_ops is None:
        custom_ops = {}
    if report_missing:
        # overwrite `verbose` option when enable report_missing
        verbose = True

    def add_hooks(m: nn.Module):
        if 'total_ops' in m._buffers:
            return

        m.register_buffer("total_ops", torch.zeros(1, dtype=torch.float64))
        m.register_buffer("total_params", torch.zeros(1, dtype=torch.float64))

        # for p in m.parameters():
        #     m.total_params += torch.DoubleTensor([p.numel()])

        m_type = type(m)

        fn = None
        if m_type in custom_ops:
            # if defined both op maps, use custom_ops to overwrite.
            fn = custom_ops[m_type]
            if m_type not in types_collection and verbose:
                print("[INFO] Customize rule %s() %s." % (fn.__qualname__, m_type))
        elif m_type in register_hooks:
            fn = register_hooks[m_type]
            if m_type not in types_collection and verbose:
                print("[INFO] Register %s() for %s." % (fn.__qualname__, m_type))
        else:
            if m_type not in types_collection and report_missing:
                prRed(
                    "[WARN] Cannot find rule for %s. Treat it as zero Macs and zero Params."
                    % m_type
                )

        if fn is not None:
            handler_collection[m] = (
                m.register_forward_hook(fn),
                m.register_forward_hook(count_parameters),
            )
        types_collection.add(m_type)

    # prev_training_status = model.training

    # model.eval()
    model.apply(add_hooks)
    return model
```

Registry is required here
![image](https://github.com/ultralytics/ultralytics/assets/60336738/44879348-8d2c-4d7c-8ade-32cd137e5cf7)

I commented ‘model.eval()’  in thop profile and the code blocks in the pic below in prevention of other errors.

![image](https://github.com/ultralytics/ultralytics/assets/60336738/c028500d-a8a8-4d96-b04e-86b0a76e3b55)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@dongfeicui hello! It seems like you've encountered an issue with the THOP (PyTorch-OpCounter) library when trying to profile the YOLOv8 model. The `AttributeError` you're seeing is because the THOP library expects a `total_ops` attribute on the `Conv2d` module, which isn't present by default.

Your approach to writing a custom function `profile_yolo` to handle the profiling for YOLOv8 is a good workaround. By registering `total_ops` and `total_params` as buffers and applying hooks, you're adapting the profiling process to work with YOLOv8's architecture.

Remember that when you modify the profiling function, you should ensure that it accurately reflects the operations performed by the model. Commenting out `model.eval()` may have implications on the model's behavior during profiling, as it affects layers like BatchNorm and Dropout. Make sure that the model's state during profiling matches the state during inference for accurate measurements.

If you have further questions or need assistance with YOLOv8, feel free to reach out. For more detailed documentation on YOLOv8's modes and tasks, you can always refer to our [Ultralytics Docs](https://docs.ultralytics.com). Keep up the great work! 🚀
