### ISSUE TITLE
YOLO using cuda in multiple threads

### ISSUE THREAD

**Issue by TiMMaTTiee** [ultralytics/ultralytics#7637]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to use instances of YOLO in different python threads, on the gpu. I have done this before in the past, but I am running into issues. My code runs in docker, and the code would hang at model.predict(). No errors, just stuck, debugger also doesn't work anymore. Sometimes it runs inference ~10 times per thread, sometimes it stops at the first inference. I then ran it outside of docker, as well as on a different system, same issue. 

Some system details:
Driver Version: 525.78.01 CUDA Version: 12.0 RTX A2000
Driver Version: 520.61.05 CUDA Version: 11.8 RTX 3070
Using ultralytics v8.1.2

I am not doing multithreading to try to increase performance, in my full architecture it's used to abstractify different cameras.
Minimal example:
```
from ultralytics import YOLO
import time
import threading
from collections import deque
import numpy as np


def run(idx: int):
    model = YOLO("yolov8s.pt")
    device = "cuda:0"
    timings = deque(maxlen=30)
    frame_number = 0
    frame = np.zeros((1080, 1920, 3), dtype=np.uint8)
    while True:
        time.sleep(0.01)
        frame_number += 1
        t1 = time.perf_counter()
        print(f'thread {idx} before')
        model.predict(frame, device=device, verbose=False)
        print(f'thread {idx} after')

        t2 = time.perf_counter()

        timings.append(t2-t1)
        if (frame_number % 30) == 0:
            avg_fps = 1 / (sum(timings) / len(timings))
            print(f"FPS thread:{idx} = {avg_fps}. {t2 - t1}")


if __name__ == "__main__":
    for idx in range(2):
        detection_thread = threading.Thread(
            target=run,
            args=(idx, )
        )
        detection_thread.start()
        time.sleep(10)
    while True:
        time.sleep(1)

```

**Comment by glenn-jocher** [comment]
@TiMMaTTiee hello! It seems you're encountering a deadlock issue when running YOLOv8 instances across multiple threads. This can be a complex situation due to the way CUDA interacts with Python's Global Interpreter Lock (GIL) and threading.

Here are a few general tips that might help:
- Ensure that each thread is using a different CUDA context. Sharing the same context across threads can lead to deadlocks.
- Consider using multiprocessing instead of threading, as it can provide better isolation between processes and might avoid GIL-related issues.
- Make sure that the GPU memory is sufficient for running multiple models simultaneously. If each thread is loading its own model into memory, you could be running out of GPU memory.
- Check if there are any CUDA synchronization points that might be causing the threads to wait indefinitely.

If these suggestions don't resolve the issue, it would be beneficial to open a discussion on our GitHub Discussions page, providing the details you've shared here. The community and our team can then collaborate to find a solution. Remember to check the Ultralytics Docs for any updates or insights on multi-threading with YOLOv8. Good luck! 🤞

**Comment by TiMMaTTiee** [comment]
@glenn-jocher Thanks, yeah looks like it's not an issue with ultralytics.

**Comment by glenn-jocher** [comment]
@TiMMaTTiee Glad to hear you've narrowed down the issue! If you have further questions or need assistance in the future, don't hesitate to reach out. Happy coding! 😊👍

**Comment by Asshok1** [comment]
Hey @glenn-jocher , I have a question related to threading on GPU, when I run this code on command prompt the cursor output is blinking without giving any output, without any error also on nvidia rtx a5000 24gb ram, when I run with 2 threads it is giving the output. Suppose if I'm increasing the threads like this I'm not getting the console output what is the reason for this   and how to overcome this issue? Is this the problem with code or GPU or ultralytics ?


import torch
import threading
from ultralytics import YOLO
import os
import time


def model_load():
    global model1, model2,model3
    try: 
        device = 'cuda' if torch.cuda.is_available() else 'cpu'
        
        model1 = YOLO(r'best.pt').to(device)
        model2 = YOLO(r'best1.pt').to(device)
        model3 = YOLO(r'best2.pt').to(device)
        print("Models are loaded, ack_event is set.",flush = True)
    
    except Exception as e:
        print('Error during model loading :',e)

model_load()
    
def fun1():
    while True:
        print('i am in funciton 1',flush=True)
        results = model1(r"img.jpg") 
	    
	    
            
def fun2():
    while True:
        print('i am in funciton 2',flush=True)
        results = model2(r"img1.jpg") 

def fun3():
    while True:
        print('i am in funciton 3',flush = True)
        results = model3(r"img2.jpg") 


if __name__=="__main__":
    
    print('models are loaded',flush = True)
    
    t1=threading.Thread(target=fun1)
    t2=threading.Thread(target=fun2)
    t3=threading.Thread(target=fun3)
    t1.start()
    t2.start()
    t3.start()
