### ISSUE TITLE
stop the training process

### ISSUE THREAD

**Issue by ziyaxuanyi** [ultralytics/ultralytics#764]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I train yolov8 on multiple graphics cards, for example, device=[2,3,5]. It works well.
When I use ctrl+c to stop the training process, only the training process on device 2 stops.
The training process on device 3 and 5 is still working and they seem to be zombie process.

Is this a bug？or how to stop the training process correctly?

**Comment by AyushExel** [comment]
It could be a bug but also just a general problem related to multi-processing. I encounter zombie processes when ending tasks abruptly with `ctrl+z` but on using `ctlr+c` all processes are ended and there is no zombie process. Can you try that and see if it also works for you

**Comment by ziyaxuanyi** [comment]
> It could be a bug but also just a general problem related to multi-processing. I encounter zombie processes when ending tasks abruptly with `ctrl+z` but on using `ctlr+c` all processes are ended and there is no zombie process. Can you try that and see if it also works for you

yes, it works.

**Comment by glenn-jocher** [comment]
@aswin-roman i'm sorry for the trouble you're experiencing with terminating the training process on multiple GPUs. It does appear there might be an issue with how processes are being handled.

To cleanly stop multi-GPU training, you could send a termination signal to the main process, which should then propagate to the child processes. If `ctrl+c` isn't effectively terminating all processes, one alternative is to manually kill the processes using the command line by identifying their process IDs (PIDs) with commands like `htop` or `top` and then using `kill -9 PID` for each one.

I will be looking at the issue further to see if there's a bug that can be fixed in the codebase to handle termination more gracefully across all devices.

Please continue to share any additional information you find, as it may help to diagnose and resolve the issue. Your feedback is important and contributes to improving YOLOv8 for everyone.

**Comment by aswin-roman** [comment]
@glenn-jocher Using [torchrun ](https://pytorch.org/docs/stable/elastic/run.html) seems to be the easiest workaround. Also I have encountered other issues with the DDP implementation integrated with Ultralytics-YOLOv8.

**Comment by glenn-jocher** [comment]
@aswin-roman i understand that manually killing processes can be tedious and isn't an ideal solution. Leveraging `torchrun` is indeed a good workaround to ensure more robust process management during distributed training.

Regarding any issues you've encountered with the Distributed Data Parallel (DDP) implementation, I would highly encourage you to open an issue on the Ultralytics YOLOv8 repository with detailed information about the problems you're facing. This way, the team can investigate, reproduce, and address the specific concerns related to DDP.

Our aim is always to improve the project and your contributions by reporting these issues are invaluable. The Ultralytics team appreciates your understanding and patience as we work towards resolving these complexities. Thanks for your input, and rest assured that we're continuously striving to enhance the functionality and user experience of YOLOv8. 🚀
