### ISSUE TITLE
Both botsort and bytetracker are called when do model.track()

### ISSUE THREAD

**Issue by MrWei282** [ultralytics/ultralytics#7649]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

![297246015-b8a95cf3-3d87-4b06-b1f5-e28c5bdf9df3](https://github.com/ultralytics/ultralytics/assets/108318437/6cfda926-53af-450b-8d55-810ae27cff7d)
I initially asked in #7614 and was advised to put this as a bug report
Basically as I browse through yolov8 in version 8.0.229, I noticed that the program calls for both Botsort and ByteTracker's update function. This happens regardless if I put a "tracker="tracker='./ultralytics/cfg/trackers/botsort.yaml'" in model.track().

### Environment

Yolov8 version 8.0.229
Python 3.7.12
Pytorch 1.7.1+cu110

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by johnohagan** [comment]
AIUI, botsort is built on top of bytetrack, so I think this might be expected behaviour. 

Based on a quick look at the code for both trackers, it looks like botsort imports and subclasses the STrack class from bytetrack, and the botsort BOTrack class's update method calls the parent class's update method. 

To test this, I added the same `print` calls suggested in [7614](https://github.com/ultralytics/ultralytics/issues/7614) and saw both "bot" and "byte" printed, confirming both methods were being called when `tracker='botsort.yaml'` is passed to `track` (or if no tracker option is passed, as botsort is the default), but if  `tracker='bytetrack.yaml' ` is passed to `track`, only "byte" is printed, i.e. only the bytetrack update function is being called.

**Comment by MrWei282** [comment]
I see, good that this is expected behavior :)

**Comment by glenn-jocher** [comment]
@MrWei282 glad to hear your understanding! If you have any more questions or need further clarification, feel free to reach out. Happy tracking! 😊🚀
