### ISSUE TITLE
Save train acc in results.csv

### ISSUE THREAD

**Issue by InfernoidZero** [ultralytics/ultralytics#7656]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

For some reason I want to save train accuracy in results.csv. After reading the code in trainer.py, I have no I idea how metrics and validator works. What should I do?

**Comment by glenn-jocher** [comment]
@InfernoidZero hello! To save training accuracy in `results.csv`, you would need to modify the code that handles logging within the training loop. The `trainer.py` script manages the training process, and metrics are calculated and logged periodically. 

For training accuracy, you would need to capture the accuracy metric after each training epoch and append it to the `results.csv` file. This involves interacting with the part of the code where metrics are computed during training and ensuring that the accuracy metric is included in the list of metrics to be logged.

Since you've already looked into `trainer.py`, you'll want to focus on the section of the code that deals with logging metrics after each epoch. Look for where `results.csv` is updated, and you can add the training accuracy to this update process.

For a detailed understanding of how metrics are handled and validator works, please refer to our documentation on the Train mode. If you need further guidance, our discussions page is a great place to ask for community or team insights. Good luck! 😊

**Comment by InfernoidZero** [comment]
I try to add self.train_validate() in trainer.py like self.validate() but find it need to calculate all train dataset again. How can I calculate train acc while training? I believe an example will help a lot.

**Comment by glenn-jocher** [comment]
Hello @InfernoidZero! To calculate training accuracy while training without going through the entire dataset again, you can accumulate the correct predictions and total predictions within the training loop itself. At the end of each epoch, you can then calculate the accuracy based on these accumulations.

Since you're already modifying `trainer.py`, you would integrate this calculation into the training loop where batches are processed. Keep track of the number of correct predictions and the total number of samples seen in each batch. After the epoch, calculate the accuracy as the ratio of correct predictions to total samples.

Remember to reset your counters for correct and total predictions at the beginning of each epoch to ensure accuracy is calculated correctly for that epoch.

Please refer to our documentation for more details on the training process and how metrics are handled. If you need further assistance, our discussions page is a great resource for community support.
