### ISSUE TITLE
pt  to trt

### ISSUE THREAD

**Issue by Sparklexa** [ultralytics/ultralytics#7686]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

I used export to convert to onnx without errors but I got the following error while exporting pt as tensorrt: PyTorch: starting from 'runs\detect\train\weights\best.pt' with input shape (2, 3, 2048, 1504) BCHW and output shape(s) (2, 20, 63168) (52.3 MB)

ONNX: starting export with onnx 1.15.0 opset 17...

The process has ended, exit code -1073741819 (0xC0000005)

### Environment

OS   WIN11
Environment Pycharm
python 3.10
CUDA 12.1
tensorrt 8.6.1
CuDNN 8801

### Minimal Reproducible Example

`from` ultralytics import YOLO

model = YOLO('runs/detect/train/weights/best.pt')  

results = model.export(format='engine', imgsz=[2048, 1500], device=0,)``

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Sparklexa hello! It seems you've encountered an issue while exporting your `.pt` model to TensorRT format. The exit code suggests a possible segmentation fault during the process, which could be due to various reasons such as compatibility issues with the CUDA, cuDNN, or TensorRT versions.

Please ensure that your environment meets the requirements for TensorRT conversion, including compatible versions of CUDA, cuDNN, and TensorRT. Also, verify that your PyTorch installation is built for the correct CUDA version.

If the environment is set up correctly and the issue persists, consider running the export process in a clean environment or container to rule out any conflicts. If you're still facing difficulties, please provide more details on the error message or logs, and we can look into this further.

Feel free to check out our documentation on the Export mode for additional guidance. If you'd like to contribute by submitting a PR with a fix or improvement, that would be fantastic! 🚀

**Comment by Sparklexa** [comment]
I have cuda version 12.1, torch version 2.1, cudnn version 8.9.6, tensorrt version 8.6.1, but can't export using the export.py file, causing the kind of error described earlier. What should I do?

**Comment by Sparklexa** [comment]
@glenn-jocher I have cuda version 12.1, torch version 2.1, cudnn version 8.9.6, tensorrt version 8.6.1, but can't export using the export.py file, causing the kind of error described earlier. What should I do?

**Comment by glenn-jocher** [comment]
@Sparklexa, it appears there might be a compatibility issue between the software versions you're using. Please ensure that your PyTorch version is compatible with CUDA 12.1. Also, check that your cuDNN and TensorRT versions are compatible with your PyTorch build. If the issue persists after verifying compatibility, try exporting the model in a fresh environment with the recommended versions. For detailed compatibility information and further assistance, please refer to our documentation on the Export mode. 🛠️

**Comment by Jay19751103** [comment]
I use cuda 11.8, it can work. 
But still have profiling time issue. looks need to change utils/ops.py time.time to time.perf_counter
then it can get the inference speed like the C++ application

**Comment by glenn-jocher** [comment]
@Jay19751103 it appears that you are encountering an issue when exporting a `.pt` model to TensorRT (`.engine`) format. The exit code `-1073741819 (0xC0000005)` typically indicates an access violation error, which could be due to a variety of reasons, including issues with memory, incompatible library versions, or other environmental factors.

Here are a few steps you can take to troubleshoot and potentially resolve the issue:

1. **Check Compatibility:**
   Ensure that your environment is set up correctly with compatible versions of PyTorch, CUDA, cuDNN, and TensorRT. Since you are using CUDA 12.1, make sure that the version of PyTorch you have installed is built for CUDA 12.1.

2. **Update Libraries:**
   Update all relevant libraries to their latest versions, as there might be bug fixes or improvements that could resolve the issue.

3. **Reduce Model Size:**
   Try reducing the input size (`imgsz`) to see if the issue is related to memory constraints. You can start with a smaller size and gradually increase it to find the limit.

4. **Isolate the Issue:**
   Try exporting the model to ONNX format first and then use the `trtexec` command-line tool provided by TensorRT to convert the ONNX model to TensorRT. This can help determine if the issue is with the export process or with the model itself.

5. **Check for Known Issues:**
   Review the [Ultralytics YOLOv8 issues](https://github.com/ultralytics/ultralytics/issues) on GitHub to see if others have reported similar problems and if there are any suggested solutions.

6. **System Resources:**
   Monitor your system resources during the export process to ensure there are no resource constraints that could be causing the issue.

7. **Verbose Logging:**
   Enable verbose logging during the export process to get more detailed error messages that can help pinpoint the problem.

8. **Simplify the Model:**
   If you have added custom layers or modifications to the model, try exporting a standard YOLOv8 model without any changes to see if the issue persists.

If you continue to experience issues after trying these steps, you can report the bug on the [Ultralytics YOLOv8 GitHub repository](https://github.com/ultralytics/ultralytics/issues) with detailed information about your environment and the steps you've taken to troubleshoot. This will help the maintainers and community to assist you further.

Since you've indicated a willingness to submit a PR, if you manage to identify a fix for the issue, your contribution would be greatly appreciated by the community.
