### ISSUE TITLE
Utilizing GPU with Jetson Nano on BalenaOS Docker

### ISSUE THREAD

**Issue by mkbielaw** [ultralytics/ultralytics#7688]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm trying to utilize GPU with my algorithm using yolov8 to make it faster but I can't proceed because `torch.cuda.is_available()` is giving me `False`. I'm running my software on Jetson Nano flashed with Balena OS and I'm using a docker container. `nvidia-smi` also doesn't recognize any GPU. How do I make use of my GPU?

### Additional

The images I've tried using to install the drivers on them are:
`nvcr.io/nvidia/l4t-pytorch:r35.2.1-pth2.0-py3`
`ultralytics/ultralytics:latest-jetson`
`ultralytics/ultralytics:latest-arm64`

When trying with `nvcr.io/nvidia/l4t-pytorch:r35.2.1-pth2.0-py3` I install the ultralytics package with `pip`

I also tried installing packages seprately: nvidia-jetpack, nvidia-driver-450 and cuda but every time I'm getting errors on each of these images.

**Comment by Shassk** [comment]
> `nvidia-smi` also doesn't recognize any GPU

This is 100% a driver problem. In our projects we were using `nvidia/cuda:11.4.1-cudnn8-devel-ubuntu18.04` image. Obviously it's too old now, but you can try a newer version of it. We didn't have to install additional driver packages other than the ones required for TensorRT (Nvidia's own library, you can use YOLO exported to ONNX in it).

**Comment by Shassk** [comment]
Yes, that's why I've said it's too old, and you should try newer versions. Overall look for `nvidia/cuda` ones since this exact doesn't work. i've also had to spend some time searching for what will do the job.

**Comment by glenn-jocher** [comment]
@Shassk it seems like you're encountering architecture compatibility issues. For ARM64, you'll need to find an image that is specifically built for ARM64 architecture. The `nvidia/cuda` images you're referring to are typically for x86_64 architecture. I recommend searching for an ARM64 compatible Docker image that includes the necessary CUDA drivers for the Jetson Nano. Nvidia's JetPack SDK might also provide a suitable base image for your needs. Once you have the correct drivers and CUDA toolkit installed, `torch.cuda.is_available()` should return `True`. Good luck with your search!

**Comment by mkbielaw** [comment]
I made several attempts with more images:
`nvidia/cuda:12.3.1-base-ubuntu20.04`
`nvcr.io/nvidia/l4t-cuda:12.2.12-devel`
`nvcr.io/nvidia/l4t-cuda:12.2.2-devel-arm64-ubuntu22.04`
`nvcr.io/nvidia/pytorch:23.12-py3`

I'm getting a CUDA welcome message with `CUDA Version 12.3.1` but running `print(torch.version.cuda)` shows `None`.
Also I'm seeing `WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.`

**Comment by glenn-jocher** [comment]
@mkbielaw it appears that while the CUDA toolkit is installed, PyTorch is not detecting the GPU, which could be due to an issue with the PyTorch installation or a mismatch between the versions of PyTorch and CUDA. Ensure that you're using a PyTorch version that is compatible with CUDA 12.3.1 and is built for ARM64. You might need to look for a PyTorch build that is specifically tailored for the Jetson Nano or build PyTorch from source with the appropriate CUDA version. Additionally, verify that the NVIDIA drivers are correctly installed and that the Docker container has access to the GPU.

**Comment by mkbielaw** [comment]
> @mkbielaw it appears that while the CUDA toolkit is installed, PyTorch is not detecting the GPU, which could be due to an issue with the PyTorch installation or a mismatch between the versions of PyTorch and CUDA. Ensure that you're using a PyTorch version that is compatible with CUDA 12.3.1 and is built for ARM64. You might need to look for a PyTorch build that is specifically tailored for the Jetson Nano or build PyTorch from source with the appropriate CUDA version. Additionally, verify that the NVIDIA drivers are correctly installed and that the Docker container has access to the GPU.

From what I've read, Jetson Nano is supposed to have nvidia drivers already installed but `torch.cuda.is_available()`, `nvidia-smi` and `dkms status` return nothing. Should I then try to install the drivers anyway?
Regarding installing the compatible CUDA and PyTorch versions, should I install CUDA that's compatible with the current PyTorch or install PyTorch that's compatible with the current CUDA version?

**Comment by glenn-jocher** [comment]
@mkbielaw, it's crucial to match the PyTorch version with the CUDA version that's compatible with the Jetson Nano's architecture. Since `torch.cuda.is_available()` is returning `False`, it suggests that PyTorch may not be correctly recognizing the CUDA installation. You should use a PyTorch build that is compatible with your current CUDA version and is designed for ARM64. If the drivers are indeed missing, despite the expectation that they come pre-installed on the Jetson Nano, you may need to install them. Check the official Jetson Nano documentation or forums for the recommended driver installation process. Remember to ensure that your Docker container is configured to access the GPU.
