### ISSUE TITLE
Youtube live stream - AttributeError: 'NoneType' object has no attribute 'url'

### ISSUE THREAD

**Issue by modellers** [ultralytics/ultralytics#7694]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

Getting URL for youtube live stream fails:

**Recreate** by opening notebook `https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb`
You can skip all sections and go directly to Classification (section 3). Then replace `https://ultralytics.com/images/bus.jpg` with a youtube live stream `https://www.youtube.com/watch?v=goSxiItCi-w` 

**Expected**:
Same procedure except replace  with a fixed `https://ultralytics.com/images/bus.jpg` video `https://www.youtube.com/watch?v=m157nCJ7VeE`

**Actual**:

Stack trace
```
[/usr/local/lib/python3.10/dist-packages/ultralytics/data/loaders.py](https://localhost:8080/#) in get_best_youtube_url(url, use_pafy)
    528         import pafy  # noqa
    529 
--> 530         return pafy.new(url).getbestvideo(preftype="mp4").url
    531     else:
    532         check_requirements("yt-dlp")

AttributeError: 'NoneType' object has no attribute 'url'
```

### Environment

account_circle
Ultralytics YOLOv8.1.2 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 26.3/78.2 GB disk)

OS                  Linux-6.1.58+-x86_64-with-glibc2.35
Environment         Colab
Python              3.10.12
Install             pip
RAM                 12.67 GB
CPU                 Intel Xeon 2.30GHz
CUDA                12.1

matplotlib          ✅ 3.7.1>=3.3.0
numpy               ✅ 1.23.5>=1.22.2
opencv-python       ✅ 4.8.0.76>=4.6.0
pillow              ✅ 9.4.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.4>=1.4.1
torch               ✅ 2.1.0+cu121>=1.8.0
torchvision         ✅ 0.16.0+cu121>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 1.5.3>=1.1.4
seaborn             ✅ 0.13.1>=0.11.0

### Minimal Reproducible Example

```
from ultralytics import YOLO

model = YOLO('yolov8n-cls.pt')  # load a pretrained YOLOv8n classification model
model.train(data='mnist160', epochs=3)  # train the model
model('https://www.youtube.com/watch?v=P1e_MWJ1nQc')  # predict on an youtube livestream
```

### Additional

I can confirm that this worked before a month ago. Personally was using YOLOv8 on 8 live stream at once.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@modellers hello! Thank you for the detailed issue report. It seems like there's a problem with the YouTube URL processing when attempting to use a live stream. This could be due to changes in the YouTube API or the libraries we use to interface with it.

As a first step, please ensure that the dependencies related to video streaming, such as `pafy` and `yt-dlp`, are up to date. If the issue persists, it might be a more complex problem related to the specific live stream or a change in the way YouTube handles these streams.

If updating does not resolve the issue, please consider opening a new issue with the updated details, and we'll investigate further. Your contributions to the YOLO community are greatly appreciated, and we're here to help get this resolved. 🛠️

For more detailed guidance on Predict mode and troubleshooting, you can refer to our documentation at https://docs.ultralytics.com/modes/predict.

**Comment by glenn-jocher** [comment]
@modellers your stream address is not available on YouTube. This might be the problem. 
<img width="1763" alt="Screenshot 2024-01-21 at 17 33 54" src="https://github.com/ultralytics/ultralytics/assets/26833433/c9c9c0dd-7c9f-47c9-8d11-13f8f12f1522">

**Comment by glenn-jocher** [comment]
Valid YouTube URL results here. Marking issue as non-reproducible and invalid as appears to be user error.

<img width="1010" alt="Screenshot 2024-01-21 at 17 38 07" src="https://github.com/ultralytics/ultralytics/assets/26833433/888d64c7-c139-4409-9bed-e778da0679d7">

**Comment by modellers** [comment]
The following example uses stream https://www.youtube.com/watch?v=P1e_MWJ1nQc .
Maybe it is offline when you see it. But the same error occurs for other live streams (see list).

Yes, "None live streams" works fine.

<img width="1522" alt="Screenshot 2024-01-26 at 05 03 58" src="https://github.com/ultralytics/ultralytics/assets/115144400/bb36e267-27ee-4f35-8ef0-d2c5624991c4">

Live streams does not work (as they once did):

 - https://www.youtube.com/watch?v=ydYDqZQpim8
 - https://www.youtube.com/watch?v=R7vrbiDi0Tc
 - https://www.youtube.com/watch?v=P1e_MWJ1nQc

Thanks for a great library and for looking into this issue.

I am sure that you are correct, that there is a change in how Youtube handles the live stream. But it is not clear on how I can configure the YOLO library to make this work again. 

Please advice since IMO is testing this library to detect lava flow near Grindavík (a small town in Iceland).

**Comment by glenn-jocher** [comment]
@modellers, thank you for the additional context. It appears that the issue with live streams is consistent across different URLs, which suggests a broader issue with the stream handling rather than a one-off problem with a specific video.

We appreciate your patience and understanding as we look into this. In the meantime, please ensure all related dependencies are up to date. If the problem persists, it may indeed be related to changes on YouTube's end that are affecting the stream extraction process.

We will investigate this further and aim to provide a solution or workaround. Your use case for monitoring lava flow is important, and we're committed to supporting such valuable applications of our library. Keep an eye on the repository for updates, and thank you for your support of Ultralytics YOLOv8. 🌋🔍

**Comment by modellers** [comment]
Managed to fix this issue in a local version by using the "yt-dlp" library instead. 
This solution fails when "classifying" but works fine for "detection".

Since this configuration option is not available I solved it using environment variables.
What is the prefered way to pass configurations options?

**Comment by glenn-jocher** [comment]
@modellers hello! Great to hear you've found a workaround using the "yt-dlp" library for detection tasks. 🎉 For configuring options, using environment variables is a practical approach, especially when dealing with external libraries or when you need a quick fix. However, for a more integrated solution within YOLOv8, you might consider contributing to the repo or suggesting a feature that allows more flexible configuration options directly through the API or CLI arguments. This could enhance usability for everyone. Thanks for sharing your solution, and we're always open to community contributions to make YOLOv8 even better! 🚀
