### ISSUE TITLE
CLI tests are running twice

### ISSUE THREAD

**Issue by validatedev** [ultralytics/ultralytics#770]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

As I see on CI pipeline, these tests are running first:
https://github.com/ultralytics/ultralytics/blob/522f1937edb0728f1fb1ec6398ae56d7f476c3a4/.github/workflows/ci.yaml#L84-L107

then this file is going to work after that:
https://github.com/ultralytics/ultralytics/blob/522f1937edb0728f1fb1ec6398ae56d7f476c3a4/tests/test_cli.py

which confuses me as there's no need to run these tasks twice. Why it is happening?

**Comment by pderrenger** [comment]
@validatedev hi there! 🌟 The behavior you're observing is intentional. The initial CI pipeline runs basic tests, while the subsequent execution of `test_cli.py` provides a more in-depth examination of the CLI functionalities. This two-step process ensures comprehensive coverage of the CLI tests. If you have further questions or need additional help, feel free to ask!
