### ISSUE TITLE
Getting KeyError: 'backbone' when trying to train a model from scratch using a Roboflow dataset. 

### ISSUE THREAD

**Issue by AndreiSaliba** [ultralytics/ultralytics#7702]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I am getting this error when tying to train a model from scratch. I am following this tutorial with a custom exported dataset from Roboflow https://docs.ultralytics.com/integrations/weights-biases/#installation

```
 File "c:\Users\andre\OneDrive - Malta College of Arts, Science & Technology\Image Processing and Computer Vision\Home Assignment\IPCV-HomeAssignment\train.py", line 10, in <module>
    model = YOLO("./datasets/data.yaml", task='detect')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\anaconda3\envs\ipcv-ha\Lib\site-packages\ultralytics\engine\model.py", line 90, in __init__
    self._new(model, task)
  File "C:\Users\andre\anaconda3\envs\ipcv-ha\Lib\site-packages\ultralytics\engine\model.py", line 119, in _new
    self.model = (model or self._smart_load('model'))(cfg_dict, verbose=verbose and RANK == -1)  # build model
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\anaconda3\envs\ipcv-ha\Lib\site-packages\ultralytics\nn\tasks.py", line 233, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=ch, verbose=verbose)  # model, savelist
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\anaconda3\envs\ipcv-ha\Lib\site-packages\ultralytics\nn\tasks.py", line 637, in parse_model
    for i, (f, n, m, args) in enumerate(d['backbone'] + d['head']):  # from, number, module, args
                                        ~^^^^^^^^^^^^
KeyError: 'backbone'
```

**Comment by glenn-jocher** [comment]
@AndreiSaliba hello! It seems like there might be an issue with the configuration file (`data.yaml`) that you're using. The error indicates that the expected 'backbone' key is missing from the model configuration dictionary. This usually happens when the YAML file is not structured correctly or certain expected keys are missing.

Please double-check your `data.yaml` file to ensure it contains all the necessary keys, including 'backbone', and follows the correct format as outlined in our documentation. If you've made any modifications to the default configuration, you might want to revert to the original and make incremental changes to identify where the issue lies.

If the problem persists, please provide more details about the contents of your `data.yaml` file, and we'll be happy to help you troubleshoot further. 😊

**Comment by anushka20403** [comment]
Hey im facing the same error? Have u figured it out, please help me. Here's my yaml file:
names:
- '0'
- '11'
- '3'
- '4'
- '6'
- '8'
- '9'
nc: 7
roboflow:
  license: Public Domain
  project: eep_detection-u9bbd
  url: https://universe.roboflow.com/objet-detect-yolov5/eep_detection-u9bbd/dataset/1
  version: 1
  workspace: objet-detect-yolov5
train: /content/EEP_Detection-1/train/images
val: /content/EEP_Detection-1/valid/images

**Comment by glenn-jocher** [comment]
@anushka20403 hey there! It looks like the YAML file you've shared is primarily structured for dataset information. For the 'backbone' error you're encountering during training, the issue lies in the model's configuration file – not in the dataset YAML. 😊

The error suggests that the model configuration (usually a .yaml file detailing the model architecture) is missing the 'backbone' section, which is crucial for building the model structure.

Here's a quick step to check:
- Make sure you're specifying the correct model configuration file (.yaml) that includes the model architecture. This file is different from the dataset YAML (`data.yaml`) you've posted.

If you're training a custom model from scratch, ensure your model config YAML has sections like 'backbone', 'head', etc., structured similar to this simple example:

```yaml
# This is a simplified example structure.
backbone:
  # Layer details here
head:
  # Layer details here
```

If you're using one of the pre-configured models, referencing the model's name should suffice without needing to delve into the architecture YAML. For any further customizations or clarifications, we're here to help!
