### ISSUE TITLE
Yolov8 exported model not working

### ISSUE THREAD

**Issue by shahzeen031** [ultralytics/ultralytics#7722]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I have Train a Yolov8 for object detection on a custom dataset Now I want to export it or use it in my React application to make prediction on live camera. I tried both ways exported the model in Onnx and then exported it in tenserflow as a save model and then in tenserflow.js.

tried two ways to use the model in react first:
onnx but onnx gives an error Uncaught (in promise) TypeError: int64 is not supported
Can I export the model in int32? and what will be the best parameter setting in the export function to get best results?

Second way load the model in tenserflow.js but the predicted object is not the desired result object of YOLO I have send the image file according to the YOLO input format (1,3,640,640).

![image](https://github.com/ultralytics/ultralytics/assets/103788851/3d7df544-2aa6-474f-b361-baf466f5378b)

What parameters setting will work best for me?

**Comment by glenn-jocher** [comment]
@shahzeen031 hello,

Thank you for reaching out and detailing the issues you're encountering with the exported YOLOv8 model.

For the ONNX export issue with int64, it's important to ensure that the data types used are compatible with the ONNX runtime you're using. While YOLOv8 does not directly support exporting to int32, you might need to post-process the ONNX model using a tool that can convert data types.

Regarding the TensorFlow.js predictions, discrepancies can arise due to various reasons, such as differences in preprocessing or postprocessing steps. Ensure that the image preprocessing in your React application matches the preprocessing used during YOLOv8 training. This includes consistent normalization and resizing of the input images.

For the best parameter settings during export, refer to the Export section in our documentation, which provides guidance on optimizing the model for different platforms and use cases.

If the issue persists, please provide more details on the preprocessing steps and the exact commands used for exporting the model, so we can assist you more effectively.

**Comment by thebabyjay** [comment]
@shahzeen031 I am starting to dig into this kind of thing now.  Did you ever figure out how to make it work?
