### ISSUE TITLE
Performing segmentation on custom dataset with YOLOV8

### ISSUE THREAD

**Issue by EmielFeryn1** [ultralytics/ultralytics#7743]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I seem to making a mistake somewhere in the buildup of my custom segmentation dataset. My dataset contains polygons annotated with 4 points.

I receive these errors when trying to train:

train: WARNING ⚠️ No labels found in cache. See https://docs.ultralytics.com/datasets/detect for dataset formatting guidance.
train: New cache created: cache
WARNING ⚠️ No images found in cache, training may not work correctly. See https://docs.ultralytics.com/datasets/detect for dataset formatting guidance.

Last line of error:
len_cls, len_boxes, len_segments = (sum(x) for x in zip(*lengths))
ValueError: not enough values to unpack (expected 3, got 0)

This is how dataset is structured:
In label file:
class_id x1 y1 x2 y2 x3 y3 x4 y4 

dataset/
├── train/
│   ├── images/
│   └── labels/
└── val/
|    ├── images/
|   └── labels/
|---- train.txt
|---- val.txt

train.txt file:
./images/filename_0
./images/filename_1
...

yaml file:
names:
  0: class_0
path: ../datasets/test
test: test.txt
train: train.txt
val: val.txt

python file:
from ultralytics import YOLO
import torch
print(torch.cuda.is_available())

import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:512"

if __name__ == "__main__":
    model = YOLO('yolov8m-seg.pt')

    # Train the model on the COCO8 example dataset for 100 epochs
    results = model.train(data='training/test.yaml', epochs=100, imgsz=640, batch=18)

Thanks for reading! Does anybody notice a mistake?

**Comment by glenn-jocher** [comment]
@EmielFeryn1 hello!

It looks like you're encountering issues with your custom segmentation dataset structure. The error messages suggest that the dataset is not being recognized correctly, which is often due to a mismatch between the expected format and the actual format of your dataset.

For segmentation tasks, ensure that your dataset annotations are in the correct format as outlined in our segmentation documentation. The labels should be in a specific format that includes class IDs and segmentation polygons. If you're using polygons with 4 points, make sure they are correctly converted to the format YOLOv8 expects for segmentation.

Also, verify that your dataset paths in the YAML file are correct and that the image file paths in `train.txt` and `val.txt` are accurate and relative to the YAML file's location.

Lastly, ensure that the model you're using (`yolov8m-seg.pt`) is compatible with segmentation tasks and that you've set up the environment correctly for training.

If you continue to face issues, please refer to our segmentation documentation for more detailed guidance on setting up your dataset for segmentation tasks with YOLOv8. 📚

Best of luck with your training!
