### ISSUE TITLE
The running results of yolov8s_full_integer_quant.tflite are all 0

### ISSUE THREAD

**Issue by kuku-sichuan** [ultralytics/ultralytics#7747]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Use project to convert yolov8 to get yolov8s_full_integer_quant.tflite. When running, the results are all 0?
What is the difference between full_integer_quant and int8? Can it all run on Android?

**Comment by hu8813** [comment]
i have the same problem, full_integer_quant.tflite  (int8)  0 predictions,  int8.tflite or  integer_quant.tflite works tho

in June 2023, glenn wrote below about this Bug, but seems like it's not fixed yet:
https://github.com/ultralytics/ultralytics/issues/3443#issuecomment-1612953361

**Comment by glenn-jocher** [comment]
@hu8813 i'm sorry to hear you're experiencing issues with the `yolov8s_full_integer_quant.tflite` model. The difference between `full_integer_quant` and `int8` is that the former quantizes all model operations and tensors to integer-only, while the latter may still use floating-point operations for certain parts of the model.

If `int8.tflite` or `integer_quant.tflite` are working for you, it suggests that the full integer quantization may not be compatible with your specific use case or environment. This could be due to a variety of factors, including the quantization process itself or the inference engine you're using on Android.

Regarding the issue you mentioned, we are aware of it and are continuously working to improve the model and fix any outstanding bugs. Please ensure you are using the latest version of the repository, as updates and bug fixes are regularly committed.

For running on Android, both `full_integer_quant` and `int8` models should technically be supported, but the actual performance and compatibility can vary depending on the device and the Android Neural Networks API (NNAPI) version.

If you continue to face problems, please open a new issue with detailed information about your setup, including the exact commands or code you're using, and any logs or error messages you're receiving. This will help us diagnose the problem more effectively. Thank you for your patience and for being part of the YOLO community! 🚀
