### ISSUE TITLE
Active Learning - Saving as AVI file instead of Images

### ISSUE THREAD

**Issue by tristanfivaz** [ultralytics/ultralytics#7754]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi Everyone!
I was wondering if there was any support for the following query of mine:

I am using a custom trained license plate detection model from a live feed and want to save the prediction labels, as well as the original image, so I can continuously grow my dataset. However, when simulating this with a live feed such as a webcam, I get the labels saved every frame which is perfect, but an AVI file recording instead of actual images. I have experimented with cropped images and that works fine, however the individual, original frames with labels associated would be even better. I have attached images to show the current output.

```
results = model.predict(source="0", save_txt=True, save=True, save_crop=True, project="activeLearning/predict", name="inference", exist_ok=True)
```

![image](https://github.com/ultralytics/ultralytics/assets/42950803/7cc185be-62ea-4d2e-a17b-63baec892717)
![image](https://github.com/ultralytics/ultralytics/assets/42950803/e1adbfcf-f4da-46aa-9623-6c4c66a6f1b6)

**Comment by glenn-jocher** [comment]
@tristanfivaz hello!

Great to hear you're using YOLOv8 for license plate detection and active learning! 👍

To save individual frames with labels instead of an AVI file, you can adjust the `save` parameter in your `predict()` function. By default, `save` will store a video file when using a live feed. To save individual frames, set `save` to the format you prefer, such as 'jpg' or 'png', to save the frames as images.

Remember to check the documentation for the `predict` mode at https://docs.ultralytics.com/modes/predict for more details on the parameters you can use.

Keep up the good work with your dataset growth! If you have any more questions, feel free to ask. Happy detecting! 😊

**Comment by tristanfivaz** [comment]
Thankyou so much Glenn!

That helps so much.

:))

**Comment by glenn-jocher** [comment]
@tristanfivaz you're welcome! I'm glad I could help. If you have any more questions down the road, don't hesitate to reach out. Happy training! 😄🚀
