### ISSUE TITLE
Issue in installing ultralytics using pip

### ISSUE THREAD

**Issue by nitish9695** [ultralytics/ultralytics#7773]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Install

### Bug

(.venv) F:\Program\.venv\Scripts>pip install ultralytics==8.0.152
Collecting ultralytics==8.0.152
  Using cached ultralytics-8.0.152-py3-none-any.whl.metadata (28 kB)
Collecting matplotlib>=3.2.2 (from ultralytics==8.0.152)
  Using cached matplotlib-3.8.2-cp312-cp312-win_amd64.whl.metadata (5.9 kB)
Requirement already satisfied: numpy>=1.22.2 in f:\program\.venv\lib\site-packages (from ultralytics==8.0.152) (1.26.3)
Requirement already satisfied: opencv-python>=4.6.0 in f:\program\.venv\lib\site-packages (from ultralytics==8.0.152) (4.9.0.80)
Requirement already satisfied: pillow>=7.1.2 in f:\program\.venv\lib\site-packages (from ultralytics==8.0.152) (10.2.0)
Collecting pyyaml>=5.3.1 (from ultralytics==8.0.152)
  Using cached PyYAML-6.0.1-cp312-cp312-win_amd64.whl.metadata (2.1 kB)
Collecting requests>=2.23.0 (from ultralytics==8.0.152)
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting scipy>=1.4.1 (from ultralytics==8.0.152)
  Using cached scipy-1.12.0-cp312-cp312-win_amd64.whl.metadata (60 kB)
INFO: pip is looking at multiple versions of ultralytics to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following versions that require a different python version: 1.10.0 Requires-Python <3.12,>=3.8; 1.10.0rc1 Requires-Python <3.12,>=3.8; 1.10.0rc2 Requires-Python <3.12,>=3.8; 1.10.1 Requires-Python <3.12,>=3.8; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11; 1.9.0 Requires-Python >=3.8,<3.12; 1.9.0rc1 Requires-Python >=3.8,<3.12; 1.9.0rc2 Requires-Python >=3.8,<3.12; 1.9.0rc3 Requires-Python >=3.8,<3.12; 1.9.1 Requires-Python >=3.8,<3.12; 8.0.10 Requires-Python >=3.7,<=3.11; 8.0.11 Requires-Python >=3.7,<=3.11; 8.0.12 Requires-Python >=3.7,<=3.11; 8.0.13 Requires-Python >=3.7,<=3.11; 8.0.14 Requires-Python >=3.7,<=3.11; 8.0.15 Requires-Python >=3.7,<=3.11; 8.0.16 Requires-Python >=3.7,<=3.11; 8.0.17 Requires-Python >=3.7,<=3.11; 8.0.18 Requires-Python >=3.7,<=3.11; 8.0.19 Requires-Python >=3.7,<=3.11; 8.0.20 Requires-Python >=3.7,<=3.11; 8.0.21 Requires-Python >=3.7,<=3.11; 8.0.22 Requires-Python >=3.7,<=3.11; 8.0.23 Requires-Python >=3.7,<=3.11; 8.0.24 Requires-Python >=3.7,<=3.11; 8.0.25 Requires-Python >=3.7,<=3.11; 8.0.26 Requires-Python >=3.7,<=3.11; 8.0.27 Requires-Python >=3.7,<=3.11; 8.0.28 Requires-Python >=3.7,<=3.11; 8.0.29 Requires-Python >=3.7,<=3.11; 8.0.30 Requires-Python >=3.7,<=3.11; 8.0.31 Requires-Python >=3.7,<=3.11; 8.0.32 Requires-Python >=3.7,<=3.11; 8.0.33 Requires-Python >=3.7,<=3.11; 8.0.34 Requires-Python >=3.7,<=3.11; 8.0.7 Requires-Python >=3.7,<=3.11; 8.0.8 Requires-Python >=3.7,<=3.11; 8.0.9 Requires-Python >=3.7,<=3.11
ERROR: Could not find a version that satisfies the requirement torch>=1.8.0 (from ultralytics) (from versions: none)
ERROR: No matching distribution found for torch>=1.8.0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@nitish9695 hello! It seems like you're encountering an issue with the installation of the Ultralytics package due to a dependency on `torch`. The error message indicates that `pip` cannot find a compatible version of `torch` for your environment.

Please ensure that you have installed PyTorch correctly before attempting to install the Ultralytics package. You can visit the official PyTorch website for installation instructions tailored to your setup. Once PyTorch is installed, try installing the Ultralytics package again.

If you continue to face issues, please check that your Python version is compatible with the versions required by the Ultralytics package. The error log suggests that certain versions of the package require Python versions less than 3.12 and greater than or equal to 3.7.

For further guidance, you can refer to our documentation at https://docs.ultralytics.com. If the problem persists, feel free to provide more details about your environment, and we'll be happy to assist you further. 😊
