### ISSUE TITLE
How do I get the detected object coordinates and categories in yolov8 in real time and print them out

### ISSUE THREAD

**Issue by Sparklexa** [ultralytics/ultralytics#7774]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How do I get the detected object coordinates and categories in yolov8 in real time and print them out?

**Comment by glenn-jocher** [comment]
@Sparklexa to obtain detected object coordinates and categories in real-time with YOLOv8, you can use the Predict mode. When running predictions, the model outputs a list of detections for each image or frame, which includes the bounding box coordinates and the category of each detected object.

To print this information, you can access the results from the model's output and iterate through each detection. For each detection, you can extract the `x1`, `y1`, `x2`, `y2` coordinates (which represent the top-left and bottom-right corners of the bounding box), as well as the `class` and `confidence` for the detected object.

The output is typically structured in a way that you can easily loop through each detection and print the desired information in real-time. Please refer to the Predict mode documentation on our Ultralytics Docs for more detailed guidance on handling the output of the model. 🚀

**Comment by Saketspradhan** [comment]
@Sparklexa You can use the Predict mode. The model outputs a list of detections for each frame, containing bounding box coordinates and object categories. Iterate through these detections to extract `x1`, `y1`, `x2`, `y2` coordinates, class, and confidence.

**Comment by fatemehmeshkini** [comment]
hello there 

How do I get the detected object coordinates
on trained model by our data in yolov8 ?

my code:

!yolo task=detect mode=train model=[yolov8s.pt](http://yolov8s.pt/) data='data.yaml' epochs=20 imgsz=640 !yolo task=detect mode=val model='[best.pt](http://best.pt/)' data='data.yaml' !yolo task=detect mode=predict model='[best.pt](http://best.pt/)' conf=0.25 source='.png' hide_labels=True hide_conf=True

there is just one class.



I will thank if you may write the code please .it is necessary.

**Comment by glenn-jocher** [comment]
Hello! 🌟

It looks like you've done great setting up your training, validation, and prediction with YOLOv8! To get the detected object coordinates from your predictions, you can tweak the prediction code slightly. You need to run the prediction in Python and then access the `results` object returned by the model.

Here's a concise example that should help you get started:

```python
from ultralytics import YOLO

# Initialize the model with your custom trained 'best.pt'
model = YOLO('best.pt')

# Run prediction
results = model('your_image.png', conf=0.25)

# Loop through detections
for det in results.detections:
    x1, y1, x2, y2 = det.box.xyxy  # Bounding box coordinates
    conf = det.conf  # Confidence
    cls = det.cls  # Detected class ID
    print(f"Coordinates: {x1}, {y1}, {x2}, {y2}, Conf: {conf}, Class: {cls}")
```

This code assumes `'your_image.png'` is the image you want to run detection on. The loop prints out the coordinates, confidence, and class ID for each detected object. Since you mentioned there's just one class, the `cls` should always be `0` (or whatever index your single class has in `data.yaml`). 

Feel free to adjust the confidence threshold and add any additional parameters as needed. Happy coding!

**Comment by fatemehmeshkini** [comment]
thanks alot for your answer

 here ,when I run ,there is an error like this : 'ValueError: too many
values to unpack (expected 4)'
I do not know what values does it mean. bounding boxes has got for corners.
another thing is that when I run python code instead of previous one I
sent,it doesn't give me any output as predicted image while It does but
doesn't show.
my code is like this:

from ultralytics import YOLO
model = YOLO('best.pt')
results = model.train(data="data.yaml", epochs=20)  # train the model
results = model.val()
results = model('/image.png', conf=0.2, hide_labels=True,hide_conf=True

then this is your code for coordinate:

# Loop through detections
for det in results:
    x1, y1, x2, y2 = det.boxes.xyxy  # Bounding box coordinates
    conf = det.conf  # Confidence
    cls = det.cls  # Detected class ID
    print(f"Coordinates: {x1}, {y1}, {x2}, {y2}, Conf: {conf}, Class:
{cls}")

please help with finding coordinates and showing final detected image.
I really need it.


thank you .

**Comment by glenn-jocher** [comment]
@fatemehmeshkini hey there! 😊

Looks like you encountered a bit of a hiccup - no worries, let's tackle this together!

Regarding the `'ValueError: too many values to unpack (expected 4)'` issue, it seems there might have been a slight misinterpretation in unpacking the bounding box coordinates. To correct and simplify the code for getting detections and their coordinates, here’s a refined snippet:

```python
from ultralytics import YOLO

# Initialize and run predictions
model = YOLO('best.pt')
results = model('image.png', conf=0.25)

# Loop through detections
for det in results.detections:
    # Extract bounding box coordinates, confidence, and class ID
    x1, y1, x2, y2 = det.box.xyxy.int().tolist()
    conf = det.conf.item()
    cls = det.cls.item()
    print(f"Coordinates: {x1}, {y1}, {x2}, {y2}, Conf: {conf}, Class: {cls}")
```

To address the output not showing up, if you want to visualize the detection results on your image, here's how you can do it:

```python
# Visualize detected objects on the image
results.render()
# Show/save output
results.show()  # Will display the image with detections in a new window
# or use results.save('path/to/save/image') to save the image with detections
```

This should display the image with the detected objects marked by bounding boxes. Just make sure you’re running this in an environment that supports image windows (like Jupyter Notebooks or a Python script executed on a machine with a display).

I hope this helps clear things up and gets you moving forward with your project! Let me know if there's anything else I can help with! 🚀

**Comment by fatemehmeshkini** [comment]
This is great, thank you so much!

I could get the coordinates with help of your code ,thanks for helping. but
the code for showing final detected image doesn't work ,I think it is
because I use google colab to run but it isn't for colab, in fact I tried
to change it in the correct way but I couldn't ,if it is possible for you
to write a code in google colab to show the final detected image .

this is the error :

AttributeError                            Traceback (most recent call last)

<ipython-input-18-12b6cb8c716a> <https://localhost:8080/#> in <cell
line: 2>()      1 # Visualize detected objects on the image
----> 2 results.render()      3 # Show/save output      4
results.show()  # Will display the image with detections in a new
window      5 # or use results.save('path/to/save/image') to save the
image with detections


AttributeError: 'list' object has no attribute 'render'



thank you so much.

**Comment by glenn-jocher** [comment]
Hey there! 🎉

I'm glad to hear the code for extracting coordinates worked out well for you! About displaying the image in Google Colab, let's tweak the approach slightly. Since `results.show()` might not work directly due to the Colab environment limitations, we can use `matplotlib` to display the image inline.

Here's a simple way to show your detected image in Colab:

```python
import matplotlib.pyplot as plt

# Assuming 'results' is your predictions object from the YOLO model
# First, render the detections on the image
img = results.render()[0]  # [0] for the first image in batch

plt.figure(figsize=(10, 10))  # Adjust the figure size as needed
plt.imshow(img)  # Matplotlib expects images in RGB format
plt.axis('off')  # No axes for a clean view
plt.show()
```

This code should display your image with the detections right within your Colab notebook. 🖼️

Let me know if this helps or if you hit any more snags. Always happy to assist!
