### ISSUE TITLE
YoloV8 int8 coreml export error

### ISSUE THREAD

**Issue by ShubhamNagarkar** [ultralytics/ultralytics#7784]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

1. I am trying to export a custom-trained yolov8m.pt object detection model to coreml with int8 quantization. However, everytime I get the error saying ~" CoreML: Export failure: scikit-learn is required for k-means quantization." I checked my environment pip list and conda list, and I already do have the package installed. I tried to reinstall it but I still get the same error? Any idea as to why this is happening?

2. The same custom trained yolov8m.pt object detection model (49MB) when exported to coreML without quantization doubles in size. The exported best.mlmodel has a size of 98MB. Is this an expected behaviour? If yes, what is the intuition behind this?

**Comment by glenn-jocher** [comment]
@ShubhamNagarkar hello! Let's address your concerns:

1. For the `int8` CoreML export error, it seems like a potential environment issue where the script might not be recognizing your scikit-learn installation. Ensure that your environment is activated and that scikit-learn is accessible within the same environment where you're running the export command. If the issue persists, consider creating a fresh environment and reinstalling the dependencies.

2. Regarding the increase in size after exporting to CoreML without quantization, this can happen due to various reasons, such as the inclusion of metadata, conversion of weights to a different precision or format, or additional layers for compatibility. It's not unusual for the model size to change during the conversion process. Quantization typically helps reduce the model size, but since you're facing issues with `int8` quantization, you're seeing the unquantized size.

For further guidance on export modes and troubleshooting, please refer to our documentation on the Export mode. If you continue to encounter issues, feel free to open an issue with detailed error logs and environment information for more specific assistance. 😊

**Comment by rromanchuk** [comment]
@ShubhamNagarkar  I actually have this problem because I export to mlmodel/Neural Network/coremltools 6. I just run this directly. After exporting an mlmodel, i then let Xcode convert to mlpackage, then use coremltools 7 to run the compression.  Only a couple of lines.

```python
import coremltools as ct
from coremltools.models.neural_network import quantization_utils

model = ct.models.MLModel("best.mlpackage")
quantized_model = quantization_utils.quantize_weights(model, 8)
quantized_model.save("best-quantized.mlpackage")
```

ML Program is slightly different
https://apple.github.io/coremltools/docs-guides/source/optimizecoreml-api-overview.html
