### ISSUE TITLE
val can't validate exported model if not square resolution was used

### ISSUE THREAD

**Issue by CySlider** [ultralytics/ultralytics#7797]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Val

### Bug

I export my model to ".engine" with non square resolutions like 832x480

But when I try to evaluate them I get this warning:

WARNING ⚠️ updating to 'imgsz=832'. 'train' and 'val' imgsz must be an integer, while 'predict' and 'export' imgsz may be a [h, w] list or an integer, i.e. 'yolo export imgsz=640,480' or 'yolo export imgsz=640'

I get that train is limited to square only, but why also val?
I want to make sure I'm not loosing precision/recall due to the way I exported the model, so I really would like to validate it the way I use it later in detection.

### Environment

Ultralytics YOLOv8.1.5 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (NVIDIA RTX A4000, 16109MiB)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CySlider** [comment]
If I force to run val with img_size=832 on an engine exported model with img_size 832x840 I get this error:

AssertionError: input size torch.Size([1, 3, 832, 832]) not equal to max model size (1, 3, 480, 832)

**Comment by CySlider** [comment]
I did hack around a bit in the code, I had to adjust validate.py, dataset.py, base.py and augment.py to also work with the rectangular image format, but now the evaluation seems to run fine against my .engine exported model with dynamic=false and image size 480x832.

The hacks involves a hard coded piece of code*, so I can't offer a reasonable pull request, but I think it shows that it is possible with not much effort, and for someone who knows his way around, this should be a quite straight forward fix.

Mainly I had to a) allow rectangular image size in validate.py by seting max_dim=2 in the call to check_imgsz and repair a view positions where the code expects an int but now gets a tuple

* in augment.py I had to set new_shape hard to (480x832) as I could not quickly figure out why my other fixes made it become ((480, 832), (480, 832))

**Comment by glenn-jocher** [comment]
@CySlider hello! I'm glad to hear that you've been exploring the code and finding ways to work with non-square resolutions for validation. Your initiative is commendable, and it's great that you've managed to get the evaluation running with your modifications.

The current limitation to square resolutions in the 'val' mode is indeed something that can be addressed. While the 'train' mode requires square images due to batch uniformity and GPU memory optimization, the 'val' mode could potentially be more flexible.

Your findings and the fact that you've successfully hacked the code to support rectangular validation is valuable feedback for us. It suggests that with some careful adjustments, we could officially support rectangular image validation in future updates.

Although your changes are hard-coded and not suitable for a pull request, they provide a useful starting point for us to consider how to implement this feature properly. We'll take note of this and look into making the necessary changes in a more generalized and robust way.

Thank you for sharing your experience and contributing to the improvement of YOLOv8! Keep an eye on future releases where we might include enhanced support for non-square resolution validation. 🚀

**Comment by UyeYwb** [comment]
> If I force to run val with img_size=832 on an engine exported model with img_size 832x840 I get this error:
> 
> AssertionError: input size torch.Size([1, 3, 832, 832]) not equal to max model size (1, 3, 480, 832)

i also meet this question. when set input size(1,3,480,640),onnx output size is (1,3,640,640).   It takes the maximum value of width and height as its value, and all subsequent image processing parameters only have one parameter, instead of two parameters for width and height.
![image](https://github.com/ultralytics/ultralytics/assets/70866897/3622965e-80bc-4f10-afda-f30d7dc40641)

**Comment by glenn-jocher** [comment]
@UyeYwb the error you're encountering is due to a mismatch between the input size expected by the model and the size of the data being validated. The validation process currently expects a square input size, which is why you're seeing an assertion error when using a rectangular input size.

The issue with the onnx output size taking the maximum of width and height is known, and it's related to the way the model's architecture handles input sizes. We're aware that this can be a limitation for certain use cases, and it's something we're considering for future updates.

For now, the validation process is designed to work with square inputs, and any deviation from that might require manual adjustments to the code, as you've discovered. We appreciate your feedback and patience as we work towards making our models more flexible in handling different input shapes. Keep an eye on the repository for updates that might address this issue. 🛠️

**Comment by CySlider** [comment]
I did make a more proper patch for my use case that has no hard coded parts anymore. And I tried to be thorough in finding and adjusting all affected parts, but 

TAKE THIS PULL REQUEST WITH CARE

I am not confident enough to be sure to have not missed side effects. Especially my changes in the Mosaic part are to be looked at and tested. I tried to limit my rectangular changes to pt and engine format, as those are the ones I test with.

So yeah, here is the pull request, take it or leave it :-)

https://github.com/ultralytics/ultralytics/pull/7847

**Comment by glenn-jocher** [comment]
@CySlider, thank you for taking the time to create a patch and submit a pull request. Your effort to contribute to the YOLOv8 project is greatly appreciated. 🙌

We understand the caution you've expressed regarding the changes, especially with complex parts like Mosaic augmentation. Our team will review your pull request thoroughly, considering all potential side effects and ensuring that any modifications align with the broader goals and stability of the project.

Your initiative to extend support for non-square inputs in both 'pt' and 'engine' formats is a valuable step towards enhancing the flexibility of YOLOv8. We'll take a close look at your contributions and provide feedback or request changes as needed during the review process.

Thanks again for your contribution, and we encourage you to continue engaging with the YOLOv8 community. Your efforts help us all move forward together. 👍

**Comment by CySlider** [comment]
Thanks. I wonder most about the _cat_labels function in augement.py

Upon reviewing it, I think I have a clear bug there, but trying to solve it, leaves me puzzled and it seems a bit like there is already a bug.

I am talking about: 
https://github.com/ultralytics/ultralytics/blob/ee8888287436b1125dcdc5c7957684e694bb90ea/ultralytics/data/augment.py#L307

Which is called from _mosaic3 (3*1) _mosaic4 (2*2) and _mosaic9 (3*3) but seems to only fit for mosaic4. So a copy paste error? But this seems not like a bug that would go unpunished/unnoticed. 

Anyway my attempt to make it compatible with a tuple is clearly wrong.

**Comment by glenn-jocher** [comment]
@CySlider, thanks for diving into the details of the `_cat_labels` function in `augment.py`. It's great to see such a thorough review of the code.

The function is indeed designed to work with the Mosaic augmentation, which concatenates labels from multiple images. The original implementation was tailored for square input sizes, which is why you're encountering issues when adapting it for non-square resolutions.

Your observation about the potential discrepancy in how `_cat_labels` is called from different Mosaic functions is insightful. It's possible that the function has been working correctly for the typical use cases but might not handle non-standard scenarios as expected.

If you've identified a clear bug in your attempt to adjust the function for tuple input sizes, it would be best to revisit the logic and ensure it can handle both square and non-square resolutions consistently across all Mosaic types.

We appreciate your efforts to improve the codebase and encourage you to continue refining your patch. If you need further clarification or assistance, don't hesitate to reach out. Your contributions are valuable to the community. 👍

**Comment by NaumanHSA** [comment]
@CySlider I came up with this issue as well. I'm using an older version of YOLO (8.151.0) and I'm exporting my models to tflite to run on an Android device. So I was checking on the preprocessing adapted by ultralytics team.

I found that the LetterBox function returns images with dynamic heights while keeping the width the same as specified. YOLO model can handle dynamic input size, while the exported tflite model has fixed size.  On Android side, I'm resizing my images while keeping the aspect ratio and padding extra pixels to make them square. Will it affect the predictions considering the change in the input sizes? To tackle this, I'm thinking of modifying the YOLO LetterBox to return fixed size images e.g. (640x640) the same as I've done on Android side.

Second issue I found is the CenterCrop preprocessing for classification models. It is possible that CenterCrop may crop important information. I modified the CenterCrop to LetterBox for my use case. I think this can be fixed.
