### ISSUE TITLE
Runtime Error when Training While Using MPS

### ISSUE THREAD

**Issue by sn3kyJ3di** [ultralytics/ultralytics#7807]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

Training fails when device is set to MPS, works fine when set to CPU, below is the output from the terminal.  Epoch 1 starts and gets to ~25% then this:

Traceback (most recent call last):
  File "main.py", line 6, in <module>
    model.train(data="config.yaml", epochs=300, device="mps")
  File "/opt/homebrew/lib/python3.11/site-packages/ultralytics/engine/model.py", line 391, in train
    self.trainer.train()
  File "/opt/homebrew/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 208, in train
    self._do_train(world_size)
  File "/opt/homebrew/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 376, in _do_train
    self.loss, self.loss_items = self.model(batch)
                                 ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ultralytics/nn/tasks.py", line 79, in forward
    return self.loss(x, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ultralytics/nn/tasks.py", line 258, in loss
    return self.criterion(preds, batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ultralytics/utils/loss.py", line 210, in __call__
    targets = self.preprocess(targets.to(self.device), batch_size, scale_tensor=imgsz[[1, 0, 1, 0]])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ultralytics/utils/loss.py", line 174, in preprocess
    out = torch.zeros(batch_size, counts.max(), 5, device=self.device)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Trying to create tensor with negative dimension -1: [16, -1, 5]

### Environment

/Yolo/import ultralytics.py"
/opt/homebrew/lib/python3.11/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Ultralytics YOLOv8.1.5 🚀 Python-3.11.7 torch-2.3.0.dev20240110 CPU (Apple M2)
Setup complete ✅ (8 CPUs, 24.0 GB RAM, 903.6/926.4 GB disk)

### Minimal Reproducible Example

from ultralytics import YOLO

model = YOLO("yolov8n.yaml")
model = YOLO("yolov8n.pt")

model.train(data="config.yaml", epochs=300, device="mps")
metrics = model.val()

### Additional

I had a much smaller dataset previously and this training was able to complete.  My dataset has gotten a lot bigger, initially I was training on a couple hundred images and now its ~5000 train and ~1000 validate.

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@sn3kyJ3di hello! It seems like you're encountering a runtime error when training with the MPS device. This could be related to a specific issue with MPS compatibility or a bug in the code that surfaces under certain conditions, such as larger datasets.

Given that the error message indicates a negative dimension, it might be related to the handling of batch sizes or target processing. Since you mentioned that training with a smaller dataset worked previously, it's possible that the issue is tied to the scaling of the dataset size.

As you're willing to submit a PR, I would suggest investigating how the targets are preprocessed and ensuring that the batch size and other related parameters are being handled correctly for MPS. Also, please ensure that your environment is set up correctly for MPS and that you're using the latest version of the necessary libraries.

If you're able to isolate the issue, your contribution through a PR would be greatly appreciated by the community. For further guidance on contributing, you can refer to our contribution guidelines in the documentation.

Thank you for bringing this to our attention, and for your willingness to contribute to the YOLOv8 project! 🚀

**Comment by sn3kyJ3di** [comment]
So far it seems to be related to auto batch sizing in combination with using MPS. When I pass the device as "MPS" and set the batch manually to 64, it trains as expected. No batch, MPS, and a large dataset are what triggers it.  My dataset also had a lot of background images. To be continued...

**Comment by glenn-jocher** [comment]
@sn3kyJ3di, great detective work! It sounds like you've narrowed down the issue to the auto batch sizing feature when using MPS with a large dataset. Manually setting the batch size is a good temporary workaround. Your findings will be valuable for further investigation and potential fixes. Keep us updated on your progress, and if you identify a solution, a PR would be most welcome. Thanks for your efforts! 🌟

**Comment by zeobec** [comment]
> So far it seems to be related to auto batch sizing in combination with using MPS. When I pass the device as "MPS" and set the batch manually to 64, it trains as expected. No batch, MPS, and a large dataset are what triggers it. My dataset also had a lot of background images. To be continued...

I faced the same issue as yours which is I  unable to train using MPS. can you provide your solution how did you able to utilise MPS during training cause when I include device=mps also didnt work for me. Thankyou!

**Comment by sn3kyJ3di** [comment]
I am still working on it, but I have found that the better I get at curating my dataset - the less issues I have.  When I ran into the issue above I was using a dataset with an very large contingent of background images.  Its possible my issue is not a bug but I was hitting the limits of my hardware.  I haven't had the same issue since I cleaned up my dataset.

**Comment by glenn-jocher** [comment]
@sn3kyJ3di hello! Thank you for reporting this issue and providing detailed information. It seems like you're encountering a runtime error related to the MPS device on an Apple M2 chip when training with a larger dataset.

The error message indicates a problem with creating a tensor with a negative dimension, which suggests there might be an issue with the dataset or the preprocessing steps. Since you mentioned that training completed successfully with a smaller dataset, it's possible that the increase in dataset size is revealing an edge case or a bug that wasn't previously encountered.

As a first step, please ensure that your dataset annotations are correct and consistent. Also, verify that the dataset is correctly formatted according to the expected input structure for YOLOv8.

If the dataset is correctly formatted and the issue persists, it could be a bug related to MPS device handling within the YOLOv8 codebase. Since you're willing to submit a PR, we would greatly appreciate your contribution to help resolve this issue. Please feel free to fork the repository, make the necessary changes, and submit a PR for review.

In the meantime, as a workaround, you might want to try training on a subset of your dataset to see if the issue is related to a specific part of the data or if it's a more general problem with MPS handling.

If you need further assistance, don't hesitate to reach out. Our community is always here to help! 🛠️🚀

**Comment by sn3kyJ3di** [comment]
I am going to close this issue out as I do not believe its a bug, it has happened to me a couple of times and I suspect its caused by one of two things: imbalanced dataset or the hardware limits of the machine I am using

**Comment by glenn-jocher** [comment]
@sn3kyJ3di thanks for the update! It's really insightful to consider the impact of dataset balance and hardware limitations on training performance. If you find more specific patterns or have insights in the future, feel free to share or reopen this issue. Happy coding! 😊👍

**Comment by eripe970** [comment]
Had the same issue, the workaround for me was just to add some more images to the dataset and then it worked again.

**Comment by glenn-jocher** [comment]
@eripe970 Thanks for sharing your experience! It's great to hear that adding more images to your dataset resolved the issue. Dataset balance and size can indeed play a crucial role in training stability. If you encounter any other challenges or have further insights, feel free to share. Happy training! 😊
