### ISSUE TITLE
how to obtain and postprocess the output tensor after inference of onnx model in c++

### ISSUE THREAD

**Issue by ZZJzhou** [ultralytics/ultralytics#7815]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I recently apply yolov8pose model to onnxrumtime and i am new to C++.
I have issues about applying onnxruntime inference:
Here is my code:
```
    // vector to tensor
    std::vector<Ort::Value> input_tensors;
    input_tensors.emplace_back(vec_to_tensor<float>(input_tensor_values, input_shape));

    // double-check the dimensions of the input tensor
    assert(input_tensors[0].IsTensor() && input_tensors[0].GetTensorTypeAndShapeInfo().GetShape() == input_shape);
    std::cout << "\ninput_tensor shape: " << print_shape(input_tensors[0].GetTensorTypeAndShapeInfo().GetShape()) << std::endl;
    

    // pass data through model
    std::vector<const char*> input_names_char(input_names.size(), nullptr);
    std::transform(std::begin(input_names), std::end(input_names), std::begin(input_names_char),
                   [&](const std::string& str) { return str.c_str(); });

    std::vector<const char*> output_names_char(output_names.size(), nullptr);
    std::transform(std::begin(output_names), std::end(output_names), std::begin(output_names_char),
                   [&](const std::string& str) { return str.c_str(); });

    std::cout << "Running model..." << std::endl;
    try {
      auto output_tensors = session.Run(Ort::RunOptions{nullptr}, input_names_char.data(), input_tensors.data(),
                                        input_names_char.size(), output_names_char.data(), output_names_char.size());
      std::cout << "Done!" << std::endl;

      // double-check the dimensions of the output tensors
      // NOTE: the number of output tensors is equal to the number of output nodes specifed in the Run() call
      assert(output_tensors.size() == output_names.size() && output_tensors[0].IsTensor());
      if (output_tensors[0].IsTensor())
        {
        float* outputData = output_tensors[0].GetTensorMutableData<float>();
        auto outputInfo = output_tensors[0].GetTensorTypeAndShapeInfo();
        std::cout << "output_tensor shape: " << print_shape(outputInfo.GetShape()) << "\n";
        size_t dim1 = outputInfo.GetShape()[0];
        size_t dim2 = outputInfo.GetShape()[1];
        size_t dim3 = outputInfo.GetShape()[2];
        std::cout << "dim1 " << dim1 << "\n";
        std::cout << "dim2 " << dim2 << "\n";
        std::cout << "dim3 " << dim3 << "\n";
        // transpose output tensor from (1,20,33600)to (1,33600,20)
        std::vector<std::vector<std::vector<int>>> output_transposed(dim1, std::vector<std::vector<int>>(dim3, std::vector<int>(dim2)));

        for (size_t i = 0; i < dim1; ++i) {
            for (size_t j = 0; j < dim2; ++j) {
                for (size_t k = 0; k < dim3; ++k) {
                    output_transposed[i][k][j] = outputData[i * k * j + k * j + j];
                }
            }
        }
```
I use a customized yolov8pose.onnx which estimate 5 keypoints.
The output_tensor shape of the same onnx model in python is (1,20, 8400), where 20 is related to the keypoints and 8400 is anchors.
However, the output_tensor shape in C++ is (1,20,33600).
And How can I obtain postprocess the proper outputtensor, because the outputData from GetTensorMutableData is not even 20*33600 shape and and final result is unreasonable.
Can anyone help me figure it out?

**Comment by glenn-jocher** [comment]
@ZZJzhou hello! It looks like you're on the right track with running inference using ONNX Runtime in C++. The discrepancy in the output tensor shape between Python and C++ might be due to differences in how the model was exported or how the data is being interpreted.

For post-processing the output tensor in C++, you'll need to understand the format of the output data. Typically, YOLO models output a tensor where each row corresponds to a detection and includes information such as bounding box coordinates, confidence score, and class probabilities.

To post-process the output:
1. Ensure you're interpreting the output tensor correctly. The shape might represent [batch, number of anchors * (5 + number of classes), grid height * grid width] or similar, depending on the model.
2. Apply the sigmoid function to the relevant parts of the output to obtain probabilities.
3. Decode the bounding boxes and keypoints from the output tensor.
4. Apply Non-Maximum Suppression (NMS) to filter overlapping detections.

For keypoints, the output might include additional values per anchor for the keypoint coordinates, which you'll need to decode similarly to the bounding boxes.

Since you're working with a custom model, ensure that the output tensor format matches your expectations and that you're applying the correct transformations. For more detailed guidance on post-processing steps, please refer to our documentation on the Predict mode, which outlines the general process for handling model outputs.

Keep in mind that the output tensor's shape and content will directly depend on how the model was trained and exported. If you continue to experience issues, you might want to revisit the export process to ensure compatibility with ONNX Runtime in C++. Good luck! 🚀

**Comment by ZZJzhou** [comment]
Thanks for replying.
The export process is like following
```
from ultralytics import YOLO

model = YOLO('best.pt')  # load a custom trained model
model.export(format='onnx', imgsz=1280)
```
And the best.onnx has been verified correct in python, where the output tensor has shape (1, 8400, 20), and I decode the bounding boxes and keypoints from the output tensor and apply Non-Maximum Suppression (NMS) to filter overlapping detections. 
Since I never apply the sigmoid function in python, I neither applied it in c++.
I used the exact same onnx model and same preprocessing methods, but obtain the output tensor with shape (1, 33600, 20). And when I apply the same decoding and NMS procedure in c++, I cannot get the correct result anymore.
If I miss the sigmoid function, can you explain more about it, which part should be included and if the confidences of boxes and keypoints from output tensor not yet the final values.

**Comment by glenn-jocher** [comment]
@ZZJzhou, it's great to hear that your ONNX model is working correctly in Python. The difference in output tensor shape between Python and C++ is unusual if the same model and preprocessing are used. The sigmoid function is typically applied to certain parts of the output tensor to convert the raw model outputs into probabilities, which are then used for confidence scores and class predictions.

Here's a concise breakdown of what you might need to consider:

1. **Sigmoid Function**: In YOLO models, the output tensor often contains raw predictions that need to be transformed into probabilities. The sigmoid function is applied to the objectness score and class predictions. If you didn't explicitly apply it in Python, it might be implicitly applied in the post-processing functions provided by the YOLOv8 library.

2. **Output Tensor Shape**: The expected shape of (1, 8400, 20) suggests that there are 8400 anchor boxes and 20 values per anchor box. If you're seeing a different shape in C++, verify that the input size and model configuration are identical to those used in Python.

3. **Decoding and NMS**: Ensure that the decoding process (extracting bounding boxes and keypoints) and NMS are implemented correctly in C++. Any discrepancies in these steps could lead to incorrect results.

If you're not applying the sigmoid function in C++, and the model expects it, you'll need to apply it to the relevant parts of the output tensor before decoding the boxes and keypoints. The parts that require the sigmoid function typically include the objectness score and class probabilities. The exact indices depend on the model's output format.

To resolve the issue, double-check the preprocessing and post-processing steps in C++ and ensure they match the Python implementation. If the problem persists, consider revisiting the model export process or reviewing the ONNX Runtime documentation for any C++-specific considerations.
