### ISSUE TITLE
How to Change the Colors of Bounding Boxes and Segmentation Masks

### ISSUE THREAD

**Issue by srheomtear** [ultralytics/ultralytics#7831]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I would like to know how to change the colors of bounding boxes and segmentation masks. In my dataset, there are three classes, and I want to specify colors for each class. I looked at the plotting.py file, but I'm not sure where to make the changes. Could you please provide guidance on this?

Thank you.

**Comment by glenn-jocher** [comment]
@srheomtear hello! To customize the colors of bounding boxes and segmentation masks for each class in YOLOv8, you'll need to adjust the class color definitions within the code. This is typically managed by a color palette or a specific array that maps classes to colors.

For bounding boxes, look for the section in the code where the colors are assigned based on class IDs. You can define a custom color for each class ID in the form of RGB tuples.

For segmentation masks, the process is similar, but you'll need to locate where the mask colors are applied and modify the corresponding color assignments for each class.

Remember to maintain the readability and structure of the code while making these changes, and always backup the original file before making modifications. For further details on customizing aspects of your model, please refer to our documentation at https://docs.ultralytics.com. Happy coding! 😊🎨

**Comment by srheomtear** [comment]
@glenn-jocher Thank you for your response! I understand that I need to modify the plotting.py file, but I'm not sure specifically which code to change and how to change it. I would appreciate it if you could provide examples of the modifications. I apologize for the inconvenience and appreciate your assistance.

**Comment by glenn-jocher** [comment]
@srheomtear, I'm glad to assist! While I can't provide code examples, I'll guide you more specifically. In the `plotting.py` file, locate the function responsible for drawing bounding boxes or masks. Within this function, there should be a part where colors are assigned based on class IDs, often using a colormap or a predefined list of colors.

To customize colors, you can create a dictionary mapping class IDs to your desired RGB color tuples. Then, update the color assignment in the function to use your custom mapping instead of the default one.

Please refer to the comments and documentation in the `plotting.py` file for more details on where these changes should be made. If you need further guidance, our documentation at https://docs.ultralytics.com is a great resource. Good luck! 🚀
