### ISSUE TITLE
Unable to sort the data the in correct way for multiobject yolo pose

### ISSUE THREAD

**Issue by MuhammadHammadBashir** [ultralytics/ultralytics#7836]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have data having two objects and every object has multiple points,  (23,11) I was facing error for having heterogenous number of points.  So I made them regular by putting zero padding at end of 2nd  object.
Now I am having 74, keypoints for each row,   1 id + 4 bounding box + (23*3)=69 points for both object,  I have two lines.

My yaml looks like this  # number of classes
nc: 2
names:
  0: A
  1: B
nkpt: 46
kpt_shape: [46, 3]

but model starting saying he is looking for  46*3=138 +5   in totla 143 points,  so every image is getting corrupted,
Plz help me in resolving this.

**Comment by glenn-jocher** [comment]
@MuhammadHammadBashir hello! It seems like there's a mismatch between the expected keypoints format in your dataset and the model's configuration. For pose estimation with YOLOv8, each keypoint is typically represented by three values (x, y, visibility), and the model expects a consistent number of keypoints for each object.

In your case, you have two objects with a different number of keypoints, and you've tried to regularize this by zero-padding. However, the model is expecting `nkpt * 3` values for keypoints, plus 5 for the bounding box and class ID, which totals to 143 as per your description.

To resolve this, ensure that your dataset is structured correctly with the expected number of keypoints for each object. If each object should have 23 keypoints, then `nkpt` should be set to 23, not 46, and your dataset should reflect this with 23 keypoints for each object, zero-padded if necessary to maintain consistency.

Make sure your YAML configuration matches the actual structure of your dataset. If each object has 23 keypoints, your `kpt_shape` should be `[23, 3]`, not `[46, 3]`. Adjust your dataset accordingly so that each line has the correct number of keypoints plus the bounding box and class ID.

If you continue to face issues, please refer to the pose estimation documentation for more detailed guidance on setting up your dataset and configuration file. 📚
