### ISSUE TITLE
How to get the all masks when the instance is consist of disconnected zones in segmentation task?

### ISSUE THREAD

**Issue by qiangxinglin** [ultralytics/ultralytics#7880]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I use YOLOv8-seg to train a segmentation model. After the training, I enable the `save=True` arg in `Model.predict` to save the visualized result (example below).
However, when I use `save_txt=True` to export the mask, I found it only save one of the disconnected zone.  
In the following example, only the bottom pink mask will be saved.
![Snipaste_2024-01-29_20-03-00](https://github.com/ultralytics/ultralytics/assets/20382522/b2f65837-5e19-4d6d-84ac-b46784200710)
I also check the `result.masks.xy`, it indeed only contain the bottom zone.  
So how can I get the full masks? 

Code snippets
```
model = YOLO('runs/segment/train/weights/best.pt')
# 0: the main dark zone 
# 1: the wrapper of 0, namely the MEDIA
result = model('test.png', save=True, save_txt=True, classes=1)
print(result[0].masks.xy) # only the bottom zone is returned
```

**Comment by glenn-jocher** [comment]
@qiangxinglin hello! For disconnected zones in segmentation tasks using YOLOv8, the model should ideally detect and segment each distinct zone as a separate instance. If you're observing that only one zone is being saved, it might be due to the post-processing thresholding that merges or discards smaller segments.

To ensure you get all disconnected masks, you may need to adjust the confidence and IoU thresholds to be more inclusive of smaller or less confident segments. Additionally, inspect the `result.masks` object to see if the masks are being detected but not saved due to the saving criteria.

If after adjusting the thresholds you still face issues, it could be related to the model's ability to distinguish between closely spaced or similar segments. In such cases, further training with more representative data of disconnected zones or tweaking the model architecture might be necessary.

For a more detailed guide on adjusting these parameters and understanding the segmentation output, please refer to the segmentation task documentation at https://docs.ultralytics.com/tasks/segment. If the issue persists, feel free to open an issue on the repo with details for further assistance. 😊

**Comment by qiangxinglin** [comment]
@glenn-jocher Thank you for your advise! After playing with `iou` and `conf` args during prediction, the issue still persists. Here attached the model and test image. Help wanted! 
[disconnected.zip](https://github.com/ultralytics/ultralytics/files/14091752/disconnected.zip)

**Comment by glenn-jocher** [comment]
@qiangxinglin Thanks for the update! If adjusting the `iou` and `conf` parameters didn't resolve the issue, it's possible that the model may need further tuning or the data requires preprocessing to better handle disconnected zones. Since the issue is persistent, I recommend opening a new issue with the details you've provided here, including the model and test image. Our team will take a closer look and assist you further. Remember to include any additional information that might help us understand the problem better. Thanks for your patience! 🌟
