### ISSUE TITLE
About the GPU frequency drop during model prediction

### ISSUE THREAD

**Issue by Mrfat-lab** [ultralytics/ultralytics#7903]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

First of all, thanks to all the yolov8 developers for giving such a wonderful experience about predicting obj.
However, when I use the 'yolov8n.engine'(FP16,which is exported by 'yolov8n.pt') to predict the "bus.jpg", I try to figure out how long it will take on the picture. so I use the following code .
```python
from ultralytics import YOLO
import time
# Load the exported TensorRT model
tensorrt_model = YOLO('yolov8n.engine')
start=time.time()
for i in range(1000):
    results = tensorrt_model('bus.jpg',stream=True)
    for result in results:
        print('over')
end=time.time()
print((end-start),'ms')
``` 

1. I find it will take 18ms to run the model once on average. It is confusing that  it took so much time. Because as the terminal showed'Speed: 2.0ms preprocess, 1.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)', the real time is longer than this which only took 4ms. I am trying to increases the frames on video capturing so I really wonder why it happens ?

2. When I increase the for loop to 2000, the model  uses 40ms each time which is much more longer than 18ms. I checked GPU-Z to figure it out and I found that when I ran the program at the beginning, the GPU frequency could reach 2000+HZ, but after a few seconds, the frequency dropped to a few hundred HZ. But at this time, the GPU LOAD was still high at about 40%, and the frequency remained at a few hundred HZ. I also checked the CPU, memory, and video memory and found no abnormal occupancy. Why is this?（My GPU is NVIDIA GeForce RTX 4070 Super）

3. You can see the results in following pics
![1000-loop-ending](https://github.com/ultralytics/ultralytics/assets/106853854/84f32f23-77d9-4c85-afd6-f39aa39b7947)
![2000-loop-ending](https://github.com/ultralytics/ultralytics/assets/106853854/f76d2656-2706-428a-8f98-ebca0507fe15)
![model-start-GPUZ](https://github.com/ultralytics/ultralytics/assets/106853854/9eb53d80-fda6-4927-97bd-83d3b843a9a6)
![running-GPUZ](https://github.com/ultralytics/ultralytics/assets/106853854/0e0c0292-81dd-4f7a-952b-94858211c8b9)

**Comment by glenn-jocher** [comment]
@Mrfat-lab hello! Thanks for reaching out and for your kind words about YOLOv8. 🚀

Regarding your observations:

1. The discrepancy between the reported speed and your measured time could be due to several factors, including I/O latency, image loading, and additional overhead in your loop. The terminal-reported speeds typically reflect the model's raw inference time, not the entire end-to-end process.

2. The GPU frequency drop you're experiencing might be related to thermal throttling or power management by the GPU. When the GPU is under a consistent load, it may reduce its clock speed to maintain a safe operating temperature or to stay within power limits.

3. For the images you've mentioned, it seems there might be an issue with the links, but generally, GPU-Z screenshots can help identify if thermal throttling or power limits are causing the frequency drops.

To further investigate, you might want to monitor the GPU temperature and power draw during inference. Also, ensure that your system's power settings are optimized for performance. If the issue persists, consider reaching out to the GPU manufacturer or checking for any known issues with the specific GPU model you're using.

For more detailed guidance on model performance and optimization, you can refer to our documentation at https://docs.ultralytics.com. Keep in mind that continuous, high-intensity tasks can lead to thermal throttling, which is a hardware-level behavior outside the scope of the YOLOv8 model itself.

Hope this helps, and happy detecting!

**Comment by Mrfat-lab** [comment]
@glenn-jocher Thanks for replying, however, I  have checked the temperature of GPU that is only 53° which probably won't lead to thermal throttling. When I run a game, it can reach a high frequency level. Maybe I should check the GPU settings. Thanks again.

**Comment by glenn-jocher** [comment]
@Mrfat-lab You're welcome! Yes, checking the GPU settings seems like a good next step, especially since gaming performance indicates that your hardware can sustain higher frequencies under load. Also, consider looking into any specific power management settings that might affect long-running tasks differently than short bursts of activity like gaming. If you need further assistance, our documentation might provide additional insights. Keep up the great work! 👍
