### ISSUE TITLE
Segmentation fault raspberry pi 5

### ISSUE THREAD

**Issue by pythonstuff8** [ultralytics/ultralytics#7914]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

When I try to predict using a pt file it says segmentation fault(works if I use onnx or tflite)using raspberry 5 bookworm

### Environment

Ultralytics YOLOv8.0.81  Python-3.11.2 torch-2.1.0 CPU
Setup complete (4 CPUs, 7.9 GB RAM, 25.9/219.6 GB disk)

### Additional

When I run a pt file I get segmentation fault

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@pythonstuff8 hello! A segmentation fault typically indicates a memory access violation, which can be tricky to diagnose. Since you mentioned that the issue occurs with a `.pt` file but not with ONNX or TFLite, it might be related to the PyTorch version or a compatibility issue with the Raspberry Pi hardware.

Here are a few steps you can take to troubleshoot the issue:
1. Ensure that your Raspberry Pi OS and all libraries are up to date.
2. Verify that your `.pt` model file is not corrupted and is compatible with the PyTorch version you're using.
3. Check for any known issues with PyTorch on Raspberry Pi, especially regarding CPU-only inference.
4. Reduce the model size or input resolution if memory limitations might be causing the fault.
5. Consider running the model inference in a more controlled environment, like a virtual environment, to rule out any conflicts with other installed packages.

If the problem persists, please provide more details on the error message and the steps leading up to the segmentation fault. This will help us better understand the context and potentially identify the cause. Meanwhile, you can refer to our documentation for more information on the Predict mode and troubleshooting tips.

Thank you for bringing this to our attention, and we appreciate your patience as we work to resolve this issue. 🛠️

**Comment by Skillnoob** [comment]
@pythonstuff8 can you run `yolo checks` and share the output.
Also please share the code you are trying to run.

**Comment by lakshanthad** [comment]
Hello,

I have also tried on my Raspberry Pi 4 with the latest Bookworm OS and latest PyTorch 2.2.0 and no issues at all. 

Below is my setup for reference:

```
pi@raspberrypi:~ $ yolo checks
Ultralytics YOLOv8.1.8 :rocket: Python-3.11.2 torch-2.2.0 CPU (Cortex-A72)
Setup complete :white_check_mark: (4 CPUs, 1.8 GB RAM, 6.5/14.0 GB disk)
OS                  Linux-6.1.0-rpi7-rpi-v8-aarch64-with-glibc2.36
Environment         Linux
Python              3.11.2
Install             pip
RAM                 1.80 GB
CPU                 Cortex-A72
CUDA                None
matplotlib          :white_check_mark: 3.8.2>=3.3.0
numpy               :white_check_mark: 1.26.3>=1.22.2
opencv-python       :white_check_mark: 4.9.0.80>=4.6.0
pillow              :white_check_mark: 10.2.0>=7.1.2
pyyaml              :white_check_mark: 6.0.1>=5.3.1
requests            :white_check_mark: 2.31.0>=2.23.0
scipy               :white_check_mark: 1.12.0>=1.4.1
torch               :white_check_mark: 2.2.0>=1.8.0
torchvision         :white_check_mark: 0.17.0>=0.9.0
tqdm                :white_check_mark: 4.66.1>=4.64.0
psutil              :white_check_mark: 5.9.8
py-cpuinfo          :white_check_mark: 9.0.0
thop                :white_check_mark: 0.1.1-2209072238>=0.1.1
pandas              :white_check_mark: 2.2.0>=1.1.4
seaborn             :white_check_mark: 0.13.2>=0.11.0
```

It should not be a memory issues because I am running on a 2GB version of the Raspberry pi 4. 

Could you please update to PyTorch 2.2.0 and try again?

**Comment by pythonstuff8** [comment]
I reinstalled everything And it worked thx

**Comment by lakshanthad** [comment]
Great! Glad to hear that!
