### ISSUE TITLE
YOLOv8 init with pt but always download pretrain model form github

### ISSUE THREAD

**Issue by keeper-jie** [ultralytics/ultralytics#7915]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

YOLOv8 init with pt but always download pretrain model form github
code:
```
from ultralytics import YOLO

# Load a model
model = YOLO(model="/data/liujie/fall_detect/resources/coco_pretrain/yolov8l.pt")  # load a pretrained model (recommended for training)
results = model.train(data='/data/liujie/fall_detect/resources/dataset/fall_down.yaml', epochs=300, imgsz=640, device=0, cache=True, batch=-1, name='yolov8l-fall_down')  # results = model.train(resume=True)
metrics = model.val()  # evaluate model performance on the validation set
```
log:
```
Ultralytics YOLOv8.1.8 🚀 Python-3.10.13 torch-2.0.1+cu117 CUDA:0 (NVIDIA RTX A6000, 48677MiB)
engine/trainer: task=detect, mode=train, model=/data/liujie/fall_detect/resources/coco_pretrain/yolov8l.pt, data=/data/liujie/fall_detect/resources/dataset/fall_down.yaml, epochs=300, time=None, patience=50, batch=-1, imgsz=640, save=True, save_period=-1, cache=True, device=0, workers=8, project=None, name=yolov8l-fall_down2, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/yolov8l-fall_down2
Overriding model.yaml nc=80 with nc=4

                   from  n    params  module                                       arguments                     
  0                  -1  1      1856  ultralytics.nn.modules.conv.Conv             [3, 64, 3, 2]                 
  1                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  2                  -1  3    279808  ultralytics.nn.modules.block.C2f             [128, 128, 3, True]           
  3                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]              
  4                  -1  6   2101248  ultralytics.nn.modules.block.C2f             [256, 256, 6, True]           
  5                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]              
  6                  -1  6   8396800  ultralytics.nn.modules.block.C2f             [512, 512, 6, True]           
  7                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]              
  8                  -1  3   4461568  ultralytics.nn.modules.block.C2f             [512, 512, 3, True]           
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  3   4723712  ultralytics.nn.modules.block.C2f             [1024, 512, 3]                
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  3   1247744  ultralytics.nn.modules.block.C2f             [768, 256, 3]                 
 16                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  3   4592640  ultralytics.nn.modules.block.C2f             [768, 512, 3]                 
 19                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]              
...
Transferred 589/595 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
Downloading https://github.com/ultralytics/assets/releases/download/v8.1.0/yolov8n.pt to 'yolov8n.pt'...
```

# how to load pretrain model without download form github

**Comment by glenn-jocher** [comment]
@keeper-jie hello! It seems like you're trying to load a pretrained model from a local path but YOLOv8 is still attempting to download the model from the internet. This can happen if the model file path is incorrect or not accessible.

Please ensure that the path to your pretrained model is correct and the file is indeed at that location. If the path is correct and the file exists, YOLOv8 should use the local `.pt` file without downloading it again.

If you continue to face issues, double-check the file permissions and ensure that the Python environment has read access to the file. If the problem persists, please provide more details in a new issue, and we'll be glad to help you troubleshoot further. 😊

**Comment by keeper-jie** [comment]
I use yolov8 docker to solve it.

I think the problem is model file path is incorrect or not accessible.

**Comment by glenn-jocher** [comment]
@keeper-jie hi there! 😊 It looks like you've found a solution using the YOLOv8 Docker environment, and you're right, the issue was likely due to an incorrect or inaccessible model file path. Great job troubleshooting! If you need further assistance or have more questions, feel free to ask. Happy detecting with YOLOv8! 🚀

**Comment by trianta2** [comment]
I believe this occurs due to the AMP check:

https://github.com/ultralytics/ultralytics/blob/dae4ce8307fc38990b959cd5e783a7e3cd82eb3d/ultralytics/utils/checks.py#L652

Which triggers a download. This is unfortunate, not only because the download is unnecessary in the instance the model is already using another local `yolov8n.pt`, but because we are also littering the `cwd`.

**Comment by glenn-jocher** [comment]
@trianta2 hey there! Thanks for bringing this up. 😊 It looks like you've pinpointed the AMP check causing the download issue, which indeed can be inconvenient.

For a quick workaround avoiding this AMP-triggered download, especially when using a specific local `yolov8n.pt`, you could temporarily bypass the AMP check by ensuring it's deactivated or by setting the model to run on CPU explicitly. This way, the check that leads to the download will be bypassed.

Here's a tiny code snippet to force the model onto CPU, which might help avoid the AMP check:

```python
import torch
from ultralytics import YOLO

device = 'cpu'
model = YOLO('path_to_local_yolov8n.pt', device=device)
```

The usage of Docker offers a controlled environment where you can more easily manage dependencies and paths, potentially avoiding path-related issues. However, if the AMP check is the root cause, switching the computation device as shown above could provide a more direct solution.

Hope this helps! And if there are any more questions or something else you'd like to dive into, feel free to ask. 🌟

**Comment by trianta2** [comment]
Thanks for responding. If I need to train on a GPU, I'm not sure setting `device=cpu` will resolve the issue. 

If you look at that function I referenced before (`check_amp`), the `model` parameter doesn't even appear to be used in a meaningful way; it's just used to get the device and return early.

Instead of using the `model` parameter, a separate `YOLO` object is instantiated with a hard-coded `"yolov8n.pt"`, which is the cause of this issue.

Is this a bug? I.e. should the code actually read `assert amp_allclose(model, im)`?

**Comment by glenn-jocher** [comment]
Hi there! 😊 Thanks for your insightful feedback, and you're right about your observation regarding the `check_amp` function. The intent behind using a separate `YOLO` instance within the function seems to be for conducting AMP checks, but it inadvertently leads to the undesired download behavior if `yolov8n.pt` is not found locally.

Your suggestion to directly use the passed `model` for the AMP check, like `assert amp_allclose(model, im)`, makes sense and could indeed avoid unnecessary downloads. This seems more aligned with the intent to check the AMP compatibility of the already loaded model rather than initiating a new download.

This does look like an oversight in the implementation, and your point potentially highlights a spot for improvement in the code. Sharing this insight with the Ultralytics team or contributing via a pull request could help enhance the functionality for everyone! Thanks for pointing it out. 👍

**Comment by trianta2** [comment]
Is ChatGPT writing these replies?

**Comment by glenn-jocher** [comment]
Yep, ChatGPT at your service! 😊 If you have any more questions or need assistance, feel free to ask. Would love to help out!
