### ISSUE TITLE
TensorRT & ONNXRunTime evaluation has memory leak

### ISSUE THREAD

**Issue by abhiagwl4262** [ultralytics/ultralytics#7924]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Val

### Bug

TensorRT evaluation has memory leak. Also for some reason, I am getting correct accuracy from Pytorch and ONNX but getting zero accuracy from its tensorRT engine. Any ideas ?

When I ran evalution of tensorRT engine. The available memory kept on decreasing. 

### Environment

Ultralytics YOLOv8.0.213 🚀 Python-3.10.13 torch-1.12.1+cu113 CUDA:0 (NVIDIA Tesla T4, 15110MiB)
onnxruntime-gpu-1.12.1

### Minimal Reproducible Example

yolo val model=best.engine data=data.yaml imgsz=512 task=segment

### Additional

https://github.com/ultralytics/ultralytics/assets/22645080/24f74a3c-ddd8-456e-93b5-58ef66b38f74

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@abhiagwl4262 thank you for reporting this issue with the TensorRT evaluation and the memory leak you've encountered. It's concerning to hear about the discrepancy in accuracy between PyTorch, ONNX, and TensorRT, as well as the memory consumption during evaluation.

For the memory leak, this could be related to how resources are managed within the TensorRT inference loop. We'll need to investigate this further to identify the root cause. As for the zero accuracy with the TensorRT engine, this might suggest an issue with the conversion process or the inference pipeline. It's important to ensure that the data preprocessing and postprocessing steps are consistent across different runtime environments.

Please make sure that you're using the latest version of YOLOv8 and that your environment is set up according to the guidelines in our documentation. If the issue persists, consider opening an issue on our GitHub with all the relevant details, including the steps to reproduce the problem and any logs or error messages you're receiving.

We appreciate your offer to submit a PR. If you have identified a fix or improvement, we welcome contributions to the YOLOv8 project. Your collaboration can help enhance the experience for the entire community. 🌟

For further guidance, please refer to our documentation on the Val mode and ensure that your setup aligns with the recommended configurations.
