### ISSUE TITLE
Freezing layers yolov8

### ISSUE THREAD

**Issue by link0ln** [ultralytics/ultralytics#793]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Question with answer!
Need to freeze for example backbone.
Previouse methods like adding extra code to python script:
model = YOLO()
freeze = 10 #backbone layers
freeze = [f'model.{x}.' for x in range(freeze)]  # layers to freeze
for k, v in model.model.named_parameters():
    v.requires_grad = True  # train all layers
    if any(x in k for x in freeze):
        print(f'freezing {k}')
        v.requires_grad = False
model.train()
Will not work, because model.train() will rewrite all layers requires_grad to True .

Solution is to add above code to ultralytics/yolo/engine/model.py after 206 line before "self.trainer.train()"

Than you can check in separate thread for example:
for k, v in model.model.named_parameters():
    print(k," ", v.requires_grad)

### Additional

Any other solutions?

**Comment by FnSK4R17s** [comment]
Trying to do the same. Would be great if the dev team would provide is with some help.

**Comment by andres-g-a** [comment]
Hi, I had the same problem. I looked for how to freeze the layers in yolov5.

https://github.com/ultralytics/yolov5/issues/1314

It is practically similar, you just need to modify a line, instead of writing:
"model.named_parameters()"
write:
"model.model.named_parameters()"

`# Freeze 
n_freeze = 10
freeze = [f'model.{x}.' for x in range(n_freeze)]  # layers to freeze 
for k, v in model.model.named_parameters(): 
  v.requires_grad = True  # train all layers 
  if any(x in k for x in freeze): 
    print(f'freezing {k}') 
    v.requires_grad = False`

I hope it works for you!

**Comment by CatInTheRain** [comment]
Any update about this question? I try to add these lines but number of weights seems always the same

**Comment by veeyuen** [comment]
bump

I also want to freeze layers during training of the v8 model

**Comment by glenn-jocher** [comment]
@veeyuen this feature is not available currently but please feel free to submit a PR to migrate this over from YOLOv5.

**Comment by umar95-hub** [comment]
So you are suggesting training the whole model instead!

**Comment by benlin1211** [comment]
To freeze part of the backbone, I think you can go to your .yaml file and add the following line: 
freeze: 10

<img width="680" alt="截圖 2023-04-16 下午4 18 01" src="https://user-images.githubusercontent.com/63309875/232285380-ad4e405d-b84c-48ea-adc9-9198243a31e8.png">

**Comment by benlin1211** [comment]
You can use callback function:

`        def freeze_layer(trainer):
            model = trainer.model
            num_freeze = 10
            print(f"Freezing {num_freeze} layers")
            freeze = [f'model.{x}.' for x in range(num_freeze)]  # layers to freeze 
            for k, v in model.named_parameters(): 
                v.requires_grad = True  # train all layers 
                if any(x in k for x in freeze): 
                    print(f'freezing {k}') 
                    v.requires_grad = False 
            print(f"{num_freeze} layers are freezed.")

        # Add the custom callback to the model
        model.add_callback("on_train_start", freeze_layer)
`

**Comment by glenn-jocher** [comment]
@benlin1211 as a user mentioned in their comment, they were able to freeze layers during training of YOLOv8 using a callback function. The callback function was added to the model using the `add_callback` method, and it froze a specified number of layers by setting the `requires_grad` parameter accordingly. The user reported that freezing layers did not result in improved performance for their specific use case. It is important to experiment with different modifications to the training process to find the best solution for each individual project.

**Comment by rgaufman** [comment]
This would be great for my use case as well :) - is this something that's planned for YoloV8 in the next few months?

**Comment by glenn-jocher** [comment]
@rgaufman hi,

As of now, there are no plans to implement a pre-trained model freezing feature in YOLOv8. However, as mentioned in the previous comment, users have been able to freeze layers during training using a callback function. You can also experiment with different methods of customizing training to achieve your desired results. 

If you face any further issues or require more information, please feel free to ask. 

Best regards.

**Comment by sibozhang** [comment]
> By reading [how to use callbacks of yolov8](https://docs.ultralytics.com/usage/callbacks/#returning-additional-information-with-prediction), I manage to use callback function to freeze the part of the layers. Here is the solution:
> 
> ```
> def freeze_layer(trainer):
>     model = trainer.model
>     num_freeze = 10
>     print(f"Freezing {num_freeze} layers")
>     freeze = [f'model.{x}.' for x in range(num_freeze)]  # layers to freeze 
>     for k, v in model.named_parameters(): 
>         v.requires_grad = True  # train all layers 
>         if any(x in k for x in freeze): 
>             print(f'freezing {k}') 
>             v.requires_grad = False 
>     print(f"{num_freeze} layers are freezed.")
> ```
> 
> Then add your custom callback function to the model.
> 
> ```
> model = YOLO("yolov8x.pt") 
> model.add_callback("on_train_start", freeze_layer)
> model.train(data="./dataset.yaml")
> ```
> 
> Although in my experience, freezing layers in yolov8 doesn't bring me better performance.

Do you mean training speed is not faster after freeze? Why is that?

**Comment by glenn-jocher** [comment]
@sibozhang hi there,

Freezing layers in YOLOv8 using a custom callback function, as mentioned in your provided solution, can indeed help to freeze specific layers during training. However, freezing layers may not necessarily result in faster training speed.

Freezing layers typically aims to retain the knowledge in the pre-trained layers while only updating the unfrozen layers. This can be useful when you want to fine-tune a model on a new dataset without losing the previously learned knowledge.

The reason why freezing layers may not lead to faster training speed in YOLOv8 could be due to the nature of the model architecture. YOLOv8 consists of multiple components, including backbone layers, neck layers, and detection heads. Freezing layers in one component may not necessarily speed up the training process since the model still needs to compute forward and backward passes through the unfrozen layers.

It's important to note that the effectiveness of freezing layers may vary depending on the specific use case and dataset. It's always a good idea to experiment and evaluate the impact of freezing layers on the overall training performance and model accuracy in your particular scenario.

If you have any further questions or need additional assistance, please don't hesitate to ask.

Best regards.

**Comment by sibozhang** [comment]
> @sibozhang hi there,
> 
> Freezing layers in YOLOv8 using a custom callback function, as mentioned in your provided solution, can indeed help to freeze specific layers during training. However, freezing layers may not necessarily result in faster training speed.
> 
> Freezing layers typically aims to retain the knowledge in the pre-trained layers while only updating the unfrozen layers. This can be useful when you want to fine-tune a model on a new dataset without losing the previously learned knowledge.
> 
> The reason why freezing layers may not lead to faster training speed in YOLOv8 could be due to the nature of the model architecture. YOLOv8 consists of multiple components, including backbone layers, neck layers, and detection heads. Freezing layers in one component may not necessarily speed up the training process since the model still needs to compute forward and backward passes through the unfrozen layers.
> 
> It's important to note that the effectiveness of freezing layers may vary depending on the specific use case and dataset. It's always a good idea to experiment and evaluate the impact of freezing layers on the overall training performance and model accuracy in your particular scenario.
> 
> If you have any further questions or need additional assistance, please don't hesitate to ask.
> 
> Best regards.

Thanks for the response!
Could I ask where should put the line of code model.add_callback("on_train_start", freeze_layer)? Also, should I put freeze_layer function in train.py?

**Comment by glenn-jocher** [comment]
Hi @sibozhang,

Regarding where to put the line of code `model.add_callback("on_train_start", freeze_layer)`, you can add it after creating the YOLOv8 model object, before calling the `model.train()` function. This ensures that the callback function is registered before training starts. You can add this line in the `train.py` file or wherever you are setting up the training process.

As for the `freeze_layer` function, you can define it in the same file (e.g., `train.py`) or create a separate module/file to define the function and import it into `train.py`. This function should include the logic to freeze the desired layers of the YOLOv8 model.

If you have any further questions or need more assistance, feel free to ask.

Best regards.

**Comment by PasinduShavinda** [comment]
> By reading [how to use callbacks of yolov8](https://docs.ultralytics.com/usage/callbacks/#returning-additional-information-with-prediction), I manage to use callback function to freeze the part of the layers. Here is the solution:
> 
> ```
> def freeze_layer(trainer):
>     model = trainer.model
>     num_freeze = 10
>     print(f"Freezing {num_freeze} layers")
>     freeze = [f'model.{x}.' for x in range(num_freeze)]  # layers to freeze 
>     for k, v in model.named_parameters(): 
>         v.requires_grad = True  # train all layers 
>         if any(x in k for x in freeze): 
>             print(f'freezing {k}') 
>             v.requires_grad = False 
>     print(f"{num_freeze} layers are freezed.")
> ```
> 
> Then add your custom callback function to the model.
> 
> ```
> model = YOLO("yolov8x.pt") 
> model.add_callback("on_train_start", freeze_layer)
> model.train(data="./dataset.yaml")
> ```
> 
> Although in my experience, freezing layers in yolov8 doesn't bring me better performance.



> By reading [how to use callbacks of yolov8](https://docs.ultralytics.com/usage/callbacks/#returning-additional-information-with-prediction), I manage to use callback function to freeze the part of the layers. Here is the solution:
> 
> ```
> def freeze_layer(trainer):
>     model = trainer.model
>     num_freeze = 10
>     print(f"Freezing {num_freeze} layers")
>     freeze = [f'model.{x}.' for x in range(num_freeze)]  # layers to freeze 
>     for k, v in model.named_parameters(): 
>         v.requires_grad = True  # train all layers 
>         if any(x in k for x in freeze): 
>             print(f'freezing {k}') 
>             v.requires_grad = False 
>     print(f"{num_freeze} layers are freezed.")
> ```
> 
> Then add your custom callback function to the model.
> 
> ```
> model = YOLO("yolov8x.pt") 
> model.add_callback("on_train_start", freeze_layer)
> model.train(data="./dataset.yaml")
> ```
> 
> Although in my experience, freezing layers in yolov8 doesn't bring me better performance.

@glenn-jocher I have try out this code to freeze the backbone and train the model using my custom dataset. I got following errors can you please kindly help me to solve this error..

ERROR ->

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-14-0ed437d69b4a>](https://localhost:8080/#) in <cell line: 1>()
----> 1 model.train(data="/content/drive/MyDrive/dataset/accident_severity_3C_V1/data.yaml")

4 frames
[/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py](https://localhost:8080/#) in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    198     # some Python versions print out the first line of a multi-line function
    199     # calls in the traceback and some print out the last line
--> 200     Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    201         tensors, grad_tensors_, retain_graph, create_graph, inputs,
    202         allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

**Comment by mahamatnoumai** [comment]
> By reading [how to use callbacks of yolov8](https://docs.ultralytics.com/usage/callbacks/#returning-additional-information-with-prediction), I manage to use callback function to freeze the part of the layers. Here is the solution:
> 
> ```
> def freeze_layer(trainer):
>     model = trainer.model
>     num_freeze = 10
>     print(f"Freezing {num_freeze} layers")
>     freeze = [f'model.{x}.' for x in range(num_freeze)]  # layers to freeze 
>     for k, v in model.named_parameters(): 
>         v.requires_grad = True  # train all layers 
>         if any(x in k for x in freeze): 
>             print(f'freezing {k}') 
>             v.requires_grad = False 
>     print(f"{num_freeze} layers are freezed.")
> ```
> 
> Then add your custom callback function to the model.
> 
> ```
> model = YOLO("yolov8x.pt") 
> model.add_callback("on_train_start", freeze_layer)
> model.train(data="./dataset.yaml")
> ```
> 
> Although in my experience, freezing layers in yolov8 doesn't bring me better performance.

@benlin1211 
@glenn-jocher 
@FnSK4R17s 

I've frozen the model following the method you provided. Here are the results of my experiment:

Freezing 10 layers resulted in a reduced mAP of 0.37 on the test set.
When I froze just 3 layers, the mAP increased to 0.43.
Continuing the experiment, freezing only a single layer further boosted the mAP to 0.52.
From these observations, it appears that freezing layers does not consistently improve the model's performance.

@glenn-jocher 
I'd like to clarify whether the script freezes the initial 10 layers or the last ones. To my knowledge, YOLOv8 has 53 convolutional  [layers](https://www.labellerr.com/blog/understanding-yolov8-architecture-applications-features/#:~:text=This%20architecture%20consists%20of%2053,series%20of%20fully%20connected%20layers.) Please correct me if I'm mistaken.

**Comment by Mahsatajik** [comment]
Hi there, how can I freeze all layers in yolov8 except last head?

**Comment by glenn-jocher** [comment]
@Mahsatajik hello,

Freezing all layers in YOLOv8 except for the head can be achieved through a few steps. First, you would need to access all the parameters of the model using the `model.parameters()` function in PyTorch. This will return all parameters of the model which are, by default, set to require gradient computation (i.e., they are trainable).

To freeze these layers, you then loop over these parameters, setting the `requires_grad` attribute to False. This indicates to PyTorch that no gradient should be computed for these parameters during backpropagation, effectively freezing them.

Next, you'll want to access the parameters of the "head" of the model. How this is done depends on the specific architecture of your YOLOv8 model, as the "head" might be referred to with different terminology like "neck" or "detection head". 

Once you have the parameters of the head, you can loop over these parameters, setting the `requires_grad` attribute back to True. This unfreezes these layers, meaning that they will be trained while the rest of the model remains frozen.

Please note that these instructions assume some familiarity with the PyTorch library and the structure/model architecture of YOLOv8.

Best regards.

**Comment by Mahsatajik** [comment]
@glenn-jocher 
Thanks for your response.
I want to freeze neck and backbone in yolov8 pose estimation model and use this script:
for name, param in model.named_parameters():
    if "backbone" in name:# or "neck" in name:
        param.requires_grad = False
model = YOLO('yolov8x-pose.pt')
is it correct?

**Comment by glenn-jocher** [comment]
@Mahsatajik hi there,

In the first script you provided: 

```
for name, param in model.named_parameters(): 
    if "backbone" in name: # or "neck" in name: 
        param.requires_grad = False 
model = YOLO('yolov8x-pose.pt')
```

It seems like you are calling `YOLO('yolov8x-pose.pt')` to create a new model at the end. You should make sure this is called first to construct the model object and then you can freeze the desired layers.

For the second script, setting `num_freeze = 22` works because there are indeed 22 layers in YOLOv8. If you want to freeze more layers than that, you would be attempting to freeze layers that do not exist – hence the error.

When freezing layers, it's important to know the exact architecture of your model. This includes knowing which layers correspond to the backbone or neck if you want to freeze or unfreeze these specific layers.

Let me know if you have other questions! Best regards.

**Comment by Mahsatajik** [comment]
I confused since yolov8 backbone could be CSPDarknet53 but I cannot freeze more than 22 layer?

**Comment by FatemehNajafiSani** [comment]
Hello everyone,
I've noticed that the train command includes a 'freeze' argument. Based on my testing, this allows us to freeze a specified number of layers. I'm not sure if this feature was added recently, but I would greatly appreciate it if someone could explain why we might use a custom callback instead of this argument. Thank you.
ex : results = model.train(data='coco128.yaml', epochs=3, freeze=10)

**Comment by glenn-jocher** [comment]
@FatemehNajafiSani hello,

The `freeze` argument in the `train` command is indeed an official feature provided to freeze a specified number of initial layers of the model during training. This is intended to make the process of layer freezing straightforward without needing custom callbacks or additional code modifications.

The decision to use a custom callback instead of the `freeze` argument boils down to the flexibility and control you desire over the training process. The `freeze` argument is a quick and easy way to freeze a fixed number of the initial layers, which typically include the early feature extraction layers of the network.

Custom callbacks, on the other hand, provide more granular control. With custom callbacks, you can:

1. Freeze and unfreeze layers dynamically at different points during training.
2. Freeze specific layers or groups of layers rather than just the initial 'n' layers.
3. Implement complex layer freezing/unfreezing schedules or conditional layer manipulation based on various training metrics.

Overall, if the standard 'freeze' functionality meets your requirements, it is the simplest approach. For more customized control over which layers are frozen, or if you want to manage freezing in response to training dynamics, custom callbacks would be the way to go.

Let me know if this clarifies your concerns! Best regards.

**Comment by Mahsatajik** [comment]
Hi, I know how to freeze layers from first layer and also another way to freeze them by their name such as backbone or neck, but I want to freeze just part of neck for example, how can I do this?

**Comment by vgarg11** [comment]
I would like to freeze the backbone of yolov8x. I am doing this by passing freeze=10. Is this the correct way of freezing the backbone? Is 10 the correct number to pass?

results = model.train(data=training_data, epochs=35, imgsz=640, device=[0,1,2,3], plots=True, workers=96, freeze=10)

**Comment by alikashlan10** [comment]
> I would like to freeze the backbone of yolov8x. I am doing this by passing freeze=10. Is this the correct way of freezing the backbone? Is 10 the correct number to pass?
> 
> results = model.train(data=training_data, epochs=35, imgsz=640, device=[0,1,2,3], plots=True, workers=96, freeze=10)

i want to ask the same question but for the medium model @glenn-jocher

**Comment by glenn-jocher** [comment]
@alikashlan10 hello! 😊 Freezing the backbone by specifying the `freeze` parameter is indeed a valid approach. However, the correct number to pass depends on the specific architecture of the YOLOv8x model. The number `10` might not fully freeze the entire backbone, as the backbone's depth can vary.

For YOLOv8x, you might need to freeze more layers to cover the entire backbone. It's essential to review the model architecture to determine the exact number. For the medium model, the number of layers to freeze might differ due to its unique architecture.

A quick tip: you can inspect the model layers using something like this to better understand what to freeze:

```python
from ultralytics import YOLO
model = YOLO('yolov8x.pt')  # or 'yolov8m.pt' for the medium model
for i, (name, param) in enumerate(model.named_parameters()):
    print(i, name)
```

This will help you identify which layers are part of the backbone. Hope this helps! Let me know if you have any more questions.

**Comment by parajav** [comment]
Hi,
Stumbled upon this thread from 2023. Not sure if freeze parameter was present then.
However, while using it to freeze=20 layers, it freezes 0-19(expected) but also layer 22(always , not sure why)
Is this a known issue or do i need to use the trainer callback as mentioned here
```
model = YOLO('yolov8n.pt')
results = model.train(data=training_data, epochs=100, imgsz=640, freeze=20)
```

Freezing layer 'model.0.conv.weight'
Freezing layer 'model.0.bn.weight'
Freezing layer 'model.0.bn.bias'
Freezing layer 'model.1.conv.weight'
Freezing layer 'model.1.bn.weight'
Freezing layer 'model.1.bn.bias'
Freezing layer 'model.2.cv1.conv.weight'
Freezing layer 'model.2.cv1.bn.weight'
Freezing layer 'model.2.cv1.bn.bias'
.................................................
Freezing layer 'model.19.conv.weight'
Freezing layer 'model.19.bn.weight'
Freezing layer 'model.19.bn.bias'
Freezing layer 'model.22.dfl.conv.weight'

**Comment by glenn-jocher** [comment]
@parajav hi there! 👋

It sounds like you're encountering an unexpected behavior with the `freeze` parameter. The freezing of layer 22 alongside 0-19 isn't typical based on the `freeze=20` setting. This might be related to how the model architecture is defined and how layers are indexed internally.

Before considering a custom callback, I'd recommend checking the latest updates or documentation for any notes on this behavior. Sometimes, model architectures have interconnected layers or dependencies that might cause such anomalies.

If this still seems out of place, using a custom callback as you mentioned is a good workaround. It gives you precise control over which layers to freeze:

```python
for name, param in model.named_parameters():
    if int(name.split('.')[1]) < 20:  # Adjust the condition based on layer naming
        param.requires_grad = False
```

Feel free to share any updates or further questions you might have! 😊

**Comment by mysakbm** [comment]
Hi, 
@parajav , I have the same output when freezeing 15 layers. The model froze
![image](https://github.com/ultralytics/ultralytics/assets/38407239/8b70e6c9-05aa-42e3-81a9-d46204c6648e)
But if I recall correctly, yolov8 has pyramid architecture and uses some "residual" connections this the layer 22 being frozen as well I assume.

**Comment by DANISHFAYAZNAJAR** [comment]
@glenn-jocher After training model using freezing, I am getting model trained and it's showing mAP50 around 60+. But when I check F1 score curve it it's showing f1 score of around 58 at a confidence of just 0.12.  I want model to have more confidence, what can I change to make it more confident.
