### ISSUE TITLE
Select YOLOv8 version

### ISSUE THREAD

**Issue by mathemaiaeirene** [ultralytics/ultralytics#7937]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

My question is very simple: is it possible to select a version of YOLOv8 to use or install? I would like to use the version 8.0.143.

**Comment by glenn-jocher** [comment]
@mathemaiaeirene hello! Yes, you can select a specific version of YOLOv8 to use. To install a particular version, such as 8.0.143, you would typically specify the version number when installing the package. However, please ensure that the version you're looking for exists and is compatible with your setup. For more details on installation and version selection, you can refer to our documentation at https://docs.ultralytics.com. Happy coding! 😊🚀

**Comment by Burhan-Q** [comment]
`pip install ultralytics==8.0.143` and you may need to manually download the weights files from Releases for `8.0.xxx` versions. All links have been updated to point to the `8.1` Release model weights.

**Comment by Burhan-Q** [comment]
@NaumanHSA there _may_ have been minor changes to the models, but overall `8.1.0` was more a feature release around the `ultralytics` codebase. As far as I'm aware, there were no updates/re-publishing of model metrics since there were no changes to expect. The only thing to be mindful of is that, and I don't know for certain, the models from `>=v8.1.0`  _might not_ run on code that's `<v8.1.0`; however the original models are still available [here](https://github.com/ultralytics/assets/releases/tag/v0.0.0) if needed.

**Comment by NaumanHSA** [comment]
Thank you so much @Burhan-Q. That was helpful.
