### ISSUE TITLE
COCO JSON Polygons to YOLO OBB

### ISSUE THREAD

**Issue by RanaShiva** [ultralytics/ultralytics#7940]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

This feature script will take as input a coco JSON file and convert it into OBB format.

### Use case

If I say, have a batch of 10 images with objects ranging from 1-3 for example. I can use tools like makesense.ai, Create polygons containing those objects. Then I can run a script that will take this as input this JSON file and convert it into YOLO OBB format for each image. `class_index, x1, y1, x2, y2, x3, y3, x4, y4`

### Additional

It will different from this feature that already exist in ultralytics- 
`ultralytics.data.converter.yolo_bbox2segment(im_dir, save_dir=None, sam_model='sam_b.pt')`
The proposed feature will take as an input polygon COCOJSON and output OBB

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@RanaShiva hello! Thank you for your interest in contributing to the YOLOv8 project and for the feature suggestion. It's great to see community members eager to enhance the capabilities of the model with new functionalities.

Your proposal to create a script that converts COCO JSON polygon annotations to YOLO oriented bounding box (OBB) format is indeed different from the existing feature that converts bounding boxes to segmentation masks. This could be a valuable addition for users who work with datasets that include more complex shapes requiring OBB rather than axis-aligned bounding boxes.

Before you start working on your PR, I recommend checking out the contribution guidelines in our documentation. This will help ensure that your contribution aligns with the project's standards and can be integrated smoothly.

Once you're ready, please make sure your script is well-documented, tested on various datasets to handle edge cases, and follows the coding style of the YOLOv8 repository. We look forward to your pull request and are here to support you through the process. Good luck, and thank you for supporting the YOLO community! 🚀

**Comment by RanaShiva** [comment]
Thank you for your swift response. I've successfully crafted the initial version for the specified functionality and have successfully trained a model using pre-trained `yolov8n-obb.pt`. I'll proceed to thoroughly test it, including edge cases, and subsequently create a pull request.

**Comment by glenn-jocher** [comment]
@RanaShiva that's fantastic news! We're excited to see your contribution. Please ensure thorough testing and adherence to our contribution guidelines. Looking forward to your pull request. Happy coding! 🌟

**Comment by SFSimDev** [comment]
@RanaShiva I'm doing some workarounds with this at the moment but what you are working on would meet my requirements. From doing some research on this myself I see that the COCO format only includes 2 XY coordinates in its output.  How are you getting around this to comply with the class_index, x1, y1, x2, y2, x3, y3, x4, y4 format?
