### ISSUE TITLE
Problem while running hyperparameter tunning with raytune

### ISSUE THREAD

**Issue by AryaFarh** [ultralytics/ultralytics#7946]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Hyperparameter Tuning

### Bug

Failure # 1 (occurred at 2024-02-01_10-41-02)
[36mray::ImplicitFunc.train()[39m (pid=656336, ip=192.168.50.178, actor_id=b4d546dadd62f1753b5463cb01000000, repr=_tune)
  File "/mnt/nest3/arya/uenv/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 342, in train
    raise skipped from exception_cause(skipped)
  File "/mnt/nest3/arya/uenv/lib/python3.9/site-packages/ray/air/_internal/util.py", line 88, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/mnt/nest3/arya/uenv/lib/python3.9/site-packages/ray/tune/trainable/function_trainable.py", line 115, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/mnt/nest3/arya/uenv/lib/python3.9/site-packages/ray/tune/trainable/function_trainable.py", line 332, in _trainable_func
    output = fn()
  File "/mnt/nest3/arya/uenv/lib/python3.9/site-packages/ultralytics/utils/tuner.py", line 103, in _tune
    return results.results_dict
AttributeError: 'NoneType' object has no attribute 'results_dict'

### Environment

Ubuntu 20.04
python3.9.7
torch==2.1.2

### Minimal Reproducible Example

import matplotlib.pyplot as plt
from ultralytics import YOLO

model = YOLO('yolov8n-seg.pt')

result_grid = model.tune(data='./datasets/Tuning/2024-01-31_test_train_split/dataset.yaml',epochs=50, device= [0,1] ,use_ray=True)

for result in result_grid:
    plt.plot(result.metrics_dataframe["training_iteration"], result.metrics_dataframe["mean_accuracy"], label=f"Trial {i}")

plt.xlabel('Training Iterations')
plt.ylabel('Mean Accuracy')
plt.legend()
plt.show()

### Additional

The tunning is happening without problem for each epoch and csv file containing the result is being created. However this error is there. Please let me know if the provided information is enough. 

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@AryaFarh hello! It seems like you're encountering an issue with hyperparameter tuning using Ray Tune where the `results_dict` attribute is not found. This typically indicates that the tuning process did not return any results, possibly due to an internal error or misconfiguration.

To address this, please ensure that:
1. Your dataset and configuration are correctly set up.
2. The Ray Tune environment is properly initialized and compatible with the version of YOLOv8 you are using.
3. There are no silent failures during the tuning process that could lead to a `None` result.

Since you mentioned that the tuning is happening without a problem for each epoch and a CSV file is being created, it might be an issue with how the results are being collected or accessed at the end of the tuning process.

If the problem persists, consider reviewing the hyperparameter tuning section in our documentation for any updates or common pitfalls. If you believe there's a bug in the code, submitting a PR with a fix or further details would be greatly appreciated by the community! 🛠️

Thank you for contributing to the YOLOv8 project, and we look forward to your PR.

**Comment by AryaFarh** [comment]
I looked a bit more into the codes and where the problem is coming from. 
def _tune(config):
        """
        Trains the YOLO model with the specified hyperparameters and additional arguments.

        Args:
            config (dict): A dictionary of hyperparameters to use for training.

        Returns:
            None
        """
        model_to_train = ray.get(model_in_store)  # get the model from ray store for tuning
        model_to_train.reset_callbacks()
        config.update(train_args)
        LOGGER.warning(f'{config}, {model_to_train} This is extra comment added by user not Ultralytics'
        results = model_to_train.train(**config)
        return results.results_dict
this function in the utils is where the issue is arising from. The comment suggests that is should return None. I am unsure then why it is returning results.results_dict. I will take a look at ray documentation.

**Comment by molnarszilard** [comment]
Hi, I had the same problem when I tried to run Raytune on YOLOv8 for detection. I was using a conda environment, and my first thought was that my GPU drivers were old (therefore I could not use Pytorch 2). I did not want to update them (to avoid the risk of borking a functional system), so I tried docker. While the GPU driver still did not work with pytorch 2, in the docker I got a different error: 
```ValueError: Invalid CUDA 'device=0,1' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.```
So I exited the docker, went back to my regular conda environment, and commented the line where I specified the devices it worked without any errors.

I tried different ways: device=0,1, device=(0,1), device=[0,1], and each of them resulted in the above error.
If I specify only one GPU (e.g. device=1), then it works (it chooses that GPU).
If I want to use more than one GPU, then I can't use the device argument, only the gpu_per_trial argument (the only downside is that this way I am not able to specify which GPUs to use. Using CUDA_VISIBLE_DEVICES=0,1 will utilize only GPU:0)

So at the moment, you either don't use multiple GPUs, or you don't specify which ones to use.

**Comment by glenn-jocher** [comment]
@molnarszilard hey there! 👋 It looks like you've run into a bit of a snag with specifying multiple GPUs for Ray Tune with YOLOv8. The error you're seeing suggests there's a hiccup in how the device IDs are being passed. 

For using multiple GPUs, you're right that specifying them directly in the `device` argument like `device=0,1` should ideally work, but it seems there's a quirk here. Since `device=1` works fine for you, this indicates your setup can indeed utilize GPUs correctly.

A workaround, as you've discovered, is leveraging `CUDA_VISIBLE_DEVICES` to control GPU visibility, though it's not perfect since it doesn't allow for explicit GPU selection within the script. 

For now, sticking to single GPU usage or using `gpu_per_trial` without specifying `device` when you need multiple GPUs seems to be the practical approach. We're always looking to improve, so insights like yours are super valuable for future updates. 🚀

If you're feeling adventurous and want to dive into the code, contributions are always welcome! Thanks for sharing your experience, and let's hope for a more flexible solution down the line.
