### ISSUE TITLE
How to use pretrained model in yolov8 training?

### ISSUE THREAD

**Issue by madenburak** [ultralytics/ultralytics#795]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I use pretrained model in yolov5 with ` --weights` parameter. Also, I continue training from last checkpoint with `--resume` parameter. But, I can't these actions in yolov8 or I can't find the solution.

How I do that?

**Comment by AyushExel** [comment]
In ultralytics repo model can accept both yaml and pt files. You can just pass `model=model.pt`

**Comment by teodororo** [comment]
Hi, @AyushExel
I have a similar question. 
Is it right to assume that when I do `model=model.yaml` the weights will be trained from scratch and `model=model.pt` will give me the pretrained model? Like, in the latter I'd be doing fine-tuning?
Thanks.

**Comment by dmddmd** [comment]
> Hi, @AyushExel I have a similar question. Is it right to assume that when I do `model=model.yaml` the weights will be trained from scratch and `model=model.pt` will give me the pretrained model? Like, in the latter I'd be doing fine-tuning? Thanks.

please answer this and what is the --resume parameter of yolov5 in yolov8

**Comment by AMG222** [comment]
> Hi, @AyushExel I have a similar question. Is it right to assume that when I do `model=model.yaml` the weights will be trained from scratch and `model=model.pt` will give me the pretrained model? Like, in the latter I'd be doing fine-tuning? Thanks.

You can save the model.pt every x epoch with the argument save_period and resume the training loading the model saved from the last epoch or in the epoch that you saved with that option. **But it's important to activate the option resume to train from the last state of that model (lr and other features)**.
An example could be:

`
model = YOLO("last.pt")
results = model.train(epochs=200, save_period = 10, resume=True)
`
And last.pt is a model trained for 100/200 epochs for example, the training will continue from the number 100 and not from the  beginning as a pretrained model

**Comment by glenn-jocher** [comment]
@AMG222 yes, you are correct. When you use `model=model.yaml`, the weights will be initialized randomly and you have to train the model from scratch. Whereas, `model=model.pt` will load a pre-trained model with weights already trained on a large dataset. You can further fine-tune the loaded model on your own dataset. 

Moreover, the `--resume` parameter can be used in both YOLOv5 and YOLOv8 to resume the training process from the last saved checkpoint. This allows you to continue training from where you left off in the previous run, rather than starting from scratch every time. It is important to mention that when using this option, you also need to load the model that was saved during the last epoch to resume training.
