### ISSUE TITLE
How to change GPU configuration when resuming training on a pretrained model

### ISSUE THREAD

**Issue by ohjunee** [ultralytics/ultralytics#7965]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

1. I trained a model using GPU:1, and now I want to resume training on GPU:0. 
However, even when I provide information for GPU:0 in the device argument, the model still uses the previous training configuration. 

2. The options `resume=False` and `pretrained=False` when resuming training with specified weights; what is the reason for these settings?

Code
```
    model = YOLO("runs/detect/cspvitcspp+nestedcspp/weights/last.pt")
    gpu_num = 0
    device = torch.device(f'cuda:{gpu_num}'),
    print(device)
    results = model.train(resume=True, device=device)
```

Results
```
(device(type='cuda', index=0),)
New https://pypi.org/project/ultralytics/8.1.9 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.1.8 🚀 Python-3.10.12 torch-2.2.0+cu121 CUDA:1 (NVIDIA GeForce RTX 3090, 24257MiB)
engine/trainer: task=detect, mode=train, model=runs/detect/cspvitcspp+nestedcspp/weights/last.pt, 
data=/media/opt-ai/workspace/ojun.kwon/ultralytics/ultralytics/cfg/datasets/coco.yaml, 
...
device=1, 
...
pretrained=False, 
resume=False
...
```

**Comment by glenn-jocher** [comment]
@ohjunee hello! When resuming training on a different GPU, you should ensure that the `device` argument is correctly set. It seems there might be a small issue in your code where `device` is defined as a tuple due to the trailing comma. Make sure to define it as `device = torch.device(f'cuda:{gpu_num}')` without the comma.

Regarding the `resume` and `pretrained` options:
- Setting `resume=True` allows you to continue training from the last checkpoint, maintaining optimizer state, epoch, etc.
- The `pretrained=False` option is typically used when you're starting fresh training without preloaded weights.

If you're still facing issues, ensure that your environment variables related to CUDA devices are set correctly, and you might want to check if any other scripts or configurations are overriding your device settings.

For more detailed guidance on training and configuration, please refer to our documentation at https://docs.ultralytics.com. 😊
