### ISSUE TITLE
Is Yolov8 pose a top-down model? Detailed explanation

### ISSUE THREAD

**Issue by JasseurHadded1** [ultralytics/ultralytics#7980]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello,

You have mentioned that yolov8 pose is a top-down model, ([Here](https://github.com/ultralytics/ultralytics/issues/6562) for example), and you have said [here](https://github.com/ultralytics/ultralytics/issues/6562#issuecomment-1825890484): 

> Even if it is not immediately apparent from the specific code snippet you referred to, the Top-Down aspect of the YOLOv8 Pose model is integrated into the overall workflow rather than in isolated portions of the codebase. The system first leverages the high-level YOLOv8 architecture to localize and identify objects, then within those localized regions, it applies the pose estimation.
It might not use the detection head outputs directly or in the traditional sense you're expecting, but the approach is designed to operate sequentially – detect then estimate pose – which is the essence of the Top-Down method. This multi-stage process allows the pose estimation to focus on the relevant parts of the image already identified as containing the objects or people of interest.

But I tried to search how are pose points detected from detection boxes, and I looked to the code and the architecture, and I didn't find the "detect then estimate pose"!. Yes the model learns at the same time the two tasks (detect & pose) but I didn't see anything about the fact the pose points are estimated from the detection boxes. 

If we take a look at the network architecture we see that the "23.cv2" layer (responsible of the detection head) and the "23.cv4" layer (responsible of the pose head) are independent and they takes the same input (we can see that by printing the model architecture or in the code in the Pose head code [here](https://github.com/ultralytics/ultralytics/blob/70d4a3752eda44580209ac821ff2c70df17a41bb/ultralytics/nn/modules/head.py#L160) where we see in the forward function that detect and pose are independent.

Also I have searched if there is a post-processing that use the detection to estimate the pose (with using pose output) and I didn't find,

So can you please explain me where can we find how the pose points are estimated from detection boxes? 

I know that finally the result of the pose is dependent of the result of detect (by experiments I never got a pose without a box) but I didn't find where this relation is implemented!

Thanks in advance,

**Comment by glenn-jocher** [comment]
@JasseurHadded1 hello,

Thank you for your detailed inquiry regarding the YOLOv8 Pose model. The YOLOv8 Pose model indeed operates with a top-down approach, where the detection and pose estimation tasks are learned simultaneously during training. However, the relationship between detection boxes and pose estimation is more nuanced than a direct sequential process.

The architecture is designed to leverage shared features for both detection and pose estimation, which is why you see the same input going to both the detection and pose heads. During inference, the pose estimation is conditioned on the presence of detection boxes, but this relationship is implicit rather than explicit within the code.

The pose estimation relies on the detection results, but the connection between them is not as direct as taking detection boxes and then estimating poses within those boxes. Instead, the model learns to estimate poses in a way that is implicitly guided by the detection task during training. This is why you observe that poses are not estimated without corresponding detection boxes.

For a deeper understanding of how the model architecture and training process enable this implicit relationship, I recommend reviewing the relevant sections in our documentation, particularly those related to the Pose/Keypoint Estimation task. The documentation provides insights into the model's design and how the different tasks are integrated.

**Comment by JasseurHadded1** [comment]
@glenn-jocher 

Thanks, Ok it's clear that the relation is not explicit within the code, but can you explain a little the implicit relationship between detection & pose? If it's just related to the architecture, I think the model will sometimes do some errors, so is there something in the post-processing for example that forces to delete poses that are not related to boxes or something like that?

Thanks again,

**Comment by glenn-jocher** [comment]
@JasseurHadded1, the implicit relationship between detection and pose estimation in YOLOv8 is primarily learned during training. The model is trained to recognize patterns where pose keypoints are associated with detected objects. In post-processing, we do apply logic to ensure that pose estimations are only reported for detected objects, which helps maintain the integrity of the results. This means that pose keypoints not associated with a confident detection are filtered out, ensuring that the final output is both coherent and relevant. For further details on this process, you might find the Pose/Keypoint Estimation section of our documentation insightful.

**Comment by Song-Jie-ing** [comment]
> @glenn-jocher
> 
> Thanks, Ok it's clear that the relation is not explicit within the code, but can you explain a little the implicit relationship between detection & pose? If it's just related to the architecture, I think the model will sometimes do some errors, so is there something in the post-processing for example that forces to delete poses that are not related to boxes or something like that?
> 
> Thanks again,

Hello, do you know how to utilize the details of the detection box for key points

**Comment by glenn-jocher** [comment]
@Song-Jie-ing the model ensures poses are linked to detection boxes during post-processing, filtering out unrelated keypoints. For more on this, please refer to our documentation.

**Comment by Song-Jie-ing** [comment]
So is yolov8pose different from yolopose in principle 

> @Song-Jie-ing the model ensures poses are linked to detection boxes during post-processing, filtering out unrelated keypoints. For more on this, please refer to our documentation.

**Comment by glenn-jocher** [comment]
Yes, YOLOv8 Pose and YOLO Pose differ in architecture and implementation, with YOLOv8 Pose offering enhanced features and performance. For more details, please check the documentation.
