### ISSUE TITLE
Questions about the pretrained model

### ISSUE THREAD

**Issue by blackcement** [ultralytics/ultralytics#799]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

1. At what resolution are the pre-trained models trained? If my dataset has a resolution of 480x480, does it make sense to train it at this resolution. Although I see that the training of the pre-trained model is going well at 480 resolution, I hardly guessed right. After all, the input layer is different, it should not have worked.

```
model = YOLO("yolov8m.pt")
results = model.train(data="data.yaml", epochs=1000, batch = 32, imgsz=480 ,v5loader=True)
```
2. It may be that in the pre-trained model there are classes that match my dataset. Does it make sense to give these classes the same numbers as in the pretrained model? If so, on what dataset were the pretrained models made, what is the class numbering?

**Comment by glenn-jocher** [comment]
@blackcement @dmddmd all official models are trained at 640 unless they are P6 models, which are trained at 1280. Your domain does not need to match the pretrained model domain for them to be useful. It's always recommended to start from a pretrained model rather than from scratch, regardless of the imgsz or classes.
