### ISSUE TITLE
yolov8 onnx convertion issue

### ISSUE THREAD

**Issue by sredouane** [ultralytics/ultralytics#8010]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

the network can only detect humain, in other word it sees only classId 0. The humain detection is very good and have the correct bounding box.

### Environment

tested on cpu docker image running on my windows virtual machine with i7/16gig ram.
tested on my ubuntu on terminal (no docker) using cpu conversion with amd rayzen 7/128gig ram.

### Minimal Reproducible Example

Create docker image using https://github.com/ultralytics/ultralytics/blob/main/docker/Dockerfile

Convert to onnx format:

ADD https://github.com/ultralytics/assets/releases/download/v8.1.0/yolov8l.pt /usr/src/ultralytics/
yolo export model=/usr/src/ultralytics/yolov8l.pt format=onnx imgsz=640

Use the result in opencv c++ same as https://github.com/ultralytics/ultralytics/blob/main/examples/YOLOv8-CPP-Inference/inference.cpp

Current result: the network can only detect humain, in other word it sees only classId 0. The humain detection is very good and have the correct bounding box.

Expected: detect all classId from 0 to 79

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Kutayykilic** [comment]
There's nothing wrong with your code.  Did you try the X model? And what video are you running the model on? I don't think it has all the available COCO classes.

**Comment by sredouane** [comment]
I tried all the model sizes they give the same result.
The video feed have me, chair, banana, bottel remote controler. The yolo 5 see them all. Exported yolov8 see me only. If go off screen and keep the others it sees nothing.

**Comment by glenn-jocher** [comment]
@sredouane it sounds like the model is not generalizing to other classes beyond 'person'. This could be due to a variety of reasons, such as an issue with the export process or a problem with the model weights. To troubleshoot, please ensure you're using the latest version of the YOLOv8 repository and follow the export instructions carefully. If the problem persists, consider validating the ONNX model with a known dataset to check if the issue is with the model or the video feed content. If the model performs well on the dataset but not on your video, it might be an issue with the input data or preprocessing steps. If you continue to experience issues, please open a detailed issue on the repo with all the steps you've taken so we can investigate further. 🕵️‍♂️

**Comment by sredouane** [comment]
- if doing git https://github.com/ultralytics/ultralytics.git does not make me use the latest code, can you please share the right branch to use to be on the latest instead of the main branch.
- in not using any export instruction, im simply using the provided dockerFile-cpu 
-and change the line:
from: RUN yolo export model=tmp/yolov8n.pt format=ncnn imgsz=32
to RUN yolo export model=tmp/yolov8n.pt format=onnx imgsz=640
if this is not the way, then can you point out the right way?

**Comment by glenn-jocher** [comment]
@sredouane hello! Thank you for reaching out and providing detailed information about the issue you're experiencing with the ONNX conversion of YOLOv8.

It seems like the model is only detecting the 'person' class (classId 0) and not the other classes. This is certainly unusual behavior, especially since you mentioned that the human detection is working well.

To help us diagnose the issue, could you please confirm if you've tried running inference with the original `.pt` model file on the same dataset to ensure that it's capable of detecting all classes as expected?

Additionally, it would be helpful if you could share the command or script you're using to run the inference with the ONNX model, as well as any output logs or error messages you might be receiving.

In the meantime, you might want to ensure that the export process is completed without errors and that the ONNX model is being loaded correctly in your OpenCV C++ environment.

We appreciate your cooperation and are here to assist you in resolving this issue. 🛠️
