### ISSUE TITLE
Inference time not faster with larger batch size

### ISSUE THREAD

**Issue by oscarwzt** [ultralytics/ultralytics#8041]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm trying to use YOLOv8 to inference videos by accumulating a batch of frames and then passing the batch to the model. However, I noticed that there is not a big difference between inferencing sequentially vs. by-batch. Also, changing the batch size does not affect the total inference time much. See the below experiment:
<img width="977" alt="Screenshot 2024-02-05 at 5 14 00 PM" src="https://github.com/ultralytics/ultralytics/assets/71715227/18c7a152-9b11-4956-834d-7d5dbb851f2f">
I expected that batch size of 16 to be significantly faster than sequential inference, and batch size of 64 to be faster than batch size of 16, and so on.

I've read #1310 but didn't find any clue on why I'm not getting the expected speed-up. I also tried setting `rect = True` as the comment in that issue suggested, but no difference.

My questions:
- why does changing batch size (number of images in a list passed to the model) not affect inference time as much?
- If passing a list of images is not the correct way to do batch inference, what is the correct way?

Thank you!

### Additional

My GPU: Quadro RTX 6000, 24G Mem

**Comment by glenn-jocher** [comment]
@oscarwzt hello! The inference time not scaling linearly with batch size can be attributed to several factors. Here are a few points to consider:

1. **GPU Utilization**: Larger batch sizes can better utilize GPU parallelism, but only up to a point. Beyond that, you may hit bottlenecks in memory bandwidth or processing capabilities.

2. **Overhead**: There's a fixed overhead for each inference call, regardless of batch size. With smaller batches, this overhead is a larger proportion of total time.

3. **I/O Bound**: If your setup is I/O bound, meaning the time to read/write data is significant compared to processing time, increasing batch size won't help much.

4. **Model Architecture**: Some models scale better with batch size than others due to their architecture and the efficiency of their operations on the GPU.

To ensure you're doing batch inference correctly, pass a list of images as a batch to the model. This is the intended method. If you're not seeing the expected speed-up, it's likely due to one of the reasons above or other system-specific constraints.

For further insights, you might want to profile your GPU usage during inference to identify potential bottlenecks. The [Benchmark](https://docs.ultralytics.com/modes/benchmark) mode in our documentation can help you with profiling.

If you continue to experience issues, please provide more details on your setup and we'll do our best to assist you. 😊

**Comment by Leminhhuy2386** [comment]
I got same problem. Using batch_size even seem slower than using loop with single image.
Recent Ultralytics version upgraded but nothing change!!!

**Comment by glenn-jocher** [comment]
@Leminhhuy2386 batch inference may not always lead to speed improvements due to factors like GPU utilization and overhead. Ensure your setup is optimized for batch processing, and consider profiling your GPU usage to identify bottlenecks.
