### ISSUE TITLE
YOLOv8 VISIONEYE

### ISSUE THREAD

**Issue by leongjy2005** [ultralytics/ultralytics#8050]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Traceback (most recent call last):
  File "d:\Random_YOLO8_Tutorials\Human_Detection\visioneye.py", line 28, in <module>
    annotator.visioneye(box, center_point)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Annotator' object has no attribute 'visioneye'

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@leongjy2005 hello! It seems like you're encountering an `AttributeError` because there's no `visioneye` method in the `Annotator` class. The `Annotator` is designed to assist with drawing on images, such as bounding boxes, labels, and other visual elements. If you're looking to annotate detections, you might want to use methods like `box` to draw bounding boxes or `text` to add text labels.

For more details on how to properly use the `Annotator` class or other functionalities of YOLOv8, please refer to our documentation at https://docs.ultralytics.com. If you need further assistance, feel free to ask. We're here to help! 😊

**Comment by Burhan-Q** [comment]
@leongjy2005 check your `ultralytics` version, it's likely you'll need to update. That method does exist and you can see it here in the source code https://github.com/ultralytics/ultralytics/blob/70a6ef9c7ed7b3ade1759bd0f2bef31849f4aacc/ultralytics/utils/plotting.py#L567-L582
