### ISSUE TITLE
Empty Validation Results at Confidence Threshold 1.0 for All Classes

### ISSUE THREAD

**Issue by Ziad-Algrafi** [ultralytics/ultralytics#8069]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Val

### Bug

![NfafawfafP](https://github.com/ultralytics/ultralytics/assets/117011801/4320014d-e8f1-458f-8592-3baf2236c06c)

### Environment

Ultralytics YOLOv8.0.239 🚀 Python-3.10.12 torch-2.0.0.dev20230209+rocm5.2 CUDA:0 (AMD Radeon RX 5700 XT, 8176MiB)

### Minimal Reproducible Example

from ultralytics import YOLO
from ultralytics.utils.torch_utils import select_device
import os
import pandas as pd
import yaml

# Path to the directory where validation results will be saved
output_directory = '/home/ziad/Files/'

# Path to YOLO model file
model_path = '/home/ziad/best.pt'

# Path to data configuration file or classes.
data_path = '/home/ziad/Documents/custom_data.yaml'

# Confidence thresholds to loop through
confidence_thresholds = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0,8, 0.9, 1]

# Run YOLO validation for each confidence threshold
for conf_threshold in confidence_thresholds:
    # Select the device
    device = select_device('0')
    
    # Run YOLO validation with the custom confidence score
    model = YOLO(model_path)
    metrics = model.val(data=data_path, conf=conf_threshold, save=True)
    
    # Extract and save per-class metrics
    ap50_scores = metrics.box.ap50.tolist()
    ap_scores = metrics.box.ap.tolist()

    # Additional metrics
    recall = metrics.box.r.tolist()
    precision = metrics.box.p.tolist()
    f1 = metrics.box.f1.tolist()
 
    # Load class names from the data configuration file
    with open(data_path, 'r') as file:
        data_config = yaml.safe_load(file)
        class_names = data_config['names']

    # Creating a dictionary to store metrics for each class
    class_metrics = {}
    for i, class_name in enumerate(class_names):
        class_metrics[class_name] = {
            'MAP50': ap50_scores[i],
            'MAP50-95': ap_scores[i],
            'Recall': recall[i],
            'Precision': precision[i],
            'F1': f1[i] if len(f1) > i else None
        }

    # Save the metrics for each class to a CSV file
    metrics_df = pd.DataFrame(class_metrics).transpose()
    csv_path = os.path.join(output_directory, f'validation_results_{conf_threshold}.csv')
    metrics_df.to_csv(csv_path, index_label='Class')

    print(f"Results for confidence threshold {conf_threshold} saved to: {csv_path}")

### Additional

I've encountered an issue while using Ultralytics for object detection evaluation. My code aims to retrieve the scores of validation for all confidence threshold levels and store them in a CSV file. While looping through each threshold value in the range [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1], I've observed that all threshold confidence scores work fine except for a confidence value of 1.

When attempting to access the scores at a confidence threshold of 1.0, I encounter the following error message:

python

ap50_scores = metrics.box.ap50.tolist()
AttributeError: 'list' object has no attribute 'tolist'

I've tried running the code on both CPU and GPU, but the issue persists. My assumption is that there might be no detection instances with a confidence score exactly equal to 1.0. Alternatively, if detection with a confidence of 1.0 do exist, it's possible that the data type of the object containing the scores changes, resulting in the error.

Could you please provide insights or guidance on how to handle this issue effectively?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Ziad-Algrafi hello! It seems like you're encountering an issue with empty validation results when setting the confidence threshold to 1.0. This typically happens because it's quite rare for a model to predict with absolute certainty (1.0 confidence). As a result, there may be no detections at this threshold, leading to an empty list and the error you're seeing.

To handle this, you could add a check before attempting to convert your metrics to a list. If the list is empty, you can skip the conversion or handle it as a special case. This way, your code will be robust to situations where no detections meet the confidence threshold.

Remember, a confidence threshold of 1.0 is not practical for real-world applications and is not recommended for evaluating model performance. It's better to use a range of lower thresholds to understand your model's precision and recall trade-offs.

If you need further guidance on validation or other modes, please refer to our documentation at https://docs.ultralytics.com. Keep up the great work with YOLOv8! 🚀
