### ISSUE TITLE
Tensorrt inference on Yolov8 -OBB (Oriented Bounding Box)

### ISSUE THREAD

**Issue by kkamalrajk** [ultralytics/ultralytics#8070]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

👋 Hello,

I successfully converted the 'yolov8x.pt' detection model to .engine format, experiencing a remarkable 2x improvement in inference speed on V100 GPUs.

However, when attempting the same with the 'yolov8x-obb.pt' (Oriented Bounding Box) model, the achieved speed boost is only 1.09x on the identical V100 16GB GPU. My expectation was to attain at least a 2x improvement in inference speed with the TensorRT version.

I am seeking guidance on potential optimisations or strategies to enhance the performance and meet the anticipated 2x speed boost on the oriented bounding box model.

Appreciate your assistance!

**Comment by glenn-jocher** [comment]
@kkamalrajk hello 👋,

Great to hear about your success with the 'yolov8x.pt' model and TensorRT! For the 'yolov8x-obb.pt' model, the smaller speedup could be due to the additional complexity of predicting oriented bounding boxes. To potentially improve performance, consider the following:
- Ensure that you're using the latest version of TensorRT and CUDA.
- Optimize the TensorRT engine with layer fusion, precision calibration, and kernel auto-tuning.
- Experiment with different batch sizes to find the optimal setting for your GPU.
- Profile the model with TensorRT's profiling tools to identify bottlenecks.

If you continue to face issues, please provide more details on your conversion and inference process, and we'll be happy to help further!

**Comment by kkamalrajk** [comment]
@glenn-jocher  👋 Hi Glenn Jocher,

I used the code below to convert the OBB model to the .engine format:

'''
from ultralytics import YOLO
model = YOLO('yolov8x-obb.pt')
model.export(format='engine')
'''

Could you confirm if this code incorporates the optimisations you mentioned? If not, could your team at Ultralytics modify the 'export' function to accommodate OBB models? This adjustment could benefit others using OBB models as well.

Regards,
Kamal Raj

**Comment by glenn-jocher** [comment]
@kkamalrajk hello,

It's great to hear that you've achieved a 2x improvement in inference speed with the 'yolov8x.pt' detection model after converting it to TensorRT format. However, it's understandable that you're looking for similar improvements with the 'yolov8x-obb.pt' model.

The difference in speedup between the two models when using TensorRT could be due to several factors, including the complexity of the model architecture, the operations used in the OBB model that may not be as optimized in TensorRT, and the data types used during inference.

Here are some potential strategies and considerations to help you optimize the 'yolov8x-obb.pt' model for TensorRT:

1. **Precision Tuning**: Ensure that you are using the appropriate precision (FP32, FP16, or INT8) for your model. FP16 can offer a good balance between speed and accuracy, while INT8 can provide the highest speedup but may require a careful calibration process to maintain accuracy.

2. **Layer Fusion**: Check if all possible layers are being fused during the TensorRT optimization process. Layer fusion can reduce memory access and improve inference speed.

3. **Model Simplification**: If possible, simplify the model by removing any unnecessary layers or operations that do not contribute significantly to the accuracy of the model.

4. **Batch Size**: Experiment with different batch sizes to find the optimal value for your specific use case. Larger batch sizes can sometimes improve throughput.

5. **Engine Optimization Profiles**: When building the TensorRT engine, use optimization profiles to specify the expected range of input dimensions. This can help TensorRT optimize the engine for varying input sizes.

6. **Dynamic Shapes**: If your model uses dynamic input shapes, ensure that TensorRT is properly handling them. Misconfiguration here can lead to suboptimal performance.

7. **Plugin Layers**: If the OBB model uses custom layers not natively supported by TensorRT, ensure that the custom plugins are optimized for performance.

8. **TensorRT Version**: Use the latest version of TensorRT, as each new release often includes performance improvements and bug fixes.

9. **Hardware Utilization**: Monitor the GPU utilization during inference to ensure that the GPU is being fully utilized. If not, there may be bottlenecks elsewhere in your pipeline.

10. **Profiling**: Use profiling tools like NVIDIA's Nsight Systems or Nsight Compute to identify bottlenecks in the model and target specific layers or operations for optimization.

If after trying these strategies you're still not seeing the expected improvements, it might be helpful to reach out to the NVIDIA forums or TensorRT support for more specific guidance, as they may have insights into optimizations that are specific to the operations used in the OBB model.

Keep in mind that some models may inherently not achieve the same level of speedup due to their structure and the operations they use, but with careful tuning and optimization, you should be able to get closer to your target performance.

**Comment by Petros626** [comment]
@kkamalrajk does INT8 engine work for OBB model?
