### ISSUE TITLE
YOLOv8 - custom model error

### ISSUE THREAD

**Issue by litaldavar** [ultralytics/ultralytics#808]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Yesterday all was well but today (02/05/23) 
the code broke 

please fix 
thankyou

### Minimal Reproducible Example

MODEL = r"runs/detect/train/weights/best.pt"
from ultralytics import YOLO

model = YOLO(MODEL)
model.fuse()

gives an error:

AttributeError                            Traceback (most recent call last)
[<ipython-input-13-8956eff8758b>](https://localhost:8080/#) in <module>
      1 from ultralytics import YOLO
      2 
----> 3 model = YOLO(MODEL)
      4 model.fuse()

5 frames
[/usr/local/lib/python3.8/dist-packages/torch/serialization.py](https://localhost:8080/#) in find_class(self, mod_name, name)
   1122                     pass
   1123             mod_name = load_module_mapping.get(mod_name, mod_name)
-> 1124             return super().find_class(mod_name, name)
   1125 
   1126     # Load the data (which may in turn use `persistent_load` to load tensors)

AttributeError: Can't get attribute 'IterableSimpleNamespace' on <module 'ultralytics.yolo.utils' from '/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/utils/__init__.py'>

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@litaldavar 👋 hi, thanks for letting us know about this possible problem. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by litaldavar** [comment]
You should provide support for custom data with your code

**Comment by AyushExel** [comment]
@litaldavar please use the latest version of the library.  Just use `pip install ultralytics`
