### ISSUE TITLE
How do I know how many objects are small, medium, or large during validation?

### ISSUE THREAD

**Issue by chioujryu** [ultralytics/ultralytics#8090]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

YOLOv5 and YOLOv8 have three outputs, predicting large, medium, and small objects respectively. I want to know, during validation, how many objects are large, how many are medium, and how many are small.

How can I find this out?

I have used both VOC and COCO datasets for validation.

**Comment by glenn-jocher** [comment]
@chioujryu during validation with YOLOv8, object sizes are categorized based on the area relative to the image size: small (area < 32^2), medium (32^2 < area < 96^2), and large (area > 96^2). To see the count of objects by size, you can check the validation results summary, which includes the number of targets per category. If you need more detailed statistics, consider modifying the validation code to count and print the sizes during processing. 📊🔍

**Comment by AREEG94FAHAD** [comment]
> @chioujryu during validation with YOLOv8, object sizes are categorized based on the area relative to the image size: small (area < 32^2), medium (32^2 < area < 96^2), and large (area > 96^2). To see the count of objects by size, you can check the validation results summary, which includes the number of targets per category. If you need more detailed statistics, consider modifying the validation code to count and print the sizes during processing. 📊🔍

Is this classification of object size the same for YOLOv11?

**Comment by Petros626** [comment]
@glenn-jocher https://github.com/ultralytics/ultralytics/issues/8090#issuecomment-2500179451

**Comment by glenn-jocher** [comment]
@Petros626 yes, YOLO11 maintains the same object size categorization as YOLOv8 for consistency in evaluation metrics. Small (<32²px), medium (32²-96²px), and large (>96²px) thresholds remain unchanged. These standards align with COCO evaluation practices detailed in the COCO Dataset documentation.

**Comment by Petros626** [comment]
How to evaluate after COCO with Yolov8 obb?

**Comment by glenn-jocher** [comment]
@Petros626 to evaluate YOLOv8 OBB models after training, use the `val` mode with your trained model and dataset:

```bash
yolo val obb model=path/to/best.pt data=coco.yaml
```

For oriented bounding box evaluation metrics and implementation details, see the Oriented Bounding Boxes documentation. Note that while COCO uses axis-aligned boxes, OBB evaluation requires datasets with rotated box annotations like DOTAv1. Ensure your dataset format matches OBB requirements.

**Comment by Petros626** [comment]
Unfortunately I realized later that, COCO needs axis aligned bounding boxes and not oriented like Yolov8 obb. So it's not mandatory for me now to evaluate after this metrics.

**Comment by glenn-jocher** [comment]
@Petros626 thanks for noting that! For OBB-specific evaluation metrics and compatible datasets like DOTA, refer to our Oriented Bounding Boxes documentation which details the validation process and supported rotated box formats. The Dataset Guide explains how to structure OBB datasets for accurate evaluation.

**Comment by hyago-harpia-ops** [comment]
@glenn-jocher we have a some objects considered tiny objects ? < 32px² ?

**Comment by glenn-jocher** [comment]
There isn’t a separate default `tiny` bucket in YOLO validation; any object with box area `w*h < 32^2` (that is, `< 1024` px²) is counted as `small`, so if you need `tiny/small/medium/large` counts you’ll need a custom validation split, and since this thread is stale please open a new issue for visibility and include your use case with the [performance metrics guide](https://docs.ultralytics.com/guides/yolo-performance-metrics) as context.

**Comment by hyago-harpia-ops** [comment]
Who is best model to detect small objects ? yolo26-p2 ? its the best ?

**Comment by glenn-jocher** [comment]
For new projects I’d start with Ultralytics YOLO26, and for small-object-heavy datasets a `P2` variant is usually the best first choice because it preserves finer spatial detail, but it’s not universally “best” since `imgsz`, tiling, annotation quality, and hardware constraints can matter just as much; this issue is stale, so please open a new issue for visibility and include sample images, and see the [small-object mAP guide](https://www.ultralytics.com/blog/how-to-improve-model-map-on-small-objects-a-quick-guide) and [model evaluation insights](https://docs.ultralytics.com/guides/model-evaluation-insights).
