### ISSUE TITLE
ValueError: too many values to unpack (expected 4)

### ISSUE THREAD

**Issue by Jeevan750** [ultralytics/ultralytics#8092]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

for the folollowing code which i tried running its showing an error " ValueError : too many values to unpack expected(4)"
 can anyone help me put by correcting the code
 
 
import cv2
import argparse
from ultralytics import YOLO
import supervision as sv
def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description = "YOLOv8 live")
    parser.add_argument(
        "--webcam-resolution", 
        default = [1280, 720],
        nargs=2,
        type =int
    )
    args = parser.parse_args()
    return args
def main():
    args = parse_arguments()
    frame_width, frame_height = args.webcam_resolution
    cap = cv2.VideoCapture(0)
    cap.set(cv2.CAP_PROP_FRAME_WIDTH, frame_width)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, frame_height)
    model = YOLO ("yolov8l.pt")
    box_annotator = sv.BoxAnnotator(
        thickness=2,
        text_thickness=2,
        text_scale=1
    )
    while True:
        ret, frame = cap.read()
        result = model(frame)[0]
        detections = sv.Detections.from_ultralytics(result)
        labels = [f"{model.model.names[class_id]} {confidence:0.2f}"
            for _, confidence, class_id,_ in detections
        ]
        frame = box_annotator.annotate(
            scene=frame, detections = detections,
            labels=labels
        )
        frame = box_annotator.annotate(scene=frame, 
                                       detections=detections, 
                                       labels=labels)
        cv2.imshow("yolov8", frame)
        if (cv2.waitKey(30) == 27):
            break
if __name__ == "__main__" : 
    main()

thank you

**Comment by Burhan-Q** [comment]
@Jeevan750 most likely due to this line `detections = sv.Detections.from_ultralytics(result)` which is something from a package not related to Ultralytics. You should raise this with the authors of that package if you feel the need, however I can tell you this is an error you _should be able_ to diagnose on your own. Read the error text _carefully_ and pay attention what it's telling you (the cause of the error). Once you understand the error, then read the documentation for any library and I assure you that you will figure out the remedy. If you still don't understand, then I _highly_ recommend that you put more time and effort into building your familiarity and foundational knowledge of python.

**Comment by glenn-jocher** [comment]
@Burhan-Q yes, this is right, for errors originating in other libraries we should direct users to raise issues directly with the authors of those packages as they are naturally outside the scope of our support.
