### ISSUE TITLE
ADD/Modify a yolo architecture

### ISSUE THREAD

**Issue by jsjoel** [ultralytics/ultralytics#8095]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

i have been trying to modify yolov8 structure by replacing conv with ODConv and one c2f block with convnext block . but after i saw previous post where i have to alter the conv.py, blocks.py,init.py and the yaml file and tasks.py.
It still says keyword error :ODconv_3d
![Screenshot 2024-02-08 195705](https://github.com/ultralytics/ultralytics/assets/97514566/c6e673f0-7650-4ffb-b9a3-7cfdd576e01b)

**Comment by glenn-jocher** [comment]
@jsjoel to modify the YOLOv8 architecture with custom layers like `ODConv` and `ConvNext` blocks, you need to ensure that these layers are correctly defined and imported in the respective `.py` files. The error `keyword error: ODconv_3d` suggests there might be an issue with the definition or the way it's being referenced in the model configuration `.yaml` file.

Please double-check the following:
1. The `ODConv` and `ConvNext` blocks are properly defined in their respective `.py` files.
2. They are correctly imported in `init.py`.
3. The `.yaml` file uses the correct layer names as defined in your code.
4. Ensure there are no typos in the layer names within the `.yaml` file and the code.

If the issue persists, could you please share the relevant code snippets or create a [new issue](https://github.com/ultralytics/ultralytics/issues/new/choose) with the details of the modifications and the full error message? This will help us assist you better. 👍

**Comment by jsjoel** [comment]
i have changed all the above but the error occurs in the parse_model class saying "model" keyword not found("odconv_3d" keyword not found). Do you need  further pics for more detailed view. And also im considering using other blocks to replace.
PS: im working it on google colab

**Comment by glenn-jocher** [comment]
@jsjoel hi there! It sounds like you're making great progress with customizing YOLOv8. 😊 If you've already made sure that all custom layers are correctly defined and imported, the issue might be with how the `parse_model()` function is handling the new keywords.

Could you please check if the `parse_model()` function in `models/yolo.py` (or the equivalent file if the structure has changed) is updated to recognize `ODconv_3d` as a valid module? It should be able to map this keyword to the corresponding class or function that creates your custom layer.

If you're still facing issues, a few screenshots or code snippets would definitely help to pinpoint the problem. Since you're on Google Colab, ensure that all the modified files are correctly uploaded and that the runtime is using the latest versions of those files.

And sure, experimenting with different blocks is a great way to find the best fit for your needs. Keep it up, and let's get this sorted out! 💪

**Comment by ahmedfarouk99** [comment]
@jsjoel did you managed to solve this problem?
if yes , can you help me in how to modify yolov8 backbone to use convnext block as backbone?
thanks in advance and sorry for bothering

**Comment by ahmedfarouk99** [comment]
@jsjoel ????

**Comment by jsjoel** [comment]
@ahmedfarouk99 no I haven't solved it yet....but I would like to contact you.

**Comment by ahmedfarouk99** [comment]
@jsjoel it's my pleasure
we can work on it together
how can we contact?

**Comment by jsjoel** [comment]
sharonjoel66@gmail.com contact me with the mail
