### ISSUE TITLE
Int8 tflite model is slower than .pt model

### ISSUE THREAD

**Issue by JasseurHadded1** [ultralytics/ultralytics#8099]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have a ".pt" model (a custom yolov8n-pose model), and I have exported it in tflite format. this is a benchmark of '.pt' model and 'int8.tflite' model using val mode and batch=1 in all cases

----------------------------------------------------------------
model     | device | inference time (ms) 
-----------------------------------------------------------------
.pt            |  gpu    | 8.7
---------------------------------------------------------------
.pt            |  cpu     | 41.1
---------------------------------------------------------------
int8.tflite | gpu     | 42.6
-------------------------------------------------------------
int8.tflite | cpu     | 42.8
-------------------------------------------------------------

So the int8.tflite model is slower than .pt model with cpu & gpu, I really didn't do anything other than exporting the model to tflite format with int8=True

I have seen some answers but they don't contain the problem! Anyone could help me?

Thanks,

**Comment by glenn-jocher** [comment]
@JasseurHadded1 hello! It's not uncommon for `.tflite` models to perform differently from their `.pt` counterparts due to various factors such as the model's architecture, the optimization techniques used during conversion, and the hardware it's being run on. For INT8 quantization, the speedup is typically observed on devices with dedicated INT8 accelerators. If you're not seeing the expected performance improvements, it could be due to the absence of such accelerators on your hardware or other bottlenecks in the inference pipeline.

For further optimization, you might consider:
- Ensuring that your TensorFlow Lite runtime is optimized for your hardware.
- Experimenting with different quantization configurations.
- Profiling the model to identify any specific layers or operations that are causing slowdowns.

Feel free to share more details or open a discussion in the [Ultralytics YOLOv8 Discussions](https://github.com/ultralytics/ultralytics/discussions) for community insights! 🚀
