### ISSUE TITLE
IndexError: index 2 is out of bounds for dimension 1 with size 2

### ISSUE THREAD

**Issue by pythonstuff8** [ultralytics/ultralytics#8105]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

when running code getting this error

### Environment

`Message: 'Setup complete \u2705 (4 CPUs, 7.9 GB RAM, 27.5/219.6 GB disk)'
Arguments: ()

OS                  Linux-6.1.0-rpi8-rpi-2712-aarch64-with-glibc2.36
Environment         Linux
Python              3.11.2
Install             pip
RAM                 7.86 GB
CPU                 Cortex-A76
CUDA                None

`

### Minimal Reproducible Example

`from ultralytics import YOLO
model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)
model.train(data="pf2-1/data.yaml", epochs=250,imgsz=224, plots=True)  # train the model
path = model.export(format="onnx")  # export the model to ONNX format`

### Additional

data.yaml
`names:
- face
- Suhaan
nc: 2

train: train/images
val: valid/images`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@pythonstuff8 it seems like there might be an issue with the dataset labels or the number of classes (`nc`) specified in your `data.yaml`. The error indicates that an index is being accessed which is beyond the available range, which often happens when the model expects more classes than provided in the dataset.

Please double-check the following:
1. Ensure that the `nc` value in `data.yaml` matches the actual number of unique classes in your dataset.
2. Verify that your label files correctly reference class indices within the range `[0, nc-1]`.

If the issue persists, could you please provide one of the label files from your dataset for further investigation? 🕵️‍♂️

**Comment by pythonstuff8** [comment]
[pf2-1.zip](https://github.com/ultralytics/ultralytics/files/14229424/pf2-1.zip)

**Comment by pythonstuff8** [comment]
my dataset

**Comment by pythonstuff8** [comment]
i have labels 1 and 0

**Comment by glenn-jocher** [comment]
@pythonstuff8 it looks like you're encountering an index error during training, which typically indicates that there's a mismatch between the number of classes the model expects and the number of classes provided in your dataset. Given that your `data.yaml` specifies 2 classes, please ensure that your model configuration (`yolov8n.pt`) is also set up for 2 classes.

Here's a concise checklist to troubleshoot the issue:
1. Verify that the `nc` (number of classes) in your model configuration matches the `nc` in `data.yaml`.
2. Check if the annotations in your dataset correctly reference class indices 0 and 1, without exceeding the index 1.
3. Ensure that there are no corrupted or incorrectly formatted annotation files in your dataset.

If the issue persists after these checks, please provide more details or consider opening an issue on the YOLOv8 GitHub repository for further assistance. 🛠️

**Comment by pythonstuff8** [comment]
fixed by fixing some stuff in my dataset thx
