### ISSUE TITLE
AttributeError: 'Results' object has no attribute 'obb'. See valid attributes below.

### ISSUE THREAD

**Issue by apiszcz** [ultralytics/ultralytics#8107]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

I am using predict. I am not using OBB as far as I know?
```

  File "/test/detection.py", line 171, in inference
    detections = sv.Detections.from_ultralytics(result)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/test/lib/python3.11/site-packages/supervision/detection/core.py", line 181, in from_ultralytics
    if ultralytics_results.obb is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/test/lib/python3.11/site-packages/ultralytics/utils/__init__.py", line 156, in __getattr__
    raise AttributeError(f"'{name}' object has no attribute '{attr}'. See valid attributes below.\n{self.__doc__}")
AttributeError: 'Results' object has no attribute 'obb'. See valid attributes below.

    A class for storing and manipulating inference results.

    Args:
        orig_img (numpy.ndarray): The original image as a numpy array.
        path (str): The path to the image file.
        names (dict): A dictionary of class names.
        boxes (torch.tensor, optional): A 2D tensor of bounding box coordinates for each detection.
        masks (torch.tensor, optional): A 3D tensor of detection masks, where each mask is a binary image.
        probs (torch.tensor, optional): A 1D tensor of probabilities of each class for classification task.
        keypoints (List[List[float]], optional): A list of detected keypoints for each object.

    Attributes:
        orig_img (numpy.ndarray): The original image as a numpy array.
        orig_shape (tuple): The original image shape in (height, width) format.
        boxes (Boxes, optional): A Boxes object containing the detection bounding boxes.
        masks (Masks, optional): A Masks object containing the detection masks.
        probs (Probs, optional): A Probs object containing probabilities of each class for classification task.
        keypoints (Keypoints, optional): A Keypoints object containing detected keypoints for each object.
        speed (dict): A dictionary of preprocess, inference, and postprocess speeds in milliseconds per image.
        names (dict): A dictionary of class names.
        path (str): The path to the image file.
        _keys (tuple): A tuple of attribute names for no
```n-empty attributes.

### Environment

_No response_

### Minimal Reproducible Example

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@apiszcz it seems like there's a misunderstanding here. The `Results` object in YOLOv8 does not have an `obb` attribute by default. The `obb` attribute is related to oriented bounding boxes, which are not part of the standard YOLOv8 `Results` object. If you're not using oriented bounding boxes in your project, you might want to check the `supervision` package or your custom code for any references to `obb` and adjust accordingly. If you need further assistance, please provide more context or code snippets, and we'll be happy to help! 😊🛠️

**Comment by apiszcz** [comment]
Understand, thank you. It appears to be related to my installation on a virtual environment.

**Comment by glenn-jocher** [comment]
@apiszcz it appears there's a misunderstanding in the code you're using. The `Results` object from the YOLOv8 inference does not have an attribute named `obb`. The error is occurring because the code is attempting to access `ultralytics_results.obb`, which doesn't exist in the YOLOv8 `Results` class.

The `Results` class contains the following attributes that you can use:
- `orig_img`: The original image as a numpy array.
- `orig_shape`: The original image shape in (height, width) format.
- `boxes`: A `Boxes` object containing the detection bounding boxes.
- `masks`: A `Masks` object containing the detection masks (if segmentation is performed).
- `probs`: A `Probs` object containing probabilities of each class for classification tasks.
- `keypoints`: A `Keypoints` object containing detected keypoints for each object (if pose estimation is performed).
- `speed`: A dictionary of preprocess, inference, and postprocess speeds in milliseconds per image.
- `names`: A dictionary of class names.
- `path`: The path to the image file.

Please ensure that you are using the correct attributes for the `Results` object. If you need oriented bounding box (OBB) support, you might be looking for a different model or feature that provides such information. YOLOv8's standard `Results` object does not include OBB data. If OBB is a feature you require, you may need to look into other models or repositories that support this feature, or consider contributing to the YOLOv8 repository to add such functionality.

**Comment by apiszcz** [comment]
Updated the systems to supervision 0.18 and to the latest yolo 8.1.18., example is not using or trying to access obb attributes. Using .track for predict.

**Comment by VMThong** [comment]
# if ultralytics_results.obb is not None:
        #     return cls(
        #         xyxy=ultralytics_results.obb.xyxy.cpu().numpy(),
        #         data={"xyxyxyxy": ultralytics_results.obb.xyxyxyxy.cpu().numpy()},
        #         confidence=ultralytics_results.obb.conf.cpu().numpy(),
        #         class_id=ultralytics_results.obb.cls.cpu().numpy().astype(int),
        #         tracker_id=ultralytics_results.obb.id.int().cpu().numpy()
        #         if ultralytics_results.obb.id is not None
        #         else None,
        #     )

        return cls(
            xyxy=ultralytics_results.boxes.xyxy.cpu().numpy(),
            confidence=ultralytics_results.boxes.conf.cpu().numpy(),
            class_id=ultralytics_results.boxes.cls.cpu().numpy().astype(int),
            mask=extract_ultralytics_masks(ultralytics_results),
            tracker_id=ultralytics_results.boxes.id.int().cpu().numpy()
            if ultralytics_results.boxes.id is not None
            else None,
        )

I edited in core.py and it's ok now.

**Comment by glenn-jocher** [comment]
@VMThong hey there! 😊 It looks like you've encountered an issue with accessing an attribute that doesn't exist in the YOLOv8 `Results` object when using it with the `supervision` package. The `obb` attribute you mentioned isn't a part of the standard YOLOv8 output, which is why you're seeing that error.

From your description, it seems you've already found a workaround by commenting out the `obb` related code in the `supervision` package. That's a good temporary fix! However, for a more permanent solution, you might want to ensure that your usage aligns with the expected output structure of YOLOv8. 

If you're using `.track` or `.predict`, you should be working with attributes like `boxes`, `masks`, and `keypoints` which are part of the YOLOv8 `Results`. Here's a quick example of how you might access these attributes safely:

```python
if hasattr(ultralytics_results, 'boxes'):
    # Now you can safely access boxes, confidences, etc.
    boxes = ultralytics_results.boxes.xyxy.cpu().numpy()
    confidence = ultralytics_results.boxes.conf.cpu().numpy()
    # and so on...
```

It's great to hear you managed to get it working! If you have further questions or run into more issues, feel free to reach out. Happy coding! 🚀

**Comment by otpidusmatar** [comment]
Somehow, in my case, when I edited the model prediction line before fetching results from supervision as so:
`
result = model(frame, agnostic_nms=True)[0]
detections = sv.Detections.from_ultralytics(result)

`
The error went away. I'm curious as to how this worked, as I was facing the same obb error, but this did work for me.

**Comment by glenn-jocher** [comment]
@otpidusmatar hey there! 😊 It's great to hear that your issue was resolved! By setting `agnostic_nms=True`, you're instructing the model to apply Non-Maximum Suppression (NMS) in a class-agnostic manner. This means it combines overlapping detections of all classes, potentially altering the structure or content of the results in a way that avoids the `obb` error when interfacing with the `supervision` package.

Here's a quick breakdown:
```python
result = model(frame, agnostic_nms=True)[0]  # Applies class-agnostic NMS
detections = sv.Detections.from_ultralytics(result)  # Converts results without the 'obb' issue
```

It seems like the `agnostic_nms` might have indirectly influenced how the results are structured, making them compatible with what `supervision.Detections.from_ultralytics` expects. It's a bit of a happy accident! 🍀 If you have more questions or need further clarification, feel free to ask. Happy coding!
