### ISSUE TITLE
Running custome training

### ISSUE THREAD

**Issue by Sarathkrishnask** [ultralytics/ultralytics#8128]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

%cd {HOME}

!yolo task=obb mode=train model=yolov8s-obb.pt data={dataset.location}/data.yaml epochs=35 imgsz=640 batch=8

give error::--

Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 568, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 601, in train
    self.trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 208, in train
    self._do_train(world_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 424, in _do_train
    self.metrics, self.fitness = self.validate()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 543, in validate
    metrics = self.validator(self)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/validator.py", line 193, in __call__
    stats = self.get_stats()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/detect/val.py", line 170, in get_stats
    stats = {k: torch.cat(v, 0).cpu().numpy() for k, v in self.stats.items()}  # to numpy
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/detect/val.py", line 170, in <dictcomp>
    stats = {k: torch.cat(v, 0).cpu().numpy() for k, v in self.stats.items()}  # to numpy
RuntimeError: torch.cat(): expected a non-empty list of Tensors

### Additional

while run the custome training code snippet , i faced this problem

**Comment by glenn-jocher** [comment]
@Sarathkrishnask it seems like there's an issue with the validation step during training. Could you please check if your `data.yaml` is correctly set up with valid paths to your train and val datasets? Also, ensure that your dataset contains labeled data. If the problem persists, consider sharing your `data.yaml` and a few sample annotations for further assistance. 👍

**Comment by MaxRondelli** [comment]
I got the same error. In my case I run the training with 50 epochs and I've the issue at the end of the 19th epoch. For further assistance @glenn-jocher, I share you my dataset.yaml. 
```
train: ../data/images/training
val: ../data/images/validation

# Number of classes 
nc: 1

# Class names
names: ['Bounding Box']
```

train.py
```
from ultralytics import YOLO

# Load a model 
model = YOLO("yolov8n.pt")

results = model.train(
    data = 'data/dataset.yaml',
    epochs = 50,
    batch = 16,
    name = 'yolo8n_custom'
)
```

Thank you in advance.

**Comment by glenn-jocher** [comment]
@MaxRondelli it looks like you're encountering an issue during the training process with YOLOv8. The error message `RuntimeError: torch.cat(): expected a non-empty list of Tensors` suggests that there might be a problem with the data being passed to `torch.cat()`, possibly due to an empty list or incorrect data processing.

To help resolve this issue, please ensure the following:
- Your dataset is correctly formatted and accessible by the model.
- The `data.yaml` file correctly points to your train and validation data with the correct paths.
- You have the latest version of the Ultralytics YOLOv8 repository.

If the problem persists, please open an issue on the [Ultralytics YOLOv8 GitHub repository](https://github.com/ultralytics/ultralytics/issues) with detailed information about your dataset structure and the full error traceback. This will help us diagnose the issue more effectively. 🛠️

In the meantime, you might want to try running a smaller test by reducing the `batch` size or `epochs` to see if the issue is related to the size of the data or a specific part of the dataset.

**Comment by Sarathkrishnask** [comment]
I checked my data.yaml file, setup the path for train, test, and valid paths are correct. even I've only once class for object detection. but still, I have same error in 13th epochs... I used labelling for roboflow..

path: ../datasets/roboflow

train: /content/datasets/objdetection-2/train/images
val: /content/datasets/objdetection-2/valid/images
test: /content/datasets/objdetection-2/test/images

nc: 1
names: ['car']
this is the structure of my data.yaml file..

**Comment by glenn-jocher** [comment]
@Sarathkrishnask it appears that you're encountering a runtime error during the validation step of your custom training process with YOLOv8. The error message indicates that `torch.cat()` is expecting a non-empty list of tensors, but it seems to be receiving an empty list instead.

This issue could be caused by several factors, including:

1. **Empty or incorrect dataset**: Ensure that your dataset is correctly formatted and that the paths to your images and annotations are correct. The dataset should not be empty and should match the expected format required by YOLOv8.

2. **Incorrect data.yaml**: Verify that your `data.yaml` file is correctly set up with the right paths to your train, val, and test datasets, as well as the correct number of classes.

3. **Model compatibility**: Make sure that the model you are using (`yolov8s-obb.pt`) is compatible with the task you are trying to perform and that it is properly configured for your dataset.

4. **Software version**: Check if you are using the latest version of the Ultralytics YOLOv8 repository. If not, consider updating to the latest version as it may contain bug fixes that could resolve your issue.

5. **Hardware resources**: Ensure that your training environment has sufficient memory and compute resources. Sometimes, out-of-memory issues can cause unexpected behavior.

To troubleshoot this issue, you can try the following steps:

- Double-check your `data.yaml` file for any mistakes in the dataset paths or class definitions.
- Make sure your dataset contains images and corresponding annotations.
- If you're using a custom dataset, ensure that it's properly labeled and that the labels are in the correct format expected by YOLOv8.
- Try running the validation step separately with a smaller subset of your data to see if the issue persists.
- Review the command you're using to start the training process and ensure that all arguments are correct.

If you continue to experience issues, you may want to reach out to the Ultralytics YOLOv8 community on GitHub with detailed information about your dataset, model configuration, and the steps you've taken to resolve the issue. This will help others to provide more targeted assistance.

**Comment by MaxRondelli** [comment]
@glenn-jocher I have solved the issue. The name of the folders in images and labels path were "training" and "validation" rather than "train" and "val". This causes some problems during the training. In addition to this, the coordinates in the txt files weren't formatted in the correct way for the model. Now it works great.

Thank you for your help and time.

**Comment by glenn-jocher** [comment]
@MaxRondelli it appears that you are encountering an error during the validation step of your custom training process with YOLOv8. The error message indicates that `torch.cat()` is expecting a non-empty list of Tensors, but it seems to be receiving an empty list instead.

This issue could be caused by several factors, including:

1. **Empty or incorrect dataset**: Ensure that your dataset is correctly formatted and that the paths to your images and annotations are correct. The `data.yaml` file should correctly reference the location of your training and validation datasets.

2. **Incorrect model configuration**: Verify that the model configuration (`yolov8s-obb.pt`) is appropriate for your dataset and that the model file exists.

3. **Validation dataset issue**: There might be an issue with the validation dataset where no predictions are being made, resulting in empty statistics. Check if your validation dataset is properly set up and contains valid data.

4. **Software version mismatch**: Make sure that you are using the correct version of the Ultralytics YOLOv8 repository and that all dependencies are up to date.

To troubleshoot this issue, you can try the following steps:

- Double-check your `data.yaml` file to ensure that all paths are correct and that the dataset is not empty.
- Make sure that the validation dataset is accessible and contains the correct annotations.
- If you are using a custom model configuration, ensure that it is compatible with your dataset and that the model file is correctly specified.
- Run a small test by training on a few images to see if the issue persists.
- Check the Ultralytics YOLOv8 repository for any similar issues reported by other users and see if there are any suggested fixes.

If the problem continues after these checks, you may want to share more details about your dataset and model configuration, or consider opening an issue in the Ultralytics YOLOv8 GitHub repository for further assistance from the developers.

**Comment by Sarathkrishnask** [comment]
val: WARNING ⚠️ /content/datasets/objdetection-2/valid/images/28_jpg.rf.7190e90152a42a54f3d8e73fc16af310.jpg: ignoring corrupt image/label: could not convert string to float: 'gun'
val: WARNING ⚠️ /content/datasets/objdetection-2/valid/images/35_jpg.rf.533e19fe910dd88b6300dad1ece36f28.jpg: ignoring corrupt image/label: could not convert string to float: 'gun'
val: WARNING ⚠️ /content/datasets/objdetection-2/valid/images/37_jpg.rf.f111beb94d9dd74d5354f7f73871bb28.jpg: ignoring corrupt image/label: could not convert string to float: 'gun'
val: WARNING ⚠️ /content/datasets/objdetection-2/valid/images/3_jpg.rf.db20dbde0023d58a8cc469341be9dd5b.jpg: ignoring corrupt image/label: could not convert string to float: 'gun'
val: WARNING ⚠️ /content/datasets/objdetection-2/valid/images/45_jpg.rf.11fc0cb4b62e9b646a9392eea04899cd.jpg: ignoring corrupt image/label: could not convert string to float: 'gun'
val: WARNING ⚠️ /content/datasets/objdetection-2/valid/images/50_jpg.rf.2beb6e317a0f460e566b02cc384d7afb.jpg: ignoring corrupt image/label: could not convert string to float: 'gun'
val: WARNING ⚠️ /content/datasets/objdetection-2/valid/images/51_jpg.rf.5eab73cf0c1bb5092170f175089febfe.jpg: ignoring corrupt image/label: could not convert string to float: 'gun'
val: WARNING ⚠️ /content/datasets/objdetection-2/valid/images/53_jpg.rf.893a0b116c42b34723e32bcad036aea8.jpg: ignoring corrupt image/label: could not convert string to float: 'gun'
val: New cache created: /content/datasets/objdetection-2/valid/labels.cache
WARNING ⚠️ No images found in /content/datasets/objdetection-2/valid/labels.cache, training may not work correctly. See https://docs.ultralytics.com/datasets/detect for dataset formatting guidance.
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 568, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 601, in train
    self.trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 208, in train
    self._do_train(world_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 322, in _do_train
    self._setup_train(world_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 289, in _setup_train
    self.test_loader = self.get_dataloader(
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/detect/train.py", line 49, in get_dataloader
    dataset = self.build_dataset(dataset_path, mode, batch_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/detect/train.py", line 43, in build_dataset
    return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=mode == "val", stride=gs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/build.py", line 87, in build_yolo_dataset
    return YOLODataset(
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/dataset.py", line 42, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/base.py", line 74, in __init__
    self.labels = self.get_labels()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/dataset.py", line 139, in get_labels
    len_cls, len_boxes, len_segments = (sum(x) for x in zip(*lengths))
ValueError: not enough values to unpack (expected 3, got 0)


I have change all parameters in data.yaml..  can you help me to recitfy this error...

**Comment by glenn-jocher** [comment]
@Sarathkrishnask it appears that you are encountering an error during the validation step of your custom training process with YOLOv8. The error message indicates that there is an issue with concatenating an empty list of tensors, which suggests that there might be a problem with the validation dataset or the way it is being processed.

Here are a few steps you can take to troubleshoot and resolve this issue:

1. **Check Your Dataset**: Ensure that your validation dataset is correctly set up and that the `data.yaml` file points to the correct paths for your validation images and labels. The dataset should not be empty and should contain valid data.

2. **Verify Data Paths**: Double-check the paths specified in your `data.yaml` file to make sure they are correct and accessible from your current working directory.

3. **Inspect Labels**: Make sure that the labels for your validation dataset are present and properly formatted. The labels should match the format expected by YOLOv8.

4. **Dataset Configuration**: Review the `data.yaml` file to confirm that the `val` key is correctly defined and points to your validation dataset.

5. **Model Compatibility**: Ensure that the model you are using (`yolov8s-obb.pt`) is compatible with the task you are trying to perform and that it is properly configured for oriented bounding box (OBB) detection.

6. **Update Ultralytics YOLO**: If you haven't already, update the Ultralytics YOLO package to the latest version to ensure that you have all the latest fixes and improvements.

7. **Run a Minimal Example**: Try running a minimal training example with a small subset of your data to see if the issue persists. This can help isolate the problem.

8. **Check for Known Issues**: Look at the Ultralytics YOLO GitHub repository's issues section to see if others have reported similar problems and if there are any suggested solutions.

If you continue to experience issues after trying these steps, consider reaching out to the Ultralytics YOLO community on GitHub with detailed information about your dataset, training configuration, and the steps you've taken to troubleshoot the problem. This will help others assist you more effectively.

**Comment by Sarathkrishnask** [comment]
Sorry @glenn-jocher  for not update, I sort out the issues, the error because of me, I made small mistakes in my code.. now issue is gone, thanks for your quick response...

Thankyou for support

**Comment by glenn-jocher** [comment]
@Sarathkrishnask the error message you're encountering indicates that there's an issue during the validation step of the training process. Specifically, the `torch.cat()` function is expecting a non-empty list of Tensors, but it seems to be receiving an empty list instead.

This could be due to several reasons, such as:

1. There are no valid detections being made on the validation dataset.
2. The validation dataset is not correctly set up or is empty.
3. There might be an issue with the model or the training configuration.

To troubleshoot this issue, you can try the following steps:

1. **Check the Validation Dataset**: Ensure that your validation dataset is correctly set up in the `data.yaml` file and that it contains valid annotation data. Verify that the paths to the images and labels are correct and accessible.

2. **Review the Data YAML File**: Open the `data.yaml` file and check that it has the correct structure, including the `train`, `val`, and `nc` (number of classes) fields. It should look something like this:

    ```yaml
    train: path/to/train/images
    val: path/to/val/images
    nc: number_of_classes
    names: ['class1', 'class2', ...]
    ```

3. **Inspect the Annotations**: Make sure that the annotations for the validation dataset are present and correctly formatted. If the annotations are missing or incorrect, the model won't be able to make any valid detections, resulting in an empty list of Tensors.

4. **Model Configuration**: Double-check that you're using the correct model configuration for your task. Since you're using `task=obb`, ensure that the `yolov8s-obb.pt` model is compatible with oriented bounding box (OBB) tasks.

5. **Run a Sanity Check**: Before running the full training, you can perform a quick test by validating the model on a few images to ensure that the setup is correct. You can use the `val` mode with a small subset of your validation data.

6. **Update the Repository**: Make sure you have the latest version of the Ultralytics YOLOv8 repository. If not, update it and try running the training again.

7. **Check for Known Issues**: Visit the Ultralytics YOLOv8 GitHub repository and check the issues and discussions for any known problems related to your error message.

If you've gone through these steps and the issue persists, you may want to reach out to the Ultralytics team with detailed information about your setup, including the `data.yaml` file and a sample of your dataset, if possible. This will help them diagnose the issue more effectively.

**Comment by Sarathkrishnask** [comment]
I made a mistake validation labels, So that's reason i have that error .. @glenn-jocher

**Comment by glenn-jocher** [comment]
@Sarathkrishnask the error message you're encountering indicates that there is an issue during the validation step of the training process. Specifically, the `torch.cat()` function is expecting a non-empty list of Tensors, but it seems to be receiving an empty list instead. This could be due to several reasons, such as issues with the validation dataset, incorrect paths, or other configuration problems.

Here are a few steps you can take to troubleshoot this issue:

1. **Check Dataset**: Ensure that your validation dataset is correctly set up and that the `data.yaml` file points to the correct paths for the validation images and labels. The dataset should not be empty and should contain valid data.

2. **Verify Paths**: Double-check the paths specified in your `data.yaml` file. Make sure that the paths for `train`, `val`, and `test` (if applicable) are correct and accessible from the environment where you're running the training.

3. **Review Configuration**: Look over the `data.yaml` and any other configuration files to ensure that all settings are correct. Pay special attention to any custom settings that might affect the validation process.

4. **Update Software**: Make sure you are using the latest version of the Ultralytics YOLOv8 repository. Sometimes, bugs are fixed in newer releases that could resolve your issue.

5. **Reduce Complexity**: Try running a simpler training command with fewer custom arguments to see if the issue persists. This can help isolate whether the problem is with the dataset or the additional parameters.

6. **Check for Empty Annotations**: Ensure that your validation dataset does not contain any images with empty annotations. All images used for validation should have corresponding annotation files with at least one valid object.

7. **Inspect Annotations**: Verify that the annotation files are correctly formatted and contain valid bounding box information. Incorrectly formatted annotations could lead to an empty tensor list during validation.

8. **Run a Sanity Check**: Perform a sanity check by running the training with a known good dataset (like COCO128) and configuration to ensure that the issue is not with the training setup itself.

If you've gone through these steps and the issue persists, you may want to reach out to the Ultralytics team with detailed information about your dataset, configuration, and the steps you've taken to troubleshoot. Providing this information can help the developers or the community assist you more effectively.
