### ISSUE TITLE
Scaling issue at save_txt with OBB

### ISSUE THREAD

**Issue by molnarszilard** [ultralytics/ultralytics#8149]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

Hi!

After I trained the OBB model I wanted to predict the oriented bounding boxes. I noticed that the bounding boxes were correctly placed on the image.
However, when I used 'save_txt=True' to save the labels, and then tried to plot the rectangles on the images from the given coordinates, the points on the Y-axis were weird. Then after a while, I realized that if I scaled the Y coordinates of each point, the plots would be correct. Then I found the scale is image_width/image_height.
Therefore, I assume, that when the prediction script saves the coordinates in the .txt file, the Y coordinates are normalized with the width of the image, but they should be normalized with the height of the image.

The problem occurs with both the DOTA dataset, and my custom dataset as well.
Or is this the intended behaviour?

(In case the problem occurs because I did not update something, or if this issue is already posted, just did not see, sorry.)

### Environment

Ultralytics YOLOv8.1.0 🚀 Python-3.8.17 torch-1.10.0 CUDA:0 (NVIDIA A100-PCIE-40GB, 40354MiB)

Ubuntu 20.04

### Additional

I did not want to open an issue, because it is not necessarily a bug, just an annoyance (and it is related to this issue). At the site https://docs.ultralytics.com/datasets/obb/#yolo-obb-format the order of the points along the rectangle is in the clockwise direction, while the saved coordinates are in the counterclockwise direction.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@molnarszilard hello! Thanks for bringing this to our attention. 🌟

It seems like there might be an issue with the normalization of the Y coordinates during the `save_txt` process. The Y coordinates should indeed be normalized using the image height rather than the width. We'll look into this and aim to address it promptly.

Regarding the order of points for the OBB, the documentation might need an update to reflect the actual order used in the saved coordinates. We appreciate your keen observation on this!

If you have any further insights or questions, feel free to share. Meanwhile, we'll work on fixing these quirks to improve your experience with YOLOv8. 🛠️

Thanks again for your contribution to making YOLOv8 better!

**Comment by molnarszilard** [comment]
Hi, maybe you are aware, but just in case I mention this:
I updated to Ultralytics YOLOv8.1.14, and now the X coordinates are also wrong.
If I want to plot the results from the saved labels, I have to scale the Y component with W/H, and the X component with H/W.
I suppose, whoever attempted the correction, instead of normalizing the Y component with the height, the X component was normalized with the height. I am afraid, that somewhere in that code the X-Y coordinates swapped. (I know sometimes it is difficult to pay attention to it. When I am coding, even easier tasks are complicated; for example, the axes are swapped between numpy and cv2)
But still, I am thankful for the fast reply and action. :1st_place_medal:

**Comment by glenn-jocher** [comment]
@molnarszilard thank you for bringing this to our attention. It seems like you've encountered an issue where the Y-axis coordinates are not being normalized correctly when saving the oriented bounding box (OBB) annotations to a text file using `save_txt=True`. This could potentially be a bug in the code that handles the normalization of the coordinates for the OBB format.

Regarding the order of the points along the rectangle being counterclockwise instead of clockwise as documented, this could be an inconsistency in the documentation or the implementation. We will need to verify this behavior and ensure that the documentation matches the actual output of the model.

To address these issues, we would need to:

1. Reproduce the issue with the incorrect normalization of the Y-axis coordinates.
2. Verify the order of the points along the rectangle and update the documentation or the implementation accordingly to ensure consistency.

Since you've already checked the existing issues and didn't find a similar report, I would recommend opening a new issue on the Ultralytics YOLOv8 GitHub repository with the details you've provided here. This will allow the Ultralytics team to track the problem and provide a fix in a future update.

In the meantime, as a temporary workaround, you can manually adjust the Y-axis coordinates based on the image height when plotting the rectangles from the saved text files.

Regarding your willingness to submit a PR, if you have identified the source of the issue and feel comfortable making code changes, you are welcome to contribute a fix. Otherwise, the Ultralytics team will handle it once the issue is reported.

Please let me know if you need any further assistance or if you would like me to open the issue on your behalf.

**Comment by KybernetikJo** [comment]
- [x] Scaling issue is fixed by #8249
- []  The Additional issue is harder.
https://github.com/ultralytics/ultralytics/issues/8149#issue-2130053060

There is a problem with the `ops.xywhr2xyxyxyxy` method. I think with the current implementation of `cv2.minRectArea` a bijective transformation is impossible. However, the method `ops.xywhr2xyxyxyxy` can possibly be improved. I am not completely sure, though.

**Comment by glenn-jocher** [comment]
Hey @KybernetikJo, thanks for the update! 🚀

Great to hear the scaling issue has been resolved with #8249. 👍

Regarding the point order for OBB, it's indeed a bit trickier. The `ops.xywhr2xyxyxyxy` method's reliance on `cv2.minAreaRect` can introduce some complexity due to its non-bijective nature. If you have ideas on how to enhance `ops.xywhr2xyxyxyxy`, we'd love to hear them! Otherwise, we'll keep investigating to ensure our documentation and implementation are aligned.

Keep the feedback coming, it's super helpful! 🛠️

**Comment by molnarszilard** [comment]
Thank you for solving the scaling issue so fast.
Regarding the order of points. At the moment I do not have much time to analyse your code (therefore I cannot say why it is a problem to do cw direction when the cv.minAreaRect also uses cw), But your code does well what I need. For my purposes, I just swap points 1 and 3, and then convert the labels to the xywhr format for further processing. It is not a big deal. Maybe put a disclaimer or something in the documentation, that says that at the output the points are in ccw direction. (I have not tried ccw points on the input side of the model, therefore I do not know if you could just say, that your code works with ccw and not cw.)

**Comment by glenn-jocher** [comment]
Hey @molnarszilard, thanks for reaching out and for your understanding! 🌟

We're glad to hear the scaling fix is working well for you. Regarding the point order, we appreciate your suggestion and will certainly consider adding a note to our documentation to clarify the current behavior with counterclockwise points. 

In the meantime, your approach to swap points 1 and 3 sounds like a neat workaround. If you ever decide to dive deeper into the code or have any insights to share, we'd be all ears. Your input is invaluable to us!

Happy coding, and let us know if there's anything else we can assist you with! 🛠️
