### ISSUE TITLE
Training Issue

### ISSUE THREAD

**Issue by Mary14-design** [ultralytics/ultralytics#8157]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

Hey All! I want to use yolo8 model for hardware aware training using AIHWKIT. I convert the model to analogue and then run training, but I keep runing into this issue while training the analogue model

`Traceback (most recent call last):
  File "/home/jovyan/test.py", line 120, in <module>
    training_loop(torch_analog_mdl, crit, opt, training_data, valid_data)
  File "/home/jovyan/test.py", line 82, in training_loop
    train_loss = train_step(train_data, mdl, criterion, optimizer)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/test.py", line 53, in train_step
    mdl.train()
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2288, in train
    module.train(mode)
  File "/opt/conda/lib/python3.11/site-packages/ultralytics/engine/model.py", line 582, in train
    self.trainer = (trainer or self._smart_load("trainer"))(overrides=args, _callbacks=self.callbacks)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'bool' object is not callable`

Here is the training function ,

`

def train_step(train_data, mdl, criterion, optimizer):

    total_loss = 0

    mdl.train()

    for images, labels in train_data:
        images = images.to(DEVICE)
        labels = labels.to(DEVICE)
        optimizer.zero_grad()

        # Add training Tensor to the mdl (input).
        output = mdl(images)
        loss = criterion(output, labels)

        # Run training (backward propagation).
        loss.backward()

        # Optimize weights.
        optimizer.step()
        total_loss += loss.item() * images.size(0)
    train_dataset_loss = total_loss / len(train_data.dataset)

    return train_dataset_loss
`

mdl is the converted YOLO model.

Here is the aihwkit documentation https://aihwkit.readthedocs.io/en/latest/hwa_training.html

### Minimal Reproducible Example

def train_step(train_data, mdl, criterion, optimizer):

    total_loss = 0

    mdl.train()

    for images, labels in train_data:
        images = images.to(DEVICE)
        labels = labels.to(DEVICE)
        optimizer.zero_grad()

        # Add training Tensor to the mdl (input).
        output = mdl(images)
        loss = criterion(output, labels)

        # Run training (backward propagation).
        loss.backward()

        # Optimize weights.
        optimizer.step()
        total_loss += loss.item() * images.size(0)
    train_dataset_loss = total_loss / len(train_data.dataset)

    return train_dataset_loss

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Mary14-design hello! It looks like you're encountering a `TypeError` because the `trainer` attribute in your YOLO model is expected to be a callable (like a function or class instance with a `__call__` method), but it's actually a boolean value at the moment. This could be due to the way the model is being converted for analogue training with AIHWKIT.

To resolve this, ensure that the `trainer` attribute is set correctly after conversion. If you're using custom training loops, you might not need to set a `trainer` at all. Here's a simplified snippet of how your training loop might look:

```python
def train_step(train_data, mdl, criterion, optimizer):
    mdl.train()  # Set the model to training mode
    total_loss = 0
    for images, labels in train_data:
        images, labels = images.to(DEVICE), labels.to(DEVICE)
        optimizer.zero_grad()
        output = mdl(images)
        loss = criterion(output, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * images.size(0)
    return total_loss / len(train_data.dataset)
```

Make sure to remove or update any references to `self.trainer` in your model if it's not intended to be used. If you're following the AIHWKIT documentation, double-check that the model conversion steps are compatible with YOLOv8's architecture.

If the issue persists, could you provide more details about the conversion process or share a snippet of how you're integrating AIHWKIT with YOLOv8? This will help us understand the context better. 😊

Keep up the great work, and we're here to help you get past this hurdle!

**Comment by Mary14-design** [comment]
Thank you for the reply! That is the same function I am using, and it does not seem to be an issue with the converted model.

**Comment by glenn-jocher** [comment]
@Mary14-design it appears that the issue you're encountering is related to the `mdl.train()` call in your `train_step` function. The error message indicates that there's a `TypeError` because a 'bool' object is being treated as if it were callable. This suggests that somewhere in your code, you may have assigned a boolean value to an attribute or variable that is expected to be a function or a class instance that can be called.

The specific line in the error message that points to the issue is:
```python
self.trainer = (trainer or self._smart_load("trainer"))(overrides=args, _callbacks=self.callbacks)
```
This line is part of the `train` method in the `ultralytics.engine.model` module, which is not directly visible in the code snippet you provided. It seems that the `train` method is expecting `trainer` to be a callable object (like a class or function), but it's actually a boolean value.

Without seeing the full context of your code and how you're integrating AIHWKIT with YOLOv8, it's difficult to provide a precise solution. However, here are some steps you can take to troubleshoot the issue:

1. Check the `mdl` object and ensure that it's an instance of a class that inherits from `torch.nn.Module` and that it has not been inadvertently modified to have a boolean value where a callable is expected.

2. Review the process of converting the YOLO model to an analogue model using AIHWKIT. Ensure that the conversion process preserves the structure and methods of the original model, particularly the `train` method.

3. If you're modifying the YOLOv8 model or its training loop, ensure that you're not overwriting any methods or attributes with boolean values.

4. If you're using custom callbacks or a custom trainer, make sure they are implemented correctly and are callable as expected by the YOLOv8 training loop.

5. Since the error is occurring within the Ultralytics codebase, you may need to adapt the training loop to work with the analogue model. This could involve overriding the `train` method or providing a custom trainer that is compatible with AIHWKIT.

If you continue to face difficulties, consider reaching out to the AIHWKIT community or the maintainers of the YOLOv8 repository for more specific guidance on integrating the two frameworks.

**Comment by wunder-waffe** [comment]
@Mary14-design Hello, I am also trying to convert a YOLO model to analog equivalent using aihwkit, is there a possibility that you can make your repository public?

**Comment by Mary14-design** [comment]
@wunder-waffe apologies I just saw the comment; did you manage to make it work?

**Comment by wunder-waffe** [comment]
> @wunder-waffe apologies I just saw the comment; did you manage to make it work?

No problem. No, unfortunately, I couldn't. I have been trying to convert the Ultralytics digital model to an analog model but I suspect that the internal algorithm is too complicated to just convert with a single `aihwkit` function `convert_to_analog` as the analog equivalent fails to perform any inference. If you had any success doing analog training of any YOLO model, please contact me at berkehan.ercan@ug.bilkent.edu.tr

**Comment by glenn-jocher** [comment]
I'm glad you're exploring analog training with YOLO models. Unfortunately, I can't provide private support or contact you directly. If you have specific questions, feel free to ask here, and I'll do my best to assist.
