### ISSUE TITLE
Changing the YOLOv8 Head to output corner points

### ISSUE THREAD

**Issue by Wissiak** [ultralytics/ultralytics#8171]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I would like to use the YOLOv8 model in order to detect cube nets:
![500px-Würfelnetze svg](https://github.com/ultralytics/ultralytics/assets/31206249/13734685-380a-4539-a757-b2cb912a36ee)
But instead of bounding boxes I would like to get the corner points of each shape. This would help me to find the homography which is what I am looking for. But I have a few questions regarding how I should start with this adaption.
1. Adaptions for the output should be done in the head of the model, right? 
2. I thought I could use the yolov8-obb.yaml as a starting point. The last line is `[[15, 18, 21], 1, OBB, [nc, 1]] # OBB(P3, P4, P5)` - what files is this referring to and can someone outline how I could adapt this to use my own header?
3. I would like the output to predict between 8 to 12 corner points, depending on the given shape. Is this feasible for example by annotating unused corner points with 0?

**Comment by glenn-jocher** [comment]
@Wissiak hi there! 👋 It's great to see your interest in adapting YOLOv8 for cube net detection with corner points. Here's a brief guide to get you started:

1. Yes, modifications for custom outputs like corner points are typically made in the model's head. You'll need to adjust the architecture to output the coordinates of the corners.

2. The `yolov8-obb.yaml` is indeed a good starting point as it's designed for oriented bounding boxes (OBB). The line you're referring to specifies the layers and the output format. To adapt it, you'll need to modify the model definition in the YAML file and corresponding layers in the code to output your desired corner points.

3. Predicting a variable number of corner points can be challenging. One approach could be to always predict the maximum number of points (e.g., 12) and use a confidence score to determine if a point is used or not. You would annotate unused points with a confidence of 0.

Here's a pseudo code snippet to illustrate the YAML change:

```yaml
[[15, 18, 21], 1, CustomHead, [nc, 12]] # CustomHead(P3, P4, P5) for 12 corner points
```

And in your custom head implementation, you would handle the variable number of points based on confidence scores.

Remember to adjust your annotations and loss function accordingly to handle the corner points and their confidences. Good luck with your project! If you have more questions or need further assistance, feel free to ask. 😊

**Comment by Wissiak** [comment]
@glenn-jocher Thanks for the answer - I think I got the custom head for corner detection setup and now I need to define the loss function. I followed the OBB scheme but I got a few questions regarding the calculation of the loss:
1. The following code `feats, pred_angle = preds if isinstance(preds[0], list) else preds[1]` sets `pred_angle` to a tensor of size (16, 8400, 12) and `feats` is an array of 3 tensors [(16,75,80,80),(16,75,40,40),(16,75,20,20)]. What are these values? I guess `feats` contains the image information, right?
2. What are the values of `pred_distri` (16,8400,64) and `pred_scores` (16,8400,11) from the following code?:
```
 pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
       (self.reg_max * 4, self.nc), 1
  )
```
3. Do you agree that the loss for corner points should be relatively simple? E.g. Euclidean distance between predicted corners and true corners. 
4. How can I obtain the true predicted corner points from the model output? Do I have to involve non maximum suppression already?

**Comment by glenn-jocher** [comment]
@Wissiak hello! It's great to see that you're looking to adapt YOLOv8 for your specific use case of detecting cube nets and obtaining corner points for homography. Let's address your questions one by one:

1. **Adaptations for the output in the model head:**
   Yes, you are correct. The head of the model is responsible for making final predictions, and this is where you would modify the architecture to output corner points instead of bounding boxes. The head will need to predict a fixed number of points for each detected object.

2. **Using `yolov8-obb.yaml` as a starting point:**
   The `yolov8-obb.yaml` file is a model configuration file that defines the architecture of the model, including the head. The line `[[15, 18, 21], 1, OBB, [nc, 1]]` specifies the layers that the OBB (Oriented Bounding Box) head is applied to (`P3`, `P4`, `P5` are feature pyramid levels), the number of heads, the head type (`OBB`), and the output channels (`nc` for number of classes, and `1` for the objectness score).

   To adapt this for your own header, you would need to create a custom head that predicts the corner points. This would involve defining a new head type in the model code (similar to how `OBB` is defined) and updating the configuration file to use this new head type. The actual implementation would require modifying the model architecture code, which is not specified in the YAML file but rather in the Python code that constructs the model.

3. **Predicting 8 to 12 corner points:**
   Predicting a variable number of points can be challenging because neural networks typically require a fixed-size output. One approach to handle this is to always predict the maximum number of points (e.g., 12) and use a mask or confidence score to indicate which points are valid. For example, you could predict 12 points for each shape, and for shapes that only have 8 corners, the remaining 4 points could have very low confidence scores or be masked out.

   When annotating your dataset, you would annotate all shapes with 12 points, and for shapes with fewer than 12 corners, you would place the unused points at a specific location (e.g., the origin) and set their confidence to zero. During training, your custom head would learn to predict high confidence for valid points and low confidence for invalid points.

To implement these changes, you would need to dive into the codebase and make significant modifications to the model architecture and possibly the loss functions to handle the prediction of corner points and their confidences. It's a non-trivial task that requires a good understanding of the model's code and possibly some experimentation to get right.

If you're ready to proceed with these modifications and need further assistance, feel free to reach out, and we can discuss the next steps in more detail.

**Comment by Wissiak** [comment]
@glenn-jocher your AI answered the wrong question :(

**Comment by glenn-jocher** [comment]
@Wissiak hello! It's great to see that you're looking to adapt YOLOv8 for your specific use case of detecting cube nets and obtaining corner points for homography. Here are the answers to your questions:

1. **Adaptations for the output**: Yes, modifications to the model's output format are typically made in the head of the model. The head is responsible for producing the final predictions from the features extracted by the backbone and neck of the network.

2. **Starting with `yolov8-obb.yaml`**: The `yolov8-obb.yaml` file is a model configuration file that defines the architecture of the model, including the head that outputs oriented bounding boxes (OBB). The line `[[15, 18, 21], 1, OBB, [nc, 1]]` specifies the layers and the type of prediction head to use. The numbers `[15, 18, 21]` refer to the output feature map layers from the backbone that are used by the head, `1` is the number of detection heads, `OBB` is the type of head, and `[nc, 1]` defines the number of classes and the stride. To adapt this for your own header, you would need to create a custom head that outputs the corner points of each shape. This would involve modifying the model architecture code where the heads are defined and potentially creating a new head class that extends the existing head classes.

3. **Predicting variable corner points**: Predicting a variable number of corner points can be challenging because neural networks typically have a fixed number of outputs. One approach to handle this is to always predict the maximum number of corner points (e.g., 12) and use a confidence score or mask to indicate which points are valid. For example, you could output a 12x2 tensor for the corner points and a 12-dimensional tensor for the validity of each point. During annotation, you would mark unused corner points with low confidence or a mask value of 0.

To implement these changes, you would need to:

- Modify the model architecture to include a custom head that predicts corner points and their validity.
- Update the loss function to handle the variable number of points and to ignore the unused points during training.
- Create a custom dataset with annotations for the corner points of each shape.
- Train the model with the new dataset and evaluate the performance of the corner point predictions.

Keep in mind that this is a non-trivial task that requires a good understanding of the model architecture and the ability to modify and train deep learning models. If you're not familiar with these concepts, it might be helpful to collaborate with someone who has experience in deep learning and computer vision.

Good luck with your project, and if you have further questions or need more detailed guidance, feel free to ask!

**Comment by Wissiak** [comment]
@glenn-jocher The AI is again answering the initial question. Here a copy of my follow-up questions - maybe it gets it right this time.
1. The following code `feats, pred_angle = preds if isinstance(preds[0], list) else preds[1]` sets pred_angle to a tensor of size `(16, 8400, 12)` and feats is an array of 3 tensors `[(16,75,80,80),(16,75,40,40),(16,75,20,20)]`. What are these values? I guess feats contains the image information, right?
2. What are the values of pred_distri `(16,8400,64)` and pred_scores `(16,8400,11)` from the following code?:
``` 
pred_distri, pred_scores = torch.cat([xi.view(feats[0].shape[0], self.no, -1) for xi in feats], 2).split(
       (self.reg_max * 4, self.nc), 1
  )
```
3. Do you agree that the loss for corner points should be relatively simple? E.g. Euclidean distance between predicted corners and true corners.
4. How can I obtain the true predicted corner points from the model output? Do I have to involve non maximum suppression already?

**Comment by glenn-jocher** [comment]
@Wissiak hello! It's great to see you're interested in adapting YOLOv8 for your specific use case of detecting cube nets and obtaining corner points for homography. Here's how you can approach this task:

1. **Adaptations for the Output:**
   Yes, modifications to the output format are typically done in the head of the model. The head is responsible for interpreting the features extracted by the backbone and neck of the model and converting them into the desired output format, such as bounding boxes, corner points, etc.

2. **Using `yolov8-obb.yaml`:**
   The line `[[15, 18, 21], 1, OBB, [nc, 1]]` in `yolov8-obb.yaml` refers to the configuration of the head for Oriented Bounding Box (OBB) detection. The numbers `[15, 18, 21]` refer to the output feature map layers from the backbone that are used by the head. The `OBB` indicates the type of head being used, and `[nc, 1]` specifies the number of classes (`nc`) and the number of anchors per location (`1`).

   To adapt this for your own header, you would need to create a custom head that outputs the corner points of each shape. This would involve modifying the model architecture code where the head is defined and potentially creating a new head class that inherits from the base head class but overrides the forward method to produce the desired output format.

3. **Predicting Variable Corner Points:**
   Predicting a variable number of corner points (8 to 12) can be challenging because neural networks typically require a fixed-size output. One approach to handle this is to always predict the maximum number of points (e.g., 12) and use a mask or confidence score to indicate which points are valid. For example, you could have an additional channel in the output that provides a binary mask indicating the presence of a corner point.

   When annotating your dataset, you would annotate all shapes with 12 points, and for shapes with fewer than 12 corners, you would set the unused points to a specific value (e.g., outside the image boundaries) and the corresponding mask value to 0.

To implement these changes, you would need to:

- Modify the model architecture code to include your custom head.
- Update the loss function to handle the variable number of corner points and the mask.
- Prepare a dataset with the appropriate annotations for training.
- Train the model with your custom head and loss function.

Keep in mind that this is a non-trivial task that requires a good understanding of the model architecture and the ability to implement custom layers and loss functions. If you're not familiar with these concepts, it might be helpful to collaborate with someone who has experience in deep learning and PyTorch.

Good luck with your project, and if you have any more questions or need further assistance, feel free to ask!

**Comment by Wissiak** [comment]
@glenn-jocher And again the same issue... I could really use some serious help!

**Comment by glenn-jocher** [comment]
@Wissiak detecting cube nets and extracting corner points for homography is an interesting application of object detection models. Here's how you can approach adapting YOLOv8 for this task:

1. **Adaptations for the Output:**
   Yes, you are correct. Modifications for custom output formats are typically done in the head of the model, where the final layer predictions are formatted into the desired output structure.

2. **Using `yolov8-obb.yaml`:**
   The `yolov8-obb.yaml` file is a model configuration file that defines the architecture of the model, including the head that outputs oriented bounding boxes (OBB). The line `[[15, 18, 21], 1, OBB, [nc, 1]]` specifies the layers used for prediction, the stride, the type of prediction (OBB), and the number of classes (`nc`) and other parameters.

   To adapt this for your use case, you would need to create a custom head that outputs the corner points of each shape. This would involve modifying the model architecture in the configuration file and potentially the code that processes the model's output.

   The files referred to in the configuration are part of the model's architecture, defined in the codebase. You would need to look into the source code where the model layers are defined and implement your custom head there.

3. **Predicting Variable Corner Points:**
   Predicting a variable number of corner points can be challenging because most object detection models expect a fixed-size output. One approach to handle this is to always predict the maximum number of points (e.g., 12) and use a mask or confidence score to indicate which points are valid. For example, you could have an additional channel in the output that provides a binary mask for the presence of each corner point.

   When annotating your dataset, you would annotate all shapes with 12 points, setting unused points to a specific value (e.g., outside the image boundaries) and using the mask to indicate which points are actually used.

To implement these changes, you would need to:

- Modify the model configuration file to define your custom head.
- Update the model architecture in the source code to include your custom head.
- Adapt the loss function to handle the variable number of points and the mask.
- Prepare a custom dataset with annotations for the corner points and masks.
- Train the model with the new dataset and evaluate its performance.

This is a non-trivial task that requires a good understanding of the model architecture and the ability to modify and train deep learning models. If you're not familiar with these concepts, it might be helpful to collaborate with someone who has experience in deep learning and computer vision.

**Comment by Wissiak** [comment]
Okay, I'll just use this issue for documentation. Maybe it helps somebody else or maybe someone will help me 🤗 

From [the YOLOv8 architecture](https://viso.ai/wp-content/uploads/2023/12/YOLOv8-Architecture-Structure-1012x1060.jpg) I found out that the values `[(16,75,80,80),(16,75,40,40),(16,75,20,20)]` contain the image information after different amount of Convolutions applied and therefore detect objects of different sizes (see in the architecture: `(16,75,80,80)`=P3=large sized, `(16,75,40,40)`=P4=medium sized, `(16,75,20,20)`=P5=small sized). 
These values are also related to the model configuration in the yaml file where `[15, 18, 21]` reference the respective input layers where 15=P3, 18=P4 and 21=P5. 

But I'm still trying to find out how I can get my predicted corners of shape `batch_size, 24, 8400` to a format where I can calculate something like `loss = F.mse_loss(pred_corners, true_corners)`. Note that the number 24 corresponds to the 12 corner points with x/y coordinates respectively. 

I'm also not quite sure if I need confidence scores... I'm generating my dataset whereas the confidence score will be 1 every time... so I think this would be kind of useless...

**Comment by glenn-jocher** [comment]
@Wissiak hey there! 😊 It's awesome that you're diving into the YOLOv8 architecture and making progress on your project.

You're on the right track with the feature map sizes (`P3`, `P4`, `P5`) corresponding to different object sizes. To calculate the loss between your predicted corners and the ground truth, you'll want to reshape your predictions to match the ground truth format. If your `true_corners` are in the shape of `batch_size, 24, num_objects`, you'll need to ensure `pred_corners` matches this shape.

Here's a quick example of how you might reshape and calculate the loss:

```python
# Assuming pred_corners is the raw output from your model
pred_corners = pred_corners.view(batch_size, 24, -1)  # Reshape to match true_corners

# Calculate MSE loss
loss = F.mse_loss(pred_corners, true_corners)
```

Regarding confidence scores, if every corner point in your dataset is labeled with confidence 1, then you might not need an additional confidence output from your model. However, if you plan to deal with occlusions or varying levels of annotation certainty in the future, incorporating confidence scores could be beneficial.

Keep up the great work, and don't hesitate to reach out if you have more questions! 🚀

**Comment by Wissiak** [comment]
I am currently at the state where I calculate the loss as absolute difference between the ground truth corners and the predicted corners and sum it up over all predictions which leaves me with 24 differences. I am adding these 24 differences to the loss tensor which is being returned at the end of the loss function. I am now wondering whether the model is being optimized automatically on all the returned values from the loss function or is there some kind of other behavior for the optimization variables?

**Comment by glenn-jocher** [comment]
@Wissiak hey there! 😊 It sounds like you're making great progress with your model. When you sum up the absolute differences between the ground truth and predicted corners to calculate the loss, the model's optimization process will indeed work to minimize this loss value during training. The optimizer updates the model weights based on the gradient of this loss.

Here's a quick example to illustrate:

```python
loss = torch.sum(torch.abs(true_corners - pred_corners))  # Sum of absolute differences
optimizer.zero_grad()  # Clear existing gradients
loss.backward()  # Compute gradient of the loss w.r.t. model parameters
optimizer.step()  # Update model parameters
```

This means the model is being optimized to minimize the total loss, which in your case is the sum of the 24 absolute differences. Keep up the great work, and feel free to reach out if you have more questions! 🚀

**Comment by Wissiak** [comment]
I am still not sure how I should handle the corner predictions. I started from the OBB example with 24 extra parameters (ne=24). In the head the underneath code returns the number of extra parameters (which resembles the angle of rotation for the OBB example):
```
nn.ModuleList(nn.Sequential(Conv(x, c4, 3), Conv(c4, c4, 3), nn.Conv2d(c4, self.ne, 1)) for x in ch)
```
In the forward step of the head, the predictions for the channels get concatenated which results in 8400 predictions for the extra parameters corresponding to the predictions for the oriented bounding boxes. 

In my case of ne=24, I get a shape of (batch_size, 8400, 24) for the predictions. The ground truth corners are of shape (n, 24) where n is the number of found objects in the current batch. My problem is that I'm not sure how to calculate the loss between the predictions (batch_size, 8400, 24) and the ground truth (n, 24)...

### Idea 1
Currently, I am taking the ground truth corners in a similar way how the NMS selected bboxes are taken. Firstly, I am preprocessing the ground truth corners (target_corners) to shape (batch_size, max_count, 24):
```
    def preprocess_corners(self, target_cls, targets, batch_size):
        if targets.shape[0] == 0:
            out = torch.zeros(batch_size, 0, 24, device=self.device)
        else:
            i = target_cls  # image index
            _, counts = i.unique(return_counts=True)
            counts = counts.to(dtype=torch.int32)
            out = torch.zeros(batch_size, counts.max(), 24, device=self.device)
            for j in range(batch_size):
                matches = i == j
                n = matches.sum()
                if n:
                    out[j, :n] = targets[matches]
        return out
```
Then I try to select the same indices as the NMS processed bboxes in the TaskAlignedAssigner:
```
batch_ind = torch.arange(end=batch_size, dtype=torch.int64, device=target_bboxes.device)[..., None]
target_gt_idx = target_gt_idx + batch_ind * gt_bboxes.shape[1]  # (b, h*w)
gt_corners = target_corners.view(-1, target_corners.shape[-1])[target_gt_idx]
```
But this leaves me with a `gt_corners` that contains a lot of 0 tensors since the preprocessed corners have 0 tensors everywhere except for the class where max_count corners were found.

### Idea 2
Another idea I had was to adapt the head directly in order to output corner predictions of the shape (batch_size, 24):
```
self.cv4 = nn.ModuleList(nn.Sequential(nn.AdaptiveAvgPool2d(1), nn.Flatten(), nn.Linear(x, self.ne)) for x in ch)
```
Firstly, this would only work if there is at most 1 set of 12 corners per image. Also, I get corner predictions for each channel which leaves me with a prediction shape of (16, n_channels, 24) and now again I am not sure how to design the loss function since the ground truth corners are of shape (16, 24).

**Question**
Does anybody have suggestions/ideas on how I could implement the loss function and head implementation so that the corners can be detected successfully?

**Comment by glenn-jocher** [comment]
@Wissiak hey there! 😊 It looks like you're diving deep into customizing YOLOv8 for corner detection, which is pretty exciting! Let's tackle your question on handling the loss calculation between your predicted corners and the ground truth.

Given the mismatch in shapes between your predictions `(batch_size, 8400, 24)` and ground truth `(n, 24)`, here's a suggestion that might help streamline your process:

### Suggested Approach

Consider reshaping or processing your predictions to align with the ground truth format before calculating the loss. One way to do this is by using a detection or assignment mechanism that maps each of the 8400 predictions to the closest ground truth corner set based on some criteria (e.g., IoU for bounding boxes containing these corners, or a direct distance metric for the corners).

Once you've aligned the predictions with the ground truth, you can calculate the loss more directly. For instance, if you manage to reduce your predictions to a shape that matches the ground truth `(n, 24)`, you could then compute the loss as:

```python
loss = F.mse_loss(pred_corners_aligned, true_corners)
```

Where `pred_corners_aligned` is the result of your alignment process, ensuring it matches the ground truth shape `(n, 24)`.

### Regarding Your Ideas

- **Idea 1** seems promising but might require refining the selection process to avoid the issue with 0 tensors. Consider filtering out these 0 tensors before loss calculation or using a masking technique to ignore them in your loss function.
  
- **Idea 2** might be too restrictive due to its assumption of at most one set of corners per image. It also complicates the loss calculation due to the mismatch in dimensions.

### Additional Tip

For the loss function, besides considering the direct MSE loss, you might also want to incorporate a mechanism to dynamically weigh the importance of each corner point based on its visibility or confidence, if such information is available or can be inferred.

I hope this gives you a good starting point! Keep experimenting, and don't hesitate to reach out if you have more questions. Good luck with your project! 🚀

**Comment by Wissiak** [comment]
Okay I found my error of aligning the corners to the bboxes so there are no zero tensors anymore. But the problem I now have is that the model does not optimize on the 24 corner losses that I return from the loss function. I also use `box_loss`, `cls_loss and `dfl_loss` as in the normal detection mode. I see that the model optimizes these losses but the corner losses increase. I tested the model by removing the `box_loss`, `cls_loss and `dfl_loss` and now the model optimizes on the first 3 corner losses... It seems to me that exactly the first 3 loss items are being optimized...

Do I need to specify somewhere how many loss items should be optimized?

**Comment by glenn-jocher** [comment]
@Wissiak hey there! 🌟 It sounds like you've made some great progress in aligning the corners to the bounding boxes. Regarding the optimization issue with the corner losses, it seems like the model might be prioritizing the `box_loss`, `cls_loss`, and `dfl_loss` over the corner losses when all are included.

One approach to ensure that all losses are optimized effectively is to combine them into a single loss value before passing it to the optimizer. This can be done by weighting each loss according to its importance or impact on the model's performance. Here's a quick example:

```python
# Assuming box_loss, cls_loss, dfl_loss, and corner_loss are already calculated
total_loss = box_loss + cls_loss + dfl_loss + corner_loss_weight * corner_loss
```

In this example, `corner_loss_weight` is a hyperparameter that you can adjust to ensure the corner losses are given enough importance during optimization. You might need to experiment with different weights to find the balance that works best for your model.

Regarding your observation that only the first 3 corner losses decrease, it could be related to how the losses are aggregated or the learning dynamics when all losses are considered. Ensuring that the corner losses are appropriately weighted and combined into the total loss should help in optimizing them alongside the other losses.

Keep up the great work, and feel free to share any further updates or questions you might have! 🚀

**Comment by Wissiak** [comment]
Okay so I tried it out with a single corner loss but again, no optimization on the corner loss. Afterwards I tried by using only the corner loss without bbox loss, etc. And the result was the following error: 
```
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```
So I guess this is what's missing, right? No gradient on the corner loss so it is not being optimized on? I calculate the loss as following:
```
torch.sum(torch.abs((gt_corners[fg_mask] - pred_corners[fg_mask]) * weight))
```
How can I require the gradient on this loss value?

**Comment by glenn-jocher** [comment]
@Wissiak hey there! 😊 It looks like you're on the right track with your debugging. The error you're encountering typically indicates that the operation leading to your loss calculation isn't part of the computational graph that PyTorch uses to compute gradients. This can happen if any of the tensors involved in calculating the loss were detached from the graph or were created without requiring gradients.

In your loss calculation:
```python
torch.sum(torch.abs((gt_corners[fg_mask] - pred_corners[fg_mask]) * weight))
```
Ensure that `pred_corners` is directly coming from your model's output without any operations that might detach it from the computational graph. Also, `weight` should be a tensor that either has `requires_grad=True` or is a constant tensor that doesn't need gradients.

If `weight` is a learnable parameter, make sure it's defined correctly, for example:
```python
weight = torch.tensor(your_initial_weight_value, requires_grad=True, device="cuda" or "cpu")
```
Or if it's part of a model's parameters, ensure it's properly registered.

If `pred_corners` and `weight` are correctly set up and you're still facing issues, double-check that `pred_corners` is indeed part of the model's forward pass and hasn't been inadvertently detached.

Keep experimenting, and don't hesitate to reach out if you have more questions! 🚀

**Comment by Wissiak** [comment]
@glenn-jocher Thank you, you were absolutely right! I was detaching the `pred_corners` from the computational graph. If I don't, the loss computation for the corners finally works! 
I will post the results shortly 🤗

**Comment by Wissiak** [comment]
In the linked video you can see the first results from training for 20 epochs on a pretrained extra large model 🥳 I am confident that with longer trianing the corner points will be more precise.
https://github.com/ultralytics/ultralytics/assets/31206249/54c6bf29-2872-44aa-b02b-5ab79676b2e3

I will now try how accurate the results are with the nano model.

**Comment by glenn-jocher** [comment]
@Wissiak That's fantastic news! 🎉 The video showcases promising results, and it's great to hear about your confidence in further refining the corner point precision with extended training. Switching to the nano model for comparison sounds like an excellent plan. Keep us posted on how it goes, and if you encounter any challenges or have more insights to share, we're here to help. Happy experimenting! 🚀

**Comment by Wissiak** [comment]
I am now trying to export the model to tf.js but somewhere the model seems to be messed up by my changes. The error is:

```
ValueError: A KerasTensor cannot be used as input to a TensorFlow function. A KerasTensor is a symbolic placeholder for a shape and dtype, used when constructing Keras Functional models or Keras Functions. You can only use it as input to a Keras layer or a Keras operation (from the namespaces `keras.layers` and `keras.operations`). You are likely doing something like:
```
```
x = Input(...)
...
tf_fn(x)  # Invalid.
```
```
What you should do instead is wrap `tf_fn` in a layer:
```
```
class MyLayer(Layer):
    def call(self, x):
        return tf_fn(x)

x = MyLayer()(x)
```
```
ERROR: input_onnx_file_path: /Users/patrick/projects/ultralytics_git/runs/train46/weights/best.onnx
ERROR: onnx_op_name: /model.0/conv/Conv
ERROR: Read this and deal with it. https://github.com/PINTO0309/onnx2tf#parameter-replacement
ERROR: Alternatively, if the input OP has a dynamic dimension, use the -b or -ois option to rewrite it to a static shape and try again.
ERROR: If the input OP of ONNX before conversion is NHWC or an irregular channel arrangement other than NCHW, use the -kt or -kat option.
ERROR: Also, for models that include NonMaxSuppression in the post-processing, try the -onwdt option.
```

I've tried to analyze my changes to find such a call but I do not know where to search for... E.g. how might the call look like or where might it be located? I also don't know which PyTorch tensors are being converted to KerasTensors because passing tensors normally does not harm the export (such as being done in the normal detection model).

Any ideas where I could start fixing this error?

**Comment by Wissiak** [comment]
Okay the problem was that if I used the `tensorflow-macos` installatio  it worked but with the normal `tensorflow` package it didn't.

**Comment by glenn-jocher** [comment]
@Wissiak hey there! 😊 Great to hear you found the root of the issue. It's interesting how the environment can impact the functionality, as seen with the `tensorflow-macos` vs. `tensorflow` packages. This could be useful info for others working in similar setups. If you ever run into any more quirks or need assistance, feel free to reach out. Happy coding!

**Comment by Wissiak** [comment]
Here are the promised results :) It is running pretty fast and the accuracy is great for the medium sized YOLO model :)

https://github.com/ultralytics/ultralytics/assets/31206249/0e15a455-918a-40be-81fc-63384b63851c

**Comment by glenn-jocher** [comment]
@Wissiak Wow, fantastic to hear the medium-sized YOLO model is doing wonders for speed and accuracy! 🚀 Thanks a lot for sharing the results with us. Keep up the amazing work, and don't hesitate to reach out if you need further assistance or have more cool updates to share. Happy detecting! 😊

**Comment by islemgh25** [comment]
Hello @Wissiak , I tried following your repository in order to create a new task that would detect the center of the detected object, but I got this error: 
AttributeError                            Traceback (most recent call last)
File [~/.local/lib/python3.10/site-packages/ultralytics/engine/model.py:804](https://file+.vscode-resource.vscode-cdn.net/home/syw/Desktop/syw_guided_camera/centered/custom-task/ultralytics/~/.local/lib/python3.10/site-packages/ultralytics/engine/model.py:804), in Model._smart_load(self, key)
    [803](https://file+.vscode-resource.vscode-cdn.net/home/syw/Desktop/syw_guided_camera/centered/custom-task/ultralytics/~/.local/lib/python3.10/site-packages/ultralytics/engine/model.py:803) try:
--> [804](https://file+.vscode-resource.vscode-cdn.net/home/syw/Desktop/syw_guided_camera/centered/custom-task/ultralytics/~/.local/lib/python3.10/site-packages/ultralytics/engine/model.py:804)     return self.task_map[self.task][key]
    [805](https://file+.vscode-resource.vscode-cdn.net/home/syw/Desktop/syw_guided_camera/centered/custom-task/ultralytics/~/.local/lib/python3.10/site-packages/ultralytics/engine/model.py:805) except Exception as e:

File [~/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:1688](https://file+.vscode-resource.vscode-cdn.net/home/syw/Desktop/syw_guided_camera/centered/custom-task/ultralytics/~/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:1688), in Module.__getattr__(self, name)
   [1687](https://file+.vscode-resource.vscode-cdn.net/home/syw/Desktop/syw_guided_camera/centered/custom-task/ultralytics/~/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:1687)         return modules[name]
-> [1688](https://file+.vscode-resource.vscode-cdn.net/home/syw/Desktop/syw_guided_camera/centered/custom-task/ultralytics/~/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:1688) raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")

AttributeError: 'YOLO' object has no attribute 'task_map'

The above exception was the direct cause of the following exception:

NotImplementedError                       Traceback (most recent call last)
Cell In[5], [line 1](vscode-notebook-cell:?execution_count=5&line=1)
----> [1](vscode-notebook-cell:?execution_count=5&line=1) model = YOLO('[/home/syw/Desktop/syw_guided_camera/centered/custom-task/ultralytics/cfg/models/v8/yolov8n-center.yaml](https://file+.vscode-resource.vscode-cdn.net/home/syw/Desktop/syw_guided_camera/centered/custom-task/ultralytics/cfg/models/v8/yolov8n-center.yaml)')

File [~/.local/lib/python3.10/site-packages/ultralytics/models/yolo/model.py:23](https://file+.vscode-resource.vscode-cdn.net/home/syw/Desktop/syw_guided_camera/centered/custom-task/ultralytics/~/.local/lib/python3.10/site-packages/ultralytics/models/yolo/model.py:23), in YOLO.__init__(self, model, task, verbose)
     [20](https://file+.vscode-resource.vscode-cdn.net/home/syw/Desktop/syw_guided_camera/centered/custom-task/ultralytics/~/.local/lib/python3.10/site-packages/ultralytics/models/yolo/model.py:20)     self.__dict__ = new_instance.__dict__
     [21](https://file+.vscode-resource.vscode-cdn.net/home/syw/Desktop/syw_guided_camera/centered/custom-task/ultralytics/~/.local/lib/python3.10/site-packages/ultralytics/models/yolo/model.py:21) else:
     [22](https://file+.vscode-resource.vscode-cdn.net/home/syw/Desktop/syw_guided_camera/centered/custom-task/ultralytics/~/.local/lib/python3.10/site-packages/ultralytics/models/yolo/model.py:22)     # Continue with default YOLO initialization
---> [23](https://file+.vscode-resource.vscode-cdn.net/home/syw/Desktop/syw_guided_camera/centered/custom-task/ultralytics/~/.local/lib/python3.10/site-packages/ultralytics/models/yolo/model.py:23)     super().__init__(model=model, task=task, verbose=verbose)
...
--> [808](https://file+.vscode-resource.vscode-cdn.net/home/syw/Desktop/syw_guided_camera/centered/custom-task/ultralytics/~/.local/lib/python3.10/site-packages/ultralytics/engine/model.py:808) raise NotImplementedError(
    [809](https://file+.vscode-resource.vscode-cdn.net/home/syw/Desktop/syw_guided_camera/centered/custom-task/ultralytics/~/.local/lib/python3.10/site-packages/ultralytics/engine/model.py:809)     emojis(f"WARNING ⚠️ '{name}' model does not support '{mode}' mode for '{self.task}' task yet.")
    [810](https://file+.vscode-resource.vscode-cdn.net/home/syw/Desktop/syw_guided_camera/centered/custom-task/ultralytics/~/.local/lib/python3.10/site-packages/ultralytics/engine/model.py:810) ) from e

NotImplementedError: WARNING ⚠️ 'YOLO' model does not support '_new' mode for 'center' task yet.
Can you help me if you also encountered this

**Comment by Wissiak** [comment]
Hmm I don't know how I could help you with this error... You can have a look at my fork of the ultralytics repository and maybe it helps which files to adapt.
