### ISSUE TITLE
How to use the ModelEMA class with yolov8

### ISSUE THREAD

**Issue by ghost** [ultralytics/ultralytics#8189]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I am experimenting with using yolov8 in a semi-supervised setting and am having some issues getting started. I am attempting to wrap the model with the `ModelEMA` class provided by ultralytics:

```
self.model = YOLO('yolov8n.pt')  
self.ema = ModelEMA(self.model) 
```
I have tried debugging, and if I'm being honest I don't quite understand the behavior. After instantiating the class, the model trains for the default 100 epochs, at which point the self.ema.parameters() appear just fine in the debug console, but then it goes into val() model, and this loop in ModelEMA.__init__() runs again.

```
    def __init__(self, model, decay=0.9999, tau=2000, updates=0):
        """Create EMA."""
        self.ema = deepcopy(de_parallel(model)).eval()  # FP32 EMA
        self.updates = updates  # number of EMA updates
        self.decay = lambda x: decay * (1 - math.exp(-x / tau))  # decay exponential ramp (to help early epochs)
        for p in self.ema.parameters():
            p.requires_grad_(False)
        self.enabled = True
```

at which point I get this error:

`AttributeError: 'DetMetrics' object has no attribute 'parameters'. See valid attributes below.`

So my question is, is it possible to use this EMA class for yolov8? All I have found in other discussions pertains to yolov5. If so, is the cause the difference in architectures of the two detectors (i.e., the anchor free mechanism in v8)? If it is not possible, what is the workaround I can use?

**Comment by glenn-jocher** [comment]
@ronj-c hello! It's great to see you're experimenting with YOLOv8 in a semi-supervised setting. The `ModelEMA` class is indeed compatible with YOLOv8, and it looks like you're on the right track with your implementation. 

The error you're encountering seems to be related to the `DetMetrics` object, which should not be passed to `ModelEMA`. Instead, ensure that you're passing the actual model object that contains the parameters. Here's a quick example of how you might use `ModelEMA` with YOLOv8:

```python
from ultralytics import YOLO, ModelEMA

# Load the YOLOv8 model
model = YOLO('yolov8n.pt')

# Initialize ModelEMA with the YOLOv8 model
ema = ModelEMA(model)

# Now you can use ema.ema for inference or further training
```

Make sure that when you're calling `val()`, you're using the underlying EMA model (`ema.ema`) if you want to validate the EMA parameters. The `ModelEMA` object itself is just a wrapper and does not have `.parameters()`.

If you continue to face issues, please provide a bit more context or code snippets, and I'll be happy to help you debug further. Keep up the good work! 😊👍

**Comment by ronj-c** [comment]
@glenn-jocher thank you for your response. So I am not explicitly calling `val()` or even `train()`. This just seems to occur in the first line of the `__init__()` of `ModelEMA`. The `ModelEMA` wrapper is being used in the same way as you suggested (the only difference being that they are class objects in my approach).

```
from ultralytics import YOLO
from ultralytics.utils.torch_utils ModelEMA

self.model = YOLO('yolov8n.pt')  
self.ema = ModelEMA(self.model) 
```

```
class ModelEMA:
    """Updated Exponential Moving Average (EMA) from https://github.com/rwightman/pytorch-image-models
    Keeps a moving average of everything in the model state_dict (parameters and buffers)
    For EMA details see https://www.tensorflow.org/api_docs/python/tf/train/ExponentialMovingAverage
    To disable EMA set the `enabled` attribute to `False`.
    """

    def __init__(self, model, decay=0.9999, tau=2000, updates=0):
        """Create EMA."""
        self.ema = deepcopy(de_parallel(model)).eval()  # FP32 EMA
        self.updates = updates  # number of EMA updates
        self.decay = lambda x: decay * (1 - math.exp(-x / tau))  # decay exponential ramp (to help early epochs)
        for p in self.ema.parameters():
            p.requires_grad_(False)
        self.enabled = True
```

I believe anytime yolov8 is set to `eval()` it "trains" for 100 epochs, then goes into validation model.
![Screenshot from 2024-02-14 08-43-54](https://github.com/ultralytics/ultralytics/assets/42298486/0e00afdd-2ced-4210-b0fd-495c4c306e4b)

Here is the stack trace
```
File "/home/ron/miniconda3/envs/yolo-teach/lib/python3.10/site-packages/ultralytics/utils/__init__.py", line 156, in __getattr__
    raise AttributeError(f"'{name}' object has no attribute '{attr}'. See valid attributes below.\n{self.__doc__}")
  File "/home/ron/miniconda3/envs/yolo-teach/lib/python3.10/site-packages/ultralytics/utils/torch_utils.py", line 441, in __init__
    for p in self.ema.parameters():
  File "/home/ron/efficientteacher/trainer/v8_trainer.py", line 133, in build_model
    self.ema = ModelEMA(self.model)
  File "/home/ron/efficientteacher/trainer/v8_trainer.py", line 65, in __init__
    self.build_model(cfg, device)
  File "/home/ron/efficientteacher/train.py", line 75, in main
    trainer = V8Trainer(cfg, device, callbacks, LOCAL_RANK, RANK, WORLD_SIZE)
  File "/home/ron/efficientteacher/train.py", line 87, in <module>
    main(opt)
  File "/home/ron/miniconda3/envs/yolo-teach/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ron/miniconda3/envs/yolo-teach/lib/python3.10/runpy.py", line 196, in _run_module_as_main (Current frame)
    return _run_code(code, main_globals, None,
AttributeError: 'DetMetrics' object has no attribute 'parameters'. See valid attributes below.

    This class is a utility class for computing detection metrics such as precision, recall, and mean average precision
    (mAP) of an object detection model.

    Args:
        save_dir (Path): A path to the directory where the output plots will be saved. Defaults to current directory.
        plot (bool): A flag that indicates whether to plot precision-recall curves for each class. Defaults to False.
        on_plot (func): An optional callback to pass plots path and data when they are rendered. Defaults to None.
        names (tuple of str): A tuple of strings that represents the names of the classes. Defaults to an empty tuple.

    Attributes:
        save_dir (Path): A path to the directory where the output plots will be saved.
        plot (bool): A flag that indicates whether to plot the precision-recall curves for each class.
        on_plot (func): An optional callback to pass plots path and data when they are rendered.
        names (tuple of str): A tuple of strings that represents the names of the classes.
        box (Metric): An instance of the Metric class for storing the results of the detection metrics.
        speed (dict): A dictionary for storing the execution time of different parts of the detection process.

    Methods:
        process(tp, conf, pred_cls, target_cls): Updates the metric results with the latest batch of predictions.
        keys: Returns a list of keys for accessing the computed detection metrics.
        mean_results: Returns a list of mean values for the computed detection metrics.
        class_result(i): Returns a list of values for the computed detection metrics for a specific class.
        maps: Returns a dictionary of mean average precision (mAP) values for different IoU thresholds.
        fitness: Computes the fitness score based on the computed detection metrics.
        ap_class_index: Returns a list of class indices sorted by their average precision (AP) values.
        results_dict: Returns a dictionary that maps detection metric keys to their computed values.
        curves: TODO
        curves_results: TODO
```

**Comment by ronj-c** [comment]
I actually just tried to recreate this in a new environment and think I have figured out the issue. It seems like you should pass `model.model` instead.

```
from ultralytics import YOLO
from ultralytics.utils.torch_utils ModelEMA

model = YOLO('yolov8s.pt')
ema = ModelEMA(model.model)
```

When doing this I now get the expected behavior from the `ModelEMA` class.

**Comment by glenn-jocher** [comment]
@ronj-c the `ModelEMA` class is designed to maintain a moving average of the model parameters, which is typically used during training to stabilize and improve the final model performance. The error you're encountering seems to suggest that the `ModelEMA` class is being applied to an object that does not have parameters, specifically a `DetMetrics` object, which is likely a metrics or results object rather than a model.

To properly use `ModelEMA` with YOLOv8, you should ensure that it is applied to the actual model object that contains trainable parameters. Here's a general approach to using `ModelEMA` with YOLOv8:

1. Initialize your YOLOv8 model.
2. Create an instance of `ModelEMA` with the model as an argument.
3. During training, update the EMA model after each training step.
4. Optionally, use the EMA model for validation or inference.

Here's an example of how you might set up and use `ModelEMA` with YOLOv8:

```python
from ultralytics import YOLO, ModelEMA

# Initialize YOLOv8 model
model = YOLO('yolov8n.pt')

# Create EMA model
decay = 0.9999  # Adjust decay rate as needed
ema = ModelEMA(model, decay=decay)

# Example training loop
for epoch in range(epochs):
    for batch in dataloader:
        # ... perform training step ...
        # Update EMA model after each training step
        ema.update(model)
```

After training, you can use `ema.ema` for validation or inference, as this attribute holds the EMA version of the model:

```python
# Use EMA model for validation or inference
val_results = ema.ema.val(data='coco128.yaml')
```

Please note that the above code is a simplified example. In practice, you would integrate the EMA updates into your actual training loop, where you handle the forward and backward passes, optimizer steps, and other training details.

If you're still encountering issues, please ensure that you're using the latest version of the Ultralytics YOLOv8 repository, as the API and features may have been updated since the last release. Additionally, consider reaching out to the Ultralytics team through their GitHub issues or discussions for more specific guidance on using `ModelEMA` with YOLOv8.

**Comment by ronj-c** [comment]
I get that `DetMetrics` is not an object that has learnable parameters. What I didn't understand was why it was being implicitly called in the first place. Though I "believe" I have solved the issue, I ask if you could please run these two lines in your system. You will see exactly what I mean.

```
from ultralytics import YOLO, ModelEMA

# Initialize YOLOv8 model
model = YOLO('yolov8n.pt')

# Create EMA model
ema = ModelEMA(model)
```

**Comment by glenn-jocher** [comment]
@ronj-c the `ModelEMA` class is designed to maintain a moving average of the model parameters during training, which can help stabilize and improve the model's performance. It seems like you are trying to use the `ModelEMA` class correctly by wrapping the YOLOv8 model instance. However, the error you're encountering suggests that there might be an issue with the model object being passed to the `ModelEMA` class.

The error message indicates that at some point, an object of type `DetMetrics` is being passed to `ModelEMA` instead of the actual model with trainable parameters. This could happen if the model object is being replaced or if the `val()` method is modifying the state of the model in a way that is incompatible with `ModelEMA`.

To resolve this issue, you should ensure that the `ModelEMA` class is only wrapping the actual neural network model with parameters, and not any other object. Here's a more detailed example of how you might use `ModelEMA` with YOLOv8:

```python
from ultralytics import YOLO
from ultralytics.utils.ema import ModelEMA

# Load a pretrained YOLOv8 model
model = YOLO('yolov8n.pt')

# Initialize the EMA wrapper
ema = ModelEMA(model)

# Example training loop
for epoch in range(epochs):
    model.train()
    for batch in dataloader:
        # Forward pass
        # ...

        # Backward and optimize
        # ...

        # Update EMA parameters after the optimization step
        ema.update(model)

    # Validate the EMA model
    ema_model = ema.ema
    ema_model.eval()
    with torch.no_grad():
        # Run validation using the EMA model
        # ...
```

In this example, `ema.ema` gives you access to the EMA model, which you can use for validation or inference.

If you continue to encounter issues, please ensure that you are using the latest version of the Ultralytics YOLOv8 repository, as there may have been updates or bug fixes related to the `ModelEMA` class.

Additionally, if you are modifying the training loop or the `val()` method, make sure that the `model` object remains the neural network model throughout the training process and is not inadvertently replaced with a `DetMetrics` object or any other non-model object.
