### ISSUE TITLE
how about yolov8-pose?

### ISSUE THREAD

**Issue by xinsuinizhuan** [ultralytics/ultralytics#819]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

how about yolov8-pose?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by knoppmyth** [comment]
It has been stated that this is something the team would like to do.

**Comment by jorislimonier** [comment]
Looking forward to it. Any progress update @knoppmyth ?

**Comment by jorislimonier** [comment]
Looking forward to it!

**Comment by xinsuinizhuan** [comment]
how to export the yolov8n-pose.pt to onnx？ the comand export now is  not work:
yolo mode=export model=yolov8n-pose.pt format=onnx simplify=True
 the out put is 1x56x8400

**Comment by glenn-jocher** [comment]
@xinsuinizhuan in order to export a YOLOv8n-pose model to ONNX format, you can use the `torch.onnx.export` function, which takes the trained PyTorch model and exports it to the ONNX format specified. However, it is important to note that the format of the input and output tensors may need to be modified to match the expected dimension and ordering in the ONNX format. You may need to reshape the output tensor depending on the number of anchor boxes used in the model. Additionally, you can simplify the ONNX graph using OpenVINO Model Optimizer to reduce complexity and optimize the model for inference.
