### ISSUE TITLE
Issue while loading pre-trained custom models

### ISSUE THREAD

**Issue by vhuard** [ultralytics/ultralytics#8215]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

  File "/content/SmartCity-tracking/SmartCity/Tracking/script_mountAIn_trafficanalysis_Bangkok.py", line 290, in <module>
    processor = VideoProcessor(
  File "/content/SmartCity-tracking/SmartCity/Tracking/script_mountAIn_trafficanalysis_Bangkok.py", line 112, in __init__
    self.model = YOLO(source_weights_path)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 134, in __init__
    self._load(model, task=task)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 215, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py", line 780, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py", line 708, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

### Environment

Ultralytics YOLOv8.1.14 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 26.8/78.2 GB disk)

### Minimal Reproducible Example

The code looks like

def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="XXXXXXX"
    )
    parser.add_argument(
        "--source_weights_path",
        required=True,
        help="Path to the source weights file",
        type=str,

    parser.add_argument(
        "--source_video_path",
        required=True,
        help="Path to the source video file",
        type=str,
    )
    parser.add_argument(
        "--target_video_path",
        required=True,
        help="Path to the target video file (output)",
        type=str,
    )
    parser.add_argument(
        "--confidence_threshold",
        default=0.3,
        help="Confidence threshold for the model",
        type=float,
    )
    parser.add_argument(
        "--iou_threshold",
        default=0.7,
        help="IOU threshold for the model",
        type=float
    )

    return parser.parse_args()

if __name__ == "__main__":
    args = parse_arguments()

    video_info = sv.VideoInfo.from_video_path(video_path=args.source_video_path)
    model = YOLO("source_weigths_path")

If i am using model = YOLO(yolov8x.pt) it is working!!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@vhuard hey there! 👋 It looks like there might be an issue with the custom weights file you're trying to load. The error `_pickle.UnpicklingError: invalid load key, '<'.` typically indicates a problem with the file itself, possibly due to a corrupt download or transfer.

Could you please double-check the `--source_weights_path` argument to ensure it's pointing to the correct file path? Also, verify that the weights file is not corrupted. You might want to try re-downloading or re-exporting the weights if you suspect file corruption.

Here's a quick snippet to ensure you're passing the correct path to the `YOLO` constructor:

```python
if __name__ == "__main__":
    args = parse_arguments()
    video_info = sv.VideoInfo.from_video_path(video_path=args.source_video_path)
    model = YOLO(args.source_weights_path)  # Make sure to use args to pass the correct path
```

Notice that `args.source_weights_path` is used instead of the string `"source_weights_path"`. Give this a try and let us know if it resolves the issue! 🛠️

**Comment by vhuard** [comment]
sorry i just figured out that the file was corrupted for some unknown reasons.
i will figure out the reasons but bug is no longer at ultralytics

thank you for the support

**Comment by glenn-jocher** [comment]
@vhuard it appears that you are encountering an issue while trying to load a custom pre-trained model using the Ultralytics YOLOv8 library. The error message indicates that there is a problem with the pickled object file that you are trying to load (`_pickle.UnpicklingError: invalid load key, '<'`).

This error typically occurs when the file you are trying to load is either corrupted, not a valid `.pt` file, or was saved with a different version of PyTorch than the one you are currently using.

Here are a few steps you can take to troubleshoot and resolve this issue:

1. **Check the File Path**: Ensure that the path to the weights file is correct and that the file exists at that location. It seems you are passing a string `"source_weigths_path"` instead of the variable `args.source_weights_path`. This should be corrected as follows:

```python
model = YOLO(args.source_weights_path)
```

2. **Verify File Integrity**: Make sure that the weights file is not corrupted. You can try re-downloading the file if it was obtained from an external source.

3. **PyTorch Version**: Check if the file was saved with a different version of PyTorch. If so, try to load it with the same version it was saved with.

4. **File Format**: Confirm that the file is indeed a PyTorch `.pt` file and not some other format.

5. **Inspect the File**: You can try opening the file with a text editor to see if it starts with strange characters. A valid PyTorch `.pt` file should start with `PK` if it's a zip file (for newer PyTorch versions) or something that is not human-readable for older versions.

6. **Model Compatibility**: Ensure that the custom model architecture is compatible with the YOLOv8 library. If the model was trained with a different library or a significantly different version of YOLO, it might not be compatible.

If you have verified all the above points and the issue still persists, you might want to consider re-training the model with the current version of the Ultralytics YOLOv8 library you are using, or reach out to the maintainers of the library with a detailed bug report including the steps to reproduce the issue and any relevant files.
