### ISSUE TITLE
How can I use self.model = RTDETR("rtdetr-l.pt") for my own custom model for model inference?

### ISSUE THREAD

**Issue by MathewWalter** [ultralytics/ultralytics#8223]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

> RTDETR class

When training on my own custom dataset it returns two files "config.JSON" and "model.safetensors". 

How can I use self.model = RTDETR("rtdetr-l.pt") for my own custom model for model inference?

### Additional

Using the commands "model.model.save_pretrained(MODEL_PATH)" to save the model.

Using the commands below to try load the custom model? 

        self.model = RTDETR("model.safetensors")  # Placeholder for actual model loading self.model = RTDETR("rtdetr-l.pt")
        self.CLASS_NAMES_DICT = class_names  # Assuming 'class_names' is defined elsewhere
        print("classes:", self.CLASS_NAMES_DICT)

**Comment by glenn-jocher** [comment]
@MathewWalter hello! To use your custom trained RTDETR model for inference, you'll need to load the model using the `RTDETR` class and the path to your saved model files. Here's a quick example of how you can do it:

```python
from ultralytics import RTDETR

# Load your custom trained RTDETR model
model_path = "path/to/your/model_directory"  # Replace with your model directory path
self.model = RTDETR(model_path)

# Load your class names
self.CLASS_NAMES_DICT = class_names  # Make sure 'class_names' contains your dataset's class names

# Now you can use self.model for inference
print("Model loaded successfully with classes:", self.CLASS_NAMES_DICT)
```

Make sure to replace `"path/to/your/model_directory"` with the actual path where your `config.JSON` and `model.safetensors` files are located. The `RTDETR` class will handle the loading of these files for you. Happy inferencing! 😊🚀

**Comment by MathewWalter** [comment]
Hi @glenn-jocher . Thank you for your answer. I've tried to implement this however I get the following error: 

`NotImplementedError: RT-DETR only supports creating from *.pt, *.yaml, or *.yml files.`

It seems it won't accept the model directory which contains the two files "config.JSON" and "model.safetensors", but instead wants it in some ".pt" format but "model.model.save_pretrained(MODEL_PATH)" does not save in a ".pt" format. Please let me know if you have any other suggestions I could try.

**Comment by glenn-jocher** [comment]
@MathewWalter to use your custom trained RT-DETR model for inference, you need to load the model with the appropriate weights and configuration. Since you mentioned that the training process returns two files, `config.JSON` and `model.safetensors`, you will need to use these files to load the model.

The `RTDETR` class in Ultralytics YOLOv8 is designed to load pretrained models with a `.pt` extension, which typically contain both the model weights and the configuration. However, in your case, you have separate files for the configuration and the weights.

Here's how you can proceed to load your custom model for inference:

1. Ensure that you have the `RTDETR` class available in your environment. This class should provide a method to load the model from custom weights and configuration.

2. Use the `config.JSON` file to load the model configuration. This file should contain the necessary information to recreate the model architecture.

3. Use the `model.safetensors` file to load the model weights. This file should contain the trained weights for your model.

The exact code to load the model will depend on the implementation of the `RTDETR` class and how it handles custom weights and configurations. If the `RTDETR` class does not provide a straightforward way to load from separate configuration and weights files, you may need to modify the class or write a custom function to handle this.

Here's a hypothetical example of how the code might look, assuming that the `RTDETR` class has methods `from_config` and `load_weights`:

```python
from ultralytics import RTDETR

# Load the model configuration from the JSON file
config_path = "path/to/config.JSON"
model = RTDETR.from_config(config_path)

# Load the model weights from the safetensors file
weights_path = "path/to/model.safetensors"
model.load_weights(weights_path)

# Now the model is ready for inference
self.model = model
self.CLASS_NAMES_DICT = class_names  # Assuming 'class_names' is defined elsewhere
print("classes:", self.CLASS_NAMES_DICT)
```

Please note that the above code is just an example and may not work as-is. You will need to refer to the actual implementation of the `RTDETR` class or the documentation provided by Ultralytics for the correct methods to load the model from custom files.

If you are unable to find the appropriate methods or face any issues, I recommend reaching out to the Ultralytics team through their GitHub issues or discussions for further assistance. They may provide you with the correct procedure or code snippet to load your custom trained RT-DETR model for inference.

**Comment by glenn-jocher** [comment]
@MathewWalter hi there! It looks like the RT-DETR class is expecting a different file format. Instead of using `model.model.save_pretrained(MODEL_PATH)`, try saving your model in the `.pt` format directly after training. Here's a quick example of how you might do this:

```python
# Assuming 'model' is your trained RTDETR model
torch.save(model.state_dict(), 'model.pt')
```

Then, you can load your model using:

```python
self.model = RTDETR('model.pt')
```

Give this a shot and let me know if it helps! 😊👍

**Comment by MathewWalter** [comment]
Hi @glenn-jocher . Unfortunately, the proposed solution was not successful for me when it came to loading back in the .pt file with the RTDETR class. 
  ```
    self.model = RTDETR("my_model.pt")  # Placeholder for actual model loading

  File ~\anaconda3\envs\transformers\Lib\site-packages\ultralytics\models\rtdetr\model.py:39 in __init__
    super().__init__(model=model, task="detect")

  File ~\anaconda3\envs\transformers\Lib\site-packages\ultralytics\engine\model.py:134 in __init__
    self._load(model, task=task)

  File ~\anaconda3\envs\transformers\Lib\site-packages\ultralytics\engine\model.py:215 in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)

  File ~\anaconda3\envs\transformers\Lib\site-packages\ultralytics\nn\tasks.py:711 in attempt_load_one_weight
    model = (ckpt.get("ema") or ckpt["model"]).to(device).float()  # FP32 model

KeyError: 'model'
```

However, using the method below worked:

`from transformers import DetrForObjectDetection, DetrImageProcessor
model = DetrForObjectDetection.from_pretrained('my_model_folder_name') #this folder contains the config.json and .tensorsafe files`

Remembering to process the image using:

`image_processor = DetrImageProcessor.from_pretrained('facebook/detr-resnet-50')`

Therefore I'll close this log. Thank you for all the help.

**Comment by glenn-jocher** [comment]
@MathewWalter hi there! I'm glad to hear you found a solution that works for you using the `transformers` library. It's great that you're able to load your model and process images successfully now. If you have any more questions or need further assistance in the future, feel free to reach out. Happy coding! 😊👨‍💻
