### ISSUE TITLE
TorchScript: export failure

### ISSUE THREAD

**Issue by oolown** [ultralytics/ultralytics#825]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

this is the code to export TorchScript model :
`from ultralytics import YOLO`
`model = YOLO("weights/yolov8n.pt")`
`success = model.export(format="TorchScript")`

then ,i got this:
`TorchScript: export failure  1.6s: Inplace update to inference tensor outside InferenceMode is not allowed.You can make a clone to get a normal tensor before doing inplace update.See https://github.com/pytorch/rfcs/pull/17 for more details.`

**Comment by huanhuan-xiao** [comment]
I got the same error. Could you solve this  


> ### Search before asking
> 
>     * [x]  I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.
> 
> 
> ### Question
> 
> this is the code to export TorchScript model : `from ultralytics import YOLO` `model = YOLO("weights/yolov8n.pt")` `success = model.export(format="TorchScript")`
> 
> then ,i got this: `TorchScript: export failure 1.6s: Inplace update to inference tensor outside InferenceMode is not allowed.You can make a clone to get a normal tensor before doing inplace update.See https://github.com/pytorch/rfcs/pull/17 for more details.`
> ### Additional
> 
> _No response_

![2023-03-21 11-33-04屏幕截图](https://user-images.githubusercontent.com/82137867/226511780-c488f877-af0b-4028-aead-f4b6e7edfb1e.png)

**Comment by oolown** [comment]
I have solved this problem. I encountered this export problem under pytorch1.9.0. The reason is that @smart_inference_mode() in the code does not support pytorch1.9.0. When I replace all @smart_inference_mode() in the project code with @ torch.no_grad(), the model can be successfully exported under pytorch1.9.0. Hope my solution can help you.

**Comment by huanhuan-xiao** [comment]
Thank you very much for your reply. I upgraded the torch to 1.10 this morning. Now it can train normally.



---- Replied Message ----
| From | ***@***.***> |
| Date | 03/22/2023 09:31 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [ultralytics/ultralytics] TorchScript: export failure (Issue #825) |

I have solved this problem. I encountered this export problem under pytorch1.9.0. The reason is that @smart_inference_mode() in the code does not support pytorch1.9.0. When I replace all @smart_inference_mode() in the project code with @ torch.no_grad(), the model can be successfully exported under pytorch1.9.0. Hope my solution can help you.
