### ISSUE TITLE
Training and validation appear to be different sizes

### ISSUE THREAD

**Issue by 25benjaminli** [ultralytics/ultralytics#8268]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Attached is a picture where you can clearly see that the number of images in the training and validation stages are different, however, the training logs seem to indicate they are the same size (under batch size of four). Not sure why this is happening - I checked the directories where the images are being stored and there aren't any problems. Do the training and validation stages have different batch sizes? I feel as though I am missing something very obvious. 

![image](https://github.com/ultralytics/ultralytics/assets/76795078/0c72ecef-7e61-42d3-b329-1a35c02176ae)

Thanks for the help!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@25benjaminli hello! 👋 It looks like you're observing a discrepancy in the number of images reported during training and validation. This could be due to the way batches are formed. Even if the total number of images in your training and validation sets are different, the logs may show the same number of steps per epoch if the batch size is constant because the number of steps is calculated by dividing the total number of images by the batch size.

For example, if you have 400 training images and 100 validation images with a batch size of 4, you would have 100 steps for training and 25 steps for validation. However, if the last batch is not complete (i.e., there are fewer images than the batch size), it might still process as a full batch in the logs, which could cause confusion.

If you want to double-check the actual counts, you could add a print statement in your dataset loader to output the number of images it's loading for training and validation. Here's a quick example:

```python
print(f"Training images loaded: {len(train_dataset)}")
print(f"Validation images loaded: {len(val_dataset)}")
```

If everything seems correct with your dataset and you're still facing issues, please provide more details or a minimal reproducible example, and we'll be happy to take a closer look! 😊

**Comment by 25benjaminli** [comment]
@glenn-jocher thank you for the explanation.

**Comment by 25benjaminli** [comment]
I closed this just now but was curious as to whether there is a way to change this in the model config.
