### ISSUE TITLE
sub 5ms inference on yolov8 Jetson orin nano

### ISSUE THREAD

**Issue by IamShubhamGupto** [ultralytics/ultralytics#8280]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am running a fine-tuned yolov8 on a  jetson orin nano inside a docker container. Currently with tensorrt `imgsz 480,640` `half` `simplify` and `dynamic` flags enabled for the engine creation and  `half` ` show` flags during prediction, I achieve an inference speed of 7.5ms on the jetson orin nano when streamed from a mp4 file. 

I am yet to test inference from a live video (480x640x60) but I assume the performance will be the same if not slower. How I can further minimize the inference latency to 3-4ms? 

### Additional

The goal is to be able to run yolov8 inference on the jetson orin nano at 60fps realsense RGB input

**Comment by glenn-jocher** [comment]
@IamShubhamGupto hi there! 👋 Achieving sub-5ms inference times on a Jetson Orin Nano can be challenging due to hardware limitations, but here are a few suggestions that might help you get closer to your target:

1. **Model Pruning**: Prune the model to reduce complexity while maintaining accuracy. This can be done using techniques like channel pruning.

2. **Model Quantization**: Further quantize the model to INT8 if you haven't already, which can offer speed improvements at the cost of some precision.

3. **Optimize Input Pipeline**: Ensure the input pipeline is optimized. Reading and preprocessing the video stream can add overhead. Consider using batched inference if applicable.

4. **Dedicated Inference Stream**: For live video, dedicate a stream for inference separate from any visualization tasks to avoid GPU contention.

5. **Kernel Optimization**: Look into CUDA kernel optimizations for TensorRT that are specific to the Orin Nano's architecture.

6. **Overclocking**: If thermal and stability constraints allow, overclocking the Jetson Orin Nano could provide a speed boost.

7. **Review TensorRT Best Practices**: NVIDIA's [TensorRT Best Practices](https://docs.nvidia.com/deeplearning/tensorrt/best-practices/index.html) guide provides a wealth of information on optimizing inference.

Remember, each change can affect the system differently, so it's important to profile the performance after each adjustment. Good luck with your optimization! 🚀

If you need further assistance, feel free to reach out!

**Comment by IamShubhamGupto** [comment]
Hey @glenn-jocher thanks for the advice, I'll look them. Are any of the above solutions implemented in ultralytics itself? for example what does `dynamic` and `simplify` flags mean when I export to tensorRT? is it advisable to enable these flags? how do they help in terms of performance?


A guide on how to maximize performance using ultraytics and tensorrt would be great

thank you
