### ISSUE TITLE
OpenVINO export version upgrade

### ISSUE THREAD

**Issue by derek-knox** [ultralytics/ultralytics#8281]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

@glenn-jocher Is there any reason (besides time/priority) that [`openvino-dev>=2023.0`](https://github.com/ultralytics/ultralytics/blob/fbed8499da8e499248c401cc5c1648a0a35c5a73/ultralytics/engine/exporter.py#L402) hasn't been updated to the [latest `2023.3`](https://github.com/openvinotoolkit/openvino/releases)?

I ask as many bug fixes and improvements have landed over the past 6mo.

**Comment by glenn-jocher** [comment]
@derek-knox hi there! 👋

The version pin for `openvino-dev>=2023.0` is indeed primarily due to time and prioritization. We aim to ensure compatibility and stability with the versions we support. However, we're always looking to improve and update our dependencies, including OpenVINO.

If you're interested in using the latest `2023.3` version and would like to help, we welcome contributions! You could try updating the version in your local setup and running some tests. If everything works well, feel free to submit a pull request. Here's a quick example of how you might adjust the version in `exporter.py`:

```python
# Change the required OpenVINO version to 2023.3
requirements = ["openvino-dev==2023.3"]
```

And then run your tests to ensure compatibility. If you encounter any issues or have further questions, let us know! We appreciate your input and support in keeping the project up-to-date. 😊
