### ISSUE TITLE
model.tune isn't finishing training

### ISSUE THREAD

**Issue by khalilxg** [ultralytics/ultralytics#8294]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

so the training starts perfectly, after a day or two a sudden exit happen, there's no console output just suddenly the terminal that hundle the training disappear and the terminal exit.

### Environment

ubuntu 24
ultralyticsv8
rtx 4060 16vram
cpu 20 core i7 12th

### Minimal Reproducible Example

so this is the code 
from ultralytics import YOLO

# Define a YOLO model
model = YOLO("/home/ubuntu/Desktop/yolo/yolov8n.pt")

# Run Ray Tune on the model
result_grid = model.tune(data="/home/ubuntu/Desktop/yolo/data.yaml",
                         epochs=400,
                         save=True,
                         use_ray=False)

### Additional

so the from 1st epoch to 2nd epoch is approx 30min.
400*30= 8 dayz
the terminal has been exited after 2 dayz, no log no trace, or i couldnt figure out from where i can get the log

tested on vscode also it exit in after 2 dayz 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@khalilxg hi there! 👋 It seems like you're encountering an unexpected exit during the `model.tune` process. This could be due to a variety of reasons, including system resource limitations or software-related issues.

To help diagnose the problem, could you please check the following:
- Ensure your system has enough free disk space and memory during the training process.
- Monitor the system's temperature to rule out overheating issues.
- Check system logs for any error messages that occurred around the time of the sudden exit. On Ubuntu, you might find relevant logs in `/var/log/syslog`.

If you're running the training in a background process, consider using `nohup` or `tmux` to keep the process running even if the terminal disconnects. For example:

```bash
nohup python -u script.py > training.log &
```

This will redirect the output to `training.log`, which you can inspect later for any errors or messages.

If the issue persists, please provide any additional information or error messages you find, and we'll be happy to help you further. 🛠️
