### ISSUE TITLE
How to clone ultralytics==8.0.86 (do not want to use pip)

### ISSUE THREAD

**Issue by Chetancool** [ultralytics/ultralytics#8325]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How to clone ultralytics==8.0.86 without pip ?

**Comment by Burhan-Q** [comment]
@Chetancool why would you want to use such an old version of the code?

If you _absolutely must_, you can search the commit history to find the corresponding version and the use `git` to clone _that_ specific commit. Using an older version like this may mean that there will be bugs present that were fixed in subsequent versions. It's recommended to use the most recent version of Ultralytics and will be one of the first suggestions when troubleshooting any problems. We can't offer support if you're intentionally using an older version of the code.

**Comment by Chetancool** [comment]
Thank you :)

**Comment by glenn-jocher** [comment]
Hi @Chetancool! 👋

To clone a specific version of Ultralytics YOLOv8, you can use Git to check out the commit that corresponds to the version you're interested in. Here's how you can do it:

1. Clone the repository:
   ```bash
   git clone https://github.com/ultralytics/ultralytics.git
   ```
2. Navigate to the cloned directory:
   ```bash
   cd ultralytics
   ```
3. List tags and find the one that corresponds to the version you want:
   ```bash
   git tag
   ```
4. Check out the tag:
   ```bash
   git checkout tags/<tag_name>
   ```
   Replace `<tag_name>` with the actual tag name for version 8.0.86.

Remember, using older versions might mean missing out on important fixes and features from later releases. If you need any help or have questions about the latest version, we're here to help! 😊

Happy coding!
