### ISSUE TITLE
how to convert json format(polygon for segmentation in Mask R CNN) to txt format(bbox for detection in YOLOv8)?

### ISSUE THREAD

**Issue by YEONCHEOL-HA** [ultralytics/ultralytics#8373]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://github.com/ultralytics/ultralytics/assets/63231666/a5f66115-0419-45fc-9159-22154738994a)

This code is for converting json format(polygon for segmentation in Mask R CNN) to txt format( bbox for detection in YOLOv8). however, Even though some json files have been normalized, values greater than 1 are output.

I just wonder what part of my code is wrong.

Error Example 

Before converting 
"width": 4032, "height": 3024
"polygon": [{"y": 3127.6800000000003, "x": 1365.1200000000001}, {"y": 3893.76, "x": 1474.56}, {"y": 3981.6000000000004, "x": 2610}, {"y": 3427.2000000000003, "x": 2941.2000000000003}, {"y": 2692.8, "x": 2818.8}, {"y": 2476.8, "x": 2199.6}]

After converting 
3 0.5340178571428572 1.0678571428571428 0.3908928571428572 0.4976190476190477

### Additional

![image](https://github.com/ultralytics/ultralytics/assets/63231666/f797b816-444a-40ee-a4a2-c296a029078f)

**Comment by glenn-jocher** [comment]
@YEONCHEOL-HA hi there! 👋 It looks like you're trying to normalize the polygon coordinates for YOLOv8 but are getting values greater than 1. This typically happens if the polygon points are not properly scaled down by the image width and height.

Here's a quick example of how you might correct the normalization:

```python
# Assuming 'polygon' is your list of points and 'width' & 'height' are your image dimensions
normalized_polygon = [{'x': point['x'] / width, 'y': point['y'] / height} for point in polygon]

# Now find min/max x and y to get the bounding box
min_x = min(point['x'] for point in normalized_polygon)
min_y = min(point['y'] for point in normalized_polygon)
max_x = max(point['x'] for point in normalized_polygon)
max_y = max(point['y'] for point in normalized_polygon)

# Calculate YOLO format center x, y, width, and height
center_x = (min_x + max_x) / 2
center_y = (min_y + max_y) / 2
bbox_width = max_x - min_x
bbox_height = max_y - min_y

# Format for YOLO (class_id center_x center_y width height)
yolo_bbox = f"0 {center_x} {center_y} {bbox_width} {bbox_height}"
```

Make sure that your `width` and `height` variables reflect the actual dimensions of the image you're working with. If the values are still greater than 1 after this, it could be that the polygon points are outside the image boundaries. Double-check the source of your polygon data to ensure it's correct.

Hope this helps! Let us know if you have any more questions. 😊
