### ISSUE TITLE
patience is not changed from 50 

### ISSUE THREAD

**Issue by ragahdtareg** [ultralytics/ultralytics#8379]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

I was training the dataset for 300 epoch and set the value of patience =50 which is the default so the training stop at the 51 epoches because no improvement observed in last 50 epochs 
so my question How you can change patience value to 100 in continuous training ? I tried to change it to patinece=300 in the sh.script but it is not reflected in the training. 

 `
engine/trainer: task=detect, mode=train, model=~/Desktop/model/Vo.pt, data=~/home/exported-datasets/dataset.yaml, epochs=300, time=None, patience=50, batch=10, imgsz=640, save=True,`

and this is the train.sh 
```

yolo detect train data=~/home/exported-datasets/dataset.yaml, 
    model=~/Desktop/Vo.pt \
    epochs=300 \
    batch=10 \
    project="project_v4" \
    exist_ok=true \
    device=0 \
    resume=true \
    box=5.0 \
    cls=2 \
    patience=0  # exist_ok=true resume name="expr"
```

### Environment

Ultralytics YOLOv8.1.17 🚀 Python-3.8.10 torch-2.1.2+cu121 CUDA:0 (NVIDIA GeForce RTX 2080 Super with Max-Q Design, 7974MiB)
Setup complete ✅ (16 CPUs, 62.5 GB RAM, 681.6/915.3 GB disk)

OS                  Linux-5.15.0-94-generic-x86_64-with-glibc2.29
Environment         Linux
Python              3.8.10
Install             pip
RAM                 62.49 GB
CPU                 Intel Core(TM) i7-10875H 2.30GHz
CUDA                12.1

matplotlib          ✅ 3.5.2>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.1.2>=1.8.0
torchvision         ✅ 0.16.2>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.7
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.1>=0.11.0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Burhan-Q** [comment]
@ragahdtareg if you have a model that has completed training, you will need to start a _new_ training session for the `patience` argument to apply. You're probably seeing that the model will not continue training because it has already completed. Once a model finalizes, there's no way to train "on-top-of" what's already been done, you need to start a new session. The `resume` argument is _only_ for when you have a training session that has been interrupted prematurely (power outage, `Ctrl+c`, etc.) and will only allow you to modify the `batch` or `imgsz` arguments in case there was an out of memory error.

**Comment by Burhan-Q** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/62214284/0b817922-075a-4146-b40b-22c92f7f6545)
