### ISSUE TITLE
Unable to install ultralytics

### ISSUE THREAD

**Issue by elcodered** [ultralytics/ultralytics#8393]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am using Raspberry Pi 3 Model B. Raspbian OS 32-bit. And this is the error that I've got. See screenshot below:

![image](https://github.com/ultralytics/ultralytics/assets/106963696/6960e692-3756-44c7-989c-0bddb1154b87)

Is there another way to fix this? Like upgrading from 32 bit to 64 bit, would it work?

**Comment by glenn-jocher** [comment]
@elcodered hi there! 👋 It looks like you're encountering an installation issue on your Raspberry Pi 3 Model B. From the screenshot, it seems there might be a compatibility problem, possibly related to the 32-bit OS.

Upgrading to a 64-bit OS could potentially resolve this issue, as our models and installation process are optimized for 64-bit systems. Before you proceed with the OS upgrade, make sure your Raspberry Pi 3 Model B is compatible with a 64-bit OS.

Here's a quick command to update and upgrade your existing packages, which sometimes resolves installation issues:

```bash
sudo apt-get update && sudo apt-get upgrade
```

After that, you can try installing the Ultralytics package again. If you still face issues, consider switching to a 64-bit OS if your hardware supports it, and then attempt the installation once more.

Let us know how it goes, and we'll be here to help you through any further steps! 😊

**Comment by lakshanthad** [comment]
Hello @elcodered,

I would recommend you install Raspberry Pi Bookworm OS (64-bit) and try again. I have verified on all RPi3, RPi4, and RPi5 and installs are all successful.

1. Download [Raspberry Pi Imager](https://www.raspberrypi.com/software)
2. Select No filtering (This is needed or otherwise Bookworm OS will not show up under Raspberry Pi 3 board)
<img src="https://github.com/ultralytics/ultralytics/assets/20147381/4b834070-79e1-419b-ae6d-2d2a0f6d4323" width="500" height="auto">

3. After booting, you can do a simple update
`sudo apt update`
4. Then it is recommended to upgrade pip and wheel to latest
`python3 -m pip install --upgrade pip wheel`

Enjoy!
