### ISSUE TITLE
Is it possible to change the AMP check with yolov8n to larger version when training RTDETR?

### ISSUE THREAD

**Issue by davidan208** [ultralytics/ultralytics#8431]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,
I currently training on VisDrone dataset with RTDETR using the script:
```
from ultralytics import RTDETR

model = RTDETR('rtdetr-l.pt')
model.train(data = './DATASET/VisDrone.yaml', imgsz = 640, dropout = 0.1, project = './save_files', batch = 8)
```

I see it currently use the Yolov8n for AMP checking, is it possible to change to larger models like m, l, x version ? And if so, will the mAP gets better than using Yolov8n ?
Thank you.

**Comment by glenn-jocher** [comment]
@davidan208 hi there! 👋

Yes, you can certainly use larger models like YOLOv8m, YOLOv8l, or YOLOv8x for AMP (Automatic Mixed Precision) checking during training. To do this, you'll need to load the desired larger model before starting the training process. Here's a quick example of how you can do it:

```python
from ultralytics import RTDETR

# Load a larger model, for example, 'rtdetr-m.pt' for the medium version
model = RTDETR('rtdetr-m.pt')  # You can also use 'rtdetr-l.pt' or 'rtdetr-x.pt'
model.train(data='./DATASET/VisDrone.yaml', imgsz=640, dropout=0.1, project='./save_files', batch=8)
```

As for the mAP, using a larger model could potentially lead to better performance due to increased capacity and complexity, which might capture more details and variations. However, it also depends on the dataset and the specific task. It's worth experimenting to see if the larger models provide a significant improvement in your case.

Happy training, and let us know how it goes! 😊

**Comment by davidan208** [comment]
Thanks @glenn-jocher,

One question, where can I find the path to change the default models for AMP (I assume it is default to use Yolov8n.pt since when training with Yolov8l.pt, it also set the Yolov8n.pt for AMP) ? Thanks again.
![image](https://github.com/ultralytics/ultralytics/assets/37769067/2568ac68-0725-42e9-ac74-843b24fe63c6)

**Comment by glenn-jocher** [comment]
@davidan208 hi there! 👋

The AMP model selection isn't directly tied to a specific file path but is determined by the model you load for training. If you're training with `yolov8l.pt`, that model should be used for AMP checks automatically.

Here's a quick example to ensure you're using `yolov8l.pt` for AMP:

```python
from ultralytics import YOLO

# Load YOLOv8l model
model = YOLO('yolov8l.pt')
model.train(...)
```

If you're seeing `yolov8n.pt` during training with `yolov8l.pt`, it could be a logging display issue rather than an actual AMP check model issue. If you suspect there's a bug, feel free to open an issue on the repo, and we'll look into it! 😊

Happy coding!
