### ISSUE TITLE
Mps ram leaks

### ISSUE THREAD

**Issue by Ced70** [ultralytics/ultralytics#8441]
Hello,

I think i have an issue of memory leak.

My setup : MacBook Pro M3 max with 128 gb ram
Mac OS Sonoma 14.3.1

Version of Ultralytics : 8.1.18 (same issue since 8.0)

First, one problem appears when creating model in trainer.py.

![image](https://github.com/ultralytics/ultralytics/assets/122569819/02eb6c5f-3e3f-4052-a3de-165d1149ac67)

![image](https://github.com/ultralytics/ultralytics/assets/122569819/8908e6d4-3005-4c53-a8a2-817c40bf0fd5)

![image](https://github.com/ultralytics/ultralytics/assets/122569819/9020b75c-4953-41fe-ba7a-b28a1af199e4)

This appears with differents datasets. in this example, there are around 1000 images in bmp format. 

There is the code of the training :

`# Load a model
    temps_debut = time.time()
    model = YOLO(type_yolo + '.yaml')  # build a new model from YAML
    model = YOLO(type_yolo + '.pt')  # load a pretrained model (recommended for training)
    model = YOLO(type_yolo + '.yaml').load(type_yolo + '.pt')  # build from YAML and transfer weightsself.format_export = from Forma import FormFormat.
    temps_chargement_model = time.time() - temps_debut
    
    # Train the model
    temps_debut = time.time()
    if torch.backends.mps.is_available():
        torch.mps.empty_cache()
        model.train(data=data_yaml, epochs=epochs, imgsz=resolution_image, device='mps', workers=0, batch=batch,
                    augment=False, save_dir=variables_globales.projet_actuel.runs_dir, cache=False, save=True,
                    save_period=0, amp=True, patience=50)`

imgsz = 1024
batch = 32

With the same code ( with device=cuda ) with a RTX4090, ram used is around 12 gb.

Other problem is the used ram increases at each epoch.

At the end of the first epochs :

![image](https://github.com/ultralytics/ultralytics/assets/122569819/eba13e9a-4f5f-44fc-9109-d30aa523a19b)

During the second epochs :

![image](https://github.com/ultralytics/ultralytics/assets/122569819/d87fecc1-0940-452d-97cd-22b9db116497)

Tell me if you need more informations.

**Comment by glenn-jocher** [comment]
@Ced70 hello 👋,

Thank you for bringing this to our attention. Memory leaks can indeed be troublesome, especially when working with large datasets and models.

From the code snippet and the images you've provided, it seems like there might be an issue with the MPS backend not releasing memory as expected. While we investigate this further, here are a couple of suggestions that might help mitigate the issue:

1. Ensure that you're creating only one instance of the model. It looks like you're loading the model multiple times in succession, which might not be necessary. Try using just:
   ```python
   model = YOLO(type_yolo + '.pt')
   ```
   instead of loading the model from YAML and then again from the `.pt` file.

2. After each training epoch, you can attempt to manually invoke garbage collection in Python, which might help release some unreferenced memory. You can do this by adding:
   ```python
   import gc
   gc.collect()
   ```
   at the end of each epoch.

3. Reducing the `batch` size could also help manage memory usage, though this may impact training time.

If the issue persists, could you please provide us with the following additional information?
- The exact error messages or behavior that indicates a memory leak.
- Any specific patterns you've noticed related to when the memory usage increases.

We appreciate your patience and are here to help you resolve this issue. 🛠️

**Comment by Ced70** [comment]
Dear @glenn-jocher ,

I made the modifications like you describe and I always have the issue.

Please find this video to describe the problem. This video was made with the same dataset and parameters like yesterday.

https://github.com/ultralytics/ultralytics/assets/122569819/dd23f1a7-eb6f-4bc5-bbdf-9fbea2d3d599

Tell me if you need more informations.

**Comment by glenn-jocher** [comment]
Hello @Ced70,

Thanks for the update and for sharing the video! 🎥 It really helps in understanding the issue better. Since the modifications didn't resolve the memory leak, it might be something deeper within the MPS backend handling or our integration with it.

Could you please try adding the garbage collection call directly after the training loop in your script? Here's a quick example:

```python
import gc

# Your training loop here
model.train(...)

# Attempt to manually trigger garbage collection
gc.collect()
```

This is a temporary workaround while we dive deeper into the issue. Your detailed feedback is invaluable, and rest assured, we're on it! If there's anything specific you notice or any pattern in the memory usage increase, do let us know. Every bit of information helps. 🛠️

**Comment by itzhoujun** [comment]
any update?

**Comment by glenn-jocher** [comment]
@itzhoujun hello! 👋

We're actively looking into the memory leak issue with the MPS backend. In the meantime, could you try incorporating `gc.collect()` after your training loop as a temporary workaround? Like so:

```python
import gc
# Your training loop
model.train(...)
gc.collect()
```

Thanks for your patience! We'll update you as soon as we have more information. 🛠️

**Comment by Ced70** [comment]
> @itzhoujun hello! 👋
> 
> We're actively looking into the memory leak issue with the MPS backend. In the meantime, could you try incorporating `gc.collect()` after your training loop as a temporary workaround? Like so:
> 
> ```python
> import gc
> # Your training loop
> model.train(...)
> gc.collect()
> ```
> 
> Thanks for your patience! We'll update you as soon as we have more information. 🛠️

Hello,
I try this code but no changes :

```
        for i in range (10):
            model.train(data=data_yaml, epochs=1, imgsz=resolution_image, device='mps', workers=2, batch=batch,
                    augment=False, save_dir=variables_globales.projet_actuel.runs_dir, cache=False, save=True,
                    save_period=0, amp=True, patience=50)
            gc.collect()
```

**Comment by larryliuming** [comment]
def main(): 
    model = YOLO('yolov8s-my.mlmodel')

    # No memory leak occurs when using this line
    results = model('http://your_live_video_or_local_video', stream=True)
    # A memory leak occurs with Metal Performance Shaders when using the line below
    # results = model('http://your_live_video_or_local_video', stream=True, device="mps")

    counter = 0
    for r in results:
        counter += 1
        if counter % 1000 == 0:
            gc.collect()
            print("Garbage collection")
    print("End")

# See the attached pip_freeze.txt for my Python package versions.

It appears the memory leak happens more rapidly when large numbers of objects are detected in the video. Based on my investigation with objgraph, the leaking object might be related to ___Annotation___.

I hope this information is helpful.
[pip_freeze.txt](https://github.com/ultralytics/ultralytics/files/14716685/pip_freeze.txt)

**Comment by glenn-jocher** [comment]
@larryliuming hey there! 👋

Thanks for sharing this issue, including the simplified code and your findings. It's insightful and helps us understand the problem better. We'll definitely look into this, especially around the MPS usage which seems to be where the issue intensifies.

Your approach with manual garbage collection is a smart temporary workaround. Also, your detective work with objgraph pointing towards `___Annotation___` as the potential culprit gives us a good starting point for further investigation. 

We appreciate your patience as we dive into this. If you discover anything more or have additional insights, please keep us posted! 🛠️
