### ISSUE TITLE
Two different results when using model.predict and working with results 

### ISSUE THREAD

**Issue by qasara** [ultralytics/ultralytics#8450]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I run this code I get a file for each frame with prediction and bounding box details which is great but I want at least one csv file for json for one video or at least dictionary

```
model = YOLO("best.pt")
for r in model.predict(source="myvideo.mp4", save=True, save_txt=True, stream=True, vid_stride=1):
  pass

```
so I tried this method however it always show boxes as none 
```
model = YOLO("best.pt")
results = model(source="myvideo.mp4",  stream=True, vid_stride=1,save_conf=True)

for r in results:
  print(r)

boxes: None
keypoints: None
masks: None
names: {0: 'apple', 1: 'ornage', 2: 'green apple'}
obb: ultralytics.engine.results.OBB object
orig_img: array([[[ ...etc

```

**Comment by glenn-jocher** [comment]
@qasara hello! It looks like you're trying to gather predictions into a single CSV or JSON file for a video. When using `model.predict()` with `stream=True`, the results are streamed as a generator, which is why you're seeing `None` for boxes in the second method. This is because `model()` is not the correct method for predictions; you should continue using `model.predict()`.

To save results into a single CSV or JSON file, you can aggregate the results in a loop and then save them outside the loop. Here's a quick example of how you might do it for a CSV:

```python
import csv

model = YOLO("best.pt")
results_list = []

# Collect results
for r in model.predict(source="myvideo.mp4", stream=True, vid_stride=1):
    if r.boxes is not None:
        for box in r.boxes.xyxy:
            results_list.append(box.cpu().numpy())

# Save to CSV
with open('predictions.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(results_list)
```

This code snippet collects all bounding boxes into `results_list` and then writes them to a CSV file named `predictions.csv`. For JSON, you can use the `json` module in a similar way to write `results_list` to a file.

Hope this helps! Let us know if you have any more questions. 😊

**Comment by roy-orfaig** [comment]
I trained a model with an IoU (NMS) threshold of 0.6, but when I run this model (after upload the pt) on an image using res = model.predict(img_path) and res = model.predict(img_path, iou=0.6), I get different results. How is that possible if I'm using the same IoU value as saved in the .pth file?

**Comment by glenn-jocher** [comment]
@roy-orfaig the difference occurs because the `iou` value in your `.pt` file sets the training NMS IoU, while the `iou` argument in `model.predict()` controls inference NMS IoU. These are separate parameters. To ensure consistency, explicitly set `iou=0.6` during inference to match your training configuration. For details, see the [Inference Arguments documentation](https://docs.ultralytics.com/modes/predict/#inference-arguments).

**Comment by roy-orfaig** [comment]
Thanks for your reply. However, if we use the same value of 0.6 for both model.predict and training, shouldn't we expect the same results as when NMS was applied during training on the validation dataset? For context, I observed low recall and precision on the validation dataset during training, and I want to analyze this issue. How can I do that? I expected NMS to behave the same way—I thought that if I loaded the .pth file, I would have the same model as during training.

**Comment by glenn-jocher** [comment]
Yes, you're correct. The `.pt` file's IoU=0.6 applies to training/validation metrics, while inference defaults to `iou=0.7` in `model.predict()`. To match validation NMS behavior during inference, explicitly set `iou=0.6`, `conf`, and `max_det` to match your training/validation values. These are the primary NMS parameters to align. For details, see the [Inference Arguments documentation](https://docs.ultralytics.com/modes/predict/#inference-arguments).
