### ISSUE TITLE
Possible typo in `select_highest_overlaps` function doc

### ISSUE THREAD

**Issue by deanmark** [ultralytics/ultralytics#8467]
https://github.com/ultralytics/ultralytics/blob/2d75f72598d5ce80786be61f140673a6d1dd7e57/ultralytics/utils/tal.py#L234

The doc states:
> ...the highest **IoI** will be selected

Shouldn't this be IOU?

**Comment by glenn-jocher** [comment]
@deanmark thank you for pointing this out! 🙌 You're absolutely right, it should indeed be IOU (Intersection over Union) rather than IoI. We appreciate your keen eye on this, and we'll update the documentation to correct this typo. Here's a quick fix for clarity:

```python
def select_highest_overlaps(...):
    """
    ...the highest IOU will be selected
    """
```

Thanks again for your contribution to making YOLOv8 even better! If you spot anything else, please don't hesitate to let us know.

**Comment by deanmark** [comment]
@glenn-jocher 
May I have the honor of fixing the typo? 
Added PR [#8600](https://github.com/ultralytics/ultralytics/pull/8600)

**Comment by glenn-jocher** [comment]
@deanmark Absolutely, we'd be delighted for you to contribute! 🎉 Thanks for catching that typo and for the PR. I'll review it shortly. Your efforts help make YOLOv8 better for everyone! 🚀
