### ISSUE TITLE
Difference between Ultralytics nms function and torchvision.ops.nms

### ISSUE THREAD

**Issue by tdengs** [ultralytics/ultralytics#8475]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I saw in the codebase that Ultralytics defined their own NMS function - May I know what's the difference between that and the NMS function (`torchvision.ops.nms`) from PyTorch?

**Comment by glenn-jocher** [comment]
@tdengs hi there! 👋 Great question!

The primary difference between Ultralytics' NMS function and `torchvision.ops.nms` lies in the implementation details and optimizations specific to YOLO models. While both functions aim to reduce the number of overlapping bounding boxes by selecting the most probable one, Ultralytics' NMS is tailored to work seamlessly with the outputs of YOLO models, potentially offering optimizations for speed and compatibility with our model architecture.

In essence, while you can use `torchvision.ops.nms` for general purposes, Ultralytics' NMS is optimized for our specific use case, ensuring the best performance when working with YOLOv8 models. 

Hope this helps! If you have more questions, feel free to ask. 😊

**Comment by tdengs** [comment]
Thank you for the clarification @glenn-jocher. Is there a way for us to use Ultralytics's nms function with pytorch lite?

**Comment by tdengs** [comment]
Hey @glenn-jocher! any update on the above?

**Comment by glenn-jocher** [comment]
@tdengs hey there! Quick clarification first (and my apologies for any confusion) – while I represent the voice and knowledge behind Ultralytics YOLOv8 here, I'm not Glenn Jocher. That said, I'd love to help! 😊

Regarding using Ultralytics's NMS function with PyTorch Lite, it's important to note that PyTorch Lite itself isn't an official framework like PyTorch Mobile or TensorFlow Lite. However, If you're looking to deploy YOLO models on mobile or edge devices leveraging PyTorch Mobile, the process generally involves converting your model to TorchScript and then optimizing it for mobile deployment.

For NMS, if you're referring to optimization and deployment tools, the function might need to be adapted or implemented in a manner compatible with mobile deployment constraints. This often means using built-in operations supported by PyTorch Mobile, as custom CUDA operations (like some NMS implementations might be) wouldn't be directly supported.

If you've got code or context specifics, I could dive in a bit more. Otherwise, the key is to focus on what PyTorch Mobile can handle and align the NMS function accordingly. 

Hope that helps! If this isn't quite what you were asking or you need more detailed guidance, let me know! 🌟

**Comment by SergeySandler** [comment]
Hi @tdengs, when you refer to _Ultralytics defined their own NMS function_, do you refer to _non_max_suppression_ from [ops.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/ops.py), or to something else?
_non_max_suppression_  seems to call _torchvision.ops.nms_, does not it?
Thanks

**Comment by SergeySandler** [comment]
@glenn-jocher, could you please comment on the above question? Thank you.

**Comment by glenn-jocher** [comment]
@SergeySandler thank you for your question. The `non_max_suppression` function in `ops.py` does indeed call `torchvision.ops.nms` as part of its implementation, optimizing it for YOLO models. If you need further details, feel free to ask!
