### ISSUE TITLE
Why does GFLOPS suddenly not output when using yolov8 for training?

### ISSUE THREAD

**Issue by Cycsics** [ultralytics/ultralytics#8486]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Why does GFLOPS suddenly not output when using yolov8 for training? I have tried re-pulling the code repository/reconfiguring the environment and changing the computer to repeat the above steps.
![20240227141829](https://github.com/ultralytics/ultralytics/assets/22937494/fd0b0380-5b86-4022-85d3-2ac5cb0c6e0f)

GFLOPS can still be output on 2024/02/22, but cannot be output on 2024/02/23. No code modifications are made. It is just repeated running of the unified model for training on different data sets.

**Comment by glenn-jocher** [comment]
@Cycsics hello! Thanks for reaching out with your question. 🌟

The sudden absence of GFLOPS output during training with YOLOv8 might be related to changes in the logging configuration or a minor glitch in the environment setup. Since you've already tried re-pulling the repository and reconfiguring the environment without success, I recommend checking the following:

1. **Logging Level**: Ensure that the logging level is set to include detailed information. Sometimes, GFLOPS information might be considered verbose and only shown at certain logging levels.

2. **Version Check**: Double-check if there were any updates or changes made to the YOLOv8 repository around the dates you mentioned. Although you haven't made code modifications, an automatic update or change in the repository might have affected the output.

3. **Debugging**: Temporarily add explicit logging for GFLOPS calculation in the training script. This can help determine if the calculation is being performed but not displayed.

```python
import logging
logging.info(f"GFLOPS: {gflops_calculated_value}")
```

If these steps don't resolve the issue, it might be helpful to open an issue on the [Ultralytics YOLOv8 GitHub](https://github.com/ultralytics/ultralytics/issues) with detailed information about your environment (OS, Python version, PyTorch version, etc.) and the exact steps to reproduce the issue. The community and developers are quite responsive and might offer more insight into this peculiar behavior.

Hope this helps! Let us know if you have any more questions or updates.

**Comment by Cycsics** [comment]
![image](https://github.com/ultralytics/ultralytics/assets/22937494/c284f58e-9fca-49ef-8387-29a66fe3eff0)
I tried to print GFLOPS in torch_utils.py, but no relevant logging output was found in the output.
The following is my environment detailed information
![image](https://github.com/ultralytics/ultralytics/assets/22937494/92b201e8-207b-4c8e-b420-e2ef96bba7e3)
`torch                    2.1.2`
`Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy`
GPU:4090 CPU:14700K Mermory:64GB DDR5

**Comment by Cycsics** [comment]
@glenn-jocher Hey, thank you for your patience in answering my issue
I think I found why this issue occurs. When I reconfigure the environment, I will install torch and thop first and then utralytics, but I don't know why thop seems to have unknown changes after installing utralytics, causing AttributeError: module 'thop' has no attribute 'profile' ,as the picture shows.
![image](https://github.com/ultralytics/ultralytics/assets/22937494/8cfd8a54-df59-45ea-91c6-14af300c1747)
This issue seemed to be resolved after I uninstalled the thop and utralytics modules and changed the installation order.
![image](https://github.com/ultralytics/ultralytics/assets/22937494/4e80a085-84b5-41ba-ad0c-39b3925cca68)
Hope these situations are helpful to you
Have a good day!

**Comment by glenn-jocher** [comment]
Hey @Cycsics, thanks for sharing your findings! 🌟 It sounds like the installation order of `thop` and `ultralytics` is indeed affecting the environment. Reinstalling the modules in the correct sequence seems to be a good workaround. Your insight is definitely helpful and might assist others facing similar issues. We'll look into why this dependency conflict occurs. Have a great day too! 😊
