### ISSUE TITLE
polygon() got an unexpected keyword argument 'width'

### ISSUE THREAD

**Issue by LeiaJ520** [ultralytics/ultralytics#8490]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

When I used yolov8-obb to validate the DOTA test set, I got an error saying "polygon() got an unexpected keyword argument 'width'" and got no test result in the val file. 
The CLI is:yolo val obb data=DOTAv1.yaml model=runs/obb/train2/weights/best.pt batch=16 imgsz=1024 device=0 split=test.
Specific problems are shown in the figure below:
<img width="732" alt="yolov8-obb检测问题" src="https://github.com/ultralytics/ultralytics/assets/95119550/32aa25d3-7f47-4add-94f4-34495ce0957d">

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@LeiaJ520 hello! Thanks for reaching out and for your willingness to contribute with a PR! 🌟

It seems like the issue you're encountering with the `polygon()` function might be due to a mismatch in the expected parameters. The `width` parameter error suggests that the function call is not aligned with the library's current implementation.

A quick workaround could be to check the definition of the `polygon()` function you're using and ensure that the `width` parameter is indeed supported. If it's not, you might need to adjust the function call accordingly.

If you're using a library like `matplotlib` or `PIL` for drawing polygons, the parameter for setting the line thickness might be named differently, such as `linewidth` in `matplotlib`.

Without seeing the exact code, it's a bit tricky to provide a precise solution, but here's a general example of how you might draw a polygon without the `width` parameter:

```python
# Example using matplotlib (just as a reference)
import matplotlib.pyplot as plt
import numpy as np

polygon = np.array([[1, 3], [2, 8], [5, 4]])  # Example polygon points
plt.plot(polygon[:, 0], polygon[:, 1], linewidth=2)  # Using 'linewidth' instead of 'width'
plt.show()
```

Please double-check the documentation of the library you're using for the correct parameter name and usage. If you find that the issue is indeed with the YOLOv8 codebase and you have a fix, we'd be thrilled to review your PR!

Let us know if you need further assistance. Happy coding! 🚀

**Comment by 54HaoHao-hue** [comment]
@LeiaJ520 The reason for the error is that in ultralytics/utils/plotting.py, when drawing a rotated rectangle with draw.polygon() on line 294, the author uses three parameters, namely [[x1,y1], [x2,y2].....], width, and outline. However, I looked at the source code of polygon(), and it doesn't accept the width parameter, so you can just delete the width parameter. width is just to adjust the line width of the box, and it doesn't hurt to remove it.
There may be some versions of pillow where polygon() can accept the width parameter, you can look for it. If you find a suitable version, please please trouble @ me, thanks.
