### ISSUE TITLE
autobatch not working

### ISSUE THREAD

**Issue by wisrovi** [ultralytics/ultralytics#8493]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train, Integrations

### Bug

I want to run the code into a container of docker with python 3.10.12 for calculate autobatch, but I have a error:

AMP: checks passed ✅
train: Scanning /app/datasets/coco8-seg/labels/train.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:00<?, ?it/s]
val: Scanning /app/datasets/coco8-seg/labels/val.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:00<?, ?it/s]
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "/app/test2.py", line 7, in <module>
    a = ultralytics.utils.autobatch.check_train_batch_size(model, imgsz=640, amp=True) 
  File "/usr/local/lib/python3.10/site-packages/ultralytics/utils/autobatch.py", line 27, in check_train_batch_size
    return autobatch(deepcopy(model).train(), imgsz)  # compute optimal batch size
  File "/usr/local/lib/python3.10/site-packages/ultralytics/engine/model.py", line 644, in train
    self.trainer.train()

### Environment

into of container:

Ultralytics YOLOv8.1.19 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060, 12036MiB)
Setup complete ✅ (8 CPUs, 31.2 GB RAM, 319.5/467.9 GB disk)

### Minimal Reproducible Example

import ultralytics
from ultralytics import YOLO

model = YOLO("yolov8s-seg.pt")

ultralytics.checks()

a = ultralytics.utils.autobatch.check_train_batch_size(model, imgsz=640, amp=True) 
print(a)

### Additional

Dockerfile:

FROM python:3.10.12
RUN apt-get update && \
    apt-get install -y libgl1-mesa-glx 
RUN apt-get install ffmpeg libsm6 libxext6  -y
RUN apt-get install -y libxrender-dev
RUN apt-get install -y htop iotop strace
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

_____________
requirements.txt

flask
ultralytics
ffmpeg-python
icecream
tqdm
shapely
nvidia-ml-py3
MoviePy
lapx
Cython

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@wisrovi hey there! 👋 It looks like you're encountering an issue with autobatch due to insufficient shared memory in your Docker container. This is a common scenario when working with Docker, especially with data-intensive tasks like those performed by YOLOv8.

A quick fix for this issue is to increase the shared memory size when you run your Docker container. You can do this by adding the `--shm-size` parameter to your `docker run` command. For example:

```bash
docker run --shm-size=1g your_image_name
```

This command increases the shared memory size to 1GB. You might need to adjust the size based on your specific requirements.

If you're still facing issues after trying this, please feel free to share more details or any updates. Happy to help further! 😊

**Comment by glenn-jocher** [comment]
@wisrovi great to hear it's working well for you now! 😊 If you have any more questions or run into other issues, feel free to reach out. Happy coding!
