### ISSUE TITLE
YOLOv8 with C programming languange

### ISSUE THREAD

**Issue by rafpy17** [ultralytics/ultralytics#8498]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is there a C, C++, C#, or any other programming languange example available for YOLOv8?

**Comment by GR899** [comment]
Strong interest in this as well. would very much like to see a C example or API. Thanks.

**Comment by glenn-jocher** [comment]
@GR899 absolutely, we understand the interest in having examples in C or other programming languages for YOLOv8! 🚀 While our main focus has been on Python for its widespread use in the AI community, we're always exploring ways to make YOLOv8 more accessible across different platforms and languages.

For C and C++, integrating YOLOv8 models can be achieved through ONNX Runtime or TensorRT, which both offer C++ APIs. Here's a very brief example of how you might load and run an ONNX model with ONNX Runtime in C++:

```cpp
#include <onnxruntime_cxx_api.h>

int main() {
    Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "test");
    Ort::SessionOptions session_options;
    session_options.SetIntraOpNumThreads(1);

    // Assuming you have an ONNX model exported from YOLOv8
    const char* model_path = "yolov8.onnx";

    Ort::Session session(env, model_path, session_options);

    // Add code to prepare input tensor, run session, and process output
}
```

For C#, Microsoft's ML.NET offers capabilities to run ONNX models, which could be a pathway for integrating YOLOv8 models into C# applications.

We're keen on supporting the community's needs, so feedback and contributions are always welcome. If you have specific examples or integrations you've worked on, feel free to share them with the community! 🌟

**Comment by GR899** [comment]
@glenn-jocher Thanks you for your sample code and your suggestions. 

May I suggest/request that what would be most useful to me is C / C++  functionality on the *inference* (predict/detect) side. Using python for training/validation/testing is fine, however I really need something I can loop into from C for inference. 

If it would be better if I make this request through another post or channel I'm happy to do so. Again, thank you very much for your response and your thoughtful assistance. Your support is very much appreciated by me and the community.

**Comment by rafpy17** [comment]
@glenn-jocher So in YOLOv8 we convert the .PT model to ONNX and implement it in C language?

Can I get an example of using .ONNX for real time object detection in C?

**Comment by YumainOB** [comment]
@glenn-jocher thank you for the ONNX example but ONNX performs really slower than TensorRT so it is not really suitable for realtime inference. Do you have an idea/example of Yolov8 inference in C++ based on TensorRT that is compatible with your legacy "yolo export format=engine ..." CLI?

**Comment by YumainOB** [comment]
Nevermind, this issue is related to metadata serialized within the engine as explained [here](https://github.com/ultralytics/ultralytics/issues/4597#issuecomment-1694948850).

Nevertheless, I have an issue to manage cls inferences with trtexec and my application (that share some code philosohy) as all results are set to **nan** and not to float values:
```
yolo export model=yolov8s_cls_dset_14.pt format=engine simplify=True opset=14 workspace=5 half=True dynamic=False
/usr/src/tensorrt/bin/trtexec --loadEngine=yolov8s_cls_dset_14.engine --shapes=images:1x3x224x224 --output=output0 --exportOutput=trt_result_rnd.json --fp16
cat trt_result.json 
[
  { "name" : "output0"
  , "dimensions" : "1x4"
  , "values" : [ nan, nan, nan, nan ]
  }
]
```
This may not be linked to ultralytics but I'm quite sure that thanks to your wizeness and knowlegde you can help me to understand  what can go wrong as the "yolo classify predict...." runs fine with results identical to those observed ith with pt and onnx predictions.

**Comment by glenn-jocher** [comment]
@YumainOB hi there! 👋 I'm glad to see you're making progress and delving deeper into the intricacies of YOLOv8 with TensorRT. The issue you're facing with `nan` values in the output seems intriguing and indeed requires a bit of digging.

Given that your `.engine` works well with `yolo classify predict...` but results in `nan` values when used with `trtexec`, it might hint at a discrepancy in how the data is being processed or interpreted between your application and `trtexec`. A few things you might consider checking are:

- **Data preprocessing and normalization:** Ensure that the input data to the TensorRT engine in your application and `trtexec` undergo the same preprocessing and normalization steps. Mismatches here can lead to unexpected output.

- **Engine compatibility:** Double-check that the `.engine` file is compatible with the version of TensorRT you are using with `trtexec`. Version mismatches can also result in errors or incompatible behavior.

- **Model architecture specifics:** Having simplified the model with `simplify=True`, it's worth making sure that all layers and operations are fully supported and correctly interpreted by TensorRT.

It's also a good idea to revisit the issue discussion around metadata serialization to ensure there's nothing amiss there that might affect inference results.

Although I can't provide an immediate solution without more context, I hope these pointers help guide your troubleshooting! Should you find more insights or require further assistance, feel free to reach out. The community and I are here to support you on your journey. Keep exploring and experimenting! 💡

**Comment by YumainOB** [comment]
@glenn-jocher Hello and thanks a lot for the reply.

As far as I understand my issue and the logs I get from debug sessions, I agree with your first cause.

In facts I achieve to get FP32 engines to operate as intended with the same inference results than with python ".pt" or ".onnx" models. The problem looks clearly on the FP32/FP16 side. I must have lost my C++ skills passing years coding in python because this transform isn't as easy as in numpy (sadely).

I'll try to investigate later on this besause sadely I have no time for this now.

Best regards

**Comment by glenn-jocher** [comment]
Hey @YumainOB! 👋 It sounds like you've narrowed down the issue to the FP32/FP16 transformation, and yes, swapping precision levels can sometimes be trickier in C++ compared to Python's more straightforward handling. It's quite common to feel a bit rusty when switching back and forth between languages, so no worries there! 😄

Since time is tight on your end, it might be a good idea to bookmark this for a deeper dive later. In the meantime, if you find a momentary break from your busy schedule and wish to revisit, remember to check on how your application deals with data casting or conversions between different precision formats.

Take care and all the best with your current priorities! Looking forward to hearing back when you circle around to this. 🚀

**Comment by kospsh157** [comment]
Where can I get YOLOv8 C++ inference code from official Ultralytics team? plz Help me! T.T

**Comment by glenn-jocher** [comment]
Hello! 🌟 For C++ inference using the `.engine` format with YOLOv8, we currently don't have an official example directly from Ultralytics. However, you can use the TensorRT API to load and run inference with the `.engine` files. Here’s a brief snippet on how you might set it up:

```cpp
#include "NvInfer.h"
#include "NvInferRuntime.h"
#include "NvInferRuntimeCommon.h"

int main() {
    nvinfer1::IRuntime* runtime = nvinfer1::createInferRuntime(gLogger);
    nvinfer1::ICudaEngine* engine = runtime->deserializeCudaEngine(trtModelStream, size);

    nvinfer1::IExecutionContext* context = engine->createExecutionContext();
    // Set up your input and output buffers, enqueue your inference, etc.
}
```

Make sure to handle your input and output buffers appropriately and link against the necessary TensorRT libraries. For a more detailed guide, the [TensorRT Developer Guide](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html) is a fantastic resource.

Hope this helps! If you have more questions, feel free to ask. Happy coding! 😊
