### ISSUE TITLE
Am I training from scratch?

### ISSUE THREAD

**Issue by ronj-c** [ultralytics/ultralytics#8499]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I am attempting to train a yolov8s model from scratch. From what I know, in order to do this, all you need to do is the following:

```
from ultralytics import YOLO


model = YOLO('yolov8s.pt')
results = model.train(data='file.yaml', batch=4, imgsz= (1824, 1024), pretrained=False)
```
Yet, when the model is being loaded I see the following:

![Screenshot from 2024-02-27 09-05-48](https://github.com/ultralytics/ultralytics/assets/42298486/a4ce27a5-ad5a-4a12-b0ba-75576ba1f36c)

So my question is, what exactly is `Transferred 349/355 items from pretrained weights` indicating?

Additionally I can notice an initial mAP_50 of around 70 in just the first few epochs. This to me, seems like performance more in line with a model that is being finetuned rather than trained from scratch,

**Comment by glenn-jocher** [comment]
@ronj-c hi there! 👋

Great question! When you see `Transferred 349/355 items from pretrained weights`, it means that most of the weights from a pretrained model have been loaded into your model. This typically happens to ensure your model has a good starting point, which can significantly speed up training and potentially lead to better final performance.

However, since you're aiming to train from scratch and want to avoid using pretrained weights, you should initialize your model without loading any pretrained weights. Here's how you can do it:

```python
from ultralytics import YOLO

# Initialize a model from scratch
model = YOLO('yolov8s.yaml')  # Note: Use the .yaml configuration file, not the .pt file
results = model.train(data='file.yaml', batch=4, imgsz=(1824, 1024))
```

By specifying the model architecture with a `.yaml` file instead of a `.pt` file, you ensure that the model starts with randomly initialized weights rather than weights from a pretrained model.

The initial high mAP_50 you're observing is indeed more characteristic of a model that has been fine-tuned from pretrained weights. Starting from scratch should give you different initial performance metrics, typically lower, as the model learns from the ground up.

Hope this helps! Let us know if you have any more questions. 😊
