### ISSUE TITLE
Support for Non-Square Image Sizes in Validator

### ISSUE THREAD

**Issue by ddroghini-ics** [ultralytics/ultralytics#8523]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Validator

### Bug

I've identified a limitation within the current implementation of the validator in the ultralytics engine, where it appears to only support square image sizes due to the way image dimensions are handled.

**Issue Location:**
[Validator Implementation Line 155](https://github.com/ultralytics/ultralytics/blob/f8e681c2be251562633d424f4a1a1cc7da526bed/ultralytics/engine/validator.py#L155)

**Current Behavior:**
The validator is currently designed to assume square image sizes, which may not be flexible enough for all use cases, especially those requiring rectangular images.

**Suggested Modification:**
To accommodate both square and non-square image sizes, I propose the following modification to the dimension handling logic:

```python
if len(imgsz) == 1:
    warmup_dim = (self.args.batch, 3, imgsz, imgsz)
else:
    warmup_dim = (self.args.batch, 3, *imgsz)
model.warmup(imgsz=(1 if pt else warmup_dim))
```

This modification checks the length of the `imgsz` input. If it's a single dimension (implying a square image), it constructs the `warmup_dim` with duplicate dimensions for height and width. If `imgsz` contains more than one dimension, it directly uses these dimensions to define the image shape, supporting non-square images effectively.

**Expected Outcome:**
This change would enable the validator to support non-square image sizes, making the library more versatile and accommodating a broader range of applications.

I believe this enhancement would be beneficial for the flexibility and usability of the ultralytics engine. Looking forward to the community's thoughts and any further suggestions.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ddroghini-ics hey there! 👋

Thanks for bringing this to our attention and for the detailed suggestion! Your proposed modification for supporting non-square image sizes in the validator looks promising. We always aim to enhance the flexibility and usability of the Ultralytics YOLO models, and accommodating a broader range of image dimensions is definitely a step in the right direction.

We'll review your suggestion and consider integrating it into the next update. If you're willing and able to help by submitting a PR, that would be fantastic! Otherwise, we'll take it from here and keep the community posted on progress.

Thanks again for your contribution to making the Ultralytics YOLO models even better! 🚀
