### ISSUE TITLE
YOLOv8 crahes when using workers > 8

### ISSUE THREAD

**Issue by Irikos** [ultralytics/ultralytics#8524]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

Hello,

I have encountered a problem that is rather new to me. When selecting any number of workers > 8, the system crashes. If I select 12, it trains for a few epochs and then crashes. If I select 16, it crashes right away. When it does so, it freezes my PC for a short amount of time, then it unfreezes it and it works really slow, only to crash all my chrome tabs (I assume the GPU driver?) and resume. I need to restart the PC afterwards in order to ensure proper working conditions.

I thought it might be from the dataset, but the same happens on the COCO dataset with the standard code.

I have a fresh reinstalled Ubuntu (because of this, but nothing changed) and have tried both 535 and 525 nvidia drivers.

I am training on a RTX 4090 and my os.cpu_count()) is 24.

This has also happened after I updated my ultralytics repo to the latest version, but this might just be a coincidence.

As per my knowledge, I should be able to input any number of workers, as it will select the maximum possible, right?

In the past, I trained on an RTX3090 with workers=24. I have also tried using CLI, Python, VSCode, Terminal and PyCharm. All situations produce a similar version of this with minimal - if any - differences.

I do not train in Jupyter normally, but did try it out in order to debug this scenario. It is the only situation that provides this warning.

This happens for both segmentation and detection in the same manner.

Update: I think it is most likely an error regarding a combination between the number of workers and the batch size. I increased the batch size even more (18GB total usage out of 24GB) and it crashes with 8 workers as well.

The value around which it does not crash is 8 workers with 9GB usage out of 24GB. Still, in the past, on RTX3090 I managed to use it with 24 workers and fairly large batch size. Combinations that now crash on RTX4090.

### Environment

Ultralytics YOLOv8.1.18 🚀 Python-3.12.1 torch-2.2.0+cu121 CUDA:0 (NVIDIA GeForce RTX 4090, 24195MiB)
Setup complete ✅ (24 CPUs, 31.1 GB RAM, 231.5/419.6 GB disk)

### Minimal Reproducible Example

``` from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n.yaml')  # build a new model from YAML
model = YOLO('yolov8n.pt')  # load a pretrained model (recommended for training)
model = YOLO('yolov8n.yaml').load('yolov8n.pt')  # build from YAML and transfer weights

# Train the model
results = model.train(data='coco128.yaml', imgsz=640, epochs=300, batch=128, workers=8)
```

### Additional

I have also noticed that when trying to train in VS Code Jupyter notebook, it provided a warning similar to
" UserWarning: This DataLoader will create 16 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary."

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Irikos hello! 👋

Thanks for the detailed report. It seems like the issue might be related to the system's ability to handle multiple worker processes efficiently, especially with high-performance GPUs like the RTX 4090. While it's true that you can specify any number of workers, the optimal number can vary based on your system's configuration, dataset, and the specific task you're running.

Given the warning you received in VS Code Jupyter notebook, it suggests that the system recommends a much lower number of workers than you're attempting to use. This is likely due to the overhead associated with managing multiple worker processes, which can indeed lead to the system becoming unresponsive or crashing, especially when combined with large batch sizes that utilize a significant portion of your GPU memory.

As a workaround, you might want to experiment with reducing the number of workers to below 8, as you've found it to be stable, and gradually increase it to find a sweet spot that balances performance without overloading your system. Additionally, monitoring system resources during training might provide insights into any bottlenecks.

Here's a slightly modified version of your training command to start with a lower number of workers:

```python
results = model.train(data='coco128.yaml', imgsz=640, epochs=300, batch=128, workers=4)
```

It's also worth noting that updates to the Ultralytics repo or changes in the underlying libraries (like PyTorch or CUDA) could introduce differences in how resources are managed, which might explain the change in behavior you've observed.

If the issue persists, providing more details about the crash (logs, error messages) could help in diagnosing the problem further. 🛠️

Hope this helps!

**Comment by Burhan-Q** [comment]
@Irikos I'm not able to replicate the issue (I also don't have as nice of a system to test on). Can you try running this from the terminal with your environment activated?

`yolo train data=coco128.yaml model=yolov8n.pt epochs=30 workers=16`

```
Ultralytics YOLOv8.1.19 🚀
Python-3.10.12
torch-2.2.0+cu121 

CUDA:0              NVIDIA GeForce RTX 2060, 5924MiB
OS                  Linux-6.6.10-76060610-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             pip
RAM                 15.56 GB
CPU                 AMD Ryzen 5 1600 Six-Core Processor
```

**Comment by Burhan-Q** [comment]
@Irikos couple questions:
1. What OS are you on? Sorry if you shared, but I just quickly skimmed and didn't find anything.
1. I just noticed you're on python 3.12, try downgrading to 3.11. Although it is supported by PyTorch and by extension Ultralytics, the PyTorch support is still fairly new. I've seen lots of users having issues with python 3.12 still, so I wouldn't recommend using it quite yet.
1. Are you always running from a notebook? Have you tried/tested using the CLI commands or from a plain python terminal?
1. NMS timeout warnings can happen, as far as I'm aware they're not really anything to be worried about
1. With large workloads I would definitely recommend closing all other applications (when possible) during training. Training cycles will have slightly varying demands on the system, if the same goes with other processes, they could be fighting over resources

**Comment by Irikos** [comment]
1. Ubuntu 22.04
2. Will do and I'll get back to you on that
3. No, I'm usually not running from a notebook. I usually run .py scripts or from CLI (but really prefer .py scripts). I only ran from a notebook as part of the debugging process in trying many new things. The situations I mentioned in the previous posts - except the one where I specifically mentioned the notebook - are using .py scripts. Normally I wrote them in VS code and called from terminal in VS code, but recently I switched to PyCharm, with no change in this problem.
4. Ok, good to know
5. True, but I'm not really pushing it to the edge. I'm aiming at 16GB - 18GB out of 24GB total load. And all these batch sizes and workers combinations worked fine 6+ months ago on RTX3090.

Thanks for the feedback!

**Comment by Irikos** [comment]
@Burhan-Q @glenn-jocher 

First of all, downgrading python made no difference, good or bad.

I have found the problem, though: it is an overflow of RAM memory, having nothing - or little - to do with the GPU memory, as the RAM load is the same irrespective of the size of the model. I monitored all my resources and it basically filled my RAM and switched to the swap memory. I increased the swap memory and watched it being filled; this worked, but significantly reduced the training speed (and PC performance), thus makes no sense to use it.

I assume the dataloader loads the images in full format and does the resizing afterwards. If that is the case, then 64-128 batch images with 8-16 workers is quite a lot. 

I am using 32 batch with 8 workers now and it stabilizes at 20ish GB out of 32 GB total RAM memory.

I still do not understand why the workers did not stabilize themselves when running out of memory, though. But I will most likely train all my models in batches of 32, except x which I'll train in batches of 16 due to not enough GPU memory.

Thanks for all the help!

**Comment by glenn-jocher** [comment]
@Irikos Thanks for sharing your findings – really insightful! 🌟 It's indeed a tricky situation when RAM (not GPU memory) becomes the bottleneck. Your observation about the dataloader and its handling of large batches and multiple workers leading to high RAM usage is spot on. The system tries to precache as much data as possible for efficiency, which can sometimes lead to overutilizing RAM, especially with high-resolution images and large batch sizes.

Reducing the batch size and worker count to better fit within your RAM limitations is a sensible approach. As for the workers not automatically adjusting, it's largely because they are predetermined based on your settings rather than dynamically adjusting to system load – something that would indeed be very useful in preventing such scenarios.

For future reference or if you're looking to push your setup further, you might consider monitoring and adjusting other system parameters or even upgrading the RAM if you consistently find it to be the limiting factor. However, it sounds like you've found a good balance for your current setup. 

If you need to run larger batches or more workers in the future, keeping an eye on the system's overall RAM usage will be key. Happy training, and if you have any more questions or run into further issues, feel free to reach out!

**Comment by mxrguspxrt** [comment]
All my x11 crashes when using v8 with video. Like 75% frames of 4000 get processed, then just all gets stuck and reboot required. Debugging and will attach more logs. :(

**Comment by glenn-jocher** [comment]
Hey @mxrguspxrt,

Sorry to hear about the crashes 😞. It sounds like a resource issue. Try reducing the `workers` and `batch` size in your training script to see if that helps stabilize things. For example:

```python
results = model.train(data='coco128.yaml', imgsz=640, epochs=300, batch=32, workers=4)
```

Also, make sure your GPU drivers and CUDA are up to date. Looking forward to your logs for more insights! 🚀

**Comment by glenn-jocher** [comment]
The optimal number of workers typically depends on your CPU cores and available RAM. It's used to parallelize data loading, so start with a number close to your CPU core count and adjust based on performance and memory usage.
