### ISSUE TITLE
Run yolov8 using Ultralytics source code not installed package

### ISSUE THREAD

**Issue by GWLee0524** [ultralytics/ultralytics#8533]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I need code modification for building my own model.

But I have problems for doing this.

I cloned ultralytics repository and run my python code for training my model in this repository.

And I modified default.yaml in repository not in python package path
I checked that it was used during training my model. So I guess my code import source codes from ultralytics repository.

I modified `augment.py` to disable Albumentations (just make a line as comment).
But it was not working. So in this case, ultralytics pip package was used not modifed source code.

how can I train my model using source codes from repository?

**Comment by glenn-jocher** [comment]
@GWLee0524 hello! 😊 It sounds like you're trying to train your model using the locally modified Ultralytics YOLOv8 source code rather than the installed package. To ensure your Python environment uses your local changes, you can navigate to the root directory of the cloned repository and run the following command:

```bash
pip install -e .
```

This command installs the package in editable mode, linking it directly to your source code changes. Any modifications you make in the repository, such as your changes in `augment.py`, will be reflected immediately without needing to reinstall the package.

Make sure you're running your training script from within or relative to the cloned repository's directory to ensure it's using your local version of the code. This approach should allow you to train your model with your custom modifications. Happy coding! 🚀

**Comment by GWLee0524** [comment]
Thanks to reply my question!

Firstly, sorry to reply your answer because I enjoyed 3 holidays (Independence Movement Day and weekend).

I tried your suggestion and it works for me.

I close this issue.

Thank you!

**Comment by glenn-jocher** [comment]
@GWLee0524 No worries at all, I hope you had a wonderful holiday! 😊 I'm thrilled to hear that the suggestion worked for you. If you have any more questions or need further assistance in the future, feel free to reach out. Happy coding, and thank you for closing the issue! 🚀
