### ISSUE TITLE
Seems resume=False not work when using multi-gpu

### ISSUE THREAD

**Issue by Mactarvish** [ultralytics/ultralytics#8535]
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'v training a model till 154 epoch with 4 gpus, and I interupted it.
If I exec:
`yolo train data=hand.yaml model=runs/detect/train154/weights/last.pt epochs=300 imgsz=128 device=[2,3,4,5] resume=False`
It will resume training through `resume=False` set, but not without `device=4`.
Why it that?

**Comment by glenn-jocher** [comment]
@Mactarvish hello! Thanks for reaching out with your question. 🌟

When you specify `resume=False` along with a model path in the `model` argument, YOLOv8 is designed to load the weights from the specified model for training but not to resume training from the exact state (including epoch count, optimizer state, etc.) where it was interrupted. This behavior ensures that you can start a new training session with the weights of a previously trained model without continuing from the previous state.

However, when using multiple GPUs (`device=[2,3,4,5]`), it's possible that the internal mechanism for distributing the model across devices might inadvertently trigger the resume behavior due to how state dictionaries are loaded and synchronized across GPUs.

If you're looking to start fresh training without resuming, consider using the `--weights` argument to specify the path to your weights file, ensuring it's clear you're initiating a new training session with preloaded weights:

```bash
yolo train data=hand.yaml weights=runs/detect/train154/weights/last.pt epochs=300 imgsz=128 device=[2,3,4,5]
```

This approach should help clarify the intention to start a new training session rather than resuming the old one, even when using multiple GPUs.

Hope this helps! Let us know if you have any more questions.

**Comment by mandal4** [comment]
> @Mactarvish hello! Thanks for reaching out with your question. 🌟
> 
> When you specify `resume=False` along with a model path in the `model` argument, YOLOv8 is designed to load the weights from the specified model for training but not to resume training from the exact state (including epoch count, optimizer state, etc.) where it was interrupted. This behavior ensures that you can start a new training session with the weights of a previously trained model without continuing from the previous state.
> 
> However, when using multiple GPUs (`device=[2,3,4,5]`), it's possible that the internal mechanism for distributing the model across devices might inadvertently trigger the resume behavior due to how state dictionaries are loaded and synchronized across GPUs.
> 
> If you're looking to start fresh training without resuming, consider using the `--weights` argument to specify the path to your weights file, ensuring it's clear you're initiating a new training session with preloaded weights:
> 
> ```shell
> yolo train data=hand.yaml weights=runs/detect/train154/weights/last.pt epochs=300 imgsz=128 device=[2,3,4,5]
> ```
> 
> This approach should help clarify the intention to start a new training session rather than resuming the old one, even when using multiple GPUs.
> 
> Hope this helps! Let us know if you have any more questions.

Same issue here.
How can i resolve the issue with python script? (not CLI)

Thanks,
