### ISSUE TITLE
OBB 

### ISSUE THREAD

**Issue by dalin666daa** [ultralytics/ultralytics#8549]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When i check for the angle of rotation of the bounding box using xywhr , the value of r is always positive not specifying whether the roatation is clock wise or counter clock wise , is there any possible solutions??

**Comment by glenn-jocher** [comment]
@dalin666daa hello! 😊

The `r` value in `xywhr` format represents the rotation angle in radians, and it's indeed always positive as it measures the angle from the horizontal axis to the bounding box's major axis in a counter-clockwise direction. If you need to determine the direction of rotation (clockwise or counter-clockwise), you can consider angles greater than π (180 degrees) as clockwise rotations, since the range is typically from 0 to π for counter-clockwise rotations.

For example, if you have an angle `r`, you can interpret it as:
```python
if r > np.pi:
    print("Clockwise rotation")
else:
    print("Counter-clockwise rotation")
```

This approach is based on the convention that angles are measured in a counter-clockwise direction from the positive x-axis. If you're working with angles outside the 0 to 2π range, you might want to normalize them first.

Hope this helps! Let us know if you have any more questions.
