### ISSUE TITLE
visualize with OBB mode got a small problem

### ISSUE THREAD

**Issue by Benjaminlk-hanhan** [ultralytics/ultralytics#8564]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

  File "E:\python_interpreter\py39\lib\site-packages\ultralytics\utils\plotting.py", line 1030, in feature_visualization
    batch, channels, height, width = x.shape  # batch, channels, height, width
AttributeError: 'tuple' object has no attribute 'shape'

### Environment

Ultralytics YOLOv8.1.18 � Python-3.9.13 torch-2.0.1+cu118 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
Setup complete ✅ (16 CPUs, 15.9 GB RAM, 868.5/931.5 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.9.13
Install             pip
RAM                 15.87 GB
CPU                 AMD Ryzen 7 5800H with Radeon Graphics
CUDA                11.8

matplotlib          ✅ 3.7.0>=3.3.0

### Minimal Reproducible Example

model = YOLO('yolov8s-obb.yaml)
results = model.predict(source=img_path, visulize=True)

### Additional

fit this problem by add "OBB" to the ultralytics/utils/plotting.py at line 1026 in the feature_visualization func.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Benjaminlk-hanhan hey there! 👋 It looks like you've encountered an issue with visualizing features in OBB mode. Thanks for the detailed report and for checking the existing issues first!

Based on the error message you've shared, it seems there's a problem with expecting a tensor where a tuple is provided. Your suggestion to adjust the `feature_visualization` function in `ultralytics/utils/plotting.py` sounds like a good start.

For a quick fix, you might want to ensure that the input to the `feature_visualization` function is correctly handled as a tensor. If you're getting a tuple, it's possible that additional unpacking is needed before accessing the `.shape` attribute.

Here's a small tweak you can try:
```python
if isinstance(x, tuple):
    x = x[0]  # Assuming the tensor you need is the first element of the tuple
batch, channels, height, width = x.shape  # Proceed as before
```

This is just a quick workaround. For a more robust solution, examining why a tuple is returned instead of a tensor at this point in the code would be beneficial.

If you're comfortable with it and have identified a solid fix, contributions through a PR are always welcome! Even though you've indicated you might not be up for submitting a PR, if you change your mind, the community and the Ultralytics team would greatly appreciate it. 🚀

Let us know if this helps or if you have any more insights into the issue!
