### ISSUE TITLE
Question on the calculation of mAP

### ISSUE THREAD

**Issue by dyhBUPT** [ultralytics/ultralytics#8568]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I have a question on mAP calculation.

![image](https://github.com/ultralytics/ultralytics/assets/99722489/6976ff74-b57c-4b0b-bea4-79bae3aea6f2)

From the visiualized "PR_curve.png", I see that there is a straight line at the end of the curve.
This is equivalent to manually adding some boxes, and will brings an improvement on mAP.
Meanwhile, in that case, properly setting a higher `conf` threshold will yield a higher mAP than `conf=0`.

Is it a bug? Or am I mistaken? 
Looking forward to your reply~

**Comment by glenn-jocher** [comment]
@dyhBUPT hello! Thanks for reaching out with your question about mAP calculation and the observed behavior in the PR curve. 🌟

The straight line you're seeing at the end of the Precision-Recall (PR) curve is actually expected behavior, not a bug. This occurs due to the way precision is calculated at low recall levels, often when the model stops detecting objects (true positives) and mainly false positives contribute to the curve. It's a common characteristic of PR curves in object detection tasks.

Regarding the `conf` threshold, indeed, adjusting it can impact the mAP. A higher `conf` threshold can reduce the number of false positives, potentially increasing the mAP, but it might also miss some true positives. It's all about finding the right balance for your specific use case.

Here's a quick example on how you might adjust the `conf` threshold:

```python
results = model.predict(source='your_image_or_video.jpg', conf=0.25)  # Adjust conf threshold as needed
```

Remember, the optimal `conf` threshold can vary depending on your dataset and what you're trying to achieve. Experimenting with different values is key. Hope this helps! Let us know if you have any more questions. 😊

**Comment by dyhBUPT** [comment]
@glenn-jocher Hi, thanks for your reply and explanation. 😊
However, I think it is contrary to offcial definition of mAP by COCO.

Specifically, in ultralytics, the heads and tails of  `recall` and `precision` lists are padded with `0.0` and `1.0`, as follows: (that's the main reason of the phenomenon mentioned above)
https://github.com/ultralytics/ultralytics/blob/14dbfeab57cb042908b4ad3da43fcf3c05938dec/ultralytics/utils/metrics.py#L511-L512
However, in official [cocoapi](https://github.com/cocodataset/cocoapi/tree/master/PythonAPI), there is no such padding operations observed from its [core codes](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py).

Therefore, I think this difference will make the mAP from ultralytics a little higher than that from cocoapi.

BTW, there are some other minor differences between them:

- cocoapi [ensures](https://github.com/cocodataset/cocoapi/blob/8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9/PythonAPI/pycocotools/cocoeval.py#L398-L400) the monotony of the PR curve, ultralytics doesn't. 
- cocoapi uses the [sampled neighbor](https://github.com/cocodataset/cocoapi/blob/8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9/PythonAPI/pycocotools/cocoeval.py#L402-L408) `precision` values and [np.mean](https://github.com/cocodataset/cocoapi/blob/8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9/PythonAPI/pycocotools/cocoeval.py#L455) to calculate mAP, and ultralytics uses the [interpolation](https://github.com/ultralytics/ultralytics/blob/14dbfeab57cb042908b4ad3da43fcf3c05938dec/ultralytics/utils/metrics.py#L593) and [integral](https://github.com/ultralytics/ultralytics/blob/14dbfeab57cb042908b4ad3da43fcf3c05938dec/ultralytics/utils/metrics.py#L519-L521) instead.

**Comment by AnAccountOnGitHub** [comment]
1) The sentiel values were added in YOLOv5 to "bridge gap" between YOLOv5 and detectron2 in this [PR](https://github.com/ultralytics/yolov5/commit/8ac96b797538d6a5e882e56f9a48f3d015bcf952).

However, according to my tests, detectron2 is using pycocotools, which does not use the sentinel values. The sentinel values seem to inflate the mAP score as AUC is larger when the last PR value is connected linearly to the <0-precision, 1-recall> point instead of dropping to <0-precision, last recall value> (see the 1st row in Fig. 1).

Moreover, it leads to anomalies such as:

- when the confidence score (`conf`) increases, the mAP increases in ultralytics (see the 2nd row in Fig. 1)
- when the number of maximum detections per image is reduced (`max_det`), the mAP increases in ultralytics (see the 3rd row in Fig. 1)

![BBOX](https://github.com/ultralytics/ultralytics/assets/42294094/ad94850d-8ab2-434e-a0dc-44e2a09bb798)

For the PR curves shown in Fig. 1, mAP@0.50:0.95 are:
1st row: ultralytics: 0.48 vs pycocotools: 0.44
2nd row: ultralytics: 0.50 vs pycocotools: 0.41.
3rd row: ultralytics: 0.45 vs pycocotools: -1.

The abovementioned plots and mAP are for the bbox task on a custom dataset with many objects, including small ones.

2) Another mAP calculation question I have is why the segmentation mAP is computed on ground truths resized to match the predictions, i.e., might be upsampled before computing IOUs if using higher than native imgsz. In the bbox case, mAP is computed in native space, i.e., in the same space as the annotations.

**Comment by glenn-jocher** [comment]
@AnAccountOnGitHub Thank you for your detailed analysis! 🕵️ It's great to see such a deep dive into the mAP calculation differences between Ultralytics and pycocotools/cocoapi.

1) Regarding the use of sentinel values and their impact on mAP scores, your observations spotlight a crucial distinction in the PR curve's handling which indeed might influence the performance metrics. The original intent behind adding sentinel values was to ensure a consistent evaluation framework, but as you rightly pointed out through your tests and comparisons, it diverges from the pycocotools' approach.

I appreciate you bringing these anomalies to our attention. It's insights like these from our community that help us improve and refine our methods continuously. We'll revisit our mAP calculation process, specifically the use of sentinel values, to better align with established standards like pycocotools/cocoapi, ensuring accuracy and compatibility.

Regarding the impact on mAP with changes to `conf` and `max_det`, these observations suggest a reevaluation of how these parameters play into our scoring metrics, particularly in scenarios with numerous small objects.

2) On the calculation of segmentation mAP and its comparison with bbox mAP calculations: The choice to resize ground truths for segmentation tasks is aimed at maintaining fidelity to the model predictions. However, your point about consistency in mAP computation across bbox and segmentation highlights an area for standardization. We'll look into making our mAP computation more uniform across different tasks to ensure that performance metrics are reliably comparable.

We're grateful for your feedback and are committed to enhancing the reliability and trustworthiness of our models. Stay tuned for updates on these matters, and thanks again for contributing to the conversation! 🚀

**Comment by AnAccountOnGitHub** [comment]
The issue has not been resolved yet.

**Comment by glenn-jocher** [comment]
@AnAccountOnGitHub Thanks for following up! 😊 We're still looking into this to find the best solution. In the meantime, could you try adjusting the `conf` and `max_det` parameters slightly to see if that impacts your results as a temporary workaround? For example:

```python
results = model.predict(source='path/to/image.jpg', conf=0.25, max_det=100)
```

We'll update you as soon as we have a solid fix. Your patience and contributions are greatly appreciated!
