### ISSUE TITLE
If the int8 option is specified, the error "'_UserObject' object has no attribute 'inputs'" occurs.

### ISSUE THREAD

**Issue by Akira-Taniguchi** [ultralytics/ultralytics#8569]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I received an error when executing the following script in Google Colaboratory.

```
from google.colab import drive

drive.mount('/content/drive')
%cd /content/drive/MyDrive/test1/


!pip install tensorflowjs
!pip install ultralytics
!pip install tensorflow==2.13.1

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/ultralytics/runs/detect/train5/weights/best.pt")
model.export(format='tfjs', int8=True, half=True)
```

error log
```
TensorFlow GraphDef: starting export with tensorflow 2.13.1...
TensorFlow GraphDef: export failure ❌ 0.0s: '_UserObject' object has no attribute 'inputs'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-1-8ec0dfed288b>](https://localhost:8080/#) in <cell line: 14>()
     12 
     13 model = YOLO("/content/drive/MyDrive/ultralytics/runs/detect/train5/weights/best.pt")
---> 14 model.export(format='tfjs', int8=True, half=True)
     15 

5 frames
[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py](https://localhost:8080/#) in export_pb(self, keras_model, prefix)
    815 
    816         m = tf.function(lambda x: keras_model(x))  # full model
--> 817         m = m.get_concrete_function(tf.TensorSpec(keras_model.inputs[0].shape, keras_model.inputs[0].dtype))
    818         frozen_func = convert_variables_to_constants_v2(m)
    819         frozen_func.graph.as_graph_def()

AttributeError: '_UserObject' object has no attribute 'inputs'
```

From what I see in the logs below, the output of onnx and the conversion from onnx to saved_model appears to be successful.
Conversion from saved_model to tfjs appears to be failing
```
ONNX: export success ✅ 27.0s, saved as '/content/drive/MyDrive/ultralytics/runs/detect/train5/weights/best.onnx' (260.1 MB)
TensorFlow SavedModel: running 'onnx2tf -i "/content/drive/MyDrive/ultralytics/runs/detect/train5/weights/best.onnx" -o "/content/drive/MyDrive/ultralytics/runs/detect/train5/weights/best_saved_model" -nuo --verbosity info -oiqt -qt per-tensor'
TensorFlow SavedModel: export success ✅ 1221.0s, saved as '/content/drive/MyDrive/ultralytics/runs/detect/train5/weights/best_saved_model' (846.7 MB)
```

I get this error when I add the int8 option and the half option.
When only the format option is given, this error does not occur and the program exits normally.
https://docs.ultralytics.com/ja/modes/export/#arguments

```
model.export(format='tfjs') // success
model.export(format='tfjs', half=True) // success
model.export(format='tfjs', int8=True) // error
model.export(format='tfjs', int8=True, half=True) // error
```

tensorflowjs:4.17.0
ultralytics:8.1.20
tensorflow:2.13.1

### Additional

https://github.com/ultralytics/ultralytics/issues/869

I have identified a similar case, but it was not resolved.

**Comment by glenn-jocher** [comment]
@Akira-Taniguchi hello! Thanks for the detailed report and for checking the existing issues and discussions before posting. It seems like the error you're encountering is related to the `int8` quantization process when exporting to TensorFlow.js (tfjs) format. 

The `int8` and `half` options can sometimes introduce complexities, especially with TensorFlow.js, which might not fully support all conversion paths or quantization options in the same way as TensorFlow or other frameworks.

As a quick workaround, you might want to try exporting without `int8` quantization if precision is not your primary concern, or explore other export formats that fully support `int8` quantization. 

```python
model.export(format='tfjs')  # Without int8 and half for compatibility
```

We'll look into this issue further to understand the root cause and work on a fix. Your patience and contribution to improving YOLOv8 are greatly appreciated! 🙏

**Comment by Burhan-Q** [comment]
I'm able to reproduce this on my Win10 system.
```
Ultralytics YOLOv8.1.19 🚀 Python-3.10.9 torch-2.1.1+cu121 CPU (Intel Core(TM) i5-10600K 4.10GHz)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

tensorflowjs                 3.18.0
tensorflow                   2.13.1
onnx                         1.15.0
onnx-graphsurgeon            0.3.27
onnx2tf                      1.17.5
onnxruntime                  1.16.3
onnxsim                      0.4.35
tflite-support               0.1.0a1
torch                        2.1.1+cu121
torchvision                  0.16.1+cu121
```
![image](https://github.com/ultralytics/ultralytics/assets/62214284/db7a991e-c6ec-410d-9b40-f3f941c5b068)

**Comment by Burhan-Q** [comment]
I will admit I have very little understanding of the `export` code and `tensorflow`, but I ran thru some testing and found that after the export fails, I have a directory named `yolov8n_saved_model` in the working path. Following the traceback error, I did the following (after some poking around) and wanted to share my findings in case they're helpful:

```py
import tensorflow as tf

model = tf.saved_model.load("yolov8n_saved_model", tags=None, options=None)

sig = getattr(model, "signatures")
sig._signatures.get("serving_default").inputs[0]

>>> TensorShape([1, 640, 640, 3])
```

Which was what it _appears_ is being attempted with `keras_model.inputs[0].shape` https://github.com/ultralytics/ultralytics/blob/14dbfeab57cb042908b4ad3da43fcf3c05938dec/ultralytics/engine/exporter.py#L817

That said, I'm not sure if this is a viable solution for the long term, because I don't know how far back this works. On introspection of the `model` object, I did not see an `input` attribute. The same goes when replicating https://github.com/ultralytics/ultralytics/blob/14dbfeab57cb042908b4ad3da43fcf3c05938dec/ultralytics/engine/exporter.py#L816
however I used a _new_ variable for the output, but this too did not have an `inputs` attribute.
