### ISSUE TITLE
TensorRT engine verbose=False will not turn off output

### ISSUE THREAD

**Issue by keaneflynn** [ultralytics/ultralytics#8603]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

Hello! I just got some code running using a tensorRT engine through yolov8 and it is doing its job very well, however I am running into an issue with it forcing a verbose output despite using the verbose=False argument. I am currently not sure if this is something that I should address to a tensorRT issue page or here, but I figure I would post here.

Code block:

```
import cv2
from ultralytics import YOLO


imageFile = 'test.jpg'
modelFile = 'model.engine'
image = cv2.imread(imageFile)
color = (255, 255, 255)


model = YOLO(modelFile, task='detect',)
classList = ['dog']
result = model.predict(imageFile, conf = 0.2, iou=0.3, device = 0, 
                       half=True, imgsz=416, verbose = False)

for detection in result:
    data = detection.boxes.data 
    list = data.tolist()
    for object in list:
        bbox = [int(i) for i in object[0:4]]
        conf = object[4]
        classes = classList[int(object[5])]
        output = [bbox, conf, classes]
        label = "ID: " + str(output[2]) + "; conf: " + str(round(output[1], 2))

        cv2.rectangle(image, output[0][0:2], output[0][2:4], color, 2)
        cv2.putText(image, label, (output[0][0], output[0][3] + 30), 
                    cv2.FONT_HERSHEY_SIMPLEX, 1, color, 2)


cv2.imshow("Detections", image)
cv2.waitKey(0)
```

Regardless of the verbose=False argument, I will always get the following CLI output:

```
Loading fish.engine for TensorRT inference...
[03/02/2024-11:38:50] [TRT] [I] The logger passed into createInferRuntime differs from one already provided for an existing builder, runtime, or refitter. Uses of the global logger, returned by nvinfer1::getLogger(), will return the existing value.

[03/02/2024-11:38:50] [TRT] [I] Loaded engine size: 7 MiB
[03/02/2024-11:38:56] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +343, GPU +138, now: CPU 1319, GPU 6276 (MiB)
[03/02/2024-11:38:56] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +6, now: CPU 0, GPU 6 (MiB)
[03/02/2024-11:38:56] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +1, now: CPU 1312, GPU 6277 (MiB)
[03/02/2024-11:38:57] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +7, now: CPU 0, GPU 13 (MiB)
```

While this doesn't hang my code at all, the output from this code will be sent to an error log so for deployment so I don't want this to clog the error file. Is this something that can be appended on the ultralytics side of things or should I try to modify tensorRT source files to figure out how to suppress this output. Thank you for your help with this issue

### Environment

Hardware & software components:
Nvidia Jetson Xavier nx
ubuntu 20.04
ultralytics version == 8.1.20
python version == 3.8.10
torch version == 2.1.0
torchvision == 1.16.1

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@keaneflynn hey there! 👋 It looks like the verbose output you're seeing is actually coming from TensorRT's internal logging mechanism rather than the Ultralytics YOLOv8 library. The `verbose=False` parameter in YOLOv8 controls the verbosity of the YOLOv8 library itself, but TensorRT's logging behavior is managed separately.

To reduce the verbosity of TensorRT, you can adjust the TensorRT logger's severity level. Here's a quick example on how you might do this:

```python
import tensorrt as trt

# Create a TensorRT logger object with desired severity level
TRT_LOGGER = trt.Logger(trt.Logger.WARNING)  # This sets the logger to capture only warnings and errors

# Pass this logger when creating your TensorRT runtime, for example:
# runtime = trt.Runtime(TRT_LOGGER)
```

Adjusting the severity level to `trt.Logger.WARNING` or `trt.Logger.ERROR` should help reduce the amount of log output you're seeing. Unfortunately, this adjustment needs to be made within the context of how you're loading and using the TensorRT engine in your application, which might require some custom handling if you're using YOLOv8's high-level APIs.

If you're directly managing TensorRT engine loading and inference in parts of your code, you'll have the flexibility to specify the logger as shown. However, if this logging is happening within a part of the YOLOv8 library that abstracts away the direct TensorRT engine manipulation, it might be a bit more challenging to control.

Hope this helps clear things up! If you have any more questions or run into further issues, feel free to reach out. 😊

**Comment by keaneflynn** [comment]
@glenn-jocher 
Unfortunately no dice there, seems like its happening on tensorRT end of things so hopefully someone in their forums can point me in the right direction. I appreciate the quick response! If there is ever a way to work this into yolov8 code it would be a good add! Might make a pull request in the future.

**Comment by glenn-jocher** [comment]
@keaneflynn Thanks for the update! 🙌 It does sound like a TensorRT-specific issue, and reaching out to their forums is a great move. We're always open to community contributions, so if you find a neat solution or have ideas on integrating a fix into YOLOv8, we'd warmly welcome a pull request from you. Good luck, and looking forward to potentially collaborating in the future!
