### ISSUE TITLE
Dimensions of the results vary when no object is detected

### ISSUE THREAD

**Issue by hdnh2006** [ultralytics/ultralytics#8635]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

Hello Ultralytics team,

Thank you for creating such an excellent framework.

I've encountered what appears to be a bug in the `predict` engine when no object is detected.

I'm attempting to predict across various images while leveraging batch size. However, when predicting on a fully black image, the dimensions of the results seem to change, preventing access to the first element of the list using `results[1][0]`.

Could you please run the example below? You will see the issue I'm referring to. My goal is to develop a universal parser for the results, but the inconsistent dimensions I am getting make this impossible.

Am I missing something?

### Environment

```
Ultralytics YOLOv8.1.19 🚀 Python-3.10.12 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 4060 Laptop GPU, 7940MiB)
Setup complete ✅ (16 CPUs, 14.9 GB RAM, 713.5/937.3 GB disk)
```

### Minimal Reproducible Example

``` 
import numpy as np
from ultralytics import YOLO

model = YOLO('yolov8n.pt')

img1 = 'https://raw.githubusercontent.com/ultralytics/ultralytics/main/ultralytics/assets/zidane.jpg'
img2 = np.zeros((640, 640, 3), dtype=np.uint8)

results = model([img1, img2])

print(results[0][0]) # everything goes well

print(results[1][0])
Traceback (most recent call last):

  Cell In[13], line 1
    print(results[1][0])

  File ~/.virtualenvs/yolo/lib/python3.10/site-packages/ultralytics/engine/results.py:126 in __getitem__
    return self._apply("__getitem__", idx)

  File ~/.virtualenvs/yolo/lib/python3.10/site-packages/ultralytics/engine/results.py:163 in _apply
    setattr(r, k, getattr(v, fn)(*args, **kwargs))

  File ~/.virtualenvs/yolo/lib/python3.10/site-packages/ultralytics/engine/results.py:63 in __getitem__
    return self.__class__(self.data[idx], self.orig_shape)

IndexError: index 0 is out of bounds for dimension 0 with size 0
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@hdnh2006 hello there! 🌟

Thank you for bringing this to our attention and for the kind words about our framework. It seems like you've stumbled upon a scenario where the predict engine behaves differently when no objects are detected in an image. This is indeed expected behavior, as the results list will be empty if no objects are found, leading to the `IndexError` you encountered.

A simple workaround is to check if the results list is empty before trying to access its elements. Here's a quick example:

```python
if len(results[1]) > 0:
    print(results[1][0])
else:
    print("No objects detected in the second image.")
```

This way, you can safely handle cases where no objects are detected without running into errors. Hope this helps, and happy coding with YOLOv8! 🚀
