### ISSUE TITLE
the mAP is low with pretrain

### ISSUE THREAD

**Issue by alicera** [ultralytics/ultralytics#864]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

```
yolo detect train data=custom.yaml model=yolov8s.pt epochs=100 imgsz=640 batch=16 device=0,1,2,3
```
I train the custom dataset about the person.
I already train the 30 epoch and  the validatioin mAP is 0.247.
Is it correct ?
I check the runs/detec/train/train_batch0.jpg. Its detect is ok.

**Comment by AyushExel** [comment]
This most likely means that your dataset isn't optimal. Try increasing the number of images in the dataset

**Comment by alicera** [comment]
I already try the it on the yolov5. The performance is great and the mAP is high (0.5 above) for the begin.
BTW I dont change the training format on yolov8. It was follow by yolov5 format.

**Comment by alicera** [comment]
So  I try to val it
```
yolo detect val data=custom.yaml model=last.pt
```
The result mAP 0.5 is higher than training validation mAP 0.26

**Comment by pderrenger** [comment]
@alicera the difference in mAP between training and validation is unusual. This could be due to overfitting or insufficient training data. It's also important to ensure that the data split between training and validation is representative of the entire dataset. To address this, you may consider additional data augmentation techniques during training and the inclusion of more diverse data in your dataset.
