### ISSUE TITLE
Cannot download ImageNet dataset 

### ISSUE THREAD

**Issue by lingchen1991** [ultralytics/ultralytics#867]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I try to run the yolov8-cls but the ImageNet dataset cannot be downloaded by the link https://github.com/ultralytics/yolov5/releases/download/v1.0/ImageNet.yaml.zip

**Comment by pderrenger** [comment]
@lingchen1991 hi there! It seems like you're encountering trouble downloading the ImageNet dataset for YOLOv8. The ImageNet dataset is automatically downloaded on the first use of the model rather than being directly obtained from a specific link. When running YOLOv8, the required datasets like ImageNet, COCO, and VOC are automatically fetched to your local machine. No manual download or specific URL is needed for the ImageNet dataset. Once the YOLOv8 model is loaded using Python, it will handle the dataset retrieval for you. If you encounter any further issues, feel free to ask! 😊
