### ISSUE TITLE
Rocky Linux Red Hat is not executing the IP Stream on yolov8 : assert cap.isOpened(), f'{st}Failed to open {s}'

### ISSUE THREAD

**Issue by faizanengineer** [ultralytics/ultralytics#8683]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

source=rtsp://stream:streamxxxxxxxxxxxxxxxxxxxxx, imgsz=[640, 640], conf_thres=0.3, iou_thres=0.3, max_det=1000, device=, show_vid=True, save_txt=False, save_conf=False, save_crop=False, save_trajectories=False, save_vid=True, nosave=False, classes=[0], agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/track, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, hide_class=False, half=False, dnn=False, vid_stride=1, retina_masks=False
/home/ottica/.conda/envs/yolo/lib/python3.10/site-packages/torch/cuda/__init__.py:141: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
  
  
Ultralytics YOLOv8.0.20 🚀 Python-3.10.13 torch-2.2.1+cu121 CPU
YOLOv8s summary (fused): 168 layers, 11156544 parameters, 0 gradients, 28.6 GFLOPs
[ WARN:0@31.912] global cap_ffmpeg_impl.hpp:453 _opencv_ffmpeg_interrupt_callback Stream timeout triggered after 30038.432457 ms

Traceback (most recent call last):
  File "/home/ottica/Downloads/People Counter updated/People Counter/track.py", line 790, in <module>
    main(opt)
  File "/home/ottica/Downloads/People Counter updated/People Counter/track.py", line 785, in main
    run(**vars(opt))
  File "/home/ottica/.conda/envs/yolo/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ottica/Downloads/People Counter updated/People Counter/track.py", line 485, in run
    dataset = LoadStreams(
  File "/home/ottica/Downloads/People Counter updated/People 
  
  Counter/yolov8/ultralytics/yolo/data/dataloaders/stream_loaders.py", line 47, in __init__
    assert cap.isOpened(), f'{st}Failed to open {s}'
AssertionError: 1/1: rtsp://stream:streamxxxxxxxxxxxxxxxxxxxxx... Failed to open rtsp://stream:streamxxxxxxxxxxxxxxxxxxxxx

### Additional

I am using the YOLOv8 program to detect persons, and it works seamlessly on my Windows system. However, when I try to run the same program on Rocky Linux, I encounter an error: 'assert cap.isOpened(), f'{st}Failed to open {s}'.' I have verified that the IP address is correct and functional on all other devices.

**Comment by glenn-jocher** [comment]
@faizanengineer hello! It looks like you're encountering an issue with opening an RTSP stream on Rocky Linux using YOLOv8. This problem might be related to the OpenCV backend used for video streaming. Here are a couple of suggestions that might help:

1. **Verify OpenCV's RTSP Support**: Ensure that your OpenCV installation supports RTSP streams. This often requires having FFmpeg compiled with your OpenCV build. You can check this by running a simple OpenCV script to open and display the stream.

    ```python
    import cv2

    cap = cv2.VideoCapture('rtsp://stream:streamxxxxxxxxxxxxxxxxxxxxx')
    if cap.isOpened():
        print("Stream opened successfully")
    else:
        print("Failed to open stream")
    ```

2. **FFmpeg Compatibility**: Since the error mentions a stream timeout and CUDA initialization warnings, it might be worth ensuring that FFmpeg (used by OpenCV for RTSP streams) is correctly installed and compatible with your hardware. You might also want to check if there are any firewall or network issues that could be blocking the stream on Linux.

3. **CUDA Error**: The CUDA error might be unrelated but ensure your hardware is compatible with the CUDA version you're using. It seems like there might be a mismatch or an initialization issue. Running some CUDA diagnostic tools or ensuring your GPU drivers and CUDA toolkit are up to date could help.

4. **Permissions**: On Linux systems, there might be permissions issues accessing network streams. Ensure your user has the necessary permissions or try running the script with `sudo` to rule out permission-related problems.

5. **Alternative Approaches**: As a workaround, you could try using a different method to capture the RTSP stream, such as using GStreamer (if supported by your OpenCV build) or capturing the stream to a file and then processing the file with YOLOv8.

If these suggestions don't resolve the issue, it might be helpful to provide more details about your OpenCV installation, especially regarding FFmpeg support, and any additional error messages related to the CUDA warning. This could offer more clues into what's going wrong. 😊
