### ISSUE TITLE
Issue with Saving YOLOv8 Object Detection Results per class

### ISSUE THREAD

**Issue by wesalawida** [ultralytics/ultralytics#8685]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://github.com/ultralytics/ultralytics/assets/59606326/0bd720b8-4b13-4983-9f33-ea84752ed535)
I'm currently testing my project on object detection using YOLOv8. When attempting to save the detection results using the provided code, I'm only able to retrieve metrics of means. However, I need to save the actual detection results per class and not the mean.
this is my code:
        detections = self.model.val(project=output_path, name="results", split="test", save_json=True, mode='val')
        res = detections.results_dict 
and its gives me just this :
metrics/precision(B) | metrics/recall(B) | metrics/mAP50(B) | metrics/mAP50-95(B) | fitness
0.692672 | 0.706036 | 0.73772921 | 0.518766432 | 0.54066271

**Comment by glenn-jocher** [comment]
@wesalawida hello! 👋 It looks like you're interested in saving the detection results per class. The code snippet you've provided is indeed geared towards validation metrics. To save individual detection results, including per-class information, you might want to use the `predict` mode instead of `val`. Here's a quick example on how you could approach this:

```python
# Assuming 'self.model' is your YOLOv8 model loaded with YOLO('path/to/model.pt')
results = self.model.predict(source='path/to/your/images', save_txt=True, save_conf=True)
```

This will save the detections in `.txt` files with class IDs, confidence scores, and bounding box coordinates for each detected object. The files will be saved in the same directory as your images, under a `labels` folder.

If you're looking to work directly with the detection results in your code, you can iterate through `results`:

```python
for result in results:
    print(result.boxes, result.classes, result.confidences)
```

This will give you access to the bounding boxes, class IDs, and confidence scores for each detection. Hope this helps! Let us know if you have any more questions. 😊

**Comment by wesalawida** [comment]
I am using validation because I need all the statistics. Therefore, after finishing training, I need the model to go through the test folder and provide me with the metrics including MAP50, precision, and recall for the comparison between the predictions made by the trained model and the actual labels we have in the test folder.

**Comment by glenn-jocher** [comment]
@wesalawida hi there! 👋 It sounds like you're on the right track with using the `val` mode for gathering comprehensive statistics. If you're looking to obtain detailed metrics like mAP50, precision, and recall specifically for your test dataset, you can indeed use the `val` mode with your test data by specifying the `data` argument to point to your test dataset configuration file. Here's a quick example:

```python
results = self.model.val(data='path/to/your_test_data.yaml', task='test')
```

Make sure your test dataset configuration file (`your_test_data.yaml`) is correctly set up with paths to your test images and labels. This way, the model will evaluate against the test set and provide you with the detailed metrics you're looking for.

Hope this helps! Let us know if you have any further questions. 😊
