### ISSUE TITLE
Why yolov8 starts parallel process automatically while start training, validation, and testing in C++.

### ISSUE THREAD

**Issue by KaranPadaraiya** [ultralytics/ultralytics#8710]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have implemented YOLOv8 for my application, it is working perfectly fine in python. this python file contains a class named "ProductDetection" so using this call I can do train and test on custom dataset. whenever this class is called in python file it is working properly.

now I want to do the same by calling this class "ProductDetection" in c++ code. for that I make wrapper.pyd and load it to c++ code.I have done all python setup for c++ implementation. in C++ code it is working till train step. at the time of training starts it multiple parallel processes stats and continuous till full cpu memory is used. ![1](https://github.com/ultralytics/ultralytics/assets/103854623/62e4409c-0c9f-48e1-9a36-35810c86ee0b) 

here is my python train function:

```

def Train(self, freeze=0, recipe_name="dummy"):
    with self.lock:
        recipe_set_path = os.path.join(self.recipe_path, str(recipe_name))
        self.model.train(data=self.data_path,
                         epochs=self.epochs,
                         time=0.5,
                         patience=10,
                         batch=self.batch_size,
                         imgsz=self.image_size,
                         cache=False,
                         save=True,  
                         resume=False,
                         name=recipe_set_path,
                         exist_ok=True,
                         device=self.device,
                         workers=0,
                         seed=42,
                         single_cls=True,
                         close_mosaic=0,
                         profile=True,
                         freeze=0,
                         plots=False)
        return
```

train function in c++:
```


bool TrainDET(std::string recipe_name, float freez_layer, bool cache, bool profile) {
#ifndef _DEBUG
	PyGILState_STATE gstate;
	gstate = PyGILState_Ensure();
	PyObject* pcache = cache ? Py_True : Py_False;
	PyObject* pprofile = profile ? Py_True : Py_False;

	PyObject* result = PyObject_CallMethod((PyObject*)pInstance, "Train", "(sfOO)", recipe_name.c_str(), freez_layer, pcache, pprofile);
	if (!result) {
		PyErr_Print();
		Py_DECREF(result);
		PyGILState_Release(gstate);
		return false;
	}
	Py_DECREF(result);
	PyGILState_Release(gstate);
#endif
	return true;
}
```
c++ main function:

```
int main() {

	Py_Initialize();

	PyEval_InitThreads(); // Initialize Python's Global Interpreter Lock (GIL) for single-threaded execution

	PyInitialize(true);

	GetPyInstance(4, 2, 640, 640, "mywrapper");

	std::string recipe_model_path = "C:\\Users\\Karan\\Documents\\Visual Studio 2015\\Projects\\testwrapper\\testwrapper\\DATA\\Models\\Blisbeat_BlisterTopA\\";

	SetDETPath(recipe_model_path, "C:\\Users\\Karan\\Documents\\Visual Studio 2015\\Projects\\testwrapper\\testwrapper\\DATA\\BASE_DATASET\\data.yaml", "DATA\\DL\\det_model.pt");

	LoadDLModel("dummy");

	TrainDET("Unknown", 0, false, true);
return 0;

```

in this first I initialize python in cpp, the get instance of python class. then use different function to train and test in my dataset at  given path.
problem start at "TrainDET("Unknown", 0, false, true);"
in this step multiple parallel processes starts in taskmanager  as shown in image above.

**Comment by glenn-jocher** [comment]
@KaranPadaraiya hello! It looks like you're encountering an issue where initiating training from C++ spawns multiple parallel processes, leading to full CPU memory usage. This behavior is typically related to the multiprocessing mechanism used by PyTorch for data loading.

In your Python `Train` function, you've set `workers=0`, which should disable multiprocessing and use the main process for data loading. However, if you're still seeing multiple processes, it might be due to the environment or how the Python interpreter is initialized and interacted with in your C++ code.

A few things you might consider:

1. Ensure that your environment variables related to multiprocessing, such as `OMP_NUM_THREADS`, are appropriately set in your C++ environment before initializing the Python interpreter. This can help control the number of threads used by underlying libraries.

2. Review how the Python GIL (Global Interpreter Lock) is managed in your C++ code. Improper handling might lead to unexpected behavior when interfacing with Python.

3. If possible, try to isolate and reproduce the issue in a simpler Python script without involving C++. This can help determine if the problem lies in the Python-to-C++ interaction or within the Python code itself.

4. As a workaround, you might consider running your training process as a separate system call from C++ rather than directly interfacing with Python. This can sometimes offer more predictable behavior regarding process and thread management.

Here's a simplified example of how you might call your Python script from C++:

```cpp
#include <cstdlib>

int main() {
    system("python path/to/your_script.py");
    return 0;
}
```

This approach bypasses direct embedding of the Python interpreter in your C++ application but requires your environment to be correctly set up for command-line execution of Python scripts.

I hope this helps! If you continue to face issues, providing more details about your environment and any error messages could be beneficial. 🛠️

**Comment by glenn-jocher** [comment]
@KaranPadaraiya Thanks for the update! It indeed sounds like the issue is tied to the interaction between CPython and multiprocessing. Since options 1 and 2 didn't work out, and considering Python alone works fine, it reinforces the idea that the C++ integration might be the root cause. 

A potential workaround, as mentioned, is to call your Python script from C++ as a separate process. This approach sidesteps the direct embedding complexities and multiprocessing issues. Here's a quick example:

```cpp
#include <cstdlib>

int main() {
    system("python path/to/your_script.py");
    return 0;
}
```

This method ensures your Python environment, which works correctly on its own, is utilized without interference. Let's keep troubleshooting together, and feel free to share any further insights or questions you might have! 🛠️

**Comment by glenn-jocher** [comment]
@KaranPadaraiya hey there! 🌟 It looks like you've pinpointed the issue to the `select_device` function in `torch_utils.py`, where the call to `get_cpu_info()` leads to spawning subprocesses when invoked from C++. This behavior is due to the way `cpuinfo` handles information gathering outside of a main Python process.

A quick workaround could be to modify the `get_cpu_info_json()` function in your local `cpuinfo` library to prevent it from spawning subprocesses when called from your C++ integration. You might consider bypassing the subprocess call by directly fetching the CPU info without using `Popen`. Here's a simplified example:

```python
def get_cpu_info_json():
    '''
    Returns the CPU info directly without spawning subprocesses.
    '''
    import json
    info = _get_cpu_info_internal()
    output = json.dumps(info)
    return output
```

This modification ensures that `get_cpu_info_json()` returns the CPU information directly, avoiding the creation of subprocesses that lead to the issue you're experiencing.

Remember, this is a workaround, and modifying third-party libraries directly might not be the best long-term solution. It could be beneficial to explore why your C++ integration requires calling this Python code and if there's a way to manage device selection differently in your setup.

Hope this helps! Let me know if you have any more questions. 😊

**Comment by Shreejan-git** [comment]
I am using YOLO in python. No C++. But upon running the detect function for an image, all of the cores (12 in my case) goes to 100%.

**Comment by glenn-jocher** [comment]
It sounds like the issue might be related to the number of workers used for data loading. Try setting `workers=0` in your `detect` function to see if it reduces CPU usage.

**Comment by Shreejan-git** [comment]
I already did that yet the result was same.

**Comment by Y-T-G** [comment]
`ultralytics` would try to utilize all the CPU resources when running Inference on CPU unless you put a limit on the FPS manually.
