### ISSUE TITLE
Load custom trained yolov9c model on CPU and clearML: AttributeError: Can't get attribute 'RepNCSPELAN4'

### ISSUE THREAD

**Issue by manuelgutierrezchaves** [ultralytics/ultralytics#8711]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

Hello, I'm trying to load a custom trained yolov9c.pt model on clearml on CPU but it's giving me this error:
```
Traceback (most recent call last):
  File "/root/.clearml/venvs-builds/3.10/code/validate_clearml.py", line 172, in <module>
    validate(args.project_name,
  File "/root/.clearml/venvs-builds/3.10/code/validate_clearml.py", line 124, in validate
    model = YOLO(model_file)
  File "/root/.clearml/venvs-builds/3.10/lib/python3.10/site-packages/ultralytics/engine/model.py", line 134, in __init__
    self._load(model, task=task)
  File "/root/.clearml/venvs-builds/3.10/lib/python3.10/site-packages/ultralytics/engine/model.py", line 215, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/root/.clearml/venvs-builds/3.10/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 709, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/root/.clearml/venvs-builds/3.10/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 634, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
  File "/root/.clearml/venvs-builds/3.10/lib/python3.10/site-packages/clearml/binding/frameworks/__init__.py", line 36, in _inner_patch
    raise ex
  File "/root/.clearml/venvs-builds/3.10/lib/python3.10/site-packages/clearml/binding/frameworks/__init__.py", line 34, in _inner_patch
    ret = patched_fn(original_fn, *args, **kwargs)
  File "/root/.clearml/venvs-builds/3.10/lib/python3.10/site-packages/clearml/binding/frameworks/pytorch_bind.py", line 279, in _load
    model = original_fn(f, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/root/.clearml/venvs-builds/3.10/lib/python3.10/site-packages/clearml/binding/frameworks/__init__.py", line 30, in _inner_patch
    return original_fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'RepNCSPELAN4' on <module 'ultralytics.nn.modules.block' from '/root/.clearml/venvs-builds/3.10/lib/python3.10/site-packages/ultralytics/nn/modules/block.py'>
ClearML Monitor: GPU monitoring failed getting GPU reading, switching off GPU monitoring
```

I can load the same model in the same docker image on GPU and CPU without clearML, so I don't understand what's going on. This is the Dockerfile I'm using:
```
FROM pytorch/pytorch:1.13.1-cuda11.6-cudnn8-runtime

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install ffmpeg libsm6 libxext6 git curl wget build-essential -y
RUN pip install --upgrade pip

RUN git clone https://github.com/ultralytics/ultralytics /ultralytics/
# RUN pip install -r /ultralytics/requirements.txt
RUN pip install -e /ultralytics/.

COPY ./requirements.txt /app/
RUN pip install -r /app/requirements.txt
RUN rm /app/requirements.txt
RUN pip install -U ultralytics sahi
WORKDIR /app/
COPY ./app/ /app/

# ClearML
RUN clearml-init < ./clearML_server/cfg_clearML.conf

# Si no, lo descarga cada vez que carga modelo clasificacion
ADD https://ultralytics.com/assets/Arial.ttf https://ultralytics.com/assets/Arial.Unicode.ttf /root/.config/Ultralytics/

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3000"]
```

### Environment

Ultralytics YOLOv8.1.23 🚀 Python-3.10.8 torch-1.13.1 CUDA:0 (NVIDIA GeForce RTX 2060 SUPER, 7979MiB)
Setup complete ✅ (8 CPUs, 15.6 GB RAM, 359.9/438.5 GB disk)

### Minimal Reproducible Example

```
from ultralytics import YOLO
model = YOLO("/app/weights/" + model_name)
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@manuelgutierrezchaves hello! It seems like you're encountering an issue with loading a custom-trained YOLOv9c model on CPU with ClearML due to an `AttributeError`. This error typically occurs when the environment where the model is being loaded does not have access to the custom classes or modules used during training. 

Given that you're able to load the same model without ClearML, the issue might be related to the environment setup in ClearML. Here are a couple of suggestions that might help:

1. **Ensure Consistency in Environment:** Make sure that the environment (Python, PyTorch versions, and other dependencies) in which you're trying to load the model with ClearML matches the environment where the model was trained. Discrepancies here can lead to such errors.

2. **Custom Classes:** If your model training involved custom classes or modules (like `RepNCSPELAN4`), ensure that these are accessible in the environment where you're trying to load the model. This might involve adjusting your Dockerfile or ClearML setup to include these custom modules.

3. **ClearML Environment:** Double-check your ClearML environment setup. You might need to explicitly specify the environment (Python packages and versions) in ClearML to match your training environment.

Here's a quick example of how you might adjust your Dockerfile to ensure custom modules are included, assuming `RepNCSPELAN4` is a part of your project:

```Dockerfile
# Assuming 'my_custom_module.py' contains the 'RepNCSPELAN4' class
COPY ./my_custom_module.py /app/
```

And ensure it's imported correctly in your application where you're loading the model.

If these suggestions don't resolve the issue, it might be helpful to reach out to the ClearML community or support for more specific guidance on integrating with custom-trained models and environments.

Hope this helps! If you have further questions or run into more issues, feel free to ask. 🌟

**Comment by manuelgutierrezchaves** [comment]
Thanks, I fixed it now, clearML was using a different version of ultralytics than the one on the docker image for some reason.

**Comment by glenn-jocher** [comment]
@manuelgutierrezchaves great to hear you've resolved the issue! 😊 It's quite common for environment mismatches to cause such problems, especially when working with complex setups like Docker and ClearML. If you encounter any more challenges or have questions, feel free to reach out. Happy coding! 🚀
