### ISSUE TITLE
mask.xy[0] is extremely slow if mask.cpu() is applied first.

### ISSUE THREAD

**Issue by Sharpz7** [ultralytics/ultralytics#8732]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

Basically, if you apply the `mask.cpu()` method and then try and access `mask.xy[0]`, it increases the time from `0.36 ms per frame` to `11.89 ms per frame`. This is a massive increase.

I would imagine a change to the docs would work short term, and a change in the codebase long-term to avoid this slow-down.

### Minimal Reproducible Example

```python

results = predict(...)

for result in results:
    mask = mask.cpu() # This line needs to be removed for speedup.
    points = mask.xy[0]
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Sharpz7 thank you for bringing this to our attention! 🌟

The slowdown you're experiencing when calling `mask.cpu()` before accessing `mask.xy[0]` is indeed significant. This happens because transferring data from GPU to CPU can be a costly operation, especially if done repeatedly in a loop for each frame.

A quick workaround is to access `mask.xy[0]` while the mask is still on the GPU and only transfer the final, processed data to the CPU if necessary. Here's a revised snippet:

```python
results = predict(...)

for result in results:
    points = result.masks.xy[0]  # Keep the operation on GPU
    # Convert points to CPU here if needed
```

For a long-term solution, we'll consider optimizing this behavior and updating the documentation to highlight the performance impact of `.cpu()` calls. Your feedback is invaluable, and we appreciate your patience as we work on improving YOLOv8!

**Comment by Sharpz7** [comment]
Hmmm. I did imagine it was something like this,  but since I can then use the value `points` with variables on the CPU and still have faster results.

I imagine this is a consequence of only that variable being carried over vs the whole thing? 

Regardless, I think what you've suggested is perfect. Thank you ;))

**Comment by glenn-jocher** [comment]
@Sharpz7 absolutely, you've got it right! 🌟 When you transfer just the specific data you need (like `points`) to the CPU rather than the entire dataset, you minimize the overhead, leading to better performance. It's all about finding that sweet spot between necessary data transfer and maintaining speed. Glad the suggestion fits your needs, and thanks for reaching out with your question! Happy coding! 😊
