### ISSUE TITLE
Yolov8 iOS How to interpret and scale pose keyPoint and bounding box values ?

### ISSUE THREAD

**Issue by pbanavara** [ultralytics/ultralytics#8740]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello folks,
  I am trying to get the pose keypoints drawn on iOS using a few options
  

-   Modify the exporter python function to include the nms pipeline so that the keypoints are available. 
-  Use ONNX export and try to draw the keypoints from the onnx output

Right now focusing on option 2 since it's taking a while to figure out the pipeline functionality for option 1.
So far I am able to get the keypoints from the onnx model output. However I need help in interpreting these values

Here is my swift code
```
guard let modelPath = Bundle.main.path(forResource: "yolov8n-pose-pre", ofType: "onnx") else {
            fatalError("Model file not found")
        }
        guard
            let input_image_url = Bundle.main.url(forResource: "IMG_0688", withExtension: "jpeg")
        else {
            fatalError("Failed to get image URL")
        }
        let inputData = try Data(contentsOf: input_image_url)
        let inputDataLength = inputData.count
        let inputShape = [NSNumber(integerLiteral: inputDataLength)]
        let inputTensor = try ORTValue(tensorData: NSMutableData(data: inputData), elementType:ORTTensorElementDataType.uInt8, shape:inputShape)

        let ortEnv = try ORTEnv(loggingLevel: ORTLoggingLevel.info)
        let ortSessionOptions = try ORTSessionOptions()
        try ortSessionOptions.registerCustomOps(functionPointer: RegisterCustomOps)
        let ortSession = try ORTSession(
            env: ortEnv, modelPath: modelPath, sessionOptions: ortSessionOptions)
        let inputNames = try ortSession.inputNames()
        let outputNames = try ortSession.outputNames()
        let outputs = try ortSession.run(
            withInputs: [inputNames[0]: inputTensor], outputNames: Set(outputNames), runOptions: nil)
        
        // If the image is specified as the output layer in the model
        /*
        guard let outputTensor = outputs[outputNames[1]] else {
            fatalError("Failed to get model output from inference.")
        }
         */
        guard let outputTensor = outputs[outputNames[0]] else {
            fatalError("Failed to get model keypoint output from inference.")
        }
```
The model is obtained from [here](https://onnxruntime.ai/docs/tutorials/mobile/pose-detection.html) The preandpost processing model.

I get the outputTensor which has a shape (1, 57) inline with the expectations. 4 bounding box coords, 1 score, 1 class and 51 keypoints (17 * 3)

When I print the contents of the Tensor I see this

```
[0, 53, 17, 69, 81, 117, 93, 69, 224, 188, 38, 69, 76, 188, 87, 69, 118, 114, 90, 63, 0, 0, 0, 0, 163, 142, 188, 68, 167, 106, 45, 69, 18, 103, 50, 63, 176, 93, 202, 68, 105, 65, 38, 69, 196, 0, 9, 63, 30, 106, 179, 68, 137, 126, 41, 69, 108, 43, 7, 63, 162, 97, 231, 68, 90, 176, 20, 69, 8, 101, 121, 62, 41, 41, 168, 68, 42, 235, 26, 69, 248, 202, 195, 61, 106, 69, 16, 69, 117, 230, 4, 69, 64, 66, 64, 63, 164, 62, 171, 68, 26, 119, 24, 69, 82, 242, 82, 63, 96, 103, 79, 69, 140, 161, 16, 69, 4, 173, 65, 63, 201, 24, 185, 68, 17, 166, 40, 69, 88, 134, 105, 63, 47, 8, 78, 69, 100, 6, 67, 69, 224, 85, 76, 63, 69, 163, 182, 68, 223, 123, 66, 69, 244, 2, 101, 63, 141, 115, 31, 69, 139, 233, 49, 69, 8, 151, 126, 63, 218, 239, 234, 68, 122, 138, 61, 69, 158, 24, 127, 63, 253, 94, 44, 69, 70, 94, 78, 69, 220, 84, 126, 63, 19, 156, 176, 68, 57, 253, 117, 69, 231, 41, 127, 63, 79, 33, 62, 69, 48, 148, 99, 69, 223, 0, 124, 63, 101, 110, 192, 68, 164, 212, 145, 69, 132, 44, 125, 63]
```
How to interpret this ? The values are all UInts but my image size is 
` Optional(4284.0) Optional(5712.0)`

I need to scale these co-ordinates I think If so how are they related to the pixel values ?  Any pointers are greatly appreciated.

Also the length of this array is 228 and not 57 no idea why.

**Comment by glenn-jocher** [comment]
@pbanavara hello! It looks like you're making great progress with your iOS implementation of YOLOv8 pose detection. Let's address your questions:

1. **Interpreting Output Tensor Values**: The output tensor shape `(1, 57)` corresponds to `[4 bounding box coordinates, 1 score, 1 class, 51 keypoints (17 keypoints * 3 for x, y, confidence)]` for each detected object. The keypoints are structured as `(x, y, confidence)` triplets for each of the 17 keypoints.

2. **Scaling Keypoint Values**: The values you're seeing are likely normalized or in a different scale. To convert them back to your image's pixel scale, you would typically normalize them based on the model's input size and then scale them up to your original image size. Here's a quick example in Swift:

```swift
// Assuming `keypoint` is one of the keypoints from the output tensor
let modelInputSize: CGFloat = 640 // The size you used for your model input
let originalImageWidth: CGFloat = 4284
let originalImageHeight: CGFloat = 5712

let scaleX = originalImageWidth / modelInputSize
let scaleY = originalImageHeight / modelInputSize

let originalX = keypoint.x * scaleX
let originalY = keypoint.y * scaleY
```

3. **Array Length Mismatch**: The length of the array being 228 instead of 57 might be due to the way the output tensor is being interpreted or flattened. Ensure you're accessing the tensor correctly and interpreting its shape as intended by the model's output format. The model might be outputting data for multiple detections in a single forward pass, hence the larger array size.

Remember, the key here is to correctly interpret the model's output format and scale the keypoints accordingly to match your original image dimensions. If you're still facing issues, consider revisiting the model's documentation or the ONNX model's specific output format for further clarification. 🚀

**Comment by pbanavara** [comment]
Thank you @glenn-jocher 

I visualized the model on Netron and the last layer reads 11 selected boxes :)
`
name: nms_output_with_scaled_boxes_and_keypoints
tensor: float32[_11_selected_boxes,57] 
`
Phew no idea why 11 selected boxes if this is already a post processed model. I may have to use nms to eliminate 10 out of these 11 boxes, let's see. Will try to figure this out but the scaling factor seems to be working. Thank you for that tip.

**Comment by glenn-jocher** [comment]
@pbanavara hey there! 🌟

Glad to hear you're making progress and that the scaling factor tip helped! Regarding the 11 selected boxes, it's common for models to output multiple detections before applying NMS (Non-Maximum Suppression). This allows you to choose the best detections based on confidence scores or other criteria. 

If you're seeing multiple boxes for what should be a single detection, applying NMS is indeed a good step. It'll help you filter out overlapping boxes and keep only the most relevant ones. 

Keep up the great work, and don't hesitate to reach out if you have more questions! Happy coding! 🚀

**Comment by pbanavara** [comment]
OK Solved this finally. The keypoints are visible as tiny red squares.

@glenn-jocher Thank you so much for all the inputs you provided. It so happens this was not a scaling problem. The problem was with a datatype. Instead of Float32 I had used UInt8 :) what gives.

```
var arr2 = Array<Float32>(repeating: 0, count: output.count/MemoryLayout<Float32>.stride)
    _ = arr2.withUnsafeMutableBytes { output.copyBytes(to: $0) }
```
I've attached the output here. 

![iOS_simulator](https://github.com/ultralytics/ultralytics/assets/600054/70862b3b-425b-47ae-8c71-f1088ac607fd)

I wanted to add this to the open source iOS app but this uses onnx, not coreml. So let me know what's the best way to include this source for the community. I need to do some code clean up and will share the repo post that.

Now, I need to extrapolate this to video and camera live feed. Should be pretty straightforward, lets see.

**Comment by glenn-jocher** [comment]
Hey @pbanavara, that's fantastic news! 🎉 I'm thrilled to hear you've resolved the issue and it was as simple as a datatype mix-up. It's often the little things that catch us off guard, isn't it? 😄

Your approach to converting the datatype and successfully visualizing the keypoints as red squares is spot on. Thanks for sharing your solution and the output image – it looks great!

Regarding adding your work to the open-source iOS app, we're excited about your contribution! Since the app currently uses CoreML and your implementation is with ONNX, perhaps you could create a separate branch or a dedicated repository for the ONNX version. This way, the community can benefit from both approaches. Once you've cleaned up the code, feel free to share the repo link or make a pull request. We're here to support you in making this addition as smooth as possible.

Moving on to video and live camera feed implementation sounds like an exciting next step. If you encounter any hurdles or have further insights to share, don't hesitate to reach out. Best of luck, and looking forward to seeing your continued progress! 🚀

**Comment by pbanavara** [comment]
Hi @glenn-jocher Here is the repo link

https://github.com/pbanavara/onnx.git

Let me know the best way to include this under Ultralytics. Am happy to do any code modifications or run tests etc. Or if there are any other ways of sharing, am more than happy to explore those as well. 

Once again, many thanks for all the help you and the community have provided in helping me reach this stage.

**Comment by glenn-jocher** [comment]
Hey @pbanavara, fantastic work on getting your repo ready, and thanks for sharing the link! 🎉

To include your ONNX implementation under Ultralytics, you could fork our main repository, add your code as a new directory or feature branch, and then submit a pull request. This way, we can review the changes together and discuss any necessary adjustments. If you're unfamiliar with the process, I'm here to help guide you through it.

Your willingness to explore other sharing methods is greatly appreciated as well. We're all about collaboration here, so if you have any ideas or questions, feel free to share!

Thanks again for your contributions and for being such an active member of our community. Looking forward to seeing your work integrated into Ultralytics! 🚀

**Comment by pbanavara** [comment]
@glenn-jocher  Done. I have created a new directory under examples and here is the PR

https://github.com/ultralytics/ultralytics/pull/8907

Please review the same and I will follow up with the review comments.

**Comment by glenn-jocher** [comment]
Hey @pbanavara, that's awesome! 🌟 Thanks for submitting the PR and for your contribution. I'll take a look and get back to you with any feedback. Keep up the great work!
