### ISSUE TITLE
Add fp16 and nms export for onnx?

### ISSUE THREAD

**Issue by UNeedCryDear** [ultralytics/ultralytics#8744]
Export onnx with nms and support FP16

**Comment by glenn-jocher** [comment]
@UNeedCryDear certainly! To export a YOLOv8 model to ONNX format with NMS and FP16 support, you can use the following command:

```bash
yolo export model=yolov8n.pt format=onnx half=True
```

This command exports your model in half-precision (FP16) to reduce size and potentially increase inference speed on compatible hardware. Currently, direct NMS layer export to ONNX is not supported within our export functionality. However, you can implement NMS post-processing after running the ONNX model inference. 

For any further assistance or questions, feel free to reach out! 😊

**Comment by UNeedCryDear** [comment]
@glenn-jocher 
```half=True``` dos not work for onnx.
```bash
yolo export model=yolov8n.pt format=onnx half=True
```

and got FP32,  yolov8n.onnx in  https://netron.app

![微信图片_20240308111915](https://github.com/ultralytics/ultralytics/assets/52729998/a774c4cc-d2a8-41cd-a3c0-585453fb9738)

**Comment by glenn-jocher** [comment]
@UNeedCryDear hi there! 😊 It looks like you encountered an issue with exporting the model in FP16 precision for ONNX. The `half=True` argument is intended for TensorRT exports and might not directly influence the ONNX export precision. For ONNX, the model precision conversion to FP16 typically happens post-export using ONNX tools.

However, you can try optimizing the ONNX model to FP16 using the ONNX Runtime or other ONNX-compatible tools after export. Here's a quick example using `onnxruntime_tools`:

```python
from onnxruntime_tools import optimizer
from onnxruntime_tools.transformers.onnx_model_fp16_converter import convert_float_to_float16

optimized_model = optimizer.optimize_model("yolov8n.onnx")
convert_float_to_float16(optimized_model.model_proto, keep_io_types=True)
optimized_model.save_model_to_file("yolov8n_fp16.onnx")
```

This should help you get the model in FP16. Let us know if you need further assistance!

**Comment by UNeedCryDear** [comment]
Run code and it got error "No module named 'onnxruntime_tools.transform’"
I used to convert using the following code by ```onnxconverter_common``` . But I was wondering if it's possible to use official support for this export.
```
import onnx
from onnxconverter_common import float16
f="yolov8n.onnx"
fout=""yolov8n-fp16.onnx""
model_onnx = onnx.load(f)  # load onnx model
onnx.checker.check_model(model_onnx)  # check onnx model
# # # Metadata should change Type to str
# d = { 'names': model.names}
# for k, v in d.items():
#     meta = model_onnx.metadata_props.add()
#     meta.key, meta.value = k, str(v)
#
model_fp16=float16.convert_float_to_float16(model_onnx,keep_io_types=True, disable_shape_infer=False)
onnx.save(model_fp16, fout)

```

**Comment by glenn-jocher** [comment]
@UNeedCryDear hey there! 😊 It looks like you're encountering an issue with the `onnxruntime_tools` package. The code snippet you've shared using `onnxconverter_common` is indeed a valid approach to convert an ONNX model to FP16. Currently, direct FP16 export support for ONNX within the Ultralytics YOLOv8 export functionality is not provided. Your method of using `onnxconverter_common` for conversion is a good workaround.

For official support on FP16 exports directly from our tooling, we'll take this feedback into consideration for future updates. Your input helps us improve! In the meantime, your approach with `onnxconverter_common` is the recommended way to achieve FP16 precision for ONNX models.

If you have any more questions or need further assistance, feel free to reach out. Happy coding!

**Comment by UltralyticsAssistant** [comment]
The associated pull request [#18484](https://github.com/ultralytics/ultralytics/pull/18484) has been merged, and it includes a potential fix that may resolve this issue! 🎉  

### Relevant Key Changes from the PR:
This update introduces extended export functionalities and post-processing improvements for object detection models, addressing several limitations in the workflow. Notable changes include:
- **Non-Maximum Suppression (NMS) Integration**: Exported models (TorchScript, ONNX, OpenVINO, TensorRT, TensorFlow) now include embedded NMS, providing seamless post-processing capabilities.
- **Enhanced Post-Processing Logic**: Predictions for various tasks (detection, segmentation, pose, and OBB) have been refined, including additional attribute support, like `keypoints`, for improved handling of prediction results.
- **Flexibility in Export Configurations**: Users can now toggle NMS during the export process, enabling easier deployment customization.
- **Better Metadata Handling**: Updates for improved export compatibility across formats.
- 🆙 Version upgraded to `8.3.67` for tracking this new functionality.

These changes aim to streamline the export process while improving runtime efficiency and usability for deployment scenarios.  

### Contributors ❤️
This valuable update was made possible due to contributions from [Y-T-G](https://github.com/Y-T-G), [lifafang](https://github.com/lifafang), [boorad](https://github.com/boorad), [glenn-jocher](https://github.com/glenn-jocher), [Laughing-q](https://github.com/Laughing-q), and [inisis](https://github.com/inisis). A big thank you to everyone involved! 🙌  

### How to Test the Changes:
To verify if this resolves your issue:
- Install the latest changes directly from the `main` branch:
  ```bash
  pip install git+https://github.com/ultralytics/ultralytics.git@main
  ```
- Or you can wait for the next official release on PyPI if preferred.

Let us know if this resolves the issue or if you encounter any remaining problems. Your feedback is invaluable in ensuring the robustness of these updates.  

Thanks again for bringing up this issue! 🙏 If anything persists or additional adjustments are needed, feel free to share more details.
