### ISSUE TITLE
Pitfalls on mAP

### ISSUE THREAD

**Issue by FoxSkywalker** [ultralytics/ultralytics#8765]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, guys!

I'm doing some research with YOLOv8 and found this paper:

[Understanding metric-related pitfalls in image analysis validation](https://www.nature.com/articles/s41592-023-02150-0)

In this paper some pitfalls about mAP caught my attention:

![image](https://github.com/ultralytics/ultralytics/assets/49927987/aafc8e1a-b1d7-4196-b3d0-3ab6285c2d58)

**With this in mind, I have some doubts:**

- YOLOv8 uses COCO or Pascal-VOC approach to calculate the mAP?
- I've noticed that in Val Mode, the confidence default value is 0.001. If I increase this value, this could be enough to resolve the issue of the last topic?
- Why the Conf and IoU parameters exists only for Validation mode? I mean, why I can't train a model using a specific value of Conf and IoU?
- If I change the IoU to 0.3, I can access like map30.box method?

**Comment by glenn-jocher** [comment]
@FoxSkywalker hello!

Great questions! Let's dive into them:

- YOLOv8 primarily uses the COCO approach for calculating mAP, which is more comprehensive and widely adopted in the community. 📊

- Adjusting the confidence threshold in Val Mode can indeed influence the mAP calculation, as it filters out detections with lower confidence. However, it's more about balancing precision and recall rather than resolving all potential issues related to mAP calculation. 🎯

- The Conf and IoU parameters are specific to the validation phase to allow for a flexible evaluation of the model under different criteria without retraining. Training with a fixed Conf or IoU would limit the model's ability to learn a broader range of object representations. 🌱

- Changing the IoU threshold for validation does allow you to access metrics like `map30.box` (for IoU=0.3) in the results, providing insights into how the model performs at that specific IoU threshold. 📈

Hope this helps clarify your doubts! If you have more questions, feel free to ask.
