### ISSUE TITLE
RT-DETR Tracking accuracy

### ISSUE THREAD

**Issue by MatthewNoyce** [ultralytics/ultralytics#8798]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

When testing tracking using YOLOv5 and comparing to RT-DETR, the HOTA, MOTA and IDF1 scores calculated for RT-DETR are significantly lower (especially the MOTA) compared to the YOLOv5 suite of models. When testing just the detection aspect of RT-DETR the models are much more accurate than the YOLOv5 models. I asked in the discord and was told to open a GitHub issue. 
![image](https://github.com/ultralytics/ultralytics/assets/131261051/2e66c499-738e-4d41-994a-2df7f2578be3)
![image](https://github.com/ultralytics/ultralytics/assets/131261051/1e34d2dd-6954-49f4-91c4-7d1b3de11503)
Attached are graphs of various metrics for tracking and detections if that is any help. 

### Environment

Ultralytics YOLOv8.1.10 🚀 Python-3.9.18 torch-2.1.0 CUDA:0 (NVIDIA GeForce RTX 3070, 8191MiB)
Setup complete ✅ (16 CPUs, 31.9 GB RAM, 789.3/930.9 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.9.18
Install             pip
RAM                 31.91 GB
CPU                 AMD Ryzen 7 3700X 8-Core Processor
CUDA                12.1

matplotlib          ✅ 3.8.0>=3.3.0
numpy               ✅ 1.25.2>=1.22.2
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.0.1>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.28.2>=2.23.0
scipy               ✅ 1.9.3>=1.4.1
torch               ✅ 2.1.0>=1.8.0
torchvision         ✅ 0.16.0>=0.9.0
tqdm                ✅ 4.65.2>=4.64.0
psutil              ✅ 5.9.0
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.1.2>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃
