### ISSUE TITLE
An unknown argument: --json

### ISSUE THREAD

**Issue by olegchomp** [ultralytics/ultralytics#8803]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi! I'm trying to run YOLO in TouchDesigner software. On simple inference i've got error 'An unknown argument: --json'. I'm interested how can i disable that argument?

```
# Load a pretrained YOLOv8n model
model = YOLO('yolov8n.pt')

# Create a random numpy array of HWC shape (640, 640, 3) with values in range [0, 255] and type uint8
source = np.random.randint(low=0, high=255, size=(640, 640, 3), dtype='uint8')

# Run inference on the source
results = model(source)
results = json.loads(results[0].tojson())
```

**Comment by glenn-jocher** [comment]
@olegchomp hello! It looks like you're encountering an issue with an unrecognized `--json` argument. In the context of your code snippet, it seems you're trying to convert the results to JSON format directly within your Python script, rather than using a command-line argument.

Your approach to converting the results to JSON using `results[0].tojson()` is correct and doesn't require disabling any argument. If you're seeing an 'unknown argument' error related to `--json`, it might be due to how you're invoking the YOLO model in TouchDesigner, rather than the Python code itself.

Ensure that when you're setting up the YOLO model in TouchDesigner, you're not inadvertently passing `--json` as part of the command or configuration. The Python API usage you've shown doesn't involve command-line arguments like `--json`, so the error might stem from elsewhere in your setup.

If you continue to face issues, could you provide more details on how you're integrating YOLO with TouchDesigner? That might help pinpoint the source of the problem. 😊

**Comment by olegchomp** [comment]
```
import json
import numpy as np
import sys

sys.stdout.encoding = 'utf-8'
from ultralytics import YOLO

# Load a pretrained YOLOv8n model
model = YOLO('yolov8n.pt')

# Create a random numpy array of HWC shape (640, 640, 3) with values in range [0, 255] and type uint8
source = np.random.randint(low=0, high=255, size=(640, 640, 3), dtype='uint8')

# Run inference on the source
results = model(source, verbose=False)

results = json.loads(results[0].tojson())

```

![image](https://github.com/ultralytics/ultralytics/assets/11017531/91b02165-69fd-44a9-87e4-2b49736f5baa)

Here is full code, nothing special. First time i see error like that, so it mostly about YOLO package.

**Comment by glenn-jocher** [comment]
@olegchomp hey there! 👋 It looks like you've got everything set up correctly in your code snippet for running inference with YOLOv8 and converting the results to JSON. The error you're encountering isn't directly related to the YOLO package based on the code you've shared.

One thing to check is the version of the `ultralytics` package you're using. Ensure it's up to date since improvements and bug fixes are regularly made. You can update it using:

```bash
pip install ultralytics --upgrade
```

If the issue persists after updating, it might be helpful to share the exact error message you're encountering. Sometimes, the error could be related to the environment or specific configurations rather than the package itself.

Also, the image link seems to be broken. If it's meant to show the error, could you please re-upload or describe the error message? That might give more clues! 🕵️‍♂️

Let's get this sorted out!

**Comment by olegchomp** [comment]
Reupload image:
https://postimg.cc/MnSkSpRr

This happend only with YOLO package.

**Comment by glenn-jocher** [comment]
Hey @olegchomp 👋! From the reuploaded image and your description, it seems like there might have been a misunderstanding with the error message origination. The `--json` argument error doesn't appear to be directly related to the Ultralytics YOLO library, as the library's Python API usage, as shown in your code, doesn't utilize command-line arguments like `--json`.

The snippet you've shared is correct for performing inference and parsing the results into JSON format:

```python
results = model(source, verbose=False)
results_json = json.loads(results[0].tojson())
```

This should work fine without any `--json` arguments. The error might be originating from how the model is being used within TouchDesigner or another part of your project that tries to integrate YOLO in a non-standard way.

If YOLO is being invoked somewhere with command-line arguments, please double-check that part of your setup or script. For a clean test, you could run the script outside of TouchDesigner in a standard Python environment to verify it works as expected.

If further issues arise or if you have more details, feel free to share! Happy coding! 🚀

**Comment by joansc** [comment]
Hey @olegchomp, it's happening the same thing to me  in TD, did you end up finding a solution? Thanks!

Joan

**Comment by olegchomp** [comment]
> Hey @olegchomp, it's happening the same thing to me in TD, did you end up finding a solution? Thanks!
> 
> Joan

nope, i think to make issue topic on TD forum, but anyway i think it's on YOLO side anyway.

**Comment by glenn-jocher** [comment]
Hey Joan 👋, and @olegchomp,

It's intriguing that both of you are facing this issue within TouchDesigner. While it initially seemed like a problem with the YOLO package, considering it solely occurs in the TD environment hints at a unique interaction there. 

A potential step forward could be to initiate a discussion on the TD forum, as other users might have encountered and solved this puzzle. Meanwhile, I highly recommend ensuring both your YOLO package and TouchDesigner software are up-to-date to mitigate any compatibility issues. 

If the problem persists and you strongly believe it's on the YOLO side, providing detailed error logs and system configurations when reaching out to either the YOLO GitHub or TD Forum would be immensely helpful for troubleshooting. Let's keep the communication open and hopefully work towards a resolution soon. 🛠️

Warm
