### ISSUE TITLE
How to load pretrained backbone correctly and training from pretrained backbone?

### ISSUE THREAD

**Issue by Estellasy** [ultralytics/ultralytics#8811]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I attempted to pretrain the YOLOv8 backbone using a self-supervised learning method and saved the state_dict file. 
It looks like I loaded the pretrained backbone correctly, but when training, both training modes (pretrained=True and pretrained=False) yield exactly same results, suggesting that the pretrained backbone weights are not effectively utilized during training.

Training with `pretrained=True`.
```python
# Loading pretrained backbone weights
model = YOLO(model_yaml)
backbone = torch.load(backbone_pt)
model.model.load_state_dict(backbone['state_dict'])
model.train(data=data_yaml, epochs=200, batch=8, seed=42, pretrained=True, name=save_name)

```
Training with `pretrained=False`
```python
# Training with pretrained weights
model = YOLO(model_yaml)
model.train(data=data_yaml, epochs=200, batch=8, seed=42, pretrained=False, name=save_name)
```
Would you tell me what went wrong? How do I load the backbone weights correctly?

**Comment by glenn-jocher** [comment]
@Estellasy hello! It looks like you're on the right track with loading your pretrained backbone. However, when using `pretrained=True` with `model.train()`, it expects the model to be initialized with pretrained weights already loaded. Since you're loading the backbone weights manually, you don't need to use `pretrained=True` in `model.train()`. Instead, ensure your backbone weights are loaded into the model before initiating training. Here's a slight adjustment to your approach:

```python
# Loading pretrained backbone weights
model = YOLO(model_yaml)
backbone_weights = torch.load(backbone_pt)
model.model.load_state_dict(backbone_weights['state_dict'], strict=False)  # Use strict=False to avoid missing keys errors

# Now train the model without specifying pretrained=True
model.train(data=data_yaml, epochs=200, batch=8, seed=42, name=save_name)
```

By setting `strict=False`, it allows for the model to load the weights available in the `state_dict` without requiring an exact match of all model parameters. This is particularly useful when you're only loading a part of the model, like the backbone. 

Give this a try, and it should utilize your pretrained backbone weights effectively during training. Happy coding! 😊

**Comment by Estellasy** [comment]
I tried not to set `pretrain` in model.train(), but it seems that the pre-training backbone is still not loaded correctly, and the model is re-initialized in the `train()` method.
However, I modified the `train()` method to manually initialize the backbone weight. This time, it worked.
Now the problem is solved, thank you very much.

**Comment by glenn-jocher** [comment]
@Estellasy, glad to hear you've found a solution! 🎉 It's great that manually initializing the backbone weights within the `train()` method worked out for you. If you have any more questions or run into further issues, feel free to reach out. Happy training! 😊

**Comment by Christian-lyc** [comment]
> I tried not to set `pretrain` in model.train(), but it seems that the pre-training backbone is still not loaded correctly, and the model is re-initialized in the `train()` method. However, I modified the `train()` method to manually initialize the backbone weight. This time, it worked. Now the problem is solved, thank you very much.

Hi, I'm facing maybe a similar problem.   I use the yolov8n model to run object detection, it gives reasonable results with predicted bonding box. Later I rebuilt the model without reading that yaml file, because with random weights, it gives bonding box with 0 value inside. And then the weird thing happens, when I load parameters from the pretrained ultralytics model to the rebuilt model, it outputs empty bounding box. And I randomly checked the maximum loaded parameters of the rebuilt model and the pretrained one, it’s same. I don’t know what happened, but I’m sure it's the problem of detection block, because without loading detection block, the model outputs bounding box with zero values. Here’s the loading code I used. Maybe you know how to solve it. Thank you so much, I really appreciate it.
rebuilt_model.conv1.load_state_dict(pretrain_model.model._modules[‘model’][0].state_dict())
rebuilt_model.conv2.load_state_dict(pretrain_model.model._modules[‘model’][1].state_dict())
rebuilt_model.c2f1.load_state_dict(pretrain_model.model._modules[‘model’][2].state_dict())
rebuilt_model.conv3.load_state_dict(pretrain_model.model._modules[‘model’][3].state_dict())
rebuilt_model.c2f2.load_state_dict(pretrain_model.model._modules[‘model’][4].state_dict())
rebuilt_model.conv4.load_state_dict(pretrain_model.model._modules[‘model’][5].state_dict())
rebuilt_model.c2f3.load_state_dict(pretrain_model.model._modules[‘model’][6].state_dict())
…
rebuilt_model.detect.load_state_dict(pretrain_model.model._modules['model'][22].state_dict())
rebuilt_model.detect.anchors=pretrain_model.model._modules['model'][22].anchors
rebuilt_model.detect.stride=pretrain_model.model._modules['model'][22].stride
rebuilt_model.detect.strides=pretrain_model.model._modules['model'][22].strides
rebuilt_model.detect.shape=pretrain_model.model._modules['model'][22].shape

**Comment by Lightmannnn** [comment]
> I tried not to set `pretrain` in model.train(), but it seems that the pre-training backbone is still not loaded correctly, and the model is re-initialized in the `train()` method. However, I modified the `train()` method to manually initialize the backbone weight. This time, it worked. Now the problem is solved, thank you very much.

Could you please tell me how you solved it? I'd appreciate it.

**Comment by glenn-jocher** [comment]
I'm glad you resolved the issue! To manually initialize the backbone weights, you can modify the `train()` method to load your pretrained weights before the model is re-initialized. If you need further assistance, feel free to ask.

**Comment by Y-T-G** [comment]
`state_dict` updates do not take effect because the model is rebuilt from yaml during training.

https://github.com/ultralytics/ultralytics/issues/17135#issuecomment-2435109331
