### ISSUE TITLE
KeyError: 'train'

### ISSUE THREAD

**Issue by AlexanderLamperouge** [ultralytics/ultralytics#8814]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

root@c3367413f364:/usr/src/ultralytics/data/fuctions# python3 myTrain.py
WARNING ⚠️ Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify','pose' or 'obb'.
Traceback (most recent call last):
  File "/usr/src/ultralytics/data/fuctions/myTrain.py", line 4, in <module>
    model = YOLO("/usr/src/ultralytics/data/fuctions/myTrain.yaml").load(
  File "/usr/src/ultralytics/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/usr/src/ultralytics/ultralytics/engine/model.py", line 140, in __init__
    self._new(model, task=task, verbose=verbose)
  File "/usr/src/ultralytics/ultralytics/engine/model.py", line 211, in _new
    self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
  File "/usr/src/ultralytics/ultralytics/nn/tasks.py", line 287, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=ch, verbose=verbose)  # model, savelist
  File "/usr/src/ultralytics/ultralytics/nn/tasks.py", line 836, in parse_model
    for i, (f, n, m, args) in enumerate(d["backbone"] + d["head"]):  # from, number, module, args
KeyError: 'backbone'
root@c3367413f364:/usr/src/ultralytics/data/fuctions# python3 myTrain.py
Traceback (most recent call last):
  File "/usr/src/ultralytics/data/fuctions/myTrain.py", line 9, in <module>
    results = model.train(
  File "/usr/src/ultralytics/ultralytics/engine/model.py", line 630, in train
    custom = {"data": DEFAULT_CFG_DICT["data"] or TASK2DATA[self.task]}  # method defaults
KeyError: 'train'

### Environment

英伟达V100
Linux server

### Minimal Reproducible Example

from ultralytics import YOLO

# Load a model
model = YOLO(
    "/usr/src/ultralytics/data/MyRed/weights/best.pt"
)  # load a pretrained model (recommended for training)

# Train the model with 2 GPUs
results = model.train(
    task="train",
    cache=True,
    profile=True,
    data="/usr/src/ultralytics/data/fuctions/myTrain.yaml",
    name="MyRed2",
    project="/usr/src/ultralytics/data",
    epochs=1000,
    imgsz=640,
    device=0,
)

path: /usr/src/ultralytics/data/data
train: # train images (relative to 'path')  16551 images
  - images_thermal_train
val: # val images (relative to 'path')  4952 images
  - images_thermal_val
test: # test images (optional)
  - images_thermal_test

# Classes
names:
  0: person
  1: bike
  2: car
  3: motor
  4: bus
  5: train
  6: truck
  7: light
  8: hydrant
  9: sign
  10: dog
  11: deer
  12: skateboard
  13: stroller
  14: scooter
  15: other vehicle

### Additional

root@c3367413f364:/usr/src/ultralytics/data/fuctions# ls /usr/src/ultralytics/data/MyRed/weights/best.pt
/usr/src/ultralytics/data/MyRed/weights/best.pt

I'm certain this path is correct. I can only conduct the initial training through model = Yolo('yolov8n.pt'). However, whenever I try to specify my best.pt, the above error occurs. I would greatly appreciate it if someone could help me. Thank you very much!

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@AlexanderLamperouge hey there! 👋 It looks like you're encountering a couple of issues related to specifying the task and loading your custom configuration file. Let's address them:

1. **Specifying Task**: When initializing your model with `YOLO()`, it's a good practice to explicitly specify the task your model is intended for. Since you're training, you should set `task='detect'` (or the appropriate task like 'classify', 'segment', etc., based on your model's purpose).

2. **Custom Configuration File**: The error `KeyError: 'backbone'` suggests there might be an issue with your custom YAML configuration file (`myTrain.yaml`). Ensure that it correctly defines the `backbone` and `head` sections as expected by YOLOv8. The structure of your YAML file should closely follow the examples provided in the official YOLOv8 repo.

3. **Loading Pretrained Weights**: When you're loading the model with `YOLO()`, and you want to use your custom trained weights (`best.pt`), make sure the path is correct and accessible. It seems like you've already checked the path, which is great!

Here's a revised version of your code with the task specified:

```python
from ultralytics import YOLO

# Load a model with task specified
model = YOLO(
    "/usr/src/ultralytics/data/MyRed/weights/best.pt",
    task='detect'  # Specify the task here
)  # load a pretrained model (recommended for training)

# Train the model with 2 GPUs
results = model.train(
    cache=True,
    profile=True,
    data="/usr/src/ultralytics/data/fuctions/myTrain.yaml",
    name="MyRed2",
    project="/usr/src/ultralytics/data",
    epochs=1000,
    imgsz=640,
    device=0,
)
```

Please double-check your `myTrain.yaml` for the correct structure and ensure all necessary sections are defined. If the issue persists, feel free to share more details about the YAML file's structure for further assistance. 😊
