### ISSUE TITLE
WARNING  Environment does not support cv2.imshow() or PIL Image.show()

### ISSUE THREAD

**Issue by LightKeyDarkBlade** [ultralytics/ultralytics#882]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm running a simple code below for segmentation (without training) and prediction using a webcam on my laptop.
```
model = YOLO("yolov8n-seg.pt")
results = model.predict(source="0", show=True, save=True)
```

It works perfectly fine when I run it using Anaconda Prompt, Visual Studio Code, and PyCharm. But when I run it using **Spyder**, the following warning shows up.
`WARNING  Environment does not support cv2.imshow() or PIL Image.show()`

The code runs fine and the webcam is being used, but the window of the camera view doesn't pop up. This only happens if I run it using Spyder as far as I know. I'm also attempting to run it in **Xircuits** (https://github.com/XpressAI/xircuits) and the same thing happens there. It is also the same for detection or classification.

My environment:
Ultralytics YOLOv8.0.32  Python-3.9.16 torch-1.12.1+cu116 CPU
OS: Windows 10

I notice that a couple of questions with the same warning were asked for YOLOv5 below, but neither of them were related to Spyder and my situation.
https://github.com/ultralytics/yolov5/issues/9844
https://github.com/ultralytics/yolov5/issues/10540

Does anyone know what the cause of this is and is there any workaround for it? Do let me know if you need more information from me.

**Comment by glenn-jocher** [comment]
@LightKeyDarkBlade we have a check here that verifies that your environment supports cv2.imshow(). It will return False for headless environments like Colab notebooks or SSH consoles where cv2 can not show images, or if cv2 headless is installed, so you may be using a different environment in Spyder.

Or possibly the function is not working correctly. The function is here, if you could help us debug this that would help us fix any issues.
https://github.com/ultralytics/ultralytics/blob/c9893810c791c187dd7046238e5ebe21605920e0/ultralytics/yolo/utils/checks.py#L268-L282

**Comment by glenn-jocher** [comment]
@LightKeyDarkBlade looking at the function above you should check to see if is_jupyter() is working correctly also. This should be True for jupyter notebooks like Colab and Kaggle, which are incapable of using cv2.imshow()

**Comment by LightKeyDarkBlade** [comment]
I've tried calling those functions using Spyder and check_imshow() returns False while is_jupyter() returns True. I don't know if this is normal for Spyder and if Spyder is Jupyter-based. I've also double-checked and I'm indeed using the same Python environment in Spyder as in other IDEs.

So from what I can gather, this is because of Jupyter limitation with cv2.imshow()? If so, is there any workaround for this?

**Comment by LightKeyDarkBlade** [comment]
@glenn-jocher I've looked through the code and I notice that after it calls the check_imshow() function, it is using the output in the stream_inference() function to determine whether to show the window or not.

https://github.com/ultralytics/ultralytics/blob/e799592718b6fc5b0dc26dd99dbdc61b6ac98c0d/ultralytics/yolo/engine/predictor.py#L185-L186

I tried removing the condition above so that it attempts to show regardless and the window actually appears in Spyder and in Xircuits (I mentioned this above and it is Jupyterlab-based). It still gives a warning because it did the check prior to showing but somehow it works. So the check returns False but cv2.imshow() works anyway in Spyder and Xircuits for some reason.

I'm not sure why it works when it "shouldn't work" according to the check, but I think there should be some amendment to the code, either the check itself or the condition to show in stream_inference(). Because the condition is preventing the code to show when there is a possibility for it to show.

**Comment by dmddmd** [comment]
I am directly working in a jupyter notebook.
I get the same WARNING today (I did a pip upgrade ultralytics) with Ultralytics YOLOv8.0.42,
 but yesterday it worked (I don't remember which ultralytics version it was).........

**Comment by dmddmd** [comment]
I tried it again in PyCharm.. for me, it has something to do with Python or memory issues, I guess.
Sometimes the windows appears, the other time not.

**Comment by wynshiter** [comment]
in my windows11 laptop i use the following code in pycharm no windows shows but visual studio code is ok：
```python
from ultralytics import YOLO

#Load a model
model_path = r'D:\code\python\yolov8\yolov8n.pt'
model = YOLO(model_path)  # load an official detection model


# Track with the model
results = model.track(source="0", show=True)
```
Does anyone know why? Does pychar need any settings？
i use pycharm 2021.3

**Comment by duy1851999** [comment]
> def check_imshow(warn=False): 
>      # Check if environment supports image displays 
>      try: 
>          assert not is_jupyter() 
>          assert not is_docker() 
>          cv2.imshow('test', np.zeros((1, 1, 3))) 
>          cv2.waitKey(1) 
>          cv2.destroyAllWindows() 
>          cv2.waitKey(1) 
>          return True 
>      except Exception as e: 
>          if warn: 
>              LOGGER.warning(f'WARNING ⚠️ Environment does not support cv2.imshow() or PIL Image.show()\n{e}') 
>       

> @LightKeyDarkBlade looking at the function above you should check to see if is_jupyter() is working correctly also. This should be True for jupyter notebooks like Colab and Kaggle, which are incapable of using cv2.imshow()

I run the yolov8 by docker and it doesn't show the image. How I show image by docker run image. Thanks sir.

**Comment by glenn-jocher** [comment]
@duy1851999 hello there! It appears that the issue you are having is that the environment you are running YOLOv8 in does not support image displays. Specifically, the `cv2.imshow()` function is not working as expected in your Docker container so the image is not showing up.

To display the image in your Docker container, you'll need to install an additional package that allows for X11 forwarding. X11 forwarding will allow you to display images on your host machine, even if the code is running inside the container. Here is an example command to launch the container and enable X11 forwarding on Ubuntu:

```
docker run -it -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix <your_image_name> <your_script.py>
```

This command sets the `DISPLAY` environment variable inside the container to match the display on your host machine, and then maps the X11 socket to the Docker container. This should allow you to display images using `cv2.imshow()`.

I hope this helps! Let us know if you have any further questions.

**Comment by JakeSimmons22** [comment]
> Hello, I am having the same issue of using a Docker container and i get the environment warning that cv2.imshow() is not supported but the camera is being used. I am using UBUNTU 18.04.6 to run the Docker container. Provided below is my docker run command sudo docker run --name spot_yolov5 --rm --ipc=host --device=/dev/video0:/dev/video0 -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --net=host ultralytics/yolov5:latest

I solved the issue

**Comment by dubstepenjoyer** [comment]
> @LightKeyDarkBlade we have a check here that verifies that your environment supports cv2.imshow(). It will return False for headless environments like Colab notebooks or SSH consoles where cv2 can not show images, or if cv2 headless is installed, so you may be using a different environment in Spyder.
> 
> Or possibly the function is not working correctly. The function is here, if you could help us debug this that would help us fix any issues.
> 
> https://github.com/ultralytics/ultralytics/blob/c9893810c791c187dd7046238e5ebe21605920e0/ultralytics/yolo/utils/checks.py#L268-L282

Hi! Can I somehow run my YOLOv8 project in docker without this check function?I tried to edit YOLO code, i wrote that this check function always return True. But process in container just end and docker stopped container. Are there any options to run my project in docker?

**Comment by glenn-jocher** [comment]
@dubstepenjoyer hello! While it's technically possible to modify the YOLOv8 code to force the check function to always return True, it's not recommended as it would bypass important environment checks which would likely lead to other issues down the line.

As for running your YOLOv8 project in Docker, it is absolutely possible but the issue lies in displaying the images. Docker is a headless environment, meaning it doesn't have a display attached to it, so it cannot directly display images using functions like `cv2.imshow()`. 

If you are running your Docker container on a machine with a display (like your personal computer), you can set up X11 forwarding to display the images on your machine. There are lots of resources online on how to do this. 

If you're running the container on a server or in an otherwise headless environment, you might consider saving your images to disk instead of trying to display them. YOLOv8 supports saving images during prediction. You might also consider using a different method of visualization that doesn't require a display, such as saving plots or using a web-based interface.

I hope this helps, and let us know if you have any other questions!

**Comment by dubstepenjoyer** [comment]
> @dubstepenjoyer hello! While it's technically possible to modify the YOLOv8 code to force the check function to always return True, it's not recommended as it would bypass important environment checks which would likely lead to other issues down the line.
> 
> As for running your YOLOv8 project in Docker, it is absolutely possible but the issue lies in displaying the images. Docker is a headless environment, meaning it doesn't have a display attached to it, so it cannot directly display images using functions like `cv2.imshow()`.
> 
> If you are running your Docker container on a machine with a display (like your personal computer), you can set up X11 forwarding to display the images on your machine. There are lots of resources online on how to do this.
> 
> If you're running the container on a server or in an otherwise headless environment, you might consider saving your images to disk instead of trying to display them. YOLOv8 supports saving images during prediction. You might also consider using a different method of visualization that doesn't require a display, such as saving plots or using a web-based interface.
> 
> I hope this helps, and let us know if you have any other questions!

@glenn-jocher  Hi! I almost run my project in docker with nvidia-pytorch image as a base-layer, but now decided to try ultralytics:latest image. (special thanks for the feature with DISPLAY=$DISPLAY and X11 server) Now i have another problems and idk what to do.
My Docoker file:
```
FROM ultralytics/ultralytics

WORKDIR /app

COPY . .

RUN apt update && apt upgrade -y

RUN pip install --no-cache -r requirements.txt

CMD ["python", "track.py"]
```
and when i start i get this ```qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/opt/conda/lib/python3.10/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.```

I tryed new image build with this command  ```sudo apt-get install libxcb-xinerama0``` and got same Error (I guess the command is not what I need)

**Comment by glenn-jocher** [comment]
Hello @dubstepenjoyer,

Running graphical applications (like X11 apps) in Docker is indeed a bit more challenging due to the headless nature of Docker containers. Your error seems to be related to the PyQt5 interface with the X11 system.

One possible solution could be to install PyQt5 explicitly in your Dockerfile using `pip install PyQt5`. This should provide the correct Qt platform plugins for you. 

If that doesn't work, another possible solution is to install the necessary Qt dependencies in your Docker image. You can do this by adding the following line to your Dockerfile:

```dockerfile
RUN apt-get install -y qt5-default libxcb-xinerama0-dev
```

Please note, these are just suggestions and might not resolve your issues completely as Docker can have other complications when running GUI programs.

If you're still facing issues, an alternative could be to save outputs (images or videos) to a mounted volume and inspect them outside of the Docker environment. That way, you won't have to worry about displaying images within the Docker container. 

I hope this information helps. Please let us know if you have any more questions.

**Comment by maxkross** [comment]
Hello,

I was able to get cv2 working in a Docker container with

docker run -it -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix <your_image_name> <your_script.py>

Like you outlined.

Additionally I had to run xhost +local: on a command line on the host to get this working.

However, 

assert not is_docker() in check_imshow() prevents a cv2 window from getting created. This line needs to be commented out in order to get a live display from yolo from within a docker container.

**Comment by glenn-jocher** [comment]
@maxkross hello,

I'm glad to hear you were able to get `cv2` working in your Docker container with the X11 forwarding command and `xhost` configuration. You're correct that `xhost +local:` permits the Docker container to connect to your X server, which is necessary for GUI applications to display windows on the host machine.

Regarding the `assert not is_docker()` line in the `check_imshow()` function, the original intention behind this assertion likely stems from the typical use case for Docker containers where graphical displays are not commonly expected to be used. However, as you've noticed, when X11 forwarding is set up correctly, it is indeed possible to use `cv2.imshow()` within a Docker container.

If commenting out `assert not is_docker()` resolves the issue for you and allows the live display to function correctly, you can create a custom Docker image with this modification. Keep in mind that editing the library directly might not be the most maintainable approach if you plan to update or redistribute your Docker image. Nevertheless, for personal use, this modification appears to be a viable workaround.

Please ensure that any modifications you make are consistent with your use case and do not negatively affect other parts of your application. If you continue to encounter any issues or have further questions, please feel free to reach out.

Best regards.

**Comment by raf329** [comment]
> Hello,
> 
> I was able to get cv2 working in a Docker container with
> 
> docker run -it -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix <your_image_name> <your_script.py>
> 
> Like you outlined.
> 
> Additionally I had to run xhost +local: on a command line on the host to get this working.
> 
> However,
> 
> assert not is_docker() in check_imshow() prevents a cv2 window from getting created. This line needs to be commented out in order to get a live display from yolo from within a docker container.

Hi, when I use:
xhost +local:
docker run -it -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix <your_image_name>

I get this error:
CUDA is not recognized. 
import torch
print(torch.cuda.is_available()) 
FALSE. 

But when I use jetson-containersrun -it -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix <your_image_name>
all is good with CUDA, but I have:
 "WARNING ⚠️ Environment does not support cv2.imshow() or PIL Image.show()" with yolov9, but with yolov7 I can see the videostream from web camera. 
 
 What should I do with this error?

**Comment by raf329** [comment]
> Hey there! 🌟
> 
> Good job getting `cv2` to work in your Docker container, and it's great that `xhost +local:` helped as well. Regarding the CUDA issue, it sounds like the `DISPLAY` and volume mapping to `/tmp/.X11-unix` are working fine, but the container might not be set up correctly for CUDA. For CUDA to work, ensure your Docker run command includes the necessary flags for GPU, like `--gpus all` if you're using NVIDIA's runtime:
> 
> ```shell
> docker run -it --gpus all -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix <your_image_name>
> ```
> 
> As for the warnings with YOLOv8 and the issues with imshow, it seems there might be slight differences in how YOLOv8 and YOLOv7 handle GUI functionalities and environment checks. Commenting out `assert not is_docker()` is a temporary fix, but it'd be important to make sure your Docker setup is fully compatible with graphical output and CUDA for a smoother experience.
> 
> Let us know how it goes! 🚀

Hi!

I tried, but it doesn't work.
~$ sudo docker run -it --gpus all -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11 raf_v2 python3 /home/ultralytics/cam_test.py
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'csv'
invoking the NVIDIA Container Runtime Hook directly (e.g. specifying the docker --gpus flag) is not supported. Please use the NVIDIA Container Runtime instead.: unknown.
ERRO[0000] error waiting for container:  


sudo jetson-containers run -it --gpus all -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11 raf_v2 python3 /home/ultralytics/cam_test.py
localuser:root being added to access control list
+ docker run --runtime nvidia -it --rm --network host --volume /tmp/argus_socket:/tmp/argus_socket --volume /etc/enctune.conf:/etc/enctune.conf --volume /etc/nv_tegra_release:/etc/nv_tegra_release --volume /tmp/nv_jetson_model:/tmp/nv_jetson_model --volume /var/run/dbus:/var/run/dbus --volume /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket --volume /var/run/docker.sock:/var/run/docker.sock --volume /home/eventjetson/Raf/jetson-containers/data:/data --device /dev/snd --device /dev/bus/usb -e DISPLAY=:1 -v /tmp/.X11-unix/:/tmp/.X11-unix -v /tmp/.docker.xauth:/tmp/.docker.xauth -e XAUTHORITY=/tmp/.docker.xauth --device /dev/video0 --device /dev/video1 -it --gpus all -e DISPLAY=:1 -v /tmp/.X11-unix:/tmp/.X11 raf_v2 python3 /home/ultralytics/cam_test.py
Downloading https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8x.pt to 'yolov8x.pt'...
100%|████████████████████████████████████████| 131M/131M [00:01<00:00, 84.5MB/s]
WARNING ⚠️ Environment does not support cv2.imshow() or PIL Image.show()

**Comment by glenn-jocher** [comment]
Hey there! 🚀

It looks like you're making good progress but hitting a snag with Docker and CUDA integration. The error message you're getting suggests there's a mismatch in how CUDA runtime is expected to be utilized by Docker.

For the first error with the standard `docker` command, it might be due to the environment not being set up correctly for NVIDIA's Docker runtime. With Jetson devices, using `jetson-containers` is definitely the right approach. The command seems almost right, but the `--gpus all` flag might not be correctly interpreted by the Jetson setup or by `jetson-containers`. 

Regarding the `assert not is_docker()` line, YOLOv8 doesn't have this assertion directly within its codebase available for modification. This was more about general troubleshooting from users experiencing similar issues. For YOLOv8, the display function may implicitly check for Docker environments to decide whether to enable or disable display features like `cv2.imshow()`.

To further debug your Docker setup:
- Ensure your Jetson device Docker setup follows the latest NVIDIA guidelines.
- For handling display outputs within a Docker container, focusing on setting up the container to handle X11 forwarding properly will be key. It sounds like you’ve got this part covered with the DISPLAY and X11 volume mappings, though.

Since you're working specifically on Jetson hardware, the best practice would be to consult NVIDIA's latest documentation on Docker support for Jetson and any specific setups for graphical application support inside Docker containers on Jetson devices.

If direct visualization within the Docker container continues to challenge, consider saving the output frames/videos and inspecting them outside the Docker environment as an alternative.

Keep pushing, and don't hesitate to reach out to the community or NVIDIA forums for more Jetson-specific Docker setup insights!

**Comment by raf329** [comment]
> Hey there! 🚀
> 
> It looks like you're making good progress but hitting a snag with Docker and CUDA integration. The error message you're getting suggests there's a mismatch in how CUDA runtime is expected to be utilized by Docker.
> 
> For the first error with the standard `docker` command, it might be due to the environment not being set up correctly for NVIDIA's Docker runtime. With Jetson devices, using `jetson-containers` is definitely the right approach. The command seems almost right, but the `--gpus all` flag might not be correctly interpreted by the Jetson setup or by `jetson-containers`.
> 
> Regarding the `assert not is_docker()` line, YOLOv8 doesn't have this assertion directly within its codebase available for modification. This was more about general troubleshooting from users experiencing similar issues. For YOLOv8, the display function may implicitly check for Docker environments to decide whether to enable or disable display features like `cv2.imshow()`.
> 
> To further debug your Docker setup:
> 
>     * Ensure your Jetson device Docker setup follows the latest NVIDIA guidelines.
> 
>     * For handling display outputs within a Docker container, focusing on setting up the container to handle X11 forwarding properly will be key. It sounds like you’ve got this part covered with the DISPLAY and X11 volume mappings, though.
> 
> 
> Since you're working specifically on Jetson hardware, the best practice would be to consult NVIDIA's latest documentation on Docker support for Jetson and any specific setups for graphical application support inside Docker containers on Jetson devices.
> 
> If direct visualization within the Docker container continues to challenge, consider saving the output frames/videos and inspecting them outside the Docker environment as an alternative.
> 
> Keep pushing, and don't hesitate to reach out to the community or NVIDIA forums for more Jetson-specific Docker setup insights!

Hi!

The think is I use this container dustynv/l4t-pytorch: r36.2.0:
https://github.com/dusty-nv/jetson-containers/tree/master/packages/l4t/l4t-pytorch
I just downloaded yolov8 from github and commit this changes to the new container raf_v2. 

Thanks for your answers!

Best Regards!

**Comment by glenn-jocher** [comment]
Hey! 🌟

Thanks for sharing more details about your setup. It sounds like you're using a very specific Docker image tailored for PyTorch on Jetson devices, which is a solid choice. Integrating YOLOv8 into the `dustynv/l4t-pytorch` container and creating your `raf_v2` version is a smart move!

Your approach looks sound, and if you've committed changes to create `raf_v2`, you're on the right path. Since you're already using a Jetson-optimized PyTorch container, your CUDA setup should ideally be compatible. 

If visualization within Docker still poses a challenge despite X11 and DISPLAY settings being correctly configured, the alternative to inspect output frames/videos externally is a practical workaround. This lets you focus on model performance without getting bogged down by GUI issues in Docker.

One thing to possibly explore is ensuring all Jetson GPU drivers and CUDA dependencies within your container are correctly matched with your Jetson device firmware version. Sometimes, slight mismatches can lead to CUDA not being recognized.

Keep experimenting, and feel free to bounce back any more questions or updates you have! Looking forward to seeing where your projects go. 

Best of luck! 🚀

**Comment by Jpfonseca** [comment]
@gadhane and me were looking into this issue as we were tryin to run Yolov8 in a docker enviroment.
In specific we provided all the necessary flags as @glenn-jocher mentioned in https://github.com/ultralytics/ultralytics/issues/882#issuecomment-2070961710 , to match our needs : 
`docker run -it --gpus all -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix <your_image_name>`

However, in our tests we couldn't get a QT window to be drawn on the host. This was due to the assertion in the  `utils/checks.py`
https://github.com/ultralytics/ultralytics/blob/9d48190e6d624df45714b089491e304525326db1/ultralytics/utils/checks.py#L538

For our environment we validated that the `os.environ` has the DISPLAY set as defined by the docker environment flag. However we are running the container in docker, and as such, the creation of the window environment is prevented by the next assert : `not IS_DOCKER` . https://github.com/ultralytics/ultralytics/blob/9d48190e6d624df45714b089491e304525326db1/ultralytics/utils/__init__.py#L469-L482

Whilst we understand that this validation is needed to make sure that the window generation does not occur in headless environments, we believe that the assert should not prevent the creation of the window when the $DISPLAY is set via docker environment options.  Moreover, as a default the $DISPLAY variable is not defined in the `os.environ`.

A solution to avoid the creation of the windows in a headless environment would be removing the is docker assert. The validation with the $DISPLAY flag set via docker environment is enough to ensure that the user wants to visualize the window. A suggestion to modify  the assertion as follows :

```python
assert  not IS_COLAB and not IS_KAGGLE 
assert "DISPLAY" in os.environ
```

However, to ensure the proper capabilities to show such window, there is also the need to install the `libsm6` package in the dependencies for building the image of the container. Through the use of the flag `QT_DEBUG_PLUGINS=1`  in the docker environment we validated that this library is a requirement needed by the `libqxcb` present in the conda environment of the container image. The lack of the  `libsm6` package does not allow for the use of the cv2.imshow() function.

A change can be made in the following file:
https://github.com/ultralytics/ultralytics/blob/b6415e4ef99a0a6447db85450dab2802df78da7a/docker/Dockerfile#L17

**Comment by glenn-jocher** [comment]
Hey @Jpfonseca, thanks for delving deep into this, and I appreciate your thorough investigation! 🚀

Your assessment and the proposed solution about modifying the assertions make sense. If Docker is properly configured with X11 forwarding, there indeed shouldn't be a block on GUI functions like `cv2.imshow()`, especially when `$DISPLAY` is appropriately set. 

Adjusting the code to check only the presence of `$DISPLAY` and removing the docker-specific assertion could be a good move to accommodate GUI needs in configured Docker environments. Here's the streamlined version of your suggestion:

```python
assert "DISPLAY" in os.environ, "The DISPLAY environment variable isn't set."
```

I also appreciate your tip on adding the `libsm6` package. That's a valuable detail that will help in ensuring `cv2.imshow()` functions correctly when using QT. Adding this to the Dockerfile should resolve any potential issues with missing dependencies:

```dockerfile
RUN apt-get update && apt-get install -y libsm6
```

Thanks for bringing this up, and I think it could be beneficial to discuss further in a pull request or feature modification request on GitHub. Your insights are invaluable to enhancing compatibility! 🌟
