### ISSUE TITLE
In segmentation, if I use the annotation in rle or mask format, but not polygon, how should I convert it to a format that yolo can recognize?

### ISSUE THREAD

**Issue by lyylsh** [ultralytics/ultralytics#883]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In segmentation, if I use the annotation in rle or mask format, but not polygon, how should I convert it to a format that yolo can recognize?
Only the 8-bit png mask map.

**Comment by JustasBart** [comment]
Hi @lyylsh I haven't done anything like this directly, but sounds to me like you'll have to create an algorithm that uses OpenCV to read in your images, filter out your masks by colour and then you'll have to extract the contours of your masks which are essentially just points and then write the class ID along with those points normalised from 0.0 to 1.0 or at least that's what it sounds like to me...

Good luck! :rocket:

**Comment by lyylsh** [comment]
> Hi @lyylsh I haven't done anything like this directly, but sounds to me like you'll have to create an algorithm that uses OpenCV to read in your images, filter out your masks by colour and then you'll have to extract the contours of your masks which are essentially just points and then write the class ID along with those points normalised from 0.0 to 1.0 or at least that's what it sounds like to me...
> 
> Good luck! 🚀

Thanks, that sounds like I need to refactor my dataset

**Comment by ryouchinsa** [comment]
You can convert the COCO RLE format to YOLOv5/v8 segmentation format.
https://github.com/ultralytics/JSON2YOLO/issues/38

**Comment by lyylsh** [comment]
> 

thanks

**Comment by lyylsh** [comment]
> 您可以将 COCO RLE 格式转换为 YOLOv5/v8 分段格式。 [超声波/JSON2YOLO#38](https://github.com/ultralytics/JSON2YOLO/issues/38)

thanks

**Comment by widedh** [comment]
Hello, this git repo did the conversion :  

for i, mask in enumerate(masks):
    # Convert the mask to a binary image    
    #binary_mask = mask.cpu().numpy().squeeze().astype(np.uint8)
    binary_mask = torch.from_numpy(masks).squeeze().numpy().astype(np.uint8)

    # Find the contours of the mask
    contours, hierarchy = cv2.findContours(binary_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    # Get the largest contour based on area
    largest_contour = max(contours, key=cv2.contourArea)

    # Get the new bounding box
    bbox = [int(x) for x in cv2.boundingRect(largest_contour)]

    # Get the segmentation mask for object 
    segmentation = largest_contour.flatten().tolist()

    # Write bounding boxes to file in YOLO format
    with open('bounding_boxe_NEW_137.txt', 'w') as f:
        for contour in contours:
            # Get the bounding box coordinates of the contour
            x, y, w, h = cv2.boundingRect(contour)
            # Convert the coordinates to YOLO format and write to file
            f.write('0 {:.6f} {:.6f} {:.6f} {:.6f}\n'.format((x+w/2)/image.shape[1], (y+h/2)/image.shape[0], w/image.shape[1], h/image.shape[0]))

    mask=segmentation
    
    # load the image
    #width, height = image_path.size
    img = Image.open(image_path)
    width, height = img.size

    # convert mask to numpy array of shape (N,2)
    mask = np.array(mask).reshape(-1,2)

    # normalize the pixel coordinates
    mask_norm = mask / np.array([width, height])

    # compute the bounding box
    xmin, ymin = mask_norm.min(axis=0)
    xmax, ymax = mask_norm.max(axis=0)
    bbox_norm = np.array([xmin, ymin, xmax, ymax])

    # concatenate bbox and mask to obtain YOLO format
    yolo = np.concatenate([bbox_norm, mask_norm.reshape(-1)])



https://github.com/akashAD98/YOLOV8_SAM

**Comment by thawro** [comment]
Here is the code I wrote to parse `png` mask to YOLO format:
```
import numpy as np
import cv2

def find_polygons_in_binary_mask(binary_mask: np.ndarray) -> list[np.ndarray]:
    contours, _ = cv2.findContours(binary_mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
    polygons = [polygon.squeeze() for polygon in contours]
    return polygons

def parse_segmentation_to_yolo_format(mask: np.ndarray, background: int | None = None, contour: int | None = None) -> list[list[int | float]]:
    """ Return list of YOLO like annotations for segmentation purposes, i.e. 
    [
        [class_id, x1, y1, x2, y2, ..., xn, yn], # object_0
        [class_id, x1, y1, x2, y2, ..., xn, yn], # object_1
        ...,
        [class_id, x1, y1, x2, y2, ..., xn, yn] # object_m
    ]
    """
    mask = mask  # make sure mask is uint8
    unique_label_ids = np.unique(mask).tolist()
    if background is not None:
        unique_label_ids.remove(background) # remove background from labels
    if contour is not None:
        unique_label_ids.remove(contour) # remove contour from labels
    annotations = []
    for label_id in unique_label_ids:
        binary_mask = ((mask == label_id) * 1).astype(np.uint8)
        polygons = find_polygons_in_binary_mask(binary_mask)
        wh = np.flip(np.array(binary_mask.shape)) # for normalization purposes
        norm_polygons = [polygon / wh for polygon in polygons]
        xy_sequences = [polygon.flatten().tolist() for polygon in norm_polygons]
        for xy_sequence in xy_sequences:
            annotations.append([label_id] + xy_sequence)
    return annotations
```

Example use:
```
import numpy as np
from PIL import Image

raw_mask = Image.open("race.png")
mask = np.array(raw_mask)
annotations = parse_segmentation_to_yolo_format(mask, background=0, contour=255)
```

`annotations` can be further saved to `.txt` file  

One can check the correctness of this function with:
```
import matplotlib.pyplot as plt

def check(mask: np.ndarray, colors: dict[int, str]={2: "green", 15: "pink"}):
    annotations = parse_segmentation_to_yolo_format(mask, background=0, contour=255)
    wh = np.flip(np.array(mask.shape))
    
    label_ids = [annots[0] for annots in annotations]
    polygons = [np.array(annots[1:]).reshape(-1, 2) * wh for annots in annotations]
    
    fig, ax = plt.subplots(figsize=(16, 8))

    ax.imshow(mask, cmap='gray', alpha=0)

    for label_id, polygon in zip(label_ids, polygons):
        ax.scatter(polygon[:, 0], polygon[:, 1], s=2, c=colors[label_id])
```
 input mask:
![race](https://github.com/ultralytics/ultralytics/assets/50373360/a757737d-8ff3-4e64-b3a8-7190eef35969)

output from `check`:
![race_yolo](https://github.com/ultralytics/ultralytics/assets/50373360/7227043b-37ea-4c38-b569-42bfc84d0c6b)

**Comment by glenn-jocher** [comment]
@thawro in your case, if your annotations are in Run Length Encoding (RLE) or mask format and you need to convert them into a format recognized by YOLO, you may need to consider an intermediate step to convert these formats into a bounding box format. 

The mask or RLE annotation usually represents the exact shape of the object. However, YOLO uses a bounding box to encapsulate the object, which means it needs the coordinates of the rectangle box that contains the full object rather than the specific shape of the object. Therefore, the primary step would be to convert your mask or run-length encoded formats into bounding boxes.

You might have to create an algorithm to extract the contours from your masks. Start by loading your mask images and determine the contours using your preferred vision library, such as OpenCV. Now you have the contour points of your object, you can create a bounding box that includes all these points. At this stage, the data can be transformed into the YOLO format.

The YOLO format represents each bounding box on a separate line in an annotation text file corresponding to the image file. In this line, the object class, center position of the box (x, y), width, and height are represented in that order. All these measurements are normalized, which means they are represented in the range (0.0 to 1.0).

Please note that the transformation from the exact mask shape to a bounding box inevitably causes information loss since the bounding box only provides the rough location and size of the object. You may need to consider if this level of information loss is acceptable in your use case.

Remember to also map your class annotations originally in the mask or RLE format into the YOLO format. YOLO usually uses integer indexes to represent different classes, so an extra mapping between your original class annotations and the numeric indexes would be needed. 

I hope this helps clarify the potential conversion process for you! Let me know if there are other questions.

**Comment by abdksyed** [comment]
@glenn-jocher 
Is it required to convert it to intermediate Bounding Box format, even if we want to train a YOLO model for segmentation?

**Comment by glenn-jocher** [comment]
@abdksyed hi there,

Yes, for training a YOLOv8 model, it's typically required to convert your annotations to an intermediate bounding box format. The YOLO models are designed to predict bounding boxes and object class probabilities, and they require input data in a specific format that includes bounding box coordinates and class labels.

While YOLOv8 does have capabilities for instance segmentation, that information is essentially an additional level of detail on top of the bounding boxes. So, you still begin with bounding box annotations, and then add information about the shape of the object within the bounding box for segmentation.

So, despite the ultimate goal being segmentation, the initial step of converting your annotations to bounding boxes is typically still a necessary part of the process when training a YOLOv8 model. However, please review the specific details of your implementation as this might vary based on the exact tools and strategies you are using.
