### ISSUE TITLE
How to disable verification during training

### ISSUE THREAD

**Issue by liugui7** [ultralytics/ultralytics#8847]
The validation set is empty, and the parameters for validation during training are False, but error happen:

File "/converter_app/ultralytics/engine/trainer.py", line 192, in train
--
Mon, Mar 11 2024 5:22:05 pm | self._do_train(world_size,progress_status)
Mon, Mar 11 2024 5:22:05 pm | File "/converter_app/ultralytics/engine/trainer.py", line 288, in _do_train
Mon, Mar 11 2024 5:22:05 pm | self._setup_train(world_size)
Mon, Mar 11 2024 5:22:05 pm | File "/converter_app/ultralytics/engine/trainer.py", line 255, in _setup_train
Mon, Mar 11 2024 5:22:05 pm | self.test_loader = self.get_dataloader(self.testset, batch_size=batch_size * 2, rank=-1, mode='val')
Mon, Mar 11 2024 5:22:05 pm | File "/converter_app/ultralytics/models/yolo/classify/train.py", line 88, in get_dataloader
Mon, Mar 11 2024 5:22:05 pm | dataset = self.build_dataset(dataset_path, mode)
Mon, Mar 11 2024 5:22:05 pm | File "/converter_app/ultralytics/models/yolo/classify/train.py", line 83, in build_dataset
Mon, Mar 11 2024 5:22:05 pm | return ClassificationDataset(root=img_path, args=self.args, augment=mode == 'train', prefix=mode)
Mon, Mar 11 2024 5:22:05 pm | File "/converter_app/ultralytics/data/dataset.py", line 220, in __init__
Mon, Mar 11 2024 5:22:05 pm | super().__init__(root=root)
Mon, Mar 11 2024 5:22:05 pm | File "/opt/conda/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 309, in __init__
Mon, Mar 11 2024 5:22:05 pm | super().__init__(
Mon, Mar 11 2024 5:22:05 pm | File "/opt/conda/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 145, in __init__
Mon, Mar 11 2024 5:22:05 pm | samples = self.make_dataset(self.root, class_to_idx, extensions, is_valid_file)
Mon, Mar 11 2024 5:22:05 pm | File "/opt/conda/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 189, in make_dataset
Mon, Mar 11 2024 5:22:05 pm | return make_dataset(directory, class_to_idx, extensions=extensions, is_valid_file=is_valid_file)
Mon, Mar 11 2024 5:22:05 pm | File "/opt/conda/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 61, in make_dataset
Mon, Mar 11 2024 5:22:05 pm | directory = os.path.expanduser(directory)
Mon, Mar 11 2024 5:22:05 pm | File "/opt/conda/lib/python3.10/posixpath.py", line 232, in expanduser
Mon, Mar 11 2024 5:22:05 pm | path = os.fspath(path)
Mon, Mar 11 2024 5:22:05 pm | TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by glenn-jocher** [comment]
@liugui7 hey there! 👋 It looks like the issue arises because the validation dataset path is not properly set, leading to a `NoneType` error when it's expected to be a string or path-like object. Even if you've set validation parameters to `False`, the code still attempts to prepare the validation set, hence the error.

A quick workaround could be to ensure that a valid path is provided for the validation dataset, even if it's not going to be used. For example, you could point it to your training dataset just to bypass this error:

```python
# Assuming 'data' is your configuration dictionary
data['val'] = data['train']
```

This way, the code has a valid path to work with and shouldn't throw the `NoneType` error. Hope this helps! Let us know if you encounter any more issues. 😊
