### ISSUE TITLE
Accumulate output in single folder in prediction task using numpy array.

### ISSUE THREAD

**Issue by GISScience** [ultralytics/ultralytics#8850]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Thanks for great software.
i am using OBB prediction using numpy array 

input_image= //create a numpy array from simple python array
model = YOLO('yolov8x-obb.yaml')
results = model.predict( images=input_image, save=True,project="/path/to/output" , already_exist = True  ) //syntax might be slightly here and there but its working 
I am using predict with numpy array , project folder , already_exist as True and also saving text label and jpg output . 

My intension to only get labels.txt and output.jpg and do some post-processing by monitoring these files as soon as created. 
Output is written correct but for every new numpy array , it is creating a new folder.
for numpyarry1 --> txt output is /path/to/output/numpyarry1/label/image0.txt
                          --> jpg output is /path/to/output/numpyarry1/image0.jpg
for numpyarry2 --> txt output is /path/to/output/numpyarry1/label/image0.txt
                          --> jpg output is /path/to/output/numpyarry2 /image0.jpg
for numpyarry3 --> txt output is /path/to/output/numpyarry3 /label/image0.txt
                          --> jpg output is /path/to/output/numpyarry3 /image0.jpg

using already_exist = True , it is not appening numbers like 1 , 2 , 3 ... etc on every run but create a new folder with  numpy array name.

My requirement is only to write 
for numpyarry1 --> txt output as /path/to/output/numpyarry1.txt
                          --> jpg output is /path/to/output/numpyarry1.jpg
for numpyarry2 --> txt output as /path/to /output/numpyarry2.txt
                          --> jpg output is /path/to/output/numpyarry2.jpg
for numpyarry3 --> txt output as /path/to/output/numpyarry3.txt
                          --> jpg output is /path/to/output/numpyarry3.jpg

i want to accumulate evey output in one folder ,all the label.txt and ouput.jpg with name of input numpy buffer,

how i should do that , I have to do many post-processing task ,which is very difficult with eveytime new folder , its easy to monitor multiple output files in one folder.

Please guide me.

### Use case

I have to do many post-processing task ,which is very difficult with eveytime new folder , its easy to monitor multiple output files in one folder.

### Additional

i have checked full documentation with following issues but couldn't find anything related to this.
https://github.com/ultralytics/ultralytics/issues/8199
https://github.com/ultralytics/ultralytics/issues/7857
https://github.com/ultralytics/ultralytics/issues/7864

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@GISScience hello! Thanks for reaching out and for your kind words about our software. 🙌

For your requirement to accumulate all outputs in a single folder with specific naming conventions for `.txt` and `.jpg` files, you might need to slightly adjust your approach since the current functionality automatically organizes outputs into separate folders to manage different inputs more systematically.

However, you can achieve your desired output structure by manually renaming and moving the files after they are created. Here's a quick Python snippet that might help:

```python
import os
import shutil

# Assuming 'results' is your prediction output
for path in results.files:
    # Extract the base name for the current numpy array
    base_name = os.path.basename(path).split('.')[0]
    # Define new paths for the .txt and .jpg files
    new_txt_path = os.path.join("/path/to/output", f"{base_name}.txt")
    new_jpg_path = os.path.join("/path/to/output", f"{base_name}.jpg")
    # Move and rename the files
    if path.endswith('.txt'):
        shutil.move(path, new_txt_path)
    elif path.endswith('.jpg'):
        shutil.move(path, new_jpg_path)
```

This script assumes that `results.files` contains paths to the saved `.txt` and `.jpg` files. You'll need to adjust the logic based on how you're accessing these file paths in your actual implementation.

While this adds an extra step, it allows you to organize the output files according to your specific requirements without waiting for a direct feature implementation. 

Hope this helps! If you have further questions or need more assistance, feel free to ask.
