### ISSUE TITLE
RT- DETR question

### ISSUE THREAD

**Issue by sreesankar711** [ultralytics/ultralytics#8860]
Issue Description:

I'm trying to continue training on a saved checkpoint using RTDETR from Ultralytics, but when I load the model with RTDETR('/kaggle/working/epoch8.pt'), it's showing as YOLOv8 instead of RTDETR. Is this a bug or just a naming convention issue?
Also during fresh start, this is named as same.

Steps to Reproduce:

```
from ultralytics import RTDETR
model = RTDETR('/kaggle/working/epoch8.pt')
model.info()
results = model.train(data='/kaggle/working/datasets/tables/data.yaml', resume ='true')
```

Expected Behavior:

The model should be loaded as RTDETR since I'm using the RTDETR class from Ultralytics.

Actual Behavior:

![image](https://github.com/ultralytics/ultralytics/assets/100954808/32e8d7ef-15aa-414b-9392-5d3729b777f0)
The model is showing as YOLOv8 instead of RTDETR.

Additional Information:

is this just a naming bug only
Is this the correct way to load RTDETR checkpoints for continued training?
If I want to change backbone to resnet18, can I do it in pip version or only by git clone this repo. Also Should i use pretrained weights for backbone.

**Comment by glenn-jocher** [comment]
@sreesankar711 hello! Thanks for reaching out with your question. 🌟

It seems like you're encountering an issue with the model type being displayed incorrectly. This could be due to how the model information is being interpreted or displayed, rather than an actual issue with the model itself. The naming might indeed be a bit misleading, but rest assured, if you're using the `RTDETR` class to load your model, you're working with an RT-DETR model.

To ensure you're loading the RTDETR model correctly for continued training, your approach seems fine. However, make sure that the checkpoint (`epoch8.pt`) was indeed saved using the RTDETR model. If it was initially trained and saved as a YOLOv8 model, it might cause confusion when loading.

Regarding changing the backbone to `resnet18`, you can indeed modify the backbone of the model. This typically requires adjusting the model's configuration or initialization code. If you're working directly with the Ultralytics repository, you might need to clone the repo to make such modifications. Here's a simplified example of how you might specify a different backbone during model initialization (note: this is a conceptual example and might require adjustments based on the actual RTDETR implementation):

```python
model = RTDETR(backbone='resnet18')
```

For using pretrained weights with the new backbone, you would generally specify this during the model initialization as well, often with a flag or by providing a path to the pretrained weights.

If you're working with the pip version of our package, some of these customizations might be limited based on the current implementation and exposed functionalities. Cloning the repo often gives you more flexibility to modify the model's architecture and training process.

I hope this helps clarify your concerns! If you have further questions or need more detailed guidance, feel free to ask. Happy coding! 😊

**Comment by pjafary** [comment]
> @sreesankar711 hello! Thanks for reaching out with your question. 🌟
> 
> It seems like you're encountering an issue with the model type being displayed incorrectly. This could be due to how the model information is being interpreted or displayed, rather than an actual issue with the model itself. The naming might indeed be a bit misleading, but rest assured, if you're using the `RTDETR` class to load your model, you're working with an RT-DETR model.
> 
> To ensure you're loading the RTDETR model correctly for continued training, your approach seems fine. However, make sure that the checkpoint (`epoch8.pt`) was indeed saved using the RTDETR model. If it was initially trained and saved as a YOLOv8 model, it might cause confusion when loading.
> 
> Regarding changing the backbone to `resnet18`, you can indeed modify the backbone of the model. This typically requires adjusting the model's configuration or initialization code. If you're working directly with the Ultralytics repository, you might need to clone the repo to make such modifications. Here's a simplified example of how you might specify a different backbone during model initialization (note: this is a conceptual example and might require adjustments based on the actual RTDETR implementation):
> 
> ```python
> model = RTDETR(backbone='resnet18')
> ```
> 
> For using pretrained weights with the new backbone, you would generally specify this during the model initialization as well, often with a flag or by providing a path to the pretrained weights.
> 
> If you're working with the pip version of our package, some of these customizations might be limited based on the current implementation and exposed functionalities. Cloning the repo often gives you more flexibility to modify the model's architecture and training process.
> 
> I hope this helps clarify your concerns! If you have further questions or need more detailed guidance, feel free to ask. Happy coding! 😊

Hi Glenn
I am trying to train RTDETR with different backbones to compare them and when I use the code you provided, I get the error below:
Traceback (most recent call last):
  File "/home/parham/yolov10/RT-DETR-train.py", line 4, in <module>
    model = RTDETR(backbone='resnet18')
TypeError: __init__() got an unexpected keyword argument 'backbone'


I have also tried: 
---- model = RTDETR("rtdetr-l.pt", backbone='resnet18')
---- model = RTDETR(backbone='resnet18')
---- model = RTDETR(backbone="resnet18")
---- model = RTDETR(backbone='resnet50')
---- model = RTDETR(backbone='resnet101')

all of them return the same error.

could you also elaborate a little on the difference of rtdetr-l.pt and rt-detr-x.pt? are the backbones different?

**Comment by sreesankar711** [comment]
Hey,
Just to chime in, the error is due to invalid arg, 'backbone'. Inorder to use ur own backbones u have to define a .yaml file and call it using 

`
model = RTDETR('rtdetr-resnet101.yaml')
`

**Comment by sreesankar711** [comment]
Also ig this 101 and 50 and predefined and if u need smaller ones u might have to define urself.

**Comment by pjafary** [comment]
Hey
Thank you for the comment, I thought pre-trained, weights exist, as they exist with Mask-RCNN, and I didn't want to start from scratch from yaml file.

**Comment by glenn-jocher** [comment]
@pjafary thank you for your comment. Currently, to use custom backbones with RTDETR, you need to define them in a `.yaml` file and load the model using that configuration. Pre-trained weights for specific backbones like `resnet101` and `resnet50` are predefined, but for others, you might need to define and train them yourself.

**Comment by pjafary** [comment]
Thank you for your reply and information.

**Comment by glenn-jocher** [comment]
@pjafary you're welcome! If you need further assistance with defining custom backbones in the `.yaml` file or any other questions, feel free to ask.
