### ISSUE TITLE
YOLOv8n-pose - pose keypoints to body part mapping

### ISSUE THREAD

**Issue by tomershukhman** [ultralytics/ultralytics#8891]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,
First sorry for the rookie question
I want to create an app that does some analytics based on spacific body parts movments but I am unable to find the mapping between the keypoints indexses to thier body part
I have found this on [medium](https://alimustoofaa.medium.com/yolov8-pose-estimation-and-pose-keypoint-classification-using-neural-net-pytorch-98469b924525) but nothing on the offical site.
What am I missing?

**Comment by Burhan-Q** [comment]
@tomershukhman I think I may have replied to you in our Discord server as well, but I'll also post it here for anyone else in the future with a similar question.

Although it causes some confusion, the reason you don't find anything about it is because there is not _really_ a standard for mapping parts to points. The COCO dataset uses 17 keypoints for the `person` class, but there's nothing stopping you from using 5 or 50. The only requirement is that the keypoint order is **always** the same for all annotations. 

For instance, I have seen keypoints annotated for other objects, like a bottle or glass that only uses 4-10 keypoints, but as long as you annotate the points in the same order, every time, you're good. One example is the [Tiger Pose dataset example](https://docs.ultralytics.com/datasets/pose/tiger-pose/) from our docs of creating custom data for a non-human class.
