### ISSUE TITLE
CLI "yolo predict [...] show=True" Only shows image for hal a second on MacBook Pro 16 Intel

### ISSUE THREAD

**Issue by olve-d** [ultralytics/ultralytics#891]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection, Integrations

### Bug

Using YOLOv8 CLI I want to show the prediction output as an image with boxes:

`yolo predict model=yolov8n.pt source="https://ultralytics.com/images/bus.jpg" show=True box=True`

The result image appears on my screen for only half a second at most while the Python process is running, then it disapears.

Console output:
```
Ultralytics YOLOv8.0.32 🚀 Python-3.10.6 torch-1.13.1 CPU
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

Found https://ultralytics.com/images/bus.jpg locally at bus.jpg
image 1/1 /Users/a5050k6/git/yolo/bus.jpg: 640x480 4 persons, 1 bus, 1 stop sign, 96.6ms
Speed: 1.9ms pre-process, 96.6ms inference, 16.5ms postprocess per image at shape (1, 3, 640, 640)
```

What I would like and expect to happen is the image keeps displaying until I dismiss it, or that there would be an option for me to save the image with the bounding boxes/labels as it's shown so that I could open it myself and look at it.

### Environment

- Ultralytics YOLOv8.0.32 🚀 Python-3.10.6 torch-1.13.1 CPU
- macOS 13.1 (22C65), using zsh (z shell)
- Python 3.10.6

### Minimal Reproducible Example

python -m pip install ultralytics && yolo predict model=yolov8n.pt source="https://ultralytics.com/images/bus.jpg" show=True box=True

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by kyoko9000** [comment]
you should put   save=True    with image detection, show = True use with webcam or video

**Comment by olve-d** [comment]
Ok, so no way of showing the image without saving it then! I figured out that you could save it, but was still wondering about the showing functionality. Thanks!

**Comment by amaalanoosucs** [comment]
I might be late, but you can you the below script to show the image without saving. 

got it from here. (https://docs.ultralytics.com/reference/engine/results/#ultralytics.engine.results.Results.plot)

from PIL import Image
from ultralytics import YOLO

img = path/to/image
results = model(img, verbose=False) 

for r in results:
    im_array = r.plot()  # plot a BGR numpy array of predictions
    im = Image.fromarray(im_array[..., ::-1])  # RGB PIL image
    im.show()

**Comment by glenn-jocher** [comment]
@amaalanoosucs i'm glad you found another way to display your image. However, it's important to note that in the context of the command-line interface (CLI), the behavior you described is expected: the image is displayed briefly and then closed. 

The `show=True` function in the CLI call is primarily meant for real-time display during video predictions, outputting frames as they are processed. This is why it only displays briefly in the case of single images.

For a static image, using the `save=True` parameter allows you to store the result for further investigation. Instead of just showing the image briefly, it gets saved as an output file you can access anytime. This is the recommended approach when using the CLI.

The Python code you found is useful when working with a Python script and you want to display the image within the Python environment. It enables the image to stay open as long as the Python process keeps running. But this approach is not applicable in the CLI environment, due to its difference in function execution and process handling.

In any case, your input is appreciated. It will help inform enhancements in future versions of the YOLOv8 software. Keep exploring, and do let us know if you stumble upon any more interesting findings or have more questions.
