### ISSUE TITLE
Waiting for stream 0  when detect youtube video use CLI

### ISSUE THREAD

**Issue by Yutse962** [ultralytics/ultralytics#8914]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am not sure is a issue or not, but when I run the command in quickstart doc :
   yolo predict model=yolov8n-seg.pt source='https://youtu.be/LNwODJXcvt4' imgsz=320
   
It will shows like this:
0:192x320 1 person, 1 potted plant, 7.8ms
WARNING ⚠️ Waiting for stream 0
WARNING ⚠️ Waiting for stream 0
WARNING ⚠️ Waiting for stream 0
WARNING ⚠️ Waiting for stream 0
WARNING ⚠️ Waiting for stream 0
WARNING ⚠️ Waiting for stream 0
WARNING ⚠️ Waiting for stream 0
WARNING ⚠️ Waiting for stream 0
WARNING ⚠️ Waiting for stream 0
WARNING ⚠️ Waiting for stream 0
WARNING ⚠️ Waiting for stream 0
WARNING ⚠️ Waiting for stream 0
WARNING ⚠️ Waiting for stream 0
WARNING ⚠️ Waiting for stream 0
WARNING ⚠️ Waiting for stream 0
0: 192x320 1 person, 1 potted plant, 7.9ms
WARNING ⚠️ Waiting for stream 0

But the result goes well,
Is there something I missed?

**Comment by Yutse962** [comment]
Thank you with the quick reply, the warnings does not impacting the output.
By the way,  the --stream-buffer 2048 not work on command line, and I try the argument stream_buffer=True, the warning reduce a bit but not totally resolve

**Comment by glenn-jocher** [comment]
@Yutse962 Glad to hear the warnings aren't impacting your output! 😊 It seems there was a misunderstanding regarding the `--stream-buffer` option, my apologies for any confusion. The `stream_buffer` argument is indeed the correct way to attempt to mitigate the warnings, though it might not eliminate them entirely due to the nature of streaming video content.

If `stream_buffer=True` helped reduce the warnings, that's a step in the right direction. Unfortunately, some level of buffering warnings can be expected due to network variability and the inherent unpredictability of streaming data.

If the warnings are not affecting your results and the process completes successfully, it's generally safe to proceed. If you're looking for a completely warning-free experience, you might consider downloading the video for local processing, though I understand that might not always be feasible.

Keep up the great work, and feel free to reach out if you have more questions or need further assistance!
