### ISSUE TITLE
"classes is not a valid key. Similar keys:['cls]" ?

### ISSUE THREAD

**Issue by hsauod** [ultralytics/ultralytics#8953]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

Hi, thank you for your amazing work!

When I use " model.predict"  in my python script on Linux, it works fine. 

But when I run the same code on Windows 10, it shows : "classes is not a valid key. Similar keys:['cls]; stream is not a valid key. Similar keys:[]". It's wired to me.

My code is pretty simple:

results = model.predict("myvideo.mp4",  imgsz =1088, classes=31, max_det=1, stream=True) 

On my windows 10, no warnings or errors related to  "imgsz"  and "max_det=1", but only on "classes" and "stream" args. 
On my linux, everythings is fine.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@hsauod hi there! 🌟

Thanks for reaching out and sharing your experience! It seems there's a slight mix-up in argument names. For specifying classes during `predict` in YOLOv8, you should use `cls` instead of `classes`. As for the `stream` argument, currently, `predict` mode does not support streaming directly through this argument, which is why you're seeing the error on Windows. The `stream` functionality is handled differently inside the code.

Here's a quick fix for your code snippet:
```python
results = model.predict("myvideo.mp4", imgsz=1088, cls=31, max_det=1)
```
For streaming videos, you might want to use the `track` mode, which is designed for video inputs and supports frame-by-frame processing or consider manually managing the video stream and passing individual frames to `predict`.

If you have any more questions or need further assistance, feel free to ask. Happy coding! 😊
