### ISSUE TITLE
ModuleNotFoundError: No module named 'ultralytics.utils'

### ISSUE THREAD

**Issue by Fadatsai9457** [ultralytics/ultralytics#8960]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

Hello,
I've successfully performed predictions using the command line interface (CLI) without any issues. However, I'm facing difficulties when attempting to replicate the process through a Python script. Despite following similar steps, and load the official model first, the Python script doesn't seem to execute the predictions correctly. Could there be a specific reason for this discrepancy? Any insights or suggestions would be greatly appreciated.
![image](https://github.com/ultralytics/ultralytics/assets/55202414/e1cb62fb-52e8-4178-9f8f-dd7fe4827496)
![image](https://github.com/ultralytics/ultralytics/assets/55202414/a86e2f4a-4983-4bbd-a475-5f54a8345b58)

### Environment

![image](https://github.com/ultralytics/ultralytics/assets/55202414/6b33e66e-6d61-426d-8802-8b224a9e9d4e)

### Minimal Reproducible Example

from ultralytics import YOLO

# Load a model
model = YOLO('yolov8s-cls.pt')  # load an official model
model = YOLO('best_3cls_200.pt')  # load a custom model

# Predict with the model
results = model('545_L2.png')  # predict on an image

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Fadatsai9457 hey there! 👋 It looks like you're encountering an issue related to the Ultralytics import in your Python script. The error `ModuleNotFoundError: No module named 'ultralytics.utils'` suggests that the Ultralytics package might not be correctly installed or recognized in your Python environment.

Before diving into code specifics, let's ensure that the Ultralytics YOLOv8 package is correctly installed. You can do this by running:

```bash
pip install ultralytics
```

If you've already installed it and are still facing issues, it could be due to the environment paths or using a different Python environment where the package is not installed. Try activating the correct environment if you’re using conda or virtualenv.

A quick tip: Ensure the `from ultralytics import YOLO` statement is correctly placed at the beginning of your script and there are no typos.

Also, your Python script seems correct at a glance. However, note that loading multiple models successively without utilizing them might not be what you intend. Here's a refined version if you're looking to predict with both models:

```python
from ultralytics import YOLO

# Load and predict with the official model
model_official = YOLO('yolov8s-cls.pt')
results_official = model_official.predict('545_L2.png')

# Load and predict with a custom model
model_custom = YOLO('best_3cls_200.pt')
results_custom = model_custom.predict('545_L2.png')
```

Ensure you've got the 'predict' method after loading your models. If the issue persists, the environment details or the complete error message would be helpful for further diagnosis. 🛠️

Glad to hear you're willing to contribute! If you discover a solution during your exploration, feel free to suggest it. Your insights could be valuable to the community. 🌟

**Comment by Fadatsai9457** [comment]
@glenn-jocher, I so appreciate your help! I copied your code into my script and compiled it. However, it still doesn't work....
The error message shows as follow:

> (yolov8) PS G:\yolov8> python predict.py
> WARNING  Ultralytics settings reset to defaults. This is normal and may be due to a recent ultralytics package update, but may have overwritten previous settings. 
> View and update settings with 'yolo settings' or at 'C:\Users\tingw\AppData\Roaming\Ultralytics\settings.yaml'
> 
> **image 1/1 G:\yolov8\545_L2.png: 224x224 apiary 0.24, washbasin 0.10, honeycomb 0.07, padlock 0.04, medicine_chest 0.03, 68.8ms**
> Speed: 9.0ms preprocess, 68.8ms inference, 0.0ms postprocess per image at shape (1, 3, 224, 224)
> WARNING  best_3cls_200.pt appears to require 'ultralytics.utils', which is not in ultralytics requirements.
> AutoInstall will run now for 'ultralytics.utils' but this feature will be removed in the future.
> Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt'
> requirements: Ultralytics requirement "ultralytics.utils" not found, attempting AutoUpdate...
> ERROR: Could not find a version that satisfies the requirement ultralytics.utils (from versions: none)
> ERROR: No matching distribution found for ultralytics.utils
> requirements:  Command 'pip install --no-cache "ultralytics.utils"  ' returned non-zero exit status 1.
> Traceback (most recent call last):
>   File "G:\yolov8\ultralytics\nn\tasks.py", line 381, in torch_safe_load
>     return torch.load(file, map_location='cpu'), file  # load
>   File "C:\Users\tingw\miniconda3\envs\yolov8\lib\site-packages\torch\serialization.py", line 1026, in load
>     return _load(opened_zipfile,
>   File "C:\Users\tingw\miniconda3\envs\yolov8\lib\site-packages\torch\serialization.py", line 1438, in _load
>     result = unpickler.load()
>   File "C:\Users\tingw\miniconda3\envs\yolov8\lib\site-packages\torch\serialization.py", line 1431, in find_class
>     return super().find_class(mod_name, name)
> ModuleNotFoundError: No module named 'ultralytics.utils'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "predict.py", line 8, in <module>
>     model_custom = YOLO('best_3cls_200.pt')
>   File "G:\yolov8\ultralytics\yolo\engine\model.py", line 107, in __init__
>     self._load(model, task)
>   File "G:\yolov8\ultralytics\yolo\engine\model.py", line 156, in _load
>     self.model, self.ckpt = attempt_load_one_weight(weights)
>   File "G:\yolov8\ultralytics\nn\tasks.py", line 441, in attempt_load_one_weight
>     ckpt, weight = torch_safe_load(weight)  # load ckpt
>   File "G:\yolov8\ultralytics\nn\tasks.py", line 396, in torch_safe_load
>     return torch.load(file, map_location='cpu'), file  # load
>   File "C:\Users\tingw\miniconda3\envs\yolov8\lib\site-packages\torch\serialization.py", line 1026, in load
>     return _load(opened_zipfile,
>   File "C:\Users\tingw\miniconda3\envs\yolov8\lib\site-packages\torch\serialization.py", line 1438, in _load
>     result = unpickler.load()
>   File "C:\Users\tingw\miniconda3\envs\yolov8\lib\site-packages\torch\serialization.py", line 1431, in find_class
>     return super().find_class(mod_name, name)
> ModuleNotFoundError: No module named 'ultralytics.utils'

It seems that the official weight works, but the custom weight doesn't. When I use the CLI, everything is fine. I just couldn't understand it.
![image](https://github.com/ultralytics/ultralytics/assets/55202414/6e0a1dd7-9e54-4dfa-8ab1-fe99f99a293f)

**Comment by glenn-jocher** [comment]
@Fadatsai9457 hey there! 🌟 Thanks for reaching out and for the detailed information. It seems like you're encountering a specific issue related to your custom model, `best_3cls_200.pt`, which appears to be referencing a non-existent module `ultralytics.utils`. This might occur if the model was trained in an older or different version of the Ultralytics YOLO package wherein `ultralytics.utils` was still utilized.

Here's a couple of suggestions you might find useful:
- **Update Your Ultralytics Package**: Make sure your Ultralytics package is up-to-date with the latest version as it might resolve unknown references or dependency issues. You can update it using:
    ```bash
    pip install ultralytics --upgrade
    ```
- **Re-train the Model (If Possible)**: If updating doesn't help, and if it's feasible, consider re-training your model with the current version of Ultralytics YOLO. This should ensure compatibility and eliminate the error.

For the moment, to bypass the error and get your script running with the official weights, you could temporarily remove or comment out the custom model lines. This isn't a fix but rather a way to continue working with the official models until a better solution can be found for your custom model.

Lastly, 🛠 you're absolutely right; the complexities sometimes behave differently when transitioning from CLI to script execution due to environment or version discrepancies. Your feedback is immensely valuable in enhancing our documentation and troubleshooting guides.

If re-training is not possible or the problem persists, feel free to revert, and we'll explore further avenues. Your adventure with YOLOv8 is important to us! 💫

**Comment by Peungwon** [comment]
This is an extremely brutal bug that took me a few days but can be solved.

This bug can occur if you have a yolo-v8 folder in your home directory (e.g. /home/tj/yolo-v8).

I searched this folder, and found the location of the utils folder (which was inside /home/tj/yolo-v8/ultralytics/yolo/utils). I then copied the utils folder and made sure it existed as: /home/tj/yolo-v8/ultralytics/utils

Then I would get a new error: FileNotFoundError: [Errno 2] No such file or directory: '/home/tj/yolo-v8/yolo/cfg/default.yaml'

So I found the default.yaml file under /home/tj/yolo-v8/ultralytics/yolo/cfg/default.yaml, copied it, and made sure it existed as: /home/tj/yolo-v8/yolo/cfg/default.yaml

Now I can run it in both CLI and python!

**Comment by glenn-jocher** [comment]
Hey there! 🌟 Thanks for sharing your experience and the solution you found for this gnarly bug. It sounds like a real adventure, and your persistence is commendable! Your findings might help somebody else facing the same issue. 

For a quick recap, if anyone runs into similar troubles, try checking your directory structure to ensure that necessary files and folders (like `utils` and `cfg/default.yaml`) are correctly placed as per the package's expectations. 

Sometimes, directory or path misconfigurations can lead to such issues. Doing a quick directory audit, as you did, can solve these pesky problems. 🚀

Glad to hear you got everything up and running both on CLI and Python! Your tip could be a valuable resource for the YOLOv8 community. Thanks again for sharing!
