### ISSUE TITLE
YOLOv8 manual training loop

### ISSUE THREAD

**Issue by Suihko** [ultralytics/ultralytics#8964]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi! I asked a question about a manual training loop at the Ultralytics Train page, and go some initial code to work with.
I've since then stumbled upon some more issues. 

Firstly, how do I set the model to training mode or validation mode for a manual training loop? When writing model.train(), model.eval(), or model.val(), it does not set a "model mode". For model.train() it starts a default training of 100 epochs, searches for the COCO dataset, and does training on no data. 

Secondly, in my current script for manual training, the main structure provided by Paula Derrenger, is not working as expected. The forward pass: loss, output = model(images, targets) throws the following error. RuntimeError: Boolean value of Tensor with more than one value is ambiguous. I debugged and the function seems to indeed want a boolean value. That is contradictory, because I cant see how my label bounding boxes can be boolean?

`loss, output = model(images, targets)`

The target is my labels, tensors of my bounding boxes: [class_id, x_center, y_center, width, height]. The tensors are also created of equal size, because of another error that required that. RuntimeError: stack expects each tensor to be equal size, but got [4, 5] at entry 0 and [6, 5] at entry 1. This was done with the collate_fn() function. The images for my dataset are .png images of size 352x288, and the dataset labels are .txt files. I want to use the pretrained YOLO model on the COCO dataset, and finetune it to my data. 

My main goal, is to get a manual loop running, and pretty much do the same thing as the "normal" automatic training you have provided tutorials for. When that is working, I will need to go in and customize and modify loss functions, to eventually setup a teacher-student setup for knowledge distillation. I couldn't figure out how to paste the whole script without making it cluttered, I hope a .txt file is fine. 

[yolo_training.txt](https://github.com/ultralytics/ultralytics/files/14614293/yolo_training.txt)

**Comment by glenn-jocher** [comment]
@Suihko hello there! 👋 

I'm glad to see you're experimenting with manual training loops using YOLOv8. Let's address your concerns.

1. **Model Mode**:
   Setting the model to training or evaluation mode in your script should ideally utilize `model.train()` for training and `model.eval()` for evaluation. The behavior you're observing with `model.train()` initiating its default training sequence is unusual for manual loop setups. Instead of `model.train()`, directly use the YOLO model architecture for manual loops. Ensure you've initialized your model correctly, something like this:

   ```python
   from ultralytics import YOLO
   model = YOLO('yolov8n.pt', autoshape=False)  # Load model without autoshaping
   model.train()  # Set to training mode
   ```

2. **Runtime Error with Tensors**:
   The error you're encountering suggests that your target tensors might not be formatted as expected by the model. YOLO models expect targets as a list of tensors, each tensor representing `[class, x_center, y_center, width, height]` for each object, normalized by image width and height.
   
   Ensure your targets are properly formatted. If you’re manually creating these tensors, they should look something like this:

   ```python
   targets = [torch.tensor([[0, 0.5, 0.5, 0.1, 0.1]], device='cuda')] # Example target
   ```

   Also, keep in mind that the input images and targets must be sent to the same device (CPU or GPU) as the model.

3. **Custom Loss for Knowledge Distillation**:
   Once you have your manual loop running as intended, altering the loss function or incorporating a teacher-student setup for knowledge distillation should be feasible. Delve into the model’s forward function to understand how outputs and loss calculations are handled. You might need to adapt this part to suit your specific requirements for knowledge distillation.

Lastly, ensuring your data loading (images and targets), model setup, and loop structure are correctly aligned is crucial. Your plan of action is right; getting the loop to work like the automatic training first is a strong foundation before diving into modifications.

I hope this helps to clarify some of the issues! Do let us know how it goes or if you encounter any other hurdles. 😊

**Comment by hoominchu** [comment]
@glenn-jocher I am trying to train a YOLOv8 classification model on custom data with manual training loops. This is what I have right now:
```
model = YOLO('../yolov8/yolov8-cls-obstacle.yaml', verbose=False).load('yolov8x.pt')  # build a new model from YAML
model.train()
```
My questions are:
1. 'autoshape' is an unexpected argument. I am unable to pass that. Why is that? How does it affect the model training?
2. model.train() seems to start a training loop by itself instead of just setting the model to the training mode and eventually causes a runtime error.

What am I missing? Any help will be much appreciated. Thanks!

**Comment by glenn-jocher** [comment]
Hello @hoominchu! 👋

It looks like you're on the right track with setting up your manual training loop for the YOLOv8 classification model. Let's address your queries:

1. **Unexpected 'autoshape' Argument**: The `autoshape` argument is typically used with the `YOLO()` constructor to automatically handle varying image sizes during inference. However, for training, especially in manual loops, this isn't necessary. If you're following a guide or example that suggests using `autoshape` during training, it might be outdated or not applicable to your specific setup.

2. **model.train() Behavior**: The `model.train()` method in your script is indeed designed to start the training process rather than just switching the model to training mode. For manual training loops, you should prepare the model for training by ensuring it's in the correct mode without initiating the training process automatically. You can set your model to training mode simply by:
   ```python
   model.model.train()  # This sets the underlying PyTorch model to training mode
   ```
   This approach prevents the automatic start of the training loop and allows you to control the training process manually.

For your manual loop, ensure you manage the data loading, forward pass, loss calculation, and optimizer steps explicitly in your script. This setup gives you the flexibility to customize the training loop as needed for your application.

Let me know if this helps or if there's anything else you need! 😊

**Comment by hoominchu** [comment]
Hey @glenn-jocher thanks for the quick reply!

Yes, I had basically done the same--remove autoshape argument and set model.model.train().

However, even after completing 100 epochs of training, I am not seeing improvement in the accuracy or lower loss (it varies but accuracy stays within the 5.7% to 5.8% range.

Here is my training loop:

```
# Load a model
model = YOLO('../yolov8/yolov8-cls-obstacle.yaml', verbose=False).load('yolov8x.pt')  # build a new model from YAML
model.to(device)
model.model.train()

# Replace the loss function with BCELoss
criterion = nn.BCEWithLogitsLoss()


# Define your custom training loop
def train(model, criterion, data, epochs):
    epoch_losses = []
    epoch_accuracies = []

    best_accuracy = 0
    best_loss = 100

    optimizer = torch.optim.Adam(model.parameters(), lr=1e-6)

    for epoch in range(epochs):

        batch_losses = []
        batch_accuracies = []

        for images, gt_labels in data:  # Your data loader should yield images and multi-hot encoded gt_labels
            # Forward pass

            # Backward and optimize
            optimizer.zero_grad()

            outputs = model(images, verbose=False)
            output_tensors = get_tensors_from_results(outputs)
            gt_labels = gt_labels.float().to(device)
            loss = criterion(output_tensors, gt_labels)

            loss.backward()
            optimizer.step()

            batch_losses.append(loss.item())

            if c12n_category == C12N_CATEGORY['TAGS']:
                accuracy = calculate_accuracy_multilabel(output_tensors, gt_labels.to(device))
            # elif c12n_category == C12N_CATEGORY['SEVERITY']:
            #     accuracy = calculate_accuracy_multiclass(output, gt_labels.to(device))

            batch_accuracies.append(accuracy)

        epoch_losses.append(np.mean(batch_losses))
        epoch_accuracy = np.mean(batch_accuracies)
        epoch_loss = epoch_losses[-1]
        epoch_accuracies.append(epoch_accuracy)

        print("  -> Epoch {}: Loss = {:.5f}, Accuracy = {:.3f}%".format(epoch, epoch_losses[-1], 100 * epoch_accuracy))

        # save the model if it has the best accuracy so far
        # @zhihan, should we be checking for accuracy at all?
        # or should we just consider the model with the lowest loss as the best?
        if epoch_accuracy > best_accuracy:
            best_accuracy = epoch_accuracy
            best_loss = epoch_loss
            torch.save(model.state_dict(), '{}/'.format(local_directory) + model_name_to_save)
            print('Saving model based on accuracy. Loss: {:.5f} | Accuracy: {:.3f}%'.format(best_loss, 100 * best_accuracy))
        elif epoch_accuracy == best_accuracy:
            if epoch_loss < best_loss:
                best_loss = epoch_loss
                best_accuracy = epoch_accuracy
                torch.save(model.state_dict(), '{}/'.format(local_directory) + model_name_to_save)
                print('Saving model based on loss. Loss: {:.5f} | Accuracy: {:.3f}%'.format(best_loss, 100 * best_accuracy))


# Train the model
train(model, criterion, data=dataloaders['train'], epochs=100)
```

And here is my custom config to 
- Change the number of output classes.
- Change the last layer to a classifier layer.

```
# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8-cls image classification model. For Usage examples see https://docs.ultralytics.com/tasks/classify

# Parameters
nc: 17 # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n-cls.yaml' will call yolov8-cls.yaml with scale 'n'
  # [depth, width, max_channels]
#  n: [0.33, 0.25, 1024]
#  s: [0.33, 0.50, 1024]
#  m: [0.67, 0.75, 1024]
#  l: [1.00, 1.00, 1024]
  x: [1.00, 1.25, 1024]

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32
  - [-1, 3, C2f, [1024, True]]

# YOLOv8.0n head
head:
  - [-1, 1, Classify, [nc]] # Classify
```

Am I doing anything wrong? Would really appreciate any input/help.

For context, I am training a multi-label classifier with multi-hot encoded data being passed to the model.

**Comment by glenn-jocher** [comment]
Hello @hoominchu! Great to see your progress and detailed setup for training your YOLOv8 classification model. Let's dive into your concerns:

1. **Stagnant Accuracy and Loss**: If your accuracy and loss aren't improving, it might be due to several factors:
   - **Learning Rate**: It might be too low, causing slow or no noticeable improvement. Consider experimenting with different learning rates.
   - **Model Complexity**: Ensure the model complexity is appropriate for the task. Sometimes, the model might be too simple to capture the necessary patterns, or too complex, leading to overfitting on a limited dataset.
   - **Data Quality and Preprocessing**: Check if the data is correctly preprocessed and normalized. Normalizing the data often helps the model learn better. You might want to uncomment the normalization line in your data loader.

2. **Model Saving Logic**: Your current logic for saving the model based on accuracy and loss looks generally fine. However, in cases where accuracy doesn't improve, it's wise to consider other metrics like F1-score, especially for imbalanced datasets. Also, ensure that your validation set is representative of the real-world data the model will encounter.

3. **Data Loader and Transformations**: Your data transformations seem appropriate. However, activating the normalization line might help if the model was pretrained with normalization. This aligns the input distribution with what the model expects, based on its initial training.

4. **Custom Configurations**: Your custom configuration for changing the number of output classes and adapting the last layer to a classifier is correctly set up. Just ensure that the number of classes (`nc`) matches the actual count in your dataset.

If adjustments to the learning rate and data normalization don't resolve the issue, consider evaluating the dataset's adequacy and diversity. Sometimes, adding more data or augmenting the existing data can significantly improve model performance.

Keep pushing forward, and don't hesitate to reach out if you need more detailed assistance! 😊
