### ISSUE TITLE
Why number of raws in confusion matrix in not equal to 1 ?

### ISSUE THREAD

**Issue by abdalluhahmed** [ultralytics/ultralytics#898]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I mean why the sum of confusion matrix is not equal 100% ?

**Comment by pderrenger** [comment]
@abdalluhahmed hey there! 🌟 The confusion matrix values are not normalized by default, so the sum of the rows may not add up to 100%. This is because the values in the confusion matrix represent the actual counts of true positive, false positive, true negative, and false negative predictions, rather than percentages. However, you can easily normalize the confusion matrix to get percentages if needed, which can be helpful for interpreting the classification performance. You can check out the documentation for more details on how to normalize the confusion matrix. If you have any other questions, feel free to ask!
