### ISSUE TITLE
Implementing yolov8s.torchscript model in android (kotlin)

### ISSUE THREAD

**Issue by tryprncp** [ultralytics/ultralytics#9004]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hi, I'm a student and I'm doing this for my undergraduate thesis. I'm implementing yolov8 model in android gallery's search mechanism. the purpose of yolov8 model is to scan media files and return images that has a bounding box label that matches the search query. i can make it work with yolov5s.torchscript.ptl using org.pytorch:pytorch_android_lite:1.10.0 and org.pytorch:pytorch_android_torchvision_lite:1.10.0 but it wont work with yolov8s.torchscript. the yolov5s.torchscript.ptl has a function to load the model and the classes.txt, is the yolov8 model wont need that?

**Comment by glenn-jocher** [comment]
@tryprncp hello! Great to hear about your project; it sounds like an exciting application of yolov8 😊. Implementing YOLOv8 in an Android context is a bit different from YOLOv5, primarily due to the model structure changes. However, the process remains quite similar.

For YOLOv8, if you're using a `.torchscript` model, you'll still load the model the same way you did with YOLOv5. The key difference could be in how you handle the output since YOLOv8 might have a different output structure.

For loading the classes, YOLOv8 does indeed require a class list for interpreting the output correctly. This isn't automatically included with the `.torchscript` file, so you'll need to handle it separately, similar to what you did with YOLOv5.

Here's a rough sketch on how you might approach this in Kotlin:

```kotlin
val model = Module.load(assetFilePath(this, "model.torchscript.ptl"))
val classes = loadClasses("classes.txt") // Implement this based on your app's structure
```

For handling the outputs effectively, I recommend reviewing the YOLOv8 output structure and adjusting your parsing logic to match the expected format. This might involve looking at how the bounding boxes, object confidence scores, and class probabilities are returned by the model.

If you continue facing issues, ensure your YOLOv8 model is correctly converted to TorchScript and compatible with the PyTorch version you're using in Android. Sometimes, version mismatches can lead to unexpected behavior.

Keep experimenting, and don't hesitate to ask more questions if you run into specific hurdles! 🚀
