### ISSUE TITLE
evaluate and save checkpoints per iteration rather than epochs?

### ISSUE THREAD

**Issue by majnas** [ultralytics/ultralytics#903]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is it possible to evaluate and save checkpoints per iteration rather than epochs while training!?  :confused:  :smiling_face_with_tear: 

```bash
# evaluate model each 300 iterations
yolo task=detect mode=train model=yolov8x.pt data=foo.yaml eval_freq_per_iter=300
```

**Comment by pderrenger** [comment]
@majnas hey there! Currently, YOLOv8 saves checkpoints and evaluates the model based on a specified number of epochs rather than iterations. While it's not directly possible to save checkpoints per iteration, you can achieve a similar effect by setting a fraction of an epoch (e.g., 0.1 or 0.01) for the `epochs` parameter, effectively triggering more frequent checkpoints and evaluations. This approach provides a finer-grained control over the frequency of checkpoints and evaluations during training. If you have any more questions or need further assistance, feel free to ask! 😊

**Comment by majnas** [comment]
Actually I want to train a model on large dataset, so I want to monitor the result in fraction of epoch. for example for 10 epochs I want 50 evaluation.
How to change the following cmd for this purpose!
```
yolo detect train data=coco8.yaml model=yolov8n.yaml epochs=100 imgsz=640

```

**Comment by pderrenger** [comment]
@majnas to achieve more frequent evaluations during training, you can use the `save_period` parameter to save checkpoints at specified intervals. However, evaluating the model at a fraction of an epoch isn't directly supported. As a workaround, you can reduce the `epochs` parameter to a smaller value and run multiple training sessions, or modify the training script to include custom evaluation logic. If you encounter any issues, please ensure you are using the latest version of the Ultralytics package.

**Comment by majnas** [comment]
Thanks :bowing_man:

**Comment by pderrenger** [comment]
To achieve more frequent evaluations during training, you can use the `save_period` parameter to save checkpoints at specified intervals. However, evaluating the model at a fraction of an epoch isn't directly supported. As a workaround, you can reduce the `epochs` parameter to a smaller value and run multiple training sessions, or modify the training script to include custom evaluation logic. If you encounter any issues, please ensure you are using the latest version of the Ultralytics package.
