### ISSUE TITLE
Different reustls running Yolo v8 on GPU vs. CPU using OpenCV and Onnx

### ISSUE THREAD

**Issue by pfmephisto** [ultralytics/ultralytics#9056]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am trying to integrate Yolo v8 in to some c++ code using OpenCV and their DNN module.
Running inference on CPU works well but is relatively slow.
Switching the backed to use the GPU has the model run at GPU speed, but I noticed that all the center points of the  anchor boxes appear to be `x=0, y=0`.

Am I doing something wrong when exporting the model? Or is there anything else that I need to pay attention to?

### Additional

This is the code I used to generate the onnx file. 
```python
from ultralytics import YOLO

model = YOLO('yolov8x-seg.pt') 
model.export(format="onnx", simplify=True)
```
Snippet of C++ inference code
```cpp

// Initialize model
cv::dnn::Net model;
model = cv::dnn::readNetFromONNX("./path-to-the-onnx-file");
model.setPreferableBackend(cv::dnn::DNN_BACKEND_CUDA);
model.setPreferableTarget(cv::dnn::DNN_TARGET_CUDA);


// Prepare the input image
cv::Mat netInputImg, blob;
LetterBox(srcImg, netInputImg, params, cv::Size(_netWidth, _netHeight));
cv::dnn::blobFromImage(netInputImg, blob  ,1.0 / 255, cv::Size(_netWidth, _netHeight), cv::Scalar(0, 0, 0), true, false);

// Run inference
model.setInput(blob);
std::vector<cv::Mat> net_output_img;

std::vector<std::string> output_layer_names{ "output0","output1" };
model.forward(net_output_img, output_layer_names);

// Access results
cv::Mat output0 = cv::Mat(cv::Size(net_output_img[0].size[2], net_output_img[0].size[1]), CV_32F, (float*)net_output_img[0].data).t();

float* pdata = (float*)output0.data;

// pdata[0] & pdata[1] are 0 for all rows.
pdata[0]
pdata[1]

pdata += output0.cols
```

**Comment by glenn-jocher** [comment]
@pfmephisto hey there,

It sounds like you’re facing a common discrepancy issue when switching from CPU to GPU inference environments, especially with ONNX models. Your C++ snippet and export process look right, so this might be rooted in how ONNX models execute within OpenCV's DNN module on GPU.

Here are a couple of pointers you might want to consider:

1. **Check ONNX Opset Version:** Ensure that the ONNX opset version used during export is compatible with the version supported by OpenCV DNN. Sometimes mismatches here can lead to unexpected behavior. Although not directly set in your export script, consider specifying it if you haven't yet, e.g., `model.export(format="onnx", simplify=True, opset=12)`.

2. **GPU Results Tensor Layout:** GPU computations can result in different memory layout, which OpenCV might interpret incorrectly. Validate if reshaping or transposing the output tensor is necessary before accessing its data.

3. **OnnxRuntime Verification:** As an additional check, run your exported ONNX model using [OnnxRuntime](https://github.com/microsoft/onnxruntime) directly with GPU support enabled to see if the issue persists. This can help isolate whether the problem is with the ONNX model or the OpenCV DNN module.

4. **OpenCV and CUDA Version:** Make sure your OpenCV build comes with CUDA support and that it is up-to-date. Compatibility issues might also arise from mismatched versions.

If after these checks the problem still exists, it might be worth checking for any related issues in the OpenCV GitHub or forums, as this could be an OpenCV DNN module specific anomaly.

Hope this helps a bit! Keep me posted on your progress, happy to dive deeper if needed. 🚀

**Comment by abyssss52** [comment]
What version of OpenCV DNN did you use? We have tried version 4.8.0. We get a same result(all the center points of the anchor boxes appear to be x=0, y=0) with CUDA and get a correct result with CPU. Finally, We find a method to solve this problem. We add a output at the final mul layer which can get the bbox coordinate. Also you can try version 4.9.0 which has solved this problem.

**Comment by pfmephisto** [comment]
@abyssss52 Thanks for sharing, I'm on OpenCV 4.9.0, compiled against cuDNN 8.9.7 but still have the issue.
I haven't tried adding the extra output layer, but I do so if none of @glenn-jocher's steps helps to narrow it down.

**Comment by glenn-jocher** [comment]
@pfmephisto That's a great catch! 🌟 I appreciate you sharing your solution with the extra output at the final mul layer, and it's valuable to know that upgrading to OpenCV 4.9.0 might resolve this issue. For anyone encountering a similar problem, here's a brief example of how to add an extra output layer in Python:

```python
import cv2
net = cv2.dnn.readNet('model.onnx')
net.getUnconnectedOutLayersNames().append('final_mul_layer')  # Assuming 'final_mul_layer' is your additional output layer.
```

Remember, this is just a placeholder. You should replace `'final_mul_layer'` with the actual name of your layer. I hope one of these solutions helps you out! Keep us posted. 😊

**Comment by pfmephisto** [comment]
What fixed the issue for me was building OpenCV from the current 4.x branch, specifically `0c6fc76`.  
From some issues and merges on the OpenCV repo it looks like they implemented some fixes early this year that solve the issue. For reference  https://github.com/opencv/opencv/issues/24606

Also for completeness, I had a closer look at the wrong results and turns out it was not just the x,y values that were wrong but also the masks.

**Comment by glenn-jocher** [comment]
@pfmephisto hey there! 😊 So glad to hear that building OpenCV from the `0c6fc76` commit of the 4.x branch resolved your issues, and thanks for sharing the relevant OpenCV issue link. It's super helpful for anyone facing similar problems.

It's interesting that both the x,y values and masks were affected. This specific fix in OpenCV demonstrates the importance of keeping up with the latest patches and contributions to open-source projects. 

For anyone needing to build from a specific OpenCV commit:
```bash
git clone https://github.com/opencv/opencv.git
cd opencv
git checkout 0c6fc76
# Follow the usual build process for your platform
```
Keep those updates coming, and sharing these insights makes the community stronger! 🚀

**Comment by hujunyao** [comment]
from https://github.com/opencv/opencv/issues/23977 , opencv fixed the bugs on jan 11

**Comment by glenn-jocher** [comment]
@hujunyao hey there! Thanks for pointing out the fix! 🌟 For those who might be affected, updating to the latest version of OpenCV where this bug is resolved could indeed help. Here's a quick way to update OpenCV using pip:

```bash
pip install --upgrade opencv-python
```

Make sure to test your application after updating to ensure everything works as expected. Happy coding! 😊
