### ISSUE TITLE
Change Label font size and bounding box thickness in the predicted video

### ISSUE THREAD

**Issue by ishtiaq-nmsu** [ultralytics/ultralytics#9094]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can I change the label size in the predicted video. I saw some solution using opencv. Is there any parameter I can use to change the label font? I installed YOLOv8 using pip install. I understand that if I can use the git repo to install locally it might be possible to change font size in the source code like what I did in YOLOv5. But, I cannot use the YOLOv8 repo as well as probably some file is missing! like requirement.txt file is not there.

**Comment by glenn-jocher** [comment]
@ishtiaq-nmsu hello! 👋 Great question. You're right that there are a couple of ways to adjust the label font size and bounding box thickness directly in your predicted video.

If you're using the YOLOv8 CLI or Python code for predictions, you can easily specify the visualization details such as label font size or bounding box thickness using the `plot()` method from the `Results` object.

Here's a quick example on how to adjust these when running predictions:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('yolov8n.pt')

# Perform prediction
results = model('path/to/your/image_or_video.jpg')

# Use the plot method with adjusted parameters, e.g., line_thickness and font_size
annotated_img = results[0].plot(line_thickness=3, font_size=15)

# Show or save the result with adjusted visualization
annotated_img.show()
# or annotated_img.save('path/to/save.jpg')
```

For scenarios requiring more advanced customizations, altering the source code would indeed be a straightforward method. Since you mentioned some challenges with finding the `requirements.txt`, you might want to ensure you're working with the correct repository or branch. YOLOv8, being a part of the Ultralytics repository, should have all necessary files in place. Be sure to clone the repository correctly and locate the `requirements.txt` file within the main directory for local installations and modifications.

Remember that using the pip-installable version offers convenience, but modifying source code does provide greater flexibility for customization. Let me know if there's anything else I can help with! 😊
