### ISSUE TITLE
ultralytics PRO user not able to see my models in HUB iOS & android application after exporting also ?

### ISSUE THREAD

**Issue by vipin-prabhakaran** [ultralytics/ultralytics#9100]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am a pro user in ultralytics ,and I have a private project and some models ,to test and verify my model in deploy I have exported my model with both iOS & android .but when I am logging in my app its showing loading under my private project ,and nothing is loading to test 
![Screenshot 2024-03-19 at 4 18 10 PM](https://github.com/ultralytics/ultralytics/assets/161804976/f4b3c1d6-651e-4651-a797-d96f88332c29)

as I am the owner of the account I assume  there shouldn't be  any access rights issue ,can anyone pls help me on this as its critical issue for our business now

**Comment by glenn-jocher** [comment]
Hello! Thanks for reaching out and for using Ultralytics for your project 🚀. Since you're a PRO user and have already exported your models for both iOS and Android without seeing them appear in the HUB app, this might indeed seem puzzling.

A common cause for this issue could be related to the synchronization process between your account and the HUB. First, please ensure that:

1. The models have been successfully uploaded to the HUB without any errors during export.
2. You are logged in with the correct account credentials on the HUB app.

If both checks are okay, a quick workaround that often helps is to **log out and log back into the HUB app** to force a refresh of your projects and models.

```bash
# Example command to ensure successful export (replace with your specific details)
yolo export model=your_model.pt format=ios android
```

If these steps do not resolve the issue, it might require a deeper look into your account specifics. Since it's a critical issue for your business, I would recommend directly contacting our dedicated PRO user support at `support @vipin-prabhakaran.com` with a detailed explanation of the problem and any relevant console logs or screenshots from the exporting process.

We're here to help, and thank you for your patience! 🌟

**Comment by vipin-prabhakaran** [comment]
@glenn-jocher  thanks for your response . attached a screen shot for your reference .after export it shows no error and models are showing with their sizes .I also want to know if I am missing something on this or any steps needs to be corrected or not 
<img width="527" alt="Screenshot 2024-03-19 at 10 56 18 PM" src="https://github.com/ultralytics/ultralytics/assets/161804976/9f2039db-6583-4fac-b807-de7cff7928c6">

**Comment by glenn-jocher** [comment]
@vipin-prabhakaran hi there! 🌟 It looks like your model export process went smoothly, which is great news! From the screenshot, everything seems in order, with the model sizes correctly showing up. If you're not seeing your models in the HUB app, try a quick refresh by logging out and back in, as sometimes the app might need a nudge to sync up. 

If the issue persists, it could be helpful to double-check the app's version to ensure it's up-to-date. Also, verify that your account details in the app match those used during the export process. Sometimes it's these little details that sneakily get in the way! 

Feel free to reach back out if you're still running into hiccups. We're here to help smooth them out! 🚀

**Comment by vipin-prabhakaran** [comment]
everything seems to be fine ,on HUB portal ,but the models are not listing inside app to use it for testing even after doing multiple login/out and refresh ,as private projects are listing but the models inside that is still not listing and its keep on loading .I am going clueless on what we need to do it to make it working in the HUB application .

**Comment by glenn-jocher** [comment]
@vipin-prabhakaran hi there! 👋 I'm glad to hear your models are up on the HUB portal, but I understand the frustration with them not showing up in the app. Let's try clearing the app's cache/data (if on Android) or uninstalling and reinstalling the app as a more forceful refresh. Sometimes, deeper cached data can cause these kinds of syncing issues.

If the problem persists, it might be an issue on our end, and we'll need to take a closer look. Could you please send us some details like your user ID and the names of the models/projects not appearing? This information will help our team to investigate further. 

Thanks for your patience! We're here to get this sorted out for you. 🌟
