### ISSUE TITLE
The effect of the IoU threshold for NMS is opposite to that stated in the doc

### ISSUE THREAD

**Issue by plashchynski** [ultralytics/ultralytics#9150]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

Files
```
docs/en/modes/predict.md
docs/en/usage/cfg.md
```

have this text: 
```
Intersection Over Union (IoU) threshold for Non-Maximum Suppression (NMS). Higher values result in fewer detections by eliminating overlapping boxes, useful for reducing duplicates.
```

However, in the context of NMS, the effect is opposite. Lower values for the threshold result in fewer detections.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@plashchynski thanks for pointing this out! 😊 It seems there might have been a misinterpretation. Let me clarify:

The text in the documentation is intended as stated. During Non-Maximum Suppression (NMS), an IoU threshold is used to determine which boxes to keep. Boxes that overlap more than this threshold with a higher score box are suppressed. So, **higher** IoU threshold values indeed result in fewer detections because it allows boxes to have more overlap before one is suppressed. Conversely, a **lower** IoU threshold is stricter, allowing less overlap and therefore potentially more boxes (detections) to be retained since it suppresses boxes more aggressively.

The common practical effect (and potential confusion point) is that increasing the IoU threshold could lead to fewer distinct objects being detected due to the suppression of closely overlapping boxes.

If you believe the behavior you're observing deviates from this explanation, there might be a specific issue at play we can look into. Again, thanks for your willingness to contribute! Feel free to open a PR with any proposed clarifications that would make this more understandable. 🚀

**Comment by plashchynski** [comment]
Hello @glenn-jocher thank you for a swift response.

Yes, I believe the behavior I'm observing deviates from this explanation.
Lower _iou_ values result in significantly fewer detections in my case.

A number of detections is directly proportional to the _iou_ values:
for ```iou=1.0``` I got 31703 detections
for ```iou=0.9``` I got 27316 detections
for ```iou=0.7``` I got 19258 detections
for ```iou=0.5``` I got 18382 detections

And it indeed removes more duplicates with the lower threshold.

So, the less iou threshold the more boxes are suppressed that results in fewer detections.
While it seems, the documentation states the opposite: Higher values (presumably of iou?) result in fewer detections".

**Comment by glenn-jocher** [comment]
Hey @plashchynski! 👋

Interesting findings you've shared! It seems there might be some confusion around the behavior of the IoU threshold in NMS. Indeed, the typical expectation is that a lower IoU threshold would suppress more detections due to less tolerance for overlap between boxes. Your observations are in line with this.

However, seeing as your results indicate more detections are suppressed with a lower IoU threshold, leading to fewer total detections, it suggests the implementation is functioning as expected. The documentation might be confusing, and we appreciate you bringing this to our attention! 🙏

On a side note, if you're observing an unexpected increase in detections at higher IoU values, do ensure your validation conditions and dataset remain constant across tests. If inconsistencies persist, we're here to help investigate further.

Feel free to contribute to the doc clarification. Every bit helps us improve! 😊

```python
# Quick example adjustment for clarification purposes:
# Lower IoU threshold means stricter overlap criteria, potentially leading to more aggressive suppression of close detections. 
```

Thanks for engaging with us on this!
