### ISSUE TITLE
Ultralytics not working when compiling a PyQt6 file to .exe using PyInstaller

### ISSUE THREAD

**Issue by rafaelcoelho1409** [ultralytics/ultralytics#9163]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

I'm trying to use Ultralytics to deploy live camera algorithms to a .exe file, similar to one of my open sources projects (https://coelhovision.streamlit.app/). 

I tried several ways to run a live camera application using the YOLOv8 model, but when I use the model.predict method, it simply crashes the PyQt6 window for a reason I don't know why.

I tried to import for inside of .exe file Ultralytics, Shapely and Torch libraries, but it didn't solve my problem too. I also tried to use multiprocessing with PyQt6, but no success.

The code piece is as follows:

class ObjectDetectionYOLO:
    def __init__(self):
        self.model = YOLO(resource_path(os.path.join('models', 'yolov8n.pt')))
    def transform(self, original_image):
        results = self.model.predict(original_image)
        for r in results:    
            annotator = Annotator(original_image)
            boxes = r.boxes
            for box in boxes:
                b = box.xyxy[0]  # get box coordinates in (left, top, right, bottom) format
                c = box.cls
                annotator.box_label(b, self.model.model.names[int(c)], color = (255, 0, 0), txt_color = (255, 255, 255))      
        img = annotator.result()
        return img
        
This class I created originally for the web application works very fine, with no problems, but crashes with PyQt6
The command in PyInstaller I used:
py -m PyInstaller --onefile --icon=assets/coelho_vision_icon.ico --add-data "data;data" --add-data "assets;assets" --add-data "models;models" --collect-all ultralytics --collect-all shapely .\COELHO_VISION.py

When I tested the .py file, it crashes too, but it corrects fast and then works well after this.
For the moment, I decided to give up using Ultralytics and I will try other libraries to apply Image Segmentation and Object Detection with PyQt6.

Originally, I developed all my code in Ubuntu, but the majority of the people use Windows, so I installed a VM to develop the .exe file. In Ubuntu, the .py file works well with no problems.

Greetings from Brazil,
Rafael

### Environment

Ultralytics YOLOv8.1.29 🚀 Python-3.10.11 torch-2.2.1+cpu CPU (11th Gen Intel Core(TM) i7-1165G7 2.80GHz)
Setup complete ✅ (1 CPUs, 16.0 GB RAM, 63.5/79.1 GB disk)

Obs: It's a Windows 11 VM. My host system is Ubuntu.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@rafaelcoelho1409 hello Rafael from Brazil! 🇧🇷

It sounds like you're doing some fantastic work with live camera algorithms! Regarding the issue with the PyQt6 window crashing when using `model.predict`, it's a bit tricky without seeing the exact error message, but here are a couple of suggestions:

1. Ensure all libraries are correctly packaged within the .exe. Libraries like `Torch` and `Ultralytics` can sometimes have difficulties when being bundled. It looks like you've attempted this, but double-checking the paths and dependencies might help.
2. Since it works on Ubuntu but not on Windows, even in a VM, it could be a platform-specific issue. Testing the script on a native Windows machine might isolate the problem if the VM isn't handling some dependencies well.

As a sidenote, when deploying applications with heavy libraries like `Torch`, ensuring that all necessary CUDA/cuDNN libraries (for GPU) or their CPU counterparts are packaged or available on the host system is crucial. Given you're working on CPU, it should simplify matters, but it's still something to verify.

If it's an option, considering Docker containers might offer a more seamless deployment across different OSes, although it introduces its complexities.

Without more specific error details, these are broad strokes. If possible, capturing and sharing the error message or log when the application crashes could provide more insights. Your approach to packaging with PyInstaller seems solid, so I suspect it's more about environment and dependencies.

Keep up the great work, and I hope you find a fitting solution soon! Feel free to share any progress or additional details.

**Comment by gguzzy** [comment]
Hello dear all,
I am still facing the same issue. 

I create a basic pyqt (using qtpy and Pyqt6), while it works perfectly on both Ubuntu and Windows using a regular YoloV5 model, using YoloV8 works regularly on Ubuntu, whereas on Windows it fails, crashing the window right after detection is performed. Sometimes it works, but most of the times it gives me back this error

'Process finished with exit code -1073741819 (0xC0000005)' then the app crashes after performing 'get_sliced_prediction'.

I cannot figure it out why this behavior is happening, and I am pretty sure this is due to ultralytics package. 

Did anyone was able to solve this issue or mitigate it?

Thanks a lot.

**Comment by glenn-jocher** [comment]
@gguzzy hello, please ensure you're using the latest version of the Ultralytics package, as updates may resolve compatibility issues. If the problem persists, consider testing with a minimal example to isolate the issue.
