### ISSUE TITLE
Where can I find the yolov8m.yaml file. How to edit the architecture without the .yaml file

### ISSUE THREAD

**Issue by LakshmySanthosh** [ultralytics/ultralytics#9180]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Where can I find the `yolov8m.yaml` file? I am working on a project and I want to use yolov8m and modify some part of its architecture. I searched the repository, I found `yolo8.yaml`, but there it is written that it has the architecture of yolov8n. Please help me find with a way to use the yolov8m model and modify the model architecture.

**Comment by LakshmySanthosh** [comment]
@glenn-jocher , Thankyou for responding,
 
I wanted to know the model architecture of yolov8models. Is the architecture of all yolov8 models same as that of `yolov8n`?  If not, how can we know the modifications in architecture of  the `yolov8m` model. 

I tried training using this line of code, when I replaced the `model=yolov8m.yaml`  by `yolov8s.yaml` and `yolov8l.yaml`, I saw that the params, arguments, and n value was different.  
`!yolo task=detect mode=train model=yolov8m.yaml data={dataset.location}/data.yaml epochs=25 imgsz=416 plots=True` 
If that is the model architecture shown in that summary, if I create a yaml file by modifying the `yolov8n.yaml` file by the values in the summary of training of `yolov8m`, I will get the model architecture for yolov8m?

One more thing, if `yolov8m.yaml` file does not exist in the repository, how are we able to use it in model training as mentioned above?

**Comment by glenn-jocher** [comment]
Hi @LakshmySanthosh,

The architecture of YOLOv8 models like `yolov8m`, `yolov8s`, and `yolov8l` differ primarily in parameters like depth, width, and layer configurations, which are scaled to suit different computational and accuracy needs.

The differences you observed in parameters and arguments when switching models in your training command are due to these architectural variations. If you want to customize or replicate the architecture of `yolov8m` using `yolov8n.yaml` as a base, you would adjust the `depth_multiple` and `width_multiple` values according to the summary stats you see during training of `yolov8m`.

Regarding the use of `yolov8m.yaml` in training, if the file isn't explicitly in the repository, it might be dynamically generated or default settings are being used based on a template like `yolo8.yaml`. You can create your own YAML file based on the training summary modifications to closely match the `yolov8m` setup.

Hope this helps clarify things! Let me know if you have any more questions.
