### ISSUE TITLE
How to plot trajectories using the yolov8-obb model?

### ISSUE THREAD

**Issue by STITCHESHHH** [ultralytics/ultralytics#9194]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Firstly, thank you for your contribution, I used the script you proposed for plotting the trajectories there in the tracking documentation under the official website, 
![image](https://github.com/ultralytics/ultralytics/assets/147716690/c90aeb43-0251-4178-9e2f-47edb6b1af2f)

and then, I would like to make use of the yolov8n-obb model for trajectory plotting.
![image](https://github.com/ultralytics/ultralytics/assets/147716690/6a49c603-e416-4415-9604-cb97d23056c6)
Specific errors are reported as follows：
![image](https://github.com/ultralytics/ultralytics/assets/147716690/cea880a5-acb6-47f0-81f8-cb280b8c7adc)
Error at line 28 of the code
I'm looking forward to your answers! Thanks!

**Comment by Burhan-Q** [comment]
@STITCHESHHH it's likely there are no detections, which is why you're getting that error. 

```
Traceback (most recent call last):
   File "D:\yolov8\tail_plot.py", line 28, in <module>
       boxes = results[0].boxes.xywh.cpu()
       
AttributeError: 'NoneType' object has no attribute 'xywh'
```

the key here is `AttributeError: 'NoneType' object has no attribute 'xywh'`

I **highly** recommend that you take the time to learn more python as this is absolutely an error you should be able to diagnose yourself. You shouldn't expect to be able to build a modern house (especially not quickly) if all you have is a hammer.

**Comment by STITCHESHHH** [comment]
> @STITCHESHHH it's likely there are no `boxes`, which is why you're getting that error. If you're using an OBB model, detections are accessed via `.obb` instead.
> 
> ```
> Traceback (most recent call last):
>    File "D:\yolov8\tail_plot.py", line 28, in <module>
>        boxes = results[0].boxes.xywh.cpu()
>        
> AttributeError: 'NoneType' object has no attribute 'xywh'
> ```
> 
> the key here is `AttributeError: 'NoneType' object has no attribute 'xywh'`
> 
> I **highly** recommend that you take the time to learn more python as this is absolutely an error you should be able to diagnose yourself. You shouldn't expect to be able to build a modern house (especially not quickly) if all you have is a hammer. Additionally the [documentation](https://docs.ultralytics.com/modes/predict/#obb) has a great deal of information that will help as well.

thank you!

**Comment by glenn-jocher** [comment]
You're welcome, @STITCHESHHH! 🙌 Just a quick tip: When working with YOLOv8 OBB models, use `.obb` for accessing detection information. Here's a small example to guide you:

```python
results = model('your_image_or_video_path')
if results.obb:  # Checking if we have detections
    obb_boxes = results.obb.xyxy[0].cpu()  # Accessing the oriented bounding boxes
    # Now you can proceed with your plotting or any other operation with obb_boxes
```

Don't hesitate to dive into the [documentation](https://docs.ultralytics.com/modes/predict/#obb) for more insights. Keep experimenting and exploring—happy coding! 😊

**Comment by STITCHESHHH** [comment]
> You're welcome, @STITCHESHHH! 🙌 Just a quick tip: When working with YOLOv8 OBB models, use `.obb` for accessing detection information. Here's a small example to guide you:
> 
> ```python
> results = model('your_image_or_video_path')
> if results.obb:  # Checking if we have detections
>     obb_boxes = results.obb.xyxy[0].cpu()  # Accessing the oriented bounding boxes
>     # Now you can proceed with your plotting or any other operation with obb_boxes
> ```
> 
> Don't hesitate to dive into the [documentation](https://docs.ultralytics.com/modes/predict/#obb) for more insights. Keep experimenting and exploring—happy coding! 😊

Thank you very much, thanks for the tip, I'll try it later, thanks again for your help!

**Comment by glenn-jocher** [comment]
@STITCHESHHH you're most welcome! 😊 If you have any more questions or run into challenges, feel free to reach out. We're here to support your journey. Good luck with your experiments, and happy coding! 🚀

**Comment by Kev1nDeng** [comment]
> ```python
> obb_boxes = results.obb.xyxy[0].cpu()  # Accessing the oriented bounding boxes
> ```
Hi @glenn-jocher ! I've tried using .obb to access obb detections as I'm using the yolov8-obb model for tracking.However,this error still occured and while debugging,it seems that the results contained obb attribute?Do you have any clue on how to solve this problem as I'm trying to plot the trajectories using the obb model(I had no issue when tracking on videos without plotting traj).Thanks in advance!

![94ec1fbb024b90efa0ccde686a06a0a](https://github.com/ultralytics/ultralytics/assets/112330183/67779dc9-22a7-44cf-af81-8429748da0ad)
![820c0459e2014c3f9521a9fae783dbb](https://github.com/ultralytics/ultralytics/assets/112330183/3566675e-5945-485c-afaf-4cbbeb6a0170)

**Comment by glenn-jocher** [comment]
@Kev1nDeng hey there! 👋 It looks like you're doing everything correctly to access the OBB detections with `.obb.xyxy[0].cpu()`. If you're encountering an error specific to plotting trajectories, let's make sure your results do indeed contain OBB detections first. Here's a quick debug snippet you can use:

```python
if hasattr(results, 'obb') and results.obb is not None:
    obb_boxes = results.obb.xyxy[0].cpu()
    print("OBB detections:", obb_boxes)
else:
    print("No OBB detections found in the results.")
```

This will help verify if the `results` contain `obb` detections. If you continue to have issues or if `obb` detections are indeed present, there might be something more at play with how the trajectories are plotted. In that case, ensuring the plotting logic is compatible with OBB format would be a good next step.

Hope this helps! Let me know if you find anything or if there's more I can do to assist. Happy coding! 🚀

**Comment by Kev1nDeng** [comment]
> @Kev1nDeng hey there! 👋 It looks like you're doing everything correctly to access the OBB detections with `.obb.xyxy[0].cpu()`. If you're encountering an error specific to plotting trajectories, let's make sure your results do indeed contain OBB detections first. Here's a quick debug snippet you can use:
> 
> ```python
> if hasattr(results, 'obb') and results.obb is not None:
>     obb_boxes = results.obb.xyxy[0].cpu()
>     print("OBB detections:", obb_boxes)
> else:
>     print("No OBB detections found in the results.")
> ```
> 
> This will help verify if the `results` contain `obb` detections. If you continue to have issues or if `obb` detections are indeed present, there might be something more at play with how the trajectories are plotted. In that case, ensuring the plotting logic is compatible with OBB format would be a good next step.
> 
> Hope this helps! Let me know if you find anything or if there's more I can do to assist. Happy coding! 🚀

@glenn-jocher Thanks for your reply,really appreciate it! I've tried the debug snippet you offered and it turned out that there are no obb detections found in the results,which is weird because I've used the same yolov8-obb model to do tracking on videos and got very satisfying results(see the screenshots below,the vehicles are detected in oriented bounding boxes). Then when I'm trying to plot tracks over time (using the code from the offical doc [https://docs.ultralytics.com/modes/track/#plotting-tracks-over-time](url) ), this error occurs.How can I resolve this?
![image](https://github.com/ultralytics/ultralytics/assets/112330183/e8b7410a-e1bb-4f2f-b781-73f289252372)

**Comment by glenn-jocher** [comment]
@Kev1nDeng Glad to hear back from you! If you're seeing OBB detections in videos but not while trying to plot trajectories, it might be an issue related to the data flow to your plotting function. 🤔 Make sure you're consistently using the `.obb` attribute across all your steps. Since you've confirmed the model does produce OBB detections in video tracks, it could be a specific condition under which you're trying to plot that leads to this hiccup.

One quick thing to check: ensure the plotting code is executed in an environment where the model is loaded and inferencing properly, similar to your tracking setup. Sometimes, differences in execution context can lead to unexpected results.

If you're still stuck, could you share the snippet where you integrate the plotting code with your tracking results? It might help pinpoint where the integration needs tweaking.

Keep up the great work; you're very close to solving the puzzle! 🧩
