### ISSUE TITLE
Extracting appearance/embedding of objects detection for further tasks like appearance similarity between objects

### ISSUE THREAD

**Issue by IGlace** [ultralytics/ultralytics#9198]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

@Burhan-Q To explain to you in more details what i'm trying to do, is changing the final object "Results" returned by the predict function of the model.

Normally a segmentation model, return in the Results object many informations including a lists of bounding boxes detected, a list of class predicted for each bounding box, and a list of polygonne for segmentation of each bounding box.

Now i want to add another thing in this Results object we can name it appearance for example, which can give an embedding vector that represent the appearance of the bounding box of the object detected ( person in my case since my model only trained on persons ), or even better the embedding vector from the polygonne of the segmentation.

The embed attribute that already exist currently return the embedding of the image in general from specfic layers i can decide, but that's not what i want, i want to add one more step further on top of those embeddings to extract the embedding of each object detected seperatly.

I hope with this i explained what i'm trying to do clearly.

Now back to what i asked before, is this even possible ? or is it already a feature implemented that i don't know ? or it is under developement ?

**Comment by Burhan-Q** [comment]
@IGlace okay, I understand a bit more what you mean. I think that I can point you to what areas you might need to make modifications to the source code, but I don't have an understanding of what would need to be changed or added to accomplish this. Hopefully you have a good understanding of how to access and process the information you're looking for (seems like maybe it would be the mask `protos`) and my input hear can serve as a guide on where those changes would need to happen.

First I think you'll need to make a change as part of the prediction `postprocess` method https://github.com/ultralytics/ultralytics/blob/8617fcf32d36a798a24631c4d495a3fcfc456145/ultralytics/models/yolo/segment/predict.py#L28
Keep in mind that the `SegmentationPredictor` class inherits from the `DetectionPredictor` which is created from the `BasePredictor` class. This could mean that you might also need to modify the `BasePredictor` class in the block where inference is executed
https://github.com/ultralytics/ultralytics/blob/8617fcf32d36a798a24631c4d495a3fcfc456145/ultralytics/engine/predictor.py#L248-L251
and/or in the `inference` method itself
https://github.com/ultralytics/ultralytics/blob/8617fcf32d36a798a24631c4d495a3fcfc456145/ultralytics/engine/predictor.py#L135-L142
which would lead to the `nn.tasks.BaseModel` section we looked at on your previous issue.

I think the `inference` method is probably a starting point and then you can follow the steps out (reverse order of code in this comment) to ensure that you have your normal predictions + whatever else you're looking to capture. Then, you'll have to update the `Results` class to accept those new objects in the `init` method https://github.com/ultralytics/ultralytics/blob/8617fcf32d36a798a24631c4d495a3fcfc456145/ultralytics/engine/results.py#L97 since this is the final step of the `postprocess` method before returning data https://github.com/ultralytics/ultralytics/blob/8617fcf32d36a798a24631c4d495a3fcfc456145/ultralytics/models/yolo/segment/predict.py#L56

**Comment by IGlace** [comment]
Ok thank you i will do some tests from what you suggested and keep you updated in this issue 👍

**Comment by glenn-jocher** [comment]
@IGlace great to hear you're willing to test out those suggestions! 😊 If you encounter any challenges or have questions as you go along, don't hesitate to share here. We're looking forward to your updates and are here to help. Good luck with your tests!

**Comment by pratikgehlott** [comment]
@IGlace did you happen to extract object embedding using any method?

**Comment by horsto** [comment]
I'd also like to know!

**Comment by glenn-jocher** [comment]
@pratikgehlott @horsto yes—two practical options: quickest is to get per‑object vectors by cropping each detection (or masking) and calling `model.embed()` on those regions; for a built‑in path, the detector already supports per‑object features via `r.feats` when feature maps are provided (see “get_obj_feats” and how it’s attached in `postprocess`). Minimal example for the crop+embed route:

```python
from ultralytics import YOLO

model = YOLO("yolo11n-seg.pt")
results = model.predict("image.jpg")

for r in results:
    obj_embeds = []
    xyxy = r.boxes.xyxy.cpu().numpy().astype(int)
    for x1, y1, x2, y2 in xyxy:
        crop = r.orig_img[y1:y2, x1:x2]
        obj_embeds.append(model.embed(crop)[0])  # 1 tensor per object
    r.appearance = obj_embeds  # optional: attach to Results
```

Docs for reference: embedding API in [Model.embed](https://docs.ultralytics.com/reference/engine/model/), isolating mask regions in [Isolating Segmentation Objects](https://docs.ultralytics.com/guides/isolating-segmentation-objects/), detector hooks in [DetectionPredictor.postprocess](https://docs.ultralytics.com/reference/models/yolo/detect/predict/#postprocess) and [get_obj_feats](https://docs.ultralytics.com/reference/models/yolo/detect/predict/#get_obj_feats), and how seg passes protos upstream in [SegmentationPredictor.postprocess](https://docs.ultralytics.com/reference/models/yolo/segment/predict/#postprocess). Since this issue is closed/stale, please open a new Discussion for follow‑ups so the team can track it.
