### ISSUE TITLE
Add custom callbacks to training with CLI 

### ISSUE THREAD

**Issue by camhpj** [ultralytics/ultralytics#9199]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is there a way to add custom callbacks to a training run with the CLI?

**Comment by camhpj** [comment]
Some more context to my question.

I have been training using a custom config that looks like the one below. I am starting training using the cli command `yolo cfg=/path/to/config.yaml`. 

```
task: detect
mode: train

# Train settings -------------------------------------------------------------------------------------------------------
model: ./yolov8s.pt
data: ./data-v1.yaml
epochs: 150
patience: 10
batch: 16
imgsz: 640
save: True
save_period: -1
cache: True
device: 0
workers: 20
project: /runs
name: baseline
exist_ok: False
pretrained: True
optimizer: Adam
verbose: True
seed: 0
deterministic: True
single_cls: True
close_mosaic: 50
amp: True
dropout: 0.0
fraction: 1
freeze: 10

# Hyperparameters ------------------------------------------------------------------------------------------------------
lr0: 0.001  # (float) initial learning rate (i.e. SGD=1E-2, Adam=1E-3)
lrf: 0.01  # (float) final learning rate (lr0 * lrf)
momentum: 0.937  # (float) SGD momentum/Adam beta1
weight_decay: 0.0005  # (float) optimizer weight decay 5e-4
warmup_epochs: 3.0  # (float) warmup epochs (fractions ok)
warmup_momentum: 0.8  # (float) warmup initial momentum
warmup_bias_lr: 0.1  # (float) warmup initial bias lr
box: 7.5  # (float) box loss gain
cls: 0.5  # (float) cls loss gain (scale with pixels)
dfl: 1.5  # (float) dfl loss gain
pose: 12.0  # (float) pose loss gain
kobj: 1.0  # (float) keypoint obj loss gain
label_smoothing: 0.0  # (float) label smoothing (fraction)
nbs: 64  # (int) nominal batch size
hsv_h: 0.015  # (float) image HSV-Hue augmentation (fraction)
hsv_s: 0.7  # (float) image HSV-Saturation augmentation (fraction)
hsv_v: 0.4  # (float) image HSV-Value augmentation (fraction)
degrees: 0.0  # (float) image rotation (+/- deg)
translate: 0.1  # (float) image translation (+/- fraction)
scale: 0.5  # (float) image scale (+/- gain)
shear: 0.0  # (float) image shear (+/- deg)
perspective: 0.0  # (float) image perspective (+/- fraction), range 0-0.001
flipud: 0.0  # (float) image flip up-down (probability)
fliplr: 0.5  # (float) image flip left-right (probability)
mosaic: 1.0  # (float) image mosaic (probability)
mixup: 0.0  # (float) image mixup (probability)
```
I am happy to use python instead of the CLI to initialize training but am a little confused as to what the direct analog to the CLI command is using Python. For example if I do this
```
from ultralytics import YOLO

model = YOLO('yolov8s.pt`)

model.train(cfg='./config.yaml`)
```
my provided argument for `data` in the config is ignored and it defaults to using COCO. Is there nothing possible like the hypothetical example below?

```
from ultralytics import Trainer

trainer = Trainer()
trainer.train(cfg='./config.yaml)
```

**Comment by glenn-jocher** [comment]
@camhpj hi there! Thanks for reaching out with your question. 🙌

The Ultralytics YOLO framework primarily supports customization and extensibility through its Python API, which provides greater flexibility, including the use of custom callbacks.

While the CLI is a convenient way to run training jobs with predefined settings, it doesn't directly support defining custom callbacks due to its current design focusing on simplicity and standardized operations. 

For your use case where you have a detailed configuration and the desire to include custom logic through callbacks, switching to the Python interface is indeed the way to go. The snippet you shared is almost there; you just need a little adjustment to fully utilize your custom config file along with the Ultralytics YOLO Python API.

Here's how you can initiate training that respects your custom config and data paths, along with a hypothetical way of adding callbacks, assuming future versions of Ultralytics YOLO might support it or through defining your own extended training logic:

```python
from ultralytics import YOLO

# Initialize the model with your .pt file and custom config file
model = YOLO(model='yolov8s.pt', cfg='./config.yaml')

# Lightly modify your YAML to directly specify all paths and parameters (as it's done here)
# The model will now respect 'data' specified in your config during initialization

# Then you can start the training process. Remember to adjust below according to actual API support or customization
model.train()
```

To integrate custom callbacks into the training lifecycle, you would typically extend or modify the training loop, which may involve a deeper dive into the framework's source code. Currently, this sort of customization would require adapting the training script itself, rather than through a high-level API. 

Though there isn't a direct analog to the CLI `yolo cfg=/path/to/config.yaml` for executing all configurations through Python with a single line, loading configurations through the `cfg` parameter when initializing your model object (as shown above) is a recommended approach. Always ensure your custom config YAML closely aligns with the expected format and includes necessary directives for your training regimen.

For the most current and detailed examples, it's always great to refer to the [Ultralytics YOLO documentation](https://docs.ultralytics.com/) and the GitHub repository for updates and new features.

I hope this clarifies your query! Don't hesitate to reach out again if you have more questions. Happy training! 🚀

**Comment by camhpj** [comment]
Thanks!

**Comment by glenn-jocher** [comment]
@camhpj hello! Thanks for reaching out! 🌟

To include custom callbacks using the CLI isn't directly supported as the CLI favours simplicity and standard workflows. However, diving into Python gives you the flexibility you need.

For applying configuration directly in Python akin to `yolo cfg=/path/to/config.yaml`, you can initialize the `YOLO` object with your custom `.pt` model and configuration like so:

```python
from ultralytics import YOLO

# Load model and config together
model = YOLO(model='path/to/your/yolov8s.pt', cfg='path/to/config.yaml')
```

This ensures that your training respects the settings defined in your custom YAML file, including your `data` path.

Regarding training with this setup, if you specify your data path directly in the `cfg`, `model.train()` should respect it, bypassing the default COCO dataset.

If you're looking to implement custom callbacks, you'll need to modify or extend the training loop directly. This kind of customization will require diving a bit into the codebase since it's beyond the current high-level API's scope.

Hope this helps! Let us know if you have further questions. Happy coding! 😊
