### ISSUE TITLE
Correct usage of ultralytics.nn module

### ISSUE THREAD

**Issue by pronoym99** [ultralytics/ultralytics#920]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I would like to perform YoLov4 based prediction using a custom `.pt` file. What is the proper procedure as per the documentation given in [ultralytics.nn reference](https://docs.ultralytics.com/reference/nn/)?

### Additional

Since, I have access to a pre - trained YoLov4 model and not the dataset on which it was trained on, I have converted my `.wt` weights file to an equiavlent `.pt` file using this [repo](https://github.com/Tianxiaomo/pytorch-YOLOv4).

**Comment by glenn-jocher** [comment]
@pronoym99 the simplest way to get started is directly with YOLOv8 prediction, i.e.:

```
yolo predict model=yolov8n.pt
```

**Comment by pronoym99** [comment]
I am facing the issue mentioned [here](https://github.com/ultralytics/ultralytics/issues/275#issuecomment-1384445490). I believe it is because of the non - compatibility of YoLov4 with the ultralytics repo.

**Comment by pderrenger** [comment]
@pronoym99 the compatibility issue you're experiencing can be resolved by ensuring the correct model and weights files are being used. When performing YOLOv8 predictions using a custom `.pt` file, please ensure that the model is trained using YOLOv8. The YOLOv8 model is specifically designed for use with the Ultralytics repo and ensures compatibility. If you continue to encounter compatibility issues, please let us know so that we can assist further.

**Comment by pronoym99** [comment]
@pderrenger try to understand that these `.pt` files are compiled using YoLov4 and not via the tools available in this repo.
