### ISSUE TITLE
Parsing Yolov8 OBB TFLite Output

### ISSUE THREAD

**Issue by tzofi** [ultralytics/ultralytics#9212]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi! Thank you for your work on this repo! I am trying to adapt the [TFLite detection inference example](https://github.com/ultralytics/ultralytics/blob/main/examples/YOLOv8-OpenCV-int8-tflite-Python/main.py) to work with oriented bounding boxes. I have trained an OBB model and converted it to TFLite. I am able to run inference with it and get an array of shape [1, 8, 21504] at this line:

```
output = interpreter.get_tensor(output_details[0]["index"])
```

This output is passed to the postprocess() function, which isn't set up to post process OBBs. Are there any existing examples of how to post process the OBB output? I wasn't able to find any for TFLite, Onnx, etc. Any help or suggestions are appreciated! Thanks!

**Comment by glenn-jocher** [comment]
@tzofi hello! Thanks for reaching out, and it's great to hear about your project using YOLOv8 for oriented bounding boxes (OBB) in a TFLite model. 😊

For parsing OBB outputs in the format you mentioned (`[1, 8, 21504]`), the primary challenge is to correctly interpret these values as coordinates for the oriented bounding boxes (assuming the format being [x1, y1, x2, y2, x3, y3, x4, y4] for each box).

Here's a basic example of how you might approach this. Note that actual post-processing could be more complex depending on your model's output specifics:

```python
import numpy as np

# Assuming 'output' is your model's raw output with shape [1, 8, 21504]

# Reshape output to separate each OBB
obb_outputs = output.reshape(-1, 8) # Resulting in shape [21504, 8]

# Example to process first OBB
obb = obb_outputs[0]
print(f"OBB Coordinates: {obb}")

# Example to convert to your desired format, e.g., center, width, height, angle
def convert_obb_to_format(obb):
    # Dummy example function, replace with actual conversion logic
    return obb[0], obb[3], obb[4], 45  # Placeholder values

# Iterate and convert each OBB
converted_obbs = [convert_obb_to_format(obb) for obb in obb_outputs]

# Now 'converted_obbs' holds your post-processed OBBs in the new format
```

This example assumes each OBB is represented as eight consecutive floats denoting the corners of the box. It's crucial to adjust `convert_obb_to_format()` as per your specific needs, perhaps utilizing geometric calculations to derive orientation, etc., from the corner points.

Currently, we don't provide direct examples for OBB postprocessing specific to TFLite, but I hope this example offers a starting point. Keep an eye on our GitHub repo for future updates or examples addressing such tasks directly!

Happy coding! 🚀

**Comment by tzofi** [comment]
Hi @glenn-jocher! Thank you for the quick response. We are simply using the default OBB model and training it on a dataset with a single class. If the 8 dimensions of the output from the OBB model were indeed the box corners, how do we obtain the confidence score needed to run NMS?

If it's helpful for comparison, if we convert the provided yolov8n-obb.pt checkpoint (which, from my understanding was trained on the DOTA dataset, with 18 classes) to TFLite, the output is 20-dimensional, `(1, 20, 21504)`, rather than 8-dimensional, `1, 8, 21504` when we have 1 class. Does this help you interpret the output of our model?

**Comment by glenn-jocher** [comment]
Hi @tzofi! Delighted to see your follow-up. 😊 Given the shape of the output you're observing, it sounds like the model is outputting additional information alongside the OBB corners.

For an OBB model, alongside the 8 dimensions for each box corner ([x1, y1, x2, y2, x3, y3, x4, y4]), there should indeed be additional dimensions to represent the confidence scores and possibly class probabilities. The output shape `(1, 20, 21504)` for the `yolov8n-obb.pt` model trained on DOTA suggests it includes the 8 coordinates for the OBB corners, 1 confidence score, and 11 class probabilities (since DOTA has 18 classes but YOLO models typically include a 'no-object' class probability as well).

When you train on a single class and see an output of `(1, 8, 21504)`, it seems like only the corner points are being returned. However, since your model is for a single class, I'd expect at least 10 dimensions ([8 corners] + [confidence] + [class probability]).

To include confidence scores in the output, it’s essential to ensure the model’s final layers are designed to output these scores alongside the corner coordinates. The model's architecture in the .pt file should reflect this. The training process should inherently train the model to output these scores.

For post-processing, including NMS, you would typically:

1. Extract the confidence scores and class probabilities.
2. Filter the detections based on a confidence threshold.
3. Apply NMS to the filtered detections based on their scores and the overlap between bounding boxes.

Here's a very basic structure of how you might start to extract and use these scores assuming they were included in your 8-dimensional output:

```python
# Placeholder for your model's output
output = np.random.rand(1, 10, 21504)  # Assuming the shape should be (1, 10, 21504) for illustration

# Reshape to [N, 10] where N is the number of detections
detections = output.reshape(-1, 10)

# Extract box corners, confidence scores, and class probabilities
box_corners = detections[:, 0:8]
confidence_scores = detections[:, 8]
class_probabilities = detections[:, 9]

# Apply a confidence threshold and NMS here
```

Ensure that your model's architecture is defined to output these additional dimensions correctly and that they're being correctly interpreted post-inference. It's also a good idea to double-check the exported TFLite model and ensure the conversion process preserves this output structure.

I hope that sheds some light on your situation! Keep pushing forward with your project! 🚀

**Comment by isakosh** [comment]
Hi,
Did you find a solution?
My model tarined on one class outputs a tensor with the size of (1,6,2600) which is not enough for the corners alone.

**Comment by glenn-jocher** [comment]
Hi there! 😊 It looks like your model is outputting fewer dimensions than expected for an OBB (oriented bounding boxes) setup. For OBBs, you'd typically need 8 values for the corners, plus additional values for confidence scores and class probabilities.

Given your output shape of `(1,6,2600)`, it seems like certain dimensions are indeed missing. Typically, for a single-class setup, you'd expect something like `(1, 10, N)`, with 8 for the corners, 1 for confidence, and 1 for the class probability.

It's essential to check the final layer of your model to ensure it's configured correctly to output all the necessary dimensions. For an OBB model, consider reviewing the model architecture you used and make sure it aligns with the requirements for an OBB output. 🚀

**Comment by tzofi** [comment]
@isakosh - I found that the OBB output format is in `xywhr`, not eight corners, as stated above. In my case, the eight dimensional output I got corresponded to `[x y width height c1 c2 c3 rotation]`. In your case, I suspect the six dimensional output corresponds to `[x y width height c1 rotation]`, where c1 is the class confidence. For more information on parsing this output, I referred to [this function](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/ops.py#L162-L302), which is called [here](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/models/yolo/obb/predict.py#L32-L41) for OBB.

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions as you go along or need further assistance, feel free to ask. Happy coding! 😊
