### ISSUE TITLE
AttributeError: bn delattr(m, 'bn')  # remove batchnorm  

### ISSUE THREAD

**Issue by aminrabinia** [ultralytics/ultralytics#926]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I ran into a problem with fusing when setup_model AutoBackend(fuse=True). I try to detect segmentation on cpu. The model works fine in Colab but I randomly get this error when deployed on docker desktop or gcp cloud run. 

```
segmentation-segyolo8-1  | Traceback (most recent call last):
segmentation-segyolo8-1  |   File "/usr/local/lib/python3.8/dist-packages/gradio/routes.py", line 374, in run_predict
segmentation-segyolo8-1  |     output = await app.get_blocks().process_api(
segmentation-segyolo8-1  |   File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 1017, in process_api
segmentation-segyolo8-1  |     result = await self.call_function(
segmentation-segyolo8-1  |   File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 835, in call_function
segmentation-segyolo8-1  |     prediction = await anyio.to_thread.run_sync(
segmentation-segyolo8-1  |   File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
segmentation-segyolo8-1  |     return await get_asynclib().run_sync_in_worker_thread(
segmentation-segyolo8-1  |   File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
segmentation-segyolo8-1  |     return await future
segmentation-segyolo8-1  |   File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in runsegmentation-segyolo8-1  |     result = context.run(func, *args)
segmentation-segyolo8-1  |   File "/usr/src/ultralytics/./main.py", line 30, in gradio_infer
segmentation-segyolo8-1  |     results = model.predict(myimg, device='cpu', conf=conf, save=True)
segmentation-segyolo8-1  |   File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/model.py", line 143, in predict
segmentation-segyolo8-1  |     self.predictor.setup_model(model=self.model)
segmentation-segyolo8-1  |   File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/predictor.py", line 210, in setup_model
segmentation-segyolo8-1  |     self.model = AutoBackend(model, device=device, dnn=self.args.dnn, data=self.args.data, fp16=self.args.half)
segmentation-segyolo8-1  |   File "/usr/local/lib/python3.8/dist-packages/ultralytics/nn/autobackend.py", line 76, in __init__
segmentation-segyolo8-1  |     model = model.fuse() if fuse else model
segmentation-segyolo8-1  |   File "/usr/local/lib/python3.8/dist-packages/ultralytics/nn/tasks.py", line 101, in fuse
segmentation-segyolo8-1  |     delattr(m, 'bn')  # remove batchnorm
segmentation-segyolo8-1  |   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1328, in __delattr__
segmentation-segyolo8-1  |     super().__delattr__(name)
segmentation-segyolo8-1  | AttributeError: bn
segmentation-segyolo8-1  | YOLOv8n-seg summary (fused): 195 layers, 3258259 parameters, 0 gradients, 12.0 GFLOPs
segmentation-segyolo8-1  |
segmentation-segyolo8-1  | Ultralytics YOLOv8.0.33 🚀 Python-3.8.10 torch-1.13.1+cpu CPU
```

### Environment

Ultralytics YOLOv8.0.33 🚀 Python-3.8.10 torch-1.13.1+cpu CPU

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@aminrabinia 👋 hi, thanks for letting us know about this possible problem with YOLO. We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub [master](https://github.com/ultralytics/yolov5/tree/master), and if necessary `git pull` or `git clone` a new copy to ensure your problem has not already been solved in [master](https://github.com/ultralytics/yolov5/tree/master).
- ✅ **Unmodified** – Your problem must be reproducible using official YOLO code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/yolov5/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by aminrabinia** [comment]
Thanks! (I did not see your guidelines when I submitted the bug.)

Problem resolved once I used async function to make the inference. 

```
async def gradio_infer(myimg, conf=0.50):
    if myimg is None:
        return
    results = model.predict(myimg, device='cpu', conf=conf, save=True) 
    print(results)
    if len(results[0].numpy())==0:
        return myimg
    else:
        return model.predictor.annotator.result()

io = gr.Interface(fn=gradio_infer, 
	inputs=[gr.Image(), 
			gr.Slider(0.20, 0.80, step=0.10, value=0.50, label="Set the confidence level:")],
	outputs=gr.Image(),
	examples=[["testimg.jpg", 0.30], ["testimg2.jpg", 0.60]],
	allow_flagging = 'never',
	css="footer {visibility: hidden}",
	live=True
	)
gr.mount_gradio_app(app, io, path="/gradio")

if __name__ == "__main__":
	uvicorn.run(app, host='0.0.0.0', port=8080)
```

**Comment by pderrenger** [comment]
@aminrabinia glad to hear that the problem was resolved! The use of an async function for inference seems to have made a difference. Your code for the async function looks good, and it's great to see how you integrated it with Gradio for interactive inference. 

Thank you for sharing the update, and feel free to reach out if you have any more questions or need further assistance! 😊
