### ISSUE TITLE
The `model.predict` call fails when `sys.argv` is empty

### ISSUE THREAD

**Issue by TurbineJoshua** [ultralytics/ultralytics#9272]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

We are calling YoloV8 in a separate thread, that itself kicks off a separate process. Without having spent too much time trying to understand why, when printing `sys.argv` right before calling the model as a predictor it shows `[]`. Because the list is empty, [this line](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/engine/model.py#L424) in `model#predict` fails because

### Environment

Ultralytics YOLOv8.0.222 🚀 Python-3.10.12 torch-2.2.1+cu121 CUDA:0 (NVIDIA GeForce RTX 2080 Ti, 11009MiB)
Setup complete ✅ (32 CPUs, 62.6 GB RAM, 555.6/914.3 GB disk)

OS                  Linux-6.5.0-1016-oem-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             pip
RAM                 62.63 GB
CPU                 AMD Ryzen Threadripper 1950X 16-Core Processor
CUDA                12.1

matplotlib          ✅ 3.8.3>=3.3.0
numpy               ✅ 1.26.4>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.12.0>=1.4.1
torch               ✅ 2.2.1>=1.8.0
torchvision         ✅ 0.17.1>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
pandas              ✅ 2.2.1>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

### Minimal Reproducible Example

```
import sys
from ultralytics import YOLO

model = YOLO('yolov8s.pt')
sys.argv = []
predictions = model(<some image>)
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@TurbineJoshua thank you for bringing this to our attention, and it's fantastic that you're willing to help with a PR! 👍

If `sys.argv` is empty and causing issues with `model.predict`, an immediate workaround is to ensure that `sys.argv` has at least one item, usually the script's filename. Here's how you can modify your minimal reproducible example:

```python
import sys
from ultralytics import YOLO

# Ensure sys.argv has at least one item
if not sys.argv:
    sys.argv.append('script_name.py')

model = YOLO('yolov8s.pt')
predictions = model(<some image>)
```

This workaround will prevent `model.predict` from failing due to an empty `sys.argv`. Meanwhile, we can explore a more robust solution to handle such cases within the YOLOv8 source code. Looking forward to your PR, and please let us know if there's any way we can support you further! 🚀
