### ISSUE TITLE
running inference on a high-resolution image  using a YOLOv8 int8 TFLite Edge TPU model with Sahi

### ISSUE THREAD

**Issue by AlaaArboun** [ultralytics/ultralytics#9275]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I want to run YOLOv8 INT8 TFLite on a PCIe Accelerator Coral, but the image size is 4200*2160. Is it possible to run YOLOv8 INT8 with such dimensions on the edge TPU, and would that affect the FPS and inference time? Also, can you confirm if Sahi is supported on TFLite Edge TPU?.
Thank you in advance for your assistance!

**Comment by glenn-jocher** [comment]
@AlaaArboun hello! Running YOLOv8 INT8 TFLite on a high-resolution image like 4200x2160 on a Coral Edge TPU is possible, but there are a couple of things to consider:

1. **Image Size:** Large image dimensions can significantly impact FPS and inference time due to the increased computational load. To enhance performance, consider resizing your images before inference or using tiling methods to process the image in parts.

2. **Sahi Support:** While Sahi provides a robust tool for slicing large images and running inference on each slice, integration with TFLite models on Edge TPU requires custom implementation. Sahi primarily supports PyTorch and ONNX models out of the box. You might need to adapt Sahi's workflow for TFLite Edge TPU compatibility, focusing on handling TFLite inference specifically.

For running inference on Coral, you'd generally do something akin to:

```python
from tflite_runtime.interpreter import load_delegate
from tflite_runtime.interpreter import Interpreter

interpreter = Interpreter(model_path="your_model_int8.tflite",
                          experimental_delegates=[load_delegate('libedgetpu.so.1.0')])
interpreter.allocate_tensors()

# Image preprocessing and inference code here
```

Consider diving into Coral's documentation or Sahi's if you plan to adjust Sahi for TFLite models. Good luck with your project! 😊

**Comment by AlaaArboun** [comment]
Hi @glenn-jocher ,

I'm reaching out to discuss two approaches for handling large images and running inference on them:

1. Sahi for Efficient Image Handling:

I'd like to explore using Sahi, an alternative to TFLite, for processing large images. Sahi might be a viable option for handling these images efficiently.There is another approach similar to Sahi for handling large images and running inference on them using TFLite models with the Edge TPU. 

2. Batch Processing for TPU Optimization:

My current setup processes image frames one at a time. I'm interested in learning how to implement batch processing to leverage the parallel processing capabilities of the Edge TPU. This could significantly improve performance.

Model Input Details:

Here are the details of my model's :
```bash
input details : 
 [{'name': 'serving_default_images:0', 'index': 0, 'shape': array([  1, 256, 256,   3]), 'shape_signature': array([  1, 256, 256,   3]), 'dtype': <class 'numpy.int8'>, 'quantization': (0.003921568859368563, -128), 'quantization_parameters': {'scales': array([  0.0039216], dtype=float32), 'zero_points': array([-128]), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]

output details : 
output details [{'name': 'PartitionedCall:0', 'index': 44, 'shape': array([   1,   84, 1344]), 'shape_signature': array([   1,   84, 1344]), 'dtype': <class 'numpy.int8'>, 'quantization': (0.006676046643406153, -110), 'quantization_parameters': {'scales': array([   0.006676], dtype=float32), 'zero_points': array([-110]), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
```
Key Question:

Based on these details, can the model process multiple images simultaneously (batch processing)?

I appreciate any insights or suggestions you might have on these approaches.

Thanks,

**Comment by glenn-jocher** [comment]
@AlaaArboun hi there! 🙌

For running inference on large images with your current setup, both Sahi and batch processing stand out as great approaches! 

1. **Using Sahi:** Sahi is indeed a fantastic tool for handling large images, especially due to its slicing and model agnosticism. If you're looking to adapt it for TFLite and Edge TPU, you might need some custom tweaks since Sahi mainly operates with PyTorch models out-of-the-box. While integrating Sahi for TFLite and Edge TPU, focus on ensuring compatibility at the inference step.

2. **Batch Processing:** For your model with an input shape of `[1, 256, 256, 3]`, enabling batch processing will require modifying the model to accept a batch dimension greater than 1. This involves model retraining or adjustment. Edge TPUs typically accelerate inference per model per instance, so leveraging parallel processing might involve separate instantiations for concurrent processing rather than traditional batch processing.

To directly answer your question: The current model as described appears to be set up for processing single images (batch size of 1). Modifying it for batch processing depends on the capability of the model architecture and the training framework. It's possible but may require some adjustments and possibly retraining the model to accept a larger batch size in the input shape (e.g., `[N, 256, 256, 3]` where N > 1).

Feel free to reach out if you've got more questions or need further assistance. Happy coding! 😊
