### ISSUE TITLE
Only have one class in one image (like mnist)

### ISSUE THREAD

**Issue by AlexKuoTW** [ultralytics/ultralytics#9286]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi Sir,

Thanks for the great work, my question is now my datasets just have one class in each images (like mnist 1,2,3,4,5.....)
when in inference how could I save the difference output in different folder?
ie,. now the model have inference one image (1.png) and have detect it is class[0]->Elephant, then I want to save 1.png to /my/project/Elephant/

Thanks

**Comment by Burhan-Q** [comment]
@AlexKuoTW you may want to use the `classify` task instead of the standard `detect` (object detection) task, but either will work fine. As for saving (or maybe copying) the image to a new directory based on the inference results, you'll need to write custom code to accomplish this. You can do this easily with `psutil` or `pathlib.Path` packages, or any other package for moving files around.
