### ISSUE TITLE
Missing frames on Jetson Orin Nano

### ISSUE THREAD

**Issue by samiukas** [ultralytics/ultralytics#9297]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm running YOLOv8n-pose tracking with Oak-D camera on NVIDIA Orin Nano 8GB RAM targeting CUDA for GPU. I want to run at least 15 frames per second but currently only achieving a mean FPS of 12 (with a variation of +/-2). More importantly, I am missing a frame every other second (on average) and also seeing 'model.track' fed with duplicated frames every now and then. Is this something you have seen before or could suggest any fixes?

[Oak_Record_Plain_YOLO.zip](https://github.com/ultralytics/ultralytics/files/14744393/Oak_Record_Plain_YOLO.zip)

**Comment by glenn-jocher** [comment]
@samiukas hi there! 🌟 It sounds like you're facing a challenge with frame rate and missing frames on your Orin Nano setup. A few things to consider for improving the situation:

1. **Optimize Model**: If you haven't already, try exporting your YOLOv8n-pose model to TensorRT format for better performance on NVIDIA platforms. This could significantly boost your inference speed. You can do this with:
   ```bash
   yolo export model=yolov8n-pose.pt format=engine
   ```
   
2. **Adjust Batch Size**: If your application allows for slight latency, increasing the batch size for inference could improve overall throughput.

3. **Camera & Buffer Processing**: Ensure your Oak-D camera's data stream is consistently fast enough and consider implementing a buffer management strategy to handle frame drops more gracefully.

Since you mentioned duplicated frames, it could be related to how frames are fetched and queued for processing. Double-check the camera capture and frame queue logic to ensure new frames are consistently captured and old frames are not reprocessed.

If the issue persists or you need further assistance, feel free to share more details, especially around how you manage frame captures and inferences. Happy to help you get up to those desired FPS! 🚀
