### ISSUE TITLE
error: externally-managed-environment on Raspberry Pi 4B

### ISSUE THREAD

**Issue by DavidFord1** [ultralytics/ultralytics#9302]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Install

### Bug

Hello,
 I am trying to install ultralytics yolo8 to run a  script in my Raspberry Pi 4B
 by command:    pip3 install ultralytics

this error appear?
Both in Ubuntu and Debian operating systems:

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by DavidFord1** [comment]
@glenn-jocher

**Comment by glenn-jocher** [comment]
@DavidFord1 hello! It seems like you're encountering an issue with installing the Ultralytics YOLO package on your Raspberry Pi due to the system being an externally managed environment. This can occur when the Python environment is managed by the system's package manager rather than `pip`. 

A quick workaround for this is to use the `--user` flag with `pip` to install the package for the current user, avoiding the need for system-wide changes which are restricted on some systems. Try running:

```bash
pip3 install ultralytics --user
```

👉 If you're still facing any issues or have further questions, don't hesitate to reach out. Happy coding! 🚀
