### ISSUE TITLE
Train own model on AWS EC2 gave me RuntimeError: GET was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by sangyo1** [ultralytics/ultralytics#9305]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I am trying to training my own model with yolov8 on AWS since I do not have GPU.
I selected the EC2 model:
Deep Learning Proprietary Nvidia Driver AMI GPU PyTorch 2.1.0 (Ubuntu 20.04)
g4dn.xlarge

From the EC2, I install ```pip install ultralytics```
And run ```yolo task=detect mode=train model=yolov8n.pt data=/home/ubuntu/ssl/dataset.yaml epochs=300```
I kept getting "RuntimeError: GET was unable to find an engine to execute this computation".
![image](https://github.com/ultralytics/ultralytics/assets/57959053/eab8f90e-993b-47ac-9367-5f19eda44189)
Does anyone know how to fix it? or how do I run the Yolov8 on EC2 server

### Environment

![image](https://github.com/ultralytics/ultralytics/assets/57959053/5db55652-03e1-4c64-994c-df7cf190c44c)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@sangyo1 hello! 👋 Thank you for reaching out and providing a detailed account of the issue. It seems like you've encountered an error related to the execution engine while trying to train YOLOv8 on an AWS EC2 instance. This problem might be related to the PyTorch version and/or your CUDA setup. Here are a few steps you might consider to troubleshoot and hopefully resolve this issue:

1. **Verify PyTorch and CUDA Compatibility**: Ensure that the installed version of PyTorch is compatible with the CUDA version available on your EC2 instance. You can check the compatibility [here](https://pytorch.org/get-started/previous-versions/).

2. **Reinstall PyTorch with the Correct CUDA Version**: If a mismatch is found, consider reinstalling PyTorch with the appropriate version that matches your CUDA version. You can install PyTorch with a specific CUDA version using the following command:

```bash
pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113
```

(Note: Replace `cu113` with the version that matches your CUDA.)

3. **Ensure `ultralytics` Package Is Up to Date**: Although you've installed `ultralytics`, double-check that you're using the latest version as improvements and bug fixes are made regularly. Upgrade using:

```bash
pip install ultralytics --upgrade
```

4. **Test PyTorch and CUDA**: Before running YOLOv8, verify that PyTorch can correctly identify and use the GPU with the following Python code snippet:

```python
import torch
print(torch.cuda.is_available())
```

This should return `True` if your setup is correct.

If after trying these steps, the issue persists, it could be helpful to provide more details about the error log (if any) beyond the RuntimeError message you've shared. This additional information could offer more insights into the root cause of the issue.

Lastly, do not hesitate to reach out again if you face further challenges. We're here to help! 😊

**Comment by biphasic** [comment]
The very first line in your first screenshot says that the cuDNN lib couldn't be loaded, even though it is present on the system in my case. I think it's a misconfig of pytorch / CUDA install.

I had the same issue, so I changed to the Ultralytics Docker container and now it works!

**Comment by glenn-jocher** [comment]
@biphasic hey there! 😊 Thanks for sharing your experience and solution. Spot on, it seems like the cuDNN library issue is indeed tied to a PyTorch/CUDA configuration mismatch. Switching to the Ultralytics Docker container is a great workaround because it comes pre-configured with compatible versions, ensuring seamless operation.

For anyone facing a similar issue and preferring to work directly on their environment, re-installing PyTorch with the correct CUDA version often helps:

```bash
pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113
```
(Just swap in your CUDA version!)

Cheers for the insight, and I'm glad you've found a solution that worked for you! 🚀

**Comment by sangyo1** [comment]
@glenn-jocher Thank you for replying.
However, I install `pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113`
but I still get this error and it seems related to cuDNN. 
```
Traceback (most recent call last):
  File "/home/ubuntu/ssl/yolov5/train.py", line 848, in <module>
    main(opt)
  File "/home/ubuntu/ssl/yolov5/train.py", line 623, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/ubuntu/ssl/yolov5/train.py", line 390, in train
    scaler.scale(loss).backward()
  File "/opt/conda/lib/python3.10/site-packages/torch/_tensor.py", line 522, in backward
    torch.autograd.backward(
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/__init__.py", line 266, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: GET was unable to find an engine to execute this computation
```

**Comment by sangyo1** [comment]
Furthermore, 
```
ubuntu@ip-172-31-3-178:~/ssl/yolov5$ echo $LD_LIBRARY_PATH
/usr/local/cuda/lib64:/opt/amazon/efa/lib:/opt/amazon/openmpi/lib:/opt/aws-ofi-nccl/lib:/usr/local/cuda/lib:/usr/local/cuda:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/targets/x86_64-linux/lib:/usr/local/lib:/usr/lib
```
is my outcome

**Comment by glenn-jocher** [comment]
Hey! Thanks for sharing your solution. It's great to hear that updating the `LD_LIBRARY_PATH` in `~/.bashrc` resolved the issue for you. For clarity, here's a quick way to apply it:

```bash
echo 'export LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/lib' >> ~/.bashrc
source ~/.bashrc
```

This ensures that the system knows where to look for the CUDA libraries. Cheers for the tip! 🚀
