### ISSUE TITLE
YOLOv8 CUDA - GPU Utilization is not working correctly

### ISSUE THREAD

**Issue by MichaelSchrank** [ultralytics/ultralytics#9318]
### Search before asking

- [ ] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Install

### Bug

Hello there,
I am attempting real time image detection using YOLO but my inference time is much higher than target due to the model running solely on CPU. I am confused as to what the compatibility issue is because all of the build versions were specifically picked for ensuring compatibility.

The issue is pretty much the same as described on here but none of the fixes provided in the thread were of any help to me.
https://github.com/ultralytics/ultralytics/issues/3084

The original thread references setting up the gpu as a device before initializing the model but torch.cuda.set_device(0) does not yield promising results (see below)

### Environment

`torch.cuda.set_device(0)`

> python3 camera.py
> Traceback (most recent call last):
>   File "camera.py", line 10, in <module>
>     torch.cuda.set_device(0)
>   File "/home/dikuerec/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 350, in set_device
>     torch._C._cuda_setDevice(device)
> AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

```
import torch
import torchvision
from ultralytics import YOLO

print(torch.__version__)
```

> python3 test.py
> 2.0.1

```
import torch
import torchvision
from ultralytics import YOLO
```

print(torchvision.__version__)

> python3 test.py
> 0.15.2

```
import torch
import torchvision
from ultralytics import YOLO

result = torch.cuda.is_available()
print(result)
```

> python3 test.py
> False

> nvcc --version
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2022 NVIDIA Corporation
> Built on Sun_Oct_23_22:16:07_PDT_2022
> Cuda compilation tools, release 11.4, V11.4.315
> Build cuda_11.4.r11.4/compiler.31964100_0

I am using Jetson Orin NX J40 16GB flash with Jetpack 5.1.2.
Alongside Cuda11.4, Torchvision 0.15.2, and Pytorch2.0.1

the model is initialized like this 

```
import cv2
import pandas as pd
from ultralytics import YOLO
from tracker import*
import json
import torch as torch
import torchvision

tracker = Tracker() # tracks objects and assigns IDs to them

model = YOLO('yolov8best.pt')
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by PiyushKamboj1503** [comment]
@MichaelSchrank kindly go through the following git: https://github.com/marcoslucianops/DeepStream-Yolo

**Comment by glenn-jocher** [comment]
@MichaelSchrank hi there! 👋

Thanks for sharing your preference for a venv environment. If you've previously had a setup that worked well for you without using a container, let's try to get that environment up and running again. Could you please provide a few more details about the setup that worked for you? Specifically, it would be helpful to know the versions of CUDA, PyTorch, and torchvision that were part of your successful setup. 

Sometimes ensuring compatibility among these versions can help resolve CUDA and GPU utilization issues. For maintaining a smooth setup within a virtual environment, you might want to ensure that your CUDA toolkit is correctly recognized by PyTorch with something like:

```python
import torch
print(torch.version.cuda)
```

This command will help verify if PyTorch is recognizing CUDA. If there's a mismatch or if CUDA isn't recognized, it might be due to the installation process or environment path settings.

Let's work through this together. A step-by-step approach to align your environment settings closely with the previously successful setup might just do the trick! 🚀

**Comment by MichaelSchrank** [comment]
Apologies for the late reply. I have since found a solution to the problem.
Building torchvision from source using a specific version worked for me. I used a git clone for the corresponding build.

**Comment by glenn-jocher** [comment]
Hi there! 😊 No worries about the late reply. I'm really glad to hear you've found a solution that works for you! Building `torchvision` from source can indeed resolve compatibility issues and improve GPU utilization with YOLOv8. Great job troubleshooting and finding a workaround. 👍 If you have any more questions or face other challenges down the road, feel free to ask. Happy coding!

**Comment by mariam-162** [comment]
> Apologies for the late reply. I have since found a solution to the problem. Building torchvision from source using a specific version worked for me. I used a git clone for the corresponding build.

Hi,

Can you please share the versions of pytorch and cuda that worked for your YOLOv8 training? I'm using NVDIA 3090 with Cuda 12.1 (nvidia-smi)

I followed these steps:
1. Created a venv with python 3.8
2. conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
3. pip install ultralytics

I'm trying to custom train a YOLOv8 model but always end up with errors related to cuda blocking or torch_use_cuda_dsa.
GPU is available after torch.cuda.is_available()
However, torch.__version__ gives "2.2.2". No cuda version is shown here.
My environment has all the wrong versions I suppose. Please help me.

Thanks.

**Comment by glenn-jocher** [comment]
Hi there! 👋

No worries at all about the timing. It sounds like you've got a solid setup but just need a bit of tuning to get everything working smoothly with your NVIDIA 3090 and CUDA 12.1. Here's a quick suggestion based on your description:

Since you've already set up your environment and are facing CUDA-related errors, the versions might indeed be the key. For your setup, ensuring compatibility between PyTorch, torchvision, and CUDA is crucial. Here's a concise recommendation:

1. PyTorch compatibility with CUDA 12.1 might require checking the [PyTorch official website](https://pytorch.org/) for the latest compatible versions. As of my last knowledge update, PyTorch 2.2.2 should generally support CUDA 12.1, but direct installations sometimes miss setting the CUDA version correctly.

2. Building `torchvision` from source has helped others in similar situations. It might be worth trying this for your environment as well. Here's a quick start on how to clone and build:
   ```bash
   git clone --branch <desired_version> https://github.com/pytorch/vision.git
   cd vision
   python setup.py install
   ```
   Replace `<desired_version>` with the version tag that matches your PyTorch installation.

3. Lastly, remember to verify the CUDA version detected by PyTorch with:
   ```python
   import torch
   print(torch.version.cuda)
   ```

Please ensure you've activated your venv or conda environment before running these commands! 😊

If issues persist, sharing the exact error messages can help pinpoint the solution more directly. Best of luck, and feel free to reach out for more help!

**Comment by mariam-162** [comment]
Hi, thanks for the response. I updated everything on my system (drivers and environment).

The system specs are: Windows 11, NVIDIA 3090 (driver version 551.86), CUDA version 12.4, 64GB RAM

Environment setup:

pip install torch==2.0.0+cu118 torchvision==0.15.1+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
pip install ultralytics

I checked the environment and got these:
torch.version.cuda = 11.8
torch.backends.cudnn.version() = 8700
torch.__version__ = 2.0.0+cu118

I ran YOLOv8 for object detection using custom dataset for 50 epochs. After 2 epochs I ended up with BSOD with error: Memory Management.

I checked the dataset and config.yaml files for labeling consistency.

Can you please suggest what might be the issue?

**Comment by glenn-jocher** [comment]
Hey there! 😊

Sounds like you've hit a couple of bumps along the way, but no worries, we'll figure this out together! Your setup and approach look solid, but let's address these issues step by step.

Firstly, indeed, you need to install `torch` before `torchvision`. Your approach to installing both in a new environment is correct. It looks like the installation commands you used are appropriate for CUDA 11.8 with PyTorch 2.0.0 and torchvision 0.15.1. This should generally set up a compatible environment on your system specs.

Now, onto the more perplexing part, the Blue Screen of Death (BSOD) during training. While it's less common for Python scripts to cause BSOD directly, it might indicate a deeper issue, possibly related to drivers or system-level stability under GPU load. A few quick thoughts:

- **GPU Drivers:** Sometimes, driver conflicts or issues can cause system-level crashes. Double-check that your NVIDIA drivers are up-to-date and consider using NVIDIA's studio drivers if you're doing deep learning, as they are often more stable.
- **CUDA Compatibility:** Ensure CUDA Toolkit is correctly installed and matches the CUDA version required by PyTorch.
- **System Stability:** Although your RAM and GPU temps seem okay, it might be worth monitoring your system with a tool like HWiNFO to check for any spikes or issues under load.

As this involves a BSOD, if the issue persists even with the correct setup, it might also help to check system logs or use Windows' built-in tool for checking system file integrity:

```shell
sfc /scannow
```

Lastly, consider reducing the batch size or using `cache=True` in your training command to see if that alleviates the strain on your system.

Sorry to hear about the frustration, but hang in there! Let's take it one step at a time. 🌟

**Comment by cfrancois7** [comment]
It seems to have a problem with the install through CONDA.
I installed the ultralytics package in a virgin virtual env with the recommended CONDA command : 
`conda install -c pytorch -c nvidia -c conda-forge pytorch torchvision pytorch-cuda=11.8 ultralytics`
but conda install a CPU version for Pytorch.

```
conda list | grep torch
libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
pytorch                   2.2.0           cpu_py311h53e38e9_0
pytorch-cuda              11.8                 h7e8668a_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
torchvision               0.17.0              py311_cu118    pytorch
```

Then I tested by installing a CUDA compatible first then install ultralytics and again it wanted to downgrade/remove the cuda version for the CPU version.

**Comment by glenn-jocher** [comment]
Hi there! 👋

It looks like there might be a conflict or priority issue with the package versions being resolved by Conda. Here are a couple of steps you can try to ensure that the correct GPU-enabled versions of the packages are installed:

1. **Create a fresh environment** and explicitly specify the GPU version of PyTorch before installing the `ultralytics` package. This sometimes helps in setting the right precedence for dependency resolution.

2. **Use the following command** to install the necessary packages while ensuring the GPU versions are prioritized:
   ```bash
   conda create -n myenv python=3.8
   conda activate myenv
   conda install pytorch torchvision torchaudio cudatoolkit=11.8 -c pytorch -c nvidia
   pip install ultralytics
   ```

This approach ensures that the CUDA toolkit and the GPU versions of PyTorch and torchvision are installed before `ultralytics` is added to the environment, which might help prevent Conda from defaulting to CPU versions.

Let me know if this resolves the issue or if there's anything else you need help with! 😊

**Comment by cfrancois7** [comment]
@glenn-jocher I confirm that the second approach was the good one for me.
- prepare the environnement with conda and use pip to install ultralytics.

```
conda create -n myenv python=3.11
conda activate myenv
conda install pytorch torchvision torchaudio cudatoolkit=11.8 -c pytorch -c nvidia
pip install ultralytics
```

**Comment by mariam-162** [comment]
>    conda create -n myenv python=3.8
>    conda activate myenv
>    conda install pytorch torchvision torchaudio cudatoolkit=11.8 -c pytorch -c nvidia
>    pip install ultralytics
>    ```

Thanks for your help. I've been following this and other threads but keep ending at BSOD or some other error.

I have started training again using the same environment you mentioned. 
Ultralytics YOLOv8.2.28 🚀 Python-3.8.19 torch-2.3.1 CUDA:0 (NVIDIA GeForce RTX 3090, 24576MiB)
CODE:
```
from ultralytics import YOLO
import torch

if __name__ == "__main__":
    model = YOLO('yolov8n.pt')
        result = model.train(data='config.yaml', epochs=20, imgsz=640)

```

This is the error which you might be able to help me dubug: 
Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/20      2.36G      1.604      1.934      1.506          1        640: 100%|██████████| 1074/1074 [02:38<
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 156/156 [00:26<00:00,  5.94it/s]
                   all       4984       6291        0.6      0.606      0.631      0.332

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/20      2.36G      1.541      1.225      1.431         26        640:  72%|███████▏  | 773/1074 [01:43<00:40,  7.45it/s]
Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\myenv\lib\site-packages\torch\utils\data\dataloader.py", line 1133, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "C:\Users\USER\anaconda3\envs\myenv\lib\queue.py", line 178, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "fire_train.py", line 30, in <module>
    result = model.train(data='config.yaml', epochs=20, imgsz=640)
  File "C:\Users\USER\anaconda3\envs\myenv\lib\site-packages\ultralytics\engine\model.py", line 674, in train
    self.trainer.train()
  File "C:\Users\USER\anaconda3\envs\myenv\lib\site-packages\ultralytics\engine\trainer.py", line 199, in train
    self._do_train(world_size)
  File "C:\Users\USER\anaconda3\envs\myenv\lib\site-packages\ultralytics\engine\trainer.py", line 353, in _do_train
    for i, batch in pbar:
  File "C:\Users\USER\anaconda3\envs\myenv\lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "C:\Users\USER\anaconda3\envs\myenv\lib\site-packages\ultralytics\data\build.py", line 48, in __iter__
    yield next(self.iterator)
  File "C:\Users\USER\anaconda3\envs\myenv\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
  File "C:\Users\USER\anaconda3\envs\myenv\lib\site-packages\torch\utils\data\dataloader.py", line 1329, in _next_data
    idx, data = self._get_data()
  File "C:\Users\USER\anaconda3\envs\myenv\lib\site-packages\torch\utils\data\dataloader.py", line 1285, in _get_data
    success, data = self._try_get_data()
  File "C:\Users\USER\anaconda3\envs\myenv\lib\site-packages\torch\utils\data\dataloader.py", line 1146, in _try_get_data
    raise RuntimeError(f'DataLoader worker (pid(s) {pids_str}) exited unexpectedly') from e
RuntimeError: DataLoader worker (pid(s) 15448) exited unexpectedly

**Comment by cfrancois7** [comment]
Originally I replied and shared here my problem because it was package problem.
It seems your problem is not just package related.

PFN_LIST_CORRUPT is link to the driver.
https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x4e--pfn-list-corrupt

Maybe you should check and clean your graphical card driver.
What is very strange it is the crash in the middle of the training.
I do not think it is ultralytics related.

Have you another ML project, such as one with a LLM model to train?
Maybe try the pytorch forum. It will be more relevant.

**Comment by glenn-jocher** [comment]
@cfrancois7 hi there,

Thank you for sharing your insights. It does seem like the issue might be more related to system or driver stability rather than the Ultralytics package itself. The PFN_LIST_CORRUPT error indeed suggests there could be problems with the memory management, which is often related to drivers or hardware issues.

Cleaning or updating the graphics card drivers is a great suggestion. Additionally, checking for any hardware issues with the RAM or GPU could also be beneficial.

For further assistance, exploring forums like the PyTorch community might indeed provide more targeted advice, especially if the problem persists across different machine learning projects.

Thanks again for your input, and best of luck resolving this issue!
