### ISSUE TITLE
When using yolov8 for tracking in a multi-threaded environment，i meet the error RuntimeError: CUDA error: operation not permitted when stream is capturing

### ISSUE THREAD

**Issue by thesky0605** [ultralytics/ultralytics#9324]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

the erros occurs randomly，here is the error information：
(yolov8) lxy@gandi-System-Product-Name:~/ultralytics/lxy/results/yolo_track_frames$ /home/lxy/anaconda3/envs/yolov8/bin/python /home/lxy/ultralytics/lxy/yolo_thread_infer.py
WARNING ⚠️ Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify','pose' or 'obb'.
WARNING ⚠️ Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify','pose' or 'obb'.
main thread end
Loading /home/lxy/ultralytics/lxy/onnx_model/yolov8n.onnx for ONNX Runtime inference...
Loading /home/lxy/ultralytics/lxy/onnx_model/yolov8n.onnx for ONNX Runtime inference...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/lxy/anaconda3/envs/yolov8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/lxy/ultralytics/lxy/video_tracker2.py", line 287, in run
    self.run_tracker_in_thread(self.filename, self.model, self.file_index)
  File "/home/lxy/ultralytics/lxy/video_tracker2.py", line 316, in run_tracker_in_thread
    results = model.track(frame,
  File "/home/lxy/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/model.py", line 478, in track
    return self.predict(source=source, stream=stream, **kwargs)
  File "/home/lxy/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/model.py", line 439, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/lxy/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/predictor.py", line 206, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/home/lxy/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 44, in generator_context
    response = gen.send(None)
  File "/home/lxy/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/predictor.py", line 281, in stream_inference
    im = self.preprocess(im0s)
  File "/home/lxy/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/utils/ops.py", line 52, in __exit__
    self.dt = self.time() - self.start  # delta-time
  File "/home/lxy/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/utils/ops.py", line 62, in time
    torch.cuda.synchronize(self.device)
  File "/home/lxy/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/cuda/__init__.py", line 402, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: operation not permitted when stream is capturing
2 end

here is my code：
yolo_thread_infer.py
```
from tabnanny import verbose
import threading
import cv2
from ultralytics import YOLO
from video_tracker2 import Tracker

# Load the models
model1 = '/home/lxy/ultralytics/lxy/onnx_model/yolov8n.onnx'
model2 = '/home/lxy/ultralytics/lxy/onnx_model/yolov8n.onnx'

# Define the video files for the trackers
video_file1 = "/home/lxy/ultralytics/lxy/data/2.mp4"  # Path to video file, 0 for webcam
video_file2 = "/home/lxy/ultralytics/lxy/data/3.mp4"  # Path to video file, 0 for webcam, 1 for external camera

# Create the tracker threads
for i in range(2):
    if i == 0:
        tracker_thread1 = Tracker(video_file1, model1, 1)
        tracker_thread1.start()
    if i == 1:
        tracker_thread2 = Tracker(video_file2, model1, 2)
        tracker_thread2.start()
# Start the tracker threads

# Wait for the tracker threads to finish
# tracker_thread1.join()
# tracker_thread2.join()

# Clean up and close windows
# cv2.destroyAllWindows()
print('main thread end')
```

video_tracker2.py
```
class Tracker(threading.Thread):

    def __init__(self, filename, model_path, file_index) -> None:
        super().__init__()
        self.filename = filename
        self.model = YOLO(model_path)
        self.file_index = file_index

    def run(self):
        self.run_tracker_in_thread(self.filename, self.model, self.file_index)

    def run_tracker_in_thread(self, filename, model, file_index):
        """
        Runs a video file or webcam stream concurrently with the YOLOv8 model using threading.

        This function captures video frames from a given file or camera source and utilizes the YOLOv8 model for object
        tracking. The function runs in its own thread for concurrent processing.

        Args:
            filename (str): The path to the video file or the identifier for the webcam/external camera source.
            model (obj): The YOLOv8 model object.
            file_index (int): An index to uniquely identify the file being processed, used for display purposes.

        Note:
            Press 'q' to quit the video display window.
        """
        video = cv2.VideoCapture(filename)  # Read the video file
        frame_count = 0
        while True:
            ret, frame = video.read()  # Read the video frames

            # Exit the loop if no more frames in either video
            if not ret:
                break
            frame_count += 1
            if frame_count > 300:
                break
            # Track objects in frames if available
            results = model.track(frame,
                                  persist=True,
                                  conf=0.3,
                                  iou=0.5,
                                  classes=[0, 2],
                                  verbose=False,
                                  tracker='/home/lxy/ultralytics/ultralytics/cfg/trackers/custom_tracker.yaml')
            res_plotted = results[0].plot()
            # cv2.imwrite(
            #     '/home/lxy/ultralytics/lxy/results/yolo_track_frames/' + str(frame_count) + '-' + str(file_index) +
            #     '.jpg', res_plotted)

            key = cv2.waitKey(1)
            if key == ord('q'):
                break

        # Release video sources
        video.release()
        print(str(self.file_index) + ' end')
```

and the guide in official docs makes me confused:
```
# Unsafe: Sharing a single model instance across threads
from ultralytics import YOLO
from threading import Thread

# Instantiate the model outside the thread
shared_model = YOLO("yolov8n.pt")


def predict(image_path):
    results = shared_model.predict(image_path)
    # Process results


# Starting threads that share the same model instance
Thread(target=predict, args=("image1.jpg",)).start()
Thread(target=predict, args=("image2.jpg",)).start()


# Unsafe: Sharing multiple model instances across threads can still lead to issues
from ultralytics import YOLO
from threading import Thread

# Instantiate multiple models outside the thread
shared_model_1 = YOLO("yolov8n_1.pt")
shared_model_2 = YOLO("yolov8n_2.pt")


def predict(model, image_path):
    results = model.predict(image_path)
    # Process results


# Starting threads with individual model instances
Thread(target=predict, args=(shared_model_1, "image1.jpg")).start()
Thread(target=predict, args=(shared_model_2, "image2.jpg")).start()



# Safe: Instantiating a single model inside each thread
from ultralytics import YOLO
from threading import Thread


def thread_safe_predict(image_path):
    # Instantiate a new model inside the thread
    local_model = YOLO("yolov8n.pt")
    results = local_model.predict(image_path)
    # Process results


# Starting threads that each have their own model instance
Thread(target=thread_safe_predict, args=("image1.jpg",)).start()
Thread(target=thread_safe_predict, args=("image2.jpg",)).start()

```
Looking forward to replying to my questions, thank you very much!

**Comment by glenn-jocher** [comment]
@thesky0605 hello! It seems like you're encountering CUDA errors due to concurrent model access in a multi-threaded environment. This type of error often occurs when threads try to perform CUDA operations simultaneously on the same model, which is not inherently thread-safe.

The key to resolving this issue is ensuring each thread handles a separate instance of the model, as you correctly identified from the documentation. From your provided code, it appears you're attempting to load the model outside of the threading context, which could lead to the problems you're experiencing.

Try adjusting your `Tracker` class to instantiate the YOLO model inside the `run_tracker_in_thread` function rather than in the `__init__` method. This ensures that each thread creates and uses its own model instance, avoiding conflicts over CUDA resources. Here's a quick code adjustment suggestion:

```python
class Tracker(threading.Thread):

    def __init__(self, filename, model_path, file_index) -> None:
        super().__init__()
        self.filename = filename
        self.model_path = model_path
        self.file_index = file_index

    def run(self):
        self.run_tracker_in_thread(self.filename, self.model_path, self.file_index)

    def run_tracker_in_thread(self, filename, model_path, file_index):
        model = YOLO(model_path)  # Instantiate the model here
        video = cv2.VideoCapture(filename)
        # (Continue as before)
```

With this change, each thread loads its own model instance, which should help avoid the CUDA error you've been seeing.

Apologies for any confusion the documentation may have caused. If this modification doesn't resolve the issue, please let us know. Your feedback helps us improve our documentation and support. 🛠️ 

Let's try this and see how it goes. Good luck! 🍀

**Comment by thesky0605** [comment]
I think i get what the documentation means in the examples，i think the guides tell readers to instantiate the model as a local variable，but in track modes of the documentation，it gives a multithreaded tracking example，like bellow:
```
import threading
import cv2
from ultralytics import YOLO


def run_tracker_in_thread(filename, model, file_index):
    """
    Runs a video file or webcam stream concurrently with the YOLOv8 model using threading.

    This function captures video frames from a given file or camera source and utilizes the YOLOv8 model for object
    tracking. The function runs in its own thread for concurrent processing.

    Args:
        filename (str): The path to the video file or the identifier for the webcam/external camera source.
        model (obj): The YOLOv8 model object.
        file_index (int): An index to uniquely identify the file being processed, used for display purposes.

    Note:
        Press 'q' to quit the video display window.
    """
    video = cv2.VideoCapture(filename)  # Read the video file

    while True:
        ret, frame = video.read()  # Read the video frames

        # Exit the loop if no more frames in either video
        if not ret:
            break

        # Track objects in frames if available
        results = model.track(frame, persist=True)
        res_plotted = results[0].plot()
        cv2.imshow(f"Tracking_Stream_{file_index}", res_plotted)

        key = cv2.waitKey(1)
        if key == ord('q'):
            break

    # Release video sources
    video.release()


# Load the models
model1 = YOLO('yolov8n.pt')
model2 = YOLO('yolov8n-seg.pt')

# Define the video files for the trackers
video_file1 = "path/to/video1.mp4"  # Path to video file, 0 for webcam
video_file2 = 0  # Path to video file, 0 for webcam, 1 for external camera

# Create the tracker threads
tracker_thread1 = threading.Thread(target=run_tracker_in_thread, args=(video_file1, model1, 1), daemon=True)
tracker_thread2 = threading.Thread(target=run_tracker_in_thread, args=(video_file2, model2, 2), daemon=True)

# Start the tracker threads
tracker_thread1.start()
tracker_thread2.start()

# Wait for the tracker threads to finish
tracker_thread1.join()
tracker_thread2.join()

# Clean up and close windows
cv2.destroyAllWindows()
```
This example seemly tells me to instantiate the model in the main thread ，that's why the YOLO Thread-Safe Inference guides makes me confused.
Thank you for your reply very much!

**Comment by thesky0605** [comment]
Even though i instantiate the model as a local variable in the thread，i still meet the error randomly，here is my code：
```
class VideoTrackBuffer(threading.Thread):

    def __init__(self, yolo_path, stmn_path, video_path, output_path, name):
        super(VideoTrackBuffer, self).__init__()

        self.yolo_path = yolo_path
        self.stmn_path = stmn_path
        self.video_path = video_path
        self.output_path = output_path
        self.name = name
        self.gallery = {}

    def process_video(self, video_cap, video_output):
        yolo_model = YOLO(self.yolo_path)
        stmn_model = STMN(self.stmn_path)

        frame_count = 0
        max_frame_num = MAX_FRAME_NUM
        while video_cap.isOpened():
            frame_count += 1
            if frame_count > max_frame_num:
                break
            success, img = video_cap.read()
            if success:
                # print(self.name + 'yolo infer begin')
                results = yolo_model.track(img,
                                           persist=True,
                                           conf=0.3,
                                           iou=0.5,
                                           classes=[0, 2],
                                           verbose=False,
                                           tracker='/home/lxy/ultralytics/ultralytics/cfg/trackers/custom_tracker.yaml')
                # print(self.name + 'yolo infer end')
                boxes = results[0].boxes
                boxes_data = boxes.data
                id_list = list(map(int, boxes.id))
                detect_num = len(boxes_data)
                if detect_num == 0:
                    continue
                x1 = list(map(int, boxes_data[:, 0]))
                y1 = list(map(int, boxes_data[:, 1]))
                x2 = list(map(int, boxes_data[:, 2]))
                y2 = list(map(int, boxes_data[:, 3]))
                crop_img = [img[y1[i]:y2[i], x1[i]:x2[i]] for i in range(detect_num)]
                self.allocate_local_id(crop_img=crop_img, id_list=id_list)

                # allocate global id
                cur_frame_gallery = {}
                for i in range(detect_num):
                    tracklets = self.gallery[id_list[i]]
                    if tracklets.get_len() >= stmn_model.seq_len and tracklets.timeout == 0:
                        # print(self.name + 'stmn infer begin')
                        feat = stmn_model.data_procesess(tracklets.tracklets_buffer)
                        # print(self.name + 'stmn infer end')
                        cur_frame_gallery[tracklets.id] = feat
                        tracklets.reset_timeout()
                        # self.show_crop_img(id_list[i], frame_count)
                    else:
                        tracklets.reduce_timeout()
                local_dict, local_feat_mat = self.get_local_gallery(cur_frame_gallery)
                if len(local_feat_mat) > 0:
                    global_id = self.allocate_global_id(local_feat_mat)
                    for k, v in global_id.items():
                        tracklets = self.gallery[local_dict[k]]
                        tracklets.global_id = v

                new_img = img.copy()
                for i in range(detect_num):
                    p1 = (x1[i], y1[i])
                    p2 = (x2[i], y2[i])
                    p3 = (x1[i], y1[i] - 6)
                    id = ''
                    if self.gallery[id_list[i]].global_id is not None:
                        id = self.gallery[id_list[i]].global_id
                    cv2.rectangle(new_img, p1, p2, [0, 255, 0], thickness=2)
                    cv2.putText(new_img,
                                'lid:' + str(id_list[i]) + 'gid:' + str(id),
                                p3,
                                fontFace=cv2.FONT_HERSHEY_SCRIPT_SIMPLEX,
                                fontScale=1,
                                color=[53, 140, 250],
                                thickness=2,
                                lineType=cv2.LINE_AA)
                video_output.write(new_img)
                video_frames_path = '/home/lxy/ultralytics/lxy/results/video_frames/' + self.name + '-f' + str(
                    frame_count) + '.jpg'
                cv2.imwrite(video_frames_path, new_img)
                if cv2.waitKey(1) & 0xFF == ord("q"):
                    break
            else:
                break
        print(self.name + str(self.gallery.keys()))

    def run(self) -> None:
        video_cap = cv2.VideoCapture(self.video_path)
        fourcc = cv2.VideoWriter.fourcc(*'mp4v')
        width = int(video_cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        height = int(video_cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        fps = video_cap.get(cv2.CAP_PROP_FPS)
        video_output = cv2.VideoWriter(self.output_path, fourcc, fps, (width, height))
        print(self.name + str(video_cap))
        print(self.name + str(video_output))
        try:
            self.process_video(video_cap, video_output)
        finally:
            video_cap.release()
            video_output.release()
        print('video %s processed' % self.name)
```
```
from unicodedata import name
from video_tracker2 import VideoTrackBuffer

if __name__ == '__main__':
    root_path = '/home/lxy/ultralytics/lxy/'
    model_root = root_path + 'onnx_model/'
    data_root = root_path + 'data/'
    output_root = root_path + 'results/videos/'
    yolo_path = model_root + 'yolov8n.onnx'
    stmn_path = model_root + 'stmn.pth'
    video_path = [data_root + '2.mp4', data_root + '3.mp4']
    output_path = [output_root + '2.mp4', output_root + '3.mp4']
    video_name = ['2.mp4', '3.mp4']
    for i in range(2):
        videoi = VideoTrackBuffer(yolo_path=yolo_path,
                                  stmn_path=stmn_path,
                                  video_path=video_path[i],
                                  output_path=output_path[i],
                                  name=video_name[i])
        videoi.start()
    # video1 = VideoTrackBuffer(yolo_path=yolo_path,
    #                           stmn_path=stmn_path,
    #                           video_path=video_path[0],
    #                           output_path=output_path[0],
    #                           name=video_name[0])
    # video2 = VideoTrackBuffer(yolo_path=yolo_path,
    #                           stmn_path=stmn_path,
    #                           video_path=video_path[1],
    #                           output_path=output_path[1],
    #                           name=video_name[1])
    # video1.start()
    # video2.start()
    print('main thread ended')
```
here is the error information：
Exception in thread 2.mp4:
Traceback (most recent call last):
  File "/home/lxy/anaconda3/envs/yolov8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/lxy/ultralytics/lxy/video_tracker2.py", line 271, in run
    self.process_video(video_cap, video_output)
  File "/home/lxy/ultralytics/lxy/video_tracker2.py", line 193, in process_video
    results = yolo_model.track(img,
  File "/home/lxy/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/model.py", line 478, in track
    return self.predict(source=source, stream=stream, **kwargs)
  File "/home/lxy/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/model.py", line 439, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/lxy/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/predictor.py", line 206, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/home/lxy/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 44, in generator_context
    response = gen.send(None)
  File "/home/lxy/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/engine/predictor.py", line 288, in stream_inference
    continue
  File "/home/lxy/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/utils/ops.py", line 52, in __exit__
    self.dt = self.time() - self.start  # delta-time
  File "/home/lxy/anaconda3/envs/yolov8/lib/python3.8/site-packages/ultralytics/utils/ops.py", line 62, in time
    torch.cuda.synchronize(self.device)
  File "/home/lxy/anaconda3/envs/yolov8/lib/python3.8/site-packages/torch/cuda/__init__.py", line 402, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: operation not permitted when stream is capturing
^CException ignored in: <module 'threading' from '/home/lxy/anaconda3/envs/yolov8/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/home/lxy/anaconda3/envs/yolov8/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
terminate called without an active exception
This error occurs occasionally and randomly，i don't know how to fix it.
Looking forward to your reply, thank you very much!

**Comment by glenn-jocher** [comment]
@thesky0605 hey there! 😊 It looks like you're facing a CUDA operation issue with YOLOv8 when using thread-based parallelism. From your code, I noticed you're creating new instances of the YOLO model inside your `VideoTrackBuffer` threads; this practice should indeed help with thread safety. However, the sporadic nature of your error suggests we're dealing with a subtler concurrency issue related to CUDA's handling of threads.

One thing you could try to mitigate this issue is to ensure that CUDA operations across threads don't inadvertently overlap. A common approach in multi-threaded setups involving CUDA is to set a specific CUDA device per thread to isolate the CUDA context. However, in a practical scenario where you might be using a single GPU, this approach might not directly apply but is worth considering the underlying principle of operation isolation.

You haven't mentioned if you're synchronizing CUDA operations anywhere in your code. Sometimes, explicitly calling `torch.cuda.synchronize()` at strategic points in your processing pipeline can help avoid such errors, although it appears the error is thrown by this very function! This suggests there's an underlying issue with the CUDA context being captured across thread operations.

Given the complexity of debugging multi-threaded CUDA applications, consider these additional steps:

- **Reduce Complexity**: Temporarily simplify your setup to run a minimal number of threads. See if the issue persists and gradually add complexity.
- **Debugging Tools**: Employ CUDA debugging tools such as `cuda-gdb` or `nsight systems` for a deeper insight into the operations causing the stream capture issue.

Also, I noticed you're working with a custom tracker configuration (`custom_tracker.yaml`). Make sure the tracker's settings are compatible with multi-threading scenarios, although the error appears to be at a lower level within CUDA operations.

Lastly, ensure your environment (PyTorch, CUDA drivers, etc.) is up to date. Compatibility issues between PyTorch and CUDA versions can sometimes manifest in obscure errors.

Feel free to share any updates or additional insights you might uncover. Debugging these issues can be quite the puzzle, but every piece of information helps! 🧩

**Comment by vlasov01** [comment]
My code works fine in multi-threaded mode on Win11 (Ultralytics YOLOv8.2.32 🚀 Python-3.11.7 torch-2.3.1+cpu CPU (AMD Ryzen 9 7940HS w/ Radeon 780M Graphics)), but gets "terminate called without an active exception" when I run it on Ubuntu 23.10 ( Ultralytics YOLOv8.2.27 🚀 Python-3.11.6 torch-2.3.0 CPU (Cortex-A72) - GNU/Linux 6.5.0-1018-raspi aarch64).
It works fine in simgle-threaded mode in both cases.
I think the issue is not limited to CUDA.

**Comment by glenn-jocher** [comment]
Hello @vlasov01,

Thank you for reaching out and providing detailed information about your issue. It’s great to hear that your code works fine in a multi-threaded mode on Windows 11 but encounters issues on Ubuntu 23.10.

To help us investigate this further, could you please provide a minimum reproducible code example? This will allow us to reproduce the bug on our end and work towards a solution. You can find guidelines for creating a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example). This step is crucial for us to diagnose and resolve the issue effectively.

Additionally, I noticed that you are using different versions of Ultralytics YOLO and PyTorch on the two systems. Please ensure that you are using the latest versions of both `ultralytics` and `torch` on your Ubuntu setup. You can upgrade your packages using the following commands:

```bash
pip install --upgrade ultralytics
pip install --upgrade torch
```

After upgrading, please try running your code again and let us know if the issue persists.

Thank you for your cooperation, and we look forward to your response. 😊

**Comment by vlasov01** [comment]
@glenn-jocher Thank you for the quick reply! I was able to reproduce the issue with yolov5nu.pt model as well. I've upgraded them as per your instructions. But I've got the same issue again: Ultralytics YOLOv8.2.36 🚀 Python-3.11.6 torch-2.3.1 CPU (Cortex-A72)

YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
terminate called without an active exception
Aborted (core dumped)

**Comment by glenn-jocher** [comment]
Hi Sergey,

Thank you for the detailed information and for upgrading your packages as suggested. It’s helpful to see the specifics of your setup and the error messages you’re encountering.

Given that the issue persists even after upgrading, and considering the error message "terminate called without an active exception," it seems like there might be a deeper issue related to threading and resource management on your Ubuntu setup.

### Next Steps:

1. **Minimum Reproducible Example**: To help us investigate further, could you please provide a minimum reproducible code example? This will allow us to reproduce the bug on our end and work towards a solution. You can find guidelines for creating a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example). This step is crucial for us to diagnose and resolve the issue effectively.

2. **Python Version**: While the difference in Python versions (3.11.6 vs. 3.11.7) is unlikely to be the root cause, it’s worth ensuring consistency. You can try upgrading Python on your Ubuntu setup to match the version on your Windows machine.

3. **Dependency Conflicts**: The error message regarding `torchvision` and `torch` version mismatch might not be directly causing the issue, but resolving it could help. You can try installing a compatible version of `torchvision`:
    ```bash
    pip install torchvision==0.18.1
    ```

4. **Thread Synchronization**: Ensure that CUDA operations are properly synchronized across threads. Explicitly calling `torch.cuda.synchronize()` at strategic points in your code might help, although it appears the error is thrown by this very function. This suggests there's an underlying issue with the CUDA context being captured across thread operations.

5. **Environment Consistency**: Ensure that your environment on Ubuntu is as consistent as possible with your Windows setup. This includes not only the versions of `torch` and `ultralytics` but also other dependencies and system libraries.

### Example Code Adjustment:

Here’s a simplified example of how you might structure your code to ensure each thread has its own model instance:

```python
import threading
import cv2
from ultralytics import YOLO

class VideoTrackBuffer(threading.Thread):
    def __init__(self, yolo_path, video_path, output_path, name):
        super(VideoTrackBuffer, self).__init__()
        self.yolo_path = yolo_path
        self.video_path = video_path
        self.output_path = output_path
        self.name = name

    def process_video(self, video_cap, video_output):
        yolo_model = YOLO(self.yolo_path)
        frame_count = 0
        while video_cap.isOpened():
            success, img = video_cap.read()
            if not success:
                break
            frame_count += 1
            results = yolo_model.track(img, persist=True, conf=0.3, iou=0.5)
            res_plotted = results[0].plot()
            video_output.write(res_plotted)
            if cv2.waitKey(1) & 0xFF == ord("q"):
                break

    def run(self):
        video_cap = cv2.VideoCapture(self.video_path)
        fourcc = cv2.VideoWriter.fourcc(*'mp4v')
        width = int(video_cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        height = int(video_cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        fps = video_cap.get(cv2.CAP_PROP_FPS)
        video_output = cv2.VideoWriter(self.output_path, fourcc, fps, (width, height))
        try:
            self.process_video(video_cap, video_output)
        finally:
            video_cap.release()
            video_output.release()

if __name__ == '__main__':
    yolo_path = 'path/to/yolov8n.onnx'
    video_paths = ['path/to/video1.mp4', 'path/to/video2.mp4']
    output_paths = ['path/to/output1.mp4', 'path/to/output2.mp4']
    threads = []
    for i in range(2):
        thread = VideoTrackBuffer(yolo_path, video_paths[i], output_paths[i], f'video{i+1}')
        threads.append(thread)
        thread.start()
    for thread in threads:
        thread.join()
    print('Main thread ended')
```

Please try these steps and let us know if the issue persists. Your feedback is invaluable in helping us improve our tools and support. 😊

**Comment by vlasov01** [comment]
Thank you!
I've used the multithreaded code example from OpenCV repo https://fossies.org/linux/opencv/samples/python/video_threaded.py as the starting point. I've just used YOLOv8 instead of their processing.
Ubuntu 23.10 for RPi4 officially only supports Python 3.11.6. So I can't upgrade it without losing support.
I've installed torchvision 0.18.1. But there is no differences,
RPi4 doesn't have CUDA. I'm not sure how#4 appiies to my case.
Your code sample is using multiple video files. I need to process one video in parallel, 
The code has a reference to yolov8n.onnx . Is it provided by Ultralytics?

Thank you!

**Comment by glenn-jocher** [comment]
Hello @vlasov01,

Thank you for the detailed information and for sharing the context of your setup. Let's address your points one by one:

1. **Minimum Reproducible Example**: To help us investigate further, could you please provide a minimum reproducible code example? This will allow us to reproduce the bug on our end and work towards a solution. You can find guidelines for creating a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example). This step is crucial for us to diagnose and resolve the issue effectively.

2. **Python Version on Ubuntu 23.10**: Given that Ubuntu 23.10 for RPi4 officially supports Python 3.11.6, it's understandable that upgrading might not be feasible. However, ensuring that your `torch` and `ultralytics` packages are up to date is essential. You've already upgraded `torch` and `torchvision`, which is great.

3. **CUDA**: Since RPi4 doesn't have CUDA, the issue is likely related to threading and resource management rather than CUDA-specific operations. 

4. **Processing One Video in Parallel**: If you need to process a single video in parallel, you might consider splitting the video into segments and processing each segment in a separate thread. Here's a simplified example of how you might approach this:

    ```python
    import threading
    import cv2
    from ultralytics import YOLO

    class VideoSegmentProcessor(threading.Thread):
        def __init__(self, yolo_path, video_path, start_frame, end_frame, output_path, name):
            super(VideoSegmentProcessor, self).__init__()
            self.yolo_path = yolo_path
            self.video_path = video_path
            self.start_frame = start_frame
            self.end_frame = end_frame
            self.output_path = output_path
            self.name = name

        def run(self):
            yolo_model = YOLO(self.yolo_path)
            video_cap = cv2.VideoCapture(self.video_path)
            video_cap.set(cv2.CAP_PROP_POS_FRAMES, self.start_frame)
            fourcc = cv2.VideoWriter.fourcc(*'mp4v')
            width = int(video_cap.get(cv2.CAP_PROP_FRAME_WIDTH))
            height = int(video_cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
            fps = video_cap.get(cv2.CAP_PROP_FPS)
            video_output = cv2.VideoWriter(self.output_path, fourcc, fps, (width, height))

            frame_count = self.start_frame
            while frame_count <= self.end_frame:
                success, img = video_cap.read()
                if not success:
                    break
                results = yolo_model.track(img, persist=True, conf=0.3, iou=0.5)
                res_plotted = results[0].plot()
                video_output.write(res_plotted)
                frame_count += 1

            video_cap.release()
            video_output.release()

    if __name__ == '__main__':
        yolo_path = 'path/to/yolov8n.onnx'
        video_path = 'path/to/video.mp4'
        output_path = 'path/to/output.mp4'
        total_frames = int(cv2.VideoCapture(video_path).get(cv2.CAP_PROP_FRAME_COUNT))
        num_threads = 4
        segment_length = total_frames // num_threads

        threads = []
        for i in range(num_threads):
            start_frame = i * segment_length
            end_frame = (i + 1) * segment_length - 1 if i < num_threads - 1 else total_frames
            thread = VideoSegmentProcessor(yolo_path, video_path, start_frame, end_frame, f'output_segment_{i}.mp4', f'segment_{i}')
            threads.append(thread)
            thread.start()

        for thread in threads:
            thread.join()

        print('Processing complete')
    ```

5. **YOLOv8n.onnx Model**: The `yolov8n.onnx` model is not provided by default in the Ultralytics repository. You can export a YOLOv8 model to ONNX format using the following command:
    ```bash
    yolo export model=yolov8n.pt format=onnx
    ```

I hope this helps! If you have any further questions or need additional assistance, feel free to ask. 😊
