### ISSUE TITLE
Error in downloading 'Instance Segmentation' datasets yolov8

### ISSUE THREAD

**Issue by dhrhkddns** [ultralytics/ultralytics#9368]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![instance segmentation dataset download error](https://github.com/ultralytics/ultralytics/assets/59607551/fd987b08-c279-46c9-b29e-0eda591db5d8)

Hello, thank you always for YOLO8 from amazing software ultralitics :)

I tried do 'Instance Segmentation' so annotated datasets in Roboflow, but couldn't download the dataset through google colab or vs code in my computer. 

However, when I download the dataset from object detection, it works fine without any problems. How can the instance segmentation dataset also execute code without any problems?

**Comment by glenn-jocher** [comment]
@dhrhkddns hi there! 👋 Thanks for reaching out and for your kind words about YOLOv8! 😊

It sounds like you're encountering an issue specific to downloading the 'Instance Segmentation' dataset. Since it works fine for 'Object Detection' datasets, the process should generally be similar. To troubleshoot, could you please check if:

1. The dataset URL from Roboflow is correctly formatted and accessible.
2. Permissions for the dataset are set properly on Roboflow's side.

As a quick tip, ensure your download code snippet in Google Colab or VS Code matches the format provided by Roboflow, something like this for Google Colab:
```python
!curl -L "YOUR_DATASET_URL" > roboflow.zip; unzip roboflow.zip
```

Replace `"YOUR_DATASET_URL"` with the link to your 'Instance Segmentation' dataset.

If you continue to face issues, feel free to share the error messages or specific steps where it fails. We're here to help! 🙌
