### ISSUE TITLE
imgsz=[720, 1280] must be multiple of max stride 32

### ISSUE THREAD

**Issue by tjasmin111** [ultralytics/ultralytics#9370]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I was trying to train my models on HD images of 1280x720. But I get this error: Since 720p is an important resolution, is there any ways to change the stride or getting around this error? 
`WARNING ⚠️ imgsz=[720, 1280] must be multiple of max stride 32, updating to [736, 1280]`

**Comment by captainfffsama** [comment]
I think 1280 >720,so model will padding 720 to 736 instead of simple resize...The effect of this operation on the performance of the model should be small

**Comment by flyinghu123** [comment]
I think this is because the convolution network implements different scales, and then because the network is downsampled five times, the network input size must be divided by 2 ^ 5.

**Comment by glenn-jocher** [comment]
@flyinghu123 yes, you're correct! 😊 The network's input size needs to be divisible by \(2^5 = 32\) due to it being downsampled five times. This process ensures compatibility with the internal architecture of the convolutional network, allowing for efficient scaling and processing. Thanks for pointing that out! If you have further questions or need assistance, feel free to ask.
