### ISSUE TITLE
Mosaic Class does not use Config Probability Parameter

### ISSUE THREAD

**Issue by f-haces** [ultralytics/ultralytics#9388]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Augmentation

### Bug

The [Mosaic class](https://github.com/ultralytics/ultralytics/blob/ed2250cf1cb494350568011a45e6219fb605790b/ultralytics/data/augment.py#L135), which is used within the default [V8 transforms](https://github.com/ultralytics/ultralytics/blob/ed2250cf1cb494350568011a45e6219fb605790b/ultralytics/data/augment.py#L973) definition, does not use the `p` parameter, which is appropriately piped from both the config and CLI parameters. There is an [assert statement](https://github.com/ultralytics/ultralytics/blob/ed2250cf1cb494350568011a45e6219fb605790b/ultralytics/data/augment.py#L151) in the mosaic class to ensure the probability is within [0, 1]. However, `p` has not been set as an object attribute, or actually been implemented.

### Environment

Ultralytics YOLOv8.1.16 🚀 Python-3.8.18 torch-2.2.1 CUDA:0 (NVIDIA GeForce RTX 3070, 8191MiB)
Setup complete ✅ (16 CPUs, 63.9 GB RAM, 877.5/930.9 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.8.18
Install             pip
RAM                 63.91 GB
CPU                 AMD Ryzen 7 3700X 8-Core Processor
CUDA                12.1

matplotlib          ✅ 3.7.3>=3.3.0
opencv-python       ✅ 4.9.0>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.2.1>=1.8.0
torchvision         ✅ 0.17.1>=0.9.0
tqdm                ✅ 4.66.2>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ❌ (not installed)>=0.1.1
pandas              ✅ 2.0.3>=1.1.4

### Minimal Reproducible Example

`yolo detect train mosaic=0`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@f-haces 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. **Your bug report is not reproducible, mosaic probability works correctly:**

```bash
yolo train mosaic=0.5
```

![train_batch1](https://github.com/ultralytics/ultralytics/assets/26833433/2e4b9d74-e12a-495b-8e84-ffc2c3f865e2)

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.


## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by f-haces** [comment]
Thank you for your quick response. I apologize, I misunderstood the role of `p` in the Mosaic class; it is [passed to `BaseMixTransform`](https://github.com/ultralytics/ultralytics/blob/ed2250cf1cb494350568011a45e6219fb605790b/ultralytics/data/augment.py#L153), not implemented in the Mosaic class. After modifying my augmentation code, it works appropriately.

**Comment by glenn-jocher** [comment]
@f-haces no worries at all! I'm glad to hear that you've worked it out and everything is running smoothly now. 😊 If you have any more questions or need further assistance, please don't hesitate to ask. Happy coding!
