### ISSUE TITLE
predict fails on torch tensor with resolution not divisible by stride, but succeeds when providing path

### ISSUE THREAD

**Issue by gino-figma** [ultralytics/ultralytics#9396]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

I'm trying to run inference on an image with an odd resolution (4081x1440). This succeeds without issues when providing an image path, and I can see that the image is being resized to a size compatible with the 32-stride:
```
Speed: 1.1ms preprocess, 29.4ms inference, 0.3ms postprocess per image at shape (1, 3, 640, 256)
```

However, if I convert the same image to a torch tensor first and pass it to the model, it fails with

```
ValueError: WARNING ⚠️ torch.Tensor inputs should be BCHW i.e. shape(1, 3, 640, 640) divisible by stride 32. Input shape(1, 3, 4081, 1440) is incompatible.
```

This makes me suspect that the images are not actually preprocessed in the exact same way? I would expect the model to handle the torch tensor and preprocess it using the same `Letterbox` method.

### Minimal Reproducible Example

```
from ultralytics import YOLO
model = YOLO('yolov8n.pt')

image_path = 'images/train/syHYucyL7TKORZnkF2dnkW_0:1535.png'
model(image_path)
```
--> succeeds

```
from torchvision import transforms
transform = transforms.ToTensor()

img_tensor = transform(img)
img_tensor = img_tensor.unsqueeze(0)
model(img_tensor)
```

--> fails with 
```
ValueError: WARNING ⚠️ torch.Tensor inputs should be BCHW i.e. shape(1, 3, 640, 640) divisible by stride 32. Input shape(1, 3, 4081, 1440) is incompatible.
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@gino-figma hey there! 🌟 Thanks for bringing this up. It looks like the difference you're seeing is because when you pass an image path to the model, it automatically handles resizing among other preprocessing steps. However, when you directly pass a torch tensor, these steps need to be manually performed.

To pre-process the tensor similar to how paths are handled internally, you can use the `ultralytics.transforms` module to apply the right transformations, including resizing to a stride-divisible resolution. Here's how you might do it:

```python
from torchvision import transforms
from ultralytics import YOLO, transforms as ul_transforms

model = YOLO('yolov8n.pt')

# Load your image as img here
transform = transforms.Compose([
    transforms.ToTensor(),
    ul_transforms.Resize(size=(640, 640))  # Resize to model's expected input size
])

img_tensor = transform(img).unsqueeze(0)  # Add batch dimension
model(img_tensor)
```

This should handle the preprocessing in a way that's compatible with model expectations, preventing the stride error! Hope this helps and keep up the great exploration with YOLOv8! ✌️

**Comment by gino-figma** [comment]
Hmm I understand that this silences the error, but this does not seem like an adequate solution. Just resizing the image will cause the input to look quite different than when it's actually going to the proper preprocessing steps, specifically `self.pre_transform` in `BasePredictor`:

https://github.com/ultralytics/ultralytics/blob/main/ultralytics/engine/predictor.py#L123

```
        if not_tensor:
            im = np.stack(self.pre_transform(im))
            im = im[..., ::-1].transpose((0, 3, 1, 2))  # BGR to RGB, BHWC to BCHW, (n, 3, h, w)
            im = np.ascontiguousarray(im)  # contiguous
            im = torch.from_numpy(im)
```

Is there a way to apply the **exact** same preprocessing to tensors? This seems very important in CV applications since we'll want to make sure the inference data is processed exactly the same way as the training/validation data.

**Comment by glenn-jocher** [comment]
@gino-figma Tensor inputs are raw data that should have already undergone preprocessing, so if you prefer to avoid preprocessing use any of our other input methods. 

See details in Docs:
https://docs.ultralytics.com/modes/predict/#inference-sources

<img width="1941" alt="Screenshot 2024-03-30 at 23 56 57" src="https://github.com/ultralytics/ultralytics/assets/26833433/2344b118-b8ec-4b1c-a9ce-af7969e97a1e">

**Comment by jurijsnazarovsambientai** [comment]
same issue.

**Comment by glenn-jocher** [comment]
Hey there! 👋 It looks like you're encountering a common issue. Could you please provide more details or share the code snippet you're using? This will help us understand the context better and assist you more effectively. Thanks!

**Comment by SuperMasterBlasterLaser** [comment]
@glenn-jocher Hello.

I've also received this error when I tried to classify my image that turned into tensor:

    WARNING ⚠️ torch.Tensor inputs should be BCHW i.e. shape(1, 3, 640, 640) divisible by stride 32. Input shape(1, 1000, 1000, 3) is incompatible.

I know that my image is 1000x1000 I tried to convert it like this:

    transform = transforms.Compose([
        transforms.Resize(size=(640, 640))  # Resize to model's expected input size
    ])

However it created shape: shape(1, 1000, 640, 640), how to change it to preferable shape?

**Comment by Tuntenfisch** [comment]
I also fail to understand the reasoning for why tensors are treated differently from the other input methods. Saying "Tensor inputs are raw data" is only true because you choose to label them as such. You could just as well treat them in the same manner as the other input methods.

I've even attempted to apply the `LetterBox` transform myself but the underlying implementation cannot deal with `Tensor` types. Specifically the call to `cv2.resize(...)` [here](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/data/augment.py#L771) fails with:
```
cv2.error: OpenCV(4.10.0) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - src is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'src'
```

**Comment by glenn-jocher** [comment]
Hi @Tuntenfisch,

Thank you for your detailed feedback and for highlighting this issue. You bring up a valid point regarding the handling of tensor inputs.

The current design treats tensor inputs as preprocessed data to provide flexibility for advanced users who might have custom preprocessing pipelines. However, we understand the need for consistency across different input types, especially for ensuring that inference data is processed identically to training/validation data.

To address your specific issue with the `LetterBox` transform and `cv2.resize`, you can convert the tensor to a numpy array before applying the transformation. Here's an example of how you might do this:

```python
import torch
import numpy as np
import cv2
from ultralytics import YOLO
from ultralytics.data.augment import LetterBox

# Load model
model = YOLO('yolov8n.pt')

# Example tensor input
img_tensor = torch.randn(1, 3, 4081, 1440)

# Convert tensor to numpy array
img_numpy = img_tensor.squeeze(0).permute(1, 2, 0).cpu().numpy()

# Apply LetterBox transform
letterbox = LetterBox(new_shape=(640, 640))
img_resized = letterbox(img_numpy)

# Convert back to tensor
img_resized_tensor = torch.from_numpy(img_resized).permute(2, 0, 1).unsqueeze(0)

# Run inference
results = model(img_resized_tensor)
```

This approach ensures that the preprocessing steps are consistent with those applied internally by the model when using image paths.

We appreciate your patience and feedback as we continue to improve the usability of our library. If you encounter any further issues or have additional suggestions, please feel free to share them. Also, ensure you are using the latest version of the library to benefit from recent updates and fixes.

For a more detailed guide on creating reproducible examples, you can refer to our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example).

Thank you for your engagement and contributions to improving our tools! 😊

**Comment by haavarpb** [comment]
Just want to chime in here, since I am having the same problems.

I am developing an application that uses a camera that allows me to fetch images on the gpu. Right now I have a cupy array that I'd like to run through one of your models. Converting the image to a numpy array is something I want to avoid since that entails moving the image back to host and then back to device (assuming the model is on the device). This is uneccesary slow.

I just tried the tensor variant using `torch.as_tensor(cupy_array)` to keep it on the gpu for prediction, but stumbled upon this exact inconsistency. I'd call it a inconsistency, since as a user I can't find any information in the "inference sources" page that tells me that the tensors are dealt with differently.

I'd suggest either documenting this difference, or to fix the inconsistency.

In the mean time, I'll try to figure out how to do the preprocessing myself...

**Comment by glenn-jocher** [comment]
Thanks for the clear context—you're right that `torch.Tensor` inputs intentionally skip `pre_transform`/`LetterBox` in `predictor.preprocess`, so tensors must be letterboxed and normalized by the caller; see the [predictor preprocess reference](https://docs.ultralytics.com/reference/engine/predictor/#preprocess) and the [LetterBox transform reference](https://docs.ultralytics.com/reference/data/augment/#ultralytics.data.augment.LetterBox). To stay on GPU with CuPy, you can import via DLPack and apply a Torch-only letterbox:

```python
import torch
import torch.nn.functional as F
from torch.utils.dlpack import from_dlpack
from ultralytics import YOLO

def letterbox_tensor(x, new_shape=(640, 640), stride=32, scaleup=True, pad_value=114/255.0, center=True):
    # x: (B, C, H, W) float in [0,1]
    b, c, h, w = x.shape
    if isinstance(new_shape, int):
        new_shape = (new_shape, new_shape)
    r = min(new_shape[0] / h, new_shape[1] / w)
    if not scaleup:
        r = min(r, 1.0)
    new_w, new_h = int(round(w * r)), int(round(h * r))
    if (new_h, new_w) != (h, w):
        x = F.interpolate(x, size=(new_h, new_w), mode='bilinear', align_corners=False)
    dw, dh = new_shape[1] - new_w, new_shape[0] - new_h
    if center:
        left, right = int(round(dw/2 - 0.1)), int(round(dw/2 + 0.1))
        top, bottom = int(round(dh/2 - 0.1)), int(round(dh/2 + 0.1))
    else:
        left, right, top, bottom = 0, dw, 0, dh
    return F.pad(x, (left, right, top, bottom), value=pad_value)

# CuPy HWC uint8 -> Torch BCHW float [0,1] on GPU without host copy
cupy_img = ...  # HWC, uint8
t = from_dlpack(cupy_img.toDlpack()).permute(2, 0, 1).unsqueeze(0).float().div_(255.0).to('cuda')

t = letterbox_tensor(t, new_shape=(640, 640))
results = YOLO('yolov8n.pt')(t)
```

Since this thread is closed/stale, please open a new issue so we can track improving the docs to call out the tensor-path behavior and discuss options; a small reproducible snippet like above would be perfect.
