### ISSUE TITLE
Model configuration file, and models cannot use custom paths

### ISSUE THREAD

**Issue by zhenhuamo** [ultralytics/ultralytics#9397]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

![1711693523682](https://github.com/ultralytics/ultralytics/assets/46718957/fb953931-51bb-4011-a6f9-55777cbc5414)

### Minimal Reproducible Example

    self.ModelYamlFilePath =  H:/PythonCode/TrtYoloTrain/main/models/v8/yolov8n.yaml       
  model = YOLO(self.ModelYamlFilePath)           
 self.selectedModelSize = model/det/yolov8n
  modelFilePath = f'{self.selectedModelSize}.pt'  # 假设模型文件名与模型大小匹配
  model = YOLO(modelFilePath)
          
            

       

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by gino-figma** [comment]
The part that's causing the failure is the `LoadTensor` dataloader.: https://github.com/ultralytics/ultralytics/blob/main/ultralytics/data/loaders.py#L477

However, there is no equivalent check in the `LoadImages` dataloader.

I think the crux might be here: https://github.com/ultralytics/ultralytics/blob/main/ultralytics/engine/predictor.py#L123

```
        if not_tensor:
            im = np.stack(self.pre_transform(im))
            im = im[..., ::-1].transpose((0, 3, 1, 2))  # BGR to RGB, BHWC to BCHW, (n, 3, h, w)
            im = np.ascontiguousarray(im)  # contiguous
            im = torch.from_numpy(im)
```
we only perform preprocessing if the input is not a torch tensor. If it is a torch tensor, do we expect the user to have already preprocessed it manually? Do you recommend using numpy over torch?

**Comment by zhenhuamo** [comment]
am training, when I enter a custom yaml file, such as: self.ModelYamlFilePath = H:/PythonCode/TrtYoloTrain/main/models/v8/yolov8n.yaml
model = YOLO(self.ModelYamlFilePath)
An error will occur when running here.
FileNotFoundError: [Errno 2] No such file or directory: 'H:\\PythonCode\\TrtYoloTrain\\main\\models\\v8\\yolov8.yaml'

**Comment by glenn-jocher** [comment]
@zhenhuamo hello! It seems like you're encountering a `FileNotFoundError` due to the specified YAML file path not being recognized. This could be caused by a typo in the file name or the path leading to the file. Let's try a couple of things to resolve the issue:

1. **Check the FilePath**: Ensure the path `H:/PythonCode/TrtYoloTrain/main/models/v8/yolov8n.yaml` is correct and that the file `yolov8n.yaml` indeed exists at that location.
2. **Path Format**: Try using double backslashes `\\` or the raw string format for the path in Python. For example:
   ```python
   self.ModelYamlFilePath = r"H:\PythonCode\TrtYoloTrain\main\models\v8\yolov8n.yaml"
   ```

Also, ensure that the filename in the error message `yolov8.yaml` is a typo in your message and that the intended file is `yolov8n.yaml`. If the error persists after these checks, it might be beneficial to print out the file path before loading to confirm the script sees the correct path:

```python
print(self.ModelYamlFilePath)
model = YOLO(self.ModelYamlFilePath)
```

This will help confirm if the path specified is exactly what the script is trying to access. Let me know how it goes!
