### ISSUE TITLE
Converting classification model to Tflite using Yolov8

### ISSUE THREAD

**Issue by PriyamDalwadii** [ultralytics/ultralytics#9411]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

How can I successfully convert pytorch classification model to tflite?

**Comment by himalayo** [comment]
Hello, if your model happens to be a YOLO, I'd recommend using the [https://docs.ultralytics.com/modes/export/](export mode). To do so, you'd only need to run `yolo export model=path/to/best.pt format=tflite` on your command line.
If it doesn't follow the YOLO architecture, it does get quite tricky, unfortunately.  If that's the case, it would be of great help if more information about your issue was shared. :)

**Comment by glenn-jocher** [comment]
@himalayo hello! Absolutely, if your model is part of the YOLO family, converting it to TensorFlow Lite (TFLite) is quite straightforward using the export mode. Just run the following command in your terminal:

```bash
yolo export model=path/to/best.pt format=tflite
```

If your model doesn't align with YOLO architecture, the process could involve more steps and might be specific to the architecture of your model. In that scenario, sharing more details about the model and the issues you're facing would greatly help in providing a more tailored solution. 😊
