### ISSUE TITLE
when try export yolov8 custom trained model to onnx format,  new exported model names property is None. 

### ISSUE THREAD

**Issue by tolahs** [ultralytics/ultralytics#9417]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

Hi ;
when try  export  yolov8 custom trained model to onnx format  new exported model names property is None. 

### the version infos:
ultralytics                  8.1.37
onnx                         1.16.0
onnxruntime                  1.16.0

### The executing proccess same as bellow 
```
from ultralytics import YOLO
model = YOLO('yolov8n.pt')
results = model.train(data='data.yml', epochs=1, imgsz=640)
model = YOLO(model="runs\\detect\\train\\weights\\best.pt") 
print(f"DEFAULT mdel names: {model.names}")
model.export(format='onnx')
model = YOLO(model="runs\\detect\\train\\weights\\best.onnx") 
print(f"ONNX mdel names: {model.names}")
```
### The out put is 
DEFAULT mdel names: {0: 'ID_CARD_BACK', 1: 'ID_CARD_FRONT'}
ONNX mdel names: None

### The data.yml is bellow 

`
train: data/train/ # path to the train folder
val: data/val/ #path to the val folder

names:
    0: ID_CARD_BACK
    1: ID_CARD_FRONT
`

### Environment

Ultralytics YOLOv8.1.37 🚀 Python-3.11.7 torch-2.2.0+cu121 CUDA:0 (NVIDIA GeForce RTX 3050 Ti Laptop GPU, 4096MiB)
Setup complete ✅ (20 CPUs, 31.7 GB RAM, 68.8/465.1 GB disk)

### Minimal Reproducible Example

```
from ultralytics import YOLO
model = YOLO('yolov8n.pt')
results = model.train(data='data.yml', epochs=1, imgsz=640)
model = YOLO(model="runs\\detect\\train\\weights\\best.pt") 
print(f"DEFAULT mdel names: {model.names}")
model.export(format='onnx')
model = YOLO(model="runs\\detect\\train\\weights\\best.onnx") 
print(f"ONNX mdel names: {model.names}")
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@tolahs hello! 👋

Thanks for reaching out and for providing detailed information about the issue you encountered when exporting your YOLOv8 custom trained model to ONNX format. It seems like the class names are not being retained in the ONNX model.

When exporting YOLO models to ONNX, the class names metadata may not always be carried over directly within the ONNX model itself. Instead, you can manually associate your class names with the exported ONNX model for subsequent operations.

Here's a quick workaround you can use after exporting your model:

```python
from ultralytics import YOLO

# Define your class names
class_names = {0: 'ID_CARD_BACK', 1: 'ID_CARD_FRONT'}

# Load the exported ONNX model
model = YOLO(model="runs\\detect\\train\\weights\\best.onnx")

# Manually set the model's names attribute
model.names = class_names

# Now, you should be able to access the class names as expected
print(f"ONNX model names: {model.names}")
```

This way, you can ensure that your class names are accessible after exporting your model to ONNX format. 🚀

If you have any further questions or need more assistance, feel free to ask. Also, since you've expressed interest in submitting a PR, enhancements to retain metadata through the export process are always welcome!

Happy coding!

**Comment by tolahs** [comment]
Thanks for your fast reply ;

The error occured when creating model if  I set parameter `verbose=true`.  So if we go through your example
`model = YOLO(model="runs\\detect\\train\\weights\\best.onnx", verbose=true)`
raised the error when above code executing. Because of verbose method use names 
The code causing the error below.
.venv\Lib\site-packages\ultralytics\engine\results.py
Line : 327 `log_string += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, `
```
def verbose(self):
        """Return log string for each task."""
        log_string = ""
        probs = self.probs
        boxes = self.boxes
        if len(self) == 0:
            return log_string if probs is not None else f"{log_string}(no detections), "
        if probs is not None:
            log_string += f"{', '.join(f'{self.names[j]} {probs.data[j]:.2f}' for j in probs.top5)}, "
        if boxes:
            for c in boxes.cls.unique():
                n = (boxes.cls == c).sum()  # detections per class
                log_string += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, 
        return log_string
```
there is no posbiltiy to set model.names.
I can hang the issue as verbose=false. However, I am worried about encountering a similar situation elsewhere.

**Comment by glenn-jocher** [comment]
@tolahs hey there! 👋

Thanks for the additional details and for pointing out the issue with the `verbose` parameter. It indeed looks like the absence of class names in the ONNX model is causing an error when verbose output is enabled. 

Since the class names aren't inherently stored in the ONNX model, a workaround is required when aiming to use features that rely on them, like the `verbose` output. Before using the `verbose` option with an ONNX model, you'll need to manually assign the class names to the `model.names` attribute as shown below. 

```python
from ultralytics import YOLO

# Define class names
class_names = {0: 'ID_CARD_BACK', 1: 'ID_CARD_FRONT'}

# Load the ONNX model
model = YOLO(model="runs\\detect\\train\\weights\\best.onnx")

# Manually set the class names
model.names = class_names

# Now you should be able to use verbose without an issue
results = model.predict(source='path/to/image.jpg', verbose=True)
```

We appreciate your concern about possible similar situations. For now, this manual step will be necessary when working with exported models in certain contexts. Your feedback is valuable, and we're always looking for ways to enhance the user experience in scenarios like these. 🚀

Keep the great observations coming, and don't hesitate if you've got more questions or insights!

**Comment by tolahs** [comment]
Ok . I tried as your explained but given error occured

Exception has occurred: AttributeError
property 'names' of 'YOLO' object has no setter

**Comment by glenn-jocher** [comment]
@tolahs hey there! 😊

It looks like we hit a snag with setting the `names` attribute directly. As a quick workaround, you can handle this by directly assigning the class names when needing them, say, for display or logging purposes, instead of setting them on the model object. 

Here's a quick example on how you might do this when you're about to use `verbose`:

```python
# Assuming you've already loaded your ONNX model as `model`
class_names = {0: 'ID_CARD_BACK', 1: 'ID_CARD_FRONT'}

# When you're ready to use verbose, pass and use `class_names` directly
# For instance, displaying prediction results with names
results = model.predict(source='path/to/image.jpg', verbose=False)  # Temporarily disable verbose
for result in results:
    print(f"{class_names.get(result.cls, 'Unknown')} detected with confidence {result.conf:.2f}") 
```

This approach lets you utilize the class names externally without needing to modify the model object itself. 

If you have further questions or run into more issues, feel free to reach out! Happy coding! 🚀

**Comment by glenn-jocher** [comment]
@tolahs I've opened a PR #9439 that partially addresses this problem. model.names will now be defined for all export models once the predictor has been initialized. You can initialize the predictor just by running inference on an image (or a blank numpy array):

```python
from ultralytics import YOLO

model=YOLO('yolov8n.onnx')

model.predict()

print(model.names)
```
