### ISSUE TITLE
Incorrectly load ema weights when resuming training

### ISSUE THREAD

**Issue by jameslahm** [ultralytics/ultralytics#9426]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

As shown in https://github.com/ultralytics/ultralytics/blob/03d0ffd9f58da3ad3e33908c19445c733a701015/ultralytics/engine/trainer.py#L524
and
https://github.com/ultralytics/ultralytics/blob/03d0ffd9f58da3ad3e33908c19445c733a701015/ultralytics/nn/tasks.py#L788-L792
, when resuming training, the model weights will be loaded with ema weights rather than the normal weights. Is it intended or a bug? Thanks!

### Environment

OS                  Linux-5.11.0-44-generic-x86_64-with-glibc2.17
Environment         Linux
Python              3.8.18
Install             git
CPU                 Intel Xeon Gold 6148 2.40GHz
CUDA                11.3

matplotlib          ✅ 3.7.5>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.28.2>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 1.10.1>=1.8.0
torchvision         ✅ 0.11.2>=0.9.0
tqdm                ✅ 4.65.2>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@jameslahm hey there, thanks for bringing this to our attention! 🙂 The behavior you've pointed out involves loading the Exponential Moving Average (EMA) weights when resuming training. This is indeed intended functionality rather than a bug. EMA weights tend to provide smoother and more stable representations of the model's state over epochs, which is why they're used during the resume operation for potentially better performance upon continuation.

However, if you prefer to load the regular weights instead of the EMA weights when resuming training, you might want to consider customizing the loading mechanism to suit your needs. Unfortunately, changing this would require a bit of manual tweaking in the code as mentioned in the lines you've referenced.

Hope this clarifies your query! If you have more questions or need further assistance, feel free to ask.
