### ISSUE TITLE
如何导出和v5 一样输出的onnx

### ISSUE THREAD

**Issue by shuifuture** [ultralytics/ultralytics#9458]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

v5  6.0版本导出onnx的输入[1,3,448,640]，输出[1,17640,85]，但是v8  的导出onnx 输出[1,84,5880]   该如何变换，model.export(format='onnx',imgsz=[448,640],opset=11,simplify=True,device="cpu")

### Additional

v5  6.0版本导出onnx的输入[1,3,448,640]，输出[1,17640,85]，但是v8  的导出onnx 输出[1,84,5880]   该如何变换，model.export(format='onnx',imgsz=[448,640],opset=11,simplify=True,device="cpu")

**Comment by glenn-jocher** [comment]
@shuifuture hey there! 👋 For exporting YOLOv8 to ONNX with specific output shapes similar to YOLOv5, keep in mind that architectural differences between YOLOv8 and YOLOv5 might lead to different output formats. However, the command you've provided is essentially correct for exporting a YOLOv8 model to ONNX:

```python
model.export(format='onnx', imgsz=[448, 640], opset=11, simplify=True, device="cpu")
```

Regarding reshaping the output to match YOLOv5's format, ONNX models can be further processed with ONNX tools. If you're looking to reshape or manipulate the output further, you might use ONNX's python API to load the exported ONNX model and modify its graph accordingly.

Do note, if you require specific output shapes due to your processing pipeline, you may need to adjust your post-processing steps to align with YOLOv8's output structure. Each version of YOLO can have intrinsic differences in architecture that naturally lead to variations in output dimensions.

If you've got more questions or need further assistance, feel free to ask! 🚀
