### ISSUE TITLE
yolov8 export simplify and optimize flags

### ISSUE THREAD

**Issue by tjasmin111** [ultralytics/ultralytics#9475]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I'm exporting a model into onnx. What do `simplify` and `optimize` flags really do and what's their effects on the performance of a deployed model?
`yolo export model=best.pt format=onnx imgsz=640 simplify=True`

I noticed the size of the onnx model still remails the same. And with some quick testing, I didn't notice any change in speed and inference time,

`yolo detect predict model=best.onnx imgsz=640 source=test.jpg`

**Comment by glenn-jocher** [comment]
@tjasmin111 hey there! 😊 The `simplify` flag, when exporting to ONNX, attempts to reduce the model's complexity by eliminating redundant nodes and combining operations where possible. This can potentially make the model more efficient for certain ONNX-compatible inference engines, though the effects might not always be noticeable in terms of file size or direct inference speed improvements.

The `optimize` flag is more relevant when exporting models in formats that explicitly support optimization phases, such as TorchScript. It aims to enhance the model's execution speed by applying various PyTorch JIT optimizations.

In your case, since the `simplify` flag didn't visibly affect the ONNX model's performance or size, it's possible that your model structure or the nature of the optimizations already applied during training didn't leave much room for further simplification. Different inference engines and hardware environments might reveal more about the benefits of these flags. Testing across multiple platforms could provide a clearer picture of their impact. 

Keep experimenting, and don't hesitate to reach out with further observations or questions!
