### ISSUE TITLE
Tuning issue with ray

### ISSUE THREAD

**Issue by chandra-ps612** [ultralytics/ultralytics#9499]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

While tuning yolov8 hyper-parameters using ```ray```, I'm getting following issues below-
**python**
```
from ultralytics import YOLO
model = YOLO('path to best ckpt')
result_grid = model.tune(use_ray = True, gpu_per_trial = 1, train_args = {'batch':-1, 'imgsz':416, 'epochs':100, 'device':0, 'workers':4})
```
**Information regarding num_samples and device** 
![Screenshot from 2024-04-02 12-54-17](https://github.com/ultralytics/ultralytics/assets/89622996/36f96c96-980e-472b-b1ab-5f213d105388)
**Information regarding failed trials**
![Screenshot from 2024-04-02 13-01-31](https://github.com/ultralytics/ultralytics/assets/89622996/df25b97e-934f-4e11-a370-ae731a791282)
**Information regarding 1st trial**
![Screenshot from 2024-04-02 12-55-36](https://github.com/ultralytics/ultralytics/assets/89622996/e916edf3-462c-41e8-8919-aad9cc76edb7)

**1. disk space issue**
![Screenshot from 2024-04-02 12-55-06](https://github.com/ultralytics/ultralytics/assets/89622996/44c01d85-8c49-4531-8bcb-ead7b5404fc9)
**2. CUDA out of memory issue**
![Screenshot from 2024-04-02 12-57-39](https://github.com/ultralytics/ultralytics/assets/89622996/41adfe02-61f5-4437-a5e3-8a1b69a8b412)
**3. Trial failure issue**
![Screenshot from 2024-04-02 13-01-07](https://github.com/ultralytics/ultralytics/assets/89622996/c1ee27c7-5453-4825-8015-424f06a86e77)

### Additional

**packages for python == 3.10.11**
```
torch==1.12.1+Cu10.2
torchaudio==0.12.1+Cu10.2
torchvision==0.13.1+Cu10.2
ultralytics==8.1.22
ray==2.9.3
```
Note: Utilizing auto batch and imgsz=416 for nano(n) architecture in order to mitigate ```CUDA out of memory``` issue but, it is not helping me out. Apart from it, disk where tuning results are being stored has just 16 GB free space left.
Any suggestions will be helpful!
Thanks,

**Comment by glenn-jocher** [comment]
@chandra-ps612 it looks like you're encountering some common issues when tuning YOLOv8 hyperparameters with Ray. Here are some suggestions that might help:

1. **Disk Space Issue**: Ensure you have ample disk space before starting the tuning process. Remove unnecessary files or target a disk with more space if possible. Ray tuning can generate a lot of data, especially with multiple trials.

2. **CUDA Out of Memory**: This could be due to running large models or having insufficient GPU memory. Consider:
   - Reducing `imgsz` further if possible.
   - Decreasing `workers` to free up some memory.
   - Using a more memory-efficient model if available.
   - Also, ensure you're not running other GPU-intensive processes simultaneously.

3. **Trial Failure**: Trial failures can arise from various issues. Given the CUDA memory and disk space issues you're facing, resolving those might alleviate these failures. Additionally, check the trial logs for specific error messages that could indicate other underlying problems.

For managing CUDA memory more effectively, you could consider dynamic adjustment of `batch` size based on available memory. However, this requires custom code adjustments and is not directly supported through current arguments.

Also, to manage disk space, consider periodically monitoring the space consumed by Ray's log and output directories during the tuning process and adjust `num_samples` if necessary.

```python
from ultralytics import YOLO

model = YOLO('path to best ckpt')
# Consider lowering `imgsz` and `workers` if memory issues persist
# Adjust `gpu_per_trial` if running on multi-GPU setup to distribute memory load
result_grid = model.tune(use_ray=True, gpu_per_trial=1,
                         train_args={'batch': -1, 'imgsz': 416, 'epochs': 100, 'device': 0, 'workers': 2})
```

Remember, tuning is often a process of balancing resources. Adjusting trial parameters based on your system's limitations is key. If issues persist, consider tuning with fewer `num_samples` or on a system with more resources. Hope this helps! 🚀
