### ISSUE TITLE
YOLOv8 POSE TRAIN CODE IS USING VAL DATASET NOT THE TRAIN DATASET

### ISSUE THREAD

**Issue by benicio22** [ultralytics/ultralytics#9532]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,  I am running my pose yolov8 train, but the train code is using the val dataset to train my model not the train dataset. The YAML is correct, showing the proper place of the training dataset. But still, I need help with this.  Have 400 images for the train and 100 for val.  The code is running in Pycharm. 

Using this code here: 

From paralytics import YOLO

# Load a model Pose
model = YOLO('yolov8n-pose.pt')  # load a pre-trained model (recommended for training)

# Train the model
results = model.train(data='C:/Users/indigo/Box/UIUC_ACADEMIC/PHD_THESIS/PROJECTS/GAIT_CATTLE/CODES/POSE_MODELV8/dataset/dataset.yaml', epochs=20)

# Validate the model
#metrics = model.val()  # no arguments needed, dataset and settings remembered

and my yaml file are like this: 

# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]

#path: C:/Users/idigi/Box/UIUC_ACADEMIC/PHD_THESIS/PROJECTS/GAIT_CATTLE/CODES/POSE_MODELV8/dataset  # dataset root dir

train:  C:/Users/idigi/Box/UIUC_ACADEMIC/PHD_THESIS/PROJECTS/GAIT_CATTLE/CODES/POSE_MODELV8/dataset/train 
val: C:/Users/idigi/Box/UIUC_ACADEMIC/PHD_THESIS/PROJECTS/GAIT_CATTLE/CODES/POSE_MODELV8/dataset/val 

# Keypoints
kpt_shape: [16, 2]  # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible)

#flip_idx: [0, 2, 1, 4, 3, 6, 5, 8, 7, 10, 9, 12, 11, 14, 13, 16, 15]

# Classes dictionary
names:
  0: cattle_keypoint

thank you,

**Comment by glenn-jocher** [comment]
@benicio22 hi there! 👋 It seems there might be a confusion with how the data is being loaded for training. Your code and YAML configurations look good at first glance. One possible reason for this issue could be related to how the paths are defined or accessed in the training process.

Could you double-check the `data` argument path in your script to ensure it matches exactly with the `dataset.yaml` path? Also, ensure that there's no caching or overriding of paths that might cause the training to pick the validation dataset instead.

A quick tip is to add some logging or print statements in your training script to confirm which datasets are being loaded for training and validation. This can help diagnose if the correct paths are being utilized.

If after checking these, the issue still persists, it might be helpful to share additional details like any console output or errors during the training process. This way, we can provide more targeted assistance. 

Keep us posted!

**Comment by glenn-jocher** [comment]
Hey @benicio22! 😄 From the logs you've shared, it looks like your model is indeed training on the correct datasets with 391 images for training and 100 for validation, as expected. The `train:` and `val:` scans in the log confirm the datasets are loaded properly, and the paths are correct. 

For the specific concern about training on the validation dataset, the output indicates that your model is training on the training dataset and using the validation dataset as intended. The validation process, shown as “Validating runs\pose\train2\weights\best.pt...”, runs after the training epoch, which is normal and expected behavior.

If you are observing unexpected results or behaviors not aligning with this, double-checking the dataset content and the model's output during training and validation could be helpful. Sometimes visualizing some predictions can give insights into what the model is learning. Keep experimenting, and feel free to reach out if you have more questions or updates!

**Comment by benicio22** [comment]
Thanks for answer. So, why my confusion matrix in the train folder has the total of the val images not the train images? And it is not saving my val folder with the outputs? What I got confuse is that while I am running the model in each epochs is showing 100 images (val images). I remember before my model was saving the train confusion matrix (but to be honest I used last year the yolov8)
Thank you

**Comment by glenn-jocher** [comment]
@benicio22 hey there! 😊 

The confusion matrix and your validation (val) image count appearing during training is entirely normal and part of YOLOv8's process. When training, YOLOv8 evaluates on the validation dataset after each epoch to measure model performance. Hence, the mention of 100 images (your val set) during the epochs.

The confusion matrix is generated using the validation dataset for a more accurate representation of how the model might perform on unseen data. It’s expected behavior for it not to tally up with the train dataset size. 

Regarding the saving of outputs in the val folder, YOLOv8 default behavior has evolved, focusing more on streamline training and validation process. If you need to save validation outputs specifically, you might want to check the arguments/options available or custom scripts used previously. 

For saving outputs explicitly, here's a quick reference:
```python
model.val(save_json=True, save_dir='your_desired_path_for_outputs')
```
Replace `'your_desired_path_for_outputs'` with the actual path where you'd like to save those outputs. 

I hope this clears things up! Let me know if you have more questions or if there's anything else you're curious about. Happy modeling! 🚀

**Comment by benicio22** [comment]
Oh Gotcha! Thank you so much.

**Comment by glenn-jocher** [comment]
@benicio22 you're welcome! If you have any more questions or run into any issues, feel free to reach out. Happy coding! 😊
