### ISSUE TITLE
How to perform multiple model training?

### ISSUE THREAD

**Issue by monkeycc** [ultralytics/ultralytics#958]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Want to train multiple models

In order

End of a model

Start with another model

But the following code prompts an error. The graphics card is not enough

```python

model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)
model.train(data="VOC1280n.yaml", epochs=300, imgsz=1280)
model.export(format="onnx")

model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)
model.train(data="VOC640n.yaml", epochs=300, imgsz=640)
model.export(format="onnx")

model = YOLO("yolov8s.pt")  # load a pretrained model (recommended for training)
model.train(data="VOC640s.yaml", epochs=300, imgsz=640)
model.export(format="onnx")

```

**Comment by glenn-jocher** [comment]
@monkeycc The error is most likely due to insufficient GPU memory when loading multiple models in memory at the same time. You can try loading and training one model at a time, and then saving and closing it before moving on to the next model. Here is an example:

```python
# train first model
model = YOLO("yolov8n.pt")
model.train(data="VOC1280n.yaml", epochs=300, imgsz=1280)
model.export(format="onnx")
del model

# train second model
model = YOLO("yolov8n.pt")
model.train(data="VOC640n.yaml", epochs=300, imgsz=640)
model.export(format="onnx")
del model

# train third model
model = YOLO("yolov8s.pt")
model.train(data="VOC640s.yaml", epochs=300, imgsz=640)
model.export(format="onnx")
del model
```

This code loads and trains one model at a time, saves the exported ONNX model, and then deletes the model from memory before moving on to the next one. This should help with the memory issues you are experiencing.

**Comment by monkeycc** [comment]
Thank you for your help

**Comment by pderrenger** [comment]
@monkeycc you're welcome! If you have any more questions or need further assistance, feel free to ask. Good luck with your multiple model training! 😊
