### ISSUE TITLE
Model is too confidently wrong

### ISSUE THREAD

**Issue by w013nad** [ultralytics/ultralytics#975]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/26445256/218764654-c72e53ea-f243-4632-b405-1e59a0d5c0ae.png)

My team has  been working on the yolo series models. Recently, I created my own detect.py to output the 3 most likely classes(rewrote NMS to preserve class likelihoods and do agnostic nms on with highest confidence class). What I noticed is that the model seems unreasonably confident in it's responses. There are very few in between options. 

Take the image here, it is calling a sedan a pickup with 0.78 confidence and sedan barely shows up in the top 3. Likewise, it calls a pickup a sedan with 0.82 confidence. Once again, the pickup class barely shows up.

Are there any ways to alleviate this? 

As an aside, would it be possible for the current validation scripts to return something like MAP Top 5 similar to classification models? And/or allow hierarchical classification i.e. Vehicle:Car:Sedan, Person:Child?

**Comment by sstainba** [comment]
Are you sure that you don't simply have the indexes of the tags switched?  Like... it was trained with a different index than the prediction is using?  At first glance, that seems the most likely issue.

**Comment by pderrenger** [comment]
@sstainba it sounds like the model might be misinterpreting the classes due to incorrectly mapped indexes. This could be causing the model to mislabel objects with high confidence. You may want to double-check the class mapping and ensure that the indexes for the tags are consistent between training and prediction. Additionally, in terms of alleviating this issue, refining the training data, adjusting the model's confidence threshold, or experimenting with different augmentation techniques could potentially help improve the model's accuracy.

Regarding your question about returning MAP Top 5 similar to classification models, the current validation scripts provide insights into model performance, and enabling hierarchical classification would be a useful feature to consider for future development. This could potentially expand the model's applicability across various domains. If you have any additional questions or need further assistance, feel free to ask!
