### ISSUE TITLE
V9e Instance Segmentation Predict feature map activation error  --visualize=True error

### ISSUE THREAD

**Issue by Jaykumaran** [ultralytics/ultralytics#9777]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

[/usr/local/lib/python3.10/dist-packages/ultralytics/utils/plotting.py](https://localhost:8080/#) in feature_visualization(x, module_type, stage, n, save_dir)
   1076             return
   1077     print(x)
-> 1078     _, channels, height, width = x.shape  # batch, channels, height, width
   1079     if height > 1 and width > 1:
   1080         f = save_dir / f"stage{stage}_{module_type.split('.')[-1]}_features.png"  # filename

AttributeError: 'tuple' object has no attribute 'shape'

### Environment

```

PyTorch version: 2.2.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: 14.0.0-1ubuntu1.1
CMake version: version 3.27.9
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-6.1.58+-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.2.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 535.104.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.6
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.6
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      46 bits physical, 48 bits virtual
Byte Order:                         Little Endian
CPU(s):                             2
On-line CPU(s) list:                0,1
Vendor ID:                          GenuineIntel
Model name:                         Intel(R) Xeon(R) CPU @ 2.30GHz
CPU family:                         6
Model:                              63
Thread(s) per core:                 2
Core(s) per socket:                 1
Socket(s):                          1
Stepping:                           0
BogoMIPS:                           4599.99
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear arch_capabilities
Hypervisor vendor:                  KVM
Virtualization type:                full
L1d cache:                          32 KiB (1 instance)
L1i cache:                          32 KiB (1 instance)
L2 cache:                           256 KiB (1 instance)
L3 cache:                           45 MiB (1 instance)
NUMA node(s):                       1
NUMA node0 CPU(s):                  0,1
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Mitigation; PTE Inversion
Vulnerability Mds:                  Vulnerable; SMT Host state unknown
Vulnerability Meltdown:             Vulnerable
Vulnerability Mmio stale data:      Vulnerable
Vulnerability Retbleed:             Vulnerable
Vulnerability Spec rstack overflow: Not affected
Vulnerability Spec store bypass:    Vulnerable
Vulnerability Spectre v1:           Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:           Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] numpy==1.25.2
[pip3] torch==2.2.1+cu121
[pip3] torchaudio==2.2.1+cu121
[pip3] torchdata==0.7.1
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.17.1
[pip3] torchvision==0.17.1+cu121
[pip3] triton==2.2.0
[conda] Could not collect
```

### Minimal Reproducible Example

![image](https://github.com/ultralytics/ultralytics/assets/60032500/a09739be-e075-4215-81fd-5dabfef46ad1)

### Additional

During prediction when --visualize=True, i get this error for Yolov9e.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Jaykumaran hi there! 👋 It seems like you encountered an issue with feature map visualizations in YOLOv9e when using `--visualize=True`. The error message you received `AttributeError: 'tuple' object has no attribute 'shape'` suggests that a tuple was returned where a tensor was expected.

This may occur if the model's forward method was modified or if there's certain customization in the plotting function. To better understand and resolve the issue, could you please confirm whether any modifications were made to the model's code or the `feature_visualization` function itself?

As a quick workaround, you could add a check before the line causing the error to ensure that `x` is a tensor. For example:

```python
if isinstance(x, tuple):
    x = x[0]  # Assuming the tensor of interest is the first element
_, channels, height, width = x.shape
```

Please make sure that this adjustment aligns with your specific use case or model modifications. If the issue persists or you have further details, feel free to share! 🛠️

**Comment by glenn-jocher** [comment]
@Jaykumaran recommend you use the default YOLOv8-seg models which work correctly, i.e.:

yolo predict model=yolov8n-seg.pt visualize=True

<img width="948" alt="Screenshot 2024-04-07 at 21 32 16" src="https://github.com/ultralytics/ultralytics/assets/26833433/73799781-8a9b-4461-b836-9e4ef36425fe">

**Comment by glenn-jocher** [comment]
@Jaykumaran I'm not able to reproduce any issue with YOLOv9c-seg visualize=True:

<img width="979" alt="Screenshot 2024-04-07 at 21 34 19" src="https://github.com/ultralytics/ultralytics/assets/26833433/036acbd5-5796-40fc-9ba7-f81c44eec9fa">

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by glenn-jocher** [comment]
@Jaykumaran we've now been able to reproduce and fixed this bug in https://github.com/ultralytics/ultralytics/pull/12573. Thank you for reporting this error and please let us know if there is anything else we can do to improve!
