### ISSUE TITLE
Is it possible for yolov8 to treat two separate contours as a single instance(object) ?

### ISSUE THREAD

**Issue by Wong-denis** [ultralytics/ultralytics#979]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I use roboflow to annotate my data and generate yolov8 training database. 
However, roboflow can't treat two separate contours as a single object, it always considers them to be two different objects.
 
![Screenshot from 2023-02-15 11-20-40](https://user-images.githubusercontent.com/57944444/218919163-3586943d-5e0f-424d-8c56-db7707aee4d0.png)

Is it possible for yolov8 to treat two separate contours as a single instance(object)?
If it is possible, can anyone tell me how?

**Comment by JustasBart** [comment]
Hi @Wong-denis unfortunately this isn't possible unless if you cross over the wire that's above. The problem is that there is no way to represent what you're describing as a polygon based mask. This would work if you found a way to present an image and a mask image to an AI model and then parse the resulting mask out of that perhaps, but there's no direct way of doing it for yolov5 or yolov8.

Sorry and I hope this helps :rocket:

**Comment by Wong-denis** [comment]
I see. Still, thank you a lot for your quick reply!

**Comment by ryouchinsa** [comment]
Labelme is an open source tool to label polygons and using the Group ID, you can export the polygons which have the same Group ID as a merged polygon.
https://github.com/wkentaro/labelme/issues/888

This script converts the merged polygon into a polygon so that you can train on YOLOv5 and YOLOv8.
https://github.com/ultralytics/JSON2YOLO

```
def merge_multi_segment(segments):
    """Merge multi segments to one list.
    Find the coordinates with min distance between each segment,
    then connect these coordinates with one thin line to merge all 
    segments into one.
    """
```

RectLabel is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel you can select multiple polygons, right click on them, and you can convert them to a merged polygon.

![yolo_polygon](https://user-images.githubusercontent.com/1954306/219925568-58e51f9c-b190-41d5-9900-28a69e0a211a.jpg)

**Comment by pderrenger** [comment]
@ryouchinsa great, thanks for sharing these resources! It's helpful to have options for handling multiple polygons and merging them into a single instance for training with YOLOv8. This kind of preprocessing step can be very valuable in certain scenarios. If you encounter any issues or have further questions, feel free to ask!

**Comment by BAMcGarvin** [comment]
@pderrenger I've seen some of your comments on other posts/questions and using some of your example code has helped me to figure quite a bit out, so thank you in advance. I'm asking this question here but can move it elsewhere if needed... How would I be able to convert a drawn polygon into a max height and max width, as if it were a bounding box rather than a polygon? I have a set of rules that I need to apply but the rules change based on these factors... Thank you :)
