### ISSUE TITLE
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/rm/ultralytics (A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)

### ISSUE THREAD

**Issue by Jojo11111** [ultralytics/ultralytics#9832]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Install

### Bug

I have cloned the ultralytics repository and cd ultralytics , then  'pip install -e .'  and this error occurred.
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/rm/ultralytics
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
![2024-04-07 12-31-48屏幕截图](https://github.com/ultralytics/ultralytics/assets/48509483/2f855226-a023-48b1-a899-1a906e768aa4)

### Environment

CPU: ARM64
OS: ubuntu20.04
python:3.8
pip:20.0.2

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Jojo11111 hello! Thanks for reaching out and for doing a search prior to posting this issue. 😊 It seems like the error you're encountering is due to the absence of a `setup.py` file, which is indeed necessary for installing packages in editable mode with Pip.

Currently, our repository relies on a `pyproject.toml` for package management, which is part of the newer Python packaging standards. For now, you can install the package without the editable flag, directly from the cloned repository:

```bash
pip install .
```

This should install the package without needing to be in editable mode. We understand this might not be ideal for development purposes where package changes are frequent. Rest assured, we're looking into enhancing our setup to support editable installs with `pyproject.toml` in the future.

If development is your primary concern, consider installing the dependencies listed in our `requirements.txt` and working in the cloned directory directly for the time being.

Hope this helps! If you have more questions or run into other issues, feel free to ask.

**Comment by glenn-jocher** [comment]
@Jojo11111 https://github.com/ultralytics/ultralytics/pull/9851 attempts to resolve this bug by updating setuptools to 57.0.0 for PEP 660 compliance. Please git pull the latest repo version after this PR merged and try again.

**Comment by maryaliza** [comment]
Hello, this error still persists, I have pulled the latest merge and double checked the the .toml file which is updated to;
requires = ["setuptools>=57.0.0", "wheel"]

but I still am getting this error:
notebooks/ultralytics$ pip install -e .
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /notebooks/ultralytics
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)

**Comment by glenn-jocher** [comment]
Hello @maryaliza! Thanks for reaching out and for double-checking the `.toml` file. 🤔 It seems like you're still facing issues despite the updates. Could you try upgrading your `pip` version to the latest to see if that helps resolve the issue? Sometimes, having an older version of `pip` can cause these discrepancies. You can upgrade `pip` using the following command:

```bash
pip install --upgrade pip
```

After upgrading, please try installing in editable mode again with:
```bash
pip install -e .
```

Let us know if this resolves your issue or if you're still facing any problems. Happy to help further! 😊

**Comment by maryaliza** [comment]
> Hello @maryaliza! Thanks for reaching out and for double-checking the `.toml` file. 🤔 It seems like you're still facing issues despite the updates. Could you try upgrading your `pip` version to the latest to see if that helps resolve the issue? Sometimes, having an older version of `pip` can cause these discrepancies. You can upgrade `pip` using the following command:
> 
> ```shell
> pip install --upgrade pip
> ```
> 
> After upgrading, please try installing in editable mode again with:
> 
> ```shell
> pip install -e .
> ```
> 
> Let us know if this resolves your issue or if you're still facing any problems. Happy to help further! 😊

Wonderful! Thank you, resolved!

**Comment by glenn-jocher** [comment]
Fantastic to hear that, @maryaliza! 🎉 If you encounter any more questions or bumps along the way, feel free to reach out. Happy coding! 😊
