### ISSUE TITLE
YOLO v8 ERROR

### ISSUE THREAD

**Issue by charlotepencier** [ultralytics/ultralytics#9857]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I have the same issue.

import os

os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

from ultralytics import YOLO
model_path = r"C:\visu_ai\Face_recognition\code\yolov8n-face.pt"

model = YOLO(model_path)
results = model.track(source=0, show=True, tracker = "bytetrack.yaml")

This is my code.

I am getting this error
Traceback (most recent call last):
File "c:\visu_ai\Face_recognition\code\person_track.py", line 9, in
results = model.track(source=0, show=True, tracker = "bytetrack.yaml")
AttributeError: 'YOLO' object has no attribute 'track'
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-Break to quit

My torch version is 2.2 and ultralytics is 8.1

**Comment by glenn-jocher** [comment]
@charlotepencier hey there! 👋 It seems like the key issue here is the AttributeError stating the 'YOLO' object has no attribute 'track'. This might be due to a version mismatch or an outdated version of the Ultralytics package where the `track` function is not available.

As a quick solution, ensure you're using the latest version of the Ultralytics YOLOv8 package, as the `track` method was introduced in recent updates. To update, you can run:

```bash
pip install ultralytics --upgrade
```

Also, please double-check the version of PyTorch (`torch`) installed in your environment. You mentioned having torch version 2.2, which seems to be a typographical error as PyTorch hasn't reached that version number yet. If you meant PyTorch 1.8.2 and Ultralytics 8.1 (assuming version formatting), an update to the latest versions could resolve the issue.

If after updating you still encounter issues, don't hesitate to reach out. We're here to help!
