### ISSUE TITLE
Right img size for training and prediction

### ISSUE THREAD

**Issue by dmddmd** [ultralytics/ultralytics#986]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

My train img size is  3024x4032.
Should I run: `
model.train(data="mydata.yaml", epochs=100, imgsz=3024) or what?`
And is it a problem if my livestream for prediction hasn't the same size?

**Comment by JustasBart** [comment]
Hi @dmddmd generally speaking you want to use the lowest resolution that makes sense, however because 3024x4032 is rather big I would recommend training as maybe 1920 that is something like this:
```
yolo detect train \
data=mydata.yaml \
model='yolov8s.pt' \
epochs=300 \
patience=200 \
imgsz=1920 \
rect=True \
device=0 \
batch=-1
```
But this is totally trivial and will ultimately depend on the size of your objects within the image (You'll need a higher-res model for smaller objects etc...) so you'll have to do some experimentation to find the optimal settings for your dataset.

One advice I could offer you would be to set aside a small dataset ~(100Val/20Train) and just experiment with that for like ~50 Epochs to see what seems to work for you before committing to the full and time consuming training run.

Hope this helps :rocket:

**Comment by RobbStarkAustria** [comment]
My source files have a similar size to yours. The smallest object is at 40x40 pixels.
I reduce to 1024x1024 and leave the aspect ratios the same. This leads to margins on the sides of the pictures, depending on the format.
For me, the recognition works very well despite the reduction.

**Comment by dmddmd** [comment]
Thanks for Your answers.

The reduction will effect the annotations, right?
