### ISSUE TITLE
How resize in yolo impact to model accuracy?

### ISSUE THREAD

**Issue by Krilaria** [ultralytics/ultralytics#9873]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I use YOLOv8X for object detection in photos, and recently I've been wondering about the impact of image size on detection quality. I usually use datasets from Roboflow and apply a resize to 1280x1280 (which results in significantly better performance than the standard resize to 640x640), but the original photos often have aspect ratios far from square, and resizing changes the proportions of objects in the photos. The annotation in the dataset is recalculated for the new photo size, but can changing proportions degrade detection quality? Can I train the model without resizing the input photos? Is it necessary to resize on Roboflow if I can simply specify the parameter imgsz=1280 during training?

**Comment by glenn-jocher** [comment]
@Krilaria hey! 👋 Great question!

Resizing images in YOLOv8 does impact model accuracy due to changes in object proportions and potential loss or distortion of details, especially for non-square aspect ratios. Your observations on better performance with 1280x1280 over 640x640 are aligned with the general principle that higher resolution can provide more details for the model, leading to improved detection quality.

However, resizing to maintain aspect ratio (e.g., using padding) could mitigate the issue of changing object proportions. While it's acceptable to train without resizing, using `imgsz=1280` for training (and inference) can help the model adapt better to higher resolutions, especially if your deployment scenario involves similar image sizes.

To answer your Roboflow question, it's not strictly necessary to resize images on Roboflow if you're setting `imgsz=1280` during training. This parameter effectively guides the model to expect and handle that specific input size, regardless of the original dimensions.

In essence, resizing can influence detection quality, but smart resizing and training practices can help preserve or even enhance model performance. Hope that helps!
