### ISSUE TITLE
ValueError: Only support at least one signature key. when export yolov8  Edge TPU model format 

### ISSUE THREAD

**Issue by abdelmageed95** [ultralytics/ultralytics#989]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

[Tensorflow Edge TPU](https://coral.ai/docs/edgetpu/models-intro/#quantization) requires the model to be quantized into [**INT8**](https://www.tensorflow.org/lite/performance/post_training_quantization#integer_only) format 

 when I export with yolov8 
`!yolo export model=yolov8n.pt format=edgetpu`

I got a saved model with **.pb**, **quantized float32** ,and  **float 16** models which are not compatible with [Coral TPU](https://coral.ai/docs/edgetpu/models-intro/#compatibility-overview) 

![image](https://user-images.githubusercontent.com/83831812/219081305-a1e58723-a229-44de-a587-02a508f28525.png)

I tried to quantize the yolov8 saved_model using the following code 

![image](https://user-images.githubusercontent.com/83831812/219078887-b430a097-b6a0-43f0-8143-a115641bd84c.png)

I got a value error saying

**_ValueError: Only support at least one signature key._**

![image](https://user-images.githubusercontent.com/83831812/219079450-61d30c8f-5840-40b4-9f3c-5fdda3535aa8.png)

so I found that there is no signature for the model 

![image](https://user-images.githubusercontent.com/83831812/219080723-231129f5-908f-40a6-9b41-af9241a66274.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@abdelmageed95 additional TF exports are being supported in https://github.com/ultralytics/ultralytics/pull/1014, but it appears that flex ops in TF exported models are conflicting with Edge TPU export at the moment.

**Comment by glenn-jocher** [comment]
@MathieuxHugo EdgeTPU exports work correctly in latest ultrlaytics versions. Just use:

```
pip install -U ultralytics

yolo export format=edgetpu
```

**Comment by 35grain** [comment]
@glenn-jocher correctly as in the quantization issue is also resolved?

**Comment by glenn-jocher** [comment]
@35grain I don't have any Edge TPU devices to run inference from, but it seems like the most up to date info there is at https://github.com/PINTO0309/onnx2tf/issues/244

**Comment by MathieuxHugo** [comment]
When I ran it with tflite, it didn't detect anything neither but you can use it with yolov8 like you would with the pt weights :
```
from ultralytics import YOLO
import cv2
model = YOLO("best_full_integer_quant_edgetpu.tflite")

image = cv2.imread('test2.jpg')

results=model.predict(image)
```

But it is slower than when I run it on my cpu.

**Comment by 35grain** [comment]
> When I ran it with tflite, it didn't detect anything neither but you can use it with yolov8 like you would with the pt weights :
> But it is slower than when I run it on my cpu with the ".pt" weights (trained from yolov8 nano).

Unfortunately, I cannot confirm this as I'm still not getting any detections with the edgetpu using the default configuration. 
As a side note for anyone affected, using the latest version of torch 2.0.0 currently causes `Illegal instruction (core dumped)` on the Raspberry Pi 4, the relevant issue is here: https://github.com/pytorch/pytorch/issues/97226

**Comment by pderrenger** [comment]
@35grain Thanks for the update! 🙏 It seems like there might be some compatibility issues there. You could also try experimenting with different model variants and hyperparameters to see if that improves detection performance on the USB Accelerator. Regarding the torch issue, it's great that you're staying informed about potential compatibility issues. If you have any other questions or concerns, feel free to ask!

**Comment by sarar1997** [comment]
Yes, you are right but I have tried almost everything to fix it but I couldnt manage it. I have trained the Yolov8m model. I have exported to edgetpu and tflite models. all of their inouts and outputs are like 

1 input(s):
[  1 416 416   3] <class 'numpy.float32'>

1 output(s):
[   1   48 3549] <class 'numpy.float32'>


but I need in this format:
1 input(s):
[  1 300 300   3] <class 'numpy.uint8'>

4 output(s):
[ 1 10  4] <class 'numpy.float32'>
[ 1 10] <class 'numpy.float32'>
[ 1 10] <class 'numpy.float32'>
[1] <class 'numpy.float32'

I couldnt run it in Python or in  Android studio. 

How can I convert it in a proper format ? 
(Thank you for answering me. )

**Comment by glenn-jocher** [comment]
@sarar1997 hi there! It looks like there may be a mismatch between your requirements and the model's output format. You're aiming to have a model with distinct output tensors that represent different aspects of detection, such as locations (bounding boxes), classifications, and confidence scores.

The YOLOv8 model typically outputs a single tensor that encapsulates all this information, hence a different output structure than the one you're expecting.

The conversion to a `uint8` input is a part of the quantization process, and the model output structure change requires a different post-processing pipeline. This is usually defined in the model's architecture and training script rather than simply the conversion process.

Here's what you should consider:

1. Ensure that you understand the YOLOv8's expected input and output formats detailed in our documentation. YOLO models typically have a single output tensor that concatenates all prediction information, which you would then need to parse after inference.

2. If you require a specific output format, you may need to adapt the model's post-processing code or even modify the model architecture accordingly.

3. If you're not deeply familiar with the model architecture and conversion process, this could be quite complex and may require assistance from someone with experience in model optimization and TensorFlow Lite conversion.

4. For the issue of converting inputs to `uint8` and ensuring multiple output tensors in the correct format, you'd typically adjust your training and exporting pipeline to include quantization and define the multiple outputs in TensorFlow.

Since your need seems specific and involves detailed model and conversion understanding that's beyond quick troubleshooting, you might want to either:
- Adjust your pipeline to match the existing YOLOv8 output format and parse the results accordingly, or
- Seek assistance from a machine learning engineer who specializes in model conversions and quantization or inquire in TensorFlow's community resources.

Remember to keep a detailed record of the changes you try and the errors you encounter, as this will be very useful in troubleshooting the process. 🛠️ If you require further assistance on the Ultralytics side, please provide detailed error logs and conversion steps via the YOLOv8 issue tracker.

**Comment by sarar1997** [comment]
but when I try to run it on python or in Android, It says 

ValueError: Expected a model with 2 or 4 output tensors, found 1.

My problem is runing the tflite model which is converted from yolo. and I keep searching a video or document that runing a tflite model which converted from yolov8 but there isnt. We have the coreml model as well converted from the same yolov8 model. That one works on ios. the same kod the same yolov8 model but when we convert to tflite model. It doesnt work in any platform. 

do you have any page that you can direct me that I can load my custom tflite model and I can see the prediction. because I have a code which works for other tflite models but doest work on the tflite models which converted from yolov8. 

Thanks for help.

**Comment by glenn-jocher** [comment]
@sarar1997 i understand that it can be quite frustrating when you have a YOLOv8 model that works in one format (like CoreML for iOS) but encounters issues when converted to TensorFlow Lite (TFLite) for other platforms.

The error you're experiencing suggests that the app or code you're using to run the TFLite model expects a specific output tensor structure. YOLO models, including YOLOv8, typically provide all detection outputs in a single tensor, whereas the error message implies your code expects separate tensors for each output component (bounding boxes, classifications, etc.).

To address this, there might be a couple of options:

1. **Modify your inference code**: Update the code that's loading and running the TFLite model to correctly interpret the YOLOv8 model's output tensor.

2. **Check for post-processing code**: YOLO model outputs often require additional post-processing to convert from raw predictions into meaningful results (such as bounding boxes and class scores). Ensure that this post-processing step is correctly implemented.

As for resources, the best place to find information about using Ultralytics models with TensorFlow Lite would be within the official documentation. Currently, if you're looking for direct guidance on how to proceed, I would recommend the following steps:

- Review the YOLOv8 documentation specifically for the export command and TFLite conversion to ensure your process is aligned with expected practices.
- Make sure you understand the post-processing required for YOLOv8 TFLite model outputs. This often involves interpreting the single output tensor to extract bounding boxes, object classes, and confidence scores.
- Compare the expected output format of the YOLOv8 model with other TFLite models that work with your code. This might help you identify the discrepancy and adapt the code accordingly.
- Engage with the community on forums or platforms where developers discuss TFLite model deployment. Developers who have worked with YOLO models in TFLite might have shared their experiences and code.

For hands-on assistance, consider using the GitHub issue tracker to report the problem you're facing in detail, including the exact error messages and steps you've taken. The community or the maintainers might be able to provide more precise guidance or point you towards existing resources or examples that match your needs.

Please remember that while it's helpful to find examples or templates, running custom models often requires a firm understanding of both the model's output structure and the inference code used to process these outputs.
