### ISSUE TITLE
Need for an iPython Notebook that generates best.pt model not more than 10 MB

### ISSUE THREAD

**Issue by ghnikien** [ultralytics/ultralytics#9901]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Greetings! I have come to realize that the iPython Notebook that I currently use generates a model file size of 21MB, no matter what quantization and pruning I did.

Do you all have any ipynb files that generate a best.pt model file size under 10MB? Or do I have still another ways to reduce the model file size by modifying the current IPYNB?

I only involved human detection (only 1 class) in my code.

Thank you

**Comment by glenn-jocher** [comment]
@ghnikien hello! 😊 Reducing the model file size, especially under 10MB, while maintaining accuracy can indeed be a bit challenging, but here are a couple of strategies you might find helpful:

1. **Model Simplification**: Start with a simpler or smaller version of the model, if you haven't already. For instance, using yolov8n (the nano version) as your base model can significantly reduce the size.
   
2. **Model Quantization**: You've mentioned trying quantization, but combining it with a simpler model as suggested above might yield better results. Ensure to experiment with `half` precision (`model.model.half()`) which converts weights to FP16. 

3. **Knowledge Distillation**: This involves training a smaller "student" model to replicate the performance of the larger "teacher" model. It can significantly reduce model size while preserving accuracy.

4. **Custom Training**: Adjust the architecture by reducing the number of layers or filters, tailored to detect humans. Since you're working with just 1 class, this could be quite effective.

Here's a basic example how you might start with a simpler model and apply half precision:
```python
from ultralytics import YOLO

# Load model
model = YOLO('yolov8n.pt')

# Apply half precision
model.half() 

# Proceed with training...
```

Before and after these steps, don't forget to validate the performance of your model to ensure that your accuracy remains acceptable.

For specific iPython Notebook examples, we might not have a ready-made notebook that hits under 10MB out of the box, as this often requires a tailored approach as mentioned. But starting with a simpler base, focusing on quantization practices, and maybe even adjusting the architecture might be your best bet!

Hope this gives you a good starting point. Happy coding!

**Comment by ghnikien** [comment]
Greetings!

Would it be possible to reduce the file size of the YOLOV8 Model by having it be an "n" model size type? I am planning to incorporate in my Raspberry Pi 4. Would the n model size type be appropriate for this tracking?

Thank you!

**Comment by glenn-jocher** [comment]
Hi there! 😊

Absolutely! Opting for the "n" model size type, like `yolov8n`, can significantly reduce your model file size, making it a suitable choice, especially for hardware with limited resources like the Raspberry Pi 4. Here's how you can load an "n" model:

```python
from ultralytics import YOLO

model = YOLO('yolov8n.pt')
```

And yes, the "n" model size is indeed appropriate for deployment on a Raspberry Pi 4 for tracking tasks. It's designed to be lightweight, offering a good balance between speed and accuracy for edge devices.

Happy tracking with your Pi 4!
