### ISSUE TITLE
Wrong classify dataset structure documentation ?

### ISSUE THREAD

**Issue by stormsson** [ultralytics/ultralytics#9911]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I believe that  [the classify index.md page](https://github.com/ultralytics/ultralytics/blob/main/docs/en/datasets/classify/index.md) is a bit misleading / confusionary: 

it is shown as an example the torchvision folder structure:

```
  root/
  |-- class1/
  |   |-- img1.jpg
  |   |-- ...
  |-- class2/
  |   |-- img1.jpg
  |   |-- ...
  |
  |-- ...
```

and after that, the cifar-10 structure 
(that contains `/train` and `/test` under the root folder)

I might be wrong, but this to me seems misleading because using torchvision structure with:
`model.train(data="../datasets/dataset-classifier", ...)`

causes the following error

```
RuntimeError: Dataset '../datasets/dataset-classifier' error 
❌ [Errno 2] No such file or directory: /[full_path_here]/datasets/dataset-classifier/train
```

so to me it seems that the `/train` and `/test` folders are mandatory, and the original example would seem not working

**Comment by glenn-jocher** [comment]
Hi there! Thanks for bringing this to our attention. 🌟

It seems there might indeed be some confusion arising from the documentation on the classification dataset structure. Let's clarify this. 

For YOLOv8 classification tasks, the dataset directory should indeed include separate `/train` and `/test` (and optionally `/val`) subdirectories under the root dataset directory, each containing class folders with their respective images. 

Here's the correct structure:
```
root/
|-- train/
|   |-- class1/
|   |   |-- img1.jpg
|   |   |-- ...
|   |-- class2/
|   |   |-- img1.jpg
|   |   |-- ...
|
|-- test/
|   |-- class1/
|   |   |-- img1.jpg
|   |   |-- ...
|   |-- class2/
|   |   |-- img1.jpg
|   |   |-- ...
```

The confusion might arise when transitioning from using torchvision datasets to the YOLOv8 structure since torchvision might not always require separate `/train` and `/test` directories. For YOLOv8, having distinct directories for training and testing/validation is essential for proper data management and training workflows.

We will review the documentation to ensure it reflects the necessity of this structure more clearly. Your feedback is invaluable in helping us improve. 🙏

Let us know if there's anything else we can help with!

**Comment by stormsson** [comment]
thank you @glenn-jocher  , I opened a PR here following your answer https://github.com/ultralytics/ultralytics/pull/9926

**Comment by stormsson** [comment]
Sorry, just to be sure 
> For YOLOv8 classification tasks, the dataset directory should indeed include separate /train and /test (and optionally /val)

Is this correct? 
from other examples I see that the folder structure used is `/train` and `/val` and optionally `/test` ; which one of the two is the minimal/suggested one ?

**Comment by glenn-jocher** [comment]
Hello! 👋

Yes, you're correct, and thanks for asking for clarification. The minimal/suggested directory structure for YOLOv8 classification tasks typically includes `/train` and `/val` subdirectories. The `/test` directory is indeed optional and can be used if you have a separate dataset for final model evaluation. So, both structures are valid, but at a minimum, you should aim for:

```
root/
|-- train/
|   |-- class1/
|   |   |-- img1.jpg
|   |   |-- ...
|   |-- class2/
|   |   |-- img1.jpg
|   |   |-- ...
|
|-- val/
|   |-- class1/
|   |   |-- img1.jpg
|   |   |-- ...
|   |-- class2/
|   |   |-- img1.jpg
|   |   |-- ...
```

Hope this clears things up! Let me know if there's anything else you need. 😊
