### ISSUE TITLE
error with classify task in torch=2.1

### ISSUE THREAD

**Issue by zmhcasmy** [ultralytics/ultralytics#9979]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I want to use yolov8 to do an image classification task, it is right when in torch 1.10.0 ,but I get an error: 'Resize' object has no attribute 'max_size',I guess it's a problem with torch version 2.1, but I need torch version 2.1, so what should I do to modify the code to solve the problem?Thanks very much!

### Additional

code:
from ultralytics import YOLO
model = YOLO('../best.pt')
if __name__=='__main__':
    results=model('/opt/custom/01.jpg')

**Comment by glenn-jocher** [comment]
Hey there! It seems like the issue you're encountering is indeed related to changes in the PyTorch `Resize` operation from version 1.10.0 to 2.1. 😊 One way to address this is by adjusting your image preprocessing steps to ensure compatibility with PyTorch 2.1.

A potential workaround is to manually resize your images to the expected input size of your model before passing them to YOLO for the classification task. Here's a quick example using PIL for image resizing:

```python
from PIL import Image
from ultralytics import YOLO

# Load your model
model = YOLO('../best.pt')

# Manually resize the image
img_path = '/opt/custom/01.jpg'
img = Image.open(img_path).resize((640, 640))  # Adjust the size (640, 640) as necessary

# Perform classification
if __name__ == '__main__':
    results = model(img)
```

Make sure to adjust the resize dimensions `(640, 640)` according to your specific model requirements. This should help you bypass the 'Resize' object issue while using PyTorch 2.1.

Hope this helps you! If you have any more questions, feel free to ask. 🚀

**Comment by zmhcasmy** [comment]
@glenn-jocher thanks for you answer. But it doesn't work when i adjust my image preprocessing steps,it get the same error.The pretrain weight that I use  is yolov8n-cls.pt and this is my code and error:
```
from ultralytics import YOLO
from PIL import Image
# Load a model

model = YOLO('/opt/custom/ultralytics-main/runs/classify/train2/weights/best.pt')  # load a custom model
img_path = '/opt/custom/ultralytics-main/ultralytics/datasets/02.jpg'
img = Image.open(img_path).resize((224, 224))
# Predict with the model
if __name__ == '__main__':
    results = model(img)  # predict on an image
```
```
error:
    results = model(img)  # predict on an image
  File "/opt/custom/ultralytics-main/ultralytics/engine/model.py", line 176, in __call__
    return self.predict(source, stream, **kwargs)
  File "/opt/custom/ultralytics-main/ultralytics/engine/model.py", line 452, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/opt/custom/ultralytics-main/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/opt/custom/ultralytics-main/ultralytics/engine/predictor.py", line 244, in stream_inference
    im = self.preprocess(im0s)
  File "/opt/custom/ultralytics-main/ultralytics/models/yolo/classify/predict.py", line 39, in preprocess
    is_legacy_transform = any(
  File "/opt/custom/ultralytics-main/ultralytics/models/yolo/classify/predict.py", line 40, in <genexpr>
    self._legacy_transform_name in str(transform) for transform in self.transforms.transforms
  File "/usr/lib/python3.8/site-packages/torchvision-0.16.1-py3.8-linux-aarch64.egg/torchvision/transforms/transforms.py", line 364, in __repr__
    detail = f"(size={self.size}, interpolation={self.interpolation.value}, max_size={self.max_size}, antialias={self.antialias})"
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Resize' object has no attribute 'max_size'
```

**Comment by glenn-jocher** [comment]
Hey there! 👋 It seems like the issue persists even with the adjusted approach. The error message you're encountering is related to an attribute mismatch in the PyTorch `Resize` operation, which might be due to the version inconsistency between PyTorch and torchvision.

To tackle this, could you please ensure that your torchvision version is compatible with PyTorch 2.1? Sometimes these issues arise from version mismatches. Another quick check would be to directly use a tensor instead of a PIL Image and bypass any potential preprocessing issues. Here's a revised snippet:

```python
from ultralytics import YOLO
import torchvision.transforms as transforms
from PIL import Image

# Load a model
model = YOLO('/opt/custom/ultralytics-main/runs/classify/train2/weights/best.pt')  # load a custom model

# Adjust preprocessing using PyTorch transforms
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
])
img_path = '/opt/custom/ultralytics-main/ultralytics/datasets/02.jpg'
img = Image.open(img_path)
img_tensor = transform(img)

# Predict with the model
if __name__ == '__main__':
    results = model(img_tensor.unsqueeze(0))  # predict on an image tensor
```

Please try updating your torchvision to the latest version that is compatible with PyTorch 2.1. If the issue persists, considering the compatibility between the specific versions of PyTorch, torchvision, and Utralytics YOLO might help us dive deeper into the underlying problem.

Hope this helps! Let me know how it goes. 🚀

**Comment by 1343464520** [comment]
when i use Yolov8-cls to do the classification task, an error has occurred:
from ultralytics import YOLO
import cv2
import numpy as np
import os

def loop_img_file(folder_path, sv_path):

    # 获取文件夹内所有文件名
    images = [img for img in os.listdir(folder_path) if
              img.endswith(".png") or img.endswith(".jpg") or img.endswith(".jpeg")]

    # 读取图片
    for img_name in images:
        img_path = os.path.join(folder_path, img_name)
        image = cv2.imread(img_path)
        results = model(task='detect', mode='predict', source=image, imgsz=(64, 64), line_width=3, show=False,
                        save=False, device='cuda')
        if (results[0].probs.top1 == 0):
            cv2.imwrite(sv_path + results[0].names[0] + '/' + img_name, image)
        elif (results[0].probs.top1 == 1):
            cv2.imwrite(sv_path + results[0].names[1] + '/' + img_name, image)
        else:
            cv2.imwrite(sv_path + results[0].names[2] + '/' + img_name, image)


if __name__ == '__main__':
    # classify
    # # Load a model
    # model = YOLO('yolov8m-cls.yaml').load('yolov8m-cls.pt')  # build from YAML and transfer weights
    # # Train the model
    # model.train(data='D:/ultralytics/my_data/matter_reg_split/', epochs=100, imgsz=(64, 64))
    #
    # metrics = model.val(imgsz=(64,64), batch=1)  # evaluate model performance on the validation set

    # ##############################################################
    # 模型加载
    model = YOLO('runs/classify/train/weights/best.pt')
    # 图片文件夹路径
    folder_path = r'D:\ultralytics\runs\detect\predict25\crops\slag'
    sv_path = 'D:/picture_13/'
    # 遍历文件夹
    loop_img_file(folder_path, sv_path)

    # path = model.export(format='onnx', opset=12)  # 导出一定不要修改这里参数
    print("————————————————————————————————————————————————")

the error log is as following:

Traceback (most recent call last):
  File ".\YOLOv8_matter_reg.py", line 44, in <module>
    loop_img_file(folder_path, sv_path)
  File ".\YOLOv8_matter_reg.py", line 18, in loop_img_file
    results = model(task='detect', mode='predict', source=image, imgsz=(64, 64), line_width=3, show=False,
  File "D:\ultralytics\ultralytics\engine\model.py", line 176, in __call__
    return self.predict(source, stream, **kwargs)
  File "D:\ultralytics\ultralytics\engine\model.py", line 452, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "D:\ultralytics\ultralytics\engine\predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "D:\software\anaconda\envs\yolov8\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "D:\ultralytics\ultralytics\engine\predictor.py", line 244, in stream_inference
    im = self.preprocess(im0s)
  File "D:\ultralytics\ultralytics\models\yolo\classify\predict.py", line 40, in preprocess
    self._legacy_transform_name in str(transform) for transform in self.transforms.transforms
AttributeError: 'NoneType' object has no attribute 'transforms'
------------------------------------------------------------------------------------
Then, i find when the first time inference is ok, self.transforms.transforms is not None, but the the second time entered the loop, the error has occurred, self.transforms.transforms is None.

Please help, thanks!

**Comment by glenn-jocher** [comment]
Hey there! 👋 It looks like you're encountering an issue where the `transforms` attribute becomes `None` after the first inference loop. This might be due to how the model or its transformations are being handled within the loop.

A quick workaround could be to reload the model inside the loop for each image. This ensures that all model attributes are reset correctly for each inference. Here's a modified version of your loop:

```python
def loop_img_file(folder_path, sv_path):
    images = [img for img in os.listdir(folder_path) if img.endswith((".png", ".jpg", ".jpeg"))]

    for img_name in images:
        model = YOLO('runs/classify/train/weights/best.pt')  # Reload model for each image
        img_path = os.path.join(folder_path, img_name)
        image = cv2.imread(img_path)
        results = model(task='detect', mode='predict', source=image, imgsz=(64, 64), line_width=3, show=False, save=False, device='cuda')
        
        if results[0].probs.top1 == 0:
            cv2.imwrite(sv_path + results[0].names[0] + '/' + img_name, image)
        elif results[0].probs.top1 == 1:
            cv2.imwrite(sv_path + results[0].names[1] + '/' + img_name, image)
        else:
            cv2.imwrite(sv_path + results[0].names[2] + '/' + img_name, image)
```

This change might impact performance due to reloading the model multiple times, but it should help bypass the error you're facing. If this resolves the issue, it might be worth investigating deeper into how the model's state is being altered in your original loop. Let me know how it goes! 😊

**Comment by 1343464520** [comment]
Thank you for your reply. i have solved the issue. My task is classification, but i set the task to "detect"，so the error occurred😅



---Original---
From: "Glenn ***@***.***&gt;
Date: Mon, May 20, 2024 10:06 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ultralytics/ultralytics] error with classify task in torch=2.1(Issue #9979)




 
Hey there! 👋 It looks like you're encountering an issue where the transforms attribute becomes None after the first inference loop. This might be due to how the model or its transformations are being handled within the loop.
 
A quick workaround could be to reload the model inside the loop for each image. This ensures that all model attributes are reset correctly for each inference. Here's a modified version of your loop:
 def loop_img_file(folder_path, sv_path):     images = [img for img in os.listdir(folder_path) if img.endswith((".png", ".jpg", ".jpeg"))]     for img_name in images:         model = YOLO('runs/classify/train/weights/best.pt')  # Reload model for each image         img_path = os.path.join(folder_path, img_name)         image = cv2.imread(img_path)         results = model(task='detect', mode='predict', source=image, imgsz=(64, 64), line_width=3, show=False, save=False, device='cuda')                  if results[0].probs.top1 == 0:             cv2.imwrite(sv_path + results[0].names[0] + '/' + img_name, image)         elif results[0].probs.top1 == 1:             cv2.imwrite(sv_path + results[0].names[1] + '/' + img_name, image)         else:             cv2.imwrite(sv_path + results[0].names[2] + '/' + img_name, image)
 
This change might impact performance due to reloading the model multiple times, but it should help bypass the error you're facing. If this resolves the issue, it might be worth investigating deeper into how the model's state is being altered in your original loop. Let me know how it goes! 😊

**Comment by glenn-jocher** [comment]
Hey there! 😊

Great to hear that you've resolved the issue! Indeed, setting the correct task type is crucial. Thanks for updating us, and don't hesitate to reach out if you encounter any more questions or need further assistance. Happy coding!
