### ISSUE TITLE
Result.probs comes out to be 'None'

### ISSUE THREAD

**Issue by shahnupur1901** [ultralytics/ultralytics#999]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I'm training yolo v8 for instance segmentation and later predicting the test images.
But, while trying to analyze the 'results', I can't get the class probabilities corresponding to each bounding box generated in the image because result.probs comes out to be 'None'.

![image](https://user-images.githubusercontent.com/67814929/219279391-50e2ccaa-628a-42df-a177-0d4455c177ef.png)
![image](https://user-images.githubusercontent.com/67814929/219279461-e0dd66c1-8802-4412-b5fd-8f362574ea58.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Laughing-q** [comment]
@shahnupur1901 hi `probs` is for classification task so it's None when you're using a segmentation model.

**Comment by shahnupur1901** [comment]
Okay, so how can I check the class probabilities for segmentation then?

**Comment by Laughing-q** [comment]
@shahnupur1901 
```python
result.boxs.conf
```

**Comment by shahnupur1901** [comment]
But this gives the confidence score for a bbox, not which class label it's
been assigned to right?

**Comment by Laughing-q** [comment]
@shahnupur1901 `result.boxs.conf` is the score corresponding to the category, `result.boxs.cls` is the class label

**Comment by shahnupur1901** [comment]
Okay, thank you so much!

**Comment by Laughing-q** [comment]
@shahnupur1901 closing the issue, feel free to reopen it if you still have related issues. :)

**Comment by AmanS369** [comment]
I have the Same issue , but i want to know the ID of the result()

the output is as 
```cls: tensor([2.])
conf: tensor([0.3135])
data: tensor([[9.3082e+02, 2.3281e+02, 9.5793e+02, 2.5121e+02, 3.1348e-01, 2.0000e+00]])
id: None
is_track: False
orig_shape: (540, 960)
shape: torch.Size([1, 6])
xywh: tensor([[944.3744, 242.0108,  27.1078,  18.4054]])
xywhn: tensor([[0.9837, 0.4482, 0.0282, 0.0341]])
xyxy: tensor([[930.8205, 232.8081, 957.9283, 251.2135]])
xyxyn: tensor([[0.9696, 0.4311, 0.9978, 0.4652]])```

**Comment by glenn-jocher** [comment]
@AmanS369 hey there! 😊 It looks like you're interested in accessing the ID of the tracked objects. In the current output you've shared, the `id` field is `None`, which typically means that tracking was not enabled during inference. To enable tracking and obtain unique IDs for each detected object, you'll need to use the tracking functionality provided by YOLOv8. Here's a quick example on how to do that:

```python
from ultralytics import YOLO

# Load your model
model = YOLO('path/to/your/model.pt')

# Enable tracking
results = model.track('path/to/your/video.mp4')
```

This should provide you with an `id` for each detected object if tracking is successfully applied. Keep in mind that tracking is more commonly used with video inputs rather than single images to track the movement of objects across frames. If you have any more questions or need further assistance, feel free to ask!

**Comment by fraborg99** [comment]
isn't there a difference between class confidence and box confidence? I mean that I expect two confidence scores, one for the detection and thew other one would be the argmax between the possible classes for the classification part.
